### ISSUE TITLE
ActiveSupport::Deprecation not obeying config.active_support.deprecation

### ISSUE THREAD

**Issue by martijnversluis** [rails/rails#40470]
### Steps to reproduce

Create barebones Rails application

```
rails new deprecation-warning-logging -M --skip-action-mailbox --skip-action-text -O --skip-active-storage -C -S --skip-spring -J --skip-turbolinks -T --skip-system-test --skip-bootsnap --api --skip-webpack-install
```

Set ActiveSupport deprecation behavior to `:notify`:

```
-  # Print deprecation notices to the Rails logger.
-  config.active_support.deprecation = :log
+  # Send deprecation notices to registered listeners.
+  config.active_support.deprecation = :notify
```

Create a file `config/initializers/raise_deprecation_warning.rb`:

```
ActiveSupport::Deprecation.new('my_version', 'my_gem').deprecation_warning('my_method', 'Do not use it')
```

1. run `bundle exec rails s`
1. run `bundle exec rails c` and execute: `ActiveSupport::Deprecation.new('my_version', 'my_gem').behavior`

### Expected behavior

1. The deprecation warning should not show up in the terminal output
1. The Rails console output should show a Proc defined on `activesupport-6.0.3.4/lib/active_support/deprecation/behaviors.rb:37`, because the behavior fo `:notify` is defined there

### Actual behavior

1. The deprecation warning still shows in the server output:

```
=> Booting Puma
=> Rails 6.0.3.4 application starting in development
=> Run `rails server --help` for more startup options
Executing development.rb
DEPRECATION WARNING: my_method is deprecated and will be removed from my_gem my_version (Do not use it) (called from <top (required)> at /Users/martijn/***/***/deprecation-warning-logging/config/environment.rb:5)
Puma starting in single mode...
* Version 4.3.6 (ruby 2.7.0-p0), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://127.0.0.1:3000
* Listening on tcp://[::1]:3000
Use Ctrl-C to stop
```

1. The Rails console output shows the `:stderr` behavior is used:

```
irb(main):001:0> ActiveSupport::Deprecation.new('my_version', 'my_gem').behavior
=> [#<Proc:0x00007fa07187edd0 /Users/martijn/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/deprecation/behaviors.rb:20 (lambda)>]
```

So it seems to me the deprecation is not picking up the correct behavior...

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.7.0p0

**Comment by composerinteralia** [comment]
Setting `config.active_support.deprecation =` is equivalent to setting `ActiveSupport::Deprecation.behavior =`:

https://github.com/rails/rails/blob/c8f9a627d9b766f7f7dab79206e66fdfe0af0f3d/activesupport/lib/active_support/railtie.rb#L33-L35

This affects the behavior of the class method `ActiveSupport::Deprecation.deprecation_warning`, but not the instance method. Each instance of `ActiveSupport::Deprecation` gets its own `@behavior` instance variable that can be set independently.

https://github.com/rails/rails/blob/c8f9a627d9b766f7f7dab79206e66fdfe0af0f3d/activesupport/lib/active_support/deprecation/behaviors.rb#L67

**Comment by mlhamel** [comment]
I understand it only affect the class method but is there a way to change the default behaviour of every instances ?
