### ISSUE TITLE
Deploying to Heroku error Command "webpack" not found

### ISSUE THREAD

**Issue by deucemac** [rails/rails#40474]
### Expected behavior

When I try to deploy to Heroku, I receive this error.  ```Command "webpack" not found.```
I've tried solutions like looking into yarn and installing a package.json in the root.  I'm not completely sure but I feel the problem could lie in my package.json needing additional information regarding 'webpack'.  

here is the error in the console:

<img width="720" alt="Screen Shot 2020-10-28 at 1 28 13 PM" src="https://user-images.githubusercontent.com/61918013/97475510-b966bd80-1923-11eb-8098-d0c93596a028.png">

### System configuration
**Rails version**:6.0.3.2

**Ruby version**: 2.7.1

**Comment by dixpac** [comment]
This [thread](https://github.com/rails/webpacker/issues/512) might help you

**Comment by rafaelfranca** [comment]
Please use https://discuss.rubyonrails.org/ for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
