### ISSUE TITLE
ArgumentError (You tried to define an enum named "availabilty_type" on the model "Product", but this will generate a instance method "regular?", which is already defined by another enum.

### ISSUE THREAD

**Issue by shahana-aym** [rails/rails#40535]
Saw many issues relating to this problem but all seem to come down to the use of the same value for different enums within the same model, which can be resolved with the use of _suffix or _prefix.

In my case, there is no duplicate in my model. I tried giving different names but still same issue.
### System configuration
**Rails version**: 6

**Ruby version**: 2.7.2

**Comment by composerinteralia** [comment]
https://github.com/rails/rails/blob/c8f9a627d9b766f7f7dab79206e66fdfe0af0f3d/activerecord/lib/active_record/enum.rb#L269-L270

This error can happen when another enum in the same model defines the same value (which you have indicated isn't the case for you):

```rb
  enum other_enum: [:regular]
  enum availability_type: [:regular]
```

Or when one enum accidentally defines the same value twice (it might be worth double checking whether you have done this):

```rb
  enum availability_type: [:regular, :regular]
```

If you are seeing the error for another reason, then that sounds like a bug. In order to confirm the bug, can you provide a reproduction script or sample application that reproduces the problem?

**Comment by mfa777** [comment]
Hi, I got same case but I found the reason. My code was written like this:

```
enum other_enum: [:regular, :others]
# validates with wrong arguments
validates [:username, :birthday], presence: true
```

It will raise a error which issue title showed. It looks like wrong `validates` method call causes a wrong error hint.

**Comment by mfa777** [comment]
Hi, I got same case but I found the reason. My code was written like this:

```
enum other_enum: [:regular, :others]
# validates with wrong arguments
validates [:username, :birthday], presence: true
```

It will raise a error which issue title showed. It looks like wrong `validates` method call causes a wrong error hint.

**Comment by carellen** [comment]
Same for me - I've used the wrong method to define an alias(`:alias_method` instead of `:alias_attribute`)  and got this error...

```
enum status: { active: 0, cancelled: 9 }
# wrong alias definition
alias_method :title, :name
```

Change to `:alias_attribute` has solved the problem.

**Comment by moveson** [comment]
Same problem here. I used `alias` instead of `alias_attribute` and it caused the same error complaining about the enum. This is quite misleading.

**Comment by composerinteralia** [comment]
Are you able to share a reproduction script?

**Comment by carellen** [comment]
> Are you able to share a reproduction script?

```
# <MyModel name:string, status:integer>
class MyModel < ApplicationRecord
  enum status: { pending: 0, confirmed: 1, cancelled: 9 }
  alias_method :title, :name
end
```

**Comment by feapaydin** [comment]
I got the same issue when I accidentally typed `validates_presece_of` instead of `validates_presence_of` (missing letter 'n' as typo).
Caused me spending some time trying to figure what's wrong with the enums, turns out it's because of a completely different typo.

Not sure what's the relation there but just wanted to report.

```ruby
class Shop < ApplicationRecord
  encrypts :access_token

  enum webhook_status: { inactive: 0, active: 1 }, _prefix: true

  belongs_to :remote_app

  validates_presece_of :remote_id # missing n is here
  validates_presence_of :access_token
  validates_uniqueness_of :remote_id, scope: :remote_app_id
end
```

**Comment by carsoncole** [comment]
Same problem here. Had an error in setting attribute values in a Class, which triggers

`You tried to define an enum named "status" on the model "Reservation", but this will generate a instance method "unconfirmed?", which is already defined by another enum. (ArgumentError)`

`class Reservation < Application Record

    enum :status, { unconfirmed: 0, pending_pickup: 1, picked_up: 2, missing: 3, cancelled: 4, archived: 99 }, default: :unconfirmed
    attribute :country, :string, default: 'United States'
    attribute :is_routed, :boolean, true

end
`
I don't have any other enums defined, and in this case by attribute for `is_routed` is missing `default:`, which when fixed results in the error disappearing.

**Comment by itsNikolay** [comment]
The problem here is your DSL not mixed up well with enum validation

Example:

```ruby
# in the same file
class User
  enum :status: [:created, :removed]
end

# in the same file
require Rails.root + 'spec/rails_helper' # rspec mixins own method which are not mix well with enum validation
describe User
  it { User.new } # got the error
end
```

so you need to move RSpec DSL in another file to load `User` ahead `DSL`

```ruby
# user.rb
class User
  enum :status: [:created, :removed]
end

# user_spec.rb  (separate file)
require Rails.root + 'spec/rails_helper'
describe User
  it { User.new } # got the error
end
```

**Comment by oliwoodsuk** [comment]
I triggered the same error by making the below mistake when mixing up classes and modules.

```ruby
# The below mistake of trying to define classes as concerns
# Gave me this error: You tried to define an enum named "status" on the model "Pitch", but this will generate a instance method "status_draft?", which is already defined by another enum. (ArgumentError)

class Pitch::Colours
    extend ActiveSupport::Concern
end

class Pitch::Votes
    extend ActiveSupport::Concern
end


# Then when I fixed the mix-up as per the below, the enum error disappeared:

class Pitch
    module Colours
        extend ActiveSupport::Concern
    end
end

class Pitch
    module Votes
        extend ActiveSupport::Concern
    end
end
```

**Comment by rstueven** [comment]
This gave me the "You tried to define an enum..." error:

```
  enum notif_type: [:manual, :pregame, :period_end, :final]
# ... lots of lines deleted ...
  validates :media, file_content_type: {
    allow: MEDIA_ACCEPT.join(","),
    if: -> { media.attached? }
  }
```

When I changed `join` to `split` - which is what I wanted anyway - the error went away.

It's *really* confusing when a syntax error gets flagged as an error in an unrelated part of the file.

**Comment by joallard** [comment]
Ran into this as well, it obscured a class-level error where I was trying to link a model that can't be found, eg:

```
class Item < ApplicationRecord
  enum status: [:created, :removed]
  has_many :goop  # doesn't exist!
```

and so it obscures the original exception which is quite tricky to diagnose.

(7.0.4.3)

**Comment by joallard** [comment]
@composerinteralia Could we kindly get some guidance on how to proceed with this bug that is for the moment closed but seems to have affected many users in a tricky way?

**Comment by zzak** [comment]
If someone has a [reproducible test case](http://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case), I recommend opening a new bug since this issue is nearly 3 years old now.

**Comment by capripot** [comment]
Maybe there is a confusion around the two different syntax offered by `enum`, single & multiple enum definition, I got confused myself.

For instance this define an enum for `status` and `category` attributes:

```ruby
enum status: [:open, :close], category: [:recall, :new]
```

With `prefix:` introduced in Rails 7, you could think that you could do that:
```ruby
enum status: [:open, :close], prefix: true
```

When in fact, this just attempts to define a second enum for the `prefix` attribute.

Solution is to change to the single enum definition syntax
```ruby
enum :status, [:open, :close], prefix: true
```

or use the underscored option with the multiple enum definition syntax (which defines only one here)
```ruby
enum status: [:open, :close], _prefix: true
```

Not sure but we might want to change the framework to reserve `prefix` and `suffix` words, but it would effectively removing them as possible attributes for enum, and that may be undesirable.

**Comment by composerinteralia** [comment]
@joallard sorry, I don't work on Rails anymore so I can't help with this.

**Comment by capripot** [comment]
@joallard
The original error reported in this issue might be resolved by explicitly erroring out when given something else than an array, which would point the developer in the right direction. See PR #44471 and Issue https://github.com/rails/rails/issues/44457

It's merged in main but didn't get promoted to be released yet, I think it should be!

**Comment by danbernier** [comment]
I just ran into this on rails v7.1.5.1, on a model where I was adding its first `enum` (with the correct syntax), and a `before_validation` hook with the wrong syntax: 

```
class MyModel < ApplicationRecord
  enum :status, { pending: 0, active: 1, closed: 2 }, default: :pending

  # With this wrong syntax, I get a version of the above error:
  # before_validate { :do_a_thing }

  # With this correct validation syntax, I get no errors:
  before_validation :do_a_thing
end
```

I've been trying to reproduce it in a single-file `app.ru`, but so far no luck.

I did, however, learn that I can reproduce the error in my model by just raising an error instead of mis-configuring hooks:

```
class MyModel < ApplicationRecord
  enum :status, { pending: 0, active: 1, closed: 2 }, default: :pending
  raise 'any error'
end
```

With that `enum` and `raise`, I get "ArgumentError: You tried to define an enum named "status" on the model "MyModel", but this will generate a instance method "pending?", which is already defined by another enum."

If I comment out the `enum`, I see the `'any error'` raised.

**Comment by foxmerald** [comment]
Can confirm that this has still not been resolved in Rails 8. 
Just ran into the exact same error using Rails `v8.0.2`.

My code:
```ruby
class Task < ApplicationRecord
  enum :status, {
    working_on_this: 0,
    closed: 1
  }

  validates :owner_id, on: :update # <-- forgot to add "presence: true, "
end
```

And got the same wrong error:

```sh
app/models/task.rb:2:in '<class:Task>': You tried to define an enum named "status" on the 
model "Task", but this will generate a instance method "working_on_this?", which is already 
defined by another enum. (ArgumentError)
```

**Comment by bradical** [comment]
Had an interesting occurrence of this that brought me here: an issue initializing ActiveStorage that resulted in this enum error on the next attempt to load the class.

The specific error is an auth error in AWS S3 storage resulting from the validator
```
	from /Users/bradleywagner/.rbenv/versions/3.3.7/lib/ruby/gems/3.3.0/gems/activestorage-7.2.2.1/lib/active_storage/attached/model.rb:107:in `has_one_attached'
	from /Users/bradleywagner/Dev/Clive/clive-api/app/models/smart_content_version.rb:57:in `<class:SmartContentVersion>'
```

which corresponded to validator line (line 107) after the class definition line (line 57):

```
  has_one_attached :image
```

... that is below my `enum`s:

```
  enum :content_type, [:image_link, :html, :button_link, :content_form], validate: true
  enum :display_rule_operator, [:and_operator, :or_operator], validate: { allow_nil: true }
```

And then the next time the class attempts to load, I get the `enum` error mentioned here:


```
`raise_conflict_error': You tried to define an enum named "content_type" on the model "SmartContentVersion", but this will generate a instance method "image_link?", which is already defined by another enum
```

**Comment by callmesangio** [comment]
I was bitten by this recently as well, after some research I found this comment which explains precisely what's going on: https://github.com/rails/rails/issues/44842#issuecomment-1090850955

**Comment by ngocbuildxuan** [comment]
Seem errors don't relate enum 👍.
