### ISSUE TITLE
Rails 6.0.3 breaks has_many without FK

### ISSUE THREAD

**Issue by ArneBouillon** [rails/rails#40543]
### Steps to reproduce
Rails 6.0.3 (and 6.1rc1 as well) seems to have changed the present scope when entering a `has_many` scope. The code below is a toy version of the code that is having this issue, but it boils down to using a join-only association (since `readers` is otherwise not present in the SQL - however, I don't think that is related to the issue) that first calls `unscope(:where)` to be able to eager load a `has_many` association without having a foreign key. Since 6.0.3, there is no `where` present on entry of the lambda, but an FK check is still inserted into the final SQL. This means I can no longer escape the FK, and the association no longer works.

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :readers, force: true do |t|
    t.integer :free_time
  end

  create_table :books, force: true do |t|
    t.integer :length
  end
end

class Reader < ActiveRecord::Base
  has_many :joined_recommended_books, -> do
    unscope(:where).where('books.length < readers.free_time * 10')
  end, class_name: 'Book'
end

class Book < ActiveRecord::Base; end

class HasManyTest < Minitest::Test
  def test_has_many
    Reader.eager_load(:joined_recommended_books).to_a
  end
end
```

### Expected behavior
In Rails 6.0.2.2 and lower, `unscope(:where)` would get rid of the foreign key check, and the test wouldn't error. The SQL generated is
```sql
SELECT "readers"."id" AS t0_r0, "readers"."free_time" AS t0_r1, "books"."id" AS t1_r0, "books"."length" AS t1_r1 FROM "readers" LEFT OUTER JOIN "books" ON (books.length < readers.free_time * 10)
```

### Actual behavior
The code generates
```sql
SELECT "readers"."id" AS t0_r0, "readers"."free_time" AS t0_r1, "books"."id" AS t1_r0, "books"."length" AS t1_r1 FROM "readers" LEFT OUTER JOIN "books" ON "books"."reader_id" = "readers"."id" AND (books.length < readers.free_time * 10)
```
(note the `"books"."reader_id" = "readers"."id"`), and gives an error as that foreign key does not exist.

Is this a Rails issue, or was I relying on a bug or undefined behaviour? If the latter, is there any supported way to define an association without FK's that can be joined (to avoid N+1)?

### System configuration
**Rails version**:
`>=6.0.3`

**Ruby version**:
`2.7.2`

**Comment by tahsin352** [comment]
Is it valid sql for `on` clause?
```sql
ON (books.length < readers.free_time * 10)
```

**Comment by ArneBouillon** [comment]
I'm pretty sure it is, it's a join condition like any other.

**Comment by ArneBouillon** [comment]
We managed to find a workaround in our specific case, so I'll close this issue. However, the described behaviour was still broken in Rails 6.0.3, intended or not.
