### ISSUE TITLE
ActionCable 6.1.0rc1 issue

### ISSUE THREAD

**Issue by rusikf** [rails/rails#40548]
After deploy action cable error:

> NoMethodError: undefined method `with_indifferent_access' for nil:NilClass                                                                    
/home/deploy/staging/shared/bundle/ruby/2.7.0/gems/actioncable-6.1.0.rc1/lib/action_cable/engine.rb:33:in `block (2 levels) in <class:Eng
ine>'                                                                                                                                         
/home/deploy/staging/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.0.rc1/lib/active_support/lazy_load_hooks.rb:73:in `instance_eval'   
/home/deploy/staging/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.0.rc1/lib/active_support/lazy_load_hooks.rb:73:in `block in execute_
hook'                                                                                                                                         
/home/deploy/staging/shared/bundle/ruby/2.7.0/gems/activesupport-6.1.0.rc1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_co
ntrol'                                                                                                                                        
/home/deploy/staging/shared/bundle/ruby/2.

Rails - latest 6.1.0.rc1 in Gemfile

[Looks related to this ](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#rails-application-config-for-return-value-no-longer-supports-access-with-string-keys)

**Comment by rafaelfranca** [comment]
Is this is a new application or an existing application? If if it in an assisting application, it looks like your action cable config doesn't have a configuration to the environment you are loading. Could you please check if that is not the case?

**Comment by Pr0p1k** [comment]
@rafaelfranca, I don't know about action cable config, but it's definitely a regression, because our integration tests started failing with 6.1.0.rc1 with the same error.

**Comment by jonathanhefner** [comment]
The reason for the difference is that #37850 changed `config_for` to return `nil` instead of an empty Hash when the config file does not contain configuration for the specified environment.  Given the purpose of #37850, I think that behavior makes sense, but it is potentially breaking.  If that's causing too much pain, we could make the old behavior configurable, and then eventually deprecate it.  But for now, I've fixed Action Cable in #40563.

**Comment by link60** [comment]
Hello, 
I just upgrade my project to 6.1.0-rc1 and I've got the same issue when running tests. 
(undefined method with_indifferent_access' for nil:NilClass […] action_cable/engine.rb:33) 

Here is my default config/cable.yml : 
```
development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: production
```

I added some debug traces to railties-6.1.0-rc1/lib/rails/application.rb:241 **config_for** method : 
```
config_path : /Users/me/Documents/dev/server-rails6/config/cable.yml  
env : "test"
all_configs : {"development"=>{"adapter"=>"async"}, "test"=>{"adapter"=>"test"}, "production"=>{"adapter"=>"redis", "url"=>"redis://localhost:6379/1", "channel_prefix"=>"production"}}
config : nil
Rails.application.config_for(config_path) : nil
```

By changing the keys as symbols in cable.yml as follows 
```
:development:
  adapter: async

:test:
  adapter: test

:production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: production
``` 
then all seems fine. 

```
config_path : /Users/me/Documents/dev/server-rails6/config/cable.yml  
env : "test"
all_configs : {:development=>{"adapter"=>"async"}, :test=>{"adapter"=>"test"}, :production=>{"adapter"=>"redis", "url"=>"redis://localhost:6379/1", "channel_prefix"=>"production"}}
config : {"adapter"=>"test"}
Rails.application.config_for(config_path) : {"adapter"=>"test"}
```

**Comment by rafaelfranca** [comment]
If that is the case `config_for` is broken. Looking in the code the names should be symbols:

https://github.com/rails/rails/blob/868866c1fd7f6c79fd48d90febb1fd02a83380e1/railties/lib/rails/application.rb#L246

Can you investigate why it is not?

**Comment by link60** [comment]
> If that is the case `config_for` is broken. Looking in the code the names should be symbols:
> 
> https://github.com/rails/rails/blob/868866c1fd7f6c79fd48d90febb1fd02a83380e1/railties/lib/rails/application.rb#L246
> 
> Can you investigate why it is not?

I feel confused, my investigation led me to find Psych to be obsolete (2.2.4). 
Now with the latest version, **symbolize_names** works perfectly 🙌

**Comment by anamba** [comment]
Adding psych 3.2.0 to my Gemfile did not help me, but symbolizing the environment names in cable.yml did.
