### ISSUE TITLE
Schema Cache regression in Active Record 6.1.0.rc1

### ISSUE THREAD

**Issue by janko** [rails/rails#40553]
### Steps to reproduce

In a gem I'm maintaining, I'm running a test suite against a dummy Rails app, which migrates up in `setup` and migrates down in `teardown`. I've managed to extract the issue into the following self-contained script:

```rb
require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Base.transaction do
  ActiveRecord::SchemaMigration.create_table
  p ActiveRecord::SchemaMigration.table_exists?
  ActiveRecord::SchemaMigration.all.to_a
  raise ActiveRecord::Rollback
end

ActiveRecord::Base.transaction do
  ActiveRecord::SchemaMigration.create_table
  p ActiveRecord::SchemaMigration.table_exists?
  ActiveRecord::SchemaMigration.all.to_a
  raise ActiveRecord::Rollback
end
```

### Expected behavior

I expect the `schema_migrations` table to be re-created in both transactions, and the script to complete without errors. This is currently the behaviour in Active Record 6.0.

### Actual behavior

The `schema_migrations` table creation gets skipped in the 2nd transaction, because Active Record thinks the table already exists, even though the creation of the table was rolled back in the 1st transaction. The reason is that `#table_exists?` asks Active Record's schema cache, which still kept a reference of the `schema_migrations` table from the 1st transaction, so it returns `true` without even making a query.

This then causes `ActiveRecord::SchemaMigration.all.to_a` in the 2nd transaction to fail, because the `schema_migrations` table doesn't exist.

### System configuration
**Rails version**: 6.1.0.rc1

**Ruby version**: 2.7.2

**Comment by eugeneius** [comment]
This bisects to https://github.com/rails/rails/commit/c5ecc338e863e771adcbcd87d5c23ae5e7ca7894: before that commit, `ActiveRecord::SchemaMigration#table_exists?` bypassed the schema cache.

I'm not sure if enabling the schema cache in https://github.com/rails/rails/commit/c5ecc338e863e771adcbcd87d5c23ae5e7ca7894 was intentional, it looks more like a code cleanup. @kamipo WDYT?

**Comment by kamipo** [comment]
Enabling the schema cache was intentional, like all other models behave so.
But `create_table` shouldn't be affected by the side effect. I'll fix it.

**Comment by janko** [comment]
Thank you for a quick fix!

I understand that the main purpose of schema cache is to cache parsed out tables and columns, but I was surprised that `#table_exists?` is also using the schema cache instead of always making a query. The [commit](https://github.com/rails/rails/commit/5b82f50feff3c80cbe7a7ae33b078baa1515150a) goes all the way back to 2011, though it doesn't any context unfortunately.
