### ISSUE TITLE
Rollback of parent destruction when children association throws :abort on third level

### ISSUE THREAD

**Issue by dmitry** [rails/rails#40550]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'activesupport', path: '../../activesupport/'
  gem 'activemodel', path: '../../activemodel/'
  gem 'activerecord', path: '../'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.references :user_account
  end

  create_table :user_accounts, force: true do |t|
    t.references :profile, null: false
  end

  create_table :profiles, force: true do |t|
  end
end

class User < ActiveRecord::Base
  belongs_to :user_account,
             dependent: :destroy
end

class UserAccount < ActiveRecord::Base
  belongs_to :profile,
             dependent: :destroy
  has_one :user,
          dependent: :destroy
end

class Profile < ActiveRecord::Base
  has_one :user

  before_destroy prepend: true do
    throw :abort
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    user = User.create!(user_account: UserAccount.new(profile: Profile.new))

    assert_equal 1, User.count
    assert !user.destroy
    assert_equal 1, User.count
  end
end

```

### Expected behavior

User and UserAccount should not be destroyed.
Any `DELETE`s should not be `COMMIT`ed but to be `ROLLBACK`.
`#destroy` should return `false`.

### Actual behavior

User and UserAccount is deleted from DB.
`#destroy` returns `true`.

### System configuration
**Rails version**: 5.x and 6.0 (and 6.1.0rc2)
**Ruby version**: any

### Related
- https://github.com/rails/rails/issues/32376
- https://github.com/rails/rails/issues/32022

**Comment by dmitry** [comment]
An issue happens because `belongs_to` association destruction is being called after_destroy, and currently there are no way to pass `ActiveRecord::Rollback` (which is the `throw :abort` does). Current solution is to raise some other exception, like `raise ActiveRecord::RecordInvalid`, see more: https://github.com/rails/rails/issues/33192. It will raise an error until the method caller, so you have to catch it by yourself. Would be great to fix this issue, so the thrown `:abort` `belongs_to` is going to be catched and rollback everything.

**Comment by dmitry** [comment]
More on this topic: https://github.com/rails/rails/pull/17227#issuecomment-59449385

**Comment by dmitry** [comment]
@kamipo can you please check this issue?

**Comment by intrip** [comment]
I'll take a look at the issue and try to figure out a fix.

**Comment by dmitry** [comment]
@intrip I have found that it may happen because `has_one` or `belongs_to` (can't remember) has transaction block with empty rescue, which means `throw :abort` exception are not going to be rethrown again.

**Comment by intrip** [comment]
@dmitry #41602 fixes the issue, turns out was just a 1-liner.
/cc @kamipo

**Comment by dmitry** [comment]
@intrip for some reason, if I do:

```
    before_destroy prepend: true do
      unless destroyable?
        errors.add(:base, :undeletable)
        raise ActiveRecord::RecordInvalid.new(self)
      end
    end
```

Then I can get an errors of the record afterwards.

But if I do with the fixed version and `throw :abort`

```
    before_destroy prepend: true do
      unless destroyable?
        errors.add(:base, :undeletable)
        throw :abort
      end
    end
```

I'm getting an empty `record.errors` afterwards. Somewhere it clears all the errors after throwing an `:abort`.

**Comment by intrip** [comment]
@dmitry thanks for pointing this out!

I've edited the script in this issue and by replacing `throw(:abort)` with `raise ActiveRecord::RecordInvalid.new(self)` and what surprised me the most was that the exception was raised outside of the callback leading to an error, from the DOCS the RecordInvalid error should be `rescued` automatically: https://edgeguides.rubyonrails.org/active_record_callbacks.html#halting-execution

I think this is also a separate issue 🤔 do you agree?
/cc @zzak @p8 

Anyways can you make new issue with a repro script? Would make much easier debugging the issue.

Also feel free to ping me in order to take a look at it when done.

**Comment by intrip** [comment]
I think [this](https://github.com/rails/rails/issues/40550#issuecomment-879110553) is basically a docs issue, in particular [this part](https://edgeguides.rubyonrails.org/active_record_callbacks.html#halting-execution) is not clear:

*"Any exception that is not ActiveRecord::Rollback or ActiveRecord::RecordInvalid will be re-raised by Rails after the callback chain is halted. Raising an exception other than ActiveRecord::Rollback or ActiveRecord::RecordInvalid may break code that does not expect methods like save and update (which normally try to return true or false) to raise an exception."*

It describes "ActiveRecord::Rollback" such as it works in the same way as "ActiveRecord::RecordInvalid" but actually it's incorrect: whilst "ActiveRecord::Rollback" is never re-raised "ActiveRecord::RecordInvalid" is re-raised, except for "save/update" methods.
Do you think it makes sense to make this part of the docs clearer?

/cc @p8 @dmitry
