### ISSUE TITLE
preventing_writes? doesn't work in test environment

### ISSUE THREAD

**Issue by alpaca-tc** [rails/rails#40559]
### Steps to reproduce

1. Turn off `ActiveRecord::Base.legacy_connection_handling`
2. Use `ApplicationRecord.connects_to()`
3. include `ActiveRecord::TestFixtures`
4. Create record from inside `ApplicationRecord.connected_to(role: :reading)` block. 

https://gist.github.com/alpaca-tc/23d658d28581fddecf3b593580f9caa4

### Expected behavior

raise `ActiveRecord::ReadOnlyError`.

### Actual behavior

Nothing was raised.

### System configuration
**Rails version**: 6.1.0.rc1

**Ruby version**: 2.7.1

---

I think that the cause is  that `#replica?` now returns false because of `ActiveRecord::TestFixtures` overwritten the pool config for reading.

`preventing_writes?` checks `replica?` at the first.
https://github.com/rails/rails/blob/b60838b0ac7a9ba8ef26ef7a6abce70fbcf84f15/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L122

`ActiveRecord::TestFixtures` removes `replica: true` option by overwriting pool config.
https://github.com/rails/rails/blob/b60838b0ac7a9ba8ef26ef7a6abce70fbcf84f15/activerecord/lib/active_record/test_fixtures.rb#L219

**Comment by alpaca-tc** [comment]
@eileencodes I would like your opinion on this issue 😄 🙏 Is this intentional?

**Comment by eileencodes** [comment]
Thanks for the report! No this isn't intentional and revealed there's a relatively major bug in prevent writes handling. I'm working on a fix.

**Comment by alpaca-tc** [comment]
@eileencodes It seems that rails6.1 have been broken yet 😭 Please try to run gist code 👀

**Comment by alpaca-tc** [comment]
I found new related bug [gist](https://gist.github.com/alpaca-tc/f4335960b312e026808712a7f43a7947). 
I think that the abstract class that the own connection not established shouldn't swap `preventing_writes` because it can't handle [`owner_name`](https://github.com/rails/rails/pull/40615/files#diff-460f4e7973c5dd945c51d24df5b0173961190d3645f4e2585fd3003fa1fc0ff7R128).

I'll try to fix them.
