### ISSUE TITLE
Duplicated intermediate records on bidirectional accepts_nested_attributes_for with many-to-many association

### ISSUE THREAD

**Issue by r7kamura** [rails/rails#40560]
### Steps to reproduce

1. Define many-to-many association
2. Define bidirectional `accepts_nested_attributes_for`
3. Create record with associated records attributes
4. Then intermediate records (team_memberships in this example) will be duplicated

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'activerecord', '6.0.3.4'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(
  adapter: 'sqlite3',
  database: ':memory:'
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true

  create_table :teams, force: true

  create_table :team_memberships, force: true do |t|
    t.integer :team_id
    t.integer :user_id
    t.index %i[team_id user_id]
  end

  create_table :posts, force: true do |t|
    t.string :title, null: false
    t.integer :user_id
    t.index :user_id
  end
end

class Team < ActiveRecord::Base
  has_many :team_memberships
  has_many :users, through: :team_memberships
end

class User < ActiveRecord::Base
  has_many :team_memberships
  has_many :teams, through: :team_memberships
  has_many :posts

  accepts_nested_attributes_for :posts
end

class TeamMembership < ActiveRecord::Base
  belongs_to :team
  belongs_to :user
end

class Post < ActiveRecord::Base
  belongs_to :user

  accepts_nested_attributes_for :user
end

class BugTest < Minitest::Test
  def test_association_stuff
    team = Team.create!
    user = User.create!(
      posts: [
        Post.new(title: 'dummy title')
      ],
      team_ids: [team.id]
    )
    assert_equal 1, user.teams.count
  end
end
```

### Expected behavior

Expect all tests pass.

### Actual behavior

```
  1) Failure:
BugTest#test_association_stuff [-:73]:
Expected: 1
  Actual: 2

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration

**Rails version**: 6.0.3.4

**Ruby version**: 2.7.2

I confirmed that there is no problem on Rails 5.2.4.4 and 6.1.0.rc1.

**Comment by r7kamura** [comment]
Maybe https://github.com/rails/rails/pull/38394 is relevant because this issue appears to be fixed on 6.1.0.rc1.

**Comment by yahonda** [comment]
Looks like this behavior had been introduced by #38166 and addressed by #39771 in master branch. #38166 change backported to 6-0-stable branch via https://github.com/rails/rails/commit/e019a964871e9cd9ca8d433cc955993d6829d9f1 between v6.0.2 and v6.0.3.

**Comment by yahonda** [comment]
Forgot to mention that #39771 has been backported to 6-0-stable via https://github.com/rails/rails/commit/2d6a726dcb3320ff021c05f3d908adbb2b2e335f but not released yet. Actually, I do not know if newer version of Rails 6.0.z will be released or not.

**Comment by eugeneius** [comment]
Yes, this was fixed in https://github.com/rails/rails/pull/39771. If there's a 6.0.4 release, it will be included.

**Comment by r7kamura** [comment]
Thanks @yahonda and @eugeneius. I tried 6-0-stable and it worked fine 👍
