### ISSUE TITLE
Controller test error on new scaffolds - RoR 6.0.3.4

### ISSUE THREAD

**Issue by bjpcjp** [rails/rails#40564]
### Steps to reproduce
````rails g scaffold <scaffoldname> name:string && rails db:migrate````
### Expected behavior
````$rails test```` results in zero errors on newly-created scaffolds

### Actual behavior
<scaffoldname>_controller_test.rb:8:in `test': wrong number of arguments (given 1, expected 2) (ArgumentError)

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.7.1p83

**Comment by hahmed** [comment]
Hi @bjpcjp could you let us know the command you ran to generate the scaffold?

**Comment by bjpcjp** [comment]
Hi @hahmed I used a default generator followed by a db migration (and updated the reproduce notes, above):
''''$rails g scaffold <scaffoldname> name:string && rails db:migrate`````

**Comment by tahsin352** [comment]
i run this and works for me
```ruby
rails g scaffold HighScore game:string score:integer && rails db:migrate RAILS_ENV=test
rails test
```

**Comment by composerinteralia** [comment]
I was also unable to reproduce this. I ran:

```
rails new testing123
cd testing123
bin/rails g scaffold User name:string
bin/rails db:migrate
bin/rails test
```
All the tests passed.

**Comment by bjpcjp** [comment]
Given this feedback, I decided to blow away my entire Ruby & infrastructure and start from scratch. (I was planning to upgrade to Ubuntu 20.04 anyway.) 
Post-update, the error disappears on Ruby 2.7.0 and Rails 6.0.3.4. So I'm going to close the ticket. TY everyone...
