### ISSUE TITLE
undefined method deprecate when using rubygems.org/gems/rails/versions/6.1.0.rc1

### ISSUE THREAD

**Issue by la-ruby** [rails/rails#40575]
### Steps to reproduce
I was trying the `rails dbconsole` command today and got an `undefined method deprecate`  error.

```
cd /tmp/
uname
ruby --version # ruby 2.7.2p137
rails --version # Rails 6.1.0.rc1
rails new example --database=postgresql
cd example/
./bin/rails console # works
./bin/rails dbconsole # error
```

[gist containing terminal output](https://gist.github.com/la-ruby/6ebeaa165408a5433b5add6bc21d5a98)

### Expected behavior
should land in a database prompt

### Actual behavior
Error: undefined method `deprecate' for Rails::DBConsole:Class.
rails aborted!

### System configuration

```
$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
$ rails --version
Rails 6.1.0.rc1
```

**Comment by eugeneius** [comment]
Thanks for reporting this! I restored the missing require in https://github.com/rails/rails/commit/bcb63fcaa89a17c3f8c65680b4e21134cebaf843 and backported the fix to 6-1-stable in https://github.com/rails/rails/commit/033c7cdfaced6523499dbd15e881131492ee077b.
