### ISSUE TITLE
Generated schema.rb from SQLite migration causes type mismatch doing db:setup on a MySQL server

### ISSUE THREAD

**Issue by sjieg** [rails/rails#40583]
# Steps to reproduce

Migration file
```
class AddContainers < ActiveRecord::Migration[6.0]
  def change
    create_table :containers do |t|
      t.string 'name'
    end
    add_reference :containers, :container, foreign_key: true
  end
end
```

1. Run the migration on an sqlite adapter
2. Run the migration on an mysql adapter

### Expected behavior

Both migrations to generate the same `schema.rb` file.

### Actual behavior

sqlite schema.rb:
```
 create_table "containers", force: :cascade do |t|
    t.string "name"
    t.integer "container_id"
    t.index ["container_id"], name: "index_containers_on_container_id"
 end
 add_foreign_key "containers", "containers"
```

mysql scehma.rb
```
create_table "containers", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci", force: :cascade do |t|
  t.string "name"
  t.bigint "container_id"
  t.index ["container_id"], name: "index_containers_on_container_id"
end
add_foreign_key "containers", "containers"
```

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**:  2.6.6p146

### Issue description

In our deployment process, we create a Rails container with an SQlite database to run the unit tests on. Also locally during development we use SQlite. So generally, the schema.rb file is generated with the SQLite adapter active.

When deploying to the server we use a MySQL server. The problem occurs only first time creating a new database. When running `rails db:setup` an error occurs:

> ```ActiveRecord::MismatchedForeignKey: Column `container_id` on table `containers` does not match column `id` on `containers`, which has type `bigint`. To resolve this issue, change the type of the `container_id` column on `containers` to be :bigint.```

Pretty straightforward and not terribly hard to fix. It did make me think that the generated `schema.rb` should be database independent, _unless database specific options are given during the migrations_.

**Comment by tahsin352** [comment]
According to the [6.0 docs](https://api.rubyonrails.org/v6.0.0/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_reference) the default is :bigint, so, please change container_id column type to `:bigint`

**Comment by sjieg** [comment]
This ticket actually represent a pending PR. Not sure what the normal process is for that.
