### ISSUE TITLE
"If you load both jquery_ujs and rails-ujs, use rails-ujs only." when `rails-ujs` imported twice

### ISSUE THREAD

**Issue by tai2** [rails/rails#40584]
### Steps to reproduce

You use two JS bundles on a page and both of them import `rails-ujs`.
In addition to that, that page exposes `jQuery` in the global space.

```js
// bundle_a.js
import { csrfToken } from 'rails-ujs'
...
```

```js
// bundle_b.js
import { csrfToken } from 'rails-ujs'
...
```

```html
<!-- page.html.erb -->
<script src="jquery-3.5.1.min.js"></script>
<script src="bundle_a.js" />
<script src="bundle_b.js" />
```

### Expected behavior

* No runtime error
* You can import `rails-ujs` in each JS bundle
* You can use `csrfToken()` in each JS bundle

### Actual behavior

`page.html.erb` crush with a runtime error which says `'If you load both jquery_ujs and rails-ujs, use rails-ujs only.`

The line throws this error is here: https://github.com/rails/rails/blob/53331b478d32e42a8155414379b2edbe4277a3a4/actionview/app/assets/javascripts/rails-ujs/start.coffee#L13-L15

### System configuration
**Rails version**:
5.2.4.3

**Ruby version**:

2.6.5

**Comment by tai2** [comment]
I guess moving these 5 lines under `Rails.start` function mitigates this problem.

https://github.com/rails/rails/blob/53331b478d32e42a8155414379b2edbe4277a3a4/actionview/app/assets/javascripts/rails-ujs/start.coffee#L13-L17

However, this change corrupts apps that uses `jQuery.rails` without calling `Rails.start`.

**Comment by tai2** [comment]
This behavior was from https://github.com/rails/rails/commit/9df747c9f018448a08c298b54ccc59e010f7dd0c

**Comment by tahsin352** [comment]
I remove the jquery and its working properly
```js
<%= javascript_pack_tag 'bundle_a' %>
<%= javascript_pack_tag 'bundle_b' %>
```

**Comment by tai2** [comment]
Yes, of course. It means you cannot use rails-ujs with jquery(or you can use it a limited way).
