### ISSUE TITLE
Get wrong url when accessing active_storage files in a rails app deployed under subdirectory.

### ISSUE THREAD

**Issue by khiav223577** [rails/rails#40582]
I tried to deploy my Rails App under subdirectory, but cannot access the uploaded files.

### Steps to reproduce

1. Setup default host with subdirectory in `application.rb`
```rb
Rails.application.routes.default_url_options[:host] = 'http://example.com/my_subdirectory'
```

2. Setup active_storage and upload a photo
```rb
class Report < ApplicationRecord
  has_one_attached :cover_photo
end

report.cover_photo.attach(io: File.open('/path/to/file'), filename: 'file.jpg')
```

3. Go to the url it generated.

```rb
Rails.application.routes.url_helpers.url_for(report.cover_photo)
# => "http://example.com/my_subdirectory/rails/active_storage/blobs/xxxxxxxxxxx/file.jpg"
```

4. It will be redirected to DiskController with wrong url.

### Expected behavior

Expected to be redirected to `http://example.com/my_subdirectory/rails/active_storage/disk/xxxxxxxx/file.jpg?....`

### Actual behavior

It is redirected to `http://example.com/rails/active_storage/disk/xxxxxxxx/file.jpg?....`.

`my_subdirectory` is missing.

### System configuration
**Rails version**:
Rails 5.2.4.3

**Ruby version**:
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]

**Comment by tahsin352** [comment]
I tested with this and works.
```ruby
Rails.application.routes.default_url_options[:host] = {'protocol':'http', 'host':'example.com', 'script_name':'/my_subdirectory'}
```

**Comment by khiav223577** [comment]
> I tested with this and works.
> 
> ```ruby
> Rails.application.routes.default_url_options = {'protocol':'http', 'host':'example.com', 'script_name':'/my_subdirectory'}
> ```

Thanks, it works.

The following is my setting:
```rb
uri = URI.parse(Settings.api_server_host)
Rails.application.routes.default_url_options = {
  protocol: uri.scheme,
  host: uri.host,
  port: uri.port,
  script_name: uri.path
}
```
