### ISSUE TITLE
rails dbconsole for SQL server uses outdated `sqsh` command

### ISSUE THREAD

**Issue by nertzy** [rails/rails#40611]
### Steps to reproduce

- Set up a SQL Server database in `database.yml`
- Run `rails dbconsole`

### Expected behavior
A SQL Server console should open up, perhaps using [`sqlcmd`](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15) which Microsoft provides for Windows, Mac, and Linux.

### Actual behavior
Rails tries to run [`sqsh`](https://sourceforge.net/projects/sqsh/), which seems to be unavailable in Homebrew on Mac and doesn't look like it's being actively maintained.

```
❯ rails db
Couldn't find database client: sqsh. Check your $PATH and try again.
```

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

**Comment by rafaelfranca** [comment]
Since you know what needs to be done and you care about it, can you open a PR?

**Comment by simi** [comment]
@nertzy it seems this is related code

https://github.com/rails/rails/blob/bcb63fcaa89a17c3f8c65680b4e21134cebaf843/railties/lib/rails/commands/dbconsole/dbconsole_command.rb#L73-L87
