### ISSUE TITLE
About including args in error message of Model.find_by!

### ISSUE THREAD

**Issue by yuta17** [rails/rails#40629]
Hello.
I think it would be better to include args in error message of `Model.find_by!`. 

```ruby
# ex)
def find_by!(*args) # :nodoc:
  find_by(*args) || raise(RecordNotFound.new("Couldn't find #{name} with #{args.first}", name))
end
```

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/core.rb#L358

This will help us to investigate when an error occurs. 

What do you think about this?

**Comment by yoones** [comment]
@yuta17 Could this lead to leaking sensitive information? I don't see how we could filter out passwords for instance.

**Comment by yuta17** [comment]
@yoones 
For example.. How about use filter_attributes?

```ruby
def find_by!(*args) # :nodoc:
  filtered_args = args.first.map do |key, value|
    if filter_attributes.include?(key)
      { "#{key}": ActiveSupport::ParameterFilter::FILTERED }
    else
      { "#{key}": value }
    end
  end
  find_by(*args) || raise(RecordNotFound.new("Couldn't find #{name} with #{filtered_args}", name))
end
```

**Comment by orenyk** [comment]
Is there a reason why this issue was closed? I think this could be very helpful. Thanks!
