### ISSUE TITLE
Model attachments do not get uploaded when reloading the model within a transaction

### ISSUE THREAD

**Issue by Zolotovmega** [rails/rails#40630]
Hello! Working with attachments I noticed a weird behaviour when attachments never get uploaded when calling `reload` within a transaction. 

Pending uploads are stored in `attachment_changes` and should be uploaded [after commit](https://github.com/rails/rails/blob/v6.0.3.4/activestorage/lib/active_storage/attached/model.rb#L56) but `attachment_changes` [gets cleaned](https://github.com/rails/rails/blob/v6.0.3.4/activestorage/lib/active_storage/attached/model.rb#L148) when calling `reload`. So when the execution leaves a transaction block and invokes `after_commit` `attachment_changes` is empty and file do not get uploaded.

### Steps to reproduce
The problem exists in Rails >= 6 only. Use a model that has one or many attachments. That does not matter which storage service to use, but I used the disk service to reproduce the issue locally:

```ruby
class User < ApplicationRecord
  has_one_attached :avatar
end
```

Create a new record with an attached attachment within a transaction and reload the record inside the transaction block:

```ruby
user = User.new
user.attachment = Rack::Test::UploadedFile.new(Rails.root.join("avatar.png"), 'image/png')

User.transaction do
  user.save!
  user.reload
end
```

User is persisted and attachment associated are persisted correctly. `ActiveStorage::AnalyzeJob` is enqueued and fail with `ActiveStorage::FileNotFoundError` exception.

Check `user.avatar.service.exist?(user.avatar.key)` to validate presence of the uploaded file.

### Expected behavior
Attached file is uploaded, running `user.avatar.service.exist?(user.avatar.key)` returns true.

### Actual behavior
Attached file does not get uploaded, running `user.avatar.service.exist?(user.avatar.key)` returns false.

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.6.6

What do you think? Does it sound like a bug or the behaviour is expected? 

Currently I'm using [this patch](https://gist.github.com/Zolotovmega/684264fa025047d3a9a1e2257ec01ed2) to fix the issue.

**Comment by jprosevear** [comment]
An additional challenge is that https://github.com/rails/rails/issues/37304 requires after_commit on your model to be prepended or before has_one_attached

**Comment by wnm** [comment]
We are still seeing this issue in rails 7.0.8 👀

**Comment by alejsalaz** [comment]
Same thing on Rails 7.0.5.1.

If you're experiencing the same issue, try finding a way to extract the file attachment process outside of the transaction. This can be achieved by introducing control flows in the update process if you are updating something other than the file in your model.

In our project, we have a method `update_file!('attachment_file', file)` that, behind the scenes, handles the file attachment process after performing validations. If an error occurs, the respective errors are added to the model instance, and the update is not performed. This allows us to check `instance.errors.present?` and display the error accordingly.

For example:
```ruby
instance.update_file!('attachment', params[:file])
return handle_update_errors if instance.errors.present?

# Continue with the rest of your flow.
```

**Comment by wrmk** [comment]
Had the same issue with Rails 7.1.3 and Ruby 3.3.0. 
Reloading an object inside the transaction breaks file uploading.

**Comment by ncr** [comment]
The bug is still present in 7.x, but seems to be fixed in 8.x

**Comment by iamadalek** [comment]
# Rails 8.1.1 - reload clears @attachment_changes, breaking after_commit uploads

```ruby
  ActiveRecord::Base.transaction do
    doc = Document.create!(...)
    doc.file.attach(io: StringIO.new("test"), filename: "test.txt")
    puts doc.attachment_changes  # => {"file" => #<CreateOne...>}

    doc.reload
    puts doc.attachment_changes  # => {}  ← CLEARED!
  end
```
  # after_commit runs, but attachment_changes is empty → no upload


Possible clean/surgical fix:
```ruby
  def reload(*)
    changes = @attachment_changes
    super.tap { @attachment_changes = changes }
  end
```
