### ISSUE TITLE
`after_commit` hooks forget previous `on` options if same method name is used 

### ISSUE THREAD

**Issue by tomasv** [rails/rails#40648]
Hey 👋🏻 

I've discovered that `after_commit` hooks behave oddly when the same symbol is used multiple times.

In a case like:
```ruby
class SomeModel < ActiveRecord::Base
  after_commit :foo, on: :create
  after_commit :foo, on: :update

  private

  def foo
    # ...
  end
end
```

`foo` is not invoked on create. The latter `after_commit :foo` seems to override all previous `:foo` after commit hooks.

A workaround is to use block form:
```ruby
class SomeModel < ActiveRecord::Base
  after_commit(on: :create) { foo }
  after_commit(on: :update) { foo }

  private

  def foo
    # ...
  end
end
```
### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

$after_commits = 0

class Post < ActiveRecord::Base
  after_commit :do_something

  def do_something
    $after_commits += 1
  end
end

class PostAfterCreateCommit < ActiveRecord::Base
  self.table_name = 'posts'

  after_commit :do_something, on: :create

  def do_something
    $after_commits += 1
  end
end


class PostMultipleHooks < ActiveRecord::Base
  self.table_name = 'posts'

  after_commit :do_something, on: :create
  after_commit :do_something, on: :update # this one overrides the previous one

  def do_something
    $after_commits += 1
  end
end

class PostMultipleHooksDifferentNames < ActiveRecord::Base
  self.table_name = 'posts'

  after_commit :do_something, on: :create
  after_commit :do_something2, on: :create

  def do_something
    $after_commits += 1
  end

  def do_something2
    $after_commits += 1
  end
end

class BugTest < Minitest::Test
  def setup
    $after_commits = 0
  end

  def test_simple_after_commit
    Post.create!
    assert_equal 1, $after_commits
  end

  def test_after_create_commit
    PostAfterCreateCommit.create!
    assert_equal 1, $after_commits
  end

  def test_multiple_after_commit
    PostMultipleHooks.create!
    assert_equal 1, $after_commits
  end

  def test_different_names
    PostMultipleHooksDifferentNames.create!
    assert_equal 2, $after_commits
  end
end
```

### Expected behavior

In a case like:
```ruby
class SomeModel < ActiveRecord::Base
  after_commit :foo, on: :create
  after_commit :foo, on: :update
end
```

`foo` should be invoked both on create ant on update.

### Actual behavior

(Using the same example from "Expected behavior")

`foo` is not invoked on create. The latter `after_commit :foo` seems to override all previous `:foo` after commit hooks.

### System configuration

**Rails version**: 6.0.3.4

**Ruby version**: 2.6.3

**Comment by tahsin352** [comment]
You can call multiple like this
```ruby
after_commit :do_something, on: [:create, :update]
```

**Comment by tomasv** [comment]
@tahsin352 thanks for sharing, that's a more elegant workaround.

This still looks like a bug to me, other ActiveRecord lifecycle callbacks work as expected except for `after_commit` when used the way I outlined.

**Comment by composerinteralia** [comment]
This is happening because when adding callbacks we first remove any duplicate callbacks:

https://github.com/rails/rails/blob/f75546891ac0d6b538991a89ed17e47ee1fe5858/activesupport/lib/active_support/callbacks.rb#L583-L598

Callbacks are considered duplicates if they have the same kind (in this case `:after`) and filter (in this case `:do_something`):

https://github.com/rails/rails/blob/f75546891ac0d6b538991a89ed17e47ee1fe5858/activesupport/lib/active_support/callbacks.rb#L323-L330

If we want to fix this, we would need to somehow compare the `:on` option as well. This might be tricky, since the callback itself doesn't know anything about the `:on` option. That is an ActiveRecord option—it gets transformed into an `:if` before the callback is built and we don't do anything with the `:on` option after that:

https://github.com/rails/rails/blob/f75546891ac0d6b538991a89ed17e47ee1fe5858/activerecord/lib/active_record/transactions.rb#L267-L277

**Comment by dhh** [comment]
I think this is working as expected. This is what allows you to overwrite callbacks in general to run less often or differently in subclasses.

**Comment by ghiculescu** [comment]
@dhh would you be open to a warning when a duplicate callback like this is detected? It seems to come up as a gotcha every now and then, see https://github.com/rails/rails/issues/48910 for example.
