### ISSUE TITLE
Rails 6 new queue names are not documented anywhere or documentation is wrong

### ISSUE THREAD

**Issue by niedfelj** [rails/rails#40654]
I'm using Sidekiq with latest Rails 6. None of the analysis jobs were firing for active storage because the queue has been renamed to active_storage_analysis, but I can't find this documented ANYWHERE. Not on the active job guide and not in the configuration guide (in fact, it says that if a specific queue is not assigned it will use default). This is horrible. I did find that someone had documented all of the new queue names here:

https://mikerogers.io/2019/06/06/rails-6-sidekiq-queues

**Comment by rafaelfranca** [comment]
Thank you for the issue.

Are you sure it is not documented anywhere? Just a few examples of where this was documented, some of them should be even inside your application:

https://guides.rubyonrails.org/configuring.html#for-6-0-new-defaults-from-previous-versions-below-and
https://github.com/rails/rails/blob/6-0-stable/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults_6_0.rb.tt#L25-L27
https://github.com/rails/rails/blob/6-0-stable/railties/CHANGELOG.md#rails-600beta1-january-18-2019

```
* Send Active Storage analysis and purge jobs to dedicated queues by default.

Analysis jobs now use the :active_storage_analysis queue, and purge jobs now use the :active_storage_purge queue. This matches Action Mailbox, which sends its jobs to dedicated queues by default.

George Claghorn
```

It is horrible that even with three different places documenting this feature you could find it.

**Comment by composerinteralia** [comment]
The configuring guide does mention the defaults for [action mailbox](https://guides.rubyonrails.org/configuring.html#configuring-action-mailbox), and the active storage defaults are mentioned) and [active storage](https://guides.rubyonrails.org/configuring.html#for-6-0-new-defaults-from-previous-versions-below-and), so I am going to close this issue. That said, if there are specific places you think we could add documentation to make this more clear, please do open a PR. Thanks!

Oops, Rafael beat me to it.

**Comment by niedfelj** [comment]
@rafaelfranca It should be in the active storage guide. It's a critical part of active storage and anyone setting this up from scratch is not going to be digging through changelogs or a new defaults section of the configuring guide.

**Comment by composerinteralia** [comment]
@niedfelj if you could open a PR adding this to the active storage guide I would be happy to review that.
