### ISSUE TITLE
find_or_create_by! generates invalid SQL query in Rails 6.1

### ISSUE THREAD

**Issue by connorshea** [rails/rails#40666]
### Steps to reproduce

You can see this issue (and instructions/details) with my example reproduction app here: https://github.com/connorshea/example-rails-6-1-associated-record-error

I'll repeat the reproduction steps from the README here.

- Clone repo with `git clone https://github.com/connorshea/example-rails-6-1-associated-record-error`
- `bundle install`
- `bundle exec rails db:create` (will need Postgres, though I think this should be reproducible on other DB engines?)
- `bundle exec rails db:migrate`
- `bundle exec rails db:seed` to trigger the failure, and use `--trace` if you want the backtrace.

If you switch to the `rails-6-0` branch in that repo, `bundle install`, and re-run `bundle exec rails db:seed`, it won't fail.

Some change in Rails 6.1 has broken this and caused it to generate invalid SQL.

I'm not sure what exactly is causing the issue, whether it's the specific usage of `has_many :through` in combination with `find_or_create_by!`, or something else, but it's definitely a regression in Rails 6.1.

I discovered this issue when trying to upgrade my Rails app [vglist](https://github.com/connorshea/vglist) to 6.1.0.rc1.

### Expected behavior

This code would Just Work™ in Rails 6.1 since it works fine in 6.0:

```ruby
platforms = Platform.first(rand(1..3)).uniq

GamePurchase.find_or_create_by!(
  comments: 'foo',
  platforms: platforms
)
```

### Actual behavior
The code does not Just Work™ on Rails 6.1.

```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "platforms"
LINE 1: ...hases" WHERE "game_purchases"."comments" = $1 AND "platforms...
                                                             ^
/Users/connorshea/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/rails-413a02c4a5dc/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:678:in `exec_params'
```

And then the SQL being run on Rails 6.1 because of this code is:

```
# From adding `puts` statements inside `lib/active_record/connection_adapters/postgresql_adapter.rb` at the `exec_no_cache` method.
# SQL query on Rails 6.1:
"SELECT \"game_purchases\".* FROM \"game_purchases\" WHERE \"game_purchases\".\"comments\" = $1 AND \"platforms\".\"platform_id\" IN ($2, $3, $4) LIMIT $5"
# arguments:
["foo", 46, 24, 10, 1]
```

On Rails 6.0, these are the queries being run instead, and they work correctly:

```
"SELECT 1 AS one FROM \"game_purchase_platforms\" WHERE \"game_purchase_platforms\".\"game_purchase_id\" IS NULL AND \"game_purchase_platforms\".\"platform_id\" = $1 LIMIT $2"
# arguments:
[23, 1]

"INSERT INTO \"game_purchases\" (\"comments\", \"created_at\", \"updated_at\") VALUES ($1, $2, $3) RETURNING \"id\""
# arguments:
["foo", "2020-11-22 01:28:53.908192", "2020-11-22 01:28:53.908192"]

"SELECT 1 AS one FROM \"game_purchase_platforms\" WHERE \"game_purchase_platforms\".\"game_purchase_id\" = $1 AND \"game_purchase_platforms\".\"platform_id\" = $2 LIMIT $3"
# arguments:
[20, 23, 1]

"INSERT INTO \"game_purchase_platforms\" (\"game_purchase_id\", \"platform_id\", \"created_at\", \"updated_at\") VALUES ($1, $2, $3, $4) RETURNING \"id\""
# arguments:
[20, 23, "2020-11-22 01:28:53.911865", "2020-11-22 01:28:53.911865"]
```

### System configuration
**Rails version**: Rails 6.1.0.rc1 and rails' `6-1-stable` branch (commit SHA 413a02c4a5dc1fa3c5bdb557b4970200eafce033)

**Ruby version**: Ruby 2.6.5

**Comment by kamipo** [comment]
In Rails 6.0,  `where`/`find_by` with through association (`GamePurchase.find_by(platforms: platforms)`) was almost no-op by generated SQL as `"game_purchases"."id" IS NULL`.

In Rails 6.1 (01cffc3789312a297cc2a7e6b44938c166125823, c9663136349201b133d73aeaea4ff5f2d358c7c3), it will generate `"platforms"."id" = ?`.

If you want the 6.0 behavior (i.e. ignore `platforms: platforms` condition for `find_by`), use `create_with` or constructor block.

If you don't want to ignore `platforms: platforms` condition for `find_by`, add `joins(:platforms)` for the through association.

```ruby
GamePurchase.create_with(platforms: platforms).find_or_create_by!(comments: 'foo')

# or

GamePurchase.find_or_create_by!(comments: 'foo') { |o| o.platforms = platforms }

# or

GamePurchase.joins(:platforms).find_or_create_by!(comments: 'foo', platforms: platforms)

**Comment by connorshea** [comment]
@kamipo So this is an intentional breaking change then?

**Comment by kamipo** [comment]
Yes.

**Comment by composerinteralia** [comment]
Since this was an intentional change, I am going to close this issue.
