### ISSUE TITLE
Unexpected ActiveSupport::NumberHelper behaviour

### ISSUE THREAD

**Issue by varg90** [rails/rails#40665]
### Steps to reproduce
```
> require 'active_support'
=> true
> include ActiveSupport::NumberHelper
=> Object
> number_to_currency(number_to_human(9256))
=> "$9.26 Thousand"
> number_to_currency(number_to_human(-9256))
=> "-$9.26"
```

### Expected behavior
```
> number_to_currency(number_to_human(-9256))
=> "-$9.26 Thousand"
```

### Actual behavior
```
> number_to_currency(number_to_human(-9256))
=> "-$9.26"
```

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.7.0p0

**Comment by varg90** [comment]
It works as expected with the **ruby 2.6.5**, but broke with the **ruby 2.7.0**

**Comment by dancristianb** [comment]
Hi @varg90, thanks for the detailed report!

I've had a look into this and it seems to be working in Rails 6.1.0.rc1. 
From what I gather, this was fixed https://github.com/rails/rails/issues/39349 via https://github.com/rails/rails/pull/39350. 
It looks like prior to the fix, for negative numbers only, there was a `#to_f` called on the `number_to_currency` input and this was stripping out the `number_to_human` units.
