### ISSUE TITLE
Unexpected Parameter with Name of Controller when POSTing Json

### ISSUE THREAD

**Issue by xcskier56** [rails/rails#40683]
### Steps to reproduce
I was unable to use the provided single file `MiniTest` examples to replicate the behavior, but am able to replicate with a simple application that you can clone [here](https://github.com/xcskier56/example_of_unexpecte_parameter) or replicate using the steps below

1. Create a brand new, API only rails app `rails new test_app --api`
2. Create a nested controller with expected parameters
```ruby
module Bar
  class ExampleController < ApplicationController
    def test
      render json: example_params, status: 200
    end

    private

    def example_params
      params.permit(:attr_1, :attr_2)
    end
  end
end
```
3. Add Route
```ruby
Rails.application.routes.draw do
  match 'bar/foo', to: 'bar/example#test', via: :post
end
```
4. Turn on `:raise` on unknown parameters
```ruby
# in application.rb
config.action_controller.action_on_unpermitted_parameters = :raise
```
5. Create the test
```ruby
require 'test_helper'

class ParamsTest < ActionDispatch::IntegrationTest
  test "it fails with unknown parameter" do
    post '/bar/foo', params: { attr_1: 'foo', attr_2: 'bar' }, as: :json

    assert_response :success
  end

  test "it works" do
    post '/bar/foo', params: { attr_1: 'foo', attr_2: 'bar' }

    assert_response :success
  end
end
```

6. Run the test
`rake test`

### Expected behavior
I would expect that both tests pass since they are making the exact same request

### Actual behavior
Notice that the first test that is posting with `as: :json` fails while the second test passes. I have been able to replicate this behavior with this application using Postman as well as the test failure.

The test will fail with `ActionController::UnpermittedParameters: found unpermitted parameter: <controller_name>`. In this example app, `<controller_name>` will be `:example`. The full params for the test are:

```ruby
# These are access by adding `STDOUT.puts params.to_s` in the controller method
# Failing test:
{"attr_1"=>"foo", "attr_2"=>"bar", "controller"=>"bar/example", "action"=>"test", "example"=>{"attr_1"=>"foo", "attr_2"=>"bar"}}

# Passing Test: 
{"attr_1"=>"foo", "attr_2"=>"bar", "controller"=>"bar/example", "action"=>"test"}
```

### System configuration
**Rails version**: 6.0.3.4 & 6.1.0.rc1

**Ruby version**: 2.7.0 & 2.6.6

**Comment by georgeclaghorn** [comment]
This is the default parameter-wrapping behavior described [here](https://guides.rubyonrails.org/action_controller_overview.html#json-parameters) and [here](https://api.rubyonrails.org/v6.0.3.4/classes/ActionController/ParamsWrapper.html).

**Comment by xcskier56** [comment]
Yep, I see that now. Thank you for pointing me to the documentation.
