### ISSUE TITLE
Changes to bin/yarn cause infinite loop when binstubs are first on the path

### ISSUE THREAD

**Issue by schneems** [rails/rails#40681]
### Steps to reproduce

This change (https://github.com/rails/rails/pull/39062) is causing an infinite loop when `bin/` is first on the path:

```
$ mdir -p  /tmp/7df6ccbca49f52e801d1bafd3be15e18; cd  /tmp/7df6ccbca49f52e801d1bafd3be15e18
$ rails -v 
Rails 6.1.0.rc1
$ rails new myapp && cd myapp
$ PATH="bin:$PATH" bundle exec rake yarn:install
# Runs forever
```

You can see this in action by adding a puts to the file. On mac, with sed:

```
$ sed -i '' '2i\
puts "calling bin/yarn"
' bin/yarn

$ PATH="bin:$PATH" bundle exec rake yarn:install
calling bin/yarn
calling bin/yarn
calling bin/yarn
calling bin/yarn
calling bin/yarn
calling bin/yarn
calling bin/yarn
calling bin/yarn
calling bin/yarn
calling bin/yarn
calling bin/yarn
calling bin/yarn
# ...
```

We want `bin` to be first on the path so that the binstubs like `bin/rake` and `bin/rails` are picked up. We need to find a way to have `exec "yarn"` not exec itself

### Expected behavior

System yarn should be invoked and the project should not be stuck in an infinite loop

### Actual behavior

The `bin/yarn` binstub invokes itself again and again

### System configuration
**Rails version**: Rails 6.1.0.rc1

**Ruby version**: 2.7.2

**Comment by kaspth** [comment]
Looks like this is being worked on in https://github.com/rails/rails/pull/40646

**Comment by schneems** [comment]
Awesome, thanks for the link!

**Comment by composerinteralia** [comment]
#40646 was merged. I tested the fix out locally and it seems to fix this issue so I'm going to close it. Thanks!

**Comment by schneems** [comment]
thank you!
