### ISSUE TITLE
Proposal: Allow DirectUpload to Receive Callback as Delegate on Class Creation.

### ISSUE THREAD

**Issue by cacheflow** [rails/rails#40692]
### Given the following code: 

```
class Uploader {
   directUploadWillStoreFileWithXHR(request) {
   	request.upload.addEventListener("progress", event => event)
   }
}
const uploader = new Uploader()
const upload = new DirectUpload(file, url, uploader);

upload.create((error, blob) => {
      // calls uploader.directUploadWillStoreFileWithXHR(request) 
    if (error) {
      // Handle the error
    } else {
      // do something else
    }
  })
```

### Currently 

When calling ` upload(file).create` it will call `directUploadWillStoreFileWithXHR` on the Uploader class as expected. However, this limits us to only passing in classes as the third parameter to DirectUpload.

### Proposal
Allow DirectUpload's third parameter to either be a callback or a class. Adding this would allow DirectUpload to be used with React Hooks or any situation that uses a callback instead of a method on a class/object.

### System configuration
**Rails version**: Rails 6.0.3.4

**Ruby version**: ruby 2.6.6p146

**Comment by cacheflow** [comment]
PR: https://github.com/rails/rails/pull/40693

**Comment by georgeclaghorn** [comment]
Closing for the same reasons as given in https://github.com/rails/rails/pull/40693#issuecomment-734984780.
