### ISSUE TITLE
ActiveSupport::TimeWithZone#dst? always returns true

### ISSUE THREAD

**Issue by drssdinblck** [rails/rails#40705]
### Steps to reproduce
Run `rails c` for a standard rails application.

Execute 
```ruby
Time.find_zone!('Berlin').parse('2020-01-01').dst?
```

### Expected behavior
`dst?` should return `false` for January as this is **not** within daylight saving time.

### Actual behavior
```ruby
[29] pry(main)> Time.find_zone!('Berlin').parse('2020-01-01').dst?
=> true
```

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.7.2

**OS**: alpine3.12

The application is running in docker. This is the Dockerfile:

```dockerfile
FROM ruby:2.7.2-alpine3.12
RUN apk add --no-cache --update build-base linux-headers git postgresql-dev tzdata less
WORKDIR /my-app
COPY Gemfile* ./
RUN bundle install
COPY . .
```

**Comment by composerinteralia** [comment]
I am not able to reproduce this locally (Ruby 2.7.2 with Rails 6.0.3.4). This returned `false` for me in the Rails console, and this reproduction script is passing:

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "6.0.3.4"
end

require "active_support"
require "active_support/core_ext/time/zones"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    refute Time.find_zone!("Berlin").parse('2020-01-01').dst?
  end
end
```

**Comment by jonathanhefner** [comment]
@drssdinblck It sounds like you may be experiencing tzinfo/tzinfo#120 (see also #40427).  Can you upgrade your `tzinfo` gem, and see if that resolves the problem?
