### ISSUE TITLE
ActionText Trix: Want to highlight one word as code, whole line gets highlighted

### ISSUE THREAD

**Issue by yshmarov** [rails/rails#40718]
### Steps to reproduce
![trix problem](https://user-images.githubusercontent.com/13472945/100734369-d897b580-33cf-11eb-8aa4-7bd5907b33ff.gif)

### Expected behavior
Only highlighted text is turned to code

### Actual behavior
Whole line is turned to code

### System configuration

ruby "2.7.2"
gem "rails", "~> 6.0.3.4"

**Comment by louim** [comment]
Hey! This seems to be an issue with the Trix editor itself, I think you should open the issue in the [Trix repo instead](https://github.com/basecamp/trix).

**Comment by yshmarov** [comment]
@louim => I've duplicated the issue there https://github.com/basecamp/trix/issues/865

**Comment by jonathanhefner** [comment]
Closing in favor of basecamp/trix#865.
