### ISSUE TITLE
6.1.0.rc1 ActiveRecord PostgreSQL daterange coercion problem

### ISSUE THREAD

**Issue by serghost** [rails/rails#40714]
Before upgrading to 6.1.0.rc1, I had to use the native postgres daterange type   (I needed it for native query operators like `&&`/`-|-` etc). I achieved this behaviour with the attribute option:
`attribute :daterange, range: true`

And the hypothetical `@booking.daterange` was returning what I needed: `"[2020-12-01,2020-12-13)"` instead of `Tue, 01 Dec 2020...Sun, 13 Dec 2020`. After upgrade to 6.1.0.rc1 it returns the ruby range

### Steps to reproduce
Please use the script below for reproducing the problem:

    if ARGV.empty? 
      puts "You can specify the local git repository, i.e. `ruby script.rb ~/work/rails.git`"
    end

    unless File.exist?('Gemfile')
      File.write('Gemfile', <<-GEMFILE)
        source 'https://rubygems.org'
        #gem 'rails', git: '#{ARGV[0] || 'https://github.com/rails/rails.git'}', tag: 'v6.0.3.4'
        gem 'rails', git: '#{ARGV[0] || 'https://github.com/rails/rails.git'}', tag: 'v6.1.0.rc1'
        gem 'pg'
        gem 'pry'
      GEMFILE
      system 'bundle'
    end
    require 'bundler'
    Bundler.setup(:default)
    require 'pry'
    require 'active_record'
    require 'minitest/autorun'
    require 'logger'

    `createdb daterange_test_db`

    ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'daterange_test_db')
    ActiveRecord::Base.logger = Logger.new(STDOUT)
    ActiveRecord::Schema.define do
         create_table :bookings, if_not_exists: true do |t|
         t.daterange :daterange
      end
    end

    module Booking
    end

    class Booking::Base < ActiveRecord::Base
      self.table_name = 'bookings'
      attribute :daterange, range: true
    end

    class BugTest < Minitest::Test
      def test_daterange_type
        booking = Booking::Base.create(daterange: Date.new(2020,12,1)..Date.new(2020,12,12))
    
        assert_equal '[2020-12-01,2020-12-13)', Booking::Base.last.daterange
      end
    end

Note: test passes when the version is changed to 6.0.3.4, so new behaviour introduced in 6.1.0.rc1

### Expected behavior
Test must pass

### Actual behavior
Test fails

### System configuration
**Rails version**: 6.1.0.rc1

**Ruby version**: 2.7.1p83

**Comment by rafaelfranca** [comment]
Thank you for the issue. You need to specify the type of your `daterange` attribute in the `attribute` call otherwise Rails will use the type defined in the database.

This changed in https://github.com/rails/rails/commit/8c793aa88b9d116f7d17eec23f4038e1f60a8dfb, but this is a deliberate change.
