### ISSUE TITLE
View Source for back-end code

### ISSUE THREAD

**Issue by mheiber** [rails/rails#40752]
### Steps to reproduce

Use a site built on Rails, such as GitHub. Look for "View back-end source" button (missing).

### Expected behavior

I'm hoping for there to be be a way to view the Ruby source for sites created Rails.
Browsers have "View Source" for front-end code, but as Rails apps typically have all or most of their logic on the back end, the most important code for Rails apps is hidden.

Having this as an opt-in feature seems it would have benefits in making the Web open and in helping people learn. I understand that not every team wants to expose their intellectual property, so I don't think this feature would be a good default.

Note: this expected behavior comes from the value of the View Source feature that works (sometimes) for HTML, CSS, JS and SVG:

<img width="588" alt="Screenshot 2020-12-05 at 13 57 54" src="https://user-images.githubusercontent.com/4691093/101245024-e1ef8d80-3701-11eb-8e43-52cc813cac49.png">

https://twitter.com/dhh/status/1334953980036853761?s=20

https://twitter.com/dhh/status/1335122200303726592?s=20

<img width="595" alt="Screenshot 2020-12-05 at 13 56 39" src="https://user-images.githubusercontent.com/4691093/101244987-b5d40c80-3701-11eb-88fd-0edafc69f8bc.png">

### Actual behavior

No built-in way to see the source for a page.

Some sites have "Fork me on GitHub" - but that's not actually the same: one can't see the code for a particular page without a little hunting. 

### System configuration

any

**Comment by mheiber** [comment]
I also want to thank the Rails team for making free tools for building feature-rich apps and building a strong community. This issue may seem like a joke, but it's earnest. Please close the issue if it isn't in line with Rails' current direction or seems infeasible.

**Comment by guledali** [comment]
![gif](https://user-images.githubusercontent.com/20647282/101275921-cb9d0c80-37a9-11eb-9ea6-a030fa8314b4.gif)

**Comment by n-rodriguez** [comment]
wtf?

**Comment by mheiber** [comment]
Thanks for your responses, could you help me understand them better?

@guledali I don't know how to interpret the meme. If you could express your sentiment as a sentence I'd have better ability to respond to feedback, or understand why the idea is welcome or unwelcome.

@n-rodriguez , I'm not sure what to take from your "wtf." I tried to explain why I (and presumably DHH) think this feature is a good idea in the issue description. Is there something missing that you'd like me to add, or some premise I got wrong?

**Comment by n-rodriguez** [comment]
It's really an astonishing request... You ask for all projects to be open source with a button to directly see the source code...

**Comment by mheiber** [comment]
> It's really an astonishing request... You ask for all projects to be open source with a button to directly see the source code...

Thanks for clarifying, IP is definitely a concern. That's why I suggested this as opt-in rather than on-by-default feature, so it wouldn't leak IP.

**Comment by n-rodriguez** [comment]
> Thanks for clarifying, IP is definitely a concern. That's why I suggested this as opt-in rather than on-by-default feature, so it wouldn't leak IP.

Security is also a big concern.

**Comment by rafaelfranca** [comment]
Thank you for the issue. While I'm also a big fan of "View Source", implementing such thing into Rails would be unlikely to happen. We also don't take feature requests in the issue tracker. A Rails plugin for this feature could be possible, so if you are interested on building it, please go ahead.
