### ISSUE TITLE
NumericalityValidator `allow_nil` option doesn't work anymore for params coming from a controller

### ISSUE THREAD

**Issue by filippoliverani** [rails/rails#40750]
`numericality` validation helper behaviour on attributes of an ActiveRecord object created using  `ActionController::Parameters` has changed in Rails 6.1.0.rc2. It could be related to [this refactoring](https://github.com/rails/rails/commit/4cc438a1df75e4c230f19cafe9258dbab969cd27)

### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", '6.1.0.rc2'
  gem "sqlite3"
end

require "action_controller"
require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
     t.integer :priority
  end
end

class Comment < ActiveRecord::Base
  validates :priority, numericality: { greater_than: 0 }, allow_nil: true
end

class BugTest < Minitest::Test
  def test_numericality_validation
    params = ActionController::Parameters.new({ comment: { priority: '' } })
    comment = Comment.new(params.require(:comment).permit!)

    assert comment.valid?
  end
end
```

### Expected behavior
`allow_nil` option should allow to skip numericality validation for empty `ActionController::Parameters` fields. Having to switch to `allow_blank` option would be a breaking change.

### Actual behavior
`numericality` validation fails with empty fields even if `allow_nil` option is specified.

### System configuration
**Rails version**: 6.1.0.rc2

**Ruby version**: 2.7.2

**Comment by eugeneius** [comment]
This seems to be the intended effect of https://github.com/rails/rails/commit/4cc438a1df75e4c230f19cafe9258dbab969cd27: numericality validations apply to the value before typecasting, which wasn't nil, so `allow_nil` shouldn't apply.

If we want to keep the new behaviour, it should have tests and a changelog entry though.
