### ISSUE TITLE
`rails new` stops and does not fail when git is not installed on system

### ISSUE THREAD

**Issue by Cian911** [rails/rails#40755]
### Steps to reproduce
In my case, I created a new `Dockerfile` with the following layers, but this should be applicable on any system without git installed:

```Dockerfile
FROM ruby:2.7-slim-buster AS base

RUN apt-get update && apt-get install -y build-base

RUN gem install rails -v 6.0
```

Build and bash into the container like so and run the `rails new` command:

```bash
docker build . -t backend
docker run -it backend bash

rails new blog
```

This will output the following, and will stop short of finishing as git is not yet installed on the system.
```bash
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
```

### Expected behavior

I would expect the command to fail at this point and reference a trace in some manner denoting to the user that git needs to be installed on the system before proceeding.

### Actual behavior

This will output the following, and will stop short of finishing as git is not yet installed on the system.
```bash
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
```

### System configuration
**Rails version**: Rails 6.0.3.4

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Comment by eugeneius** [comment]
`gem install rails -v 6.0` installs 6.0.0, and not 6.0.3.4 as reported above. This problem was already fixed in https://github.com/rails/rails/pull/38115 and released in 6.0.3.
