### ISSUE TITLE
Regression (5.2 -> 6): ActionView::Base.sanitized_allowed_attributes calls private method

### ISSUE THREAD

**Issue by DanielHeath** [rails/rails#40753]
### Steps to reproduce

In a rails console, run: `ActionView::Base.sanitized_allowed_attributes`

### Expected behavior
In rails 5.2
```
irb(main):001:0> ActionView::Base.sanitized_allowed_attributes
=> #<Set: {"href", "src", "width", "height", "alt", "cite", "datetime", "title", "class", "name", "xml:lang", "abbr"}>
```

### Actual behavior
```
NoMethodError (private method `allowed_attributes' called for #<Rails::Html::SafeListSanitizer:0x00007f46ac638dd8>)
```

### System configuration

**Rails version**:
6.0.2
**Ruby version**:
2.6.3

It appears that between these versions, SanitizeHelper was refactored and a call to a class method was changed to instead call an instance method (which does not exist).

**Comment by rafaelfranca** [comment]
Fixed by 9698570a35
