### ISSUE TITLE
define a shards method for ActiveRecord abstract classes

### ISSUE THREAD

**Issue by ritikesh** [rails/rails#40764]
With native horizontal sharding in place, an API to be able to run snippets across all shards for a given `ActiveRecord::Base` abstract class(`ApplicationRecord` in most cases) would be a definite nice to have.

```ruby
def run_something_on_all_shards
  ApplicationRecord.shards.each do |shard|
    ApplicationRecord.connected_to(shard: shard, role: :writing) do
      # execute some script for data collection / updation.
    end
  end
end
```
The alternative to this would be to provide a hook to execute a block of code on all connections, but I felt like that's application logic.
```ruby
def run_something_on_all_shards
  ApplicationRecord.on_all_shards(role: :writing).each do |shard|
    # execute some script for data collection / updation.
  end
end
```
This is a regular use-case for running 1-off scripts across all your tenants. Keeping/reading shard information across multiple PODs for every run isn't practical.

Happy to help with a PR based on suggestions.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.
