### ISSUE TITLE
Suggestion! Rails 6.0.4 ActiveTanant :-)

### ISSUE THREAD

**Issue by emrahyildirim** [rails/rails#40761]
Hello

I was going to have a new enregration proposal with rails. I think it's time to add multi tenant to rails. The name ActiveTenant looks very good. The gem files for this job are too old or problematic. Besides, it seems that there are a lot of people who have problems with ActionCable. Some tenant gem files require sub domain.  I think a scalable integration tenant_id milia gem file would be nice. A multi-tenant project such as "rails new project activetenant" can even be created when creating the project.

By the way, I'm not a software developer :-) I'm more on the system and network side. I'm interested in Rails as a hobby. I love Rails.

Regards

**Comment by louim** [comment]
Hey @emrahyildirim! The issue tracker is reserved for bug reports. A better place to discuss a new feature suggestion would be the Rails forums here: https://discuss.rubyonrails.org/

Have a great day!

**Comment by emrahyildirim** [comment]
> Hey @emrahyildirim ! Sorun izleyici, hata raporları için ayrılmıştır. Yeni bir özellik önerisini tartışmak için daha iyi bir yer, buradaki Rails forumları olabilir: https://discuss.rubyonrails.org/
> 
> İyi günler!

I'm so sorry, 
You're right, it's my fault.

Have a great day!

**Comment by emrahyildirim** [comment]
> Hey @emrahyildirim! The issue tracker is reserved for bug reports. A better place to discuss a new feature suggestion would be the Rails forums here: https://discuss.rubyonrails.org/
> 
> Have a great day!

I'm so sorry, 
You're right, it's my fault.

Have a great day!
