### ISSUE TITLE
AttributeMethods::Query does not respect getter overrides on Models

### ISSUE THREAD

**Issue by feliperaul** [rails/rails#40771]
### Steps to reproduce

Assuming the `User` model has boolean column named `admin`:

```
class User

  def admin
    # Overriding the getter to always return false
    false
  end

end

user = User.first
user.update(admin: true)
user[:admin] # true (as expected)
user.read_attribute(:admin) # true (as expected)

user.admin # false (as expected)
user.admin? # true (not expected)
```

### Expected behavior
The expected behavior was that `ActiveRecord::AttributeMethods::Query` would respect the overriden getter, but it doesn't, since https://github.com/rails/rails/blob/fe76a95b0d252a2d7c25e69498b720c96b243ea2/activerecord/lib/active_record/attribute_methods/query.rb#L13 uses the https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods.html#method-i-5B-5D method to access the value, which itself uses `read_attribute`, and bypasses the getter.

A simple fix would be to use `self.send(attr_name)` in that line, and I can create a pull request with tests if this is acknowledged as a problem. 

### Actual behavior
It returns the database value for `admin`, even tough the getter was overriden as per Rails documentation. 

This forces anyone that overrides a getter, specially in a boolean column, to also override the `attribute_method_suffix "?"` method as well, and it has bitten me more times than I wish it should have :)

### System configuration
Rails 6.1

**Ruby version**:
2.7.2

**Comment by rafaelfranca** [comment]
Thank you for the issue. I believe the current behavior is the desirable given I'd expect the attribute methods to always use the database value, but I can see a case be made in either way.

Please do investigate an see if this behavior is tested anywhere in the framework and if not, please open a PR using the reader.

**Comment by feliperaul** [comment]
@rafaelfranca I took a good look in the test suite regarding this and I didn't find this behavior tested anywhere, so I believe this is not by design.

I'm closing this for now. I'll investigate further and, as soon as I'm sure there are no tests (so this is not by design), I'll open the PR and reference you and this issue. Cheers.
