### ISSUE TITLE
Inconsistent behaviour of `config.action_dispatch.trusted_proxies` depending on value

### ISSUE THREAD

**Issue by csutter** [rails/rails#40772]
`ActionDispatch::RemoteIp` proxy filtering behaves inconsistently depending on whether the `custom_proxies` argument (set through `config.action_dispatch.trusted_proxies`) is set to a single value or an enumerable. This is surprising behaviour and can lead to frustration when e.g. moving from having one single trusted proxy specified to needing multiple (and vice versa).

Opening this as an issue instead of a PR as the method documentation makes it clear the existing behaviour is intentional and changing it would be a breaking change. Happy to PR it (with suitable deprecation warnings) if people think it makes sense to do so, but wanted to get feedback first.

### Steps to reproduce
Set `config.action_dispatch.trusted_proxies` to each of the following in `config/application.rb` (or an environment-specific config file):

1. an array, e.g. `[IPAddr.new("1.1.1.1"), IPAddr.new("1.1.1.2")]`
2. a single value, e.g. `IPAddr.new("1.1.1.1")`

### Expected behavior
Both should behave consistently, i.e. the setting should either replace the default set of proxies in `ActionDispatch::RemoteIp::TRUSTED_PROXIES`, or append its contents to it.

### Actual behavior
1. If an enumerable (or object responding to `#any?`) is specified, the setting _replaces_ the default set of trusted proxies in its entirety
2. If a single value is specified, it is _added_ to the existing contents of default set of trusted proxies

c.f. https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/remote_ip.rb#L65

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.7.2

**Comment by rafaelfranca** [comment]
Agree we should change this behavior to always replace the default set of proxies.

**Comment by csutter** [comment]
Cool, I'd be happy to make the change!

On second thought, it seems a bit odd to assign a single value to a setting with a plural name (`trusted_proxies`). Do you think it might be better to just deprecate the ability to set a single value instead?

**Comment by rafaelfranca** [comment]
Yes. I think that should be the case. We should only accept enumerables.
