### ISSUE TITLE
Railsties yarn.rake fails when the Rails.root folder name has spaces in its name.

### ISSUE THREAD

**Issue by thebravoman** [rails/rails#40783]
### Steps to reproduce
Create a rails folder that has spaces in its name.  
Example is "is-commands Build and Release/workspace"
The folder in question is "/var/lib/jenkins/jobs/is-commands Build and Release/workspace" and the rails project is located in it.

Build a rake task that calls:
```
Rake::Task["assets:precompile"].invoke
```

### Expected behavior
Yarn completes successfully. Precompilation completes successfully.

### Actual behavior
```
Errno::ENOENT: No such file or directory - /var/lib/jenkins/jobs/is-commands
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-6.1.0/lib/rails/tasks/yarn.rake:13:in ``'
/usr/local/rvm/gems/ruby-2.6.5/gems/railties-6.1.0/lib/rails/tasks/yarn.rake:13:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.6.5/gems/is-gcc_tools-1.3.18/lib/tasks/is/gcc_tools_tasks.rake:172:in `assets_and_closure' (this calls Rake::Task["assets:precompile"].invoke)
/usr/local/rvm/gems/ruby-2.6.5/gems/is-gcc_tools-1.3.18/lib/tasks/is/gcc_tools_tasks.rake:139:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.6.5/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
```

### System configuration
**Rails version**: 6.1

**Ruby version**: 2.6.5

### Update 1
Yesterday this was working with 

```
Using railties 6.0.3.4
```

Today it is not working with

```
Using railties 6.1.0 (was 6.0.3.4)
```

About 150 projects have failed because of this. Trying to understand it further.

### Update 2
The problem is in 
```
[9, 18] in /usr/local/rvm/gems/ruby-2.6.5/gems/railties-6.1.0/lib/rails/tasks/yarn.rake
    9:       valid_node_envs.include?(Rails.env) ? Rails.env : "production"
   10:     end
   11: 
   12:     byebug
   13:     yarn_flags =
=> 14:       if `#{Rails.root}/bin/yarn --version`.start_with?("1")
   15:         "--no-progress --frozen-lockfile"
   16:       else
   17:         "--immutable"
   18:       end
(byebug) Rails.root
#<Pathname:/var/lib/jenkins/jobs/is-commands Build and Release/workspace/test/dummy>
(byebug) `#{Rails.root}/bin/yarn --version`
*** Errno::ENOENT Exception: No such file or directory - /var/lib/jenkins/jobs/is-commands

nil
```

You can not call `#{Rails.root}/bin/yarn --version` when there is a space in the name of the folder

This was introduce about 2 days ago with https://github.com/rails/rails/commit/bd4d8fdfce9bbc160752d1b15db2f358d005fd24
I am not sure If I should tag the people that have made the commit (please tell me if I should not)
@rafaelfranca @doits 

I do have yarn in 
```
jenkins@vpszap6s:~/jobs/is-commands Build and Release/workspace/test/dummy/bin$ ls
bundle  rails  rake  setup  update  yarn
```

I could prepare a PR if you want.

**Comment by doits** [comment]
Thanks for your report, I created https://github.com/rails/rails/pull/40785 – can you see if this fixes it for you?

NB: I think this error was present before already, because the next `system` call a few lines later had the same problem if I am correct. Maybe it simply doesn't hard fail in this case?

**Comment by doits** [comment]
Yeah indeed, that is the difference indeed:

```ruby
system("not present")
=> nil

`not present`
Traceback (most recent call last):
        2: from (irb):4
        1: from (irb):4:in ``'
Errno::ENOENT (No such file or directory - not)
```

So before it silently wasn't doing anything at all in such cases and now it hard fails because of the different way to execute yarn.

**Comment by thebravoman** [comment]
No. This does not fix it

```
sh: 1: /var/lib/jenkins/jobs/is-commands Build and Release/workspace/test/dummy/bin/yarn --version: not found
```

system("not present") and `not present` follow different protocol. system reports it to the error log. they also return different results.

**Comment by doits** [comment]
:+1: so when it is merged it will actually run `yarn install` for you now, on Rails 6.0 it didn't – looks like yarn is called by some other means in your pipeline.

**Comment by thebravoman** [comment]
No sure what you mean.

I was calling Rake::Task["assets:precompile"].invoke and this was calling yarn.rake. 

We have all the project do a 
```
bundle install
yarn install
```
and they then continue. Why do you call yarn install in a yarn.rake.
Isn't this like calling bundle install in rake spec? Or bundle install in rake db:migrate. 

Why should yarn.rake call yarn install and rake db:migrate will not call bundle install?

**Comment by doits** [comment]
I can't reason about the logic, but look at:

https://github.com/rails/rails/blob/f4265aebc8ee2a8f038d10430e12e569ce848e23/railties/lib/rails/tasks/yarn.rake#L23-L26

This makes `yarn:install` run before `assets:precompile`. This was not changed in 6.1 but was like this in 6.0 already.

**Comment by thebravoman** [comment]
Ok. Thanks. I was sometimes wondering looking at the logs why yarn install run two times, but I never got to the point to look at it further.
