### ISSUE TITLE
Regression on Optimistic Locking from 6.0

### ISSUE THREAD

**Issue by bobmaerten** [rails/rails#40786]
### Steps to reproduce
It seems that the `lock_version` column is always incremented even if it's forced to an older revision.
I set up a script running the same test in both version to illustrate the problem:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", ARGV[0]
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.integer :lock_version
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_lock_version
    post = Post.create! title: "Hello"
    assert_equal 0, post.lock_version

    post.update! title: "Hello2"
    assert_equal 1, post.lock_version

    assert_raises ActiveRecord::StaleObjectError do
      post.update! title: "Yo", lock_version: post.lock_version - 1
    end
  end
end
```

### Expected behavior
When we want to do optimistic locking, we usually add the `lock_version` attribute to a model and then add in a hidden_field_tag the version to pass the current version, preventing a concurrent request to be updated and raising a `ActiveRecord::StaleObjectError`.

```
$ ruby optimistic_locking_bug.rb 6.0.3.4
[...snip...]
.
Finished in 0.004008s, 249.5010 runs/s, 748.5030 assertions/s.
1 runs, 3 assertions, 0 failures, 0 errors, 0 skips
```

### Actual behavior
Since 6.1.0, the very same test fails and no `ActiveRecord::StaleObjectError` is risen.

```
$ ruby optimistic_locking_bug.rb 6.1.0
[...snip...]
F

Failure:
BugTest#test_lock_version [optimistic_locking_6.1.0.rb:40]:
ActiveRecord::StaleObjectError expected but nothing was raised.

rails test optimistic_locking.rb:33

Finished in 0.003884s, 257.4665 runs/s, 772.3996 assertions/s.
1 runs, 3 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.2

**Comment by fatkodima** [comment]
Regression was introduced in https://github.com/rails/rails/pull/39321

**Comment by varentsov** [comment]
I have same issue on 6.1

**Comment by bobmaerten** [comment]
@kamipo It seems there is a side effect to #39321.
The `lock_version` value is always incremented, even the dirty value.
It took me a while to understand the fix, but my concern is that it breaks a common controller pattern in which we pass the lock_version value to a PATCH request payload (via the form in the view), to prevent an outdated model to overwrite updates on the same model by another user with different data. The `locking_version` mismatch was triggering the `StaleObjectError`, but now, since the lock_version is incremented, this does not work anymore.

How can we prevent concurrent model updates from now on with rails?

**Comment by bobmaerten** [comment]
To be clear, I'm still relying on @ryanb Railscast on Optimistic locking : http://railscasts.com/episodes/59-optimistic-locking.
But it seems, from now on, that Optimistic Locking is done the same way as `model.with_lock` from the database. But instead checking value from the database row, it's done on the dirty attribute?

From this observation I updated our code from Ryan's idea to something like this, keeping the notion of `StaleObjectError` in the codebase, in case the behavior would change again.

```ruby
def update
  @product = Product.find(params[:id])
  @product.attributes = params.require(:product).permit(:title, :lock_version)
  raise ActiveRecord::StaleObjectError if @product.lock_version_changed?
  
  if @product.save 
    flash[:notice] = "Successfully updated product."
    redirect_to product_path(@product)
  else
    render :action => 'edit'
  end
rescue ActiveRecord::StaleObjectError
  @product.reload
  render :action => 'conflict'
end
```

Hope this will help people who where still using this pattern, but willing tu upgrade to 6.1.

**Comment by shugo** [comment]
@bobmaerten 
> From this observation I updated our code from Ryan's idea to something like this, keeping the notion of `StaleObjectError` in the codebase, in case the behavior would change again.
> 
> ```ruby
>   raise ActiveRecord::StaleObjectError if @product.lock_version_changed?
>   
>   if @product.save 
> ```

This code has a race condition; another process or thread may change the record between `@product.lock_version_changed?` and `@product save`.

**Comment by shugo** [comment]
I've heard from @kamipo that this change is intentional: <https://twitter.com/kamipo/status/1347400453026271234>.

However, the new behavior doesn't work when lock_version is transferred between requests by form hidden fields, JSON, and so on.
I think optimistic locking is for these use cases, and hope this change will be reverted.

**Comment by bobmaerten** [comment]
I can't really tell @shugo, but but temporary patch is acceptable for now as I don't have many optimistic locking points in my apps, and few concurrent users in this same spots.
I hope either this will be reverted, or at least documented as for Ryans Bates example.
