### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by fynsta** [rails/rails#40781]
I installed Rails 6.1 today, but I got the error "Stack level too deep" with the following stack trace
```
        - activesupport (6.1.0) lib/active_support/core_ext/object/json.rb:173:in `each'
        - activesupport (6.1.0) lib/active_support/core_ext/object/json.rb:173:in `as_json'
        - activesupport (6.1.0) lib/active_support/core_ext/object/json.rb:57:in `as_json'
        - activesupport (6.1.0) lib/active_support/core_ext/object/json.rb:174:in `block in as_json'
        - activesupport (6.1.0) lib/active_support/core_ext/object/json.rb:173:in `each'
        - activesupport (6.1.0) lib/active_support/core_ext/object/json.rb:173:in `as_json'
        - activesupport (6.1.0) lib/active_support/core_ext/object/json.rb:57:in `as_json'
        - activesupport (6.1.0) lib/active_support/core_ext/object/json.rb:174:in `block in as_json'
        - activesupport (6.1.0) lib/active_support/core_ext/object/json.rb:173:in `each'
        - activesupport (6.1.0) lib/active_support/core_ext/object/json.rb:173:in `as_json'
        - activesupport (6.1.0) lib/active_support/core_ext/object/json.rb:57:in `as_json'
```
and so forth. This looks like a rails issue to me because it seems like some kind of recursive call stack.

### System configuration
**Rails version**:
Rails 6.1.0

**Ruby version**:
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin19]

**Comment by composerinteralia** [comment]
Could you provide a reproduction script or a sample application to reproduce the bug?

One way you might run into this error is if you try to turn an object that references itself into json:

```rb
x = {}
x[:x] = x
x.to_json
```

That would not be a Rails bug, but I think it would produce a stack trace like the one you show here.

**Comment by fynsta** [comment]
I see, thanks for the feedback!
I'll try to find the root of the problem. Is this something that might not have occurred in 6.0?

**Comment by MatheusSilvaSouza** [comment]
I also have that problem on `Rails 5.2.4.4` 
It seems to be caused by a recursive call to `as_json` in `activesupport-5.2.4.4/lib/active_support/core_ext/object/json.rb`

**Comment by paulwis** [comment]
In my case, removing the `meta_request` gem solved this in 6.1.

**Comment by jeffblake** [comment]
In my case I was using a custom Logger formatter that called `to_json` at the end. Changed it to `JSON.dump(hash)` to fix it

**Comment by fynsta** [comment]
> In my case, removing the `meta_request` gem solved this in 6.1.
That actually seems to have done the trick in my case. Thanks!

Closing the issue as it does not seem to be Rails' fault.

**Comment by zzemla** [comment]
For anyone looking for a solution:
https://github.com/dejan/rails_panel/pull/177#issuecomment-797378347

**Comment by leompeters** [comment]
Thank you, @zzemla. You rock!
