### ISSUE TITLE
Cache-Control "private, no-store" header not being preserved

### ISSUE THREAD

**Issue by ags** [rails/rails#40798]
https://github.com/rails/rails/pull/39461 changed the `no-store` directive for the `Cache-Control` header to be exclusive, i.e. when setting `Cache-Control` to `private, no-store`, this is simplified to just `no-store`. `private` should typically be superfluous there, but it's not always.

For instance, Fastly "does not currently respect no-store or no-cache directives" and says that "if you need to prevent caching by both Fastly and web browsers, we recommend combining the private directive with max-age=0 or no-store".

https://docs.fastly.com/en/guides/configuring-caching#do-not-cache

It's currently not possible (or at least clear) how to override this directive reduction behaviour.

### Steps to reproduce

Set a `Cache-Control` header of `private, no-store`, e.g.

```ruby
response.headers["Cache-Control"] = "private, no-store"
```

### Expected behavior

The response `Cache-Control` header should have a value of "private, no-store".

### Actual behavior

The response `Cache-Control` header has a value of "no-store".

### System configuration

**Rails version**: 6.1.0

**Ruby version**: 2.6.5

**Comment by rafaelp** [comment]
+1

**Comment by PikachuEXE** [comment]
My gem [`action_controller_tweaks`](https://github.com/PikachuEXE/action_controller_tweaks) also got spec failed in rails 6.1.0

Trying to set there headers in response:
```ruby
HEADERS = {
  # HTTP 1.1
  "Cache-Control" => "no-cache, no-store, pre-check=0, post-check=0",
  # HTTP 1.0
  "Pragma"        => "no-cache",
  # HTTP 1.0
  "Expires"       => "Mon, 01 Jan 1990 00:00:00 GMT",
}.freeze
```

But header `Cache-Control` would only include `no-store`
![image](https://user-images.githubusercontent.com/1018543/103986442-af83f500-51c5-11eb-9f7b-cecfe1b470b5.png)

**Comment by PikachuEXE** [comment]
I found [this commit](https://github.com/rails/rails/commit/e06f7b3ef7a24d9e25c99ef04b16eceec0fddbf4) when browsing [cache module in `6-1-stable`](https://github.com/rails/rails/blob/6-1-stable/actionpack/lib/action_dispatch/http/cache.rb)

I am not sure if this change would affect client behaviour
