### ISSUE TITLE
Rails 6.1.0 release changelog is missing breaking change notice

### ISSUE THREAD

**Issue by juliosantos** [rails/rails#40794]
Bumping rails from 6.0.3.4 to 6.1.0 causes an issue similar to [this other one](https://github.com/rails/rails/issues/37391) first identified in a release candidate. It was fixed by https://github.com/rails/rails/pull/39059.

This breaks older environment files which don't `require "active_support/core_ext/integer/time"`. I don't find the issue, but an earlier commit (adressing this issue for the test environment config generator only: https://github.com/rails/rails/commit/1c7207a22faca3f07ee9aee1dc00a5b01286de2f) mentions that

> Usually the application requires the entire active support at load time
> but the configuration happens before it is loaded. For that reason we
> need to require the core_ext that we want to use in this file.

Should it be documented as a breaking change in [the changelog](https://github.com/rails/rails/releases/tag/v6.1.0), or in the [Upgrade Guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-0-to-rails-6-1)?

### System configuration
**Rails version**:
Rails 6.1.0

**Ruby version**:
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]

**Comment by juliosantos** [comment]
Opened a PR for the Upgrade Guide in case it helps.

**Comment by louim** [comment]
@juliosantos did you run `rails app:update`? The line should have been highlighted in the diff between your actual configuration and the new configuration.

**Comment by juliosantos** [comment]
I did not. Running it does the trick. Thank you for your help.
