### ISSUE TITLE
ActiveSupport::Duration#{+,-} doesn't handle an array of parts

### ISSUE THREAD

**Issue by jeremyevans** [rails/rails#40796]
### Steps to reproduce

```
ruby -r active_support/duration -e 'ActiveSupport::Duration.new(1, [[:seconds, 1]]) + 1'
```

### Expected behavior

```
2 seconds
```

### Actual behavior

```
Traceback (most recent call last):
        2: from -e:1:in `<main>'
        1: from /usr/local/lib/ruby/gems/2.7/gems/activesupport-6.1.0/lib/active_support/duration.rb:247:in `+'
/usr/local/lib/ruby/gems/2.7/gems/activesupport-6.1.0/lib/active_support/duration.rb:247:in `fetch': no implicit conversion of Symbol into Integer (TypeError)
```

### System configuration
**Rails version**: 6.1.0 (worked in 6.0 and earlier versions)

**Ruby version**: 2.7.0 (should be Ruby version independent)

### More information

This appears to be caused by fa0587b56dd37bca9c088dbd2aeea5cd02bc43f5 (by @kamipo).

**Comment by kamipo** [comment]
Can you use `ActiveSupport::Duration.build` instead?

https://api.rubyonrails.org/classes/ActiveSupport/Duration.html#method-c-build

Actually `ActiveSupport::Duration.new` is not public API.
