### ISSUE TITLE
Offer a way to make images available in JS (no Asset pipeline)

### ISSUE THREAD

**Issue by technodrome** [rails/rails#40802]
### Steps to reproduce
@dhh removed the option to make images available in JS with Webpacker when no Asset pipeline is used. This was done here: https://github.com/rails/rails/commit/184358ae333ccbf1dc6677fb1e12b931dcfdef0e#diff-6076054da5dd96b0387641951a8399bbb93fa313723aea71c412bad2b557a4db

Without such an instruction it is impossible to work with images in Rails.

### Expected behavior
We should have a clear way of making images available through webpacker with pack_tags. 

### Actual behavior
No official guide available (at least I haven't found it)

### System configuration
**Rails version**: 6.1.0
**Ruby version**: 2.7.2

**Comment by dhh** [comment]
It wasn't the right place for that instruction. Needs to live in a guide or even in the Webpacker documentation. Feel free to investigate which of those options could make sense 👍

**Comment by louim** [comment]
@technodrome There is a section of the Webpacker doc that covers the use case: https://github.com/rails/webpacker/blob/master/docs/assets.md#link-in-your-rails-views

**Comment by technodrome** [comment]
Thanks @louim for taking time to look that up instead of just dismissing it. I'm using the original solution which DHH removed and it still works fine. If anything, removing it made it harder to find, especially when Webpacker docs explicitly say to put it back there.

**Comment by rafaelfranca** [comment]
@technodrome can you work on documenting it in the Rails guide? https://github.com/rails/rails/blob/master/guides/source/working_with_javascript_in_rails.md
