### ISSUE TITLE
Running "rails generate" or "rails test" results in error: Bad file descriptor - not a socket file descriptor (Errno::EBADF)

### ISSUE THREAD

**Issue by BluePeony** [rails/rails#40819]
### Steps to reproduce
rails new test_app
cd test_app
bundle install
No problems until here. When I try to run one of the 3 following commands I always get the same error:
rails generate scaffold User name:string email:string
rails generate controller StaticPages home help
rails test

### Expected behavior
Rails should successfully run the command and generate the scaffold of the User model or run the test suite - depending on the command.

### Actual behavior
Traceback (most recent call last):
	4: from -e:1:in `<main>'
	3: from /snap/ruby/189/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	2: from /snap/ruby/189/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	1: from /home/max/.gem/gems/spring-2.1.1/lib/spring/application/boot.rb:7:in `<top (required)>'
/home/max/.gem/gems/spring-2.1.1/lib/spring/application/boot.rb:7:in `for_fd': Bad file descriptor - not a socket file descriptor (Errno::EBADF)

And then the process hangs there.

### System configuration
**Rails version**:
6.1.0
**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Comment by rafaelfranca** [comment]
I just tried all the steps you described to reproduce and could not reproduce the problem. I think it could be something in your setup. Speficially, it seems it could be that you have a process running with the file descriptor number 3. Spring set the descriptor to the child socked https://github.com/rails/spring/blob/d7b21ff9afcaf1f5904b7a2286e2a8201728cb54/lib/spring/application_manager.rb#L109. Can you investigate to what this FD points?
