### ISSUE TITLE
Migrations with postgresql schemas name indexes incorrectly and fails to drop them

### ISSUE THREAD

**Issue by vihai** [rails/rails#40821]
Hello,

I'm using PostgreSQL schemas in my database. Automatically named indexes prepend `index_' to table name including schema, leading to index names containing a dot and the schema name, which is aesthetically not pleasant.

The issue, however, is that when the index is being dropped the generated name lacks the part following the dot altogether and the index is not found.

```
[4] pry(main)> cd ActiveRecord::Migration[6.1]
[5] pry(ActiveRecord::Migration::Current):1> 
[6] pry(ActiveRecord::Migration::Current):1> add_index 'ca.le_slots', 'owner_id'
-- add_index("ca.le_slots", "owner_id")
   (10.3ms)  CREATE INDEX "index_ca.le_slots_on_owner_id" ON "ca"."le_slots" ("owner_id")
   -> 0.0627s
=> #<PG::Result:0x0000560ac092d170 status=PGRES_COMMAND_OK ntuples=0 nfields=0 cmd_tuples=0>
[7] pry(ActiveRecord::Migration::Current):1> remove_index 'ca.le_slots', 'owner_id'
-- remove_index("ca.le_slots", "owner_id")
   (2.3ms)  DROP INDEX  "ca"."index_ca"
ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR:  index "index_ca" does not exist

from /var/lib/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `exec'
Caused by PG::UndefinedObject: ERROR:  index "index_ca" does not exist

from /var/lib/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `exec'
```

Also, explicitly setting the index name does not work:

```
[9] pry(ActiveRecord::Migration::Current):1> remove_index 'ca.le_slots', name: 'index_ca.le_slots_on_owner_id'
-- remove_index("ca.le_slots", {:name=>"index_ca.le_slots_on_owner_id"})
ArgumentError: Index schema 'index_ca' does not match table schema 'ca'
from /var/lib/gems/2.7.0/gems/activerecord-6.1.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:464:in `remove_index'
```

**Rails version**: 6.1
**Ruby version**: 2.7.0

**Comment by fatkodima** [comment]
Not all databases support schemas (pg and mysql - does, but sqlite - don't), so, as far as I can say, `ActiveRecord` is implemented without schemas in mind and assumes some kind of default schema by default, while some migration operations (like `create_table "my_schema.my_table"`) are working. 

You can rewrite with something like this:
```ruby
def change
  reversible do
    execute 'SET search_path to ca'
  end

  add_index :le_slots, :owner_id
ensure
  # write code to reset search_path to the original value
end
```

cc/ @kamipo

**Comment by vihai** [comment]
Okay, the workaround you propose seems workable.

Anyway, IMHO, the handling of dots as schema separators in migration statements could be made as a generic implementation that would eventually fail if used with database non supporting schemas.

Thank you
