### ISSUE TITLE
active record persistence reload does not reset the destroyed flag

### ISSUE THREAD

**Issue by schnika** [rails/rails#40820]
### Why does this even matter?
We have a situation in our project where we cannot rely on active record transactions but have to manually rollback our state (which involves inserting a deleted object into our database again). 
If the workflow provided by my gist is desired, then please close this issue. If you agree with me that a reload in the described situation should not have `destroyed?` set to `true` anymore then I am happy to contribute with a PR to this wonderful community :).
 
### Steps to reproduce

https://gist.github.com/schnika/30be816fd77675269a80f330763df7c0

### Expected behavior
The `post` should not be marked as `destroyed` anymore because it got inserted into the database again.

### Actual behavior
The `post` is still marked as `destroyed` even though it got added to the database again.

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.2

**Comment by marcelolx** [comment]
If I'm not wrong, when we do a reload and the record doesn't exists rails raises an exception, so, I think that if the record is found, there is no reason to not reset the flag.
