### ISSUE TITLE
Rendering ActiveRecord collections as non-derived partials results in `SELECT COUNT` query 

### ISSUE THREAD

**Issue by aar0nr** [rails/rails#40837]
When a partial is derived from a collection, `collection.map` is called first which loads the relation.

https://github.com/rails/rails/blob/v6.1.0/actionview/lib/action_view/renderer/collection_renderer.rb#L119

However, when it's non-derived, `collection.size` gets called first, which results in the `SELECT COUNT` query.

https://github.com/rails/rails/blob/v6.1.0/actionview/lib/action_view/renderer/collection_renderer.rb#L147

The collection should probably be loaded with a `to_a` somewhere.

/cc @tenderlove 

### Steps to reproduce

Render a collection using a non-derived partial:

```rb
<%= render collection: Post.all, partial: "post" %>
```

This results in the following queries:

```sql
SELECT COUNT(*) FROM "posts"
CACHE  SELECT COUNT(*) FROM "posts"
Post Load SELECT "posts".* FROM "posts"
```

Rendering a collection with a derived partial:

```rb
<%= render Post.all %>
```

This results in the following queries:

```sql
Post Load SELECT "posts".* FROM "posts"
```

### Expected behavior

Rendering an ActiveRecord collection with a non-derived partial should not execute a `SELECT COUNT` query.

### System configuration
**Rails version**:

6.1.0

**Ruby version**:

2.7.1

**Comment by rafaelfranca** [comment]
That is an interesting issue. Can you investigate where we can load the collection so the behavior is consistent? The only thing you need to keep in mind is that the collection something needs to preload some associations so we need to take that in consideration as well

**Comment by aar0nr** [comment]
After a further look, it's a little more complicated. The main issue is that `collection.size` is being called in [two](https://github.com/rails/rails/blob/v6.1.0/actionview/lib/action_view/renderer/collection_renderer.rb#L147) [places](https://github.com/rails/rails/blob/v6.1.0/actionview/lib/action_view/renderer/collection_renderer.rb#L174), but then further along [expects the collection to still be an unloaded relation](https://github.com/rails/rails/blob/v6.1.0/actionview/lib/action_view/renderer/collection_renderer.rb#L83) for the `PreloadCollectionIterator`. In reality, the `collection.size` information should not available if the collection is a relation, otherwise we have a bunch of phantom `SELECT COUNT` queries running. I'm not sure how you want to go about fixing it.

**Comment by aar0nr** [comment]
Actually, the `PreloadCollectionIterator` checks if the relation has been loaded, so I think we can just preload to array and count the size. I'll open pull request.
