### ISSUE TITLE
Can't connect an abstract class to the same database as `ActiveRecord::Base` using `connected_to`

### ISSUE THREAD

**Issue by ghiculescu** [rails/rails#40853]
We'd like to have an abstract class models can use to only ever access the primary connection:

```ruby
class ApplicationRecord
  connected_to database: { writing: :primary, reading: :replica }
end

class NeverAccessesTheReplica < ApplicationRecord
  self.abstract_class = true
  connected_to database: { writing: :primary, reading: :primary }
end

class ThingThatNeedsToAlwaysBeFresh < NeverAccessesTheReplica
end
```

The problem is that `ThingThatNeedsToAlwaysBeFresh` and `ApplicationRecord` will use different connections for reading *and* writing. This is causing issues in our test environment, because we use transactional tests. Here's a test case (that would live [here](https://github.com/rails/rails/blob/master/activerecord/test/cases/connection_adapters/connection_handlers_multi_db_test.rb)) that hopefully illustrates the problem:

```ruby
def test_can_connect_models_to_identical_connections_inside_transaction
  previous_env, ENV["RAILS_ENV"] = ENV["RAILS_ENV"], "default_env"

  config = {
    "default_env" => {
      "readonly" => { "adapter" => "sqlite3", "database" => "test/db/readonly.sqlite3" },
      "primary"  => { "adapter" => "sqlite3", "database" => "test/db/primary.sqlite3" }
    }
  }
  @prev_configs, ActiveRecord::Base.configurations = ActiveRecord::Base.configurations, config

  ActiveRecord::Base.connects_to(database: { writing: :primary, reading: :readonly })
  SecondaryBase.connects_to(database: { writing: :primary, reading: :primary })

  ActiveRecord::Base.connection.execute("CREATE TABLE `multi_connection_test_base_models` (id integer PRIMARY KEY)")
  ActiveRecord::Base.connection.execute("CREATE TABLE `multi_connection_test_models` (id integer PRIMARY KEY)")

  ActiveRecord::Base.transaction do
    MultiConnectionTestBaseModel.create! # same connection as AR::Base
    MultiConnectionTestModel.create! # SecondaryBase connection # <- CRASH HERE
  end
ensure
  ActiveRecord::Base.configurations = @prev_configs
  ActiveRecord::Base.establish_connection(:arunit)
  ENV["RAILS_ENV"] = previous_env
end
```

In this test, the call to `MultiConnectionTestModel.create!` crashes. I assume this is because SQLite doesn't allow multiple concurrent transactions, but I'm not super familiar with it. Removing the `transaction` block removes the issue.

Here's an example of a test we have in our codebase is failing, for what I think are the same reasons:

```ruby
class ApplicationRecord
  connected_to database: { writing: :primary, reading: :replica }
end
class OAuthApplication < ApplicationRecord; end

class NeverAccessesTheReplica < ApplicationRecord
  self.abstract_class = true
  connected_to database: { writing: :primary, reading: :primary }
end
class OAuthAccessGrant < NeverAccessesTheReplica
  belongs_to :oauth_application # foreign key
end

oauth_app = OAuthApplication.create!

# expect this to create & return an OAuthAccessGrant, which descends from NeverAccessesTheReplica
# when we attempt to create the OAuthAccessGrant, we are getting a foreign key error ("no application with id = x found")
post "/api/oauth/grant", client_id: oauth_app.id
```

The test passes if we disable transactional tests.

It feels like what Rails should do is use the same connection for `ActiveRecord::Base -> :writing` and `SecondaryBase -> :writing`, rather than creating a second connection to the same database. @eileencodes mentioned at https://github.com/rails/rails/pull/40219#issuecomment-696916432 that this is unlikely. Given that, I'd love some feedback on if there is a correct approach here.

### System configuration
**Rails version**: 6.0.3.4, but the test above fails against rails master

**Ruby version**: ruby 2.7.1p83

ps. I'm sorry if this is way too confusing. I've scratched my head a lot writing it. Happy to add further clarification / answer any questions.

**Comment by ghiculescu** [comment]
ps. I tried just setting `:reading`, hoping `:writing` would inherit from `ApplicationRecord:

```ruby
class NeverAccessesTheReplica < ApplicationRecord
  self.abstract_class = true
  connected_to database: { reading: :primary }
end
```

But it didn't work either 😭. To be fair I didn't expect it to, but thought it would be cool if it did.

**Comment by ghiculescu** [comment]
Oh and in case anyone else has this problem. This is our workaround for now:

```ruby
class ThingThatNeedsToAlwaysBeFresh < ApplicationRecord
  def self.find_by(*)
    ActiveRecord::Base.connected_to(role: ActiveRecord::Base.writing_role, prevent_writes: false) do
      super
    end
  end
end
```

(we're using this for [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) models that only ever call `find_by`, but depending on the use case you may need to override other methods too)

**Comment by eileencodes** [comment]
>   SecondaryBase.connects_to(database: { writing: :primary, reading: :primary })

If you want just a writing connection establish only the writing one. Reading isn't required.

```ruby
class SecondaryBase
  self.abstract_class = true
  establish_connection :primary
```

**Comment by eileencodes** [comment]
> It feels like what Rails should do is use the same connection for ActiveRecord::Base -> :writing and SecondaryBase -> :writing, rather than creating a second connection to the same database

It can't work this way, the connections are created based on the parent class they're created from. Rails doesn't check if the connection names from the database are the same. Rails doesn't even know which configurations belong to which classes until connections are established. Configurations don't know what classes they belong to either until connections are established.

**Comment by ghiculescu** [comment]
> > SecondaryBase.connects_to(database: { writing: :primary, reading: :primary })
> 
> If you want just a writing connection establish only the writing one. Reading isn't required. Writing is required because it's the default. If you don't set a writing, establish connection will default to writing.
> 
> ```ruby
> class SecondaryBase
>   self.abstract_class = true
>   establish_connection :primary
> end
> ```

This doesn't work either :( Because it is still creating an extra connection to the same database.

Just spitballing ideas here, but what if `ConnectionHandler#establish_connection` could inherit connections? Something like this (not yet tested):

![image](https://user-images.githubusercontent.com/509837/102380167-35c56680-3f8d-11eb-91b1-c50e8e1a504a.png)

**Comment by eileencodes** [comment]
> This doesn't work either :( Because it is still creating an extra connection to the same database.

That's how it works, it's not a bug. This is behaving as designed. If you don't want a model to use the reading connection then you can avoid switching to the reading connection when using that model. You can add a middleware or around action that always wraps calls to `NeverAccessesTheReplica` in a `connected_to(role: :writing)` block and then not use the replica connection.

> Just spitballing ideas here, but what if ConnectionHandler#establish_connection could inherit connections? Something like this (not yet tested):

I don't think this is a good idea, this could very easily break existing behavior in applications. Right now the behavior, while it doesn't work for your app, is easy to reason about. If we sometimes inherited connections with abstract classes that behavior very quickly becomes cumbersome.

Maybe one day we'll add a way to ignore connections for a model but I don't see a clear way to that right now and this is behaving as architected.

**Comment by ghiculescu** [comment]
Okay, thanks for the help and the explanations!
