### ISSUE TITLE
CORS issues with direct upload to GCS after upgrade to Rails 6.1

### ISSUE THREAD

**Issue by weilandia** [rails/rails#40852]
### Steps to reproduce
Similar to #31523

Upgrade to Rails 6.1/Webpacker 5.2.1 and try to direct upload to GCS with the below CORS policy:

```
[
  {
    "origin": ["*"],
    "responseHeader": ["Content-Type", "Content-Md5"],
    "method": ["PUT", "POST", "GET", "DELETE"],
    "maxAgeSeconds": 3600
  }
]
```

### Expected behavior

It works!

### Actual behavior

```
Access to XMLHttpRequest at 'https://storage.googleapis.com/...'  from origin '...' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
### System configuration
**Rails version**: 6.1

**Ruby version**: 2.7.2

**Comment by louim** [comment]
Looking at the [sample configuration here](https://guides.rubyonrails.org/active_storage_overview.html#example-google-cloud-storage-cors-configuration):
```
[
  {
    "origin": ["https://www.example.com"],
    "method": ["PUT"],
    "responseHeader": ["Origin", "Content-Type", "Content-MD5", "Content-Disposition"],
    "maxAgeSeconds": 3600
  }
]
```
You seem to be missing  "Content-Disposition" and "Origin" response headers. Note that this is a shot in the dark as I'm not using GCS, and I don't know if it will help or not.

**Comment by weilandia** [comment]
Thank you @louim !!

**Comment by quoyi** [comment]
Thank you very much!!! @louim

**Comment by adenta** [comment]
can we tag this with 'activestorage'? Had this _exact_ same issue but wasn't able to find this until after I spent an hour throwing stuff at the wall.
