### ISSUE TITLE
6.1 - Any attempt to get URL of pre-existing attachment results in undefined method `service_name' 

### ISSUE THREAD

**Issue by AFlowOfCode** [rails/rails#40854]
### Steps to reproduce
Have pre-existing ActiveStorage attachments & amazon s3 bucket configuration from Rails 6.0. Upgrade to 6.1, change no ActiveStorage configuration (because the service has not changed), then try to get the URL of an attachment.

### Expected behavior
Retrieving a URL from an attachment should continue to work.

### Actual behavior
`rails_blob_url(user.avatar)`

`NoMethodError: undefined method 'service_name' for #<ActiveStorage::Blob:0x0000etc>
Did you mean?  service`

This happens using any of the following methods, and potentially more which I tried but did not add to the list: 
```
rails_blob_url()
rails_blob_path()
url_for()
user.avatar.service_url
```
I've looked through 6.1's changelog to find 

> DiskController is able to handle multiple services by adding a
service_name field in the generated URL in DiskService.

It's clear this is related: https://github.com/rails/rails/commit/fbb83d78c3238dab8611788f55511683796365d6 but I am not sure how to fix this breaking change nor have time to investigate why ActiveStorage attachments break the app now. I am rolling back to 6.0.3.4 & leave this issue as a record, since I cannot find any reference to this issue occurring anywhere yet.

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.1p83

**Comment by JasonBarnabe** [comment]
Did you run `rails app:update`, which creates migrations for the Active Storage tables?

**Comment by aar0nr** [comment]
It's not documented well, but ActiveStorage in 6.1 has database migration changes. If you run the `rails active_storage:install` command, it will generate the new migration file, and you can check out the differences. There is a new column named `service_name` that was added to the blobs table, and also a new table to store variants. You'll need to make these changes to your schema to avoid the error you're getting.

**Comment by rafaelfranca** [comment]
Will be fixed by https://github.com/rails/rails/pull/40791.

**Comment by AFlowOfCode** [comment]
🤦 For some reason I didn't do that even though I know it should be done without seeing db changes in the release notes.

Perhaps subconscious avoidance.. `rails app:update` can take some analysis to determine useful / necessary config changes for the update vs which have no changes & just want to overwrite custom setups,

Thank you, looking forward to several of the additions 👍
