### ISSUE TITLE
Comparision in `AddServiceNameToActiveStorageBlobs` migration

### ISSUE THREAD

**Issue by ShockwaveNN** [rails/rails#40858]
In process of upgrading my rails app to Rails 6.1
Created migration `add_service_name_to_active_storage_blobs.active_storage.rb`

But rubocop raise warning on this line:
https://github.com/rails/rails/blob/7ee31150eb590136ace3458d3a0ca29364f4b1b4/activestorage/db/update_migrate/20190112182829_add_service_name_to_active_storage_blobs.rb#L6
```
db/migrate/20201215155647_add_service_name_to_active_storage_blobs.active_storage.rb:7:29: W: Lint/AssignmentInCondition: Use == if you meant to do a comparison or wrap the expression in parentheses to indicate you meant to assign in a condition.
```

Should it be:
```ruby
if configured_service == ActiveStorage::Blob.service.name
  ActiveStorage::Blob.unscoped.update_all(service_name: configured_service)
end
```
or
```ruby
configured_service = ActiveStorage::Blob.service.name
ActiveStorage::Blob.unscoped.update_all(service_name: configured_service)
```

**Comment by composerinteralia** [comment]
Thanks for the issue! I'm going to close this along the same lines as https://github.com/rails/rails/pull/32101#issuecomment-368328081. We don't use https://github.com/bbatsov/ruby-style-guide; instead, we use rules mentioned in https://github.com/rails/rails/blob/master/.rubocop.yml.

Of course you can edit the file within your own project to match the style guide you use. But I don't think either of your alternatives will quite work. You probably want either:

```rb
if (configured_service = ActiveStorage::Blob.service.name)
  ActiveStorage::Blob.unscoped.update_all(service_name: configured_service)
end
```

or

```rb
configured_service = ActiveStorage::Blob.service.name
if configured_service
  ActiveStorage::Blob.unscoped.update_all(service_name: configured_service)
end
```

**Comment by ShockwaveNN** [comment]
@composerinteralia Thank you for your comment
I understand that rubocop style is not applied for all, but I was afraid it was some error in code, but if you 100% sure that original code is correct I'm fine with it
Thanks for your time
