### ISSUE TITLE
`ArgumentError` in Active Job `initialize` using `perform_later`

### ISSUE THREAD

**Issue by reshleman** [rails/rails#40862]
### Steps to reproduce

I've encountered some unexpected behavior in Active Job when deserializing and running a job via `perform_later` that I do not encounter with `perform_now`.

I'm not sure if this is a bug, or perhaps a misunderstanding on my end, but the inconsistent behavior is surprising.

Specifically, I'd expect to be able to set instance variables on a job instance in `initialize`. A trivial example might be:

```ruby
class TestJob < ActiveJob::Base
  def initialize(foo)
    super

    @foo = foo
  end

  def perform(*args)
    puts "foo=#{@foo.inspect} in `perform`"
  end
end
```

This works when I call `perform_now`:

```
2.6.5 :061 > TestJob.perform_now('bar')
foo="bar" in `perform`
nil
```

However I encounter an error in the job worker when I enqueue this job with `perform_later`:

```
[Worker(host:d7442d0c84cb pid:52935)] Job TestJob [396d3833-76c5-4367-84d1-ce875d858477] from DelayedJob(queue_name) with arguments: ["bar"] (id=33) (queue=queue_name) FAILED (0 prior attempts) with ArgumentError: wrong number of arguments (given 0, expected 1)
```

Although I don't fully understand what's going on here, I've traced the exception to this deserialization code, which appears to be independent of the queue adapter. It does not pass any arguments to the constructor:

https://github.com/rails/rails/blob/7ee31150eb590136ace3458d3a0ca29364f4b1b4/activejob/lib/active_job/core.rb#L50-L54

(As a workaround, I've also tried setting set instance variables inside of `perform`. However, this approach prevents the instance variables from being available to methods called on the job in, e.g., a `before_perform` callback.)

Thanks for your help!

### Expected behavior

- `perform_now` and `perform_later` should exhibit consistent behavior when instantiating a job
- Job arguments should be passed to `initialize` when deserializing and instantiating a job enqueued with `perform_later`

### Actual behavior

- `perform_now` and `perform_later` exhibit inconsistent behavior when instantiating a job
- Job arguments are not passed to `initialize` when deserializing and instantiating a job enqueued with `perform_later`

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.6.5

**Comment by rafaelfranca** [comment]
Setting instance variables in initialize is not supported on jobs. The public API is to define the `perform` method and set instance variables there.

**Comment by reshleman** [comment]
@rafaelfranca I see, thanks for clarifying.

> (As a workaround, I've also tried setting set instance variables inside of `perform`. However, this approach prevents the instance variables from being available to methods called on the job in, e.g., a `before_perform` callback.)

Is there a suggested / supported way to set instance variables so they are available in `before_perform` and `around_perform` callbacks?

**Comment by rafaelfranca** [comment]
You can set them in a callback, so you can access in later callbacks.

**Comment by reshleman** [comment]
Ah, got it. I'll give that a shot, thanks!
