### ISSUE TITLE
Rails 6.1: ActiveRecord: summing a calculation including a money typed column returns a string instead of a number

### ISSUE THREAD

**Issue by wiegand** [rails/rails#40860]
In Rails 6.0.X you could perform an ActiveRecord [sum](https://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-calculate) with an expression containing a column typed as the [PostgreSQL money column type.](https://www.postgresql.org/docs/current/datatype-money.html) This would return a BigDecimal as expected. However, in Rails 6.1 this behavior has changed. Now the expression returns a string (formatted with a dollar sign) instead of a BigDecimal. Note: if you read the value of the money column via ActiveRecord it does properly return a BigDecimal. This seems to only be an issue when running the PostgreSQL SUM aggregate function with a money type.

### Steps to reproduce
Test file here: https://gist.github.com/wiegand/2748b1644fc71c009f1043e52cfbbf04

### Expected behavior
ActiveRecord returns the sum as a BigDecimal.

### Actual behavior
ActiveRecord returns the sum as a String representing the dollar amount.

### System configuration
**Rails version**: 6.1.0

**Ruby version**: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin19]

**PostgreSQL version**: 13.1

**Comment by wiegand** [comment]
No problem. Here's the commit: https://github.com/rails/rails/commit/e10765cfa5e05a655d208e6c598a32b8dce64752.

**Comment by rafaelfranca** [comment]
@kamipo can you take a look?

**Comment by gingerlime** [comment]
I'm seeing a similar issue with time DB fields. With Rails 6

On Rails 6

```ruby
[1] > Video.for_locale(locale).sum(:play_time)
=> "122:46:41"
```

On Rails 6.1 

```ruby
[2] > Video.for_locale(locale).sum(:play_time)
=> 122 hours, 46 minutes, and 41 seconds
```
