### ISSUE TITLE
Visible validator not up to date

### ISSUE THREAD

**Issue by andrevieira11** [rails/rails#40863]
### Steps to reproduce
Follow all thee 8 steps on the rails Getting started guide

### Expected behavior
Running the application smoothly showing the amount of public articles in the home screen

### Actual behavior
Error in the "validates :status, in: VALID_STATUSES" validator 

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.2

On the "edge" version of the guide there is the correct veresion of the validator: "validates :status, inclusion: { in: VALID_STATUSES }"

**Comment by rafaelfranca** [comment]
Fixed by #40847
