### ISSUE TITLE
Implementing multi database in Rails 6.1

### ISSUE THREAD

**Issue by kapso** [rails/rails#40866]
Sorry for posting this question here, but did not get any bites on stackoverflow, so trying to get some help here : )

This is my first time implementing multi DB access in Rails and I am using version 6.1 for it.

My requirement is that all `SELECT` queries to model `Product` should go to my read replica. This is how I have setup multi DB access...

```ruby
class MultiDb < ApplicationRecord
  self.abstract_class = true

  connects_to database: { writing: :primary, reading: :primary_replica }
end

class Product < MultiDb
end

class User < ApplicationRecord
end

# database.yml
default: &default
  encoding: unicode
  pool: <%= ENV.fetch('DB_MAX_POOL') { 7 } %>

development:
  primary:
    <<: *default
    url: postgres://product_db_user:@localhost:5432/product_db
  primary_replica:
    <<: *default
    url: postgres://product_db_user:@localhost:5432/non_existing_product_db
    replica: true

```

The `non_existing_product_db` database does not exist and is meant to fail. But when I do `Product.count` from rails console, the query executes successfully, meaning the model is reading from `primary` and not `primary_replica`. Why is that? Shouldn't the query fail? ...since it should try and "read" from `primary_replica`.

Also, when I do the following...

```ruby
ActiveRecord::Base.connected_to(role: :reading) do
  Product.count
end
```

...I do see the following error - `ActiveRecord::NoDatabaseError (FATAL:  database "non_existing_product_db" does not exist)`

**Comment by eileencodes** [comment]
> But when I do Product.count from rails console, the query executes successfully, meaning the model is reading from primary and not primary_replica. Why is that? Shouldn't the query fail? ...since it should try and "read" from primary_replica.

Nope, the default database is the writing database. We have no way of knowing you want to read from the replica - especially in a real application where there may be replica lag you need to calculate before sending queries to the replica.

**Comment by kapso** [comment]
@eileencodes thanks for the response. So basically I need to do an "explicit" context switch like...

```ruby
MultiDb.connected_to(role: :reading) do
  Product.count
end
```

...or the automatic context switching? - https://guides.rubyonrails.org/active_record_multiple_databases.html#activating-automatic-connection-switching

Without the context switch, the read & write will always happen against the primary/default DB?

**Comment by eileencodes** [comment]
Yes, you either need to be explicit or use the automatic switching. Otherwise all queries will be against the primary.

**Comment by mukinabis** [comment]
@eileencodes , Why can't all INSERT/UPDATE/DELETE queries be in "writing" and all SELECT queries be in "reading"?

**Comment by mateuscruz** [comment]
@mukinabis you cannot do it with native Rails but you can do it with this gem:

https://github.com/Nasdaq/active_record_proxy_adapters

Currently, we support only Postgres but it's relatively simple to add your own custom adapter for other database systems.

Make sure you have solid, active monitoring of replication delay so you can configure the gem to better suit your needs.
