### ISSUE TITLE
Rails 5.2: issue with saving duplicate records inside a transaction

### ISSUE THREAD

**Issue by aitizazk** [rails/rails#40875]
I am upgrading my application to rails 5.2 and while investigating a test failure I saw a weird behaviour. I duplicate an object and then save both the original and duplicate inside a `ActiveRecord::Base.transaction`. the records actually fail to save (which is expected behaviour in this case) but some how after the transaction block both objects have the same id.

### Steps to reproduce
```
u1 = User.last
u2 = u1.dup

# values before the transaction block
# irb(main):003:0> u1.id
# => 1044027
# irb(main):004:0> u2.id
# => nil

ActiveRecord::Base.transaction do
# it shouldn't save as there is a uniqueness validation on `email` field that will fail
 raise ActiveRecord::Rollback unless u1.save && u2.save 
end

# values after the transaction block
# irb(main):010:0> u1.id
# => 1044027
# irb(main):011:0> u2.id
# => 1044027

```
### Expected behavior
the duplicate object `u2` should have id as `nil` as there is a 

### Actual behavior
the duplicate object `u2` have the same id as `u1`

### System configuration
**Rails version**: 5.2.4.4

**Ruby version**: ruby 2.3.8p459 (2018-10-18) [x86_64-darwin17]

**Comment by louim** [comment]
@aitizazk can you make a reproducible case using [this template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb)? Seem's like from your example I would expect `u2` to save, unless there is some uniqueness validations not shown here?

**Comment by rafaelfranca** [comment]
Also please make sure to test with Rails 6.0 since Rails 5.2 is not supported to bug fixes anymore.
