### ISSUE TITLE
Rails 6.1.0 is breaking my Specs

### ISSUE THREAD

**Issue by psantos10** [rails/rails#40871]
### Steps to reproduce

I have this line of code, which on Rails 6.0.3.4 is working fine:

```ruby
csv_file { fixture_file_upload(Rails.root.join('spec/support/files/contacts.csv'), 'text/csv') }
```

### Actual behavior

With Rails 6.1.0 is causing this error:

```
 Failure/Error: csv_file { fixture_file_upload(Rails.root.join('spec/support/files/contacts.csv'), 'text/csv') }
     
     NoMethodError:
       undefined method `file_fixture_path' for FactoryBot::SyntaxRunner:Class
```

I saw that Rails 6.1.0 release changed  this file: https://github.com/rails/rails/commit/1ab0e6b6d8070f30b2a02254070c6dd07fa56ec4 Seems to be related. 

But the PR itself does not give me any cue how can I fix the spec.

### System configuration
**Rails version**: 6.1.0
**Ruby version**: 2.7.1
ªªfactory_bot version**: 6.1.0

**Comment by rafaelfranca** [comment]
Thank you for the report. This seems to be an issue on FactoryBot. Can you open an issue there?

**Comment by abhaynikam** [comment]
@psantos10 Not sure if this is relevant to Rails version. From what I can find is `ActionDispatch::TestProcess` is not autoloaded due to which the `file_fixture_path` is throwing undefined for `FactoryBot::SyntaxRunner:Class`.

`ActionDispatch::TestProcess` autoloaded in `ActionDispatch::IntegrationTest` and not for `ActiveSupport::TestCase`. Adding `include ActionDispatch::TestProcess` should resolve the issue. 

By any change your test case file inherit from `ActiveSupport::TestCase`?

```
// test_helper.rb
class ActiveSupport::TestCase
  include ActionDispatch::TestProcess
end
```

**Comment by rafaelfranca** [comment]
@abhaynikam I don't think `TestProcess` has anything to do with this. `file_fixture_path` is defined in `ActiveSupport::TestCase`

**Comment by abhaynikam** [comment]
@rafaelfranca Oh. Sorry my bad. I am no expert here. I was trying to reproduce it on Rails 6.3 and addition of `include ActionDispatch::TestProcess` seems to resolve the issue for me so I thought I should mention it.

**Comment by psantos10** [comment]
> Thank you for the report. This seems to be an issue on FactoryBot. Can you open an issue there?

@rafaelfranca my point here is that, the same FactoryBot version with Rails 6.0.3.4 works. The problem only occurs with Rails 6.1.0 

Is there something that Rails changed and FactoryBot should implement or change also?

**Comment by psantos10** [comment]
> Thank you for the report. This seems to be an issue on FactoryBot. Can you open an issue there?

@rafaelfranca my point here is that, the same FactoryBot version wuth Rails

**Comment by rafaelfranca** [comment]
Not sure, many things in Rails changes, so my point here is that FactoryBot should investigate.

**Comment by ZilvinasKucinskas** [comment]
Previously you had to have the following:

```
FactoryBot::SyntaxRunner.class_eval do
  include ActionDispatch::TestProcess
end
```

to enable `fixture_file_upload` functionality with Rails 6.0.X.

Right now I am getting the same error, which prevents the migration to Rails 6.1.0.

If someone solved this one, let us know in the thread. 🙏

**Comment by ZilvinasKucinskas** [comment]
@psantos10 Found a solution to the problem. You can have the following in `rails_helper.rb`:

```
FactoryBot::SyntaxRunner.class_eval do
  include ActionDispatch::TestProcess
  include ActiveSupport::Testing::FileFixtures
end
```

**Comment by psantos10** [comment]
> @psantos10 Found a solution to the problem. You can have the following in `rails_helper.rb`:
> 
> ```
> FactoryBot::SyntaxRunner.class_eval do
>   include ActionDispatch::TestProcess
>   include ActiveSupport::Testing::FileFixtures
> end
> ```

Thank you @ZilvinasKucinskas 

Adding `  include ActiveSupport::Testing::FileFixtures` solved the issue. 

I only had `  include ActionDispatch::TestProcess` in place.

Thank you again
