### ISSUE TITLE
Rails 6.1.0 error when generating Active Storage links to S3 service

### ISSUE THREAD

**Issue by arye-dov-eidelman** [rails/rails#40895]
### Steps to reproduce

I'm trying to upgrade from rails 6.0.3.4 to 6.1.0
I can't generate links for active storage files stored on s3 after upgrading

Greating URLs for attachments throws a ```NoMethodError (undefined method `service_name' for #<ActiveStorage::Blob:0x0000558b5edfbeb8>)```

The same thing happens when using url_for(attachment) rails_blob_path(attachment) or attachment.url

app/models/author.rb
```
class Author < ApplicationRecord
  has_one_attached :profile_photo
end
```

config/storage.yml
```
aws:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: us-east-2
  bucket: my-bucket
```

config/environments/development.rb
```
config.active_storage.service = :aws
```

### Expected behavior

Using rails 6.0.3.4 generates links

```
rails c
Running via Spring preloader in process 14890
Loading development environment (Rails 6.0.3.4)
irb(main):001:0> Rails.application.routes.url_helpers.url_for(Author.first.profile_photo)
  Author Load (20.4ms)  SELECT "authors".* FROM "authors" ORDER BY "authors"."id" ASC LIMIT $1  [["LIMIT", 1]]
  ActiveStorage::Attachment Load (19.9ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 1], ["record_type", "Author"], ["name", "profile_photo"], ["LIMIT", 1]]
  ActiveStorage::Blob Load (42.3ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 20], ["LIMIT", 1]]
=> "http://localhost:3000/rails/active_storage/blobs/eyJfc..In19--1d0d...fe/the%20file%20name.jpg"
```

### Actual behavior

Rails 6.1.0 throws an error ```NoMethodError (undefined method `service_name' for #<ActiveStorage::Blob:0x0000558b5edfbeb8>)```

```
rails c
Running via Spring preloader in process 15751
Loading development environment (Rails 6.1.0)
irb(main):001:0> Rails.application.routes.url_helpers.url_for(Author.first.profile_photo)
  Author Load (20.3ms)  SELECT "authors".* FROM "authors" ORDER BY "authors"."id" ASC LIMIT $1  [["LIMIT", 1]]
  ActiveStorage::Attachment Load (28.3ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 1], ["record_type", "Author"], ["name", "profile_photo"], ["LIMIT", 1]]
  ActiveStorage::Blob Load (34.3ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 20], ["LIMIT", 1]]
Traceback (most recent call last):
        1: from (irb):1
NoMethodError (undefined method `service_name' for #<ActiveStorage::Blob:0x0000558b5edfbeb8>)
Did you mean?  service
```

### System configuration
**Rails version**: 6.1.0

**Ruby version**:  2.7.2p137

**Comment by EnziinSystem** [comment]
Run:
```
rails active_storage:update
rails db:migrate
```

**Comment by composerinteralia** [comment]
Thanks for the issue. A [PR](https://github.com/rails/rails/pull/40791) was recently merged that mentions `service_name` in the [6.1 release notes](https://edgeguides.rubyonrails.org/6_1_release_notes.html#active-storage-notable-changes). Running `bin/rails app:update` is the documented solution. Since this is an intentional change, I'm going to close this issue.

**Comment by dorianmariefr** [comment]
`bin/rails app:update` does far too much things, it creates a lot of files and wants to overrides a lot of files

**Comment by rafaelfranca** [comment]
Correct. But it is the recommended command to run when upgrading a Rails application. All the necessary configurations and files to a 6.1 application are generated by that command, so it is doing exactly what we expect it to do.
