### ISSUE TITLE
Support Ruby 3.0.0

### ISSUE THREAD

**Issue by tilhoft** [rails/rails#40901]
### Steps to reproduce
any rails command

### Expected behavior
working :D

### Actual behavior
rails aborted!
NameError: uninitialized constant BusinessTime::Config::SortedSet
/usr/local/bundle/gems/business_time-0.9.3/lib/business_time/config.rb:10:in `<class:Config>'
/usr/local/bundle/gems/business_time-0.9.3/lib/business_time/config.rb:8:in `<module:BusinessTime>'
/usr/local/bundle/gems/business_time-0.9.3/lib/business_time/config.rb:3:in `<top (required)>'
/usr/local/bundle/gems/business_time-0.9.3/lib/business_time.rb:9:in `<top (required)>'

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 3.0.0-preview2

https://github.com/bokmann/business_time/issues/199

**Comment by composerinteralia** [comment]
It looks like this is coming from the business_time gem, so I think the issue you created on that repo is the right place for tracking this.

**Comment by tilhoft** [comment]
Makes sense, but as the other repository seems not well maintained, (last commit was 3 years ago) maybe somebody wants to fork it, as this is the only issue with rails(6.1.0) and ruby 3.0.0(-preview2)

**Comment by tilhoft** [comment]
Sorry my bad, I thougth first that business_time gem is a dependency in rails
