### ISSUE TITLE
Rails 6.1 - problem with lazy translations inside view partial

### ISSUE THREAD

**Issue by mkasztelnik** [rails/rails#40900]
I'm trying to migrate my app into rails 6.1 and discovered braking change for the translation view helper for the lazy partial translations. 

For example I have a `organization/_form` template with `t ".title"` inside. This partial is rendered in `admin/organization/show`. In rails 6.0 this lazy translation is expanded into `organization.form.title` and in rails 6.1 into `admin.organization.show.title`.

The difference between 6.0 and 6.1 cames from the `TranslationHelper.scope_key_by_partial` method implementation: in 6.0 `@virtual_path` is used (evaluated into `organization.form`) and in 6.1 `@current_template&.virtual_path` (evaluated into `admin.organization.show`).

This change was introduced by: https://github.com/rails/rails/commit/dd7a673782f102d2b58194007bf18a8e496818e3.

**Comment by jean-francois-labbe** [comment]
I'm also facing this issue

**Comment by rafaelfranca** [comment]
Thank you for the issue. Now that you know which commit introduced the change, can you try to write a test for the expected behavior and fix this issue? Thank you.

**Comment by mkasztelnik** [comment]
Sure I will submit a PR.
