### ISSUE TITLE
Rails 5.2.4.4 AEC-256-ECB mode is throwing error while decryption

### ISSUE THREAD

**Issue by Gajendarkodela** [rails/rails#40907]
### Steps to reproduce

data = 'message to encrypt'
crypt = ActiveSupport::MessageEncryptor.new(ENV['ENCRYPT_KEY'], cipher: 'aes-256-ecb')
decrypted_pii = crypt.encrypt_and_sign(data)
crypt.decrypt_and_verify(data)
### Expected behavior
Should give the decrypted message

### Actual behavior
throwing error saying 'cant convert nil into string'

### System configuration
**Rails version**: 5.2.4.4

**Ruby version**: 2.6.6

**Comment by vinicius0197** [comment]
Hey @Gajendarkodela , I've created a failing test case for this issue. I'm actually running into a `ActiveSupport::MessageEncryptor::InvalidMessage` exception while running it, but couldn't reproduce the `can't convert nil into string` error you've mentioned.

The test case I'm running is the following:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'activesupport', '5.2.4.4'
end

require 'active_support'
require 'active_support/core_ext/object/blank'
require 'minitest/autorun'

class BugTest < Minitest::Test
  def test_decrypt
    len   = ActiveSupport::MessageEncryptor.key_len
    salt  = SecureRandom.random_bytes(len)
    enc_key = ActiveSupport::KeyGenerator.new('password').generate_key(salt, len)
    crypt = ActiveSupport::MessageEncryptor.new(enc_key, cipher: 'aes-256-ecb')
    encrypted_data = crypt.encrypt_and_sign('secret message')
    crypt.decrypt_and_verify(encrypted_data)
  end
end
```

I've noticed that this test passes if you don't specify a `cipher` to `ActiveSupport::MessageEncryptor`, or if you specify a different algorithm (like `aes-256-gcm`).

**Comment by Gajendarkodela** [comment]
Hey @vinicius0197  thanks for the response. That is what I have mentioned. issue is with ECB mode. I need to use ECB mode in my case.
I found fix for it. but need some one to update in the repo

**Comment by dark-panda** [comment]
Just a note that this issue still exists in `6-1-stable` and on `main`. The suggested fix of changing `cipher.iv = iv` to `cipher.iv = iv.to_s` still resolves the issue.
