### ISSUE TITLE
Grouped calculations return all nil values

### ISSUE THREAD

**Issue by snex** [rails/rails#40917]
### Steps to reproduce
Postgres 12

Given a table with three columns, id (primary key), fk_id (integer - in my app it is a foreign key but the problem appears even without extra tables) and result (integer or any numeric), enter in some data and then run the following in console:
```
Table.group(:fk_id).average(:result)
```

### Expected behavior
Expected behavior should be a hash with a list of fk_ids as keys and the average of the result column for those fk_ids as values.

### Actual behavior
What actually gets returned is a hash with the fk_ids as keys but nil for all values. If I run the auto-generated query in psql console, the results are correct. Other calculations such as sum, count, maximum, minimum, etc, all either incorrectly give 0s or nils as well.

### System configuration
**Rails version**: 6.1

**Ruby version**: 2.7.1

**Comment by kamipo** [comment]
Can you provide a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by snex** [comment]
The test passes when I use this template, so not sure what is going on. The issue still persists in my app that was upgraded from Rails 6.0 to 6.1. I even changed the template to use Postgres and it still passes. Are there any things to look for in settings or something that may have altered behavior from 6.0 to 6.1? I read through the changelogs and didn't see anything that should be relevant.

**Comment by esparta** [comment]
If you can't reproduce with the script then you should check on your gems that may be interfering.

**Comment by snex** [comment]
I think I found it - having the arel_extensions gem (https://github.com/Faveod/arel-extensions/) installed makes the test fail. Will open an issue over there. Thanks.
