### ISSUE TITLE
Allow ActionText::Content attachments to use configurable service

### ISSUE THREAD

**Issue by simmerz** [rails/rails#40915]
Currently, ActionText attachments use the default storage service. If we want one ActionText `has_rich_text` on a model to use a public service, the whole app needs to be public first, rather than private first, which would be my preference. Allowing a per case configuration as is possible with native-to-model attachables would allow the developer to choose their preference, but importantly allow that data-privacy-first approach.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.
