### ISSUE TITLE
action_text installation fails on rails 6.1

### ISSUE THREAD

**Issue by eddiebanks1** [rails/rails#40942]
### Steps to reproduce
On a windows 10 computer

Install ruby 2.7.2p137
Install rails 6.1.0
Install yarn 1.22.5
create a project
install action_text with command: action_text:install

### Expected behavior
action_text should install successfully. 

```
### Actual behavior
$ rails action_text:install
       rails  app:binstub:yarn
Installing JavaScript dependencies
         run  bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.0 from "."
rails aborted!
Errno::ENOEXEC: Exec format error - bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.0

Tasks: TOP => action_text:install
(See full trace by running task with --trace)
```

### System configuration
Rails 6.1.0

Ruby 2.7.2p137
![Capture](https://user-images.githubusercontent.com/56547469/103158993-e4eb1480-47bb-11eb-8788-642c0530cdf9.PNG)

**Comment by jonathanhefner** [comment]
I believe MinGW installs executables with an `.exe` file extension, and it appends the extension for you as necessary.  But `bin/yarn` [would not find `yarn.exe`](https://github.com/rails/rails/blob/7378ffb782cc7f61e3148ff746e1847e9424c6d6/railties/lib/rails/generators/rails/app/templates/bin/yarn.tt#L5-L9).  I've created #40950 to address this.

**Comment by Rex-am-I** [comment]
I am a bit (noobie) confused. I am getting the exact same error, yet this is marked as closed. I assumed this meant the issue was resolved. Can somebody please help me here?

ruby 2.6.6
rails 6.1.1
yarn 1.22.5

"Exec format error - bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.1 (Errno::ENOEXEC)"

**Comment by eddiebanks1** [comment]
Are you running your set on Windows directly or are you using WSL2

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Rex-am-I** [comment]
on Windows 10 directly

**Comment by eddiebanks1** [comment]
That's why you are having that error. I had the same experience. You need to run your ruby on rails  installation on windows subsystem for linux. The current version is version 2. I.e wsl2. Its basically Linux running on window. Google it. Once you set up WSL2 on your Windows 10 OS, you can go ahead and run your ruby rails on the wSL and you would stop  seeing those errors.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Rex-am-I** [comment]
Thanks a bunch, @eddiebanks1. Not to minimize the incredible work that folks put in building these functionalities, but is there no easier way to install this? Or to put in another way, is there likely to be a non-WSL way to this soon? I wish I could help, but my development skills are, to put it nicely, severely limited,

**Comment by eddiebanks1** [comment]
when i started by running my rails setup directly on window, i find that installing some bundle and package gives error like the one i encountered and posted above, i believe you are experience the same issue now. The issue as @jonathanhefner explained has got to do with file reference.  Search for yarn.exe in bin/yarn #40950. You can follow that thread if you want to try to resolve the issue without switching to running rails on WSL.

**Comment by Rex-am-I** [comment]
This problem is apparently resolved in rails 6.1.2. Thanks to the Rails Stars!

**Comment by Rex-am-I** [comment]
I spoke too soon! In rails 6.1.2 action_text is still not installed. Only the error message is not shown during the attempted installation.

### Actual behavior
$ rails action_text:install
       rails  app:binstub:yarn
Installing JavaScript dependencies
         run  bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.0 from "."
c:\rails\blogtest>

... and action_text is still not reflected in the package.json file.

**Comment by jonathanhefner** [comment]
@Rex-am-I With Rails 6.1.2 the output [should](https://github.com/rails/rails/blob/v6.1.2/actiontext/lib/generators/action_text/install/install_generator.rb#L15) look something like:

```
run path/to/ruby.exe bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.0 from "."
```

(Notice the extra `path/to/ruby.exe`.)

Can you verify that the project is using Rails 6.1.2 by running `bundle exec rails --version`?

Also, could you post the contents of your project's `bin/yarn`?

**Comment by Rex-am-I** [comment]
Here's the info:

Installing JavaScript dependencies
         run  C:/Ruby26-x64/bin/ruby.exe bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.2 from "."

Rails version is 6.1.2

Contents of bin/yarn:

#!/usr/bin/env ruby.exe
APP_ROOT = File.expand_path('..', __dir__)
Dir.chdir(APP_ROOT) do
  yarn = ENV["PATH"].split(File::PATH_SEPARATOR).
    select { |dir| File.expand_path(dir) != __dir__ }.
    product(["yarn", "yarn.exe"]).
    map { |dir, file| File.expand_path(file, dir) }.
    find { |file| File.executable?(file) }

  if yarn
    exec yarn, *ARGV
  else
    $stderr.puts "Yarn executable was not detected in the system."
    $stderr.puts "Download Yarn at https://yarnpkg.com/en/docs/install"
    exit 1
  end
end

**Comment by jonathanhefner** [comment]
@Rex-am-I There seem to be two underlying issues here.

The main issue is that `bin/yarn` was generated by Rails 6.1.1 but not updated by Rails 6.1.2.  I've submitted #41399 to address this.

The secondary issue is that the error messages from `bin/yarn` are being swallowed by the Action Text installer.  I've submitted #41400 to address this.

Thanks for bringing these up!

**Comment by jonathanhefner** [comment]
@Rex-am-I  I forgot to mention a workaround: try deleting your `bin/yarn` and running `rails action_text:install` again.

**Comment by Rex-am-I** [comment]
@jonathanhefner,  thanks so much. The work-around worked!
