### ISSUE TITLE
ActiveRecord::Relation "merge" new behavior and incorrect deprecation warning

### ISSUE THREAD

**Issue by balbesina** [rails/rails#40944]
### Steps to reproduce
When using "not equal to" scopes the warning occurs saying we should use `merge` with **rewhere: true**.

**Test**
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '=6.1.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :foos, force: true do |t|
    t.string :status
  end
end

class Foo < ActiveRecord::Base
  STATUSES = %i[a b c d e f].freeze
  enum status: STATUSES.index_with(&:to_s), _prefix: true
end

# yup, ugly, but quick example
@@warned = false

require 'active_support/deprecation'

ActiveSupport::Deprecation.prepend(Module.new {
  def warn(message, *)
    super
    @@warned = true if message.respond_to?(:include?) && message.include?('rewhere: true')
  end
})

class BugTest < Minitest::Test
  def test_association_stuff
    Foo.not_status_a.merge(Foo.not_status_b, rewhere: false).to_sql
    assert_equal false, @@warned
  end
end
```

Consider we've got model with status field enum.
```ruby
class Foo < ApplicationRecord
  STATUSES = %i[a b c d e f].freeze
  enum status: STATUSES.index_with(&:to_s), _prefix: true
end
```
The following code
```ruby
Foo.not_status_a.merge(Foo.not_status_b).to_sql
```
should generate sql similar to
```sql
select * from foos where foos.status != 'a' and  foos.status != 'b'
```
Which is correct and works as expected, but we receive a deprecation warning:
```
DEPRECATION WARNING: Merging ("foos"."status" != $1) and ("foos"."status" != $1) no longer maintain both conditions, and will be replaced by the latter in Rails 6.2. To migrate to Rails 6.2's behavior, use `relation.merge(other, rewhere: true)
```
If we follow the suggestion and use **rewhere: true**, our sql becomes wrong (doesn't exclude 'a' status):
```sql
select * from foos where foos.status != 'b'
```
If we use **rewhere:false** we still see a deprecation warning.

### Expected behavior

Not receive a warning with **rewhere:false** option

okish: receive a warning with suggestion to change to merge(scope, rewhere: false) if rewhere was nil.
better: make `merge` work as **rewhere:false** by default - this would require no effort for ppl to migrate.
good: revert unnecessary `merge` behavior change.
godlike: revert the change and fix `merge` to **never replace** conditions

### Actual behavior
We receive a warning saying that we should use merge(scope, rewhere: **true**).

### System configuration
**Rails version**:
6.1.0
**Ruby version**:
2.7.2

**Comment by kamipo** [comment]
In this case, use `Foo.not_status_a.and(Foo.not_status_b)`. #39558

This deprecation is introduced by #39328.

Basically `Relation#merge` behaves almost like `Hash#merge`, but remains both conditions on some conditions due to attribute detection didn't work (e.g. `Arel::Nodes::NotEqual`, etc), so it is harder to predict which condition is replaced or remained.

The purpose of #39328 is to unify to `Relation#merge` behaves always like `Hash#merge`.
If you want both conditions are remained, use `Relation#and` instead in Rails 6.1.

**Comment by kamipo** [comment]
Closing this since it is a deliberate change.

**Comment by jairovm** [comment]
You guys aware of this case, when a default_scope is used and it triggers this Deprecation Warning ? https://github.com/ErwinM/acts_as_tenant/issues/251#issuecomment-812762541

Thanks

**Comment by ghiculescu** [comment]
^ made an issue for this https://github.com/rails/rails/issues/42759
