### ISSUE TITLE
ruby 3.0.0: undefined method `arity' for

### ISSUE THREAD

**Issue by clwy-cn** [rails/rails#40957]
### Steps to reproduce

This error is only in ruby 3.0.0
if I use ruby 2.6.6 or 2.7.2，it works fine。

This code is causing the problem：

```
acts_as_nested_set
```

### Actual behavior
undefined method `arity' for {:class_name=>"Guide::Page", :foreign_key=>"parent_id", :primary_key=>"id", :counter_cache=>:children_count, :inverse_of=>:children, :polymorphic=>false, :touch=>false, :optional=>true}:Hash

![image](https://user-images.githubusercontent.com/57120683/103219364-78594c80-4958-11eb-880f-50373f2364fc.png)

### System configuration
**Rails version**: 6.1

**Ruby version**: 3.0.0

**Comment by sergiopantoja** [comment]
I hit this as well and it turned out to be an issue with my code. For anybody else coming across this, double check that you're using Ruby 3's new keyword argument syntax correctly.

**Comment by ahmeij** [comment]
Ran into the same problem here, for me the problem was in an older version of awesome_nested_set, updating it fixed the problem.

**Comment by ykamin-booth** [comment]
I'm still seeing this issue with rails 6.1.6.1 and ruby 3.1.2, despite combing through my code to verify that I'm not using keyword arguments in any of my methods and combing through my gemfile (and removing gems willy nilly) to make sure everything is compatible with Ruby 3. Seeing very little info elsewhere on this topic.

**Comment by mck9** [comment]
This is still broken when if: parameter is an array e.g.:

validates :password,              presence: true, length: { minimum: 6 }, if: [:password_required?, :account?]
