### ISSUE TITLE
ActionText + Trix: Tags and attributes only stripped on editor

### ISSUE THREAD

**Issue by colmexdev** [rails/rails#40955]
Hi there! First of all, I'd like to say this is a really impressive and straightforward addition for rich text editing. Thanks a lot.

I've been reading through the docs and issues trying to figure out something I've came across:
I've customised the allowed tags and attributes as it's stated in [#36725](https://github.com/rails/rails/issues/36725) and I've managed to store rich text successfully and displayed it correctly; nonetheless, when I try to edit the content, it appears unformatted (except for the default tags: strong and em).

#### Initial custom text editing
![text_on_creating](https://user-images.githubusercontent.com/29102027/103183468-4d97c700-4878-11eb-9ae8-086f8045a274.png)

#### Custom text showing
![text_on_show](https://user-images.githubusercontent.com/29102027/103183520-9a7b9d80-4878-11eb-9225-45daa0f5809c.png)

#### Custom text editing
![text_on_editing](https://user-images.githubusercontent.com/29102027/103183560-d282e080-4878-11eb-922b-d1d31d5486b2.png)

Besides, I've configured Trix to override *strong* and *em* tags to be *b* and *i*, respectively. This setting is also reverted on edition.

I'd like to know where can the error be. I'm using Turbolinks and Webpacker inside my app, if that helps. It's configured in the following order inside `javascript/packs/application.js`:

```
require("trix")
require("@rails/actiontext")
require('backend') # Custom Trix settings
```

And inside `backend.js`:

```
addEventListener("trix-initialize", (event) => {
	configTrix(); # Setting custom tags and attributes for editor.
	extendTrix(event); # Extends the toolbar as seen on pictures.
})
```
### Steps to reproduce

1. Follow ActionText docs for setting a rich text area into a model.
2. Set custom tags and attributes into JS function for Trix extended toolbar.
3. Add custom initializer to add custom scrubber for tags/attributes whitelisting.
4. Create rich text content.
5. Save it.
6. Edit the recently saved rich text content.

### Expected behavior
The rich text with custom tags and attributes should persist in every situation (render and edition).

### Actual behavior
Rich text is stripped from custom tags and attributes only on editor.

### System configuration
**Rails version**: 6.1
**Ruby version**: 2.7.2

Thank you in advance for your attention!

**Comment by r-obeen** [comment]
I have the same issue ! Anyone has a solution ? Thanks

**Comment by YutoYasunaga** [comment]
Does anyone have solution to resolve this?

**Comment by colmexdev** [comment]
A bit late by now, but I managed to solve this situation.

   The fact that Trix is executed as an immediate function causes troubles when working with JS bundlers because it is no longer seen as a global function. So far, I've tested with Webpack and esbuild/Propshaft and here's how I solved it:

# For Webpack (Webpacker)
In ```config/webpack/environment.js``` this lines must be added:

```
environment.plugins.append('Provide', 
	new webpack.ProvidePlugin({
		Trix: "trix"
               //Some other plugins that must be treated as global.
	})
)
```

After that, every custom config made to Trix will be persisted for every ```<trix-editor>``` element.

# For esbuild / Propshaft
This one is fairly simple. In the ```<head>``` section of your HTML layout, add this lines:

```
<%= javascript_include_tag "trix/dist/trix", "data-turbo-track": "reload", defer: true %>
<%= javascript_include_tag "path/to/trix/customization", "data-turbo-track": "reload", defer: true %>
```

Where the second file should contain the custom extensions to the editor.

   Hope this can help anyone else in the future with this same issue!

**Comment by Furqanameen** [comment]
Can we add more options while using this rich text? 
Like the below image attached.?

I integrated rich text into my project but there are very few mean limited options I want some extra like below attached..
THanks
![rich tect editor](https://github.com/rails/rails/assets/38700276/5596c642-6a67-4ff6-9354-b244aa06f63e)

**Comment by fillipeppalhares** [comment]
Hello guys, maybe this can help someone with the same issue. just a quick reminder: if you're customizing your trix editor within stimulus `connect()`, remind to do it outside the `trix-initialize` listener, since these configs need to be set before initialization.

I actually went a step further and added the attributes in another file and imported them inside `application.js`:

```js
import "trix"
import "./services/custom_trix"
```

```js
// custom_trix.js
Trix.config.textAttributes.underline = {
  tagName: "u",
  style: { textDecoration: "underline" },
  inheritable: true,
  parser: function (element) {
    var style = window.getComputedStyle(element)
    return style.textDecoration === "underline"
  }
}

Trix.config.textAttributes.subscript = {
  tagName: "sub",
  inheritable: true,
}

Trix.config.textAttributes.superscript = {
  tagName: "sup",
  inheritable: true,
}

for (let i = 2; i <= 6; i++) {
  let heading = `heading${i}`

  Trix.config.textAttributes[heading] = {
    tagName: `h${i}`,
    inheritable: true
  }
}

Trix.config.textAttributes.highlight = {
  tagName: "mark"
}

```
