### ISSUE TITLE
Ability to use `unsigned bigint` as the default primary key?

### ISSUE THREAD

**Issue by joshuapinter** [rails/rails#40967]
### Steps to reproduce
1. Create a table with the default primary key (i.e. without specifying `id` options in the `create_table` migration definition).

  ```ruby
  create_table :products do |t|
  end
  ```
2. Look at the table definition and see that the default `id` column created is a (signed) `bigint`:
  ![image](https://user-images.githubusercontent.com/180819/103298630-fe58b000-49b7-11eb-8866-b8191946f316.png)

### Workaround
I know that we can manually override the default primary key yourself with something like this: 

```ruby
create_table :products, id: false do |t|
  t.bigint :id, unsigned: true, null: false
end
```

![image](https://user-images.githubusercontent.com/180819/103299314-783d6900-49b9-11eb-85b9-d246d8312e9b.png)

But for something like this, we want all of our primary key columns to be the same of type `unsigned bigint`. 

### Question and Proposal
It appears that the default primary_key column is set [here](https://github.com/rails/rails/blob/401ce9dd3d68bb550c92d40c31dc4c4e564eb6b9/activerecord/lib/active_record/connection_adapters/mysql/schema_definitions.rb#L75):

```ruby
when :primary_key
  type = :integer
  options[:limit] ||= 8
  options[:primary_key] = true
```

Is there any value or support in a change that would allow you to specify the default primary key to be unsigned by default? And, is there a reason why signed was chosen as the default in the first place?

Thanks!

### System configuration
**Rails version**: master

**Ruby version**: 2.7.2p137

**Comment by rafaelfranca** [comment]
> And, is there a reason why signed was chosen as the default in the first place?

Not all databases support unsigned integers. In fact only MySQL of all the three other db adapters Rails support has it.

> Is there any value or support in a change that would allow you to specify the default primary key to be unsigned by default?

I believe we can make this change for MySQL, guaranteed that we keep the old behavior by default in applications using migrations older than 6.2. Are you interested in making that change?

**Comment by rafaelfranca** [comment]
BTW, closing this since it is not an issue and it is more a feature request and we don't take feature requests in the issue tracker.

**Comment by joshuapinter** [comment]
Sorry to bug you again @rafaelfranca. :) 

> I believe we can make this change for MySQL, guaranteed that we keep the old behavior by default in applications using migrations older than 6.2. Are you interested in making that change?

Absolutely. I already did a quick [fork and change](https://github.com/cntral/rails/commit/cfb6c72121bcb31ceb653a8c377f979b212e8dd7) to get us up and running but will look at making this a backwards change when time frees up.

A couple of quick clarification questions with this change: 

1. Do we want to make `unsigned` the default going forward with MySQL databases (i.e. 6.2+) or is this an opt-in thing?

2. For all migrations targeted for < 6.2, it remains as `signed`, correct?

Thanks.

**Comment by rafaelfranca** [comment]
> 1. Do we want to make `unsigned` the default going forward with MySQL databases (i.e. 6.2+) or is this an opt-in thing?

We should make the default.

> 2\. For all migrations targeted for < 6.2, it remains as `signed`, correct?

Correct.
