### ISSUE TITLE
ActiveRecord.update => Result

### ISSUE THREAD

**Issue by chmich** [rails/rails#40978]
### Steps to reproduce
```
ModelName.update(name: 'kjllk')
```

please update the doku :)

### Expected behavior
https://apidock.com/rails/ActiveRecord/Base/update/class
Result should be the object

### Actual behavior
i earn a true or false

### System configuration
**Rails version**: 6

**Ruby version**:

**Comment by jonathanhefner** [comment]
The page you linked is for an older version of Rails.  Also, apidock.com is not the official documentation.  Here is the official documentation for Rails 6.0.3: https://api.rubyonrails.org/v6.0.3/classes/ActiveRecord/Persistence.html#method-i-update

It looks correct, so I will close this.  If you find an error in the documentation, feel free to open a PR!
