### ISSUE TITLE
ActionMailer test environment not recognizing url options from config

### ISSUE THREAD

**Issue by redbassett** [rails/rails#40972]
### Steps to reproduce

Open this test repo and run `rake test:mailers`:
https://github.com/redbassett/HelperUrlTest

### Expected behavior

Resource url/path is returned as seen in development server behavior without additional code in the test environment configuration.

### Actual behavior

Error is thrown:

> ThingMailerTest#test_mail_action:
> NoMethodError: undefined method `thing_url' for #<ThingMailerTest:0x00007fb3954c2db8>

Referring to this line in the test file:
```ruby
class ThingMailerTest < ActionMailer::TestCase
  test "mail_action" do
    [...]
    assert_match thing_url(Thing.new(id: 1)), mail.body.encoded
  end
end
```

Add the following include line to `test/mailers/thing_mailer_test.rb` and run `rake test:mailers` again:
```ruby
class ThingMailerTest < ActionMailer::TestCase
  include Rails.application.routes.url_helpers

  [...]
end
```

Error is thrown:

> ThingMailerTest#test_mail_action:
> ArgumentError: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true

Add the following line at the bottom of `config/environments/test.rb` and run `rake test:mailers` again:

```ruby
HelperUrlTest::Application.default_url_options = HelperUrlTest::Application.config.action_mailer.default_url_options
```

Test now runs without error and passes.

### System configuration
**Rails version**:
`Rails 6.0.3.4`
**Ruby version**:
`ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]`

**Comment by rafaelfranca** [comment]
Can you expand the steps for reproduction? For example

> * Call a resource route: `my_resource_url()`

Call where? Inside the mailer? Inside the template? Inside the test?

**Comment by redbassett** [comment]
I added a location for the url helper call in the original issue. I will look into building a test repo soon, currently troubleshooting inside an existing codebase.

**Comment by redbassett** [comment]
@rafaelfranca Updated original issue message with demo repo and steps to repro in that repo.

Ha, repro in that repo is a fun sentence!

**Comment by rafaelfranca** [comment]
hahaha. Thank you. That will help us to debug.

**Comment by sooyang** [comment]
When you include `include Rails.application.routes.url_helpers` inside `ThingMailerTest`, a bunch of modules are inserted to the `ThingMailerTest` ancestors chain.  

`ThingMailerTest` will gain class method - `default_url_options`. However, the `default_url_options` is always an empty hash `{}` despite `config.action_mailer.default_url_options = { host: 'example.com' }` is being set.

Looking up the ancestors chain, we will be able to see the following:
- The superclass for `ThingMailerTest` is `ActionMailer::TestCase`
- The superclass for `ActionMailer::TestCase` is `ActiveSupport::TestCase`

`ThingMailerTest` did not inherit from `ActionMailer::Base` class hence the `default_url_options` is empty.

I've seen recommendations of setting `Rails.application.routes.default_url_options[:host]= 'example.com' ` inside `test.rb` 
which is similar to what you've done to make the spec pass.
