### ISSUE TITLE
ActiveRecord Update Result

### ISSUE THREAD

**Issue by chmich** [rails/rails#40979]
### Steps to reproduce
```
ModelName.update(name: 'kjllk')
```

### Expected behavior
https://apidock.com/rails/ActiveRecord/Base/update/class
Result should be the object whether it succeeds or not

### Actual behavior
i earn a true or false

### System configuration
**Rails version**: 6.0.3

### soulution
please update the doku
**or** change the behaviour of update method (=> i would prefer this)

**Comment by jonathanhefner** [comment]
Duplicate of #40978.
