### ISSUE TITLE
Add a dismissive assertion to check redirection "assert_not_redirected_to"

### ISSUE THREAD

**Issue by sandip-mane** [rails/rails#40975]
Currently, there no way to check whether the redirection was dismissive of particular URL.

### Expected behaviour
Should be able to use the following method.
```
assert_not_redirected_to controller: "home", action: "index"
assert_not_redirected_to "http://localhost:3000/dashboard"
assert_not_redirected_to %r(/dashboard)
```

**Comment by rafaelfranca** [comment]
Closing in favor of the PR. We don't accept issues for feature requests.
