### ISSUE TITLE
mailers previews not auto loaded from test/mailers/previews

### ISSUE THREAD

**Issue by dorianmariefr** [rails/rails#40971]
### Steps to reproduce

- have some mailer previews in `test/mailers/previews/user_mailer_preview.rb`

e.g.

```ruby
class UserMailerPreview < ActionMailer::Preview
  def confirmation_email
    UserMailer.with(user: User.last!).confirmation_email
  end

  def reset_password_email
    User.last!.update(reset_password_token: SecureRandom.hex)
    UserMailer.with(user: User.last!).reset_password_email
  end
end
```

### Expected behavior

- Going to http://localhost:3000/rails/mailers/ shows the preview list

### Actual behavior

- Going to http://localhost:3000/rails/mailers/ doesn't show any preview

### System configuration

**Rails version**: `6.1.0`

**Ruby version**: `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]`

### Workaround

add `config.action_mailer.preview_path = Rails.root.join("test/mailers/previews")` in `config/environments/development.rb`

**Comment by rafaelfranca** [comment]
Can you provide an example application that reproduce the issue?

**Comment by rafaelfranca** [comment]
I just tried this in a new app and it is working fine:

```
rails new foo
cd foo
rails generate mailer user_mailer
rails s
```

And them I went to http://localhost:3000/rails/mailers/. This is the result:

<img width="437" alt="Screen Shot 2020-12-29 at 6 50 25 PM" src="https://user-images.githubusercontent.com/47848/103321241-b8770880-4a06-11eb-9495-ea0f960b98e6.png">

**Comment by dorianmariefr** [comment]
> Can you provide an example application that reproduce the issue?

I tried it on a new app and it works like you saw. Can't reproduce it :(

here is my `config/environments/development.rb` maybe it helps:

```ruby
Rails.application.configure do
  config.cache_classes = false
  config.eager_load = false
  config.consider_all_requests_local = true
  config.action_controller.perform_caching = false
  config.cache_store = :null_store
  config.active_storage.service = :local
  config.action_mailer.raise_delivery_errors = false
  config.action_mailer.perform_caching = false
  config.active_support.deprecation = :log
  config.active_record.migration_error = :page_load
  config.active_record.verbose_query_logs = true
  config.assets.debug = true
  config.assets.quiet = true
  config.file_watcher = ActiveSupport::EventedFileUpdateChecker
  config.i18n.raise_on_missing_translations = true
  config.hosts << ENV.fetch("HOST") if ENV["HOST"].present?
  config.action_mailer.preview_path = Rails.root.join("test/mailers/previews")
end
```

**Comment by dorianmariefr** [comment]
and my `config/application.rb`:

```ruby
require_relative 'boot'

require 'rails/all'

Bundler.require(*Rails.groups)

module Socializus
  class Application < Rails::Application
    config.load_defaults 6.1

    config.generators.test_framework = nil

    config.i18n.available_locales = [:en, :fr, :es, :pt, :it, :de]

    config.secret_key_base = ENV.fetch("SECRET_KEY_BASE")

    config.time_zone = "Europe/Paris"

    config.active_job.queue_adapter = :delayed_job
  end
end
```

**Comment by rafaelfranca** [comment]
I don't see anything out of the ordinary in your configs. Sorry I can't help more without a way to reproduce since it is working in new applications and even other applications that I have here. Feel free to ask questions on this issue if you find pointers of what is wrong.

**Comment by dorianmariefr** [comment]
I logged the preview path and it's `/Users/dorianmariefr/src/current/socializus/spec/mailers/previews` (from `lib/action_mailer/preview.rb:123`), maybe it's because I have rspec installed

**Comment by dorianmariefr** [comment]
seems like either an intended or a bug from rspec-rails

**Comment by agirlnamedsophia** [comment]
@dorianmariefr I see this same problem. Can you share how you resolved it? Thank you!
