### ISSUE TITLE
Integer column should reject non-number string that start with number

### ISSUE THREAD

**Issue by cklll** [rails/rails#40988]
### Steps to reproduce

**Migration**
Create 2 tables. 
- One with integer column
- One with integer column but it's also a reference
```ruby

class CreatePosts < ActiveRecord::Migration[6.0]
  def change
    create_table :posts do |t|
      t.integer :counter
    end
  end
end

class CreateComments < ActiveRecord::Migration[6.0]
  def change
    create_table :comments do |t|
      t.references :post
    end
  end
end
```

**Models**
```ruby
class Comment < ApplicationRecord
  belongs_to :post, class_name: "Post", foreign_key: "post_id"
end

class Post < ApplicationRecord
end
```

**Create Post and Comment with rails console**
```
irb(main):011:0> Post.create!(counter: '1a')
   (0.7ms)  BEGIN
  Post Create (12.9ms)  INSERT INTO "posts" ("counter") VALUES ($1) RETURNING "id"  [["counter", 1]]
   (4.7ms)  COMMIT
=> #<Post id: 1, counter: 1>
irb(main):012:0> Comment.create!(post_id: '1a')
   (0.8ms)  BEGIN
  Post Load (4.4ms)  SELECT "posts".* FROM "posts" WHERE "posts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Comment Create (34.7ms)  INSERT INTO "comments" ("post_id") VALUES ($1) RETURNING "id"  [["post_id", 1]]
   (15.2ms)  COMMIT
=> #<Comment id: 1, post_id: 1>
```

### Expected behavior
`post.counter` and `comment.post_id` should be null 

### Actual behavior
`post.counter` and `comment.post_id` is `1`. 
Reason is that `String#to_i` will truncate the string if the string start with number. e.g.
```
irb(main):008:0> '1a'.to_i
=> 1
```

### System configuration
**Rails version**:
```
irb(main):014:0> Rails.version
=> "6.0.3.4"
```

**Ruby version**:
```
irb(main):017:0> RUBY_VERSION
=> "2.7.2"
```

### Potential Fix
https://github.com/rails/rails/blob/2a12fe0b122e37e3321d4a53af013a2eb596ccd1/activemodel/lib/active_model/type/integer.rb#L44
This line should be changed to 
```ruby
Integer(value) rescue nil
# or
Integer(value, exception: false)
```

```
irb(main):019:0> Integer('1a', exception: false)
=> nil
irb(main):020:0> Integer('1', exception: false)
=> 1
```

### My thought
I understand that this is a huge behavior change. But I feel this is really a bug.
This cause a very unexpected behavior, especially when it's a foreign key. It failed silently.
I wonder if this is something discussed before and what is the rationale of against it.
It this is too breaking, should we introduce a flag and by default, it should change `1a` to `nil`?

### Edit
Digging through the code, I notice that there is a test case covering this
https://github.com/rails/rails/blob/a94315b94edbaadd97b751e3ab375ea8032dcb79/activemodel/test/cases/type/integer_test.rb#L14

Here is the code from Ruby
https://github.com/ruby/ruby/blob/68ea7720b367fe84da601cdbc61cb0d651c3221b/string.c#L5954-L5984
From the comment, seems that they have put some thought during the implementation and this is not a bug or an unintended behavior.

So probably this is the intended behavior from both Ruby and Rails but I am not quite convinced this is the user expectation. At least not in Rails world IMHO

Anyway, please feel free to close the issue and I could fix our problem at application level

**Comment by ysnga** [comment]
I recently faced similar problem... 

ActiveRecord changes String value into 0 when it is assigned to integer column. I read Rails code and realized that Ruby's to_i method changes String into 0. (Like 'abc'.to_i => 0)

I was confused about what ActiveRecord did, so I agree that non-numeric values should be nil. 

Here's what I rewrote some test code... 

```ruby
test "simple values" do
  type = Type::Integer.new
  assert_nil type.cast("")
  assert_equal 1, type.cast(1)
  assert_equal 1, type.cast("1")
  assert_equal nil, type.cast("1ignore")
  assert_equal nil, type.cast("bad1")
  assert_equal nil, type.cast("bad")
  assert_equal 1, type.cast(1.7)
  assert_equal 0, type.cast(false)
  assert_equal 1, type.cast(true)
  assert_nil type.cast(nil)
end
```

**Comment by intrip** [comment]
Personally I think this would add a backward incompatibilities in existing apps. As you mentioned you can always force an integer in your app.

**Comment by ghiculescu** [comment]
I think this should be handled at the application level.
