### ISSUE TITLE
active storage generator/migrations don't respect active_record's primary_key_type

### ISSUE THREAD

**Issue by josh-m-sharpe** [rails/rails#40986]
Steps to repro:

Configure your app to generate tables with UUID primary keys:
config/application.rb:
```
  config.generators do |g|
    g.orm :active_record, primary_key_type: :uuid
  end
```

Run the ActiveStorage generator:
`bin/rails active_storage:install`

The generated migrations all lack the `id: :uuid` option for create_table and `type: :uuid` for foreign keys.
The `t.references :record,   null: false, polymorphic: true, index: false` is particularly concerning because it points back to normal models that (given the above application-wide configuration) likely have UUID primary keys.

Expectations:
Rails generators would honor rails configuration.  So, at a minimum all the new tables and internal relationships should use UUIDs in this case.

The `record` relationship is tricky since who knows what combination of integer/uuid/string foreign key type it should be given the app state.  That said, if the above `application.rb` config is in place, if feels like an integer is not correct.  Maybe throw a comment (or a raise statement) in that migration which calls attention to the choice the application developer needs to make?

**Comment by fatkodima** [comment]
> Run the ActiveStorage generator:
`bin/rails active_storage:install`

This command does not run a "generator" per se, but just simply copies the predefined engine's (`active_storage`) migration files (https://github.com/rails/rails/blob/main/activestorage/db/migrate/20170806125915_create_active_storage_tables.rb) into `db/migrations` folder.

Yes, while this feature probably will be useful, it will greatly complicate the existing code. You can always manually edit the copied migration files however you like.

@rafaelfranca Wdyt on this?

**Comment by eadz** [comment]
We just came across this issue. Please please, respect the PK type configured in rails. 

The logic doesn't have to be super complicated, it could be two different copies of the migration - one for uuids and one for ints.

**Comment by eadz** [comment]
And/or as suggested, throw an error, or print a big warning.

**Comment by zzak** [comment]
@eadz We generally don't accept feature requests here, and prefer [discuss](https://discuss.rubyonrails.org/) for that. However, I can see you may have an idea for a relatively small change with meaningful impact. How do you feel about writing a PR for this?

**Comment by eadz** [comment]
@zzak this isn't a feature request, it's a bug report. 

While under the hood it's "not a generator", to the end user, it appears like one. 

The real nasty thing about this, is your application will continue to work, but UUIDs will be truncated to INTs in the foreign key reference ( another rails bug ).

**Comment by zzak** [comment]
@eadz I get what you mean, sorry if it sounded like I was trying to push you out, I wasn't. What I meant was this is the current behavior, and changing it would either require significant work or introduce another way to generate this file (possibly) -- given that I would consider this a feature. But I can see how it's both a bug too.

That said, I'm happy to take a look at providing a workaround for this, I was just reading into the internals of `bin/rails active_storage:install` so if you have any ideas or want to help contribute a patch let me know!

**Comment by eadz** [comment]
I will look into it. I think possibly the bug should be fixed in ActiveRecord as well.

**Comment by fatkodima** [comment]
@zzak 
Wdyt on something like this?
```diff
--- a/activestorage/db/migrate/20170806125915_create_active_storage_tables.rb
+++ b/activestorage/db/migrate/20170806125915_create_active_storage_tables.rb
@@ -1,6 +1,6 @@
 class CreateActiveStorageTables < ActiveRecord::Migration[5.2]
   def change
-    create_table :active_storage_blobs do |t|
+    create_table :active_storage_blobs, id: primary_key_type do |t|
       t.string   :key,          null: false
       t.string   :filename,     null: false
       t.string   :content_type
@@ -18,10 +18,10 @@ def change
       t.index [ :key ], unique: true
     end

-    create_table :active_storage_attachments do |t|
+    create_table :active_storage_attachments, id: primary_key_type do |t|
       t.string     :name,     null: false
-      t.references :record,   null: false, polymorphic: true, index: false
-      t.references :blob,     null: false
+      t.references :record,   null: false, polymorphic: true, index: false, type: primary_key_type
+      t.references :blob,     null: false, type: primary_key_type

       if connection.supports_datetime_with_precision?
         t.datetime :created_at, precision: 6, null: false
@@ -30,15 +30,22 @@ def change
       end

       t.index [ :record_type, :record_id, :name, :blob_id ], name: "index_active_storage_attachments_uniqueness", unique: true
-      t.foreign_key :active_storage_blobs, column: :blob_id
+      t.foreign_key :active_storage_blobs, column: :blob_id, type: primary_key_type
     end

-    create_table :active_storage_variant_records do |t|
-      t.belongs_to :blob, null: false, index: false
+    create_table :active_storage_variant_records, id: primary_key_type do |t|
+      t.belongs_to :blob, null: false, index: false, type: primary_key_type
       t.string :variation_digest, null: false

       t.index %i[ blob_id variation_digest ], name: "index_active_storage_variant_records_uniqueness", unique: true
-      t.foreign_key :active_storage_blobs, column: :blob_id
+      t.foreign_key :active_storage_blobs, column: :blob_id, type: primary_key_type
     end
   end
+
+  private
+
+  def primary_key_type
+    config = Rails.application.config.generators
+    config.options[config.orm][:primary_key_type] || :bigint
+  end
 end
```

This is the simplest implementation I can think of. It checks which type is configured and uses it, or fallbacks to default.

**Comment by zzak** [comment]
@fatkodima It would help to see some tests, but I think this is a good step in the right direction 👍
