### ISSUE TITLE
ActiveModel::AttributeMethods breaks defined?(super) on Ruby 3.0.0

### ISSUE THREAD

**Issue by benedikt** [rails/rails#40980]
When using `defined?(super)` to check that a superclass method exists before calling `super`, `ActiveModel::AttributeMethods` seems to break the check so it wrongfully returns a truthy value, even though the superclass method doesn't exist. 

This only happens on Ruby 3.0.0 and works fine on previous Ruby versions. 

It is possibly related to this change: https://github.com/ruby/ruby/pull/3777 

### Steps to reproduce

```ruby 
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'activemodel', require: 'active_model'
end

module SomeModule
  def a_method
    defined?(super) ? super : :no_super_method
  end
end

class Model
  include ActiveModel::AttributeMethods
  include SomeModule
end

class Klass
  include SomeModule
end

puts "Klass: #{Klass.new.a_method}"
puts "Model: #{Model.new.a_method}"
```

### Expected behavior

```
Klass: no_super_method
Model: no_super_method
```

### Actual behavior

```
Klass: no_super_method
[...]/lib/active_model/attribute_methods.rb:466:in `method_missing': super: no superclass method `a_method' for #<Model:0x00007ff0ae2a8748> (NoMethodError)
Did you mean?  method
	from test.rb:11:in `a_method'
	from test.rb:26:in `<main>'
```

### System configuration
**Rails version**: 6.1.0, 6.0.3.4

**Ruby version**: 3.0.0p0

**Comment by rafaelfranca** [comment]
Not necessarily it is caused by `ActiveModel::AttributeMethods`. That seems to be a Ruby bug since I can reproduce with just simple modules:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'activemodel', require: 'active_model'
end

module SomeModule
  def a_method
    respond_to = respond_to?(:a_method)
    puts respond_to
    super_method = defined?(super) ? super : :no_super_method
    puts super_method
  end
end

module Foo
  def respond_to?(*)
    super
  end
end

class Model
  include Foo
  include SomeModule
end

class Klass
  include SomeModule
end

puts "Klass: "
Klass.new.a_method
puts "Model: "
Model.new.a_method
```

As you can see, just by having a module included before the one that call `defined?` that overrides `respond_to?` but just call `super`. The behavior changes.

Can you please report the bug to the Ruby issue tracker?

**Comment by benedikt** [comment]
Thanks for unraveling this, @rafaelfranca! Just posted a issue on the Ruby bug tracker: https://bugs.ruby-lang.org/issues/17509

**Comment by jrochkind** [comment]
I've been hit by this first, thanks for finding and filing first! 

Curious if anyone can figure out any workarounds. I hope ruby maintainers attend to it soon-ish.
