### ISSUE TITLE
`ActiveRecord::Base.find_by_sql` Disincentivizes Parameterization

### ISSUE THREAD

**Issue by JoshCheek** [rails/rails#40990]
It's undocumented and really painful to figure out how to pass the bind parameters to `find_by_sql`, I feel like a lot of people are going to give up trying to figure it out and just interpolate, leading to security vulnerabilities. For a different method (`select_all`, in [this](https://github.com/rails/rails/issues/27923) issue), this was deemed a regression, and perhaps it is here, as well.

### Steps to reproduce

```ruby
require 'active_record'
ActiveRecord::VERSION::STRING # => "6.0.3.4"
RUBY_VERSION                  # => "2.7.2"
RUBY_PLATFORM                 # => "x86_64-darwin18"

ActiveRecord::Base.establish_connection adapter: 'sqlite3', database: ':memory:'
ActiveRecord::Schema.define do
  self.verbose = false
  create_table(:users) { }
end
User = Class.new ActiveRecord::Base

# Lets say my user can give me this number
num = 1

# And I want to use it in this impressively sophisticated query:
User.find_by_sql "select #{num} as id" # => [#<User id: 1>]

# But, of course, there is a SQL injection vulnerability, so I should parameterise `num`
# ...uhm, nothing I can think of seems to work (I swear one of these used to work):
User.find_by_sql "select ? as id", num     rescue $! # => #<NoMethodError: undefined method `first' for 1:Integer>
User.find_by_sql "select ? as id", [num]   rescue $! # => #<NoMethodError: undefined method `value_for_database' for 1:Integer>
User.find_by_sql "select ? as id", [[num]] rescue $! # => #<NoMethodError: undefined method `sql_type' for 1:Integer>
User.find_by_sql "select :n as id", n: num rescue $! # => #<ArgumentError: unknown keyword: :n>
User.find_by_sql "select $1 as id", num    rescue $! # => #<NoMethodError: undefined method `first' for 1:Integer>
User.find_by_sql "select $1 as id", [num]  rescue $! # => #<NoMethodError: undefined method `value_for_database' for 1:Integer>

# Apparently I have to do this, according to https://github.com/rails/rails/issues/27923#issuecomment-277950243
User.find_by_sql(
  "select ? as id",
  [ ActiveRecord::Relation::QueryAttribute.new(
      "this apparently doesn't matter?",
      num,
      ActiveRecord::Type::Integer.new
    )
  ],
) # => [#<User id: 1>]

# But that took a lot of effort to figure out, doesn't seem to be documented, and is really painful to use
# I think it may not be intentional, TBH, so Imma open this issue here
```

### Expected behavior

I don't know 🤷‍♂️  probably one of these two should have worked:

```ruby
User.find_by_sql "select ? as id", num 
User.find_by_sql "select ? as id", [num]
```

### Actual behavior

Those ones explode, as can be seen in my code sample. The one that does work requires wrapping my integer in these undocumented heavily namespaced internal implementation details in order to pass my parameters to the query.

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.7.2

**Comment by eugeneius** [comment]
The API documentation does in fact cover how to achieve this:

https://github.com/rails/rails/blob/b791f7dedc912419834699fc3927f6d3278b2536/activerecord/lib/active_record/querying.rb#L42-L45

**Comment by JoshCheek** [comment]
Something is still off here. The signature says to call it like this:

```ruby
find_by_sql(sql, binds)
```

But the example calls it like this:

```ruby
find_by_sql([sql, *binds])
```

The docs don't mention the `binds` except in the signature:

![image](https://user-images.githubusercontent.com/77495/103454326-6ead4d00-4ca8-11eb-864a-464576e78ffa.png)

And they specify that `sql` should be a `String`, not an `Array`:

![Screen Shot 2021-01-02 at 3 14 53 AM](https://user-images.githubusercontent.com/77495/103454386-fe52fb80-4ca8-11eb-85fa-cdb773450fa8.png)

I acknowledge that there is an example, that I didn't realize was relevant to my use case, but that example contradicts the signature, the documentation, and my intuition.

**Comment by eugeneius** [comment]
Passing an array of values as `binds` works on 6.1 (via https://github.com/rails/rails/pull/39106):

```ruby
User.find_by_sql "select ? as id", [num]
```

This slightly more awkward syntax also works on older versions:

```ruby
User.find_by_sql "select ? as id", [[nil, num]]
```

**Comment by JoshCheek** [comment]
Oh wow. Yes, you are right, thank you.
