### ISSUE TITLE
Long Rails 6 migration printout

### ISSUE THREAD

**Issue by janospapp** [rails/rails#40999]
After I migrated my application from Rails 5.2.3 to 6.1.0 the add_reference migration step logging has changed. Earlier it logged only
```
-- add_reference(:categories, :user, {:foreign_key=>true})
```
and after the upgrade it logs
```
-- update_table_definition(:categories, ...)
-- add_column("categories", "user_id", :bigint, {})
-- add_index("categories", ["user_id"], {})
-- add_foreign_key("categories", "users", {:column=>"user_id"})
```

The problem is that the second parameter of update_table_definition (the ... part) is an instance of my migration class and prints 4 screens of text.

Is there a way to get back the simple printout of Rails 5 (or something more user friendly)? I know I can turn off migration logs with VERBOSE=false, but then I lose all the migration logs.

The add_reference method and missing_parameter, say_with_time methods (that prints the logs) seemingly didn't change between the two Rails versions.

### Steps to reproduce
Create a migration with add_reference method, i.e:
```
class AddUserToCategory < ActiveRecord::Migration[5.1]
  def change                   
    add_reference :categories, :user, foreign_key: true
  end
end
```
Then run it with `rails db:migrate`.

### Expected behavior
A readable output when I run `rails db:migrate`.

### Actual behavior
The AddUserToCategory object is printed (more than 60k characters)

### System configuration
Previous config:
Rails: 5.2.3
Ruby: 2.6.6

Current config:
Rails: 6.1.0
Ruby: 2.7.2

**Comment by doits** [comment]
I can confirm this with Rails 6.1, it looks like this (only the first few lines, there are approx 1500 lines of these):

```
== 20200519143100 AddSingleAppointmentAtToEventApplications: migrating ========
-- update_table_definition(:event_applications, #<AddSingleAppointmentAtToEventApplications:0x00007fc81fda7548 @name="AddSingleAppointmentAtToEventApplications", @version=20200519143100, @connecti
on=#<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00007fc85c55d9b8 @transaction_manager=#<ActiveRecord::ConnectionAdapters::TransactionManager:0x00007fc85c55d940 @stack=[#<ActiveRecord::C
onnectionAdapters::RealTransaction:0x00007fc81fda7188 @connection=#<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00007fc85c55d9b8 ...>, @state=#<ActiveRecord::ConnectionAdapters::Transact
ionState:0x00007fc81fda7138 @state=nil, @children=nil>, @records=nil, @isolation_level=nil, @materialized=false, @joinable=true, @run_commit_callbacks=true, @lazy_enrollment_records=nil>], @connec
tion=#<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x00007fc85c55d9b8 ...>, @has_unmaterialized_transactions=true, @materializing_transactions=false, @lazy_transactions_enabled=true>, @que
ry_cache={}, @query_cache_enabled=false, @connection=#<PG::Connection:0x00007fc85c55e688 @prepare_map={"a1"=>"SELECT \"forms\".* FROM \"forms\" WHERE \"forms\".\"name\" = $1 LIMIT $2", "a2"=>"SELE
CT \"users\".* FROM \"users\" ORDER BY \"users\".\"id\" ASC LIMIT $1", "a3"=>"SELECT \"forms\".* FROM \"forms\" WHERE \"forms\".\"name\" = $1 LIMIT $2", "a4"=>"SELECT \"forms\".* FROM \"forms\" OR
DER BY \"forms\".\"id\" ASC LIMIT $1", "a5"=>"SELECT \"form_inputs\".* FROM \"form_inputs\" WHERE \"form_inputs\".\"kind\" = $1 ORDER BY \"form_inputs\".\"id\" ASC LIMIT $2", "a6"=>"SELECT \"event
s\".* FROM \"events\" WHERE \"events\".\"state\" = $1 ORDER BY \"events\".\"id\" ASC LIMIT $2", "a7"=>"SELECT \"events\".* FROM \"events\" WHERE \"events\".\"state\" = $1 ORDER BY \"events\".\"id
[...]
```

**Comment by mkasztelnik** [comment]
This is a minimal example that replicates the issue. The problem is in `add_reference` in migrations `v6.0` and older. Unfortunately, I'm not sure how to make an assertion for the stdout produced by `ActiveRecord::Migration#say` method - this can be for sure improved in this snippet.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :rooms, force: true do |t|
    t.string :name
  end

  create_table :messages, force: true do |t|
    t.string :text
  end
end

class AddReferenceBetweenMessageAndRoom < ActiveRecord::Migration[6.0]
  def change
    add_reference :messages, :room
  end
end

class BugTest < Minitest::Test
  def test_add_reference
    AddReferenceBetweenMessageAndRoom.migrate(:up)
  end
end
```

**Comment by mkasztelnik** [comment]
The long log for `update_table_definition(:model_name, ...)` is printed because `method_missing` is invoked in the `ActiveRecord::Migration` by https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration/compatibility.rb#L62. `method_missing` by default prints the method name and list of arguments and the second argument for the `update_table_definition` is a migration class instance. 

Changing this method https://github.com/rails/rails/blob/master/activerecord/lib/active_record/migration/compatibility.rb#L61-L63 into:

```ruby
def add_reference(table_name, ref_name, **options)
  ReferenceDefinition.new(ref_name, **options)
    .add_to(connection.update_table_definition(proper_table_name(table_name, table_name_options), self))
end
```
solves the problem with the long log with migration class instance details. If this is a way to go I can prepare a PR.

**Comment by rafaelfranca** [comment]
@mkasztelnik that makes sense. Can you open a PR?
