### ISSUE TITLE
DestroyAsync bug with STI

### ISSUE THREAD

**Issue by uxxman** [rails/rails#41008]
### Sample test

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails"
  gem "sqlite3"
end

require "active_job"
require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.destroy_association_async_job = ActiveRecord::DestroyAssociationAsyncJob
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :companies, force: true do |t|
  end

  create_table :users, force: true do |t|
    t.string :type

    t.references :company
  end
end

class User < ActiveRecord::Base
  belongs_to :company
end

class Employer < User
end

class Employee < User
end

class Company < ActiveRecord::Base
  has_many :users, dependent: :destroy_async
end

class BugTest < ActiveJob::TestCase
  def test_destroy_async
    company = Company.create!

    Employer.create! company: company
    Employee.create! company: company

    company.destroy!

    perform_enqueued_jobs

    assert_equal User.count, 0
  end
end
```

### Expected behavior
All users should be deleted by the background job. **User.count == 0**

### Actual behavior
Only first user is destroyed.

### Notes
Issue seems related to using class.name instead of base_class name

https://github.com/rails/rails/blob/22f3dfe3cb0b590dd3e80dcb68116dbf2339d789/activerecord/lib/active_record/associations/has_one_association.rb#L42
https://github.com/rails/rails/blob/22f3dfe3cb0b590dd3e80dcb68116dbf2339d789/activerecord/lib/active_record/associations/has_many_association.rb#L45
https://github.com/rails/rails/blob/22f3dfe3cb0b590dd3e80dcb68116dbf2339d789/activerecord/lib/active_record/associations/belongs_to_association.rb#L21
 
### System configuration
**Rails version**: master

**Ruby version**: 3.0.0

**Comment by krtschmr** [comment]
nice catch

**Comment by intrip** [comment]
I'd like to take a look and work on this, unless somebody else want to do it.

**Comment by uxxman** [comment]
@intrip i think the solution is just to use base_class name as I suggested. Was waiting for feedback from any core team member to create and push a PR.

**Comment by kamipo** [comment]
Just use `polymorphic_name` for the name.

https://github.com/rails/rails/blob/5cfd58bbfb8425ab1931c618d98b649bab059ce6/activerecord/lib/active_record/inheritance.rb#L189-L192

**Comment by kamipo** [comment]
Ah, no, `sti_name` is the name for STI class, but it doesn't call `base_class`, hmm.

https://github.com/rails/rails/blob/5cfd58bbfb8425ab1931c618d98b649bab059ce6/activerecord/lib/active_record/inheritance.rb#L167-L170

Perhaps seems directly calling `base_class.name` is a right direction.

**Comment by uxxman** [comment]
> Just use `polymorphic_name` for the name.

The issue with using `polymorphic_name` is that the Job tries to load the constant from this name, and if someone has namespaced models but configured to not store full sti class, this will fail.
https://github.com/rails/rails/blob/11e0c1092f2303f7dd35700565a114e649cf9145/activerecord/lib/active_record/destroy_association_async_job.rb#L18


> Perhaps seems directly calling `base_class.name` is a right direction.

Yes, using base_class.name would handle all cases properly.

**Comment by kamipo** [comment]
Probably `reflection.klass` is the base class for the STI classes.

**Comment by uxxman** [comment]
> Probably `reflection.klass` is the base class for the STI classes.

If that's true, then we only need to handle has_many case

i.e change this 
https://github.com/rails/rails/blob/22f3dfe3cb0b590dd3e80dcb68116dbf2339d789/activerecord/lib/active_record/associations/has_many_association.rb#L35

to 

```ruby
association_class = target.first.class.base_class

**Comment by kamipo** [comment]
My suggestion is here:

```diff
diff --git a/activerecord/lib/active_record/associations/has_many_association.rb b/activerecord/lib/active_record/associations/has_many_association.rb
index e2bbf42a62..2553fd0ef1 100644
--- a/activerecord/lib/active_record/associations/has_many_association.rb
+++ b/activerecord/lib/active_record/associations/has_many_association.rb
@@ -42,7 +42,7 @@ def handle_dependency
             enqueue_destroy_association(
               owner_model_name: owner.class.to_s,
               owner_id: owner.id,
-              association_class: association_class.to_s,
+              association_class: reflection.klass.to_s,
               association_ids: ids,
               association_primary_key_column: primary_key_column,
               ensuring_owner_was_method: options.fetch(:ensuring_owner_was, nil)
```

**Comment by uxxman** [comment]
> My suggestion is here:
> 
> ```diff
> diff --git a/activerecord/lib/active_record/associations/has_many_association.rb b/activerecord/lib/active_record/associations/has_many_association.rb
> index e2bbf42a62..2553fd0ef1 100644
> --- a/activerecord/lib/active_record/associations/has_many_association.rb
> +++ b/activerecord/lib/active_record/associations/has_many_association.rb
> @@ -42,7 +42,7 @@ def handle_dependency
>              enqueue_destroy_association(
>                owner_model_name: owner.class.to_s,
>                owner_id: owner.id,
> -              association_class: association_class.to_s,
> +              association_class: reflection.klass.to_s,
>                association_ids: ids,
>                association_primary_key_column: primary_key_column,
>                ensuring_owner_was_method: options.fetch(:ensuring_owner_was, nil)
> ```

PR submitted 👍🏻
