### ISSUE TITLE
A has_many relationship not being loaded in order

### ISSUE THREAD

**Issue by nedcampion** [rails/rails#41007]
I ran into a situation when debugging an issue of mine where a has_many relationship was lazily loaded but the `.first` record returned was not the first record created. I am not sure under what conditions postgres will return the records for the relationships out of order, but it seems there is no guarantee that it should (without specifying an `ORDER BY`). Any help understanding what I'm missing or identifying the issue would be greatly appreciated. I'm happy to work on a PR if this is indeed an underlying issue in activerecord.

### Steps to reproduce
I'm having a very hard time reproducing this issue as in all my testing the returned order seems to match the desired order (`id ASC`) even though that seems not to be guaranteed.

### Expected behavior
I would expect has_many associations to be loaded in the same order that `ActiveRecord::FinderMethods#ordered_relation` loads them.

### Actual behavior
The included test passes because the db is coincidentally returning the comments in the order that `ActiveRecord::FinderMethods#find_nth_with_limit` seems to expect them (`comments.id ASC`). What the test shows though is that when the `Post#comments` association is not loaded the `post.comments.first` call issues a query for just the one comment as I would expect. But, after the association is loaded the call to `post.comments.first` looks up the comment record on the association which was loaded without any order specified in the query. These points can be verified via the output logs from the test:
```
Post Load (0.1ms)  SELECT "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = ? ORDER BY "comments"."id" ASC LIMIT ?  [["post_id", 2], ["LIMIT", 1]]
Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = ?  [["post_id", 2]]
```

Though the db may consistently return these comments in the order in which they are created I don't see that being guaranteed. To quote some of the [postgresql documentation](https://www.postgresql.org/docs/13/queries-order.html):

> After a query has produced an output table (after the select list has been processed) it can optionally be sorted. If sorting is not chosen, the rows will be returned in an unspecified order.

### System configuration
**Rails version**: `6.1.0`

**Ruby version**: `ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]`

**Postgres version**: `11.9`

### Test
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!

    first_comment = Comment.create!
    second_comment = Comment.create!
    post = Post.create! comments: [first_comment, second_comment]
    post.reload

    assert_equal first_comment.id, post.comments.first.id
    post.comments.load
    assert_equal first_comment.id, post.comments.first.id
  end
end
```

**Comment by lostapathy** [comment]
I'm confused by this issue.  You note from the Postgres docs that the order returned is not deterministic unless you specify a sort order, which you are not supplying in your rails code.  

You'll need to do a query like `post.comments.order(:created_at).first` if you want to always get the oldest result first.

**Comment by nedcampion** [comment]
Yes, specifying the order is explicit and resolves any confusion/issues. It does, however, force a query and if the records are loaded on `post.comments` it'd be ideal to avoid that query.

My point is just that `post.comments.first` can return different values depending on if the relationship is loaded or not.

**Comment by lostapathy** [comment]
> My point is just that post.comments.first can return different values depending on if the relationship is loaded or not.

Right, and I'm confirming that's expected behavior for how your models are configured.

Another option to get what you want would be put a scope on the association like:
`has_many :comments, -> { order(created_at: :desc) }`

**Comment by nedcampion** [comment]
Ok, thank you for the clarification @lostapathy. I'll close this one out.

I guess there would performance implications to loading has_many associations in order be default, but it just felt unsettling to have that same call on the relationship return different results.
