### ISSUE TITLE
SQLite3::SQLException: no such column: articles.status

### ISSUE THREAD

**Issue by juniperlRails** [rails/rails#41018]
I'm following the Ruby on Rails guide 6.1 and after solving a problem with an alredy fixed error 'Unknown validator: 'InValidator'. My Blog is displaying a new error message 'SQLite3::SQLException: no such column: articles.status' in fact, the tutorial don't create a column named 'status' and we using it on  Concern 'Visible'

### Steps to reproduce
```ruby
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end
```
After include the class_methods above on 'models/concerns/visible.rb' go to rails console and type
```ruby
irb(main):001:0> Article.public_count
```

### Expected behavior
The public_count method should be count all articles where status are 'public'

### Actual behavior
Aplication is raising the errror: 'SQLite3::SQLException: no such column: articles.status'

### System configuration
**Rails version**: 6.1.0

**Ruby version**:  ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-linux]

**Comment by intrip** [comment]
@juniperlRails the guide mentions the following:

> "Within the article model, after running a migration to add a status column, you might add:"

The above assumes you've created and ran a migration to add the `status` column to the `articles` table.
You can easily generate that with something on the line of (didn't check):

```bash
$ rails generate migration AddStatusToArticles status:string
$rails db:migrate
```

**Comment by juniperlRails** [comment]
Hey, thank you @intrip!  This might have unnoticed...Thanks to be attention and quickly on help me!
