### ISSUE TITLE
remove nokogiri dependency

### ISSUE THREAD

**Issue by LeFnord** [rails/rails#41016]
Are any plans to remove nokogiri as dependency?

After upgrading to nokogiri 1.11.0, again failures are popping up, this happenes allways to this gem.
I t seems it is one of the most failure introducing gem in the rails eco-system.

On the other hand, never seen it in direct usage on project level – have seen many projects in about 15y of rails dev, so it seems it is only a rails internal dependency.

Can somebody give a starting point, so somebody – beste me ;) – can start and make a PR.

Thanks

**Comment by LeFnord** [comment]
mmh … unter "open mind" versteh da schon was anderes, so'ne barsche absage – nich mal nen Ansatz – ist de facto schon arg unhöflich ([help](https://translate.google.de/?sl=de&tl=en&text=mmh%20…%20unter%20%22open%20mind%22%20versteh%20da%20schon%20was%20anderes%2C%20so%27ne%20barsche%20absage%20–%20nich%20mal%20nen%20Ansatz%20–%20ist%20de%20facto%20schon%20arg%20unhöflich&op=translate))

**Comment by eileencodes** [comment]
It's not rude to answer your question directly. I'm sorry if you felt dismissed but the framework requires nokogiri, removing it is not trivial nor do we have plans for it. Additionally _every_ application I have ever worked on uses nokogiri so it's not a transitive dependency of Rails. If you have broken code in your application please open an issue on the nokogiri repo to report a bug.

**Comment by brosintoski** [comment]
So nokogiri since 1.18 now requires glibc >= 2.29 which is an issue for those of us still on older platforms/OSs that do Not support this
