### ISSUE TITLE
ActiveModel Validations seems to have undocumented changes between 6.0 and 6.1

### ISSUE THREAD

**Issue by jlahtinen** [rails/rails#41039]
### Testfile

    class Foo
      include ActiveModel::Validations
      attr_accessor :bar
      validates :bar, presence: true
    end

### 6.0

    2.7.2 :001 > require "active_model"
     => true 
    2.7.2 :002 > ActiveModel.version
     => #<Gem::Version "6.0.3.4"> 
    2.7.2 :003 > load "foo.rb"
     => true 
    2.7.2 :004 > f = Foo.new; f.valid?; f.errors.first
     => [:bar, "can't be blank"] 

### 6.1

    2.7.2 :001 > require "active_model"
     => true 
    2.7.2 :002 > ActiveModel.version
     => #<Gem::Version "6.1.0"> 
    2.7.2 :003 > load "foo.rb"
     => true 
    2.7.2 :004 > f = Foo.new; f.valid?; f.errors.first
     => #<ActiveModel::Error attribute=bar, type=blank, options={}>

It looks like `#first` is not documented at all for `ActiveModel::Errors`... This change still needs some attention in our code base.
To get first message could have been written `model.errors.first.second` and can be fixed with `model.errors.messages.first.second.first` so impact is quite minimal.

**Comment by louim** [comment]
Hello @jlahtinen, the changes to ActiveModel are documented here: https://guides.rubyonrails.org/6_1_release_notes.html#active-model-notable-changes.
That page is referenced in the upgrade guide here: https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-0-to-rails-6-1

**Comment by jlahtinen** [comment]
@louim I missed link on upgrading page, sorry. All OK
