### ISSUE TITLE
Suggestion: mention FactoryBot into Rails Guides to help beginners write tests

### ISSUE THREAD

**Issue by giovanni-cloudwalk** [rails/rails#41031]
## Context

Although I use Rails for many years, I would like to address an issue that affects mostly beginners, in the spirit of [May of WTFs](https://weblog.rubyonrails.org/2020/5/7/A-May-of-WTFs/). I faced it after joining a project in a new company, where most developers don't have many years of experience under their belts.

## Problem

You see, in the Rails guides [there is a well written section about testing](https://guides.rubyonrails.org/testing.html), and there is a mention of fixtures. However, as far as I can tell, [experienced Rails developers use factories far more than fixtures](https://semaphoreci.com/blog/2014/01/14/rails-testing-antipatterns-fixtures-and-factories.html). There is a good reason for that: fixtures are always persisted to the database, but often what you need in tests are just a set of attributes. At first you can "wing it" with fixtures, but in the moment you start adding uniqueness validations/constraints to your model/table, your tests start failing (as you are creating a duplicate), and the whole setup doesn't work anymore.

As an experienced Rails developer, I'm well aware that most of the time factories are the right solution. However, beginner and intermediate Rails developers reach out for the official guides, which just mention fixtures but not factories.

## Proposed solution

The minimum thing we could do to fix the problem (once aknowledged) is add a section to Rails guides addressing Factories with the gem most people use (arguably), which is FactoryBot. Optionally we could also ship it as a default gem in a new Rails setup (in the next release).

What do you think?

**Comment by rafaelfranca** [comment]
Thank you for the suggestion but fixtures is the solution that we include in Rails and it is the one that we think most Rails developers should be using. It is fine if they developers chose to use other tools like RSpec for example, but the Rails guide focus is for the default Rails stack that the Rails Core team define, not for the  collection of libraries that the community decides are they want to use.

**Comment by giovanni-cloudwalk** [comment]
> Thank you for the suggestion but fixtures is the solution that we include in Rails and it is the one that we think most Rails developers should be using. It is fine if they developers chose to use other tools like RSpec for example, but the Rails guide focus is for the default Rails stack that the Rails Core team define, not for the collection of libraries that the community decides they want to use.

I get your point, but we are talking about different things. `Rspec` and `Minitest` are different **libraries** that implement the same **concept** (automated tests). Fixtures and factories are different **concepts**, and the documentation is leading the inexperienced developers in the wrong way. Regardless of the library (it doesn't have to be `FactoryBot`, it could something else).

**Comment by rafaelfranca** [comment]
I think you don't get the point. We don't think you need factories when you already have fixtures.

**Comment by giovanni-cloudwalk** [comment]
> We don't think you need factories when you already have fixtures.

For future readers, could we at least have a link that shows where that is discussed and how that decision has been made?

**Comment by rafaelfranca** [comment]
There is no link. Discussions about what is included in the default Rails stack usually don't happen in the open so we can link. Sometimes David just decide and we follow suite. But I believe about this specific case, the decision was made when fixtures was implemented in the framework, maybe pre Rails 1.0.

**Comment by giovanni-cloudwalk** [comment]
Alright, thank you for the information. :+1:
