### ISSUE TITLE
date_field Safari issue

### ISSUE THREAD

**Issue by lrjbrual** [rails/rails#41035]
### Steps to reproduce
Using tag date_field. it is working in Firefox, chrome and other except Safari. I'm using html5 it should work. but seems safari is not
<%= invoice.date_field :departure_date__c, max: Date.today, class: "form-control", type: "date" %>
Validate the inspect in Safari but no issue found.

### Expected behavior
In chrome this is what I expected, which is good but in Safari is not. 
![image](https://user-images.githubusercontent.com/9385561/103805511-fa7dfb00-5053-11eb-970e-98d7701b0c17.png)

### Actual behavior
Actual behavior in Safari
![image](https://user-images.githubusercontent.com/9385561/103805755-5052a300-5054-11eb-9af0-55215cf85a12.png)
It doesn't show the calendar. I know there is better solution using date_select or using date picker with js. however I'm thinking if someone encounter this using Safari. 

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.7.1

**Comment by rafaelfranca** [comment]
Thank you for the issue. Rails just generate an HTML tag with the right type. It seems Safari doesn't know how to do with that type, but it is not an issue of the Rails framework.

**Comment by jonathanhefner** [comment]
For anyone interested in tracking this, here is the Safari bug: https://bugs.webkit.org/show_bug.cgi?id=200416

It is currently in Safari's Technology Preview, and will hopefully be in the next major Safari release! :tada: 

See also: https://caniuse.com/?search=input-datetime
