### ISSUE TITLE
Rails 6.1 produces UrlGenerationError with some route helpers of engines that worked fine with Rails 6.0

### ISSUE THREAD

**Issue by vtamara** [rails/rails#41038]
### Steps to reproduce
* Download branch rails61pr1 of the application available at https://github.com/pasosdeJesus/heb412/tree/rails61pr1
* Follow setup instructions available at: https://github.com/pasosdeJesus/heb412/blob/rails61pr1/.travis.yml
* Run the test `test/controllers/rutas_test.rb` with 
```
CONFIG_HOSTS=www.example.com bin/rails test test/controllers/rutas_test.rb` 
```

### Expected behavior

```
$ CONFIG_HOSTS=www.example.com bin/rails test test/controllers/rutas_test.rb 
Run options: --seed 53016

# Running:

/heb412/personas
.

Finished in 0.816051s, 1.2254 runs/s, 3.6762 assertions/s.
1 runs, 3 assertions, 0 failures, 0 errors, 0 skips
```

Passing test as it happens by using Rails 6.0 instead of Rails 6.1.  To confirm:

* Follow the same procedure described above but using the branch rails60pr1 of the same repository: https://github.com/pasosdeJesus/heb412/tree/rails60pr1
* Or check the result of the continuos integration at https://travis-ci.org/github/pasosdeJesus/heb412/builds/753339769 lines 1317 to 1327 

### Actual behavior

* It will produce the error 
```
Error:                                                            
RutasTest#test_personas_path_usable:       
ActionController::UrlGenerationError: No route matches {:action=>"index", :controller=>"sip/personas"}
    app/controllers/sip/personas_controller.rb:15:in `index'
    test/controllers/rutas_test.rb:17:in `block in <class:RutasTest>'
```
* This can be confirmed by checking the result of the continous integration https://travis-ci.org/github/pasosdeJesus/heb412/builds/753339688  lines 1419 to 1423 
* The exception is generated by the line 15 in `app/controllers/sip/personas_controller.rb` that is:
```
puts personas_path
```
* However this exception is not generated if this statement is in another controller neither in the test. Even the test includes the assertion: `assert_equal '/heb412/personas', personas_path` that is passing.
* The application includes 3 open source engines (`sip`, `mr519_gen` and `heb412_gen` see in the `Gemfile`) all of them hosted in github. The exception is not generated in the test application of the engine `sip` (i.e the one available at `test/dummy`) neither in the test application of the engine `mr519_gen` (which uses the engine `sip`).  But it can be reproduced in the test application of the engine `heb412_gen.` 
* The route `personas_path` is defined in the motor `sip`.  A workaround is to change `personas_path` with `sip.personas_path`.  However that was not required with rails 6.0 (and anyway there are situations where this change cannot be made easily --like with `will_paginate`).
* The controller `app/controllers/sip/personas_controller.rb` already has `include Sip::Engine.routes.url_helpers`

### System configuration
**Rails version**: 6.1
**Ruby version**: 2.7.1

**Comment by rafaelfranca** [comment]
Thank you for the issue. Since you know which version of Rails this work, and which version of Rails doesn't, can you use git bisect to find which commit changed the behavior you seeing?

**Comment by samuelgiles** [comment]
We're seeing the same behaviour under 6.1, its definitely something to do with engines (specifically we're using Administrate), we've yet to get to the bottom of it. The URL helpers available within views sometimes appear not to include the applications own URL helpers but only those of an engine being used.

We were able to work around this for now by doing `include MyApplication.routes.url_helpers` at the top of our `ApplicationHelper`.

**Comment by FlickStuart** [comment]
Experiencing a similar issue to the original poster. Bisecting shows the tests passing at commit `4500ebba21836c4bf264a043b68cf580cfa55611` and failing at the subsequent commit `37e778b6b44ae087ce052ff380b1e3aaee31473d` - see: [Cache routes.url_helpers built modules](https://github.com/rails/rails/commit/37e778b6b44ae087ce052ff380b1e3aaee31473d)

Have tested this with the original poster's example repo and found the same pass/fail result before/at that commit.

**Comment by FlickStuart** [comment]
Hi @rafaelfranca is there anything else I can usefully add apart from the bisected commit hash?

**Comment by vtamara** [comment]
> Experiencing a similar issue to the original poster. Bisecting shows the tests passing at commit `4500ebba21836c4bf264a043b68cf580cfa55611` and failing at the subsequent commit `37e778b6b44ae087ce052ff380b1e3aaee31473d` - see: [Cache routes.url_helpers built modules](https://github.com/rails/rails/commit/37e778b6b44ae087ce052ff380b1e3aaee31473d)
> 
> Have tested this with the original poster's example repo and found the same pass/fail result before/at that commit.

I confirm the result of this bisection of @FlickStuart 

For me, using "include MyApplication.routes.url_helpers" as @samuelgiles suggest didn't work.

**Comment by vtamara** [comment]
I could create a much smaller and simple case that shows the problem.

1. Create a mountable engine `e1` like this:  `rails plugin new e1 --mountable --skip-collision-check --skip-keeps --skip-action-mailer --skip-action-mailbox --skip-active-record --skip-active-job --skip-active-storage --skip-puma --skip-action-cable --skip-sprockets --skip-spring --skip-listen --skip-javascript --skip-turbolinks --skip-jbuilder --skip-test --skyp-system-test --skyp-bootsnap `
2. Create a second mountable engine `e2` like this: `rails plugin new e3 --mountable --skip-collision-check --skip-keeps --skip-action-mailer --skip-action-mailbox --skip-active-record --skip-active-job --skip-active-storage --skip-puma --skip-action-cable --skip-sprockets --skip-spring --skip-listen --skip-javascript --skip-turbolinks --skip-jbuilder --skip-test --skyp-system-test --skyp-bootsnap`
3. Create an application `a3` like this: `rails new a3 --skip-collision-check --skip-keeps --skip-action-mailer --skip-action-mailbox --skip-active-record --skip-active-job --skip-active-storage --skip-puma --skip-action-cable --skip-sprockets --skip-spring --skip-listen --skip-javascript --skip-turbolinks --skip-jbuilder --skip-test --skyp-system-test --skyp-bootsnap  --skip-bundle`
4.

**Comment by vtamara** [comment]
IMHO it would be good to introduce a configuration variable `config.action_dispatch.cache_url_helpers_built_modules` that would activate the caching of <https://github.com/rails/rails/commit/37e778b6b44ae087ce052ff380b1e3aaee31473d> only when it would be true.

**Comment by vtamara** [comment]
I guess the same problem happens in the `main` branch.  Later I could create another PR for that branch.

**Comment by FlickStuart** [comment]
I can confirm the issue we saw is fixed by the PR https://github.com/rails/rails/pull/41463 - cheers @jhawthorn 👍🏻

**Comment by vtamara** [comment]
Confirming that the issue is solved by using the branch main, that includes the solution of @jhawthorn.  
Thank you very much.

**Comment by rubydesign** [comment]
I'm on 7.0.4 and i seem to have this issue (or a similar one?) 
The main app routes are not found when the engine controller renders the application layout.
Tried deriving the engine Controller from ::ApplicationController, or just setting layout 'application'
Can't put main_app in the apps layout (obviously).

Just saying, because the include tip @samuelgiles gave (include MyApplication.routes.url_helpers at the top of ApplicationHelper.) does the trick.
Not sure if anyone is still listening or interested. I obviouly fix my problem (thanks sam), but would be willing help investigate what is going on, ie if this is the same or not.
