### ISSUE TITLE
Combination of `select`, `includes`, and `joins` leads to StatementInvalid

### ISSUE THREAD

**Issue by mobilutz** [rails/rails#41059]
After upgrade from Rails 5.2 to 6.0.3.4 our application threw in error in code that had not changed for years.

The problem is a statement like this:
```
Post.select(Post::SELECTS).order(Post::ORDER).includes(:user).references(:user).joins(:post_tags)
```
(details in the linked repos)

A combination of `select`, `includes` and `joins` in my opinion is leading to the error I am seeing which is this:
```
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column "sort_index" does not exist)
LINE 1: SELECT DISTINCT sort_index AS alias_0, "posts"."id" FROM "po...
                        ^
```

### Steps to reproduce

There are two repos, one rails-5 (`rails-success`) the other rails-6 (`rails-fail`).
The rails-5 code works, but rails-6 code does not.

* https://github.com/mobilutz/rails-success
* https://github.com/mobilutz/rails-fail

### Expected behavior

No error should be raised.

### Actual behavior

`ActiveRecord::StatementInvalid` error was raised.

### System configuration
**Rails version**: Rails 6.0.3.4

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

**Comment by louim** [comment]
Hi @mobilutz, both repos show up as 404 for me. Maybe they are still private?

**Comment by mobilutz** [comment]
🤦🏻  Sorry about that. I didn’t check the settings for the repos in details ...

**Comment by kamipo** [comment]
Caused by #37434.

This is potentially a problem that parent records deduplication for eager loading has_many association.

So if `joins(:post_tags)` changed to `eager_load(:post_tags)`, the statement error will be raised even in Rails 5.2.

**Comment by mobilutz** [comment]
> So if `joins(:post_tags)` changed to `eager_load(:post_tags)`, the statement error will be raised even in Rails 5.2.

That is correct, I just tested it our in the rails 5.2 app, and this is what I got:
```
irb(main):002:0> Post.select(Post::SELECTS).order(Post::ORDER).includes(:user).references(:user).eager_load(:post_tags)
  SQL (1.2ms)  SELECT  DISTINCT sort_index AS alias_0, "posts"."id" FROM "posts" LEFT OUTER JOIN "posts_tags" ON "posts_tags"."post_id" = "posts"."id" LEFT OUTER JOIN "users" ON "users"."id" = "posts"."user_id" ORDER BY sort_index LIMIT $1  [["LIMIT", 11]]
Traceback (most recent call last):
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column "sort_index" does not exist)
LINE 1: SELECT  DISTINCT sort_index AS alias_0, "posts"."id" FROM "p...
                         ^
: SELECT  DISTINCT sort_index AS alias_0, "posts"."id" FROM "posts" LEFT OUTER JOIN "posts_tags" ON "posts_tags"."post_id" = "posts"."id" LEFT OUTER JOIN "users" ON "users"."id" = "posts"."user_id" ORDER BY sort_index LIMIT $1
```

**Comment by kamipo** [comment]
If possible to remove `references(:user)`, it can avoid the eager loading problem.

**Comment by mobilutz** [comment]
> If possible to remove `references(:user)`, it can avoid the eager loading problem.

@kamipo Thanks for the hint. It works in the test case of the rails6 repo, but unfortunately it does not work in the production case we are having.
There I get the following error:
```
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "score_cards")
```

PS: I just see, that my production setup is a bit different than the demo repos - I will change them to reflect that case we are having.

**Comment by mobilutz** [comment]
@louim @kamipo Is there something more I need to provide?
I don't want to be pushy, I just want to see if this can be improved from rails side.

**Comment by intrip** [comment]
Adding a [reproduction script](https://gist.github.com/rafaelfranca/dd0a2d32397fd9c3a596a349e6601309) would be nice.
