### ISSUE TITLE
Upgrade or remove actiontext's dependence for @rails/activestorage@^6.0.0-alpha

### ISSUE THREAD

**Issue by francesco-loreti** [rails/rails#41058]
Hi
Into `actiontext/package.json` there is a dependency for `@rails/activestorage@^6.0.0-alpha`.
I know it's not a problem, but the yarn adds this package which has no reason to be added anymore having Rails 6.1 released.

Regards

**Comment by rafaelfranca** [comment]
Why it is not needed anymore? Action Text still depends on activestorage to upload attachments. That version requirements allows activestoraged 6.1.0

**Comment by francesco-loreti** [comment]
Yes, I know. But why an alpha version again? `@rails/activestorage` 6.0.0 and 6.1.0 stable are been released.
