### ISSUE TITLE
ActionView::Template::Error with Ruby 3.0.0

### ISSUE THREAD

**Issue by kaiquekandykoga** [rails/rails#41069]
I started to upgrade my app to Ruby on Rails 6.1.1, and I started to face this situation.

Ruby 3.0.0

Ruby on Rails 6.1.1

<br>

**Print Error**

<img width="876" alt="Screen Shot 2021-01-09 at 21 52 22" src="https://user-images.githubusercontent.com/6296479/104111765-ff95b100-52c4-11eb-9636-33aa701b47b7.png">

<br>

I decided to check the backtrace inside the rescue.

<img width="936" alt="Screen Shot 2021-01-09 at 22 00 50" src="https://user-images.githubusercontent.com/6296479/104111858-31f3de00-52c6-11eb-8517-8b1f2251c515.png">

I started to debug looking for each file in the exception.

https://github.com/rails/rails/blob/19759dfaf38406907dd360f29527152d15c5e6e5/actionview/lib/action_view/renderer/partial_renderer.rb#L285-L287

Values passed to template.render are `view => #<ActionView::Base:0x0000000000a050>`, `locals => {}` and `block => nil => !block => true`.

<br>

```
begin
  self.send without_profiling, *args, &orig
ensure
```

The piece of code above comes from rack-mini-profiler https://github.com/MiniProfiler/rack-mini-profiler/blob/master/lib/mini_profiler/profiling_methods.rb#L110-L112

Here args is containing `[#<ActionView::Base:0x0000000000a050>, {}, {:add_to_stack=>true}]`.

<br>

https://github.com/rails/rails/blob/19759dfaf38406907dd360f29527152d15c5e6e5/actionview/lib/action_view/template.rb#L150-L158

And finally the point where things start to get messy.

The values received in render are `view => #<ActionView::Base:0x0000000000a050>`, `locals => {}`, `buffer => {:add_to_stack=>true}`, `add_to_stack => true` and `block => #<Proc:0x00007ffe9f5e7798>`.

buffer contains a Hash, which is causing the exception.

According to this article https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/ arguments in Ruby 3.0.0 changed.

I created a branch with some changes, it is working. https://github.com/rails/rails/compare/master...kaiquekandykoga:add-to-stack-parameters.

Thank you a lot.

**Comment by intrip** [comment]
@kaiquekandykoga can't this be handled in the rack mini_profiler by also forwarding `**kwargs` ?

**Comment by kaiquekandykoga** [comment]
> @kaiquekandykoga can't this be handled in the rack mini_profiler by also forwarding `**kwargs` ?
> 
> I think you should try to open an issue in their repo.

Suggestion accepted.

Thank you very much.

**Comment by kaiquekandykoga** [comment]
Issue resolved in https://github.com/MiniProfiler/rack-mini-profiler/pull/481.
