### ISSUE TITLE
Public ActionText direct uploads don't correctly upload to DigitalOcean Spaces

### ISSUE THREAD

**Issue by lylo** [rails/rails#41070]
### Steps to reproduce
1. Create and configure a DigitalOcean Space, also set ACL to `public-read` via API
2. Configure ActiveStorage `storage.yml` accordingly 
3. Upload a file via ActionText and direct upload as normal 

### Expected behavior
When a direct upload via ActionText occurs, the file should be stored on the configured DigitalOcean Space with `public-read` permissions 

### Actual behavior
The file is stored on the configured DigitalOcean Space with `private-read` permissions. This is because DigitalOcean requires that the header `x-amz-acl: public-read` is set on all uploads that should be stored with `public-read` permissions and ActiveStorage/ActionText doesn't support this header.

I have managed to patch this temporarily by defining my own `DigitalOceanService` as follows:

```ruby
# frozen_string_literal: true

require 'active_storage/service/s3_service.rb'

module ActiveStorage
  class Service::DigitalOceanService < Service::S3Service

    def headers_for_direct_upload(key, content_type:, checksum:, filename: nil, disposition: nil, **)
      content_disposition = content_disposition_with(type: disposition, filename: filename) if filename

      headers = public? ? { "x-amz-acl" => "public-read" } : {}

      headers.merge({ "Content-Type" => content_type, "Content-MD5" => checksum, "Content-Disposition" => content_disposition })
    end
  end
end
```

I am raising this issue to have a conversation about whether I should look to add this class (perhaps with changes) to Rails itself and create a patch accordingly. 

A simpler solution would be to add this new header to the existing `S3Service` class as from what I can tell it will not have an adverse affect. That said, it might be a good time to introduce a specific DigitalOceanService class as suggested since it's quite popular and there are plenty of people who seem to be complaining about this particular issue on DigitalOcean forums.

### System configuration
**Rails version**:
6.1

**Ruby version**:
2.7.1

**Comment by current-username** [comment]
@lylo could you help me please ? I am stuck with the same problem.
Could you point me in the right direction ?

**Comment by inventionsbyhamid** [comment]
The above approach works for original uploads. If there are separate variants they are still getting stored as private. Can anyone point me in the direction where to add headers for variants?
