### ISSUE TITLE
I can't create a new Rails app  5.2.4.4. in ruby 3.0.0. metadata.rb:17:in `wrap': wrong number of arguments

### ISSUE THREAD

**Issue by aoreinoso** [rails/rails#41074]
### Steps to reproduce

I want to create a new Rails app

<pre>
$rails new prueba
	...
	...
	create  config/locales
    create  config/locales/en.yml
    create  config/master.key
/usr/local/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/messages/metadata.rb:17:in `wrap': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/message_encryptor.rb:175:in `_encrypt'
	from /usr/local/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/message_encryptor.rb:151:in `encrypt_and_sign'
</pre>
metadata.rb:
<pre>
	def wrap(message, expires_at: nil, expires_in: nil, purpose: nil)
</pre>
/usr/local/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/message_encryptor.rb:
<pre>
	def _encrypt(value, **metadata_options)
        ....
        ....
        encrypted_data = cipher.update(Messages::Metadata.wrap(@serializer.dump(value), metadata_options))
        ...
        ...
        
      end
</pre>
 /usr/local/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/message_encryptor.rb:
<pre>
	def encrypt_and_sign(value, expires_at: nil, expires_in: nil, purpose: nil)
		verifier.generate(_encrypt(value, expires_at: expires_at, expires_in: expires_in, purpose: purpose))
    end

</pre>

### System configuration
**Rails version**:
Rails 5.2.4.4
**Ruby version**:
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

<pre>
asssor@ssssss:~/tmp$ rails new r_prueba
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Inicializado repositorio Git vacío en /home/sss/tmp/r_prueba/.git/
      create  package.json
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/javascripts/application.js
      create  app/assets/javascripts/cable.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images/.keep
      create  app/assets/javascripts/channels
      create  app/assets/javascripts/channels/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/update
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_5_2.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
/usr/local/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/messages/metadata.rb:17:in `wrap': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /usr/local/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/message_encryptor.rb:175:in `_encrypt'
	from /usr/local/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/message_encryptor.rb:151:in `encrypt_and_sign'
	from /usr/local/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/encrypted_file.rb:75:in `encrypt'
	from /usr/local/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/encrypted_file.rb:49:in `write'
	from /usr/local/lib/ruby/gems/3.0.0/gems/activesupport-5.2.4.4/lib/active_support/encrypted_configuration.rb:29:in `write'
	from /usr/local/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/generators/rails/credentials/credentials_generator.rb:31:in `add_credentials_file_silently'
	from /usr/local/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/generators/rails/app/app_generator.rb:185:in `credentials'
	from /usr/local/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/generators/app_base.rb:159:in `build'
	from /usr/local/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/generators/rails/app/app_generator.rb:328:in `create_credentials'
	from /usr/local/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	from /usr/local/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
	from /usr/local/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
	from /usr/local/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
	from /usr/local/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
	from /usr/local/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/commands/application/application_command.rb:26:in `perform'
	from /usr/local/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/command/base.rb:69:in `perform'
	from /usr/local/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/command.rb:46:in `invoke'
	from /usr/local/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/lib/rails/cli.rb:18:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/lib/ruby/gems/3.0.0/gems/railties-5.2.4.4/exe/rails:10:in `<top (required)>'
	from /usr/local/bin/rails:23:in `load'
	from /usr/local/bin/rails:23:in `<main>'
</pre>

**Comment by composerinteralia** [comment]
Thank you for the issue. This is essentially a duplicated of https://github.com/rails/rails/issues/40938, although the specific error is a little different. At least for now Rails 5.2 is not expected to work with Ruby 3.0. You will need to use Rails 6.0.3 or higher if you want to use Ruby 3.
