### ISSUE TITLE
In Getting Started, ERB tags are incorrectly printed resulting in unnecessary brackets being displayed

### ISSUE THREAD

**Issue by julianharr** [rails/rails#41085]
### Steps to reproduce
Printing the ERB tags causes the **new.html.erb** page to display square brackets unnecessarily.
```
<%= @article.errors.full_messages_for(:title).each do |message| %>
<%= @article.errors.full_messages_for(:body).each do |message| %>

```

### Expected behavior
Excluding the equals sign from both of these lines eliminates the square brackets being displayed.

```
<% @article.errors.full_messages_for(:title).each do |message| %>
<% @article.errors.full_messages_for(:body).each do |message| %>
```

### Actual behavior
Square brackets are appended to the `<%= form.text_field :title %>` and `<%= form.text_area :body %>` if included with the validation error message ERB.

### System configuration
Rails 6.1.1

ruby 2.6.6

**Comment by jonathanhefner** [comment]
Thank you for opening an issue!  This has been fixed by #40891.
