### ISSUE TITLE
"NoMethodError (undefined method `-@' for #<Class:...>)" in has_many

### ISSUE THREAD

**Issue by elv1ss** [rails/rails#41092]
### Steps to reproduce
Models:
```ruby
class StateEvent < ActiveRecord::Base; end

class TransitDetail < ActiveRecord::Base
  belongs_to :transit
  belongs_to :detail, polymorphic: true
end

class Transit < ActiveRecord::Base
  has_many :transit_details
  has_many :state_events, through: :transit_details, source: :detail, source_type: StateEvent
end
```

### Expected behavior
In Rails 6.0, `transit.state_events` returns collection without errors.

### Actual behavior
In Rails 6.1, `transit.state_events` throws `NoMethodError (undefined method '-@' for #<Class:0x00007f813c7e39d8>)` exception.

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 2.6.6

### Reproducing test
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", '~> 6.1.1'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :transits, force: true do |t|
  end

  create_table :transit_details, force: true do |t|
    t.references :transit, foreign_key: true, null: false
    t.references :detail, polymorphic: true, null: false
  end

  create_table :state_events, force: true do |t|
  end
end

class StateEvent < ActiveRecord::Base; end

class TransitDetail < ActiveRecord::Base
  belongs_to :transit
  belongs_to :detail, polymorphic: true
end

class Transit < ActiveRecord::Base
  has_many :transit_details
  has_many :state_events, through: :transit_details, source: :detail, source_type: StateEvent
end

class BugTest < Minitest::Test
  def test_state_events
    transit = Transit.create!
    state_event = StateEvent.create!
    TransitDetail.create!(transit: transit, detail: state_event)

    assert_raises(NoMethodError) { transit.state_events }
  end
end
```

**Comment by kamipo** [comment]
Thanks for the report, I've fixed the NME for the case of a symbol in #41098.

But for the case of a class, I suppose it doesn't work anymore since Rails 5.1 because the class predicate handler is removed in b4664864c972463c7437ad983832d2582186e886.

And also, `class_name` as a class is deprecated in 5.1 and raise an `ArgumentError` in 5.2 e65aff70696be52b46ebe57207ebd8bb2cfcdbb6.
Probably we missed `source_type` at that time, but `source_type` should also not be given as a class.

**Comment by intrip** [comment]
@kamipo since this behaviour is not supported what about raising an error also when `source_type` is given as a class (as we already do for `class_name`) ? 

I'd be happy to attach a PR for that.

**Comment by kamipo** [comment]
Feel free to open a PR if you are interested.

**Comment by intrip** [comment]
> Feel free to open a PR if you are interested.

sure! Will do.

**Comment by intrip** [comment]
@kamipo I've created https://github.com/rails/rails/pull/41187. could you take a peek? 🙏
