### ISSUE TITLE
Wrong initialization of belongs_to association

### ISSUE THREAD

**Issue by dilshod** [rails/rails#41091]
### Steps to reproduce
create a new empty project with only a model:
```
class CreatePages < ActiveRecord::Migration[6.1]
  def change
    create_table :pages do |t|
      t.references :page
      t.timestamps
    end
  end
end
```
```
class Page
  belongs_to :page, optional: true
end
```

### Expected behavior
```
p = Page.create
p.page # it is nil
Page.new.page = p
p.page # it is nil
```

### Actual behavior
```
p = Page.create
p.page # it is nil
Page.new.page = p
p.page # it is <Page id: nil, page_id: 4, created_at: nil, updated_at: nil> 
```

### System configuration
**Rails version**: 6.1.1
**Ruby version**: 2.6.3

**Comment by intrip** [comment]
@dilshod I couldn't reproduce the issue with ruby `2.4.3` and Rails `6.1.1` by using the [following script](https://gist.github.com/intrip/3525944a05ed5c80d94fc5838afcca95).

Could you please send us a script to reproduce the issue?

**Comment by dilshod** [comment]
@intrip Weird, it works on your script on the same gem files, but in real rails app it fails,
I made the same test file, and when I run rake test it fails
```
require "test_helper"

class PageTest < ActiveSupport::TestCase
  test "Test" do
    p = Page.create
    assert_nil p.page
    Page.new.page = p
    assert_nil p.page
  end
end
```
```
Failure:
PageTest#test_Test [/Users/dilshod/Test/testrails/test/models/page_test.rb:8]:
Expected #<Page id: nil, page_id: 980190963, created_at: nil, updated_at: nil> to be nil.
```

**Comment by intrip** [comment]
Is it a brand new Rails app? 
Which DB adapter are you using (might be related) ? 
The key is that we need to figure out a way to reproduce it in an empty rails app to make sure it's a framework issue.

**Comment by dilshod** [comment]
yes, it's a brand new rails app, default sqlite adapter, I'm trying to reproduce it in the script

**Comment by dilshod** [comment]
it works correct if I change config.load_defaults in config/application.rb to 6.0, and fails if it is 6.1

**Comment by dilshod** [comment]
here is the [script](https://gist.github.com/dilshod/e7d340e67868bb1cfa1d1da1695da28b) which can reproduce it,
I only added
```
ActiveRecord::Base.has_many_inversing = true
```

**Comment by dilshod** [comment]
It works correct if I do this
```
class Page < ActiveRecord::Base
  has_many :pages, inverse_of: :page
  belongs_to :page, optional: true, inverse_of: :pages
end
```

**Comment by gmcgibbon** [comment]
This is intended. When upgrading your app you [opt into this behaviour](https://github.com/rails/rails/blob/f10dfa7f0ed8dcbb03dc65877797d29f6f6aca9e/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults_6_1.rb.tt#L10).
