### ISSUE TITLE
"Unsupported argument type: NilClass. Construct an Arel node instead." when using where(polymorphic_association: [])

### ISSUE THREAD

**Issue by jalyna** [rails/rails#41105]
First of all thanks for the great work! I hope I thoroughly checked all created issues so this is no duplicate.

### Steps to reproduce

I created a minimal repository with rails new :
- https://github.com/jalyna/demo-polymorphic-rails61-issue (using rails 6.1.1, error also appears on 6.1.0)

See minimal changes in this commit:
https://github.com/jalyna/demo-polymorphic-rails61-issue/commit/928fd7b875a5acf9dc479862acd7f0745a550ae1

Basically this test

```rb
assert_nil Subscription.find_by(plan: []) # plan is a polymorphic belongs_to association
```

fails with `6.1.x`, resulting in: `Unsupported argument type: NilClass. Construct an Arel node instead.`

I also created a branch using `6.0.3` where the test passes. https://github.com/jalyna/demo-polymorphic-rails61-issue/tree/rails60

This test will pass though (no rows within `public_plans`):

```rb
assert_nil Subscription.find_by(plan: PublicPlan.all)
```

The workaround I'm currently using in my projects is to not trigger a query when the array is empty.

### Expected behavior

```rb
Subscription.find_by(plan: []) # plan is a polymorphic belongs_to association
```

should return nil

### Actual behavior

```rb
Subscription.find_by(plan: []) # plan is a polymorphic belongs_to association
```

raises: `Unsupported argument type: NilClass. Construct an Arel node instead.`

### System configuration
**Rails version**: 6.1.0 & 6.1.1

**Ruby version**: 2.7.1

**Comment by dbussink** [comment]
This was fixed with https://github.com/rails/rails/pull/40951, the same issue was identified in https://github.com/rails/rails/pull/40951#issuecomment-757078536. There's no release yet though afaik that includes this fix.

**Comment by jalyna** [comment]
@dbussink thank you!
