### ISSUE TITLE
Provide a way to disable active_storage

### ISSUE THREAD

**Issue by vpereira** [rails/rails#41106]
### Steps to reproduce

Migrate a 6.0.34 application to 6.1.1  without any active_storage configuration (no Rails.root/config/storage.yml)

### Expected behavior
The application runs as before

### Actual behavior
Error: 

```
/usr/lib64/ruby/gems/2.5.0/gems/activestorage-6.1.1/lib/active_storage/engine.rb:121:in `block (2 levels) in <class:Engine>': 
Couldn't find Active Storage configuration in /home/frontend/project/src/api/config/storage.yml (RuntimeError)
rake aborted!
Command failed with status (1)
```

### System configuration
Rails 6.1.1
Ruby 2.5.0

The first two lines of my `config/application.rb` look like:

```
require_relative 'boot'

require 'rails/all'
```

Is the `require 'rails/all'` responsible for loading the `active_storage`?

**Comment by jonathanhefner** [comment]
This is tangential to #39498, which I would like to revive at some point.

**Comment by AkashHC13** [comment]
Is there a workaround for this?

**Comment by rafaelfranca** [comment]
Not a workaround. There is an official way to disable any of the rails frameworks. That way is to remove the `require "rails/all"` on top of `config/application.rb` and require only the railties you want to use. The list of railties can be found here https://github.com/rails/rails/blob/59b3d372a8f7da5b3f50471575bd8189c531b3ab/railties/lib/rails/generators/rails/app/templates/config/application.rb.tt#L9-L19
