### ISSUE TITLE
reduce the unecessary changes introduced by major updates

### ISSUE THREAD

**Issue by vpereira** [rails/rails#41109]
Looking the diff between Rails 6.0.34 and 6.1, there are a lot of unnecessary changes - sometimes even contradictory.

Take for example the diff http://railsdiff.org/6.0.3.4/6.1.0

For example, the quotes changes (contradictory, i.e `Rakefile` x `config.ru` ), or comments update, could be done in a minor release. This is an issue when we want to diff using `rails app:update` while doing a major update.

**Comment by gmcgibbon** [comment]
The quote changes were a result of https://github.com/rails/rails/pull/38841 in templates. These kinds of changes don't happen normally and Rails doesn't accept stylistic PRs by default.

The comment changes on the other hand are a natural part of the framework and could be useful in the event the comment changed was simply incorrect. I personally don't think there are enough to justify a separate release.

Sorry for the extra noise, but the release has already shipped, so I'm going to closet this. Thank you for the issue.
