### ISSUE TITLE
Deprecated Constants cannot be inherited

### ISSUE THREAD

**Issue by jasonkarns** [rails/rails#41110]
### Steps to reproduce
```rb
class OldClass; end
class NewClass; end

OldClass = ActiveSupport::Deprecation::DeprecatedConstantProxy.new('OldClass', 'NewClass')

Class.new(OldClass)
```

results in

### Expected behavior

I expected to be able to create subclasses using the "OldClass" constant, which references the deprecated constant proxy for the new class.

### Actual behavior

`TypeError: superclass must be a Class (ActiveSupport::Deprecation::DeprecatedConstantProxy given)`

### System configuration
**Rails version**: 6.0.3.2

**Ruby version**: 2.6.5

**Comment by gmcgibbon** [comment]
`ActiveSupport::Deprecation::DeprecatedConstantProxy` is a **constant** proxy that has no guarantees for subclassing. From a API design perspective, you use it as a convenient substitute for a single constant in your public API.

> I expected to be able to create subclasses using the "OldClass" constant, which references the deprecated constant proxy for the new class.

If the constant was a module or an array (for example), inheritance wouldn't make sense. There might be room for a `DeprecatedClassProxy` that returns a metaprogrammed class to solve this use-case.

**Comment by jasonkarns** [comment]
> is a **constant** proxy that has no guarantees for subclassing

Possibly. That seems like a thin reading for what a constant is. class names _are_ constants in Ruby, so it seems perfectly reasonably (to me, :D ) to expect `DeprecatedConstantProxy` to work for, well, any constant (which includes classes).

On multiple occasions, rails codebase itself has attempted to use DeprecatedConstantProxy to deprecate a class and has introduced bugs each time:
- https://github.com/rails/rails/pull/27858
- https://github.com/rails/rails/pull/8607

So the current naming definitely seems to imply the ability to deprecate a class in this way; and there is clearly a demonstrated need for the capability. If that behavior needs separated into its own proxy, that would solve the need. (I would hope there is also the ability somewhere to do the same for modules.) Then we could clearly document classes/modules as an exception not covered by `DeprecatedConstantProxy`, despite the name.

**Comment by matthewd** [comment]
I think this is at best a[n impossible] feature request.

> [I] expect DeprecatedConstantProxy to work for, well, any constant

"Proxy" is right in the name, though. It provides a proxy, which enables it to defer the warning until later, but that carries unavoidable trade-offs.

It sounds like you're describing `deprecate_constant` -- which is intended to be the first option a potential caller will find (because it's a friendly method, not a build-it-yourself class), and which makes a different trade-off by immediately returning the "real" object, able to be used in a wider range of circumstances, but also consequently producing the warning earlier.
