### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by jim-ttc** [rails/rails#41116]
### Steps to reproduce
go to docs https://edgeguides.rubyonrails.org/configuring.html#rails-railtie-initializer

### Expected behavior
You may put your initializer before or after any other initializer in the chain, as long as it is logical. Say you have 4 initializers called "one" through "four" (defined in that order) and you define "four" to go before **"two"** but after "three", that just isn't logical and Rails will not be able to determine your initializer order.

### Actual behavior
You may put your initializer before or after any other initializer in the chain, as long as it is logical. Say you have 4 initializers called "one" through "four" (defined in that order) and you define "four" to go before **"four"** but after "three", that just isn't logical and Rails will not be able to determine your initializer order.

**Comment by gmcgibbon** [comment]
Hm, you're right, this is incorrect. I'll fix it.
