### ISSUE TITLE
rails 6.2.0.alpha - depends on coffeescript in javascript less rails instance

### ISSUE THREAD

**Issue by koenhandekyn** [rails/rails#41120]
### Steps to reproduce

create a javascriptless app in rails 6.1.0. 
the app does not explicit have references to coffee script. 
validate the app launches and basic stuff works. 
upgrade the rails app to current main branch. 

### Expected behavior

the app still works

### Actual behavior

first, the app does not start due to reference to coffee. after adding `config.generators.javascript_engine = :js` the app starts but we still get an error `cannot load such file -- coffee_script`

### System configuration

**Rails version**:  current master branch
**Ruby version**: 2.7.2

**Comment by gmcgibbon** [comment]
I can't reproduce this. Please provide an example app that demonstrates the issue.

**Comment by jonathanhefner** [comment]
This sounds like rails/sprockets#183.
