### ISSUE TITLE
action_text installation fails on rails 6.1.1

### ISSUE THREAD

**Issue by AlexUkPC** [rails/rails#41123]
Hi, I'm trying to learn Rails but I have a problem with action_text installation. Please don't tell me it's a dup of https://github.com/rails/rails/issues/40942 because someone closed that issue but I have the same problem. You can see in the pictures that my file yarn.tt is exactly as it was changed in https://github.com/rails/rails/pull/40950. Thank you.
![cmd](https://user-images.githubusercontent.com/51413109/104715082-f326b380-571d-11eb-9993-e371d5650cb7.PNG)
![win](https://user-images.githubusercontent.com/51413109/104715084-f3bf4a00-571d-11eb-9b0e-3f2f19ac273c.PNG)
![yarn](https://user-images.githubusercontent.com/51413109/104715085-f3bf4a00-571d-11eb-9265-0c710f7f79a6.PNG)
![yarn_project](https://user-images.githubusercontent.com/51413109/104715087-f3bf4a00-571d-11eb-9bcf-34abf20961ee.PNG)

### Steps to reproduce
On a windows 10 computer

Install ruby 2.7.2p137
Install rails 6.1.1
Install node 14.15.4
Install yarn 1.22.5
create a project
install action_text with command: action_text:install

### Expected behavior
action_text should install successfully.

### Actual behavior
rails action_text:install
       rails  app:binstub:yarn
Installing JavaScript dependencies
         run  bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.1 from "."
rails aborted!
Errno::ENOEXEC: Exec format error - bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.1

Tasks: TOP => action_text:install
(See full trace by running task with --trace)

### System configuration
Rails 6.1.1

Ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

**Comment by jonathanhefner** [comment]
#40942 was in the context of MinGW, so it's possible that this is a different issue, or that I was wrong about the root cause.  Unfortunately, I do not have a Windows machine to test on.

Looking at the error message again, I'm wondering if the problem is actually from running `bin/yarn` itself.  Could you add `STDERR.puts "HERE"` above `APP_ROOT = ...` in `bin/yarn` to verify that the script is being executed?  If it is, could you also add `STDERR.puts yarn.inspect` before `exec yarn` and share the result?

**Comment by AlexUkPC** [comment]
I get the same output as before:
![inspect](https://user-images.githubusercontent.com/51413109/104753281-ac51b180-574f-11eb-96f2-00508a8bb4e1.PNG)

**Comment by des-albert** [comment]
Perhaps a full trace would assist with diagnosis

![Capture](https://user-images.githubusercontent.com/7909090/105104102-846f9000-5a66-11eb-8fbf-f9a0b172b8a1.PNG)

**Comment by rafaelfranca** [comment]
Looking the output the `bin/yarn` file is not even being executed. Not sure why the exec format is invalid on windows. Maybe because of the `@` or `^`?

**Comment by jonathanhefner** [comment]
I believe it's because Windows can't run shebang scripts, i.e. any bin stubs.  We have a [note to this effect](https://guides.rubyonrails.org/v6.1.0/getting_started.html#starting-up-the-web-server) in the Getting Started guide.  I was planning to open a PR to address this either today or tomorrow.

**Comment by des-albert** [comment]
Has this issue changed since rails 6.0.3 ?  After a downgrade, the problem did not a occur. Something has clearly changed between 6.0.3 and 6.1.1
