### ISSUE TITLE
Is it possible to remove schema version from schema.rb ?

### ISSUE THREAD

**Issue by kriom** [rails/rails#41128]
### Context
It's not really a bug, but as many of us are writing migrations, we always have conflicts on a line of `db/schema.rb` when we merge our branches.

```ruby
 ActiveRecord::Schema.define(version: 2021_01_15_140505) do
```

What is the purpose of this line? It only gives the last migration version which is the latest in the migration directory. If I want to know it I can also go and look in this directory. This version number doesn't even guarantee that all the migrations have been passed. From my little point of view it's useless, isn't it? Wouldn't it be possible to generate schema without it?

### Steps to reproduce
```
me@here:~/apps/super_app on (feature-what-to-do)
$ rails g migration do_nothing
```

```
my_colleague@elsewhere:~/apps/super_app on (feature-do-something)
$ rails g migration do_nothing_interesting
```
Then we commit and push, all tests passed (of course) ... and now we have to merge !
```
me@here:~/apps/super_app on (feature-what-to-do)
$ git merge feature-do-something
...
```

### Expected behavior
```
...
Auto-merging db/schema.rb
[NO CONFLICT]
```
because the version is not set in \schema.rb\
```ruby
 ActiveRecord::Schema.define do
```

### Actual behavior
```
...
Auto-merging db/schema.rb
CONFLICT (content): Merge conflict in db/schema.rb

$ cat db/schema.rb
++<<<<<<< HEAD                                                                     
 +ActiveRecord::Schema.define(version: 2021_01_15_140505) do
++=======                                                          
+ ActiveRecord::Schema.define(version: 2021_01_15_140404) do
++>>>>>>> 9d17cc5330... Add Webhook Integration Permission (billing_manager)
```
And as always thank you for everything !

### System configuration
**Rails version**: 
`Rails 6.1.1`

**Ruby version**:
`ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]`

**Comment by esparta** [comment]
> What is the purpose of this line?

`Migrations, mighty as they may be, are not the authoritative source for your database schema. Your database remains the authoritative source. By default, Rails generates db/schema.rb which attempts to capture the current state of your database schema.`

https://edgeguides.rubyonrails.org/active_record_migrations.html#schema-dumping-and-you

**Comment by kriom** [comment]
While waiting to see if it's possible (delete the schema version) I created an empty migration date of December 31, 2029 at 23:59:59 📆 to be quiet until then 😈.
Of course this will only work with the branches of the project that already include this migration ☝️🤓. 
I don't see what problems this could cause and if I discover one I will let you know.
🖐️😊

**Comment by intrip** [comment]
I think you can deal with the issue by pulling master and running the migration before dealing with the conflicts

**Comment by kriom** [comment]
Yes but when, in my branch, I have several commits with a migration in each one and that I rebase over the target branch of the merge I get a conflict on each commit which is boring.
So a workaround is that I squash all my commits during the rebase but my colleagues don't like it too much for code review.

**Comment by rafaelfranca** [comment]
It is possible to remove the schema version from the schema, but I don't recommend you doing it, and we are not going to change Rails default behavior to be like that since it causes more confusing problems than merge conflicts. It is there so Rails knows which migrations were already run to generate that schema. Without it Rails would need to run every single migration, every time, causing your application, if the schema was already loaded, to try to create tables that are already defined in the schema, failing with an "table already exist" error.

You can see what is does here https://github.com/rails/rails/blob/32e5d55a277690a8b4e58864bb2542d93ceaa017/activerecord/lib/active_record/schema.rb#L54. As the name of the method says, it tells rails to assume that all migrations up to that version are already run, so it doesn't need to run any of them.

One way to solve those conflicts automatically is to use git attributes to do this as for example here https://gist.github.com/jeromedalbert/afab24e80102b41d75d5f5538f1459c4

**Comment by kriom** [comment]
Thank you very much for this answer and this elegant solution based on git attributes. :+1:

**Comment by phuongnd08** [comment]
> It is possible to remove the schema version from the schema, but I don't recommend you doing it, and we are not going to change Rails default behavior to be like that since it causes more confusing problems than merge conflicts. It is there so Rails knows which migrations were already run to generate that schema. Without it Rails would need to run every single migration, every time, causing your application, if the schema was already loaded, to try to create tables that are already defined in the schema, failing with an "table already exist" error.
> 
> You can see what is does here
> 
> [rails/activerecord/lib/active_record/schema.rb](https://github.com/rails/rails/blob/32e5d55a277690a8b4e58864bb2542d93ceaa017/activerecord/lib/active_record/schema.rb#L54)
> 
> Line 54 in [32e5d55](/rails/rails/commit/32e5d55a277690a8b4e58864bb2542d93ceaa017)
> 
>  connection.assume_migrated_upto_version(info[:version]) 
> . As the name of the method says, it tells rails to assume that all migrations up to that version are already run, so it doesn't need to run any of them.
> One way to solve those conflicts automatically is to use git attributes to do this as for example here https://gist.github.com/jeromedalbert/afab24e80102b41d75d5f5538f1459c4

I don't see how this design make sense.
given there is 3 branch happens in parallel, with each add a migration of v1 < v2 < v3.
Now branch of v3 is merged, then migration run, rails then assume that is is on v3. and later branch of v1 and branch of v2 is merged, what will happens? As of right now, rails is storing executed version in schema_migrations table, then what is the point of that version on schema.rb again?
