### ISSUE TITLE
filter_parameter_logging.rb - filters :passw - is this expected behaviour?

### ISSUE THREAD

**Issue by benkoshy** [rails/rails#41150]
### Steps to reproduce

```ruby
rails new test_app
```
Here is a repo that I've prepared (in case you want it):

`git clone git@github.com:benkoshy/test_app.git`

### Expected behavior
Unless I'm missing something here, I would expect `:password` rather than `:passw` to be a filtered parameter? Unsure if this is a bug or not. 

```ruby
# ./config/initializers/filter_parameter_logging.rb
Rails.application.config.filter_parameters += [
  :password  ## <---- note the full word here
  # etc.
]
```

### Actual behavior

```ruby
Rails.application.config.filter_parameters += [
  :passw ## but only half the word is here?!
]
```

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 2.7.1p0

### Is this expected behaviour or not?

If not, I'm happy to put in a PR for this.

Thanks for reviewing

**Comment by abhaynikam** [comment]
@benkoshy `:passw` is expected filter_parameter here. The changes were done in PR: https://github.com/rails/rails/pull/40513 and here is the exact reasoning for why `password` was changed to `passw`(In short, filter_parameters uses regex matching so password would always be filtered): https://github.com/rails/rails/pull/40513#issuecomment-727598707 😊
