### ISSUE TITLE
Getting Started Guide - Validation Errors not rendering

### ISSUE THREAD

**Issue by goatatwork** [rails/rails#41159]
### Steps to reproduce

In the Getting Started Guide, In the section labeled `6.3.3 Validations and Displaying Error Messages`, the following syntax is used to start a new form:

```
<%= form_with model: @article do |form| %>
```

The following syntax needs to be used instead:

```
<%= form_with model: @article, local: true do |form| %>
```

### Expected behavior

`@article.errors` will be populated and therefore be available to work with in the view.

### Actual behavior

The default behavior of `form_with` is to  submit data using an XHR (Ajax) request. When attempting to work with validation errors in the view as documented, none are rendered and it seems as though they are not being added to `@article` at all judging by throwing `<%= debug @article.errors %>` at the bottom of `new.html.erb`.

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.6-alpine

**Comment by louim** [comment]
Hey @goatatwork,

I see you're using Rails 6.0. The default behaviour of form_with [was updated in Rails 6.1 to generate local forms by default](https://github.com/rails/rails/pull/40708). The docs correctly describe the behavior for Rails 6.1.

**Comment by goatatwork** [comment]
Hey @louim,

That will teach me to drag around old container images! Thank you so much for the clarification.
