### ISSUE TITLE
Rails 5.1 (And 6.1) Generated Column Gets Extra '\' in schema MySQL

### ISSUE THREAD

**Issue by danothemen** [rails/rails#41156]
### Steps to reproduce

Create a table with a JSON column, then add a generated column that uses JSON_EXTRACT to store part of the json document in a generated column

[Example pulled from guidelines](https://gist.github.com/danothemen/44f6fbae2e5f98efac8f1e9210cc8347)

### Expected Output for Schema
```
ActiveRecord::Schema.define(version: 0) do

  create_table "payments", force: :cascade do |t|
    t.decimal "amount", precision: 10, default: "0", null: false
    t.json "invoice"
    t.virtual "invoice_id", type: :integer, as: "json_extract(`invoice`,(_utf8mb3\'$.id\' collate utf8mb3_general_ci))", stored: true
  end

end
```

### Actual behavior

```
ActiveRecord::Schema.define(version: 0) do

  create_table "payments", force: :cascade do |t|
    t.decimal "amount", precision: 10, default: "0", null: false
    t.json "invoice"
    t.virtual "invoice_id", type: :integer, as: "json_extract(`invoice`,(_utf8mb3\\'$.id\\' collate utf8mb3_general_ci))", stored: true
  end

end
```

### System configuration
**Rails version**:
5.1
**Ruby version**:
2.6.6

**Comment by louim** [comment]
Hey! can you reproduce in Rails 6.1? Rails 5.1 not supported anymore.

**Comment by danothemen** [comment]
> Hey! can you reproduce in Rails 6.1? Rails 5.1 not supported anymore.

Hello! Yes it turns out that I can reproduce this in Rails 6.1 also, the behavior is identical.

**Comment by intrip** [comment]
@danothemen the key is that the `SchemaDumper` [calls `.inspect` on the query result](https://github.com/rails/rails/blob/v6.1.1/activerecord/lib/active_record/connection_adapters/mysql/schema_dumper.rb#L82) which leads into escaping `\`. 
This approach is consistent across the whole `SchemaDumper` classes, I don't think it's actually a bug.

looping into @kamipo for further feedback.

**Comment by danothemen** [comment]
> @danothemen the key is that the `SchemaDumper` [calls `.inspect` on the query result](https://github.com/rails/rails/blob/v6.1.1/activerecord/lib/active_record/connection_adapters/mysql/schema_dumper.rb#L82) which leads into escaping `\`.
> This approach is consistent across the whole `SchemaDumper` classes, I don't think it's a bug.
> 
> looping into @kamipo for further feedback.

This results in a SQL syntax error when trying to set up the db from schema.rb, despite the original migration running just fine.

**Comment by intrip** [comment]
> > @danothemen the key is that the `SchemaDumper` [calls `.inspect` on the query result](https://github.com/rails/rails/blob/v6.1.1/activerecord/lib/active_record/connection_adapters/mysql/schema_dumper.rb#L82) which leads into escaping `\`.
> > This approach is consistent across the whole `SchemaDumper` classes, I don't think it's a bug.
> > looping into @kamipo for further feedback.
> 
> This results in a SQL syntax error when trying to set up the db from schema.rb, despite the original migration running just fine.

You mean that `rails db:schema:load` will raise an error in such situation ?

**Comment by danothemen** [comment]
I believe so, I was running `rails db:reset` though

**Comment by intrip** [comment]
> Yes, though I was running `rails db:reset` while testing

Yes, looks like there is an issue when we try to load the generated schema, you can reproduce it with [this gist](https://gist.github.com/intrip/180694fc9a2f1f99481d5f93df74fd51). 

I'll take a deeper lock and let you know.

**Comment by intrip** [comment]
I've pushed #41292 which should fix this.
