### ISSUE TITLE
before_action is not working as expected

### ISSUE THREAD

**Issue by MuhammadRazaAslam** [rails/rails#41169]
### Steps to reproduce

**Step 1:** Add a `resources :books` in routes.rb
**Step 2:** Create a following controller

```
class BooksController < ApplicationController
  before_action :method1, only: [:index]
  before_action :method1, only: [:new]

  def new
    byebug
    puts "Called: Create"
  end

  def index
    byebug
    puts "Called: Index"
  end

  def method1
    byebug
    puts "Called: Method1"
  end
end
```

**Step 3:** Start the server
**Step 4:** Open http://localhost:3000/books in browser

### Expected behavior

When we open http://localhost:3000/books in the browser then method1 should be called but it's not calling.
### Actual behavior

If I remove the `before_action :method1, only: [:new]` and open [http://localhost:3000/books in the browser then `method1` is calling.

### System configuration
**Rails version**:
5.1.7
**Ruby version**:
2.6.6

**Comment by hmkashif** [comment]
@MuhammadRazaAslam I am having same issue. My guess is, while registering same callback(`before_action: method1`) for two different methods (`index` and `new`) later one will be registered and all others will be ignored.

We can also do this `before_action :method1, only: [:index, :new]` as an alternative.

**Comment by eileencodes** [comment]
> We can also do this before_action :method1, only: [:index, :new] as an alternative.

This is the correct way to do it as writing a second `before_action` with the same method will override. This is true of any callback and isn't considered a framework bug. I'm going to close this out.

**Comment by MuhammadRazaAslam** [comment]
@hmkashif Thank you for sharing a solution with me.

**Comment by MuhammadRazaAslam** [comment]
@eileencodes Thank you for telling me. Can you share the documentation link where it is explained?

**Comment by flavorjones** [comment]
@MuhammadRazaAslam https://guides.rubyonrails.org/action_controller_overview.html

![image](https://user-images.githubusercontent.com/8207/105072667-102bf100-5a54-11eb-8556-2c6980bdd817.png)

**Comment by williantenfen** [comment]
something like this wouldn't work:
```ruby
before_action :check_mfa_done_in_threshold, only: %i(destroy)
before_action :check_mfa_done_in_threshold, only: %i(new create), if: -> { current_user.two_factor_enabled? }
```
