### ISSUE TITLE
ActionText permitted html attributes in rendered rich text insufficient

### ISSUE THREAD

**Issue by haroldus-** [rails/rails#41163]
add a `<%= link_to blob.url, target: :_blank do %>...<% end %>` to `views/active_storage/blobs/_blob.html.erb` partial so app user can get to pdf proper from preview or the original of the image in a new tab

one would expect the `target` html attribute to be rendered

but it is sanitized away by the `sanitize_action_text_content` method within `ActionText::ContentHelper`

`Rails::Html::Sanitizer.safe_list_sanitizer.allowed_tags` includes the `a` html tag so you would expect its associated attributes to also be allowed

my workaround is to put `ActionText::Attachment::ATTRIBUTES << "target"` in an initializer

**Rails version**: 6.1.1

**Comment by abhaynikam** [comment]
@haroldus- I have faced similar issue in past and my workaround was as follows:
```
# config/initializers/action_text.rb
ActionText::ContentHelper.allowed_attributes += %w[ target ]
```

Hope this helps 😊

**Comment by Alexander-Senko** [comment]
> ```ruby
> # config/initializers/action_text.rb
> ActionText::ContentHelper.allowed_attributes += %w[ target ]
> ```

I tried this, but got `nil` in `ActionText::ContentHelper.allowed_attributes`. So, here is my variant:

```ruby
# config/initializers/action_text.rb
Rails::HTML::SafeListSanitizer.allowed_attributes += %w[ target ]
```

**Comment by Alexander-Senko** [comment]
See [the docs](https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-sanitize-label-Global+Configuration) for `ActionView::Helpers::SanitizeHelper#sanitize`:

> To set the default allowed tags or attributes across your application:
> 
> ```ruby
> # In config/application.rb
> config.action_view.sanitized_allowed_tags = ['strong', 'em', 'a']
> config.action_view.sanitized_allowed_attributes = ['href', 'title']
> ```
