### ISSUE TITLE
Heroku perform_later undefined method error after added has_one_attached

### ISSUE THREAD

**Issue by vilusa** [rails/rails#41177]
Hi everyone,

Project is active using paperclip. And we using Sidekiq for background job process. We try ActiveStorage migration for each model. So far, we have completed the migration of the two models without any problems. But driver gives model, methods of method undefined error on just background jobs. When I run it as perform_now it doesn't give any error and complete it successfully. I removed the has_one_attached relation, it doesn't give any exception. And at my local development environment works successfully as perform_later and perform_now.

### My Class
```ruby
class Driver < ApplicationRecord
   has_one_attached :photo
end
```

Previously, `paperclip`  relation was defined as `photo`

### Error Logs
``` undefined method `photo' for #<Driver:0x000055b0d3502088>```
``` undefined method `name' for #<Driver:0x000055b0d3502088>```

### System configuration
**Rails version**:  6.0.3.2

**Ruby version**: 2.6.6

**Sidekiq version**: 5.2.5

**Comment by composerinteralia** [comment]
Nothing is coming to mind for me. Could you provide an [executable test case](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) or a sample application that reproduces the problem? Without that there is not much we can do to help unless somebody happens to have a hunch.

**Comment by yoones** [comment]
Did your sidekiq process take into account the new code change or is it still running on previous release?
