### ISSUE TITLE
ActiveStorage configuration resolve_model_to_route is not picked up by rails_blob_* URL generator

### ISSUE THREAD

**Issue by aliismayilov** [rails/rails#41172]
### Steps to reproduce

1. Create a new rails app.
2. Set up activestorage with Amazon (S3) as backend service.
3. Set `config.active_storage.resolve_model_to_route = :rails_storage_proxy`.
3. Create a model with attachment. E.g. `class Picture < ApplicationRecord; has_one_attached :file; end`.
4. Create a new record with attachment.
5. Render `rails_blob_path`.

### Expected behavior
The link should start with `/rails/active_storage/blobs/proxy/`.

### Actual behavior
The link starts with `/rails/active_storage/blobs/redirect/`.

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 2.7.2p137

**Comment by weilandia** [comment]
Related:

I'm seeing 
```
Rails.application. config.active_storage.resolve_model_to_route = :rails_storage_proxy

obj = ActiveStorage::Attachment.first

Rails.application.routes.url_helpers.url_for(obj) == "http://localhost:3000/rails/active_storage/blobs/proxy/..."

# BUT

Rails.application.routes.url_helpers.rails_blob_url(obj) == "http://localhost:3000/rails/active_storage/blobs/redirect/..."
```

Is this by design?

**Comment by aliismayilov** [comment]
> Related:
> 
> I'm seeing
> 
> ```
> Rails.application.config.active_storage.resolve_model_to_route = :rails_storage_proxy
> 
> obj = ActiveStorage::Attachment.first
> 
> Rails.application.routes.url_helpers.url_for(obj) == "http://localhost:3000/rails/active_storage/blobs/proxy/..."
> 
> # BUT
> 
> Rails.application.routes.url_helpers.rails_blob_url(obj) == "http://localhost:3000/rails/active_storage/blobs/redirect/..."
> ```
> 
> Is this by design?

I wouldn't think this is intentional. From my understanding of the docs and release notes is that `rails_storage_proxy` should generate proxy URLs by default. In case you need to use the redirect strategy while the default is proxy, you'll need to use `rails_storage_redirect_url`.

**Comment by composerinteralia** [comment]
It looks like when we added proxying in https://github.com/rails/rails/pull/34477 the `rails_blob` and `rails_representation` url helpers didn't come along for the ride. Unsure whether that was intentional, but one way to fix would be to change:

https://github.com/rails/rails/blob/af9c910db799ab1f238b2e8116f8099f76164b6c/activestorage/config/routes.rb#L18-L24

```diff
 direct :rails_representation do |representation, options| 
-   signed_blob_id = representation.blob.signed_id 
-   variation_key  = representation.variation.key 
-   filename       = representation.blob.filename 
-  
-   route_for(:rails_blob_representation, signed_blob_id, variation_key, filename, options)
+   route_for(ActiveStorage.resolve_model_to_route, representation, option) 
 end 
```

and

https://github.com/rails/rails/blob/af9c910db799ab1f238b2e8116f8099f76164b6c/activestorage/config/routes.rb#L30-L32

```diff
 direct :rails_blob do |blob, options| 
-   route_for(:rails_service_blob, blob.signed_id, blob.filename, options) 
+   route_for(ActiveStorage.resolve_model_to_route, blob, option) 
 end 
```

**Comment by aliismayilov** [comment]
@composerinteralia please see https://github.com/rails/rails/pull/41186

**Comment by composerinteralia** [comment]
Ah, I totally missed your PR. Left one comment, but what you did makes sense to me.
