### ISSUE TITLE
Opting out of strict loading

### ISSUE THREAD

**Issue by ayrton** [rails/rails#41171]
### Steps to reproduce

Given the following code:

```rb
# config/application.rb
module MyApplication
  class Application < Rails::Application
    config.active_record.strict_loading_by_default = true
  end
end

# app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
end

# app/models/user.rb
class User < ApplicationRecord
  has_many :subscriptions, inverse_of: :user
end

# app/jobs/archive_subscription_job.rb
class ArchiveSubscriptionJob < ApplicationJob
  def perform(subscription)
    user = subscription.user
    # [...]
  end
end

# test/jobs/archive_subscription_job_test.rb
class ArchiveSubscriptionJobTest < ActiveJob::TestCase
  it 'archives the subscription' do
    subscription = subscriptions(:one)

    perform_enqueued_jobs do
      ArchiveSubscriptionJob.perform_later(subscription)
    end

    assert true
  end
end
```

### Expected behavior

No failures.

### Actual behavior

```sh
$ rails test test/jobs/archive_subscription_job_test.rb
Running via Spring preloader in process 87708
Run options: --seed 31094

# Running:

E

Error:
ArchiveSubscriptionJobTest#test_0001_archives_the_subscription:
ActiveRecord::StrictLoadingViolationError: `Company` called on `Subscription` is marked for strict_loading and cannot be lazily loaded.
    app/jobs/archive_subscription_job.rb:3:in `perform'
    test/jobs/archive_subscription_job_test.rb:13:in `block (3 levels) in <class: ArchiveSubscriptionJobTest>'
    test/jobs/archive_subscription_job_test.rb:12:in `block (2 levels) in <class:ArchiveSubscriptionJobTest>'
    test/jobs/archive_subscription_job_test.rb:11:in `block in <class:ArchiveSubscriptionJobTest>'


rails test test/jobs/archive_subscription_job_test.rb:5



Finished in 0.618767s, 1.6161 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

### Proposal

I think there's a case where you'd want to have strict loading by default but have the option to opt-out eg when using `ActiveJob`.

```rb
subscription.strict_loading!(false)
```

Similar to defining the value of `strict_loading` on [relations](https://github.com/rails/rails/pull/37400/files#diff-79b53b2602bf702bdd8ce677e096be6a6923a54236e17237c16068a510078683) we could accept a value on [records](https://github.com/rails/rails/pull/37400/files#diff-4411c7993e3f8ccfd8e09f44a81f10dfac3ea7dbd44cabd60b369040a00be324). @eileencodes I know you've spent a lot of time building this feature 🙏 would love to hear your thoughts on this. If this sounds reasonable I'm happy to draft a PR.

```rb
# app/jobs/archive_subscription_job.rb
class ArchiveSubscriptionJob < ApplicationJob
  def perform(subscription)
    subscription.strict_loading!(false)

    user = subscription.user
    # [...]
  end
end
```

**Alternatively**: would it make sense to opt-out of strict_loading with `rails/globalid`?

### System configuration

**Rails version**:

6.1.1

**Ruby version**:

3.0.0

**Comment by eileencodes** [comment]
Hi @ayrton! Adding this functionality is on my to do list, but I haven't gotten around to it yet. If you want to work on a PR, please go ahead. 😄

**Comment by ayrton** [comment]
> Hi @ayrton! Adding this functionality is on my to do list, but I haven't gotten around to it yet. If you want to work on a PR, please go ahead. 😄

Sweet! I'll draft something up and then we can take it from there. 👯

**Comment by ayrton** [comment]
Opened PR #41181

**Comment by gmcgibbon** [comment]
Added in https://github.com/rails/rails/pull/41181. Thanks for contributing!
