### ISSUE TITLE
routes.rb calling during initial load

### ISSUE THREAD

**Issue by anson2590** [rails/rails#41185]
### Steps to reproduce
Routes.rb file is getting called for the first time during run time it not getting executed

### Actual behavior
I need a suggestion,  routes.rb file is getting called for the first time during the run time it's not getting executed during runtime I have a requirement where based on condition different action methods to be called. When I added conditions in routes.rb noticed that routes.rb file is called only once during initial loading but in my case condition will change during runtime. Can you please suggest a solution how to add conditions to call different action methods from routes.rb file.

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.6.2

**Comment by viniciusalonso** [comment]
Hey @anson2590, could you provide a bit more context about the problem that are you trying to solve?

**Comment by anson2590** [comment]
hey @viniciusalonso Thank you, Issue got resolved by adding this code
`Rails.application.reload_routes!`

we are good to close this issue
