### ISSUE TITLE
rails new fails at webpacker:install elsewhere

### ISSUE THREAD

**Issue by gfsheppard** [rails/rails#41182]
### Steps to reproduce
I am having a similar issue to #41103
In a new directory:
```
bundle init
bundle config set path 'vendor/bundle'
```
Uncomment #gem rails in Gemfile

```
bundle
bundle exec rails new app
```

### Expected behavior
Should initialize a new rails app

### Actual behavior
At the end of the installation:
```
rails  webpacker:install
Traceback (most recent call last):
	3: from bin/rails:4:in `<main>'
	2: from bin/rails:4:in `require_relative'
	1: from /home/george/bug_test/app/config/boot.rb:4:in `<top (required)>'
/home/george/bug_test/app/config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
```
### System configuration
**Rails version**: Rails 6.1.1
**Ruby version**:Ruby 2.7.0
Bundler version 2.1.2

Entering the directory and manually running `bundle exec rails webpacker:install` succeeds. 

Adding `gem 'bootsnap'` to the Gemfile and retrying rails new yields 
```
rails  webpacker:install
rails aborted!
Don't know how to build task 'webpacker:install' (See the list of available tasks with `rails --tasks`)
```

**Comment by gfsheppard** [comment]
This is an absolute vanilla install of rails. There is no app/tmp folder when the command is run.
There seems to be an error based on which directory webpacker:install is run from.

**Comment by rafaelfranca** [comment]
Does any other command work. Like `bin/rails environment` for example?

**Comment by gfsheppard** [comment]
Other commands seem to work once I am in the rails app folder.
I tried it again on a fresh VM running Mint 20.2, to make sure it wasn't my system.
The same errors occur, but perhaps it has something to do with installing nodejs and yarn?
I don't think so, because the error persists with subsequent new apps.

**Comment by rafaelfranca** [comment]
Do you have webpacker in the gemfile? Because you didn't have `bootsnap` but still have the `bootsnap/setup` require, so I'm guessing you removed bootsnap yourself.

**Comment by rafaelfranca** [comment]
Ok. I just now read what you are doing here. You are generating an app using `bundle init` and `rails new`. I don't think that would work, especially if you are not accepting the `Gemfile` generated by Rails.

Use:

```
gem install rails
rails new my_app
```

instead.

**Comment by gfsheppard** [comment]
Thanks. It works the way you suggest.
