### ISSUE TITLE
#inverse_of and #has_inverse? returning nil for ActiveRecord::Reflection::BelongsToReflection

### ISSUE THREAD

**Issue by tpkonrad** [rails/rails#41190]
### Steps to reproduce
```ruby
ActiveRecord::Schema.define do
    create_table :accounts do |t|
      t.timestamps
    end

    create_table :users do |t|
      t.references :account, foreign_key: true, index: true
      t.timestamps
    end
end

class Account < ActiveRecord::Base
  has_many :users
end

class User < ActiveRecord::Base
  belongs_to :account
end

class BugTest < Minitest::Test
  def test
    has_inverse = User.reflect_on_association(:account).has_inverse?
    inverse_of = User.reflect_on_association(:account).inverse_of

    refute_nil has_inverse
    refute_nil inverse_of
  end
end
```

### Expected behavior
#has_inverse? should return :users symbol insted of nil.
#inverse_of should return an instance of ActiveRecord::Reflection::HasManyReflection instead of nil.

### Actual behavior
#has_inverse? returns nil.
#inverse_of returns nil.

### Additional Information

Adding "inverse_of" option overcomes the problem, but I still think it's a bug...

```ruby
class User < ActiveRecord::Base
  belongs_to :account, inverse_of: :users
end
```

### System configuration
**Rails version**: Tested on Rails 5.2.3 and 6.1.1.

**Ruby version**: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

**Comment by intrip** [comment]
@tpkonrad I'm pretty sure this is not a bug: the `inverse_of` purpose is only to make [associations update working in both directions](https://guides.rubyonrails.org/association_basics.html#bi-directional-associations). 

`inverse_of` works from the `has_many` but not from the `belongs_to` because the latter is not needed.
Check for example [this gist](https://gist.github.com/intrip/a9c83650e346d09866fefcb143cd2832)

**Comment by tpkonrad** [comment]
@intrip thanks for your answer. I understood what you said, but for me it still doesn't make sense for **#inverse_of** and **#has_inverse?** methods to return nil when **both** directions (:belongs_to and :has_many) were informed. 

I'm not sure if It's related, but if you take a look at [ActiveRecord::Reflection::AssociationReflection docs](https://www.rubydoc.info/docs/rails/ActiveRecord/Reflection/AssociationReflection) it has a constant for automatic inverse macros that includes :belongs_to:
```ruby
VALID_AUTOMATIC_INVERSE_MACROS =
    [:has_many, :has_one, :belongs_to]

**Comment by intrip** [comment]
Leaving this to the core team, I'm not even totally sure if that method is part of the [public_api](https://guides.rubyonrails.org/v5.2/api_documentation_guidelines.html#method-visibility) or not 🤷‍♂️

**Comment by intrip** [comment]
Still relevant
