### ISSUE TITLE
idle_timeout behavior and documentation

### ISSUE THREAD

**Issue by jjb** [rails/rails#41196]
My testing seems to suggest that the idle_timeout configuration is only relevant if the reaper is running. The [documentation](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html#class-ActiveRecord::ConnectionAdapters::ConnectionPool-label-Options) does not mention this.

The only place I could find `.flush` invoked is in the reaper, so this seems to match my observations: https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L337

I'm not sure if this is expected behavior and the documentation should be updated, or if the behavior should be changed.

It might be good to have another couple sentences about the reaper as well - pros and cons of turning it on. All one can find about it is a few blog posts about when it was turned off by default several years go.

Let me know any questions/if there's anything I can do!

The idle flusher was introduced [here](https://github.com/rails/rails/commit/9027fafff6da932e6e64ddb828665f4b01fc8902) by @matthewd

### without reaper

1. Set up a loop to log `ActiveRecord::Base.connection_pool.connections.map &:seconds_idle`
1. set `idle_timeout: 5` in database.yml
1. `ab -n 100000 -c 100 http://127.0.0.1:3000/`
2. observe in logs that idle connections stay alive far past 5 seconds (until around 40-45 seconds in my environment - not sure what is happening there, maybe postgres closes them?

### with reaper

1. same as above
2. same as above, and also `reaping_frequency: 5`
3. same as above
4. observe in logs that connections do not survive past 5 second

**Rails version**:

5.2.4.4

**Ruby version**:

2.7.1

**Comment by eugeneius** [comment]
Rails 5.2 is no longer supported outside of security fixes. Can you reproduce this behaviour on 6.1 or main?

**Comment by jjb** [comment]
Alas, I won't have time to do that - looking at the code in main, and 6.0 and 6.1 release notes (no mention of behavior changing there) I'm guessing it's still the case

@matthewd if you have a minute, maybe you could chime in about what intended behavior is?

**Comment by jjb** [comment]
for anyone stumbling upon this years later - Looks like the reaper is on by default in 7.2.1  https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool/Reaper.html

"Configure the frequency by setting reaping_frequency in your database YAML file (default 60 seconds"

i think this wasn't the case when i made this issue? in my tests described above i was using a bare-bones rails app (i think?) and setting reaping_frequency 🤷

**Comment by jjb** [comment]
https://github.com/rails/rails/pull/54175
