### ISSUE TITLE
ActiveRecord::Persistence#becomes doesn't handle virtual attributes

### ISSUE THREAD

**Issue by SampsonCrowley** [rails/rails#41195]
### Steps to reproduce

Add a virtual attribute to an inherited model, and use `#becomes` from either the parent to the child or the child to the parent

### Expected behavior

Virtual Attributes should be correctly initialized and there shouldn't be any errors, since they have nothing to do with the database

### Actual behavior

an `ActiveRecord::UnknownAttributeError` is thrown if you try to go either direction

### System configuration
**Rails version**: 6.0.3.4 (but I was the one who submitted the last patch for becomes to correctly move items back into the initialize block like they're supposed to be, so I have the current monkey patch for the latest version, it happens on all versions at least from 6+, tested up to 6.1.1)

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux] (but also really not a cause here)

**Comment by intrip** [comment]
not stale
