### ISSUE TITLE
current_page? breaks with Ruby 3 keyword arguments

### ISSUE THREAD

**Issue by sergiopantoja** [rails/rails#41198]
Passing keyword arguments ([as shown in the docs](https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-current_page-3F)), throws `ArgumentError (wrong number of arguments (given 0, expected 1))`.

Passing a string or hash like `current_page?({action: 'index'})` still works, which is why the Rails test suite is currently green for these tests: [url_helper_test](https://github.com/rails/rails/blob/9d8ff323729f8f8fe09f14f4f45586f2d6340a70/actionview/test/template/url_helper_test.rb#L559)

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
  include ActionView::Helpers::UrlHelper

  def index
    current_page?(action: 'index')
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior
Page should render and test should pass.

### Actual behavior
`ArgumentError` is thrown.

```ruby
# Running:

I, [2021-01-21T09:40:34.218885 #88388]  INFO -- : Started GET "/" for 127.0.0.1 at 2021-01-21 09:40:34 -0600
F, [2021-01-21T09:40:34.236578 #88388] FATAL -- :
ArgumentError (wrong number of arguments (given 0, expected 1)):
```

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 3.0.0

**Comment by intrip** [comment]
@kamipo I've created a #41206 to fix this issue, could you please take a look?
