### ISSUE TITLE
Run rails database tasks on just development environment

### ISSUE THREAD

**Issue by duane-at-cosell** [rails/rails#41202]
### Steps to reproduce

Use virtually any task in the `db:` namespace.

### Expected behavior

The tasks operate on a single environment, either whatever is specified in `RAILS_ENV`, or `development` by default.

### Actual behavior

Database tasks operate on both development and test. This makes operating on just the development environment impossible. If I am connected to the test database, I cannot drop the development database using the rails rake tasks. This is unexpected, inconsistent, and undesirable behavior.

PLEASE add a `NO_TEST` variable or something akin to that to allow opt-out of this decision short of forking rails.

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 3.0.0p0

**Comment by duane-at-cosell** [comment]
I see this is a known issue; I'm fine to just register another pain point. Closing.

**Comment by eileencodes** [comment]
You can do this in Rails 6.1 with `SKIP_TEST_DATABASE`. See https://github.com/rails/rails/pull/39027

**Comment by duane-at-cosell** [comment]
@eileencodes I appreciate the heads up, thank you!
