### ISSUE TITLE
Action Text with Sprockets

### ISSUE THREAD

**Issue by gobijan** [rails/rails#41221]
The turbo-rails gem works with sprockets or webpacker.

@dhh mentioned in tweets and interviews that he is considering Rails 7 to not offer webpacker by default. 

Tailwind-rails gem is another step into webpacker free plain old rails.

Therefore it makes sense in my opinion to also change actiontexts install routine to support sprockets in case webpacker is not installed.

Is this worth investigating?
Would pull requests be welcome?

Cheers Bijan

**Comment by Lomig** [comment]
I don't know what will be the official way, but I did it this way:

## Prerequisites
* hotwire-rails

## CSS
* Copy the CSS file in your asset pipeline (https://github.com/basecamp/trix/tree/main/dist)

## JS Libraries
* In `app/assets/javascripts/libraries` create these two files
* Updated content may be found on https://www.skypack.dev

```javascript
// app/assets/javascripts/libraries/actiontext@6.1.4.js
export * from 'https://cdn.skypack.dev/pin/@rails/actiontext@v6.1.4-znF92tREya92yxvegJvq/mode=imports/optimized/@rails/actiontext.js';
export { default } from 'https://cdn.skypack.dev/pin/@rails/actiontext@v6.1.4-znF92tREya92yxvegJvq/mode=imports,min/optimized/@rails/actiontext.js';
```

```javascript
// app/assets/javascripts/libraries/trix@1.3.1.js
export * from 'https://cdn.skypack.dev/pin/trix@v1.3.1-EGGvto9zyvcAYsikgQxN/mode=imports/optimized/trix.js';
export { default } from 'https://cdn.skypack.dev/pin/trix@v1.3.1-EGGvto9zyvcAYsikgQxN/mode=imports,min/optimized/trix.js';
```

## Import through Stimulus
* In `app/assets/javascripts/controllers` create this file

```javascript
//app/assets/javascripts/controllers/trix_controller.js
import { Controller } from "stimulus"

export default class extends Controller {
  connect() {
    import("actiontext").catch(err => null)
    import("trix").catch(err => null)
  }
}
```

* On pages where trix/action_text should be loaded, add a `data-controller="trix"` to the relevant div
* And voilà !

**Comment by u2000** [comment]
A sprockets installer would be very welcome.

**Comment by zzak** [comment]
@u2000 @Lomig Since we do not accept feature requests in issues, would you be willing to try a PR for this? :bow:
