### ISSUE TITLE
Bug - Failed to call custom method on validation repeatly

### ISSUE THREAD

**Issue by helmiItsavirus** [rails/rails#41231]
### Steps to reproduce
**Call multiple times custom method on validation on my model e.g**
```
Class User 
    validate :check_username on: :create_user
    validate :check_username on: :update_user

  private
  def check_username
  end
end
```

### Expected behavior
We can call multiple times custom method on the validation separate by context e.g on: :create_user or on: :update_user

### Actual behavior
The validation only works on one context e.g on: :create_user and the second validation on: :update_user doesn't work.

If we want the validation to work, we should change one of validation to **before_validation** e.g

## Only one validation works
```
Class User 
    validate :check_username on: :create_user
    validate :check_username on: :update_user

  private
  def check_username
  end
end
```

## All validation works
```
Class User 
    validate :check_username on: :create_user
    before_validation :check_username on: :update_user

  private
  def check_username
  end
end
```

### System configuration
**Rails version**:
6.0.3.2

**Ruby version**:
2.6.6

**Comment by louim** [comment]
Hey @helmiItsavirus 

Callbacks to the same method should be registered at the same time, eg:
```
validate :check_username on: [:create_user, :update_user]
```
Else, the last definition will overwrite the first, making only one of them work.

**Comment by composerinteralia** [comment]
I think this is roughly the same as other callback issues like https://github.com/rails/rails/issues/19590 and https://github.com/rails/rails/issues/41169. Overwriting is the expected behavior here, and `validate :check_username on: [:create_user, :update_user]` sounds like a reasonable solution.

I wonder if there is some documentation we can add to make this clearer to folks.

**Comment by eileencodes** [comment]
Is there an incorrect blog post out there? This is the second time in a month we've gotten a report like this and I'm pretty sure this is well documented behavior.

**Comment by helmiItsavirus** [comment]
Thanks, @composerinteralia, I will close the issue and I will try to figure out the issue on like [#19590](https://github.com/rails/rails/issues/19590) and [#41169](https://github.com/rails/rails/issues/41169)
