### ISSUE TITLE
Joining same table multiple times with where fails in ActiveRecord 6.1

### ISSUE THREAD

**Issue by remofritzsche** [rails/rails#41239]
### Steps to reproduce

The following script is able to reproduce the (alleged) bug. To run it:

* Save it, i.e. as `test.rb`
* Change the MySQL database credentials if necessary (you need a MySQL server)
* Run the script:
  * `ruby test.rb 6.0.3.4` => Works
  * `ruby test.rb 6.1.1` => Broken

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", ARGV.first || "6.1.1"
  gem "mysql2", "0.5.3"
  gem "colorize"
  gem "pry"
end

require "active_record"
require "colorize"
require "minitest/autorun"
require "logger"

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "mysql2", database: 'test', host: 'db', user: 'root', password: '')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :leafs, force: true do |t|
    t.integer :node_id
  end

  create_table :nodes, force: true do |t|
    t.integer :parent_id
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Leaf < ApplicationRecord
  belongs_to :node
end

class Node < ApplicationRecord
  has_one :leaf
  belongs_to :parent, class_name: 'Node', optional: true
  has_many :children, class_name: 'Node', foreign_key: :parent_id, dependent: :nullify, inverse_of: :parent
end

class BugTest < Minitest::Test
  # This works, as it does not contain a where statement
  def test_join_without_where
    assert_equal(
      <<~SQL.strip,
        SELECT `leafs`.* FROM `leafs` INNER JOIN `nodes` ON `nodes`.`id` = `leafs`.`node_id` INNER JOIN `nodes` `parents_nodes` ON `parents_nodes`.`id` = `nodes`.`parent_id`
      SQL
      Leaf.joins(node: :parent).to_sql
    )
  end

  # This works in ActiveRecord 6.0.3.4 but is broken in 6.1.1
  def test_join_with_where
    assert_equal(
      <<~SQL.strip,
        SELECT `leafs`.* FROM `leafs` INNER JOIN `nodes` ON `nodes`.`id` = `leafs`.`node_id` INNER JOIN `nodes` `parents_nodes` ON `parents_nodes`.`id` = `nodes`.`parent_id` WHERE `parents_nodes`.`parent_id` = 123
      SQL
      Leaf.joins(node: :parent).where(node: { parents_nodes: { parent_id: 123 } }).to_sql
    )
  end

  # The following works in ActiveRecord 6.0.3.4 but is broken in 6.1.1
  def test_join_with_where_actual_execution
    Leaf.joins(node: :parent).where(node: { parents_nodes: { parent_id: 123 } }).to_a
  end
end
```

### Expected behavior

We would expect ActiveRecord 6.1.1 to produce the same or a similar query to Rails 6.0.3.4 where the second join to the `nodes` table would alias the table name so `nodes` is not joined twice.

```ruby
Leaf.joins(node: :parent).to_sql
```

```sql
SELECT `leafs`.* FROM `leafs` INNER JOIN `nodes` ON `nodes`.`id` = `leafs`.`node_id` INNER JOIN `nodes` `parents_nodes` ON `parents_nodes`.`id` = `nodes`.`parent_id`
```

### Actual behavior

ActiveRecord 6.1.1, in contrast to 6.0.3.4, joins the `nodes` table two times without aliasing it. The query does not work for this reason.

```ruby
Leaf.joins(node: :parent).where(node: { parents_nodes: { parent_id: 123 } }).to_sql
```

```sql
SELECT `leafs`.* FROM `leafs ` INNER JOIN `nodes` node ON node.`id` = `leafs`.`node_id` INNER JOIN `nodes` ON `nodes`.`id` = node.`parent_id` WHERE `parents_nodes`.`parent_id` = 123
```

### System configuration

**Rails version**: 6.1.1

**Ruby version**: ruby-2.6.2-p47

**Comment by remofritzsche** [comment]
Quick update: A bisect shows that 999bf3d0977edc48a18e943f24669dfe4bbdda54 did break my test.

**Comment by kamipo** [comment]
In Rails 6.0, `Leaf.joins(node: :parent).where(noop: { noop: { parents_nodes: { parent_id: 123 } } })` worked, but multi-level hash condition is quite useless. 

In Rails 6.1, top-level hash key would be used as join alias if possible by #40106.

Can you avoid multi-level hash condition, just do `Leaf.joins(node: :parent).where(parents_nodes: { parent_id: 123 })`?

**Comment by remofritzsche** [comment]
Thanks for your answer, your suggestion indeed works. But I think the status quo is not optimal, as :

* Multi-level hash conditions are generally supported (there is no exception telling you otherwise)
* The upgrade guide does not mention anything, and this might break a lot of queries in an application

I would therefore suggest one of two ways going forward:

1. Leave the implementation as-is, but mentioning it in the upgrade guide and possibly also make sure that a custom exception is raised if one attempts to supply a multi-level hash condition.
2. Fix the "issue". I found that changing one single line (see below) would do the trick. However, it breaks the tests mentioned below, so this may not be the solution.

Please let me know what you think. Many thanks for your time.

------

```ruby
# activerecord/lib/active_record/associations/join_dependency.rb:198

# Change from:
table_name = @references[reflection.name.to_sym]&.to_s

# To:
table_name = @references[reflection.table_name.to_sym]
```

This breaks the following AR tests:

* `EagerAssociationTest#test_attribute_alias_in_where_references_association_name`
* `EagerAssociationTest#test_type_cast_in_where_references_association_name`

**Comment by Dantemss** [comment]
I would also love to see official support for joining a table multiple times in 1 query. A common use case is when you need information from your users table multiple times from different users in different roles.

@remofritzsche unfortunately your proposed fix fails in the following case (Foo belongs_to Bar):

```
irb(main):001:0> Foo.joins(:bar).where(bar: {id: 1})
   (0.2ms)  SELECT sqlite_version(*)
  Foo Load (0.2ms)  SELECT "foos".* FROM "foos" INNER JOIN "bars" ON "bars"."id" = "foos"."bar_id" WHERE "bar"."id" = ? /* loading for inspect */ LIMIT ?  [["id", 1], ["LIMIT", 11]]
Traceback (most recent call last):
ActiveRecord::StatementInvalid (SQLite3::SQLException: no such column: bar.id)
```

Seems like it breaks the table aliasing that was introduced in Rails 6.1. Without the patch, "bars" would be aliased to "bar", which is what the `WHERE` expects.
