### ISSUE TITLE
ActionMailer does not timeout network connections by default

### ISSUE THREAD

**Issue by mperham** [rails/rails#41244]
I have a Sidekiq customer complaining of a lot of "stuck" threads. He sends a lot of email so I suspected misbehaving SMTP servers.

The `mail` gem has support for timeouts here but they default to `nil`:

https://github.com/mikel/mail/blob/7b3e100f42f2d7738c3af7bf1909777568270b67/lib/mail/network/delivery_methods/smtp.rb#L91

Rails does not appear to set them by default:

https://github.com/rails/rails/blob/a0908477cfe2c52ffbb1a0a18a064b6dd7c255a2/actionmailer/lib/action_mailer/delivery_methods.rb#L20-L27

nor does it appear to document how to set timeouts in the SMTP configuration section:

https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration

Would a read/open timeout of 5 seconds be reasonable to use as a default going forward? Could we update the ActionMailer guide for 6.1 so people know how to configure the timeouts?

**Comment by rafaelfranca** [comment]
> Would a read/open timeout of 5 seconds be reasonable to use as a default going forward?

Yes

> Could we update the ActionMailer guide for 6.1 so people know how to configure the timeouts?

Yes

I think we should do both.

I marked the issue with the "Good first issue", but if you want to do or get your customer involved with contributing to Rails, please go ahead.

**Comment by andrehjr** [comment]
Unless @mperham wants to do it. I can make that PR 🙌

**Comment by mperham** [comment]
Be my guest. 👍
