### ISSUE TITLE
`ActiveModel::Dirty#changed?` is `true` for Newly Instantiated STI Models

### ISSUE THREAD

**Issue by sshaw** [rails/rails#41243]
### Steps to reproduce

```rb
ActiveRecord::Schema.define(version: 4) do
  create_table "children", force: :cascade do |t|
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "parents", force: :cascade do |t|
    t.string "type"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end
end

class Parent < ApplicationRecord
end

class Child < Parent
end
```

### Expected behavior

`Child.new.changed?` returns `false`, changes to `inheritance_column` are ignored (though in the case of an _update_ to this column, what the proper behavior is is debatable). 

### Actual behavior

`Child.new.changed?` returns `true`

This is because the STI column is set to the subclass name. This is an implementation detail of how a class hierarchy is/will be persisted and should not be counted as a change to the instance. 

`Child.new.changes` returns `{"type"=>[nil, "Child"]}`

This was mentioned back in the Lighthouse days via #1022 but there is no (visible) resolution. 

### System configuration
**Rails version**: 6.0.3.4

**Comment by fatkodima** [comment]
This behavior is explicitly stated in the documentation - https://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html

> Be aware that because the type column is an attribute on the record every new subclass will instantly be marked as dirty and the type column will be included in the list of changed attributes on the record. This is different from non Single Table Inheritance(STI) classes.

So not sure if this is something that needs to be fixed and this will be a breaking change.
