### ISSUE TITLE
Confusing documentation of FormHelper#form_with and `form_with_generates_remote_forms` config

### ISSUE THREAD

**Issue by RobinDaugherty** [rails/rails#41245]
With Rails 6.1, a configuration option `action_view.form_with_generates_remote_forms` was changed to default to `false`. The [documentation for the `form_with` method](https://github.com/rails/rails/blob/a0908477cfe2c52ffbb1a0a18a064b6dd7c255a2/actionview/lib/action_view/helpers/form_helper.rb#L607-L610) does not make it clear whether the default behavior is to be "remote" or "local".

This is confusing because:
- The configuration option is named "form_with_generates_remote_forms"
- "generates" seems to indicate that it has something to do with the rails generator
- `#form_with` doesn't take a "remote" argument

The documentation is inconsistent with its use of the terms "remote" and "local" and understanding it requires processing at least one double-negative.

It seems that the default behavior changed from "remote true" to "remote false" which means that with this config change, the implicit argument to `form_with` changed from `local: false` to `local: true`. [Here's the implementation](https://github.com/rails/rails/blob/a0908477cfe2c52ffbb1a0a18a064b6dd7c255a2/actionview/lib/action_view/helpers/form_helper.rb#L1532).

But the documentation and argument name don't make this clear.

To compound the confusion, #39711 seems to indicate that the default should change from `local: true` to `local: false` while the PR #40708 seems to indicate the opposite.

It seems like the project might intend to rename the argument from `local` to `remote` in order to clean up the inconsistent naming (since `form_for` takes a `remote` argument instead).

I can open a PR to improve the documentation if we can agree on the intent.

### Steps to reproduce

1. Using Rails 6.0, create a new application.
2. In a view template, use `form_with` to create a form
3. Upgrade the application to Rails 6.1 by updating the gem, `rails app:update`, and adopt the 6.1 configuration defaults in `config/application.rb`.

### Expected behavior
Unclear.

### Actual behavior
Unclear.

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 2.7.2

**Comment by rafaelfranca** [comment]
The documentation says: `By default form submits via typical HTTP requests.`. Which mean that is local.

After that is says: `Enable remote and unobtrusive XHRs submits with <tt>local: false</tt>.` which tells that to enable remove you need to set `local: false`

What would make that message more clear? If you have ideas, please open a PR, but the intent is what `form_with` generates forms without `data-remote`.

**Comment by RobinDaugherty** [comment]
In #41276 I propose changes to this documentation. Some goals are laid out there.

**Comment by thebluber** [comment]
I'm really wondering why `form_with` can't provide the same name for the `remote` option like all the other helpers such as `form_for`, `link_to` and `button_to`. This is just utterly confusing.
