### ISSUE TITLE
Does Rails 6 bulk insert support strong parameters?

### ISSUE THREAD

**Issue by davideluque** [rails/rails#41246]
I am implementing batch/bulk insert in a rails application, in API-only mode. The data that I am inserting comes from an array of hashes, where each hash is a record of the "report" model.

### Steps to reproduce

**Controller**
```ruby
class ReportsController < ApplicationController
  def create
    result = Report.insert_all(reports_params)
  end

  private
  def reports_params
    params.permit(_json: [:customer_id, :score_one, :score_two])
  end
end
```

**JSON Test Data**
```json
[
    {
        "customer_id": "aaaa",
        "score_one": "50",
        "score_two": "20"
    },
    {
        "customer_id": "bbbb",
        "score_one": "11",
        "score_two": "47"
    }
]
```

### Expected behavior
The two records are inserted into the database.

### Actual behavior
It seems that strong parameters work by permitting the right parameters but the `insert_all` method does not know what to do with those objects.

```bash
Processing by ReportsController#create as */*
  Parameters: {"_json"=>[{"customer_id"=>"aaaa", "score_one"=>"50", "score_two"=>"20"}, {"customer_id"=>"bbbb", "score_one"=>"11", "score_two"=>"47"}], "report"=>{}}
Unpermitted parameter: :report
{"_json"=>[<ActionController::Parameters {"customer_id"=>"aaaa", "score_one"=>"50", "score_two"=>"20"} permitted: true>, <ActionController::Parameters {"customer_id"=>"bbbb", "score_one"=>"11", "score_two"=>"47"} permitted: true>]}
Unpermitted parameter: :report
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms | Allocations: 1274)
  
NoMethodError (undefined method `first' for #<ActionController::Parameters:0x00007fecd0552318>):
```

Then, I came up with a solution that _partially worked_. After changing the create method to:

```ruby
  def create
    result = Report.insert_all(reports_params[:_json])
  end
```

I get 

```bash
Processing by ReportsController#create as */*
  Parameters: {"_json"=>[{"customer_id"=>"aaaa", "score_one"=>"50", "score_two"=>"20"}, {"customer_id"=>"bbbb", "score_one"=>"11", "score_two"=>"47"}], "report"=>{}}
Unpermitted parameter: :report

  Report Bulk Insert (0.4ms)  INSERT INTO "reports" ("customer_id","score_one","score_two") VALUES ('aaaa', 50, 20), ('bbbb', 11, 47) ON CONFLICT  DO NOTHING
  ↳ app/controllers/v1/reports_controller.rb:15:in `create'
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.4ms | Allocations: 875)
  
ActiveRecord::NotNullViolation (SQLite3::ConstraintException: NOT NULL constraint failed: reports.created_at):
```

I am not sure why ActiveRecord is not auto-generating the created_at, updated_at. 

### System configuration
**Rails version**:
Rails 6.0.3.4

**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

**Comment by rafaelfranca** [comment]
Thank you for the issue.

Think about `insert_all` as a low level operation. Active Record will not only try to use the attributes that are defined to the models. It is also not going to automatically generate the timestamps. If you are using `insert_all` you need to only pass attributes that exists and you need to deal with all values that are not null and have no default set in the database.

**Comment by louim** [comment]
About the absence of auto-generation for created_at, updated_at, this is how it works currently. There is a lengthy discussion about why in this issue and the related PR: https://github.com/rails/rails/issues/35493
