### ISSUE TITLE
Response of ActiveRecord #pluck method changes (in specific case) between 6.0 and 6.1

### ISSUE THREAD

**Issue by egiurleo** [rails/rails#41247]
Hello!

I noticed that the response of the the `ActiveRecord` [pluck](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/relation/calculations.rb#L183) method has changed between Rails 6.0 and 6.1 when trying to aggregate on an empty `Relation` or `AssociationRelation` object.

### Steps to reproduce
I have an example Rails app with failing tests set up in a repository. My tests pass on Rails 6.0 but fail on Rails 6.1.0 and 6.1.1.

[https://github.com/egiurleo/rails-61-test-aggregated-pluck/blob/main/spec/aggregated_pluck_spec.rb](https://github.com/egiurleo/rails-61-test-aggregated-pluck/blob/main/spec/aggregated_pluck_spec.rb)

You can set up this scenario in your own app as follows:
- Create one model (e.g. my `Person` model)
- Create an empty `Relation` object by performing a query that will generate an empty result (e.g. `Person.where(id: [])`)
- Use `pluck` to aggregate on that Relation (e.g. `Person.where(id: []).pluck("count(id)")`)

The same thing happens with empty `AssociationRelation` objects (e.g. `person.pets.where(id: []).pluck(...)`)

### Expected behavior
With Rails 6.0, using the pluck method in this way will return `[0]` when you pass `count(id)`, or it will return `[nil]` (for example if you try to perform an average on an integer field).

### Actual behavior
With Rails 6.1.0 and 6.1.1, pluck will return an empty array.

For some context, we use this method in our app to perform multiple aggregations on different columns (e.g. `people.pluck('count(id), avg(age)')`, which is why I noticed this change.

### System configuration
**Rails version**: Rails 6.1.1
**Ruby version**: Ruby 2.7.2

Thank you very much for your time :)

**Comment by rafaelfranca** [comment]
Thank yu for the issue. This is by design. See https://github.com/rails/rails/commit/0d0c30e534af7f80ec8b18eb946aaa613ca30444 and https://github.com/rails/rails/pull/37266
