### ISSUE TITLE
Scoped and namespaced routes differ when nested

### ISSUE THREAD

**Issue by orhantoy** [rails/rails#41249]
### Steps to reproduce

I thought `scope` was similar to `namespace` but here is a script that IMO shows an unexpected difference:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "6.1"
end

require "action_controller/railtie"
require "rails/commands/routes/routes_command"
require "rake"

class TestRailsApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    resources :users, only: :index do
      scope path: "x", as: :x do
        resources :friends, only: :index
      end

      namespace :y do
        resources :friends, only: :index
      end
    end
  end
end

Rails::Command::RoutesCommand.new.perform
```

Feel free to disregard if this is as intended. Perhaps the docs could be updated to explain the difference.

### Expected behavior
```
        Prefix Verb URI Pattern                         Controller#Action
x_user_friends GET  /x/users/:user_id/friends(.:format) friends#index
user_y_friends GET  /users/:user_id/y/friends(.:format) y/friends#index
         users GET  /users(.:format)                    users#index
```

### Actual behavior
```
        Prefix Verb URI Pattern                         Controller#Action
x_user_friends GET  /users/:user_id/x/friends(.:format) friends#index
user_y_friends GET  /users/:user_id/y/friends(.:format) y/friends#index
         users GET  /users(.:format)                    users#index
```

### System configuration
**Rails version**: 6.1 (but the behavior appears to be the same all the way back to Rails 4, not sure about before that)

**Ruby version**: 2.5.8

**Comment by rafaelfranca** [comment]
Why did you thought they were similar? I mean `namespace` uses `scope` in its implementation, and `scope` with the same options than `namespace` uses by default would give the same result, but other than that the methods do different things.

**Comment by orhantoy** [comment]
I can't get `scope` to behave the same way as `namespace` in the example I gave. I think the use of `path_scope` in `namespace` is what makes the difference, but that's a private API.

As to why I thought they were similar: `namespace` and `scope` are described in similar ways, so I assumed that they worked similarly, which they almost do, except when nested under `resource`.

**Comment by orhantoy** [comment]
I just tried this

```diff
diff --git a/actionpack/lib/action_dispatch/routing/mapper.rb b/actionpack/lib/action_dispatch/routing/mapper.rb
index 07bc2cc42b..5ce30bdb05 100644
--- a/actionpack/lib/action_dispatch/routing/mapper.rb
+++ b/actionpack/lib/action_dispatch/routing/mapper.rb
@@ -1597,6 +1597,15 @@ def namespace(path, options = {})
           end
         end
 
+        # See ActionDispatch::Routing::Mapper::Scoping#scope.
+        def scope(*)
+          if resource_scope?
+            nested { super }
+          else
+            super
+          end
+        end
+
         def shallow
           @scope = @scope.new(shallow: true)
           yield
```

and now I'm getting the expected result:

```
        Prefix Verb URI Pattern                         Controller#Action
user_x_friends GET  /users/:user_id/x/friends(.:format) friends#index
user_y_friends GET  /users/:user_id/y/friends(.:format) y/friends#index
         users GET  /users(.:format)                    users#index
```

I can submit as PR if you agree with the change, but then again, it is a breaking change, so I'm not sure 🤷

**Comment by rafaelfranca** [comment]
Ahhh, now I see what you mean. Yeah, it is because `namespace` is overridden on inside the resources DSL. I think that changes make sense, but this will probably break some application. We need to think on how people can get the previous behavior and maybe suggest which changes need to be done using a deprecation?
