### ISSUE TITLE
Non-descriptive error message in `render file: ...`

### ISSUE THREAD

**Issue by JelF** [rails/rails#41265]
### Steps to reproduce

```ruby
# /tmp/nothing is a non-existing file
render file: "/tmp/nothing"
```

### Expected behavior

Error with message "file /tmp/nothing does not exist"

### Actual behavior

Error with message "`render file:` should be given the absolute path to a file. '#{options[:file]}' was given instead"

Please note that this message is not correct, /tmp/nothing is an absolute path to a file, even when file does not exist

### System configuration
**Rails version**: 6.1.0
**Ruby version**: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

**Comment by tywhang** [comment]
I've submitted a pull request to fix this: https://github.com/rails/rails/pull/41283

**Comment by tywhang** [comment]
Hello this is still an issue, please refer to https://github.com/rails/rails/pull/41283 for a fix.
