### ISSUE TITLE
initialized object create an empty record in views

### ISSUE THREAD

**Issue by dashingspidy** [rails/rails#41274]
### Steps to reproduce
Try to initialize a new object using one to many relationship model like : `@todo_list.todo_items.build`

`todo_list.rb`
```ruby
class TodoList < ApplicationRecord
  has_many :todo_items, dependent: :destroy
end
```
`todo_item.rb`
```ruby
class TodoItem < ApplicationRecord
  belongs_to :todo_list
end
```
`todo_items_controller.rb`
```ruby
class TodoItemsController < ApplicationController

  def index
    @todo_list = TodoList.find(params[:todo_list_id])
    @todo_items = @todo_list.todo_items
    @todo_item = @todo_list.todo_items.build
  end

  def create
    @todo_list = TodoList.find(params[:todo_list_id])
    @todo_item = @todo_list.todo_items.new(params.require(:todo_item).permit(:description, :complete_at))
    if @todo_item.save
      redirect_to todo_list_todo_items_path(@todo_list)
    end
  end
end
```
`todo_items/index.html.erb`
```ruby
  <div>
    <%= form_with(model: [@todo_list, @todo_item], local: true) do |f| %>
      <%= f.text_field :description %>
      <%= f.submit %>
    <% end %>
  </div>
    <ul>
    <% @todo_items.each do |todo_item| %>
      <li><%= todo_item.description %></li>
    <% end %>
    </ul>
```

### Expected behavior
should only return list of data from database

### Actual behavior
It creates an empty object. Also shows an extra` li `tag inside views like above example.

### System configuration
**Rails version**:
Rails 6.1.1
**Ruby version**:
ruby 3.0.0
ruby 2.7.2

**Comment by louim** [comment]
Hey!

This is the expected behavior since [this PR](https://github.com/rails/rails/pull/34533) because the object is added to the in-memory association. If you want the collection from the database, you can either call `reload` on the association `@todo_items = @todo_list.todo_items.reload` or you can build your object separately, eg: `TodoItem.new()`. You could also only display persisted object by doing:
```ruby
@todo_items = @todo_list.todo_items
@todo_item = @todo_list.todo_items.build
@todo_items = @todo_list.todo_items.select(&:persisted?)
```
