### ISSUE TITLE
wrong number of arguments (given 3, expected 1..2) on errors.add when given hash

### ISSUE THREAD

**Issue by rmehner** [rails/rails#41270]
### Steps to reproduce

Use errors.add in your model to add validation errors:

```rb
class User < ApplicationRecord
  def add_error
    errors.add(:name, :invalid, {})
  end
end

User.new.add_error
```

### Expected behavior

Not throwing an error (which is Rails 6.0 behaviour)

### Actual behavior

`wrong number of arguments (given 3, expected 1..2)` on Rails 6.1

This boils down to a changed method signature between 6 and 6.1

6.0: https://api.rubyonrails.org/v6.0.0/classes/ActiveModel/Errors.html#method-i-add
6.1: https://api.rubyonrails.org/v6.1.1/classes/ActiveModel/Errors.html#method-i-add

The change was introduced in a three years old commit: https://github.com/rails/rails/commit/d9011e39357300fe78720227af4c13b4bc4ac4dd (quite some archeology here 🦖 )

The fix for consumer side is rather easy:

```rb
errros.add(:name, invalid, **{})
```

Not sure what the Rails team can do here, but that breaking change definitely caught me by surprise on one project, since it's not mentioned at all in the [6.1 changelog for ActiveModel](https://github.com/rails/rails/blob/6-1-stable/activemodel/CHANGELOG.md). If nothing else, this issue post here should allow people to find if they run into it (which they will with current versions of kt-paperclip, since this is how I found the issue)

Thanks for reading and keep on the good work!

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 3.0.0

**Comment by vipulnsward** [comment]
Thank you for reporting, we can add change to improve https://github.com/rails/rails/blob/6-1-stable/activemodel/CHANGELOG.md if you are up for it.

**Comment by intrip** [comment]
This issue only appears in `ruby3` and is related to the changes of how `ruby3` handles keyword arguments, we probably have other places in the public API which are affected by a similar issue.
I don't know if it's worth documenting all of them, maybe we should consider to just add a note related to the Ruby upgrade incompatibilities instead.
WDYT?

**Comment by intrip** [comment]
@zzak WDYT? 
Shall we mention such info in the docs? If so have any hints on where we should put it? 🤔

**Comment by zzak** [comment]
@intrip I wonder if it doesn't make sense to split out [this kind of information](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#ruby-versions) into a more formal Ruby-specific guide for Rails developers 🤔

**Comment by intrip** [comment]
> @intrip I wonder if it doesn't make sense to split out [this kind of information](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#ruby-versions) into a more formal Ruby-specific guide for Rails developers 🤔

I like that idea!

docs is one of my weak spot 😞 so any guidance is very appreciated, maybe we can start by adding a sub section "ruby 3.0" which mentions all the ruby 3.0 incompatibilities?

In any case I think we also need to add a CL line in ActiveSupport for this.

**Comment by zzak** [comment]
@intrip I'm happy to start this and we can ping-pong pair to flesh out the details.

> In any case I think we also need to add a CL line in ActiveSupport for this.

What do you mean by CL line?

**Comment by intrip** [comment]
@zzak 
> @intrip I'm happy to start this and we can ping-pong pair to flesh out the details.

Sure I'll start then

> What do you mean by CL line?

I meant changelog (CL) but nevermind: after re-thinking doesn't look a great idea to put ruby compatibility changes there so let's start just with the docs for now.

**Comment by byroot** [comment]
I don't think there's much more Rails should do here. Closing.
