### ISSUE TITLE
`where` with comparison operators (`>`, `>=`, `<`, and `<=`) do not work 

### ISSUE THREAD

**Issue by gudata** [rails/rails#41271]
### Steps to reproduce
run in irb
```
StaticPage.where("created_at >=": 2.days.ago).to_sql
=> "SELECT \"static_pages\".* FROM \"static_pages\" WHERE \"static_pages\".\"created_at >=\" = '2021-01-26 20:41:26.987327'"
```
The same goes for numbers
```
StaticPage.where("id >": 2).to_sql
=> "SELECT \"static_pages\".* FROM \"static_pages\" WHERE \"static_pages\".\"id >\" = 2"
```

### Expected behaviour
I expect to see correctly formed SQL expression. 
```"static_pages"."created_at" >= '2021-01-26 20:41:26.987327'"```

### Actual behaviour
Instead, the comparing operator is merged into the field name.
```"static_pages"."created_at >=" = '2021-01-26 20:41:26.987327'"```

### System configuration
6.1.1
6.1.0

**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

ref  #39613

**Comment by rafaelfranca** [comment]
Yes. That doesn't work. #39613 was reverted.
