### ISSUE TITLE
Getting "ArgumentError (unknown keyword: ..." on any model load after upgrading to rails 6.1.0

### ISSUE THREAD

**Issue by martinlevesque** [rails/rails#41286]
### Steps to reproduce

Hey, after I upgraded the rails version from 6.0.3 to 6.1.0 I started getting the following error when I try to load any model, illustrated via the console (same error happening in any environment):

```
$ rails c
Resolving dependencies...
Running via Spring preloader in process 332794
Loading development environment (Rails 6.1.0)
2.7.1 :001 > User.last
  User Load (0.5ms)  SELECT `users`.* FROM `users` ORDER BY `users`.`id` DESC LIMIT 1
Traceback (most recent call last):
        1: from (irb):1
ArgumentError (unknown keyword: :owner)
```

The source code of my application is available here https://github.com/openode-io/openode-api/tree/upgrade-packages-jan-31
and failing test suite is here https://github.com/openode-io/openode-api/actions/runs/526123200

### Expected behavior

Should load the model with no error

### System configuration
**Rails version**:

6.1.0

**Ruby version**:

2.7.1

###

Any idea how I should debug to find what the issue might be? 

Note that I get the error whenever the row exists. When no row exists with the condition, no error is thrown and it returns an empty list correctly.

Thanks

**Comment by eileencodes** [comment]
This isn't a Rails issue, it very likely is an issue with one of your gems - andand looks like a good place to start. We've fixed all the kwarg warnings in Rails and standard models shouldn't be throwing any warnings. If you can't reproduce this in a new Rails application without your extra dependencies then it's not a Rails bug. Good luck with the upgrade!

**Comment by martinlevesque** [comment]
@eileencodes thanks for the feedback, will deep debug it!

**Comment by martinlevesque** [comment]
As a follow-up, the issue was in my case was with having the gem safe_attributes ( https://github.com/bjones/safe_attributes ) with rails 6.1.0

Fixed it by removing safe_attributes
