### ISSUE TITLE
PG::ProtocolViolation:  ERROR: bind message supplies 0 parameters, but prepared statement "" requires 2

### ISSUE THREAD

**Issue by CodingAnarchy** [rails/rails#41299]
### Steps to reproduce

```ruby
binds = [
        ActiveRecord::Relation::QueryAttribute.new(nil, Foo.reset_sequence_name, ActiveRecord::Type::String.new),
        ActiveRecord::Relation::QueryAttribute.new(nil, foos.count, ActiveRecord::Type::Integer.new)
      ]
      query = "SELECT nextval($1::regclass) AS foo_id FROM generate_series(1, $2)"
      new_ids = ApplicationRecord.connection.exec_query(query, 'SQL', binds).map {|row| row['foo_id']}
```

### Expected behavior

```ruby
binds = [
    ActiveRecord::Relation::QueryAttribute.new(nil, "foos_id_seq", ActiveRecord::Type::String.new),
    ActiveRecord::Relation::QueryAttribute.new(nil, 5, ActiveRecord::Type::Integer.new)
]
ApplicationRecord.connection.exec_query("SELECT nextval($1::regclass) AS version_id FROM generate_series(1, $2)", 'SQL', binds).map {|row| row['version_id']}
=> [2050719, 2050720, 2050721, 2050722, 2050723]
```

### Actual behavior

When prepared statements are on, this works as expected. When they are turned off, this blows up on a Postgresql database with `PG::ProtocolViolation:  ERROR: bind message supplies 0 parameters, but prepared statement "" requires 2`

### System configuration
**Rails version**: 5.2.4

**Ruby version**: 2.6.6

**Comment by rafaelfranca** [comment]
When prepared statements is disabled Rails don't pass binds anymore and don't call the method in the adapter that knows how to deal with prepared statements. Since you are writing the SQL snipped using bind placeholders by hand there is no way to make this work.

You need to make the bind substituting yourself.

**Comment by CodingAnarchy** [comment]
@rafaelfranca That doesn't appear to be the way that `exec_no_cache` works according to the Rails postgresql adapter as found here: https://github.com/rails/rails/blob/fc96b3bf3ede52e643a33692474b9e9198eddf65/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L671-L685

It clearly has a section for type-casting and passing in binds, despite not caching any prepared statement. Moreover, whether prepared statements are on or off globally, without explicitly setting `prepare: true`, Rails treats it the same by calling `exec_no_cache` - the only difference is that with it off permanently (rather than just for the single `exec_query` call) it drops the `binds` array for an empty one.

What specifically is preventing this substitution from working as expected here? In fact, if I monkey patch the PostgresqlAdapter like so:

```ruby
module ActiveRecord
  module ConnectionAdapters
    class PostgreSQLAdapter < AbstractAdapter
      private

      def execute_and_clear(sql, name, binds, prepare: false)
        if !prepare || without_prepared_statement?(binds)
          result = exec_no_cache(sql, name, binds)
        else
          result = exec_cache(sql, name, binds)
        end
        begin
          ret = yield result
        ensure
          result.clear
        end
        ret
      end
    end
  end
end
```

Then it actually works, even with prepared statements turned off globally!

```ruby
[2] pry(main)> require_relative 'lib/rails_extensions/active_record'
=> true
[3] pry(main)> binds = [
[3] pry(main)*   ActiveRecord::Relation::QueryAttribute.new(nil, PaperTrail::Version.reset_sequence_name, ActiveRecord::Type::String.new),
[3] pry(main)*   ActiveRecord::Relation::QueryAttribute.new(nil, versions.count, ActiveRecord::Type::Integer.new)
[3] pry(main)* ]
  [slave/1] (2.4ms)  SELECT COUNT(*) FROM "versions"
Query Trace:
      lib/rails_extensions/active_record.rb:8:in `execute_and_clear'
=> [#<ActiveRecord::Relation::QueryAttribute:0x00007f9b227f8e78 @name=nil, @original_attribute=nil, @type=#<ActiveModel::Type::String:0x00007f9b227f8ea0 @limit=nil, @precision=nil, @scale=nil>, @value_before_type_cast="master.versions_id_seq">,
 #<ActiveRecord::Relation::QueryAttribute:0x00007f9b1280d5b8 @name=nil, @original_attribute=nil, @type=#<ActiveModel::Type::Integer:0x00007f9b1280d630 @limit=nil, @precision=nil, @range=-2147483648...2147483648, @scale=nil>, @value_before_type_cast=6>]
[4] pry(main)> query = "SELECT nextval($1::regclass) AS version_id FROM generate_series(1, $2)"
=> "SELECT nextval($1::regclass) AS version_id FROM generate_series(1, $2)"
[5] pry(main)> new_ids = ApplicationRecord.connection.exec_query(query, 'SQL', binds).map {|row| row['version_id']}
  [master/1] SQL (5.8ms)  SELECT nextval($1::regclass) AS version_id FROM generate_series(1, $2)  [[nil, "master.versions_id_seq"], [nil, 6]]
Query Trace:
      lib/rails_extensions/active_record.rb:8:in `execute_and_clear'
=> [7, 8, 9, 10, 11, 12]
```

At this point, all I have not done is verified that other queries will still work as expected if I put this change into Rails itself. It is my opinion, though, that this is a change worth at least considering.
