### ISSUE TITLE
Custom column in before_create callback

### ISSUE THREAD

**Issue by Jaroost** [rails/rails#41294]
I don't know if it is really a bug. What I want to achieve is to fill a column before_object creation that contains the record id by year (call later number) with value like 21-001, 21-002, ... and for 22-001, ...
I also need that every record as his unique number.
### Steps to reproduce
with this model:
``` 
class GlobalRequest < ApplicationRecord
  before_create :create_number
  def create_number
    loop do
       set_number
       break if GlobalRequest.where(number: self.number).count<=0
    end
  end
  def set_number
    count=GlobalRequest.where("YEAR(created_at)=?", Date.today.year).count+1
    self.number = "#{Date.today.year % 100}-#{format("%03d", count)}"
  end
end
```

Now if I set a breakpoint on line ```break if GlobalRequest.where(number: self.number).count<=0``` and in the meantime I create a new record by hand in the database ```GlobalRequest.where(number: self.number).count``` will never see the record created by hand and I will end up with 2 same number in the database.

### Expected behavior
I there a way that we can check all record in the database in the before_create callback?

### Actual behavior
2 same number are in the database

### System configuration
**Rails version**:
6.1.1
**Ruby version**:
2.6.6

**Comment by intrip** [comment]
This looks like a concurrency issue, one way to deal with it is by using a [locking strategy](https://guides.rubyonrails.org/v3.1.0/active_record_querying.html#locking-records-for-update)

**Comment by kamipo** [comment]
The behavior in a transaction depends on transaction isolation level, use locking read if you want to read latest data.
