### ISSUE TITLE
Always got the warning: BigDecimal.new is deprecated; use BigDecimal() method instead when Rails Console Or Rspec

### ISSUE THREAD

**Issue by troniez** [rails/rails#41311]
### Steps to reproduce
I am using ruby version 2.6.6 and rails version 5.1.7. 

When run rails console, or rails server or rspec I always get the warning

`ruby-2.6.6/gems/activesupport-5.1.7/lib/active_support/number_helper/rounding_helper.rb:37: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.`

I did gg search, saw similar issues, but, my project not using gem mysql2 and the warning is showing on line 37 of activesupport-5.1.7

### System configuration
**Rails version**: 2.6.6

**Ruby version**: 5.1.7

Any guys met that warning before? I need removing that warning, the warning is showing multiple time when run rspec and rails server.

**Comment by eileencodes** [comment]
This is fixed in Rails 5.2+ with https://github.com/rails/rails/commit/67b9dbcc1cfce6694ab18c9629b233979506fbf0, Rails 5.1 is no longer supported. In order to get rid of this warning you'll need to upgrade to 5.2
