### ISSUE TITLE
Defining a `config` action on a controller causes a `SystemStackError`

### ISSUE THREAD

**Issue by chrisbloom7** [rails/rails#41323]
### Steps to reproduce

1. Generate a new Rails app ([example Rails 5.2 app](https://github.com/chrisbloom7/rails-5-config-action-error), [example Rails 6.1 app](https://github.com/chrisbloom7/rails-6-config-action-error))

    ```sh
    rails new config-demo --minimal
    ```

2. Create a new controller with two actions, with at least one named `config`, which render something simple

    ```ruby
    class MyConfigController < ApplicationController
      def notconfig
        render text: :notconfig
      end

      def config
        render text: :config
      end
    end
    ```

3. Create routes for the new controller and actions

    ```ruby
    get "/config, to: "my_config#config"
    get "/notconfig, to: "my_config#notconfig"
    ```

4. Create a new ActionDispatch test file that calls the new routes

    ```ruby
    require "test_helper"

    class MyConfigControllerTest < ActionDispatch::IntegrationTest
      def test_notconfig
        get "/notconfig"
        assert_equal 200, status
      end

      def test_config
        get "/config"
        assert_equal 200, status
      end
    end
    ```

5. Run the test

    ```sh
    bin/rails test
    ```

### Expected behavior

I would expect the routes to work as intended, or for Rails to generate an error about overriding the `config` method as an action.

### Actual behavior

Both new routes result in a `SystemStackError: stack level too deep` pointing to the `config` action definition. This is because `ActiveSupport` defines `ActiveSupport::Configurable#config` which is included into `ActionController::Base` by default, and the new `config` action overrides it. (We can confirm this by adding a byebug breakpoint in the `config` action and calling `method(:config).super_method` from the debugger console.) Our actions both call `render` which eventually will call `logger` which is a configurable attribute which calls `config` which then calls the new `config` action which calls `render` and so on. I initially spotted this when a team mate tried to create a `config` endpoint using https://github.com/github/chatops-controller, which essentially works the same way by defining a new action on the controller. 

### System configuration

**Rails version**: 5.2.4.4, 6.1.1, 6.2.0.alpha

**Ruby version**: 2.7.1, 2.6.6

_Updated to show that this affects other actions in the same controller and does not rely on calling the config action directly_

**Comment by chrisbloom7** [comment]
Note you don't even have to call the `config` endpoint to trigger this. You could define another action on the same controller and call that and you'd still end up with a `SystemStackError`

**Comment by rafaelfranca** [comment]
Thank you for the issue. Unfortunately I don't think there is something we can do about this. There are some methods that every controller have and if you call an action with the same name you will override it. `config` is one of them but you could override `process`, `controller_path`, `action_methods`, `send_action`, `process_action`, `logger` and that would also cause problems.

Do you have suggestions on what we can do?

**Comment by gmcgibbon** [comment]
We should add to the method definition hook on action controller base to raise a proper error here. I don't think there's much we can do about this otherwise.

A pattern you can follow in controller to get over this hurdle routes-wise is to create a new controller and route the `#index` action to plural resource names (eg. `get "/configs, to: "configs#index"`) and `#show` actions for singular resource names (eg. `get "/config, to: "configs#show"`). That way your actions are only ever the standard ones.

**Comment by chrisbloom7** [comment]
@rafaelfranca I don't have a specific fix in mind, but I like the idea proposed by @gmcgibbon - raising a proper error is preferable to a `SystemStackError` that doesn't point to a specific error (by its nature, and thus difficult to isolate to offending change, as in our original issue where adding a `chatop :config` suddenly caused other chatops to start failing in this way.)

**Comment by rafaelfranca** [comment]
We try to detect methods that can cause conflicts in Active Record instance and I'm not sure it is worth. People still override methods that they shouldn't without knowing and the complexity of that code in Rails only increase.

In my opinions this is just one of the pitfalls of using inheritance. If you define a method you can override a method of the superclass and this will cause unsuspected results.

Because we can't separate between overriding because people really want to give a new behavior to `config` and overriding by mistake because people wanted to define an action. There is no way to fix this specific issue unfortunately.

**Comment by gmcgibbon** [comment]
> There is no way to fix this specific issue unfortunately.

Is it unreasonable to assume any _public_ method defined on a controller subclass is intended to be an action? I believe `config`, for example, could be overridden and made protected because it is typically used to check class level config. While trying to fix this I found most internals could simply change access level on the subclass if an override was desired. 

I guess it really boils down to if we expect controller subclasses to respond to anything _other_ than action methods.

**Comment by shioyama** [comment]
> I guess it really boils down to if we expect controller subclasses to respond to anything other than action methods.

"expect controller subclasses to respond _publicly_ to anything other than action methods"

**Comment by rafaelfranca** [comment]
Changing the visibility would not change the consequences of overriding. `process` needs to be a public method and this is not an action.

**Comment by chrisbloom7** [comment]
I think it's worth noting that there's a difference in behavior with overriding `config` with something like 

```
# as a public or private method that's not wired as an action
def config
  # do some config-y things that returns some object that's not the actual configurable module object
end
```

and 

```
# as an action or method that is invoked from an action
def config
  # do some stuff
  render :foo # or something else that will eventually call config
end
```

In the former, you'll likely end up with a `NoMethodError` that points very clearly to the source of the problem, i.e. the new config method, with a stacktrace likely pointing to the call site and then you can kind of figure out that it's a supermethod problem. However, in the case of the latter the `SystemStackError` stacktrace is not helpful at all and you suddenly find yourself in a very deep, dark pit where things that used to work suddenly don't and there's no feedback as to why.

**Comment by chrisbloom7** [comment]
I agree that there's an inherent danger with overriding critical methods when using inheritance. This corner just felt particularly sharp to me for a number of reasons:

- That configurable model is included in ActionController as part of rails core, so it's not obvious that it exists
- The inherited `config` method is not a method one would normally reach for as part of typical work since it's intended to be used for meta programming configurable attributes
- `config` is a pretty common term in development as is the need to `config`-ure things
- When it is used as an action (or in the path of an action) and it calls render, the infinite loop makes it difficult to debug

**Comment by chrisbloom7** [comment]
A sufficient enough fix for this could also be as simple as updating the actioncontroller docs with a list of reserved keywords which shouldn't be used as actions, as we do or attribute names in https://guides.rubyonrails.org/active_record_basics.html#schema-conventions

**Comment by rafaelfranca** [comment]
> A sufficient enough fix for this could also be as simple as updating the actioncontroller docs with a list of reserved keywords which shouldn't be used as actions, as we do for attribute names in https://guides.rubyonrails.org/active_record_basics.html#schema-conventions

Yes. I agree we can document this.

**Comment by chrisbloom7** [comment]
Great. I can tackle that, then. Can you think of any other keywords we should include along with `config`?

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/blob/main/actionpack/lib/abstract_controller/base.rb#L156-L297 is a good start, but there are many others in `ActionController::Metal` and `ActionController::Base`.

**Comment by americodls** [comment]
And about rename those methods that could be overridden by mistake to something like `__<method_name>__`?

I think not even all methods that are intended to be used by the framework should have this shape, but I think this decision could be interesting for those which are designed to be inherited from or are risky to be overwritten by mistake.

This should be done without rely on the method visibility (private, protected, public).

Upsides:
- Almost totally self-documented: just one paragraph could describe that methods with the shape `__<method_name>__` are internal and the overwritten of them should be done with caution.
- Will avoid people who are not aware of internal methods to overwrite them inadvertently.

Downsides:
- A lot of work to be done. (but maybe it is possible to do it gradually?)

Is it a bad idea?

**Comment by zzak** [comment]
@americodls @chrisbloom7 Have you been able to make any progress here? 🙏

**Comment by chrisbloom7** [comment]
@zzak thanks for the reminder. I haven't yet, but I can get to it this week.

**Comment by zzak** [comment]
@chrisbloom7 Sounds good, please don't hesitate if you have any questions! :bow:

**Comment by chrisbloom7** [comment]
@zzak I'm leaning towards this living at https://guides.rubyonrails.org/action_controller_overview.html#methods-and-actions at the bottom of that section, just below the paragraph starting `Only public methods are callable as actions...`. Another option could be somewhere in `/routing.html`, like either in https://guides.rubyonrails.org/routing.html#adding-more-restful-actions or https://guides.rubyonrails.org/routing.html#non-resourceful-routes, but those are more oriented towards the routes themselves than the controller actions. Do you have any preference? Or is there another section of the guide that goes more in depth on actions which I might not be aware of?

**Comment by chrisbloom7** [comment]
I wanted to get a sense of how many methods would result in something like what redefining `config` as an action method does, mainly to see if the list would be small enough to include in full in the new callout section. To help figure that out I generated a new [rails app](https://github.com/chrisbloom7/rails-6-action-controller-reserved-methods) that dynamically creates controllers, actions, and routes for each instance method on `ActionController::Base`, and plus an integration test suite with a [custom reporter](https://github.com/chrisbloom7/rails-6-action-controller-reserved-methods/blob/main/test/test_helper.rb#L7-L46) that would exercise each route and dump failures to a [CSV file](https://gist.github.com/chrisbloom7/97a4b10a0135008c68b77016c14b0d93). In Rails 6.1.3 there are 17 methods (including `config`) that would result in `SystemStackError: stack level too deep` if redefined in a controller, 9 that would result in a `ArgumentError` if redefined, and 3 that would result in a `AbstractController::DoubleRenderError`. Most of these are obvious, like yeah don't redefine `class` or `render` or `action_name`. TBH the only one that jumps out at me as surprising is the one I originally encountered: `config`. So it's probably not worth mentioning specific method names, but I still feel it's worth calling out that there is a potential for accidentally redefining one of these methods and suddenly getting hit with ambiguous `SystemStackError` in all actions in the controller. Working on something along the lines of the text below. Will refine it and get a PR up in the morning

> While it's possible to define action methods of any name, some method names are reserved by Action Controller. Because of this, limiting your controllers to the using only the default RESTful [Resource Routing][] actions do not need to worry about this, but if your application defines custom routes then you should be aware of the potential for collision with a reserved method. If you find that your application would benefit from using a reserved method as an action name, one workaround is to define your action with a non-reserved method name and then use a custom route to map the otherwise reserved method name to your non-reserved action method.

**Comment by zzak** [comment]
@chrisbloom7 I need a bit more time to review this, but unfortunately yes a PR will make things easier once I can see the code :bow: Thanks for your effort!

**Comment by iksflow** [comment]
@chrisbloom7 
`AbstractController::DoubleRenderError` brought me here😂 Thanks to you, I could easily understand the cause.
But I think this message is still insufficient in response to the question "What caused double rendering?". 
I just created a method named `config` in Controller, but Log told me it was a rendering problem.🤔
It was difficult to understand.
