### ISSUE TITLE
Allow updating ActionCable protocols (JWT authentication)

### ISSUE THREAD

**Issue by zedtux** [rails/rails#41338]
JWT authentication with ActionCable can be achieved passing the JWT in the WebSocket (sub)protocol so that the `ApplicationCable::Connection` can retrieves them from the `request.headers[:HTTP_SEC_WEBSOCKET_PROTOCOL]` hash.

There's [a gem](https://github.com/saravanabalagi/action-cable-react-jwt) doing exactly that but it is not maintained and it looks like the author import a version of ActionCable and adds the feature.
It would make much more sense to have a way of doing it in ActionCable directly.

Having a function to append/replace (when JWT has been renewed) a protocol to the passed list to the WebSocket would be great and smell like a small change but before opening a PR I wanted to get the maintainers/community's input about this.

Thank you

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.
