### ISSUE TITLE
Inconsistent behaviour in Hash.except between different Ruby/Rails versions

### ISSUE THREAD

**Issue by skipchris** [rails/rails#41330]
When calling `.except` on a Hash in rails, the behaviour of the resulting Hash, _specifically_ its default value (but perhaps other things as well) changes depending on which Rails/Ruby combo you are using.

In Rails 5.x and below, `except` called `dup` on the Hash, meaning its default return value is preserved.

In Rails 6.0.x, this has changed to `slice`, meaning the Hash’s default return value is reset to `nil`

In Rails 6.1.x, this defers to the underlying Ruby implementation if it exists, so if it’s ran on Ruby 2.x the hash’s default return value will be reset (as the AS implementation is used), and if it’s ran on Ruby 3.x, the hash’s default return value will be preserved (as the Ruby implementation is used)

### Steps to reproduce
This test will pass in Rails 5, fail in 6.0, fail in 6.1 on Ruby 2.x, pass on 6.1 on Ruby 3.x
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    assert Hash.new(5).except.default == 5
  end
end
```

### Expected behavior
This should, at least, be consistent. The silent change caught us out during a 5.2 -> 6.0 upgrade. 

If we’re delegating to Ruby, we should be consistent with Ruby, so the default value of the Hash should be preserved.

I think the most pragmatic way to fix this is to simply revert to the Rails 5 implementation, even if the 6.0 implementation runs faster. My reasoning is that people will be eventually moving to Ruby 3 and picking up the native implementation, so any _slight_ slowness introduced by the ActiveSupport implementation will evaporate over time. 

If a revert to the Rails 5 implementation isn’t desirable for whatever reason, the implementation should still change to something which is consistent with the native Ruby 3 behaviour so people upgrading their 6.1 apps to Ruby 3 don’t experience a surprise change.

Happy to do a PR, etc but I wanted to be sure people understand and agree with the diagnosis of the issue first.

**Comment by intrip** [comment]
What about adding this information to the [Rails upgrade guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-2-to-rails-6-0)?

**Comment by skipchris** [comment]
I’d be happy to add that warning, but I don’t think doing so solves all the problems:

* If you upgrade a Rails 6.x application from Ruby 2 to Ruby 3, the behaviour will change. I’m not sure the Rails upgrade guide is the best place for that information (and obviously, there is no Ruby upgrade guide).
* Should this be considered a bug, and if so, fixed? I appreciate there may be other perspectives, but I don’t expect that calling `except` on a Hash should alter its default value (OK, it’s returning a new Hash with a different default value, but hopefully the point stands). 

I realise that things are clouded by the ruby version inconsistency, but at present if you call `except` on Rails 6.x on Ruby 2.x, the behaviour is weird at best, buggy at worst.

**Comment by andrehjr** [comment]
I think that unless intended, the behavior should match Ruby's for consistency before 3.0. For example https://github.com/rails/rails/pull/39159

Another example, `slice!` copies the default values/proc over to the new hash. Similar issue: https://github.com/rails/rails/pull/12611

**Comment by kamipo** [comment]
It is a regression for #35771.

@skipchris Are you interested to make a PR that reverting #35771 with a regression test?

**Comment by skipchris** [comment]
Yup!

**Comment by andrehjr** [comment]
The tests on #41414 are broken. Seems like on Ruby 3.0 `except` does not copy the `default` over. In that case, the current impl seems correct. 🤔 

```
> RUBY_VERSION
=> "3.0.0"
> Hash.new(5).except.default
=> nil
```

Hence the broken tests? 
```
Failure:
HashExtTest#test_except_does_not_alter_default_value [/Users/andrehjr/work/rails/activesupport/test/core_ext/hash_ext_test.rb:444]:
Expected: 5
  Actual: nil


bin/test test/core_ext/hash_ext_test.rb:438
```

**Comment by andrehjr** [comment]
Also see: https://github.com/ruby/ruby/blob/master/spec/ruby/core/hash/except_spec.rb#L23-L32

**Comment by skipchris** [comment]
Right — I’ve made a mistake here. 

I thought the version of Ruby 3 on my system was the release version, but I was actually testing against `-preview2`. As you can see, the change to Ruby’s behaviour was fairly last-minute (19th Dec!)

Nevertheless, it’s most important to be consistent against Ruby, so I’ll close my PR.

Still worth a mention in the upgrade guide?

**Comment by rafaelfranca** [comment]
Not in the upgrade guide, but definitely worth mention in the CHANGELOG
