### ISSUE TITLE
rails action_text:install doesn't generate required files

### ISSUE THREAD

**Issue by El-Potato-Slayer** [rails/rails#41348]
### Steps to reproduce
run `rails action_text:install` inside application root folder

### Expected behavior
The following should be produced
```
Copying actiontext.scss to apps/assets/stylesheets
    create app/assets/stylesheets/actiontext.scss
Copying fixtures to test/fixtures/action_test/rich_texts.yml
    create test/fixtures/action_test/rich_texts.yml
Copying blob rendering partial to rails/views/active_storage/blobs/_blob.html.erb
    create rails/views/active_storage/blobs/_blob.html.erb
Installing JavaScript dependencies
     run  bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.1 from "."
```

### Actual behavior
I get the following:
```
    rails  app:binstub:yarn
Installing JavaScript dependencies
     run  bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.1 from "."
```

### System configuration
**Rails version**: Rails 6.1.1

**Ruby version**: ruby 2.7.2p137

**Comment by jonathanhefner** [comment]
@El-Potato-Slayer Please see https://github.com/rails/rails/issues/41345#issuecomment-774104150.

**Comment by El-Potato-Slayer** [comment]
@jonathanhefner I'm using a Linux subsystem. Previously I used Windows to install action_text
