### ISSUE TITLE
rails action_text:install fails

### ISSUE THREAD

**Issue by El-Potato-Slayer** [rails/rails#41353]
**Note**
I ran this command on Ubuntu as well as macOS. screenshots are provided.

### Steps to reproduce
run `rails action_text:install`

### Expected behavior
The following should be produced
```
Copying actiontext.scss to apps/assets/stylesheets
    create app/assets/stylesheets/actiontext.scss
Copying fixtures to test/fixtures/action_test/rich_texts.yml
    create test/fixtures/action_test/rich_texts.yml
Copying blob rendering partial to rails/views/active_storage/blobs/_blob.html.erb
    create rails/views/active_storage/blobs/_blob.html.erb
Installing JavaScript dependencies
     run  bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.1 from "."
```

### Actual behavior
![{3A1DE291-0D31-4E19-827D-71E904748B2F}](https://user-images.githubusercontent.com/43865875/107114130-41862880-686c-11eb-9841-810b270c2f20.jpg)
![image](https://user-images.githubusercontent.com/43865875/107114072-d63c5680-686b-11eb-9f31-430290f5404f.png)

### System configuration
**Rails version**: Rails 6.1.1

**Ruby version**: ruby 2.7.2p137

**Comment by andrehjr** [comment]
Wasn't able to reproduce this on OS X, using: 
Rails 6.1.1 
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

```
» rails action_text:install                                                                                                                                                                    
       rails  app:binstub:yarn
Installing JavaScript dependencies
         run  bin/yarn add trix@^1.2.0 @rails/actiontext@^6.1.1 from "."
Adding trix to app/javascript/packs/application.js
      append  app/javascript/packs/application.js
Adding @rails/actiontext to app/javascript/packs/application.js
      append  app/javascript/packs/application.js
      create  app/assets/stylesheets/actiontext.scss
      create  app/views/active_storage/blobs/_blob.html.erb
       rails  railties:install:migrations FROM=active_storage,action_text
Copied migration 20210206150255_create_active_storage_tables.active_storage.rb from active_storage
Copied migration 20210206150256_create_action_text_tables.action_text.rb from action_text
      invoke  test_unit
      create    test/fixtures/action_text/rich_texts.yml
``` 

I believe is something related to your setup. What happens when you do `./bin/yarn` directly?

**Comment by jonathanhefner** [comment]
@El-Potato-Slayer If this project was copied from a Windows file system, then the executable flags on the bin stubs will not be set.  You can fix this by running `chmod a+x bin/*` in the project directory.

#41200 also addresses this since it runs `bin/yarn` via the Ruby executable regardless of operating system.

**Comment by El-Potato-Slayer** [comment]
@andrehjr Thank you for responding. As @jonathanhefner mentioned. It had to do with the incorrect executable flags.

**Comment by El-Potato-Slayer** [comment]
@jonathanhefner Thank you, that worked like a charm. However, I'm still unable to install action text. As a test, I created a new project on Ubuntu, and I managed to install action text without an issue. However, a project created on Windows doesn't generate the required files. Even when run on WSL. I believe this is an issue specifically for Windows on rails 6.1.1.

**Comment by jonathanhefner** [comment]
@El-Potato-Slayer Now that Rails 6.1.2 is released, would you mind trying again, and reporting back any issues?

**Comment by El-Potato-Slayer** [comment]
@jonathanhefner Of course. I'll report back on everything once I'm done.

**Comment by El-Potato-Slayer** [comment]
@jonathanhefner With the latest update, action_text generates all of the required files. The rich text area displays correctly, and image attachments work as expected.
A separate issue has also been resolved that prevented the `image_processing` gem from being installed only on Windows. 
Everything works perfectly.

Thank you. All the hard work is greatly valued.
