### ISSUE TITLE
When prepared_statements is true, Rails 6.1 raises Mysql2::Error with mysql2 gem.

### ISSUE THREAD

**Issue by zeitnot** [rails/rails#41368]
### Steps to reproduce
[Here](https://github.com/zeitnot/prepared_statement) is the sample application which raises exception when prepared_statements is true. Along with sample application, I want to write down the steps:

- Clone and bundle the application
- `rails g model User email:string`
- `rails db:create db:migrate`
- Open your rails console and type `User.create(email: 'test@test.com')`

### Expected behavior
It should create the record without exception.

### Actual behavior
ActiveRecord::StatementInvalid (Mysql2::Error: Incorrect datetime value: '0' for column 'created_at' at row 1)

### System configuration
**Rails version**:
6.1.1
**Ruby version**:
2.6.6

I tried it with postgres as well the result is the same.

**Comment by rafaelfranca** [comment]
I see. It just configure `prepared_statements: true` on `config/database.yml`. I can confirm this bug is happening in a new app.

**Comment by santib** [comment]
Hey @rafaelfranca I found the guilty commit `d29d4598972e85df7ee42f5aa969b51d1b14d615`. Seems like we added an extra condition `!value.utc?` that is causing this failure.
```ruby
# activemodel/lib/active_model/type/helpers/time_value.rb

value = value.getutc if value.respond_to?(:getutc) && !value.utc?`
```

The intention of the commit is reducing the amount of allocations so I'm not sure what is the correct path to take, if reverting the commit or if always making sure to transform the `value` from a `ActiveSupport::TimeWithZone` into a `Time`.. thoughts?

**Comment by rafaelfranca** [comment]
I'd measure. I had a patch for this myself and was debating what is the best course of action.

Another solution would be to change `_type_cast` on the MySQL adapter to make this transformation. Do you want to measure if it is better to make the transformation in the adapter or add the transformation to the type?

**Comment by santib** [comment]
I'm not sure I'd be able to measure it. Do you mean measuring object allocation such as Ryuta did with:

```ruby
ObjectSpace::AllocationTracer.setup(%i{path line type})

pp ObjectSpace::AllocationTracer.trace {
  1_000.times { User.create }
}.select { |k, _| k[0].end_with?("quoting.rb", "time_value.rb") }
```

or measuring performance with the benchmarking script?

**Comment by rafaelfranca** [comment]
Measuring the allocation like Ryuta did.

**Comment by santib** [comment]
@rafaelfranca I was able to measure the `.to_time` solution I proposed and it performs even worser than the code before the commit that introduces the bug
![image](https://user-images.githubusercontent.com/6373536/107590686-87821a00-6be7-11eb-8443-e48fd531aa96.png)

So now we have two options, either going with your mysql specific fix or reverting the commit. Unfortunately, I can't take a look at it today, so feel free to go ahead.

**Comment by kamipo** [comment]
Identified the root cause, it is due to `_type_cast` in mysql2 adapter does not properly handle the time object what `quoted_date` does.

Suggested fixes are:

* Just remove the `_type_cast` in mysql2 adapter
* Fix the `_type_cast` in mysql2 adapter to properly handle the local and the time with zone object

```diff
diff --git a/activerecord/lib/active_record/connection_adapters/mysql/quoting.rb b/activerecord/lib/active_record/connection_adapters/mysql/quoting.rb
index 0069f5871c..62b92581be 100644
--- a/activerecord/lib/active_record/connection_adapters/mysql/quoting.rb
+++ b/activerecord/lib/active_record/connection_adapters/mysql/quoting.rb
@@ -71,7 +71,9 @@ def column_name_with_order_matcher
         private
           def _type_cast(value)
             case value
-            when Date, Time then value
+            when Time
+              # ...
+            when Date then value
             else super
             end
           end
```

**Comment by rafaelfranca** [comment]
> Another solution would be to change `_type_cast` on the MySQL adapter to make this transformation.

That is what I said above. I'll push my patch then since I already had write it.
