### ISSUE TITLE
action_mailbox/engine still loads even after not requiring it in application.rb

### ISSUE THREAD

**Issue by szTheory** [rails/rails#41361]
### Steps to reproduce
Use this code at the top of `application.rb` to require only what you need instead of `require "rails/all"`. Note that `action_mailbox/engine` is not being required.

```ruby
require_relative "boot"

# Instead of including all Rails components,
# only include what we need to reduce memory footprint
# For example we don't need ActionCable and Sprockets
# Look at rails/all.rb in the Rails source code to see
# the original full list
# require "rails/all"
# "active_storage/engine", #activestore not used
# "action_cable/engine", #websockets not used
# "action_mailbox/engine", #inbound email not used
# "action_text/engine", #actiontext rich text editor not used
# rubocop:disable Style/RedundantBegin
require "rails"
[
  "active_record/railtie",
  "action_controller/railtie",
  "action_view/railtie",
  "action_mailer/railtie",
  "active_job/railtie",
  "rails/test_unit/railtie",
  "sprockets/railtie",
].each do |railtie|
  begin
    require railtie
  rescue LoadError
  end
end
# rubocop:enable Style/RedundantBegin
```

### Expected behavior

When running `bundle exec derailed bundle:mem` after following the [derailed install instructions](https://github.com/schneems/derailed_benchmarks), action_mailbox should not appear as loaded in memory.

### Actual behavior

`bundle exec derailed bundle:mem` shows `action_mailbox/engine` as being loaded in memory, taking up ~32MB RAM:

```ruby
➜ bundle exec derailed bundle:mem
TOP: 77.1992 MiB
  rails/all: 61.7266 MiB
    action_mailbox/engine: 32.5508 MiB
```

### System configuration
**Rails version**:
6.1.1

**Ruby version**:
2.7.2

**Comment by andrehjr** [comment]
I think that's because rails/all is required when running `derailed bundle:mem` [here](https://github.com/schneems/derailed_benchmarks/blob/main/bin/derailed#L86).

Also, it looks like it only loads up your Gemfile and doesn't boot the application itself.

**Comment by kamipo** [comment]
Closing this since it is not a Rails' issue.
