### ISSUE TITLE
Behavior change after "Optimize underscore inflector" optimization

### ISSUE THREAD

**Issue by leequarella** [rails/rails#41382]
https://github.com/rails/rails/commit/58147cd2b494beec92f810a40dc9a736ff688a01 made a change to ActiveSupport underscore inflector that causes a behavior change.  Previously, when handed a camel cased string with 2 capital letters side by side it would separate those with an underscore. After the change they are kept together.  Any grouping of more than 2 capital characters are maintained as a group in both versions. 

Before:

```
AbCDeFgHIJK
Ab_C_De_Fg_HIJK
```

After

```
AbCDeFgHIJK
Ab_CDe_Fg_HIJK
```

(PR #41303)

**Comment by eileencodes** [comment]
cc/ @byroot curious if you have any ideas how to fix this while keeping your performance optimizations. Specifically this broke some of our GraphQL fields.

**Comment by casperisfine** [comment]
Thanks for letting me know. I'll dig into this ASAP and come back to you.
