### ISSUE TITLE
Uppercase strings that contain acronym inflections do not titleize properly

### ISSUE THREAD

**Issue by amilligan** [rails/rails#41398]
### Steps to reproduce

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "minitest/autorun"

class BugTest < Minitest::Test
  def setup
    ActiveSupport::Inflector.inflections(:en) do |inflect|
      inflect.acronym("IBB") # International Bureau of Boxers (the dogs, not the pugilists)
    end
  end

  def test_titleize_acronym
    assert "ibb".titleize == "IBB"
    assert "wibble".titleize == "Wibble"
    assert "WIBBLE".titleize == "Wibble"
  end
end
```

### Expected behavior
```
# Assuming "IBB" is defined as an acronym inflection:
"WIBBLE".titleize # => "Wibble"
```

### Actual behavior
```
# Assuming "IBB" is defined as an acronym inflection:
"WIBBLE".titleize # => "W IBB Le"
```

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 2.7.2

**Comment by gmcgibbon** [comment]
Thanks for the issue, but unfortunately we do not accept patches to `ActiveSupport::Inflector` due to the possibility that applications depend on current behaviour.  See https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html for more information.

**Comment by cam-ball** [comment]
Is there another document somewhere describing this decision in more detail? To @joshgoebel 's point, fixing this feels like the kind of breaking change that is acceptable to introduce in a major version release, just like any other breaking change
