### ISSUE TITLE
Rails 6.0 guides aren't accessible from guides.rubyonrails.org

### ISSUE THREAD

**Issue by josh-m-sharpe** [rails/rails#41405]
### Steps to reproduce
1) visit https://guides.rubyonrails.org/
2) click on Rails 6.0
3) redirected to: https://edgeguides.rubyonrails.org/

### Expected behavior
Expected to be redirected to https://guides.rubyonrails.org/v6.0 (similar to other versions)

### Actual behavior
redirected to: https://edgeguides.rubyonrails.org/

I pulled this repo and built the guides.  Seems index.html gets built correctly:
```
<a href="https://guides.rubyonrails.org/v6.1/">Rails 6.1</a>,
<a href="https://guides.rubyonrails.org/v6.0/">Rails 6.0</a>,
<a href="https://guides.rubyonrails.org/v5.2/">Rails 5.2</a>,
<a href="https://guides.rubyonrails.org/v5.1/">Rails 5.1</a>,
```

So maybe the 6.0 guides aren't built correctly wherever they are hosted?

**Comment by rafaelfranca** [comment]
Fixed. Thank you.
