### ISSUE TITLE
Onion Services should be considered secure for cookies

### ISSUE THREAD

**Issue by jtracey** [rails/rails#41426]
### Steps to reproduce

When running a Rails application as an [onion service](https://tools.ietf.org/html/rfc7686) over HTTP, Rails does not send cookies with the secure flag set. This is true of any Rails application, but a workaround was just [merged into Mastodon](https://github.com/tootsuite/mastodon/pull/15712) by monkey patching Rails.

### Expected behavior

Because onion services are end-to-end encrypted and authenticated, they are [considered secure for cookies](https://bugzilla.mozilla.org/show_bug.cgi?id=1633015) by browsers that support them (Tor Browser, Firefox when configured to use Tor, and Brave). Therefore, for the purposes of cookies, there should be no difference between behavior when loading a site via HTTPS and via a .onion URL.

### Actual behavior

When serving a request, Rails [only checks for HTTPS](https://github.com/rails/rails/blob/092713ffb0369e962ea09c0f64c5a33749cbebb6/actionpack/lib/action_dispatch/middleware/cookies.rb#L442) (or a dev environment) when deciding whether to serve secure cookies. This prevents things like logins from functioning properly on onion services. A common workaround (probably the most common workaround) is to not mark cookies as secure for onion services, but this gets risky when operating a site as both an onion service and traditional site -- something frequently done on Mastodon instances, hence the [monkey patch solution](https://github.com/tootsuite/mastodon/pull/15712/commits/d5f69c6bdd9af587c8b4343c71dbd2ddb1a9f4b2#diff-efeb6e15a330821d94adb72ff4d7ec785918e7dcddc68e31f936ffbef8432742R10).

**Comment by rafaelfranca** [comment]
Makes sense. Do you want to provide a pull request?

**Comment by jtracey** [comment]
Sure, I'll just have to just set up an environment for running rails' tests first.

**Comment by jonathanhefner** [comment]
@jtracey If your changes don't interact with databases and the like, it may suffice to test them running `bin/test path/to/your_test.rb` in the appropriate framework directory (e.g. `actionpack`).  (You may need to run `bundle install` first.)  However, if you do need a more complete development environment, try [rails-dev-box](https://github.com/rails/rails-dev-box).

**Comment by jtracey** [comment]
Issue should still exist, as the relevant PR (#41470) has yet to be merged.
