### ISSUE TITLE
[ActiveStorage] Unable to use the following syntax: `user.avatar.variant(:thumb)`

### ISSUE THREAD

**Issue by niuage** [rails/rails#41446]
### Steps to reproduce

Model:

```
class Drink < ApplicationRecord
  has_one_attached :thumbnail do |attachable|
    attachable.variant(:thumb, resize: "100x100")
    attachable.variant(:regular, resize_to_limit: [500, 1000])
    attachable.variant(:large, resize_to_limit: [1000, 2000])
  end
```

View:
```
image_tag drink.thumbnail.variant(:thumb) if c.thumbnail.attached?
```

I got this syntax from this guide: https://edgeguides.rubyonrails.org/active_storage_overview.html#has-one-attached

I'm probably doing something wrong or not using the right version, but I think I'm using the latest rails.

### Expected behavior

I expect the code above to behave the same way this code does (i.e. render the image tag)

```
image_tag drink.thumbnail.variant(resize: "100x100") if c.thumbnail.attached?
```

### Actual behavior

```
undefined method `deep_symbolize_keys' for :thumb:Symbol
```

So, I get that the variant method is expecting a hash of transformations, but in the guide it seems like we can use a name defined on the model. Am I wrong?

### System configuration
**Rails version**:
6.1.2.1

**ActiveStorage**
6.1.2.1

**Ruby version**:
2.6.6p146

**Comment by santib** [comment]
Hi @niuage, seems like https://github.com/rails/rails/blob/eb7cee01698d928a944e1abd088a66d15a753bbf/activestorage/app/models/active_storage/attachment.rb#L40 is not present in the `v6.1.2.1` release.

You shared a link to the `edge` guides, instead you should look at your current version guides https://guides.rubyonrails.org/v6.1.2.1/active_storage_overview.html#has-one-attached

**Comment by kaspth** [comment]
This is a new feature, that'll be released in 7.0. Thanks!

**Comment by niuage** [comment]
Ok, thanks! I thought that edge referred to the latest released version, and not latest master or anything like that. That explains it.

**Comment by arpu** [comment]
wups hit this too :/  with rails 6.1.3 and github master
