### ISSUE TITLE
ActiveRecord::Base.no_touching does not prevent touch on save

### ISSUE THREAD

**Issue by fschwahn** [rails/rails#41462]
### Steps to reproduce
When saving a record inside a `ActiveRecord::Base.no_touching`-block, the `updated_at`-column is updated. I'm aware that there's a very similar issue #18811, however in the meantime the possibility to do `model.save(touch: false)` was added. The similarity in names leads one to believe that `no_touching` implies that the model is saved with `touch: false`.

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "~> 6.0"
  gem "sqlite3"
  gem 'byebug'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.timestamps
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.timestamps
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_no_touching
    post = Post.create!

    timestamp_before_update = post.updated_at
    ActiveRecord::Base.no_touching do
      post.update!(title: "Foo")
    end

    assert_equal timestamp_before_update, post.updated_at
  end
end
```

### Expected behavior
I see several possiblities here:
- Extend `no_touching` so it does not update timestamp columns.
- Rename `save(touch: false)` to something like `save(record_timestamps: false)`, to be more closely aligned with `ActiveRecord::Base.record_timestamps`
- At the very least extend the docs of `no_touching` to make it clear that it does not imply `save(touch: false)`

### Actual behavior
`no_touching` somewhat surprisingly does not mean the same as `save(touch: false)` despite the similarity in names.

### System configuration
**Rails version**: 6.1.2.1
**Ruby version**: 2.7.2

**Comment by lfalcao** [comment]
This module is a little confusing indeed, but the docs is clear when it says that '_disable calls to touch_. However, being so low used ([github results](https://github.com/search?l=Ruby&q=NoTouching+-%22module+NoTouching%22+-%22autoload+%3ANoTouching%22+-%22include+NoTouching%22&type=Code)) I think it could be removed...

Btw, you can disable touch for a block using:

```ruby
    ActiveRecord::Base.record_timestamps = false
    timestamp_before_update = post.updated_at
    post.update!(title: "Foo")
    ActiveRecord::Base.record_timestamps = true
```
