### ISSUE TITLE
PendingMigrationError not raised for engine migrations

### ISSUE THREAD

**Issue by wedgex** [rails/rails#41460]
### Steps to reproduce

We have an engine mounted that adds it's migration directory to the app's configuration as follows

```ruby
  initializer :append_migrations do |app|
    unless app.root.to_s.match root.to_s
      config.paths['db/migrate'].expanded.each do |expanded_path|
        app.config.paths['db/migrate'] << expanded_path
      end
    end
  end
```

When running the application, `ActiveRecord::PendingMigrationError` is never raised by the middleware if there are pending migrations in the engine. However the rake tasks pick them up correctly, `bin/rails db:migrate:status` for example shows the correct migration status.

I can only assume there's some subtle difference in timing in when the `migration_context` gets loaded in the application when running vs rake tasks.

### Expected behavior

`ActiveRecord::PendingMigrationError` would be raised if there are pending migrations in the engine.

### Actual behavior

No error is raised.

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.6.2

**Comment by wedgex** [comment]
After digging in a bit deeper it seems that the `ActiveRecord::Migration::CheckPending` middleware ultimately uses `Migrator.migrations_paths` as its source of migration paths. However nothing ever seems to set this when running the application so it remains the default.

https://github.com/rails/rails/blob/561fa1e165766a45ef9b0c93d7dd3bc746775bc3/activerecord/lib/active_record/migration.rb#L1235

In a migration rake task the configuration is loaded at set on the `Migrator` which explains why it works in that context.

https://github.com/rails/rails/blob/0f09dfca363410f51f6f60787a0e497ee66cdd13/activerecord/lib/active_record/railties/databases.rake#L26

https://github.com/rails/rails/blob/0f09dfca363410f51f6f60787a0e497ee66cdd13/activerecord/lib/active_record/tasks/database_tasks.rb#L93-L95

For the time being I've added this to our initializer, which seems to work. It just feels strange to have to set the path in two places.

```ruby
  migrate_relative_path = Pathname.new(expanded_path)
    .relative_path_from(app.root)
    .to_s

  ActiveRecord::Migrator.migrations_paths.push(migrate_relative_path)
```

**Comment by intrip** [comment]
I wonder if this is the correct usage of engine and migrations, by checking the docs it's suggested to copy the migration from the engine to the main app https://guides.rubyonrails.org/engines.html#engine-setup with the `install:migrations` rails task.

**Comment by p8** [comment]
@intrip I think I agree. We even copy the migrations for Active Storage and Action Text: https://guides.rubyonrails.org/action_text_overview.html#installation

**Comment by intrip** [comment]
@p8 can we close this issue at this point? It's been here for a while and we all agree that it's not a bug.

**Comment by p8** [comment]
@intrip, looking at it more closely, we do have the following:
https://github.com/rails/rails/blob/main/activerecord/lib/active_record/railtie.rb#L45
So it does seem we do support this.
Should we maybe add the engine paths to the `ActiveRecord::Migrator.migrations_paths` there as well?
There also is this PR which changed some things for migration_paths: https://github.com/rails/rails/pull/31727

**Comment by intrip** [comment]
@p8 Thanks for taking a look! I'm not an expert on this topic but I've done a few checks and looks like:

- https://github.com/rails/rails/blob/main/activerecord/lib/active_record/railtie.rb#L43 is true only when is ran inside an engine (not from the main application) and is required in order to run the migrations whilst developing the engine
- The guides clearly states that [migration from engines should be copied to the application in order to be ran](https://edgeguides.rubyonrails.org/engines.html#engine-setup)

So I think that the behaviour of automatically running migrations from engine is not something which we are supporting right now which leads to the conclusion that, unless we want to provide such support this is not a bug.
If someone wants to add such behaviour to his engine he can still use the workaround outlined in this issue.

**Comment by p8** [comment]
Thanks for looking into this @intrip.
I'm not an expert on this topic either.
This does seem like a feature request instead of a bug, so I'll close it for now.
