### ISSUE TITLE
test is mixing nested attributes when using `with_options` validation

### ISSUE THREAD

**Issue by yalmasri** [rails/rails#41477]
### Steps to reproduce

- I have created an example project to reproduce the error with `rspec` and `minitest`:
https://github.com/yalmasri/rspec-nested

- add validation `with_options` to validate attributes by enum type:
https://github.com/yalmasri/rspec-nested/blob/master/app/models/seek.rb#L4

- create test and send 2 nested records to be created, each record with a different enum type and different attributes:
  - https://github.com/yalmasri/rspec-nested/blob/master/spec/requests/exchanges_request_spec.rb#L6
  - https://github.com/yalmasri/rspec-nested/blob/master/test/controllers/exchanges_controller_test.rb#L7

- print the params before sending the request in the test file, and print the received params in the controller, you will notice that the nested attributes are mixed and well formed.

- also you can refer to rspec issue I have created: https://github.com/rspec/rspec-rails/issues/2459

### Expected behavior

expected to receive the nested attributes as it has been declared in the test file

### Actual behavior

if you send 2 nested attributes, controller receive the params mixed one with the other.

### System configuration
**Rails version**:
Rails 6.1.2.1

**Ruby version**:
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

**Comment by zzak** [comment]
It seems there was some more information in the rspec-rails thread, but no one has triaged this one :(

I'll keep it open if anyone has time to look 🙏
