### ISSUE TITLE
Running an individual test file should not use parallelized workers

### ISSUE THREAD

**Issue by dhh** [rails/rails#41473]
Parallelized-worker testing is amazing. When you're running a large suite of tests, and all your cores are cooking, it's peach. But when you're just running a single test file, the overhead required to setup the number of test databases equal to the number of cores you have is too great. So when we run a single test file, rather than a whole suite, we should not be using parallelized workers.

So: `./bin/rails test`, `./bin/rails test:system`, etc should use parallelized workers as today.

But `./bin/rails test test/controllers/my_controller_test.rb` should not.

**Comment by ricardotk002** [comment]
@dhh Are you thinking of something like this? https://github.com/rails/rails/compare/ricardotk002:disable-parallel-testing Happy to open a PR if that's the case.

Comparing times using the test example (printing the output):

Before
```
Finished in 0.208965s, 4.7855 runs/s, 0.0000 assertions/s.
```

After
```
Finished in 0.002195s, 455.5809 runs/s, 0.0000 assertions/s.
```
