### ISSUE TITLE
Multiple Databases: Role suppose to change automatically based on request type? 

### ISSUE THREAD

**Issue by sajjadmurtaza** [rails/rails#41476]
Currently, I am trying to use Multiple Databases in my application and my ApplicationRecord looks like
`connects_to database: { writing: :primary, reading: :primary_replica }`

Things are working fine but in my controller method when I print `ActiveRecord::Base.current_role` the output is always `:writing`. 

`ActiveRecord::Base.current_role` should be `:reading` in case of `index` or `show` method - right? or do I need to use `ApplicationRecord.connected_to(role: :reading){..}` everywhere?

### System configuration
**Rails version**: 6.1

**Ruby version**: 2.7.2

**Comment by eileencodes** [comment]
Are you using the automatic swapping middleware? It won't automatically switch the connection if you don't have that turned on. Please read the guides here: https://guides.rubyonrails.org/active_record_multiple_databases.html

**Comment by sajjadmurtaza** [comment]
Oppssii. Sorry, I just added in `production.rb` and i forgot to add in my `development.rb`

Thanks alot! @eileencodes! 

Actually, I was checking your video on youtube and tried to do the same!
