### ISSUE TITLE
Forced mysql2 Require on mysql2_adapter.rb is Causing Issues With Custom mysql2 Library

### ISSUE THREAD

**Issue by bunnyUFO** [rails/rails#41471]
### Steps to reproduce
include in gemfile
```
gem 'activerecord'
gem 'mysql2-lambda'
```
bundle
run code
`ActiveRecord::Base.establish_connection( adapter: 'mysql2', encoding: 'utf8', port: 3306)`

### Expected behavior
Should create connection and run fine

### Actual behavior
`"Error loading the 'mysql2' Active Record adapter. Missing a gem it depends on? Could not find 'mysql2'`

### System configuration
Running inside lambda with ruby 2.5 image.
Should work local ruby configuration too.

### Extra Info 

mysql2-lambda creates a custom mysql2 lib file that I want to require instead of the official mysql2 gem.
On [mysql2_adapter](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/mysql2_adapter.rb)
vendor cache gem when I comment out mysql2_adapter.rb#6  `gem "mysql2", "~> 0.5"` it works. 
**Is there a way to stop forcing the mysql2 gem to be used to I can require the mysql2 library file that mysql2-lambda has?**

**Comment by eileencodes** [comment]
This looks incorrect to me: `ActiveRecord::Base.establish_connection( adapter: 'mysql2', encoding: 'utf8', port: 3306)`. There can only be on `mysql2` adapter. Try changing it to `mysql2-lambda`, ie `ActiveRecord::Base.establish_connection( adapter: 'mysql2-lambda', encoding: 'utf8', port: 3306)`

If that doesn't fix it it's an issue with the mysql2-lambda gem, not Rails. Please open an issue at https://github.com/customink/mysql2-lambda

**Comment by bunnyUFO** [comment]
@eileencodes 'mysql2-lambda' has no adapter. It really is no different from mysql2 other than having the binary mysqlclient packaged in. It could use the exact same adapter if it just didn't forcefully depend on `gem "mysql2", "~> 0.5"`. Inside mysql2-lambda there is a mysql2 package that you can require instead.

**Comment by rafaelfranca** [comment]
> Inside mysql2-lambda there is a mysql2 package that you can require instead.

We can require but we can't assert the version is compatible. `gem "mysql2", "~> 0.5` is there to make sure mysql2 0.4 or lower is not used. The `mysql2_adapter` adapter in Rails to be used with the mysql2 gem. If people want to distribute their own version of the mysql2 library without using the mysql2 gem, they can also distribute their own version of mysql2_adapter as well.

**Comment by bunnyUFO** [comment]
@rafaelfranca That makes sense.
I'll figure out how to make an adapter for my use case.

**Comment by bunnyUFO** [comment]
After some digging around I found that the `mysql2-lambda` gem just [overrides the gem method if rails is present](https://github.com/customink/mysql2-lambda/blob/master/lib/mysql2-lambda.rb). Not using rails so didn't work. Will override it with a similar method that does not check for rails.

**Comment by DanielViglione** [comment]
@bunnyUFO what solution did you come up with?

**Comment by DanielViglione** [comment]
I bypassed the issue with this hack for non-Rails app:

    ```
# monkeypatch Kernel#gem
    def enforce_lambda_lib_for_mysql2_adapter
      $ORIG_GEM_METHOD = method(:gem)
      Kernel.send :remove_method, :gem
      Kernel.send :define_method, :gem do |dep, *reqs|
        unless ['mysql2'].include?(dep)
          $ORIG_GEM_METHOD.call(dep, *reqs)
        end
      end
    end
```
