### ISSUE TITLE
Syntax error when add_index is used at Postgresql with both options if_not_exists and algorithm

### ISSUE THREAD

**Issue by kivanio** [rails/rails#41480]
There is a syntax error for Postgresql when using both `if_not_exists: true` and `algorithm: :concurrently` options.

From what I have checked this seems to be an issue in previously rails versions too.

Postgresql documentation since 9.6 point that the Rails syntax is wrong.
https://www.postgresql.org/docs/current/sql-createindex.html
<pre>
CREATE [ UNIQUE ] INDEX [ CONCURRENTLY ] [ [ IF NOT EXISTS ] name ] ON 
</pre>

Rails put `IF NOT EXISTS` before `CONCURRENTLY ` causing the error.
<pre>
CREATE INDEX IF NOT EXISTS CONCURRENTLY "index_posts_on_owner_id" ON "posts" ("owner_id")
</pre>

The correct should be:
<pre>
CREATE INDEX CONCURRENTLY IF NOT EXISTS "index_posts_on_owner_id" ON "posts" ("owner_id");
</pre>

I could try make a fix if I receive any guidance. 

### Steps to reproduce
<pre>
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.0"
  gem 'pg',            '1.2.3'
end

require "active_record"
require "minitest/autorun"
require "logger"

`dropdb active_record_gem_template`
`createdb -E UTF8 -T template0 active_record_gem_template`

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'active_record_gem_template')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :owner_id
  end

  add_index(:posts, :id, if_not_exists: true)
  add_index(:posts, :owner_id, algorithm: :concurrently, if_not_exists: true)
end

</pre>

### Actual behavior
<pre>
ERROR:  syntax error at or near "CONCURRENTLY" (PG::SyntaxError)
LINE 1: CREATE INDEX IF NOT EXISTS CONCURRENTLY "index_posts_on_owne...
                                   ^
</pre>

### System configuration
**Rails version**: 6.1.2.1
 pg:   1.2.3

**Ruby version**:
2.7.2

**Potgresql**
13.1

**Comment by fatkodima** [comment]
Please, create a fix with a proper test case.
