### ISSUE TITLE
Loaded has_many collection doesn't get updated when new records are created

### ISSUE THREAD

**Issue by alimi** [rails/rails#41481]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3", "~>1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments.load
    comment = Comment.create!(post: post)

    assert_includes post.comments.pluck(:id), comment.id
    assert_includes post.comments, comment
  end
end
```

### Expected behavior

`post.comments` should include the new `Comment`, and `post.comments.pluck(:id)` should include the new `Comment`'s id.

### Actual behavior

`post.comments` doesn't include the new `Comment`, nor does `pluck` include the new `Comment` id.

```
Failure:
BugTest#test_association_stuff [rails_master_pluck_bug.rb:47]:
Expected [] to include 1.
```

```
Failure:
BugTest#test_association_stuff [rails_master_pluck_bug.rb:48]:
Expected #<ActiveRecord::Associations::CollectionProxy []> to include #<Comment id: 1, post_id: 1>.
```

### System configuration
**Rails version**: master

**Ruby version**: 2.7.1

### Notes

The test script passes on ActiveRecord 5.0.0 (with an older version of the sqlite3 gem). It looks like it first fails on ActiveRecord 5.0.1.rc1.

https://github.com/rails/rails/pull/25976 *might* be related.

**Comment by p8** [comment]
Hi @alimi, it does work if you do:
```
    comment = post.comments.create!
```

**Comment by alimi** [comment]
@p8 yeah, `comment = post.comments.create!` works.

Should `comment = Comment.create!(post: post)` work too, or is that not the expected behavior? It used to work in older versions of ActiveRecord.

**Comment by eileencodes** [comment]
Hey @alimi 😄 

I think this is an issue with an already loaded association. If you call `post.reload` before the assertions then the script passes. I'm not sure this is a bug, that seems like expected behavior to me. I think potentially pluck worked before #25976 but wasn't supposed to.

**Comment by alimi** [comment]
Hey @eileencodes! 👋🏾

Hmm, ok. I'm working on a Rails upgrade from 4.2, and we're running into problems because this used to work in 4.2 but doesn't in 5+. Fortunately this has only been a problem in the test suite, and it's not the end of the world to sprinkle `reload`s in a few tests. It feels a little wrong though.

**Comment by systemist** [comment]
Should we / @alimi upstream a test case for future versions? 4.2 is out of maintenance, so if @eileencodes thinks this is intended, it seems like a test case for using `Comment.create!(post:post)` vs `post.comments.create!` could be useful.
