### ISSUE TITLE
Conotrollers scaffold generator update broke old behaviour for previous rails versions.

### ISSUE THREAD

**Issue by panSarin** [rails/rails#41539]
### Steps to reproduce

```
rails _6.0.3.5_ new test_app
cd test_app
rails g scaffold tickets
```

### Expected behavior
Based on 
https://github.com/rails/rails/blob/6-0-stable/railties/lib/rails/generators/rails/scaffold_controller/templates/controller.rb.tt
it should generate something like:
```
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        redirect_to @ticket, notice: "Ticket was successfully created." 
      else
        render :new
      end
    end
  end

```

### Actual behavior

but generated:
```
  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end
```
I am aware that it is not a big deal, even if someone will use the new scaffold in old rails, it won't break anything.
Only thing is that tests generated from RSpec are expecting old behavior. 
So I created PR in Rspec https://github.com/rspec/rspec-rails/pull/2466 for that change, but it looks like - for build for old versions of rails, it also expects new behavior. So that is more like a question than a regular issue report - should I assume that now each rails version will generate that kind of controller? Or maybe it is related to some strange scaffold cache/spring behavior?

**Comment by p8** [comment]
Hi @panSarin Thanks for reporting this issue.
It seems like the scaffolds are generated by the wrong Rails version.
Does it also occur if you run:
```bin/rails g scaffold tickets```
And what does `rails -v` return when run from the `test_app` directory?

**Comment by lfalcao** [comment]
@panSarin 

It's **jbuilder** who is creating the controller file: https://github.com/rails/jbuilder/blob/master/lib/generators/rails/templates/controller.rb#L28

If you just remove it from Gemfile and execute the scaffold will use the template you mentioned (https://github.com/rails/rails/blob/6-0-stable/railties/lib/rails/generators/rails/scaffold_controller/templates/controller.rb.tt)

**Comment by JuanVqz** [comment]
recently, I had the same issue I just removed the `, status: :unprocessable_entity` in the else statement `format.html { render :new }` and it still works.

**Comment by zzak** [comment]
@JuanVqz Can you explain more about the issue you ran into? 🤔

**Comment by JuanVqz** [comment]
@zzak sure! 
Context:
_I have a rails app it was created at 5.X version and recently (about 1 or 2 days) I updated it to version 6.X, then I ran the scaffold command as usual when I was running RSpec I noticed one of the new request tests was failing and I fond the error comes from the **create** method in the controller._


```ruby
def create
  @model = Model.new(model_params)
   respond_to do |format|
    if @model.save
      format.html { redirect_to @model, notice: "message." }
      format.json { render :show, status: :created, location: @model }
    else 
     format.html { render :new, status: :unprocessable_entity  }
     format.json { render json: @model.errors, status: :unprocessable_entity }
   end
  end
end

it "renders a successful response" do
  post model_url, params: { model: invalid_attributes }
  expect(response).to be_successful
end
```

I removed the  `status: :unprocessable_entity` in the `format.html { render :new }` in order to fix the issue, I'm thinking it failed because the `be_successful` expects a 200 response code but it receives another one.

**Comment by zzak** [comment]
@JuanVqz Oh ok, yeah I would expect an attempt to create a model with invalid attributes would not be a successful (200) response.

Was this test something you wrote?

```
it "renders a successful response" do
  post model_url, params: { model: invalid_attributes }
  expect(response).to be_successful
end
```

**Comment by JuanVqz** [comment]
@zzak no, it comes from the scaffold.
that is the reason we may change `be_successful` for another one since the scaffold returns a `unprocessable_entity`.
what do you think?
