### ISSUE TITLE
Unknown Attribute after column is added to db and shows on console when instance of the model is called

### ISSUE THREAD

**Issue by nsikanikpoh** [rails/rails#41540]
### Expected behavior

attribute should be mass assigned with new and read from model object. 

### Actual behavior

I added a migration as follows:
`class AddPaceLearnToPlans < ActiveRecord::Migration[5.2]
    def change
      add_column :plans, :pace_learn, :boolean, default: false
      add_column :plans, :publish, :boolean, default: false
    end
end`

`publish` is accessible and mass assigned by new. 
`pace_learn` throws ` ActiveModel::UnknownAttributeError (unknown attribute 'pace_le
arn' for Plan.):` on create  action.

this line throws that error ` Plan.new(plan_params)`

### System configuration
**Rails version**:
5.2.3

**Ruby version**:
2.7.1

**Comment by intrip** [comment]
Looks like there is an issue with the name `'pace_le arn'` could you double check that? 
Would be also nice to have a reproduction script.
Is it only Rails5 or also newer?

**Comment by nsikanikpoh** [comment]
Oh thanks. I'm just taking note of the space in `pace_le arn`.
