### ISSUE TITLE
undefined method `pool when running a test with multiple databases on Rails 6.1

### ISSUE THREAD

**Issue by yknx4** [rails/rails#41549]
### Steps to reproduce
  I have a normal test to an endpoint that calls two different databases
  ```ruby
      get '/api/rankings', params: {
        domain: 'example',
        tld: 'com',
        ranked_at: '20210220'
      }, headers: { authorization: 'Bearer XXXXX' }
      expect(response).to have_http_status(200)
```

database.yml
```yml
test:
  primary:
    <<: *default
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: primary_test

  secondary:
    <<: *default
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    database: secondary_test
    migrations_paths: db/secondary_migrate
```

### Expected behavior
It should complete the test with no DB errors

### Actual behavior
```1.1) Failure/Error:
             get '/api/rankings', params: {
        domain: 'example',
        tld: 'com',
        ranked_at: '20210220'
      }, headers: { authorization: 'Bearer XXXXX' }
          
          NoMethodError:
            undefined method `pool' for nil:NilClass
          # <internal:kernel>:90:in `tap'
          # ./spec/requests/rankings_request_spec.rb:15:in `block (3 levels) in <top (required)>'

     1.2) Failure/Error: owner_to_pool_manager.values.flat_map { |m| m.pool_configs.map(&:pool) }
          
          NoMethodError:
            undefined method `pool' for nil:NilClass
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1035:in `map'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1035:in `block in all_connection_pools'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1035:in `each'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1035:in `flat_map'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1035:in `all_connection_pools'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_handling.rb:356:in `clear_on_handler'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_handling.rb:275:in `clear_query_caches_for_current_thread'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/query_cache.rb:21:in `rollback_db_transaction'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:205:in `rollback'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:302:in `block in rollback_transaction'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:300:in `rollback_transaction'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/database_statements.rb:328:in `rollback_transaction'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/test_fixtures.rb:168:in `block in teardown_fixtures'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/test_fixtures.rb:167:in `each'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/test_fixtures.rb:167:in `teardown_fixtures'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activerecord-6.1.3/lib/active_record/test_fixtures.rb:16:in `after_teardown'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activejob-6.1.3/lib/active_job/test_helper.rb:52:in `after_teardown'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-rails-4.0.2/lib/rspec/rails/adapters.rb:76:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `block in run'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `map'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `run'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/bin/rspec:23:in `load'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/bin/rspec:23:in `<top (required)>'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:63:in `load'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:63:in `kernel_load'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/lib/bundler/cli/exec.rb:28:in `run'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/lib/bundler/cli.rb:494:in `exec'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/lib/bundler/cli.rb:30:in `dispatch'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/lib/bundler/cli.rb:24:in `start'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/exe/bundle:49:in `block in <top (required)>'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/bundler-2.2.9/exe/bundle:37:in `<top (required)>'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/bin/bundle:23:in `load'
          # /home/yknx4/.asdf/installs/ruby/3.0.0/bin/bundle:23:in `<main>'
```

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 3.0.0

**Comment by eileencodes** [comment]
Thanks for the report @yknx4. Unfortunately, there's not enough information in this issue to figure out what's wrong. Can you make a sample application that reproduces the issue? Are you using legacy_connection_handling or the new connection handling?

**Comment by eileencodes** [comment]
I tried reproducing this on 6.1 generated app with both the new and legacy connection handling and the tests passed. This is either an issue with rspec (I used minitest because that's the default), or with a part of the application setup not included in the report.

**Comment by jdarnok** [comment]
@yknx4 Hey! have you managed to fix the problem? I'm facing similar stuff - all works on production but fails in rspec. It throws error only when trying to do the read to the db - writes seem to work

**Comment by zzak** [comment]
@jdarnok Would you mind opening a new issue with a [reproducible example](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb) that will help us determine if this is a bug in Rails or not :bow:

**Comment by jdarnok** [comment]
@zzak @yknx4 
Turns out that I only had controller specs in rspec. When I've added `models` folder with empty spec (just a `describe` block) - all works. It's clearly an rspec Issue and the way it loads stuff.

**Comment by zzak** [comment]
@jdarnok Wait, if this is an rspec issue isn't it better to report it there instead? 🤔

**Comment by JonRowe** [comment]
RSpec doesn't load things, Rails does. If it works with controller tests (which use the `rails-controller-testing` gem) or request specs, but not model specs, its because the inclusions for those tests don't include Rails configuration for multiple databases. As we scribe from rails test helpers here its far more likely some lazy loading is failing to load the right things,

**Comment by zzak** [comment]
@JonRowe Fair enough, if someone could help write a [reproduction script](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb) that would help us get to the bottom of it :bow:

**Comment by zzak** [comment]
@JonRowe @jdarnok Ok, @rails-bot is being a PITA so if you can come up with a [reproduction script](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb) can you please open a new ticket? :bow:

**Comment by andykallhoff** [comment]
I am getting this exact same error. However, my env is slightly different:
```
- ruby 3.0.0
- rails 6.1.3.2
- mysql 8.0.25

- not using RSPEC, only minitest
```

@zzak I didn't do a reproduction script, but I did do a [sample project repo](https://github.com/andykallhoff/multi-tenant-minitest) on my github page. Will report back if I find a workaround.

**Comment by eileencodes** [comment]
I looked at the sample project and I can see why this is broken. These roles are incorrect, they cannot be `all` they must be `writing`:

```
  shards_config = {    default: {all: :default},    one: {all: :one},    two: {all: :two}  }
````

The only way `all` can be used is by setting the `config.active_record.writing_role` to `:all` and I don't see that set in your application. So Rails can't find the `pool` because it's looking for `pool` under the `writing` role for the shard. Rails doesn't know to look up the pools from `all` unless you added `connected_to(role: :all)` which is commented out in your tests.

Second I don't think this can be `default` here https://github.com/andykallhoff/multi-tenant-minitest/blob/master/config/database.yml#L10 - at least I wouldn't recommend it. It is confusing to have 2 configs named default - I'd choose primary or something else just to avoid confusion. I'm unsure this will actually cause a bug though.

**Comment by andykallhoff** [comment]
@eileencodes appreciate you! This is the piece I was missing: `config.active_record.writing_role`. My mistake, I assumed since we are utilizing a permissions gem for actual permissions, I thought the role names wouldn't matter.

**Comment by eileencodes** [comment]
I thought about it a bit more and while this was implemented incorrectly the error you're getting isn't right. It should be that there's no connection pool rather than an undefined method. I'll look at improving the error handling so it's raising the correct one.

**Comment by JoshCheek** [comment]
We're dealing w/ this issue, as well :P If you want an env where it's reproduced (not whittled down to a minimal script, though), then you're welcome to jump on the call where we're trying to debug it :) https://meet.google.com/ekf-zngc-oec

**Comment by JoshCheek** [comment]
This fixed it for us. 
![image](https://user-images.githubusercontent.com/77495/121070946-8ecbc580-c78c-11eb-940c-7468d1b9bd44.png)

I don't really understand why, but once I got down into the code that was blowing up, and read the comments around there, I saw an example that did that, which worked ([here](https://github.com/rails/rails/blob/6-1-stable/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L953)).

In a very technical sense, we could see that [this](https://github.com/rails/rails/blob/6-1-stable/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L1035) line was exploding because the pool config's reading default was `nil`, even though I don't really understand why that was the case.

Anyway, hope this is helpful.

**Comment by eileencodes** [comment]
That's not really a fix if someone intends to use multiple databases - however there's no reason to use connects_to in your app if you aren't using replicas so that change is fine for your app @JoshCheek 

I reopened this so I remember to fix the error message, but the only repro provided so far is a misconfiguration, not a bug in Rails. This other incident of this bug also feels like a clear case of misconfiguration, but I have no bandwidth to debug applications in the wild, I would need to know how to reproduce this in a pared down env if it is configured correctly.

**Comment by JoshCheek** [comment]
> That's not really a fix if someone intends to use multiple databases - however there's no reason to use connects_to in your app if you aren't using replicas so that change is fine for your app @JoshCheek

A little confused on this one, we do have multiple databases (so it seems like "that's not really a fix" would apply to us), and we aren't using replicas. Different models come from different databases.

> I reopened this so I remember to fix the error message, but the only repro provided so far is a misconfiguration, not a bug in Rails. This other incident of this bug also feels like a clear case of misconfiguration, but I have no bandwidth to debug applications in the wild, I would need to know how to reproduce this in a pared down env if it is configured correctly.

Honestly, it wouldn't surprise me if they all turn out to be configuration issues. I assume we're all following along with https://guides.rubyonrails.org/active_record_multiple_databases.html but I think it's more oriented towards the replica use case.

**Comment by JoshCheek** [comment]
FWIW, I did attempt to reproduce it from scratch on a brand-new minimal Rails app, and did not encounter this issue.

**Comment by eileencodes** [comment]
> A little confused on this one, we do have multiple databases (so it seems like "that's not really a fix" would apply to us), and we aren't using replicas. Different models come from different databases.

Sorry I meant multiple connection types. Your model in this example is using only a writing connection - so `connects_to` isn't necessary. But if someone had replicas then using `establish_connection` won't work.

**Comment by eileencodes** [comment]
I have dug into this and understand why this is happening in the test environment but the path to this in test is not possible in production. This error happens if `set_pool_config` is setting `nil` for the `pool_config` argument and is caused by how the fixtures share connections. I've improved this by raising an error if anything tries to set the pool config to nil in #42537.

Now that I understand where this is coming from, I don't see how this can happen in production because `set_pool_config` is only called from `connection_handler.establish_connection` in prod which will not accept `nil` for the config argument and won't gracefully handle a `pool_config` that's `nil`. This means that something in your app is messing with connections in an unexpected way @JoshCheek. Perhaps a gem or the app is using the private PoolManager APIs. Without a reproduction we can't dig into that possibility more.

**Comment by batalla3692** [comment]
I came a little bit late to this issue, but I've been dealing with this very same error on test environement _(although now it has a nicer error message thanks @eileencodes)_.

After reading the error message, I found that the error is raised when the order of the roles defined in the model is not exactly `:writing` first and then `:reading`...

I had those roles inverted in my model, so the error was being triggered:
```ruby
class AuditRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { reading: :audit, writing: :audit }
end
```

But everything started to work after I changed the order to:
```ruby
class AuditRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :audit, reading: :audit }
end
```

**Comment by eileencodes** [comment]
@batalla3692 I fixed that in https://github.com/rails/rails/pull/45773. It was backported to 7-0-stable and 6-1-stable but only if you're using the new connection handling. Opting into new handling (set `config.active_record.legacy_connection_handling = false` and fix any calls to `connection_handlers`) should be pretty simple if you haven't already.
