### ISSUE TITLE
Different index name is given when running migration in Rails 6.1

### ISSUE THREAD

**Issue by JunichiIto** [rails/rails#41547]
### Steps to reproduce

```
git clone git@github.com:JunichiIto/index_name_sandbox.git
bundle install
rails db:create
rails db:migrate
git diff
```

Then, you will see:

```diff
diff --git a/db/schema.rb b/db/schema.rb
index 38de2d5..5834f92 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -23,7 +23,7 @@ ActiveRecord::Schema.define(version: 2021_02_25_025817) do
     t.datetime "updated_at", null: false
     t.string "widget_type"
     t.bigint "widget_id"
-    t.index ["imageable_type", "imageable_id"], name: "index_pictures_on_imageable_type_and_imageable_id"
+    t.index ["imageable_type", "imageable_id"], name: "index_pictures_on_imageable"
     t.index ["widget_type", "widget_id"], name: "index_pictures_on_widget_type_and_widget_id"
   end
```

### Expected behavior

`git diff` should show nothing. (no difference)

### Actual behavior

- [The polymorphic index name that was defined in Rails 5.2](https://github.com/JunichiIto/index_name_sandbox/blob/main/db/migrate/20210225025058_create_pictures.rb#L5) will change in Rails 6.1.
- But [the polymorphic index name that was defined in Rails 6.0](https://github.com/JunichiIto/index_name_sandbox/blob/main/db/migrate/20210225025817_add_widget_reference_to_pictures.rb#L3) will not change in Rails 6.1.

This issue seems to be related to https://github.com/rails/rails/pull/38717 (And I give a mention to @lukeredpath and @eugeneius )

### System configuration
**Rails version**: Rails 6.1.3

**Ruby version**: Ruby 2.7.2

**Comment by lukeredpath** [comment]
If it helps, you should use db:schema:load to recreate a new database, not db:migrate. There's lots of ways old migrations can change behaviour as your codebase changes over time and also between Rails versions.

**Comment by JunichiIto** [comment]
You can see my commit logs here:
https://github.com/JunichiIto/index_name_sandbox/commits/main

I just created a Rails 5.2 application for testing purpose and added a model with polymorphic association, then updated to Rails 6.0 and added another polymorphic association column, finally updated to Rails 6.1.

> You can see there was a test for preserving the original behaviour on old migrations in my PR.

I saw it, but I don't know why it doesn't work for Rails 5.2 migration. The test might fail if it has Rails 5.2 migration.

**Comment by aglushkov** [comment]
Same issue for me. 

### Reproducable script:

Here created `users`  table with polymorphic `imagable` using 5.2 migration version.
Correct index for 5.2 should be `index_users_on_imagable_type_and_imagable_id`
Logs shows that was created index with name `index_users_on_imagable`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord", "6.1.3"
  gem "sqlite3"
end

require "active_record"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

class CreateUsers < ActiveRecord::Migration[5.2]
  def change
    create_table(:users) do |t|
      t.belongs_to :imagable, polymorphic: true, index: true
    end
  end
end

CreateUsers.migrate(:up)

# ==  CreateUsers: migrating ====================================================
# D, [2021-03-23T14:24:42.978938 #23103] DEBUG -- :    (0.7ms)  SELECT sqlite_version(*)
# -- create_table(:users, {})
# D, [2021-03-23T14:24:42.979797 #23103] DEBUG -- :    (0.2ms)  CREATE TABLE "users" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "imagable_type" varchar, "imagable_id" integer)
# D, [2021-03-23T14:24:42.980121 #23103] DEBUG -- :    (0.1ms)  CREATE INDEX "index_users_on_imagable" ON "users" ("imagable_type", "imagable_id")
#    -> 0.0010s
# ==  CreateUsers: migrated (0.0011s) ===========================================
```

**Comment by zzak** [comment]
@JunichiIto Could you give #42350 a try and let us know if that solves your issue? 🙇

**Comment by JunichiIto** [comment]
@zzak I confirmed the issue has been fixed. Thank you!

**Comment by ziaulrehman40** [comment]
This issue is still happening, issue is closed but relevent PR is not merged yet so issue is not fixed

**Comment by cdcooksey** [comment]
This is happening for me with Postgres. 

I have a HABTM join table with 2 foreign key columns. Rails' default generated name is too long for Postgres and fails. Overriding the name in the migration does nothing. Rails still attempts to use it's own generated index name rather than my explicit override.
