### ISSUE TITLE
Ability to set default values with `rails generate`

### ISSUE THREAD

**Issue by cloud69420** [rails/rails#41566]
Anybody know if `rails g migration` will ever let you set default values? Seems kinda silly having to manually add them afterwards :)

In my case it'd be nice with say `rails g migration AddVotesToPosts upvotes:integer:0 downvotes:integer:0`.

Thanks everyone!

**Comment by intrip** [comment]
Is not possible: https://guides.rubyonrails.org/active_record_migrations.html#column-modifiers
"null and default cannot be specified via command line."

**Comment by cloud69420** [comment]
@intrip yes, but it would be nice if it was possible!

**Comment by robin850** [comment]
Hello,

Thanks @cloud69420, but this tracker is for issues only. Questions must be asked on the [rubyonrails-talk](https://discuss.rubyonrails.org/c/rubyonrails-talk) forum and and feature requests on [rubyonrails-core](https://discuss.rubyonrails.org/c/rubyonrails-core).

**Comment by anon987654321** [comment]
Agreed, this has to happen. @dhh
