### ISSUE TITLE
"Invalid encoding for parameter" no more reaching action with rails 6.1

### ISSUE THREAD

**Issue by martinlevesque** [rails/rails#41567]
Hey,

Looks like since rails 6.1, I am now getting the following errors getting thrown before reaching the controller action code:

```
{"timestamp":"2021-02-23T06:47:50.081+00:00","level":"INFO","message":"Started POST \"/order/paypal\" for 173.0.81.1 at 2021-02-23 06:47:50 +0000"}
{"timestamp":"2021-02-23T06:47:50.091+00:00","level":"FATAL","message":"  \n[95374279-da00-4a90-9621-7bf9c5cd87dd] ActionController::BadRequest (Invalid request parameters: Invalid encoding for parameter: Test-Rh�ne-Alpes):\n[95374279-da00-4a90-9621-7bf9c5cd87dd]   \n[95374279-da00-4a90-9621-7bf9c5cd87dd] actionpack (6.1.3) 
```

while before, I was handling these bad encoding parameters, without failing requests - those are valid transactions from Paypal. 

Is it a breaking change? And is there a way to avoid having that exception being throw and process the raw post - i'm typically processing it with `request.raw_post` for fixing encoding issues.

Thanks

edit: looking at the release note, I believe it's the following item:

```
Catch invalid UTF-8 parameters for POST requests and respond with BadRequest.

Additionally, perform #set_binary_encoding in ActionDispatch::Http::Request#GET and
ActionDispatch::Http::Request#POST prior to validating encoding.
```

would be great to have a way to disable this for a specific route, and be able to process request.raw_post. That new check is probably correct for most cases, but if you want to process without encoding check you just cannot.

**Comment by martinlevesque** [comment]
Can use the following to skip encoding checks (not really recommended thus):

_$ cat config/initializers/skip_encoding_check.rb_ 

```
module ActionDispatch
  class Request
    class Utils # :nodoc:
      def self.check_param_encoding(params)
        # skipping this, to avoid failing with Invalid encoding for parameter
        # due to Catch invalid UTF-8 parameters for POST requests and respond with BadRequest.
        # introduced in rails 6.1.0
      end
    end
  end
end
```

**Comment by intrip** [comment]
Your request is against the HTTP 1.1 RFC: https://tools.ietf.org/html/rfc2616#page-16
For a simple explanation check https://stackoverflow.com/questions/4400678/what-character-encoding-should-i-use-for-a-http-header

Hence there are no valid reason for allowing invalid `UTF-8` characters.

**Comment by martinlevesque** [comment]
I get that, but it turns out some major companies (e.g. Paypal) sometimes send "invalid" characters - the default should definitely to fail on invalid characters, but IMO would be nice to have a way to disable it via an option when you want to handle it in a controller.

**Comment by rafaelfranca** [comment]
Yes. That was a change introduced in Rails 6.1. You can disable using http://api.rubyonrails.org/classes/ActionController/ParameterEncoding/ClassMethods.html#method-i-skip_parameter_encoding

See https://github.com/rails/rails/pull/40124

**Comment by raldred** [comment]
Having issues with Sendgrid's inbound parse API posting incorrectly encoded UTF-8 strings.
Like with @martinlevesque's example of Paypal, they may not be compliant with RFCs, but often people will have endpoints that are hit by third parties who they have possible influence on ensuring they're following standards.

**Comment by ghiculescu** [comment]
@raldred  if I'm reading it right, https://github.com/rails/rails/issues/42278 is a similar issue (it also mentions Sendgrid!) and it looks like @adrianna-chang-shopify has plans on fixing it 👍  It would be great to centralise the discussion on there.

**Comment by ghiculescu** [comment]
Oh, even better, could you see if https://github.com/rails/rails/pull/42396 fixes the issue for you?

**Comment by raldred** [comment]
Awesome thanks @ghiculescu and sorry for dragging up a closed thread, been stuck with this one for a while.

**Comment by abury** [comment]
@raldred how did you end up solving this issue? We're a bit stuck as `skip_parameter_encoding` isn't supported in an API controller, and the linked issued in this thread aren't resolved.

**Comment by raldred** [comment]
@abury we moved the controller to use ActionController::Base and used `skip_parameter_encoding :create`

**Comment by abury** [comment]
@raldred yeah I ended up doing the same.

**Comment by raldred** [comment]
Glad to hear you're sorted.

**Comment by bv-shreyansh** [comment]
Hey,

is there a way to know before hand ..the bad request is happening for which controller. Because I am thinking of specifying the encoding manually using `param_encoding `for every parameter of every controller. But I am not able to identify the params and controller.

These are the following logs I am getting

```
Rails -- Exception: ActionController::BadRequest: Invalid query parameters: invalid %-encoding (%%32%65%%32%65%%32%66%%32%65%%32%65%%32%66%%32%65%%32%65%%32%66%%32%65%%32%65%%32%66%%32%65%%32%65%%32%66%%36%35%%37%34%%36%33%%32%66%%37%30%%36%31%%37%33%%37%33%%37%37%%36%34)

Rails -- Exception: ActionController::BadRequest: Invalid query parameters: Invalid encoding for parameter: ..��../..��../..��../..��../..��../..��../boot.inibvserver/.rvm/gems/ruby-2.7.4/gems/actionpack-6.1.7.4/

Rails -- Exception: ActionController::BadRequest: Invalid request parameters: Invalid encoding for parameter: Sandh�fer Allee
```

I don't want to use   `skip_parameter_encoding`

**Comment by ShreyanshSingh20** [comment]
Hey,

is there a way to know before hand ..the bad request is happening for which controller. Because I am thinking of specifying the encoding manually using `param_encoding `for every parameter of every controller. But I am not able to identify the params and controller.

These are the following logs I am getting

```
Rails -- Exception: ActionController::BadRequest: Invalid query parameters: invalid %-encoding (%%32%65%%32%65%%32%66%%32%65%%32%65%%32%66%%32%65%%32%65%%32%66%%32%65%%32%65%%32%66%%32%65%%32%65%%32%66%%36%35%%37%34%%36%33%%32%66%%37%30%%36%31%%37%33%%37%33%%37%37%%36%34)

Rails -- Exception: ActionController::BadRequest: Invalid query parameters: Invalid encoding for parameter: ..��../..��../..��../..��../..��../..��../boot.inibvserver/.rvm/gems/ruby-2.7.4/gems/actionpack-6.1.7.4/

Rails -- Exception: ActionController::BadRequest: Invalid request parameters: Invalid encoding for parameter: Sandh�fer Allee
```

I don't want to use   `skip_parameter_encoding`

**Comment by jaynetics** [comment]
an alternative solution, especially in API mode, is to use a middleware like https://github.com/whitequark/rack-utf8_sanitizer
