### ISSUE TITLE
undefined method `deduplicate' for 4:Integer Did you mean? duplicable?

### ISSUE THREAD

**Issue by fynsta** [rails/rails#41580]
On the following statement, we experienced an error
`Product.find(13).devices.pluck(:id)`

The error was 
> undefined method `deduplicate' for 4:Integer Did you mean? duplicable?

According to AppSignal, it happened in active_record/connection_adapters/mysql/type_metadata.rb, line 33

### System configuration
**Rails version**:
6.1.0

**Ruby version**:
3.0.0

**Comment by p8** [comment]
Hi @fynsta. Thanks for submitting this issue.
Could you add a reproduction script using a bug template? For example:
https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb

**Comment by fynsta** [comment]
Hi, thanks for your answer. I'd like to add a reproduction script, but for some reason I can not reliably reproduce the error, which is very weird...

**Comment by fynsta** [comment]
Sure, 
For `Product.find(13).devices.map(&:id)`

> Product Load (0.6ms)  SELECT `products`.* FROM `products` WHERE `products`.`id` = 13 LIMIT 1
>   Device Load (1.9ms)  SELECT `devices`.* FROM `devices` WHERE `devices`.`product_id` = 13
> => [18697,
>  19307,
>  19308,
>  19309,
>  19310,
>  19311,
>  19312,
>  19313,
>  19314,
>  19315, 
> .....
> 

And for `Device.where(product_id: 13).map(&:id)`

> Device Load (1.6ms)  SELECT `devices`.* FROM `devices` WHERE `devices`.`product_id` = 13
> => [18697,
>  19307,
>  19308,
>  19309,
>  19310,
>  19311,
>  19312,
>  19313,
>  19314
> ......

But right now, `pluck(:id)` works again and gives the same result... If this is not enough information (and I suspect it is not) I can close the issue until I notice it the next time and can find out more about it.

**Comment by p8** [comment]
Weird... Does the error always mention the number 4? 4 used to be the object id of nil. Can the column contain nil values?

**Comment by fynsta** [comment]
Hm do you mean the id column? That can't be nil...
The error occured only once, and the relevant line is in a sidekiq-worker that runs very regularly. Could that have something to do with it?

**Comment by p8** [comment]
Hmm... could be that the devices/product weren’t committed to the database while sidekiq was trying to process them.

**Comment by fynsta** [comment]
Didnt occur againg

**Comment by iMasashi** [comment]
we got same error

> NoMethodError: undefined method `deduplicate' for 4:Integer

Rails version: 7.1.5.1

**Comment by willnet** [comment]
@iMasashi Can you create a reproduction script?
