### ISSUE TITLE
Time.at(946702800, 123) fails with latest Rails on Ruby 2.5.8

### ISSUE THREAD

**Issue by eregon** [rails/rails#41583]
### Steps to reproduce

```
ruby -ractivesupport -e 'p Time.at(946702800, 123)'
```

### Expected behavior
```
2000-01-01 06:00:00 +0100
```

### Actual behavior
```
del.rb:4:in `at': unexpected unit: {} (ArgumentError)
	from del.rb:4:in `at_with_coercion'
	from del.rb:19:in `<main>'
```

### System configuration
**Rails version**: latest
**Ruby version**: 2.5.8

Extracted from https://github.com/rails/rails/commit/249232f6590394103494aa83075cc5c38efa0e6d#r47699843
Related to #41375

**Comment by p8** [comment]
Hi @eregon, thanks for reporting this.

If I run the following script:
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    assert_equal "2000-01-01 06:00:00.000123 +0100", Time.at(946702800, 123).inspect
  end
end
```

I get the following error on 2.5.8:
```
activesupport-7.0.0.alpha requires ruby version >= 2.7.0, which is incompatible with the current version, ruby 2.5.8p224 (Bundler::InstallError)
```

**Comment by kamipo** [comment]
Main branch is targeted to >= Ruby 2.7.

But I've found the backported commit 97a0a94cc825810f4cd1e3c74cf75ed7159a330c has another bug that losing `in` option.
It will be fixed by #41592.

**Comment by kamipo** [comment]
Closing this in favor of #41592.

**Comment by eregon** [comment]
I see, my bad, I thought master was Rails 6 and still supported Ruby 2.5.

Nevertheless, the delegation on `master` is still brittle and could be incorrect in some corner cases for Ruby 2.7, so I think we should use `ruby2_keywords` on `master` too.
In general, `(*args, **kwargs)` delegation doesn't work on Ruby 2.7, only in Ruby 3+.
I'll make a PR.

**Comment by kamipo** [comment]
> In general, `(*args, **kwargs)` delegation doesn't work on Ruby 2.7, only in Ruby 3+.

I know about that, but specifically in the case of delegating to the original `Time#at`, AFAICS there is no problem.

**Comment by eregon** [comment]
PR: https://github.com/rails/rails/pull/41594
