### ISSUE TITLE
SQL produced by eager loadin queries causes issues when some column is removed from DB during deploy

### ISSUE THREAD

**Issue by GProst** [rails/rails#41587]
Hello!

Eager loading queries produce SQL where each column is selected explicitly by name:
```sql
 SELECT  `users`.`id` AS t0_r0, `users`.`name` AS t0_r1, ...
```
Instead of just:
```sql
SELECT `users`.*, `association1`.*, `association2`.*, ...
```

This causes problems when some column gets removed from the database during deploy - when DB is updated but some servers are still running with the old schema loaded in memory.

Is there a way to use `*` instead of selecting all columns by name?

As I understand the current workaround is to deploy the updated schema.rb file with manually removed column in it (before generating a new migration to actually remove the column from DB) which seems a bit tricky since normally schema.rb is generated automatically by running migrations.

### System configuration
**Rails version**: 5.1.7
**Ruby version**: 2.5.1

**Comment by kamipo** [comment]
Thanks for the report, but  use `ignored_columns` for the migration purpose. #21720
