### ISSUE TITLE
Should ActionDispatch::Http::UploadedFile#headers be encoded like #original_filename

### ISSUE THREAD

**Issue by sjieg** [rails/rails#41607]
Hello,

First off, awesome work on Rails, love to use it!

**Description**

I noticed that in the initializer of `ActionDispatch::Http::UploadedFile` the original_filename is being escaped, but this doesn't happen for the headers. (Nor for the content type, but that might be a different case.
https://github.com/rails/rails/blob/12613accfdd5665600958c2c291f8377bc1f11e3/actionpack/lib/action_dispatch/http/upload.rb#L27-L45

**Actual**

The headers often also include the original filename, so if the filename included non-utf8 characters, they can still get in your system this way.

**Expected** (This is more intended as a question)

Possibly the headers should be escaped too, to prevent unwanted encoding issues later in the system.

Pro: No unwanted issues
Con: You might lose track of what the real original data was in the call. Actually, that can be accessed through `:tempfile`

**My use case**

Filename used: `Some screenshot — generated by Greenshot.png`
Pretty printed UploadedFile:
```
#<ActionDispatch::Http::UploadedFile:0x000000001d2c7ed8
 @content_type="image/png",
 @headers=
  "Content-Disposition: form-data; name=\"file[]\"; filename=\"Some screenshot \xE2\x80\x94 generated by Greenshot.png\"; filename*=UTF-8''Some%20screenshot%20%E2%80%94%20generated%20by%20Greenshot.png\r\n" +
  "Content-Type: image/png\r\n",
 @original_filename="Some screenshot — generated by Greenshot.png",
 @tempfile=
  #<File:C:/Users/gijs_/AppData/Local/Temp/RackMultipart20210303-27376-1bwovu6.png>>
```

For debugging and tracking purposes I store all `params` used and serve this to the user through JSON. `JSON.pretty_generate` then ends up trying to convert the `headers` and throws an `Encoding::UndefinedConversionError`.

It's a bit edge case, and I can solve it by force encoding before processing it. But when investigating how come the original filename seemed okay while the headers were wrong, I was a bit confused.

**I would love to contribute, so please let me know if this should be done and I'll come with a PR.**

**Comment by zzak** [comment]
@sjieg This is a good question, and I will counter with another. Are `headers` in other requests encoded like `params`?

**Comment by sjieg** [comment]
@zzak Good point, no, I suppose not. Also, looking back at this ticket after3 months, the implications that escaping the full header could have is not something you would want.

In that case, I think encoding the `original_filename` should not happen either. I suppose it happens to prevent errors creating the `tempfile`.

Thanks I'll close it. 👍

**Comment by zzak** [comment]
@sjieg A good argument for this is passing a JWT where the contents are already encoded, so encoding that with UTF-8 would break some applications. I'm sure there are other arguments against it, but (since I'm doing that at work today it came to mind)!

Anyways, thanks for following up and glad you have a working solution either way! :bow:
