### ISSUE TITLE
ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.new_client raises NoDatabaseError erroneously

### ISSUE THREAD

**Issue by ccutrer** [rails/rails#41606]
### Steps to reproduce
Have a database.yml that includes a database name, and the hostname also includes the database name. The hostname should not be resolveable. Try to connect. 

### Expected behavior
A ActiveRecord::ConnectionNotEstablished error is raised.

### Actual behavior
A ActiveRecord::NoDatabaseError is raised:
`could not translate host name "clusterX" to address: Name or service not known`

The problem is you're just checking the exception message for the database name, instead of _also_ checking if it is actually a "database does not exist" error. 

### System configuration
**Rails version**: 6.1.3
**Ruby version**: 2.7.2

**Comment by bitfurry** [comment]
I was not able to reproduce this error.  Every time when I pass an unresolvable hostname I am getting the following message:

> ActiveRecord::ConnectionNotEstablished (could not translate host name "localhostx" to address: nodename nor servname provided, or not known)


@ccutrer  could you please share your sample database.yml file?

**Comment by ccutrer** [comment]
Your hostname has to match your database name. Like this:

```
production:
  adapter: postgresql
  host: cluster1
  database: cluster1
```

**Comment by bitfurry** [comment]
Got it, I am able to reproduce it now.

The problem is how PostgreSQLAdapter  `new_client` method is rescuing the error.

  

>           if conn_params && conn_params[:dbname] && error.message.include?(conn_params[:dbname])
>             raise ActiveRecord::NoDatabaseError
>           else
>             raise ActiveRecord::ConnectionNotEstablished, error.message
>           end

```error.message.include?(conn_params[:dbname])``` is the problem.

I will try to raise a PR for this.
