### ISSUE TITLE
change_credentials_in_system_editor breaks with spaces in Windows user name

### ISSUE THREAD

**Issue by ariccio** [rails/rails#41617]
### Steps to reproduce

Run `rails credentials:edit` while using a windows username that contains spaces. In my case, it's "Lucius Riccio" (since this was my dad's laptop a decade ago)

### Expected behavior

Open a temporary file with a path like `C:/Users/Lucius Riccio/AppData/Local/Temp/22716.credentials.yml`
### Actual behavior

Opens two temporary files with vscode, like `Lucius` and a file named  Riccio/AppData/Local/Temp/22716.credentials.yml.

### System configuration
**Rails version**:
6.1.2.1
**Ruby version**:
3.0.0

[`change_credentials_in_system_editor`](https://github.com/rails/rails/blob/fdba9304c2652af674fdb9cf3704ff5a64af92d7/railties/lib/rails/commands/credentials/credentials_command.rb#L92) should handle paths with spaces.

**Comment by ariccio** [comment]
Locally patching to quote tmp_path fixes it.

**Comment by lfalcao** [comment]
@ariccio can you provide a pull request with the fix?

**Comment by ghiculescu** [comment]
> Locally patching to quote tmp_path fixes it.

@ariccio quick bump, are you able to share this patch?

**Comment by ariccio** [comment]
Sorry, I missed the email! I don't know if I have time to do a proper PR, but the patch looks like this:

```
        def change_credentials_in_system_editor
          credentials.change do |tmp_path|
            system("#{ENV["EDITOR"]} \"#{tmp_path}\"")
          end
        end

```

**Comment by ghiculescu** [comment]
Made a PR and gave you commit credit: https://github.com/rails/rails/pull/42728

**Comment by ariccio** [comment]
Excellent, thanks!!

**Comment by ariccio** [comment]
Uhh, is it possible this didn't work for some reason? Maybe I'm not noticing it until just now because I patched it locally, but the new version that uses shellwords.escape produces this:

```
"C:\Program Files\Microsoft VS Code\bin\..\Code.exe"  "C:\Program Files\Microsoft VS Code\bin\..\resources\app\out\cli.js" --ms-enable-electron-run-as-node --wait C:/Users/Lucius\ Riccio/AppData/Local/Temp/16704.credentials.yml
```
In other words, it looks like escaping just added a `\` to the path, which doesn't work for spaces. 

Perhaps instead, did you mean to do something like:

```ruby
escaped_and_quoted = Shellwords.escape("\"#{tmp_path}\"")

system("#{ENV["EDITOR"]} #{escaped_and_quoted}")

```

...or would that cause trouble for the shell redirect also?

I think I'mma locally patch this again XD

CCing @dorianmariefr [because they suggested it](https://github.com/rails/rails/pull/42728#issuecomment-876174148).

**Comment by ariccio** [comment]
No, no combination works with shellescape. Makes sense, [in the docs it says](https://ruby-doc.org/stdlib-3.1.1/libdoc/shellwords/rdoc/Shellwords.html):
```
Note that a resulted string should be used unquoted and is not intended for use in double quotes nor in single quotes.
```
