### ISSUE TITLE
Counting has_many associations with extra clauses gives wrong resuls since Rails 6.1

### ISSUE THREAD

**Issue by Naturseptime** [rails/rails#41612]
### Steps to reproduce

Since Rails 6.1 I have some trouble when counting has_many associations in combination with extra clauses.

In my setup I have four tables: Event, Registration, Person, Contacts

An event has multiple registrations:
	`has_many :registrations, -> { includes(person: [:contacts]).order('people.last_name') }, dependent: :destroy, inverse_of: :event`

A registration belongs to an event and a person
	`belongs_to :event`
	`belongs_to :person`

A person has multiple contacts (phone number, mail etc.)
	`has_many :contacts, dependent: :destroy`
	
A person registered for an event can have organizer status
	`has_many :organizers, -> {where(registrations: {organizer: true})},
		source: :person, through: :registrations`

I want to query the number of all organizers for an event.
  `Event.find(my_event_id).organizers.count`
  
### Expected behaviour

I expect that this query should return the number of all organizers.

### Actual behaviour

Since rails 6.1 it returns the number of all contacts for all organizers.

The problem comes from a wrong SQL-Query in Rails 6.1.3

`SELECT COUNT(*) FROM "people" INNER JOIN "registrations" ON "people"."id" = "registrations"."person_id" LEFT OUTER JOIN "people" "people_registrations" ON "people_registrations"."id" = "registrations"."person_id" LEFT OUTER JOIN "contacts" ON "contacts"."person_id" = "people_registrations"."id" WHERE "registrations"."event_id" = ? AND "registrations"."organizer" = ?`

In Rails 6.0.3.5 the correct SQL query was used:
`SELECT COUNT(*) FROM "people" INNER JOIN "registrations" ON "people"."id" = "registrations"."person_id" WHERE "registrations"."event_id" = ? AND "registrations"."organizer" = ?`

I think the problem comes somehow from the `order('people.last_name')` clause. Removing it gives correct counts.

### System configuration

**Rails version**
Rails 6.0.3.5 and 6.1.3 tested

**Ruby version**
My ruby version is 2.7.2p137

**Comment by louim** [comment]
Hey @Naturseptime,

Are you able to reproduce the problem with [this bug report template](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb)? This will help further investigation.

**Comment by Naturseptime** [comment]
Hallo, I have created a minimal example with the bug report template.

```
require "bundler/inline"
require 'bundler'
Bundler.configure

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.3"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :events, force: true do |t|
	t.integer :event_id
  end

  create_table :registrations, force: true do |t|
    t.integer :event_id
    t.integer :person_id
    t.boolean :organizer
  end

  create_table :people, force: true do |t|
    t.integer :person_id
    t.string :last_name
  end

  create_table :contacts, force: true do |t|
    t.integer :contact_id
    t.integer :person_id
  end
end

class Event < ActiveRecord::Base
  	has_many :registrations, -> { includes(person: [:contacts]).order('people.last_name') }, dependent: :destroy,
		inverse_of: :event
	has_many :organizers, -> {where(registrations: {organizer: true})},
		source: :person, through: :registrations

end

class Registration < ActiveRecord::Base
  belongs_to :event
  belongs_to :person
end

class Person < ActiveRecord::Base
  has_many :contacts
end

class Contact < ActiveRecord::Base
  belongs_to :person
end


class BugTest < Minitest::Test
  def test_association_stuff
	event = Event.create!

	person = Person.create!(last_name: "Newton")
	person.contacts << Contact.create!
	person.contacts << Contact.create!
	event.registrations << Registration.create!(person: person, event: event, organizer: true)

	person = Person.create!(last_name: "Euler")
	person.contacts << Contact.create!
	event.registrations << Registration.create!(person: person, event: event, organizer: true)

	# For Rails 6.1 this is 3 (wrong)
	# For Rails 6.0 this was 2 (correct)
	assert_equal event.organizers.count, 2
  end
end```

**Comment by intrip** [comment]
git bisect outlines that https://github.com/rails/rails/pull/39390 introduces the regression.
@kamipo if you agree I'd like to work on a fix

**Comment by intrip** [comment]
@Naturseptime basically the issue happens when building the `AssociationScope`, I'm not sure what could be a good fix for this (maybe to not add the outer join if the `referenced_values` are already joined.

Meanwhile a workaround for this could be to use `preload` instead of `includes` in `:registrations` association , or to append `distinct` on the count `event.organizers.distinct.count`.
