### ISSUE TITLE
Condition to skip cache.fetch saving

### ISSUE THREAD

**Issue by bvicenzo** [rails/rails#41616]
Nowadays when we use the method [cache.fetch](https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-fetch) has an option for skipping the result store `skip_nil` where it does not store the result value if it's nil...

However, there are some cases where the block result is not nil and we don't want to store the result.
Is it possible, we have an option, for example, `skip_if` where we can specify a condition to skip the cache storing like the `skip_nil` does?

### Expected behavior
```rb
is_odd = ->(number) { number.odd? }

cache.fetch('foo', skip_if: is_odd) { 2 }
cache.exist?('foo') # => true

cache.fetch('bar', skip_if: is_odd) { 3 }
cache.exist?('bar') # => false
```

**Comment by lfalcao** [comment]
Based on the [contributing guidelines](https://github.com/rails/rails/blob/3c5cbe84017165b86894601776531990eb93846f/CONTRIBUTING.md), issues are only for bugs and fixes. New features or changes should be first addressed at the mailing list to see feedback.

But you can have the same result doing this:

```ruby
cache.fetch('foo', skip_nil: true) {
  a = 3
  a.odd ? a : nil
}
```

**Comment by bvicenzo** [comment]
@byroot thanks for answering.
I'll consider opening that suggestion there so.
