### ISSUE TITLE
Rails.configuration.active_storage.service_configurations returns nil in development but the correct configs in production

### ISSUE THREAD

**Issue by dorianmariefr** [rails/rails#41636]
### Steps to reproduce

- have a rails app with active storage configured
- run `Rails.configuration.active_storage.service_configurations`

### Expected behavior

It returns the different storage configurations

### Actual behavior

nil in development, correct in production

### System configuration

**Rails version**: Rails 6.1.3

**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

**Comment by dorianmariefr** [comment]
context: I was trying to test a rake task locally from https://www.entreprehero.com/activestorage-migrate-from-local-disk-to-amazon-s3/

**Comment by georgeclaghorn** [comment]
That config is populated [when `ActiveStorage::Blob` is loaded](https://github.com/rails/rails/blob/c431432f93a35530cd0544192b93dabda51f2bf7/activestorage/lib/active_storage/engine.rb#L116). You may need to reference `ActiveStorage::Blob` first in dev to autoload it.

Note:
* This config is undocumented, which means it’s a framework implementation detail, not intended to be used directly.
* The [forum](https://discuss.rubyonrails.org) is the best place to ask for support.
