### ISSUE TITLE
form_with's ability to set enctype="multipart/form-data" is contradicting with its documentation

### ISSUE THREAD

**Issue by radiantshaw** [rails/rails#41632]
The [documentation about the `form_with` helper](https://guides.rubyonrails.org/v6.1/form_helpers.html#uploading-files) is contradicting the actual working of `form_with`. Either the documentation needs to be updated, or there's a bug in the code which makes `form_with` not follow what the documentation says. The issue is regarding the `enctype="multipart/form-data"` HTML attribute/value pair which is automatically set by `form_with` based on the options passed to it.

The documentation says:
> the rendered form's `enctype` attribute **must** be set to "multipart/form-data". If you use `form_with` with `:model`, this is done automatically ... If you use `form_with` without `:model`, you must set it yourself

So it's safe to assume that if the `:url` parameter is used instead of `:model`, then the HTML attribute/value pair in question will not be added.

### Steps to reproduce

Render the following code:
```erb
<%= form_with(url: "/uploads") do |form| %><!-- ... --><% end %>
```

### Expected behavior

The above code should render:
```html
<form action="/uploads" accept-charset="UTF-8" method="post"><!-- ... --></form>
```

### Actual behavior

But it actually renders:
```html
<form enctype="multipart/form-data" action="/uploads" accept-charset="UTF-8" method="post"><!-- ... --></form>
```

### System configuration

**Rails version**: 6.1.3

**Ruby version**: 2.6.6p146

### Additional notes

The documentation also passes the `:multipart` parameter directly. So I checked by passing `multipart: fasle` for whether it will remove the HTML attribute/value pair. But that didn't work. What worked was actually passing the parameter as part of the `:html` hash: `html: { multipart: false }`.

**Comment by p8** [comment]
Hi @radiantshaw, thanks for creating this issue.
I tried reproducing it with a simple form:
```
<%= form_with(url: "/uploads") do |form| %>
  <%= form.text_field :x %>
<% end %>
```
Which results in the following:
```
<form action="/uploads" accept-charset="UTF-8" method="post">
  ....
  <input type="text" name="x" id="x">
</form>
```

Does your form contain a `file_field`?
Using it inside a form_for/form_with block will set the enclosing form's encoding to multipart/form-data.
https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-file_field

**Comment by ghiculescu** [comment]
`enctype="multipart/form-data"` gets added [here](https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/actionview/lib/action_view/helpers/form_helper.rb#L1538) if `options[:multipart]` is true. this can either be set directly (on `form_with`) or it can be inferred from the builder object [here](https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/actionview/lib/action_view/helpers/form_helper.rb#L751).

the default form builder is [here](https://github.com/rails/rails/blob/5aaaa1630ae9a71b3c3ecc4dc46074d678c08d67/actionview/lib/action_view/helpers/form_helper.rb#L1648); `multipart = true` happens if you call `file_field` on it ([here](https://github.com/rails/rails/blob/5aaaa1630ae9a71b3c3ecc4dc46074d678c08d67/actionview/lib/action_view/helpers/form_helper.rb#L2418)).

So it looks like the docs don't match behavior. I will make a PR.

**Comment by radiantshaw** [comment]
@p8 @ghiculescu I did check if it's happening without the `file_field` and yes, it was happening. Although just to be sure I'll check again. Can we not close the issue till then, please? I might not be able to check ASAP. So I'll check in a couple of days. Hope that's okay.

**Comment by radiantshaw** [comment]
@p8 @ghiculescu I did find some time in between and found out that the problem was related to how I was debugging the issue. I was doing:
```erb
<%= form_with(model: model) do |form| %>
  <!-- <%= form.file_field :attribute %> -->
<% end %>
```
and didn't know that the ERB tags were still getting evaluated. Instead I should have done:
```erb
<%= form_with(model: model) do |form| %>
  <%#= form.file_field :attribute %>
<% end %>
```

But I agree that the documentation is still misleading. But now that it's being solved by #41645, it's all good. Thanks for the help everyone. Closing this issue.

**Comment by p8** [comment]
Thanks @radiantshaw !

**Comment by ghiculescu** [comment]
Thanks for clarifying. Erb comments get me all the time!

**Comment by radiantshaw** [comment]
> Thanks for clarifying. Erb comments get me all the time!

IKR. BTW, what about the `html: { multipart: false }` thing? Should I test that as well?

**Comment by ghiculescu** [comment]
@radiantshaw reading through the code it looks like it'll work without the `html` hash. If that's not working as expected can you please share a code sample?

**Comment by radiantshaw** [comment]
Hello @ghiculescu, sure.

I have a form:
```rb
<%= form_with(model: user) do |form| %>
  <%= form.file_field :avatar %>
  <%= form.submit %>
<% end %>
```
which generates:
```html
<form enctype="multipart/form-data" action="/users">
  <input type="file" name="user[avatar]">
  <input type="submit" name="commit" value="Create User">
</form>
```
which is expected because I'm using a file field. And when I pass `multipart: false`, then it still keeps the `enctype` as `"multipart/form-data"`. Which is also expected [as you said](https://github.com/rails/rails/issues/41632#issuecomment-794570892); also evident from [this line of code](https://github.com/ghiculescu/rails/blob/05d0e73eb49f5882089915748a2b2aacc2acbdf9/actionview/lib/action_view/helpers/form_helper.rb#L750). But if you pass `html: { multipart: false }`, then the `enctype` attribute does get removed:
```rb
<%= form_with(model: user, html: { multipart: false }) do |form| %>
  <%= form.file_field :avatar %>
  <%= form.submit %>
<% end %>
```
which generates:
```html
<form action="/users">
  <input type="file" name="user[avatar]">
  <input type="submit" name="commit" value="Create User">
</form>
```

BTW, I did spent some time on debugging this issue, and also found out the source which is causing this. I'd love to contribute to this repo but I first need to understand if this is an actual issue or the intended behaviour.

**Comment by ghiculescu** [comment]
@radiantshaw thanks for the examples. My opinion:

- `multipart: true` and `html: { multipart: true }` should set `enctype="multipart/form-data"` on the form.
- `multipart: false` and `html: { multipart: false }` should ensure that `enctype="multipart/form-data"` is *not* set on the form..
- If you mix the two (`multipart: false` and `html: { multipart: true }` or the inverse), it's undefined behavior, so do whatever is simplest.
- If no multipart attributes are provided, `enctype="multipart/form-data"` is set on the form if `file_field` is called on the form builder.

Ideally we wouldn't support top level `multipart` _and_ `html`-level `multipart`, but removing one would be a breaking change and it probably doesn't hurt much to have both.

(note I'm not a Rails maintainer so you'd need someone else to agree/merge a PR in. but please do give it a go, and I'm happy to review!)
