### ISSUE TITLE
Set Cache-Control: public, no-cache with etag

### ISSUE THREAD

**Issue by collimarco** [rails/rails#41644]
### Steps to reproduce

```
fresh_when etag: @resource, public: true
# => Cache-control: public
# => ETag: ...
```

The problem is that there is no way to add `no-cache`.

**Sometimes you need to use `Cache-Control: public, no-cache`, with an etag, in order to allow caching in the intermediate / proxy caches, while also requiring the caches to re-validate the request with etags.**

For example Cloudflare suggests:

> Cache an asset in client and proxy caches, but prefer revalidation when served:
> Cache-Control: public, no-cache
> https://support.cloudflare.com/hc/en-us/articles/115003206852-Understanding-Origin-Cache-Control

If you don't add `no-cache`, the proxy or the browser may show a stale response to the user (and does not use the etag for re-validation).

### Expected behavior

`fresh_when` should set `Cache-Control: public, no-cache` instead of `Cache-control: public`... otherwise what is the meaning of an etag if it's not used?

Or at least there should be a way (an option) to set `Cache-Control: public, no-cache` when using `fresh_when`. 

### Actual behavior

If we keep the current configuration, browsers use the unpredictable / heuristic behavior in order to decide when to contact the server again, so `etag` is not reliable / is not always checked.

### System configuration

**Rails version**: 6.1

**Comment by byroot** [comment]
> fresh_when should set Cache-Control: public, no-cache instead of Cache-control: public... otherwise what is the meaning of an etag if it's not used?

`public, no-cache` is not the only legitimate configuration. Allowing the browser or proxy to use a stale response if it can't reach the server is sometimes what the users want. It could be argued that it's not the best default, but I see no reason to prevent it.

> there should be a way

I think you are able to do this already by setting `response.cache_control['no-cache'] = true`. 

Now `fresh_when` takes a `public:` option, so maybe it should accept a few more common `cache-control` directives, or simply a `cache_control` option as a shortcut for setting `response.cache_control` manually.

**Comment by collimarco** [comment]
> Allowing the browser or proxy to use a stale response if it can't reach the server is sometimes what the users want.

That is allowed even if you use `no-cache` (see the Cloudflare article for the difference between `no-cache` and `must-revalidate`). 

What we need to prevent by using `no-cache` is the unpredictable HTTP cache heuristic behavior (used by browsers when a max age is not set).

>  setting response.cache_control['no-cache'] = true

I'll try that.

> Now fresh_when takes a public: option, so maybe it should accept a few more common cache-control directives

Yes, I think that would be the perfect place for that option.

**Comment by byroot** [comment]
> That is allowed even if you use `no-cache`

From the article you linked:

> no-cache The no-cache response directive indicates that the response cannot be used to satisfy a subsequent request without successful validation on the origin server. 

> (see the Cloudflare article for the difference between no-cache and must-revalidate).

I don't see which one you are talking about. But either way that's not really the point. The point is there many different sets of cache control that make sense based on your app and HTTP setup. And I don't think the one you propose is so much better that it would justify taking the risk of changing the current default (at the risk of causing caching bug on some users apps).

However I agree that a `cache_control: { }` option would make sense.

**Comment by collimarco** [comment]
> I don't see which one you are talking about. 

See "Examples" on that page: 

- `public, no-cache` => **prefer** revalidation
- `public, no-cache, must-revalidate` => **require** revalidation

>  I agree that a cache_control: { } option would make sense

Ok, great!

**Comment by byroot** [comment]
> See "Examples" on that page:

Hum, seems to me that this cloudflare article is wrong.

https://tools.ietf.org/html/rfc7234#section-5.2.2


> 5.2.2.  Response Cache-Control Directives

> 5.2.2.1.  must-revalidate

>   The "must-revalidate" response directive indicates that once it has
   become stale, a cache MUST NOT use the response to satisfy subsequent
   requests without successful validation on the origin server.

>   The must-revalidate directive is necessary to support reliable
   operation for certain protocol features.  In all circumstances a
   cache MUST obey the must-revalidate directive; in particular, if a
   cache cannot reach the origin server for any reason, it MUST generate
   a 504 (Gateway Timeout) response.

>   The must-revalidate directive ought to be used by servers if and only
   if failure to validate a request on the representation could result
   in incorrect operation, such as a silently unexecuted financial
   transaction.

> 5.2.2.2.  no-cache

>   Argument syntax:

>      #field-name

>   The "no-cache" response directive indicates that the response **MUST
   NOT be used to satisfy a subsequent request without successful
   validation on the origin server**.  This allows an origin server to
   prevent a cache from using it to satisfy a request without contacting
   it, even by caches that have been configured to send stale responses.

>   If the no-cache response directive specifies one or more field-names,
   then a cache MAY use the response to satisfy a subsequent request,
   subject to any other restrictions on caching.  However, any header
   fields in the response that have the field-name(s) listed MUST NOT be
   sent in the response to a subsequent request without successful
   revalidation with the origin server.  This allows an origin server to
   prevent the re-use of certain header fields in a response, while
   still allowing caching of the rest of the response.

>   The field-names given are not limited to the set of header fields
   defined by this specification.  Field names are case-insensitive.

**Comment by intrip** [comment]
I'll work on a PR to add a `cache_control: { }` option.
