### ISSUE TITLE
Is `logger` method introduced by ActiveSupport::Configurable public API?

### ISSUE THREAD

**Issue by mtsmfm** [rails/rails#41647]
`ActionController::Base` and `ActiveRecord::Base` have `logger` method because it includes `ActiveSupport::Configurable` and it sets logger.

In Rails guides, in some place it uses `logger` directly:

https://github.com/rails/rails/blob/dc7817cb42768ad01d69d5f9b0023f556760cb06/guides/source/debugging_rails_applications.md#L161-L167

And other uses `Rails.logger`:

https://github.com/rails/rails/blob/dc7817cb42768ad01d69d5f9b0023f556760cb06/guides/source/upgrading_ruby_on_rails.md#L193-L200

I'd like to know which API is preferable and considered as a public API to prepare possibility of breaking changes in the future.

If my understanding is correct, all methods listed in https://api.rubyonrails.org/ are considered as public API but I can't find `ActionController::Base#logger`, `ActiveRecord::Base#logger` and `Rails.logger`.

**Comment by georgeclaghorn** [comment]
I think those `logger` methods are intended to be public API. Would you be willing to open a PR to add docs?

**Comment by mtsmfm** [comment]
I've found `ActiveRecord::Core.logger` is documented on source code but not appeared because currently RDoc doesn't support comments within DSL.

https://github.com/rails/rails/blob/168ddaa08a63cd956bb7c3ba10be1a7ae36d4ee2/activerecord/lib/active_record/core.rb#L14-L20

I sent a PR to support such a case.

https://github.com/ruby/rdoc/pull/795

**Comment by zzak** [comment]
If `:singleton-method:` is not showing up and we're stuck waiting for #795 I wonder if there is an alternative. I remember RDoc used to provide a way to tag a method in the comment 🤔

**Comment by mtsmfm** [comment]
@zzak In my understanding, comments within module level DSL aren't documented well by RDoc.

Let's say we have the following Ruby code foo.rb:

```ruby
module A
  included do
    ##
    # :singleton-method: foo
    # Hello
  end

  ##
  # :singleton-method: bar
  # Hello
end
```

Generated result only contains `A.bar`:

```
$ rdoc foo.rb 
Parsing sources...
100% [ 1/ 1]  foo.rb

Generating Darkfish format into /app/doc...

  Files:      1

  Classes:    0 (0 undocumented)
  Modules:    1 (1 undocumented)
  Constants:  0 (0 undocumented)
  Attributes: 0 (0 undocumented)
  Methods:    1 (0 undocumented)

  Total:      2 (1 undocumented)
   50.00% documented

  Elapsed: 0.0s
```

```
$ cat doc/js/search_index.js
var search_data = {"index":{"searchIndex":["a","bar()"],"longSearchIndex":["a","a::bar()"],"info":[["A","","A.html","",""],["bar","A","A.html#method-c-bar","","<p>Hello\n"]]}}%
```

To be exact, it has strange behavior.

<details>
<summary>
If we put two comments within DSL, only the last one is documented.
</summary>

```ruby
module A
  included do
    ##
    # :singleton-method: foo
    # Hello

    ##
    # :singleton-method: foo2
    # Hello
  end
end
```

```
$ rdoc foo.rb               
Parsing sources...
100% [ 1/ 1]  foo.rb

Generating Darkfish format into /app/doc...

  Files:      1

  Classes:    0 (0 undocumented)
  Modules:    1 (1 undocumented)
  Constants:  0 (0 undocumented)
  Attributes: 0 (0 undocumented)
  Methods:    1 (0 undocumented)

  Total:      2 (1 undocumented)
   50.00% documented

  Elapsed: 0.0s
```

```
$ cat doc/js/search_index.js
var search_data = {"index":{"searchIndex":["a","foo()"],"longSearchIndex":["a","a::foo()"],"info":[["A","","A.html","",""],["foo","A","A.html#method-c-foo","","<p>Hello\n"]]}}%
```
</details>

<details>
<summary>
If we call a method just after a comment within DSL, nothing is documented. (That's why current codes aren't documented even they have comments)
</summary>

```ruby
module A
  included do
    ##
    # :singleton-method: foo
    # Hello
    foo

    ##
    # :singleton-method: foo2
    # Hello
    foo2
  end
end
```

```
$ rdoc foo.rb               
Parsing sources...
100% [ 1/ 1]  foo.rb

Generating Darkfish format into /app/doc...

  Files:      1

  Classes:    0 (0 undocumented)
  Modules:    1 (1 undocumented)
  Constants:  0 (0 undocumented)
  Attributes: 0 (0 undocumented)
  Methods:    0 (0 undocumented)

  Total:      1 (1 undocumented)
    0.00% documented

  Elapsed: 0.0s
```

```
$ cat doc/js/search_index.js
var search_data = {"index":{"searchIndex":["a"],"longSearchIndex":["a"],"info":[["A","","A.html","",""]]}}%  
```
</details>

**Comment by zzak** [comment]
Sorry I meant to ping ruby/rdoc#795.

@mtsmfm I think you found a bug in RDoc, so let's wait and see what @aycabta says. 🙏
