### ISSUE TITLE
slow perfomance method `sum` for enumerable, array

### ISSUE THREAD

**Issue by ermolaev** [rails/rails#41650]
### Steps to reproduce
```ruby
> irb
require 'benchmark/ips'
num_arr = (1..10).to_a;
C = Struct.new(:v);
obj_arr = (1..10).map { |i| C.new(i) };

Benchmark.ips do |x|
  x.report("sum num_arr") do |n|
    while n > 0
      num_arr.sum
      n-=1
    end
  end
  x.report("sum obj_arr") do |n|
    while n > 0
      obj_arr.sum(&:v)
      n-=1
    end
  end

  x.compare!
end;
Calculating -------------------------------------
         sum num_arr     17.615M (± 4.4%) i/s -     88.270M in   5.021204s
         sum obj_arr      2.645M (± 3.8%) i/s -     13.292M in   5.033431s
```

```ruby
> rails c
require 'benchmark/ips'
num_arr = (1..10).to_a;
C = Struct.new(:v);
obj_arr = (1..10).map { |i| C.new(i) };

Benchmark.ips do |x|
  x.report("sum num_arr") do |n|
    while n > 0
      num_arr.sum
      n-=1
    end
  end
  x.report("sum obj_arr") do |n|
    while n > 0
      obj_arr.sum(&:v)
      n-=1
    end
  end

  x.compare!
end;

Calculating -------------------------------------
         sum num_arr      5.277M (± 4.0%) i/s -     26.518M in   5.034190s
         sum obj_arr    911.786k (± 5.6%) i/s -      4.626M in   5.090562
```

### Expected behavior
speed should be equal

### Actual behavior
in rails app code very slow
```
sum num_arr 17.6/5.2 => 3.3846153846153846
sum obj_arr 2645/911.0 => 2.903402854006586
```

### System configuration
**Rails version**: 6.0

**Ruby version**: 2.5

I think we may remove this monkey patch

https://github.com/rails/rails/blob/4607f13c88fdc773a3ee69101bcb6ebe41ed20ce/activesupport/lib/active_support/core_ext/enumerable.rb#L53

https://github.com/rails/rails/blob/4607f13c88fdc773a3ee69101bcb6ebe41ed20ce/activesupport/lib/active_support/core_ext/enumerable.rb#L265

### The next examples very strange
https://github.com/rails/rails/blob/4607f13c88fdc773a3ee69101bcb6ebe41ed20ce/activesupport/lib/active_support/core_ext/enumerable.rb#L47
replaced by `['foo', 'bar'].join`

https://github.com/rails/rails/blob/4607f13c88fdc773a3ee69101bcb6ebe41ed20ce/activesupport/lib/active_support/core_ext/enumerable.rb#L48
replaced by `[[1, 2], [3, 1, 5]].flatten`

---

method sum added in rails in the 2006 year https://github.com/rails/rails/commit/236c7325df4ca2783c92dffc0f0b9592f822d95a

but ruby added this method in version 2.4, and now rails require minimum ruby version 2.5, we may remove it from rails

**Comment by ermolaev** [comment]
@rafaelfranca, maybe you can watch this PR?

**Comment by ghiculescu** [comment]
Closed by https://github.com/rails/rails/pull/42080
