### ISSUE TITLE
ActiveRecord::Tasks::DatabaseTasks.purge fails if the database doesn't exist

### ISSUE THREAD

**Issue by saveriomiroddi** [rails/rails#41658]
### Steps to reproduce

- create a standard rails application
- drop the databases
- execute the `ActiveRecord::Tasks::DatabaseTasks.purge(config)`, with any configuration

### Expected behavior

The operation should succeed.

### Actual behavior

An error is raised: `Mysql2::Error: Unknown database 'my_db_name'`

### System configuration

Rails 6.0.3.5.

### Diagnosis and fix

The `:purge` API establishes a connection assuming that a db is present:

```ruby
      def purge
        establish_connection configuration
        connection.recreate_database configuration["database"], creation_options
      end
```

the method invoked (`:configuration`) is not the correct one to invoke when the presence of a db is not guaranteed; see for example the `:create` API:

```ruby
      def create
        establish_connection configuration_without_database
        connection.create_database configuration["database"], creation_options
        # etc etc
      end
```

The fix is therefore to use the configuration that doesn't assume a db to be present:

```ruby
      def purge
        establish_connection configuration_without_database
        connection.recreate_database configuration["database"], creation_options
      end
```

I've inspected the source code, and this applies to Rails 6.0.x and 6.1.x (with non-semantic differences); didn't inspect Rails 5.2.

**Comment by eileencodes** [comment]
> The operation should succeed.

I don't think this is right. We can't purge a db that doesn't exist. The same error gets raised for creating a database that doesn't exist. I don't think this is a bug, this is correct, intended, behavior.

**Comment by saveriomiroddi** [comment]
> > The operation should succeed.
> 
> I don't think this is right. We can't purge a db that doesn't exist. The same error gets raised for creating a database that doesn't exist. I don't think this is a bug, this is correct, intended, behavior.

It makes sense in isolation, but I see a problem in the mixed semantics of the context:

- the `drop` API doesn't raise an error if the database doesn't exist; it instead prints the message `Database 'mydb' does not exist` and continues
- the `create` API has the same behavior (when the db exists); it prints `Database 'mydb' already exists`

So, my definition of "succeed" is vague :) More precisely, I think it's matter of consistency - it would be consistent to print a message and follow up rather than raising an error, like the `create`/`drop` APIs do (or adapt those two to the same behavior).

This is a minor (perceived) issue of course - ultimately, `purge` can pretty much replaced with subsequent `create` and `drop` invocations :)
