### ISSUE TITLE
ActiveRecord::Result#column_types is often missing data

### ISSUE THREAD

**Issue by terracatta** [rails/rails#41651]
### Regression in ActiveRecord::Result column_types

In my app (which uses PostgreSQL) I have several reporting features that construct TEMP DB views on the fly and query them with ActiveRecord's `exec_query` functionality. When I run these queries, I depend upon the values in the `column_types` attribute of the [ActiveRecord::Result object ](https://api.rubyonrails.org/classes/ActiveRecord/Result.html) to contain all of the column names and associated types.

After upgrading to Rails 6.1 I have noticed most of the time, the `columns_types` hash is now empty. This seems to be caused by this commit, specifically on the line that I have highlighted. https://github.com/rails/rails/commit/71e45582b794d7cdcbd72a93dc2f3c8665859653#diff-e6fd03cad5e3437c76b6c5db106359124dc9feab8341ade39b9ae54af001fac9R58

This appears to skip adding certain items to `column_types`. From what I can see, it's clear this was an intentional decision, and that the absence of data in meaningful in some way to other parts of AR. With that said, I believe this attribute is a public-enough API surface that it should always reflect all columns in the query.

As you might expect, it's hard to understand the context of a SQL query result without knowing what data types are for each column. I think we should keep that context in the `ActiveRecord::Result` object and restore the original behavior.

### Steps to reproduce

1. In a rails console run `result = ActiveRecord::Base.connection.exec_query("SELECT 1 AS test")`
1. Run `result.column_types`

### Expected behavior
I expect that `result.column_type` will return something like `=> {"test"=>#<ActiveModel::Type::Integer:0x00007fc9fbb6fe50 @limit=4, @precision=nil, @range=-2147483648...2147483648, @scale=nil>}`

### Actual behavior
After this commit 71e45582b794d7cdcbd72a93dc2f3c8665859653, `result.column_type` returns `{}`

### System configuration
**Rails version**:Rails 6.1.3
**Ruby version**: ruby 2.7.2p137

**Comment by thiagogabriel** [comment]
I'm having something that looks similar to this problem in a calculated attribute. I have the correct behavior when I access like this: `record.attributes_before_type_cast["test"]`.

**Comment by BobbyMcWho** [comment]
I believe I'm also experiencing this issue, it worked on 6.0, is now broken on 6.1
