### ISSUE TITLE
Multiple attachment files are not persisted to storage service when attached separately within a transaction

### ISSUE THREAD

**Issue by reshleman** [rails/rails#41661]
Hello!

I've encountered an issue with multiple ActiveStorage attachments that occurs when calling `#attach` more than once on the same model within a transaction.

Specifically, the `ActiveStorage::Attachment` objects are all created as expected, however all attachments except the last silently fail to be persisted to the storage service. Attempting to access these files (e.g., by calling `#download`) throws `ActiveStorage::FileNotFoundError`.

This issue does not appear to occur when attaching multiple attachments in a single call to `#attach` within a transaction, nor does it occur with multiple calls to `#attach` that are not wrapped in a transaction.

I found a similar recent (but closed) bug related to ActiveStorage attachments and transactions which could be related: https://github.com/rails/rails/issues/40630

Thanks!

### Steps to reproduce

[This gist](https://gist.github.com/reshleman/25edc7854e9d8a262e6fff9e5a8f26ab) contains a reproduction script with a failing test case (along with 3 passing test cases which do not meet all the conditions to trigger the issue).

### Expected behavior

Multiple calls to `#attach` inside a transaction persist all attached files to the storage service.

### Actual behavior

Multiple calls to `#attach` inside a transaction creates `ActiveStorage::Attachment` objects, but only the last attached file is persisted to the storage service.

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 2.6.5p114

**Comment by riku1027** [comment]
Are there any plans to fix it? I am also using 6.1.
