### ISSUE TITLE
Records created from build api can't be saved

### ISSUE THREAD

**Issue by dgonzalezvts** [rails/rails#41665]
### Steps to reproduce
We have a problem saving two objects that are associated and created in memory through the build api. For example, 

```
class Foo
  has_many :bars
end

class Bar
  belongs_to :foo
end

foo = Foo.new
foo.build(<attrs>)
foo.save
```

foo.save fails b/c the associated bar can't figure out how to set the foreign key on itself.

This breaks on the rails v6.0.3.5 tag but is fixed on the rails 6-0-stable branch. I wanted to ask if the Rails team could release a tag off the stable branch that includes at least the history up to and including the d918be6e7f61fa6a6fea081ca23f17cecd657c3f commit where I know this is solved?

### Expected behavior
We should be able to save two objects that are associated with each other where the has_many was created through the build api.

### Actual behavior
We are unable to call save in this situation. The example I gave is a simplication. My use case has some more complicated logic in the association that causes this functionality to break on the rails v6.0.3.5 tag, but I've been able to confirm it works on the rails 6-0-stable branch.

### System configuration
**Rails version**: Rails 6.0, Commit: d918be6e7f61fa6a6fea081ca23f17cecd657c3f

**Ruby version**: Ruby 2.6.5

**Comment by eileencodes** [comment]
> My use case has some more complicated logic in the association that causes this functionality to break on the rails v6.0.3.5 tag, but I've been able to confirm it works on the rails 6-0-stable branch.

If it works on the 6-0-stable branch then it will be in the next release. We can't re-release 6.0.3.5. So it sounds like this isn't a bug anymore and we can close this?

**Comment by dgonzalezvts** [comment]
do you know when 6.0.4 will be released? and yes, this can be closed.

**Comment by eileencodes** [comment]
Probably in a couple of weeks - we don't have a set timeline.
