### ISSUE TITLE
rails-ujs does not respect "data-turbo=false" when the "data-method" attribute is present in an <a> tag

### ISSUE THREAD

**Issue by Xenofex** [rails/rails#41676]
rails-ujs' [handleMethod](https://github.com/rails/rails/blob/520bb79411e96eeb14ec5d2c7431ca09ea6c1b6e/actionview/app/assets/javascripts/rails-ujs/features/method.coffee#L7) function creates an anonymous form, append which. to the `document.body`. In this process, any attributes on the original `<a>` tag is lost. In my case, `data-turbo="false"`. This makes rails-ujs `<a>` tags are always subject to turbolinks' effect.

The reason why I need `data-turbo="false"` may be a bug in `Turbo` drive (Turbolinks), which I'm atempting to avoid:

When I create `<a>` tag using 

```ruby
link_to 'Sign Out',  '/admin/sessions/sign_out', method: :delete
```
it always fails because Turbolinks swallows the 401 response.

### Steps to reproduce

```ruby
link_to 'Sign Out',  '/admin/sessions/sign_out', method: :delete
```

With Turbolinks enabled on the page

### Expected behavior

The user should be redirected (after signed out) to the page that the action specifies.

### Actual behavior

The user stays on the current page. The response has a 401 status, Turbolinks treats it as an error, refuses to place the content on the page. Due to the current implementation of rails-ujs, there is no way to tell Turbolinks to skip only this link.

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 3.0.0

**Comment by Xenofex** [comment]
Not sure the best way to fix this. For me I'd like to provide a `data-before-navigation` which is a callback function, to the rails-ujs links. In this function, the developer is able to do some customization to the generated form before submission. Or the Turbolinks `data-turbo` attribute should be copied by default.

**Comment by p8** [comment]
Hi @Xenofex,

Rails UJS will probably be replaced with Turbo in Rails 7.0, so I don't think it will get big updates.
Instead of using `link_to` you might have more luck with `button_to` which creates a form instead of an anchor tag:

```
button_to 'Sign Out',  '/admin/sessions/sign_out', method: :delete
```

**Comment by p8** [comment]
You maybe also need to `include Turbolinks:Controller`
https://github.com/heartcombo/devise/blob/45b831c4ea5a35914037bd27fe88b76d7b3683a4/lib/generators/templates/devise.rb#L299-L304

**Comment by Xenofex** [comment]
Hello @p8, thanks for the reply. I do use turbo instead of turbolinks in my current project, just so used to turbolinks for years. Anyway I'll try your work around. Though this is really something to do with the `rails-ujs` part, isn't it? Or you think we should use `button_to` as a workaround?

`link_to` used to create a form in place, until `rails-ujs` came out. If you have any directions I can work on this and make a PR. Just not sure whether good or what to expose from `rails-ujs`'s perspective.

**Comment by Xenofex** [comment]
> You maybe also need to `include Turbolinks:Controller`
> https://github.com/heartcombo/devise/blob/45b831c4ea5a35914037bd27fe88b76d7b3683a4/lib/generators/templates/devise.rb#L299-L304

Thanks for finding this for me. However this is no longer valid. The `Turbolinks::Controller` module belongs to turbolinks-classic, which is deprecated before turbolinks. In current turbolinks (not turbo), I could not find an equivalent module. There is only TypeScript code there, and the original `Turbolinks::Controller` module does some work in the controller. Therefore xhr requests are properly handled.

For the `button_to` method, it works for me, with only one caveat: if you put a `data-confirm`, put it on the `form`, e.g.:

```slim
= button_to destroy_admin_biz_user_session_path,
  class: 'nav-link dropdown-item',
  method: :delete,
  form: {data: { confirm: "Are you sure to sign out?", turbo: false }} do
  i.fa.fa-exit
  | Sign Out

```

The `data-confirm` is explicity ignored for a button in a form by `rails-ujs`.

**Comment by Xenofex** [comment]
Ah I misread your reply. You wrote that the entire `rails-ujs` is gonna be replaced by `Turbo`. Then I'll stick to the `button_to` method for this project. Thank you so much for your help!

**Comment by p8** [comment]
@Xenofex You're welcome! 😄
