### ISSUE TITLE
Rails install error native extension.

### ISSUE THREAD

**Issue by Neha-chhajed** [rails/rails#41678]
Hello, 
I am using the Ruby version 2.7.2 and while installing rails I got these error -

ERROR: Failed to build gem native extension.

what is mean native extension?

So, please can anyone help me.

Thank you,
Neha

**Comment by louim** [comment]
Hi @Neha-chhajed,

This is not enough information to provide help. Since the problem is probably related to your computer setup (OS, installed libraries, etc), it would be a better fit for StackOverflow.
