### ISSUE TITLE
Consistenly respond to `*/*`

### ISSUE THREAD

**Issue by abitrolly** [rails/rails#41683]
When Google Translate requested Rails pages in https://github.com/minsk-hackerspace/hackerspace.by/issues/470 the Rails returned JSON instead of HTML to it. [The page controller](https://github.com/minsk-hackerspace/hackerspace.by/blob/master/app/controllers/projects_controller.rb) uses [implicit render](https://github.com/rails/rails/blob/v6.0.3.5/actionpack/lib/action_controller/metal/implicit_render.rb), and there are [JSON and HTML templates](https://github.com/minsk-hackerspace/hackerspace.by/tree/master/app/views/projects) for each view. 

Headers sent by Google Translate.

connection | close
-- | --
accept-encoding | gzip,deflate,br
user-agent | Mozilla/5.0 (X11;  Fedora; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0,gzip(gfe)
accept | */*
host | webhook.site
via | 1.0 translate.google.com TWSFE / 9.0
content-length |  
content-type |  

### Steps to reproduce

1. git clone https://github.com/minsk-hackerspace/hackerspace.by
2. cd hackerspace.by; git checkout 39f365c0e7a9f99e670f7f5695c198ada80229f3
3. Create project
4. Feed the page to Google Translate

### Expected behavior

Expected implicit render to prefer HTML first like [explicit `render` does](https://guides.rubyonrails.org/layouts_and_rendering.html#options-for-render).

### Actual behavior

JSON is fed to Google Translate.

### System configuration

**Rails version**: 6.0.3.5

**Ruby version**: 2.7

**Comment by p8** [comment]
Hi @abitrolly,

This might be related to the responders gem, which is included in the Gemfile...
Does it still occur if you disable the gem?

**Comment by abitrolly** [comment]
@p8 I am not sure what `responders` is for. Seems like it is not used, but when I removed it it is being pulled again by `devise`.

**Comment by lfalcao** [comment]
@abitrolly can you provide a page where this happens in production?

Tried with curl here and worked.
`curl -A "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0,gzip(gfe)" --compressed -i -H "Accept: */*" https://hackerspace.by/projects/42 -v`

**Comment by abitrolly** [comment]
@lfalcao it was fixed in production with this hack - https://github.com/minsk-hackerspace/hackerspace.by/pull/483/files

You need to rollback to revision I specified to repeat the behavior with checkout.

**Comment by abitrolly** [comment]
I am sure it was pretty repeatable at that time. Maybe I could build a Docker container later. No ETA though.

**Comment by abitrolly** [comment]
I definitely need to create an image for that and upload it. Hopefully I can do this this week.
