### ISSUE TITLE
Doc help: What's the Problem when Executor wrap Rack API

### ISSUE THREAD

**Issue by xuxiangyang** [rails/rails#41685]
@matthewd Thanks for your jobs with Executor, I Have a problem with under sentence in  [Threading and Code Execution in Rails](https://github.com/rails/rails/blob/main/guides/source/threading_and_code_execution.md) Doc

```
If it's impractical to wrap the application code in a block (for example, the Rack API makes this problematic), you can also use the run! / complete! pair:
```

I can not understand what's the problem when use wrap with RACK API, would you like show some examples? Thanks

**Comment by rafaelfranca** [comment]
Please use https://discuss.rubyonrails.org/ for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
