### ISSUE TITLE
Couldn't drop database for some reason

### ISSUE THREAD

**Issue by LightningRpper** [rails/rails#41689]
undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007fffeec19cd8>
Did you mean?  configuration_hash
Couldn't drop database 'app_development'
rails aborted!
NameError: undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007fffeec19cd8>
Did you mean?  configuration_hash

I'm trying to migrate and reset the database to get it to work as an app. What's going on here and how can I fix it?

**Comment by eugeneius** [comment]
This looks like the same issue as https://github.com/rails/rails/issues/41047, which was resolved by upgrading the pgreset gem. If you're using that gem, can you try again after upgrading it? Otherwise, can you post the output of `bundle exec rails db:reset --trace`?

**Comment by LightningRpper** [comment]
** Invoke db:reset (first_time)
** Invoke db:drop (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke db:load_config
** Execute db:check_protected_environments
** Execute db:drop
** Invoke db:drop:_unsafe (first_time)
** Invoke db:load_config
** Execute db:drop:_unsafe
undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007fffc1de66b0>
Did you mean?  configuration_hash
Couldn't drop database 'app_development'
rails aborted!
NameError: undefined local variable or method `configuration' for #<ActiveRecord::Tasks::PostgreSQLDatabaseTasks:0x00007fffc1de66b0>
Did you mean?  configuration_hash
/.rvm/gems/ruby-2.6.5@app/gems/pgreset-0.1.1/lib/pgreset.rb:14:in `drop'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3/lib/active_record/tasks/database_tasks.rb:199:in `drop'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3/lib/active_record/tasks/database_tasks.rb:214:in `block in drop_current'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3/lib/active_record/tasks/database_tasks.rb:506:in `block (2 levels) in each_current_configuration'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3/lib/active_record/tasks/database_tasks.rb:503:in `each'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3/lib/active_record/tasks/database_tasks.rb:503:in `block in each_current_configuration'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3/lib/active_record/tasks/database_tasks.rb:502:in `each'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3/lib/active_record/tasks/database_tasks.rb:502:in `each_current_configuration'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3/lib/active_record/tasks/database_tasks.rb:214:in `drop_current'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3/lib/active_record/railties/databases.rake:68:in `block (2 levels) in <main>'
/.rvm/gems/ruby-2.6.5@poppy/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/.rvm/gems/ruby-2.6.5@poppy/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/.rvm/gems/ruby-2.6.5@poppy/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/.rvm/gems/ruby-2.6.5@poppy/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/.rvm/gems/ruby-2.6.5@poppy/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/.rvm/gems/ruby-2.6.5@poppy/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.1.3/lib/active_record/railties/databases.rake:64:in `block (2 levels) in <main>'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/.rvm/gems/ruby-2.6.5@poppy/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.1.3/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.1.3/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/.rvm/gems/ruby-2.6.5@app/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.1.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.1.3/lib/rails/command.rb:52:in `invoke'
/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.1.3/lib/rails/commands.rb:18:in `<main>'
/.rvm/gems/ruby-2.6.5@app/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/.rvm/gems/ruby-2.6.5@app/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/.rvm/gems/ruby-2.6.5@app/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/.rvm/gems/ruby-2.6.5@app/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/.rvm/gems/ruby-2.6.5@app/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/workspace/app/bin/rails:5:in `<top (required)>'
/.rvm/gems/ruby-2.6.5@app/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/.rvm/gems/ruby-2.6.5@app/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/.rvm/gems/ruby-2.6.5@app/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/.rvm/gems/ruby-2.6.5@app/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/.rvm/gems/ruby-2.6.5@app/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/.rvm/gems/ruby-2.6.5@app/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/.rvm/gems/ruby-2.6.5@app/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/workspace/app/bin/spring:10:in `require'
/workspace/app/bin/spring:10:in `block in <top (required)>'
/workspace/app/bin/spring:7:in `tap'
/workspace/app/bin/spring:7:in `<top (required)>'
bin/rails:2:in `load'
bin/rails:2:in `<main>'
Tasks: TOP => db:drop:_unsafe

This was the output of when i run the command you showed.

**Comment by eugeneius** [comment]
You need to upgrade the pgreset gem.

**Comment by LightningRpper** [comment]
@eugeneius  How? What I've found on the issue is very unclear.

**Comment by eugeneius** [comment]
`bundle update pgreset` should do it.
