### ISSUE TITLE
`rails s -p 5000` ignores `ssl_bind` option in Puma config

### ISSUE THREAD

**Issue by aergonaut** [rails/rails#41682]
### Steps to reproduce

I have created an example repo that can be used to observe the behavior I'm seeing: https://github.com/aergonaut/puma_ssl_bind

I am using mkcert for HTTPS development on my localhost. To get Puma to respond to the HTTPS connection, I added a `ssl_bind` option to my `config/puma.rb` like [this](https://github.com/aergonaut/puma_ssl_bind/commit/30f8f23950a949e9cea1a147e252a2aecfac950a). This works great, however I noticed a problem with `rails s` when I specify a port on the command line.

If I run `rails s` (and use the default port), everything works great.

But if I run `rails s -p 5000`, using the `-p` option to specify a different port, Rails ignores the `ssl_bind` option in my Puma config. All other options from the Puma config are applied, it's just the `ssl_bind` option that is discarded.

Maybe there is another way that I should use to specify alternative ports, or to specify the SSL config?

### Expected behavior

I expect Rails to keep all of my config options from my `config/puma.rb` file, and layer any other options from the command line on top.

Since I only specified a different port, I would expect the `ssl_bind` to remain, and just the HTTP binding to change.

### Actual behavior

`ssl_bind` is ignored.

### System configuration
**Rails version**: Rails 6.1.3

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

**Comment by p8** [comment]
Hi @aergonaut,
Does it work correctly if you start with puma directly?
```https://github.com/rails/rails/issues/25700```
See: https://github.com/rails/rails/issues/25700

**Comment by aergonaut** [comment]
@p8 Thanks for the response.

If I start Puma directly like you indicate, I see the same behavior:

Without `--port`

```
$ bundle exec puma            
Puma starting in single mode...
* Puma version: 5.2.2 (ruby 2.7.2-p137) ("Fettisdagsbulle")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 40000
* Listening on http://0.0.0.0:3000
* Listening on ssl://0.0.0.0:3001?cert=/Users/chris/local-certs/localhost.pem&key=/Users/chris/local-certs/localhost-key.pem&verify_mode=none
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2021-03-16 13:25:55 -0700 ===
- Goodbye!
```

With `--port 5000`

```
$ bundle exec puma --port 5000
Puma starting in single mode...
* Puma version: 5.2.2 (ruby 2.7.2-p137) ("Fettisdagsbulle")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 40043
* Listening on http://0.0.0.0:5000
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2021-03-16 13:26:07 -0700 ===
- Goodbye!
```

Thank you for pointing out #25700. It does sound like something similar.

**Comment by p8** [comment]
You might fix it by passing an ENV variable:
```
ssl_bind "0.0.0.0",  ENV.fetch("SSL_PORT") { 3001 }, {
  key: File.expand_path("~/local-certs/localhost-key.pem").to_s,
  cert: File.expand_path("~/local-certs/localhost.pem").to_s,
  verify_mode: "none"
}
```

`rails s SSL_PORT=5000`

**Comment by aergonaut** [comment]
Thanks @p8.

So I guess this is because when I use the `-p` option to `rails s`, that overrides the port binding from the config file, because Puma prefers options passed in on the CLI. That's what [this comment](https://github.com/rails/rails/issues/41682#issuecomment-230506400) seems to state.

This is expected behavior, although it's not my _preferred_ behavior 😉
