### ISSUE TITLE
Question: Any chance to release 6.1.x that includes fix for regression on optimistic locking?

### ISSUE THREAD

**Issue by eitoball** [rails/rails#41695]
### Description

As described in #40786, there has been regression on optimistic locking in 6.1. And revert commit (d24dc88dad0577f86efbd91cb9295f957f150b2d, #41049) has been in master branch, but not in 6.1 branch.
Will this revert commit be in 6.1 release? Should we wait until 6.2 release?

**Comment by kamipo** [comment]
That is already released as 6.1.2.

https://github.com/rails/rails/commits/v6.1.2/activerecord/lib/active_record/locking/optimistic.rb

**Comment by eitoball** [comment]
Thank you!
