### ISSUE TITLE
ActionMailer generated view templates variables cause error

### ISSUE THREAD

**Issue by cameronbarker** [rails/rails#41719]
### Steps to reproduce
1. Generate a new mailer `rails g mailer Generic email`
2. Start rails server
3. Go to http://localhost:3000/rails/mailers/generic/email

### Expected behavior
When we go to http://localhost:3000/rails/mailers/generic/email it should show the templated message.

### Actual behavior
When we got to http://localhost:3000/rails/mailers/generic/email it shows an error:
```
ActionView::Template::Error (undefined local variable or method `class_name' for #<ActionView::Base:0x000000000294c8>
```
If we fix that error by calling `controller.class.to_s` then `@action` isn't recognized either. I fixed `@action` by changing it to `action_name`.

### System configuration
**Rails version**: 6.1.3
**Ruby version**: 2.7.2p137

**Comment by abhaynikam** [comment]
@cameronbarker Tried to reproduce the issue with the mentioned steps on Rails `6.1.3` and Rails `master`. Could not re-produce the error you mentioned. If you could add more details on how to reproduce the issue or create a sample application with the issue it might help trace the error 😊 

Also, the mailer preview are generated on `http://localhost:3000/rails/mailers/generic_mailer/email` instead. URL should have `generic` -> `generic_mailer`.
