### ISSUE TITLE
ActionDispatchIntegrationTest body from request helper with raw JSON is not in params but only params(:_json)

### ISSUE THREAD

**Issue by klyonrad** [rails/rails#41724]
### Steps to reproduce

```ruby
RSpec.describe 'raw json test', type: :request do # should be the ActionDispatch::IntegrationTest
def authorization_header; {}; end

post '/some_endpoint.json', as: :json, headers: authorization_header, params: { key: 'value' }.to_json
end
```

### Expected behavior

I expected that the test rails controller parses the given JSON string and maps it to the params. So that in this example the controller can access `params(:key)`

### Actual behavior

Instead the params are kind of empty. What gets populated is a `_json` key.

```
{"_json"=>"{\"key\":\"value\"}", "format"=>"json", "controller"=>"some_controller, "action"=>"some_endpoint}
```

### System configuration

**Rails version**:

6.0.3.5

**Ruby version**:

2.6.6

----

I have searched through the interwebs about this, so sorry for keeping the report very short. Maybe I am trying something very wrong or something this behaviour is intended like this.
I found it awkward that IntegrationDispatchTest / Requst specs promise to do less mocking than `ControllerTest` and here they cannot test the reality of the data input format.
Background: I added a JSON field to the strong params list but it was filtered out, when in the test I sent the input in a nested hash, so I wanted to test all the params coming in as raw JSON.

So thanks in advance for the consideration

**Comment by p8** [comment]
I think you can just do the following:
```
  it "creates a Widget and redirects to the Widget's page" do
    headers = { "CONTENT_TYPE" => "application/json" }
    post "/widgets", :params => '{ "widget": { "name":"My Widget" } }', :headers => headers
    expect(response).to redirect_to(assigns(:widget))
  end
```
https://relishapp.com/rspec/rspec-rails/v/5-0/docs/request-specs/request-spec#providing-json-data

These questions are better asked in the Rails forum: https://discuss.rubyonrails.org/
