### ISSUE TITLE
NoEnvironmentInSchemaError when migration fails

### ISSUE THREAD

**Issue by vanboom** [rails/rails#41732]
This database environment restriction is causing a lot of angst as we attempt to upgrade our app from 4.2 to 5.2. 

### Steps to reproduce
1. Create a migration with a syntax error. 
2. Attempt `rake db:create db:migrate RAILS_ENV=development`
3. The migration fails with error. 
4. After fixing the migration, the ActiveRecord::NoEnvironmentInSchemaError appears. 

### Expected behavior
The environment should be loaded even if the migration fails. 

`rake db:migrate RAILS_ENV=development` should succeed after the migration is corrected 

### Actual behavior
```
Environment data not found in the schema. To resolve this issue, run: 

        bin/rails db:environment:set RAILS_ENV=development
```

### System configuration
**Rails version**: 5.2.4.5
**Ruby version**: 2.5.0

(2c this database environment feature causes infinitely more trouble in development than it is worth in production.  Suggest removing it completely for development and test environments)

**Comment by intrip** [comment]
This check is a safety net to [avoid erasing the production DB accidentally](https://github.com/rails/rails/pull/21237)
I don't think the core team has any plan in removing such check.

**Comment by vanboom** [comment]
I just discovered that you can control this feature with ActiveRecord::Base.protected_environments.  So this issue would not apply if the protection is only configured for production.  Thanks for the ability to disable this silly bikeshedding.  

```
ActiveRecord::Base.protected_environments = []
```

**Comment by vanboom** [comment]
I published a gem for anyone who wants to avoid this obstructiveness: https://github.com/vanboom/stub_protected_environments

I think rails protecting activities on the database is a bike-shed from the perspective of core rails and such extensions are more suitable for gems.

**Comment by rafaelfranca** [comment]
You don't need a gem for that. You can set `DISABLE_DATABASE_ENVIRONMENT_CHECK` in your shell
