### ISSUE TITLE
Object Attributes Got Changed When Update Is Failed

### ISSUE THREAD

**Issue by Decoydoll** [rails/rails#41738]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments

  validates_uniqueness_of :title
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_attribute_should_not_be_changed_after_failed_update
    post1 = Post.create!(title: 'Foo')
    post2 = Post.create!(title: 'Bar')

    result = post1.update(title: 'Bar')

    assert_equal false, result
    assert_equal 'Foo', post1.title
  end
end
```
### Expected behavior
`post1.title` should not be changed to `Bar`. I expect the `update` to not mutate the object, since there is no `!` on it.

### Actual behavior
`post1.title` was changed to `Bar`. If in some of the next line there is a code that persist the same object and ignores any validation, and the person who use it only relies on Rails validation without DB constraint, they will get invalid data in their DB.

### System configuration
**Rails version**:

**Ruby version**:
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

**Comment by abhaynikam** [comment]
@Decoydoll I think this is an expected behavior as validation are run after setting the new attributes passed to `update` but in case validation fail then update query is not fired and DB does not have the latest changes. You can reload the post object before using it again or conditionally handle the case. 😊

```
if post1.update(title: 'Bar')
  ... 
else
  ... 
end
```  
OR

```
assert_equal 'Foo', post1.reload.title
```

**Comment by p8** [comment]
I agree with @abhaynikam ...
And unlike the Ruby Standard Library, where methods like `sort!` mutate the receiver, ActiveRecord uses `!`  to raise an error if the happy flow isn't met.

For example `find_by!` raises an error if no record is found:
https://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by-21

**Comment by Decoydoll** [comment]
So the solution is to always run `.reload` after any `.update` to make sure the object attributes is always the correct state, correct?

**Comment by p8** [comment]
@Decoydoll Yes, if that is what you want.
You can also only reload if it failed.
But if you're processing a submitted Post form that did not validate, you probably want to show the user the Post they submitted, instead of resetting the whole form.
