### ISSUE TITLE
Rails assets:precompile on Windows 

### ISSUE THREAD

**Issue by Jaroost** [rails/rails#41748]
I updated my rails application from 6.0.3.4 to 6.1.3 after that, I run ```rails app:update``` that updated the "bin/yarn" file.

After that when I run```rails assets:precompile``` I have the following error: 
```
rails aborted!
Errno::ENOEXEC: Exec format error - "D:/Projets/PTMManager/PTMManager/bin/yarn" --version
D:/Projets/PTMManager/PTMManager/bin/rails:4:in `require'
D:/Projets/PTMManager/PTMManager/bin/rails:4:in `<top (required)>'
Tasks: TOP => assets:precompile => yarn:install
(See full trace by running task with --trace)
```

- yarn version 1.22.10
- OS: Windows Server 2016 64bit

I there some other things to do after updating?

**Comment by rafaelfranca** [comment]
This was fixed by https://github.com/rails/rails/pull/41529. You can get it by running rails in the 6-1-stable branch.

**Comment by Jaroost** [comment]
@rafaelfranca Do you know when a "official" release will be out? I'tried 6-1-stable branch but I'm behind a corporate proxy and it doesn't work : /
