### ISSUE TITLE
6.1.3 action_dispatch route_set.rb:91: [BUG] Segmentation fault

### ISSUE THREAD

**Issue by dvodvo** [rails/rails#41749]
### Steps to reproduce
running on localhost in development mode, calling a url from a browser.

This bug is revealing itself now on multiple occasions (4 in the past 11 days); the URL is not constant.

I enclose two such auto-generated bug reports, changing the extension to `.txt` as github does not take kindly to `.crash`
[ruby_2021-03-13-110124_jj.txt](https://github.com/rails/rails/files/6195694/ruby_2021-03-13-110124_jj.txt)
[ruby_2021-03-24-100156_jj.txt](https://github.com/rails/rails/files/6195695/ruby_2021-03-24-100156_jj.txt)

Do note that I suspect it may be a local memory issue, with swapping out of memory tripping over itself.
However there is little certainty on my part & as this is re-occurring only with this app, which is the only one with both these rails and ruby versions, after a number of crashes, I surmised it was better to report it. 

### Expected behavior
Page to be rendered.  
On crash, destruction of `server.pid` file.

### Actual behavior
Server crashes, closing with 
```
[...]rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionpack-6.1.3/lib/action_dispatch/routing/route_set.rb:91: [BUG] Segmentation fault  
[...] 2473 lines in stack ending with:
.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionview-6.1.3/lib/action_view/helpers/tags/number_field.rb
[...] * Process memory map: [with 454 lines but mainly invoking: libruby.3.0.dylib bcrypt_ext.bundle  bootsnap.bundle2generator.bundletsnap.bundle2 bundlerse.bundlenap.bundle2�j� 3.0/nokogiri.bundle bundleuby.bundleer-ext.bundleej� ]
Abort trap: 6`  
 -  however `server.pid`file is not destroyed.
Restarting server will serve the page apporpriately.

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 3.0.0

**Comment by p8** [comment]
This seems like a Ruby 3.0.0 issue instead of a Rails issue.
On Ruby master a lot segmentation bugs got fixed...

**Comment by eileencodes** [comment]
Agree with @p8 - it's unlikely this is a Rails bug. Please upgrade your Ruby version to the newest 3.x release and if the problem continues open an issue at https://bugs.ruby-lang.org/

**Comment by dvodvo** [comment]
Right.  Just to note that as of today  [the latest version listed](https://www.ruby-lang.org/en/downloads/releases/)  is 3.0.0 ...  and, oddly the list of branches is unservable `git ls-remote https://github.com/ruby/ruby.git` for lack of a `Invalid certificate chain` .

Will keep in mind the suggestion.
