### ISSUE TITLE
can't create new ruby project

### ISSUE THREAD

**Issue by Tolson321** [rails/rails#41742]
### Steps to reproduce

rails new test1

### Expected behavior
after funning rails new (name) it should create a fresh rails project

### Actual behavior
rails new test1
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:12: warning: already initialized constant YAML
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:13: warning: previous definition of YAML was here
Traceback (most recent call last):
        11: from /usr/local/bin/rails:26:in `<main>'
        10: from /usr/local/bin/rails:26:in `load'
         9: from /Library/Ruby/Gems/2.6.0/gems/railties-6.1.3/exe/rails:10:in `<top (required)>'
         8: from /Library/Ruby/Site/2.6.0/rubygems/custom_require.rb:29:in `require'
         7: from /Library/Ruby/Site/2.6.0/rubygems/custom_require.rb:29:in `require'
         6: from /Library/Ruby/Gems/2.6.0/gems/railties-6.1.3/lib/rails/cli.rb:9:in `<top (required)>'
         5: from /Library/Ruby/Site/2.6.0/rubygems/custom_require.rb:29:in `require'
         4: from /Library/Ruby/Site/2.6.0/rubygems/custom_require.rb:29:in `require'
         3: from /Library/Ruby/Gems/2.6.0/gems/railties-6.1.3/lib/rails/ruby_version_check.rb:3:in `<top (required)>'
         2: from /Library/Ruby/Gems/2.6.0/gems/railties-6.1.3/lib/rails/ruby_version_check.rb:3:in `new'
         1: from /Library/Ruby/Site/2.6.0/rubygems/version.rb:189:in `initialize'
/Library/Ruby/Site/2.6.0/rubygems/version.rb:189:in `strip!': can't modify frozen String (FrozenError)

### System configuration
**Rails version**: I don't know but I get the same frozen output:
rails --version
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/yaml.rb:12: warning: already initialized constant YAML
/Library/Ruby/Site/2.6.0/rubygems/requirement.rb:13: warning: previous definition of YAML was here
Traceback (most recent call last):
        11: from /usr/local/bin/rails:26:in `<main>'
        10: from /usr/local/bin/rails:26:in `load'
         9: from /Library/Ruby/Gems/2.6.0/gems/railties-6.1.3/exe/rails:10:in `<top (required)>'
         8: from /Library/Ruby/Site/2.6.0/rubygems/custom_require.rb:29:in `require'
         7: from /Library/Ruby/Site/2.6.0/rubygems/custom_require.rb:29:in `require'
         6: from /Library/Ruby/Gems/2.6.0/gems/railties-6.1.3/lib/rails/cli.rb:9:in `<top (required)>'
         5: from /Library/Ruby/Site/2.6.0/rubygems/custom_require.rb:29:in `require'
         4: from /Library/Ruby/Site/2.6.0/rubygems/custom_require.rb:29:in `require'
         3: from /Library/Ruby/Gems/2.6.0/gems/railties-6.1.3/lib/rails/ruby_version_check.rb:3:in `<top (required)>'
         2: from /Library/Ruby/Gems/2.6.0/gems/railties-6.1.3/lib/rails/ruby_version_check.rb:3:in `new'
         1: from /Library/Ruby/Site/2.6.0/rubygems/version.rb:189:in `initialize'
/Library/Ruby/Site/2.6.0/rubygems/version.rb:189:in `strip!': can't modify frozen String (FrozenError)
**Ruby version**:
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

**Comment by louim** [comment]
Hi @Tolson321! Can you try `gem update --system` and see if that fixes the errors you're seeing?

**Comment by rafaelfranca** [comment]
Thank you for the issue. This seems to be a problem in your Rubygems/Ruby setup, so it is not a rails issue. That being said I'm closing the issue here.
