### ISSUE TITLE
Enums defined with symbols return a string value

### ISSUE THREAD

**Issue by yagudaev** [rails/rails#41753]
### Steps to reproduce

When an enum is defined with symbols as keys, whether it is a hash or array block, it should return back the same type (i.e. symbol) and not strings.

If our goal is to adhere to the principle of least-surprise, it is worth while fixing. It could also have a positive impact on memory usage / performance.

### Expected behavior
```
class Conversation < ActiveRecord::Base
  enum status: [ :active, :archived ]
end

conversation.status    # => :archived
```

### Actual behavior

From the documentation:

```
class Conversation < ActiveRecord::Base
  enum status: [ :active, :archived ]
end

conversation.status    # => "archived"
```

### System configuration
**Rails version**: 6.x.x (and probably all version)

**Ruby version**: 2.7+ (and probably all versions)

### Related Issues

https://github.com/rails/rails/issues/31775 https://github.com/rails/rails/issues/41118

**Comment by intrip** [comment]
The proposal makes sense from my POV but this is not a backward compatible change and it might break existing apps, I'd wait from input from the core team and if makes sense for them and they maybe want to put this in the 7.x release .

**Comment by rafaelfranca** [comment]
Rails never returns symbol for database types, only strings. We have no interest of breaking this behavior. Thank you for the issue.

**Comment by yagudaev** [comment]
> Rails never returns symbol for database types, only strings. We have no interest of breaking this behavior. Thank you for the issue.

@rafael Thanks for the clarification. 

I might be missing something, but enum types are stored as numbers in the database (I believe there is also an option to store them as strings). Thus, we are converting an integer into a string. Why not convert it into the symbol it was defined with instead?

Also let me demonstrate really quick the issue:

```ruby
class Post < AppilcationRecord
  enum status: { draft: 0, published: 1 }
  
  # legacy method, only lets valid records be published.
  # yes, this can be solved with a data migration, but there are other 
  # constraints that make this a better stop-gap
  def status
    if valid?
      # a new dev seeing this, might think: ok, let's change to symbol.
      # this will break things like graphql types and other logic
      return "draft"
    end
    
    super
  end
end
```

We don't have to make this the default behavior either, it can be an option on the enum definition.

Finally, we can also just address it in the documentation. Call out that it returns a string and that rails always does for database types as you say.

**Comment by rafaelfranca** [comment]
> Finally, we can also just address it in the documentation. Call out that it returns a string and that rails always does for database types as you say.

I'm up to that.

> I might be missing something, but enum types are stored as numbers in the database (I believe there is also an option to store them as strings).

when I mean strings I mean for all string based columns (I know the enum is not).

If you do

```
user.name = :rafael
user.save!
user.reload
user.name
```

You will get a string, not a symbol. Enum is a feature to map string values to integers (or other strings). Of course you can pass symbols for it, but I don't think we should store internally as symbols.

**Comment by gerry3** [comment]
Trying to migrate our codebase to `ActiveRecord::Enum` from the [simple_enum](https://github.com/lwe/simple_enum) gem and ran into this behavior.

The test `"deserialize enum value to original hash key"` (from #41278) indicates that we should expect the original hash key. Should symbols really be an exception?

We would really appreciate an option for this. Curious if there's more to it than just changing `enum_values = ActiveSupport::HashWithIndifferentAccess.new` to `enum_values = {}` in `_enum`?

**Comment by thiagodiniz** [comment]
@rafaelfranca totally agree that should be always returned a string, but.. 
don't you think that once the mapping is being used through the code, that shouldn't be a why to compare using the symbol keys?

I my code I had to do this:


```ruby
class SomeModel < ApplicationRecord
  enum kind: { charge_paid: 'charge_paid', active_contract: 'active_contract', charge_cancelled: 'charge_cancelled', sms_sent: 'sms_sent' }

  def some_method
    case kind.to_sym
    when :charge_paid, :charge_cancelled
      some_attribute
    when :active_contract
      another_attribute
    when :sms_sent
      other_attribute
    end
  end
```

**Comment by rafaelfranca** [comment]
I see no problem with that `to_sym`. Some people expect to compare with symbols, some people with strings. Rails is being consistent and always returning a string. If you want a symbol you could for example override the enum reader and call `to_sym` automatically.

**Comment by dougjq** [comment]
This is all very surprising.

**Comment by jessicard** [comment]
I just ran into this as well and found the behavior surprising.

**Comment by jerefrer** [comment]
Yep, same here, since enum values are so often used in conditionals (typically for a `status` field) that might end up all over the place, I would have expected it to return symbols.
