### ISSUE TITLE
wrong constant name SaasySimple/applicationHelper (NameError)

### ISSUE THREAD

**Issue by shadydealer** [rails/rails#41752]
### Steps to reproduce
make any subdirectory of a helpers directory start with an uppercase letter

### Expected behavior
Expected that subdirectories of the helpers directories can start with uppercase letters and still work as expected.

### Actual behavior
`SaasySimple/application` would result in the helper_prefix variable to remain as `SaasySimple/application` whereas it should be camelized so it can be transformed into `SaasySimple::Application`.

The bug is introduced [here](https://github.com/rails/rails/commit/5b28a0e972da31da570ed24be505ef7958ab4b5e#diff-3149407bd2f6287e7791fc3e0cc5b2559d7e4e0c19eb1e7f7ea84e0db1e35ac5R156https://github.com/rails/rails/commit/5b28a0e972da31da570ed24be505ef7958ab4b5e#diff-3149407bd2f6287e7791fc3e0cc5b2559d7e4e0c19eb1e7f7ea84e0db1e35ac5R156) line 156

### System configuration
**Rails version**:
6.1.3

**Ruby version**:
2.6.5

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is not a bug. The folder are Rails application are expected to use snake case, like `saasy_simple`. See https://github.com/rails/rails/commit/5b28a0e972da31da570ed24be505ef7958ab4b5e#r48666392
