### ISSUE TITLE
Release new activestorage versions allowing marcel 1.0.0

### ISSUE THREAD

**Issue by pjmartorell** [rails/rails#41767]
There has been a new release of `marcel` 1.0.0 removing `mimemagic`, could you release version of `activestorage` updating the semver of `marcel` to `~> 1.0.0`? 

https://github.com/rails/rails/blob/30ef29289ba631911564129a1c040f9e81c7a770/activestorage/activestorage.gemspec#L39

**Comment by kaspth** [comment]
We're working on exactly this. Thanks.

**Comment by pjmartorell** [comment]
Thank you and sorry if it sounded condescending 🙏

**Comment by kaspth** [comment]
All good, we're just on it already 😊
