### ISSUE TITLE
New mimemagic version breaks windows support

### ISSUE THREAD

**Issue by ahorek** [rails/rails#41762]
### Steps to reproduce
```
gem install mimemagic

Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing mimemagic:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mimemagic-0.4.1/ext/mimemagic
C:/Ruby27-x64/bin/ruby.exe -IC:/Ruby27-x64/lib/ruby/2.7.0/rubygems -rrubygems C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.3/exe/rake RUBYARCHDIR\=C:/Ruby27-x64/lib/ruby/gems/2.7.0/extensions/x64-mingw32/2.7.0/mimemagic-0.4.1 RUBYLIBDIR\=C:/Ruby27-x64/lib/ruby/gems/2.7.0/extensions/x64-mingw32/2.7.0/mimemagic-0.4.1
rake aborted!
Could not find MIME type database in the following locations: ["/usr/local/share/mime/packages/freedesktop.org.xml", "/opt/homebrew/share/mime/packages/freedesktop.org.xml", "/usr/share/mime/packages/freedesktop.org.xml"]

Ensure you have either installed the shared-mime-types package for your distribution, or
obtain a version of freedesktop.org.xml and set FREEDESKTOP_MIME_TYPES_PATH to the location
of that file.

Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/mimemagic-0.4.1 for inspection.
Results logged to C:/Ruby27-x64/lib/ruby/gems/2.7.0/extensions/x64-mingw32/2.7.0/mimemagic-0.4.1/gem_make.out
```

### Expected behavior
since all previous versions were junked and ```mimemagic``` is a hard dependency of Rails, there's no official way to use Rails on Windows anymore.

### Actual behavior
```bundle install``` is broken

### System configuration
**Rails version**: any

**Ruby version**: any

**Comment by rafaelfranca** [comment]
Please open an issue on minimagic about this.

**Comment by ahorek** [comment]
it's forbidden to open a new issue on https://github.com/mimemagicrb/mimemagic/issues

**Comment by rafaelfranca** [comment]
lol. This issue needs to be fixed there, not here, so I don't think this is the right place for the issue. @jellybob can you please enable issues on that repository? I understand you don't want to deal with the influx of angry mob but you will also lose some real issues that needs to be fixed.

**Comment by jellybob** [comment]
I've just opened up issues over there - we were indeed trying to avoid the mob, but I'm more comfortable with that than inflicting a bunch of unrelated issues on the Rails team.
