### ISSUE TITLE
ActiveSupport::TimeZone.iso8601 expects result of Date._iso8601 to contain specific keys, raises KeyError

### ISSUE THREAD

**Issue by steventux** [rails/rails#41763]
### Steps to reproduce

Pass a string to `ActiveSupport::TimeZone.iso8601` which is parseable by `Date._iso8601` but doesn't result in a hash with expected `:mon` or `:mday` keys.

```ruby
Date._iso8601('12936')
=> {:yday=>936, :year=>2012}
```

```ruby
Time.zone.iso8601('12936')
KeyError: key not found: :mon`
```
See https://github.com/rails/rails/blob/main/activesupport/lib/active_support/values/time_zone.rb#L384

### Expected behavior

Expect an `ArgumentError` if the string passed to `ActiveSupport::TimeZone.iso8601` is not a valid ISO8601 formatted date.
This could be achieved by rescuing `KeyError` and raising `ArgumentError` in the method.

PR with the suggested change here https://github.com/rails/rails/pull/41764

I'm uncertain whether this is really a bug with `Date._iso8601` as the input string is evidently not ISO8601. 

### Actual behavior

The error `KeyError: key not found: :mon` is raised which doesn't quite reflect the method documentation.

### System configuration
**Rails version**:  Rails 6.0.3.5

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352)

**Comment by pixeltrix** [comment]
Fixed by #41764
