### ISSUE TITLE
ActiveSupport::Testing::Parallelization::Worker#perform_job does not invoke Minitest::AbstractReporter#prerecord

### ISSUE THREAD

**Issue by hurricup** [rails/rails#41766]
Some reporters may rely on proper API usage and I believe it's 

- start 
- for each test:
  - prerecord
  - run test
  - record
- report

And pre-record step is missing for some reason

**Comment by donv** [comment]
This is still a problem.

**Comment by donv** [comment]
This is still a problem.

**Comment by UweKubosch** [comment]
This is still a problem.
