### ISSUE TITLE
New release included additional changes

### ISSUE THREAD

**Issue by eraffel-MDSol** [rails/rails#41771]
@georgeclaghorn, it seems like the new release included other changes besides just the Marcel bump:

https://github.com/rails/rails/compare/v5.2.4.5...v5.2.5

particularly https://github.com/rails/rails/compare/v5.2.4.5...v5.2.5#diff-5f81b06a0e3051b576daee16c960b21e715a6cc26d97d020c546d2fa697c9bc6

Saw this comment: https://github.com/rails/rails/commit/abd27d5121573ab591d1501afa5f81e2e9da8c90#commitcomment-42598389

Not sure if this is going to cause a problem, but wanted to raise it.

**Comment by rafaelfranca** [comment]
That is by design. Thank you for pointing though. Without those changes Rails 5.2 would not work in Ruby 2.2 anymore.
