### ISSUE TITLE
Arel fails to search text column which is serialized in ActiveRecord model

### ISSUE THREAD

**Issue by vanboom** [rails/rails#41787]
### Steps to reproduce
Consider a User model with a `permissions` field declared as `text` in the migration. 

```ruby
class User < ApplicaitonRecord
   serialize :permissions
end
```

```irb
irb> pred = User.arel_table[:permissions]
irb> User.where(pred.matches("%manager%"))

Traceback (most recent call last):
ActiveRecord::SerializationTypeMismatch (can't dump `permissions`: was supposed to be a Array, but was a String. -- "%manager%")

```

### Expected behavior
The query should successfully search the *plain text* and return matching results or ActiveRecord::Relation [].  

### Actual behavior

```
ActiveRecord::SerializationTypeMismatch (can't dump `permissions`: was supposed to be a Array, but was a String. -- "%manager%")
```
This worked perfectly in Rails 4.1.8.  Related to ransack issue: https://github.com/activerecord-hackery/ransack/issues/932

### System configuration
**Rails version**: 5.2.4.5
**Ruby version**: 2.5.0

**Comment by rafaelfranca** [comment]
Thank you for the issue. Arel is not public API of Rails and should not be used by applications. Also Rails 5.2 is not supported to bug fixes anymore.

**Comment by vanboom** [comment]
Please reopen - confirmed this issue with Rails 6.1.3.1

The root issue for discussion is:  I think Rails and Arel should allow us to query a serialized value based on its database type with consistent handling of this scenario.  

This works...
```ruby
User.where("permissions ilike ?", "%manager%")
```
whereas Arel does something different...

```ruby
User.arel_table[:permissions]
User.where(pred.matches("%manager%"))
```
The latter results in in the SerializationTypeMismatch exception. 
This SQL is produced in debugging if I patch around the exception...  (I have removed some of the escaped quotes for clarity)

```sql
SELECT users.* FROM users WHERE users.permissions ILIKE --- \"%manager%\"
```
Some YAML is being inserted instead of allowing a plain text search on the *text* database field. 

Shouldn't `matches` create a plain text `ILIKE` in this case?

**Comment by rafaelfranca** [comment]
Arel is not public API of Rails and should not be used by applications. We don't support using Arel objects to make queries in application. If `User.where("permissions ilike ?", "%manager%")` works, so there is no issue in Rails.

**Comment by vanboom** [comment]
> Arel is not public API of Rails and should not be used by applications. We don't support using Arel objects to make queries in application.

Regardless, this looks like an inconsistency / bug in Arel that could cause issues elsewhere.  Issues, bug reports, suggestions and PRs related to Arel are not accepted from the community?
