### ISSUE TITLE
Rendering a partial outside of a controller results in the wrong host being used in Active Storage URLs

### ISSUE THREAD

**Issue by brian-kephart** [rails/rails#41795]
### Steps to reproduce
There are various ways to reproduce this. What I did was render an Action Text content field with an image attachment within a Turbo stream using the `broadcasts_to` class method (which renders in a background job).

Other issues referring to this behavior:
- https://github.com/hotwired/turbo-rails/issues/54 (closed by the person who opened the issue, who found a workaround for other uses of Active Storage but not for the Action Text case)
- https://github.com/rails/rails/issues/31979 (closed by stale bot, contains full repro steps)
- https://github.com/rails/rails/issues/35578 (fixed, but only for Action Mailer)

It appears that this issue has been around for some time, and that it affects multiple out-of-the box uses of Rails.

### Expected behavior
The url in the image tag `<src>` generated from the attachment should use the default host. In the case of my example from dev mode, it should be 'localhost'.

### Actual behavior
The attachment host in the `<src>` url is 'example.org'. This differs from the behavior when rendering from a controller.

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: 3.0.0

**Comment by brian-kephart** [comment]
Some inspection has confirmed that `ApplicationController::Renderer::DEFAULTS` ([link](https://github.com/rails/rails/blob/4f1f63b98a866b573df5e26f05f167a6a9f4b797/actionpack/lib/action_controller/renderer.rb#L40)) are not being overridden for these types of requests.

**Comment by brian-kephart** [comment]
Made a repro here: https://github.com/brian-kephart/rendering_bug

**Comment by stevepolitodesign** [comment]
I'm running into the same issue as @seanharmer 

![CleanShot 2021-06-02 at 07 09 54@2x](https://user-images.githubusercontent.com/5122678/120470547-a7457580-c371-11eb-8ffd-decd11d6ce2d.png)

**Comment by lfalcao** [comment]
Hi @brian-kephart thanks for the sample app! :+1: 

I don't know if this current behavior is expected or not, but what's happening here is a little bit tricky. So, my first attempt to fix, with less possible changes and keeping everything working was to just check if env was empty and loading `ApplicationController.renderer.defaults` before initialize render. 

```git
+++ b/actionpack/lib/action_controller/renderer.rb
@@ -63,6 +63,8 @@ def with_defaults(defaults)
     # It will be merged with the default Rack environment defined by
     # +ActionController::Renderer::DEFAULTS+.
     def initialize(controller, env, defaults)
+      env = env.empty? ? custom_defaults : env
+
       @controller = controller
       @defaults = defaults
       @env = normalize_keys defaults, env
@@ -102,6 +104,12 @@ def render(*args)
     alias_method :render_to_string, :render # :nodoc:
 
     private
+      def custom_defaults
+        if defined? ApplicationController and not ApplicationController.renderer.nil?
+          ApplicationController.renderer.defaults
+        end || {}
+      end
+

```

I know this is not the optimal solution and the correct would be pass the `ApplicationController.renderer.defaults` correctly across the stack, but to avoid breaking other things I think doing this way is ok. Does it makes sense? :thinking:

**Comment by brian-kephart** [comment]
@lfalcao Thanks for taking a look at this. I'm not sure I follow what you're doing. Are you proposing a change in Rails or a monkey patch in my app?

If you mean a change to Rails, then I'm still not sure how to pass in the defaults. This issue is triggered in my case by using library features (Hotwire's various `:broadcast_later` features) that initiate rendering through some indirection, so I'm not well-positioned to alter rendering arguments through any new pathways.

If you mean to suggest that I patch my app, is that solution superior in any way to this?
```ruby
# config/environments/production.rb
config.action_controller.default_url_options = { host: 'https://mysite.com' }
```

The code above is my current workaround, which is easy and reliable, but doesn't work with apps accessible on multiple hosts. Thankfully, I have apps that hit this issue and apps that use multiple hosts, but no apps that do both. 🙂

My understanding of the problem is this:
1. When something like a background rendering job or a mailer gets triggered in response to a web request, the environment of that request is lost by the time that rendering happens in the job/mailer/whatever.
2. Some Rails-adjacent libraries (Hotwire in my case) aren't set up to pass this environment information explicitly.
3. Rails appears to have no framework defaults for this situation.
4. The way of setting app defaults (as in my code above) is inadequate to the case of multi-host apps, as far as I could discover.

I wanted to lay this out point-by-point for discussion, but based on your post I'm pretty sure you understand this better than I do, so let me know if I got any of the summary points wrong or misunderstood what you were proposing. Thanks again for looking at this.

**Comment by ghiculescu** [comment]
Thanks for the great detail. This is an interesting bug. Some quick notes:

- turbo-rails calls [`ApplicationController.render`](https://github.com/hotwired/turbo-rails/blob/2945dcb7c5fc634ad7d459e0872cf04cf8a3576d/app/channels/turbo/streams/broadcasts.rb#L64). `config.action_controller.default_url_options` should resolve that. I couldn't see that in your sample app; can you confirm that it does?
- Point taken on apps with multiple hosts - the config solution wouldn't work.
- The background rendering step in turbo-rails runs through an ActiveJob: https://github.com/hotwired/turbo-rails/blob/2945dcb7c5fc634ad7d459e0872cf04cf8a3576d/app/jobs/turbo/streams/action_broadcast_job.rb#L2. A simple solution could be to pass some more request details into the job, eg. `request.host`. Similar to  https://github.com/rails/rails/pull/32085 and https://github.com/rails/rails/pull/20800

**Comment by lfalcao** [comment]
Hi @brian-kephart, I was suggesting a possible way to fix into Rails core. But its not the ideal, as it would not work with multipe hosts too. What you and @ghiculescu said, gave me some insights. Later I'll try to take a look into this again.

**Comment by brian-kephart** [comment]
@ghiculescu Yes, setting the config fixes the issue in the sample app, and is how I fixed my production app.

I love the idea of automatically setting the host for ActiveJob::Base using the approach in those PRs. Duplicating the approach seen in [this commit](https://github.com/rails/rails/pull/32085/commits/a9d1167b1fdae6f5f5496738b3e7d1e05949dcd0) seems like it would do the job nicely.

**Comment by ghiculescu** [comment]
@brian-kephart are you interested in working on a PR for this?

**Comment by brian-kephart** [comment]
@ghiculescu I do not feel well-equipped to make a PR for this, at least not without some direction from the team. In my mind, this is a whole-framework problem, applying to any rendering that happens outside a controller. We've already seen that this was addressed for mailers, but that fix did not address background jobs.

Likewise, your proposed fix seems like it would work well for jobs generated by a controller action, but does not appear to address jobs created outside a controller, like in a rake task. It also does not address any rendering done outside of background jobs.

If we just want to solve the specific problem of making Turbo and similar libraries render URLs correctly out of the box using background jobs created during a controller response, then I think I could make a PR based on your idea. I would really like to see some feedback from others about the broader problem before committing to that fix, though, to make sure we're not just playing whack-a-mole every time a library calls the renderer in a way we didn't anticipate.

**Comment by ghiculescu** [comment]
> Likewise, your proposed fix seems like it would work well for jobs generated by a controller action, but does not appear to address jobs created outside a controller, like in a rake task. It also does not address any rendering done outside of background jobs.

Hmmm, good point on rake tasks. I don't have any great ideas for that, for multi-host apps I think there's only so much the framework can infer for you.

> I would really like to see some feedback from others about the broader problem before committing to that fix, though, to make sure we're not just playing whack-a-mole every time a library calls the renderer in a way we didn't anticipate.

Yep, that's not a bad idea.

**Comment by tenpaiyomi** [comment]
I came across this issue myself, only with a few other components that utilized `ActionController::Renderer`.  I detailed out my observations, thoughts, temporary solution, and a proposal for a longer term solution [here](https://github.com/hotwired/turbo-rails/issues/155#issuecomment-978968830) in case it proves to be interesting or gives ideas to others on how to possibly create a better solution.  I'm also willing to create a PR with my proposed solution if there is enough support that it would be a decent approach.

**Comment by clarkology56** [comment]
I was having the same issue. I fixed it by using the `path` helper instead of the `url` helper (ex `user_path(@user)` instead of `user_url(@user)`)

**Comment by jmarsh24** [comment]
I'm also running into this issue when trying to broadcast a job which references as activestorage via url eg. `video_tag video.watermarked_video.url`

**Comment by matthee** [comment]
Note to self, and to anyone experiencing similar issues - you can't do: 

`config.action_controller.default_url_options = { host: "localhost:3020" }`

Instead, you *must* use an explicit port specification

`config.action_controller.default_url_options = { host: "localhost", port: 3020 }`
