### ISSUE TITLE
Rails docs are unusable without a mouse with JavaScript enabled

### ISSUE THREAD

**Issue by SleeplessByte** [rails/rails#41813]
### Steps to reproduce
1. Go to any page in the docs
2. Focus is on the input searchbox field (meh, but okay)
3. Pressing tab focuses `body` (??)
4. Go to https://api.rubyonrails.org/files/activerecord/lib/active_record/callbacks_rb.html
5. Pressing tab goes to https://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html ????

### Expected behavior
Tab focusses the next focussable element, or component, or `tab-index` (except -1).

### Actual behavior
Docs are hijacking tabs to do some weird navigation. I cannot use my screenreader to navigate the docs. I cannot use my keyboard to navigate the docs. I cannot use the docs without disabling JavaScript.

**Comment by p8** [comment]
Hey Derk-Jan, I think we can move this discussion to the sdoc repo.

**Comment by SleeplessByte** [comment]
Sounds good. Should I close here?

**Comment by p8** [comment]
Yes, please. 😄
