### ISSUE TITLE
Rails Docs captures CTRL and break Keyboard usage, copying, and a lot of other things

### ISSUE THREAD

**Issue by SleeplessByte** [rails/rails#41814]
### Steps to reproduce
1. Be on Windows, Chrome
2. Go to https://api.rubyonrails.org/
3. Select something
4. Press CTRL+C.

### Expected behavior
It copies what's selected.

### Actual behavior
It highlights "files" and shows the following error in the console:

![Error message from the JavaScript Console showing searchdocs.js: searchdoc.js:94 Uncaught TypeError: Cannot read property 'mozilla' of undefined](https://user-images.githubusercontent.com/1964376/113320380-bf1d6080-9312-11eb-8d48-b55d571ea93a.png)

### Additional context

I don't know why this decision was made, but this makes the docs not very great to work with, and in fact completely inaccessible for keyboard-only users, without disabling JavaScript. Perhaps Windows is added to the QA pipeline, or at least a less mac/linux centric library is used? Copy should work.

What I think it's supposed to do is "navigate up" one in the tree, which it annoying does instead of copying what I've selected. Steps to reproduce:

1. Be on Windows
2. Go to https://api.rubyonrails.org/classes/AbstractController.html
3. Press CTRL + C
4. The highlighted item moves to Core extensions

Related: https://github.com/rails/rails/issues/41813

### Workaround

Be on a mac. CMD + C works...

**Comment by iHiD** [comment]
There's a PR for this [here](https://github.com/zzak/sdoc/pull/155/files) that doesn't seem to have had attention yet. Would be great if this could be expedited for all the non-Mac users out there 🙂

**Comment by eileencodes** [comment]
Thanks for the report and pr link. The sdoc repo isn't owned by Rails so I'm going to close this - it's not something we can fix as part of rails/rails.

**Comment by SleeplessByte** [comment]
It's an upstream problem therefore it's fine if Windows users can't copy content out of the docs isn't quite the answer I expected. However, the sdoc repo people have, gladly, picked up this issue, so it will be resolved.

I find it troubling that there is (seemingly) no QA in place from the rails team to make sure the documentation is usable and accessible.

**Comment by eileencodes** [comment]
I didn't say it's fine, I said we should fix it in sdoc where the bug is. Even if Rails owned sdoc, we'd ask to move the issue to sdoc so we can track it. I'm not saying we don't care, we do care. But the bug isn't in the framework, it's in the tool we use to display API docs so I want to track and fix it there. I'm sorry if you felt dismissed, that wasn't my intention

**Comment by SleeplessByte** [comment]
I'm glad to hear you care - sorry if I misunderstood that. I understand your intention closing the issue and I agree the discussion around the original issue should be held there where it can be fixed. 

What do we do to ensure that there is some QA process for Windows users and users with accessibility issues? Is there somewhere to open an issue for that?

**Comment by eileencodes** [comment]
> What do we do to ensure that there is some QA process for Windows users and users with accessibility issues? Is there somewhere to open an issue for that?

I honestly don't know how to implement this. We are a really small team of 12 who _volunteer_ to work on Rails and none of us are Windows users as far as I'm aware. We would need someone in the community who uses Windows and is willing to do QA for sdoc. Any bug affecting Rails docs would affect all other users of sdoc.

**Comment by SleeplessByte** [comment]
I have offered my time and expertise to the people over at sdoc (regarding the bigger overarching accessibility concerns), which they've accepted, so I hope I can help them help me in the short term.
