### ISSUE TITLE
System test screenshot path is not configurable

### ISSUE THREAD

**Issue by dmolesUC** [rails/rails#41828]
### Steps to reproduce

1. create a Rails project using `capybara` and `selenium-webdriver` for system tests.
2. set [`Capybara.save_path`](https://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FSessionConfig:save_path) to some directory, e.g. `ci-artifacts/screenshots`
3. write and run a system test that fails and takes a screenshot

### Expected behavior

- screenshot is saved under the path specified above

### Actual behavior

- screenshot is saved under `tmp/screenshots`

### Notes

The issue is in [ActionDispatch::SystemTesting::TestHelpers::ScreenshotHelper#absolute_path](https://github.com/rails/rails/blob/v6.1.3.1/actionpack/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb#L78-L80), which hard-codes the screenshot directory to `tmp/screenshots`.

It's not critical that it follow `Capybara.save_path` (although it is counterintuitive that it doesn't), but it would be nice if there was **some** way to configure where these go.

### System configuration

**Rails version**: 6.0.3.5, but 6.1.3.1 (linked above) has the same code (as does `main`, at least as of this writing)

**Ruby version**: 2.7.2

**Comment by lfalcao** [comment]
@dmolesUC yes, it shouldn't be hardcode... can you send a PR?

you can use a symbolic link in the meantime: `ln -fs tmp/screenshots ci-artifacts/screenshots`
