### ISSUE TITLE
can't bypass strict_loading on new records

### ISSUE THREAD

**Issue by mockdeep** [rails/rails#41827]
### Steps to reproduce

Set up a one-to-many relationship, with `strict_loading` enabled:

```rb
class User < ApplicationRecord
  self.strict_loading_by_default = true

  has_many :checks
end

class Check < ApplicationRecord
  self.strict_loading_by_default = true

  belongs_to :user
end
```

And try to access the `checks` on a new `User`:

```rb
user = User.create!
puts user.checks
```

### Expected behavior

This should not cause an error, or there should be a way to trigger the checks to be loaded. It looks like right now the only options are to directly set the relationship when the parent record is created:

```rb
user = User.create!(checks: [])
```

Or to disable `strict_loading` entirely:

```rb
user = User.create!
user.strict_loading!(false)
```

I'd rather not disable it, so for now I'll set the relationship to an empty array.

### Actual behavior

A strict loading error is triggered:

```
ActiveRecord::StrictLoadingViolationError:
  `User` is marked for strict_loading. The `Check` association named `:checks` cannot be lazily loaded.
```

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 2.7.2

**Comment by mockdeep** [comment]
Actually, setting them to an empty array causes weird loading issues, so maybe that won't work, either:

```rb
> user = User.create!(checks: [])
> check = Check.create!(user: user)
> user.checks
=> []
> user.reload.checks
=> ActiveRecord::StrictLoadingViolationError:
```

**Comment by abhaynikam** [comment]
@mockdeep Following are couple of ways you can bypass the strict loading mode. Maybe `strict_loading` should by default use `mode: n_plus_one_only` instead of `:all` in order to make it easier but I do not have the depth in this matter and would leave to the Rails core team to decide. Happy to debug more if that makes sense  to the Rails team 😊. 

1. Disable `strict_loading` on user object
```
user = User.create!
user.strict_loading!(false)

user.checks # => should work.
```

2. Enable `strict_loading` in `n_plus_one_only` mode only(**I would recommend this**)
```
user = User.create!
user.strict_loading!(mode: :n_plus_one_only)

user.checks # => should work.
user.checks.first.some_assocation_name # => should raise exception
```

3. Disable `strict_loading` on `checks` association(model level)
```
class User < ApplicationRecord
  self.strict_loading_by_default = true

  has_many :checks, strict_loading: false
end
```

**Comment by mockdeep** [comment]
@abhaynikam thanks for the tip! It's unfortunate that these won't be released until Rails 7. I guess I might have to point my app at `main`.

**Comment by yoelblum** [comment]
> can't bypass strict_loading on new records 

The bug's title is not 100% accurate - user is not a new record

```
user = User.create!
user.new_record? #false
```
Perhaps the intention is "single record" ? @mockdeep

**Comment by mockdeep** [comment]
@yoelblum yes, I didn't mean strictly `#new_record?` but newly created records.

**Comment by yoelblum** [comment]
@abhaynikam It looks like n_plus_one_only should be true by default perhaps? I mean that's what we want to prevent right?
I don't understand why 
     ``` 
       User.first.checks
       User.create!.checks
       ```
Should raise. A sane default would be it skis the check since preloading doesn't gain anything here (and preloading isn't even possible here right?)
