### ISSUE TITLE
Add ability to not add x-crsf-token on specific requests

### ISSUE THREAD

**Issue by mildred** [rails/rails#41820]
### Steps to reproduce
With rails javascript bundled in, any form or link with `data-method=post` will produce a request with a `X-CRSF-Token`

### Expected behavior
It should be possible for some links/forms to not add the `X-CRSF-Token` header

### Use case
When redirecting to an OAuth backend that has Access-Control-Allow-Headers set and not including X-CRSF-Token, the request fails.

### System configuration
**Rails version**: 6.1
**Ruby version**: 3.0

**Comment by jacobherrington** [comment]
Hi @mildred!

Could you provide a specific example of what you mean?

For example, it is possible to generate forms that do not create a hidden authenticity token field like so:

[form_tag defines an `authenticity_token` parameter](https://api.rubyonrails.org/classes/ActionView/Helpers/FormTagHelper.html#method-i-form_tag)
```erb
<%= form_tag('http://far.away.com/form', authenticity_token: false) %>
# => <form action="http://far.away.com/form" accept-charset="UTF-8" method="post"></form>
```

Approximately the same behavior exists for [`form_with`](https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with):
```erb
<%= form_with(model: @post, authenticity_token: false) %>
```

Are you specifically referring to a helper like `button_to` which does not allow a user to override this behavior?

**Comment by intrip** [comment]
not stale: PR Attached

**Comment by intrip** [comment]
Can you please reopen? /cc @p8 @ghiculescu

**Comment by p8** [comment]
This should be fixed in: https://github.com/rails/rails/pull/43417
