### ISSUE TITLE
Issue with devise and bcrypt on a macbook m1 rails install

### ISSUE THREAD

**Issue by elviajero971** [rails/rails#41843]
Hello there, I'm having some issues on a new mac m1 and my install of rails

### System configuration

**OS**:  macOS Big Sur Version 11.2.1 (20D74)

**zsh**: 5.8 (x86_64-apple-darwin20.0)

**postgres**: 13.2

**Rails version**:  Rails 6.1.3

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin20]

**Brew version**:  Homebrew 3.0.9

### What I can do:
I have successfully:
- create a rails app with `rails new myApp -d postgresql`
- add gem devise to the Gemfile
- run `bundle install`
- create devise User and all CRUD views
- run `db:create`, `db:migrate`
- launch the server with `rails s`
- access all the pages of login, sign up, etc...

### Expected behavior
I'm expecting to be able to create an account and connect to it.

### Actual behavior

When I try to create an account I'm running into an error about the gem bcrypt that seems to run on the wrong architecture...

<img width="1431" alt="Screenshot 2021-04-05 at 21 33 17" src="https://user-images.githubusercontent.com/60394449/113617696-f5324b80-9656-11eb-9776-953a248bccb1.png">

I've tried to reinstall everything but i still got the same error.

Anyone have an idea about the issue ?

Thanks by advance and have a good day to you all.

**Comment by louim** [comment]
Hi @elviajero971. This looks like an issue with Bcrypt specifically. There is an issue open in the Bcrypt repository here: https://github.com/bcrypt-ruby/bcrypt-ruby/issues/239. One user report success by running `gem uninstall bcrypt` and then `bundle install`. Discussion should probably continue in the Bcrypt repository.

**Comment by elviajero971** [comment]
> Hi @elviajero971. This looks like an issue with Bcrypt specifically. There is an issue open in the Bcrypt repository here: [bcrypt-ruby/bcrypt-ruby#239](https://github.com/bcrypt-ruby/bcrypt-ruby/issues/239). One user report success by running `gem uninstall bcrypt` and then `bundle install`. Discussion should probably continue in the Bcrypt repository.

I just tried it and I still got the same issues even after uninstalling bcrypt, running bundle install and restarting the server.

I'm moving the issue to bcrypt repo, thanks :)

**Comment by elviajero971** [comment]
#https://github.com/bcrypt-ruby/bcrypt-ruby/issues/250
