### ISSUE TITLE
ActionView: `render file:` does not output html-safe strings

### ISSUE THREAD

**Issue by ClearlyClaire** [rails/rails#41840]
In the past, the behavior of the raw template renderer outputing html-safe strings has been [explicitly documented](https://github.com/rails/rails/commit/1de0df86695f8fa2eeae6b8b46f9b53decfa6ec8) but it seems that the calling `render file:` has stopped outputting HTML-safe strings in Rails 6, without that change being explicitly documented.

I do not know if this behavior change was intentional, but it was surprising, especially with the lack of documentation surrounding it.

### Steps to reproduce

Call `= render file: path_to_svg_file` in a HAML template.

### Expected behavior

The SVG file is included verbatim, without being escaped.

### Actual behavior

The SVG file is actually escaped.

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: 2.7.2p137

**Comment by lfalcao** [comment]
Related: https://github.com/rails/rails/pull/35688
