### ISSUE TITLE
ActiveStorage duplicate attachments with after_save callback

### ISSUE THREAD

**Issue by colinlieberman** [rails/rails#41847]
### Steps to reproduce
Hi, apologies if this has been asked and answered elsewhere, if so, I couldn't find it.

1. Have a model with a `has_many_attached` relationship
2. Have an `after_save` callback on the model that conditionally changes model properties
3. Call `model#attach`

### Expected behavior
Have single attachment.

### Actual behavior
Two attachments with same `blob_id` and `created_at` timestamp

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.6.3p62

In the [docs](https://edgeapi.rubyonrails.org/classes/ActiveStorage/Attached/Many.html#method-i-attach) it says

> If the record is persisted and unchanged, the attachments are saved to the database immediately. Otherwise, they'll be saved to the DB when the record is next saved

And we're wondering if it's possible that the first case (persisted and unchanged) causes the attachment to store a first time, and then the model data change introduced in the `after_save` callback triggers the second case to save the attachment as well.

Thanks

**Comment by lfalcao** [comment]
Related to https://github.com/rails/rails/issues/41661 https://github.com/rails/rails/issues/41903 ?

**Comment by abhaynikam** [comment]
@colinlieberman I couldn't reproduce this issue on `master` and `Rails 6.0.2.2`. Attaching the reproduction script I wrote here. Maybe I am missing something here. Could you update the script and help us reproduce it? 😊 

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "6.0.2.2"
  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true do |t|
    t.string :name
  end
end

class User < ActiveRecord::Base
  has_many_attached :attachments

  after_save :update_name
  def update_name
    if name == "DHH"
      self.update(name: "David")
    end
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  # Passes
  def test_duplicate_attachments_with_after_save
    user = User.create!(name: "DHH")

    user.attachments.attach([{
      content_type: "text/plain",
      filename: "dummy.txt",
      io: ::StringIO.new("dummy"),
    }])

    assert_equal "David", user.reload.name
    assert_equal 1, user.attachments.count
    assert user.attachments.first.service.exist?(user.attachments.first.key)
  end
end
```
