### ISSUE TITLE
bin/rails t test/jobs/ runs all the tests in test/

### ISSUE THREAD

**Issue by JoeMcNuggets** [rails/rails#41853]
### Steps to reproduce
Having directory test with following layout

```
test
├── application_system_test_case.rb
├── controllers
├── fixtures
│   └── files
├── helpers
├── integration
├── jobs
│   ├── scrape_capacity_job_test.rb
│   ├── scrape_quota_details_job_test.rb
│   ├── scrape_quota_details_job_test.rb~
│   ├── scrape_quota_job_test.rb
│   └── scrape_quota_job_test.rb~
├── models
│   ├── cluster_test.rb
│   ├── cluster_test.rb~
│   ├── env_type_test.rb
│   └── env_type_test.rb~
├── services
│   ├── girls_test.rb
│   └── girls_test.rb~
├── system
├── #test_helper.rb#
├── test_helper.rb
└── test_helper.rb~
```
Running tests with `bin/rails t -p  test/jobs/`

### Expected behavior
It runs only tests from `test/jobs/` 

### Actual behavior
It runs all the tests

### System configuration
**Rails version**: rails (6.0.3.6)

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Comment by eugeneius** [comment]
This was fixed in https://github.com/rails/rails/pull/38814, which I've just backported to the 6-0-stable branch in https://github.com/rails/rails/commit/bd48a0e3d1061d35815a517b764e4a21ae87749f.

The fix was released in Rails 6.1, so you can also get it by upgrading.
