### ISSUE TITLE
Connection closed during migrations under certain circumstances

### ISSUE THREAD

**Issue by joshleblanc** [rails/rails#41855]
MVCE: https://github.com/joshleblanc/sharding-migrations-bug

### Steps to reproduce

Create a new rails application

Create a sharded database with 

```yml
# database.yml
development:
  default:
    database: default
  archive:
    database: archive
```

```ruby
# application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to shards: {
    default: {writing: :default, reading: :default},
    archive: {writing: :archive, reading: :archive}
  }
end
```

Create any model, then add a second migration that queries the database using the model, then runs an `execute` statement.

```ruby
class ThisShouldBreak < ActiveRecord::Migration[6.0]
  def up
    Author.count
    execute "SELECT * from authors"
  end

  def down
    # no-op
  end
end
```

### Expected behavior

The migration should run

### Actual behavior

The connection is closed during the migration, triggering a rollback.

### System configuration
**Rails version**: Rails 6.1.3.1

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]

**Comment by eileencodes** [comment]
Can you see if this is reproducible on master? I am pretty sure I fixed this - but it might not have gotten backported.

**Comment by eileencodes** [comment]
Also, not sure if it's related to the issue you're seeing but if you don't have replicas, you shouldn't create connections for them. You're just doubling the number of open connections to your database with no benefit of using replicas.

```ruby
# application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to shards: {
    default: {writing: :default, reading: :default},
    archive: {writing: :archive, reading: :archive}
  }
end
```

Should be

```ruby
# application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to shards: {
    default: {writing: :default},
    archive: {writing: :archive}
  }
end
```

**Comment by joshleblanc** [comment]
@eileencodes Thanks for the quick response.

Running the MVCE off of master produces the same problem.

Thanks for the tip re: the reading role. Horizontal sharding requires specifying a role when connecting, and the docs didn't really touch on what was required or not, so this is useful to know.

**Comment by eileencodes** [comment]
I have reproduced this and bisected and found that this is caused by https://github.com/rails/rails/pull/39758. Will update again when I have a fix. Not sure how long it will take since this is a little bit of a chicken and egg problem. Just wanted to let you know I haven't forgotten about this.

In the mean time you can "fix" this by using `ActiveRecord::Base.connection.execute` (or the connection you're executing on like `AnimalsRecord.connection.execute`. This is still a bug that needs to get fixed but this will unblock you until I figure it out.
