### ISSUE TITLE
ActiveModel::Attributes - I am able to mutate the default value directly

### ISSUE THREAD

**Issue by james-reading** [rails/rails#41854]
### Steps to reproduce
```
class Foo
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :bars, default: []
end

foo = Foo.new
foo.bars << 1

another_foo = Foo.new
another_foo.bars
=> [1]
```

### Expected behavior
If I mutate the value of an attribute on an instance of Foo, it should not affect the default value for new instances of Foo.

### Actual behavior
Mutating the attribute value will change the default value for new instances.

### System configuration
**Rails version**: 6.1.3

**Ruby version**:  2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]

**Comment by kamipo** [comment]
Use `attribute :bars, default: -> { [] }` instead.
