### ISSUE TITLE
Wrong numericality validation

### ISSUE THREAD

**Issue by marcosdemelo** [rails/rails#41861]
When upgrading to version 5.2.3 of Rails, my test suite had several flaws related to the validation of numerics of larger values.

I made a small script that allows you to simulate the problem from version 5.2.3 of Rails onwards.
In the script I noticed that the `bigdecimal` gem generates interference, but I don't know if the defect is in it or in Rails.

can anybody help me?

### Steps to reproduce

From `Rails/ActiveModel 5.2.3` onwards and `bigdecimal 1.x`

```ruby

# - Open the `irb` 
# - Paste the class below

require 'active_model'
class AClass
  include ActiveModel::Validations

  attr_accessor :a_column

  validates :a_column, numericality: { less_than_or_equal_to: 999_999_999_999.9999 }

  def initialize
    puts "ActiveModel version: #{ActiveModel.version}"
    puts "BigDecimal version: #{BigDecimal::VERSION}\n\n"

    @a_column = 999_999_999_999.9999
  end
end
```

### Expected behavior

```shell
irb(main):017:0> a = AClass.new
ActiveModel version: 5.2.2

BigDecimal version: 1.4.1

=> #<AClass:0x00007fd2689b01d0 @a_column=999999999999.9999>
irb(main):018:0> a.valid?
=> true
irb(main):019:0> a.a_column = 1_000_000_000_000.0000
=> 1000000000000.0
irb(main):020:0> a.valid?
=> false
```

### Actual behavior

From version 5.2.3 of Rails onwards, the `a_column` value is invalid, but returns true

```shell
irb(main):018:0> a = AClass.new
ActiveModel version: 5.2.3

BigDecimal version: 1.4.1

=> #<AClass:0x00007fea515d33e0 @a_column=999999999999.9999>
irb(main):019:0> a.valid?
=> true
irb(main):020:0> a.a_column = 1_000_000_000_000.0000
=> 1000000000000.0
irb(main):021:0> a.valid?
=> true 
```

When using bigdecimal-1.4.1, `.valid?` return true ???

### System configuration
**Rails version**: 5.2.3 or 6.x

**Ruby version**: 2.6.5 and 2.7.2

**Comment by lmansur** [comment]
The `NumericalityValidator` converts floats to `BigDecimal` when validating the values, and, by default, it uses `Float::DIG` (15) as the precision. `999_999_999_999.9999` exceeds that precision, so it's rounded to `1_000_000_000_000.0` when it's converted to `BigDecimal`.

If you need that level of precision, it might be a good idea to use `BigDecimal` instead of a float.

**Comment by marcosdemelo** [comment]
Thanks @lmansur, I will configure like this!
