### ISSUE TITLE
New postgres connection opened during migrations on production but not development

### ISSUE THREAD

**Issue by thornomad** [rails/rails#41865]
> I am unsure if this is a bug or a configuration error on my part.  Apologies in advance and thanks for any insight.

I am having an issue with a migration that succeeds locally (on development machines) but fails on production (we are using Heroku).  It appears that a new connection is being opened during the migration on production that is not opened locally (see below for a full rundown). 

Here is an example migration in its simplest reproducible step:

```ruby
# Adds column `test` and sets values for each record in the table
class AddTestColumnToRecurrences < ActiveRecord::Migration[6.1]
  def change
    add_column :recurrences, :test, :string

    up_only do
      Recurrence.find_each do |recurrence|
        recurrence.update!(test: "Example insert: #{recurrence.summary}")
      end
    end

    change_column_null :recurrences, :test, false
  end
end
```

This works on our development machines (as I believe it should) however in production it is failing with a `ActiveModel::UnknownAttributeError` for the newly added column `test`.

This was unexpected.

### Debugging

I tried using `Recurrence.reset_column_information` and that did not help.

Inside the migration itself I examined logged the content of `Recurrence.column_names` during the migration and while I can see the new column `#test` on local/development it is absent on production (as if the previous migration line was not even running).

I then added some debug logging [here](https://github.com/rails/rails/blob/v6.1.3/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L26) to see if perhaps a new connection was being established between the `ALTER TABLE` statement and the `#update!` attempt.

```ruby
module ActiveRecord
  module ConnectionHandling # :nodoc:
    # Establishes a connection to the database that's used by all Active Record objects
    def postgresql_connection(config)
      puts "==Established New Connection=="
      # ...
```

When I run the migration *locally*, I get expected output similiar to:

```text
==Established New Connection==
== 20210326201141 AddTestColumnToRecurrences: migrating =======================
-- add_column(:recurrences, :test, :string)
   -> 0.0026s
-- Testing adding a column via direct sql execution
-- execute("UPDATE recurrences SET test = 'Example test Every for the next four days (or something
 like that)' WHERE id = 1")
   -> 0.0027s
   -> 0.0258s
-- change_column_null(:recurrences, :test, false)
   -> 0.0015s
== 20210326201141 AddTestColumnToRecurrences: migrated (0.0302s) ==============
```

However, when I run it on *production*, there an additional connection being established after the column is added:

```text
==Established New Connection==
I, [2021-04-06T20:44:40.934957 #13]  INFO -- : Migrating to AddTestColumnToRecurrences (20210326201141)
== 20210326201141 AddTestColumnToRecurrences: migrating =======================
-- add_column(:recurrences, :test, :string)
   -> 0.0047s
-- Testing adding a column via direct sql execution
==Established New Connection==       ##### <-- EXTRA CONNECTION HERE! ######
-- execute("UPDATE recurrences SET test = 'Example test Every for the next four days (or something like that)' WHERE id = 1")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
```

For some reason, this additional connection is being established.  I suspect that by creating a new connection it makes the newly added column "unrecognizable" as it has not yet been committed in the currently open database transaction (in a different connection).

### Workaround

I can work around this issue by defining the `Recurrence` class inside the migration class.  Such as:

```ruby
class AddTestColumnToRecurrences < ActiveRecord::Migration[6.1]
  class Recurrence < ApplicationRecord; end

  def change
    # ... same code here
  end
end
```

When I do this, the "extra" connection is not started and the migration passes both locally and in production.

### Help needed

We are upgrading our application from 5.2 to 6.1 and just started testing it on production (as a staging).  This hiccup though is causing a bit of a headache and would like to try and sort out why this extra connection is being established on production!

I am not sure where to look, honestly; I wanted to make sure this behavior was indeed unexpected and if there was some place I could start digging further.

Thanks for your help.

### System configuration
**Rails version**: 6.1.3
**Ruby version**: 2.7.2

**Comment by malclocke** [comment]
I'd recommend as a first step if you can run the migration locally with `RAILS_ENV=production` and see if you can reproduce the error that way.

That may help you to narrow down whether the problem is in your application / Rails, or something specific to Heroku.
