### ISSUE TITLE
Docs: Preloader refers to incorrect information about `find`

### ISSUE THREAD

**Issue by runephilosof-abtion** [rails/rails#41879]
There are two problems with this
https://github.com/rails/rails/blob/2ed5ba7f9f7f316d447f7b2151122332037d3506/activerecord/lib/active_record/associations/preloader.rb#L80-L81

1. It should refer to `{ActiveRecord::Base.find}[rdoc-ref:FinderMethods#find]`.
2. Find does not accept an `include` option.

**Comment by p8** [comment]
Seeing this comment is 10 years old, it refers to how `find` used to work:
```ruby
Post.find(:all, include: [:books])
```
The comment should probably be changed to something like:
```
      # +:associations+ has the same format as the +:includes+ method for
      # <tt>ActiveRecord::QueryMethods</tt>. So +associations+ could look like this:
```
Do you want to make a PR?

**Comment by rafaelfranca** [comment]
BTW, both the method and the class you are pointing is not part of the public API of the framework yet https://github.com/rails/rails/blob/2ed5ba7f9f7f316d447f7b2151122332037d3506/activerecord/lib/active_record/associations/preloader.rb#L45, so it should not be used directly in applications.
