### ISSUE TITLE
inverse association in `after_create` inherits `where` conditions of `where(conditions).create!` 

### ISSUE THREAD

**Issue by MathieuDerelle** [rails/rails#41883]
weird behavior is happening on 4.2.11.3 and 5.2.5 
(3.2.22.5 and 6.1.3.1 are behaving as expected)

### Steps to reproduce

(sorry im not sure how to create an Executable Test Case for an SQL query in an after_create)

1. choose a rails version

```bash
version=4.2.11.3
version=5.2.5
version=6.1.3.1
```

2. install rails and create basic models

```
rails new "rails-${version}" "_${version}_" --database=postgresql
cd "rails-${version}"

rails g model Post title:string content:text
rails g model Comment name:string comment:text
rails g migration AddPostIdToComments
```

3. update files as follows : 
```
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
end

class Comment < ApplicationRecord
  belongs_to :post

  after_create do
    puts '--- after_create'
    post.comments.to_a
  end
end

class AddPostIdToComments < ActiveRecord::Migration[6.1]
  def change
    add_reference :comments, :post, foreign_key: true
  end
end
```

4. `bundle exec rake db:create db:migrate`

5. launch console `rails c --sandbox`

6. execute the following code
```
p = Post.create!(title: 'my title', content: 'my content')
Comment.where(name: 'my name', comment: 'bla bla', post: p).create!
```

### Expected behavior
The DB query created by `post.comments.to_a` in `Comment.after_create` should only have a condition on post
something like
```
SELECT * FROM comments WHERE post_id = 1
```

### Actual behavior

conditions from the `where` (`Comment.where(name: 'my name', comment: 'bla bla', post: p).create!`)
are in the association query : 

```
Comment Load (0.3ms)  SELECT "comments".* FROM "comments" WHERE "comments"."name" = $1 AND "comments"."comment" = $2 AND "comments"."post_id" = $3  [["name", "my name"], ["comment", "bla bla"], ["post_id", 2]]
```

### System configuration

- weird behaviod on :

**Rails version**: 4.2.11.3
**Ruby version**: 2.6.6

and

**Rails version**: 5.2.5
**Ruby version**: 2.6.6

- expected behavior on : 

**Rails version**: 3.2.22.5
**Ruby version**: 2.2.9

and

**Rails version**: 6.1.3.1
**Ruby version**: 2.6.6

**Comment by MathieuDerelle** [comment]
is there a quick fix to apply in the `after_create` ?

`post.comments.unscoped.to_a` would juste give `SELECT * FROM comments` and loose the association condition

**Comment by kamipo** [comment]
Leaky scoping is fixed in Rails 6.1 #39181.

**Comment by MathieuDerelle** [comment]
no backport in rails 5 ?

**Comment by kamipo** [comment]
Yes, only the latest release series will receive bug fixes.

https://guides.rubyonrails.org/maintenance_policy.html#bug-fixes
