### ISSUE TITLE
Active Storage blob is attached once but unattached later on

### ISSUE THREAD

**Issue by colmexdev** [rails/rails#41895]
I'm struggling with Active Storage recently in a project where I just updated gem versions. It seems that Active Storage is attaching the blob to the record but then detaches later on and it's breaking my views where I call **rails_blob_{path|url}**. I appreciate any help on figuring what's going on and what can be causing this.

### Steps to reproduce
1. Create a model with an attached blob.
2. Save a blob to a record of that model.

### Expected behavior
The blob can be accessed anytime (e.g. calling **rails_blob_{path|url}**) because it should be attached.

### Actual behavior
Blob seems to be detached, although records are saved in ActiveStorage::Blob and ActiveStorage::Attachment. Blob even exists in the path where it should be according to its **key** value in ActiveStorage::Blob. Calls to **<record>.<blob>.attached?** returns false anytime.

### System configuration
**Rails version**: 6.1.3.1
**Ruby version**: 3.0.0

**Comment by gmcgibbon** [comment]
I can't reproduce the issue. Please provide a trivial app demonstrating the issue. Thanks!

**Comment by colmexdev** [comment]
Sorry for the delay, I managed to solve it. It seemed to be something with the schema path (using PostgreSQL and Disk storage). I use several instances of Active Storage because I have quite some projects living in the same server, so I think the wrong schema path caused wrong ActiveStorage::Blob and ActiveStorage::Attachment tables to be queried. Nonetheless, it was pretty misleading that it failed silently and not giving advice on the blob's retrieval.

   Thank you very much for your time. Wish this kind of errors could be traceable somehow.
