### ISSUE TITLE
Remote connections disconnect throws ArgumentError. Rails 6.1.3.1 Ruby 3.0.1

### ISSUE THREAD

**Issue by danielyazbek** [rails/rails#41890]
### Steps to reproduce
ActionCable.server.remote_connections.where(current_user: User.find(1)).disconnect

### Expected behavior
Disconnects the user

### Actual behavior
ArgumentError is thrown
ArgumentError:
       wrong number of arguments (given 1, expected 2)
     # .rvm/gems/ruby-3.0.1@gemset/gems/actioncable-6.1.3.1/lib/action_cable/server/broadcasting.rb:24:in `broadcast'
     # .rvm/gems/ruby-3.0.1@gemsetgems/actioncable-6.1.3.1/lib/action_cable/remote_connections.rb:48:in `disconnect'

### System configuration
**Rails version**:
6.1.3.1

**Ruby version**:
3.0.1

**Comment by georgeclaghorn** [comment]
Fixed in #41673. Will go out in 6.1.4.
