### ISSUE TITLE
ActiveRecord::Base.filter_attributes doesn't filter SQL logs

### ISSUE THREAD

**Issue by stouset** [rails/rails#41896]
### Steps to reproduce

```ruby
Rails.application.config.filter_parameters += %i[
  sekret
]

class Foo < ActiveRecord::Base
  attribute :sekret
end

Foo.find_by(sekret: 'abc')
```

### Expected behavior

This correctly filters `sekret` in controller parameters and from the record in the console, but `sekret` is still logged to `development.log`, `test.log`, and `production.log` when queried. It should also filter logs written to disk.

### Actual behavior

```sh
$ tail -f log/production.log | grep "Foo Load"
  Foo Load (0.7ms)  SELECT "foos".* FROM "foos" WHERE "foos"."sekret" = $1 LIMIT $2  [["sekret", "abc"], ["LIMIT", 1]]
```

### System configuration
**Rails version**: 6.1.3
**Ruby version**: 3.0.1

**Comment by stouset** [comment]
Pretty sure this is a security issue. Any sensitive data that's stored in the database is logged to disk on both insertion and query.

**Comment by rafaelfranca** [comment]
Default log level of Rails application in production is `:info` and the `:info` log level doesn't log any SQL queries. If you are using `:debug` in production I'm afraid you could be logging way more than just sensitive data. We don't recommend using `:debug` in production, and if you are, you should be making sure PII and sensitive data is not being logged.

**Comment by stouset** [comment]
Fair enough. I'll just say that people turn on debug logs all the time in production, and 

> and if you are, you should be making sure PII and sensitive data is not being logged.

rings a little hollow if Rails doesn't actually provide any mechanism to accomplish this. I'd expect that `ActiveRecord::Base.filter_attributes` (or `Rails.application.config.filter_parameters`, which sets that value) filters those attributes in logs.

**Comment by rafaelfranca** [comment]
We can definitely improve it to filter by default but this is not a security bug in the framework in my opinion. Feel free to open a PR.

**Comment by stouset** [comment]
Since it's only `debug` logs, I agree it's not a security bug. It's been awhile since I've worked with Rails as intimately and didn't remember that the `info` level doesn't directly log SQL queries.

**Comment by aishbuilds** [comment]
@stouset: If you don't mind, I'd like work on this issue. 

Opened https://github.com/rails/rails/pull/42006 for the fix.

**Comment by pixeltrix** [comment]
Just to add some context - the Rails default changed to `:info` in 6.1 (https://github.com/rails/rails/commit/229fd2a02fc694b4b7756445b6647777aa94e25d) so if your app was generated in an earlier version I'd double check your setting in production.rb as I see a lot of apps with it set to `:debug`.

**Comment by aishbuilds** [comment]
Is there a way we can get a maintainer with capacity help review the PR for this fix: https://github.com/rails/rails/pull/42006 ?

Thanks!

**Comment by stouset** [comment]
All this needs is a maintainer to look at the PR, approve it, and merge.
