### ISSUE TITLE
ActiveStorage attachment not saved to disk when adding attachments to a new record inside a transaction

### ISSUE THREAD

**Issue by siefkenj** [rails/rails#41903]
### Steps to reproduce
Set up `ActiveStorage` to use the local disk store.
Create a model that has many attachments and within the same transaction create a new instance, save it, and then add attachments.

### Expected behavior
The appropriate blobs are created and the relevant files are saved to disk.

### Actual behavior
The blobs are created, but the files are never saved to disk. (A `Disk Storage` message never appears in the logs.) If I move `application.documents.attach` out of the transaction, everything works as expected (and a `Disk Storage` message appears in the logs).

If an existing record is being updated inside a transaction instead of created, everything appears to work correctly.

### System configuration
**Rails Version**: 6.1.3

**Ruby Version**: 2.6.6p146

**Comment by gmcgibbon** [comment]
Creating and attaching on the same transaction results in `SQLite3::BusyException: database is locked` on a new app. Are you using something other than SQLite? Please provide a trivial app that demonstrates this behaviour.

**Comment by siefkenj** [comment]
I am using the Postgres backend. I'll see what I can do about an example.

**Comment by lfalcao** [comment]
Duplicate of https://github.com/rails/rails/issues/41661 ?

**Comment by siefkenj** [comment]
> Duplicate of #41661 ?

Yes. It appears so. Closing for now.
