### ISSUE TITLE
stylesheet_link_tag should can use extname param

### ISSUE THREAD

**Issue by nyrf** [rails/rails#41918]
I want to use a less or sass file with <%= stylesheet_link_tag '/custom/main.less' %>, but stylesheet_link_tag seems can't  accept extname param, https://github.com/rails/rails/blob/1598ad5c4bc74e26fd9337b33a4b514b404998cd/actionview/lib/action_view/helpers/asset_tag_helper.rb#L152

### Steps to reproduce
` <%= stylesheet_link_tag '/custom/main.less' %>`

### Expected behavior
` <link rel="stylesheet" media="screen" href="/custom/main.less" />`

### Actual behavior
` <link rel="stylesheet" media="screen" href="/custom/main.less.css" />`

### System configuration
**Rails version**: 6.1.3
**Ruby version**: 3.0.0

**Comment by gmcgibbon** [comment]
If the browser doesn't understand less or sass without transpiling, what is the use-case for this behaviour?

**Comment by nyrf** [comment]
> If the browser doesn't understand less or sass without transpiling, what is the use-case for this behaviour?

Use vite and rails.

**Comment by gmcgibbon** [comment]
> Use vite and rails. The main reason is that sometimes we want to use `extname: false` to make `stylesheet_link_tag ` doesn't  add `.css` suffix to filename.

Yes, I understand that part, but with vite (and most other modern frontend tooling) you typically manage css via js imports. Even if vite doesn't bundle your assets, it preprocesses them somehow, right? I'm not seeing why you would want to expose something browsers can't understand in a link tag.

**Comment by nyrf** [comment]
> Yes, I understand that part, but with vite (and most other modern frontend tooling) you typically manage css via js imports. Even if vite doesn't bundle your assets, it preprocesses them somehow, right? I'm not seeing why you would want to expose something browsers can't understand in a link tag.

Sometimes, we need make a sass file as vite's entry, then we don't need `stylesheet_link_tag`  add `.css` ext to the filename,


eg  i  want link a scss file `admin.scss`

```ruby
  <%= stylesheet_link_tag "admin.scss'' %>
```

this will become `<link rel="stylesheet" media="screen"  href="/stylesheets/admin.scss.css">`, but i want to get `<link rel="stylesheet" media="screen"  href="/stylesheets/admin.scss">`

https://github.com/ElMassimo/vite_ruby/blob/main/vite_ruby/lib/vite_ruby/dev_server_proxy.rb#L36
