### ISSUE TITLE
ActiveStorage ImageAnalyzer does not support Vips

### ISSUE THREAD

**Issue by wilg** [rails/rails#41941]
Since ActiveStorage can use Vips for everything else, it doesn't make sense that mini_magick and ImageMagick are required to get the image size.

**Comment by p8** [comment]
Hi @wilg 👋 
I was just going to link to https://github.com/janko/image_processing/issues/41 and then noticed you already found that ticket :)

**Comment by wilg** [comment]
Here's my Vips implementation in case this is useful to someone:

```rb
class VipsImageAnalyzer < ActiveStorage::Analyzer
  def self.accept?(blob)
    blob.image?
  end

  def metadata
    read_image do |image|
      (width, height) = image.autorot.size
      {width: width, height: height}
    end
  end

  private def read_image
    download_blob_to_tempfile do |file|
      image = Vips::Image.new_from_file(file.path)
      yield image
    end
  end
end
```

Then swap it with the default in an initializer with:

```rb
Rails.application.config.active_storage.analyzers.delete ActiveStorage::Analyzer::ImageAnalyzer
Rails.application.config.active_storage.analyzers.append VipsImageAnalyzer
```

**Comment by wilg** [comment]
The primary reason I need this is that the default analyzer is incorrect https://github.com/rails/rails/issues/41940

**Comment by p8** [comment]
It would be nice if you only had to override a `image` method in a ActiveStorage::Analyzer::ImageAnalyzer subclass.

**Comment by wilg** [comment]
Agree, seems like image_processing could easily provide some limited metadata support so Rails doesn't have to reinvent the wheel.
