### ISSUE TITLE
ActiveRecord invalid query parameter constructed when using where(entity: array_of_entities)

### ISSUE THREAD

**Issue by ttibensky** [rails/rails#41959]
### Steps to reproduce

we were doing:
```ruby
users = User.find([123456, 654321])
scope = scope.where(user: users)
```
also tried:
```ruby
scope = scope.where(user: users.pluck(:id))
```
but that didn't work either - the query didn't return any results. We "fixed" it with this
```ruby
scope = scope.where("random_table.user_id IN (?)", users.pluck(:id))
```
which is not producing this query:
```sql
SELECT "random_table".* FROM "random_table" WHERE (user_id IN (123456,654321)) AND (created_at >= '2020-12-31 23:00:00' AND created_at <= '2021-12-31 22:59:59.999000') ORDER BY "random_table"."created_at" DESC
```
and now it also returns correct results.

### Expected behavior

```
RandomTable Load (0.3ms)  SELECT "random_table".* FROM "random_table" WHERE "random_table"."user_id" IN ($1) AND (created_at >= '2020-12-31 23:00:00' AND created_at <= '2021-12-31 22:59:59.999000') ORDER BY "random_table"."created_at" DESC  [123456, 654321]
```

### Actual behavior
```
RandomTable Load (0.3ms)  SELECT "random_table".* FROM "random_table" WHERE "random_table"."user_id" IN ($1, $2) AND (created_at >= '2020-12-31 23:00:00' AND created_at <= '2021-12-31 22:59:59.999000') ORDER BY "random_table"."created_at" DESC  [[nil, 123456], [nil, 654321]]
```

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 2.7.2

**Comment by p8** [comment]
Hey @ttibensky, :wave: thanks for reporting this bug.

Could you reproduce this bug with a bug report template?
It helps others to reproduce the bug and hopefully fix it.
https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb

**Comment by A7madXatab** [comment]
> ```ruby
> scope = scope.where(user: users.pluck(:id))
> ```

Though it might not be related to question, rails has a helper for retrieving model ids

```ruby
scope = scope.where(user: users.ids)
```

is the same as 

```
scope = scope.where(user: users.pluck(:id))
```

**Comment by A7madXatab** [comment]
> ```ruby
> scope = scope.where(user: users.pluck(:id))
> ```

One this here, have you tried doing it this way

```ruby
users = User.find([123456, 654321])
scope = scope.where(user_id: users)
```

I think that should fix the issue, let me know if it works or not.

**Comment by ttibensky** [comment]
> > ```ruby
> > scope = scope.where(user: users.pluck(:id))
> > ```
> 
> One this here, have you tried doing it this way
> 
> ```ruby
> users = User.find([123456, 654321])
> scope = scope.where(user_id: users.ids)
> ```
> 
> I think that should fix the issue, let me know if it works or not.

sure, here is the result:

```ruby
users = User.find(params[:users])
scope = scope.where(user_id: users.ids)
```
```
undefined method `ids' for #<Array:0x00007f212924be08>
```

**Comment by A7madXatab** [comment]
> sure, here is the result:
> 
> ```ruby
> users = User.find(params[:users])
> scope = scope.where(user_id: users.ids)
> ```
Sorry it seems the answer i gave was wrong one.


> > > ```ruby
> > > scope = scope.where(user: users.pluck(:id))
> > > ```
> > 
> > 
> > One this here, have you tried doing it this way
> > ```ruby
> > users = User.find([123456, 654321])
> > scope = scope.where(user_id: users.ids)
> > ```
> > 
> > 
> > I think that should fix the issue, let me know if it works or not.
> 
> sure, here is the result:
> 
> ```ruby
> users = User.find(params[:users])
> scope = scope.where(user_id: users.ids)
> ```
> 
> ```
> undefined method `ids' for #<Array:0x00007f212924be08>
> ```

are the result of this line

```ruby
users = User.find(params[:users])
```

an `Array` or `ActiveRecordAssociationRelation` ?

I'm trying to achieve the same thing as u everything works for me

```ruby
 businsesss= Business.find([1,4])   

 Conversation.where(business: businsesss)
```

everything seems to run fine for me. But note that the `businesses` variable is an `ActiveRecordAssociationRelation` type

what is the `scope` variable in your code ?

**Comment by p8** [comment]
@ttibensky 
You might have more luck using where instead of find:
```
  users = User.where(id: [123456, 654321])
  users.ids # => [123456, 654321]
  scope = scope.where(user: users)
```

**Comment by ttibensky** [comment]
> Hey @ttibensky,  thanks for reporting this bug.
> 
> Could you reproduce this bug with a bug report template?
> It helps others to reproduce the bug and hopefully fix it.
> https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb

I tried to reproduce it using the template, it produces the same weird-looking query but it actually returns the correct results. See below.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class User < ActiveRecord::Base

end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    user = User.create!

    post = Post.create!
    post.comments << Comment.create!

    post2 = Post.create!
    post2.comments << Comment.create!

    post3 = Post.create!
    post3.comments << Comment.create!

    assert_equal 1, post.comments.count
    assert_equal 3, Comment.count
    assert_equal post.id, Comment.first.post.id

    posts = Post.find([1, 2])
    comments = Comment.where(post: posts)

    assert_equal comments.first&.id, 1
    assert_equal comments.last&.id, 2
  end
end
```
```
D, [2021-04-15T11:39:20.932433 #803] DEBUG -- :   Post Load (0.0ms)  SELECT "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
D, [2021-04-15T11:39:20.932753 #803] DEBUG -- :   Post Load (0.1ms)  SELECT "posts".* FROM "posts" WHERE "posts"."id" IN (?, ?)  [[nil, 1], [nil, 2]]
D, [2021-04-15T11:39:20.933204 #803] DEBUG -- :   Comment Load (0.2ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" IN (?, ?) ORDER BY "comments"."id" ASC LIMIT ?  [[nil, 1], [nil, 2], ["LIMIT", 1]]
D, [2021-04-15T11:39:20.933467 #803] DEBUG -- :   Comment Load (0.0ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" IN (?, ?) ORDER BY "comments"."id" DESC LIMIT ?  [[nil, 1], [nil, 2], ["LIMIT", 1]]
.

Finished in 0.015562s, 64.2574 runs/s, 321.2869 assertions/s.

1 runs, 5 assertions, 0 failures, 0 errors, 0 skips
```

I will try to dig deeper to see why this can be hapenning.
