### ISSUE TITLE
Direct Upload not working on heroku active admin deployment

### ISSUE THREAD

**Issue by fedeagripa** [rails/rails#41968]
### Steps to reproduce
I have a form with direct upload and input fields with direct upload too, but yet upload is being done as usual.
My code:
`admin/fighter.rb` 
```
form multipart: true, direct_upload: true do |f|
    input :first_name
    input :last_name
    input :country
    input :reach
    input :height
    input :price_tier, include_blank: false
    input :birthdate, start_year: 1900
    input :organization
    input :preview_url
    f.input :cover_photo, as: :file
    f.input :profile_pic, as: :file
    f.inputs do
      f.input :public_videos, as: :file, input_html: { multiple: true, direct_upload: true }
    end
    f.inputs do
      f.input :private_videos, as: :file, input_html: { multiple: true, direct_upload: true }
    end
    f.actions
  end
```

### Expected behavior
Video content should be direct uploaded to S3 instead of waiting on client side

### Actual behavior
Form submition takes more than 30 seconds and due to heroku timeout it end up in a 503 error

### System configuration
**Rails version**: 6.0.0

**Ruby version**: 2.7.2

**Comment by p8** [comment]
Hi @fedeagripa,
This seems like an ActiveAdmin issue.
Make sure the ActiveStorage javascript is enabled and CORS headers are set as described in the guides:
https://guides.rubyonrails.org/active_storage_overview.html#usage

**Comment by fedeagripa** [comment]
@p8 Hi! thanks for jumping in
ActiveStorage js is enabled like this (I'm using webpacker):
![Screen Shot 2021-04-14 at 15 45 03](https://user-images.githubusercontent.com/23194751/114762695-639e9a00-9d38-11eb-98a1-cea3f3faab57.png)

And I checked my CORS configuration in my s3 bucket, should I be checking anything about CORS in my rails app?

Here is my ActiveAdmin input generated code just in case it helps finding out the problem:
![Screen Shot 2021-04-14 at 15 32 20](https://user-images.githubusercontent.com/23194751/114761414-d149c680-9d36-11eb-8640-303f9bb52295.png)

And the moment I click on the submit button on the form this is the trace for my backend, is that right? Because that lead me to think that direct upload is not working and my backend is waiting for client side to upload the video (?)
<img width="1221" alt="Screen Shot 2021-04-14 at 15 46 52" src="https://user-images.githubusercontent.com/23194751/114762939-a496ae80-9d38-11eb-8003-29dcf466574f.png">

**Comment by p8** [comment]
Hey @fedeagripa,
Looking at the data-direct-upload-url (http://localhost:3000/rails/active_storage/direct_uploads), it seems you haven't configured a remote service like S3, which is required for direct uploads.

**Comment by fedeagripa** [comment]
@p8 right thats strange 🤔 
I have `config.active_storage.service = :amazon` in my `environments/development.rb` and the aws keys configured properly in my ENV. Also my storage.yml is properly set to fetch the env vars 😕 

Here is my staging input and seems to have the same issue besides is also configured with amazon storage
![Screen Shot 2021-04-15 at 12 59 45](https://user-images.githubusercontent.com/23194751/114900719-87221d00-9dea-11eb-8ccd-961531474be0.png)

I have re checked active storage doc and it seems i'm not forgetting any file or configuration. Could it be possible that ActiveAdmin forms are different and so something does not match accordingly? That wont explain why my url looks like local disk anyways....

**Comment by p8** [comment]
Sorry, my mistake the url is correct.
Are you maybe processing the videos inline instead of in a background job?

**Comment by fedeagripa** [comment]
Yes the files will be huge indeed, locally I can upload them with s3 configuration, but heroku does have a 30 sec timeout limitation. Unfortunately heroku only provides a jquery implementation that looks like re inventing the wheel for me initially https://devcenter.heroku.com/articles/direct-to-s3-image-uploads-in-rails .

I understood that placing the direct upload tag in my inputs would do the trick to don't process the videos, completely open to try new options if thats not the case.
And would try on discussions as you propose, Thanks!

**Comment by fedeagripa** [comment]
I'm closing this as the error finally was a js note being loaded properly by webpacker and that's why my uploads where not working. Thanks everyone for comments and research 😃
