### ISSUE TITLE
`rails test:system` and `rails test:all` don't support `rails test` arguments like verbose or seed

### ISSUE THREAD

**Issue by arielj** [rails/rails#41976]
### Steps to reproduce

Run `rails test:system` with options like `rails test:system -v`, `rails test:system --seed=1234` or `rails test:system -p`.

### Expected behavior

Command should handle the arguments like `rails test` does, to be able to run system tests with a given seed or with a verbose output for debugging.

### Actual behavior

- Some arguments are ignored (like `-v`)
- Some arguments produce an `OptionParser::MissingArgument` exception (like `-p`)
- Some arguments just shows an `invalid option` error (like `--seed=1234`)
- Some arguments respond with an incorrect output (like `-h`, display the `rails` command help instead)

My current workaround is to do `rails test -v -p test/system/` or `rails test -v --seed=1234 test/` (to mimic `test:all`)

#### Some research

I understand that the problem is here https://github.com/rails/rails/blob/main/railties/lib/rails/commands/rake/rake_command.rb#L19

Args are handled as arguments for the `rails` command instead of arguments for the task (that's why -h displays the rails help and --seed shows an invalid option and -p expect the value).

Another issue is that the rake task is not sending the arguments to the rake_run command here https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/railties/lib/rails/test_unit/testing.rake#L57

Changing it to:

```ruby
Rails::TestUnit::Runner.rake_run(["test/system", *ARGV])
```
makes `rails test:system -v` work.

I assume that makes all the arguments work if only the code would reach that point (with `-p` or `--seed` it fails before this call at `rake_command.rb#19`).

I'd be happy to make a PR if somebody can point me in the right direction. I understand that the problem is how to get `rake_command.rb#19` to use the args for the rake task and not for the rails command.

### System configuration
**Rails version**:
Latest commit in the main branch. But can be reproduced with other versions (tried with 6.0.1 too).

**Ruby version**:
Ruby 2.7.2 right now, but happens with any Ruby version (tried with 2.6.6 too)

**Comment by jamie** [comment]
I'd love to see this (plus PR #42009) get a bit of love.

I'm working with a toy Rails 7.0.3 project using minitest on CircleCI using [minitest-junit](https://github.com/aespinosa/minitest-junit) to build XML reports for their test reporting. While I can use `bundle exec rails test --junit` and get results, I can't do that with `bundle exec rails test:system --junit`.

**Comment by skipkayhil** [comment]
It looks like most of this was fixed by #44106 (for all of the metaprogrammed methods), but `test:system` still raises with extra args. @etiennebarrie do you remember if there was a reason the `all`, `system` and `generators` methods don't accept `(*)` like the `define_method` methods do?

**Comment by jamie** [comment]
Ah, thanks for the pointer to that PR @skipkayhil - I just bumped my app to edge rails to test against, can confirm with a better stack trace:

```shellsession
➜  bundle exec rails test:system --junit --junit-filename=test/reports/report.xml
/Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:525:in `handle_argument_error': ERROR: "rails system" was called with arguments ["--junit", "--junit-filename=test/reports/report.xml"] (Thor::InvocationError)
Usage: "rails test [options]"
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:34:in `rescue in run'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:20:in `run'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/bundler/gems/rails-2f5dcb7255e5/railties/lib/rails/command/base.rb:87:in `perform'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/bundler/gems/rails-2f5dcb7255e5/railties/lib/rails/command.rb:48:in `invoke'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/bundler/gems/rails-2f5dcb7255e5/railties/lib/rails/commands.rb:18:in `<main>'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
/Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/bundler/gems/rails-2f5dcb7255e5/railties/lib/rails/commands/test/test_command.rb:51:in `system': wrong number of arguments (given 2, expected 0) (ArgumentError)
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/bundler/gems/rails-2f5dcb7255e5/railties/lib/rails/command/base.rb:87:in `perform'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/bundler/gems/rails-2f5dcb7255e5/railties/lib/rails/command.rb:48:in `invoke'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/bundler/gems/rails-2f5dcb7255e5/railties/lib/rails/commands.rb:18:in `<main>'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/jamie/code/realworld-rails-hotwire/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
```

and also that a spot change of method signature to `system(*)` gets things running as I'd expect.

**Comment by etiennebarrie** [comment]
Sorry I hadn't seen that and when I fixed the issue [mentioned in the review](https://github.com/rails/rails/pull/44106#discussion_r851253606) I haven't been thorough 😬 

Created a PR in #45439
