### ISSUE TITLE
has_and_belongs_to_many association: link existing AND non-existing relations at the same time

### ISSUE THREAD

**Issue by littletime** [rails/rails#41986]
Hi,

This is not really a bug report but I've been having an issue with the following situation:

We have two models with a simple `has_and_belongs_to_many` relationship, `MissionOffer` and `Skill`, linked by a join table.
When creating a `MissionOffer`, we want to enable the user to create **and/or** link existing `Skills` to it.

If we create a mission offer this way:
`mo = MissionOffer.create(skill_ids: [1, 3])`
The link to existing skills is properly done.

Also, if we create it this way:
`mo = MissionOffer.create(skills_attributes: [{ label: "first skill"}, { label: "second_skill"}])`
The new skills are correctly being created and linked.

## Issue

If we pass both `skill_attributes` and `skill_ids` to the MissionOffer at creation, Rails will **only** consider the skill_ids array, and won't create the new skills from skills_attributes array.

I'm not sure about whether I'm missing something here and this could be accomplished in a totally different approach, or if this is maybe a bug in Active Record that stops interpreting data for a specific relationship after the "relationship"_ids property is passed.

Thanks for reading!

**Rails version**: 6.1.3.1

**Ruby version**: 2.7.3

**Comment by ChaelCodes** [comment]
I was able to reproduce this, but only if the attributes were the first key. @littletime, you can avoid this issue by saying `MissionOffer.create(skill_ids: [1, 3], skills_attributes: [{ label: "first skill"}, { label: "second_skill"}])`.

https://gist.github.com/ChaelCodes/3923597e7a72c294a145a182b4135fa4

I'll continue to investigate and see if I can find out why.

**Comment by ChaelCodes** [comment]
Further examination shows that `foos_attributes` are only used to create new associated objects, and update existing ones. `foo_ids` will replace any existing associations with its list of objects.

If `foo_ids` is called with a list of new ids first, then `foos_attributes` can update the newly created list of ids with new attributes and changes.

I wonder if the best option is to reorder the attributes, but there's no concept of reordering attributes in Rails.

**Comment by littletime** [comment]
@ChaelCodes thank you very much for investigating, I've been able to make it work having `skill_ids` before the `skills_attributes` :)

I do find this kind of weird.. I know there's a side of magic with ActiveRecord models that makes all those relationship attributes possible, but having the order of the attributes change the model's behaviour is something I did not expect
