### ISSUE TITLE
actionview initialize expects 3 arguments and fails to initialize with 0 arguments form application startup

### ISSUE THREAD

**Issue by danielbidwell** [rails/rails#41985]
### System configuration
**Rails version**:

**Ruby version**:

**Comment by danielbidwell** [comment]
With ruby 3.0.0p0 and rails 6.1.3.1, starting an application that uses actionview I get the following error on initializatino:
.rvm/gems/ruby-3.0.0/gems/actionview-6.1.3.1/lib/action_view/base.rb:230:in `initialize': wrong number of arguments (given 0, expected 3) (ArgumentError)
I am in the process of updating the application from very old versions of ruby and rails.  Now it will not start due to initialization errors.

**Comment by zsolt-lukacs** [comment]
I'm having exactly the same issue and can't figure out what's causing it.
Did you manage to solve it, and if yes could you please tell me how?
Thanks!

**Comment by danielbidwell** [comment]
No, I avoided upgrading to a newer version that was causing this
problem.  The client expects to replace the application before we have
to face this problem.

On Wed, 2021-05-12 at 07:13 -0700, zsolt-lukacs wrote:
> I'm having exactly the same issue and can't figure out what's causing
> it.
> Did you manage to solve it, and if yes could you please tell me how?
> Thanks!
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
-- 
Daniel R. Bidwell       |       ***@***.***
Former Sr. Systems Architect   |       former Chief Information Security Officer
Andrews University      |       Information Technology Services
If two always agree, one of them is unnecessary.
Karma is getting what you deserve,
mercy is not getting what you deserve
grace is getting what you do not deserve.
In theory, theory and practice are the same.
In practice, they are not.

**Comment by zsolt-lukacs** [comment]
thank you
