### ISSUE TITLE
Dynamic Table Name Prefix

### ISSUE THREAD

**Issue by rhuanbarreto** [rails/rails#41995]
Is rails capable of supporting changing the table name prefix at runtime?

From what I have tested, it seems that the value is cached during initialisation and then it can't be changed. Only restarting the server loads the new value again.

### Steps to reproduce
1. Install Devise and add an attribute `company` to an user through an migration and adding it as an attribute on the User model.
2. Define a Current model to use thread safe attributes
```ruby
class Current < ActiveSupport::CurrentAttributes
  attribute :company
end
```
3. Load the current user on application_controller.rb through an callback
```ruby
class ApplicationController < ActionController::Base
  before_action -> { Current.company = current_user.company if current_user }
end
```
4. Define the dynamic table_name_prefix on the main model.
```ruby
class ApplicationRecord < ActiveRecord::Base
  def self.table_name_prefix
        company = Current.company || "default_company_"
  end
end
```
5. Define on a `rails console` a different company from the default for an user
```ruby
irb(main):001:0> User.first.update(company: "test_company_")
```
### Expected behavior

The queries ran by rails should show the new table name prefix without restarting the server.

### Actual behavior

The queries ran by rails show the old table name prefix. Only after restarting the server the prefix gets updated.

### System configuration
**Rails version**: > 5.2
**Ruby version**: > 2.6

**Comment by lfalcao** [comment]
@rhuanbarreto there is some gems that supports multitenancy (https://www.ruby-toolbox.com/categories/Multitenancy) that I think are a better approach to this, as you'll have to think about other things like migrations for example.

But if you want to give a try, it would be more or less this:

```ruby
class ApplicationController < ActionController::Base
  def index
    current_user ? Company.use_table('user_company') : Company.use_table('company')
   end 
end

class Company < ApplicationRecord
  def self.table_name
     @custom_table || 'company'
  end

  def self.use_table(new_table)
     return if table_name.eql? new_table

     reset_column_information
     @custom_table = new_table
  end
end

```

**Comment by supertry55** [comment]
#41995

**Comment by rhuanbarreto** [comment]
Thanks @lfalcao! I will try here and check if it works. In my specific case the "multi tenancy" is made by table name prefixes and no gem works with this behavior yet.

**Comment by pixeltrix** [comment]
@rhuanbarreto the only way to achieve this would be to use `self.table_name = <value>` but since this reloads the column information the performance would be terrible. Prefixing is also unlikely to scale well so I recommend looking at alternative methods of multi-tenancy.
