### ISSUE TITLE
Getting ActiveStorage::IntegrityError after upgrade to Rails 6.1.3.1

### ISSUE THREAD

**Issue by archonic** [rails/rails#41991]
### Steps to reproduce
Attach an avatar to a user with ActiveStorage, using disk service, in a factory using the following trait:
```
trait :avatared do
  avatar { Rack::Test::UploadedFile.new("#{::Rails.root}/spec/fixtures/files/avatar.png") }
end
```

### Expected behavior
The file should successfully be attached.

### Actual behavior
The creation of the user with the avatar trait fails with `ActiveStorage::IntegrityError`. Inspecting where the failure happens, the `.attach` doesn't fail, but calling `save` on the user will raise the `ActiveStorage::IntegrityError`. I've tried different files - it doesn't seem to be a file corruption issue.

Strangely attaching the same file in a request test works, and I'm not seeing the failure in the CircleCI environment.

### System configuration
**Rails version**:
6.1.3.1

**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-musl]

Here's a public repo with the issue reproducable locally (on Docker for Mac)
https://github.com/archonic/limestone/blob/master/spec/helpers/icon_spec.rb
https://github.com/archonic/limestone/blob/master/spec/factories/users.rb#L60

**Comment by rafaelfranca** [comment]
Thank you so much for the issue. Given you know how to reproduce and have a test application, can you try to use git bisect to find which commit introduce the failure?

**Comment by archonic** [comment]
Yes, I'll work on that tonight.

**Comment by archonic** [comment]
I tested:
6.1.3.1
6.1.3
6.1.2.1
6.1.0
6.0.3.6

All got the `ActiveStorage::IntegrityError`. I now suspect it's a Docker for Mac issue and I'm not sure how old the issue is as I normally test through CI.

I'll close this and come back and write what the solution is if I find it.

**Comment by Notalifeform** [comment]
running into this too...  have not idea where to start to fix this...

**Comment by archonic** [comment]
@Notalifeform Are you also running Docker for Mac?

**Comment by khaitu** [comment]
Same issue here. Running latest Docker for Mac with docker-sync.

**Comment by Notalifeform** [comment]
yep. for me only the downgrade to 3.2.2. worked - see https://github.com/docker/for-mac/issues/5570
the ruby workaround mentioned does not somehow...

**Comment by ralph** [comment]
Hey, I did the workaround in the other thread. I should have mentioned that I’m using Carrierwave, sorry I forgot that! Too bad that it does not work for Active Storage. Let’s hope that docket will release a fix soon. 🐳🤞

**Comment by rPetas** [comment]
> 
> 
> So I have started to having this issue in bitbucket pipelines with ruby 2.7.2/ rails 6.0.3.7. Versions of docker images are the same. Last successful build was 4 days ago. I have tried to freeze gems to the ones from successfull build, but with no success. So probably not only docker version for mac is affected? Local tests on linux host are fine.

Exactly the same issue but ruby 2.7.1 and rails 6.0.3.3. The docker images had no meaningful changes that i could perceive. Last successful build was also 4 days ago.
I ran the tests in local with docker-windows using the same images and there is no problem.

**Comment by mkleint** [comment]
Several our Bitbucket Pipelines customers are facing the same issue after our kubernetes node host FlatCarOS upgrade 2605.12.0 to 2765.2.2 (kernel moved from 5.4.92 directly to 5.10.19). 
it mostly appears as ActiveStorage::IntegrityError while running rspec tests

The smallest test case demonstrating the problem appears to be this ruby script (copied from another github issue I found on the internet)
```
require 'fileutils'
require 'tempfile'
tempfile_1 = Tempfile.new(['tempfile_1', ".txt"])
FileUtils.cp('bitbucket-pipelines.yml', tempfile_1.path)
tempfile_2 = Tempfile.new(['tempfile_2', ".txt"])
FileUtils.cp(tempfile_1.path, tempfile_2.path)
puts tempfile_2.read # will be empty, but should not be
```

```
docker info
Client:
 Debug Mode: false
Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Authorization: pipelines
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  userns
 Kernel Version: 5.10.25-flatcar
 Operating System: Alpine Linux v3.13 (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 30.91GiB
 Name: 44212645-d3ba-4afa-b2d9-8a1f81e7f1ee-wrmh2
 ID: KPMN:TGRY:QL5G:YYZT:4ZHE:XLQD:BCPI:UEUZ:6KD7:TGB4:GUVN:KAIB
 Docker Root Dir: /var/lib/docker/165536.165536
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  http://10.203.197.49:5000/
 Live Restore Enabled: false
 Product License: Community Engine
 ```

**Comment by RafalWalczak** [comment]
I have temporarily fixed the docker upgrade issue by manually creating `Temporary` file which is passed into `Rack::Test::UploadedFile` initializer:

```ruby
# frozen_string_literal: true

module FactoryHelpers
  def self.upload_file(src, content_type, binary = false)
    path = Rails.root.join(src)
    original_filename = ::File.basename(path)

    content = File.open(path).read
    tempfile = Tempfile.open(original_filename)
    tempfile.write content
    tempfile.rewind

    uploaded_file = Rack::Test::UploadedFile.new(tempfile, content_type, binary, original_filename: original_filename)

    ObjectSpace.define_finalizer(uploaded_file, uploaded_file.class.finalize(tempfile))

    uploaded_file
  end
end

```

Inside your `specs` or `factories` instead of using `Rack::Test::UploadedFile` it should be attached by above module:

```ruby
trait :avatared do
  avatar { FactoryHelpers.upload_file('spec/fixtures/files/avatar.png', 'image/png', true) }
end
```

**Comment by VitaliyAdamkov** [comment]
> I have temporarily fixed the docker upgrade issue by manually creating `Tempfile` file which is passed into `Rack::Test::UploadedFile` initializer:
> 
> ```ruby
> # frozen_string_literal: true
> 
> module FactoryHelpers
>   def self.upload_file(src, content_type, binary = false)
>     path = Rails.root.join(src)
>     original_filename = ::File.basename(path)
> 
>     content = File.open(path).read
>     tempfile = Tempfile.open(original_filename)
>     tempfile.write content
>     tempfile.rewind
> 
>     uploaded_file = Rack::Test::UploadedFile.new(tempfile, content_type, binary, original_filename: original_filename)
> 
>     ObjectSpace.define_finalizer(uploaded_file, uploaded_file.class.finalize(tempfile))
> 
>     uploaded_file
>   end
> end
> ```
> 
> Inside your `specs` or `factories` instead of using `Rack::Test::UploadedFile` it should be attached by above module:
> 
> ```ruby
> trait :avatared do
>   avatar { FactoryHelpers.upload_file('spec/fixtures/files/avatar.png', 'image/png', true) }
> end
> ```

Just made small patch to your workaround, or it ruined content-type validation:
```ruby
extname = ::File.extname(path)
original_filename = ::File.basename(path, extname)
tempfile = Tempfile.open([original_filename, extname])
```

**Comment by kieraneglin** [comment]
As of `rack-test` 2.2.0 (2024-12-23) the `finalize` method has been made unnecessary and been removed. Here's what my helper looks like now:

```ruby
  def self.upload_file(src, content_type, binary: false)
    path = Rails.root.join(src)
    original_filename = ::File.basename(path)

    content = File.read(path)
    tempfile = Tempfile.open(original_filename)
    tempfile.write(content)
    tempfile.rewind

    Rack::Test::UploadedFile.new(tempfile, content_type, binary, original_filename: original_filename)
  end
```
