### ISSUE TITLE
Active Storage: FileNotFoundError on AnalyzeJob and resulting/being cause of  missing image

### ISSUE THREAD

**Issue by sebastian-echeverria-lenio** [rails/rails#42003]
I'm currently having an issue when trying to upload and subsequently retrieve an image linked to a record. I'm manually assigning the image to the entity as in `@entity.main_image = params[:main_image]` being `main_image` the value of a file field. Later even after the browser successfully redirected me to the success page I get the following error in the console 

`[ActiveJob] [ActiveStorage::AnalyzeJob] [dd84c5a8-7a93-4f08-9198-b5236bf2ae66] Error performing ActiveStorage::AnalyzeJob (Job ID: dd84c5a8-7a93-4f08-9198-b5236bf2ae66) from Async(default) in 5.39ms: ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError):
`

As a testing stance I created a dummy app and used the same set up and gem versions but everything ran smoothly then.

### Steps to reproduce
- Integrate Activerecord normally 
- Upload an image
- Assign image manually

### Expected behavior
- AnalyzeJob should finish correctly and Image should be retrievable

### Actual behavior
- AnnalyzeJob fails with FileNotFoundError and Image is not retrievable

### System configuration
**Rails version**:  6.0.22

**Ruby version**: 2.6.5

**Comment by lfalcao** [comment]
@sebastian-echeverria-lenio can you provide more details and/or provide an example of the problem?

**Comment by mhaulo** [comment]
I've had a `ActiveStorage::FileNotFoundError` problem too with gpx files. I'm not sure if the root cause is the same, but just in case this helps, here some information about my environment:

- Ruby 2.6.5
- Rails 6.0.2.1

A simplified code usage example:
```
class GpxUpload < ApplicationRecord
  has_one_attached :gpx_file

  def process
    xml = Nokogiri::XML(gpx_file.download) # I believe this is when the exception happens
  end
end
```

In this case, the gpx file has succesfully been attached to a GpxUpload record. But sometimes when trying to download the file, it throws an exception.

This does _not_ happen with _every_ gpx file. I haven't investigated this in details so far and I don't yet know what it is in some gpx file that causes this to happen.

**Comment by brenogazzola** [comment]
@mhaulo I've had this in the past due to consistency problems in S3 (when it still used "eventual consistency" instead of strong consistency). Do your jobs fail on the first try, and succeed later? If they do, this is the probably cause. Are you using S3, Google or Azure?

**Comment by mhaulo** [comment]
I can't remember if the same job keeps failing (I'll pay more attention next time I catch this). It has happened in development environment using disk storage.

**Comment by ball-hayden** [comment]
We're seeing this a lot with GCS. Our logs look a bit like this:

| Time | Job | Message
| -- | -- | --
| Jul 23, 2021 @ 08:17:08.884 | OurJob | ActiveStorage::Blob Create
| Jul 23, 2021 @ 08:17:08.970 | ActiveStorage::AnalyzeJob | Sending HTTP get https://storage.googleapis.com/storage/v1/b/<redacted>/o/kqfe9vxp3qoscn2gh07qtljdbajx?
| Jul 23, 2021 @ 08:17:08.996 | ActiveStorage::AnalyzeJob | Caught error notFound: No such object: <redacted>/kqfe9vxp3qoscn2gh07qtljdbajx
| Jul 23, 2021 @ 08:17:08.997 | ActiveStorage::AnalyzeJob | GCS Storage (20.1ms) Downloaded file from key: kqfe9vxp3qoscn2gh07qtljdbajx
| Jul 23, 2021 @ 08:17:09.038 | OurJob | Sending upload start command to https://storage.googleapis.com/upload/storage/v1/b/<redacted>/o?name=kqfe9vxp3qoscn2gh07qtljdbajx
| Jul 23, 2021 @ 08:17:09.062 | OurJob | Sending upload command to https://storage.googleapis.com/upload/storage/v1/b/<redacted>/o?name=kqfe9vxp3qoscn2gh07qtljdbajx&upload_id=ADPycdtT-FZMgaHAfSJzynygQDJjpLNewhRtcHQLhFibm4MLwFV5WKHThxryw1OL85mH6EQqZsu-OAbJDXbeiUiUZi0&upload_protocol=resumable
| Jul 23, 2021 @ 08:17:09.141 | OurJob | Success - #<Google::Apis::StorageV1::Object:0x00007f84f79ac1e8 ... >
| Jul 23, 2021 @ 08:17:09.141 | OurJob | GCS Storage (105.3ms) Uploaded file to key: kqfe9vxp3qoscn2gh07qtljdbajx (checksum: KcTah+3xXss/OsfMkS+FNA==)
| Jul 23, 2021 @ 08:17:30.064 | ActiveStorage::AnalyzeJob | Sending HTTP get https://storage.googleapis.com/storage/v1/b/<redacted>/o/kqfe9vxp3qoscn2gh07qtljdbajx?
| Jul 23, 2021 @ 08:17:30.083 | ActiveStorage::AnalyzeJob | Success - #<Google::Apis::StorageV1::Object:0x00007f84fa7faa68 ... >
| Jul 23, 2021 @ 08:17:30.129 | ActiveStorage::AnalyzeJob | GCS Storage (65.9ms) Downloaded file from key: kqfe9vxp3qoscn2gh07qtljdbajx

Notably, the analyze job seems to be being kicked off before the upload has completed for GCS. It then succeeds on retry.
This isn't a problem as such, it's just (a lot of) noise in our bug tracker.

**Comment by brenogazzola** [comment]
@ball-hayden This is weird. The analyze job is supposed to run after the `ActiveStorage::Attachment` relation, which ties the blob to the record is created, not after the blob. Do you have an insert into `active_storage_attachments` there somewhere?

**Comment by ball-hayden** [comment]
I do indeed. Note that this is a different example (I no longer have access to logs from the original example).
Hopefully, I've got everything relevant here this time - I'm afraid the logs from this job are quite noisy 😓 

Time | rails.named_tags.class | rails.message | rails.payload.sql
--|--|--|--
Aug 5, 2021 @ 09:19:49.429 | OurJob | start | -
Aug 5, 2021 @ 09:19:54.859 | OurJob | TRANSACTION | BEGIN
Aug 5, 2021 @ 09:19:54.887 | OurJob | ActiveStorage::Blob Create | INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "metadata", "byte_size", "checksum", "created_at", "service_name") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"
Aug 5, 2021 @ 09:19:54.890 | OurJob | ActiveStorage::Attachment Create | INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"
Aug 5, 2021 @ 09:19:54.894 | OurJob | TRANSACTION | COMMIT
Aug 5, 2021 @ 09:19:54.896 | OurJob | Enqueued ActiveStorage::AnalyzeJob (Job ID: 6e99643e-7785-4e4e-ae3c-b2ad3c933702) to Sidekiq(active_storage_analysis) | -
Aug 5, 2021 @ 09:19:54.897 | OurJob | TRANSACTION | BEGIN
Aug 5, 2021 @ 09:19:54.920 | OurJob | Sending upload start command to https://storage.googleapis.com/upload/storage/v1/b/REDACTED/o?name=bfnf83f86e2lj8j2uk2u6z3wkiur | -
Aug 5, 2021 @ 09:19:54.920 | OurJob | TRANSACTION | COMMIT
Aug 5, 2021 @ 09:19:54.931 | ActiveStorage::AnalyzeJob | start | -
Aug 5, 2021 @ 09:19:54.934 | ActiveStorage::AnalyzeJob | ActiveStorage::Blob Load | SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2
Aug 5, 2021 @ 09:19:54.935 | ActiveStorage::AnalyzeJob | Performing ActiveStorage::AnalyzeJob (Job ID: 6e99643e-7785-4e4e-ae3c-b2ad3c933702) to Sidekiq(active_storage_analysis) | -
Aug 5, 2021 @ 09:19:54.937 | ActiveStorage::AnalyzeJob | Sending HTTP get https://storage.googleapis.com/storage/v1/b/REDACTED/o/bfnf83f86e2lj8j2uk2u6z3wkiur? | -
Aug 5, 2021 @ 09:19:54.966 | OurJob | Sending upload command to https://storage.googleapis.com/upload/storage/v1/b/REDACTED/o?name=bfnf83f86e2lj8j2uk2u6z3wkiur&upload_id=ADPycdvFxQGuEyNf4dSR80lu_zW7fBBr4tzaH3SatVfaezo9i2a8UyEJZEJC9-HWjNxHNrs7slIaWuc5-g9Rr75Mtrg&upload_protocol=resumable | -
Aug 5, 2021 @ 09:19:54.966 | OurJob | Upload status active | -
Aug 5, 2021 @ 09:19:54.975 | ActiveStorage::AnalyzeJob | - | -
Aug 5, 2021 @ 09:19:54.977 | ActiveStorage::AnalyzeJob | - | -
Aug 5, 2021 @ 09:19:54.981 | ActiveStorage::AnalyzeJob | Caught error notFound: No such object: REDACTED/bfnf83f86e2lj8j2uk2u6z3wkiur | -
Aug 5, 2021 @ 09:19:54.982 | ActiveStorage::AnalyzeJob | - | -
Aug 5, 2021 @ 09:19:54.982 | ActiveStorage::AnalyzeJob | GCS Storage (38.7ms) Downloaded file from key: bfnf83f86e2lj8j2uk2u6z3wkiur | -
Aug 5, 2021 @ 09:19:54.983 | ActiveStorage::AnalyzeJob | - | -
Aug 5, 2021 @ 09:19:54.983 | ActiveStorage::AnalyzeJob | fail | -
Aug 5, 2021 @ 09:19:54.984 | - | - | -
Aug 5, 2021 @ 09:19:55.033 | OurJob | Upload status final | -
Aug 5, 2021 @ 09:19:55.034 | OurJob | GCS Storage (113.8ms) Uploaded file to key: bfnf83f86e2lj8j2uk2u6z3wkiur (checksum: KcTah+3xXss/OsfMkS+FNA==) | -
Aug 5, 2021 @ 09:19:55.099 | OurJob | done | -
Aug 5, 2021 @ 09:20:13.666 | ActiveStorage::AnalyzeJob | start | -
Aug 5, 2021 @ 09:20:13.670 | ActiveStorage::AnalyzeJob | ActiveStorage::Blob Load | SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2
Aug 5, 2021 @ 09:20:13.670 | ActiveStorage::AnalyzeJob | Performing ActiveStorage::AnalyzeJob (Job ID: 6e99643e-7785-4e4e-ae3c-b2ad3c933702) to Sidekiq(active_storage_analysis) | -
Aug 5, 2021 @ 09:20:13.672 | ActiveStorage::AnalyzeJob | Sending HTTP get https://storage.googleapis.com/storage/v1/b/REDACTED/o/bfnf83f86e2lj8j2uk2u6z3wkiur? | -
Aug 5, 2021 @ 09:20:13.690 | ActiveStorage::AnalyzeJob | - | -
Aug 5, 2021 @ 09:20:13.692 | ActiveStorage::AnalyzeJob | - | -
Aug 5, 2021 @ 09:20:13.693 | ActiveStorage::AnalyzeJob | Success - #<Google::Apis::StorageV1::Object:0x00007f371eebfe18 @bucket="REDACTED", @content_type="image/png", @crc32c="jCmVvQ==", @etag="COP1peDGmfICEAE=", @generation=1628155194997475, @id= "REDACTED/bfnf83f86e2lj8j2uk2u6z3wkiur/1628155194997475", @kind="storage#object", @md5_hash="KcTah+3xXss/OsfMkS+FNA==", @media_link= "https://storage.googleapis.com/download/storage/v1/b/REDACTED/o/bfnf83f86e2lj8j2uk2u6z3wkiur?generation=1628155194997475&alt=media", @metageneration=1, @name="bfnf83f86e2lj8j2uk2u6z3wkiur", @self_link= "https://www.googleapis.com/storage/v1/b/REDACTED/o/bfnf83f86e2lj8j2uk2u6z3wkiur", @size=10376, @storage_class="STANDARD", @time_created=Thu, 05 Aug 2021 09:19:54 +0000, @time_storage_class_updated=Thu, 05 Aug 2021 09:19:54 +0000, @updated=Thu, 05 Aug 2021 09:19:54 +0000> | -
Aug 5, 2021 @ 09:20:13.731 | ActiveStorage::AnalyzeJob | - | -
Aug 5, 2021 @ 09:20:13.732 | ActiveStorage::AnalyzeJob | GCS Storage (60.6ms) Downloaded file from key: bfnf83f86e2lj8j2uk2u6z3wkiur | -
Aug 5, 2021 @ 09:20:13.970 | ActiveStorage::AnalyzeJob | TRANSACTION | BEGIN
Aug 5, 2021 @ 09:20:13.972 | ActiveStorage::AnalyzeJob | ActiveStorage::Blob Update | UPDATE "active_storage_blobs" SET "metadata" = $1 WHERE "active_storage_blobs"."id" = $2
Aug 5, 2021 @ 09:20:13.974 | ActiveStorage::AnalyzeJob | TRANSACTION | COMMIT
Aug 5, 2021 @ 09:20:13.975 | ActiveStorage::AnalyzeJob | done | -
Aug 5, 2021 @ 09:20:13.975 | ActiveStorage::AnalyzeJob | Performed ActiveStorage::AnalyzeJob (Job ID: 6e99643e-7785-4e4e-ae3c-b2ad3c933702) to Sidekiq(active_storage_analysis) in 304.5ms | -

I'm wondering if something in the GCS backend is being "helpful" by pushing the upload into a background thread?

**Comment by brenogazzola** [comment]
Yeah, this is out of order. It should be `create blob`, `upload file`, `create attachment`. 

I'm not using GCS so I can't debug this easily, but I'm reading the code in Active Storage's `gcs_service.rb` and I'm not seeing anything like what you mentioned. It's using `create_file` from Google's gem for the upload. When I check Google's gem, they have a test that does `create_file` and immediately after a `list`. If the gem was pushing stuff to a background thread this would cause a flakky test due to a race condition, so I don't think this is it.

How are you performing this upload:
1 - Is it through a normal form, a form with direct upload, or from your backend?
2 - Are you doing a normal `attach` or something?

**Comment by ball-hayden** [comment]
The upload is from a Sidekiq job using `attach` - we take a base64 encoded string and store it as a file (don't ask!).

```rb
io = StringIO.new(Base64.decode64(base64_encoded_string))
target.attach(io: io, filename: "file.png", content_type: "image/png")
```

**Comment by brenogazzola** [comment]
Well, look at that. Using S3:

1 - Transaction is opened
2 - Blob is created
3 - Attachment is created
4 - Transaction is committed <- this is where callback for the job is
6 - File finishes upload
7 - 0.002 seconds later job is enqueued.

So I'm guessing that if the file upload is slow enough, we'd see your error? I'll try to create a CGS account this weekend so I can try to actually get the error to happen, so I can figure out how to solve this.

**Comment by ball-hayden** [comment]
Yeah, that looks like the same thing. I guess you could manage the same with a proxy and artificially slowing down requests to S3.
Thanks for taking the time to look at this @brenogazzola - I appreciate it.

**Comment by brenogazzola** [comment]
I've actually already tried using my mobile phone's 3G connection for that (viva the farm life), but still had no problem on S3. This must really be something specific to the cgs service in Active Storage or the cgs gem. I'm quite curious about this one. 

At least now I know it's something related to `create_and_upload!` and CGS.

**Comment by brenogazzola** [comment]
@ball-hayden I’ve just noticed I did not ask what version of Rails you are using. I was simply testing this on master 😅

**Comment by ball-hayden** [comment]
Good question 😂
We're running 6.1.4.

**Comment by ball-hayden** [comment]
@brenogazzola unfair of me to ask, but I don't suppose you were ever able to look into this any further?

**Comment by brenogazzola** [comment]
Sorry 😅. I created the GCP account but ended completely forgetting about this due to other things. I'll add it back to my list, since there's discussion about moving our app from AWS to GCP.
