### ISSUE TITLE
Generated package.json file uses version constraints that may be too loose

### ISSUE THREAD

**Issue by rmacklin** [rails/rails#42012]
### Steps to reproduce

Generate a new rails 6.0 app: `rails _6.0.3.6_ new sample_app`

### Expected behavior

I expected the app to install the `@rails/actioncable`, `@rails/activestorage`, and `@rails/ujs` javascript packages at the corresponding version `6.0.3-6`

### Actual behavior
The app installed the `@rails/actioncable`, `@rails/activestorage`, and `@rails/ujs` javascript packages at version `6.1.3`

### System configuration
**Rails version**: 6.0.3.6

**Ruby version**: any supported version

### More information

This happens because the [generated `package.json` file](https://github.com/rails/rails/blob/v6.0.3.6/railties/lib/rails/generators/rails/app/templates/package.json.tt) declares the dependencies with a loose version constraint:
```json
  "dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
```

(`^6.0.0` will match the latest `6.x.y` version)

I don't think this has really been an issue so far since these packages haven't really had any significant changes. Thus, version 6.1 of the npm packages is likely compatible with a rails 6.0 server. But I wanted to bring this up because I'm not sure this behavior was desired/intentional. I know that rails only expects each framework gem (activerecord, activestorage, etc) to be compatible with the other framework gems of the same exact version, which simplifies maintenance. If that should extend to the npm packages, too, then we probably want to change the generated `package.json` to prevent this behavior.

**Comment by rmacklin** [comment]
Related: [Even in rails 6.1, the generated `package.json` uses `^6.0.0`](https://github.com/rails/rails/blob/v6.1.3.1/railties/lib/rails/generators/rails/app/templates/package.json.tt) rather than `^6.1.0`.

This was a little surprising, since it's declaring that any version >= 6.0.0 and < 7.0.0 is valid - I would have expected the minimum version to be 6.1.0 for rails 6.1 apps. Of course, given that it's a loose version constraint, it does end up installing 6.1.3, so new apps won't actually end up with 6.0.x. Nonetheless, I'm not sure the `^6.0.0` declaration was intentional.

I wonder if we want to do away with the loose version constraint altogether. Would we rather specify an exact version (e.g. by interpolating the rails version)?

**Comment by zzak** [comment]
It doesn't seem the `npm` packages are released in sync with gems, so the exact versions may be different. i.e. if it were to map directly to `RAILS_VERSION` that is assuming the npm packages are cut at the same time (which I don't believe they are). I could be wrong though, and this was just a quick look comparing `actioncable` on the npm org and rubygems.org -- so I'd love to find out more.

Hopefully someone can add more context into how these npm packages are published! 🙏

**Comment by rmacklin** [comment]
@zzak 
> that is assuming the npm packages are cut at the same time (which I don't believe they are)

I think the npm packages are cut at the same time. See https://github.com/rails/rails/blob/61fb58f6a7f852d765d616d1da41d17851ec7afc/tasks/release.rb#L101-L110

(originally introduced in https://github.com/rails/rails/commit/548c1d6e8b819ca4e02e6218b67107c580ee65f2 to publish the `actioncable` npm package when releasing rails)

It's also part of the release documentation:
https://github.com/rails/rails/blob/61fb58f6a7f852d765d616d1da41d17851ec7afc/RELEASING_RAILS.md#release-to-rubygems-and-npm

Furthermore, these javascript packages can also be consumed from within the gems themselves via the sprockets asset pipeline. If the npm packages were not cut at the same time as the gems, it would open up the possibility that the javascript in the gem would be out of sync with the javascript in the npm package. That's bad because developers should be able to migrate between the two approaches of javascript consumption freely with the assumption that this won't have any noticeable impact on their compiled javascript.

**Comment by zzak** [comment]
@rmacklin Thanks for digging in there, and apologizes for my laziness.

I must have not been looking closely (or tired), but it seems that the latest packages exist both on [npm (as 6.1.3-2)](https://www.npmjs.com/package/@rails/actioncable/v/6.1.3-2) and [rubygems (as 6.1.3.2)](https://rubygems.org/gems/actioncable/versions/6.1.3.2).

Interesting difference in the last version segment on npm vs rg. Though, I'm not sure this matters if we can just use the `npm_tag` when writing to `package.json`.

Still on the table though, is what the team decides is best for version dependencies.

My opinion is that we should leave it open to SemVer (so `^#{npm_tag}`), I think?

**Comment by ghiculescu** [comment]
> My opinion is that we should leave it open to SemVer (so `^#{npm_tag}`), I think?

I think it should be an exact match, the same as the [Rails gemspec](https://github.com/rails/rails/blob/main/rails.gemspec#L31..L42). Given Rails sometimes makes breaking changes in "minor" (in semver terms) versions, anything else doesn't feel safe.

**Comment by zzak** [comment]
@ghiculescu Sorry for different versions I specifically meant "6.0.2.1" from the gem is not the same as the string "6.0.2-1" used for npm.

I was also mistaken when I said `npm_tag` I mean `npm_version`, which is defined [here](https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/tasks/release.rb#L26-L36).

Probably we would have to move that definition into somewhere `railtie` can use it for generating the package.json for `rails new`. 🤔
