### ISSUE TITLE
Arel.to_dot doesn't show some nodes for SelectCore

### ISSUE THREAD

**Issue by intrip** [rails/rails#42026]
When calling `.to_dot` on `Arel::Nodes::SelectCore` some nodes aren't shown.
This behaviour applies for all the nodes associated to the following attributes : `[:groups, :comment, :optimizer_hints, :havings, :set_quantifier]`.

Is this the expected behaviour? If so why and [why we are still implementing the related visitors](https://github.com/rails/rails/blob/5d7b86b698a26f45aa83974a27e04d5a20891c53/activerecord/lib/arel/visitors/dot.rb#L72-L88) ?

### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 6"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users do |t|
  end
end

class User < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_arel_to_dot_select_core
    users = User.optimizer_hints("a hint").having("id")
    assert_match (/Arel::Nodes::OptimizerHints/), users.arel.to_dot
  end
end
```

### Expected behavior

`Arel::Nodes::OptimizerHints` should be rendered.

### Actual behavior

`Arel::Nodes::OptimizerHints` is not rendered.

### System configuration
**Rails version**:

`6.x, master branch`

**Ruby version**:

`2.7.x, 3.x`

**Comment by flavorjones** [comment]
PR submitted at #42128 that addresses this as well as missing properties from a few other node types.
