### ISSUE TITLE
Handling streaming responses.

### ISSUE THREAD

**Issue by ioquatix** [rails/rails#42031]
I would like to see if we can come to a consensus on what streaming responses should look like from within Rails controllers.

I have been playing around with how to make this work and did finally figure it's possible.

```ruby
def live
  self.response = Async::WebSocket::Adapter::Rails.new(request) do |connection|
    connection.read # / write / etc
  end
end
```

However, internally, it's a bit janky because it uses `rack.hijack`: https://github.com/socketry/async-websocket/blob/master/lib/async/websocket/adapters/rails.rb#L30-L39

I wonder if we want to design a better interface for handling this, and if so, what would it look like?

Exposing partial hijack might make sense, but then do we want to use that for Rails live streaming too? This would be one potential solution for https://github.com/rails/rails/issues/38842

To do some kind of "live" response, you could have an interface like this:

```ruby
def my_controller_method
  self.response.live do |stream|
    stream.read # write etc
  end
end
```

The implementation might look something like this:

```ruby
class Response
  def live(&block)
    set_header('rack.hijack', block)
    self.close
  end
end
```

We are currently discussing whether `rack.hijack` is the right interface for streaming responses, but for now it seems like the most compatible option: https://github.com/rack/rack/pull/1745

cc @tenderlove

**Comment by p8** [comment]
Hi @ioquatix,
Have you seen the following?
https://github.com/rails/rails/blob/main/actionpack/lib/action_controller/metal/streaming.rb
https://github.com/rails/rails/pull/41488

**Comment by ioquatix** [comment]
Yes, thanks, I am very familiar with Rails' current model for streaming, which is different from what is proposed here. Rails creates an internal queue and buffers it using a thread, but this proposal directly interacts with the server.
