### ISSUE TITLE
Better Support User-Added Columns on ActiveStorage::Blob

### ISSUE THREAD

**Issue by dleavitt** [rails/rails#42057]
### Scenario

You're building a multi-tenant app and need to make sure all your `Blob`s `belong_to` an `Organization`.

To accomplish this, you'd want to pass along the organization id to your blob whenever you create one. 

### The Issue

Currently there are a number of class methods on `ActiveStorage::Blob` that are basically wrappers around `new` - taking attributes and returning a new blob. See:
https://github.com/rails/rails/blob/bd33ddaf710f94fafff1854ed4b4311e497e8492/activestorage/app/models/active_storage/blob.rb#L89-L116

Unfortunately, unlike most methods that accept model attributes, each attribute is a hardcoded keyword argument. So if you want to pass an additional attribute in, you have to override all of them, which seems very fragile.

### Solution

This would be easy to fix by using `**splats` and forwarding any extra keyword arguments through to `new`

So instead of looking like this:
```ruby
def build_after_upload(io:, filename:, content_type: nil, metadata: nil, service_name: nil, identify: true, record: nil)
  new(filename: filename, content_type: content_type, metadata: metadata, service_name: service_name).tap do |blob|
    blob.upload(io, identify: identify)
  end
end
```

They should look like this:
```ruby
def build_after_upload(io:, filename:, content_type: nil, metadata: nil, service_name: nil, identify: true, record: nil, **attributes)
  new(filename: filename, content_type: content_type, metadata: metadata, service_name: service_name, **attributes).tap do |blob|
    blob.upload(io, identify: identify)
  end
end
```

Or this:
```ruby
def build_after_upload(io:, identify: true, record: nil, **attributes)
  new(**attributes).tap do |blob|
    blob.upload(io, identify: identify)
  end
end
```

A change here would also be required:
https://github.com/rails/rails/blob/9437958e5623b38ef7e125cd24189834dee5c857/activestorage/app/models/active_storage/variant_with_record.rb#L36-L37

Seems much nicer! Happy to submit a PR.

### System configuration
**Rails version**:
6.1.3.1
**Ruby version**:
2.7.2

**Comment by pixeltrix** [comment]
@dleavitt I wouldn't recommend trying to load extra attributes onto the Active Storage tables so what's the use case here? Are you wanting to find all of an organisation's assets? If so you can add an existing blob to another record to create an attachment, e.g.

``` ruby
class Organisation < ApplicationRecord
  has_many_attached :images
end

class User < ApplicationRecord
  belongs_to: :organisation
  has_one_attached :avatar

  after_create do
    if avatar.attached?
      organisation.images.attach([avatar.blob])
    end
  end
end
```

If that doesn't work for you I'd look at using `ActiveSupport::CurrentAttributes` and include a concern in `ActiveStorage::Blob`, e.g.

``` ruby
class Current < ActiveSupport::CurrentAttributes
  attribute :organisation
end

module CurrentOrganisation
  extend ActiveSupport::Concern

  included do
    before_create :set_current_organisation
  end

  def set_current_organisation
    self.organisation = Current.organisation
  end
end

ActiveStorage::Blob.include(CurrentOrganisation)

Current.set(organisation: @organisation) do
  # your code
end 
```

You can also set `Current.organisation` in a `before_action` so that it's in effect for the whole request or similarly a `before_perform` so it's in effect for the whole job.

**Comment by dleavitt** [comment]
Thanks @pixeltrix! These are both great suggestions. 

My use-case is to be able to ensure, via foreign keys, that a given stored file is always associated with an organization (or user, or whatever.) Your second example solves this nicely! The more general use-case is adding application-specific metadata to a blob.

Assuming this is something Rails would want to support, I think the changes I suggested would allow this to be accomplished a bit more cleanly and explicitly and would make the codebase a little more flexible.

**Comment by przemad** [comment]
Another need is adding an ALT attribute for an image.
