### ISSUE TITLE
Reloading of routes after a Controller/Model change is painfully slow in large applications

### ISSUE THREAD

**Issue by venkat-ally** [rails/rails#42050]
In development, each time an rb file(controller/model) is changed, routes are reloaded (Starting from rails 4), which in case of large applications (with ~hundred models and controllers) take about **a minute** to complete. This exact concern was raised by @knoopx [way back in 2014](https://github.com/rails/rails/commit/b9b06daa915fdc4d11e8cfe11a7175e5cd8f104f#r6810835), but the behaviour still remains the same.

### Expected behavior

Ideally, it would be handy to have a flag to control this behaviour (Something like _config.reload_routes_upon_rb_changes_ in development). 

### Actual behavior

Since there's no such config, in larger applications, developer needs to wait for 25-30 seconds for the first request to pass, after making a controller/model change. Even though the current behaviour is great for smaller applications, it's painful after a point.

### System configuration
**Rails version**:
4-0-stable to master

**Comment by venkat-ally** [comment]
@rafaelfranca, please explain if there's a rationale behind the decision. I've currently patched RoutesReloader to circumvent the issue. I'd be happy to open a PR.

**Comment by Austio** [comment]
@venkat-ally Could you post a profile of what you are seeing?  https://github.com/MiniProfiler/rack-mini-profiler

I work in a large app as well and don't experience much in terms of slowness.

**Comment by venkat-ally** [comment]
@Austio , Thanks for your response. I did profile before deciding to patch RoutesReloader. It was pretty evident that reloading of routes was actually taking up most of the time. Here's the sandwich view of the first reload after a controller change (without the patch) :
![image](https://user-images.githubusercontent.com/58689496/116770288-3b18de80-aa60-11eb-8faf-b5d27906dd6f.png)

**Comment by pixeltrix** [comment]
@venkat-ally is there a large number of engines in this app? Seems to be taking a long time in `clear!` and `define_url_helper`

**Comment by venkat-ally** [comment]
@pixeltrix Just a couple of small engines and ~650 routes in total.

**Comment by byroot** [comment]
Something seems off because we load more routes in way under a second.

Could it be that some code is erroneously calling routes to be reloaded more than once per request cycle?

Would be useful if you could put some breakpoint/puts in there to see why it's called so much (because I doubt it's slow, I believe it's called too much).

**Comment by venkat-ally** [comment]
@byroot I had the same suspicion at first. I added a breakpoint at RoutesReloader#reload! and ensured its called only once when I reload after a change. Calls to ‘clear!’ and ‘load_paths’ were taking too long as shown in the above profile.

**Comment by casperisfine** [comment]
> Something seems off because we load more routes in way under a second.

```
[19] pry(main)> Benchmark.realtime { Rails.application.routes.clear!; Rails.application.routes_reloader.execute }
=> 1.4373429999686778
[20] pry(main)> Rails.application.routes.routes.size
=> 4795
```

So I was wrong on the under a second, but still, we seem to load our routes 240 times faster than you. So I really suspect there something off in your app. Unless of course I'm not using the proper code to reload my routes?

I think it would be worth trying to reproduce in a new clean app.

**Comment by lfalcao** [comment]
hey @venkat-ally did you find anything?

**Comment by venkat-ally** [comment]
We use url_helpers extensively and with [this PR](https://github.com/rails/rails/pull/37927), caching of `routes.url_helpers` is brought back. Since we're still on Rails 5.2, had to work around with a solution similar to https://travisofthenorth.com/blog/2017/12/27/rails-urlhelpers, to overcome this issue.
