### ISSUE TITLE
Partiality in merging pull request

### ISSUE THREAD

**Issue by adityapandit17** [rails/rails#42058]
@DHH @eileencodes @tenderlove @georgeclaghorn  @rafaelfranca I see on the latest code that rafael merge the pull request
 #42053 (Replace map + compact with filter_map)
 But reject my same pull request days ago. this one is my pull request #41780 (Using filter_map for performance appraisal)
 The change in both pull request are really same.
 It seems like this is some partiality with me. He merged same pull request from his Brazil group but not mine. This is really not done. This really hurts me. This make me unclear to contribute to any other opensource or even to rails. I am demotivated to open another pull request or contribution because of people like rafeal my pull request should me merge because I opted for that pull request changes first. I need clarification from you guys. I am really frustrated.

**Comment by adityapandit17** [comment]
https://discuss.rubyonrails.org/t/partiallity-in-merging-pull-request/77647?u=adityapandit17
link to rails discussion board.

**Comment by eileencodes** [comment]
Hey @adityapandit17 I reviewed both PRs and discussed with some of the Core team members who are currently online and this looks like an honest mistake to me. I'm sorry that your PR wasn't merged and that you feel frustrated and dismissed.

We get hundreds of PRs a month and I know I've closed a PR that I later merged because they made a more compelling case or I honestly just forgot. We're all humans here and sometimes we make mistakes. There isn't any partiality here though.

The merged PR linked to the blog post where the benchmarks originated from which made the case for the changes more compelling. In the future, if you borrow benchmarks from a blog post, please include the link to the post in your PR. It helped make the case for the changes beyond the microbenchmarks in isolation. Additionally that PR had more changes to drop slightly more complex code that supported Rubys less than 2.7.

**Comment by adityapandit17** [comment]
Thanks you for you response @eileencodes, I know you will reply me.
Last time I see this type of mistake and you are the person who said you will bring the changes who created it the first.
Also The micro benchmarks are all same I copied that from the same blog post. 
You can verify them.

**Comment by adityapandit17** [comment]
@eileencodes  You said if you borrow benchmarks from a blog post, please include the link to the post in your PR.
what if I included it that time and @rafaelfranca not merged it on that time. Then what will be your clarification.

**Comment by eileencodes** [comment]
> It would be great if my PR is merged and then his PR is Merged with the same additional changes.

The other PR is already merged and we're not going to complicate Rails git history by reverting the change, merging yours, re-doing the other one, and then re-merging it. We also do not force push to Rails main or stable branches.

> what if I included it that time and @rafaelfranca not merged it on that time. Then what will be your clarification.

I'm not going to go through "what if" scenarios that didn't happen.

**Comment by adityapandit17** [comment]
@dhh @georgeclaghorn , I am a Ruby on rails developer from past 5 years from now. 
How can I apply to become a member of `RAILS CORE` team. 
I need to be honest with the changes. 
Or can you explain me the procedure for this.

**Comment by adityapandit17** [comment]
> The other PR is already merged and we're not going to complicate Rails git history by reverting the change, merging yours, re-doing the other one, and then re-merging it. We also do not force push to Rails main or stable branches.

Fine, I know it is not the best practice to do this.

**Comment by adityapandit17** [comment]
why this pull request is closed without proper clarification.

**Comment by rafaelfranca** [comment]
Sorry about that. There is a clear difference between the two changes in my opinion. Your PR was about "merge this to get speed", while the other one was "we now don't support this version of Ruby anymore, we can use this new feature". While we really don't accept changes based in micro benchmarks, we do accept changes to clean our codebase of unsupported versions of Ruby.

It is not my intention to discourage you but if you really want to contribute to Rails and become a Rails Core member maybe a better way of doing it would try to fix issues that are opened in the repository or real problems that you found in your application.
