### ISSUE TITLE
Rails 6 ActiveJob with Resque backend fails silently

### ISSUE THREAD

**Issue by john-999** [rails/rails#42073]
Rails 6 ActiveJob in conjunction with the Resque backend fails (entirely silently) to perform the defined Jobs - no error messages at all, even with all verbose modes on.

To get my Jobs performed, I had to change the Job class syntax to Resque's "proprietary" language, as follows (commented out = the non-working ActiveJob syntax, as per Rails guides)

    # class TestJob < ApplicationJob
    class TestJob
      # queue_as :default
      @queue = :default

      # def perform(*args)
      def self.perform(*args)
        Rails.logger.info "Doing the job..."
      end
    end

System configuration
- Rails 6.0.3.6
- ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
- resque (2.0.0)
- resque-scheduler (4.4.0)
- redis (4.2.5)

**Comment by fatkodima** [comment]
Can't reproduce.
Can you show what is the result of executing `lrange resque:failed 0 -1` within `redis-cli`?
Additionally, can you post a minimal repro using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_job_gem.rb template?
