### ISSUE TITLE
Railtie middleware not being loaded.

### ISSUE THREAD

**Issue by coding-bunny** [rails/rails#42084]
### Steps to reproduce
- Create a gem with a Railtie and Middleware to load
- Include the gem in the Gemfile
- Try to access the middleware's path

### Expected behavior
I expect Rails to have loaded the Middleware and make its path available

### Actual behavior
The application does not load the middleware

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: 3.0.0

### Technical Notes
I've created a middleware like follows:

```ruby
module IsItUp
  # If you are using Ruby on Rails, you do not need to manually insert this
  # middleware into your middleware stack.  See railtie.rb.
  class Middleware
    def initialize(app)
      @app = app
    end

    def call(env)
      status, header, response =
      if env["PATH_INFO"] == "/is_it_up"
        [
          200,
          { "Content-Type" => "application/json" },
          ['{ "status": "ok", "code": 200 }']
        ]
      else
        @app.call(env)
      end
      [status, header, response]
    end
  end
end
```

And the Railtie is defined as follows:

```ruby
module IsItUp
  class Railtie < Rails::Railtie
    initializer "is_it_up.configure_rails_initialization" do |app|
      app.middleware.use IsItUp::Middleware
    end
  end
end
```

When I manually load this, it works:
```
# Because there seems to be a compatibility issue with IsItUp and Rails 6,
# we will load the middleware manually.
require 'is_it_up'
Rails.application.config.middleware.use(IsItUp::Middleware)
```

This was working fine before in previous Rails versions.

**Comment by srabuini** [comment]
Hey @coding-bunny!

Make sure that you have the following `require`

```ruby
# lib/is_it_up.rb

require "is_it_up/railtie" if defined?(Rails::Railtie)
```

I haven't tested it with Ruby 3.0 but it works for me using Ruby 2.6.

**Comment by coding-bunny** [comment]
I have, this is the gem's core code:

```ruby
require "rack"

module IsItUp
  autoload :VERSION, "is_it_up/version"
  autoload :Middleware, "is_it_up/middleware"
  autoload :Railtie, "is_it_up/railtie" if defined?(Rails::Railtie)
end
```

It definitely works on all our older projects without issue, but on Rails 6.1.3.1 and Ruby 3.0.0 there seems to be something odd going on.

**Comment by coding-bunny** [comment]
wait....
could the problem be the `autoload` ?

**Comment by coding-bunny** [comment]
Yep, it was the `autoload`.
Swapped it all to `require_relative` and works like a charm
