### ISSUE TITLE
`assign_attributes` persists changes to join table relationships for already persisted records

### ISSUE THREAD

**Issue by thewatts** [rails/rails#42097]
### Steps to reproduce
Test to reproduce:

Copy the below code into a file, and run `ruby {filename}.rb`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :movies, force: true do |t|
  end

  create_table :characters, force: true do |t|
  end

  create_table :movie_characters, force: true do |t|
    t.integer :movie_id
    t.integer :character_id
  end
end

class Movie < ActiveRecord::Base
  has_many :movie_characters
  has_many :characters, through: :movie_characters
end

class Character < ActiveRecord::Base
  has_many :movie_characters
  has_many :movies, through: :movie_characters
end

class MovieCharacter < ActiveRecord::Base
  belongs_to :movie
  belongs_to :character
end

class BugTest < Minitest::Test
  def test_association_stuff
    # initialize
    hobbit = Movie.new

    luke = Character.create!
    frodo = Character.create!

    assert_equal 0, hobbit.movie_characters.count

    # assigning in-memory an incorrect character, Luke, to The Hobbit
    hobbit.assign_attributes(character_ids: [luke.id])
    assert_equal 0, hobbit.movie_characters.where(character_id: luke.id).count

    # persisting with incorrect character
    hobbit.save
    assert_equal 1, hobbit.movie_characters.where(character_id: luke.id).count

    # replacing in-memory with correct character, Frodo
    hobbit.assign_attributes(character_ids: [frodo.id])

    # Luke should still be associated with The Hobbit, since we haven't persisted yet
    assert_equal 1, hobbit.movie_characters.where(character_id: luke.id).count
    # Frodo should not be associated with the hobbit yet
    assert_equal 0, hobbit.movie_characters.where(character_id: frodo.id).count

    # persisting with correct character
    hobbit.save

    # Luke should no longer be associated with The Hobbit
    assert_equal 0, hobbit.movie_characters.where(character_id: luke.id).count
    # Frodo is now associated with The Hobbit
    assert_equal 1, hobbit.movie_characters.where(character_id: frodo.id).count
  end
end
```

### Expected behavior
I would expect that, given I'm calling `assign_attributes` (and not calling `.save` or `.update`), that the potential relationship changes in the join table `movie_characters` would not be persisted.

### Actual behavior
Calling `assign_attributes` persists the database changes.

### Additional Thoughts
I realize that Rails provides some convenient methods around managing relationships (in fact, one can be seen [in the example test file given for Active Record issues](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb#L43), where relationships are modified using the `<<` method).

However, I would personally assume `assign_attributes`, which is intended to update the attributes of the record in-memory without persisting changes, would **not** cause any additive/subtractive changes to the data.

Also, the management of these objects without persisting already exists in the context of a new record. Before the movie record is persisted, no join records can be created due to a lack of movie primary key.

### Final Thoughts
Thanks for taking the time to look at this :)

### System configuration
**Rails version**: All currently supported versions

**Ruby version**: 3.0.1

**Comment by sawangupta92** [comment]
Hey @thewatts 

Assign Attributes is just a fancy way of assigning value to variables. You can look at the code [here](https://github.com/rails/rails/blob/75ac626c4e21129d8296d4206a1960563cc3d4aa/activemodel/lib/active_model/attribute_assignment.rb#L28-L53).

In your example, if you simply set hobbit.character_ids = [frodo.id], this should also save the record in the DB.

Although, I do agree with you that this is a confusing behavior as it stores the data in the DB when our intention could be just to assign the attribute.

Still, I am not sure if this is a bug on the code level, but yes, this should be mentioned in docs.

Hope this helps :)

**Comment by thewatts** [comment]
Thanks, @sawangupta92 and @intrip for chiming in 😄 

What you've said makes sense, for sure!

I wonder though - should there be a way for someone to assign these attributes without persisting the db changes?

I get that there are methods in AR to give the developer some convenience, but in our use case - we're wanting to assign these attributes and _not_ persist until we've explicitly told the object to do so (ex: validations didn't pass - so we don't want to save the record changes).

**Comment by zzak** [comment]
@thewatts Sorry for my ignorance, but if you just want attributes w/o persistence couldn't you use AM or a plain-old Ruby object?

**Comment by sawangupta92** [comment]
@thewatts I guess you can always use transactions for this purpose. Just wrap your code within a transaction and raise ActiveRecord::Rollback in case of any errors.
