### ISSUE TITLE
rails6 : "bundle exec rails" is pre loading the environment -> FATAL:  database XX does not exist

### ISSUE THREAD

**Issue by seballot** [rails/rails#42103]
Dear all,

when executing `bundle exec rails db:create`, I got an error cause it try to pre laod the environement, which leads to following error :  `PG::ConnectionBad: FATAL:  database XX does not exist`

Before upgrading (in Rails4), the use of `bundle exec` was preventing such environment preload

I'm wondering if some of my conf is wrong, I have introduced `bootsnap` and `zeitwerk` as recommended, maybe it comes from there?

Rails 6.1.3.1
ruby 2.5.8p224 

**Full log :**

```
user@c6ff8a78b7d8:~$ bundle exec rails db:load_config
warning: parser/current is loading parser/ruby25, which recognizes
warning: 2.5.9-compliant syntax, but you are running 2.5.8.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Could not open library 'libgtk-x11-2.0': libgtk-x11-2.0: cannot open shared object file: No such file or directory.
Could not open library 'libgtk-x11-2.0.so': libgtk-x11-2.0.so: cannot open shared object file: No such file or directory.
Could not open library 'libgtk-x11-2.0.so.0': libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory.
Could not open library 'libgtk-3': libgtk-3: cannot open shared object file: No such file or directory.
Could not open library 'libgtk-3.so': libgtk-3.so: cannot open shared object file: No such file or directory.
Could not open library 'libgtk-3.so.0': libgtk-3.so.0: cannot open shared object file: No such file or directory
/usr/local/bundle/gems/redis-3.3.1/lib/redis/client.rb:459: warning: constant ::Fixnum is deprecated
DEBUG  Rails : **Airbrake: applying remote settings: {}

# --- starts warnings regarding autoloading, mainly because of the cells gem I think ---- #

 WARN  Rails : DEPRECATION WARNING: Initialization autoloaded the constants TranslationsHelper, CourseApplicationCell, FormCell, ActionText::ContentHelper, and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload TranslationsHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:

    Rails.application.reloader.to_prepare do
      # Autoload classes and modules needed at boot time here.
    end

That block runs when the application boots, and every time there is a reload.
For historical reasons, it may run twice, so it has to be idempotent.

Check the "Autoloading and Reloading Constants" guide to learn more about how
Rails autoloads and reloads.

# --- ends warnings regarding autoloading --- #

 (called from <top (required)> at /app/config/environment.rb:21)
DEBUG  Rails : **Airbrake: applying remote settings: {"project_id"=>136768, "updated_at"=>1595827321, "poll_sec"=>0, "config_route"=>"2020-06-18/config/136768/config.json", "settings"=>[]}
rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "reg_dev" does not exist
/app/config/environment.rb:42:in `<top (required)>'

Caused by:
PG::ConnectionBad: FATAL:  database "reg_dev" does not exist
/app/config/environment.rb:42:in `<top (required)>'
Tasks: TOP => db:load_config => environment
(See full trace by running task with --trace)
DEBUG  Rails : **Airbrake: thread pool closed
DEBUG  Rails : **Airbrake: thread pool closed
DEBUG  Rails : **Airbrake: performance notifier closed
```

**config/environement.rb**

```
# Load the Rails application
require_relative 'application'

# .... Some code ...

# Initialize the Rails application
(line 21) Rails.application.initialize! 

# .... Some code ...
```

**Maybe related issues?**

- https://github.com/rails/spring/issues/125#issuecomment-576058388

Thank you so much for your help !

**Comment by pixeltrix** [comment]
Two things to try:

1. To see if it's a `spring` issue you can temporarily disable it by running the command like this:

    ```
    DISABLE_SPRING=1 bundle exec rails db:create
    ```

2. There's a warning about "Initialization autoloaded the constants ..." - some of those autoloaded classes may be triggering database connections. Try wrapping them in a `to_prepare` block like the warning suggests.

If those don't work, run the `rake` command with `--trace` so you can see the backtrace to get more information. Also you can see that the error is raised on line 42 of `config/environment.rb:42`. The default version of this file only has 5 lines so there's some heavy customisation in there that you're masking with '# .... Some code ...' in your description - it's likely the issue is in that block of code.

**Comment by seballot** [comment]
moving my custom `config/environement` code into a `to_prepare` block solved the issue ! Thanks a lot @pixeltrix !

**Comment by alecernas** [comment]
@seballot hello, qq, where did you move your code? I am seeing the same breaking my app

**Comment by seballot** [comment]
Hi @alecernas, I moved it into an initializer : `config/initializers/YOUR_FILE.rb`

**Comment by baranyeni** [comment]
Hi, as my initiliazier environment.rb as same as with the default one I have the same exact problem. What can be trigging DB connection when I try to run **bundle exec db:create** or **bundle exec db:migrate**. Is there any way that I can trace what specific lines are triggered with the commands I ran. Thanks.

**Comment by youssef1337** [comment]
@seballot Mine is actually failing because of code inside `config/initializers` and I still do not get how to avoid preloading when doing `bundle exec rails db:create`, any ideas?
