### ISSUE TITLE
FactoryBot using ActiveStorage exceptions with ActiveStorage::IntegrityError 

### ISSUE THREAD

**Issue by alr888** [rails/rails#42100]
An old spec that has been working for over a year has recently started failing and I have pinned it down to the method ensure_integrity_of(key, checksum) (in activestorage/lib/active_storage/service/disk_service.rb) where the result of Digest::MD5.file(path_for(key)).base64digest != checksum.

The ActiveStorageBlob has the checksums and not sure why Digest::MD5.file(path_for(key)).base64digest with return a different value.

The only spanner we have is this is running in a Docker container.  

### Steps to reproduce

Here is our factories/person_attachment:

`FactoryBot.define do
  factory :person_attachment, class: "Person::Attachment" do
    person
    user
    name { Faker::File.file_name }
    description { "Description" }
    attachment do
      Rack::Test::UploadedFile.new(
        Rails.root.join("Gemfile"),
        "text/plain"
      )
    end
  end
end`

### Expected behavior

I expect the checksums to be equal.

### Actual behavior

Checksums differ.

### System configuration
**Rails version**:  6.0.3.6

**Ruby version**:  2.6.6p146

**Comment by byroot** [comment]
It's really unclear what your issue is. Would it be possible to provide a [reproduction script](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_storage_gem.rb)?

**Comment by alr888** [comment]
Hi @byroot, its related to the docker version similar to this issue: https://github.com/docker/for-mac/issues/5570
Initially  reinstalling version 3.2.2 didn't work for me, I had to do remove docker and do a fresh install which eventually worked.

**Comment by alr888** [comment]
Hi @byroot, its related to the docker version similar to this issue: https://github.com/docker/for-mac/issues/5570
Initially  reinstalling version 3.2.2 didn't work for me, I had to do remove docker and do a fresh install which eventually worked.

**Comment by leikind** [comment]
having the same issue in Docker for Mac 3.3.0 and 3.3.1

**Comment by pixeltrix** [comment]
One solution if you don't want to downgrade docker is to use `tmpfs` for `/tmp` - just add the following to your service in docker-compose.yml:

```
tmpfs:
  - /tmp
```

That fixed some failures I was seeing with the Dragonfly gem which were the same underlying docker issue.

**Comment by fernandoaleman** [comment]
> One solution if you don't want to downgrade docker is to use `tmpfs` for `/tmp` - just add the following to your service in docker-compose.yml:
@pixeltrix Thanks so much. This fixed my issue 👍
