### ISSUE TITLE
`collection=` for a `has_many` association doesn't persist added records already referencing the parent when `has_many_inversing` is enabled

### ISSUE THREAD

**Issue by waiting-for-dev** [rails/rails#42102]
Given:
- `ActiveRecord::Base.has_many_inversing = true`.
- Reciprocal associations `has_many`/`belongs_to` between two models (e.g. `Parent` and `Node`) with `inverse_of` enabled.

When:
- A `Parent` record is created.
- A `Node` record is initialized with reference to the created `Parent` record.
- `Parent.nodes=` is invoked with the node record within an array.

Then:
- The `Node` record doesn't get persisted.

This snippet reproduces the bug. All tests will succeed besides the first one. The success test cases have a `# <---` comment on the lines that differ from the failing case.

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  gem 'activerecord', '6.1.3.1'
  gem 'sqlite3'
end

require 'active_record'

ActiveRecord::Base.has_many_inversing = true
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: 'bug.db')

ActiveRecord::Schema.define do
  create_table :parents, force: true do |t|
    t.timestamps
  end
  create_table :nodes, force: true do |t|
    t.references :parent, foreign_key: false
    t.timestamps
  end
end

class Parent < ActiveRecord::Base
  has_many :nodes, inverse_of: :parent
end

class Node < ActiveRecord::Base
  belongs_to :parent, inverse_of: :nodes
end

require 'minitest/autorun'

class BugTest < Minitest::Test
  def test_bug
    parent = Parent.new
    parent.save
    node = Node.new(parent: parent)

    parent.nodes = [node]

    assert_equal(
      true,
      node.persisted?
    )
  end

  def test_no_bug_if_parent_is_not_set_in_node
    parent = Parent.new
    parent.save
    node = Node.new # <---

    parent.nodes = [node]

    assert_equal(
      true,
      node.persisted?
    )
  end

  def test_no_bug_if_push_is_used
    parent = Parent.new
    parent.save
    node = Node.new(parent: parent)

    parent.nodes << node # <---

    assert_equal(
      true,
      node.persisted?
    )
  end

  def test_no_bug_if_has_many_inverse_is_disabled
    ActiveRecord::Base.has_many_inversing = false # <---

    parent = Parent.new
    parent.save
    node = Node.new(parent: parent)

    parent.nodes = [node]

    assert_equal(
      true,
      node.persisted?
    )

    ActiveRecord::Base.has_many_inversing = true # <---
  end
end
```

**Comment by dmitry** [comment]
@gmcgibbon any ideas what can lead to this issue?

**Comment by gmcgibbon** [comment]
https://github.com/rails/rails/blob/3cf6378a5b92cea3b5e2030f43a12ac05017e8cc/activerecord/lib/active_record/associations/collection_association.rb#L241

Collection proxy assignment only performs a transaction if the new records are different from the original ones. Because the inverse is set in the first test, the target does not change. This is a subtle difference in behaviour, but I think it is correct. It is also noted in the [`replace` method](https://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-replace). Since I don't see a bug here, I'm going to close this. Thanks for the issue!

**Comment by waiting-for-dev** [comment]
Hey, thanks for looking into it.

> Collection proxy assignment only performs a transaction if the new records are different from the original ones.

It looks like performing a decision according to a non-correlated reason. If we want to persist sometimes, it should depend on whether the records are persisted or not. In my view, `collection=` should not persist ever. Having an apparently innocuous assignment to perform a transaction breaks a lot of expectations. This issue makes clear we're coupling assignment with persistence. However, changing it would break old behavior.

**Comment by dmitry** [comment]
Behaviour is also related to the `collection_ids=`. More on that: https://github.com/rails/rails/issues/29420
