### ISSUE TITLE
Wrong compile option during Rails installation on Clear Linux OS?

### ISSUE THREAD

**Issue by espio999** [rails/rails#42117]
Install Rails with "sudo gem install rails" on Clear Linux OS, building gem is failed at "websocket-driver".

Error said
"gcc: error: unrecognized command-line option ‘-mzero-caller-saved-regs=used’; did you mean ‘-fzero-call-used-regs=’?"

Is Makefile with inappropriate compiling option dynamically generated during installation process?
It looks associated with the next topic.
https://gcc.gnu.org/pipermail/gcc-patches/2020-July/550018.html

### Steps to reproduce
Process of installation
1. install following bundles with command "sudo swupd bundle-add"
-ruby-basic
-sqlite
-nodejs-basic
-c-basic
-devpkg-sqlite-autoconf

2. setup command of ruby and rails
`sudo gem update --system`

Error at "websocket-driver"

### Expected behavior
Rails is successfully installed.

### Actual behavior
Next error is reported.

```
wsluser@paulownia~ $ sudo gem install rails
Password:
Building native extensions. This could take a while...
ERROR:  Error installing rails:
        ERROR: Failed to build gem native extension.

    current directory: /usr/lib64/ruby/gems/2.7.0/gems/websocket-driver-0.7.3/ext/websocket-driver
/usr/bin/ruby -I /usr/lib64/ruby/site_ruby/2.7.0 -r ./siteconf20210501-2471-f0bjii.rb extconf.rb
creating Makefile

current directory: /usr/lib64/ruby/gems/2.7.0/gems/websocket-driver-0.7.3/ext/websocket-driver
make DESTDIR\= clean

current directory: /usr/lib64/ruby/gems/2.7.0/gems/websocket-driver-0.7.3/ext/websocket-driver
make DESTDIR\=
compiling websocket_mask.c
gcc: error: unrecognized command-line option ‘-mzero-caller-saved-regs=used’; did you mean ‘-fzero-call-used-regs=’?
make: *** [Makefile:245: websocket_mask.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/lib64/ruby/gems/2.7.0/gems/websocket-driver-0.7.3 for inspection.
Results logged to /usr/lib64/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/websocket-driver-0.7.3/gem_make.out
```

### System configuration
**Rails version**:
```
wsluser@paulownia~ $ rails -v
Rails 6.1.3.1
```

**Ruby version**:
```
wsluser@paulownia~ $ ruby -v
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux-gnu]
```

**Clear Linux OS**:
```
wsluser@paulownia~ $ cat /etc/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=34560
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
BUILD_ID=34560
```

**Comment by pixeltrix** [comment]
@espio999 this seems to be an issue with your build configuration - the gem involved is websocket-driver and doesn't configure that option as it uses the mkmf library that comes with Ruby to generate its Makefile. Either way it's not an issue with Rails so I'm going to close this issue.
