### ISSUE TITLE
Issue with belongs_to associations when missing models

### ISSUE THREAD

**Issue by dferrazm** [rails/rails#42122]
I noticed something strange with the `belongs_to`. I'm not sure if that's by design.

```rb
class Foo < ApplicationRecord
  belongs_to :post
  has_many :comments
end

foo = Foo.new
foo.post # => nil
foo.comments # => NameError (uninitialized constant Foo::Comment)
```

As we can see, with the `has_many` association, an error is raised, which is epxected, since there's no `Comment` class defined. The  `belongs_to` association on the other hand silently returns. Which is a lack of consistency imho. The ideal would be to fail loud in this case too, since this is a (most probably unintentional) mistake during the task of removing a feature and its references, but fogetting to remove some of the associations.

This can be a source of bugs that can go unnoticed. Most probably will be caught during the tests / CI, but still, the lack of consistency is also a problem.

### System configuration
**Rails version**: 6.1.3.1
**Ruby version**: 2.7

**Comment by ghiculescu** [comment]
[Full replication](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case)

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :foos, force: true do |t|
  end
end

class Foo < ActiveRecord::Base
  belongs_to :post
  has_many :comments
end

class BugTest < Minitest::Test
  def test_what_crashes
    foo = Foo.new
    assert_raises(NameError) { foo.post }
    assert_raises(NameError) { foo.comments }
  end
end
```

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/42124 should fix this 👍
