### ISSUE TITLE
Schema and Migration file can't express parser option when using fulltext index

### ISSUE THREAD

**Issue by sblim0126** [rails/rails#42131]
### Steps to reproduce
We can set parser options when add a fulltext index to mysql.
Default parser is white space, but we can choose a different parser.
[MySQL doc url](https://dev.mysql.com/doc/refman/5.7/en/fulltext-search-ngram.html)

Migration file example,
```RUBY
  def up
    create_table :items do |t|
      t.string  :name
      t.text    :description
      t.timestamps
    end
    execute 'CREATE FULLTEXT INDEX index_items_on_description ON items(description) WITH PARSER ngram'
  end
```

I think it's better expression in migration file when fulltext index with parser
```RUBY
  def up
    create_table :items do |t|
      t.string  :name
      t.text    :description
      t.timestamps
    end
    add_index :items, :description, type: :fulltext, parser: :ngram
  end
```

And Generated schema file can't express parser option about fulltext index.

### Expected behavior

```RUBY
  create_table "items", charset: "utf8mb4", collation: "utf8mb4_unicode_ci", force: :cascade do |t|
    t.string "name"
    t.text "description"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["description"], name: "index_items_on_description", type: :fulltext, parser: :ngram
```
### Actual behavior

```RUBY
  create_table "items", charset: "utf8mb4", collation: "utf8mb4_unicode_ci", force: :cascade do |t|
    t.string "name"
    t.text "description"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["description"], name: "index_items_on_description", type: :fulltext
```

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: 2.6.6

**Comment by lfalcao** [comment]
hi @sblim0126 

I've written a test script in order to reproduce this: https://gist.github.com/lfalcao/4a816f763897904ad61e0dcca818c6ba

I'm looking to fix it in my fork (https://github.com/lfalcao/rails/commit/fe560162fa252c90d39946f453503d9edfe48611) still need to write tests and fix some things, but its passing the test...

**Comment by byroot** [comment]
I don't quite remember the policy on supporting advanced features like this one in `schema.rb` format. So I'm not sure wether this feature is acceptable.

But in the meantime there is `config.active_record.schema_format = :sql` https://guides.rubyonrails.org/active_record_migrations.html#types-of-schema-dumps which should solve your problem.

**Comment by lfalcao** [comment]
So, close this issue? cc/ @zzak
