### ISSUE TITLE
Virtual attributes value is shared across instances when used with an array or hash typed default

### ISSUE THREAD

**Issue by husam212** [rails/rails#42145]
### Steps to reproduce
Generate any test model.
```
rails g model Test
```
Add a virtual attribute to the model with an array or hash typed default value.
```
class Test < ApplicationRecord
  attribute :foo, default: []
end
```

### Expected behavior
Each instance will have its own value of `foo` attribute.
```
t1 = Test.new
t2 = Test.new

t1.foo << :bar
t2.foo #=> []
```

### Actual behavior
Instances share the value of `foo` attribute.
```
t1 = Test.new
t2 = Test.new

t1.foo << :bar
t2.foo #=> [:bar]
```

### System configuration
**Rails version**: 6.1.3.1

**Comment by byroot** [comment]
The problem here is that you provide a mutable object as default, you should pass it as a proc so that every instance gets it's own array:

```ruby
class Test < ApplicationRecord
  attribute :foo, default: -> { [] }
end
```
