### ISSUE TITLE
[activesupport] requiring active_support makes object respond to blank?

### ISSUE THREAD

**Issue by alx75** [rails/rails#42152]
### Expected behavior
According to the [documentation](https://guides.rubyonrails.org/active_support_core_extensions.html)
Doing
`require "active_support"
`
should not make objects respond to blank?.

### Actual behavior
Doing
`require "active_support"
`
makes objects respond to blank?

### System configuration
**Rails version**:
This has been introduced by [this](https://github.com/rails/rails/commit/2ec1bad4ad) commit so all version after v6.1.0.rc1
**Ruby version**:
2.6.6

**Suggestion:**

Either update the documentation or do not use extensions in files required by active_support.rb.

**Comment by malclocke** [comment]
Full issue here is that:
- `require "activesupport"` requires `active_support/dependencies/autoload`
- `Autoload.autoload` uses `Inflector.underscore` so requires `active_support/inflector/methods`
- Private method `Inflector.const_regexp` (used indirectly from a `rescue` in `Inflector.safe_constantize`) uses `.blank?` so requires `active_support/core_ext/object/blank`.

I think realistically it's likely to be a documentation fix.  The linked guide says:

> In order to have a near-zero default footprint, Active Support does not load anything by default.

The reality at the time of writing is that `require "active_support"` triggers about 150 other `require`s by my reckoning, so the 'near-zero footprint' statement in the guide is a bit of a lie.
