### ISSUE TITLE
[BUG] object allocation during garbage collection phase

### ISSUE THREAD

**Issue by Kryze** [rails/rails#42159]
### Steps to reproduce

It happened sometimes when I'm navigating in my application, I don't really know the cause

### Expected behavior
Normal navigation

### Actual behavior
The application crashed while printing thousand of lines and also
`C;/Ruby27-x64/lib/ruby/gems/2.7.0/action-pack-6.1.3/lib/action_dispatch/middleware/static.rb:140: [BUG] object allocation during garbage collection phase`

### System configuration
**Rails version**:
6.1.3
**Ruby version**:
2.7.2

**Comment by byroot** [comment]
This is a Ruby interpreter crash, so it can only be a Ruby (as in MRI) bug, or a C extension bug.

If you can get the full crash report, you can report it upstream: https://bugs.ruby-lang.org/projects/ruby-master/issues.

Thanks.
