### ISSUE TITLE
ActiveStorage purge in development deletes file from S3

### ISSUE THREAD

**Issue by atstockland** [rails/rails#42186]
Sometimes I pg:pull my production db.  ActiveStorage attachment blobs that were created in production are given a :service_name equal to the storage service that was used during upload.  In my storage.yml I have a :local service for development and an :amazon service for production.  When I pg:pull the production database, the blobs have "amazon" service types.  If I purge a file (ie: User.find(1).avatar.purge) in development the file on S3 will be deleted and the production record will now render a broken img reference.

I have verified all my local settings including config.active_storage.service in all environments, usage of bucket definition only in the :amazon service for production, and that my local app is in fact running in development environment.

It seems that rails is reading the new :service_name column and, regardless of the environment or environment configs, is calling on that service.

### Steps to reproduce
In development, set your storage service to a remote service (ie S3).  Add an attachment.  Verify the associated blob has that service name saved in the :service_name column.  Verify that image exists on the remote service.  Change the storage service to back to local storage, purge the attachment, verify that attachment was deleted from the remote service.

### Expected behavior
Since the development service is set to local, the remote image should not be deleted...even though the blob does have a remote service_name.

### Actual behavior
Rails seems to be ignoring development configs and simply calls on the service that is saved as an attribute of the blob.  Which causes problems if the db has been pulled down from production and then purge is called on records locally.

### System configuration
Rails: 6.1.3.2

Ruby: 3.0.1

**Comment by ghiculescu** [comment]
Hmmm, this sounds like it's technically correct behavior, but certainly very surprising. Similar to https://github.com/rails/rails/pull/22967, maybe we need a similar feature to that for Active Storage.

**Comment by ghiculescu** [comment]
I thought about this more. I think an optional `environment(s)` parameter in storage.yml would be the way to totally prevent this issue.

```erb
amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: us-east-1
  bucket: <%= Rails.env %>-files
  environment: production
```

Then the [`ActiveStorage::Service::Registry`](https://github.com/rails/rails/blob/2af458a10d336ec15a5734dba27709c2f8eb745b/activestorage/lib/active_storage/service/registry.rb#L4) would only return services whose `environment` is blank, or matches the `Rails.env`.

**Comment by ghiculescu** [comment]
Having a go at implementing in https://github.com/rails/rails/pull/42193

**Comment by zzak** [comment]
I think similar to #42188 we can probably add something to the [ActiveStorage guide](https://edgeguides.rubyonrails.org/active_storage_overview.html#setup). 🤔

**Comment by dylanfisher** [comment]
An alternative approach is to define a custom ActiveStorage Service, and customize the `delete` methods how you see fit.

```ruby
# lib/active_storage/service/s3_safe_delete_service.rb

require "active_storage/service/s3_service"

class ActiveStorage::Service::S3SafeDeleteService < ActiveStorage::Service::S3Service
  def delete(key)
    if Rails.env.production?
      super
    else
      Rails.logger.debug { "Skipping deletion of #{key} in #{Rails.env} environment." }
    end
  end

  def delete_prefixed(prefix)
    if Rails.env.production?
      super
    else
      Rails.logger.debug { "Skipping deletion of #{prefix} prefixed objects in #{Rails.env} environment." }
    end
  end
end
```

Then in your `config/storage.yml` file, use your custom service:

```yaml
amazon:
  service: S3SafeDelete
  access_key_id: ""
  secret_access_key: ""
  bucket: ""
  region: ""
```

**Comment by mhenrixon** [comment]
> An alternative approach is to define a custom ActiveStorage Service, and customize the `delete` methods how you see fit.

You saved my sanity! I have been pulling the hairs from my head because images sometimes went missing. 

Thank you @dylanfisher
