### ISSUE TITLE
Broken links in activemodel/README.rdoc

### ISSUE THREAD

**Issue by martinjaimem** [rails/rails#42208]
## Steps to reproduce
This Issue is a copy of #42206 
Go to Active Model's README file and click on any of the Learn More links in the file. [Here is an example of one of those links.](https://github.com/rails/rails/blob/main/activemodel/classes/ActiveModel/Callbacks.html)

## Expected behavior
There was originally a document that these links pointed to which explained some of the ActiveModel concepts, but there are no longer present.

## Actual behavior
[A GitHub 404 page.
](https://github.com/rails/rails/blob/main/activemodel/classes/ActiveModel/Callbacks.html)
## System configuration
N/A, error happens with the repo's own deployed config

**Comment by byroot** [comment]
Explanation in https://github.com/rails/rails/pull/42209
