### ISSUE TITLE
Final newline rendered in partials

### ISSUE THREAD

**Issue by boardfish** [rails/rails#42201]
### Steps to reproduce

See [test repo](https://github.com/boardfish/view_component-bug). `bundle && rails s`, then navigate to localhost:3000.

The test repo has a partial that renders an anchor tag. The file ends with a newline, which is commonly established as a standard.

Identified in github/view_component#913. It's worth checking out that issue and the linked PR for some further insight.

### Expected behavior

The following should be rendered:

```html
<p>
  <a href="https://simon.fish">Add Test template here</a>, <a href="https://simon.fish">Add Test template here</a>, and also <a href="https://simon.fish">Add Test template here</a>
</p>
```

### Actual behavior

The following is rendered:

```html
<p>
  <a href="https://simon.fish">Add Test template here</a>
, <a href="https://simon.fish">Add Test template here</a>
, and also
  <a href="https://simon.fish">Add Test template here</a>
</p>
```

The newlines introduced by `render` appear as a singular space before the commas in the first two instances. It renders like this:

![Screen Shot 2021-05-12 at 13 52 09](https://user-images.githubusercontent.com/20680337/117818049-20184c80-b260-11eb-8dda-f60ee53f0a1f.png)

I'm aware that `<%= -%>` is expected to strip trailing whitespace, but it doesn't appear to do so when rendering partials or ViewComponents. I figure this is most likely an ActionView-specific problem.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.7.2p137

**Comment by lfalcao** [comment]
@boardfish both partials have a newline at the end. Its not the `render` method who is adding them...

**Comment by boardfish** [comment]
What I'm saying is that the newline should be ignored. I'll copy my comment from github/view_component#920 here:

> It seems as though the final newline of the template file is rendered, even though this usually indicates the end of a file.
>
> As @\Spone mentioned, trailing newlines are something of a standard ([here's one stance on why](https://unix.stackexchange.com/a/18789), if you're
> curious). It's definitely something we lint for over @raisedevs and something [RuboCop](https://www.rubydoc.info/gems/rubocop/0.20.1/Rubocop/Cop/Style/FinalNewline) checks out.
>
> A per-component or global option would be a great idea. :sparkles:

**Comment by boardfish** [comment]
When you see the :no_entry: symbol at the end of a GitHub diff, that means there's no trailing newline to mark the end of the file.

**Comment by zzak** [comment]
> I'm aware that <%= -%> is expected to strip trailing whitespace, but it doesn't appear to do so when rendering partials or ViewComponents. I figure this is most likely an ActionView-specific problem.

@boardfish I would be surprised if this is the case, but I don't see how this would work.

It appears we're defaulting the ERB trim mode to "-" [here](https://github.com/rails/rails/blob/002c4fe6d9bf2b76bd2c1d365614ad1e0cef17df/actionview/lib/action_view/template/handlers/erb.rb#L9-L11) which should "`-  omit blank lines ending in -%>`" as the [ERB docs](https://docs.ruby-lang.org/en/master/ERB.html#method-c-new) suggest.

What am I missing? 🤔

**Comment by boardfish** [comment]
I see. I think I might've misunderstood the function of that trim mode. It looks like it wouldn't be responsible for removing a solitary trailing newline as I'd originally hoped:

```ruby
pry(main)> x = ERB.new("<span>Hello, world!</span>", trim_mode: '-').run
<span>Hello, world!</span>nil # desired render output
pry(main)> x = ERB.new("<span>Hello, world!</span>\n", trim_mode: '-').run
<span>Hello, world!</span>
nil # actual render output
```

I was hoping that might be the solution to my issue, but I was wrong. Apologies for the red herring there.

I guess the thing I'm asking for is a configuration option for ActionView that can trim that final newline whenever we're `render`ing something, be that a partial, layout, view, or component.

**Comment by zzak** [comment]
@boardfish If I'm understanding correctly, rendering partial does trim the trailing new-line? But you want to support this for other render modes?

**Comment by boardfish** [comment]
Rendering a partial does not trim the trailing newline in the template. This is also the case for rendering components.

I'd like Rails to support trimming the trailing newline because (at least for my use case) it's only there to signify the end of the file.

**Comment by zzak** [comment]
I think making it optional/configurable would be nice, I'm just not sure where that would go. 🤔

**Comment by zzak** [comment]
Took another look at this, and pasting my results just so it's not scattered.

## <%= %> tags

index.html.erb: 
```
<p>
  <%= render 'test_partial' %>,
  <%= render 'test_partial' %>, and also
  <%= render 'test_partial' %>
</p>
```

_test_partial.html.erb: 
```
<a href="https://simon.fish">Add Test template here</a>
```

Result: 
```
<p>
  <a href="https://simon.fish">Add Test template here</a>
,
  <a href="https://simon.fish">Add Test template here</a>
, and also
  <a href="https://simon.fish">Add Test template here</a>

</p>
```

## <% -%> tags

index.html.erb:
```
<p>
  <%= render 'test_partial' -%>,
  <%= render 'test_partial' -%>, and also
  <%= render 'test_partial' -%>
</p>
```

Result:
```
    <p>
  <a href="https://simon.fish">Add Test template here</a>
,
  <a href="https://simon.fish">Add Test template here</a>
, and also
  <a href="https://simon.fish">Add Test template here</a>
</p>
```

**Comment by pixeltrix** [comment]
You can just `strip` the rendered content:

``` erb
<p>
  <%= render('test_partial').strip %>,
  <%= render('test_partial').strip %>, and also
  <%= render('test_partial').strip %>
</p>
```

Either that or use a custom helper to build the content. I'd be loathe to add some global config for this.

**Comment by pixeltrix** [comment]
I realised that would make the string be not tagged as html safe so here's a helper method that does what you want:

``` ruby
module ApplicationHelper
  def render(*)
    super.chomp.html_safe
  end
end
```

**Comment by boardfish** [comment]
That's really neat and concise. I think it does what I want, but as with any patch, I'm a little uncertain about adding it without being sure of its side effects. I'd feel much more comfortable if it were integrated into Rails itself and fully tested. I'd argue that it should really be the default behavior, as that final newline isn't meant to be interpreted.

Also, I don't think simply overriding the `render` helper would have this carry over to other things like layouts. That's not a problem for me personally, but it'd be good to make sure this is consistent across the entire view layer.

Having dug about a bit, I wonder if it'd be possible to achieve this [here](https://github.com/rails/rails/blob/c453a5fa88e89bc0bc8efde3b397f2464712bb49/actionview/lib/action_view/renderer/abstract_renderer.rb#L141):

```ruby
def body
  strip_final_newline(super)
end

private

def strip_final_newline(string)
  # I'm not sure how to get to top-level Action View config as you'd have in application.rb, but hopefully the gist is there
  config.action_view.strip_final_newline ? string.chomp : string
end
```

That being said, I've struggled to get my head around the guts of Action View's renderer, so I wouldn't be surprised if that's the wrong place to put this.

**Comment by boardfish** [comment]
Turns out I was right! [Here's the commit on my repo](https://github.com/boardfish/view_component-bug/commit/ff5ad9c220e2f83755cb4c79efbe4dff4263d51a) that shows where this can be implemented.

There's a double-edged sword in that the original bug (github/view_component#913) would also need to be resolved in that repo. But I think that's good, because it means this change is isolated to Action View and not anything that implements `render_in`.

I can look into opening a PR soon and discussion can continue from there.
