### ISSUE TITLE
Broken links in activerecord/README.rdoc

### ISSUE THREAD

**Issue by Joseph-Burke** [rails/rails#42206]
### Steps to reproduce
Easy! Just go to [Active Record's README file](https://github.com/rails/rails/blob/main/activerecord/README.rdoc) and click on the link which says _Learn More_ on Line 25, or on any of the many identical links throughout the document.

### Expected behavior
Presumably there was originally a document that these links pointed to which explained some of the ActiveRecord concepts more, but there are no longer.

### Actual behavior
A GitHub 404 page (see below).

### System configuration
N/A, error happens with the repo's own deployed config

![image](https://user-images.githubusercontent.com/56026099/117892692-179c3200-b2b1-11eb-94ab-958dfb93fab6.png)

**Comment by zzak** [comment]
@Joseph-Burke This confused me once many years ago, but the answer then was that these files are meant to be read in our generated docs i.e. [api.rubyonrails.org](https://edgeapi.rubyonrails.org/files/activerecord/README_rdoc.html).

I'm not sure this has change or if it's officially documented anywhere though in general, I think internal document links are using the rdoc syntax by constant and file lookup that aren't supported in GitHub's Markdown/RDoc parser.

**Comment by Joseph-Burke** [comment]
@zzak Hahaha, I was a bit surprised actually. It's not as if Rails is some old, unmaintained repo where I would expect to find dead links! 

I've just taken a look at #42207 that @martinjaimem linked - I think this fix is great. I don't know much about rdoc, but I think it's best if these links are accessible for visitors to the GH repo, so replacing the `link:` with `https://api.rubyonrails.org/` will bring take visitors somewhere more useful.

Thanks to you both :D Closing this issue now
