### ISSUE TITLE
custom validation only considered in one with_options block 

### ISSUE THREAD

**Issue by JimEvansIntox** [rails/rails#42204]
### Steps to reproduce
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :examples, force: true do |t|
    t.text :status
  end
end

class Example < ActiveRecord::Base
  with_options if: :in_process? do
    validate :this_is_never_valid # change to this_is_never_ever_valid and everything passes
  end

  with_options if: :complete? do
    validate :this_is_never_valid
  end
  # In the above, the 2nd with_option works and the 1st doesn't.
  # If you switch the order, the test results change accordingly


  def complete?
    status == 'complete'
  end

  def in_process?
    status == 'in process'
  end

  private

  def this_is_never_valid
    unless 1 == 2
      errors.add(:status, 'one does not equal two')
    end
  end

  def this_is_never_ever_valid
    this_is_never_valid
  end


end

class BugTest < Minitest::Test
  def test_complete_validation
    complete = Example.create!
    complete.status = 'complete'
    assert complete.complete?
    refute complete.valid?
    refute complete.save
  end

  def test_in_process_validation
    in_process =  Example.create!
    in_process.status = 'in process'
    assert in_process.in_process?
    refute in_process.valid?
    refute in_process.save
  end
end
```

### Expected behavior
Tests should pass because both validations should fail

### Actual behavior
The first validation doesn't seem to be applied, but the second one is. If you use two differently named custom validations, though, it behaves as expected

### System configuration
** Rails Version **
Verified on 6.0,6.1

**Ruby version**:
2.7.2

**Comment by martinjaimem** [comment]
I think `validate` creates a callback with the name provided.

It is in the rails documentation under Notes. [You can see it here](https://api.rubyonrails.org/classes/ActiveModel/Validations/ClassMethods.html#method-i-validate)
***NOTE: Calling validate multiple times on the same method will overwrite previous definitions.***

Anyway, you can add your custom condition that is an OR of both stated above, or you can [combine conditions by passing an array](https://guides.rubyonrails.org/active_record_validations.html#combining-validation-conditions) to the `if`.

**Comment by JimEvansIntox** [comment]
@martinjaimem Thank you for pointing me to that section of the documentation. It looks like this is expected behavior. I'll tweak my code accordingly.
