### ISSUE TITLE
rails 6.1 novalidate is not added on the page

### ISSUE THREAD

**Issue by mehras1991** [rails/rails#42235]
I'm trying to add novalidate to the form, but it doesn't actually add it on the page and I end up seeing browser popups.

I'm trying to add it to this line where my form start. on the browser **novalidate** is not added anyways.

I have also tried adding `novalidate: 'novalidate'` and other ways but no luck. true or false, novalidate is not add to the form tag I'm on rails 6.1

on this line of novalidate is not added. 
`<%= form_with model: @grad, class: 'needs-validation', novalidate: 'true' do |form| %>`

**Comment by lfalcao** [comment]
@mehras1991 try this:

` <%= form_with model: @grad, html: { class: 'needs-validation', novalidate: 'true' } do |form| %>`

**Comment by mehras1991** [comment]
> @mehras1991 try this:
> 
> ` <%= form_with model: @grad, html: { class: 'needs-validation', novalidate: 'true' } do |form| %>`

Thank you so much it fixed it 🙏
