### ISSUE TITLE
ActiveRecord::Migration rename_column should rename the foreign key constraint as well

### ISSUE THREAD

**Issue by agvald** [rails/rails#42259]
### Steps to reproduce

Create a migration with this code in the change method
```ruby
    create_table :users do |t|
      t.column :id, :integer
      t.column :name, :string
    end

    create_table :invoices do |t|
      t.column :id, :integer
      t.column :user_id, :integer
    end

    add_index :invoices, :user_id
    add_foreign_key :invoices, :users  # has name fk_rails_3d1522a0d8

   rename_column :invoices, :user_id, :created_by_id
   # this will rename the column, the index will have both the values and name updated
   # the  foreign key constraint will have its values updated but not the name. 
   # which means we can easily create duplicate foreign key constraints like this:
   add_foreign_key :invoices, :users  # has name fk_rails_6d5296f05d
```
the index is just there for the example to be as full as possible.

### Expected behavior

`#rename_column` should update the foreign key constraint name.
Then the `add_foreign_key table, :users, column: :created_by_id` would raise since the name would not be unique

### Actual behavior

rename_column does not update the foreign ket constraint name.

### System configuration
**Rails version**: 6.1.3.1

**Ruby version**: 2.6.6

**PostgreSQL version**: 12.4

As a workaround we did  the following:
```ruby
class RenameInvoiceUserToCreatedBy < ActiveRecord::Migration[6.1]
  def change
    rename_column :invoices, :user_id, :created_by_id

    # AR gives the foreign key a name to prevent duplicate foreign keys
    # the name depends on the table and column but rename_column does not fix the FKC name
    remove_foreign_key table, :users, column: :created_by_id
    add_foreign_key table, :users, column: :created_by_id
  end
end
```

**Comment by zzak** [comment]
I want to say this is intended behavior, because renaming a foreign key unintentionally could have severe consequences.

Is there not an existing `rename_foreign_key` method? 🤔

**Comment by agvald** [comment]
> I want to say this is intended behavior, because renaming a foreign key unintentionally could have severe consequences.

Could you briefly mention what consequences you are thinking about?
I could not on the top of the mind come up with something which would be affected by the foreign key constraint rename while not affected by  the column rename.
Since it renames the index i would assume it renamed the foreign_key_constraint as well. 
 
> Is there not an existing `rename_foreign_key` method? 🤔

Not that i could find.

**Comment by pixeltrix** [comment]
@agvald there might actually be a deeper bug here - the foreign key name is derived from the table and column options so it's possible that by failing to rename the foreign key we prevent being able to remove it later.

What happens if you try to do the following migrations:

1. Add foreign key to a column
2. Rename column
3. Remove foreign key using the new column name

If step 3 fails, what happens if you try to drop it using the original column name?

I suspect the answers to this will vary across databases.

**Comment by lfalcao** [comment]
It's not just the case to when call `rename_column` checks if there's any fk related to that column, and depending of the database system drop and recreate it or just rename? It seems like a simple issue to fix.

**Comment by agvald** [comment]
> @agvald there might actually be a deeper bug here - the foreign key name is derived from the table and column options  so it's possible that by failing to rename the foreign key we prevent being able to remove it later.

with PostgreSQL it will drop the correct index, no problems.
I am not fully aware what other databases i should test with.... (Is it still  SQLite, MySQL and PostgreSQL?)
Don't see much value in testing this unless we know a fix is wanted/would be accepted...

If someone can confirm this feature-enhancement is wanted I'll have a go at fixing the code for rename_column and create a PR :D
I am assuming [this](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L438) is the correct place to start on PostgreSQL...
