### ISSUE TITLE
Named route helper problem when optional part assigned  false value

### ISSUE THREAD

**Issue by bogdan** [rails/rails#42280]
### Steps to reproduce

Script: https://gist.github.com/935fc4dbd6ba723cf3e8a6d3ede56106

1. Make a new rails app
2. Add the following to `routes.rb`:

``` ruby
get "(/optional/:optional_id)/things" => "foo#foo", as: :things
```

3. Open `rails console`
4. call `app.things_path(optional_id: false)`

### Expected behavior

```
=> /things
```

### Actual behavior

```
=> /things?optional_id=false
```

The behavior is pretty inconsistent with:

```
app.things_path(optional_id: '')  # => "/things"
app.things_path(optional_id: nil) # => "/things"
```

Originally found through:  https://github.com/railsware/js-routes/issues/274

### System configuration

**Rails version**: 6.0.3.7

**Ruby version**: 2.6.3

**Comment by Tonkpils** [comment]
🙇  Thanks for the report @bogdan! Would you mind creating a reproduction script following the guide here https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case? This will help us in debugging and fixing the issue. 

[ActionPack Test Script](https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller_gem.rb)

**Comment by bogdan** [comment]
@Tonkpils https://gist.github.com/935fc4dbd6ba723cf3e8a6d3ede56106

**Comment by bogdan** [comment]
Just for my information: will there be a backport to 6-1-stable?

**Comment by eileencodes** [comment]
Confirmed it's broken in 6.1 and backported in d83a3189d5248479bbf8f123ff8dd0c770e38421
