### ISSUE TITLE
`acts_like?` doesn't check if the object actually acts that way (alternate title: Rubber Ducks Don't Quack)

### ISSUE THREAD

**Issue by mvastola** [rails/rails#42292]
### Summary
So I followed the template, but it's probably overkill given the issue (though I like the subtitle it allowed me to give this issue :smile:)..

The [`Object#acts_like?`](https://github.com/rails/rails/blob/328113b0adfb516639ea0ad9845e15877b8c8141/activesupport/lib/active_support/core_ext/object/acts_like.rb#L9-L20) core extension is defined as:
```ruby
def acts_like?(duck)
  case duck
  when :time
    respond_to? :acts_like_time?
  when :date
    respond_to? :acts_like_date?
  when :string
    respond_to? :acts_like_string?
  else
    respond_to? :"acts_like_#{duck}?"
  end
end
```

Obviously, while `#acts_like?` checks to ensure the duck type method exists, it never invokes it. 

This creates an antipattern wherein a developer overriding `#acts_like_duck?` to return false (for example if it's set in a superclass or an included module/concern) will see completely divergent results from `#acts_like_duck?` and `#acts_like?(:duck)`. 

Since -- as long as the method exists at all -- `#acts_like?(:duck)` will always return true, the way to get the desired behavior is to -- rather than overriding the `#acts_like_duck?` method to return a falsy value -- instead undefine the method.

Furthermore, the documentation of the method is partially misleading in that it can easily 

### Steps to reproduce
<details><summary>Run this ruby script</summary>

```ruby
#!/usr/bin/env ruby
require 'bundler/inline'
gemfile do
  gem 'activesupport',
      git: 'https://github.com/rails/rails',
      require: %w[active_support/core_ext/object/acts_like
                  active_support/core_ext/module/remove_method]
end

class Duck
  def acts_like_duck?
    true
  end
end

class RubberDuck < Duck
  def acts_like_duck?
    false
  end
end

def debug(code)
  prefixed_print = ->(text, prefix: '> ') do
    text.strip.split(/[\r\n]+/).each do |line|
      puts "#{prefix}#{line.strip}"
    end
  end

  prefixed_print[code]
  output = begin
    eval(code).inspect
  rescue Exception => ex
    ex.original_message
  end
  prefixed_print[output, prefix: '  => ']
  puts
end

puts '## Correct:'
debug %{Duck.new.acts_like_duck?}
debug %{Duck.new.acts_like?(:duck)}
debug %{RubberDuck.new.acts_like_duck?}

puts '## Incorrect/Confusing/Unintuitive:'
debug %{RubberDuck.new.acts_like?(:duck)}

puts '## Also:'
debug %{RubberDuck.remove_possible_method :acts_like_duck?}
debug %{RubberDuck.new.acts_like?(:duck)}
debug %{RubberDuck.new.acts_like_duck?}

```

</details>

### Actual behavior
Output is:

```ruby
## Correct:
> Duck.new.acts_like_duck?
  => true

> Duck.new.acts_like?(:duck)
  => true

> RubberDuck.new.acts_like_duck?
  => false

## Incorrect/Confusing/Unintuitive:
> RubberDuck.new.acts_like?(:duck)
  => true

## Also:
> RubberDuck.remove_possible_method :acts_like_duck?
  => RubberDuck

> RubberDuck.new.acts_like?(:duck)
  => false

> RubberDuck.new.acts_like_duck?
  => undefined method `acts_like_duck?' for #<RubberDuck:0x000055d6eeb46110>
```
### Expected behavior
Result of `RubberDuck.new.acts_like?(:duck)` should be `false`.

### System configuration
**Rails version**: `main` [branch](https://github.com/rails/rails/tree/main) (current `HEAD`: 328113b)

**Ruby version**: `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]`

**Comment by zzak** [comment]
🦆

**Comment by eugeneius** [comment]
The current behaviour is specifically documented in the Active Support Core Extensions guide:

https://guides.rubyonrails.org/active_support_core_extensions.html#acts-like-questionmark-duck

> The method `acts_like?` provides a way to check whether some class acts like some other class based on a simple convention: a class that provides the same interface as `String` defines
>
> ```ruby
> def acts_like_string?
> end
> ```
>
> **which is only a marker, its body or return value are irrelevant**. Then, client code can query for duck-type-safeness this way:
>
> ```ruby
> some_klass.acts_like?(:string)
> ```
>
> Rails has classes that act like `Date` or `Time` and follow this contract.

Given that a method with an empty body returns nil, making `acts_like?` check the return value would likely break a lot of existing code. I don't think it's worth doing this if the feature is working as designed, and the only problem is that it's deemed unintuitive.

**Comment by mvastola** [comment]
Ok, but it's not clear in the rdoc documentation. And this can be deprecated first and then removed in a later version.

I said unintuitive but afterwards I realized I was being overly generous. It's a bug if you can check the value through two different interfaces and get different results. Removing the method is just a workaround, and workarounds by definition are always unintuitive.

One of the draws of ruby/rails is how intuitive it is. 
I can't really think of anything else that seems so simple and yet is so not straightforward.

**Comment by mvastola** [comment]
Yup. Still there.

**Comment by mvastola** [comment]
Just noticed @rails-bot still has this closed. Anyone home, @rails-bot?

cc @zzak
