### ISSUE TITLE
`initialize!` raises `FrozenError` when called more than once from an app using `zeitwerk`

### ISSUE THREAD

**Issue by modosc** [rails/rails#42319]
### Steps to reproduce
initialize a rails app twice:
```ruby
  require "action_controller/railtie"
  class App < Rails::Application; end

  a = App.new
  a.initialize!
  
  b = App.new
  b.initialize!
```
### Expected behavior
no errors should be raised - this is the case on `6.0.3.7` and `6.1.3.2` with default configs

### Actual behavior
on `main` i get this error:
```
Traceback (most recent call last):
	22: from ./bug.rb:8:in `<main>'
	21: from /Users/jon/.rvm/gems/ruby-2.7.3/bundler/gems/rails-b678667853b4/railties/lib/rails/application.rb:389:in `initialize!'
	20: from /Users/jon/.rvm/gems/ruby-2.7.3/bundler/gems/rails-b678667853b4/railties/lib/rails/initializable.rb:60:in `run_initializers'
	19: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	18: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	17: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	16: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:347:in `call'
	15: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:347:in `each'
	14: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	13: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	12: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:415:in `call'
	11: from /Users/jon/.rvm/gems/ruby-2.7.3/bundler/gems/rails-b678667853b4/railties/lib/rails/initializable.rb:50:in `tsort_each_child'
	10: from /Users/jon/.rvm/gems/ruby-2.7.3/bundler/gems/rails-b678667853b4/railties/lib/rails/initializable.rb:50:in `each'
	 9: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	 8: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 7: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	 6: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 5: from /Users/jon/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	 4: from /Users/jon/.rvm/gems/ruby-2.7.3/bundler/gems/rails-b678667853b4/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
	 3: from /Users/jon/.rvm/gems/ruby-2.7.3/bundler/gems/rails-b678667853b4/railties/lib/rails/initializable.rb:32:in `run'
	 2: from /Users/jon/.rvm/gems/ruby-2.7.3/bundler/gems/rails-b678667853b4/railties/lib/rails/initializable.rb:32:in `instance_exec'
	 1: from /Users/jon/.rvm/gems/ruby-2.7.3/bundler/gems/rails-b678667853b4/railties/lib/rails/engine.rb:588:in `block in <class:Engine>'
/Users/jon/.rvm/gems/ruby-2.7.3/bundler/gems/rails-b678667853b4/railties/lib/rails/engine.rb:588:in `unshift'
FrozenError (can't modify frozen Array: [])
```
i also found the same behavior when instantiating and initializing instances of two different classes. 

a bisect gave me https://github.com/rails/rails/commit/0d523d83657ce7066f25d87f6f094e804590e1e8 as the first bad commit which is where `zeitwerk` becomes the default autoloader.

i found that in `6.1.3.2`  i could get a similar error by enabling `zeitwerk`
```ruby
  require "action_controller/railtie"
  class App < Rails::Application; end
  App.config.autoloader = :zeitwerk

  a = App.new
  a.config.autoloader = :zeitwerk
  a.initialize!
  
  b = App.new
  b.config.autoloader = :zeitwerk
  b.initialize!
```

### System configuration
**Rails version**:
https://github.com/rails/rails/commit/b678667853b48751ea6134f1f8ba3d687c943889
`6.1.3.2`
`6.0.3.7`

**Ruby version**:
`ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin20]`

**Comment by zzak** [comment]
@modosc I think this is a question to ask [zeitwerk](https://github.com/fxn/zeitwerk) 🤔 but I will leave this open for a while if anyone else has ideas.

**Comment by modosc** [comment]
@zzak i opened this here because multiple app support [is in the api docs](https://api.rubyonrails.org/classes/Rails/Application.html#class-Rails::Application-label-Multiple+Applications) - that example will fail if you call `initialize!` on both apps. 

that being said, if this is specific to `zeitwerk` i'm happy to move it. @fxn what are your thoughts here?

also fwiw my usage case is not hypothetical, it's for testing a [rails/rack middleware](https://github.com/modosc/cloudflare-rails/blob/master/spec/cloudflare/rails_spec.rb#L12). if there's another way to do so (or to reset an existing loader instance) without hitting this bug i'd be satisfied but so far all my attempts have failed.

**Comment by zzak** [comment]
I just spent some time looking into this afaict there is no way to "reload" once the app is initialized -- but you can create a new app using the same config and that _should_ work. I'm not entirely sure though, so let's wait to see what Xavier says. 🙏

**Comment by modosc** [comment]
>  but you can create a new app using the same config and that should work.

if i'm understanding you correctly, i tried that also and it didn't work:
```ruby
require "action_controller/railtie"

class App < Rails::Application; end
class OtherApp < Rails::Application; end

a = App.new.tap(&:initialize!)

# no config, fails
b = OtherApp.new.tap(&:initialize!)

# or with the same config, also fails
b = OtherApp.new(config: a.config).tap(&:initialize!)
```

**Comment by fxn** [comment]
I remember we discussed this in core when doing the integration, and the consensus was that right now we do not support several application instances. `Rails.application` is a singleton.

@rafaelfranca do you remember? Should we correct that documentation?

**Comment by modosc** [comment]
any idea why [this spec](https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/activemodel/test/cases/railtie_test.rb) works even with this change? this is exactly what i'm trying to do.

**Comment by rafaelfranca** [comment]
> @rafaelfranca do you remember? Should we correct that documentation?

There was some work in the past to make multiple applications possible, but the place we are right now it is not possible since the work was never finished. Since we have no plans to finish I think we should remove the documentation.

**Comment by ghiculescu** [comment]
> Since we have no plans to finish I think we should remove the documentation.

made a PR to remove the relevant section from the docs: https://github.com/rails/rails/pull/42961

> also fwiw my usage case is not hypothetical, it's for testing a [rails/rack middleware](https://github.com/modosc/cloudflare-rails/blob/master/spec/cloudflare/rails_spec.rb#L12). if there's another way to do so (or to reset an existing loader instance) without hitting this bug i'd be satisfied but so far all my attempts have failed.

can you use `ActiveSupport::Testing::Isolation` in your gem?

**Comment by modosc** [comment]
ah, a much easier solution was linked. this works for my usage case, thanks @st0012 

https://github.com/getsentry/sentry-ruby/commit/e21fac946b3d2d03ff11aae86a98a49f42054df9#diff-18f3f95d0126b5b677a9472bd8f57b4123fdfbb3412f5762ebf1d5667ad67b7bR91-R95

**Comment by st0012** [comment]
@modosc haha, thanks for creating the issue too. great cooperation I guess 🤝
