### ISSUE TITLE
Undefined, but obvious, where in a join produces unexpected result instead error

### ISSUE THREAD

**Issue by arivero** [rails/rails#42313]
It is not really a bug because the way to access a joined table is to fully specify the match, ie
`.where( solution: {id: s.id})` instead of `.where(solutions: s)`

but selection via id generates a lot of errors when `s` happens to be a `nil`, so it would be nice if
either` .where(solutions:s) `or` .where(solutions: [s1,s2,s3])` were implemented

```

### Steps to reproduce
class Solution < ApplicationRecord
   belongs_to :project
end
class Project < ApplicationRecord
   has_many :solutions
end
...
Project.joins(:solutions).where(solutions: s).explain

```
### Expected behavior
Either:
- emit an error "_column does not exist_" because solutions is not a field of Project
or
- Match against the Solution "s"
`SELECT "projects".* FROM "projects" INNER JOIN "solutions" ON "solutions"."project_id" = "projects"."id" WHERE "solutions"."id" = $1  `

### Actual behavior

We get a collection consisting of so many copies of s.project as the number of siblings of s.

`SELECT "projects".* FROM "projects" INNER JOIN "solutions" ON "solutions"."project_id" = "projects"."id" WHERE "projects"."id" = $(s.project_id)`

### System configuration
**Rails version**: 6.0.3.7
**Ruby version**: 2.6.5

**Comment by lfalcao** [comment]
hi @arivero, I think this can confuse more than help. Just use `where(solutions: { id: s })`. What you can do to is write a scope that checks the value before executing the query for example.

`scope :find_solutions, ->(id) { joins(:solution).where(solutions: { id: attr }) unless id.nil? }`

Then call it:  `Project.find_solutions(variable)`

**Comment by arivero** [comment]
> hi @arivero, I think this can confuse more than help. 

I trend to agree, it seems obvious to me but it can confuse others, 

So the only non confusing "expected behaviour" is that rails should emit a "column does not exist" error.

**Comment by zzak** [comment]
@arivero sounds like you found a solution, so I'm going to close this :bow:

Feel free to re-open if you have other questions or concerns
