### ISSUE TITLE
Copying ActionText associations between models creates an extra "trix-content" wrapper div

### ISSUE THREAD

**Issue by swanson** [rails/rails#42315]
### Steps to reproduce

Here is a one-file app with a failing test:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Activate the gem you are reporting the issue against.
  gem "rails", "6.1.3.2"
  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "action_text/engine"
require "tmpdir"

require "minitest/autorun"

class TestApp < Rails::Application
  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :action_text_rich_texts do |t|
    t.string     :name, null: false
    t.text       :body, size: :long
    t.references :record, null: false, polymorphic: true, index: false
    t.timestamps
    t.index [ :record_type, :record_id, :name ], name: "index_action_text_rich_texts_uniqueness", unique: true
  end

  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  has_rich_text :title
end

class BugTest < Minitest::Test
  def test_action_text_extra_wrapper_bug
    post = Post.create!(title: "<b>Hello!</b>")
    another_post = Post.create!(title: post.title)

    assert_equal post.title.body.to_html, another_post.title.body.to_html
  end
end
```

Observe the failing test:

```diff
Failure:
BugTest#test_action_text_extra_wrapper_bug [bug.rb:57]:
--- expected
+++ actual
@@ -1 +1,3 @@
-"<b>Hello!</b>"
+"<div class=\"trix-content\">
+  <b>Hello!</b>
+</div>"
```

### Expected behavior

Copying rich-text associations from one model to another should produce identical HTML when saved to the database.

### Actual behavior

An extra `<div class='trix-content'>` wrapper is added to the HTML that is stored in the ActionText table. This leads to potential display issues, as well as extra newlines/whitespace when calling `to_plain_text`.

### Work-around

I am currently working around this by calling `body.dup` on the rich-text association:

```ruby
post = Post.create!(title: "<b>Hello!</b>")
another_post = Post.create!(title: post.title.body.dup)
```

The cause seems to be an implicit `to_s` call that cause ActionText to apply the wrapper div. It's unexpected that you can't copy rich-text in this way, as other model attributes and associations can be copied without special handling.

Perhaps Rails could check if you are assigning an `ActionText::RichText` object and call `to_html` instead of `to_s`.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 3

**Comment by zzak** [comment]
@swanson I think this is [intentional](https://github.com/rails/rails/blob/main/actiontext/app/helpers/action_text/tag_helper.rb#L14) (see [here](https://github.com/rails/rails/blob/main/actiontext/app/views/layouts/action_text/contents/_content.html.erb) too). 

Also this seems to be addressed (documentation-size) in #41889.

**Comment by swanson** [comment]
> @swanson I think this is [intentional](https://github.com/rails/rails/blob/main/actiontext/app/helpers/action_text/tag_helper.rb#L14) (see [here](https://github.com/rails/rails/blob/main/actiontext/app/views/layouts/action_text/contents/_content.html.erb) too).
> 
> Also this seems to be addressed (documentation-size) in #41889.

My understanding is that it is intentional (and a nice feature) that the `trix-content` class is added when rendering. But in this case, that extra wrapper div is getting saved in the ActionText database table so you end up with double wrappers.

```html
<div class="trix-content"> <!-- added by tag_helper -->
  <div class="trix-content"> <!-- extraneous div caused by the behavior I'm reporting -->
   <b>Hello!</b>
  </div>
</div>
```

**Comment by zzak** [comment]
Ahh, ok I think I get what you're saying now, thanks for your explanation!

I'm curious what type of object `post.title` is.. but I could also investigate this myself 🤔

**Comment by swanson** [comment]
@zzak could this be re-opened? I don't think the linked PR addresses this bug.

The `post.title` is an `ActionText::RichText` object.

**Comment by zzak** [comment]
@swanson Good call, I'm not sure how this got closed 🤔 

I'm not sure but it sounds like maybe `ActionText::RichText.to_s` might be at fault here.. Let's experiment with than and see what we can find :bow:

**Comment by swanson** [comment]
ActionText defines this setter:

```ruby
def #{name}=(body)            
  self.#{name}.body = body          
end
```
https://github.com/rails/rails/blob/main/actiontext/lib/action_text/attribute.rb#L42-L45

Which eventually creates a `Fragment` with `from_html`: https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/actiontext/lib/action_text/fragment.rb#L17-L19

The `to_s` call there on `ActionText::RichText` adds the wrapper div. So perhaps `Fragment` can have additional handling for wrapping `ActionText::RichText` -- there is already some structure there for different handling based on different input classes.

**Comment by swanson** [comment]
Still an issue, same reproduction steps apply.

**Comment by alexandreruban** [comment]
I'd be happy to work on this issue if that's OK with you!

**Comment by alexandreruban** [comment]
@swanson I made a PR that should fix your issue! 
@zzak please tell me if it's OK with you so I can squash my commits!
