### ISSUE TITLE
Requesting s390x support in BuildKite CI for Rails

### ISSUE THREAD

**Issue by skribm9** [rails/rails#42330]
This feature request is not related to a problem.

We are looking to add s390x support to the existing BuildKite CI to allow testing of the latest build on s390x(IBM Z) architecture.
It seems that Ruby docker image being used in BuildKite CI already supports IBM Z.

Will be glad to discuss and provide any assistance required for this enablement. Hardware/VM access can be also provided if needed. Can you provide some pointers to proceed?

**Comment by zzak** [comment]
I actually have no idea how BuildKite works, but perhaps @matthewd knows. 🙏 

In general, I think we do not accept feature requests in issues, so it's better to open a PR and discuss your needs from there. However, since I don't know where the CI configuration is I will leave this open and hopefully someone can point us in the right direction :bow:

**Comment by lfalcao** [comment]
> However, since I don't know where the CI configuration

Related https://github.com/rails/rails/issues/39015

**Comment by skribm9** [comment]
Thanks @zzak and @lfalcao. 
I tried to find out the changes required but it would be great if @matthewd can also give some pointers. I will then raise a PR as you suggested.

**Comment by matthewd** [comment]
As we're pure ruby, we don't expect to need to test on multiple architectures -- as long as the language runtime and any compiled gems work correctly/consistently, we shouldn't see any architecture-induced variations. And, by extension, any such failure that did occur would be beyond our control. 

(The Buildkite CI configuration is in https://github.com/rails/buildkite-config, for anyone wondering. I originally did that to support builds of older branches, but then have never ended up adding a `.buildkite/` to the main repo.)

**Comment by zzak** [comment]
@skribm9 I believe we have our answer, and, correct me if I'm wrong but it seems there is no need to worry about supporting `s390x` for Rails.

That said, I know [ruby](https://bugs.ruby-lang.org/issues/16360) has been working on this using Travis-CI if you're interested.

Giving this a close as there seems to be nothing actionable on our side. 🙏
