### ISSUE TITLE
ActiveSupport::Duration#iso8601 can produce unparsable values

### ISSUE THREAD

**Issue by irminsul** [rails/rails#42344]
### Steps to reproduce

```ruby
# OK
999_999.seconds.iso8601 # => "PT999999S"
ActiveSupport::Duration.parse("PT999999S") # => 999999 seconds

# Fails
1_000_000.seconds.iso8601 # => "PT1e+06S"
ActiveSupport::Duration.parse("PT1e+06S") # => ActiveSupport::Duration::ISO8601Parser::ParsingError: Invalid ISO 8601 duration: "PT1e+06S"
```

### Expected behavior

Values of one million seconds and above should not be represented in scientific notation.

### Actual behavior

Values of one million seconds and above are represented in scientific notation, and cannot be parsed by `ActiveSupport::Duration.parse`.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.7.3

**Comment by HParker** [comment]
It does look like the behaves strangely.

You can work around this by passing `precision` to `iso8601`

```ruby 
d = 1_000_000.seconds.iso8601(precision: 1)
ActiveSupport::Duration.parse(d) # => 1000000.0 seconds
```
