### ISSUE TITLE
ActiveSupport Time.zone.parse unexpected behavior

### ISSUE THREAD

**Issue by Ar2emis** [rails/rails#42354]
I was trying to fix phantom test falling and found interesting behavior. Why is it so?

### Steps to reproduce
![Screenshot from 2021-06-02 09-57-02](https://user-images.githubusercontent.com/44751949/120438309-dff14900-c389-11eb-8ea2-986ea65d68d6.png)

```ruby
Time.zone.parse('sunt')
```

### Expected behavior
Expect to return nil

### Actual behavior
Returns current date

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.7.2

**Comment by zzak** [comment]
@Ar2emis This is intended behavior, while in Ruby `Time.parse('foobar')` will raise an ArgumentError this might be surprising in that regard.

Looking at the [docs](https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html#method-i-parse):

> If upper components are missing from the string, they are supplied from TimeZone#now:

Which just returns the current time in the default time zone (UTC).

This matches the behavior you're experiencing. :thinking:

All of that said, perhaps `parse` should be louder about raising an exception if it's unable to parse the supplied string. 🤔

**Comment by Ar2emis** [comment]
> @Ar2emis This is intended behavior, while in Ruby `Time.parse('foobar')` will raise an ArgumentError this might be surprising in that regard.
> 
> Looking at the [docs](https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html#method-i-parse):
> 
> > If upper components are missing from the string, they are supplied from TimeZone#now:
> 
> Which just returns the current time in the default time zone (UTC).
> 
> This matches the behavior you're experiencing. 🤔
> 
> All of that said, perhaps `parse` should be louder about raising an exception if it's unable to parse the supplied string. 🤔

I am using FFaker::Lorem.word to trigger validation. As I know `Time.zone.parse('some string')` returns `nil`. But only for that word I am getting current date

**Comment by zzak** [comment]
TIL: "sunt" is apparently Latin which explains why its coming out of the `Lorem` gem. But also its close enough to "sunday" that it actually parses.

You can find other similar behaviors typing "mon" or "mont" or "tue" (but not "tu").

I have no idea what defines this behavior yet but I'm guessing it will be rather difficult to change 🤔

**Comment by Ar2emis** [comment]
> TIL: "sunt" is apparently Latin which explains why its coming out of the `Lorem` gem. But also its close enough to "sunday" that it actually parses.
> 
> You can find other similar behaviors typing "mon" or "mont" or "tue" (but not "tu").
> 
> I have no idea what defines this behavior yet but I'm guessing it will be rather difficult to change 🤔

Thanks, It's enough to me to understand why this happens)

**Comment by pixeltrix** [comment]
Ruby's time and date parsing is a bit weird - this quirk is often referred to as '23 dogs' day:

https://twitter.com/tomstuart/status/668795250190757888
