### ISSUE TITLE
GeoIP Lite Country url in localization guide gives 404

### ISSUE THREAD

**Issue by FlorisXll** [rails/rails#42386]
### Steps to reproduce
Go to the [localization by ip guide section](https://guides.rubyonrails.org/i18n.html#inferring-the-locale-from-ip-geolocation) and follow the GeoIP Lite Country link.

### Expected behavior

Opens a GeoIP Lite Country page with a 200 status code.

### Actual behavior

Returns a page with a 404 status code.

**Comment by hahmed** [comment]
Thanks for reporting the issue @FlorisXll

We can update the docs to point to the right link, maybe https://dev.maxmind.com/geoip/geolite2-free-geolocation-data ?

Do you want to open a PR to address the doc updates?

**Comment by hahmed** [comment]
Here is the PR where it's been updated https://github.com/rails/rails/pull/42372

**Comment by FlorisXll** [comment]
Alright, let's close the issue then.
