### ISSUE TITLE
this place needs i18n

### ISSUE THREAD

**Issue by daihm-1041** [rails/rails#42382]
https://github.com/rails/rails/blob/cb0a558f42fc6957fac4d2daa16771b72ff7da6e/activerecord/lib/active_record/enum.rb#L140

**Comment by byroot** [comment]
Would you mind giving more context? I don't see how this error could possibly be shown to the end user.

**Comment by daihm-1041** [comment]
enum status: { reject: 0, approved: 1 }
when update status: 9999, validate false -> show errors "9999 is not a valid status", 
I want to use the translation for this place?
so I have to overwrite this place and add I18n

**Comment by byroot** [comment]
`"9999 is not a valid status"` is an exception, not a validation error, so it shouldn't be shown to the user. 

So I don't know what you are doing, but based on the information you provided it looks like a bug in your app, not in Rails.

**Comment by kamipo** [comment]
Probably it is a same issue with #13971.

Currently there is no official way to translate the invalid enum error to validation error, for now people overrides the enum attribute for the purpose described at #41730.

**Comment by daihm-1041** [comment]
sorry i'm wrong, not a validation error, I just want to add translate for this exception message

**Comment by daihm-1041** [comment]
Please tell me how to get model name in Module Enum.

**Comment by byroot** [comment]
> I just want to add translate for this exception message

We don't translate exception messages.

**Comment by HParker** [comment]
Thanks for the issue @daihm-1041!

It seems clear this is not a rails bug. I'll go ahead and close this, but if you have more questions or want to make a feature request, feel free to head over the the forums or stackoverflow. If you think this is incorrect or have a different issue feel free to open another issue.

PS
I like @kamipo's idea to make converting these into validation errors easier is great and should help with issues like this. 😄
