### ISSUE TITLE
PG::UndefinedTable running migrations for namespaced models with references

### ISSUE THREAD

**Issue by dmolesUC** [rails/rails#42380]
### Steps to reproduce

1. Create a new Rails application, e.g. `rails new pgns`.
2. Modify `database.yml` to connect to a Postgres database.
3. Generate two namespaced models, `Foo::Bar` and `Foo::Baz`, with `Baz` referencing `Foo`, as follows:

   ```none
   $ rails generate model Foo::Bar
         invoke  active_record
         create    db/migrate/20210603203750_create_foo_bars.rb
         create    app/models/foo/bar.rb
         create    app/models/foo.rb
   $ rails generate model Foo::Baz bar:references
         invoke  active_record
         create    db/migrate/20210603203914_create_foo_bazs.rb
         create    app/models/foo/baz.rb
      identical    app/models/foo.rb
   ```

4. Invoke `rails db:create`.
5. Invoke `rails db:migrate`.

### Expected behavior

- Migrations succeed for both models.

### Actual behavior

1. first migration (`CreateFooBars`) succeeds.

    ```none
    == 20210603203750 CreateFooBars: migrating ====================================
    -- create_table(:foo_bars)
       -> 0.0063s
    == 20210603203750 CreateFooBars: migrated (0.0064s) ===========================
    ```

2. second migration (`CreateFooBazs`) fails with `PG::UndefinedTable: ERROR:  relation "bars" does not exist`:

    ```none
    == 20210603203914 CreateFooBazs: migrating ====================================
    -- create_table(:foo_bazs)
    rails aborted!
    StandardError: An error has occurred, this and all later migrations canceled:
    
    PG::UndefinedTable: ERROR:  relation "bars" does not exist
    /Users/david/Work/Scratch/pgns/db/migrate/20210603203914_create_foo_bazs.rb:3:in `change'
    
    Caused by:
    ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "bars" does not exist
    /Users/david/Work/Scratch/pgns/db/migrate/20210603203914_create_foo_bazs.rb:3:in `change'
    
    Caused by:
    PG::UndefinedTable: ERROR:  relation "bars" does not exist
    /Users/david/Work/Scratch/pgns/db/migrate/20210603203914_create_foo_bazs.rb:3:in `change'
    Tasks: TOP => db:migrate
    (See full trace by running task with --trace)
    ```

3. rerunning with `--trace` shows [this backtrace (gist)](https://gist.github.com/dmolesUC/7e17514339868fb06f4ac4d0400a1ce2).

### System configuration

- **Operating system**: macOS 10.15.7 Catalina
- **Rails version**: 6.1.3.2
- **Ruby version**: 3.0.1 (installed with RVM)
- **`pg` gem version**: 1.2.3
- **Postgres version**: 12.2 (running in Docker)

(Note: problem also exists with Rails 6.0.3.6, Ruby 2.7.2)

**Comment by dmolesUC** [comment]
A sample app demonstrating the problem is at [dmolesUC/rails-42380](https://github.com/dmolesUC/rails-42380).

**Comment by ghiculescu** [comment]
Where you did this:

```
rails generate model Foo::Baz bar:references
```

Does it generate a correct migration if you do this:

```
rails generate model Foo::Baz foo_bar:references
```

I don't know if we expect the generator to figure out that the reference is namespaced otherwise.

**Comment by abhaynikam** [comment]
@dmolesUC Like @ghiculescu mentioned in the above comment. Active Model generator doesn't lookup for namespace and would generate a migration file with the reference name received. 

The attributes passed to the generator are parsed here: https://github.com/rails/rails/blob/main/railties/lib/rails/generators/generated_attribute.rb#L36

**Comment by zzak** [comment]
Yeah, my guess is "_" is used for generating CamelCase and not `::` namespace resolution. _Maybe_ we could make it take a --namespace flag to use for lookup? 🤔
