### ISSUE TITLE
ActionMailer default values should not be evaluated when overridden

### ISSUE THREAD

**Issue by alexandreruban** [rails/rails#42415]
### Steps to reproduce
I opened a PR #41157 in January solving a small bug on ActionMailer default values that are evaluated even when they are overridden in the mailer instance method.

I never opened an issue because I could submit the PR directly. However it was marked as stale by rails-bot before someone could review it and I would love to solve this bug (the test is still failing today).

Here is the example: 

```rb
class LazyProcMailer < ActionMailer::Base
  default from: -> { flunk }, to: -> { flunk }

  def welcome
    mail from: "overridden-from@example.com", to: "overridden-to@example.com"
  end
end
```

### Expected behavior
Sending the welcome email should not fail because `from` and `to` default values are overridden in the `#welcome` method.

### Actual behavior
Sending the welcome email raises an error because the default `from` and `to` procs are evaluated even if they are overridden later on the `#welcome` method.

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 3.0.1

**Comment by p8** [comment]
hey @alexandreruban, I'll have look to see if I can find the problem.

**Comment by ghiculescu** [comment]
I think the fix in https://github.com/rails/rails/pull/41157 is fine @p8 - just needs to get merged.

**Comment by p8** [comment]
@ghiculescu, thanks :) I misread that.
