### ISSUE TITLE
Add Cache-Control: no-store by default to prevent bfcache

### ISSUE THREAD

**Issue by collimarco** [rails/rails#42436]
### Steps to reproduce

Currently this is the default Rails behavior:

```
cache-control: max-age=0, private, must-revalidate
```

However that allows the browser to cache stale responses that are used when you click the Back button.

For example:

1. You are on a page with a list of items
2. You click an item to open it
3. You click edit and you change the item name
4. After save, you are redirected to the show action
5. Now if you click the browser back button multiple times and you go back to step 1 you will notice that the name of the item in the list is wrong (it's the old name)

### Expected behavior

A user that uses the Back button goes back to previous URLs, but should see the current content (not the stale content). 

The correct behavior would be applied if we added `Cache-Control: no-store` to all responses (with the exclusion of the responses that use `fresh_when`).

See also: https://web.dev/bfcache/#ways-to-opt-out-of-bfcache

### Actual behavior

A user that uses the Back button may see stale content / wrong information that was restored from the browser back/forward cache (bfcache).

### System configuration

**Rails version**: all

**Comment by lfalcao** [comment]
Interesting find. Even though I agree with you, this change can cause so much impact in some applications. I think a better approach for this, if you really need it, would be to add something like `before_action { expires_now }` into application_controller.rb to change the default Cache-Control directive.

**Comment by zzak** [comment]
See: #40324

**Comment by collimarco** [comment]
@lfalcao `expires_now` adds `no-cache`, which does not work in this case.

We need `no-store`, like in the pull request linked by @zzak
