### ISSUE TITLE
Blank query can't be executed on a readonly database connection

### ISSUE THREAD

**Issue by dgageot** [rails/rails#42432]
Trying to execute a blank SQL query on a readonly (role: :reading) database connection always fails with this error:

```
ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode
```

### Steps to reproduce

```
ActiveRecord::Base.connected_to(role: :reading) { ActiveRecord::Base.connection.execute('').count }
ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode:
```

or if you deep dive into why Rails thinks the query can't run on a readonly database:

```
Class.new.extend(ActiveRecord::ConnectionAdapters::PostgreSQL::DatabaseStatements).write_query?('')
=> true
```

### Expected behaviour

The query should be allowed to execute on a readonly connection.
It would return an empty result like when it runs on a read/write connection:

```
ActiveRecord::Base.connection.execute('').count
=> 0
```

### Actual behaviour

```
ActiveRecord::Base.connected_to(role: :reading) { ActiveRecord::Base.connection.execute('').count }
ActiveRecord::ReadOnlyError: Write query attempted while in readonly mode:
```

### System configuration

**Rails version**: Rails 6.1.3.2
**Ruby version**: ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin20

**Comment by ghiculescu** [comment]
Thanks for the bug report - https://github.com/rails/rails/pull/42433 should fix this, can you please confirm.

**Comment by dgageot** [comment]
Thanks @ghiculescu for the super fast fix. 

Actually, I forgot one **important** thing: the queries we send are not totally blank. They are suffixed with a comment added by [marginalia](https://github.com/basecamp/marginalia)

Something like:

```
' /*hostname:thehost,application:theapp,controller:index*/'
```

So `sql.blank?` will not be enough

**Comment by HParker** [comment]
Thanks @dgageot for the issue,

One thing that might help this issue is explaining why you want to run empty queries. I agree it isn't a write query and probably should error that way, but understanding why you want to run empty queries would be helpful for understanding what the best fix might be.

**Comment by dgageot** [comment]
Sure, we have a few cases where we don't query the database though `ActiveRecord`. Instead we use `ActiveRecord::Base.connection.execute(raw_query)` with a `raw_query` that's computed in a way we don't totally control. It turns out that we hit a bug when switch from `Standby` to rails built-in mechanism.

We tried to fix places where we generate empty queries. All the time, it can early return.
We couldn't fix them all and also we are afraid that future usage of `.execute` could happen with en empty query anyways.

It doesn't seem legit to assume empty queries are write queries since they are essentially no-op so, here am I, opening a ticket :-)

**Comment by ghiculescu** [comment]
That sounds like a bit of a scary use case, not relevant to this but would love to know how you are protecting against things like SQL injection. 

> It doesn't seem legit to assume empty queries are write queries since they are essentially no-op so, here I am, opening a ticket :-)

Agree! Thanks for raising it.

**Comment by bpaquet** [comment]
(I'm working with @dgageot)

We have other cases for which ActiveRecord generates an empty query

```
MyModel.my_scope(list_of_ids).to_sql
```

If `list_of_ids` is empty (which can happen in some use cases), the generated query is `''`

May be our scope is not well written :)

**Comment by ghiculescu** [comment]
@dgageot @bpaquet would https://github.com/rails/rails/pull/42450 resolve this issue? It looks more generally useful than https://github.com/rails/rails/pull/42433

**Comment by casperisfine** [comment]
> If `list_of_ids` is empty (which can happen in some use cases), the generated query is `''`

That is changed in 7.0: https://github.com/rails/rails/pull/42232.
