### ISSUE TITLE
ActiveStorage migration: NoMethodError: undefined method `attachment' 

### ISSUE THREAD

**Issue by jshumakerpruitt** [rails/rails#42434]
### Steps to reproduce
```sh
rails _5.2.6_ new StorageDemo --database=postgresql
cd StorageDemo/
bin/rails db:create
bin/rails active_storage:install
bin/rails db:migrate
bin/rails generate model User avatar:attachment
bin/rails db:migrate
```

### Expected behavior
Migrations with `t.attachment` work

### Actual behavior
```ruby
== 20210609160743 CreateUsers: migrating ======================================
-- create_table(:users)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `attachment' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x00007ff214ca61c0>
/Users/js/code/rails/StorageDemo/db/migrate/20210609160743_create_users.rb:4:in `block in change'
/Users/js/code/rails/StorageDemo/db/migrate/20210609160743_create_users.rb:3:in `change'
/Users/js/code/rails/StorageDemo/bin/rails:9:in `<top (required)>'
/Users/js/code/rails/StorageDemo/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
NoMethodError: undefined method `attachment' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x00007ff214ca61c0>
/Users/js/code/rails/StorageDemo/db/migrate/20210609160743_create_users.rb:4:in `block in change'
/Users/js/code/rails/StorageDemo/db/migrate/20210609160743_create_users.rb:3:in `change'
/Users/js/code/rails/StorageDemo/bin/rails:9:in `<top (required)>'
/Users/js/code/rails/StorageDemo/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```
### System configuration
**Rails version**:
5.2.6

**Ruby version**:
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin19]

**Comment by HParker** [comment]
Thanks for the issue @jshumakerpruitt!

I think it is clear the docs should be improved here

This is the same issue as: https://github.com/rails/rails/issues/42296 which updated the docs here: https://github.com/rails/rails/pull/42391 to make it clearer how to setup your model for active storage

Repeating the previous issue,
> Rails do not support setting Active Storage has_one_attached or has_many_attached in the migration.
- https://github.com/rails/rails/issues/42296#issuecomment-848890782


This is not a rails bug, but I'll leave it open as a docs issue since we have had multiple people run into this issue.

**Comment by SkipKayhil** [comment]
I believe this was added in ecdcf06cb2e19e4bd2d883fbf3908cf196cfc1a5, so this feature wouldn't be available in Rails 5.2. 

I'll make a PR to update the docs indicating that Rails 6.0 is required to use `:attachment` and `:attachments`

**Comment by jshumakerpruitt** [comment]
@SkipKayhil Thanks for that info.  What generator syntax or column type should I use in a 5.2 app?

**Comment by SkipKayhil** [comment]
> @SkipKayhil Thanks for that info. What generator syntax or column type should I use in a 5.2 app?

I believe the correct way would be to not specify the attachment in the generator, and to add `has_one_attached :avatar` to the model yourself

**Comment by jshumakerpruitt** [comment]
@SkipKayhil Thanks for the quick reply!  Feel free to close this issue
