### ISSUE TITLE
Configuring _fixture.class_name does not change the table_name for the fixture

### ISSUE THREAD

**Issue by mildred** [rails/rails#42441]
Here, the fixture is initialized, and the table name is set according to the class name:

https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/activerecord/lib/active_record/fixtures.rb#L654-L664

However, the class name is determined from the fixture file name, and setting the `_fixture.class_name` in the fixture itsenf does not change it.

It would be nice to be able to configure the table name and the class independently

The use case I have is that I have a model that is backed by a read-only view, which is used for all querying, and a separate table that I use for write access. I need to read from the view but write to the separate table.

**Comment by ghiculescu** [comment]
> However, the class name is determined from the fixture file name, and setting the _fixture.class_name in the fixture itsenf does not change it.

This sounds like a bug, and it also sounds like the correct way to solve your use case I think.

Can you provide an replication example to show `_fixture.class_name` not working?

**Comment by pixeltrix** [comment]
Isn't it `model_class`, e.g:

``` yaml
_fixture:
  model_class: Person
andrew:
  name: Andrew
```

**Comment by casperisfine** [comment]
Hum, maybe we should raise some error for key that don't match anything?

**Comment by casperisfine** [comment]
I opened a PR: https://github.com/rails/rails/pull/42490, please let me know if it makes sense to you.
