### ISSUE TITLE
Inaccurate active_record_callbacks documentation

### ISSUE THREAD

**Issue by Wittiest** [rails/rails#42457]
### Context
I'm opening an issue for a discussion on this since I cannot tell if the documentation is wrong or if Rails unintentionally allows us to operate differently than the documentation

### Steps to reproduce
- Read https://github.com/rails/rails/blob/main/guides/source/active_record_callbacks.md
- Find statement and example of: "Using both after_create_commit and after_update_commit in the same model will only allow the last callback defined to take effect, and will override all others."

### Expected behavior
The docs should reflect the reality of:
- `after_create_commit` and `after_update_commit` can both exist in a model and will only have "the last callback defined take effect" if they both give the same method symbol if using symbol notation
- If you pass a block, you can call the same method
- If you pass separate method symbols, both are called

##### Only calls on `after_update_commit`:
```
after_create_commit :method_invocation
after_update_commit :method_invocation
```

##### Calls on both:
```
after_create_commit { method_invocation }
after_update_commit { method_invocation }
```

```
after_create_commit :method_invocation
after_update_commit :method_invocation2
```

**Comment by HParker** [comment]
Thanks for the issue @Wittiest!

I am not able to reproduce the behavior you are describing with the reproduction script:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

$log_user_saved_to_db_calls = 0

class Post < ActiveRecord::Base
  has_many :comments
  after_create_commit { log_user_saved_to_db }
  after_update_commit { log_user_saved_to_db_two }

  private
  def log_user_saved_to_db
    $log_user_saved_to_db_calls += 1
    puts '---------- User was saved to database ----------'
  end

  def log_user_saved_to_db_two
    $log_user_saved_to_db_calls += 1
    puts '---------- User was saved to database two ----------'
  end
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    assert_equal 1, $log_user_saved_to_db_calls
  end
end

```

This test passes as the `log_user_saved_to_db*` methods where only called once.

Would you help me update it to get the behavior you are seeing?

If you can also update your issue with rails version and ruby version that might be helpful in debugging this issue.

Thanks in advance!

**Comment by HParker** [comment]
Oh, I think I got it now, my test expectation should be:

```ruby
class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    assert_equal 1, $log_user_saved_to_db_calls

    comment = Comment.create!

    post = Post.update(comments: [comment])
    assert_equal 2, $log_user_saved_to_db_calls
  end
end
```

**Comment by Wittiest** [comment]
Please also note that your test passes in both of these cases as well

```
class Post < ActiveRecord::Base
  has_many :comments
  after_create_commit { log_user_saved_to_db }
  after_update_commit { log_user_saved_to_db }

  private
  def log_user_saved_to_db
    $log_user_saved_to_db_calls += 1
    puts '---------- User was saved to database ----------'
  end
end
```

```
class Post < ActiveRecord::Base
  has_many :comments
  after_create_commit :log_user_saved_to_db
  after_update_commit :log_user_saved_to_db2

  private
  def log_user_saved_to_db
    $log_user_saved_to_db_calls += 1
    puts '---------- User was saved to database 1 ----------'
  end

  def log_user_saved_to_db2
    $log_user_saved_to_db_calls += 1
    puts '---------- User was saved to database 2 ----------'
  end
end
```

The only failure case seems to actually be when the method call is exactly the same in symbol form:
```
class Post < ActiveRecord::Base
  has_many :comments
  after_create_commit :log_user_saved_to_db
  after_update_commit :log_user_saved_to_db

  private
  def log_user_saved_to_db
    $log_user_saved_to_db_calls += 1
    puts '---------- User was saved to database 1 ----------'
  end
end
```

**Comment by Wittiest** [comment]
Updated summary to detail the above ^

**Comment by HParker** [comment]
Updating the docs is a great idea. I am also really curious if it is possible to remove the warning and make `after_create_commit` and `after_update_commit` work like I expect with symbols.

**Comment by HParker** [comment]
Ah, good discussion here: https://github.com/rails/rails/issues/29554

**Comment by Wittiest** [comment]
@HParker It seems like if we modified the deduplication logic here to include `if` it would remove the need for all of this commentary in the documentation:
https://github.com/rails/rails/blob/main/activesupport/lib/active_support/callbacks.rb#L323

The reason this would avoid breaking the convention set in the other discussion is that this would really be a larger change to make `after_commit` only de-dup if the `if` array is also the same. Supposing `rails` is okay with that change, I'm guessing it would make sense to de-dup on `unless` as well.

This would be backwards incompatible, but I can't really imagine it causing bugs outside of extremely rare cases.
