### ISSUE TITLE
Fixtures with multiple records error out when table has an generated column

### ISSUE THREAD

**Issue by brettallred** [rails/rails#42469]
### Steps to reproduce

1. Create a fixture with only one record
2. Create a fixture with two or more records
3. Open up ```activerecord-6.1.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:47``` and log  the sql out to the console.
4. Run your tests

- On the fixture with only one record, the insert statement will only include the column names that were specified in the fixture.
- On the fixture with two or more items, all column names are included in the insert statement, rather than the column names specified.

The problem with this is if you have a generated column, it creates a situation where when you have one fixture item, it inserts into the database correctly, but when you have multiple items in your fixture, you get an error like

```ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  cannot insert into column```

This situation where 1 item in the list is handled differently that multiple items is explicitly handled here:

```activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:487```

### System configuration
**Rails version**:
6.1.3.2
**Ruby version**:
6.7.1

**Comment by ghiculescu** [comment]
Thanks for reporting this. Just to confirm the issue it would be great to see some example fixtures or a fresh rails app that replicates the bug.

**Comment by brettallred** [comment]
https://github.com/brettallred/rails_fixture_bug

**Comment by ghiculescu** [comment]
Yep, please do - that looks like a bug to me. The fact we have a special case if there's a [single fixture](https://github.com/rails/rails/blob/051b0fcd29e927ec8adf7ac11d3a469645e1d8d6/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L482) is concerning. It looks like https://github.com/rails/rails/commit/d8d6bd5e63a9a4a6c06a4dde3c7137ee2be105fd added it, that might give you some clues as to how to fix it.

**Comment by brettallred** [comment]
@ghiculescu - I have a fix for this.  I'll get a PR up soon. I've just been doing a bunch of local testing.

**Comment by luizkowalski** [comment]
Hey, just to weigh on this: I'm having the exact same issue. Brett, do you happen to have found a workaround in the meantime?

**Comment by fatkodima** [comment]
There was a bug (missing implementation, actually) in postgres - https://www.postgresql.org/message-id/CAJJLo9Wt2Xd06xeuiUH5YWg145Eu2iFAj1Q4YYsa-TO16RBsKQ%40mail.gmail.com

So if you are on newer postgres - this should work. Also, I verified - this is fixed in newer railses, as of https://github.com/rails/rails/pull/41856.
