### ISSUE TITLE
Active Support time zone offset

### ISSUE THREAD

**Issue by gahia** [rails/rails#42473]
ActiveSupport and TZInfo utc_offset return different values. TZinfo gives the correct current offset value (EDT UTC-4h) for today.

### Expected behavior

```ruby
#> Time.find_zone("America/New_York").utc_offset
=> -14400 # -04:00
#> Time.find_zone("America/New_York").tzinfo.utc_offset
=> -14400 # -04:00
```

### Actual behavior

```ruby
#> Time.find_zone("America/New_York").utc_offset
=> -18000 # -05:00
#> Time.find_zone("America/New_York").tzinfo.utc_offset
=> -14400 # -04:00
```

### System configuration
**Rails version**: 6.1.3.2
**Ruby version**: 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

**Comment by airled** [comment]
#42467 Related?

**Comment by gahia** [comment]
> #42467 Related?

I don't think so... it doesn't seems just a daylight savings difference there.

**Comment by gahia** [comment]
Find out that ActiveSupport::Timezone.utc_offset (1) comes form TZInfo::TimezonePeriod.utc_offset that says (2):

> Returns the base offset from UTC in seconds (observed_utc_offset - std_offset). This does not include any adjustment made for daylight savings time and will typically remain constant throughout the year.
> 
> To obtain the currently observed offset from UTC, including the effect of daylight savings time, use #observed_utc_offset instead.

I'm expecting to get the current offset because I'm creating a "custom" date in an specific timezone but got it wrong. It has not to be like I was expecting although I think it makes more sense to retrieve the current offset or at least document that ActiveSupport::Timezone.utc_offset retrieves the "base" offset... and maybe a new method to get the current one?

Well, I don't think this is a bug.

(1)https://github.com/rails/rails/blob/f626b47d56061fc414791217c7904a51df2de226/activesupport/lib/active_support/values/time_zone.rb#L285
(2) https://rubydoc.info/gems/tzinfo/TZInfo/TimezonePeriod#base_utc_offset-instance_method
