### ISSUE TITLE
ActiveStorage S3 doesn't generate custom domain URLs

### ISSUE THREAD

**Issue by josegomezr** [rails/rails#42488]
### Scenario

Your rails app is using ActiveStorage with S3 Driver. You followed [AWS guide for having custom domain for buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/website-hosting-custom-domain-walkthrough.html#root-domain-walkthrough-create-buckets) (it mandates that the bucket name has to be equal to the domain name). So instead of having:

```
https://<bucket_name>.s3.<region>.amazonaws.com/<key>
```

You want to generate
```
https://<bucket_name>/<key>
```

As the [aws-sdk-ruby](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#presigned_url-instance_method) already allows.

But it fails! You never see your shiny custom domain URL's when you call `ActiveStorage::Blob#url` and pass `virtual_host: true` as the `aws-sdk-ruby` specifies.

### Steps to reproduce

1. Enable ActiveStorage with S3
2. Upload a file
3. Open `rails console` and run:
```ruby
ActiveStorage::Blob.last.url(virtual_host: true)
```

### Expected behavior
The generated URL must match
```
https://<bucket_name>/<key>
```

### Actual behavior
The generated URL matches
```
https://<bucket_name>.s3.<region>.amazonaws.com/<key>
```

Regardless of the options passed to `ActiveStorage::Blob#url`

### System configuration
**Rails version**: `rails-6.1.3.2`

**Ruby version**: `ruby-2.5.0`

---

The S3Service swallows the extra options passed by `ActiveStorage::Blob` in `activestorage/lib/active_storage/service/s3_service.rb:99-107`:

https://github.com/rails/rails/blob/e5816783961b20daf6b391ef35ad1345396caf55/activestorage/lib/active_storage/service/s3_service.rb#L99-L107

A proposed solution would be:

```diff
- def private_url(key, expires_in:, filename:, disposition:, content_type:, **)
+ def private_url(key, expires_in:, filename:, disposition:, content_type:, virtual_host: nil, **)
  object_for(key).presigned_url :get, expires_in: expires_in.to_i,
    response_content_disposition: content_disposition_with(type: disposition, filename: filename),
-    response_content_type: content_type
+    response_content_type: content_type, virtual_host: virtual_host
end

def public_url(key, virtual_host: nil, **)
-  object_for(key).public_url
+  object_for(key).public_url(virtual_host: virtual_host)
end
```

So the `virtual_host` opt is passed to the S3 interface. I can volunteer to make the respective PR if required :blush:

**Comment by ghiculescu** [comment]
That solution looks good; maybe it's worth allowing you to pass any options you want through to the relevant S3 client methods.

A PR would be welcome.

**Comment by josegomezr** [comment]
I'll work on it, I like the idea of passing all remaining options to the S3 client! 🚀
