### ISSUE TITLE
Support to easily override `ActionDispatch::DebugExceptions` log format

### ISSUE THREAD

**Issue by tegon** [rails/rails#42493]
### Background

I recently upgraded an application to Rails 6, and after seeing `ActionDispatch::DebugExceptions` [interceptors](https://github.com/rails/rails/pull/23868) I thought that I could get rid of a monkey patch, but it wasn't possible in the end. That's what drove me to open this issue.

This was somewhat already discussed in https://github.com/rails/rails/pull/33609, and it was [pointed out](https://github.com/rails/rails/pull/33609#issuecomment-493970516) that the interceptors are not the right tool for the job. 
It was also mentioned that it's possible to [silence specific exceptions](https://github.com/rails/rails/pull/33609#issuecomment-515731007) by using the `silent_exceptions` config option.

### Actual behavior
Currently, the method `log_error` in `ActionDispatch::DebugExceptions` logs out a multiple line message, that may look good in a terminal, but in a logging management system - e.g. Datadog - looks like the following:

![Screen Shot 2021-06-14 at 12 20 14](https://user-images.githubusercontent.com/3727827/121948780-0e7a0700-cd2e-11eb-9478-b2b0d9a774da.png)

This adds unnecessary noise since there are four different lines for the same exception. The only way to get rid of this behavior right now is to monkey patch `ActionDispatch::DebugExceptions` and override the `log_format` method. 

### Goal
What I want to get is a good instrumentation by using structured logging for my application. One of the main goals is to have ["one log entry for each unit of work" or "one log entry for each request"](https://aws.amazon.com/builders-library/instrumenting-distributed-systems-for-operational-visibility/).

I'm opening this issue to see if there are any thoughts on how a custom log format could be provided to `ActionDispatch::DebugExceptions`.  I understand that aborting the interceptors is not the answer, and I think silencing the exceptions also isn't.

In my situation - and possibly @wjordan and @lucaong - we do want the exceptions to be reported (or logged in this case) but we would like to format the log message in a way that makes sense for the application. 

Right now, tools such as https://github.com/roidrage/lograge are able to provide a good log formatting option, but they fall off short for this situation. Maybe there is a better way of developing such tools (I don't have much knowledge about it), and if that's the case, let me know.

Logging out a single line would probably be enough for my use case, but I have the impression that the exception logging in this module is not something intended for production logging like we have been using it for. So I'm curious to hear what the maintainers think about this.

### System configuration
**Rails version**: 6.1.3.2
**Ruby version**: 2.5.8

**Comment by zzak** [comment]
Thanks for your well thought out message @tegon.

Unfortunately we do not accept feature requests in our bug tracker, instead we ask that you bring this to [rubyonrails-core discuss](https://discuss.rubyonrails.org/c/rubyonrails-core). :bow:
