### ISSUE TITLE
Error with Angular 11 server side rendering

### ISSUE THREAD

**Issue by vishalsingh123** [rails/rails#42508]
https://github.com/rails/rails/blob/1ec0f6a68382608565339e58727d0bfc8f1c0004/actioncable/app/assets/javascripts/action_cable.js#L5-L7

it is giving error in angular server side rendering 

/server/main.js:62858
    logger: self.console,
            ^
![Screenshot 2021-06-16 at 5 12 44 PM](https://user-images.githubusercontent.com/6927028/122213000-18367280-cec6-11eb-9e22-8f4bf8d7e298.png)
ReferenceError: self is not defined

**Comment by vishalsingh123** [comment]
fixed

**Comment by danthareja** [comment]
@vishalsingh123 - how did you fix this?
