### ISSUE TITLE
ActionDispatch::SystemTesting::Driver doesn't allow the use of more than one selenium-based driver

### ISSUE THREAD

**Issue by cjlarose** [rails/rails#42502]
### Steps to reproduce

I've got a [reproducible example in a separate repo](https://github.com/cjlarose/rails-issue-system-test-case-driver-name-conflict), but for brevity, the important part is this:

```ruby
class ChromeGUITest < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :chrome

  def test_stuff
    page.visit "/"
    assert_empty Capybara.current_session.driver.options[:options].args
  end
end

class ChromeHeadlessTest < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :headless_chrome

  def test_stuff
    page.visit "/"
    assert_includes Capybara.current_session.driver.options[:options].args, '--headless'
  end
end
```

### Expected behavior

I'd expect the tests in `ChromeGUITest` to execute using the Capybara driver that's configured to use Chrome with a GUI and for the tests in `ChromeHeadlessTest` to execute using the Capybara driver that's configured to use headless Chrome.

### Actual behavior

If the GUI test runs first, then both tests use a GUI. If the headless test runs first, then both tests use headless Chrome.

### System configuration

**Rails version**: main at 98d48cf3a269aaae53777a19fea0a9e3740a00c5

**Ruby version**: 2.7.2

### Additional info

The `@name` instance variable for `ActionDispatch::SystemTesting::Driver` is used both as the driver name when registering the driver with Capybara as well as for determining how to construct a Capybara Driver instance. I think conflating these two roles is the source of the problem.

https://github.com/rails/rails/blob/98d48cf3a269aaae53777a19fea0a9e3740a00c5/actionpack/lib/action_dispatch/system_testing/driver.rb#L33-L40

Of course, it's possible to give a different `name` to the `ActionDispatch::SystemTesting::Driver`, but then the code for actually constructing the driver instance in `register_selenium` isn't called. So a workaround is to create a custom Driver subclass and assign it manually

```ruby
class ChromeGUITest < ActionDispatch::SystemTestCase
  class ChromeGUIDriver < ActionDispatch::SystemTesting::Driver
    private

    def registerable?
      true
    end

    def register
      Capybara.register_driver @name do |app|
        register_selenium(app)
      end
    end
  end

  self.driver = ChromeGUIDriver.new :chrome_gui, using: :chrome
  
  ...
end
```

But that's a bit cumbersome.

I think one solution to this problem is to just dynamically construct the driver name given to `Capybara.register_driver` in such a way that it's guaranteed to be unique.

**Comment by rmacklin** [comment]
Similar issue: https://github.com/rails/rails/issues/32468
