### ISSUE TITLE
Creation of temporary table with `force: true` issues a non-temporary table drop when using the MySQL adapter

### ISSUE THREAD

**Issue by iridakos** [rails/rails#42525]
### Steps to reproduce
Create a vanilla Rails 6.1.3.2 application using the `mysql2` adapter and execute the following command inside a `rails console`:

```ruby
ActiveRecord::Base.connection.create_table(:foo, force: true, temporary: true) { |t| t.string :name }
```

### Expected behavior

The drop statement should include the `TEMPORARY` keyword.

```sql
DROP TEMPORARY TABLE IF EXISTS `foo`
CREATE TEMPORARY TABLE `foo` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255))
```

### Actual behavior

The drop statement does not include the `TEMPORARY` keyword.
```sql
DROP TABLE IF EXISTS `foo`
CREATE TEMPORARY TABLE `foo` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255))
```

### Investigation details

This bug was found due to the following error reported by a failing spec that was trying to create a temporary table with `force: true` in an rspec's `before` block.
```
ActiveRecord::StatementInvalid:
  Mysql2::Error: SAVEPOINT active_record_1 does not exist
```

From [ActiveRecord::Transactions documentation](https://api.rubyonrails.org/v6.1.3.2/classes/ActiveRecord/Transactions/ClassMethods.html#module-ActiveRecord::Transactions::ClassMethods-label-Caveats):
> If you're on MySQL, then do not use Data Definition Language (DDL) operations in nested transactions blocks that are emulated with savepoints. That is, do not execute statements like 'CREATE TABLE' inside such blocks. This is because MySQL automatically releases all savepoints upon executing a DDL operation. When transaction is finished and tries to release the savepoint it created earlier, a database error will occur because the savepoint has already been automatically released

The [drop operation for non-temporary tables commits the current transaction](https://mariadb.com/kb/en/drop-table/) in MariaDB:
> Note: DROP TABLE automatically commits the current active transaction, unless you use the TEMPORARY keyword.

The following part in version 6.1.3.2 of [ActiveRecord::ConnectionAdapters::SchemaStatements](https://github.com/rails/rails/blob/v6.1.3.2/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L316-L317)
```ruby
if force
  drop_table(table_name, force: force, if_exists: true)
else
  schema_cache.clear_data_source_cache!(table_name.to_s)
end
```
does not pass the `temporary` option in the `drop_table` call and thus the [ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter](https://github.com/rails/rails/blob/v6.1.3.2/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L334-L337)
```ruby
def drop_table(table_name, **options)
  schema_cache.clear_data_source_cache!(table_name.to_s)
  execute "DROP#{' TEMPORARY' if options[:temporary]} TABLE#{' IF EXISTS' if options[:if_exists]} #{quote_table_name(table_name)}#{' CASCADE' if options[:force] == :cascade}"
end
```
does not include the `TEMPORARY` keyword in the produced SQL.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.7.3

**Comment by ghiculescu** [comment]
Thanks for the bug report and the investigation. Would this be the fix:

```ruby
  drop_table(table_name, force: force, if_exists: true, temporary: options[:temporary])
```

?

Would you be interested in making a PR and adding a test?

**Comment by iridakos** [comment]
Hi @ghiculescu , yes, I think that's what's needed here.

> Would you be interested in making a PR and adding a test?

Of course, I will try to open it as soon as possible.
