### ISSUE TITLE
YAML aliases not working with psych 4

### ISSUE THREAD

**Issue by jacquesn** [rails/rails#42528]
Loading yaml files (e.g. database.yml) raises `Psych::BadAlias`. It seems `YAML.load` by default no longer allows aliases in new psych releases.

```
/psych-4.0.1/lib/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias': Cannot load database configuration: (Psych::BadAlias)
...
/activesupport-6.1.3.2/lib/active_support/configuration_file.rb:22:in `parse'
```

`ActiveSupport::ConfigurationFile#parse`:
```
def parse(context: nil, **options)
      YAML.load(render(context), **options) || {}
```

### Steps to reproduce
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'activesupport', '6.1.3.2'
  gem 'psych', '4.0.1'
end

require 'active_support'
require 'active_support/core_ext/object/blank'
require 'minitest/autorun'

class BugTest < Minitest::Test
  def test_stuff
    # No error:
    yaml_without_aliases = <<~YAML
      development:
        database: the_database
    YAML
    YAML.load(yaml_without_aliases)

    # Error:
    yaml_with_aliases = <<~YAML
      default: &default
        adapter: postgresql

      development:
        <<: *default
        database: the_database
    YAML
    assert_raises(Psych::BadAlias) { YAML.load(yaml_with_aliases) }

    # No error:
    YAML.load(yaml_with_aliases, aliases: true)
  end
end
```

### System configuration
**Rails version**:  6.1.3.2

**Ruby version**:  3.0.1

**Comment by yahonda** [comment]
Psych is 4 support for 6-1-stable branch has been backported at https://github.com/rails/rails/commit/255b5ff9af57f9b54dee7ec884b12a1ad16f0321 but not released yet. When Rails 6.1.4 is released this fix will be available, I do not know when it is released though.

Then the current workarounds are:

* Lock Psych version 3.
* Use `6-1-stable` branch as follows.
```ruby
gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'activesupport', github: 'rails/rails', branch: '6-1-stable'
  gem 'psych', '4.0.1'
end
```

**Comment by gurrenPizza** [comment]
> Psych is 4 support for 6-1-stable branch has been backported at [255b5ff](https://github.com/rails/rails/commit/255b5ff9af57f9b54dee7ec884b12a1ad16f0321) but not released yet. When Rails 6.1.4 is released this fix will be available, I do not know when it is released though.
> 
> Then the current workarounds are:
> 
>     * Lock Psych version 3.
> 
>     * Use `6-1-stable` branch as follows.

I was experiencing the error the OP mentioned when trying to run `rails generate`. Not even the --help option was working.

My environment was:

```
Ubuntu 22.04.3 LTS
Ruby v3.0.4
Rails 6.0.3.6
```

Specifying Psych to be version 3 in my Gemfile fixed the issue.

```yaml
gem  'psych', '3.0.2'
```

This seemed to be an uncommon error for this version as I mostly found things related to legacy rails 3 and 4 stuff when searching for it, so thanks for the solution, mr. @yahonda
