### ISSUE TITLE
`preload_link_tag` uses route path rather than assets pipeline path

### ISSUE THREAD

**Issue by romaricpascal** [rails/rails#42545]
### Steps to reproduce

Due to some unfortunate naming, a legacy project has an AssetsController mounted at the following route 

```ruby
resources :assets, :only => :show, :path => 'product-assets' do
  get :preview, :on => :member
  get :metadata, :on => :member
end
```

Trying to add a preload link with `preload_link_tag` uses the URL to that controller, rather than to the assets pipeline.

Digging a little, I'd suspect it's due to [`preload_link_tag` using `asset_path`](https://github.com/rails/rails/blob/165805402871d8e11d11729ea2c00bd0502c36d9/actionview/lib/action_view/helpers/asset_tag_helper.rb#L320) instead of [`path_to_asset`](https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/actionview/lib/action_view/helpers/asset_url_helper.rb#L218).

### Expected behavior
The URL in the preload tag should be the one of the assets pipeline

### Actual behavior
The URL in the preload tag is the one for the controller declared in the routes

### System configuration
**Rails version**: 5.2.0

**Ruby version**: 2.5.5

**Comment by ghiculescu** [comment]
Hi @romaricpascal, thanks for the bug report. Could you confirm if this is still an issue in Rails 6.1? 5.2 is [no longer supported for bug fixes](https://guides.rubyonrails.org/maintenance_policy.html).

If it's still an issue on rails `main` then we should fix it. It sounds like it might be an easy fix, would you like to open a PR?
