### ISSUE TITLE
Asset pipeline guide uses jquery and old javascript syntax

### ISSUE THREAD

**Issue by diegodauri** [rails/rails#42558]
### Steps to reproduce

Go to [rails guides](https://guides.rubyonrails.org) and choose the [asset pipeline guide](https://guides.rubyonrails.org/asset_pipeline.html)

### Expected behavior

Find examples with the new javascript syntax

### Actual behavior

Old syntax examples using jquery and the old manifest sintax, for example:
```javascript
//= require rails-ujs
//= require turbolinks
//= require_tree .
```
```javascript
$('#logo').attr({ src: "<%= asset_path('logo.png') %>" });
```

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: not applicable

**Comment by hahmed** [comment]
Hey @diegodauri, thanks for reporting the issue. 

The asset pipeline is still good to use, also coffee script is still supported in sprockets, but I do agree that moving over any examples we can to javascript would be better.

Specifically https://edgeguides.rubyonrails.org/asset_pipeline.html#javascript-coffeescript-and-erb

```
$('#logo').attr({ src: "<%= asset_path('logo.png') %>" });
```

The first example can be changed over the javascript... did you want to open a pull request to address that?

The second example specifically mentions coffeescript, I think we could snip that part out (below) as it's not really adding any extra value over the previous example. i.e.

```
Similarly, you can use the asset_path helper in CoffeeScript files with erb extension (e.g., application.coffee.erb):
$('#logo').attr src: "<%= asset_path('logo.png') %>"
```

**Comment by hahmed** [comment]
I think that manifest syntax is still valid/correct in sprockets?

**Comment by rafaelfranca** [comment]
Yes. It is. Closing this issue since the PR was merged. If there are more changes to be done please open PRs. Thank you
