### ISSUE TITLE
Proposal: Define timestamps as two first columns in migrations by default

### ISSUE THREAD

**Issue by wout** [rails/rails#42582]
For years now I've been struggling with the positioning of timestamp columns in migrations to create models. Having an empty line in a database migration before the timestamps suggests the model's columns should go there. Initially, that's fine. Timestamps are less important because they are handled by Rails. But in practice, almost every model gets new columns after creation, leaving the timestamps at an awkward position between the initial columns and everything else.

So my proposal is to switch line 4 and 5 in the generated migrations. That way, suggesting the timestamps to be the first two columns in the migration and having everything else come after.

**Comment by rafaelfranca** [comment]
Can you explain why is the order of the columns important?

**Comment by wout** [comment]
It's particularly useful when searching data using a database GUI. Having `id`, `created_at` and `updated_at` grouped together at the start makes it easier to quickly order items. These columns are almost always present, so it makes sense to have them appear together consistently.

As it is now, you'll have the id, then a bunch of columns from the initial migration, then timestamps, then a bunch of columns that came after the initial migration. It always felt a bit sloppy to me.

The migration generator puts the timestamps last, so I always have to open the migration file first to move them instead of running `db:migrate` straight away, adding an extra step.

Since it's just a cosmetic change, it won't break anything.

**Comment by ghiculescu** [comment]
@wout would you like to create a PR?

**Comment by wout** [comment]
@ghiculescu of course, I'll work on a PR this week.

**Comment by ceritium** [comment]
Hi @wout, I think that your proposal is nice to have. Do you still want to tackle it, or can I do it?

**Comment by wout** [comment]
@ceritium I can't make the time right now. So if you can dot it, that would be great!

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/43165#issuecomment-923332590
