### ISSUE TITLE
js_compressor is outdated: no gem is currently maintained

### ISSUE THREAD

**Issue by collimarco** [rails/rails#42589]
In an existing project, that has been using `uglifier` for a long time, I found that it raises an exception when compiling valid ES6 code (e.g. chart.js v3). The I made some research and found that the gem is no longer updated and is not fully compatible with ES6.

So I went to Rails docs to find an updated answer, and this is what I found:

> 5.2 JavaScript Compression
> Possible options for JavaScript compression are :closure, :uglifier and :yui. These require the use of the closure-compiler, uglifier or yui-compressor gems, respectively.
> https://edgeguides.rubyonrails.org/asset_pipeline.html#javascript-compression

**None of the suggested libraries is maintained and none is fully compatible with ES6.**

What is the plan?

**Comment by SkipKayhil** [comment]
Rails 6.0 made the default JS compiler [Webpacker](https://edgeguides.rubyonrails.org/webpacker.html), I would recommend migrating to using that to support more modern language features

**Comment by ghiculescu** [comment]
Maybe we should update https://edgeguides.rubyonrails.org/asset_pipeline.html#javascript-compression to say that?

**Comment by collimarco** [comment]
@SkipKayhil Webpacker is something with a different scope, much more complex, incompatible with existing code and messy (IMHO)... not just an alternative JS compiler.

**Comment by byroot** [comment]
The uglifier README recommends using https://github.com/ahorek/terser-ruby. Assuming it works as advertized, it should be trivial to add an adapter for it, here's the uglifier one: https://github.com/rails/sprockets/blob/master/lib/sprockets/uglifier_compressor.rb, it's really a simple interface.

**Comment by byroot** [comment]
Ah, just noticed that terser even ships with a sprockets adapter: https://github.com/ahorek/terser-ruby#rails

**Comment by collimarco** [comment]
Yes, Terser can be an alternative... In any case the docs should be updated.

At the moment I have disabled the JS compressor because Terser seems relatively new/experimental and when I click on "Build passing" button I get a configuration error... So I was not sure about adding it to a large application.

**Comment by zzak** [comment]
I think [all](https://edgeguides.rubyonrails.org/working_with_javascript_in_rails.html) of [the](https://edgeguides.rubyonrails.org/asset_pipeline.html) current [javascript](https://edgeguides.rubyonrails.org/webpacker.html) guides need a refresh. But I am waiting for things to simmer down with hotwire first.

**Comment by ahorek** [comment]
@collimarco as for being experimental, WebPacker switched to Terser as a default JS compressor 3.5 years ago https://github.com/rails/webpacker/pull/1816

unlike Uglifier (especially the ES6 version), the Terser library (which is a successor to UglifyJS) is well maintained https://github.com/terser/terser

and it's really easy to switch, see GitLab's PR https://gitlab.com/gitlab-org/gitlab/-/merge_requests/44034 (almost a year ago in production)

I originally did the wrapper for a large application in my company that already runs on 2000+ servers all around the world, so I'm pretty confident it's stable enough

the only downside is that https://github.com/rubyjs/therubyracer is no longer supported
https://github.com/rubyjs/mini_racer (which is the default JS runtime on new Rails projects for years) or NodeJS works well

**Comment by pixeltrix** [comment]
> the only downside is that https://github.com/rubyjs/therubyracer is no longer supported

Since support for Ruby Racer was removed from ExecJS 2.8 I don't really see this as a downside

**Comment by guilleiguaran** [comment]
I'm proposing the addition of a railtie to terser-ruby to make it easier to use it with Rails: https://github.com/ahorek/terser-ruby/pull/20

**Comment by guilleiguaran** [comment]
I've added terser to the list of supported options in the guide. 

This can be improved further by changing the uglifier example to terser, feel free to open this PR and ping me 👍

**Comment by collimarco** [comment]
Maybe we should remove the other gems from the docs since they no longer receive updates.
