### ISSUE TITLE
Temporary v5.2 and v6.0 guides redirect (302 Moved Temporarily) to edgeapi.rubyonrails.org

### ISSUE THREAD

**Issue by sergey-alekseev** [rails/rails#42629]
### Steps to reproduce

```
$ curl -I https://api.rubyonrails.org/v2.3/
HTTP/1.1 200 OK

$ curl -I https://api.rubyonrails.org/v3.0/
HTTP/1.1 200 OK

$ curl -I https://api.rubyonrails.org/v3.1/
HTTP/1.1 200 OK

$ curl -I https://api.rubyonrails.org/v3.2/
HTTP/1.1 200 OK

$ curl -I https://api.rubyonrails.org/v4.0/
HTTP/1.1 200 OK

$ curl -I https://api.rubyonrails.org/v4.1/
HTTP/1.1 200 OK

$ curl -I https://api.rubyonrails.org/v4.2/
HTTP/1.1 200 OK

$ curl -I https://api.rubyonrails.org/v5.0/
HTTP/1.1 200 OK

$ curl -I https://api.rubyonrails.org/v5.1/
HTTP/1.1 200 OK

$ curl -I https://api.rubyonrails.org/v5.2/
HTTP/1.1 302 Moved Temporarily
Location: http://edgeapi.rubyonrails.org/

$ curl -I https://api.rubyonrails.org/v5.2/
HTTP/1.1 302 Moved Temporarily
Location: http://edgeapi.rubyonrails.org/

$ curl -I https://api.rubyonrails.org/v6.0/
HTTP/1.1 302 Moved Temporarily
Location: http://edgeapi.rubyonrails.org/

$ curl -I https://api.rubyonrails.org/v6.1/
HTTP/1.1 200 OK
```

### Expected behavior

https://api.rubyonrails.org/v5.2/ and https://api.rubyonrails.org/v6.0/ should respond with 200 OK.

### Actual behavior

https://api.rubyonrails.org/v5.2/ and https://api.rubyonrails.org/v6.0/ respond with 302 Moved Temporarily to http://edgeapi.rubyonrails.org/.

**Comment by sergey-alekseev** [comment]
Sorry if it's not the right repo/place to submit this bug. I haven't found anything better under https://github.com/rails/, there is https://github.com/rails/rails-docs-server which doesn't contain much info (no description and README).

**Comment by sergey-alekseev** [comment]
The behaviour is the same for https://guides.rubyonrails.org.

**Comment by pixeltrix** [comment]
Seems like the docs build for those branches must be failing - we'll investigate, thanks

**Comment by zzak** [comment]
I just got SSH access recently so I'll try to help if I can.

**Comment by fxn** [comment]
Documentation build for the last releases there did not succeed for some reason. We'll check it out.

**Comment by zzak** [comment]
I've regenerated the api and guides for v5.2.6 and v6.0.4, so the following links should be fixed:

* https://api.rubyonrails.org/v5.2/
* https://api.rubyonrails.org/v5.2.6/
* https://guides.rubyonrails.org/v5.2/
* https://guides.rubyonrails.org/v5.2.6/

* https://api.rubyonrails.org/v6.0/
* https://api.rubyonrails.org/v6.0.4/
* https://guides.rubyonrails.org/v6.0/
* https://guides.rubyonrails.org/v6.0.4/

I will look into why it failed and try to prevent this from happening again but I think we can close this.

**Comment by sergey-alekseev** [comment]
Happens again with v5.2:  
```
$ curl -I https://api.rubyonrails.org/v5.2/
HTTP/1.1 302 Moved Temporarily
Location: http://edgeapi.rubyonrails.org/

$ curl -I https://guides.rubyonrails.org/v5.2/
HTTP/1.1 302 Moved Temporarily
Location: http://edgeguides.rubyonrails.org/
```

All other versions return 200 OK. The following should be useful for the copy-paste next time:  
```
curl -I https://api.rubyonrails.org/v2.3/
curl -I https://api.rubyonrails.org/v3.0/
curl -I https://api.rubyonrails.org/v3.1/
curl -I https://api.rubyonrails.org/v3.2/
curl -I https://api.rubyonrails.org/v4.0/
curl -I https://api.rubyonrails.org/v4.1/
curl -I https://api.rubyonrails.org/v4.2/
curl -I https://api.rubyonrails.org/v5.0/
curl -I https://api.rubyonrails.org/v5.1/
v5.2 - NOT OK
curl -I https://api.rubyonrails.org/v6.0/
curl -I https://api.rubyonrails.org/v6.1/
curl -I https://api.rubyonrails.org/v7.0/
```
