### ISSUE TITLE
Need a way to determine the engine rendering the view

### ISSUE THREAD

**Issue by kyrofa** [rails/rails#42645]
I'm poking at adding better webpacker support for engines. As part of that, I've been hunting around for ways to determine which engine is currently rendering a given view, and I'm coming up empty. The idea is this (and it may be stupid/too much magic, feel free to share your thoughts): if the view is in the main app, it should default to using the webpacker instance from the main app. If the view is in an engine, it should default to using the webpacker instance from the engine. My challenge is that, from the `javascript_pack_tag` (and similar helpers) I see no clean way to determine the engine rendering that view, so I don't know which webpacker instance to use.

I have two questions:

1. Is there a way to do this today that I missed?
2. If not, and folks would be amenable to such a feature, can I get some pointers for where to start?

**Comment by zzak** [comment]
@kyrofa Could you direct your question to [discuss](https://discuss.rubyonrails.org)? We only use the [bug tracker](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#reporting-an-issue) for actual bugs and patches.

**Comment by kyrofa** [comment]
Of course, my apologies.

**Comment by zzak** [comment]
@kyrofa No worries! Sorry my answer was a little short was on my way out of the door ❤️

**Comment by kyrofa** [comment]
Hey, I get it, I've been there!
