### ISSUE TITLE
select and select_tag have inconsistent method definitions

### ISSUE THREAD

**Issue by chris-gooley** [rails/rails#42646]
This has been something which has bugged me since Rails 3.
`select` and `select_tag` have inconsistent method declarations.

`select(method, choices = nil, options = {}, html_options = {}, &block)`
`select_tag(name, option_tags = nil, options = {})`

Naming conventions aside, `select` has separate parameters for `options` and `html_options` where as `select_tag` merges them into one. 

Is there a reason they haven't been updated to be more consistent?

**Comment by zzak** [comment]
@chris-gooley Could you direct your question to [discuss](https://discuss.rubyonrails.org)? We only use the [bug tracker](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#reporting-an-issue) for actual bugs and patches. Thank you for understanding!
