### ISSUE TITLE
Migration breaks when model used inside (full reproducible steps)

### ISSUE THREAD

**Issue by borisd** [rails/rails#42660]
### Steps to reproduce

	$ rails new sample
	$ rails g model book

Change the created migration to the following code:

```ruby
def up
  create_table :books # Can be in another migration
  
  Book.count # <--- This line causes the rest to fail
  
  add_column :books, :title, :string
  
  Book.create!(title: 'Hmmm') # <--- Throws exception
end
```

    rake db:migrate

This results in

    ActiveModel::UnknownAttributeError: unknown attribute 'title' for Book.

### Expected behavior
A new instance of `Book` model should be created with `title` set

### Actual behavior
The `add_column` directive fails to work

### Notes
Similar behavior for both sqlite and postgress

### System configuration

**Rails version**: 6.1.4

**Ruby version**: 2.6.3 & 2.7.3

**Comment by ghiculescu** [comment]
Does [`Book.reset_column_information`](https://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html) fix the issue?

**Comment by borisd** [comment]
It does! 

Looks like accessing the model before `add_column` loads the schema and `add_column` does not reset it.

Wonder if `reset_column_information` shouldn't be done by any methods that mutate tables.

**Comment by ghiculescu** [comment]
> Looks like accessing the model before `add_column` loads the schema and `add_column` does not reset it.

Yeah, that's right. I suspect this is done for performance reasons since in the majority of migrations would not need to access schema information between schema changes.

I'm going to close this for now as this doesn't appear to be a bug in Rails 👍
