### ISSUE TITLE
With the schema_cache supporting gz for loading, it should automatically gz when creating

### ISSUE THREAD

**Issue by justin808** [rails/rails#42663]
Following up from https://github.com/rails/rails/pull/38566, it's awesome that @kytrinyx enabled support for a `.gz` format. However, the rake task to create the file creates the uncompressed file with the .gz suffix.

### Steps to reproduce
Add this line to the db/config.yml:

```
  schema_cache_path: db/schema_cache.yml.gz
```

Run rake task:

```
rake db:schema:cache:dump
```

File db/schema.yml.gz is created but it's not gzipped!

### Expected behavior
File should have been gzipped.

### Actual behavior
File is uncompressed. You can see plain text in the file.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.7.3

**Comment by ghiculescu** [comment]
Hmm, [this](https://github.com/rails/rails/pull/38566/files#diff-88a3187247c061ad9f74c57ca178697675b54496e05229d8509e306d637aff2fR212-R216) implies it will be gzipped on write. Do you have any idea how to fix it?

**Comment by fatkodima** [comment]
I'm seeing a gzipped file. 
```
▶ file db/schema_cache.yml.gz
db/schema_cache.yml.gz: gzip compressed data, last modified: Fri Jul  2 01:02:51 2021, from Unix, original size modulo 2^32 3995
```

Can you reproduce this on a freshly generated app from the latest rails?

**Comment by justin808** [comment]
I didn't get a chance yet to create a fresh app. However, this is how I fixed the issue locally:

```ruby
# Rails should be doing this automatically, but it doesn't
# https://github.com/rails/rails/issues/42663
namespace :db do
  namespace :schema do
    namespace :cache do
      task dump: :environment do
        SchemaCache.instance.fix_gzipped_cache
      end
    end
  end
end
```

Here's the `SchemaCache.instance.fix_gzipped_cache`

```ruby
  def fix_gzipped_cache
    # Rails should be doing this automatically, but it doesn't
    # https://github.com/rails/rails/issues/42663
    if schema_cache_path.ends_with?('.gz')
      # Take out the suffix
      puts 'Gzipping the schema_cache because it ends with gz'
      name_no_gz = schema_cache_path[0...-3]
      FileUtils.mv(schema_cache_path, name_no_gz, force: true)
      Rake.sh "gzip #{name_no_gz}"
    end
  end
```

**Comment by justin808** [comment]
I can open a new issue if that's worthwhile.

**Comment by fatkodima** [comment]
@justin808 Yes, please open a separate issue with the use-case for discussion, if you would like. 
Maybe other people have thoughts.
