### ISSUE TITLE
Add a linter to always use OpenSSL

### ISSUE THREAD

**Issue by eileencodes** [rails/rails#42665]
As a followup to https://github.com/rails/rails/pull/41722 we need a linter to make sure that any new code going into rails/rails fails a rubocop rule if it does not use `OpenSSL::Digest` and instead uses `Digest`.

**Comment by markhallen** [comment]
Hi @eileencodes. I'd like to look at this. Should I be assigned or should I just submit a PR? Thanks

**Comment by vishaldeepak** [comment]
If this is not being worked on, I'd like to give this a shot

**Comment by markhallen** [comment]
> If this is not being worked on, I'd like to give this a shot

That is fine for me @vishaldeepak. I haven't had time to get started on it yet. I'm open to collaborating if you wish.

**Comment by vishaldeepak** [comment]
sure, I am definately open to collabration as well. Didn't expect a response so soon,  let me get a feel of this. Thank you @markhallen

**Comment by edipofederle** [comment]
@eileencodes the rob shouldn't  be add the https://github.com/rubocop/rubocop-rails ?

**Comment by markhallen** [comment]
> @eileencodes the rubocop rule shouldn't be add the https://github.com/rubocop/rubocop-rails ?

Hi @edipofederle. I wasn't sure about this myself. My initial feeling was that it should be a rule in rubocop-rails, as I couldn't find any similar responsibility in rails itself. Unless I'm missing something.

@eileencodes did you have a high-level approach in mind? Thanks

**Comment by edipofederle** [comment]
> > @eileencodes the rubocop rule shouldn't be add the https://github.com/rubocop/rubocop-rails ?
> 
> Hi @edipofederle. I wasn't sure about this myself. My initial feeling was that it should be a rule in rubocop-rails, as I couldn't find any similar responsibility in rails itself. Unless I'm missing something.
> 
> @eileencodes did you have a high-level approach in mind? Thanks

Hi @markhallen , I did some investigation, and looks like there is 2 options

1) Implement the rule at `rubocop-rails` gem
2) Implement a custom rule in `rails` itself, for example inside `.cops/linters/some_linter.rb` and include it on `.rubocop`

I just see your comment about your intention to work in this issue, if you already started let me know if you wanna collaborate in something.

**Comment by vishaldeepak** [comment]
wont adding it to rubocop-rails apply it every repo that uses that gem. I dont think thats the intention. We only want rails Repo code to have `OpenSSL`

**Comment by vishaldeepak** [comment]
hi @rafaelfranca , could you review this, or if this is somehow incorrect or needs to be done on rubocop/rails , do let me know. Ignore otherwise, thank you
