### ISSUE TITLE
Active Storage + Rails not working with Docker + Nginx

### ISSUE THREAD

**Issue by SushantKumar29** [rails/rails#42688]
I am using active storage in rails 6 with Docker and Nginx. I am uploading an image through the rails console, i.e., 

`object.images.attach(io: File.open("#{Rails.root}/image_path"), filename: "image.jpg")`

It is uploading successfully, but the file is not getting stored in the specified location i.e., `Rails.root.join("storage")`. And for that, I am not getting the image files. 

I am not sure if the issue is with Docker or Nginx or ActiveStorage

Please help...

 - app.Dockerfile

`FROM ruby:3.0.0
RUN apt-get update \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . /app

COPY ./entrypoint.sh /app
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
EXPOSE 3000
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb", "-p", "3000"]`

 - nginx.Dockerfile

`FROM nginx
RUN apt-get update -qq && apt-get -y install apache2-utils
ENV RAILS_ROOT /app
WORKDIR $RAILS_ROOT
RUN mkdir log
COPY public public/
COPY ./nginx.conf /tmp/docker.nginx
RUN envsubst '$RAILS_ROOT' < /tmp/docker.nginx > /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD [ "nginx", "-g", "daemon off;" ]`

 - nginx.conf

`upstream app {
  server 'app:3000';
}
server {
  listen 3000;
  server_name localhost;
  keepalive_timeout 5;
  root /app/public;
  access_log /app/log/nginx.access.log;
  error_log /app/log/nginx.error.log info;
  if (-f $document_root/maintenance.html) {
    rewrite  ^(.*)$  /maintenance.html last;
    break;
  }
  location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    if (-f $request_filename) {
      break;
    }
    if (-f $request_filename/index.html) {
      rewrite (.*) $1/index.html break;
    }
    if (-f $request_filename.html) {
      rewrite (.*) $1.html break;
    }
    if (!-f $request_filename) {
      proxy_pass http://app;
      break;
    }
  }
  location ~ ^(?!/rails/).+\.(jpg|jpeg|gif|png|ico|json|txt|xml)$ {
    gzip_static on;
    expires max;
    add_header Cache-Control public;
    try_files $uri =404;
    error_page 404 /404.html;
  }
  location = /500.html {
    root /app/current/public;
  }
}`

 - docker-compose.yml

`version: '3.9'
services:
  db:
    image: mariadb:10.3.29
    restart: unless-stopped
    volumes:
      - .:/app
      - db-volume:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MARIADB_DATABASE_NAME: database
      MARIADB_ROOT_USERNAME: username
      MARIADB_ROOT_PASSWORD: password
    networks:
      - network_name
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: container_name
    command: bash -c "bundle exec puma -C config/puma.rb -p 3000"
    restart: unless-stopped
    volumes:
      - .:/app
      - bundle-volume:/usr/local/bundle
    depends_on:
      - db
    networks:
      - network_name
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 3000:3000
    networks:
      - network_name
volumes:
  db-volume:
  bundle-volume:
networks:
  network_name:`

**Comment by zzak** [comment]
@SushantKumar29 Could you upload a reproducible app and share it here with steps to reproduce?

I'm guessing it has something to do between docker and the storage service, not Rails itself but that might help us get to the bottom of it. :bow:

**Comment by p8** [comment]
Hi @SushantKumar29 this appears to be a docker issue.
I'm closing this for now due to inactivity.
