### ISSUE TITLE
Encoding check on Active Record encryption serialization fails if value does not implement `#encoding`

### ISSUE THREAD

**Issue by dark-panda** [rails/rails#42699]
### Steps to reproduce

The recent changes to enforce encodings in AR encryption can cause values serialized with custom or alternative encryptors to fail if the serialized value does not support `#encoding`, as in the case of, say, `Array` or `Hash`. I'm using AR encryption in a project and we have a custom serializer that uses JSON values in Postgres, which means our encrypted output is wrapped in a `Hash`, which causes the encoding checks to fail.

The specific breakage is here: abfd2cc7a6eab91c558a30f7376c1b994055b2f4

### Proposed fix

The following code can be modified to check for `#encoding` on `value`:

```ruby
def force_encoding_if_needed(value)
  if deterministic? && forced_encoding_for_deterministic_encryption && value && value.respond_to?(:encoding) && value.encoding != forced_encoding_for_deterministic_encryption
    value.encode(forced_encoding_for_deterministic_encryption, invalid: :replace, undef: :replace)
  else
    value
  end
end
```

In the above code I've inserted `value.respond_to?(:encoding)`, which fixes the issue.

### System configuration

**Rails version**: 6.1.3.2, with AR encryption backported

**Ruby version**: 2.7.3

**Comment by zzak** [comment]
@jorgemanrubia Do you have any thoughts here? :bow:

@dark-panda Would you be willing to contribute a PR? :pray:

**Comment by jorgemanrubia** [comment]
@dark-panda Thanks for looking into this. As of today, Active Record encryption is meant to work with string values. If using other types, they should be serialized to a string before being encrypted. With built-in Rails types like "serialized attributes" this can be achieved by making sure that the `encrypts` declaration comes after their declaration ([check this](https://edgeguides.rubyonrails.org/active_record_encryption.html#supported-types)). Is this an option in your case?

**Comment by dark-panda** [comment]
@jorgemanrubia we are serializing to a jsonb field in Postgres. We have kind of a neat use case, where we wrote an encryptor that encrypts the values in a jsonb/hash field using deterministic encryption so that we can use Postgres’ jsonb operators and functions and such on the encrypted results. This lets us query on the data within the encrypted field, as the structure of the field is maintained while the values are encrypted and secured. It works quite well and let’s us index on the jsonb fields and everything and use many of the fun jsonb features in Postgres like SQL/JSON. 

One option I might be able to do is wrapping the structure in a thin wrapper that implements `#encoding` or whatever.

**Comment by jorgemanrubia** [comment]
I see @dark-panda, thanks for explaining the use case. I think I'd rather move the "forced encoding" to the standard encryptor, so that we remove the encoding concern from the type. Would you like to create that PR? I can help if you need.

>  This lets us query on the data within the encrypted field, as the structure of the field is maintained while the values are encrypted and secured. It works quite well and let’s us index on the jsonb fields and everything and use many of the fun jsonb features in Postgres like SQL/JSON.

Just out of curiosity, is this because you encode only certain JSON values and not others? Or, if everything is encrypted, how do you leverage the json format? I'd love if you could explain with some example.

**Comment by dark-panda** [comment]
@jorgemanrubia I can probably whip something up, sure.

Basically, our encryptor retains the structure of the JSON value while only encrypting the values. We thought about further encrypting the keys, but for now we're just doing the values.

Take for instance this sort of structure:

```javascript
{
  "foo": {
    "bar": {
      "baz": [ 1, 2, 3, 4 ]
    } 
  }, 

  "hello": "world"
}
```

Once it passes through our encryptor, that JSON becomes something akin to the following:

```javascript
{
  "message": {
    "foo": {
      "bar": {
        "baz": [ 
          "iw==--gUIKGljabk0xfkIN--5NRAjT8z8LBwXMQGMcZaGA==--u", 
          "fg==--chPRQgXZKV2zyO3k--yOFP0M1n0P51O+Sds2liRQ==--u", 
          "2A==--cIsaHkkn6iWvUBzj--I4Ir+ix9yDozKoopSXqAZQ==--u", 
          "NA==--NleCna20fUsvzFXV--bbWkd6MQyDE80xE68f7w1A==--u"
        ]
      }
    },
    "hello": "h5vsDTTGzQ==--O2dXS3fBNeEnST1W--jKzhvmInzCKNH+e3EM1I0g==--u"
  },
  "signature": "d649f1a467406a48496816d84b39710fbe58e956d4162b43c154209513324d6a"
}
```

So what we're seeing is that we encrypt just the primitive values within the nested JSON structure using a deterministic cipher. Each of the values is encrypted separately using the same encryption schemes as the AR encryption stuff, so the encrypted values contain an IV, tag, compression, the payload, etc. 

The signature that we've added is a HMAC digest of the entire JSON field to ensure that the structure as a whole cannot be tampered with. The individual values are encrypted separately, but the overall structure needs to maintain integrity so the structure cannot be manipulated, so we check that signature when we deserialize the values and before we decrypt.

We've combined this with Postgres' JSON querying capabilities, so we can effectively do stuff like this:

```ruby
SomeModel.where_encrypted_json_path_exists(:data, '$.message.foo.bar.baz[*] ? (@ == :value)', value: 3)
```

Which gets translated to

```sql
 SELECT some_models.*
  FROM some_models
  WHERE some_models.data @? '$.message.foo.bar.baz[*] ? (@ == "2A==--cIsaHkkn6iWvUBzj--I4Ir+ix9yDozKoopSXqAZQ==--u")'
```

So we can see that our query uses the same deterministic value for `3` as what we encrypted in the JSON structure we stored. We can put an index on this in Postgres and the querying becomes very efficient. Now, we do lose access to various operators within SQL/JSON because we can't do things like comparison operators, but most of the time we're checking for things like equality and path existence and that sort of thing. This also lets us to various analytics on the data sets without decrypting them, as we can query on all of this stuff right in the database.

We use JSON fields in a bunch of places in our app, and our developers like the flexibility, so this gives us the ability to encrypt and still leverage those JSON capabilities in a very accessible way and still enjoy some of the benefits of indexing without having to build out purpose-built blind indexes and that sort of thing. We may run into the use case where we may eventually need more purpose-built blind indexes, but for right now it's working very well with our current use cases.

**Comment by jorgemanrubia** [comment]
Thanks for the detailed explanation @dark-panda 🙏, I  understand the use case much better now.

**Comment by dark-panda** [comment]
A PR for this issue is up at #42778.

**Comment by gjtorikian** [comment]
@dark-panda You wouldn't happen to have that custom encryptor written anywhere, would you?

**Comment by gjtorikian** [comment]
👋 In the end, I turned this logic into its own gem: https://github.com/gjtorikian/encrypted_jsonb
