### ISSUE TITLE
Why the bundler showing this error or incorrect version

### ISSUE THREAD

**Issue by prvinuch** [rails/rails#42697]
### Steps to reproduce

I was trying to upgrade rails and ruby version and also tried updating the dependent gem, I'm getting this error which I'm not able to understand
```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    actionpack (~> 6.0, >= 6.0.4)

    public_activity (~> 1.6, >= 1.6.4) was resolved to 1.6.4, which depends on
      actionpack (>= 3.0.0)

    rails (= 6.0.4) was resolved to 6.0.4, which depends on
      actionpack (= 6.0.4)

```

```ruby
# Your reproduction script goes here
```

### Expected behavior

as per my understanding, the version of actionpack is 6.0.4 which should be ok as public_activity gem also depends upon actionpack >=3.0.0 which is being satisfied by 6.0.4 
and similarly for rails 6.0.4

### System configuration
**Rails version**:
6.0.4
**Ruby version**:
2.6.7

**Comment by p8** [comment]
Hi @prvinuch, thanks for reporting this issue.

You could probably run something like `bundle update rails actionpack` to fix this.
This is a Bundler issue instead of a Rails issue, so I'm closing it.
You might have more luck on the Rails forum: https://discuss.rubyonrails.org/
