### ISSUE TITLE
Globally strip null bytes for application

### ISSUE THREAD

**Issue by athix** [rails/rails#42696]
Okay, so my Google foo is failing me, apologies if this has been answered before and I just can't find it.

I'm wanting to strip null bytes from all text columns because Postgres cannot accept null bytes, and my application doesn't care about storing them.

One approach that you can take is to override each attribute setter individually:

```ruby
class User < ApplicationRecord
  def name=(value)
    if value.is_a?(String) && value.present?
      super(value.delete("\u0000"))
    else
      super(value)
    end
  end
end
```

This works, but it quickly gets unwieldy if you need to do this for _every string attribute in the application_.

Ideally, I would be able to override it globally, e.g. something like:

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def attribute=(value)
    if value.is_a?(String) && value.present?
      super(value.delete("\u0000"))
    else
      super(value)
    end
  end
end
```

So my questions are:

1. Is wanting to do this sane? How do others approach users providing null bytes when you're using Postgres?
2. Are there any ways to override the attribute setters for all setters in an application? I would be fine with monkey patching / meta programming if that's the only option available.

**Comment by p8** [comment]
Hi @athix,

You can post these kind of questions in the forum: https://discuss.rubyonrails.org/
Maybe you could override:
https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Write.html#method-i-write_attribute

We reserve the bug tracker for actual bugs and patches, so I'm closing this.

**Comment by athix** [comment]
Looks like this gets the test suite passing, might be some gotchas I haven't run into yet, but it seems to be working!

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def _write_attribute(attr_name, value)
    if value.is_a?(String) && value.present?
      super(attr_name, value.delete("\u0000"))
    else
      super
    end
  end
end
```

Guessing that most of the rails internal calls are using the version of the method without the primary key check for speed.
