### ISSUE TITLE
Better document how to migrate active storage from image magick to libvips

### ISSUE THREAD

**Issue by brenogazzola** [rails/rails#42700]
I had previously opened PR #42482 to show that ImageMagick and libvips are not fully compatible. But now that I have actually made the migration in a production app, I've noticed that was only one of the many things that need to be changed.

Is there a place in the documentation we can add this, to help other developers trying to make the move?

Gist with all the changes required:
https://gist.github.com/brenogazzola/a4369965a1da426d50f11d080fe2e563

**Comment by ghiculescu** [comment]
Good question, I will ask around for second opinions. My gut feel it would make a great blog post (you've already half written it!) but not clear if it needs to live in the Rails guides.

**Comment by brenogazzola** [comment]
Sure. I suggested as part of rails because DHH did something similar for Turbolinks/Turbo:
https://github.com/hotwired/turbo-rails/blob/main/UPGRADING.md

**Comment by ghiculescu** [comment]
My thinking in that case is that `turbolinks` -> `turbo` is a pretty common upgrade path. Is imagemagic -> vips the same? I got the impression imagemagick is fine for most use cases and Rails is supporting both equally.

**Comment by brenogazzola** [comment]
You are right that there's nothing that Vips does that ImageMagick can't do. But I still believe Vips is a clear upgrade when compared to ImageMagick and have been recommending most people who are using active storage to make the switch. I'd go as far as to say that Rails Active Storage guide should do the same. Here's why I think that:

**It improves queue time**
Let's say you allow users to upload multiple photos and then redirect them to their gallery. Now let's say your user selects 5 photos. When the user opens the gallery, it will generate 5 requests to the representations controller, which will process 5 images, keeping 5 puma workers occupied. Vips can go through those images much faster then ImageMagick, improving queue times. 

This is specially problematic on Heroku. From my experience in the CGRP group, many devs are running Standard-2x dynos with a concurrency of 2 and auto scaling enabled (thus running few servers at the same time). With Heroku assigning requests at random, you might end with multiple unrelated requests waiting in the queue of a server trying to process the multiple images.

**It improves response time**
Image Magick must load the entire image in memory to process it. Considering how good phone cameras are now, we are talking about some pretty big photos being processed. If you are running instances with low memory (512MB, 1GB memory), a couple large images can throw your app above the ceiling and force it to swap. As soon as this happens, ActiveRecord will start having problems allocating objects for queries. A `find` that used to take 1-2ms will start taking 10-30ms. If you have multiple of those in a page, you might be talking about a few hundred extra ms to open a page. And that might make users give up.

**Comment by brenogazzola** [comment]
I'll readily admit that my "evidence" is based on the single production app I have control of, and that I'm basically extrapolating that other apps running with low concurrency and/or limited memory will see the same benefits. I'll also admit that the Turbolinks -> Turbo is a much clearer "upgrade" then ImageMagick -> Vips.

However if we assume that what I said makes sense, then Rails should probably incentivize developers to use Vips. This is a form of conceptual compression. By providing a better default, Rails eliminates the needs for developers to understand how Active Storage's chosen implementation for variant generation, when combined with ImageMagick slow processing, can impact their user's experience (and how ImageMagick memory intensive processing can make it difficult to stay under the memory ceiling of their servers)

If we do that, then providing a good upgrade guide is necessary.

**Comment by brenogazzola** [comment]
Sorry, this became a bit of a rant, but my argument is based on a feeling that more and more developers will be using ActiveStorage for their images, and that there's still a lot of low hanging fruits we can pluck to make this a better experience (#42394, #42683, #42686) so that they don't have to spend as much time as I had to figure out all these things.

**Comment by ghiculescu** [comment]
> However if we assume that what I said makes sense, then Rails should probably incentivize developers to use Vips. This is a form of conceptual compression

I'm on board with this, and it's great to learn from your experience. I think it's a good thing to [discuss](https://discuss.rubyonrails.org/c/rubyonrails-core/5). I'm going to try upgrading an app that uses AS from imagemagick to vips to test your instructions out, will report back with any findings.

**Comment by brenogazzola** [comment]
I had completely forgotten we had that forum. Should I post this there?

Also, I've updated the GIST. It's now explaining a 2 step process and contains another adjustment (remove EXIF based rotation) because I had forgotten that vips auto rotates images when processing.

**Comment by ghiculescu** [comment]
> I had completely forgotten we had that forum. Should I post this there?

Yes please!

**Comment by brenogazzola** [comment]
Done. Here's the [link](https://discuss.rubyonrails.org/t/make-vips-the-recommended-variant-processor-for-active-storage/78368).

**Comment by ghiculescu** [comment]
Can we close this now @brenogazzola ?

**Comment by brenogazzola** [comment]
Yes, definitely. Sorry, I had forgotten about this issue
