### ISSUE TITLE
ActiveRecord and JSONB: Incorrect quoting for array of value to look for

### ISSUE THREAD

**Issue by Pagehey** [rails/rails#42713]
### Issue
Since latest patch `6.1.4`, it seems there is a bug in queries over **jsonb** postgres's columns when passed an array in `where` query builder. The array elements seem to be "overquoted" jsons and thus query doesn't return expected records. This worked perflectly well in previous versions.

### Steps to reproduce
Its needs 
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "6.1.4"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql",  database: 'jsonb_activerecord_issue')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :entries, force: true do |t|
    t.jsonb :value
  end
end

class Entry < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_entry_query
    entry   = Entry.create(value: 1)
    entries = Entry.where(value: [1, 2])

    assert_equal 1, entries.count
    assert_includes entries, entry # But works with Rails 6.1.3
  end
end

```

### Expected behavior
Until `6.1.3`, when looking at the logs we can see that the binds are correctly to match json value (since `JSON.parse("1") == 1`). Here is what I expected to see : 
```ruby
Entry.where(value: [1, 2])
Entry Load (64.6ms)  SELECT "entries".* FROM "entries" WHERE "entries"."value" IN ($1, $2)  [["value", "1"], ["value", "2"]]
```

### Actual behavior
But with `6.1.4` its like the binds are quoted two times since we can see that quotes are now escaped in binds :
```ruby
Entry.where(value: [1, 2])
Entry Load (63.9ms)  SELECT "entries".* FROM "entries" WHERE "entries"."value" IN ($1, $2)  [["value", "\"1\""], ["value", "\"2\""]]
```

### System configuration
**Rails version**: 6.1.4

**Ruby version**: 2.6.6

Thank you for your time, I hope this is actually a bug and that it can be easily fixed. Unfortunately, I don't know enough (yet!) about ActiveRecord internals to know where to look exactly and provide a fix. I'll be please to give more details if needed or even work on a fix if told where the bug happen.

**Comment by mdemare** [comment]
I've been digging into this a bit. Looks like it was introduced in https://github.com/rails/rails/pull/41068. 

exec_params gets called with:

```
PG::Connection.exec_params("SELECT COUNT(*) FROM "entries" WHERE "entries"."value" IN ($1)", ["\"1\"", "\"2\""])`
```

That's incorrect. The following is what happens in `exec_params` in a nutshell:

```
type = ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Jsonb.new
binds = %w(1 2).map { ActiveModel::Attribute::WithCastValue.new("value", _1, type) }
type_casted_binds = binds.map { type.serialize(_1) }
```

However, the values that the binds were created from had already been serialized in `Arel::Visitors::ToSql#visit_Arel_Nodes_HomogeneousIn`

Before PR#41068, the binds were not converted to attributes, and therefore were only serialized once. Also, the text of that PR suggests that it is a fix for the logging only, but it affects both the call to `log` and the call to `exec_params`.

The test by @Pageheyreveals the bug for jsonb and postgres, but it might occur for other datatypes and databases.

I'd like to take a stab at this, but I'm lacking some context. Pinging @kamipo, @eileencodes and @ricardotk002.

**Comment by medranocalvo** [comment]
This issue persists with Rails 7.0.3.  Please reopen.

**Comment by tisba** [comment]
Can confirm on `7.0.3.1`. The issue seems to be independent on the DB adapter (using MySQL in this case). It only happens, if the attbiubute is serializable:

```ruby
serialize :limits, JSON

# …

User.where(limits: [nil, "{}"])
# produces this SQL: SELECT `users`.* FROM `users` WHERE (`users`.`limits` = '\"{}\"' OR `users`.`limits` IS NULL)
# should be SELECT `users`.* FROM `users` WHERE (`users`.`limits` = '{}' OR `users`.`limits` IS NULL)
```

The provided value is serialised (though JSON) twice (thx for the analysis @mdemare)

**Comment by mowat27** [comment]
Still having problems with this and it's blocking us from upgrading one of our apps to rails 7.  Can you please re-open this?
