### ISSUE TITLE
Allow to use different tables on different SQL operations (select, insert, update, destroy)

### ISSUE THREAD

**Issue by mildred** [rails/rails#42711]
I'm willing to provide an implementation as a PR

I think it would be nice to be able to choose a different table name depending on the current CRUD operation.

My use case is that I have a single model composed of a view and a table name. The view aggregates results from the table and from another source. The view is not updatable in itself. I'd like new records, updates and destroys to happen the table, and selects to happen in the view.

I'd imagine the following configuration in the model class:

```rb
class MyModel < ApplicationRecord
  self.table_name = :my_models
  self.insert_table_name = :my_writable_models
  self.update_table_name = :my_writable_models
  self.delete_table_name = :my_writable_models

  # ...
end
```

I plan to implement this in `lib/active_record/core.rb` where the method `def arel_table` would take an optional parameter that represents the operation to carry out, and update `lib/active_record/persistence.rb` to make use of this new parameter.

**Comment by mildred** [comment]
Alternative configuration could be:

```rb
class MyModel < ApplicationRecord
  self.table_name = :my_models, insert: :my_writable_models, update: :my_writable_models, delete: :my_writable_models

  # ...
end
```

It might simplify a bit the implementation and better allow for extensions in the future

**Comment by p8** [comment]
Hi @mildred, 

Rails does support connecting to separate databases for reading and writing.
If you create the view in a separate database you could split reading and writing.
https://edgeguides.rubyonrails.org/active_record_multiple_databases.html
```ruby
class MyModel < ApplicationRecord
  connects_to database: { writing: :my_database, reading: :my_database_with_views }
end
```

Another solution could be using scenic (although I haven't used it).
https://github.com/scenic-views/scenic

**Comment by p8** [comment]
I'd expect multi table support to have a api similar to multi db support.
```ruby
class MyModel < ApplicationRecord
   connects_to table: { writing: :my_writable_models, reading: :my_models }
end
```

**Comment by p8** [comment]
This issue appears to be a feature request. As we reserve the issue tracker for issues only, I'm closing this.
The discussion can continue in the attached PR.
If you are unsure if the feature would be accepted, please ask on the [rubyonrails-core](
https://discuss.rubyonrails.org/c/rubyonrails-core/5) forum.
