### ISSUE TITLE
ActiveRecord supports validate_uniqueness_of for json field

### ISSUE THREAD

**Issue by hyhuang1218** [rails/rails#42715]
### Steps to reproduce
Create a json field in `ApplicaionRecord` and verify the uniqueness of the field using `validate_uniqueness_of`.

Create a record with following json:
```json
[{
	"name": "order_id",
	"value": 50,
	"operator": "=="
}]
```

Then create another record with following json:
```json
[{
	"name": "order_id",
        "operator": "==",
	"value": 50
}]
```

### Expected behavior
`validate_uniquess_of` should compare json natively and fail when creating the second record. 

### Actual behavior
Currently, it always compares using strings. As a result, the validation succeeds when create the second record as the order of keys are different.

### System configuration
**Rails version**:
6.1.4
**Ruby version**:
2.7.2

**Comment by mdemare** [comment]
I don't think that there's a native equality operation for the `json` type that does what you want. `jsonb` does work however.

**Comment by hahmed** [comment]
@hyhuang1218 thanks for reporting the issue. Could you replicate the issue you are seeing using the bug report template, found https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb ?

Maybe something like this:

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :events, force: true do |t|
    t.json 'payload'
  end
end

class Event < ActiveRecord::Base
  validates_uniqueness_of :payload
end

class BugTest < Minitest::Test
  def test_json_compare
    event1 = Event.create(payload: { kind: "user_renamed", change: ["jack", "john"]})
    event2 = Event.create(payload: { change: ["jack", "john"],kind: "user_renamed" })
    event3 = Event.create(payload: { change: ["jack", "john"],kind: "user_renamed" })
    puts event3.valid? # => false
    assert_equal event1.payload, event2.payload
  end
end
```

From what I understand about the json store type, it's storing the exact copy of the input text, preserving white space and order of objects whereas jsonb does not preserve the order. See here for more details https://www.postgresql.org/docs/current/datatype-json.html. 

Once you can replicate that issue, I can take another look 🙂

**Comment by hyhuang1218** [comment]
@hahmed Thanks for looking into this! I think jsonb only works with postgresql, not MySQL? 

We use MySQL and it doesn't support `t.jsonb`. As a workaround, I wrote some custom validation to compare after loading the objects so that the json field is loaded as hash/array for comparison. Just felt it would be nice that ActiveRecord supports it natively.

**Comment by hahmed** [comment]
Ah you meant mysql, thanks for that info, from what I can see looking at the mysql docs here https://dev.mysql.com/doc/refman/8.0/en/json.html#json-comparison

```
OBJECT

Two JSON objects are equal if they have the same set of keys, and each key has the same value in both objects.

Example:

{"a": 1, "b": 2} = {"b": 2, "a": 1}
The order of two objects that are not equal is unspecified but deterministic.
```

From what I'm reading, both databases seem to be doing things differently;

- mysql: order is not important and the objects are still the same
- postgresql: it's a text and comparing 2 texts will fail when the order of objects are not the same

I'm going to do a bit more reading around the json specs to see what I can find, if you do have any links that would be awesome.

**Comment by hyhuang1218** [comment]
From what I understand, MySQL treats JSON field as an object when compare, however, in ActiveRecord, it compares JSON as a pure string the same way as postgresql. 

With the different behaviors among different databases, I think it may not be a good idea to just simply change the behavior of `ActiveRecord` on JSON field from one way to another.

**Comment by hahmed** [comment]
Agreed, In that case I will go ahead and close this issue for now 🙂
