### ISSUE TITLE
"ActionView::Template::Error: undefined method" is raised with Rails 6 and prepend_view_path with config.cache_classes false

### ISSUE THREAD

**Issue by GCorbel** [rails/rails#42727]
### Steps to reproduce
In a Rails 6.0.4 application, we use prepend_view_path to switch between two versions of the design. Some view files have the same path with a different namespace. For example, there is `app/views/home/index.html.erb` and `app/views/v2/home/index.html.erb`.

On `config/environments/development.rb`, there is `config.cache_classes = false` and `config.action_view.cache_template_loading = false`. 

### Expected behavior

Changes in view files have to be visible without to restart the server.

### Actual behavior

The view file is correctly compiled on first load, but if we change a view file, "ActionView::Template::Error: undefined method" is raised. The error happens because in [ActionView::Template#compile!](https://github.com/rails/rails/blob/v6.0.4/actionview/lib/action_view/template.rb#L269-L289), the value of `@compile` is set to true, so the method isn't created in the view context.

I changed `config.action_view.cache_template_loading` to true and it fixes the issue, but I have to restart the server every time I change a view.

This ugly patch does the job by always compiling templates :

```
module AlwaysCompile
  def compile!(_view)
    @compiled = false if Rails.env.development? && !view.respond_to?(method_name)
    super
  end
end

ActionView::Template.prepend(AlwaysCompile)
```

This issue is very similar to https://github.com/rails/rails/issues/40613, but I have no error on test environment.

### System configuration
**Rails version**:
6.0.4

**Ruby version**:
2.6.6p146

**Comment by ghiculescu** [comment]
Do you happen to know if this is still an issue in 6.1? According to https://guides.rubyonrails.org/maintenance_policy.html#bug-fixes 6.0 is only getting security patches.

**Comment by aishbuilds** [comment]
Hi @GCorbel @ghiculescu - I was trying to replicate the issue on the latest `main`. And, the view rendered correctly without the need to restart the server and without erroring out.

Created a walkthrough video: 

https://user-images.githubusercontent.com/4476196/130128381-d66e50ea-ffa5-4039-b2b7-7e4a4f479ea5.mp4

Please let me know if you still think you are facing an issue. I'd love to help resolve!

**Comment by GCorbel** [comment]
I finally found the root cause of the issue and it's not related to rails. Sorry about that.

FTR, it happens because we had (I don't know why I miss that) :

```
# app/controllers/application_controller.rb
  before_action :set_view_path
  V2_VIEW_PATHS = [ActionView::OptimizedFileSystemResolver.new("#{Rails.root.join('app/views/v2')}")]
  def set_view_path
    prepend_view_path(V2_VIEW_PATHS)
  end
```

In this case, `V2_VIEW_PATHS` is computed when the application and not on each reload. Because of this, files are cached in entries in `lookup_context.view_paths.paths` when it shouldn't be when `config.cache_classes` is `false`.
