### ISSUE TITLE
ActiveSupport: concern not extended by ClassMethods when including another concern

### ISSUE THREAD

**Issue by qnighy** [rails/rails#42730]
When a module includes a concern, the module is extended by `<The concern>::ClassMethods`. However, it doesn't work when the module is already itself a concern.

### Steps to reproduce

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'activesupport'
end

require 'active_support/concern'

module Concern1
  extend ActiveSupport::Concern

  class_methods do
    def greet(name)
      puts "Hello, #{name}!"
    end
  end
end

module Concern2
  extend ActiveSupport::Concern
  include Concern1
  # extend Concern1::ClassMethods

  greet("world")
end
```

### Expected behavior

`Concern2` is extended by `Concern1::ClassMethods`. It outputs `Hello, world!`

### Actual behavior

`Concern2` is not extended by `Concern1::ClassMethods`. It fails with the following error

```
Traceback (most recent call last):
	1: from repro2.rb:25:in `<main>'
repro.rb:25:in `<module:Concern2>': undefined method `greet' for Concern2:Module (NoMethodError)
```

### System configuration

**Rails version**: 6.1.4

**Ruby version**: 2.7.3

**Comment by lfalcao** [comment]
Maybe that's expected? https://stackoverflow.com/a/15954818

**Comment by qnighy** [comment]
Thank you for the reference! I don't still understand why `base.extend ClassMethods` part is guarded by `@_dependencies`, so this is my investigation:

----

`ActiveSupport::Concern`'s origin is https://github.com/rails/rails/commit/c1aa5b0e14cd4bd27a5d8bd85cf7c36fa5911830, where three DSL methods `#setup`, `#use`, and `#depends_on` were added to `Module` to reduce boilerplates and correctly resolve indirect dependencies. At that time, we distinguished `#use` and `#depends_on`; `#use` for a root of dependency trees (usually a class) and `#depends_on` for a module which is to be `#use`d.

Then the DSL was made opt-in as `ActiveSupport::DependencyModule` in https://github.com/rails/rails/commit/2854535b02bcee3668bda02c76c3105fc24730d3. We no longer needed to be careful not to poison `Module`, so we reused `#include` for the purpose of `#use`. (`#setup` was also renamed as `#included` with a block.)

In https://github.com/rails/rails/commit/4e50a35fa243f6cf7ad567774a9f7c1cb87a1653 some part of `ActiveSupport::DependencyModule` was separated into `ActiveSupport::Concern`.

In https://github.com/rails/rails/commit/669fd84910586d4c791b6f5bf4320f68ac7845aa `#depends_on` was aliased as `#include` in `ActiveSupport::Concern`. This means:

- When the module/class is extended by `ActiveSupport::Concern`, `#include` behaves like what is originally called `#depends_on`.
- When the module/class is **not** extended by `ActiveSupport::Concern`, `#include` behaves like what is originally called `#use`.

In https://github.com/rails/rails/commit/7ec947d59c1bc3e9772788b757fe70f51b0ffd9b `ActiveSupport::Concern` was refactored to use the existence of `@_dependencies` to achieve the above branch, without overriding `#include` itself. Additionally, `ActiveSupport::DependencyModule` was absorbed by `Concern`.

----

So in my understanding, this behavior is a reminiscence of when `#use` and `#depends_on` were distinguished.

**Comment by qnighy** [comment]
There is a great compatibility concern (pun not intended) in changing this behavior (like method name conflict), but otherwise I think it's a good idea to remove the historical distinction of the two `#include` methods.

**Comment by rafaelfranca** [comment]
Changing this behavior at this point can indeed break many apps. The `included` blocks would be executed inside the `Concern2` in your example and not inside the class that will include `Concern2`. I don't see a way to fix this without introducing a new DSL for concerns and given this behavior is already there for more than 10 years, I'm not sure we have enough reason to change.

Thank you for the issue.
