### ISSUE TITLE
ActiveRecord::RecordInvalid Validation failed

### ISSUE THREAD

**Issue by Souravgoswami** [rails/rails#42741]
### Steps to reproduce

```
$ rails c

> u = User.create!(email: 'hello@world.net', password: 'He11oWor1d!', first_name: 'Hello', last_name: 'World', organizations: Organization.last(1))

> User.find(id: u.id) &.save!
```

```ruby
  has_and_belongs_to_many :organizations
  belongs_to :active_organization, class_name: 'Organization', optional: true
  has_many :user_roles
  has_many :notifications, foreign_key: :recipient_id
  has_and_belongs_to_many :audits

  has_secure_password(validations: false)
  has_secure_password :password_reset_token, validations: false


  validates :password,
          presence: true,
          length: { minimum: 8 },
          format: { with: /(?=.*[0-9])(?=.*[!?@#$%^&*_.,])(?=.*[a-z])(?=.*[A-Z])/ }

.
.
.
```

### Expected behavior
The save!() method should save the user.

### Actual behavior
After a user is created, upon any modification and save!() or running save!() solely raises `ActiveRecord::RecordInvalid` like the following:

```
> User.find(id: u.id) &.save!
  User Load (0.2ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
Traceback (most recent call last):
        1: from (irb):6:in `<main>'
ActiveRecord::RecordInvalid (Validation failed: Password can't be blank, Password is too short (minimum is 8 characters), Password is invalid)
```

Also, `User.find(id: u.id) &.save` returns false.

### System configuration
**Rails version**:
Rails 6.0.3.6

**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Comment by lfalcao** [comment]
@Souravgoswami it worked here. Check if you don't have any [callbacks](https://api.rubyonrails.org/v6.1.4/classes/ActiveRecord/Callbacks/ClassMethods.html) changing something...

# steps:
1) rails generate model User email:string password_digest:string
2) ~ added validations to user model ~
3) rails runner "User.create!(email: 'helllo@world.net', password: 'He11oWor1d!'); puts User.last.inspect"

**Comment by p8** [comment]
@Souravgoswami `has_secure_password` doesn't store the password in the database, as it is unsafe to store passwords clear text. Instead it stores the password hash in `password_digest`.

So your custom validation on password doesn't work when you reload the `User` because password will be `nil`.

See the documentation of `has_secure_password` for more details:
https://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html#method-i-has_secure_password
https://github.com/bcrypt-ruby/bcrypt-ruby/blob/master/README.md

**Comment by Souravgoswami** [comment]
> @Souravgoswami `has_secure_password` doesn't store the password in the database, as it is unsafe to store passwords clear text. Instead it stores the password hash in `password_digest`.
> 
> So your custom validation on password doesn't work when you reload the `User` because password will be `nil`.
> 
> See the documentation of `has_secure_password` for more details:
> https://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html#method-i-has_secure_password
> https://github.com/bcrypt-ruby/bcrypt-ruby/blob/master/README.md

Got it! Thanks!
