### ISSUE TITLE
Rails.cache.delete_matched not deleting matched keys in all nodes in Redis cluster

### ISSUE THREAD

**Issue by Subramanian-ERS** [rails/rails#42750]
### Steps to reproduce
1. Write a large number of keys to the Redis cluster with Rails.cache:
```ruby
1000.times {|i| Rails.cache.write("key_#{i}", "dummy_value")}
```
2. Delete the added keys based on a regex using Rails.cache.delete_matched:
```ruby
Rails.cache.delete_matched("key_*")
```
### Test case
```ruby
def test_cross_slot_issues_in_rails_cache_delete_matched
    #Add 1000 keys
    1000.times {|i| Rails.cache.write("key_#{i}", "dummy_value")}
    Rails.cache.delete_matched("key_*")
    redis = Redis.new(cluster: %W[redis://<cluster_host_url>:<redis_cluster_port>)
    assert_equal 0, redis.keys("key_*").count
end
```

### Expected behavior
All the keys should have been deleted.

### Actual behavior
An error is returned - "Redis::CommandError: CROSSSLOT Keys in request don't hash to the same slot"

### System configuration
**Rails version**: 6.0.3.7

**Ruby version**: 2.7.2

I understand that the crossslot issue would crop up if the keys to be deleted exist across multiple slots. Hence to fix the issue, I had overridden the Rails.cache.delete_matched in my application to look like this:
```ruby
def delete_matched(matcher, options = nil)
  instrument :delete_matched, matcher do
    unless String === matcher
      raise ArgumentError, "Only Redis glob strings are supported: #{matcher.inspect}"
    end
    redis.with do |c|
      pattern = namespace_key(matcher, options)
      cursor = "0"
      # Fetch keys in batches using SCAN to avoid blocking the Redis server.
      nodes = c.respond_to?(:nodes) ? c.nodes : [c]
      nodes.each do |node|
      begin
        cursor, keys = node.scan(cursor, match: pattern, count: SCAN_BATCH_SIZE)
        # Override starts here - to avoid Redis cluster cross slot issues (delete_multi functionality is also overridden to delete the keys one at a time)
        delete_multi(keys, {:namespace=>nil}) unless keys.empty?
        # Override end
        end until cursor == "0"
      end
    end
  end
end
```
After overriding it, the cross slot error is gone, but the keys matching the regex from only one of the nodes in the cluster are removed. After some debugging, I found that the below line of code might be the cause of the issue:

```ruby
nodes = c.respond_to?(:nodes) ? c.nodes : [c]
```
The ternary operator condition is supposed to return true, so that "nodes" will be a list of redis node connections in the cluster. But the condition is returning false, and hence "nodes" is simply a list containing the original cluster connection. And the scan command scans across only one of the nodes (as expected, as scan commands do not exist for the entire cluster), and returns the keys matching the regex in that node.

How can this issue be solved so that I can use my overridden Rails.cache.delete_matched to delete the keys that match the regex in all my nodes?

Note: I can achieve it by doing a redis.keys operation for the regex, but I believe that is not a very optimal solution.

**Comment by Subramanian-ERS** [comment]
Are there any updates on this?

**Comment by p8** [comment]
@ghiculescu Do you have any idea?

**Comment by ghiculescu** [comment]
I haven't looked closely at it, I don't use Redis much for caching.

I think a good first step would be to put a draft PR up with a failing test.

**Comment by byroot** [comment]
I doubt `RedisCacheStore` really ever considered `Redis::Cluster`, as it's a relatively recent addition.

**Comment by praveen-ks** [comment]
What't is the state of this issue? I am still facing this issue.
