### ISSUE TITLE
DEPRECATION WARNING: Initialization autoloaded the constants from the app/helpers/*.rb

### ISSUE THREAD

**Issue by Obsiye** [rails/rails#42758]
Hi 👋🏾 

Setting the `config.cache_classes` to `true` in the development environment has gotten rid of Deprecation warnings we've been getting for loading app/helpers/*.rb

I was wondering if there's an alternative solution? Also, if you have an idea of what's occurring please and thank you 🙌🏾 

### Steps to reproduce

With Rails version 6 or higher do the following:
- Have some helper modules in your app/helpers/* directory e.g. module ApplicationHelper
- Set config.cache_classes to `false` in the development.rb environment.
- In your terminal, run `bin/rails about`

### Expected behavior

No Deprecation warning and the expected `bin/rails about` output of
```
About your application's environment
Rails version             6.1.4
Ruby version ...
...
```

### Actual behavior

```
DEPRECATION WARNING: Initialization autoloaded the constants ApplicationHelper, ...(the other helper files)
...
Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ApplicationHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:

    Rails.application.reloader.to_prepare do
      # Autoload classes and modules needed at boot time here.
    end

That block runs when the application boots, and every time there is a reload.
For historical reasons, it may run twice, so it has to be idempotent.

Check the "Autoloading and Reloading Constants" guide to learn more about how
Rails autoloads and reloads.
...
About your application's environment
Rails version             6.1.4
Ruby version ...
...
```
It logs into the terminal the above deprecation warning.

### System configuration
**Rails version**: 6.1.4

**Ruby version**: 2.7.1

**Comment by byroot** [comment]
This isn't a Rails bug, as stated by the deprecation warning you copied, some code in your initializers is loading some helper while it shouldn't.

You must find a way to delay this. There's no textbook answer it heavily depend on what your application is doing.
