### ISSUE TITLE
Multi-DB Config - Skip Database Management Features for certain Databases

### ISSUE THREAD

**Issue by westonganger** [rails/rails#42787]
For multi-database configs, often times I will want to just connect to another database, not manage it.

One main pain point is that all of the rake tasks affect all databases. Ie. `rake db:drop` will drop all databases. This is frustrating. Same with `schema:load`, `db:create`, `db:migrate`, and `rake db:setup`.

I am currently not aware of any option that to **disable database management features on certain databases** such as:

- Migrations
- Database Drop / Create
- Schema generation/dumping

The reason I dont just use `establish_connection` is that I am hoping to utilize the (soon-to-be) built-in AR cross-db join functionalities, amongst others.

Therefore I propose something like the following:

```ruby
development:
  primary:
    database: first
  another_read_only_database:
    database: second
    migrations: false ### or schema_management or any other good name
```

If I have missed an existing option to do this then I suspect we may need to update the rails guides or such.

**Comment by ghiculescu** [comment]
@westonganger if you mark a db as as replica using `replica: true`, maintenance tasks won't be run against it.

**Comment by ghiculescu** [comment]
This is mentioned in https://edgeguides.rubyonrails.org/active_record_multiple_databases.html#setting-up-your-application but always open to feedback on how to make it more clear.

**Comment by westonganger** [comment]
`replica` is not a great name for the option in a more generic sense. In many cases its not a replica its simply an "external database without migrations"

I would say name it `readonly` however thats not fully correct in all cases, we may still want to write to the records, just not handle the migrations and schema changes.

Would `manage_schema: false` be better?

**Comment by westonganger** [comment]
For the Rails documentation I would also like to see a Table of Contents item and Header for "Connecting to Databases without Managing Schema and Migrations" or similar

**Comment by eileencodes** [comment]
> Would manage_schema: false be better?

`replica: true` is for replicas, so if it's not a replica I don't recommend using it because that option will also enforce blocking writes. Because this is a public API changing it without deprecation is not possible, and I also don't think the name needs to change.

I do see some room for an additional feature though. I don't like the name `manage_schema` because we aren't only skipping managing the schema. How about `database_tasks: false`? You probably want to avoid seeding this DB as well as all the other tasks which is why I think `manage_schema` is too narrow. We'd accept a PR for this feature. 

> For the Rails documentation I would also like to see a Table of Contents item and Header for "Connecting to Databases without Managing Schema and Migrations" or similar

Happy to accept a PR for adding these docs as well.

**Comment by westonganger** [comment]
I've started work on this PR https://github.com/rails/rails/pull/42794. Could use help if anyone wants to assist.

**Comment by jordanmaguire** [comment]
Hey there,

For those readers who cannot update their Rails version to take advantage of the newer `database_tasks: false` option, here's a workaround that seems to work fine for me.

You can overwrite the default db:* tasks to be called only on the database of your choice.

As an example, if I want `db:create`, `db:drop`, and `db:migrate` to only run on my `primary` database, I can add a new file `lib/tasks/db_overrides.rake`, with the contents:

```ruby
["db:create", "db:drop", "db:migrate"].each do |task_name|
  Rake::Task[task_name].clear
end

namespace :db do
  task create: ["db:create:primary"]
  task drop: ["db:drop:primary"]
  task migrate: ["db:migrate:primary"]
end
```

**Comment by ghiculescu** [comment]
(closing as https://github.com/rails/rails/pull/42794 was merged)
