### ISSUE TITLE
Rails version is not being set as 6.0.3.4, but rather set as 6.0.4

### ISSUE THREAD

**Issue by amrutsabale** [rails/rails#42798]
### Steps to reproduce

```ruby

1. I installed Rails 6.0.3.4 in my system
2. Created a new application using the rails new command.
     `$ rails new demo --skip-turbolinks`
3. When I am creating the new rails app, rails v6.0.4 is automatically installed in the project and on my system.
```

### Expected behavior

Rails new project should be created with rails `v6.0.3.4`and, not  with rails `v6.0.4` 

### Actual behavior

When I am creating the new rails app, rails `v6.0.4` is automatically installed in the project and on my system.
<img width="814" alt="Screenshot 2021-07-16 at 11 43 47 AM" src="https://user-images.githubusercontent.com/41994367/125904628-d234e1eb-6a50-44ca-a7ee-34198314bc64.png">

### System configuration
**Rails version**:
  rails `v6.0.3.4

**Ruby version**:
 ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]

**Machine**
MacBook air M1 chip

**Comment by ghiculescu** [comment]
Hmmm, this doesn't seem right. That said, 6.0.4 is the latest release in the 6.0 series - is there an issue with it or did you specifically want 6.0.3.4?
