### ISSUE TITLE
Rails Guides marked as `work_in_progress` do not show up in "Guides Index" / TOC

### ISSUE THREAD

**Issue by westonganger** [rails/rails#42793]
I note that many of the Rails guides do not appear in the "Guides Index" / table of contents. For both released guides and edgeguides

The reason they do not appear in the table of contents is that these guides are marked as "work_in_progress: true"

1. Rather than not show them in the table of contents at all, I would much more prefer to have them listed along with a suffix `(WIP)`

2. Do any of the `work_in_progress: true` guides deserve to be promoted now to a real guide? One main one being "Multiple Databases with Active Record" a main feature of Rails 6. Here is the current list of wip guides.

```
"Active Model Basics",
 "Action View Overview",
 "Action View Helpers",
 "Action Mailbox Basics",
 "Action Text Overview",
 "Working with JavaScript in Rails",
 "The Rails Initialization Process",
 "Active Support Instrumentation",
 "Active Record and PostgreSQL",
 "Multiple Databases with Active Record",
 "Active Record Encryption",
 "The Basics of Creating Rails Plugins",
 "Getting Started with Engines",
 "Threading and Code Execution in Rails",
 "Version 7.0 - ?"
```

**Comment by zzak** [comment]
AFAIK this was intentional to avoid users from finding incomplete guides that may have bugs in them. Since this could lead to confusion, and even more bug reports.

**Comment by p8** [comment]
If I search for "Active Model guide" the guide ends up in the result:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/28561/126639326-e1a20e22-29b9-4c40-b976-ab11864a315a.png">
https://duckduckgo.com/?t=ffsb&q=activemodel+guide+rails&ia=web

But there is no mention of it being WIP in the guide itself.
Maybe we should add a warning to the guides as well, just like on the index:
> This guide is currently being worked on and will not be available in the Guides Index menu. While still useful, it may contain incomplete information and even errors. You can help by reviewing them and posting your comments and corrections.

**Comment by p8** [comment]
There was a previous discussion on this, although from 6 years ago:
https://github.com/rails/rails/pull/19593#issuecomment-88226002

**Comment by zzak** [comment]
@p8 I thought there used to be a banner that showed when a guide was still WIP. 🤔

**Comment by sedubois** [comment]
This issue still occurs. E.g. the Action Text guide is not available from the menu, even though it is quite useful and I was expecting to find it in the navigation.
