### ISSUE TITLE
"Blocked host" error message shown in production by default

### ISSUE THREAD

**Issue by georgeclaghorn** [rails/rails#42813]
<img width="1029" alt="Screen Shot 2021-07-19 at 12 26 25 PM" src="https://user-images.githubusercontent.com/94129/126194468-b57defdf-de2b-40e3-af76-cbf948a1867b.png">

We probably shouldn’t be showing detailed error messages like this in production. We can render a blank 403 Forbidden response unless the request is local (and write a message to the log, where administrators of production apps look to troubleshoot issues).

**Comment by ajaxm** [comment]
@georgeclaghorn @p8 
I took a crack at this with PR #42828 (my first attempt at a rails contribution!), lmk your thoughts.
