### ISSUE TITLE
Action cable doesn't work when reload_classes_only_on_change is set to false

### ISSUE THREAD

**Issue by tayyab-on-toptal** [rails/rails#42816]
### Steps to reproduce

1. Create an API only application 
2. Make an ActionCable channel and subscribe to it on the front end
3. Try establishing a connection and communicating with it. It works fine.
4. Set reload_classes_only_on_change in `config/development.rb` to false.
5. Restart the server.
6. Try communicating with it now.

### Expected behavior
It should work.

### Actual behavior
it does not work.

### System configuration
**Rails version**:
6.0.0

**Ruby version**:
2.6.6

**Comment by p8** [comment]
Hi @tayyab-on-toptal thanks for reporting the issue.

This is documented behaviour (but maybe it should be added to the Action Cable guide as well):
> Action Cable uses the Executor instead: because a Cable connection is linked to a specific instance of a class, it's not possible to reload for every arriving WebSocket message. Only the message handler is wrapped, though; a long-running Cable connection does not prevent a reload that's triggered by a new incoming request or job. Instead, Action Cable uses the Reloader's before_class_unload callback to disconnect all its connections. When the client automatically reconnects, it will be speaking to the new version of the code.
https://edgeguides.rubyonrails.org/threading_and_code_execution.html#framework-behavior

See also this rejected PR and the discussion: https://github.com/rails/rails/pull/33469

**Comment by ghiculescu** [comment]
I'm going to close this per https://github.com/rails/rails/pull/33469, but an update to the docs to make it more clear would make for a great PR.
