### ISSUE TITLE
Security guide doesn’t cover host authorization/DNS rebinding protection

### ISSUE THREAD

**Issue by georgeclaghorn** [rails/rails#42817]
Action Dispatch comes with host authorization, a security feature that can be enabled in production by populating `config.hosts`. The DNS rebinding attacks it protects against aren’t covered in [the security guide](https://edgeguides.rubyonrails.org/security.html). The guide should cover the relevant security issues, how to protect against them at the app level with `config.hosts`, and how reverse proxies and load balancers like Nginx sometimes protect against them already.

**Comment by p8** [comment]
The configuration guides partly cover it. 
https://edgeguides.rubyonrails.org/configuring.html#configuring-middleware
We could link to it or copy some things.
The original PR has a lot of background information for anyone that wants to work on this: https://github.com/rails/rails/pull/33145

**Comment by vishaldeepak** [comment]
Im wiling to give this a try. Can I be assigned?

**Comment by ghiculescu** [comment]
Go ahead and make a PR 👍

**Comment by TopDogIRE** [comment]
Hi, I'd like to be given a chance to solve this!
