### ISSUE TITLE
Rails render json: @objects does not call overridden to_json method.

### ISSUE THREAD

**Issue by mofmn** [rails/rails#42835]
I have overriden the user models to_json / as_json methods to avoid accidentally providing undesirable information to the page, so if you call render json: users, it wont start handing out their emails or other sensitive information. Unfortunately this only works as expected if i use render json: users.to_json, the docs claim that the to_json method will be called but it does not seem to be the models overridden version of to_json. 

this is running rails 6.1.3.2 with Sequel ORM so Active Model serialization is a no go, Rails docs claim to use the to_json method at section 2.2.8 in https://guides.rubyonrails.org/v5.1/layouts_and_rendering.html

**Comment by casperisfine** [comment]
`to_json` is indeed called, as this repro script proves it:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "6.1.3.2"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class CustomObject
  def to_json(_options = nil)
    '"#to_json"'
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render json: CustomObject.new
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
    assert_equal '"#to_json"', last_response.body
  end

  private
    def app
      Rails.application
    end
end
```

```
Finished in 0.602669s, 1.6593 runs/s, 3.3186 assertions/s.
1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

So either it's a problem with your code, or either you didn't include enough information for us to reproduce.

I'll be closing this issue, but I'll happily re-open if you can provide a reproduction script that demonstrate the issue.
