### ISSUE TITLE
ActionMailer fails to create correct multipart message with rfc822 attachment

### ISSUE THREAD

**Issue by der-flo** [rails/rails#42849]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem 'rails', github: 'rails/rails', branch: 'main'
end

require 'minitest/autorun'
require 'action_mailer/railtie'

class TestMailer < ActionMailer::Base
  def main
    message_to_attach =  <<~MAIL.gsub(/\n/, "\r\n")
      Message-ID: <12345@foo.example>
      Subject: Test
      From: test1@foo.example
      To: test2@foo.example
      
      hello world
    MAIL
    attachments['test.eml'] = {
      mime_type: params[:mime_type],
      content: message_to_attach
    }

    mail(from: 'test3@foo.example', to: 'test4@foo.example', subject: 'Test outer') do |format|
      format.text { "outer text - #{params[:mime_type]} attachment" }
    end
  end
end

class BugTest < Minitest::Test
  def test_with_plain_mime_type
    message = TestMailer.with(mime_type: 'text/plain').main
    assert_equal message.mime_type, 'multipart/mixed'
  end

  def test_with_rfc822_mime_type
    message = TestMailer.with(mime_type: 'message/rfc822').main
    assert_equal message.mime_type, 'multipart/mixed'
  end
end
```

The second test fails, the message object is rendered as follows:
```
Date: Fri, 23 Jul 2021 13:59:19 +0200
From: test3@foo.example
To: test4@foo.example
Message-ID: <60faaf1738a02_14fbd98-3fb@flo.adigi.ai.mail>
Subject: Test outer
Mime-Version: 1.0
Content-Type: text/plain;
 boundary="--==_mimepart_60faaf1738008_14fbd98-484";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_60faaf1738008_14fbd98-484
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

outer text - message/rfc822 attachment
----==_mimepart_60faaf1738008_14fbd98-484
Content-Type: message/rfc822
Content-Transfer-Encoding: 
Content-Disposition: attachment;
 filename=test.eml
Content-ID: <60faaf1739102_14fbd98-2b@flo.adigi.ai.mail>

Message-ID: <12345@foo.example>
Subject: Test
From: test1@foo.example
To: test2@foo.example

hello world

----==_mimepart_60faaf1738008_14fbd98-484--

```

### Expected behavior

The `message.mime_type` is `multipart/mixed` in both test cases. ActionMailer handles attachments in the way it is described in https://guides.rubyonrails.org/action_mailer_basics.html#adding-attachments describes.

### Actual behavior

When attaching a `message/rfc822` - an email message - the generated mail parts are not nested correctly, the outer `multipart/mixed` is missing.

Perhaps this behaviour is caused by the [special handling](https://github.com/mikel/mail/blob/master/lib/mail/attachments_list.rb#L9) of such attachments in the `mail` gem.

### System configuration
**Rails version**: master

**Ruby version**: 3.0.2

**Comment by brianknight10** [comment]
I am happy to address

**Comment by brianknight10** [comment]
There is an open PR for the `mail` gem that appears to address this problem (see https://github.com/mikel/mail/pull/1389).

I've inquired into why it hasn't been merged, and have developed some tests in Rails to validate that it behaves as expected. Waiting for the response before deciding the way forward.

**Comment by ghiculescu** [comment]
Can (should?) this be fixed in Rails? If not then I think we should close this in favour of https://github.com/mikel/mail/pull/1389

**Comment by der-flo** [comment]
> Can (should?) this be fixed in Rails? If not then I think we should close this in favour of [mikel/mail#1389](https://github.com/mikel/mail/pull/1389)

Imho Rails is somewhat responsible for the functionality it provides via incorporated libraries.
Especially in this case where Rails orchestrates the multipart message and provides a opinionated approch to attachments, which a generally like.

Perhaps the respectable Rails (core) contributors have a special connection with @mikel so that he can have a look at the PR soon.

**Comment by der-flo** [comment]
BTW: The tests above work with the pull request and also our production code seems to like the changes.

**Comment by ahorek** [comment]
there wasn't any release for 3 years and none of 2 existing maintainers seem to be interested anymore, see https://github.com/mikel/mail/issues/1391

It would be great if the Rails team could maintain it, the gem is an essential part of the Action Mailer. Maybe a fork is the only option to move things forward :-(

**Comment by der-flo** [comment]
Another aspect I ran into yesterday: Referencing attachments can get tricky.

I circumvent the original problem by adding a dummy attachment before adding the RC822 message:

```ruby
attachments['sp'] = { mime_type: 'text/plain', content: '.' } if attachments['sp'].blank?
[…]
attachments['test.eml'] = { mime_type: %(message/rfc822; name="test.eml"), content: message.to_s }
```
This somewhat works for adding itself but leads to more glitches.

Unfortunately the `attachments#[]` reader also provides the attachments of the inner message (eg. `test.eml`). Suppose this inner message contains the some inline images (attachments) and the same are added (via `attachments#[]=`) again to the outer message later on, referencing them with `attachments#[]` in eg. the view returns the `first`, the wrong attachment for this use case. MUAs fail displaying these images. This use case  is not so uncommon in a "reply to a reply" situation.

I somewhat fixed this with a very hacky monkey patch of `#attachments`:
```ruby
class MyMailer < ApplicationMailer
  def attachments
    message_to_search_in = @_message
    super.tap do |original|
      original.define_singleton_method(:[]) do |index_value|
        if index_value.is_a?(Integer)
          super
        else
          message_to_search_in.parts.select(&:attachment?).find { |a| a.filename == index_value }
        end
      end
    end
  end
end
```

I'm not sure whether [mikel/mail#1389](https://github.com/mikel/mail/pull/1389) attacks this.

**Comment by der-flo** [comment]
Thank you @rails-bot. I can confirm this problem still exists in `6-1-stable` and `main`.

**Comment by der-flo** [comment]
Is there anything I can do to support resolving this issue?

**Comment by der-flo** [comment]
Thanks again @rails-bot! I can confirm this problem still exists in `7-0-stable` and `main`.

**Comment by der-flo** [comment]
Thanks again @rails-bot! I can confirm this problem still exists in `7-0-stable` and `main`.

**Comment by der-flo** [comment]
I cannot re-open this issue so I created a new one: #45691
