### ISSUE TITLE
Path helpers can be generated for namespace rather than a specific endpoint

### ISSUE THREAD

**Issue by glasserc** [rails/rails#42841]
### Steps to reproduce
I've created a simple Rails application for the sake of debugging which has the following `config/routes.rb`:

```
Rails.application.routes.draw do
  namespace :ethan_is_cool do
    scope path: "/:message" do
      get "/go_big", to: "transformations#uppercase"
    end
    get "/profile", to: "profile#index"
    get "/users/:id", to: "users#show"
  end
end
```

### Expected behavior

Helpers would be generated for certain endpoints within the namespace, prefixed by `ethan_is_cool_`, for example `ethan_is_cool_profile_path` for `profile#index`. It would be obvious which endpoint corresponded to which helper.

### Actual behavior

An `ethan_is_cool` route appears to be generated. `rails routes --grep ethan_is_cool` shows:

```
               Prefix Verb URI Pattern                              Controller#Action
 ethan_is_cool_go_big GET  /ethan_is_cool/:message/go_big(.:format) ethan_is_cool/transformations#uppercase
ethan_is_cool_profile GET  /ethan_is_cool/profile(.:format)         ethan_is_cool/profile#index
        ethan_is_cool GET  /ethan_is_cool/users/:id(.:format)       ethan_is_cool/users#show
```

```
irb(main):001:0> Rails.application.routes.url_helpers.ethan_is_cool_path(id: 1)
=> "/ethan_is_cool/users/1"
```

This behavior is different from what happens if you unwrap the `namespace` call -- in this case, no helper is generated for this route, as expected.

This behavior is also different from what happens if you replace the `scope` call with the presumably-equivalent `get "/:message/go_big", to: "transformations#uppercase"`. In this case, an `ethan_is_cool_path` helper is generated but it points to the `go_big` route rather than the `users` route. The effect is that this refactor breaks any use of the `ethan_is_cool_path` helper as well as the `ethan_is_cool_go_big_path` helper. (Of course, if you also unwrap the `namespace` call, no helper is generated for either route). 

Additionally, I had a really hard time figuring out whether this behavior was expected or not. https://guides.rubyonrails.org/routing.html emphasizes resourceful routing and there is no overall explanation of what circumstances helpers are generated in or what controls them. I learned from a co-worker a rule of thumb that they are generated from the path (not the controller, action or method) and typically not generated when there are dynamic segments in the path. A paragraph or two on that document, or another document if it makes more sense, would be very helpful to learners like me.

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.7.1p83

**Comment by richiethomas** [comment]
Noob Rails contributor here.  I reproduced the example Rails app on my local and verified that the same routes as above are created.  Next I'm trying to clarify the expected behavior for each of the 3 paths in your list of routes.

Is it just the last of these path helpers (i.e. `ethan_is_cool` => `GET  /ethan_is_cool/users/:id(.:format)`) which is surprising, or is it all 3?  If the helpers were as unsurprising as possible, what form would they each take?

**Comment by glasserc** [comment]
I'm also pretty new to Rails so my opinion may not be valuable, but based on my co-worker's comment, I would not expect a helper for the first or last route, and the second route's helper is fine as it is.

**Comment by richiethomas** [comment]
In that case, I guess our expectations differ.  The path helpers for 1 and 2 look OK to me, but I'd expect the 3rd helper to be `ethan_is_cool_user_path`.  I'd expect this based on the fact that, when I replace `get "/users/:id", to: "users#show"` with `resources :users`, the path helper I see generated for `/ethan_is_cool/users/:id` is `ethan_is_cool_user_path`.  I'm not sure I'd expect the generated helper to be any different when circumventing the `resources` route helper.  Some relevant documentation exists [here](https://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing).

If only for my own edification, I'll dig around the source code and try to see why the behavior differs between `resources :users` vs. `get "/users/:id", to: "users#show"`.

**Comment by richiethomas** [comment]
In the meantime, if this is a blocker for you then it looks like you can use the `:as` keyword to manually set up the helper path to be what you want.  For example, the following produces `ethan_is_cool_user_path` for me:

```
namespace :ethan_is_cool do
    get "/users/:id", to: "users#show", as: "user"
end
```

I can't speak for the core team, but it's possible that using `as:` might even be the recommended / conventional solution when circumventing `resource` and `resources` in this manner.

**Comment by glasserc** [comment]
To be honest, I care more about the absence of `ethan_is_cool_path` (which I think is misleading) than about any specific route for the `users` path.

Yes, it's true that I could use `as` to "cover up" the misleading route, but it's a little bit of a footgun since other routes could "inherit" the name or another endpoint could be added later that reintroduces the misleading name.

I think the observation that `resource` and `resources` are normalized or preferred is an interesting one. The documentation says in [section 3](https://guides.rubyonrails.org/routing.html#non-resourceful-routes) that "While you should usually use resourceful routing, there are still many places where the simpler routing is more appropriate." My reading of this is that non-resourceful routing is of equal status with resourceful routing. I am open to the possibility that the problem is my understanding, but in that case I would request that the documentation be clarified.

**Comment by glasserc** [comment]
This behavior is the same in `rails` from `main` (`7.1.0.alpha`).
