### ISSUE TITLE
The application.scss not re-complier when import file get change

### ISSUE THREAD

**Issue by jubilee2** [rails/rails#42851]
### Expected behavior

1. new app
2. create test page
``` bash
rails generate controller Greetings hello
```
app/views/greetings/hello.html.erb
``` html
<h1>Greetings#hello</h1>
<p class='test'>Find me in app/views/greetings/hello.html.erb</p>
```
change the application.css > application.scss
then remove all lines replace by following 1 line
```scss
@import 'greetings.scss';
```
app/assets/stylesheets/greetings.scss
```scss
.test {
    color: blue;
}
```
3. go to url of /greetings/hello we see blue words
4. change app/assets/stylesheets/greetings.scss
```scss
.test {
    color: red;
}
```
5. go to url of /greetings/hello we see red words

### Actual behavior
5. go to url of /greetings/hello we still see blue words

### System configuration
**Rails version**:
6.1.4
**Ruby version**:
2.7.2

**Comment by lfalcao** [comment]
@jubilee2 here worked fine.

Rails 6.1.4 and Ruby 3.0.0p0

**Comment by jubilee2** [comment]
it is update with
#application.scss
``` 
 *= require_tree .
 *= require_self
```

but not work with
#application.scss
```
@import 'greetings.scss';
```

i tested in Rails 6.0.4 and Ruby 2.6.3 on my local machine tonight
