### ISSUE TITLE
Aliases for polymorphic associations like delegated types

### ISSUE THREAD

**Issue by mansakondo** [rails/rails#42868]
I wanted to know if there's a particular reason why aliases for polymorphic associations (like delegated types) isn't implemented.

**Comment by ghiculescu** [comment]
Can you give an example of what's missing? Chances are it is because nobody has implemented it. [You should!](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-code)

**Comment by mansakondo** [comment]
Basically i'd like to be able to declare polymorphic associations like this:
```ruby    
# app/models/comment.rb    
class Comment < ApplicationRecord    
  belongs_to :commentable, polymorphic: true, types: %w( Post Picture )    
end    
    
# app/models/post.rb    
class Post < ApplicationRecord    
  has_many :comments, as: :commentable    
end    
    
# app/models/picture.rb    
class Picture < ApplicationRecord    
  has_many :comments, as: :commentable    
end
```
And access them through aliases that way:
```ruby
post    = Post.new(title: "Polymorphic Aliases", content: "...")
picture = Picture.new(legend: "Here's my code.", url: "https://avatars.githubusercontent.com/u/47113995?v=4")

comment_from_post    = Comment.new(content: "...", commentable: post)
comment_from_picture = Comment.new(content: "...", commentable: picture)

comment_from_post.post.title
# => "Polymorphic Aliases"

comment_from_picture.picture.legend
# => "Here's my code."

comment_from_post.picture
# => undefined method `picture'

comment_from_picture.post
# => undefined method `post'
```

**Comment by mansakondo** [comment]
I'll try to implement it. I'll start with a rough draft to get some feedback.

**Comment by georgeclaghorn** [comment]
What’s the difference between this and delegated types? Which part of the desired behavior isn’t provided by delegated types?

**Comment by mansakondo** [comment]
> What’s the difference between this and delegated types? Which part of the desired behavior isn’t provided by delegated types?

Delegated types are for when you want to use a sort of "multi-table inheritance". Here I just want to add the same behaviour for simple polymorphic associations.

**Comment by intrip** [comment]
@mansakondo From my understanding delegated types [are just an extension to polymorphic associations](https://github.com/rails/rails/blob/d7c0b4542c2ad8e74df111bcfceb0716a0d1b90c/activerecord/lib/active_record/delegated_type.rb#L191-L194), from what I see in your request what you need is exactly a delegated_type.

**Comment by mansakondo** [comment]
> @mansakondo From my understanding delegated types [are just an extension to polymorphic associations](https://github.com/rails/rails/blob/d7c0b4542c2ad8e74df111bcfceb0716a0d1b90c/activerecord/lib/active_record/delegated_type.rb#L191-L194), from what I see in your request looks like what you need can be achieved by using a delegated_type.
> 
> Anyways you made already a PR to follow up so I wouldn't bother you here

Hey @intrip. From my understanding, delegated types aren't just an extension for polymorphic associations but a alternative to single-table inheritance. So I think that the use cases are different.

Let's look at this piece code from the doc:
```ruby
# Schema: entries[ id, account_id, creator_id, created_at, updated_at, entryable_type, entryable_id ]
class Entry < ApplicationRecord
  belongs_to :account
  belongs_to :creator
  delegated_type :entryable, types: %w[ Message Comment ]
end

module Entryable
  extend ActiveSupport::Concern

  included do
    has_one :entry, as: :entryable, touch: true
  end
end

# Schema: messages[ id, subject, body ]
class Message < ApplicationRecord
  include Entryable
end

# Schema: comments[ id, content ]
class Comment < ApplicationRecord
  include Entryable
end
```
Here's what it says in the doc: 

> As you can see, neither Message nor Comment are meant to stand alone. Crucial metadata for both classes resides in the Entry “superclass”. But the Entry absolutely can stand alone in terms of querying capacity in particular.

But in this code, `Album` and `Restaurant` aren't dependent of `Review`, they're just associated objects:
```ruby
# app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :reviewable, polymorphic: true, types: %w( Album Restaurant )
end

# app/models/album.rb
class Album < ActiveRecord::Base
  has_many :reviews, as: :reviewable
end

# app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, as: :reviewable
end
```

**Comment by intrip** [comment]
I understand your point, I just wanted to say what `delegated_type` does from just checking the current implementation.

**Comment by mansakondo** [comment]
I see. srry @intrip I've misunderstood you, my bad :)

**Comment by nerlichman** [comment]
Hey @mansakondo I know it's been a long while, but I just read this issue.

I wanted to achieve the same as you a while ago and built this gem [safe_polymorphic](https://github.com/gogrow-dev/safe_polymorphic)

**Comment by sandstrom** [comment]
For reference, Mongoid has implemented something in this direction:

```ruby
module Engineering
  class Department
    include Mongoid::Document
    
    # Ensures Mongoid uses 'dept' in the _type field instead of 'Engineering::Department'
    identify_as 'dept'
  end
end
```

https://www.mongodb.com/docs/mongoid/current/api/Mongoid/Identifiable.html
