### ISSUE TITLE
Wrap LocalCache around ActiveJob's

### ISSUE THREAD

**Issue by chaffeqa** [rails/rails#42875]
I've been looking at the source to see if this is already being done and can't find it anywhere.  Proposal is:

Wrap `ActiveSupport::Cache::Strategy::LocalCache.with_local_cache` around `ActiveJob.perform`.

Seems like it should be fairly straightforward, and may introduce nice performance wins.  Happy to assist if this makes sense!

**Comment by ghiculescu** [comment]
@byroot wdyt? Assuming you don't intend to remove local cache anymore, I think this is a good idea. @chaffeqa would you be interested in making a PR?

**Comment by byroot** [comment]
> Assuming you don't intend to remove local cache anymore

Yeah, I think it's still useful, even though not as much. I don't see a reason why it wouldn't be enabled in Active Job

**Comment by ghiculescu** [comment]
@chaffeqa I'm going to close this as it's technically not an issue (but a feature proposal). That said, please consider making a PR, I think it would be a great feature to add to Active Job!
