### ISSUE TITLE
ActiveModel Errors - display detailed related model errors

### ISSUE THREAD

**Issue by ltickett** [rails/rails#42883]
### Steps to reproduce

I'm working on the GitLab project, where we have the concept of `Issues`. An issue can have many `Timelogs`. 

If I create an invalid timelog and check the `issue.errors` I get a rather unhelpful `attribute=timelogs, type=invalid`

But if I check the `timelog.errors` I get a helpful `summary, type=too_long`

```ruby
pry(main)> i = Issue.first
=> #<Issue id:1 gitlab-org/gitlab-test#1>
pry(main)> i.timelogs.create(time_spent: 600, summary: "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz")
=> #<Timelog:0x000055c4cfdc5a70
 id: nil,
 time_spent: 600,
 user_id: nil,
 created_at: nil,
 updated_at: nil,
 issue_id: 1,
 merge_request_id: nil,
 spent_at: nil,
 note_id: nil,
 project_id: nil,
 summary:
  "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz">
pry(main)> i.errors.errors
=> [#<ActiveModel::Error attribute=timelogs, type=invalid, options={}>]
pry(main)> i.timelogs.first.errors.errors
=> [#<ActiveModel::Error attribute=user, type=blank, options={}>, #<ActiveModel::Error attribute=summary, type=too_long, options={:count=>255}>]
```

Can we create an "out of the box mechanism" to view all of the detailed errors?

I started building something, but realised:

* i'm not qualfied for the job
* there is likely already a way of doing it, I just don't know how

Forgive the duplication- but I previously posted on SO: https://stackoverflow.com/questions/68522570/get-hash-of-activerecord-errors-including-nested-children-relations-etc?noredirect=1#comment121124779_68522570
And have also created an issue in the GitLab project: https://gitlab.com/gitlab-org/gitlab/-/issues/336970

But this feels like something that should be available natively?

Thanks!

```ruby
# Your reproduction script goes here
```

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.7.2

**Comment by intrip** [comment]
@ltickett feature request is something which requires evaluation from the Rails core team so I can't help you in that sense.

If can help `i.timelogs.create` returns the actual `timelog` so you can check for the record being persisted:

```ruby
errors = []
create_timelog = i.timelogs.create(time_spent: 600, summary: "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz")
unless create_timelog.persisted?
  errors << create_timelog.errors.full_messages 
end
```

**Comment by ltickett** [comment]
Thanks for the quick reply @intrip 

I think you can see from my notes that I'm able to get that information (via several means). 

This issue is more about ​trying to understand why there isn't a generic mechanic to get the detailed validation messages from a model and all of it's attributes?

And  I guess  understand the appetite to create one?

Feel free to ping me if it would be beneficial to have a chat (I may not be articulating myself very well here :)

**Comment by intrip** [comment]
Looping to @zzak and @p8. Hopefully they have something to add.

**Comment by ltickett** [comment]
I have made a little progress... it appears enabling `autosave: true` using `accepts_nested_attributes_for` causes the validation errors to bubble up perfectly.

The rough explanation I've been given/interpreted is: Without these options enabled there is only partial support for working with related models (e.g. creating new ones should work, but updating existing ones is likely not to).

This makes a little bit of sense, and deliberately calling out that the parent model `accepts_nested_attributes_for` or should `autosave` seems like a good idea.

That being said, it still seems like it should not be necessary. If the model validation already identifies the related model as being invalid, why can't it go that step further and give the verbose/detailed error?

**Comment by lulalala** [comment]
As my colleague has pointed out, `autosave`  is required for for the following to work, and I was quite surprised by this:

```
## When autosave is true on the association
>> i = Issue.last
>> t = i.timelogs.build
>> i.valid?
=> false
>> i.errors.messages
=> {:"timelogs[0].time_spent"=>["can't be blank"], :"timelogs[0].user"=>["can't be blank"]}

## When autosave is not set on the association
>> i = Issue.last
>> t = i.timelogs.build
>> i.valid?
=> false
>> i.errors.messages
=> {:timelogs=>["is invalid"]}
```

I think the core issue would be the lack of documentation on this feature (especially on Rails Guides). If there is a section dedicated to `index_errors`, we can then state that it is a feature which is closely associated with `save`. Any use of it outside of this context (e.g. my example above) would mean it does not work.

**Comment by ltickett** [comment]
From digging, I suspect this is the code which is responsible for the vague `is invalid` messages: https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/activerecord/lib/active_record/validations/associated.rb#L6

I've not found where/how the path differs when `autosave`/`accepts_nested_attributes_for` is enabled yet...

**Comment by p8** [comment]
@ltickett You are probably looking for this method:
https://github.com/rails/rails/blob/main/activerecord/lib/active_record/autosave_association.rb#L327-L330

**Comment by ltickett** [comment]
I posted an update on the GitLab issue recently when I came across another scenario where it'd've been super helpful: https://gitlab.com/gitlab-org/gitlab/-/issues/336970#note_715519217

I just experienced another occurrence of this working on `app/services/issues/set_crm_contacts_service.rb`

I tested `accepts_nested_attributes_for` but unfortunately the error still wasn't quite good enough:

```
1) Issues::SetCrmContactsService#execute when user has permission when the contact does not exist returns expected error response
     Failure/Error: expect(response.message).to match_array([something_went_wrong])
     
       expected collection contained:  ["Something went wrong. One or more issue customer relations contacts may not have been updated."]
       actual collection contained:    ["Issue customer relations contacts contact must exist"]
       the missing elements were:      ["Something went wrong. One or more issue customer relations contacts may not have been updated."]
       the extra elements were:        ["Issue customer relations contacts contact must exist"]
```

Adding `index_errors: true` just provides the "position" of the relational record, where I would like to see the id/pk:

```
1) Issues::SetCrmContactsService#execute when user has permission when the contact does not exist returns expected error response
     Failure/Error: expect(response.message).to match_array([something_went_wrong])
     
       expected collection contained:  ["Something went wrong. One or more issue customer relations contacts may not have been updated."]
       actual collection contained:    ["Issue customer relations contacts[0] contact must exist", "Issue customer relations contacts[1] contact must exist"]
       the missing elements were:      ["Something went wrong. One or more issue customer relations contacts may not have been updated."]
       the extra elements were:        ["Issue customer relations contacts[0] contact must exist", "Issue customer relations contacts[1] contact must exist"]
```

My manual technique generates:

```
1) Issues::SetCrmContactsService#execute when user has permission when the contact does not exist returns expected error response
     Failure/Error: expect(response.message).to match_array([something_went_wrong])
     
       expected collection contained:  ["Something went wrong. One or more issue customer relations contacts may not have been updated."]
       actual collection contained:    ["Issue customer relations contacts [\"Contact 2147483647: Contact must exist\", \"Contact 2147483646: Contact must exist\"]"]
       the missing elements were:      ["Something went wrong. One or more issue customer relations contacts may not have been updated."]
       the extra elements were:        ["Issue customer relations contacts [\"Contact 2147483647: Contact must exist\", \"Contact 2147483646: Contact must exist\"]"]
``
