### ISSUE TITLE
Multi-tenant/multi-database Proposition

### ISSUE THREAD

**Issue by chaffeqa** [rails/rails#42900]
## Problem

* One database per tenant
* 2500 tenants
* Requests and background jobs generally only address one tenant
* Same schema per tenant
* x2 "global" databases
* Each tenant database config resides in table of one of those global databases

## Current Solution

* Hack rails connection resolver and create/teardown a connection pool per transaction (set current connection on a class variable)
* Not threadsafe, use single threaded model
* Must connect/disconnect every request

## Proposed Solution

* Support multiple connection pools existing at the same time
* If memory is a problem, implement some reaping logic:
* ex: if over 500 connections, attempt to reap (allow to be garbage collected) connections that are not in use + haven't been used in last 30 seconds
* If memory is a problem, allow connection pools to be "lazy initialized" (added to the collection of pools when first seen)

## Proposition

Up until Rails 6.1 and a lot of the horizontal DB work appearing, we have had little hope of working this into Rails core itself, and have kept it mostly our hack.

But the big additions of `shards` and propositions like https://github.com/rails/rails/pull/38721 I feel Rails is actually very close to being able to implement a solution organically that meets our needs!

I would love to:
1. Talk to whoever has any further questions / insight into implementation theories
2. Contribute in any way possible to the solution residing in Rails

I have some ideas of where to start, happy to share!

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.

**Comment by rafaelfranca** [comment]
But in general, it is easier to you to open a PRs so we can discuss over working code than trying to discuss ideas without working code.

**Comment by chaffeqa** [comment]
Excellent I'll take that approach! Sorry should have searched more for the proper channel for this!

**Comment by chaffeqa** [comment]
Looks like the closest solution is the gem explained https://github.com/rails/rails/issues/50120

I think there still is room to improve here, but using the discussion board is a better place

**Comment by zgid123** [comment]
Do we have a discussion already? I wanna know if we have a solution for this one or not. Because the connection that we added at runtime usually kicked out of the pool if it takes too long
