### ISSUE TITLE
`ActiveStorage::Attached::Changes::CreateOne#upload` doesn't support `Rack::Test::UploadedFile`s initialized with `StringIO` contents

### ISSUE THREAD

**Issue by noon-ng** [rails/rails#42927]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~>6.1.0"
  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_one_attached :profile
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_uploaded_file_with_string_io_contents
    user = User.create!(
      profile: Rack::Test::UploadedFile.new(
        StringIO.new("dummy"),
        original_filename: "dummy.txt"
      )
    )

    assert_equal "dummy", user.profile.download
  end

  def test_uploaded_file_with_file_contents
    dummy_file_path = "#{Dir.tmpdir}/dummy.txt"
    File.open(dummy_file_path, "w+") { |file| file << "dummy" }

    user = User.create!(profile: Rack::Test::UploadedFile.new(dummy_file_path))

    assert_equal "dummy", user.profile.download

    File.unlink(dummy_file_path)
  end
end
```

### Expected behavior
Both tests should pass.

### Actual behavior
Only `test_uploaded_file_with_file_contents` passes; `test_uploaded_file_with_string_io_contents` errors out with the following stacktrace:

```
Error:
BugTest#test_uploaded_file_with_string_io_contents:
NoMethodError: private method `open' called for #<StringIO:0x00007f9157be4b38>
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-test-1.1.0/lib/rack/test/uploaded_file.rb:47:in `public_send'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-test-1.1.0/lib/rack/test/uploaded_file.rb:47:in `method_missing'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activestorage-6.1.4/lib/active_storage/attached/changes/create_one.rb:58:in `find_or_build_blob'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activestorage-6.1.4/lib/active_storage/attached/changes/create_one.rb:20:in `blob'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activestorage-6.1.4/lib/active_storage/attached/changes/create_one.rb:12:in `initialize'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activestorage-6.1.4/lib/active_storage/attached/model.rb:65:in `new'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activestorage-6.1.4/lib/active_storage/attached/model.rb:65:in `profile='
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activemodel-6.1.4/lib/active_model/attribute_assignment.rb:49:in `public_send'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activemodel-6.1.4/lib/active_model/attribute_assignment.rb:49:in `_assign_attribute'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.4/lib/active_record/attribute_assignment.rb:21:in `block in _assign_attributes'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.4/lib/active_record/attribute_assignment.rb:13:in `each'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.4/lib/active_record/attribute_assignment.rb:13:in `_assign_attributes'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activemodel-6.1.4/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.4/lib/active_record/core.rb:510:in `initialize'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.4/lib/active_record/inheritance.rb:72:in `new'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.4/lib/active_record/inheritance.rb:72:in `new'
    /Users/ngc/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-6.1.4/lib/active_record/persistence.rb:54:in `create!'
    active_storage_gem.rb:58:in `test_uploaded_file_with_string_io_contents'
```

### System configuration
**Rails version**:
6.1.4

**rack-test version**:
1.1.0

**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]

**Comment by ghiculescu** [comment]
Thanks for the report, looks like https://github.com/rails/rails/blob/c3664b0c2b509fc0a47929f42afbd716959c8f4c/activestorage/lib/active_storage/attached/changes/create_one.rb#L58 is the culprit. Do you have any idea what the fix would be?

**Comment by noon-ng** [comment]
Thanks for taking a look @ghiculescu.

That is indeed where the issue lies, but I'm still wondering what a good fix (ie. fits the overall Rails design and is resilient to change on `rack-test`'s side) for this would be.

`UploadedFile` delegates every call to its underlying `@tempfile` - a `StringIO` instance in the failing case -  and doesn't provide anything to encapsulate it so that `.open` would work regardless.

The most elegant solution I can think of would be if there's a method that can be called on either `StringIO` or `File`. In the former case it'd return a corresponding file (or `Tempfile`?). In the latter case, it'd be an identity. But I couldn't find anything.

Alternatively, one can check for the type of `tempfile`, since it's part of the public interface, and react accordingly (ie. `.open` if it's a file _or_ write a `Tempfile` and open that instead). That could be extracted to its own unit to wrap away this `UploadedFile` quirk. But at that point I'm wondering if I should raise this issue against https://github.com/rack/rack-test instead 😅

**Comment by ghiculescu** [comment]
I'm not seeing an elegant solution inside Rails, I think making an issue or PR against `rack-test` is a pretty good idea.

**Comment by ghiculescu** [comment]
The best Rails solution I see is splitting up this `when` statement into two branches https://github.com/rails/rails/blob/c3664b0c2b509fc0a47929f42afbd716959c8f4c/activestorage/lib/active_storage/attached/changes/create_one.rb#L56

But even then you have to handle the `Rack::Test::UploadedFile` option differently based on if it's a StringIO or a real file. So you are basically adding two code paths.

**Comment by noon-ng** [comment]
> splitting up this when statement into two branches

Yeah... that's precisely what I was hoping to avoid. :)

I'm going to spike something to abstract away the StringIO on `rack-test` and see how it looks. Hopefully it fixes the error without breaking compatibility -- if I pull that off I'll PR it against `rack-test` then... close this issue?

**Comment by ghiculescu** [comment]
> if I pull that off I'll PR it against `rack-test` then... close this issue?

Yep, sounds good 👍
