### ISSUE TITLE
Add drop table migration on model delete instead of removing creation migration

### ISSUE THREAD

**Issue by coder2000** [rails/rails#42920]
### Steps to reproduce

1. Create a model
2. Migrate database
3. Delete model

```ruby
# Your reproduction script goes here
```

### Expected behavior

Migration should be created to drop table from database instead of deleting the migration to create the table. Removing the create table migration can cause issues with migrations run after model removal.

### Actual behavior

Migration to create table is deleted

### System configuration
**Rails version**: 6.1.4

**Ruby version**: 3.0.2

**Comment by ghiculescu** [comment]
Thank you so much for the issue but we don't take feature requests on the issue tracker. We recommend you to try to implement the feature and send a pull request or if you are in doubt if the feature will be accepted, ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.
