### ISSUE TITLE
Empty hash does not enter hash type serialization

### ISSUE THREAD

**Issue by akicho8** [rails/rails#42928]
### Steps to reproduce

```ruby
require "bundler/inline"

gemfile do
  gem "activerecord"
  gem "sqlite3"
end

require "active_record"
ActiveRecord::VERSION::STRING   # => "6.1.4"
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Migration.verbose = false

ActiveRecord::Schema.define do
  create_table :users do |t|
    t.text :foo, null: false
  end
end

class User < ActiveRecord::Base
  serialize :foo, Hash
end

User.create!(foo: {}) rescue p $!
# >> #<ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: users.foo>
```

### Expected behavior

Succeeded without errors.

Put foo column into db with `"--- {}\n"`.

### Actual behavior

Put foo column into db with NULL.

It works well if do `serialize :foo` or `serialize :foo, JSON` or `t.text :foo, null: true`.

Same in MySQL.

### System configuration

**ActiveRecord version**: 6.1.4
**Ruby version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin17]

**Comment by byroot** [comment]
This is a tested and documented behavior: https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize

> Empty objects as `{}`, in the case of `Hash`, or `[]`, in the case of `Array`, will always be persisted as `null`.

A corollary is that serialized fields should always allow `null`.
