### ISSUE TITLE
no locale in params from ActionMailer previews

### ISSUE THREAD

**Issue by dorianmariefr** [rails/rails#42924]
### Steps to reproduce

```ruby
class ApplicationMailer < ActionMailer::Base
  default from: "Socializus <contact@socializus.app>"
  layout "mailer"

  rescue_from ActiveRecord::RecordNotFound do |exception|
    Rails.logger.info(exception)
  end

  rescue_from ActiveJob::DeserializationError do |exception|
    Rails.logger.info(exception)
  end

  has_history
  track_clicks campaign: -> { "#{controller_path}-#{action_name}" }

  def with_user(user, &block)
    Time.use_zone(user.timezone) do
      I18n.with_locale(params["locale"] || user.locale) { block.call }
    end
  end
end
```

### Expected behavior

`params['locale']` contains the locale chosen in the preview interface

### Actual behavior

params only contains the user for instance, no locale

### System configuration

**Rails version**: Rails 6.1.4

**Ruby version**: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

**Comment by ghiculescu** [comment]
Can you share your previewer code? Assuming by preview interface you mean https://guides.rubyonrails.org/action_mailer_basics.html#previewing-emails

**Comment by dorianmarie** [comment]
I don't see anything about `locale` in the docs, my previews are very standars

one solution would be do something like `user.update!lcale: params[:locale])`

**Comment by louim** [comment]
@dorianmarie I think you might be mistaken on how to use the locale parameter shown in the preview interface. The param is exposed to the mailer _preview_, not the actual mailer. It is intended to be used like that:

In the mailer preview:
```ruby
class MyMailerPreview < ActionMailer::Preview
  def send_important_email
    I18n.with_locale(params[:locale]) do
      # user = ... whatever logic you use to create / populate user. ex:
      user = FactoryBot.create(:user, locale: I18n.locale)
      # or
      user = User.first.update!(locale: I18n.locale)

      MyMailer.send_important_email(user)
    end
  end
end
```

The actual mailer doesn't change:
```ruby
class MyMailer < ApplicationMailer
  def send_important_email(user)
    I18n.with_locale(user.locale) do
      # mailer stuff here
      mail(to: user.email)
    end
  end
end
```

**Comment by dorianmarie** [comment]
Nice!! the `params[:locale]` is sent to the preview, I didn't get that, thanks a lot!
