### ISSUE TITLE
Instrument ActiveStorage analyzer

### ISSUE THREAD

**Issue by shouichi** [rails/rails#42930]
Background:

We use google cloud trace to instrument our rails app. We see "jumps" between spans when running ActiveStorage analyzers. It seems that ActiveStorage publishes events when downloading/uploading blobs but does not publish events when running analyzers. As a result, we failed to trace analyzers and see "jumps between spans.

Solution:

Publish events when running ActiveStorage analyzers so that the tracer can subscribe.

Thanks in advance.

**Comment by intrip** [comment]
This proposal makes sense to me. Are you interested in making a PR?

**Comment by p8** [comment]
This commit added most of the instrumentation:
https://github.com/rails/rails/commit/4bfe7af68f1e1a7d02ace760ac1a5c5a4462edb2
You can use that as a guideline to add more instrumentation.

**Comment by shouichi** [comment]
I'll make a PR. Thanks for the guideline 👍
