### ISSUE TITLE
Misleading ActiveRecord::UnknownAttributeReference documentation

### ISSUE THREAD

**Issue by jordannb** [rails/rails#42950]
### Expected behavior
Docs state that `Post.order("length(title)").first` is invalid and would produce `UnknownAttributeReference` without `Arel.sql`:  https://api.rubyonrails.org/v6.1.4/classes/ActiveRecord/UnknownAttributeReference.html

### Actual behavior
Functions with zero or one arg are allowed, including `length(col_name)`. See Regexes below:

- Postgres: https://github.com/rails/rails/blob/8be6e7af27a11960ef76a8b46fb5cf171c54beed/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb#L102-L114
- Mysql: https://github.com/rails/rails/blob/8be6e7af27a11960ef76a8b46fb5cf171c54beed/activerecord/lib/active_record/connection_adapters/mysql/quoting.rb#L73-L84
- Sqlite: https://github.com/rails/rails/blob/8be6e7af27a11960ef76a8b46fb5cf171c54beed/activerecord/lib/active_record/connection_adapters/sqlite3/quoting.rb#L69-L80

### System configuration
**Rails version**:
`v6.1.3.2`

**Ruby version**:
`ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]`

**Comment by ghiculescu** [comment]
Good pickup. Is there a better example we can update the docs with?

**Comment by jordannb** [comment]
@ghiculescu Thank you for taking a look at this and finding where the behavior change was introduced.

I've opened a PR using one of the examples.

**Comment by ghiculescu** [comment]
Nice one @jordannb !
