### ISSUE TITLE
Strong Params require with permit combination produce unexpected exception

### ISSUE THREAD

**Issue by sanzstez** [rails/rails#42953]
### Steps to reproduce

```ruby
params = ActionController::Parameters.new(comment: 'some text')

params.require(:comment).permit(:text)
```

### Expected behavior
raise ActionController::ParameterMissing error 

### Actual behavior
This code will return String value 'some text' at require(:comment) step, but after this we got 'some text'.permit(:comment) and exception like:

```
 undefined method `permit' for "some text":String.
```
Github response for this issue (like example):
<img width="1358" alt="14 40 37" src="https://user-images.githubusercontent.com/1447939/128509617-1aa5e29e-4edc-409c-9271-a22d069d8372.png">

We can handle some additional checks with tap block but for my opinion it's overhead logic.
So maybe:
1) require method should always return object with ActionController::Parameters type or raise ActionController::ParameterMissing exception for correct handle on the top level.
 2) can be added some ability for type checking for require method, like:
`params.require(comment: {}).permit(...)`

### System configuration

**Rails version**:
RAILS: 6.1

**Ruby version**:
Ruby: 2.7

**Comment by Krupskis** [comment]
> ```ruby
> params = ActionController::Parameters.new(comment: 'some text')
> 
> params.require(:comment).permit(:text)
> ```

Is this a typo and did you mean `permit(:comment)`? It's inconsistent with your `'some text'.permit(:comment)`

**Comment by Krupskis** [comment]
Anyway, I think this is expected behavior given the current documentation.

> When passed a single key, if it exists and its associated value is either present or the singleton false, returns said value:

**Comment by sanzstez** [comment]
> > ```ruby
> > params = ActionController::Parameters.new(comment: 'some text')
> > 
> > params.require(:comment).permit(:text)
> > ```
> 
> Is this a typo and did you mean `permit(:comment)`? It's inconsistent with your other comment.
> 
> > I know that such code will return String value 'some text' at require(:comment) step, but after this we got 'some text'.permit(:comment) and error like:

No, code is correct. I similated situation when form was manually changed and request with params was fabricated. During such actions we guaranteed to get an error.
Cause in this line we didn't do any checks of value type (or something like) and pass as is:
https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/actionpack/lib/action_controller/metal/strong_parameters.rb#L504

**Comment by sanzstez** [comment]
Github like response fi this issue:
<img width="1358" alt="14 40 37" src="https://user-images.githubusercontent.com/1447939/128505388-495024fc-5ced-4c4a-834f-4090f65ebbcb.png">

**Comment by brenogazzola** [comment]
Looking at the `require` code:

```ruby
def require(key)
  return key.map { |k| require(k) } if key.is_a?(Array)
  value = self[key]
  if value.present? || value == false
    value
  else
    raise ParameterMissing.new(key, @parameters.keys)
  end
end
```

Basically, in your example `value` ends up being a `String`. In a correct usage, it's an instance of `ActionController::Parameters`. Why not open a PR for this, implementing the behavior you want and see what others think? 

Just be aware that the expected behavior according to the API is "If it's present, returns the parameter at the given key, otherwise raises an ActionController::ParameterMissing error". So returning the API is not making promises on the type of the returned parameter, only that it will be returned. There also a quite old [PR](https://github.com/rails/rails/pull/15692) where the `false` condition was added to ensure that this behavior was correct, so your change would be basically undoing that PR, since `false` would no longer be a valid return.

**Comment by sanzstez** [comment]
> Looking at the `require` code:
> 
> ```ruby
> def require(key)
>   return key.map { |k| require(k) } if key.is_a?(Array)
>   value = self[key]
>   if value.present? || value == false
>     value
>   else
>     raise ParameterMissing.new(key, @parameters.keys)
>   end
> end
> ```
> 
> Basically, in your example `value` ends up being a `String`. In a correct usage, it's an instance of `ActionController::Parameters`. Why not open a PR for this, implementing the behavior you want and see what others think?
> 
> Just be aware that the expected behavior according to the API is "If it's present, returns the parameter at the given key, otherwise raises an ActionController::ParameterMissing error". So the API is not making promises on the type of the returned parameter, only that it will be returned. There also a quite old [PR](https://github.com/rails/rails/pull/15692) where the `false` condition was added to ensure that this behavior was correct, so your change would be basically undoing that PR, since `false` would no longer be a valid return.

As you said in “correct usage”, but rails do not give any possibility

**Comment by sanzstez** [comment]
@brenogazzola I understand what you mean. 
But changing of default behaviour by rails convention should be approved by rails core DEV's firstly. 
I think rails community need more attention to this trouble, because his issue covers thousands rails app's and confuse dev's what sure that require method can be safely chained to permit method without any additional checks.

**Comment by brenogazzola** [comment]
I had assumed from your issue that your intent was to simply produce a better error message when the format of params did not match what the controller expected. 

IMO, if the controller expects comment to contains a text, and the form only sends the comment, raising an error is what I’d like Rails to do, so I know the exact place where the problem is, instead of checking the whole chain. 

How would allowing safe chaining help the case you mentioned? I’m not asking as a criticism, but as legitimate curiosity since I’ve never thought about this before.

**Comment by sanzstez** [comment]
@brenogazzola I just trying to say that construction below is unsafe and produce errors in 100% cases with fake data and didn't gave ability to directly use in code (as I want), without additional checks, that's it. VERY simple construction.
```
person_params = params.require(:person).permit(:name)
Person.create(person_params)
```

**Comment by brenogazzola** [comment]
Alright, in this case I'll recommend you cross post this on the `rubyonrails-core` channel of the [official forums](https://discuss.rubyonrails.org/). It will increase exposure and allow other developers who might be interested in this change to give input and provide arguments in favor of it. This was recommended to me in the past by one the Rails members, and helped me successfully get a breaking change merged.

**Comment by brenogazzola** [comment]
You might also give another thought to the PR suggestion. It’s what Rails [core members themselves recommend](https://github.com/rails/rails/issues/42900).

**Comment by p8** [comment]
This is also related to another recent issue: #42942
