### ISSUE TITLE
ActiveRecord::Associations::CollectionProxy#last returns wrong result

### ISSUE THREAD

**Issue by alexxty7** [rails/rails#42956]
### Steps to reproduce
```ruby
 class Author < ApplicationRecord
    has_many :books
 end

 class Book < ApplicationRecord
    belongs_to :author
 end

 author = Author.find(1)
 author.books
#  Books Load (74.4ms)  SELECT "books".* FROM "books" WHERE "books"."author_id" = $1 [["author_id", 1]]
# => [#<Book:0x00007f86254bc370
#        id: 2,
#         name: 'book2'>,
#       #<Book:0x00007f86254bc371
#         id: 1,
#        name: 'book1'>]

last_book = author.books.last
# No query executed
#       <Book:0x00007f86254bc371
#         id: 1,
#        name: 'book1'>

```

### Expected behavior
Executes a query and returns the last association item

### Actual behavior
Returns random association item (last item from cached collection)

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.6.5

**Comment by intrip** [comment]
If you don't want to rely on cached association you can use reload `author.books.reload.last`

**Comment by brenogazzola** [comment]
The behavior you are seeing is specific to the Rails console, because it will automatically inspect the result to print it for you, for the relation to be converted to an array. If test the same in a controller in your app you will see two queries.

**Comment by ghiculescu** [comment]
I think this is expected behaviour. You could also use `order` if you want to be explicit about your ordering.
