### ISSUE TITLE
Rails-ujs content-type response matcher matches media-type arguments

### ISSUE THREAD

**Issue by SleeplessByte** [rails/rails#42980]
The following code:

https://github.com/rails/rails/blob/6983a89c726243fb38fe28cff49cba3a5f63ba6f/actionview/app/assets/javascripts/rails-ujs/utils/ajax.coffee#L64-L68

...attempts to parse/interpret the response type by matching the `Content-Type` against a few regular expressions. Unfortunately it's matching against the _entire header_, including any sent *arguments*/*parameters*/*extension fields*. This means that this breaks on custom media types, and also registered media types using HTTP extensions (with custom parameters).

Examples of the current code:

```ruby
# Good: interpreted as JSON
Content-Type: application/json; charset=utf-8

# Good: interpreted as JavaScript
Content-Type: application/javascript; charset=utf-8

# Okay: legacy type interpreted as JavaScript
Content-Type: text/javascript; charset=utf-8

# Good: interpreted as JSON
Content-Type: application/vnd.company.model.v1+json; charset=utf-8

# Good: interpreted as JSON
Content-Type: application/ld+json; charset=utf-8
```

And some examples of things that currently break:

```ruby
# Bad: interpreted as JSON
Content-Type: application/vnd.company.thisisno.json.document; charset=utf-8

# Probably bad: non-existing combination interpreted as JSON
Content-Type: text/json; charset=utf-8

# Bad: interpreted as JSON
Content-Type: application/javascript; extension=json.parsed; charset=utf-8

# Bad: interpreted as JSON
Content-Type: application/vnd.company.binary; param=json.parsed; charset=utf-8

# Bad: interpreted as JavaScript
Content-Type: application/vnd.company.model.v1; param=javascript; charset=utf-8
```

### Solution

Instead of looking at the entire string, it _really_ should only look at the first part, as defined in [RFC 7231 3.1.1.1 and 3.1.1.5](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.5). Given the entire string:

```ruby
application/vnd.company.model.v1+json; param=javascript; charset=utf-8
```

it should only consider everything up-to but not including the first `;`

```ruby
application/vnd.company.model.v1+json
```

### One line solution:

For example, adding (below) on line 65 
https://github.com/rails/rails/blob/6983a89c726243fb38fe28cff49cba3a5f63ba6f/actionview/app/assets/javascripts/rails-ujs/utils/ajax.coffee#L65

```coffeescript
type = type.split(';')[0]
```

...changes the examples to:

```ruby
# Bad: interpreted as JSON
Content-Type: application/vnd.company.thisisno.json.document; charset=utf-8

# Probably bad: non-existing combination interpreted as JSON
Content-Type: text/json; charset=utf-8

# Good interpreted as JavaScript
Content-Type: application/javascript; extension=json.parsed; charset=utf-8

# Good: interpreted as other
Content-Type: application/vnd.company.binary; param=json.parsed; charset=utf-8

# Good: interpreted as other
Content-Type: application/vnd.company.model.v1; param=javascript; charset=utf-8
```

### Proper solution:

For _both_ `javascript` _and_ `json`, further changes can be made to make this tight. `JSON` can _only_ be:

- `^application\/json$`
- `\+json$`

JavaScript can only be:

- `^application\/javascript$`

and if supporting the obsoleted:

- `^(?:application|text)\/(?:java|ecma)script$`

...changes the examples to:

```ruby
# Good: interpreted as other
Content-Type: application/vnd.company.thisisno.json.document; charset=utf-8

# Good: interpreted as other
Content-Type: text/json; charset=utf-8

# Good interpreted as JavaScript
Content-Type: application/javascript; extension=json.parsed; charset=utf-8

# Good: interpreted as other
Content-Type: application/vnd.company.binary; param=json.parsed; charset=utf-8

# Good: interpreted as other
Content-Type: application/vnd.company.model.v1; param=javascript; charset=utf-8
```

### References

- Obsoleted `text/javascript` and `text/ecmascript`: https://www.rfc-editor.org/rfc/rfc4329.html#page-9
- Non-existence of `text/json`: https://www.iana.org/assignments/media-types/media-types.xhtml
- Longer list of unregistered mime types for JavaScript: https://datatracker.ietf.org/doc/html/rfc4329#section-3

**Comment by ghiculescu** [comment]
Thanks for the report and the proposed solutions. Would you like to make a PR?

**Comment by SleeplessByte** [comment]
Yeah certainly :)

**Comment by SleeplessByte** [comment]
@ghiculescu would you be interested in limiting the types for the `DOMParser` (https://developer.mozilla.org/en-US/docs/Web/API/DOMParser#parsing_xml_svg_and_html) as well? It has similar issues.

**Comment by ghiculescu** [comment]
That sounds like a good idea.

**Comment by SleeplessByte** [comment]
And finally: https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#write-your-code mentions to add test cases that fail without this code, but pass with it. Is it also preferable to add the list of already **Good** examples (in case they're not yet tested) to ensure that this behaviour is unaltered when further changes to this file are made?

**Comment by ghiculescu** [comment]
> Is it also preferable to add the list of already **Good** examples (in case they're not yet tested) to ensure that this behaviour is unaltered when further changes to this file are made?

Yes please!
