### ISSUE TITLE
pg_env in postgresql_database_tasks doesn't support certs for mtls

### ISSUE THREAD

**Issue by twk3** [rails/rails#42994]
Looks like config entries related to connection certs are missing from https://github.com/rails/rails/blob/5e8a26d70559c0b3183e81a5d2775d19146b0c04/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L100-L107

- `PGSSLCERT`
- `PGSSLKEY`
- `PGSSLROOTCERT`

### Steps to reproduce

- Configure a database.yml to postgres connecting using clientKey clientCertificate for mutual tls
- run the `db:structure:load` rake task

### Expected behavior

Schema is loaded

### Actual behavior

```shell
psql: error: FATAL:  connection requires a valid client certificate
```

### System configuration
**Rails version**: 6.1.3.2

**Ruby version**: 2.7.3

**Comment by mbayucot** [comment]
Hi @twk3, @byroot. Can I pick up this issue?

**Comment by byroot** [comment]
@mbayucot no need to ask for permission. However I can't guarantee it will be reviewed in a timely manner (I personally know very little about Postgres).

**Comment by WarheadsSE** [comment]
Go for it @mbayucot

In the least, we (@twk3 & @warheadsse) will have a look as soon as we can.

**Comment by mbayucot** [comment]
Ok, thanks @WarheadsSE @byroot
