### ISSUE TITLE
Do the db:... tasks wait for proper port unbinding?

### ISSUE THREAD

**Issue by mcandre** [rails/rails#43001]
Open question. I am troubleshooting a problem with Rails / Puma, and wondering if a command `rake db:create`... just before my `bundle exec puma` is somehow responsible for the EADDRINUSE error I am getting.

Is it possible that Rails `db`... tasks are not waiting for port unbinding to complete, before allowing the process to terminate and restore control to the next command?

I can try to work around this by explicitly killing PID's, but that feels unsafe and high maintenance.

**Comment by tenderlove** [comment]
I don't think that is possible.  The operating system should release resources when the process ends.  If you're not sure, maybe try adding a sleep between the commands?  Anyway, this seems more like a support issue, and I think StackOverflow might be a better place to ask.

Thanks!
