### ISSUE TITLE
ActiveRecord create! silently inserts Hash as NULL

### ISSUE THREAD

**Issue by sam-brownlow** [rails/rails#43039]
Hello 👋

I would like to investigate this issue myself and eventually open a PR to patch this issue.  Before doing so, it would be much appreciated if 3rd party input could be provided in order to confirm the below:

From my perspective, this is very clearly a bug, and *not* a feature; however, I realize that the Rails ecosystem is very large (with a lot of builtin "magic"), and this may somehow be expected behavior that is non-obvious.

I also realize that a custom validation could be created for a specific model, but it still strikes me as a bug that this behavior occurs in the first place.

### Steps to reproduce

1) Create a table containing an `integer` column that permits `NULL`
2) Execute `table.create!(int_column: {'some' => 'hash'})`
3) Notice that the value of the `int_column` is now `NULL` in the database

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)


ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end


class Comment < ActiveRecord::Base; end


class BugTest < Minitest::Test
  def test_proper_insert
    post_id = 1
    comment = Comment.create!(post_id: post_id)

    # this passes
    assert_equal(post_id, comment.post_id)
  end

  def test_improper_insert
    post_id = { 'key' => 'val' }
    comment = Comment.create!(post_id: post_id)

    # this FAILS
    assert_equal(post_id.present?, comment.post_id.present?)
  end
end
```

### Expected behavior
The expected behavior is that an error should be raised along the lines of `cannot insert Hash into an integer column` or `NoMethodError: undefined method 'to_i' for {"key"=>"val"}:Hash`

### Actual behavior
The insert succeeds by converting the `Hash` to `NULL`.

### System configuration
**Rails version**: `5.2.4.5` (in our production app) and `7.0.0.alpha` (in the above test code)

**Ruby version**: `2.6.6` (in our production app) and `2.7.0` (in the above test code)

(we are using PostgreSQL in our production app; the above test code obviously uses sqlite)

**Comment by thiagovsk** [comment]
@sam-brownlow  I think that this is not a bug, because when you are passing something with different type than integer, the query (insert) that is generated doesn't contain the "wrong" type that you are passing, then, the value of `post_id` is nil and no exceptions will be raise.

**Comment by sam-brownlow** [comment]
@thiagovsk If I hear you correctly, your point boils down to the following example...

```
comment = Comment.new
comment.post_id = { 'key' => 'val' }
comment.post_id.nil? == true
```

i.e. the bug as I've reported it is due to behavior in `Model.new`, *not* `Model.create`

Is this behavior documented somewhere?  It still strikes me as much more of a bug than a feature that a value is being silently cast to `nil` when it's very clearly not `nil`.

A similar example:

```
comment = Comment.new
comment.post_id = 'abc'
comment.post_id == 0
```

^ imo, the fact that `'abc'.to_i == 0` gives credence to the original point of my op, which is that (for e.g. `test_improper_insert`) I would expect an error similar to `NoMethodError: undefined method 'to_i' for {"key"=>"val"}:Hash` to be raised, instead of the observed behavior that the value be silently cast to `nil` inside of `Model.new`

**Comment by p8** [comment]
The relevant code is here:
https://github.com/rails/rails/blob/cb0c746b7d757d8491f2db1539cf9377b3eb833e/activemodel/lib/active_model/type/integer.rb#L46-L48

It's been that way for a long time:
https://github.com/rails/rails/commit/807e176aba7804cad8d630d04f3b771011be4fe6#r2427756
Maybe we shouldn't silently rescue?

**Comment by sam-brownlow** [comment]
@p8 Thanks for the deep dive on the origins of this behavior.

It seems like I'm not the first person to consider this a bug, as @sobrinho pointed out in [your link](https://github.com/rails/rails/commit/807e176aba7804cad8d630d04f3b771011be4fe6#r2427756).

While I recognize that there are opposing points of view, e.g. [this](https://github.com/rails/rails/commit/807e176aba7804cad8d630d04f3b771011be4fe6#r2428425), which point to a motivation to avoid dealing with the various forms of Ruby's numeric types and their potential edge cases, I am still persuaded to believe that ActiveRecord implicitly owns the duty to transliterate between Ruby types and SQL (strong) types and that avoiding this with a blind `try ... catch ...` that coerces any non `to_i` values to `nil` should be considered a bug that introduces the ability to silently corrupt the contents of a database via the mishandling of types.

I am going to proceed forward with developing a PR to *not* silently coerce non-integer types to `nil` and instead raise an error in this scenario, although I expect that there may be friction with getting this formally merged due to the fact that this type of [rescue behavior](https://github.com/rails/rails/blob/37e0d5de899cfbb3703067daefe2546215aaa4cc/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L55) has existed for the past 16 years.  Realistically, I see this patch being merged first as a warning and then in a later version as a do-not-pass-go error.

**Comment by p8** [comment]
@sam-brownlow sounds good to me!

**Comment by intrip** [comment]
I don't know why the `rescue nil` was added and all the possible implication but `.to_i` looks more than enough to me (is not as strict as `Integer()` and already tries to convert most of the types) in such situation and agree in removing the `rescue`. 
That said I'm not the decision maker here so it's just an opinion 😄

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/pull/43142#issuecomment-915820545
