### ISSUE TITLE
Enum backed by string column doesn't work with array syntax

### ISSUE THREAD

**Issue by MatheusRich** [rails/rails#43049]
### Steps to reproduce

1. Create a Books table with a **string** column for its cover type.

```ruby
# db/schema.rb
ActiveRecord::Schema.define(version: 2021_08_19_014728) do
  create_table "books", force: :cascade do |t|
    t.string "cover", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["cover"], name: "index_books_on_cover"
  end
end
```

2. Define an enum in the model with the array syntax

```ruby
# apps/models/book.rb
class Book < ApplicationRecord
  enum cover: [:hard, :soft]
end
```

3. Access Rails console and create an object

```ruby
Book.create cover: "soft"
# => #<Book:0x00007fe231b30860
#     id: 1,
#     cover: nil,
#     created_at: Thu, 19 Aug 2021 02:23:56.794160000 UTC +00:00,
#     updated_at: Thu, 19 Aug 2021 02:23:56.794160000 UTC +00:00>
```

4. Note that the `cover` column is `nil` even though Rails created the object.

### Expected behavior

I think it would be neat if Rails could infer the enum value from its key for string columns. It already does this for integers (inferring by the array position), so I don't think it's a stretch for us to add this. Here's what I'm thinking:

```ruby
class Book < ApplicationRecord
  # for string columns, Rails would interpret it as
  # enum cover: { hard: "hard" , soft: "soft" }
  enum cover: [:hard, :soft]
end
```

Using the key as a value is probably the most common option for this case. I've seen a lot of apps using the following pattern to address this:

```ruby
class Book < ApplicationRecord
  COVER_OPTIONS = [:hard, :soft, :other]
  enum cover: COVER_OPTIONS.map { |option| [option, option.to_s] }.to_h
end
```

This would help in those cases as well. **I will tackle this if approved.**

### Actual behavior

Currently, it saves the object with the array index position as string, but it cannot load the value from the database, so the ActiveRecord object comes with the enum field as `nil`.

### System configuration

**Rails version**: Rails 6.1.4

**Ruby version**: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

### Bug Reproduction Script

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "books", force: :cascade do |t|
    t.string "cover", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["cover"], name: "index_books_on_cover"
  end
end

class Book < ActiveRecord::Base
  enum cover: [:hard, :soft]
end

class BugTest < Minitest::Test
  def test_enum_backed_by_string_with_array_syntax
    book = Book.create! cover: :soft

    refute_nil Book.last.cover
  end
end
```

**Comment by ghiculescu** [comment]
For feature requests/suggestions, the best place to ask them is the Ruby on Rails discussion forum https://discuss.rubyonrails.org/c/rubyonrails-core/5. The core team hang out there as do many others, so you will be able to get feedback on if this will work for many apps.

Alternatively you can always make a PR, then it's possible to discuss the proposal with real code.

I'm going to close this now as we try to keep this issue tracker strictly for bugs.

**Comment by MatheusRich** [comment]
@guiocavalcanti That makes sense, but what about the current behavior? Isn't it a bug?

**Comment by ghiculescu** [comment]
No, I think it is behaving as documented. I agree your suggested improvements would make it nicer though.
