### ISSUE TITLE
ActiveRecord OR condition not placing parenthesis correctly when there are AND conditions in the query

### ISSUE THREAD

**Issue by abhishekjain16** [rails/rails#43046]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", tag: "v6.0.3.7"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.string :description
    t.boolean :active
  end

end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_or_condition
    post = Post.create!(title: "test", description: "Bug report", active: true)

    puts Post.where(title: "test", description: "Bug report").or(Post.where(active: true)).to_sql
  end
end

```

### Expected behavior
The Query fired should be 
```
SELECT "posts".* FROM "posts" WHERE (("posts"."title" = 'test' AND "posts"."description" = 'Bug report') OR "posts"."active" = 1)
```

### Actual behavior
```
SELECT "posts".* FROM "posts" WHERE ("posts"."title" = 'test' AND "posts"."description" = 'Bug report' OR "posts"."active" = 1)
```

### System configuration
**Rails version**: 6.0.3.7

**Ruby version**: 2.6.3

According to the docs https://api.rubyonrails.org/v6.0.0/classes/ActiveRecord/QueryMethods.html#method-i-or it should set parenthesis as below: 
```
Post.where("id = 1").or(Post.where("author_id = 3"))
# SELECT `posts`.* FROM `posts` WHERE ((id = 1) OR (author_id = 3))
```
Looks like it is not happening now, so not sure if something changed or if this is a bug?

**Comment by aditya-kapoor** [comment]
@abhishekjain16 I believe this is due the argument type passed in to the where method. I found that the query when passed with the string arguments works correctly. 

```
# Doesn't work.
Post.where(title: "test", description: "Bug report").or(Post.where(active: true)).to_sql

# => SELECT "posts".* FROM "posts" WHERE ("posts"."title" = 'test' AND "posts"."description" = 'Bug report' OR "posts"."active" = 1)

# Works.
Post.where("title = 'test' and description = 'Bug report'").or(Post.where("active = 1")).to_sql

# => SELECT "posts".* FROM "posts" WHERE (("posts"."title" = 'test' AND "posts"."description" = 'Bug report') OR "posts"."active" = 1)


```

**Comment by abhishekjain16** [comment]
@aditya-kapoor Correct! Which means there is an issue with the query generation in first case. Seems like when I inject query statement directly to the where in a string it works but when activerecord generates it, then it messes up.

**Comment by matthewd** [comment]
Those two queries are semantically identical.. do you have a use case where the unnecessary parens make a difference?

**Comment by abhishekjain16** [comment]
Yeah! Looks like there would be no difference in the result. Just the way we formulate it (which confused me at first)
The only time parens would be necessary is when OR condition needs to take precedence, which Rails does correctly.
I will close this issue. Thank you!
