### ISSUE TITLE
Can't access @request and/or @controller variables on `ActionDispatch::IntegrationTest`

### ISSUE THREAD

**Issue by luizkowalski** [rails/rails#43041]
I have a controller test like this:

```ruby
class Abi::OrganizationsControllerTest < ActionDispatch::IntegrationTest
  setup do
    @request.headers['x-abi-token'] = 'test'
  end
...
```

and when I run it, I get `NoMethodError: undefined method 'headers' for nil:NilClass`.

This is my `test_helper.rb` class

```ruby
# frozen_string_literal: true

ENV['RAILS_ENV'] ||= 'test'
require_relative '../config/environment'
require 'rails/test_help'
require 'minitest/rails'

# Consider setting MT_NO_EXPECTATIONS to not add expectations to Object.
# ENV["MT_NO_EXPECTATIONS"] = true

Dir[Rails.root.join('test/support/**/*.rb')].each { |f| require f }

class ActiveSupport::TestCase
  # Run tests in parallel with specified workers
  # parallelize(workers: :number_of_processors)

  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  fixtures :all

  # Add more helper methods to be used by all tests here...
end
```

It also happens when using the spec way

```ruby
describe Abi::OrganizationsController do
  setup do # also tried `before` here
    @request.headers['x-abi-token'] = 'test'
  end
```

### Steps to reproduce
I managed to reproduce it with a fresh new app 
```
$ rails new testing -d postgresql
$ rails g scaffold admin/blog_post post:text
```

```ruby
class Admin::BlogPostsControllerTest < ActionDispatch::IntegrationTest
  setup do
    @request.headers
    @admin_blog_post = admin_blog_posts(:one)
  end
```

### Expected behavior
I should have access to `@request` and `@controller`

### Actual behavior
`NoMethodError`

### System configuration
**Rails version**: 6.1.4

**Ruby version**:  3.0.2

**Comment by dmcge** [comment]
I think this is the expected behaviour. `@request` stores the request that was made. It’s not for actually building up the request, that’s what the [`get` method](https://edgeapi.rubyonrails.org/classes/ActionController/TestCase/Behavior.html#method-i-get) (and friends) are for.

**Comment by luizkowalski** [comment]
hmm, that's actually true, I just checked the docs and it says

```
You also have access to three instance variables in your functional tests, after a request is made:
```

good call @dmcge, thanks a lot!
