### ISSUE TITLE
SchemaStatements#column_exists? is broken when passing type

### ISSUE THREAD

**Issue by sholden** [rails/rails#43054]
It seems that @eileencodes already found this behavior from `add_column if_not_exists: true` here (https://github.com/rails/rails/pull/42212), but maybe the type parameter should just be removed in the `column_exists?` method as well?

I don't think anyone would expect this behavior, and could lead to sadness in migrations if people encounter it unexpectedly. I know it's been around forever, and maybe it's not worth it to break dependencies. But it still seems like a bit of a foot gun.

If left in, maybe we can make it check the underlying `sql_type`?

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "postgresql"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true
end

Post = Class.new(ActiveRecord::Base)

class BugTest < Minitest::Test
  def conn
    Post.connection
  end

  def test_column_exists_no_without_type
    # Yay, this works
    conn.add_column(:posts, :happy_number, :bigint)
    assert conn.column_exists?(:posts, :happy_number)
  end

  def test_column_exists_with_type
    # Oh nooooo 😭
    conn.add_column(:posts, :sad_number, :bigint)
    assert conn.column_exists?(:posts, :sad_number, :bigint)
  end
end
```

### Expected behavior
Both calls to `column_exists?` should return true

### Actual behavior
Calling `column_exists?` with the type specified returns false

### System configuration
**Rails version**: main

**Ruby version**: 2.7.1

**Comment by ghiculescu** [comment]
I don't think the parameter should be removed, it (sometimes) works and it is probably in use in lots of code in the wild (sometimes working correctly I hope).
 
> If left in, maybe we can make it check the underlying `sql_type`?

This idea has merits. It'd be good to see a PR with some test cases to see if it causes any regressions compared to the current behaviour.

**Comment by eileencodes** [comment]
I'm pretty sure I tried `sql_type` and found that it results in a change in behavior but don't recall exactly what. I also tried `lookup_cast_type` and the problem is that it needs more information than we have at this point in the code, esp for postgres. I think the only solution is to add a comment in the document. I agree that we shouldn't remove the argument.

**Comment by ghiculescu** [comment]
I tried changing to `sql_type` and it breaks this test, and maybe others too https://github.com/rails/rails/blob/9a6669d4da7a068af4e936f6bf681d2fba082540/activerecord/test/cases/ar_schema_test.rb#L125

In https://github.com/rails/rails/pull/43669 I updated the docs but also added a new option to explicitly check by `sql_type`.
