### ISSUE TITLE
STI methods from BaseClass won't `respond_to` on children

### ISSUE THREAD

**Issue by krtschmr** [rails/rails#43057]
In plain Ruby the inherited classes would `respond_to` parents methods correctly.

```
class Base
  def test; end
  private def private_test; end
end
class Test < Base; end
Test.new.respond_to?(:test)
Test.new.respond_to?(:private_test)
Test.new.respond_to?(:private_test, true)
```

### Expected behavior

If we have a `class User` with a `def love` and a `class GuestUser < User` i would naturally expect that `GuestUser` does `respond_to?(:love)` (which is defined in `User`). However this isn't the case.
In order to have this working, we need `respond_to_missing` and add return `true` for a given method. 

I'm here to learn _why_ this way was build in favor of the _ruby way_

### System configuration
**Rails version**: 5.2

**Ruby version**: 2.7

**Comment by SkipKayhil** [comment]
Hey @krtschmr, I tried to reproduce this with a bug report template but was not able to. Do you have a reproducible test case for this?

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end
end

class User < ActiveRecord::Base
  def love
    'something'
  end
end

class GuestUser < User
end

class BugTest < Minitest::Test
  def test_subclass_responds_to
    user = User.create!
    guest = GuestUser.create!

    assert user.respond_to?(:love)
    assert guest.respond_to?(:love)
  end
end
```

**Comment by p8** [comment]
Changing the reproduction script to use Rails 5.2 also doesn’t reproduce the error.  It might be an classic autoloader issue, where GuestUser gets loaded before User, because  load order is alphabetic.

**Comment by krtschmr** [comment]
@p8  that sounds very interesting. i will try to reproduce it.

what actually happened ist that the `resource-activity` gem allows to override the subject of an email by just adding a method `def override_mail_subject` (something like that).

We do have `GeneralDocument`, `ClmDocument` and `ContractDocument` and all 3 inherit from `Document` (C prior of D as i can see already).

somehow my coworker added the method to the `Document` and then added to all 3 subclasses

```
def override_mail_subject
  super
end
```

i asked him why that is, and the said it's the only way to make the test pass and actually have this work. sounded weird so i debugged `resource-activity` gem which uses smth like `model.respond_to?(:override_mail_subject)` but that was returning `false`. 
it does work if i just add `def override_mail_subject` to the `Document` base class and also add `respond_to_missing` and then return true for that method.
