### ISSUE TITLE
Documentation: 5.2 -> 6.0 Upgrade docs re: config.add_autoload_paths_to_load_path

### ISSUE THREAD

**Issue by pglombardo** [rails/rails#43053]
Documentation section [4.7.11 config.add_autoload_paths_to_load_path](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#config-add-autoload-paths-to-load-path)

This nicely explains about the new option and it's suggested value but it doesn't say in which file that value should be set.  

I would guess one of the environment files (or all) or config/application.rb but I'm not sure honestly and a best practice indication would be helpful.

**Comment by ghiculescu** [comment]
I think it should be in `config/application.rb`. It would be more confusing to have this behaviour differ per-environment.

**Comment by ghiculescu** [comment]
Would you like to make a PR to improve the docs?

**Comment by pglombardo** [comment]
I tried but failed :-(

First, A PR in my fork closed this issue which was a surprise to me.

And second, the Create Pull Request button is disabled for me so it might be a permissions issue.

![Screen Shot 2021-08-20 at 16 43 57](https://user-images.githubusercontent.com/395132/130251291-83e43591-ed51-4ca4-9baa-a7dbcaa070b7.png)

I'm probably missing something so for now I'll pass on the PR but thanks for the info!

**Comment by ghiculescu** [comment]
Hmm, do the instructions here help https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#issue-a-pull-request

**Comment by pglombardo** [comment]
Those are the same steps I took (and just tried again).  I've contributed to a bunch of other projects over the years so I have no clue really.
