### ISSUE TITLE
Cache misses as a result of `RedisCacheStore#failsafe` silently dropping errors

### ISSUE THREAD

**Issue by nstuart-at-salesforce** [rails/rails#43082]
### Steps to reproduce

1. Store something in cache, `Rails.cache.write('a_key', 123)`
2. Reboot a Redis cluster while pointing a RedisCacheStore to it.
3. Read from cache, `Rails.cache.read('a_key')`

### Expected behavior
Value `123` should be returned

### Actual behavior
`nil` is returned

### System configuration
**Rails version**: `Rails 6.1.3.2`

**Ruby version**: `ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin19]`

**Comment by nstuart-at-salesforce** [comment]
This seems to be an issue related to https://github.com/rails/rails/issues/42818#issuecomment-890849726. 

The logic of `failsafe` doesn't allow raising the captured exception. This causes implementors of `Rails.cache.read` and other methods to not know if the entry is missing, or if a connection issue is preventing access to the cache. 

Opening this issue to hopefully get traction on adding a configuration option to the `redis_cache_store` to allow the exception to be raised instead of "handled"

**Comment by ghiculescu** [comment]
> adding a configuration option to the `redis_cache_store` to allow the exception to be raised instead of "handled"

👍  on this, would you be interested in making a PR? We try to avoid using the issues board for feature requests (in favour of https://discuss.rubyonrails.org/c/rubyonrails-core/5) but if you'll be working on it then that's fine.

**Comment by nstuart-at-salesforce** [comment]
@ghiculescu 👍  Will do, thanks for the response

**Comment by nstuart-at-salesforce** [comment]
I don't see the guidelines specifically addressing this question, so hoping you don't mind me asking you...

@ghiculescu if I want to target a specific version, such as 6.1, would I file the PR against the `6-1-stable` branch, or start with `main` and work to 6.1?

**Comment by ghiculescu** [comment]
@nstuart-at-salesforce target `main`. https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#issue-a-pull-request talks you through how the PR should be set up, but basically, always target `main`. Select bug fixes [*may* be backported](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#backporting) to existing stable branches but it's not a guarantee, particularly as Rails 7 is fairly close I think.

**Comment by nstuart-at-salesforce** [comment]
@ghiculescu Perfect, I was looking for doc here in github(since PRs are git specific), thanks for pointing me in the right direction!

**Comment by byroot** [comment]
I'm not sure the proposed option is acceptable. In the meantime you can easily implement the behaviour you want in your app:

```ruby
module ActiveSupport
  module Cache
    class StrictRedisCacheStore < RedisCacheStore
      private
      
      def handle_exception(exception:, method:, returning:)
        raise exception
      end
    end
  end
end

# config/application.rb
config.cache_store = :strict_redis_cache_store, ...
```

**Comment by ghiculescu** [comment]
^ works, but what don't you like about the proposed solution? I am curious, as the concept seems worthwhile to me.

**Comment by byroot** [comment]
I'll comment there.
