### ISSUE TITLE
`with_options` ignored in migrations

### ISSUE THREAD

**Issue by themilkman** [rails/rails#43087]
`with_options` seems to be ignored in migrations. At least in the [API docs](https://api.rubyonrails.org/classes/Object.html#method-i-with_options) there are no usage limitations mentioned.

### Steps to reproduce

Add a column in a migration inside an with_options block:

```ruby
class CreateUsers < ActiveRecord::Migration[6.1]
  def change
    create_table :users do |t|
      with_options(null: false) do
        t.string :name
      end
	  # boring way that works
      t.string :mood, null: false
    end
  end
end
```

### Expected behavior

The :name column should be not-null.

### Actual behavior

schema.rb:

```ruby
  create_table "users", force: :cascade do |t|
    t.string "name"
    t.string "mood", null: false
  end
```

### System configuration
**Rails version**: 6.1.4.1

**Ruby version**: 3.0.2

Cheers!

**Comment by intrip** [comment]
@themilkman 

Have you tried with:

```ruby
class CreateUsers < ActiveRecord::Migration[6.1]
  def change
    create_table :users do |t|
      t.with_options(null: false) do
        string :name
      end
    end
  end
end
```

?

**Comment by kaspth** [comment]
Your code references a variable defined outside of the block, so there's not much we can do. @intrip's suggestion is correct. Thank you!

**Comment by themilkman** [comment]
Good catch, thanks @intrip! Didn't think about this.
