### ISSUE TITLE
Please create a fork from rails 6 without webpacker

### ISSUE THREAD

**Issue by hadmut** [rails/rails#43090]
Hi, 

I've started a bug report myself in 2019 about how rails went broken from rails 5 to rails 6 by using webpacker and bloating rails apps from less than 1MB with rails 5 to 106MB with rails 6, and read at least three other discussion threads about that problem. 

The fact is: No one ever gave any good reason or answer why rails should have made the move to webpacker. 

Instead, all those people objecting had really good reasons for objecting, which have been completely ignored. There were completely silly answers like „other frameworks do the same“ or „Apples X-Code is even bigger“. That's nonsense. 

And, from a european point of view, I wonder how this all was possible after the USA heavily introducing codes of conduct, forcing people to respect someones gender, but obviously not someones arguments. 

Other arguments where just childish, e.g. that it moved the space from gems to the node directory. 
Problem 1: I have control over the gems I need, rails new never downloaded all gems available on the planet, just the ones I wanted. Now it seems to download every javascript code it can find. 
 
Problem 2:  Gems are installed once per system and then shared between rails apps. That heap of js/node is downloaded once per application, and if you have 20 applications you need 20*106MB. And it's not just a problem of disk space. It's a networking problem. You simply can't develop anymore when away from high bandwith internet access, e.g. in airplane, train etc. 

Problem 3: Who should ever be able to survey 106MB of code? I mean 106MB before having written a single line. 

Problem 4: Who should be able to check, verify, even survey all those copyright and license notes and see, whether compatible? 

Problem 5: Huge security problem, no one knows which of these things is still maintained. 

Problem 6: It is hard to keep track with rails itself and all the features and functions, all those new bells and whistles. But it's possible by spending a certain amount of time on the rails guides. However, I don't see how I should ever by able to understand, what these 106MB of bloat are good for, not to mention how to use them. 

Problem 7: I used to pack the rails environment for several apps (with same Gemfile and Gemfile.lock) in a docker container, which could be reused for all rails application. Rails 6 places the 106MB of bloat right into the app directory, making it impossible to separate that heap of useless things from the application. It's a rather unforgivable design flaw to mix the application code with foreign libraries in the same directory. 

Lots of people have raised good reasons and arguments against webpacker and it's behaviour. 

Let's face the fact, that it s 2021, and nothing got fixed or improved. 

Webpacker is broken by design and beyond repair. It's a script kiddies design who wants to have all the possible gifts for christmas, but simply unable to accept that it went a wrong way. 

I've started using rails around 2007/2008, Rails 2, and never had any problem with Rails up to version 5, but just wasted hours (and not yet finished) trying to port an app from Rails 5 to Rails 6. 

I do not consider myself beeing able to produce production-ready reliable apps with Rails 6, since I simply do not understand what's going on there. 

And if I do read those discussion I mentioned above, I'm really convinced that the rails developers don't understand it either. But at the same time, they are unwilling to accept any other point of view, while not having a reasonable one of their own. In fact, in all those discussions I did not see a single good reason for this step to webpacker. As pointed out for some of the discussions points above, that's just blabla and ignorance.

So could someone closer than me to the development of rails please create a sane fork of rails 6 without that terrible webpacker/yarn thing?

This damned thing really breaks the usability of rails. It has become a nightmare. 

 
And, to finally fulfill the modern way of american communication and thinking: It's incredibly racist. Because it is based on the extremely resource-wasting american way of life, where costs, disk space, bandwith just don't matter. It completely ignores the limitations of disk space, money, bandwith in other countries. 

Therefore it is a violation of the rails code of conduct, which says

- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Focusing on what is best for the community

which has severely been violated by the rails developers defending webpacker in all discussions/code issues I've seen. People are telling that they have problems, real problems with that bloatware, but the developers are completely ignoring that. 
 

So maybe consider what the code of conduct defines for that case:

> Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project's leadership.

**Comment by rafaelfranca** [comment]
Thank you so much for this detailed issue. Unfortunately we have no interest of creating a fork of the framework we maintain, but feel free to create a fork and maintain it. 

We do plan to remove webpacker from Rails 7.0 but Rails 6.0 is already in maintenance mode and can’t introduce breaking changes. But, it is already totally possible to use rails 6 without webpacker, we even have an option to generate applications without it, so feel free to use that option.

You can find that option running ‘rails new —help’. 

I hope this help. Have a nice day and thank you again for the issue.

**Comment by collimarco** [comment]
> We do plan to remove webpacker from Rails 7.0

That is great.

> it is already totally possible to use rails 6 without webpacker

How can I do that? Is there any option for `rails new` to skip webpacker?

**Comment by vfonic** [comment]
@collimarco I assume you could try `rails new --help` and see what comes out?

I'd try `rails new --skip-webpack-install` and see what it does.

**Comment by collimarco** [comment]
@vfonic `-skip-webpack-install` only skips the installation of the webpack packages, it doesn't skip the installation of webpack itself... So it's not related to this question.
