### ISSUE TITLE
ActiveRecord::RecordInvalid exception ignored when attaching an ActiveStorage field, and the associated record isn't valid but persisted

### ISSUE THREAD

**Issue by imdario** [rails/rails#43123]
### Steps to reproduce

Invoking `attach` on a ActiveStorage backed field mapped as `has_one_attachment` in a model, it raises an `ActiveRecord::RecordNotSaved` without no explanation of the root cause. In this case, an `ActiveRecord::RecordInvalid` is ignored (because I forgot to set the `config.active_storage.service` setting) and it's:

```
ActiveRecord::RecordInvalid (Validation failed: Blob service name can't be blank)
```

I think it's not an ActiveStorage issue, but a general issue when a validation fails in the associated record, although it was persisted previously. In this case, the associated record is an `ActiveRecord::Associations::HasOneAssociation`.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 6.1.0"
  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"

class TestApp < Rails::Application
  config.eager_load = false

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  # Left this commented on purpose
  # config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :jobs do |t|
    t.string :source
    t.integer :status, default: 0

    t.timestamps
  end
end

class Job < ActiveRecord::Base
  has_one_attached :body
end

require "minitest/autorun"

class BugTest < MiniTest::Test
  def test_ignored_exception
    job = Job.create!(source: 'bug_test')

    assert_raises ActiveRecord::RecordNotSaved do
      job.body.attach(
        io: File.open(__FILE__),
        filename: 'bug_test.rb',
        content_type: 'text/plain'
      )
    end
  end
end
```

### Expected behavior

Raise the same `ActiveRecord::RecordNotSaved`, but include the root cause. I think the code in `ActiveRecord::Associations::HasOneAssociation#replace` (at `active_record/relations/has_one_association`, and probably more places where this pattern `ActiveRecord::RecordNotSaved` is applied) should be like this:

```ruby
if record
  set_owner_attributes(record)
  set_inverse_instance(record)

  begin
    if save && !record.save!
      nullify_owner_attributes(record)
      set_owner_attributes(target) if target
    end
  rescue => e
    raise RecordNotSaved, "Failed to save the new associated #{reflection.name}.", cause: e
  end
end
```

### Actual behavior

An `ActiveRecord::RecordNotSaved` is raised, hiding the root cause. It's similar to #36210, #36591 and #42741.

### System configuration
**Rails version**: 6.1.4.1

**Ruby version**: 2.7.0p0

**Comment by imdario** [comment]
Note: I could provide a PR, but I would like to know your opinion, and to make sure my proposal is fine.

**Comment by alexandreruban** [comment]
Do you think it would solve the problem to add an error message when the ActiveStorage service is not configured like in #43144 ?

**Comment by imdario** [comment]
@alexandreruban It would solve the specific issue that brought me down the rabbit hole for half an hour, but I think it can happen with any other validation error.
