### ISSUE TITLE
Defining an ActiveRecord scope using keyword arguments gives a deprecation warning

### ISSUE THREAD

**Issue by dmeranda** [rails/rails#43126]
If you define a scope method using Ruby keyword arguments then you will get a deprecation warning.

Consider a simple example:

```ruby
scope :with_value, -> (val, equal: true) {
    equal ? where( value: val ) : where.not( value: val )
}
```

Then calling the scope:

```Ruby
  records = SomeModel.with_value( "hello", equal: false )
```

will give a deprecation warning like:

```
.../gems/activerecord-6.0.4/lib/active_record/relation.rb:412: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

### Possible fix

I'm not sure if this works, but it seems like the internal method ```ActiveRecord::Relation._exec_scope```, which is currently defined like:
```ruby
def _exec_scope(name, *args, &block)
    .....  instance_exec(*args, &block) .....
```
should also take a keywords splat argument and pass that through to the call to ```instance_exec```, as:
```ruby
def _exec_scope(name, *args, **kwargs, &block)
    ..... instance_exec(*args,**kwargs, &block) .....
```

Also the call to ```_exec_scope``` that is made by the scope's singleton method, which it itself created
inside ```ActiveRecord::Scoping::Named.scope()```, would also need to accept and pass on a keywords splat argument.

### System configuration
**Rails version**: 6.0.4

**Ruby version**: 2.7.4

**Comment by ceritium** [comment]
I think that your proposal makes sense, but I am not able to reproduce it. I created a new rails app with 6.0.4 and ruby 2.7.4, but I don't see the warnings. Maybe I have some configuration that hides the warnings?

**Comment by dmeranda** [comment]
You may need to enable the deprecation warning. See https://bugs.ruby-lang.org/issues/17000

The easiest is to do the following immediately after loading ruby (or after a ```reload!```)

```ruby
Warning[:deprecated]=true
```

I don't have the environment ready to test it, but I suspect this would become a hard failure in Ruby 3.

**Comment by guilleiguaran** [comment]
@dmeranda hi, do you want to open a PR for this?  if not let me know and I'll take care of it directly.

**Comment by dmeranda** [comment]
@guilleiguaran Yes, please. I don't have the experience or time to do much work in the Rails project.

**Comment by guilleiguaran** [comment]
I've confirmed that this isn't reproducible in 6-1-stable nor the main branch:

```ruby
    scope :with_args_and_kwargs, ->(replies_count, approved: false) { where(replies_count: replies_count, approved: approved) }
```

```ruby
  def test_scope_with_args_and_kwargs
    # Explicit true
    topics = Topic.with_args_and_kwargs(0, approved: true)
    assert_operator topics.length, :>, 0
    assert topics.all?(&:approved?), "all objects should be approved"

    # No arguments
    topics = Topic.with_args_and_kwargs(1)
    assert_operator topics.length, :>, 0
    assert topics.none?(&:approved?), "all objects should not be approved"
  end
```

Unfortunately, 6.0 only receives security updates so this can't be fixed but the errors will go away when your app is updated.

Thanks for your bug report!
