### ISSUE TITLE
validates_with on instance does not work with strict: true

### ISSUE THREAD

**Issue by caiohsramos** [rails/rails#43135]
Going through the docs, I noticed the class method `validates_with` accepts a `strict: true` option, but the instance one does not accept it. Should this behaviour be implemented on instance's `validates_with`?

File: https://github.com/rails/rails/blob/main/activemodel/lib/active_model/validations/with.rb#L143 (not passing `options` to `validator.validate(self)`)
### Steps to reproduce

```ruby
class Book < ApplicationRecord
end

class Book::TitleValidator < ActiveModel::Validator
  def validate(record)
    record.validates_presence_of :title
  end
end

b = Book.create!(title: nil)
b.validates_with Book::TitleValidator, strict: true
```

### Expected behavior

Should raise an `ActiveModel::StrictValidationFailed` error.

### Actual behavior

No `ActiveModel::StrictValidationFailed` is raised, but `b.errors` contains the errors.

### System configuration
**Rails version**: 6.0.3.6

**Ruby version**: 2.7.1

**Comment by ceritium** [comment]
It works if you define `Book::TitleValidator` like:

```ruby
class Book::TitleValidator < ActiveModel::Validator
  def validate(record)
    record.validates_presence_of :title, options
  end
end
```

**Comment by caiohsramos** [comment]
@ceritium thanks! That really worked for me :smile: 

Shouldn't this be the default behaviour for the "validates_with" method? Propagating `options` to validate

**Comment by ceritium** [comment]
@caiohsramos, do you mean to pass the `options` argument implicitly to `record.validates_presence_of`? I can't imagine how `ActiveModel::Validator` could do that.
