### ISSUE TITLE
rails new --edge option does not work (windows?) How to solve ?

### ISSUE THREAD

**Issue by Bodata** [rails/rails#43143]
### Steps to reproduce

```ruby
rails new app_name -m module.rb --database=postgresql --edge (--webpacker option off/on no effect same error)
```

### Expected behavior

There would be a new application generated

### Actual behavior

All goes well until:
```Bundle complete! 40 Gemfile dependencies, 156 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  webpacker:install
Traceback (most recent call last):
C:\Ruby27-x64\bin\ruby.exe: No such file or directory -- C:/Users/P.C. (LoadError)
```
When i remove the --edge option all works ok.

Running after the new command is halted in app dir : rails webpacker:install --trace

```
** Invoke webpacker:install (first_time)
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
** Invoke webpacker:check_yarn (first_time)
** Execute webpacker:check_yarn
** Execute webpacker:install
Traceback (most recent call last):
C:\Ruby27-x64\bin\ruby.exe: No such file or directory -- C:/Users/P.C. (LoadError)
```
### System configuration
**Rails version**:

Edge (7.0alfa)

**Ruby version**:

ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x64-mingw32]

**OS**.

Windows 10

**Who to proceed ?**

I am more or less stuck. The option seemed to work a week ago.
**Is there a way to get edge versions back in time ?**

Every time i execute a rails new --edge i get the lastes version, and this is not wat i want.
I only need a more recent version of active:storage.

If i install rails 6.x and upgrade to edge i run into simular problems.
- first i have to set Rails.configuration.application_name by hand
- app:install
- db:migrate

But after this the first webpage requested makes the server crash. 
With no useable error message.

**Comment by ceritium** [comment]
Can you try with `SKIP_REQUIRE_WEBPACKER=true`?

```
SKIP_REQUIRE_WEBPACKER=true rails new app_name -m module.rb --database=postgresql --edge 
```

**Comment by Bodata** [comment]
Hi,
I am on windows... so this does not work on windows.
I tried on windows:
```
set SKIP_REQUIRE_WEBPACKER=true
rails new app_name -m module.rb --database=postgresql --edge
```

Same result, no such file or directory

**Comment by hahmed** [comment]
Could you try `rails new app_name --database=postgresql --edge` or even `rails new app_name --edge` and does that work? Webpacker is no longer enabled by default on edge, from the output it's not clear if this issue is related to webpacker/node or something else...

**Comment by Bodata** [comment]
@hahmed 
I have tried as you requested but same error at both options... with or without --database=postgresql
