### ISSUE TITLE
Rails.application.config_for causes ERB and YAML to be loaded every time

### ISSUE THREAD

**Issue by jclusso** [rails/rails#43151]
This seems like an oversight in the way configurations are loaded and used. We recently were trying to track down a memory leak and noticed that ERB and YAML was being loaded in places we didn't expect. Every time we use Rails.application.config_for to load configuration settings Rails is loading all of this. Is there a reason that configs aren't preloaded and then referenced?

**Comment by p8** [comment]
Looking at the implementation it seems one of the few configurations in Application that isn't memoized.
Unlike `secrects`, `credentials`, `env_config`.....
https://github.com/rails/rails/blob/cde95c83a9eb6c7b30a24a8469b764f0815dfc67/railties/lib/rails/application.rb#L241-L264
Not sure if that is intentional.

**Comment by rafaelfranca** [comment]
It is intentional. Make sure to store the result of the `config_for` in the `config` object of the Rails application. Something like:

```
config.my_custom_config = self.config_for("some_file")
```

**Comment by jclusso** [comment]
@rafaelfranca is this documented somewhere? Just curious. Thanks!

**Comment by p8** [comment]
@jclusso It is not. Do you want to create a PR?
The relevant sections are here:
https://github.com/rails/rails/blob/edf08301df28cb4ad95c1bf2a13aece5043c6b4e/railties/lib/rails/application.rb#L183
https://github.com/rails/rails/blame/main/guides/source/configuring.md#L2326

**Comment by jclusso** [comment]
@p8 after reviewing that it appears to be documented under this section. https://github.com/rails/rails/blob/a44fbb5dcacd3281116f7d9881a25e8f08f729a4/guides/source/configuring.md#custom-configuration
