### ISSUE TITLE
Mistype Japanese Text

### ISSUE THREAD

**Issue by ino-via** [rails/rails#43155]
- place
  - https://railsguides.jp/getting_started.html
- mistype
  - ~~`しかし、link_toヘルパーを用いるとさらに便利になります。link_toヘルパーの第1引数はリンクテキスト、第2引数はリンク先です。第2引数にモデルオブジェクトを渡すと、link_toが適切はパスヘルパーを呼び出してオブジェクトをパスに変換します。たとえば、link_toにarticleを渡すとarticle_pathというパスヘルパーが呼び出されます。これを用いると、 app/views/articles/index.html.erbは以下のように書き換えられます。`~~
  - `しかし、link_toヘルパーを用いるとさらに便利になります。link_toヘルパーの第1引数はリンクテキスト、第2引数はリンク先です。第2引数にモデルオブジェクトを渡すと、link_toが適切なパスヘルパーを呼び出してオブジェクトをパスに変換します。たとえば、link_toにarticleを渡すとarticle_pathというパスヘルパーが呼び出されます。これを用いると、 app/views/articles/index.html.erbは以下のように書き換えられます。`

**Comment by ghiculescu** [comment]
Thanks for the issue, but it looks like https://github.com/yasslab/railsguides.jp is the repo for railsguides.jp, based on the link at the bottom of the page. You might want to make an issue or PR there.

**Comment by ino-via** [comment]
> Thanks for the issue, but it looks like https://github.com/yasslab/railsguides.jp is the repo for railsguides.jp, based on the link at the bottom of the page. You might want to make an issue or PR there.

Thanks!
I follow your advise^^
