### ISSUE TITLE
AVIF image variants are assigned the wrong :content_type

### ISSUE THREAD

**Issue by brian-kephart** [rails/rails#43150]
### Steps to reproduce
[Repro](https://github.com/brian-kephart/avif)

### Expected behavior
AVIF image variant blobs should have a `:content_type` of `'image/avif'`

### Actual behavior
AVIF image variants have a `:content_type` of `'video/quicktime'` on the blob. At least they do when running on MacOS. The images display correctly in Chrome, but the "Content-type" header is wrong as a result of the incorrect attribute.

### System configuration
**Rails version**: Edge

**Ruby version**: 3.0

**Comment by georgeclaghorn** [comment]
You’ll want to report (and fix?) here: [rails/marcel](https://github.com/rails/marcel). Marcel is the library Active Storage uses to identify content types.

**Comment by brian-kephart** [comment]
Thanks, George. I looked at that but wasn't deep enough in to identify whether that was the issue. I'll report there.

**Comment by brian-kephart** [comment]
Fixed in https://github.com/rails/marcel/pull/63
