### ISSUE TITLE
Useless warning when overwriting existing scopes "Creating scope :foobar. Overwriting existing method"

### ISSUE THREAD

**Issue by westonganger** [rails/rails#43163]
When redefining scopes on a child class or class that uses a generic concern we are getting warning messages about overwriting methods that dont seem very useful, especially when you consider the nature of object oriented languages.

I dont want to see any warnings about overwriting existing method when redefining scopes.

For object oriented languages we simply understand that you can always override a method in a sub-class. Why doesnt this concept apply to scopes. This results in us having to add additional warning ignores, etc to handle these messages.

### Steps to reproduce
```ruby
module BasicScopesConcern
  extend ActiveSupport::Concern  

  included do
    scope :active, ->(){ where(active: true) }
    scope :active, ->(){ where(active: true) }
  end
end

class ApplicationRecord
  include BasicScopesConcern
end

class User < ApplicationRecord
  # has column `active` : boolean
end

class UserTeamLink < ApplicationRecord
  # has column `active` : boolean

  belongs_to :user
  belongs_to :team

  scope :active, ->(){ joins(:user).where(active: true, users: {active: true}) }
  scope :inactive, ->(){ left_joins(:user).where("user_team_links.active != ? OR users.active != ?", true, true)
end
```

### Expected behavior

I dont want to see any warnings about overwriting existing method

For object oriented languages we simply understand that you can always override a method in a sub-class. Why doesnt this concept apply to scopes. This results in us having to add additional warning ignores, etc to handle these messages.

### Actual behavior

Getting warnings messages like

```
Creating scope :active. Overwriting existing method UserTeamLink.active.
Creating scope :inactive. Overwriting existing method UserTeamLink.inactive.
```

### System configuration
Rails version: 6.1.4
Ruby version: 3.0.1

### Related Issues
https://github.com/rails/rails/issues/35499

**Comment by shqear93** [comment]
any updates on this?

**Comment by rafaelfranca** [comment]
This was removed before, but brought back https://github.com/rails/rails/pull/23331. I see the arguments in both camps, but, if we see `scope` just as a glorified way to do `def self.some_scope_name` it is better to not warn. Feel free to open a PR.

**Comment by marcelolx** [comment]
Since #43204 has been merged I think this can be closed @westonganger
