### ISSUE TITLE
Wrong where clause when filtering a has_many relation using parameters other than a hash

### ISSUE THREAD

**Issue by nagaroni** [rails/rails#43179]
I don't know if it is a bug or the intended behavior, but when filtering a has_many relation using parameters other than a hash the rails generated a wrong SQL where clause. for example:

```RUBY
# This would filter the posts.id instead of the comments.id
Post.joins(:comments).where(comments: 1).to_sql
# SELECT "posts".* FROM "posts" INNER JOIN "comments" ON "comments"."post_id" = "posts"."id" WHERE "posts"."id" = ? ORDER BY "posts"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
```

If that is not the expected behavior I think this small change would fix this behavior:

```ruby
# file: lib/active_record/relation/predicate_builder.rb:99
klass ||= AssociationQueryValue
queries = klass.new(associated_table, value).queries.map! do |query|
  # If the query produced is identical to attributes don't go any deeper.
  # Prevents stack level too deep errors when association and foreign_key are identical.
  query == attributes ? self[key, value] : expand_from_hash(key => query)
end
```

### Steps to reproduce

```ruby
#frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 6.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_filtering_relation_by_not_using_hash
    post = Post.create!
    other_post = Post.create!
    other_post.comments << Comment.create!
    post.comments << Comment.create!

    assert_equal Post.joins(:comments).where(comments: other_post.comment_ids).first, other_post
  end
end
```

### Expected behavior

It should generate a SQL where clause that filters by the comments.id

### Actual behavior

It generates a SQL where clause that filters by the posts.id

### System configuration

**Rails version**: 6.1.4.1

**Ruby version**: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

**Comment by yoelbl** [comment]
This also happens with a Hash.
`class BugTest < Minitest::Test
  def test_filtering_relation_by_not_using_hash
    post = Post.create!
    other_post = Post.create!
    other_post.comments << Comment.create!
    post.comments << Comment.create!
    puts Post.joins(:comments).where(comments: 1).to_sql
    puts Post.joins(:comments).where({comments: 1}).to_sql
  end
end`

`SELECT "posts".* FROM "posts" INNER JOIN "comments" ON "comments"."post_id" = "posts"."id" WHERE "posts"."id" = 1
SELECT "posts".* FROM "posts" INNER JOIN "comments" ON "comments"."post_id" = "posts"."id" WHERE "posts"."id" = 1`

**Comment by nagaroni** [comment]
I don't know @yoelbl, it seems strange to me raise an exception in this scenario, but it may be because I'm not seeing the big picture.
