### ISSUE TITLE
Incorrect dependency information in Active Storage guide

### ISSUE THREAD

**Issue by brian-kephart** [rails/rails#43182]
[The guide](https://github.com/rails/rails/blob/b4ccee7a8a571261c047066b7f9a3c1d5f1bddb5/guides/source/active_storage_overview.md#L40) states:

> libvips or ImageMagick v8.6+ for image analysis and transformations

8.6 seems right for libvips, but the current version of ImageMagick is only 7.1.0, so that's incorrect. Can anyone tell me what version of ImageMagick is required?

**Comment by p8** [comment]
Ah, those got swapped but the version wasn't swapped.
https://github.com/rails/rails/pull/42744
cc @brenogazzola 

Not sure if there is a minimal version but we use `6.9` for ImageMagick.

**Comment by brenogazzola** [comment]
Oh, ops. My bad. I inverted them because vips was the primary now and forgot about the version. We can probably ask @ghiculescu to fix that in #42910

I'm not aware of of a minimal version for ImageMagick, but its 8.6 for libvips as defined by `image_processing` gem.

**Comment by ghiculescu** [comment]
This will be fixed in https://github.com/rails/rails/pull/42910
