### ISSUE TITLE
Integer#change_sign

### ISSUE THREAD

**Issue by ekampp** [rails/rails#43184]
Hi there, everyone. 

I have a need to change the sign of an integer and I couldn't find it in the existing codebase so I extended the `Integer` class, and it seems to be working pretty well. 

```ruby
class Integer
  # Changes the Integer's sign from positive to negative or vice versa.
  #
  # Example:
  #
  #   int = 1
  #   int.positive? # => true
  #   int.negative? # => false
  #   int == 1      # => true
  #   int == -1     # => false
  #
  #   int = 1.change_sign
  #   int.positive? # => false
  #   int.negative? # => true
  #   int == 1      # => false
  #   int == -1     # => true
  #
  def change_sign(sign = nil)
    case sign.to_s.downcase.to_sym
    when :positive, :+ then abs
    when :negative, :- then -abs
    else -self
    end
  end
end
```

I wanted to make a PR to bring this into Rails, but I don't know where the right place for it is. I was thinking ActiveSupport? I would like a little guidance here. 

Thanks in advance.

**Comment by rafaelfranca** [comment]
Thank you for the proposal but I don't think we would need this in the framework. It is possible for you to implement this in your application or even in a gem.

**Comment by ekampp** [comment]
Hi, @rafaelfranca, yes, it is. Like I stated, I have already done so.

I'm not asking if you want it, but where it should live. I will make a PR, and we can have a more in-depth discussion than you off-handedly discarding it?
