### ISSUE TITLE
why does your error handling in console blow

### ISSUE THREAD

**Issue by svey** [rails/rails#43183]
### Steps to reproduce

do some bad shit in the console and look at the output... some where in the console there is a small snippet of text that is ACTUALLY USEFUL, usually buried in a lot of hot garbage

**Comment by rafaelfranca** [comment]
Thank you so much for such detailed issue. What you see as hot garbage is important information for some people in some situation. You can disable stack trace easily if you want.

See https://stackoverflow.com/questions/34098894/disable-stack-trace-display-in-rails-console
