### ISSUE TITLE
Enum definition is ignored when combined with attribute definition on Rails 6.1

### ISSUE THREAD

**Issue by voraciousdev** [rails/rails#43196]
### Steps to reproduce

In Rails 6.0 (and prior), using an `enum` definition in combination with an `attribute` definition would allow us to specify a default value for enums at the model level without adding a database default. In Rails 6.1, the `attribute` definition overrides the `enum` definition without warning and allows any values to be set on the enum field.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 6.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :things, force: true do |t|
    t.string :state
  end
end

class Thing < ActiveRecord::Base
  enum state: {
    started: :started,
    stopped: :stopped,
  }
  attribute :state, :string, default: :started
end

class BugTest < Minitest::Test
  def test_happy_path
    thing = Thing.create!

    assert_equal 'started', thing.state
  end

  def test_sad_path
    thing = Thing.create!

    assert_raises ArgumentError do
      thing.state = :invalid
    end
  end
end
```

### Expected behavior

An `ArgumentError` exception should be raised.

### Actual behavior

Nothing is raised.

### System configuration

**Rails version**: 6.1.4.1

**Ruby version**: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]

**Comment by voraciousdev** [comment]
For those that encounter this, the fix is to use the new `_default:` key on the enum definition. E.g.

```ruby
class Thing < ActiveRecord::Base
  enum state: {
    started: :started,
    stopped: :stopped,
  }, _default: :started
end
```

That said, I'd still love to hear whether or not this effect was intended.

**Comment by ghiculescu** [comment]
@kamipo do you know if this was intended? I assume the new call to `attribute` [here](https://github.com/rails/rails/pull/39820/files#diff-a0de22dc0114613fdc67f48c916e70b9983ef47bcc84b96232c36398af1d166fR185) is what's causing the change in behaviour.

**Comment by federicoaldunate** [comment]
I don't think this is intended.
We have this test in `enum_test.rb`
```ruby
  test "enum on custom attribute with default" do
    klass = Class.new(ActiveRecord::Base) do
      self.table_name = "books"
      attribute :status, default: 2
      enum status: [:proposed, :written, :published]
    end

    assert_equal "published", klass.new.status
  end
```

**Comment by intrip** [comment]
Let me add that "attribute" API [was private back then](https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/activemodel/lib/active_model/attributes.rb#L19) hence I argue that breaking it was expected at the time being.

**Comment by jessieay** [comment]
> ,
