### ISSUE TITLE
`primary_key` option doesn't work with polymorphic associations

### ISSUE THREAD

**Issue by stephannv** [rails/rails#43193]
### Steps to reproduce
```ruby
require 'bundler/inline'

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'activerecord', '6.1.4.1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :messages do |t|
    t.references :messageable, polymorphic: true, index: true, type: :string
  end

  create_table :users do |t|
    t.string :email, null: false
  end
end

class Message < ActiveRecord::Base
  belongs_to :messageable, polymorphic: true, inverse_of: :messages
end

class User < ActiveRecord::Base
  has_many :messages, as: :messageable, primary_key: :email, inverse_of: :messageable
end

class Test < Minitest::Test
  def test_relationship
    user = User.create! email: 'example@example.com'
    message = Message.new
    message.messageable = user
    message.save!
    assert_equal message.messageable_id, user.email
  end
end
```

### Expected behavior
The `{relation}_id` should be filled with attribute assigned as `primary_key` on `has_many` relation. Eg.: use `email` instead `id`.

### Actual behavior
The `{relation}_id` is being filled with table primary key.

### System configuration
**Rails version**:
6.1.4.1

**Ruby version**:
3.0.1

**Comment by stephannv** [comment]
My situation:
I have a old table: `User (id: Integer, uuid_ref: UUID)`
I created a new table: `Message (id: UUID, messageable_id: UUID, messageable_type: String)`
I want to create a relationship between user and message using `uuid_ref` column. But Rails is trying to use `id` column.

**Comment by eslamodeh** [comment]
@stephannv According to the documentation, you have to override the primary key class method to use the `email` instead of the `id`.

```
class User < ActiveRecord::Base
  self.primary_key = :email
  has_many :messages, as: :messageable, inverse_of: :messageable
end
```

**Comment by stephannv** [comment]
@eslamodeh but I want `email` as primary_key only for `messages` relationship, other models will keep using `id`. For example:
```ruby
class Message < ActiveRecord::Base
  belongs_to :messageable, polymorphic: true, inverse_of: :messages
end

class User < ActiveRecord::Base
  has_many :addresses # using :id
  has_many :messages, as: :messageable, primary_key: :email, inverse_of: :messageable # this should use :email
end

class Address < ActiveRecord::Base
  belong_to :user
end
```

**Comment by eslamodeh** [comment]
@stephannv I am not sure if that's doable or not (Hence you can't have multiple primary keys in the same table). A related issue you can find here https://github.com/rails/rails/issues/35803

**Comment by abhishek-coupa** [comment]
This is still reproducible in Rails 6
