### ISSUE TITLE
ActiveModel::Error with options containing Proc can't be serialized using Marshal.dump

### ISSUE THREAD

**Issue by sundling** [rails/rails#43195]
### Steps to reproduce

This problem occur when using conditional validations using procs for :if/:unless
(https://edgeguides.rubyonrails.org/active_record_validations.html#using-a-proc-with-if-and-unless)

I was trying to output/log validation errors after a failed validation using `error.message`. 
https://github.com/rails/rails/blob/6-1-stable/activemodel/lib/active_model/error.rb#L134

That method then pass the call on to https://github.com/rails/rails/blob/0c3e02cb520a1a7a913dd76d631bea03d6dd9764/activemodel/lib/active_model/error.rb#L64
which in turn calls `I18n.translate` at the end, with all options from the Error instance.
The actual call to `Marshal.dump` is made by the gem `i18n-active_record` which my application has a dependency on.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "6.1.4"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base; end

class BugTest < Minitest::Test
  def test_marshal_dump
    subject = ActiveModel::Error.new(Post.new, :title, :too_short, if: -> { true }, count: 30, something: "else")

    assert_equal subject.inspect, Marshal.load(Marshal.dump(subject)).inspect
  end
end
```

### Expected behavior
It should be possible to Marshal.dump the ActiveModel::Error instance

### Actual behavior
An exception is thrown
```
TypeError: no _dump_data is defined for class Proc
```

### System configuration
**Rails version**: 6.1.4 & Rails main branch

**Ruby version**: 2.7.4

**Comment by rafaelfranca** [comment]
Thank you for the issue. It is true that procs can't be marshalled, but there is not much we can do. The gem that is trying to marshal that object that should take care of dealing with this limitation.

**Comment by rafaelfranca** [comment]
> which in turn calls I18n.translate at the end, with all options from the Error instance.

That is actually not correct. It exclude all the callbacks options. If the i18n-active_record gem use interception the options passed to `I18n.t` the procs should not be there. Are you sure they are?

**Comment by rafaelfranca** [comment]
I also searched by Marshal.dump in i18n-active_record and could not find any.

Your reproduction steps are not really doing what your code is supposedly doing. The steps you used to reproduce are not supported and that exception is actually expected. If your code is actually marshalling an `ActiveModel::Error` instance it should transform it to a string first.

**Comment by sundling** [comment]
Thank you for the feedback.
When attempting to make a minimal reproduction case it seems I got a little off course. :)

The problematic bit for me is actually when enabling I18n caching.
```ruby
I18n::Backend::Simple.send(:include, I18n::Backend::Cache)
I18n.cache_store = ActiveSupport::Cache.lookup_store(:memory_store)
```
***

> > which in turn calls I18n.translate at the end, with all options from the Error instance.
> 
> That is actually not correct. It [exclude](https://github.com/rails/rails/blob/0c3e02cb520a1a7a913dd76d631bea03d6dd9764/activemodel/lib/active_model/error.rb#L137) all the [callbacks options](https://github.com/rails/rails/blob/0c3e02cb520a1a7a913dd76d631bea03d6dd9764/activemodel/lib/active_model/error.rb#L10). If the i18n-active_record gem use interception the options passed to `I18n.t` the procs should not be there. Are you sure they are?

Yes, it is correct that the options are filtered before being passed to `generate_message` but the method also takes an argument `base` which is a reference to the ActiveRecord instance. That instance has not been filtered and the errors attribute still contain all callbacks options.
The ActiveRecord instance is then [added](https://github.com/rails/rails/blob/167f5c80658a15b5aa2524433affe52553e2c8d9/activemodel/lib/active_model/error.rb#L72) to the options hash before `I18n.t` is called, triggering the exception.

> I also searched by Marshal.dump in i18n-active_record and could not find any.
> 
> Your reproduction steps are not really doing what your code is supposedly doing. The steps you used to reproduce are not supported and that exception is actually expected. If your code is actually marshalling an `ActiveModel::Error` instance it should transform it to a string first.

That was a red herring, sorry about that.
The Marshal.dump that triggered it actually exist in https://github.com/rails/rails/blob/0c3e02cb520a1a7a913dd76d631bea03d6dd9764/activesupport/lib/active_support/cache.rb#L841 and is called from https://github.com/rails/rails/blob/0c3e02cb520a1a7a913dd76d631bea03d6dd9764/activesupport/lib/active_support/cache/memory_store.rb#L36
***

Here is a better representation of the actual code im trying to run
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "6.1.4"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

I18n::Backend::Simple.send(:include, I18n::Backend::Cache)
I18n.cache_store = ActiveSupport::Cache.lookup_store(:memory_store)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
  validates :title, length: { minimum: 10 }, if: -> { true }
end

class BugTest < Minitest::Test
  def test_marshal_dump
    post = Post.new(title: "My post")
    post.save

    assert_equal "Title is too short (minimum is 10 characters)", post.errors.first.full_message
  end
end
```
