### ISSUE TITLE
`config.assets.debug = true` no longer works in development

### ISSUE THREAD

**Issue by josh-m-sharpe** [rails/rails#43203]
Quick Summary:

The rails configuration `config.assets.debug = true` used to split asset-pipeline generated assets into individual 'debug' files instead of compiling them all together into a single file.  The configuration appears to have no effect in that regard anymore.  This is a problem for large applications with a large js file.  In our case we're seeing 2+ minutes compile times in development every time anything referenced through a manifest file is changed.

This is presumably related/duplicate of these closed issues:

- https://github.com/rails/sprockets/issues/162
- https://github.com/rails/sprockets/issues/157
- https://github.com/rails/webpacker/issues/1199

I attempted removing the sourcemap preprocessor (as suggested here: https://discuss.rubyonrails.org/t/disable-source-maps-support-in-sprockets-4/75266/2) by commenting these lines out: 
https://github.com/rails/sprockets/blob/master/lib/sprockets.rb#L223-L225 - It had no effect.  So, not sure the assumption in https://github.com/rails/sprockets/issues/157 that this is a source maps issue is correct?  Maybe?

I created a demo app to reproduce with latest rails (6.1.4.1) and latest sprockets (4.0.2 - which was the version that rails 6.1.4.1 went with).  So, all defaults here.  https://github.com/josh-m-sharpe/assets_test

Should be something like: `bundle ; yarn install ; rails s` view source and note that there is only a single `/assets/application.debug-<hash>.js` file which includes the contents of both foo.js and bar.js.  I would expect to see (in development) a `/assets/foo.debug-<hash>.js` and `/assets/bar.debug-<hash>.js` files as well.

Note: I apologize for opening another issue on this topic, but https://github.com/rails/sprockets/issues/162 was closed many moons ago and wasn't addressed with the closure of https://github.com/rails/sprockets/issues/157. I also opened it here because high-level this is a rails feature. sprockets/sprockets-rails are implementation details.  The setting is configured in rails configuration files and still mentioned in the guides: https://guides.rubyonrails.org/asset_pipeline.html#turning-debugging-off. Maybe the 'fix' for this is that rails isn't going to support this feature anymore - which is OK (but sad) - in which case there's rails cleanup to be done.  Cheers and Thanks!

**Comment by josh-m-sharpe** [comment]
Not stale.  Still a real thing.

**Comment by ghiculescu** [comment]
My read of https://github.com/rails/sprockets/issues/162#issuecomment-158524035 is that this is working correctly, since it is source mapped to two separate files:

![image](https://user-images.githubusercontent.com/509837/145470366-4c9ec888-f162-497c-bc22-17d55563fe6f.png)

If nothing else, the docs should be updated to make that more clear.

**Comment by ghiculescu** [comment]
https://github.com/rails/sprockets/blob/master/guides/source_maps.md#what-is-a-source-map suggests this is intentional too. At least since sprockets 4.

> A source map is a standard that allows assets bundled into one file to declare a "source map" that lets browsers know what code came from what sources.

**Comment by ghiculescu** [comment]
For what it's worth, we also have a large amount of JS that goes through sprockets, in a big old monolith. This much:

![image](https://user-images.githubusercontent.com/509837/145472201-6b09e5b4-3cfd-4c9a-9b28-8c5191215cca.png)
![image](https://user-images.githubusercontent.com/509837/145472217-4d895d46-4186-478b-87ca-2adfd3e0d6d5.png)

We run with `config.assets.debug = false`. When changes to a JS file are made, it is ~instant. So I wonder if there is something else going on that it is making it slow for you.

We use `sprockets (3.7.2)` and `sprockets-rails (3.2.1)`.

We also have these settings in development.rb, which you may find helpful.

```ruby
  # https://github.com/rails/sprockets-rails/blob/v3.2.2/README.md#initializer-options
  # When set to a falsey value it will raise an error when no asset is found in the pipeline.
  config.assets.unknown_asset_fallback = false
  # When enabled, an exception is raised for missing assets. This option is enabled by default.
  # To make app boot faster for devs, we only run this in test/staging (not development).
  config.assets.check_precompiled_asset = false
```

**Comment by josh-m-sharpe** [comment]
@ghiculescu there's a demo app in the description of this ticket that's basically barebones rails I created a while back.  If you can tell me what's wrong with it I'd be much obliged.

**Comment by josh-m-sharpe** [comment]
Apologies, I see what you're saying.  The issue is that debug mode is concating everything into a single file now.  It used to be such that foo.js and bar.js were served up in different files.  The result of that is that if I change any javascript anywhere, the entire package has to be recompiled - which is slow.

**Comment by ghiculescu** [comment]
How much JS are you serving? Is it a lot more than the screenshots I showed above? I'm surprised it's really slow; in my experience it's pretty quick even with big files.

That said I just found https://github.com/rails/sprockets-rails/blob/5c0ecb004e4f20f3e29147765d9063427072489a/lib/sprockets/rails/helper.rb#L140 so I'm gonna try and debug your test app a bit more...

**Comment by ghiculescu** [comment]
One thing I will say is that if you downgrade to `sprockets` 3 you get the behavior you're looking for.

![image](https://user-images.githubusercontent.com/509837/145490789-42892b22-0b79-416b-adcc-c297bc26e39b.png)
![image](https://user-images.githubusercontent.com/509837/145490855-d01cc05e-add2-4786-af57-d876a605ce4f.png)

**Comment by ghiculescu** [comment]
I've made https://github.com/rails/rails/pull/43825 to make the docs correct for Rails 7 / latest Sprockets
