### ISSUE TITLE
Autoloading helpers fails initially in Rails 7.x, but succeeds on the second attempt

### ISSUE THREAD

**Issue by bradgessler** [rails/rails#43205]
### Steps to reproduce

When I try loading a Rails Application in Ruby 7.0, the `app/helpers` autoload path does not appear to be working from my gems engine.

Here's the script to reproduce the issue **NOT working** under 7.0:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "sitepress", github: "sitepress/sitepress", branch: "rails-7"
  gem "rails", github: "rails/rails", branch: "main"
end

require "sitepress/server"  # Load all the stuff needed setup the configuration below.

# Setup defaults for stand-alone Sitepress server in the current path. This
# can, and should, be over-ridden by the end-user in the `config/site.rb` file.
Sitepress.configure do |config|
  config.routes = false
  config.site = Sitepress::Site.new root_path: "."
end

# Create the module that should autoload without an issues.
require 'fileutils'
FileUtils.mkdir_p 'helpers'
File.write "helpers/foo_helper.rb", "module FooHelper; end;"

# Boot the Rails app
app = Sitepress::Server
app.initialize!

puts "Loading ::SiteController fails in Rails 7.0"
# See https://github.com/sitepress/sitepress/blob/rails-7/sitepress-rails/lib/sitepress/engine.rb#L15 for helper path configuration
# See https://github.com/sitepress/sitepress/blob/rails-7/sitepress-server/lib/sitepress/server.rb for the configuration of the Rails app this boots
p ::SiteController # This will raise an exception
```

Now for code that shows this **WORKING** under Rails 6:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "sitepress", github: "sitepress/sitepress", branch: "rails-7"
  gem "rails"
end

require "sitepress/server"  # Load all the stuff needed setup the configuration below.

# Setup defaults for stand-alone Sitepress server in the current path. This
# can, and should, be over-ridden by the end-user in the `config/site.rb` file.
Sitepress.configure do |config|
  config.routes = false
  config.site = Sitepress::Site.new root_path: "."
end

# Create the module that should autoload without an issues.
require 'fileutils'
FileUtils.mkdir_p 'helpers'
File.write "helpers/foo_helper.rb", "module FooHelper; end;"

# Boot the Rails app
app = Sitepress::Server
app.initialize!

puts "Loading ::SiteController succeeds in Rails 6.x"
p ::SiteController # This will not raise an exception
```

Finally, in a third example under Rails 7.0, I demonstrate that this is **WORKING** when I attempt to load the constant a second time:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "sitepress", github: "sitepress/sitepress", branch: "rails-7"
  gem "rails", github: "rails/rails", branch: "main"
end

# require "sitepress/boot"
require "sitepress/server"  # Load all the stuff needed setup the configuration below.

# Setup defaults for stand-alone Sitepress server in the current path. This
# can, and should, be over-ridden by the end-user in the `config/site.rb` file.
Sitepress.configure do |config|
  config.routes = false
  config.site = Sitepress::Site.new root_path: "."
end

# Create the module that should autoload without an issues.
require 'fileutils'
FileUtils.mkdir_p 'helpers'
File.write "helpers/foo_helper.rb", "module FooHelper; end;"

# Boot the Rails app
app = Sitepress::Server
app.initialize!

puts "Loading ::SiteController fails in Rails 7.0 on the first attempt"
begin
  p ::SiteController
rescue => e
  puts "Failed with #{e.inspect}"
end

puts "Loading ::SiteController succeeds in Rails 7.0 on the second attempt"
p ::SiteController
```

The following source files may be helpful to help diagnose the issue:
* https://github.com/sitepress/sitepress/blob/rails-7/sitepress-rails/lib/sitepress/engine.rb#L15 for helper path configuration
* https://github.com/sitepress/sitepress/blob/rails-7/sitepress-server/lib/sitepress/server.rb for the configuration of the Rails app this boots

### Expected behavior

I expect the `FooHelper` to be resolved in Rails 7.x, as it does in Rails 6.x. Here's what a succesful script run looks like from above:

```
SiteController
```

### Actual behavior

The `FooHelper` module is not resolved when Rails attempts to find it. Here's what the error looks like from the first Rails 7.x script above:

```
/Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/bundler/gems/rails-a692e63bf400/activesupport/lib/active_support/inflector/methods.rb:280:in `constantize': uninitialized constant FooHelper (NameError)
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/bundler/gems/rails-a692e63bf400/activesupport/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/bundler/gems/rails-a692e63bf400/actionpack/lib/abstract_controller/helpers.rb:177:in `block in modules_for_helpers'
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/bundler/gems/rails-a692e63bf400/actionpack/lib/abstract_controller/helpers.rb:170:in `map!'
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/bundler/gems/rails-a692e63bf400/actionpack/lib/abstract_controller/helpers.rb:170:in `modules_for_helpers'
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/bundler/gems/rails-a692e63bf400/actionpack/lib/action_controller/metal/helpers.rb:104:in `modules_for_helpers'
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/bundler/gems/rails-a692e63bf400/actionpack/lib/abstract_controller/helpers.rb:148:in `helper'
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/bundler/gems/rails-a692e63bf400/actionpack/lib/action_controller/railties/helpers.rb:19:in `inherited'
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/bundler/gems/sitepress-cd078ab7255c/sitepress-server/rails/app/controllers/application_controller.rb:1:in `<top (required)>'
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.0.beta3/lib/zeitwerk/kernel.rb:27:in `require'
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.0.beta3/lib/zeitwerk/kernel.rb:27:in `require'
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/bundler/gems/sitepress-cd078ab7255c/sitepress-server/rails/app/controllers/site_controller.rb:1:in `<top (required)>'
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.0.beta3/lib/zeitwerk/kernel.rb:27:in `require'
	from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.0.beta3/lib/zeitwerk/kernel.rb:27:in `require'
	from bug.rb:40:in `<main>'
```

### System configuration

**Rails version**: 7.x

**Ruby version**: 3.x

**Comment by rafaelfranca** [comment]
This could be an issue on sitepress. Are you able to reproduce in a regular Rails application without using Sitepress?

**Comment by bradgessler** [comment]
Short answer is no, I haven't tried reproducing this in a vanilla Rails 7.x app. I doubt its an issue there since helpers are so heavily tested.

The longer answer is that Sitepress itself is a stripped-down Rails application (see https://github.com/sitepress/sitepress/blob/rails-7/sitepress-server/lib/sitepress/server.rb). The paths that are not loading are set in an engine (see https://github.com/sitepress/sitepress/blob/rails-7/sitepress-rails/lib/sitepress/engine.rb#L21-L26). While its not a full-blown Rails application in a `rails new foo_bar`, it should serve as a simpler use case since it is only loading a subset of Rails.

The reason I think this is of interest is that if I'm seeing this strange behavior in what should be a "simple use case", it will appear in more complicated rails apps and/or gems.

If this turns out to not be a bug in the Rails 7.x autoloading features, I'd guess that whatever I've found is worth documenting in the autoloading change log, autoloading docs, or the Rails engine docs.

**Comment by fxn** [comment]
I've played around for a few minutes. Some details I see:

First, let's eliminate case (3) from the equation. In Ruby, you know that if you have this

```ruby
# foo.rb
class Foo
  raise
  def x
  end
end
```

and then

```ruby
begin
  require "foo"
rescue
  # ignored
end

Foo
```

That works, because the `Foo` constant was actually defined. You are not loading again and succeeding, it was the first load the succeeded partially. Of course, instances of `Foo` won't respond to `#x`, that is expected.

That is in essence what is happening in case (3).

There's one difference between case (1) and case (2), if you

```ruby
pp ActiveSupport::Dependencies.autoload_paths
```

after initialization, you'll see `tmp/helpers` is present in (2), and missing in (1).

I don't know why is that yet, just reached this point by now, but looks like the problem is the configurations, for some reason, are different between both versions.

I'll try to dig into it, thanks a lot for testing the alpha ❤️.

**Comment by bradgessler** [comment]
I tested against `alpha2` and dug into some of the docs in there to see if any of the new info in the README (https://github.com/rails/rails/blob/main/guides/source/autoloading_and_reloading_constants.md) would help out. 

I discovered `Rails.autoloaders.log!` and dropped that into the loading. Here's what I get on the first attempt to load `::SiteController`

```ruby
[1] pry(#<Sitepress::CLI>)> pp ActiveSupport::Dependencies.autoload_paths
["/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers",
 "/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/helpers",
 "/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers",
 "/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/concerns"]
=> ["/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers",
 "/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/helpers",
 "/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers",
 "/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/concerns"]
[2] pry(#<Sitepress::CLI>)> ::SiteController
Zeitwerk@rails.main: constant ApplicationHelper loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/helpers/application_helper.rb
NameError: uninitialized constant PageHelper
from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/inflector/methods.rb:280:in `constantize'
```

Then on the second attempt:

```ruby
[3] pry(#<Sitepress::CLI>)> pp ActiveSupport::Dependencies.autoload_paths
["/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers",
 "/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/helpers",
 "/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers",
 "/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/concerns"]
=> ["/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers",
 "/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/helpers",
 "/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers",
 "/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/concerns"]
[4] pry(#<Sitepress::CLI>)> ::SiteController
Zeitwerk@rails.main: constant ApplicationController loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/application_controller.rb
Zeitwerk@rails.main: constant Sitepress::SitePages loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/concerns/sitepress/site_pages.rb
Zeitwerk@rails.main: constant SiteController loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/site_controller.rb
=> SiteController
```

From what I observe, the `ActiveSupport::Dependencies.autoload_paths` are the same between both attempts, but the Zeitwork logger is kicking in on the second attempt to reference that controller.

---

@fxn people don't say this enough in OSS projects, but much 🤟and 🤗  for digging into this issue. I'm going to keep working at it too and see if I can understand the problem better.

**Comment by bradgessler** [comment]
I found another surprising thing: the `Rails.autoloaders.main.autoloads` paths changes *after* `::SiteController` successfully loads on the second attempt.

```ruby
[1] pry(#<Sitepress::CLI>)> Rails.autoloaders.main.autoloads
=> #<Zeitwerk::Autoloads:0x00007fef91204f30
 @a2c=
  {"/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/application_controller.rb"=>[Object, :ApplicationController],
   "/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/site_controller.rb"=>[Object, :SiteController],
   "/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/helpers/application_helper.rb"=>[Object, :ApplicationHelper],
   "/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/sitepress/site_controller.rb"=>[Sitepress, :SiteController],
   "/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/concerns/sitepress/site_pages.rb"=>[Sitepress, :SitePages]},
 @c2a=
  {[Object, :ApplicationController]=>"/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/application_controller.rb",
   [Object, :SiteController]=>"/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/site_controller.rb",
   [Object, :ApplicationHelper]=>"/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/helpers/application_helper.rb",
   [Sitepress, :SiteController]=>"/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/sitepress/site_controller.rb",
   [Sitepress, :SitePages]=>"/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/concerns/sitepress/site_pages.rb"}>
[2] pry(#<Sitepress::CLI>)> ::SiteController
Zeitwerk@rails.main: constant ApplicationHelper loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/helpers/application_helper.rb
NameError: uninitialized constant PageHelper
from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/inflector/methods.rb:280:in `constantize'
```

Then I try it again:

```ruby
[3] pry(#<Sitepress::CLI>)> Rails.autoloaders.main.autoloads
=> #<Zeitwerk::Autoloads:0x00007fef91204f30
 @a2c=
  {"/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/application_controller.rb"=>[Object, :ApplicationController],
   "/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/site_controller.rb"=>[Object, :SiteController],
   "/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/sitepress/site_controller.rb"=>[Sitepress, :SiteController],
   "/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/concerns/sitepress/site_pages.rb"=>[Sitepress, :SitePages]},
 @c2a=
  {[Object, :ApplicationController]=>"/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/application_controller.rb",
   [Object, :SiteController]=>"/Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/site_controller.rb",
   [Sitepress, :SiteController]=>"/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/sitepress/site_controller.rb",
   [Sitepress, :SitePages]=>"/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/concerns/sitepress/site_pages.rb"}>
[4] pry(#<Sitepress::CLI>)> ::SiteController
Zeitwerk@rails.main: constant ApplicationController loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/application_controller.rb
Zeitwerk@rails.main: constant Sitepress::SitePages loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/concerns/sitepress/site_pages.rb
Zeitwerk@rails.main: constant SiteController loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/site_controller.rb
```

Finally when I run `Rails.autoloaders.main.autoloads` after the controller is successfully loaded, I get a different set of autoload paths:

```ruby
[5] pry(#<Sitepress::CLI>)> Rails.autoloaders.main.autoloads
=> #<Zeitwerk::Autoloads:0x00007fef91204f30
 @a2c={"/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/sitepress/site_controller.rb"=>[Sitepress, :SiteController]},
 @c2a={[Sitepress, :SiteController]=>"/Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/sitepress/site_controller.rb"}>
```

I'd expect these paths to not change after the application & Rails boot successfully (assuming no mutations after that)

**Comment by fxn** [comment]
Regarding the first message, in the first attempt [this](https://github.com/rails/rails/blob/e21c38ed7f9161e07e73afe2899f26ab7a260231/actionpack/lib/abstract_controller/helpers.rb#L177) tries to load `FooHelper`, and fails. Because the configuration does not have the directory. In the second attempt, you move on because of the partial evaluation, that code is not executed again, and you are able to move on.

Regarding the second one. That is internal, private state, and it is [mutated in place](https://github.com/fxn/zeitwerk/blob/e91f0eb4b7c4bbd41cedf39a19890e0e1a15d242/lib/zeitwerk/loader/callbacks.rb#L11).

I believe our best hint so far is that the configuration is wrong. In Rails 6, the directory that contains `FooHelper` is not in the autoload paths. That is the root of everything (I believe!), `FooHelper` cannot be autoloaded in the Rails 7 example, and that squares because the configuration does not have it. However, to debug that I'll need to understand your engine, I suspect.

Something that we could do is bisect `rails/main`.

**Comment by bradgessler** [comment]
I'm narrowing down the problem to eager loading. First attempt:

```ruby
[1] pry(#<Sitepress::CLI>)> Rails.autoloaders.main.eager_load
Zeitwerk@rails.main: eager load start
Zeitwerk@rails.main: constant ApplicationHelper loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/helpers/application_helper.rb
NameError: uninitialized constant PageHelper
from /Users/bradgessler/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0.alpha2/lib/active_support/inflector/methods.rb:280:in `constantize'
```

Second attempt:

```ruby
[2] pry(#<Sitepress::CLI>)> Rails.autoloaders.main.eager_load
Zeitwerk@rails.main: eager load start
Zeitwerk@rails.main: constant ApplicationController loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/application_controller.rb
Zeitwerk@rails.main: constant Sitepress::SitePages loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/concerns/sitepress/site_pages.rb
Zeitwerk@rails.main: constant SiteController loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-server/rails/app/controllers/site_controller.rb
Zeitwerk@rails.main: constant Sitepress::SiteController loaded from file /Users/bradgessler/Projects/sitepress/gem/sitepress-rails/rails/app/controllers/sitepress/site_controller.rb
Zeitwerk@rails.main: eager load end
=> nil
```

> Regarding the second comment. That is internal, private state, and it is mutated in place.

I see that now. Thanks for pointing this out.

> I believe our best hint so far is that the configuration is different

When you say configuration do you mean my application's configuration or a change to the overall Rails configuration?

**Comment by fxn** [comment]
> When you say configuration do you mean my application's configuration or a change to the overall Rails configuration?

Rails configures Zeitwerk with the contents of `ActiveSupport::Dependencies.autoload_paths` by the end of application boot, in what we call [the finisher](https://github.com/rails/rails/blob/e21c38ed7f9161e07e73afe2899f26ab7a260231/railties/lib/rails/application/finisher.rb#L18-L46).

In your examples, after initialization, `ActiveSupport::Dependencies.autoload_paths` in Rails 6 contains the directory where `FooHelper` lives, and in Rails 7, the directory is not there. Hence, `FooHelper` is not autoloaded (this is consistent with the autoload paths configured). So, what happens after `FooHelper` is not that much important, those are side-effects of partially evaluated code.

What we have to understand is why are the autoload paths different.

**Comment by fxn** [comment]
```ruby
# Boot the Rails app
app = Sitepress::Server
app.initialize!

pp ActiveSupport::Dependencies.autoload_paths
```

see what that prints in Rails 7 and Rails 6.

**Comment by bradgessler** [comment]
I did a git bisect. Here's what I got as far as "the first bad commit":

```
2306a8e645627a7913e161b76eeeb7ee6e6724a9 is the first bad commit
commit 2306a8e645627a7913e161b76eeeb7ee6e6724a9
Author: Xavier Noria <fxn@hashref.com>
Date:   Tue Aug 17 05:23:51 2021 +0200

    Setup the once autoloader on bootstrap

 actionpack/test/controller/helper_test.rb          |  4 +-
 actionview/test/actionpack/abstract/helper_test.rb |  8 ++--
 activesupport/lib/active_support/dependencies.rb   |  4 ++
 .../dependencies/zeitwerk_integration.rb           | 50 +-------------------
 railties/lib/rails/application/bootstrap.rb        | 17 +++++++
 railties/lib/rails/application/finisher.rb         | 24 +++++++++-
 railties/lib/rails/engine.rb                       | 29 +++++++-----
 railties/test/application/configuration_test.rb    | 54 ----------------------
 .../test/application/zeitwerk_integration_test.rb  | 48 +++++++++++++++++++
 9 files changed, 116 insertions(+), 122 deletions(-)
```

**Comment by fxn** [comment]
That is awesome, and indeed that commit looks like could be related. It's almost midnight here, I'll continue in another moment, but I believe we have moved forward understanding the issue. Thanks a lot!!!

**Comment by bradgessler** [comment]
I think I found the problem: https://github.com/rails/rails/commit/2306a8e645627a7913e161b76eeeb7ee6e6724a9#diff-c72ea90e9c6b7c60285006ea4c34548ae9257dffcda0c1b2f41fffd75a14363bR578-R580.

Any rails engine that depends on the `before: :set_autoload_paths` would break from this change. If I change that to `before: :setup_main_autoloader` it works.

In my engine when I change:

```ruby
    # Load paths from `Sitepress#site` into rails so it can render views, helpers, etc. properly.
    initializer :set_sitepress_paths, before: :set_autoload_paths do |app|
      app.paths["app/helpers"].push site.helpers_path.expand_path
      app.paths["app/assets"].push site.assets_path.expand_path
      app.paths["app/views"].push site.root_path.expand_path
      app.paths["app/views"].push site.pages_path.expand_path
    end
```

to:

```ruby
    # Load paths from `Sitepress#site` into rails so it can render views, helpers, etc. properly.
    initializer :set_sitepress_paths, before: :setup_main_autoloader do |app|
      app.paths["app/helpers"].push site.helpers_path.expand_path
      app.paths["app/assets"].push site.assets_path.expand_path
      app.paths["app/views"].push site.root_path.expand_path
      app.paths["app/views"].push site.pages_path.expand_path
    end
```

it works.

**Comment by bradgessler** [comment]
I know that Rails engines are not that well documented and the API, particularly the callbacks, are brittle. I'm OK with that since Rails engine developers are more technically inclined and can release updates, but I would call this a regression.

The ideal fix would be for the `7.x` codebase to setup the initializer callback behaviors to fire roughly in the order of `6.x`. If that's not possible then I'd propose adding this change to the docs at https://github.com/rails/rails/blob/main/guides/source/autoloading_and_reloading_constants.md

**Comment by bradgessler** [comment]
> I should add that its entirely possible I'm not hooking into the right initializer callback at https://github.com/sitepress/sitepress/blob/rails-7/sitepress-rails/lib/sitepress/engine.rb#L21 in 6.x, but it just happened to work.

As I suspected, if I change my code from `before: :set_autoload_paths` to `after: :set_autoload_paths` it boots just fine in Rails 7.x and 6.x.

IMO this is the call of a Rails maintainer to make as to wether or not this is a regression or simply "undocumented behavior".

**Comment by fxn** [comment]
Fantastic @bradgessler! We have it narrowed down. I'll think about it and will write back.

**Comment by bradgessler** [comment]
FWIW when I change  `before: :set_autoload_paths` to `after: :set_autoload_paths` it creates a bunch of other issues unrelated to the autoloader that I'd have to figure out. I'm going to hold off on this until I hear back on how ya'll are thinking about this issue.

**Comment by fxn** [comment]
The idea of that move was, "we should not need the autoload paths until we setup the `main` autoloader". But that move breaks initialization logic related to `paths`, and the fact that `set_autoload_paths` runs before `:bootstrap_hook` is documented in the configuration guide.

I believe this has to reverted, could you please try [this branch](https://github.com/rails/rails/tree/issue-43205)?

**Comment by bradgessler** [comment]
https://github.com/rails/rails/tree/issue-43205 works! No modification needed in the Sitepress gem for the upgrade from Rails 6.x to 7.x with the updated branch.

**Comment by fxn** [comment]
Fantastic @bradgessler! It was great that you caught this one. Thanks for testing the alpha, the isolated reproduction scripts, and the bisect.

I'll polish that patch soon and merge.

**Comment by bradgessler** [comment]
Thanks for patching it and a huge thanks for maintaining Zeitwerk and all of your contributions to Rails.
