### ISSUE TITLE
Trailing slashes are not added when url has a dot

### ISSUE THREAD

**Issue by silva96** [rails/rails#43219]
### Steps to reproduce
create a route that allows dots like in the documentation.

> By default, dynamic segments don't accept dots - this is because the dot is used as a separator for formatted routes. If you need to use a dot within a dynamic segment, add a constraint that overrides this – for example, id: /[^\/]+/ allows anything except a slash.

```ruby
get 'users/:username', to: 'users#show', constraints: { id: /[^\/]+/ }, as: :user, trailing_slash: true
```

call the path with username with and without a dot.

```ruby
user_path('someone')
user_path('some.one')
```
### Expected behavior
both should return  the url with trailing slash
```ruby
user_path('someone')
=> "/users/someone/"
user_path('some.one')
=> "/users/some.one/"
```

### Actual behavior
both should return  the url with trailing slash
```ruby
user_path('someone')
=> "/users/someone/"
user_path('some.one')
=> "/users/some.one"
```

Checking the code, theres a condition that explicitly asks if it has a dot it:

```ruby
def add_trailing_slash(path)
  if path.include?("?")
    path.sub!(/\?/, '/\&')
  elsif !path.include?(".") # here
    path.sub!(/[^\/]\z|\A\z/, '\&/')
  end
end
```

if this is not possible using trailing_slash , how can I achieve it? the problem is that Turbo is not being used if the url has a dot and it does not end in slash (see https://github.com/hotwired/turbo/issues/385)
### System configuration
**Rails version**: 6.1.4

**Ruby version**: 2.7.2-p137

**Comment by byroot** [comment]
This behaviour was implemented in https://github.com/rails/rails/pull/14986

In short it's because it assume a `.` is for something like `foo.json`, so it doesn't make sense to append a slash. I can't think of anyway to fix your use case without breaking a larger one.

**Comment by ghiculescu** [comment]
The “.” check feels naive. Could it not instead check if a format argument is being explicitly passed?

**Comment by byroot** [comment]
Indeed, it would make much more sense. The problem is there's this other test https://github.com/rails/rails/blob/c839fdb4d715e0866bb4e483283e7e3e60e5bfe1/actionpack/test/dispatch/request_test.rb#L45-L46 which more or less implies that you can pass `url_for(path: "/foo.json?bar=42", trailing_slash: true)`, which is kind of a shitty API if you ask me.

I wouldn't mind getting rid of that, but who knows the kind of code that might depend on this. :/

**Comment by byroot** [comment]
The PR that introduced this: https://github.com/rails/rails/pull/8704

**Comment by ghiculescu** [comment]
It sounds like there's a few different scenarios.

If you ask for a URL that contains:

- a "."
- a "?"
- `trailing_slash: true`

Then you should *not* get a trailing slash, because of the querystring. (This is currently supported.)

------------

If you ask for a URL that contains

- a "."
- `trailing_slash: true`
- no "?"
- no specific format

Then you *should* get a trailing slash. (This is the requested change.)

------------

If you ask for a URL that contains

- a "."
- `trailing_slash: true`
- no "?"
- a specific format

Then you should *not* get a trailing slash, because of the format requested. (This is currently supported.)

**Comment by ghiculescu** [comment]
Since we're discussing shitty APIs, the other I idea I had was a new option

```ruby
get 'users/:username', to: 'users#show', constraints: { id: /[^\/]+/ },
  as: :user,
  trailing_slash: true,
  dots_allowed_in_path: true # lol
```

**Comment by silva96** [comment]
> Since we're discussing shitty APIs, the other I idea I had was a new option
> 
> ```ruby
> get 'users/:username', to: 'users#show', constraints: { id: /[^\/]+/ },
>   as: :user,
>   trailing_slash: true,
>   dots_allowed_in_path: true # lol
> ```

That's what the constraints are for... the path has the dot, is allowed. 

> It sounds like there's a few different scenarios.
> 
> If you ask for a URL that contains:
> 
> * a "."
> * a "?"
> * `trailing_slash: true`
> 
> Then you should _not_ get a trailing slash, because of the querystring. (This is currently supported.)
> 
> If you ask for a URL that contains
> 
> * a "."
> * `trailing_slash: true`
> * no "?"
> * no specific format
> 
> Then you _should_ get a trailing slash. (This is the requested change.)
> 
> If you ask for a URL that contains
> 
> * a "."
> * `trailing_slash: true`
> * no "?"
> * a specific format
> 
> Then you should _not_ get a trailing slash, because of the format requested. (This is currently supported.)

There should be an option to disallow extensions in the path in the route.rb

ie. I would like mister john json to join my platform (he's already at instagram https://www.instagram.com/john.json/)

**Comment by intrip** [comment]
Dumb question: I didn't investigate, I just wonder if as a workaround replacing "." with the related htmlenties "&#46;" works.

**Comment by intrip** [comment]
Related to https://github.com/rails/rails/issues/43219#issuecomment-922480915 it doesn't look great but adding another parameter will certainly work out.

**Comment by byroot** [comment]
I need to dig more into this, but it seems that `url_for(path: "...")` isn't documented and is for internal use only. If I'm right then we can properly fix this.

If we no longer have to parse the `:path` argument, then we can know wether the `"."` is a format separator or part of one of the params.

**Comment by silva96** [comment]
> I need to dig more into this, but it seems that `url_for(path: "...")` isn't documented and is for internal use only. If I'm right then we can properly fix this.
> 
> If we no longer have to parse the `:path` argument, then we can know wether the `"."` is a format separator or part of one of the params.

Can you submit a PR then? I didn't quite understand what you are up to but it seems that you have a good solution.

**Comment by byroot** [comment]
> Can you submit a PR then?

As I said I need to dig more into this, implying I dont have the time to deal with it just now. Anyone is free to look into it.

**Comment by byroot** [comment]
https://github.com/rails/rails/pull/43287. 

It seems `url_for(path: ...)` isn't public API, so it should be good.

Also note that I have no idea wether the router would be confused or not by `https://example.com/john.json/`.
