### ISSUE TITLE
after recreating app in WSL, `rails g` freezes

### ISSUE THREAD

**Issue by Naokimi** [rails/rails#43217]
**Environment:**
- Windows WSL2 dev environment (setup based on https://github.com/lewagon/setup/blob/master/windows.md)
- ruby 2.7.2
- rails 6.1.4.1

**Reproduction steps:**
1. create new app (e.g. `rails new app_name`)
2. run any generator (e.g. `rails g model Author`)
2. remove folder and all contents (either delete in explorer or `-rm -rf`)
3. recreate app with same name (e.g. `rails new app_name`)
4. run any generator (e.g. `rails g model Author`)

**Result:**
Command freezes and won't finish generation
![image](https://user-images.githubusercontent.com/49295880/133172521-6ee17278-6a16-49f2-8111-92d87af2109d.png)

**Expected**
Commands should work

**Comment by intrip** [comment]
Have you tried to disable spring?
```
$ export DISABLE_SPRING=true
```
And then re-run the failing command

**Comment by Naokimi** [comment]
That worked. Thank you
