### ISSUE TITLE
Add configuration to disable schema validation model of ActiverRecord

### ISSUE THREAD

**Issue by KSH-code** [rails/rails#43214]
This is a suggestion.
- configuration bool value `app.config.active_record.health_check`

Since we separate database connections for switching connections by model and user in real-time, we cannot validate schema when initializing (i.e. `active_record.define_attribute_methods`)

by the way, we are handling database connections using customization code not only pure rails code.
so when boot, always warning message is visible if `eager_load = true` for prod, staging.
> Failed to define attribute methods because of ActiveRecord::ConnectionNotEstablished: No connection pool for '' found.

If our any database connection is set-ups, it should be. but our situation is that database connections are handling in real-time via http request or something. so it cannot be.

```
initializer "active_record.define_attribute_methods" do |app|
  config.after_initialize do
    ActiveSupport.on_load(:active_record) do
      if app.config.eager_load
        begin
		  ...
        rescue ActiveRecordError => error
        end
      end
    end
  end
end
```

after
```
initializer "active_record.define_attribute_methods" do |app|
  config.after_initialize do
    ActiveSupport.on_load(:active_record) do
      if app.config.eager_load && app.config.active_record.health_check
        begin
		  ...
        rescue ActiveRecordError => error
        end
      end
    end
  end
end
```
### System configuration
**Rails version**:
6.1.4
**Ruby version**:
2.7.1

**Comment by rafaelfranca** [comment]
Do we need the option if we already do nothing in case the connection fail? In other words, why isn't the `rescue ActiveRecordError` sufficient?

**Comment by KSH-code** [comment]
The reason why option needs is because warning message is unnecessary to us.

**Comment by rafaelfranca** [comment]
I don't think it is worth the complexity to remove a warning. Thank you for the suggestion.
