### ISSUE TITLE
Rails 6.1 double assignment leads to duplicate in-memory associations

### ISSUE THREAD

**Issue by voraciousdev** [rails/rails#43222]
### Steps to reproduce

```bash
rails new --api demo
```

Create the following task at `lib/tasks/ar_dup.rake`.

```ruby
# frozen_string_literal: true

desc "test duplication issue"
task ar_dup: :environment do
  require "minitest/autorun"

  ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
  ActiveRecord::Base.logger = Logger.new(STDOUT)

  ActiveRecord::Schema.define do
    create_table :people do |t|
      t.string :name
    end

    create_table :things do |t|
      t.references :person
      t.string :name
    end
  end

  class Person < ActiveRecord::Base
    has_many :things, inverse_of: :person
  end

  class Thing < ActiveRecord::Base
    belongs_to :person, inverse_of: :things
  end

  class BugTest < Minitest::Test
    def test_happy_path
      person = Person.new(name: 'Tiff')
      person.things << Thing.new(person: person)

      assert_equal 1, person.things.length
    end
  end
end
```

Run the rake task.

```bash
bin/rails ar_dup
```

The test fails, because `person.things.length` is 2. Oddly enough, I could not reproduce this in a standalone ActiveRecord script. It _had_ to be in a Rails app.

### Expected behavior

Only 1 association should be added to `person.things`.

### Actual behavior

The new association is duplicated (same `object_id`s).

### System configuration

**Rails version**: Rails 6.1.4.1

**Ruby version**: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin20]

**Comment by voraciousdev** [comment]
As I mentioned above, this does not happen in a standalone ActiveRecord test. This is the test I wrote to reproduce the bug, but it actually passes (as I would expect the full Rails app to do).

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.4.1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :people do |t|
    t.string :name
  end

  create_table :things do |t|
    t.references :person
    t.string :name
  end
end

class Person < ActiveRecord::Base
  has_many :things, inverse_of: :person
end

class Thing < ActiveRecord::Base
  belongs_to :person, inverse_of: :things
end

class BugTest < Minitest::Test
  def test_happy_path
    person = Person.new(name: 'Tiff')
    person.things << Thing.new(person: person)

    assert_equal 1, person.things.length
  end
end
```

**Comment by voraciousdev** [comment]
It turns out this actually only happens when using `inverse_of` on the `belongs_to` association.

**Comment by ghiculescu** [comment]
Rails 7 alpha just launched, could you please check if it is fixed in there?

There were a fair few changes around `has_many_inversing` in 6.1 and there's probably some bug fixes in 7.

**Comment by jstncarvalho** [comment]
Hey @voraciousdev,

https://github.com/rails/rails/pull/43445 fixed this. 

The test was passing with ActiveRecord, because the has_many_inversing config option was not set (in Rails it is). You can get the same behavior by adding `ActiveRecord::Base.has_many_inversing = true` to the AR test.
