### ISSUE TITLE
ActiveRecord validations using Proc and I18n.cache_store does not work together

### ISSUE THREAD

**Issue by sundling** [rails/rails#43235]
This problem happen when ActiveRecord validations uses [procs for :if/:unless](https://edgeguides.rubyonrails.org/active_record_validations.html#using-a-proc-with-if-and-unless) and caching is enabled using `I18n.cache_store=`

I get the exception when trying to display the error messages of an invalid ActiveRecord instance.
It is reproducible when displaying the error messages using my own code but it also happens when building forms using SimpleForm.

It seems that it is an `I18n::MissingTranslation` object that is causing this. A MissingTranslation object is created using the options passed to `I18n.translate`, which includes the ActiveRecord object being validated. (see [here](https://github.com/rails/rails/blob/167f5c80658a15b5aa2524433affe52553e2c8d9/activemodel/lib/active_model/error.rb#L55), [here](https://github.com/rails/rails/blob/167f5c80658a15b5aa2524433affe52553e2c8d9/activemodel/lib/active_model/error.rb#L70) & [here](https://github.com/rails/rails/blob/167f5c80658a15b5aa2524433affe52553e2c8d9/activemodel/lib/active_model/error.rb#L72))
An attempt to serialize that instance is made by the ActiveSupport::Cache::MemoryStore when writing to the cache.
The MemoryStore does not have its own handling for serializing so it delegates that responsibility to ActiveSupport::Cache.
The cache is using MemoryStore::DupCoder for serializing data and that ultimately uses Marshal.dump.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "6.1.4.1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

I18n::Backend::Simple.send(:include, I18n::Backend::Cache)
I18n.cache_store = ActiveSupport::Cache.lookup_store(:memory_store)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
  validates :title, length: { minimum: 10 }, if: -> { true }
end

class BugTest < Minitest::Test
  def test_run
    post = Post.new(title: "My post")

    assert post.invalid?
    assert_equal "Title is too short (minimum is 10 characters)", post.errors.first.full_message
  end
end
```

### Expected behavior
I expect it to be possible to call the `full_message`/`message` methods of an error even when using `I18n.cache_store`

### Actual behavior
I get the exception
```
TypeError: no _dump_data is defined for class Proc
```

### System configuration
**Rails version**: 6.1.4.1 & Rails main branch

**Ruby version**: 2.7.4

**Comment by ghiculescu** [comment]
Here's a simpler test case that also crashes

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "6.1.4.1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

I18n::Backend::Simple.send(:include, I18n::Backend::Cache)
I18n.cache_store = ActiveSupport::Cache.lookup_store(:memory_store)

class BugTest < Minitest::Test
  def test_run
    I18n.t(".")
  end
end
```

I suspect it's crashing because of this proc https://github.com/rails/rails/blob/e21c38ed7f9161e07e73afe2899f26ab7a260231/activesupport/lib/active_support/locale/en.rb#L7

**Comment by ghiculescu** [comment]
I can't think of a good reason why a `MissingTranslation` should be written to the cache here: https://github.com/ruby-i18n/i18n/blob/3d0f144038eebe3ff6bc7699de00736abd5ef634/lib/i18n/backend/cache.rb#L97

**Comment by intrip** [comment]
As @ghiculescu correctly pointed out:

- `memory_store` doesn't support dumping AR models
- We need to dump AR models

I couldn't find a good patch for Rails to handle this scenario.

What I think you can do as workaround is to introduce a store which silently fails on write, using it should workaround the issue:

```ruby

class SilentStore < DelegateClass(ActiveSupport::Cache::MemoryStore)
  def initialize
    super(ActiveSupport::Cache.lookup_store(:memory_store))
  end

  def write(...)
    super
  rescue TypeError
    false
  end
end

I18n::Backend::Simple.send(:include, I18n::Backend::Cache)
I18n.cache_store = SilentStore.new
```

The above code makes the test green. Could you please check?

**Comment by ghiculescu** [comment]
To be clear I think there’s at least a bug in i18n here (missing translation objects shouldn’t be cached IMO).

**Comment by intrip** [comment]
> To be clear I think there’s at least a bug in i18n here (missing translation objects shouldn’t be cached IMO).

I'm not 100% sure, shouldn't that speedup the lookup in any case?

In any case might be worth opening an issue in I18n gem at least to see their take on this.

**Comment by sundling** [comment]
This is still an issue on the `7-0-stable` & `main` branch
