### ISSUE TITLE
Using a layout seems to break turbo

### ISSUE THREAD

**Issue by drzel** [rails/rails#43249]
### Steps to reproduce
- Create a Foo controller
- Create a layout identical to application.html.erb
- Create a Foo#index route / action / view.
- Add enough content to the view that you need to scroll down.
- Add a link to another url on same domain
- In browser, scroll down and click link
- Page will scroll to the top and flicker before following link
- Back button returns user to top of previous page
- Delete foo.html.erb
- Works fine

### System configuration
**Rails version**: 7.0.0.alpha2

**Ruby version**: 3.0.1

**Comment by ghiculescu** [comment]
Could you share a test app / Heroku link that replicates the issue?

**Comment by drzel** [comment]
Okay, so after some more testing, not any layout will break turbo but there are two examples:
- Add a `<p>` tag in the `<head>`
- Include some external css.
Some things do work:
- Changing the title in `<head>` was fine.

Repo: https://github.com/drzel/turbo-layout-issue
Heroku: https://thawing-earth-06749.herokuapp.com/bar/index

To replicate:
- Navigate to https://thawing-earth-06749.herokuapp.com/bar/index
- Scroll to bottom
- Click 'Foo'
- Observe page flicker / scroll to top before redirecting
- Click back
- You will be at the top of the bar index.

So, the issue might not be the layout itself, but turbo failing when one page includes external css (or some other markup?), and another doesn't?

**Comment by ghiculescu** [comment]
Yeah, I think having a CSS link in one `<head>` but not the other might be confusing Turbo. I noticed that the same request gets made twice:

![image](https://user-images.githubusercontent.com/509837/133931166-f0c3b8b2-43cf-43a1-a681-a3b428c8e168.png)


(`index` is `/foo/index`)

So I suspect what's happening is:

- Turbo makes initial request ("fetch" request), renders page with old CSS file.
- Turbo notices head has changed.
- Turbo forces browser to reload page ("document" request), this explains why all the assets are reloading

Having different CSS links in the head of different pages feels like an odd practice. Is that something you can avoid?

**Comment by drzel** [comment]
Yeah, I've just moved everything to one css bundle. Have different CSS links in different layouts since I brought a static site into a rails app and it had its own CSS that conflicted. Seemed to work okay with Turbolinks on Rails 6.1.

**Comment by ghiculescu** [comment]
Could you please report that to https://github.com/hotwired/turbo ? Particularly if it works with Turbolinks.

Based on this code:

- https://github.com/hotwired/turbo/blob/e3f6f24aa36533351f97b3a6ea64b108f7b62f3f/src/core/native/browser_adapter.ts#L64
- https://github.com/hotwired/turbo/blob/e3f6f24aa36533351f97b3a6ea64b108f7b62f3f/src/core/view.ts#L93
- https://github.com/hotwired/turbo/blob/e3f6f24aa36533351f97b3a6ea64b108f7b62f3f/src/core/drive/page_renderer.ts#L50
- https://github.com/hotwired/turbo/blob/e3f6f24aa36533351f97b3a6ea64b108f7b62f3f/src/core/drive/head_snapshot.ts#L31

It looks like what you're seeing is probably expected, but I haven't dug into how Turbolinks differed or how it was smart enough to not have this issue.

I'm going to close here as it seems fine on the Rails side.
