### ISSUE TITLE
Foreign key change doesn't reset the association

### ISSUE THREAD

**Issue by heaven** [rails/rails#43245]
When changing the foreign key, the association is being reloaded as expected
```
2.6.6 :099 > admin = Admin.first
  Admin Load (0.5ms)  SELECT ...
 => #<Admin id: 1>
2.6.6 :100 > admin.saas_company
  SaasCompany Load (0.5ms)  SELECT ...
 => #<SaasCompany id: 2, name: "Company #2">
2.6.6 :101 > admin.saas_company_id = 3
 => 3
2.6.6 :102 > admin.saas_company
  SaasCompany Load (0.6ms)  SELECT ...
 => #<SaasCompany id: 3, name: "Company #3">
```

But this doesn't happen when running validations while updating a record. Here's the validation in the `Admin` model
```ruby
validates :saas_company, inclusion: { in: proc { |admin|
  debugger
  admin.saas_companies
} }, allow_nil: true
```

And here's what I see in the debugger
```
(byebug) admin.saas_company
 => #<SaasCompany id: 1>
(byebug) admin.saas_company_id
 => 3
(byebug) admin.changes
 => {"saas_company_id"=>[1, 3]}
```

Changing the `saas_company` to `saas_company_id` in the validation works but causes other problems.

Rails 6.1.3.2

**Comment by heaven** [comment]
Changing this
```ruby
belongs_to :saas_company, inverse_of: :current_admins
```
To this
```ruby
belongs_to :saas_company
```
Fixes the problem. So it seems something is wrong with the inverse option. I think this is not expected behavior.

**Comment by ghiculescu** [comment]
@heaven any chance you could try and replicate the issue against Rails 7 alpha? It sounds similar to https://github.com/rails/rails/issues/43222

**Comment by heaven** [comment]
@ghiculescu wasn't able to upgrade to 7 but can try setting up a test example similar to #43222
