### ISSUE TITLE
Sprockets::Rails::Helper::AssetNotPrecompiled for rails-ujs.js with importmap

### ISSUE THREAD

**Issue by ianterrell** [rails/rails#43242]
I would expect that adding the following would enable UJS, based on the `//= require rails-ujs` line in the asset pipeline [instructions for UJS](https://github.com/rails/rails/tree/main/actionview/app/assets/javascripts#usage).

`config/importmap.rb`:
```ruby
pin "@rails/ujs", to: "rails-ujs.js"
```

`app/javascript/application.js`:
```javascript
import "@rails/ujs"
```

### Expected behavior

UJS is enabled.

### Observed behavior

`Sprockets::Rails::Helper::AssetNotPrecompiled` for `rails-ujs.js` on rendering the importmap with `<%= javascript_importmap_tags %>`.

(This is different than if I pin the library to a nonexistent filename, like `asdfasdfasdf.js`, which seems to currently be ignored.)

### Workaround

I'm currently working around this by using UJS from a CDN:

```ruby
pin "@rails/ujs", to: "https://cdn.skypack.dev/rails-ujs"
```

**Comment by ghiculescu** [comment]
UJs is deprecated (https://github.com/rails/rails/pull/43112) which makes me think this is intended behavior. The workaround seems fine.

@dhh could you confirm?

**Comment by dhh** [comment]
Need to use link_file in the config manifest to ensure it’ll be compiled. But yes, UJS is deprecated. Wouldn’t start new apps on it. For existing apps it’s of course fine to keep using.

**Comment by ianterrell** [comment]
Thank you!
