### ISSUE TITLE
Error when persisting model with virtual column in PG

### ISSUE THREAD

**Issue by bnjamin** [rails/rails#43262]
I tried to use the new generated columns feature implemented in #41856, sadly i ran into a bug where AR tried to set values for the virtual columns when persisting.

### Steps to reproduce
Create a new rails app with postgresql as the db
`bundle exec rails new . --edge --force --database postgresql`

create a new model with a virtual column
`bundle exec rails g model virtual_column name`

```ruby
class CreateVirtualColumns < ActiveRecord::Migration[7.0]
  def change
    create_table :virtual_columns do |t|
      t.string :name
      t.virtual :upper_name,  type: :string,  as: "UPPER(name)", stored: true

      t.timestamps
    end
  end
end
```

Create a new record in the rails console
`VirtualColumn.create(name: "Hello")`

I've tried to see if i can reproduce the bug with an executable test script, but for some reason the bug doesn't appear. A gist is [here](https://gist.github.com/bnjamin/7853d7380b57a000d833e0803deefcd0) 

I've instead reproduced it in a rails app [here](https://github.com/bnjamin/rails_virtual_column_test)
run `bundle exec rails test test/models/virtual_column_test.rb` and the bug will appear.

The bug also doesn't appear in the tests for virtual columns in AR [here](https://github.com/rails/rails/blob/eda60f26b3f9d58cfc81f1b90bae5e299a1b3976/activerecord/test/cases/adapters/postgresql/virtual_column_test.rb#L23)

### Expected behavior
That it creates the record successfully

### Actual behavior
It gives an error because it tries to set the value in the generated column.

```SQL
TRANSACTION (0.1ms)  BEGIN
  VirtualColumn Create (5.2ms)  INSERT INTO "virtual_columns" ("name", "upper_name", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["name", "Hello"], ["upper_name", nil], ["created_at", "2021-09-19 15:48:25.779399"], ["updated_at", "2021-09-19 15:48:25.779399"]]
  TRANSACTION (0.1ms)  ROLLBACK
/Users/benjamin/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-50adba474699/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:730:in `exec_params': PG::SyntaxError: ERROR:  cannot insert into column "upper_name" (ActiveRecord::StatementInvalid)
DETAIL:  Column "upper_name" is a generated column.
/Users/benjamin/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/rails-50adba474699/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:730:in `exec_params': ERROR:  cannot insert into column "upper_name" (PG::SyntaxError)
DETAIL:  Column "upper_name" is a generated column.
```

### System configuration
**Rails version**: 7.0.0.alpha2

**Ruby version**: 3.0.2

**PG version**: 13.3

**Comment by bnjamin** [comment]
I would like to help fixing the bug, so if someone could give me some pointers so I can reproduce the bug in the tests for AR, I would be glad to help.

**Comment by bnjamin** [comment]
I did some digging and found that if I put `binding.break` before line 1024 and run the test for virtual columns `bin/test -a postgresql test/cases/adapters/postgresql/virtual_column_test.rb --name test_virtual_column`

https://github.com/rails/rails/blob/bac0038e20a7c7be434c3fa3983e536054dc6edc/activerecord/lib/active_record/persistence.rb#L1023-L1038

when in rdbg:
attribute_names => ["name"] 
self.attribute_names => ["id", "name", "upper_name", "name_length", "name_octet_length"]

it makes no sense because `_create_record` is called on line 998 with no arguments, so attribute_names should be the same as self.attribute_names

When i try the same from my sample rails app, attribute_names is the same as self.attribute_names.

**Comment by cristianbica** [comment]
The difference between the reproduction script and rails app is that rails app loads the 7.0 default. And the config that makes a difference is `ActiveRecord::Base.partial_inserts`.

**Comment by bnjamin** [comment]
Thanks! That makes sense. I found a way to fix the bug if i change the `attributes_for_create` method in `activerecord/lib/active_record/attribute_methods.rb` to filter out attributes that are virtual.
```ruby
def attributes_for_create(attribute_names)
  attribute_names &= self.class.column_names
  attribute_names.delete_if do |name|
    column_for_attribute(name).virtual? ||
      pk_attribute?(name) && id.nil?
  end
end
```

I'll make a PR

**Comment by cristianbica** [comment]
So when you call `save` it will actually have the following call stack:
- activerecord/lib/active_record/timestamp.rb:99
- activerecord/lib/active_record/callbacks.rb:460
- activerecord/lib/active_record/attribute_methods/dirty.rb:221

Now when the `_create_record` from `dirty.rb` is called:
- in the script (with `partial_inserts == true`) it will use `changed_attribute_names_to_save`
- in the rails app (with `partial_inserts == true`) it will use `attribute_names`

IMO a fix could be implemented in `attributes_for_create` / `attributes_for_update` which should filter out virtual attributes.

**Comment by bnjamin** [comment]
Thanks a lot! I'll make a PR

**Comment by cristianbica** [comment]
> Thanks a lot! I'll make a PR

To be discussed (maybe in the PR) is if `VirtualColumn.create(name: "Hello", upper_name: "hello")` should raise or ignore the `upper_name` value
