### ISSUE TITLE
String.in_time_zone(zone) returns wrong results for some Timezones

### ISSUE THREAD

**Issue by R-Inbarasu** [rails/rails#43274]
### Steps to reproduce
```
date = "21/09/2021 07:00"
date.in_time_zone("Etc/GMT-5")
=> Tue, 21 Sep 2021 07:00:00 +05 +05:00

date.in_time_zone("EST") # EST is of same offset as the above timezone
=> Tue, 21 Sep 2021 07:00:00 EST -05:00
```

### Expected behavior
Tue, 21 Sep 2021 07:00:00 -05 -05:00 is the expected answer

### Actual behavior
Tue, 21 Sep 2021 07:00:00  +05 +05:00 is what I'm getting instead

### System configuration
**Rails version**: 5.0.0

**Ruby version**: 2.4.1

**Comment by ceritium** [comment]
Hi @R-Inbarasu, please, take a look at this comment: https://github.com/rails/rails/issues/37989#issuecomment-566273713

Link TZ source: https://github.com/eggert/tz/blob/765984a9356b01bf1c629fb474c5cee8b6ba2c70/etcetera#L37-L43

Would you consider close this issue?

**Comment by khall** [comment]
I agree, this is a bug in TZInfo

**Comment by R-Inbarasu** [comment]
Thank you for the comments. We can close this now.
