### ISSUE TITLE
Missing functionality to create references without indexes from the CLI (index:false)

### ISSUE THREAD

**Issue by geekodour** [rails/rails#43281]
I had a usecase where i wanted to create references but did not want the index created, but rails by default creates the index when using `add_reference`. Which can be modified in the migration file itself, but cannot be provided via the command line.

The only other options i have are:
- manually edit the file and add `index: false`
- creating these foreign key as bigints and using `add_foreign_key` (which again requires me to modify the file)
- remove the index once it's created.

So do we by any chance plan to add support for this? if yes, can help with adding this functionality if the community finds it helpful :)

### Steps to reproduce

```ruby
# generates migration with correct reference
rails generate migration AddDetailsToProducts 'price:decimal{5,2}' 'supplier:references{index}'
# behaves same as the above, as references by default have index:true
rails generate migration AddDetailsToProducts 'price:decimal{5,2}' 'supplier:references'
# generates something that's not even correct ruby code, basically broken here.
rails generate migration AddDetailsToProducts 'price:decimal{5,2}' 'supplier:references{index:false}'
```

Links:
- [references default to `index:true`](https://edgeapi.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_reference)

### System configuration
**Rails version**: Rails 6.0.3.2

**Ruby version**: ruby 2.6.5p114

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.

In this case, I'd say just open a PR and make it so, please.
