### ISSUE TITLE
Postgresql default type for datetime does not include timezone

### ISSUE THREAD

**Issue by key88sf** [rails/rails#43307]
Rails does not store timezone by default in Postgres datetime/timestamp columns. The native data type used, which is stored in `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter::NATIVE_DATABASE_TYPES[:datetime][:name]` is `timestamp` (which does not include the time zone in Postgres).

Rails always assumes timestamps are in UTC, but the problem is that when other applications use the data stored in Postgres by Rails, they often expect the timezone to be set in order to convert to another timezone for reporting, etc.

Suggested Fix:

Change the native database type used here to be `timestamptz`, which includes the timezone.

**Comment by ghiculescu** [comment]
Since https://github.com/rails/rails/pull/41084, you can set the preferred format for datetime types.

Do this in an initializer:

```ruby
ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.datetime_type = :timestamptz
```

Note that this won't change existing columns, but it works well for new apps.

**Comment by key88sf** [comment]
Oh that's nice, thanks!
