### ISSUE TITLE
Possible doc error for NestedAttributes

### ISSUE THREAD

**Issue by machinehum** [rails/rails#43316]
See: https://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html

Unless I'm missing something, the section 'Validating the presence of a parent model' is outdated since belongs_to associations started being required by default in Rails 5. Following the given example will result in a "parent_foo can't be blank" error.

**Comment by p8** [comment]
Yes, that section seems a bit outdated. The validation gets added by default now:
https://github.com/rails/rails/blob/061bf3156fb90ac6b8ec255dfa39492cf22d7b13/activerecord/lib/active_record/associations/builder/belongs_to.rb#L126
I think we could delete that section until the "For one-to-one nested associations..." part and change the heading to match the last part.
Do you want to create a pull request? 🙂

**Comment by machinehum** [comment]
Will do.
