### ISSUE TITLE
`thread_mattr_accessor` default value does not apply to threads

### ISSUE THREAD

**Issue by tdeo** [rails/rails#43312]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support/core_ext/module/attribute_accessors_per_thread"
require "minitest/autorun"

class BugTest < Minitest::Test
  class ThreadAccessors
    thread_mattr_accessor :variable, default: 42
  end

  def test_stuff
    assert(ThreadAccessors.variable == 42)
    Thread.new do
      assert(ThreadAccessors.variable == 42)
    end.join
  end
end
```

### Expected behavior

I'd expect the default value for the thread variable to be present in all threads

### Actual behavior

The variable is initialized only in the main thread at load time and `nil` in other threads

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

**Comment by intrip** [comment]
I think this is the expected behaviour: main thread != a new thread.
Under the hood [`thread_mattr_accessor`](https://github.com/rails/rails/blob/45c2cc546beddd3b7f359ed954231ef10d7ccb42/activesupport/lib/active_support/core_ext/module/attribute_accessors_per_thread.rb#L44) relies on [`Thread.current[:name]`](https://ruby-doc.org/core-3.0.2/Thread.html#method-i-5B-5D) please check the related docs to find more info.

**Comment by tdeo** [comment]
What I mean is that I find misleading that `thread_mattr_accessor` supports a `default` option which is not always applied. When I define a class having a `thread_mattr_accessor :variable, default: 0`, I would expect calling `Class.variable` to never be `nil` (unless I set it manually myself), but always have its default value of `0` before an explicit assignment.

My example makes very explicit what's happening with `Thread.new`, however, in real life, you could end up in that situation because your code is being called from a threaded production environment (be it a job framework or a web server), and it's quite opaque to the end-user.

**Comment by intrip** [comment]
@tdeo Ah I see your point now!

I agree that this behaviour is counter intuitive, on the other hand changing it introduces a backward incompatibility If we add such change to the 7 upgrade and document it I suppose that's ok.

@ghiculescu what's your take on this?

**Comment by ghiculescu** [comment]
There was a recent issue similar to this: https://github.com/rails/rails/issues/43228

It's expected + documented, but I can accept it's also confusing. I think https://discuss.rubyonrails.org/c/rubyonrails-core/5 is the right venue to discuss it, since it is behaving as documented. @tdeo would you like to start a thread there? (it doesn't look like anyone did since the last issue)

**Comment by tdeo** [comment]
I'm not talking about the same issue (that previous one deals with default value in subclasses, and subclasses behavior is somewhat documented).

However, I can't find any explanation for the expected `default` option behavior in the doc for `thread_mattr_accessor`, is it somewhere else?

**Comment by ghiculescu** [comment]
Chatted to @matthewd and he agreed this is probably a bug. A PR would be welcome, with the caveat that it not kill performance in the reader (but that could be a nontrivial caveat).

**Comment by tdeo** [comment]
Hello @ghiculescu,

From the top of my mind, here is the patched version I would come up with:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "benchmark-ips"
end

require "active_support"
require "active_support/core_ext/module/attribute_accessors_per_thread"
require "minitest/autorun"

# Your patch goes here.
class Module
  def thread_mattr_reader_default(*syms, instance_reader: true, instance_accessor: true, default: nil)
    syms.each do |sym|
      raise NameError.new("invalid attribute name: #{sym}") unless /^[_A-Za-z]\w*$/.match?(sym)
      class_eval(<<-EOS, __FILE__, __LINE__ + 1)
        def self.#{sym}
          if Thread.current["attr_defined_" + name + "_#{sym}"].nil?
            Thread.current["attr_defined_" + name + "_#{sym}"] = true
            Thread.current["attr_" + name + "_#{sym}"] = #{default.inspect}
          end
          Thread.current["attr_" + name + "_#{sym}"]
        end
      EOS

      if instance_reader && instance_accessor
        class_eval(<<-EOS, __FILE__, __LINE__ + 1)
          def #{sym}
            self.class.#{sym}
          end
        EOS
      end
    end
  end

  def thread_mattr_writer_default(*syms, instance_writer: true, instance_accessor: true, default: nil) # :nodoc:
    syms.each do |sym|
      raise NameError.new("invalid attribute name: #{sym}") unless /^[_A-Za-z]\w*$/.match?(sym)

      # The following generated method concatenates `name` because we want it
      # to work with inheritance via polymorphism.
      class_eval(<<-EOS, __FILE__, __LINE__ + 1)
        def self.#{sym}=(obj)
          if Thread.current["attr_defined_" + name + "_#{sym}"].nil?
            Thread.current["attr_defined_" + name + "_#{sym}"] = true
          end
          Thread.current["attr_" + name + "_#{sym}"] = obj
        end
      EOS

      if instance_writer && instance_accessor
        class_eval(<<-EOS, __FILE__, __LINE__ + 1)
          def #{sym}=(obj)
            self.class.#{sym} = obj
          end
        EOS
      end

      public_send("#{sym}=", default) unless default.nil?
    end
  end

  def thread_mattr_accessor_default(*syms, instance_reader: true, instance_writer: true, instance_accessor: true, default: nil)
    thread_mattr_reader_default(*syms, instance_reader: instance_reader, instance_accessor: instance_accessor, default: default)
    thread_mattr_writer_default(*syms, instance_writer: instance_writer, instance_accessor: instance_accessor)
  end
end

module A
  thread_mattr_accessor_default :attribute_with_default, default: 42
  thread_mattr_accessor :attribute, default: 42
end

Benchmark.ips do |x|
  x.report("original")      { A.attribute }
  x.report("patched_default") { A.attribute_with_default }
  x.compare!
end

class BugTest < Minitest::Test
  def test_stuff
    assert(A.attribute_with_default == 42)
    Thread.new do
      assert(A.attribute_with_default == 42)
    end.join
    A.attribute_with_default = nil
    assert(A.attribute_with_default.nil?)
  end
end
```

Output of this script:
```
Warming up --------------------------------------
            original   170.500k i/100ms
     patched_default    66.095k i/100ms
Calculating -------------------------------------
            original      2.105M (± 5.4%) i/s -     10.571M in   5.036874s
     patched_default    914.367k (± 7.5%) i/s -      4.561M in   5.018758s

Comparison:
            original:  2104980.9 i/s
     patched_default:   914367.3 i/s - 2.30x  (± 0.00) slower

Run options: --seed 65131

# Running:

.

Finished in 0.002085s, 479.6453 runs/s, 1438.9359 assertions/s.
1 runs, 3 assertions, 0 failures, 0 errors, 0 skips
```

The performance hit is indeed pretty nasty (x2.3), however, that's still ~1M ips, which I'm not sure if that would be acceptable for such a feature, let me know what you think.


Unfortunately, I can't think of a way to do it without a second thread variable as the following occurs when explicitly setting it to `nil`:
```ruby
Thread.current[:var] = 1
Thread.current.key?(:var) # => true 
Thread.current[:var] = nil
Thread.current.key?(:var) # => false 
```

**Comment by jonathanhefner** [comment]
@tdeo

> the following occurs when explicitly setting it to `nil`:
>
> ```ruby
> Thread.current[:var] = 1
> Thread.current.key?(:var) # => true
> Thread.current[:var] = nil
> Thread.current.key?(:var) # => false
> ```

That's unfortunate. :thinking:  What about using a placeholder object for `nil`?  Something like:

```ruby
    NIL_OBJECT = Object.new

    # ...

      class_eval(<<-EOS, __FILE__, __LINE__ + 1)
        def self.#{sym}
          key = "attr_" + name + "_#{sym}"
          obj = Thread.current[key]
          
          if obj.nil?
            obj = #{default.inspect}
            Thread.current[key] = obj.nil? ? NIL_OBJECT : obj
          end

          obj
        end
      EOS

    # ...

      class_eval(<<-EOS, __FILE__, __LINE__ + 1)
        def self.#{sym}=(obj)
          Thread.current["attr_" + name + "_#{sym}"] = obj.nil? ? NIL_OBJECT : obj
        end
      EOS

    # ...
```

That does keep a thread variable allocated, even when the value (or `default`) is `nil`, but perhaps that's not so bad.  (Related to performance: it might save a few string allocations to change `"attr_" + name + "_#{sym}"` to `"attr_\#{name}_#{sym}"`.)
