### ISSUE TITLE
i get unexpected @path error.

### ISSUE THREAD

**Issue by francelwebdev** [rails/rails#43319]
Hello, i get this error when i run rails s . I use ruby 3.0.2 and rails 7.0.0.alpha2.

francel@francel-Inspiron-N5010:~/Documents/rails_api$ rails s
/home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/path.rb:103:in `to_s': unexpected @path (TypeError)
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/path.rb:103:in `stability'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/path.rb:11:in `stable?'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/path.rb:41:in `entries_and_dirs'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:159:in `block (2 levels) in unshift_paths_locked'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:155:in `reverse_each'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:155:in `block in unshift_paths_locked'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/store.rb:47:in `block in transaction'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/store.rb:45:in `synchronize'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/store.rb:45:in `transaction'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:154:in `unshift_paths_locked'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:107:in `block in unshift_paths'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:107:in `synchronize'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/cache.rb:107:in `unshift_paths'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/change_observer.rb:21:in `unshift'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/application.rb:339:in `add_lib_to_load_path!'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/application.rb:72:in `inherited'
	from /home/francel/Documents/rails_api/config/application.rb:24:in `<module:RailsApi>'
	from /home/francel/Documents/rails_api/config/application.rb:22:in `<main>'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.0.beta3/lib/zeitwerk/kernel.rb:35:in `require'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:137:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/command/base.rb:87:in `perform'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/command.rb:48:in `invoke'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/railties-7.0.0.alpha2/lib/rails/commands.rb:18:in `<main>'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/francel/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from bin/rails:4:in `<main>'

**Comment by p8** [comment]
Hi @francelwebdev ,
Do you get the same error when you prepend the command with `bin`?
```
bin/rails s
```

**Comment by francelwebdev** [comment]
i get the same error.

**Comment by p8** [comment]
Which version of Bundler are you using?

**Comment by p8** [comment]
This seems like a bootsnap issue.
You could report an issue there: https://github.com/Shopify/bootsnap/issues
As a temporary solution you could remove `bootsnap` from you Gemfile.
