### ISSUE TITLE
rails alpha2 returning js error on new application

### ISSUE THREAD

**Issue by salex** [rails/rails#43325]
### Steps to reproduce

Decided to take a look at alpha2 and create a new app.

I tried the different approaches but decided that the default import maps would be best since all the JS I have was converted to stimulus over a year ago, But I have played with tailwind and have a mixed tailwind and w3css on one app

This is all I did (compact commands)
```
mkdir rails7
cd rails7
rbenv install 3.0.1 # then set .ruby-version
gem install rails --prerelease
rails new demo --css tailwind
cd demo
bin/rails g controller home show
bin/rails s
```
going to `localhost:3000` brings up Hello Your on Rails page
going to `localhost:3000/home/show` brings up the scaffold page

When tried to bring up the stimulus hello_controller, it didn't work and I had an error on JS console

```
[Error] TypeError: Module specifier, 'application' does not start with "/", "./", or "../". Referenced from http://localhost:3000/home/show
/   promiseReactionJob
```

tailwind works but where do you put/create a tailwind_config.js file to add new color and stuff?

I also tried to add stimulus-flatpickr and stimulus-autocomplete with bin/importmap and it timed out. Did get it to load by adding to importmap.rb, but nothing worked, probably because of the JS error.

**Comment by ghiculescu** [comment]
could you possibly share a repo to replicate the issue in?

**Comment by mrhead** [comment]
This error can be ignored. See: https://github.com/rails/importmap-rails#expected-errors-from-using-the-es-module-shim

**Comment by salex** [comment]
ok
