### ISSUE TITLE
ActionCable disconnected (Javascript) callback is not passing the reason for disconnection

### ISSUE THREAD

**Issue by vtt** [rails/rails#43336]
When a connection is rejected with `reject_unauthorized_connection`, the javascript callback only passes the `reconnect` parameter but omits the `reason` parameter.

It'd be nice to know the reason for rejection (eg. unauthorized) so the application can redirect to a login page.

**Comment by p8** [comment]
Hi @vtt, This appears to be a feature request. We generally do not take
    feature requests, and we reserve the issue tracker for issues only.
    We recommend you [try to implement the feature](
    https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-code),
    and send us a pull request instead. If you are unsure if the feature
    would be accepted, please ask on the [rubyonrails-core](
    https://discuss.rubyonrails.org/c/rubyonrails-core/5) forum.
