### ISSUE TITLE
NameError using 2.5.0beta5 with Rails 7

### ISSUE THREAD

**Issue by fxn** [rails/rails#43344]
_(Moved from https://github.com/fxn/zeitwerk/issues/185.)_

I'm testing a Rails engine for compatibility with Rails 7.0.0alpha2, and [I get a NameError](https://app.travis-ci.com/github/brian-kephart/camaleon-cms/jobs/540484105#L662) whenever I try to run the test suite.

This seems possibly related to [this section of the Rails upgrade guide](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#autoloading-during-initialization), except that the deprecation notice from the guide never appeared under Rails 6 with Zeitwerk 2.4, as can be seen in the [6.0/6.1 CI builds](https://app.travis-ci.com/github/brian-kephart/camaleon-cms/builds/238810649).

At this point I'm not sure if my issue is with Zeitwerk, Rails, or the engine, but I've been unable to resolve it by looking at the Rails upgrade guide or the Zeitwerk changelog, so I wanted to get maintainer eyes on it before the release in case it's a regression or a gap in the upgrade docs. Please let me know if there's anything I can clarify beyond the CI logs.

**Comment by fxn** [comment]
Yeah, it is indeed what the edge upgrade guide says, in Rails 7 you cannot autoload reloadable code in the initializers.

It is surprising that you didn't see the warning in previous versions, because [the logic is pretty straightforward](https://github.com/rails/rails/blob/3be6c2d67c0dcbefa1c252943b0188b384403ec1/railties/lib/rails/application/finisher.rb#L30). Please, note that the warning goes to `log/<environment>.log`.

To reduce the scope of the search for the fix, let me say that this is unrelated to Zeitwerk, it is a deliberate change in Rails 7.

Have you tried to wrap the access in a `Rails.application.config.to_prepare` block?

**Comment by fxn** [comment]
@brian-kephart Does the current edge guide help? Please check https://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-when-the-application-boots.

**Comment by brian-kephart** [comment]
Thanks for giving this your attention. The main thing that threw me off was that the deprecation notice went straight to the log file. I'm used to seeing other deprecations in the window that's running the server/tests, so when I didn't see the deprecation notice in the test output I wasn't sure if that section of the guide was relevant.

Just knowing that I'm dealing with the change described in the guide helps. By wrapping several initializers in `to_prepare` blocks, I've at least gotten the tests to run. There are still several failures, but I have yet to discover whether they're related to this change or not.

I don't see any obvious improvements to be made to the docs as of now. This issue can probably be closed.

**Comment by fxn** [comment]
Excellent Brian, let's close by now. However, anything that I can help with those initializers, please don't hesitate to followup.
