### ISSUE TITLE
Rails.application.config.action_mailer.smtp_settings not the same as ActionMailer::Base.smtp_settings on development

### ISSUE THREAD

**Issue by camilova** [rails/rails#43349]
### Steps to reproduce
On `development` env add an initializer file with some example configuration `config/initializers/smtp_settings_initializer.rb`:

```
Rails.application.config.action_mailer.smtp_settings = {
  address: 'mymailserver.com',
  authentication: :plain,
  enable_starttls_auto: true,
  password: 'mypassword',
  port: 25,
  user_name: 'myusername',
  tls: true,
  openssl_verify_mode: 'none',
  ssl: true
}
```
Then start a new rails console `rails c` and run:

`Rails.application.config.action_mailer.smtp_settings` -> outputs the same config previously setted
`ActionMailer::Base.smtp_settings` -> outputs defaults thinks pointing to `localhost` but not the same config that was setted previously

### Expected behavior
Both `Rails.application.config.action_mailer.smtp_settings` and `ActionMailer::Base.smtp_settings` should be the same

### Actual behavior
Mail delivering fails on development because settings are taken from `ActionMailer::Base.smtp_settings` and there are only default values for `localhost`

### System configuration
**Rails version**: 6.1.4.1

**Ruby version**: 2.7.4p191

### My Current Solution
To resolve this I setted both settings entry points on an initializer file as follow:

```
my_settings = { .... }
Rails.application.config.action_mailer.smtp_settings = my_settings
ActionMailer::Base.smtp_settings = my_settings
```

**Comment by gkampjes** [comment]
You need to set the action mailer config in a `Rails.application.configure` block, like so:

```ruby
# config/initializers/smtp_settings_initializer.rb

Rails.application.configure do
  config.action_mailer.smtp_settings = {
    address: 'mymailserver.com',
    authentication: :plain,
    enable_starttls_auto: true,
    password: 'mypassword',
    port: 25,
    user_name: 'myusername',
    tls: true,
    openssl_verify_mode: 'none',
    ssl: true
  }
end
```

Then it will correctly set the config on `ActionMailer::Base`:

```ruby
Loading development environment (Rails 6.1.4.1)
[1] pry(main)> Rails.application.config.action_mailer.smtp_settings
=> {:address=>"mymailserver.com", :authentication=>:plain, :enable_starttls_auto=>true, :password=>"mypassword", :port=>25, :user_name=>"myusername", :tls=>true, :openssl_verify_mode=>"none", :ssl=>true}
[2] pry(main)> ActionMailer::Base.smtp_settings
=> {:address=>"mymailserver.com", :authentication=>:plain, :enable_starttls_auto=>true, :password=>"mypassword", :port=>25, :user_name=>"myusername", :tls=>true, :openssl_verify_mode=>"none", :ssl=>true}
```

**Comment by camilova** [comment]
I see, thank you. I was upgrading my app from `5.2` to `6.1.4` thorugh all the patch intermediate version as rails guide sugest, but I did not see any warning about this on my test or while running, is this a new way available on version `6.1` or even I dont know that this was the way to get it work since always?

Thanks in advance

**Comment by camilova** [comment]
I tried what you suggested, but the problem is still there, `ActionMailer::Base.smtp_settings` is setted with default `localhost` anyway.

![example](https://user-images.githubusercontent.com/29240376/135672910-69417c40-4ade-4d2a-a4d9-2f911506ea6f.png)

**Comment by fatash89** [comment]
> ### Steps to reproduce
> On `development` env add an initializer file with some example configuration `config/initializers/smtp_settings_initializer.rb`:
> 
> ```
> Rails.application.config.action_mailer.smtp_settings = {
>   address: 'mymailserver.com',
>   authentication: :plain,
>   enable_starttls_auto: true,
>   password: 'mypassword',
>   port: 25,
>   user_name: 'myusername',
>   tls: true,
>   openssl_verify_mode: 'none',
>   ssl: true
> }
> ```
> 
> Then start a new rails console `rails c` and run:
> 
> `Rails.application.config.action_mailer.smtp_settings` -> outputs the same config previously setted `ActionMailer::Base.smtp_settings` -> outputs defaults thinks pointing to `localhost` but not the same config that was setted previously
> 
> ### Expected behavior
> Both `Rails.application.config.action_mailer.smtp_settings` and `ActionMailer::Base.smtp_settings` should be the same
> 
> ### Actual behavior
> Mail delivering fails on development because settings are taken from `ActionMailer::Base.smtp_settings` and there are only default values for `localhost`
> 
> ### System configuration
> **Rails version**: 6.1.4.1
> 
> **Ruby version**: 2.7.4p191
> 
> ### My Current Solution
> To resolve this I setted both settings entry points on an initializer file as follow:
> 
> ```
> my_settings = { .... }
> Rails.application.config.action_mailer.smtp_settings = my_settings
> ActionMailer::Base.smtp_settings = my_settings
> ```

**Comment by intrip** [comment]
Why aren't you setting the configuration via the related ENV files as [suggested by the guides](https://guides.rubyonrails.org/action_mailer_basics.html#example-action-mailer-configuration)?

**Comment by camilova** [comment]
Hi @intrip you are right, setting this config on the env file makes correct assignment, and I didn't see before the hint on the guide. It solved my problem.

But why must be setted there?, when in my opinion it should be the same when setting this on their own initializer file. It makes this setting depends on precedence and less flexible, but it was only my personal meaning.

Thanks!
