### ISSUE TITLE
[js] Subscriptions.notify "Cannot read received of undefined"

### ISSUE THREAD

**Issue by froziq** [rails/rails#43340]
### Steps to reproduce

In js application create consumer and then create subscription on channel. After receiving any message from server in browser console appear error `Uncaught TypeError: Cannot read properties of undefined (reading 'received')`

```js
const consumerInstance = actioncable.createConsumer();
consumerInstance.subscriptions.create(channel, {
        initialized,
        connected,
        received,
        disconnected,
        rejected,
      });
```

### Expected behavior
There is no any errors

### Actual behavior
The error appears when going through all subscriptions
```
Uncaught TypeError: Cannot read properties of undefined (reading 'received')
    at Subscriptions.ActionCable.Subscriptions.Subscriptions.notify (action_cable.js?f5ee:497)
    at Connection.message (action_cable.js?f5ee:347)
    at Connection.consumerInstance.connection.events.message (index.ts?4393:46)
```

### Steps to fix
`actioncable/app/javascript/action_cable/subscriptions.js [75]`  method `notify`. You need to add check for subscription existence
```    
if (typeof subscription === "string") {
      subscriptions = this.findAll(subscription)
} else if (subscription) {               // <-- this string
      subscriptions = [subscription]
}
```

**Comment by p8** [comment]
Hi @froziq,
What Rails version are you using?
Looking the the guides it seems you might need to do something like:
```javascript
const consumerInstance = actioncable.createConsumer();
consumerInstance.subscriptions.create({channel: channel });
```
https://guides.rubyonrails.org/action_cable_overview.html#subscriber.

**Comment by froziq** [comment]
be honest, does not matter. it's client side error. i showed the line to be corrected...
used latest rails version and latest actioncable version

**Comment by vijaypemmaraju** [comment]
For anyone who runs into this in the future, this is why we were seeing it:
1. Our backend was upgraded to rails 6, but our client js library was still on `actioncable@5.x`
2. Users not signed into our app were receiving a message to the client that looks like this `{"type":"disconnect","reason":"unauthorized","reconnect":false}`
3. This wasn't not being handled correctly by the 5.x version of the library and hence throwing this error.

We were able to resolve the issue by upgrading to `@rails/actioncable@6.x`
