### ISSUE TITLE
Opt rails into hacktoberfest

### ISSUE THREAD

**Issue by grepsedawk** [rails/rails#43360]
If rails wants to participate in hacktoberfest, this can be done by adding the "hacktoberfest" topic to the github repo:
![image](https://user-images.githubusercontent.com/6721355/135693160-68914e07-7cb5-44f7-b112-eb0e58563ce2.png)

**Comment by eileencodes** [comment]
Hi @grepsedawk thanks for the suggestion, but we don't want to opt-in to Hacktoberfest this year. Of course we welcome contributions from anyone this month and all future months 😄
