### ISSUE TITLE
rexml dependency is missing for ActiveSupport in Ruby 3+ applications

### ISSUE THREAD

**Issue by maxnovee** [rails/rails#43463]
### Steps to reproduce
Rails 6.1.3 app running Ruby 3.0.1

1. Start rails console in environment without gems from test & development groups
2. call `Hash.from_xml("<text>Parse me</text>")`

### Expected behavior
Hash returned `{"text"=>"Parse me"}`

### Actual behavior
Missing `rexml/document` exception raised

### Notes
`rexml` gem is a bundled gem since Ruby 3.0.0. So it should be added to `activesupport.gemspec` as dependency, because  `XmlMini.backend = "REXML"` is still in use.

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/commit/f624ed09abba4a0bae64eb699c9fc2e3f9bdc2dc
