### ISSUE TITLE
ActionText is rendering partials way too many times when parent is saved.

### ISSUE THREAD

**Issue by WriterZephos** [rails/rails#43469]
Use the Trix editor and follow the guide on Go Rails here: https://www.youtube.com/watch?v=aE1Mqzpxa1U to implement @mentions. Then implement `to_attachable_partial_path` and put a breakpoint inside it, or put a breakpoint inside the default partial that is rendered when the model gets rendered as an attachment.

You will hit the break point several times before and after the content is stored.

I think it is the same problem described here: https://github.com/rails/rails/issues/37818

### Expected behavior
Should not render partial more than once for the returned HTML.

### Actual behavior
It renders the partial many times

### System configuration
**Rails version**:
7.0.0.alpha2

**Ruby version**:
2.7

**Comment by jacobherrington** [comment]
Hey @WriterZephos!

In the previous issue you linked, there is a workaround suggested. I made a PR that uses that suggestion. You're welcome to pull down my branch and see if it solves the issue on your project. 👍 

I'm not sure if it *should* be merged or not, but if you have any feedback, let me know!

**Comment by WriterZephos** [comment]
Hey sorry my reply took so long. Thanks for opening the PR. I hope it gets merged!
