### ISSUE TITLE
Suggestion of improvement for the getting started guide

### ISSUE THREAD

**Issue by psychoslave** [rails/rails#43475]
Hello,

In section 8 of [Getting Started](https://guides.rubyonrails.org/getting_started.html), users learn how to add a status attribute. By the end of the section, they should have this feature working well, including a count of public posts on the index page. However if the user played with the blog application and already created some posts, this count won't include these posts as values have not been set.

The reader should be informed of that and indicated a way to tackle this kind of issue, either by modifying the migration scripts or run a console and run something equivalent to: 
```ruby
[Article, Comment].each{|model| model.all.each{|ens| ens.status = 'public'} }
```

**Comment by ghiculescu** [comment]
Thanks for the feedback. Maybe it’s better to give the new status column a default, and backfill the data all in one migration. Anyway, would you like to make a PR to update the guide?

**Comment by viktorianer** [comment]
I think it is a really common case, to change data after or during a DB migration. In real projects, we will find different ways to deal with that problem. From "one shot rake task" to put this "modifying data" task in the migration himself. In later case, if some classes changing, the migration will not work (new developers in team).

I would love to see some best practice examples in [Migration Guides](https://guides.rubyonrails.org/active_record_migrations.html). And if I am right, there are some examples already under  section 3.9 [using-reversible](https://guides.rubyonrails.org/active_record_migrations.html#using-reversible) and following?!

So, maybe it is OK to write a small example at section 8 of Getting Started and add a link to the Migration Guides section 3.9?
