### ISSUE TITLE
self-referential models sometimes have wrong inverse-of-related object references when first created

### ISSUE THREAD

**Issue by jjb** [rails/rails#43478]
When first persisting rows for models with a self-referential association, the reference is sometimes wrong in the in-memory object.

reproduction repo with tests: https://github.com/jjb/self-referencial-repro

### Steps to reproduce

```console
git clone https://github.com/jjb/self-referencial-repro.git
cd self-referencial-repro
bundle
rails db:setup
./bin/setup
rails c
```

```ruby
t1 = Thing.create
t2 = Thing.create(thing: t1)
t3 = Thing.create(thing: t2)

t1.id
# => 1
t2.id
# => 2
t3.id
# => 3
t1.thing_id
# => nil
t2.thing_id
# => nil
t3.thing_id
# => 2
```

this seems to only be a problem when first creating the records. if they are loaded from the db, they are correct.

This fixes the behavior:

```ruby
class Thing << ApplicationRecord
  belongs_to :thing, inverse_of: :things
  has_many :things, inverse_of: :thing
end
```

### System configuration
**Rails version**: 6.1
 
**Ruby version**: 3 and 2.7

**Comment by jjb** [comment]
@composerinteralia @ktmouk @alpaca-tc @cat2koban @luccafort @jstncarvalho @TerencedzLi @drose-shopify 

Any ideas?

**Comment by jjb** [comment]
although not sure if the bug will be present when the association has a custom name https://github.com/rails/rails/blob/main/activerecord/test/models/comment.rb#L26-L27

anyway i'll give it a shot and maybe make a new model

**Comment by intrip** [comment]
> The `belongs_to :thing` association is finding itself as an inverse, which I don't think is ever what we want. The simplest fix might be to check `reflection != self` in `valid_inverse_reflection?`. I'll open a PR if nobody beats me to it.

Agree!

**Comment by jjb** [comment]
Wow, thanks for all of the above! while searching for has_many_inversing i immediately found https://github.com/rails/rails/pull/41552 which is about the same problem and seemed to be going well but then became stale, maybe someone could look at that
