### ISSUE TITLE
cannot load such file -- polyamorous/activerecord_7.0_ruby_2/join_association (LoadError)

### ISSUE THREAD

**Issue by danquick** [rails/rails#43494]
I'm updating a 6.1 rails app to 7.0.0.alpha2 - just to see

Using ransack to the character by character search.

Get: polyamorous/activerecord_7.0_ruby_2/join_association (LoadError)

View:
<%= form.text_field :q, placeholder: "Address",size:50, data: {behavior: "autocomplete"} %>

Model:

has_many :jobsitecontacts
  has_many :jobsite_ests
  def self.search(params)
    jobsites = Jobsite.where('address LIKE ?',"%#{params[:search]}%" ).limit(10) 
    if params[:search].present?
      jobsites
    end
  end

I upgraded from gem 'ransack', '~>  2.3.0 to gem 'ransack', '~> 2.4.2' no change.

/Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- polyamorous/activerecord_7.0_ruby_2/join_association (LoadError)
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/zeitwerk-2.5.0.beta6/lib/zeitwerk/kernel.rb:35:in `require'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/ransack-2.4.2/lib/polyamorous/polyamorous.rb:16:in `block in <main>'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/ransack-2.4.2/lib/polyamorous/polyamorous.rb:15:in `each'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/ransack-2.4.2/lib/polyamorous/polyamorous.rb:15:in `<main>'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/zeitwerk-2.5.0.beta6/lib/zeitwerk/kernel.rb:35:in `require'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/ransack-2.4.2/lib/ransack.rb:4:in `<main>'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/zeitwerk-2.5.0.beta6/lib/zeitwerk/kernel.rb:35:in `require'
	from /Users/danielquick/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:66:in `block (2 levels) in require'
	from /Users/danielquick/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:61:in `each'
	from /Users/danielquick/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:61:in `block in require'
	from /Users/danielquick/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:50:in `each'
	from /Users/danielquick/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler/runtime.rb:50:in `require'
	from /Users/danielquick/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/bundler.rb:174:in `require'
	from /Users/danielquick/www/rails7/bob7/config/application.rb:7:in `<main>'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/zeitwerk-2.5.0.beta6/lib/zeitwerk/kernel.rb:35:in `require'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:137:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/railties-7.0.0.alpha2/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/railties-7.0.0.alpha2/lib/rails/command/base.rb:87:in `perform'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/railties-7.0.0.alpha2/lib/rails/command.rb:48:in `invoke'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/railties-7.0.0.alpha2/lib/rails/commands.rb:18:in `<main>'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/danielquick/.rvm/gems/ruby-3.0.2/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from bin/rails:4:in `<main>'

### Expected behavior

A text field that shows query results after each character is typed. 

### Actual behavior
cannot load such file -- polyamorous/activerecord_7.0_ruby_2/join_association (LoadError)

### System configuration
7.0.0.alpha2

**Ruby version**:
3.0.2p107

**Comment by yahonda** [comment]
This is not an Rails issue because the `polyamorous/activerecord_7.0_ruby_2/join_association` directory
belongs to ransack.

I've found a similar issue reported https://github.com/activerecord-hackery/ransack/issues/1251

**Comment by danquick** [comment]
Thank you for looking into this.
