### ISSUE TITLE
Performance impact of reloader/executor (does the reloader/executor restrict number of db connections used within the block?)

### ISSUE THREAD

**Issue by jjb** [rails/rails#43504]
For ruby-clock, I recently add reloader wrapping for each run of a scheduled job: https://github.com/jjb/ruby-clock/commit/9d44d82f5114d71b5270f059693be6697c258009#diff-c297bb981ee55224743b8406b4d8c5b1acb02798940f2a44bd0183844c7451a1

After deploying on a pretty busy application with 60 jobs, I saw the connections used by the ruby-clock pool go down from about 10 to 5.

It also seems like seemingly all jobs have worse performance. in some cases 0.3seconds → 1 second, in other cases 80 seconds → 600 seconds. So, it's not just an issue of db connection management overhead.

my only guess is that this is because the number of connections available has decreased and my code was previously benefitting from multiple connections.

i seem to be unable to find any info or discussion about this, so i'm doubting my theory.

Any ideas here? i'll try to submit some updates to the docs if i figure it out.

thanks!

/cc @luizkowalski  @pocke @jonathanhefner @matthewd

**Comment by bbugh** [comment]
@jjb did that resolve the performance with ruby-clock?

**Comment by jjb** [comment]
@luizkowalski @bbugh I wish I had some interesting numbers for you but too many variables were changing at that time. what i can tell you is it's been in production in the version 1 form for many months on a large production system
