### ISSUE TITLE
javascript_packs_with_chunks_tag loads another files of different entry point

### ISSUE THREAD

**Issue by ahmedsayedabdelsalam** [rails/rails#43522]
Hello everyone,

I am working on a rails project, I have a frontend app and a dashboard

I use react components in frontend in some pages
and use some libraries like select2 and Trix on the dashboard

adding all the frontend and dashboard js in one single bundle will be not so good especially for the google **pagespeed** tool which will detect much code not used

I am using **webpacker 5** and want to make 2 separate bundles one for each domain, how can I achieve that?

now I have **app/javascript/packs/application.js**
and I am using splitChunks which will create (_vendor-application.js, runtime-application.js, application.js_)
and include it in my frontend layout like this
**<%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>**

but when I add a new file **app/javascript/packs/admin.js** and include it in my dashboard like this 
**<%= javascript_packs_with_chunks_tag 'admin', 'data-turbolinks-track': 'reload' %>**
I found that the **frontend** still requesting a script with the name (_vendor-admin.js_) and the browser detects unused js code again

anyone knows why this is happening although I am requesting **application** script only ?!!

**Comment by Sangarkhan786** [comment]
> Hello everyone,
> 
> I am working on a rails project, I have a frontend app and a dashboard
> 
> I use react components in frontend in some pages and use some libraries like select2 and Trix on the dashboard
> 
> adding all the frontend and dashboard js in one single bundle will be not so good especially for the google **pagespeed** tool which will detect much code not used
> 
> I am using **webpacker 5** and want to make 2 separate bundles one for each domain, how can I achieve that?
> 
> now I have **app/javascript/packs/application.js** and I am using splitChunks which will create (_vendor-application.js, runtime-application.js, application.js_) and include it in my frontend layout like this **<%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>**
> 
> but when I add a new file **app/javascript/packs/admin.js** and include it in my dashboard like this **<%= javascript_packs_with_chunks_tag 'admin', 'data-turbolinks-track': 'reload' %>** I found that the **frontend** still requesting a script with the name (_vendor-admin.js_) and the browser detects unused js code again
> 
> anyone knows why this is happening although I am requesting **application** script only ?!!

**Comment by ghiculescu** [comment]
When you view the source of the page, what `script` tags are being rendered? Here's an example from the docs

![image](https://user-images.githubusercontent.com/509837/146065634-423cc25b-f35a-4f5c-8c7a-64bd1428e451.png)
(from https://github.com/rails/webpacker/tree/5-x-stable#usage)

It'd be good to see your equivalent.
