### ISSUE TITLE
--javascript option causes support for tailwind styled scaffold templates not to be installed

### ISSUE THREAD

**Issue by rubys** [rails/rails#43531]
### Steps to reproduce

```
(rm -rf depot; \
rails new depot -j esbuild --css tailwind; \
cd depot; \
bin/rails generate scaffold Product title:string; \
grep class app/views/products/show.html.erb)
```

### Expected behavior
The generated view should contain class attributes utilizing tailwind classes.

### Actual behavior
No class attribute are defined

Additionally, errors are produced when generating the tailwind class:

```diff
         rails  css:install:tailwind
  Build into app/assets/builds
         exist  app/assets/builds
     identical  app/assets/builds/.keep
- File unchanged! The supplied flag value not found!  app/assets/config/manifest.js
  Stop linking stylesheets automatically
        gsub  app/assets/config/manifest.js
- File unchanged! The supplied flag value not found!  .gitignore
- File unchanged! The supplied flag value not found!  .gitignore
  Remove app/assets/stylesheets/application.css so build output can take over
        remove  app/assets/stylesheets/application.css
  Add stylesheet link tag in application layout
- File unchanged! The supplied flag value not found!  app/views/layouts/application.html.erb
        append  Procfile.dev
  Add bin/dev to start foreman
     identical  bin/dev
  Install Tailwind (+PostCSS w/ autoprefixer)
        create  tailwind.config.js
        create  app/assets/stylesheets/application.tailwind.css
           run  yarn add tailwindcss@latest postcss@latest autoprefixer@latest from "."
```

Note: no errors are produced, and class attributes making use of tailwind classes are added if the `-j esbuild` option is removed from the `rails` command in the test case above.

### Analysis/commentary

The tailwindcss_rails gem has a nice feature whereby it provides Tailwind styled scaffold templates: https://github.com/rails/tailwindcss-rails/pull/71

Rails, by default, will install tailwindcss_rails via `tailwindcss:install` **unless the js option is specified**, see:

https://github.com/rails/rails/blob/83808166e6c659fccb4019ab936c5714ff5277f2/railties/lib/rails/generators/app_base.rb#L326-L330

This was added with the following commit:
https://github.com/rails/rails/commit/83808166e6c659fccb4019ab936c5714ff5277f2#diff-a83245368df35c610a37260d0a51041de89211857d47cfd0b2d1301a11709164R409-R412

Likely one of the following two options will need to be done to fix this problem:

  * `css:install:tailwind` (and therefore, cssbundling-rails) will install tailwindcss_rails in addition to what it is currently doing
  * rails will need to install both cssbundling-rails and tailwindcss_rails 

Either way, the errors produced by `css:install:tailwind` should be addressed.

### System configuration
**Rails version**:
Rails 7.0.0.alpha2

**Ruby version**:
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

**Comment by ro31337** [comment]
Similar bug with the same version of Ruby and Rails.

Error says "File unchanged! The supplied flag value not found!" when you type either `rails new whatever1 --css=sass` or `rails new whatever2 --css=bulma`

There is a single error though, complaining about "File unchanged! The supplied flag value not found!" for `app/views/layouts/application.html.erb`.

Screenshot:

![image](https://user-images.githubusercontent.com/1477672/141695306-d4916ac9-5c2a-49f4-bfbf-420f59da25ac.png)

**Comment by rafaelfranca** [comment]
@dhh do you have an opinion on how we should fix this case?

**Comment by dhh** [comment]
The tailwindcss-rails gem is exclusively for use with node-less setup. It has a number of restrictions on customization at the moment, but then on the other hand it has these nice tailored templates. But it's either-or at the moment. If you use node-powered JS, you'll get the node-version of Tailwind, straight from the npm package. It doesn't even install the tailwindcss-rails gem, so therefore you also won't get the templates. So in my opinion, we simply need to document this difference. There are two ways to get Tailwind, depending on whether you run node or not, and there are pros and cons.

Re: "File unchanged! The supplied flag value not found!", that's an artifact of Thor, which complains excessively when a modification to a file has already been made. cssbundling-rails and jsbundling-rails both need to do some setup to shared files, and they can each be used alone, so they both need to attempt to do these changes. I think the answer here is to change Thor such that it does not complain in this alarming way when the change it's looking to do have already been done – that's how it deals with other actions that lead to the desired outcome.

**Comment by rubys** [comment]
Just a heads up: i have a piece of this working on my machine, and will be posting something publicly this weekend.  I can successfully take a project that was generated with import maps and tailwind, unwind the installs of tailwind, stimulus, turbo, and importmaps, then install jsbundler, turbo, stimulus, and tailwind.

Admittedly this is just a start.  It still may end up being the case that there is a binary choice, but as a first step, perhaps we can make that not be something you have to decide when you first create your project, and not something you can easily change later.

This is also related to the Thor messages issue: I believe that the templates need to be more resilient and handle more cases where the files in question already exist and have content in them.

**Comment by rubys** [comment]
Looking at the tailwindcss-rails gem, the engine has 4 initializers, provides a number of rake tasks, and scaffold templates.

Looking at other -rails gems (e.g. turbo, stimulus), there is code along the lines of

```ruby
if Rails.root.join("config/importmap.rb").exist?
```

If such a check were placed around the initializers, inclusion of this gem would make the scaffolding functionality available to node users.
