### ISSUE TITLE
Specifying unknown options ignores them silently (`rails new myapp --something` for instance)

### ISSUE THREAD

**Issue by dorianmariefr** [rails/rails#43564]
### Steps to reproduce

- `rails new myapp --something`
- or `rails new myapp --js esbuild`

### Expected behavior

Raises an error saying that the option is unknown and point to the help usage of the command

### Actual behavior

Ignores silently the extra options

### System configuration

**Rails version**: Rails 7.0.0.alpha2
**Ruby version**: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

I tried to look into how to fix it but not sure how, seems like every command should declare all their possible options (maybe already done for the help message) seems to be in `lib/rails/generators.rb`

**Comment by rafaelfranca** [comment]
This is by design to support application templates to be handling their own options. Thank you for the issue.
