### ISSUE TITLE
Rails CI raises Segmentation fault against ruby3.1.0dev which has `Class#descendants`

### ISSUE THREAD

**Issue by yahonda** [rails/rails#43574]
Rails CI raises Segmentation fault against ruby3.1.0dev which has `Class#descendants`. 

### Steps to reproduce
Rails CI is getting segmentation fault since https://buildkite.com/rails/rails/builds/82202

### Expected behavior
It should work successfully.

### Actual behavior
It gets segmentation fault as follows.
https://buildkite.com/rails/rails/builds/82202#51423820-56ab-46c5-9982-ebcf6af9b3c4/1116-1122

```ruby
/rails/activesupport/lib/active_support/callbacks.rb:854: [BUG] Segmentation fault at 0x00007f3bf4d1f588
```

### System configuration
**Rails version**: main branch including https://github.com/rails/rails/commit/ffae3bd8d69f9ed1ae185e960d7a38ec17118a4d via https://github.com/rails/rails/pull/43548

**Ruby version**: ruby 3.1.0dev (2021-10-26T19:35:21Z master 717ab0bb2e) [x86_64-linux]

### Additional information

This segmentation raises only when both of these conditions are satisfied.

1. Use Rails main branch which has https://github.com/rails/rails/commit/ffae3bd8d69f9ed1ae185e960d7a38ec17118a4d via https://github.com/rails/rails/pull/43548

2. Use Ruby master branch which has https://github.com/ruby/ruby/commit/717ab0bb2ee63dfe76076e0c9f91fbac3a0de4fd via https://github.com/ruby/ruby/pull/4974

### Workarounds found
Then workarounds found so far are:

1. Revert https://github.com/rails/rails/commit/ffae3bd8d69f9ed1ae185e960d7a38ec17118a4d at Rails repository

2. Use ruby3.1.0dev version whose latest commit is https://github.com/ruby/ruby/commit/a4d5ee4f31bf3ff36c1a8c8fe3cda16aa1016b12 , which is the previosu commit of https://github.com/ruby/ruby/commit/717ab0bb2ee63dfe76076e0c9f91fbac3a0de4fd

**Comment by yahonda** [comment]
Usually this kind of segfault at Ruby should be reported to bugs.ruby-lang.org but Rails has some `Class.method_defined?(:descendants) # RUBY_VERSION >= "3.1"` code then, reported as Rails issue first.

**Comment by byroot** [comment]
> but Rails has some `Class.method_defined?(:descendants) # RUBY_VERSION >= "3.1"`

That doesn't change anything. We should report this upstream.

**Comment by yahonda** [comment]
Opened https://bugs.ruby-lang.org/issues/18282

**Comment by casperisfine** [comment]
Thank you ❤️

**Comment by ghiculescu** [comment]
I’m going to close this as it’s been confirmed a bug in Ruby, so presumably it’ll fix itself here eventually.

**Comment by yahonda** [comment]
For the future references, this issue should have been addressed via https://github.com/ruby/ruby/pull/5097 .
