### ISSUE TITLE
Cached AR object incompatibility between <6 and >=6

### ISSUE THREAD

**Issue by jjb** [rails/rails#43582]
ActiveRecord objects saved in the cache while running rails <6 that are loaded in rails >=6 will return `nil` for `.id`. `.attributes` shows the correct `id`, as does `[:id]`. 

This problem presented when I deployed a well-tested 5.2→6.1 PR to prod and immediately had problems anywhere that expected object ids. (in QA we didn't test cross-version cache compatibility)

my short-term solution is to add `namespace: 'rails-6.1'` to my cache config to bust the entire cache, which is of course not ideal.

The problem is described in this SO question: https://stackoverflow.com/questions/66081310/marshal-conflict-between-rails-activerecord-versions. The author believes the problem started here: https://github.com/rails/rails/commit/b6828fc91531ae0cc0a0f216705dd19112596301

* I was surprised to not find more discussion about this problem anywhere, so maybe Im misunderstanding the situation or why my use case is atypical
* I don't know if the problem could/should be solved in code
* maybe a note should be added to the 6.0 upgrade guide?

**Comment by jjb** [comment]
@kamipo

**Comment by Legomegger** [comment]
Faced the same issue, any response from rails team please?

**Comment by fatkodima** [comment]
To clarify, do you cache whole ActiveRecord objects using the `Rails.cache`? If yes, what is the use case for this?

**Comment by Legomegger** [comment]
> To clarify, do you cache whole ActiveRecord objects using the `Rails.cache`? If yes, what is the use case for this?

Yes, using `Rails.cache.write`.
I noticed when I cache same simple object for example `object = {a: 1, b: 2}` repl returns different output for 5 and 6 rails
