### ISSUE TITLE
Schema dumper incorrectly dumps operator-based generated PG columns

### ISSUE THREAD

**Issue by DNNX** [rails/rails#43590]
### Steps to reproduce

* Clone Rails repo or check out the latest revision if you have it cloned already.
* `cd rails`.
* Apply the patch below.
* Run `(cd activerecord && ARCONN=postgresql bundle exec ruby -Itest test/cases/adapters/postgresql/virtual_column_test.rb -n test_schema_dumping)`.

```diff
diff --git a/activerecord/test/cases/adapters/postgresql/virtual_column_test.rb b/activerecord/test/cases/adapters/postgresql/virtual_column_test.rb
index 069e10e74b..a7d4562e4b 100644
--- a/activerecord/test/cases/adapters/postgresql/virtual_column_test.rb
+++ b/activerecord/test/cases/adapters/postgresql/virtual_column_test.rb
@@ -19,6 +19,8 @@ def setup
         t.virtual :upper_name,  type: :string,  as: "UPPER(name)", stored: true
         t.virtual :name_length, type: :integer, as: "LENGTH(name)", stored: true
         t.virtual :name_octet_length, type: :integer, as: "OCTET_LENGTH(name)", stored: true
+        t.jsonb :tender
+        t.virtual :love, type: :string, as: "tender->>'love'", stored: true
       end
       VirtualColumn.create(name: "Rails")
     end
@@ -78,6 +80,8 @@ def test_schema_dumping
       assert_match(/t\.virtual\s+"upper_name",\s+type: :string,\s+as: "upper\(\(name\)::text\)", stored: true$/i, output)
       assert_match(/t\.virtual\s+"name_length",\s+type: :integer,\s+as: "length\(\(name\)::text\)", stored: true$/i, output)
       assert_match(/t\.virtual\s+"name_octet_length",\s+type: :integer,\s+as: "octet_length\(\(name\)::text\)", stored: true$/i, output)
+      assert_match(/as:.*tender.*love/, output)
+      assert_no_match(/as: nil/, output)
     end
 
     def test_build_fixture_sql
```

### Expected behavior

Dumper should generate the following output for the new virtual column:

```ruby
    t.virtual "love", type: :string, as: "(tender ->> 'love'::text)", stored: true
```

The test should be green, too. The two new assertions should pass.

### Actual behavior

The test fails because `as: nil` is generated for the new virtual column.

```ruby
    t.virtual "love", type: :string, as: nil, stored: true
```

### System configuration

**Rails version**:
I reproduced it on 57fe7dfce9fc751dd521ec8e175924eb1480b5d5, but it's probably been broken since #41856, when the support for generated Postgresql columns was added.

**Ruby version**:
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin17]

### Possible cause

The culprit is likely to be somewhere in the [has_default_function?](https://github.com/rails/rails/blob/57fe7dfce9fc751dd521ec8e175924eb1480b5d5/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L650) method. The regexp that is used there, `%r{\w+\(.*\)|\(.*\)::\w+|CURRENT_DATE|CURRENT_TIMESTAMP}`, does not recognize the expressions like `tender->>'love'` as a function call. Modifying the regexp to match this helps, but I'm not sure this modification can break anything, so I'm not sending a PR.

### Workaround

In this particular case, replacing `as: "tender->>'love'"` with `as: "jsonb_extract_path_text(tender, 'love')"` helps (and also makes the test green).

It's not always possible to find a suitable workaround though. For example, creating a virtual column with `as: "id + 100"` generates `as: nil` in the schema dump. I don't know if there is an easy way to rewrite the expression in such a way that the dumper is happy.

**Comment by ghiculescu** [comment]
> Modifying the regexp to match this helps, but I'm not sure this modification can break anything, so I'm not sending a PR.

I think you should put a branch up, so we can run tests and see any potential changes.

**Comment by ghiculescu** [comment]
I'm surprised changing the regex fixes things though, given that `virtual?` seems to only depend on the `generated` attribute https://github.com/rails/rails/blob/25418676cd36d5b4f87a55178f53b80f2fdcf900/activerecord/lib/active_record/connection_adapters/postgresql/column.rb#L23

**Comment by fatkodima** [comment]
This was fixed by https://github.com/rails/rails/pull/44319.
