### ISSUE TITLE
ActiveRecord::Relation#each_slice runs an extra query before the select query

### ISSUE THREAD

**Issue by ttstarck** [rails/rails#43603]
### Steps to reproduce
Using Rails version >= 5.0, run `#each_slice` on an `ActiveRecord::Relation` object and see that a count query followed by a select query are made.

### Expected behavior

To match the behavior from Rails 4: When calling `#each_slice` on an `ActiveRecord::Relation` object, it only generates a select query.
[Rails 4 Test Case](https://gist.github.com/ttstarck/2e29c913626bc39ffee0715cfa4e8254#file-rails_4_test-rb)
[Rails 4 Test Run Output](https://gist.github.com/ttstarck/2e29c913626bc39ffee0715cfa4e8254#file-rails_4_test_run_output-txt)

``` ruby
# Using Post defined in Rails 4 Test Case above
ActiveRecord::Base.logger = Logger.new(STDOUT);
Post.all.class
=> Post::ActiveRecord_Relation
Post.all.each_slice(5) {}
D, [2021-11-05T17:15:11.496169 #35496] DEBUG -- :   Post Load (0.2ms)  SELECT "posts".* FROM "posts"
=> nil
```

### Actual behavior

Calling `#each_slice` on an `ActiveRecord::Relation` object generates two queries: a count query followed by a select query.

[Rails 6 Test Case](https://gist.github.com/ttstarck/2e29c913626bc39ffee0715cfa4e8254#file-rails_6_bug_test-rb)
[Rails 6 Test Run Output](https://gist.github.com/ttstarck/2e29c913626bc39ffee0715cfa4e8254#file-rails_6_bug_test_run_output-txt)

``` ruby
# Using Post defined in the Rails 6 Test Case above
ActiveRecord::Base.logger = Logger.new(STDOUT);
Post.all.class
=> Post::ActiveRecord_Relation
Post.all.each_slice(5) {}
D, [2021-11-05T17:11:12.366823 #35456] DEBUG -- :    (0.2ms)  SELECT COUNT(*) FROM "posts"
D, [2021-11-05T17:11:12.367303 #35456] DEBUG -- :   Post Load (0.1ms)  SELECT "posts".* FROM "posts"
=> nil
```

### Possible Fix
In Rails 4, `#each_slice` was not defined on the relation object, but was instead run against the `.to_a` of the relation (see [here](https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/relation/delegation.rb#L131-L132)).

However in Rails 5 and beyond, `#each_slice` was missed when adding the delegations in `ActiveRecord::Delegation` to the `records` method. A fix for this would be to add `#each_slice` into that list defined in `ActiveRecord::Delegation` [here](https://github.com/rails/rails/blob/5-2-stable/activerecord/lib/active_record/relation/delegation.rb#L71-L74)
``` ruby
module ActiveRecord::Delegation
  delegate :each_slice, to: :records
end
```

[Rails 6 Test with Fix Added](https://gist.github.com/ttstarck/2e29c913626bc39ffee0715cfa4e8254#file-rails_6_fixed_test-rb)
[Rails 6 Test Run with Fix Added](https://gist.github.com/ttstarck/2e29c913626bc39ffee0715cfa4e8254#file-rails_6_fixed_test_run-txt)

### System configuration
**Rails version**: Bug exists in versions >= 5.0, tested on 5.2.6 and 6.1.4.1
**Ruby version**: 2.6.1

**Comment by yesthesoup** [comment]
Ran into this as well in Rails 7.1.3.4, Ruby 3.3.4
