### ISSUE TITLE
HashWithIndifferentAccess dup ignores instance variables

### ISSUE THREAD

**Issue by patodevilla** [rails/rails#43602]
### Steps to reproduce
When duplicating an `ActiveSupport::HashWithIndifferentAccess` instance, only keys and default block are considered.

The code that causes the problem can be found [here](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/hash_with_indifferent_access.rb#L256) and [here](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/hash_with_indifferent_access.rb#L68)

```ruby
hash = ActiveSupport::HashWithIndifferentAccess.new({})
hash.instance_variable_set('@hello', 1)
hash.dup.instance_variable_get('@hello')
# => nil
```

### Expected behavior
Like in a regular dup call, instance variables should be copied

```ruby
hash = {}
hash.instance_variable_set('@hello', 1)
hash.dup.instance_variable_get('@hello')
# => 1
```

### Actual behavior
Instance variables are ignored

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.4

**Comment by ghiculescu** [comment]
Hmm, this feels intended to me. The docs [say that `dup` behaves in a specific way](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/hash_with_indifferent_access.rb#L248..L255), based on how `HashWithIndifferentAccess` is normally used. Is there a use case for setting instance variables on a `HashWithIndifferentAccess`?

**Comment by patodevilla** [comment]
Thanks for the rapid response! It might be completely out of the scope of the purpose of `HashWithIndifferentAccess ` but I'm building a gem with many backing classes for JsonSchema based forms, [something like this](https://rjsf-team.github.io/react-jsonschema-form/).

Since JsonSchema does not differentiate between symbols and strings it made me a lot of sense to extend from `HashWithIndifferentAccess` and it all works like a tree of classes, which gets constructed from another gem that I built that allows you to define transforms for each key in a `Hash`.

I'll be able to monkey path this, so no worries. I just caught me by surprise and took me a while to find the bug I'm dealing with 🐛.

**Comment by ghiculescu** [comment]
Yeah, if you are subclassing again, I think monkey patching is the way to go - as this seems like intended behaviour.

**Comment by dpep** [comment]
here's a potential fix: https://github.com/dpep/rails/compare/master..indifferent-access-dup

```ruby
    def dup
      self.class.new(self).tap do |new_hash|
        set_defaults(new_hash)

        instance_variables.each do |x|
          new_hash.instance_variable_set(x, instance_variable_get(x))
        end
      end
    end
```

that said, this sounds like an edge case that isn't really intended to be supported.  subclass with an override `dup` might be a cleaner route
