### ISSUE TITLE
Remove uglifier as an asset compressor

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#43610]
Uglifier does not support modern JS.  This commit indicates it is for ES5 only: https://github.com/lautis/uglifier/commit/902cc160d3f8f405a35a8f16da227489366a3ad6

There are important ES6 features that are missing: https://github.com/lautis/uglifier/issues/174

This causes many issues that would be avoided if uglifier was removed from the Guide. 

I'm happy to do this work if any one with commit thinks it's worthwhile.

**Comment by hahmed** [comment]
@jcoyne I think you were referring to https://edgeguides.rubyonrails.org/asset_pipeline.html#javascript-compression ?

If that's the case, sounds good 👍 looks like the PR https://github.com/rails/sprockets/pull/713 is recommending the same thing
