### ISSUE TITLE
MemCacheStore should send cache keys with TTL of 0 to memcached 

### ISSUE THREAD

**Issue by andrejbl** [rails/rails#43619]
Memcached supports setting the TTL to 0 to cache the record [permanently](https://stackoverflow.com/questions/6027517/can-the-time-to-live-ttl-for-a-memcached-key-be-set-to-infinite/6027559). However, trying to cache a value through `MemCacheStore` with `exipres_in: 0` option instead causes the record to not be cached at all.

### Steps to reproduce
(not providing a test for repro as it requires an externally running memcached server so it is not really self contained, hopefully this is ok as the repro steps are very basic)

Start a memcached server locally: `memcached -p 11211`

In a Rails console, run
```ruby
cache = ActiveSupport::Cache.lookup_store(:mem_cache_store, "localhost:11211", {})
cache.write("key", "value", :expires_in => 0)
cache.read("key") # this will return `nil`
```

### Expected behavior
Entry should be cached indefinitely.

### Actual behavior
Entry is not cached at all.

### System configuration
**Rails version**: 6.1.4.1

**Ruby version**: 2.6.5

**Comment by lfalcao** [comment]
Hi @andrejbl 

When you pass the `:expires_in` it saves the cache entry with `value + Time.now`, so when you try to read it Rails deletes it as its already expired... (Source: https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache.rb#L923)

Possible fix:

``ruby
        @expires_in = expires_at&.to_f || expires_in && expires_in > 0 && (expires_in.to_f + Time.now.to_f)
``

**Comment by ghiculescu** [comment]
If you include the `expires_in` parameter, the entry will never expire.

That said, I've also come across situations where that results in messy code. The fix above would work, but it would break existing code if anyone is depending on the behaviour described (though I dunno why you would...).

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/43727 treats it as a bug, but I'm happy to add a config option if we need backward compat.

**Comment by ghiculescu** [comment]
Chatted to @matthewd and his view was this is expected behaviour.

You can use `expires_in: nil`, or exclude the option entirely, to have non-expiring entries.
