### ISSUE TITLE
Parallelizing setup for ActiveStorage doesnt expose setter

### ISSUE THREAD

**Issue by ParamagicDev** [rails/rails#43616]
### Steps to reproduce

When reading through the ActiveStorage guides, it recommends the below code:

```ruby
class ActiveSupport::TestCase
  parallelize(workers: :number_of_processors)
  parallelize_setup do |i|
    ActiveStorage::Blob.service.root = "#{ActiveStorage::Blob.service.root}-#{i}"
  end
  fixtures :all
end
```

https://edgeguides.rubyonrails.org/active_storage_overview.html#system-tests

However, it produces an error.

### Expected behavior

The above should run without error when setting up tests.

### Actual behavior

The following error is produced:

<img width="1440" alt="Screen Shot 2021-11-09 at 12 57 03 AM" src="https://user-images.githubusercontent.com/26425882/140870804-341e7514-00ca-4544-9ee5-96bd550e2283.png">

### How to fix

The below will work since instead of using a setter, it manually sets the instance variable.

```rb
class ActiveSupport::TestCase
  parallelize(workers: :number_of_processors)
  parallelize_setup do |i|
    ActiveStorage::Blob.service.instance_variable_set(:@root, "#{ActiveStorage::Blob.service.root}-#{i}")
  end
  fixtures :all
end
```

<img width="1427" alt="Screen Shot 2021-11-09 at 12 56 25 AM" src="https://user-images.githubusercontent.com/26425882/140871040-2348e59b-e6ea-4eb1-a6ca-9a5b37fd9820.png">

Im not sure if this is a documentation issue or a legitimate bug.

### System configuration

**Rails version**: 6.1.3

**Ruby version**: 2.7.3

**Comment by SkipKayhil** [comment]
Hey @ParamagicDev,

It looks like this documentation/functionality was added in ea43daa, so it won't work in Rails 6.1 but should be possible in Rails 7

**Comment by ghiculescu** [comment]
Yes that's right. https://github.com/rails/rails/pull/42163 is in Rails 7.

You should use https://guides.rubyonrails.org/active_storage_overview.html#system-tests (note the subdomain) for the current version of Rails. `edgeguides` is for code on the current `main` branch.
