### ISSUE TITLE
ActiveRecord generates new instance of `has_many` relation, if `has_many_through` relation is iterated from a callback

### ISSUE THREAD

**Issue by mcfoton** [rails/rails#43617]
There's an `Order` model:

```
 has_many :order_items
 has_many :dishes, through: :order_items
 ```
When I try to create a new `Order` together with a new `OrderItem` (see test below), another `OrderItem` suddenly is created. It happens simply because I try to iterate over `dishes` in the `after_save` callback 🤔 

Seems like a bug, but may also be my lack of understanding, would appreciate any suggestions.
Tested with Rails 6.1.x, but same behavior is seen with version 5.x.x

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 6.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :orders, force: true do |t|
    t.integer :prep_time
  end

  create_table :order_items, force: true do |t|
    t.integer :order_id
    t.integer :dish_id
  end

  create_table :dishes, force: true do |t|
    t.integer :name
    t.integer :prep_time
  end
end

class Order < ActiveRecord::Base
  has_many :order_items
  has_many :dishes, through: :order_items

  def iterate_over_dishes
    dishes.map(&:prep_time).sum
  end
end

class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :dish

  after_save -> { order.iterate_over_dishes }
end

class Dish < ActiveRecord::Base

end

class BugTest < Minitest::Test
  def test_association_stuff
    dish = Dish.create!(prep_time: 10)
    order = Order.create!(order_items: [OrderItem.new(dish: dish)])

    assert_equal 1, order.order_items.count
  end
end
```

### Expected behavior
Iterating over `Dishes`, defined as a `has_many_through` relation on the `Order`, should not create another `OrderItem`.

### Actual behavior
Second `OrderItem` is created

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.4

**Comment by Jay0921** [comment]
This is interesting. While we are finding the root cause, I believe changing `after_save` to `after_commit` will solve the issue.

**Comment by mcfoton** [comment]
still happens with `activerecord 7.0.2.2`

**Comment by mansakondo** [comment]
Hi @mcfoton. Like mention above, I think that using `after_commit` is the way to go.

If we take a look at the generated queries, we can see the database tries to create and load the `OrderItem` in the same transaction:
```
D, [2022-02-20T17:26:43.778975 #8318] DEBUG -- :   OrderItem Create (0.0ms)  INSERT INTO "order_items" ("order_id", "dish_id") VALUES (?, ?)  [["order_id", 1], ["dish_id", 1]]
D, [2022-02-20T17:26:43.782318 #8318] DEBUG -- :   Dish Load (0.1ms)  SELECT "dishes".* FROM "dishes" INNER JOIN "order_items" ON "dishes"."id" = "order_items"."dish_id" WHERE "order_items"."order_id" = ?  [["order_id", 1]]
```
But since the transaction wasn't commited yet, the database cannot find the `OrderItem` so another insert is performed to create it:
```
D, [2022-02-20T17:26:43.778975 #8318] DEBUG -- :   OrderItem Create (0.0ms)  INSERT INTO "order_items" ("order_id", "dish_id") VALUES (?, ?)  [["order_id", 1], ["dish_id", 1]]
D, [2022-02-20T17:26:43.782318 #8318] DEBUG -- :   Dish Load (0.1ms)  SELECT "dishes".* FROM "dishes" INNER JOIN "order_items" ON "dishes"."id" = "order_items"."dish_id" WHERE "order_items"."order_id" = ?  [["order_id", 1]]
D, [2022-02-20T17:26:43.783235 #8318] DEBUG -- :   OrderItem Create (0.0ms)  INSERT INTO "order_items" ("order_id", "dish_id") VALUES (?, ?)  [["order_id", 1], ["dish_id", 1]]
D, [2022-02-20T17:26:43.783413 #8318] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
```
Thus, when the transaction will be commited we'll have 2 insert statements instead of 1.

When using `after_commit`, the database will try to load the `OrderItem` in a diffrent transaction:
```
D, [2022-02-20T17:56:10.603509 #9146] DEBUG -- :   OrderItem Create (0.0ms)  INSERT INTO "order_items" ("order_id", "dish_id") VALUES (?, ?)  [["order_id", 1], ["dish_id", 1]]
D, [2022-02-20T17:56:10.603694 #9146] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2022-02-20T17:56:10.607014 #9146] DEBUG -- :   Dish Load (0.1ms)  SELECT "dishes".* FROM "dishes" INNER JOIN "order_items" ON "dishes"."id" = "order_items"."dish_id" WHERE "order_items"."order_id" = ?  [["order_id", 1]]
```
So everything will work as expected.

**Comment by mcfoton** [comment]
@mansakondo Thanks a lot for responding and walking me though the SQL queries! What I don't get is this part though:
>  the transaction wasn't commited yet, the database cannot find the OrderItem so another insert is performed to create it:

Why this would be a good idea, to generate another INSERT in that case, why is this even happening, instead of skipping over or trying to resolve the `OrderItem` to the one that it has in memory, staged to be created?

**Comment by mansakondo** [comment]
> Why this would be a good idea, to generate another INSERT in that case, why is this even happening, instead of skipping over or trying to resolve the `OrderItem` to the one that it has in memory, staged to be created?

Ah I get it now. Since `:dishes` is a has_many_through association, instead of manually creating a new `OrderItem`, you need to add new dishes like so:
```ruby
order = Order.create!
dish  = Dish.new(prep_time: 10)
order.dishes << dish
```
Or:
```ruby
order = Order.create!
dish  = order.dishes.build(prep_time: 10)
order.save!
```
This will automaticaly create a new `OrderItem` associated  with `dish`, and `order.dishes` and `order.order_items` will be resolved to what's in memory.

So now you should be able to  `iterate_over_dishes` from an `after_save` callback:
```
D, [2022-02-21T14:06:49.421699 #10808] DEBUG -- :   OrderItem Create (0.0ms)  INSERT INTO "order_items" ("order_id", "dish_id") VALUES (?, ?)  [["order_id", 1], ["dish_id", 1]]
D, [2022-02-21T14:06:49.422395 #10808] DEBUG -- :   Dish Load (0.1ms)  SELECT "dishes".* FROM "dishes" INNER JOIN "order_items" ON "dishes"."id" = "order_items"."dish_id" WHERE "order_items"."order_id" = ?  [["order_id", 1]]
D, [2022-02-21T14:06:49.422669 #10808] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2022-02-21T14:06:49.423048 #10808] DEBUG -- :    (0.0ms)  SELECT COUNT(*) FROM "order_items" WHERE "order_items"."order_id" = ?  [["order_id", 1]]
.

Finished in 0.014971s, 66.7961 runs/s, 66.7961 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
------------------------------------------------------
```
