### ISSUE TITLE
Advisory locks stopped working between 4.2 and 5.2

### ISSUE THREAD

**Issue by jmanian** [rails/rails#43634]
This is not directly an issue with Rails, so my apologies if this is the wrong place for this. I'm hoping someone familiar with ActiveRecord can provide any info that might lead to solving [this issue](https://github.com/ClosureTree/with_advisory_lock/issues/47) in the `with_advisory_lock` gem.

`with_advisory_lock` is a gem that provides methods for acquiring advisory locks in PostgreSQL. I use it in my application to prevent two processes from trying to create the same record simultaneously. (See the above issue for more details.)

When I upgraded my app from 4.2 to 5.2 (a while back) these advisory locks mysteriously stopped working. Does anyone have any ideas about what may have changed from 4.2 to 5.2 that could have made this gem stop functioning?

### Steps to reproduce
See the issue above for an example. As noted there, I have not been able to reproduce this in a development environment, but it happens in my production environment.

### Expected behavior
Advisory locks are acquired and a second process trying to acquire the same lock waits for the first one to release it.

### Actual behavior
The second process does not wait for the first process to release its lock, and instead proceeds with trying to create the same record.

### System configuration
**Rails version**: 5.2.5

**Ruby version**: 2.7.4

`with_advisory_lock`: 4.6.0

**Comment by fatkodima** [comment]
It will be really helpful if you try to come up with a reproducible test case.

**Comment by jmanian** [comment]
I finally was able to reproduce this after examining my real production code. It turns out to not be an issue with the locking, but it's actually a caching issue, where `find_or_initialize_by` thinks thinks that the record does not exist even though it actually does. Here's the sequence of events in the code:
1. Use `find_by` to check for an existing record, which does not yet exist
2. Acquire an advisory lock
3. Use `find_or_initialize_by` with the same query as `find_by` above. At this point the record already exists, because another process just created it, but `find_or_initialize_by` uses the cache and returns a new record.

Here's an example job that I created which reproduces this, and has enough logging to completely understand what's happening. You could swap `UserProfileFieldCategory` for any model you have in your app, and `ordinal` for any attribute.
```ruby
class TestLockJob
  include Sidekiq::Worker

  def perform(n)
    Rails.logger.info "#{jid}: looking for existing category"
    cat = UserProfileFieldCategory.find_by(ordinal: n)
    if cat
      Rails.logger.info "#{jid}: found existing category"
    else
      Rails.logger.info "#{jid}: no category found"
    end

    UserProfileFieldCategory.transaction do
      Rails.logger.info "#{jid}: transaction begun"
      UserProfileFieldCategory.with_advisory_lock("testing transactional advisory lock #{n}", transaction: true) do
        Rails.logger.info "#{jid}: lock acquired"
        cat = UserProfileFieldCategory.find_or_initialize_by(ordinal: n)
        cat.text = SecureRandom.uuid
        if cat.new_record?
          Rails.logger.info "#{jid}: creating new category: #{cat}"
        else
          Rails.logger.info "#{jid}: Updating existing category: #{cat}"
        end
        cat.save!
        Rails.logger.info "#{jid}: ending"
      end
    end
  end
end
```

I started two runs of this job from the console with:
```ruby
2.times { TestLockJob.perform_async(106) }
```

And the full output is below. As you can see, the lock is working correctly: the second job waits for the first to release its lock before acquiring its own. The issue occurs when the second job hits `find_or_initialize_by` using the cache and decides the record doesn't exist, which is no longer correct. (In this case there's no uniqueness constraint at the db level, so it creates a duplicate record.)

I can fix this with `ActiveRecord::QueryCache.uncached`. Does the built-in pessimistic locking do something to avoid this cache issue within locks? E.g. does `with_lock` automatically use `uncached` for the block? If so then I will open an issue on `with_advisory_lock` to follow whatever pattern is used for pessimistic locking.

```
3:32:40 PM worker.1    |  2021-11-12T20:32:40.232Z 49646 TID-2506 TestLockJob JID-f2a91f80f96ea70f88d23301 INFO: start
3:32:40 PM worker.1    |  2021-11-12T20:32:40.233Z 49646 TID-249e TestLockJob JID-7d8cc624f62cb516334c0637 INFO: start
3:32:40 PM worker.1    |  f2a91f80f96ea70f88d23301: looking for existing category
3:32:40 PM worker.1    |  7d8cc624f62cb516334c0637: looking for existing category
3:32:40 PM worker.1    |    UserProfileFieldCategory Load (0.8ms)  SELECT  "user_profile_field_categories".* FROM "user_profile_field_categories" WHERE "user_profile_field_categories"."ordinal" = $1 LIMIT $2  [["ordinal", 106], ["LIMIT", 1]]
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:6
3:32:40 PM worker.1    |  f2a91f80f96ea70f88d23301: no category found
3:32:40 PM worker.1    |    UserProfileFieldCategory Load (0.8ms)  SELECT  "user_profile_field_categories".* FROM "user_profile_field_categories" WHERE "user_profile_field_categories"."ordinal" = $1 LIMIT $2  [["ordinal", 106], ["LIMIT", 1]]
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:6
3:32:40 PM worker.1    |  7d8cc624f62cb516334c0637: no category found
3:32:40 PM worker.1    |     (0.2ms)  BEGIN
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:13
3:32:40 PM worker.1    |  f2a91f80f96ea70f88d23301: transaction begun
3:32:40 PM worker.1    |     (0.1ms)  BEGIN
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:13
3:32:40 PM worker.1    |  7d8cc624f62cb516334c0637: transaction begun
3:32:40 PM worker.1    |     (0.2ms)  SELECT pg_try_advisory_xact_lock(551479762,0) AS tebeb7525ed65f8c368911dbea3c5fa11 /* testing transactional advisory lock 106 */
3:32:40 PM worker.1    |     (0.2ms)  SELECT pg_try_advisory_xact_lock(551479762,0) AS tdee038558bf40ce122fdd92c4bd73973 /* testing transactional advisory lock 106 */
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:15
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:15
3:32:40 PM worker.1    |  f2a91f80f96ea70f88d23301: lock acquired
3:32:40 PM worker.1    |    CACHE UserProfileFieldCategory Load (0.0ms)  SELECT  "user_profile_field_categories".* FROM "user_profile_field_categories" WHERE "user_profile_field_categories"."ordinal" = $1 LIMIT $2  [["ordinal", 106], ["LIMIT", 1]]
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:17
3:32:40 PM worker.1    |  f2a91f80f96ea70f88d23301: creating new category: #<UserProfileFieldCategory:0x00000001113b7178>
3:32:40 PM worker.1    |    UserProfileFieldCategory Create (0.7ms)  INSERT INTO "user_profile_field_categories" ("text", "ordinal", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["text", "825afac4-a088-4820-b225-feea115037cf"], ["ordinal", 106], ["created_at", "2021-11-12 20:32:40.270132"], ["updated_at", "2021-11-12 20:32:40.270132"]]
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:24
3:32:40 PM worker.1    |  f2a91f80f96ea70f88d23301: ending
3:32:40 PM worker.1    |     (1.5ms)  COMMIT
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:13
3:32:40 PM worker.1    |  2021-11-12T20:32:40.273Z 49646 TID-2506 TestLockJob JID-f2a91f80f96ea70f88d23301 INFO: done: 0.04 sec
3:32:40 PM worker.1    |     (0.7ms)  SELECT pg_try_advisory_xact_lock(551479762,0) AS t1ce0e609522634a80fa113efb5f6e147 /* testing transactional advisory lock 106 */
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:15
3:32:40 PM worker.1    |  7d8cc624f62cb516334c0637: lock acquired
3:32:40 PM worker.1    |    CACHE UserProfileFieldCategory Load (0.0ms)  SELECT  "user_profile_field_categories".* FROM "user_profile_field_categories" WHERE "user_profile_field_categories"."ordinal" = $1 LIMIT $2  [["ordinal", 106], ["LIMIT", 1]]
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:17
3:32:40 PM worker.1    |  7d8cc624f62cb516334c0637: creating new category: #<UserProfileFieldCategory:0x00000001113965e0>
3:32:40 PM worker.1    |    UserProfileFieldCategory Create (1.0ms)  INSERT INTO "user_profile_field_categories" ("text", "ordinal", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["text", "bc97284e-a771-4de0-939c-8854905a1ac6"], ["ordinal", 106], ["created_at", "2021-11-12 20:32:40.383075"], ["updated_at", "2021-11-12 20:32:40.383075"]]
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:24
3:32:40 PM worker.1    |  7d8cc624f62cb516334c0637: ending
3:32:40 PM worker.1    |     (1.1ms)  COMMIT
3:32:40 PM worker.1    |    ↳ app/jobs/test_lock_job.rb:13
3:32:40 PM worker.1    |  2021-11-12T20:32:40.385Z 49646 TID-249e TestLockJob JID-7d8cc624f62cb516334c0637 INFO: done: 0.152 sec
```

**Comment by jmanian** [comment]
In conclusion, the original issue was due to Active Record caching (which must have been introduced or changed behavior between 4.2 and 5.2). I fixed it by using `uncached` within my advisory lock where I expected to get up to date query results.

I had a question above about whether pessimistic locking does anything to avoid cache issues. The general idea is that if you're working within a lock you probably want query results that are up to date as of the acquisition of the lock, rather than cached results. This will be true of the record that is locked, since it is (re)loaded to acquire the lock. But I did some testing and it's not true of other records.

Take for example:
```ruby
Widget.find_by(name: 'gear')

user.with_lock do
  # This will use the cached result from above, rather than a fresh query
  widget = Widget.find_by(name: 'gear')
end
```

Since row-level locking is only about ensuring integrity of that one row I think this is OK. In the case of an advisory lock it's more of a problem since the scope of the lock is defined by the application.

All of this is to say that I think we're good here, and I'll continue the conversation at ClosureTree/with_advisory_lock#52.

**Comment by ricardopacheco** [comment]
Hi folks!

`.uncached` not works for me (rails 6.1). But, when i create two block, like this:

```
ActiveRecord::Base.with_advisory_lock("post-create-#{fields[:user_id]}") do
  ActiveRecord::Base.transaction do
   ....
   user.save
   end
end
```

works! Before, i use ActiveRecord::Base.with_advisory_lock("post-create-#{fields[:user_id]}", transaction: true)

**Comment by jmanian** [comment]
@ricardopacheco I don't know if this is relevant for you, but to use a transactional advisory lock with this gem you need to explicitly have a transaction around the lock. If you use `transaction: true` and you're **not** already in a transaction then it has no effect:
```ruby
ActiveRecord::Base.with_advisory_lock("post-create-#{fields[:user_id]}", transaction: true) do
  # this lock does nothing because there's no transaction
end
```

```ruby
ActiveRecord::Base.transaction do
  ActiveRecord::Base.with_advisory_lock("post-create-#{fields[:user_id]}", transaction: true) do
    # the lock is held until the end of the transaction
  end
end
```

So in my case I fixed the caching by using `uncached` within that:
```ruby
ActiveRecord::Base.transaction do
  ActiveRecord::Base.with_advisory_lock("post-create-#{fields[:user_id]}", transaction: true) do
    ActiveRecord::Base.uncached do
      # the lock is held until the end of the transaction, and Rails won't use any caches
    end
  end
end
```

**Comment by ricardopacheco** [comment]
@jmanian thank you man, his was very enlightening to me!
