### ISSUE TITLE
with_lock erases saved_changes

### ISSUE THREAD

**Issue by heaven** [rails/rails#43645]
### Steps to reproduce
We have a set of before/after commit callbacks, one of them uses `with_lock`, which breaks the callback chain because callbacks executed after this one don't see the saved changes.

```ruby
before_commit do
  # ...
end

before_commit do
  self.with_lock do
    # ...
  end
end

after_commit do
  self.saved_changes # => nil
end
```

In the log I see this:
```
  TRANSACTION (0.3ms)  SAVEPOINT active_record_2
  Customer Load (0.5ms)  SELECT `customers`.* FROM `customers` WHERE `customers`.`deleted_at` IS NULL AND `customers`.`id` = 1 ORDER BY `customers`.`active` DESC, `customers`.`default` DESC, `customers`.`id` DESC LIMIT 1
  Order Update (0.5ms)  UPDATE `orders` SET `orders`.`status` = 1, `orders`.`updated_at` = '2021-11-15 12:01:51.858475' WHERE `orders`.`id` = 1
  Order Load (0.4ms)  SELECT `orders`.* FROM `orders` WHERE `orders`.`id` = 1 LIMIT 1 FOR UPDATE
  TRANSACTION (0.3ms)  RELEASE SAVEPOINT active_record_2

# after commit is called here
```

### Expected behavior
Saved changes should survive while we are in after/before save/commit callbacks.

### Actual behavior
Saved changes state is lost if one of the callbacks has called `with_lock`.

### System configuration
**Rails version**: 6.1.4.1

**Ruby version**: 2.7.4

**Comment by heaven** [comment]
A workaround was to replace `self.with_lock` with `self.class.where(id: self.id).first.with_lock`.

**Comment by jacobherrington** [comment]
Hey @heaven! Thanks for reporting an issue 😄 

I wasn't able to replicate this behavior in 6.1.4.1 or 7.0.0.alpha2, I'm adding a script to the end of this comment to share my reproduction attempt.

In case it matters (I don't think it should), I'm using Ruby 3.0.2 on macOS Big Sur.

Maybe you could run this script and report back if you have different results? Or perhaps there is some detail I'm missing in this script that would change the outcome?

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord"
  gem "sqlite3"
  gem "byebug"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :articles, force: true do |t|
    t.string :title
  end

  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Article < ActiveRecord::Base
  before_commit do
    update(title: "#{title}_before")
  end

  after_commit do
    # byebug
    saved_changes #=> { "title" => ["test", "test_before"] }
  end
end

class Post < ActiveRecord::Base
  before_commit do
    with_lock do
      update(title: "#{title}_before")
    end
  end

  after_commit do
    # byebug
    saved_changes #=> { "title" => ["test", "test_before"] }
  end
end

class BugTest < Minitest::Test
  # All assertions pass in 6.1.4.1 AND 7.0.0.alpha2
  def test_callbacks
    subject = Article.new(title: "test")
    subject.save!
    assert_equal({ "title" => ["test", "test_before"] }, subject.saved_changes)
    assert_equal "test_before", subject.title
  end

  def test_callbacks_with_lock
    subject = Post.new(title: "test")
    subject.save!
    assert_equal({ "title" => ["test", "test_before"] }, subject.saved_changes)
    assert_equal "test_before", subject.title
  end
end
```

**Comment by heaven** [comment]
Hi @jacobherrington, thank you for this work!

The thing is you are updating from within the `#with_lock` block:
```ruby
  before_commit do
    with_lock do
      update(title: "#{title}_before")
    end
  end
```

So if you do something like this:
```ruby
  @post.update(body: "test")
  
  before_commit do
    with_lock do
      update(title: "#{title}_before")
    end
  end

  after_commit do
    # here you will only the changed title
  end
```

The `after_commit` callback will only see changes to the `title`. And the case could be even more complicated when you have multiple `before_commit` callbacks and each uses `#with_lock`.

In my case, I was updating the record before as well. So I think the problem is not in the callbacks, it is in the `#with_lock` method itself, which erases the changes. Which works in most cases and raises an error if unsaved changes are present. But if you need to lock the record from the before/after commit callbacks that also erases the state and further callbacks see no changes.

This is probably an edge case but I use this practice of locking the record in the callbacks a lot, especially when working with payments. My opinion is, `#with_lock` should not reload the record like the regular `#reload` does but should probably keep the saved changes history.

**Comment by jacobherrington** [comment]
@heaven, thanks for the clarification. I can see how that behavior is different from what I was modeling.

Here is a script that I think models your point more accurately:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activerecord"
  gem "sqlite3"
  gem "byebug"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.string :body
  end

  create_table :comments, force: true do |t|
    t.string :title
    t.string :body
  end
end

class Post < ActiveRecord::Base
  before_commit do
    update(title: "#{title}_before")
  end

  after_commit do
    saved_changes
  end
end

class Comment < ActiveRecord::Base
  before_commit do
    with_lock do
      update(title: "#{title}_before")
    end
  end

  after_commit do
    saved_changes
  end
end

class BugTest < Minitest::Test
  def test_callbacks_when_another_column_is_updated
    subject = Post.create(title: "test")
    subject.update!(body: "content")
    assert_equal({ "title"=>["test_before", "test_before_before"] }, subject.saved_changes)
    assert_equal "test_before_before", subject.title
  end

  def test_callbacks_with_lock_when_another_column_is_updated
    subject = Comment.create(title: "test")
    subject.update!(body: "content")
    assert_equal({ "title"=>["test_before", "test_before_before"] }, subject.saved_changes)
    assert_equal "test_before_before", subject.title
  end
end
```

These assertions all pass as well. So I don't think this behavior is specific to `#with_lock`, it happens any place we update the record in a callback. We'd see a different result on the first assertion in each test if `with_lock` was the only thing at play here; the `Post` class doesn't use `with_lock` in its `before_commit` callback (at least, as far as I understand things).

However, if you were to drop a debugger into the `before_commit` callback during the `update!` call we'd see behaviors that feel relevant:

```ruby
class Post < ActiveRecord::Base
  before_commit do
    saved_changes #=> {"body"=>[nil, "content"]}
    update(title: "#{title}_before")
    saved_changes #=> {"title"=>["test_before", "test_before_before"]} # A new transaction, so this feels correct to me.
  end

  after_commit do
    saved_changes #=> {"title"=>["test_before", "test_before_before"]}
  end
end

class Comment < ActiveRecord::Base
  before_commit do
    saved_changes #=> {"body"=>[nil, "content"]}
    with_lock do
      saved_changes #=> {} # The behavior you're identifying! ⭐️
      # This is a little weird, but it does seem to be part of the intended behavior of `with_lock`
      update(title: "#{title}_before")
      saved_changes #=> {"title"=>["test_before", "test_before_before"]}
      # We've kicked this off with an `update!` but the changes from that `update!` have been lost.
    end
  end

  after_commit do
    saved_changes #=> {"title"=>["test_before", "test_before_before"]}
  end
end

```

I believe this is how I expect them to behave, but I think you're pointing out that we could keep track of the initial attributes that were changed when we called `update!(body: "content")`, correct?

For example, it'd be ideal in your case, to see something like this:
```ruby
def test_callbacks_with_lock_when_another_column_is_updated
    subject = Comment.create(title: "test")
    subject.update!(body: "content")
    assert_equal({ "body"=>[nil, "content"], "title"=>["test_before", "test_before_before"] }, subject.saved_changes)
    # We can see that both body and title were recently updated.
    ...
  end
```

I'm not sure I have a lot of authority to speak on how ActiveRecord *should* behave, but I think the way it works now makes more sense to me than what you're proposing.

In my thinking, `saved_changes` should only reflect changes within the current or most recent transaction; `with_lock` initiates a new transaction (I think), so it makes sense that `saved_changes` in that context would reflect only the changes taking place within that transaction. Do you disagree?

Perhaps another solution is to leave `saved_changes` alone but introduce some new method that allows us to see what changes occurred without respect to the callbacks? Something like `changes_excluding_callbacks`?

It might look like this:
```ruby
def test_callbacks_with_lock_when_another_column_is_updated
    subject = Comment.create(title: "test")
    subject.update!(body: "content")
    assert_equal({ "title"=>["test_before", "test_before_before"] }, subject.saved_changes)
    assert_equal({ "body"=>[nil, "content"] }, subject.changes_exlcuding_callbacks)
    assert_equal "test_before_before", subject.title
end
```

Something that I found which might already accomplish a piece of this is [attribute_before_last_save](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Dirty.html#method-i-attribute_before_last_save).

Going back to the test case:
```ruby
def test_callbacks_with_lock_when_another_column_is_updated
    subject = Comment.create(title: "test")
    subject.update!(body: "content")
    assert_equal({ "title"=>["test_before", "test_before_before"] }, subject.saved_changes)
    assert_equal(nil, subject.attribute_before_last_save(:body)) # Because we updated nil to "content"
    assert_equal "test_before_before", subject.title
end
```

Does all of this make sense, or have I misunderstood again? 😅
