### ISSUE TITLE
Don't know how to build task 'assets:precompile' during project setup

### ISSUE THREAD

**Issue by wojciech-rzepecki** [rails/rails#43658]
### Steps to reproduce

```sh
rails new project --edge --javascript esbuild --css bootstrap 
```

### Expected behavior
Should normally run assets:precompile 

### Actual behavior
```
Bundle complete! 15 Gemfile dependencies, 65 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  javascript:install:esbuild
rails aborted!
Don't know how to build task 'assets:precompile' (See the list of available tasks with `rails --tasks`)
/home/wojciech/project/Rakefile:6:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
       rails  turbo:install stimulus:install
rails aborted!
Don't know how to build task 'assets:precompile' (See the list of available tasks with `rails --tasks`)
/home/wojciech/project/Rakefile:6:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
       rails  css:install:bootstrap
rails aborted!
Don't know how to build task 'assets:precompile' (See the list of available tasks with `rails --tasks`)
/home/wojciech/project/Rakefile:6:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)

```

### System configuration
**Rails version**: 7.0.0.alpha2 at main@dea5603

**Ruby version**: 3.0.2

**Comment by ghiculescu** [comment]
Could you share the output of `rails --tasks` please?

**Comment by wojciech-rzepecki** [comment]
```bundle exec rails --tasks``` gives me
```
rails aborted!
Don't know how to build task 'assets:precompile' (See the list of available tasks with `rails --tasks`)
/home/wojciech/project/Rakefile:6:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

**Comment by ghiculescu** [comment]
Cool, I can replicate by doing the following:

- `gem uninstall rails`, all versions
- `gem install rails --prerelease`
- `rails --version` -> Rails 7.0.0.alpha2
- `rails new project --edge --javascript esbuild --css bootstrap`

The error is raised here https://github.com/rails/jsbundling-rails/blob/f6c6ccac51451fa580ce1d09c60a5ad61c44bf4f/lib/tasks/jsbundling/build.rake#L10

**Comment by ghiculescu** [comment]
The tasks are defined by `sprockets-rails` ([here](https://github.com/rails/sprockets-rails/blob/4d7dd0c28e4b60a27075382decb7f326ce7b23b1/lib/sprockets/rails/task.rb#L52)) but this app doesn't have `sprockets-rails` in its Gemfile.

They can also be defined by `propshaft` [here](https://github.com/rails/propshaft/blob/e739a3811e71d27a79946bd3961071d20fce2c4f/lib/propshaft/railtie.rb#L48) 

@dhh am I right in saying that for JS bundling and CSS bundling to work, the new app Gemfile *must* include either `sprockets-rails` or `propshaft`?

**Comment by ghiculescu** [comment]
For the record, `rails new project --javascript esbuild --css bootstrap` works fine with the above setup.

**Comment by dhh** [comment]
--edge will use the Rails 6 app generator to create a Rails 7 setup. Does not work. To use Rails 7, you must use Rails 7 gems to generate the skeleton.

**Comment by estiens** [comment]
This is still a problem. Uninstalled all versions of rails from ruby 3.0.3, installed rails 7.0.2

`rails new --skip-test --skip-asset-pipeline --javascript=esbuild --css=tailwind`

Don't know how to build task 'assets:precompile' from Rakefile

**Comment by ghiculescu** [comment]
@dhh in that case should `--skip-asset-pipeline` be ignored, if you include a `--javascript` or `--css` option?
