### ISSUE TITLE
'method_missing': undefined method 'assets' on rails s

### ISSUE THREAD

**Issue by wojciech-rzepecki** [rails/rails#43659]
### Steps to reproduce
```
rails new project --javascript esbuild --css bootstrap
```
in Gemfile change `gem "rails", "~> 7.0.0.alpha2"` to `gem "rails", github: "rails/rails", branch: "main"` then `bundle`

### Expected behavior
`rails s` should start normally

### Actual behavior
```
'method_missing': undefined method `assets'
<very long output>
Did you mean?  asset_host
```
it points to every line where `...config.assets...` is used like in 
```ruby
# environments/development.rb
config.assets.quiet = true
``` 
```ruby
# environments/production.rb
config.assets.compile = false
```
```ruby
# config/assets.rb
Rails.application.config.assets.version = "1.0"
```

### System configuration
**Rails version**: 7.0.0.alpha2

**Ruby version**: 3.0.2

**Comment by wojciech-rzepecki** [comment]
I have found workaround to this
```
mkdir project
cd project
cat >> Gemfile << EOF
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", github: "rails/rails", branch: "main"
EOF
bundle
bundle exec rails new . -j esbuild --css bootstrap
```
allow overwrite `Gemfile` when prompt asks, next need replace again `gem "rails", "~> 7.0.0.alpha2"` with `gem "rails", github: "rails/rails", branch: "main"` in `Gemfile` and make `bundle` now error not appears :+1:

**Comment by wojciech-rzepecki** [comment]
as I see there is difference in generated Gemfile between `7.0.0.alpha2` and `master` branch, that in Gemfile from `master` branch generator there is `sprockets-rails` so this is probably the solution

**Comment by qichunren** [comment]
Yes, config.assets method is provided by prockets-rails gem.

**Comment by ghiculescu** [comment]
> as I see there is difference in generated Gemfile between `7.0.0.alpha2` and `master` branch

Yes that's right. I think that's what DHH was hinting at in https://github.com/rails/rails/issues/43658

Hopefully an alpha3 release comes soon to resolve this.
