### ISSUE TITLE
Action Text attachments broken in rails/main (environment/service agnostic)

### ISSUE THREAD

**Issue by strobilomyces** [rails/rails#43667]
### Steps to reproduce

- Create new app from rails/main (on or after 193289d)
- Install Action Text and throw it on a model.
- Try to attach anything.

### Expected behavior
File is attached.

### Actual behavior
File is not attached.

```ruby

Started POST "/rails/active_storage/direct_uploads" for 127.0.0.1 at 2021-11-17 20:52:10 +0100
Processing by ActiveStorage::DirectUploadsController#create as JSON
  Parameters: {"blob"=>{"filename"=>"file.jpg", "content_type"=>"image/jpeg", "byte_size"=>27906, "checksum"=>"CcwnZBNhychA4/2SYVHjbg=="}, "direct_upload"=>{"blob"=>{"filename"=>"antonino_libro_opt.jpg", "content_type"=>"image/jpeg", "byte_size"=>27906, "checksum"=>"CcwnZBNhychA4/2SYVHjbg=="}}}
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms | Allocations: 1066)
  
ActiveStorage::InvalidDirectUploadTokenError (ActiveStorage::InvalidDirectUploadTokenError):
  
rails (193289dbbe14) activestorage/lib/active_storage/direct_upload_token.rb:16:in `verify_direct_upload_token'
rails (193289dbbe14) activestorage/app/controllers/active_storage/direct_uploads_controller.rb:20:in `verified_service_name'
rails (193289dbbe14) activestorage/app/controllers/active_storage/direct_uploads_controller.rb:10:in `create'
rails (193289dbbe14) actionpack/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
rails (193289dbbe14) actionpack/lib/abstract_controller/base.rb:215:in `process_action'
rails (193289dbbe14) actionpack/lib/action_controller/metal/rendering.rb:53:in `process_action'
rails (193289dbbe14) actionpack/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
rails (193289dbbe14) activesupport/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
rails (193289dbbe14) actiontext/lib/action_text/rendering.rb:20:in `with_renderer'
rails (193289dbbe14) actiontext/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
rails (193289dbbe14) activesupport/lib/active_support/callbacks.rb:127:in `instance_exec'
rails (193289dbbe14) activesupport/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
rails (193289dbbe14) activesupport/lib/active_support/callbacks.rb:138:in `run_callbacks'
rails (193289dbbe14) actionpack/lib/abstract_controller/callbacks.rb:233:in `process_action'
rails (193289dbbe14) actionpack/lib/action_controller/metal/rescue.rb:22:in `process_action'
rails (193289dbbe14) actionpack/lib/action_controller/metal/instrumentation.rb:65:in `block in process_action'
rails (193289dbbe14) activesupport/lib/active_support/notifications.rb:207:in `block in instrument'
rails (193289dbbe14) activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
rails (193289dbbe14) activesupport/lib/active_support/notifications.rb:207:in `instrument'
rails (193289dbbe14) actionpack/lib/action_controller/metal/instrumentation.rb:64:in `process_action'
rails (193289dbbe14) actionpack/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
rails (193289dbbe14) activerecord/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
rails (193289dbbe14) actionpack/lib/abstract_controller/base.rb:152:in `process'
rails (193289dbbe14) actionview/lib/action_view/rendering.rb:39:in `process'
rails (193289dbbe14) actionpack/lib/action_controller/metal/live.rb:266:in `block (2 levels) in process'
rails (193289dbbe14) activesupport/lib/active_support/concurrency/share_lock.rb:162:in `sharing'
rails (193289dbbe14) activesupport/lib/active_support/dependencies/interlock.rb:37:in `running'
rails (193289dbbe14) actionpack/lib/action_controller/metal/live.rb:258:in `block in process'
rails (193289dbbe14) actionpack/lib/action_controller/metal/live.rb:343:in `block in new_controller_thread'

```

### System configuration
**Rails version**: rails/main (currently at b4cc85c49c7af682a935e41c9d9798070584a8f8)

**Ruby version**: 3.0.2

### Fix
Rolling back to the previous commit, a92db0d533b30f7d58dc9b367cc8fe7ffa968e30, fixes the issue.

**Comment by ghiculescu** [comment]
Hmm, I would have thought that https://github.com/rails/rails/pull/43650 fixes this.

@DmitryTsepelev or @gmcgibbon any chance you could have a look here?

**Comment by strobilomyces** [comment]
Just tried it. Same result.

**Comment by gmcgibbon** [comment]
Could it be because you are using release versions of JS packages? The changes on main to Active Storage and Action Text should fix this.

**Comment by strobilomyces** [comment]
Thanks for looking into this. I just tried setting both to rails/main in my package.json (e.g. "@rails/actioncable": "https://gitpkg.now.sh/rails/rails/actioncable?main"). No change.

**Comment by gmcgibbon** [comment]
> No change.

Node package resolution is a bit tricky compared to rubygems. Since the packages aren't published yet, you need to `yarn link` them locally to override the dependency `@rails/actiontext` has on `@rails/activestorage` (otherwise it will use activestorage from npm). You can verify this by inspecting your `node_modules`.

This isn't ideal seeing how git sourcing is impossible on import maps, and linking packages locally is a hassle. I think the issue here is less related to 193289d and more related to JS package management.

**Comment by strobilomyces** [comment]
Thanks for the guidance. It took me a while (`yarn link` was new to me), but I was finally able to link the two; attachments worked again, as you thought.

**Comment by ghiculescu** [comment]
Closing as this seems to be resolved. Thanks for the help @gmcgibbon

**Comment by strobilomyces** [comment]
Sorry to be a pain--and forgive my ignorance here--but is this really resolved without the user having to monkey patch things like described above? I think I get that it will resolve itself when actiontext changes the activestorage dependency away from alpha1, but until then? Thanks.

**Comment by ghiculescu** [comment]
Oh sorry, my understanding is it will resolve itself when Rails 7 fully ships.

You're right it's not resolved if you are trying to work against rails/main now, but there's no other changes required to fix it - we just need to ship 7 (which I think will happen fairly soon). And there is a workaround that works in the interim.

**Comment by strobilomyces** [comment]
Gotcha. Thanks for the clarification :)
