### ISSUE TITLE
Rails 7, Ruby 3.1, Bootstrap The asset "application.css" is not present in the asset pipeline

### ISSUE THREAD

**Issue by nleo** [rails/rails#43677]
I generate new rails app from github.com/rails/rails/ with this guide https://gist.github.com/vmcilwain/b44100e32165c82793d4df8691cee4e4

bundle exec rails new . -d postgresql -T --edge --css bootstrap

![image](https://user-images.githubusercontent.com/800970/142712446-bd496e34-3bfb-49bb-9858-2f2c2d53cd89.png)

There are some errors with net/smtp. But I add `gem 'net-smtp'` and run tasks manually

There are some errors on `rails  css:install:bootstrap`

![image](https://user-images.githubusercontent.com/800970/142712478-0af20c38-a556-43b4-bb1b-9519f4029c3b.png)

I generated action: `bin/rails g controller home index` and got error: 

Sprockets::Rails::Helper::AssetNotFound in Home#index The asset "application.css" is not present in the asset pipeline.
![image](https://user-images.githubusercontent.com/800970/142712512-5daf9303-aa20-4c41-83e1-ef6f06941662.png)

I change to application.bootstrap `<%= stylesheet_link_tag "application.bootstrap", "data-turbo-track": "reload" %>`

Got error: `cannot load such file -- sassc`

Uncomment `gem "sassc-rails", "~> 2.1"` in Gemfile

Got error `SassC::SyntaxError in Home#index`
```
Error: File to import not found or unreadable: bootstrap/scss/bootstrap.
        on line 1:1 of app/assets/stylesheets/application.bootstrap.scss
>> @import 'bootstrap/scss/bootstrap';
```
Decided to report a issue and return to it after some time.

Rails version: 7.0.0.alpha2
Ruby version: ruby 3.1.0preview1 (2021-11-09 master 5a3b2e6141) [x86_64-linux]

**Comment by edwinlunando** [comment]
Have you run `yarn build:css --watch`. Rails 7 need this process to compile the assets. I think it is not documented yet.

**Comment by nleo** [comment]
Didn't try `yarn build:css --watch`

I switched to `bundle exec rails new . -d postgresql -T --edge --css tailwind`. With tailwind works ok.

**Comment by nleo** [comment]
I think issue with https://github.com/rails/cssbundling-rails with bootstrap support

**Comment by ro31337** [comment]
`yarn build:css --watch` says `error Command "build:css" not found.`

**Comment by dhh** [comment]
With latest cssbundling-rails, `yarn build:css` is automatically run once when first generating the app. Ensuring you won't get this missing file error.

But also, you shouldn't generate a Rails 7 app using a Rails 6 rails command.

**Comment by owen2345** [comment]
> Used commands from here: https://github.com/rails/cssbundling-rails/blob/3f359b0900712654fe4139eddbfcd8cc1559a479/lib/install/sass/install.rb

> yarn add sass
> npm set-script build:css "sass ./app/assets/stylesheets/application.sass.scss ./app/assets/builds/application.css --no-source-map"



This is strange. Does rails require `npm` too aside from `yarn`?

**Comment by owen2345** [comment]
Confirmed: When using `esbuild` or similar, you need to install yarn and npm
```
RUN apt install yarn -y
RUN apt install npm -y
```
Because of this: https://github.com/rails/cssbundling-rails/blob/3f359b0900712654fe4139eddbfcd8cc1559a479/lib/install/sass/install.rb

**Comment by hamzaasif4981-sudo** [comment]
> With latest cssbundling-rails, `yarn build:css` is automatically run once when first generating the app. Ensuring you won't get this missing file error.
> 
> But also, you shouldn't generate a Rails 7 app using a Rails 6 rails command.

then how should we generate the app in rails 7. i am using cssbundling but getting the error.
`The asset "application.css" is not present in the asset pipeline.
`

**Comment by la-ruby** [comment]
> then how should we generate the app in rails 7

personally I use `bundle exec railties/exe/rails new`
like you see here: https://github.com/la-ruby/create-rails-app/blob/main/create-rails-app

**Comment by owen2345** [comment]
Btw: here i created a repo wich helps you to create Rails apps in a couple of secods (dockerized)
https://github.com/owen2345/create_rails_app

**Comment by bbugh** [comment]
If anyone else ends up here trying to track down this issue for bootstrap, tailwind, or esbuild, there's two things to note.

1\. When Rails is set up, [if your npm is too old](https://github.com/rails/cssbundling-rails/issues/56#issuecomment-1013841128) (`npm -v < 7.1`), rails will not add the two scripts to your `package.json`, and will output an easy-to-miss message, which is also has a bug and does not output the correct message. The instructions tell you to

> Add "scripts": { "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css" } to your package.json

but if you've set up both `tailwind` and `esbuild` with `-j esbuild -c tailwind`, this message is incomplete. You need to add **two** scripts to your `package.json`:

```
"scripts": {
  "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
  "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css"
}
```

2\. This message also doesn't tell you that you need to run `yarn build:css` afterwards in order for things to work, so you need to do that at least once. However, there is a generated `Procfile.dev` so either run those commands individually, or always run Rails in development using `foreman start -F Procfile.dev` instead of `rails s`. Then you don't need to run the `yarn build:css` on its own.

**Comment by rdetert** [comment]
Also, if you are using nvm, then make sure `yarn` and `esbuild` are installed

**Comment by webzorg** [comment]
I wouldn't name the file `application.bootstrap.scss` and then require `application_link_tag 'application'`, it's confusing on where the file is coming from, after looking at package.json scripts yes it makes sense but lot of upgrades will end in confusion

**Comment by undu82** [comment]
I had the same issue, but based on this tutorial, https://www.bootrails.com/blog/rails-7-bootstrap-5-tutorial/, I figure out that the problem was the version of npm and node that I was using. 

After upgrading them, everything worked fine.

**Comment by iC-3PU** [comment]
> I had the same issue, but based on this tutorial, https://www.bootrails.com/blog/rails-7-bootstrap-5-tutorial/, I figure out that the problem was the version of npm and node that I was using.
> 
> After upgrading them, everything worked fine.

Did you have an existing project you were working on with the older npm? And if you did, after upgrading, did everything work fine?

**Comment by JohnSmall** [comment]
This problem has resurfaced if you're using Node v21.0.0, the problem occurs when creating a new app. You'll get this error during the creation of the app `Node.js v21.0.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  Add build:css:prefix script
         run    npm pkg set scripts.build:css:prefix="postcss ./app/assets/builds/application.css --use=autoprefixer --output=./app/assets/builds/application.css" from "."
         run    yarn build:css:prefix from "."
yarn run v1.22.19
$ postcss ./app/assets/builds/application.css --use=autoprefixer --output=./app/assets/builds/application.css
Input Error: You must pass a valid list of files to parse
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  Add build:css script
         run    npm pkg set scripts.build:css="yarn build:css:compile && yarn build:css:prefix" from "."
         run    yarn build:css from "."
yarn run v1.22.19
$ yarn build:css:compile && yarn build:css:prefix
$ sass ./app/assets/stylesheets/application.bootstrap.scss:./app/assets/builds/application.css --no-source-map --load-path=node_modules
/workspaces/rails-7-stimulus/check_bootstrap/node_modules/sass/sass.dart.js:116832
    if (ua.indexOf("DumpRenderTree") >= 0) return hooks;
           ^

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at /workspaces/rails-7-stimulus/check_bootstrap/node_modules/sass/sass.dart.js:116832:12`

Which then leads to the error 'application.css' cannot be found. 

If you switch to Node 18 then it works.

**Comment by a-ta-ta** [comment]
try switching to another framework
why use Rails if it doesn't work from scratch?

**Comment by devsparkles** [comment]
> try switching to another framework why use Rails if it doesn't work from scratch?

:) 

funny I am reading this trying to get rid of that
The asset "tailwind.css" is not present in the asset pipeline.
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %> <- culprit 

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">

I will find a way. 
It works in dev not in prod.

**Comment by Pauloparakleto** [comment]
Running `rails new --css=bootstrap` as option **without** `yarn`, will raise this error. Tested in `rails 7.1.3.4`. After make sure yarn was installed, I run `rails new --css=bootstrap` again avoiding overwrite old files and works. The rails new command still works. You need yarn in this case.
