### ISSUE TITLE
Some paths are wrong when scaffold with `--model-name` option

### ISSUE THREAD

**Issue by kenzo-tanaka** [rails/rails#43678]
Hi👋
First of all thank you for the very helpful framework!

### Steps to reproduce

Generate a namespace controller with `--model-name` option. 

```shell
$ rails g model article title:string
$ rails db:migrate
$ rails g scaffold_controller admin/articles --model-name=article
```

This is a sample code.
https://github.com/kenzo-tanaka/rails_sandbox/pull/16

### Expected behavior

`app/views/admin/articles/show.html.erb`

```erb
<%= link_to 'Edit', edit_admin_article_path(@article) %>
```

`app/views/admin/products/edit.html.erb`

```erb
<%= link_to 'Show', [:admin, @product] %>
```

### Actual behavior

The scaffold command generates not namespaced path like below:

`app/views/admin/articles/show.html.erb`
```erb
<%= link_to 'Edit', edit_article_path(@article) %>
```

`app/views/admin/products/edit.html.erb`
```erb
<%= link_to 'Show', @product %>
```

Maybe is this because of these lines?

https://github.com/rails/rails/blob/f47204802ae2e212a238276492584b7607c513f1/railties/lib/rails/generators/erb/scaffold/templates/show.html.erb.tt#L6

https://github.com/rails/rails/blob/f47204802ae2e212a238276492584b7607c513f1/railties/lib/rails/generators/erb/scaffold/templates/edit.html.erb.tt#L8

### System configuration
**Rails version**: 6.1.4
**Ruby version**: 2.6.3p62

I'm sorry if I misunderstood something about this behaviour🙏

**Comment by hahmed** [comment]
@kenzo-tanaka thanks for taking the time to report this issue, seems like it's related to https://github.com/rails/rails/pull/43611 👍

**Comment by kenzo-tanaka** [comment]
@hahmed 
Certainly, this PR is going to solve the issue! 
Thanks for letting me know! 😄
