### ISSUE TITLE
Encrypted attributes causing presence validation test error

### ISSUE THREAD

**Issue by gardnerapp** [rails/rails#43699]
Rails 7.0.0alpha2

Model: 
```
  encrypts :email, deterministic: true
```

Test: 
```
test "Email must be present " do
    @user.email = "  "
    assert_not @user.valid?
  end
```

Expected: 
Passing Test 

Output
E

Error:
'''
UserTest#test_email_must_be_present:
ActiveRecord::Encryption::Errors::Decryption: ActiveRecord::Encryption::Errors::Decryption
    test/models/user_test.rb:18:in `block (2 levels) in <class:UserTest>'
'''

**Comment by jacobherrington** [comment]
Hey @gardnerapp!

I wrote a little reproduction script for this (below), but I'm not sure I'm seeing the same results that you're seeing.

Things on my end seem to work as expected. I'm on the main branch and using Ruby `2.7.3` for this script.

I wasn't sure if you had a presence validation on your model, so I wrote two examples. The model with validation returns `false` when sent `#valid?` and the attribute is a blank string (as we would expect). The model without validation saves as expected. In fact, when I query for the record, this is what I see:
```ruby
Dog.first #=> #<Dog id: 1, favorite_toy: "   ">
```

Both models use an encrypted string attribute with `deterministic` set to true in their declarations. So, I think it seems like each piece of this is working as expected.

If you've got some different conditions in your app, maybe I can add those to this script to show how Active Record Encryption is misbehaving. Do you think there is some condition that is true in your app but missed in my script?

You could also try running this script and checking to see if you get a different result than I am getting.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "jsonb_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Encryption.configure \
      primary_key: "nYlllafgBdhQ7Vn37dlWAoqfDbTPl4Fl",
      deterministic_key: "CK7x2oUEeu06bKehhKGiKYAHoytPaOPg",
      key_derivation_salt: "Fol1dR03ZXnL8k4hEUYj7IMr0UlgOMHC"

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :email
  end

  create_table :dogs, force: true do |t|
    t.string :favorite_toy
  end
end

class User < ActiveRecord::Base
  validates :email, presence: true
  encrypts :email, deterministic: true
end

class Dog < ActiveRecord::Base
  encrypts :favorite_toy, deterministic: true
end

class BugTest < Minitest::Test
  def test_encrypted_string_with_validations
    user = User.new(email: "   ")

    assert user.valid? # Fails, as expected

    user.save! # Raises ActiveRecord::RecordInvalid Exception: Validation failed: Email can't be blank
  end

  def test_encrypted_string_without_validations
    spot = Dog.new(favorite_toy: "   ")

    assert spot.valid? # Passes, as expected

    spot.save! # Does not raise
  end
end
```

**Comment by gardnerapp** [comment]
The only difference that I could think of off the top of my head is that I'm using Ruby 3.0.2,. I'm very new to this, how would I go about running this script?

I also tried writing this method: 
```
 def generate_token
    self.mobile_token = User.new_token
    update_attribute :mobile_digest, User.digest(mobile_token)
  end
```
and testing it with 
```
 test 'Generates token' do
    assert_nil @user.mobile_token
    assert_nil @user.mobile_digest
    @user.generate_token
    assert_not_nil @user.mobile_token
    assert_not_nil @user.mobile_digest
  end
```
I got the same error as with my validation test.

**Comment by hahmed** [comment]
@gardnerapp I'm also not seeing the error, I tested this out on ruby 3.0.2

Here is my script (slightly simplified version from @jacobherrington code -- thank you!), if there is a validation check the user model cannot be saved.

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: "encryption_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Encryption.configure \
      primary_key: "nYlllafgBdhQ7Vn37dlWAoqfDbTPl4Fl",
      deterministic_key: "CK7x2oUEeu06bKehhKGiKYAHoytPaOPg",
      key_derivation_salt: "Fol1dR03ZXnL8k4hEUYj7IMr0UlgOMHC"

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :email
  end
end

class User < ActiveRecord::Base
  # validates :email, presence: true
  encrypts :email, deterministic: true
end

class BugTest < Minitest::Test
  def test_encrypted_string
    user = User.new(email: " ")
    assert user.valid?
    assert user.save
  end
end
```

To run this script create a file somewhere on your machine and call it using `ruby your_file_name.rb` and copy the content above into that file, I have a rails_issues folder on my machine and I usually name them something like `issue_43699.rb`.

Could you upload a fresh rails app with your model (or a script using the bug report template), and a test to show it failing, that would really help to help track the issue.

I'm going to go ahead and close this issue for now, but feel free to continue the discussion (and post any further code that could be of help).

Thanks for reporting this issue!
