### ISSUE TITLE
Autoloading fails when using debug

### ISSUE THREAD

**Issue by brasic** [rails/rails#43691]
Hello!  I've been testing the wonderful [debug](https://github.com/ruby/debug) gem with the GitHub monolith.  I noticed an issue using it with autoloading that makes me concerned it's not fully compatible with zeitwerk: autoloading some constants fail inside a debugger session when they do not in a normal context.  This looks similar to how byebug fails with zeitwerk, see https://github.com/fxn/zeitwerk/issues/31#issuecomment-479996317 and https://github.com/deivid-rodriguez/byebug/issues/564 although I imagine it might be a different underlying cause.

It's difficult to use the bug report tempate to explain this issue so I've opened https://github.com/brasic/rails-debug-bug-report to demonstrate the issue.

/cc @fxn @ko1 @jhawthorn 

### Steps to reproduce

1. Start a new rails app on main (`bundle exec railties/exe/rails new ../myapp --edge --dev`)
2. Add these three files in `app/models`: https://github.com/brasic/rails-debug-bug-report/commit/7b6485629539e350ef9ddd69a78a74fc71afcb95
3. open a debugger session with `bin/rails runner debugger`
4. Reference `Git::Ref::Collection` in the debugger by typing it.
5. (Optional) verify that the constant loads correctly in a normal console.

In case something happens to my test repo, here are the test files:

```
$ tree git/
git/
├── ref
│   ├── collection
│   │   └── pagination.rb
│   └── collection.rb
└── ref.rb

$ cat git/ref.rb
# frozen_string_literal: true

module Git
  class Ref
  end
end
$ cat git/ref/collection.rb
# frozen_string_literal: true

class Git::Ref::Collection
end
$ cat git/ref/collection/pagination.rb
# frozen_string_literal: true

module Git::Ref::Collection::Pagination
end
```

### Expected behavior

All constants that can autoload outside a debugger session also load within one.  In particular referencing `Git::Ref::Collection` in the above example when it is not loaded should autoload it.

### Actual behavior

Referencing `Git::Ref::Collection` inside a debugger session triggers `uninitialized constant Git::Ref::Collection`, although the same behavior outside a debugger session works fine.

### Additional details

This repro was extracted from real files in the github monolith.  In case it helps, here are the zeitwerk debug logs emitted when debug and an IRB session attempt to load this constant:

debug (started from IRB):

    (rdbg) Git::Ref::Collection
    Zeitwerk@rails.main: module Git autovivified from directory app/models/git
    Zeitwerk@rails.main: autoload set for Git::Ref, to be autovivified from app/models/git/ref
    Zeitwerk@rails.main: earlier autoload for Git::Ref discarded, it is actually an explicit namespace defined in app/models/git/ref.rb
    Zeitwerk@rails.main: autoload set for Git::Ref, to be loaded from app/models/git/ref.rb
    Zeitwerk@rails.main: constant Git::Ref loaded from file app/models/git/ref.rb
    eval error: uninitialized constant Git::Ref::Collection
      (rdbg)(irb):1: in `<main>'

IRB: (started using `bin/rails console`):

    irb(main):001:0> Git::Ref::Collection
    Zeitwerk@rails.main: module Git autovivified from directory app/models/git
    Zeitwerk@rails.main: autoload set for Git::Ref, to be autovivified from app/models/git/ref
    Zeitwerk@rails.main: earlier autoload for Git::Ref discarded, it is actually an explicit namespace defined in app/models/git/ref.rb
    Zeitwerk@rails.main: autoload set for Git::Ref, to be loaded from app/models/git/ref.rb
    Zeitwerk@rails.main: autoload set for Git::Ref::Collection, to be autovivified from app/models/git/ref/collection
    Zeitwerk@rails.main: earlier autoload for Git::Ref::Collection discarded, it is actually an explicit namespace defined in app/models/git/ref/collection.rb
    Zeitwerk@rails.main: autoload set for Git::Ref::Collection, to be loaded from app/models/git/ref/collection.rb
    Zeitwerk@rails.main: constant Git::Ref loaded from file app/models/git/ref.rb
    Zeitwerk@rails.main: autoload set for Git::Ref::Collection::Pagination, to be loaded from app/models/git/ref/collection/pagination.rb
    Zeitwerk@rails.main: constant Git::Ref::Collection loaded from file app/models/git/ref/collection.rb
    => Git::Ref::Collection

### System configuration
**Rails version**: tested on rails/rails@6e1694275007b94b8112455ac53e8a345938376e, rails/rails@6e83d065ae3722e384d005adf3d4a01487fb89fd

**Ruby version**: tested on `3.0.2p107`, `3.0.3p143 (2021-10-09 revision fe6d90fd66)`

**Comment by fxn** [comment]
This seems unrelated to Rails. I reported it in `ruby/debug`.
