### ISSUE TITLE
First class support for rspec

### ISSUE THREAD

**Issue by eadz** [rails/rails#43708]
### Steps to reproduce

When starting a new rails app you have lots of options for different databases, javascript libs, etc, but there is no `--rspec` option. 

Rspec is well supported, and if we're willing to support Oracle SQL server ( no offense ) why can't we support `rspec` as an option when creating a new rails app? The `rspec-rails`  gem seems to be integrated well and highly tested. 

### Expected behavior

There should be a `--rspec` option

### Actual behavior

There is no `--rspec` option

### System configuration
**Rails version**:
7-pre
**Ruby version**:
3

**Comment by matthewd** [comment]
This is interesting to revisit in the context of our desire to make the initial app generation more adaptable for people's needs.

Oracle only needs us to know the right gem name, and we then ship a matching template `database.yml` (which obviously changes very rarely, and mostly from our needs rather than the adapter's). 

Clearly we can't ship RSpec templates: they differ across RSpec versions, and vary based on RSpec changes. 

I'm curious about how you see it working, technically, but we can figure that out in the PR.

**Comment by eadz** [comment]
I imagine the option would install the `rspec-rails` gem then run `rspec:install`.

**Comment by rafaelfranca** [comment]
This is not an issue though, so I recommend moving this to the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.

**Comment by rafaelfranca** [comment]
Or by proposing a PR for it as well if you are confident you can implement it with current information.

**Comment by eadz** [comment]
The issue is that there is no `--rspec` option for `rails new` but there should be. 

Would a PR be accepted? It would likely be a group effort, but I want to check that this is something rails-core wants?

**Comment by rafaelfranca** [comment]
Like @matthewd said:

> This is interesting to revisit in the context of our desire to make the initial app generation more adaptable for people's needs.
> I'm curious about how you see it working, technically, but we can figure that out in the PR.

We can't promise the PR will be accepted, but PRs it is easier to have a conversation over code than "proposal".

**Comment by JonRowe** [comment]
> Oracle only needs us to know the right gem name, and we then ship a matching template database.yml (which obviously changes very rarely, and mostly from our needs rather than the adapter's).
>
> Clearly we can't ship RSpec templates: they differ across RSpec versions, and vary based on RSpec changes.

FWIW `rspec-rails` includes a Rails generator, so a possible implementation would be load the latest version of `rspec-rails` into the gem file then invoke the existing `rspec:install` generator.
