### ISSUE TITLE
after_rollback hooks not triggered on ActiveRecord::NotNullViolation/RecordNotUnique

### ISSUE THREAD

**Issue by stripedpumpkin** [rails/rails#43721]
### Steps to reproduce

Using:
```ruby
gem "activerecord", "= 6.1.4.1"
```
An error in an `after_update` hook is properly triggering a rollback and the `after_rollback` hooks. But if the error happens while hitting the DB, say an `ActiveRecord::NotNullViolation` or `ActiveRecord::RecordNotUnique` the transaction is properly rolled back, but the `after_rollback` hooks are never called.

Is it the expected behavior ? If it is, why are the after_rollback hooks not triggered in these cases ? If it is not, here is a script that reproduces the issue:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "= 6.1.4.1"
  gem "sqlite3"
  gem "byebug"
end

require "active_record"
require "minitest/autorun"
require "logger"
require "byebug"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter: "sqlite3",
  database: ":memory:"
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true do |t|
    t.string :title, null: false
    t.string :isbn, null: false, index: { unique: true }
  end

  create_table :newspapers, force: true do |t|
    t.string :name, null: false
  end
end

##########################
# We will pretend to be logging
# in after rollback hooks
# This class is just helping keeping
# track of whether the hooks
# are called or not
class FakeLogger
  def self.clean_up
    @@logger = nil
  end

  def self.error(what_to_say)
    @@logger ||= FakeLogger.new
    @@logger.error what_to_say
  end

  def self.error_logs
    @@logger ||= FakeLogger.new
    @@logger.error_logs
  end

  def initialize
    @error_logs = []
  end

  def error(what_to_say)
    @error_logs << what_to_say
  end

  attr_reader :error_logs
end
############################

class Book < ActiveRecord::Base
  after_rollback :notify_rollback

  private

  def notify_rollback
    FakeLogger.error "Book #{id} transaction has been rolled back"
  end
end

class Newspaper < ActiveRecord::Base
  class NewspaperRefusesToBeUpdated < RuntimeError; end

  after_update :break_update
  after_rollback :notify_rollback

  private

  def break_update
    raise NewspaperRefusesToBeUpdated, 'Not letting myself be updated'
  end

  def notify_rollback
    FakeLogger.error "Newspaper #{id} transaction has been rolled back"
  end
end

class BugTest < Minitest::Test
  SOME_ISBN = '9780394607269'

  def setup
    super
    Book.destroy_all
    FakeLogger.clean_up
  end

  def test_after_rollback_is_called_on_after_update_error
    times = Newspaper.create! name: 'Times'

    assert_raises Newspaper::NewspaperRefusesToBeUpdated do
      times.update! name: 'The New York Times'
    end

    times.reload

    assert_equal(
      'Times',
      times.name
    )

    assert_equal(
      1,
      FakeLogger.error_logs.size
    )

    assert_equal(
      "Newspaper #{times.id} transaction has been rolled back",
      FakeLogger.error_logs.first
    )
  end

  def test_after_rollback_is_called_on_not_null_violation
    book = Book.create!(
      title: 'Das Kapital',
      isbn: SOME_ISBN
    )

    assert_raises ActiveRecord::NotNullViolation do
      book.update! title: nil
    end

    book.reload

    assert_equal(
      'Das Kapital',
      book.title
    )

    # Expected 1 but actually 0
    assert_equal(
      1,
      FakeLogger.error_logs.size
    )

    # Message we would expect to see in logs
    assert_equal(
      "Book #{book.id} transaction has been rolled back",
      FakeLogger.error_logs.first
    )
  end


  def test_after_rollback_is_called_on_not_unique_violation
    Book.create!(
      title: 'Das Kapital',
      isbn: SOME_ISBN
    )

    other_book = Book.create!(
      title: 'Das Kapital. Kritik der politischen Ökonomie',
      isbn: '123'
    )

    assert_raises ActiveRecord::RecordNotUnique do
      other_book.update! isbn: SOME_ISBN
    end

    other_book.reload

    assert_equal(
      '123',
      other_book.isbn
    )

    # Expected 1 but actually 0
    assert_equal(
      1,
      FakeLogger.error_logs.size
    )

    # Message we would expect to see in logs
    assert_equal(
      "Book #{other_book.id} transaction has been rolled back",
      FakeLogger.error_logs.first
    )
  end
end

```

### Expected behavior
I would expect after_rollback hooks to be called on `ActiveRecord::NotNullViolation` or `ActiveRecord::RecordNotUnique`, since the transactions are indeed being rolled back.

### Actual behavior
`after_rollback` hooks are not being called on `ActiveRecord::NotNullViolation` or `ActiveRecord::RecordNotUnique`.

### System configuration
**Rails version**: `6.1.4.1`

**Ruby version**: reproduced with `2.7.0` and `2.6.6`

**Comment by kstevens715** [comment]
Line 913 in `Persistence` raises an error (from further down in the stack) and `@_trigger_update_callback` never gets set to `true`:

https://github.com/rails/rails/blob/90357af08048ef5076730505f6e7b14a81f33d0c/activerecord/lib/active_record/persistence.rb#L906-L915

This `rollback_records` method does get called, but `record.trigger_transactional_callbacks?` is `false` because  `@_trigger_update_callback` was never set to `true` as shown above. So `rolledback!` is finally called with `should_run_callbacks: false`.

https://github.com/rails/rails/blob/90357af08048ef5076730505f6e7b14a81f33d0c/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L126-L140

It makes sense that we wouldn't want `after_update` callbacks to be executed in this case. But `after_rollback` makes sense to me. It looks like the rollback callbacks used to happen all the time, then the following config option was added and that's when the callbacks became conditional in commit b11b1e868a89319b8523c5f7b0da4c130ee42992:

`config.active_record.errors_in_transactional_callbacks`

Then, in Rails 5.1 that config option was removed in commit 8029f779b8a1dd9848fee0b7967c2e0849bf6e07, but there's still the vestigial conditional before the callbacks are run from the original feature.

My next step would be to determine if more of that original feature still needs to be removed or if its now being relied on for another purpose.

**Comment by kstevens715** [comment]
Here's the beginning of a fix that further shows the problem: https://github.com/rails/rails/compare/main...kstevens715:fix-rollback?expand=1

**Comment by matthewd** [comment]
I may be misreading, but the described behaviour sounds correct to me: `after_rollback` is an opportunity to undo something "prematurely" done on the belief that the record had already been saved successfully -- that only becomes true after the record claims to have been saved. (That is, it's not "on failure to save" -- it's "on a previously-completed save vanishing from the timeline".)

**Comment by stripedpumpkin** [comment]
I am not sure I understand what you are saying. Let us consider the update case for simplicity.
An after_commit hook would be run if and only if the update has been persisted, "immediately after the transaction is committed". Similarly an after_rollback are called on a saved record if and only if the transaction has been rolled back (hence the change has not been persisted, "immediately after the transaction is rolled back"). (cf. https://github.com/rails/rails/blob/2459c20afb508c987347f52148210d874a9af4fa/activerecord/lib/active_record/transactions.rb#L175)

If so, it seems surprising to observe a db rollback and not trigger the after_rollback hook. In the same way that observing a db commit and not executing the after_commit hook would be surprising as well.

I am sorry if I am missing something, just trying to make sure I understand the expected behavior properly.

**Comment by matthewd** [comment]
> Similarly an after_rollback are called on a saved record if and only if the transaction has been rolled back (hence the change has not been persisted, "immediately after the transaction is rolled back")

I think this is where my conceptual definition is departing.

I would say something more like "the change is being _un_-persisted". It's not enough that the change is not being persisted, it must also have previously _been believed to be persisted_ [within the conditional-persistence definition of a transaction].

In the simplest case: if you make a change to a record's attributes and then don't call `save`, that record will not receive rollback callbacks, because despite having been modified, it was never persisted.

Extrapolating from there, if you attempted to save the record _but failed to do so_, then it still has never been persisted into the transaction's to-be-committed state, and is thus not eligible for rollback.

---

That's just my take on expected behaviour, though... perhaps it'd be worth exploring whether the actual behaviour has changed over time. If it's ~always been this way, I'd be more inclined to better document it as-is; if it's varied, then it might warrant some further consideration.

**Comment by stripedpumpkin** [comment]
I absolutely agree that the record should be saved. In the case I was mentioning the rolled back happened because of a db constraint. I also agree that testing with respect to older versions of Rails is good test of intentions. So here it is:

The version we were discussing:
6.1.4.1 => after_rollback not triggered:
```ruby
  1) Failure:
BugTest#test_after_rollback_is_called_on_not_null_violation [reprod.rb:151]:
Expected: 1
  Actual: 0

  2) Failure:
BugTest#test_after_rollback_is_called_on_not_unique_violation [reprod.rb:187]:
Expected: 1
  Actual: 0


```
Older versions (< 6):
5.2.3 => tests pass
5.2.6.2 => tests pass
5.1.7 => tests pass

Even older versions:
(Here one has to adapt:
```ruby
  gem "activerecord", "= 4.2.11.3"
  gem "sqlite3", "~> 1.3.6"
```
and
```ruby
    # assert_raises ActiveRecord::NotNullViolation do
    assert_raises ActiveRecord::StatementInvalid do
      book.update! title: nil
    end
    # end
```
but 4.2.11.3 => test pass 
(Other things become problematic when downgrading to 4.1)

Newer 6 versions:
6.1.4.6 => same failures as 6.1.4.1

**Comment by alexdowad** [comment]
> I think this is where my conceptual definition is departing.
> 
> I would say something more like "the change is being _un_-persisted". It's not enough that the change is not being persisted, it must also have previously _been believed to be persisted_ [within the conditional-persistence definition of a transaction].
> 
> In the simplest case: if you make a change to a record's attributes and then don't call `save`, that record will not receive rollback callbacks, because despite having been modified, it was never persisted.
> 
> Extrapolating from there, if you attempted to save the record _but failed to do so_, then it still has never been persisted into the transaction's to-be-committed state, and is thus not eligible for rollback.

This is interesting reasoning, but I suggest it may be missing the point.

This is what the Rails documentation states: "There are two additional callbacks that are triggered by the completion of a database transaction: `after_commit` and `after_rollback`. These callbacks are very similar to the `after_save` callback except that they don't execute until after database changes have either been committed or rolled back."

And further: "When a transaction completes, the `after_commit` or `after_rollback` callbacks are called for all models created, updated, or destroyed within that transaction."

The issue which was raised here is that when Active Record methods like `update!` or `destroy` are called, it can happen that AR opens a DB transaction to perform the requested operation, the DB driver raises an error for reasons such as a DB constraint violation, the transaction is rolled back, and then **after_rollback hooks are not called**.

This is exactly the opposite of what the Rails documentation states. It seems fairly safe to say that it is a bug in Rails. I'm not sure what else could be said about it.
