### ISSUE TITLE
scaffold generated system tests don't pass with Rails 7 alpha 2

### ISSUE THREAD

**Issue by rubys** [rails/rails#43768]
### Steps to reproduce
```
rails new library
cd library
rails generate scaffold book title
rails db:migrate
rails test:system
```

### Expected behavior
generated tests pass

### Actual behavior
```
4 runs, 1 assertions, 1 failures, 3 errors, 0 skips
```

Specifically:
  * Unable to find link or button "Edit"
  * Unable to find link or button "New Book"
  * Unable to find link or button "Destroy"
  * expected to find visible css "h1" with text "Books" but there were no matches. Also found "Book", which matched the selector but not all filters

### System configuration
**Rails version**: Rails 7.0.0.alpha2

**Ruby version**: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin21]

**Comment by rafaelfranca** [comment]
Did you test the master branch? I think we fixed that already https://github.com/rails/rails/commit/c6e798c38e19fc1a9d7fa2b1daa9c308c714d6ae

**Comment by rubys** [comment]
I'm embarrassed to say that I'm not sure how to run off the main branch.  Things I've tried:

```
% rails new foo --master
```

> NoMethodError: undefined method `assets' for #<Rails::Application::Configuration

```
echo "gem 'rails', github: 'rails/rails', branch: 'main'" > Gemfile
bundle install
bundle exec rails new foo
```

> `require': cannot load such file -- bootsnap/setup

```
git clone git://github.com/rails/rails.git
./rails/railties/exe/rails new foo
cd foo
rails generate scaffold book title
rails db:migrate
rails test:system
```

> Produces exactly the same results as alpha2

**Comment by rafaelfranca** [comment]
yeah... It is not easy. You would need to clone Rails and run `railties/exe/rails new --edge foo`.

I'm going to release rc1 soon, so Ill make sure the issue is fixed myself using your reproduction steps.

**Comment by rubys** [comment]
Ah, I had all the pieces, I just didn't put them together right.  The following passes:

```
git clone git://github.com/rails/rails.git
./rails/railties/exe/rails new foo --edge
cd foo
rails generate scaffold book title
rails db:migrate
rails test:system
```

**Comment by rafaelfranca** [comment]
Amazing! Thank you for confirming

**Comment by rubys** [comment]
Follow-on issue: https://github.com/rails/tailwindcss-rails/issues/91

I realize that it is a separate gem, but in my opinion that should also be released before RC.  It looks like an easy fix.

Unrelated: alpha=>rc?  What happened to beta?  :-)

**Comment by rafaelfranca** [comment]
> Unrelated: alpha=>rc? What happened to beta? :-)

😂. We thought people had enough time to try already, but I can also release a short beta period. I'll take a look on that issue.

**Comment by rubys** [comment]
Oh, don't mind me.  I'm just poking fun.

FWIW, my sense is each of the components are rock solid, it is the combinatorics of the various options that will be the issue.  And the reality is that no matter how long you have alpha/beta/rc's, most won't try things until the code is released.

An example of the combinatorics: https://github.com/rails/rails/issues/43531

**Comment by rafaelfranca** [comment]
Oh, tricky issue. I think we are fine to address those in the rc. I'm not sure I'll be able to release today, so maybe David already fixed that issue tomorrow.
