### ISSUE TITLE
package.json not updating with build script

### ISSUE THREAD

**Issue by hoffdog** [rails/rails#43784]
### Create a new Rails Project
 rails new test_rails_seven_rc --js esbuild --css bootstrap --skip-activerecord

### Expected behavior
I expect this to be added to the package.json file automatically. 
```
Add build script
Add "scripts": { "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds" } to your package.json

Appending Bootstrap JavaScript import to default entry point
append  app/javascript/application.js
Add build:css script
Add "scripts": { "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules" } to your package.json

```
### Actual behavior
I have to manually add the code above to the package.json.  It does not get automatically added. 

### System configuration
Rails 7.0.0.rc
Ruby 3.0.2

**Comment by SkipKayhil** [comment]
The automatic addition of the build script is dependent on you having npm 7.1+. This is mentioned in the [css-bundling README](https://github.com/rails/cssbundling-rails#installation), although very briefly

**Comment by hoffdog** [comment]
> The automatic addition of the build script is dependent on you having npm 7.1+. This is mentioned in the [css-bundling README](https://github.com/rails/cssbundling-rails#installation), although very briefly

Perfect. Thank you!
