### ISSUE TITLE
link_to :back redirects to OverTheWire website

### ISSUE THREAD

**Issue by Intimaria** [rails/rails#43782]
### Steps to reproduce

```ruby
<%= link_to 'Back', :back, class: "btn btn-secondary btn-sm" %>
```

### Expected behavior

> "Using a :back Symbol instead of an options hash will generate a link to the referrer (a JavaScript back link will be used in place of a referrer if none exists)." 

from [ApiDock.com](https://apidock.com/rails/ActionView/Helpers/UrlHelper/link_to)

### Actual behavior
leads me to a hacking challenge page 
http://natas5.natas.labs.overthewire.org/

### System configuration
**Rails version**: 6.1

**Ruby version**:2.7.4

**Comment by ghiculescu** [comment]
Could you share a sample app that demonstrates this? This feels unlikely to be a rails issue as that link just uses the referrer header or browser history API.

**Comment by Intimaria** [comment]
Thanks for the feedback, you're right - I can't reproduce it in a deployed app. It seems to be something local. Probably a cache issue. Sorry about that!
