### ISSUE TITLE
Unable to resolve javascript module "application"

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#43794]
### Steps to reproduce
1. Create a new rails app: `rails new foo && cd foo`
1. Uncomment the line in routes: `root "articles#index"`
1. Create a articles controller `bin/rails g controller articles`
1. Create `app/views/articles/index.html.erb`
1. Start the server `bin/rails s` and open http://localhost:3000

Open the javascript console and see:

```
Uncaught TypeError: Error resolving module specifier “application”. Relative module specifiers must start with “./”, “../” or “/”. localhost:3000:26:7
```

<img width="1660" alt="Screen Shot 2021-12-07 at 2 34 27 PM" src="https://user-images.githubusercontent.com/92044/145102221-7ac8aab9-3412-460a-b2cd-01630bebbc26.png">

### Expected behavior
no javascript error

### Actual behavior
There is an error in the javascript.

### System configuration
**Rails version**: 7.0.0.rc1

**Ruby version**: 2.7.4

Using latest Firefox and Safari.

The HTML source looks like this:
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Foo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="o8roG8G0LWY8i6o7C1QloC3j2PDXyYDciJJSHNFeQSbFM-l9Siejowxro6r4yxEnZkxnnwvkiBMbAtBFC9I9yA" />
    

    <link rel="stylesheet" href="/assets/application-e0cf9d8fcb18bf7f909d8d91a5e78499f82ac29523d475bf3a9ab265d5e2b451.css" data-turbo-track="reload" />
    <script type="importmap" data-turbo-track="reload">{
  "imports": {
    "application": "/assets/application-37f365cbecf1fa2810a8303f4b6571676fa1f9c56c248528bc14ddb857531b95.js",
    "@hotwired/turbo-rails": "/assets/turbo-7c5e418c7a4d154780d11e54c0fbd17ca23ba401e915c299c4166410c90db9df.js",
    "@hotwired/stimulus": "/assets/stimulus.min-900648768bd96f3faeba359cf33c1bd01ca424ca4d2d05f36a5d8345112ae93c.js",
    "@hotwired/stimulus-loading": "/assets/stimulus-loading-685d40a0b68f785d3cdbab1c0f3575320497462e335c4a63b8de40a355d883c0.js",
    "controllers/hello_controller": "/assets/controllers/hello_controller-549135e8e7c683a538c3d6d517339ba470fcfb79d62f738a0a089ba41851a554.js",
    "controllers": "/assets/controllers/index-2db729dddcc5b979110e98de4b6720f83f91a123172e87281d5a58410fc43806.js",
    "controllers/application": "/assets/controllers/application-368d98631bccbf2349e0d4f8269afb3fe9625118341966de054759d96ea86c7e.js"
  }
}</script>
<link rel="modulepreload" href="/assets/application-37f365cbecf1fa2810a8303f4b6571676fa1f9c56c248528bc14ddb857531b95.js">
<link rel="modulepreload" href="/assets/stimulus.min-900648768bd96f3faeba359cf33c1bd01ca424ca4d2d05f36a5d8345112ae93c.js">
<link rel="modulepreload" href="/assets/stimulus-loading-685d40a0b68f785d3cdbab1c0f3575320497462e335c4a63b8de40a355d883c0.js">
<script src="/assets/es-module-shims.min-14f842b3135c93aeaad8c92b30fab3030c07e9656484b8444ac43f0e2d452ce1.js" async="async" data-turbo-track="reload"></script>
<script type="module">import "application"</script>
  </head>

  <body>
    <h1> hello</h1>

  </body>
</html>
```

**Comment by rafaelfranca** [comment]
Does it works on Chrome?

**Comment by rafaelfranca** [comment]
@dhh would it be related to Firefox and Safari not supporting import maps?

**Comment by jcoyne** [comment]
I was unable to test on chrome.

**Comment by SkipKayhil** [comment]
I'm also able to reproduce the error in Firefox, and can confirm there is no error logged in chrome.

However, the `application.js` still loads/runs even in Firefox. I added `<div data-controller="hello"></div>` to `app/views/articles/index.html.erb` and see "Hello World!" in both browsers

**Comment by dhh** [comment]
This is the expected output when going through the shim: https://github.com/rails/importmap-rails#expected-errors-from-using-the-es-module-shim

**Comment by capripot** [comment]
Also, notice on Firefox the (probably new) message from the shim:
> ^^ Module TypeError above is polyfilled and can be ignored ^^
