### ISSUE TITLE
guides: documentation of `foreign_key` somewhat shallow

### ISSUE THREAD

**Issue by fwolfst** [rails/rails#43803]
Referring to https://edgeguides.rubyonrails.org/active_record_migrations.html#foreign-keys .

The documentation lacks explaining how exactly the `column` or `primary_key` options should be used, does not mention what to do if the table name cannot be inferred by the attribute name (I believe there is a `to_table` option) and also does not state that the foreign-key options can be passed on to column creation statements like `t.integer` (can they?).

Unfortunately I have a hard time figuring out how it is supposed to work. A pointer to the right direction might help me making a change proposal, but it is not my area of expertise.

**Comment by fwolfst** [comment]
So I found out that you can do something like `t.references :the_other_named_thing, null: true, type: :integer, foreign_key: {to_table: :plants}`. The API documentation does a good job to explain the `references` part of the story and its options 👍 .

**Comment by ghiculescu** [comment]
I'm going to close this as it sounds like you found what you needed. But if you do have any thoughts on how to make the docs better, [please submit a PR](https://github.com/rails/rails/blob/main/guides/source/active_record_migrations.md) ❤️ !
