### ISSUE TITLE
Behaviour of ActiveRecord::Relation#one? has changed

### ISSUE THREAD

**Issue by jpawlyn** [rails/rails#43801]
### Steps to reproduce

If a record is removed from a 2 record relation, a call to `one?` returns false.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "v7.0.0.rc1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_one_with_destroy
    Post.create!
    Post.create!
    posts = Post.all
    assert_equal false, posts.one?

    posts.destroy(Post.first.id)

    assert_equal 1, posts.size
    assert_equal true, posts.one?
  end
end
```

### Expected behavior
When a record from a 2 record relation is destroyed, the relation then contains a single record and a call to `one?` returns true. This is the behaviour for v6.1.4.1 and seems like it changed with https://github.com/rails/rails/pull/42143.

### Actual behavior
On destroy the relation contains one record but a call to `one?` returns false. 

### System configuration
**Rails version**:  7.0.0.rc1

**Ruby version**: 2.7.2

**Comment by rafaelfranca** [comment]
This is indeed an issue. Given you can reproduce. Can you take a look on how to fix it?

**Comment by jpawlyn** [comment]
> This is indeed an issue. Given you can reproduce. Can you take a look on how to fix it?

Sure thing. The only solution I found was to remove the memoization - https://github.com/rails/rails/pull/43816. Will this impact the benchmarks @gonzaloriestra do you think?

**Comment by gonzaloriestra** [comment]
Hi! The benchmarks were run without memoization indeed, so I think it's safe to remove it. Thanks!
