### ISSUE TITLE
undefined method .empty? for nil when default_url_options is defined

### ISSUE THREAD

**Issue by pacMakaveli** [rails/rails#43819]
### Steps to reproduce
Define a value for `default_url_options` in an initialiser:
`MyGamesIO::Application.default_url_options = Rails.application.config.action_mailer.default_url_options`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 7.0.0.rc1"
end

require "rack/test"
require "action_controller/railtie"


class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  config.default_url_options = { host: 'localhost:3000' }

  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  TestApp::Application.default_url_options = Rails.application.config.action_mailer.default_url_options
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def show
    render plain: request.path_parameters.inspect
  end
end
```

### Actual behavior

I'll be honest, I cannot for the life of me remember why I need or created this initialiser in the first place. I created it a couple of years ago when I  had some issues with some gems like PaperTrail and ActiveStorage when generating URLs for images, I think.
Anyway, the problem is that without a value, the app will choke without a meaningful error.

Couple of reasons why I opened this issue:

1. This bug was caused by `bin/update` deleting the relevant line of code that defined that value in my `development.rb` file.
```ruby
diff --git a/config/environments/development.rb b/config/environments/development.rb
index 0cf3cbdb..ff5f7d97 100644
--- a/config/environments/development.rb
+++ b/config/environments/development.rb
@@ -1,10 +1,10 @@
+require "active_support/core_ext/integer/time"
+
 Rails.application.configure do
   # Settings specified here will take precedence over those in config/application.rb.

-  config.default_url_options = { host: 'localhost:3000' }
...

    config.action_mailer.perform_caching = false
-  config.action_mailer.default_url_options = { host: 'localhost:3000' }
```
2. I feel like a more meaningful error should be shown to the User.

The problem is that, without the `debug` gem, the error returned by the app/console makes absolutely no sense.
```ruby
undefined method `empty?' for nil:NilClass (NoMethodError)
```

With the debug gem, I finally get something useful:
```ruby
Traceback (most recent call last):
/Users/vlad/.rvm/gems/ruby-2.7.2/gems/actionpack-7.0.0.rc1/lib/action_dispatch/routing/route_set.rb:784:in `optimize_routes_generation?': 
```
I personally don't use `debug` and I've used pry until now, so I've just spent 2 hours trying to figure out what was the issue.

### System configuration
**Rails version**: 7.0.0.rc1
**Ruby version**: 2.7.2

**Comment by rafaelfranca** [comment]
You are setting `TestApp::Application.default_url_options` to `nil` and that value should always be a hash. You either need to remove that line of make sure that `Rails.application.config.action_mailer.default_url_options` is not `nil.

**Comment by pacMakaveli** [comment]
Thanks for the explanation.

The problem is the error message we get back, which is not clear enough.

I feel like this is a very specific case and not many people will come across this, but if they do, they should probably get a better message since having this value set to nil completely breaks the app, and like I said, the message on why it happens is not clear, at all.

Also, maybe `bin/update` shouldn't delete the line.

Not a massive issue, just think it should throw some sort of message that's clearer.

I'd be happy to look at if needed be.

**Comment by pacMakaveli** [comment]
Yup. I'll take a stab at it early next year. 👍🏻  I'll use this issue for reference.

**Comment by wdiechmann** [comment]
hmm - updating/upgrading a 5.x Rails application to 7.x, I kind'a stuck my toe into this hornets nest 😆 

Adding `config.default_url_options = { host: 'localhost:3000' }` to my **environments/development.rb** immediately offer plenty of condiments for my toe ailment 😉 

guess @pacMakaveli never got around to send that PR?

(I didn't manage to keep the hrs to 2 - but then again, I'm still dark dark green, almost #000, using Rails over bootstrapping with `class MyFramework end` - so no complaints what-so-ever) 😃

**Comment by jm3** [comment]
Thanks for posting this, just saved me a ton of time on the quick fix :)
