### ISSUE TITLE
Variable is passed to partial but unable to be used in the partial

### ISSUE THREAD

**Issue by kendallcarey** [rails/rails#43826]
### Steps to reproduce

Create an API only rails app and make the changes to allow a view to be created with a route. I successfully created a triple nested form on this page. The issue happened when I needed to access a variable (that was not a form variable) on the nested partials. 

Pass a collection to a partial:
```ruby
    <%= render partial: "discount_rule", collection: @programs.discount_rules, locals: { f: form } %>
```
the local variable `f` is successfully passed to the partial.

I print out the local variables available to me in the partial:
```ruby
    <%= pp local_variables %>
```
The result I get is: 
```ruby
    [:local_assigns, :output_buffer, :discount_rule, :discount_rule_counter, :discount_rule_iteration, :f]
```
I'll add a debugger:
```ruby
    <% debugger %>
```
type in `discount_rule` in the terminal and get the correct object:
```ruby
    #<DiscountRule id: 24, program_id: 30, name: "Discount Test",...>
```
I replace the debugger with:
```ruby
    <%= discount_rule.name %>
```
So it's in the same scope as the debugger was. I get:
```ruby
    undefined local variable or method `discount_rule' for #<ActionView::Base:0x000000000078c8>
```
`local_assigns[:discount_rule]` does show me the object. I can even get the object's class but I seem to not be able to access any of the fields on the object. I can access the fields on local_assigns[:discount_rule] in the debugger.

There are no syntax errors. I have also tried `discount_rule_counter` and `discount_rule_iteration` and renaming the variable name from the collection (using as: :variable_name) and get the unknown local variable or method errors. I have tried not using collections and just rendering the partial and passing the variables in an each loop. Same errors. 

I am able to use the subform variable in the partial. The reason things have broken now is because I need to access a collection on each individual discount_rule when before I just needed the form variable. I am able to access the variable's fields on the main form and I'm currently just going to have to use the one file and no partials until this is fixed. The reason it was API only was because, after a few months working on this app, only last minute and temporarily did we need a form page.

### Expected behavior
I want to access fields on the local variable that I am passing to a partial.

### Actual behavior
I get the error: `undefined local variable or method `discount_rule' for #<ActionView::Base:0x000000000078c8>`

### System configuration
**Rails version** 
Rails 6.1.4.1

**Ruby version**:
ruby 3.0.2p107

**Comment by ghiculescu** [comment]
Hmm, this seems surprising.

In your view and in your debugger session, try printing `method(:discount_rule).source_location` - that might give you some clues as to how that method works and why it's working inconsistently.

**Comment by kendallcarey** [comment]
On both, I get `undefined method `discount_rule' for class `#<Class:0x000000012788e708>'
Did you mean?  discount_rule_counter`.

**Comment by matthewd** [comment]
You can use `defined?(discount_rule)` to safely detect whether it's available in the view context.

I would suggest that the most likely cause for the behaviour you've described is a second invocation of the partial, which does not supply that variable / a collection, on the same page. When it fails, does the exception backtrace definitely include the line number of the collection render you quoted above?

**Comment by kendallcarey** [comment]
There is something funky going on with the collection that I hadn't noticed. I added a count of the discount_rules for the program and it says 2 but the collection doubles it. When I add the local_assigns(discount_rule).to_json, it is just adding both of the discount_rules twice. I added `<%= defined?(discount_rule) %>` to the partial and all 4 (which should be 2) of the discount rule partials say `local-variable`. I created this program with the discount rules so I know that the collections on the discount_rule are not nil.

**Comment by rafaelfranca** [comment]
I think it would help if you could create an example application reproducing the issue and publish on GitHub so we could also debug with you.

**Comment by kendallcarey** [comment]
I created this test repo! https://github.com/kendallcarey/rails_6_debug_app

**Comment by wittawasw** [comment]
@kendallcarey  The error come from this line.
You didn't pass the `discount_rule` variable into the form here.
https://github.com/kendallcarey/rails_6_debug_app/blob/c8d360d21f39bfc0121af0ae06eba8d15c20195c/app/views/programs/_program_form.html.erb#L21

**Comment by kendallcarey** [comment]
@wittawasw you are correct. Thank you for pointing this out. Sorry for the confusion

**Comment by kendallcarey** [comment]
@wittawasw do you know why the collection has duplicates?
