### ISSUE TITLE
Check constraint with psql CASE statement is nil in schema.

### ISSUE THREAD

**Issue by ChrisCPO** [rails/rails#43823]
### Steps to reproduce
rails 6/7 migration:

```
add_check_constraint :tasks,
  "(CASE WHEN user_task IS TRUE AND assigned_user_id IS NULL THEN FALSE ELSE TRUE END)",
  name: "ensure_user_present_if_required"
 ```
 
 schema: ` t.check_constraint nil, name: "ensure_user_present_if_required"`

can reproduce via console 
```ruby
connection = ActiveRecord::Base.connection; nil
scope = connection.send(:quoted_scope, "tasks")
check_info = connection.exec_query(<<-SQL, "SCHEMA")
            SELECT conname, pg_get_constraintdef(c.oid) AS constraintdef, c.convalidated AS valid
            FROM pg_constraint c
            JOIN pg_class t ON c.conrelid = t.oid
            WHERE c.contype = 'c'
              AND t.relname = #{scope[:name]}
          SQL

row = check_info.first
expression = row["constraintdef"][/CHECK \({2}(.+)\){2}/, 1] #returns nil
```

### Expected behavior
schema should have full check: 
`t.check_constraint "CASE WHEN user_task IS TRUE AND assigned_user_id IS NULL THEN FALSE ELSE
TRUE END", name: "ensure_user_present_if_required"`

### Actual behavior
 schema: ` t.check_constraint nil, name: "ensure_user_present_if_required"`

### System configuration
**Rails version**: on 6 but code is same on 7.

**Ruby version**: `ruby 3.0.2p107`

**Bug location**: https://github.com/rails/rails/blob/38cb5610b17c1cb6e6a6abfb54e79f104376ef61/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L538

**Comment by ghiculescu** [comment]
This is indeed an issue. Given you can reproduce, can you take a look at how to fix it?
