### ISSUE TITLE
Rails 7.0.0.rc1 Engine Initializer Hooks Not Working 

### ISSUE THREAD

**Issue by cpanderson** [rails/rails#43822]
Trying to get my gem working with Rails 7. Works in Rails 6.1.4.1. In the engine.rb file I want to automatically include my controller in the main app controller but I get...

```uninitialized constant MyEngine::MyController (NameError)```

All my controllers, models, etc are name spaced and my engine.rb file looks like this...

```
module MyEngine
  class Engine < ::Rails::Engine
    isolate_namespace MyEngine

    initializer "my_engine.include_controller" do |app|
      ActionController::Base.send :include, MyEngine::MyController
    end
  end
end
```

I have also tried...

```ActionController::Base.include MyEngine::MyController```

and...

```
ActiveSupport.on_load :action_controller_base do
  include MyEngine::MyController
end
```

If I put the following in the main app's ApplicationController instead then it works...

```include MyEngine::MyController```

### Steps to reproduce

Inside a new rails 7 app...

```rails plugin new blorgh --mountable```

Which creates an application_controller.rb file in <app_name>/blorgh/app/controllers/blorgh

Add an initializer to the engine.rb file...

```
initializer "blorgh.include_controller" do |app|
  ActionController::Base.include Blorgh::ApplicationController
end
```

### Expected behavior
No error to occur and controller is available in main app

### Actual behavior
errors out with "uninitialized constant (NameError)"

### System configuration
**Rails version**: 7.0.0.rc1

**Ruby version**: 2.7.3 and 3.0.1 (these are the two I tried)

**Comment by cpanderson** [comment]
Thanks Raphael, 

It's in the app directory. I will try the suggestions. Other than the edge guide is there documentation for upgrading engines for Rails 7?

**Comment by rafaelfranca** [comment]
For this specific issue, there is a general callout to make the application run in the zeitwerk mode https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#applications-need-to-run-in-zeitwerk-mode.

**Comment by cpanderson** [comment]
I'm not sure what I missed documentation/deprecation wise between 6.1 and 7 as my gem worked in 6.1 in zeitwerk mode. I can confirm that using a config/initializer with to_prepend and also using a before_initialize hook in the engine.rb file both work in this particular case.

I think the documentation could use some improvement in regards to engine convention in this new paradigm. I don't know enough about it to make any recommendations.

Thanks Rafael. Close this if you want.

**Comment by rafaelfranca** [comment]
The engine recommendations are the same as the application recommendations. Applications are engines, so their behavior are the same.

There [were for sure deprecation for this](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#autoloading-during-initialization), since 6.0 it is being show, maybe you were testing the engine with deprecations disabled?

**Comment by cpanderson** [comment]
I didn't say there weren't any notices, I said I don't know how I missed them. I see lots of other deprecation warnings and have seen them in my gems as well. Just not this particular one where I recently upgraded an application from 5.2 to 6.1. Even checking it now produces no deprecations for this particular issue.

Anyways, thanks again. I'm happy I can move forward with getting my gems updated for Rails 7.
