### ISSUE TITLE
Proposal to change api for content_security_policy

### ISSUE THREAD

**Issue by stoivo** [rails/rails#43827]
Hello, 👋

We are currently setting up content security policy for our application. We want to follow the rails convention as much as possible, we gave rails content security policy setup a try. 

It is working, although I find the api strange and hard to work with. Iit could be me doing it wrong but look at this.

We want to have recaptcha on your contact form but nowhere else, and you always want to send errors to bugsnag (error tracker)
```rb
# config.rb
Rails.application.config.content_security_policy do |policy|
  policy.connect_src(
    :self,
    "https://sessions.bugsnag.com/",
    "https://notify.bugsnag.com/",
  )

  policy.report_uri "/csp_violation_report"
end

Rails.application.config.content_security_policy_report_only = true

# I want the controller to look like 
class FrontPageController < ApplicationController
  content_security_policy do |policy|
    policy.script_src("https://www.gstatic.com/recaptcha/releases")
    policy.connect_src("https://www.recaptcha.net")
  end

  def index
  end
end
```

This would work correctly for script-src but connect-src would be overwritten. We could need to read out the existing connect sources and add one and reset.

```rb
new_connection = policy.connect_src
new_connection.push("https://www.recaptcha.net")
policy.connect_src(**new_connection)
```

This is ok, if connect_src is set in config. Otherwise new_connection would be nil.

```rb
new_connection = policy.connect_src || []
new_connection.push("https://www.recaptcha.net")
policy.connect_src(**new_connection)
policy.connect_src(clear: true)
```

Great! Now I can have this in the controller and it will add if already present and set if not. I have to do this for script_src too in case I add script_src to config later.

I think we should have a reader so that you can debug different directives. I thought we had one. When you call connect_src without any arguments it would return the existing values (once at least), actually it unsets and deletes current values.

I propose to change the api.

https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/actionpack/lib/action_dispatch/http/content_security_policy.rb#L163-L171

```rb
# can't think of a case when you want re move one entry in a directive

# alternative 1. two methods, on to add and one to clear
DIRECTIVES.each do |name, directive|
  define_method(name) do |*sources|
    @directives[directive].concat(apply_mappings(sources))
  end

  define_method("unset_#{name}".to_sym) do
    @directives.delete(directive)
  end
end

# alternative 2. one method with an option to clear the directive before adding
# maybe overwrite would be better name for the option.
DIRECTIVES.each do |name, directive|
  define_method(name) do |*sources, clear: false|
    @directives.delete(directive) if clear
    @directives[directive].concat(apply_mappings(sources))
  end
end

# probably some changed more
```

I like alternative 2. 
It's short, concise and you can do it all in one line.

**Comment by spdawson** [comment]
> I think we should have a reader so that you can debug different directives. I thought we had one. When you call connect_src without any arguments it would return the existing values (once at least), actually it unsets and deletes current values.

:+1: This is similar in spirit to what I proposed in #31366; I also find the current API a little awkward to work with, in all but the most trivial use-cases.

**Comment by rafaelfranca** [comment]
If you are sure about your proposal please open a PR. It is easier to discuss a propoval on top of working code than text. If you want to discuss, please use the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5).

**Comment by stoivo** [comment]
I have created a PR with suggested changes. #44015
