### ISSUE TITLE
Proposal to add Model Generator to separate models 

### ISSUE THREAD

**Issue by avosa** [rails/rails#43830]
### How the situation currently is

When scaffolding models they are all added in the app/models directory in no particular order.
For example, if I'm creating three models Product, Order, Comment as below:
  * rails g model Product
  * rails g model Order
  * rails g model Comment
   
 The result of the above actions will result in ```product.rb```, ```order.rb``` and ```comment.rb```  created in format below: 
  * app/models/product.rb
  * app/models/order.rb
  * app/models/comment.rb

The above format is not ideal as all the models are mixed in the ```models``` directory.
Maintaining the microservice/service will be unfriendly/difficult since the models don't have any order.
One, for example, has to restructure the models manually adding new folder names to help make maintenance easier.

### My proposal

I'm proposing improving model generators to separate models; instead of using normal ```rails g model Order``` for instance, have a generator say, ```rails g model OrderContext Order``` where OrderContext will be a new directory inside ```models``` directory such that the models will be generated into app/models/order_context directory.

Using the examples above, we will have models in separate folders/directories inside the models directory as below:
  * app/models/product_context/product.rb
  * app/models/oder_context/oder.rb
  * app/models/comment_context/comment.rb
  
As you can see, this will be neat and fasten code maintenance.
 

### System configuration
**Rails version**:
6.0 onwards

**Ruby version**:
2.5 onwards

**Comment by rafaelfranca** [comment]
Doesn't `rails g model order_context/order` work already? Note that only moving the model to a folder will not work since Rails will not know how to autoload that constant since the file path doesn't match the constant name anymore, so you also need to add the namespace to the class, which will create the model in the right folder. Thank you for the issue.

**Comment by avosa** [comment]
Thank you for the response @rafaelfranca. I, however, don't think ```rails g model order_context/order``` works or maybe there's a misunderstanding.

**Comment by avosa** [comment]
Refer to [this](https://hexdocs.pm/phoenix/contexts.html#:~:text=mix%20phx.gen.html%20Catalog%20Product%20products%20title%3Astring%20%5C) solves this. That's the same idea I'm trying to put across and see if the same can be implemented in Rails.

**Comment by condef5** [comment]
Hey @avosa, I just tried the command as Rafael says, and works really well
![order rb — biobridge-backend 2021-12-10 at 3 46 44 PM](https://user-images.githubusercontent.com/21107031/145639315-bd845bab-dcc7-4a9a-8825-398f1a42f584.jpg)

**Comment by avosa** [comment]
@condef5 Thanks for the screenshots, I've seen where I was making a mistake.
