### ISSUE TITLE
Running db:migrate with multi-db setup

### ISSUE THREAD

**Issue by EscoCreeks** [rails/rails#43833]
Issue related to conversation in [this commit](https://github.com/rails/rails/commit/45eb0f3beccc966689ddf76d1d3c0618852f8af6)

Note: In the repository there are 3 migrations
20211210172422_create_user_table.rb => already run in the db
20211210172519_add_password_to_users.rb => not run yet in the db
20211210172534_add_email_to_users.rb => already run in the db

The issue happens because of multi-db and mentioned commit

### Steps to reproduce

1. clone the public repository: https://github.com/EscoCreeks/rails-multi-db-migrate
2. bundle
3. rails db:migrate

### Expected behavior
The migration should run:
```
== 20211210172519 AddPasswordToUsers: migrating ===============================
-- add_column(:user_tables, :password, :string)
   -> 0.0025s
== 20211210172519 AddPasswordToUsers: migrated (0.0026s) ======================
```

### Actual behavior
The migration is "reverting" the migration 20211210172534_add_email_to_users.rb 
```
== 20211210172534 AddEmailToUsers: reverting ==================================
-- remove_column(:user_tables, :email, :string)
   -> 0.0229s
== 20211210172534 AddEmailToUsers: reverted (0.0250s) =========================
```

### System configuration
**Rails version**: 7.0.0.alpha2

**Ruby version**: 3.0.3

**Comment by morgoth** [comment]
@EscoCreeks this was fixed in https://github.com/rails/rails/pull/43988 and can be closed now
