### ISSUE TITLE
Self referential link in Scaffold Partial

### ISSUE THREAD

**Issue by fig** [rails/rails#43843]
#41210 Introduced a Modernised Scaffold Generator. The modernised scaffold includes a partial template that has a [link to itself](https://github.com/rails/rails/blob/a35a380c2cdc7fe032f927095545aee21a192f54/railties/lib/rails/generators/erb/scaffold/templates/partial.html.erb.tt#L18).

Because the partial is rendered in response to both an `index` and a `show` action, the link is rendered redundantly in response to a `show`  request.

**Comment by ghiculescu** [comment]
Thanks for the report. Looks like an oversight we should fix. Would you like to make a PR to fix it?
