### ISSUE TITLE
test_clear_failure_returns_nil tests fails since dalli 3.1.1

### ISSUE THREAD

**Issue by yahonda** [rails/rails#43849]
Managed to reproduce CI failures since https://buildkite.com/rails/rails/builds/83226#222c384e-50c4-42e3-9ca4-64c32cee1dbd

These failures are triggered by this change https://github.com/petergoldstein/dalli/commit/6495138e2f63f066225d73f1ff681ba06b4edca7

### Steps to reproduce
```ruby
$ cd activesupport
$ bundle update dalli --conservative
$ bin/test test/cache/stores/mem_cache_store_test.rb -n test_clear_failure_returns_nil
```
### Expected behavior
It should pass.

### Actual behavior
```ruby
$ bundle update dalli --conservative
... snip ...
$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 9476667024..3ba23f15c4 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -189,7 +189,7 @@ GEM
       railties (>= 6.0.0)
     curses (1.4.2)
     daemons (1.4.0)
-    dalli (3.0.1)
+    dalli (3.1.1)
     dante (0.2.0)
     debug (1.1.0)
       irb
@@ -609,4 +609,4 @@ DEPENDENCIES
   websocket-client-simple!

 BUNDLED WITH
-   2.2.29
+   2.2.32
$
```

```ruby
$ bin/test test/cache/stores/mem_cache_store_test.rb -n test_clear_failure_returns_nil
Run options: -n test_clear_failure_returns_nil --seed 35954

# Running:

F

Failure:
OptimizedMemCacheStoreTest#test_clear_failure_returns_nil [/home/yahonda/src/github.com/rails/rails/activesupport/test/cache/behaviors/failure_safety_behavior.rb:123]:
Expected [true] to be nil.


bin/test test/cache/behaviors/failure_safety_behavior.rb:121

F

Failure:
MemCacheStoreTest#test_clear_failure_returns_nil [/home/yahonda/src/github.com/rails/rails/activesupport/test/cache/behaviors/failure_safety_behavior.rb:123]:
Expected [true] to be nil.


bin/test test/cache/behaviors/failure_safety_behavior.rb:121



Finished in 0.012204s, 163.8856 runs/s, 163.8856 assertions/s.
2 runs, 2 assertions, 2 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**:ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]

**Comment by matthewd** [comment]
Thanks for investigating!

I guess that means we need to change this (and/or the mentioned `UnavailableDalliServer` class): https://github.com/rails/rails/blob/42e92c0a8e5b007672a50fee5dcbab75717e367c/activesupport/test/cache/stores/mem_cache_store_test.rb#L302-L310

Specifically, I think we might need to have that test patch `Dalli::Protocol::ConnectionManager` instead. (IMO it's probably fine to just change our Gemfile to require the new Dalli version, and not keep this test compatible with the older one, though we should remain backwards-compatible in our runtime implementation.)

**Comment by ghiculescu** [comment]
Hmm, I think the real issue is this check has been removed: https://github.com/petergoldstein/dalli/commit/6495138e2f63f066225d73f1ff681ba06b4edca7#diff-95f40bab82f3e5f469f064bc02fde33597d531cd74aaaad2015ed7a6ce4c1f79L71

If you add it back, the tests pass again.

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/43857 should fix it
