### ISSUE TITLE
Using `http://localhost:3000/` works fine in development. Other hostnames that are added don't.

### ISSUE THREAD

**Issue by RaminDadou** [rails/rails#43874]
Using `http://localhost:3000/` works fine in development. Other hostnames that are added don't.

_Originally posted by @johan-smits in https://github.com/rails/rails/issues/43870#issuecomment-994512650_

**Comment by johan-smits** [comment]
@RaminDadou why is this a new issue? To me it is feedback on the already open issue #43870

**Comment by RaminDadou** [comment]
> Using `http://localhost:3000/` works fine in development. Other hostnames that are added don't.
> 
> _Originally posted by @johan-smits in https://github.com/rails/rails/issues/43870#issuecomment-994512650_

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/43871 should resolve this, so I'm giong to close this as a duplicate.
