### ISSUE TITLE
Local development, puma-dev host no longer working after 6.0.4.2 + 6.0.4.3

### ISSUE THREAD

**Issue by radar** [rails/rails#43870]
### Steps to reproduce

1. `rails new _6.0.4.3_ host`
2. Add this line to `config/environments/development.rb`: config.hosts << "host.test"
3. Point `host.test` to `127.0.0.1` using your favourite method (ours is by using `puma-dev link .`)
4. Attempt to access `host.test`, or `host.test:3000`

### Expected behavior

Rails application loads successfully.

### Actual behavior

<img width="855" alt="image" src="https://user-images.githubusercontent.com/2687/146099707-67bd3aee-575b-4abe-9908-a7bffbbc5bfb.png">

### System configuration

**Rails version**: 6.0.4.3
**Ruby version**: 2.7.something

**Comment by radar** [comment]
Related to #43868

**Comment by rafaelfranca** [comment]
I'm trying to write a test for this and it seems accessing `host.test` works. Can you confirm the problem only happens when you try to access in a port?

**Comment by radar** [comment]
Yes, seems like without the port it works fine:

![Uploading image.png…]()

**Comment by rafaelfranca** [comment]
Thanks! I think I have a fix. I'll push in a few minutes with a new release.

**Comment by johan-smits** [comment]
Using `http://localhost:3000/` works fine in development. Other hostnames that are added don't.

**Comment by RaminDadou** [comment]
> ### Steps to reproduce
> 
> 1. `rails new _6.0.4.3_ host`
> 2. Add this line to `config/environments/development.rb`: config.hosts << "host.test"
> 3. Point `host.test` to `127.0.0.1` using your favourite method (ours is by using `puma-dev link .`)
> 4. Attempt to access `host.test`, or `host.test:3000`
> 
> 
> ### Expected behavior
> 
> Rails application loads successfully.
> 
> ### Actual behavior
> 
> <img width="855" alt="image" src="https://user-images.githubusercontent.com/2687/146099707-67bd3aee-575b-4abe-9908-a7bffbbc5bfb.png">
> 
> 
> ### System configuration
> 
> **Rails version**: 6.0.4.3
> **Ruby version**: 2.7.something
>

**Comment by NDuggan** [comment]
Can confirm the same is happening for me on `6.1.4.3` - @RaminDadou

**Comment by khalilgharbaoui** [comment]
A workaround for this would be to temporarily add: `config.hosts.clear` to your `config/environments/development.rb` until there is a proper fix for it. 🤔

**Comment by jmeattle** [comment]
We are facing this with the following:

```
  config.hosts << ".abc.com"
```
