### ISSUE TITLE
cssbundling-rails is not included with rails-7.0.0.rc3

### ISSUE THREAD

**Issue by MdreW** [rails/rails#43875]
### Steps to reproduce
in a new installation of rails with the command `rails new . -d postgresql -j importmap -C [tailwind | bulma]` cssbundling is not in GEMFILE, the css processor are not installated and task `./bin/rails css:install:bulma` are not available.

If I add manually the cssbundling gem in Gemfile and run `./bin/rails css:install:bulma` command manually all work

### Expected behavior
* cssbundling installed
* yarn innitialized
* importmap configured

### Actual behavior
* cssbundling no installed
* yarn not innitialized
* importmap not configured

### System configuration
**Rails version**: Rails 7.0.0.rc3
**Ruby version**: ruby-3.0.3

**Comment by ghiculescu** [comment]
I'm not sure that's the right command. I think it's meant to be `--css bulma`, or `-c bulma` (lowercase). Can you try one of those?

**Comment by ghiculescu** [comment]
Command is defined here https://github.com/rails/rails/blob/52c0711bcf9bc991887822f235e8c561b53a8213/railties/lib/rails/generators/rails/app/app_generator.rb#L269

**Comment by MdreW** [comment]
I confirm my type error, apologize for this!
