### ISSUE TITLE
Update to Rails 7.0.0 from 7.0.0.rc.3 Resolving Dependencies Error

### ISSUE THREAD

**Issue by cloudsbird** [rails/rails#43888]
### Steps to reproduce

1. Change the gemfile, from `gem 'rails',                          '~> 7.0.0.rc3'` to `gem 'rails',                          '~> 7.0.0'`
2. `bundle update`

### Expected behavior

Should can be updated
### Actual behavior

Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................^C

### System configuration
**Rails version**:
7.0.0.rc.3 -> 7.0.0
**Ruby version**:
3.0.2

**Comment by rafaelfranca** [comment]
Thank you for the issue. There is no code difference between 7.0.0.rc3 and 7.0.0, so this is most likely a bundler/rubygems issue. Make sure you update both. If it doesn't work, please report to Rubygems.

**Comment by gjtorikian** [comment]
@cloudsbird Did you find a solution for this? I'm experiencing the same issue.

**Comment by gjtorikian** [comment]
Ah, I came up with a "fix" on my own: I uncommented out every other gem in the Gemfile, ran `bundle update`, then uncommented everything back in. Hope this helps someone in the future ✌️

**Comment by cloudsbird** [comment]
> @cloudsbird Did you find a solution for this? I'm experiencing the same issue.

I found the issues is in acts_as_paranoid.. I think some of gem which dependent on rails < 7.0 only will got this error
