### ISSUE TITLE
delete_all, destroy_all support batch deletion

### ISSUE THREAD

**Issue by KSH-code** [rails/rails#43893]
First of all, this is not a bug. it is about a feature request.

e.g.
```
codes.in_groups_of(1000, false).each {|batch| Model.where(code: batch).delete_all}
```
I'd be happy with new feature e.g.
```
Model.where(code: codes).batch_delete_all(1000)
```

the example for is only for example. it may be another form under implementation.

Why I'm using batch deletion is because huge table and huge deletion rows can occupy database.
that affect other processes because of starvation.

**Comment by KSH-code** [comment]
so after it is approved, I'll start implementing.

**Comment by KSH-code** [comment]
it is a kind of https://github.com/rails/rails/pull/40445.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.

**Comment by KSH-code** [comment]
Thank you for guide.
