### ISSUE TITLE
Rails guide needs updated to show new welcome screen

### ISSUE THREAD

**Issue by yahonda** [rails/rails#43892]
### Steps to reproduce
Open this link https://guides.rubyonrails.org/getting_started.html#starting-up-the-web-server

### Expected behavior
It should show the new startup screen since https://github.com/rails/rails/commit/5889e6ba9255a6ae6eb14992b297dd1021d01c21
![Rails700](https://user-images.githubusercontent.com/73684/146308451-07ac525e-1e29-4360-969e-fc84fe8f369c.png)

### Actual behavior
It shows the startup screen used at Rails 6.1.

### System configuration
**Rails version**: 7.0.0

**Ruby version**:ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]

**Comment by yahonda** [comment]
Let me open a pull request to update these files.

https://github.com/rails/rails/blob/v7.0.0/guides/assets/images/getting_started/rails_welcome.png
https://github.com/rails/rails/blame/v7.0.0/guides/source/getting_started.md#L250
https://github.com/rails/rails/blame/v7.0.0/guides/source/getting_started.md#L257

**Comment by rafaelfranca** [comment]
👍🏽. Please
