### ISSUE TITLE
rails new with -f -c doesn't add "scripts" to package.json

### ISSUE THREAD

**Issue by mithos99** [rails/rails#43896]
### Steps to reproduce
rails new myapp -j esbuild -c bootstrap

### Expected behavior
package.json has 
"scripts": { "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds" }
and 
"scripts": { "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules" }

### Actual behavior
package.json content:

{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.0.1",
    "@hotwired/turbo-rails": "^7.1.0",
    "@popperjs/core": "^2.11.0",
    "bootstrap": "^5.1.3",
    "esbuild": "^0.14.5",
    "sass": "^1.45.0"
  }
}

### System configuration
rails 7.0.0 (rc3 too)
ruby 3.0.3

**Comment by deanpcmad** [comment]
It's likely something has failed during the `jsbundling-rails` setup. What happens if you run this:

```
bin/rails javascript:install:esbuild
```

**Comment by mithos99** [comment]
Found a problem.
I had npm version < 7.1 thus command "npm set-script build "esbuild ..." failed.

**Comment by thedayisntgray** [comment]
This is pretty for beginners. Should rails throw some sort of warning if npm isn't the version it is expecting.
