### ISSUE TITLE
Multiple CHANGELOG entries for "Fix compatibility with `psych >= 4`"

### ISSUE THREAD

**Issue by yahonda** [rails/rails#43890]
### Steps to reproduce

I am checking Ruby 3.1 compatibility with Rails, I have found there are 3 changelog entries for "Fix compatibility with `psych >= 4".

- For upcoming Rails 6.1.z versions (will be 6.1.5 if it is released)
https://github.com/rails/rails/blame/6-1-stable/activerecord/CHANGELOG.md#L35-L41

- As part of `## Rails 6.1.4 (June 24, 2021) ##`
https://github.com/rails/rails/blame/6-1-stable/activerecord/CHANGELOG.md#L75-L80

- As part of `## Rails 7.0.0.alpha1 (September 15, 2021) ##`
https://github.com/rails/rails/blame/7-0-stable/activerecord/CHANGELOG.md#L974-L979

### Expected behavior
CHANGELOG entry for "Fix compatibility with `psych >= 4" should be written in once at `## Rails 6.1.4 (June 24, 2021) ##`

### Actual behavior
CHANGELOG entry for "Fix compatibility with `psych >= 4`" are written in multiple versions, 7.0.0.alpha1, 6.1.4 and upcoming 6.1.z release 

### System configuration
**Rails version**: 7.0.0 and 6.1.4

**Ruby version**: Not specific to Ruby version

**Comment by yahonda** [comment]
This is a commit for `6-1-stable` branch on May 19 which was included in Rails 6.1.4. https://github.com/rails/rails/commit/255b5ff9af5

**Comment by rafaelfranca** [comment]
The CHANGELOG in 7-0-stable is correct. But I'll remove the CHANGELOG in 6.1.5
