### ISSUE TITLE
Rails 7 .to_formatted_s ignores zone when constructed as Time.zone.now.to_formatted_s(:db)

### ISSUE THREAD

**Issue by ccasabona** [rails/rails#43905]
While converting a Rail 6.1 app to Rails 7, I replaced occurrences of .to_s(:db) with .to_formatted_s(:db) to clear the deprecation notices.  I had many constructs of Time.zone.now.to_s(:db) that were duly changed to Time.zone.now.to_formatted_s(:db).

The method .to_formatted_s, however, ignores the .zone when constructed as I have done above.

To recreate this, load the rails console from a Rails 7 app (in the Eastern US Time zone, the time of this test was 17:43):

```
railsapp [master_rails70●] % rails c
Loading development environment (Rails 7.0.0)
3.0.3 :001 > Time.now
2021-12-16 17:43:37.194669 -0500
3.0.3 :002 > Time.zone.now
Thu, 16 Dec 2021 17:43:44.947349000 EST -05:00
3.0.3 :003 > Time.now.to_formatted_s(:db)
"2021-12-16 17:44:00"
3.0.3 :004 > Time.zone.now.to_formatted_s(:db)
"2021-12-16 22:44:05"
3.0.3 :005 > Time.now.to_formatted_s(:db).in_time_zone
Thu, 16 Dec 2021 17:44:24.000000000 EST -05:00
3.0.3 :006 > 


```
Time.zone.now.to_formatted_s(:db) should return the same time as Time.now.to_formatted_s(:db).in_time_zone.

### Actual behavior
Time.zone.now.to_formatted_s(:db) ignores the .zone method

### System configuration
Rails 7.0.0

**Ruby version**:
Ruby 3.0.2

**Comment by casperisfine** [comment]
Sorry, but I either don't understand what the bug is, or can't reproduce.

I used the following script:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activesupport", ENV.fetch("RAILS_VERSION", "~> 6.1")
  gem "minitest"
end

require "minitest/autorun"
require "active_support/all"

class TimeTest < ActiveSupport::TestCase
  test "to_s vs to_formatted_s" do
    Time.zone = ActiveSupport::TimeZone['Eastern Time (US & Canada)']
    travel_to Time.zone.local(2021, 1, 1, 1, 0, 0) do
      now = Time.now
      assert_equal '2021-01-01 07:00:00', now.to_s(:db)
      assert_equal "2021-01-01 07:00:00", now.to_formatted_s(:db)

      zone_now = Time.zone.now
      assert_equal '2021-01-01 06:00:00', zone_now.to_s(:db)
      assert_equal '2021-01-01 06:00:00', zone_now.to_formatted_s(:db)
    end
  end
end
```

It passes on both 6.1 and 7.0. Could you provide a repro script on the same basis?

**Comment by ccasabona** [comment]
That is indeed interesting.  When I run the above script on 6.1 and 7.0, I get the same error. Here is the output from the Rails 7 test:

```
DEPRECATION WARNING: Time#to_s(:db) is deprecated. Please use Time#to_formatted_s(:db) instead. (called from block (2 levels) in <class:TimeTest> at time.rb:17)
F

Finished in 0.026499s, 37.7373 runs/s, 37.7373 assertions/s.

  1) Failure:
TimeTest#test_to_s_vs_to_formatted_s [time.rb:17]:
Expected: "2021-01-01 07:00:00"
  Actual: "2021-01-01 01:00:00"

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by ccasabona** [comment]
After getting a Rails 7 project to a production server under Centos 7, I cannot duplicate this error there.  I can reliably duplicate this error in development and test environments using latest Mac Catalina and Monterey.  I am closing this since Time.now.to_formatted_s(:db).in_time_zone works everywhere.
