### ISSUE TITLE
`--css bootstrap` results in an error once the layout attempts to render

### ISSUE THREAD

**Issue by MattBudz** [rails/rails#43901]
### Steps to reproduce

When creating a new app with bootstrap using the `--css bootstrap` option, the app throws an error

1. Create the app: `$ rails new MyApp --css bootstrap`
2. Generate a scaffold `$ rails g scaffold post title content:text`
3. Create/Setup the db
4. Run migrations
5. Start the server
6. Navigate to `posts#index`
7. Get an error

### Expected behavior
```$ rails new MyApp --css bootstrap``` should create an app with bootstrap loaded out-of-the-box.

### Actual behavior
```$ rails new MyApp --css bootstrap``` creates an app where navigating to any view other than the welcome screen results in:

```
Sprockets::Rails::Helper::AssetNotFound in Posts#index
Showing app/views/layouts/application.html.erb where line #9 raised:

The asset "application.css" is not present in the asset pipeline.
```

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.3

**Comment by deanpcmad** [comment]
With `cssbundling-rails`, which is used when using the `--css` option, you'll need to run `bin/dev` to start the CSS bundling script and start the Rails server at the same time

**Comment by MattBudz** [comment]
turns out I had to upgrade my npm.

**Comment by dhh** [comment]
Was just going to say. I had fixed this so `build:css` is automatically run on install, but only if you have a compatible npx version: https://github.com/rails/cssbundling-rails/blob/main/lib/install/bootstrap/install.rb
