### ISSUE TITLE
Some rubyonrails.org pages are not found when visit from search engine

### ISSUE THREAD

**Issue by mtsmfm** [rails/rails#43912]
Please let me know if I should re-recreate this issue on https://github.com/rails/website.

---

Previously, https://rubyonrails.org serves pages with trailing slash but now it returns 404.
Existing links like search engines' indexes are still have references to old URL.
Is it intentional?

### Steps to reproduce

1. Search "rails security policy" on google.com
2. Visit the Security policy page

![image](https://user-images.githubusercontent.com/1796864/146538603-35e55fe0-aac8-4791-a8ab-5b6fc93bba7e.png)

### Expected behavior

Show content as the same as https://rubyonrails.org/security or redirect to https://rubyonrails.org/security

### Actual behavior

https://rubyonrails.org/security/ returns 404

**Comment by casperisfine** [comment]
> Please let me know if I should re-recreate this issue on https://github.com/rails/website.

Yes please.

**Comment by mtsmfm** [comment]
https://github.com/rails/website/issues/6
