### ISSUE TITLE
Action Text gif attachments display as static images

### ISSUE THREAD

**Issue by ConfusedVorlon** [rails/rails#43917]
### Steps to reproduce

1) edit an ActionText field
2) attach a gif
3) view the rendered result

### Expected behavior

the gif should be animated

### Actual behavior

the gif is displayed as a single static frame 

### System configuration
**Rails version**:
6.1.4

**Ruby version**:
3.0.2

**Comment by ConfusedVorlon** [comment]
the fix which works for me is to edit 

#app/views/active_storage/blobs/_blob.html.erb

replacing
```

  <% if blob.representable? %>
    <%= image_tag url_for(blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])) %>
  <% end %>
```

with

```
  <% if blob.representable? %>
    <%= image_tag url_for(blob.representation(loader: { page: nil }, coalesce: true, resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])) %>
  <% end %>
```


I don't have the broad knowledge to know whether this might cause problems in non-gif cases...

**Comment by ConfusedVorlon** [comment]
This is still a live issue.

I was able to work around the issue as commented above when using rMagick, but I'm now on VIPS and I get the error

> Vips::Error: VipsOperation: class "coalesce" not found

**Comment by porterbayne** [comment]
Same -- I'm on Rails 7 with VIPS, and embedded animated GIFs render correctly in the Trix editor, but not in the output.

**Comment by ParamagicDev** [comment]
If using VIPs, you may have to compile with imagemagick support. I haven't quite figured out the magical incantation, but here's VIPs / ImageProcessing docs on it:

https://github.com/janko/image_processing/blob/master/doc/vips.md#convert

**Comment by Talha345** [comment]
The following works for VIPS:

`    <%= image_tag blob.representation(loader: { n: -1 }, resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>`

**Comment by mhenrixon** [comment]
> The following works for VIPS:
> 
> 
> 
> `    <%= image_tag blob.representation(loader: { n: -1 }, resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>`
> 
> 

How would you do that in action text/trix @Talha345 ?

**Comment by Talha345** [comment]
> > The following works for VIPS:
> > 
> > 
> > 
> > `    <%= image_tag blob.representation(loader: { n: -1 }, resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>`
> > 
> > 
> 
> How would you do that in action text/trix @Talha345 ?

There is a default partial created for displaying images when installing action text. Simply update the image tag in there.
