### ISSUE TITLE
in rails 7 link_to @article, @article not working as in rails 6

### ISSUE THREAD

**Issue by donapieppo** [rails/rails#43913]
### Steps to reproduce

```ruby
link_to @article  # => <a href="/articles/1">article name</a>
link_to @article, '\pippo' # => <a href="\pippo">article name</a>
link_to @article.to_s, @article # => <a href="/articles/1">article name</a>
link_to @article, article_path(article) # => <a href="/articles/1">article name</a>

link_to @article, @article # raise undefined method `empty?' for #<Article id: 1,

```

### Expected behavior
```ruby
link_to @article, @article # => <a href="/articles/1">article name</a>
```
This form of link_to was ok in rails 6. 
In rails 7 no more. 

The documentation in ActionView 

> More concise yet, when +name+ is an Active Record model that defines a
> +to_s+ method returning a default value or a model instance attribute

propose only the `link_to @article` version but on rails 6 also `link_to @article, @article` was working.
I have a lot of code like this and maby many like me.

### Actual behavior
```ruby
link_to @article, @article # raise undefined method `empty?' for #<Article id: 1,
```

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.3

**Comment by ghiculescu** [comment]
Sounds like https://github.com/rails/rails/pull/42234 might be the culprit. I can see this test fails with the error you describe

```ruby
  def test_link_tag_using_active_record_model_twice
    @workshop = Workshop.new(1.to_s)
    link = link_to(@workshop, @workshop)
    assert_dom_equal %{<a href="/workshops/1">1</a>}, link
  end
```

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/43918 should fix it. FYI @olivierlacan
