### ISSUE TITLE
In Rails 7 rails generators for engines do not work anymore

### ISSUE THREAD

**Issue by muriloime** [rails/rails#43920]
Hi all, 

I tried steps below on both 6.1.4.3 ( which works fine ) , and 7.0.0 ( breaking). 

The issue seems to be that `Rails.application.config.assets` is not being set for the dummy app automatically generated with engine.

### Steps to reproduce
```bash
rails plugin new my_engine --mountable 
cd my_engine
(remove TODOs from gemfile)
rails g controller Landing index
```

### Expected behavior
`rails g model User name` , `rails g controller Landing index` to work  

### Actual behavior
`undefined method `assets' for #<Rails::Application::Configuration @root=<Pathname:..../my_engine/test/dummy> ` ( edited for conciseness)

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.0

Many thanks

**Comment by ceritium** [comment]
Hi @muriloime, I think that it is because of this PR https://github.com/rails/rails/pull/43261.

You can fix it by adding `gem "sprockets-rails"` to the Gemfile.

**Comment by oyenmwen** [comment]
> Hi @muriloime, I think that it is because of this PR #43261.
> 
> You can fix it by adding `gem "sprockets-rails"` to the Gemfile.

thank you, I thought I was going crazy 😵‍💫
