### ISSUE TITLE
Rails.env == "development" when starting system tests

### ISSUE THREAD

**Issue by renchap** [rails/rails#43937]
When launching system tests, `Rails.env == "development"` after launching the tests, but is correctly `test` in the test themselves.

This is breaking thinks like the `dotenv-rails` gem, due to the following:
- `rails test:system` is started
- App is loaded, `Rails.env == "development"`, so `dotenv-rails` loads the env variables for `development`, and those are added to the process's `ENV` variable
- The main process then launches the tests's process, which inherits its parent's `ENV`
- `dotenv-rails` load the env variables for `test`
- But is some variables were set for `development` but dont have a value in `test`, they are still defined in the tests

### Steps to reproduce

- Create a new Rails 7 application
- Add `puts "Rails.env: #{Rails.env}"` to `config/application.rb` on line 7 (after the `Bundler.require` line)
- Run system tests: `rails test:system`

### Expected behavior
`Rails.env` should be `test`, as it is in Rails 6.1 and when running `rails test`

### Actual behavior
`Rails.env` is `development`

### System configuration
**Rails version**:
7.0.0
**Ruby version**:
3.0.3

**Comment by renchap** [comment]
I am not sure if this is related, but we are seeing another behaviour changes regarding ENV variables and tests:

In `test/test_helper.rb` we had the following:

```
require File.expand_path('../config/environment', __dir__)
require 'rails/test_help'

ENV['MYVAR'] = 'something'

class ActiveSupport::TestCase
  fixtures :all
 …
end
```

And in fixtures, we were using `ENV['MYVAR']`.

Starting with Rails 7, the ENV variable is undefined when loading the fixtures.

If `ENV['MYVAR'] = 'something'` is moved before loading `config/environment` then it is properly defined.

**Comment by fredplante** [comment]
I confirm I have the same issue. I'm using dotenv-rails as well.

When launching system tests using `rails test:system` I have the same error.
If lauching using `rails test test/system/foo_test.rb` it uses the correct database.

**Comment by rafaelfranca** [comment]
Since you have a way to reproduce can you check what changed this behavior in Rails using git bisect?

**Comment by renchap** [comment]
I made a quick script that creates a new rails app and checks `Rails.env` after the bundle load in `config/application.rb` and used it to run a bisection.

The culprit seems to be #41298 with #41314 as a related commit.

cc @etiennebarrie

**Comment by etiennebarrie** [comment]
Since #41132 we create a fork to run the tests, which results in the app being loaded twice, and since #41298 like you mentioned, we don't automatically set `RAILS_ENV` to `"test"` for the tasks `default`, `test`, and those starting with `test:` like `test:system`, so this bug also applies to `test:models` .

I really think we should keep #41298 because it's pretty unclean to change the environment behind your back while loading a framework/library.

As a workaround, you can add a similar piece of code at the top of your Rakefile to get the same result:

```ruby
if Rake.application.top_level_tasks.grep(/^(default$|test(:|$))/).any?
  ENV["RAILS_ENV"] ||= Rake.application.options.show_tasks ? "development" : "test"
end
```

---

> Starting with Rails 7, the ENV variable is undefined when loading the fixtures.

I can't reproduce this. With a `bin/rails g scaffold account name`, then I add this:

<details><summary>Diff</summary>

```diff
diff --git i/config/application.rb w/config/application.rb
index 6a7dbb5..471ae9f 100644
--- i/config/application.rb
+++ w/config/application.rb
@@ -6,6 +6,8 @@
 # you've limited to :test, :development, or :production.
 Bundler.require(*Rails.groups)
 
+p rails_env: Rails.env
+
 module RailsApp
   class Application < Rails::Application
     # Initialize configuration defaults for originally generated Rails version.
diff --git i/test/fixtures/accounts.yml w/test/fixtures/accounts.yml
index 7d41224..d99cd91 100644
--- i/test/fixtures/accounts.yml
+++ w/test/fixtures/accounts.yml
@@ -1,7 +1,7 @@
 # Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
 
 one:
-  name: MyString
+  name: MyString <%= ENV["MYVAR"] %>
 
 two:
   name: MyString
diff --git i/test/models/account_test.rb w/test/models/account_test.rb
index b6de6a1..8ebc600 100644
--- i/test/models/account_test.rb
+++ w/test/models/account_test.rb
@@ -1,7 +1,7 @@
 require "test_helper"
 
 class AccountTest < ActiveSupport::TestCase
-  # test "the truth" do
-  #   assert true
-  # end
+  test "fixtures use the env var" do
+    assert_equal "MyString something", accounts(:one).name
+  end
 end
diff --git i/test/test_helper.rb w/test/test_helper.rb
index d713e37..79ce562 100644
--- i/test/test_helper.rb
+++ w/test/test_helper.rb
@@ -2,6 +2,8 @@
 require_relative "../config/environment"
 require "rails/test_help"
 
+ENV["MYVAR"] = "something"
+
 class ActiveSupport::TestCase
   # Run tests in parallel with specified workers
   parallelize(workers: :number_of_processors)
```
</details>

And I run `bin/rails test:models`, I see that the app boots in development, then the fork in test, but the fixture uses the environment variable as expected. Running rails `db:fixtures:load` does not use the environment variable but that's expected since it loads the fixtures in development, without loading `test/test_helper.rb`:

```
$ bin/rails db:fixtures:load
{:rails_env=>"development"}
$ bin/rails runner 'puts Account.pluck(:name)'
{:rails_env=>"development"}
MyString
MyString
```

Same with `RAILS_ENV=test`, the test helper is not loaded for this:

```
$ RAILS_ENV=test bin/rails db:fixtures:load
{:rails_env=>"test"}                                 
$ bin/rails runner -e test 'puts Account.pluck(:name)'                                                                                                                                                                                               
{:rails_env=>"test"}                                 
MyString
MyString
```

But even then, running the tests, then running that again, the fixtures have the environment variable included.

Something I noticed with your setup though:

> In `test/test_helper.rb` we had the following:
> 
> ```ruby
> require File.expand_path('../config/environment', __dir__)
> ```

Since Rails 5.1.5 there is a line that sets the `RAILS_ENV` at the beginning of `test/test_helper.rb`:

 ```ruby
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../config/environment', __dir__)
```

But even removing it on my machine, I still get the fixture loaded with the environment variable, so that's not the issue.

**Comment by etiennebarrie** [comment]
I added https://github.com/bkeepers/dotenv/pull/441 to fix dotenv-rails to set the environment when using Rake, but I also thought about it more and created #44106 here so that we don't do the double boot and fork if you use `rails test:system`, only if you use `rake test:system`.

**Comment by artemave** [comment]
Eventually arrived here after hours of head scratching. For those who can't wait for two years while this makes it through the pipes, here's a workaround that worked for me:

Append this code to the `config/boot.rb`:
```ruby
require_relative '../lib/rails/command/test_command' if [nil, 'test'].include?(ENV['RAILS_ENV'])
```

And then monkey patch rails test command (`lib/rails/command/test_command.rb`):
```ruby
require 'rails/commands/test/test_command'

module Rails
  module Command
    class TestCommand < Base
      %i[models helpers channels controllers mailers integration jobs mailboxes system].each do |name|
        define_method(name) do |*|
          self.args = ["test/#{name}"]
          perform
        end
      end
    end
  end
end
```

**Comment by etiennebarrie** [comment]
I think the first snippet from https://github.com/rails/rails/issues/43937#issuecomment-1007288285 makes more sense. It's what was happening before, and it doesn't involve patching Rails. You just set the `RAILS_ENV` to test if the rake task is `default` or starts with `test` or `test:` (unless you're just listing the tasks with `rake -T`/`-D`/`-W` for some reason).

**Comment by artemave** [comment]
> I think the first snippet from [#43937 (comment)](https://github.com/rails/rails/issues/43937#issuecomment-1007288285) makes more sense. It's what was happening before, and it doesn't involve patching Rails. You just set the `RAILS_ENV` to test if the rake task is `default` or starts with `test` or `test:` (unless you're just listing the tasks with `rake -T`/`-D`/`-W` for some reason).

There's another problem that this fix does not address (but the [above](https://github.com/rails/rails/issues/43937#issuecomment-1099190349) one does): the application loads twice. Once in the current process and once more when falling through to the test rake task:
https://github.com/rails/rails/blob/c9e5057de4be7e0f4365ff9c2d411cffc39c3746/railties/lib/rails/test_unit/runner.rb#L35

Double load means twice as long startup time. Startup time is important.

**Comment by etiennebarrie** [comment]
Yeah I don't disagree. I should have thought of the solution I found in https://github.com/rails/rails/pull/44106 in the first place.
