### ISSUE TITLE
I think X-Download-Options is Unnecessary in Rails7

### ISSUE THREAD

**Issue by kossy0701** [rails/rails#43948]
## Summary

Thanks to all the contributors.

Currently, the default HTTP Request Header includes X-Download-Options, which is the one used by IE. (ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers)
Rails 7 contains a lot of changes that are supposed to make IE unsupported, and I think it's not necessary to leave X-Download-Options as the default as well.

Since default_headers can be set in 'config/environments/**. rb', I think you only need to add X-Download-Options for applications that need to support IE.

## Change Proposal

https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/railtie.rb#L34

```
    config.action_dispatch.default_headers = {
      "X-Frame-Options" => "SAMEORIGIN",
      "X-XSS-Protection" => "1; mode=block",
      "X-Content-Type-Options" => "nosniff",
  -   "X-Download-Options" => "noopen",
      "X-Permitted-Cross-Domain-Policies" => "none",
      "Referrer-Policy" => "strict-origin-when-cross-origin"
    }
```

and fix [this test case](https://github.com/rails/rails/blob/main/actionpack/test/dispatch/response_test.rb#L336)

and some documents need to update.

**Comment by ghiculescu** [comment]
Thanks for the issue, we prefer to discuss proposals in PRs (or use the [forum](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for discussion). Would you like to submit a PR?

**Comment by ghiculescu** [comment]
You could use https://github.com/rails/rails/pull/41769 for inspiration; you'd be adding a few more lines to `railties/lib/rails/application/configuration.rb` for Rails 7.1, updating the new framework defaults file, and updating relevant guides.

**Comment by keisuke-koshikawa** [comment]
Thanks to reply for this issue. And Thank you for letting me know the URL that will be helpful.

I` d like to submit a PR, Please Give me a few days 🙏

**Comment by kossy0701** [comment]
Thanks for reply. And Thank you for letting me know the URL that will be helpful.

I `d like to submit a PR, So Please give me a few days 🙏
