### ISSUE TITLE
api.rubyonrails.org/v6.1 redirects to edgeapi.rubyonrails.org

### ISSUE THREAD

**Issue by dmke** [rails/rails#43943]
Apologies in advance, if this is not the correct issue tracker for this kind of issue. Feel free to point me in the proper direction :)

### Steps to reproduce

I'm trying to read up on some 6.0/6.1 differences, but the documentation pages don't exist (any more).

These URLs redirect to https://edgeapi.rubyonrails.org:

- https://api.rubyonrails.org/v6.1/
- https://api.rubyonrails.org/v6.0/

### Expected behavior

They should either render the 6.x docs, redirect to a page containing those docs, or show a 404 page.

### Actual behavior

I'm redirected to the edge API docs.

However, these URLs don't perform a redirect, and indeed render the historical documentation:

- https://api.rubyonrails.org/v5.2/
- https://api.rubyonrails.org/v5.1/
- https://api.rubyonrails.org/v5.0/
- ...
- https://api.rubyonrails.org/v2.3/

### System configuration

Not relevant.

**Comment by ghiculescu** [comment]
fyi @rafaelfranca

**Comment by rafaelfranca** [comment]
Fixing it.

**Comment by rafaelfranca** [comment]
Fixed. Thank you for reporting.
