### ISSUE TITLE
Rails destroy scaffold/resource with namespace ends up with broken routes.rb

### ISSUE THREAD

**Issue by edwinlunando** [rails/rails#43950]
### Steps to reproduce
Install the rails 7.0.0 gem in any way and start adding new scaffolds/resources and destroy a scaffold/resource with a namespace.

```
gem install rails
rails new blog
cd blog
bin/rails g resource blog/post
bin/rails g resource blog/comment
bin/rails d resource blog/comment
```

I end up with a broken `routes.rb`. Here is the final content. 
```
Rails.application.routes.draw do
    resources :post
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
```

It gave this error when I tried to run `rails s`

```
syntax error, unexpected `end', expecting end-of-input
```

I take a look at the rails route generator code, it seems https://github.com/rails/rails/commit/106e20d48134044e6a8473e01a4636b22eacedb4 might be the trigger. @jonathanhefner what do you think? I tried the same steps with 6.1.4.4 the final content of `routes.rb` is correct.

### Expected behavior
I expect the `routes.rb` file is at least have no syntax error and the resource route is deleted cleanly.

### Actual behavior
What's happened instead, the namespace got deleted but the `end` statement is still there. 

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.3

**Comment by strobilomyces** [comment]
Confirmed (also in rails/main).

**Comment by excid3** [comment]
I noticed this today too.

**Comment by condef5** [comment]
Hi @jonathanhefner, do you mind if I start working on this :`)` ?
