### ISSUE TITLE
Inaccessible colour scheme for code examples in the Guides

### ISSUE THREAD

**Issue by cpjmcquillan** [rails/rails#43969]
I'm not sure if this is a recent regression, or if I have only just noticed it, but the code examples in the guides are very difficult to read (and I have no problems with my vision).

### Steps to reproduce
1. Visit the [Rails guides](https://guides.rubyonrails.org/getting_started.html)
2. Try to read the code examples

### Expected behavior
The colour scheme should be accessible, with sufficient contrast between text and background.

<details>
<summary>Edge guides</summary>

[Edge guides](https://edgeguides.rubyonrails.org/getting_started.html)

<img width="660" alt="image" src="https://user-images.githubusercontent.com/25187547/147091958-46715293-0a18-4610-80a5-0af9783686c5.png">

</details>

### Actual behavior
The colour scheme is inaccessible and code examples are very difficult to read.

<details>
<summary>Rails guides</summary>

[Rails guides](https://guides.rubyonrails.org/getting_started.html)

<img width="684" alt="image" src="https://user-images.githubusercontent.com/25187547/147091380-af37b501-1f94-4a0e-b896-334b66500964.png">

</details>

### Browser
Safari Version 15.2 (17612.3.6.1.6)

**Comment by ghiculescu** [comment]
Dark Mode recently got added to the guides https://github.com/rails/rails/pull/41987

It seems like it's enabled in one of your screenshots and disabled in the other? Is the feedback about the presence of dark mode or something more specific?

In any case it'd be great to see a PR with suggested improvements <3

**Comment by cpjmcquillan** [comment]
I'm not sure exactly what has changed in the last 19 days, but I'm no longer experiencing this issue. 

The Rails guide https://guides.rubyonrails.org now respects my system dark mode setting and the correct styles are applied.
