### ISSUE TITLE
rails new installs turbo-rails 7.1.1 instead of 1.0

### ISSUE THREAD

**Issue by DavidColby** [rails/rails#43962]
### Steps to reproduce
Creating a new Rails 7 application with turbo installed adds an out of date version of turbo-rails due to an [erroneous version](https://github.com/hotwired/turbo-rails/commit/31e19cb4b781d186bc31edaa4035b2e13a19fc3c) release in November. The erroneous release version number is 7.1.1. The actual latest release is 1.0.

Reproduce with:
```bash
rails new my_new_app
```

Check Gemfile.lock and see `turbo-rails (7.1.1)`

### Expected behavior
The latest version of `turbo-rails` (1.0, at the time of this report) should be installed when `rails new` is run.

### Actual behavior
`turbo-rails` installs version 7.1.1, a version that is several releases behind the the current 1.0 release.

I'm not sure if this is just a me problem — perhaps there's some odd bundler caching behavior going on?

It feels like it would be appropriate to pin turbo-rails with `gem "turbo-rails", "~> 1.0"` which was released alongside Rails 7 and is likely to be the latest major version for quite some time. This change locally resolves the issue for me and installs turbo-rails 1.0 during a fresh Rails install as expected.

Happy to PR that if there's actually an issue here.

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.2

**Comment by ghiculescu** [comment]
Version 7.1.1 has been yanked from https://rubygems.org/gems/turbo-rails

It's possible that bundler has a copy cached locally for you. Could you try `gem uninstall turbo-rails` (uninstall all versions) and then try again?

**Comment by ghiculescu** [comment]
See also the discussion @ https://discuss.hotwired.dev/t/fyi-turbo-rails-gem-version-7-1-1-was-yanked/3452

**Comment by DavidColby** [comment]
@ghiculescu That did it, had it cached locally, all good now. Thanks!
