### ISSUE TITLE
Blank values for timestamp with timezone causes NoMethodError getutc

### ISSUE THREAD

**Issue by davetron5000** [rails/rails#43961]
### Steps to reproduce

1. Use Postgres and configure `TIMESTAMP WITH TIME ZONE` for dates:
   ```ruby
   # config/initializers/postgres.rb
   require "active_record/connection_adapters/postgresql_adapter"
   ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.datetime_type = :timestamptz
   ```
   This will tell Active Record to treat datetime values as `timestamptz` which is not the default
1. Create a table that has a datetime, e.g. `t.datetime :happened_at`
1. Attempt to insert into this table using the empty string for the value of (e.g.) `happened_at`:

   ```ruby
   Widget.create!(happened_at: "")
   ```

This can happen when using strong params passed into an Active Record, since blank values from the front end tend to be blank strings and not `nil`

I will work on a more obviously executable app, but hopefully others have this and someone can help me with the solution.

#### Test Case

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "7.0.0"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

require "active_record/connection_adapters/postgresql_adapter"
ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.datetime_type = :timestamptz


# You will need actual Postgres to do this,
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "xxx_test", host: "db", username: "postgres", password: "postgres")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.datetime :happened_at, null: true
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class BugTest < Minitest::Test
  def setup
    Post.destroy_all
  end
  def test_nil
    Post.create!(happened_at: nil)
    assert_equal 1, Post.count
  end

  def test_string_with_date
    Post.create!(happened_at: "2021-01-01")
    assert_equal 1, Post.count
  end

  def test_blank_string
    Post.create!(happened_at: "")
    assert_equal 1, Post.count
  end
end
```

### Expected behavior

In previous versions of Rails, this would be converted to nil in this code:

https://github.com/rails/rails/blob/bcd76f101e6f7998b51e18b1335df1759d9cbb7d/activemodel/lib/active_model/type/date_time.rb#L17-L22

### Actual behavior

Because of the change in #41084 this code is no longer called, and we get an error:

```
undefined method `getutc' for nil:NilClass
```

https://github.com/rails/rails/blob/bcd76f101e6f7998b51e18b1335df1759d9cbb7d/activerecord/lib/active_record/connection_adapters/postgresql/oid/timestamp_with_time_zone.rb#L12-L24

Essentially, any Active Record that uses `timestamptz` cannot be given a blank string and expect it to be coerced to `nil`.

I believe the change that needs to be made is:

```ruby
module ActiveRecord
  module ConnectionAdapters
    module PostgreSQL
      module OID # :nodoc:
        class TimestampWithTimeZone < DateTime # :nodoc:
          def type
            real_type_unless_aliased(:timestamptz)
          end

          def cast_value(value)
            time = super
            return if value.blank? # <--------------------
            return time if time.is_a?(ActiveSupport::TimeWithZone)

            # While in UTC mode, the PG gem may not return times back in "UTC" even if they were provided to Postgres in UTC.
            # We prefer times always in UTC, so here we convert back.
            if is_utc?
              time.getutc
            else
              time.getlocal
            end
          end
        end
      end
    end
  end
end
```

This change, locally, works for me, but obviously that is not enough to get this change into Rails. Would love to know a) are others experiencing this and b) any help in how to create a test inside Rails for this that fails in this case.

### System configuration
**Rails version**: 7.0.0
**Ruby version**:
```
# ruby --version
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
```

**Comment by ghiculescu** [comment]
Thanks for the issue, I can work on a fix.
