### ISSUE TITLE
Rails cashes with Ruby 3.1.0 release

### ISSUE THREAD

**Issue by erik-brueggemann** [rails/rails#43998]
### Steps to reproduce

```ruby
ruby -v
# => ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]

rails new test-app
cd test-app
rails s
```

### Expected behavior
Create a new rails app and serve it.

### Actual behavior
Crashes during the project creation process:
```bash
...
         run  bundle binstubs bundler
       rails  importmap:install
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
rails aborted!
Rails::Engine is abstract, you cannot instantiate it directly.
/Users/erik/Code/test-app/config/application.rb:3:in `<main>'
/Users/erik/Code/test-app/Rakefile:4:in `<main>'
bin/rails:4:in `<main>'
...
```

Furthermore, `test-app` gets generated, but cannot be served:
```bash
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
[WARNING] Could not load command "rails/commands/server/server_command". Error: Rails::Engine is abstract, you cannot instantiate it directly..
/Users/erik/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/railtie.rb:246:in `initialize'
/Users/erik/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/railtie.rb:184:in `new'
/Users/erik/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/railtie.rb:184:in `instance'
/Users/erik/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/railtie.rb:223:in `method_missing'
/Users/erik/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.0/lib/active_support/descendants_tracker.rb:90:in `descendants'
/Users/erik/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:923:in `block in define_callbacks'
/Users/erik/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:920:in `each'
/Users/erik/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:920:in `define_callbacks'
/Users/erik/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/engine.rb:427:in `<class:Engine>'
/Users/erik/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/engine.rb:349:in `<module:Rails>'
/Users/erik/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/railties-7.0.0/lib/rails/engine.rb:11:in `<main>'
... 
```

### System configuration
**Rails version**: 7.0.0

**Ruby version**: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]

**Comment by fatkodima** [comment]
This is already fixed on `main` - https://github.com/rails/rails/pull/43951.
It was expected for rails 7.0.1 to be released before ruby 3.1.0. See https://bugs.ruby-lang.org/issues/14394#note-36.

cc @byroot

**Comment by byroot** [comment]
Yes sorry about that one, please use the `7-0-stable` branch for now.

**Comment by rogeralmeida** [comment]
What about Rails 6.1? 🤔 
I'm getting the same error with Rails 6.1
```shell
$ ruby --version
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [aarch64-linux]
```

```shell
$ rails --version
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Rails 6.1.4.4
```
Note that the command still works, but it is annoying that this error message pops up whenever I do `rails...` or `rake...`

**Comment by adamniedzielski** [comment]
@rogeralmeida I think that the topic of this issue and the reason for Rails 7.0.0 crashing is

```
[WARNING] Could not load command "rails/commands/server/server_command". Error: Rails::Engine is abstract, you cannot instantiate it directly..
```

```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
```

appears right next to it, but I believe that it's unrelated. It looks like a depreciation warning introduced in Ruby 3.1.0. According to https://guides.rubyonrails.org/maintenance_policy.html Rails 6.1.x receives only security fixes. Therefore, if the deprecated code is inside Rails (and not in one of Rails dependencies) I don't think that it will ever get fixed 🙂

**Comment by dwightwatson** [comment]
Surely Ruby 3.1.x support should be backported to Rails 6.1.x too - Rails 7.x has been out for 13 days.

**Comment by adamniedzielski** [comment]
@dwightwatson based on what @rogeralmeida wrote, Rails 6.1 works perfectly fine with Ruby 3.1. It's just a warning. You can silence it 😉

**Comment by adamniedzielski** [comment]
Here's the fix for the deprecation warning - https://github.com/rails/thor/pull/761. As the Rails dependency on Thor is pretty relaxed (https://github.com/rails/rails/blob/df475877efdcf74d7524f734ab8ad1d4704fd187/railties/railties.gemspec#L44) it should be possible to get rid of the deprecation warning without a new release of Rails 6.1.x 🙂

**Comment by ghiculescu** [comment]
https://gist.github.com/yahonda/2776d8d7b6ea7045359f38c10449937b this gist outlines how to use Ruby 3.1 with various Rails versions (thanks @yahonda ❤️ )

**Comment by diek** [comment]
I am having the same issue, and I thought I could resolve just by using a rails 6.1.0. When I ran new it did the following.
`Fetching rails 7.0.0
Installing rails 7.0.0`
I have used rails in the past with no issue, it has been a few years. Is this behavior, rails updating itself, by design?

**Comment by CodingItWrong** [comment]
@diek I think the `rails` command runs the latest version of the `rails` gem installed within your current Ruby version. To create a new Rails app using a specific version of Rails, do this:

```
$ gem install rails -v 6.1.4.4
$ rails _6.1.4.4_ new …
```

Then, within the project, you can just run `rails` and I think it'll use the bundled version.

**Comment by diek** [comment]
@CodingItWrong thanks for the insight. I learned rails in school and even though I took a different path into Python/Django land, rails remains in my heart. I could easily switch if an opportunity opened. 

I appreciate that Open Source can be daunting, and often thankless, but the keepers of rails need to keep newcomers in mind. Imagine a new learner beginning to learn rails 7, it is supposed to be a 'stable' release, it would be a complete disaster. I consider myself an experienced programmer and I was completely baffled

**Comment by samwinslow** [comment]
Using the `main` branch of Rails resolved this for me. One line in my Gemfile was all that was needed: `gem "rails", github: "rails/rails", branch: "main"`. Spell checker warning appears unrelated.

I can understand folks may want to be on a stable rather than edge release... Wonder what it would take to publish a patch release or pre-release (7.0.0.x)?

**Comment by akpatternica** [comment]
@dhh Please release 7.0.1!:)

**Comment by nnhansg** [comment]
This issue is from Ruby 3.1.0. If you use ruby 3.0.3, it will work ok for Rails 7.0.0.

**Comment by akpatternica** [comment]
Yes, but all want to use 3.1.0 and also it is a title of the issue.

**Comment by gerrywastaken** [comment]
> This issue is from Ruby 3.1.0. If you use ruby 3.0.3, it will work ok for Rails 7.0.0.

The primary features of Ruby 3.1 are [speed improvments for Rails apps](https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/) so this is not a great solution.

**Comment by darkBuddha** [comment]
Any update on 7.0.1 ETA? Thanks!

**Comment by rafaelfranca** [comment]
Yes. ETA is this week. The people that releases rails took the last two weeks of the year as vacation, because you know they are people and need to rest. As Ruby 3.1 was released in those two weeks we will have to wait they to came back to release a new version.

**Comment by adamniedzielski** [comment]
Great answer @rafaelfranca 💚 you're amazing and your hard work means a lot to many many people!

And to everybody who thinks that they're "contributing", because they leave a comment pushing for a new release - you're the reason why maintainers quit open source and why we can't have nice things 😠

**Comment by darkBuddha** [comment]
Just asking, answering with 1 sentence doesn't hurt...

**Comment by darkBuddha** [comment]
> And to everybody who thinks that they're "contributing", because they leave a comment pushing for a new release - you're the reason why maintainers quit open source and why we can't have nice things 😠

Who thinks that asking for a release date is contributing? Weird comment

**Comment by rafaelfranca** [comment]
7-0-stable should be ready for a release (which I plan to do tomorrow). If anyone want to help, you can try to use that branch and report if it is still crashing.

**Comment by aaronmallen** [comment]
> 7-0-stable should be ready for a release (which I plan to do tomorrow). If anyone want to help, you can try to use that branch and report if it is still crashing.

I have used 7-0-stable and didn't run into the issue

**Comment by larouxn** [comment]
> 7-0-stable should be ready for a release (which I plan to do tomorrow). If anyone want to help, you can try to use that branch and report if it is still crashing.

I confirmed a week or so back with my little test app, [Carrotgram](https://github.com/larouxn/carrotgram), that Rails on `7-0-stable` + Ruby 3.1.0 no longer crashes. https://github.com/larouxn/carrotgram/pull/329

**Comment by erik-brueggemann** [comment]
> 7-0-stable should be ready for a release (which I plan to do tomorrow). If anyone want to help, you can try to use that branch and report if it is still crashing.

Just ran a test on `7-0-stable` and it works fine for me as well 👍

**Comment by darkBuddha** [comment]
I use it since 3 days, w/o any issues.

**Comment by LoranKloeze** [comment]
I also tested `7-0-stable` and it works fine with `3.1.0` now 🎉

**Comment by rafaelfranca** [comment]
7.0.1 released https://rubyonrails.org/2022/1/6/Rails-7-0-1-has-been-released

**Comment by agrberg** [comment]
Correct me if I'm wrong but I don't believe Rails 6 will work with Ruby 3.1 until [this commit](https://github.com/rails/rails/commit/5dd292f5511fedd91833dc8482baf696cb821af6#diff-425e951ef3a6a24b3456b697a383b1d73b4fbdfd7e2ddb8db70bf615ff21f920) is ported to the 6.1 branch or [this issue](https://github.com/mikel/mail/pull/1439) with [mail](https://github.com/mikel/mail/) is resolved.

**Comment by adamniedzielski** [comment]
@agrberg what breaks if you add the missing gems to the Gemfile of your Rails 6 application yourself?

**Comment by agrberg** [comment]
It works (after I remove the other gems with Ruby 3.1 problems 😅) so it's a decent work around.
