### ISSUE TITLE
Getting started guide broken for 7.0.0

### ISSUE THREAD

**Issue by pb82** [rails/rails#44003]
### Steps to reproduce

Follow the `Getting started with Rails` guide guide from [here](https://guides.rubyonrails.org/) until the chapter [Deleting an article](https://guides.rubyonrails.org/getting_started.html#deleting-an-article).

### Expected behavior

The described way of deleting an article does no longer work. I'm only starting with Rails, but it looks like the guide needs to be updated for Hotwire.

### Actual behavior

The destroy link does not delete the article and instead just reloads the page.

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.3

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/43974 will resolve this.

**Comment by kamipo** [comment]
Fixed by #43974.
