### ISSUE TITLE
Rails 7 is not clearing query cache

### ISSUE THREAD

**Issue by JasonBarnabe** [rails/rails#44005]
### Steps to reproduce

After changing my app to `config.load_defaults 7.0`, Rails is seemingly caching SQL run with `ActiveRecord#connection#select_value`.

The test is asserting that a record is inserted when an action is performed on the site (`insert` is run from a ActiveRecord#connection#execute). Looking at the test log, the insert *is* indeed happening when the test runs, yet `select_value` doesn't see it. Test passed in Rails 6.1, as well as 7.0 with `config.load_defaults 6.1`.

Failing test: https://github.com/JasonBarnabe/greasyfork/blob/a41a00a375bb70df11b4b24d7c9aa096b74b5079/test/system/scripts/install_test.rb#L7
CircleCI result: https://app.circleci.com/pipelines/github/JasonBarnabe/greasyfork/650/workflows/101728fe-c4e2-4a67-a5ad-6bc1db438ba5/jobs/652

If I add a breakpoint and run the `select` query with a minor change (e.g. whitespace), then I get expected results.

```
(byebug) Script.connection.select_value('select count(*) from daily_install_counts')
0
(byebug) Script.connection.select_value('select  count(*) from daily_install_counts')
1
```

So it seems that perhaps the result is getting cached by the query string? I've been unable to create a minimal test case that shows the behaviour.

### System configuration
**Rails version**: 7.0.0.0
**Ruby version**: 3.0.3p157
**mysql2**: 0.5.3
**minitest**: 5.15.0

**Comment by JasonBarnabe** [comment]
With `config.load_defaults 6.1`, around [here](https://github.com/JasonBarnabe/greasyfork/blob/2e9b8acf6526006bf440e896e07b48101ac986f0/test/system/scripts/install_test.rb#L9-L10) (where the request happens), `ActiveRecord::ConnectionAdapters::QueryCache.clear_query_cache` is called with this stacktrace:

```
--> #0  ActiveRecord::ConnectionAdapters::QueryCache.clear_query_cache at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.0/lib/active_record/connection_adapters/abstract/query_cache.rb:92
    #1  ActiveRecord::ConnectionAdapters::QueryCache.disable_query_cache! at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.0/lib/active_record/connection_adapters/abstract/query_cache.rb:73
    #2  ActiveRecord::ConnectionAdapters::QueryCache::ConnectionPoolConfiguration.disable_query_cache! at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.0/lib/active_record/connection_adapters/abstract/query_cache.rb:42
    #3  block in #<Class:ActiveRecord::QueryCache>.block in complete(pools#Array) at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.0/lib/active_record/query_cache.rb:43
    ͱ-- #4  Array.each at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.0/lib/active_record/query_cache.rb:43
    #5  #<Class:ActiveRecord::QueryCache>.complete(pools#Array) at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-7.0.0/lib/active_record/query_cache.rb:43
    #6  ActiveSupport::ExecutionWrapper::CompleteHook.before(target##<Class:0x00005562621546f8>) at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/execution_wrapper.rb:37
    #7  block in ActiveSupport::Callbacks::CallTemplate::ObjectCall.block in make_lambda at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:423
    #8  block (2 levels) in #<Class:ActiveSupport::Callbacks::Filters::Before>.block (2 levels) in halting(callback_sequence#ActiveSupport::Callbacks::CallbackSequence, user_callback#Proc, halted_lambda#Proc, filter#ActiveSupport::ExecutionWrapper::CompleteHook, name#Symbol) at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:199
    #9  block (2 levels) in ActiveSupport::Callbacks::CallbackChain.block (2 levels) in default_terminator at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:687
    ͱ-- #10 Kernel.catch(*args) at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:686
    #11 block in ActiveSupport::Callbacks::CallbackChain.block in default_terminator at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:686
    #12 block in #<Class:ActiveSupport::Callbacks::Filters::Before>.block in halting(callback_sequence#ActiveSupport::Callbacks::CallbackSequence, user_callback#Proc, halted_lambda#Proc, filter#ActiveSupport::ExecutionWrapper::CompleteHook, name#Symbol) at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:200
    #13 block in ActiveSupport::Callbacks::CallbackSequence.block in invoke_before(arg#ActiveSupport::Callbacks::Filters::Environment) at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:595
    ͱ-- #14 Array.each at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:595
    #15 ActiveSupport::Callbacks::CallbackSequence.invoke_before(arg#ActiveSupport::Callbacks::Filters::Environment) at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:595
    #16 ActiveSupport::Callbacks.run_callbacks(kind#Symbol) at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:106
    #17 ActiveSupport::ExecutionWrapper.complete at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/execution_wrapper.rb:147
    #18 ActiveSupport::ExecutionWrapper.complete! at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-7.0.0/lib/active_support/execution_wrapper.rb:141
    #19 block in ActionDispatch::Executor.block in call(env#Hash) at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/executor.rb:15
    #20 Rack::BodyProxy.close at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.3/lib/rack/body_proxy.rb:29
    #21 Puma::Request.handle_request(client#Puma::Client, lines#Puma::IOBuffer, requests#Integer) at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.5.2/lib/puma/request.rb:174
    #22 Puma::Server.process_client(client#Puma::Client, buffer#Puma::IOBuffer) at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.5.2/lib/puma/server.rb:447
    #23 block in Puma::ThreadPool.block in spawn_thread at /home/jason/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/puma-5.5.2/lib/puma/thread_pool.rb:147
```

With `config.load_defaults 7.0`, `ActiveRecord::ConnectionAdapters::QueryCache.clear_query_cache` is not called when doing the request.

**Comment by JasonBarnabe** [comment]
This may be because my controller action *only* does DB updates with `ActiveRecord#connection#execute`. If I add a dummy update through normal ActiveRecord stuff then the expected results return.

Not sure if this is expected behaviour, but seems like if so then it should at least have some mention in the changelog.

**Comment by ghiculescu** [comment]
What's the value of `ActiveRecord.legacy_connection_handling` in both cases?

> Looking further, `ActiveRecord::QueryCache.complete` is getting called with an empty Array after the request with `config.load_defaults 7.0`, but with a non-empty Array with `6.1`.

It looks like the array will be whatever https://github.com/rails/rails/blob/main/activerecord/lib/active_record/query_cache.rb#L39 returns.

**Comment by JasonBarnabe** [comment]
`ActiveRecord.legacy_connection_handling` is `false` both when `config.load_defaults` is `6.1` (without the bug) and `7.0` (with the bug).

**Comment by JasonBarnabe** [comment]
The pertinent difference between `load_defaults` `6.1` and `7.0` is `active_support.executor_around_test_case`. With:

```
config.load_defaults 7.0
config.active_support.executor_around_test_case = false
```
the problem no longer occurs.

So I guess my question would be: is it expected behaviour for `ActiveRecord#connection#execute` to not clear the query cache?

**Comment by ghiculescu** [comment]
Hmm, I suspect that means the bug is here https://github.com/rails/rails/blob/a4d685b2842d91cb702259c07c50c2623288c714/activesupport/lib/active_support/railtie.rb#L51

**Comment by akpatternica** [comment]
Looks like it by design cause

3.13.16 config.active_support.executor_around_test_case

Configure the test suite to call Rails.application.executor.wrap around test cases. This makes test cases behave closer to an actual request or job. Several features that are normally disabled in test, such as Active Record query cache and asynchronous queries will then be enabled.

**Comment by JasonBarnabe** [comment]
To be clear, in my case:

1. The test does a select on the DB
2. The test fires a request, which updates the DB using `connection#execute`
3. The test does the same select on the DB again, expecting to see the change from 2.

So I understand that `executor_around_test_case` enables the query cache for tests, but should the cache not be cleared when

1. A `connection#execute` runs, as this may be a `INSERT` or `UPDATE` or whatever, and/or:
2. Any time a system test performs a request, as it's expected that the cache be cleared after each request

**Comment by morgoth** [comment]
I have exactly the same issue. It can be reproduced in the Rails app test by something like:
```ruby
pp User.pluck(:name)
ActiveRecord::Base.connection.execute "INSERT INTO users (name) VALUES (1)"
pp User.pluck(:name)
```
Both `pluck` return empty array. When I turn `config.active_support.executor_around_test_case = false`
it works as expected, thus the second pluck returns inserted value

@byroot Looks like https://github.com/rails/rails/pull/43550 doesn't work as expected.

**Comment by ghiculescu** [comment]
Executable test case:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "rails/all"
require "minitest/autorun"
require "logger"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_support.executor_around_test_case = true
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.text :name
  end
end

class User < ActiveRecord::Base
end

class BugTest < ActiveSupport::TestCase
  def test_stuff
    assert_equal [], User.pluck(:name)
    ActiveRecord::Base.connection.execute "INSERT INTO users (name) VALUES (1)"
    assert_equal ["1"], User.pluck(:name)
  end
end
```

If you change line 28, the test passes.

**Comment by byroot** [comment]
Hum. Correct me if I'm wrong, but I'm pretty sure this would have been broken before, not in test because the cache wasn't enabled there, but in similar instances.

I actually had an instance like that in our app when I upgraded, I had to clear cache after the call to `execute`.

Maybe any use of raw `execute` should clear the cache ?

**Comment by ghiculescu** [comment]
Dug into it a bit, the issue is the query cache isn't enable at all when `executor_around_test_case = false`. Whereas when it's true, it gets enabled when `ActiveRecord::QueryCache.run` is called.

> Maybe any use of raw `execute` should clear the cache ?

This would fix the issue, but I think the real issue is if the query cache should be enabled in tests at all?

**Comment by byroot** [comment]
> I think the real issue is if the query cache should be enabled in tests at all?

I believe so yes. In your executable example, it's the assertion code that is broken by it and that's infortunate. But as I said previously, when I updated our app, I did catch a similar case in application code.

If you have some model code, or some service class that you unit test, having the query cache enabled make it behave much closer to how it would behave in production.

Does that make sense?

**Comment by ghiculescu** [comment]
It does, but I think we need to call this out in the release notes much more explicitly - it seems like this is the first time Rails will be using the query cache in tests.

**Comment by byroot** [comment]
It was pointed here at least https://github.com/rails/rails/pull/43550/files#diff-cb3cd7cbeee84c9ad3020d4a3aaa8e9d91def097aa5e46ef6fe7281b6e0d0f8aR50, I think I've noted else where but I don't quite remember.

**Comment by ghiculescu** [comment]
Haha, I guess everyone in this issue missed that (or I did at least).

What do you think about adding to https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-1-to-rails-7-0 ?

**Comment by byroot** [comment]
Sure. That definitely can't hurt.

**Comment by JasonBarnabe** [comment]
Note that the test case above is different than what was originally reported. The original issue involves a system test, where the request is the thing running the execute.

From the sounds of it, enabling the query cache is expected and desirable so that the test runs as production would. However with a system test it still seems the query cache should be cleared after a request is performed, as that's more production-like behavior.

**Comment by byroot** [comment]
> with a system test it still seems the query cache should be cleared after a request is performed

Yes, it should be cleared before and after the request for improved accuracy. If that's not the case it's a bug.

**Comment by fxn** [comment]
I believe I am hitting this.

I generated a vanilla Rails 7 application with a `User` model and wrote this test:

```ruby
class UserTest < ActiveSupport::TestCase
  test "INSERT with execute" do
    assert_difference "User.count", 1 do
      User.connection.execute("INSERT INTO users (name) VALUES ('John Smith')")
    end
  end
end
```

This test fails, and the reason is the second `User.count` hits the query cache.

If `execute` is not invalidating the cache, I think it should.

**Comment by byroot** [comment]
@fxn yeah, I meant to do it, but it requires a significant refactor of the MySQL2 adapter has it uses `execute` both internally and externally, and even for other adapters, they all have their own `execute` implementation, it's a bit of a mess.

In the meantime, the better method to use in your case is:

```ruby
class UserTest < ActiveSupport::TestCase
  test "INSERT with execute" do
    assert_difference "User.count", 1 do
      User.connection.insert("INSERT INTO users (name) VALUES ('John Smith')")
    end
  end
end
```

**Comment by fxn** [comment]
@byroot what would you recommend for other statements that may have side-effects? This application for example runs `REFRESH MATERIALIZED VIEW` with `execute`.

**Comment by fxn** [comment]
@byroot gotcha, thanks :).

This applications has 27 `execute` calls across the code base, and they run arbitrary SQL (that `INSERT` was just a simple way to reproduce). I am not familiar with the implementation of the query cache by as far as I can see this seems to affect only the `test` environment.

By now, I believe the most reasonable thing to do in my case is to set

```ruby
config.active_support.executor_around_test_case = false
```

and leave things as they are for now.

**Comment by fxn** [comment]
I mean

```ruby
p User.count # => 0
User.connection.execute("INSERT INTO users (name) VALUES ('John Smith')")
p User.count # => 1
```

this works as expected in Rails 7.

**Comment by fxn** [comment]
Ahhhh, wait, I need a request in place. Let me try in older versions of Rails.

**Comment by fxn** [comment]
Confirm, you were right, `execute` did not clear the cache before. This is really surprising. Both `insert` and `update` do.

**Comment by byroot** [comment]
Ok, so I've fixed `#execute` to flush the query cache. I'll followup to also fix `#exec_query`.

However I won't backport this change as it required a very major refactoring, that's way too tricky to attempt to backport.

**Comment by fxn** [comment]
❤️
