### ISSUE TITLE
Zeitwerk::NameError facing while deploying rails application

### ISSUE THREAD

**Issue by jaiathp** [rails/rails#44001]
### Steps to reproduce
bundle exec cap production deploy

### Expected behavior
Should not see this error

### Actual behavior

App 473617 output: Here1
App 473617 output: Error: The application encountered the following error: expected file /opt/sirius/sh_release_2/releases/20211226100208/lib/shr_autonotes_v2.rb to define constant ShrAutonotesV2, but didn't (Zeitwerk::NameError)
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:28:in `block in require'
App 473617 output:     <internal:kernel>:90:in `tap'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `cget'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:232:in `block (2 levels) in eager_load'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `ls'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:227:in `block in eager_load'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `synchronize'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `eager_load'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `each'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `eager_load_all'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/application/finisher.rb:79:in `block in <module:Finisher>'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/initializable.rb:32:in `instance_exec'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/initializable.rb:32:in `run'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/initializable.rb:61:in `block in run_initializers'
App 473617 output:     /opt/sirius/local/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
App 473617 output:     /opt/sirius/local/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 473617 output:     /opt/sirius/local/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 473617 output:     /opt/sirius/local/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 473617 output:     /opt/sirius/local/lib/ruby/3.0.0/tsort.rb:347:in `each'
App 473617 output:     /opt/sirius/local/lib/ruby/3.0.0/tsort.rb:347:in `call'
App 473617 output:     /opt/sirius/local/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
App 473617 output:     /opt/sirius/local/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
App 473617 output:     /opt/sirius/local/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/initializable.rb:60:in `run_initializers'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/application.rb:369:in `initialize!'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/railtie.rb:224:in `public_send'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/railties-7.0.0/lib/rails/railtie.rb:224:in `method_missing'
App 473617 output:     /opt/sirius/sh_release_2/releases/20211226100208/config/environment.rb:5:in `<top (required)>'
App 473617 output:     config.ru:3:in `require'
App 473617 output:     config.ru:3:in `block in <main>'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 473617 output:     /opt/sirius/sh_release_2/shared/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 473617 output:     config.ru:1:in `new'
App 473617 output:     config.ru:1:in `<main>'
App 473617 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
App 473617 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 473617 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 473617 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 473617 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 473617 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 473617 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2021-12-26 18:21:36.3479 405684/T8i age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/sirius/sh_release_2/current: The application encountered the following error: expected file /opt/sirius/sh_release_2/releases/20211226100208/lib/shr_autonotes_v2.rb to define constant ShrAutonotesV2, but didn't (Zeitwerk::NameError)
  Error ID: 0160ec3e
  Error details saved to: /tmp/passenger-error-ss0yG8.html

### System configuration
**Rails version**:
rails (7.0.0)

**Ruby version**:
3.0.0

**Comment by jaiathp** [comment]
These are the setting that i used application.rb
    config.eager_load = true
    config.eager_load_paths += %W(#{config.root}/app/lib)

**Comment by courtsimas** [comment]
what does the output of `bin/rails zeitwerk:check` from your terminal give you?

**Comment by jaiathp** [comment]
i dont know how to run this command. But i have managed to fix this issue by downgrading rails version to 6.2 and everything works fine.

**Comment by courtsimas** [comment]
You most likely have some misnamed class files and you’re not running in zeitwerk mode in 6.x. I’m 7, it’s the only way to load the files (defaults in rails from now on). That command i referenced you just run in terminal and it will check all the files in your rails app for compatibility. In the meantime you can safely close this issue, because zeitwerk name errors are not actually rails bugs.
