### ISSUE TITLE
Rails 6: server needs to be restarted everytime I make a new entry in the database (I dynamically add new enteries to the routes.rb)

### ISSUE THREAD

**Issue by faraznisar** [rails/rails#44013]
### Steps to reproduce

<----- sorry for not providing the code, not really sure how to reproduce it in your templates, but do not close the issue if the current information is not enough----->
I make a new entry in the database and I see the entry in the admin panel but when I visit the newly created route for that entry, I get a 404 in my production environment (route not found in the production.log) and a route not found in my local

```ruby
# Your reproduction script goes here
```
The route goes like this: 
  for city in City.pluck(:slug) do
    get "/#{city}",to: 'app#city'
  end
As you can see from the code above I am plucking the slug for all the entries in the database table and I have dynamic pages defined for the routes but it doesn't work
### Expected behavior

As I make a new entry in the database, I should be able to redirect to that route without any issues because I have what is needed already (the slug) and the page is dynamic based on the record in the database, I just fill in the information.
### Actual behavior

I make a new entry, try to visit the url and I get a route not found (once I restart the server the route works fine). My colleague tells me that if we disable caching, it might help because the routes are currently being cached.
### System configuration
**Rails version**:
 6.1.4.1
**Ruby version**:
2.6.7p197 (2021-04-05 revision 67941) [x64-mingw32]

Also, I am using MySQL - 'mysql2', '~> 0.5'

**Comment by dwightwatson** [comment]
I don't think this is expected behaviour - you should be using a wildcard route that points to `app#city` which then performs a lookup for the `City` model. Alternatively if you wanted to ensure the route only responded to slugs that exist you could look at adding a constraint to the route.

**Comment by flavorjones** [comment]
@faraznisar I hope the guidance provided by @dwightwatson above is helpful. Rails Routes automatically forward segments of the path to the Controller in the `params` hash. See https://guides.rubyonrails.org/routing.html#non-resourceful-routes for a short explanation with examples.
