### ISSUE TITLE
link_to with method :delete does not work with fresh rails 7 project

### ISSUE THREAD

**Issue by spksoft** [rails/rails#44017]
### Steps to reproduce

I am a new for Rail and I start learning by follow the guide page of https://guides.rubyonrails.org/getting_started.html
```ruby
1. Add destroy method by following step "7.5 Deleting an Article" on getting start page
2. Update app/views/articles/show.html.erb by adding 
`<li><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>`
3. Click destroy link on /articles/:id page
```

### Expected behavior
I should delete articles from db and redirect to root path

### Actual behavior
It does not delete everything and when I inspect by chrome dev tools it does not call /articles/:id with delete as I show in the attached image below
![image](https://user-images.githubusercontent.com/1377991/147589092-fc1b067d-d801-42b9-aee4-0d04aec72f14.png)
![image](https://user-images.githubusercontent.com/1377991/147589150-d0412639-c96d-45b0-992d-109fcf875058.png)

### System configuration
**Rails version**: Rails 7.0.0

**Ruby version**: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [-darwin21]

**Comment by ghiculescu** [comment]
Hi, thanks for the issue. The docs are a bit out of date, sorry about that. They'll be updated in the next release. See https://github.com/rails/rails/pull/43974

If you browse https://edgeguides.rubyonrails.org/getting_started.html it should work correctly with Rails 7 :)
