### ISSUE TITLE
why column query reutrn [FILTERED]

### ISSUE THREAD

**Issue by bill1997603** [rails/rails#44021]
### Steps to reproduce

```ruby
create_table "fields", force: :cascade do |t|
    t.string "name"
    t.string "identity_key"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end
```
```ruby
#<Field:0x00007ff56fe01728
 id: 3,
 name: "test",
 identity_key: "[FILTERED]",
 created_at: Tue, 28 Dec 2021 21:07:58.766659000 CST +08:00,
 updated_at: Tue, 28 Dec 2021 21:11:55.688326000 CST +08:00
>
```

### Expected behavior

create model column name is identity_key

### Actual behavior

user find or where query db return identity_key: "[FILTERED]", idont know why return this result.

### System configuration
**Rails version**:
7.0.0
**Ruby version**:
2.7.4

**Comment by jvelez1** [comment]
Maybe it is related to [this pr](https://github.com/rails/rails/pull/33756/files)

check if you added the key in `filter_parameters` config, in this file `config/application.rb`
or maybe in the model.

**Comment by bill1997603** [comment]
> Maybe it is related to [this pr](https://github.com/rails/rails/pull/33756/files)
> 
> check if you added the key in `filter_parameters` config, in this file `config/application.rb` or maybe in the model.

yeah！I found it，in this file `config/initializers/filter_parameter_logging.rb`
