### ISSUE TITLE
config.content_security_policy script_src and style_src are overwritten in railties

### ISSUE THREAD

**Issue by apoland** [rails/rails#44022]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"
require "rails/application_controller"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.content_security_policy do |policy|
    policy.default_src 'https://default.example.com'
    policy.font_src    'https://fonts.example.com'
    policy.img_src     'https://images.example.com'
    policy.object_src  'https://objects.example.com'
    policy.script_src  'https://scripts.example.com'
    policy.style_src   'https://styles.example.com'
    # Specify URI for violation reports
    # policy.report_uri "/csp-violation-report-endpoint"
  end

  routes.draw do
    get "/base" => "base#index"
    get "/app" => "app#index"
  end
end

class BaseController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render html: "<h1>Welcome to BaseController!</h1>"
  end
end

class AppController < Rails::ApplicationController
  include Rails.application.routes.url_helpers

  def index
    render html: "<h1>Welcome to ApplicationController!</h1>"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_base_script_src
    get "/base"
    assert last_response.headers['Content-Security-Policy'].include? 'https://scripts.example.com'
  end

  def test_base_style_src
    get "/base"
    assert last_response.headers['Content-Security-Policy'].include? 'https://styles.example.com'
  end

  def test_app_script_src
    get "/app"
    assert last_response.headers['Content-Security-Policy'].include? 'https://scripts.example.com'
  end

  def test_app_style_src
    get "/app"
    assert last_response.headers['Content-Security-Policy'].include? 'https://styles.example.com'
  end

  private
  def app
    Rails.application
  end
end
```

### Expected behavior
I expect to be able to configure content security policy directives script_src and style_src by specifying the values I want in my rails configuration.

### Actual behavior
It appears that the script_src and style_src directives are overwritten directly by Rails::ApplicationController, ignoring the values specified in configuration.
https://github.com/rails/rails/blob/7-0-stable/railties/lib/rails/application_controller.rb#L10-L11

We can see that the tests pass on ActionController::Base however tests on Rails::ApplicationController fail.

I suspect the values required by Rails::ApplicationController should be merged with the configuration values rather than overwriting them.

### System configuration
**Rails version**:
Rails 7.0.0

**Ruby version**:
Ruby 3.0.3

**Comment by rafaelfranca** [comment]
Why are you using `Rails::ApplicationController`? That controller is only for internal Rails usage and applications should not be using. I'm closing since this issue is related to using a internal Rails controller.

**Comment by apoland** [comment]
That controller is inherited by ApplicationController and is thus used by every controller in an application.

**Comment by apoland** [comment]
Perhaps the bug is that rails new should not be generating a project that inherits from Rails::ApplicationController?

**Comment by rafaelfranca** [comment]
Rails don't generate any controller that inherits from `Rails::ApplicationController`. It does generates a `ApplicationController` and all other controllers inherit from `ApplicationController`, but nothing rails generates in users application inherits from `Rails::ApplicationController`

**Comment by apoland** [comment]
This issue is happening because in my brand new rails7 project the ApplicationController generated appears to directly inherit Rails::ApplicationController.  I will generate a new project and confirm when I'm at my desk.  If I can no longer reproduce that then we can close this. :)

**Comment by rafaelfranca** [comment]
We can see by the code that is not happening because of Rails https://github.com/rails/rails/blob/v7.0.0/railties/lib/rails/generators/rails/app/templates/app/controllers/application_controller.rb.tt#L1. Maybe one of you gems are changing this?

**Comment by apoland** [comment]
I re-tested this with a fresh project and cannot reproduce.  Thanks for your help and sorry for the false alarm. :)
