### ISSUE TITLE
Allow user to choose importmap while using node-based CSS framework

### ISSUE THREAD

**Issue by tannakartikey** [rails/rails#44035]
If the new app is generated with any CSS framework other than Tailwind then the Rails generator forces `esbuild` as Javascript environment.

What if we allow users to choose the latest way to use Javascript with Importmap while they use Node, to depend minimum on it, only to process their stylesheets? 

For example, Sass requires Node but it may not always require "node-based Javascript environment" as mentioned in the code comment below:

https://github.com/rails/rails/blob/f292daad7051275f7b557b352876cfeb3988f639/railties/lib/rails/generators/app_base.rb#L345-L353

### System configuration
**Rails version**:
7.0.0

**Comment by javierav** [comment]
I also have the same issue. I want to develop my new app using importmap for javascript and cssbundling with bootstrap for css.

**Comment by javierav** [comment]
I also have the same issue. I want to develop my new app using importmap for javascript and cssbundling with bootstrap for css.

```
$ rails new app -d postgresql -a propshaft -j importmap -c bootstrap
```

**Comment by brentgreeff** [comment]
> If the new app is generated with any CSS framework other than Tailwind then the Rails generator forces `esbuild` as Javascript environment.

Thanks @tannakartikey - I just ran `rails new` 3 times trying to figure out why I was getting esbuild.

If we look art https://github.com/rails/cssbundling-rails#how-does-this-compare-to-tailwindcss-rails-and-dartsass-rails

> If you're already relying on Node to process your JavaScript, this gem is the way to go. But if you're using [the default import map setup in Rails 7+](https://github.com/rails/importmap-rails/), you can avoid having to deal with Node at all by using the standalone versions of Tailwind CSS and Dart Sass that are available through [tailwindcss-rails](https://github.com/rails/tailwindcss-rails/) and [dartsass-rails](https://github.com/rails/dartsass-rails/). It's simpler, fewer moving parts, and still has all the functionality.

- AND dart Sass

`rails new --help` - 

>   -c, [--css=CSS]                                            # Choose CSS processor [options: tailwind, bootstrap, bulma, postcss, sass... check https://github.com/rails/cssbundling-rails]

That page does not actually list the available options for the `--css` param.

I tried `rails new . -j importmap -a propshaft -d postgresql --skip-jbuilder --css=sass`

but that doesnt work.

package.json includes:

```
"@hotwired/stimulus": "^3.0.1",
    "@hotwired/turbo-rails": "^7.1.1",
    "esbuild": "^0.14.38",
    "sass": "^1.51.0"
```

and Gemfile contains:

```
gem "jsbundling-rails"
gem "cssbundling-rails"
```

How do I get `--css dartsass` ?

I think the docs need a bit more clarity. -

**Comment by brentgreeff** [comment]
I think I figured it out - `--css` should be called `--cssbundling` since thats what it does, - its not a global css choice, - you only specify it when you want node-based-bundling from what I can see.

https://github.com/rails/dartsass-rails/ - I dont think can be selected with `rails  new` but seems confusing to me - especially telling people to look at https://github.com/rails/cssbundling-rails for the options to this param - that page should explain things a bit more explicitly.

**Comment by DonMat** [comment]
Is there any option to add bootstrap/bulma to **existing rails 7 app** generated using default **cssbundling**? 

I want to achieve the same as @javierav said
> I want to develop my new app using importmap for javascript and cssbundling with bootstrap for css.

 My app is 100+ commits away. What should I do to include bootstrap or bulma to my project?
