### ISSUE TITLE
Calling DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call DidYouMean.correct_error(error_name, spell_checker)' instead.

### ISSUE THREAD

**Issue by zchrb** [rails/rails#44037]
### Steps to reproduce
Running `rails -v` in terminal shows this warning:

```ruby
# Your reproduction script goes here
$ rails -v
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Rails 7.0.0
```

### Expected behavior

No warning message. Should only show version number.

### Actual behavior

Version number shows with warning message.

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.1.0

**Comment by Mechetel** [comment]
Same Issue

**Comment by eugeneius** [comment]
This warning is coming from thor; https://github.com/rails/thor/pull/761 will fix it.

I think this issue should stay open for visibility, but there's nothing to be fixed in Rails itself here.

**Comment by rafaelfranca** [comment]
This should be fixed already.

**Comment by jagira** [comment]
I am getting the warning even on rails 7.0.1 (with ruby v3.1.0 & rubygems v3.3.4).

<img width="1197" alt="Screenshot 2022-01-08 at 8 01 24 PM" src="https://user-images.githubusercontent.com/244721/148648021-65137594-4681-4af7-a98c-b3e45b1dabcb.png">

**Comment by nekojanai** [comment]
Getting the same as above person, is this going to be opened up again?

**Comment by jagira** [comment]
@nekojanai upgrading rubygems fixed it for me.

**Comment by canaandavis** [comment]
@jagira Would you mind sharing the steps you took? I attempted to update `rubygems`, but with no luck.

```bash
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]
Rails 7.0.2.3

gem update --system
```

```bash
bin/rails c
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
```

**Comment by jagira** [comment]
@canaandavis I simply updated rubygems.

ruby version - 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin21]
rubygems version - 3.3.4
rails version - 7.0.2.3

**Comment by canaandavis** [comment]
Thanks @jagira! Unfortunately, I'm still having the issue 🤔 

My rubygems version is `3.3.9`, if I'm checking this correctly, but possibly I'm misunderstanding something here.

```
gem --version
3.3.9
```

Does that look correct to you?

**Comment by jagira** [comment]
@canaandavis That's correct.

Can you check the version of `thor` gem in your app's `Gemfile.lock`?

**Comment by jmay** [comment]
It's bundler. Upgrade to 2.3.9.

`bundle update --bundler`

**Comment by canaandavis** [comment]
@jmay Thank you! This worked for me 🔥
