### ISSUE TITLE
[Guide] Misleading code in the "Deleting an Article" section for version 7.0.0

### ISSUE THREAD

**Issue by panr** [rails/rails#44030]
### Steps to reproduce
I've been learning Rails recently and going through the first guide I spotted a little misleading part (at least for me)... 

In **Getting Started** in section **7.5 Deleting an Article** (https://guides.rubyonrails.org/getting_started.html#deleting-an-article), there is a code snippet for implementing the destroy action In UI:

```ruby
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>
```

If you implement the code as is, it won't work in Rails 7 since it's using `GET` method instead of `DELETE`. Since I'm totally new to Rails, It took me a while to understand what is going on (using `@rails/ujs` is now deprecated and the new version does not include it) and I think this code (based on the new setup of version 7) is misleading and should be replaced.

What worked for me:

1) Replacing `link_to` with `button_to`
2) Replacing `method: :delete` with `data: { "turbo-method": :delete }`

### Expected behavior
Based on the snippet above, a `Destroy` link should remove an element from a database by invoking `DELETE` method.

### Actual behavior
Based on the snippet above, by clicking on a `Destroy` link, we are redirected to an element's `show.html.erb` page with `GET` method.

### System configuration
**Rails version**:
Rails 7.0.0

**Ruby version**:
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]

**Comment by ghiculescu** [comment]
Thanks for the issue and welcome to Rails! That has been fixed but the change hasn’t been deployed yet (a new bug fix version of Rails 7 should be coming soon). If you browse the guides at https://edgeguides.rubyonrails.org/getting_started.html it should work correctly with Rails 7 👍
