### ISSUE TITLE
belongs_to track change tracking methods can conflict with association named `:record`

### ISSUE THREAD

**Issue by rylwin** [rails/rails#44033]
In upgrading to Rails 7, we found the belongs_to change tracking methods (introduced in https://github.com/rails/rails/commit/fc3acf2e8dc) can create methods that conflict with existing methods in the AR codebase.

In our case, we have a `belongs_to :record` association. The belongs_to change tracking therefore [creates a method called `#record_changed?`](https://github.com/rails/rails/blob/a17629e393141fadaae75fd1398fa4b80b7a5c5c/activerecord/lib/active_record/associations/builder/belongs_to.rb#L132), which is the same name as the method defined by [AutosaveAssociation](https://github.com/rails/rails/blob/a17629e393141fadaae75fd1398fa4b80b7a5c5c/activerecord/lib/active_record/autosave_association.rb#L464).

### Steps to reproduce

Please see the following gist for a reproduction script and associated stack trace: https://gist.github.com/rylwin/d6e297a5e5bd7a532c3e772eac948e0c 

The file in the gist can be download and run with `ruby {filename}.rb`. Or for the ~~brave~~ reckless: `curl https://gist.githubusercontent.com/rylwin/d6e297a5e5bd7a532c3e772eac948e0c/raw/0c9f233ecea15a5c420437a3e119cb079bead641/belongs_to_change_tracking_method_name_conflict.rb  | ruby`

### Expected behavior

We expect that we should continue to be able to have belongs_to associations named `:record`.

### Actual behavior

Due to the name/method conflict, `:record` is de facto a prohibited association name.

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 2.7.5

### Potential solution

`AutosaveAssociation#record_changed?` is a private method and appears to be used only once. Perhaps the fix is to simply rename the method such that it is less likely to cause a conflict. I've seen methods prefixed with underscores in the rails codebase. What if we renamed the method to `#_record_changed?`? 

I'd be happy to submit a PR with this change, or another preferred one.

**Comment by joeywang** [comment]
nice one, we have a similar issue with this. We are using record_id, record_type to implement polymorphic. The dynamic method record_changed? conflict with the one here.

`belongs_to :record, polymorphic: true, touch: true`

**Comment by eugeneius** [comment]
Fixed in https://github.com/rails/rails/pull/44191.
