### ISSUE TITLE
rails db:migrate runs down migrations in Rails 7

### ISSUE THREAD

**Issue by morgoth** [rails/rails#44077]
After update to Rails 7, there is a serious bug in multi db apps.

Having db migration status like:
```
rails db:migrate:status

database: db/development.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20220105120620  Create users
  down    20220105121206  Add age to users
   up     20220105121229  Add email to users


database: db/animals.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20220105121113  Create dogs

```

When I run `rails db:migrate`, the `20220105121229` is reverted instead of migrating `20220105121206` up.

```
rails db:migrate
== 20220105121229 AddEmailToUsers: reverting ==================================
-- remove_column(:users, :email, :string)
   -> 0.0091s
== 20220105121229 AddEmailToUsers: reverted (0.0159s) =========================


rails db:migrate:status

database: db/development.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20220105120620  Create users
  down    20220105121206  Add age to users
  down    20220105121229  Add email to users


database: db/animals.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20220105121113  Create dogs

```

I couldn't reproduce it in the app with single database.
Running `rails db:migrate:primary` works fine.

I created a sample app where this is visible on https://github.com/morgoth/bug-multi-db

Rails version: 7.0.0
Ruby version: 3.0.3

@eileencodes I guess this have to be related to some multi db changes in Rails 7

**Comment by morgoth** [comment]
Now, I noticed that this is already reported https://github.com/rails/rails/issues/43833

**Comment by eileencodes** [comment]
@morgoth does https://github.com/rails/rails/pull/43988 fix your issue?

**Comment by morgoth** [comment]
@eileencodes yes, this fixes the issue

**Comment by eileencodes** [comment]
Thanks for checking @morgoth - I've merged it and backported to 7-0-stable.
