### ISSUE TITLE
ActiveRecord previous_changes is buggy

### ISSUE THREAD

**Issue by Tang8330** [rails/rails#44082]
### Steps to reproduce
```rb
# Save
l = Lead.first
c = Customer.first
l.customer = c
l.save! # previous_changes -> {"customer_id"=>[1748699, 1748698], "updated_at"=>[Wed, 05 Jan 2022 09:28:01 PST -08:00, Wed, 05 Jan 2022 09:30:14 PST -08:00]}

# Now trying to do an update instead
c = Customer.offset(1).first
l.update!(customer: c) # previous_changes -> {}
```

Say I have 2 models: `Lead` and `Customer` (Lead has a FK to customer)

### Expected behavior

I would expect no difference between `save` and `update` when I have a callback on `after_save` which calls [previous_changes](https://apidock.com/rails/ActiveModel/Dirty/previous_changes).

However, I noticed that upon calling only `.update!(...)`, the callback runs, but `previous_changes` does not get applied.

### Actual behavior

`previous_changes` does not get triggered for an ActiveRecord `update`

### System configuration
**Rails version**:
4.2.11

**Ruby version**:
2.6.8

**Comment by rafaelfranca** [comment]
Does this also happen in Rails 7.0? Rails 4.2 is not supported anymore. Also 
could you create a reproduction script with this template https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_master.rb?

**Comment by Tang8330** [comment]
@rafaelfranca The URL you have sent me gives me a 404. I'm not sure if this is an issue within Rails 7. We're in the midst of migrating everything to Rails 5 from 4

**Comment by rafaelfranca** [comment]
Sorry https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb

**Comment by p8** [comment]
I think this is related to: https://github.com/rails/rails/issues/41701
I'll try to update my PR in https://github.com/rails/rails/pull/43167
