### ISSUE TITLE
Railties CI are still failing even after thor 1.2.1 is released

### ISSUE THREAD

**Issue by yahonda** [rails/rails#44080]
Railties CI are still failing even after thor 1.2.1 is released
https://buildkite.com/rails/rails/builds/83778#e0151aa2-3027-4166-9038-e834dc95ba2e

### Steps to reproduce

Unable to reproduce it locally. https://buildkite.com/rails/rails/builds/83778#e0151aa2-3027-4166-9038-e834dc95ba2e

### Expected behavior
All of `railties` CI should be green againt Ruby 3.1.0 and thor 1.2.1 including https://github.com/rails/thor/pull/761

### Actual behavior

https://buildkite.com/rails/rails/builds/83778#e0151aa2-3027-4166-9038-e834dc95ba2e/1078-1086
```
Error:
--
  | ApplicationTests::RakeTests::RakeMultiDbsTest#test_db:test:prepare:name_works_for_the_primary_database_with_a_ruby_schema:
  | JSON::ParserError: 859: unexpected token at 'Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
  | ["books", "schema_migrations", "ar_internal_metadata"]'
  | test/application/rake/multi_dbs_test.rb:217:in `block in db_test_prepare_name'
  | test/application/rake/multi_dbs_test.rb:205:in `chdir'
  | test/application/rake/multi_dbs_test.rb:205:in `db_test_prepare_name'
  | test/application/rake/multi_dbs_test.rb:606:in `block in <class:RakeMultiDbsTest>'
  |  


```
### System configuration
**Rails version**: main branch

**Ruby version**: Ruby          3.1.0p0 (2021-12-25 revision fb4df44d1670e9d25aef6b235a7281199a177edb) [x86_64-linux]

**Comment by yahonda** [comment]
It may be due to it uses older version of RubyGems 3.2.9.  

https://buildkite.com/rails/rails/builds/83778#e0151aa2-3027-4166-9038-e834dc95ba2e/133-143
```
RubyGems      3.2.9
```

RubyGems 3.3.2 also addresses this warning via https://github.com/rubygems/rubygems/pull/5211
https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#332--2021-12-23

I've found these commits https://github.com/rails/buildkite-config/commit/906b9abd4b741fb9694d94d3deb4dd3cad43e12e and https://github.com/rails/buildkite-config/commit/0b59c68f6f8e9318564e81bace64d66821620eeb to use RubyGems 3.2.9. 

@rafaelfranca I'm inclined to open a pull request at https://github.com/rails/buildkite-config to remove them but have not found if we can "unlock" RubyGems and Bundler versions. It would be helpful if you have some ideas.

https://github.com/rails/buildkite-config/blob/0b59c68f6f8e9318564e81bace64d66821620eeb/pipeline-generate#L34-L35
https://github.com/rails/buildkite-config/blob/0b59c68f6f8e9318564e81bace64d66821620eeb/pipeline-generate#L41-L42

**Comment by rafaelfranca** [comment]
Fixed!
