### ISSUE TITLE
Rails 7.0.1 Regression: Running group queries results in double quoted invalid SQL

### ISSUE THREAD

**Issue by terracatta** [rails/rails#44099]
### Steps to reproduce
I am unable to narrow this down to a script-based reproduction, but on a standard Rails 7.0.0 app running Ruby 3.0.3 I have a bunch of test failures related to `.group` queries after I upgraded to 7.0.1

Let's consider the following code: `User.group(:created_at).count`

On Rails 7.0.0 on PostgreSQL this produces the following query...

```sql
SELECT COUNT(*) AS count_all, "users"."created_at" AS "users_created_at" FROM "users" GROUP BY "users"."created_at"
```

On Rails 7.0.1 that same command produces the following query (note the double quotes)

```sql
SELECT COUNT(*) AS "count_all", "users"."created_at" AS ""users_created_at"" FROM "users" GROUP BY "users"."created_at"
```

Which results in the following error:

```
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  zero-length delimited identifier at or near """"
LINE 1: ... COUNT(*) AS "count_all", "users"."created_at" AS ""users_cr...
                                                             ^

from /Users/jmeller/.rvm/gems/ruby-3.0.3/gems/activerecord-7.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params'
Caused by PG::SyntaxError: ERROR:  zero-length delimited identifier at or near """"
LINE 1: ... COUNT(*) AS "count_all", "users"."created_at" AS ""users_cr...
```

I assume this is related to the following commit https://github.com/rails/rails/commit/7e6e9091e55c3357b0162d44b6ab955ed0c718d5

As I said earlier, I cannot get this to reproduce in a test script, yet it's easily reproduced in my production rails app. I'm filing this issue now in case this is widespread and others are faster at determining the root cause.

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 3.0.3

**Comment by terracatta** [comment]
I have narrowed down the root cause to be the `arel_extensions` gem. Since this is not a rails bug I am going to close this issue. Sorry for the trouble!

**Comment by atruskie** [comment]
@terracatta did you file an issue with arel_extensions? Got any hints about what was the problem?
