### ISSUE TITLE
@rails/actioncable 7.0.0 does not work with next.js / ssr

### ISSUE THREAD

**Issue by ajsharp** [rails/rails#44092]
next.js renders files first on the server, and then again on the client. When it attempts to run on the server, rendering breaks because self is undefined.

### Steps to reproduce
In a next.js (12.0.4) project, add `@rails/actioncable` (7.0.0) and try to import it in a javascript file:

<details>
<summary>package.json</summary>

```json
{
  "name": "actioncable-repro",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@rails/actioncable": "^7.0.0",
    "next": "12.0.7",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "eslint": "8.6.0",
    "eslint-config-next": "12.0.7"
  }
}
```
</details>

<details>
<summary>pages/index.js</summary>

```javascript
import { createConsumer } from "@rails/actioncable";

export default function Home() {
  return <div>Hello, World</div>;
}
```
</details>
    
Then run the server:
```bash
yarn dev
```
    
### Expected behavior
The server should run
    
### Actual behavior

The following error message: `ReferenceError: self is not defined` 

```
<unknown>
file:///Users/ajsharp/code/actioncable-repro/node_modules/@rails/actioncable/app/assets/javascripts/actioncable.js (7:13)
<unknown>
file:///Users/ajsharp/code/actioncable-repro/node_modules/@rails/actioncable/app/assets/javascripts/actioncable.js (2:66)
Object.<anonymous>
file:///Users/ajsharp/code/actioncable-repro/node_modules/@rails/actioncable/app/assets/javascripts/actioncable.js (4:3)
Module._compile
node:internal/modules/cjs/loader (1101:14)
Object.Module._extensions..js
node:internal/modules/cjs/loader (1153:10)
Module.load
node:internal/modules/cjs/loader (981:32)
Function.Module._load
node:internal/modules/cjs/loader (822:12)
Module.require
node:internal/modules/cjs/loader (1005:19)
require
node:internal/modules/cjs/helpers (102:18)
Object.@rails/actioncable
file:///Users/ajsharp/code/actioncable-repro/.next/server/pages/index.js (86:18)
```

<details><summary>Error screenshot</summary>

![image](https://user-images.githubusercontent.com/12774/148371077-bf05aec4-49c3-43c3-9ad1-de47fea8a97d.png)

</details>

**Comment by rafaelfranca** [comment]
Thank you for the issue. actioncable is a client only library. I think you need to tell next.js to not try to use it in the server. I don't know how to do it, but I think it is possible.

**Comment by jpheos** [comment]
do you find a solution @ajsharp ?

**Comment by ajsharp** [comment]
@jpheos We haven't implemented it, but the solution, unfortunately, is basically to load everything async. Next has some tooling to async load javascript/typescript files, but this will essentially require you to async load your actioncable client, and whatever is using it. We're wanting to use actioncable in conjunction with the apollo graphql client, which mean's we'd need to load that async. Not impossible, just annoying and hasn't been a priority yet.

**Comment by detonatR** [comment]
@ajsharp hi! was wondering if you were able to get this working? im going through this same exact situation now. trying to use nextjs, actioncable, and apollo client all together

**Comment by tomkra** [comment]
Hey I've had same problem and come up with solution. I've written article about it here [https://tomkral.hashnode.dev/how-to-make-rails-action-cable-work-in-your-nextjs-app](https://tomkral.hashnode.dev/how-to-make-rails-action-cable-work-in-your-nextjs-app)

I will copy solution, so It's accessible in here too.

Basically I've ended up creating provider where I load @rails/action_cable dynamically:

```jsx
import { createContext, useEffect, useState } from "react";
import { useSession } from "next-auth/react";

const ActionCableContext = createContext();

const ActionCableProvider = ({ children }) => {
  const { data: session } = useSession();
  const [CableApp, setCableApp] = useState({});

  const loadConsumer = async () => {
    const { createConsumer } = await import("@rails/actioncable");
    return createConsumer;
  };

  useEffect(() => {
    if (typeof window !== "undefined" && session?.user && session?.user?.accessToken && CableApp.cable === undefined) {
      loadConsumer().then((createConsumer) => {
        setCableApp({
          cable: createConsumer(`${process.env.NEXT_PUBLIC_API_WS_URL}?token=${session?.user?.accessToken}`),
        });
      });
    }
  }, [session, window]);

  return <ActionCableContext.Provider value={CableApp.cable}>{children}</ActionCableContext.Provider>;
};

export { ActionCableContext, ActionCableProvider };
```

Then I've wrapped my Layout into this provider in `_app.js`

And in then I've been able to use it in my component as follows:

```jsx
import { useState, useEffect, useRef, useContext } from "react";
import { ActionCableContext } from "../../src/providers/action_cable_provider";

const ChatRoom = (props) => {
  const cable = useContext(ActionCableContext);
  const [channel, setChannel] = useState(null);

  useEffect(() => {
      if (!channel && cable && props.chat) {
        const chnl = cable.subscriptions.create(
          {
            channel: "ChatRoomChannel",
            id: props.chat.id,
          },
          {
            connected: () => {
              console.log("RoomsChannel connected!");
            },
            disconnected: () => {
              console.log("RoomsChannel disconnected!");
            },
            received: (data) => {
              console.log(data);
            },
          }
        );

        setChannel(chnl);
      }

      return () => {
        if (cable) {
          cable.disconnect();
        }
      };
    }, [props.chat, cable]);

  return <>My chat room</>;
}

export default ChatRoom;
```


The hardest part was to find out, how to import this lib without error :)

**Comment by duchk226** [comment]
hi @tomkra , thank you for your solution, you're a savior. It works for me. Could you explain why `import @rails/action_cable dynamically` solve the issue?

**Comment by metronom72** [comment]
I solved this issue with require, but it will have conflicts with nextjs 13
