### ISSUE TITLE
Ruby 3.2.0dev removes Object#=~

### ISSUE THREAD

**Issue by yahonda** [rails/rails#44107]
`ActiveRecord::RelationMutationTest#test_#order!_on_non-string_does_not_attempt_regexp_match_for_references` fails with Ruby 3.2.0 which removes `Object#=~`. 

### Steps to reproduce

`ActiveRecord::RelationMutationTest#test_#order!_on_non-string_does_not_attempt_regexp_match_for_references` should get an error  when https://github.com/rails/rails/issues/44101 is resolved and CI runs against Ruby 3.2.0dev.

I have pushed a repository that workarounds #44101 by not installing the `sneakers` gem.

```ruby
- Install Ruby 3.2.0dev by `rbenv install 3.2.0-dev`
$ git clone https://github.com/yahonda/rails -b sneakers
$ cd rails/activerecord
$ bundle install
$ bin/test test/cases/relation/mutation_test.rb:35
```

### Expected behavior
It should pass

### Actual behavior
```ruby
$ bin/test test/cases/relation/mutation_test.rb:35
Using sqlite3
Run options: --seed 56918

# Running:

E

Error:
ActiveRecord::RelationMutationTest#test_#order!_on_non-string_does_not_attempt_regexp_match_for_references:
NameError: undefined method `=~' for class `#<Class:#<Object:0x00007f0150ddabf0>>'

    metaclass.send :undef_method, name
             ^^^^^
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/method_call_assertions.rb:12:in `assert_called'
    /home/yahonda/src/github.com/rails/rails/activesupport/lib/active_support/testing/method_call_assertions.rb:35:in `assert_not_called'
    /home/yahonda/src/github.com/rails/rails/activerecord/test/cases/relation/mutation_test.rb:35:in `block in <class:RelationMutationTest>'
    /home/yahonda/src/github.com/rails/rails/railties/lib/rails/test_unit/line_filtering.rb:10:in `run'


bin/test test/cases/relation/mutation_test.rb:33



Finished in 0.033504s, 29.8471 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**:ruby 3.2.0dev (2022-01-07T14:55:59Z master 3f9af8a9dc) [x86_64-linux]

**Comment by yahonda** [comment]
Looks like this test may want to make sure [Regexp#=~](https://ruby-doc.org/core-3.1.0/Regexp.html#method-i-3D~) is not called. but actually, it is confirming if `Kernel#=~` is not called.

https://github.com/rails/rails/blob/2b05b25809a53a7765d04b2aa9ed0f2f96aa83a5/activerecord/test/cases/relation/mutation_test.rb#L33-L39

**Comment by rafaelfranca** [comment]
I think we should just change the test to remove the `assert_not_called`.

**Comment by yahonda** [comment]
Sure. Let me open a pull request soon.

**Comment by zzak** [comment]
@yahonda @rafaelfranca I also ran into this issue, hope ya’ll don’t mind that I’ve submitted a PR to remove the assertion in #44128 :bow:
