### ISSUE TITLE
Oracle12 visitor - Combination of limit and lock is not supported

### ISSUE THREAD

**Issue by akostadinov** [rails/rails#44114]
`Oracle12` Arel visitor does not handle sub-queries with `LIMIT` properly and this makes locking a row impossible. While it works in normal queries, in sub-queries that doesn't seem to be the case.

### Steps to reproduce

```
# just a minimal project `rails new --database=oracle
git clone https://github.com/akostadinov/rails-ora-02014.git
cd rails-ora-02014
vi config/database.yml # set your DB connection details
rails c
> a = Article.create!(title: "test", body: "test body")
> a.with_lock {}
```

### Expected behavior
```
  Article Load (1.8ms)  SELECT "ARTICLES".* FROM "ARTICLES" WHERE "ARTICLES"."ID" = :a1 AND ROWNUM <= :a2  FOR UPDATE  [["id", 23], ["LIMIT", 1]]
=> nil
```

### Actual behavior
```
Traceback (most recent call last):
/home/avalon/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/activerecord-oracle_enhanced-adapter-7.0.0/lib/arel/visitors/oracle12.rb:10:in `visit_Arel_Nodes_SelectStatement': Combination of limit and lock is not supported. Because generated SQL statements (ArgumentError)
`SELECT FOR UPDATE and FETCH FIRST n ROWS` generates ORA-02014.
```

### Possible workaround - use `Arel::Visitors::Oracle`

`Arel::Visitors::Oracle`  works fine though because it always translates `LIMIT` statements to `ROWNUM`.

The example above properly works, if we add to `application.rb`:

```
ActiveSupport.on_load(:active_record) do
  ActiveRecord::ConnectionAdapters::OracleEnhancedAdapter.class_eval do
    # Use old visitor for Oracle 12c database
    self.use_old_oracle_visitor = true
  end
end
```

### System configuration
**Rails version**:
Rails 7.0.1

**Ruby version**:
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]

**Oracle version**:
19.3.0

**Comment by rafaelfranca** [comment]
This issue should be open in the activerecord-oracle_enhanced-adapter gem. Rails doesn't define the arel/visitors/oracle12

**Comment by akostadinov** [comment]
My bad. I was looking at old arel gem sources. For anybody that comes here, check rsim/oracle-enhanced#2237
