### ISSUE TITLE
Rails 7.0.1: rails new x -css sass results in rails  css:install:css which is an unknown build task

### ISSUE THREAD

**Issue by andreimoment** [rails/rails#44116]
### Steps to reproduce
`rails new pil -d postgresql -j esbuild -css sass`

### Expected behavior

A new rails app in working condition should be generated

### Actual behavior

The `new` script ran `css:install:css` instead of `css:install:sass`, resulting in an error. I am not sure if the setup is complete.

```
rails  css:install:css
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
rails aborted!
Don't know how to build task 'css:install:css' (See the list of available tasks with `rails --tasks`)
Did you mean?  css:install:sass
               css:install:postcss

```

Here's a gist of the full output: https://gist.github.com/andreimoment/3e77e7d3826131c411206b02d90b2b12

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 2.7.5

**Comment by rafaelfranca** [comment]
You are passing the option incorrectly, it should be `--css=sass` or `-c sass`
