### ISSUE TITLE
Active Storage analyzer 'missing FFmpeg' error message is misleading.

### ISSUE THREAD

**Issue by weavermedia** [rails/rails#44110]
### Steps to reproduce
1. Install ffmpeg but not ffprobe.
2. Attach an Active Storage video or audio file.

### Expected behavior
According to the docs the file should be analyzed by `ffmpeg`.

From: https://github.com/rails/rails/blob/main/activestorage/lib/active_storage/analyzer/video_analyzer.rb
` # This analyzer requires the {FFmpeg}[https://www.ffmpeg.org] system library, which is not provided by Rails.`

From: https://guides.rubyonrails.org/active_storage_overview.html
"ffmpeg v3.4+ for video/audio analysis and video previews"

### Actual behavior
Error message:
`[ActiveStorage::AnalyzeJob] Skipping video analysis because FFmpeg isn't installed`
`[ActiveStorage::AnalyzeJob] Skipping audio analysis because FFmpeg isn't installed`

The previewers use the ffmpeg binary but the the analyzers instead use the ffprobe binary. Depending on how the user installs ffmpeg, ffprobe may be a separate installer therefore not available to Rails.

Example: go to the official FFmpeg download page https://ffmpeg.org/download.html, then under "Get packages & executable files" click "Static builds for macOS 64-bit". The resulting page has separate installers for ffmpeg and ffprobe.

A simple change to the error message would be a good start:
`[ActiveStorage::AnalyzeJob] Skipping video analysis because ffprobe isn't installed`
`[ActiveStorage::AnalyzeJob] Skipping audio analysis because ffprobe isn't installed`

(Minor gripe - FFmpeg is the name of the overall software project. The binaries are lowercase, ffmpeg and ffprobe.)

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0

**Comment by rafaelfranca** [comment]
> (Minor gripe - FFmpeg is the name of the overall software project. The binaries are lowercase, ffmpeg and ffprobe.)

You are just saying what the message is trying to say. The message is saying the overall software project is missing, in this case, just part of it, but we can for sure change to tell which binary is missing.

**Comment by weavermedia** [comment]
@rafaelfranca Would a PR be useful?

**Comment by rafaelfranca** [comment]
Of course!

**Comment by weavermedia** [comment]
Done! https://github.com/rails/rails/pull/44112
