### ISSUE TITLE
Rails 7.1: rails  css:install:css rails aborted! Don't know how to build task 'css:install:css'

### ISSUE THREAD

**Issue by MtnBiker** [rails/rails#44124]
Rails 7.0.1
Ruby 3.1.0
`➜ rails new rails71 -j esbuild -css bootstrap -d postgresql`

Get error in log: 
➜ rails new rails71 -j esbuild -css bootstrap -d postgresql

rails  css:install:css
rails aborted!
Don't know how to build task 'css:install:css'

But ➜` rails css:install:bootstrap` runs

So some error in the building of the app. Way beyond my knowledge.

Partial log from `rails new…`

    hint: 	git branch -m <name>
    Initialized empty Git repository in /Users/gscar/Documents/Ruby/RailsTrials/prails71/.git/
          create  app
          create  app/assets/config/manifest.js
          create  app/assets/stylesheets/application.css
          create  app/channels/application_cable/channel.rb
          create  app/channels/application_cable/connection.rb
          create  app/controllers/application_controller.rb
          create  app/helpers/application_helper.rb
          create  app/jobs/application_job.rb
          create  app/mailers/application_mailer.rb
          create  app/models/application_record.rb
          create  app/views/layouts/application.html.erb
          create  app/views/layouts/mailer.html.erb
          create  app/views/layouts/mailer.text.erb
          create  app/assets/images
          create  app/assets/images/.keep
          create  app/controllers/concerns/.keep
          create  app/models/concerns/.keep
          create  bin
          create  bin/rails
          create  bin/rake
          create  bin/setup
          create  config
          create  config/routes.rb
          create  config/application.rb
          create  config/environment.rb
          create  config/cable.yml
          create  config/puma.rb
          create  config/storage.yml
          create  config/environments
          create  config/environments/development.rb
          create  config/environments/production.rb
          create  config/environments/test.rb
          create  config/initializers
          create  config/initializers/assets.rb
          create  config/initializers/content_security_policy.rb
          create  config/initializers/cors.rb
          create  config/initializers/filter_parameter_logging.rb
          create  config/initializers/inflections.rb
          create  config/initializers/new_framework_defaults_7_0.rb
          create  config/initializers/permissions_policy.rb
          create  config/locales
          create  config/locales/en.yml
          create  config/master.key
          append  .gitignore
          create  config/boot.rb
          create  config/database.yml
          create  db
          create  db/seeds.rb
          create  lib
          create  lib/tasks
          create  lib/tasks/.keep
          create  lib/assets
          create  lib/assets/.keep
          create  log
          create  log/.keep
          create  public
          create  public/404.html
          create  public/422.html
          create  public/500.html
          create  public/apple-touch-icon-precomposed.png
          create  public/apple-touch-icon.png
          create  public/favicon.ico
          create  public/robots.txt
          create  tmp
          create  tmp/.keep
          create  tmp/pids
          create  tmp/pids/.keep
          create  tmp/cache
          create  tmp/cache/assets
          create  vendor
          create  vendor/.keep
          create  test/fixtures/files
          create  test/fixtures/files/.keep
          create  test/controllers
          create  test/controllers/.keep
          create  test/mailers
          create  test/mailers/.keep
          create  test/models
          create  test/models/.keep
          create  test/helpers
          create  test/helpers/.keep
          create  test/integration
          create  test/integration/.keep
          create  test/channels/application_cable/connection_test.rb
          create  test/test_helper.rb
          create  test/system
          create  test/system/.keep
          create  test/application_system_test_case.rb
          create  storage
          create  storage/.keep
          create  tmp/storage
          create  tmp/storage/.keep
          remove  config/initializers/cors.rb
          remove  config/initializers/new_framework_defaults_7_0.rb
             run  bundle install
    Fetching gem metadata from https://rubygems.org/...........
    Resolving dependencies...
    Using rake 13.0.6
    Using concurrent-ruby 1.1.9
    Using minitest 5.15.0
    Using builder 3.2.4
    Using erubi 1.10.0
    Using racc 1.6.0
    Using crass 1.0.6
    Using nio4r 2.5.8
    Using websocket-extensions 0.1.5
    Using marcel 1.0.2
    Fetching digest 3.1.0
    Fetching io-wait 0.2.1
    Fetching timeout 0.2.0
    Fetching strscan 3.0.1
    Using bindex 0.8.1
    Using bundler 2.2.30
    Using regexp_parser 2.2.0
    Using rack 2.2.3
    Using mini_mime 1.1.2
    Using thor 1.2.1
    Using zeitwerk 2.5.3
    Using public_suffix 4.0.6
    Using msgpack 1.4.2
    Using matrix 0.4.2
    Using childprocess 4.1.0
    Using i18n 1.8.11
    Using tzinfo 2.0.4
    Using rexml 3.2.5
    Using method_source 1.0.0
    Using websocket-driver 0.7.5
    Using puma 5.5.2
    Using rack-test 1.1.0
    Using mail 2.7.1
    Using addressable 2.8.0
    Using bootsnap 1.9.3
    Using sprockets 4.0.2
    Using io-console 0.5.11
    Using pg 1.2.3
    Using reline 0.3.1
    Using activesupport 7.0.1
    Using rubyzip 2.3.2
    Using activemodel 7.0.1
    Using activerecord 7.0.1
    Using irb 1.4.1
    Using selenium-webdriver 4.1.0
    Using globalid 1.0.0
    Using debug 1.4.0
    Using activejob 7.0.1
    Fetching nokogiri 1.13.0 (arm64-darwin)
    Installing io-wait 0.2.1 with native extensions
    Installing digest 3.1.0 with native extensions
    Installing timeout 0.2.0
    Installing strscan 3.0.1 with native extensions
    Installing nokogiri 1.13.0 (arm64-darwin)
    Using rails-dom-testing 2.0.3
    Using loofah 2.13.0
    Using xpath 3.2.0
    Using rails-html-sanitizer 1.4.2
    Using webdrivers 5.0.0
    Using actionview 7.0.1
    Using capybara 3.36.0
    Using actionpack 7.0.1
    Using jbuilder 2.11.5
    Using railties 7.0.1
    Using actioncable 7.0.1
    Using activestorage 7.0.1
    Using sprockets-rails 3.4.2
    Using web-console 4.2.0
    Using cssbundling-rails 1.0.0
    Using jsbundling-rails 1.0.0
    Using stimulus-rails 1.0.2
    Using turbo-rails 1.0.0
    Using actiontext 7.0.1
    Fetching net-protocol 0.1.2
    Installing net-protocol 0.1.2
    Using net-pop 0.1.1
    Fetching net-imap 0.2.3
    Fetching net-smtp 0.3.1
    Installing net-smtp 0.3.1
    Installing net-imap 0.2.3
    Using actionmailbox 7.0.1
    Using actionmailer 7.0.1
    Using rails 7.0.1
    Bundle complete! 16 Gemfile dependencies, 75 gems now installed.
    Use `bundle info [gemname]` to see where a bundled gem is installed.
             run  bundle binstubs bundler
           rails  javascript:install:esbuild
    Compile into app/assets/builds
          create  app/assets/builds
          create  app/assets/builds/.keep
          append  app/assets/config/manifest.js
          append  .gitignore
          append  .gitignore
    Add JavaScript include tag in application layout
          insert  app/views/layouts/application.html.erb
    Create default entrypoint in app/javascript/application.js
          create  app/javascript
          create  app/javascript/application.js
    Add default package.json
          create  package.json
    Add default Procfile.dev
          create  Procfile.dev
    Ensure foreman is installed
             run  gem install foreman from "."
    Successfully installed foreman-0.87.2
    1 gem installed
    Add bin/dev to start foreman
          create  bin/dev
    Install esbuild
             run  yarn add esbuild from "."
    yarn add v1.22.17
    info No lockfile found.
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    [3/4] 🔗  Linking dependencies...
    [4/4] 🔨  Building fresh packages...
    success Saved lockfile.
    success Saved 2 new dependencies.
    info Direct dependencies
    └─ esbuild@0.14.10
    info All dependencies
    ├─ esbuild-darwin-arm64@0.14.10
    └─ esbuild@0.14.10
    ✨  Done in 1.02s.
    Add build script
             run  npm set-script build "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds" from "."
             run  yarn build from "."
    yarn run v1.22.17
    $ esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds

      app/assets/builds/application.js      55b
      app/assets/builds/application.js.map  93b

    ✨  Done in 0.27s.
           rails  turbo:install stimulus:install
    Import Turbo
          append  app/javascript/application.js
    Install Turbo
             run  yarn add @hotwired/turbo-rails from "."
    yarn add v1.22.17
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    [3/4] 🔗  Linking dependencies...
    [4/4] 🔨  Building fresh packages...
    success Saved lockfile.
    success Saved 3 new dependencies.
    info Direct dependencies
    └─ @hotwired/turbo-rails@7.1.0
    info All dependencies
    ├─ @hotwired/turbo-rails@7.1.0
    ├─ @hotwired/turbo@7.1.0
    └─ @rails/actioncable@6.1.4
    ✨  Done in 1.22s.
    Run turbo:install:redis to switch on Redis and use it in development for turbo streams
    Create controllers directory
          create  app/javascript/controllers
          create  app/javascript/controllers/index.js
          create  app/javascript/controllers/application.js
          create  app/javascript/controllers/hello_controller.js
    Import Stimulus controllers
          append  app/javascript/application.js
    Install Stimulus
             run  yarn add @hotwired/stimulus from "."
    yarn add v1.22.17
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    [3/4] 🔗  Linking dependencies...
    [4/4] 🔨  Building fresh packages...
    success Saved lockfile.
    success Saved 1 new dependency.
    info Direct dependencies
    └─ @hotwired/stimulus@3.0.1
    info All dependencies
    └─ @hotwired/stimulus@3.0.1
    ✨  Done in 0.60s.
           rails  css:install:css
    rails aborted!
    Don't know how to build task 'css:install:css' (See the list of available tasks with `rails --tasks`)
    Did you mean?  css:install:sass
                   css:install:postcss

    (See full trace by running task with --trace)

    Documents/Ruby/RailsTrials on  main [?] via ⬢ v17.2.0 took 18s
    ➜ chruby ruby-3.1.0

    Documents/Ruby/RailsTrials on  main [?] via ⬢ v17.2.0
    ➜ rails -v
    Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
    Rails 7.0.0

    Documents/Ruby/RailsTrials on  main [?] via ⬢ v17.2.0
    ➜ gem install rails
    Fetching activesupport-7.0.1.gem
    Fetching railties-7.0.1.gem
    Fetching activerecord-7.0.1.gem
    Fetching activejob-7.0.1.gem
    Fetching actionpack-7.0.1.gem
    Fetching actionview-7.0.1.gem
    Fetching activemodel-7.0.1.gem
    Fetching activestorage-7.0.1.gem
    Fetching actiontext-7.0.1.gem
    Fetching actionmailer-7.0.1.gem
    Fetching actionmailbox-7.0.1.gem
    Fetching actioncable-7.0.1.gem
    Fetching rails-7.0.1.gem
    Successfully installed activesupport-7.0.1
    Successfully installed actionview-7.0.1
    Successfully installed actionpack-7.0.1
    Successfully installed railties-7.0.1
    Successfully installed activemodel-7.0.1
    Successfully installed activerecord-7.0.1
    Successfully installed activejob-7.0.1
    Successfully installed activestorage-7.0.1
    Successfully installed actiontext-7.0.1
    Successfully installed actionmailer-7.0.1
    Successfully installed actionmailbox-7.0.1
    Successfully installed actioncable-7.0.1
    Successfully installed rails-7.0.1
    13 gems installed

    Documents/Ruby/RailsTrials on  main [?] via ⬢ v17.2.0 took 3s
    ➜ rails -v
    Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
    Rails 7.0.1

    Documents/Ruby/RailsTrials on  main [?] via ⬢ v17.2.0
    ➜ rails new rails71 -j esbuild -css bootstrap -d postgresql
    Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
          create
          create  README.md
          create  Rakefile
          create  .ruby-version
          create  config.ru
          create  .gitignore
          create  .gitattributes
          create  Gemfile
             run  git init from "."
    hint: Using 'master' as the name for the initial branch. This default branch name
    hint: is subject to change. To configure the initial branch name to use in all
    hint: of your new repositories, which will suppress this warning, call:
    hint:
    hint: 	git config --global init.defaultBranch <name>
    hint:
    hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
    hint: 'development'. The just-created branch can be renamed via this command:
    hint:
    hint: 	git branch -m <name>
    Initialized empty Git repository in /Users/gscar/Documents/Ruby/RailsTrials/rails71/.git/
          create  app
          create  app/assets/config/manifest.js
          create  app/assets/stylesheets/application.css
          create  app/channels/application_cable/channel.rb
          create  app/channels/application_cable/connection.rb
          create  app/controllers/application_controller.rb
          create  app/helpers/application_helper.rb
          create  app/jobs/application_job.rb
          create  app/mailers/application_mailer.rb
          create  app/models/application_record.rb
          create  app/views/layouts/application.html.erb
          create  app/views/layouts/mailer.html.erb
          create  app/views/layouts/mailer.text.erb
          create  app/assets/images
          create  app/assets/images/.keep
          create  app/controllers/concerns/.keep
          create  app/models/concerns/.keep
          create  bin
          create  bin/rails
          create  bin/rake
          create  bin/setup
          create  config
          create  config/routes.rb
          create  config/application.rb
          create  config/environment.rb
          create  config/cable.yml
          create  config/puma.rb
          create  config/storage.yml
          create  config/environments
          create  config/environments/development.rb
          create  config/environments/production.rb
          create  config/environments/test.rb
          create  config/initializers
          create  config/initializers/assets.rb
          create  config/initializers/content_security_policy.rb
          create  config/initializers/cors.rb
          create  config/initializers/filter_parameter_logging.rb
          create  config/initializers/inflections.rb
          create  config/initializers/new_framework_defaults_7_0.rb
          create  config/initializers/permissions_policy.rb
          create  config/locales
          create  config/locales/en.yml
          create  config/master.key
          append  .gitignore
          create  config/boot.rb
          create  config/database.yml
          create  db
          create  db/seeds.rb
          create  lib
          create  lib/tasks
          create  lib/tasks/.keep
          create  lib/assets
          create  lib/assets/.keep
          create  log
          create  log/.keep
          create  public
          create  public/404.html
          create  public/422.html
          create  public/500.html
          create  public/apple-touch-icon-precomposed.png
          create  public/apple-touch-icon.png
          create  public/favicon.ico
          create  public/robots.txt
          create  tmp
          create  tmp/.keep
          create  tmp/pids
          create  tmp/pids/.keep
          create  tmp/cache
          create  tmp/cache/assets
          create  vendor
          create  vendor/.keep
          create  test/fixtures/files
          create  test/fixtures/files/.keep
          create  test/controllers
          create  test/controllers/.keep
          create  test/mailers
          create  test/mailers/.keep
          create  test/models
          create  test/models/.keep
          create  test/helpers
          create  test/helpers/.keep
          create  test/integration
          create  test/integration/.keep
          create  test/channels/application_cable/connection_test.rb
          create  test/test_helper.rb
          create  test/system
          create  test/system/.keep
          create  test/application_system_test_case.rb
          create  storage
          create  storage/.keep
          create  tmp/storage
          create  tmp/storage/.keep
          remove  config/initializers/cors.rb
          remove  config/initializers/new_framework_defaults_7_0.rb
             run  bundle install
    Fetching gem metadata from https://rubygems.org/...........
    Resolving dependencies...
    Using rake 13.0.6
    Using racc 1.6.0
    Using crass 1.0.6
    Using digest 3.1.0
    Using io-wait 0.2.1
    Using timeout 0.2.0
    Using strscan 3.0.1
    Using nio4r 2.5.8
    Using websocket-extensions 0.1.5
    Using marcel 1.0.2
    Using bundler 2.3.3
    Using mini_mime 1.1.2
    Using matrix 0.4.2
    Using minitest 5.15.0
    Using erubi 1.10.0
    Using method_source 1.0.0
    Using public_suffix 4.0.6
    Fetching thor 1.2.1
    Using msgpack 1.4.2
    Using concurrent-ruby 1.1.9
    Using pg 1.2.3
    Using builder 3.2.4
    Using rubyzip 2.3.2
    Using net-protocol 0.1.2
    Using zeitwerk 2.5.3
    Using bindex 0.8.1
    Using puma 5.5.2
    Using regexp_parser 2.2.0
    Using addressable 2.8.0
    Using childprocess 4.1.0
    Using rack 2.2.3
    Fetching io-console 0.5.11
    Fetching net-imap 0.2.3
    Using mail 2.7.1
    Using rexml 3.2.5
    Using bootsnap 1.9.3
    Using net-pop 0.1.1
    Using tzinfo 2.0.4
    Using websocket-driver 0.7.5
    Fetching nokogiri 1.13.0 (arm64-darwin)
    Using i18n 1.8.11
    Using net-smtp 0.3.1
    Using activesupport 7.0.1
    Using sprockets 4.0.2
    Using selenium-webdriver 4.1.0
    Using rack-test 1.1.0
    Using globalid 1.0.0
    Using activemodel 7.0.1
    Using activejob 7.0.1
    Using activerecord 7.0.1
    Installing io-console 0.5.11 with native extensions
    Installing net-imap 0.2.3
    Installing thor 1.2.1
    Installing nokogiri 1.13.0 (arm64-darwin)
    Using rails-dom-testing 2.0.3
    Using loofah 2.13.0
    Using xpath 3.2.0
    Using webdrivers 5.0.0
    Using rails-html-sanitizer 1.4.2
    Using capybara 3.36.0
    Using actionview 7.0.1
    Using actionpack 7.0.1
    Using jbuilder 2.11.5
    Using sprockets-rails 3.4.2
    Using actioncable 7.0.1
    Using activestorage 7.0.1
    Using actionmailer 7.0.1
    Using actiontext 7.0.1
    Using railties 7.0.1
    Using actionmailbox 7.0.1
    Using stimulus-rails 1.0.2
    Using rails 7.0.1
    Using turbo-rails 1.0.0
    Fetching cssbundling-rails 1.0.0
    Fetching jsbundling-rails 1.0.0
    Using web-console 4.2.0
    Fetching reline 0.3.1
    Installing cssbundling-rails 1.0.0
    Installing jsbundling-rails 1.0.0
    Installing reline 0.3.1
    Using irb 1.4.1
    Using debug 1.4.0
    Bundle complete! 16 Gemfile dependencies, 75 gems now installed.
    Use `bundle info [gemname]` to see where a bundled gem is installed.
             run  bundle binstubs bundler
           rails  javascript:install:esbuild
    Compile into app/assets/builds
          create  app/assets/builds
          create  app/assets/builds/.keep
          append  app/assets/config/manifest.js
          append  .gitignore
          append  .gitignore
    Add JavaScript include tag in application layout
          insert  app/views/layouts/application.html.erb
    Create default entrypoint in app/javascript/application.js
          create  app/javascript
          create  app/javascript/application.js
    Add default package.json
          create  package.json
    Add default Procfile.dev
          create  Procfile.dev
    Ensure foreman is installed
             run  gem install foreman from "."
    Fetching foreman-0.87.2.gem
    Successfully installed foreman-0.87.2
    1 gem installed
    Add bin/dev to start foreman
          create  bin/dev
    Install esbuild
             run  yarn add esbuild from "."
    yarn add v1.22.17
    info No lockfile found.
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    [3/4] 🔗  Linking dependencies...
    [4/4] 🔨  Building fresh packages...
    success Saved lockfile.
    success Saved 2 new dependencies.
    info Direct dependencies
    └─ esbuild@0.14.10
    info All dependencies
    ├─ esbuild-darwin-arm64@0.14.10
    └─ esbuild@0.14.10
    ✨  Done in 1.24s.
    Add build script
             run  npm set-script build "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds" from "."
             run  yarn build from "."
    yarn run v1.22.17
    $ esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds

      app/assets/builds/application.js      55b
      app/assets/builds/application.js.map  93b

    ✨  Done in 0.34s.
           rails  turbo:install stimulus:install
    Import Turbo
          append  app/javascript/application.js
    Install Turbo
             run  yarn add @hotwired/turbo-rails from "."
    yarn add v1.22.17
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    [3/4] 🔗  Linking dependencies...
    [4/4] 🔨  Building fresh packages...
    success Saved lockfile.
    success Saved 3 new dependencies.
    info Direct dependencies
    └─ @hotwired/turbo-rails@7.1.0
    info All dependencies
    ├─ @hotwired/turbo-rails@7.1.0
    ├─ @hotwired/turbo@7.1.0
    └─ @rails/actioncable@6.1.4
    ✨  Done in 1.04s.
    Run turbo:install:redis to switch on Redis and use it in development for turbo streams
    Create controllers directory
          create  app/javascript/controllers
          create  app/javascript/controllers/index.js
          create  app/javascript/controllers/application.js
          create  app/javascript/controllers/hello_controller.js
    Import Stimulus controllers
          append  app/javascript/application.js
    Install Stimulus
             run  yarn add @hotwired/stimulus from "."
    yarn add v1.22.17
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    [3/4] 🔗  Linking dependencies...
    [4/4] 🔨  Building fresh packages...
    success Saved lockfile.
    success Saved 1 new dependency.
    info Direct dependencies
    └─ @hotwired/stimulus@3.0.1
    info All dependencies
    └─ @hotwired/stimulus@3.0.1
    ✨  Done in 0.58s.
           rails  css:install:css
    rails aborted!
    Don't know how to build task 'css:install:css' (See the list of available tasks with `rails --tasks`)
    Did you mean?  css:install:sass
                   css:install:postcss

    (See full trace by running task with --trace)

    ➜ rails css:install:bootstrap (from within the app)
    Build into app/assets/builds
           exist  app/assets/builds
       identical  app/assets/builds/.keep
    File unchanged! The supplied flag value not found!  app/assets/config/manifest.js
    Stop linking stylesheets automatically
            gsub  app/assets/config/manifest.js
    File unchanged! The supplied flag value not found!  .gitignore
    File unchanged! The supplied flag value not found!  .gitignore
    Remove app/assets/stylesheets/application.css so build output can take over
          remove  app/assets/stylesheets/application.css
    Add stylesheet link tag in application layout
    File unchanged! The supplied flag value not found!  app/views/layouts/application.html.erb
          append  Procfile.dev
    Add bin/dev to start foreman
       identical  bin/dev
    Install Bootstrap with Popperjs/core
          create  app/assets/stylesheets/application.bootstrap.scss
             run  yarn add sass bootstrap @popperjs/core from "."
    yarn add v1.22.17
    [1/4] 🔍  Resolving packages...
    [2/4] 🚚  Fetching packages...
    [3/4] 🔗  Linking dependencies...
    [4/4] 🔨  Building fresh packages...
    success Saved lockfile.
    success Saved 20 new dependencies.
    info Direct dependencies
    ├─ @popperjs/core@2.11.2
    ├─ bootstrap@5.1.3
    └─ sass@1.47.0
    info All dependencies
    ├─ @popperjs/core@2.11.2
    ├─ anymatch@3.1.2
    ├─ binary-extensions@2.2.0
    ├─ bootstrap@5.1.3
    ├─ braces@3.0.2
    ├─ chokidar@3.5.2
    ├─ fill-range@7.0.1
    ├─ fsevents@2.3.2
    ├─ glob-parent@5.1.2
    ├─ immutable@4.0.0
    ├─ is-binary-path@2.1.0
    ├─ is-extglob@2.1.1
    ├─ is-glob@4.0.3
    ├─ is-number@7.0.0
    ├─ normalize-path@3.0.0
    ├─ picomatch@2.3.1
    ├─ readdirp@3.6.0
    ├─ sass@1.47.0
    ├─ source-map-js@1.0.1
    └─ to-regex-range@5.0.1
    ✨  Done in 1.32s.
    Appending Bootstrap JavaScript import to default entry point
          append  app/javascript/application.js
    Add build:css script
             run  npm set-script build:css "sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules" from "."
             run  yarn build:css from "."
    yarn run v1.22.17
    $ sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules
    ✨  Done in 1.17s.

I think this has been true from 7.1

Keep up the good work. Minor error, but trips one up with new version and all the great changes

**Comment by akpatternica** [comment]
--css bootstrap not -css :)

**Comment by MtnBiker** [comment]
Duh. -c bootstrap or --css bootstrap?

**Comment by DcsMarionDickten** [comment]
Had the same problem just now with Rails 8.0.5
