### ISSUE TITLE
post/delete links not working

### ISSUE THREAD

**Issue by elbarto132** [rails/rails#44121]
Ruby 3.0, Rails 7.0.1

Demo project: https://github.com/elbarto132/railspostprob

I created a new rails project, added a controller/route and added a link to the view, like this:
`<%= link_to "test", root_path, method: :post %>`
Upon checking the generated HTML code, the link tag has a data-method="post" attribute, so when pressing this link one would expect it to be a post request (same problem if I use :delete), but it's actually a GET request.

According to what I found on Google, for this option to work JQuery is required (Shouldn't there be some kind of error message, instead of failing silently?)
So I added the jquery-rails gem and required jquery and jquery_ujs in the application.js file. But this doesn't help, it's still not working, clicking on the link results in a GET request.

**Comment by billabel** [comment]
See https://github.com/heartcombo/devise/issues/5439#issuecomment-997927041

**Comment by elbarto132** [comment]
Why is this closed?
Is link_to ... method: post supposed to generate a POST request upon clicking the link?
If yes, then we have a bug.
If no, then we also have a kind of bug, because using it should at least generate a message that this option is deprecated.

**Comment by collimarco** [comment]
Please reopen.

Moreover, on delete links, the confirm does not work.

**Can you please suggest how to upgrade these links to Rails 7?**

```
<%= link_to 'Delete', menu_path(@menu), data: { confirm: 'Are you sure?' }, method: :delete %>
```

**Comment by jsphnecclia** [comment]
I also am having this issue (not running devise), neither using 
`<%= link_to 'Remove', @user, data: { turbo: false }, method: :delete %>`
nor
`<%= link_to 'Remove', @user, data: { "turbo-method": :delete } %>`
works for me, only GET and PATCH requests are ever sent
