### ISSUE TITLE
Delivering assets through CloudFlare requires monkey-patch

### ISSUE THREAD

**Issue by sedubois** [rails/rails#44136]
### Steps to reproduce

It appears that delivering ActiveStorage assets through CloudFlare (free plan) can be done as suggested [here](https://edgeguides.rubyonrails.org/active_storage_overview.html#proxy-mode) + [here](https://github.com/rails/rails/pull/34477#issuecomment-660490231):
- add `Rails.application.config.active_storage.resolve_model_to_route = :rails_storage_proxy` to `config/initializers/active_storage.rb` OR use `rails_storage_proxy_path` in the views (e.g. `rails_storage_proxy_path(content.poster.variant(resize_to_limit: [size, size]))`). There is it seems no need to define a `direct :cdn_image` like in the docs, as the CDN host remains the same when using CloudFlare.
- monkey-patch `request.session_options[:skip] = true` in the `ProxyController`s ([ref](https://github.com/rails/rails/pull/34477#issuecomment-660490231))

### Expected behavior

- No monkey-patch should be needed. 
- It would be helpful to have some documentation to use CloudFlare with ActiveStorage.

### Actual behavior

After doing the above, I can see my images have headers `cache-control: public, max-age=3155695200` and `cf-cache-status: HIT` (after the second request). However, a monkey-patch was necessary to achieve this, so @zzak [recommended](https://github.com/rails/rails/pull/42363#issuecomment-1008824861) I open this issue.

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.0.3

**Comment by brenogazzola** [comment]
I think we currently can't remove remove sessions because https://github.com/rails/rails/pull/38957 is relying on it to provide the individual service per attachment feature. That implementation is however being discussed in https://github.com/rails/rails/issues/43971.

**Comment by lypanov** [comment]
How rude.

**Comment by brenogazzola** [comment]
An alternative to monkey patching is to use one of the limited page rules that comes with free plans to force cloudflare to cache:

```
URL: https://example.com/rails/active_storage/representations/proxy*
Browser Cache TTL: a year
Cache Level: Bypass
Edge Cache TTL: a month
```

**Comment by danhodgins** [comment]
@brenogazzola  - great solution for page rule caching in Cloudflare for Active Storage. Appreciate the alternative to monkey patching. Thank you!
