### ISSUE TITLE
Tailwind not configuring properly

### ISSUE THREAD

**Issue by simonsapiel** [rails/rails#44130]
I've been having quite a bit of bugs with the tailwind configuration using esbuild. 

For starters it seems that action text doesn't get any styling when installed and for a fresh app trying to use tailwind UI's components some of the stylings also break.

Input fields end up looking like this

<img width="556" alt="Screenshot 2022-01-09 at 17 23 19" src="https://user-images.githubusercontent.com/61185966/148688765-6b0c7f9c-8861-4b33-a863-6db1756255cb.png">

when they should look like this

<img width="544" alt="Screenshot 2022-01-09 at 17 23 25" src="https://user-images.githubusercontent.com/61185966/148688786-3f45d5a4-e12a-4e39-8eec-1206efb647c4.png">

this can be verified by creating a fresh app and using the html

```html
<div class="max-w-lg flex rounded-md shadow-sm">
        <span class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 sm:text-sm">
         workcation.com/
      </span>
     <input type="text" name="username" id="username" autocomplete="username" class="flex-1 block w-full focus:ring-indigo-500 focus:border-indigo-500 min-w-0 rounded-none rounded-r-md sm:text-sm border-gray-300">
</div>
```

is there some other configuration one should consider?

**Comment by ghiculescu** [comment]
Could you share a sample repo that we can replicate the issue with? All that HTML looks like valid tailwind so that's unlikely to be the issue. It would be helpful to see configuration.
