### ISSUE TITLE
Rails 7.0.1 is not rendering localized templates if the locale includes a lowdash

### ISSUE THREAD

**Issue by jguecaimburu** [rails/rails#44154]
We are aware that the [pragmatic approach](https://guides.rubyonrails.org/i18n.html#configure-the-i18n-module) is to use just language, but regional dialects are important for our application. Also, we've noticed that most of the examples use `-` to separate locale and region code. Not sure if the `_` approach is deprecated intentionally.

### Steps to reproduce

In expected and actual behaviour I left a couple of example apps that reproduce the bug.

In `actionpack/test/controller/localized_templates_test.rb` this failing case can be added:
```rb
def test_use_locale_with_lowdash
  I18n.locale = :"de_AT"
  get :hello_world
  assert_equal "Guten Morgen", @response.body
end
```

`actionpack/test/fixtures/localized/hello_world.de_AT.html`:
```html
Guten Morgen
```

### Expected behavior
It should render the variant including the locale with lowdash.

Example:
In this [app](https://github.com/jguecaimburu/rails-blog6144):
`/` renders `show.es_AR.html` (as it is set in the controller)
`/?locale=es_AR` renders `show.es_AR.html`
`/?locale=es-AR` renders `show.es-AR.html`
`/?locale=es` renders `show.es.html`

### Actual behavior
It raises `ActionController::MissingExactTemplate`.

Example:
In the [updated version](https://github.com/jguecaimburu/rails-blog701):
`/` raises `ActionController::MissingExactTemplate`
`/?locale=es_AR` raises `ActionController::MissingExactTemplate`
`/?locale=es-AR` renders `show.es-AR.html`. If that's missing, it renders `show.es.html`
`/?locale=es` renders `show.es.html`

We've tested translation of keys with lowdash locales and it there's no issue there.

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

### Analysis

Changing the regex in `actionview/lib/action_view/template/resolver.rb:22` makes the test pass and also solves the issue in the example app:
```rb
locales = "[a-z]{2}(?:[-_][A-Z]{2})?"
```
Weird thing is that the regex is the same in both `6.1.4.4` and `7.0.1` so I'm not sure this is right, but it might give some clues. We can open a PR to fix it. We may need some guidance cc/ @diegonulinga

**Comment by Meat-Chopper** [comment]
Why don't make this regex configurable?

**Comment by rafaelfranca** [comment]
I think before we change the regexp we need to find the source cause of it. Given you already have an application that can reproduce, can you try to bisect to see which change broke this behavior. As you said this regexp is the same in 6.1 and this feature works fine there.

**Comment by jvillarejo** [comment]
I've been researching about it and I think the problem I think is in how the templates virtual paths are built. 

The resolver builds infers correctly all the views, with `es_AR`, `es-AR`, and `es` 

The problem is that the `virtual_path` isn't correct for example: 

For all this templates
`homes/show.es-AR.html`
`homes/show.es_AR.html`
`homes/show.es.html`

The virtual paths that gets build are 

The virtuals_paths the template are all:

```ruby
["homes/show", "homes/show.es_AR", "homes/show"]
```

The code on the method `unbound_templates_from_path` does this it maps correctly all the 3 templates, but the select doesn't match.

```ruby
  paths.map do |path|
    build_unbound_template(path)
  end.select do |template|
    # Select for exact virtual path match, including case sensitivity
    template.virtual_path == path.virtual
  end
```

It doesn't match because the `virtual_path` for `home/show.es_AR.html` `path.virtual` returns `homes/show.es_AR`

I think I can fix it if you point me how to do it :rocket:

**Comment by jvillarejo** [comment]
To add more info the on **6.1** the `action` that matched with the regex still had the `locale` 

`:action => "show.es_AR"` however this wasn't used to build the `virtual_path` as it was passed as an argument from outside to the method `build_unbound_template` 

In Rails 7, this `virtual_path` isn't passed as an argument on `build_unbound_template` and it gets built from the regex. 

So I think that we can change the regex, or we can set the `virtual_path` again from outside. 

I don't know the impact of this change but it works with this:

```ruby
    def build_unbound_template(template, virtual_path)
      parsed = @path_parser.parse(template.from(@path.size + 1))
      details = parsed.details
      source = source_for_template(template)

      UnboundTemplate.new(
        source,
        template,
        details: details,
        virtual_path: virtual_path,
      )
    end

    def unbound_templates_from_path(path)
      if path.name.include?(".")
        return []
      end

      # Instead of checking for every possible path, as our other globs would
      # do, scan the directory for files with the right prefix.
      paths = template_glob("#{escape_entry(path.to_s)}*")
      paths.map do |p|
        build_unbound_template(p, path.virtual)
      end
    end
```

**Comment by jvillarejo** [comment]
We might say that lowdash wasn't supported even in Rails 6.1 (because the regex wasn't matching it as locale) but it still worked.

But in Rails 7 it stopped working because of the way the `virtual_path` is now passed to the `UnboundTemplate`. 

Somehow If we are going to fix it, I think the correct way would be to change the regex.
But it present me this dilemma: Should we update it for previous supported versions too? 

What's the best decision here?

**Comment by jguecaimburu** [comment]
Adding to the questions above, just tried a few more things.

In 6.1 if we keep the locale regex but change the action regex to ignore the wrong locale part (matching `action: "show", locale: nil` instead of `action: "show.es_AR", locale: nil`), it stills renders `show.es_AR.html`. So if lowdash was not supported, just changing the regex to ignore the wrong format wouldn't fix the issue.

**Comment by jguecaimburu** [comment]
I believe I've found what changed.

In 6.1 even if the path gets changed in a debugging session to make the captured action be any string, it still renders the correct view with the lowdash. `OptimizedFileSystemResolver` calls `find_template_paths_from_details(path, details)`, with `details` including the `I18n.locale` and it's fallbacks. Then the regex that gets used to find the templates is this one:
```rb
/\A\/path\/to\/blog6144\/app\/views\/homes\/show(\.(?<locale>es_AR|en))?(\.(?<formats>html))?(\+(?<variants>))?(\.(?<handlers>raw|erb|html|builder|ruby|jbuilder))?\z/
```
Which has the actual `I18n` config instead of inferring the locale with a regex. `build_unbound_template` then receives that template and the virtual path, which gets built with the `name` of the action received by the resolver (no regex here). I believe that's why it works.

In Rails 7, the templates search changes. `FileSystemResolver` in `_find_all` also has access to `TemplateDetails::Requested` that include the `I18n.locale` and fallbacks. The issue, as mentioned before by @jvillarejo, is that `build_unbound_templates` uses the strict regex from `PathParser` to build the `UnboundTemplate`, so it gets the wrong action including whatever the file has in it's name. When comparing `template.virtual_path == path.virtual`, the file gets filtered.

But after that filter there's this method that compares the requested details with the candidate templates: `filter_and_sort_by_details(templates, requested_details)`. If the `I18n.locale` does not match the regex, the file won't be here, so the template missing error gets raised.

My take on this is that the regex mentioned in the issue works as a filter that allows only the expected locale format (ex: `:es` or `:es-AR`) by capturing a wrong action if the locale does not match (not sure if this was expected). It was not working in 6.1 but it is doing that now. The fix (if wanted or needed) could be to extend the regex to allow the lowdash or to allow any locale accepted by the `I18n` gem to be used in a localized view file. Any thoughts about this?

**Comment by jguecaimburu** [comment]
Hi @jhawthorn. I think the reported behaviour changed in this commit: https://github.com/rails/rails/commit/9e0c42b0bde91da41745e2bcf4a14bfefdc72fc0
From the commit description I get it was intended to match templates with `PathParser` details instead of building a dynamic regex.

Is it intended that any unmatched part of the path ends up being part of the captured `:action` in that regex? Do you believe it makes sense to extend the locale regex to accept lowdash?

**Comment by jhawthorn** [comment]
> Is it intended that any unmatched part of the path ends up being part of the captured `:action` in that regex? Do you believe it makes sense to extend the locale regex to accept lowdash?

Yes, I believe that makes sense. Would you mind opening a PR and CC-ing me? 😁

**Comment by jguecaimburu** [comment]
Done! https://github.com/rails/rails/pull/44174
