### ISSUE TITLE
How can I turn off dark mode on error screen?

### ISSUE THREAD

**Issue by HeppokoNeet** [rails/rails#44153]
Sorry..
maybe it has already an issue..

When I transferred to Rails7.0, theme of error screen was changed.
It looks like dark mode.

From Rails5.x, It's really weird.
I really want to change back.
How can I do that?

**Comment by rafaelfranca** [comment]
Thank you for the issue. There is no way to do that, sorry, but you can probably hack something in your browser to force the the light mode to be used.
