### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/not-found"):

### ISSUE THREAD

**Issue by arbutt1010** [rails/rails#44155]
### Steps to reproduce

I have dockerize my project everything is working fine locally my docker containers are working fine locally but when I run my container on server it work on http by appending port on the end of my url for instance http://mydomain.com:3000 but when I try to access with this url https://mydomain.com it give the error given below in Actual Behavior. I just want to know what could be the root cause definietly the issue is regarding redirection can anyone guide how can we handle redirection in Ruby on Rails from http => https

```ruby
# Your reproduction script goes here
```

### Expected behavior

=> Booting Puma
web_1  | => Rails 5.1.4 application starting in development
web_1  | => Run `rails server -h` for more startup options
web_1  | Puma starting in single mode...
web_1  | * Version 4.3.5 (ruby 2.4.10-p364), codename: Mysterious Traveller
web_1  | * Min threads: 2, max threads: 2
web_1  | * Environment: development
web_1  | * Listening on tcp://0.0.0.0:3000
web_1  | Use Ctrl-C to stop
web_1  | Started GET "/" for 182.180.66.230 at 2022-01-12 06:10:36 -0800
web_1  | Cannot render console from 182.180.66.230! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
web_1  |    (1.7ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
web_1  | Processing by HomeController#index as HTML
web_1  |   Rendering home/index.html.erb
web_1  |   Rendered home/index.html.erb (519.3ms)
web_1  | Completed 200 OK in 524ms (Views: 523.6ms | ActiveRecord: 0.0ms)
### Actual behavior

Actual Behavior
=> Booting Puma
web_1  | => Rails 5.1.4 application starting in development
web_1  | => Run `rails server -h` for more startup options
web_1  | Puma starting in single mode...
web_1  | * Version 4.3.5 (ruby 2.4.10-p364), codename: Mysterious Traveller
web_1  | * Min threads: 2, max threads: 2
web_1  | * Environment: development
web_1  | * Listening on tcp://0.0.0.0:3000
web_1  | Use Ctrl-C to stop
web_1  | Started GET "/" for 172.21.0.1 at 2022-01-12 06:09:00 -0800
web_1  | Cannot render console from 172.21.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
web_1  |    (1.6ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
web_1  | Processing by HomeController#index as HTML
web_1  |   Rendering home/index.html.erb
web_1  |   Rendered home/index.html.erb (445.3ms)
web_1  | Completed 200 OK in 450ms (Views: 448.9ms | ActiveRecord: 0.0ms)
web_1  |
web_1  |
web_1  | Started GET "/not-found" for 172.21.0.1 at 2022-01-12 06:09:01 -0800
web_1  | Cannot render console from 172.21.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
web_1  | No route matches [GET] "/not-found" excluded from capture: DSN not set
web_1  |
web_1  | ActionController::RoutingError (No route matches [GET] "/not-found"):
web_1  |
web_1  | actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
web_1  | web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web_1  | web-console (3.5.1) lib/web_console/middleware.rb:20:in `block in call'
web_1  | web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web_1  | web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
web_1  | actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
web_1  | railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
web_1  | railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
web_1  | activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
web_1  | activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
web_1  | activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
web_1  | railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
web_1  | sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
web_1  | actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
web_1  | actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
web_1  | rack (2.0.3) lib/rack/runtime.rb:22:in `call'
web_1  | activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
web_1  | actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
web_1  | actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
web_1  | rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
web_1  | sentry-raven (2.7.1) lib/raven/integrations/rack.rb:51:in `call'
web_1  | rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
web_1  | railties (5.1.4) lib/rails/engine.rb:522:in `call'
web_1  | puma (4.3.5) lib/puma/configuration.rb:228:in `call'
web_1  | puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
web_1  | puma (4.3.5) lib/puma/server.rb:472:in `process_client'
web_1  | puma (4.3.5) lib/puma/server.rb:328:in `block in run'
web_1  | puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'

### System configuration
**Rails version**:
Rails Version: Rails 5.1.4
**Ruby version**:
Ruby Version: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by hahmed** [comment]
Hey @arbutt1010, thanks for reporting this issue. Sounds like https://discuss.rubyonrails.org is more better suited for this as it seems related to a setup issue and not rails itself. May be worth sharing the Dockerfile/docker-compose file if that's possible? 

Going to go ahead and close this for now, but if you find there is an issue w/ rails itself please do report back.

Whilst i'm here though, couple of quick things;
- The docker app is running in development mode on the server you are deploying... maybe you could pass in the RAILS_ENV=production option?
- May be worth looking at https://api.rubyonrails.org/classes/ActionDispatch/SSL.html?
