### ISSUE TITLE
[ActiveStorage::Variant] Calling `variant.key` on a preloaded object should not trigger a database `Load`

### ISSUE THREAD

**Issue by nduitz** [rails/rails#44165]
### Steps to reproduce

```ruby
user = user.avatar.includes(avatar_attachment: [blob: variation_records])

variant = user.avatar.variant({ format: :webp, resize_to_fill: [200, 200] })

# works without load
variant.blob.key
# works without load
variant.variation.key

# triggers database load of ActiveRecord::Attachment and ActiveRecord::Blob
variant.key
```

### Expected behavior
When I call `ActiveStorage::Variant.key` on a preloaded database object `ActiveRecord::Attachment` and `ActiveRecord::Blob` should not be loaded from the database again. 

The method `key` according to the code calls `blob.key` and `variation.key` 
```ruby
  def key
    "variants/#{blob.key}/#{OpenSSL::Digest::SHA256.hexdigest(variation.key)}"
  end
```
Both attributes can be called directly from the object without triggering a load.

### Actual behavior
Calling `variant.key` on a preloaded database object triggers a database load.

### System configuration
**Ruby version**: `2.7.5`

**Rails version**: `6.1.4` - tested on `7.0.1` as well

**Comment by khasinski** [comment]
I don't understand how to reproduce your exact situation, the first line in your example doesn't work for me, I'm not sure what `user` is in this context and why it gets redefined and what's `variation_records`. `avatar.variant_records` perhaps?

Still I'm giving it a go:

- the relation to `variant_records` is named...well: `variant_records`. If you preload it with `variant.blob.variation_records.load` it won't load the `ActiveStorage::VariantRecord` which is what actually loads every time you call `variant.key`.
- the load happens in https://github.com/rails/rails/blob/65e4e4e9acf9a872db5185f81eda842db606d3b3/activestorage/app/models/active_storage/variant_with_record.rb#L51-L57 and it's cached in `ActiveStorage::VariantWithRecord` as `@record`. 

Please try (starting with your second line)

```ruby
variant = user.avatar.variant({ format: :webp, resize_to_fill: [200, 200] })

# This preloads the variant records manually
variant.blob.variant_records.load

# There should be no Load
variant.key
```

**Comment by Sohair63** [comment]
This issue still occurs in `rails 7.1.2`, when calling `version.key` on preloaded data, triggering a query in the database
<img width="1266" alt="Screenshot 2024-01-09 at 7 02 22 PM" src="https://github.com/rails/rails/assets/8349026/badd750c-de51-4603-9402-e364d1f5acb0">
