### ISSUE TITLE
Records are deleted without an "Are you sure?" prompt.

### ISSUE THREAD

**Issue by btrewern** [rails/rails#44163]
Rails 7.0.1
Ruby 2.7.5

After creating a new application and then a simple scaffold the destroy button on the show view does not have an "Are you sure?" prompt before it deletes the record.

I think this is an oversight when the scaffold template was updated.  See here: https://github.com/rails/rails/blob/83a4fa414bc9e5008825f47857fdd80e85c82033/railties/lib/rails/generators/erb/scaffold/templates/show.html.erb.tt#L9

Thanks.

**Comment by billabel** [comment]
This was removed because UJS is not longer installed by default.

See:
https://github.com/rails/rails/pull/41210/files
https://github.com/rails/tailwindcss-rails/commit/196825ff41633a538a659e89d73cbeb007cc461e
