### ISSUE TITLE
Rails 7: link_to delete not working (wrong redirect)

### ISSUE THREAD

**Issue by collimarco** [rails/rails#44170]
### Steps to reproduce

View:

```
<%= link_to "Destroy", @question, data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' } %>
```

Controller:

```
  def destroy
    @question = current_user.questions.find(params[:id])
    @question.destroy
    redirect_to questions_url, notice: "Question was successfully destroyed."
  end
```

### Expected behavior
The question is deleted and the user redirected to the questions index.

### Actual behavior
The question is deleted and the user is redirected to the question (instead of question index as defined in the controller!)  where he gets an obvious error:

```
ActiveRecord::RecordNotFound in QuestionsController#show
Couldn't find Question with 'id'=6
inside def show
```

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 3.1

**Comment by AlexKovynev** [comment]
try to add status to redirect like here "redirect_to root_path, status: :see_other"
Look into examples https://guides.rubyonrails.org/getting_started.html

**Comment by collimarco** [comment]
@AlexKovynev Thanks! **Adding `status: :see_other` fixes the issue.** 

However I have been developing with Rails for 10+ years and never used that code... Why now it is required to set the status?

 Is it a "bug" with `redirect_to` or with `turbo` that should be fixed? If 303 is now required - it wasn't in the past - why isn't it used automatically by `redirect_to`?

**Comment by akpatternica** [comment]
As i understood it is not a bug. It is a new requirement for turbo.

**Comment by ohpreis** [comment]
Thanks, @AlexKovynev for the `status: :see_other` solution. Now the delete works. 
By any chance do you know why the `turbo_confirms` does not fire on click? Here is what my link looks like. 

`<%= link_to "Destroy", @author, data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %>`

Thanks

**Comment by rafaelfranca** [comment]
See https://guides.rubyonrails.org/getting_started.html#deleting-an-article

**Comment by ohpreis** [comment]
@rafaelfranca, thank you for responding  - This is where I did get the code from, by following the "Getting Started" guide. 

Interestingly enough, everything is working as expected, except that the `data: { turbo_method: :delete, turbo_confirm: "Are you sure?"` does not popup a confirmation dialog. I must be missing something and perhaps I will simply redo the tutorial.

**Comment by MattBudz** [comment]
@ohpreis you are not going crazy. I can confirm that `data: { turbo_confirm: "Are you sure?" }` also doesn't work for me.

My system configuration is:
Rails version: 7.0.2
Ruby version: 3.0.3

**Comment by rafaelfranca** [comment]
Thanks for confirming it is not working. Can you publish this application somewhere public so we can take a look?

**Comment by AlexKovynev** [comment]
standard example from documentation is working <%= link_to "Destroy", article_path(@article), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} % @MattBudz try with clean application, it seems maybe you have no turbo after update. Or maybe you use a button so see https://github.com/hotwired/turbo-rails/issues/302

**Comment by miclain** [comment]
I had this problem, was solved by using the code like this:
data: { "turbo-method": :delete , "turbo-confirm": "Are you sure?"}

**Comment by MattBudz** [comment]
@rafaelfranca @AlexKovynev yea this was definitely a PEBCAK issue on my end. I was using `button_to` rather than `link_to`. 

[This comment](https://github.com/hotwired/turbo-rails/issues/302#issuecomment-1022584571) from @excid3 solved my issue:

```ruby
<%= button_to "Sign out", logout_path, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } %>
```

Spinning up a new app, the default example works for `link_to`:
```ruby
<%= link_to "Destroy", article_path(https://github.com/Article), data: {
turbo_method: :delete,
turbo_confirm: "Are you sure?"
} %>
```

Also, I confirmed that both of these variations work as expected: 
- `data: { "turbo-method": :delete , "turbo-confirm": "Are you sure?"}`
- `data: { turbo_method: :delete , turbo_confirm: "Are you sure?"}` work as expected.

**Comment by michael-reeves** [comment]
None of these options are working for me.  I just tried moving up to Rails 7.0.2.3 from 7.0.2.2, but still no luck.  I'm using Ruby 3.1.1.  The only thing that did work was switching to 
```ruby
  <%= button_to "Delete", @event, class: "button", 
                form: {
                  data: { turbo_method: :delete, turbo_confirm: "Really?!?" } 
                } %>
```
but this isn't ideal.   Would really like to have `link_to` working

Failed attempts:
```ruby
<%= link_to "Delete", @event, class: "button",
              data: { turbo_method: :delete, turbo_confirm: "Really?!?" } %>
<%= link_to "Delete", @event, class: "button",
              data: { "turbo-method": :delete, "turbo-confirm": "Really?!?" } %>
```

is there some way to test if Turbo is running correctly?  Or a configuration setting someplace I need to enable?  I ran `rails turbo:install` just to see what would happen and it complained about not having node or importmap.  My original installation doesn't appear to have installed `importmap`, but I just ran a new project and Rails seems to have called that.  Is this something I need to bootstrap back into my active project?

**Comment by rafaelfranca** [comment]
Does this work?

```erb
<%= link_to "Delete", @event, { data: { turbo_method: :delete, turbo_confirm: "Really?!?" } },
              class: "button" %>
<%= link_to "Delete", @event, { data: { "turbo-method": :delete, "turbo-confirm": "Really?!?" } },
              class: "button" %>
```

**Comment by rafaelfranca** [comment]
Actually, that should not work, that is wrong syntax. I can see with your call a link with `data-turbo-method` is created. So there is nothing wrong in the HTML generated by Rails.

**Comment by michael-reeves** [comment]
For anyone else coming across this, this solved the issue for me.
```bash
$ rails importmap:install
$ rails turbo:install stimulus:install
```
I saw those lines in the installation of a new Rails app with 7.0.2.3, where the associated files did not exist in my 7.0.2.2 installation.  After running those commands and restarting my app,
```ruby
<%= link_to "Delete", @event, class: "button",
              data: { turbo_method: :delete, turbo_confirm: "Really?!?" } %>
```
works perfectly.

HTH

**Comment by michael-reeves** [comment]
As a small addition here.  To get it working with rspec feature specs, `without selenium`, I've resorted to:
```ruby
<%= link_to "Delete", @event, method: :delete, class: "button",
                     data: { turbo_method: :delete, turbo_confirm: "Really?" } %>
```
It's a little convoluted to say :delete twice, but it works both in specs and in browser testing.

**Comment by vkononov** [comment]
> ```ruby
> <%= link_to "Delete", @event, class: "button",
>               data: { turbo_method: :delete, turbo_confirm: "Really?!?" } %>
> ```

This presents the confirm dialog, but the redirect does not work correctly when using `link_to` instead of `button_to`

**Comment by vkononov** [comment]
@miclain Yes, you're right. Adding `status :see_other` was the missing piece. It's clunky, but it does work.

**Comment by Gibson2** [comment]
This is my case with **link_to** the solution was to add in the controller> `status :see_other`

![image](https://user-images.githubusercontent.com/24903283/173261223-acb8b9a9-77a0-443e-ac83-8268f838b956.png)
![image](https://user-images.githubusercontent.com/24903283/173261268-399c7d2e-c686-4f10-85d2-d6a565b444e0.png)

**Comment by salex** [comment]
I've been fighting this whole delete tag helper since January. In the two apps I upgraded I ended up created a destroyConfirmTag helper that used stimulus to ask the confirm message.

I can confirm that both:

```ruby
<%= link_to "Delete", @event, class: "button",
              data: { turbo_method: :delete, turbo_confirm: "Really?!?" } %>
and

<%= button_to "Delete", @event, class: "button", 
            form: {
                  data: { turbo_method: :delete, turbo_confirm: "Really?!?" } 
             } %>
```
work in the latest version of rails. I was just kind of lucky to find the button_to needed the form: key wrapping. But:

1. Rails 7.0.3 scaffold now generates _button_to_ links (without confirm tags, which are not documented)
2. Getting started guide does not talk about _button_to_
3. The redirect 303 stuff is not well known but it can get you ( I had all records in one model deleted!!!)
4. I sense a move to _button_to_

**Comment by cielolucas** [comment]
**This really helped me!**

> I use Rails 7 and this really works

> I know this is closed, but I've been fighting this whole delete tag helper since January. In the two apps I upgraded I ended up created a destroyConfirmTag helper that used stimulus to ask the confirm message.
> 
> I can confirm that both:
> 
> ```ruby
> <%= link_to "Delete", @event, class: "button",
>               data: { turbo_method: :delete, turbo_confirm: "Really?!?" } %>
> and
> 
> <%= button_to "Delete", @event, class: "button", 
>             form: {
>                   data: { turbo_method: :delete, turbo_confirm: "Really?!?" } 
>              } %>
> ```
> 
> work in the latest version of rails. I was just kind of lucky to find the button_to needed the form: key wrapping. But:
> 
> 1. Rails 7.0.3 scaffold now generates _button_to_ links (without confirm tags, which are not documented)
> 2. Getting started guide does not talk about _button_to_
> 3. The redirect 303 stuff is not well known but it can get you ( I had all records in one model deleted!!!)
> 4. I sense a move to _button_to_
