### ISSUE TITLE
[Rails 7.0.1] does not update a record with nested attributes and active storage

### ISSUE THREAD

**Issue by one0fnine** [rails/rails#44180]
* Rails 7.0.1
* Ruby 3.1.0

`app/model/account.rb`
```ruby
class Account < ApplicationRecord
  has_one :attachment, as: :record, inverse_of: :record
  accepts_nested_attributes_for :attachment, update_only: true, allow_destroy: true
end
```

`app/models/attachment.rb`
```ruby
class Attachment < ApplicationRecord
  belongs_to :record, polymorphic: true
  has_one_attached :resource
end
```

Reproduce steps:
```ruby
resource = Account.first
params = {attachment_attributes: {resource: "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWt3TlRFd05XUm1PUzB3TVdZekxUUmhZamN0WVdZMlppMDRZVGczT1RSaE1XVXpNellHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--1dd4b93fc8e80f604ccc046b492df66dfcc06e72"}}

resource.update! params
=> true

resource.update! params
ArgumentError: wrong number of arguments (given 3, expected 0)
from /usr/local/bundle/gems/activerecord-7.0.1/lib/active_record/associations/builder/belongs_to.rb:132:in `record_changed?'

resource.reload.update! params
=> true
```
`signed_id` is valid. I've uploaded a file before.

**Comment by uxxman** [comment]
The resource attribute needs to be a file or an attachable stream. It cannot be a string value.

**Comment by one0fnine** [comment]
> The resource attribute needs to be a file or an attachable stream. It cannot be a string value.

According by https://api.rubyonrails.org/classes/ActiveStorage/Attached/One.html#method-i-attach i can attach a file by signed_id and i can do it in Rails 6.1.
I mean, the resource attribute is signed_id, not a just string value.

**Comment by eugeneius** [comment]
Fixed in https://github.com/rails/rails/pull/44191.
