### ISSUE TITLE
Rails 7: link_to method: :delete not working

### ISSUE THREAD

**Issue by collimarco** [rails/rails#44185]
### Steps to reproduce

Example:

```
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>
```

The API docs for Rails 7 clearly state that you can use `method: :delete`, there are even some examples.

### Expected behavior
A DELETE request is made.

### Actual behavior
A GET request is made (i.e. `method: :delete` is ignored)

### System configuration
**Rails version**: 7.0.1
**Ruby version**: 3.1

### Related issues

This issue is similar, but not the same: https://github.com/rails/rails/issues/44170

This issue is about `method: :delete` which does not work.

The linked issue is about a wrong redirect when you use `'turbo-method': :delete`.

**Comment by willyjie** [comment]
because `rails-ujs` is remove :)

**Comment by rafaelfranca** [comment]
`method: :delete` really doesn't work. It needs to be `turbo_method: :delete` if you are using Rails default stack. See https://guides.rubyonrails.org/getting_started.html#deleting-an-article

**Comment by collimarco** [comment]
@rafaelfranca In any case the API reference is wrong and needs to be updated, that's why I opened this issue:

https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to

In my original post:

> The API docs for Rails 7 clearly state that you can use method: :delete, there are even some examples.

**Comment by rafaelfranca** [comment]
It was already updated. See https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to

**Comment by byteg** [comment]
I face the same problem with Rails 7.0.2.3
Non of the methods works:

1. data: { turbo_method: :delete }
2. data: { method: :delete }
3. method: :delete

**Comment by byteg** [comment]
Sorry I bothered you. Everything works if I run:
`
$ rails importmap:install
$ rails turbo:install stimulus:install
`

**Comment by Abdelrahman-kamall** [comment]
> Sorry I bothered you. Everything works if I run: `$ rails importmap:install $ rails turbo:install stimulus:install`

yes it worked , thank you .. 
can some one explain what these lines do , after a quick search i came up to a conclusion that this had something to do with java script , bec delete req uses js , that caused the delete req to be handeled as a get req , why does this happen and how to prevent it happening again ?

**Comment by EricYoung37** [comment]
For Rails 7.0.3.1, edit and delete are a bit different from what is shown in this article: https://guides.rubyonrails.org/getting_started.html#deleting-an-article

Run
`$ rails importmap:install`
then
`$ rails turbo:install stimulus:install`
as suggested by others.

For edit, it should be:
`<%= link_to "Edit", edit_article_path(article) %>`
No `@` in the parentheses.

For delete, it should be:
```
<%= link_to "Destroy", article, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
```
`article_path(@article)` doesn't seem to work.

**Comment by michalwiacek** [comment]
what if I don't wanna use turbo in my legacy code?

**Comment by michalwiacek** [comment]
> 

could You tell me how to accomplish that with esbuild setup? I've tried passing this into application.js
```
import Rails from "@rails/ujs";
Rails.start();
```
but linkt_to with `method: :delete` and `data: { confirm: "confirmaton needed" }` still wont sending get request without confirmation

**Comment by iVieL** [comment]
> Sorry I bothered you. Everything works if I run: `$ rails importmap:install $ rails turbo:install stimulus:install`

Hey there, I tried those steps, but rails 7.0.3.1 looks to don't have `importmap:install` task, just these

![image](https://user-images.githubusercontent.com/1512543/187950391-f6c8574f-6d64-4771-9aec-ef66242fb4c7.png)

the `link_to` with any of these combinations doesn't work yet:

>I face the same problem with Rails 7.0.2.3
> Non of the methods works:
>
>    data: { turbo_method: :delete }
>    data: { method: :delete }
>    method: :delete

as an additional info, I'm kind of new with RoR.
The tutorial that I'm following is using:
* hamlit
* hamlit-rails
* simple_form

and was created like this:
`rails new project_name --css bootstrap -T --database=postgresql`

any other clue or tip to solve the issue?

**Comment by iVieL** [comment]
I was able to resolve the issue following this other steps:

* Install hotwire-rails `bundle add hotwire-rails`
ref: [hotwire-turbo-replacing-rails-ujs](https://www.driftingruby.com/episodes/hotwire-turbo-replacing-rails-ujs)
* follow these steps [installing importmaps and hotwire](https://github.com/hotwired/hotwire-rails/issues/41#issuecomment-946649719)

now `link_to` is working even with confirmation dialog.

**Comment by Debadattajena080** [comment]
> 

it worked for me

**Comment by curtisbarnard** [comment]
> to add if anyone else struggling. The following worked with me using the following set up
> 
> ```
> ruby "3.0.0"
> gem "rails", "~> 7.0.2", ">= 7.0.2.3"
> gem 'devise', '~> 4.8', '>= 4.8.1'
> ```
> 
> First do this
> 
> > $ rails importmap:install $ rails turbo:install stimulus:install
> 
> you may have to do this first if you get errors:
> 
> > $ rails redis:install
> 
> make sure you are using `data: { turbo_method: :delete }` in your `link_to` method. I found that `method: :delete` was not working
> 
> example of working code. `<%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>`

I was following the free code camp Rails course and came upon this issue. Doing the above seems to have fixed it. Thanks!

**Comment by peoplenamed** [comment]
I had the same issue and fixed it by adding `= javascript_importmap_tags` under my `= javascript_include_tag` inside the application.html.erb file.

**Comment by ali-p-q** [comment]
In my case the problem was that I had turbo Drive configured to work on a per element basis in my application.js, as shown here: https://turbo.hotwired.dev/handbook/drive but I could not get the `data-turbo="true"` to work (I don't know where exactly I am supposed to put that or if the tag format is wrong in the documentation). So I simply changed my application.js to always use turbo Drive.
``
import { Turbo } from "@hotwired/turbo-rails"
Turbo.session.drive = true
```

**Comment by ali-p-q** [comment]
In my case the problem was that I had turbo Drive configured to work on a per element basis in my application.js, as shown here: https://turbo.hotwired.dev/handbook/drive but I was struggling to get the `data-turbo="true"` mentioned  in the documentation to work .

Until I tried this, and it worked: `data: { turbo: true, turbo_method: :delete }`
Another option is to turn on turbo Drive globally, like this:
```
import { Turbo } from "@hotwired/turbo-rails" 
Turbo.session.drive = true
```
In which case, the "turbo true" part is not necessary and this works: `data: { turbo_method: :delete }`. Notice that using just `method: :delete` will not work.

**Comment by lyc4n** [comment]
Encountered the issue in 7.0.4.3 but it turned out I had to run ./bin/dev because `rails server` alone does not compile the assets. I got so much used to the old version. Hope this helps.

**Comment by mamboZero** [comment]
> 

i can confirm this work! tq

**Comment by hansonfox** [comment]
I met the same problem and added this line into application.html.erb file to solve it . and it works fine
under `<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>`
+++ `<%= javascript_include_tag  "turbo" ,type: "module" %>`

**Comment by Ivan-Sizyh** [comment]
Аll is good on Rails 7.0.8 just use gem 'turbo-rails' in your gemfile use the import '@hotwired/turbo-rails'  in yaou application.js and write command yarn add @hotwired/turbo-rails or write in dependencies in to your package.json dependencies: { "@hotwired/turbo-rails": "^8.0.0-beta.1" } it's work for me. But i am create prod with -skip-hotwire. If you are have problems write the comments to me

**Comment by DogAndCode** [comment]
> I met the same problem and added this line into application.html.erb file to solve it . and it works fine under `<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>` +++ `<%= javascript_include_tag "turbo" ,type: "module" %>`

This works for me. Why is that?

**Comment by smtlaissezfaire** [comment]
What about something like this:

```export function convertPostLinks() {
  document.querySelectorAll('a[data-method="post"]').forEach((link) => {
    link.addEventListener("click", function (e) {
      e.preventDefault();

      const form = document.createElement("form");
      form.method = "POST";
      form.action = this.getAttribute("href");

      const csrfToken = document.querySelector(
        'meta[name="csrf-token"]'
      ).content;
      const csrfInput = document.createElement("input");
      csrfInput.type = "hidden";
      csrfInput.name = "authenticity_token";
      csrfInput.value = csrfToken;

      form.appendChild(csrfInput);
      document.body.appendChild(form);
      form.submit();
    });
  });
}
```

which you can then hook in with:
```
document.addEventListener("turbo:load", () => {
  convertPostLinks();
});
```

without loading rails-ujs and keeping the old behavior?
