### ISSUE TITLE
Ruby-3.1.0 Rails-7.0.1 new APP railties error

### ISSUE THREAD

**Issue by coopeu** [rails/rails#44208]
_### Steps to reproduce_
install LAMP on a new DEBIAN Private Server  and install rvm for installing Ruby and Rails

_# Your reproduction script goes here_
rails new APP -d mysql --css TAILWIND

_### Expected behavior_
build a new initial rails app skeleton

_### Actual behavior_
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
/home/user/.rvm/gems/ruby-3.1.0/gems/railties-7.0.1/lib/rails/generators/rails/app/app_generator.rb:250:in ``': 
No such file or directory - git (Errno::ENOENT`
250:in `user_default_branch
76:in `version_control'
134:in `public_send'
320:in `create_root_files'
...

_### System configuration_
DEBIAN 10.11
rvm 1.29.12
gem 3.3.5
ruby 3.1.0p0
Rails 7.0.1

**Comment by SkipKayhil** [comment]
> `No such file or directory - git`

It looks like you don't have git installed. You can use `--skip-git` if you don't want it to initialize a repository for you

**Comment by coopeu** [comment]
Thanks you very much
Currently the rails constructor work perfectly.
1) How to install git in RoR app?
2) How to fix An error occurred while installing mysql2 (0.5.3)?

**Comment by SkipKayhil** [comment]
The error is probably because you're missing a mysql package, you can use debian's package manager to install both `git` and one of the packages listed [here](https://github.com/brianmario/mysql2#linux-and-other-unixes) to fix the mysql issue

**Comment by coopeu** [comment]
All perfect now! 
Exploring new rails 7.0.1 features
Thank you very much
