### ISSUE TITLE
credentials:edit mapping values error

### ISSUE THREAD

**Issue by coopeu** [rails/rails#44217]
### Steps to reproduce
New RoR app
EDITOR='nano' bin/rails credentials:edit
The same credentials edition is working perfectly in rails 7.0.0 and ruby 3.0.1p64

### Expected behavior
secret_key_base: 1...............................$
mysql:
  username:
    default: user
  password:
    default: password0123456

### Actual behavior
After editing and before saving (it's not saved) console error:
/home/user/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/psych.rb:455:in `parse': (<unknown>): mapping values are not allowed in this context at line 2 column 16 (Psych::SyntaxError)

### System configuration
**Rails version**: 7.0.1
**Ruby version**: 3.1.0

**Comment by kunashir** [comment]
@coopeu I cannot reproduce your problem.
I am not sure for 100% but probably you have an incorrect structure in your credentials file.

**Comment by coopeu** [comment]
Thanks problem solved.
