### ISSUE TITLE
ActionController defaulting response to turbo_stream

### ISSUE THREAD

**Issue by dvodvo** [rails/rails#44225]
Logging:
```
Started POST "/messages/sms_post" for 127.0.0.1 at 2022-01-21 10:50:18 +0100
Processing by MessagesController#sms_post as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "message"=>{"room_id"=>"1", "content"=>"sdfkjsndflwdfsdfksdfk. ~éùìòÇØøÅåΔ^€{}[]~"}, "commit"=>"Create Message"}
49
1
No template found for MessagesController#sms_post, rendering head :no_content
Completed 204 No Content in 3ms (ActiveRecord: 0.0ms | Allocations: 1108)
```
### Steps to reproduce
where routes define:
```
  resources :messages do
    collection do
      get   :sms_pre
      post  :sms_post
    end
  end
```
these are controller actions (not pertinent to issue) to count SMS characters :
```
  def sms_pre
    @message = Message.new
  end
  
  def sms_post
    sms_count(params[:message][:content])
  end
```
Note: there is a view `<%# turbo_stream.append 'messages', @message %>
<% #return handled by cable %>` but that should not have any impact here.
### Expected behavior

Expecting a posting as 'HTML'

### Actual behavior

`Processing by MessagesController#sms_post as TURBO_STREAM`  was unexpected, as   the only reference to turbo_stream is on the messages_create action
```
  message = Message.create!(message_params)
    respond_to do |format|
      if message.save
        format.turbo_stream
        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
```
It appears as the POST on an object `.new` is processing via the **first** respond command for the create action *in absence of such a definition in the action itself*

To my recollection Rails < 7 would attempt to render to html by default.   But this could also have been a direction to the first create action rendering definition & I had only experienced HTML.  Just trying to clarify...  
Has this changed in Rails 7? if so, I have not seen the information documented (and my have missed it)

### System configuration
**Rails version**:  7.0.1

**Ruby version**: 3.1

**Comment by nick-symon** [comment]
Hi, it would be helpful to include a [test case](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case)

**Comment by dvodvo** [comment]
Hi, I uploaded the sandbox where a number of rails 7 experiments were effected:  https://github.com/dvodvo/seven

**Comment by dvodvo** [comment]
Actually it is the `sms_pre.html.erb` view that posts to 
```
<%= form_with(scope: @message, url: sms_post_messages_path) do |form| %>
```

**Comment by nick-symon** [comment]
Is this being rendered inside of a turbo frame as a partial? Have you tried setting `data-turbo="false"` on that form?

https://turbo.hotwired.dev/handbook/drive#disabling-turbo-drive-on-specific-links-or-forms
https://www.viget.com/articles/five-turbo-lessons-i-learned-the-hard-way/

**Comment by dvodvo** [comment]
No, it is not a partial.  I was not trying to break out of anything, I was expecting the application to respond as HTML.

So now form_with will default to TURBO_STREAM ?

**Comment by nick-symon** [comment]
1. In what context is sms_pre.html.erb being rendered in your application? I.E what view? 
2. Have you tried changing the data-turbo attribute to false per my comment above?
3. Finally, have you looked at the issues in the `turbo-rails` gem? Again this appears to be an issue with that gem, not rails itself, so I'd check that out. [This issue](https://github.com/hotwired/turbo-rails/issues/122) might be related to the issue you face.
