### ISSUE TITLE
DateTime calculation functions use other timezone offset than the original time

### ISSUE THREAD

**Issue by emilkappert** [rails/rails#44226]
### Steps to reproduce
```ruby
brisbane = TZInfo::Timezone.get('Australia/Brisbane')

local_time_in_brisbane = brisbane.now
local_time_in_brisbane # returns: 2022-01-21 20:32:39.878438 +1000

# actual
local_time_in_brisbane.beginning_of_day # returns: 2022-01-21 00:00:00 +0100

# expected for the beginning of day
local_time_in_brisbane.change(hour: 0, offset: local_time_in_brisbane.timezone_offset.base_utc_offset) # returns: 2022-01-21 00:00:00 +1000
```

### Expected behavior
When trying to get the beginning of the day of a time in a specific timezone, the offset is taken into account 
```ruby
local_time_in_brisbane.beginning_of_day == local_time_in_brisbane.change(hour: 0, offset: local_time_in_brisbane.timezone_offset.base_utc_offset)
```

### Actual behavior
When trying to get the beginning of the day of a time in a specific timezone, the offset is not taken into account and it creates a new DateTime with the local system timezone
```ruby
local_time_in_brisbane.beginning_of_day == local_time_in_brisbane.change(hour: 0)
```

This is the case for all calculations like `beginning_of_day`, `beginning_of_week`, `beginning_of_month`, etc

### System configuration
**Rails version**: 7.0.1
**Ruby version**: 2.7.2

**Comment by pjfitzgibbons** [comment]
I am having a really wierd experience while attempting to reproduce this issue.

My steps : 
1. Loaded a demo rails app using 7.0.1 / 2.7.4.
2. Ran script above -- issue observed as indicated.
3. While inspecting https://github.com/rails/rails/blob/9aae3ae183e59c85c5b275e96492c86ef1cfc156/activesupport/test/core_ext/date_ext_test.rb#L311 ...
4. set Time.zone = ActiveSupport::TimeZone["Brisbane"]
5. observed behaviour changed to desired -- brisbane.now.beginning_of_day returns Tue, 25 Jan 2022 00:00:00.000000000 AEST +10:00 
6. Rebooted computer.
7. rails console
```
2.7.4 :004 > Time.zone 
 => #<ActiveSupport::TimeZone:0x00007f9a1e12e598 @name="UTC", @tzinfo=#<TZInfo::DataTimezone: Etc/UTC>, @utc_offset=nil> 
2.7.4 :005 > local = r_brisbane.now
 => Tue, 25 Jan 2022 02:49:28.272452000 AEST +10:00 
2.7.4 :006 > local.beginning_of_day
 => Tue, 25 Jan 2022 00:00:00.000000000 AEST +10:00 
```
!!!

Now I have no idea what system-level / local-folder-level change has occurred that this?
I have also re-created a default rails app from `rails new ... --dev` -- same result -- issue no longer observed.

This definitely has something to do with TimeWithZone / ActiveSupportTimeZone .. though now repeatability is in question.

@emilkappert -- thoughts?

**Comment by pjfitzgibbons** [comment]
Are you able to demonstrate this issue with a single script that runs
minitest w/ rails?

Thanks and Kindest Regards,
Peter Fitzgibbons
(224) 307-9689

**Comment by emilkappert** [comment]
I think I understand where it goes wrong. But maybe that's due to having not fully read the implementation of the `utc_to_local` method on the `ActiveSupport::TimeZone` class.

All methods in `ActiveSupport::TimeZone` return an `ActiveSupport::TimeWithZone` except for `utc_to_local`.

I think it is very confusing that for example `.local(...)` returns an `ActiveSupport::TimeWithZone` and the `utc_to_local(...)`   returns a `Time` or a `TZInfo::TimeWithOffset` (depending on the `ActiveSupport.utc_to_local_returns_utc_offset_times` setting).

I would also expect an `ActiveSupport::TimeWithZone` object there.

I've written a small test for that. Maybe that helps you understand. 
So my actual problem seems to not be with the `beginning_of_day` method, but with the fact that I'm calling that method on different Time instances and getting different results because of that.


I'm using the `time_zone_test_helpers` that are also used by [`rails/activesupport/test/core_ext/date_ext_test.rb`](https://github.com/rails/rails/blob/9aae3ae183e59c85c5b275e96492c86ef1cfc156/activesupport/test/core_ext/date_ext_test.rb#L311)
```
require "active_support/time"
require_relative "../time_zone_test_helpers"

class TimeZoneTest < ActiveSupport::TestCase
  include TimeZoneTestHelpers

  test "Using the `local` method from Active Support and expecting a TimeWithZone and correct formatting" do
    zone = ActiveSupport::TimeZone["Australia/Brisbane"]

    with_env_tz "UTC" do
      with_tz_default zone do
        local_time = zone.local(2011, 6, 7, 12, 0, 0)

        assert_equal '2011-06-07 12:00:00 +1000', local_time.to_s
        assert_equal '2011-06-07 00:00:00 +1000', local_time.beginning_of_day.to_s
        assert local_time.beginning_of_day.is_a?(ActiveSupport::TimeWithZone)
      end
    end
  end

  test "Using the `utc_to_local` method from Active Support and expecting a TimeWithZone (utc_to_local_returns_utc_offset_times has not been set)" do
    zone = ActiveSupport::TimeZone["Australia/Brisbane"]

    with_env_tz "UTC" do
      with_tz_default zone do
        new_utc_time = DateTime.new(2011, 6, 7, 12, 0, 0).utc

        # This test will currently fail because it returns a Time instead of a TimeWithZone
        assert_equal ActiveSupport::TimeWithZone, zone.utc_to_local(new_utc_time).class
      end
    end
  end

  test "Using the `utc_to_local` method from Active Support and expecting a TimeWithZone (utc_to_local_returns_utc_offset_times has been set)" do
    zone = ActiveSupport::TimeZone["Australia/Brisbane"]

    ActiveSupport.utc_to_local_returns_utc_offset_times = true

    with_env_tz "UTC" do
      with_tz_default zone do
        new_utc_time = DateTime.new(2011, 6, 7, 12, 0, 0).utc

        # This test will currently fail because it returns a TZInfo::TimeWithOffset instead of a TimeWithZone
        assert_equal ActiveSupport::TimeWithZone, zone.utc_to_local(new_utc_time).class
      end
    end
  end

  # This test will currently fail because it returns a Time instead of a TimeWithZone
  test "Using active support and expecting a local time with time zone" do
    zone = ActiveSupport::TimeZone["Australia/Brisbane"]

    with_env_tz "UTC" do
      with_tz_default zone do
        new_utc_time = DateTime.new(2011, 6, 7, 12, 0, 0).utc

        # This test will currently fail because it returns a TZInfo::TimeWithOffset instead of a TimeWithZone
        assert_equal ActiveSupport::TimeWithZone, zone.utc_to_local(new_utc_time).class
      end
    end
  end

end
```
