### ISSUE TITLE
conflicts between css and js file

### ISSUE THREAD

**Issue by martindemello** [rails/rails#44239]
### Steps to reproduce

I have assets `app/assets/stylesheets/exolve-m.css` and `app/javascript/exolve-m.js`. If I try `import ./exolve-m` in my `application.js` it tries to load `exolve-m.css` and throws an error. I need to explicitly import `./exolve-m.js`

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 3.0.2p107

**Comment by ccasabona** [comment]
If you have a file `app/assets/stylesheets/needthis.css` and a file `app/javascript/needthis.js`, and in `app/javascript/application.js` you use this import command:

`import './needthis'`

this generates a console error:

`Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.`

The import does not take place.  If you change the import command to:

`import './needthis.js'`

the file imports correctly.

Rails 7.0.1
Ruby 3.1.0
