### ISSUE TITLE
It is strongly recommended to add  Admin module

### ISSUE THREAD

**Issue by qx** [rails/rails#44256]
It is strongly recommended to add the background admin module, which is the most basic application module. There is no application that does not require the background. These tasks should not be left to other gems to integrate, which will bring many problems and raise the learning threshold for newbies.

**Comment by orhantoy** [comment]
What do you mean by "background"?

**Comment by byroot** [comment]
I presume this is a feature request for an automatic admin interface like Django / Active Admin etc?

If so, then sorry we don't take feature requests on the bug tracker, and more generally this is beyond the scope of Rails

**Comment by qx** [comment]
> I presume this is a feature request for an automatic admin interface like Django / Active Admin etc?
> 
> 
> 
> If so, then sorry we don't take feature requests on the bug tracker, and more generally this is beyond the scope of Rails

Yes，This is very important for web applications, rather than waiting for the update and adaptation of devise.
