### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/assets/application.js....) 

### ISSUE THREAD

**Issue by simonsapiel** [rails/rails#44260]
I'm suddenly faced with 

```
ActionController::RoutingError (No route matches [GET] "/assets/application.js-920efc795bbe74efc45b09c59b03e18109155fbdf62b008ca8d094aed269d334.map")
```
in a fresh rails 7 application using tailwind and esbuild. I cannot seem to locate where this is originating from. What might be causing this? 

Removing

```
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
```
from the application.htlm.erb file removes the issue.

**Comment by nick-symon** [comment]
Hi, I just ran a fresh rails 7 app with tailwind and esbuild, not facing this issue right out of the box. I don't think this is an issue with rails. What does you app/assets folder look like?

**Comment by Pulkit203** [comment]
Yes I am also facing the same issue

**Comment by fhcadmin** [comment]
I'm also facing this error. It will only occur when you have the broswer's dev console open. (I'm using chrome)

```
% tree app/assets
app/assets
├── builds
│   ├── application.js
│   ├── application.js.map
├── config
│   └── manifest.js
├── images
└── stylesheets
```


```
cat app/assets/config/manifest.js
//= link_tree ../images
//= link_directory ../stylesheets .css
//= link_tree ../builds

```

**Comment by SkipKayhil** [comment]
@simonsapiel or @fhcadmin, do either of you have an example repository that you could share where you are having this issue? Without that it is very hard to see what is going wrong

**Comment by fhcadmin** [comment]
For anybody googling this, manually clearing out the build artifacts fixes this

`rm -rf app/assets/builds/*`

@SkipKayhil

**Comment by januszm** [comment]
> For anybody googling this, manually clearing out the build artifacts fixes this
> 
> `rm -rf app/assets/builds/*`
> 

This doesn't help. I am facing this issue in an application that was upgraded from Rails 6 with webpacker to Rails 7 with esbuild

**Comment by nachoal** [comment]
Same issue here when migrating from webpack to jsbuild, any clue?

**Comment by star-square** [comment]
Same issue here when migrating from Webpacker to jsbundling-rails.

**Comment by alexpertsev** [comment]
Regarding map file, faced same issue in development environment for Rails 6 (6.1.6.1) after upgrading from webpack to esbuild. Didn't notice same issue in Rails 7 (7.0.3). After checking the differences, noticed that fingerprinted version of application.js.map set as sourceMappingURL at the end of application.js file, is absent in Rails 7, but appears in Rails 6. 
Rails 6 has `config.assets.debug = true` which does not appear in Rails 7.
After setting `config.assets.debug = false`, fingerprinted map file reference in application.js disappears along with the error.

**Comment by Bryanprz** [comment]
For me, I solved it by doing the following:

1. Followed the advice of @fhcadmin above and removed everything from my assets build directory: `rm -rf app/assets/builds/*`

2. Removed this line from `config/environments/development.rb`: `config.assets.prefix = "/dev-assets"`

Restarted by server with `bin/dev` and reloaded the page, the error was gone. 

Hope that helps someone.

**Comment by ashok-stack** [comment]
Same issue here when migrating from webpacker to esbuild
`ActionController::RoutingError (No route matches [GET] "/assets/assets/application.css.map"):`
but weirdly for me it is adding wrong path when fetching the file. i'm not sure where it's taking the path though
here is assets builds directory
![image](https://user-images.githubusercontent.com/62198474/184951623-7738258f-b531-4a28-b19a-10139683d29f.png)

and my manifest.js looks like this
`//= link_tree ../images
//= link_tree ../builds`

**Comment by benkoshy** [comment]
### What worked for me?

`rake assets:clobber` 

And then regenerate the source map.

**Comment by ariandanim** [comment]
Hey @hahmed my case is different, not about missing route of application.js but application.js is not present in pipeline

**Comment by AsifNawaz2** [comment]
I am facing same issue in rails 7.0.4.

```ActionController::RoutingError (No route matches [GET] "/assets/admin-lte/dist/css/adminlte.css"):```

there are no errors in my app/assets/builds/application.css where adminlte css are availabe.

However when I run bin/dev, i see this issue. 
This is how my stylesheet looks like:

<img width="453" alt="Screenshot 2022-11-06 at 4 57 54 PM" src="https://user-images.githubusercontent.com/94438118/200169301-7c9f776a-dc77-40c7-99fc-c7dbf67330d7.png">

**Comment by suupic** [comment]
try this, worked for me
```
rake assets:clean
```

**Comment by etoundi2nd** [comment]
> Same issue here when migrating from webpacker to esbuild `ActionController::RoutingError (No route matches [GET] "/assets/assets/application.css.map"):` but weirdly for me it is adding wrong path when fetching the file. i'm not sure where it's taking the path though here is my assets builds directory
> 
> and my manifest.js looks like this `//= link_tree ../images
> 
> //= link_tree ../builds`
> 
> looks like the `/*# sourceMappingURL=assets/application.css.map */` sourceMappingURL is not proper so when browser parses the application.css file it looks at the comment and tries to load that file from and because of the invalid path it's not able to find the .map file
> 
> https://esbuild.github.io/api/#sourcemap


Remove any css file `import` within your javascripts files and instead them in your `application.scss` (or whatever you call it)

**Comment by gfsheppard** [comment]
I have this problem on a new install of Rails 7.1.3 with esbuild and bootstrap. None of the above advise helped, having tried `rails assets:clobber`, `rake assets:clean`, and `rake assets:clean`.
It only occurs with DevTools console open.
I gave up. I made the message go away with `touch public/assets/application.js-1c69856ea...10bf70.map`
