### ISSUE TITLE
references/belongs_to method create a column as integer when migration version is 6.0 even if we use PostgreSQL/MySQL

### ISSUE THREAD

**Issue by willnet** [rails/rails#44268]
### Steps to reproduce

sample app is here https://github.com/willnet/rails701-migration-bug-sample 

1. `rails new -d postgresql rails701-migration-bug-sample`
1. cd rails701-migration-bug-sample
1. rails g model parent
1. rails g model child parent:references
1. modify db/migrate/YYYYMMDD_create_children.rb from `ActiveRecord::Migration[7.0]` to `ActiveRecord::Migration[6.0]`
1. rails db:create
1. rails db:migrate
1. see schema.rb

### Expected behavior

references/belongs_to method create a column as bigint if we use PostgreSQL/MySQL

### Actual behavior

references/belongs_to method create a column as integer if we use PostgreSQL/MySQL

This behavior seemed to be introduced by https://github.com/rails/rails/pull/43295 

### System configuration

- Rails 7.0.1
- Ruby 3.1.0

**Comment by fatkodima** [comment]
@willnet Can you verify https://github.com/rails/rails/pull/42350 fixes your problem? Works for me.

**Comment by willnet** [comment]
@fatkodima I've confirmed that https://github.com/rails/rails/pull/42350/commits/26afb6dbda8f4923a9a75afbdda185a8b23acc16 works as expected!

**Comment by julianrubisch** [comment]
I don’t know if this helps, but I’ve seen this behavior intermittently, e.g. when adding columns with the [money gem](https://github.com/RubyMoney/money-rails)

**Comment by george-ayris** [comment]
Hello, any updates on this? I believe I'm hitting this issue with PostgreSQL.

**Comment by ZilvinasKucinskas** [comment]
Tested https://github.com/rails/rails/pull/42350 and it seems to fix the backward compatibility issue.

A temporary solution until the PR is merged might be adding explicit `type: :bigint` option to old migrations (`references` and `belongs_to`). 

Otherwise, this issue blocks migration from `7.0.0` upwards.

**Comment by QWYNG** [comment]
This problem also reproduced in Rails 6.1.5, Ruby 3.0.2 and MySQL.

**Comment by tvdeyen** [comment]
This is an issue on Rails 6.1.5 as well

**Comment by arturopie** [comment]
@rafaelfranca can we reopen this issue as it's still an issue in 6.1? It was introduced by this PR (https://github.com/rails/rails/pull/43295) in 6.1.5, and with the new security vulnerability that was fixed in 6.1.5.1, I predict a lot of people will be running into this issue.

**Comment by SkipKayhil** [comment]
> can we reopen this issue as it's still an issue in 6.1? It was introduced by this PR (#43295) in 6.1.5, and with the new security vulnerability that was fixed in 6.1.5.1, I predict a lot of people will be running into this issue.

This has been fixed on `6-1-stable` (in #42350), there just hasn't been another bugfix release of Rails. 6.1.5.1 only had the security fix and no other changes since 6.1.5. You can point your Gemfile at the `6-1-stable` branch if you need the fix immediately.

**Comment by jbosse** [comment]
Any idea when 6.1.5.2 will be released with this fix? I cannot upgrade a repo with mysql to 6.1.5.1 and pointing to a branch in flux for production seems ill-advised.

**Comment by SkipKayhil** [comment]
> Also not, in Rails 6.1.6 this issue still persists.

Hmm, I just upgraded an app from 6.1.5.1 (where I saw the issue) to 6.1.6 and the schema correctly uses bigint now. Do you have an example repo you could share where you are still experiencing this?

**Comment by dmke** [comment]
> Do you have an example repo you could share where you are still experiencing this?

I was about to create one and found it doesn't happen anymore. :thinking: 

Yesterday I could have sworn that our production app did still observe this behaviour... I guess I've been hallucinating at the end of a particularly long day (either that, or we have another gem monkey-patching the innards of ActiveRecord, which I'm currently not remembering).

At least I can now confirm that polymorphic relations created with 6.1.5, 6.1.5.1, and 6.1.6 adopt the correct column type (`bigint`), without the need to annotate `type: :bigint` to the migration files.

<details><summary>Repro steps</summary>

For the curious, I've probed the following:

1. create a new app with Rails 6.1.5
2. add `config.activerecord.schema_format = :sql` to `config/application.rb`
3. `rails g model Book title 'author:references{polymorphic}'`
4. `rake db:{create,migrate}`
5. git-commit app, including `db/structure.sql`
6. update to Rails 6.1.5.1, run `rake db:migrate:redo`
7. observe no diff on `db/structure.sql`
8. update to Rails 6.1.5.1, run `rake db:migrate:redo`
9. observe no diff on `db/structure.sql`, still

The `db/structure.sql` created in (4) already had `author_id bigint not null`, rebuilding the schema in (6) and (8) did not change that definition.

</details>

Sorry for the noise.
