### ISSUE TITLE
Missing zeitwerk synchronization in rails 7.0.2.2 and ruby 3.1.0

### ISSUE THREAD

**Issue by mildred** [rails/rails#44264]
Originally reported at https://github.com/fxn/zeitwerk/issues/207

It seems that rails is not synchronizing zeitwerk when it autoload classes, causing a `RuntimeError`: `can't add a new key into hash during iteration`. The constant loading is aborted and only restarting the rails server causes it to retry loading the constant.

**Comment by fxn** [comment]
The problem seems to be that reloading and autoloading are happening at the same time. That should not happen and there's a RW lock in place that has been there for a long time synchronizing this.

@mildred you've experienced this always doing web requests in `development` mode with multi-threaded Puma?

**Comment by mildred** [comment]
That's true, running rails in development environment with multi threaded puma. I'm not running this on the CI yet, and it has not reached production. zeitwerk should not affect production in any case I believe.

In the https://github.com/fxn/zeitwerk/issues/207 issue I put the stack traces I get on the rails error page. I don't know how I can catch the concurrent stack trace if it exists. Perhaps I can instrument the code a little bit to extract more information. Where is the lock supposed to be taken?

**Comment by mildred** [comment]
Also, I also experience a deadlock causing requests to lock until the thread pool is exhausted (#44263). Could it be somehow the locking infrastructure that is failing?

**Comment by mildred** [comment]
Still having the issue with rails 7.0.2.2

**Comment by fxn** [comment]
This is the first time we find this. Applications reload in a multi-threaded environment routinely, so we don't know the cause without a way to reproduce.

@matthewd and I suspect that there has to be something in your app or some dependency that might be provoking this. Maybe related to that other ticket linked.

Maybe we could help debugging, @matthewd is more familiar with the code in Rails protecting this to guess what could be interfering. If he was not able to chime in, I could try to help.

**Comment by fxn** [comment]
@mildred This is really weird.

Does this happen if you launch the dev server using one single thread?

**Comment by fxn** [comment]
Ideally we should be able to reproduce. If you can't, do you see a pattern in the constants that are not found?

**Comment by fxn** [comment]
@bvogel are you getting

```
RuntimeError: can't add a new key into hash during iteration
```

with one thread?

**Comment by mildred** [comment]
Setting the number of puma threads to only one, I can't reproduce the issue.

**Comment by bvogel** [comment]
@fxn Yes, and refreshing the page again will work, however no real reload happens and the code get's stale

**Comment by bvogel** [comment]
Will try to get a minimal setup to reproduce our error

**Comment by fxn** [comment]
@bvogel awesome, let's see if we hunt this one down.

Even if you get one sporadic error, sharing the stack trace would be already something.

**Comment by fxn** [comment]
@bvogel Good one. I wonder if `descendants` is conflicting with itself depending on how you hit the hierarchy. I'll try to follow this hint.

Meanwhile, I believe it should be safe to do the same upfront in an initializer. Something like (off the top of my head):

```ruby
# config/initializers/preload_sti.rb

unless Rails.configuration.eager_load
  Rails.configuration.to_prepare do
    # Fetch all distinct class names from the STI table and constantize them.
  end
end
```

Could you please add that and remove `StiPreload` from the application?

**Comment by bvogel** [comment]
@fxn it was even easier as that, We seem to run into a race condition as each constantize actually triggered another preload. by moving the line `self.preloaded = true` up to be the first in the `preload_sti` method we seem to have fixed this as subsequently the preload method isn't triggered again. the file now looks like this:
```
module StiPreload
  unless Rails.application.config.eager_load
    extend ActiveSupport::Concern

    included do
      cattr_accessor :preloaded, instance_accessor: false
    end

    class_methods do
      def descendants
        preload_sti unless preloaded
        super
      end

      # Constantizes all types present in the database. There might be more on  disk, but that does not matter in
      # practice as far as the STI API is concerned.
      #
      # Assumes store_full_sti_class is true, the default.
      def preload_sti
        self.preloaded = true

        types_in_db = base_class.unscoped.select(inheritance_column).distinct.pluck(inheritance_column).compact

        types_in_db.each do |type|
          logger.debug("Preloading STI type #{type}")
          type.constantize
        end
      end
    end
  end
end
```

**Comment by fxn** [comment]
@bvogel problem is, it is not thread-safe. A second thread finds the flag set while the first one is still preloading, so it calls `super` with an intermediate state.

**Comment by bvogel** [comment]
understood, but as a concern I can include the preloader in STI base classes as an initializer I ended up with this:
```
unless Rails.configuration.eager_load
  Rails.configuration.to_prepare do
    [Content, Product, PrivacySetting].each do |base_class|
      types_in_db = base_class.unscoped.select(base_class.inheritance_column).distinct.pluck(base_class.inheritance_column).compact

      types_in_db.each do |type|
        Rails.logger.debug("Preloading STI type #{type}")
        type.constantize
      end
    end
  end
end
```
So I have to actively list the STI base classes here. Any idea how that could be avoided?

**Comment by fxn** [comment]
@bvogel STI has always tension, because we need to eager load in a lazy loading context. So you need to find the sweet spot in which you feel the trade-off is good enough for you taste.

The only way I can imagine if you control your application and STI columns have the common names, would be to scan the schema and detect the tables that have said columns.

You'd then trade a bit of boot time for not having to maintain the list of root models.

Open to more clever solutions :).

**Comment by fxn** [comment]
Hey, perhaps `StiPreload` has some issue that can be solved, eh? I need to dig into it, that initializer is something that may at least avoid the exceptions meanwhile.

**Comment by bvogel** [comment]
@fxn thanks for your patience. Yeah this preloading is hard. BUT we should at least reflect this back towards the rails documentation team as this initializer is probably safer than the solution they suggested?

**Comment by mildred** [comment]
How to best debug this king of issue, this issue is very annoying, requiring to restart the rail server every 5 minutes because suddenly it cannot find a constant...

**Comment by fxn** [comment]
@mildred unfortunately, I have no other report like this.

Since you cannot reproduce in single-thread mode, the hypothesis is that it is an issue related to multi-threading. Since this is the only ticket reporting this, I suspect something is going on in your particular application, somehow.

Autoloading synchronization is done by Ruby. Reloading synchronization is done by Rails.

Without a minimal way to reproduce, it is going to be hard. One thing we could try is to leave logging always enabled (`Rails.autoloaders.logger = Rails.logger` in `config/application.rb`), and share the logs when the problem occurs.

**Comment by mildred** [comment]
I set `config.eager_load = true` and I no longer have an issue.
