### ISSUE TITLE
`rails new project_name --help` with or without other command line args creates a new project instead of displaying help

### ISSUE THREAD

**Issue by bbugh** [rails/rails#44280]
### Steps to reproduce

This is the exact process I followed installing ruby 3.1.0 and rails 7 just now. 
```ruby
asdf install ruby 3.1.0
asdf local ruby 3.1.0
gem install rails -v7.0.1
rails new project_name --help
```

This also happens with other command line switches like:

`rails new project_name -j=esbuild --help`

It only outputs help correctly when *only* specifying the `--help` switch.

### Expected behavior
Rails CLI would output the help content, not create a new project. While constructing the CLI arguments for a new project, it's useful to be able to incrementally add them and check `--help`.

### Actual behavior
Any combination of `rails new project --help`, including any other command line switches, will generate a project instead of printing help.

### System configuration
**Rails version**: 7.0.1

**Ruby version**: 3.0.1

**Comment by nick-symon** [comment]
Hi there -- I looked in the guide and the `rails new --help` man page, I haven't seen any indication that running `rails new [app_name] --help` should actually generate any help text. running `rails new --help` provides details on the various flags that are available when running `rails `new`. So this issue sounds more like a feature request and I'd flag it as such

**Comment by bbugh** [comment]
I don't think it's a rails documentation thing. The standard behavior of probably nearly every CLI program is that if `--help` is specific, it ignores everything else and prints help. 

For example, all of these print the help for the program or subcommand:

```
git clone https://github.com/rails/rails --depth=0 --help
```
```
psql myapp_development -w -x --help
```

```
wget -p -k https://avatars.githubusercontent.com/u/42363224?s=88&u=99d32d75a086eea19eaf1cf4d6c85b40801121bf&v=4 --help
```

```
curl https://raw.githubusercontent.com/github/gitignore/master/Node.gitignore -s -o .gitignore -v --help
```

Principle of least surprise is definitely not to create a new app when specifying `--help`.

**Comment by nick-symon** [comment]
Thanks -- that's helpful context. Didn't mean to suggest there was an issue with the documentation, rather that the documentation doesn't create an expectation that the behavior should happen. So still think this is a feature request but interested to see if this behavior worked in earlier versions of rails

**Comment by rafaelfranca** [comment]
Yes, this is definitely a feature request. Feel free to open a PR implementing it.

**Comment by bbugh** [comment]
After looking at this some more, I actually think it's an issue with Thor. I'll carry on over there. Thanks!
