### ISSUE TITLE
Don't forget to include the Crash Report log file under DiagnosticReports directory in bug reports.

### ISSUE THREAD

**Issue by shravanteegala** [rails/rails#44293]
<img width="649" alt="Screenshot 2022-01-31 at 2 55 26 PM" src="https://user-images.githubusercontent.com/13646977/151768807-98d4e089-302b-4217-99f5-9b8a3e19a145.png">
hi,
iam always getting this issue. when I installed in my Mac M1 Chip.
[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: https://www.ruby-lang.org/bugreport.html

pod version: 1.11.2

**Comment by yahonda** [comment]
Based on `pod install` in the screenshot and the `pod version: 1.11.2` in the description, this is related to CocoaPods, not Ruby on Rails.

How about asking for help as explained at https://guides.cocoapods.org/using/troubleshooting.html ?

**Comment by shravanteegala** [comment]
Thank you for your help.
it's resolved.

**Comment by shengshu** [comment]
> Thank you for your help. it's resolved.
> 
> iam using :
> 
> below commands: sudo gem update --system sudo gem install -n /usr/local/bin cocoapods

Thank you for your help.
Solved a big problem.
