### ISSUE TITLE
Improper redirection leads to link-based hijack

### ISSUE THREAD

**Issue by clonesgit** [rails/rails#44310]
I found  one of the links used in https://github.com/rails/rails/ leads an improper redirection link, an attacker can able to intermediate and hijack the link 

#### Steps to Reproduce 

1, Go to https://github.com/rails/rails/blob/a433cdcdd842cc9aa423c205dbfb99c8d0f1ed79/guides/source/upgrading_ruby_on_rails.md

2. Search for Active Storage now requires Image Processing
3. Click on the image_processing gem link  you will see takeover message

#### Fix :

Change the internal link for (image_processing gem)
From https://github.com/janko-m/image_processing to https://github.com/janko/image_processing

**Comment by ghiculescu** [comment]
Thanks, this was fixed in https://github.com/rails/rails/commit/a17629e393141fadaae75fd1398fa4b80b7a5c5c#diff-f5ff9aa07f44111a79d56c09ec37d774b462d97aff68f32490c2e56e74c95783
