### ISSUE TITLE
Better Documentation for rails new

### ISSUE THREAD

**Issue by ChaelCodes** [rails/rails#44325]
### Description
`rails new` is the definitive start for any project, and it's important to get it right, but documentation on the available options are spread throughout the Rails Guides.

The [Command Line](https://guides.rubyonrails.org/command_line.html#rails-new) guide says you can skip modules. The [API-only](https://guides.rubyonrails.org/api_app.html#creating-a-new-application) guide offers the option of adding `--api`. I could only find information about `--database=` from [Digital Ocean's guide on working with postgres](https://www.digitalocean.com/community/tutorials/how-to-set-up-ruby-on-rails-with-postgres). `--webpacker` being an option is 
just a side-note in this guide on [webpacker in rails](https://guides.rubyonrails.org/webpacker.html#installing-webpacker).

The CLI documentation helps, but there's not much room for elaboration, and no space to link to additional documentation.
```
rails new --help
Usage:
  rails new APP_PATH [options]

Options:
      [--skip-namespace], [--no-skip-namespace]              # Skip namespace (affects only isolated engines)
      [--skip-collision-check], [--no-skip-collision-check]  # Skip collision check
  -r, [--ruby=PATH]                                          # Path to the Ruby binary of your choice
                                                             # Default: /Users/rachael.wrightmunn/.rbenv/versions/3.1.0/bin/ruby
  -m, [--template=TEMPLATE]                                  # Path to some application template (can be a filesystem path or URL)
  -d, [--database=DATABASE]                                  # Preconfigure for selected database (options: mysql/postgresql/sqlite3/oracle/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
                                                             # Default: sqlite3
  -G, [--skip-git], [--no-skip-git]                          # Skip .gitignore file
      [--skip-keeps], [--no-skip-keeps]                      # Skip source control .keep files
  -M, [--skip-action-mailer], [--no-skip-action-mailer]      # Skip Action Mailer files
      [--skip-action-mailbox], [--no-skip-action-mailbox]    # Skip Action Mailbox gem
      [--skip-action-text], [--no-skip-action-text]          # Skip Action Text gem
  -O, [--skip-active-record], [--no-skip-active-record]      # Skip Active Record files
      [--skip-active-job], [--no-skip-active-job]            # Skip Active Job
      [--skip-active-storage], [--no-skip-active-storage]    # Skip Active Storage files
  -C, [--skip-action-cable], [--no-skip-action-cable]        # Skip Action Cable files
  -A, [--skip-asset-pipeline], [--no-skip-asset-pipeline]    # Indicates when to generate skip asset pipeline
  -a, [--asset-pipeline=ASSET_PIPELINE]                      # Choose your asset pipeline [options: sprockets (default), propshaft]
                                                             # Default: sprockets
  -J, [--skip-javascript], [--no-skip-javascript]            # Skip JavaScript files
      [--skip-hotwire], [--no-skip-hotwire]                  # Skip Hotwire integration
      [--skip-jbuilder], [--no-skip-jbuilder]                # Skip jbuilder gem
  -T, [--skip-test], [--no-skip-test]                        # Skip test files
      [--skip-system-test], [--no-skip-system-test]          # Skip system test files
      [--skip-bootsnap], [--no-skip-bootsnap]                # Skip bootsnap gem
      [--dev], [--no-dev]                                    # Set up the application with Gemfile pointing to your Rails checkout
      [--edge], [--no-edge]                                  # Set up the application with Gemfile pointing to Rails repository
  --master, [--main], [--no-main]                            # Set up the application with Gemfile pointing to Rails repository main branch
      [--rc=RC]                                              # Path to file containing extra configuration options for rails command
      [--no-rc], [--no-no-rc]                                # Skip loading of extra configuration options from .railsrc file
      [--api], [--no-api]                                    # Preconfigure smaller stack for API only apps
      [--minimal], [--no-minimal]                            # Preconfigure a minimal rails app
  -j, [--javascript=JAVASCRIPT]                              # Choose JavaScript approach [options: importmap (default), webpack, esbuild, rollup]
                                                             # Default: importmap
  -c, [--css=CSS]                                            # Choose CSS processor [options: tailwind, bootstrap, bulma, postcss, sass... check https://github.com/rails/cssbundling-rails]
  -B, [--skip-bundle], [--no-skip-bundle]                    # Don't run bundle install

Runtime options:
  -f, [--force]                    # Overwrite files that already exist
  -p, [--pretend], [--no-pretend]  # Run but do not make any changes
  -q, [--quiet], [--no-quiet]      # Suppress status output
  -s, [--skip], [--no-skip]        # Skip files that already exist

Rails options:
  -h, [--help], [--no-help]        # Show this help message and quit
  -v, [--version], [--no-version]  # Show Rails version number and quit

Description:
    The 'rails new' command creates a new Rails application with a default
    directory structure and configuration at the path you specify.

    You can specify extra command-line arguments to be used every time
    'rails new' runs in the .railsrc configuration file in your home directory,
    or in $XDG_CONFIG_HOME/rails/railsrc if XDG_CONFIG_HOME is set.

    Note that the arguments specified in the .railsrc file don't affect the
    defaults values shown above in this help message.

Example:
    rails new ~/Code/Ruby/weblog

    This generates a skeletal Rails installation in ~/Code/Ruby/weblog.
```
It'd be really helpful to have a home for all of these options, and then be able to link to specific pages to support them. Like the aforementioned API-only guide. Also, some people, like myself, like to link to the resources that we used to make decisions, and that's much harder if the information only exists in the CLI.

**Comment by p8** [comment]
Thanks for reporting the issue @ChaelCodes !
I think multiple PR's could be made to improve the documentation.
- Adding the missing `skip-x` options to the Command Line guide
- Adding the usage of `--template` to the Command Line guide.
- Adding the usage of `--api` and `--minimal` to the Command Line guide.
- etc...

**Comment by ChaelCodes** [comment]
@p8 wonder if that'll add too much length to the existing Rails Guide. Would it be more helpful to break it out into a separate guide and link to it, or is there room in the existing command line guide?

**Comment by p8** [comment]
I don't think the Command Line guide is that long (700 lines).
Comparing it to some others:
Getting started guide: 2100 lines
Configuration guide: 2900 lines
Active Record Querying guide: 2400 lines

We currently don't have search in the guide, so splitting it up might make it hard to find?
On the other hand I just noticed there already is an "advanced" part in the Command line guide,
describing the `--database` and `--scm` options
https://guides.rubyonrails.org/command_line.html#the-rails-advanced-command-line
And that is easily overlooked :)

We don't describe everyting in the guides and sometimes refer to the API docs for more
exhaustive documentation. However I don't think it's possible to describe the options in
rdoc, as we don't have methods that easily match to the commands.
For example `rails new` uses:
https://github.com/rails/rails/blob/3da45ea10e7a9892b5c4aa4c88957d37833a5183/railties/lib/rails/commands/application/application_command.rb#L25-L29
On the other hand we might add documentation for the `ApplicationCommand` class and link to
it from the guide? Similar to: https://github.com/rails/rails/blob/3da45ea10e7a9892b5c4aa4c88957d37833a5183/activerecord/lib/active_record/base.rb#L16-L22

**Comment by ChaelCodes** [comment]
@p8 Thank you!! I really appreciate the clarification and context on this one. I agree that documenting it more exhaustively on ApplicationCommand would really help.

**Comment by papey** [comment]
Hi everyone, still need help on this ?

**Comment by salochara** [comment]
👋  hey everyone! 
Is help still needed on this? 
I'd be happy to take this and make my first contribution to Rails 😄

**Comment by p8** [comment]
Hey @papey and @salochara 👋 
We could still use some help with this. 🙂 

I think the `rails new` command could have it's own section before "Command Line Basics".
Maybe something like "Creating a Rails App".
You could copy the existing `rails new` section and maybe

If that is merged, separate PR's could add sections for:
- some common options like `--api` and `--minimal`
- skipping options
- ...

**Comment by salochara** [comment]
Hey! Thanks for your reply! 

@papey if you want, go ahead on this first PR. You saw this first 🙂

If there are others PR that will come out of this, I'd be super happy to take one!

**Comment by papey** [comment]
👋 @p8 and @salochara.

Thanks for the feedback and i'll go ASAP with the suggestion made by @p8 !

💎

**Comment by papey** [comment]
:wave: again !

Here is a [starting work](https://github.com/papey/rails/tree/44325-better-rails-new-doc) regarding @p8's last comment.

This is a really tiny change (new header, moved a block of text and some rewording) so I wasn't sure if it was worth notifying all the people watching the repo yet.

Anyway, thanks for your feedback

**Comment by p8** [comment]
Hey @papey,
That looks great.
You can create a PR for that, as we merge lot's of smaller document changes all the time.
