### ISSUE TITLE
Rails7 shard_resolver does not work with ActiveStorage::BaseController

### ISSUE THREAD

**Issue by Notalifeform** [rails/rails#44321]
### Steps to reproduce
when implementing rails7 [horizontal-sharding](https://guides.rubyonrails.org/active_record_multiple_databases.html#horizontal-sharding) I ran into the issue that the shard-selector does not work when using  `ActiveStorage::BaseController` as base controller

The result is that the `shard_selector` is never executed (so the default shard is selected)

The base controller that causes this behaviour

```
class ApplicationController < ActiveStorage::BaseController
end
```

a work around (where the ActiveStorage behaviour still works)

```
class ApplicationController < ActiveStorage::BaseController
  # This is totally weird.
  # inheriting from ActiveStorage::BaseController breaks multidb support
  # but including the content of it fixes it. ?!?

  include ActiveStorage::SetCurrent

  protect_from_forgery with: :exception

  self.etag_with_template_digest = false
end

``` 

trivial app to reproduce can be found here:

https://github.com/Notalifeform/rails-multidb-44321

might be related to this comment:
https://github.com/rails/rails/issues/43403#issuecomment-940455264
### Expected behavior

shard_selector is executed and the proper shard is selected

### Actual behavior

shard_selector is  executed but the proper shard is never selected

### System configuration
**Rails version**:
7.0.1
**Ruby version**:
3.0.3

**Comment by gmcgibbon** [comment]
Please provide a [bug report script](https://github.com/rails/rails/tree/d9edce650f215e821cc90108a8707c0ec24a9440/guides/bug_report_templates) or trivial app that demonstrates the issue.

**Comment by Notalifeform** [comment]
Added a trivial app to the issue and updated the description of the issue

**Comment by gmcgibbon** [comment]
Thanks! The issue was fixed by https://github.com/rails/rails/pull/44244, and I think we just need to backport it.

`ActionController::Live` is being included in all Active Storage controllers and spinning up separate threads so the middleware shard setting isn't being remembered.

**Comment by gmcgibbon** [comment]
Sorry for the delay, backported in https://github.com/rails/rails/commit/5d08b95874594188d1f4e44581b5bea8e5a228ad
