### ISSUE TITLE
`ActiveSupport::Notification`: bugs with overlapping events and subscriptions

### ISSUE THREAD

**Issue by jaynetics** [rails/rails#44348]
this is a bunch of bugs i found while investigating https://github.com/rails/rails/issues/44167.

## bug 1: subscribing during an event causes errors

there is no handling for subscriptions/instrumentations that happen between the start and the end of an event. i've described the control flow in some detail [here]( https://github.com/rails/rails/issues/44167#issuecomment-1029015048 ).

- if the listeners internal stack is not initialized, i.e. an `instrumenter#finish` call happens after subscribing, but before the first `instrumenter#start` call, the stack is `nil` and there is a `NoMethodError`
- else, if at least one event starts before any event finishes, the stack will be initialized but depleted
  - for `EventObject` subscribers, this will cause a `NoMethodError`
  - for `Timed` subscribers, this will cause `Event#start` to be `nil`, which causes https://github.com/rails/rails/issues/44167

### example

```ruby
ActiveSupport::Notifications.instrumenter.start('bar', {})
ActiveSupport::Notifications.subscribe('bar') { |*args| }
ActiveSupport::Notifications.instrumenter.finish('bar', {})
# => undefined method `pop' for nil:NilClass (NoMethodError)

ActiveSupport::Notifications.instrumenter.start('bar', {})  # initialize stack
ActiveSupport::Notifications.instrumenter.finish('bar', {}) # OK
ActiveSupport::Notifications.instrumenter.finish('bar', {}) # start == nil
```

## bug 2: event data (times, payloads) leaks between multiple subscribers

because multiple subscribers (`Evented` instances) of the same type share a stack for all events that they match, they mishandle events with an overlapping duration.

this particular bug was also described in the abandoned PR https://github.com/rails/rails/pull/43241, but AFAICT that PR would have fixed only this one bug and only for a specific use case.

### example

```ruby
foo_events = []
bar_events = []
ActiveSupport::Notifications.subscribe('foo') { |e| foo_events << e }
ActiveSupport::Notifications.subscribe('bar') { |e| bar_events << e }

# puts foo data on shared stack
ActiveSupport::Notifications.instrumenter.start('foo', { name: 'FOO' })

# fetches foo data from shared stack
ActiveSupport::Notifications.instrumenter.finish('bar', { name: 'BAR' })

# resulting event is a mix of both events
foo_events.count      # => 0
bar_events.count      # => 1
bar_events[0].name    # => 'foo'            # name from foo event
bar_events[0].payload # => {:name => "BAR"} # payload from bar event
bar_events[0].time    # => 1650862655       # start time from foo event
bar_events[0].end     # => 1650862656       # end time from bar event
```

## bug 3: event data leaks between events of a single subscriber

this is because individual subscribers use a shared stack for all types of events that they match.

### example

```ruby
events = []
ActiveSupport::Notifications.subscribe(/.*/) { |e| events << e }

ActiveSupport::Notifications.instrumenter.start('foo', { name: 'FOO' })
ActiveSupport::Notifications.instrumenter.finish('bar', { name: 'BAR' })

# resulting event is a mix of both events
events.count      # => 1
events[0].name    # => 'foo'            # name from foo event
events[0].payload # => {:name => "BAR"} # payload from bar event
events[0].time    # => 1650862655       # start time from foo event
events[0].end     # => 1650862656       # end time from bar event
```

**Comment by jhawthorn** [comment]
Thanks for the issue. Is this possible to reproduce without calling start/finish manually? I think the expectation of the previous fanout implementation (I'd like to improve) is that within the execution context we do not interleave start/finish

**Comment by jaynetics** [comment]
@jhawthorn 

> I think the expectation of the previous fanout implementation (I'd like to improve) is that within the IsolatedExecutionState we do not interleave start/finish

i don't think it's possible to prevent this in a multi-threaded environment, and even in just a single thread you'd have to be careful not to do this, which might not even be under your control as some gems also fire `Notifications` that could be picked up by any sufficiently wide subscriber, mixing up the data.

even deprecating `#finish` and at some point making it a no-op, thus enforcing the use of `#finish_with_state` everywhere, would not fix all of the issues mentioned above.

consider these requests, assuming we use `#finish_with_state` for `request.action_dispatch` as suggested in #44454:

```
request A:   (start) ---------------------> (finish)
request B:       (start) ---------------------> (finish)
request C:           (start) ---------------------> (finish)
````

`ServerTiming` would receive one `request.action_dispatch` event for request A, two for request B, three for request C. the start time that request C pushes to the stack would be wrongly picked up by the event describing request A. and so on.

i see two options:

1. enforce `#finish_with_state` *and* prevent subscribing per request. i'm not even sure why ServerTiming does this instead of subscribing just once in initialize? is that to isolate it from events higher up in the call chain? either way, i doubt subscribing per request can be prevented. maybe it could be made very clear in the docs that it's a no-no.
2. deprecate `#start`, `#finish`, `#finish_with_state`. add a replacement method, maybe `#start_event`, that returns either a unique event identifier or the event data itself, that *must* then be passed to a new method `#finish_event`. this seems like the most robust solution to me. of course, this would make it hard to start and finish events in distinct parts of codebases - and quite hard to do so across multiple requests if that is meant to be a supported use case.
