### ISSUE TITLE
Tell me the appropriate or efficient change method for ActiveRecord::Enum.

### ISSUE THREAD

**Issue by ryosk7** [rails/rails#44344]
### Steps to reproduce

After upgrade rails version 5.1 to 5.2, then raise an error like this.

```ruby
You tried to define an enum named "status" on the model "User", but this will generate a class method "reject", which is already defined by ActiveRecord::Relation.
```

I tried `_prefix ` option. And it looks good work.
However, there are many changes in our service.
Please tell me the appropriate or efficient change method.

I want a solution that lets me list and detect unused keys.

### Expected behavior

NOTE: Since it is written according to the issue guide, the content is duplicated.

```ruby
  enum status: {
    normal: 0,
    deleted: 1,
    reject: 2
  }, _prefix: :is
```

```ruby
User.last.is_reject!
#=> is_reject
```

### Actual behavior

sample code.

```ruby
User.last.reject!
```

then,

```ruby
You tried to define an enum named "status" on the model "User", but this will generate a class method "reject", which is already defined by ActiveRecord::Relation.
```

but I know, it fix like this.

```ruby
  enum status: {
    normal: 0,
    deleted: 1,
    reject: 2
  }, _prefix: :is
```

```ruby
User.last.is_reject!
#=> is_reject
```

### System configuration
**Rails version**:
5.2.6
**Ruby version**:
2.7.5

**Comment by ryosk7** [comment]
Related to this issue.
https://github.com/rails/rails/issues/14160

**Comment by byroot** [comment]
@ryosk7 your question isn't clear, I'm having trouble understanding what you mean by "efficient change method".

If you mean what name to chose for your method, then well it's up do you, but if you renamed your state from `reject` to `rejected`, that would likely solve it.

Either way, we don't really do support question on the bug tracker, so I'm happy to help but I'll close.
