### ISSUE TITLE
Add an index to the guides

### ISSUE THREAD

**Issue by martindemello** [rails/rails#44351]
I wanted to know how to deal with file uploads in the controller, and a bit of googling finally turned up the `form.file_field` tag, which made me realise the docs would be under form helpers. Perhaps obvious in retrospect, but as someone learning rails I didn't think of it at the time. It would be super useful to have a flat alphabetical index of everything in the guides, so that e.g. the link to `form.file_field` would be there under "File uploads" and "Uploads".

**Comment by martindemello** [comment]
yeah, a search box within the guides site would be nice too - i didn't think of adding "rails guides" to my search term in google. (I do still like the idea of an index but as you say it's work to maintain)

**Comment by ghiculescu** [comment]
I'm going to close this as a feature request (for the docs). A better place to discuss it would be https://discuss.rubyonrails.org/, we reserve the issue tracker for bugs.
