### ISSUE TITLE
Rails 7.0.1 Direct Uploads remain painful to use

### ISSUE THREAD

**Issue by resistorsoftware** [rails/rails#44374]
Using Ruby 3.1 and Rails 7.01 to do a Direct Upload, we know we have to Monkeypatch out any of the Direct Upload token code. Failure to do so results in the dreaded:

    ActiveStorage::InvalidDirectUploadTokenError (ActiveStorage::InvalidDirectUploadTokenError):
    
Interestingly, while we get uploads working by removing this token, if we have an exception in our code, and then re-use the same upload to try again after fixing the exception, this error is indeed part of the cycle again. So as an example, when saving the attachment from a direct upload, we then try and run a background job to process it, and we blew that. If we fix the background job call, and just re-up a file, boom:

     ActiveStorage::InvalidDirectUploadTokenError (ActiveStorage::InvalidDirectUploadTokenError):
     
I would love for this to be fixed!! I

**Comment by rafaelfranca** [comment]
Did you try Rails 7.0.2?

**Comment by resistorsoftware** [comment]
Yes. AFAIK that did not make any major changes to direct uploads. This is a strange one though. I get it. If I have an exception, everything about the form is probably borked, and for sure, trying to re-use it is not likely to work as Rails has now reset itself after the exception. Maybe this is all just smoke.

**Comment by ghiculescu** [comment]
7.0.2 includes https://github.com/rails/rails/pull/44287 which was meant to resolve a lot of the `InvalidDirectUploadTokenError` issues.

**Comment by jesselawson** [comment]
I just upgraded to 7.0.2 and it has been the only thing that fixed the dreaded `InvalidDirectUploadTokenError` issue for me. Thank you all so much!
