### ISSUE TITLE
ActiveModel::Attributes raise error on example from edge guides

### ISSUE THREAD

**Issue by uxxman** [rails/rails#44383]
### Steps to reproduce

The updated **ActiveModel::Attributes** guides suggest the example which doesn't run. The initialise method doesn't accept any arguments.

Guide: https://edgeapi.rubyonrails.org/classes/ActiveModel/Attributes/ClassMethods.html#method-i-attribute 

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_model"
require "minitest/autorun"

class Person
  include ActiveModel::Attributes

  attribute :name, :string
  attribute :active, :boolean, default: true
end

class BugTest < Minitest::Test
  def test_stuff
    person = Person.new(name: "Volmer")
  end
end
```

### Expected behavior
Test should not raise any exception.

### Actual behavior
Raises: ArgumentError: wrong number of arguments (given 1, expected 0)

### System configuration
**Rails version**: main

**Ruby version**: 3.1.0

**Comment by jonathanhefner** [comment]
@uxxman I missed that -- good catch!  The example needs an `include ActiveModel::API`.  Would you like to submit a PR?

**Comment by uxxman** [comment]
@jonathanhefner thank you for the prompt response. Sure, would love to submit a PR and contribute.

Do you think including **ActiveModel::API** in all examples is ok? Because ActiveModel::API adds a bunch of other stuff as well and from the example docs user will think he will always have to include both in order to use attributes, where as he can use all the features of ActiveModel::Attributes even without ActiveModel::API minus the **.new(attrs)** part.

**Comment by jonathanhefner** [comment]
@uxxman 

> ```ruby
> person = Person.new
> person.name = "Volmer"
> 
> person.name   # => "Volmer"
> person.active  # => true
> ```

That looks good.  Let's go with that! :+1:
