### ISSUE TITLE
Documentation should specify which version of yarn to use

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#44391]
I was unable to find any documentation about which version is supported, although it looks like the directions in https://github.com/rails/rails/blob/0d91d4aa07cd69d97e8390176d43a93a862cca0a/guides/source/development_dependencies_install.md#ubuntu end up getting you 1.22

If you follow those links you end up redirected to this site (https://classic.yarnpkg.com/en/docs/install) where it says that yarn <2 is in maintenance mode and will soon reach EOL.

**Comment by p8** [comment]
@gmcgibbon There is an open PR that removes Yarn and Node from the "Getting Started" guide
and tries to update the "Working with Javascript" guide:
https://github.com/rails/rails/pull/43957

**Comment by ghiculescu** [comment]
Lots of docs have been updated recently, and I don't think Rails has a hard requirement on any Yarn version anymore, so I'm going to close this.
