### ISSUE TITLE
Multiple "fixtures" folders support

### ISSUE THREAD

**Issue by inem** [rails/rails#44418]
Hello, I am trying to have two sets of fixtures in my Rails app. The reason behind that is fixtures library became quite big, and hard to maintain. My idea is to have two separate sets of fixtures - one for one subset of features, another one - for the rest.

Another potential use-case: When you have a legacy app with a mess in fixtures, you put your fixtures into "quarantine" folder, and mark you tests accordingly, and go through your tests one by one and give fixtures a better organization in a separate folder (and making related tests use different fixtures folder).

I was able to find a brief mention that it fixtures path might be configurable [here](https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html): `ActiveSupport::TestCase.fixture_path=(path)`

Also [here](https://github.com/rails/rails/blob/24956f2e5fdbc43ff5e073a8f5c4d7f710d359e5/actionmailbox/test/test_helper.rb#L17): `ActionDispatch::IntegrationTest.fixture_path = ActiveSupport::TestCase.fixture_path`.

I tried setting alternative paths in:
- specific test files - with no effect
- test helper - got `NoMethodError: undefined method `users'`

I also tried to use low level helper `ActiveRecord::FixtureSet.create_fixtures('test/fixtures-2', model_name)`, but it gives you not very useable array of something.  Also, it seems to ignore the path you pass to it ('test/fixtures-2'):

```
 @name="users",
 @path="/usr/src/app/test/fixtures/users",
 @table_name="users">
```

I would appreciate any hints how could one make multiple folders of fixtures working in a Rails app. Thanks!

**Comment by gmcgibbon** [comment]
The fixtures path can be a glob pattern: https://github.com/rails/rails/blob/24956f2e5fdbc43ff5e073a8f5c4d7f710d359e5/activerecord/lib/active_record/test_fixtures.rb#L45 which can glob multiple directories.

Please use the mailing list or StackOverflow for help / questions. The issues tracker should be for issues only. Thanks!

**Comment by inem** [comment]
Well, I was considering to shoot a PR for this, but yes, you're right, I should've start with SO. Thanks!

**Comment by iMacTia** [comment]
@gmcgibbon we tried doing that just now but if we do, it breaks 2 lines later:

https://github.com/rails/rails/blob/24956f2e5fdbc43ff5e073a8f5c4d7f710d359e5/activerecord/lib/active_record/test_fixtures.rb#L47

@inem were you actually able to make this work? It doesn't look to me like this is currently supported

**Comment by gmcgibbon** [comment]
True, I just tried using a glob and that line doesn't quite parse the name correctly depending on the glob length v folder name length. We can probably use `File.basename` instead. Do you want to open a PR?

**Comment by iMacTia** [comment]
Sure, happy to give it a try.
I'll have a look myself as well, but are you aware of any other places where `fixture_path` is being used that might have similar issues? I just want to be sure I don't miss anything 😄

**Comment by inem** [comment]
@iMacTia nope, didn't work for me. Would be great if you find a way to achieve it!
