### ISSUE TITLE
Rails 5.2 Guides link leads to Edge Guides

### ISSUE THREAD

**Issue by fitterflytech** [rails/rails#44430]
This link I got from the homepage for Guides on Rails version 5.2 => https://guides.rubyonrails.org/v5.2/
which leads me to Edge guides page.

**Comment by elfotografo007** [comment]
I am experiencing the same issue.

**Comment by ckhall** [comment]
steps to reproduce:

visit `https:/guides.rubyonrails.org`
click `Rails 5.2` link (observe link href is `https://guides.rubyonrails.org/v5.2/`)
browser is redirected to `https://edgeguides.rubyonrails.org/`

<img width="876" alt="Screen Shot 2022-02-16 at 19 18 47" src="https://user-images.githubusercontent.com/11068/154379621-f0a92fc0-047b-4ad0-b803-0081e64d9b9d.png">

<img width="735" alt="Screen Shot 2022-02-16 at 19 20 51" src="https://user-images.githubusercontent.com/11068/154379823-9d9ca23a-12ed-4a09-b92c-d67416233ae5.png">

**Comment by rafaelfranca** [comment]
Thank you for reporting. Fixed now.
