### ISSUE TITLE
Doing a request.params within a log_tag lambda causes malformed parameters to bubble up to puma

### ISSUE THREAD

**Issue by arianf** [rails/rails#44444]
### Steps to reproduce
Change config.log_tag to the following:

```ruby
config.log_tags = [
  -> (req) { req.params[:hi] }
]
```

Then make a curl request with invalid data that is not `application/json` valid.
```bash
curl -X "PUT" "http://localhost:3000/?hi=5" \
     -H 'Content-Type: application/json' \
     -H 'Accept: application/json' \
     -d "asdfadf"
```

The error will bubble up to puma
`Puma caught this error: 765: unexpected token at 'asdfadf' (ActionDispatch::Http::Parameters::ParseError)`

### Expected behavior
To be captured internally within rails and a 400 respond be sent `{"status":400,"error":"Bad Request"}`

### Actual behavior
`Puma caught this error: 765: unexpected token at 'asdfadf' (ActionDispatch::Http::Parameters::ParseError)`

### System configuration
**Rails version**: I tried rails (7.0.1) and rails (5.2.6.2)

**Ruby version**:
2.7.2 and 2.6.9

**Comment by arianf** [comment]
This also prevents things like `rescue_from` from working.

```
rescue_from ActionDispatch::Http::Parameters::ParseError do |exception|
  render status: 418, json: { errors: [ exception.cause.message ] }
end
```

**Comment by gmcgibbon** [comment]
The `log_tags` run in rack middleware, and that gets called before the controller is called. Still, there might be room for improvement here. 👀 https://github.com/rails/rails/blob/d9edce650f215e821cc90108a8707c0ec24a9440/railties/lib/rails/application/default_middleware_stack.rb#L51

**Comment by gmcgibbon** [comment]
Looking further, since this happens at the middleware level, it doesn't seem reasonable to expect the controller to be able to rescue here. If you'd like to account for params parsing errors for malformed requests, you can rescue in your log_tags proc. Thanks for opening the issue! 😄

**Comment by arianf** [comment]
Thanks for looking into it @gmcgibbon

In case anyone else ever stumbles on this issue. We able to solve it for our use case, (since we are only looking to log query params), by being more specific and calling `req.query_parameters`

```ruby
config.log_tags = [
  -> (req) { req.query_parameters[:hi] }
]
```
