### ISSUE TITLE
Pathname.presence has surprising semantics

### ISSUE THREAD

**Issue by akimd** [rails/rails#44452]
Because `Object#blank?` bounces to `empty?` if it exists, and because `Pathname#empty?` checks whether the directory/file is empty, the result is, I venture, not the intended semantics.  IMHO, `Pathname#blank?` should check whether this is `Pathname.new('')`.

### Steps to reproduce
```ruby
p = Pathname.new('/tmp/foo')  # Where /tmp/foo does not exist.
p p.presence # => #<Pathname:/tmp/foo>
p.mkpath
p p.presence  # => nil

p Pathname.new('').blank? # => false
```

### Expected behavior

I expect `Pathname#blank?` to behave like `to_s.empty?`, or, arguably, like `to_s.blank?`.

### Actual behavior

Tells whether the file/dir is empty.

### System configuration
**Rails version**:

7.0.1

**Ruby version**:

2.7.4

**Comment by byroot** [comment]
That's a tricky one.

I agree that the current semantic makes little sense. `Pathname#empty?` semantic is:

> exists and is empty file or directory

Which I doubt is what you're looking for when doing something likes `paths.reject!(&:blank?)`.

The backward compatibility risk of changing this seems small.

**Comment by byroot** [comment]
https://github.com/rails/rails/pull/44485
