### ISSUE TITLE
`# :nodoc:` on ActiveModel::Errors#copy!

### ISSUE THREAD

**Issue by jameno** [rails/rails#44453]
`ActiveModel::Errors#copy!` is a useful method, but it does not appear in the documentation.

Is there some reason this is marked with `# :nodoc:`?

https://github.com/rails/rails/blob/0dbe699d5cd2b57a4a253283a7d7b7ffdd74db28/activemodel/lib/active_model/errors.rb#L102-L115

**Comment by rafaelfranca** [comment]
The public method is `merge!`. Is there anything in `copy!` that merge doesn't provide?
