### ISSUE TITLE
validates_with can't be used with multiple Validators when the options hash must contain :attributes

### ISSUE THREAD

**Issue by dspaeth-lp** [rails/rails#44460]
The `ActiveModel::EachValidator`
[deletes](https://github.com/rails/rails/blob/7-0-stable/activemodel/lib/active_model/validator.rb#L139) the `:attributes` key from the provided options hash.

When I use `validates_with` with multiple validators that require an `:attribute` options, I get an exception,
because the `options` hash is [reused](https://github.com/rails/rails/blob/7-0-stable/activemodel/lib/active_model/validations/with.rb#L142) and altered under the hood.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end
end

class Post < ActiveRecord::Base
  validate :my_validations

  def my_validations
     validates_with ActiveRecord::Validations::UniquenessValidator, ActiveRecord::Validations::PresenceValidator, { attributes: [:name], allow_nil: true }
  end
end

class BugTest < Minitest::Test
  def test_validations
    post = Post.new name: 'a' 

    assert post.valid?
  end
end
```

### Expected behavior

This test should pass. `validates_with` should pass a duplicate of the option hash to the validators or 
`ActiveModel::EachValidator` should duplicate the options hash before modifying it.

### Actual behavior

An `ArgumentError`: `:attributes` cannot be blank

### System configuration
**Rails version**: 6.1, 7.0

**Ruby version**:  2.7.5

**Comment by fatkodima** [comment]
> ActiveModel::EachValidator should duplicate the options hash before modifying it

I think this is the way to go. And we will be safe to any other callers passing options, not only for `validates_with`.

Do you want to open a PR?

**Comment by dspaeth-lp** [comment]
I did open https://github.com/rails/rails/pull/44476 

I did go with the `dup` route. The docs for `ActiveModel::EachValidator`
says that the `:attribute` key is deleted from the `Validator` attribute `options`, 
so keeping the `attributes` key would have been a breaking change.
