### ISSUE TITLE
Request.headers in a JSON response raises SystemStackError

### ISSUE THREAD

**Issue by realmocaccino** [rails/rails#44477]
### Steps to reproduce
```ruby
# app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return render :json => {
      :headers => request.headers
    }, status: :ok
    rescue SystemStackError => e
      head :internal_server_error
  end
end

# test/controllers/home_controller_test.rb
require "test_helper"

class HomeControllerTest < ActionDispatch::IntegrationTest
  OK = 200
  INTERNAL_SERVER_ERROR = 500

  def test_returns_ok
    get '/'
    assert_not response.status == OK
  end
  def test_returns_internal_server_error
    get '/'
    assert response.status == INTERNAL_SERVER_ERROR
  end
end
```

### Expected behavior
Output request's HTTP headers in a JSON response

### Actual behavior
Application raises SystemStackError (stack level too deep)

### System configuration
**Rails version**:
6.1.4.6
**Ruby version**:
3.0.2 p107

**Comment by tenderlove** [comment]
My guess is that `headers` probably contains a cyclic data structure.  Here is a trivial program that will raise a `SystemStackError`:

```ruby
x = []
x << x
x.as_json
```

We could probably use the `options` parameter from `as_json` to detect cycles and do something, but I'm not sure what we would do besides raise an exception.  A specific exception is probably better than `SystemStackError`, but I'm not sure if it's worth the refactoring?

FWIW this also raises a `SystemStackError` and there's no Rails involved:

```ruby
require "json"

x = []
x << x
JSON.dump x
```

🤷‍♀️

**Comment by tenderlove** [comment]
My guess is that `headers` probably contains a cyclic data structure.  Here is a trivial program that will raise a `SystemStackError`:

```ruby
x = []
x << x
x.as_json
```

We could probably use the `options` parameter from `as_json` to detect cycles and do something, but I'm not sure what we would do besides raise an exception.  A specific exception is probably better than `SystemStackError`, but I'm not sure if it's worth the refactoring?

FWIW this also raises a `SystemStackError` and there's no Rails involved:

```ruby
require "json"

x = []
x << x
JSON.dump x
```

🤷‍♀️

**Comment by nvasilevski** [comment]
I agree that investing into making messaging better might not be worth it mainly because serializing whole `request.headers` object doesn't seem like a common use-case for a regular application
