### ISSUE TITLE
ActiveStorage :host in subfolder

### ISSUE THREAD

**Issue by exocode** [rails/rails#44474]
### Steps to reproduce
I am using Rails 6.1.4.1 as my backend API.
Rails is also handling image upload and variants
I am creating URLs in the model

Becuase of CORS I am running Rails in the "subfolder" `/backend`

But the UrlHelpers of ActiveStorage are truncating the `/backend` part of my `ActiveStorage::Current.host` path.

```ruby

model Product
  ActiveStorage::Current.host = "http://localhost:8000/backend/"

  has_many_attached :photos do |attachable|
    attachable.variant({thumbnail: { resize_to_fill: [90, 90] })
  end

end

Product.last.photos.first.url
```

### Expected behavior
urls generated by ActiveStorage should be `http:://localhost:8000/backend/`
`http://localhost:8000/backend/rails/active_storage/disk/--9c2c6/400x400.png`

### Actual behavior
But gets returned
`http:://localhost:8000`
`http://localhost:8000/rails/active_storage/disk/--9c2c6/400x400.png`
### System configuration
**Rails version**:
`Rails 6.1.4.1`
**Ruby version**:
`ruby 2.7.2p137`

**How can I explicitly reroute the ActiveStorage generated URLs?**

**Comment by pixeltrix** [comment]
@exocode have you tried using [`config.active_storage.routes_prefix `][1] ?

[1]: https://guides.rubyonrails.org/configuring.html#config-active-storage-routes-prefix

**Comment by gmcgibbon** [comment]
It looks like `config.active_storage.routes_prefix` should do what you want here. Closing for now, but let us know if you encounter any issues with it!
