### ISSUE TITLE
The PR 43671 has broken many because `new_controller_thread` just copy `Thread.current`  fiber locals

### ISSUE THREAD

**Issue by qinmingyuan** [rails/rails#44496]
this PR #43671  has broken many because `new_controller_thread` just copy `Thread.current`  fiber locals

https://github.com/rails/rails/blob/dbdb546c0cf1de4e0745ea00234558425dc37457/actionpack/lib/action_controller/metal/live.rb#L251-L263

_Originally posted by @qinmingyuan in https://github.com/rails/rails/pull/43671#issuecomment-1046464496_

**Comment by casperisfine** [comment]
@qinmingyuan I backported a fix to `7-0-stable`, could you confirm it fixes your issues and that there's not some other state we're missing?

**Comment by qinmingyuan** [comment]
`undefined local variable or method `context' for ActiveSupport::IsolatedExecutionState:Module`  7-0-stable raise this errors

main branch fixed my issues

**Comment by byroot** [comment]
Fixed in 647cf865a4ef8f067defffbfed74e001f4d00039
