### ISSUE TITLE
Column comments set with `add_column` are now stripped from PostgreSQL structure dumps

### ISSUE THREAD

**Issue by chrisandreae** [rails/rails#44498]
Commit https://github.com/rails/rails/commit/d5745607463ef72adb6a34e3ecc9b3820484a33f adds the `--no-comment` pg_dump option to the `structure_dump` database task. The linked issues suggest that the motivation for this was that setting comments on PostgreSQL extensions such as `plpgsql` requires elevated database permissions.

However, this breaks the [documented](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L559-L560) functionality of setting a `comment:` on database columns. While the comment will be added to the live database during the migration, it will no longer be emitted as part of the `structure.sql` dump, causing the committed structure to diverge from the schema in the database.

### Steps to reproduce

Add a column with a comment in a migration, then update the database structure dump.

```ruby
add_column(:users, :some_column, :integer, comment: 'the description of the column')
```

### Expected behavior

The comment is emitted in `structure.sql`, in such a way that it will be restored to the database as part of loading the schema.

```sql
--
-- Name: COLUMN users.some_column; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.some_column IS 'the description of the column';
```

### Actual behavior

The comment is not emitted.

### System configuration
**Rails version**: [`main`](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L61)

**Comment by ghiculescu** [comment]
Good point. @jaynetics FYI. Maybe we should add a setting about if you want to use comments or not. If enabled, `add_column comment:` works, and if disabled then it does https://github.com/rails/rails/pull/43216

**Comment by ghiculescu** [comment]
Made a PR: https://github.com/rails/rails/pull/44603
