### ISSUE TITLE
ActionMailer smtp_settings lost with ruby 3.0 (but applied with ruby 2.7)

### ISSUE THREAD

**Issue by hoeni** [rails/rails#44503]
### Steps to reproduce

Scaffold a new Rails 6.1 App.
Set `production.conf` to
```ruby
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
      address: 'smtpout.xxxx.com',
      port: 25,
      enable_starttls: false,
      enable_starttls_auto: false,
      openssl_verify_mode: OpenSSL::SSL::VERIFY_NONE,
      ssl: false,
      tls: false,
  }
```
So there should be no TLS/SSL handshake by any means.

Rails console shows, the config has been imported correctly:

```irb
RAILS_ENV=production rails c
Loading production environment (Rails 6.1.4.6)
irb(main):001:0> mailer = ActionMailer::Base.new
=> #<ActionMailer::Base:0x00000000008688>
irb(main):002:0> mailer.smtp_settings
=> {:address=>"smtpout.mitxp.com", :port=>25, :enable_starttls=>false, :enable_starttls_auto=>false, :openssl_verify_mode=>0, :ssl=>false, :tls=>false}
irb(main):003:0> mailer.mail(from: 'sender@example.com', to: 'recipient@ example.com', subject: 'test', body: "Hello, you've got mail!").deliver
```

### Expected behavior
ActionMailer should connect to the unsecured mail server (which has a self-signed certificate).

### Actual behavior
Using ruby 2.7: This works fine.
Using ruby 3.0: This results in an error:
```
/usr/local/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate) (OpenSSL::SSL::SSLError)
```

### System configuration
actionmailer 6.1.4.6

**Comment by gmcgibbon** [comment]
I can't reproduce the issue. I would check the deployment setup to make sure nothing is broken. Ruby version upgrades shouldn't modify this behaviour. Closing.

**Comment by hoeni** [comment]
That was my idea at first, until I reproduced it in a naked ruby:2.7 vs. ruby:3.0 docker image. I'll try to set up a test case to reproduce. Thanks so far!

**Comment by zhongsheng** [comment]
I got this problem too.
Rails 7.0.0.rc1 with ruby(3.0.2p107 [x86_64-linux]) no problem.

When I upgrade to Rails 7.0.2.2 and ruby(3.1.0p0 [x86_64-linux]),  lost the smtp_settings.

**Comment by hoeni** [comment]
You can reproduce with this simple Dockerfile. Using `ruby:2.7-alpine` and a valid recipient it delivers the mail, using `ruby:3.0-alpine` it gets the SSL error, because it did not disable TLS. Mail server is a vanilla Ubuntu postfix, but any other with invalid cert should do as well.

I'll see if I can supply a Dockerfile for supplying this mail server, too. However, this ticket got closed and probably no one is reading here anymore, right?
 

Dockerfile:
```docker
FROM ruby:2.7-alpine

RUN apk --update add build-base shared-mime-info
RUN gem install rails -v 6.1
COPY send.rb /
CMD ruby send.rb
```

send.rb:
```ruby
require 'action_mailer'

ActionMailer::Base.delivery_method = :smtp
ActionMailer::Base.smtp_settings = {
  address: 'mailserver',
  port: 25,
  enable_starttls: false,
  enable_starttls_auto: false,
  openssl_verify_mode: OpenSSL::SSL::VERIFY_NONE,
  ssl: false,
  tls: false,
}

ActionMailer::Base.new.mail(
  from: 'send@example.com',
  to: 'receive@example.com',
  subject: 'test',
  body: "Hello, you've got mail!"
).deliver
```

**Comment by hoeni** [comment]
@zhongsheng You say it's working for you with 3.0.2p107, so maybe that's not a problem generic to ruby 2 vs 3?
The docker tag `ruby:2.7-alpine` installed a newer ruby, so maybe between was, where the problem started?

```bash
docker run --rm cert-error_script ruby --version
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux-musl]
```

**Comment by wollistik** [comment]
@hoeni We had the same issue when upgrading our app to Ruby 3.0. The root cause is that with Ruby 3.0 there was a change in Net::SMTP (which comes bundled in version 0.2.1), which enables server certificate validation by default (see https://github.com/ruby/net-smtp/pull/12). There is also a PR in the mail gem to adapt to this change (see https://github.com/mikel/mail/pull/1435).

**Comment by ghiculescu** [comment]
Given that, are any Rails changes needed or shall we close this?

**Comment by hoeni** [comment]
Afaics, this needs to be fixed in the Mail gem: https://github.com/mikel/mail/pull/1435#issuecomment-1066639815
Thanks @wollistik for the relevant hint.
