### ISSUE TITLE
Update password to an empty string("") not working properly.

### ISSUE THREAD

**Issue by rajesh-rrk** [rails/rails#44516]
I'm using **has_secure_password** for User model. When I try to update my existing user's password to an empty string(''), It's not raising the **Password can't be blank** error. But when I try with nil, It's raising the error.

**Reference**:
```
User.first.update!(password: '')
  User Load (1.1ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> true
>> User.first.update!(password: nil)
  User Load (2.8ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
/Users/rajeshkanna/.rvm/rubies/ruby-3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-7.0.1/lib/active_record/validations.rb:80:in `raise_validation_error': Validation failed: Password can't be blank (ActiveRecord::RecordInvalid)
```

I've analyzed and figured out an issue in **secure_password.rb** file.

The issue is in secure_password.rb file, line no 96,
`unencrypted_password.nil?` should be change it to `unencrypted_password.nil? || unencrypted_password.empty?`

https://github.com/rails/rails/blob/1c976f26dfa2423bede55e89c8e6119d45edd79a/activemodel/lib/active_model/secure_password.rb#L96

**Comment by mansakondo** [comment]
Or `unencrpted_password.present?` maybe ?

**Comment by rajesh-rrk** [comment]
We can also use `unencrpted_password.bank?` instead of `unencrypted_password.nil? || unencrypted_password.empty?`. Because we are trying to check blank check on if condition.

We can use `present?` by making the below change,
```
if unencrypted_password.present?
   instance_variable_set("@#{attribute}", unencrypted_password)
   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
   self.public_send("#{attribute}_digest=", BCrypt::Password.create(unencrypted_password, cost: cost))
else
   instance_variable_set("@#{attribute}", nil)
   self.public_send("#{attribute}_digest=", nil)
end
```

**Comment by mansakondo** [comment]
Yes exactly.

**Comment by mansakondo** [comment]
It works either way, but in any case this change seems fair to me. Maybe you can open a PR to suggest this change.

**Comment by rajesh-rrk** [comment]
Sure, I'll open a PR for the same. Thanks.

**Comment by rajesh-rrk** [comment]
PR with fixes - https://github.com/rails/rails/pull/44582
