### ISSUE TITLE
Incorrect type definition for direct upload

### ISSUE THREAD

**Issue by Oleksii14** [rails/rails#44524]
### Steps to reproduce

1. Open `@types/rails__activestorage/index.d.ts`
2. Open `@rails/activestorage/src/direct_upload.js`
3. See that the class constructor is different from what we have in the type definition file.

### Expected behavior
The type definition from step 1 should be correct and implement the class from step 2

### Actual behavior
The type definition from step 1 should be correct and related to the class from step 2. It causes TS errors. And if those errors are fixed according to the incorrect type definition, the DirectUpload class does not work as expected

**Comment by SkipKayhil** [comment]
The [Definitely Typed repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/rails__activestorage) is the source for `@types/rails__activestorage`, this should probably be raised as an issue over there

**Comment by p8** [comment]
I agree with @SkipKayhil this is a Definitly Typed issue.
