### ISSUE TITLE
PR #36210 solved only for `save!`, but not for `save` neither `valid?`.

### ISSUE THREAD

**Issue by cgimenes** [rails/rails#44533]
Related PR: https://github.com/rails/rails/pull/36210

```ruby
class List < ApplicationRecord
  has_many :items, class_name: "ListItem", dependent: :destroy
end

class ListItem < ApplicationRecord
  belongs_to :list

  validates_uniqueness_of :name, scope: :list_id
end

l = List.create name: 'TestList'
l.items.build name: 'Item'
l.items.build name: 'Item'
l.valid? # this returns true instead of false
l.save # this returns false correctly, but with a rollback exception
```

Confirmed on Rails 7.0.2.2

**Comment by thiagofm** [comment]
I've managed to reproduce in a test inside the activerecord codebase.

What happens there is that Rails doesn't know that 'Item' is not unique(when and evaluates both items separately, without in regards to its value. So both items's `valid?` call will yield `true`.

But when the record tries to be saved, it will test for real if the record is unique, failing to `save`.

It would need some custom logic to handle only uniqueness validations. If we want to go through that path, I can try to implement a fix.
