### ISSUE TITLE
Unintialized Constant I cannot figure out in Rails 7

### ISSUE THREAD

**Issue by resistorsoftware** [rails/rails#44546]
I have an app directory in my Rails 7 App, app/beer, and in that folder a file named cool.rb with a defined execute() method.

In an ActiveJob **DrinkSudsJob** perform method I am calling the method execute from cool.rb as: 

    def perform(**jobargs)
      Beer::Cool.execute
    end

But my App blows up. Tells me **unitialized constant DrinkSudsJob::Beer**

Zeitwerk:check tells me everything is fine. What am I doing wrong here? 

    bin/rails r 'puts ActiveSupport::Dependencies.autoload_paths'
    /Users/sputz/Documents/Workspace/Apps/2022/fug/app/beer

### System configuration
**Rails version**: 7.0.2

**Ruby version**: 3.1.0

**Comment by PedroAugustoRamalhoDuarte** [comment]
By default, rails only load default folders at the start, so when you create a new folder you need to add in config.authload_paths.

Solution: Adds this line inside class Application in application.rb
```ruby
config.autoload_paths << Rails.root.join("app/beer")
```

If this already set, try to call:
```ruby
::Beer::Cool.execute
```

**Comment by rafaelfranca** [comment]
> Solution: Adds this line inside class Application in application.rb
> 
> ```ruby
> config.autoload_paths << Rails.root.join("app/beer")
> ```

This is not a solution. Anything inside `app` is already in the autoload paths, you just need to restart the server.

**Comment by resistorsoftware** [comment]
I am not using spring. I also found that by adding a directory to app/ I was able to make progress. 

So by doing nothing but adding **brewery** to app/, I was able to reference my objects without complaint. So zeitwerk autoloaded /app/brewery and in my ActiveJob, I was able to reference Beer::Cool.execute() without a problem. 

I have no idea why that even works, nor do I care too much. But it does go to show you can go far on super flimsy understanding of how Rails and autoload go hand in hand. 

I suppose I could try your approach again, and undo that work. Still. I remain perplexed as to why my original effort fails. Zeitwerk goes to great lengths to ensure we have to do as little as possible, all the tools say things are fine, yet it does not work.

**Comment by resistorsoftware** [comment]
> > Solution: Adds this line inside class Application in application.rb
> > ```ruby
> > config.autoload_paths << Rails.root.join("app/beer")
> > ```
> 
> This is not a solution. Anything inside `app` is already in the autoload paths, you just need to restart the server/process/spring.

I am not sure what you speak of here. Restarting my server does not make objects magically start working.

**Comment by matthewd** [comment]
Zeitwerk expects to find a fully-qualified name inside one of your autoload paths.

If your constant is `Beer::Cool`, then it expects to find `beer/cool.rb` inside one of your autoload paths.

It won't find `app/beer/cool.rb`, because `app/beer/` is the nearby autoload path: that file would provide a top-level `Cool`.

(Models live in `app/models/foo.rb`, corresponding to `Foo`, not `Models::Foo`, etc.)

As you've found, adding another level of directory between `app/` and your class names is the correct solution.

**Comment by resistorsoftware** [comment]
I appreciate that explanation @matthewd. It totally makes sense now. Took me a long time to figure it out, but still.
