### ISSUE TITLE
Something wrong when create new ror application

### ISSUE THREAD

**Issue by masterbo98** [rails/rails#44552]
### Steps to reproduce

```ruby
# Your reproduction script goes here
```
When I use the command "rails new myapp"，there came some errors, can anyone teach me how to solve this problem?
### Actual behavior

![image](https://user-images.githubusercontent.com/73686357/155722373-a9f4d0a1-4e40-4334-8cd1-5661089045f3.png)

### System configuration
**Rails version**:
7.0.2.2
**Ruby version**:
3.0.3

**Comment by fa11enangel** [comment]
As the error says: you are missing git as version control system. Try to install it.
