### ISSUE TITLE
Upgrade to active_storage for 6.0 to 6.1 is objected to by strong_migrations gem

### ISSUE THREAD

**Issue by obromios** [rails/rails#44557]
### Steps to reproduce
Upgrading from rails 6.0 to 6.1, run
```
rails active_storage:update
rails db:migrate
```

### Expected behavior
I imagine this normally just works and creates the required changes to the database

### Actual behavior
The migration fails with the following message

```
rails db:migrate
== 20220226005243 AddServiceNameToActiveStorageBlobs: migrating ===============
-- column_exists?(:active_storage_blobs, :service_name)
   -> 0.0097s
-- add_column(:active_storage_blobs, :service_name, :string)
   -> 0.0051s
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

=== Dangerous operation detected #strong_migrations ===

Changing the type is safe, but setting NOT NULL is not.
```

The exception is causes by the  strong_migration [gem](https://github.com/ankane/strong_migrations).  Looking at their github page it seems to say that requiring a field to be not null 'on an existing column blocks reads and writes while every row is checked'. So according to the strong_parameters gem this is dangerous practice.  Should I just turn of the strong_migration check for this particular migration or is there an issue with the migration as it stands?

### System configuration
**Rails version**:
rails '6.1.4.6'

**Ruby version**:
ruby '2.7.5'

**Comment by jon-sully** [comment]
If your app has some kind of down time (maybe during evenings or low use periods), that might be a good time to go ahead and run the migration. strong_migrations block that type of migration because it can lock the table and prevent (in a chain of events) requests to your Rails app from completing until the migration is done. If the table in question has millions of records, that could take a while. So if you have a low-use / downtime period that you wouldn't be worried about a few requests being a little slow (depending on how many active storage records you have), you might give it a shot.

**Comment by obromios** [comment]
The migration in question is
```
# This migration comes from active_storage (originally 20191206030411)
class CreateActiveStorageVariantRecords < ActiveRecord::Migration[6.0]
  def change
    create_table :active_storage_variant_records do |t|
      t.belongs_to :blob, null: false, index: false
      t.string :variation_digest, null: false

      t.index %i[ blob_id variation_digest ], name: "index_active_storage_variant_records_uniqueness", unique: true
      t.foreign_key :active_storage_blobs, column: :blob_id
    end
  end
end
```
So it appears to be creating a table, so when the migration is run the table would have zero records, so perhaps strong_migrations is incorrectly flagging this migration?

**Comment by obromios** [comment]
Actually looking at error message more carefully, the relevant migration is
```
# This migration comes from active_storage (originally 20190112182829)
class AddServiceNameToActiveStorageBlobs < ActiveRecord::Migration[6.0]
  def up
    unless column_exists?(:active_storage_blobs, :service_name)
      add_column :active_storage_blobs, :service_name, :string

      if configured_service = ActiveStorage::Blob.service.name
        ActiveStorage::Blob.unscoped.update_all(service_name: configured_service)
      end

      change_column :active_storage_blobs, :service_name, :string, null: false
    end
  end

  def down
    remove_column :active_storage_blobs, :service_name
  end
end
```
so would your observation hold that if there are a large number of entries in this table it should be done at a quiet time or under maintenance?

**Comment by obromios** [comment]
OK, so I have proceeded with the migrations.  To do this, I created a `config/initializers/strong_migrations.rb` file and put the following in it:
```
# only check migrations after this one.
StrongMigrations.start_after = <date/time number of migration  you want to skip e.g. 20220226005244>
```
Thank you for your help. As far as I am concerned this issue is resolved.

**Comment by hahmed** [comment]
Glad you managed to solve it @obromios -- will go ahead and close this issue

**Comment by kanejamison** [comment]
In case anyone else encounters this, we updated the migration to ignore strong migrations but forgot to check blob count on production. It took our app 259 seconds to run the AddServiceNameToActiveStorageBlobs migration against 5.5 million blobs during release on Heroku. So, good to deploy during a slow time.

``` 
I, [2024-02-06T16:25:48.796936 #14]  INFO -- : Migrating to AddServiceNameToActiveStorageBlobs (20240205201219)
== 20240205201219 AddServiceNameToActiveStorageBlobs: migrating ===============
-- table_exists?(:active_storage_blobs)
   -> 0.0011s
-- column_exists?(:active_storage_blobs, :service_name)
   -> 0.0037s
-- add_column(:active_storage_blobs, :service_name, :string)
   -> 0.0092s
-- change_column(:active_storage_blobs, :service_name, :string, {:null=>false})
   -> 22.5280s
== 20240205201219 AddServiceNameToActiveStorageBlobs: migrated (259.1581s) ====
I, [2024-02-06T16:30:07.968863 #14]  INFO -- : Migrating to CreateActiveStorageVariantRecords (20240205201220)
== 20240205201220 CreateActiveStorageVariantRecords: migrating ================
-- table_exists?(:active_storage_blobs)
   -> 0.0011s
-- create_table(:active_storage_variant_records, {:id=>:primary_key, :if_not_exists=>true})
   -> 0.0686s
== 20240205201220 CreateActiveStorageVariantRecords: migrated (0.0739s) =======
```
