### ISSUE TITLE
tests relying on non-existant Gemfiles

### ISSUE THREAD

**Issue by Segaja** [rails/rails#44565]
Both the tests for `activestorage` and `actionmailbox` in version 7.0.2 rely on a `Gemfile` being present in their subfolders ( https://github.com/rails/rails/blob/v7.0.2/activestorage/test/dummy/config/boot.rb, https://github.com/rails/rails/blob/v7.0.2/actionmailbox/test/dummy/config/boot.rb ) or being provided via environment variable.

The fallback path in both cases doesn't contain any `Gemfile`, so I'm unsure as to how to run these tests without them or what the Gemfile needs to contain.

Can you give some advice?

**Comment by Segaja** [comment]
actiontext ( https://github.com/rails/rails/blob/v7.0.2/actiontext/test/dummy/config/boot.rb ) is also affected by this issue.

**Comment by matthewd** [comment]
It does look like those paths are wrong. In practice they're irrelevant, though: the test application will always be invoked under Bundler, which will have already located the Gemfile in the repo root.
