### ISSUE TITLE
SVG tags generated with tag helper are not self closing

### ISSUE THREAD

**Issue by davekaro** [rails/rails#44563]
### Steps to reproduce
Generate HTML using this code to output an SVG:

```
tag.div(style: "height: 100px; width: 100px") do
  tag.svg(viewBox: "0 0 100 100", xmlns: "http://www.w3.org/2000/svg") do
    tag.g(fill: "white", stroke: "green", "stroke-width": "5") do
      tag.circle(cx: 40, cy: 40, r: 25) +
        tag.circle(cx: 60, cy: 60, r: 25)
    end
  end
end
```

### Expected behavior
`<circle>` tags inside the SVG should be closed.

```
<div style="height: 100px; width: 100px">
  <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <g fill="white" stroke="green" stroke-width="5">
      <circle cx="40" cy="40" r="25"></circle>
      <circle cx="60" cy="60" r="25"></circle>
    </g>
  </svg>
</div>
```

SVG should look like
![image](https://user-images.githubusercontent.com/21263/155895035-787f3854-a017-4b01-bb40-c639dd247421.png)

### Actual behavior
`<circle>` tags are not closed.

```
<div style="height: 100px; width: 100px">
  <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <g fill="white" stroke="green" stroke-width="5">
      <circle cx="40" cy="40" r="25">
      <circle cx="60" cy="60" r="25">
    </g>
  </svg>
</div>
```

The browser ends up nesting the `<circle>` tags like:

```
<div style="height: 100px; width: 100px">
  <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <g fill="white" stroke="green" stroke-width="5">
      <circle cx="40" cy="40" r="25">
        <circle cx="60" cy="60" r="25"></circle>
      </circle>
    </g>
  </svg>
</div>
```

The final SVG looks like:
![image](https://user-images.githubusercontent.com/21263/155895127-2b5529b7-f987-47b8-b0e1-5ed6a0022e6e.png)

Changes introduced in Rails 7 in https://github.com/rails/rails/pull/43232 broke this SVG. I think the changes are not correct. Only [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) can omit the end tag. Tags inside SVG elements are not considered void elements but rather are [foreign elements](https://dev.w3.org/html5/html-author/#foreign-elements) (elements in the SVG namespace). These elements must be closed with either an end tag (like they were before the change), or by self-closing like `<circle cx="60" cy="60" r="25" />`.

### System configuration
**Rails version**: 7.0.2.2

**Ruby version**: 3.1.1

**Comment by matthewd** [comment]
Yeah, that change sounds wrong. 

Would you like to open a PR that reverts it, and adds some new tests to protect the better behaviour? 

We could possibly retain the new list of SVG-related likely-empty tags, and special-case them to be self-closing, just to make the output look more like people expect. But they were also perfectly valid before, and the code is simpler without an extra special case. 🤷🏻‍♂️

**Comment by davekaro** [comment]
Great I will try making a PR. Thanks for the input.
