### ISSUE TITLE
Rails 7 looking for application.css

### ISSUE THREAD

**Issue by josephmo** [rails/rails#44583]
### Steps to reproduce

    Mac OS Monterey
    Rails 7.0.2.2
    Ruby 3.1.0
    yarn 1.22.17
    node 17.5.0

I created an application as follows:

`rails new myapp --database=mysql --skip-test --css=bootstrap
`
I added the DB credentials, and created the DB

`rake db:create
`
Then I added a static home page (View and Controller) and made the home page the root page.

Then I added the Devise Gem and produced all the views and controllers. Then I migrated the database.

On my local development machine, everything was running fine. I pushed the code to the repository, and then cloned the repo to another folder MyApp2

From MyApp2, I did:

```
bundle install
bundle update
```
And then:

`rails s
`

I got an error message:

```
Sprockets::Rails::Helper::AssetNotFound in StaticPages#home
Showing MyApp2/app/views/layouts/application.html.slim where line #9 raised:
The asset "application.css" is not present in the asset pipeline.

  = csrf_meta_tags
  = csp_meta_tag
  = stylesheet_link_tag "application", "data-turbo-track": "reload"
  = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
body
  = yield

```

There is no "application.css", it was deleted by the install process, that replaced it with "application.bootstrap.scss"

Any idea what I'm missing before I start the server?

```ruby
# Your reproduction script goes here
```

### Expected behavior

I am expecting to see the home page

### System configuration
**Rails version**:

7.0.2.2

**Ruby version**:

3.1.0

**Comment by yahonda** [comment]
There was a similar issue reported https://github.com/rails/rails/issues/43677 .

**Comment by josephmo** [comment]
I saw (https://github.com/rails/rails/issues/43677)  and it does not address the issue. #43677 is about generating an application and running it. This is about cloning a repo of the application that's already running, and trying to get the cloned repo to work on my local machine.

**Comment by SkipKayhil** [comment]
I think you're missing `yarn build:css --watch`, which is how cssbundling compiles in development. If you use `bin/dev` script or run `foreman` yourself then this should happen automatically as its listed in `Procfile.dev`

**Comment by JosephProxLearn** [comment]
```
yarn build:css --watch                                                                                                                                                                                         03-01-2022  7:38:19
yarn run v1.22.17
$ sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules --watch
/bin/sh: sass: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by josephmo** [comment]
npm v 8.4.1

And here's my package.json:

`{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.0.1",
    "@hotwired/turbo-rails": "^7.1.1",
    "@popperjs/core": "^2.11.2",
    "bootstrap": "^5.1.3",
    "bootstrap-icons": "^1.8.1",
    "esbuild": "^0.14.23",
    "sass": "^1.49.9"
  },
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
    "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules"
  }
}
`

**Comment by josephmo** [comment]
npm 8.4.1

{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.0.1",
    "@hotwired/turbo-rails": "^7.1.1",
    "@popperjs/core": "^2.11.2",
    "bootstrap": "^5.1.3",
    "bootstrap-icons": "^1.8.1",
    "esbuild": "^0.14.23",
    "sass": "^1.49.9"
  },
  "scripts": {
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds",
    "build:css": "sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules"
  }
}

**Comment by josephmo** [comment]
I've already tried bin/dev it did not work.

**Comment by an280420** [comment]
tried 
``` ./bin/dev ```

**Comment by josephmo** [comment]
@an280420 Yes .bin/dev, same issue as described in my issue report

**Comment by an280420** [comment]
or
```
npm remove yarn
yarn install
./bin/dev
```

**Comment by josephmo** [comment]
@an280420 It worked this time around. Why? Does this mean that I will have to start the server this way, always? Should this be reflected somewhere, or will it be fixed, in order for it to work as it should?

**Comment by msxavi** [comment]
How should we be handling this when running tests on CI?
```
  15) /projects PATCH /update with invalid parameters renders a successful response (i.e. to display the 'edit' template)
      Failure/Error: <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

      ActionView::Template::Error:
        The asset "application.css" is not present in the asset pipeline.
        
 ......
       # --- Caused by: ---
      # Sprockets::Rails::Helper::AssetNotFound:
      #   The asset "application.css" is not present in the asset pipeline.
      #   /usr/local/bundle/gems/sprockets-rails-3.4.2/lib/sprockets/rails/helper.rb:84:in `compute_asset_path' 
```

**Comment by Edouard-chin** [comment]
@msxavi You'd have to configure a CI step to compile the assets using `yarn build:css`. Worth to note that if your CI is configured to run `bin/rails test:all`, `bin/rails test:system` etc.. then this the compilation phase will be done automatically, this however doesn't work if you use `bin/rails test` as noted in the README https://github.com/rails/cssbundling-rails#css-bundling-for-rails

**Comment by Edouard-chin** [comment]
I'm going to close this as I'm not seeing anything broken but more a confusion on how cssbundling-rails works. Maybe we could clarify this in the README in the appropriate repo https://github.com/rails/cssbundling-rails

**Comment by seanarnold** [comment]
> > I think you're missing `yarn build:css --watch`,
> 
> yarn is not mentioned at all in [guides.rubyonrails.org/asset_pipeline.html](guides.rubyonrails.org/asset_pipeline.html)

Indeed. The documentation at https://guides.rubyonrails.org/asset_pipeline.html still mentions Coffeescript. It really needs to be updated with the latest way of doing things.
