### ISSUE TITLE
Rails 7: `implicit_order_column` does not order records

### ISSUE THREAD

**Issue by john-999** [rails/rails#44621]
### How to to reproduce:

In the file `app/models/application_record.rb`, add a `implicit_order_column` as follows:
```
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  self.implicit_order_column = 'created_at'
end
```
A query like...
```
User.all
```
...will fail to return the records in the `created_at` order.

### System configuration
**Rails version**: Rails 7.0.2.2

**Ruby version**: ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

**Comment by fatkodima** [comment]
https://github.com/rails/rails/pull/34480  - It was meant that this is applied to ordered finder methods like `first`/`last`.  

So, this is working as expected. I think I would be surprised if `.all` will be implicitly ordered.

**Comment by john-999** [comment]
It is my understanding that the most prominent use case of `implicit_order_column` is to accommodate the use of `UUID` as the primary key, in which case it seems natural to me to expect the `.all` query to support the same logic as `.first` and `.last`.

But that's just... like... my opinion, man. ;-)

**Comment by eugeneius** [comment]
As @fatkodima mentioned, this is working as intended (and documented):

https://api.rubyonrails.org/classes/ActiveRecord/ModelSchema.html#method-c-implicit_order_column

> The name of the column records are ordered by if no explicit order clause is used during an ordered finder call.

`all` is not an ordered finder call. Note that `all` executes `SELECT * FROM table`, with no order clause; `first` and `last` order by primary key by default, which is problematic when using UUIDs.
