### ISSUE TITLE
Rails 7: `default_scope` with `all_queries: true` -> syntax error

### ISSUE THREAD

**Issue by john-999** [rails/rails#44620]
### How to to reproduce:

In the file `app/models/application_record.rb`, add a `default_scope` as follows:
```
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  default_scope { order(created_at: :asc) }, all_queries: true
end
```
This will throw an error like:
```
/home/user/Websites/someproject/app/models/application_record.rb:3: syntax error, unexpected ',', expecting `end'
...pe { order(created_at: :asc) }, all_queries: true
... ^ 
```
Deleting `, all_queries: true` will eliminate the error.

### System configuration
**Rails version**: Rails 7.0.2.2

**Ruby version**: ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

**Comment by mansakondo** [comment]
Hi @john-999 . Scopes are lambdas, so you need to use `->` or `lambda` to define them.
```ruby
default_scope -> { order(created_at: :asc) }, all_queries: true
```

**Comment by john-999** [comment]
Thank you @mansakondo  !

So the documentation is wrong then, at: https://api.rubyonrails.org/classes/ActiveRecord/Scoping/Default/ClassMethods.html#method-i-default_scope

**Comment by mansakondo** [comment]
> Thank you @mansakondo !
> 
> So the documentation is wrong then, at https://api.rubyonrails.org/classes/ActiveRecord/Scoping/Default/ClassMethods.html#method-i-default_scope ?

Nice catch! It seems like we can use the regular blocks if we don't pass `all_queries: true`, but we have to use the lambdas otherwise. Kinda weird... Maybe I'm missing something...

**Comment by eugeneius** [comment]
A block has to come after any other arguments, so to use one with `all_queries: true` you would have to do this:

```ruby
default_scope(all_queries: true) { order(created_at: :asc) }
```

I fixed the documentation in https://github.com/rails/rails/commit/e3fd639fead3c804386a3aa35bd1d6ccdf1cf79c; the difference in how lambdas and blocks are passed is just how Ruby works.
