### ISSUE TITLE
Removing the response body from redirects breaks assert_select

### ISSUE THREAD

**Issue by brenogazzola** [rails/rails#44634]
Original discussion: https://github.com/rails/rails/pull/44632

After https://github.com/rails/rails/pull/44554 removed response body of redirect requests, tests that execute `assert_select` without first doing a `follow_redirect` produce the following error:

```
NoMethodError: undefined method `document' for nil:NilClass
  Nokogiri::XML::NodeSet.new(node.document, [node])
```

While not having the `follow_redirect` is an error (since the `assert_select` is not testing the correct page), the exception is confusing.

I'm opening this issue to keep track of this until we have a PR that fixes the exception.

**Comment by ghiculescu** [comment]
What do you think about https://github.com/rails/rails-dom-testing/pull/97 as a solution?
