### ISSUE TITLE
Rails 7.0.1 migration with belongs_to association converts bigint to integer

### ISSUE THREAD

**Issue by ZilvinasKucinskas** [rails/rails#44645]
### Steps to reproduce

Upgrade existing Rails project to Rails 7.0.1 with existing migration (from active_storage):

```ruby
class CreateActiveStorageVariantRecords < ActiveRecord::Migration[6.0]
  def change
    create_table :active_storage_variant_records do |t|
      t.belongs_to :blob, null: false, index: false
      t.string :variation_digest, null: false

      t.index %i[ blob_id variation_digest ], name: "index_active_storage_variant_records_uniqueness", unique: true
      t.foreign_key :active_storage_blobs, column: :blob_id
    end
  end
end
```

P.S. **With Rails 7.0.0 this issue does not happen!**

### Expected behavior

Running the following:

```bash
bundle exec rake db:drop db:create db:migrate
git diff db/schema.rb
```

No changes should be present.

### Actual behavior

```bash
bundle exec rake db:drop db:create db:migrate
git diff db/schema.rb
```

produces:

```diff
create_table "active_storage_variant_records", force: :cascade do |t|
-    t.bigint "blob_id", null: false
+    t.integer "blob_id", null: false
     t.string "variation_digest", null: false
     t.index ["blob_id", "variation_digest"], name: "index_active_storage_variant_records_uniqueness", unique: true
   end
```

### System configuration

**Rails version**:

7.0.1

**Ruby version**:

3.0.3

Let me know if you need more input into this.

**Comment by ZilvinasKucinskas** [comment]
This might be useful to minimize the scope of the problem:

If I change `ActiveRecord::Migration[6.0]` to `ActiveRecord::Migration[5.2]`, the issue does not happen and running `bundle exec rake db:drop db:create db:migrate` produces no changes in `db/schema.rb`.

**Comment by pixeltrix** [comment]
@ZilvinasKucinskas pretty sure this is a duplicate of #44268

**Comment by ZilvinasKucinskas** [comment]
Thanks, @pixeltrix. I can confirm it is a duplicate. 🙇 

Tested https://github.com/rails/rails/pull/42350 and it seems to fix the backward compatibility issue.
