### ISSUE TITLE
ActiveStorage::Variation (v5.2.6.3)> .validate_arg_string > undefined method .any? for nil:NilClass

### ISSUE THREAD

**Issue by roms182** [rails/rails#44656]
### Steps to reproduce
ActiveStorage::Variation method .validate_arg_string raises an error :
  undefined method `any?' for nil:NilClass

  ```
## ActiveStorage::Variation in activestorage (v5.2.6.3, rbenv 2.7.2) > models > active_storage > variation.rb

def validate_arg_string(argument)
      if UNSUPPORTED_IMAGE_PROCESSING_ARGUMENTS.any? { |bad_arg| argument.to_s.downcase.include?(bad_arg) }; raise UnsupportedImageProcessingArgument end
    end
```

This constant is defined at the top of the class : 

```
## ActiveStorage::Variation in activestorage (v5.2.6.3, rbenv 2.7.2) > models > active_storage > variation.rb

UNSUPPORTED_IMAGE_PROCESSING_ARGUMENTS = ActiveStorage.unsupported_image_processing_arguments
```
ActiveStorage.unsupported_image_processing_arguments is not null when checking its value in console. 
```
$ ActiveStorage.unsupported_image_processing_arguments
=> ["-debug", "-display", "-distribute-cache", "-help", "-path", "-print", "-set", "-verbose", "-version", "-write", "-write-mask"]
```

This one is defined in engine within the initializer

```
## ActiveStorage::Variation in activestorage (v5.2.6.3, rbenv 2.7.2) > models > active_storage > engine.rb
default_unsupported_image_processing_arguments = %w(
      -debug
      -display
      -distribute-cache
      -help
      -path
      -print
      -set
      -verbose
      -version
      -write
      -write-mask
    )

initializer "active_storage.configs" do
      config.after_initialize do |app|
        ActiveStorage.logger     = app.config.active_storage.logger || Rails.logger
        ActiveStorage.queue      = app.config.active_storage.queue
        ActiveStorage.previewers = app.config.active_storage.previewers || []
        ActiveStorage.analyzers  = app.config.active_storage.analyzers || []
        ActiveStorage.paths      = app.config.active_storage.paths || {}

        ActiveStorage.supported_image_processing_methods = app.config.active_storage.supported_image_processing_methods || []
        ActiveStorage.unsupported_image_processing_arguments = app.config.active_storage.unsupported_image_processing_arguments || default_unsupported_image_processing_arguments
        ActiveStorage.variable_content_types = app.config.active_storage.variable_content_types || []
        ActiveStorage.content_types_to_serve_as_binary = app.config.active_storage.content_types_to_serve_as_binary || []
        ActiveStorage.content_types_allowed_inline = app.config.active_storage.content_types_allowed_inline || []
        ActiveStorage.binary_content_type = app.config.active_storage.binary_content_type || "application/octet-stream"
      end
    end
```

### Expected behavior
UNSUPPORTED_IMAGE_PROCESSING_ARGUMENTS should be loaded with the value of ActiveStorage.unsupported_image_processing_arguments, no ?

### Actual behavior
UNSUPPORTED_IMAGE_PROCESSING_ARGUMENTS is nil which raises an error

### System configuration
rails (5.2.6.3)
      activestorage (= 5.2.6.3)
**Ruby version**:
ruby '2.7.2'

**Comment by pixeltrix** [comment]
@roms182 are you selecting individual railties or using `require "rails/all"` ?

**Comment by roms182** [comment]
@pixeltrix yes we require "rails/all" in config > application.rb

**Comment by pixeltrix** [comment]
@roms182 thanks for the info - I think must be a load order issue and trying to narrow down where that could be.

**Comment by mawise** [comment]
I'm running into what seems like the same issue.  For what it's worth it doesn't present locally when using the local disk for storage but does present on deployment when using S3 for storage.

**Comment by pixeltrix** [comment]
@roms182 @mawise @arekk are you somehow loading model code that refers to variations during the initialization phase, e.g. inside a `config/initializer/*.rb` file? The `ActiveStorage.unsupported_image_processing_arguments` value is set during an `after_initialize` block and the only way you can hit the error you're seeing is if it's unset and the `transform` method is called.

**Comment by mawise** [comment]
Nope, but you're welcome to explore my code yourself.  It's possible I've
got a dependency that is doing something funny.

This is the commit where I upgraded to 5.2.6.3, I've since reverted it:
https://github.com/havenweb/haven/tree/f857b1cdc4263ae328bbf1ac66998f7da0538f4e

This is the line that throws the above error:
https://github.com/havenweb/haven/blob/f857b1cdc4263ae328bbf1ac66998f7da0538f4e/app/controllers/images_controller.rb#L12

**Comment by mglenn** [comment]
Getting the same error when creating an image variant in a view. 
```
<% if @lot.image1.attached? %>
  <%= image_tag url_for(@lot.image1.variant(resize: "400x400")), class: "img-rounded" if valid_image?(@lot.image1) %><br>
<% end %>
```

@roms182 's suggestion is working for me. I've scanned the code and can't figure out why `UNSUPPORTED_IMAGE_PROCESSING_ARGUMENTS` isn't being set on line 316. Calling `ActiveStorage.unsupported_image_processing_arguments` from the console returns the default array of arguments.

**Comment by pixeltrix** [comment]
@mawise thanks for the link to your code - using that I've worked out what the problem is now. In Rails 5.2 the `UNSUPPORTED_IMAGE_PROCESSING_ARGUMENTS` constant is defined in `ActiveStorage::Variation` which lives in `app/models` in the Active Storage engine. This gets eager loaded in production which happens before `config.after_initialize` hooks run so the `ActiveStorage.unsupported_image_processing_arguments` isn't set at that point. In Rails 6.0, 6.1 and 7.0 the constant is in a different place that's marked with `autoload` and isn't eager loaded so when it's eventually loaded the hooks have run and the constant is set correctly.

**Comment by roms182** [comment]
@pixeltrix tanks for you support. I found this piece of code in a file added by a team mate :
```
#  app > controllers > active_storage > representations_controller.rb. 

module ActiveStorage
  class RepresentationsController < BaseController
    include ActiveStorage::SetBlob

    def show
      expires_in 1.day, public: true
      variant = @blob.representation(params[:variation_key]).processed
      send_data @blob.service.download(variant.key),
                type: @blob.content_type || DEFAULT_SEND_FILE_TYPE,
                disposition: 'inline'
    end
  end
end
```

**Comment by rafaelfranca** [comment]
@roms182 are you able to try this branch in your application to see if the error is gone? https://github.com/rails/rails/compare/5-2-stable...rm-fix-5-2

**Comment by roms182** [comment]
@rafaelfranca thanks for your help. Is that the correct way to achieve this : 
```
# in gemfile
gem 'rails', '~> 5.2', github: 'rails/rails', branch: 'rm-fix-5-2'
```

**Comment by rafaelfranca** [comment]
yes

**Comment by roms182** [comment]
@rafaelfranca I tried this in production and I confirm this fix the bug I had this morning. Thanks.

**Comment by rafaelfranca** [comment]
Thank you for confirming. I'll release a new version of 5.2 with this fix soon

**Comment by rafaelfranca** [comment]
5.2.7 was released

**Comment by mawise** [comment]
Thank you @pixeltrix and @rafaelfranca !!

**Comment by roms182** [comment]
@pixeltrix @rafaelfranca Thank you for your quick support !
