### ISSUE TITLE
certificate verify failed (unspecified certificate verification error)

### ISSUE THREAD

**Issue by seb-sykio** [rails/rails#44698]
hi
after upgrading from rails 6.1.5 to rails 7.0.2 (ruby 2.7.4)
I got this error in production why sending email :

`W, [2022-03-15T19:16:12.512442 #792956]  WARN -- : [c07b4560-8dcd-4d6e-85f1-71bb17804f8e] exception : SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error)
W, [2022-03-15T19:16:12.512491 #792956]  WARN -- : [c07b4560-8dcd-4d6e-85f1-71bb17804f8e] .rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'
.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
bundle/ruby/2.7.0/gems/net-smtp-0.3.1/lib/net/smtp.rb:673:in `tlsconnect'
bundle/ruby/2.7.0/gems/net-smtp-0.3.1/lib/net/smtp.rb:649:in `do_start'
bundle/ruby/2.7.0/gems/net-smtp-0.3.1/lib/net/smtp.rb:604:in `start'
bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
bundle/ruby/2.7.0/gems/actionmailer-7.0.2.3/lib/action_mailer/base.rb:565:in `block in deliver_mail'
bundle/ruby/2.7.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `block in instrument'
bundle/ruby/2.7.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
bundle/ruby/2.7.0/gems/activesupport-7.0.2.3/lib/active_support/notifications.rb:206:in `instrument'
bundle/ruby/2.7.0/gems/actionmailer-7.0.2.3/lib/action_mailer/base.rb:563:in `deliver_mail'
bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
bundle/ruby/2.7.0/gems/actionmailer-7.0.2.3/lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
bundle/ruby/2.7.0/gems/actionmailer-7.0.2.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
bundle/ruby/2.7.0/gems/actionmailer-7.0.2.3/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
bundle/ruby/2.7.0/gems/devise-4.8.1/lib/devise/models/authenticatable.rb:204:in `send_devise_notification'
bundle/ruby/2.7.0/gems/devise-4.8.1/lib/devise/models/confirmable.rb:121:in `send_confirmation_instructions'
bundle/ruby/2.7.0/gems/devise-4.8.1/lib/devise/models/confirmable.rb:136:in `block in resend_confirmation_instructions'
`
in  production.rb

`  
  config.action_mailer.smtp_settings = {
    address: "localhost",
    port: 25,
    enable_starttls_auto: false,
  }`
  
  i have tried with
  `openssl_verify_mode: 'none'`
  
  but no difference
  with previous version of rails it has always work fine.

can it be linked with gem net-smtp' which since to have change with rails 7 / ruby 3 ?

**Comment by SkipKayhil** [comment]
This sounds like you're being hit with https://github.com/ruby/net-smtp/pull/12 which in in net-smtp >= 0.20.0. https://github.com/mikel/mail/pull/1435 This PR in the mail gem will add support to override the new default but it hasn't been merged/released yet. I _think_ you could try downgrading net-smtp in your Gemfile and it may work

**Comment by seb-sykio** [comment]
thanks. unfortunately net-smtp 0.1 does not work with ruby 3

**Comment by glaszig** [comment]
this hit me as well after going from rails 6 to 7 (on ruby 2.7) which pulls in net-smtp 0.3.1 but the mail gem has not been updated to handle the changes in ruby/net-smtp#9.

what happens is that ruby/net-smtp#9 changed the default for `starttls` to `:auto` from `false` but the mail gem does not explicitly disable starttls if you set it to false. so it'll just go ahead and initiate tls anyway.

i came up with the following patch to add the missing behavior in a compatible way i hope:

```rb
module DisableStarttls
  def build_smtp_session
    super.tap do |smtp|
      unless settings[:enable_starttls_auto]
        if smtp.respond_to?(:disable_starttls)
          smtp.disable_starttls
        end
      end
    end
  end
end

Mail::SMTP.prepend DisableStarttls
```

put that in an initializer file.

**Comment by rafaelfranca** [comment]
Closing since this is not a Rails issue. Thank you
