### ISSUE TITLE
Visit enum value before type cast within ActiveRecord model instance method get unexpected result.

### ISSUE THREAD

**Issue by zw963** [rails/rails#44711]
### Steps to reproduce
create a enum field in User model.

```rb
  enum moment_expires_in_seconds: {
         'last_3_days' => 259200,
         'last_month' => 2592000,
         'last_6_months' => 15552000,
         'all' => 0
       }, _prefix: true
```

# Your reproduction script goes here

Following is a screenshot for make describe more simpler, Following is some context:

1. the breaking point is stop on a instance method in User model, so the self is a User model instance, that is why assert self == User.find(self.id) is pass
2. But `self.moment_expires_in_seconds_before_type_cast` get different result as `user.moment_expires_in_seconds_before_type_cast`

![image](https://user-images.githubusercontent.com/549126/158744077-46cb4038-612a-4a58-8845-cfb5074536ba.png)

### Expected behavior

When visit `moment_expires_in_seconds_before_type_cast` in model instance variable, i expected it return `259200`, as returned value when invoke from `user` instead self.

### Actual behavior

self.moment_expires_in_seconds_before_type_cast # => last_3_days  unexpected result.
self.moment_expires_in_seconds_before_type_cast # => 259200, expected result.

### System configuration
**Rails version**:

6.1.4.4

**Ruby version**:
3.1.0

**Comment by eileencodes** [comment]
Hey @zw963 can you check whether this is present in `main` and 7.0.x? A script that reproduces the failure case in addition to the screenshot will help us debug this as well.

**Comment by hworoshch** [comment]
I confirm this behavior using Ruby 3.0.0 and Rails 7.0.2.3

**Comment by zw963** [comment]
live

**Comment by okk-o** [comment]
live
