### ISSUE TITLE
rails server does not work

### ISSUE THREAD

**Issue by InakiGT** [rails/rails#44721]
### Steps to reproduce

```ruby
rails -v #Rails 7.0.2.3
rails server
```

### Expected behavior

Rails server would works normally

### Actual behavior

In console shows that the pocess was killed
`[2]    9854 killed     rails server`

### System configuration
**Rails version**: Rails 7.0.2.3

**Ruby version**: 2.7.1p83

**Comment by nvasilevski** [comment]
Hey, do you have a bit more context, perhaps some stack trace? 
It doesn't seem to be 100% reproducible on `Ruby 2.7.1` & `Rails 7.0.2.3` so I'm afraid it's going to be hard to help with so little information :(

**Comment by InakiGT** [comment]
This issue happens in all the projects that I make, if I create a new project it happens again
```
rails new test_app
cd test_app && rails s
```
Shows in console
`[2]    10183 killed     rails server`

this also happens with other rails commands like generate or console
`rails console`
Turns
`[2]    10293 killed     rails console`

**Comment by nvasilevski** [comment]
what about `bin/rails server` or `bundle exec rails server`

**Comment by InakiGT** [comment]
Same issue in both
```
[2]    10342 killed     bin/rails server
[2]    10371 killed     bundle exec rails server
```

**Comment by HParker** [comment]
I am not able to reproduce,

```
⋊> ~/code rails new test_app                                                                                                                                   09:59:13
<clip>
⋊> ~/code cd test_app && rails s                                                                                                                               09:59:31
=> Booting Puma
=> Rails 7.0.2.3 application starting in development 
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.6.2 (ruby 3.0.2-p107) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 89640
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
```

Are you able to come up with a script or test app where this issue reproduces on someone else's computer?

**Comment by gmcgibbon** [comment]
You can use a profiler like [rbspy](https://github.com/rbspy/rbspy) to inspect the process and potentially see what the process is doing before it dies, but I would assume it is more likely an issue your environment. Without a way to reproduce the issue, there is nothing we can do.
