### ISSUE TITLE
Incorrect documentation on IntegrationTest header setting

### ISSUE THREAD

**Issue by chaffeqa** [rails/rails#44736]
### Steps to reproduce

- section https://github.com/rails/rails/blob/main/guides/source/testing.md#functional-tests-for-your-controllers explains how the keyword `headers` can be passed to `process` method
- `process` method does not accept that keyword: https://github.com/rails/rails/blob/de53ba56cab69fb9707785a397a59ac4aaee9d6f/actionpack/lib/action_controller/test_case.rb#L474

### Solution options:

- Add support for keyword
- Change rails guide

**Comment by ghiculescu** [comment]
Thanks for the issue. Functional tests are deprecated so i'm not sure we should add support for the keyword, but we should update the guide. Would you like to make a PR?
