### ISSUE TITLE
Missing Association Does Not Raise MissingAttributeError

### ISSUE THREAD

**Issue by Neilshweky** [rails/rails#44738]
### Steps to reproduce

I have found unexpected behavior when trying to reference an association that was not in the "select" projection. Take the following code: 
```
class User < ActiveRecord::Base
  self.table_name = 'user'

  has_one :address
  has_many :homes
end

class Address < ActiveRecord::Base
  self.table_name = 'address'

  belongs_to :user
end

class Home < ActiveRecord::Base
  self.table_name = 'homes'

  belongs_to :user
end

user = User.create!(name: "Sam", age:12)
user.address = Address.new
user.homes = [Home.new]
user.save

u = User.select(:name).first
puts u.name # Sam
puts u.address # nil
puts u.homes # []
puts u.age # MissingAttributeError
```

### Expected behavior

My expected behavior would be:
```
u = User.select(:name).first
> u.name 
Sam 
> u.address
# => raise MissingAttributeError
> u.homes
# => raise MissingAttributeError
> u.age
# => raise MissingAttributeError
```

### Actual behavior
```
u = User.select(:name).first
> u.name 
Sam 
> u.address
# => nil
> u.homes
# => #<ActiveRecord::Associations::CollectionProxy []>
> u.age
# => raise MissingAttributeError
```
For some reason, when referencing associations that were not selected, they return `nil` or `[]`, and they do not raise a MissingAttributeError. Is this working as intended?

### System configuration
**Rails version**: 7.0.2.2

**Ruby version**: 2.7.5

**Comment by tomu123** [comment]
This unexpected behaviour occurs only when I use the [] method to read an attribute from an active record model, the default accessor raises a NoMethodError. According to [the documentation](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods.html#method-i-5B-5D), this behaviour is wrong. 

`irb(main):033:0> v.class.class
=> Class
irb(main):034:0> v.class.ancestors
=> 
[SalesClient(id: integer, company_name: string, contracted_company: string, company_headline: string, company_bio: string, location: string, company_website: string, company_email: string, industry: string, created_at: datetime, updated_at: datetime, logo_uuid: string),
irb(main):035:0> v[:this_method_doesnt_exist]
=> nil`

System configuration
Rails version: 7.0.3.1

Ruby version: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-musl]

**Comment by fesilvajacquier** [comment]
Hey all!
Not an expert here. But I hope this helps.

From what I understand the key words in the [docs](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods.html#method-i-5B-5D) are "**identified attribute**"

> Returns the value of the attribute identified by attr_name after it has been typecast (for example, “2004-12-12” in a date column is cast to a date object, like Date.new(2004, 12, 12)). It raises ActiveModel::MissingAttributeError if the identified attribute is missing.


```ruby
user_with_just_id_selected = User.select(:id).first
# => #<User id: 1>
user_with_just_id_selected["email"]
# ActiveModel::MissingAttributeError: missing attribute: email
# from .../.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activemodel-6.0.4.7/lib/active_model/attribute.rb:221:in `value'
user_with_just_id_selected["non_existing attribute"]
# => nil
user_with_every_attribute = User.first
# => #<User id: 1, email: "super_cool_email@mail.com" ...>
user_with_every_attribute["email"]
# => "super_cool_email@mail.com"
user_with_every_attribute["non_exixting_attribute"]
# => nil
```

Considering this example where we have the `User` model that has the `#email` attribute, we can see that the `ActiveModel::MissingAttributeError` is raised when we try to read an attribute that was not initialized. In this case we are deailing with an `ActiveModel::Attribute::Uninitialized` instance whose `#value` method says:

```ruby
        def value
          if block_given?
            yield name
          end
        end
```
As the `#[]` source code shows, it just calls `#read_attribute` (eventually, this method will fetch the `#value` of the attribute) passing the `attr_name` and a block that would raise the error.

```ruby
# File activerecord/lib/active_record/attribute_methods.rb, line 329
def [](attr_name)
  read_attribute(attr_name) { |n| missing_attribute(n, caller) }
end
```

On the other hand, for the `non_existing_attribute` case, we are dealing with an `ActiveModel::Attribute::Null` instance. This instance is initialized with `value_before_type_cast = nil`, so `#value` (see below) will return `nil`.

```ruby
    def value
      # `defined?` is cheaper than `||=` when we get back falsy values
      @value = type_cast(value_before_type_cast) unless defined?(@value)
      @value
    end
```
