### ISSUE TITLE
params.to_yaml fails with TypeError (can't dump anonymous module ) in Rails 7

### ISSUE THREAD

**Issue by RogerE** [rails/rails#44743]
After upgrading to Rails 7 doing params.to_yaml in a controller fails with TypeError (can't dump anonymous module ). Works in Rails 6.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    post "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    params_yaml = params.to_yaml
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    post '/', params: { custom: "a", item_number: "123" }
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior
Submited parameters should be returned as YAML

### Actual behavior
Request fails with TypeError (can't dump anonymous module ) 

### System configuration
**Rails version**: example code is with branch: "main" (Affects all version from 7.0.0 and up as far as I can tell)

**Ruby version**: 2.7.5

**Comment by SkipKayhil** [comment]
It looks like 6be9c498bccd8dbc99b4b451841fcf73c7061d48 is causing this. Dumping `params` now includes `@logging_context`, which is failing because it includes the request object

**Comment by RogerE** [comment]
Thanks for the fix @SkipKayhil , appreciated!
