### ISSUE TITLE
Default scope erroneously sets attributes

### ISSUE THREAD

**Issue by dchacke** [rails/rails#44741]
### Steps to reproduce

1. Assuming you have a boolean attribute `:foo` on a model, add the following `default_scope` to that model:

```ruby
default_scope -> { where(foo: true) }
```

2. Observe that new instances of the affected model have `:foo` set to `true` by default:

```ruby
Model.new
=> #<Model id: nil, foo: true>
```

### Expected behavior

```ruby
Model.new
=> #<Model id: nil, foo: false>
                         ^
```

### Actual behavior

```ruby
Model.new
=> #<Model id: nil, foo: true>
                         ^
```

### System configuration
**Rails version**: 6.1.1
**Ruby version**: 2.6.5

### Notes

I do not see why a `default_scope` using a conditional for retrieving subsets from a db table should mutate an in-memory model instance in any way. The observed behavior leads to a particularly egregious inconsistency when the db schema is set to `default: false` for the affected attribute.

**Comment by dchacke** [comment]
FYI, I ran into another issue using a lambda for the default scope. When I changed that to a block, my hope was that the issue above would go away, too. That was not the case.

**Comment by SkipKayhil** [comment]
Can confirm this behavior, here's a bug template if anyone is able to dive into this before I get a chance to:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
    t.boolean :flagged, default: false
  end
end

class Comment < ActiveRecord::Base
  # uncommenting makes assertion fail
  # default_scope -> { where(flagged: true) }
end

class BugTest < Minitest::Test
  def test_default_scope
    assert_equal false, Comment.new.flagged
  end
end
```

**Comment by SkipKayhil** [comment]
Actually this is specifically documented so I think this behavior is intended: https://api.rubyonrails.org/classes/ActiveRecord/Scoping/Default/ClassMethods.html#method-i-default_scope

> The default_scope is also applied while creating/building a record. It is not applied while updating or deleting a record.
```ruby
Article.new.published    # => true
Article.create.published # => true
```

**Comment by dchacke** [comment]
It had occurred to me that this might be intentional, but I fail to see why/what good it does. It leads to the inconsistency with default values I've mentioned. It's also meaningless when having a default scope that does not mutate, e.g. if it merely sorts.

**Comment by matthewd** [comment]
As noted, this is expected and documented behaviour; it's an extension of

```ruby
Article.where(published: true).new.published # => true
```

i.e., all active scopes that filter an attribute to a single value also correspondingly set that value on newly-created records when that scope is.. in scope.

Notably, doing otherwise here would create a no-less-egregious inconsistency of its own:

```ruby
class Article < ApplicationRecord
  default_scope -> { where(published: true) }
end

Article.create! # => #<Article published: false>
Article.first # => nil
```

**Comment by dchacke** [comment]
Matthew, what you describe is not an inconsistency but expected. If you create a record that doesn't meet your default scope it won't be returned. There can be use cases where this is necessary: picture having an `approved` field and *wanting* newly created records not to be returned in queries unless they're explicitly (and perhaps even manually) set to `true`. Like when a human reviews and approves comments on a blog and the comments should stay hidden until approved. Isn't `unscoped` just the thing for the case you describe?

In addition, why somebody would write `Article.where(published: true).new` when they could write `Article.new(published: true)` is unclear to me, even if it were chained through an association stored in a variable. But if necessary, why not keep the strange behavior just for cases like `Article.where(published: true).new`? At least there, the boolean is explicitly and purposefully set.

The behavior may be documented but I still find it strange. Is there another reason to keep it? If not, I think you're wrong to close this issue.

**Comment by matthewd** [comment]
Dennis, we're not going to change 15+ year old established behaviour because you find it strange, and open issues are for issues, not litigating the merits of intended behaviour.

A default scope applies everywhere by default. `unscoped` is just the thing for the case you describe.

**Comment by dchacke** [comment]
I could use `Model.unscoped.new` as a workaround, yes, but `where` clauses should be for reading only, not mutating. Semantically, it makes no sense to use read instructions for mutations. Not to mention that it can be dangerous.

It isn't true that a "default scope applies everywhere by default". From https://guides.rubyonrails.org/active_record_querying.html#applying-a-default-scope: "It is not applied while updating a record."

You seem to be saying, in effect, that you want to keep things the way they are because they've always been that way. That's not valid reasoning. Intended or not, if some behavior, upon further reflection, has no merit, isn't that cause for change?

**Comment by uxxman** [comment]
@dchacke The scope doesn't state that its only meant for querying and where clauses. It makes sure that the model object is scoped to the attributes and values provided whether you are querying or building/creating new objects. 

```ruby
Post.published          # [<Post: published: true>]
Post.published.new  # <Post: published: true>
```

The name DEFAULT_scope clearly justifies that.

**Comment by matthewd** [comment]
> It isn't true that a "default scope applies everywhere by default".

That was in the context of your suggestion that `Article.new` (with the `where(published: true)` default scope defined) and `Article.where(published: true).new` be made to behave differently. A default scope applies everywhere in the sense that `Article` and `Article.where(published: true)` are interchangeable.

(If you still just don't see any reason that `some_scoped_relation.new` should work and carry along its filtering attributes, that's fine, though I'm surprised you've never used e.g. `my_post.comments.new`.)

> You seem to be saying, in effect, that you want to keep things the way they are because they've always been that way.

Yes, I am.

> That's not valid reasoning.

Yes, it is. Compatibility with existing applications, which rely on the existing behaviour, is a critical consideration for any potential change. We don't exist in a vacuum, and are not designing an API from scratch.

That you are personally unconvinced the existing design has merit is not a significant factor in my consideration of whether this should be changed.

**Comment by dchacke** [comment]
@uxxman 

> The scope doesn't state that its only meant for querying and where clauses.

I understand that, and I did not claim that it does. But where clauses do end up being used for mutation when they should only be used for reading. It'd be different if a scope were declared using just a hash or something, as in

```ruby
default_scope published: true
```

In that case, using the hash for where clauses *and* for building/creating new objects would seem reasonable.

**Comment by dchacke** [comment]
@matthewd Your example `my_post.comments.new` convinced me I was wrong. (You have said you don't care much whether I'm convinced but I wanted to bring this to a conclusion.)
