### ISSUE TITLE
`Range#overlaps?` error when comparing beginless ranges

### ISSUE THREAD

**Issue by donny741** [rails/rails#44755]
### Steps to reproduce

```ruby
(1..5).overlaps?(..10)
(..5).overlaps?(..10)
```

### Expected behavior
It returns `true`

### Actual behavior
It raises a `RangeError: cannot get the first element of beginless range`

### System configuration
**Rails version**: 7

**Ruby version**: 3.0.2

**Comment by ghiculescu** [comment]
Thanks for the report, do you want to try and make a PR with a fix? It would be in here https://github.com/rails/rails/blob/main/activesupport/lib/active_support/core_ext/range/overlaps.rb and tests here https://github.com/rails/rails/blob/main/activesupport/test/core_ext/range_ext_test.rb#L52

**Comment by donny741** [comment]
Sure!

**Comment by jonathanhefner** [comment]
Fixed by #44755.
