### ISSUE TITLE
why svg image is not treated as web image content types in active storage configuration?

### ISSUE THREAD

**Issue by bijay3030** [rails/rails#44768]
when uploading svg image to active storage via digital ocean s3 service  it gives downloadable link which is not render in browser  but we need to render it in browser

### Steps to reproduce
svg image are included in active storage configuration as 
config.active_storage.content_types_to_serve_as_binary = %w(
      text/html
      text/javascript
      image/svg+xml
      application/postscript
      application/x-shockwave-flash
      text/xml
      application/xml
      application/xhtml+xml
      application/mathml+xml
      text/cache-manifest
    )
but why svg image is not included in 
 config.active_storage.web_image_content_types = %w(
      image/png
      image/jpeg
      image/jpg
      image/gif
    )

### Expected behavior
 config.active_storage.web_image_content_types = %w(
      image/png
      image/jpeg
      image/jpg
      image/gif
      image/svg+xml
    )

    config.active_storage.content_types_to_serve_as_binary = %w(
      text/html
      text/javascript
      application/postscript
      application/x-shockwave-flash
      text/xml
      application/xml
      application/xhtml+xml
      application/mathml+xml
      text/cache-manifest
    )

### Actual behavior
config.active_storage.web_image_content_types = %w(
      image/png
      image/jpeg
      image/jpg
      image/gif
    )

    config.active_storage.content_types_to_serve_as_binary = %w(
      text/html
      text/javascript
      image/svg+xml
      application/postscript
      application/x-shockwave-flash
      text/xml
      application/xml
      application/xhtml+xml
      application/mathml+xml
      text/cache-manifest
    )

### System configuration
**Rails version**: 6.1.4

**Ruby version**:3.0.2

**Comment by hfpp2012copy** [comment]
see this: [svg](https://github.com/rails/rails/issues/34665)

you can upload you svg to storage server, and show it like this:

```
  if blob.content_type == "image/svg+xml"
    begin
      URI.parse(blob.url).open.read.html_safe
    rescue StandardError
      ""
    end
  else
    image_tag current_avatar.variant(resize_to_fill: [size, size]), **options
  end
```

**Comment by gmcgibbon** [comment]
Thanks for the issue. As @hfpp2012copy mentioned,  https://github.com/rails/rails/issues/34665#issuecomment-445888009 goes into detail on why we do this. SVG+XML makes your app more vulnerable to XSS. You can change configuration to enable this, but for security sake, it is served as binary instead by default.
