### ISSUE TITLE
Some strings passed to "where.not(numeric_attribute: x)" lead to unhelpful Postgres null equality comparison 

### ISSUE THREAD

**Issue by patrick-gleeson** [rails/rails#44778]
### Steps to reproduce
Have a Postgres-backed ActiveRecord setup, with a User model that has a numeric 'id' attribute. In most cases, `User.where.not(id: x)` is handled very sensibly:

Case A: `puts User.where.not(id: 1).to_sql` outputs: `SELECT "users".* FROM "users" WHERE "users"."id" != 1`, which makes total sense

Case B: `puts User.where.not(id: nil).to_sql` outputs: `SELECT "users".* FROM "users" WHERE "users"."id" IS NOT NULL`, which also makes total sense

Case C:`puts User.where.not(id: []).to_sql` outputs `SELECT "users".* FROM "users" WHERE 1=1` which makes sense when you think about it. _All_ ids are not equal to `[]`, so any `WHERE` clause that always returns true is equivalent

Here's where it goes a bit weird and unhelpful:

### Expected behavior
```ruby
puts User.where.not(id: 'foo').to_sql
# I'd have thought this should output "SELECT "users".* FROM "users" WHERE 1=1" to match case C above
```

### Actual behavior
```ruby
puts User.where.not(id: 'foo').to_sql
# outputs:  SELECT "users".* FROM "users" WHERE "users"."id" != NULL
```

This is both weird in that it's not a literal translation to SQL of the slightly absurd statement I am making in Ruby, and unhelpful in that, unlike the empty array comparison, it doesn't say, in effect: "no users have 'foo' as their ID, so all users do _not_ have 'foo' as their ID". Instead, it uses "!= NULL", which always evaluates to false, so this query can never return any records.

It's particularly unhelpful because you _can_ pass not only `"1"` as an interpretable ID value, but also `"1foo"` or `"0foo"` (although not `"foo1"`), so there are plenty of instances where using a string is considered reasonable. 

### System configuration
**Rails version**: 6.1.4.6

**Ruby version**: 2.7.5

**Comment by matthewd** [comment]
Is this a regression from a previous version? (I'm guessing not, given it's 6.1, but still worth asking)

> you can pass not only "1" as an interpretable ID value, but also "1foo" or "0foo" (although not "foo1"), so there are plenty of instances where using a string is considered reasonable.

FWIW, that is _why_ it happens: the supplied string goes through our type-casting, so that "1foo" will match (or, here, anti-match) `1`... and so the numberless string gets lost into a generic cast+inequality, without any of the specialized "this is known impossible" handling seen in the `[]` case.

Barring a regression, I think I'd hesitate to call this a bug per se, but I'd certainly be open to reasonable attempts to make it behave better. (Where reasonableness is a measure of the amount of special-case code required.)

**Comment by patrick-gleeson** [comment]
I have no reason to believe this is a regression, and agree, it's not necessarily a bug, because I'm not sure there's a 'correct' behaviour here. It just stands out to me as a (blessedly rare) case where Rails could do more to save me from myself. 

Possible more consistent behaviours:

- Any time a SQL string ends up containing an equality comparison with NULL, swap out for "IS"/"IS NOT" (this logic is implemented in places, but seems to be _before_ type casting is done normally, which is why it's missed here?)
- Substitute a better integer equivalent of 'foo' than NULL. Er... `"foo".to_i` is zero, but that's probably no improvement...
- Obey the request literally, and allow postgres to error out when queries
- Raise an error when a string cannot be type cast to an integer sensibly?
