### ISSUE TITLE
toastify-js not working hotwire/stimulus

### ISSUE THREAD

**Issue by fabriciobonjorno** [rails/rails#44775]
### Steps to reproduce

Install Toastfy
```
yarn add toastify-js
```
add in to application.js
```
import Toastify from "toastify-js"

  document.addEventListener('DOMContentLoaded', () => {
    const backgroundColors = {
      alert: "#f44336",
      error: "#f39c12",
      notice: "#009688"
    }
    JSON.parse(document.body.dataset.flashMessages).forEach(flashMessage => {
      const [type, message] = flashMessage;
      Toastify(
        {
          text: message,
          duration: 3000,
          close: true,
          backgroundColor: backgroundColors[type],
          stopOnFocus: true
        }
      ).showToast();
    });
  });
```
add in to css file
```
@import "toastify-js/src/toastify";
```
add in to application.html.erb (views/layout)
```
<body data-flash-messages="<%= JSON.dump(flash.to_a) %>" >
```

### Expected behavior

Expected that renders the alert or confirmation message. In devise message it's working
[Doc Toastfy](https://apvarun.github.io/toastify-js/)
![ok](https://user-images.githubusercontent.com/28460996/160262999-c5bc2930-f79f-4f58-a4a3-b66da9723806.png)

### Actual behavior
It renders the message but does not open the alarm popup.
Result:
![toastfy](https://user-images.githubusercontent.com/28460996/160262823-5f0ff0c3-0913-4964-b122-5dc646226412.png)

### System configuration
**Rails version**:
7.0.2.3
**Ruby version**:
3.1.1

**Comment by TerloevIslam** [comment]
Hey @fabriciobonjorno how did you solve the problem? I have the same 1 to 1

**Comment by fabriciobonjorno** [comment]
Hey @TerloevIslam I made this article about it
https://medium.com/p/0ff5e455ec80
