### ISSUE TITLE
Cache::Entry encoding changes in Rails 7 are leading to some confusing behaviour with the increment call

### ISSUE THREAD

**Issue by andrejbl** [rails/rails#44787]
### Steps to reproduce

With https://github.com/rails/rails/pull/42025 and related changes, there is some confusing side-impact to how the `increment` method now works in combination with the `read` method. Prior to this change, in Rails 6.1 one could do the following:

```ruby
Rails.cache.write("counter", 1, raw: true)
=> 2723551874652307456
Rails.cache.increment("counter")
=> 2
Rails.cache.read("counter")
=> "2"
```

In Rails 7 the `Rails.cache.read("counter")` will silently fail and return `nil` unless `raw: true` option is set making the behaviour indistinguishable from a cache miss, and there was no deprecation warning to indicate that this can happen - large codebases are particularly vulnerable to this change in behaviour. 

In addition, the `Rails.cache.read("counter", raw: true)` is returning a `String` even though the read of a raw counter value is asked for and one should expect an integer. I assume this is due to the counter value being converted to string on write https://github.com/rails/rails/commit/4b63c2700ffc5c646af0e728d4ec2fcb6770671b#diff-9378046eebcf3b1b838fdf05602c2711eb78c6f57123fb61760d78fadbcf74ac. Should this behaviour be deprecated? I do not know if `memcache-client` is still used in the wild, and afaik Dalli is the default memcached client since Rails 6.1.

### Expected behavior
```ruby
Rails.cache.write("counter", 1, raw: true)
=> 2723551874652307456
Rails.cache.increment("counter")
=> 2
Rails.cache.read("counter") # at least with a deprecation warning raised, or perhaps an exception that the value cannot be decoded
=> 2
```

### System configuration
**Rails version**:
7.0.2

**Ruby version**:
2.7.5

**Comment by nvasilevski** [comment]
Just wanted to link relevant issue - https://github.com/rails/rails/issues/43492#issuecomment-947384751
It seems like the `Rails 7` behaviour is expected, according to the comment, but I would agree that perhaps upgrade guide or changelog could benefit from explicitly pointing this out
