### ISSUE TITLE
Incorrect `foreign_key` in associations in models with namespaces (with load_defaults(7.0) only)

### ISSUE THREAD

**Issue by aglushkov** [rails/rails#44780]
Now foreign key does not include namespace part.

Not sure this is a bug, because foreign keys in associations can be specified manually. But there are no notices in UPGRADING guide about such possible issue.

Can be fixed manually by adding correct foreign keys
Can be fixed by using config.load_defaults(6.0)

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record/railtie"
require "logger"

class Application < Rails::Application
  config.load_defaults 7.0 #------------ WORKS with 6.0 ------------
end

ENV["DATABASE_URL"] = "sqlite3::memory:"
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :community_categories, force: true do |t|
  end

  create_table :community_topics, force: true do |t|
    t.belongs_to :community_category
  end
end

module Community
  class Topic < ActiveRecord::Base
    self.table_name = :community_topics

    belongs_to :community_category,
      class_name: 'Community::Category',
      inverse_of: :community_topics
      # foreign_key: :community_category_id # correct foreign key
  end

  class Category < ActiveRecord::Base
    self.table_name = :community_categories

    has_many :community_topics,
      class_name: 'Community::Topic',
      inverse_of: :community_category,
      dependent: :restrict_with_exception
      # foreign_key: :community_category_id # correct foreign key
  end
end

community_category = Community::Category.new
topic = Community::Topic.create!(community_category: community_category)
```

### Expected behavior
Record must be created without error

### Actual behavior
Error: can't write unknown attribute `category_id` (ActiveModel::MissingAttributeError)

### System configuration
**Rails version**: Rails 7.0.2.3

**Ruby version**: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

**Comment by gmcgibbon** [comment]
Trying to query `community_category.community_topics` you'll find that it doesn't work. Even with has_many_inversing off, the expected foreign key is `community_topics.category_id`. Also, considering the behaviour of the String inflector (eg. `"A::B".foreign_key # => "b_id"`), the code is wrong here. Has many inversing just catches the bug sooner. Expecting foreign keys to be namespaced is fine, but you'll need to specify them. Thanks for the issue!
