### ISSUE TITLE
NoMethodError: undefined method `attribute?'

### ISSUE THREAD

**Issue by artemave** [rails/rails#44791]
### Steps to reproduce

1. In an empty folder

```sh
mkdir fixtures
```

2. Create `fixtures/foos.yml`:

```yml
one:
  awesome: true
```

3. Create `bug.rb`:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", '~> 7.0.2'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"
require 'rails/test_help'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :foos, force: true do |t|
    t.boolean :awesome
  end
end

class Foo < ActiveRecord::Base
end

class BugTest < ActiveSupport::TestCase
  self.fixture_path = File.expand_path("../fixtures", __FILE__)
  fixtures :foos

  def test_attribute_bug
    foos(:one)

    bar = Class.new do
      include ActiveModel::Attributes

      attribute :awesome?, :boolean
    end

    assert_nil bar.new.awesome?
  end
end
```

4. Run:

```
    ruby bug.rb
```

### Expected behavior

Test is passing.

### Actual behavior

```
Error:
BugTest#test_attribute_bug:
NoMethodError: undefined method `attribute?' for #<#<Class:0x0000560ab1c1c098>:0x0000560ab1d34b60>
Did you mean?  attribute
               attribute=
               attributes
               attributes=
    /home/artem/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activemodel-7.0.2.3/lib/active_model/attribute_methods.rb:458:in `method_missing'
    /home/artem/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activemodel-7.0.2.3/lib/active_model/attribute_methods.rb:277:in `awesome?'
    bug.rb:46:in `test_attribute_bug'
```

**Note**: commenting out `foos(:one)` makes the problem go away.

### System configuration
**Rails version**: 7.0.2, Current main (as of 888ea75df13d9cb0320b9410b0905eb910f8e26f)

**Ruby version**: 2.7.5

**Comment by artemave** [comment]
So it looks like the problem lies in the method definition cache:

https://github.com/rails/rails/blob/de53ba56cab69fb9707785a397a59ac4aaee9d6f/activesupport/lib/active_support/code_generator.rb#L14-L23

**How does it apply to the errors above**:

The first definition of `awesome?` wins. Whether it's defined by ActiveRecord (original test case) or by the `attribute :awesome?` ([this test case](#issuecomment-1085865292)).

This probably works most of the time, but in this case the definitions are subtly different. ActiveRecord generates one like this:

```ruby
self.attribute?("awesome")
```

Where's ActiveModel generates this one:

```ruby
self.attribute("awesome?", *args)"
```

Those aren't interchangeable.

**Comment by skipkayhil** [comment]
I agree, it looks like that PR fixed this. The bug report is now passing on `7-0-stable` and `main`
