### ISSUE TITLE
Easy XSS with Array#join and html_safe ActiveSupport::SafeBuffer

### ISSUE THREAD

**Issue by mildred** [rails/rails#44804]
### Steps to reproduce

It is too easy to introduce XSS security issues when using `Array#join` to concatenate both unsafe `String` and safe `ActiveSupport::SafeBuffer`. Today I found a bug in a library that I was using, the code looked like this:

```ruby
    def pre_render
      [content_tag(:i, '', html_options), label].compact.join(' ').html_safe
    end
```

Here, the problem is that `content_tag(:i, '', html_options)` is a safe string while `label` is unsafe. using `Array#join` instead of `+` and `<<` operators is removing the benefit of using html_safe as all strings are joined together in an unsafe manner

The correct way to write the above code would have been:

```ruby
    def pre_render
      (content_tag(:i, '', html_options) + ' ' + label).html_safe
    end
```

Where the last `.html_safe` is actually optional.

A suggestion would be to change the `Array#join` method to account for html_safe strings. The following code does the trick:

```ruby
module SecurityArray
  def join(separator = "")
    if any? { |i| i.class == ActiveSupport::SafeBuffer }
      reduce(nil) { |buf, x| (buf ? (buf << separator) : "".html_safe) << x }
    else
      super(separator)
    end
  end
end

Array.class_eval do
  prepend SecurityArray
end
```

### Expected behavior

```
 :002 > ["<img alt=safe>".html_safe, "<img/src/onerror=foo()>"].join(" ")
 => "<img alt=safe> &lt;img/src/onerror=foo()&gt;" 
```

### Actual behavior

```
 :002 > ["<img alt=safe>".html_safe, "<img/src/onerror=foo()>"].join(" ")
 => "<img alt=safe> <img/src/onerror=foo()>" 
```

### System configuration
**Rails version**: 6.1.4.7

**Ruby version**:  3.1.0

**Comment by fschwahn** [comment]
> The correct way to write the above code would have been:

The more straightforward alternative would be

```ruby
    def pre_render
      safe_join([content_tag(:i, '', html_options), label].compact, ' ')
    end
```

Overwriting Array in such a way seems like an extreme measure.

**Comment by gmcgibbon** [comment]
Thanks for the issue, but @fschwahn is correct, the method you are looking for is [`safe_join`](https://api.rubyonrails.org/classes/ActionView/Helpers/OutputSafetyHelper.html#method-i-safe_join). Patching a core class for the sake of Action View is solving the problem at the wrong end.
