### ISSUE TITLE
Hash.deep_merge should use deep_dup?

### ISSUE THREAD

**Issue by perryn** [rails/rails#44802]
Just tracked down a very confusing bug to what I humbly submit is 'surprising' behaviour of `Hash.deep_merge`.

The surprising aspects are 
      1) under some circumstances changes to the returned hash will mutate the original hash 
      2) It provides a mechanism to silently mutate a frozen constant hash

Perhaps the implementation should use `deep_dup` rather than `dup`?

### Steps to reproduce
```ruby
DEFAULTS = { 
    "section_one" => { "foo" => false, "bar" => false},
    "section_two" => { "foo" => false, "bar" => false},
}.freeze
overidden = DEFAULTS.deep_merge({"section_one" => { "foo" => true}})
overidden["section_one"]["bar"] = true
overidden["section_two"]["bar"] = true
DEFAULTS
```

### Expected behavior
DEFAULTS should be unchanged
`{"section_one"=>{"foo"=>false, "bar"=>false}, "section_two"=>{"foo"=>false, "bar"=>false}}`

### Actual behavior
One of the bar keys in DEFAULTS has been mutated (but only one)
`{"section_one"=>{"foo"=>false, "bar"=>false}, "section_two"=>{"foo"=>false, "bar"=>true}}`

### System configuration
**Rails version**:
6.1.4.6 
**Ruby version**:
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin20]

**Comment by SkipKayhil** [comment]
It looks like this was updated in #41931 to do what you describe but that commit was later reverted. Not sure if any opinions have changed since then but it seems unlikely that this behavior can be changed

**Comment by perryn** [comment]
Hi @rafaelfranca, @casperisfine I see you have previously decided to keep the current behaviour (https://github.com/rails/rails/pull/41946#issuecomment-818814855)

I'm interested in what your thoughts were, if you have the time

**Comment by casperisfine** [comment]
> I'm interested in what your thoughts were

As explained in that comment, we agree it's not ideal, but no better alternative was found.
