### ISSUE TITLE
Rails 7: Can not call `javascript_importmap_tags` from console

### ISSUE THREAD

**Issue by n00bvn** [rails/rails#44809]
### Steps to reproduce
Go to `bin/rails console` and try `helper.javascript_importmap_tags`

### Expected behavior

It should show script tag for importmap, so we don't need to view the source code the see all the mappings.

### Actual behavior

It raised exception `actionpack-7.0.2.3/lib/action_controller/metal/content_security_policy.rb:14:in 'content_security_policy_nonce': undefined method 'content_security_policy_nonce' for nil:NilClass (NoMethodError)`

### System configuration
**Rails version**: 7.0.2.3

**Ruby version**: 3.0.0

**Comment by jacobherrington** [comment]
Hey @n00bvn, I can also hit this error in Rails `7.0.2.3` and Ruby `3.0.2`.

It looks like the exception is raised here:
https://github.com/rails/rails/blob/75e6c0ac5f7c1043178e9c43059fba3c15a9da87/actionpack/lib/action_controller/metal/content_security_policy.rb#L77-L79

Looking at the tests for the `javascript_importmap_tags` method [importmap-rails](https://github.com/rails/importmap-rails/blob/7e77a09a7ec054e71f5572d03728b523b9b7faf4/test/importmap_tags_helper_test.rb) repo, this method is stubbed out.

I honestly don't know if this is the expected behavior or not!

**Comment by SkipKayhil** [comment]
It looks like this will happen when trying to render any javascript tag with a nonce from the console:
```ruby
helper.javascript_tag 'test.js', nonce: true
# => /home/hartley/.cache/asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/content_security_policy.rb:14:in `content_security_policy_nonce': undefined method `content_security_policy_nonce' for nil:NilClass (NoMethodError)

helper.javascript_include_tag 'test.js', nonce: true
# => /home/hartley/.cache/asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/actionpack-7.0.2.3/lib/action_controller/metal/content_security_policy.rb:14:in `content_security_policy_nonce': undefined method `content_security_policy_nonce' for nil:NilClass (NoMethodError)
```

Would accessing the json output from `Rails.application.importmap` be a reasonable workaround?

```ruby
puts Rails.application.importmap.to_json(resolver: helper)
# {
#   "imports": {
#     "application": "/assets/application-37f365cbecf1fa2810a8303f4b6571676fa1f9c56c248528bc14ddb857531b95.js",
#     "@hotwired/turbo-rails": "/assets/turbo.min-96cbf52c71021ba210235aaeec4720012d2c1df7d2dab3770cfa49eea3bb09da.js",
#     "@hotwired/stimulus": "/assets/stimulus.min-900648768bd96f3faeba359cf33c1bd01ca424ca4d2d05f36a5d8345112ae93c.js",
#     "@hotwired/stimulus-loading": "/assets/stimulus-loading-1fc59770fb1654500044afd3f5f6d7d00800e5be36746d55b94a2963a7a228aa.js",
#     "controllers/application": "/assets/controllers/application-368d98631bccbf2349e0d4f8269afb3fe9625118341966de054759d96ea86c7e.js",
#     "controllers/hello_controller": "/assets/controllers/hello_controller-549135e8e7c683a538c3d6d517339ba470fcfb79d62f738a0a089ba41851a554.js",
#     "controllers": "/assets/controllers/index-2db729dddcc5b979110e98de4b6720f83f91a123172e87281d5a58410fc43806.js"
#   }
# }
```

**Comment by rafaelfranca** [comment]
We should check if `request` is set in the `javascript_include_tag` before calling `content_security_policy_nonce`.
