### ISSUE TITLE
Use `nil` in values for `in_order_of`

### ISSUE THREAD

**Issue by Flixt** [rails/rails#44814]
### Steps to reproduce
Using `nil` in the array of values for the `MyModel.in_order_of` query method returns inconsistent (and probably wrong?) results across different databases.

Given the following example:

```ruby
Book.create!(name: "a")
Book.create!(name: "b")
Book.create!(name: "c")
Book.create!(name: nil)

order = ["a", nil, "c", "b"]
assert_equal order, Book.in_order_of(:name, order).pluck(:name)
```

**PostgreSQL& SQLite3**
```
# Expected: [nil, "a", "c", "b"]
# Actual: ["a", "c", "b"]
```

**MySQL**

```ruby
Unsupported argument type: String. Construct an Arel node instead
```

The other test in the executable example below also raises an exception for MySQL:
```ruby
Unsupported argument type: NilClass. Construct an Arel node instead.
```

I found this originally coming from the Postgres world, as we had an exact fit for the use of `in_order_of` in our code base (built our case statement for ordering before Rails 7). But the tests went red after switching over to `in_order_of`. So I investigated it a bit.

Here is what I found:

```sql
SELECT NULL = NULL -- > NULL
```

This means that a `case` statement like

```
...
ORDER BY CASE my_column
WHEN NULL THEN 0
WHEN 'value' THEN 1
...
```

actually never uses the `NULL` (NULL is not true) case. On our side we were able to work around it, by using `COALESCE` in the case part of the condition.

```
...
ORDER BY CASE COALESCE(my_column, 'NULL_VALUE')
WHEN 'NULL_VALUE' THEN 0
WHEN 'value' THEN 1
...
```

I tried to come up with a patch that would introduce the use of COALESCE for the `ActiveRecord::ConnectionAdapters::AbstractAdapter` and wrote some tests but then fell over several other things:

- Even if the use of `COALESCE` would work, rows matching `nil` will never be part of the result scope, because 
 https://github.com/rails/rails/blob/75e6c0ac5f7c1043178e9c43059fba3c15a9da87/activerecord/lib/active_record/relation/query_methods.rb#L464-L464

will not return any records with the value being `nil`/`NULL` (same reason as above, NULL is not equal to NULL).

- Building a generic version using `COALESCE` was not that easy because of a limitation from Postgres ([here](https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL)):
> The arguments must all be convertible to a common data type, which will be the type of the result

- So I had a look at what MySQL is doing with `NULL` values and found [this](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_field): 
> If all arguments to FIELD() are strings, all arguments are compared as strings. If all arguments are numbers, they are compared as numbers. Otherwise, the arguments are compared as double.
> If str is NULL, the return value is 0 because NULL fails equality comparison with any value. FIELD() is the complement of ELT()

Here is an executable example, that I used to run against SQLite, PostgreSQL and MySQL.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"

  # gem "pg"
  # gem "mysql2", "~> 0.5", github: "brianmario/mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Use for SQLite
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

# Use for Postgresql
# ActiveRecord::Base.establish_connection(
#   adapter: 'postgresql',
#   encoding: 'unicode',
#   host: ENV.fetch("POSTGRES_HOST", "127.0.0.1"),
#   port: ENV.fetch("POSTGRES_PORT", 5432),
#   database: 'rails_dev'
# )

# Use for MySQL
# ActiveRecord::Base.establish_connection(
#   adapter: "mysql2",
#   encoding: "utf8",
#   host: ENV.fetch("POSTGRES_HOST", "127.0.0.1"),
#   port: ENV.fetch("POSTGRES_PORT", 3306),
#   username: "root",
#   database: "rails_dev"
# )

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true do |t|
    t.string :name
    t.integer :last_read
  end
end

class Book < ActiveRecord::Base
  enum last_read: { unread: 0, reading: 2, read: 3, forgotten: nil }
end

class BugTest < Minitest::Test
  def test_in_order_of_with_nil_values
    Book.destroy_all
    Book.create!(name: "a")
    Book.create!(name: "b")
    Book.create!(name: "c")
    Book.create!(name: nil)

    order = ["a", nil, "c", "b"]
    assert_equal order, Book.in_order_of(:name, order).pluck(:name)
  end

  def test_in_order_of_with_nil_values_for_enum
    Book.destroy_all
    Book.create!(last_read: :unread)
    Book.create!(last_read: :reading)
    Book.create!(last_read: :read)
    Book.create!(last_read: :forgotten) # mapped enum value is nil

    order = [Book.last_reads[:forgotten], Book.last_reads[:reading], Book.last_reads[:unread], Book.last_reads[:read]]
    books = Book.in_order_of(:last_read, order)

    assert_equal(order, books.map { |book| Book.last_reads[book.last_read] })
  end
end

```

### Expected behavior
The whole thing puzzled me so hard, I barely know what I would have expected `in_order_of` to return 😄 but here is my try:

- I'd expect the same AR API call with different databases to return the same result, and not some returning one and some raising an error.
-  I'd expect ActiveRecord to order records correctly were I wrote `nil` in the array of values I want to order by

### Actual behavior
- When using Postgres/SQLite `nil` values are ignored.
- When using MySQL and error is raised.

### System configuration
**Rails version**:
7.0, 7.0.2, 75e6c0ac5f7c1043178e9c43059fba3c15a9da87

**Ruby version**:
2.7.2

**Comment by Flixt** [comment]
@kddnewton, as you implemented the original feature, can you probably have look? I'd be happy to try to come up with a fix but, as I said, I'm not sure about what the correct behavior would look like?

I'd be even fine with raising an error if someone tries to use `nil` in the array argument to `in_order_of` and document it properly.

For me it currently looks like the best way would be to also fall back to a case statement for MySQL when the array contains `nil`.

**Comment by kddnewton** [comment]
I think simplest would be to raise an error. If you're purposefully putting `nil` into the list of ordered values, then I think it's fine to say that's beyond the scope of this method and you need to handle the SQL yourself manually.

**Comment by hahmed** [comment]
I wonder if we could do the same thing here as we do with the find method e.g. `User.find 1, nil, 4, 6` https://github.com/rails/rails/blob/51b4370bb371a0f1d0823c57cad3a1557bf1e6fe/activerecord/lib/active_record/relation/finder_methods.rb#L448 ?

**Comment by kddnewton** [comment]
Oof I really don't like that behavior for this method. That would be really surprising. Imagine if you had some kind of category-item setup:

```ruby
class Genre < AR::Base
end

class Book < AR::Base
end
```

and then you try to order by genre:

```ruby
genre1 = Genre.find(1)
genre2 = Genre.find(2)
genre3 = Genre.find(3)
Book.all.in_order_of(:genre_name, [genre1.name, genre2.name, genre3.name])
```

and you think everything is working. But oops `genre2` actually has a `nil` name, but because we automatically compacted it just went away and no one knew.

**Comment by Flixt** [comment]
Yeah I don't think it would be a good idea to just strip the `nil`s here, for ids that is probably fine, because in a sane world an id (in the db) should not be `nil`.

I'm fine with raising if `nil` is passed, but it would be a breaking change, at least for folks using MySQL (`nil`/`NULL` "just works" there).
Another option probably would be not to use the `FIELDS_FOR` method in MySQL at all, but always use a `CASE` statement. Then we would be able to always handle `NULL` specifically.
