### ISSUE TITLE
Rewrite delegate methods in ActionController::Parameters

### ISSUE THREAD

**Issue by tenderlove** [rails/rails#44813]
We need to rewrite [the delegate methods on `ActionController::Parameters`](https://github.com/rails/rails/pull/44812) so that they no longer directly delegate to the underlying hash object.

## Problem

Currently `AC::Parameters` [delegates some methods to the underlying object](https://github.com/rails/rails/pull/44812), and this causes the AC::Params to behave in inconsistent ways.  For example:

```ruby
require "active_support/all"
require "action_controller/metal/strong_parameters"

hash = { "foo" => { "bar" => :baz } }
params = ActionController::Parameters.new(hash)
p params.values
p params.each_value.to_a
```

The `values` method should probably be equivalent to `each_value.to_a`, but the output of this script shows that they are clearly different:

```
$ bundle exec ruby -I activesupport/lib/:actionpack/lib thing.rb
[{"bar"=>:baz}]
[#<ActionController::Parameters {"bar"=>:baz} permitted: false>]
```

## Help Wanted (One possible solution)

We should re-implement each of these delegate methods so that the behavior of AC::Params is consistent.  If `each_value` does a conversion on objects, then `values` should do the same conversion.

As of #23733 and https://github.com/rails/rails/pull/44812, we are not supposed to be directly comparing hashes with AC::Params objects, so we should consider what to do with code like this:

```ruby
require "active_support/all"
require "action_controller/metal/strong_parameters"

hash = { "foo" => { "bar" => :baz } }
params = ActionController::Parameters.new(hash)
p hash.has_value?({ "bar" => :baz })             # true
p params.has_value?({ "bar" => :baz })           # true
```

Should we continue to support it, or?

Anyway, we should start with rewriting `values` as it's clearly a bug, then maybe separate PRs / discussion about the other methods.

**Comment by gmcgibbon** [comment]
Generally I think delegating predicates like `:key?` and `has_key?` to the hash should be safe. We just want to make sure that nested objects are AC::Params when needed, right?

**Comment by tenderlove** [comment]
> Generally I think delegating predicates like `key?` and `has_key?` to the hash should be safe. We just want to make sure that nested objects are casted to AC::Params when needed, right? I guess it depends on what we define as valid input (eg. hash or AC::Params or both).

I'm not 100% sure. A hash can be a key for a hash.  We don't seem to convert that to an AC::Parameters object though:

```ruby
require "active_support/all"
require "action_controller/metal/strong_parameters"

hash = { { "bar" => :baz } => "foo" }
params = ActionController::Parameters.new(hash)
p params.keys.map(&:class)
```

Is there a reason we don't do the conversion on keys?  I assume it's because we don't expect hashes (or arrays) as keys from the query parameters.  If we don't support certain object types as keys, we should probably raise an exception (IMO).

**Comment by stefkin** [comment]
> Is there a reason we don't do the conversion on keys? I assume it's because we don't expect hashes (or arrays) as keys from the query parameters. If we don't support certain object types as keys, we should probably raise an exception (IMO).

The assumption of having strings/symbols as keys is fair and it makes perfect sense to enforce it. 
I created a simple [PR](https://github.com/rails/rails/pull/44844) to test the approach and CI is green.

**Comment by stefkin** [comment]
Removal of equality override is going to make the current behaviour of has_value/value change.
After the flag is disabled result of has_value?(Hash) changes depending on whether the key was read via `#[]` (or other methods calling `convert_hashes_to_parameters` and wrapping the value in AC::Params) or not. This looks like a bug and is quite counter intuitive. 
I tried to address the issue in the PR: https://github.com/rails/rails/pull/44866

**Comment by promulo** [comment]
Hi, assuming all key-based delegations will remain, which ones are there to be removed? [Here](https://github.com/rails/rails/blob/main/actionpack/lib/action_controller/metal/strong_parameters.rb#L220-L221) is how it looks like at the moment.

I guess `#as_json` and `#to_s` are the only applicable ones?

**Comment by gmcgibbon** [comment]
I think all the necessary delegates have been addressed, so I think we can close this.
