### ISSUE TITLE
Feature request: Encryption for Active Storage files

### ISSUE THREAD

**Issue by john-999** [rails/rails#44810]
[Active Record Encryption](https://guides.rubyonrails.org/active_record_encryption.html) does a great job at helping defend _Personally identifiable information_ (PII) and _confidential data_ that is stored **encrypted in the database** against server intrusions.

However, any files "attached" via [Active Storage](https://edgeguides.rubyonrails.org/active_storage_overview.html) are stored **unencrypted in the file system**, and thus remain open to attackers. Thus, it would be great to have these files encrypted as well, via a new Active Storage option `encrypted: true`, like:

```
class User < ApplicationRecord
  has_many_attached :financial_statements, encrypted: true
  has_many_attached :confidential_inventions, encrypted: true
  has_many_attached :sensitive_pictures, encrypted: true
end
```

**Comment by ghiculescu** [comment]
Hi @john-999 👋  thanks for the feedback. We reserve the issue tracker here for bugs; for feature requests or discussions the best place is https://discuss.rubyonrails.org/. Alternatively if you're interested please make a PR and we can discuss over code.
