### ISSUE TITLE
uninitialized constant Rails::Command::Base (NameError)

### ISSUE THREAD

**Issue by sunil-lulla** [rails/rails#44829]
Facing this issue while running `rails c`, have upgraded from version 4 to 6.0.3.6 Rails

Traceback (most recent call last):
	4: from bin/rails:3:in `<main>'
	3: from bin/rails:3:in `require'
	2: from railsApp/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.6/lib/rails/commands/server/server_command.rb:11:in `<top (required)>'
	1: from railsApp/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.6/lib/rails/commands/server/server_command.rb:93:in `<module:Rails>'
railsApp/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.6/lib/rails/commands/server/server_command.rb:94:in `<module:Command>': uninitialized constant Rails::Command::Base (NameError)

### System configuration
**Rails version**: 6.0.3.6

**Ruby version**: 2.6.6

Any inputs on debugging this further.

**Comment by gmcgibbon** [comment]
I would try restarting spring and checking the content in your `bin/rails` script with a fresh Rails 6 app. However, this is likely not a bug and we are not accepting bug fixes for Rails 6 at this time (see [the maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html)). Please use StackOverflow for help / questions. The issues tracker should be for bugs only. Thanks!
