### ISSUE TITLE
Rails 7: find_by_sql binding int to string

### ISSUE THREAD

**Issue by robertochingon** [rails/rails#44853]
I have a ruby on rails Rails 7.0.2.2 webapp (ruby version 3.0.3) with a query to mysql 8.0.18 for macos10.14 on x86_64 database like:

pagIndex = params[:pagIndex].to_i
limitBoats = 20
offset = pagIndex * 20  
values = Array.new  
indexValues = 0

sQuery = "SELECT DISTINCT b.id, ... FROM ... WHERE ... LIMIT ? OFFSET ?"

values.insert(indexValues + 1, limitBoats)
values.insert(indexValues + 2, offset)    
values.shift    
values.insert(0, sQuery)
@result = Entity.find_by_sql(values)
This code is working perfectly and it´s translating to a query like:

SELECT ... LIMIT '20' OFFSET '0';
where limit and offset are strings.

This has been working perfectly for years in my previous ruby 2.4, rails 4 and mysql 5.5. However, after migrating to ruby 3, Rails 7 and mysql 8, I get error in the limit and offset parameters, because mysql is expecting an integer.

If I just remove the '', the query works. How can I get this working with find_by_sql?

I guess I´m missing something as I don´t even find any other issues like this one.

Note: limit and offset are part of a pagination, so they are coming from variables and I cannot just use these values as constant integers.

UPDATE just to debug it easier, if I just create a method with:

@result = Entity.find_by_sql(['select * from entity limit ?', 11])
    logger.debug "Entities=" + @result.inspect
I´m getting this output:

DEBUG -- :   Entity Load (0.5ms)  select * from boats limit '11'
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.5ms | Allocations: 324)

  
ActiveRecord::StatementInvalid (Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''11'' at line 1):
As you can see it´s changing the int to string and mysql 8 complains.

**Comment by Flixt** [comment]
Hi, thanks for reporting the issue.

For further investigation I crafted the executable example to reproduce the error your encounter.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "mysql2", "~> 0.5", github: "brianmario/mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Use for MySQL
ActiveRecord::Base.establish_connection(
  adapter: "mysql2",
  encoding: "utf8",
  host: ENV.fetch("POSTGRES_HOST", "127.0.0.1"),
  port: ENV.fetch("POSTGRES_PORT", 3306),
  username: "root",
  database: "rails_dev"
)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true do |t|
    t.string :name
  end
end

class Book < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_find_by_sql
    Book.destroy_all
    4.times { Book.create! }

    result = Book.find_by_sql(["SELECT * FROM books limit ?", 2])
    assert_equal result.count, 2
  end
end
```

Although as far as I can see, the change in behavior here was intended and is not a bug. It was introduced with 1dc69cab761fbfd46142f70d8ea58a41c6a12c12.

As using `limit` works find I'm not sure if it is something we should/could fix, @byroot?

**Comment by robertochingon** [comment]
Hi, 

    thanks for your response. I´m not sure if I understood your message: "As using limit works find", did you mean fine. 

Not sure if I´m missing something but limit 'string' is not working with mysql 8. So, now limit seems not to be working anymore.

Please let me know if I´m missing anything or should do something different to do this query.

**Comment by robertochingon** [comment]
Hi, 

  I had to downgrade to ruby 2.7.5 and rails 5.2.4 and everything works again as expected. I wonder why to you wonder yourself if this should be fixed. Now you cannot use limit in Mysql 8 with find_by_sql. Unless I´m missing something, I´m afraid this is a bug guys.

**Comment by byroot** [comment]
Please see the discussion in https://github.com/rails/rails/issues/44312, which include some workarounds.

This regression is unfortunate, but is the consequence of a security fix, so reverting is not an option.
