### ISSUE TITLE
Cannot run rails test command

### ISSUE THREAD

**Issue by koorizhizhi** [rails/rails#44851]
Hi, I'm new to Rails and following the rails tutorial book  to build a sample project.
This is what I get when _rails test_ command is used:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/83855880/161915637-605520fb-9904-4b76-bcc5-1062ada1e12e.png">
Can someone tell me why it is raised?
Env:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/83855880/161916199-eb7e9172-9230-407c-ad6b-1e7ea274b347.png">
<img width="227" alt="image" src="https://user-images.githubusercontent.com/83855880/161916262-a2ffc523-1ebe-44fb-b141-39937a7e7d73.png">

Appreciate your help.

**Comment by eileencodes** [comment]
Hey @koorizhizhi it looks like you're getting a segfault from Ruby. Please upgrade to the latest Ruby 2.7 (which is 2.7.5). If you still have the same error we'll need a way to reproduce this. Realistically it's unlikely that a segfault is caused by something in Rails.
