### ISSUE TITLE
ActiveRecord update_all ignoring the subquery from the from method

### ISSUE THREAD

**Issue by layonferreira** [rails/rails#44861]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '~> 7.0.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post2 = Post.create!
    Post.from(Post.where(id: post)).update_all(title: 'a')

    assert_equal 'a', post.reload.title
    assert_equal nil, post2.reload.title
  end
end

```

### Expected behavior

I would expect `Post.from(Post.where(id: post)).update_all(title: 'a')` to only update posts that matches the records returned by `Post.from(Post.where(id: post))`
### Actual behavior
It ignores the subquery and updates all posts
### System configuration
**Rails version**:
7.x and 6.x
**Ruby version**:
2.7.3

**Comment by nvasilevski** [comment]
I think the issue is most likely in a slightly different place
`Post.from(Post.where(id: post))` relation doesn't seem to be built/evaluated correctly? 
So any method we call on this relation would be broken in some way
So I believe we should be looking into the `.from` behaviour as the root cause

```ruby
(byebug) Post.from(Post.where(id: post)).to_a
D, [2022-04-12T15:54:51.108040 #8404] DEBUG -- :   Post Load (0.4ms)  SELECT "posts".* FROM (SELECT "posts".* FROM "posts" WHERE "posts"."id" = ?) subquery  [["id", 1]]
*** ActiveRecord::StatementInvalid Exception: SQLite3::SQLException: no such table: posts
```

**Comment by fatkodima** [comment]
> So I believe we should be looking into the .from behaviour as the root cause

There was a PR https://github.com/rails/rails/pull/13344 fixing this, which was reverted.

I'm not sure `update_all` should work with `from`, since `UPDATE ... FROM ...` syntax is [postgres specific](https://www.postgresql.org/docs/current/sql-update.html).
