### ISSUE TITLE
link_to with data-turbo-method="post"

### ISSUE THREAD

**Issue by rctneil** [rails/rails#44863]
### Steps to reproduce
I have a link like below:

        <%= link_to "Tidy Gallery",
            admin_gallery_tidy_path,
            "am-button": '',
            data: {
                turbo_method: :delete
            }
        %>

### Expected behavior
Should submit a POST request to the `admin_gallery_tidy_path`

### Actual behavior
A GET request is made to the `admin_gallery_tidy_path` instead

I have tried suggestions from other issues. Tried reinstalling Stimulus and Turbo. If I switch to `button_to`, it works but I need a `link_to`.

### System configuration
**Rails version**: 7.0.2.3

**Ruby version**: 3.0.3

**Comment by ghiculescu** [comment]
Could you share what the HTML that gets output looks like? Does it look like this https://turbo.hotwired.dev/handbook/drive#performing-visits-with-a-different-method

**Comment by DStringer18** [comment]
I've got the same issue. 

My code is like so:
`<%= link_to "Archive", archive_blog_path(@blog), data: {turbo_method: "post"} %>`
HTML output looks like this:
`<a data-turbo-method="post" href="/blogs/1/archive">Archive</a>`
and clicking on it still creates a get request:
```
Started GET "/blogs/1/archive" for 127.0.0.1 at 2022-07-26 11:13:34 +0200
  
ActionController::RoutingError (No route matches [GET] "/blogs/1/archive"):
```
