### ISSUE TITLE
Database connections opened in routes not closed

### ISSUE THREAD

**Issue by kuahyeow** [rails/rails#44875]
## Problem

When using multiple database connections, and opening a connection in `config/routes.rb`, the `db:test:prepare` task is broken due to not closing all connections before trying to drop the database.

GitLab migrated to using multiple databases. Running tests sometimes fails when Rails reloads the test database (`db:test:prepare`) with ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR: database "gitlabhq_test_ci" is being accessed by other users`. See https://gitlab.com/gitlab-org/gitlab/-/issues/356656

We are  currently running on Rails 6.1.4.7, and still autoload in initializers. To exclude GitLab specific code, I have made a sample reproduction app (see below)

### Detailed investigation

1. In an `after_initialize`, Rails closes all connections opened during boot in [`active_record.clear_active_connections`](https://github.com/rails/rails/blob/fdf840f69a2e33d78a9d40b91d9b7fddb76711e9/activerecord/lib/active_record/railtie.rb#L308).
2. However, there is a [`set_routes_reloader_hook`](https://github.com/rails/rails/blob/fdf840f69a2e33d78a9d40b91d9b7fddb76711e9/railties/lib/rails/application/finisher.rb#L149) which runs after `after_initialize`. Which means database connections opened in routes do not get closed.
3. This affects rake tasks like `db:test:prepare` as these open connections prevent the test database from being dropped.
4. However, this only affects multiple databases because by accident, Rails removes the previous connection_pool owned by `ActiveRecord::Base`. Follow [`establish_master_connection`](https://github.com/rails/rails/blob/b2669d7361fe43e1b1d5ce2add3cb63c9061b761/activerecord/lib/active_record/tasks/postgresql_database_tasks.rb#L31). Removing the connection_pool closes the database connection

### Steps to reproduce

1. Check out the reproduction rails app in https://gitlab.com/tkuah/test_prepare_multi
1. Run `RAILS_ENV=test be rails db:test:prepare`. Observe the error.
1. If you comment out the `TempAnimalsRecord.current_database` in `config/routes.rb`, the error does not happen.

### Expected behavior

The rake test drops, and re-creates the test databases

### Actual behavior

A `PG::ObjectInUse` error occurs:

```
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  database "test_prepare_multi_test_animals" is being accessed by other users
DETAIL:  There is 1 other session using the database.


Caused by:
PG::ObjectInUse: ERROR:  database "test_prepare_multi_test_animals" is being accessed by other users
DETAIL:  There is 1 other session using the database.

Tasks: TOP => db:test:load => db:test:purge
(See full trace by running task with --trace)
```

### System configuration
**Rails version**: `Rails 7.0.2.3`

**Ruby version**: `ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin21]`

**Comment by eileencodes** [comment]
Hi @kuahyeow - can you help me understand your use case? Connections are not designed to be used or opened in the routes file.

**Comment by kuahyeow** [comment]
Thanks for the quick response @eileencodes !

> can you help me understand your use case? Connections are not designed to be used or opened in the routes file.

I understand this principle. I did some investigation and it turns out that the open connections are side-effects of loading classes from the routes file. This classes in-turn connects to the database on class load. 

I guess since auto-loading is not allowed anymore in Rails 7, this is probably not worth fixing then.

Potentially Rails can move the `[active_record.clear_active_connections](https://github.com/rails/rails/blob/fdf840f69a2e33d78a9d40b91d9b7fddb76711e9/activerecord/lib/active_record/railtie.rb#L308).` initializer to happen after [set_routes_reloader_hook](https://github.com/rails/rails/blob/fdf840f69a2e33d78a9d40b91d9b7fddb76711e9/railties/lib/rails/application/finisher.rb#L149) ? Not sure. I will try this out in https://gitlab.com/gitlab-org/gitlab/-/merge_requests/85006

> For what it's worth, this is not an accident, it is by design that the pool's are removed when connections are re-established.

Thanks for clarifying this !

**Comment by hahmed** [comment]
fwiw I worked on an app a while back, where the team were flipping (hundred or so) routes to establish the best combination for SEO reasons. They were not comfortable editing the code, so they had a simple form where the routes were added/edited.

I found a way to call a model inside the routes file, I threw up a quick example below as I don't recall the exact code but something like the below works (note: I uncommented the cache block because `RestrictedListConstraint` is defined before the app)

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"
require "action_controller/railtie"
require "rack/test"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :seo_routes, force: true do |t|
    t.string :url
    t.string :description
  end
end

class SeoRoutes < ActiveRecord::Base
end

SeoRoutes.create(url: "/some/category", description: "description")
SeoRoutes.create(url: "/some/other_category", description: "description")
SeoRoutes.create(url: "/some/category/here", description: "description")
SeoRoutes.create(url: "/what/category", description: "description")
SeoRoutes.create(url: "/random/stuff", description: "description")

class RestrictedListConstraint
  def initialize
    @routes = fetch_routes
  end

  def matches?(request)
    @routes.include?(request.path)
  end

  private
    def fetch_routes
      # Rails.cache.fetch("seo_routes") do # whenever the routes change, break the cache
        SeoRoutes.pluck(:url)
      # end
    end
end

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get '*path', to: 'test#index', constraints: RestrictedListConstraint.new
  end
end


class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_valid_route_success
    get "/random/stuff"
    assert last_response.ok?
  end

  def test_invalid_route_fails
    get "/random"
    refute last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```
