### ISSUE TITLE
Collection singular ids attribute should insert objects in bulk

### ISSUE THREAD

**Issue by hboisgibault** [rails/rails#44886]
### Steps to reproduce

Using the _collection_singular_ids_ attribute to update N objects of a has_many relationships (for example book_ids) makes N insert statements.

### Expected behavior

Since Rails 6, it should make use of the insert_all function and insert objects in one statement. It would drastically improve performance.

### System configuration
**Rails version**:
6.1.4.4

**Ruby version**:
2.7

**Comment by fatkodima** [comment]
This is not possible, because:
1. each associated record should have callbacks and validations called, but `insert_all` is not doing this
2. there is a possibility for a race - record is deleted before the run of `insert_all`, but `insert_all` will recreate it
