### ISSUE TITLE
Introduce option to set app name in the app generator

### ISSUE THREAD

**Issue by nicolasiensen** [rails/rails#44891]
### Steps to reproduce

When generating a new app in the current folder, I have no option to set the application name.

```shell
rails new .
```

### Expected behavior

I wish we could provide a name for the application when we are creating it in the current folder, something like the following:

```shell
rails new --name=the-next-unicorn .
```

This command would generate the Rails application in the current folder, and the file `./config/application.rb` would like the following:

```ruby
module TheNextUnicorn
  class Application < Rails::Application
    # ...
  end
end
```

### Actual behavior

When we generate the Rails application in the current folder, the file `./config/application.rb` looks like the following:

```ruby
module App
  class Application < Rails::Application
    # ...
  end
end
```

### System configuration
**Rails version**: 7.0.2.3

**Ruby version**: 3.0.2p107

**Comment by dgarcia-lwolf** [comment]
I'm reproducing the steps that you described before but it's creating a rails folder with name: --name=the-next-unicorn and with the app name: NameTheNextUnicorn, I think in case that you want defined the app name, it will be after the new clause, by example: `rails new next-unicorn`, the name that rails will defined here will be: NextUnicorn.

**Comment by nicolasiensen** [comment]
Hey @dgarcia-lwolf, thanks for replying.

You are right. I changed the issue description because I'm not reporting a bug but proposing a new feature.

Let me know if that is clear.

**Comment by SkipKayhil** [comment]
Hey @nicolasiensen, thanks for the suggestion! We reserve the issue tracker here for bugs; for feature requests or discussions the best place is https://discuss.rubyonrails.org/. Alternatively if you're interested please make a PR and we can discuss over code.

**Comment by nicolasiensen** [comment]
That makes sense, thanks!
