### ISSUE TITLE
Rails 6.1: has_many_inversing breaks belongs_to relations when having multple belongs_to for a given model

### ISSUE THREAD

**Issue by jonasporto** [rails/rails#44924]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", tag: "v6.1.5"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Support for inversing belongs_to -> has_many Active Record associations.
# default to true on rails 6.1
ActiveRecord::Base.has_many_inversing = true

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :accounts, force: true do |t|
    t.string "name", limit: 255
  end

  create_table :account_settings, force: true do |t|
    t.integer "account_id"
    t.integer "cost_account_id"
  end
end

class Account < ActiveRecord::Base
  has_many :cost_accounts, class_name: 'AccountSetting'
end

class AccountSetting < ActiveRecord::Base
  belongs_to :account
  belongs_to :cost_account, class_name: 'Account', inverse_of: :cost_accounts
end

class BugTest < Minitest::Test
  def test_association_assigning
    account = Account.new(name: 'Main Account')
    cost_account = Account.new(name: 'Cost Account')

    account_setting = AccountSetting.new(account: account, cost_account: cost_account)

    assert_equal account_setting.account, account
    assert_equal account_setting.cost_account, cost_account
  end

  def test_unset_main_account
    cost_account = Account.new(name: 'Cost Account')

    account_setting = AccountSetting.new(cost_account: cost_account)

    assert_equal account_setting.cost_account, cost_account
    assert_nil account_setting.account
  end
end

```

### Expected behavior
- On `test_association_assigning` scenario, is expected `account` and `cost_account` to return the same objects provided on instantiating
- For `test_unset_main_account`, is expected `account` to not be set (because only `cost_account` is provided)
- I believe another expected behavior would be raising an error if the has_many association doesn't correspond to the belongs_to + inverse_of

It works as expected when:
- Adding the `inverse_of :cost_account` on `has_many :cost_accounts, class_name: 'AccountSetting'`
- Setting `ActiveRecord::Base.has_many_inversing` to `false`
- Adding `foreign_key: :account_id` to `belongs_to :account`

### Actual behavior
- When assigning `AccountSetting#cost_account` it also sets `account` as the same value received for `cost_account`
- When providing `account` and `cost_account`, `account` is ignored and `cost_account` is set as value for both attributes.

### System configuration
**Rails version**: 6.1.5
**Ruby version**: 2.6.5

**Comment by jlsync** [comment]
I also had multiple belongs_to on a model break. 

The fix is to change the has_many side in the Account model above, from
`  has_many :cost_accounts, class_name: 'AccountSetting'`
to
` has_many :cost_accounts, class_name: 'AccountSetting', inverse_of :cost_account`
