### ISSUE TITLE
Rails 6.1: where.not raises ArgumentError: Unsupported argument type: chain (Symbol)

### ISSUE THREAD

**Issue by guillaumebriday** [rails/rails#44926]
### Steps to reproduce
After upgrading from Rails `6.0` to Rails `6.1`, I have this error when using a simple `where.not`.

I have no idea why but it seems to be raised at this line: https://github.com/rails/rails/blob/6-1-stable/activerecord/lib/active_record/relation/query_methods.rb#L1097

In my example, the parameter `opts` is equal to `:chain` in Rails 6.1 and `{:id => 5}` in Rails 6.0. That is why it raises an error.

Any idea why? Thanks in advance

### Expected behavior
```ruby
Status.where.not(id: 5)
#=> []
```

### Actual behavior
```ruby
Status.where.not(id: 5)
#=> ArgumentError: Unsupported argument type: chain (Symbol)
```

### System configuration
**Rails version**: 6.1.5

**Ruby version**: 2.7.6

I'm using `config.autoloader = :classic` I'm not sure if it could have an impact...

**Comment by eileencodes** [comment]
Hey @guillaumebriday, thanks for opening na issue. Unfortunately there's not enough information here to determine what's wrong - the `where.not` in active record appears to be working correctly. Can you try making a new application that reproduces the bug?

**Comment by guillaumebriday** [comment]
Hey @eileencodes and thanks for your quick reply

Actually, I think it's not a Rails issue but a bug from [awesome_hstore_translate](https://github.com/openscript/awesome_hstore_translate) that I use in one of my project. See: https://github.com/openscript/awesome_hstore_translate/issues/17

The signature of some methods has change between Rails 6.0 and Rails 6.1. That is why it's incompatible.

We can close the issue here, thanks again!
