### ISSUE TITLE
When using upsert_all, one cannot update only the timestamp attributes

### ISSUE THREAD

**Issue by zog** [rails/rails#44933]
### Steps to reproduce

```ruby
# frozen_string_literal: true

# Make sure tu run `createdb railstestdb` beforehand

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "railstestdb")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.timestamps
    t.index :title, unique: true
  end

  create_table :others, force: true do |t|
    t.string :title
    t.string :label
    t.timestamps
    t.index :title, unique: true
  end
end

class Post < ActiveRecord::Base
end

class Other < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_working
    Other.create title: "foo"
   
    # as `label` is not in uniqueness key, we get "ON CONFLICT UPDATE ..."
    res = Other.upsert_all(
      [{ title: "foo", label: "bar" }],
      unique_by: :title,
      returning: [:id, :title]
    )

    assert_equal 1, res.count
  end

  def test_failing
    Post.create title: "foo"
   
    # all the fields we want to update are in the uniqueness key, we get "ON CONFLICT DO NOTHING"
    res = Post.upsert_all(
      [{ title: "foo" }],
      unique_by: :title,
      returning: [:id, :title]
    )

    assert_equal 1, res.count
  end
end
```

### Expected behavior

When trying to upsert values in a table, if all the fields are present in the uniqueness key, it should update timestamps attributes on conflict, and return the corresponding rows .

### Actual behavior
It does nothing on conflict, and returns an empty collection.

### System configuration
**Rails version**: main

**Ruby version**: 3.1.1

**Comment by fatkodima** [comment]
> ### Expected behavior
> When trying to upsert values in a table, if all the fields are present in the uniqueness key, it should update timestamps > attributes on conflict, and return the corresponding rows.

Personally, I'm not sure this is expected behavior. If you did not update the row, why would you touch its `updated_at`? There is even a test for this: https://github.com/rails/rails/blob/bc9fa030a62a1a65d383dc08bc7de0255e555450/activerecord/test/cases/insert_all_test.rb#L378-L386

**Comment by zog** [comment]
Well, actually my issue is not with "not updating the row timestamps", but with the fact that the command returns nothing

**Comment by fatkodima** [comment]
Ok, got it. I checked the implementation of this feature in rails. 
It is a postgres behavior to **always** return results for `insert ... on conflict ... do update`, even when nothing was updated. 

From rails docs:
> :returning
(PostgreSQL only) An array of attributes to return for **all successfully inserted** records, which by default is the primary key. 

Since nothing was updated, the correct result would be an empty result for both tests and the  `test_working` should fail. But seems like there is nothing we can do, because of the mentioned (unexpected?) behavior of postgres.

**Comment by zog** [comment]
Can we consider adding a "touch" option to `upsert_all`, where it would update all `updated_at` values ?
I know it looks a bit hacky, but so far my only workaround has been adding an useless column to my table :/

**Comment by fatkodima** [comment]
Since it already returns all rows (no matter updated or not), can't you use something like:

```ruby
posts = {...}
Post.upsert_all(posts, unique_by: :title)

titles = # select titles from posts
ids = Post.where(title: titles).ids
```

to get the ids?
