### ISSUE TITLE
`simple_format` with blank `wrapper_tag` option returns nonsence HTML tag

### ISSUE THREAD

**Issue by JunichiIto** [rails/rails#44948]
### Steps to reproduce

Use `simple_format` method with blank `wrapper_tag` option.

```ruby
simple_format(nil, {}, { wrapper_tag: "" })
```

Some people try to remove wrapper tag from the result of `simple_format` method, so they give an empty string to `wrapper_tag` option.

### Expected behavior

It should fallback to `p` tag:

```ruby
"<p></p>"
```

Or return no wrapper tags:

```ruby
""
```

Or raise ArgumentError.

### Actual behavior

It returns the following HTML:

```ruby
"<></>"
```

But it is nonsense.

### System configuration
**Rails version**: 7.0.2.3

**Ruby version**: 3.1.1

**Comment by akhilgkrishnan** [comment]
Made a partial fix in PR #49120 for handling the `nil` case. But as per the discussion  https://github.com/rails/rails/pull/49120#discussion_r1315644911, we finally agreed to have validation in `content_tag` for handling different scenarios including the empty string `""` case and raising an error.

I'm working on that and creating another PR handling the validation and raising an error for `content_tag`.
