### ISSUE TITLE
Seed task runs multiple times and breaks with multi-database setup

### ISSUE THREAD

**Issue by vahe** [rails/rails#44957]
### Steps to reproduce

1. Create a rails app with Rails version pointing to latest `7-0-stable` branch
2. Create multiple databases [as per docs](https://guides.rubyonrails.org/active_record_multiple_databases.html)
3. Add a print statement in `seeds.rb` file
4. Run db prepare task: `bin/rake db:prepare` - **Notice how print statement is executed multiple times**
6. Create a migration and model for the non-primary database [as per docs](https://guides.rubyonrails.org/active_record_multiple_databases.html#generators-and-migrations), eg:
```
bin/rails generate migration CreateDogs name:string --database animals
bin/rails generate scaffold Dog name:string --database animals
```
7. Add the following to `seeds.rb`
```
Dog.create!(name: "Harry")
```

8. Run db prepare task: `bin/rake db:prepare` - **Notice `ActiveRecord::NoDatabaseError` is thrown**

### Expected behavior
`seeds.rb` should run (once per environment?) after all the databases are created/migrated.

### Actual behavior
`seeds.rb` runs for every database after it's created/migrated. If there's an attempt to connect to any database other than the first one created/migrate, an exception is thrown eg:

```
ActiveRecord::NoDatabaseError: We could not find your database: animals.
```

I think this broke after https://github.com/rails/rails/pull/44820

### System configuration
**Rails version**: `7-0-stable` branch (ref: 391505c3f2d0859f7394e6bc685ba18567154ad7)

**Ruby version**: 3.1.1

**Comment by fatkodima** [comment]
Can reproduce, but seems like not by the mentioned PR - it is also not working for the commits before that.
@eileencodes I can look into this, if you don't mind.

**Comment by eileencodes** [comment]
Go ahead @fatkodima!
