### ISSUE TITLE
Recommendations for linking an icloud email address to a mailing function

### ISSUE THREAD

**Issue by LightningRpper** [rails/rails#44978]
Hello,

I'm currently working on a website with a contact function and I would like to program that function to link to my icloud email address to send me any emails created through it. But I am not sure on how to fully link the two sources. What are some of your recommendations for using Rails to link to an icloud email account?

**Comment by SkipKayhil** [comment]
As mentioned above, I think you would get more helpful responses on https://discuss.rubyonrails.org/ or [StackOverflow](https://stackoverflow.com/questions/tagged/ruby-on-rails).

I'm going to close this as the issue tracker is reserved for bugs only.
