### ISSUE TITLE
`store_accessor` does not work with both MySQL and MariaDB

### ISSUE THREAD

**Issue by mamhoff** [rails/rails#44997]
We're maintaining a [Rails Engine](https://github.com/AlchemyCMS/alchemy_cms) that is supposed to work independent of the database in use. In one of our STI models, we use the 
`store_accessor` API in order to store some values that depend on the instance type. 

The syntax we use is: 
```rb
class Alchemy::Ingredient
  self.abstract_class = true
end
```

```rb
class Alchemy::Ingredients::Text < Alchemy::Ingredient
  store_accessor :data, :link_target
end
```

This works great with Postgres, MySQL and SQLite, as all of those databases have a native JSON(B) column type. With MariaDB, however, we run into a problem: MariaDB does [not natively support JSON](https://mariadb.com/kb/en/json-data-type/), but instead aliases it to `TEXT`. 

This means that in order to use `store_accessor`, we would need to run `store data, coder: JSON` in the superclass. However, if we do that, the code breaks for those databases that support JSON natively. 

We've tried several workarounds: 

```rb
class Alchemy::Ingredient
  self.abstract_class = true
  
    class << self
      # This is done for MariaDB, which needs to be told that
      # `data` is not text, but needs to behave like a JSON column.
      def load_schema!
        super
        if # insert conditions here
           store :data, coder: JSON
        end
      end
    end
end
```

This approach fails because `store` needs to be called before the schema is loaded. We've also tried overriding `store_attribute_for` from the [store.rb](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/store.rb#L216-L218) file - also calls `store` too late. 

This is not so much a bug report as a feature request. I'm not sure what the best path forward could be: 
1. Allow running `store` on columns that are already JSON without breaking past behavior
2. Add an extra configuration option to the `database.yml` hash (`flavor: mariadb`), upon which certain model configurations can be made
3. Allow `store` to be called after loading the schema.

### Expected behavior

We would like to be able to use `store_accessor` on MariaDB, MySQL, Postgres and SQLite databases.

### Actual behavior

We have to forgo the benefits of the native JSON type in MySQL, SQLite, and Postgres and use `TEXT`, or we cannot support MariaDB.

### System configuration

We've tried with every permutation of Ruby 2.6 - 3.1 and Rails 6 through 7. See  https://github.com/AlchemyCMS/alchemy_cms/runs/6249316280 for spec runs and https://github.com/AlchemyCMS/alchemy_cms for implementation details.

**Comment by mamhoff** [comment]
It looks like we've found a fix that works for us, it may work for others, too: 

By forcing the type of our `data` column to be `:json`, we have something that works for all databases. 

Code example:

```rb
class Alchemy::Ingredient
  attribute :data, :json
```

This has - for our purposes - the same outcome as running `store: :data, coder: JSON`, but also works if `data` is already a JSON field.

**Comment by rolfschmidt** [comment]
yo @mamhoff ,

thank you very much for your approach. I think this issue should get reopened because it is still a open topic to fix? I'm currently evaluating another hack which is a bit more dynamic and could be helpful for a proper fix. I found out that the constraint checks might be a nice indication to modify the column type on a lower level.

config/initializers/mariadb_json_columns.rb
```ruby
require_dependency 'active_record/connection_adapters/abstract_mysql_adapter'

ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter.class_eval do
  private

  alias_method :column_definitions_original, :column_definitions

  def column_definitions(table_name)
    result = column_definitions_original(table_name)
    if mariadb?
      result.each do |row|
        next if row[:Type] != 'longtext'
        next if !mariadb_column_json?(table_name, row[:Field])

        row[:Type] = 'json'
      end
    end
    result
  end

  # json columns in mariadb are listed as longtext, so we
  # need to check the constraint checks to find out if the column
  # was created as json. Based on this detection we will hack the
  # type so rails will handle values properly as json values.
  def mariadb_column_json?(table_name, field_name)
    field = quote(field_name)
    scope = quoted_scope(table_name)
    execute_and_free("SELECT 1 FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS WHERE TABLE_NAME = #{scope[:name]} AND CONSTRAINT_SCHEMA = #{scope[:schema]} AND CONSTRAINT_NAME = #{field} AND CHECK_CLAUSE LIKE '%json_valid%'") do |r|
      return r.to_a.present?
    end
  end
end
```

@kamipo you did the original implementation right? (https://github.com/rails/rails/pull/21110) Are you only working with mysql or also mariadb? Do you think the constraint checks would be a possible fix or do you have any idea how we could solve this issue also for mariadb?

**Comment by gagaha** [comment]
Hi, 

thank you @mamhoff for sharing your workaround for this issue. I can confirm that this works for us aswell. 
But I also agree with the opinion of @rolfschmidt, that this is still an ongoing issue on the side of the mysql adapter which would be worth to fix. 
So I would welcome reopening this issue.

**Comment by Floppy** [comment]
Just run into this problem here, and yes, it would be great to reopen this issue as while @mamhoff's solution works a treat, Rails should be dealing with this itself deeper down.
