### ISSUE TITLE
Action Cable: Subscriptions.notify "Cannot read received of undefined"

### ISSUE THREAD

**Issue by ppascualv** [rails/rails#45002]
This error is still happening I'm using    `"actioncable": "^5.2.7-1"` and graphql
```
import ActionCableLink from "graphql-ruby-client/subscriptions/ActionCableLink"
import { relayStylePagination } from "@apollo/client/utilities"

if (typeof window !== "undefined") {
  const ActionCable = require("actioncable")
}

const wsClient =
  typeof window === "undefined"
    ? null
    : ActionCable.createConsumer(`${process.env.NEXT_PUBLIC_WS_URL}?auth_token=${getAuth()}`)

const wsLink = typeof window === "undefined" ? null : new ActionCableLink({ cable: wsClient })
```
![Screenshot from 2022-04-26 15-26-04](https://user-images.githubusercontent.com/2453682/165997078-4001646d-37e7-4978-a8f2-c1b8ca2e4fba.png)

The library that I'm using is handling subscriptions according to docs.
https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/src/subscriptions/ActionCableSubscriber.ts#L33

_Originally posted by @ppascualv in https://github.com/rails/rails/issues/43340#issuecomment-1113530439_

**Comment by tjk** [comment]
Seeing this too after upgrading from `actioncable (5.2.7.1)` to `actioncable (6.1.6)`.

(using `@rails/actioncable@6.0.3-7` in both cases)

**Comment by tjk** [comment]
Was this actually fixed or is this just a stale to completed timed automation?

**Comment by ppascualv** [comment]
This bug is still happening
