### ISSUE TITLE
Wrong links in docs for Ruby on Rails 6

### ISSUE THREAD

**Issue by Kapeli** [rails/rails#45001]
The links at https://api.rubyonrails.org/v6.1.5.1/ point to Ruby on Rails 7. For example, the "Getting Started with Rails" link at the bottom takes you to https://guides.rubyonrails.org/getting_started.html, which is for Ruby on Rails 7.

**Comment by grassiricardo** [comment]
Hello @Kapeli, I don't understand your issue. Do you send me more information for this problem?

**Comment by memorycancel** [comment]
@grassiricardo I think @Kapeli means, every link should be correspond to the corresponding version of rails, like

<img width="1439" alt="图片" src="https://user-images.githubusercontent.com/10057052/169287688-4e67a3f0-0a11-4838-a4e6-7c049297c256.png">

**Comment by grassiricardo** [comment]
@memorycancel Oh, ok. I go see to fix this problem.

**Comment by grassiricardo** [comment]
@memorycancel Do you know where stay this project? https://api.rubyonrails.org/v6.1.5.1/
I never contribute for this project api.rubyonrails.

**Comment by grassiricardo** [comment]
Or @skipkayhil you can help me please?

**Comment by simi** [comment]
That part is generated by RDOC_MAIN.rdoc.

https://github.com/rails/rails/blob/1fde031e899bf950bb43566bdef02308ee36ed1e/railties/RDOC_MAIN.rdoc#getting-started-

**Comment by grassiricardo** [comment]
@simi you contribute for this project? Can you help me, please?
