### ISSUE TITLE
Contrast between text and background is too low when searching routes on the routing error page in development in dark mode

### ISSUE THREAD

**Issue by dhughes** [rails/rails#45007]
### Steps to reproduce

1. Enable dark mode on your OS. 
2. Create a new Rails 6.1 app with `rails new someapp`.  
3. Start the app and navigate to any URL without a matching route. EG: http://localhost:3000/hi_mom
4. Use the provided search field and search for a route that exists. For example: "conductor/action_mailbox/inbound_emails"
5. Observe that the matching routes output at the top of the table are exceptionally hard to read and are definitely not accessible.

Here's an example screenshot:

![Screen Shot 2022-05-02 at 2 18 09 PM](https://user-images.githubusercontent.com/573772/166302711-97ae5c98-91bc-42c9-bd96-9b71257f1e64.png)

This problem is known to occur in Chrome, Firefiox, Safari, and Edge on Mac OS. It is presumed to occur in Windows, though I don't have access to a Windows machine to test and confirm this.

### Expected behavior
I would expect that the table's search data show highlighted results and with high enough contrast that the text is legible.  For example, something like this:

![Screen Shot 2022-05-02 at 2 30 30 PM](https://user-images.githubusercontent.com/573772/166304483-5cbe4482-ff6e-4117-a07a-b6ce4f8f2a0c.png)

This screenshot shows the CSS having been manually edited in the browser's developer tools to make search result text bold and colored #ddd.

### Actual behavior
As shown in the initial screenshot, the contrast of the text shown in the search results in the routes table is too low-contrast to be readable.

### System configuration
**Rails version**:
This appears to have been introduced in Rails 6.1. I have explicitly reproduced this in Rails 6.1.4.1. It does _not_ occur in Rails 6.0 or 5.1 which do not appear to support OS dark mode.

**Ruby version**:
 This is known to occur with Ruby 2.6.9, 2.7.4, and 3.03.

**Comment by jonathanhefner** [comment]
Thank you for opening an issue!

This was fixed by #41000, and the fix was included in Rails 7.0.

As per our [maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html), Rails 6.1 is currently receiving security patches only, so it is unlikely that the fix will be backported.

**Comment by dhughes** [comment]
@jonathanhefner I hear you and understand the policy. If that's the way it is, that's the way it is. There are workarounds like using browser extensions to modify styles on that page. 

However, I'd like to make the point that this isn't just a usability issue, but an accessibility issue for users with sight-related disabilities. Honestly, it's so hard to read that, arguably, it's no less accessible to that population than to normally sighted people, but _perhaps_ this type of concern is worth a non-security patch update to 6.1?

Regardless, thanks for the speedy review and response.
