### ISSUE TITLE
Rails version 7+ breaks with Ruby 3.1+

### ISSUE THREAD

**Issue by MarkusAbtion** [rails/rails#45010]
It seems like [this addition](https://github.com/rails/rails/commit/1e56b1d1152e8ab74203db30625116844614cc78#r71711767) broke the integration with Psych 4 and Ruby 3.1.

### Steps to reproduce
- Install Rails 7
- Install Ruby 3.1
- Setup databases (it should fail here)

### Expected behavior
That it works

### Actual behavior
`Psych 4: aliases in database.yml cause Psych::BadAlias exception`

### System configuration
**Rails version**: 7+

**Ruby version**: 3.1+

@byroot

**Comment by byroot** [comment]
@MarkusAbtion I can't reproduce, would you mind including a backtrace as well as the content of your `database.yml`?

**Comment by MarkusAbtion** [comment]
I tried to reproduce myself.
And you're right. This is actually an issue with an old version of webpacker. 
Sorry about this!
