### ISSUE TITLE
Migration: change_column_default removes column options from schema.rb

### ISSUE THREAD

**Issue by rikvanderkemp** [rails/rails#45023]
### Steps to reproduce

Please be aware that the test succeeds! The problem lies on the changes in `schema.rb`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :payments, force: true do |t|
    t.decimal "amount", precision: 10, scale: 2, default: "0.0", null: false
  end
end

class Payment < ActiveRecord::Base
end

class ChangeAmountToAddScale < ActiveRecord::Migration[6.0]
  def change
    reversible do |dir|
      dir.up do
        change_column_default :payments, :amount, nil
      end

      dir.down do
        change_column_default :payments, :amount, "0.0"
      end
    end
  end
end

class BugTest < Minitest::Test
  def test_migration_up
    ChangeAmountToAddScale.migrate(:up)
    Payment.reset_column_information

    assert_equal "decimal(10,2)", Payment.columns.last.sql_type
  end

  def test_migration_down
    ChangeAmountToAddScale.migrate(:down)
    Payment.reset_column_information

    assert_equal "decimal(10,2)", Payment.columns.last.sql_type
  end
end
```

### Expected behavior

I expected to see the following change in `schema.rb`

```ruby
create_table "payments", force: :cascade do |t| 
    t.decimal "amount", precision: 10, scale: 2, default:  nil, null: false
end
```

### Actual behavior

All options are gone, except for the change in default value.

```ruby
create_table "payments", force: :cascade do |t| 
    t.decimal "amount", default:  nil, null: false
end
```

### System configuration
**Rails version**: 6.1.5.1

**Ruby version**:  2.7.3p183

### Additional note
Maybe I misunderstand the underlying functionality but the [documentation only mentions](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-change_column_default) changes to the default value.

**Comment by fatkodima** [comment]
Can't reproduce. I see
```ruby
    t.decimal "amount", precision: 10, scale: 2, null: false
```

`default` is absent because `nil` is by default, so it is redundant.

Can you provide a sample app, which reproduces an issue?

**Comment by rikvanderkemp** [comment]
> Can't reproduce. I see
> 
> ```ruby
>     t.decimal "amount", precision: 10, scale: 2, null: false
> ```
> 
> `default` is absent because `nil` is by default, so it is redundant.
> 
> Can you provide a sample app, which reproduces an issue?

Well that is just odd, a complete fresh install of rails (same version) seems to work correctly.
Just tried it in our project and the behaviour is different. Trying to see if I can make this reproduceable.

**Comment by rikvanderkemp** [comment]
Will close the issue for now. It seems to happen specifically in our project for some reason. Once I'll be able to reproduce this correctly I'll reopen the issue (if I can that is)
