### ISSUE TITLE
ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.reconnect doesn't seem to reach rescue block

### ISSUE THREAD

**Issue by eshults35** [rails/rails#45038]
Regarding the reconnect! function

```
def reconnect!
        @lock.synchronize do
          super
          @connection.reset
          configure_connection
        rescue PG::ConnectionBad
          connect
        end
      end
```

In debugging a gem that enables RDS IAM authentication, we are hitting a potential bug on reconnect! as described here: https://github.com/haines/pg-aws_rds_iam/issues/290

The obvious fix was to add PG:Error to the caught exceptions as that was the error being encountered in configure_connection which is being called by reconnect!. However, after further debugging, the exception still wasn't being caught.

I found that the exception was finally caught by moving the rescue block within the do block like so:

```
def reconnect!
        @lock.synchronize do
          super
          @connection.reset
          configure_connection
          rescue PG::ConnectionBad, PG::Error
            connect
        end
      end
```

Ofcourse this is totally unrelated with the issue we are trying to solve in the gem. But since the only code block within the function is contained in that do, and since the @lock.synchronize doesn't seem to contain any PG class functionality (as far as I know), it seems that the rescue block in general may be wrongly placed. 

At the least, I think it would be important to discuss the background of this function and the intention of that rescue block, as the least impactful change on my end, if in fact that rescue PG::ConnectionBad is rightfully placed for a specific purpose, just may be this:

```
def reconnect!
        @lock.synchronize do
          super
          @connection.reset
          configure_connection
          rescue PG::Error
            connect
        rescue PG::ConnectionBad
          connect
        end
      end
```

### Steps to reproduce 

```ruby
Unfortunately outside of the context of temporary passwords, there doesn't seem to be a clear reproducible way of reaching that rescue block. But in the context of utilizing the pg-aws_rds_iam gem, I was able to reproduce the PG:Error issue as follows:
--connection established
>> ActiveRecord::Base.connection.execute("SELECT pg_sleep(10000);")
SSL SYSCALL error: Operation timed out
>> ActiveRecord::Base.connection.reconnect!
PG::Error: connection to server at "xxx" (xxx), port 5432 failed: FATAL:  PAM authentication failed for user "xxx"
connection to server at "xxx" (xxx), port 5432 failed: FATAL:  pg_hba.conf rejects connection for host "10.249.250.113", user "xxx", database "xxx", SSL off
```

### Expected behavior
When adding the PG:Error exception to existing rescue block, failure in configure_connection should hit this block.

### Actual behavior
Rescue block is never reached and connection never happens. 

### System configuration
**Rails version**: 6.0.4.4

**Ruby version**: 2.7.3

**Comment by eshults35** [comment]
Actually I may be able to reproduce this by changing the PW half way through. Will test and update this issue.

**Comment by eshults35** [comment]
So in the following 2 scenarios, it seems PG throws a PG::Error rather than a PG::ConnectionBad when failing within the reconnect! block:

losing route
```
ActiveRecord::Base.connection.reconnect!
success and disconnect from VPN
ActiveRecord::Base.connection.reconnect!
PG:Error
```

Changing PW of connection:

```
ActiveRecord::Base.connection.reconnect!
success and change PW in Postgres
ActiveRecord::Base.connection.reconnect!
PG:Error
```

But if I initially have an incorrect password or bad route I get a PG:ConnectionBad in the following scenarios:
Incorrect password at first attempt (fails in ConnectionHandling.postgresql_connection method)
```
ActiveRecord::Base.connection.reconnect!
PG::ConnectionBad
```
Establish_connection followed by SELECT 1 with incorrect password
```
ActiveRecord::Base.establish_connection
ActiveRecord::Base.connection.execute("SELECT 1;")
PG::ConnectionBad
```

Makes me wonder if the reconnect! class should be capturing PG::Error and not PG::ConnectionBad

**Comment by fatkodima** [comment]
@eshults35 Can you verify the issue is still present on `main`?

**Comment by eshults35** [comment]
@fatkodima Will do
