### ISSUE TITLE
Ability to use helpers within content_security_policy controller method

### ISSUE THREAD

**Issue by lavaturtle** [rails/rails#45034]
Hi! I'm using Rails 7.0, with ruby 3.1.1, and have just started using the controller `content_security_policy` method.

I have a helper method something like this:
```
module TrackingHelper
  def use_google_analytics?
    # Some logic based on the current hostname and account that returns either true or false
  end
end
```

I would like to be able to write a content security policy like this:
```
class MyController
  content_security_policy do |policy|
    script_sources = [:self, 'https://example.com']
    if helpers.use_google_analytics?
      script_sources << 'https://www.googletagmanager.com'
    end
    policy.script_src script_sources
  end
end
```

But when I try that, I get errors from within my helper method, because it seems the controller is nil within the helper method. I'm able to successfully use `helpers` methods from _other_ `before_action` methods, so I assume it's something about `content_security_policy` that results in the controller not being passed along to the helper method. Is this a known issue? Would it be possible to enable `helpers` within `content_security_policy`?

Thanks for your time!

**Comment by ghiculescu** [comment]
> I'm able to successfully use `helpers` methods from _other_ `before_action` methods, so I assume it's something about `content_security_policy` that results in the controller not being passed along to the helper method

I would have thought so too. It seems like a pretty simple implementation https://github.com/rails/rails/blob/01d836fcf384b2fa9c416705b0570737ac9ad7e0/actionpack/lib/action_controller/metal/content_security_policy.rb#L18

Is it possible to share a basic app that reproduces the issue?

**Comment by lavaturtle** [comment]
OK! Here's an example app: https://github.com/controlshift/rails-csp-helper-demo

If you try to visit `/foo` or run `./bin/rails test test/controllers/foo_controller_test.rb`, you'll see this error:
```
NoMethodError: undefined method `special_check?' for nil:NilClass

  controller.send(:'special_check?', *args, &block)  #   controller.send(:'current_user', *args, &block)
            ^^^^^
    app/controllers/application_controller.rb:3:in `special_check?'
    app/helpers/application_helper.rb:7:in `enable_extra_source_2?'
    app/controllers/foo_controller.rb:9:in `block in <class:FooController>'
    test/controllers/foo_controller_test.rb:5:in `block in <class:FooControllerTest>'
```

I found something interesting while putting this test together: A simple helper method like https://github.com/controlshift/rails-csp-helper-demo/blob/main/app/helpers/application_helper.rb#L2 works fine within `content_security_policy`, but one that relies on a `helper_method`, like https://github.com/controlshift/rails-csp-helper-demo/blob/main/app/helpers/application_helper.rb#L6, causes the error.

**Comment by ghiculescu** [comment]
I'm not sure the issue is `helper_method` specifically. I think it's that `controller` is `nil` in all the helper methods. It just so happens that `helper_method` relies on `controller` to find the method.

I *think* this is a bug because `controller` *is* defined in helper methods when they are accessed from a view or from an action method. It seems like it's only the class-level version of `helpers` that is problematic.

Anyway, a workaround for now could be to avoid using `helper_method` to define the relevant method?

**Comment by lavaturtle** [comment]
Cool, thanks!
