### ISSUE TITLE
upsert_all causes PG::NotNullViolation

### ISSUE THREAD

**Issue by varg90** [rails/rails#45049]
### Steps to reproduce

Create a model with some attributes that is `null: false` in the db schema (I use PostgreSQL). For example, a `Book` with attributes `title` and `color`. Then try to update existing records using `upsert_all` method. Let's say we already have books with the next attributes:
```
id: 1, title: 'Red Book', color: 'Red'
id: 2, title: 'Blue Book', color: 'Blue'
```

```ruby
Book.upsert_all([
    {id: 1, title: 'Actually Crimson Book'}, 
    {id: 2, title: 'Azure Book'}
  ], update_only: [:title])
```

### Expected behavior
It is expected that it will ignore skipped `color` attribute for two reasons: we didn't list it in the upsert_all attributes and we didn't put it in the upsert_all `update_only` option. It should successfully update just titles by the books' ids (as a default index for `unique_by`)

### Actual behavior
We get an error:
```
Book Bulk Upsert (0.9ms)  INSERT INTO "books" ("id","title","created_at","updated_at") VALUES (1, 'Actually Crimson Book', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (2, 'Azure Book', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) ON CONFLICT ("id") DO UPDATE SET updated_at=(CASE WHEN ("books"."title" IS NOT DISTINCT FROM excluded."title") THEN "books".updated_at ELSE CURRENT_TIMESTAMP END),"title"=excluded."title" RETURNING "id"

/my/path/to/gems/activerecord-7.0.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params':
PG::NotNullViolation: ERROR:  null value in column "color" of relation "books" violates not-null constraint (ActiveRecord::NotNullViolation)
DETAIL:  Failing row contains (1, null, Actually Crimson Book, 2022-05-09 19:06:09.0335, 2022-05-09 19:06:09.0335).

/my/path/to/gems/activerecord-7.0.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params':
ERROR:  null value in column "color" of relation "books" violates not-null constraint (PG::NotNullViolation)
DETAIL:  Failing row contains (1, null, Actually Crimson Book, 2022-05-09 19:06:09.0335, 2022-05-09 19:06:09.0335).
```
Which is strange since we don't see anything about the `color` in the SQL request `ON CONFLICT ("id") DO UPDATE SET ... `

### System configuration
**Rails version**:
7.0.2.4
**Ruby version**:
3.0.2

**Comment by varg90** [comment]
The issue will gone if we add any value to the `color` attribute
```
Book.upsert_all([
    {id: 1, title: 'Actually Crimson Book', color: 'anything'}, 
    {id: 2, title: 'Azure Book', color: 'anything'}
  ], update_only: [:title])
  ```
  but it doesn't seem right to put ignored attribute here

**Comment by varg90** [comment]
We can also add `change_column_null :books, :color, true` migration. But it doesn't look safe either since `upsert_all` does not trigger Active Record callbacks or validations

**Comment by fatkodima** [comment]
Unfortunately, [this is how it works](https://stackoverflow.com/questions/67874661/postgresql-upsert-insert-on-conflict-update-fails) and seems like there is nothing we can do about it, except the mentioned hacks.

Also, the check constraint example from the link also not works.

**Comment by fatkodima** [comment]
If this column had a default, we can try to insert defaults for non-nullable columns. This will possibly reduce the amount of errors like the original one for users. 
I can try to implement. Just need for other people to confirm this is a good idea.

**Comment by varg90** [comment]
Hi @fatkodima thanks for your answer. 
I see, so the problem is in the PostgreSQL `upsert` method. It would make sense to be able to pass array of objects to the `update_all` method instead of `upsert_all` since I only update existing records in my case, but I'd like to do that with a single request which upsert does.
About defaults it would not help in my case, but may be useful for other users.
