### ISSUE TITLE
Memory consumption problem when creating jobs from another job

### ISSUE THREAD

**Issue by panovek** [rails/rails#45040]
If we have some kind of job that creates a large number (for example, hundreds of thousands) of other jobs in the course of its work, then the problem with memory consumption becomes clearly visible, which depends solely on the number of created jobs and is freed only after the main job finishes its work.

### Steps to reproduce
Test example: https://github.com/panovek/test_jobs
This example with sidekiq, but it is just for visualization. Problem reproduced with plain AJ also.
To see the problem, you can run this test application, click "Start test" link and observe the memory consumption of ruby process while the main job is running.

Or you can create new simple rails app with 2 simple jobs:

```ruby
class MainJob < ApplicationJob
  def perform
      400000.times { ChildJob.perform_later("asdfasdfasdf", options: { a: 1, b: 2 }) }
  end
end

class ChildJob < ApplicationJob
  def perform(some_text, options = {})
  end
end

MainJob.perform_later
```

### Expected behavior
Jobs generated, memory does not grow significantly.

### Actual behavior
Jobs generated, but memory grow and freed only when main job finished.

### System configuration
**Rails version**: Rails 6.1.5.1

**Ruby version**: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin20]

**Comment by fatkodima** [comment]
Can reproduce on `6.1.5.1`, can't reproduce on `main`. That was fixed by https://github.com/rails/rails/commit/51e28dc3221509e084d51e5c948d6b76ee9688f5, so you need to upgrade or this should be backported to `6-1-stable`.

@jhawthorn

**Comment by byroot** [comment]
Unfortunately 6.1 isn't supposed to receive bug fixes anymore, only security fixes.
