### ISSUE TITLE
Time#advance and Time#change behave incorrectly at fall Daylight Saving Time change

### ISSUE THREAD

**Issue by ikaronen-relex** [rails/rails#45055]
### Steps to reproduce

Run the following RSpec:

```ruby
require 'active_support/time'

describe Time do
  before { Time.zone = 'Europe/Lisbon' }
  let(:time) { Time.new(2021, 10, 31, 0, 0, 0, Time.zone).advance(hours: 2) }

  context '#advance' do
    it 'works correctly at fall DST change' do
      expect(time.advance(seconds: 0) - time).to eq(0)
    end
  end

  context '#change' do
    it 'works correctly at fall DST change' do
      expect(time.change(sec: 0) - time).to eq(0)
    end
  end
end
```

### Expected behavior

Specs pass.

### Actual behavior

Specs fail as follows:

```
  1) Time#advance works correctly at fall DST change
     Failure/Error: expect(time.advance(seconds: 0) - time).to eq(0)
     
       expected: 0
            got: 3600.0
     
       (compared using ==)
     # ./backend/spec/rails_time_advance_dst_spec.rb:7:in `block in <main>'

  2) Time#change works correctly at fall DST change
     Failure/Error: expect(time.change(sec: 0) - time).to eq(0)
     
       expected: 0
            got: 3600.0
     
       (compared using ==)
     # ./backend/spec/rails_time_advance_dst_spec.rb:13:in `block in <main>'
```

### System configuration

**Rails version**: 6.1.5.1

**Ruby version**: 2.6.8p0 (jruby 9.3.4.0)

### Notes

The bug is probably also reproducible on Rails 7.0.3, since [the relevant code](https://github.com/rails/rails/blob/v7.0.3//activesupport/lib/active_support/core_ext/time/calculations.rb#L138) hasn't changed [since 6.1.5.1](https://github.com/rails/rails/blob/v6.1.5.1/activesupport/lib/active_support/core_ext/time/calculations.rb#L139).

Using ActiveSupport::TimeWithZone instead of Time (i.e. replacing `Time.new(..., Time.zone)` with `Time.zone.local(...)`) makes the specs pass, and can be an acceptable workaround. Nonetheless, since ActiveSupport does attempt and claim to support working with Time objects, and provides the `change` and `advance` methods for them, I consider this a bug. FWIW, it has bit me in practice while writing tests for DST handling in our time-related code. 

The specs above are the shortest and simplest examples I've found that clearly display the incorrect behavior. There's probably some need for more comprehensive test coverage for time handling around DST changes in general, as I can think of several possible tweaks to the behavior that could probably make the specs above pass while still leaving the underlying bug(s) unfixed.

In particular, note that the `time` fixture set up for the specs above is arguably already a somewhat broken object: it stringifies to "2021-10-31 02:00:00 +0100", which is not a time that exists in the Lisbon time zone, as the clock should've jumped back to 01:00:00 +0000 at that moment. My original code, of which the above is a condensed version, stepped the time forward by one minute increments using `advance(minutes: 1)`; the `time` value above is where things broke down when doing that.

**Comment by kaiquekandykoga** [comment]
change method needs to use sec instead of seconds.

```
irb(main):001:0> time = Time.new(2000, 01, 01)
=> 2000-01-01 00:00:00 -0200
irb(main):002:0> time.change(seconds: 10)
=> 2000-01-01 00:00:00 -0200
irb(main):003:0> time.change(sec: 10)
=> 2000-01-01 00:00:10 -0200
```

**Comment by ikaronen-relex** [comment]
@kaiquekandykoga Thanks. I've fixed the spec above. It doesn't actually change the failure in any way. Indeed, even passing an empty hash (i.e. `time.change({})`) will trigger the same misbehavior.

**Comment by ghiculescu** [comment]
[Executable test case](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case):

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/time"
require "minitest/autorun"

Time.zone = 'Europe/Lisbon'

class BugTest < Minitest::Test
  def test_advance
    time = Time.new(2021, 10, 31, 0, 0, 0, Time.zone).advance(hours: 2)
    assert_equal 0, time.advance(seconds: 0) - time
  end

  def test_change
    time = Time.new(2021, 10, 31, 0, 0, 0, Time.zone).advance(hours: 2)
    assert_equal 0, time.change(seconds: 0) - time
  end
end
```
