### ISSUE TITLE
Deprecation warning after patch upgrade from Rails 6.0.4.8 to Rails 6.0.5

### ISSUE THREAD

**Issue by diesl** [rails/rails#45076]
### Steps to reproduce
I have a Rails app that runs fine with Rails 6.0.4.8, but after a new build with Rails 6.0.5, I get a Deprecation warning during startup (with setting  `config.active_support.deprecation = :raise`). 

With another setting like `:log`, it works fine of course, but I think this deprecation warning should not occur in a minor patch version?

### Expected behavior
Startup should work without deprecation warning

### Actual behavior
At startup I get the following error:

```
=> Booting Puma
=> Rails 6.0.5 application starting in development
=> Run `rails server --help` for more startup options
Exiting
/usr/local/bundle/gems/railties-6.0.5/lib/rails/initializable.rb:32:in `instance_exec': DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper. (ActiveSupport::DeprecationException)

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <main> at /myapp/config/environment.rb:5)
       from /usr/local/bundle/gems/railties-6.0.5/lib/rails/initializable.rb:32:in `run'
       from /usr/local/bundle/gems/railties-6.0.5/lib/rails/initializable.rb:61:in `block in run_initializers'
```

Digging a bit further with the script from [here](https://github.com/rails/rails/issues/36546#issuecomment-558773961), I got the following result:

```
=> Booting Puma
=> Rails 6.0.5 application starting in development
=> Run `rails server --help` for more startup options
Cleaned backtrace:
       actiontext (6.0.5) lib/action_text/engine.rb:42:in `block (3 levels) in <class:Engine>'
       actiontext (6.0.5) lib/action_text/engine.rb:41:in `block (2 levels) in <class:Engine>'
       actiontext (6.0.5) lib/action_text/engine.rb:40:in `each'
       actiontext (6.0.5) lib/action_text/engine.rb:40:in `block in <class:Engine>'
       /myapp/config/environment.rb:5:in `<main>'
       config.ru:3:in `require_relative'
       config.ru:3:in `block in <main>'
       <internal:kernel>:90:in `tap'
Most probably the cause is: actiontext (6.0.5) lib/action_text/engine.rb:42:in `block (3 levels) in <class:Engine>'
```

### System configuration
**Rails version**: 6.0.5

**Ruby version**: 3.0.4p208

**Comment by diesl** [comment]
Hi @eileencodes,

I know this deprecation has been already existing since 6.0.x and we fixed these deprecation warnings quite some time ago. However, this deprecation warning now reappeared when (only!) the Rails gem was updated from 6.0.4.8 to 6.0.5. 

> You can use the script in https://github.com/rails/rails/issues/36546#issuecomment-791736621 to find which gem it is.

I did, and I already posted the output in my initial post. It says

```
Most probably the cause is: actiontext (6.0.5) lib/action_text/engine.rb:42
```

I even stripped down my Gemfile to

```ruby
source "https://rubygems.org"

ruby "~> 3.0.0"

gem "rails", "~> 6.0.0" # , "< 6.0.5"
gem "mysql2", "~> 0.5.3"
gem "puma", "~> 5.0"
gem "bootsnap", require: false
```

Starting without errors on Rails 6.0.4.8, but same error on Rails 6.0.5.

When looking at the diff of the two releases https://github.com/rails/rails/compare/v6.0.4.8...v6.0.5, the mentioned code in `lib/action_text/engine.rb:42` has indeed changed in commit https://github.com/rails/rails/commit/3e6ac87136ef2ff6766af2ab468da48dbae6ae9e

**Comment by eileencodes** [comment]
@p8 @jeremy @jonathanhefner can one of you look at this? Sounds related to the backport PR #42620 that @p8 made, but I think Jeremy and Jonathan are the original authors. I'm too busy with RailsConf prep to debug this now.

**Comment by p8** [comment]
@eileencodes I had a quick look.
Maybe we need to do add the helpers path to the autoload_once_paths?
Like we do on in Rails 7.0:
https://github.com/rails/rails/commit/c431432f93a35530cd0544192b93dabda51f2bf7

**Comment by jonathanhefner** [comment]
@diesl What is on line 5 of `/myapp/config/environment.rb`?  Is it something that would load `ActionMailer::Base`?

The reason I ask is because `lib/action_text/engine.rb` invoked `helper ActionText::Engine.helpers` (which loads `ActionText::ContentHelper` and `ActionText::TagHelper`) prior to 3e6ac87136ef2ff6766af2ab468da48dbae6ae9e (i.e. [in Rails 6.0.4](https://github.com/rails/rails/blob/v6.0.4/actiontext/lib/action_text/engine.rb#L41)).  3e6ac87136ef2ff6766af2ab468da48dbae6ae9e merely triggers that behavior on `ActionMailer::Base` load as well.

Also, based on @p8's suggestion, does adding the following *before line 5* in `/myapp/config/environment.rb` eliminate the warning?

```ruby
ActionText::Engine.instance_eval do
  config.autoload_once_paths = %W(
    #{root}/app/helpers
    #{root}/app/models
  )
end
```

**Comment by diesl** [comment]
Hi @jonathanhefner, thanks for your support!

> What is on line 5 of /myapp/config/environment.rb?

This is our `config/environment.rb`
```ruby
# Load the Rails application.
require_relative "application"

# Initialize the Rails application.
Rails.application.initialize!
```

> Also, based on @p8's suggestion, does adding the following before line 5 in /myapp/config/environment.rb eliminate the warning?

Yes, adding these lines before the `Rails.application.initialize!` does eliminate the warning.

**Comment by p8** [comment]
Thanks for checking @diesl !
I've created a PR to backport c431432f93a35530cd0544192b93dabda51f2bf7

**Comment by diesl** [comment]
Perfect! Thank you all for the support and quick fix @p8 @jonathanhefner and @eileencodes

**Comment by jonathanhefner** [comment]
@diesl  Do you have an initializer which references `ActionMailer::Base` outside of an `on_load` block?  Perhaps something like #42170?  If so, does wrapping it in an `on_load` block (see https://github.com/rails/rails/issues/42170#issuecomment-835177539) also eliminate the warning?

I'm not opposed to backporting c431432f93a35530cd0544192b93dabda51f2bf7, but I'm not sure when or if we'll do another 6.0.x release (see [our maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html)).  Of course, you could point your app at the `6-0-stable` branch if you're comfortable doing that.

Also, regardless of whether we backport c431432f93a35530cd0544192b93dabda51f2bf7, it is recommended to use an `on_load` block when referencing autoloaded classes in an initializer.

**Comment by diesl** [comment]
@jonathanhefner Seems like you finally pushed me on the right track 👍 

> Do you have an initializer which references ActionMailer::Base outside of an on_load block?

At first I thought no, because our `Interceptor`s are already wrapped in a `Rails.application.reloader.to_prepare` block. 

However, after some more investigation, I found an assignment of `ActionMailer::Base.smtp_settings` in another initializer file. After putting it into the  `to_prepare` block too, the warning is also gone.

So everything considered, the backport likely is not necessary. Thanks again for the help and sorry for the false alarm.

**Comment by eileencodes** [comment]
I'm going to close this and the backport PR since the issue can be fixed in your app. 👍🏼
