### ISSUE TITLE
Normalize `ActiveSupport::Duration` when substracting durations

### ISSUE THREAD

**Issue by amomchilov** [rails/rails#45087]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org/"
  
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  
  # Activate the gem you are reporting the issue against.
  gem "activesupport", "~> 7.0.2.3"
end

require "active_support"
require "active_support/core_ext/numeric/time.rb"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    assert_equal "1 hour and 1 minute", (1.hour + 1.minute).inspect # ✅
    assert_equal "59 minutes", (1.hour - 1.minute).inspect # ❌ actual: "1 hour and -1 minutes"
  end
end
```

### Expected behavior

```
1 hour and 1 minute
59 minutes
```

### Actual behavior

```
1 hour and 1 minute
1 hour and -1 minutes
```

This can be achieved by passing the result back through a `.build`:

```ruby
p ActiveSupport::Duration.build(1.hour - 1.minute) # => "59 minutes"
```

It would be nice if this was the built-in behavior of subtracting durations. If backwards compatibility or perforance concerns are an issue, then I thing the next-best-thing would be to add a `#normalize` method:

```ruby
p (1.hour - 1.minute).normalize # => "59 minutes"
```

### System configuration

**Rails version**: `rails (7.0.2.3)`
**Ruby version**: `ruby 3.1.2p20`

**Comment by nvasilevski** [comment]
I think the default behaviour "works as designed", a bit context - https://github.com/rails/rails/issues/44331#issuecomment-1030689727
However having a method like `normalize` to force the parts recalculation might be a reasonable thing to consider
