### ISSUE TITLE
Should "defaults" initializer be loaded at the same time that defaults version is?

### ISSUE THREAD

**Issue by brandoncc** [rails/rails#45105]
Important note: I reference Rails 5 as our current working app version, but I created a test app and gem on Rails main branch (7.1.0-alpha) and Ruby 3.0.1. I verified the same issue still exists using that configuration.

---

We are working on upgrading a Rails 5 app and we were confused why a change in `config/initializers/new_framework_defaults_5_2.rb` didn't seem to be working. It was:

```ruby
Rails.application.config.action_controller.default_protect_from_forgery = true
```

It turns out we had older versions of a couple of gems that were causing `ActionController` to be loaded earlier than it should have been. 

#### Expected execution order

The expected execution order of the code is:

- `application.rb`
- initializers in `config/initializers`
- https://github.com/rails/rails/blob/main/actionpack/lib/action_controller/railtie.rb#L101-L107

When the code executes in this order, forgery is setup as expected. However, this is not the case if a gem accesses `ActionController::Base` prematurely by not using a railtie.

#### Actual execution order

When a gem accesses `ActionController::Base` without using a railtie containing something like `ActiveSupport.on_load(:action_controller_base)`, the execution order is:

- `application.rb`
- https://github.com/rails/rails/blob/main/actionpack/lib/action_controller/railtie.rb#L101-L107
- initializers in `config/initializers`

Since the initializers haven't run when the second item (`railtie.rb#L101-L107`) is executed, forgery protection isn't setup as expected. You can see a screenshot of my debuggers being hit in the unexpected order below:

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/543973/168491959-fed657d5-9a9f-4ec7-9f89-92d107289d17.png">

---

There are numerous other examples of this bug, as seen [here](https://github.com/rails/rails/issues/39855#issuecomment-659670294).

We believe the reason that this is happening is because gems are loaded between `application.rb` and the `config/initializers` files. Because of this, gems have a chance to access things too early and cause premature loading of Rails components.

We have come up with two conceptual ways to fix this.

#### 1. Move default overrides out of initializers

If default overrides were loaded at the same place as defaults, it could look something like this:

```ruby
# application.rb

...
load_defaults 5.0
load_default_overrides
...
```

```ruby
# elsewhere in Rails bootstrap or config object

def load_default_overrides
  Dir.glob('config/defaults/*.rb').each do |f|
    require f
  end
end
```

The overrides could then live in files like `config/defaults/5_2.rb`.

This solution would remove the chance for any gem to load between `load_defaults` being called and overrides being set.

#### 2. Raise on early loading

If a gem loads any of the rails components before Rails is ready for them to be loaded, Rails could raise an error.

The bug presented in this issue could affect any initializer in an application. Raising an error if Rails isn't done loading when one of the components is accessed would protect every initializer in the application.

### Main branch reproduction

I created a test gem with this code:

```ruby
# frozen_string_literal: true

require_relative "test_rails_initializers/version"

module TestRailsInitializers
  ActionController::Base.prepend Module.new
end
```

This code replicates the bug on the current main branch:

![image](https://user-images.githubusercontent.com/543973/168493558-1ef88c2d-7abe-4a8f-aa6a-a21c059295c5.png)

### System configuration
**Rails version**: 5.x all the way through main branch (currently 7.1.0-alpha)

**Ruby version**:
2.6 - 3.0.1 tested

**Comment by casperisfine** [comment]
Related: https://github.com/rails/rails/pull/44996
