### ISSUE TITLE
WebSocket connection failed: WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by salmagomaa** [rails/rails#45131]
I am facing a problem when the connected users be more than 2 users (2 channels not sessions)

The error is:
```
WebSocket connection  failed: WebSocket is closed before the connection is established.
```
Here you are the recent scenario we have:
1. Browser 1: Login with user 1 and create a post
2. Browser 2: Login with user 2
3. Browser 3: Login with user 3
--------------------------------------------------------------
5. Browser 2: Add a comment to the post created by user 1 in browser 1
6. Browser 3: Add a comment to the post created by user 1 in browser 1
--------------------------------------------------------------
7. Browser 1: Should receives the notifications of the two comments without refreshing
--------------------------------------------------------------
8. Browser 1: Reply for the comment added by user 2 in browser 2
9. Browser 1: Reply for the comment added by user 3 in browser 3
--------------------------------------------------------------
10. Browser 2: Should receives the notification of replying without refresh
11. Browser 3: Should receives the notification of replying without refresh
----------------------------------------------------------------
But unfortunately, I didn't receive any notifications
When I tried the same scenario using 2 users only, it works properly

Conclusion:
The real-time stops and websocket error appears depending on the number of connected users

Anyone can help me please?

**Comment by ghiculescu** [comment]
What version of Rails and ActionCable is this happening on?

**Comment by salmagomaa** [comment]
> What version of Rails and ActionCable is this happening on?

Rails 6.0.4.7

**Comment by palkan** [comment]
> WebSocket connection  failed: WebSocket is closed before the connection is established.

Could you please show the browser logs? (Ideally, console and networking). Server (Action Cable) logs could be helpful, too.

Does the problem persist after you disconnect all the users and try to connect 2 users again?
