### ISSUE TITLE
Delegator parent is never touched 

### ISSUE THREAD

**Issue by lazaronixon** [rails/rails#45152]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.datetime :created_at, null: false
    t.datetime :updated_at, null: false
  end

  create_table :profiles, force: true do |t|
    t.bigint :user_id
    t.string :profilable_type
    t.bigint :profilable_id

    #t.datetime :created_at, null: false
    #t.datetime :updated_at, null: false
  end

  create_table :doctors, force: true do |t|
    t.string :name

    #t.datetime :created_at, null: false
    #t.datetime :updated_at, null: false
  end

  create_table :patients, force: true do |t|
    t.string :name

    #t.datetime :created_at, null: false
    #t.datetime :updated_at, null: false
  end

  create_table :skills, force: true do |t|
    t.bigint :doctor_id
    t.string :name
  end
end

class User < ActiveRecord::Base
  has_one :profile
end

class Profile < ActiveRecord::Base
  delegated_type :profilable, types: %w[ doctor patient ]

  belongs_to :user, touch: true
end

class Patient < ActiveRecord::Base
  has_one :profile, as: :profilable, touch: true
end

class Doctor < ActiveRecord::Base
  has_one  :profile, as: :profilable, touch: true
  has_many :skills
end

class Skill < ActiveRecord::Base
  belongs_to :doctor, touch: true
end

class BugTest < Minitest::Test
  def test_touching_user_after_add_doctors_skill
    new_doctor  = Doctor.new name: "sebastian"
    new_profile = Profile.new profilable: new_doctor

    user = User.create!(profile: new_profile)

    # previously_doctor_updated_at  = user.profile.profilable.updated_at
    # previously_profile_updated_at = user.profile.updated_at
    previously_user_updated_at    = user.updated_at

    user.profile.profilable.skills.create!(name: "diabetes_management")

    # assert(previously_doctor_updated_at  != user.profile.profilable.reload.updated_at) # ok
    # assert(previously_profile_updated_at != user.profile.reload.updated_at) # ok
    assert(previously_user_updated_at    != user.reload.updated_at) # failed
  end
end
```

### Expected behavior
1 - When a doctors' skill is added, the user should be touched since the touch flow is skill -> doctor -> profile -> user. 
2 - If there's no timestamps on the doctor, the profile should be touched as well.

### Actual behavior
1 - When a doctor's skill is added, doctor and profile are touched, but not the user.
2 - If there's no timestamps on the doctor, the profile is not touched along with the user.

### System configuration
**Rails version**:
Rails 7.0.3

**Ruby version**:
Ruby ruby 3.1.1

**Comment by HParker** [comment]
> 1 - When a doctors' skill is added, the user should be touched since the touch flow is skill -> doctor -> profile -> user.

It seems to work for me if you change `has_one :profile` to `has_one :profile, touch: true`. and add timestamps to `doctor`

> 2 - If there's no timestamps on the doctor, the profile should be touched as well.

Can you point to some documentation or help me understand why you expect this behavior? I am not sure that would be expected behavior for `delegated_type`. For example, right now calling,

```ruby
user.profile.profilable.updated_at
```

I get,

```
/Users/hparker/code/rails/activemodel/lib/active_model/attribute_methods.rb:462:in `method_missing': undefined method `updated_at' for #<Doctor id: 1, name: "sebastian"> (NoMethodError)
Did you mean?  update
```

So I don't think I would expect `updated_at` on `profiles` to be updated even if `doctors` doesn't have timestamps.

**Comment by lazaronixon** [comment]
1 -  Ok, thanks. but is it not confuse ? We need to put touch in both sides ?
2 - If you take a look [here](https://api.rubyonrails.org/classes/ActiveRecord/DelegatedType.html), the example recommends not setting timestamps for delegated.
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/2651240/170146006-a1a2b8ce-fe00-400b-b704-7fdc2c5619a0.png">

**Comment by lazaronixon** [comment]
But you're right the documentation recommends to put touch on has_one
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/2651240/170146772-c08acefe-1e89-49da-88a1-6ffcbcdc457d.png">

**Comment by lazaronixon** [comment]
reopen
