### ISSUE TITLE
config/initializers/multi_db doesn't work

### ISSUE THREAD

**Issue by nate-at-gusto** [rails/rails#45162]
It doesn't insert the database selector middleware, because the railtie which inserts it has already run by the time the initializer is run.

## Repro 

[See repo here.](https://github.com/nate-at-gusto/multidb-dont-work)

```
bin/rails test test/integration/replica_test.rb 
```

**Comment by ghiculescu** [comment]
Related: https://github.com/rails/rails/pull/44996

If that PR isn't accepted, then `config.after_initializer` might fix it, here: https://github.com/rails/rails/blob/b24c44159c4dc5904c78d61b57a8728846d453a9/activerecord/lib/active_record/railtie.rb#L98

In the meantime, moving the config to `application.rb` (like it was before https://github.com/rails/rails/pull/43796) definitely works.

**Comment by eileencodes** [comment]
I know that we discussed in chat that order of config initializers has been a problem for awhile but I am 100% sure I tested this in an app when I implemented it. This leads me to believe something else changed between 6.1 and 7.0 that is causing all these initializers to now not work. 😕

**Comment by ghiculescu** [comment]
Trying to bisect this, but not having much luck yet.

`railties/test/application/configuration_test.rb`:

```ruby
    test "can get multi-db middleware from initializer" do
      app_file "config/initializers/multi_db.rb", <<-RUBY
        Rails.application.configure do
          config.active_record.database_selector = { delay: 2.seconds }
        end
      RUBY

      app "development"

      assert_includes Rails.application.config.middleware.map(&:name), "ActiveRecord::Middleware::DatabaseSelector"
    end

    test "can get multi-db middleware from application.rb" do
      add_to_config <<-RUBY
        config.active_record.database_selector = { delay: 2.seconds }
      RUBY

      app "development"

      assert_includes Rails.application.config.middleware.map(&:name), "ActiveRecord::Middleware::DatabaseSelector"
    end
```

On both `main` and `6-1-stable` the first test fails and the second test passes. I'm having some trouble getting `6-0-stable` to build atm so can't confirm if it works there.

**Comment by ghiculescu** [comment]
I did some poking around. I don't know if this helps at all but i want to brain dump so I can wrap up for the day. The main interesting thing is that the order that railties get evaluated in is defined here https://github.com/rails/rails/blob/55cee0331e1af4fb517291108045f39cb19dfd41/railties/lib/rails/application.rb#L558

This is the order on Rails 6.1, on 7 it's basically the same: `["I18n::Railtie", "ActiveSupport::Railtie", "ActionDispatch::Railtie", "ActiveModel::Railtie", "ActionController::Railtie", "ActiveRecord::Railtie", "GlobalID::Railtie", "ActiveJob::Railtie", "ActionMailer::Railtie", "Rails::TestUnitRailtie", "Sprockets::Railtie", "ActionView::Railtie", "ActiveStorage::Engine", "ActionCable::Engine", "ActionMailbox::Engine", "ActionText::Engine", "Turbolinks::Engine", "Webpacker::Engine", "AppTemplate::Application"]`

So all the railties, and then all the engines, as defined [here](https://github.com/rails/rails/blob/55cee0331e1af4fb517291108045f39cb19dfd41/railties/lib/rails/engine/railties.rb#L10).

https://gist.github.com/ghiculescu/8d36b09402daff400d3786f89964c7ca lists each railtie/engine and which initializers it adds. My debug code was

```ruby
    def railties_initializers(current) #:nodoc:
      initializers = []
      puts "railties is #{railties.to_a.map(&:class).map(&:name)}"
      puts "ordered_railties is #{ordered_railties.reverse.flatten.map(&:class).map(&:name)}"
      ordered_railties.reverse.flatten.each do |r|
        puts "r is #{r}"
        if r == self
          puts "adding #{current.map(&:name)}"
          initializers += current
        else
          puts "adding #{r.initializers.map(&:name)}"
          initializers += r.initializers
        end
      end
      initializers
    end
```

What's interesting is that `load_config_initializers` is not explicitly called by any of the railties. It is called basically as a side effect of all the engines. As a result it is called relatively late.

It seems to me like it should probably be called at a specified point, not randomly halfway through the loading of the frameworks.

**Comment by eileencodes** [comment]
I spent a long time on this today trying to determine when and how certain configs broke and the only thing I've come up with is that certain config initializations have broken since at least 6.0 and in Ruby 2.6 to to 3.0. This initializer predates 6.0 so I was testing with others that have been around for awhile.

For example calling `Rails.application.config.active_record.use_schema_cache_dump = false` in 6.1 and 6.0 raises an error that `use_schema_cache_dump` is undefined. I also see this if I set up the multi_db initializer - `database_selector` is undefined.

I can see why this is happening, the initializer in the Railtie runs before the initializer is loaded from config. `options` is never set so nothing else is set either. I attempted to use `after_initialize` with the Railtie and that didn't improve the situation.

I think the best course going forward is to drop the `config.active_record.database_selector` initializer that installs the middleware in the Railtie, and install it directly with the config initializer. PR incoming.

**Comment by eileencodes** [comment]
I've come to the conclusion that no one noticed before because we were using initializers less for this kind of thing. That's the only reasonable explanation I can come up with since it doesn't look like anything changed. That or this particular issue isn't related to the other issues we're seeing.

**Comment by eileencodes** [comment]
Decided to fix this differently in #https://github.com/rails/rails/pull/45368. Backported to 7-0-stable. It will be in the next release. In the mean time calling these intializers from config/application.rb or config/environments works fine.

**Comment by altjx** [comment]
Thanks @eileencodes this just saved me from a long, miserable 2-3 days of troubleshooting, lol.
