### ISSUE TITLE
CI against MariaDB has been failing

### ISSUE THREAD

**Issue by yahonda** [rails/rails#45167]
### Steps to reproduce

It reproduces at Rails CI environment. 

- The first failing build
https://buildkite.com/rails/rails/builds/86711#ebc53e55-14aa-4abf-819b-5928cbbe9938

- The last successful build
https://buildkite.com/rails/rails/builds/86701#2f3a5396-4237-47a5-b27c-cf6774c90bb6

### Expected behavior
CI against MariaDB should work.

### Actual behavior
https://buildkite.com/rails/rails/builds/86711#ebc53e55-14aa-4abf-819b-5928cbbe9938/1174-1175

```sql
mysqladmin: connect to server at 'mysql' failed
--
  | error: 'Unknown MySQL server host 'mysql' (-2)'
  | Check that mysqld is running on mysql and that the port is 3306.
  | You can check this by doing 'telnet mysql 3306'
  | mysqladmin: connect to server at 'mysql' failed
  | error: 'Unknown MySQL server host 'mysql' (-2)'
  | Check that mysqld is running on mysql and that the port is 3306.
  | You can check this by doing 'telnet mysql 3306'
  | ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (-2)
  | ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (-2)
  | ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (-2)
  | ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (-2)
  | ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (-2)
  | ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (-2)
  | ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (-2)


```
### System configuration
**Rails version**: main branch

**Ruby version**:3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-linux]

**Comment by yahonda** [comment]
It may be related to the latest version of MariaDB 10.8.2 the first GA version of 10.8 is chosen by "mariadb:latest" tag.

https://github.com/rails/buildkite-config/blob/a0c0052fb8e07cffa0b546ff4fc1e113f84bf304/pipeline-generate#L252

Let me investigate.

**Comment by yahonda** [comment]
Opened https://github.com/MariaDB/mariadb-docker/issues/434

**Comment by yahonda** [comment]
Current workaround is replacing `"mariadb:latest"` with `"mariadb:10.7"`. 

https://github.com/rails/buildkite-config/blob/a0c0052fb8e07cffa0b546ff4fc1e113f84bf304/pipeline-generate#L252

I'll open a pull request at https://github.com/rails/buildkite-config until  https://github.com/MariaDB/mariadb-docker/issues/434 is resolved.

**Comment by yahonda** [comment]
Investigated this issue https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1135513246 and found how to address it.

Here are 3 options. I prefer `1. Upgrade DOCKER_VERSION at BuildKite to 20.10.10 or higher`. 

1. Upgrade DOCKER_VERSION at BuildKite to 20.10.10 or higher
Now it is running `20.10.9`.
https://buildkite.com/rails/rails/builds/86711#ebc53e55-14aa-4abf-819b-5928cbbe9938/3-10

```
export DOCKER_VERSION="20.10.9"
```

2. Lock MariaDB version to "mariadb:10.7"
3. Ask MariaDB Docker maintainer to release "release a focal based mariadb:10.8/latest."

I'm not sure how to request BuildKite to upgrade the Docker version to 20.10.10.
Please advise.

**Comment by matthewd** [comment]
I've merged https://github.com/rails/buildkite-config/pull/17 for now, as the simplest option to keep things moving & green, pending option 1. :+1:
