### ISSUE TITLE
Rails.configuration.to_prepare

### ISSUE THREAD

**Issue by fxn** [rails/rails#45176]
(Moved from https://github.com/fxn/zeitwerk/issues/217).

I'm updating from redmine 4 to redmine 5. When updating a plugin, it didn't work. I think the plugin's libraries couldn't be loaded. In the plugin's init.rb file, it's configured below
`Rails.configuration.to_prepare do #ActiveSupport::Reloader.to_prepare`
    `User.send :include, Patch::UserPatch`
    `ApplicationController.send :include, Patch::ApplicationControllerPatch`
`end`
So, what will be replaced for Rails.configuration.to_prepare in Zeitwerk?

**Comment by fxn** [comment]
@ttqtrang146 I am not familiar with Redmine plugins. Could you give me more information please? Is the plugin open source? If so, can you link to the plugin and that `init.rb`? In what sense isn't the plugin working?

**Comment by sanak** [comment]
@ttqtrang146 (CC: @fxn)
I use `Rails.application.config.after_initialize` in Redmine 5.0 as alternative of `Rails.configuration.to_prepare` in Redmine 4.x.
- https://www.redmine.org/issues/36245#note-14
- https://github.com/gtt-project/redmine_custom_fields_groups/pull/14

**Comment by fxn** [comment]
@sanak I see https://github.com/gtt-project/redmine_custom_fields_groups/pull/14 is merged. Can we close this issue?

**Comment by sanak** [comment]
@fxn @ttqtrang146
Yes, I think that we can close this issue.

**Comment by fxn** [comment]
Awesome :).
