### ISSUE TITLE
Hash#to_xml generates invalid XML when keys are numbers

### ISSUE THREAD

**Issue by lexafesyk** [rails/rails#45170]
### Steps to reproduce
Call to_xml on a hash that has integers/stringified integers keys.

```ruby
> hash = { 1 => 'foo' }
=> {1=>"foo"}
> hash.to_xml
=> "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<hash>\n  <1>foo</1>\n</hash>\n"

> hash = { '1' => 'foo' }
=> {"1"=>"foo"}
> hash.to_xml
=> "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<hash>\n  <1>foo</1>\n</hash>\n"
```

### Expected behavior
Valid XMLs expected

### Actual behavior
Both generated XMLs are invalid since "1" is not a valid XML element. Element names must start with a letter or underscore. 

### System configuration
**Rails version**: 6.1.5.1

**Ruby version**: 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]

**Comment by flavorjones** [comment]
@lexafesyk Thanks for opening this issue. Can you help me understand exactly what markup you would expect to be emitted given the example input hashes?

It doesn't seem easy to interpret the user's intent in this case, and so in a sense perhaps the current implementation, to make a best-efforts attempt at serialization and force the user to provide valid input, is the most appropriate compromise. I might even be convinced that `#to_xml` should raise an exception in cases where the emitted markup is obviously invalid.

**Comment by flavorjones** [comment]
I don't think there is a reasonable way to guess at the user's intent. Your suggestion above assumes "attr" or some other tag name which would be hardcoded and doesn't appear in the input hash. I think that violates the principle of least surprise and I would prefer the caller to be aware of the translation mechanism and take the responsibility of ensuring keys are valid XML tag names.

I think a better idea might be to raise an exception if a hash key is not a valid [XML tag name](https://www.w3.org/TR/xml/#NT-Name), perhaps as opt-in behavior.

However, I'm not sure what problem we're actually solving. The `#to_xml` method is doing what it says on the tin: it creates tags named after the hash keys, and those names are the responsibility of the caller. Can you help me more deeply understand by providing your use case? Is this untrusted input, or trusted input?

**Comment by flavorjones** [comment]
After looking at the code, I think a better place to enforce validation would be inside the `builder` gem (because Active Support's `#to_xml` helper is a wrapper around that gem).

Perhaps you would be willing to open an issue at https://github.com/tenderlove/builder for discussion there?

**Comment by lexafesyk** [comment]
Thank you, I will try to raise an issue there.
