### ISSUE TITLE
ActiveSupport::Reloader.to_prepare do runs before autoload_paths

### ISSUE THREAD

**Issue by rgaufman** [rails/rails#45197]
### Steps to reproduce
I have this in my application.rb
```
class Application < Rails::Application
    config.load_defaults 7.0
    config.autoload_paths += Dir["#{config.root}/lib/**/"]
    ...
```

I have this in a file config/initializers/good_job.rb:

```
ActiveSupport::Reloader.to_prepare do
  Cameras::Hikvision
end
```

I have this in my ./lib/cameras/hikvision.rb:
```
class Cameras::Hikvision
end
```

When I start my app, I see:

```
uninitialized constant Cameras::Hikvision
```

### Expected behaviour

I am expecting Rails to load the autoload_paths (which include "#{config.root}/lib/**/") before loading my initializers, which depend on the former.

### Actual behaviour

It seems to first load the initializers before my libraries.

### System configuration
**Rails version**: 7.0.3
**Ruby version**: 3.1.2

Any ideas? - Maybe I need to use something other than ActiveSupport::Reloader.to_prepare?

**Comment by skipkayhil** [comment]
I think if you add `lib/cameras` to the autoload path then the rest of the path needs to be `cameras/hikvision.rb` instead of `hikvision/hikvision.rb`. I would expect `hikvision/hikvision.rb` to define `Hikvision::Hikvision`

**Comment by rgaufman** [comment]
Zeitwerk was the one that recommend these paths, I actually added a lib/cameras/common.rb and added Cameras::Hikvision to inherit from this. This is working well, I can run rails c and I access Cameras::Hikvision no problem, this works in all my code including with rails runner. However initialiazers cannot find these classes.

**Comment by rgaufman** [comment]
@skipkayhil I moved the files as you recommended, which make more sense, Zeitwerk is still happy. I updated the description to reflect these changes. I restarted rails and I still see the same:

```uninitialized constant Cameras::Hikvision```

**Comment by rgaufman** [comment]
I'm trying to figure out what's going wrong, I added this to my application.rb:

```
config.eager_load_paths += Dir["#{config.root}/lib/**/"]
```

However now, when I check zeitwerk, I see:

```
$ bin/rails zeitwerk:check
Hold on, I am eager loading the application.
expected file lib/cameras/common.rb to define constant Common
```

Why does zeitwek think this file needs to define Common? - it currently defines class Cameras::Common which I believe is correct?

**Comment by skipkayhil** [comment]
By adding `lib/**` to the auto load path, you're saying `lib/cameras` is the base path to load from, so `lib/cameras/hikvision.rb` should define a top level `Hikvision`.

To do `Cameras::Hikvision`, you either need `lib/**` added to `autoload_paths` and the path as `lib/cameras/cameras/hikvision.rb` OR `lib` added to `autoload_paths` and the path as `lib/cameras/hikvision.rb‘.

**Comment by rgaufman** [comment]
Thank you, that was super helpful! - I ended up with this:

```
    config.autoload_paths << "#{Rails.root}/lib"
    config.eager_load_paths << "#{Rails.root}/lib"
    config.autoload_paths << "#{Rails.root}/lib/network"
    config.eager_load_paths << "#{Rails.root}/lib/network"
```

I then followed all the instructions from:

```
$ bin/rails zeitwerk:check
```

Any now everything is working as expected, thank you!
