### ISSUE TITLE
How to get blob service_url in Javascript

### ISSUE THREAD

**Issue by JoaoPedroAssis** [rails/rails#45225]
### Steps to reproduce
Hey, I'm trying to fetch images from S3 in a JS script, which reads from a rich text editor html and extracts images src's. The problem is that when i use js `fetch`function in the redirect url, i have a cors issue and cannot get the image (that will be later converted to base64)

How can I download the blob directly from S3 in JS?

**Comment by p8** [comment]
Hey @JoaoPedroAssis, :wave:
Sorry, we reserve the issue tracker for issues only.
Please use the [rubyonrails-talk](https://discuss.rubyonrails.org/c/rubyonrails-talk/7)
forum where a wider community can help you.
