### ISSUE TITLE
Where clauses with arrays including nil aren't removed by unscope

### ISSUE THREAD

**Issue by jmeberlein** [rails/rails#45227]
### Steps to reproduce
```ruby
ActiveRecord::Schema.define do
  create_table :books, force: true do |t|
    t.string :genre
    t.string :title
  end
end

class Book < ActiveRecord::Base
  attr_accessible :genre, :title
end

Book.create!(genre: :mystery, title: 'A Study in Scarlet')
Book.create!(genre: :romance, title: 'Pride and Prejudice')
Book.create!(genre: nil, title: 'An empty book')

Book.where(genre: [nil, :romance]).unscope(where: :genre)
```

### Expected behavior
It should return all three books, regardless of genre

### Actual behavior
The SQL query still includes `WHERE ("books"."genre" = 'romance' OR "books"."genre" IS NULL)` and doesn't return A Study in Scarlet

### System configuration
**Rails version**: 4.2.11.3

**Ruby version**: 2.6.6

**Comment by nvasilevski** [comment]
>Rails version: 4.2.11.3

I'm afraid this won't be getting a bugfix unless it's reproducible on a never version or `main`
I can double check

**Comment by nvasilevski** [comment]
Not reproducible on `main` nor on `7-0-stable` 
A reproduction script, if someone is interested:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "7-0-stable"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :books, force: true do |t|
    t.string :genre
    t.string :title
  end
end

class Book < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    Book.create!(genre: :mystery, title: 'A Study in Scarlet')
    Book.create!(genre: :romance, title: 'Pride and Prejudice')
    Book.create!(genre: nil, title: 'An empty book')
    
    assert_equal 3, Book.where(genre: [nil, :romance]).unscope(where: :genre).to_a.size
  end
end
```

**Comment by ghiculescu** [comment]
Thanks for the report @jmeberlein but we [only take issues in the current Rails version](https://guides.rubyonrails.org/maintenance_policy.html). I'm going to close this for now, but if there is an issue in the current Rails version please let me know and I can reopen.

**Comment by jmeberlein** [comment]
@ghiculescu Fair enough. I actually tested across a handful of versions, and it looks like this was fixed around Rails 6 anyway
