### ISSUE TITLE
ActiveSupport::ParameterFilter in config/initializers/**.rb cause NameError: uninitialized constant ActiveSupport::ParameterFilter in Rails7, but not cause in Rails6

### ISSUE THREAD

**Issue by hamilton-keisuke** [rails/rails#45253]
Excuse me. I'm sorry for your busy schedule. 
There is a problem that I just don't understand.

My rails project is using Sentry.

I am using `ActiveSupport::ParameterFilter` in `config/initializers/sentry.rb` as shown below.

https://docs.sentry.io/platforms/ruby/guides/rails/configuration/filtering/#using-platformidentifier-namebefore-send-

In my project, I'm working on updating from rails v6 to v7.
When I ran the `$ rspec`, I didn't get any error in v6, but when I updated v7, I got the following error.
(RSpec and Sentry versions are not updated.)

```
An error occurred while loading ./spec/helpers/posts_helper_spec.rb.
Failure/Error: require_relative '../config/environment'

NameError:
  uninitialized constant ActiveSupport::ParameterFilter
# ./config/initializers/content_security_policy.rb:6:in `<main>'
# /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
# /usr/local/bundle/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
# /usr/local/bundle/gems/railties-7.0.3/lib/rails/engine.rb:667:in `block in load_config_initializer'
# /usr/local/bundle/gems/activesupport-7.0.3/lib/active_support/notifications.rb:208:in `instrument'
# /usr/local/bundle/gems/railties-7.0.3/lib/rails/engine.rb:666:in `load_config_initializer'
# /usr/local/bundle/gems/railties-7.0.3/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
# /usr/local/bundle/gems/railties-7.0.3/lib/rails/engine.rb:619:in `each'
# /usr/local/bundle/gems/railties-7.0.3/lib/rails/engine.rb:619:in `block in <class:Engine>'
# /usr/local/bundle/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `instance_exec'
# /usr/local/bundle/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `run'
# /usr/local/bundle/gems/railties-7.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'
# /usr/local/bundle/gems/railties-7.0.3/lib/rails/initializable.rb:50:in `each'
# /usr/local/bundle/gems/railties-7.0.3/lib/rails/initializable.rb:50:in `tsort_each_child'
# /usr/local/bundle/gems/railties-7.0.3/lib/rails/initializable.rb:60:in `run_initializers'
# /usr/local/bundle/gems/railties-7.0.3/lib/rails/application.rb:372:in `initialize!'
# ./config/environment.rb:5:in `<top (required)>'
# ./spec/rails_helper.rb:4:in `require_relative'
# ./spec/rails_helper.rb:4:in `<top (required)>'
# ./spec/helpers/posts_helper_spec.rb:1:in `<top (required)>'
```

I know that adding `require active_support/parameter_filter` doesn't cause this errors, but I don't understand why this happens.

Cound you please tell me why the error did not occur in Rails6 and the error occurred in Rails7.

### Steps to reproduce

It reproduce in my sample repository below.
(Sentry is not included for simplicity.)

https://github.com/hamilton-keisuke/activesupport_parameter_filter_probrem_sample

### System configuration
**Rails version**:
7.0.3
(no error happen in 6.1.6)

**Ruby version**:
3.0.1

**rspec-rails**
5.1.2

**Comment by nvasilevski** [comment]
I think this is related to autoloadable constant used in an initializer 
would you mind trying to wrap the code that references the constant in a `to_prepare` block, like:
```ruby
Rails.application.config.to_prepare do
  filter = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
  puts "☆ #{filter.inspect}"
end
```
<img width="684" alt="image" src="https://user-images.githubusercontent.com/5512772/171878625-a3ca6efa-294b-4fea-908d-7b98a2beef7f.png">

https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#use-case-1-during-boot-load-reloadable-code

**Comment by hamilton-keisuke** [comment]
@nvasilevski 

I’m grateful for your advice!
It turns out that adding `to_prepare` block cause no error!

> ```
> Rails.application.config.to_prepare do
>   filter = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
>   puts "☆ #{filter.inspect}"
> end
> ```

And I found this page 👉 [Autoloading in Rails 7, get ready!](https://rubyonrails.org/2021/9/3/autoloading-in-rails-7-get-ready)
It seems that the specifications of autoload at app booting have changed in version 7.


By the way, I turned out that rails cannot autoload from the autoload paths while booting.
But when `$rails s`, why doesn't the same error occur (without `to_prepare` block)?
Is the booting procedure different between `$ rspec` and `$ rails s`?

(`autoload_paths` doesn't seem to make a critical difference between `$ rspec` and `$ rails s`.
I confirmed that by adding `puts ActiveSupport::Dependencies.autoload_paths` to `config/initializers/**` any file.)

```sh
# rspec
☆ This is ActiveSupport::Dependencies.autoload_paths ☆
/app/app/channels
/app/app/controllers
/app/app/controllers/concerns
/app/app/helpers
/app/app/jobs
/app/app/mailers
/app/app/models
/app/app/models/concerns
/usr/local/bundle/gems/actionmailbox-7.0.3/app/controllers
/usr/local/bundle/gems/actionmailbox-7.0.3/app/jobs
/usr/local/bundle/gems/actionmailbox-7.0.3/app/models
/usr/local/bundle/gems/activestorage-7.0.3/app/controllers
/usr/local/bundle/gems/activestorage-7.0.3/app/controllers/concerns
/usr/local/bundle/gems/activestorage-7.0.3/app/jobs
/usr/local/bundle/gems/activestorage-7.0.3/app/models

```

```sh
# rails s -b 0.0.0.0
=> Booting Puma
=> Rails 7.0.3 application starting in development 
=> Run `bin/rails server --help` for more startup options

☆ This is ActiveSupport::Dependencies.autoload_paths ☆
/app/app/channels
/app/app/controllers
/app/app/controllers/concerns
/app/app/helpers
/app/app/jobs
/app/app/mailers
/app/app/models
/app/app/models/concerns
/usr/local/bundle/gems/actionmailbox-7.0.3/app/controllers
/usr/local/bundle/gems/actionmailbox-7.0.3/app/jobs
/usr/local/bundle/gems/actionmailbox-7.0.3/app/models
/usr/local/bundle/gems/activestorage-7.0.3/app/controllers
/usr/local/bundle/gems/activestorage-7.0.3/app/controllers/concerns
/usr/local/bundle/gems/activestorage-7.0.3/app/jobs
/usr/local/bundle/gems/activestorage-7.0.3/app/models
/app/spec/mailers/previews

Puma starting in single mode...
* Puma version: 5.6.4 (ruby 3.0.1-p64) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 367
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
```

**Comment by nvasilevski** [comment]
>But when $rails s, why doesn't the same error occur (without to_prepare block)?
Is the booting procedure different between $ rspec and $ rails s?

To be honest I'm not sure, my expectation and in my experience the problem should exist at any time the application boots, whether it's for tests, `rails c` or `rails `
Also I'm curious if https://github.com/rails/rails/blob/838d3f73ddd4b333295b7cd942505ce775d03ee0/railties/lib/rails/application/finisher.rb#L51 this deprecation should have caught the violation in advance. 
But I have to admit I haven't deeply looked into the area yet so I'm basically guessing
