### ISSUE TITLE
Customize Generator Docs Missing Links

### ISSUE THREAD

**Issue by philippneugebauer** [rails/rails#45254]
from: https://guides.rubyonrails.org/v7.0/generators.html#customizing-your-workflow-by-changing-generators-templates
> If you generate another resource, you can see that we get exactly the same result! This is useful if you want to customize your scaffold templates and/or layout by just creating edit.html.erb, index.html.erb and so on inside lib/templates/erb/scaffold.

I wonder why we don't have some kind of links to the [current files](https://github.com/rails/rails/tree/5257da7bb543e2b5a51da72a3e4bb77bf96eaefc/railties/lib/rails/generators/erb/scaffold/templates) here so you can easily customize based on them? I was searching for some while and just found it after searching for "display: block" in the rails repository.

**Comment by skipkayhil** [comment]
Sounds like a helpful change, would you like to create a PR?

**Comment by philippneugebauer** [comment]
I am not sure if my linking is correct, but I am happy to apply changes
