### ISSUE TITLE
Rails.cache.read() is not working as expected in Rails 7.0.3

### ISSUE THREAD

**Issue by AfolabiOlaoluwa** [rails/rails#45267]
Is there anything I am missing? Rails.cache.read() is not behaving as expected. Is there any configurations I need to do?
### Steps to reproduce

```ruby
rails c
Rails.cache.write("my-cache-key", 123)
=> true
```

### Expected behavior
```ruby
Rails.cache.read("my-cache-key")
=> 123
```

### Actual behavior
```ruby
Rails.cache.read("my-cache-key")
=> nil
```

### System configuration
**Rails 7.0.3**

**Ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]**:

### Image
<img width="448" alt="Screenshot 2022-06-04 at 19 00 07" src="https://user-images.githubusercontent.com/15254043/172020488-b7046c36-baf4-4848-8910-454514f27ad3.png">

**Comment by fatkodima** [comment]
Which cache store are you using?
Can you create a minimal reproduction script using [this template](https://github.com/rails/rails/blob/main/guides/bug_report_templates/generic_gem.rb)?

**Comment by byroot** [comment]
I'm gonna assume `null_store` is being used and close the issue. If that's not the case please comment back with more information and I'll re-open.
