### ISSUE TITLE
ActiveSupport: MessageEncryptor rotation fails to decrypt 'nil' values

### ISSUE THREAD

**Issue by sbosio** [rails/rails#45263]
### Steps to reproduce
Create two instances of MessageEncryptor. The first one with only an old secret and the second one with a new secret. Add to the second one another rotation with the old secret (this is a standard scenario when rotating secrets).

The second encryptor will be able to decrypt any data encrypted with the old secret, except for `nil` values, where it will raise an exception.

#### Test case
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activesupport", "7.0.3"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    old_secret = SecureRandom.base64(24)
    old_encryptor = ActiveSupport::MessageEncryptor.new old_secret

    current_secret = SecureRandom.base64(24)
    current_encryptor = ActiveSupport::MessageEncryptor.new current_secret
    current_encryptor.rotate old_secret

    # Old encryptor roundtrips a 'nil' value correctly
    assert_nil old_encryptor.decrypt_and_verify(old_encryptor.encrypt_and_sign(nil))

    # New encryptor roundtrips a 'nil' value correctly
    assert_nil current_encryptor.decrypt_and_verify(current_encryptor.encrypt_and_sign(nil))

    # Old encryptor cannot decrypt data encrypted with the current secret
    assert_raises(ActiveSupport::MessageVerifier::InvalidSignature) do
      old_encryptor.decrypt_and_verify(current_encryptor.encrypt_and_sign("test"))
    end

    # New encryptor correctly decrypts data encrypted with the old secret (being rotated)
    assert_equal "test", current_encryptor.decrypt_and_verify(old_encryptor.encrypt_and_sign("test"))

    # New encryptor should be able to decrypt a 'nil' value encrypted with the old secret --THIS FAILS--
    assert_nil current_encryptor.decrypt_and_verify(old_encryptor.encrypt_and_sign(nil))
  end
end
```

#### Possible root cause
The [method `verified`](https://github.com/rails/rails/blob/3872bc0e54d32e8bf3a6299b0bfe173d94b072fc/activesupport/lib/active_support/message_verifier.rb#L152) of MessageVerifier uses the special value `nil` to signal some error conditions to the caller, but `nil` is also a valid message itself, so the [`verify` method](https://github.com/rails/rails/blob/3872bc0e54d32e8bf3a6299b0bfe173d94b072fc/activesupport/lib/active_support/message_verifier.rb#L177) interprets this as a failure and raises.

### Expected behavior
A `nil` value encrypted with an old secret should be correctly decrypted as `nil` by an encryptor that has the old secret available as a rotation.

### Actual behavior
An `ActiveSupport::MessageVerifier::InvalidSignature` exception is raised.

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 2.7.5

**Comment by sampatbadhe** [comment]
Hello @yahonda @sbosio 

I attempted to resolve the above mentioned issue, could you please take a look at the PR https://github.com/rails/rails/pull/45266
