### ISSUE TITLE
Regression: Setting datetime inside Time#use_zone does not work

### ISSUE THREAD

**Issue by DanielHeath** [rails/rails#45270]
### Steps to reproduce

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.datetime :publish_after
  end
end

class Post < ActiveRecord::Base
end


class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    Time.use_zone("Perth") do
      post.publish_after = '2015-03-02 09:00:00.000000000 +0000'
    end

    assert_equal "2015-03-02 09:00:00 AWST", post.publish_after.to_s
  end
end

```

### Expected behavior

The timezone specified (Perth) is used

### Actual behavior

The timezone used is UTC

### System configuration

**Rails version**:
`rails 7.1.0.alpha (was 6.1.6) from https://github.com/rails/rails.git (at main@e494efd)`

**Ruby version**:
`ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]`

**Comment by fatkodima** [comment]
The bug report fails for me on `6.1.6` too.

**Comment by ghiculescu** [comment]
For reference, https://github.com/rails/rails/issues/28877, https://github.com/rails/rails/pull/31140

**Comment by ghiculescu** [comment]
I'm not sure that your test code is correct.

```
-"2015-03-02 09:00:00 AWST"
+"2015-03-02 09:00:00 UTC"
```

I think this is correct, because you are setting a time with an explicit UTC offset (`+0000`).

More generally the test case is tricky because it's lacking a few things a real Rails app would have:

```ruby
ActiveRecord::Base.time_zone_aware_attributes = true
ActiveRecord.default_timezone = :utc # or whatever you set this too
Time.zone_default = "UTC # Time.find_zone!(app.config.time_zone)
```

Maybe it would be better to make a simple replication app to demonstrate the issue, then we can go from there in trying to fix it.

I will say that if you are working across multiple time zones and you have specific models that should be in specific time zones, Active Record doesn't make this very easy. We use a patch to force time zone casting on write, and we read the time zone from the model or an associated (eg the user that owns it).

If you can describe your use case a bit more I can probably give you some more targeted advice.

**Comment by DanielHeath** [comment]
Thanks for the tip RE `ActiveRecord::Base.time_zone_aware_attributes` - that is true in the real app.

> If you can describe your use case a bit more I can probably give you some more targeted advice.

So, we're representing events in a local timezone (an event in Melbourne has its start time recorded using AEST so that it's correct on the day with respect to daylight savings time).

With the full app running, it's easy to drop into a debugger and verify that on 6.1.6 the string `"2015/03/02 9:00 am"` is coerced into `2015-03-02 09:00:00.000000000 +1100`. Switching to 7.0.3, that same string is coerced into `2015-03-02 09:00:00.000000000 +0000`

Sorry for sending that test case through without more checking, that was sloppy of me.

I'll do a bit more digging and see if I can get a minimal test case together.

**Comment by ghiculescu** [comment]
Cool, that sounds promising. Feel free to tag me in when you have a more firm replication.

**Comment by DanielHeath** [comment]
Got it! Updated test case that passes in rails 6 and fails in rails 7, and an explanation of why.

```# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "rails", github: "rails/rails", branch: "v6.1.6"
  gem "rails", github: "rails/rails"
  gem "pg"
  gem "byebug"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "bugreport")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.time_zone_aware_attributes = true

ActiveRecord::Schema.define do
  connection.execute <<-SQL
    DROP TABLE IF EXISTS public.courses;
    CREATE TABLE public.courses (
      id bigint NOT NULL,
      start_date timestamp with time zone
    );

    CREATE SEQUENCE public.courses_id_seq
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1;
    ALTER SEQUENCE public.courses_id_seq OWNED BY public.courses.id;
    ALTER TABLE ONLY public.courses ALTER COLUMN id SET DEFAULT nextval('public.courses_id_seq'::regclass);
    ALTER TABLE ONLY public.courses
      ADD CONSTRAINT courses_pkey PRIMARY KEY (id);
  SQL
end

class Course < ActiveRecord::Base
end

# In rails 7, the start_date attribute has a cast_type.type of
# :timestamptz which is not in ActiveRecord::Base.time_zone_aware_types

# In rails 6, it has a type of :datetime

# Uncomment the following line to fix in rails 7
# ActiveRecord::Base.time_zone_aware_types += [:timestamptz]

class BugTest < Minitest::Test

  def test_cast_in_zone
    Course.delete_all
    Time.use_zone("Perth") do
      Course.create!(start_date: '2015/03/02 9:00 am')
      assert_equal "2015-03-02 09:00:00 +0800", Course.last.start_date.to_s
    end
  end

  def test_cast_out_of_zone
    Course.delete_all
    Time.use_zone("Perth") do
      Course.create!(start_date: '2015/03/02 9:00 am')
    end

    # Irrelevant formatting change between 6 and 7
    if Rails.version =~ /^7/
      assert_equal "2015-03-02 01:00:00 UTC", Course.last.start_date.to_s
    else
      assert_equal "2015-03-02 01:00:00 +0000", Course.last.start_date.to_s
    end

  end
end
```

**Comment by ghiculescu** [comment]
Nice find. It seems like https://github.com/rails/rails/pull/44601 will fix this.
