### ISSUE TITLE
Rails.cache uses 6.1 coder when 7.0 configuration defaults are loaded

### ISSUE THREAD

**Issue by dinjas** [rails/rails#45289]
Sorry I am not providing a script below - wasn't sure how to best illustrate the issue in a test given the lack of public APIs here.

### Steps to reproduce

1. Set `config.cache_store = :file_store, 'tmp/cache'` in environment file (eg. `config/environments/development.rb`)
2. Load `bin/rails console` in 7.0.x Rails application
3. Note that `Rails.cache.instance_variable_get(:@coder)` returns `ActiveSupport::Cache::Coders::Rails61Coder`
4. Note that `Rails.cache.class.new('tmp/cache').instance_variable_get(:@coder)` returns `ActiveSupport::Cache::Coders::Rails70Coder`

The problem seems to be that `Rails.cache` is initialized before the app configuration is loaded. The default coder is 
[hardcoded to 6.1](https://github.com/rails/rails/blob/3872bc0e54d32e8bf3a6299b0bfe173d94b072fc/activesupport/lib/active_support/cache.rb#L38) but is overridden when the [app configuration is loaded](https://github.com/rails/rails/blob/ad409d5c3a7dbc1c16b5583d7fa9248099bf5360/railties/lib/rails/application/configuration.rb#L228).

This can be worked around by manually setting `ActiveSupport::Cache.format_version = 7.0` before the app is initialized, or by re-initializing `Rails.cache` after the app configuration is loaded.

[The configuration docs](https://guides.rubyonrails.org/configuring.html#config-active-support-cache-format-version) seemed to indicate no special handling would be needed to use the 7.0 serializer. 

### Expected behavior

When `application.rb` uses `load_defaults 7.0` and doesn't override the `cache_format_version`, `Rails.cache` should use the 7.0 cache coder.

### Actual behavior

When `application.rb` uses `load_defaults 7.0` and doesn't override the `cache_format_version`, `Rails.cache` use the 6.1 cache coder by default.

### System configuration

I've seen this using `FileStore` and `NullStore`, but have not looked at the behavior of the other cache store types.

**Rails version**: 
7.0.3

**Ruby version**: 
3.0.4

**Comment by ghiculescu** [comment]
Thanks for the report. I can replicate the issue in some tests that would go [here](https://github.com/rails/rails/blob/main/railties/test/application/configuration_test.rb)

```ruby
    test "cache_format_version in a new app" do
      add_to_config <<-RUBY
        config.cache_store = :null_store
      RUBY
      app "development"

      assert_equal ActiveSupport::Cache::Coders::Rails70Coder, Rails.cache.instance_variable_get(:@coder) # fails, gets ActiveSupport::Cache::Coders::Rails61Coder instead
    end

    test "cache_format_version with explicit 7.0 defaults" do
      add_to_config <<-RUBY
        config.cache_store = :null_store
      RUBY
      remove_from_config '.*config\.load_defaults.*\n'
      add_to_config 'config.load_defaults "7.0"'
      app "development"

      assert_equal ActiveSupport::Cache::Coders::Rails70Coder, Rails.cache.instance_variable_get(:@coder) # fails, gets ActiveSupport::Cache::Coders::Rails61Coder instead
    end

    test "cache_format_version with 6.1 defaults" do
      add_to_config <<-RUBY
        config.cache_store = :null_store
      RUBY
      remove_from_config '.*config\.load_defaults.*\n'
      add_to_config 'config.load_defaults "6.1"'
      app "development"

      assert_equal ActiveSupport::Cache::Coders::Rails61Coder, Rails.cache.instance_variable_get(:@coder)
    end
```

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/45293 gets the tests passing. Could you test it out?

**Comment by dinjas** [comment]
@ghiculescu - awesome, thanks for taking a look at it so quickly. The PR seems to fix what I was experiencing.
