### ISSUE TITLE
link_to with "turbo_method: :delete" triggers DELETE request for consecutive redirect (instead of GET)

### ISSUE THREAD

**Issue by stomar** [rails/rails#45292]
In a nested resource scenario this might lead to unwanted deletion of the "parent" resource with all its dependent resources when only a dependent resource was meant to be deleted. E.g. for articles with comments, deleting a comment might cause the deletion of the relevant article (and all its other comments).

### Steps to reproduce

I worked through the example in the [Getting Started guide](https://guides.rubyonrails.org/getting_started.html#deleting-comments), and stumbled over a somewhat surprising behavior when deleting a comment from an article.

Relevant code in `app/views/articles/show.html.erb`:

```ruby
  <li><%= link_to "Destroy", article_path(@article), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %></li>
```

Relevant code in `app/controllers/comments_controller.rb`:

```ruby
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other  # or: status: 303
  end
```

At some time I omitted the explicitly given `status` option, using the following line:

``` ruby
    redirect_to article_path(@article)
``` 

Similar to other occurrences of `redirect_to` without `status` in the code examples of the Getting Started guide.

### Expected behavior

After clicking on "Destroy" the comment should be deleted and the article page should be displayed (regardless of the given status).

### Actual behavior

Without the `status` option, the `redirect_to` triggers a DELETE request for the article instead of a GET request, thereby also **deleting the article and all its other comments** (when `has_many :comments, dependent: :destroy` is specified in the Article model), instead of only deleting the intended comment. See also the relevant lines from the log further below.

I must note that I have not much experience with Rails, and know absolutely nothing about the `turbo-` stuff, but it seems to me this is a **serious problem**. If I am mistaken, then at least the guide should clearly state the **crucial importance** of using the `status: :see_other` option with the redirect in this case.

Excerpt from the log:

```
Started DELETE "/articles/10/comments/18" for ::1 at 2022-06-07 [...]
Processing by CommentsController#destroy as TURBO_STREAM
[...]
Redirected to http://localhost:3000/articles/10
Completed 302 Found in 23ms (ActiveRecord: 10.6ms | Allocations: 3850)

Started DELETE "/articles/10" for ::1 at 2022-06-07 [...]
Processing by ArticlesController#destroy as TURBO_STREAM
```

### System configuration

**Rails version**: Rails 7.0.3

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by faqndo97** [comment]
I had the same problem some time ago, and after researching a little bit, I found the reason why [in the documentation](https://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_to):

> If you are using XHR requests other than GET or POST and redirecting after the request then some browsers will follow the redirect using the original request method. This may lead to undesirable behavior such as a double DELETE. To work around this you can return a 303 See Other status code which will be followed using a GET request.

So, it is more a problem on the browser's side that needs to be fixed using the `:see_other` status code with the redirect.

**Comment by stomar** [comment]
@DRBragg The default used by `redirect_to` is `302 Found`.

@faqndo97 Thanks for the pointer to the docs. It happens both for Firefox (100.0.2) and Chromium (101.0.4951.64), which should behave similar to Chrome, so _"some browsers"_ seems like an understatement...

Is it also expected behavior that the second request is a TURBO_STREAM?

**Comment by skipkayhil** [comment]
> Then in the `destroy` actions `status: :see_other` is used without any explanation. It should be **explicitly explained why this is necessary**

I think it makes sense to call this out, would you be interested in making a PR?
