### ISSUE TITLE
Migrations ignores `shared` section in database.yml

### ISSUE THREAD

**Issue by jandudulski** [rails/rails#45299]
### Steps to reproduce

* create a new app
* add multiple databases
* separate migrations for each one with `migrations_paths` config value
* create migrations & run them - everything should be fine at this point
* [extract migrations_paths](https://github.com/jandudulski/shared_migrations_bug/commit/c81319a75b22c287b133d7ecfa0d32799a8382b2) from each stage to `shared` section
* `Rails.application.config_for(:database)` loads yaml as expected with merged values
* `rails db:migrate` and `db:migrate:status` ignores shared config

Example app with reproduce: https://github.com/jandudulski/shared_migrations_bug

### Expected behavior

Use shared section for migrations.

### Actual behavior

Shared section is ignored.

### System configuration
**Rails version**: verified on 6.1 and 7.0

**Ruby version**: N/A

**Comment by eileencodes** [comment]
Hey @jandudulski thanks for the report! I've fixed this in https://github.com/rails/rails/pull/45309 and backported it to 7-0-stable in fe2a34d1674592adb5a08409315646fd3e6be024.

**Comment by jasonkarns** [comment]
@jandudulski Are you able to confirm latest rails behaves as expected for you? I might be missing something, but when I run the demo app (https://github.com/jandudulski/shared_migrations_bug) against Rails 7.0.4.2, I end up with the `shared` options merged "below" each db config.

sample from `ActiveRecord::Base.configurations`:

```
   #<ActiveRecord::DatabaseConfigurations::HashConfig:0x0000000109d1f5d8
    @configuration_hash=
     {:foo=>{"migrations_paths"=>["db/foo"]},
      :bar=>{"migrations_paths"=>["db/bar"]},
      :adapter=>"sqlite3",
      :pool=>5,
      :timeout=>5000,
      :database=>"db/foo_dev.sqlite3"},
    @env_name="development",
    @name="foo">,
```

Note how the `{foo:, bar:}` migrations_paths hash from shared is added to the development foo database? I would not have expected to see any configuration for the `bar` database to be in the foo database's configuration.
