### ISSUE TITLE
documentation question: Active Record Query Interface

### ISSUE THREAD

**Issue by jeffbuzz** [rails/rails#45323]
I am trying to learn Ruby active records.  Specifically how models define and/or use cross-reference tables.  The documentation (https://guides.rubyonrails.org/active_record_querying.html) visually shows a table named "Book Orders".  The text describes a join table named "books_orders".  Are those supposed to be the same thing?  If so, should they be spelled the same?  If not, how does this reference work?

### Expected behavior
I expected the table names to match in the documentation.

### Actual behavior
I see different names.

### System configuration
**Rails version**:

**Ruby version**: 7.0.3

**Comment by Vic-L** [comment]
Hi!

If I understood you correctly, they can be spelled in any manner, as long as the `join_table` option is specified

`has_and_belongs_to_many :books, join_table: 'something_else'`

In rails, we stress on convention over configuration, and the convention for the join table naming for this case is `book_orders`. In this case, the `join_table` option can be left out and rails will know how to find them.

More information can be found here https://guides.rubyonrails.org/association_basics.html#the-has-and-belongs-to-many-association

Hope it helps!

**Comment by simi** [comment]
Hello @jeffbuzz.

If you have more questions you can ask at https://discuss.rubyonrails.org/ or you can join Ruby discord (link at https://www.ruby-lang.org/en/community/, there is Rails section as well). Issue tracker is used mostly to report problems.

**Comment by p8** [comment]
Hey @jeffbuzz,
The names in the UML diagram reference the models, not the tables.
For example the `Customer` (singular) model will be stored in the `customers` (plural) table.
I can image the "Book Orders" is a bit confusing in this case, as that isn't defined as a model in the example.
