### ISSUE TITLE
Actiontext inserting `record_id`: 0 instead of real record ID

### ISSUE THREAD

**Issue by markvanlan** [rails/rails#45321]
I am having an issue that _looks_ like a race condition with actiontext. Actiontext is trying to create a record with the correct `record_type`, but `record_id` is _sometimes_ `0`. Other times this logic works, which is making me think race condition with saving the associated polymorphic record.

### Steps to reproduce
```ruby
note = Note.new(record: record, note_type: :note, submitted_by: current_user, content: params[:content])
note.save!
```
Or!
```ruby
note = new(record: record, note_type: :note, submitted_by: current_user)
note.build_rich_text_content(body: params[:content])
note.save!
```
Or!
```ruby
note = create!(record: record, note_type: :note, submitted_by: current_user)
note.create_rich_text_content(body: params[:content])
```

What makes me _not_ think this is a race condition issue is that even calling reload on the record before creating the rich text content, results in the same situation: `note.reload.create_rich_text_content(body: params[:content])`

I then added `sleep 1` in-between creating the `note` and creating rich text. No go. I am thinking it is not a race condition; I don't see how it could be.

### Expected behavior
Rich text is created :)

### Actual behavior
Error! (sorry for weird blocked out stuff.. private repo)

![Screen Shot 2022-06-10 at 10 18 48 AM](https://user-images.githubusercontent.com/16214023/173100362-4c60f394-bbfa-4b44-a2a7-b4da9feac60b.png)

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.0.3p157

**Comment by skipkayhil** [comment]
Do you have a sample repo where you could reproduce this issue? Without this it will likely be hard to figure out what is going on

**Comment by markvanlan** [comment]
Ahh we are using `uuid`, rather than a `bigint` ID for the record. The IDs in `action_text_rich_text` are all wrong as, they're just UUIDs.to_i (I believe).

```
irb(main):007:0> Note.last.id
  Note Load (17.3ms)  SELECT "notes".* FROM "notes" ORDER BY "notes"."created_at" DESC LIMIT $1  [["LIMIT", 1]]
=> "72601c5b-6998-409c-8946-5bd7d0a145fc"
irb(main):008:0> Note.last.id.to_i
  Note Load (19.7ms)  SELECT "notes".* FROM "notes" ORDER BY "notes"."created_at" DESC LIMIT $1  [["LIMIT", 1]]
=> 72601
```

Luckily this is a case where I can simply not use a UUID, but I think a good change would be to either somehow support UUID polymorphic relationships (probably with a different column) or at least detect what is happening and give a useful error.

**Comment by arni1981** [comment]
I'm not sure if I should comment on this one or create another, but this is still an issue with Rails 7.2, using UUID with ActionText causes this error to happen.
