### ISSUE TITLE
New rails projects have hello_controller.js created, despite there being no other files related to it

### ISSUE THREAD

**Issue by unikitty37** [rails/rails#45343]
### Steps to reproduce

```sh
$ rails new testapp
```

(I ran this using `docker run -it --rm ruby:3.1.2 bash` to avoid any incompatibilities with my system)

### Expected behavior

The Rails application is created without any superfluous files.

### Actual behavior

`app/javascript/controllers/hello_controller.js` is created:

```
Create controllers directory
      create  app/javascript/controllers
      create  app/javascript/controllers/index.js
      create  app/javascript/controllers/application.js
      create  app/javascript/controllers/hello_controller.js
```

No other files relating to this controller are created, including the Rails controller itself. It looks like a bit of an example project has been included by mistake.

(It's possible it's there as an example of how to write a Stimulus controller, of course, but no other parts of Rails are included this. I wonder how many projects ship with it still in there? :)

I've looked through the rails/rails repo, but the only references I can find to the file are in railties/test/commands/notes_test.rb, so I can't see where it's coming from…

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.1.2

**Comment by ghiculescu** [comment]
> (It's possible it's there as an example of how to write a Stimulus controller, of course, but no other parts of Rails are included this. I wonder how many projects ship with it still in there? :)

Yeah, that's why it's there. It comes from here: https://github.com/hotwired/stimulus-rails/blob/main/lib/install/app/javascript/controllers/hello_controller.js

**Comment by AdityaBhutani** [comment]
Close this issue ?
