### ISSUE TITLE
Migration converts references and polymorphic associations from bigint to integer

### ISSUE THREAD

**Issue by matteo-rossi-wise** [rails/rails#45349]
### Steps to reproduce

On Rails 6.1.6 app, when running the `bin/rails db:migrate` task, each `t.references` (included polymorphic) that were written as `bigint` in the `schema.rb` are automatically converted to `integer`. This happens for migration inheriting from `ActiveRecord::Migration[6.0]` and below, the ones who inherit from `ActiveRecord::Migration[6.1]` are not affected.

```ruby
# setup a Rails 6.1.6 app
# create a db migration with version [6.0] that references an attribute as foreign key
# create a db migration with version [6.1] that references an attribute as foreign key
# run `bin/rails db:migrate`
```

### Expected behavior

I'd expect each referenced field to have `bigint` type even for pre [6.1] migrations

### Actual behavior

Each previous `bigint` reference is converted to `int`

### System configuration
**Rails version**: 6.1.6

**Ruby version**: 3.0.2

**Comment by fatkodima** [comment]
That should be fixed by https://github.com/rails/rails/pull/42350. Can you verify using the latest code from the `main`?

**Comment by matteo-rossi-wise** [comment]
Hi @fatkodima, you're right it is fixed. I regenerated my local db with Rails `6.1.5.1` that still have this issue and after the upgrade to `6.1.6`. By doing this, the wrong data types within the db were affecting my `schema.rb` and were hiding the actual behaviour.

I'm closing this issue, thanks
