### ISSUE TITLE
Report bug template does not work

### ISSUE THREAD

**Issue by morgoth** [rails/rails#45340]
I'm trying to report a bug - a different one ;-) and the bug report template does not work for me.

I'm trying to run this one https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb

and getting:
```
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using bundler 2.3.15
bug.rb:15:in `require': cannot load such file -- active_record (LoadError)
	from bug.rb:15:in `<main>'
```

**Rails version**: 7.0.3

**Ruby version**: 3.1.2p20

**Bundler version**: 2.3.15

**Comment by ghiculescu** [comment]
It is working fine for me, but maybe the issue relates to your ruby or bundler versions... could you try an older version to check?

**Comment by morgoth** [comment]
The same error with Ruby 3.0.3 and bundler 2.3.4

**Comment by simi** [comment]
All works for me as well (using Ruby/Bundler 3.0.3/2.3.4 + chruby/ruby-install). We have seen various problems reported by using `asdf` to RubyGems. Would you mind to open issue at `asdf`?

**Comment by siaw23** [comment]
Works for me too.

```
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
Bundler version 2.3.15
```

Using RVM.

**Comment by morgoth** [comment]
I downloaded this ruby script to the directory where I had a file `.bundle/config` with a content:
```
---
BUNDLE_WITHOUT: "default"
BUNDLE_WITH: "linter"
```

This was some old leftover that I didn't notice. After removing it, it works fine.

Sorry, for the falsy report and thank you for confirming that it works on your site.

**Comment by simi** [comment]
@morgoth Maybe that's something we can fix in `require "bundler/inline"` itself. I would expect to ignore `.bundle/config` and work the same everywhere no matter the local environment configuration.
