### ISSUE TITLE
Active Record logger method in enum.rb is overriden by Httparty logger method

### ISSUE THREAD

**Issue by maniSHarma7575** [rails/rails#45357]
### Steps to reproduce

1. Create a new rails application.
```ruby
rails new reproduce-behaviour-app
```

2. Generate Scaffold for post
```ruby
bin/rails generate scaffold Post name:string title:string content:text category:integer
```

3. Migrate database
```ruby
bin/rails db:migrate RAILS_ENV=development
```
4. Define enum category in  `post.rb`
```ruby
  class Post < ApplicationRecord
    enum :category, [:technology, :marketing, :sales]
  end
```
5. Modify `app/views/posts/_form.html.erb`

Replace

```ruby
    <%= form.number_field :category %>
```
With

```ruby
    <%= form.select :category, options_for_select(Post.categories.map {|key, value| [key.titleize, Post.categories.key(value)]}, post.category) %>
```

6. Create new posts by visting the url `/posts/new`

7. Modify `gemfile`
```ruby
gem 'httparty'
```

8.  Do Bundle install
```ruby
  bundle install
```
9. Modify `post.rb`
```ruby
  class Post < ApplicationRecord
    include HTTParty
    enum :category, [:technology, :marketing, :sales]
  end
```

10. visit the url `http://127.0.0.1:3000/posts/1`

The above mentioned code will give the following error :

<img width="1440" alt="Screenshot 2022-06-14 at 11 49 10 PM" src="https://user-images.githubusercontent.com/39980734/173661083-d3f5c0ba-e5e9-472a-bf1f-73370913dc6c.png">

### Expected behavior
Logger method should not be overriden by the Httparty logger method.

### Actual behavior
And in the rails source code, in the file lib/active_record/enum.rb:, the logger is being overridden by HTTParty's logger.
```ruby

     def detect_negative_enum_conditions!(method_names)
        return unless logger       # problematic code, temp solution is to replace logger with ActiveRecord::Base.logger

        method_names.select { |m| m.start_with?("not_") }.each do |potential_not|
          inverted_form = potential_not.sub("not_", "")
          if method_names.include?(inverted_form)
            logger.warn "Enum element '#{potential_not}' in #{self.name} uses the prefix 'not_'." \
              " This has caused a conflict with auto generated negative scopes." \
              " Avoid using enum elements starting with 'not' where the positive form is also an element."
          end
        end
      end

It looks like the HTTParty's logger function defined in lib/httparty.rb:77 is overriding the rails logger.
```

### System configuration
**Rails version**: 7.0.3

**Ruby version**:3.1.2

**Comment by simi** [comment]
You should not do `include HTTParty`. What's the reason for that? Is that recommended anywhere?

**Comment by maniSHarma7575** [comment]
> You should not do `include HTTParty` in model. What's the reason for that? Is that recommended anywhere?

@simi It's is a sample application for reproducing the behaviour.But  In our actual applications we are using HTTParty for sending request.

**Comment by simi** [comment]
> > You should not do `include HTTParty` in model. What's the reason for that? Is that recommended anywhere?
> 
> @simi It's is a sample application for reproducing the behaviour.But In our actual applications we are using HTTParty for sending request.

That's ok. But `HTTParty` is not intended to be included in ActiveRecord models. You need to use it as [intended](https://github.com/jnunemaker/httparty#examples). By calling `HTTParty.get(url)` for example.

**Comment by hahmed** [comment]
From what I'm seeing it looks like ActiveRecord defines the logger via a class method here https://github.com/rails/rails/blob/bdc3e192bb9b7223963d79cf7a15967a88f4bf6f/activerecord/lib/active_record/core.rb#L20

If you mixin the HTTParty module into an ActiveRecord module it looks like it will get overridden here https://github.com/jnunemaker/httparty/blob/907accf4d25e11251679eb9f02bebe3a23ab37e6/lib/httparty.rb#L28

I think the best bet would be to create a class and include HTTParty as mentioned above e.g. 

````
class Example
  include HTTParty
end

class Post < ApplicationRecord
    def example
      @_ example ||= Example.new
   end
end
```

**Comment by simi** [comment]
Anyway there is nothing wrong in Rails and I think this issue can be closed.

**Comment by skipkayhil** [comment]
As mentioned above, you should probably not be doing `include HTTParty` in an Active Record model. I'm going to close the issue but feel free to continue the discussion on the [rubyonrails-talk](https://discuss.rubyonrails.org/c/rubyonrails-talk/7) forum

**Comment by maniSHarma7575** [comment]
> From what I'm seeing it looks like ActiveRecord defines the logger via a class method here
> 
> https://github.com/rails/rails/blob/bdc3e192bb9b7223963d79cf7a15967a88f4bf6f/activerecord/lib/active_record/core.rb#L20
> 
> If you mixin the HTTParty module into an ActiveRecord module it looks like it will get overridden here https://github.com/jnunemaker/httparty/blob/907accf4d25e11251679eb9f02bebe3a23ab37e6/lib/httparty.rb#L28
> 
> I think the best bet would be to create a class and include HTTParty as mentioned above e.g.
> 
> ```
> class Example
>   include HTTParty
> end
> 
> class Post < ApplicationRecord
>     def example
>       @_ example ||= Example.new
>    end
> end
> ```
> ```

@hahmed Yes, I created a ruby class and performed all HTTParty related task there. It worked!
