### ISSUE TITLE
Improved time field support 

### ISSUE THREAD

**Issue by dssjoblom** [rails/rails#45371]
I ran into the following bug in a codebase I'm working on:

a) front-end validates a time input field with `Time.parse`, considering an exception a validation failure
b) on success, the string value is assigned to a database field of type time

The bug here is that `Time.parse(foo_string)` and `model.time_field = foo_string` don't use the same logic for deciding what is a valid time. For example, Time.parse('11.21') is valid, but assigning '11.21' to a database field sets it to nil, while it works as expected for '11:21' or '11:21am'.

Obviously, the code in question makes invalid assumptions, but I think this bug would have been prevented if:

1. Rails had a built-in validator for time strings that does the right thing, meaning if the validation passes, the string can be assigned to a database time field. Now people have to write their own custom validators which may or may not have bugs like this. It would also be nice if this was configurable to a degree, e.g. some applications might want just hh:mm input, while others need seconds as well.
2. The valid time string format (for DB fields) was documented. In what ways is it different from Time.parse? For the record, I think Time.parse is too lax, and the database field code looks better.
3. This last part I'm not sure of, but is it a good idea in general to coerce invalid assignments to nil? Wouldn't raising an exception be more appropriate?

### System configuration
**Rails version**: 6.1.5.1

**Ruby version**: 2.7.6

**Comment by nvasilevski** [comment]
>For example, Time.parse('11.21') is valid,

May I ask you to clarify what do you mean as "valid"?
That's how `Time.parse` behaves for me:
```ruby
(rdbg) Time.parse("5.23")    # ruby
2022-06-23 00:00:00 +0000
(rdbg) Time.parse("11.23")    # ruby
2022-06-16 02:34:11.23 +0000
(rdbg) Time.parse("11.21")    # ruby
2022-06-16 02:34:11.21 +0000
(rdbg) Time.parse("12.32")    # ruby
2022-06-16 02:35:12.32 +0000
(rdbg) Time.parse("7.23")    # ruby
2022-06-23 00:00:00 +0000
```

And I wouldn't confidently call these values "valid" 😕

**Comment by nvasilevski** [comment]
From the doc - https://ruby-doc.org/stdlib-3.1.2/libdoc/time/rdoc/Time.html#method-c-parse
```
This method **does not** function as a validator. If the input string does not match valid formats strictly, you may get a cryptic result. Should consider to use `Time.strptime` instead of this method as possible.
```

**Comment by dssjoblom** [comment]
@nvasilevski no, you are right, the code is obviously broken. 

But to reiterate, if Rails supported `validates :field, type: :time` (or something similar), this code wouldn't have been written in the first place. I don' think this is that unusual either, the first Google result for "rails time validation" is https://stackoverflow.com/questions/32053927/validating-time-in-rails, which has the exact same error.

I also think the silent conversion to nil on assignment is pretty dangerous. It means any errors caused by this are not found at the site of the assignment, but likely in completely unrelated code, like in this case, a background job that assumed that if the form in question had been submitted, the field would have a valid value. I'd prefer fail-fast behavior here.

**Comment by natematykiewicz** [comment]
Time can be formatted a lot of different ways. To have an accurate parsing, you really should be defining a specific format you expect user-input to be. Then you can use [strptime](https://rubyapi.org/3.1/o/time#method-c-strptime) to parse it.

```ruby
Time.strptime('1.25pm', '%I.%M%P')

=> 2022-06-29 13:25:00 -0500
```

Or you could go with an ISO6801 formatted timestamp and specify a specific date. Rails [uses 2000-01-01](https://github.com/rails/rails/blob/main/activemodel/lib/active_model/type/time.rb#L56) for "time" (no date) columns. 

```ruby
time = '13:45:52Z'
Time.iso8601("2000-01-01T#{time}")

=> 2000-01-01 13:45:52 UTC
```
