### ISSUE TITLE
updated_at is not affected by attribute changes in before_update callback

### ISSUE THREAD

**Issue by etherbob** [rails/rails#45389]
### Steps to reproduce

* Modify an attribute in a before_update callback.
* call save on an instance of a model with said callback

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| 'https://github.com/#{repo}.git' }

  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '~> 6.1.4.1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :updaty_posts, force: true do |t|
    t.string :name
    t.timestamps
  end

  create_table :savy_posts, force: true do |t|
    t.string :name
    t.timestamps
  end
end

class UpdatyPost < ActiveRecord::Base
  before_update :mutate_name

  private

  def mutate_name
    return if new_record?

    self.name = 'something different'
  end
end

class SavyPost < ActiveRecord::Base
  before_save :mutate_name

  private

  def mutate_name
    return if new_record?

    self.name = 'something different'
  end
end


class BugTest < Minitest::Test
  def test_association_stuff
    upost = UpdatyPost.create!
    spost = SavyPost.create!

    before_upost_updated_at = upost.updated_at
    before_spost_updated_at = spost.updated_at

    refute_equal 'something different', spost.name
    refute_equal 'something different', upost.name

    sleep 2

    upost.save!
    spost.save!

    assert_equal 'something different', spost.name
    assert_equal 'something different', upost.name

    refute_equal spost.updated_at, before_spost_updated_at, 'changed attribute did not change timestamps in before_save'
    refute_equal upost.updated_at, before_upost_updated_at, 'changed attribute did not change timestamps in before_update'
  end
end
```

### Expected behavior
Based on the warning in [the guide](https://guides.rubyonrails.org/active_record_callbacks.html#updating-an-object) 

> Avoid updating or saving attributes in callbacks. For example, don't call update(attribute: "value") within a callback. This can alter the state of the model and may result in unexpected side effects during commit. Instead, you can safely assign values directly (for example, self.attribute = "value") in before_create / before_update or earlier callbacks.

I would expect updated_at to change when changing an attr in a before_update callback.

### Actual behavior
updated_at does not change.

### System configuration
**Rails version**: 6.1.4.1 (but tested my reproduction above in rails 7 with same result)

**Ruby version**: ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-darwin21]
(but also seen on other ruby 2.7.x versions on heroku-20 stack)

Not sure if this is an actual bug or intended behavior, but I be happy to open a PR against the guides if it's the latter.

**Comment by markhallen** [comment]
> As a quick update, I believe that `should_record_timestamps?` is incorrectly evaluated to `false` here:
> 
> https://github.com/rails/rails/blob/d77c3fac9e8111a7f20cc5b4b2c686a7ad49d789/activerecord/lib/active_record/timestamp.rb#L117-L118
> 
> Specifically, `has_changes_to_save?` on this line:
> 
> https://github.com/rails/rails/blob/d77c3fac9e8111a7f20cc5b4b2c686a7ad49d789/activerecord/lib/active_record/timestamp.rb#L135-L137
> 
> I'm continuing to investigate.

**I think** this may be evaluated before the `before_update` callback.

**Comment by markhallen** [comment]
The change is evaluated in `ActiveRecord#_update_record` and a decision is made whether to touch the `updated_at` timestamp.

`ActiveRecord#_update_record` is invoked for the `before_update` callback during the `:validate` callbacks and before the change has been made.

`ActiveRecord#_update_record` is invoked for the `before_save` change during the `:save` callbacks and after the change has been made.

**Comment by markhallen** [comment]
## `before_update` flow

Note that `ActiveRecord::Timestamp::_update_record` is executed before the `name` attribute is updated.

```mermaid
sequenceDiagram
    record.save!-->>validation callbacks: no changes
    validation callbacks-->>validate callbacks: no changes
    validate callbacks->>update callbacks: record.name = "Jack Bauer"
    validate callbacks->>update callbacks: ActiveRecord::Timestamp::_update_record
    validate callbacks->>update callbacks: record_timestamps = true, partial_updates? = true, has_changes_to_save? = false
    validate callbacks->>update callbacks: should_record_timestamps? = false
    update callbacks->>write to db: record.name = "Jack Bauer"
    write to db->>saved: record.name = "Jack Bauer"
```

## `before_save` flow

```mermaid
sequenceDiagram
    record.save!-->>validation callbacks: no changes
    validation callbacks-->>validate callbacks: no changes
    validate callbacks-->>save callbacks: no changes
    save callbacks->>write to db: record.name = "Jack Bauer"
    save callbacks->>write to db: ActiveRecord::Timestamp::_update_record
    save callbacks->>write to db: record_timestamps = true, partial_updates? = true, has_changes_to_save? = false
    save callbacks->>write to db: should_record_timestamps? = false
    save callbacks->>write to db: record.updated_at = Time.now
    write to db->>saved: record.name = "Jack Bauer"
    write to db->>saved: record.updated_at = Time.now
```
