### ISSUE TITLE
Order of SQL JOINs should not matter for ActiveRecord::Relation#or

### ISSUE THREAD

**Issue by Exterm1nate** [rails/rails#45398]
### Steps to reproduce

Consider we have some model with associations.

```ruby
class User < ApplicationRecord
  has_many :posts
  has_many :comments
end
```

Then we want to use `ActiveRecord::Relation#or` to build some query.

```ruby
  User.joins(:posts, :comments).where(comments: { id: 1 }).or(User.joins(:comments, :posts).where(posts: { id: 2 }))
```

### Expected behavior

It should produce a valid SQL query with two JOINs (final order of JOIN statements can be determined from one of subqueries).

```ruby
User.joins(:posts, :comments).where(comments: { id: 1 }).or(User.joins(:comments, :posts).where(posts: { id: 2 }))

# SELECT "users".* FROM "users" INNER JOIN "posts" ON "posts"."user_id" = "users"."id" INNER JOIN "comments" ON "comments"."user_id" = "users"."id" WHERE ("comments"."id" = $1 OR "posts"."id" = $2)  [["id", 1], ["id", 2]]
```

### Actual behavior

But it raises an error due to arguments order difference in #joins.

```ruby
User.joins(:posts, :comments).where(comments: { id: 1 }).or(User.joins(:comments, :posts).where(posts: { id: 2 }))

# Relation passed to #or must be structurally compatible. Incompatible values: [:joins] (ArgumentError)
```

### Notes

This problem exists for all methods provided in `STRUCTURAL_VALUE_METHODS` constant in `ActiveRecord::QueryMethods`. I think for most of them arguments order should not be checked.

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.1.2

**Comment by sampatbadhe** [comment]
Hello @skipkayhil @Exterm1nate 

I have made the necessary changes to address the reported issue. Could you please review the [PR#45403](https://github.com/rails/rails/pull/45403) and provide your suggestions.
