### ISSUE TITLE
Rails 7 activejob using deprecated Que API

### ISSUE THREAD

**Issue by kyrofa** [rails/rails#45392]
Forgive me, I'm not entirely up to speed on how Rails determines what fixes land where. Que recently deprecated parts of its API in preparation for Ruby 3, which makes Rails 7 spit a lot of deprecation warnings. This is fixed in Rails main with 6c933738421bec6ad266f2fa0037942eb0605c00. Any chance we can get that cherry-picked back to a v7 release? I'd be happy to propose exactly that to the 7-0-stable branch if that's the proper process.

**Comment by byroot** [comment]
Backported to `7-0-stable` as 7b677ef506c039ec18d382b3654e15a0c8b79737

**Comment by kyrofa** [comment]
Thank you :)

**Comment by kyrofa** [comment]
For future reference, could I have proposed that myself as a PR to `7-0-stable`?
