### ISSUE TITLE
ActionDispatch::IntegrationTest GET with params keyword cause a conversion to POST 

### ISSUE THREAD

**Issue by matteo-rossi-wise** [rails/rails#45409]
### Steps to reproduce

- Setup a new Rails api_only app with MiniTest
- Write a controller with `index` and `create` actions (and respective routes)
- Write an `ActionDispatch::IntegrationTest` to test both previous actions
- Run the test suite

```ruby
test "should get index and return ok on success" do
  get items_url, params: index_params, as: :json
  assert_response :ok
end

test "should post create and return created on success" do
  post items_url, params: create_params, as: :json
  assert_response :created
end
```

### Expected behavior

The first test (GET) is successful

### Actual behavior

The first test fails, its verb is converted to `POST` and the invoked action is `create`. I managed make the test pass by converting the first test like this:

```ruby
test "should get index and return ok on success" do
  get items_url(index_params), as: :json
  assert_response :ok
end
```

or by removing the `as: :json` like this:

```ruby
test "should get index and return ok on success" do
  get items_url, params: index_params
  assert_response :ok
end
```

### System configuration
**Rails version**: 6.1.6

**Ruby version**: 3.0.2

**Comment by deepakmahakale** [comment]
Looks like this is intentional

https://github.com/rails/rails/blob/1f979184efc27e73f42c5d86c7f19437c6719612/actionpack/lib/action_dispatch/testing/integration.rb#L204-L211

**Comment by skipkayhil** [comment]
> Looks like this is intentional

Beat me to it by seconds 😆 

For some more context: added in af1680f to fix #26033

@matteo-rossi-wise what is the high level expected behavior here? I believe JSON bodies for GET requests are not supported by the HTTP spec

**Comment by matteo-rossi-wise** [comment]
From my point of view this behaviour is misleading and not documented at all. Moreover for an inbound request, Rails treats boh query-string and body params the same way with the `params` Hash. With this, I'd expect the same behaviour in my integration tests.

In the end I find really confusing (and dangerous) converting an explicit GET request into a POST one.

What do you think?

**Comment by rafaelfranca** [comment]
This is intentional, but it should be document. Apart from that, I don't think this behavior should change.

**Comment by neemiasvf** [comment]
> I don't think this behavior should change.

Why not? How else are we supposed to make GET requests with a payload?
