### ISSUE TITLE
Rails 5.2.3: Not able to install rails 5.2.3 because of transitive dependencies on  minitest 5.16.1 ~> 5.1:

### ISSUE THREAD

**Issue by mayankesh-maurya** [rails/rails#45417]
### Steps to reproduce
I am using ruby version as 2.5.9

ruby -v
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]

while installing gem using gem install it is giving below error:
ERROR:  Error installing rails:
        minitest requires Ruby version < 4.0, >= 2.6. The current ruby version is 2.5.0.

I tried to install minitest older version which was working as minitest 5.15, but still I am facing same issue.

I am running my application in centos 7 and _I am not using bundler_ 

We are first installing gems our app requires using "gem install" as below.

`
http_proxy=proxy-grp1.lb-priv.svc.247-inc.net:3128 gem install --install-dir /usr/share/gems rails -v '5.2.3'
http_proxy=proxy-grp1.lb-priv.svc.247-inc.net:3128 gem install --install-dir /usr/share/gems passenger -v '5.0.22'
`
I have raised the below PRs to the Ruby on Rails community.

https://github.com/rails/rails/pull/45386
https://github.com/mayankesh-maurya/minitest/pull/1

### Expected behavior
it should be able to install rails gem

### Actual behavior
it is not able to install, giving the below error and breaking backward compatibility.
ERROR:  Error installing rails:
        minitest requires Ruby version < 4.0, >= 2.6. The current ruby version is 2.5.0.

### System configuration
**Rails version**: rails 5.2.3

**Ruby version**: ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]

Please check this, it does not provide backward compatibility and breaks the existing ROR application.

**Comment by matthewd** [comment]
Rails 5.2 is no longer supported.

That being said, the Ruby community provides tools that are aware of dependencies (including Ruby version constraints) and will ensure an application runs using a mutually-compatible set of versions; if you choose not to use such a tool, you're going to have to get it right yourself.

You're trying to use a setup that was never officially supported, on a set of versions of both Ruby and Rails that are no longer supported even for severe security issues. You're welcome to try, but we are not here to help with that.
