### ISSUE TITLE
Active Job worker crashes when a job causes an Exception in DelayedJob

### ISSUE THREAD

**Issue by fnordfish** [rails/rails#45418]
(I'm not quite sure if that issue is limited to the DelayedJob adapter)

### Steps to reproduce

Demo project with traces: https://github.com/fnordfish/activejob-poison-pill-demo.

```ruby
class TestJob < ActiveJob::Base
  # Thid has no effect on Exceptions thrown in Queue Adapters?
  discard_on Encoding::CompatibilityError
  
  # this will eventually bubble up into the Adapter (when retries exhausted?)
  retry_on Exception, wait: 1.second

  def perform(message)
    raise message.dup.force_encoding("ASCII-8BIT")
  end
end

TestJob.perform_later("🤷")
```

### Expected behavior

- Job fails
- Exception trace of the `Encoding::CompatibilityError` is logged
- Job worker keeps on working, not trying the failed job again

### Actual behavior

- Job fails
- Exception trace of the `Encoding::CompatibilityError` is logged
- Job worker crashes with `Encoding::CompatibilityError` exception
- Restarting the job worker will try the failed job again, crashing the job worker again

### System configuration
**Rails version**: 7.0.3, 7.1.0.alpha

**Ruby version**: 3.1

**Comment by fnordfish** [comment]
I do. Sorry my snipped was not complete, but the demo project does that. I've updated the snippet in the description above.

**Comment by fnordfish** [comment]
Thanks for the suggestion. I tried that, but it has no impact. The job will try 5 times and the last one will let the `bin/rails  jobs:work` process crash.

Having no `discard_on` and `retry_on`, or only `discard_on` will let it crash immediately.  
Having only `retry_on` will try for 5 time and crash.

**Comment by fnordfish** [comment]
For me, it feels like `discard_on` and `retry_on` only guards the call to `perform`, not what happens later.

Here's another sample, where, when the job changes it's attributes to something the adapter cannot cope with, it crashes: https://github.com/fnordfish/activejob-poison-pill-demo/tree/sqlite-writeback

**Comment by fnordfish** [comment]
Right. Because that raises an exception with an message that does not crash in `DelayedJob`.
But that's what this issue is about. The job does something that will eventually bubble up into the job adapter (`DelayedJob` in my case) and causes an error there – after the error handling around `perform` – and than make the entire worker job process crash.

My example in `TestJob` is a very simplified version of what we experienced in production, and we fixed our code so that particular error does not bite us anymore.

However, there might be any number of ways how to let something bubble out of the error catching around `perform` and cause the job worker process to crash. (Like the one in https://github.com/fnordfish/activejob-poison-pill-demo/tree/sqlite-writeback - again an encoding issue, but that's just an example I came up with)

It would be nice if activejob would also provide a way to guard against errors in its queue adapters, maybe even provide some sensible default (like marking the job as failed).

**Comment by fatkodima** [comment]
https://github.com/rails/rails/blob/8a91f7293d16caeed04e1fd7fd1c26aafcd78ad5/activejob/lib/active_job/exceptions.rb#L15-L18

> It would be nice if activejob would also provide a way to guard against errors in its queue adapters, maybe even provide some sensible default (like marking the job as failed).

I think, you can use a block version for this - 
https://github.com/rails/rails/blob/8a91f7293d16caeed04e1fd7fd1c26aafcd78ad5/activejob/lib/active_job/exceptions.rb#L48-L50

It is called when all attempts were exhausted.

```ruby
retry_on Exception, wait: 1.second do |job, error|
  # mark job as failed in the db
end
```

**Comment by etiennebarrie** [comment]
It's a bug in `delayed_job`. Active Job and the queue adapter do what they're supposed to, ultimately if the exception is not handled it needs to bubble up to the queueing framework. For example sidekiq has a number of retries before the job gets moved to the dead set. The problem here is the handling of the errors from `delayed_job` https://github.com/collectiveidea/delayed_job/blob/v4.1.10/lib/delayed/worker.rb#L304

If I change delayed_job with this diff, the workers don't crash:

```diff
diff --git i/lib/delayed/backend/base.rb w/lib/delayed/backend/base.rb
index 494c33b..40f1abe 100644
--- i/lib/delayed/backend/base.rb
+++ w/lib/delayed/backend/base.rb
@@ -47,7 +47,7 @@ def work_off(num = 100)
       attr_reader :error
       def error=(error)
         @error = error
-        self.last_error = "#{error.message}\n#{error.backtrace.join("\n")}" if respond_to?(:last_error=)
+        self.last_error = "#{error.message.encode}\n#{error.backtrace.join("\n")}" if respond_to?(:last_error=)
       end
 
       def failed?
diff --git i/lib/delayed/worker.rb w/lib/delayed/worker.rb
index 1a352f7..bcaa920 100644
--- i/lib/delayed/worker.rb
+++ w/lib/delayed/worker.rb
@@ -301,7 +301,7 @@ def say_queue(queue)
 
     def handle_failed_job(job, error)
       job.error = error
-      job_say job, "FAILED (#{job.attempts} prior attempts) with #{error.class.name}: #{error.message}", 'error'
+      job_say job, "FAILED (#{job.attempts} prior attempts) with #{error.class.name}: #{error.message.encode}", 'error'
       reschedule(job)
     end
```

**Comment by fnordfish** [comment]
> It's a bug in delayed_job.

Well, yes - it was also a bug in my application code, that allowed mixed encoded strings in the first place.

IMHO, it's a design question if Active Job can or wants to protect against those type of errors. And I do not mean the specific encoding issue I used for this demo, but in general errors that arise from queue libs AJ provides adapters for.

For me, it would be a valid (yet disappointing) design decision, that failures in queue libs, regardless of their origin, are not handled by Active Job and might lead to worker process crashes. Although I believe that should be clearly stated in the documentation.

**Comment by etiennebarrie** [comment]
> IMHO, it's a design question if Active Job can or wants to protect against those type of errors.

The queueing system is calling us, running `ActiveJob::Base.execute(job)`, we have no control over what happens there, we can't protect against exceptions in the job runner.
The only control we have is preventing errors from bubbling up, like @fatkodima showed you can use a block to `retry_on` to prevent exceptions from bubbling up.

**Comment by ghiculescu** [comment]
I'm gonna close this as it's a DJ issue.

> So in the end this is a documentation thing?

I think the documentation could be improved. Would you like to make a PR? Ideally we take the gist of what you learned here and put it in the docs.
