### ISSUE TITLE
Not working with model connection to a view instead of a table

### ISSUE THREAD

**Issue by Koen03** [rails/rails#45428]
### Steps to reproduce
Add to model:
`self.table_name = <view>`

### Expected behavior
Expect to work like any other model

### Actual behavior
`undefined method 'match' for nil:NilClass`
`match = create_table_info(table_name).match(/'#{field_name}' (.+) DEFAULT ('|\d+|[A-z]+)/)`

### System configuration
**Rails version**: 7.03

**Ruby version**: 3.1.*

**Comment by hahmed** [comment]
Either that or the 7-stable branch (https://github.com/rails/rails/tree/7-0-stable) re: https://github.com/rails/rails/pull/45067#issuecomment-1123633894

**Comment by gregorbg** [comment]
Just dropping a note here that I'm running into the same exact issue. Using the backported fix on `7-0-stable` solves the issue for me. When can we expect a gem release including that commit?

**Comment by colmexdev** [comment]
Hello there.

   I have the same issue on 7.0.3.1 so, supporting @gregorbg's question, I'd like to know if we can have a release for 7.0.z anytime soon regarding this fix.

   Thank you very much in advance!

**Comment by skipkayhil** [comment]
I'm going to close since this has been fixed on main, you can use `gem 'rails', github: 'rails/rails', branch: '7-0-stable'` as mentioned above if you need the fix sooner than the next release.
