### ISSUE TITLE
Defer constant loading ActiveRecord `destroy_association_async_job` during Rails initialization

### ISSUE THREAD

**Issue by bensheldon** [rails/rails#45434]
ActiveRecord's `destroy_association_async_job` currently loads an ActiveJob Job constant during ActiveRecord's initialization. Introduced in #40157

https://github.com/rails/rails/blob/4d5a570cfe1890f71a1d198a5fe40d528f2b60d4/activejob/lib/active_job/railtie.rb#L45-L47

That means that loading ActiveRecord triggers loading the Job constant, which triggers initializing ActiveJob, which then triggers initializing the ActiveJob adapter. I have seen this cause an autoloading deadlock if somewhere during this chain an ActiveRecord constant is touched.

A similar autoload chain is also present with [`ActionMailer.delivery_job`](https://github.com/rails/rails/blob/1003e974ed9cdae6a057a1857374bceb09b34a7b/actionmailer/lib/action_mailer/railtie.rb#L44-L46) but I have yet to see it deadlock (probably because people are less likely to reference an ActionMailer constant in their ActiveJob configuration).

Aside: I also think that the ActiveJob initializer linked above should be inverted such that it lives in ActiveRecord and is assigned `on_load(:active_job)`; that makes it more consistent with ActionMailers Railtie behavior. I don't think this impacts the autoload behavior though, just an observation.

### Expected behavior

This loading could be deferred if instead of a constant, `destroy_association_async_job` was configured with a string that was then constantized when the behavior is invoked.

**Comment by skipkayhil** [comment]
Hmm, the inversion could be interesting. I _think_ it still ends up complicated because the configuration is defined on `ActiveRecord::Base`, and we shouldn't be loading that during initialization.

For example:
https://github.com/rails/rails/blob/2f5dcb7255e59fdf093fb92b681a737ebab99520/activerecord/lib/active_record/railtie.rb#L76-L78

Even in the Active Record Railtie we need the Active Record load hook

**Comment by matthewd** [comment]
I agree this needs the https://github.com/rails/rails/issues/45434#issuecomment-1163602303 treatment. It's safe: `on_load` will fire immediately if the specified component is already loaded.

I do tend to agree it feels like this line would better live in AR, with the job class etc. /cc @rafaelfranca

**Comment by skipkayhil** [comment]
> It's safe: `on_load` will fire immediately if the specified component is already loaded.

🙏 thank you for the confirmation, I opened a PR to document this: #45453
