### ISSUE TITLE
Anyway to change the default colors that rails uses?

### ISSUE THREAD

**Issue by arianf** [rails/rails#45447]
### Steps to reproduce

Use `rails c`

while using a solarized dark console theme for Terminal...
[Solarized Dark.terminal.zip](https://github.com/rails/rails/files/8968996/Solarized.Dark.terminal.zip)

### Expected behavior
Not to have colors clashing. Maybe be able to modify the standard colors that rails selects

### Actual behavior

<img width="383" alt="Screen Shot 2022-06-23 at 9 13 28 AM" src="https://user-images.githubusercontent.com/7397857/175348995-492285bd-97d5-4226-afe3-18ef1e0bb305.png">

### System configuration
**Rails version**:

Rails 7.0.3

**Ruby version**:

ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]

**Comment by nvasilevski** [comment]
I believe `IRB` is that controls it, not particularly related to Rails
https://stackoverflow.com/questions/66447356/how-can-i-change-the-default-syntax-coloring-in-ruby-3-0s-irb

**Comment by nvasilevski** [comment]
Some relevant links
https://github.com/ruby/reline/pull/413
https://github.com/ruby/irb/issues/328
https://github.com/ruby/irb/pull/337
