### ISSUE TITLE
Current versions of NPM packages do not match the actual most recent versions

### ISSUE THREAD

**Issue by matthee** [rails/rails#45443]
NPM displays version 6.0.5 as the most recent version of the [@rails/activestorage](https://www.npmjs.com/package/@rails/activestorage) package. However, version [7.0.3](https://www.npmjs.com/package/@rails/activestorage/v/7.0.3) actually is.

Same thing applies to the [@rails/actiontext](https://www.npmjs.com/package/@rails/actiontext) package (maybe others as well?).

# Why is this a problem?

Running `rails action_text:install` in a new app (with jsbundling) installs old versions of the @rails/actiontext and @rails/activestorage packages, without the most recent bugfixes. 

This task calls `yarn add [package]` internally, which inserts the following line into `package.json`:

```js
  "@rails/actiontext": "^6.0.5"
```

I'm not sure how versions are ordered in the JS ecosystem. I assume it's by release date, since 6.0.5 seems to be the package most recently uploaded to NPM and is listed as the current version there. 

Therefore, running `rails action_text:install` in a rails 7 app leads to installation of the older 6.x packages (since these were the most recently uploaded ones).

# How to fix?

I'm not sure how. Maybe running `rails action_text:install` could install the corresponding package to the version of the actiontext gem? Thoughts?

**Comment by matthewd** [comment]
> I guess [release.rb](https://github.com/rails/rails/blob/8a91f7293d16caeed04e1fd7fd1c26aafcd78ad5/tasks/release.rb#L121) needs a conditional to only `--tag` if the current version is higher than the existing entry for that tag

**Comment by matthewd** [comment]
Thanks @codergeek121, yeah that sounds like a plan.

I'd say we should go with major+minor, because that's the level of our release series. One option would be `6-0-stable`, the same as our corresponding branch name.. or otherwise e.g. `latest-6.0` might feel more npm-ish? Is there any relevant precedent? I know a lot of software doesn't maintain backbranches these days, but surely some major libraries have already made some ecosystem-local precedent?

**Comment by codergeek121** [comment]
I guess two popular examples would be angular and vuejs:
[Angular](https://www.npmjs.com/package/@angular/core) seems to publish a separate lts tag for each major version.
[Vue](https://www.npmjs.com/package/vue) seems to publish a `v2-latest` for version 2  and `latest` for v3 versions.

I'll try to update my PR tomorrow and compare the local and remote minor versions as well :)
