### ISSUE TITLE
Get attributes that were used to instantiate object

### ISSUE THREAD

**Issue by OskarEichler** [rails/rails#45479]
We are looking for a method to grab the attributes that were used when instantiating an object.

So for example when we call:

`user = User.new(name: "John", age: 27, address: "")`

then it is possible to grab the changes by looking at user.changes in order to see which values have changed:

`{"name"=>[nil, "John"], "age"=>[nil, 27], "address"=>[nil, ""]}`

However, if the default value of address is an empty string "" then .changes will not return it anymore:

`{"name"=>[nil, "John"], "age"=>[nil, 27]}`

Is there a way to still know that address was explicitly used to instantiate the object and was not filled by the default after the fact?

It's import for us to know which columns were used explicitly during instantiation as those are the ones that we want to update via an upsert. But if the column is being set back to the default value we will miss it.

In our example, if a user currently has an address and then wants to remove it then we would replace it with an empty string, but then .changes would not return the column because it is the same like the default.

Similarly, if changing name from "John" => "John" on an existing record, it would also not show up in .changes

Hence why it would be awesome to have some new method that returns the columns / attributes that were explicitly provided when instantiating the object.

**Comment by luanzeba** [comment]
Hi @OskarEichler , thanks for submitting this issue!

> In our example, if a user currently has an address and then wants to remove it then we would replace it with an empty string, but then .changes would not return the column because it is the same like the default.

This seems like a bug to me. If you are saving the record with an address, setting a new value of empty string on it should show up in the `changes` hash, regardless of the database default value.
I created a reproduction script and that's the behavior I observed. Are you able to provide a reproduction script that shows your bug?
<details><summary>Reproduction script</summary>

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
    t.integer :age
    t.string :address, default: ""
  end
end

class User < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_activemodel_dirty
    user = User.new(name: "John", age: 27, address: "123 Main St")
    user.save

    user.address = ""
    assert_equal({"address"=>["123 Main St", ""]}, user.changes)
  end
end
```

</details> 

> Hence why it would be awesome to have some new method that returns the columns / attributes that were explicitly provided when instantiating the object.

I agree that would be nice, but we prefer to keep all feature request discussions in https://discuss.rubyonrails.org/. I would suggest bringing that up there or opening a PR.

**Comment by OskarEichler** [comment]
Hey @luanzeba,

Ahh sorry I would like to clarify that in the case where I'm describing the change of the address attribute, the previous record is not initialized. We are basically instantiating it by creating a new record via User.new and then performing a .upsert

So example would be as follows:

```
existing_user = User.create!(name: "John", age: 27, address: "Bikini Bottom")

new_attributes = {'name': "John", 'age': 27, 'address': ""}
new_or_changed_user = User.new(**new_attributes)
```

Since in that case new_or_changed_user is instantiated as a new object that has an empty string "" set as the default value for address, when calling .changes on it it will only return:

`{"name"=>[nil, "John"], "age"=>[nil, 27]}`

However, address was explicitly provided when instantiating the object and therefor is one of the columns that we would want to include when performing the update via the upsert. I don't think that this is something .changes would handle, and I do believe that .changes works as intended and that there is no bug. This is more to outline a scenario in which it is later impossible to tell which attributes were specifically provided when instantiating a new model, as changes is unreliable as it disregards default values.

Therefor it would be great to have another method that could return basically all of the attributes that were provided when instantiating the object. Just for demonstration let's call the method .original_attributes. So in our example above, when now calling:

`new_or_changed_user.original_attributes`

Then this should pretty much return everything in our new_attributes variable, something along the lines of:

`{"name"=>"John", "age"=>27, "address": ""}`

Like this we would know exactly which attributes were specifically provided, and can call an upsert exactly on those columns to update them.

**Comment by OskarEichler** [comment]
So here is the application for this:

We want to instantiate an array of new objects, based on their updated values. Let’s say we are updating 100 records all at once - so we map through them and instantiate the new records by calling Record.new and then pass in the attributes that we want to update.

Now we want to perform an upsert_all on these records. We know the unique columns and will always provide them when instantiating the objects. But the columns that we want to update actually can vary. So maybe we pass in 2 unique columns on which there is a unique index, and then we only want to update one column on existing records. This we want to abstract in order to not always need to pass in exactly which particular column should be updated, and instead we would just like to check the keys of the attributes that were provided when instantiating the model, and then subtract the unique columns in order to determine which columns should be updated.

The issue with attributes_before_type_cast is that it returns all attributes of the model, and it would be impossible to tell which ones actually were supposed to be updated, as the defaults on columns would interfere. Say the default of a column is actually nil, and then we update records that have non-nill columns to be nil again, then we would have no chance of finding out that nil was specifically provided when instantiating the object.

Similarly changes_to_save does not work, as default values are not being returned. That’s annoying because existing records might have different values other than the default that we would want to reset to the default, but then we would not detect those columns and therefor not include them in the upsert.

So really what we are after is to know exactly which attributes were provided when instantiating. Hope that kind of makes sense.
