### ISSUE TITLE
ActiveStorage variant filename. Issue with TIFF files

### ISSUE THREAD

**Issue by coorasse** [rails/rails#45480]
### Steps to reproduce
Our customer uploads TIFF files and we attach them to the model using ActiveStorage.
Since we need to display them in the browser, and most browsers do not support TIFF format, we have a variant that converts the uploaded file to PDF.

```
has_one_attached :file do |attachable|
  attachable.variant :pdf, format: :pdf, loader: { page: nil } # page: nil is needed to convert all pages
end
```

We then embed the PDF using the following:

```erb
<embed src="#{url_for(pdf.variant(:pdf))}">
```

And here is the issue: `url_for` generates the following path (truncated for readability):

```
/rails/active_storage/representations/redirect/eyJfcm/eyJfcm/sample.tiff
```

Now chrome thinks that this is a TIFF file, and does not even try to load this URL 😱 , and just display a message:
<img width="438" alt="CleanShot 2022-06-28 at 16 57 57@2x" src="https://user-images.githubusercontent.com/1319150/176212076-61773a8c-fc41-466d-99ee-a709d52ed349.png">

We have a ~~solution~~trick. We can add the .pdf extension to the filename 🙈 

```erb
<embed src="#{url_for(pdf.variant(:pdf))}.pdf">
```

and force chrome into fetching the file (which is actually a PDF!)

### Expected behavior

`url_for(pdf.variant(:pdf))` returns a path with a `.pdf` extension.

### Actual behavior

`url_for(pdf.variant(:pdf))` returns a path with a `.tiff` extension.

### System configuration
**Rails version**: 7.0.2.3

**Ruby version**: 3.1.0

**Comment by TheStu** [comment]
Also running in to this problem when converting jpg to webp. Not as big a deal as the OP, as the browser ultimately loads the image fine, but it doesn't seem like good manners to have the wrong file extension. Would love to know what the solution to this is.

**Comment by dhanson358** [comment]
Curious if you ever got this resolved?  Having a similar issue, it seems that libvips is not able to output a PDF properly when converting in this way?

**Comment by zzak** [comment]
Are variants intended to be just variations on the same file, therefore retaining the extension of the file they represent?

It's interesting that you can set `format: :pdf` and that generates a PDF file, but where the extension is derived from the parent? 🤔
