### ISSUE TITLE
Epub format support for kindle version documentation

### ISSUE THREAD

**Issue by geongeorge** [rails/rails#45499]
Amazon is dropping support for .mobi files for their Kindle devices slowly. 
Send to device will stop working from August. And later, support will fully drop.

**Source**: https://www.amazon.com/gp/help/customer/display.html?nodeId=G5WYD9SAF7PGXRNA

**Solution**

- Build EPUB version of the documentation along with mobi ([code](https://github.com/rails/rails/blob/main/guides/Rakefile))
- Towards the end of support, stop supporting mobi, and only support epub

**Email recieved**

> Dear Kindle Customer,
> Thank you for using the Send to Kindle service to send personal documents to your Kindle library. We noticed that the following document(s), sent by you at 10:42 PM on Thu, Jun 30, 2022 IST are in MOBI (.mobi, .azw) formats:
>
>  Ruby on Rails Guides v2 - Ruby on Rails.mobi
>
> We wanted to let you know that starting August 2022, you will no longer be able to send MOBI (.mobi, .azw) files to your Kindle library. Any MOBI files that are already in your library will not be affected by this change. MOBI is an older file format and will not support the newest Kindle features for documents. Any existing MOBI files that you want to read with our most up-to-date features for documents will need to be re-sent in a compatible format.
>
> Compatible formats now include EPUB (.epub), which you can send to your library using your Send to Kindle email address. We will also be adding EPUB support to the free Kindle app for iOS and Android devices and the Send to Kindle desktop app for PC and Mac.      
>
> If you have any questions, please visit our help page or contact our Customer Service team.      
>
> Regards,
> Amazon Kindle Support

**Excerpt from Amazon help page**

> Note: Beginning in late 2022, you'll no longer be able to send MOBI (.AZW, .MOBI) files to your Kindle library using Send to Kindle. This change won't affect any MOBI files already in your Kindle library. You can still read them with Kindle. MOBI is an older file format and won't support the newest Kindle features for documents.

**Comment by ghiculescu** [comment]
> * Build EPUB version of the documentation along with mobi ([code](https://github.com/rails/rails/blob/main/guides/Rakefile))

Thanks for the heads up. Are you interested in making a PR for this?

**Comment by geongeorge** [comment]
@ghiculescu Yeah I'll give it a go

**Comment by geongeorge** [comment]
@ghiculescu I've looked into potential solutions. 

Right now we're using the [kindlerb gem](https://github.com/rails/rails/blob/main/guides/rails_guides/kindle.rb) to generate mobi files.

The available options for generating EPUB files I can find are:

- [Epubber](https://rubygems.org/gems/epubber)
- [gepub](https://rubygems.org/gems/gepub)

Epubber has an MIT license, what do you think about using this? If it's alright, I can create a PR for the same

**Comment by ghiculescu** [comment]
I think that is fine. But you could also double check on the Rails discord to confirm https://rubyonrails.org/2022/6/13/rails-discord-server-is-now-open-to-the-public

**Comment by geongeorge** [comment]
Upon further inspection, there is a deeper issue here, The gem `kindlerb` used here no longer works. It relies on a tool Amazon provided long time ago called `kindlegen` which happens to be [no longer available as well](https://github.com/asciidoctor/asciidoctor-epub3/issues/363)

I read that the guides for later versions of rails is manually built https://github.com/rails/rails/issues/29865#issuecomment-358951081

There is also code from the past that needs clean up. For instance 
`Please run setupkindlerb to install kindlegen` =>  setupkindlerb is long gone

I think this calls for a cleanup of old code and also the new logic for EPUB generation. 

Do you mind if I work on both? And is it possible to get this assigned to me?

@ghiculescu

**Comment by skipkayhil** [comment]
Closed by #45539
