### ISSUE TITLE
Using scopes with belongs_to/has_many changes the behavior on the result of `collection.create`

### ISSUE THREAD

**Issue by pjambet** [rails/rails#45496]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
  gem "debug"
end

require "active_record"
require "minitest/autorun"
require "logger"
require "debug"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments, ->() { where("1=1") }
  # Using a scope-less association like this works
  # has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post, ->() { where("1=1") }
  # Using a scope-less association like this works
  # belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    comment = post.comments.create!
    # Explicitly passing the post object works
    # comment = post.comments.create!(post: post)

    assert_equal 1, post.comments.count
    assert_equal 1, Comment.count
    assert_equal post.id, Comment.first.post.id
    assert_equal post.id, comment.post.id
    # Problematic test:
    assert_equal post.object_id, comment.post.object_id
  end
end

```

### Expected behavior

The `post` object should be the same object as `comment.post`, even when using scopes for the associations

We could argue that due to the scope on `belongs_to`, we do want to load a new instance when calling `comment.post`, maybe the scope would actually not return the `post` due to the condition, but even changing it to a plain `belongs_to :post` fails the test

### Actual behavior

The `post` object and the `comment.post` object are two different ruby objects of the the same (an extra query is performed when calling `comment.post`, loading the new object)

### System configuration
**Rails version**:  `7.1.0.alpha from https://github.com/rails/rails.git (at main@92fa470)`

**Ruby version**: `ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]`

**Comment by vinibispo** [comment]
I could reproduce it

**Comment by nvasilevski** [comment]
Just wanted to point out that defining association with an explicit `inverse_of` argument fixes the issue, like:
`has_many :comments, ->() { where("1=1") }, inverse_of: :post`

So presumably defining a custom scope intentionally breaks the `inverse_of`  value that is supposed to be inferred by default

**Comment by vinibispo** [comment]
> Just wanted to point out that defining association with an explicit `inverse_of` argument fixes the issue, like: `has_many :comments, ->() { where("1=1") }, inverse_of: :post`
> 
> So presumably defining a custom scope intentionally breaks the `inverse_of` value that is supposed to be inferred by default

I could reproduce it, and I agree

**Comment by vinibispo** [comment]
I think I can do this issue @pjambet
