### ISSUE TITLE
[Active-Record] Using .pluck with DISTINCT ON drops DISTINCT from the query

### ISSUE THREAD

**Issue by asad-u** [rails/rails#45516]
### Steps to reproduce

```ruby
Model.select("DISTINCT ON (table.uniq_key) table.*").pluck(:uniq_key)
# SELECT "table"."uniq_key" FROM "table"

Model.select("DISTINCT table.uniq_key").pluck(:uniq_key)
# SELECT "table"."uniq_key" FROM "table"
```

Both of the above examples return non-distinct results.

### Expected behavior

```ruby
Model.select("DISTINCT ON (table.uniq_key) table.*").pluck(:uniq_key)
# SELECT DISTINCT ON (table.uniq_key) table.* FROM "table" 

Model.select("DISTINCT table.uniq_key").pluck(:uniq_key)
# SELECT DISTINCT ON table.uniq_key FROM "table" 
```

### Actual behavior

DISTINCT ON gets dropped from the query which results in non-unique results.

### System configuration
**Rails version**: 6.1.4.4

**Ruby version**: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-musl]

**Comment by ghiculescu** [comment]
I'm going to close as this is expected, but feel free to reopen if there's any other issues here.
