### ISSUE TITLE
Getting "Connection Closed: 1006" when trying to establish a connection to ActionCable

### ISSUE THREAD

**Issue by gustavothecoder** [rails/rails#45535]
### Expected behavior
I would like my real-time chat using ActionCable to work in a production like environment using Redis as the adapter.

### Actual behavior
I'm building a real-time chat using ActionCable and it works very well locally, but when I deploy to a production like environment it stops to work. 

#### Browser
No error is displayed in the browser console, but non-stop requests to ActionCable mount point are made, and in all of them I get this response:

![ac_stg](https://user-images.githubusercontent.com/57065994/177396450-cec6164b-57c0-4f5c-ba42-cab2443d56a7.png)

#### Server logs
For each request, this is printed:
```bash
{"method":{},"path":{},"format":{},"params":null,"controller":"ApplicationCable::Connection","action":"connect","status":200,"duration":1.45}
{"method":{},"path":{},"format":{},"params":null,"controller":"ChatChannel","action":"subscribe","status":200,"duration":0.53}
```

#### Redis connection
I think the problem is here, because when I change the adapter to `async` my app works in all environments. 

Checking the connection with Redis directly from the ActionCable, I get this:
```bash
irb(main):006:0> ActionCable.server.pubsub.redis_connection_for_subscriptions.connected?
=> false
irb(main):007:0> ActionCable.server.pubsub.redis_connection_for_subscriptions._client
=> #<Redis::Client:0x000055b89df3df30 @options={"url"=>"redis://my-domain.com:6379/1", "id"=>"ActionCable-PID-2391", "scheme"=>"redis", "host"=>"my-domain.com", "port"=>6379, "path"=>nil, "timeout"=>5.0, "password"=>nil, "db"=>1, "driver"=>Redis::Connection::Ruby, "tcp_keepalive"=>0, "reconnect_attempts"=>1, "reconnect_delay"=>0.0, "reconnect_delay_max"=>0.5, "inherit_socket"=>false, "role"=>:master, "connect_timeout"=>5.0, "read_timeout"=>5.0, "write_timeout"=>5.0, "_parsed"=>true}, @reconnect=true, @logger=nil, @connection=nil, @command_map={}, @pending_reads=0, @connector=#<Redis::Client::Connector:0x000055b89df978f0 @options={"url"=>"redis://my-domain.com:6379/1", "id"=>"ActionCable-PID-2391", "scheme"=>"redis", "host"=>"my-domain.com", "port"=>6379, "path"=>nil, "timeout"=>5.0, "password"=>nil, "db"=>1, "driver"=>Redis::Connection::Ruby, "tcp_keepalive"=>0, "reconnect_attempts"=>1, "reconnect_delay"=>0.0, "reconnect_delay_max"=>0.5, "inherit_socket"=>false, "role"=>:master, "connect_timeout"=>5.0, "read_timeout"=>5.0, "write_timeout"=>5.0, "_parsed"=>true}>>
irb(main):008:0> ActionCable.server.pubsub.redis_connection_for_subscriptions.ping
Traceback (most recent call last):
        1: from (irb):8
Redis::CommandError (ERR unknown command 'client')
```
Creating a connection myself (in the same environment), I get this:
```bash
irb(main):012:0> redis_conn = Redis.new(url: "redis://my-domain.com:6379/1")
=> #<Redis client v4.1.3 for redis://my-domain.com:6379/1>
irb(main):013:0> redis_conn.connected?
=> false
irb(main):014:0> redis_conn.ping
=> "PONG"
irb(main):015:0> redis_conn.connected?
=> true
irb(main):016:0> redis_conn.publish('ChatChannel', 'test')
=> 0
```

#### My ActionCable code
I think this is all the code relevant to the problem:
```ruby
# app/channels/chat_channel.rb

class ChatChannel < ApplicationCable::Channel
  def subscribed
    stream_from 'chat_channel'
  end

  def unsubscribed; end
end
```
```ruby
# config/application.rb

config.action_cable.mount_path = '/cable'
```
```ruby
# config/cable.yml

local: &local
  adapter: redis
  url: redis://localhost:6379

development: *local

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['HOST_REDIS'] %>
```
OBS.: I've tried to putting the Redis url directly in `cable.yml` instead of using an environment variable, but I get the same error.

```ruby
# config/environments/production.rb

config.action_cable.allowed_request_origins = [/http:\/\/*/, /https:\/\/*/]
```
```ruby
# config/routes.rb

mount ActionCable.server => '/cable'
```

### System configuration
**Rails version**: 6.0.2.2
**Ruby version**: 2.6.3
**Redis**: 3.2
**Browser**: Firefox 101.0.1 (I tried Chrome too)
**OS**: Manjaro Linux

**Comment by eileencodes** [comment]
Hey @gustavothecoder can you provide a demo app that reproduces the problem?

**Comment by gustavothecoder** [comment]
I updated Redis to 5.0.14 and now it works 🤔 

Is Redis > 3.2 needed for ActionCable 6.0.2.2?

**Comment by gustavothecoder** [comment]
In [this app](https://github.com/gustavothecoder/demo-app-ac-bug) you can see the problem I'm facing, basically I just fork the [actioncable-examples](https://github.com/rails/actioncable-examples) and add a container with Redis 3.2, then the app starts crashing just like my app.
