### ISSUE TITLE
ActiveRecord: Incorrect Mysql Connection Adapter Quoting handling

### ISSUE THREAD

**Issue by dutompson** [rails/rails#45551]
### Problem

I'm running rake spec with a Mysql database named `database.name` with a dot in the middle of its name.

When the code is ran it goes through this line:

https://github.com/rails/rails/blob/3872bc0e54d32e8bf3a6299b0bfe173d94b072fc/activerecord/lib/active_record/connection_adapters/mysql/quoting.rb#L31

Then the database name is escaped like this:

``CREATE DATABASE `database`.`name` ``

But it should be:

``CREATE DATABASE `database.name` ``

### Solution

Change this:

https://github.com/rails/rails/blob/3872bc0e54d32e8bf3a6299b0bfe173d94b072fc/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L251-L266

To this:

```ruby
      def create_database(name, options = {})
        if options[:collation]
          execute "CREATE DATABASE `#{name}` DEFAULT COLLATE #{quote_table_name(options[:collation])}"
        elsif options[:charset]
          execute "CREATE DATABASE `#{name}` DEFAULT CHARACTER SET #{quote_table_name(options[:charset])}"
        elsif row_format_dynamic_by_default?
          execute "CREATE DATABASE `#{name}` DEFAULT CHARACTER SET `utf8mb4`"
        else
          raise "Configure a supported :charset and ensure innodb_large_prefix is enabled to support indexes on varchar(255) string columns."
        end
      end

      # Drops a MySQL database.
      #
      # Example:
      #   drop_database('sebastian_development')
      def drop_database(name) #:nodoc:
        execute "DROP DATABASE IF EXISTS `#{name}`"
```

### System configuration

ActiveRecord: 6.1.4.4

Ruby version: 2.5.3

**Comment by fatkodima** [comment]
Why the database is named with a dot in it? Can you use a db name with the `_`? 
Peeps on stackoverflow [are arguing](https://stackoverflow.com/questions/776123/does-mysql-allows-to-create-database-with-dot) about the described approach.

**Comment by dutompson** [comment]
I really wish I could change the database name. It would make my life easier!
But if MySQL allows a `.` in the database name then theoretically it shouldn't be escaped like in table names.
