### ISSUE TITLE
Record not touched when ActiveStorage::Blob is analyzed

### ISSUE THREAD

**Issue by natematykiewicz** [rails/rails#45567]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true do |t|
    t.timestamps
  end
end

class User < ActiveRecord::Base
  has_one_attached :profile
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_upload_and_download
    user = User.create!(
      profile: {
        content_type: "text/plain",
        filename: "dummy.txt",
        io: ::StringIO.new("dummy"),
      }
    )

    old_updated_at = user.updated_at

    # Sanity test, since some database adapters truncate microseconds
    assert_equal user.reload.updated_at, old_updated_at

    # Analyze the blob
    user.profile.blob.analyze

    # User should have been touched
    refute_equal user.reload.updated_at, old_updated_at
  end
end
```

### Expected behavior
Analyzing an ActiveStorage Blob should touch all of the models that the blob is attached to.

### Actual behavior
The model is untouched.

### System configuration
**Rails version**: 6.1.6

**Ruby version**: 2.6

### Additional Context

ActiveStorage Blobs are considered immutable. The table has no `updated_at` column, and the documentation states:

> Blobs are intended to be immutable in as-so-far as their reference to a specific file goes. You're allowed to update a blob's metadata on a subsequent pass, but you should not update the key or change the uploaded file. If you need to create a derivative or otherwise change the blob, simply create a new blob and purge the old one.

In this case, I've added an analyzer and need to update old records to have the additional metadata. This is not a new concept, as Rails added a few new analyzers in Rails 7.0.0 and presumably people would like to have this additional metadata on old records. 
I ran `ActiveStorage::Blob.find_each(&:analyze_later)` to re-analyze my records, but this did not touch my model records that they're associated to, and therefore various caches were not invalidated.

A similar problem can happen due to the fact that attachments are analyzed later. When an attachment is uploaded, `analyze_later` is called, and a background job then downloads the blob, analyzes it, and updates the `ActiveStorage::Blob` to have new metadata.

This means that it's very possible to experience this race condition:

1. Upload attachment (this will create an ActiveStorage::Blob, ActiveStorage::Attachment, and `touch` the model) 
2. Enqueue analyze job
3. Request record
4. Build a cache for that record
5. Analyze the attachment. 
6. Request the record again
7. Serve a cache that doesn't include data from the analyzers, because the cache was built before it got analyzed, and the updated_at hasn't changed.

Right now when an `ActiveStorage::Attachment` changes, the attachments's `record` is `touch`ed. I believe that when a Blob changes, all of the attachments' records should be updated as well.

I'm currently running this patch and it does what I expect. I'm wondering if this feels like a PR that Rails would be willing to accept.

```ruby
module ActiveStorageBlobTouchAssociated
  extend ActiveSupport::Concern

  included do
    after_update :touch_attachment_records, if: :saved_change_to_metadata?
  end

private

  def touch_attachment_records
    attachments.includes(:record).each do |attachment|
      attachment.record.touch
    end
  end
end

ActiveSupport.on_load :active_storage_blob do
  include ActiveStorageBlobTouchAssociated
end
```

As an aside, it does make me wonder if the table should have an `updated_at`. While the file you've uploaded to your ActiveStorage Service (like S3) cannot change, the ActiveStorage::Blob can definitely change as analyzers are added/fixed, and more metadata is extracted from the raw file.

**Comment by luanzeba** [comment]
Hey @natematykiewicz , thanks for the very detailed explanation of this issue. I think you will get more eyes on it if you open a PR with your suggested patch. I won't be able to merge it, but I'd be happy to review it

**Comment by colszowka** [comment]
Hey all,

is there a suggested way how to handle this best together with the optimistic locking feature?

As it stands, due to this change code like this starts getting "random" failures after 7.1 when the user table has a `lock_version` column, because of the touch in the background:

```ruby
user = User.create! name: "Hello"
user.avatar.attach(io: Rails.root.join("public/apple-touch-icon.png").open, filename: "avatar.png")
sleep rand
user.update! name: "World"
```

**Comment by feliperaul** [comment]
For future readers, note that #49723 added an option to restore the behavior of not touching the Attachment's associated records.

**Comment by dhanajit96** [comment]
I tried the above patch for the audited gem, It is still not working 

Even I applied the byebug to check everything but was not able to configure

**Comment by frayzil** [comment]
I've made a new gem that provides a hook after the analysis is complete.

https://rubygems.org/gems/activestorage-after_analyze_attached
https://github.com/frayzil/activestorage-after_analyze_attached
