### ISSUE TITLE
ActiveSupport:Cache:RedisCacheStore write_multi_entries with raw: true bug

### ISSUE THREAD

**Issue by nivb121** [rails/rails#45561]
At function 'write_multi_entries', at:
activesupport-6.141/lib/active_support/cache/redis_cache_store.rb line 89
entries.map returns `raw_entry.expires_at` which makes to_h function fails.
This can be fixed by returning [key, raw_entry] at the end of the mapped block.

### Steps to reproduce

```ruby
config.cache_store = :redis_cache_store

values_hash = { 'key1' => 'val1', 'key2' => 'val2' }
Rails.cache.write_multi(values_hash, { raw: true} )
```

### Expected behavior
Successful writes to Redis

### Actual behavior
Raised Exception

### System configuration
**Rails version**: 6.1.4.1

**Ruby version**: 3.0.2

**Comment by fatkodima** [comment]
rails 6 is [no longer supported](https://guides.rubyonrails.org/maintenance_policy.html), only for security issues. 
Can you verify your problem happens with the [7-0-stable](https://github.com/rails/rails/tree/7-0-stable) branch or the latest changes from the `main` branch?

**Comment by fatkodima** [comment]
> Can you verify your problem happens with the [7-0-stable](https://github.com/rails/rails/tree/7-0-stable) branch or the latest changes from the main branch?

So I tested out, this is no longer an issue and should be closed.
