### ISSUE TITLE
tag for v6.1.6 does not seem to live in this repository

### ISSUE THREAD

**Issue by thomasdziedzic-census** [rails/rails#45560]
### Steps to reproduce

Visit https://github.com/rails/rails/tree/v6.1.6 and you will see: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.".

Alternatively:

```
% git checkout v6.1.6
error: pathspec 'v6.1.6' did not match any file(s) known to git
```

### Expected behavior
Since 6.1.6 has been released, I expect there to be an associated tag in this repo. https://rubygems.org/gems/rails/versions/6.1.6

### Actual behavior
The tag `v6.1.6` doesn't seem to exist.

**Comment by fatkodima** [comment]
It belongs to `6-1-stable` branch - https://github.com/rails/rails/commits/6-1-stable.

Works for me:
```
% git fetch --all --tags
% git checkout v6.1.6
```

**Comment by thomasdziedzic-census** [comment]
Ah I see, in that case it seems unexpected because all the other tags live in main:

```
% git branch
* main
% git checkout v6.1.5.1
Note: switching to 'v6.1.5.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at e2efc667de Preparing for 6.1.5.1 release
```

**Comment by fatkodima** [comment]
> all the other tags live in main

Try to switch to the latest release
```
% git checkout v7.0.3
```

**Comment by thomasdziedzic-census** [comment]
That works as expected.

```
% git branch
* main
% git checkout v7.0.3
Note: switching to 'v7.0.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 3872bc0e54 Preparing for 7.0.3 release
```

**Comment by fatkodima** [comment]
What are the differences between https://github.com/rails/rails/issues/45560#issuecomment-1180405210 and https://github.com/rails/rails/issues/45560#issuecomment-1180411518 ?

**Comment by thomasdziedzic-census** [comment]
For https://github.com/rails/rails/issues/45560#issuecomment-1180405210 I was demonstrating that for the previous 6.1.x release before 6.1.6, the tag works as expected.

For https://github.com/rails/rails/issues/45560#issuecomment-1180411518 I was replying to https://github.com/rails/rails/issues/45560#issuecomment-1180409255 because you said to try the command, so I did and posted my experience.

**Comment by matthewd** [comment]
Looks like an error in the history: the tag is pointing to 147557dc16a5bd8bab96f999f359a570232e1873, while the branch contains d42b549de66988eecfca36e5581885e82d1b6d87. 

They both have the same parent, but differ in that d42b549de66988eecfca36e5581885e82d1b6d87 contains the changelog headers that 147557dc16a5bd8bab96f999f359a570232e1873 was missing.

**Comment by fatkodima** [comment]
@matthewd Sorry for the offtopic, seems like you missed a notification, but can you please give a comment at https://github.com/rails/rails/pull/45381#discussion_r899200518?

**Comment by eileencodes** [comment]
Oh this is my bad. That release was a disaster because I typed the wrong OTP code and the release failed half way through. Then the changelog headers got missed somehow. If I push the tags again will that fix it?

**Comment by p8** [comment]
@eileencodes I think you first need to delete the remote tag before you can push: `git push --delete origin v6.1.6`, but I think that should fix it.

**Comment by simi** [comment]
:information_source: seems fixed https://github.com/rails/rails/releases/tag/v6.1.6
