### ISSUE TITLE
Rails `button_to` form submission is detected as format turbo-stream incorrectly after redirect

### ISSUE THREAD

**Issue by Ikariusrb** [rails/rails#45566]
### Steps to reproduce
Generate a rails 7 application  (`rails new myapp`), scaffold a model (`rails g scaffold my_model`), update the index method in the model controller to respond to both HMTL and turbo_stream:

```
  def index
    respond_to do |format|
      format.html { @my_models = MyModel.all }
      format.turbo_stream { raise StandardError.new('Wrong format!') }
    end
  end
```

Create a single model on console (MyModel.new.save!) , and go to the show page for it (http://localhost:3000/my_models/1) - now click the "destroy this MyModel" button

### Expected behavior
The MyModels index page should be rendered from the `redirect_to` of the form delete submission.
### Actual behavior
The index method executes the turbo_stream format block, and raises an exception.
### Notes
The `button_to` helper generates the following form: 
```
<form class="button_to" method="post" action="/mymodels/2"><input type="hidden" name="_method" value="delete" autocomplete="off"><button type="submit">Destroy this my_model</button></form>
```
When that form is submitted, the following header is set on the request: 
```
Accept: text/vnd.turbo-stream.html, text/html, application/xhtml+xml
```
That accept header carries over to the GET following the redirect from the delete handler, and then it appears that Rails concludes the request format is `turbo-stream` rather than `html`.

I have dropped debugging breakpoints in both the html and turbo-stream blocks for the controller index method and determined that the html format block is never called, only the turbo-stream format block. 

There are no turbo-frames anywhere in the HTML in this reproduction.

### System configuration
rails version: **7.0.3**

ruby version: **3.1.2**

**Comment by robzolkos** [comment]
I suspect that its the browser that keeps the original `Accept` header in place during the redirect not Rails (meaning that its browser behaviour not a Rails bug but someone smarter than I can chime in).

Rails will default to responding with html if there is no explicit handling of turbo stream format so I haven't yet been bit by this (yet).  Can also disable turbo on the delete button.

**Comment by Ikariusrb** [comment]
There's no turbo-frames in the generated templates whatsoever.   The default generated `delete` controller method handles either html or turbo-stream formats, and is detecting format of html.  It then issues a redirect, which is detected as format `turbo-stream` if the redirect target handles both turbo stream and html. The fact that the detected format is switching after a redirect seems like a bug.

I did however, determine that adding `data: { turbo: false}` to the `button_to` on the show page will successfully keep the format as `html` after the redirect.

**Comment by robzolkos** [comment]
The _detected_ format isn't switching - it's just being responded to by a fallback handler (html).  You are however _explicitly_ handling the turbo_steam format in the index action.

So the flow goes

DESTROY (`text/vnd.turbo-stream.html, text/html` accept header)
1. ->   does a `turbo_stream` handler exist?  no, try with next accept header
2. ->   does a `html` handler exist? yes, redirect to index action (keep same accept header)

INDEX 
3. ->   does a `turbo_stream` handler exist?  yes,  handle...


I think your expectation is that the fallback handler continue to be used after the redirect but I think that would be surprising behaviour if you had handlers in place for the original requested format in other actions.

**Comment by Ikariusrb** [comment]
Oh good grief. you're right.  The formats handled by the generated `destroy` method are `html` and `json`, there's no `turbo_stream` handler.  I have verified that the destroy method also selects turbo stream if a handler for that format exists.   So I guess the only surprising behavior is that `button_to` form submits a request that defaults to turbo-stream format.

**Comment by robzolkos** [comment]
Yep - by including turbo-rails all form submissions are handled by turbo - which can be then _explicitly_ disabled per form.
