### ISSUE TITLE
MISSING_TRANSLATION from ActionView::Helpers::TranslationHelper is cached in the I18n cache and read back as a different Object

### ISSUE THREAD

**Issue by rocket-turtle** [rails/rails#45571]
We try upgrading to Rails 6.1 and have the following Problem.
If we call something like `t('some_untranslated_key', default: :hello)` in a view twice the result changes.
This can be reproduced with Rails Rails 7.0.3.

```
(ruby) t('some_untranslated_key', default: :hello)
"Hello world"
(ruby) t('some_untranslated_key', default: :hello)
#<Object:0x00007f96ec466ce0>
```

It might be related to this change https://github.com/rails/rails/commit/d81926fdacbeb384d211e22cff66195c1a753eb5.
The `translated` value from the I18n cache is not `true` for `translated.equal?(MISSING_TRANSLATION)`
The problem is not related to the `default` so I left it out for the example code.

### Steps to reproduce

-  Setup new Rails 7.0.3 application
-  Add i18n caching
-  Put two times the same untranslated i18n call into the view.

```
diff --git a/config/initializers/i18n_cache.rb b/config/initializers/i18n_cache.rb
new file mode 100644
index 0000000..4e305d6
--- /dev/null
+++ b/config/initializers/i18n_cache.rb
@@ -0,0 +1,3 @@
+I18n::Backend::Simple.send(:include, I18n::Backend::Cache)
+
+I18n.cache_store = ActiveSupport::Cache.lookup_store(:memory_store)
```

```
railties-7.0.3/lib/rails/templates/rails/welcome/index.html.erb
  <%= t('foo') %>
  <%= t('foo') %>
```

### Expected behavior
Prints the key of the translation two times

### Actual behavior
Prints the key on the first call and an object on the second call

```
Foo
#<Object:0x00007fbece7dc668>
```

### System configuration
**Rails version**: 7.0.3
**Ruby version**: ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-darwin21]

### Analysis
**First call to t('foo')**

actionview/lib/action_view/helpers/translation_helper.rb#translate
- sets `default = MISSING_TRANSLATION`
- `default` is `#<Object:0x00007fbece12c3b8>`
- calls `translated = ActiveSupport::HtmlSafeTranslation.translate(key, **options, default: default)`

activesupport/lib/active_support/html_safe_translation.rb#translate
- calls `I18n.translate(key, **options)`

i18n-1.11.0/lib/i18n.rb#translate
- calls `translate_key(key, throw, raise, locale, backend, options)`

i18n-1.11.0/lib/i18n.rb#translate_key
- calls `backend.translate(locale, key, options)`

i18n-1.11.0/lib/i18n/backend/cache.rb#translate
- `I18n.perform_caching?` is `true`
- calls `fetch(cache_key(locale, key, options)) { super }`

i18n-1.11.0/lib/i18n/backend/cache.rb#fetch
- calls `result = _fetch(cache_key, &block)`
- `result` is `#<Object:0x00007fbece12c3b8>`

i18n-1.11.0/lib/i18n/backend/cache.rb#_fetch
- calls `result = I18n.cache_store.read(cache_key)`
- `result` is `nil`
- ...
- calls `result = catch(:exception, &block)`
- `result` is `#<Object:0x00007fbece12c3b8>` that is the same as `MISSING_TRANSLATION`

When I call `I18n.cache_store.read(cache_key)` now or later with a second call to `t('foo')` the result allways changes.
Example: `#<Object:0x00007fbedd3a9ed8>`

**Second call to t('foo')**

actionview/lib/action_view/helpers/translation_helper.rb#translate
- calls `translated = ActiveSupport::HtmlSafeTranslation.translate(key, **options, default: default)`
- `translated` is `#<Object:0x00007fbece7dc668>` and `translated.equal?(MISSING_TRANSLATION)` is `false`

**Comment by jonathanhefner** [comment]
It would be good to fix this, however, @rocket-turtle, have you benchmarked your app / view to see if using `I18n::Backend::Cache` is actually faster?

Given how [`translate` is implemented](https://github.com/rails/rails/blob/3cbc7279fbbe3d941f1b0aac4bc13c1620c3c4eb/actionview/lib/action_view/helpers/translation_helper.rb#L73-L93) (by looping over individual keys), I wonder if any cache-related performance gains are outweighed by the cost of serializing / deserializing `MISSING_TRANSLATION` (whatever its value) when the first key isn't found.

**Comment by rocket-turtle** [comment]
@jonathanhefner I'm not sure if my benchmark is correct.

Thats what I tried:

On app startup I redefined the `MISSING_TRANSLATION`.  Please let me know if there is a better solution.
```
require 'action_view/helpers/translation_helper'

ActionView::Helpers::TranslationHelper.send(:remove_const, 'MISSING_TRANSLATION')
ActionView::Helpers::TranslationHelper.const_set('MISSING_TRANSLATION', -1327903252)
```

I added an `byebug` to the view to make my benchmarks in that context.
```
(byebug) ActionView::Helpers::TranslationHelper::MISSING_TRANSLATION
-1327903252
```

I was not sure how to deaktivate the cache for one test batch so I testet that setting and resetting the cache is the same speed.
```
require 'benchmark/ips'
cache = I18n.cache_store

Benchmark.ips do |x|
  x.report('set cache') { I18n.cache_store = cache }
  x.report('set nil') { I18n.cache_store = nil }
  x.compare!
end
```

> Calculating -------------------------------------
>            set cache      7.504M (± 6.7%) i/s -     37.918M in   5.079031s
>              set nil      7.700M (± 3.3%) i/s -     38.906M in   5.058401s
> 
> Comparison:
>              set nil:  7699738.1 i/s
>            set cache:  7504204.4 i/s - same-ish: difference falls within error

**benchmark in the view context: cache / no cache**
```
require 'benchmark/ips'
cache = I18n.cache_store

Benchmark.ips do |x|
  x.report('with cache') do
    I18n.cache_store = cache
    t('body', scope: 'devise.mailer.confirmation_instructions')
  end
  x.report('with cache - missing') do
    I18n.cache_store = cache
    t('foo', scope: 'devise.mailer.confirmation_instructions')
  end
  x.report('with cache - default') do
    I18n.cache_store = cache
    t('foo', default: :body, scope: 'devise.mailer.confirmation_instructions')
  end
  x.report('with cache - count') do
    I18n.cache_store = cache
    t('missing_key', default: :grades, scope: 'attributes', count: 1)
  end

  x.report('no cache') do
    I18n.cache_store = nil
    t('body', scope: 'devise.mailer.confirmation_instructions')
  end
  x.report('no cache - missing') do
    I18n.cache_store = nil
    t('foo', scope: 'devise.mailer.confirmation_instructions')
  end
  x.report('no cache - default') do
    I18n.cache_store = nil
    t('foo', default: :body, scope: 'devise.mailer.confirmation_instructions')
  end
  x.report('no cache - count') do
    I18n.cache_store = nil
    t('missing_key', default: :grades, scope: 'attributes', count: 1)
  end
  x.compare!
end
```

> Calculating -------------------------------------
>           with cache     50.060k (± 4.3%) i/s -    251.784k in   5.039008s
> with cache - missing     17.515k (± 4.6%) i/s -     87.550k in   5.009492s
> with cache - default     26.385k (± 3.6%) i/s -    132.500k in   5.028396s
>   with cache - count     26.164k (± 4.0%) i/s -    133.000k in   5.091836s
>             no cache     32.818k (± 3.5%) i/s -    164.750k in   5.026334s
>   no cache - missing      8.864k (± 3.8%) i/s -     45.186k in   5.105620s
>   no cache - default      9.682k (± 3.5%) i/s -     48.900k in   5.056655s
>     no cache - count      6.810k (± 8.8%) i/s -     34.028k in   5.041290s
> 
> Comparison:
>           with cache:    50060.4 i/s
>             no cache:    32818.0 i/s - 1.53x  (± 0.00) slower
> with cache - default:    26385.0 i/s - 1.90x  (± 0.00) slower
>   with cache - count:    26163.7 i/s - 1.91x  (± 0.00) slower
> with cache - missing:    17515.2 i/s - 2.86x  (± 0.00) slower
>   no cache - default:     9681.9 i/s - 5.17x  (± 0.00) slower
>   no cache - missing:     8863.5 i/s - 5.65x  (± 0.00) slower
>     no cache - count:     6809.6 i/s - 7.35x  (± 0.00) slower

**benchmark: view context / plain i18n**
```
require 'benchmark/ips'
cache = I18n.cache_store

Benchmark.ips do |x|
  x.report('action_view') do
    t('body', scope: 'devise.mailer.confirmation_instructions')
  end
  x.report('action_view - missing') do
    t('foo', scope: 'devise.mailer.confirmation_instructions')
  end
  x.report('action_view - default') do
    t('foo', default: :body, scope: 'devise.mailer.confirmation_instructions')
  end
  x.report('action_view - count') do
    t('missing_key', default: :grades, scope: 'attributes', count: 1)
  end
  x.report('plain i18n') do
    I18n.t('body', scope: 'devise.mailer.confirmation_instructions')
  end
  x.report('plain i18n - missing') do
    I18n.t('foo', scope: 'devise.mailer.confirmation_instructions')
  end
  x.report('plain i18n - default') do
    I18n.t('foo', default: :body, scope: 'devise.mailer.confirmation_instructions')
  end
  x.report('plain i18n - count') do
    I18n.t('missing_key', default: :grades, scope: 'attributes', count: 1)
  end
  x.compare!
end
```

> Calculating -------------------------------------
>          action_view     52.796k (± 2.7%) i/s -    265.353k in   5.029629s
> action_view - missing
>                          18.126k (± 3.1%) i/s -     91.450k in   5.050012s
> action_view - default
>                          27.685k (± 2.7%) i/s -    138.650k in   5.011764s
>  action_view - count     27.603k (± 2.8%) i/s -    139.050k in   5.041465s
>           plain i18n     71.182k (± 3.0%) i/s -    355.950k in   5.005021s
> plain i18n - missing     31.379k (± 3.5%) i/s -    159.588k in   5.092241s
> plain i18n - default     66.691k (± 3.0%) i/s -    338.310k in   5.077470s
>   plain i18n - count     66.371k (± 2.9%) i/s -    331.900k in   5.004762s
> 
> Comparison:
>           plain i18n:    71182.2 i/s
> plain i18n - default:    66690.5 i/s - 1.07x  (± 0.00) slower
>   plain i18n - count:    66370.9 i/s - 1.07x  (± 0.00) slower
>          action_view:    52796.3 i/s - 1.35x  (± 0.00) slower
> plain i18n - missing:    31379.1 i/s - 2.27x  (± 0.00) slower
> action_view - default:    27685.4 i/s - 2.57x  (± 0.00) slower
>  action_view - count:    27603.3 i/s - 2.58x  (± 0.00) slower
> action_view - missing:    18125.8 i/s - 3.93x  (± 0.00) slower
