### ISSUE TITLE
System test with importmap

### ISSUE THREAD

**Issue by rzepetor** [rails/rails#45610]
### Steps to reproduce
I have a "Sign up" link that has `data-turbo-frame` attribute, when test starts sometimes click is not intercepted by Turbo and nothing happens, but sometimes test run normally. 

I also noticed that on development server if I refresh website and quickly click "Sign up" button also nothing happens. I must wait some time (maybe second) to be able to Turbo works

### Expected behavior
Capybara tests should always starts only when all JS modules are loaded

### Actual behavior
Sometimes JS modeles are not loaded before test starts

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**Comment by spam100011** [comment]
7(#??7??6!6?
6?#6??*?
7?#6?6!
7+

**Comment by spam100011** [comment]
ykkuwky

**Comment by spam100011** [comment]
+opqowow

**Comment by skipkayhil** [comment]
Do you have a repo/reproduction where you can show this happening? It's very hard to figure out what is going wrong without one
