### ISSUE TITLE
Explicitly touch on save

### ISSUE THREAD

**Issue by schmijos** [rails/rails#45639]
### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  ruby "3.1.0"
  gem "rails", "7.0.3.1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.timestamps
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_save_touch
    Post.create!(updated_at: 3.days.ago)
    Post.last.save!(touch: true)

    assert_in_delta 0.seconds.ago.to_i, Post.last.updated_at.to_i, 5
  end
end
```

### Expected behavior
If I tell _ActiveRecord_ to explicitly "touch", then I would expect it to update the timestamps.

### Actual behavior
`save` never hits the database if no attribute changed.

### System configuration
**Rails version**: >= 3.0.0, < 8

**Comment by fatkodima** [comment]
I think, you should use [`touch`](https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-touch) for this.

**Comment by skipkayhil** [comment]
To expand on fatkodima's answer a bit: the default behavior for `save!` is that it would update the `updated_at` time if attributes are updated, and you can pass `touch: false` to prevent it from doing that (so `touch: true` is the default).

**Comment by schmijos** [comment]
> `touch: true` is the default

That's my point. `touch: true` without any other changed attributes doesn't "touch". Don't you think this is misleading? If I tell it to touch, it should touch.
