### ISSUE TITLE
Recent security releases are missing from the Releases page

### ISSUE THREAD

**Issue by georgeclaghorn** [rails/rails#45635]
Rails versions 7.0.3.1, 6.1.6.1, 6.0.5.1, and 5.2.8.1 are not listed at this GitHub repository’s [Releases](https://github.com/rails/rails/releases) page. Past releases are listed there, including the most recent round of bugfix releases from May.

**Comment by rafaelfranca** [comment]
Thank you @georgeclaghorn. I'll make sure that page is up-to-date and next releases don't forgot to do it.

**Comment by rafaelfranca** [comment]
Done finally.
