### ISSUE TITLE
Check if database constraint exists before attempting to remove

### ISSUE THREAD

**Issue by eudaimonious** [rails/rails#45634]
I love the new ability to add and remove constraints. I can't use the remove_constraint feature as intended however. I can not guarantee that the constraint will exist on every environment the migration is run and the remove_constraint method is designed to raise an error if the the constraint does not exist. What about if, instead, we check whether the constraint exists, and if it does remove it, otherwise no-op

[Relevant PR.](https://github.com/rails/rails/pull/31323)

**Comment by fatkodima** [comment]
I think, we should add a new method - `check_constraint_exists?` (similar to `index_exists?` or `foreign_key_exists?`) and, additionally, an `if_exists` option to the `remove_check_constraint` (like for indexes and foreign keys is already done).

Would you like to open a PR?

**Comment by eudaimonious** [comment]
yes!

**Comment by fatkodima** [comment]
@eudaimonious Are you working on a PR?

**Comment by AdityaBhutani** [comment]
I can work on it if not a problem. Have been trying to understand `activerecord` and it's flow for a couple of days.

**Comment by eudaimonious** [comment]
Yep, I'm already on it!
