### ISSUE TITLE
value that fails to cast for a JSON column is silently set to nil

### ISSUE THREAD

**Issue by tjwp** [rails/rails#45641]
### Steps to reproduce

Assign to a JSON column a value that cannot be cast, serialized and deserialized. 

The value will first be cast by calling serialize, followed by deserialize: 
https://github.com/rails/rails/blob/main/activemodel/lib/active_model/type/helpers/mutable.rb#L8

When deserialize fails for a JSON value, the error is rescued and nil is returned:
https://github.com/rails/rails/blob/main/activerecord/lib/active_record/type/json.rb#L14

This results in the attribute being set to nil with no indication that there was an error.

One way that a value can fail to be cast as JSON is that it is too deeply nested.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.json :data
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_setting_json_column
    post = Post.new

    # Generate a hash that serializes to JSON < 100 bytes
    post.data = BigJson.serializable_hash
    refute_equal nil, post.data, "small JSON is set correctly"

    # Generate a deeply nested hash. The size here is large enough demonstrate the issue,
    # but the error is due to nesting, not the size specifically.
    nested_hash = BigJson.serializable_hash(30_000)

    # Identify the error that is silently discarded when casting to ActiveModel::Type::Json
    begin
      ActiveSupport::JSON.decode(ActiveSupport::JSON.encode(nested_hash))
    rescue => error
    end
    assert_equal JSON::NestingError, error.class
    assert_equal "nesting of 101 is too deep", error.message

    # Assigning the deeply nested hash will fail to cast as demonstrated above, and the
    # attribute is silently set to nil
    post.data = nested_hash
    refute_equal nil, post.data, "deeply nested JSON is not silently set to nil"
  end
end

class BigJson
  def self.serializable_hash(max_size = 100, current = nil)
    current ||= { key: "a" }
    if current.to_json.size < max_size
      serializable_hash(max_size, { key: "a", previous: current })
    else
      current
    end
  end
end
```

### Expected behavior

An error should be raised instead of silently setting the attribute to nil and discarding the data.

In the reproduction above the underlying error is `#<JSON::NestingError: nesting of 101 is too deep>`.

### Actual behavior

The attribute is set to nil, and if the record is saved, and the model allows, the column is set to NULL.

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.1.2

**Comment by fatkodima** [comment]
Looks like this is an established pattern: see https://github.com/rails/rails/blob/main/activemodel/lib/active_model/type/integer.rb or https://github.com/rails/rails/blob/main/activemodel/lib/active_model/type/date.rb and even more types there.

I think this is done to protect the application from failing when malicious users provide invalid values.

**Comment by tjwp** [comment]
> Looks like this is an established pattern:

What is surprising in this case is that outwardly the data is valid. It can be serialized as JSON. The failure can be attributed to the internal implementation and not to the value being invalid. In fact, this might succeed if a different JSON encoder is configured.

**Comment by tjwp** [comment]
Today I learned about the standardized error reporter: https://github.com/rails/rails/pull/43625

Perhaps the serialization error would be a good use case for that, changing error handling here: https://github.com/rails/rails/blob/main/activerecord/lib/active_record/type/json.rb#L14 to:

```ruby
Rails.error.handle(fallback: -> { nil }) { ActiveSupport::JSON.decode(value) }
```

(Probably with `Rails.error` replaced by `ActiveRecord.error` when that is available.)

**Comment by rafaelfranca** [comment]
I don't think we should be special casing JSON serialization on attribute assignment. Every single input that could not be deserialized to the corresponding Ruby type will be set to `nil`. This is the API of the framework since forever.

If we as a framework were to report JSON decoding error we should do with all other types and I think this will just increase noise in the error reporting, since most values for those attributes are set by user input, which could be malicious or full of typos, which would cause a lot of exceptions.

The layer to perhaps capture those errors and log or even tell the user that the input is incorrect is by defining a validation.
