### ISSUE TITLE
enum definition silences UnknownAttributeError & misbehaves with outdated schema cache

### ISSUE THREAD

**Issue by klyonrad** [rails/rails#45668]
Defining an enum to a ActiveRecord model has the affect that typical safeguards / checks for *unknown attributes* are bypassed, for example when there was a typo in the database migration related to an enum.

**How was this observed?**

A process (example a worker processor like sidekiq), which had the enum definition loaded already, and another process/system changed the database with a migration, adding the column for which the enum was defined. Later on expected data was not stored into the database (instead the default value for the column). Assumption: Since the background process did not refresh the schema cache it ignores the change for the enum attribute. But because `Enum` module defines an `attribute` activerecord considers it not a problem that the column is not really present.

**Comment:**

I would totally understand if this considered an extreme edge case but I just thought it would be worthwhile to report. While thinking about about a potential solution, I realize that a potential solution is not even obvious. Should the enum definition cause an error when the model is loaded? Should every update to an Enum attribute check whether or not the column exists?

### Steps to reproduce

- define enum attribute in model for a non existing column name
- try to store a value into this attribute with the same name
- no error is raised. The desired data is not stored

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
# ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: "rails_enum_bug.sqlite")
# ActiveRecord::Base.establish_connection(adapter: "mysql2", database: "rails_enum_bug_report", username: 'root', host: '127.0.0.1')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  enum :wrong_attributee, [:default_value, :middle_value, :other_value]
end

class AddAttributeToPosts < ActiveRecord::Migration[7.0]
  def change
    add_column :posts, :wrong_attrib, :integer, default: 0
  end
end

class AddEnumToPosts < ActiveRecord::Migration[7.0]
  def change
    add_column :posts, :wrong_attributee, :integer, default: 0
  end
end

class BugTest < Minitest::Test
  def test_with_outdated_schema_cache
    assert_equal ["id"], Post.column_names # to load schema cache
    AddAttributeToPosts.migrate(:up)
    AddEnumToPosts.migrate(:up)
    assert_equal ["id"], Post.column_names
    new_post = Post.create!(wrong_attributee: :other_value) # column is not in the schema cache, so why no error?
    Post.reset_column_information

    assert_equal "default_value", new_post.reload.wrong_attributee # database default is used
    assert_equal "other_value", new_post.reload.wrong_attributee # actual value is 0 (sqlite default)
  end

  def test_unknown_attribute
    AddAttributeToPosts.migrate(:up)
    Post.reset_column_information

    # expected/normal behaviour
    assert_raises(ActiveModel::UnknownAttributeError) do
      Post.create!(wrong_attribute: :other_value)
    end
    new_post = Post.create!(wrong_attributee: :other_value) # bug, this should raise an error

    assert_nil new_post.reload.wrong_attributee
    assert_nil new_post.reload.wrong_attrib
    assert_equal "other_value", new_post.reload.wrong_attributee # not really expected behaviour :)
  end

  def teardown
    Post.delete_all
    AddAttributeToPosts.migrate(:down)
    AddEnumToPosts.migrate(:down) if ActiveRecord::Base.connection.column_exists?(:posts, :wrong_attributee)
    Post.reset_column_information
  end
end

```

### Expected behavior

- UnknownAttributeError would get raised at *some point* 

### Actual behavior

- no error is raised
- record gets created/modified without the desired value
- in the case of a successful migration for a column with a default value but a missing schema cache update, the record gets created without the desired data in that column but the default value

### System configuration
**Rails version**:

7

**Ruby version**:

3

**Comment by fatkodima** [comment]
So both problems can be fixed  by checking if the column exists before assigning to the enum:
 
```diff
diff --git a/activerecord/lib/active_record/enum.rb b/activerecord/lib/active_record/enum.rb
index 8597efc49b..6152b21bd9 100644
--- a/activerecord/lib/active_record/enum.rb
+++ b/activerecord/lib/active_record/enum.rb
@@ -198,6 +198,11 @@ def _enum(name, values, prefix: nil, suffix: nil, scopes: true, **options)

         value_method_names = []
         _enum_methods_module.module_eval do
+          define_method("#{name}=") do |value|
+            raise UnknownAttributeError.new(self, name) unless self.class.columns_hash.key?(name)
+            super
+          end
+
           prefix = if prefix
             prefix == true ? "#{name}_" : "#{prefix}_"
           end
```

If core people agree with this solution, I will open a PR.

**Comment by heaven** [comment]
This was an absolutely terrible decision.
