### ISSUE TITLE
Rails.application.config.active_record.has_many_inversing config not applied until load_defaults value is changed to 6.1

### ISSUE THREAD

**Issue by alexadia** [rails/rails#45683]
### Steps to reproduce

* Uncomment `Rails.application.config.active_record.has_many_inversing = true` in file config/initializers/new_framework_defaults_6_1.rb. 
* In config/application.rb, set `config.load_defaults` to 6.0 (no string). Ex: `config.load_defaults 6.0`. 

In a rails console run 
```ruby
Rails.application.config.active_record.has_many_inversing
ActiveRecord::Base.has_many_inversing
```

### Expected behavior

The output for both commands below should be true so that has_many_inversing is turned on.

```ruby
Rails.application.config.active_record.has_many_inversing
ActiveRecord::Base.has_many_inversing
```

### Actual behavior

* Only `Rails.application.config.active_record.has_many_inversing` returned true. 
* Whereas `ActiveRecord::Base.has_many_inversing` returned false. 

Hence the feature `has_many_inversing` wasn't on when `config.load_defaults` was 6.0, even though `Rails.application.config.active_record.has_many_inversing` was set to true in config/initializers/new_framework_defaults_6_1.rb. 

The feature has_many_inversing was only turned on once I deleted the file config/initializers/new_framework_defaults_6_1.rb and changed `config.load_defaults` from 6.0 to 6.1. 

This caused a spec related to `has_many_inversing` to only fail once load_defaults was changed to 6.1. On the branch with load_defaults set to 6.1, setting `has_many_inversing` to false fixed the spec.

### System configuration
**Rails version**: 6.1.6.1

**Ruby version**: 2.7.2p137

**Comment by ghiculescu** [comment]
@alexadia Thanks for the report, I think this is a known issue in 6.1. In 7 it should be resolved by https://github.com/rails/rails/pull/42499.

**Comment by alexadia** [comment]
Awesome!
