### ISSUE TITLE
Attribute assignment fails after ActiveRecord::Persistence#becomes 

### ISSUE THREAD

**Issue by caiohsramos** [rails/rails#45702]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org/"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :parents, force: true do |t|
    t.string :type
  end
end

class Parent < ActiveRecord::Base
end
class Child1 < Parent
  attribute :name
end
class Child2 < Parent
  attribute :email
end

class BugTest < Minitest::Test
  def test_becomes
    c1 = Child1.create!
    c2 = c1.becomes(Child2)
    c2.email = "test@test.com"
  end
end
```

### Expected behavior

Should not raise `ActiveModel::MissingAttributeError` and assign the attribute
### Actual behavior

Raises `ActiveModel::MissingAttributeError` and doesn't assign the attribute
### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.1.1

**Comment by fatkodima** [comment]
From my understanding, `becomes` should be really used for conversions between parent-child or child-parent, not like child-child as in your example.

So the following works for me:
```ruby
class Parent < ActiveRecord::Base
  attribute :name
end
class Child < Parent
  attribute :email
end

class BugTest < Minitest::Test
  def test_becomes
    c = Child.create!
    p = c.becomes(Parent)
    p.name = "test"
    p.email = "test@test.com"
  end
end
```

What is the usecase for converting between childs?

**Comment by haffla** [comment]
`child.becomes(Parent)`

I believe it's only meant to be used **up** the ancestor chain. If you look at the source of `becomes` it basically only instantiates a new instance of `Parent` and sets the attributes of the `child` instance on that new instance. That's it.

Everything else wouldn't make sense. Imagine an instance of `Car < Vehicle` becomes a `Bicycle < Vehicle`. Now it's a `Bicycle` but should still have all methods that `Car` has? So it's both a `Car` and a `Bicycle` now?
