### ISSUE TITLE
Incorrect installation command for webpacker

### ISSUE THREAD

**Issue by pkayokay** [rails/rails#45703]
### Steps to reproduce

- Visit ["Install Webpacker"](https://guides.rubyonrails.org/webpacker.html#installing-webpacker)

### Expected behavior
- "To include Webpacker in a new project, add `-j webpack`..."

### Actual behavior
- "To include Webpacker in a new project, add `--webpack`..."

https://github.com/rails/jsbundling-rails/#installation

`rails new myapp -j [esbuild|rollup|webpack].`

**Comment by skipkayhil** [comment]
Webpacker refers to the [gem](https://github.com/rails/webpacker) that was the default in Rails 6, and is different than jsbundling-rails' Webpack, so I think these docs are technically correct. 

There's an open PR to modernize the asset pipeline documentation at #45400, so I'm going to close this. However, feel free to provide feedback over there.
