### ISSUE TITLE
Rails Active Storage image variant flipped upside down

### ISSUE THREAD

**Issue by zaouch** [rails/rails#45713]
When rendering a rails active storage image variant as follows:

```ruby
<%=image_tag(current_user.avatar.variant(resize_to_limit:[200, 200])) %>
```
The image gets flipped upside down. I have tried to remove the EXIF metadata by setting the `auto_orient` option as `true` like suggested [here](https://rubyflow.com/p/qqivs1-activestorage-variants-are-persisting-original-image-exif-metadata) without success. This is definitely a rails bug because as soon as I remove the variant method, the original image displays correctly.

Note that I am uploading picture captured by iphone devices. Here is [the image I used](https://easyupload.io/9fu47q).

### Expected behavior
Resized Image variant should be displayed as is. 

### Actual behavior
Resized Image variant is displayed flipped upside down.

### System configuration
**Rails version**: 6.1.5

**Ruby version**: 3.1.1p18

**Comment by fatkodima** [comment]
Tested on rails `main` - works correctly for me 
<img width="280" alt="Screen Shot 2022-07-31 at 14 29 20" src="https://user-images.githubusercontent.com/5657035/182024165-697103da-515e-4d99-8f63-33441803e080.png">

Can you verify your problem on the latest rails version? If it persists, can you create a small reproduction app and share with us?

**Comment by zaouch** [comment]
I've finally solved the problem by updating the backend the `image_processing` gem was using under the hood on my local machine. So, it was not really a rails issue, but something worth keeping in mind when using Active storage variants.
