### ISSUE TITLE
Model.upsert_all raises ArgumentError if passed an empty array

### ISSUE THREAD

**Issue by dhnaranjo** [rails/rails#45710]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    empty_array = []
    Post.create(empty_array)

    assert_raises(ArgumentError) do
      Post.upsert_all(empty_array)
    end
  end
end

```

Which like... is on purpose as we can see in this lil snip, but why?

https://github.com/rails/rails/blob/d96609505511a76c618dc3adfa3ca4679317d008/activerecord/lib/active_record/insert_all.rb#L5-L11

### Expected behavior
Nothing happens, same as `Model.create` when passed an empty array. Or like... most things that accept arrays.

### Actual behavior
Raises `initialize: Empty list of attributes passed (ArgumentError)`

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.1.2

**Comment by fatkodima** [comment]
That makes sense for me as well (considering the `create` method works this way).
The change was introduced in https://github.com/rails/rails/commit/ba795c9e4acc3954f52ad9f4d1059964a51cdce0.
@kaspth Can you recall the details of that change?

**Comment by byroot** [comment]
I agree that it would be more consistent to just noop.

I'll probably change this tomorrow if I don't forget, but I'd also take a PR.
