### ISSUE TITLE
Testing an invalid resource as turbo_stream format

### ISSUE THREAD

**Issue by david-hello-world** [rails/rails#45725]
I've faced what I think is an inconsistency between testing an invalid resource in an integration test, and testing it using the browser. Explanation:

I have this create action (modified from a scaffold generated by Rails):

```ruby
def create
  @post = Post.new(post_params)

  respond_to do |format|
    if @post.save
      format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
      format.json { render :show, status: :created, location: @post }
      format.turbo_stream
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @post.errors, status: :unprocessable_entity }
    end
  end
end
```

In the browser this works correctly:

- If post is valid, it responds as turbo-stream, adding the new post to the list with JS.
- If post is invalid, it displays the "error prohibited this post from being saved" message, and lists the validation error/s **responding as turbo-stream as well.**

I want to focus on the second case, when the post is invalid. The request is a post method, using a fetch type, which is correct. And it gets a 422 status in the response, using a turbo-frame.

Then I have this integration test:

```ruby
class CreatePostTest < ActionDispatch::IntegrationTest
  def post_params
    { title: 'Some title',
      body: 'Some text' }
  end

  test 'cannot create an invalid post' do
    post posts_path(format: :turbo_stream),
          params: { post: { title: '', body: '' } }

    assert_response 422
  end

  test 'create a valid post' do
    post posts_path(format: :turbo_stream),
          params: { post: { title: 'Some title', body: 'Some text' } }

    assert_response 200
  end
end
```

After running it, the "valid post" test passes, but the invalid one fails with this error:

> Error: CreatePostTest#test_cannot_create_an_invalid_post: ActionController::UnknownFormat: ActionController::UnknownFormat app/controllers/posts_controller.rb:26:in 'create' test/integration/create_post_test.rb:12:in 'block in class:CreatePostTest'

So it's basically saying that it doesn't know how to respond with turbo-stream format. This is expected because the `else` in the controller doesn't implement the `turbo_stream` format. The solution is to remove `format: :turbo_stream` from the `posts_path`.

Why must I specify the path without a format (and therefore default to HTML), and in the browser it works correctly responding as turbo-stream? Isn't this an inconsistency?

**Comment by gardnerapp** [comment]
It's not an issue or inconsistency with the framework. Your invalid test is specifying a format that does not exist at the controller level, that is why you are getting an unknown format error. if you add ```format.turbo_stream ``` to your else clause the test will work properly.  You'll need to add a turbo frame to your view to tell your users which errors they are making on form submission. Does that make sense?

**Comment by ghiculescu** [comment]
> * If post is invalid, it displays the "error prohibited this post from being saved" message, and lists the validation error/s **responding as turbo-stream as well.**

Hmm, are you sure? This seems surprising as there's no code for this scenario - what turbo stream content does it render?

Could you share a simple replication app that we can clone to see this behavior?

**Comment by david-hello-world** [comment]
> Hmm, are you sure? This seems surprising as there's no code for this scenario - what turbo stream content does it render?
> 
> Could you share a simple replication app that we can clone to see this behavior?

Sorry, I wanted to say that the controller is responding to my turbo-stream request. In the browser it's rendering the response as a turbo-frame. So it's accepting the turbo-stream request. This is not happening on the integration test.

Here's the repo: https://github.com/david-hello-world/turbo-stream-sample

**Comment by ghiculescu** [comment]
If you add this to the controller, you can see the issue:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/509837/182651413-30b7f7cd-4ab0-4fb9-950b-6cf021f1a878.png">


```
http://www.example.com/posts.turbo_stream
E

Error:
CreatePostTest#test_cannot_create_an_invalid_post:
ActionController::UnknownFormat: ActionController::UnknownFormat
    app/controllers/posts_controller.rb:26:in `create'
    test/integration/create_post_test.rb:7:in `block in <class:CreatePostTest>'


rails test test/integration/create_post_test.rb:6

http://www.example.com/posts.turbo_stream
```

The correct way to write the test is like this: https://github.com/ghiculescu/turbo-stream-sample/commit/c9ac6b72281d949db3933049b36892ace94eb69b

**Comment by david-hello-world** [comment]
Thank you. Maybe this should be better documented.

**Comment by ghiculescu** [comment]
@david-hello-world would you like to make a PR to improve the docs?

**Comment by david-hello-world** [comment]
> @david-hello-world would you like to make a PR to improve the docs?

Sure thing. After my vacation I will find some time to look for a place to fit this information.

Thanks for looking into it.
