### ISSUE TITLE
Feature request/suggestion: add "exist?" aliases to "exists?" methods

### ISSUE THREAD

**Issue by marvinthepa** [rails/rails#45746]
Rationale:
Rubys [`File.exist?`](https://rubyapi.org/3.1/o/file#method-c-exist-3F) used to have an alias `File.exists?`, but it was deprecated and removed: https://bugs.ruby-lang.org/issues/17391

Rails methods that do a similar thing are (still) called `exists?`, and no alias exists (no pun intended).
This makes for a sub-optimal developer experience, as $developer always needs to remember where to include the s, and where to leave it off.

I would suggest adding aliases to all `exists?` methods, e.g.
https://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-exists-3F
https://api.rubyonrails.org/classes/ActiveRecord/Encryption/ExtendedDeterministicQueries/RelationQueries.html#method-i-exists-3F
https://api.rubyonrails.org/classes/ActionView/LookupContext/ViewPaths.html#method-i-exists-3F
https://api.rubyonrails.org/classes/ActionMailer/Preview.html#method-c-exists-3F

It is then possible to deprecate the `exists?` version (and eventually remove it) to become fully consistent to ruby, but for me personally it would be sufficient to have the alias around. I just would like to use the same variant everywhere.

Feel free to close this if you think it is okay as-is - just a suggestion.

**Comment by ghiculescu** [comment]
Hi @marvinthepa thanks for the feedback. We don't typically take feature requests on the bug tracker, we reserve it for issues. Please do either [start a discussion](https://discuss.rubyonrails.org/), or make a PR, either way would be a great way to discuss further. Thanks!

**Comment by dilraj-vidyard** [comment]
Hey, off topic, but I know there used be a `.exists?` method, (which I guess got deprecated) but I can't find it anywhere. 

We used to use it like: `if Model.find_by(...).exists?`.

I tried to search the code at v5.2.3, but I couldn't find any trace of `def exists?`. I want to see the PR that removed because I want to know the reason and what it was replaced by.
