### ISSUE TITLE
Uniqueness validation on association does not use the correct primary key

### ISSUE THREAD

**Issue by mikeletscher** [rails/rails#45775]
### Steps to reproduce

I'm not _entirely_ sure if this is considered a bug, or intended behavior that's not well-documented for `uniqueness` validations on associations.

I'm happy to help improve the documentation on this if that would be the most helpful way forward, or if this _is_ considered a bug, I can take a stab at a PR. 

It looks like the issue is that `build_relation` on the uniqueness validator calls [`bind_attribute` on `ActiveRecord::Relation`](https://github.com/rails/rails/blob/408d061a80a49878ad26b305616ed9ba88ee1411/activerecord/lib/active_record/relation.rb#L45), which properly takes into account the reflection's foreign_key, but not primary key if it's been overridden. 

Here's a test that reproduces the issue:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '~> 7.0.3.1'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter: 'sqlite3',
  database: ':memory:'
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :prescriptions, force: true do |t|
    t.string :rx_number
  end

  create_table :fills, force: true do |t|
    t.string :rx_number
  end
end

class Prescription < ActiveRecord::Base
  has_many :fills, foreign_key: :rx_number, primary_key: :rx_number
end

class Fill < ActiveRecord::Base
  belongs_to :prescription, foreign_key: :rx_number, primary_key: :rx_number

  validates :prescription, uniqueness: true
end

class BugTest < Minitest::Test
  def test_fill_unique_by_rx_number
    Fill.create!(rx_number: '1234')
    prescription = Prescription.create!(rx_number: '1234')
    new_fill = prescription.fills.new
    refute new_fill.save
  end
end
```

### Expected behavior
The uniqueness validation query would use the `rx_number` value of the `Prescription` to query for an existing `Fill` since that is what is set as the associations `primary_key`. 

### Actual behavior
The uniqueness validation query uses the `id` value of the `Prescription` to query for existing fills, disregarding the association's overridden `primary_key`.

This test passes if I patch bind_attribute to read the primary key from the reflection instead of directly from the reflection's klass:

```ruby
module ActiveRecord
  # = Active Record \Relation
  class Relation
    def bind_attribute(name, value) # :nodoc:
      if reflection = klass._reflect_on_association(name)
        name = reflection.foreign_key
        primary_key = reflection.association_primary_key || reflection.klass.primary_key
        value = value.read_attribute(primary_key) unless value.nil?
      end

      attr = table[name]
      bind = predicate_builder.build_bind_attribute(attr.name, value)
      yield attr, bind
    end
  end
end
```

We were able to work around this by adding the uniqueness validation to the `rx_number` attribute instead of the association. If this is the desired way to handle this, I can open a PR to add a note about this to the docs, as it took us by surprise that validation on the association wouldn't use the defined key to get the value to query.

### System configuration
**Rails version**: `7.0.3.1`

**Ruby version**: `3.1.2`

**Comment by fatkodima** [comment]
Please, do open a PR.

**Comment by tonyaraujop** [comment]
Hello @mikeletscher did you open a PR to work on this issue? I was wondering if I could try to solve it.

**Comment by mikeletscher** [comment]
@tonyaraujop Just put a PR up for this, sorry! https://github.com/rails/rails/pull/45790 Let me know if you have any thoughts on the approach.

**Comment by tonyaraujop** [comment]
Oh ok. I will search another issue to try to solve it. Thanks for reply and congrats on solving this.

**Comment by yahonda** [comment]
This test case successfully finishes by adding `self.primary_key = "rx_number"` to each model. 

```ruby
class Prescription < ActiveRecord::Base
  self.primary_key = "rx_number"
  has_many :fills, foreign_key: :rx_number, primary_key: :rx_number
end

class Fill < ActiveRecord::Base
  self.primary_key = "rx_number"

  belongs_to :prescription, foreign_key: :rx_number, primary_key: :rx_number

  validates :prescription, uniqueness: true
end
```

https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-primary-key

> [4.1.2.6 :primary_key](https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-primary-key)
By convention, Rails assumes that the id column is used to hold the primary key of its tables. The :primary_key option allows you to specify a different column.

**Comment by mikeletscher** [comment]
> This test case successfully finishes by adding `self.primary_key = "rx_number"` to each model. 

@yahonda This makes sense that it allows the test to pass, but if the Rails convention here is that you are unable to override the primary key for relations, I don't understand why primary_key is an option for relations. 

Outside of the validation, the associations work as expected with foreign_key and primary_key defined as options on the association. This has allowed us to make associations using natural keys in some situations and using the surrogate primary key of the associated object in others.
