### ISSUE TITLE
undefined method `queue_as' for ActionMailer::MailDeliveryJob:Class (NoMethodError)

### ISSUE THREAD

**Issue by sonaligvc** [rails/rails#45803]
ruby-2.7.2
gem 'rails', '~> 7.0.1'

When I am starting server, I am getting "undefined method `queue_as' for ActionMailer::MailDeliveryJob:Class (NoMethodError)"
I am upgrading application from rails 6.0.1. to rails 7.0.1

=> Booting Puma
=> Rails 7.0.3.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	58: from bin/rails:4:in `<main>'
	57: from bin/rails:4:in `require'
	56: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/commands.rb:18:in `<top (required)>'
	55: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/command.rb:48:in `invoke'
	54: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/command/base.rb:87:in `perform'
	53: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	52: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	51: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	50: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/commands/server/server_command.rb:134:in `perform'
	49: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/commands/server/server_command.rb:134:in `tap'
	48: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	47: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/commands/server/server_command.rb:36:in `start'
	46: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/commands/server/server_command.rb:76:in `log_to_stdout'
	45: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
	44: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
	43: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	42: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
	41: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
	40: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
	39: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
	38: from config.ru:3:in `block in <main>'
	37: from config.ru:3:in `require_relative'
	36: from /home/sonali/bank/tupay/config/environment.rb:8:in `<top (required)>'
	35: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/application.rb:372:in `initialize!'
	34: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/initializable.rb:60:in `run_initializers'
	33: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	32: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	31: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	30: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
	29: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
	28: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	27: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	26: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `call'
	25: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	24: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/initializable.rb:50:in `each'
	23: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	22: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	21: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	20: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	19: from /home/sonali/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	18: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	17: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/initializable.rb:32:in `run'
	16: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/initializable.rb:32:in `instance_exec'
	15: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
	14: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/engine.rb:619:in `each'
	13: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
	12: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/engine.rb:666:in `load_config_initializer'
	11: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/activesupport-7.0.3.1/lib/active_support/notifications.rb:208:in `instrument'
	10: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/engine.rb:667:in `block in load_config_initializer'
	 9: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/railties-7.0.3.1/lib/rails/engine.rb:667:in `load'
	 8: from /home/sonali/bank/tupay/config/initializers/monkey_patches.rb:2:in `<top (required)>'
	 7: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	 6: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	 5: from /home/sonali/bank/tupay/lib/core_ext/action_mailer/delivery_job.rb:3:in `<top (required)>'
	 4: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	 3: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	 2: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/actionmailer-7.0.3.1/lib/action_mailer/mail_delivery_job.rb:5:in `<top (required)>'
	 1: from /home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/actionmailer-7.0.3.1/lib/action_mailer/mail_delivery_job.rb:11:in `<module:ActionMailer>'
/home/sonali/.rvm/gems/ruby-2.7.2@tupay_2.7/gems/actionmailer-7.0.3.1/lib/action_mailer/mail_delivery_job.rb:12:in `<class:MailDeliveryJob>': **undefined method `queue_as' for ActionMailer::MailDeliveryJob:Class (NoMethodError)**

**Comment by sonaligvc** [comment]
Please help me

**Comment by fatkodima** [comment]
Probably the problem is somewhere here

> 8: from /home/sonali/bank/tupay/config/initializers/monkey_patches.rb

**Comment by sonaligvc** [comment]
Thanks @fatkodima for reply.

home/sonali/bank/tupay/config/initializers/monkey_patches.rb:2 has below code. We want to retry the Job after 10 min.
What is wrong with below code?

`class ActionMailer::MailDeliveryJob
  include ExceptionLogging

  rescue_from(StandardError) do |e|
    reschedule_wait = 10.minutes
    log_exception(e, "ActionMailer::MailDeliveryJob: Problem sending email. Will attempt again in #{reschedule_wait}. Cause: #{e.class} #{e.message}")
    retry_job wait: reschedule_wait
  end
end`

**Comment by fatkodima** [comment]
If you comment everything on this file, does the error persists? 
If yes, it would be helpful if you can debug and localize your problem and provide a reproduction script. Without it, it is hard to tell what is wrong.

**Comment by sonaligvc** [comment]
@fatkodima thanks
It resolved by your help. 
It was not working because of  `include ExceptionLogging` concern.
