### ISSUE TITLE
active_record:multi_db generator seems to be missing

### ISSUE THREAD

**Issue by JoaoPedroAssis** [rails/rails#45800]
Hi there, I'm trying to implement read/write databases, following the official docs [here](https://edgeguides.rubyonrails.org/active_record_multiple_databases.html)

In step 4, or `Activating automatic role switching`, the instructions tells me to run the following generator:

`$ bin/rails g active_record:multi_db`

To properly generate some files. When I actually run this command, I get the following output:

```bash
Could not find generator 'active_record:multi_db'. Maybe you meant "active_record:model"?
Run `bin/rails generate --help` for more options.
```
Am I missing something?
### Steps to reproduce

Trying to run the generator

### Expected behavior

Generator should run, and the docs should mention installation steps, if needed

### Actual behavior
 The command outputs the error mentioned above

### System configuration
**Rails version**:
6.1.6

**Ruby version**:
2.7.2

**Comment by ghiculescu** [comment]
The guide you're referencing is for Rails 7.1 (the edge version of Rails). The command has changed a bit in the past few versions. 

Rails 6.1 (no command for this): https://guides.rubyonrails.org/v6.1/active_record_multiple_databases.html
Rails 7: https://guides.rubyonrails.org/v7.0/active_record_multiple_databases.html#activating-automatic-role-switching
Rails `main` branch: https://edgeguides.rubyonrails.org/active_record_multiple_databases.html#activating-automatic-role-switching <- this is the link you are using

**Comment by ghiculescu** [comment]
No worries, I'll close this but can reopen if you find any other issues.
