### ISSUE TITLE
ActiveRecord "endless" range for >=, =<, < but not >

### ISSUE THREAD

**Issue by olegantonyan** [rails/rails#45821]
This is not a bug, but more like question/suggestion.

ActiveRecord support endless ranges in queries, for example:
```
User.where(created_at: ..2.years.ago).to_sql
#=> SELECT `users`.* FROM `users` WHERE `users`.`created_at` <= '2020-08-12 08:57:08'
```
`>=` possible too
```
User.where(created_at: 2.years.ago..).to_sql
#=> SELECT `users`.* FROM `users` WHERE `users`.`created_at` >= '2020-08-12 08:57:56'
```
Also works with non-inclusive ranges as `<`
```
User.where(created_at: ...2.years.ago).to_sql
#=> SELECT `users`.* FROM `users` WHERE `users`.`created_at` < '2020-08-12 08:59:06'
```
But not `>`
```
User.where(created_at: 2.years.ago...).to_sql
#=> SELECT `users`.* FROM `users` WHERE `users`.`created_at` >= '2020-08-12 09:00:15'
```

This makes sense from range's perspective b/c left value of a range is always included. But considering examples above I'd expect `whatever...` to mean `strictly greater than whatever` b/c it makes sense in this context and only this context.

This range syntax is great b/c otherwise you need to write condition as sql string (`where("created_at <= ?", whatever)`), and when you do this you also have to put table name (`where("users.created_at <= ?", whatever)`), otherwise you risk running into db errors when joining with another table with the same column.

**Rails version**: 7.0.3.1
**Ruby version**: 3.2.1

**Comment by fatkodima** [comment]
In ranges, `..` is for `end` part of it (whether to include/exclude it), so `2.years.ago..` and `2.years.ago...` are equivalent.
There is no way in ruby currently to define ranges excluding its beginning. There is a discussion in the ruby discussions forum - https://bugs.ruby-lang.org/issues/12133.
 
So, imo the currently generated syntax is correct.

**Comment by byroot** [comment]
Closing as non actionable.
