### ISSUE TITLE
JSON rendered as empty array of strings when bundling edge Rails

### ISSUE THREAD

**Issue by izaguirrejoe** [rails/rails#45866]
An error occurs when running `bundle update rails`. I'm bundling edge rails, going from commit d0bc58a8365034c06333e1aff5383892e3a7d803 to 893e5e25e5d83416c8f270dd1b1e32d9e5da76f5. Upon upgrading, attempting to render an array of ActiveRecord objects as JSON returns ["","","","","","","","","","","",""]. A new bug was introduced between those two commits in Rails. Reverting to older version of Rails fixes the bug. 

The full bundle logs:

❯ bundle update rails
Fetching https://github.com/rails/rails.git
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using rake 13.0.6
Using connection_pool 2.2.5
Using minitest 5.16.3 (was 5.15.0)
Using builder 3.2.4
Using erubi 1.11.0 (was 1.10.0)
Using racc 1.6.0
Using crass 1.0.6
Using digest 3.1.0
Using timeout 0.3.0
Using strscan 3.0.4 (was 3.0.1)
Using public_suffix 4.0.7
Using aws-eventstream 1.2.0
Using aws-partitions 1.593.0
Using jmespath 1.6.1
Using bcrypt 3.1.18
Using nio4r 2.5.8
Using marcel 1.0.2
Using bindex 0.8.1
Using msgpack 1.5.1
Using bundler 2.3.7
Using matrix 0.4.2
Using regexp_parser 2.4.0
Using childprocess 4.1.0
Using dead_end 3.1.2
Using io-console 0.5.11
Using ffi 1.15.5
Using mini_mime 1.1.2
Using memory_profiler 1.0.0
Using mini_histogram 0.3.1
Using ruby-statistics 3.0.0
Using rack 2.2.4 (was 2.2.3)
Using websocket-extensions 0.1.5
Using docile 1.4.0
Using honeybadger 4.12.1
Using http-accept 1.7.0
Using method_source 1.0.0
Using thor 1.2.1
Using mime-types-data 3.2022.0105
Using geocoder 1.8.0
Using newrelic_rpm 8.7.0
Using mini_magick 4.11.0
Using benchmark-ips 2.10.0
Using redis 4.6.0
Using rubyzip 2.3.2
Using simplecov-html 0.12.3
Using simplecov_json_formatter 0.1.4
Using stackprof 0.2.19
Using nokogiri 1.13.8 (arm64-darwin) (was 1.13.6)
Using mail 2.7.1
Using unf_ext 0.0.8.2
Using addressable 2.8.0
Using local_time 2.1.0
Using rexml 3.2.5
Using reline 0.3.1
Using get_process_mem 0.2.7
Using ruby-vips 2.1.4
Using aws-sigv4 1.5.0
Using bootsnap 1.11.1
Using rack-mini-profiler 3.0.0
Using websocket-driver 0.7.5
Using heapy 0.2.0
Using mime-types 3.4.1
Using loofah 2.18.0
Using zeitwerk 2.6.0 (was 2.5.4)
Using simplecov 0.21.2
Using irb 1.4.1
Using unf 0.1.4
Using image_processing 1.12.2
Using selenium-webdriver 4.1.0
Using pg 1.3.5
Using concurrent-ruby 1.1.10
Using net-protocol 0.1.3
Using rack-test 2.0.2 (was 1.1.0)
Using netrc 0.11.0
Using puma 5.6.4
Using xpath 3.2.0
Using aws-sdk-core 3.131.1
Using i18n 1.12.0 (was 1.10.0)
Using tzinfo 2.0.5 (was 2.0.4)
Using rails-html-sanitizer 1.4.3 (was 1.4.2)
Using net-pop 0.1.1
Using net-smtp 0.3.1
Using derailed_benchmarks 2.1.1
Using domain_name 0.5.20190701
Using webdrivers 5.0.0
Using net-imap 0.2.3
Using activesupport 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using debug 1.5.0
Using sprockets 4.0.3
Using capybara 3.37.1
Using faker 2.21.0
Using http-cookie 1.0.5
Using aws-sdk-kms 1.57.0
Using rest-client 2.1.0
Using aws-sdk-s3 1.114.0
Using mailgun-ruby 1.2.5
Using activemodel 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using rails-dom-testing 2.0.3
Using activerecord 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using actionview 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using globalid 1.0.0
Using actionpack 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using jbuilder 2.11.5
Using rails-controller-testing 1.0.5
Using sprockets-rails 3.4.2
Using railties 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using actioncable 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using activejob 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using activestorage 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using actionmailer 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using actionmailbox 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using active_storage_validations 0.9.8
Using actiontext 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using rails 7.1.0.alpha from https://github.com/rails/rails.git (at main@d1a9a99)
Using stimulus-rails 1.0.4
Using tailwindcss-rails 2.0.8 (arm64-darwin)
Using turbo-rails 1.1.1
Using web-console 4.2.0
Using importmap-rails 1.1.0
Bundle updated!

**Comment by fatkodima** [comment]
Can you create a reproducible test case using one of the following templates - https://github.com/rails/rails/tree/main/guides/bug_report_templates ?
