### ISSUE TITLE
ActiveRecord store deserialization fails with nested objects

### ISSUE THREAD

**Issue by tkalliom** [rails/rails#45868]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text "properties"
  end
end

class Post < ActiveRecord::Base
  store :properties
end

class BugTest < Minitest::Test
  def test_store_yaml_serialization
    post = Post.create! properties: { scalar_value: 2, nested_properties: { a: 3, b: 4 } }
    assert_equal 2, post.properties[:scalar_value]
  end
end

```

### Expected behavior
The serialization/deserialization round trip should work.

### Actual behavior
A `Psych::DisallowedClass` error is raised:
```
BugTest#test_store_yaml_serialization:
Psych::DisallowedClass: Tried to load unspecified class: ActiveSupport::HashWithIndifferentAccess
    /usr/lib/ruby/2.7.0/psych/class_loader.rb:97:in `find'
    /usr/lib/ruby/2.7.0/psych/class_loader.rb:28:in `load'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:411:in `resolve_class'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:283:in `visit_Psych_Nodes_Mapping'
    /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
    /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:340:in `block in revive_hash'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `each'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `each_slice'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:338:in `revive_hash'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
    /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
    /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:313:in `visit_Psych_Nodes_Document'
    /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:16:in `visit'
    /usr/lib/ruby/2.7.0/psych/visitors/visitor.rb:6:in `accept'
    /usr/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:32:in `accept'
    /usr/lib/ruby/2.7.0/psych.rb:360:in `safe_load'
    .../.bundle/ruby/2.7.0/rails-241893900740/activerecord/lib/active_record/coders/yaml_column.rb:61:in `yaml_load'
    .../.bundle/ruby/2.7.0/rails-241893900740/activerecord/lib/active_record/coders/yaml_column.rb:26:in `load'
    .../.bundle/ruby/2.7.0/rails-241893900740/activerecord/lib/active_record/store.rb:275:in `load'
    .../.bundle/ruby/2.7.0/rails-241893900740/activerecord/lib/active_record/type/serialized.rb:22:in `deserialize'
    .../.bundle/ruby/2.7.0/rails-241893900740/activemodel/lib/active_model/attribute.rb:168:in `type_cast'
    .../.bundle/ruby/2.7.0/rails-241893900740/activemodel/lib/active_model/attribute.rb:43:in `value'
    .../.bundle/ruby/2.7.0/rails-241893900740/activemodel/lib/active_model/attribute_set.rb:51:in `fetch_value'
    .../.bundle/ruby/2.7.0/rails-241893900740/activerecord/lib/active_record/attribute_methods/read.rb:38:in `_read_attribute'
    .../.bundle/ruby/2.7.0/rails-241893900740/activemodel/lib/active_model/attribute_methods.rb:277:in `properties'
    serialize-case.rb:35:in `test_store_yaml_serialization'
```

The issue #45585 was marked as fixed with PR #45591, but that fix is incomplete. It does not take into account nested objects: e.g. in my example above, the top-level `properties` is converted from `HashWithIndifferentAccess` to a regular hash, but even after that conversion, `properties[:nested_properties]` remains a `HashWithIndifferentAccess`. `Activerecord::Store::IndifferentCoder#as_regular_hash` should work in a recursive fashion.

### System configuration
**Rails version**: 2418939 (7.1.0.alpha)

**Ruby version**: 2.7.4p191

**Comment by byroot** [comment]
> Activerecord::Store::IndifferentCoder#as_regular_hash should work in a recursive fashion.

As explained on https://github.com/rails/rails/pull/45872 I disagree, Rails can't know if you are passing a HWIA on purpose and expect to get it back or wanted to pass a hash.

The top level hash is part of the store contract, so Rails can convert it at will, but Rails can't assume anything about what's inside. Your `nested_properties` is a black box for Rails.

Note that you can pass a custom coder to your store, so it's easy to implement the behavior you want in your app.

**Comment by tkalliom** [comment]
> As explained on #45872 I disagree, Rails can't know if you are passing a HWIA on purpose and expect to get it back or wanted to pass a hash.
> 
> The top level hash is part of the store contract, so Rails can convert it at will, but Rails can't assume anything about what's inside. Your `nested_properties` is a black box for Rails.

If you’ll look at the example code, I pass ActiveRecord a structure of _plain_ hashes, and ActiveRecord then produces a broken object from this input. It is only _ActiveRecord_ which ever refers to HWIA, not my code. So `nested_properties` is not quite treated as a black box; it is already converted in one direction. It seems a little clumsy that users of the ActiveRecord interface would have to know about this internal behavior and devise a workaround for it, undoing the conversion which AR did.

For what it’s worth, this used to work. My example code passed the test before the recent micro release.

**Comment by byroot** [comment]
Hum, let me check something.

**Comment by byroot** [comment]
Ah damn it, I forgot HashWithIndifferentAccess convert hash values to -_-. Sorry.

So ok, it need to be fixed. I'll re-open the PR, but the fix can be simplified I think.

**Comment by dominikklein** [comment]
@byroot Any thoughts that this leads to a "changed" state when you fetch one object which has for example a store column. Afterward, the `with_lock` complains about an already existing lock (`Locking a record with unpersisted changes is not supported. `).
