### ISSUE TITLE
ActiveStorage NoMethodError: undefined method `upload' for nil:NilClass

### ISSUE THREAD

**Issue by mridul911** [rails/rails#45889]
### Steps to reproduce

Simply follow the instruction to download the activestorage.

- I've ran the migration: rails active_storage:install

- I've edited my development environtment file: config.active_storage.service = :local

- setup xyz model by adding: has_one_attached :image

```ruby
# Here we have request parameters
Started PATCH "url/99" for ::1 at 2022-08-26 03:03:43 +0530
Processing by XYZController#update as HTML
  Parameters: {......., "image"=>#<ActionDispatch::Http::UploadedFile:0x0000000118d3b238 @tempfile=#<Tempfile:/var/folders/vt/yz_3y9j54d12prrw0k28n0nr0000gn/T/RackMultipart20220826-6048-1dxkoj9.png>, @original_filename="Screenshot 2022-08-16 at 11.07.24 PM.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"xyz[image]\"; filename=\"Screenshot 2022-08-16 at 11.07.24 PM.png\"\r\nContent-Type: image/png\r\n">, ......}
```
**Controller**
```
def update
    @xyz.update(xyz_params)
end
```

**Form**
 using .slim 
```
= form_for @xyz, :html => {:class => "ui form deal-form", 'data-parsley-validate' => true, multipart: true, :action => "upload"} do |f|
  = f.file_field :image, id: "cover-photo", class: "xyz-field", :value =>  "some value""
```
### Expected behavior

Should attach this object as expected.
### Actual behavior

When I submit this form, the aforementioned error is thrown. The same error occurs when trying to update an @event object.
### System configuration
**Rails version**:
5.2.8.1
**Ruby version**:
2.7.0

**Comment by fatkodima** [comment]
Rails `5.2.x` is not currently supported for bug fixes. 
Can you verify the problem still exists when using the latest changes from the `main` branch? If yes, please create a repro script using one of the templates from https://github.com/rails/rails/tree/main/guides/bug_report_templates or share with us a sample app that demonstrates the problem.
