### ISSUE TITLE
propshaft broken by change in rails/main

### ISSUE THREAD

**Issue by strobilomyces** [rails/rails#45888]
### Steps to reproduce
- Create app using Rails main (on or after 73d96c494759888eda7021c94774463c9b0f5556) and propshaft -- `rails new fuck -a propshaft --main`

### Expected behavior
A new Rails app with propshaft should be created without errors.

### Actual behavior
```
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  importmap:install
rails aborted!
NoMethodError: undefined method `assets=' for #<Fuck::Application>

      app.assets = Propshaft::Assembly.new(app.config.assets)
         ^^^^^^^^^
/home/user/fuck/config/environment.rb:5:in `<main>'
Tasks: TOP => app:template => environment
(See full trace by running task with --trace)

```

### System configuration
**Rails version**: main

**Ruby version**: 3.1.2p20

Rolling back to the previous commit, 2045cef03babe22ddbc9edab7df5e9829bb8748b, everything works as normal.

Not sure whether this is ultimately a Propshaft issue, but given that it was broken here, here we are.

Thanks :)

**Comment by p8** [comment]
The `assets` accessor was removed in https://github.com/rails/rails/pull/45878
Propshaft probably needs the fixed it similarly to the fix in `sprockets-rails`.
cc @etiennebarrie

**Comment by etiennebarrie** [comment]
Sorry about that. 😅 

I wonder why both aren't defining their own accessor, it's kind of weird to store your object on an object you don't own. Why use `Rails.application.assets` when you can use `Propshat.assets` for instance?
