### ISSUE TITLE
`<<` function of `ActiveRecord::Associations::CollectionProxy` unexpected behavior

### ISSUE THREAD

**Issue by youssef1337** [rails/rails#45919]
### Explanation
Hello, so I am using the `<<` [function](https://api.rubyonrails.org/v6.1.3/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-3C-3C) of `ActiveRecord::Associations::CollectionProxy` and before (in `rails 5`) it was returning `false` when it failed, when I upgraded to `rails 6` that doesn't happen anymore and I traced it to this [change](https://github.com/rails/rails/commit/5dc72378b783e924c5bf079ca660388ec4ac9224?diff=split#diff-ceff30ddab4e756e3a70ece45076eb17ff2f587a068dae657d2ad3a265a3f0d6L446) on `Jun 6, 2018` – my question is, how was I supposed to know that this change happened when upgarding? what did I miss? I have checked the upgrade guide and the release notes, didn't seem to find something related to that change. Thanks in advance.

### Steps to reproduce
Just check the reproduction script below for both `rails 5` and `rails 6`

### Expected behavior
This is the expected behavior in rails 5, expected the return value of `<<` to be `false` when it fails.
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "5.0.7"
  gem "sqlite3", "1.3.13"
  gem "byebug"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
  validates :post, uniqueness: true # for the sake of testing
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!
    val = post.comments << Comment.create!

    assert_equal false, val
  end
end
```
val returns `false` correctly as expected.
### Actual behavior
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "6.0.3"
  gem "sqlite3"
  gem "byebug"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
  validates :post, uniqueness: true # for the sake of testing
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!
    val = post.comments << Comment.create!

    assert_equal false, val
  end
end
```
`Expected: false`
`Actual: nil`

### System configuration
**Rails version**:
`5.0.7` for expected behavior
`6.0.3` for the changed behavior which I wasn't expecting
**Ruby version**:
`2.5.5` for expected behavior
`2.7.2` for the changed behavior which I wasn't expecting

**Comment by eileencodes** [comment]
Hey @youssef1337 in Rails we don't guarantee return values that are undocumented. In addition `nil` is still falsey so it didn't change behavior or cause a bug in production. The test should be updated to assert nil over asserting equality to false. 

Given that this was a change to an internal method (`_create_record`) we didn't include a changelog. IMO this isn't a bug so I'm going to close it. If there's other changes in behavior this caused, I'll reopen.

**Comment by youssef1337** [comment]
@eileencodes I completely agree with you and we weren't doing the check correctly anyways. I just wanted to understand if that should be documented or not. Thank you so much for clarifying 🙏
