### ISSUE TITLE
cannot send mail in rails

### ISSUE THREAD

**Issue by hminhduc** [rails/rails#45929]
im using gmail smtp to send mail in my rails app to now. recenly activejob peformed but mail not received in mail box.
have google changed policy?

Gmail SMTP server address: smtp.gmail.com.
Gmail SMTP name: Your full name.
Gmail SMTP username: Your full Gmail email address (e.g. xyz@gmail.com)
Gmail SMTP password: The password you use to log in to Gmail.
Gmail SMTP port (TLS): 587.

**Comment by byroot** [comment]
This isn't an issue with Rails.
