### ISSUE TITLE
ActiveStorage installation migration ignores `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.datetime_type`

### ISSUE THREAD

**Issue by compeak** [rails/rails#45922]
Installing ActiveStorage with `bin/rails active_storage:install` after setting `ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.datetime_type = :timestamptz` results in `timestamp without time zone` columns, because [activestorage/db/migrate/20170806125915_create_active_storage_tables.rb](https://github.com/rails/rails/blob/main/activestorage/db/migrate/20170806125915_create_active_storage_tables.rb) is a `5.2` migration.

I don't know whether this is a bug or intended behaviour.

### Steps to reproduce

Create new Rails app:

```bash
rails new testcase
```

Set `PostgreSQLAdapter.datetime_type`:

`config/initializers/postgres.rb`:
```ruby
require 'active_record/connection_adapters/postgresql_adapter'
ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.datetime_type = :timestamptz
```

Run ActiveStorage installation task:
```bash
bin/rails active_storage:install
```

Run migration:
```bash
bin/rails db:migrate
```

### Expected behavior

All `datetime` columns should be created as `timestamp(6) with time zone`.

Example:

```
                                         Table "public.active_storage_attachments"
   Column    |            Type             | Collation | Nullable |                        Default                         
-------------+-----------------------------+-----------+----------+--------------------------------------------------------
 id          | bigint                      |           | not null | nextval('active_storage_attachments_id_seq'::regclass)
 name        | character varying           |           | not null | 
 record_type | character varying           |           | not null | 
 record_id   | bigint                      |           | not null | 
 blob_id     | bigint                      |           | not null | 
 created_at  | timestamp(6) with time zone |           | not null | 
```

### Actual behavior

`datetime` columns are created as `timestamp(6) without time zone`.

Example:

```
                                          Table "public.active_storage_attachments"
   Column    |              Type              | Collation | Nullable |                        Default                         
-------------+--------------------------------+-----------+----------+--------------------------------------------------------
 id          | bigint                         |           | not null | nextval('active_storage_attachments_id_seq'::regclass)
 name        | character varying              |           | not null | 
 record_type | character varying              |           | not null | 
 record_id   | bigint                         |           | not null | 
 blob_id     | bigint                         |           | not null | 
 created_at  | timestamp(6) without time zone |           | not null | 
```

### Possible fix

After changing the migration version from `5.2` to `7.0` all `datetime` columns are created as `timestamp(6) with time zone`.

### System configuration

**Rails version**: 7.0.3.1
**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
**PostgreSQL version**: 14.5

**Comment by fatkodima** [comment]
> After changing the migration version from 5.2 to 7.0 all datetime columns are created as `timestamp(6) with time zone`.

I think this is a way to go. Can you open a PR with this change?

**Comment by compeak** [comment]
> I think this is a way to go. Can you open a PR with this change?

@fatkodima Yes: #45923 

There are probably other migrations with the same problem.
