### ISSUE TITLE
ActionText::Attachable#as_json override is breaking ActiveStorage::Blob#as_json when blob is not persisted

### ISSUE THREAD

**Issue by balbesina** [rails/rails#45949]
### Steps to reproduce
from rails console:
```ruby
ActiveStorage::Blob.build_after_unfurling(io: StringIO.new('asd'), filename: 'asd.txt').as_json
```

[Reproduction script](https://gist.github.com/balbesina/30fbdafbfee4b71b06209d9e950f4128)

### Expected behavior
ActiveStorage::Blob#as_json returns a Hash

### Actual behavior
ActiveStorage::Blob#as_json raises exception
```
/Users/dhh/.rvm/gems/ruby-3.1.2/gems/globalid-1.0.0/lib/global_id/uri/gid.rb:167:in `validate_model_id': 
Unable to create a Global ID for ActiveStorage::Blob without a model id. (URI::GID::MissingModelIdError)
```

### System configuration
**Rails version**: Rails 7.0.3.1
**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

**Comment by hahmed** [comment]
👋 @balbesina could you expand on your use case a little more? Want to try and understand the root of this issue...

How is this related to action text?

**Comment by alexandreruban** [comment]
@hahmed `ActiveStorage::Blob.build_after_unfurling(io: StringIO.new('asd'), filename: 'asd.txt').as_json` does not raise an error if you remove the `require "action_text/engine"` in `application.rb`.

```rb
# config/application.rb

# require "rails/all"

require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_view/railtie"
require "action_mailer/railtie"
require "active_job/railtie"
require "action_cable/engine"
require "action_mailbox/engine"
# require "action_text/engine"
require "rails/test_unit/railtie"
```

In the `ActionText` engine, we include the `ActionText::Attachable` module in `ActiveStorage::Blob` which created the issue. You can have a look at the linked PR for more information: https://github.com/rails/rails/pull/46126
