### ISSUE TITLE
JSON field not saving data with symbol : and it's saving with arrow =>

### ISSUE THREAD

**Issue by sajjadmurtaza** [rails/rails#45959]
### Steps to reproduce
I have JSON field in my database `t.json "theme"`. When I try to save the field hash with : , it's overridden before save
e.g.
`object.theme = { color: 'red' }` it always change to `{ color => 'red' }`

i also tried with jsonb and default value with empty hash {} but still having the same issue.

I want to save the JSON data hash with symbol keys `{ color: 'red' }`

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 2.7.1

**Comment by byroot** [comment]
Hi, your description is really unclear, so this isn't actionable for us.

Could you please provide a reproduction script using this template https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb ?
