### ISSUE TITLE
Cannot Eager Load has_many :through Relationships with custom scope

### ISSUE THREAD

**Issue by dcorrigan** [rails/rails#45984]
### Steps to reproduce

This seems like it's the same as #28324, but I'm still seeing the issue in Rails 7. 

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :images, force: true do |t|
    t.string :title
    t.integer :post_id
  end

  create_table :captions, force: true do |t|
    t.integer :image_id
  end
end

class Post < ActiveRecord::Base
  has_many :images
  has_many :captions, lambda { order('images.title DESC') }, through: :images
end

class Image < ActiveRecord::Base
  belongs_to :post
  has_one :caption
end

class Caption < ActiveRecord::Base
  belongs_to :image
end

class BugTest < Minitest::Test
  def test_preload_has_many_through_association_with_scope
    post = Post.create!
    image = Image.create!
    image.caption = Caption.create!
    post.images << image
    post.save!

    # Access through the model works
    assert_includes post.captions, Caption.first

    # Query with association preloaded does not.
    # When evaluated, it will apply the scope without the relevant JOIN table:
    # SELECT "captions".* FROM "captions" WHERE "captions"."image_id" = ? ORDER BY images.title DESC
    preloaded = Post.where(id: post.id).includes(:captions)

    assert_includes preloaded.first.captions, Caption.first
  end
end
```

### Expected behavior

The test passes and we're able to eager load has_many :through associations with custom scopes in this way.

I realize this can be fixed by adding a `references(:images)` to the query, but it seems reasonable to expect AR to infer that that the join is necessary here.

### Actual behavior

Test fails with an error: `ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: images.title`

### System configuration
**Rails version**: 7.0 

**Ruby version**: 3.1.2p20

**Comment by palkan** [comment]
Hey @dcorrigan,

The behavior is expected: Active Record has no idea that the `images` table is required (since you pass a plain string to `#order`). To indicate the intentions, you can use the `#references` method:

```ruby
has_many :captions, lambda { order('images.title DESC').references(:images) }, through: :images
```

That would turn the `#includes` into a `JOIN` query.

**Comment by dcorrigan** [comment]
HI @palkan , that's interesting. I had thought ActiveRecord would infer the `references` was necessary because of the `through`.

**Comment by palkan** [comment]
> I had thought ActiveRecord would infer the references was necessary because of the through.

It only can infer references from Hash-like values; probably, the following should do the trick:

```ruby
has_many :captions, lambda { merge(Image.order(title: :desc)) }, through: :images
```

Though explicit `#references` looks more straightforward.
