### ISSUE TITLE
Incorrect link present when using the help menu -h, under -c option.

### ISSUE THREAD

**Issue by creaturenex** [rails/rails#45988]
### Steps to reproduce

rails -h

under the option
 -c, [--css=CSS]
 
 clicking on link provided generate an 404 error due to wrong address
 

```ruby
# Need some help running the test script, based on the provided list most like have to use generic_main.rb

# The correction is simple, just removed the unnecessary bracket from the link
```

### Expected behavior
Link should open to
https://github.com/rails/cssbundling-rails

### Actual behavior
404 error due to wrong link

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.1.2

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/45989
