### ISSUE TITLE
CSRF getting different token

### ISSUE THREAD

**Issue by Saleh-Salem** [rails/rails#45998]
When validating the CSRF token getting an exception in API
 
> Can't verify CSRF token authenticity.
> ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):

the `session[:_csrf_token]` and  `request.x_csrf_token` is different and getting issue.
when I need to skip the csrf, I add `verify_authenticity_token`, In this case, I don't need to skip it.
I debug and found the issue in the method:

```
  def compare_with_global_token(token, session = nil) # :doc:
    ActiveSupport::SecurityUtils.fixed_length_secure_compare(token, global_csrf_token(session))
  end
```

what is `session[:_csrf_token]` and how can I implement it in API?
Is there any missing from my side?
### Steps to reproduce

1. Add `protect_from_forgery with: :exception` .
2. When logging in return token in response is generated by `form_authenticity_token`.
3. When Trying to request any POST, PUT or DELETE API get an exception.
> Can't verify CSRF token authenticity.
> ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):

### Expected behavior

Return Response without exception
### Actual behavior

getting an exception when requesting API by FE

> Can't verify CSRF token authenticity.
> ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):

Getting an success when requesting API by Postman

### System configuration
**Rails version**:
6.0.3.5
**Ruby version**:
2.7.2

**Comment by hahmed** [comment]
There is not a lot to go on from this issue but if you are using api mode and getting a CSRF issue, in the ApplicationController you may need to add the module `include ActionController::RequestForgeryProtection`, which is not included for api controllers.

```
class ApplicationController < ActionController::Api
  include ActionController::RequestForgeryProtection
...
```

**Comment by Saleh-Salem** [comment]
I add `include ActionController::RequestForgeryProtection` in controller.
I need to know why `session[:_csrf_token]` is always in every requested change so method `compare_with_global_token ` return **false** when using API from FE by **React** but when used from postman no issue and not changed and method `compare_with_global_token ` return **true**.

**Comment by rafaelfranca** [comment]
Is the React frontend sending the token in the request?

**Comment by Saleh-Salem** [comment]
@rafaelfranca yes react frontend sending the token in the request

add them in the header

`'X-CSRF-Token': value`

**Comment by Saleh-Salem** [comment]
@rafaelfranca ?

**Comment by hahmed** [comment]
@Saleh-Salem could you add a script or link a repo that reproduces this issue please?

**Comment by rwilliams3088** [comment]
Seeing this same behavior...

**Comment by hahmed** [comment]
@rwilliams3088 if you can provide/link to a sample app that reproduces this issue that will help a lot.

**Comment by rwilliams3088** [comment]
@hahmed Actually, after a bunch of debugging, I found an error on my end where a silent exception was causing the session to get reset (doh!). So it's working OK for me now :)
