### ISSUE TITLE
JSON encoded IPAddr/CIDR remove the prefix address

### ISSUE THREAD

**Issue by taketo1113** [rails/rails#46006]
### Steps to reproduce

JSON encoded IPAddr value of CIDR remove the prefix address.

```ruby
ipaddr = IPAddr.new('172.16.0.0/24')
=> #<IPAddr: IPv4:172.16.0.0/255.255.255.0>
ActiveSupport::JSON.encode(ipaddr)
=> "\"172.16.0.0\""
```

### Expected behavior

It returns a CIDR address that IP address with a prefix.
```ruby
ipaddr = IPAddr.new('172.16.0.0/24')
=> #<IPAddr: IPv4:172.16.0.0/255.255.255.0>
ActiveSupport::JSON.encode(ipaddr)
=> "\"172.16.0.0/24\""
```

### Actual behavior

It returns an IP address without prefix.

```ruby
ipaddr = IPAddr.new('172.16.0.0/24')
=> #<IPAddr: IPv4:172.16.0.0/255.255.255.0>
ActiveSupport::JSON.encode(ipaddr)
=> "\"172.16.0.0\""
```

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**Comment by skipkayhil** [comment]
```
irb(main):002:0> require 'ipaddr'
=> true
irb(main):003:0> i = IPAddr.new('172.16.0.0/24')
=> #<IPAddr: IPv4:172.16.0.0/255.255.255.0>
irb(main):005:0> require 'json'
=> true
irb(main):006:0> JSON.dump(i)
=> "\"172.16.0.0\""
```

Hey @taketo1113, thanks for opening an issue! I'm seeing the same behavior with standard library JSON, so I'm not sure this is a bug with Rails. Maybe an issue should be raised with the `json` gem?

**Comment by taketo1113** [comment]
@skipkayhil Thanks for reply.

I will create issue at `json` gem.

**Comment by skipkayhil** [comment]
Also seems related: https://github.com/ruby/ipaddr/pull/23
