### ISSUE TITLE
Documentation bug: Layouts and Rendering in Rails link to ActionController::Base#render

### ISSUE THREAD

**Issue by dumbledad** [rails/rails#46023]
### Steps to reproduce

Got to https://guides.rubyonrails.org/layouts_and_rendering.html#using-render and click the link titled `ActionController::Base#render`

### Expected behavior

You are taken to https://api.rubyonrails.org/v7.0.4/classes/ActionController/Rendering.html#method-i-render

### Actual behavior

You are taken to https://api.rubyonrails.org/v7.0.4/classes/AbstractController/Rendering.html#method-i-render

I.e. there is a typo in the href, it should be `ActionController` not `AbstractController`

**Comment by sreeram-venkitesh** [comment]
Can I take this up if someone hasn't already? First time contributor here.
