### ISSUE TITLE
#annotate does not add comments into BEGIN statement

### ISSUE THREAD

**Issue by levkk** [rails/rails#46032]
### Steps to reproduce
Pretty easy:

```ruby
class MyTable < ActiveRecord::Base
end

MyTable.annotate("hello = world").scoped do
  MyTable.create(hello: 'world')
end
```

### Expected behavior

I would like to see this in the database:

```sql
/* hello = world */ BEGIN
/* hello = world */ INSERT INTO "public"."my_table" ("hello") VALUES ('world') RETURNING id;
/* hello = world */ COMMIT
```

### Actual behavior

```sql
BEGIN
/* hello = world */ INSERT INTO "public"."my_table" ("hello") VALUES ('world') RETURNING id;
COMMIT
```

### System configuration
**Rails version**: latest commit in main.

**Ruby version**: 3.0.2

### More info

I'd like to see comments in the transaction control statements because clients can start transactions and do nothing. The comments are used to track who's doing what and when in `pg_stat_statements` and `pg_stat_activity`, and other monitoring tools, so idle transactions go unaccounted for and are hard to debug.

**Comment by yahonda** [comment]
Thanks for opening an issue.

I do not think it is feasible because the `annotate` belongs to `ActiveRecord::Relation`, while the transaction does not know which SQL statements will be executed and each transaction can run multiple SQL statements which come from different `ActiveRecord::Relation`s

**Comment by levkk** [comment]
I think the `#scoped` method can push the annotation into a shared state which the transaction manager can check before starting the implicit transaction triggered by `#create`.

The fact that multiple, differently annotated, relations can be inside a transaction is fine - the first relation that runs a query inside the transaction should get to comment on the `BEGIN` statement. This will create attribution for which relation (and line of code even) started the transaction.

Explicit transactions can do the same thing, e.g.:

```ruby
MyTable.annotate('hello = wold').transaction do
  MyTable.create(hello: 'world')
end
```

**Comment by yahonda** [comment]
Thanks for the comment. I'd say this is not an issue but a feature request.
So if you are interested in this feature, please feel free to open a pull request.

**Comment by yahonda** [comment]
I'm closing this issue for now because this is more like a feature request. As I mentioned earlier, please feel free to open a pull request.
