### ISSUE TITLE
Querying with mutable bound parameters can produce false-positive query cache hits

### ISSUE THREAD

**Issue by rnubel** [rails/rails#46044]
In production at Enova, in one of our apps, we were seeing an _incredibly_ rare issue where sometimes a query would improperly perform a cache load from the query cache and return the wrong value. After several days of debugging and load-testing and more debugging, I was eventually able to track down the issue to a place in our code where we doing, essentially:

```
search = { key: "value" }
r = Record.where(criteria: search).first
# ...
search.merge!(key2: "value2")
r2 = Record.where(criteria: search).first
```

As it turns out, the mutation of the search key produces a situation where -- _occasionally_, as demonstrated below -- the query cache returns the wrong value. The root cause is how Ruby hashes work internally: objects are hashed into a bucket in the internal structure based on a modulus of their numerical hash, and retrieved by searching the list of objects in the matching bucket for an equal object. When we mutate the search object, it is possible that the new numerical hash still falls into the **same** bucket, and because the key is a pointer to the object, the `==` check passes and the old object is returned.

In normal Ruby code, it would be obvious to an experienced Ruby developer that using a mutable hash key (and then mutating it) is a bad idea. Since the Rails query cache is under the covers, however, it is not obvious to a developer that the code above would be problematic. And because it happens so rarely, I suspect this is occurring in many Rails applications across the world without anyone noticing (other than the occasional head-scratching Sentry error, perhaps).

I do have a possible fix for this, which I'll add in a comment below.

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:", prepared_statements: true)
# ActiveRecord::Base.logger = Logger.new(STDOUT) # you can enable this to see the cache loads, but it's noisy

ActiveRecord::Schema.define do
  create_table :my_records, force: true do |t|
    t.json :value
    t.text :description
  end
end

class MyRecord < ActiveRecord::Base; end

class QueryCacheMutableSearchTest < Minitest::Test
  def test_bug
    iterations = 10000
    false_positives = 0

    MyRecord.connection.enable_query_cache!

    iterations.times do
      key, val = rand(100000), rand(100000)

      record = MyRecord.create(value: { key => val }, description: "The record we want to find")

      search = { key => val }
      the_record = MyRecord.where(value: search).first # this should populate the cache
      assert the_record.present?

      # cache now looks like this, essentially:
      #  { "SELECT * FROM my_records WHERE value = $1" =>
      #    { [search] => the_record }
      #  }

      new_val = rand(100000) until new_val != val

      search.merge!(key => new_val) # this mutates the key inside the query cache

      # normally: because the hash of the key has changed, this is a cache miss
      # however, if the new hash key's numerical hash falls into the same bucket
      # as the original, the hash lookup will a) find the first query's entry and
      # b) use it, because the objects are equal b/c the `search` hash was mutated
      # is equal to key_obj (since it's a reference)

      should_not_exist = MyRecord.where(value: search).first # this SHOULD not return a value
      false_positives += 1 if should_not_exist.present?

      record.destroy
      MyRecord.connection.clear_query_cache
    end

    assert_equal 0, false_positives
  end
end
```

### Expected behavior
The second query should never return a value, since the value it's supposed to look for does not exist in the database.

### Actual behavior
The second query **sometimes** performs a `CACHE MyRecord Load` and returns the original record, incorrectly:

```
Failure:
QueryCacheMutableSearchTest#test_bug [minimal_case.rb:69]:
Expected: 0
  Actual: 43
```

This happens because the mutated `search` hash inside the query cache ends up a) hashing into the same bucket as the original `search` hash did inside the query cache's hash, and b) still remains equivalent to the original search hash since the query cache stores a reference to it. Technically, the query cache is keying off of the list of binds which is a list of objects like `ActiveRecord::QueryAttribute`, but ultimately they end up with a reference to the `search` variable itself and thus the problem still manifests.

### System configuration
**Rails version**: edge (7.1.0.alpha), also occurs in 6.x and probably older versions as well
**Ruby version**: 2.7.6

**Comment by rnubel** [comment]
https://github.com/rnubel/rails/commit/9b48b35a1adbb8c36abee8472afe7ebd49d84475 is a patch which does fix the above test, but I'm not sure about side effects it may have or if there's a better solution. Essentially, it just updates the hash keys for the query cache to include the original numerical hash so that the equivalence check cannot return true if the hash has changed.

**Comment by tenderlove** [comment]
Nice find!!!  I'm not sure if this is the best fix.  It's perfectly legit for two objects to return the same value for `.hash`.  That's why we have the `eql?` method too.  That makes me doubt that storing the return value of `.hash` will 100% fix this issue.  Also it seems like the proposed patch would punish every query.

It seems like this is only a problem when a column can store a complex data type, like JSON or something.  Maybe we can make a more surgical fix, like dup and freeze the bind value, but only on JSON columns?  I'm trying something but not 100% sure it'll work.

**Comment by tenderlove** [comment]
I pushed #46048.  It fixed your test case, but I haven't tried all of the suite.  If CI is green (and you're OK with that patch) we should add your test case. :)

**Comment by rnubel** [comment]
@tenderlove I think your deep-dup-and-freeze idea is an elegant fix to this problem. I wouldn't be surprised if one day Ruby stopped allowing mutable objects to be used as hash keys, like Python does, because it's only a recipe for trouble. Your patch looks great! My only feedback is that `wrap_value` isn't really describing what's happening -- maybe `hashable_value` (not really right either as all values are hashable, but descriptive of the purpose) or `immutable_value`?

Also, since your fix is more robust, I was able to minify the test case down to just one iteration by using a custom HashWithFixedHash class that locks its `hash` as `1`. If you'd prefer to keep the thousands-of-iterations version for better fidelity, I can switch it back, but that one took over 5 minutes to run on my dev container and just felt a bit wasteful.

On main, the test fails; with your patch, it passes:

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/850438/190560400-4418d2d0-aa48-41b8-a8fe-fe2cec640889.png">

Here's a commit with just the test case that you can cherry-pick, if you'd like: https://github.com/rnubel/rails/commit/a93bd508d26b9b3852ef98aba36225420173b5b1. I'm new to developing on the Rails codebase so it might need some work.


<br />

P.S. While digging through `hash.c` and working on reproducing this bug, I thought of your [Yak Shaving Is Best Shaving](https://speakerdeck.com/tenderlove/yak-shaving-is-best-shaving) talk that I was fortunate enough to watch you give at Madison Ruby way back in 2013. That talk inspired me in my career to not be afraid to peel back layers and keep digging until everything is made clear... which is probably why I found the root cause here instead of just disabling the query cache in our app and moving on. Full circle! 😄

**Comment by tenderlove** [comment]
> I wouldn't be surprised if one day Ruby stopped allowing mutable objects to be used as hash keys, like Python does, because it's only a recipe for trouble.

Ya, I think that would be great.  Might be worth making a feature request to Ruby. This isn't the first time we've hit this particular footgun (see #43681)

> My only feedback is that wrap_value isn't really describing what's happening -- maybe hashable_value (not really right either as all values are hashable, but descriptive of the purpose) or immutable_value?

I agree.  I like `immutable_value` so I'll change it to that.

> Also, since your fix is more robust, I was able to minify the test case down to just one iteration by using a custom HashWithFixedHash class that locks its `hash` as `1`. If you'd prefer to keep the thousands-of-iterations version for better fidelity, I can switch it back, but that one took over 5 minutes to run on my dev container and just felt a bit wasteful.

No, I think your test case is good.  I'll cherry pick it over.  Thank you!

> P.S. While digging through `hash.c` and working on reproducing this bug, I thought of your [Yak Shaving Is Best Shaving](https://speakerdeck.com/tenderlove/yak-shaving-is-best-shaving) talk that I was fortunate enough to watch you give at Madison Ruby way back in 2013. That talk inspired me in my career to not be afraid to peel back layers and keep digging until everything is made clear... which is probably why I found the root cause here instead of just disabling the query cache in our app and moving on. Full circle! 😄

Nice!  Thank you so much, I really appreciate it.  I'm glad I was able to make an impact!! 🙇🏻‍♀️
