### ISSUE TITLE
Passing a string to sanitize_sql provides a false sense of security.

### ISSUE THREAD

**Issue by PhilCoggins** [rails/rails#46053]
`ActiveRecord::Base.sanitize_sql` performs a noop when passed a string, as is [clearly documented and found in source](https://github.com/rails/rails/blob/c5d8105e6290a3c7fb8b94cd75696f37198f105a/activerecord/lib/active_record/sanitization.rb#L8-L29). This would allow carefully crafted SQL input to be injected into various ActiveRecord query methods (see the executable test case below). The official [Securing Rails Applications](https://guides.rubyonrails.org/security.html) guide also suggests using `sanitize_sql` when not using model instances.

I believe that noop provides a false sense of security to users who might wrap a string with it, brush the dirt off their hands and assume they have safely "sanitized" their input, especially since a popular security vulnerability static analysis tools, Brakeman, [allows it](https://github.com/presidentbeef/brakeman/issues/1455). Note that even passing an array to `sanitize_sql_for_conditions` could pose issues depending on the string provided, but it is more obvious that an array expects binding parameters.

Given the above, I would propose a deprecation cycle for passing a string to `sanitize_sql_for_conditions` since it provides no added benefits, only a false sense of security.

### Steps to reproduce

1. Craft a clever SQL string
2. Pass to any ActiveRecord query method

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.boolean :published
  end
end

class Post < ActiveRecord::Base;end

class BugTest < Minitest::Test
  def setup
    Post.destroy_all
    post = Post.create!(published: false)
    @interpolation = "t' OR '1"
  end

  def test_sanitize_sql
    query = Post.where(
      ActiveRecord::Base.sanitize_sql("published = '#{@interpolation}'")
    )

    assert_equal 0, query.count
  end

  def test_sanitize_sql_2
    query = Post.where(
      "published = '#{ActiveRecord::Base.sanitize_sql(@interpolation)}'"
    )

    assert_equal 0, query.count
  end
end
```

### Expected behavior

It should make a best effort to sanitize potentially malicious input.

### Actual behavior

It does nothing

### System configuration
**Rails version**:
main
**Ruby version**:
3.0.3

**Comment by rafaelfranca** [comment]
I totally get the false sense of security argument here, but I don't think deprecating this will aliviate that. People can also pass an array like:

```
query = Post.where(
      "published = '#{ActiveRecord::Base.sanitize_sql([@interpolation, nil])}'"
    )
```

And think they are fine, but they aren't. Maybe we should change the name of this method to tell we sanitize binds only and remove support to passing strings.
