### ISSUE TITLE
bundle install doesn't work ,it says "Could not locate Gemfile" -> then when i run 'gem install bundler' it says "You don't    have write permissionhave write permission 

### ISSUE THREAD

**Issue by damnlucky** [rails/rails#46069]
### Steps to reproduce

```ruby
# Your reproduction script goes here
```

### System configuration
**Rails version**:

**Ruby version**:

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by damnlucky** [comment]
Where is CONTRIBUTING.md file, located

**Comment by flavorjones** [comment]
https://github.com/rails/rails/blob/main/CONTRIBUTING.md

**Comment by damnlucky** [comment]
i installed rbenv , but still can't use [ gem install bundler ] !

**Comment by damnlucky** [comment]
rbenv 1.1.2 version

**Comment by rafaelfranca** [comment]
You can ask for help in the support forum https://discuss.rubyonrails.org/c/rubyonrails-talk/7. You might even find similar topics to your problem there.

**Comment by damnlucky** [comment]
thanks
