### ISSUE TITLE
find_by_token_for and Rails/DynamicFindBy cop

### ISSUE THREAD

**Issue by strobilomyces** [rails/rails#46065]
https://github.com/rails/rails/pull/44189 introduced a token generator and a lookup function called find_by_token_for

rubocop-rails confuses it for a model lookup and is not pleased:

`Rails/DynamicFindBy: Use find_by instead of dynamic find_by_token_for`

Should this be renamed? Ignored by rubocop-rails?

Thanks!

**Comment by louim** [comment]
This is not a problem with rails. It should be addressed by rubocop-rails.
