### ISSUE TITLE
ActiveRecord 6.1: has_many, through, source raises InvalidArgument error

### ISSUE THREAD

**Issue by doconnor-clintel** [rails/rails#46073]
### Steps to reproduce
Given a class like:

```
class Foo
   has_many :subscribers, through: :subscriptions, source: :user
end
```
Rails 6.1.7 raises errors; where Rails 6.0 did not.

I believe this is distinct from #40830; though if it's no longer supported / a documentation bug, happy to close.

```ruby

```
(Pending executable test case)

This differs from the documentation:
https://apidock.com/rails/v6.1.3.1/ActiveRecord/Associations/ClassMethods/has_many

![image](https://user-images.githubusercontent.com/86343144/191154729-de74683d-4c0a-4661-963d-4b07757de5cc.png)
![image](https://user-images.githubusercontent.com/86343144/191154675-bfca2a98-c9b7-4fc6-8aad-7a421333f597.png)

And https://github.com/rails/rails/blob/5cfd58bbfb8425ab1931c618d98b649bab059ce6/activerecord/lib/active_record/reflection.rb#L885 suggests this is a valid options.

### Expected behavior

No errors

### Actual behavior

```
ArgumentError: Unknown key: :source. Valid keys are: :class_name, :anonymous_class, :primary_key, :foreign_key, :dependent, :validate, :inverse_of, :strict_loading, :autosave, :before_add, :after_add, :before_remove, :after_remove, :extend, :counter_cache, :join_table, :index_errors, :ensuring_owner_was

/path/to/application/.bundle/ruby/2.6.0/gems/activesupport-6.1.7/lib/active_support/core_ext/hash/keys.rb:52:in `block in assert_valid_keys'
/path/to/application/.bundle/ruby/2.6.0/gems/activesupport-6.1.7/lib/active_support/core_ext/hash/keys.rb:50:in `each_key'
/path/to/application/.bundle/ruby/2.6.0/gems/activesupport-6.1.7/lib/active_support/core_ext/hash/keys.rb:50:in `assert_valid_keys'
/path/to/application/.bundle/ruby/2.6.0/gems/activerecord-6.1.7/lib/active_record/associations/builder/association.rb:69:in `validate_options'
/path/to/application/.bundle/ruby/2.6.0/gems/activerecord-6.1.7/lib/active_record/associations/builder/association.rb:42:in `create_reflection'
/path/to/application/.bundle/ruby/2.6.0/gems/activerecord-6.1.7/lib/active_record/associations/builder/association.rb:32:in `build'
/path/to/application/.bundle/ruby/2.6.0/gems/activerecord-6.1.7/lib/active_record/associations.rb:1458:in `has_many'
/path/to/application/app/models/invoice.rb:108:in `<class:Invoice>'
/path/to/application/app/models/invoice.rb:3:in `<main>'
```

### System configuration
**Rails version**:
6.1.7

**Ruby version**:
2.6.0

**Comment by doconnor-clintel** [comment]
Closing for the moment, until reproducable test case written.

**Comment by mateusdeap** [comment]
I actually have this error, but precisely when I have a `has_many` call that _doesn't_ have a `through` option but _does_ have a `source` option. Like so:
```ruby
```

**Comment by zzak** [comment]
@mateusdeap The closest thing I might have found in the changelog was #43132, wdyt?

Although we won't be able to update the release notes, we _could_ add a note to the [upgrading guide](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) or at least post it here for others who run into it.

**Comment by mateusdeap** [comment]
I know it's been almost 2 months, but just to get back on this.

So, honestly, the changelog entry for that PR really doesn't make me think of this change in the validation logic. I could see some connection, but only after reading the PR and because you pointed me towards it.

But it might be that I'm just not that well versed in active record knowledge.

Which is maybe why I think it'd be good to have this documented somewhere, be it in the upgrading guide or even in the API docs, since, and I'm a case in point, if someone who isn't super familiar with relationships and how they work comes across this, just having the docs tell you that these options have certain restrictions would be very helpful.

If you think it makes sense to add this anywhere at all, just let me know. I can help.

**Comment by zzak** [comment]
@mateusdeap I believe the best place to document this behavior is in association builders, like 2c008d9f6311d92b3660193285230505e74a114f has modified them in this case. Second, would be the [associations guide](https://edgeguides.rubyonrails.org/association_basics.html), I think.

Thanks for looking into this and feel free to ping me if you run into trouble! I can try to help :joy:

**Comment by mateusdeap** [comment]
Sure thing. I'll try to get to it and ping you once I open a PR.

**Comment by Sweex99** [comment]
Need to use `source` options with `thought` (check has_many builder)

when we use has_many :relation, thought: :qwe

`has_many :match_context_staff_members, class_name: 'MatchContext::StaffMembers', dependent: :destroy`
`has_many :staff, through: :match_context_staff_members, source: :user`

<img width="1121" alt="Знімок екрана 2024-08-08 о 14 18 31" src="https://github.com/user-attachments/assets/c1fcadb8-7c57-4241-a97b-6355b4cfa7d5">
