### ISSUE TITLE
Requirement of installing turbo not mentioned in getting started guide

### ISSUE THREAD

**Issue by originalmk** [rails/rails#46079]
Getting started page teaches about deleting posts using `link_to` method with `turbo_method: :delete` data. 

It requires turbo to be installed by using:
`rails importmap:install` and then
`rails turbo:install`.

It is not installed by default and does not work by default, so guide should mention that you **must** execute these commands in order to make your app work. Currently guide says

> In the above code, we use the data option to set the data-turbo-method and data-turbo-confirm HTML attributes of the "Destroy" link. Both of these attributes hook into [Turbo](https://turbo.hotwired.dev/), which is included by default in fresh Rails applications.

what is misleading (it is as a gem, but you need to use extra commands). Honestly I spent more than an hour to find a solution. I am new to Ruby, I know some things may take me more time, but shouldn't it be clear for everyone?

Regards, originalmk

**Comment by sreeram-venkitesh** [comment]
I followed the guide and made a fresh app. I didn't face the issue with Turbo and was able to delete the post. Can you share the exact error message you had got?

**Comment by hahmed** [comment]
What's the command you used to create your rails app? I used `rails new testappname`  and turbo was added. Here is the latter part of the output from the install:

```
...
run  bundle binstubs bundler
       rails  importmap:install
Add Importmap include tags in application layout
      insert  app/views/layouts/application.html.erb
Create application.js module as entrypoint
      create  app/javascript/application.js
Use vendor/javascript for downloaded pins
      create  vendor/javascript
      create  vendor/javascript/.keep
Ensure JavaScript files are in the Sprocket manifest
      append  app/assets/config/manifest.js
Configure importmap paths in config/importmap.rb
      create  config/importmap.rb
Copying binstub
      create  bin/importmap
       rails  turbo:install stimulus:install
Import Turbo
      append  app/javascript/application.js
Pin Turbo
      append  config/importmap.rb
Run turbo:install:redis to switch on Redis and use it in development for turbo streams
Create controllers directory
      create  app/javascript/controllers
      create  app/javascript/controllers/index.js
      create  app/javascript/controllers/application.js
      create  app/javascript/controllers/hello_controller.js
Import Stimulus controllers
      append  app/javascript/application.js
Pin Stimulus
Appending: pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true"
      append  config/importmap.rb
Appending: pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true
      append  config/importmap.rb
Pin all controllers
Appending: pin_all_from "app/javascript/controllers", under: "controllers"
      append  config/importmap.rb
```

Will close the issue for now, but please do report back if you have more info.

**Comment by originalmk** [comment]
Now when I generate a new project it is working just fine. It must have been some error related to installation of gems that interrupted generation of JavaScript files (I don't know exactly). Thank you for your answers :slightly_smiling_face:
