### ISSUE TITLE
rails bundle install and Gemfile issue 

### ISSUE THREAD

**Issue by damnlucky** [rails/rails#46071]
### Steps to reproduce

```ruby
# Your reproduction script goes here gem install bundler to get all the gems and versions i need to build an application.
```

### Expected behavior
 it should have installed bundler

### Actual behavior
(Gem::FilePermissionError) and "You don't have write permission for 
the /var/lib/gem/2.7.0 directory
### System configuration
**Rails version**:7.0.4

**Ruby version**:2.4.4p191 (2021 -07-07 revision a21a3b7d23) [x86_64-linux-gnu]

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by damnlucky** [comment]
I've been following the exsamples  from ruby.org on installing

**Comment by rafaelfranca** [comment]
If `gem install bundler` is failing this is not a Rails issue, but instead in your system. `gem install` is a RubyGems command. And it requires that your use have write access to the folder the gems needs to be installed into. I recommend you to use a version manager like rbenv https://github.com/rbenv/rbenv#installation

**Comment by damnlucky** [comment]
i'll see if that works -yes it is a system issue ,i'll check out the link now ,and i'll let you know

**Comment by damnlucky** [comment]
Thanks, I'll check it out.
