### ISSUE TITLE
Rails multi-database: Couldn't create database. Please check your configuration.

### ISSUE THREAD

**Issue by sajjadmurtaza** [rails/rails#46075]
### Steps to reproduce
I am trying to use the rails multi-database feature. I set up the database.yml file as below but I am getting an error

> Created database 'test_development'
> no implicit conversion of nil into String
> Couldn't create '' database. Please check your configuration.
> rake aborted!
> TypeError: no implicit conversion of nil into String

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 2.7.1

`database.yml
`
````ruby
 default: &default
  adapter: postgresql
  encoding: unicode
  pool: 1
  timeout: 5000
  username: <%= ENV['POSTGRES_USERNAME'] %>
  host: <%= ENV['POSTGRES_URL'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  primary:
    <<: *default
    database: test_development
  primary_replica:
    <<: *default
    database: test_development
    replica: true
```

**Comment by fatkodima** [comment]
Can you verify it is working if you fix the spacing for the `default: &default` line?

**Comment by sajjadmurtaza** [comment]
@fatkodima it's fine

**Comment by fatkodima** [comment]
> it's fine

Did you mean "it is working now"? If yes, please, close the issue.
