### ISSUE TITLE
Running app:update doesn't respect rails new options

### ISSUE THREAD

**Issue by onlynone** [rails/rails#46091]
### Steps to reproduce

1. Generate a site with `rails new --skip-listen MyWebSite`
2. Within that site, run `rails app:update`

### Expected behavior

There should be no changes made.

### Actual behavior

The update process results in the following line in `config/environments/development.rb` becoming uncommented:

```
   # Use an evented file watcher to asynchronously detect changes in source code,
   # routes, locales, etc. This feature depends on the listen gem.
-  # config.file_watcher = ActiveSupport::EventedFileUpdateChecker
+  config.file_watcher = ActiveSupport::EventedFileUpdateChecker
```

This is because the update process ignores the various `--skip-*` options used to generate the site. It seems like most of them are figured out okay based on which gems are defined when `app:update` is run. But it seems like this isn't done correctly for `--skip-listen`. It used to be that more of the skip options used during creation were not respected during updating as noted by #32879. It seems like most of them have been figured out, but just by inferring the values. It would be nice if an explicit setting could be used during updates.

Could a change be made that the options used to create a new site are retained somewhere under `config` so that future runs of `app:update` will use the same settings? Alternatively (or in addition to that), could `rails app:update` be modified to take the same `--skip-*` options as `rails new` ? That way, any new skip options that weren't present in the previous version, but are present in the version being updated to, can be selected.

### System configuration
**Rails version**: 6.1.7

**Ruby version**: 2.6.5

**Comment by onlynone** [comment]
This is unrelated to the issue, but running `rails app:update` also changes the active job queue name:
```
   # Use a real queuing backend for Active Job (and separate queues per environment).
   # config.active_job.queue_adapter     = :resque
-  # config.active_job.queue_name_prefix = "MyWebSite_production"
+  # config.active_job.queue_name_prefix = "my_web_site_production"
```

**Comment by skipkayhil** [comment]
Hey @onlynone, thanks for opening an issue. I've opened a PR to fix `--skip-listen` for Rails 6.1, however I think its unlikely that it ever sees a release because 6.1 isn't accepting bug fixes. Rails 7 removed the Listen gem during app generation, so this particular problem won't pop up in future versions.

> This is unrelated to the issue, but running `rails app:update` also changes the active job queue name:

Looking into this as well

**Comment by onlynone** [comment]
Thanks @skipkayhil ! I wasn't just thinking about `--skip-listen` specifically, but there are a ton of `--skip-*` options to `rails new`:

```
--skip-namespace
--skip-collision-check
--skip-gemfile
--skip-git
--skip-keeps
--skip-action-mailer
--skip-action-mailbox
--skip-action-text
--skip-active-record
--skip-active-job
--skip-active-storage
--skip-puma
--skip-action-cable
--skip-sprockets
--skip-spring
--skip-listen
--skip-javascript
--skip-turbolinks
--skip-jbuilder
--skip-test
--skip-system-test
--skip-bootsnap
--skip-bundle
--skip-webpack-install
```

But `app:update` only supports some of them. And it only infers the ones it does support by checking which gems have been loaded:

```
          options[:skip_javascript] = !File.exist?(Rails.root.join("bin", "yarn"))
          options[:skip_active_record]  = !defined?(ActiveRecord::Railtie)
          options[:skip_active_storage] = !defined?(ActiveStorage::Engine) || !defined?(ActiveRecord::Railtie)
          options[:skip_action_mailer]  = !defined?(ActionMailer::Railtie)
          options[:skip_action_cable]   = !defined?(ActionCable::Engine)
          options[:skip_sprockets]      = !defined?(Sprockets::Railtie)
          options[:skip_puma]           = !defined?(Puma)
          options[:skip_bootsnap]       = !defined?(Bootsnap)
          options[:skip_spring]         = !defined?(Spring)
```

I was wondering if `rails app:update` could support the same `--skip-*` options as `rails new` and/or have `rails new` record the settings it was run with somewhere, so that when `rails app:update` runs later (even without options), it could use the same values. So that way, `rails app:update` wouldn't have have have the options added separately whenever they're added/removed from `rails new`, and it wouldn't have to infer the correct value.

**Comment by skipkayhil** [comment]
> But `app:update` only supports some of them. And it only infers the ones it does support by checking which gems have been loaded:

I believe all of the options should be correctly inferred in Rails 7. If figuring out the original options was more complicated it may be worth looking into alternatives but right now I don't see a ton of benefit for added complexity.

**Comment by onlynone** [comment]
I just thought it would be simpler, not more complex, for app:update to
have access to a definitive set of options to use that's identical to the
set that the site was created with rather than having to resort to
inference.

Part of the problem is that because previous versions of app:update didn't
infer correctly, components and configs could have been added to a site
that are difficult to know how to remove even after the bug has been fixed.

If version 6 results in a component being added to a site incorrectly, it
doesn't matter if it was fixed in version 7 because once the component is
added, later runs of app:update won't know if it was added by mistake or
not and they'll keep it there. If there was a definitive list of options, a
bug in version 6 can actually be fixed in 7 and the component will get
removed.

**Comment by skipkayhil** [comment]
I appreciate the desire to make improvements, and PRs are always welcome!

However, I'm going to close this as we reserve the issue tracker for bugs only and the original issues have been addressed.
