### ISSUE TITLE
`ActiveSupport::Reloader.wrap` reports raised exceptions twice

### ISSUE THREAD

**Issue by nvasilevski** [rails/rails#46100]
I believe this problem existed since the introduction of the error reporter however it was hidden until this PR - https://github.com/rails/rails/pull/46029/files#diff-fbb409271b9a1f69a3c2cdd5d7671c5ac6ce8dadf4c6b7b6e4cfb0e4b9ef127e

Reproduction: 

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class ErrorFromWrappedCode < StandardError; end

class BugTest < Minitest::Test
  def test_stuff
    reloader = Class.new(ActiveSupport::Reloader).tap do |r|
      r.executor = Class.new(ActiveSupport::Executor)
    end

    mock = Minitest::Mock.new
    mock.expect(:report, true) do |error, **_rest|
      assert error.is_a?(ErrorFromWrappedCode)
      assert_equal "hello", error.message
    end

    ActiveSupport.error_reporter.subscribe(mock)

    assert_raises(ErrorFromWrappedCode) { reloader.wrap { raise ErrorFromWrappedCode, "hello" } }
  end
end
```

This script fails with `"No more expects available for :report: [#<ErrorFromWrappedCode: hello>] {:handled=>false, :severity=>:error, :context=>{}, :source=>\"application.active_support\"}"` when the reloader tries to report the same exception for the second time.
This happens because the code wrapped by `Reloader` is wrapped two times, the outer block is handled by the `Reloader.executor.wrap` and inner block is wrapped by the `Reloader.wrap` itself which just calls parent `ExecutionWrapper.wrap` 

Previously this error wasn't reproducible because `ExecutionWrapper.error_reporter` was lazy-initialized which means new instance of `ErrorReporter` had zero subscribers

**Comment by casperisfine** [comment]
Ok, I get what's going on. `active?` is on a per class basis, so since `Reloader < Executor`, they both activate once, and both report the error once. I'll figure a fix, thanks for letting me know.
