### ISSUE TITLE
Vanilla 6.0.6 doesn't produce a working `webpack-dev-server`

### ISSUE THREAD

**Issue by davidkrider** [rails/rails#46114]
### Steps to reproduce
`rails _6.0.6_ new testapp`
Try to run `bin\webpack-dev-server`
Let yarn install `webpack-cli` and `webpack`
`yarn add @rails/webpacker` when it complains about that too.
Try to run `bin\webpack-dev-server`

### Actual behavior
```
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node should be one of these:
   false | object { __dirname?, __filename?, global? }
   -> Include polyfills or mocks for various node stuff.
   Details:
    * configuration.node has an unknown property 'dgram'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'fs'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'net'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'tls'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'child_process'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
```

### System configuration
**Rails version**: 6.06

**Ruby version**: 2.5.5

**Comment by skipkayhil** [comment]
Is there a reason you're creating a new app on such an old version of Rails? 6.0 (and Webpacker) aren't receiving bug fixes any more.

**Comment by davidkrider** [comment]
I was trying to upgrade to the latest bug fix release of an existing 6.0.x app, and it's breaking web packer. I've jacked around with gems and node modules for a couple of days before discovering that it's Rails, not me. I guess my options are to try to go back to the config I had before I started upgrading gems, and bundler, and my gem set, and python, and node, and yarn, and... or push to the latest 6.x release and hope nothing breaks my app.

**Comment by davidkrider** [comment]
There's something about package.json's referenced version of webpack-dev-server (4.x) that doesn't like the format of webpacker.yml. If I downgrade my package.json file to webpack-dev-server 3.x and web pack 4.x, running webpack-dev-server spews out a bunch of warnings about babel, but compiles and runs. It seems webpacker.yml needs to be updated to work properly with the "included" version of webpacker, but I have no idea how.

**Comment by byroot** [comment]
Given that 6.0 now longer receive fixes, I'll close.
