### ISSUE TITLE
Rails 6 new framework defaults does not call out the change of autoloader to zeitwerk

### ISSUE THREAD

**Issue by onlynone** [rails/rails#46118]
### Steps to reproduce
1. Have a module/class that can be found via the classic autoloader, but not zeitwerk
2. Upgrade that site from v5 to v6 with `rails app:update`
3. Work you way through all the settings in `config/initializers/new_framework_defaults_6_0.rb` to make sure your site is compatible with the new defaults
4. Use `config.load_defaults 6.0` in `config/application.rb` and remove `config/initializers/new_framework_defaults_6_0.rb`

### Expected behavior

The setting `config.autoloader = :zeitwerk` should have been called out in the new framework defaults file so that the site would fail to load things correctly when working through those settings.

### Actual behavior

The site runs fine ever after testing each new setting from the new framework defaults file, but fails to run when changing the `config.load_defaults` to `6.0`.

### System configuration
**Rails version**: any v5 to v6 upgrade

**Ruby version**: 2.6.10p210

**Comment by JohnAnon9771** [comment]
Could you try leaving `config.load_defaults 6.0` and running `./bin/rails zeitwerk:check`?

**Comment by hahmed** [comment]
> The setting config.autoloader = :zeitwerk should have been called out in the new framework defaults file so that the site would fail to load things correctly when working through those settings.

Rails 6 still uses classic mode and there is no requirement to run rails 6 with zeitwerk, it's a recommendation but you can still upgrade. In rails 7 there is only zeitwerk mode, see https://guides.rubyonrails.org/classic_to_zeitwerk_howto.html#applications-running-rails-7 for mode details.

**Comment by hahmed** [comment]
Sounds like your issue is the `config.autoloader = :zeitwerk` not enabled when updating? If that's the case, I have answered above and will close this issue, but please report back if I have misunderstood.

**Comment by onlynone** [comment]
> Could you try leaving `config.load_defaults 6.0` and running `./bin/rails zeitwerk:check`?

```
$ ./bin/rails zeitwerk:check
Hold on, I am eager loading the application.
rails aborted!
NameError: uninitialized constant XYZ
Did you mean?  Xyz
```

@JohnAnon9771 The problem isn't that my site has modules that can't be loaded via zeitwerk. That's definitely the case, and I know we'll have to address it some time before upgrading to rails-v7 or changing `config.autoloader = :zeitwerk`. The problem is that the user isn't given an opportunity to check their site with `config.autoloader = :zeitwerk` prior to using `config.load_defaults 6.0` like they are with the other defaults given in `config/initializers/new_framework_defaults_6_0.rb`.

I just think it would probably make sense to have `config/initializers/new_framework_defaults_6_0.rb` contain something like:

```
# Use zeitwerk as the autoloader instead of :classic
# Rails.application.config.autoloader = :zeitwerk
```

Shouldn't the new framework defaults file have exactly the difference between `config.load_defaults 6.0` and `config.load_defaults 5.2` ?

**Comment by hahmed** [comment]
Whoops @onlynone I misunderstood! 

Looks like that was missed in the new framework defaults for 6.0 and I go agree it helps make the upgrade a little easier. I have opened a PR fixing that and targeting 6.0 branch, however I doubt 6.0 is getting anything but security fixes so I'm not sure if that will get merged.

**Comment by onlynone** [comment]
I could try that when I get a chance. But I'm curious what that would show?
The problem isn't that zeitwerk finds classes differently than classic and
that our site has an instance of that. The issue is that `config.autoloader
= : zeitwerk` isn't in the new framework defaults file.
