### ISSUE TITLE
Application.js is not present in asset pipeline (rails 7.0.4)

### ISSUE THREAD

**Issue by ariandanim** [rails/rails#46124]
### Expected behavior
application.js should present

### Actual behavior
i try create new app with this command:
rails new myapp -c tailwind -j esbuild -d postgresql -T --main

when to running by rails server or rails s it's shows error like this :
Sprockets::Rails::Helper::AssetNotFound in StaticPages[#root](https://www.youtube.com/hashtag/root)
Showing C:/myapp/app/views/layouts/application.html.erb where line #10 raised:
The asset "application.js" is not present in the asset pipeline.

Extracted source (around line #10):

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

so i decided to change manually into my app view/layouts/application.html.erb in line of 
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

become this

<%= javascript_include_tag "/javascript/application.js", "data-turbo-track": "reload", defer: true %>

then works

### System configuration
**Rails version**:
7.0.4
**Ruby version**:
3.1.2
**OS type**:
Windows 11

**Comment by hahmed** [comment]
Hey @ariandanim, thanks for reporting this issue. 

It's really helpful when reporting issues related to creating a new rails, to post the output of the `rails new` command, in your case `rails new myapp -c tailwind -j esbuild -d postgresql -T --main`, it helps to identify the issue much quicker.

Without knowing the exact output from your end, I'm going to take a guess after running into the same issue 🙂

Maybe you have something like this in your output?

```
Add bin/dev to start foreman
      create  bin/dev
Install esbuild
         run  yarn add esbuild from "."
yarn add v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
└─ esbuild@0.15.9
info All dependencies
├─ esbuild-darwin-64@0.15.9
└─ esbuild@0.15.9
✨  Done in 4.87s.
Add build script
Add "scripts": { "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets" } to your package.json
```

That last line, is the issue which looks closely related to what you described, in short you need to add that script into package.json, that file will look something like this:

```
{
  "name": "app",
  "private": "true",
  "dependencies": {
    "@hotwired/stimulus": "^3.1.0",
    "@hotwired/turbo-rails": "^7.2.0",
    "esbuild": "^0.15.9"
  },
  "scripts": { 
    "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --minify",
    "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets"
  },
  "version": "v1.22.19"
}
```

Before starting your server with `bin/rails s` run the command `bin/dev` which will compile your js files in the right place. So you don't need to do this change `<%= javascript_include_tag "/javascript/application.js", "data-turbo-track": "reload", defer: true %>`.

This is all mentioned in the second paragraph here https://github.com/rails/jsbundling-rails#javascript-bundling-for-rails and here https://guides.rubyonrails.org/working_with_javascript_in_rails.html#adding-npm-packages-with-javascript-bundlers

I'm going to close this issue, but feel free to report back in case I missed the mark.

**Comment by hahmed** [comment]
Looking at this line https://github.com/rails/jsbundling-rails/blob/5e6758f077f0be59f94ea34678c2f8c452f2ba32/lib/install/esbuild/install.rb#L7 if the correct version of npm is installed, it will be added automatically. Maybe https://github.com/rails/rails/issues/44260 is a similar issue to this 🤔

**Comment by ariandanim** [comment]
> Hey @ariandanim, thanks for reporting this issue.
> 
> It's really helpful when reporting issues related to creating a new rails, to post the output of the `rails new` command, in your case `rails new myapp -c tailwind -j esbuild -d postgresql -T --main`, it helps to identify the issue much quicker.
> 
> Without knowing the exact output from your end, I'm going to take a guess after running into the same issue 🙂
> 
> Maybe you have something like this in your output?
> 
> ```
> Add bin/dev to start foreman
>       create  bin/dev
> Install esbuild
>          run  yarn add esbuild from "."
> yarn add v1.22.19
> info No lockfile found.
> [1/4] 🔍  Resolving packages...
> [2/4] 🚚  Fetching packages...
> [3/4] 🔗  Linking dependencies...
> [4/4] 🔨  Building fresh packages...
> success Saved lockfile.
> success Saved 2 new dependencies.
> info Direct dependencies
> └─ esbuild@0.15.9
> info All dependencies
> ├─ esbuild-darwin-64@0.15.9
> └─ esbuild@0.15.9
> ✨  Done in 4.87s.
> Add build script
> Add "scripts": { "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets" } to your package.json
> ```
> 
> That last line, is the issue which looks closely related to what you described, in short you need to add that script into package.json, that file will look something like this:
> 
> ```
> {
>   "name": "app",
>   "private": "true",
>   "dependencies": {
>     "@hotwired/stimulus": "^3.1.0",
>     "@hotwired/turbo-rails": "^7.2.0",
>     "esbuild": "^0.15.9"
>   },
>   "scripts": { 
>     "build:css": "tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --minify",
>     "build": "esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets"
>   },
>   "version": "v1.22.19"
> }
> ```
> 
> Before starting your server with `bin/rails s` run the command `bin/dev` which will compile your js files in the right place. So you don't need to do this change `<%= javascript_include_tag "/javascript/application.js", "data-turbo-track": "reload", defer: true %>`.
> 
> This is all mentioned in the second paragraph here https://github.com/rails/jsbundling-rails#javascript-bundling-for-rails and here https://guides.rubyonrails.org/working_with_javascript_in_rails.html#adding-npm-packages-with-javascript-bundlers
> 
> I'm going to close this issue, but feel free to report back in case I missed the mark.

run the command 'bin/dev' in CMD windows 11 its not working, also when i open from terminal windows also show what specific application should to open the 'dev', i am figure that the 'dev' file is bash, but how to compile in windows cmd?

**Comment by hahmed** [comment]
I'm afraid I'm not using a windows machine 😔

**Comment by hahmed** [comment]
@ariandanim can you use Git Bash, Cygwin or Windows Subsystem for Linux (WSL) to run the Bash script on a windows machine?

**Comment by drewhoffer** [comment]
If anyone comes across this, I updated to new OS and even though I had node setup with asdf, I did NOT have yarn installed. Solution was to install yarn (or npm and update the procfile.dev to use npm)
