### ISSUE TITLE
Rails 7.0.4 serilize hash has seemed to stop working

### ISSUE THREAD

**Issue by salex** [rails/rails#46128]
I'll start off simple.

The vulnerabily that came up in Rails 7.0.3 with YMAL load (psyc?) was handled with a new(?) ActiveRecord config `ActiveRecord.yaml_column_permitted_classes` which caused some initial problems and the fix was not clearly defined. I found something that worked. When I upgraded to 7.0.4 it stopped working, but found another fix after posting [7.0.4 model with serialized field hash_with_indifferent _access cannot be changed#46072](https://github.com/rails/rails/issues?q=is%3Aissue+is%3Aclosed)

Somewhere in the post about the YAML bug posts I saw 'Why not just use JSON'. The problem is that once you do something like `serial :preference, Hash`, you are stuck with it, unless you do some kind of converion process. You can't access the stored YAML unless you remove the `serialize` option, parse the YAML and store it off, then add a JSON serailize and replace it form  wherever you stashed it. Then add a `serialise, JSON` method.

Anyhow I started to play with it to come up with a conversion process. That's when I found that `serialize :preference, Hash` stopped working for me.

### Steps to reproduce

I created a new Rails app with default options
```sh
rails new trystuff
```
Created a model and migrated it
```sh
cd trystuff
bin/rails g model group name settings:text preferences:text
bin/rails db:migrate
```
Edited the Group model and added
```ruby
class Group < ApplicationRecord
  serialize :preferences, JSON
  serialize :setting, Hash
end
```
Added config to config/application.rb
```ruby
class Application < Rails::Application
  # Initialize configuration defaults for originally generated Rails version.
  config.load_defaults 7.0
  ...
  config.active_record.yaml_column_permitted_classes = [Symbol, Hash, Array, Date, Range, ActiveSupport::HashWithIndifferentAccess]
end
```

### Expected behavior and Actual behavior

I then entered the Rail console `bin/rails c` and create a hash and create a new Group
```ruby
h = {:one=>1, :two=>2, :three=>3}
g = Group.new(name:'newgroup')
```
set the prefererence attribute(JSON) and displayed it
```ruby
g.preferences = h
g.preferences
=> {"one"=>1, "two"=>2, "three"=>3}
```
It returned a hash using the JSON serailization

set the setting attribute(Hash) and displayed it
```ruby
g.setting = h
g.settings
=> "{:one=>1, :two=>2, :three=>3}"
```
It returned a string, not a hash!

I have no idea what I'm doing wrong. Current 7.0.4 apps seem to be working but I have not tried changing hash settings/preferences - and am somewhat afraid to try.

Setting/Preferences in my case are somewhat like rails config options, they rarely change, but I do have some dynamic serializations, mainly status info.

Maybe I'm not seeing the forest because of the trees, but I'm stumped.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1

**Comment by clouvet** [comment]
@salex, you have a typo in your example model. `serialize :setting, Hash` should be `serialize :settings, Hash`. 

I put together a script to test your case and can't reproduce the problem with the typo corrected:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  gem "sqlite3"
end

require "active_record"
require "active_record/railtie"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :groups, force: true do |t|
    t.string :name
    t.text :preferences
    t.text :settings
  end
end

class Group < ActiveRecord::Base
  serialize :preferences, JSON
  serialize :settings, Hash
end

class Application < Rails::Application
  # Initialize configuration defaults for originally generated Rails version.
  config.load_defaults 7.0
  config.active_record.yaml_column_permitted_classes = [Symbol, Hash, Array, Date, Range, ActiveSupport::HashWithIndifferentAccess]
end

class BugTest < Minitest::Test
  def test_serialized_json
    group = Group.create(name: "New group")
    test_hash = { one: 1, two: 2, three: 3 }
    group.preferences = test_hash

    assert_equal Hash, group.preferences.class
    assert group.preferences.respond_to?(:to_json)
  end

  def test_serialized_hash
    group = Group.create(name: "New group")
    test_hash = { one: 1, two: 2, three: 3 }
    group.settings = test_hash

    assert_equal Hash, group.settings.class
  end
end
```
With the typo uncorrected, I definitely saw the same issue. I copied-and-pasted your code, and it took me more than a few minutes to realize what was going on. 😉

**Comment by salex** [comment]
@clouvet I feel stupid!

A typo! I guess the forest hid the tree. I spent hours trying to figure out why it wasn't working. I actually, many times, did `g.setting = h`  and there was no error and no results. I guess you can serialize an attribute.

I thank you for your time and effort.
