### ISSUE TITLE
Broken defaults for redis_cache_store (reset redis connection)

### ISSUE THREAD

**Issue by mweitzel** [rails/rails#46149]
Default behavior of `RedisCacheStore` is to not establish a connection. This is unintuitive default behavior.

I think the following issues are directly related:
https://github.com/rails/rails/issues/37854
https://github.com/rails/rails/issues/43767
https://github.com/rails/rails/issues/43422
https://github.com/rails/rails/issues/43082
https://github.com/rails/rails/issues/42818

Downstream effects also include accidental `nil` sessions when both of the following are configured:
```ruby
config.cache_store = :redis_cache_store
config.session_store :cache_store, key: ENV['APP_SESSION_KEY']
```
This is due to what I'd think would be a reasonable expectation ([which rails core code holds](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/middleware/session/cache_store.rb#L55)) of expecting a cache.read to read from the cache instead of failing silently.

Odd, but noteworthy:
- ~redis-rb/redis-client has a [default reconnect attempt of 2](https://github.com/redis-rb/redis-client/blob/8c00763177f94c63a4c8f8e57410c2f147235758/lib/redis_client/sentinel_config.rb#L8)~ (edit: this is incorrect, thanks @byroot)
- redis/redis-rb/ overrides this the default with [a reconnect attempt of 1](https://github.com/redis/redis-rb/blob/3037564001edb36a839b41b577c83241c85121a8/lib/redis.rb#L66)
- rails' redis_cache_store overrides this with [a reconnect attempt of 0](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/cache/redis_cache_store.rb#L42)

Can we just change this default to 1 or 2? It will have no effect on the method signature or default error handling behavior.

### Steps to reproduce
```ruby
# application.rb
config.cache_store = :redis_cache_store
```

```ruby
Rails.cache.write('foo', 'bar')
# restart redis
Rails.cache.read('foo', 'bar')
Rails.cache.read('foo', 'bar')
```

### Expected behavior
```
"bar"
"bar"
```

### Actual behavior

```
nil
"bar"
```
<img width="360" alt="cache-miss" src="https://user-images.githubusercontent.com/318925/192861430-651df618-2d8b-479d-8030-ddba0f1f561e.png">

### System configuration
**Rails version**: Rails 7.0.4

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin19.6.0]

**Comment by skipkayhil** [comment]
Seems like this has been suggested before: https://github.com/rails/rails/pull/32041#discussion_r168941492

Would you be interested in opening a PR?

**Comment by mweitzel** [comment]
Sure, can do.
