### ISSUE TITLE
Rails 7.1 autoloader/zeitwerk NameError: uninitialized constant but the constant is being loaded

### ISSUE THREAD

**Issue by ron-shinall** [rails/rails#46147]
Using Rails 7.1 with 7.1 defaults, I am getting `NameError: uninitialized constant` in an initializer when reopening the class with `class_eval`, but if I comment out the offending code and run `rails zeitwerk:check`, I can see that the constant is set for autoload and is indeed subsequently loaded.

### Steps to reproduce

Generate a new Rails Edge app:
```bash
❯ rails new MyApp --main
```

Add the Delayed gem to the Gemfile:
```ruby
# Gemfile

...
gem "delayed"
...
```

Install the gem:
```bash
❯ bundle install
```

Enable autoloader logging in `application.rb`:
```ruby
# config/application.rb

...
module MyApp
  class Application < Rails::Application
    ...
    Rails.autoloaders.log!
    ...
  end
end
...
```

Execute zeitwerk check to confirm that constant `Delayed::Job` is autoloading:
```bash
❯ rails zeitwerk:check
...
Zeitwerk@rails.main: autoload set for Delayed::Job, to be loaded from /path_to/.rvm/gems/ruby-3.1.2/gems/delayed-0.4.0/app/models/delayed/job.rb
Zeitwerk@rails.main: constant Delayed::Job loaded from file /path_to/.rvm/gems/ruby-3.1.2/gems/delayed-0.4.0/app/models/delayed/job.rb
...
```

Create the delayed job initializer:
```ruby
# config/initializers/delayed_job.rb

Delayed::Job.class_eval  do
  def my_method
    return true
  end
end
```

Execute zeitwerk check:
```bash
❯ rails zeitwerk:check
```

### Expected behavior
```bash
Hold on, I am eager loading the application.
All is good!
```
### Actual behavior
```bash
NameError: uninitialized constant Delayed::Job

Delayed::Job.class_eval  do
       ^^^^^
```

### System configuration
**Rails version**: 7.1.0.alpha

**Ruby version**:  ruby-3.1.2 [ arm64 ]

@fxn I have a couple of other examples in my application, but this one is simple to recreate.

**Comment by fxn** [comment]
Exactly.

And in your use case you can see why. Initializers do not run on reload (as explained in the docs), so if you have

```ruby
Delayed::Job.class_eval  do
  def my_method
    return true
  end
end
```

and reload, the newly defined `Delayed::Job` won't have `my_method`. Conceptually, autoloading reloading constants in application initializers doesn't make sense because it yields inconsistent situations like that one. That is why Rails 7 finally removed this possibility, documenting ways to do the equivalent that do not have these issues.

This is expected behaviour, so I am going to close.

**Comment by ron-shinall** [comment]
Excellent. @fxn thank you for clarifying, and @nvasilevski you are correct in that using a `Rails.application.config.to_prepare` block solves the problems. Many thanks!
