### ISSUE TITLE
Rails 7: yarn install is no longer executed before assets:precompile

### ISSUE THREAD

**Issue by collimarco** [rails/rails#46148]
### Steps to reproduce
It seems that after upgrading from Rails 6.1 to Rails 7.0, the task `rake assets:precompile` no longer executes `yarn install`.

This for example breaks our deployment with Capistrano: https://github.com/capistrano/rails/issues/259

In the upgrade guides I can't find anything related to Yarn, but I expect that something has changed in Rails.

Is this an intended behavior? Is this a bug? Where can I find more information about this change? 

How can we make sure that `rake assets:precompile` also includes a `yarn install` step like in the past?

### Expected behavior
`rake assets:precompile` should always run `yarn install` before compiling the assets.

Otherwise Sprockets can't find the `node_modules` folder and the files in it (and it will raise `Sprockets::FileNotFound` for some dependencies).

### Actual behavior
`rake assets:precompile` runs without downloading the required files in the `node_modules` folder (i.e. `yarn install` is never executed).

### System configuration

**Rails version**: 7.0.4
**Ruby version**: 3.0.4

**Comment by collimarco** [comment]
I think that I have found the commit responsible for this issue:

https://github.com/rails/rails/pull/43641

Still looking for a way to solve the problem and run `yarn install` before `assets:precompile`

**Comment by collimarco** [comment]
I found a solution for Capistrano (see the linked issue).

If this is the new expected behavior of Rails, then feel free to close this issue.
Otherwise keep it open if you believe that it is a bug or a new behavior that should be documented.

**Comment by ghiculescu** [comment]
I think this is intended.

**Comment by sebyx07** [comment]
```ruby
# inside lib/tasks/yarn.rake
namespace :yarn do
  desc "Yarn Install"
  task install: :environment do
    sh "yarn install"
  end
end

Rake::Task["assets:precompile"].enhance [ "yarn:install" ]

```

**Comment by tomfast** [comment]
I had to add `capistrano-yarn` to my project again in order to get asset precompilation to work.
