### ISSUE TITLE
db:structure:load being called in rails 7.0.4

### ISSUE THREAD

**Issue by bernar40** [rails/rails#46162]
### Steps to reproduce
Hello! I tried upgrading from rails 6.1.6.1 to 7.0.4 and I'm facing the following issue:
Every time I try to run "any rails tasks it shows:

```
Don't know how to build task 'db:structure:load' (See the list of available tasks with `rails --tasks`)
```
I first noticed this after running bundle install/update and trying to run `rails zeitwerk:check` and then noticed this happened after every rails task, even trying to run `rails --tasks` 

### Expected behavior
To work normally 😄 

### Actual behavior
`rails zeitwerk:check`
```
rails aborted!
Don't know how to build task 'db:structure:load' (See the list of available tasks with `rails --tasks`)
Did you mean?  db:test:load
/Users/user.name/Documents/Repos/Project/Rakefile:6:in `<main>'
/Users/user.name/Documents/Repos/Project/bin/rails:9:in `<top (required)>'
<internal:/Users/user.name/.asdf/installs/ruby/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/user.name/.asdf/installs/ruby/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/user.name/Documents/Repos/Project/bin/spring:10:in `block in <top (required)>'
<internal:kernel>:90:in `tap'
/Users/user.name/Documents/Repos/Project/bin/spring:7:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)
```

OR

`rails db:migrate`    
```
Running via Spring preloader in process 97257
rake aborted!
Don't know how to build task 'db:structure:load' (See the list of available tasks with `rake --tasks`)
Did you mean?  db:test:load
/Users/user.name/Documents/Repos/Project/Rakefile:6:in `<main>'
<internal:/Users/user.name/.asdf/installs/ruby/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/user.name/.asdf/installs/ruby/3.0.1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
-e:1:in `<main>'
```
### System configuration
**Rails version**: 
new version: 7.0.4 
old version: 6.1.6.1

**Ruby version**: 3.0.1p64

**Comment by fatkodima** [comment]
These tasks were renamed - https://github.com/rails/rails/pull/39470. 
You (or some gem) probably extends or calls `db:structure:load` manually. You can run the task with `rails db:migrate -t` flag to see the backtrace.

**Comment by bernar40** [comment]
It was the gem **strong-migrations**, i updated it and solved!

Thank you so much @fatkodima!
