### ISSUE TITLE
When rendering multipart emails `format` is not passed to custom template handlers

### ISSUE THREAD

**Issue by sbulat** [rails/rails#46198]
### Steps to reproduce
When creating multiparts emails with [Maildown gem](https://github.com/zombocom/maildown) I couldn't get it to render both text and HTML correctly. Both were rendered as HTML, because that's the default set in the gem. Also, I tried old gem [Markerb](https://rubygems.org/gems/markerb/versions/1.1.0) locally and it was having the same problem (here, the text are the default one).

This is the code in those gems responsible for determining whether is should be HTML or text.
```ruby
...
def call(template, source = nil)
  source ||= template.source
  compiled_source = erb_handler.call(template, source)

  if template.format == :html
  ...
end
...
```
In both cases `template.format` here is `nil`. This led me to a conclusion that this may be an issue with Rails rather than a gem.

Mailer method
```ruby
def notify
  mail(to: 'john@example.com', subject: "Grocery List") do |format|
    format.html
    format.text
  end
end
```

notify.markerb / notify.md.erb file
```md
## Hello!

This is your grocery list:
1. [eggs](https://example.com/eggs)
2. [bread](https://example.com/bread)
3. [milk](https://example.com/milk)
```

### Sample app
A sample app with showing this behavior is available here: https://github.com/sbulat/mailer_rendering

### Expected behavior
`template.format` should be `:html` or `:text` so custom template handlers can operate on that value.

### Actual behavior
`template.format` is `nil` which breaks the mails behavior.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

Also breaks on:

**Rails version**: 6.0.5

**Ruby version**: 2.7.6

### Investigation
This is something that was working in Rails 5.2. I found that the [Resolver#query](https://github.com/rails/rails/blob/5-2-stable/actionview/lib/action_view/template/resolver.rb#L223) method was using `details` param to set `formats` value on a Template.
After changes in Rails 6.0 the default value from `details` is no longer used in [Resolver#query](https://github.com/rails/rails/blob/6-0-stable/actionview/lib/action_view/template/resolver.rb#L189) to set `format` variable on a Template.

**Comment by ubaidmyasintv** [comment]
For latest Asian/Korean Movies, drama, K-Series please visit [MyAsianTv] (https://myasiantv.at/)

**Comment by ghiculescu** [comment]
It would be good to write a test for this that doesn't depend on another gem, so we can isolate the issue to Rails.

This test seems to be similar to the one in your repo: https://github.com/rails/rails/blob/be0b5c65a175b6c92514375fc7044efb11cdbe90/actionmailer/test/base_test.rb#L595

Could you have a go at writing a failing test in Rails that demonstrates the issue?

**Comment by sbulat** [comment]
I tried once more to set up a `maildown` gem and when using `mail(...)` with implicit formats everything was working great. So, I'm assuming this is not a problem with Rails - closing the issue. Thanks a lot!
