### ISSUE TITLE
remove_index raises an error when using column: keyword argument that should have been avoided with if_exists: true

### ISSUE THREAD

**Issue by packrat386** [rails/rails#46196]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "= 7.0.4"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :payments, force: true do |t|
    t.decimal :amount, precision: 10, scale: 0, default: 0, null: false
    t.string :memo, null: false
    t.string :payer, null: false
    t.string :payee, null: false

    t.index [:memo, :payer], unique: true
  end
end

class Payment < ActiveRecord::Base
end

class RemoveIndexIfNotExistsFailure < ActiveRecord::Migration[7.0]
  def change
    # the index that actually exists is just [:memo, :payer]
    remove_index :payments, column: [:memo, :payer, :amount], unique: true, if_exists: true
  end
end

class RemoveIndexIfNotExistsSuccess < ActiveRecord::Migration[7.0]
  def change
    if index_exists?(:payments, [:memo, :payer, :amount], unique: true)
      remove_index :payments, column: [:memo, :payer, :amount], unique: true
    end
  end
end

class BugTest < Minitest::Test
  def test_migration_if_not_exist_failure
    assert !ActiveRecord::Migration.connection.index_exists?(:payments, [:memo, :payer, :amount], unique: true)
    RemoveIndexIfNotExistsFailure.migrate(:up)
  rescue StandardError => e
    flunk e.message
  end

  def test_migration_if_not_exist_success
    assert !ActiveRecord::Migration.connection.index_exists?(:payments, [:memo, :payer, :amount], unique: true)
    RemoveIndexIfNotExistsSuccess.migrate(:up)
  rescue StandardError => e
    flunk e.message
  end
end
```

### Expected behavior
Both of these migrations should do nothing.

### Actual behavior
The first migration raises an error because it cannot find an index that matches the constraints.

```
# Running:

==  RemoveIndexIfNotExistsSuccess: migrating ==================================
-- index_exists?(:payments, [:memo, :payer, :amount], {:unique=>true})
   -> 0.0001s
==  RemoveIndexIfNotExistsSuccess: migrated (0.0001s) =========================

.==  RemoveIndexIfNotExistsFailure: migrating ==================================
-- remove_index(:payments, {:column=>[:memo, :payer, :amount], :unique=>true, :if_exists=>true})
F

Finished in 0.001106s, 1808.3182 runs/s, 2712.4773 assertions/s.

  1) Failure:
BugTest#test_migration_if_not_exist_failure [active_record_migrations_gem.rb:57]:
No indexes found on payments with the options provided.

2 runs, 3 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**: activerecord version 7.0.4

**Ruby version**: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]`

### Investigation

`remove_index` first checks if `index_exists?` if the `if_exists: true` option is passed, then calls `index_name_for_remove`, which is where the error message we get bubbles up from.

https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L894-L900

`index_exists?` looks only at the positional `column_name` argument, which can be either a single name (string/symbol) or an array of column names. It also looks at the keyword arguments `unique: <boolean>` and `name: <string>`. It returns true if something matches all of those criteria.

https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L99-L111

`index_name_for_remove` however looks at either the positional `column_name` _or_ the keyword `column: <name or array of names>`. If it finds no matching columns it raises an error.

https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L1436-L1466

`remove_index` supports the `columns:` keyword arg per [the api docs](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-remove_index) but because `index_exists?` ignores it, you can get weird errors when combined with `if_exists: true`. In this case `index_exists?` succeeds because the only criterion that it is looking at is `unique: true` (we didn't supply `column_name` or the `name: ` keyword argument) and there _is_ a unique index on this table (on a different set of columns). If you manually check `index_exists?` with the positional argument you can avoid the error.

In the event that this is in fact a bug, I'd be happy to attempt to contribute a fix. It seems like `index_exists?` just needs to also support the `column:` keyword argument, probably to be implemented the same way `index_name_for_remove` does here: https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L1445

**Comment by eileencodes** [comment]
Hey @packrat386 thanks for the bug report. I've opened a PR to fix this here https://github.com/rails/rails/pull/46203.
