### ISSUE TITLE
Add support for default value in new column created by migrate generator from cli

### ISSUE THREAD

**Issue by wellington1993** [rails/rails#46207]
History: I need add a new column named "uuid" in all my rails project tables, the new column needs a "UUID" mysql function as default value.
I can't create with easy way a migration to add new columns with default value from command line.
I neither create easily too, a migration adding some new column in all tables.

https://guides.rubyonrails.org/active_record_migrations.html#column-modifiers

### Steps to reproduce

- Needs to add a column with a default value from cli
- rails generate migration doesn't support default value column modifier.

### Expected behavior
- rails generate migration AddUuidColumnToPatient uuid:string:**{default:'UUID()'}**
- Way to easily add default value in migrations generation from cli
 
### Actual behavior
I need to iterate tables, generate migrations without default value in columns, and after manually replace text in migrations, adding default values syntax.

### System configuration
**Rails version**:
Rails 6.1.6.1

**Ruby version**:
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by ubaidmyasintv** [comment]
For latest Asian/Korean Movies, drama, K-Series please visit [MyAsianTv] (https://myasiantv.at/)

**Comment by khall** [comment]
This sounds like a feature request. Per [CONTRIBUTING.md](https://github.com/rails/rails/blob/main/CONTRIBUTING.md#do-you-intend-to-add-a-new-feature-or-change-an-existing-one) can you suggest your change over at https://discuss.rubyonrails.org/c/rubyonrails-core/5 and get some feedback on your proposal?

A simpler way to do what you are suggesting might be to do something like
```
%i(long list of table names).each do |table_name|
  add_column table_name, :uuid, :string, default: 'UUID()'
end
```
