### ISSUE TITLE
render_and_return

### ISSUE THREAD

**Issue by hasandiwan** [rails/rails#46209]
The attached patch adds a render_and_return method to rails.

**Comment by hasandiwan** [comment]
diff --git a/actionpack/lib/abstract_controller/rendering.rb b/actionpack/lib/abstract_controller/rendering.rb
index 673e06ba17..80b44f0b8f 100644
--- a/actionpack/lib/abstract_controller/rendering.rb
+++ b/actionpack/lib/abstract_controller/rendering.rb
@@ -56,6 +56,12 @@ def rendered_format
       Mime[:text]
     end
 
+    # renders and returns, convenience method to address concerns in https://blog.arkency.com/render-is-not-your-final-word-in-your-rails-controllers-action/
+    def render_and_return(*args, &block)
+      render(*args, &block)
+      return
+    end
+
     DEFAULT_PROTECTED_INSTANCE_VARIABLES = %i(@_action_name @_response_body @_formats @_prefixes)
 
     # This method should return a hash with assigns.

**Comment by yahonda** [comment]
Hi, Would you open a pull request instead of adding a patch as a comment?

**Comment by hahmed** [comment]
Closing this for now, but please do open a PR!
