### ISSUE TITLE
Rails.application.config.active_record.automatic_scope_inversing not applied from config/initializers/new_framework_defaults_7_0.rb file

### ISSUE THREAD

**Issue by alexadia** [rails/rails#46208]
### Steps to reproduce

Uncomment `Rails.application.config.active_record.automatic_scope_inversing = true` in config/initializers/new_framework_defaults_7_0.rb with application loading 6.1 defaults (`config.load_defaults 6.1` in config/application). 

Note that inverse_of is not automatically detected for associations with a scope. For example, for the setup in this [gist](https://gist.github.com/alexadia/72baf7628796bab36d9d86a4b0aab502), the call `comment.post` ([code line](https://gist.github.com/alexadia/72baf7628796bab36d9d86a4b0aab502#file-inverse_of_test-rb-L46)) triggers a db query for post.

The new inverse_of feature does work once I put in the config in our config/application.rb file, so I'm not blocked by this issue. I just want to call out that it needs to get enabled in the config/application.rb file so that other folks know and don't think that they've enabled it from the framework defaults file. Enabling it from the config/application.rb is a suitable workaround. 

```ruby
# Your reproduction script goes here
```

### Expected behavior

Enabling the configuration from the framework defaults file should turn on automatically inferring the inverse_of for associations with a scope. So a database load for the post record should not be triggered as shown here. 

```
D, [2022-10-07T16:18:07.323128 #6388] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2022-10-07T16:18:07.323692 #6388] DEBUG -- :   Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = ? AND "comments"."is_deleted" = ? ORDER BY "comments"."id" ASC LIMIT ?  [["post_id", 1], ["is_deleted", 0], ["LIMIT", 1]]
```

### Actual behavior

A database load for post record is triggered.

```
D, [2022-10-07T16:12:07.774869 #4519] DEBUG -- :   Comment Load (0.1ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = ? AND "comments"."is_deleted" = ? ORDER BY "comments"."id" ASC LIMIT ?  [["post_id", 1], ["is_deleted", 0], ["LIMIT", 1]]
THIS POST LOAD IS TRIGGERED:
D, [2022-10-07T16:12:07.777274 #4519] DEBUG -- :   Post Load (0.1ms)  SELECT "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
```

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 2.7.2

**Comment by alexadia** [comment]
The same happened for Rails.application.config.action_mailer.smtp_timeout configuration.

**Comment by skipkayhil** [comment]
Hey @alexadia, thanks for opening an issue! I tried reproducing what you are seeing but was unable to:

```sh
rails _6.1.7_ new --minimal testing
# update Gemfile to rails 7.0.4
bundle update
bin/rails app:update
bin/rails runner 'puts ActiveRecord::Base.automatic_scope_inversing' # => false
# uncomment Rails.application.config.active_record.automatic_scope_inversing = true in new_framework_defaults
bin/rails runner 'puts ActiveRecord::Base.automatic_scope_inversing' # => true
```

Could you create a sample repo that demonstrates the issue?

**Comment by alexadia** [comment]
@skipkayhil : This looks like an issue with my rails setup and not with rails since you are not able to replicate but I get false for ActiveRecord::Base.automatic_scope_inversing when I uncomment it from the framework defaults file.
