### ISSUE TITLE
Timezone problem when casting time field

### ISSUE THREAD

**Issue by bvicenzo** [rails/rails#46220]
### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_time_zone
    Time.zone = 'Brasilia'
    assert Time.zone.local(2007, 2, 10, 15, 30, 45).to_s.end_with?('-0300')
    assert Time.zone.parse('2007-02-10 15:30:45').to_s.end_with?('-0300')
    assert Time.zone.at(1171139445).to_s.end_with?('-0300')
    assert Time.zone.now.to_s.end_with?('-0300')
    assert Time.utc(2007, 2, 10, 20, 30, 45).in_time_zone.to_s.end_with?('-0300')
  end
end
```

### Expected behavior

Looking for [TimeWithZone](https://api.rubyonrails.org/classes/ActiveSupport/TimeWithZone.html) doc, I understood that this should return time in the defined timezone.

```rb
Time.zone = 'Eastern Time (US & Canada)'        # => 'Eastern Time (US & Canada)'
Time.zone.local(2007, 2, 10, 15, 30, 45)        # => Sat, 10 Feb 2007 15:30:45.000000000 EST -05:00
Time.zone.parse('2007-02-10 15:30:45')          # => Sat, 10 Feb 2007 15:30:45.000000000 EST -05:00
Time.zone.at(1171139445)                        # => Sat, 10 Feb 2007 15:30:45.000000000 EST -05:00
Time.zone.now                                   # => Sun, 18 May 2008 13:07:55.754107581 EST -05:00
Time.utc(2007, 2, 10, 20, 30, 45).in_time_zone  # => Sat, 10 Feb 2007 15:30:45.000000000 EST -05:00
```

### Actual behavior

However, what I see is Time.zone.now returning a different timezone from others. As docs.

![image](https://user-images.githubusercontent.com/173159/194929516-5c5b5a16-cf0e-4b34-959a-a76002475fad.png)

![image](https://user-images.githubusercontent.com/173159/194929730-776030ee-89e9-4541-8d34-e876f7535198.png)

Shouldn't they all return the same timezone?

I realized that when I'm using a time field and it started to show my time aways 1 hour ahead.
And I saw that is uses Time.local to cast: https://github.com/rails/rails/blob/3258979977e8aa80c9592ad105ae8b76ea77064c/activemodel/lib/active_model/type/helpers/time_value.rb#L61

It seems that all methods, except `Time.zone.now` are using brazilian summer time instead of use brazilian time.

### System configuration
**Rails version**: 7.0.3.1

**Ruby version**: 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux-musl]

**Comment by hbontempo-br** [comment]
Hi @bvicenzo!

I know this is strange and confusing, but the behavior is correct.
The normal timezone for Brazil is -03:00, but in  `2007-02-10` Brazil was in the -02:00 timezone because in this date Brazil was using a DST (summer time).

<img width="516" alt="image" src="https://user-images.githubusercontent.com/15916283/194986353-cbac0fa3-3604-4cd9-b6b6-0c26705ee4a3.png">

Source: https://pt.wikipedia.org/wiki/Lista_de_per%C3%ADodos_em_que_vigorou_o_horário_de_verão_no_Brasil

**Comment by bvicenzo** [comment]
Hi @hbontempo-br!

Thanks for the answer.

That's true!!!

Then I realized what would be happening to me...

As I said before, I'm using a time field, and before, and it casts the value to a date time field:

```rb
ActiveModel::Type::Time.new.cast('10:00') # => 2000-01-01 10:00:00 -0200
```

And this could confuse me. I'll keep investigating my problem.

Thanks again.
