### ISSUE TITLE
Can't specify a UUID primary key when using `rails generate model`  (solved: undocumented flag)

### ISSUE THREAD

**Issue by jasonfb** [rails/rails#46229]
### Steps to reproduce

• Make a new rails app `rails new RailsGeneratorUUIDTest --database=postgresql`
• Enable UUID extension on postgres `rails generate migration EnableUUIDOnPostgres`
your migration file should look like:
```
class EnableUuidOnPostgres < ActiveRecord::Migration[7.1]
  def up
    enable_extension 'pgcrypto' unless extension_enabled?('pgcrypto')
  end

  def down
    disable_extension 'pgcrypto' unless !extension_enabled?('pgcrypto')
  end
end
```

Then make a new migration, trying to specify the primary key (`id`) as a uuid:

`rails generate model Thing id:uuid`

this generates a migration with incorrect syntax:
```
class CreateThings < ActiveRecord::Migration[7.1]
  def change
    create_table :things do |t|
      t.uuid :id

      t.timestamps
    end
  end
end
```

### Expected behavior

The migration created should have a `create_table` line like so to correctly create a UUID as a primary key
```
create_table :things, id: :uuid do |t|
```

### Actual behavior

if this migration is run, it crashes with 
```
== 20221012142550 CreateThings: migrating =====================================
-- create_table(:things)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

you can't redefine the primary key column 'id' on 'things'. To define a custom primary key, pass { id: false } to create_table.
/Users/jason/Work/RailsGeneratorUUIDTest/db/migrate/20221012142550_create_things.rb:4:in `block in change'
/Users/jason/Work/RailsGeneratorUUIDTest/db/migrate/20221012142550_create_things.rb:3:in `change'

Caused by:
ArgumentError: you can't redefine the primary key column 'id' on 'things'. To define a custom primary key, pass { id: false } to create_table.
/Users/jason/Work/RailsGeneratorUUIDTest/db/migrate/20221012142550_create_things.rb:4:in `block in change'
/Users/jason/Work/RailsGeneratorUUIDTest/db/migrate/20221012142550_create_things.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### System configuration
**Rails version**: 7.1.0.alpha

**Ruby version**: 3.1.2

### SOLVED
This already works using the undocumented `--primary-key-type=uuid` as a flag passed to the generator

**Comment by jasonfb** [comment]
Documentation PRed against the guides section: https://github.com/rails/rails/pull/46228

**Comment by p8** [comment]
Closing as the PR got merged.
