### ISSUE TITLE
Action Text Migration is broken in branch main

### ISSUE THREAD

**Issue by cantin** [rails/rails#46232]
### Steps to reproduce
```bash
 rails new test_app
 # modify the Gemfile, set Rails to `gem "rails", github: 'rails/rails'`
 rails action_text:install
 rails db:mirgate
```

### Expected behavior
No errors

### Actual behavior
```
Unknown key: :size. Valid keys are: :limit, :precision, :scale, :default, :null, :collation, :comment, :primary_key, :if_exists, :if_not_exists
.../test_app/db/migrate/20221013084208_create_action_text_tables.action_text.rb:9:in `block in change'
.../test_app/db/migrate/20221013084208_create_action_text_tables.action_text.rb:7:in `change'
```

### System configuration
**Rails version**:
 Edge Rails
**Ruby version**:
3.1.2

**Comment by andrewn617** [comment]
I believe it's related to this: https://github.com/rails/rails/commit/e6da3ebd6c65af23d134a9e01145f26600912008

I can open a PR to fix the generated migration.

**Comment by rubyrider** [comment]
At rails version 7.0.4 and with ruby 3.1.2 I couldn't reproduce the issue. Size attribute is working perfectly fine. 

But with Main branch, the issue is valid.

**Comment by rubyrider** [comment]
The issue is also valid with postgres.
