### ISSUE TITLE
`Concurrent::ReentrantReadWriteLock` might not be fiber safe.

### ISSUE THREAD

**Issue by ioquatix** [rails/rails#46257]
Just adding an issue here to track <https://github.com/socketry/falcon/issues/166> and <https://github.com/ruby-concurrency/concurrent-ruby/issues/962>

We have reports of this code failing when running on falcon.

https://github.com/rails/rails/blob/caf94136045f79b1d9103ebf17fc74b7ff7f8727/actionview/lib/action_view/cache_expiry.rb#L7

It might make sense for us to implement this behaviour in CRuby itself rather than Rails depending on a gem for providing locking mechanisms. A multi-reader, single writer mutual exclusion primitive seems pretty useful.

**Comment by byroot** [comment]
Closing since this isn't actionable by Rails.

**Comment by ioquatix** [comment]
Well, it can be actionable by Rails, if you can use the thread primitives provided by Ruby instead of the Concurrent gem.

**Comment by ioquatix** [comment]
Okay, after some digging, I think the issue is a `concurrent-ruby` bug. https://github.com/ruby-concurrency/concurrent-ruby/issues/962#issuecomment-1281676806

**Comment by ioquatix** [comment]
Okay, this was fixed and released in concurrent-ruby v1.2.0.
