### ISSUE TITLE
Should Explain Queries Always Skip the ActiveRecord QueryCache?

### ISSUE THREAD

**Issue by chadrschroeder** [rails/rails#46255]
### Steps to reproduce
I know this probably isn't a common workflow, but while testing out the ActiveRecord QueryCache in the Rails console, I noticed that calls to `.explain` only work once.  After that it returns an empty string.

```
ActiveRecord::Base.connection.enable_query_cache!
 => true

# First call to explain - Good
User.where(id: 1).explain
  User Load (5.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1  [["id", 1]]
 =>
EXPLAIN for: SELECT "users".* FROM "users" WHERE "users"."id" = $1 [["id", 1]]
                                QUERY PLAN
--------------------------------------------------------------------------
 Index Scan using users_pkey on users  (cost=0.14..8.16 rows=1 width=608)
   Index Cond: (id = '1'::bigint)
(2 rows)

# Second call to explain - Bad
User.where(id: 1).explain
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1  [["id", 1]]
 =>
```

### Expected behavior
Calling `.explain` performs an uncached query and always returns a result.

### Actual behavior
Calling `.explain` performs a cached query and returns an empty string on the second attempt.

### System configuration
**Rails version**: 7.0.4
**Ruby version**: 3.0.3

**Comment by eileencodes** [comment]
IMO the current behavior is correct because it is actually not running a second query so there's nothing to `explain`.  There wouldn't be an index scan or query plan to display in the explain output. I could maybe see a message that explain wasn't run due to the query cache but given that this is a debugging feature I don't think it's worth adding more complexity there.

**Comment by chadrschroeder** [comment]
That makes sense.  I'll close this.  Thanks for the response!
