### ISSUE TITLE
Contributing to the Rails core should mention RAILS_STRICT_WARNINGS

### ISSUE THREAD

**Issue by yahonda** [rails/rails#46263]
Contributing to the Rails core should mention RAILS_STRICT_WARNINGS added via #46189

### Steps to reproduce
Read https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#warnings

### Expected behavior
This guide should mention that
- Rails CI will fail if the pull request raises warnings
- By setting `RAILS_STRICT_WARNINGS`, contributors can reproduce Rails CI behavior

https://github.com/rails/rails/pull/46189#event-7559954952

### Actual behavior
It does not mention that Rails CI fails if warnings are raised.

> [5.8 Warnings](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#warnings)
The test suite runs with warnings enabled. Ideally, Ruby on Rails should issue no warnings, but there may be a few, as well as some from third-party libraries. Please ignore (or fix!) them, if any, and submit patches that do not issue new warnings.

### System configuration
**Rails version**: main branch

**Ruby version**: Any version that is supported by Rails main

**Comment by Mysta3** [comment]
Hello! First time contributor here and would love to work on resolving this issue.  @yahonda

**Comment by aviralsomani** [comment]
Just to clarify the scope of this issue begins and ends with updating documents correct?

**Comment by khall** [comment]
> Just to clarify the scope of this issue begins and ends with updating documents correct?

That sounds correct

**Comment by aviralsomani** [comment]
https://github.com/rails/rails/pull/46272 - not sure what the protocol is but I raised a PR here, could any seasoned contributors let me know what the best way would be to request reviews?

**Comment by eileencodes** [comment]
There is no way to request reviews, and we'd prefer you don't @ members of the core team. We look at PRs as we're able to (maintainers and contributors are volunteers). If a PR falls off the radar you can mention it in the #contributors channel on [Discord](https://discord.gg/xSb5z6GK) .
