### ISSUE TITLE
Early loading of ActiveRecord silently breaks configuration in initializers

### ISSUE THREAD

**Issue by dfritsch** [rails/rails#46277]
### Steps to reproduce

Steps for reproducing the issue:
1. Created a test-app with `rails new ./test-app`
2. Updated application.rb to have:

```
config.load_defaults 6.1
# Anything to cause ActiveRecord to be loaded at this point and trigger `ActiveSupport.run_load_hooks(:active_record, Base)`
p ActiveRecord::Base.name
```

3. Added an initializer to configure ActiveRecord

```
# New file at config/initializers/active_record.rb
Rails.application.config.active_record.verify_foreign_keys_for_fixtures = true
```

4. Open a console (`rails c`) and see that while the initializer did set the config this wasn't applied to ActiveRecord's singleton class:

```
Loading development environment (Rails 7.0.4)
[1] pry(main)> Rails.application.config.active_record.verify_foreign_keys_for_fixtures
=> true
[2] pry(main)> ActiveRecord.verify_foreign_keys_for_fixtures
=> false
```

This example is a bit fictitious but it covers a real case I ran in to using the "new_framework_defaults" initializer provided by rails as part of upgrading to Rails 7.0. New defaults were uncommented in the initializer and were silently not actually being applied.

I couldn't see a good way to write an executable test case for this, since the problem appears to lie in railtie.rb with `active_record.set_configs` [here](https://github.com/rails/rails/blob/0eb42cae30e3b74d88771c971d2d2957084cf88a/activerecord/lib/active_record/railtie.rb#L224-L270).

The assumption in the code appears to be that the `after_initialize` block will run before the `ActiveSupport.on_load(:active_record)`. When that is not the case, the `configs = configs.except` updates the local `configs` variable to now be a purely local object over something tied back to `app.config.active_record`, meaning that even when the after_initialize block runs it doesn't actually see any config changes from the initializers and fails to apply them.

Finally, while it is obviously better if our application isn't loading ActiveRecord before initializers, I think we can improve this code and make it a bit more defensive by either defining `configs` independently in each block or not overwriting `configs` with the `except` call.

### Expected behavior

ActiveRecord should be properly configured by initializers 

### Actual behavior

Configuration appears to be there when inspecting `Rails.application.config` but are not actually used by Active Record.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**Comment by skipkayhil** [comment]
Closing as the attached PR was closed as well
