### ISSUE TITLE
Content-Length header not provided by ActiveStorage

### ISSUE THREAD

**Issue by danielyazbek** [rails/rails#46288]
### Steps to reproduce
Create a simple model with an ActiveStorage attachment:
```ruby
class User < ActiveRecord::Base
  has_one_attached :photo do |p|
    p.variant :medium, resize_to_limit: [350, 350]
    p.variant :thumb, resize_to_limit: [100, 100]
    p.variant :large, resize_to_limit: [1000, 1000]
  end
end
```

Get a URL for a photo:
```ruby
url = rails_storage_proxy_url(User.last.photo, host: 'example.com')
```

GET the photo and inspect the response headers
```sh
$ curl -v the_url > /dev/null
< HTTP/2 200
< date: Thu, 20 Oct 2022 08:55:49 GMT
< last-modified: Sat, 01 Jan 2011 00:00:00 GMT
< accept-ranges: bytes
< content-type: image/jpeg
< content-disposition: inline; filename="avatar.jpg"; filename*=UTF-8''avatar.jpg
< cache-control: max-age=3155695200,public
```

The same occurs for a URL generated for a variant:
```ruby
url = rails_storage_proxy_url(User.last.photo.variant(:medium), host: 'example.com')
```

### Expected behavior
We should get a **Content-Length** header, because this is required for some CDNs to perform caching.

### Actual behavior
We don't get a **Content-Length** header.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**Comment by hahmed** [comment]
@danielyazbek could you provider an example script that repro this issue? Or link a repo please?

You should get that header looking at this line...

https://github.com/rails/rails/blob/b96ddea5f0b4ff8ed6e9dfe4df62f7571b147b11/activestorage/app/controllers/active_storage/blobs/proxy_controller.rb#L19

**Comment by codergeek121** [comment]
Even though the `Content-Length` header is set in the ActiveStorage controller, the header is removed here: https://github.com/rails/rails/blob/7fdcbe747f7ab5ef664b894f73c8e0ada04c5c50/actionpack/lib/action_controller/metal/live.rb#L154
Afaik when streaming content the Content-Length header should be omitted.
I'll open up a PR that removes setting the header in this controller action.

**Comment by danielyazbek** [comment]
Hi @codergeek121,

I'm not sure I'm following you.
According to the HTTP RFC, a `Content-Length` header field should be provided when the content size of the response is known, unless the `Transfer-Encoding` header is present. See https://httpwg.org/specs/rfc9110.html#rfc.section.8.6

Since ActiveStorage knows the size of the file (and any variants) being served - as stored in blob's ActiveRecord - the `Content-Length` should be provided irrespective of the technique of serving the bytes.

**Comment by danielyazbek** [comment]
Hi @hahmed, Yes you are right, although ActiveStorage sets the `Content-Length` header in the proxy controller, I can confirm that actionpack is removing this header as @codergeek121 suggested.

**Comment by codergeek121** [comment]
Hi @danielyazbek

I tested it on a local development app. I was confused, because when I inspected the response headers I got a `Transfer-Encoding: chunked` header (because the file is chunked/streamed). Removing the `Content-Length` header would then be correct, like you wrote.

But I noticed your HTTP response uses HTTP2, my guess is the `Transfer-Encoding: chunked` header set by Rails is dropped on your HTTP2 proxy, making it look like it should send a Content-Length header? HTTP2 must not send a chunked encoding header, which I could imagine means that HTTP2 proxies just drop the header.

I think it's not necessary to set the "content-length" header in the active storage controller, since it will always be removed anyways because of `metal/live.rb`, I'll open up a PR now.

What do you think, would that be a possible explanation for your observed behavior?

**Comment by danielyazbek** [comment]
Hi @codergeek121

Thanks for investigating this further and helping me understand.

As you suggested, I performed a HTTP GET directly to Puma without any proxies in between.
As expected, I do not receive the `Content-Length` header, however I do receive the `Transfer-Encoding: chucked` header. This is the output of the curl request:

```
> GET /storage/representations/proxy/image.jpg HTTP/1.1
> Host: localhost:3333
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Sat, 22 Oct 2022 12:21:22 GMT
< ETag: W/"1b9d16acfb817b44d4e1b1d0493b456c"
< Last-Modified: Sat, 01 Jan 2011 00:00:00 GMT
< Content-Type: image/jpeg
< Content-Disposition: inline; filename="image.jpg"; filename*=UTF-8''image.jpg
< Cache-Control: max-age=3155695200, public
< X-Request-Id: a15f379d-e7ad-42f5-a259-027b2a0aee45
< X-Runtime: 0.094806
< Transfer-Encoding: chunked
```

As you suggest, there is something else that is dropping the `Transfer-Encoding` header, and I will investigate and let you know what I find.

Thanks again!

**Comment by hahmed** [comment]
I will close this issue for now, as it's not clear this is an issue with rails, if you feel it is after your investigation, please feel free to leave a message so this issue can be re-opened.
