### ISSUE TITLE
database.yml production block executing in development mode

### ISSUE THREAD

**Issue by omarluq** [rails/rails#46349]
### Steps to reproduce
I am trying to use both dotenv and rails credentials one for dev env and the latter for production to avoid sharing the master keys with all developers and to give more control over the local environment. I have the following code in my `database.yml`

```ruby
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT']' %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  host: <%= Rails.application.credentials.database[:host] %>
  port: <%= Rails.application.credentials.database[:port]' %>
```
I am not setting the rails credentials for the development env however I expected that the production block will not be excuted 
### Expected behavior

the production block should be completly ignored when serving the application or loading the console when `Rails.env == 'development'`
### Actual behavior

when I try to load the console or serve the application I'm getting the following error: 
```
database.yml:91:in `<main>': Cannot load database configuration: (NoMethodError)
undefined method `[]' for nil:NilClass

; _erbout.<<(( Rails.application.credentials.database[:username] ).to_s); _erbout.<< "\\n  password: ".freeze
```
### System configuration
**Rails version**:
7.0.0
**Ruby version**:
3.1

**Comment by matthewd** [comment]
The config file is a text document which is preprocessed via ERb when we read it; we cannot selectively execute parts of the file, because its structure doesn't exist at that time. 

The most direct way of approximating the behaviour you're describing would be for you to add a `<% if .. %>` block around the `production:` section in the template.
