### ISSUE TITLE
Rails 7.0 configs missing from config/initializers/new_framework_defaults_7_0.rb

### ISSUE THREAD

**Issue by alexadia** [rails/rails#46350]
Hi,

I noticed that the file config/initializers/new_framework_defaults_7_0.rb generated by running bin/rails app:update with config.load_defaults 6.1 does not include two configs mentioned in the [config doc](https://guides.rubyonrails.org/configuring.html#default-values-for-target-version-7-0). The two missing configs are:

* Rails.application.config.action_dispatch.return_only_request_media_type_on_content_type
* Rails.application.config.active_support.disable_to_s_conversion

### System configuration
**Rails version**: 7.0.4 with config.load_defaults 6.1
**Ruby version**: 2.7.2

**Comment by fatkodima** [comment]
@alexadia Would you like to work on a PR? 
Seems like `config.active_storage.multiple_file_field_include_hidden` is missing too.

**Comment by alexadia** [comment]
I wonder if the [disable to_s conversion config](https://guides.rubyonrails.org/configuring.html#config-active-support-disable-to-s-conversion) is intentionally not included in the new framework defaults file since it needs to added to the config/application.rb file instead. 

Perhaps a comment in the [configure framework defaults upgrade section](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#configure-framework-defaults) that not all defaults are in the new frameworks file would suffice so that people know to also check [the new configurations list](https://guides.rubyonrails.org/configuring.html#default-values-for-target-version-7-0).

**Comment by skipkayhil** [comment]
Fixed in #46358

**Comment by alexadia** [comment]
Thank you for addressing this! 🎆
