### ISSUE TITLE
config.active_record.encryption.add_to_filter_parameters=true not filtering parameters in console

### ISSUE THREAD

**Issue by GMolini** [rails/rails#46359]
Im not sure if its because I understood the docs uncorrectly, but I expected that when using in a model 
`encrypts :content` if I did in the rails console `MyModel.first` I would see something like 
```
#<MyModel:0x00007f71632f7908  
  id: 1,
  content: "[FILTERED]"
```
instead, I see the content value printed in plain text. Only if I manually add the value to config.filter_parameters
`config.filter_parameters += [:content]` its filtered as expected.

It doesnt matter if I set `config.active_record.encryption.add_to_filter_parameters = true` in my application.rb

### System configuration
**Rails version**:
rails (7.0.2.4)
**Ruby version**:
ruby 3.1.2p20

**Comment by skipkayhil** [comment]
I am able to reproduce, it looks like this is because the console doesn't load `ActionController::Base` which is where Encrypted attributes get added to the application's `filter_parameters`. I'll investigate a bit and open a PR
