### ISSUE TITLE
[ActiveStorage] use for existing files

### ISSUE THREAD

**Issue by rctneil** [rails/rails#46379]
Hi,

I have a lot of files already on S3 that I wish to use with ActiveStorage.   The problem is, the majority of my sites data gets populated and updated by wiping it all out and being reimported by way of an Excel document and an import script.

Basically for this app, the truth is in a spreadsheet, I KNOW it's not ideal but that's the way it is here for this app.

I do not wish to download all my files each time I do a reimport.

Therefore I am writing a rake task that creates the appropriate ActiveStorage records and associates them with the correct model instances after an import.   This MOSTLY works fine. It does create everything but it then comes to analysing and it says with `ActiveStorage::IntegrityError`.   I'm not 100% sure but I assume this is something to do with the checksum?

Currently my task can be viewed here: https://gist.github.com/rctneil/7e275e74c66dd7a6ffc804ff1d740121

Any suggestions to how I can get the analysing done and the Integrity Error to be resolved?

Thanks!

**Comment by hahmed** [comment]
👋 @rctneil 

I think you might get a bit more direction/help on this issue if you post on https://discuss.rubyonrails.org or the discord?

The issue tracker is reserved for bugs, so i will go ahead and close this issue as the issue.

I will post a few things I found whilst looking at this;

> I'm not 100% sure but I assume this is something to do with the checksum?
Yup, looks like it is related to a checksum error thrown by aws s3.

Did you have a chance to look at https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#large-object-checksums or https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html?

It looks like you may need to add an additional header to get the checksum to work, but I have not checked that out... If this ends up being an issue with rails itself, please do report back and this issue can be re-opened.
