### ISSUE TITLE
`ActiveRecord::StrictLoadingViolationError` after initializing association owner with primary key

### ISSUE THREAD

**Issue by richardboehme** [rails/rails#46392]
### Steps to reproduce

When initializing a model with an id attribute (without persisting it), working with a `has_many` association raises a `StrictLoadingViolationError`.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.new(id: 1)
    post.strict_loading!

    post.comments << Comment.new
  end
end
```

### Expected behavior

The `StrictLoadingViolationError` should not be raised, because no records are persisted and thus are not loaded lazily.

### Actual behavior

ActiveRecord will throw a `StrictLoadingViolationError`.

After some digging through the code I think it's because it tries to load the `comments` association. It does that because `ActiveRecord::Associations::Association::find_target?` (see [here](https://github.com/rails/rails/blob/2612b88abfca6ac80db1923e133d5e7822bcef0b/activerecord/lib/active_record/associations/association.rb#L274)) returns `true`. This is due to the foreign key column (in this case Post's `id` column) being present on the post model (see [here](https://github.com/rails/rails/blob/2612b88abfca6ac80db1923e133d5e7822bcef0b/activerecord/lib/active_record/associations/foreign_association.rb#L7) for the check).

I'm not sure if this use case should even be supported, so feel free to close this if initializing a model with an id should not be supported. My use case is testing serializers without creating database traffic, but I'd be fine disabling strict loading for those tests.

### System configuration
**Rails version**: main (2612b88)

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by ghiculescu** [comment]
No answers just yet, but some notes...

> if initializing a model with an id should not be supported

It looks like it should be, as it enables functionality such as [this](https://github.com/rails/rails/blob/c6b227b95b631ead7ffd5c8984b16b0fbe5b3ca4/activerecord/test/cases/associations/has_many_associations_test.rb#L70). Basically it seems like AR is fine with you loading an association from a record if you give the record the primary key yourself as opposed to loading it from the database.

So I actually think the issue stems from [here](https://github.com/rails/rails/blob/2612b88abfca6ac80db1923e133d5e7822bcef0b/activerecord/lib/active_record/associations/collection_association.rb#L121), because the call to `load_target` is what eventually causes the attempt to load the association.

If you remove just the `load_target`, the only Active Record test that fails as a result is [this one](https://github.com/rails/rails/blob/2612b88abfca6ac80db1923e133d5e7822bcef0b/activerecord/test/cases/associations/join_model_test.rb#L494).

**Comment by ghiculescu** [comment]
Here is a relevant test case for `strict_loading_test.rb`:

```ruby
  def test_strict_loading_on_new_record_with_primary_key_and_build
    developer = Developer.new(id: Developer.first.id)
    developer.strict_loading!

    assert_nothing_raised do
      developer.audit_logs.build
    end
  end
```

**Comment by richardboehme** [comment]
Hey @ghiculescu! Thanks for looking into this issue. 

I tried the changes you did and they work like a charm! However they only seem to cover the case of concatenating records. In my actual application I'm replacing the association (using factory bot's `build` method) which still raises the error. I'm sorry for providing a wrong code example here... After looking at it a bit more I feel like in the case of setting/replacing the association directly, loading it is intended to be able to delete old records. We can't really prevent it, can we?

**Comment by ghiculescu** [comment]
> After looking at it a bit more I feel like in the case of setting/replacing the association directly, loading it is intended to be able to delete old records

Yes, I think so too. But I don't think you should get strict loading violations for that... 🤔

**Comment by richardboehme** [comment]
> > After looking at it a bit more I feel like in the case of setting/replacing the association directly, loading it is intended to be able to delete old records
> 
> Yes, I think so too. But I don't think you should get strict loading violations for that... 🤔

@ghiculescu Should I create a new issue for this?

**Comment by ghiculescu** [comment]
Yes please, with a repro script if you can. Feel free to tag me.
