### ISSUE TITLE
Document ActiveModel::Validations#validation_context

### ISSUE THREAD

**Issue by oljfte** [rails/rails#46391]
The `ActiveModel::Validations#validation_context` seems to be a public method, but it is not documented on the  https://api.rubyonrails.org/. If it is correct to use this publicly, shouldn't it be documented?

I was trying to do something like [this comment](https://github.com/rails/rails/pull/26897#issuecomment-291560176) but could not find the documentation...

Thanks.

**Comment by yahonda** [comment]
Hi, Thanks for opening an issue here. I think `validation_context` is documented at https://api.rubyonrails.org/classes/ActiveRecord/Validations.html#method-i-save via https://github.com/rails/rails/pull/36863

**Comment by oljfte** [comment]
Thank you for the response:)
Let me explain a little further.

Yes, I found the documentation for the `context:` option of the `ActiveRecord::Validations#save` method,
but I could not find any documentation on the accessor to the attribute called `validation_context` that is used internally to handle that context option.

Looking at this part of the code, I see that only the setter is made private, and the getter could still be called publicly.
https://github.com/rails/rails/blob/cfa9c9f89184cfb14bdfd8fce58a1b630142007a/activemodel/lib/active_model/validations.rb#L48-L49

And this method could be used in situations like this https://github.com/rails/rails/issues/21957#issue-111333714 (see "How to do" section), because there's still no `except:` option for `validate` method, like the one proposed in the linked comment.

but this looks kinda workaround-ish to me so I wasn't sure if it should be documented as a public method or not.
