### ISSUE TITLE
Invalid HTML generated by hidden inputs (`autocomplete="off"`)

### ISSUE THREAD

**Issue by ahukkanen** [rails/rails#46405]
### Steps to reproduce
1. Take any form generated through rails containing hidden inputs (e.g. the `_method` or `token` inputs)
2. Copy the HTML source of that page
3. Paste this to: https://validator.w3.org/nu/#textarea
4. See invalid HTML

![Invalid HTML](https://user-images.githubusercontent.com/864340/199430948-7feae5ce-c46f-4d42-a19f-fff1b24d235b.png)

### Expected behavior
We would expect the HTML produced by the Rails form helpers to be valid HTML.

### Actual behavior
The HTML produced by Rails form helpers is not valid.

### System configuration
**Rails version**: Latest (`main` branch)

**Ruby version**: Any compatible version (for the relevant project we are using 3.1.1 if it matters)

### Additional context
This functionality originates from #43280 (related issue #42610).

Related discussion:
https://discuss.rubyonrails.org/t/form-with-first-field-value-is-overriden-with-a-token-like-string/74861/4

Related Firefox bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=520561

**Comment by byroot** [comment]
Given that the Firefox bug still isn't fixed, I don't think we can do much here. 

I get that invalid HTML isn't cool, but if reverting this change means re-introducing a bug, it's a hard sell.

What are you expecting us to do here?

**Comment by ahukkanen** [comment]
I think the proper solution would be to apply the `autocomplete="off"` attribute for hidden inputs only for Firefox and leave it out for other browsers.

I think Rails should generate valid HTML by default, although I also understand the willingness to have maximum browser support. The main problem with invalid HTML is that this is one criteria that fails with accessibility audits. So this particular issue has to be documented as an accessibility violation by the services that are required to be accessible.

IMO this kind of "hack" should not be part of the Rails core in the first place and rather it should be its own separate gem that fixes the issue for FF.

**Comment by byroot** [comment]
> I think the proper solution would be to apply the `autocomplete="off"` attribute for hidden inputs only for Firefox

No that's a very bad solution because:

  - Detecting a browser on the server side is unreliable, you need to parse the user agent etc.
  - If you start doing this, all your fragment and page caching now need to be scoped by browser, it's terribly inefficient.

> IMO this kind of "hack" should not be part of the Rails core in the first place

Disagree, we had hacks to handle various browsers bugs basically forever. I understand your viewpoint, but it's really not pragmatic at at..

**Comment by SampsonCrowley** [comment]
@byroot this takes things too far. I can't set autocomplete attributes for hidden fields because hidden field helper is overriding it

![Screenshot 2023-03-16 at 10 11 23 AM](https://user-images.githubusercontent.com/22461638/225683353-09ef9e65-ac67-46f7-bb21-8e7176e95c7c.png)
![Screenshot 2023-03-16 at 10 07 47 AM](https://user-images.githubusercontent.com/22461638/225683354-d9e1b116-fa45-4cde-83cb-bc0ae59a84bf.png)
![Screenshot 2023-03-16 at 10 11 42 AM](https://user-images.githubusercontent.com/22461638/225683351-584afde7-04b0-4ecd-9f8a-f739265063e8.png)

**Comment by byroot** [comment]
@SampsonCrowley that's a bug and that we can fix no problem. Please open either a PR or issue for it.

**Comment by zzak** [comment]
I've started #47798 to fix the bug for overriding autocomplete, but probably needs to add a test or two, everything was green locally. Anyway, let's move there!

**Comment by jdufresne** [comment]
The linked bugzilla was marked as resolved 9 months ago. Are we in a position to reconsider the need for `autocomplete`?

**Comment by byroot** [comment]
> The linked bugzilla was marked as resolved 9 months ago

No-one claimed to have fixed the bug though, some bot was re-triaging and failed to reproduce, It's really not clear if Firefox bug was fixed.

**Comment by zzak** [comment]
@byroot If you feel like this still applies, could you look at #47798? I'm happy to add tests or whatever if it makes sense. :pray:

**Comment by kshnurov** [comment]
This is insane. Firefox has a 3% share, the bug is rare and hard to reproduce, but someone decided to **break HTML for all Rails apps!** #43280 must be reverted, whoever wants can add autocomplete to their hidden fields.

**Comment by jcracknell** [comment]
Just dropping in here to confirm that this is indeed still an issue in Firefox 126 (May 2024), and I just finished *backporting* `autocomplete=off` into an old rails 1.9.3 app.

The autocompletion seems to get worse depending on the number of inputs in a form/page (the app in question has a page with hundreds in repeating formlets) which suggests a hash collision or something similar going on during the completion process.

**Comment by kshnurov** [comment]
> calling something insane is offensive
> invalid HTML, but is it really a problem?
> I'm sorry to say that you make no decision here. ... how you put it only got you ignored.

Wow, such an infantile, ignorant and arrogant attitude. No wonder rails has more bugs than ever and they're not fixed for years.

**Comment by rafaelfranca** [comment]
I warned you, and you are back insulting me. Banned. Take care.
