### ISSUE TITLE
Set trix production release as "latest" on npm instead of the beta

### ISSUE THREAD

**Issue by moenodedev** [rails/rails#46411]
### Steps to reproduce

1. Create a new rails app
2. Run `npm outdated`
3. trix 2.0.0-beta.0 shows as the latest version instead of the production release
```
$ npm outdated
Package  Current  Wanted        Latest  Location           Depended by
trix       1.3.1   1.3.1  2.0.0-beta.0  node_modules/trix  rails-app
```

### Expected behavior
`npm outdated` shouldn't suggest beta versions of rails packages

### Actual behavior
`npm outdated` suggests  trix 2.0.0-beta.0

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

See https://github.com/basecamp/trix/issues/993

**Comment by eileencodes** [comment]
Hi @moenodedev the latest release is set in NPM and not in Rails source code. Rails also doesn't maintain Trix - it's under the Basecamp org. It also looks like they resolved it on the trix npm side. Since this isn't a bug in the framework I'm going to close this.
