### ISSUE TITLE
Memory bloat / memory leak caused by find_each

### ISSUE THREAD

**Issue by collimarco** [rails/rails#46436]
### Steps to reproduce

Sometimes we need to delete very large amounts of data from the database (e.g. millions of records).

We cannot use a single database transaction in SQL, because it would lock the tables for some seconds... So we delete the records one by one using `find_each`.

However we see that our background workers go from 500MB to several GBs when we run the following code (and this can cause OOM kills and all kind of issues):

```ruby
class Project < ApplicationRecord
  def destroy_outside_transaction
    subscriptions.find_each { |s| s.destroy }
    notifications.find_each { |n| n.destroy }
    destroy
  end
end
```

### Expected behavior

`find_each` is made to process large amounts of data and should not produce large memory bloats.

### Actual behavior

`find_each` causes memory bloat / memory leak.

### System configuration

**Rails version**: 7.0.4
**Ruby version**: 3.1.2

**Comment by fatkodima** [comment]
Can you use `subscriptions.in_batches.delete_all`? And the same for notifications. 
Do you have/need any callbacks in them to run?

**Comment by collimarco** [comment]
@fatkodima Thanks for the suggestion! I'll try it.

In the meantime I was testing `find_each` on my Mac and I am confused since I cannot reproduce the memory bloat. This is a dummy task that I am using and it produces constant memory usage on my personal computer...

```bash
$ /usr/bin/time -l bundle exec rake memory:bloat
```

```ruby
namespace :memory do
  task :bloat => :environment do
    sum = 0
    50.times do
      Subscription.find_each do |s|
        sum += s.id
      end
    end
    puts sum
  end
end
```

I have also read some old posts that recommend to use `ActiveRecord::Base.uncached`, but it is not producing any difference in my rake task above.

**Comment by fatkodima** [comment]
`ActiveRecord::Base.uncached` is already used in batches implementation - https://github.com/rails/rails/blob/45eceb2744ce141d9251ba2ca57c3a667b009247/activerecord/lib/active_record/relation/batches.rb#L232

**Comment by collimarco** [comment]
I am starting to think that the constant growth in memory is caused by the number of Sidekiq workers, and not by the work (`find_each`) itself.

https://github.com/mperham/sidekiq/issues/3892

Other hypothesis is that the problem is only on Ubuntu/linux and not on other platforms, because on my Mac I cannot reproduce the bloat.

In any case I have tried to lower the concurrency in Sidekiq and I want to see if it solves the large memory increase over time. If that's the reason, we can close this. I'll monitor for a few days and let you know.

**Comment by collimarco** [comment]
By searching "sidekiq memory" on Google, I found a lot of issues that can be possibly related to this.

For example:

- https://medium.com/1mgofficial/how-we-solved-sidekiq-memory-issue-in-rails-application-8995ad2b4f83
- https://github.com/mperham/sidekiq/issues/3824
- https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html
- https://hustle.bizongo.in/adventures-with-sidekiq-where-did-the-memory-go-12163cb1e7bf
- and many many others.

**Comment by collimarco** [comment]
Another related post on Heroku: https://devcenter.heroku.com/changelog-items/1683

**Comment by eileencodes** [comment]
Those are all pretty old so I'd think something would have been done by now. Anyway if we can't find anything in Rails, then this isn't a Rails issue so I'm going to close.

**Comment by collimarco** [comment]
If anyone lands here in the future, here's the solution that worked for us:

https://answers.abstractbrain.com/how-to-reduce-memory-usage-in-ruby/
