### ISSUE TITLE
Non-unique ids when preloading associations with includes or eager_load

### ISSUE THREAD

**Issue by mak-dunkelziffer** [rails/rails#46455]
### Steps to reproduce
Compare the size of `#to_a` and `#ids` while loading associated records.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def setup
    post = Post.create!
    post.comments << Comment.create!
    post.comments << Comment.create!
    post.comments << Comment.create!
    post.save!
  end

  def teardown
    Post.all.destroy_all
  end

  def test_count_coherent
    assert_equal Post.all.to_a.size, Post.all.ids.size
  end

  def test_eager_load_count_coherent
    assert_equal Post.all.eager_load(:comments).to_a.size, Post.all.eager_load(:comments).ids.size  # Bug
  end

  def test_includes_count_coherent
    assert_equal Post.all.includes(:comments).to_a.size, Post.all.includes(:comments).ids.size  # Bug
  end
  
  def test_preload_count_coherent
    assert_equal Post.all.preload(:comments).to_a.size, Post.all.preload(:comments).ids.size
  end
end
```

### Expected behavior
For each scope, I expect to get the same number of elements, whether I call `#to_a` or `#ids`. If I get repeats, I expect them to happen in both cases.

### Actual behavior
This assumption fails, as soon as I preload an association with `#includes` or `#eager_load`. When I load associations, then `#to_a` returns each record once, however `#ids` returns duplicate entries. A post ID is returned 5 times if the post has 5 comments.

### System configuration
First Test
**Rails version**: 4.2 LTS
**Ruby version**: 2.6.10

Second Test
**Rails version**: 7.0.3.1
**Ruby version**: 3.1.2

**Comment by fatkodima** [comment]
Agreed. For `eager_load`/etc It does a `JOIN`, so we have duplicates from there. 
Imo it does not make much (if any) practical sense to have duplicates.
So, the simplest change is:
```diff
diff --git a/activerecord/lib/active_record/relation/calculations.rb b/activerecord/lib/active_record/relation/calculations.rb
index db650e5a70..4c3709357c 100644
--- a/activerecord/lib/active_record/relation/calculations.rb
+++ b/activerecord/lib/active_record/relation/calculations.rb
@@ -322,7 +322,7 @@ def async_pick(*column_names)
     #   Person.ids # SELECT people.id FROM people
     #   Person.joins(:companies).ids # SELECT people.id FROM people INNER JOIN companies ON companies.person_id = people.id
     def ids
-      pluck primary_key
+      pluck(primary_key).uniq
     end

     private
``` 

But there is a similar problem for something like `Post.all.includes(:comments).pluck(:title)`. I think, we should remove duplicates from there too.

@byroot Wdyt on this?

**Comment by byroot** [comment]
Ack. I’m away for a few days I’ll try to review this when I’m back.

**Comment by joshuay03** [comment]
Hello! @mak-dunkelziffer @fatkodima @byroot

I was looking for an issue to tackle and decided to get a PR up in case you wish to proceed with this change: https://github.com/rails/rails/pull/46503.

Rather than just grabbing the unique results I've amended the logic to only grab the IDs for the base model.
I think calling `ids` implies that just the ids for the base model will be grabbed, `pluck` can still be used to grab the ids of all loaded associations using `pluck(:id)`.
