### ISSUE TITLE
No content-disposition=inline for blob perma-urls

### ISSUE THREAD

**Issue by WillTaylor22** [rails/rails#46460]
### Steps to reproduce

- Ensure inline allowed, i.e. in `environments/development.rb` set `config.active_storage.content_types_allowed_inline =
    %w(image/png)` and `config.active_storage.content_types_to_serve_as_binary -= ['image/png']`
- Add blob to S3
- Confirm no content disposition meta-data on blob in S3
- Run `app.rails_blob_url(blob)` or `app.rails_blob_url(blob, disposition: :inline)` to get a perma url
- Check destination with `curl -I [URL]` you get:

```
HTTP/1.1 302 Found
...
Location: ... ?response-content-disposition=attachment ...
...
```

This response-content-disposition is being added by rails as it's not in the S3 settings.

### Expected behavior

app.rails_blob_url(blob) should generate the S3 redirect url with `content-disposition=inline`.

I.e. the same as
```
Aws::S3::Object.new(
  ENV["AWS_BUCKET"],
  blob.key
).presigned_url(:get, response_content_disposition: 'inline', expires_in: 3600)

```
### Actual behavior

app.rails_blob_url(blob) generates an S3 url with `content-disposition=attachment`.

### System configuration
**Rails version**:
gem 'rails', '~> 7.0.3'

**Ruby version**:
ruby '3.1.1'

**Comment by hahmed** [comment]
Hey @WillTaylor22, thanks for reporting this issue!

I think it would be easier if you could link an app or post a reproducible bug report that follows the format of https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_storage_gem.rb that makes it easier to determine if this is a bug or not.

I'm assuming that the last line below returns `nil` (and not attachment) for you?

```
blob = ActiveStorage::Blob.new(content_type: "image/png") # you could use your existing attachment that you uploaded, this is just an example
blob.send(:forced_disposition_for_serving)
```

If that's the case, then when you are calling url `app.rails_blob_url(blob)` you should be getting `disposition: :inline` for private blobs (presigned urls). For public blobs, this is not true, please refer to `activestorage/lib/active_storage/service/s3_service.rb` the method `public_url`. 

I don't think public urls can have the `disposition: :inline`, maybe I'm wrong?
