### ISSUE TITLE
Active Storage with vips can't transform animated gifs

### ISSUE THREAD

**Issue by miharekar** [rails/rails#46465]
I [wrote a comment in the original thread](https://github.com/rails/rails/issues/37833#issuecomment-1072542505) back in March, but since the issue got closed, I guess it went unnoticed.

There have been two more comments with the same issue, so I'm certain I'm not the only one with the problem.

I've just encountered it again in another project, so I'm now reopening the issue via a new issue 😅

### Steps to reproduce
Have vips library, and a model with an ActiveStorage variant. Upload a gif.

### Expected behavior
The variant should be animating.

### Actual behavior
The variant isn't animating.

**Comment by p8** [comment]
@miharekar Thanks for reporting the issue.
I think this is more an issue with libvips than with Rails
https://github.com/libvips/ruby-vips/issues/344#issuecomment-1190044945

**Comment by p8** [comment]
Closing this as it seems an issue with libvips.

**Comment by mati-a** [comment]
For anyone still having this issue. Using  `loader: { n: -1 }` explained [here](https://github.com/libvips/libvips/issues/2668#issuecomment-1336163797) worked for me:

``` ruby
file.variant(
  loader: { n: -1 },
  resize_to_fit: [
    THUMBNAIL_DIMENSION,
    THUMBNAIL_DIMENSION
  ]
)
```

Versions:
```
libvips42/now 8.10.5-2 arm64

rails (~> 7.0.3)
ruby-vips (2.1.4)
```

**Comment by Set27** [comment]
> For anyone still having this issue. Using `loader: { n: -1 }` explained [here](https://github.com/libvips/libvips/issues/2668#issuecomment-1336163797) worked for me:
> 
> file.variant(
>   loader: { n: -1 },
>   resize_to_fit: [
>     THUMBNAIL_DIMENSION,
>     THUMBNAIL_DIMENSION
>   ]
> )
> Versions:
> 
> ```
> libvips42/now 8.10.5-2 arm64
> 
> rails (~> 7.0.3)
> ruby-vips (2.1.4)
> ```

I see topic create for .gif, but just is case, this one won't work for .webp
