### ISSUE TITLE
Bug: travel_to with validates inside model

### ISSUE THREAD

**Issue by llpereiras** [rails/rails#46463]
### Steps to reproduce
Hey Guys, below steps to reproduce my problem.

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 7.0.4"
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require 'rails'
require 'active_model/railtie'
require 'active_record/railtie'
require 'active_storage/engine'
require 'action_controller/railtie'
require 'action_view/railtie'
require "active_support"
require 'active_support/testing/time_helpers'
require "active_support/core_ext/object/blank"

require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.date :birth_date
  end
end

class Post < ActiveRecord::Base
  validates_comparison_of :birth_date, less_than_or_equal_to: -> { Date.today }
end


class BugTest < Minitest::Test
  include ActiveSupport::Testing::TimeHelpers

  def setup
    Time.zone = 'Brasilia'
    travel_to '2020-10-01' do
      post = Post.create!(birth_date: DateTime.current)
    end
  end

  def teardown
    Post.all.destroy_all
  end

  def test_validate_birth_date
    assert_equal Post.first.birth_date.to_s, '2020-10-01'
  end
end

```

```ruby

Error:
BugTest#test_validate_birth_date:
ActiveRecord::RecordInvalid: Validation failed: Birth date wrong number of arguments (given 1, expected 0)
    /usr/share/rvm/gems/ruby-3.1.2/gems/activerecord-7.0.4/lib/active_record/validations.rb:80:in `raise_validation_error'
    /usr/share/rvm/gems/ruby-3.1.2/gems/activerecord-7.0.4/lib/active_record/validations.rb:53:in `save!'
    /usr/share/rvm/gems/ruby-3.1.2/gems/activerecord-7.0.4/lib/active_record/transactions.rb:302:in `block in save!'

```
## Expected behavior

Post record should be created with old dates using travel_to

### Actual behavior

Validates ignore stub of date with travel_to
Using the proc function happens error of wrong number of parameters

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**Comment by fatkodima** [comment]
Can you create a reproducible test script using the following template - https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb?
It will be easier to us to debug the problem using it.

**Comment by ghiculescu** [comment]
The issue is probably because all these dates...

```ruby
  validates :published_at, comparison: { greater_than_or_equal_to: DateTime.current.beginning_of_day }
  validates_comparison_of :published_at, greater_than_or_equal_to: Date.today

  validates_comparison_of :published_at, greater_than: Date.today - 1.day
  validates :published_at, comparison: { greater_than: DateTime.current.beginning_of_day - 1.day }
```

get evaluated at "boot" time, and not at runtime. ie. they get evaluated before the `travel_to` line runs. In the context of a webserver, they'd get evaluated when the server starts, not a few days later when the request is processed.

You could use a proc instead to avoid the issue, then it would be evaluated at runtime. See the example in the docs: https://edgeapi.rubyonrails.org/classes/ActiveModel/Validations/HelperMethods.html#method-i-validates_comparison_of

```ruby
  validates_comparison_of :birth_date, less_than_or_equal_to: -> { Date.today }
```

**Comment by llpereiras** [comment]
@fatkodima I update my first comment and add the script to simulate my problem.
@ghiculescu Thanks for your suggestions, but I tried to use proc, and it not work as expected.

**Comment by fatkodima** [comment]
You have a mistake in a validation. It works in the latest changes from `main`, but for `7.0.4` you need an argument: `validates_comparison_of :birth_date, less_than_or_equal_to: ->(_) { Date.today }`.

With this change, tests are passing for me.

**Comment by llpereiras** [comment]
@fatkodima Many thanks now it's works.
