### ISSUE TITLE
Limiting Display

### ISSUE THREAD

**Issue by Ben-Nyaoro** [rails/rails#46480]
How do I limit the display from rich text content. Say for example I want to display the first 80 characters of rich text content  In ruby for example you would do for example `@model.title.first(80)`. It does not work like this iwith rich text content.

### Steps to reproduce

```ruby
# Your reproduction script goes here
```

### System configuration
**Rails version**:

**Ruby version**:

**Comment by dancristianb** [comment]
@Ben-Nyaoro you should be able to use [#to_plain_text](https://github.com/rails/rails/blob/1f6202a1fe6cd976993c88a7e22afc165ba06c5f/actiontext/app/models/action_text/rich_text.rb#L21) then `first(80)` or `truncate(80)` something like `@model.title.to_plain_text.truncate(80)`

**Comment by eileencodes** [comment]
Hi @Ben-Nyaoro - btw, we reserve the Rails issues tracker for bugs in the framework. If you need help with exiting functionality you can use our discussion board https://discuss.rubyonrails.org/ or stackoverflow. Thanks for understanding.

**Comment by Ben-Nyaoro** [comment]
@eileencodes thanks understood. @dancristianb Thank you very much it worked.
