### ISSUE TITLE
Rails controller not responding with '.to_json' of instances when testing (rspec)

### ISSUE THREAD

**Issue by bubbaspaarx** [rails/rails#46506]
## What Ruby, Rails and RSpec versions are you using?

Ruby version: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin21]
Rails version: Rails 6.1.7
RSpec version: RSpec 3.12

## Observed behaviour

I am not certain this is a direct rails or rspec error but when testing a controller action, we expect our response to be a full json object of the instance we are fetching. What we receive though is a json object of 

```
=> render(json: @instance)
"{\"type\":\"class_name\"}"
```

If I manually call '.to_json' on my instance at the point of render

```
=> render(json: @instance.to_json)
<full object json response>
```

I get a full response back of my whole object, which is the expected behaviour and is matched with development and production environments. 

I can't see a reason why the implicit 'to_json' is not called when calling from rspec which is stated in the rails docs

 [![rails guide][1]][1]

  [1]: https://i.stack.imgur.com/NO2mQ.png

Any help is greatly appreciated. TIA

The controller action

```
def show
  render(json: @book)
end
```

book_controller_spec.rb
'json' is a custom JSONHelper which just parses the response.body

```ruby
RSpec.describe(Api::V1::BooksController, type: :controller) do
  context '#show' do
    it 'returns the book with the correct ID' do
      get :show, params: { id: 1 }
      expect(json[:id]).to(eq(1))
    end
  end
end
```

The controller action

```
def show
  render(json: @book)
end
```

book_controller_spec.rb
'json' is a custom JSONHelper which just parses the response.body

```ruby
RSpec.describe(Api::V1::BooksController, type: :controller) do
  context '#show' do
    it 'returns the book with the correct ID' do
      get :show, params: { id: 1 }
      expect(json[:id]).to(eq(1))
    end
  end
end
```

**Comment by hahmed** [comment]
Hey @bubbaspaarx

Maybe I have not fully understood this issue, please correct me if I'm wrong. I created a new app, with rspec-rails, updated my show action and created a test similar to what you have, and I'm not seeing anything out of place. 

Controller:
```
  def show
    render(json: @widget)
  end
```
Test:
```
RSpec.describe "/widgets", type: :request do
  describe "GET /show" do
    it "renders a successful response" do
      widget = Widget.create! name: "something"
      get widget_url(widget)
      expect(response).to be_successful
      puts response.body
      expect(json[:id]).to(eq(1))
    end
  end

  private

  def json
    JSON.parse(response.body, symbolize_names: true)
  end
end
```

> we expect our response to be a full json object of the instance we are fetching.

I'm seeing a json object.

Output from test run:

```
{"id":1,"name":"something","created_at":"2022-11-23T22:05:31.403Z","updated_at":"2022-11-23T22:05:31.403Z"}
```

Any chance you could post a fully reproducible example? Maybe link a github repo that shows this issue?
