### ISSUE TITLE
ActiveRecord - changing store to store_accessor converts ActiveSupport::HashWithIndifferentAccess to string on json/jsonb field

### ISSUE THREAD

**Issue by hsearcy** [rails/rails#46502]
### Steps to reproduce
Run the below script, then change this line:

`store :properties, accessors: %i[title body], prefix: true, coder: YAML`

to 

`store_accessor :properties, %i[title body], prefix: true`

and re-run the script.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem 'rails', '7.0.4'
  gem 'pg'
  gem 'puma'
end

require "active_model/railtie"
require "active_record/railtie"
require "minitest/autorun"
require 'logger'

ENV['DATABASE_URL'] = 'postgres://postgres:postgres@localhost:5432/testing_db'
ActiveRecord::Base.establish_connection(
  {:adapter => 'postgresql',
   :database => 'testing_db'}
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema[7.0].define do
  unless table_exists?(:posts)
    create_table :posts, force: true do |t|
      t.jsonb "properties"
    end
  end
end

class Post < ActiveRecord::Base
  store :properties, accessors: %i[title body], prefix: true, coder: YAML
end

class App < Rails::Application
  config.eager_load = false
  config.active_record.legacy_connection_handling = false
end

App.initialize!

class BugTest < Minitest::Test

  def test_index
    Post.create!(properties: {title: 'some title', body: 'some body'})
    first_post = Post.first
    puts "Class: #{first_post.properties.class}, Post: #{first_post.attributes}"
    assert_equal ActiveSupport::HashWithIndifferentAccess, first_post.properties.class
    assert_equal 'some title', first_post.properties[:title]
  end
end
```

### Expected behavior
The assertions should all pass, and the record should either maintain its data type (ActiveSupport::HashWithIndifferentAccess) or return as a regular Hash. `first_post.properties` should be equal to `{ title: some title, body: some body }`

### Actual behavior
The second run fails, and the value for `first_post.properties` returns as a String with value `"---\ntitle: some title\nbody: some body\n"`

Furthermore, if the record is originally created in Rails 6.1.3.1, and then the app is updated to 7.0.4 with the same `store` -> `store_accessor` change, then `first_post.properties` returns as a string with value `"--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess\ntitle: some title\nbody: some body\n"`. (I uncovered this issue while converting an app to Rails 7)

EDIT: The strings actually work just fine like that with `store`, so I'm guessing that YAML parses them. However, converting them to store_accessor does break them. I'm guessing the proper way to do the conversion would be to run a migration to YAML parse them and then save them again?

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.0.1

**Database**: PostgreSQL

I have also tested the field as `json` instead of `jsonb` and got the same result. In the original app where I did this, the `store` did not have a `coder` specified, but the fields that get mangled are ActiveSupport::HashWithIndifferentAccess fields. This is unexpected behavior since the [docs here](https://api.rubyonrails.org/classes/ActiveRecord/Store.html) state that you can simply use `store_accessor` with PostgreSQL json fields. It could be that I am simply misunderstanding the docs, but it was surprising behavior 😅

**Comment by javiyu** [comment]
Hello @hsearcy,

I think the problem is storing the attributes in a JSON field with YAML format in the first case. While this is supported ( a string is still a valid JSON ) the YAML serializer should only be used for string columns.

If you are using JSON or JSONB fields there is no need to encode the information since the database does it for you hence the `store_accessor` recommendation in the docs.

> I'm guessing the proper way to do the conversion would be to run a migration to YAML parse them and then save them again?

Exactly, once you convert the information to JSON format you should be able to use `store_accessor`.
