### ISSUE TITLE
String#blank? doesn't catch specific list of empty unicode characters

### ISSUE THREAD

**Issue by Rub1st** [rails/rails#46504]
Hey, guys!

I found a rather interesting problem in the `blank?`, `present?`, `presence` for the String class. They don't check a specific list of empty unicode characters.

I want to expand `blank?` for the String class, adding a check for these unicode characters. I believe this will help a lot of people with presence checks, etc.

A list of empty unicode characters that are not checked with `blank?`:

```
\u2060
\u2061
\u2062
\u2063
\u180e
\u200b
\u200c
\u200d
```

**Comment by kalashnikovisme** [comment]
I've tried it. The result is the same. Tested on Ruby 

```
$> str = "\u2060\u2061\u2062\u2063\u180e\u200b\u200c\u200d"
 => "⁠⁡⁢⁣᠎​‌‍" 
$> str.blank?
 => false 
```

Will try to write failing test with it.

**Comment by kalashnikovisme** [comment]
Made failing test in the my fork. You can find it here.

https://github.com/rails/rails/commit/d884bfd1ee6ea97630476a5f99077b86341835f7

When I finish updating `blank` and `present?` methods,  I will create a Pull Request with a full implementation.

**Comment by p8** [comment]
@kalashnikovisme There is a closed PR that also tried to fix this: https://github.com/rails/rails/pull/39786 that has some relevant discussions.
