### ISSUE TITLE
Improve Rails Upgrade Guide: "Key generator digest class changing to use SHA256"

### ISSUE THREAD

**Issue by rajivraman** [rails/rails#46500]
### Steps to reproduce

After upgrading from Rails 6 to Rails 7, we unknowingly wiped out all our user sessions. This had a negative effect on our site since we rely on users having persistent sessions to make regular purchases. Longtime users were forced to login again and some abandoned their purchases.

We traced this to the fact that we had not implemented the cookie-rotator as described [here](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#key-generator-digest-class-changing-to-use-sha256). When we realized this, we implemented the cookie-rotator and were able to maintain a seamless session for our existing users going forward.

My suggestion is to word this step less as a suggestion and more of a requirement. State that one of the consequences of not doing this is possible session less for existing users.

### Expected behavior

Users should not have been forced to login again.

### Actual behavior

Users were forced to login again and some abandoned their purchases.

### System configuration
**Rails version**:
7
**Ruby version**:
2.7

**Comment by p8** [comment]
I think moving the cookie-rotator change higher up the list and changing the title to something like:
"Key generator digest class change requires a cookie rotator"
or maybe:
"Add cookie rotator for SHA256 key generator"
Do you want to create a PR?

**Comment by rajivraman** [comment]
@p8 great ideas, I'll open a PR this week.
