### ISSUE TITLE
Disallow passing non-rewindable io to ActiveStorage::Blob.create_and_upload!

### ISSUE THREAD

**Issue by Earlopain** [rails/rails#46507]
### Steps to reproduce

Passing a Pathname to ActiveStorage::Blob.create_and_upload results in an infinite loop. The read method gets called on the io parameter when calculating the checksum, but since there is no pointer to advance it just keeps on reading from the beginning forever, fully utilizing a cpu core in the process.

It's kind of mentioned in the docs [here](https://github.com/rails/rails/blob/2d2fdc941e7497ca77f99ce5ad404b6e58f043ef/activestorage/app/models/active_storage/blob.rb#L6-L7) that the io must be rewindable. The fix is to simply not use Pathname, but it should either work or throw, infinite loops aren't great. One solution could be to check if the io responds to rewind in compute_checksum_in_chunks, which Pathname doesn't do.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_active_storage_pathname
    t = Tempfile.new
    t << "dummy"
    t.rewind

    io = Pathname.new(t.path)
    ActiveStorage::Blob.create_and_upload!(io: io, filename: "dummy")
    puts "never reached, create_and_upload! calculates the checksum in an infinite loop"
  end
end
```

### Expected behavior
It throws an error telling me that the io must be rewindable.

### Actual behavior
The function doesn't terminate and spins the cpu.

### System configuration
**Rails version**:
7.0.4
**Ruby version**:
3.1.2

**Comment by hahmed** [comment]
Hey there! Thanks for reporting this issue.

Usually rails does not validate arguments given. The expectation is pretty clear as per docs.

In AS, errors are raised if config is not found/invalid, invalid keys, missing service names etc. which makes a lot of sense, but I'm a little bit on the fence on this one though.

**Comment by Earlopain** [comment]
Perhaps the documentation can be expanded a bit? I don't think it's unreasonable to pass a Pathname here, even though the documentation mentions it isn't supported. My main issue I think was to only look at the individual function documentation, and not the class documentation as well. But even after reading that, it only clicked what was happening after investigating the actual AS code.

**Comment by ghiculescu** [comment]
Would you like to make a PR for the docs improvements? Since you came across the issue you can probably point to where the best improvement would be.

**Comment by rafaelfranca** [comment]
I think it is fine to raise an error in this case. Of course, if all we can do is to check if `rewind` is there.

**Comment by Earlopain** [comment]
There are two places where the error could be raised, in the public `unfurl` method, or in the private `compute_checksum_in_chunks`, which only gets called by `unfurl`. The correct error would be `ArgumentError` I assume.

Should I leave the PR as is or switch over to raise instead?

**Comment by rafaelfranca** [comment]
Let's switch over to raise instead.

**Comment by Earlopain** [comment]
Done!
