### ISSUE TITLE
NoMethodError: undefined method `content_type' for #<ActiveStorage::Attached::One:0x00007fddb690fe48>

### ISSUE THREAD

**Issue by Souravgoswami** [rails/rails#46520]
### Steps to reproduce

```ruby
# content_type() works when blob is not nil (file is present)
User.find { |x| x.resume.attached? && x.resume.blob }.resume.content_type
=> "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

# content_type() breaks when blob is nil (file is absent)
User.find { |x| x.resume.attached? && !x.resume.blob }.resume.content_type
NoMethodError: undefined method `content_type' for #<ActiveStorage::Attached::One:0x00007fddb690fe48>
from /home/sourav/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.7/lib/active_support/core_ext/module/delegation.rb:307:in `method_missing'
``````

### Expected behavior
`content_type()` should return the string content_type or nil if the magic isn't present.

### Actual behavior
The `attached?()` method returns true regardless the blob is present or deleted from storage. In cases where the file is deleted, the attached?() returns true, but the blob is nil.

In my  case using `resume.blob&.content_type()`   fixes the issue. But it becomes unclear why NoMethodError is raised on `resume.content_type()` when blob is nil. If blob is present, it returns the correct content_type.

### System configuration
**Rails version**:
Rails 6.0.3.7

**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Comment by fatkodima** [comment]
Rails 6.0 is not supported for bug fixes - https://guides.rubyonrails.org/maintenance_policy.html. 

Can you verify the problem persists with the latest changes from rails `main` branch? If so, can you create a reproducible test script using the template - https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_storage_main.rb?

**Comment by brenogazzola** [comment]
It's fixed on main:
```ruby
photo = Photo.new
=> #<Photo:0x00007f5ca0527c78
photo.file.attached?
=> false
photo.file.blob
=> nil
photo.file.content_type
=> nil
```
