### ISSUE TITLE
Rails CLI autocompletion

### ISSUE THREAD

**Issue by rnestler** [rails/rails#46547]
### Steps to reproduce

I was wondering if the rails executable does provide any shell autocompletion scripts. So far I couldn't find anything. There are several third party solutions ([omyzsh](https://github.com/ohmyzsh/ohmyzsh) seems to have a plugin, [/mernen/completion-ruby](https://github.com/mernen/completion-ruby) provides completions for bash), but no official one as it seems.

### Expected behavior

Rails provides official autocompletion scripts for bash / zsh or is able to generate them from the command line.

### Actual behavior

I couldn't find any official autocompletion scripts or a way to generate them with the rails executable.

### System configuration
**Rails version**: Rails 7.0.4

**Ruby version**: ruby 3.1.2p20

**Comment by eileencodes** [comment]
Hey @rnestler thanks for opening an issue! 

In general we don't want to maintain something like this. 1) autocompletion bash/zsh is not our expertise, 2) there are already existing tools, and 3) it wouldn't make sense for Rails to maintain a plugin for Ruby itself. It'd be cool to have an official plugin, but with the current expertise and maintenance load, I wouldn't want to add something unrelated to the framework code like this.

For the future, we don't accept feature requests on the issues tracker. You can reach out on [Discord](https://discord.gg/hMPjzEmk) or the [Forum](https://discuss.rubyonrails.org/) to get feedback before opening a PR.

**Comment by rnestler** [comment]
Thanks for the fast answer and the detailed reasoning!

> For the future, we don't accept feature requests on the issues tracker. You can reach out on [Discord](https://discord.gg/hMPjzEmk) or the [Forum](https://discuss.rubyonrails.org/) to get feedback before opening a PR.

Sorry for that. Is this noted somewhere? I found https://github.com/rails/rails/blob/main/CONTRIBUTING.md#do-you-intend-to-add-a-new-feature-or-change-an-existing-one which mentions the mailing list, but neither the Discord nor the Forum.
