### ISSUE TITLE
`Mysql2::Error: SAVEPOINT active_record_1 does not exist` after an `ActiveRecord::Deadlocked`

### ISSUE THREAD

**Issue by nvasilevski** [rails/rails#46556]
I'm creating this issue to keep context around an issue someone may run in the future.

The problem generally looks like a deadlock followed by a `Mysql2::Error` with ` SAVEPOINT active_record_#{n} does not exist` message. We have addressed a very similar problem in this PR - https://github.com/rails/rails/pull/46367 and the one described here is just a variation. However we are not experiencing this variation of the problem in production and I couldn't find anyone else experiencing it so I don't think that at this moment complicating Rails code is justified to prevent an issue that is a corner case and honestly caused by a wrong application design.

General way of running into this type of the problem would be while being inside a savepoint transaction to rescue a deadlock exception (usually it gets rescued unintentionally by a general `StandardError` rescue) and do nothing. This will cause parent transaction to perform a "commit" (release savepoint, to be specific) while database server has nothing to commit.
The issue we fixed was the same but instead of doing nothing, an application would issue a manual `ActiveRecord::Rollback` causing Rails to issue a ROLLBACK statement while server has nothing to rollback as deadlock automatically rolls back the transaction.

Here is a reproduction test that is failing on `main` with `Mysql2::Error: SAVEPOINT active_record_1 does not exist`. Don't forget to run it with `ARCONN=mysql2`

```ruby
    test "commit exception is swallowed after a rollback" do
      barrier = Concurrent::CyclicBarrier.new(2)
      deadlocks = 0

      s1 = Sample.create value: 1
      s2 = Sample.create value: 2

      thread = Thread.new do
        Sample.transaction(requires_new: false) do
          make_parent_transaction_dirty
          Sample.transaction(requires_new: true) do
            assert_current_transaction_is_savepoint_transaction
            s1.lock!
            barrier.wait
            s2.update value: 4

          rescue ActiveRecord::Deadlocked
            deadlocks += 1
          end

          s2.update value: 10
        end
      end

      begin
        Sample.transaction(requires_new: false) do
          make_parent_transaction_dirty
          Sample.transaction(requires_new: true) do
            assert_current_transaction_is_savepoint_transaction
            s2.lock!
            barrier.wait
            s1.update value: 3
          rescue ActiveRecord::Deadlocked
            # rescuing a deadlock in a savepoint transaction and doing nothing is wrong
            # as it stops propagation of the exception to the parent transaction 
            # causing parent transaction to issue a savepoint release statement while the database server has nothing to commit
            deadlocks += 1
          end
          s1.update value: 10
        end
      ensure
        thread.join
      end

      assert_equal 1, deadlocks, "deadlock is required for the test setup"
      assert_equal [10, 10], Sample.pluck(:value)
    end
```

### Possible solution
Similarly to https://github.com/rails/rails/pull/46367 a solution would be to add a condition that checks for `transaction.state.invalidated?` and skips issuing the `release savepoint` statement here:https://github.com/rails/rails/blob/e5f3d692030b41ed5ac671fedc9cc268b13ebd40/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L283
or perhaps here
https://github.com/rails/rails/blob/e5f3d692030b41ed5ac671fedc9cc268b13ebd40/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L497

**Comment by nvasilevski** [comment]
Closing as not intended to be worked on, at least at this moment

**Comment by matthewd** [comment]
Yeah, I think this is a variant of the scenario I described in https://github.com/rails/rails/pull/46367#issuecomment-1294200070
