### ISSUE TITLE
Testing is hard when the service option of ActiveStorage is used

### ISSUE THREAD

**Issue by shouichi** [rails/rails#46572]
### Steps to reproduce

When the service is specified e.g., `has_one_attached :avatar, service: :s3`, it is always used even for testing. In the example, running tests would end up sending requests to s3 which is not desirable. We can work around this by conditionally setting service e.g., `service: :s3 if Rails.env.production?` but that is not ideal.

### Expected behavior

DiskService is used for testing.

### Actual behavior

It sends requests to the actual service even for testing. This makes testing hard.

### System configuration
**Rails version**: Rails 7.0.4

**Comment by georgeclaghorn** [comment]
It doesn’t seem to be very well documented, but Active Storage supports per-environment service configurations for this reason. In the test environment, `config/storage/test.yml` takes precedence over `config/storage.yml`.

https://github.com/rails/rails/blob/25a7d2a87f7819220c9d1c26d3cbd9949257755e/activestorage/lib/active_storage/engine.rb#L147-L154

A PR to update the Active Storage guides to include this would probably be welcome.

**Comment by georgeclaghorn** [comment]
I see now that it’s mentioned in a note in the Active Storage Overview guide’s [Setup](https://guides.rubyonrails.org/active_storage_overview.html#setup) section which I missed earlier:

<img width="653" alt="Screenshot 2022-11-25 at 7 54 24 PM" src="https://user-images.githubusercontent.com/94129/204066368-5c9ccede-10e9-4769-b9a3-60ffc83d497a.png">

Maybe that should be elaborated on further.

**Comment by siaw23** [comment]
I believe this is the case the API [documentation describes](https://api.rubyonrails.org/classes/ActiveStorage/Attached/Model.html#method-i-has_one_attached) in this screenshot. The Guides, however, doesn't mention this.

<img width="747" alt="Screenshot 2022-11-26 at 18 19 55" src="https://user-images.githubusercontent.com/100293177/204101218-36b3a16a-ef9a-4c58-aa38-de57d38ef0f3.png">

**Comment by shouichi** [comment]
Thank you very much! Adding `config/storage/test.yml` worked like a charm :magic_wand: 

I'm going to open a PR to improve the guide.

**Comment by shouichi** [comment]
I opened a PR https://github.com/rails/rails/pull/46599. Can someone take a look?
