### ISSUE TITLE
Nested attributes - Is there any way to destroy record if some fields are blank????

### ISSUE THREAD

**Issue by loqimean** [rails/rails#46588]
### Steps to reproduce

```ruby
# Your reproduction script goes here
```

### Expected behavior

to use something like an option to accepts_nested_attributes_for `destroy_if` that automatically merges `_destroy: true` attribute and then destroy it WITHOUT javascript or might be some "hidden" js, like a turbo.js processing

### System configuration
**Rails version**:

**Ruby version**:

**Comment by ghiculescu** [comment]
Hi, we reserve this issue tracker for bug reports. For help using the framework a good place to ask is the [discussion forum](https://discuss.rubyonrails.org/).
