### ISSUE TITLE
SMTP SASL XOAUTH2 support

### ISSUE THREAD

**Issue by JensDebergh** [rails/rails#46591]
Hi!

I've been looking into communicating with Office365 and Gsuite like mailing providers through OAUTH tokens via rails and apparently to do so we need the SASL XOAUTH2 format.

Ruby core recently merged support for this for IMAP in master: https://github.com/ruby/net-imap/pull/63 and SMTP support is probably on it's way too: https://github.com/ruby/net-smtp/issues/46

There's a heavy push from providers towards the more secure XOAUTH2 protocol and it will probably become the defacto way of sending emails on behalf of a user through a decent consent and revoke mechanism.

Is this something the rails community would be interested in supporting? Maybe it's just as simple as providing the correct SMTP credentials with the XOAUTH2 protocol once `net-smtp` supports it.

I'd be happy to attempt to create a pull request to support this workflow. I'm working on it anyway.

Kind regards
Jens

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.
