### ISSUE TITLE
Test Parallelize Config inhibits Pry for Rails Contribution

### ISSUE THREAD

**Issue by alison-acuna** [rails/rails#46606]
### Steps to reproduce

I started investigating my first rails issue and encountered an issue running pry with actionview tests.  I successfully cloned the rails project and ran bin/test test/template/text_helper_test.rb.  I added "require pry, binding.pry" to the relevant method and reran the test.  The pry session opened but typing in the session slowed to the point of being non-functional.  I needed to close the entire terminal rather than being able to !!! out of the pry session or do any investigation.

I later learned that commenting out actionview/test/abstract_unit.rb:180-184 resolved the test parallelization that was slowing my pry session

### Expected behavior

Configuring rails for local development should be possible in a central location. The contribution guide should mention commenting out the parallelize lines for performant pry sessions.

### Actual behavior

Test parallelization slowed pry to unusably slow.

### System configuration
**Rails version**:

latest main

**Ruby version**:

2.7.6

**Comment by skipkayhil** [comment]
Hey @alison-acuna, thanks for the report!

I think as alternatives to commenting out those lines, you could run a single test with `-n test_long_test_name` or you could set `PARALLEL_WORKERS=1` so that the tests run serially.

Would you like to open a PR to expand the documentation?

**Comment by AlisonAcuna** [comment]
Hi @skipkayhil 

Thanks for the alternate suggestions.  I will open a PR to expand the documentation within the next few days.

I appreciate the support + encouragement :)

**Comment by alison-acuna** [comment]
Hi @skipkayhil

Thanks for the alternate suggestions.  I will open a PR to expand the documentation within the next few days.
I appreciate the support + encouragement :)

**Comment by alison-acuna** [comment]
Doc change PR is up: https://github.com/rails/rails/pull/46627

Thanks y'all :)
