### ISSUE TITLE
[ActiveRecord] Why does MySQL's schema dumper ask the abstract class for it's default primary key type?

### ISSUE THREAD

**Issue by shreeve** [rails/rails#46601]
https://github.com/rails/rails/blob/656118bc17791291db7c10075b489dfc6f93fce3/activerecord/lib/active_record/connection_adapters/mysql/schema_dumper.rb#L32-L38

When calling `rake db:schema:dump`, the MySQL SchemaDumper needs to know if the column currently being dumped is a default primary key for the table in question. In line 37, the code seems to know that a truly _default_ primary key type is an `integer` and not set to autoincrement.

However, in line 32, this code seems to want to defer to it's parent class (an abstract class) to let it figure out if this column is of the right type. The problem is that the parent parent class thinks a default column type should be a `bigint`, so the call to `super` on line 32 will return `false` in the common case. As a result, MySQL thinks that this primary key is a non-standard primary key and thus outputs unnecessary details in the schema dump.

I've tried to sort of monkey patch this in my own code, using something like this:

```ruby
class ActiveRecord::ConnectionAdapters::SchemaDumper
  def default_primary_key?(column)
    schema_type(column) == :integer
  end
end
```

But, I always get the following error: `TypeError: superclass mismatch for class SchemaDumper`.

Why do I get the above error? If I can run the above code, then I could write my own custom `default_primary_key?` method.

**Comment by byroot** [comment]
> Why do I get the above error?

Because your patch is loaded before the original code, so it end up like this:

```ruby
class ActiveRecord::ConnectionAdapters::SchemaDumper # < Object is implied
  # ...
end

# in lib/active_record/connection_adapters/mysql/schema_dumper.rb
class SchemaDumper < ConnectionAdapters::SchemaDumper # The superclass doesn't match.
```

A good way to make sure you don't mess this up is to do:

```ruby
ActiveRecord::ConnectionAdapters::SchemaDumper.class_eval do
  def default_primary_key?(column)
    schema_type(column) == :integer
  end
end
```

**Comment by shreeve** [comment]
Thank you for the clear answer!
