### ISSUE TITLE
Single-Table-Inheritance and Active Record Callbacks can lead to autoload errors in Rails 7.0

### ISSUE THREAD

**Issue by jrochkind** [rails/rails#46625]
I ran into an odd thing breaking trying to upgrade an app from Rails 6.1 to Rails 7.0.  I have isolated it with a reproduction -- because it involves auto-loading, and requires existing data in the database at time of autoload, it's not feasible to provide an all-in-one repro file. 

But I have a simple app that reproduces with a reproduction script, and will also provide an explanation of reproduction here. 

* Rails 7.0.4
* Ruby 3.1.2

1. You have single-table inheritance with three classes involved, say `Car` < `Motorized` < `Vehicle`. 
2. You are using the StiPreload module [recommended by Rails Guide](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#single-table-inheritance)
3. You have an ActiveRecord callback (such as `after_initialize` or `after_commit`) on the _middle_ class of the hieararchy (eg `Motorized`). 

If there are any existing rows in the DB for the leaf class (eg `Car`), then when the StiPreload module runs, it will result in a `NameError` on the class-name of the leaf class. This happens in Rails 7.0, but *does not* happen in Rails 6.1, I'd call it a regression. 

```ruby
require 'sti_preload'

class Vehicle < ApplicationRecord
  # from https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#single-table-inheritance
  include StiPreload
end

class Motorized < Vehicle
  after_initialize do
  end
end

class Car < Motorized
end

# create a Car
Car.create!(title: "Honda")
```

Now, when you boot the app subsequently, you'll get a `NameError`, `uninitialized constant Car`,  only in Rails 7, not Rails 6.1. 

Nothing needs to be in the `after_initialize`, nor does it need to execute. Just registering the block is what does it. Also reproduces with `after_commit` or `before_validation`, or presumably any other callback. 

Demonstration app, with simple repro script in README: 

https://github.com/jrochkind/rails7_sti_bug_demo

Same app in Rails 6.1 demonstrating exception is not raised: https://github.com/jrochkind/rails61_sti_bug_non_repro

Relevant stack trace from error in Rails 7:

```
/Users/jrochkind/.gem/ruby/3.1.2/gems/activesupport-7.0.4/lib/active_support/inflector/methods.rb:280:in `const_get'
/Users/jrochkind/.gem/ruby/3.1.2/gems/activesupport-7.0.4/lib/active_support/inflector/methods.rb:280:in `constantize'
/Users/jrochkind/.gem/ruby/3.1.2/gems/activesupport-7.0.4/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
/Users/jrochkind/code/rails_demos/rails7_sti_demo/lib/sti_preload.rb:33:in `block in preload_sti'
/Users/jrochkind/code/rails_demos/rails7_sti_demo/lib/sti_preload.rb:31:in `each'
/Users/jrochkind/code/rails_demos/rails7_sti_demo/lib/sti_preload.rb:31:in `preload_sti'
/Users/jrochkind/code/rails_demos/rails7_sti_demo/lib/sti_preload.rb:13:in `descendants'
/Users/jrochkind/.gem/ruby/3.1.2/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:706:in `__update_callbacks'
/Users/jrochkind/.gem/ruby/3.1.2/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:764:in `set_callback'
/Users/jrochkind/.gem/ruby/3.1.2/gems/activemodel-7.0.4/lib/active_model/callbacks.rb:151:in `block in _define_after_model_callback'
/Users/jrochkind/code/rails_demos/rails7_sti_demo/app/models/motorized.rb:2:in `<class:Motorized>'
/Users/jrochkind/code/rails_demos/rails7_sti_demo/app/models/motorized.rb:1:in `<main>'
/Users/jrochkind/.gem/ruby/3.1.2/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/jrochkind/.gem/ruby/3.1.2/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/jrochkind/.gem/ruby/3.1.2/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
/Users/jrochkind/code/rails_demos/rails7_sti_demo/app/models/car.rb:1:in `<main>'
```

**Comment by jrochkind** [comment]
Discovered others who have run into this problem here: https://stackoverflow.com/questions/70816488/sudden-uninitialized-constant-purissue-error-on-sti-preload-while-upgrading-ra

**Comment by skipkayhil** [comment]
Hey @jrochkind, thanks for opening an issue! Xavier recently added some new documentation for loading STI models  in https://github.com/rails/rails/commit/01bc3a4971068917e755bc0e15e6852cd65edfa9 which you can view on the [edge guides](https://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html#single-table-inheritance)

Does one of these methods potentially resolve your issue?

**Comment by jrochkind** [comment]
Hi thanks for the response!

Very odd, I can definitely still reproduce with my repo.  But I didn't try with `&&`, if you want to repro, please try with three separate shell commands, including the third one mentioned (which you didn't mention there). 

But either way, the problem was recognized by others, leading to those doc changes by Xavier, indeed, thanks!

I did subsequently find the issue where this was already being discussed, at #45307. The guide changes don't fully resolve things, I don't think, which I was discussing on that Issue [here](https://github.com/rails/rails/issues/45307#issuecomment-1347052403). so perhaps we should close this issue, as it duplicates that one? That one is closed however, so I am not sure.

**Comment by skipkayhil** [comment]
> Very odd, I can definitely still reproduce with my repo. But I didn't try with `&&`, if you want to repro, please try with three separate shell commands, including the third one mentioned in README (which you didn't mention here as including?).

🤦‍♂️ I'm not sure what I was doing before but I can definitely reproduce now. It looks like the same issue described in #45307 as you mention.

I'm also able to reproduce the second issue you mention (Option 4 of new docs prevent successfully running `bin/rails db:create`). With your `rails7_sti...` app I applied this diff:

```diff
diff --git a/app/models/vehicle.rb b/app/models/vehicle.rb
index 5f3c01e..ac2c747 100644
--- a/app/models/vehicle.rb
+++ b/app/models/vehicle.rb
@@ -1,6 +1,2 @@
-require 'sti_preload'
-
 class Vehicle < ApplicationRecord
-  # from https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#single-table-inheritance
-  include StiPreload
 end
diff --git a/config/initializers/preload_stis.rb b/config/initializers/preload_stis.rb
new file mode 100644
index 0000000..03e91d3
--- /dev/null
+++ b/config/initializers/preload_stis.rb
@@ -0,0 +1,8 @@
+# frozen_string_literal: true
+
+unless Rails.application.config.eager_load
+  Rails.application.config.to_prepare do
+    types = Vehicle.unscoped.select(:type).distinct.pluck(:type)
+    types.compact.each(&:constantize)
+  end
+end
```

and running `bin/rails db:create` results in:

```
rails aborted!
ActiveRecord::StatementInvalid: Could not find table 'vehicles'
/home/hartley/src/github.com/jrochkind/rails7_sti_bug_demo/config/initializers/preload_stis.rb:5:in `block in <main>'
/home/hartley/src/github.com/jrochkind/rails7_sti_bug_demo/config/environment.rb:5:in `<main>'
Tasks: TOP => db:create => db:load_config => environment
(See full trace by running task with --trace)
```

Maybe we should suggest adding some additional checks?
```diff
diff --git a/config/initializers/preload_stis.rb b/config/initializers/preload_stis.rb
index 03e91d3..0ad9c4b 100644
--- a/config/initializers/preload_stis.rb
+++ b/config/initializers/preload_stis.rb
@@ -2,7 +2,10 @@

 unless Rails.application.config.eager_load
   Rails.application.config.to_prepare do
+    next unless Vehicle.table_exists?
+
     types = Vehicle.unscoped.select(:type).distinct.pluck(:type)
     types.compact.each(&:constantize)
+  rescue ActiveRecord::NoDatabaseError
   end
 end
 ```

cc @fxn if that sounds like a good idea I'll open a PR
