### ISSUE TITLE
ActionView tag helpers only output html with the last child node when called in ruby

### ISSUE THREAD

**Issue by schpet** [rails/rails#46667]
### Steps to reproduce

in ruby (not erb!) use action view tag helpers to build up a tree, e.g.

```rb
module ApplicationHelper
  def example_list
    tag.ul {
      tag.li { "i am never seen! it would be better if i was!" }
      tag.li { "i get printed!" }
    }
  end
end
```

what happens is that only the last item in the list is printed:

```html
<ul><li>i get printed!</li></ul>
```

i don't know if this is necessarily a bug, or if it's simply expected that tag helpers are used in erb where this is not a problem.

why not use erb? i find the tooling, like standardrb and [rubyfmt](https://github.com/fables-tales/rubyfmt) are a really great at formatting and doing static checks on ruby code and it's harder to write erb without a good formatter.

view component [supports inline rendering](https://viewcomponent.org/guide/templates.html#inline), so if this was supported it would allow you to avoid erb in a lot of cases.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source("https://rubygems.org")
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem("rails", github: "rails/rails", branch: "main")
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"
require "action_view"

class BugTest < Minitest::Test
  include ActionView::Context
  include ActionView::Helpers::TagHelper

  def test_one_node
    result = tag.ul { tag.li { "hello" } }

    # this test passes ok!
    assert_equal(result, "<ul><li>hello</li></ul>")
  end

  def test_multiple_nodes
    result = tag.ul {
      tag.li { "first" }
      tag.li { "second" }
    }

    # this fails! output is actually <ul><li>second</li></ul>
    assert_equal(result, "<ul><li>first</li><li>second</li></ul>")
  end
end
```

### Expected behavior

you should be able to build up a tree with multiple child nodes in ruby using the action view TagHelper apis.

### Actual behavior

only the last child node is present in the returned html.

### System configuration
**Rails version**:
rails 7.1.0.alpha
actionview 7.1.0.alpha

**Ruby version**:
3.1.0

**Comment by dmcge** [comment]
I _think_ this is expected. These methods just return strings, they don’t put their output in a buffer or anything. You can use `safe_join`, though:

```ruby
safe_join [
  tag.li { "I am now seen!" },
  tag.li { "And so am I" }
] 
```

**Comment by schpet** [comment]
@dmcge oh awesome, yeah safe join does work there. i am curious if an api like this would be welcome in rails:

```rb
    tag.ul {
      tag.li { "first" }
      tag.li { "second" }
    }
```

i would certainly prefer that over `safe_join`

**Comment by skipkayhil** [comment]
> ```ruby
> tag.ul {
>     tag.li { "first" }
>     tag.li { "second" }
> }
> ```

Looks pretty similar to https://www.phlex.fun/, you should check it out!

Since this is more a feature request than a bug, I'm going to close this as we reserve the issue tracker for bugs only.

**Comment by naofumi** [comment]
@schpet 
I am currently considering a syntax that would remove the need to explicitly use `safe_join`.

I would highly appreciate it if you could take a look. https://dev.to/naofumik/rails-view-helpers-for-components-481c
