### ISSUE TITLE
[Feature Request] Add `UNION` to ActiveRecord

### ISSUE THREAD

**Issue by Tao-Galasse** [rails/rails#46675]
Hello Rails team! 👋 

I did some research about it, and it seems like the SQL "UNION" operator still does not exist in Active Record. It looks like it is present in Arel, but it is a private API from rails and using it seems to be a bad practice, and a bad rails-developer experience.

I have been able to work around it by using something like this : `ActiveRecord::Base.connection.select_values("#{sub_query1.to_sql} UNION #{sub_query2.to_sql}")`, but it also seems kinda strange to use it this way.

It would probably be possible to add something like `sub_query1.union(sub_query2)` to this amazing ORM, don't you think ? 😄 

Thank you all for your amazing work! 💪 ❤️

**Comment by ghiculescu** [comment]
Thanks for the feedback, but we reserve this issue tracker for bugs. If you would like to make a PR that would be a great way to get the ball rolling on this. Alternatively you can discuss on the [mailing list or Discord](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark). Thanks!
