### ISSUE TITLE
Changes in behaviour with `#dup` and `#concat`

### ISSUE THREAD

**Issue by adrianna-chang-shopify** [rails/rails#46685]
👋 Hi folks! 

This is not necessarily a bug, but a change in behaviour introduced by https://github.com/rails/rails/commit/2db098c177d51f5bd6ecad57a545da5a5e0644c0 that is impacting Shopify's Core monolith.

Some background: There's a pattern being used in a couple places in our Rails monolith where associations are added to an already-persisted model without making changes to the database. This is so that complex calculations involving orders, sales taxes, etc. can be performed without persisting those associations to the database.

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", ref: "c6b227b95b631ead7ffd5c8984b16b0fbe5b3ca4" # Commit before Alex's changes
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create
    post.comments << Comment.new

    assert_equal 1, post.comments.count

    # Add associations to already-persisted post without making changes to the database
    another_post = post.dup
    another_post.id = post.id

    assert_equal 1, another_post.comments.size

    another_post.comments << Comment.new
    assert_equal 2, another_post.comments.size
  end
end
```
(Test passes)

When run with `  gem "rails", github: "rails/rails", branch: "main"`:
```ruby
Failure:
BugTest#test_association_stuff [scripts/46392_strict_loading_has_many.rb:55]:
Expected: 2
  Actual: 1
````

### Expected behavior
As shown in the script, this pattern of duping an Active Record, assigning the id, and then adding records to the collection **previously resulted in the persisted record's collection being preserved on the duped record**.

### Actual behavior
As a side effect of the changes made in https://github.com/rails/rails/commit/2db098c177d51f5bd6ecad57a545da5a5e0644c0, when we add (`<<`) `records` to the collection of a duped active record, we now lose all of the records that were associated with the original record, despite the FKs of those records pointing to the duped record's PK.

`#concat` previously called [`#load_target`](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/associations/collection_association.rb#L262-L269), which would call `#find_target` and [load the associated records based on the owner record's PK](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/associations/association.rb#L232-L239).

Now, based on the [documentation](https://github.com/rails/rails/blob/83217025a171593547d1268651b446d3533e2019/activerecord/lib/active_record/core.rb#L573-L578) for dup:
> Duped objects have no id assigned and are treated as new records. Note that this is a “shallow” copy as it copies the object's attributes only, not its associations. 

It seems to me that, even though copying the id to the duped record was a "hack" that previously worked as expected, the documentation makes it clear that it's not expected that those associations would be copied over. Duping the associations makes the tests pass:
```ruby
    # Add associations to already-persisted post without making changes to the database
    another_post = post.dup
    another_post.comments = post.comments.dup
```
So this is perhaps the correct fix for us at Shopify 😄 That said, it _is_ a change in behaviour that we can't rely on the duped object having the correct PK to have it's records loaded appropriately, so thought I'd raise this.

### System configuration
**Rails version**:
main (as of 2db098c177d51f5bd6ecad57a545da5a5e0644c0)

**Ruby version**:
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

cc @eileencodes @ghiculescu @richardboehme

**Comment by ghiculescu** [comment]
I'm not going to be able to look closely into this until some time next week, but I think we should revert https://github.com/rails/rails/pull/46613. It caused this error and it doesn't seem like it properly fixed [the initial issue](https://github.com/rails/rails/issues/46392#issuecomment-1332200573) either.

**Comment by ghiculescu** [comment]
> even though copying the id to the duped record was a "hack" that previously worked as expected, the documentation makes it clear that it's not expected that those associations would be copied over.

> So this is perhaps the correct fix for us at Shopify 😄

I do agree with this though!
