### ISSUE TITLE
is there any possibility that implementing find! method?

### ISSUE THREAD

**Issue by akkt222** [rails/rails#46686]
Hi team
I have been using Rails for a couple of years and was wondering why there is no `find!` on ApplicationRecord.
It seems a little awkward to me that `find` raises an error while there is no `find!` method existed.
Other basic AR methods have their corresponding method such as find_by/find_by! or save/save!, update/update!, destroy/destroy!.
it is understandable why there is no `new!` method when it doesn't access a DB.

Sorry to annoy you with my issue, but I and my friends discussed it, but we couldn't get concluded on this issue.

**Comment by Buzzkill-McSquare** [comment]
I think @akkt222 is pointing out that the `find` method doesn't follow the conventions that the other AR methods establish. I agree that it's weird, but I'm sure that a lot of people rely on the existing behavior. Changing it seems like an unnecessary risk.

**Comment by akkt222** [comment]
Thanks for the support!

>  I'm sure that a lot of people rely on the existing behaviour. 

Yes, that sounds a hundred percent truthy. I'm not confident about this, but if many people think the same way as mine, my suggestion is:

1. implementing `find!` method which works the same as `find` today
2. changing the behaviour of `find` to returning nil in future versions.

I understand it is confusing, so maybe just implementing `find!` method is satisfying enough to me. it may helps to eliminate `find_by_id!(id)` and` find_by!(id: id)` from my codebases.

**Comment by eileencodes** [comment]
Hi @robzolkos thanks for the suggestion. I don't think adding `find!` will have a net-positive impact on applications and making this change would introduce complexity we're not willing to take on. I'm going to close this since we don't have plans to implement this change.
