### ISSUE TITLE
Associations comming nil in before_save if we update the corresponding associated column to nil

### ISSUE THREAD

**Issue by physics121** [rails/rails#46687]
### System configuration
**Rails version**:7.0.4

**Ruby version**:3.0.4

### Steps to reproduce
Consider two models: User(id,client_id),Client(id) with one to one relation
`class User < ActiveRecord::Base`
`belongs_to :client`
`before_save :before_saving`
   `def before_saving`
    `p "client_id:::::::::#{self.client.id}"`
    `end`
`end`

`class Client <  ActiveRecord::Base`
`has_one :user`
`end`
now consider a user and client entry user_test=(id: 1,client_id: 3) client_test=(id: 3)
now i execute the following code
`user_test.update(client_id: nil)`

### Expected behavior
the print statement should print "client_id:::::::::3"
#this is what happens in rails 6.0.3

### Actual behavior
the code throws error in before_saving
`undefined method id for nil class`
The problem is its not picking up the association in before_save ,but when i worked on rails version 6.0.3 this used to give old association in before_save before it sets to nil.but now in rails 7.0.4 it is not picking up.i read all patchnotes properly for 6.1 release and 7.0 release and there is no specification for this change.Thats why i think this is a bug.
Please Tell otherwise if i am missing some change in these versions or there is some miss in the documentation.

**Comment by physics121** [comment]
@georgeclaghorn can you confirm is this issue related to this pr https://github.com/rails/rails/pull/42751 ?

**Comment by lukesarnacki** [comment]
@physics121 I don't have much context here but I don't think it is a bug. 

This behavior is an implication of the changes in this commit https://github.com/rails/rails/commit/9c8fab96bead193620bdb8a77bf308fc05c20e51 and I think it is intentional. 

@composerinteralia could you take a look?

**Comment by ghiculescu** [comment]
This seems intentional. It would be good to get an executable test case (https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) so that we can verify the behaviour. Then we can also verify if it has changed between versions.
