### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by JustD1mas** [rails/rails#46682]
### Expected behavior
Ruby on rails should install

### Actual behavior
~$ sudo gem install rails
Building native extensions. This could take a while...
ERROR:  Error installing rails:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.7.0/gems/websocket-driver-0.7.5/ext/websocket-driver
/usr/bin/ruby2.7 -I /usr/lib/ruby/vendor_ruby -r ./siteconf20221209-5384-12dp39h.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

### System configuration
**Rails version**:
{Error when install}

**Ruby version**:
~$ ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]

**Comment by yaodong** [comment]
This error message indicates that the `ruby-dev` package is not installed, which is required for building native extensions.

**Comment by skipkayhil** [comment]
> This error message indicates that the `ruby-dev` package is not installed, which is required for building native extensions.

As mentioned above, you most likely have a missing package.

Since this is not an issue with Rails, I'm going to close this issue because we reserve the issue tracker for Rails bugs only.
