### ISSUE TITLE
Docs: Automatic Role Switching has no information on what is required for custom implementation

### ISSUE THREAD

**Issue by SampsonCrowley** [rails/rails#46693]
### Steps to reproduce

[When Reading the Guides for Multi DB](https://guides.rubyonrails.org/active_record_multiple_databases.html#activating-automatic-role-switching) new users are told: 
> The setup in Rails allows you to easily change how the switching is done and what parameters it's based on

However the sample code given is missing a basic implementation for what methods will be called and what is required. There is Very little information on what DIYing those classes entails available.

### Expected behavior

If we're going to say "it's easy to DIY", the docs should at least have a minimum example of the methods that are required to roll your own, so users know what they expect to get called on.

If we'd prefer not to clog up the docs with additional sample code should we maybe link to the API docs? That way users who are new to rails (but still proficient enough to understand sharding or DB switching) would have a direct path to the to more information

### Actual behavior

Instead we just give an empty class, which if you think about it may as well be omitted if that's all we're going to include. it's just extra fluff with the only benefit being that you're aware that the class isn't expected to be inherited from `ActiveRecord::Middleware::DatabaseSelector::Resolver::Session`

```ruby
class MyCookieResolver
  # code for your cookie class
end
```

### System configuration
**Rails version**: 7.0.4

**Ruby version**: any

**Comment by ghiculescu** [comment]
> If we'd prefer not to clog up the docs with additional sample code should we maybe link to the API docs?

Yeah, this is a good idea. Want to make a PR?

Another idea would be to have a very simple implementation of `MyCookieResolver` (or even just the required methods to be implemented) included in the guide.

**Comment by niudage** [comment]
good thankyou

**Comment by eileencodes** [comment]
Closed by #46835
