### ISSUE TITLE
Error cucumber features testing ruby 2.6.6 and rails 4.2.10

### ISSUE THREAD

**Issue by arshekas** [rails/rails#46692]
Hello everyone, 
Hope you are all good!

We added this and our RSpec tests seems to run fine which is good

```
if RUBY_VERSION>='2.6.0'
  if Rails.version < '5'
    class ActionController::TestResponse < ActionDispatch::TestResponse
      def recycle!
        # hack to avoid MonitorMixin double-initialize error:
        @mon_mutex_owner_object_id = nil
        @mon_mutex = nil
        initialize
      end
    end
  else
    puts "Monkeypatch for ActionController::TestResponse no longer needed"
  end
end
```

However, we are experiencing the error below while running cucumber feature tests. 

```
Feature: Address
  A user should be able to manage addresses

  Background:            # features/admin/address.feature:4
    Given I am logged in # features/step_definitions/session_steps.rb:1
      undefined method `<<' for #<Hash:0x00007f7c7dc4b908>
      Did you mean?  < (NoMethodError)
      ./features/step_definitions/session_steps.rb:4:in `/^I am logged in$/'
      features/admin/address.feature:5:in `Given I am logged in'
      /Users/arsh/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/protocol.rb:264:in `writing'
      /Users/arsh/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/protocol.rb:247:in `write'
      /Users/arsh/.rbenv/versions/2.6.6/lib/ruby/2.6.0/net/http/generic_request.rb:335:in `write_header'
 ```
session_steps.rb
```
Given (/^I am logged in$/) do
  user = FactoryGirl.create(:user)

  visit '/session/new'

  fill_in 'Email', with: user.email
  fill_in 'Password', with: 'password'

  click_button('Submit')
end
```
address.feature
```
Feature: Address
  A user should be able to manage addresses

  Background:
    Given I am logged in
   ```
   
Here are the tests gems and versions we are using
     
    ruby '2.6.6'
    'rails', '4.2.10
    
    gem 'rspec-rails', '~> 3.4.2'
    gem 'guard-rspec'
    gem 'factory_girl', '4.5.0'
    gem 'capybara', '2.5.0'
    gem 'capybara-webkit'
    gem 'selenium-webdriver', '2.53.0'
    gem 'chromedriver-helper'
    gem 'cucumber-rails', '1.4.3', require: false
    gem 'rspec_junit_formatter'
    gem 'database_cleaner', '1.5.1'
     
   It seems like every test @javascript tag is failing while doing create or destroy.
     
  We tried updating gems versions related to the cucumber and changing some configurations, but we have had no luck. 
  Any help would be appreciated!
     
  Thanks

**Comment by eileencodes** [comment]
Hi @arshekas - thanks for the report.

Rails 4.2 has been unsupported since 2017 and we have no reports of similar errors in recent versions. I don't see Rails in the provided backtrace so I don't think this is a bug in the Rails framework. If you upgrade to 7.0 and are still having issues, please comment or open a new issue with reproduction steps that aren't specific to your application.

**Comment by arshekas** [comment]
Hi @eileencodes, thank for your response!

We tried below, 

We have updated our rails app from rails 4.2.6 to rails 5.2.5 and ruby version from 2.3.0 to 2.6.6, we have changed the code according to here [https://gist.github.com/anklos/eb0088e26223c92a034cd1ea36fcee2c](https://gist.github.com/anklos/eb0088e26223c92a034cd1ea36fcee2c). However, when we run the application we are getting this error somewhere from application.rb 

code from application.rb where erroring out

```
require File.expand_path('../boot', __FILE__)

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups). **THIS LINE GIVING ERROR**
```

Error
```
`block in <module:ControllerHelper>': undefined method `alias_method_chain' for ActionController::Base:Class (NoMethodError)
Did you mean?  alias_method
```

Any help would be appreciated!

Thanks

**Comment by eileencodes** [comment]
Hey @arshekas sorry you're still having trouble. `alias_method_chain` was removed in Rails 5 / Ruby 2.6. You'll need to find the [code calling that and update it to using prepend](https://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/).

We reserve the issues tracker for bugs in the framework and don't have the bandwidth to do application support. Unless you can determine there is a bug in the current version of Rails (7.0), please use Stackoverflow or the [forum](https://discuss.rubyonrails.org/) to get help with debugging issues during upgrading. Thanks for understanding.

**Comment by arshekas** [comment]
Hi @eileencodes,
We looked at our entire code repo and we aren't using alias_chain_method anywhere. Also, couldn't able to find any of the gems causing that.

**Comment by eileencodes** [comment]
The backtrace will tell you where it's originating from. `alias_method_chain` is not present in Rails 5.2.5 as it was removed from the framework code in 5.0.
