### ISSUE TITLE
has_one association getting deleted on using create_association & validation fails

### ISSUE THREAD

**Issue by akshaymohite** [rails/rails#46737]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 7.0.4"
  gem "byebug"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
  end

  create_table :accounts, force: true do |t|
    t.integer :user_id
  end
end

class User < ActiveRecord::Base
  has_one :account, dependent: :destroy
end

class Account < ActiveRecord::Base
  belongs_to :user

  validates_uniqueness_of :user_id
end

class BugTest < Minitest::Test
  def test_association_stuff
    user = User.create!
    assert_equal 1, User.count

    user.create_account!
    assert_equal 1, Account.count

    begin
      user.create_account!
    rescue ActiveRecord::RecordInvalid => e
      puts "Expected error raised because uniqueness violated - #{e.message}"
    end

    assert_equal 1, Account.count
  end
end
```

### Expected behavior

The existing has_one relation from the database should not get deleted. The transaction should be rolled back.

### Actual behavior

```ruby
F

Failure:
BugTest#test_association_stuff [bug.rb:56]:
Expected: 1
  Actual: 0
```

### System configuration

**Rails version**: `7.0.4`

**Ruby version**:  `3.1.2`

### More info

Tried debugging this and seems the associated record is getting deleted because of `dependent: :destroy` on `User` model. [This method](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/associations/has_one_association.rb#L64) is being called which deletes this associated record. It seems intentional deletion but I am not sure if it should be the expected behavior in this case. Let me know if I am missing any context here.

**Comment by lazaronixon** [comment]
It should be fixed on master….

**Comment by lazaronixon** [comment]
Hey... your test is passing on the main branch.
`gem "rails", github: "rails/rails", branch: "main"`.

**Comment by lazaronixon** [comment]
Hey @s-mustafa, your test is passing on the main branch. `gem "rails", github: "rails/rails", branch: "main"`.

**Comment by lazaronixon** [comment]
@byroot I think it can be closed.

**Comment by byroot** [comment]
Backported in 83009f94e7539c7db89f83446b1478bdaec9d1a0
