### ISSUE TITLE
Rest api documentation #documentation

### ISSUE THREAD

**Issue by G33kNoob** [rails/rails#46764]
https://guides.rubyonrails.org/api_app.html#what-is-an-api-application-questionmark

I read the API documentation but seem very confused, I hope I can see the documentation about creating simple restapi and authenticator in the doc.

**Comment by hahmed** [comment]
> This guide covers building a Rails application that serves JSON resources to an API client, including client-side frameworks.

I don't think it's a bad thing that this guide has a little bit more information about API apps. Maybe how a controller and action looks like when using API mode?

**Comment by davidomullan** [comment]
Not sure if you would prefer an in-house solution/example, but there are several good articles explaining the basics of setting up RESTful API using Rails. One example from Oliver DS on Medium.com:

Set up RESTful API
https://medium.com/@oliver.seq/creating-a-rest-api-with-rails-2a07f548e5dc
Add authenticator and password hashing
https://medium.com/@oliver.seq/authentication-in-rails-with-auth0-4cc8ead3bd78

Possible solution is to add the following note to the end of 3.1 Creating a New Application:

https://github.com/rails/rails/blob/adbb85be9ca0a876ae7b865a188c3db192732ab6/guides/source/api_app.md?plain=1#L134-L153

NOTE: It may be helpful to see an example application created from scratch. Please refer to [this article][medAPI] to create a basic API containing a list of user submitted facts. You can also check out [this article][medAUTH] about implementing authentication and password hashing.

[medAPI]: https://medium.com/@oliver.seq/creating-a-rest-api-with-rails-2a07f548e5dc
[medAUTH]: https://medium.com/@oliver.seq/authentication-in-rails-with-auth0-4cc8ead3bd78

If this is sufficient, I will happily generate a PR.

**Comment by hahmed** [comment]
I think it's better to avoid linking to another articles and writing our own example. Also, I don't think we need to add anything about authentication/securing your rails app -- that's better suited for https://guides.rubyonrails.org/security.html

**Comment by davidomullan** [comment]
Thoughts on below?

https://github.com/davidomullan/rails/blob/802f48f866ae09df1a3d42fd9e4d0ecbfb4c0cbc/guides/source/api_app.md?plain=1#L134-L260

**Comment by zzak** [comment]
@davidomullan I think it's a good start, but myself and others might have feedback, so would you be able to open a PR?

**Comment by davidomullan** [comment]
Out of curiosity, is there anyway for me to close out the change request to my most recent pull request? The only option I saw was to request a re-review from P8 (have done). Just want to make sure the PR shows up as ready for review. No rush, just want to know if I'm doing everything right. Thanks you!

**Comment by zzak** [comment]
@davidomullan Yeah, @p8 will have to update their review status. Please wait until we get around to finish the review. Thanks!
