### ISSUE TITLE
raw_post being empty for "Transfer-Encoding: chunked"

### ISSUE THREAD

**Issue by kazu9su** [rails/rails#46784]
`raw_post` of chunked request is empty. I would like to open a feature request to handle chunked request by action pack.
I found the same issue was raised by @hahmed and he sent [the PR to fix it](https://github.com/rails/rails/pull/37423) but was closed at that time.
The reason why the PR closed is the problem was solved with Puma by adding CONTENT_LENGTH request header at the Puma layer by [this PR](https://github.com/puma/puma/pull/2287).
However, the same problem still happens with unicorn, thin and webrick at least.
It is helpful to us application developers if this problem would be taken care by rails so that we won't have to check neither the request is chunked nor which rack http server is used.

### Steps to reproduce
I prepared environments to reproduce the problem via docker. Please download it and follow the instruction of README.
https://github.com/kazu9su/rails-experiment

### Expected behavior
If the chunked request is sent to the rails server, application can read the `raw_post` with any rack http server.

### Actual behavior
We can access to the request body with `raw_post` with only the rack http server which buffers the request body upfront like Puma.

* Reproduced the problem with...
  * Puma 4.3.3(The version before [Content-Length change](https://github.com/puma/puma/pull/2287) was merged)
  * Unicorn 6.1.0
  * Thin 1.8.1
  * Webrick 1.7.0

**Comment by hahmed** [comment]
Hey @kazu9su, thanks for reporting this issue. I'm going to take a look at this some time this week, apologies its taken a while to get around to it!

**Comment by hahmed** [comment]
@kazu9su a fix was merged upstream, any chance you could retest?

**Comment by kazu9su** [comment]
@hahmed First of all, thank you for letting me know it and thank you all to work on this issue!

 I tested this version of rails [097ead2](https://github.com/rails/rails/commit/097ead29d93ea02ea1afdc8d34effb9fd9e496f2) with unicorn 6.1.0 app, and found out all things work well except for 'CONTENT_LENGTH' value of `request.headers`.

With Puma 5.6.5 app, I can get correct CONTENT_LENGTH value from request.headers hash like [this](https://github.com/kazu9su/rails-experiment/blob/main/railsapp_puma_5_6_5/app/controllers/webapi_controller.rb#L10)

I suppose that it would solve this problem that setting CONTENT_LENGTH at the same. How do you think?

**Comment by kazu9su** [comment]
@hahmed
I confirmed what I addressed again about `request.headers` property and I believe that rails handles them as `raw` request headers sent through the request. Given that, providing content_length or raw_post methods seems enough to satisfy what I raised as this issue, I close this.

Again, thank you for the great work!
