### ISSUE TITLE
Action Text `fill_in_rich_text_area` system test helper calls nonexistent Trix `Editor` method

### ISSUE THREAD

**Issue by georgeclaghorn** [rails/rails#46803]
#46249 updated `fill_in_rich_text_area` to call `focus` on the located `<trix-editor>` element’s `editor`, but [Trix `Editor` doesn’t have a `focus` method](https://github.com/basecamp/trix/blob/5462b1bc86796e940d2a952f513bb58d533e573a/src/trix/models/editor.js). The result is an error:

```
Failure/Error: fill_in_rich_text_area "message[content]", with: "Hello back!"
     
     Selenium::WebDriver::Error::JavascriptError:
       javascript error: this.editor.focus is not a function
         (Session info: chrome=108.0.5359.124)
```

The [`ActionText::SystemTestHelper` tests](https://github.com/rails/rails/blob/a7902034089e8b6bff747c08d93eeac4b1377032/actiontext/test/system/system_test_helper_test.rb) do not run in CI. They require a system testing setup that I never got around to adding to Rails CI. They are fairly broken at the moment. I’ll make a separate issue.

/cc @seanpdoyle @eileencodes

**Comment by seanpdoyle** [comment]
That's surprising! Thank you for catching this @georgeclaghorn, I'll investigate a resolution. Worse comes to worst, I'll open a revert PR.

**Comment by seanpdoyle** [comment]
@georgeclaghorn I've opened https://github.com/rails/rails/pull/46807.

**Comment by seanpdoyle** [comment]
@georgeclaghorn in the short term, I've opened https://github.com/rails/rails/pull/46808 to completely revert #46249.

Once we have the suite executing and passing in CI, I'll rebase https://github.com/rails/rails/pull/46807 and make sure it passes.
