### ISSUE TITLE
`ActionText::SystemTestHelper`’s tests don’t run in CI

### ISSUE THREAD

**Issue by georgeclaghorn** [rails/rails#46804]
When I added `ActionText::SystemTestHelper` and its tests, I had a to-do to add the tests to CI. I never got around to it. They need a full system testing setup with Chrome, Chromedriver, and Selenium.

Several breaking `ActionText::SystemTestHelper` changes have been submitted in recent years and some of them have been merged. See #46803.

**Comment by georgeclaghorn** [comment]
More is still needed here. See rails/buildkite-config#26.

**Comment by hahmed** [comment]
Oh my bad... I ended up linking to the other PR instead of this issue 🤦🏽. 

@eileencodes any chance I could get a review on the supplementary PR https://github.com/rails/buildkite-config/pull/26?
