### ISSUE TITLE
Parallel test databases are truncated before each run, but non-parallel test databases are not

### ISSUE THREAD

**Issue by ghiculescu** [rails/rails#46820]
### Steps to reproduce

Repro here: https://github.com/ghiculescu/parallel-tests-repro. The key bits are as follows.

In the [test helper](https://github.com/ghiculescu/parallel-tests-repro/blob/main/test/test_helper.rb):

```ruby
parallelize(workers: :number_of_processors, threshold: 2)

# Load some data in the test database before tests run.
# We don't use fixtures for this because it's a huge static dataset.
# A good example might be loading data from the countries gem or something like that.
# We don't do this in `setup` because it is slow. We want to just do it once (per database), before all tests.
10.times {|n| User.create!(name: "User #{n}") }
```

The [test](https://github.com/ghiculescu/parallel-tests-repro/blob/main/test/models/user_test.rb):

```ruby
test "static data is created in test_helper.rb" do
  assert_equal 10, User.count
end
```

This just confirms that the static data was successfully loaded and is available to the test.

### Expected behavior

I expect the test to pass if you run in singular or in parallel.

```
rails db:reset test # run tests in singular, should pass
PARALLEL_WORKERS=2 rails db:reset test # run tests in parallel, should pass
```

### Actual behavior

Running not in parallel passes.

Running in parallel fails.

```
PARALLEL_WORKERS=2 rails db:reset test
Dropped database 'db/development.sqlite3'
Dropped database 'db/test.sqlite3'
Created database 'db/development.sqlite3'
Created database 'db/test.sqlite3'
Running 1 tests in parallel using 2 processes
Run options: --seed 10094

# Running:

F

Failure:
UserTest#test_static_data_is_created_in_test_helper.rb_-_0
Expected: 10
  Actual: 0
```

It is failing because

https://github.com/rails/rails/blob/40a1f3ae24b297cddcfca06332fe113faf2ab52f/activerecord/lib/active_record/test_databases.rb#L8

calls

https://github.com/rails/rails/blob/40a1f3ae24b297cddcfca06332fe113faf2ab52f/activerecord/lib/active_record/tasks/database_tasks.rb#L389

which truncates all tables. The equivalent does not happen if you aren't running in parallel.

I tried commenting out that line, and all tests still passed, but I assumed there's a reason for it (though I can't think of one...) so wanted to make an issue for discussion first.

### System configuration
**Rails version**: `main`

**Ruby version**: 3.2

**Comment by eileencodes** [comment]
The data being inserted into the database is happening before the test databases are created. If you want to insert data into the parallel databases you need to hook into the same callback that parallel testing uses. This is documented here https://guides.rubyonrails.org/testing.html#parallel-testing-with-processes.

I think the docs could be improved, but calling a manual insert before the test databases are established will always cause the tests to fail in parallel.

**Comment by ghiculescu** [comment]
Geez, how did I miss that. This works as expected: https://github.com/ghiculescu/parallel-tests-repro/compare/use-parallel-setup

**Comment by ghiculescu** [comment]
That seems like a bug, fixtures should get loaded automatically in either setup. Could you create an issue with more derail?
