### ISSUE TITLE
Unexpected routes in console using app.

### ISSUE THREAD

**Issue by woto** [rails/rails#46822]
### Steps to reproduce
```ruby
irb(main):013:0> host = "https://host.ru:443"
=> "https://host.ru:443"

irb(main):014:0> Rails.application.routes.url_helpers.tests_url(host: host)
=> "https://host.ru/tests"

irb(main):015:0> app.tests_url(host: host)
=> "http://host.ru:443/tests"

irb(main):016:0> 
irb(main):017:0> 

irb(main):018:0> host = "https://host.ru:443/"
=> "https://host.ru:443/"

irb(main):019:0> Rails.application.routes.url_helpers.tests_url(host: host)
=> "https://host.ru/tests"

irb(main):020:0> app.tests_url(host: host)
=> "http://host.ru/tests"

```

### Expected behavior
In all cases I expect that output will be `https://host.ru/tests`

### Actual behavior
Unexpected results built with `app.` are `http://host.ru:443/tests` and `http://host.ru/tests`

### System configuration
**Rails version**:
7.0.4

**Ruby version**:
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

Cheers!

**Comment by ghiculescu** [comment]
This is the cause:

```ruby
3.1.3 :002 > app.url_options
 => {:host=>"www.example.com", :protocol=>"http"}
3.1.3 :003 > Rails.application.routes.url_helpers.url_options
 => {}
```

These get merged into what you pass to the route. So the fact you're passing in a https host is overridden by the http protocol.

**Comment by ghiculescu** [comment]
Maybe we should log a warning [here](https://github.com/rails/rails/blob/9f141a423d551f7f421f54d1372e65ef6ed1f0be/actionpack/lib/action_dispatch/http/url.rb#L146) if the `host` starts with "http://" or "https://" ?

**Comment by woto** [comment]
Yeah. I know how to avoid the problem. The most annoying part of this that I thought that this methods must give identical results. Like if agree

**Comment by zzak** [comment]
I agree this is surprising, can reproduce it simply with a newly generated application like this:

```ruby
# bin/rails c
# Loading development environment (Rails 7.1.0.alpha)
>> app.url_options
=> {:host=>"www.example.com", :protocol=>"http"}

>> app.rails_health_check_url
=> "http://www.example.com/up"

>> app.rails_health_check_url host: "https://github.com"
=> "http://github.com/up"

>> app.rails_health_check_url host: "github.com", protocol: "https"
=> "https://github.com/up"
```
