### ISSUE TITLE
Ruby 3.2.0 Compatibility?

### ISSUE THREAD

**Issue by OskarEichler** [rails/rails#46833]
Hey everyone,

Just wondering if Rails 7.0.4 is compatible with the new version of Ruby 3.2.0 which was released 2 days ago. Would be great to gain some insights here from the core maintainers, or if compatibility is planned for the upcoming release of Rails 7.1

Thanks so much!

**Comment by ghiculescu** [comment]
It should work fine. Are you having any issues?

**Comment by OskarEichler** [comment]
Haven't tested yet on our end, as we wanted confirmation first that it is compatible. Will give it a spin now.

**Comment by ghiculescu** [comment]
Cool, I will close this but feel free to reopen if you find any issues.
