### ISSUE TITLE
Migrating after a DB reset changes the active storage foreign keys in the schema from bigint to integer

### ISSUE THREAD

**Issue by gsmendoza** [rails/rails#46834]
### Steps to reproduce

1. Create a Rails 7.0.4 app.
2. Run `bin/rails active_storage:install` to generate a migration that creates the active storage tables (https://edgeguides.rubyonrails.org/active_storage_overview.html#setup).
3. Run `rails db:migrate` to migrate the db and generate the DB schema.
3. Run `rails db:reset`.
4. Run `rails db:migrate` again.

### Expected behavior

I should see no changes to the app's database schema.

### Actual behavior

Running `rails db:migrate` after the database reset changes the `schema.rb`:

```diff
$ git diff HEAD
diff --git a/db/schema.rb b/db/schema.rb
index 72828ed..07d88a6 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -33,8 +33,8 @@ ActiveRecord::Schema[7.0].define(version: 2022_12_15_070245) do
   create_table "active_storage_attachments", force: :cascade do |t|
     t.string "name", null: false
     t.string "record_type", null: false
-    t.bigint "record_id", null: false
-    t.bigint "blob_id", null: false
+    t.integer "record_id", null: false
+    t.integer "blob_id", null: false
     t.datetime "created_at", null: false
     t.index ["blob_id"], name: "index_active_storage_attachments_on_blob_id"
     t.index ["record_type", "record_id", "name", "blob_id"], name: "index_active_storage_attachments_uniqueness", unique: true
@@ -53,7 +53,7 @@ ActiveRecord::Schema[7.0].define(version: 2022_12_15_070245) do
   end

   create_table "active_storage_variant_records", force: :cascade do |t|
-    t.bigint "blob_id", null: false
+    t.integer "blob_id", null: false
     t.string "variation_digest", null: false
     t.index ["blob_id", "variation_digest"], name: "index_active_storage_variant_records_uniqueness", unique: true
   end
```

### System configuration

**Rails version**: 7.0.4
**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
**Database**: sqlite3 (3.37.2)
**OS**: `Pop!_OS 22.04 LTS`

### Background

I first reported this issue at https://github.com/solidusio/solidus/issues/4787.

**Comment by duc-hoang-kim** [comment]
hi @gsmendoza , with rails 7 and sqlite3. The migration will produce primary_keys in integer type. reference [here](https://github.com/rails/rails/blob/v7.0.3/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L65)
The problem here is with the former schema file. Did you do step 2 with the same version of rails and also with sqlite3?

**Comment by fatkodima** [comment]
Thanks for the report! I identified what the problem is, working on a PR.

**Comment by gsmendoza** [comment]
> hi @gsmendoza , with rails 7 and sqlite3. The migration will produce primary_keys in integer type. reference [here](https://github.com/rails/rails/blob/v7.0.3/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L65) The problem here is with the former schema file. Did you do step 2 with the same version of rails and also with sqlite3?

@duc-hoang-kim Yes, I didn't change the Rails and sqlite3 version throughout the test.

**Comment by gsmendoza** [comment]
Thanks @fatkodima !
