### ISSUE TITLE
Rails.logger.level for production in docs is wrong

### ISSUE THREAD

**Issue by woto** [rails/rails#46841]
Hi, was surprised by this line which has already existed for 8 years. Am I doing something wrong or docs are lying?
The default log level for `production` is `info`. For `development` and `test` is `debug`. You can check this yourself.

https://edgeguides.rubyonrails.org/debugging_rails_applications.html#log-levels
https://github.com/rails/rails/blame/afbde03801104e4d56dac736043f47f141a91d3e/guides/source/debugging_rails_applications.md?plain=1#L146

```ruby
(base) ➜  foo git:(main) ✗ RAILS_ENV=production ./bin/rails c
Loading production environment (Rails 7.0.4)
irb(main):001:0> Rails.logger.level
=> 1
irb(main):002:0> 
(base) ➜  foo git:(main) ✗ ./bin/rails c               
Loading development environment (Rails 7.0.4)
irb(main):001:0> Rails.logger.level
=> 0
irb(main):002:0> 
(base) ➜  foo git:(main) ✗ RAILS_ENV=test ./bin/rails c      
Loading test environment (Rails 7.0.4)
irb(main):001:0> Rails.logger.level
=> 0
```

Cheers

**Comment by skipkayhil** [comment]
Hey @woto, nice find! The default in production changed in 229fd2a0, would you like to open a PR to update the docs?
