### ISSUE TITLE
Release a new patch version after self-XSS?

### ISSUE THREAD

**Issue by dorianmariefr** [rails/rails#46853]
### Steps to reproduce

- have a rails app
- push to github

### Expected behavior

no warnings

### Actual behavior

remote: GitHub found 1 vulnerability on organization/project's default branch (1 low). To find out more, visit:
remote:      https://github.com/organization/project/security/dependabot/50

which links to this commit https://github.com/rails/rails/commit/be177e4566747b73ff63fd5f529fab564e475ed4

### System configuration
**Rails version**: Rails 7.0.4

**Ruby version**: ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [arm64-darwin22]

**Comment by eileencodes** [comment]
Hi @dorianmariefr thanks for opening an issue! Since this was determined to not be critical (which is also why the PR was done in public instead of in private) this doesn't warrant a security release. It will be available in the next version of Rails (7.0.5).
