### ISSUE TITLE
ActiveSupport::Subscriber is not working without eager_load

### ISSUE THREAD

**Issue by nirname** [rails/rails#46852]
### Steps to reproduce

In `config/development.rb`:

```ruby
config.eager_load = false
config.active_support.deprecation = :notify
```

Create `app/subscribers/my_subscriber.rb` with the following content:

```ruby
class MySubscriber < ActiveSupport::Subscriber
  attach_to :rails

  # This is simply example, do whatever you need
  def deprecation(event)
    raise 'event.payload[:message]
    
    # or something like
    # Honeybadger.notify(
    #   error_class: ActiveSupport::Deprecation,
    #   error_message: event.payload[:message],
    #   backtrace: event.payload[:callstack]
    # )
  end
end
```

Go to `rails c` and execute:

```ruby
ActiveSupport::Deprecation.warn('test warn')
```

Paste your executable test case created from one of the scripts found [here](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case)

```ruby
# Your reproduction script goes here
```

### Expected behavior

Raised error:

```
app/subscribers/deprecation_subscriber.rb:5:in `deprecation': "DEPRECATION WARNING: test (called from <main> at bin/rails:4)" (RuntimeError)
```

### Actual behavior

You see this message:

```ruby
"DEPRECATION WARNING: test (called from <main> at bin/rails:4)"
```

### System configuration

**Rails version**:

rails (7.0.4)

**Ruby version**:

ruby '3.0.2'

**Comment by fatkodima** [comment]
This is an expected behavior - in development, rails do lazy load - loads constants only when they are referenced.
You need to put your subscriber into an initializer, or `require` it from some initializer or something like that.

**Comment by skipkayhil** [comment]
> You need to put your subscriber into an initializer, or `require` it from some initializer or something like that.

To add to this, if you keep it inside `app/subscribers` you'll want to configure Zeitwerk like this:
```ruby
# config/initializers/subscribers.rb
subscribers_path = Rails.root.join("app/subscribers")

unless Rails.application.config.eager_load
  Rails.application.config.to_prepare do
    Rails.autoloaders.main.eager_load_dir(subscribers_path)
  end
end
```

or if you simply want to `require` the file then you should move it out of `app` to `lib`.

I'm going to close this issue as we reserve the issue tracker for bugs only, however feel free to reply if the above isn't working for you!
