### ISSUE TITLE
number_with_precision() helper failing to round float

### ISSUE THREAD

**Issue by dachdecker** [rails/rails#46854]
The below snippit works fine in rails 5.2.3 but fails under rails 6.1. Placing this snippit in any view of a rails app:

```
			<% thing = 50.09 %>
			<% puts thing %>
			<% puts thing.respond_to?(:to_i) %>
			<% puts thing.class %>	
			<% puts BigDecimal(thing.to_s).round(1) %>
			<% puts number_with_precision(thing, precision: 1) %> #works in rails 5.2.3, fails in 6.1
```

### Expected behavior
Should successfully return 50.1 (as does in rails 5.2.3):
```
Rendering main/index.html.erb within layouts/application
50.09
true
Float
50.1
50.1
```

### Actual behavior
Fails with type error: no implicit conversion of String into Integer
![image](https://user-images.githubusercontent.com/13346757/210013824-76f110f8-d74a-4640-bf04-efe06cf3f35a.png)

### System configuration
**Rails version**: 6.1.0

**Ruby version**: 2.7.7

**Comment by fatkodima** [comment]
Rails 6 is not supported for bug fixes (see https://guides.rubyonrails.org/maintenance_policy.html). Can you verify the issue still persists for the latest changes from the rails `main` branch? 
If so, can you create a sample app, demonstrating the issue, and share with us?

**Comment by ghiculescu** [comment]
I can't replicate the issue with a specified `precision`, but I can without one, if there is an i18n key with a string value.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activesupport", github: "rails/rails", branch: "main"
  gem "actionview", github: "rails/rails", branch: "main"
end

require "active_support"
require "action_view"
require "minitest/autorun"

class BugTest < Minitest::Test
  include ActionView::Helpers::NumberHelper

  def test_stuff
    I18n.eager_load!
    I18n.backend.store_translations(:en, number: { format: { precision: "4" } })

    assert_equal "50.1", number_with_precision(50.09) # TypeError: no implicit conversion of String into Integer
  end
end
```

Is it possible this is the case here?

**Comment by ghiculescu** [comment]
Actually this looks related. It has the same backtrace https://github.com/rails/rails/issues/41459
