### ISSUE TITLE
Move `ActiveRecord::Type::Boolean` to active_support and forward

### ISSUE THREAD

**Issue by rickmark** [rails/rails#46870]
### Steps to reproduce
In order to use basic boolean-like parsing you must import ActiveRecord, when this is a concern that is easily handled in ActiveSupport

```ruby

require 'active_record'

ActiveRecord::Type::Boolean.new.cast('false')
```

We can better make use of this by making this class part of active_support, and adding a core_ext to various types to support `to_b` whereby we get a boolean value.  This corrects the issue whereby "false" is truthy in ruby due to being a string with value, which is not intuitive to many use cases.

### Expected behavior
active_support should support basic boolean fuzzy handling

### Actual behavior
Overly explicit calls with active_record are required for this case

### System configuration
**Rails version**:

**Ruby version**:

**Comment by nvasilevski** [comment]
To be specific, `Boolean` type is part of `active_model` and `ActiveRecord::Type::Boolean` is just an alias https://github.com/rails/rails/blob/d1461cdb61c9b8d6ed046a54b20df311903fdc0a/activerecord/lib/active_record/type.rb#L61

>active_support should support basic boolean fuzzy handling

I agree with the intention of this proposal but I was thinking that Active Support will benefit from having a boolean parser class which can be reused by the `Boolean` attribute type. So I don't think that moving the attribute itself to Active Support and using it just to parse boolean is a reasonable decision design-wise.

**Comment by byroot** [comment]
This was rejected many times, see https://github.com/rails/rails/pull/9667 for instance.
