### ISSUE TITLE
Possible deadlock when accessing Mail constants in different threads

### ISSUE THREAD

**Issue by alanhala** [rails/rails#46876]
### Steps to reproduce
I can't reproduce it in a non-production environment. I will try to explain the issue.

I'm running a Rails application. I'm using a custom background job processor built on top of ActiveJob. It uses Google Cloud PubSub as backend. The background job processor calls `Rails.application.eager_load!` manually before starting. After that a bunch of threads are spawned for listening to the topics and process messages/jobs.

After every deploy there is one instance in which jobs get stuck and don't finish. I've managed to add some debugging to the threads to print their backtrace and I found some pattern. They are stuck in one of these backtraces:

1)
```
Thread: #<Thread:0x00007f700bcf2330@worker-2 /usr/src/app/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep_forever> #214:
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/fields/content_type_field.rb:39:in `element'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/fields/content_type_field.rb:33:in `parse'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/fields/content_type_field.rb:25:in `initialize'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/field.rb:277:in `new'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/field.rb:277:in `new_field'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/field.rb:266:in `create_field'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/field.rb:187:in `field'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/field.rb:239:in `method_missing'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/header.rb:186:in `[]='
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/message.rb:1327:in `[]='
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/message.rb:2118:in `block in init_with_hash'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/message.rb:2111:in `each_pair'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/message.rb:2111:in `init_with_hash'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/message.rb:135:in `initialize'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/base.rb:1043:in `new'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/base.rb:1043:in `insert_part'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/base.rb:1037:in `block in create_parts_from_responses'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/base.rb:1037:in `each'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/base.rb:1037:in `create_parts_from_responses'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/base.rb:878:in `mail'
```

2)
```
Thread: #<Thread:0x00007f700ae6e098@worker-8 /usr/src/app/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep_forever> #170:
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/base.rb:596:in `email_address_with_name'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/base.rb:674:in `email_address_with_name'
```
3)
```
Thread: #<Thread:0x00007f700bd0ca00@worker-2 /usr/src/app/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:332 sleep_forever> #156:
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:6:in `<main>'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/elements/address.rb:3:in `<main>'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/base.rb:596:in `email_address_with_name'
/usr/src/app/vendor/bundle/ruby/3.1.0/gems/actionmailer-7.0.4/lib/action_mailer/base.rb:674:in `email_address_with_name'
```

There is only one Thread with the backtrace shown in 3. and that one should also belong to 2. as it is calling also the method `email_address_with_name`.

3. is stuck in the constant declaration `Mail::Parsers::AddressListsParser`, 2. is referencing at some point the same constant and 1. is referencing `Mail::Parsers::ContentTypeParser`.

Can this be some kind of deadlock when loading consants? Is there any other information that might be useful to provide or any tool I can use to dig further? I also created an issue in [zeitwerk](https://github.com/fxn/zeitwerk/issues/246) and I was told to create the issue in Rails as it's not likely to be related to it.

### Expected behavior
Jobs should not get stuck and they should process the task.

### Actual behavior
Jobs get stuck and don't process any task.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**Comment by bensheldon** [comment]
@alanhala that is frustrating! I think you're running into an issue in `Mail`... sorry to send you to yet another project! 😄 

https://github.com/mikel/mail/issues/912 suggests calling `Mail.eager_autoload!` in an initializer.

Also, just to try to help here, could you share the complete backtrace for those deadlocks?

**Comment by skipkayhil** [comment]
Are you just calling `Rails.application.eager_load!`? If you are, can you try requiring the application's `config/environment.rb` instead? As an example, [Sidekiq](https://github.com/the-spectator/sidekiq/blob/1b5af0adc903fba3075477766d374e08faee6219/lib/sidekiq/cli.rb#L274) does this

**Comment by byroot** [comment]
Closing as this is likely to be an application issue. If not I'll reopen.

**Comment by alanhala** [comment]
Sorry for the late response. I was out for a bit. I will try requiring the environment first, checking sidekiq's example. Will post again if the issue still happens with more data. Thanks!

**Comment by alanhala** [comment]
Going through the code I've realized that I'm already loading the environment in the rake task by adding `:environment` to it. I will check if running `Rails.application.eager_load!` is causing the issue by loading twice the app? Not sure though, but will try.

**Comment by alanhala** [comment]
I've found that `Rails.application.eager_load!` is not calling `ActionMailer.eager_load!` and that's why `Mail.eager_autoload!` was never called. I tried instead requiring `config/environment.rb` and it was surprisingly not working. I found later that config.eager_load is overwritten by the `environment` rake task with the value set in `rake_eager_load`.

Just a small question: is it expected that `Rails.application.eager_load!` would not call that method? Or is it a bug?

**Comment by skipkayhil** [comment]
> Just a small question: is it expected that `Rails.application.eager_load!` would not call that method? Or is it a bug?

`ActionMailer` gets added to the `eager_load_namespaces` in `action_mailer/railtie`, so it will only be eager loaded if the railtie is required

https://github.com/rails/rails/blob/c8190750f9d28b831f9b38b4ded8a3ee5b41fd9d/actionmailer/lib/action_mailer/railtie.rb#L12

**Comment by alanhala** [comment]
@skipkayhil yes, I do require the `action_mailer/railtie` in the `application.rb`. Not sure why it wasn't working with the `Rails.application.eager_load!` call.
