### ISSUE TITLE
Querying deterministically encrypted fields possible using CLI or IDE

### ISSUE THREAD

**Issue by jdescelliers** [rails/rails#46885]
Hi

While i think it’s a great idea to have Activerecord being able to encrypt data it’s also essential to be able to query a database.

So is there any way to be able to run raw SQL queries on encrypted fields? What are the best practices when needing to extract data? Get a dump of the db locally and decrypt fields?

Please take the time to answer this, it may be worth to document this clearly.

**Comment by ghiculescu** [comment]
The [deterministic](https://guides.rubyonrails.org/active_record_encryption.html#deterministic-and-non-deterministic-encryption) option exists for allowing queryable data. The querying can be done through Active Record.
