### ISSUE TITLE
`rails credentials:show` ignores the configured key_path for the master key

### ISSUE THREAD

**Issue by Fjan** [rails/rails#46884]
### Steps to reproduce

Move the Rails master key to a non-standard location, for example

```ruby
class Application < Rails::Application
  config.credentials.key_path = '/etc/rails-master.key'
  puts "Non-standard path configured"
end
```

### Expected behavior
`rails server` works and picks up the key from the new location as expected.
`rails credentials:show` should also look in the new location.

### Actual behavior
`rails server` works fine.
`rails credentials:show` reads the configuration but doesn't seem to use it:
```
Non-standard path configured
Missing 'config/master.key' to decrypt credentials. See `bin/rails credentials:help`
```

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/46904 should fix this. Could you test it out?

**Comment by Fjan** [comment]
Yes, I tested it, it works :+1:
