### ISSUE TITLE
Group by using a joined table column with the same name as a enum column fails

### ISSUE THREAD

**Issue by harishchronus** [rails/rails#46892]
### Steps to reproduce
```ruby
class Customer < ActiveRecord::Base
  enum status %i[active slipping lost recovered]
  has_many :purchases
end

class Purchase < ActiveRecord::Base
  belongs_to :customer
  status :string
end
```
`purchases` table

| id | customer_id | status |
| :-: |       :------:     |    :-:    |
| 1 | 1 | shipped |
| 2 | 1 | shipped |
| 3 | 2 | delivered |
| 4 | 2 | returned |
| 5 | 1 | delivered |

### Expected behavior
```
Customer.joins(:purchases).group("purchases.status").count

{ "shipped" => 2, "delivered" => 2, "returned" => 1 }
```

### Actual behavior
```
{ nil => 5 }
```

### System configuration
**Rails version**:
6.1.7
**Ruby version**:
2.7

**Comment by mayank0109** [comment]
@harishchronus I think this query will throw `ActiveRecord::StatementInvalid: PG::GroupingError` error. You have to include `customers.id` while grouping since this query will select `customer.*`.

If you want the expected result try using:-
```
Customer.joins(:purchases).select("purchases.status").group("purchases.status").count
```

**Comment by ghiculescu** [comment]
Could you please create an [executable test case](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case), so we can replicate the issue and confirm it.

**Comment by harishchronus** [comment]
> Could you please create an [executable test case](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case), so we can replicate the issue and confirm it.

@ghiculescu, please find the gist containing the executable test case.
[executable test case gist](https://gist.github.com/harishchronus/21d963f285412fbd7f6ddc3ecb855f5a)
