### ISSUE TITLE
About the column type of polymorphic association foreign_type

### ISSUE THREAD

**Issue by OuYangJinTing** [rails/rails#46906]
### Steps to reproduce

``` ruby
create_table :comments, force: true do |t|
  t.add_reference :target, polymorphic: true
end
```

Currently call the `#add_reference` method defined a polymorphic associations which will create a string type `target_type` column.
This is no problem. However, the `target_type` column also can use cheaper type implement the same function. eg:

- For PG, it can be used directly [Enumerated Types](https://www.postgresql.org/docs/current/datatype-enum.html)
- For Mysql/Sqlite, it can combine integer type with `ActiveRecord::Enum` implement the same function

Perhaps it would be better to change `#add_reference` behavior?

### Expected behavior

NONE

### Actual behavior

NONE

### System configuration
**Rails version**: 7

**Ruby version**: 3

_PS: English is not my native language; please excuse typing errors._

**Comment by ahowardm** [comment]
This is not backwards compatible thow

<img width="547" alt="image" src="https://user-images.githubusercontent.com/14304368/214675431-aaabd904-e244-4905-ad84-d7e871bc18c0.png">

**Comment by OuYangJinTing** [comment]
@ahowardm Yes, but think this can be solved by [config.load_defaults](https://edgeguides.rubyonrails.org/configuring.html#versioned-default-values)

**Comment by zzak** [comment]
I'm not sure I entirely understand this thread, but it sounds like you're expecting the behavior of `add_reference` to be different?

This doesn't sound like a bug, without more concrete examples. 🤔 

Please be aware that we do not accept feature requests here, and we recommend to post on [our forum](https://discuss.rubyonrails.org) to discuss any behavior changes first. That is unless you are able to produce a patch that can explain what you're looking for. Code is easier to communicate sometimes 😄 

Feel free to re-open if I'm misunderstanding here.
