### ISSUE TITLE
skip-active-job results in no actionmailer, and thus broken development.rb in new app

### ISSUE THREAD

**Issue by mcr** [rails/rails#46926]
### Steps to reproduce

Initialize a new rails application without active-job.
(I didn't think I needed active-job, so I omitted it seeing that nice option)

```ruby
rails new --skip-active-job test4
```

### Expected behavior

Rails directory should get templated, bundled, and various things initialized.
I'm unclear why removing acting job breaks loading of active_mailer, since it seems to be included in the gem, but clearly it does not initialize.  Perhaps active_job is now required for active_mailer.
The error occurs because the default config/environments/development.rb initializes some config.active_mailer variables.

Removing/commenting them out allows rake tasks to run, but actually I want active_mailer, so I guess I will include active-job.

### Actual behavior

```
...
Using actionmailer 7.0.4
...
Fetching sprockets-rails 3.4.2
Installing sprockets-rails 3.4.2
Installing sqlite3 1.5.4 (x86_64-linux)
Bundle complete! 15 Gemfile dependencies, 72 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
         run  bundle binstubs bundler
       rails  importmap:install
rails aborted!
NoMethodError: undefined method `action_mailer' for #<Rails::Application::Configuration:0x00007f64225c3400 @root=#<Pathname:/ssw/projects/pandora/test4>, @generators=#<Rails::Configuration::Generators:0x00007f6422c9be08 @aliases={}, @options={:rails=>{:orm=>:active_record, :test_framework=>:test_unit, :integration_tool=>:test_unit, :system_tests=>:test_unit}, :active_record=>{:migration=>true, :timestamps=>true}, :test_unit=>{:fixture=>true, :fixture_replacement=>nil}}, @fallbacks={}, @templates=[], @colorize_logging=true, @api_only=false, @hidden_namespaces=[], @after_gene
```

### System configuration
**Rails version**: Rails 7.0.4

**Ruby version**: %ruby --version
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]

**Comment by skipkayhil** [comment]
Hey @mcr, thanks for opening an issue! This was fixed in #46308, which will be included in the next 7.0 release.

I'm going to close as the issue has been fixed, but feel free to reply if you have any questions!
