### ISSUE TITLE
`mark_for_destruction` on new records does not prevent them from beeing created (without `autosave: true`)

### ISSUE THREAD

**Issue by fmichaut-diff** [rails/rails#46937]
### Steps to reproduce

```ruby
#!/usr/bin/env ruby

# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_mark_for_destruction
    post = Post.new
    comment1 = post.comments.new
    comment2 = post.comments.new

    comment1.mark_for_destruction

    assert_equal true, comment1.marked_for_destruction?
    assert_equal false, comment2.marked_for_destruction?

    post.save!

    post.reload
    post.comments.reload

    assert_equal 1, post.comments.size # Currently failing, post.comments.size == 2
    # post.comments.first.marked_for_destruction? -> true
    # post.comments.last.marked_for_destruction? -> false
  end
end
```

### Expected behavior
I was expecting records marked as deleted not to be saved. 
I know adding `autosave: true` "fixes" it, but I don't think it should be required: it is counter-intuitive to mark a record for destruction and ending up with it persisted to the database.
If this is the expected behavior, a note/mention in the documentation of `mark_for_destruction` would be appreciated.

### Actual behavior
We are currently saving a record that is `marked_for_destruction`.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2p20

**Comment by eileencodes** [comment]
The [documentation](https://api.rubyonrails.org/classes/ActiveRecord/AutosaveAssociation.html#method-i-mark_for_destruction) says that this feature does not work without autosave.

<img width="983" alt="Screenshot 2023-01-09 at 1 05 46 PM" src="https://user-images.githubusercontent.com/1080678/211376899-db314f96-27f2-4302-b7dc-a5998732ac5e.png">
