### ISSUE TITLE
ActionCable: FE Disconnection Reason

### ISSUE THREAD

**Issue by DosCervezas** [rails/rails#46952]
Sorry for breaking your issue pattern but I thought it would be a bit of overkill for my simple issue.

### Expected behavior
I would like to specify a specific disconnect reasons, that the FE could catch and react on it.
Therefore I defined Standard error handled it in the handle_open method

>     class Connection < ActionCable::Connection::Base
>     ...
>     def handle_open
>       super
>     rescue MultiConnectionError => exception
>       close(reason: exception.message, reconnect: false) if websocket.alive?
>     end
>     ...
>     end

It works like a charm, the message is broadcasted to the FE

![image](https://user-images.githubusercontent.com/43810807/211588531-2902441f-5180-4ab5-a47b-2f0cfa98dca5.png)

But I cannot catch the reason.. after debugging I found the culprit

The reason is not passed to the close of the websocket
![image](https://user-images.githubusercontent.com/43810807/211588759-22e30d67-9870-4fc9-b792-94368f37445b.png)

### Actual behavior
I would like to catch the reason, why the connection is disconnected. Of course I could do it on the serverside but the reason seems to me a valid other approach.

### System configuration
**Rails version**:
Rails 7.0.4
"@rails/actioncable": "^7.0.4"

**Ruby version**:
ruby 3.1.2p20

**Comment by hahmed** [comment]
Hey @DosCervezas, could you upload a repo to demonstrate the issue? This makes it so much easier to take a look into the issue, thank you!

**Comment by DosCervezas** [comment]
thanks for your reply hahmed but I rerolled my own branch days ago sorry
but the lines I mention to pass the reason to the close event of the websocket are in this file available
https://github.com/rails/rails/blob/main/actioncable/app/javascript/action_cable/connection.js

the reason is logged in line 138 but not passed further. Thats my problem.. and globaly overwritting the log function to get the reason is not the right way I guess...

**Comment by hahmed** [comment]
I'm not sure that's the way to go, I mean you can use the logger for logging too, but maybe you want something like this https://guides.rubyonrails.org/action_cable_overview.html#server-side-components-channels-exception-handling 

Handle the exception then broadcast the error message to another channel that displays errors in a modal/alert/banner or something? (been a while since I used action cable, so I would need to test it)

**Comment by hahmed** [comment]
I did a quick test and managed to broadcast an error message to another channel, something along the lines of `ErrorAlertChannel.broadcast_to("error", exception.message)` this will allow the subscriber to handle the error client side. 

I'm closing this because I don't think this is an issue.
