### ISSUE TITLE
Automatic `:inverse_of` detection for plurals not available in Rails 6.1.x

### ISSUE THREAD

**Issue by anaulin** [rails/rails#46968]
PR https://github.com/rails/rails/pull/33729, merged ~4 years ago, extended Active Record's automatic `inverse_of` detection to support plurals (as in `has_many` associations).

This functionality remains in main but not in Rails 6.1.7:

https://github.com/rails/rails/blob/ea65d92f1924648e72f93bb0e8e5fc62a56d0bac/activerecord/lib/active_record/reflection.rb#L622

https://github.com/rails/rails/blob/v6.1.7/activerecord/lib/active_record/reflection.rb#L604

Are there plans to port this functionality to 6.x?

Apologies if this is explained somewhere, I didn't find anything about this searching through existing issues.

**Comment by skipkayhil** [comment]
Hey @anaulin, thanks for opening an issue!

New features will only be merged into `main` and released in the next major version (at that time, 7.0 was the next major version). Only bug fixes will be backported to the last stable branch (at that time, 6-1-stable).

Hope this helps!

**Comment by anaulin** [comment]
If anyone else comes across this, I was mistaken in my original report, and this change was reverted in https://github.com/rails/rails/pull/35116/files , so it no longer exists at all
