### ISSUE TITLE
Tags missing for 7.0.4.1, 6.1.7.1, and 6.0.6.1

### ISSUE THREAD

**Issue by jswanner** [rails/rails#47037]
### Expected behavior
`git tag` to include v7.0.4.1, v6.1.7.1, and v6.0.6.1

### Actual behavior
`git tag` does not include v7.0.4.1, v6.1.7.1, and v6.0.6.1

Thanks for all the work that goes into creating and maintaining these libraries!

**Comment by jhawthorn** [comment]
Thanks for the reminder.

https://github.com/rails/rails/releases/tag/v6.0.6.1
https://github.com/rails/rails/releases/tag/v6.1.7.1
https://github.com/rails/rails/releases/tag/v7.0.4.1
