### ISSUE TITLE
ActiveStorage::FileNotFoundError due to upload after commit

### ISSUE THREAD

**Issue by sbungartz** [rails/rails#47047]
We were getting `ActiveStorage::FileNotFoundError`s spuriously and are fairly confident that this is a race condition in the way ActiveStorage handles uploads and attachment.

### Steps to reproduce
In the [rails guides](https://guides.rubyonrails.org/active_storage_overview.html#has-one-attached), the recommended set up for a controller that attaches a file to a model is as follows:

```ruby
class SignupController < ApplicationController
  def create
    user = User.create!(user_params)
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:email_address, :password, :avatar)
  end
end
```

When using this recommended set up Rails will upload the file [_after committing_](https://github.com/rails/rails/blob/18707ab17fa492eb25ad2e8f9818a320dc20b823/activestorage/lib/active_storage/attached/model.rb#L77) the creation and attachment of the `Blob` to the model.
Within the same thread this is not a problem because the hook will obviously wait until the upload is finished and other code runs that might depend on that file.
However since the `Blob` and `Attachment` are already committed in the database, parallel processes like integrations polling for updates, or even just users clicking on the entity at just the wrong moment, will already see the attachment and try to download it causing an `ActiveStorage::FileNotFoundError`.

### Expected behavior
Before the file is actually uploaded, the `User` should not be committed to the database.
For updates, the `Attachment` should not be committed to the database before upload is finished.

### Actual behavior
The new user is committed with the `Blob` attached before the file is uploaded. Other requests or background tasks can find that `User` causing an `ActiveStorage::FileNotFoundError` when they try to download the avatar.

### Our workaround
Rewriting the controller like this solves the problem as the file is uploaded before the change is committed to the database:
_Edit:_ The original version of the workaround that I posted broke presence-validation. With this updated variant, we still just assign `nil` to the `avatar`, if the param is not sent, so displaying form errors still works normally.

```ruby
class SignupController < ApplicationController
  def create
    user = User.new(user_params.except(:avatar)) # Note this change, to avoid creating the attachment twice.
    user.avatar = try_create_and_upload_blob!(user_params.fetch(:avatar, nil))

    user.save!
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:email_address, :password, :avatar)
  end

  # This can also be put somewhere as a static method for reuse in different controllers.
  def try_create_and_upload_blob!(uploaded_file)
    return nil if uploaded_file.blank?
    ActiveStorage::Blob.create_and_upload!(
      io: uploaded_file.to_io,
      filename: uploaded_file.original_filename,
    )
  end
end
```

This makes sure, that the file is completely uploaded before the `Blob` is attached to the `User`. Of course this is quite a bit more cumbersome.

### Other considerations
I could also see other problems arising from doing a long upload within a transaction, so I was wondering if this was intentional.

If upload it is really supposed to be happening in the `after_commit`, at least the guide should point out these potential issues and maybe we can even find a way to make uploading before committing less verbose and cumbersome.

### Potentially related issues
These issues might be related:
- #42003
- #39107

### System configuration
**Rails version**: `6.1.6`

**Ruby version**: `3.1.3`

**Comment by zzak** [comment]
Thanks for reporting this issue, TIL something new!

I think the docs could be improved, to call out these types of gotchas, feel free to submit a PR.

Looking at the guides, there is one small reference to this here:
https://guides.rubyonrails.org/active_storage_overview.html#downloading-files

> It's important to know that the file is not yet available in the after_create callback but in the after_create_commit only.

I have no checked the API docs yet, but also something to consider.

**Comment by sbungartz** [comment]
@zzak Thanks, I will try to find the time for a PR.

I also just updated the workaround code in the description, because my original version broke presence validation.

**Comment by zzak** [comment]
Also somewhat related, but I wonder in this case why not wrap the whole thing in a transaction 🤔

**Comment by sbungartz** [comment]
> Also somewhat related, but I wonder in this case why not wrap the whole thing in a transaction thinking

I do have reservations about doing the upload within transaction, since having long running transactions could cause problems, especially if other validations or callbacks cause widespread locking.
With the workaround code, we would have the possibility of `Blobs` being created that are never attached.
If I am not mistaken this could also happen using direct upload, even more likely because the client device is still involved.
Maybe there should be a cleanup job that gets rid of these periodically.

**Comment by Polo2** [comment]
👋 ,

As mentioned by @paulRbr , we have a similar issue on our project.

What happens:

1.  User upload a logo for his documentation (our product is a tool to generate API documentation from OpenAPI/AsyncAPI specification)
2. Consequently, a job `ActiveStorage::AnalyzeJob` is scheduled (native behavior, no change in our app).
3. But User may destroy its documentation (blob's resource) before this job is performed
4. Exception `ActiveStorage::FileNotFoundError` is raised, and job failed.

My first impression here was that this exception `ActiveStorage::FileNotFoundError` should prevent this job `ActiveStorage::AnalyzeJob` to be re-scheduled.
Solution could be to discard also `ActiveStorage::FileNotFoundError` in `ActiveStorage::AnalyzeJob`, as it's already done with `ActiveRecord::RecordNotFound` (introduced by 06f8baf73c677303353c79609838caaeec3ccc9a)

Something like:
```ruby
class ActiveStorage::AnalyzeJob < ActiveStorage::BaseJob
  queue_as { ActiveStorage.queues[:analysis] }

  discard_on ActiveRecord::RecordNotFound
  discard_on ActiveRecord::FileNotFoundError # new line here
  retry_on ActiveStorage::IntegrityError, attempts: 10, wait: :exponentially_longer

  def perform(blob)
    blob.analyze
  end
end
```

WDYT?

**Comment by palexvs** [comment]
we have the same issue, and it's possible to reproduce:
in first console run:
```

loop do
  if (image = some_model.find(1).image).attached?
    resp = Faraday.get Rails.application.routes.url_helpers.rails_storage_proxy_url(image)
    puts resp.status
    break if resp.status == 200
  else
    sleep(0.01)
  end
rescue => e
  puts e
  sleep(0.01)
end
```
in the second console:
```
some_model.find(1).image.attach(io: StringIO.new(file), filename: filename, content_type: "image/jpg")
```

I'm getting this output:
```
502 <-- first request fails
200
```

**Comment by palexvs** [comment]
There is another simpler and more stable way to reproduce the issue:

the first console that fetches the file:
```
loop do
  if (image = some_model.find(1).image).attached?
    key = image.attachment.blob.key
    exist = image.attachment.blob.service.exist?(key)
    puts "exist?(#{key}) => #{exist}"
    break if exist
  else
    sleep(0.01)
  end
end
```

the second console that uploads the file:
```
class ActiveStorage::Blob < ActiveStorage::Record
  def upload_without_unfurling(io)
    sleep(1) # imitate big file upload or some delay on storage system side
    service.upload key, io, checksum: checksum, **service_metadata
  end
end

some_model.find(1).image.attach(io: StringIO.new(file), filename: filename, content_type: "image/jpg")
```

output in the first console 
```
exist?(vpz3azorta188m1aj2ibc2ctbei5) => false
exist?(vpz3azorta188m1aj2ibc2ctbei5) => false
exist?(vpz3azorta188m1aj2ibc2ctbei5) => false
exist?(vpz3azorta188m1aj2ibc2ctbei5) => false
exist?(vpz3azorta188m1aj2ibc2ctbei5) => false
exist?(vpz3azorta188m1aj2ibc2ctbei5) => false
exist?(vpz3azorta188m1aj2ibc2ctbei5) => true
```

**Comment by rafaelfranca** [comment]
This seems like the expected behavior. Maybe we should have a flag in the `Blob` record to say the image isn't yet uploaded to the service so users can check that flag, but I don't see how to change this behavior so the record is only committed when it is uploaded to the service without decreasing considerably the resilience of applications.

**Comment by gbp** [comment]
We're seeing the same [issue](https://github.com/mysociety/alaveteli/issues/7934#issuecomment-1761268470) in ActiveJob/Sidekiq which results in the file being lost due to the job exiting before the `after_commit` fires.

Adding a flag on `Blob` would be useful and allow us to ensure the job doesn't exit early.

**Comment by manafire** [comment]
Adding a flag would fix my inline upload case where the UI shows a broken image momentarily while the variants are uploading/processing in the background.

**Comment by garethrees** [comment]
> Adding a flag on `Blob` would be useful and allow us to ensure the job doesn't exit early.

Currently we're basically doing:

```rb
record.file_blob.service.exist?(record.file_blob.key)
#  Disk Storage (2.9ms) Checked if file exists at key: fumc2mmt9sj44b84o03taz1m1ooe (yes)
# => true
```

Would a PR adding the following be of interest?

```rb
class ActiveStorage::Blob < ActiveStorage::Record
  #…

  # Alternatively, could call this #uploaded?
  def exist?
    service.exist?(key)
  end

  #…
end
```

That way we could at least do `record.file_blob.exist?`. Could also look at cleaning this up to be `record.uploaded?`, but I think the above would be a prerequisite for that.

**Comment by palexvs** [comment]
@garethrees I would not recommend using `service.exist?` as in prod with AWS & GCS. It could be anything from 10ms up to 100-1000ms + $ for each request. So far, @sbungartz solution looks like the best.

**Comment by sbungartz** [comment]
@rafaelfranca 

> ..., but I don't see how to change this behavior so the record is only committed when it is uploaded to the service without decreasing considerably the resilience of applications.

I would argue that this really depends on the use case. Not creating a user account because the avatar failed to upload would be bad, so that is a good example, where the current behavior makes more sense.

However in our case, where this came up originally, we have a separate model for uploaded photos along with some metadata like a description. To me it makes no sense having that record in the database before the upload is completed, and even less sense to have it if the photo ultimately failed to upload.
That would feel *less* resilient to me than simply not having that record, showing the user that the upload of the image failed, and they can try it again.

With a flag to indicate the status of the Blob, we could show other users a loading spinner instead of the image, which might feel nice if we also automatically show the image once it becomes available.
But since the upload is not completed, it might still fail. Then we have this record that is forever in a state of "file will be here soon, just wait a bit more".

It seems to me like "direct upload" also makes that tradeoff in the opposite direction: We upload the image before even submitting the actual form to Rails, so when we link attachment and model in the database, the upload has already been completed. We never end up with a record pointing to an attachment without an uploaded file. We might just end up with uploaded files that are never used.

Maybe I'm overlooking other aspects that would decrease resilience though.

**Comment by Dreamersoul** [comment]
Hello, after looking around it looks like a bug in rails.

https://stackoverflow.com/questions/77201333/cannot-get-a-signed-id-for-a-new-record-with-url-for-after-attaching-pictur

https://github.com/rails/rails/issues/47047

Id appreciate it if you found a workaround and submit a PR 🙏🏻

**Comment by palexvs** [comment]
>If you can still reproduce this error on the 7-1-stable branch or on main, please reply with all of the information you have about it in order to keep the issue open.

Yes, still regularly happens in my app

**Comment by danielricecodes** [comment]
I'm having a very similar issue in my `test` environment with Rails and AS 7.0.8.4.

```
ActiveRecord::RecordNotFound:
       Couldn't find ActiveStorage::Blob with 'id'=11
     # /<path>/gems/activestorage-7.0.8.4/app/models/active_storage/blob.rb:87:in `find_signed!'
     # /<path>/gems/activestorage-7.0.8.4/app/controllers/concerns/active_storage/set_blob.rb:12:in `set_blob'
```

Most of the solutions for "how to attach ActiveStorage Uploads in RSpec" do not seem to resolve it.  Additionally, if I try to refactor my Factories to use `create_and_upload!` then call `signed_id` on that instance, I get another odd error from inside `ActiveStorage::Blob`:

```
NoMethodError:
  undefined method `generate' for nil
# /<path>/gems/activerecord-7.0.8.4/lib/active_record/signed_id.rb:114:in `signed_id'
# /<path>/gems/ruby-3.3.4@provalet-rails/gems/activestorage-7.0.8.4/app/models/active_storage/blob.rb:165:in `signed_id'
# ./spec/factories/invoices.rb:203:in `block (3 levels) in <top (required)>'
# /<path>/gems/factory_bot-6.2.1/lib/factory_bot/trait.rb:13:in `instance_eval'
# /<path>/gems/factory_bot-6.2.1/lib/factory_bot/trait.rb:13:in `initialize'
```
