### ISSUE TITLE
Functional Tests documentation needs some updates

### ISSUE THREAD

**Issue by siaw23** [rails/rails#47048]
I was looking to stub some methods with minitest in a new Rails app. It looks like [this part of the documentation](https://guides.rubyonrails.org/testing.html#instance-variables-available) is out of date.

This bit of the documentation is not true as far as I can tell:

>You also have access to three instance variables in your functional tests, after a request is made:
>
>@controller - The controller processing the request
>@request - The request object
>@response - The response object

### Steps to reproduce
Generate a Rails 7 app, then generate a scaffold, try prying into any `ActionDispatch::IntegrationTest` and accessing `@controller`.

### Expected behavior
I expected to be able to access `@controller`

### Actual behavior
`@controller` is `nil`

### System configuration

Rails 6.1.4.6

ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-darwin22]

**Comment by siaw23** [comment]
Closing. I was wrong. I missed this bit "after a request is made".

**Comment by zzak** [comment]
@siaw23 I can see skipping that last bit (the most important part) of the sentence, so I made #47065 to reword it a little. :pray: Thanks for reporting the issue!
