### ISSUE TITLE
Unexpected ORDER BY Clause via `has_many :through`

### ISSUE THREAD

**Issue by eric-hemasystems** [rails/rails#47059]
Note. I previously attempted to discuss this issue [in the forums](https://discuss.rubyonrails.org/t/unexpected-order-by-clause-from-has-many-through/82067) but was redirected to post here.

### Steps to reproduce
```ruby
require 'bundler/inline'

gemfile do
 source 'https://rubygems.org'
 gem 'activerecord', require: 'active_record'
 gem 'sqlite3'
 gem 'minitest'
 gem 'minitest-bang', require: 'minitest/bang'
end

require 'minitest/spec'
require 'minitest/autorun'

describe 'has_many :through with order' do
  let!(:widget) { Widget.create! }

  let!(:group1) { Group.create! position: 1, widget: }
  let!(:item1) { Item.create! position: 1, group: group1 }
  let!(:item2) { Item.create! position: 2, group: group1 }

  let!(:group2) { Group.create! position: 2, widget: }
  let!(:item3) { Item.create! position: 1, group: group2 }
  let!(:item4) { Item.create! position: 2, group: group2 }

  it 'should return items sorted by group then within group' do
    # puts widget.items.to_sql
    expect( widget.items.to_a ).must_equal [item1, item2, item3, item4]
  end
end

ActiveRecord::Base.establish_connection adapter: 'sqlite3', database: ':memory:'
ActiveRecord::Migration.verbose = false

ActiveRecord::Schema.define version: 1 do
  create_table :widgets
  create_table :groups do |t|
    t.belongs_to :widget, null: false
    t.integer :position, null: false
  end
  create_table :items do |t|
    t.belongs_to :group, null: false
    t.integer :position, null: false
  end
end

class Widget < ActiveRecord::Base
  has_many :groups, -> { order :position }
  has_many :items, through: :groups
  # has_many :items, -> { order 'groups.position, items.position' }, through: :groups
end

class Group < ActiveRecord::Base
  belongs_to :widget
  has_many :items, -> { order :position }
end

class Item < ActiveRecord::Base
  belongs_to :group
end
```

### Expected behavior

I expected the `ORDER BY` clause to be:

```sql
ORDER BY "groups"."position" ASC, "items"."position" ASC
```

Uncomment the `puts` statement to see the generated SQL statement when running. Swap which `has_many :through` statement is commented out for the work-around that allows my tests to run.

### Actual behavior

The `ORDER BY` clause is:

```sql
ORDER BY "items"."position" ASC, "groups"."position" ASC
```

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.2.0

**Comment by fatkodima** [comment]
Yes, makes sense to me. Will try to look into it.

**Comment by szymonlipka** [comment]
I was checking this issue and it looks like the order of scope evaluation from through scope was changed intentionally in https://github.com/rails/rails/commit/5c6d6fd30af2208a86f97ce0ca303c6c59700246, after reverting this commit it is working like you would expect.

**Comment by nickborromeo** [comment]
since this seems to be an intentional change, should we go ahead and close out this issue?

**Comment by matthewd** [comment]
Hmmm, yeah, I think this might be "expected" behaviour.

Personally I find the behaviour of multiple `.order` calls in general to be unfortunate: whether `rel.order(:name).pluck(:name)` ends up ordered by name depends on whether `rel` already had an order set (in contrast to `sort_by(&:name)`, for example).

While I agree the behaviour described in this issue would probably be more useful on average, there is also the point that it's easier & more intuitive to achieve the opposite (with the double-barrelled order) than it would be to do the inverse.

Overall I think I'm going to close this for now as works-as-intended. I'm 50/50 on whether the current behaviour is the best thing to do, but given how complex a deprecation would be, I think that's enough to bias away from change.

I'm not a fan of adding potentially-distracting paragraphs to documentation to describe edge cases when people can probably intuit them when they run into them, but if there's a concise way of hinting at this in the docs (perhaps by casually using this sort of dual-`position` arrangement as the example block, without even needing any explicit discussion), that might be worth looking at.
