### ISSUE TITLE
raise_on_missing_translations should raise for *all* missing translations

### ISSUE THREAD

**Issue by jaynetics** [rails/rails#47057]
the option name `config.i18n.raise_on_missing_translation` misleadingly suggests that it will help you catch all missing translations, but it is really just for views.

either the name should be changed (back?), or it should really raise in all cases.

### Steps to reproduce

```ruby
# in application.rb
config.i18n.raise_on_missing_translations = true


# my_model.rb
class MyModel
  def self.name = I18n.t('no_such_name')
end
```

### Expected behavior

```ruby
MyModel.name # => error
```

### Actual behavior

```ruby
MyModel.name # => "translation missing: en.no_such_name"
MyModel.name.class # => String
```

### Simple solution

```ruby
if config.i18n.raise_on_missing_translations
  I18n.exception_handler = ->(msg, *) { raise msg }
end
```

(this would make https://github.com/rails/rails/pull/45361 obsolete)

**Comment by rafaelfranca** [comment]
There is no config called `config.i18n.raise_on_missing_translations`.

There is only `config.action_view.raise_on_missing_translations`. 

Where did you find about the `config.i18n.raise_on_missing_translations`?

**Comment by rafaelfranca** [comment]
Ah, true, but the documentation of that config tells it only for controller and views. We just not document this in the generated app, but that is fixed 5c835bd669.

Now, should it affect all of the I18n? Maybe. This would be a feature request though, and we don't take feature requests in the issue tracker, but if you want to implement that, I'd love to merge the PR.

Is the config name misleading? I think so. Can we change, not really, that is a lot of deprecation cycle for us and for our users, so it is better to improve the situation with documentation.

**Comment by rafaelfranca** [comment]
Sorry, not meant to close again.

**Comment by zzak** [comment]
I _feel_ like this is documented [here](https://edgeguides.rubyonrails.org/i18n.html), but maybe could be rephrased to emphasis that `MissingTranslationData` is not re-raised and instead render the exception message.

> This method will re-raise all exceptions except for MissingTranslationData exceptions. When a MissingTranslationData exception has been caught, it will return the exception's error message string containing the missing key/scope.
> 
> The reason for this is that during development you'd usually want your views to still render even though a translation is missing.

I'm also not sure if/how `raise_on_missing_translations` fits into this yet, but probably should be covered in this guide?

**Comment by fwolfst** [comment]
> I _feel_ like this is documented [here](https://edgeguides.rubyonrails.org/i18n.html), but maybe could be rephrased to emphasis that `MissingTranslationData` is not re-raised and instead render the exception message.

I agree it should be covered there and I support the informal feature request :) Being able to catch missing translations in specs by setting the (then well-named) `config.i18n.raise_on_missing_translation` options.

**Comment by zzak** [comment]
Yeah, if the behavior for `raise_on_missing_translations` is unexpected then a PR is preferred since we don't accept feature requests as issues. Also open to suggestions on how to improve the docs in that form, or discuss/discord whichever you prefer. :bow:

**Comment by ghiculescu** [comment]
> if you want to implement that, I'd love to merge the PR.

Would love feedback on https://github.com/rails/rails/pull/47105
