### ISSUE TITLE
Cookie domain calculation broken with domain: all after 6.1.7.1 upgrade

### ISSUE THREAD

**Issue by ilya-konanykhin** [rails/rails#47055]
The recent 6.1.7.1 update changed how `domain: :all` for cookies works and is now handling two letter domains incorrectly: https://github.com/rails/rails/compare/v6.1.7...v6.1.7.1#diff-ec27bb8290189e09e65a52e49641cd7952660dcf237a327311f79ddd65d01eecR457-R462

The REGEXP in the code above grabs ANY `xx(x).xx` host suffix (`example.nl -> le.nl`) and falls into the `else` branch when it shouldn't. I assume there is a leading dot missing `.xx(x).xx`, so the REGEXP should be smth like `/\.([^.]{2,3}\.[^.]{2})$/` but not sure, please check.

Why tests didn't catch it? Because they test with `www.nextangle.com` host which is not affected due to 3 letter `com` ending.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 6.1.7"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts = []
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    cookies["test"] = {value: "1", domain: :all}
    render plain: "Home"
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_example_org
    get "http://example.org/"
    assert last_response.ok?
    assert_equal ".example.org", last_response.cookies["test"].domain
  end

  def test_www_example_org
    get "http://www.example.org/"
    assert last_response.ok?
    assert_equal ".example.org", last_response.cookies["test"].domain
  end

  def test_example_nl
    get "http://example.nl/"
    assert last_response.ok?
    assert_equal ".example.nl", last_response.cookies["test"].domain
  end

  def test_www_example_nl
    get "http://www.example.nl/"
    assert last_response.ok?
    assert_equal ".example.nl", last_response.cookies["test"].domain
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior

`www.example.nl` should yield `.example.nl` cookie domain if used with `domain: :all`.

### Actual behavior

`.www.example.nl` is produced, the last test fails `test_www_example_nl`.

### System configuration
**Rails version**: 6.1.7.1

**Ruby version**: 2.5.1

**Comment by ilya-konanykhin** [comment]
Also in that REGEXP brackets are redundant I think, they aren't used neither for grouping nor for matching, but may be wrong.

**Comment by sgnh** [comment]
I ran into this problem in production too on 7.0.4.1, and the result is that a session cookie is now set for both: .domain.co and .www.domain.co

This means that rolling back to 7.0.4 switches the cookie back to .domain.co, but the existing .www.domain.co gets picked first as it's more specific. So our users are now stuck with the old invalid session, unable to sign in.

So even when this gets fixed in Rails, it doesn't fix it for the users as far as I can tell. Does anyone have any idea on how we can wipe the invalid cookie, without asking the users to do it locally?

**Comment by sgnh** [comment]
Quick update for anyone who gets their users locked out by this. I ended up rolling back to 7.0.4 and changing the "key" on Rails.application.config.session_store. This will effectively reset everybody's session and stop any looping caused by the wrong session being picked.

**Comment by zzak** [comment]
@jhawthorn Could you take a look? :bow:

**Comment by ilya-konanykhin** [comment]
> Quick update for anyone who gets their users locked out by this. I ended up rolling back to 7.0.4

FYI if you don't want/can rollback and your app responds to a single known up front domain, you can specify the session cookie domain explicitly:

```
Rails.application.config.session_store :cookie_store, {...otheroptions..., domain: ".example.nl"}
```

This will disabled the `:all` logic at least for session cookies, which is the main problem for the majority of users I think.

**Comment by KevinSchiffmann** [comment]
We have the same cookie issue with Rails 7.0.4.1 (Ruby 3.1.2), with domain like "https://customer.project.ch".

Thank you!

**Comment by rafaelfranca** [comment]
> It basically loads the code before the change.

@langalex Isn't this reintroducing the security issue? At that point, it is better to not upgrade (that I don't recommend as well).

**Comment by jhawthorn** [comment]
I've opened #47087. Would love help confirming that fixes the issue 🙇‍♂️

**Comment by langalex** [comment]
> > It basically loads the code before the change.
> 
> @langalex Isn't this reintroducing the security issue? At that point, it is better to not upgrade (that I don't recommend as well).

yes. updated it.

**Comment by ilya-konanykhin** [comment]
> I've opened https://github.com/rails/rails/pull/47087. Would love help confirming that fixes the issue

Fixes for me, thanks! Please don't forget to port to 6.1 branch as well.

**Comment by jhawthorn** [comment]
Rails 7.0.4.1 and 6.1.7.2 have been released with a fix for this issue
