### ISSUE TITLE
Rails guide statement recommending changing `secret_key_base` doesn't give full context of what will be lost

### ISSUE THREAD

**Issue by daniel-nelson** [rails/rails#47060]
https://github.com/rails/rails/blob/main/guides/source/security.md?plain=1#L118 states "Changing secret_key_base will expire currently active sessions", but does not mention other things (e.g. ActionText attachments) that will be affected. Listing all the affected things and linking to instructions on how to rotate each of them gracefully would be helpful.

**Comment by ghiculescu** [comment]
Thanks for the feedback, would you like to make a PR to improve the guide?

**Comment by Aryanryn09** [comment]
i want to claim this issue

**Comment by zzak** [comment]
There's no need to "claim" anything here, anyone can submit a patch anytime they want. Usually the first one wins, but not always, sometimes a better patch comes along.

Starting [here](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html) is always a good first step.

**Comment by kinduff** [comment]
This can be closed now, I miss-spelled "Fix" and used "Fixes" instead.

**Comment by zzak** [comment]
@kinduff The ticket description mentions "ActionText attachments" but the docs say "Active Storage Files" 🤔

**Comment by kinduff** [comment]
@zzak maybe I'm wrong, but aren't ActionText attachment really Active Storage files? Do we need further clarification?

**Comment by zzak** [comment]
> maybe I'm wrong, but aren't ActionText attachment really Active Storage files? Do we need further clarification?

I wasn't sure either, that's why I asked 😂 we will have to adjust the list to be a sentence in the same block, due to how these get rendered, but can always make changes to that list in the future. Thanks for your patch!

![Screenshot 2023-04-09 at 8 10 29](https://user-images.githubusercontent.com/277819/230746415-a606ce57-a995-4239-a5b5-18152db208c7.png)
