### ISSUE TITLE
Active Storage dependency documentation inconsistent

### ISSUE THREAD

**Issue by diesl** [rails/rails#47062]
### Steps to reproduce
I have a question about Active Storage dependencies. The documentation is not consistent about _Yarn_ and _Node.js_. Unfortunately I am not sure which part is correct.

https://edgeguides.rubyonrails.org/development_dependencies_install.html says
> Active Storage depends on Yarn (additionally Yarn depends on [Node.js](https://nodejs.org/)), ImageMagick, libvips, FFmpeg, muPDF, Poppler, and on macOS also XQuartz.

https://edgeguides.rubyonrails.org/active_storage_overview.html says

> Various features of Active Storage depend on third-party software which Rails will not install, and must be installed separately:
 [libvips](https://github.com/libvips/libvips) v8.6+ or [ImageMagick](https://imagemagick.org/index.php) for image analysis and transformations
 [ffmpeg](http://ffmpeg.org/) v3.4+ for video previews and ffprobe for video/audio analysis
 [poppler](https://poppler.freedesktop.org/) or [muPDF](https://mupdf.com/) for PDF previews

### Expected behavior
The documentation should be consistent concerning required 3rd party dependencies.

### Actual behavior
_Development Dependencies Install_ says Yarn (and Node.js) are required, but _Active Storage Overview_ does not

### System configuration
**Rails version**: N/A

**Ruby version**: N/A

**Comment by hahmed** [comment]
@diesl so they are 2 different things... https://edgeguides.rubyonrails.org/development_dependencies_install.html  talks about dev dependencies, so for example to run the tests for active storage 

e.g. `cd active_storage` and  `bin/test` will run the tests for yarn, if installed, example test: https://github.com/rails/rails/blob/5b9a24601331d53fbd3931c736b1785b16590b9f/activestorage/test/javascript_package_test.rb#L10

Whereas if you want to use active storage in your application, then the dependencies are different, you don't need yarn/node if you install active storage client code via importmaps.

Hope that clears things up.

**Comment by diesl** [comment]
Thanks for clearing this up 👍

**Comment by zzak** [comment]
Maybe "Rails development" is too vague, I can see that being confused with say "Rails app development" for someone building an application vs. developing the Rails framework 🤔

**Comment by hahmed** [comment]
This is good "Ruby on Rails core development" but I can see for every reference of "Rails development" maybe it's a bit much 🤷‍♂️
