### ISSUE TITLE
Active Storage previewable not resized when using proxy mode on storage service local

### ISSUE THREAD

**Issue by mbodlund** [rails/rails#47071]
### Steps to reproduce

Active proxy mode or use rails_storage_proxy_path to generate preview of a video or pdf.
Rails.application.config.active_storage.resolve_model_to_route = :rails_storage_proxy

```ruby
development.rb
config.active_storage.service = :local

active_storage.rb
Rails.application.config.active_storage.resolve_model_to_route = :rails_storage_proxy

In a view
image_tag message.video.preview(resize_to_limit: [100, 100]) 
```

### Expected behavior
An jpg version resized to limit 100x100

### Actual behavior
Returns a jpg version in the same size as the original video (or pdf)

If you turn off rails_storage_proxy it works as expected.

### System configuration
Rails 7.0.4.1
ffmpeg version 5.1.2 (also tried version 3.x and 4.x with the same result)
mutool version 1.20.0

Ruby 3.1.2

**Comment by alexandreruban** [comment]
I can reproduce the issue on `main`. The `resolve_model_to_route` configuration can take two values:

1. `rails_storage_redirect`
2. `rails_storage_proxy`

--- 

When using the `rails_storage_redirect` configuration, `message.video.preview(resize_to_limit: [100, 100])` will end up in the `ActiveStorage::Representations::RedirectController#show` action. In this controller, we redirect to `@blob.representation(params[:variation_key]).processed.url`.

In that case, the url we redirect to is the url of the variant corresponding to the applied transformations:

```rb
def url(**options)
  if processed?
    variant.url(**options)
  else
    raise UnprocessedError
  end
end
```

--- 

When using the `rails_storage_proxy` configuration, `message.video.preview(resize_to_limit: [100, 100])` will end up in the `ActiveStorage::Representations::ProxyController#show` action. In this controller, we stream `@blob.representation(params[:variation_key]).processed.image`.

In that case, the `image` is always the blob's `preview_image` without any transformations:

```rb
def image
  blob.preview_image
end
```

--- 

I'm not sure why there are two different approaches here. 
In the `ProxyController`, we should also return the correct variation by doing something like this (in pseudo code):

```rb
# activestorage/app/controllers/active_storage/representations/proxy_controller.rb

def show
  http_cache_forever public: true do
    send_blob_stream @representation.variant.image, disposition: params[:disposition]
  end
end
```

I've tested and it works. If you think the approach is correct, I'd love to draft a PR!

**Comment by chaadow** [comment]
Hi @mbodlund and @alexandreruban 

I've fixed this in https://github.com/rails/rails/pull/50098  and it's on both [7-0-stable](https://github.com/rails/rails/tree/7-0-stable) and [7-1-stable](https://github.com/rails/rails/tree/7-1-stable)

@jonathanhefner I believe we can close this issue

**Comment by chaadow** [comment]
cc @zzak
