### ISSUE TITLE
ActionText view path not registered in mailer previews

### ISSUE THREAD

**Issue by irminsul** [rails/rails#47072]
### Steps to reproduce

Create a simple model with a rich text content attribute and a mailer that uses that model:

```ruby
# app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_rich_text :content

  # This causes a template lookup error in the mailer preview
  validates :content, length: { maximum: 10 }
end

# app/mailers/blog_mailer.rb
class BlogMailer < ApplicationMailer
  def post_published
    mail(to: 'foo@bar.com', subject: 'New blog post')
  end
end

# test/mailers/previews/blog_mailer_preview.rb
class BlogMailerPreview < ActionMailer::Preview
  def blog_post_published
    post = BlogPost.create!(content: 'post content')
    BlogMailer.with(post: post).post_published
  end
end
```

Here's a ready to go repo to illustrate the issue: https://github.com/irminsul/rails7-mailerpreview

Run `rails s` and open http://localhost:3000/rails/mailers/blog_mailer/blog_post_published in a browser.

### Expected behavior
The mailer preview should render without errors.

### Actual behavior

`BlogPost.create!` will run model validations, and attempt to render the rich text attribute with the default content template.

For reasons beyond my current understanding of Rails internals, `$GEM_PATH/gems/actiontext-7.0.4.1/app/views` is not registered as a view path at that point and a `MissingTemplate` error is raised:

```
ActionView::MissingTemplate (Missing partial action_text/contents/_content with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}.

Searched in:
  * "/home/mz/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-7.0.4.1/lib/action_dispatch/middleware/templates"
  * "/home/mz/.asdf/installs/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/railties-7.0.4.1/lib/rails/templates"
```

### System configuration
**Rails version**: 7.0.4.1

**Ruby version**: 2.7.6

**Comment by ghiculescu** [comment]
The root cause is that the view path is overriden for internal Rails controllers [here](https://github.com/rails/rails/blob/5a16eadbc31b8d7ab0f1fecb9aee581fc1d97327/railties/lib/rails/application_controller.rb#L4).
