### ISSUE TITLE
ActiveRecord storing different datetime values

### ISSUE THREAD

**Issue by GlauberrBatista** [rails/rails#47084]
### Steps to reproduce
Create a simple rails project with a dummy model with a `datetime` field.
```shell
$ rails new test-date
$ bundle exec rails generate model Dummy date:datetime
$ bundle exec bin/rails db:migrate
```
Open the console and type:
```ruby
irb(main):001:0> obj = Dummy.new
=> #<Dummy:0x0000000121405200 id: nil, date: nil, created_at: nil, updated_at: nil>
irb(main):002:0> value = '05/04/18'.to_datetime
=> Sat, 18 Apr 0005 00:00:00 +0000
irb(main):003:0> obj.date = value
=> Sat, 18 Apr 0005 00:00:00 +0000
irb(main):004:0> value == obj.date
=> false
irb(main):005:0> value
=> Sat, 18 Apr 0005 00:00:00 +0000
irb(main):006:0> obj.date
=> Mon, 18 Apr 0005 00:00:00.000000000 UTC +00:00
irb(main):007:0> value.to_i
=> -62000294400
irb(main):008:0> obj.date.to_i
=> -62000121600
```

### Expected behavior
The model attribute should be equal to the `datetime` object.

### Actual behavior
ActiveRecord is setting a wrong `datetime` value. This happens with ancient dates (I catch it in a test with some old dates). This is not happening to recent dates.

### System configuration
**Rails version**: 7.0.4.1

**Ruby version**: 2.7.6

At first, I thought it was related to the SQL injection fix, but when I uncommented the quoting lines it didn't change the result. 
It seems the culprit is the date gem, which was introduced through the `mail` -> `net-imap` -> `date` gem update. To test it, I copied the old `date 3.0.3` gem I had installed to the `date 3.3.3` folder, and it worked.

**Comment by GlauberrBatista** [comment]
Just found some references to the Julian and Gregorian calendars on the `date` gem changelog: https://github.com/ruby/date/compare/v3.0.3...v3.3.3
Perhaps rails should use Gregorian by default?

**Comment by yahonda** [comment]
I recall https://github.com/rails/rails/commit/43a6b4fc0f7902e682d49933f84fa84642282393 to follow the https://github.com/ruby/date/pull/73

**Comment by ismailaidar** [comment]
if you `"#{value.day} #{value.month} #{value.year}"` that would give you `18 4 5` and year 5 doesn't make sense, so what you want to do is help .to_datetime function by giving a 4 digits year instead of 2.
