### ISSUE TITLE
Lowercase headers returned from Sprockets 4.2.0 not caught within Actionpack router

### ISSUE THREAD

**Issue by markedmondson** [rails/rails#47096]
### Steps to reproduce
The [Gemlock](https://github.com/rails/rails/blob/main/Gemfile.lock#L454) specifies Sprockets 4.2.0 but this is incompatible with the Actionpack router. In [Sprockets 4.2.0, the returned headers were changes to lowercase to support Rack 3](https://github.com/rails/sprockets/pull/758), the [Actionpack router has case sensitive matching for the `X-Cascade` header](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/journey/router.rb#L52-L57) which means failed routes don't cascade to other potential matches.

Toggle the Sprockets version from 4.2.0 to 4.1.1 below to see the issue.

For a Sprockets application serving from `/assets` and an additional route serving from `/assets/some-path`, the latter should still respond after Sprockets has failed to match the route.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 7.0.4.1"
  gem "sprockets", "~> 4.2.0"
  gem "sprockets-rails", "~> 3.4.2"
  gem "capybara"
end

require "rails"
require "action_controller/railtie"
require "action_view/railtie"
require "sprockets/railtie"

class HelloWorld
  def self.call(env)
    [200, {}, ["hello world"]]
  end
end

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts = []
  config.session_store :cookie_store, key: "cookie_store_key"
  config.assets.compile = true
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger
end

require 'fileutils'
FileUtils.mkdir_p('app/assets/config/')
FileUtils.touch('app/assets/config/manifest.js')

Rails.application.initialize!

TestApp.routes.draw do
  get "/assets/test", to: ::HelloWorld
end

FileUtils.rm('app/assets/config/manifest.js')
FileUtils.rmdir('app/assets/config/')

require "minitest/autorun"
require 'capybara/rails'
require 'capybara/minitest'

class ActionDispatch::IntegrationTest
  # Make the Capybara DSL available in all integration tests
  include Capybara::DSL
  # Make `assert_*` methods behave like Minitest assertions
  include Capybara::Minitest::Assertions

  # Reset sessions and driver between tests
  teardown do
    Capybara.reset_sessions!
    Capybara.use_default_driver
  end
end

class BugTest < ActionDispatch::IntegrationTest
  def test_assets_route
    visit "/assets/test"

    assert_equal 200, page.status_code
    assert_content "hello world"
  end
end
```

### Expected behavior
Both `X-Cascade` and `x-cascade` headers should be matched from Sprockets. 
Alternatively, Sprockets should be locked to 4.1.1 until this is resolved in Rails.

### Actual behavior
X-Cascade header isn't matched and matching routes are missed.

### System configuration
**Rails version**: 7.x & 6.1.x

**Ruby version**: 3.x

**Comment by ghiculescu** [comment]
Hmm, based on my read of https://github.com/rails/sprockets/pull/758 it seems like `rack >= 2.2.4` is also required. Do you know what version you are using?

cc @lsylvester

**Comment by markedmondson** [comment]
> Using rack 2.2.6.2

**Comment by lsylvester** [comment]
I am using rack 2.2.6.2 - but I don't rely on this cascade behavior in my applications so I haven't run into this. I have added #47108 to fix this issue.
