### ISSUE TITLE
I18n translate stringfies the Hash of grabbing all values

### ISSUE THREAD

**Issue by crashtech** [rails/rails#47090]
### Steps to reproduce

When running I18n with and without Rails, there is a difference while trying to fetch the whole hash.
```ruby
# irb
require 'i18n'
I18n.backend = I18n::Backend::Simple.new
I18n.backend.store_translations(:en, foo: { a: 'a', b: 'b' })
puts(I18n.t("foo").class)
# Hash
```

```ruby
# rails c
I18n.backend = I18n::Backend::Simple.new
I18n.backend.store_translations(:en, foo: { a: 'a', b: 'b' })
puts(I18n.t("foo").class)
# String
```

### Expected behavior
I expected that both would return me a Hash.

### Actual behavior
Only when running over the Rails console is when I get a String instead.

### System configuration
**Rails version**: 7.0.4.1

**Ruby version**: 3.0.4

**Comment by rafaelfranca** [comment]
How can I reproduce this? I just tried in a new application and I get a hash.

**Comment by rafaelfranca** [comment]
This is in the Rails console:

```irb
>> I18n.backend = I18n::Backend::Simple.new
=> #<I18n::Backend::Simple:0x0000ffff91c66b00>
>> I18n.backend.store_translations(:en, foo: { a: 'a', b: 'b' })
>> puts(I18n.t("foo").class)
Hash
```

**Comment by crashtech** [comment]
I've just found the problem! Thanks for the rapid reply!
