### ISSUE TITLE
v6.1.7.1 missing action mailbox changes present in 6.1-stable

### ISSUE THREAD

**Issue by softr8** [rails/rails#47114]
### Steps to reproduce
[v6.1.7.1 ](https://github.com/rails/rails/releases/tag/v6.1.7.1)tag is out but it's different from what the branch 6.1-stable has
https://github.com/rails/rails/blob/v6.1.7.1/actionmailbox/lib/action_mailbox/mail_ext/addresses.rb
https://github.com/rails/rails/blob/6-1-stable/actionmailbox/lib/action_mailbox/mail_ext/addresses.rb

We're getting:
```
     NoMethodError:
       undefined method `address_list' for #<Mail::FromField:0x000000013358df20>
       Did you mean?  address
     # .../lib/ruby/gems/2.7.0/gems/mail-2.8.0.1/lib/mail/field.rb:233:in `method_missing'
     # .../lib/ruby/gems/2.7.0/gems/actionmailbox-6.1.7.1/lib/action_mailbox/mail_ext/addresses.rb:6:in `from_address'
     # .../lib/ruby/2.7.0/delegate.rb:83:in `method_missing'
```

### Expected behavior
6.1-stable code to be present in v6.1.7.1

### Actual behavior
For some reason, the commit coming from https://github.com/rails/rails/pull/46643 is not in v6.1..1

### System configuration
v6.1.7.1 vs 6.1-stable

**Comment by yahonda** [comment]
Hi, 

Rails 6.1.7.1 was built out of 6.1.7, not the latest 6-1 stable branch. Therefore, it is correct that the v6.1.7.1 tag does not have https://github.com/rails/rails/commit/f5463f314886016fb40199d1265cacddf64ea357 because it was merged after 6.1.7 was released. 

This is explained below.

https://guides.rubyonrails.org/maintenance_policy.html#security-issues

> These releases are created by taking the last released version, applying the security patches, and releasing. Those patches are then applied to the end of the x-y-stable branch. For example, a theoretical 1.2.2.1 security release would be built from 1.2.2, and then added to the end of 1-2-stable.
