### ISSUE TITLE
number_to_human_size not returning the expected result

### ISSUE THREAD

**Issue by scratchoo** [rails/rails#47131]
I wanted to convert the size of file (which is in bytes) to human readable format

The actual file size is 136535 bytes
that is 133.33 KB (the result I am getting from a Javascript function I am using in the frontend, and also the same result I am getting from online tools like this one https://www.gbmb.org/bytes-to-kb

However in Rails, I am getting only 133 KB without the decimal points.

```ruby
number_to_human_size(136535)  # 133 KB
```

### Expected behavior
Should return 133.33 KB

### Actual behavior
It returns 133 KB

To make the story short, I translated my own JS function to ruby and I started getting 133KB (same result as number_to_human_size), after that the fix was to change this line of my ruby script: 

```
bytes /= 1024
```

to this

```
bytes /= 1024.0
```

I think similar thing is happening with number_to_human_size method

see: https://github.com/rails/rails/blob/18707ab17fa492eb25ad2e8f9818a320dc20b823/activesupport/lib/active_support/number_helper/number_to_human_size_converter.rb#L56

and also this line (which uses "base" and make it as int (using to_i)
https://github.com/rails/rails/blob/18707ab17fa492eb25ad2e8f9818a320dc20b823/activesupport/lib/active_support/number_helper/number_to_human_size_converter.rb#L46

without dividing by a float number (1024.to_f) you don't get the correct result.

### System configuration
**Rails version**:  7.0.3.1

**Ruby version**:  3.0.2

**Comment by ghiculescu** [comment]
Try `number_to_human_size(136535, significant: false)`. It outputs `133.335 KB`, so closer to what you want. `number_to_human_size(136535, significant: false, precision: 2)` outputs exactly what you want. The `significant` and `precision` options are documented here: https://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_to_human_size 

I'm gonna leave this open because I feel like maybe we could give a better answer out of the box, but at least there's a way to get what you want 👍

**Comment by ghiculescu** [comment]
Ahh, no, this is expected. If I'm understanding right, the default options (`precision: 3, significant: true`) means the output will have at most 3 significant digits. So `133`. You can customise using the `significant` and `precision` options. eg. if you always want 2 decimal places you'd do `significant: false, precision: 2`.

**Comment by scratchoo** [comment]
@ghiculescu Oh I see, sorry about that, it was confusing because in the doc there is an example which seems to give 2 digits without adding any extra option:

```
number_to_human_size(1234)                                         # => 1.21 KB
```

But the result for 136535 there was no digits

Also the "significant" option still not clear what it does from the doc, I wouldn't figure it out by myself if you didn't explain it.

Thank you.

**Comment by ghiculescu** [comment]
Ahh, so that has 3 significant digits (1, 2, 1). Which is the default. By contrast:

```ruby
3.1.3 :003 > ActiveSupport::NumberHelper.number_to_human_size 1234, precision: 4, significant: true
 => "1.205 KB"
```
