### ISSUE TITLE
Given a String sanitize_sql_for_order Sill Requires Calling `Arel.sql` on Its Return Value

### ISSUE THREAD

**Issue by sshaw** [rails/rails#47140]
### Steps to reproduce

```rb
Model.order(sanitize_sql_for_order(q))
```

### Expected behavior

`sanitize_sql_for_order` should call `Arel.sql` when given a `String` like it does in [the other case](https://github.com/rails/rails/blob/f0c5e60aed8bdce96c385cad05b1e34d7d757038/activerecord/lib/active_record/sanitization.rb#L75). 

### Actual behavior

Results in an `ActiveRecord::UnknownAttributeReference` error.

**Comment by rafaelfranca** [comment]
We can't do that. If `q` contains an user provided string, `sanitize_sql_for_order` isn't going to do anything with that string, and `Model.order` can cause a SQL injection.

**Comment by fabian-as** [comment]
> We can't do that. If `q` contains an user provided string, `sanitize_sql_for_order` isn't going to do anything with that string, and `Model.order` can cause a SQL injection.

I recently stumbled across this exact issue. Do you mind if I adjust the place in the documentation and add a warning that providing a string does not involve any sanitisation at all?

**Comment by iberianpig** [comment]
@rafaelfranca  I thought sanitization was happening, but I didn’t realize it only returns the string unchanged. Allowing a string without sanitization is risky, as it can lead to API misuse and security issues.

As @fabian-as mentioned, some measures may be necessary.

1. Add a note in the API documentation or Rails Guide.
2. Issue a warning when a string is passed, or raise an error to prevent receiving a string type.

**Comment by rafaelfranca** [comment]
Isn't the exception that it causes enough for preventing misuse?

> Actual behavior
Results in an ActiveRecord::UnknownAttributeReference error.
