### ISSUE TITLE
Document other web server support for AC::Streaming

### ISSUE THREAD

**Issue by zzak** [rails/rails#47173]
When applying some changes to [ActionController::Streaming](https://edgeapi.rubyonrails.org/classes/ActionController/Streaming.html) recently I noticed the "Web server support" section is missing [puma](https://github.com/puma/puma) and [falcon](https://github.com/socketry/falcon), but perhaps others too?

Maybe a good first patch if someone wants to investigate! :bow:

**Comment by ioquatix** [comment]
There are two main mechanisms in Rails for "real time" responses:

1. `ActionController::Streaming`
2. `ActionController::Live`

## `ActionController::Streaming`

The implementation depends on `Rack::Chunked` which **only** works with HTTP/1.1 and you could argue violates the Rack spec by writing `transfer-encoding: chunked` data as a Rack entity body. Most servers implement chunked encoding as part of the network transport layer.

My guess is `Rack::Chunked` and by implication `ActionController::Streaming` are unlikely to work on most mainstream web servers.

The irony of this is, chunked encoding is not needed for streaming, and correctly supporting streaming depends on the network protocol in use, e.g. HTTP/1.0 needs to use `connection: close`, HTTP/1.1 can use either `connection: close`, `connection: upgrade` or `transfer-encoding: chunked` depending on the situation, and HTTP/2+ doesn't need any of those.

## `ActionController::Live`

Likewise `ActionController::Live` is a bit of a hack and uses a separate thread with a buffered body.

## Rack 2 vs Rack 3

Rack 3 explicitly introduces a streaming body. If you don't model it like this, middleware doesn't know whether it can/should buffer the response body, e.g. `Rack::ETag` can buffer the `ActionController::Live` response body causing it to break the streaming.

Both should be replaced by Rack 3 streaming. For all intents and purposes, Rack 2 does not support streaming except via the `rack.hijack` interface.

**Comment by haadfida** [comment]
can I work on this issue, thanks?

**Comment by Basit108** [comment]
Good

**Comment by zzak** [comment]
Anyone can submit a patch anytime they want. You don't have to ask for permission 😅 

Starting [here](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html) is always a good first step.

**Comment by giovannism20** [comment]
> When applying some changes to [ActionController::Streaming](https://edgeapi.rubyonrails.org/classes/ActionController/Streaming.html) recently I noticed the "Web server support" section is missing [puma](https://github.com/puma/puma) and [falcon](https://github.com/socketry/falcon), but perhaps others too?
> 
> Maybe a good first patch if someone wants to investigate! bow

Could you better describe the steps to find this problem ?

**Comment by zzak** [comment]
Basically according to the API docs, in order to get streaming to work with certain webservers there are some tricks involved. I haven't tested it myself, but at the time of the writing it seems multiple webservers have been released. It would be good to review [the guides](https://edgeguides.rubyonrails.org/action_controller_overview.html#live-streaming-of-arbitrary-data) as well and try building an app that uses it for each webserver and verify they all work.

Having said all of that, I'm not so sure how beginner friendly this issue really is 😄 but going to keep it hear in case anyone is interested -- feel free to ask any questions!
