### ISSUE TITLE
Multiple database config results in No connection pool for 'ActiveRecord::Base' found for the 'reading' role.

### ISSUE THREAD

**Issue by figandbones** [rails/rails#47182]
### Steps to reproduce
Followed instructions for writer and reader database configs: https://guides.rubyonrails.org/active_record_multiple_databases.html
I have a legacy rails project, which I've stripped down to a skeleton which still has the error: https://diana-xml.s3.us-west-1.amazonaws.com/ih2-rails-app.tgz

### Expected behavior
Database queries should not cause error.

### Actual behavior
The first database query results in the error above.
This command
`ActiveRecord::Base.configurations.configs_for(env_name: "development")`
results in only one entry.

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.0.4

**Comment by eileencodes** [comment]
Hi @figandbones you are never establishing a connection to the replica database, so Rails doesn't know it exists. The documentation for multiple databases is here: https://guides.rubyonrails.org/active_record_multiple_databases.html. You need to update your ApplicationRecord with a `connects_to database: { writing: :primary, reading: :primary_replica }` as documented.
