### ISSUE TITLE
MessageVerifier fails when only the serializer is rotated

### ISSUE THREAD

**Issue by ankane** [rails/rails#47185]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support/all"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    key = SecureRandom.hex(64)
    message = ActiveSupport::MessageVerifier.new(key, serializer: Marshal).generate(["hello", "world"])

    verifier = ActiveSupport::MessageVerifier.new(key, serializer: JSON)
    verifier.rotate(serializer: Marshal)
    assert_equal ["hello", "world"], verifier.verify(message)
  end
end
```

### Expected behavior

Verification succeeds (it deserializes as Marshal when JSON fails)

### Actual behavior

Verification errors with `JSON::ParserError: unexpected token`

### System configuration
**Rails version**: 7.0.4.2 and `main`

**Ruby version**: 3.2.0

**Comment by alexandreruban** [comment]
I'd love to work on this issue. I found the bug, I'll open a PR later today.

**Comment by alexandreruban** [comment]
@ankane I think what you are looking for is the `ActiveSupport::JsonWithMarshalFallback` serializer.

The following example works:

```rb
class BugTest < Minitest::Test
  def test_stuff
    key = SecureRandom.hex(64)
    message = ActiveSupport::MessageVerifier.new(key, serializer: Marshal).generate(["hello", "world"])

    verifier = ActiveSupport::MessageVerifier.new(key, serializer: ActiveSupport::JsonWithMarshalFallback)
    verifier.rotate(serializer: Marshal)
    assert_equal ["hello", "world"], verifier.verify(message)
  end
end
```

Let me know if it helps.

**Comment by ankane** [comment]
Hey @alexandreruban, thanks for the response. That'll work on `main` for those specific serializers, but not the general case. For instance, trying to rotate from YAML to JSON will raise the same error as above, and trying to rotate something to YAML will raise `Psych::SyntaxError: (<unknown>): control characters are not allowed at line 1 column 1`.

**Comment by ankane** [comment]
Thanks @jonathanhefner for both the fix and additional improvements!
