### ISSUE TITLE
no minimized tag support for the boolean attributes

### ISSUE THREAD

**Issue by dhurba87** [rails/rails#47198]
Creating script tag using `content_tag` with `defer: true` adds `defer="defer"` in the html attributes.  Which is correct but according to [HTML4.01 spec](https://www.w3.org/TR/REC-html40/intro/sgmltut.html#h-3.3.4.2), it is recommended to use  minimized form as many user agents only recognize the minimized form of boolean attributes and not the full form

> Some attributes play the role of boolean variables (e.g., the selected attribute for the OPTION element). Their appearance in the start tag of an element implies that the value of the attribute is "true". Their absence implies a value of "false".
>
> [...]
>
> In HTML, boolean attributes may appear in minimized form -- the attribute's value appears alone in the element's start tag. Thus, selected may be set by writing:
>
> \<OPTION selected>
> instead of:
>
> \<OPTION selected="selected">
> Authors should be aware that many user agents only recognize the minimized form of boolean attributes and not the full form.

**Comment by hahmed** [comment]
@dhurba87 Is that still true for the latest version of HTMl? 

I'm not seeing that comment in https://www.w3.org/TR/2021/NOTE-html53-20210128/infrastructure.html#sec-boolean-attributes nor here https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes. Maybe that's no longer true the spec you linked is to a much older version (1999 -- https://www.w3.org/TR/REC-html40/cover.html#minitoc)...

**Comment by dhurba87** [comment]
@hahmed looks like it is not true for the latest version of HTML

**Comment by hahmed** [comment]
Cool, i'm going to close this issue because the value of removing extra characters from the DOM is nice and prob worth even creating a PR for (please explore that if you wish), but I don't feel it's a bug.
