### ISSUE TITLE
Regression between Rack 2 and Rack 3 when a param is `nil`

### ISSUE THREAD

**Issue by ghiculescu** [rails/rails#47207]
### Steps to reproduce

This passes when using Rack 2:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "rack", "~> 2.0"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "www.example.com"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    post "/" => "test#index"
  end
end

class TestController < ActionController::Base
  def index
    output = params[:foo].nil? ? "Foo is nil" : "Foo is #{params[:foo].presence || "blank"}"
    render plain: output
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < ActionDispatch::IntegrationTest
  def test_returns_success
    post "/", params: { foo: nil, bar: "1" }
    assert_equal "Foo is nil", response.body
  end

  private
    def app
      Rails.application
    end
end
```

But if you switch to Rack 3 by changing line 11, it fails:

```
Expected: "Foo is nil"
  Actual: "Foo is blank"
```

### Expected behavior

The test should pass with both versions of Rack, or there should be a deprecation warning if this change is expected, or this issue should be closed as it's a known issue with a fix in progress :)

I think https://github.com/rails/rails/pull/47080 is the same issue but I thought it was worth logging just in case it's not.

cc @ioquatix since it seems related to the Rack migration.

### System configuration
**Rails version**: `main`

**Ruby version**: 3.1

**Comment by ioquatix** [comment]
Encoding `nil` in URL parameters is not officially supported: https://github.com/whatwg/url/issues/732

It was removed in Rack 3, but as you point out #47080 restores that (non-standard) behaviour.

**Comment by ghiculescu** [comment]
This isn't in a URL param, it's in a POST body. Not sure if that makes a difference. In any case, thanks for confirming re that PR.

**Comment by ioquatix** [comment]
Nope, it's the same `application/x-www-form-urlencoded` format whether it's the URL query part or the POST body.
