### ISSUE TITLE
7.0.4.x releases not cut from 7-0-stable? (Missing commits)

### ISSUE THREAD

**Issue by pboling** [rails/rails#47216]
### Steps to reproduce

Fix has been in 7-0-stable branch since November 2022.

https://github.com/rails/rails/commit/cac3c8f54eac403b1bc49b8090e39b8c176add68

### Expected behavior

I expect the fix to be in a release cut from 7-0-stable branch.

The modified code resulting from the commit is in the 7-0-stable branch still today:
https://github.com/rails/rails/blob/7-0-stable/actionpack/lib/action_dispatch/middleware/templates/routes/_table.html.erb#L105

### Actual behavior

Can't find fix in the release:

https://github.com/rails/rails/blame/7c70791470fc517deb7c640bead9f1b47efb5539/actionpack/lib/action_dispatch/middleware/templates/routes/_table.html.erb#L105

How is this possible?

**Comment by eileencodes** [comment]
Security releases are cut from the _last_ security release branch/tag. Otherwise there could be breaking changes in the security release. It should only be the changes needed to ensure the app is secure so that it's easier for applications to remain upgraded.
