### ISSUE TITLE
Confirmation dialog didn't showed up using `button_to` without turbo

### ISSUE THREAD

**Issue by rizlantamima** [rails/rails#47213]
### Steps to reproduce
Confirmation dialog didn't show when I'm using `button_to` without turbo (`data: { turbo: false }`).
### Expected behavior
Able to use a confirmation dialog with (**button_to helper**) but without turbo
### Actual behavior
by using one of this solution, the confirmation dialog still doesn’t showed up.
```ruby
button_to t("delete_this"), the_path(@resource), method: :delete,  data: { turbo: false, turbo_confirm: I18n.t('action_confirmations')}
```
OR
```ruby
button_to t("delete_this"), the_path(@resource), method: :delete,  data: { turbo: false, confirm: I18n.t('action_confirmations')}
```
### System configuration
**Rails version**:
Rails 7.0.4
**Ruby version**:
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]

**Comment by skipkayhil** [comment]
As far as I know there are two options for enabling `data-confirm` behavior: Turbo and rails-ujs. If you aren't using Turbo you could use rails-ujs, but if you aren't using either I would not expect your snippet to produce a dialog.
