### ISSUE TITLE
Redis cache store docs about hiredis seem outdated

### ISSUE THREAD

**Issue by RasimKhusaenov** [rails/rails#47228]
### Summary
[There is a paragraph about the `hiredis`](https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-rediscachestore) in the guide. In `redis 4.x` gem everything worked as it should. I recently updated the gem to 5.x and now it doesn't work. I investigated the source of the problem, and came to the following conclusion.

I noticed that after the update, `redis-client` started to be used too. In the CHANGELOG, [it says that since version 0.4.0, the `hiredis` driver has moved to `hiredis-client`](https://github.com/redis-rb/redis-client/blob/master/CHANGELOG.md#040). If we compare the documentation of the two versions of the `redis` gem, there, too, `hiredis` was replaced by `hiredis-client`: [old one](https://github.com/redis/redis-rb/blob/v4.5.1/README.md#hiredis) and [new one](https://github.com/redis/redis-rb/blob/master/README.md#hiredis-binding).

It seems to me that this moment also needs to be corrected in the guide.

### Steps to reproduce

In `Gemfile`:
```ruby
gem 'redis', '5.0.5'
gem 'hiredis', '0.6.3'
```

In `config/environments/*.rb`:
```ruby
config.cache_store = :redis_cache_store, { url: ENV['REDIS_URL'], driver: :hiredis }
```
OR
In rails console:
```ruby
RedisClient.new(driver: :hiredis)
```

You should have error:
```ArgumentError: Unknown driver :hiredis, expected one of: [:ruby]```

**Comment by ghiculescu** [comment]
Thanks for the report. Would you like to make a PR to update the guide?

**Comment by RasimKhusaenov** [comment]
@ghiculescu, I just noticed, that in #45856 `hiredis` was removed. I suppose it's not worth adding it back?

**Comment by ghiculescu** [comment]
@byroot what do you think?

**Comment by ghiculescu** [comment]
@RasimKhusaenov do these docs seem correct? https://edgeguides.rubyonrails.org/caching_with_rails.html#activesupport-cache-rediscachestore

They include the changes from that PR. If they still have issues we should fix them.

**Comment by RasimKhusaenov** [comment]
@ghiculescu, no, it seem okay. The problem is only related to `hiredis`.

**Comment by byroot** [comment]
I see no reason to document Hiredis in Rails guides. It's documented in the `redis-rb` README, if people think that makes a measurable performance difference in their app (it generally doesn't) they can find the information on how to tune redis there.

**Comment by ghiculescu** [comment]
👍 sounds like this is all good then.
