### ISSUE TITLE
Checking if a date in an open date range loops forever when the range starts after the test date

### ISSUE THREAD

**Issue by wilhelmsen** [rails/rails#47272]
### Steps to reproduce
```ruby
Date.today.in?(Date.tomorrow..)
```
it never returns an answer.

`Date.today.in?(Date.yesterday..)` e.g. returns `true` right away.

### Expected behavior
Return `false`

### Actual behavior
Never returns. Infinite loop?

### System configuration
**Rails version**: 7.0.4.2

**Ruby version**: 3.1.3

**Comment by wilhelmsen** [comment]
This is a ruby issue and not a rails issue... Opened a bug report there instead... sorry for spamming.

**Comment by wilhelmsen** [comment]
I'd like to reopen this, after the comment in the ruby bug report: https://bugs.ruby-lang.org/issues/19418

It indicates that the `in?` uses `include?` whereas it should use `cover?`?

**Comment by eileencodes** [comment]
> It indicates that the in? uses include? whereas it should use cover??

I don't see Rails using or documenting usage of `Date.today.in?(Date.tomorrow..)` so I'm not sure what we'd change on our end? Do you think this is a bug in Rails? `Date`, `cover?`, and `in?` are defined by Ruby, not Rails so I'm not sure what we would do here.

**Comment by wilhelmsen** [comment]
According to the comment from zverok in the ruby-issue (see above), ruby 3.2 raises a `TypeError` if `include?` is being used with an open range.

I am not too familiar with the rails source code, but
`Date.today.method(:in?).source_location`
suggests that the implementaion of `in?` is found here:
https://github.com/rails/rails/blob/main/activesupport/lib/active_support/core_ext/object/inclusion.rb
and that is just uses the ruby-version of `include?`.

If I understand this correctly, a more robust implementation would be to use `cover?`, which accepts open ranges.
