### ISSUE TITLE
Incorrect subquery for a polymorphic `has_one` association

### ISSUE THREAD

**Issue by janko** [rails/rails#47335]
### Steps to reproduce

```ruby
require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Schema.define do
  create_table :pins do |t|
    t.string :code, null: false
  end
  create_table :cards do |t|
  end
  create_table :access_tools do |t|
    t.references :item, polymorphic: true
  end
end

class Pin < ActiveRecord::Base
  has_one :access_tool, as: :item
end

class Card < ActiveRecord::Base
  has_one :access_tool, as: :item
end

class AccessTool < ActiveRecord::Base
  belongs_to :item, polymorphic: true
end

Pin.create!(code: "1111")
AccessTool.create!(item: Card.create!)
AccessTool.create!(item: Pin.create!(code: "2222"))

Pin.where(access_tool: AccessTool.all).count # => 2 (expected 1)
```

### Expected behavior

I expected the subquery to automatically filter by the source type, because Active Record has the information about this. So, I expected `Pin.where(access_tool: AccessTool.all)` to filter access tools by `item_type = "Pin"`:

```sql
SELECT "pins".* FROM "pins" WHERE "pins"."id" IN (
  SELECT "access_tools"."item_id" FROM "access_tools" WHERE "access_tools"."item_type" = "Pin"
)
```

### Actual behavior

What happened was that the subquery didn't include any source type filters, so the query would return PINs with IDs from other source types. The actual subquery didn't contain any `item_type` filters:

```sql
SELECT "pins".* FROM "pins" WHERE "pins"."id" IN (
  SELECT "access_tools"."item_id" FROM "access_tools"
)
```

I find this subquery to be incorrectly inferred from my `has_one` association declaration, because it's missing the `item_type = "Pin"` filter. Active Record should either generate the complete subquery, or raise an error that it cannot generate it. I find the current behavior to be dangerous, because it gave me the illusion that it succeeded in generating the requested subquery, but it was only partial.

This is the second time I got surprised by this behavior; the first time it was just me running something in the console, but the second time it actually caused a bug in production. So I thought I would report it.

### System configuration

**Rails version**: 7.0.4.2

**Ruby version**: 2.7.6

**Comment by janko** [comment]
It happened again that I feel into this Active Record behavior. I would appreciate to least get an acknowledgement whether this does look like a bug. For me this behavior makes subqueries for polymorphic associations broken.

**Comment by rafaelfranca** [comment]
Yeah, this is a bug. Thank you for reporting. Someone triaged it already and added a label, so it means it is really an issue. If wasn't the person would have closed it.

**Comment by janko** [comment]
Thank you for fixing this, I verified it indeed resolves the issue 🙌🏻

**Comment by byroot** [comment]
Backported to 7-0-stable.
