### ISSUE TITLE
ActionView::Helpers::TextHelper # highlight is performing slow with either large text or multiple matches

### ISSUE THREAD

**Issue by stillhart** [rails/rails#47337]
### Steps to reproduce

The following test is the most simple use-case to increase the `highlight` execution time into multiple seconds. In my real world case I was trying to match 50 different items across 1000's of lines of plain text.

The test below only shows the execution times and does not fail. I can not really define what the expected performance on any hardware is supposed to be, expect that it am certain that it should be faster.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "~> 7.0.0"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers
end

require "minitest/autorun"
require "minitest/benchmark"

class BugTest < Minitest::Benchmark
  include Rack::Test::Methods

  def bench_highlight_with_one_text_match
    assert_performance (proc {}) do |n|
      TestController.helpers.highlight("foo bar 1234\n" * n, "bar")
    end
  end

  def bench_highlight_with_one_match
    assert_performance (proc {}) do |n|
      TestController.helpers.highlight("foo bar 1234\n" * n, /bar/)
    end
  end

  def bench_highlight_with_two_matches
    assert_performance (proc {}) do |n|
      TestController.helpers.highlight("foo bar 1234\n" * n, /foo|bar/)
    end
  end

  def bench_highlight_with_three_matches
    assert_performance (proc {}) do |n|
      TestController.helpers.highlight("foo bar 1234\n" * n, /foo|bar|1234/)
    end
  end
end
```

### Expected behavior

The `highlight` method performs highlighting with multiple thousand of lines and multiple matches in less than a second, or even better in less than 100ms. 

### Actual behavior

| Benchmark | 1 lines | 10 lines | 100 lines | 1000 lines | 10000 lines |
| ------------- |:----------:|:----------:|:----------:|:----------:|:----------:|
| bench_highlight_with_one_text_match | 0.002027 | 0.000874 | 0.001864 | **0.072229** | **6.902236** |
| bench_highlight_with_one_match | 0.231050 | 0.001049 | 0.001921 | **0.069195** | **6.856789** |
| bench_highlight_with_two_matches | 0.000937 | 0.000907 | 0.002685 | **0.148295** | **14.246967** |
| bench_highlight_with_three_matches | 0.001286 | 0.000569 | 0.002794 | **0.208822** | **20.961633** |

The highlight method performs surprisingly slow and easily reaches multi-second execution times when having either larger text or multiple matches.

In my case I was highlighting 50 kind of matches found in multiple 1000's of lines of text. That resulted in timeouts due to the 60+ second long execution time. I did not expect highlight to be that slow and that sensitive. My matches did not consist of very complex regexes. It usually mostly consisted of simple case insensitive word matches, sometimes some simple character matching like \S+.

Initially I tried to nest `highlight` method calls for each kind of match, which resulted in even worse execution times.

### System configuration
**Rails version**:
7.0.4.2

**Ruby version**:
ruby 3.2.0
ruby 3.2.1

### Documentation
https://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-highlight

**Comment by fatkodima** [comment]
Thanks for the report. I was able to find a solution - PR is coming.
