### ISSUE TITLE
Link to SQL Reference guide

### ISSUE THREAD

**Issue by zzak** [rails/rails#47369]
In the [Active Record Basics](https://guides.rubyonrails.org/active_record_basics.html#object-relational-mapping) guide there is a note pointing readers where to learn more about SQL (and RDBMS) the latter part is missing entirely, and the SQL links to W3schools:

https://github.com/rails/rails/blob/b6ecefddac2fc13382ad25d8d84052a547d04bcf/guides/source/active_record_basics.md?plain=1#L46-L49

Would prefer to link to a standard resource that does not contain ads, tracking software, or other subscription related incentives.

Patches welcome that can fix this!

**Comment by davidomullan** [comment]
In case it's easier than opening the commit, my recommended new links:
https://www.khanacademy.org/computing/computer-programming/sql
https://www.devart.com/what-is-rdbms/

This is my pull request, so please let me know any best practices I got wrong! Thanks for reviewing.
