### ISSUE TITLE
Ruby 3.2.0 actionmailer backports have not been released in 6.1.7.1 and 6.1.7.2

### ISSUE THREAD

**Issue by d4rky-pl** [rails/rails#47375]
### Steps to reproduce
Even though the commit that introduces the Ruby 3.2.0 fixes [is present in 6-1-stable branch](https://github.com/rails/rails/commit/67bdba4e63cad218c02dbb3171ddd53353cc0b48), it seems that the 6.1.7.1 and 6.1.7.2 do not include the necessary changes.

- https://my.diffend.io/gems/actionmailer/6.1.7/6.1.7.1
- https://my.diffend.io/gems/actionmailer/6.1.7.1/6.1.7.2

### Expected behavior
Actionmailer 6.1.7.1 and 6.1.7.2 should include all patches from 6-1-stable branch

### Actual behavior
Ruby 3.2.0 patch is missing

### System configuration
**Rails version**:
6.1.7.1, 6.1.7.2

**Ruby version**:
3.2.0

**Comment by zzak** [comment]
I think because those were security fixes, they only include the patches to resolve those CVEs, unlike a bugfix release.

All of this is covered here:
https://edgeguides.rubyonrails.org/maintenance_policy.html

But I think because 6.1 is not supported for bugfixes, this won't be released.

**Comment by d4rky-pl** [comment]
@zzak yeah, on further research I saw [this comment](https://github.com/rails/rails/issues/47040#issuecomment-1387552189), closing this
