### ISSUE TITLE
Support processing active storage variants eagerly

### ISSUE THREAD

**Issue by shouichi** [rails/rails#47387]
ActiveStorage variants are processed on the fly when they are needed but sometimes we're sure that they are accessed and want to process them upfront.

We could add an option for eager processing variants.

```
has_one_attached :avatar do |attachable|
	attachable.variant :thumb, resize_to_limit: [100, 100], eager_process: true
end
```

Thank you.

**Comment by shouichi** [comment]
Thank you for the feedbalck! Yes, we can do that but sometimes we have multiple controllers for the same resource (e.g., API and admin) and manually calling the processing job is error-prone. Another way is to use active record callbacks but if a callback is used, why don't we support it at the framework level? Analyzing blobs is already built-in, and the requested feature seems sensible.

**Comment by hahmed** [comment]
I think having a variant already processed and ready to serve attachment is a nice feature.

This looks more like a feature request, so going to close it because the issue tracker is mostly for bugs, but please create a PR if you can.

**Comment by shouichi** [comment]
I'm going to open a PR. Thank you!

**Comment by shouichi** [comment]
@hahmed I opened https://github.com/rails/rails/pull/47473. Could you take a look?
