### ISSUE TITLE
ActiveStorage "index_active_storage_blobs_on_key" should be "index_active_storage_blobs_on_key_and_service_name"

### ISSUE THREAD

**Issue by weilandia** [rails/rails#47382]
### Steps to reproduce

Create two blobs with the same `key` but with a different `service_name`.  The "index_active_storage_blobs_on_key" does not take `service_name` into account when it seems like it should.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "rails"
  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.active_storage.service = :local_a
  config.active_storage.service_configurations = {
    local_a: {
      root: Dir.tmpdir,
      service: "Disk"
    },
    local_b: {
      root: Dir.tmpdir,
      service: "Disk"
    },
  }
end

db_dir = Dir.mktmpdir("test", Dir.tmpdir)
ENV["DATABASE_URL"] = "sqlite3:#{db_dir}/db.sqlite3"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_one_attached :profile_a, service: :local_a
  has_one_attached :profile_b, service: :local_b
end

require "minitest/autorun"

class BugTest < Minitest::Test
  include Rails.application.routes.url_helpers
  include Rack::Test::Methods

  def test_upload_and_fetch
    user = User.create!
    user.profile_a.attach(
      key: "test",
      io: StringIO.new("test"),
      filename: "test.txt"
    )

    assert_raises(ActiveRecord::RecordNotUnique) do
      user.profile_b.attach(
        key: "test",
        io: StringIO.new("test"),
        filename: "test.txt"
      )
    end
  end
end
```

### Expected behavior
When blobs are created with the same key in different services, I don't think there should be a RecordNotUnique error. 

### Actual behavior
The unique constraint on `key` for `active_storage_blobs` does not take `service_name` into account when it seem like it should.

**Comment by ghiculescu** [comment]
The `key` isn't meant to be user-provided as it is in your example, it's meant to be [defined programmatically](https://github.com/rails/rails/blob/75a1871b3919db95fcaf19089b5ada0889092c0c/activestorage/app/models/active_storage/blob.rb#L161).

Given that, I think it is simplest to have the key be guaranteed unique.

**Comment by weilandia** [comment]
@ghiculescu  specifying `key` was added to the public api in [4dba136](https://github.com/rails/rails/commit/4dba136c83cc808282625c0d5b195ce5e0bbaa68).
