### ISSUE TITLE
Yarn cannot use latest versions automatically due to hyphens

### ISSUE THREAD

**Issue by joao-esteves** [rails/rails#47390]
### Steps to reproduce

1. Go to an empty folder
2. yarn add @rails/ujs@7.0.4
3. Update with either
    a) yarn upgrade @rails/ujs
    b) yarn upgrade-interactive --latest

Note this could have been any other `@rails` package.

### Expected behavior

With either steps 3a or 3b, `@rails/ujs` is updated to 7.0.4-2, as of writing. Or 7.0.4.2, if versions were uploaded without hyphens.

### Actual behavior

`@rails/ujs` stays on 7.0.4, despite there being a more recent 7.0.4-2.

### Description

From what I know, hyphens should be used for pre-release versions. I do not know any other packages that use hyphens for their release versions. I propose that new release versions stop using hyphens.

I chose a specific version to install on the reproduction steps, but, as of writing, this issue is also applicable to version-less package installation. `yarn add @rails/ujs` installs version 7.0.4 instead of 7.0.4-2.

### System configuration
**Yarn version**: 1.22.19

**Comment by yahonda** [comment]
There was a similar discussion #39351

**Comment by ghiculescu** [comment]
I think we can close this per https://github.com/rails/rails/pull/47394 and https://github.com/rails/rails/issues/39351

You will need to manually update the package if you want the security release.
