### ISSUE TITLE
IRB Corruption rails console - (Object doesn't support #inspect) 

### ISSUE THREAD

**Issue by JohnDBR** [rails/rails#47413]
I was about to start a project, so I decided to upgrade my developing environment, by updating my Ruby and Rails versions a little bit and I was coding smoothly while looking up the new rails features. Then, suddenly I entered the `rails console` and tried to do a simple query `Order.all.left_joins(:remainders).group(:id).order('COUNT(remainders.id) DESC')` but it threw me **(Object doesn't support #inspect)**. Searching around I ended up [here](https://stackoverflow.com/questions/71529685/object-doesnt-support-inspect) and it worked... that's hysteric it should get more visibility!

I ended up using my debugging gem to stop an endpoint request in order to have a working console.

### Expected behavior
Running queries in the `rails console` should return data.
`Order.all.left_joins(:remainders).group(:id).order('COUNT(remainders.id) DESC')`

### Actual behavior
Running queries in the rails console throws (Object doesn't support #inspect).

### System configuration
**Ruby Version Manager version**:  rbenv 1.1.2-61-g585ed84
**System version**: Ubuntu 21.04 x86-64
**Rails version**:  rails (7.0.3.1)
**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by JohnDBR** [comment]
UPDATE: I ended up having [a string as an id reference](https://stackoverflow.com/questions/11286481/pgerror-operator-does-not-exist-character-varying-bigint) and it solved the "IRB Corruption" but the console was not able to tell me the actual error until I debugged a non-related endpoint to test my queries.

I'm going to leave the issue open because the console was not able to tell me the actual error of my query while my debugging gem did.

**Comment by skipkayhil** [comment]
Would you be able to create a sample app that can reproduce the issue? Whether the problem exists within Rails' model inspect or irb I think that would help tremendously to identity the proper fix

**Comment by skipkayhil** [comment]
(Closing the loop) the error message was improved upstream in IRB: https://github.com/ruby/irb/pull/511
