### ISSUE TITLE
Use of ActiveSupport::ForkTrace::check! in ActiveRecord::ConnectionAdapters::PoolConfig#pool causes the `getpid` syscall to be called excessively in production

### ISSUE THREAD

**Issue by dalehamel** [rails/rails#47418]
### Steps to reproduce

This occurs at scale with a large number of database shards. It is probably more severe in proportion with the number of database shards.

### Expected behavior

We should expect that connection pooling logic has minimal syscall overhead.

### Actual behavior

Connection pooling logic uses the `getpid` syscall repeatedly. In fact, in a production process, it is the highest syscall:

```
root@PRODUCTION_SERVER:/# syscount -p !$
syscount -p UNICORN_WORKER_PID
Tracing syscalls, printing top 10... Ctrl+C to quit.
^C[06:49:56]
SYSCALL                   COUNT
getpid                    38455
futex                     18081
clock_nanosleep            7575
clock_gettime              2133
sendto                     1447
read                       1293
semtimedop                 1097
recvfrom                    810
poll                        472
ppoll                       457
```

This isn't one of the only things calling it, but it is a top culprit.

In flamegraphs, see that Process.pid is one of the top frames. Here is an example showing it accounting for nearly 5 minutes of a 2 hours worth of aggregated stack traces:

![image](https://user-images.githubusercontent.com/618615/219393464-240feea7-43b3-4df9-90e1-0f66d20bb3ee.png)

Here is [that code location](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/pool_config.rb#L53-L57). 

https://github.com/rails/rails/blob/main/activesupport/lib/active_support/fork_tracker.rb#L41 seems to be the logic in question, notably we see this mention in the [patch that added this](https://github.com/rails/rails/pull/37312
) that added this:

> However just in case the fork was done inside a c-extension, there's a check! method which is recommended to be called before using database connections. And that any forking code bypassing ruby's fork method should invoke.

So i guess it is expected we need to ensure the pid is checked before a database connection in case fork happened in a native extension.

I wrote up a quick LD_PRELOAD patch that can be used I think to solve that issue, as it wraps `fork` and `getpid` so that the glibc usage gets wrapped and cached as well, but I suppose this won't be a good general solution.

Note that `getpid` used to be cached in glibc, but in newer versions the manpage adds this warning that the caching was removed:

>        Because of the aforementioned problems, since glibc version 2.25,
>       the PID cache is removed: calls to getpid() always invoke the
>      actual system call, rather than returning a cached value.

### System configuration

Linux with Glibc newer than 2.25

**Rails version**: 

08f0b74da4fc7eaa7b06fac0bf181e8922f51b0a, looks like 7.1.0 alpha

**Ruby version**:

3.2 (I think)

**Comment by casperisfine** [comment]
Ref: https://github.com/rails/rails/pull/37312
Ref: https://github.com/rails/rails/pull/37296

Normally on Ruby 3.1+, the `Process._fork` callback should be enough, the only way PID can change without it being called is via `Process.daemonize` but that really shouldn't be used.

Forking from a native extension in MRI is impossible, and would leave the Ruby VM in a broken state, so we don't have to protect for that.

So I'd say we should just not do the PID check on Ruby 3.1+.

That said, this pattern is common in client libraries (e.g. Redis, Dalli, etc), so we should probably make it faster on MRI as well.

I think lots of code out there assume the `getpid()` is cached by the libc().
