### ISSUE TITLE
Lower case HTTP headers when rails serves files

### ISSUE THREAD

**Issue by stac47** [rails/rails#47456]
### Steps to reproduce

When using Rails Edge, some HTTP headers appears like `content-type` next to `Context-Type`.
To reproduce, from a new Rails application:
```bash
% rails assets:precompile
I, [2023-02-21T17:56:19.789769 #55874]  INFO -- : Writing /Users/stac/project/public/assets/application-e908707cbd3f4136efe68dfbbecf05e37659161b146c4ac3c9d41acd50cb4b90.css
I, [2023-02-21T17:56:19.789917 #55874]  INFO -- : Writing /Users/stac/project/public/assets/application-e908707cbd3f4136efe68dfbbecf05e37659161b146c4ac3c9d41acd50cb4b90.css.gz
[...]
% RAILS_SERVE_STATIC_FILES=1 RAILS_ENV=production rails s
Rack::Server is deprecated and replaced by Rackup::Server
Rack::Handler is deprecated and replaced by Rackup::Handler
=> Booting Puma
=> Rails 7.1.0.alpha application starting in production http://0.0.0.0:3000
=> Run `bin/rails server --help` for more startup options
/Users/lstacul/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rack-3.0.4.1/lib/rack/chunked.rb:6: warning: Rack::Chunked is deprecated and will be removed in Rack 3.1
Puma starting in single mode...
* Puma version: 5.6.5 (ruby 3.1.3-p185) ("Birdie's Version")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 56239
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
```
Then we try to query the statics (for clarity I only query headers)
```bash
% curl -I http://localhost:3000/assets/application-e908707cbd3f4136efe68dfbbecf05e37659161b146c4ac3c9d41acd50cb4b90.css
HTTP/1.1 200 OK
last-modified: Tue, 21 Feb 2023 16:56:19 GMT
content-type: text/css
Content-Type: text/css
Vary: Accept-Encoding
Content-Length: 661272
```
If we accept compressed resources, we can evan have different `content-type` values:
```bash
% curl -I 'http://localhost:3000/assets/application-e908707cbd3f4136efe68dfbbecf05e37659161b146c4ac3c9d41acd50cb4b90.css' -H 'Accept: text/css,*/*;q=0.1' -H 'Accept-Encoding: gzip, deflate, br'
HTTP/1.1 200 OK
last-modified: Tue, 21 Feb 2023 16:56:19 GMT
content-type: application/x-gzip
Content-Type: text/css
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 45665
``` 

### Expected behavior
When I run the same against Rails 7.0.4.1 (stable), it does not show any lower case HTTP header.

```bash
% curl -I 'http://localhost:3000/assets/application-e908707cbd3f4136efe68dfbbecf05e37659161b146c4ac3c9d41acd50cb4b90.css' -H 'Accept: text/css,*/*;q=0.1' -H 'Accept-Encoding: gzip, deflate, br'
HTTP/1.1 200 OK
Last-Modified: Tue, 21 Feb 2023 16:56:19 GMT
Content-Type: text/css
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 45665
```

### Actual behavior

HTTP reply shows lower case header with potentially different value compared to the non-lower case counterparts. On some other cases, I can see `last-modified` header.

This can fool the browsers. For instance Chrome errors with the following message:
> Failed ro load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/x-gzip". Strict MIME type checking is enforced for module scripts per HTML spec.

### System configuration
**Rails version**: Rails 7.1.0.alpha (commit: 1bf6dc00fb350ca48cece7b96a31e828e79a8c0a (yesterday))

**Ruby version**: ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [arm64-darwin22]

**Comment by yahonda** [comment]
Does this application install rack 3? if so, would you pin rack version to 2 to see how t goes.

https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md
> Response header keys can no longer include uppercase characters.


```ruby
$ bundle info rack
  * rack (3.0.4.1)
	Summary: A modular Ruby webserver interface.
	Homepage: https://github.com/rack/rack
	Documentation: https://rubydoc.info/github/rack/rack
	Source Code: https://github.com/rack/rack
	Changelog: https://github.com/rack/rack/blob/main/CHANGELOG.md
	Bug Tracker: https://github.com/rack/rack/issues
	Path: /home/yahonda/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rack-3.0.4.1
	Reverse Dependencies:
		actionpack (7.1.0.alpha) depends on rack (>= 2.2.4)
		capybara (3.38.0) depends on rack (>= 1.6.0)
		rack-session (2.0.0) depends on rack (>= 3.0.0)
		rack-test (2.0.2) depends on rack (>= 1.3)
		rackup (2.1.0) depends on rack (>= 3)
		sprockets (4.2.0) depends on rack (>= 2.2.4, < 4)
```

**Comment by stac47** [comment]
Thanks very much for your answer! My installation was with rack 3.x. Downgrading to `2.2.6.2` fixed the problem.

**Comment by ghiculescu** [comment]
> > Response header keys can no longer include uppercase characters.

I think the bug here is that the response is sending an uppercase and a lowercase header (and in some cases they differ).

cc @ioquatix

**Comment by ioquatix** [comment]
Thanks for the good bug report, I could reproduce the issue.

**Comment by ioquatix** [comment]
```
      def serve(request, filepath, content_headers)
        original, request.path_info =
          request.path_info, ::Rack::Utils.escape_path(filepath).b

        @file_server.call(request.env).tap do |status, headers, body|
          # Omit Content-Encoding/Type/etc headers for 304 Not Modified
          if status != 304
            binding.irb
            headers.update(content_headers)
          end
        end
      ensure
        request.path_info = original
      end
```

I dropped into here, and found the headers are merged without considering case.

```
=> {"last-modified"=>"Thu, 23 Feb 2023 06:46:00 GMT", "content-type"=>"application/javascript", "content-length"=>"137"}
irb(#<ActionDispatch::FileHandler:0x0000000107e747f0>):005:0> content_headers
=> {"Content-Type"=>"application/javascript", "Vary"=>"Accept-Encoding"}
irb(#<ActionDispatch::FileHandler:0x0000000107e747f0>):006:0> 
```

**Comment by ioquatix** [comment]
Nice work team!

**Comment by ioquatix** [comment]
By the way, there will be other parts of rails that use non-normalised (mixed case) headers. The linked PR was not an attempt to address the entire problem, but just the problem outlined by this issue. I think we probably want to take a holistic approach before 7.1 (or we could wait until later, provided that mixed case headers are using the `response.headers` wrapper which performs lower case normalisation.
