### ISSUE TITLE
Update_all with join 

### ISSUE THREAD

**Issue by dawidof** [rails/rails#47540]
### Steps to reproduce

```
model Creation  < ApplicationRecord
  belongs_to: :campaign
end

class Campaign < ApplicationRecord
  has_many :creations, dependent: :destroy
end

Creation.joins(:campaign).where(details: '').update_all('details = campaigns.brief_name')
```

### Expected behavior

```
UPDATE creations
  INNER JOIN campaigns ON creations.campaign_id = campaigns.id
  SET details = campaigns.name
  WHERE creations.details = '';
```

### Actual behavior

```
Creation Update All (1.0ms)  
UPDATE "creations" 
  SET details = campaigns.name 
  WHERE "creations"."id" IN (
    SELECT "creations"."id" 
      FROM "creations"
      INNER JOIN "campaigns" ON "campaigns"."id" = "creations"."campaign_id" 
      WHERE "creations"."details" = $1)  [["details", ""]]

ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "campaigns"
LINE 1: UPDATE "creations" SET details = campaigns.brief_name WHERE ...
```

### System configuration
**Rails version**: `7.0.4.2`

**Ruby version**: `ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]`

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb please?

**Comment by BenoitMC** [comment]
I'm facing the same issue, here are the reproduction scripts using PostgreSQL and SQLite : 

[joins_update_all_pg.rb.txt](https://github.com/rails/rails/files/11157852/joins_update_all_pg.rb.txt)
[joins_update_all_sqlite.rb.txt](https://github.com/rails/rails/files/11157854/joins_update_all_sqlite.rb.txt)
