### ISSUE TITLE
Issues when editing non-default environment credentials

### ISSUE THREAD

**Issue by morgoth** [rails/rails#47570]
When I edit some other than production/development/test environment credentials file, like this:
```
EDITOR="gnome-text-editor -i" rails credentials:edit -e staging
```
It works fine, however there are 2 small issues:
1) There is a warning in console (I don't have config/environments/staging.rb)
```
config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:

  * development - set it to false
  * test - set it to false (unless you use a tool that preloads your test environment)
  * production - set it to true
```

2) There is no preview of changes on `git diff`. The diff preview works fine for development credentials changes, but here I got something like this:
```
-azmQ2iiwXhhd6x...
+O/TmR0ymILlc2vmy...
```

The editing and overall functionality is fine.

### System configuration
**Rails version**: main (7.1.0.alpha 556025d)
**Ruby version**: 3.2.1

**Comment by skipkayhil** [comment]
I looked into this, and I think both issues actually come down to not having `config/environments/staging.rb`. The `credentials:diff` commands tries to guess the Rails environment based on the name of the credentials file, but the possibilities it considers are the files in `config/environments`:

https://github.com/rails/rails/blob/20d87500a4568b175f1e06796572154a5a8d283d/railties/lib/rails/command/environment_argument.rb#L46-L49

Can I ask why you don't have the `staging.rb` file? That may help make it clear what we could improve on here

**Comment by skipkayhil** [comment]
Got it. I believe since #47148 you should be able to use `STAGE=staging bin/rails credentials:edit -e production` with your current setup to prevent warnings.

I'm not sure if I have a good answer about `credentials:diff` yet 🤔

**Comment by jonathanhefner** [comment]
Another possibility might be to add environment files that delegate to another environment.  For example:

```ruby
# config/environments/staging.rb
ENV["STAGE"] = "staging"
require_relative "production"
```

That would allow both `bin/rails credentials:edit -e staging` (without warnings) and `git diff config/credentials/staging.yml.enc`.

**Comment by morgoth** [comment]
@jonathanhefner Thanks for the tip.
I didn't try it yet, but do you know maybe if there are any side effects of running `Rails.application.configure {}` twice?

I was thinking of having `config/environments/staging.rb` with:
```
require_relative "production"
Rails.application.configure do
  # my staging overrides
end
```

**Comment by jonathanhefner** [comment]
@morgoth `Rails.application.configure` is really just an `instance_eval`:

https://github.com/rails/rails/blob/3025eaa09154f5f031f5c2e0e5b59553ff5c902b/railties/lib/rails/railtie.rb#L256-L258

So it should be good. :+1:

Thank you for testing out the new code, and thank you for the report! :smile:

**Comment by skipkayhil** [comment]
> Another possibility might be to add environment files that delegate to another environment. For example:

I figured I'd add I first learned about this pattern from this blog post: https://signalvnoise.com/posts/3535-beyond-the-default-rails-environments

I definitely found it useful for the same reasons you outlined as wanting to not have a `staging.rb` at all

**Comment by morgoth** [comment]
Thank you both. I think it would be useful to put this tip into Rails Guides, ie in this place https://edgeguides.rubyonrails.org/configuring.html#creating-rails-environments
WDYT?

**Comment by skipkayhil** [comment]
> WDYT?

Yep, that seems like a good place to expand a bit
