### ISSUE TITLE
Overridden Time.at method doesn't support `in` keyword argument

### ISSUE THREAD

**Issue by andrykonchin** [rails/rails#47586]
It's a known issue that was fixed in https://github.com/rails/rails/pull/41592.

Is the fix backporting to Rails 6.0 be accepted? It's nothing more than

```ruby
ruby2_keywords(:at_with_coercion) if respond_to?(:ruby2_keywords, true)
```

### Steps to reproduce

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'activesupport', '~> 6.0.0'
end

require 'active_support/time'

puts Time.at(946702800, 500, :nanosecond, in: 0)
```

### Expected behavior

It's expected to have Time string representation be printed:

```
2000-01-01 05:00:00 +0000
```

### Actual behavior

ArgumentError exception `wrong number of arguments (given 4, expected 1..3)` is raised instead:

```
.../.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.0.6.1/lib/active_support/core_ext/time/calculations.rb:45:in `at': wrong number of arguments (given 4, expected 1..3) (ArgumentError)
	from .../.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.0.6.1/lib/active_support/core_ext/time/calculations.rb:45:in `at_with_coercion'
```

### System configuration
**Rails version**: 6.0

**Ruby version**: 3.0

**Comment by skipkayhil** [comment]
Hey @andrykonchin, thanks for opening an issue.

The `6.0` series is only receiving severe security fixes at this point. You can find the full Maintenance Policy [here](https://guides.rubyonrails.org/maintenance_policy.html)

I highly recommend upgrading to a newer version of Rails at `6.0` will be End of Life in June.

**Comment by andrykonchin** [comment]
Thank you for your response 🙇 

Could you please point to a discussion or rationale of this policy?

**Comment by skipkayhil** [comment]
I searched but haven't found anything super definitive 😕 

It looks like the file was basically copied from this blog post: https://rubyonrails.org/2013/2/24/maintenance-policy-for-ruby-on-rails in #12171

**Comment by andrykonchin** [comment]
Thank you 🙇 

I remember there was a comment in some Rails issue with some kind of explanation several years ago.

Looks like I've found something relevant:
- https://github.com/rails/rails/issues/40938#issuecomment-751898275 and
- https://github.com/rails/rails/pull/41797#issuecomment-818289111

I would consider mentioning the main idea/rationale (provided in these comments or something similar) in the Maintenance Policy guide.

**Comment by zzak** [comment]
@andrykonchin There is a snippet I've added here:
https://edgeguides.rubyonrails.org/maintenance_policy.html#unsupported-release-series

Happy to hear any feedback on how to improve that messaging!

We could also maybe add something to the issue template that at least links to the policy page, but I have doubts on if people actually read those.

Another idea I just had was (at least for PRs) to automate a message if the base ref is an unsupported release, I think we can do that 🤔

**Comment by andrykonchin** [comment]
Thank you!
