### ISSUE TITLE
`.references` with an unknown table makes all associations to be eager loaded

### ISSUE THREAD

**Issue by blanquer** [rails/rails#47588]
### Steps to reproduce
Inside any Rails console, try out any AR query with an included association, add a `.references` with any bogus table name. 

```ruby
# From any Rails console, with SQL logging turned on

> ActiveBook.includes(:author).references(:foo).to_a; nil
```

### Expected behavior
It should either complain or ignore the invalid `:foo` table, not just continue going ahead by deciding to eager load ALL of the included  associations (which, as it happens, if it is a deep query with many nested ones, this transforms the query into a massive cartesian product of rows.

If it was to ignore such string/symbol, I'd expect the exact same behavior without the `.references(:foo)`... i.e., which in this case would preload the authors instead of eager load them

Expected preloading of authors:
```
ActiveBook Load (0.2ms)  SELECT "active_books".* FROM "active_books"
ActiveAuthor Load (0.2ms)  SELECT "active_authors".* FROM "active_authors" WHERE "active_authors"."id" IN (?, ?, ?)  [["id", 11], ["id", 22], ["id", 33]]
```

### Actual behavior
It eager loads ALL of the included associations (in this case there's only 1), instead of preloading them if available.

```
 SQL (0.2ms)  SELECT "active_books"."id" AS t0_r0, "active_books"."simple_name" AS t0_r1, "active_books"."added_column" AS t0_r2, "active_books"."category_uuid" AS t0_r3, "active_books"."author_id" AS t0_r4, "active_authors"."id" AS t1_r0, "active_authors"."name" AS t1_r1 FROM "active_books" LEFT OUTER JOIN "active_authors" ON "active_authors"."id" = "active_books"."author_id"
```
### System configuration
**Rails version**: ActiveRecord 6.1.7.1
**Ruby version**: 3.1.1

**Comment by eileencodes** [comment]
Hi @blanquer can you provide a reproduction using  our [bug report templates](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb)? It makes it easier for us to debug and test against other versions of Rails.

**Comment by blanquer** [comment]
Sure, here you go:
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!

    # Normal preloading of comments in a second query
    good = Post.includes(:comments).to_sql
    assert_equal true, good !~ /comments/


    bad = Post.includes(:comments).references(:foobar).to_sql
    puts "This shouldn't be eagerloaded:\n #{bad}"
    assert_equal true, bad !~ /comments/
  end
end
```

the test is not gonna win any awards, but it does fail if it eagerloads so it is usable against different versions.

**Comment by nickborromeo** [comment]
Is the use of `references` with `includes` valid without a condition? 

The docs say 
> Use to indicate that the given table_names are referenced by an SQL string, and should therefore be JOINed in any query rather than loaded separately. This method only works in conjunction with [includes](dfile:///Users/nickborromeo/Library/Application%20Support/Dash/DocSets/Ruby_on_Rails_7/Ruby%20on%20Rails.docset/Contents/Resources/Documents/api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-includes).

When used with a condition, it will fail with an `ActiveRecord::InvalidStatement` error 

```
Post.includes(:comments).where("foo.column = 1").references(:foo)

D, [2023-03-18T18:05:39.565356 #53048] DEBUG -- :   SQL (0.1ms)  SELECT DISTINCT "posts"."id" FROM "posts" LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id" WHERE (foo.column = 1) /* loading for pp */ LIMIT ?  [["LIMIT", 11]]
#<ActiveRecord::StatementInvalid: SQLite3::SQLException: no such column: foo.column> rescued during inspection
```

There are also existing tests that ensures `EagerLoadPolymorphicError` is raised 

https://github.com/rails/rails/blob/05c3f84a511663cfef265834efb7ad8d3e472682/activerecord/test/cases/associations/join_model_test.rb#L369-L371

All that being said, I think there is still something that can be improved here because it seems like it does not have to be a _valid_ table in the reference call for the query to work 

```
Post.includes(:comments).where("comments.body = 'hello'").references(:foo)

D, [2023-03-18T18:10:23.288356 #53048] DEBUG -- :   SQL (0.4ms)  SELECT DISTINCT "posts"."id" FROM "posts" LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id" WHERE (comments.body = 'hello') /* loading for pp */ LIMIT ?  [["LIMIT", 11]]

D, [2023-03-18T18:10:23.290302 #53048] DEBUG -- :   SQL (0.1ms)  SELECT "posts"."id" AS t0_r0, "comments"."id" AS t1_r0, "comments"."post_id" AS t1_r1, "comments"."body" AS t1_r2 FROM "posts" LEFT OUTER JOIN "comments" ON "comments"."post_id" = "posts"."id" WHERE (comments.body = 'hello') AND "posts"."id" = ? /* loading for pp */  [["id", 1]]

[#<Post:0x000000011955d718 id: 1>]
```

**Comment by blanquer** [comment]
Sure, maybe it raises if you have a where clause that tries to use the same table name (even if it's bogus).
The problem, in my opinion, is that if you use a `.references` with a bogus table name (regardless if you have a where clause or not), it should a) fail outright, or b) at the very least, it should not change the query plan to sudenly eager load ALL includes!.

This silent behavior of not failing and changing the query to join all existing includes is very surprising, and has a massive performance implication impact.

When you're crafting queries by hand, this situation is a little more unlikely cause you might see if if you're paying attention, but when you're doing it programmatically it is a much more difficult case to catch...even if it is just by quoting the table name slightly wrong as a string.

I guess what I'd ask is that an invalid `.references` table either just raises, or if somehow you guys think it is better to ignore it, then we need to make sure it actually ignores it fully and does not change the query to then fully eager load all existing tables in the `includes` set. i.e., the principle of least surprise.
