### ISSUE TITLE
if_exists on drop_table migration command does not make migration reversible

### ISSUE THREAD

**Issue by dmilburn** [rails/rails#47614]
### Steps to reproduce

- Create a migration to drop a table and include the `if_exists: true` argument
like:
```
  def change
    drop_table :table_name, if_exists: true
  end
```
- Run the migration forward
- Attempt to rollback the migration

### Expected behavior

Based on the error message `To avoid mistakes, drop_table is only reversible if given options or a block (can be empty).` when the migration looked like:
```
  def change
    drop_table :table_name
  end
```
I would have expected `if_exists: true` to make the migration reversible. It does run successfully going forward.

### Actual behavior

Instead, when rolling back, I got `Unknown key: :if_exists. Valid keys are: :temporary, :if_not_exists, :options, :as, :comment, :charset, :collation, :limit, :default, :precision, :unsigned`

### System configuration
**Rails version**: Rails 7.1.0.alpha.31f5cb18fa

**Ruby version**:  ruby 3.2.1

**Comment by eileencodes** [comment]
Hrm I'm not sure what we should do here, because technically `if_exists: true` wouldn't apply to the reverse of `drop_table` - it'd be `create_table` and you'd never want `create_table :table_name, if_exists: true`. The two choices are:

1) Delete the `if_exists: true` option when running a reverse. (and drop `if_not_exists: true` when reversing a `create_table`.
2) Replace the option with the opposite where `if_exits: true` on a reverse becomes `if_not_exists: true`.

I think 1 is the more correct answer if anyone wants to work on this.

**Comment by matthewd** [comment]
> I think 1 is the more correct answer

Yeah, I think we should also ignore it specifically for that "To avoid mistakes" check -- as an option, it certainly does nothing to improve reversibility, nor to explicitly opt in to "if you have to recreate the table, just make it empty" as the empty-block case seems to intend.

**Comment by zzak** [comment]
This should be fixed in main with #47616, @dmilburn can you confirm? :pray:

**Comment by nickborromeo** [comment]
Tested this using the migration script and got the following results


```
[1] pry(#<BugTest>)> ChangeAmountToAddScale.migrate(:up)
==  ChangeAmountToAddScale: migrating =========================================
-- drop_table(:payments, {:if_exists=>true})
D, [2023-03-31T00:46:48.504848 #22363] DEBUG -- :    (2.2ms)  DROP TABLE IF EXISTS "payments"
   -> 0.0029s
==  ChangeAmountToAddScale: migrated (0.0031s) ================================

=> nil
[2] pry(#<BugTest>)> ChangeAmountToAddScale.migrate(:down)
==  ChangeAmountToAddScale: reverting =========================================
-- create_table(:payments)
D, [2023-03-31T00:46:54.570165 #22363] DEBUG -- :    (0.3ms)  CREATE TABLE "payments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)
   -> 0.0020s
==  ChangeAmountToAddScale: reverted (0.0087s) ================================

=> nil
```

however when running the drop table migration, it seems idempotent 

```
[4] pry(#<BugTest>)> ChangeAmountToAddScale.migrate(:up)
==  ChangeAmountToAddScale: migrating =========================================
-- drop_table(:payments, {:if_exists=>true})
D, [2023-03-31T00:47:05.241782 #22363] DEBUG -- :    (0.6ms)  DROP TABLE IF EXISTS "payments"
   -> 0.0015s
==  ChangeAmountToAddScale: migrated (0.0016s) ================================

=> nil
[5] pry(#<BugTest>)> ChangeAmountToAddScale.migrate(:up)
==  ChangeAmountToAddScale: migrating =========================================
-- drop_table(:payments, {:if_exists=>true})
D, [2023-03-31T00:48:32.472151 #22363] DEBUG -- :    (0.7ms)  DROP TABLE IF EXISTS "payments"
   -> 0.0013s
==  ChangeAmountToAddScale: migrated (0.0015s) ================================

=> nil
[6] pry(#<BugTest>)> ChangeAmountToAddScale.migrate(:up)
==  ChangeAmountToAddScale: migrating =========================================
-- drop_table(:payments, {:if_exists=>true})
D, [2023-03-31T00:48:33.587084 #22363] DEBUG -- :    (0.1ms)  DROP TABLE IF EXISTS "payments"
   -> 0.0003s
==  ChangeAmountToAddScale: migrated (0.0004s) ================================

=> nil
```

and while the reverse is not true which I think is correct, but wanted to confirm


```
[7] pry(#<BugTest>)> ChangeAmountToAddScale.migrate(:down)
==  ChangeAmountToAddScale: reverting =========================================
-- create_table(:payments)
D, [2023-03-31T00:49:17.860991 #22363] DEBUG -- :    (0.5ms)  CREATE TABLE "payments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)
   -> 0.0016s
==  ChangeAmountToAddScale: reverted (0.0022s) ================================

=> nil
[8] pry(#<BugTest>)> ChangeAmountToAddScale.migrate(:down)
==  ChangeAmountToAddScale: reverting =========================================
-- create_table(:payments)
D, [2023-03-31T00:49:19.461018 #22363] DEBUG -- :    (2.8ms)  CREATE TABLE "payments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL)
ActiveRecord::StatementInvalid: SQLite3::SQLException: table "payments" already exists
from /Users/nickborromeo/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/sqlite3-1.6.2-arm64-darwin/lib/sqlite3/database.rb:152:in `initialize'
Caused by SQLite3::SQLException: table "payments" already exists
from /Users/nickborromeo/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/sqlite3-1.6.2-arm64-darwin/lib/sqlite3/database.rb:152:in `initialize'
```

**Comment by eileencodes** [comment]
In all the `up` cases `if_exists` or `if_not_exists` will be applied so you can run up over and over again. With `down` you can't unless you write your own down to use the correct argument. We decided against automatically applying the opposite option on `down` because that's potentially not desired. Looks like this is fixed though so I'm going to close this. If something is still broken, let's open a new issue.

**Comment by dmilburn** [comment]
Apologies i was slow to test this, thanks for getting the fix in!
