### ISSUE TITLE
Querying deterministically encrypted attributes with multiple values is not returning results

### ISSUE THREAD

**Issue by cover** [rails/rails#47626]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Encryption.configure(
  support_unencrypted_data: true,
  extend_queries: true,
  primary_key: SecureRandom.alphanumeric(32),
  deterministic_key: SecureRandom.alphanumeric(32),
  key_derivation_salt: SecureRandom.alphanumeric(32),
)

ActiveRecord::Encryption::ExtendedDeterministicUniquenessValidator.install_support

ActiveRecord::Schema.define do
  create_table :people, force: true do |t|
    t.string :email
  end
end

class Person < ActiveRecord::Base
  encrypts :email, deterministic: true, downcase: true
end

class BugTest < Minitest::Test
  def test_bug
    person1 = Person.create!(email: "email@example.com")
    person2 = Person.create!(email: "email2@example.com")
    
    # Works
    assert_includes Person.where(email: 'email@example.com'), person1
    assert_includes Person.where(email: ['email@example.com']), person1

    # Doesn't work
    assert_includes Person.where(email: ['email@example.com', 'a']), person1
    assert_includes Person.where(email: ['email@example.com', 'email2@example.com']), person1
    assert_includes Person.where(email: ['email@example.com', 'email2@example.com']), person2
  end
end
```

### Expected behavior

When searching multiple records using encrypted attributes it should return all those that exist. The query from `to_sql` looks right (it's using `IN`) and I've confirmed that running it directly on the database (postgres) it returns the results, but it doesn't when it's run through ActiveRecord, from the log it seems that it's running a completely different query:

```
irb(main):047:0> Person.where(email: ['email@example.com', 'a'])
D, [2023-03-10T00:54:10.481192 #450648] DEBUG -- :   Person Load (0.2ms)  SELECT "people".* FROM "people" WHERE "people"."email" IN (?, ?) /* loading for pp */ LIMIT ?  [["email", "{\"p\":\"F89sxJnKi3ytvfNlzg56MsPNDPLpdEKUHkH/nkQEZPy4qBZlCXPwDYNTfFoiwcMlSkF1Py+6aAw2xFogmpMVigdN/r40j409t2GDdzFZQhAGAoHL8YtSEUCFZucabw==\",\"h\":{\"iv\":\"DJnykq2QgoKIBO7j\",\"at\":\"aCbCGgCGPsafYA9yRKPgDQ==\"}}"], ["email", "{\"p\":\"DZjNWfF/eQCWvA0R9e+O0gEhzDSUULyMON6qXPxjx0jCwBXE6R/U+4QbTaCiEj6HiKAHzS5/fQqYSzFCZIYmwgZlY5xxokSuOZk=\",\"h\":{\"iv\":\"LzQK4NBask34gywl\",\"at\":\"q9FLX48PW9+CjvATrfjyXQ==\"}}"], ["LIMIT", 11]]
=> []

irb(main):048:0> Person.where(email: ['email@example.com', 'a']).to_sql
=> "SELECT \"people\".* FROM \"people\" WHERE \"people\".\"email\" IN ('{\"p\":\"6LrM4lDU+4kNWj/0CV9NUjM=\",\"h\":{\"iv\":\"2lunFHgjAy+nVwIe\",\"at\":\"Rofc1vJyOUHQ8WNF1pG+tw==\"}}', '{\"p\":\"Xw==\",\"h\":{\"iv\":\"UCmojhSRztEcgnvr\",\"at\":\"y8g/2E3eBt1QMctLUdTQcw==\"}}')"
```

### Actual behavior

It returns an empty array instead of the existing records

### System configuration
**Rails version**: 7.0.4.2 (also confirmed on `main`)

**Ruby version**: 3.2.1

**Comment by aj-abhishek-jadav** [comment]
@cover,
This is because original values (i.e `['email@example.com', 'a']`) are being serialized twice.
1 time from [visit_Arel_Nodes_HomogeneousIn](https://github.com/rails/rails/blob/main/activerecord/lib/arel/visitors/to_sql.rb#L344) -> [casted_values](https://github.com/rails/rails/blob/main/activerecord/lib/arel/nodes/homogeneous_in.rb#L43)
2 time from [type_casted_binds](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L239) -> [_value_for_database](https://github.com/rails/rails/blame/main/activemodel/lib/active_model/attribute.rb#L166)

need to skip serialization when `type` is instance of `ActiveRecord::Encryption::EncryptedAttributeType` when called from `visit_Arel_Nodes_HomogeneousIn -> casted_values`

@dhh @tenderlove @rafaelfranca @fxn @kaspth @eileencodes @josevalim Guys need your suggestion here

**Comment by eileencodes** [comment]
@aj-abhishek-jadav please don't cc random contributors on issues, half the people on your list are no longer maintainers.

**Comment by aj-abhishek-jadav** [comment]
> @aj-abhishek-jadav please don't cc random contributors on issues, half the people on your list are no longer maintainers.

I was unaware of that. 
Apologies.

**Comment by cover** [comment]
Closing as it was caused by not having enabled the `extend_queries`
