### ISSUE TITLE
`delegate` to Module does not work when using an implicit block.

### ISSUE THREAD

**Issue by lsylvester** [rails/rails#47624]
When delegating a method with `delegate` to a Module, if the method doesn't take a block param but calls `yield` to call an implicit block - then the block is no longer available.

I think that this was introduced in #46875.

One option would be always have a block param on the method defined by  `delegate`, but with my benchmarks based on the original PR - this makes it about 1.1 times slower (this is still faster than the previous implementation). I am unsure if there are other approaches that could be used that wouldn't have the performance penalty. 

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activestorage", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/module/delegation"
require "minitest/autorun"
require "active_support/testing/assertions"

class Foo
  def self.implicit_block
    yield
  end
end

class Bar
  delegate :implicit_block, to: Foo
end

class BugTest < Minitest::Test
  include ActiveSupport::Testing::Assertions

  def test_implicit_block
    Bar.new.implicit_block{ }
  end
end

```

### Expected behavior

The block should be yielded to.

### Actual behavior

```
  1) Error:
BugTest#test_implicit_block:
LocalJumpError: no block given (yield)
    bug.rb:20:in `implicit_block'
    bug.rb:25:in `implicit_block'
    bug.rb:32:in `test_implicit_block'
<!-- Tell us what happens instead -->
```

### System configuration
**Rails version**: main

**Ruby version**: 3.2.1

**Comment by skipkayhil** [comment]
I bisected and can confirm that 8b2f57d is the first failing commit.

@amatsuda would you mind taking a look?

**Comment by amatsuda** [comment]
Oh, sure. I'll take a look soon!
