### ISSUE TITLE
[Documentation] Continued Tutorial Series? Starting from the primary guide at: https://guides.rubyonrails.org/getting_started.html

### ISSUE THREAD

**Issue by rubyFeedback** [rails/rails#47645]
The guide at https://guides.rubyonrails.org/getting_started.html is of a rather high quality. It gives
people an entry point to rails. I was able to model and adapt quite a few things to my own use
case.

Perhaps I should briefly explain my use case, so that this can be put in context.

I have been using ruby since many years, so I do not consider myself to be a newcomer; neither
a "true" expert". More of a medium skillset here.

I have also been using ruby on the world wide web, that is, mostly .cgi files, and also sinatra. I
also read through rails tutorials in the past, but after some time my brain loses motivation
quickly (in general, by the way, not just rails specific; I have the attention span of a squirrel
on a nut rush - see the three squirrel maze youtube videos for that).

So, as I get adjusted to rails (again, or hopefully finally), one decision I made some time ago
is that I want to interconnect ALL the different web-related dataset that I have. I have a very
large local knowledge base about tons of stuff, personal, science-related, hobby, fun. So my
idea here was to have ONE huge monolithic rails applications ON TOP OF IT ALL that can
manage this, but one that can be flexible, so that I can also have smaller individual applications
here, that also have output that is related to the world wide web.

Coming from this point of view, I would love to have a SLIGHTLY more advanced tutorial that
would be RECOMMENDED by the rails folks, and that can also be OFFICIAL, linked in from
the main guide at:

https://guides.rubyonrails.org/getting_started.html

Somewhere near the end.

Now there are external resources, I get that, and there are books, I get that, but from experience
it always seems to work better when good, high quality documentation is gathered in ONE
place. I learned this in sinatra already - external websites tend to vanish, or become outdated,
and don't get updated in many years. So I would like to convince the rails folks to host an
add-on tutorial on the main page too.

I am not saying this should be catering to my use cases only! The advanced tutorial can
explore different, wild topics. It should be, in style and perhaps length, similar to the 
primary tutorial (e. g. the guides.rubyonrails.org/getting_started.html page).

What should it then cover?

Well. Perhaps it can cover more advanced use cases in general.

Just as ONE example, right now I am thinking how I could interconnect different ruby
classes which will generate output (a string), to then display in rails too. I suppose I
can simply repurposes the routes, similar to sinatra (since we all seem to be using
rack), but even then I am not entirely certain where to put things. Perhaps in some weeks
this will all become super-clear to me, but right now I'd love an advanced tutorial that
would make it easier to get a head-start in regards to advanced rails stuff. Perhaps
even fancy effects too, or like "how to embed the snakes game" and such use cases.
They should not be too long, but not too trivial either.

Anyway, I end this here. Please feel free to close this issue request for whatever reason;
it's not extremely important, but if there is anyone who ever feels like extending the
documentation, I would really appreciate a similar tutorial-style, like the getting started.
For starting people I think this is the best way to work, followed by working examples
that are documented.

**Comment by skipkayhil** [comment]
Hey @rubyFeedback, thank you for opening an issue

We reserve the issue tracker for bugs only, so I'm going to have to close this. However, PRs are always welcome!

**Comment by AmandaPerino** [comment]
Hi @rubyFeedback just a quick note to say that this is work that the Rails Foundation will be planning in the coming years. No solid plans yet, but it is in the roadmap. So thanks for your feedback!
