### ISSUE TITLE
Uncaught request-level errors should be logged as :error, not :fatal

### ISSUE THREAD

**Issue by jakerobb** [rails/rails#47643]
### Steps to reproduce
Allow a raised error to propagate uncaught from your ActionController.

### Actual behavior
The logged error has severity `:fatal`.

### Expected behavior
The logged error should have severity `:error`.

### Justification
The Ruby [documentation on log severities](https://ruby-doc.org/3.2.1/stdlibs/logger/Logger/Severity.html) is clear: `:fatal` means "An unhandleable error that results in a program crash." The naming is logical; a fatal event leads to (process) death. By this definition, if my webserver process continues to run, then it didn't "die", and `:fatal` was not justified. 

This exact definition of `:fatal` has existed unchanged (aside from capitalizing the sentence and adding a period in 2.0.0) in Ruby's documentation since at least [version 1.8.6 in 2007](https://ruby-doc.org/stdlib-1.8.6/libdoc/logger/rdoc/Logger.html) (that's the earliest version available at ruby-doc.org; I didn't dig further). It is also consistent with log level definitions across many other language ecosystems:

| Language / Framework | Highest Severity | Definition |
| ------------- | ------------- | ------------- |
| Java / Log4J  | [FATAL](https://logging.apache.org/log4j/2.x/javadoc/log4j-api/index.html) | A fatal event that will prevent the application from continuing. |
| Go | [Fatal](https://pkg.go.dev/log#Fatal) | No definition, but logging a message at this level _literally causes the program to exit._ |
| C# | [Critical](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel?view=dotnet-plat-ext-7.0) | Logs that describe an unrecoverable application or system crash, or a catastrophic failure that requires immediate attention. |
| Swift | [Critical](https://apple.github.io/swift-log/docs/current/Logging/Structs/Logger/Level.html#/s:7Logging6LoggerV5LevelO8criticalyA2EmF) | Appropriate for critical error conditions that usually require immediate attention. <br><br> [Elsewhere](https://www.swift.org/server/guides/libraries/log-levels.html) in the documentation; they note that this log level is likely to cause someone to be paged immediately. |

This interpretation of "fatal" also extends to language-agnostic tools. For one example, when a log of this level is ingested into DataDog, their system labels the entry **EMERGENCY** (their highest severity level; a reasonable translation of `:fatal` IMO). I think most web application operators would agree that a single failed request falls well short of an emergency.

Calling an isolated web request failure an "emergency" or "fatal" is akin to calling the police or an ambulance because the post office delivered your neighbor's mail to your mailbox. It's an error, but not an emergency, and it's certainly not fatal! Nobody needs to be paged. (A sudden onset of _many/most/all_ requests failing in this way probably warrants a page, but that's not Rails' job.)

### Concessions

Rails has logged request errors as `:fatal`, with a comment saying that you could overwrite the method if desired, [since @dhh's original commit in 2004](https://github.com/rails/rails/commit/db045dbbf60b53dbe013ef25554fd013baf88134#diff-c20582338b99111554f3604ad2e87e5723a2304431e978ddc79eaa7967982b3dR29-R40). This decision has persisted through several renames and refactors as Rails has matured. Today, the comment suggesting overwrite is no longer present in the DebugExceptions middleware, [where the code in question lives today](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L150-L158).

19 years of history (not to mention the founder's original intent) is a lot to go against. I therefore suggest that the level should be made configurable, and the default should remain `:fatal` for the time being. I would strongly consider changing the default with Rails 8.0.

To be clear, I know that I can subclass `DebugExceptions`, overwrite `#log_array` with my own implementation, and swap it in, but there is more logic in that method than just selection of the log level. I don't want to have to maintain my overwritten method to stay consistent with whatever other logic is included in that method as I upgrade to each successive Rails version. It's also a private method, and you are under no obligation to maintain it as an API, which means that any upgrade could completely or partially break my overwrite with no indication of that in the release notes. `#log_array` does not feel like something I _should_ overwrite.

### System configuration
**Rails version**: 7.0.4.2 (but it doesn't matter; this is true of literally every version ever)

**Ruby version**: 3.2.1 (again, doesn't matter)

**Comment by zzak** [comment]
Thank you for the detailed report.

Generally we don't accept feature requests in the issue tracker, the preference is to post in [discuss](https://discuss.rubyonrails.org) or [discord](https://rubyonrails.org/2022/6/13/rails-discord-server-is-now-open-to-the-public).

That said, if you're interested in contributing a patch, those tend to get more traction since it's easier to see the impact of a given change with a diff. But I don't want to suggest you work on something that might not get accepted. :pray:
