### ISSUE TITLE
NameError:   uninitialized constant Concurrent::Concern::Logging::Logger

### ISSUE THREAD

**Issue by nolyoi** [rails/rails#47678]
I'm trying to get rspec set up on a sinatra app and I keep running into an odd error when the app tries loading activesupport. Oddly, this doesn't occur when loading my app to run normally, only when running rspec. I'm not quite sure if the problem is myself, activesupport, or rspec. I'm guessing it's me so hopefully I can find some insight here. :P

### Steps to reproduce
Create a sinatra app. Install activesupport and rspec. When running rspec, there is a NameError at the line `require 'active_support'` or `Bundler.require(:default, ENV['RACK_ENV'])`.

### Expected behavior
No error should be thrown.

### Actual behavior
`NameError:   uninitialized constant Concurrent::Concern::Logging::Logger`

### System configuration
**Rails version**: Sinatra

**Ruby version**: 3.2.1

**Comment by skipkayhil** [comment]
Hey @nolyoi, thanks for opening an issue.

Can you provide a sample repo where you can reproduce the problem? (Also please specify the version of Active Support you are using)

**Comment by eileencodes** [comment]
`Concurrent::Concern::Logging::Logger` doesn't come from Active Support. It's from [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent-ruby/concurrent/concern/logging.rb).

**Comment by nolyoi** [comment]
> `Concurrent::Concern::Logging::Logger` doesn't come from Active Support. It's from [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent-ruby/concurrent/concern/logging.rb) which is included in Active Support but I don't see us using the logging (unless that's from an older version). I suspect the bug is in your app or another gem you're using.

the backtrace points to active_support require. here's the full backtrace:

```
An error occurred while loading ./spec/operations/test_spec.rb.
Failure/Error: require './config/environment'

NameError:
  uninitialized constant Concurrent::Concern::Logging::Logger
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/concern/logging.rb:11:in `<module:Logging>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/concern/logging.rb:10:in `<module:Concern>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/concern/logging.rb:5:in `<module:Concurrent>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/concern/logging.rb:4:in `<top (required)>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/concern/deprecation.rb:1:in `<top (required)>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/abstract_executor_service.rb:2:in `<top (required)>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/immediate_executor.rb:2:in `<top (required)>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/delay.rb:3:in `<top (required)>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/configuration.rb:2:in `<top (required)>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent.rb:4:in `<top (required)>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/logger_thread_safe_level.rb:5:in `<top (required)>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/logger_silence.rb:5:in `<top (required)>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/logger.rb:3:in `<top (required)>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support.rb:29:in `<top (required)>'
# ./config/initializers/active_support.rb:1:in `<top (required)>'
# ./config/environment.rb:17:in `require_relative'
# ./config/environment.rb:17:in `<top (required)>'
# ./spec/spec_helper.rb:2:in `<top (required)>'
# ./spec/app_helper.rb:6:in `<top (required)>'
# ./spec/operations/test_spec.rb:1:in `<top (required)>'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.1/lib/rspec/core/configuration.rb:2117:in `load'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.1/lib/rspec/core/configuration.rb:2117:in `load_file_handling_errors'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.1/lib/rspec/core/configuration.rb:1617:in `block in load_spec_files'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.1/lib/rspec/core/configuration.rb:1615:in `each'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.1/lib/rspec/core/configuration.rb:1615:in `load_spec_files'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.1/lib/rspec/core/runner.rb:102:in `setup'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.1/lib/rspec/core/runner.rb:86:in `run'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.1/lib/rspec/core/runner.rb:71:in `run'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.1/lib/rspec/core/runner.rb:45:in `invoke'
# /Users/nolan/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.1/exe/rspec:4:in `<top (required)>'
# /Users/nolan/.rbenv/versions/3.2.1/bin/rspec:25:in `load'
# /Users/nolan/.rbenv/versions/3.2.1/bin/rspec:25:in `<main>'
No examples found.
```

**Comment by nolyoi** [comment]
> Hey @nolyoi, thanks for opening an issue.
> 
> Can you provide a sample repo where you can reproduce the problem? (Also please specify the version of Active Support you are using)

yeah I'll try to get one spun up tonight.

**Comment by skipkayhil** [comment]
Looking at the stack, the only thing I can think of is your `logger` gem isn't providing the `Logger` constant somehow. 

`concurrent-ruby` has `require "logger"` at the top of that file so I would expect it to be defined.

**Comment by nolyoi** [comment]
> bundle open logger

huh weird, I get an empty file there.

![Screenshot 2023-03-17 at 4 25 07 AM](https://user-images.githubusercontent.com/59351042/225865234-6ca1d334-9c31-413e-a3e7-169d6e04423d.png)

**Comment by skipkayhil** [comment]
Going to close as it sounds like this is not an issue with Rails. I definitely recommend reinstalling the logger gem, and potentially your Ruby if needed.
