### ISSUE TITLE
[ActiveSupport::Inflector] Acronyms preceded by digits behave differently in `camelize` and `underscore`

### ISSUE THREAD

**Issue by b-loyola** [rails/rails#47740]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "activesupport", "~> 7.0.0"
end

require "active_support"
require "active_support/inflector"
require "minitest/autorun"

class BugTest < Minitest::Test
  def setup
    ActiveSupport::Inflector.inflections(:en) do |inflect|
      inflect.acronym("HTTP")
    end
  end

  def test_camelize_and_underscore_acronym
    assert_equal "http", "HTTP".underscore
    assert_equal "HTTP", "http".camelize
    assert_equal "http_one", "HTTPOne".underscore
    assert_equal "HTTPOne", "http_one".camelize
    assert_equal "http1.1", "HTTP1.1".underscore
    assert_equal "HTTP1.1", "http1.1".camelize
  end
end
```

### Expected behavior

Should acronyms followed by numbers be considered their own words for `camelize` in the same way they are for `underscore`? The `underscore` method seems to transform `HTTP1` to `http1` and `HTTPOne` to `http_one`, seemingly recognizing the acronym regardless of the character that follows it, whereas `camelize` will consider digits as part of the same word for acronyms, failing to recognize the `HTTP` acronym when followed by digits. Perhaps the behaviour should be consistent?

I know there is some reluctance to change inflections "to avoid breaking legacy applications which may be relying on errant inflections" but perhaps this could be done through an inflector option and/or configuration so that we can fix things like these while allowing previous errant inflections with default configuration?

I'd be happy to work on something like this, but wanted to check first if it would be acceptable.

E.g.:
```ruby
ActiveSupport::Inflector.configure do |config|
  config.camelize_with_digits = false # defaults to `true`
end

ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym("HTTP")
end

"http1.1".camelize
#=> "HTTP1.1"
```

### Actual behavior
```
  1) Failure:
BugTest#test_camelize_and_underscore_acronym [test_inflection.rb:30]:
Expected: "HTTP1.1"
  Actual: "Http1.1"

1 runs, 6 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**: `Using activesupport 7.0.4.3`

**Ruby version**: `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin20]`

**Comment by dorianmariefr** [comment]
I don't think the inflector is going to change because of backward compatibility like you mention.

I kinda have a patch for this but it breaks at least one test:

```diff
diff --git a/activesupport/lib/active_support/inflector/methods.rb b/activesupport/lib/active_support/inflector/methods.rb
index 0ee91fe08f..316f4f41ca 100644
--- a/activesupport/lib/active_support/inflector/methods.rb
+++ b/activesupport/lib/active_support/inflector/methods.rb
@@ -70,12 +70,12 @@ def camelize(term, uppercase_first_letter = true)
       # String#camelize takes a symbol (:upper or :lower), so here we also support :lower to keep the methods consistent.
       if !uppercase_first_letter || uppercase_first_letter == :lower
         string = string.sub(inflections.acronyms_camelize_regex) { |match| match.downcase! || match }
-      elsif string.match?(/\A[a-z\d]*\z/)
+      elsif string.match?(/\A[a-z]*\z/)
         return inflections.acronyms[string] || string.capitalize
       else
-        string = string.sub(/^[a-z\d]*/) { |match| inflections.acronyms[match] || match.capitalize! || match }
+        string = string.sub(/^[a-z]*/) { |match| inflections.acronyms[match] || match.capitalize! || match }
       end
-      string.gsub!(/(?:_|(\/))([a-z\d]*)/i) do
+      string.gsub!(/(?:_|(\/))([a-z]*)/i) do
         word = $2
         substituted = inflections.acronyms[word] || word.capitalize! || word
         $1 ? "::#{substituted}" : substituted
diff --git a/activesupport/test/inflector_test.rb b/activesupport/test/inflector_test.rb
index 7814326e00..de13f5e2c9 100644
--- a/activesupport/test/inflector_test.rb
+++ b/activesupport/test/inflector_test.rb
@@ -209,6 +209,7 @@ def test_acronyms
       ["HTTP::RESTful",     "http/restful",       "HTTP/RESTful",       "HTTP/RESTful"],
       ["HTTP::RESTfulAPI",  "http/restful_api",   "HTTP/RESTful API",   "HTTP/RESTful API"],
       ["APIRESTful",        "api_restful",        "API RESTful",        "API RESTful"],
+      ["HTTP1.1",           "http1.1",            "HTTP1.1",            "HTTP1.1"],
 
       # misdirection
       ["Capistrano",        "capistrano",         "Capistrano",       "Capistrano"],
```

```
Failure:
InflectorTest#test_acronyms [/Users/dorianmariefr/src/github/rails/activesupport/test/inflector_test.rb:222]:
Expected: "IHeartW3C"
  Actual: "IHeartW3c"
```

To me, the solution is adding an inflection on `HTTP1` which doesn't seem too bad.

```ruby
inflect.acronym("HTTP1")
```

**Comment by b-loyola** [comment]
Thanks @dorianmariefr 
To give some context, we have some acronyms in our codebase which are always followed by numbers, but the list of numbers is almost infinite.
The change you have above is the exact monkey patch we have right now to fix this.

I was thinking that to avoid issues with backwards compatibility, the regex could change depending on a setting passed to the inflector (as a configuration). So by default it would still use the old regex, avoiding any backwards compatibility issues, but users who might want the new behaviour could opt-in by passing configuring the inflector with the new option.

**Comment by dorianmariefr** [comment]
Does this look good

<img width="652" alt="Screenshot 2023-06-27 at 10 12 59" src="https://github.com/rails/rails/assets/58794487/6338c0f2-727a-4a3f-912a-6a55daa43c4c">
 to you?

**Comment by b-loyola** [comment]
@dorianmariefr yeah that looks perfect, but I think that would be a breaking change right? So I think it would have to be opt-in via some option/configuration to be considered here?

**Comment by zzak** [comment]
I think it will be very hard to convince merging an optional configuration to the inflector, unless I'm mistaken there aren't many if at all. Most of the methods use arguments to modify the behavior, and it's probably safe to assume `camelize` and `underscore` are intended to be used with Ruby code and you can't have decimals in Ruby variables, because the `.` operator has significant meaning.
