### ISSUE TITLE
Transactions not working as expected with many actions inside

### ISSUE THREAD

**Issue by BlinovA25** [rails/rails#47759]
### Steps to reproduce

This bug is more about behavior of system using transactions and it can be caused by rails issue or some Heroku stuff. Described below actions(on screenshots) are surrounded by one ActiveRecord::Base.transaction block.

```Ruby
# updater.rb

ActiveRecord::Base.transaction do
    params[:obj_list].each do |obj|
        updater = ObjUpdater.new(some_params)
        updater.update(insert_list, delete_list)
    end
end
``` 

```Ruby
# obj_updater.rb

def update(insert_list, delete_list)
    insert_list.each do
        # somewhere here we started seeing own transactions for INSERT action
        create!(some_params)
    end

    delete_list.each do
        update!(deleted_at: DateTime.now)
    end
end
``` 

### Expected behavior
If you have one big transaction and have many actions(inserts and updates used without their own explicitly declared transactions) you expect that all changes inside the transaction will be rollbacked in case you raise the error. 

<img width="1434" alt="Снимок экрана 2023-03-23 в 19 13 01" src="https://user-images.githubusercontent.com/70841471/227266709-8a1ace87-1bf9-4bfe-acb8-0787d2c79514.png">

### Actual behavior
The described behavior works fine with a couple of actions, but after a lot of actions, the system automatically surrounds each new INSERT and UPDATE DB log with its own transaction logs:

<img width="1432" alt="Снимок экрана 2023-03-23 в 19 08 39" src="https://user-images.githubusercontent.com/70841471/227266727-057531e1-a1aa-4d6e-9f43-da50a66d44cf.png">

As a result rollback functionality doesn't works properly(system doesn't rollbacks all actions that have their own transaction).

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.6.6

**PostgreSQL version**: 14

**Hosting**: Heroku

**Comment by dorianmariefr** [comment]
Could you provide a test case reproducing the issue?

Maybe `create` or `update` sometimes creates a new transaction
