### ISSUE TITLE
Case Insensitive Unique Indexes

### ISSUE THREAD

**Issue by softwaregravy** [rails/rails#47769]
Unless this exists and I can't find it, this is a feature proposal/discussion.

I'm currently writing a migration and I'd like to end up with a case-insensitive unique index on a string column. The purpose is to mirror/enforce the following validation in the db:

```ruby
validates :name, uniqueness: {case_sensitive: false}
``` 

Using `postgres`, it would look like this:

```SQL
CREATE UNIQUE INDEX index_name ON table_name (UPPER(column_name));
```

`UPPER` or `LOWER` doesn't matter, it's used only in the index. Refer to [Postgres docs](https://www.postgresql.org/docs/15/indexes-expressional.html)

Putting this in a migration might look like this:
```ruby
add_index :table, [:name], unique: true, case_sensitive: false
```

Probably `ignore_case` would only be valid if `unique` were true. Or we could use a `unique_ignore_case`

Thoughts on such a feature?

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.

**Comment by softwaregravy** [comment]
@rafaelfranca Thank you
