### ISSUE TITLE
Stack level too deep error

### ISSUE THREAD

**Issue by haweris** [rails/rails#47784]
https://github.com/rails/rails/blob/99096b88ae7a7c9019f2cbcf867e29ba42768e65/activerecord/lib/active_record/table_metadata.rb

I have created a class method in three models (Role, User, Industry) named **table_metadata**. I was unaware that there is a built-in method with same name. Now issue is when I use **all** in that method, which refers to Model.all and then call this method like Model.table_metadata, it raise exception:

**SystemStackError: stack level too deep**
from /home/username/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/relation.rb:27:in `initialize'

The bigger problem is that this method works fine with **Role** model but it raises exception when I use it for **Industry** or **User** model.
Please provide if there is any detailed explanation for that.

**Comment by rafaelfranca** [comment]
Thank you for the issue. Why this method works in Role and not in the others I can't explain, but you are correct that you should not override this method. If you do, there is no way to guarantee Active Record will work.
