### ISSUE TITLE
Could not log "sql.active_record" event. NoMethodError: undefined method `round' for nil:NilClass

### ISSUE THREAD

**Issue by kvokka** [rails/rails#47814]
### Steps to reproduce

```bash
rails new app
cd app
bundle exec rails g scaffold user name
bundle exec rails db:migrate
bundle exec rails runner 'User.create name: :foo'
bundle exec rails runner 'User.create name: :bar'
bundle exec rails console
```

In the console:
```ruby
ApplicationRecord.connection.execute(User.limit(2).to_sql, async: true)

Could not log "sql.active_record" event. NoMethodError: undefined method `round' for nil:NilClass
["/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/log_subscriber.rb:39:in `sql'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/subscriber.rb:149:in `finish'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/log_subscriber.rb:115:in `finish'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/fanout.rb:211:in `finish'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/fanout.rb:76:in `block in finish'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/fanout.rb:91:in `block in iterate_guarding_exceptions'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/fanout.rb:90:in `each'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/fanout.rb:90:in `iterate_guarding_exceptions'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/fanout.rb:76:in `finish'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:49:in `finish_with_state'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:30:in `instrument'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/sqlite3/database_statements.rb:30:in `execute'",
 "(irb):4:in `<main>'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb/workspace.rb:113:in `eval'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb/workspace.rb:113:in `evaluate'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb/context.rb:497:in `evaluate'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb.rb:587:in `block (2 levels) in eval_input'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb.rb:776:in `signal_status'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb.rb:566:in `block in eval_input'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb/ruby-lex.rb:257:in `block (2 levels) in each_top_level_statement'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb/ruby-lex.rb:239:in `loop'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb/ruby-lex.rb:239:in `block in each_top_level_statement'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb/ruby-lex.rb:238:in `catch'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb/ruby-lex.rb:238:in `each_top_level_statement'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb.rb:565:in `eval_input'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb.rb:499:in `block in run'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb.rb:498:in `catch'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb.rb:498:in `run'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.6.3/lib/irb.rb:416:in `start'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.4.3/lib/rails/commands/console/console_command.rb:70:in `start'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.4.3/lib/rails/commands/console/console_command.rb:19:in `start'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.4.3/lib/rails/commands/console/console_command.rb:102:in `perform'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.4.3/lib/rails/command/base.rb:87:in `perform'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.4.3/lib/rails/command.rb:48:in `invoke'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `<main>'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'",
 "/Users/mikeb/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'",
 "bin/rails:4:in `<main>'"]
```

With `async: false`  everything works as expected

```bash
$ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin22]
$ rails -v
Rails 7.0.4.3
```

**Comment by fatkodima** [comment]
Are you sure `:async` is supported? - https://github.com/rails/rails/blob/c15ee6e7b5065db3c46afa1f025b8e45f443604e/activerecord/lib/active_record/connection_adapters/sqlite3/database_statements.rb#L23

**Comment by kvokka** [comment]
> Are you sure :async is supported? -

Initially, I faced the issue with the `mysql2` gem (the latest v. 0.5.5), which supports this feature. After switching on `mysql2` the situation is the same.

Added steps which I applied:

```bash
echo 'default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password:

development:
  <<: *default
  database: dev' > config/database.yml
echo '\n gem "mysql2"' >> Gemfile
bundle
```

**Comment by nickborromeo** [comment]
it looks like we are missing a key in the payload for the log subscriber. it fails in this line 
https://github.com/rails/rails/blob/08a18c75ff1a2d8f20e64f9935dd118f47358662/activerecord/lib/active_record/log_subscriber.rb#L45

and the call to instrument this event does not pass this key along

https://github.com/rails/rails/blob/08a18c75ff1a2d8f20e64f9935dd118f47358662/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L1108-L1119

The test in place explicitly passes in a `lock_wait` value 
https://github.com/rails/rails/blob/08a18c75ff1a2d8f20e64f9935dd118f47358662/activerecord/test/cases/log_subscriber_test.rb#L136-L140

removing that from the payload reproduces the error that was reported in the test suite.

**Comment by kvokka** [comment]
@nickborromeo 
Thank you for the submission.

Atm I created a hack to live with it for now, maybe someone will find this useful. Dont mind making a PR, but only after someone assign me on it.

Here is the pluck:

```ruby 
module ActiveRecordLogSubscriberExt
  def sql(event)
    event.payload[:lock_wait] ||= 0
    super
  end
end

module ActiveRecord
  class LogSubscriber < ActiveSupport::LogSubscriber
    prepend ActiveRecordLogSubscriberExt
  end
end
```

**Comment by fatkodima** [comment]
I am not very familiar with the internals of the `async` feature, but reading through the code, it seems like you are using it incorrectly (kinda using private API). `ApplicationRecord.connection.execute(User.limit(2).to_sql, async: true)` does not actually execute the query asynchronously and that option should not be used manually. The `async: true` option is passed internally via a few method calls chain via https://github.com/rails/rails/blob/0b73361a5880d8d9d1683ceb86e2e35a421c75bc/activerecord/lib/active_record/future_result.rb#L151-L153 when the query is executed asynchronously.

You should use something like `User.limit(2).load_async`. 

I am sure @byroot as an [implementor of this feature](https://github.com/rails/rails/pull/40037) can give clarity for this issue.

**Comment by kvokka** [comment]
The method `execute` is public, meaning that might be used directly. 

https://github.com/rails/rails/blob/c15ee6e7b5065db3c46afa1f025b8e45f443604e/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb#L199

Not even to mention that it's the default way to execute a custom SQL code through the connection pool.

I just want to say, that from my perspective it should be working (and it does, by the way after applying the dirty patch above).

As you can see in the `load_async` method, it's a wrapper over the `execute` method:

https://github.com/rails/rails/blob/e8b47dd695a3236c57a719c8e2f525e2af5145f7/activerecord/lib/active_record/relation.rb#L688

**Comment by byroot** [comment]
Yes, this isn't public API.

Yes the method is public, but what defines public API is documentation, here the parameter is unfortunately caught by RDoc, but the option isn't mentioned, it's just unfortunately exposed for the mysql adapter, but as you can see it isn't on the others.

That being said I'm not against supporting raw async queries, but it has to be supported on all adapters, not just quickly patch the mysql adapter.

**Comment by nickborromeo** [comment]
could it be though that we are just missing that value being passed? The mysql docs say that the default value for [`innodb_lock_wait_timeout`](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_lock_wait_timeout) is 50. 

If run this query while running the test that I mentioned early you get the default value

```
[10] pry(#<LogSubscriberTest>)> ActiveRecord::Base.connection.select_all("show variables like 'innodb_lock_wait_timeout'")
=> #<ActiveRecord::Result:0x00000001065ffaf8 @column_types={}, @columns=["Variable_name", "Value"], @hash_rows=nil, @rows=[["innodb_lock_wait_timeout", "50"]]>
```

so when we are making the call to instrument the query being ran, can we just add

**Comment by byroot** [comment]
No that's not it. 

If you really wanna do raw async queries, it wasn't particularly intended, but I think `Connection#select_all` should work: https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/DatabaseStatements.html#method-i-select_all

Also in 7.1 you now have `ActiveRecord::Base.async_find_by_sql` https://edgeapi.rubyonrails.org/classes/ActiveRecord/Querying.html#method-i-async_find_by_sql.

Only `SELECT` queries are supported asynchronously, so not sure we could really support `Connection#execute`.

Anyway, I'll close as I don't think this is a bug per say.
