### ISSUE TITLE
Incorrect timestamps when converting to timezones in Mexico

### ISSUE THREAD

**Issue by henceagrin36** [rails/rails#47853]
### Steps to reproduce

Mexico eliminated Daylight Savings Time last October, and most of the country is staying on CST. Looks like `ActiveSupport::TimeZone` is returning the incorrect daylight savings versions of timestamps converted to the Mazatlan, Mexico City, and Monterrey timezones.

```
time = DateTime.parse('2023-04-04T00:00:00.000Z')
time.in_time_zone('America/Mazatlan')
time.in_time_zone('America/Mexico_City')
time.in_time_zone('America/Monterrey)
```

### Expected behavior
```
time = DateTime.parse('2023-04-04T00:00:00.000Z')

time.in_time_zone('America/Mazatlan')
=> Mon, 03 Apr 2023 17:00:00.000000000 MST -07:00

time.in_time_zone('America/Mexico_City')
=> Mon, 03 Apr 2023 18:00:00.000000000 CST -06:00

time.in_time_zone('America/Monterrey)
=> Mon, 03 Apr 2023 18:00:00.000000000 CST -06:00
```

### Actual behavior
```
time = DateTime.parse('2023-04-04T00:00:00.000Z')

time.in_time_zone('America/Mazatlan')
=> Mon, 03 Apr 2023 18:00:00.000000000 MDT -06:00

time.in_time_zone('America/Mexico_City')
=> Mon, 03 Apr 2023 19:00:00.000000000 CDT -05:00

time.in_time_zone('America/Monterrey)
=> Mon, 03 Apr 2023 19:00:00.000000000 CDT -05:00
```

### System configuration
**Rails version**: 6.1.4.6, 7.0.1

**Ruby version**: ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux-musl], ruby 3.0.3p157 (2021-11-24) [x86_64-linux]

**Comment by mammuth** [comment]
@henceagrin36 I just stumbled upon the same challenge, what was your solution? 😊
