### ISSUE TITLE
issue with ENUM - incorrect activerecord condition result 

### ISSUE THREAD

**Issue by saviokmua** [rails/rails#47868]
### Steps to reproduce
example: 
we have model `Order` with the next enum
```ruby
enum status: { active: 0, canceled: 1 }
```
tried to select objects with incorrect status values

```ruby
Order.where(status: "pending")
```

### Expected behavior
Expected, that relation will be empty

### Actual behavior
Returns relation with records with `active` status

### System configuration
**Rails version**:
Rails 6.1.7.3
**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Comment by eileencodes** [comment]
Please provide a reproduction using our [bug report templates](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb).

**Comment by saviokmua** [comment]
tried to create bug report, and found that
1) this issue is reproduced only when DB is mysql (mysql  Ver 8.0.32-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))
2) on rails v 6.0.4.4 it worked correctly with above notice version MySQL
3) with sqlite all works ok

**Comment by nickborromeo** [comment]
It looks like this behavior was _fixed_ with this change https://github.com/rails/rails/pull/41516.

**Comment by saviokmua** [comment]
does it fix on rails 6.1.7.3? for me not working correctly

**Comment by eileencodes** [comment]
No 6.1.x doesn't receive bug fixes anymore and only receives security patches. You'll need to upgrade to 7.0

**Comment by davidlbean** [comment]
I have the same issue.  Defined an enum on an AR class, and I'm getting different results from ```Class.group(:enum_name).count``` and ```Class.enum_name_plural```
e.g. ```Post.group(:status).count``` and ```Post.statuses```

Demonstration:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :status
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
  enum status: [:on, :off, :both]
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_enum
    # create some dummy data
    20.times do
      # randomize assignment of a status to each post
      post = Post.create!(status: Post.statuses.keys[rand(3)])
    end

    # getting the status counts via sql
    # e.g.: {nil=>11, "off"=>5, "both"=>4}
    results_from_db_query = Post.group(:status).count
    # getting the status counts via enum
    # e.g.: {"on"=>0, "off"=>1, "both"=>2}
    results_from_enum     = Post.statuses

    assert_equal results_from_db_query, results_from_enum
  end
end

```

Ruby 3.1.1p18
Using activerecord 7.1.0.alpha from https://github.com/rails/rails.git (at main@767653a)

(This is my first time reporting an issue -- apologies if I'm not following all the rules/conventions.)
