### ISSUE TITLE
Regression in setting multiple cookies.

### ISSUE THREAD

**Issue by ioquatix** [rails/rails#47881]
👋 hey @ioquatix

This change seems to have caused a regression when setting multiple cookies in a response. I haven't been able to come up with a reproducible test case (due to test harness shenanigans most likely), but it's easy to reproduce manually by setting multiple cookies.

When setting a single cookie, everything looks fine:

```
$ curl -I http://localhost:3000/session/new
HTTP/1.1 200 OK
...
Set-Cookie: a=1; path=/; SameSite=Lax
```

But when setting multiple cookies, the response contains a single `Set-Cookie` header with an Array-ified string:

```
$ curl -I http://localhost:3000/session/new
HTTP/1.1 200 OK
...
Set-Cookie: ["a=1; path=/; SameSite=Lax", "b=2; path=/; SameSite=Lax"]
```

The result is that browsers parse the first cookie's name as `["name`. 

Prior to this, multiple cookies were set using individual headers:

```
Set-Cookie: a=1; path=/; SameSite=Lax
Set-Cookie: b=2; path=/; SameSite=Lax
```

_Originally posted by @packagethief in https://github.com/rails/rails/issues/47085#issuecomment-1499309508_

**Comment by ioquatix** [comment]
Can you tell me the following:

- What version of Puma (or other webserver) you are using?
- What version of Rack are you using?
- Can you show me the controller code that's setting multiple cookies?

**Comment by packagethief** [comment]
Hey @ioquatix, I'm sorry for the noise. The problem wasn't with your commit, but rather with the Puma version. I'm using Rack 3, which is only supported on Puma >= 6.0. In my tests I was using 5.6.5.

The default Gemfile created by `rails new` specifies `puma >= 5.0`:
https://github.com/rails/rails/blob/2e81ed6/railties/lib/rails/generators/app_base.rb#L270

That may need to be changed in light of the upper bound on Rack being removed in 859b526.

You can close this issue! Thanks for your time.
