### ISSUE TITLE
Unable to disable triggers on a partitioned table in Rails

### ISSUE THREAD

**Issue by quynhethereal** [rails/rails#47904]
### Steps to reproduce

1. Create a table and its partition in Postgres
```sql
CREATE TABLE activities (
  id INT PRIMARY KEY,
  activity_name VARCHAR(50)
);

CREATE TABLE users (
  id INT,
  username VARCHAR(50),
  activity_id INT,
  FOREIGN KEY (activity_id) REFERENCES activities(id)
) PARTITION BY RANGE (id);

CREATE TABLE users_0 PARTITION OF users
  FOR VALUES FROM (0) TO (100);

CREATE TABLE users_1 PARTITION OF users
  FOR VALUES FROM (100) TO (200);

CREATE TABLE users_2 PARTITION OF users
  FOR VALUES FROM (200) TO (300);

CREATE TABLE users_3 PARTITION OF users
  FOR VALUES FROM (300) TO (MAXVALUE);
```

2. Attempt to disable triggers on the partitioned table using the following code:

```sql
ActiveRecord::Base.connection.execute("DISABLE TRIGGER ALL ON users")
```

### Expected behavior
The SQL command should succeed. It is the underlying command that Rails uses before it attempts to drop/insert the test fixtures into the test db. 

https://github.com/rails/rails/blob/c567850476dc443563b9be93a129eb09601e25af/activerecord/lib/active_record/connection_adapters/postgresql/referential_integrity.rb#L12

### Actual behavior

Rails is unable to execute the command due to the error: 

```sql
ERROR:  trigger "RI_ConstraintTrigger_c_572918" for table "users_0" does not exist
```
### System configuration
**Rails version**: 6.0.2

**Ruby version**: 2.7.4

**Postgres version:** 15.2

### Notes
This is a known bug in PostgreSQL 15+ and a patch will be released in May (https://postgrespro.com/list/id/980717.1680452426@sss.pgh.pa.us). I wonder if it is okay if we were to monkey patch this method so that it uses `SET CONSTRAINTS ALL DEFERRED;` or `ALTER TABLE ONLY users DISABLE TRIGGER ALLL;` instead. Is there any caveat that we should be aware of?

**Comment by ghiculescu** [comment]
Sorry for the late reply here, but yes, you should be fine to monkey patch it.

You could also make a PR to Rails, if going from `ALTER TABLE users` to `ALTER TABLE ONLY users` is safe and would fix the bug.
