### ISSUE TITLE
Missing "@" for form_with model: article

### ISSUE THREAD

**Issue by EtienneLen** [rails/rails#47906]
In the documentation : "https://guides.rubyonrails.org/getting_started.html", it seems that there is a typo, the 
```@article ``` is missing

```
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>
```
It should be changed : 

```
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
```

**Comment by nashby** [comment]
@EtienneLen it's not a typo. In that doc form partial is rendered with `<%= render "form", article: @article %>
` so `article` local variable is available for you.

**Comment by skipkayhil** [comment]
The next paragraph after the code is this:

> The above code is the same as our form in app/views/articles/new.html.erb, except that all occurrences of @​article have been replaced with article. Because partials are shared code, it is best practice that they do not depend on specific instance variables set by a controller action. Instead, we will pass the article to the partial as a local variable.

Do you think there's anything we should change to make it more clear?

**Comment by EtienneLen** [comment]
Thank you for your help. I misunderstood. I don't think it's necessary to make a change. Please excuse me for this issue.
