### ISSUE TITLE
Merge Resolution Tools will save unencrypted output silently if using diff=rails_credentials

### ISSUE THREAD

**Issue by krainboltgreene** [rails/rails#47911]
### Steps to reproduce
1. Have encrypted credentials
2. Have the enrolled diff feature
3. Have a merge conflict in the credentials file
4. Use a merge resolution tool (Like visual studio code's default merge resolution tool)
5. Resolve the conflict
6. Look `config/credentials.enc.yml`

### Expected behavior
Users will expect it to be encrypted.

### Actual behavior
The contents is saved unencrypted

This isn't something that can be solved, but it absolutely should come with a warning label.

**Comment by ghiculescu** [comment]
Hmm, is it possible to provide a repo that replicates the issue? It sounds like it should be solved, or at least detected (and then if it's detected we could raise an error for it).

**Comment by krainboltgreene** [comment]
Entirely possible, I'll do it tonight.
