### ISSUE TITLE
config.active_support.disable_to_s_conversion doesn't do anything (ENV["RAILS_DISABLE_DEPRECATED_TO_S_CONVERSION"] does)

### ISSUE THREAD

**Issue by Hampei** [rails/rails#47914]
Setting `config.active_support.disable_to_s_conversion` in application.rb doesn't do anything and I see no code in activesupport reading from the setting.

Instead `ENV["RAILS_DISABLE_DEPRECATED_TO_S_CONVERSION"]` is being used for this, but I can't find this in any of the documentation or change-logs. Setting that to anything at the very top of application.rb does the trick. 

Not quite sure if the changelog should just be changed or the code should be changed. 

I also can't see  `config.load_defaults 7.0` working, since the env-var is never set.

### Steps to reproduce

New rails 7.0 project with 

```
  class Application < Rails::Application
    config.load_defaults 6.1
    config.active_support.disable_to_s_conversion
```

### Expected behavior
expected `1.to_s(:db)` to throw an error

### Actual behavior
Gave me a `"1"`

### System configuration
**Rails version**: 7.0.4.3

**Ruby version**: 3.2.1

**Comment by ghiculescu** [comment]
> ### Steps to reproduce
> New rails 7.0 project with
> 
> ```
>   class Application < Rails::Application
>     config.load_defaults 6.1
>     config.active_support.disable_to_s_conversion
> ```

You need to do `config.active_support.disable_to_s_conversion = true`. Does the issue still exist with that?

**Comment by a3626a** [comment]
In my case, it was `gem 'jsonapi.rb', '~> 1.7.0'`.

Some gems can load active support prematurely as mentioned earlier.

**Comment by BrianHawley** [comment]
For those still using rails 7.0.x and running into this issue, add this code in config/application.rb before `Bundler.require`:
```ruby
ENV["RAILS_DISABLE_DEPRECATED_TO_S_CONVERSION"] = "true"
```
You can remove it when you update rails to 7.1+.

**Comment by galievruslan** [comment]
Rails 7.1.5
ruby-3.2.6

```
config.active_support.disable_to_s_conversion = true
```
Hello. I upgraded from Rails 6.1 to Rails 7.1. This setting in my application.rb file doesn't work. In all view files, the date/time fields are displayed in a format other than the one set in the localization file.
```
en:
  date:
    formats:
      default: "%d.%m.%Y"
      short: "%b %d"
      long: "%d %B, %Y"
  time:
    formats:
      default: "%d.%m.%Y %H:%M"
      short: "%H:%M"
      long: "%B %d, %Y %H:%M:%S"
    am: "am"
    pm: "pm"
```
In rails console
```
3.2.6 :009 > Date.today.to_s
"2024-11-13"
3.2.6 :010 > Date.today.to_fs
"13.11.2024"
```
```
# initializers/datetime_format.rb
Date::DATE_FORMATS[:default] = lambda { |date| I18n.l(date) }
Time::DATE_FORMATS[:default] = lambda { |time| I18n.l(time) }
```
How to fix this and return to the behavior of Rails 6 ?

**Comment by galievruslan** [comment]
ruby 3.2.6
Rails 7.1.5

Hello. I upgrade from rails 6 to rails 7. After this, in all view files, fields with the date/time type began to be displayed in a format different from that specified in the locale file.

initializers/datetime_format.rb
```
Date::DATE_FORMATS[:default] = lambda { |date| I18n.l(date) }
Time::DATE_FORMATS[:default] = lambda { |time| I18n.l(time) }
```
I tried add this setting to application.rb
```
config.active_support.disable_to_s_conversion = true
```
But it didn't help. The only thing is to wrap the display of fields in a method I18n.l in all view files. Tell me what I'm doing wrong, why my setting **disable_to_s_conversion** is not applied
