### ISSUE TITLE
ActiveSupport::MessagEncryptor.decrypt_and_verify

### ISSUE THREAD

**Issue by priyalorha** [rails/rails#47930]
### Steps to reproduce

len   = ActiveSupport::MessageEncryptor.key_len
salt  = SecureRandom.random_bytes(len)
key   = ActiveSupport::KeyGenerator.new('password').generate_key(salt, len) # => "\x89\xE0\x156\xAC..."
crypt = ActiveSupport::MessageEncryptor.new(key)                            # => #<ActiveSupport::MessageEncryptor ...>
encrypted_data = crypt.encrypt_and_sign('my secret data')                   # => "NlFBTTMwOUV5UlA1QlNEN2xkY2d6eThYWWh..."
crypt.decrypt_and_verify(encrypted_data)                                    # => "my secret data"
crypt.decrypt_and_verify(encrypted_data)   #=> "should raise raise, key been now verified"

```ruby
# Your reproduction script goes here
```

### Expected behavior

if key is verified should raise an error

### Actual behavior

is returning the decrypter data

### System configuration
**Rails version**:
Rails 7.0.4.3
**Ruby version**:
ruby 3.2.0

**Comment by vipulnsward** [comment]
@priyalorha this is expected behavior, any documentation you found that was wrong about this?

**Comment by priyalorha** [comment]
> @priyalorha this is expected behavior, any documentation you found that was wrong about this?

documentation states, am I missing out on something?

The decrypt_and_verify method will raise an ActiveSupport::MessageEncryptor::InvalidMessage exception if the data provided cannot be decrypted or verified.

https://api.rubyonrails.org/classes/ActiveSupport/MessageEncryptor.html

**Comment by nvasilevski** [comment]
>The decrypt_and_verify method will raise an ActiveSupport::MessageEncryptor::InvalidMessage exception if the data provided cannot be decrypted or verified.

It might be better to use the issue template to demonstrate the problem https://github.com/rails/rails/blob/main/guides/bug_report_templates/generic_main.rb so we can be talking and running exactly the same code.

It sounds like your expectation is that `decrypt_and_verify` can only be called once and subsequent calls will result in an exception but that's not how it actually works and documentation doesn't seem to be mentioning it. 

Perhaps in your example you expected to run something like:
```ruby
encrypted_data = crypt.encrypt_and_sign('my secret data') # => "NlFBTTMwOUV5UlA1QlNEN2xkY2d6eThYWWh..."
decrypted_data = crypt.decrypt_and_verify(encrypted_data) # => "my secret data"
crypt.decrypt_and_verify(decrypted_data) #=> "should raise
```

But generally you should be able to call `crypt.decrypt_and_verify(encrypted_data)` any number of times as the `key` stays the same and `encrypted_data` stays the same between calls

**Comment by vipulnsward** [comment]
> But generally you should be able to call crypt.decrypt_and_verify(encrypted_data) any number of times as the key stays the same and encrypted_data stays the same between calls

Right

> It sounds like your expectation is that decrypt_and_verify can only be called once and subsequent calls will result in an exception but that's not how it actually works and documentation doesn't seem to be mentioning it.

@priyalorha as @nvasilevski mentioned this is expected behavior and not stated anywhere such in docs, let me know if anything you find that needs to be fixed in docs, thanks!
