### ISSUE TITLE
Current time for Tehran still uses +4:30 offset

### ISSUE THREAD

**Issue by thushw** [rails/rails#47937]
### Steps to reproduce

```ruby
in a rails console do:
Time.now.in_time_zone("Asia/Tehran")

```

### Expected behavior
The time offset (at right end of output) should show 3:30
### Actual behavior
The offset shows 4:30
### System configuration
**Rails version**:
7.0.4.3
**Ruby version**:
3.1.2

<img width="428" alt="Screen Shot 2023-04-13 at 2 07 57 PM" src="https://user-images.githubusercontent.com/1197851/231883175-b3ca26e1-c57b-4dd1-9e76-a9e75e008e9e.png">

<img width="700" alt="Screen Shot 2023-04-13 at 2 13 00 PM" src="https://user-images.githubusercontent.com/1197851/231884083-106de6ea-efb3-4972-94bf-de548417df36.png">

**Comment by louim** [comment]
Hey! This is probably related to a outdated zone info data on your system. This is what I see:
```
irb(main):001:0> Time.now.in_time_zone("Asia/Tehran")
=> Fri, 14 Apr 2023 22:58:32.680898000 +0330 +03:30
```
You can try adding the [tzinfo-data gem](https://github.com/tzinfo/tzinfo-data) to see if the problem goes away.

**Comment by thushw** [comment]
Thank you   - yes, installing the gem worked. We were not using this gem before as the zonefiles our machines had worked, but looks like updating the gem is the way to sync with the changes in DST etc.
