### ISSUE TITLE
Active Record Migrations Guide contains invalid syntax for SQLite3

### ISSUE THREAD

**Issue by matiaslagoevia** [rails/rails#47941]
### Steps to reproduce
1. Create a rails app that uses SQLite3 (on Rails 7, this happens by default for me by running `rails new`)
2. Visit one of the affected sections: [using reversible](https://guides.rubyonrails.org/active_record_migrations.html#using-reversible), [using the up down methods](https://guides.rubyonrails.org/active_record_migrations.html#using-the-up-down-methods), [reverting previous migrations](https://guides.rubyonrails.org/active_record_migrations.html#reverting-previous-migrations).

### Expected behavior
The guide's migrations should be able to be ran successfully.

### Actual behavior
Migrations fail due to `SQLite3::SQLException: near "CONSTRAINT": syntax error`. This is because SQLite3 does not support `ADD CONSTRAINT` within `ALTER TABLE`. References: [1](https://www.tutorialspoint.com/sqlite/sqlite_constraints.htm), [2](https://www.sqlite.org/lang_altertable.html).

### System configuration
**Rails version**: 7.0.4.3

**Ruby version**: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin20]

**Comment by matiaslagoevia** [comment]
Hey team, created this issue after following the instructions [here](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#contributing-to-the-rails-documentation). I appreciate the work and effort that has gone into not only Rails but the guides & community itself, I'm having a lot of fun learning and experimenting with it!

I'd be happy to work on implementing the fix after getting some guidance from more senior community members. Thanks again!

**Comment by ghiculescu** [comment]
Thanks for the issue, that's good feedback. I guess the point of those examples is to show that you can also write raw SQL in migrations. Is there a better example we can use that will work across DBs?

**Comment by matiaslagoevia** [comment]
No problem, happy to help out. 

I couldn't think of any applicable examples at the moment, but I did have two approaches I wanted to run by others:
1. Display some sort of banner on those examples explaining they will not work if ran against SQLite3
2. Come up with an example of valid syntax across SQLite3, MySQL/MariaDB, and PostgreSQL to replace the current ones

The solution could be iterated — add the banner in one PR, and add an example (once available) in a second PR. If all looks good, I could get started on the banner. Further feedback (including better alternatives I may not be aware of) are welcome and appreciated!

**Comment by ghiculescu** [comment]
I think the guides should work out of the box with sqlite since that's the default for Rails.

**Comment by matiaslagoevia** [comment]
Makes sense, will do some digging and share a potential example here for feedback. Thanks!
