### ISSUE TITLE
Why does Model.to_key return an Array? How about returning a scalar instead?

### ISSUE THREAD

**Issue by johnnyshields** [rails/rails#47945]
It's not clear why the `Model#to_key` method would return an Array. Here's the [relevant code](https://github.com/rails/rails/blob/355fd5929058ee3a73032c5f62de3d8819550482/activerecord/lib/active_record/attribute_methods/primary_key.rb#L12):

```ruby
module ActiveRecord
  module AttributeMethods
    module PrimaryKey
      extend ActiveSupport::Concern

      # Returns this record's primary key value wrapped in an array if one is
      # available.
      def to_key
        key = id
        [key] if key
      end
```

At a minimum this deserves an explanatory code comment, but wouldn't it make much more sense to just return the `id` as a scalar?

**Comment by matthewd** [comment]
Active Record implements the Active Model API. While Active Record has historically done so, Active Model does not assume that a key is a single scalar value.
