### ISSUE TITLE
Rails new generated config/locales.en.yml mentions surrounding specific keys with 'single quotes' while the example is presented with "double quotes"

### ISSUE THREAD

**Issue by tomczak-mateusz** [rails/rails#47956]
### Subject
Hi :wave:,
The reported issue is a very minor one & comment related:
While generating the Rails app via `rails new`, the autogenerated `config/locales/en.yml` file template mentions surrounding specific keys with  `'single quotes'` while the example below is presented with `"double quotes"`

```ruby
# The following keys must be escaped otherwise they will not be retrieved by
# the default I18n backend:
#
# true, false, on, off, yes, no
#
# Instead, surround them with single quotes.
#
# en:
#   "true": "foo"
```

Back in April 2021 @ashiksp & @rafaelfranca have updated (https://github.com/rails/rails/pull/42064) the templates to use "double quotes" instead of 'single' ones but the comment in `config/locales/en.yml` [was missed](https://github.com/rails/rails/pull/42064/files#diff-e9731e50a226aac4e914118d2532dc91f784e90c452f924d100071d6fb8c7c68R24).

### Steps to reproduce
1. run `rails new XYZ `
2. rails app `XYZ` should be generated
3. checkout into `XYZ app`, verify if `config/locales/en.yml` file is present
4. verify if the comment `'Instead, surround them with single quotes.'` is present

### Expected behavior
comment should mention double quotes: `# Instead, surround them with double quotes.` 

### Actual behavior
comment mentions single quotes: `# Instead, surround them with single quotes.` 

### System configuration
**Rails version**: 7.0.4.3
**Ruby version**: 3.2.2

**Comment by skipkayhil** [comment]
Hey @tomczak-mateusz, thanks for opening an issue! Would you like to make a PR to update the comment?

**Comment by tomczak-mateusz** [comment]
@skipkayhil will do soon, thanks
