### ISSUE TITLE
turbo_stream not sufficient recognized by render

### ISSUE THREAD

**Issue by chmich** [rails/rails#47954]
**Hi**

render is not recognizing turbo_stream on absolute path: content is not rendered as turbo_stream

**With relative paths, inside app/views all is working**

```ruby
render template: 'my_template.turbo_stream.erb'

my_template.turbo_stream.erb
my_template.turbo_stream.haml
```

**No success rendering a turbo_stream template by absolute paths**

```ruby
render file: Rails.root.join('app', 'views', 'articles', 'my_template.turbo_stream.erb'), formats: :turbo_stream

render turbo_stream: { file: Rails.root.join('app', 'views', 'articles', 'my_template.turbo_stream.erb'), layout: false }

render template: 'layouts/my_template' #=> from within a module that resides inside a gem

respond_to do |format|
      format.turbo_stream { render file: Rails.root.join('app', 'views', 'articles', 'my_template.turbo_stream.erb'), layout: false }
end
```

i also tried: `format: :turbo_stream` `formats: [:turbo_stream]` , see [4841](https://github.com/rails/rails/issues/4841)

all of that is rendering the file but not as turbo_stream

**confusing**

At a previously project i had to name my files by `my_template.turbo_stream.html.haml` for make it working (.html was necessary). Now i have the opposit: If i have the .html included by the suffix it  didnt work, i have to name it like above mentioned. This is very confusing and i lost days for finding that. It would be good if all this ways would work, like it works by rendering :html by example.

**Comment by skipkayhil** [comment]
Hey @chmich, thanks for opening an issue! Can you create a repository to reproduce the issue? That would make it easier for us to understand the expected/actual behavior

**Comment by chmich** [comment]
Hi @skipkayhil i made quick-and-dirty a rails project which includes the error, see repo on [GitLab](https://gitlab.com/sedl/renderturbostream_railsapp).
on the root page click that button for reproducting.

![grafik](https://user-images.githubusercontent.com/31048265/232254300-48c1a4ec-4b38-4084-9dad-854f2802aaf4.png)


may this help you?

**Comment by skipkayhil** [comment]
Yes, that does. I believe the issue is that the view you are trying to render is not in the view paths (rendering an absolute path means ERB won't evaluate the file). If you are writing a gem you should make it a `Rails::Engine`, which will add the gem's `app/views` folder to an application's view paths automatically. (Alternatively you could look into `prepend_view_paths` or `append_view_paths` which would let you do a completely custom path).

I'm going to close as I'm not seeing an issue in Rails, but feel free to reply if you have more questions!

**Comment by chmich** [comment]
Thanks @skipkayhil i'll try it next week
