### ISSUE TITLE
inverse associations are not properly populated with a custom primary_key

### ISSUE THREAD

**Issue by brightredchilli** [rails/rails#47976]
It seems like specifying a custom primary_key with an association doesnt seem to populate inverses properly on Rails 6+. AFAICT, this is because setting an inverse fails because [inversable?](https://github.com/rails/rails/blob/732a4748b361bfdadb042fc62b4c608b1a6eef47/activerecord/lib/active_record/associations/association.rb#L142) is not true on an association defined below, and that is because this [matches_foreign_key?](https://github.com/rails/rails/blob/732a4748b361bfdadb042fc62b4c608b1a6eef47/activerecord/lib/active_record/associations/association.rb#L378-L385) uses reflection.foreign_key, as opposed to reflection.active_record_primary_key.

I'm happy to submit a PR that I think will fix this but want to confirm that this is seen as a bug. The records are created properly but inverse relationships are not populated properly.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "rails", github: "rails/rails", branch: "v5.2.8.1" # <-- This worked on Rails 5!
  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :name
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :post_name
  end
end

class Post < ActiveRecord::Base
  # has_many :comments <-- this works
  has_many :comments, foreign_key: :post_name, primary_key: :name, inverse_of: :post
end

class Comment < ActiveRecord::Base
  # belongs_to :post <-- this works  
  belongs_to :post, foreign_key: :post_name, primary_key: :name, inverse_of: :comments
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(name: 'hi')
    post.comments << Comment.create!

    assert_equal 1, post.comments.count
    assert_equal 1, Comment.count
    assert_equal post.id, Comment.first.post.id

    assert_equal post.object_id, post.comments.first.post.object_id # <— this fails
  end
end


```

### Expected behavior
Expect that object_id would be the same(ie, the inverse will be set up properly). *Note, this is working on: v5.2.8.1*

### Actual behavior
object_ids differ

### System configuration
**Rails version**:
Tested on main, and on branch v6.1.7

**Ruby version**:
2.7.7

**Comment by nickborromeo** [comment]
👋 @brightredchilli that looks really similar to https://github.com/rails/rails/issues/47574 and you also chimed in on the PR I have out for that in https://github.com/rails/rails/pull/47756. I took your reproduction script and ran it against that branch I have and the test passes.

**Comment by brightredchilli** [comment]
Yep, opened this before I realized there was active work!
