### ISSUE TITLE
number_to_human_size gives wrong result

### ISSUE THREAD

**Issue by phoet** [rails/rails#47989]
### Steps to reproduce

```ruby
require "active_support/all"

module Helpers
  extend ActiveSupport::NumberHelper
end

Helpers.number_to_human_size(10.megabyte)
# => "10 MB"
Helpers.number_to_human_size(12.megabyte)
# => "10 MB"
Helpers.number_to_human_size(12.megabyte, precision: 2)
# => "12 MB"
```

### Expected behavior

retruns "12 MB" for 12.megabyte

### Actual behavior

returns "10 MB" for 12.megabyte

### System configuration

```
Rails.version
=> "7.0.4.3"
```

**Comment by fatkodima** [comment]
Works as expected for me. Can you create a reproducible test case using this template - https://github.com/rails/rails/blob/main/guides/bug_report_templates/generic_gem.rb?

**Comment by phoet** [comment]
i think i found the issue. i have locale :de and use a default I18n template. the formatter pulls formats from the translation file using a namespace, but the `NumberToHumanSizeConverter` AND the `NumberToHumanConverter` both pull from the same `:human` namespace which calls the method with those options

```
i18n_format_options
{:delimiter=>"", :precision=>1, :separator=>",", :significant=>true, :strip_insignificant_zeros=>true}
```

instead of 

```
default_format_options
{:separator=>".", :delimiter=>"", :precision=>3, :significant=>true, :strip_insignificant_zeros=>true}
```

**Comment by phoet** [comment]
But even with those options the result should be 12 not 10...

**Comment by phoet** [comment]
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", "7.0.4.3"
end

require "active_support/all"
require "minitest/autorun"

module Helpers
  extend ActiveSupport::NumberHelper
end

OPTS = {
  separator: ".",
  delimiter: "",
  precision: 1,
  significant: true,
  strip_insignificant_zeros: true
}

class BugTest < Minitest::Test
  def test_stuff
    assert_equal "10 MB", Helpers.number_to_human_size(10.megabyte, OPTS)
    assert_equal "12 MB", Helpers.number_to_human_size(12.megabyte, OPTS)
  end
end
```

**Comment by fatkodima** [comment]
Seems like you need to use `precision: 2`. `precision: 1` converts to the nearest tenth and so `12` is rounded to `10`.

**Comment by phoet** [comment]
looks like the default template has changed that setting to precision 3 as well https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/de.yml#L192
