### ISSUE TITLE
Rails 7 could be so much more successful

### ISSUE THREAD

**Issue by chmich** [rails/rails#47991]
Rails 7 is so great! 

But confusing!

Why we need a second standard Rails package

## Dear DHH, dear rails core team,

Rails 7 is great, but it is more confusing than ever. How do you make, with turbo-streams, a simple create or update action with redirects, consistent testing and, 2023, with a fully working HMR?

I lost many months and wrote [this TUTORIAL (gem and npm package from me included)](https://dev.to/chmich/rails-7-vite-wrapping-up-1pia) and I want to suggest: Please appoint a small team of developers from the core team who are thinking like me, check if that is a way, and if so, add a second default package on the official rails page, and the docs.

Why not have flags like `rails new --vite --rspec` which generates a new app without minitest? Regarding rubygems, the majority of the community has chosen rspec.

Let us call the current default, `the basic package` and something like what I am describing `the ambitioned package` and find 2 explanatory sentences for each and post them on [rubyonrails.org](https://rubyonrails.org/). In 3 minutes a new developer would find his entry point.

I think there are a lot of developers like me who need to take a different path, and if the core team would give a different path, this group would grow together better. But it has to come from the core team because this is where we are at home.

If you follow the official docs and gems you will be led to importmaps, jsbundling or webpacker (shakapacker). We are a group of 3 developers. After years of webpacker we all started with importmaps. Now we all switched to vite and are as happy as [Juice10 mentioned: "Please add vite as default option for rails"](https://github.com/rails/jsbundling-rails/issues/25). Justin Gordon has really done a great job, I loved to see all what hes doing, but, sorry, webpacker has had its time and compare react to [svelte (nice video there, check from minute 4:21)](https://svelte.dev/blog/svelte-3-rethinking-reactivity). Why not suggest svelte for rails before react? 

Why am I a Rails developer? Why Rails? From my point of view, Rails has its place among the other frameworks by being an ambitious framework for those who do not want to just do what the others do. 

Why is Django so successful? Because it is simple and it works. What are the criticisms of Rails? Confusing, you have to deal with thousands of third party libs. But those who work with it, and I'm in that group, love it.

Many good products have disappeared from the market due to lack of knowledge on how to sell their goodness.

2021 DHH published [Rails 7.0: Fulfilling a vision](https://rubyonrails.org/2021/12/15/Rails-7-fulfilling-a-vision) and you took a big step that is ahead of time and there is now the expectation to write "react-like apps" but so much easier. And Rails made it!

Rails is ahead of the curve and could be more successful.

Because the packages I found in my tutorial are young, stable, and will be successful for years to come, the time is right. Rails can grow with them. But it is very important for the success of a framework that the developers are led on a path at first sight, where they are going to be satisfied.

## Thanks, Christian

**Comment by ghiculescu** [comment]
Hey Christian, thanks for the feedback. It might be better received on https://discuss.rubyonrails.org/, we reserve this issue board for bugs. So I'm going to close this issue, hope you understand.

(It also might not be. I get the feeling lots are people are fine without Vite and Rspec being built-in. They are easy enough to add, and [Rails is omakase](https://rubyonrails.org/doctrine#omakase).)
