### ISSUE TITLE
Forms with file input now default to accepting 0 files

### ISSUE THREAD

**Issue by shamas-** [rails/rails#48006]
### Steps to reproduce

```ruby
<%= form.file_field name, multiple: true, direct_upload: true %>
```

### Expected behavior
```
<input multiple="multiple" data-direct-upload-url="http://localhost:3000/rails/active_storage/direct_uploads" type="file" name="name1[name2][]" id="name1_name2_files">
```

### Actual behavior
```
<input name="name1[name2][]" type="hidden" value="" autocomplete="off">
<input multiple="multiple" data-direct-upload-url="http://localhost:3000/rails/active_storage/direct_uploads" type="file" name="name1[name2][]" id="name1_name2_files">
```

[The documentation](https://api.rubyonrails.org/v7.0.4/classes/ActionView/Helpers/FormBuilder.html#method-i-file_field) says that the hidden input is only output if `include_hidden: true` is present. However, it is also output even if the `include_hidden` key is entirely absent. The problem with this is that it turns forms that were designed to require 1+ files into forms that submit successfully with 0+.

`include_hidden` was not present in [6.1 documentation](https://api.rubyonrails.org/v6.1/classes/ActionView/Helpers/FormBuilder.html#method-i-file_field).

### System configuration
**Rails version**: 7.0.4.3

**Ruby version**: 3.0

**Comment by ghiculescu** [comment]
ref: https://github.com/rails/rails/pull/43511

Looks like the documentation is wrong. `multiple: true, include_hidden: true` will result in the hidden input, but so will `multiple: true` + `config.active_storage.multiple_file_field_include_hidden == true`, which is the default in Rails 7. If you set that config to `false` your issue should go away.

@seanpdoyle was this expected? Reading through the PR I'm not sure it it was expected that this would `file_field` when being used without Active Storage.

**Comment by alexpapworth** [comment]
Can we get the documentation updated? Looks like you need `multiple: true, include_hidden: false` to stop the form removing existing images.

**Comment by ghiculescu** [comment]
Yes, good call. Re-opening for that.

**Comment by alexpapworth** [comment]
Created a PR for this. https://github.com/rails/rails/pull/48658
