### ISSUE TITLE
When I generate project with -j importmap the gem does not show in generated Gemfile.

### ISSUE THREAD

**Issue by bigos** [rails/rails#48000]
### Steps to reproduce
 

` rails new qc_plus -d postgresql -c bootstrap -j importmap
`

```ruby
# Your reproduction script goes here
```

### Expected behavior

I would expect the following to appear in Gemfile.
gem 'importmap-rails'

### Actual behavior

But it does not and leads me to a day of searching for answers to why my code does not behave like in the tutorials.

### System configuration
**Rails version**:
Rails 7.0.4.3

**Ruby version**:
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-linux]

**Comment by morgoth** [comment]
This is by design, ie https://github.com/rails/rails/blob/d8a8df3d854ac8eff636b5da44fda39ee1f2254f/railties/lib/rails/generators/app_base.rb#L569-L570

**Comment by bigos** [comment]
Can you please tell me what combination of 'rails new 'options I should use if I do not want to end up in trouble further down the line and still have Bootstrap? 

Or is it OK to add the gem and rename
app/javascript/application.js

**Comment by ghiculescu** [comment]
You should use:

```
rails new qc_plus -d postgresql -c bootstrap -j esbuild
```

For bootstrap to work you need a Javascript runtime. Esbuild is good.

Your app will be set up with https://github.com/rails/jsbundling-rails and https://github.com/rails/cssbundling-rails, both of which are supported. So you won't end up in trouble.
