### ISSUE TITLE
PG adapter deprecation in recent release

### ISSUE THREAD

**Issue by morgoth** [rails/rails#48046]
With the recent release of pg gem (1.5.0) https://github.com/ged/ruby-pg/blob/master/History.md#v150-2023-04-24-lars-kanis-larsgreiz-reinsdorfde
the warning is logged:
```
PG::Coder.new(hash) is deprecated. Please use keyword arguments instead! Called from ../ruby/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:980:in `new'
```

```
ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
rails -v
Rails 7.0.4.3
```

**Comment by yahonda** [comment]
Please feel free to open a pull request. it looks like the main branch will get the same warning.

https://github.com/rails/rails/blob/c15ee6e7b5065db3c46afa1f025b8e45f443604e/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L980

https://github.com/rails/rails/blob/77fa5584a3f17caef4dfc0f986f0eaee04e10291/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L1099

**Comment by nPaul** [comment]
i have same problem

**Comment by janosrusiczki** [comment]
@nPaul It will be fixed in the next Rails patch release. Make sure you update.

**Comment by larskanis** [comment]
pg-1.5.3 marks the warnings as deprecation, so that they are suppressed at an ordinary rails run and shouldn't bother any longer.
