### ISSUE TITLE
Sidekiq background job refresh issue.

### ISSUE THREAD

**Issue by amolbudkhe** [rails/rails#48058]
### Expected behavior
In our project, we are using sidekiq to perform some background jobs. And we use the pusher to update the status of the background job to the front end. When the user starts the background job the web page is used to reload.

### Actual behavior
Now when the user starts the background job the page is not getting reloaded, User has to manually check the status of the background job.

### System configuration
Ruby version: ruby 2.7.4p191
Rails version: 6.1.7.3
Sidekiq : 6.5.3

**Comment by byroot** [comment]
With the little information provided, nothing indicate that this may be a Rails bug. It's likely a problem in your application.
