### ISSUE TITLE
ActiveRecord::Base with SimpleDelegator throws Warning

### ISSUE THREAD

**Issue by Gbeschbacher** [rails/rails#48059]
### Steps to reproduce
- use any ActiveRecord::Base instance
- Wrap the ActiveRecord::Base instance in a SimpleDelegator
- use the SimpleDelegator instance and call `[#instance].to_a`

```ruby
class Foo < ActiveRecord::Base
  def name
    "foobar"
  end
end

class FooDelegator < SimpleDelegator
  def name
    "name"
  end
end

foo = Foo.new
delegator = FooDelegator.new(foo)
[delegator].to_a
(pry):51: warning: delegator does not forward private method #to_ary
=> [#<Foo:0x00007f43db88ff10 id: nil, created_at: nil, updated_at: nil>]
```

### Expected behavior

Calling `[delegator].to_a` shouldn't print a warning.
### Actual behavior
Prints the following warning:
```ruby
(pry):51: warning: delegator does not forward private method #to_ary
```

### System configuration
**Rails**: 7.0.4.3
**Ruby**: 3.2.1

**Comment by pawlik** [comment]
As a datapoint: Rails 7.0.4.3, Ruby: 3.1.2p20 
```
[27] pry(main)> foo = User.new
=> #<User id: nil, CUT!
[28] pry(main)> delegator = FooDelegator.new(foo)
=> #<User id: nil, CUT!>
[29] pry(main)> [delegator].to_a
=> [#<User id: nil,CUT>]
```
Seems ok.

**Comment by developius** [comment]
@Gbeschbacher I just bumped into this exact scenario (flattening a nested array of delegators that wrap ActiveRecord objects) and found this article which might be of interest: http://tenderlovemaking.com/2011/06/28/til-its-ok-to-return-nil-from-to_ary.html
It explains why `to_ary` is private and what it's use is - effectively to bypass expensive method_missing calls for each element in the array.

Here is a wayback machine link to the Ruby spec files that @tenderlove mentions (I couldn't accurately link the Ruby source):
- https://web.archive.org/web/20131026172244/https://github.com/rubyspec/rubyspec/blob/master/core/array/flatten_spec.rb#L105-L107

The way I got around the warning is to do what Aaron suggests (thank you 🙏) and redefine `to_ary` in the delegator:

```ruby
class MyDelegator < SimpleDelegator
  def method_missing(...)
    # etc
  end

  private

  # @note fixes warning when calling [[MyDelegator], [MyDelegator]].flatten
  # This reimplements what ActiveRecord:Base does.
  def to_ary
    nil
  end
end
```

**Comment by Gbeschbacher** [comment]
Thank you @developius for the linked articles! It surely helped me understand the underlying decisions! 👏🏼 🙌🏼
