### ISSUE TITLE
PG::Coder.new(hash) is deprecated

### ISSUE THREAD

**Issue by wawer77** [rails/rails#48060]
### Steps to reproduce
Update pg gem to 1.5.0.
https://github.com/ged/ruby-pg/blob/master/History.md

### Expected behavior
Deprecated method PG::Coder.new(hash) is not used anymore in activerecord.

### Actual behavior
Deprecated method PG::Coder.new(hash) is still used in:
`activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:980`

Warning is printed in console:
```
PG::Coder.new(hash) is deprecated. Please use keyword arguments instead! Called from /app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:980:in `new'
```

### System configuration
**Rails version**:
7.0.4.3

**Ruby version**:
3.2.0 (2022-12-25 revision a528908271)

**Comment by morgoth** [comment]
This is already fixed via https://github.com/rails/rails/pull/48048
