### ISSUE TITLE
ActiveRecord::Associations::CollectionProxy shovel method behaves different from rails 6.0.6.1 to 6.1.7.3

### ISSUE THREAD

**Issue by theobarango** [rails/rails#48074]
### Summary
Unlike in rails 6.0.6.1, `ActiveRecord::Associations::CollectionProxy` is behaving like a set in rails 6.1.7.3 where it no longer allows concating objects with the same object ID.

### Steps to reproduce

```ruby
class Person < ApplicationRecord
  has_many :friends
end

class Friend < ApplicationRecord
  belongs_to :person
end

p = Person.new # instantiate new Person memory object not persisted to db

p.friends
# => ActiveRecord::Associations::CollectionProxy []

friend = Friend.new # instantiate new Friend memory object not persisted to db

p.friends << friend

puts p.friends.size
# => 1

# add the same friend record again
p.friends << friend

puts p.friends.size
# in rails 6.0.6.1 the result will be 2
# in rails 6.1.7.3 the result is 1
```

### Expected behavior

I expected that after adding the same friend object to the friends collection proxy twice, the size of the collection will increase by 2 as was the case in rails 6.0.6.1, especially as since this change was not documented in the changelog for Rails 6.1 😄 

### Actual behavior

In rails 6.1.7.3, the size remains at 1. Is `ActiveRecord::Associations::CollectionProxy` now behaving like a set and enforcing that its elements have unique object IDs?

### System configuration
**Rails version**: 6.1.7.3

**Ruby version**: 2.7.6

**Comment by skipkayhil** [comment]
Hey @theobarango, thanks for opening an issue. Can you explain why you are expecting the previous behavior? (or are you just concerned about the change not being in the changelog?)

Ref #43445

**Comment by theobarango** [comment]
Hi @skipkayhil Hartley, thank you for getting back to me.

Yes my concern is that it was not included in the changelog, causing some of our specs that depended on this behaviour to fail following the upgrade to rails 6.1.7.3.

Looking at the PR I can see the motivation for the behaviour though. FWIW, i'm not asking for the behaviour to be reinstated, just pointing out that it was sort of a 'breaking change' that wasn't documented in the changelog.

**Comment by skipkayhil** [comment]
I missed it last time I looked but there actually was a CHANGELOG entry for that PR in 6.1.5: https://github.com/rails/rails/blob/8798a6f2aa95e12f37993ba3c5a80fd0ac813dbb/activerecord/CHANGELOG.md?plain=1#L163-L165

Since the change was actually documented, I'm going to close this as I don't think there's much else to do here.
