### ISSUE TITLE
Column type inference is sometimes broken for group counts using joins

### ISSUE THREAD

**Issue by wooly** [rails/rails#48089]
### Steps to reproduce

1. Create a new postgres database called `join_bug`
2. Run the script
3. See error

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "join_bug")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, id: :uuid, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!

    assert_equal({1 => 1}, Comment.joins(:post).group('posts.id').count)
  end
end
```

### Expected behavior

You should get a hash of the count of records grouped by workspace id.

### Actual behavior

You get garbage.

### System configuration
**Rails version**:
7.0.4

**Ruby version**:
3.0.2

**Comment by wooly** [comment]
The bug comes about because of the difference in types for the ID columns on the two tables. I've looked into this a little bit and while I'm not sure how to solve it gracefully, it appears that the issue is in the `type_for` method here: https://github.com/rails/rails/blob/main/activerecord/lib/active_record/relation/calculations.rb#L525 This is returning UUID instead of integer because `@klass` is the `Topic` (with the UUID primary key) rather than the `Workspace`.

**Comment by fatkodima** [comment]
That was fixed by me in https://github.com/rails/rails/pull/46923, but the backport to `7-0-stable` is missing, so I opened a PR with a backport.

**Comment by fatkodima** [comment]
@byroot This can be closed.
