### ISSUE TITLE
Request for documentation of PostgreSQL `numeric` type

### ISSUE THREAD

**Issue by peterbecich** [rails/rails#48098]
PostgreSQL supports a `numeric` datatype. It takes two optional arguments:

```
NUMERIC(precision, scale)
```
https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL

Active Record already supports this type:
https://github.com/rails/rails/blob/912096d4ce930b8e7e5d91e0c86bae2091fda0e4/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L646C7-L664

However, `numeric` is not included in the "Active Record and PostgreSQL" documentation: https://guides.rubyonrails.org/active_record_postgresql.html

Can it be included?

----------------------

I am not certain the Active Record support for this `NUMERIC(precision, scale)` type is working correctly. The arguments may be thrown away, and the PostgreSQL type created is the "unconstrained numeric" datatype. Or I may just be using Active Record incorrectly.

Thank you

**Comment by louim** [comment]
Hey! My understanding is that [the Numeric and Decimal types are equivalents](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-DECIMAL:~:text=The%20types%20decimal%20and%20numeric%20are%20equivalent.%20Both%20types%20are%20part%20of%20the%20SQL%20standard.). Both `precision` and `scale` are supported as arguments when adding a decimal column: https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_column:~:text=%3Aprecision%20%2D%20Specifies%20the,%3Anumeric%20columns. ActiveRecord will automatically handle the casting in and out of the database and use BigDecimal to represent those values.

**Comment by ghiculescu** [comment]
> I am not certain the Active Record support for this NUMERIC(precision, scale) type is working correctly. The arguments may be thrown away, and the PostgreSQL type created is the "unconstrained numeric" datatype. Or I may just be using Active Record incorrectly.

Could you share your code to demonstrate the issue?
