### ISSUE TITLE
syntax error, unexpected tLABEL

### ISSUE THREAD

**Issue by MuhammadRazaAslam** [rails/rails#48090]
### Steps to reproduce

I'm trying to rails [bult-in cache store](https://github.com/rails/rails/pull/31134)  but I'm getting an error. 

**Here are the steps to reproduce the issue:**
Add the following code in the `config/environments/production.rb` or create a `.rb` file and execute it.

```ruby
config.cache_store = :redis_cache_store, driver: :hiredis,
    compress: true, expires_in: 90.minutes,
    url: ''
```

### Expected behavior

It shouldn't give me an error.
### Actual behavior

I'm getting the following error.

```
syntax error, unexpected tLABEL
...e = :redis_cache_store, driver: :hiredis,

```
### System configuration
**Rails version**:
6.1.7.2
**Ruby version**:
2.7.6

**Comment by fatkodima** [comment]
You need to wrap options in a hash braces:
```ruby
config.cache_store = :redis_cache_store,  {driver: :hiredis,
    compress: true, expires_in: 90.minutes,
    url: '' }
```

**Comment by venkat-clone** [comment]
Try using the following code this should work `config.cache_store = :redis_cache_store, {
  driver: :hiredis,
  compress: true,
  expires_in: 90.minutes,
  url: ''
}
`
