### ISSUE TITLE
High allocation overhead due to details_cache_key

### ISSUE THREAD

**Issue by headius** [rails/rails#48156]
I have been profiling JRuby on Rails, in particular looking for excess object allocations, and one method from Rails seems to consistently be in the top five allocation sites: the hash dup in `details_cache_key`.

https://github.com/rails/rails/blob/08a18c75ff1a2d8f20e64f9935dd118f47358662/actionview/lib/action_view/lookup_context.rb#L65-L71

If I'm understanding this code right, it's using a Hash as a key to look up the correct view for a given request. In my benchmarks, it appears to follow this "formats" path, duping the Hash and adding an additional format (I think?).

This dup accounts for anywhere from 10-15% of all object allocations in one profile I took. It varies, but it's clearly allocating a lot of objects.

Is there a lighter-weight way to generate such a key? Is there something I can change in my application or benchmark to avoid this `formats` dup?

**Comment by headius** [comment]
Commenting out the whole `formats` block here does not appear to affect basic usage nor my benchmark, but I'm still not sure I understand what it is doing.

**Comment by ghiculescu** [comment]
> Commenting out the whole `formats` block here does not appear to affect basic usage nor my benchmark

Does it make any Rails tests fail?

**Comment by casperisfine** [comment]
If I'm understanding that code correctly, I think we can easily avoid that dup in most cases.

`details[:formats] &= Template::Types.symbols` ensure that the `:formats` list is a subset of `Template::Types.symbols`.

We can assume it's already true in most cases, and only dup if it isn't true.

**Comment by headius** [comment]
Looks good! I'll run it through profiling later but this should fix the problem.
