### ISSUE TITLE
Unable to run rails from Procfile.dev

### ISSUE THREAD

**Issue by vasilevskykv** [rails/rails#48169]
### Steps to reproduce

Install yarn
```npm install -g yarn```
```yarn set version berry```
Install rails
```gem install rails```
Create new rails project using command 
```rails new MyProject -T -css bootstrap -j esbuild```
Install bootstrap:
```rails css:install:bootstrap```

Create **start.cmd** file with the following contents:
```ruby
foreman start -f Procfile.dev
```
Run ```start.cmd``` 

**Procfile.dev**
```ruby
web: unset PORT && bin/rails server
js: yarn build --watch
css: yarn build:css --watch
```

### Expected behavior
Normal running of the rails server

### Actual behavior

19:33:13 web.1  | started with pid 25644
19:33:13 js.1   | started with pid 28396
19:33:13 css.1  | started with pid 20436
19:33:13 web.1  | "unset" �� ���� ����७��� ��� ���譥�
19:33:13 web.1  | ��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
19:33:14 web.1  | exited with code 1
19:33:14 system | sending SIGTERM to all processes
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/engine.rb:201:in `kill': Invalid argument (Errno::EINVAL)
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/engine.rb:201:in `kill_children'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/engine.rb:473:in `terminate_gracefully'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/engine.rb:439:in `wait_for_shutdown_or_child_termination'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/engine.rb:60:in `start'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/cli.rb:42:in `start'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/vendor/thor/lib/thor/command.rb:27:in `run'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/vendor/thor/lib/thor.rb:369:in `dispatch'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/lib/foreman/vendor/thor/lib/thor/base.rb:444:in `start'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/foreman-0.87.2/bin/foreman:7:in `<top (required)>'
        from C:/Ruby32-x64/bin/foreman:32:in `load'
        from C:/Ruby32-x64/bin/foreman:32:in `<main>'
### System configuration
**Operation system**:
Windows 10
**Rails version**:
7.0.4.3
**Ruby version**:
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]

**Comment by hahmed** [comment]
This looks to be an issue with css bundling and support for windows -- https://github.com/rails/cssbundling-rails/blob/main/lib/install/dev. I'm assuming that running `bin/dev` does not work? (which should be included in your app when you run the bootstrap generator). I think we might need to transfer this issue to cssbundling-rails...

btw what are you using to run your shell script? Git Bash, Cygwin, or WSL (`bin/dev` should work with either of those 3).
