### ISSUE TITLE
Rails redis cache storage not working propertly after adding ActiveSupport::MessagePack

### ISSUE THREAD

**Issue by softr8** [rails/rails#48196]
### Steps to reproduce
Setup a rails app with action controller perform caching enabled and redis_cache_store working, then:

```ruby
# Execute this twice
irb(main):002:0> Rails.cache.clear
=> "OK"
irb(main):003:0> Rails.cache.fetch("test") { sleep 1 ; "Más" }
=> "Más"
irb(main):004:0> Rails.cache.fetch("test") { sleep 1 ; "Más" }
/Users/ecruz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-d954155dd8cc/activesupport/lib/active_support/message_pack/serializer.rb:28:in `start_with?': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
```

### Expected behavior
it should return `"Más"` from cache

### Actual behavior
It says `incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)`

Redis CLI shows:
```bash
0.0.0.0:6380> get "test"
"\x00\x04\b[\x06I\"\tM\xc3\xa1s\x06:\x06ET"
0.0.0.0:6380>
```
Looks like Marshal.dump is modifying the original encoding

### System configuration
Anything after #47770

**Comment by obie** [comment]
@jonathanhefner might be worth you taking a look at https://github.com/rails/rails/issues/48195 too, suspicious that it might be related.

**Comment by jonathanhefner** [comment]
Thank you for the bug report, @softr8!  And thank you for trying out the new code!  :bow:

**Comment by benone** [comment]
This issue is still present in main branch (rails-e18791c0bf2e):

```ruby
irb(main):001:0> Rails.configuration.cache_store
=> :mem_cache_store
irb(main):002:0> Rails.cache.clear
Dalli::Server#connect 127.0.0.1:11211
=> [true]
irb(main):003:0> Rails.cache.fetch("test") { "Más" }
/Users/benone/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/rails-e18791c0bf2e/activesupport/lib/active_support/cache/serializer_with_fallback.rb:80:in `try_dump_bare_string': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
```
