### ISSUE TITLE
Avoid database query if querying a not_null constrained column provided a nil value

### ISSUE THREAD

**Issue by wahabmangat** [rails/rails#48219]
Database queries should be avoided, if possible. One of the scenario is when we query a `not_null` constrained `column` to find let's say all the `users` with `id` null, `activerecord` should return `none` relation right away instead of first querying database underlying, avoiding unnecessary query. Similarly if the developer has added not_null constraint to any other column, the similar behaviour should be expected. 
### Steps to reproduce

`User.where(id: nil)` -> should return `User.none`
`User.find_by(id: nil)` -> should return `nil`

### System configuration
**Rails version 7.0.3**:
**Ruby version 3.0.1**:

**Comment by pzac** [comment]
What if the constraint is not validated? Example: https://github.com/ankane/strong_migrations#setting-not-null-on-an-existing-column

**Comment by fatkodima** [comment]
If the column is "NOT NULL", it means that it is actually "NOT NULL". Check constraint is a postgres alternative to it, but in this case the column is not "NOT NULL". We should check only the first case.

I am thinking how popular would be the use case mentioned in the description.

**Comment by abdul-wahab-qbatch** [comment]
> What if the constraint is not validated? Example: https://github.com/ankane/strong_migrations#setting-not-null-on-an-existing-column

@pzac Yes we can execute query for that i.e, skip this from our usecase. But for the most NOT NULL (validate true) constraints, we can skip the query as I suggested.

**Comment by wahabmangat** [comment]
`What if the constraint is not validated? Example: https://github.com/ankane/strong_migrations#setting-not-null-on-an-existing-column`

@pzac Yes we can execute query for that i.e, skip this from our usecase. But for the most NOT NULL (validate true) constraints, we can skip the query as I suggested.

**Comment by wahabmangat** [comment]
Any follow-up on this Issue?
