### ISSUE TITLE
Duplicated `content-type` header with `rack` 2 (not with `rack` 3)

### ISSUE THREAD

**Issue by stac47** [rails/rails#48225]
Hello,

Recently I opened a bug report (https://github.com/rails/rails/issues/47456) about duplicated HTTP headers when running with `RAILS_ENV=production`. At that time, a workaround was to downgrade rack from 3.x to 2.x.

After upgrade to the tip of main, now I can see duplicated headers `Content-Type` and `content-type` with different values.

If I upgrade from rack 2.x to 3.x, only the lower case `content-type` is filled. More precisely, at the time of writing, I have the bug with `rack` 2.2.7 and not with `rack` 3.0.7.

### Steps to reproduce

Create a new application:

```
%  rails new . --main
```
Add `gem "rack", "< 3.0.0"` in the Gemfile and install:

```
% bundle install
```

Add a dummy controller and a view:

```
% bundle exec rails g controller posts
% cat app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end
% cat app/views/posts/index.html.erb
<div>Hello World</div>
```

Also add a route to the index action of the posts_controller:

```
root "posts#index"
```

Now let's run this in production mode:

```
% SECRET_KEY_BASE_DUMMY=1 RAILS_ENV=production bundle exec rails assets:precompile
I, [2023-05-14T16:41:07.031499 #97949]  INFO -- : Writing /Users/stac/development/reproducer-rails-headers/public/assets/application-37f365cbecf1fa2810a8303f4b6571676fa1f9c56c248528bc14ddb857531b95.js
[...]
% SECRET_KEY_BASE_DUMMY=1 RAILS_ENV=production bundle exec rails s
[...]
```

### Expected behavior

There should not be any duplicated `Content-Type`, `content-type` whatever the version of `rack` (well I think: I don't whether Rails 7.1.0 is planned to be rack 3.x only).

### Actual behavior

When no `Accept-Encoding` is passed, we have a duplicate `Content-Type` with same value:

```
% curl -I http://127.0.0.1:3000/assets/application-37f365cbecf1fa2810a8303f4b6571676fa1f9c56c248528bc14ddb857531b95.js
HTTP/1.1 200 OK
Last-Modified: Sun, 14 May 2023 14:41:07 GMT
Content-Type: application/javascript
content-type: application/javascript
vary: accept-encoding
Content-Length: 158
```

When we accept compression:

```
% curl -I http://127.0.0.1:3000/assets/application-37f365cbecf1fa2810a8303f4b6571676fa1f9c56c248528bc14ddb857531b95.js -H "Accept-Encoding: gzip"
HTTP/1.1 200 OK
Last-Modified: Sun, 14 May 2023 14:41:07 GMT
Content-Type: application/x-gzip
content-type: application/javascript
vary: accept-encoding
content-encoding: gzip
Content-Length: 133
```

### System configuration
**Rails version**: Head of main branch
From the `Gemfile.lock`:
```
GIT
  remote: https://github.com/rails/rails.git
  revision: d1028617c5875c2da08007c5db37425481db6737
  branch: main
```

**Ruby version**: MRI 3.2.2

**Comment by ioquatix** [comment]
Thanks for this great repo. If no one else has time to look at this, I'll take a look.

**Comment by skipkayhil** [comment]
Hey @stac47, I opened a PR linked above to fix the issue. Would you mind trying it out to see if it fixes the problem for you?

**Comment by ioquatix** [comment]
Nice work team!
