### ISSUE TITLE
Rails 7.0: Double validation error for `validates_uniqueness_of` when attribute is encrypted

### ISSUE THREAD

**Issue by john-999** [rails/rails#48248]
### Steps to reproduce
In the `User` model, I have an attribute (`User.thing`) that is encrypted and has a uniqueness validation:

``` ruby
class User < ApplicationRecord

  encrypts :thing, deterministic: true, downcase: true
  
  validates :thing, uniqueness: true

end
```

When I attempt to trigger this validation error (by submitting a `User` with a value for this attribute that already exists in a different `User`), the uniqueness error message is displayed 2 times, instead of only once.

When I output and inspect this `User`'s errors in the log file, I see that 1 error message contains the **unencrypted** value, and 1 additional error messages are added for the **encrypted** value.

It looks like this:

``` ruby
#<ActiveModel::Errors [

#<ActiveModel::Error attribute=thing, type=taken, options={:value=>"my_test_string"}>, 
#<ActiveModel::Error attribute=thing, type=taken, options={:value=>"{\"p\":\"35Q9AxGPf1w9uWS3lAkbXZULHiU=\",\"h\":{\"iv\":\"XYR33B22apwOsVwP\",\"at\":\"on8mfHa5ePMUCgVjjn81oQ==\"}}"}>

]>
```
### Actual behavior
2 "duplicate" error messages are generated/displayed.

### Expected behavior
Only 1 error message should be generated/displayed.

### System configuration
- Ruby **3.0.1p64**
- Rails **7.0.4.3**

**Comment by nickborromeo** [comment]
👋 @john-999 can you confirm that this repro script is accurate? I am unable to reproduce the behavior that you are reporting in both `main` and `7.0.0`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "rails", github: "rails/rails", branch: "main"
  gem 'rails', '~> 7.0.4.3'
  # gem "rails", path: "~/nickborromeo/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Encryption.configure(
  primary_key: SecureRandom.alphanumeric(32),
  deterministic_key: SecureRandom.alphanumeric(32),
  key_derivation_salt: SecureRandom.alphanumeric(32),
  support_unencrypted_data: true,
  extend_queries: true,
)

ActiveRecord::Encryption::ExtendedDeterministicUniquenessValidator.install_support

ActiveRecord::Schema.define do
  create_table :users, force: :true do |t|
    t.string :thing
  end
end

class User < ActiveRecord::Base
  encrypts :thing, deterministic: true, downcase: true
  
  validates_uniqueness_of :thing
end

class BugTest < Minitest::Test
  def test_association_stuff
    User.create!(thing: "my_test_string")
    model = User.create(thing: "my_test_string")
   
    # puts model.errors.inspect
    assert_equal 1, model.errors.size
  end
end
```

**Comment by iamradioactive** [comment]
@john-999 , I'm able to reproduce the error with `Case Insensitive` comparison. I'm receiving two errors for single case insensitive validation.

The Bug that I'm able to reproduce could be described as follows:

- Add uniqueness validation to an Encrypted field with case sensitive set to false.
- Two errors objects will be generated incase of a hit in database.
- One object will indicate cipher value and other indicates a plain text.

Sample code that reproduces the error.

```
class User < ApplicationRecord
  validates :thing, uniqueness: { case_sensitive: false }
end
```

This line seems to be the cause of error.

https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L825

 Do you have any other validation on the same field where **case_sensitive** option is set to false?

**Comment by john-999** [comment]
@iamradioactive , I don't have `uniqueness: { case_sensitive: false }` like you, I only use `uniqueness: true` instead.

But no, I don't currently have any other validation on that same field. (I have deactivated all of them for this debugging attempt.)

(And I suppose the fact that the DB column has a "unique index" will not play a role in this matter?)

@nickborromeo , thanks for your script - unfortunately, I'm not yet at that point where I could verify such test scripts.

**Comment by iamradioactive** [comment]
@nickborromeo , I'm not sure why this line validates for the current `encrypted_type`. Since we are already calling super at the start to validate the uniqueness of plain text, it doesn't make sense to re-validate the same thing with cipher text. It should only perform the validations for `previous_type`. Let me know if my understanding is not correct.

https://github.com/rails/rails/blob/main/activerecord/lib/active_record/encryption/extended_deterministic_uniqueness_validator.rb#LL17C19-L17C19

**Comment by nickborromeo** [comment]
@iamradioactive I added that based on previous examples of issues opened related to encryption and `deterministic` set to true. 

The script I shared must not be doing something that you both are doing because I still cannot reproduce this 😅 . With or without the `ExtendedDeterministicUniquenessValidator` and passing in `case_sensitive: false`. 🤔

**Comment by iamradioactive** [comment]
@nickborromeo , I'm able to reproduce to issue with this script. Let me know if you still can't. I also created a sample application as well, which is able to reproduce the issue as well.

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "rails", github: "rails/rails", branch: "main"
  gem 'rails', '~> 7.0.4.3'
  # gem "rails", path: "~/nickborromeo/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Encryption.configure(
  primary_key: SecureRandom.alphanumeric(32),
  deterministic_key: SecureRandom.alphanumeric(32),
  key_derivation_salt: SecureRandom.alphanumeric(32),
  support_unencrypted_data: true,
  extend_queries: true,
)

ActiveRecord::Encryption::ExtendedDeterministicUniquenessValidator.install_support

ActiveRecord::Schema.define do
  create_table :users, force: :true do |t|
    t.string :thing
  end
end

class User < ActiveRecord::Base
  encrypts :thing, deterministic: true, downcase: true
  
  validates :thing, uniqueness: { case_sensitive: false }
end

class BugTest < Minitest::Test
  def test_association_stuff
    User.create!(thing: "my_test_string")
    model = User.create(thing: "my_test_string")
   
    # puts model.errors.inspect
    assert_equal 1, model.errors.size
  end
end
```

**Comment by iamradioactive** [comment]
@nickborromeo , When using a Local version of Rails I removed current `encrypted _type` from `ExtendedDeterministicUniquenessValidator`. The logic now only validates `encrypted_type.previous_encrypted_types` , if they exist. It seems to fix this issue. 

I'm trying to think of a use case where revalidating the field with current ciphered value makes sense.

Reference: https://github.com/rails/rails/blob/main/activerecord/lib/active_record/encryption/extended_deterministic_uniqueness_validator.rb#L11

**Comment by iamradioactive** [comment]
@john-999 , Can you share the logs containing the exact queries being fired?

**Comment by john-999** [comment]
@iamradioactive Well, this is strange: I just created a new sample app containing just the code as explained above, and with that app, I only get 1 validation error (for the unencrypted value), if I output it in the log file:

```
#<ActiveModel::Errors [#<ActiveModel::Error attribute=thing, type=taken, options={:value=>"thing"}>]>
```
Which indicates that my real app has some "special" logic somewhere that causes the 2nd validation error (but I have no idea where).
Also, the result of my sample app would contradict the result of your sample app.

**Comment by zzak** [comment]
It sounds like `encrypts downcase: true` and `validates uniqueness: { case_sensitive: false }` are possibly competing. Which results in the 2 validation errors here.

I _think_ this is still a bug, but needs more investigation.

**Comment by ghiculescu** [comment]
Confirmed https://github.com/rails/rails/pull/48462 will fix this.
