### ISSUE TITLE
Serialized columns with Hashes that contain Unicode characters have `changed?==true` without changes.

### ISSUE THREAD

**Issue by brphelps** [rails/rails#48255]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.blob :blob
  end
end

class Post < ActiveRecord::Base
  serialize :blob
end

UNICODE_CHAR = "\u2022"

class BugTest < Minitest::Test
  def test_dirtiness
    post = Post.create!({blob: {thing: UNICODE_CHAR}})
    refute post.changed?
    post.blob
    refute post.changed?, "reading a property should not cause the model to become dirty"
  end
end
```

### Expected behavior
The test should pass -- Namely, a model object should have `post.changed? == false` after reading a serialized column from the DB

### Actual behavior
`post.changed? == true`. 

This appears to be because reading the value causes the second part of https://github.com/rails/rails/blob/7c70791470fc517deb7c640bead9f1b47efb5539/activemodel/lib/active_model/attribute.rb#L68 to be hit (` type.changed_in_place?(original_value_for_database, value)`).   

It looks like this code (from [serialized.rb](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/type/serialized.rb#LL66C10-L66C72)): 

Is not properly forcing encoding on the old value before comparison, and Unicode values result in escaped values on the newly encoded value but not on the old one. We end up comparing unencoded Unicode with encoded Unicode, and that always results in a `changed? == true` (as long as the property is read from the DB).  

I applied the following prepend in a monkey patch in an attempt to fix it, I don't know if there are side effects as a result: 
```ruby
  module InstanceMethods
    def changed_in_place?(raw_old_value, value)
      unless value.nil?
        raw_new_value = encoded(value)
        false if raw_old_value.nil? != raw_new_value.nil?
        if raw_new_value.present? && raw_new_value.encoding == Encoding::BINARY && raw_old_value.is_a?(ActiveModel::Type::Binary::Data)
          raw_old_value_s = raw_old_value.to_s
          raw_old_value_s.force_encoding(Encoding::BINARY) if raw_old_value_s.encoding == Encoding::UTF_8
        end
      end
      super(raw_old_value, value)
    end
  end
```

This code is mostly just trying to force binary encoding on the raw_old_value as well as the new, and is a little uglier because it's happening outside the native `changed_in_place?`

### System configuration
**Rails version**: 7.1.0.alpha

**Ruby version**: 3.1.3

**Comment by byroot** [comment]
I haven't dug more than that, but I believe the issue here is simply that in Ruby, if you compare `UTF-8` and `BINARY` (aka `ASCII-8BIT`), they can only be equal if they only contain ASCII characters.

Otherwise Ruby doesn't know how to interpret characters outside the ASCII range.

A few note:
  - If you are serializing with YAML, the column should be a `:text` not a `:blob`. But I see how it's easy to make that mistake.
  - I don't think your PR is the way to go. Instead the comparison should be always done with binary strings if the column is a blob.

I'll dig a bit into that code to see if I find a more elegant solution.

**Comment by byroot** [comment]
We fixed a similar bug in the past: https://github.com/rails/rails/pull/40383

**Comment by byroot** [comment]
Fixed in https://github.com/rails/rails/pull/48274 and backported to 7.0.

Thanks for the very good bug report.
