### ISSUE TITLE
Add 'back to top' links to all linked headings

### ISSUE THREAD

**Issue by msucorey** [rails/rails#48277]
### Steps to reproduce
1 . Enter into Rails Guides from a link like https://guides.rubyonrails.org/active_record_migrations.html#references.
2. Observe you are at the 'active_record_migrations' page with scroll to 'references'.
3. Observe there is no 'back to top' or similar link available to quickly get to the top of the page where the table of contents is.

### Expected behavior
A 'back to top' or similar navigation link is available.

### Actual behavior
No 'back to top' or similar navigation ink is available.

### Suggested implementation
`<a class="anchorlink" href="#feature">Back to Top</a>`

### System configuration
N/A

**Comment by zzak** [comment]
I think this would be a welcome addition, do you want to try opening a PR?

The layout for the guides template is here:
https://github.com/rails/rails/blob/main/guides/source/layout.html.erb

Any and all CSS/JS should be in here:
https://github.com/rails/rails/tree/main/guides/assets

LMK if you have any questions! :bow:

**Comment by msucorey** [comment]
Yes I might find the time - not in the near near future, but soon hopefully

**Comment by ally1002** [comment]
Hey guys,

I'm new at contributing into open source issues, I think this one is easy, and good for a first issue, can I get that one?

**Comment by msucorey** [comment]
I will grab in July if no one else does; meanwhile dont' let me stand in the way :)
