### ISSUE TITLE
What should the behaviour of ActiveSupport::CurrentAttributes be with isolation_level = :fiber?

### ISSUE THREAD

**Issue by KJTsanaktsidis** [rails/rails#48279]
I'm designing a logging-related gem which I would like to make compatible with as many Rails apps as possible. This involves passing context about the current request into all the corners of the app. As part of this, I started looking at `ActiveSupport::CurrentAttributes`.

The behaviour of `CurrentAttributes` when you use a Fiber from inside e.g. a controller method depends on the value of `config.active_support.isolation_level`. Consider a controller that does something like this, using the `async` gem as a fiber scheduler to make multiple requests in parallel

```
class Context < ActiveSupport::CurrentAttributes
    attribute :request_id
end

class SomeControllerThatUsesFibers
  before_action do
    Context.request_id = SecureRandom.hex
   end

  def index
    # Make requests in parallel
    Async do
        b = Async::Barrier.new
        b.async do
            # make first request using async-http or something
            Rails.logger.info("did first client req on request_id #{Context.request_id}"
        end
        b.async do
            # make second request
            Rails.logger.info("did second client req on request_id #{Context.request_id}"
        end
        b.wait
    end
  end
end
```

If you have `config.active_support.isolation_level = :thread` (if you're using e.g. Puma or Unicorn), this will work how you expect. The attributes get stored based on a threadlocal key, and all the fibers are in the same thread, so they're all able to read `Context.request_id`. (Also, I imagine that if you tried to use ActiveRecord in one of those fibers, things would be bad, since the connection state would be per-thread).

If you have `config.active_support.isolation_level = :fiber` (e.g. if you're using Falcon), this will _not_ work; each sub-fiber gets its own IsolatedExsecutionScope so `Context.request_id` is nil in the log statements.

This isn't really a bug, it all makes sense if you think about what IsolatedExecutionScope is doing and what it's for. However, I do wonder what the future should hold for doing sub-tasks with fibers like this. 

Should `ActiveSupport::CurrentAttributes` implicitly cascade down when a fiber is created like this? Or should it be the responsibility of the fiber scheduler to do this cascading, perhaps? Is this just a bad idea and nobody should be doing async tasks in controllers like this? Or perhaps CurrentAttributes is the bad idea?

I guess the point of my issue is to ask if anybody has thought about how `ActiveSupport::CurrentAttributes` should work in a world where people are setting `isolation_level = :fiber` and also want to run async tasks in controllers.

**Comment by KJTsanaktsidis** [comment]
Makes sense - I hadn't actually considered that there's not even a way to implement cascading, really, without `Fiber.storage`. Thanks for your thoughts.

**Comment by ioquatix** [comment]
If what you are after, is `Fiber.storage`, and you want backwards compatibility, the most practical solution, today, is to use the `fiber-storage` shim. It is about 95% compatible except with native extensions which explicitly create fibers and the Ruby VM i.e. lazy enumerators, but everywhere else it should just work.

**Comment by mintuhouse** [comment]
Would something like below work until Rails' CurrentAttributes use Fiber.storage?

````ruby
module FiberWrapperClassMethods
  def new(*args, &block)
    current_klass = "::Current".constantize
    cattr = current_klass.attributes
    fiber_proc = proc do |*fiber_block_args|
      current_klass.set(cattr) do
        yield(*fiber_block_args)
      end
    end
    super(*args, &fiber_proc)
  end
end

Fiber.extend(FiberWrapperClassMethods)
````


Tests
````ruby
Current.attributes[:test] = 1
f = Fiber.new do
  Fiber.yield Current.attributes[:test]
  Current.attributes[:test] = 2
  Fiber.yield Current.attributes[:test]
end
puts "outside: #{Current.attributes[:test]}" #=> 1
puts "inside1: #{f.resume}" #=> 1
puts "outside: #{Current.attributes[:test]}" #=> 1
puts "inside2: #{f.resume}" #=> 2
puts "outside: #{Current.attributes[:test]}" #=> 1
````
