### ISSUE TITLE
Inconsistency between route helpers and url_for expectation in nested routes for resources with the same namespace

### ISSUE THREAD

**Issue by vzelenko** [rails/rails#48276]
> I'm not sure if this is actually an issue with rails or my misunderstanding of it.  To demonstrate the problem I would have to build a small version of the full application, and I'm happy to do that if requested.
>
> If the rails core team agrees this to be an actual issue, I'd be happy to make a PR.

### Problem Description
I have a model (RealEstate::Deal) that has another model (RealEstate::Payment) associated to it via `has_many`.  They both are stored in directory `app/real_estate/***` and have corresponding controllers.

I use nested routes like this:

```ruby
# config/routes.rb
Rails.application.routes.draw do
  namespace :real_estate do
    resources :deals do
      resources :payments
    end
  end
end
```

In the form for entering payment I must generate the `url` myself:

```erb
<!-- app/views/real_estate/payments/_form.html.erb -->
<% 
  url = @payment.persisted? ? 
          real_estate_deal_payment_path(@deal, @payment) : 
          real_estate_deal_payemnts_path(@deal) 
%>
<%= form_for [@deal, @payment], url: url do %>
  <%# irrelevant code %>
<% end %>
```

### Expected behavior

```ruby
# url_helper generated from the route definition (`namespace :real_estate { resources :deals { resources :payments } }`):
real_estate_deal_payments_path(@deal) || real_estate_deal_payment_path(@deal, @payment) 

# url_helper EXPECTED by `url_for(@deal) || url_for(@deal, @payment)` (more specifically, form_for([@deal, @payment]):
real_estate_deal_payments_path(@deal) || real_estate_deal_payment_path(@deal, @payment) 
```

That is, when the namespace is the same for both objects, only apply it once to the generated url helper.

### Actual behavior

```ruby
# url_helper generated from the route definition (`namespace :real_estate { resources :deals { resources :payments } }`)
real_estate_deal_payments_path(@deal) || real_estate_deal_payment_path(@deal, @payment) 

# url_helper EXPECTED by `url_for(@deal) || url_for(@deal, @payment)` (more specifically, form_for([@deal, @payment]):
real_estate_deal_real_estate_payments_path(@deal) || real_estate_deal_real_estate_payment_path(@deal, @payment) 
```

### System configuration
**Rails version**:
Rails 7.0.4.3
**Ruby version**:
ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-darwin22]

**Comment by hahmed** [comment]
Hey @vzelenko, I tried this on an app but I'm not able to repro, any chance you could link a repo or use the [bug template](https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller_gem.rb) please?

**Comment by vzelenko** [comment]
Frankly, I'm not sure how to apply a bug report template to this scenario.  Best I can do is put together a small application...

https://github.com/vzelenko/rails-bug-report-48276-demo

**Comment by hahmed** [comment]
Thanks for the repro, I think this makes sense, it looks like there could be an issue with the way polymorphic_urls are determined 🤔

**Comment by vzelenko** [comment]
Great, lmk if I can be of assistance here.

**Comment by CuddlyBunion341** [comment]
This issue is still around in Rails 8.0.
