### ISSUE TITLE
Lazy evaluation breaks ActiveRecord::Relation scoping, with the potential for data leaks

### ISSUE THREAD

**Issue by Qqwy** [rails/rails#48345]
### Steps to reproduce
- Create a class method in an ActiveRecord model, which returns as part of its response a `proc`.
- Inside this proc, perform further work on `self.all`.
- Call this method with a restricted scope, such as through an association (`Post.first.comments`) or by using `where`/`limit`/etc.
- Call the proc which is part of the result.

Below is an example of how and why to do this.
In this example, we're building up a hash to pass to a Liquid template. When there are parts of the hash which would take long to evaluate and are not needed on all pages, they are put in a proc. 
<sub>(In our real codebase, we have a 'lazy hash' wrapper class which automatically performs the `.call()` step whenever a value is a proc)</sub>
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :title
  end
end

class Post < ActiveRecord::Base
  has_many :comments

  def to_liquid_hash
    {
      'id' => self.id,
      'comments' => self.comments.collection_to_liquid_hash
    }
  end
end

class Comment < ActiveRecord::Base
  belongs_to :post

  def self.collection_to_liquid_hash
    puts self.all.to_sql # <- this prints: SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = 1
    {'count' => proc { self.all.count },
     'data' => proc do
       puts self.all.to_sql; # <- this prints: SELECT "comments".* FROM "comments" ❗❗❗
       self.all.map(&:to_liquid_hash)
     end
    }
  end

  def to_liquid_hash
    {
      'id' => self.id,
      'title' => self.title
    }
  end
end

class BugTest < Minitest::Test
  def test_association_stuff
    post1 = Post.create!
    post1.comments << Comment.create!(title: "First")
    post1.comments << Comment.create!(title: "Second")

    post2 = Post.create!
    post2.comments << Comment.create!(title: "Third")

    assert_equal 2, post1.to_liquid_hash["comments"]["data"].call().count # Expected: 2, actual: 3
    assert_equal 1, post2.to_liquid_hash["comments"]["data"].call().count # Expected: 1, actual: 3
  end
end
```

### Expected behavior

**Expected:** `self.all` inside the proc resolves to the same object/scope as `self.all` inside the surrounding method body.

In the example test: `post1.to_liquid_hash["comments"]["data"]` should contain only the comments belonging to `post1` and similarly, the result for `post2` should only contain the comments belonging to `post2`.

### Actual behavior

**Actual:** Inside the proc, `self.all` is `YourModel.all`. All scoping information is lost.

In the example test: `post1.to_liquid_hash["comments"]["data"]` contains data from **all** comments in the application.
And similarly `post2.to_liquid_hash["comments"]["data"]` contains data from **all** comments in the application.

---

### System configuration
**Rails version**: 7.0.5

**Ruby version**: 3.2.2

_(First observed in our production app which still runs Rails 6.0.3 / Ruby 2.7.6. The same behaviour is present there.)_

### Impact

This bug can very easily cause a [data leak](https://en.wikipedia.org/wiki/Data_breach), because suddenly ActiveRecord ends up returning 'all' instances of a model rather than only those under the scope provided by the programmer.

**Comment by rafaelfranca** [comment]
Thank you for the issue, but this isn't really a bug. Relations are lazy evaluated. We are not going to change that. That means that your code need to expect this behavior.

**Comment by rafaelfranca** [comment]
I think a very easy fix for your situation would be:

```
def self.collection_to_liquid_hash
    scope = self.all
    {'count' => proc { scope.count },
     'data' => proc do
       puts scope.to_sq
       scope.map(&:to_liquid_hash)
     end
    }
  end
```

**Comment by Qqwy** [comment]
If this is expected behaviour, could it be documented somewhere? It is very counter-intuitive.
