### ISSUE TITLE
Setting a postgres timestamptz attribute sets the value's timezone to UTC

### ISSUE THREAD

**Issue by stex** [rails/rails#48346]
After updating Rails from 7.0.4.3 to 7.0.5, I started getting weird errors in my tests. Every time I set a value to `my_attribute.tomorrow.beginning_of_day`, it would set it to one day earlier than I expected.

I figured out that setting an attribute would now erase the time zone, resp. set it to UTC instead of keeping the original one which lead to all "00:00" values to become "22:00" on the previous day.

### Steps to reproduce

1. Use a postgres database
2. Use `timestamptz` fields
3. Use a timezone other than UTC
4. Assign a time with zone to a `timestamptz` attribute

Running the same test with Rails 7.0.4.3 passes.

You'll need a postgres database, here's the docker compose file I used for the test below:

```yaml
version: "3"

services:
  db:
    image: postgres:14
    command: postgres -c listen_addresses='*'
    shm_size: 1gb
    environment:
      POSTGRES_PASSWORD: postgres
    restart: no
    ports:
      - "127.0.0.1:5432:5432"
```

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "pg"
end

require "active_record"
require "active_support/all"
require "minitest/autorun"
require "logger"

Time.zone = "Europe/Berlin"
ActiveRecord::Base.time_zone_aware_types |= [:timestamptz]

ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  host: "127.0.0.1",
  user: "postgres",
  password: "postgres"
)

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :timezone_models, force: true do |t|
    t.timestamptz :a_time
  end
end

class TimezoneModel < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    assert_includes ActiveRecord::Base.time_zone_aware_types, :timestamptz
    assert_equal "timestamp with time zone", TimezoneModel.columns.last.sql_type

    now = Time.zone.now
    assert_equal TimezoneModel.new(a_time: now).a_time.zone, now.zone
  end
end

```

### Expected behavior
The time's zone should not change after assigning it to an attribute

### Actual behavior
The time zone changes to UTC

### System configuration
**Rails version**: 7.0.5

**Ruby version**: 3.1.2

If you need more information, please let me know!
I'll go back to 7.0.4.3 for the time being.

**Comment by frodsan** [comment]
@fatkodima Hi! I noticed the following breaking change when casting a `date` field into a `timestamp` field:

```
# Rails 7.0.4.1
>> t = Document.pluck(Arel.sql("DATE_TRUNC('month', date)")).first
>> t.zone
=> nil
>> t.to_s
=> "2022-01-01 00:00:00 +0000"

# Rails 7.0.6
>> t = Document.pluck(Arel.sql("DATE_TRUNC('month', date)")).first
>> t.zone
=> "UTC"
>> t.to_s
=> "2022-01-01 00:00:00 UTC"
```

Could this be related? Thanks! 😄

**Comment by fatkodima** [comment]
`git bisect` shows, that this was introduced in https://github.com/rails/rails/pull/42933. Please, do open a separate issue with a reproduction test script.
