### ISSUE TITLE
I am using rails 7 importmap but error is generated javascript function is not defined on custom js file

### ISSUE THREAD

**Issue by weeggs** [rails/rails#48344]
Recently I am learning to use rails7, but when I use importmap to refer to my  js file, 
I always get an error: [ testalert is not defined ], please help me

testjs.js  is my js file

app/javascript/testjs.js
  `.....`
`  function testalert(){`
`    alert('call from testjs');`
`  }`

app/views/welcome/index.html.erb
  `......`     
  `<input type='button' onclick="testalert();" value='test alert'>`  

importmap.rb
 `pin "application", preload: true`
  `pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true`
  `pin "@hotwired/stimulus", to: "stimulus.min.js", preload: true`
  `pin "@hotwired/stimulus-loading", to: "stimulus-loading.js", preload: true`
  `pin_all_from "app/javascript/controllers", under: "controllers"`
  `pin "testjs", preload: true`

application.js 
  `import "@hotwired/turbo-rails"`
  `import "controllers"`
  `import "testjs"`

app/assets/config/manifest.js
  `//= link_tree ../images`
  `//= link_directory ../stylesheets .css`
  `//= link_tree ../../javascript .js`
  `//= link_tree ../../../vendor/javascript .js`

config/initializers/assets.rb
 ` ......`
 ` Rails.application.config.assets.precompile += %w( testjs.js )`

when i click the button [test alert] should pop up a alert windows ,but always get the error message
![image](https://github.com/rails/rails/assets/2030732/21e84e73-705b-4a36-8d4e-a3ffc61e86b1)

the html head 
![image](https://github.com/rails/rails/assets/2030732/c14d4c47-f214-49e9-baa3-101622003238)

please help me thank you

### System configuration
**Rails version**:
rails 7.0.5
**Ruby version**:
ruby 3.1.2

**Comment by rafaelfranca** [comment]
Please use https://discuss.rubyonrails.org/ for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
