### ISSUE TITLE
Add a Rails Way to get all foreign_keys from a model

### ISSUE THREAD

**Issue by victorlcampos** [rails/rails#48359]
### Steps to reproduce

I was trying to get all foreign_keys that exist on a table and I realize that there is no rails way to get it

### Actual behavior

Model today have a beautiful method .columns that return all columns. On rails c I tried .foreign_keys and PAM!!!, the method does not exist.

I had to do something like this

```rb
  foreign_keys = ActiveRecord::Base.connection.foreign_keys(Model.table_name)
``` 

### Expected behavior

```rb
  Model.foreign_keys
``` 

Will make me less surprise =)

---

I never contributed with rails before and Will be very happy to do it, I start a PR for add this method.
If someone could me guide to where I add tests and if the change make sense, I will be very thanks

**Comment by simi** [comment]
Would you mind to share what's your usecase? Why do you need to get list of `foreign_keys`?

**Comment by victorlcampos** [comment]
We have a select field that we list all columns from a table for user select, but we cant show columns that are FKs

**Comment by byroot** [comment]
I think `connection.foreign_keys` is good enough given this is a fairly niche need.

**Comment by victorlcampos** [comment]
Another example that required less implementation effort, but triggered almost as much consternation: Array#second through #fifth (and #forty_two for good trolling measure). These alias accessors were deeply offensive to a very vocal constituency who decried the bloat (and near end of civilization, for good measure) of something that could as well be written as Array#[1], Array#[2] (and Array[41]).

But both decisions still, to this day, make me smile. I relish getting to write people.third in a test case or the console. No, that’s not logical. It’s not efficient. It may even be pathological. But it continues to make me smile, thus fulfilling the principle and enriching my life, helping to justify my continued involvement with Rails after 12 years of service.

**Comment by simi** [comment]
@victorlcampos btw. there is `ApplicationRecord` today, you can add this method in there to make it specific to your project and available at model level in your app.
