### ISSUE TITLE
How to permit 2D array in strong parameters?

### ISSUE THREAD

**Issue by Baozi2** [rails/rails#48361]
### Steps to reproduce
```ruby
lines  = ActionController::Parameters.new(a: [[1,2], [2,3]])
r = lines.permit a: []
```

### Expected behavior
#<ActionController::Parameters {"a"=>[[1,2], [2,3]]} permitted: true>

### Actual behavior
#<ActionController::Parameters {"a"=>[]} permitted: true>

### System configuration
**Rails version**:
7.0.4.3
**Ruby version**:
 3.0.0

**Comment by rafaelfranca** [comment]
Please use https://discuss.rubyonrails.org/ for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
