### ISSUE TITLE
Add support for Brotli compression to ActiveSupport::Cache::Store

### ISSUE THREAD

**Issue by pawurb** [rails/rails#48368]
Hi, I’m an author of [rails-brotli-cache gem](https://github.com/pawurb/rails-brotli-cache/). I’ve received feedback that it should be proposed upstream. Based on my benchmarks, I’m seeing up to **~25%** less storage space needed for cache entries and also **~20%** better performance because of the faster compression/decompression process. 

Please let me know if you’d be interested in optionally supporting Brotli compression for `Rails.cache` and I will work on PR.

One thing I’m worried about is a seamless migration process for projects that are already using cache with Gzip. I resolved this issue in my gem by adding a custom cache key prefix. But, for the native solution, I think using an internal value prefix similar to `MARK_70_COMPRESSED` should be possible. So old cache entries would still be decompressed with Gzip and only later start using Brotli. But I’m not sure if I’d accept this additional complexity.

I’m looking forward to your feedback on this one.

**Comment by byroot** [comment]
I'll close as you can open a PR if you wish to work on this.
