### ISSUE TITLE
create_or_find_by not preventing race condition

### ISSUE THREAD

**Issue by mbajur** [rails/rails#48379]
### Steps to reproduce
I'm not really able to provide a reproduction steps nor failing test cases as this is caused by a specific race condition 

### Expected behavior
In one of my apps, i have an endpoint that receives a big amount of requests from an external service. For each incoming request, i have to check if record for incoming parameters exists and create it if it doesn't. If it's already there, code should just find it and operate on whatever is already there.

### Actual behavior

Code for that looks as follows:
```
Device.create_or_find_by!(
  identifier: params['device_identifier'],
  push_token: params['pushToken']
)
```

From what i found in the documentation, using `create_or_find_by!` should not be impacted by race condition i am facing **however I can see a following exception being reported**:

```
ActiveRecord::RecordInvalid
Validation failed: Identifier has already been taken, Push token has already been taken
```

Index defined for these two columns is:

```
t.index ["identifier", "push_token"], name: "index_devices_on_identifier_and_push_token", unique: true
```

### System configuration
**Rails version**: 6.1.4.2

**Ruby version**: 2.7.0

**Comment by byroot** [comment]
If that's suitable in your application, yes, that would solve your issue.

**Comment by mbajur** [comment]
Thank you for your support! I will give it a try.

**Comment by rafaelfranca** [comment]
Yes. `create_or_find_by` should not be used with uniqueness valiadation

**Comment by kamipo** [comment]
Previously we addressed this issue by https://github.com/kamipo/retryable_find_or_create_by.

**Comment by byroot** [comment]
That's built-in now https://github.com/rails/rails/commit/023a3eb3c046091a5d52027393a6d29d0576da01
