### ISSUE TITLE
New version of i18n is breaking action_view translation test

### ISSUE THREAD

**Issue by guilleiguaran** [rails/rails#48377]
### Steps to reproduce

1. Upgrade to i18n v1.14.0

2. Run actionview tests:

```
Failure:
TranslationHelperTest#test_raise_arg_overrides_raise_config_option [/Users/guille/src/rails/actionview/test/template/translation_helper_test.rb:134]:
--- expected
+++ actual
@@ -1 +1,2 @@
-"translation missing: en.translations.missing"
+"Translation missing. Options considered were:
+- en.translations.missing"
```

### Expected behavior
Test passing

### Actual behavior
Test broken

### System configuration
**Rails version**: main

**Comment by guilleiguaran** [comment]
Related: https://github.com/ruby-i18n/i18n/pull/654

**Comment by guilleiguaran** [comment]
Fixed with: https://github.com/ruby-i18n/i18n/pull/662

**Comment by yahonda** [comment]
Testing against the i18n master branch which includes ruby-i18n/i18n#662 , 
`test_raise_arg_overrides_raise_config_option` expects `translation` to be lowercase.
while i18n v1.14.0 or higher uses uppercase `Translation` since https://github.com/ruby-i18n/i18n/commit/c5c6e753f31e2c107925cee5fce37639d68a6a9d, so this test will fail.

* Add this entry to Gemfile
```
gem 'i18n', github: "ruby-i18n/i18n", branch: "master"
```

```
$ bin/test test/template/translation_helper_test.rb -n test_raise_arg_overrides_raise_config_option
Running 61 tests in parallel using 8 processes
Run options: -n test_raise_arg_overrides_raise_config_option --seed 14986

# Running:

F

Failure:
TranslationHelperTest#test_raise_arg_overrides_raise_config_option [/home/yahonda/src/github.com/rails/rails/actionview/test/template/translation_helper_test.rb:134]:
--- expected
+++ actual
@@ -1 +1 @@
-"translation missing: en.translations.missing"
+"Translation missing: en.translations.missing"
```

**Comment by guilleiguaran** [comment]
Added a workaround for the test-case: https://github.com/rails/rails/commit/f618fa4bfd202c9be47f0d07f3799eef55e20fef
