### ISSUE TITLE
Action View: Failure: TranslationHelperTest#test_raise_arg_overrides_raise_config_option 

### ISSUE THREAD

**Issue by zzak** [rails/rails#48387]
I was able to reproduce this CI failure on main:
https://buildkite.com/rails/rails/builds/96919#01887df9-b80d-4805-959b-2da508942ca7/1075-1083

### Steps to reproduce

```ruby
# Using Ruby 3.2.2
git clone https://github.com/rails/rails
cd rails
rm Gemfile.lock
bundle install
cd activeview
bin/test test/template/translation_helper_test.rb
```

### Expected behavior
It should pass.

### Actual behavior

```
Failure:
--
TranslationHelperTest#test_raise_arg_overrides_raise_config_option [/rails/actionview/test/template/translation_helper_test.rb:134]:
--- expected
+++ actual
@@ -1 +1,2 @@
-"translation missing: en.translations.missing"
+"Translation missing. Options considered were:
+- en.translations.missing"


bin/rails test /rails/actionview/test/template/translation_helper_test.rb:130
```
 
### System configuration

**Rails version**: main branch
**Ruby version**: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

**Comment by zzak** [comment]
Found in the diff from the last [green](https://buildkite.com/rails/rails/builds/96913#01887deb-052b-4d74-b181-29253819252d) and [red](https://buildkite.com/rails/rails/builds/96915#01887df9-b44d-4255-b05d-3230416a0c06) builds:

```
diff -u green red
--- green       2023-06-03 07:47:22.115499089 +0900
+++ red 2023-06-03 07:46:23.378027181 +0900

...

@@ -538,7 +538,7 @@

     httpclient (2.8.3)

-    i18n (1.13.0)
+    i18n (1.14.0)

       concurrent-ruby (~> 1.0)
```

Downgrading i18n to `0.13.0` (failing CI builds with `0.14.0`) fixes the failures.

**Comment by skipkayhil** [comment]
See #48377 🙂

**Comment by yahonda** [comment]
Closing because it is duplicated with #48377
