### ISSUE TITLE
Should Active Record disable prepared statements if QueryLogs are enabled?

### ISSUE THREAD

**Issue by casperisfine** [rails/rails#48398]
Ref: https://github.com/rails/rails/pull/42240

`ActiveRecord::QueryLogs` was a direct port of Marginalia, and it just hit me that Marginalia was very purposely disabling prepared statements: https://github.com/basecamp/marginalia/blob/c02d3d8404b15004c3432783543b8fc04306927b/lib/marginalia.rb#L67

I think `AR::QueryLogs` should do the same to avoid generating tons of prepared statements, as with query logs each query has a high chance to be unique, making prepared statements a useless overhead.

cc @keeran @eileencodes

**Comment by exterm** [comment]
I believe that since https://github.com/rails/rails/issues/41896, prepared statements are used as a way to filter sensitive data from SQL logs (not just for performance). Enabling `ActiveRecord::QueryLogs` now sanitizing of SQL logs (by disabling prepared statements). This was surprising to me.

By default, we seem to be getting the `application` key (should be constant) and either `job` or `index` and `controller`.

I'm thinking the cardinality should be OK?

**Comment by exterm** [comment]
Would it make sense for Rails to use explicit binds (enabling #41896) even when prepared statements are disabled?

**Comment by byroot** [comment]
Can you reproduce this with a script? And if so open an issue. Because I don't think that is the case. Prepared statements or not shouldn't change anything about logging.

**Comment by exterm** [comment]
I may be misunderstanding but I believe that https://github.com/rails/rails/pull/42006/files filters the binds, and without prepared statements there don't seem to be binds to filter. My understanding (and observation) is that without prepared statements, the values will be in the sql string itself.

Reproduce with a script? 🤔 I think one could set up a minimal Rails app to reproduce this, yes. Just enable `ActiveRecord::QueryLogs`, create a table with an `email` column, and look at the logs for queries for it. I don't really have the time right now but I'll try to get to it

**Comment by byroot** [comment]
There are binds regardless of whether prepared statements are enabled or not. At least up until the logging point.

If you are experencing a problem please open an issue with repro steps.

**Comment by byroot** [comment]
See https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case for how to provide a reproduction.
