### ISSUE TITLE
Rails cache Entry expired_at and expired_in confusion

### ISSUE THREAD

**Issue by dawei-nava** [rails/rails#48391]
### Steps to reproduce
In active support cache.rb

The Entry class has following initializer

```ruby
def initialize(value, compressed: false, version: nil, expires_in: nil, expires_at: nil, **)
    @value      = value
    @version    = version
    @created_at = 0.0
    @expires_in = expires_at&.to_f || expires_in && (expires_in.to_f + Time.now.to_f)
    @compressed = true if compressed
=end
```

Looks like we are setting @expires_in as expires_at argument if exists, which I think is the absolute unix time.

But in the method following

```ruby
def expired?
  @expires_in && @created_at + @expires_in <= Time.now.to_f
end
```
Clearly it uses @expired_in as a relative time shift?

Is my understanding wrong or there is something going on here I did not get.

### System configuration
**Rails version**: 7.0.4.3

**Ruby version**: 3.2.2

**Comment by byroot** [comment]
The code is a bit contrived for backward compatibility reasons, but it works as it should.

**Comment by dawei-nava** [comment]
Oh, my, but that expired method is totally wrong.
