### ISSUE TITLE
Link headers generated by Rails may exceed nginx's upstream limit

### ISSUE THREAD

**Issue by nateberkopec** [rails/rails#48402]
### Steps to reproduce

1. Create a view with 100s of javascript_include_tags.
2. You now have a response with a fairly large Link header. 
3. If that Link header is over 4kb and you are using Nginx as a reverse proxy, Nginx serves an error with `upstream sent too big header while reading response header from upstream`.

Nginx requires that the _entire_ headers of an upstream response be less than the configured `proxy_buffer_size`, which is only 4kb by default on 64bit Linux. 

Currently, Rails can generate a Link header of unlimited size (split into 8kb field/value pairs). 

### Expected behavior

At some point, adding additional assets to the Link header is not really useful. The browser will only download so many assets at once.

Should we have a limit here?

cc @casperisfine

**Comment by byroot** [comment]
Yeah, as discussed on Slack, I agree on all counts here. 

A 1kb default limit seem like it would be more than plenty.
