### ISSUE TITLE
Translations for active record model not working

### ISSUE THREAD

**Issue by theobarango** [rails/rails#48424]
According to https://edgeguides.rubyonrails.org/i18n.html#translations-for-active-record-models if I set my `config/locales/en.yml` file with the translations from the docs, then `Model.model_name.human` should read from my custom translations, but that's not working. 

I don't know if i'm missing a crucial step in setup, but i've also confirmed that my `I18n.load_paths` includes my `config/locales/en.yml` file.

### Steps to reproduce

```ruby
# user.rb
class User < ActiveRecord::Base
# has a name attribute
end

# config/locales/en.yml
en:
  activerecord:
    models:
      user: 'Superhuman'
    attributes:
      user:
        name: "Username"

# console
User.model_name.human
User.human_attribute_name('name')
```

### Expected behavior

I expected that the above 2 commands should return the following, given my translations override:

```
User.model_name.human
# => 'Superhuman'

User.human_attribute_name('name')
# => 'Username'
```
### Actual behavior

I instead received the Rails defaults:

```
User.model_name.human
# => 'User'

User.human_attribute_name('name')
# => 'Name'
```
### System configuration
**Rails version**: 6.1.7.3

**Ruby version**: 2.7.6

fwiw **I18n version**: 1.7.1

**Comment by fatkodima** [comment]
Rails 6 is not supported for bug fixes (see https://guides.rubyonrails.org/maintenance_policy.html). Can you verify the bug persists with the latest rails version?

**Comment by fatkodima** [comment]
This feature is available from the very old rails versions, I was thinking that you maybe hit some bug, because your setup looks correct at a glance. It will be helpful if you can create a sample app with the newest rails that reproduces the issue, and share with us.

**Comment by eileencodes** [comment]
Hey @theobarango - I tested this in a demo app and it works correctly. We don't have the bandwidth to offer application support so if this doesn't appear to be a bug it would be better to use stackoverflow or the [forum](https://discuss.rubyonrails.org/) to ask for help. Thanks for understanding!
