### ISSUE TITLE
Additional Query incase of Uniqueness validation for Encrypted Attribute

### ISSUE THREAD

**Issue by iamradioactive** [rails/rails#48445]
### Steps to reproduce

- Set Deterministic option to true for an Encrypted attribute
- Add uniqueness validation for the Same Encrypted attribute

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "rails", github: "rails/rails", branch: "main"
  gem 'rails', '~> 7.0.4.3'
  gem "sqlite3"
  gem "pry"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Encryption.configure(
  primary_key: SecureRandom.alphanumeric(32),
  deterministic_key: SecureRandom.alphanumeric(32),
  key_derivation_salt: SecureRandom.alphanumeric(32),
  extend_queries: true,
)

ActiveRecord::Encryption::ExtendedDeterministicUniquenessValidator.install_support

ActiveRecord::Schema.define do
  create_table :users, force: :true do |t|
    t.string :thing
  end
end

class User < ActiveRecord::Base
  encrypts :thing, deterministic: true#, downcase: true
  validates :thing, uniqueness: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    User.create!(thing: "my_test_string")
    model = User.create(thing: "my_test_string")
   
    puts model.errors.inspect
    assert_equal 1, model.errors.size
  end
end
```

### Expected behavior

- Single Query should be fired per encryption type for a uniqueness validation.
- Single validation error should be raised per encryption type.

### Actual behavior
**Case A - downcase: false or unset**

- Two queries will be fired when trying to validate the uniqueness of the attribute.
- Both the queries will be the same, validating encrypted strings against the database values.
- Two uniqueness validation errors will be raised.

**Case B - downcase: true**

- In this case, the number of queries will remain the same i.e. 2 but only a single validation error will be raised.
- This is because the encrypted_string is converted to downcase before comparison.

### Reason for the additional query
- This call in [extended_deterministic_uniqueness_validator](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/encryption/extended_deterministic_uniqueness_validator.rb#L20) treats the encrypted value as an original value for the attribute and converts the value as per upon the options specified (for eg: downcase)

### Possible solution

The [loop](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/encryption/extended_deterministic_uniqueness_validator.rb#L17) should be changed to only iterate over **[*encrypted_type.previous_types]**. In other words, it should exclude the current encrypted/ciphered value.

An additional query with the current encrypted/ciphered value should not be fired. I'm unable to think of any use case where this re-validation is needed. Additional queries for previous_types makes sense.

I need another set of eyes, maybe someone from the Core team or someone who has worked on the Encrypted module for confirmation. After that, I can go ahead and create a PR for the changes.

**Additional context:** https://github.com/rails/rails/issues/48248

### System configuration
**Rails version**: 7.0.4.3
**Ruby version**: 3.0.1

**Comment by iamradioactive** [comment]
Draft: https://github.com/iamradioactive/rails/tree/remove_additional_query

**Comment by justinko** [comment]
Booo - this needs to be reopened. Currently experiencing this bug. Thanks @iamradioactive

**Comment by iamradioactive** [comment]
@justinko , I have already created a PR that fixes this issue. It's awaiting review from someone with the write access to the repository.

PR: https://github.com/rails/rails/pull/48462
