### ISSUE TITLE
`actioncacle integration` CI have been failing since https://buildkite.com/rails/rails/builds/97055

### ISSUE THREAD

**Issue by yahonda** [rails/rails#48453]
### Steps to reproduce
Rails CI `actioncacle integration` have been failing since https://buildkite.com/rails/rails/builds/97055

### Expected behavior
It should pass. 

### Actual behavior
There are some reasons why they have been failing.

https://buildkite.com/rails/rails/builds/97055#0188a23b-c197-4afd-bb36-a4360d1de807/1059-1072
> 09 06 2023 22:17:11.268:ERROR [launcher.sauce]: Can not start chrome 70
  Failed to start Sauce Connect:
  'create tunnel' request failed with: URL https://saucelabs.com/rest/v1/rubyonrails/tunnels - 400 (Bad Request) Error: HTTP request failed. Server response: 400: Too many active user tunnels: 10 >= 10 (ref: 8e9fd488).

https://buildkite.com/rails/rails/builds/97099#0188ac73-a004-43a2-84c1-66389d63bd58/1060-1090
> 11 06 2023 22:03:16.737:ERROR [launcher]: safari 12 (macOS 10.13) on SauceLabs failed 2 times (timeout). Giving up.

### System configuration
**Rails version**: main branch

**Ruby version**: Ruby 2.7, 3.0, 3.1, 3.2 and 3.3.0dev

**Comment by guilleiguaran** [comment]
I think this might be related to the alert shown on the SauceLabs website: https://status.saucelabs.com/

**Comment by yahonda** [comment]
Thanks for the info.
CI are green now https://buildkite.com/rails/rails/builds/97114 after https://status.saucelabs.com/incidents/t980tkf7xpqc is resolved.
