### ISSUE TITLE
ActiveRecord::Store 7 unexpacted behaviour

### ISSUE THREAD

**Issue by dixent** [rails/rails#48461]
### Description

After updating Rails 6 to Rails 7 I found failed specs that include store defining in models. I have made research on this problem and looks like the roots came from sources. Looks like `stores` in the 7 version behave unstably. Please have a look:

Test repo with existing specs: https://github.com/dixent/activerecord_7_store

### Steps to reproduce
1. Create a model with field :jsonb, null: false, default: {}
```ruby
create_table :applicants do |t|
      t.jsonb :settings, null: false, default: {}
      t.string :name
      t.timestamps
    end
```
2. Define store for `settings`
```ruby
# app/models/applicant.rb
class Applicant < ApplicationRecord
  store :settings, accessors: [ :age, :phone_number ], coder: JSON
end
```

3. Then two existing problems, all these spec fail, but must pass. If you remove `store :settings, accessors: [ :age, :phone_number ], coder: JSON` from the model all tests pass successfully.
```ruby
# spec/models/applicant_spec.rb
require 'rails_helper'

describe Applicant do
  subject(:new_applicant) { described_class.new }

  it 'must except record without settings' do
    expect(Applicant.create.id).to_not be(nil)
  end

  describe '#order' do
    let!(:low) { Applicant.create(settings: { phone_number: '111' }) }
    let!(:high) { Applicant.create(settings: { phone_number: '222' }) }

    it 'must work order by phone_number DESC' do
      expect(Applicant.order(Arel.sql("settings -> 'phone_number' DESC")).ids).to eq([high.id, low.id])
    end

    it 'must work order by phone_number ASC' do
      expect(Applicant.order(Arel.sql("settings -> 'phone_number' ASC")).ids).to eq([low.id, high.id])
    end
  end
end
```

### System configuration
**Rails version**: 7.0.5

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
Can you recreate a test script using this template -  https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb?

**Comment by dixent** [comment]
> Can you recreate a test script using this template - https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb?

I hope it helps.
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  database: ":memory:"
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :applicants do |t|
    t.jsonb :settings, null: false, default: {}
    t.string :name
    t.timestamps
  end
end

class Applicant < ActiveRecord::Base
  store :settings, accessors: [ :age, :phone_number ], coder: JSON
end

class BugTest < Minitest::Test
  def test_creating_without_settings
    assert_equal Applicant.create.class, Applicant
  end

  def test_order_by_phone_number
    low = Applicant.create(settings: { phone_number: '111' })
    high = Applicant.create(settings: { phone_number: '222' })

    assert_equal Applicant.order(Arel.sql("settings -> 'phone_number' DESC")).ids, [high.id, low.id]
    assert_equal Applicant.order(Arel.sql("settings -> 'phone_number' ASC")).ids, [low.id, high.id]
  end
end
```

**Comment by fatkodima** [comment]
The test case is failing for me even for rails 6 and 5. `JSON` coder does an extra serialization and the data in the postgres table is stored not as a "hash" in `jsonb` column (as you are expecting), but as a hash serialized into json string.
As stated in the documentation, you really should use `store_accessor` method instead (see https://api.rubyonrails.org/classes/ActiveRecord/Store.html).

**Comment by dixent** [comment]
> The test case is failing for me even for rails 6 and 5. `JSON` coder does an extra serialization and the data in the postgres table is stored not as a "hash" in `jsonb` column (as you are expecting), but as a hash serialized into json string. As stated in the documentation, you really should use `store_accessor` method instead (see https://api.rubyonrails.org/classes/ActiveRecord/Store.html).

Oh, I see. Sorry for wasting your time.
![image](https://github.com/rails/rails/assets/25899828/ae0e8600-e093-4809-a40c-c6125719cc5e)
