### ISSUE TITLE
Convenience methods like `Arel.if`, `Arel.coalesce`

### ISSUE THREAD

**Issue by elebow** [rails/rails#48476]
With the recent move toward making Arel a public API (ref https://github.com/rails/rails/pull/47438, https://github.com/rails/rails/pull/46485), are there any thoughts on adding some convenience methods to `Arel`?

I have been using this locally for a little while:

```ruby
module Arel
  def self.coalesce(*exprs)
    Nodes::NamedFunction.new "COALESCE", exprs
  end

  def self.if(*exprs)
    Nodes::NamedFunction.new "IF", exprs
  end
end
```

I can open a PR if there is interest.

**Comment by akhilgkrishnan** [comment]
@elebow We already have `coalesce` defined in Arel. Ref: https://github.com/rails/rails/blob/27b12e9249572d267e9ebf9f64b5bb2c21070f0d/activerecord/lib/arel/factory_methods.rb#L45-L47
