### ISSUE TITLE
Enhancements to the Rails Generate Command for Easier Setup

### ISSUE THREAD

**Issue by ptamarshall** [rails/rails#48479]
Dear Rails Development Team,

I'm writing to suggest potential improvements to the `rails generate` command, specifically around setting up complex model associations and setting default values.

1. **Complex Model Associations**: Currently, `rails generate model` can create a polymorphic association at the database level but doesn't specify the polymorphic association in the model files. It would be beneficial if the command could also update the model files with the appropriate association. 

    Consider a blogging platform where a Comment can belong to either a Post or another Comment:

    ```bash
    rails generate model Comment user:references commentable:references{polymorphic} content:text
    rails generate model Post user:references title:string content:text
    ```

    In this scenario, developers still need to manually edit the model files to add the correct associations. If `rails generate model` could also add these associations, it would save developers time and reduce potential errors.

2. **Default Values**: The `rails generate model` command does not currently provide an option to set default values for fields. If this functionality was added, developers could specify default values right in the `rails generate model` command.

    For example:

    ```sh
    rails generate model Post user:references title:string content:text views:integer{default:0}
    ```

    In this example, a `Post` model is generated with a `views` field that has a default value of `0`.

Thank you for considering these suggestions. Your work is greatly appreciated.

Best regards,

Pete Marshall

**Comment by hahmed** [comment]
I think both of these are more of a feature request than a bug, that second one has been reported previously over at https://github.com/rails/rails/issues/46207. Mostly the issue tracker is for tracking bugs, so I think this should be closed.

Feel free to submit a PR to address those issues.

**Comment by fatkodima** [comment]
@ptamarshall Regarding 1:

For `rails generate model Comment user:references commentable:references{polymorphic} content:text` I got:
```ruby
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end
```

> In this scenario, developers still need to manually edit the model files to add the correct associations.

Did you mean to add association to `User`?
