### ISSUE TITLE
default_form_builder for ActionMailer::Base

### ISSUE THREAD

**Issue by dub357** [rails/rails#48477]
This isn't a bug report but maybe a feature request...

The `ActionController::FormBuilder` module was created so that controllers can easily define the default form builder for any views they render.  I would like to see the same functionality added to mailers.  Currently the only way (that I know of) to define the form builder defaults for views rendered by ActionMailer::Base is to use an initializer or something in the vein of:

`config.action_view.default_form_builder = MyFormBuilder`

However if controllers use the `default_for_builder` method, that overrides the initializer code for the controller and its subclasses and the only way to get around that is for a subclass to then call `default_for_builder` itself.  The problem is, if a view is shared by both a mailer and a controller, the mailer doesn't pick up that same form builder default and the mailer throws errors if the view tries to render the view and it uses methods defined in the custom form builder.

It seems that I can monkey-patch this behavior in via:
`ActionMailer::Base.include ActionController::FormBuilder`

This adds the `default_form_builder` method for ActionMailer::Base and seems to work, but I dont think it feels right.  Even though actionmailer depends on actionpack, other code in actionmailer depends on AbstractController and not ActionController and this seems to be something related to the view. 

Anyway - it just feels like the different mechanisms currently in place for defining the default form builder for controllers seems to be disconnected with respect to mailers.  Maybe I'm missing something?

**Comment by ghiculescu** [comment]
> Maybe I'm missing something?

I think probably just that it's atypical for an email to have a form in it. But it's not impossible. So i think this is worth doing. I've put together a PR: https://github.com/rails/rails/pull/48542

**Comment by ghiculescu** [comment]
That said, we typically don't take feature requests here. We prefer the [discussion forum](https://discuss.rubyonrails.org/) for features, and the issue tracker for bugs. So I am going to close this as not being an issue. We can move discussion to the PR.
