### ISSUE TITLE
`fork_tracker` active support module does not play nice with `passenger` and `zk` gems

### ISSUE THREAD

**Issue by niodice** [rails/rails#48475]
### Environment setup
- Install `rails 6.1.7.3`
- Install latest passenger using `gem install passenger`. The version as of writing this issue is `6.0.18`
- Create a demo server using `rails new blog`
- Add `gem 'zk', '1.10.0'` to `Gemfile`
- Create the following initializer:
  ```
  # file: blog/config/initializers/zookeeper.rb
  require 'zk'
  
  # following instructions from here: https://github.com/zk-ruby/zk/wiki/Forking.
  # this ends up running the code here:
  #   https://github.com/zk-ruby/zk/blob/release/1.10.0/lib/zk/install_fork_hooks.rb
  ZK.install_fork_hook
  ```

At this point, I can start my rails server with passenger without any issues by running:

```
$ RAILS_ENV=production passenger start
```

### Steps to reproduce

> Note: I'm unsure how to package this particular issue into an executable test script but will try my best to give instructions below:

If I depend on the `fork_tracker` active support module, I start to run into problems. In my actual application this module is imported transitively, but I can force the import easily for the sake of a test case by modifying my initializer:

```
# file: blog/config/initializers/zookeeper.rb
require 'zk'
require 'active_support/fork_tracker'

ZK.install_fork_hook
```

Now, when I run my application with passenger I see some issues introduced by the fork_tracker module:

```
RAILS_ENV=production passenger start
=============== Phusion Passenger(R) Standalone web server started ===============
PID file: /Users/niodice/workspace/oss/rails-repro/blog/tmp/pids/passenger.3000.pid
Log file: /Users/niodice/workspace/oss/rails-repro/blog/log/passenger.3000.log
Environment: production
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger(R) Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================
[ N 2023-06-14 12:14:46.7575 69509/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 69555 output: /Users/niodice/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.3/lib/active_support/fork_tracker.rb:27:in `fork':
App 69555 output: super: no superclass method `fork' for PhusionPassenger::PreloaderSharedHelpers:Module (NoMethodError)
App 69555 output: Did you mean?  for
App 69555 output: 	from /Users/niodice/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/zk-1.10.0/lib/zk/install_fork_hooks.rb:15:in `fork_with_zk_hooks'
App 69555 output: 	from /Users/niodice/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.3/lib/active_support/fork_tracker.rb:13:in `fork'
App 69555 output: 	from /Users/niodice/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.3/lib/active_support/fork_tracker.rb:27:in `fork'
App 69555 output: 	from /Users/niodice/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.3/lib/active_support/fork_tracker.rb:13:in `fork'
App 69555 output: 	from /Users/niodice/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7.3/lib/active_support/fork_tracker.rb:27:in `fork'
App 69555 output: 	from /Users/niodice/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/passenger-6.0.18/src/ruby_supportlib/phusion_passenger/preloader_shared_helpers.rb:108:in `handle_spawn_command'
App 69555 output: 	from /Users/niodice/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/passenger-6.0.18/src/ruby_supportlib/phusion_passenger/preloader_shared_helpers.rb:78:in `accept_and_process_next_client'
App 69555 output: 	from /Users/niodice/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/passenger-6.0.18/src/ruby_supportlib/phusion_passenger/preloader_shared_helpers.rb:167:in `run_main_loop'
App 69555 output: 	from /Users/niodice/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/passenger-6.0.18/src/helper-scripts/rack-preloader.rb:207:in `<module:App>'
App 69555 output: 	from /Users/niodice/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/passenger-6.0.18/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 69555 output: 	from /Users/niodice/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/passenger-6.0.18/src/helper-scripts/rack-preloader.rb:29:in `<main>'
```

### Expected behavior
- It seems that the introduction of the `fork_tracker` does not play nicely out of the box with passenger and the zookeeper gems. I'd expect that this to continue working with the introduction of the `fork_tracker` module, as this module should not break forking behavior.

### Actual behavior
- The exception pasted above is encountered.

### System configuration
**Rails version**: 6.1.7.5

**Ruby version**: 3.0.5

I understand that there is a _lot_ happening with the definition of `Kernel.fork` here, as both the `zk` gem and the `activesupport` module are modifying the behavior. I would appreciate suggestions on how to work around this problem without breaking other behavior.

**Comment by eileencodes** [comment]
> Note: I'm unsure how to package this particular issue into an executable test script but will try my best to give instructions below:

For more complex bugs, you can provide a new Rails application that demonstrates the issue. Rails 6.1 is only supported for security vulnerabilities and isn't receiving bug fix backports, so the reproduction should be done with `main` ideally, or 7.0.

**Comment by niodice** [comment]
> > Note: I'm unsure how to package this particular issue into an executable test script but will try my best to give instructions below:
> 
> For more complex bugs, you can provide a new Rails application that demonstrates the issue. Rails 6.1 is only supported for security vulnerabilities and isn't receiving bug fix backports, so the reproduction should be done with `main` ideally, or 7.0.

Noted. I did just re-test with rails 7.0 and observed the same behavior

```
$ cat Gemfile | grep "gem 'rails'"
gem 'rails', '~> 7.0', '>= 7.0'
```

Also, I'm unsure if this is a "bug" or if there is general advice for working around this. I am open to either of these.

**Comment by niodice** [comment]
One finding - If I remove `::Kernel.prepend(CoreExtPrivate)` (rails `6.1.7.3` or `7.0`) then the error goes away

**Comment by byroot** [comment]
IMO the issue is on the ZK side. The way they do alias method chain doesn't compose well, they should use `prepend` like Active Support.

Additionally, I added `Process._fork` in Ruby 3.1, they should use that when available to make their life easier.

Please report this to the `zk` gem.
