### ISSUE TITLE
PostgreSQL Range adapter throws `NoMethodError` for an empty string value

### ISSUE THREAD

**Issue by clairity** [rails/rails#48486]
when trying to save a postgres `int4range` value that is an empty string (as would be submitted by a form post with a blank value), the postgresql adapter throws a `NoMethodError`. but when `nil` is passed, it handles that gracefully and inserts a `null` value into the field in postgres, as expected.

```sh
> User.new(my_int_range: "").save
NoMethodError: undefined method `split' for nil:NilClass
from .../activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb:70:in `extract_bounds'
> User.new(my_int_range: nil).save
=> true
```

it looks like there are safeguards in place to handle exceptional values like `nil`:

https://github.com/rails/rails/blob/dfc365949b1b18f8a25eb4eec696982442ed28f7/activerecord/lib/active_record/connection_adapters/postgresql/oid/range.rb#L20-L24

but an empty string is not handled gracefully. at the very least, the error returned is misleading, as it should really tell you that an empty string is an invalid value for range types. however, for range types, it seems empty strings should be handled the same way as `nil` values, given that they're always invalid (rather than indicating an empty value), and be converted to `null` for persistence rather than erroring out.

**Comment by ghiculescu** [comment]
Thanks for reporting this @clairity - would you like to make a PR to fix it?

**Comment by clairity** [comment]
@ghiculescu i looked into it a bit but i don't think i understand the codebase well enough to know where to put things or what things to put in.
