### ISSUE TITLE
`ActiveSupport::RangeWithFormat` fails for beginless and endless ranges

### ISSUE THREAD

**Issue by clairity** [rails/rails#48485]
### Steps to reproduce / Actual behavior
i stumbled across this issue while experimenting with Range support on the rails console:

```sh
> (0..1).to_fs(:db)
=> "BETWEEN '0' AND '1'"
> (..1).to_fs(:db)
RangeError: cannot get the first element of beginless range
from .../activesupport/lib/active_support/core_ext/range/conversions.rb:33:in `first'
> (0..).to_fs(:db)
RangeError: cannot get the last element of endless range
from .../activesupport/lib/active_support/core_ext/range/conversions.rb:33:in `last'
```

### Expected behavior
```sh
> (0..1).to_fs(:db)
=> "BETWEEN '0' AND '1'"
> (..1).to_fs(:db)
=> "LESS THAN '1'"
> (0..).to_fs(:db)
=> "GREATER THAN '0'"
```

### System configuration
**Rails version**: 7.1.alpha
**Ruby version**: 3.2.2

i realize that the expected messages here are arbitrary (and not part of the default formatter message), and a custom formatter can be added to `Range::RANGE_FORMATS`, but that still won't handle a beginless or endless range as input.

it seems the problem here is passing `first` and `last` rather than `begin` and `end` (which would instead return `nil` for endless/beginless endpoints) on this line of the `to_fs` method referenced in the error:

https://github.com/rails/rails/blob/dfc365949b1b18f8a25eb4eec696982442ed28f7/activesupport/lib/active_support/core_ext/range/conversions.rb#L33

it would be great to be able to format beginless/endless ranges using the built-in `ActiveSupport::RangeWithFormat` feature.

**Comment by ghiculescu** [comment]
Hmm. Maybe this is a dumb question, but is this valid SQL syntax? `"GREATER THAN '0'"`

`BETWEEN` is documented at https://www.postgresql.org/docs/current/functions-comparison.html but `GREATER THAN` is not.

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/pull/48494

**Comment by clairity** [comment]
@ghiculescu @guilleiguaran thanks for fix and the quick turnaround!
