### ISSUE TITLE
complex where cluases including dots are split improperly

### ISSUE THREAD

**Issue by k-kostadinov** [rails/rails#48503]
### Steps to reproduce
use postgress database
create a table( posts),
create a query with complex where statement like `where('CASE WHEN posts.use_created_at_flag THEN posts.created_at ELSE posts.updated_at'=> 2.days.ago..1.day.ago)`

### what happens 
after some investigation i found the method `convert_dot_notation_to_hash`
which takes the 
`CASE WHEN posts.use_created_at_flag THEN posts.created_at ELSE posts.updated_at` splits it byt dot`.split(".")`
and the result is bad.
i would expect it to take the string as is and apply just the > , >=, between, < , <= to the dates.

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.boolean "use_created_at_flag", default: false
    t.datetime "created_at", precision: nil, null: false
    t.datetime "updated_at", precision: nil, null: false
  end
end

class Post < ActiveRecord::Base
end


class BugTest < Minitest::Test
  def test_complex_where
    Post.create!(use_created_at_flag: true, created_at: 3.day.ago)
    Post.create!(use_created_at_flag: false, created_at: 3.day.ago)
    Post.create!(use_created_at_flag: true, created_at: 2.day.ago)
    Post.create!(use_created_at_flag: false, created_at: 2.day.ago)
    Post.create!(use_created_at_flag: true, created_at: 1.day.ago)
    Post.create!(use_created_at_flag: false, created_at: 1.day.ago)

    Post.where('created_at' => 2.days.ago..1.day.ago).size # will work perfectly 
    Post.where('CASE WHEN posts.use_created_at_flag THEN posts.created_at ELSE posts.updated_at'=> 2.days.ago..1.day.ago).size # will will throw an error

  end
end

```

### Expected behavior
I would expect to get the results 

### Actual behavior

.../activerecord-7.0.4.3/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "CASE WHEN posts" (ActiveRecord::StatementInvalid)
LINE 1: SELECT COUNT(*) FROM "posts" WHERE "CASE WHEN pos...

### System configuration
**Rails version**:
Rails 7.0.4.3

**Ruby version**:
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

I am not sure that this is a bug or a bit like feature expansion or inteded behaviour.
I couldn't make the test run with postgress so it is a bit useless
i am grateful for any attention to this issue of mine

**Comment by matthewd** [comment]
This is expected behaviour; the keys in the hash form of `where` are fields (model attributes), not arbitrary SQL expressions.
