### ISSUE TITLE
Why does ActiveRecord query on association with singular table name instead of plural create an alias instead of error?

### ISSUE THREAD

**Issue by justinpchang** [rails/rails#48502]
### Steps to reproduce
- Database schema must have any model `Foo` which has a has_one relationship to model `Bar`.
- `Foo.joins(:bar).where(bar: { col: val })`
- Notice that the generated SQL will look like `...INNER JOIN "bars" "bar" ON "bar"."foo_id" = "foos"."id"...`
- This command will execute as expected, but from the SQL, we see that it has automatically aliased the `bars` association to the singular `bar`.
- If somewhere in the Query Chain, you use raw SQL because it is more complex, such as `.order("foos.col ASC, bars.col DESC")` and use the Rails standard pluralized table name, this will error out since the table has been aliased behind the scenes.

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', github: 'rails/rails', branch: 'main'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    Comment.create!(post: Post.create!)

    # 1. Signular in join (correct), plural in query (correct)
    assert_equal Comment.joins(:post).where(posts: { id: 1 }).pluck(:id), [1]
    # Generates the following SQL (notice no "posts" alias):
    # SELECT "comments"."id" FROM "comments" INNER JOIN "posts" ON "posts"."id" = "comments"."post_id" WHERE "posts"."id" = ?  [["id", 1]]

    # 2. Signular in join (correct), singular in query (INCORRECT -  but works?)
    assert_equal Comment.joins(:post).where(post: { id: 1 }).pluck(:id), [1]
    # Works, but creates the following SQL (notice automatic "post" alias):
    # SELECT "comments"."id" FROM "comments" INNER JOIN "posts" "post" ON "post"."id" = "comments"."post_id" WHERE "post"."id" = ?  [["id", 1]]

    # 3. Signular in join (correct), singular in query (INCORRECT), using raw SQL (fails!)
    assert_raises(ActiveRecord::StatementInvalid) do
      Comment.joins(:post).where(post: { id: 1 }).order('comments.id ASC, posts.id DESC').pluck(:id)
    end

    # 4. Plural in join (INCORRECT) - throws error
    assert_raises(ActiveRecord::ConfigurationError) { Comment.joins(:posts).pluck(:id) }
  end
end

```

### Expected behavior
- I would expect the singular table name in the query to raise a `ActiveRecord::ConfigurationError`, just as using an incorrectly pluralized table name in a JOIN raises.

### Actual behavior
- Instead, ActiveRecord tries to correct the incorrect syntax behind the scenes by aliasing the table name, which is not obvious and unintuitive.

### System configuration
**Rails version**:
7.0.5
**Ruby version**:
3.2.0

**Comment by p8** [comment]
I've bisected this to the following commit: 68c4103d70d3b401583b670e87cde3268da1841f
We probably need to backport: https://github.com/rails/rails/pull/47940

**Comment by rafaelfranca** [comment]
Already fixed on 7-0-stable
