### ISSUE TITLE
javascript_include_tag's implicit modulepreload Link header insertion breaks importmaps

### ISSUE THREAD

**Issue by aaronjensen** [rails/rails#48517]
If you use importmaps along with something like `javascript_include("some-module", type: "module")` you end up with an error in the Chrome Devtools:

`An import map is added after module script load was triggered.`

This happens even if the import map is before the script tag. You may need to be running Puma or another server that supports early hints.

This behavior is opaque and overly presumptuous. I cannot find an obvious way to disable it other than to write script tags without the helper. Please provide a means for disabling the behavior or make it opt-in.

**Comment by ghiculescu** [comment]
Thanks for the report. Could you please provide a minimal demo app that we can use to replicate the issue? That'll make it easier to debug and fix.

**Comment by aaronjensen** [comment]
Sorry, I should have included reference to the underlying issue: https://github.com/WICG/import-maps/issues/273

There's nothing to debug and fix, this is just not supported by importmaps. You cannot use moduleprelod header early hints and importmaps together, period:

https://github.com/WICG/import-maps/issues/273#issuecomment-1097276232

Note that one does not typically run into this, because when people use importmaps they typically use `javascript_import_module_tag`, which does not use early hints. However, I have a use case where I need to load a module that isn't in my importmap (but uses modules that *are* in my importmap).

That said, here's an app that demonstrates the issue: https://github.com/aaronjensen/importmap-early-hints-repro

The specific commit: https://github.com/aaronjensen/importmap-early-hints-repro/commit/67166e40e0565e0803135193ba5659364b04f0a5

**Comment by ghiculescu** [comment]
FYI those links don't work.

**Comment by aaronjensen** [comment]
Thanks, sorry, it was private. Try now.

**Comment by ghiculescu** [comment]
Okay cool, so is the ask for a way to opt out of the `rel` attribute entirely here:

https://github.com/rails/rails/blob/7a033f58ab3a17ea0b0066aeb604507f73017ff3/actionview/lib/action_view/helpers/asset_tag_helper.rb#L119-L124

**Comment by aaronjensen** [comment]
They are only incompatible if you are using importmaps. If you are not, they would work fine.

In my opinion the entire preload links/early hints functionality should be opt-in. It is maximally surprising to have my headers changed as a side effect of adding a javascript tag to my page. I'd be fine with either a config-level opt-in and/or a invocation level (`javascript_include_tag "some-javascript", preload_link_header: true`) or whatever.

**Comment by ghiculescu** [comment]
> In my opinion the entire preload links/early hints functionality should be opt-in.

It is, at least at a global level. You can set [`config.action_view.preload_links_header = false`](https://guides.rubyonrails.org/configuring.html#config-action-view-preload-links-header).

**Comment by aaronjensen** [comment]
OK, that's good that it can be disabled globally, thanks for pointing that out. I do still think it's the wrong default (provably so as it's a footgun w/ importmaps).

The interesting thing is that I don't necessarily mind the behavior (as long as I can opt out at the invocation level).

**Comment by aaronjensen** [comment]
Thanks, though note that this doesn't actually fix anything. It just makes it possible for someone to work around the issue once they know it exists. It still has implicit and surprising behavior that breaks when used with importmaps, which are included in Rails by default. The user that encounters it will do what I did and have to dive into a rabbit hole and hope to discover what Rails is doing, then figure out that what Rails is doing is fundamentally flawed when used with importmaps and then discover that there's a way to opt out of it.

With luck, they may stumble onto this issue and cut out some of that journey, but that would just be luck.

**Comment by ghiculescu** [comment]
@aaronjensen is your proposal that we turn default `preload_links_header` to `false`? That seems to me like it will have more cons than pros, but happy to have the discussion. If not that, then I'm not sure what you are suggesting, if anything.

**Comment by aaronjensen** [comment]
That would be the simplest solution, yes. The entire feature is, while convenient, incredibly surprising (this can be said about many things in Rails).

So yes, disabling it by default and requiring a user to opt-in would alleviate that, but it would also mean that many people would never get the performance benefit from it. Personally, I think that's a reasonable trade-off. After all, if they are trying to squeeze that level of performance out, they may very well find this feature and opt into it.

The other possible consideration would be to add even more complexity. That is, once importmap-rails is installed, it could disable preload links but only for modules. This is the level of coupling and entanglement that would immediately signal to me that something was wrong and that's why I would personally opt for disabling it entirely.

I recognize I'm battling uphill here, since this is Rails, but having been burned by it, I feel I have to at least advocate for an approach that does not burn, but still gives those who are most interested in the performance increase that control while increasing transparency (and removing opaque defaults).

**Comment by ghiculescu** [comment]
> That is, once importmap-rails is installed, it could disable preload links but only for modules

This seems like it might be a valid idea. I think it's worth copying this suggestion to the `importmap-rails` repo.

**Comment by aaronjensen** [comment]
You're of course welcome to do that, but I do not intend to advocate for adding further complexity to that project and this ecosystem, since I know where that leads -- even more complexity and headaches for our fellow developers. I was only mentioning that possibility to demonstrate that complexity begets complexity.
