### ISSUE TITLE
Should ActionDispatch::Executor be moved higher up the middleware stack?

### ISSUE THREAD

**Issue by KJTsanaktsidis** [rails/rails#48528]
### Steps to reproduce

Currently, the `ActionDispatch::HostAuthorization` and `ActionDispatch::Static` middlewares, amongst others, are ordered before `ActionDispatch::Executor`. Let's say we want to include a custom middleware to instrument requests. This middleware should go before `HostAuthorization` and `Static`, because we want to instrument requests which fail host authorization or hit static files; on the other hand, they should go after `Executor` because the [threading and code execution](https://guides.rubyonrails.org/threading_and_code_execution.html) rails guide says that user code should be wrapped in an Executor.

I suspect this might cause problems with the autoloader not working on such middleware, but actually there is another practical problem with including the instrumentation before `Executor`. If the instrumentation middleware wants to use a `ActiveSupport::CurrentAttributes` class, the values stored in there are cleared when the executor middleware calls the `run` callbacks.

### Expected behavior
I believe the Executor middleware should come first, perhaps? The only reason I can think of not to do this is an efficiency concern of booting up the executor unnecessarily for serving static files without user code intervention. 

* Is there any reason I shouldn't re-order this middleware in my own app?
* Would this be something that should be changed in Rails by default?

### Actual behavior
Any values stored in `ActiveSupport::CurrentAttributes` in middlewares before `Executor` are cleared when Executor is run.

**Comment by rafaelfranca** [comment]
I do think we can move it to be the first one, but in fact I don't think the Executor should be a middleware at this point. It is too important to be reordered, or even delayed. I believe it should just be called in the `Application` `#call` method.

@byroot @matthewd do you know any reason why we would not make the Executor not optional in the form of a middleware?

**Comment by byroot** [comment]
That seem like an option, I don't forsee particular problem, but it would be interesting to check which middleware are currently sitting before it. e.g. Perhaps `ShowException` in case an executor callback raise? Things like that.

**Comment by matthewd** [comment]
I feel like the middleware stack is in a constant state of tension because everything feels like it should happen before everything else 😅 

https://github.com/rails/rails/blob/c25cc2ead272a4c3965795139124dfe62ee5a79e/railties/test/commands/middleware_test.rb#L131-L133

**Comment by KJTsanaktsidis** [comment]
> it would be interesting to check which middleware are currently sitting before it

Assuming I’m not missing anything important…

- `ActionDispatch::HostAuthorization`
- `ActionDispatch::AssumeSSL`
- `ActionDispatch::SSL`
- `Rack::Sendfile`
- `ActionDispatch::Static`
- `Rack::Cache`
- `Rack::Lock`

I don’t think any of these are benefiting from being above Executor, except maybe Lock? Actually I wonder if  we should implement `config.allow_concurrency` by putting a lock around `ExecutorWrapper#run!` and dispensing with `Rack::Lock` entirely; that way (in theory) _all_ calls to app code should be protected, including hypothetical calls from e.g. gems that have background threads.

If you reckon this makes sense I’m happy to make a PR tomorrow deleting these middlewares & unconditionally calling the executor.

**Comment by KJTsanaktsidis** [comment]
The “static files shouldn’t be affected by config.allow_concurrency = false” thing is interesting…

“Allow user code to run around static file serving calls” and “don’t invoke user-provided code in static file serving to avoid the Lock middleware” as ideas seem in complete tension.

dare I suggest, invoking the executor before middleware if allow_concurrency = true, otherwise leaving things how they are? Seems like a lot of complexity to carry around for the disjunction of two kind of niche use cases though.

**Comment by matthewd** [comment]
Again, SendFile should not be holding database connections while it's sending the file.

HostAuthorization should be stopping incoming requests as early as possible, _before_ they start doing potentially-resource-consuming things.

If we're going to stop early and do an SSL redirect, again, that should happen before we start doing anything significant.

Wanting to wrap user code around requests that are not being handled by the user application is an outlying requirement, and not something the stack is designed to accomodate. Rearranging things to support it would degrade behaviour for most applications.

**Comment by KJTsanaktsidis** [comment]
Sorry I also was writing my first reply whilst you were writing yours! 

Sounds like nothing really bad would result from lifting executor in my own app then, since we don’t serve many static file requests (I hope!). But I agree there are some finely balanced interactions here and changing the default isn’t appropriate.

I kind of wonder how many rails apps out there are injecting middlewares at the top of the stack, before the executor. Certainly we have quite a number, although by luck (or perhaps due to somebody before me who understood this all better!) none of them are using ActiveRecord, CurrentAttributes, etc, so we’re not missing any of the cleanup there.

**Comment by KJTsanaktsidis** [comment]
@rafaelfranca @matthewd sounds like we’re happy with the ordering how it is, and we _dont_ want to move the executor out of rack middleware? If so I’ll go ahead and close this.
