### ISSUE TITLE
Change in ActiveRecord JSON/JSONB Query Behavior from Rails 6.0 to 6.1

### ISSUE THREAD

**Issue by JohnAnon9771** [rails/rails#48535]
### Steps to reproduce
In Rails 6.0, create a query on a JSON/JSONB column in PostgreSQL using an array of hashes:

```ruby
store_ids = [{ "store_id" => 7 }, { "store_id" => 8 }]
where(dimensions: store_ids) # This works as expected in Rails 6.0
```

Then, run the same query in Rails 6.1:

```ruby
store_ids = [{ "store_id" => 7 }, { "store_id" => 8 }]
where(dimensions: store_ids) # This returns [] in Rails 6.1
```

### Expected behavior
The query should return the same results in Rails 6.1 as it did in Rails 6.0. The ActiveRecord should convert the array of hashes into a JSON representation that PostgreSQL can understand.

### Actual behavior
In Rails 6.1, the query returns an empty array. It appears that ActiveRecord is no longer converting the array of hashes into a JSON representation that PostgreSQL can understand.

As a workaround, I've had to convert the store IDs into strings and use PostgreSQL's `->>` operator syntax:

```ruby
store_ids = [7, 8].map(&:to_s)
where("dimensions->>'store_id' in (?)", store_ids) # This works as expected in Rails 6.1
```

### System configuration
**Rails version**: 6.1

**Ruby version**: 2.7.7

**Comment by fatkodima** [comment]
Can you verify if the issue still persists with the latest changes from the `main` branch? If so, can you create a reproducible test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_main.rb template?

**Comment by abaldwin88** [comment]
Looks like the issue persists on `main`.  Here's a reproduction script...

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "activerecord", "~> 6.0.0" # PASS
  # gem "activerecord", "~> 6.1.0" # FAIL
  gem "rails", github: "rails/rails", branch: "main" # FAIL

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :locations, force: true do |t|
    t.json :dimensions
  end

end

class Location < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_json_where
    post = Location.create!(dimensions: { store_id: 7 })

    store_ids = [{ "store_id" => 7 }, { "store_id" => 8 }]
    assert_equal 1, Location.where(dimensions: store_ids).size
  end
end
```

**Comment by fatkodima** [comment]
Thanks for the test case, that was helpful! The problem is the same as in https://github.com/rails/rails/issues/48072#issuecomment-1523996933. I am going to provide a fix.

**Comment by yahonda** [comment]
Looks like this behavior change was introduced via https://github.com/rails/rails/commit/4b1122c572060e9a2a344608b15dfcbb7ff82213
