### ISSUE TITLE
ActionCable subscriptions are never created because welcome event is not received

### ISSUE THREAD

**Issue by Georgegriff** [rails/rails#48543]
### Steps to reproduce
I apologise upfront that i've not been able to produce a reproduction case, it involves some network conditions which breaks actioncable's default usage

We've been working with some of our customers who have reported our application not working as expected. The area relies on Action Cable subscriptions. We have observed the following behaviour.

1. We Create ActionCable in js
2. We immediately add a subscriber
```js
const consumer = ActionCable.createConsumer("wss://...");
consumer.subscriptions.create(
            ....
);
```
3. Server opens the connection and sends the welcome message (this is the rails code i've been looking at)
4. Websocket opens, but [welcome even](https://github.com/rails/rails/blob/e446ef82c8174a4bd6c98f670912bb395b3091d6/actioncable/lib/action_cable/connection/base.rb#L188)t is never received.

The result is that subscriptions are never  reloaded - (internal actioncable code)(https://github.com/rails/rails/blob/e446ef82c8174a4bd6c98f670912bb395b3091d6/actioncable/app/assets/javascripts/actioncable.esm.js#L253) when welcome is received, which should have created the subscription.

It's possible the reason this doesn't come up more is due to some specific network conditions, but we have enough diagnostics gathered in our system to show that this is the issue, we have open websockets but no subscriptions are established.

It is possible to workaround this by creating the subscriptions in the onOpen handler of the websocket instead, but this is circumventing the design of action cable.

In our logging we have collected we have no observed any connection instability.

> The logs are a combination of the action cable logs and some custom event handlers we have added to on message/open, to detect the issue.

```
  [
    "[ActionCable]",
    "Opening WebSocket, current state is null, subprotocols: actioncable-v1-json,actioncable-unsupported",
    1687331929209,
    "Wed, 21 Jun 2023 07:18:49 GMT"
  ],
  [
    "[ActionCable]",
    "ConnectionMonitor started. stale threshold = 6 s",
    1687331929210,
    "Wed, 21 Jun 2023 07:18:49 GMT"
  ],
  [
    "[SUCCESS]",
    "WebSocket onopen event",
    "Wed, 21 Jun 2023 07:18:49 GMT"
  ],
  [
    "[ActionCable]",
    "WebSocket onopen event, using 'actioncable-v1-json' subprotocol",
    1687331929446,
    "Wed, 21 Jun 2023 07:18:49 GMT"
  ],
   [
    "[WARN]",
    "Welcome not received within 20s",
    "Wed, 21 Jun 2023 07:19:09 GMT"
  ]
```
(These are extracted from logs where we have put a work around in place, but we have alerting to detect if the welcome event was never received)

[It's a different library but its possible that something like this might describe the issue? I'd just be guessing though
](https://github.com/pocoproject/poco/issues/1212)

### Expected behavior
ActionCable subscriptions should be initialised once the websocket has opened. The welcome should not be "lost"

### Actual behavior
Subscriptions never establish, websocket just is left open doing nothing.

### System configuration
**Rails version**:
6.1.7.2

[Looks like the logic that linked is broadly the same for actioncable in the version im using.
](https://github.com/rails/rails/blob/8798a6f2aa95e12f37993ba3c5a80fd0ac813dbb/actioncable/lib/action_cable/connection/base.rb#L175)**Ruby version**:
3.1.3
**Action cable NPM version**:
    "@rails/actioncable": "^7.0.4-3",

**Comment by palkan** [comment]
Hey @Georgegriff!

The issue you linked looks interesting, though I never experienced such problems with Action Cable (or AnyCable). The `welcome` event is sent asynchronously after the HTTP Upgrade response, so it shouldn't be our case. However, it's still worth checking this hypothesis: you can add a small `sleep` to the `Connection#connect` method (the `welcome` event is sent only after it has been executed).

Re: logs.

I don't see any logs mentioning subscription attempts (I believe, we should see some from the [guarantor](https://github.com/rails/rails/blob/d87ecd04671c3967f4a334e9f947ddc2140aea33/actioncable/app/javascript/action_cable/subscription_guarantor.js#L12)).

How do you check that `welcome` hasn't been received? (This log line: `Welcome not received within 20s`).
