### ISSUE TITLE
Render from before_action does not respect request format

### ISSUE THREAD

**Issue by mikerobe** [rails/rails#48550]
### Steps to reproduce
See https://github.com/rails/rails/issues/32179

When a call to `render` is made from within a `before_action` in a controller, it does not respect the request format. This issue recently led to an unexpected behavior where incorrect HTML templates were being rendered for JSON requests.

Here are the steps from the ticket above (created in 2018 then auto closed as stale). 

1. Create before_action function and run render within it:

```
class BeforeController < ApplicationController
  before_action :before_index

  def index
  end

  private
  def before_index
    render partial: 'test'
  end
end
```

2. Create templates for html and js format: `_test.html.erb` and `_test.json.erb`
3. Open index action url.

### Expected behavior
Render uses the format specified in the request, so if open `http://localhost:3000/before/index.html` you see _test.html.erb rendered, and if open `http://localhost:3000/before/index.json` you see _test.json.erb rendered.

### Actual behavior
Default format (_test.html.erb) is being rendered. If make same render execution within index action, format specified in the request is being used.

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.2.2

**Comment by iamradioactive** [comment]
@mikerobe, Based on my understanding, [this line](https://github.com/rails/rails/blob/main/actionpack/lib/action_controller/metal/rendering.rb#L163C20-L163C20) appears to be responsible for setting the formats before the controller action. To ensure the formats are correctly set, implementing a before_action could be a suitable solution for now. You can use something similar to the code snippet below, utilizing `prepend_before_action` to ensure this specific action runs before any other before_action in the chain.

```ruby
class ApplicationController < ActionController::Base
  prepend_before_action :set_formats

  def set_formats
    self.formats = request.formats.filter_map(&:ref)
  end
end
```

By implementing this approach, you can ensure that the formats are properly established before executing other before_actions, potentially addressing your use case.

I think the changes should be made to the rails codebase eventually. However, I partially agree with this [comment](https://github.com/rails/rails/issues/32179#issuecomment-371518938) as well. Considering the potential impact of this modification, it would be better to wait for an opinion from someone on the Core team.

**Comment by ghiculescu** [comment]
We probably can't change the behaviour outright as noted in the stale issue. Here's some other ideas for framework level fixes

- We could introduce a config, that defaults to the current behaviour but lets users opt in to `config.action_pack.set_request_format_before_before_action` your preferred behaviour.
- Rails could expose a method (`set_request_formats`) that you can reference in specific controllers (`before_action :set_request_formats`), this way you can opt in to the behaviour on specific requests. Then Rails could also call `set_request_formats` just before rendering, if it hasn't already been called.
- For users using default config, I think it needs to be possible to change the `request.formats` during a `before_action`. This was noted on the stale issue as a potential reason to not change.
