### ISSUE TITLE
Error when providing a class argument to ActiveJob for classes that implement `permitted?`

### ISSUE THREAD

**Issue by adnanrh** [rails/rails#48561]
### Steps to reproduce

1. Write a class MyClass that implements a class method named `permitted?`
2. Write a job BuggyJob with a `perform` method that accepts a class as a parameter
3. Enqueue a BuggyJob job with MyClass as an argument: `BuggyJob.perform_later(MyClass)`

The issue seems to be here: https://github.com/rails/rails/blob/main/activejob/lib/active_job/arguments.rb#L93
It seems in the switch statement to choose the correct serializer for the argument, we attempt to call `serialize_indifferent_hash` on `argument.to_h` if it responds to `permitted?`. I suppose the assumption here is that if the argument responds to `permitted?`, it should be an instance of `ActionController::Parameters`? In our app, we have a module that defines a class method named `permitted?` for some other business logic and it's used in a few classes.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activejob", "~> 7.0.0"
end

require "minitest/autorun"
require "active_job"

class MyClass
  def self.permitted?
    # noop
  end
end

class BuggyJob < ActiveJob::Base
  def perform(klass)
    puts "performed"
  end
end

class BuggyJobTest < ActiveJob::TestCase
  def test_stuff
    error = assert_raises(NoMethodError) { BuggyJob.perform_later(MyClass) }
    assert_match /undefined method `to_h' for MyClass:Class/, error.message
  end
end
```

### Expected behavior

A BuggyJob job should successfully be queued, with the MyClass argument serialized using ActiveJob::Serializers::ModuleSerializer.

### Actual behavior

A NoMethodError is raised:
```
Failed enqueuing BuggyJob to DelayedJob(default): NoMethodError (undefined method `to_h' for MyClass:Class
Did you mean?  to_s)
.../ruby/3.0.0/gems/activejob-6.1.7.3/lib/active_job/arguments.rb:120:in `serialize_argument': undefined method `to_h' for MyClass:Class (NoMethodError)
Did you mean?  to_s
```

### System configuration
**Rails version**: Tested on 6.1.x, 7.0.x

**Ruby version**: Tested on 3.0.4

**Comment by abaldwin88** [comment]
Removing these two lines allows `BuggyJob.perform_later(MyClass)` to be called in the test case without an error being raised

https://github.com/rails/rails/blob/06da26afbabb1681d3d680cac13f70f7623cf69a/activejob/lib/active_job/arguments.rb#L93-L94

**Comment by sampatbadhe** [comment]
How about checking `argument` is responding to `to_h` along with `permitted?`

https://github.com/rails/rails/blob/06da26afbabb1681d3d680cac13f70f7623cf69a/activejob/lib/active_job/arguments.rb#L93

```diff
-        when -> (arg) { arg.respond_to?(:permitted?) }
+        when -> (arg) { arg.respond_to?(:permitted?) && arg.respond_to?(:to_h) }
```
