### ISSUE TITLE
Clarify support status of 6.1

### ISSUE THREAD

**Issue by slondr** [rails/rails#48595]
Rails 6.1.7.x doesn't support Ruby 3.2, but there's no public documentation stating this. 

The 6-1-stable branch contains some fixes related to Ruby 3.2, but has a broken build and seemingly lots of unresolved problems. 

Can the current state of support for Rails 6.1 be made more clear?

**Comment by rafaelfranca** [comment]
It is very clear here https://guides.rubyonrails.org/maintenance_policy.html#security-issues.

6.1 is only receiving security fixes since December 15, 2021.
