### ISSUE TITLE
No way to configure `Strict-Transport-Security` not to be added on `config.force_ssl = true`?

### ISSUE THREAD

**Issue by r7kamura** [rails/rails#48609]
### Steps to reproduce

I would like to use `config.force_ssl = true` for secure cookie and https URL generation. However, my application already has a reverse proxy configured to add `Strict-Transport-Security` header.

### Expected behavior

So I want to use `config.force_ssl = true`, but not add `Strict-Transport-Security` header on the Rails application side, by setting `config.ssl_options`.

### Actual behavior

There appears to be no way to set it up that way. The result is that `Strict-Transport-Security` header is added twice.

As a workaround, I have solved this problem by adding some Rack middleware on the outside that removes this header.

### System configuration
**Rails version**: 7.0.5.1

**Ruby version**: 3.2.1

**Comment by r7kamura** [comment]
I created this issue to talk about whether such a setting should be added, and if so, in what format. If adding such a setting is not worth considering, feel free to close this.

**Comment by skipkayhil** [comment]
There's a test case that looks like it should cover the case you describe:
https://github.com/rails/rails/blob/b214c07558530d8fe7d858cfd8c8a5bd1a8ce03b/actionpack/test/dispatch/ssl_test.rb#L145-L147

Can you create one either here or in a [bug template](https://github.com/rails/rails/tree/main/guides/bug_report_templates) that fails?

**Comment by r7kamura** [comment]
Ideally, I would like to configure my Rails app like the following code so that Strict-Transport-Security header is never set.

```ruby
# config/environments/production.rb
Rails.application.configure do
  config.force_ssl = true

  config.ssl_options = {
    hsts: false
  }
end
```

However, `{ hsts: false }` is already used as a value to set `Strict-Transport-Security: max-age=0`, so it cannot be implemented this way.

So how about adding the following implementation for such cases?

```diff
$ git diff
diff --git a/actionpack/lib/action_dispatch/middleware/ssl.rb b/actionpack/lib/action_dispatch/middleware/ssl.rb
index 9788aaadd9..f285462064 100644
--- a/actionpack/lib/action_dispatch/middleware/ssl.rb
+++ b/actionpack/lib/action_dispatch/middleware/ssl.rb
@@ -68,7 +68,7 @@ def initialize(app, redirect: {}, hsts: {}, secure_cookies: true, ssl_default_re
       @exclude = @redirect && @redirect[:exclude] || proc { !@redirect }
       @secure_cookies = secure_cookies
 
-      @hsts_header = build_hsts_header(normalize_hsts_options(hsts))
+      @hsts_header = build_hsts_header(normalize_hsts_options(hsts)) if hsts != :never
       @ssl_default_redirect_status = ssl_default_redirect_status
     end
 
@@ -77,7 +77,7 @@ def call(env)
 
       if request.ssl?
         @app.call(env).tap do |status, headers, body|
-          set_hsts_header! headers
+          set_hsts_header! headers if @hsts_header
           flag_cookies_as_secure! headers if @secure_cookies && !@exclude.call(request)
         end
       else
diff --git a/actionpack/test/dispatch/ssl_test.rb b/actionpack/test/dispatch/ssl_test.rb
index 5353081fd2..cddea974df 100644
--- a/actionpack/test/dispatch/ssl_test.rb
+++ b/actionpack/test/dispatch/ssl_test.rb
@@ -154,6 +154,10 @@ def assert_hsts(expected, url: "https://example.org", hsts: { subdomains: true }
     assert_hsts "max-age=0; includeSubDomains", hsts: false
   end
 
+  test "hsts: :never does not set Strict-Transport-Security" do
+    assert_hsts nil, hsts: :never
+  end
+
   test ":expires sets max-age" do
     assert_hsts "max-age=500; includeSubDomains", hsts: { expires: 500 }
   end
```

In this way, the requirement "Do not set Strict-Transport-Security" can be satisfied by configuration like this:

```ruby
# config/environments/production.rb
Rails.application.configure do
  config.force_ssl = true

  config.ssl_options = {
    hsts: :never
  }
end
```

The format `{ hsts: :never }` is debatable, but I would at least like to see a configuration method provided for doing such things.

**Comment by skipkayhil** [comment]
I'm still having trouble understanding why the current behavior is wrong. If a proxy is setting the `Strict-Transport-Security` header, then Rails should not be changing it (and there should be no duplicate).

Instead of writing a test with a hypothetical option that you want to pass, can you write a test that just fails right now without any API changes? (for example, that the header should not be duplicated but it is?)

**Comment by r7kamura** [comment]
To demonstrate the double `Strict-Transport-Security` problem I described, I have prepared an example application that combines Nginx and Rails, can you check this?

- https://github.com/r7kamura/rails_nginx_hsts_example

**Comment by guilleiguaran** [comment]
if I understand correctly the problem is that `Strict-Transport-Security` is **always** included if the SSL middleware is turned on, setting `hsts` option to false just sets the header to  `max-age=0` so we really don't have the option to disable it completely.

@r7kamura the proxy you mentioned leaves the header as is if it happens to be already configured by the app, is that right?

**Comment by r7kamura** [comment]
> the proxy you mentioned leaves the header as is if it happens to be already configured by the app, is that right?

Yes, that's right 👍

**Comment by Flixt** [comment]
I think it is debatable if Rails should allow turning off the header at all. With browsers caching the header once seen (even it is not sent anymore) until the max-age is expired, it could just confuse people and the default to have it in place very sane. I'd say it is not Rails responsibility to be able turn off the header. I'd pass the responsibility to the stack in front of the Rails application server (in your case nginx). Shouldn't it be possible to remove the header the application sent and add your own with something like:

```nginx
location @app {
  # ...
  proxy_hide_header Strict-Transport-Security;
  add_header Strict-Transport-Security "max-age=31536000;";
  # ...
}
```

**Comment by guilleiguaran** [comment]
@rafaelfranca If I understand correctly OP wants to add the header *after* the request is returned from Rails to nginx (https://github.com/r7kamura/rails_nginx_hsts_example/blob/main/docker/nginx/nginx.conf#L44) but nginx isn't adding it since it's already set by Rails.

I think the solution proposed by @Flixt (removing the header returned by Rails) is acceptable and we don't need to make any changes on the middleware.

**Comment by rafaelfranca** [comment]
Ahhh, I thought nginx was adding the header to the request. If it only wants to add to response I agree this isn't an Rails issue.
