### ISSUE TITLE
create_enum in migration does not drop type when rolling back

### ISSUE THREAD

**Issue by jarl-dk** [rails/rails#48634]
### Steps to reproduce
Use Postgres backend.

Create a migration like
```ruby
class CreateEnum < ActiveRecord::Migration[7.0]
  def change
    create_enum :direction ["left", "right"]
  end
end
```

Then run
```
rails db:migrate
rails db:rollback
```
### Expected behavior
I expect db/schema.rb not to contain a `create_enum` line

### Actual behavior
The `db/schema.rn` file still contains a `create_enum` line after the rollback.

### System configuration
Rails: 7.0.4
Ruby: 3.1.3

**Comment by fatkodima** [comment]
That is already fixed on `main`.

**Comment by jarl-dk** [comment]
@fatkodima : Can you point to a commit? I cannot confirm it is part of 7.0.7
I consider it to be a bug (not fatal though), so maybe it should be part of minor version release or patch version release.
