### ISSUE TITLE
ActiveRecord serialize stripping obj's attributes before sending the data to the serializer on rails 7.0.5

### ISSUE THREAD

**Issue by TopRoupi** [rails/rails#48652]
upgrading from rails **7.0.4.3** to **7.0.5** causes activerecord models with serialized params to break since the data sent to the serializer on **7.0.5** is now being passed to `deep_dup` before being sent to the serializer, and this makes activerecord objs passed inside the parameters to lose attributes.
this was changed on this commit [activerecord/lib/active_record/relation/predicate_builder.rb](https://github.com/rails/rails/commit/213972e1ef8b50d5a930fed52780846f674eb808#diff-b8fadd6d1ec091c30f94738b9b193b78ec90681790dd3a6aa79938b4dacbe904)

example of a case that this change is causing problems https://github.com/excid3/noticed/issues/296 

### Steps to reproduce
```ruby
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '= 7.0.5'
  # gem 'rails', '= 7.0.4.3'
  gem 'sqlite3'
  gem 'byebug'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :notifications do |t|
    t.json :params
  end

  create_table :comments do |t|
    t.string :body
  end
end

class DummyCoder
  def self.load(data)
    return if data.nil?
    puts "load"
    p data
    "dummy"
  end

  def self.dump(data)
    return if data.nil?
    puts "dump"
    p data
    raise "object has no id" if data[:comment].id.nil?
    "dummy"
  end
end

class Notification < ActiveRecord::Base
  serialize :params, DummyCoder
end

class Comment < ActiveRecord::Base
end

class TestWhereQueryWithSerializedParam < Minitest::Test
  def test_where_query_with_serialized_param
    comment = Comment.create(body: "1")
    notifications = Notification.where(params: {comment: comment}).last
    assert_equal notifications, nil
  end
end
```

### Expected behavior
calling Notification.where(params: {comment: comment}).last should not raise since the `data` variable on `DummyCoder.dump(data)`  method will have an id: `{:comment=>#<Comment id: 1, body: "1">}`

this was the behavior on rails 7.0.4.3 

### Actual behavior
calling Notification.where(params: {comment: comment}).last will raise since the `data` variable on `DummyCoder.dump(data)`  method wont have an id: `{:comment=>#<Comment id: nil, body: "1">}`
which is cause by this new change [activerecord/lib/active_record/relation/predicate_builder.rb](https://github.com/rails/rails/commit/213972e1ef8b50d5a930fed52780846f674eb808#diff-b8fadd6d1ec091c30f94738b9b193b78ec90681790dd3a6aa79938b4dacbe904)

### System configuration
**Rails version**: 7.0.5

**Ruby version**: 3.0.0

**Comment by yahonda** [comment]
This change has been introduced via https://github.com/rails/rails/commit/213972e1ef8b50d5a930fed52780846f674eb808

**Comment by abhisheksarka** [comment]
Not an elegant solution but can work on a case to case basis

```ruby
# Modify the required class to respond to `duplicable?` correctly. 
# Use the `attr_accessor` so as to not affect all instances unless required

class Comment < ActiveRecord::Base
  attr_accessor :duplicable

  def duplicable?
    return super if duplicable.nil?

    duplicable
  end
end

def test_where_query_with_serialized_param
  comment = Comment.create(body: "1")
  comment.duplicable = false
  notifications = Notification.where(params: {comment: comment}).last
  assert_equal notifications, nil
end
```

Passing test case
```ruby
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '= 7.0.5'
  # gem 'rails', '= 7.0.4.3'
  gem 'sqlite3'
  gem 'byebug'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :notifications do |t|
    t.json :params
  end

  create_table :comments do |t|
    t.string :body
  end
end

class DummyCoder
  def self.load(data)
    return if data.nil?
    puts "load"
    p data
    "dummy"
  end

  def self.dump(data)
    return if data.nil?
    puts "dump"
    p data
    raise "object has no id" if data[:comment].id.nil?
    "dummy"
  end
end

class Notification < ActiveRecord::Base
  serialize :params, DummyCoder
end

class Comment < ActiveRecord::Base
  attr_accessor :duplicable

  def duplicable?
    return super if duplicable.nil?

    duplicable
  end
end

class TestWhereQueryWithSerializedParam < Minitest::Test
  def test_where_query_with_serialized_param
    comment = Comment.create(body: "1")
    comment.duplicable = false
    notifications = Notification.where(params: {comment: comment}).last
    assert_equal notifications, nil
  end
end
```

**Comment by casperisfine** [comment]
Ok, so this won't be easy to fix. 

The problem is specific to `ActiveRecord::Base` instance, because `ActiveRecord::Base#dup` doesn't copy the primary key on purpose.

Which means that `deep_dup` should probably be a `deep_clone`, but `Object#deep_clone` doesn't exist, and I'm not sure adding it is quite justified.

That said, I think we could avoid that `deep_dup` for serialized columns, as long as we cache the serialized result and not the source object.

FYI: @tenderlove

**Comment by casperisfine** [comment]
It's very weird. If I remove the patch from https://github.com/rails/rails/pull/46048, it's test still pass: https://github.com/rails/rails/pull/48705

But it was clearly failing at the time, so something else must have changed since then.

**Comment by byroot** [comment]
I backported a fix to `7-0-stable`.
