### ISSUE TITLE
Skips mailer and 7.0.6

### ISSUE THREAD

**Issue by dawidof** [rails/rails#48656]
### Steps to reproduce

```ruby
# Your reproduction script goes here
`rails new --skip-action-cable --skip-active-storage --skip-asset-pipeline --skip-javascript --skip-hotwire --skip-jbuilder --skip-action-mailbox --skip-active-job --skip-test --skip-system-test --api -d=postgresql backend`
```

the key `--no-skip-action-mailer` make no difference

### Expected behavior, Actual behavior

Creating new app with command above it does not generate files for mailer. Also it in `application.rb` mailer is commented out.

<img width="1680" alt="Screenshot 2023-07-05 at 10 02 05" src="https://github.com/rails/rails/assets/1425756/a80ca5f2-a5ea-4671-9662-9edeb797e441">
<img width="1189" alt="Screenshot 2023-07-05 at 10 01 49" src="https://github.com/rails/rails/assets/1425756/37694174-b0d2-40fe-9b62-079a807e694a">

### System configuration
**Rails version**: 7.0.6

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
Works for me on `main`. This was fixed in https://github.com/rails/rails/pull/45520.
