### ISSUE TITLE
BSON Document Deep_transform_keys not converting keys to symbols

### ISSUE THREAD

**Issue by mekasudheer** [rails/rails#48668]
### Steps to reproduce

```ruby
  I see that this issue is coming because we are not converting to hash, instead using the same object at 
  `https://github.com/rails/rails/commit/f5e597638853e5550509347254889d50c738ea56` 
  BSON::Document.new('hello' => {"hello" => {"hello" => 'world'}}).deep_transform_keys(&:to_sym) should convert all the keys to symbols.
```

### Expected behavior
{:hello=>{:hello=>{:hello=>"world"}}}

### Actual behavior
{"hello"=>{"hello"=>{"hello"=>"world"}}}

### System configuration
**Rails version**: 7.0.5 & 7.0.6

**Ruby version**: 3.0.6

**Comment by mekasudheer** [comment]
@d12 could you please check and suggest what we can do here?

**Comment by eileencodes** [comment]
Hi @mekasudheer thanks for opening an issue. I'm not able to reproduce this in a console with Active Support on the current `main` branch. I'm not sure whether this is an issue with Rails, are you able to provide a reproduction using the bug report [templates we provide](https://github.com/rails/rails/blob/main/guides/bug_report_templates/generic_main.rb)? If you can only reproduce this with BSON then it is likely a bug in that library and not in Rails.
