### ISSUE TITLE
Potential bug with use of `create_#{association}!` method.

### ISSUE THREAD

**Issue by rishijain** [rails/rails#48675]
### Steps to reproduce
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "7.0.5"
  gem "debug"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.references :totp_setting
  end

  create_table :totp_settings, force: true do |t|
    t.references :user
  end
end

class User < ActiveRecord::Base
  belongs_to :totp_setting, optional: true

  after_create :setup_totp_setting

  def setup_totp_setting
    create_totp_setting!(user: self)
  end
end

class TotpSetting < ActiveRecord::Base
  belongs_to :user, touch: true

  before_create :set_parent

  def set_parent
    puts '1'*100
    puts user.totp_setting
  end
end

class BugTest < Minitest::Test
  def test_bug
    @user = User.create!
  end
end
```

```ruby
# Your reproduction script goes here
```

### Expected behavior

If you set the rails version to '7.0.4.3' and run the script, the puts statements would print
```
  1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
  nil
```

If you set the rails version to '7.0.5' and run the script, the puts statements would print
```
  1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
  #<TotpSetting:0x00007fcd86d0da80>
```

### Actual behavior
I don't know what behaviour is broken, is the Rails 7.0.4.3 correct or 7.0.5?

### System configuration
**Rails version**:
7.0.4.3 & 7.0.5

**Ruby version**:
2.7.7

### My analysis:
The difference in behaviour was introduced with this commit: https://github.com/rails/rails/commit/bdbe58b50461dc44c42df4d5427fa78aeb1debcb

Specifically this line https://github.com/rails/rails/blob/bdbe58b50461dc44c42df4d5427fa78aeb1debcb/activerecord/lib/active_record/associations/singular_association.rb#L58

If I change that to `build_record` instead of using `build` in Rails 7.0.5 code, it works the same way as 7.0.4.3.
I understand the `build` method calls `build_record` internally and does an additional step `set_new_record` here https://github.com/rails/rails/blob/bdbe58b50461dc44c42df4d5427fa78aeb1debcb/activerecord/lib/active_record/associations/singular_association.rb#L22C8-L22C8.

**Comment by yahonda** [comment]
This behavior has been introduced via https://github.com/rails/rails/commit/bdbe58b50461dc44c42df4d5427fa78aeb1debcb #46799

**Comment by abaldwin88** [comment]
The new behavior in 7.0.5 seems more intuitive to me? I'd expect all references to be assigned in memory by the time `before_create` callbacks are triggered.

Per the docs...

> This object will be instantiated from the passed attributes, the link through this object's foreign key will be set ...

https://guides.rubyonrails.org/association_basics.html#methods-added-by-belongs-to-create-association-attributes

Happens during instantiation before callbacks run.

**Comment by yahonda** [comment]
Closing this issue because this behavior has been restored as Rails 7.0.4 via https://github.com/rails/rails/pull/48809
