### ISSUE TITLE
Custom serialization & storage in ActiveRecord::Encryption (beyond strings)

### ISSUE THREAD

**Issue by maximerety** [rails/rails#48689]
### Steps to reproduce

In https://guides.rubyonrails.org/active_record_encryption.html#supported-types, it is clearly stated:

> **`active_record.encryption` will serialize values using the underlying type before encrypting them, but they must be serializable as strings**. Structured types like serialized are supported out of the box.

As long as you only have string values, a `text`/`varchar` column in the database, and a message serializer that emits and consumes strings (the situation currently described in the docs), everything works just fine.

But I'd like to propose to support a wider range of use cases by **allowing custom serializers that output another type than strings**.

A typical use case would be to use a binary column in the database (e.g. `bytea` in PostgreSQL) and serialize encrypted values using a compact binary format such as the one provided by [MessagePack](https://github.com/msgpack/msgpack-ruby) (example given below), instead of the default JSON string format provided by the default message serializer.

Setting a custom serializer via `config.active_record.encryption.message_serializer` is already supported (https://guides.rubyonrails.org/active_record_encryption.html#encryption-contexts). Unfortunately, it's not possible to make your custom serializer produce binary values and have things work right out of the box.

One small inconvenience is the problem described in https://github.com/rails/rails/issues/48685 (quite straitghforward to fix: https://github.com/rails/rails/pull/48686), but a bigger problem lies in the current design of `ActiveRecord::Encryption::EncryptedAttributeType`.

To make my explanation a bit visual, this is what we have today:

```plaintext
Attribute without encryption:
                          ┌──────┐     
  user-provided value ───►┤ cast ├───► value for the db
                          └──────┘     
                                        
                          ┌──────┐     
   value for the user ◄───┤ cast ├◄─── db-provided value
                          └──────┘     


Attribute with encryption:
                          ┌────────┐    ┌─────────┐    ┌─────────────┐    ┌────────┐     
  user-provided value ───►┤ cast A ├───►┤ encrypt ├───►┤  serialize  ├───►┤ cast B ├───► value for the db
                          └────────┘    └─────────┘    └─────────────┘    └────────┘     
                                                                                         
                          ┌────────┐    ┌─────────┐    ┌─────────────┐    ┌────────┐     
   value for the user ◄───┤ cast A ├◄───┤ decrypt ├◄───┤ deserialize ├◄───┤ cast B ├◄─── db-provided value
                          └────────┘    └─────────┘    └─────────────┘    └────────┘     
```

As of today, the default implementation of `ActiveRecord::Encryption::EncryptedAttributeType` uses the type of the database column as `cast_type` to perform the `cast A` step in the figure, and there is no `cast B` step.

When a value is extracted from the database, there is no type casting before sending it to the message serializer for deserialization. Conversely, a value serialized with the message serializer is sent directly to the database without any further type casting. So, by default, there is no `cast B` step, and only strings are expected to be sent to/received from the database.

As long as you only have string values, a `text`/`varchar` column in the database, and a message serializer that emits and consumes strings (the situation currently described in the docs), everything works just fine.

But with this model, you can't easily switch to a `bytea` column and serialize in database-compatible binary format, because you have no built-in way to perform a `cast B` (binary) which is different from `cast A` (strings).

I think we should recognize the need for two distinct types of casting:

* Casting clear values before encryption (e.g. ensuring correct type/encoding), and;
* Casting encrypted+serialized values before sending them to the database (e.g. sending a message that is serialized in binary format).

Ideally, the framework should allow developers to specify the type of casting they need in a particular place, instead of using the database column type for `cast A` (not always appropriate), and providing no support for `cast B`.

**If you think this could be a good addition to the framework, I would volunteer to help make this happen.**

For completeness, a possible workaround is:

1. To declare the attribute as a string (despite the attribute being stored in a binary format in the database) in order to trick the framework to use a `:string` attribute type when performing `cast A` (see figure above):

    ```diff
      create_table(:records, force: true) do |t|
        t.bytea :some_attribute
      end

      class Record < ActiveRecord::Base
    +   attribute :some_attribute, :string
        encrypts :some_attribute
      end
    ```

2. To perform `cast B` yourself in the serializer, here an example of a binary message serializer using [MessagePack](https://github.com/msgpack/msgpack-ruby) (some details omitted - don't use this in your project):

    ```ruby
    class ByteaSerializer < ActiveRecord::Encryption::MessageSerializer
      def load(escaped_content)  
        encoded_content = binary_type.deserialize(escaped_content)
        parse_message(MessagePack.unpack(encoded_content), 1)
      end
    
      def dump(message)
        encoded_content = MessagePack.pack message_to_json(message)
        binary_type.serialize(encoded_content)
      end
    
      private
    
      def encode_if_needed(value) = value
      def decode_if_needed(value) = value
    
      def binary_type
        @binary_type ||= ActiveRecord::Type.lookup(:binary, adapter: :postgresql)
      end
    end
    ```

Although this gives us a picture of what we're trying to achieve, I think we'd do better to make `ActiveRecord::Encryption::EncryptedAttributeType` more versatile so that it's possible to achieve this goal without using dangerous tricks.

### Expected behavior

Various database column types and message serializers are supported for encrypted attributes.

### Actual behavior

You can only have string values, a `text`/`varchar` column in the database, and a message serializer that emits and consumes strings.

### System configuration

**Rails version**: 7.0.6

**Ruby version**: 3.2.2

---------

**Edit on `2023-07-10`**

I reworded the explanations around `cast B`, which is a step that does not exist in the default implementation, but which is needed in custom ones.

**Comment by jorgemanrubia** [comment]
@maximerety Great explanation of the issue.

I think this should be solvable using the regular [Rails attributes API](https://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html), which offers great support for data casting, instead of building additional casting options in Active Record encryption.

Could something like this work in your case?

```ruby
encrypts :some_attribute

attribute :some_attribute do |type|
 # type is an `ActiveRecord::Encryption::EncryptedAttributeType`
  return MyType.new(type) # MyType casts the encrypted value to and from whatever format I want
end
```

**Comment by maximerety** [comment]
@jorgemanrubia This is an interesting avenue.

Here is the description of the (demo) working version that I got so far:

1. A table with a binary column (PostgreSQL adapter):

    ```ruby
    create_table(:records, force: true) do |t|
      t.bytea :some_attribute
    end
    ```

2. An encrypted attribute which is able to use `String` as `cast A` and a type derived from `ActiveModel::Type::Binary` as `cast B`:

    ```ruby
    class Record < ActiveRecord::Base
      # Trick upcoming EncryptedAttributeType to use ActiveRecord::Attribute::Type::String
      # as internal `cast_type` (used to cast user-facing values, i.e. cast A)
      attribute :some_attribute, :string

      # Create our ActiveRecord::Encryption::EncryptedAttributeType
      encrypts :some_attribute

      # Override database-facing methods (serialize/deserialize) to hook an additional
      # casting step (cast B) using a db_attr_type
      attribute :some_attribute do |encrypted_attribute_type|
        encrypted_attribute_type.extend(
          Module.new do
            def db_attr_type=(db_attr_type)
              @db_attr_type = db_attr_type
            end

            def serialize(value)
              @db_attr_type.serialize(super(value))
            end

            def deserialize(value)
              super(@db_attr_type.deserialize(value))
            end
          end
        )

        # Use the actual type for the database column
        encrypted_attribute_type.db_attr_type =
          ActiveRecord::Type.lookup(:binary, adapter: :postgresql)

        encrypted_attribute_type
      end
    end
    ```

3. A simpler binary serializer that no longer needs to perform type casting, as should be the case (some details omitted - don't use this in your project):

    ```ruby
    class ByteaSerializer < ActiveRecord::Encryption::MessageSerializer
      def load(serialized_content)
        data = MessagePack.unpack(serialized_content)
        parse_message(data, 1)
      end

      def dump(message)
        MessagePack.pack message_to_json(message)
      end

      private

      def encode_if_needed(value) = value
      def decode_if_needed(value) = value
    end
    ```

Although step 2 is a little tricky, it's a definite improvement because we've managed to separate type casting concerns from binary message serialization concerns.

**Is this example anywhere near what you had in mind? Maybe I missed a simpler path?**

Here are my new observations:

* As you suggested, the [Rails attributes API](https://api.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html) has enabled me to interpose a `cast B` step between the message serializer and the database, allowing binary data to be stored/retrieved, without coupling this additional step with the message serializer.

* Although it is possible to customize the cast_type of an `ActiveRecord::Encryption::EncryptedAttributeType`: https://github.com/rails/rails/blob/a5fc471b3f4bbd02e6be38dae023526a49e7d049/activerecord/lib/active_record/encryption/encrypted_attribute_type.rb#L23 `encrypts` won't let you do it. Instead, the type previously defined, usually from database schema, is always used (and you can't override it): https://github.com/rails/rails/blob/a5fc471b3f4bbd02e6be38dae023526a49e7d049/activerecord/lib/active_record/encryption/encryptable_record.rb#L83-L88 So the preliminary `attribute :some_attribute, :string` in step 2 above is still needed as far as I know.

* The fix proposed in https://github.com/rails/rails/pull/48686 is no longer necessary **in that example**. The message serializer no longer has to deal with `ActiveModel::Type::Binary::Data` objects because the `@db_attr_type.deserialize` method (basically a `to_s`) is always called before sending the value to `Encryptor#decrypt`, whereas this type casting was performed by the custom serializer before. Only strings reach the message serializer now. This fix is still necessary **in other cases** where `cast B` exposes object types other than strings, with a custom serializer capable of handling these object types.

**Conclusion**

We have a working solution that does not seem to rely on any hack, which is very nice. As far as _I_ am concerned, it meets my needs.

Nevertheless, it still seems trickier and more difficult to support a binary database column using a binary serializer than it might be. Further discussion would be needed to determine whether we could find a simpler way to support such cases, and whether this should be considered a "common" need worth adding to the public documentation.
