### ISSUE TITLE
Line filtering doesn't work for plugin tests

### ISSUE THREAD

**Issue by lewispb** [rails/rails#48696]
### Steps to reproduce

- Checkout [rails/kredis](https://github.com/rails/kredis)
- Run `bin/test test/attributes_test.rb:82`

### Expected behavior

Only one test runs

### Actual behavior

All tests in test/attributes_test.rb run

### More info

I've fixed this for Kredis only, in this PR: https://github.com/rails/kredis/pull/122

Kredis has a standard `require "rails/plugin/test"` in `bin/test`.

[`rails/plugin/test`](https://github.com/rails/rails/blob/main/railties/lib/rails/plugin/test.rb) does not support line filtering in the same way line filtering is installed for Rails apps or [Rails itself](https://github.com/rails/rails/blob/main/tools/test.rb#L9).

**Comment by yahonda** [comment]
Closed via https://github.com/rails/kredis/pull/122

**Comment by lewispb** [comment]
Thanks for reviewing this @yahonda. Sorry if I wasn't clear but I think this is a broader issue than just Kredis.

Would this issue not affect other consumers of the generated `bin/test`? e.g. [MRSK](https://github.com/mrsked/mrsk/blob/main/bin/test).

This is generated from here in Rails:

https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/plugin/templates/bin/test.tt

We could update the bin/test generator or perhaps include line filtering elsewhere, but I think we should reopen this issue.

**Comment by fatkodima** [comment]
I generated a new plugin using rails' `main` and was able to correctly run tests by lines and line ranges.
@lewispb Can you, please, verify this is the case?
