### ISSUE TITLE
FormData requests with empty body lead to 400 Bad Reqeust

### ISSUE THREAD

**Issue by mmaier** [rails/rails#48702]
### Steps to reproduce
send a FormData request (content-type: multipart/form-data; boundary= ...) with no content but only the boundary string as body.

### Expected behavior
Request should proceed as before

### Actual behavior
ActionPack parser throws error (Empty content) -> 400 Bad Request

### System configuration
**Rails version**: 7.0.0

**Ruby version**: 3.1.2

**Comment by adrianna-chang-shopify** [comment]
👋 Hey @mmaier, can you provide a reproduction script demonstrating this behaviour? Thanks!

**Comment by alpaca-tc** [comment]
I think this is a bug in rack. It has already been fixed.
https://github.com/rack/rack/pull/2104

**Comment by mmaier** [comment]
@adrianna-chang-shopify sorry for my late response due to holiday reasons ;-) as @alpaca-tc mentioned this was exactly the way to reproduce it and it has already been solved. thank you both!
