### ISSUE TITLE
Rails CI `activesupport (3.1)` runs `3.3.0p-1 (2023-07-06 revision 75f8781c08da421d6bcfb2c3c8b7b74efea3bec2) [x86_64-linux]`

### ISSUE THREAD

**Issue by yahonda** [rails/rails#48701]
While investigating CI failure https://buildkite.com/rails/rails/builds/97870#01892cc9-5038-4065-a6d5-56e973eda905 , it should run Ruby 3.1 as it says  `activesupport (3.1)`, it actually run `3.3.0p-1 (2023-07-06 revision 75f8781c08da421d6bcfb2c3c8b7b74efea3bec2) [x86_64-linux]`

### Steps to reproduce
Open one of the recent failed build https://buildkite.com/rails/rails/builds/97870#01892cc9-5038-4065-a6d5-56e973eda905

### Expected behavior
It should pass and it should use the Ruby 3.1.

### Actual behavior
The Ruby version is `Ruby          3.3.0p-1 (2023-07-06 revision 75f8781c08da421d6bcfb2c3c8b7b74efea3bec2) [x86_64-linux]`

### System configuration
**Rails version**: main

**Ruby version**:3.3.0p-1 (2023-07-06 revision 75f8781c08da421d6bcfb2c3c8b7b74efea3bec2) [x86_64-linux]

**Comment by yahonda** [comment]
Similar one is https://buildkite.com/rails/rails/builds/97873#01892d19-2c36-4305-a302-d338387d4ba5/224-230 

`activesupport (2.7)` runs `3.3.0p-1 (2023-07-06 revision 75f8781c08da421d6bcfb2c3c8b7b74efea3bec2) [x86_64-linux]`

**Comment by zzak** [comment]
I think this is a bug in the CI config, should we move it there?

**Comment by yahonda** [comment]
I was thinking about that then https://github.com/rails/buildkite-config does not have issues, it only has Pull Requests.

**Comment by matthewd** [comment]
Ooops! Thanks for noticing! I used our new CI-CI to confirm that things were working, but obviously didn't see that all the image builders were overwriting each other.

Should now be fixed by rails/buildkite-config#58.

**Comment by yahonda** [comment]
Thank you for the fix. Will see how the next build goes.

**Comment by yahonda** [comment]
It looks good now.
