### ISSUE TITLE
`filter_parameters` used by `active_record.set_filter_attributes` initializer before it is set

### ISSUE THREAD

**Issue by nicholasdower** [rails/rails#48704]
A sample project which demonstrates this issue can be found here: https://github.com/nicholasdower/filter_parameters_issue

### Steps to reproduce

- Set `filter_parameters` in a Rails app to prevent a field in an `ActiveRecord` class from being logged.
- Start the application.
- Log an instance of the `ActiveRecord` class.

### Expected behavior

The ActiveRecord object should be filtered based on the `filter_parameters`.

### Actual behavior

The ActiveRecord object is not filtered based on the `filter_parameters`.

### Potential Cause

Afaict, this is due to the fact that:

- `active_record/railtie` requires `rails` (See [here](https://github.com/rails/rails/blob/7b52f56/activerecord/lib/active_record/railtie.rb#L4))
- `rails` requires `rails/application` (See [here](https://github.com/rails/rails/blob/7b52f569c1a05d3c988540a2fc1ccef40165a59c/railties/lib/rails.rb#L15))
- `rails/application` requires `rails/engine` (See [here](https://github.com/rails/rails/blob/7b52f569c1a05d3c988540a2fc1ccef40165a59c/railties/lib/rails/application.rb#L12))
- `rails/engine` adds the initializer `load_config_initializers` (See [here](https://github.com/rails/rails/blob/7b52f569c1a05d3c988540a2fc1ccef40165a59c/railties/lib/rails/engine.rb#L634))
- `active_record/railtie` then adds the initializer `active_record.set_filter_attributes` (See [here](https://github.com/rails/rails/blob/7b52f56/activerecord/lib/active_record/railtie.rb#L339))

This means `active_record.set_filter_attributes` will run before `load_config_initializers`. But `active_record.set_filter_attributes` uses `Rails.application.config.filter_parameters` (See [here](https://github.com/rails/rails/blob/7b52f56/activerecord/lib/active_record/railtie.rb#L341)) which is supposed to be set by a config initializer (per https://guides.rubyonrails.org/configuring.html#config-filter-parameters).

### System configuration
**Rails version**: `7.0.4.3`

**Ruby version**: `3.2.2`

**Comment by nicholasdower** [comment]
FYI, as a workaround I am initializing `filter_parameters` in `config/application.rb` like:
```ruby
Rails::Railtie.initializer :filter_parameter_initializer, { before: 'active_record.set_filter_attributes' } do
  Rails.application.config.filter_parameters += [:blah]
end
```

**Comment by skipkayhil** [comment]
Can you create a sample app that reproduces this? We have a test that covers setting `filter_parameters` in an initializer:

https://github.com/rails/rails/blob/56c784d808a9256f57728840fee931206ea1915b/railties/test/application/configuration_test.rb#L3665-L3672

**Comment by nicholasdower** [comment]
Hi @skipkayhil, thank you very much for your help. Your explanation makes it very clear what is happening. We are depending on a Gem which includes a class which extends `ActiveRecord::Base`. When we call `Bundler.require`, that Gem is required causing the ActiveRecord load hooks to run.

I have created the following project to demonstrate the issue: https://github.com/nicholasdower/filter_parameters_issue

Is it unexpected that a Gem might reference ActiveRecord::Base?

**Comment by skipkayhil** [comment]
Yes, gems should be using the same kind of lazy load hook that's used inside `set_filter_parameters`

**Comment by nicholasdower** [comment]
> Yes, gems should be using the same kind of lazy load hook that's used inside `set_filter_parameters`

Thanks @skipkayhil.

In my case, the Gem which is causing this problem is [Delayed::Job](https://github.com/collectiveidea/delayed_job). I've updated the [example project](https://github.com/nicholasdower/filter_parameters_issue) to demonstrate this.

I can file an issue in that project. Do you happen to know whether it is documented anywhere that extending/referencing `ActiveRecord::Base` in a Gem is unsupported?

**Comment by nicholasdower** [comment]
> Member

Hi @Edouard-chin, thanks for the link and for the great examples! I will try to propose a similar change in Delayed::Job.

I will close this issue. Thanks for all the help.

**Comment by eliotsykes** [comment]
For anyone else arriving here, if DelayedJob fixes the ActiveRecord loading bug, it can be still easily introduced by accident in various other ways or gems, making this security config worryingly brittle. (@Edouard-chin If this issue can be revisited and possibly reopened with this in mind, please consider it.)

If this security config is important to your app (likely will be to production apps), I'd strongly recommend setting `filter_attributes` immediately after setting `filter_parameters` in the same file for more predictable and resilient behavior.

For most Rails apps this means adding this config to the bottom of `config/initializers/filter_parameter_logging.rb`:

```rb
# Ensure filter_attributes is always set. Without this, it is brittle.
# See https://github.com/rails/rails/issues/48704
ActiveRecord::Base.filter_attributes += Rails.application.config.filter_parameters
```

To add test coverage for this, this expectation/assertion can be used, replacing the array with appropriate values:

```rb
# RSpec
expect(ActiveRecord::Base.filter_attributes).to eq [:value1, :value2, :etc]

# Minitest
assert_equal [:value1, :value2, :etc], ActiveRecord::Base.filter_attributes
```
