### ISSUE TITLE
Log level in production template doesn't agree with comment

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#48713]
Looking at 
https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/templates/config/environments/production.rb.tt#L70C1-L73C58

I see:
> Use "debug" for everything.

But below that it uses "info" as the default. Can these be made consistent?

**Comment by fatkodima** [comment]
The first line describes what "info" level does, which is used by default. And "Use "debug" for everything" is suggests which level to use, if you want everything. Which also really should not be used in production. So no inconsistencies here.
