### ISSUE TITLE
Calling model.decrypt saves the unencrypted entity, which breaks further access to it

### ISSUE THREAD

**Issue by dsusviela** [rails/rails#48721]
### Steps to reproduce

1. Create a model with AR encryption on one of the fields
2. Make sure the chosen field has deterministic encryption
3. Go into the rails console
4. Create an entity of this model, and save it
5. Call `#decrypt`
6. Do `Model.find(:id).inspect`
7. You should get an error

Any interaction with this record will result in errors

### Executable use case:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "rails", github: "rails/rails", branch: "main"
  gem 'rails'
  gem "sqlite3"
  gem "pry"
  gem "byebug"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Encryption.configure(
  primary_key: SecureRandom.alphanumeric(32),
  deterministic_key: SecureRandom.alphanumeric(32),
  key_derivation_salt: SecureRandom.alphanumeric(32),
  extend_queries: true,
  )

ActiveRecord::Schema.define do
  create_table :users, force: :true do |t|
    t.string :secret
  end
end

class User < ActiveRecord::Base
  encrypts :secret, deterministic: true
end

class BugTest < Minitest::Test
  def test_decrypt_breaks_access_to_model
    model = User.create(secret: "my_test_string")
    id = model.id
    model.decrypt

    assert_raises(ActiveRecord::Encryption::Errors::Decryption) do
      User.find(id).inspect
    end
  end
end
```

### Expected behavior
I can still interact with the entity, at the very least I should be able to recover it

### Actual behavior
Any method calls on this record yield in the after mentioned exception

### My 2 cents

I found this behavior when playing around with some records, and called `decrypt` on some of them because I was playing around. My issue is probably the intended behavior (that the record gets updated) and I understand that we get an exception since the record is not in the expected json string format anymore. However I think that we can improve the experience with any of: 

- Improving the documentation; adding a warning that this will result in an `update` of your record
- Changing the implementation so that the `ActiveRecord::Encryption::NullEncryptor.new` returns a string with a single string

I'm okay with providing any solution that it may be okay

### System configuration
**Rails version**: 7.0.6

**Ruby version**: 3.2.2

**Comment by abhisheksarka** [comment]
Looks like after the `decrypt` is called, the deserialisation of the attribute starts failing since it does not check whether the value is encrypted or not

https://github.com/rails/rails/blob/c9cdd800d30ec38f079b3df0772ab47f4ba4b11f/activerecord/lib/active_record/encryption/encrypted_attribute_type.rb#L35-L37

Updating this method to the code below seems to be working but I am not completely sure if this is the correct fix 🤔 

```ruby
def deserialize(value)
  if encryptor.encrypted? value
    cast_type.deserialize decrypt(value)
  else
    cast_type.deserialize
  end
end
```

**Comment by dsusviela** [comment]
@abhisheksarka My problem with this approach is that its completely invisible then that the record has been decrypted for the developer, and that can lead to leave the database in an inconsistent state (some records encrypted and some of them decrypted).

To me the issue resolution should be:
 - document that `.decrypt` is saving into the database,
 - the error should be explaining the situation (you have an unencrypted value int the db when its expected to be encrypted)
 - allowing to call `.encrypt` to revert the change from `decrypt`

**Comment by abhisheksarka** [comment]
> document that .decrypt is saving into the database,

I agree we should be more clear about this in the documentation [here](https://guides.rubyonrails.org/active_record_encryption.html#encrypt-and-decrypt)

> the error should be explaining the situation (you have an unencrypted value int the db when its expected to be encrypted)

IMO I don't think the `decrypt` should be erroring the record at all. This is definitely a bug. Instead, it should update & return. However, I am still not very sure about having some records encrypted and some as decrypted in the table but seems like that is a consequence anyway right now with this API

> allowing to call .encrypt to revert the change from decrypt

Agreed!

**Comment by abhisheksarka** [comment]
After digging further into this, it seems to me you can enable/disable this behaviour using

```ruby
ActiveRecord::Encryption.config.support_unencrypted_data = true
```

https://guides.rubyonrails.org/active_record_encryption.html#config-active-record-encryption-support-unencrypted-data
