### ISSUE TITLE
Unable to use named variants for blob preview

### ISSUE THREAD

**Issue by matiassalles99** [rails/rails#48744]
### Steps to reproduce

1. Create a record with named variants

<img width="570" alt="Screenshot 2023-07-17 at 12 05 47" src="https://github.com/rails/rails/assets/57004457/50ab402e-1cdc-433b-b8ee-2ea33e69c63e">

2. Upload a previewable file to the record

3. Try to show the blob preview using named variants

<img width="263" alt="Screenshot 2023-07-17 at 12 06 23" src="https://github.com/rails/rails/assets/57004457/731c4234-2014-4950-9325-06be359aeb20">

### Expected behavior
Should decode the transformations based on the symbol passed to preview

### Actual behavior
Gives undefined method deep_symbolize_keys when running into this line

<img width="665" alt="Screenshot 2023-07-17 at 12 08 37" src="https://github.com/rails/rails/assets/57004457/6832d8ee-58fe-40a6-b1e1-89f30db4b841">

Open to help coding in order to resolve this issue, from what I saw we don't have a clear way to the attachment variants.
I was thinking of grabbing the attachments from the has_many relationship in the blob and, if all of them belong to the same model type (eg: User) then grab the variants from there, if not, raise an error.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
Can you create a reproducible sample app and share with us?
