### ISSUE TITLE
ActiveRecord::Base#attribute_names and ActiveRecord::Base#table_exist? to work without connection

### ISSUE THREAD

**Issue by kirs** [rails/rails#48758]
In the app I'm working on, we take resiliency very seriously and we have a hard requirements for the app to boot and be able to access model's `attribute_names` even when the database connection is down. For that, we employ schema cache for each connection.

We employ a bunch of patches of connection & connection pooling to make that happen. It would be great to have Rails support that from the box when schema cache is available.

A snippet to illustrate the idea:

```ruby
require "active_record"

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :mydb }
end

class Post < ApplicationRecord
end

# on boot, load and set the cache to pool
cache = ActiveRecord::ConnectionAdapters::SchemaCache.load_from("./stored_schema_cache.yml")
ApplicationRecord.connection_pool.set_schema_cache(cache)

# pretend that connection is "down"
module ActiveRecord
  module ConnectionHandling
    def retrieve_connection
      raise "should not be called"
    end
  end
end

puts Post.attribute_names.inspect
=> expect this to return attribute names based on info from the schema cache, without retrieve_connection being called at all
```

I believe this could be achieved by changing calls like `connection.schema_cache.columns_hash` and `connection.schema_cache.data_source_exists?(table_name)` into something that can access schema cache without invoking the connection.

**Comment by kirs** [comment]
cc @matthewd since you've been working on untying connection from schema cache

**Comment by matthewd** [comment]
`retrieve_connection` is an awfully arbitrary place to break things. Try raising in `ActiveRecord::ConnectionAdapters::<YourAdapter>.new_client` instead.

**Comment by kirs** [comment]
This turned out to come from the fact how we initialize `Mysql2::Client` in our setup.
I confirm that Rails is indeed initializing the connection in a lazy way so that `connection.schema_cache.columns_hash` does not invoke `<YourAdapter>.new_client` when cache is loaded.
