### ISSUE TITLE
`belongs_to` validating the presence of object and not the object's ID

### ISSUE THREAD

**Issue by tejanium** [rails/rails#48771]
### Steps to reproduce

Given I have

```ruby
class Post < ActiveRecord::Base
  validates :title, presence: true

  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post, optional: false
end
```

then I do

```ruby
comment = Comment.new(post: Post.new)
```

I expect

```ruby
comment.invalid?
```

to be true and see a validation error either in `post` or `post_id`

### Reproducible script

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "mysql2", user: 'root', host: 'localhost')

ActiveRecord::Base.connection.execute("DROP DATABASE IF EXISTS bug_test")
ActiveRecord::Base.connection.execute("CREATE DATABASE bug_test")

ActiveRecord::Base.establish_connection(adapter: "mysql2", database: "bug_test", user: 'root', host: 'localhost')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end

  create_table :comments, force: true do |t|
    t.references :post, foreign_key: true
  end
end

class Post < ActiveRecord::Base
  validates :title, presence: true

  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post, optional: false
end

class BugTest < Minitest::Test
  def test_default_belongs_to_validation
    comment = Comment.new(post: Post.new)

    assert_predicate comment, :invalid?
    assert_equal comment.errors[:post], ["must exist"]
  end

  def test_default_belongs_to_validation_with_id
    comment = Comment.new(post_id: Post.new.id)

    assert_predicate comment, :invalid?
    assert_equal comment.errors[:post_id], ["can’t be blank"]
  end
end
```

### Expected behavior

Since Rails 5.0 the default for `belongs_to` is `optional: false` (or `required: true` now), which means the presence validator is added automatically.

So that when we do `Comment.new(post: Post.new)` it will validate the presence of `post`, however it doesn't translates as `validates :post_id, presence: true`

We can explicitly `validates :post_id, presence: true` so it became

```ruby
class Comment < ActiveRecord::Base
  belongs_to :post, optional: false
  
  validates :post_id, presence: true
end
```

But I think it defeats the purpose of `optional: false` (`require: true`) (and the default behavior of `belongs_to`)

Also, Rubocop has this check https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/RedundantPresenceValidationOnBelongsTo which complains if devs explicitly validating `association` or `association_id` of a `belongs_to`

```ruby
# bad
belongs_to :user
validates :user, presence: true

# bad
belongs_to :user
validates :user_id, presence: true

# bad
belongs_to :author, foreign_key: :user_id
validates :user_id, presence: true

# good
belongs_to :user

# good
belongs_to :author, foreign_key: :user_id
```

Which warn me if I have both `belongs_to :post` and `validates :post_id, presence: true`

While I understand this probably is a Rubocop issue, this behavior is perhaps somehow unexpected since there's no point in automatically validating the presence of the association of `belongs_to`, if the association itself is invalid/incomplete (without `id`) 

Therefore, would it be better for `belongs_to :post, optional: false` actually to automatically add `validates :post_id, presence: true` instead?

### Actual behavior

It persists the broken `comment` without `post_id`

### System configuration

**Rails version**: 7.1.0.alpha from https://github.com/rails/rails.git

**Ruby version**: ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [arm64-darwin22]

**Comment by ghiculescu** [comment]
The current behaviour seems intentional to me. `presence` doesn't mean "has the associated object been persisted?"; it means "is there an associated object (is it not nil)?". Otherwise you wouldn't be able to do autosaving since it would never be valid.

Maybe the cop should be updated to allow `_id` validations.

**Comment by tejanium** [comment]
Thanks @ghiculescu!

> Otherwise you wouldn't be able to do autosaving since it would never be valid.

Yeah, this makes sense

I have opened a ticket in Rubocop as well https://github.com/rubocop/rubocop-rails/issues/1055, I'll close this one.

Thanks!
