### ISSUE TITLE
HashWithIndifferentAccess#to_proc does not map keys to values as Hash#to_proc does

### ISSUE THREAD

**Issue by jasonkarns** [rails/rails#48770]
`Hash#to_proc` returns a proc that maps key to its value in the hash.

`HashWithIndifferentAccess#to_proc` however, does not generate a proc that behaves similarly.

There are two distinct behaviors that deviate from expections. Firstly, since HWIA normalizes symbol keys to strings internally, then HWIA#to_proc will _only_ work with string keys. (symbol keys map to nil). If a HWIA is constructed with symbol keys, then it should be expected that `#to_proc` honor that form.

The more general behavior, I think, is that one would expect a HWIA#to_proc to still map keys indifferently. So even if the HWIA were constructed with string keys, it should still accept symbols as well, since that is the point of HWIA (and since the proc is intended to essentially equate to `#[]`).

### Steps to reproduce

Repro gist: https://gist.github.com/jasonkarns/b8cfea9d681f3754648d807dc6710d63

```ruby
regular_hash = {a: 1, b: 2}
indifferent_hash = regular_hash.with_indifferent_access

keys = regular_hash.keys # symbol keys

keys.map(&indifferent_hash)
```

### Expected behavior

I would expect the result to be `[1,2]` just as `keys.map(&regular_hash)` would return.

### Actual behavior

Actual result is `[nil, nil]`

### System configuration
**Rails version**: 7.0.6

**Ruby version**: 3.1.3

**Comment by fatkodima** [comment]
Looks reasonable and given that the change is actually as simple as
```diff
diff --git a/activesupport/lib/active_support/hash_with_indifferent_access.rb b/activesupport/lib/active_support/hash_with_indifferent_access.rb
index aed884f84b..5e04b48c85 100644
--- a/activesupport/lib/active_support/hash_with_indifferent_access.rb
+++ b/activesupport/lib/active_support/hash_with_indifferent_access.rb
@@ -369,6 +369,10 @@ def to_hash
       _new_hash
     end

+    def to_proc
+      proc { |key| self[key] }
+    end
+
     private
       if Symbol.method_defined?(:name)
         def convert_key(key)
```

unless I am missing something on why this method can not be implemented on this class, for example.

**Comment by jasonkarns** [comment]
Yep. What we have in our wip pr is:

def to_proc = super << method(:convert_key)

That way we can keep whatever potential performance optimizations ruby has for has to proc.

My pair and I are working on a pr so that we have test coverage with this.

**Comment by akhilgkrishnan** [comment]
@jasonkarns Are you still working on this?

**Comment by jasonkarns** [comment]
Thank you all for landing this!
