### ISSUE TITLE
Why does ActiveStorage put my attachments in crazy directories

### ISSUE THREAD

**Issue by mices** [rails/rails#48786]
Look at the path to this image on disk And the top directory under storage there's lots of those directories Why do I need this craziness?
 /home/mices/data/websites/mywebsite/storage/uk/rg/ukrgqd7u7pud52r54d9eis3rq7gr/IMG_20230519_225450994.jpg

**Comment by fatkodima** [comment]
Rails "Issues" section is reserved for issues. Better to ask such questions on StackOverflow.

**Comment by mices** [comment]
You can't just ask on stackoverflow you have to include code
