### ISSUE TITLE
Changing Encryption Field to Deterministic Causes Encryption Errors

### ISSUE THREAD

**Issue by aveedibya** [rails/rails#48797]
Wondering if there is a way to read an encrypted field after changing its encryption to `deterministic`? Seems like currently there is no way in Rails to read the field's value if the field was set to `non-deterministic` (default way)  and then changed to `deterministic`.

<div class="message mb-1" style="box-sizing: border-box; margin: 0px 12px; font-family: Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; color: rgb(33, 37, 41); font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">ActiveRecord::Encryption::Errors::Decryption: ActiveRecord::Encryption::Errors::Decryption</div>

56 | uncompress_if_needed(cipher.decrypt(message, key: keys.collect(&:secret), **cipher_options), message.headers.compressed)
-- | --
57 | rescue *(ENCODING_ERRORS + DECRYPT_ERRORS)
58 | raise Errors::Decryption
59 | end

Versions in use:
ruby "3.1.2"
gem "rails", "~> 7.0.3"

**Comment by pdmholden** [comment]
This section of the ActiveRecord Encryption guide should explain how to change encryption properties with backwards compatibility: https://guides.rubyonrails.org/active_record_encryption.html#support-for-previous-encryption-schemes
