### ISSUE TITLE
URL of attachments inside ActionText content are wrong when content is rendered within background jobs

### ISSUE THREAD

**Issue by Benratelade** [rails/rails#48790]
### Steps to reproduce
I couldn't figure out how to use the scripts to replicate the issue, since I had to include background jobs and ActionText with ActiveRecord. Instead, I put together a simple Rails app with a test case that shows the problem. Hopefully that's enough. 

You can find the app here: https://github.com/Benratelade/rails-workers-routing-bug 

### Expected behavior
The `src` of images inside the ActionText should match that of the rest of the Rails app when the content is rendered within a Sidekiq job. 

### Actual behavior
The `src` of images inside the ActionText uses `http://example.org` and ignores the Rails app config, but only when the content is rendered synchronously. 

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.2.2

**Comment by Jay0921** [comment]
It seems like this issue is related to https://github.com/rails/rails/issues/41795. I don't think there is an easy fix at the moment. If this is a blocker for you, you can try this while waiting for a better solution.

```
config.action_controller.default_url_options = { host: 'https://mysite.com' }
```
