### ISSUE TITLE
CSP Middleware wrongly uses upper case header names

### ISSUE THREAD

**Issue by andrepiske** [rails/rails#48815]
`ActionDispatch::ContentSecurityPolicy::Middleware#policy_present` wrongly checks if a policy is already defined in the headers because it checks for a `Content-Security-Policy` header but won't check for `content-security-policy`.
This leads to the middleware then replacing a previously existing policy.

For instance, when using Rails 7.0.6 and Sidekiq 7.1.2 and a strict CSP is configured in rails (e.g. one that requires nonces in inline `script` tags), sidekiq dashboard UI breaks because it contains inline script tags. Those script tags should be affected by Sidekiq's own CSP which is set in https://github.com/sidekiq/sidekiq/blob/b3225ce/lib/sidekiq/web/application.rb#L353 but they're set with a lower case header name, which then gets ignored by rails' CSP middleware.

[Rack 2 & 3 compatibility guidelines](https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md#rack-2--rack-3-compatibility) states:

> Response header keys can no longer include uppercase characters.

Thus I believe rails CSP middleware should check & set only lowercase characters.

I'm happy to provide a PR with a fix, but I'm unsure if just changing those to lowercase wouldn't impact other things too much.

### System configuration
**Rails version**: 7.0.6

**Ruby version**: 3.2.2

**Comment by skipkayhil** [comment]
Hmm, I added attached PR because of #48812 but now I'm thinking that we probably should add more tests for this. The existing tests all rely on Rails using `Rack::Headers` but that won't be the case here.

cc @nunosilva800

**Comment by ghiculescu** [comment]
Looks like https://github.com/rails/rails/pull/48812 fixes this, so closing.
