### ISSUE TITLE
`after_destroy` callback should not run on non `persisted?` records

### ISSUE THREAD

**Issue by smtlaissezfaire** [rails/rails#48841]
### Steps to reproduce

Non persisted objects should not run callbacks (especially `after_destroy`) after calling `destroy` or `destroy!`

Example with test case:
https://gist.github.com/smtlaissezfaire/262f05a54b4c568dc1310f3b52006d61

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"

require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|; end
end

class User < ActiveRecord::Base
  class CallbackRanError < StandardError; end

  after_destroy :raise_an_error

  def raise_an_error
    raise CallbackRanError
  end
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_non_persisted_destroy_should_not_run_callbacks
    # an persisted? user should run after destroy callbacks
    persisted_user = User.create!
    assert_raises(User::CallbackRanError) { persisted_user.destroy! }

    # a non persisted user should NOT run callbacks
    non_persisted_user = User.new
    assert_nothing_raised { non_persisted_user.destroy! }
  end
end
```

### Expected behavior

It should not run the callbacks.

### Actual behavior

It does run the callbacks.

Without this, all callbacks that might touch other objects have to check persisted? (and might also have to check valid?) which seems to violate the principle of least surprise.

### System configuration
**Rails version**: 

```
>> Rails::VERSION::STRING
=> "7.0.6"
```

although same seems to be present in 7.x, 6.x and 5.x series

**Ruby version**:

```
>> RUBY_VERSION
=> "3.1.2"
```

**Comment by smtlaissezfaire** [comment]
FWIW, ChatGPT agrees with this behavior:

<img width="573" alt="CleanShot 2023-07-28 at 11 10 18@2x" src="https://github.com/rails/rails/assets/3690/9ad31bd8-098e-4a81-87e6-7c04030c3348">

**Comment by eileencodes** [comment]
As far as I can tell this behavior has existed since the beginning of Active Record, which means changing it without a deprecation warning or opt in config option could break applications. I've read through the history and documentation and I don't see anywhere we say that the `after_destroy` callbacks shouldn't run on non-persisted records.

(FWIW what chatgpt says doesn't matter to me, it doesn't have to deal with bug reports after a change in long standing behavior. 😅)

cc-ing/ @joshuay03 here so I don't need to leave this comment on the PR too. I don't know if we should make this change without deprecation.

**Comment by matthewd** [comment]
Yeah, I don't see any reason this should behave differently than it does: it's an after destroy callback, you called destroy -> there is a point in time that is "after destroy".

> Without this, all callbacks that might touch other objects have to check persisted? (and might also have to check valid?) which seems to violate the principle of least surprise.

I don't know what this means.

**Comment by smtlaissezfaire** [comment]
> Yeah, I don't see any reason this should behave differently than it does: it's an after destroy callback, you called destroy -> there is a point in time that is "after destroy".
> 

How do you destroy something that hasn't been created?

**Comment by smtlaissezfaire** [comment]
Why was it closed?

**Comment by smtlaissezfaire** [comment]
> > Yeah, I don't see any reason this should behave differently than it does: it's an after destroy callback, you called destroy -> there is a point in time that is "after destroy".

Basically, every after_destroy callback also has to check persisted? first before it touches the db.  So now every callback is:

```
class Foo < AR::Base
  after_destroy :delete_something_else_in_the_db_1
  after_destroy :delete_something_else_in_the_db_2

private

  def delete_something_else_in_the_db_1
    return if !persisted?
    OtherModel.where(:foo_id => id).destroy_all
  end

  def delete_something_else_in_the_db_2
    return if !persisted?
    OtherModel.where(:foo_id => id).destroy_all
  end
end
```

Does that make sense?

**Comment by joshuay03** [comment]
> How do you destroy something that hasn't been created?

I think the original intention was for 'destroy' to be seen as an event, not an outcome. So an `after_destroy` callback simply runs at the end of the destroy lifecycle, regardless of the outcome. If you need a callback to run after destroy and only once persisted you could do something like:

```ruby
  after_commit : raise_an_error, if: :destroyed?
```

**Comment by smtlaissezfaire** [comment]
> It seems like the original intention was for 'destroy' to be seen as an event, not an outcome.

I don't know what this means.

`after_save` doesn't run if you call `save` and `valid?` fails, right?

Shouldn't this be similar?

`destroy` doesn't destroy anything (since it's not `persisted?`), so after_destroy shouldn't run, right?

**Comment by rafaelfranca** [comment]
> after_save doesn't run if you call save and valid? fails, right?

But, but that is because not being valid stops the actin of saving a record. Not being persisted doesn't stop the action of destroying a record.

That is why this should not be similar.

> destroy doesn't destroy anything (since it's not persisted?), so after_destroy shouldn't run, right?

Not really. If you look the implementation of `destroy` you are going to see that it returns `true` when the record isn't persisted, which means that for the ORM, that object was destroyed, so it should run the `after_destroy` callback.

The operation deleting the record from the database indeed didn't run. But the operation of freezing a record, making it as destroyed and destroying the associations (if there is any) happened, so destroy indeed was successful and the callback should be executed.

**Comment by smtlaissezfaire** [comment]
> > after_save doesn't run if you call save and valid? fails, right?
> 
> But, but that is because not being valid stops the actin of saving a record. Not being persisted doesn't stop the action of destroying a record.
> 
> That is why this should not be similar.

I'm not saying that the current implementation calls it, but rather _what it should do_.

You could very well have after_save run on a non-valid record, but it would be surprising if it did.  Afterall, it was never saved, so why would you run after_save ?

Likewise, it's surprising that after_destroy runs on a non-persisted record.  The thing was never destroyed (because it was never created - for instance, create! would fail), so why would you run after_destroy?

So if you wanted to be consistent here, after_save _should_ run after calling save, even if it isn't valid.  Likewise, after_destroy should run even if the record is not persisted.  At least that would be consistent with what is being said in this thread.  

I'd also argue that destroy! should raise an error if the thing is not persisted, the same way create! and save! raise an error if the object is not valid.

**Comment by rafaelfranca** [comment]
Sorry, this behavior isn't going to change.

**Comment by smtlaissezfaire** [comment]
> Sorry, this behavior isn't going to change.

Was that an argument for why it shouldn't?

I'm happy to contribute a PR, including deprecation warnings etc.

> > How do you destroy something that hasn't been created?
> 
> It seems like the original intention was for 'destroy' to be seen as an event, not an outcome. So an `after_destroy` callback simply runs at the end of the `destroy` lifecycle, regardless of the whether or not the record was destroyed. If you need a callback to run after destroy and only once persisted you could do something like:
> 
> ```ruby
> after_commit :raise_an_error, if: :destroyed?
> ```

This is the best argument I've heard.  That after_destroy was actually intended to act fundamentally different than all of the other after_* hooks.  (Why though?)

If that's the case, OK, but something should be added to the docs to that effect.

It would also be nice to add something to the docs as to _why_ this is the intended behavior.

**Comment by joshuay03** [comment]
> That after_destroy was actually intended to act fundamentally different than all of the other after_* hooks. (Why though?)

This wasn't the point I was trying to make, and it's probably a bad explanation on my part. Here's what I was trying to say:

If you have a look at the callback sequence [here](https://guides.rubyonrails.org/active_record_callbacks.html#available-callbacks), you'll notice that when creating / updating a record, validation is a part of it's callback lifecycle, meaning there are validation related callbacks that simply don't make sense to be run if the record is invalid, and if it is invalid, the lifecycle never reaches the `after_save` step.

Whereas when destroying, persistence isn't a step in the destroy callback lifecycle, but as @rafaelfranca pointed out in [this comment](https://github.com/rails/rails/issues/48841#issuecomment-1664636763), the record meets the criteria of going through a `destroy`, meaning there are certain events that take place when destroying a record, and all of them have been run, so the record has made it's way to the `after_destroy` step of the lifecycle.

I hope that makes sense, it's just my 2 cents.

**Comment by rafaelfranca** [comment]
> Was that an argument for why it shouldn't?

The `destroy` action is more than just "running a delete stamement". You can see it more like "make sure the data isn't in the database and the object is frozen".

I get why you are seeing this callback is behaving differently from other callbacks but if you see the action of `destroy` with this lens, it is not. Even if the `delete` statement was not run, the action of destroying a record succeeded, so the callback should run.

I totally agree we should document it, so if you are up to, it would be great if you open a PR.
