### ISSUE TITLE
ActiveRecord: relation.count != relation.to_a.count

### ISSUE THREAD

**Issue by eadz** [rails/rails#48848]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string "name"
  end

  create_table :comments, force: true do |t|
    t.integer "post_id"
    t.string "author"
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end


class BugTest < Minitest::Test
  def setup
    Post.create! do |p|
      p.name = "first post"
      p.comments.build(author: "bar")
      p.comments.build(author: "baz")
    end

    Post.create! do |p|
      p.name = "second post"
      p.comments.build(author: "bar")
      p.comments.build(author: "baz")
    end
  end

  def test_test_setup
    assert_equal 2, Post.count
    assert_equal 4, Comment.count
  end

  def test_unscoped_bug
    scoped_posts = Post.includes(:comments).where(comments: { author: "bar" })

    scoped_posts.each do |post|
      assert_equal post.comments.to_a.count, post.comments.count
    end
  end
end
```

### Expected behaviour

`post.comments.to_a.count` should equal `post.comments.count`

### Actual behavior

`post.comments.to_a.count` is not equal to `post.comments.count`

### System configuration
**Rails version**: main branch

**Ruby version**: 3.22

**Comment by fatkodima** [comment]
You need to use `references` method. And this test case is correct, because `post.comments.count` issues a db `COUNT` query (not runs `count` on loaded `comments` association, as you may expected).

**Comment by eadz** [comment]
@fatkodima Using `references` doesn't fix the issue:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string "name"
  end

  create_table :comments, force: true do |t|
    t.integer "post_id"
    t.string "author"
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
  scope :bar, -> { where(author: "bar") }
end


class BugTest < Minitest::Test
  def setup
    Post.create! do |p|
      p.name = "first post"
      p.comments.build(author: "bar")
      p.comments.build(author: "baz")
    end

    Post.create! do |p|
      p.name = "second post"
      p.comments.build(author: "bar")
      p.comments.build(author: "baz")
    end
  end

  def test_test_setup
    assert_equal 2, Post.count
    assert_equal 4, Comment.count
  end

  def test_unscoped_bug
    scoped_posts = Post.includes(:comments).where("comments.author = ?", "baz").references(:comments)

    scoped_posts.each do |post|
      assert_equal post.comments.to_a.count, post.comments.count
    end
  end
end
```

**Comment by fatkodima** [comment]
You also need to use `assert_equal post.comments.to_a.count, post.comments.size` (notice the `size` call), because `.count` issues a db `COUNT` query, no matter what you loaded into the association via `includes`.

**Comment by eadz** [comment]
@fatkodima  I understand it uses a DB `COUNT`, but it does it on the association right?

So I have an association with conditions, and those conditions are used for the count. E.g. Comment.where({comments: { author: 'baz'}}).count will only count posts with author=baz. 

So both `to_a` and `count` both *do* work with relations that are scoped. 

The issue is that the behaviour is different, so when I look at `post.comments` in my test, is it scoped or not? That is the real question. 

And the answer seems to be 'scoped for some methods, not scoped for other methods. 

So why does Post.count differ from Post.where(..).count then?

I hope you can see where I'm coming from.

**Comment by fatkodima** [comment]
`post.comments.count` does a simple `select count(*) from comments where post_id = 1`, no extra conditions, unless you have a scope defined on the association (which is not in your example). You can see the sql log output when running the test cases. Is it more clear or not?

**Comment by eadz** [comment]
The question is " unless you have a scope defined on the association"

If I don't have a scope defined on the association, then why does `association.to_a` use a scope?
And if I do, then why does count not use it?

Anyway, it's a little confusing. Thank you very much for taking the time to explain. 

I think the answer is that `posts.comments` is already loaded, so there is no extra SQL query. 

I think I understand now! 🙇

**Comment by fatkodima** [comment]
Yeah, `post.comments` is loaded (via `.to_a` in the example), and so calls like `.size` and `.length` just use the loaded association. But `.count` always runs an SQL query, no matter if it is loaded or not. Glad that helped 👍
