### ISSUE TITLE
ActiveSupport JSON.encode in API mode spends most time in String.gsub!

### ISSUE THREAD

**Issue by fanktom** [rails/rails#48858]
### Steps to reproduce
In our codebase, we have a `Datable` concern, which allows to store JSON serialized chunks of data via `serialize :data, JSON`. The concern also adds further checks, we should not be relevant here. The data to be stored can be quite big, such as 20 MB in occasions.

As the performance in production was slower as expected, we ran some benchmarks and compared two versions:

**A**: Version that uses `ActiveSupport::JSON.encode`:
```ruby
module Automation::Datable
  extend ActiveSupport::Concern

  included do
    serialize :data, JSON
  end

  # more stuff ...
end
```

**B**: Version that uses only Ruby `JSON.dump`:
```ruby
module Automation::Datable
  extend ActiveSupport::Concern

  class PlainJSON
    def self.load(string)
      JSON.load(string)
    end

    def self.dump(value)
      JSON.dump(value)
    end
  end

  included do
    serialize :data, PlainJSON
  end

  # more stuff ...
end
```

### Expected behavior
From the encoder source code:https://github.com/rails/rails/blob/b18b9df65eb7d4e5dfa9a6982a8709c0c94b0b97/activesupport/lib/active_support/json/encoding.rb#L21
we know that ActiveSupport is doing some extra work, e.g. converting Ruby objects into JSON dumpable structures and escaping some strings. So we expect it to be a bit slower, and the Ruby only version to be a bit faster.

### Actual behavior
We created multiple test cases and measured them using pprof and then converted them into Flamegraphs with similar relationships of results: **A** was much slowet then **B**, and most time was spend string replacing the patterns as defined in 
https://github.com/rails/rails/blob/b18b9df65eb7d4e5dfa9a6982a8709c0c94b0b97/activesupport/lib/active_support/json/encoding.rb#L38-L65

**A**: Our test took 1m20s:

<img width="1139" alt="Screenshot 2023-07-31 at 14 45 37" src="https://github.com/rails/rails/assets/189038/1b67261d-0951-48cb-aaca-3f0dd3bd8930">

Over 30% of the time was spend in `String.gsub!`.

**B**: Our test took 18s:

![plain_json](https://github.com/rails/rails/assets/189038/18fc3374-017c-4239-bab1-10811fa1094b)

We can clearly see that most time is spent in escaping the special chars from the strings, which of course takes longer with bigger strings (we measured a roughly linear relationship between time and string size, before we ran out of memory).

### Final question
We use Rails purely in API mode and would never render the encoded strings to HTML, but parse them through JavaScript on the frontend. Also, we have a dedicated serializer mechanism, which converts "complex" ruby objects to JSON dumpable structures (Arrays, Hashes, ...).

- Do we understand it correctly, that the escaping is purely to ensure JSON strings can be rendered straight to HTML?
- Is there any way to disable the ActiveSupport encoding HTML escape? Basically skipping the `EscapedString` class? We don't see one, except monkey patching ActiveSupport, if we want to skip the String escape everywhere.
- Would it make sense to implement a "faster" JSON serialization in API mode by default? E.g. `config.active_support.encoding.api_mode = true` or enable it by default with `api_mode`

We would be happy to contribute and have this upstream.

Thanks a lot for your insights and help!

### System configuration
**Rails version**: 7.0.4.2

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
Made a small experiment. Without any deep changes, just avoiding `gsub!` if not necessary with a little ugly check (same needed for other branch too)
```diff
diff --git a/activesupport/lib/active_support/json/encoding.rb b/activesupport/lib/active_support/json/encoding.rb
index 5b4f8e873f..1e6b39b9c7 100644
--- a/activesupport/lib/active_support/json/encoding.rb
+++ b/activesupport/lib/active_support/json/encoding.rb
@@ -40,7 +40,9 @@ def encode(value)
           end
           json = stringify(jsonify(value))
           if Encoding.escape_html_entities_in_json
-            json.gsub! ESCAPE_REGEX_WITH_HTML_ENTITIES, ESCAPED_CHARS
+            if json.include?("\u2028") || json.include?("\u2029") || json.match?(/[><&]/)
+              json.gsub! ESCAPE_REGEX_WITH_HTML_ENTITIES, ESCAPED_CHARS
+            end
           else
             json.gsub! ESCAPE_REGEX_WITHOUT_HTML_ENTITIES, ESCAPED_CHARS
           end
```

I got 70% perf improvements for `encode` method with the following hash
```ruby
hash = {
  "class" => "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper",
  "wrapped" => "ActionMailer::MailDeliveryJob",
  "queue" => "mailers",
  "args" => [
    { "job_class" => "ActionMailer::MailDeliveryJob",
      "job_id" => "2f967da1-a389-479c-9a4e-5cc059e6d65c",
      "provider_job_id" => nil,
      "queue_name" => "mailers",
      "priority" => nil,
      "arguments" => [
        "ApiMailer",
        "test_email",
        "deliver_now",
        { "args" => [1,2,3], "_aj_symbol_keys" => ["args"]}
      ],
      "executions" => 0,
      "exception_executions" => {},
      "locale" => "en",
      "timezone" => "UTC",
      "enqueued_at" => "2019-09-12T16:28:37Z"
    }],
    "retry" => true,
    "jid" => "469979df52bb9ef9f48b49e1",
    "created_at" => 1568305717.9457421,
    "enqueued_at" => 1568305717.9457731
}
```

**Comment by maier-stefan** [comment]
@fatkodima thanks for pointing that changes in the codebase out which I assume are the commits https://github.com/rails/rails/commit/52be530755020daa62eb12a7478c9e7d42b10597 and https://github.com/rails/rails/commit/ab01f9f3da837395550c0b20d3349aad9d314e38 by @jhawthorn 

So maybe @jhawthorn could help us answer the questions above?

**Comment by jhawthorn** [comment]
Yes! Well spotted. This should be significantly improved by https://github.com/rails/rails/pull/48614 and https://github.com/rails/rails/pull/48669 (the latter of which is based on the same finding as about the cost of the unicode gsub). I've estimated that `.to_json` will be 4.5x faster in 7.1 than 7.0 (and hopefully I'm right about that 😅)

> * Is there any way to disable the ActiveSupport encoding HTML escape? Basically skipping the `EscapedString` class? We don't see one, except monkey patching ActiveSupport, if we want to skip the String escape everywhere.

`EscapedString` will no longer exist in Rails 7.1. However we will still perform the escaping - but over the entire JSON output rather than running it many times on all Strings, which is faster.

> * Do we understand it correctly, that the escaping is purely to ensure JSON strings can be rendered straight to HTML?

It's two parts: first that JSON can be embedded in an HTML script tag and second that it can be embedded in JavaScript.

> * Would it make sense to implement a "faster" JSON serialization in API mode by default? E.g. `config.active_support.encoding.api_mode = true` or enable it by default with `api_mode`

You can set `ActiveSupport.escape_html_entities_in_json = false`, but I'd prefer you didn't 😅. One problem is that we'll currently still escape U+2028 and U+2029 so there isn't really a performance benefit, at some point (maybe already?) JavaScript will support those characters unescaped inside strings (a change in ES2019, so we basically just have to wait until we think everyone's nodejs supports that. Browsers are already there).

However I'd really prefer we didn't have this configuration or add an even less secure one. It's nice that we can "convention over configuration" the extra security guarantee for those who need it. However I also don't think this was a reasonable performance hit to pay. Hopefully our recent changes make the extra escaping a non-issue. (We're still not yet as fast as a plain `JSON.generate`, in part because we are doing more work, but also I do think more progress is possible particularly if we upstream some changes to JSON)

If you want to benchmark your application against those changes I'd love to know the results!

**Comment by fanktom** [comment]
Thank you @jhawthorn, wonderfull insights and happy to see we were on the right path ;)

I will run the benchmark against the changes and post the results shortly.

**Comment by fanktom** [comment]
Alright, so I've been running more benchmarks now and compared 3 versions:

### A: Rails 7.0.4.2 with serialize JSON

- Takes roughly 50 seconds
- String#gsub! is active for about 14 seconds

<img width="1451" alt="7_0_left_heavy" src="https://github.com/rails/rails/assets/189038/39adb0fc-2e6f-4118-a100-727e0747a0cf">
<img width="722" alt="7_0_sandwich" src="https://github.com/rails/rails/assets/189038/6cc5965d-3c7d-4da3-b4d1-f795834024e4">


### B: Rails 7.0.4.2 with patched encoding.rb from main

- Replaced original encoding.rb with https://github.com/rails/rails/blob/35a614c227620a62d7a2a242e375a43e7e2affc5/activesupport/lib/active_support/json/encoding.rb
- No escaping disabled
- Takes roughly 19 seconds
- String#gsub! is active for about 900ms seconds

<img width="962" alt="patched_left_heavy" src="https://github.com/rails/rails/assets/189038/9883c5c9-1839-4f43-9296-817157082efe">
<img width="822" alt="patched_sandwich" src="https://github.com/rails/rails/assets/189038/16fc271f-ee1c-4b3e-9e92-822bbf5a9d59">

### C: Rails 7.0.4.2 with custom PlainJSON serializer

-  PlainJSON serializer which directly calls JSON.load and JSON.dump
- Takes roughly 12.5 seconds
- String#gsub! is absent

<img width="975" alt="plain_json_left_heavy" src="https://github.com/rails/rails/assets/189038/0f9e3e9a-b91c-40b0-a687-7d9ab14e2ffb">
<img width="573" alt="plain_json_sandwich" src="https://github.com/rails/rails/assets/189038/a3c77537-4159-4598-88d0-11b8d9c5f181">

### Summary

- Updated encoding.rb for 7.1 compared to 7.0 is 2.63 times faster
- Plain Ruby JSON load/dump would be 4 times faster

Thanks for the excellent improvements, @jhawthorn!

Do you think there is any chance we can get the escaping upstream into Ruby?

**Comment by fatkodima** [comment]
Can you also test with the following change replacing `jsonify` method?
```ruby
JSONIFY = {
  String => ->(value) { value },
  Integer => ->(value) { value },
  Float => ->(value) { value.as_json },
  Symbol => ->(value) { value },
  NilClass => ->(value) { nil },
  TrueClass => ->(value) { true },
  FalseClass => ->(value) { false },
  Hash => ->(value) {
    result = {}
    value.each do |k, v|
      k = k.to_s unless Symbol === k || String === k
      result[k] = JSONIFY[v.class].call(v)
    end
    result
  },
  Array => ->(value) {
    value.map { |v| JSONIFY[v.class].call(v) }
  }
}
JSONIFY.default = ->(value) {
  json = value.as_json
  case value
  when Numeric
    as_json
  else
    JSONIFY[json.class].call(json)
  end
}
JSONIFY.compare_by_identity

def jsonify(value)
  JSONIFY[value.class].call(value)
end
```

And, btw, which tool do you use for this graphical output?

**Comment by fanktom** [comment]
@fatkodima thanks for your work. In our test case, your changes perform equal to the current main branch with 19.5 seconds duration.

<img width="1040" alt="Screenshot 2023-08-02 at 08 41 58" src="https://github.com/rails/rails/assets/189038/e31f670c-5c4b-490b-a4c0-2358b42c52c0">
<img width="606" alt="Screenshot 2023-08-02 at 08 42 10" src="https://github.com/rails/rails/assets/189038/5b87fa79-78e3-4766-aa65-f4ea489b7fda">

For testing I use https://github.com/tmm1/stackprof and https://github.com/jlfwong/speedscope.

**Comment by fanktom** [comment]
I think we can close this ticket, as @jhawthorn has already identified the problem and provided a great improvement in https://github.com/rails/rails/pull/48669.

Maybe it's still up for debate, whether it would be nice to have a plain JSON.dump/load option for Rails API mode, if desired.
