### ISSUE TITLE
Unable to autoload constant Example, expected /lib/example.rb to define it (LoadError)

### ISSUE THREAD

**Issue by karantomar-aretove** [rails/rails#48864]
I am getting this error though I have autoloaded the lib directory in the application.rb file and also wrapped the Example module in Rails.application.config.to_prepare do block. Can you please help @fxn

    config.autoload_paths << Rails.root.join('lib')
    config.eager_load_paths << Rails.root.join('lib')

**Comment by fxn** [comment]
@karantomar-aretove which are the contents of `lib/example.rb`? Can you paste the exact error trace?

**Comment by karantomar-aretove** [comment]
Here it is. I updated to rails 6.1.7.4 and I am checking if zeitwerk is properly enabled or not

`RAILS_ENV=test bin/rails runner 'p Rails.autoloaders.zeitwerk_enabled?'
/Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/Users/karan/.rvm/gems/ruby-2.6.9/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/Users/karan/.rvm/gems/ruby-2.6.9/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
/Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/Users/karan/.rvm/gems/ruby-2.6.9/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: previous definition of Socket was here
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
/Users/karan/.rvm/gems/ruby-2.6.9/gems/faraday-0.15.4/lib/faraday/upload_io.rb:65: warning: constant ::UploadIO is deprecated
/Users/karan/.rvm/gems/ruby-2.6.9/gems/faraday-0.15.4/lib/faraday/upload_io.rb:66: warning: constant ::Parts is deprecated
Dalli::Server is deprecated, use Dalli::Protocol::Binary instead
/Users/karan/.rvm/gems/ruby-2.6.9/gems/activesupport-6.1.7.4/lib/active_support/dependencies.rb:564:in `load_missing_constant': Unable to autoload constant Example, expected /Users/karan/Desktop/project/example/lib/example.rb to define it (LoadError)
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/activesupport-6.1.7.4/lib/active_support/dependencies.rb:213:in `const_missing'
        from /Users/karan/Desktop/project/example/config/initializers/json_api.rb:2:in `block in <main>'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/jsonapi-resources-0.10.7/lib/jsonapi/configuration.rb:319:in `configure'
        from /Users/karan/Desktop/project/example/config/initializers/json_api.rb:1:in `<main>'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/activesupport-6.1.7.4/lib/active_support/dependencies.rb:326:in `load'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/activesupport-6.1.7.4/lib/active_support/dependencies.rb:326:in `block in load'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/activesupport-6.1.7.4/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/activesupport-6.1.7.4/lib/active_support/dependencies.rb:326:in `load'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/engine.rb:681:in `block in load_config_initializer'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/activesupport-6.1.7.4/lib/active_support/notifications.rb:205:in `instrument'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/engine.rb:680:in `load_config_initializer'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/engine.rb:633:in `each'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/engine.rb:633:in `block in <class:Engine>'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/initializable.rb:32:in `instance_exec'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/initializable.rb:32:in `run'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/initializable.rb:50:in `each'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/initializable.rb:50:in `tsort_each_child'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:415:in `call'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:347:in `each'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:347:in `call'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        from /Users/karan/.rvm/rubies/ruby-2.6.9/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/initializable.rb:60:in `run_initializers'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/application.rb:391:in `initialize!'
        from /Users/karan/Desktop/project/example/config/environment.rb:5:in `<main>'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/zeitwerk-2.6.10/lib/zeitwerk/kernel.rb:38:in `require'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/activesupport-6.1.7.4/lib/active_support/dependencies.rb:332:in `block in require'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/activesupport-6.1.7.4/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/activesupport-6.1.7.4/lib/active_support/dependencies.rb:332:in `require'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/application.rb:367:in `require_environment!'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/command/actions.rb:28:in `require_environment!'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/commands/runner/runner_command.rb:33:in `perform'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/command/base.rb:69:in `perform'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/command.rb:48:in `invoke'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/railties-6.1.7.4/lib/rails/commands.rb:18:in `<main>'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Users/karan/.rvm/gems/ruby-2.6.9/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'`

**Comment by fxn** [comment]
This:

> lib/active_support/dependencies.rb:564:inload_missing_constant': Unable to autoload constant Example, expected /Users/karan/Desktop/project/example/lib/example.rb to define it (LoadError)

is saying the application is in `classic` mode.

**Comment by fxn** [comment]
However, the root cause seems to be `lib/example.rb` does not actually define an `Example` constant, `classic` should be able to load it too.

**Comment by karantomar-aretove** [comment]
That's weird. I have set `zeitwerk` in my application.rb file and example.rb has Example defined as 

`Rails.application.config.to_prepare do
  module Example
   #some code 
  end`

`  class Application < Rails::Application
    config.load_defaults 6.1

    config.autoloader = :zeitwerk`

**Comment by fxn** [comment]
OK, then that means the constant is referenced in an initializer outside of a `to_prepare` block (that is a quirk of Rails 6.x, you are not supposed to autoload from initializers that way). I suspect the file referencing the constant is

```
config/initializers/json_api.rb
```

What does `Rails.application.config.to_prepare do module Example #some code  end` mean? Can you format it please in a code block using newlines and indentation? Are you defining the module in the `to_prepare` block?

Can you please paste the contents of `lib/example.rb`? I'd like that you prove it defines `Example`.

**Comment by karantomar-aretove** [comment]
Sorry, my bad for the format. Here is `lib/example.rb` and yes I wrapped this in `to_prepare` block. Yes, I can see Example ref from `config/initializers/json_api.rb`. Can you please suggest how can I handle it?

        
      Rails.application.config.to_prepare do
        module Example
        class ErrorWithObj < StandardError
          attr_accessor :obj
        
          def initialize(msg = nil, obj: nil)
            super(msg)
            @obj = obj
          end
        end
  
        class InvalidAccess < ErrorWithObj; end
        class InvalidAction < ErrorWithObj; end
  
        class Unauthorized < StandardError; end
        class SendOrderDataError < StandardError; end
        class NotLoggedIn < StandardError; end
        class AdminOnly < StandardError; end
        class RecordNotFound < StandardError; end
        class UnableToProcess < StandardError; end
        class Unauthorized < StandardError; end
     end  
      end

**Comment by fxn** [comment]
Oh, I see.

You have it almost right, but need to interchange two things:

First, `lib/example.rb` should be

```ruby
module Example
  class ErrorWithObj < StandardError
  ...
```

without `Rails.application.config.to_prepare`.

Then, in `config/initializers/json_api.rb` you can reference `Example` within a `to_prepare` block:

```ruby
# config/initializers/json_api.rb

Rails.application.config.to_prepare do
  # Can use Example here.
end
```

**Comment by karantomar-aretove** [comment]
Bravo! That error is gone but now I am facing a different error saying `/Users/karan/.rvm/gems/ruby-2.6.9/gems/zeitwerk-2.6.10/lib/zeitwerk/loader/helpers.rb:135:in `const_get': uninitialized constant Guardian::AddressGuardian (NameError)` lol. Not sure what it is, I will check this. Thanks @fxn 👍
