### ISSUE TITLE
AbstractController::DoubleRenderError:        Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".

### ISSUE THREAD

**Issue by karantomar-aretove** [rails/rails#48875]
I recently upgraded our application to Rails 6 and while running Rspec I am getting this below error

`AbstractController::DoubleRenderError: Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also, note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".`

```
     # --- Caused by: ---
     # Example::RecordNotFound:
     #   Example::RecordNotFound
     #   ./app/controllers/api/v1/dummy_controller.rb:75:in `find_test_by_email'
```
```
      def find_test_by_email
        @abc = Test.find_by_email(email)
        fail Example::RecordNotFound unless @abc
      end
```
      
Below is the def of that specific action and I can see there is only a single render used 
        
     def rescue_example_action(type, status_code)
        render json: {
          errors: [
            JSONAPI::Error.new(
              title: I18n.t(type),
              code: status_code,
              status: :forbidden
            )]
        }, status: status_code || 422
      end`

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by gallegosdamian505** [comment]
x
