### ISSUE TITLE
7.0.6 changed the i18n behavior of validation messages for `base` in autosave associations

### ISSUE THREAD

**Issue by wata727** [rails/rails#48884]
From v7.0.6, the behavior regarding i18n of autosave associations validation errors added to `base` has been changed. This change was introduced in https://github.com/rails/rails/pull/48413 (I know this has been reverted in https://github.com/rails/rails/pull/48871, but the behavior hasn't changed).

This broke our use case of adding to the `base`, which is configured as `""`. This may have been intentional, but I've decided to open this issue in order to share our use case.

### Background

- Add validation errors to `base` that are not related to a column (e.g. depending on multiple columns).
- An entity is stored in multiple models (imagine the [Delegated Types example](https://api.rubyonrails.org/v7.0.6/classes/ActiveRecord/DelegatedType.html)).
- Add validation errors to the delegated association.

### Steps to reproduce

Below is a simplified example of our use case. This works fine in v7.0.5.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", '7.0.5'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

I18n.backend.store_translations(
  :en,
  activerecord: {
    attributes: {
      comment: {
        entity: "Comment"
      },
      entity: {
        base: "",
      }
    }
  }
)

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
  end

  create_table :entities, force: true do |t|
    t.integer :comment_id
  end
end

class Comment < ActiveRecord::Base
  has_one :entity, autosave: true

  validates :entity, presence: true
end

class Entity < ActiveRecord::Base
  validate ->() { errors.add(:base, "This operation is not allowed") }
end

class BugTest < Minitest::Test
  def test_without_entity
    comment = Comment.new

    assert_predicate(comment, :invalid?)
    assert_equal(["Comment can't be blank"], comment.errors.full_messages.map(&:strip))
  end

  def test_with_entity
    comment = Comment.new
    comment.build_entity

    assert_predicate(comment, :invalid?)
    assert_equal(["This operation is not allowed"], comment.errors.full_messages.map(&:strip))
  end
end

```

### Expected behavior

All tests pass in v7.0.6.

```
# Running:

..

Finished in 0.007893s, 253.3891 runs/s, 506.7782 assertions/s.

2 runs, 4 assertions, 0 failures, 0 errors, 0 skips
```

Or that there is a way to change the locale data to support this case.

### Actual behavior

First, if I simply update to v7.0.6, the tests fail:

```diff
@@ -8,7 +8,7 @@ gemfile(true) do
   git_source(:github) { |repo| "https://github.com/#{repo}.git" }
 
   # Activate the gem you are reporting the issue against.
-  gem "activerecord", "7.0.5"
+  gem "activerecord", "7.0.6"
   gem "sqlite3"
 end
```

```
# Running:

.F

Finished in 0.122810s, 16.2853 runs/s, 32.5706 assertions/s.

  1) Failure:
BugTest#test_with_entity [test.rb:68]:
--- expected
+++ actual
@@ -1 +1 @@
-["This operation is not allowed"]
+["Comment This operation is not allowed"]


2 runs, 4 assertions, 1 failures, 0 errors, 0 skips
```

The other test fails when changed the locale data as below:

```diff
@@ -24,10 +24,9 @@ I18n.backend.store_translations(
   activerecord: {
     attributes: {
       comment: {
-        entity: "Comment"
+        entity: ""
       },
       entity: {
-        base: "",
       }
     }
   }
```

```
# Running:

.F

Finished in 0.007706s, 259.5380 runs/s, 519.0761 assertions/s.

  1) Failure:
BugTest#test_without_entity [test.rb:59]:
Expected: ["Comment can't be blank"]
  Actual: ["can't be blank"]

2 runs, 4 assertions, 1 failures, 0 errors, 0 skips
```

Only `base` is treated specially in https://github.com/rails/rails/pull/48413, so it works if changed to `_base`.

```diff
@@ -27,7 +27,7 @@ I18n.backend.store_translations(
         entity: "Comment"
       },
       entity: {
-        base: ""
+        _base: ""
       }
     }
   }
@@ -49,7 +49,7 @@ class Comment < ActiveRecord::Base
 end
 
 class Entity < ActiveRecord::Base
-  validate ->() { errors.add(:base, "This operation is not allowed") }
+  validate ->() { errors.add(:_base, "This operation is not allowed") }
 end
 
 class BugTest < Minitest::Test
```

```
# Running:

..

Finished in 0.006907s, 289.5613 runs/s, 579.1226 assertions/s.

2 runs, 4 assertions, 0 failures, 0 errors, 0 skips
```

But is this the right approach? Isn't it an issue that only `base` behaves differently in autosave than otherwise?

### System configuration
**Rails version**: 7.0.6

**Ruby version**: 3.1.4

**Comment by zzak** [comment]
Since that PR was reverted, and all we changed was to remove "base" from the message, I don't think it's related, but I will need to dig in further. Thanks for your report!

**Comment by rafaelfranca** [comment]
Did you test with 7-0-stable?

**Comment by rafaelfranca** [comment]
This is worse than I thought. `message` on the `base` attribute is translatable, but `full_message` isn't 🤦🏽. I'm inclined to revert that change all together for 7.0 and really rethink how this should behave in 7.1.

**Comment by wata727** [comment]
> so setting I18n to translate base doesn't make much sense.
> [In non-nested errors, base errors just return the message and aren't even translated](https://github.com/rails/rails/blob/36597e2093add6457e213b3691746d1b27aaed07/activemodel/test/cases/error_test.rb#L174-L177). Probably that is what we should be doing here.

Agreed.

But the next issue is that for my use case I want to translate without "Comment" whereas for #48408 use case they want to translate with "Comment". I'm not sure which one is right, but if you expect `base` to return messages as-is, the different behavior between autosave and otherwise can be tricky.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", '7.0.6'
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

I18n.backend.store_translations(
  :en,
  activerecord: {
    attributes: {
      comment: {
        entity: "Comment"
      }
    }
  }
)

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
  end

  create_table :entities, force: true do |t|
    t.integer :comment_id
  end
end

class Comment < ActiveRecord::Base
  has_one :entity, autosave: true

  validates :entity, presence: true
end

class Entity < ActiveRecord::Base
  validate ->() { errors.add(:base, "is not allowed") }
end

class BugTest < Minitest::Test
  def test_with_entity
    comment = Comment.new
    comment.build_entity

    assert_predicate(comment, :invalid?)
    assert_equal(["Comment is not allowed"], comment.errors.full_messages.map(&:strip))
  end

  def test_entity
    entity = Entity.new

    assert_predicate(entity, :invalid?)
    assert_equal(["Entity is not allowed"], entity.errors.full_messages.map(&:strip))
  end
end
```

```
# Running:

.F

Finished in 0.010377s, 192.7376 runs/s, 385.4753 assertions/s.

  1) Failure:
BugTest#test_entity [test.rb:65]:
Expected: ["Entity is not allowed"]
  Actual: ["is not allowed"]

2 runs, 4 assertions, 1 failures, 0 errors, 0 skips
```

> I'm inclined to revert that change all together for 7.0 and really rethink how this should behave in 7.1.

Thank you for your consideration. I'm happy if there is anything I can help.

**Comment by rafaelfranca** [comment]
In the end I found a way to fix the issue to go back to the original behavior. Does the commit above works for you?

**Comment by zzak** [comment]
This also works for my use-case, thank you!

**Comment by wata727** [comment]
Thank you! This patch made our CI green.
