### ISSUE TITLE
Show image in view but show record in mysql 

### ISSUE THREAD

**Issue by phamthanhlam** [rails/rails#48902]
I tried but the result still shows the record information stored in the database
![post image](https://github.com/rails/rails/assets/25340581/39a919ee-c1a3-4573-94f5-0a54d4393c3a)
Code show image in view
![Image show record](https://github.com/rails/rails/assets/25340581/1909bb7a-3b73-4397-942d-6db7412087de)
I don't know what to adjust the config to not show the record in the database.
Hope for a help

### System configuration
**Rails version**:7.0.6

**Ruby version**: 3.1.2p20

**Comment by fatkodima** [comment]
Please, do not duplicate the same issue in the future. Can you also create a sample app which reproduced the issue and share with us?

**Comment by phamthanhlam** [comment]
I am using docker to write ruby on rails application, can i send you by email or i share drvie. How do you want me to share?

**Comment by fatkodima** [comment]
Use `rails new myapp`, change the app to show the problem, push it to the github and paste a link to the repo here.

**Comment by fatkodima** [comment]
Ahh, haha, I got what the problem is. You need to use `<% post.images.each` instead of `<%= post.images.each` 😄

**Comment by phamthanhlam** [comment]
> Ahh, haha, I got what the problem is. You need to use `<% post.images.each` instead of `<%= post.images.each` 😄

Thank you verry much
