### ISSUE TITLE
If multiple after_commits are defined with the same callback only the last one is evaluated

### ISSUE THREAD

**Issue by melefabrizio** [rails/rails#48910]
### Steps to reproduce
When two after_commit hooks with the same callback are defined, i.e. on different conditions, only the last one is evaluated.
```rb
class Post < ActiveRecord::Base
  has_many :comments
  after_commit :do_something, on: :create
  after_commit :do_something, on: :update

  def do_something
    comments << Comment.new
  end
end
```
In this case, a `Post.create!` action does not fire the `do_something` method. An update does.

[Here is the standard test case](https://gist.github.com/melefabrizio/07f52d7c55bb7d1ae651bd35cb620785)

### Expected behavior
Both hooks should be evaluated and executed.

### Actual behavior
Only the last one is evaluated.

### System configuration
**Rails version**:  7.0.6

**Ruby version**: 3.2.1

**Comment by Jay0921** [comment]
@melefabrizio  If you're using the same callback method for two different actions, you can group them like this
```
after_commit : do_something, on: [:create, :update]
```

I've created a few basic tests for this. Let me know if you need more help.
```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
  @@after_commit_called = false

  after_commit :set_after_commit_flag, on: [:create, :update]

  def self.after_commit_called?
    @@after_commit_called
  end

  def set_after_commit_flag
    @@after_commit_called = true
  end
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_after_commit_on_create
    Post.create!(title: "Post 1")
    assert_equal true, Post.after_commit_called?
  end

  def test_after_commit_on_update
    post = Post.create!(title: "Post 1")
    post.update!(title: "Post 2")
    assert_equal true, Post.after_commit_called?
  end
end
```

**Comment by melefabrizio** [comment]
Grouping is fine when both callbacks must be always fired, but if one of them is set conditionally with an `if:` and the other not they must be declared separately.

This specific behaviour is not documented in the guide, and its not documented at all in the `Transaction` module documentation.

**Comment by victorsmoreira** [comment]
have you tried to use `after_create_commit` and `after_update_commit` callbacks?

**Comment by melefabrizio** [comment]
Yes, they are aliases for `after_commit :foot, on: :create` and  `after_commit :foot, on: :update`, so the behaviour is the same

**Comment by victorsmoreira** [comment]
sure, sorry! Another approach is to use `previously_new_record?` combined with your conditions

**Comment by skipkayhil** [comment]
https://github.com/rails/rails/issues/40648#issuecomment-735203080
I believe this is working as expected. Would you like to open a PR to improve the documentation?

**Comment by Jay0921** [comment]
> My workaround was to create an alias of the callback to effectively create two different callbacks, but it is a workaround, the bug is still there

@melefabrizio Alternatively, you can move the if condition to the callback method.

```
class Post < ActiveRecord::Base
  after_commit :do_something, on: [:create, :update]

  def do_something
    if true
      puts "do something"
    else
      puts "do something else"
    end
  end
end
```

**Comment by akhilgkrishnan** [comment]
> > My workaround was to create an alias of the callback to effectively create two different callbacks, but it is a workaround, the bug is still there
> 
> @melefabrizio Alternatively, you can move the if condition to the callback method.
> 
> ```
> class Post < ActiveRecord::Base
>   after_commit :do_something, on: [:create, :update]
> 
>   def do_something
>     if true
>       puts "do something"
>     else
>       puts "do something else"
>     end
>   end
> end
> ```

@Jay0921 I think he is referring to adding an if condition only for one action. In your example, we are checking the same condition for both the `create` and `update` actions.

```ruby
class Post < ActiveRecord::Base
  after_commit :do_something, on: :create, if: :condition?
  after_commit :do_something, on: :update
  

  def do_something
      ----
    end
    
    def condition?
     end
end
```

**Comment by ghiculescu** [comment]
> [#40648 (comment)](https://github.com/rails/rails/issues/40648#issuecomment-735203080) I believe this is working as expected. Would you like to open a PR to improve the documentation?

I'm going to close this as expected (if surprising) behaviour. A PR to document this better would be welcome.
