### ISSUE TITLE
Make "class_name" option for polymorphic `has_many` relation to STI required

### ISSUE THREAD

**Issue by loqimean** [rails/rails#48925]
### Steps to reproduce
Models:
```ruby
class Product < ApplicationRecord
  has_many :requests, as: :requestable, dependent: :destroy
end

# STI tables
class Request < ApplicationRecord
  belongs_to :requestable, polymorphic: true

  validate :request_type, presence: true
end

class ProductRequest < Request
  belongs_to :user
end
```
Then running in your console:
```ruby
Product.joins(requests: :user).where(requests: { user: { role: "admin" } })
```
Raises you an error:
```ruby
/Users/some/.rvm/gems/ruby-3.1.1/gems/activerecord-7.0.4/lib/active_record/table_metadata.rb:22:in `has_column?': undefined method `key?' for nil:NilClass (NoMethodError)
```

### Expected behavior
To raise a detailed error, like "provide a `class_name` option to use joins on STI table with polymorphic, or make required option `class_name` for polymorphic relation with STI", like:
```ruby
class Product < ApplicationRecord
  has_many :requests, as: :requestable, class_name: "ProductRequest", dependent: :destroy
end

# STI tables
class Request < ApplicationRecord
  belongs_to :requestable, polymorphic: true

  validate :request_type, presence: true
end

class ProductRequest < Request
  belongs_to :user
end
```

### Actual behavior
Unknown error 🙂 
```ruby
/Users/some/.rvm/gems/ruby-3.1.1/gems/activerecord-7.0.4/lib/active_record/table_metadata.rb:22:in `has_column?': undefined method `key?' for nil:NilClass (NoMethodError)
```

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.1

**Comment by rosanelli** [comment]
+1

**Comment by xfifix** [comment]
+1 

i interest because i have the same problem on my projet !

**Comment by xfifix** [comment]
@byroot do you have an idea ? :)

**Comment by matthewd** [comment]
It's definitely a bug; this should be using `&.`:

https://github.com/rails/rails/blob/8015c2c2cf5c8718449677570f372ceb01318a32/activerecord/lib/active_record/table_metadata.rb#L22

I imagine I'll be happy with whatever behaviour that restores, though. "This might be pointing at an STI class and one of the STI children might have an association with the name you asked for, and you might know that all instances referencing this object are of that class" is clearly possible, but I don't foresee us encoding that level of detail into an error.

If anyone's up for an easy PR, ☝🏻 plus a test would be welcome.

**Comment by xfifix** [comment]
@matthewd  i seems to work :D

**Comment by xfifix** [comment]
@matthewd  i will to try do an PR ;)

**Comment by byroot** [comment]
Backported to `7-0-stable` as https://github.com/rails/rails/commit/c1150f47b72d7ee2a74623fa3a800acac736d120

**Comment by zzak** [comment]
> plus a test would be welcome

I think we missed this but just incase anyone is looking for something to do 👀
