### ISSUE TITLE
`undefine_attribute_methods` now clears alias attribute methods

### ISSUE THREAD

**Issue by nvasilevski** [rails/rails#48931]
In https://github.com/rails/rails/pull/48533 we made a deliberate decision to use `generated_attribute_methods` module
https://github.com/rails/rails/blob/008db52a0694d36ae47be7a8ab79bf838d79079d/activemodel/lib/active_model/attribute_methods.rb#L376
to define both attribute and alias attribute methods. 

This lead to the `undefine_attribute_methods` method now cleaning up alias attribute methods along with attribute methods. 
We may want to reconsider this decision since this behavior may be found confusing since there is no clear guidance on how to explicitly re-generate alias method attributes after clearing them. 

Also it may lead to some libraries being broken since those libraries won't be aware of the new behavior. 

For example `frozen_record` undefines attributes under certain circumstances and frozen records may end up not having alias attributes since the library doesn't bring the alias attribute methods back. 

https://github.com/byroot/frozen_record/blob/1c809bcdc603759728ec0923c4ba5a23f1466101/lib/frozen_record/compact.rb#L11

If we think this behavior is intended we should at least change documentation of the `undefine_attribute_methods`. Otherwise we may want to use a different module specifically for alias attribute methods or even define methods directly on the model class as it was being done in Active Model prior our change.

cc: @byroot

**Comment by byroot** [comment]
> This lead to the undefine_attribute_methods method now cleaning up alias attribute methods along with attribute methods.

Which sound logical to me.

They are defined again if you call `define_attribute_methods` right?

**Comment by nvasilevski** [comment]
>They are defined again if you call define_attribute_methods right?

Nope 😞 

So we should treat this as the problem. I'll look into making sure `define_attribute_methods` defines alias attribute methods as well along with updating docs
