### ISSUE TITLE
assert_broadcasts fails when testing broadcast_append_to

### ISSUE THREAD

**Issue by intradayreview** [rails/rails#48934]
### Steps to reproduce

Make sure you have turbo-rails gem installed then try and test using assert_broadcasts and it will fail.

```ruby

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  after_create_commit do
    broadcast_append_to(commentable, target: ApplicationController.helpers.dom_id(commentable, :comments),
                                     partial: "comments/comment", locals: { comment: self })
  end
end

class CommentCallbackTest < CommentTest
  include ActionCable::TestHelper

  setup do
    Current.user = users(:roger)
    @commentable = screenshots(:roger_review)
  end

  test 'should broadcast comment after create' do
    assert_broadcasts @commentable, 1 do
      Comment.create!(commentable: @commentable, content: 'Test content')
    end
  end
end
```

### Expected behavior
Expected test to pass.

But the stream name is not converted using `stream.to_gid_param ` so the stream is never found and the test fails https://github.com/rails/rails/blob/157920aead96865e3135f496c09ace607d5620dc/actioncable/lib/action_cable/test_helper.rb#L45

Writing the test like this passes but does not match the docs.

```ruby
  test 'should broadcast comment after create' do
    assert_broadcasts @commentable.to_gid_param, 1 do
      Comment.create!(commentable: @commentable, content: 'Test content')
    end
  end
```

### Actual behavior
`
Failure:
CommentCallbackTest#test_should_broadcast_comment_after_create [/Users/lmackay/Desktop/intradayreview/test/models/comment_test.rb:43]:
1 broadcasts to #<Screenshot:0x00000001166ecde8> expected, but 0 were sent.
Expected: 1
  Actual: 0
`

### System configuration

**Rails version**: 7.0.2.3
**Ruby version**: ruby 3.0.5p211
**Turbo rails version**: 1.0.1

**Comment by ghiculescu** [comment]
You can use `assert_turbo_stream_broadcasts` for this use case, see https://github.com/hotwired/turbo-rails/blob/main/lib/turbo/broadcastable/test_helper.rb and https://github.com/hotwired/turbo-rails/pull/466

It would be nice if `assert_broadcasts` handled this too, but I think `turbo-rails` should implement that. So I am going to close this here as not an issue in the Rails repo.
