### ISSUE TITLE
Would be nice to drop DB with FORCE argument

### ISSUE THREAD

**Issue by loqimean** [rails/rails#48943]
### Steps to reproduce
There is no step to reproduce, because database can be accessed automatically and because of doesn't closed connection I can't drop my DB. So, would be fine to have ability to drop DB with `FORCE` option, that DB provides. The problem described in this stackowerflow issue:
https://stackoverflow.com/questions/17449420/postgresql-unable-to-drop-database-because-of-some-auto-connections-to-db

### Expected behavior
`rails db:drop! # success`

### Actual behavior
`rails db:drop # error, because database is accessed by other user`

### System configuration
**Rails version**:

**Ruby version**:

**Comment by smathy** [comment]
That _would_ be nice.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.
