### ISSUE TITLE
ActiveModel Validations - DEPRECATION WARNING Time#to_s to Time#to_fs actioncable

### ISSUE THREAD

**Issue by magni-** [rails/rails#48960]
### Steps to reproduce

The error message for comparison validations involving dates and times triggers a deprecation message (related to #48555)

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activemodel", "7.0.7"
end

require "active_model"
require "active_support/core_ext/time/conversions"
require "active_support/core_ext/time/deprecated_conversions"
require "minitest/autorun"

Time::DATE_FORMATS[:default] = "%F %T"

class Reproduction
  include ActiveModel::API

  attr_accessor :first, :second

  validates_comparison_of :first, less_than: :second
end

class ReproductionTest < Minitest::Test
  def test_error_message_does_not_trigger_deprecation_warning
    invalid = Reproduction.new(first: Time.at(2), second: Time.at(1))
    assert invalid.valid? == false

    assert_output(nil, "") { invalid.errors.full_messages.to_sentence }
  end
end
```

### Expected behavior
No deprecation warning should be raised.

### Actual behavior
A deprecation warning is raised.

### System configuration
**Rails version**: 7.0.7
**Ruby version**: 3.2.2

6.1 defaults are loaded (so `disable_to_s_conversion` is `false`) and `Time::DATE_FORMATS[:default]` is set.

**Comment by davidgumberg** [comment]
I believe this issue is with [i18n](https://github.com/ruby-i18n/i18n), I have opened a PR there https://github.com/ruby-i18n/i18n/pull/674 which fixes this by avoiding the call to `#to_s` altogether in creating the error message. Try

```
  gem 'i18n', git: 'https://github.com/davidgumberg/i18n.git', branch: 'datetime_interpolation'
```

**Comment by rafaelfranca** [comment]
This deprecation is valid. It is basically telling you that setting `Time::DATE_FORMATS[:default]` will not change the result of `Time#to_s` anymore. To fix this I recommend stopping setting `Time::DATE_FORMATS[:default]` and use `I18n` instead to localize time objects.
