### ISSUE TITLE
Unexpected `schema.rb` change when using `db:migrate:redo` or `db:migrate` after a `db:reset`

### ISSUE THREAD

**Issue by manuelvanrijn** [rails/rails#48976]
### Steps to reproduce

```console
# Clone/setup the example project
git clone https://github.com/manuelvanrijn/rails-issue-reset-migrate-vs-reset-migrate-redo.git
cd rails-issue-reset-migrate-vs-reset-migrate-redo
bin/setup

# db:reset db:migrate scenario
bin/rails db:reset db:migrate
# At this point the schema.rb file is changed 🤔

# Reset the schema
git checkout db/schema.rb

# db:reset db:migrate:redo scenario
bin/rails db:reset db:migrate:redo STEP=1
# Schema file did not change 🙄
```

### Expected behavior
When performing a `db:reset` with a `db:migrate:redo` or `db:migrate`, I wouldn't expect the schema.rb file to change. In my case, I'm running the `db:migrate:redo` in a CI task to see if the schema doesn't change, but in this case it does.
It has to have something to do with the `where` in the `add_index` but I was unable to figure out why the SchemaDumper would give a different outcome.

### Actual behavior
Changes the `schema.rb` file to a bit of different syntax, but as far as I can tell is still a valid one.
```diff
-    t.index ["name"], name: "index_blogs_on_name", unique: true, where: "(((state)::text <> ALL ((ARRAY['finished'::character varying, 'expired'::character varying])::text[])) AND (created_at > '2018-09-01 00:00:00'::timestamp without time zone))"
+    t.index ["name"], name: "index_blogs_on_name", unique: true, where: "(((state)::text <> ALL (ARRAY[('finished'::character varying)::text, ('expired'::character varying)::text])) AND (created_at > '2018-09-01 00:00:00'::timestamp without time zone))"
```

Setting the `config.active_record.schema_format = :sql` give's the same outcome

### System configuration
**Rails version**: github#main

**Ruby version**: 3.2.2

**Comment by Flixt** [comment]
I was not able to reproduce this locally on my machine with Postgres v13.5. The given instructions did not change the `schema.rb` for me. You probably use different Postgres versions on your machine and the CI?

On a broader view: I don't quite understand what you try to achieve with checking the `schema.rb` not to change. The CI should probably not run migrations but use a fresh database `bin/rails db:setup`.

**Comment by manuelvanrijn** [comment]
Hi @Flixt
Thank you for trying to reproduce this issue. 
I was using PostgreSQL 15.4 and have also checked it now with 13.5. However, I am still experiencing the issue. Please see below:
[recording-reproducable-steps.webm](https://github.com/rails/rails/assets/331876/67b53d74-d956-4f5f-85bd-360f9c4fe07a)

In response to your question about our reasoning behind this approach, when we utilize `bin/rails setup`, it executes a `db:schema:load` which assumes that the schema has been generated correctly. The intention is to ensure that someone doesn't accidentally commit a schema change related to a different ticket they might be working on.

**Comment by matthewd** [comment]
As you can see when using a SQL-format dump, we're at the mercy of how Postgres round-trips the expression: for us it's just an opaque string.

**Comment by manuelvanrijn** [comment]
@matthewd Thanks for your reply. I did some more digging and can't pinpoint exactly why or how Postgres is giving different index definitions back for these scenarios.

I did find out that if I define the `where` in the `add_index` differently it does make the definition the same, so I've changed the following:

```diff
    add_index :blogs, :name,
-    where: "state NOT IN ('finished', 'expired') and created_at > '2018-09-01'",
+    where: "state <> ALL (ARRAY['finished', 'expired']) and created_at > '2018-09-01'",
      unique: true
```

I'll close this for now, thanks!
