### ISSUE TITLE
Rails 7.0.7 regression Time#to_fs when setting :wait option in active job instance

### ISSUE THREAD

**Issue by adamzapasnik** [rails/rails#48995]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activesupport", "7.0.7"
  gem "activejob", "7.0.7"
end

require "active_support"
require "active_job"
require "active_support/core_ext/time"

# Add default format
Time::DATE_FORMATS[:default] = "%d %b %Y %H:%M"

class TestJob < ActiveJob::Base
  def perform
  end
end

puts "job"
TestJob.set(wait: 5.minutes).perform_later
puts "to_s"
Time.current.to_s
puts "to_fs"
Time.current.to_fs
```

### Expected behavior
```ruby
job
[ActiveJob] Enqueued TestJob (Job ID: 7b0fee7a-bfb6-4fc6-8d30-038ddc949524) to Async(default) at 22 Aug 2023 11:36
to_s
DEPRECATION WARNING: Using a :default format for Time#to_s is deprecated. Please use Time#to_fs instead. (called from <main> at b.rb:30)
to_fs
```

### Actual behavior
```ruby
job
DEPRECATION WARNING: Using a :default format for Time#to_s is deprecated. Please use Time#to_fs instead. (called from <main> at b.rb:28)
[ActiveJob] Enqueued TestJob (Job ID: 7b0fee7a-bfb6-4fc6-8d30-038ddc949524) to Async(default) at 22 Aug 2023 11:36
to_s
DEPRECATION WARNING: Using a :default format for Time#to_s is deprecated. Please use Time#to_fs instead. (called from <main> at b.rb:30)
to_fs
```

The deprecation warning is guiding me to use `to_fs`, but the warning comes from ActiveJob::LogSubscriber https://github.com/rails/rails/blob/7-0-stable/activejob/lib/active_job/log_subscriber.rb#L41

Adding `to_fs` seems to solve the problem.
```ruby
info do
  "Enqueued #{job.class.name} (Job ID: #{job.job_id}) to #{queue_name(event)} at #{scheduled_at(event).to_fs}" + args_info(job)
end
```

 
### System configuration
**Rails version**:  7.0.7

**Ruby version**: 3.1.4

**Comment by adamzapasnik** [comment]
@rafaelfranca I'm sorry, I'm missing a point here.

>Using a :default format for Time#to_s is deprecated. Please use Time#to_fs instead. 

The message tell me to change usage from `to_s` to `to_fs`. Sure, that's what I'd like to do.

https://github.com/rails/rails/blob/7-0-stable/activesupport/lib/active_support/core_ext/time/conversions.rb#L54

`to_fs` allows usage of `Time::DATE_FORMATS[:default]`  ☝️ 

This way I can eliminate warnings in my code, but the reported warning comes from `ActiveJob::LogSubscriber`. In 7.1 this warning will disappear, my code will still work (because it'll use `to_fs`), but until then I'll keep receiving these warnings from `ActiveJob::LogSubscriber`, I don't want that. I think it should be dealt on rails side?

**Comment by rafaelfranca** [comment]
`LogSubscriber` wants to use `to_s`. It doesn't want `Time::DATE_FORMATS[:default]` to change its behavior. But agree, I'll deal with this in the Rails side.

**Comment by rafaelfranca** [comment]
But, you will not be able to remove all deprecations if you continue to set `Time::DATE_FORMATS[:default]`. `Time::DATE_FORMATS[:default]` also changes the result of `JSON.load(Time.now)` and it will not in 7.1. To fix it you will need to call `JSON.load(Time.now.to_fs)`, which is fine if it is inside your application. But if your time object is inside some hash and you are using Rails to serialize the JSON it is less clear how you need to change your code.

I'll remove the most common causes of this deprecation inside the formework, but I can't remove the JSON one for example without performance overhead.

**Comment by skipkayhil** [comment]
One more possibility is setting https://guides.rubyonrails.org/configuring.html#config-active-support-disable-to-s-conversion to `true` so that the `to_s` patch isn't applied. I think this should be the recommendation once apps have dealt with places they were expecting to be able to customize the `to_s` format.

**Comment by rafaelfranca** [comment]
That is a good point. I'll update the message to say that.

**Comment by rafaelfranca** [comment]
Fixed with the commit above. Thanks for reporting.
