### ISSUE TITLE
Rails 7.0.7 config.active_support.disable_to_s_conversion doesn't seem to be enforced

### ISSUE THREAD

**Issue by adamzapasnik** [rails/rails#49013]
### Steps to reproduce
Based on https://github.com/rails/rails/issues/48995#issuecomment-1688880814 I tried to enable it, but it doesn't work properly in my app as `Time` is affected too. I was able to reproduce it partly (`Time` isn't affected, but `Array` is) in a fresh rails app with these commands:
```sh
rails new tt --skip-javascript --database=postgresql
cd tt
rails console
``` 
```ruby
 Array.new.method(:to_s)
 ```

### Expected behavior
Should return `#<Method: Array#to_s(inspect)()>`?
### Actual behavior
Instead returns
`=> #<Method: Array#to_s(format=...) /Users/xxx/.gem/ruby/3.1.4/gems/activesupport-7.0.7.2/lib/active_support/core_ext/array/deprecated_conversions.rb:5>`

It gets fixed by setting  `RAILS_DISABLE_DEPRECATED_TO_S_CONVERSION` right before `Bundler.require(*Rails.groups)`
```ruby
require_relative "boot"

require "rails/all"
ENV['RAILS_DISABLE_DEPRECATED_TO_S_CONVERSION'] = "true"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Tt
  class Application < Rails::Application
  ```
### System configuration
**Rails version**: 7.0.7.2

**Ruby version**: 3.1.4

**Comment by rafaelfranca** [comment]
Urh. Yeah, the behavior makes sense. This happens because some other gem is requiring time conversion before the Rails app stats to initialize. The right fix is the one you did.

Thank you for reporting.

**Comment by rafaelfranca** [comment]
Sorry, not meant to close it. Can you check what is requiring `active_support/core_ext/time` before Rails initialization?

**Comment by adamzapasnik** [comment]
@rafaelfranca `jbuilder-2.11.5/lib/jbuilder/key_formatter.rb:2`

**Comment by rafaelfranca** [comment]
Thanks! Yes, in that case env variable is the way to go, which sucks, but we can't change all gems to avoid loading the core extensions before we set the environment in Rails initialization. We would not even be able to catch all the gems that might do this.
