### ISSUE TITLE
Rails 7.0.7 config.active_support.disable_to_s_conversion doesn't work for ActiveSupport::TimeWithZone

### ISSUE THREAD

**Issue by adamzapasnik** [rails/rails#49033]
### Steps to reproduce

```sh
rails new tt --skip-javascript --database=postgresql
cd tt
# Add  ENV['RAILS_DISABLE_DEPRECATED_TO_S_CONVERSION'] = true to application.rb
rails console
``` 

```ruby
Time::DATE_FORMATS[:default] = "%d %b %Y %H:%M"
Time.zone.now.to_s
 ```

### Expected behavior
I'm not sure what to expect tbh. Maybe the previous warning?
```ruby
ActiveSupport::Deprecation.warn(
  "TimeWithZone#to_s(#{format.inspect}) is deprecated. Please use TimeWithZone#to_fs(#{format.inspect}) instead."
)
```
or maybe `@utc.to_default_s` being used?

I think what the problem is that:
1. I'm supposed to be able to use `to_fs(:default)`
2. I enabled the ENV to disable deprecated_to_s_conversion
3. It didn't disable the deprecated behaviour in TimeWithZone class
4. I can't use `Time.zone.now.to_s` if `::Time::DATE_FORMATS[:default]` is set (to be used with `to_fs`)
☝️ hopefully this explain well enough my way of thinking

### Actual behavior
Instead shows a warning
```ruby
[1] pry(main)> ENV['RAILS_DISABLE_DEPRECATED_TO_S_CONVERSION']
=> "true"
[2] pry(main)> Time::DATE_FORMATS[:default] = "%d %b %Y %H:%M"
=> "%d %b %Y %H:%M"
[3] pry(main)> Time.zone.now.to_s
DEPRECATION WARNING: Using a :default format for TimeWithZone#to_s is deprecated. Please use TimeWithZone#to_fs instead. If you fixed all places inside your application that you see this deprecation, you can set `ENV['RAILS_DISABLE_DEPRECATED_TO_S_CONVERSION']` to `"true"` in the `config/application.rb` file before the `Bundler.require` call to fix all the callers outside of your application. (called from eval at /Users/xxx/.gem/ruby/3.1.4/gems/pry-0.14.1/lib/pry/pry_instance.rb:290)
=> "25 Aug 2023 10:59"
[4] pry(main)> Time.zone.now.to_fs
=> "25 Aug 2023 10:59"
```

### System configuration
**Rails version**: f9175dbf20938f744c5081d199250db15e520e9f 7-0-stable branch

**Ruby version**: 3.1.4

**Comment by adamzapasnik** [comment]
it's super confusing, let me edit the description

**Comment by skipkayhil** [comment]
Hey @adamzapasnik, thanks for the great reproduction! Let me take a look
