### ISSUE TITLE
Nested Attributes saves the parent record before `#save` is called on the child record

### ISSUE THREAD

**Issue by radiantshaw** [rails/rails#49066]
### Steps to reproduce

```ruby
class Parent < ApplicationRecord
  has_many :children
end

class Child < ApplicationRecord
  belongs_to :parent
  accepts_nested_attributes_for :parent
end
```

### Expected behavior

```ruby
child = Child.find(42)
child.assign_attributes(parent_attributes: { foo: 'bar', id: child.parent.id })
child.save # The DB query for updating the parent attributes should be made here.
```

### Actual behavior

```ruby
child = Child.find(42)
child.assign_attributes(parent_attributes: { foo: 'bar', id: child.parent.id }) # The DB query for updating the parent attributes is being made here.
child.save
```

### System configuration

**Rails version**: 7.0.4.3

**Ruby version**: 3.1.4

**Comment by paulreece** [comment]
Hey there,

I just ran this locally with your reproduction steps and it ran as one would expect.  It updated the parent record after I saved the `child` with `child.save`.  Are there other settings you have in your app that might be affecting this behavior as to cause it to save at the `assign attributes` method?  Or were you possibly looking at the loading of the `Parent` after you assign attributes as a bug?

Here's my IRB output, I have my models setup just like yours above:
```Ruby
irb(main):001:0> child = Child.find(1)
  Child Load (0.7ms)  SELECT `children`.* FROM `children` WHERE `children`.`id` = 1 LIMIT 1
=>
#<Child:0x000000010a5da240
...
irb(main):002:0> child.assign_attributes(parent_attributes: { name: 'bar', id: child.parent.id })
  Parent Load (0.3ms)  SELECT `parents`.* FROM `parents` WHERE `parents`.`id` = 1 LIMIT 1
=> nil
irb(main):003:0> child.save
  TRANSACTION (0.4ms)  BEGIN
  Parent Update (1.4ms)  UPDATE `parents` SET `parents`.`name` = 'bar', `parents`.`updated_at` = '2023-08-28 17:11:08.084837' WHERE `parents`.`id` = 1
  TRANSACTION (1.1ms)  COMMIT
=> true
irb(main):004:0>
```

**Comment by radiantshaw** [comment]
Thanks @paulreece for the help. I was able to figure out the issue with your help. Apparently, the culprit was that the `Parent` model had a `has_and_belongs_to_many` call to some other resource, and as soon as I was assigning `other_resource_ids`, the DB call was being made. Using https://github.com/robinroestenburg/deferring, and `deferred_has_and_belongs_to_many` solves the issue.

Thanks for the help once again. 🤝
