### ISSUE TITLE
Serial attributes (PostgreSQL) not set on save

### ISSUE THREAD

**Issue by dorianmarie** [rails/rails#49060]
### Steps to reproduce

- Run postgres
- Have a field type `t.serial :external_id` on `users`
- `User.create!.external_id` => `nil`
- `User.create!.reload.external_id` => `1`

### Expected behavior

The serial attribute is set on the model after_save

### Actual behavior

The serial attribute is not set on the model and present on reload

### System configuration

**Rails version**: Rails 7.0.7
**Ruby version**: ruby 3.2.2 (2023-03-30 revision e51014f9c0) +YJIT [arm64-darwin22]

**Comment by Flixt** [comment]
This is already fixed in `main` by https://github.com/rails/rails/pull/48241

Here is an executable example of the issue:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # gem "rails", "~> 7.0.7" # Fails
  # gem "rails", github: "rails/rails", branch: "main" # Works
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "rails_49060")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.serial :external_id
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_serial_attribute
    post = Post.create
    refute_nil Post.first.external_id
    refute_nil post.external_id
  end
end
```

I could confirm that the problem does not occur when using the `main` branch.

**Comment by dorianmarie** [comment]
Thanks @Flixt and @byroot, I will wait for 7.1
