### ISSUE TITLE
ActiveStorage::Attachment Forcefully Sets touch: true, Causing after_update Callbacks to Trigger Twice

### ISSUE THREAD

**Issue by rapito** [rails/rails#49098]
When using `ActiveStorage::Attachment`, I noticed that it forcefully sets `touch: true` to the parent record whenever it's saved. This behavior leads to `after_update` callbacks on the parent record being invoked twice. In use cases where versioning (e.g., with the PaperTrail gem) is employed, this results in two versions being created instead of just one.

### Steps to reproduce:

1. Create a model with an ActiveStorage attachment and an `after_update` callback.
2. Integrate versioning with PaperTrail gem.
3. Upload an attachment to the model and save.
4. Observe that two versions are created in PaperTrail instead of one.

or

1. Create a model with an ActiveStorage attachment and an after_update callback.
2. Attach a file to the model instance and save.
3. Observe that the operation within the after_update callback is triggered twice.

### Expected behavior:

Only one version should be created in PaperTrail when an attachment is added or updated.

### Actual behavior:

Two versions are being created in PaperTrail due to the `after_update` callback being triggered twice.

### System configuration:

**Rails version:** 7.0.5
**Ruby version:** 3.0.5

### Possible solutions:

1. Make the `touch: true` behavior configurable for ActiveStorage::Attachment.
2. Do not set `touch: true` by default and allow developers to opt-in if needed.

### Additional notes:

This behavior can potentially lead to other unintended side effects when combined with other gems or custom logic that relies on after_update callbacks. It would be beneficial for developers to have more control over this behavior.

i.e.: Imagine I have an after_update that runs or schedules a long-running process, this will be triggered twice just because the attachment is touched the record.

Furthermore, I've seen workarounds such as wrapping the code with no_touching, but I find this to be somewhat unpractical and bloats the code. 
Some codebases are large enough that doing this would require a considerable amount of refactoring just to attach a file.
```rb
SomeClass.no_touching do
  some_object.attachment.attach(attachable)
end
```

**Comment by akhilgkrishnan** [comment]
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '7.0.5'
  gem 'sqlite3'
  gem 'debug'
  gem 'paper_trail'
end

require 'active_record/railtie'
require 'active_storage/engine'
require 'tmpdir'
require 'minitest/autorun'
require 'paper_trail'

class TestApp < Rails::Application
  # Important configuration
  config.api_only = true

  config.root = __dir__
  config.hosts << 'example.org'
  config.eager_load = false
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: 'Disk'
    }
  }
end

db_dir = Dir.mktmpdir('test', Dir.tmpdir)
ENV['DATABASE_URL'] = "sqlite3:#{db_dir}/db.sqlite3"

Rails.application.initialize!

# Enable PaperTrail
PaperTrail.config.enabled = true
PaperTrail.config.version_limit = 3

require ActiveStorage::Engine.root.join('db/migrate/20170806125915_create_active_storage_tables.rb').to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true do |t|
    t.string :name
  end

  create_table :versions do |t|
    t.string   :item_type, null: false
    t.integer  :item_id, null: false
    t.string   :event, null: false
    t.string   :whodunnit
    t.text     :object
    t.datetime :created_at
  end

  add_index :versions, %i[item_type item_id]
end

class User < ActiveRecord::Base
  has_paper_trail
  has_one_attached :profile

  after_update :my_callback

  private
  def my_callback
    Rails.logger.info 'after_update callback triggered'
  end
end

# Create a Minitest test to verify the callback behavior
class UserTest < Minitest::Test
  def setup
    @user = User.create
  end

  def test_after_update_callback
    assert_equal 1, @user.versions.count
    @user.name = "Akhil"
    @user.profile.attach(io: StringIO.new('Test file content'), filename: 'test.txt')

    @user.save
    assert_equal 2, @user.versions.count
  end
end

```

I tried to reproduce this, and I can confirm that the after_update callback is indeed called both when attaching a file and when saving the model. This behavior is expected because attaching a file to the model instance is considered an update action in ActiveRecord.

**Comment by natematykiewicz** [comment]
Oh! It's not my PR. My PR is not in Rails 7.0. It'll be in 7.1
https://github.com/rails/rails/blob/v7.0.8/activestorage/app/models/active_storage/blob.rb

I ran this:
```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '7.0.8'
  gem 'sqlite3'
  gem 'debug'
end

require 'active_record/railtie'
require 'active_storage/engine'
require 'tmpdir'
require 'minitest/autorun'

class TestApp < Rails::Application
  # Important configuration
  config.api_only = true

  config.root = __dir__
  config.hosts << 'example.org'
  config.eager_load = false
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: 'Disk'
    }
  }
end

db_dir = Dir.mktmpdir('test', Dir.tmpdir)
ENV['DATABASE_URL'] = "sqlite3:#{db_dir}/db.sqlite3"

Rails.application.initialize!

require ActiveStorage::Engine.root.join('db/migrate/20170806125915_create_active_storage_tables.rb').to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true do |t|
    t.string :name
    t.boolean :update_callback_ran, default: false, null: false
  end
end

class User < ActiveRecord::Base
  has_one_attached :profile

  before_update :my_callback

  private
  def my_callback
    puts caller
    self.update_callback_ran = true
  end
end

# Create a Minitest test to verify the callback behavior
class UserTest < Minitest::Test
  def setup
    @user = User.create!(name: 'Nate')
  end

  def test_after_update_callback
    assert_equal @user.update_callback_ran, false

    @user.profile.attach(io: StringIO.new('Test file content'), filename: 'test.txt')
    assert_equal @user.update_callback_ran, true
  end
end
```

It fails on the last line of the test. My `puts caller` points me to this:
https://github.com/rails/rails/blob/fc734f28e65ef8829a1a939ee6702c1f349a1d5a/activestorage/lib/active_storage/attached/one.rb#L58-L59

This isn't `touch`ing the model. It's setting a couple associations and then saving the record (an `update`).

record.#{attachment_name}=

https://github.com/rails/rails/blob/fc734f28e65ef8829a1a939ee6702c1f349a1d5a/activestorage/lib/active_storage/attached/model.rb#L60-L67

record's `after_save`

https://github.com/rails/rails/blob/fc734f28e65ef8829a1a939ee6702c1f349a1d5a/activestorage/lib/active_storage/attached/model.rb#L75

ActiveStorage::Attached::Changes::CreateOne's `save`

https://github.com/rails/rails/blob/fc734f28e65ef8829a1a939ee6702c1f349a1d5a/activestorage/lib/active_storage/attached/changes/create_one.rb#L32-L35

The 2 associations it sets and saves
https://github.com/rails/rails/blob/fc734f28e65ef8829a1a939ee6702c1f349a1d5a/activestorage/lib/active_storage/attached/model.rb#L70-L71

So the act of inserting the associated records is the "update".

Here's a simpler example that also demonstrates the "update" run.

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '7.0.8'
  gem 'sqlite3'
  gem 'debug'
end

require 'active_record/railtie'
require 'active_storage/engine'
require 'tmpdir'
require 'minitest/autorun'

class TestApp < Rails::Application
  # Important configuration
  config.api_only = true

  config.root = __dir__
  config.hosts << 'example.org'
  config.eager_load = false
  secrets.secret_key_base = 'secret_key_base'

  config.logger = Logger.new($stdout)
  Rails.logger = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: 'Disk'
    }
  }
end

db_dir = Dir.mktmpdir('test', Dir.tmpdir)
ENV['DATABASE_URL'] = "sqlite3:#{db_dir}/db.sqlite3"

Rails.application.initialize!

require ActiveStorage::Engine.root.join('db/migrate/20170806125915_create_active_storage_tables.rb').to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true do |t|
    t.string :name
    t.boolean :update_callback_ran, default: false, null: false
  end

  create_table :things, force: true do |t|
    t.string :title
    t.references :user
  end
end

class Thing < ActiveRecord::Base
  belongs_to :user
end

class User < ActiveRecord::Base
  has_one :thing

  before_update :my_callback

  private
  def my_callback
    puts caller
    self.update_callback_ran = true
  end
end

# Create a Minitest test to verify the callback behavior
class UserTest < Minitest::Test
  def setup
    @user = User.create!(name: 'Nate')
  end

  def test_after_update_callback
    assert_equal @user.update_callback_ran, false

    thing = Thing.new(title: 'Hello', user: @user)
    @user.thing = thing
    @user.save!

    assert_equal @user.update_callback_ran, true
  end
end
```

**Comment by mylesboone** [comment]
@rapito  @natematykiewicz https://github.com/rails/rails/pull/49723 (which is now in main) will allow for a configuration to not `touch` the record.

**Comment by rapito** [comment]
> @rapito @natematykiewicz #49723 (which is now in main) will allow for a configuration to not `touch` the record.

This is great, thanks. I will be closing this then.
