### ISSUE TITLE
Upgrading rails from 5.0.2 to 5.1.7 and Encounter an Error

### ISSUE THREAD

**Issue by shoaib-iqbal** [rails/rails#49102]
my ruby version is 2.5.9
and i upgraded rails from 5.0.2  to 5.1.6.2 and I am facing this issue.

That this line is running in loop, whenever i create one of my model name relationships which has association with needs.

CACHE  (0.0ms)  SELECT nextval('needs_id_seq')
  CACHE  (0.0ms)  SELECT nextval('needs_id_seq')
  CACHE  (0.0ms)  SELECT nextval('needs_id_seq')
  CACHE  (0.0ms)  SELECT nextval('needs_id_seq')
  CACHE  (0.0ms)  SELECT nextval('needs_id_seq')
  CACHE  (0.0ms)  SELECT nextval('needs_id_seq')
  CACHE  (0.0ms)  SELECT nextval('needs_id_seq')
  CACHE  (0.0ms)  SELECT nextval('needs_id_seq')
  CACHE  (0.0ms)  SELECT nextval('needs_id_seq')
  CACHE  (0.0ms)  SELECT nextval('needs_id_seq')

![rails_upgradation_error](https://github.com/rails/rails/assets/12743611/73b71605-81ec-45f6-9ac9-752862fd5874)

**Comment by fatkodima** [comment]
Rails 5 is not supported anymore - https://guides.rubyonrails.org/maintenance_policy.html.

**Comment by shoaib-iqbal** [comment]
I am facing the same issue in rails 6.

**Comment by fatkodima** [comment]
Create a reproduction script using one of the templates from - https://github.com/rails/rails/tree/main/guides/bug_report_templates.
