### ISSUE TITLE
has_one association is not clear after transaction is rollback

### ISSUE THREAD

**Issue by sanjaysalunkhe-ayla** [rails/rails#49131]
### Background
I am upgrading project from rails 3 to rails 5 version. in rails 3 version when transaction is rollback record is not getting inserted into has_one relationship but in rails 5 this is happening.
### Steps to reproduce

```ruby
class Student < ApplicationRecord
    has_one :task
end

class Task < ApplicationRecord
    belongs_to :student
end

student = Student.new
student.save
student = Student.first
def student.testing
  begin
    ActiveRecord::Base.transaction do
      t = Task.new
      t.name = 'ddd'
      t.student = self
      t.save!
      puts "raising exception"
      raise "exception"
   end
  rescue => e
  end
end
student.testing
student.save!
```

### Expected behavior

Transaction is rollback hence record should not be inserted into tasks table.
### Actual behavior

Record is getting inserted into the tasks table
### System configuration
**Rails version**:
Rails 5.2.8.1
**Ruby version**:
ruby 2.6.10p210 (2022-04-12 revision 67958) [x86_64-linux]

**Comment by fatkodima** [comment]
Rails 5 is not supported (see https://guides.rubyonrails.org/maintenance_policy.html). Can you reproduce this with a rails 6.1+? If so, create a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb.

For other core members looking into this, wdyt on somehow encouraging people to test against the supported rails versions; and additionally to test against the `main` (`7-0-stable`) to avoid false positives when it is already fixed, but not released.

**Comment by zzak** [comment]
@fatkodima I think unless we have a way to contribute bug reports which are automatically tested (like in CI), then it's up to a human to provide an accurate bug report. Many people, including this one, who are opening an issue for the first time will be overwhelmed by all of the options and walls of text.
