### ISSUE TITLE
Column not updated when counter_cache columns overlap with model db field

### ISSUE THREAD

**Issue by Earlopain** [rails/rails#49132]
### Steps to reproduce

This works fine with 7.0.7.2 but fails on main. ~~I'm fairly sure it has something to do with #48665.~~

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :tags, force: true do |t|
    t.integer :post_count
  end
  create_table :posts, force: true do |t|
  end
  create_table :user_statuses, force: true do |t|
  end
end

class Tag < ActiveRecord::Base
end

class UserStatus < ActiveRecord::Base
end

class Post < ActiveRecord::Base
  belongs_to :user_status, counter_cache: :post_count
end

class BugTest < Minitest::Test
  def test_association_stuff
    tag = Tag.create!(post_count: 4)
    tag.update!(post_count: 10)

    assert_equal(10, tag.reload.post_count)
  end
end
```

### Expected behavior
The column should be updated.

### Actual behavior
The column remains the same.

### System configuration
**Rails version**: main

**Ruby version**: 3.2.2

**Comment by akhilgkrishnan** [comment]
@Earlopain I just tested this by reverting the changes in #48665, But there also I'm getting the same error.

**Comment by Earlopain** [comment]
Thanks for checking, that seemed like the obvious case. Takin a proper look, reverting #46105 makes the test pass.

**Comment by akhilgkrishnan** [comment]
Yeah, that PR causing this issue.

**Comment by fatkodima** [comment]
Seems like I identified the cause. Looking into a fix.

**Comment by akhilgkrishnan** [comment]
The issue is causing on 
https://github.com/rails/rails/blob/42db7f307f9cc1fb0cc5da68c830d08f625429cf/activerecord/lib/active_record/attribute_methods.rb#L474 line
