### ISSUE TITLE
ActiveRecord#define_attribute_methods should be called on deserialization from cache

### ISSUE THREAD

**Issue by such** [rails/rails#49147]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"


gemfile(true) do
  source "https://rubygems.org"

  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
  gem 'test-unit'
end

require 'rails'
require 'active_record'
require 'logger'
require 'test/unit/assertions'

include Test::Unit::Assertions

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new($stdout)

ActiveRecord::Schema.define do
  create_table 'posts' do |t|
    t.string 'title'
  end
end

class Post < ActiveRecord::Base
  def title
    super.upcase
  end
end

Rails.cache = ActiveSupport::Cache::MemoryStore.new

post = Post.create!(title: 'Bug')
assert_equal 'BUG', post.title

Rails.cache.write('post', post)
post = Rails.cache.read('post')
assert_equal 'BUG', post.title

Post.reset_column_information
post = Post.find_by(title: 'Bug')
assert_equal 'BUG', post.title

Post.reset_column_information
post = Rails.cache.read('post')
assert_equal 'BUG', post.title
```

### Expected behavior
`post.title` should return `BUG` on the last line of code

It's failing because the `title` method has not been defined on Post. This. is usually done through `define_attribute_methods` the first time an ActiveRecord model is initialized or loaded from the DB.

### Actual behavior

```
/ruby-3.2.2/bundler/gems/rails-a10e7a9dc52d/activemodel/lib/active_model/attribute_methods.rb:481:in `method_missing': 
super: no superclass method `title' for #<Post id: 1, title: "Bug"> (NoMethodError)
```
### System configuration
**Rails version**: `main`

**Ruby version**: `3.2.2`

**Comment by eileencodes** [comment]
So I see the reproduction but I don't quite get why an application would be calling `Post.reset_column_information` in this way and then read from the cache. Can you help me understand the use case?

**Comment by nvasilevski** [comment]
I think this bug report may benefit from a little bit more context on when the issue can happen in a real-world app. Currently in order for this bug to appear the application must be lazy loaded which often implies development environment and also the code should be calling `reset_column_information` from a place where it makes sense

If the use-case is extremely unique and scoped to development env only perhaps Rails should recommend calling  `define_attribute_methods` manually after `reset_column_information` similarly how Active Model expects applications/libraries to manually define methods back after calling `undefine_attribute_methods`

But if the use-case is more common then it's definitely worth fixing

**Comment by such** [comment]
This happens in a real world application.

Use case: sometimes in the lifecycle of our app runtime, the first time we encounter a `Post` object is through cache deserialization. When this is the case if fails in the way described above. We are not calling `reset_column_information` ourselves in our application. This is only to simulate a restart of the app in the test. The application is question uses the production environment and `config.eager_load = true`.

`define_attribute_methods` is only called the first time `initialize` or `initialize_with` is called. My understanding is that It is always lazy.

**Comment by such** [comment]
According to the comment: 

```
          # Additionally if `check_schema_cache_dump_version` is enabled (which is the default),
          # loading the schema cache dump trigger a database connection to compare the schema
          # versions.
          # This means the attribute methods will be lazily defined whent the model is accessed,
          # likely as part of the first few requests or jobs. 
```

So I'm using the default config (`check_schema_cache_dump_version`), meaning it is lazy, right?

The app does have access to the production db on boot. I don't see why I should use the schema cache and set `check_schema_cache_dump_version` to false.

**Comment by rafaelfranca** [comment]
Because that is the recommended, resilient way to deploy Rails applications. And it is the right way to fix the issue you are describing.

defining the attribute methods, when deserializing from cache will add performance overhead to every user of the framework every time a cache entry is deserialized.

**Comment by rafaelfranca** [comment]
Alternativelly

**Comment by rafaelfranca** [comment]
I'm reopening just for the case someone come up with a better solution that doesn't add overhead to every single cache deserialization.

And also because using the schema cache, while it is the recommended, isn't the default, neither easy to do.

But I don't think there is a better solution than starting relying on the schema cache.

**Comment by jvlara** [comment]
@such what was your solution to this? I'm having the exact same problem :(
