### ISSUE TITLE
CalculationsTest#test_should_return_float_average_if_db_returns_such fails testing with SQLite 3.43.0

### ISSUE THREAD

**Issue by voxik** [rails/rails#49169]
Running AR 7.0.7.2 test suite, I started to observer following error when SQLite 3.43.0 landed in Fedora:

~~~
  1) Failure:
CalculationsTest#test_should_return_float_average_if_db_returns_such [/builddir/build/BUILD/activerecord-7.0.7.2/usr/share/gems/gems/activerecord-7.0.7.2/test/cases/calculations_test.rb:77]:
Expected: Infinity
  Actual: nil
~~~

Just briefly looking at SQLite [changelog](https://www.sqlite.org/releaselog/3_43_0.html), the "Enhancements to the [decimal extension](https://www.sqlite.org/floatingpoint.html#decext)" section caught my attention. Could it be the culprit?

BTW [this](https://koschei.fedoraproject.org/package/rubygem-activerecord?collection=f40) is Fedora CI service where I have noticed the issue.

@zmiklank FYI, should anybody else hit similar issues elsewhere.

**Comment by rafaelfranca** [comment]
It is a bug in sqlite, nothing we can do.

**Comment by voxik** [comment]
> It is a bug in sqlite, nothing we can do.

Thank you for looking into this. Please, do you have any reference by a chance?

**Comment by rafaelfranca** [comment]
It is all here https://github.com/rails/rails/pull/49048

**Comment by voxik** [comment]
Thx for the pointer. I think I saw the issue but somehow evaluated it as non-relevant. Sorry for the noise.
