### ISSUE TITLE
ActionController does not respect authority

### ISSUE THREAD

**Issue by slondr** [rails/rails#49174]
Hi. When I'm hosting my rails app in production mode, served through an nginx reverse proxy, all calls to redirect_to don't have the port my application is served on, so all link_to and redirect_to calls fail. From the clients perspective, they get redirected to port 443 instead of the actual port used. So, in other words, clients are redirected to the hostname instead of the full URI authority. 

In a controller the request object has port: nil.

**Comment by paulreece** [comment]
Can you please provide a reproduction script that demonstrates this behavior?
