### ISSUE TITLE
In production mode ,Js load error while visit http://127.0.0.1:3000

### ISSUE THREAD

**Issue by qx** [rails/rails#49199]
### Steps to reproduce

Access address is http://0.0.0.0:3000 (normal) and http://127.0.0.1:3000(all JS is 404 status)
Start with `bin/rails assets:precompile && bin/rails server - b - p 3000 -e production`
I write a hello-world example to show this bug [example](https://github.com/qx/bugshow)
 * the path is different, the result of access is different, this is an obvious mistake! *
```
  # Disable serving static files from the `/public` folder by default since
  # Apache or NGINX already handles this.
  config.public_file_server.enabled = ENV["RAILS_SERVE_STATIC_FILES"].present?
```
* In this issue should set to `config.public_file_server.enabled = true`, this bug will disappear, because RAILS_SERVE_STATIC_FILES not set before. 
- This setup is very uncomfortable, and in general we do not deliberately transfer static files to be managed by nginx, and even if we do use nginx, we need to point to public/assets. If the default is not set to false, static files cannot be obtained! It took a long time to troubleshoot this problem! And I raised the question -
 *  I don't know what the purpose of this setup is, I have been using rails4 for almost 10 years, and this is the first time to mention this annoying bug, hoping to improve this setup *

```ruby
# Your reproduction script goes here
```

### Expected behavior

in 127.0.0.1 , All JS should be 200 status,Not 404 status, and the page should be normal
### Actual behavior

Lost all JS, and the page is not normal while visit http://127.0.0.1:3000

### System configuration
**Rails version**:
7.0.0+

**Ruby version**:
3.2.2
![127](https://github.com/rails/rails/assets/648406/a8e088da-7322-4376-a699-16f262088331)

**Comment by paulreece** [comment]
Hey there thanks for reporting the issue.  Can you please provide a [reproduction script](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report)?

Also I'm wondering if you are running production on `0.0.0.0`(the Rails default)?  Was what made it hard to trouble shoot is that you were running this locally on `127.0.0.1` in `development` while working on the app?  I'm just trying to understand your problem better.

I ran my own test app locally and checked both of the addresses and was not able to reproduce.  Perhaps I'm leaving out some settings you have in your own app?

**Comment by qx** [comment]
Thx for your attention.
I have given an basic initial code.
create new rails app
then run production with those code
`bin/rails assets:precompile && bin/rails server - b - p 3000 -e production`
open chrome with link `http://127.0.0.1:3000 or http://localhost:3000 or http://<LAN_IP>:3000 ` This issue is only inconsistent in production mode, because this config `config.public_file_server.enabled = ENV["RAILS_SERVE_STATIC_FILES"].present?`

**Comment by paulreece** [comment]
So I guess I'm trying to understand how this is a bug?  Since Rails is an opinionated framework there's going to be certain choices made for us by default.  Using the `public/assets` to serve static files has been deprecated for a while.  

>config.public_file_server.enabled = true

I see you found the solution here.  I don't see Rails changing the default of how static files are served.  However, what if we added a section in the docs about overriding this, so others could find it easier than you did next time someone runs into the same problem?

**Comment by rafaelfranca** [comment]
This is a deliberate choice. If you want something different from the default you can either set `RAILS_SERVE_STATIC_FILES` or change the production.rb file to the config you want to chose.

**Comment by qx** [comment]
No, the problem I want to point out is first of all, different addresses, different results
Second is the irrationally setting the default option!
