### ISSUE TITLE
polimorphic_url returns url with http schema when using https reverse proxy

### ISSUE THREAD

**Issue by sameignatovich** [rails/rails#49204]
### Steps to reproduce
Setup production environment (puma as rails web-server) with reverse proxy (nginx, for example) and TLS.

### Expected behavior
`polimorphic_url` should returns links with https schema

```ruby
polymorphic_url(video.video_preview.variant(:thumb))
```

### Actual behavior
returned URL with http schema

### System configuration
**Rails version**: Rails 7.0.7.2

**Ruby version**: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

**Comment by paulreece** [comment]
Hey there, thanks for reporting the issue.  Would you mind creating a reproduction script so that this can be tested locally?

Also, have you tried setting `config.force_ssl = true` in your `environment/development.rb` file(or whatever environment you're coding in, it could be production or testing instead)?  You could also add it in your `application.rb` file.

**Comment by sameignatovich** [comment]
I just found option `proxy_set_header X-Forwarded-Proto $scheme;` in nginx config, it's solved my problem.

Full config what solved my problem:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name example.com;

    http2 on;

    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/example.com/chain.pem;

    include /etc/nginx/tls.conf;

    client_max_body_size 0;

    location / {
        proxy_pass       http://localhost:3000;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

My backend didn't known protocol which the client accessed my reverse-proxy web server

Issue can be closed.
