### ISSUE TITLE
Value of the Content Security Policy directive 'trusted_types' contains an invalid policy

### ISSUE THREAD

**Issue by hunchr** [rails/rails#49203]
### Steps to reproduce
```ruby
Rails.application.configure do
  config.content_security_policy do |csp|
    csp.trusted_types :self
  end
end
```

### Expected behavior
HTTP response headers should include the following CSP (notice that the quotes for 'self' are missing):
`Content-Security-Policy: trusted-types self`

### Actual behavior
The response headers include this:
`Content-Security-Policy: trusted-types 'self'`

Error displayed in Chrome browser console:
![Chrome Console](https://github.com/rails/rails/assets/76159444/9171763f-1b1b-42e6-9cc1-7a8ac10e68b9)

### System configuration
**Rails version**: 7.0.7.2

**Ruby version**: 3.2.2

**Comment by hunchr** [comment]
```ruby
csp.trusted_types 'self'
```
works

**Comment by zzak** [comment]
Weird, I would expect the symbol version to work naturally.

There is even a test similar to this:
https://github.com/rails/rails/blob/e6f09150a88c1fdcfbf343226fe020837e665aab/actionpack/test/dispatch/content_security_policy_test.rb#L223-L224

**Comment by olivparm** [comment]
This bug is still present in Rails 8.0.2
