### ISSUE TITLE
Gemfile / Gemfile.lock vs rails/generators/app_base.rb, Puma version

### ISSUE THREAD

**Issue by MSP-Greg** [rails/rails#49224]
I'm not that familiar with Rails CI, and also not a heavy Rails user.  Recently there was an 'installation' problem in another repo's issues, and I thought I'd see if I could repo the problem.

Noticed the below, using the most recent commit on the 7-0-stable branch:

https://github.com/rails/rails/blob/fc734f28e65ef8829a1a939ee6702c1f349a1d5a/Gemfile#L92-L94

https://github.com/rails/rails/blob/fc734f28e65ef8829a1a939ee6702c1f349a1d5a/Gemfile.lock#L396

https://github.com/rails/rails/blob/fc734f28e65ef8829a1a939ee6702c1f349a1d5a/railties/lib/rails/generators/app_base.rb#L171-L173

I didn't look further than Puma, but the above versions seem odd.  I assume I'm missing something.  So, if possible, a brief explanation would be appreciated...

Off-topic: Puma master runs runs CI against turbo-rails and socketry/rack-conform, Puma 5 does not.  Turbo-rails only runs CI against Puma 6.

**Comment by rafaelfranca** [comment]
There is no issue on this code. While Rails is always tested against the newest version of its dependencies, it doesn't need to generate applications with the newest version of its dependencies. Regardless I changed the generator to allow using 6.0

**Comment by zzak** [comment]
To add a little more, the Gemfile and Gemfile.lock are purely used for development of Rails.

Yes, CI will bundle install those dependencies, but it throws away the Gemfile.lock before doing that:
https://github.com/rails/buildkite-config/blob/f14dc01f07de06be2c79dd94ec31b683da8c0c58/Dockerfile#L134

As far as the generator, that is added for new applications via `rails new` and was recently updated in #46254 which might provide more context. Generally it's not something existing users have to worry about, and they can manage this constraint by themselves.
