### ISSUE TITLE
Remove CoffeeScript from UJS on `7-0-stable`.

### ISSUE THREAD

**Issue by ruyrocha** [rails/rails#49225]
### Steps to reproduce

```ruby
# Your reproduction script goes here
```

Hey team, what are the plans on removing CoffeeScript from UJS? 

### Expected behavior
Only vanilla JS  is present on UJS at `7-0-stable` branch.

### Actual behavior
CoffeeScript is present on USJ at `7-0-stable` branch.

**Comment by rafaelfranca** [comment]
No. 7-0-stable don't receive any new feature, and this is a new feature
