### ISSUE TITLE
Queries executed with `ActiveRecord::Base.connection.execute` do not modify query_cache

### ISSUE THREAD

**Issue by marco-carini** [rails/rails#49232]
Queries that are formed using `ActiveRecord::Base.connection.execute` in Rails v7 do not properly clear the query cache, and thus leave services operating on stale data if the query modified data. 

This change appears to be a regression from Rails v6, as I don’t see clear documentation of alternatives.

**Comment by skipkayhil** [comment]
Ref #44005 there was some discussion of this before and a fix was merged for Rails 7.1 but the implementation changed things in a way that it is unlikely to be backported.

Until 7.1 is released, can you try using `insert` `update` or `delete` (which should be properly be clearing the cache)?

cc @byroot

**Comment by matthewd** [comment]
Notably, per the linked discussion, `execute` never historically cleared the query cache. The only change in 7.0 was that the query cache can be active by default when running tests.

Outside a test environment, e.g. in a job or a request, the same behaviour should be visible in all versions [prior to 7.1].

@marco-carini does that match what you're seeing?

**Comment by marco-carini** [comment]
Ah, I was able to reproduce! Thank you both for your insight, I'll run with @skipkayhil's suggestion until Rails 7.1.
