### ISSUE TITLE
TypeError: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by nicke** [rails/rails#49248]
### Error Trace
```
/Users/username/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/core_ext/string/output_safety.rb [line 183]

181 def [](*args)
182  if html_safe?
183    new_string = super
184    return unless new_string
```

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**Comment by yahonda** [comment]
Please provide a sample application that actually reproduce issues.

**Comment by Judahmeek** [comment]
@yahonda I believe that I've encountered the same issue referenced here.

The cache entry value is supposed to be a hash, but it actually returns a string.

When someone tries referencing a hash key on that string, the error in the issue title gets thrown.

Example repo: https://github.com/Judahmeek/active-support-cache-bug

However, this might not be the same exact issue, as this test passes with rails 7.0.8, but fails with rails 7.1.1

**Comment by yahonda** [comment]
please open another issue since the original reporter says `Rails version: 7.0.8`.
