### ISSUE TITLE
ActionCable 7.0.8 guide

### ISSUE THREAD

**Issue by Tikkoneus** [rails/rails#49254]
Not a bug, but the [guide](https://guides.rubyonrails.org/action_cable_overview.html) left me in the dark at the end. The consumer never connected. Running `rails generate channel foobar` worked. It seems the key step missing from the docs is the diff in `config/importmap.rb`, never mentioned in the guide:

```
+pin "@rails/actioncable", to: "actioncable.esm.js"
+pin_all_from "app/javascript/channels", under: "channels"
```

I appreciate the guide's walk-through of all files involved, but since all the functionality the generator creates is do-nothing it seems reasonable to me to start the guide with an invocation of `generate channel` and then do the walk-through to fill out all the files just created.

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**Comment by paulreece** [comment]
I suggest opening a PR on the Docs and then adding the information you think would be helpful in the Guide.  I'm sure it would get added as long as it makes sense in the context of the rest of the Guide.
