### ISSUE TITLE
7.1.0.beta1 regression: NameError when using alias_method with aliased attribute

### ISSUE THREAD

**Issue by andreimaxim** [rails/rails#49250]
Before Rails 7.1.0.beta1 it was possible to use `alias_method` or `alias` on an attribute defined with `alias_attribute`.

This is very useful when working with legacy databases that don't conform to the Rails naming conventions:

```ruby
class Payment < ActiveRecord::Base
  alias_attribute :legacy_amount, "legacyamount"

  alias_method :amount, :legacy_amount
end
```

The solution is rather simple: replace `alias_method` with `alias_attribute`, but I figured it's worth creating an issue and letting the Rails team decide if it's worth fixing or not.

The test script below will raise a `NameError` exception once it reaches the `alias_method` line on Rails 7.1.0.beta1 and it passes correctly on v7.0.8:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "= 7.1.0.beta1"
  gem "sqlite3"
end

require "minitest/autorun"
require "active_record"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :payments, force: true do |t|
    t.decimal :legacyamount, precision: 10, scale: 0, default: 0, null: false
  end
end

class Payment < ActiveRecord::Base
  alias_attribute :legacy_amount, "legacyamount"

  alias_method :amount, :legacy_amount
end

class BugTest < Minitest::Test
  def test_legacy_attribute
    payment = Payment.create legacy_amount: 10

    assert_equal 10, payment.legacyamount
    assert_equal 10, payment.legacy_amount
  end

  def test_aliased_attribute
    payment = Payment.create legacy_amount: 10

    assert_equal 10, payment.amount
  end
end
```

**Comment by yahonda** [comment]
This behavior change has been introduced via https://github.com/rails/rails/pull/48533

**Comment by casperisfine** [comment]
Yes, this is somewhat expected, `alias_attribute` used to define new methods right away, now it define them after attribute methods have been defined.

I see how this might break in some corner cases, but I don't think there is much we can do about it without giving up the change entirely (which I'd rather not do)

**Comment by nvasilevski** [comment]
Just to be sure I checked the script with a setup like
```ruby
class Payment < ActiveRecord::Base
  alias_attribute :legacy_amount, "legacyamount"
  alias_attribute :amount, "legacyamount"
end
```
and it works so most likely this is going to be the recommendation as this way of getting alias methods will be the most consistent with Rails expectations. This approach will end up generating more methods for `amount` that the application may need but this is a small price to pay

Sorry for the trouble. I would be more than glad to make sure the change to `alias_attribute` method generation as visible as possible if core team finds it necessary

**Comment by rafaelfranca** [comment]
I think this is an acceptable trade off. Maybe we should add to the changelog entry, but I don't think it is worth reverting the change back. Thank you for the issue and for trying the beta ❤️

**Comment by andreimaxim** [comment]
@rafaelfranca I think this issue should provide enough visibility. Ruby will raise a very explicit error if you try to load the model and should be rather trivial to fix.

Thank you all very much for your work on Rails!
