### ISSUE TITLE
7.1.0.beta1 minitest assert_equals reports failure when both objects appear equal

### ISSUE THREAD

**Issue by ccasabona** [rails/rails#49256]
Minitest assert_equals is failing under certain circumstances when the objects being compared appear equal.  I haven't investigated all the circumstances under which this occurs, but it is consistently happening on validations that use the confirmation helper.  In previous versions of Rails, this test has always passed. Interestingly, the return objects as displayed appear to match.

Here is a reproduction script:

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.0.beta1"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :email
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments

  validates :email, presence: true, confirmation: true
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_email_confirmation
    post = Post.create
    post.email = 'firstemail@rails.com'
    post.email_confirmation = 'notthesame@rails.com'
    assert post.invalid?
    assert_equal ["doesn't match Email"], post.errors[:email_confirmation]
  end
end

```
### Expected behavior
This test should pass.

### Actual behavior
The assert_equal assertion reports failure although returned objects appear to the the same.
```

Expected: ["doesn’t match Email"]
  Actual: ["doesn't match Email"]
```

It also fails if you reverse the objects:

`assert_equal post.errors[:email_confirmation], ["doesn't match Email"]`

Test Results:
```

Run options: --seed 51191

# Running:

F

Finished in 0.062630s, 15.9668 runs/s, 31.9336 assertions/s.


  1) Failure:
BugTest#test_association_stuff [railsbug.rb:50]:
Expected: ["doesn’t match Email"]
  Actual: ["doesn't match Email"]

1 runs, 2 assertions, 1 failures, 0 errors, 0 skips

```

ADDITIONAL OBSERVATION:
If you stop the test right after `assert post.invalid?` and copy the 2 objects onto a new line of code, they are not equal.  It isn't clear if the problem is with assert_equal or with a change in how the errors array is returned.

```
(ruby) post.errors[:email_confirmation]
["doesn’t match Email"]
(ruby) post.errors[:email_confirmation] == ["doesn’t match Email"]
false

```

### System configuration
**Rails version**: 7.1.0.beta1

**Ruby version**: ruby 3.2.2

**Comment by rafaelfranca** [comment]
Thank you for the issue. Those strings aren't equal. `doesn’t` is't equal to `doesn't`. Pay attention to the `’` over `'`.

**Comment by ccasabona** [comment]
Good spotting.  So has the character that Rails is using for the apostrophe in these message has changed?

**Comment by rafaelfranca** [comment]
Yes.
