### ISSUE TITLE
Sandbox console doesn't rollback table truncations

### ISSUE THREAD

**Issue by mlwyatt** [rails/rails#49253]
### Steps to reproduce

I'm not entirely sure how to get the sandbox console ran within a script but I provided a setup script from the template to get the data set up. I provided a test to show that it's not an issue with `ActiveRecord::Base::transaction`

- Setup:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
end

Post.create!([{ title: "Title 1" }, { title: "Title 2" }, { title: "Title 3" }])

class BugTest < Minitest::Test
  def test_stuff
    Post.transaction do
      assert_equal 3, Post.count
      Post.connection.truncate(Post.table_name)
      assert_equal 0, Post.count
      raise ActiveRecord::Rollback
    end

    Post.transaction do
      assert_equal 3, Post.count
    end
  end
end
```
- `rails c -s`
```ruby
Post.count
# => 3
Post.truncate(Post.table_name)
Post.count
# => 0
exit
```
- `rails c -s`
```ruby
Post.count
# => 0 # This should be 3
exit
```

### Expected behavior
Table truncation should be rolled back on exit

### Actual behavior
Table truncation is not rolled back on exit

### System configuration
**Rails version**: `rails -v` => `Rails 7.0.4.3`

**Ruby version**: `ruby -v` => `ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [aarch64-linux]`

**Comment by paulreece** [comment]
Hey there, so I think the method you are looking for here would be `destroy_all`.  

When you are calling `Post.connection.truncate(Post.table_name)` you are reaching outside of the sandbox to the `connection`, so it is truncating the prod table.

When you call `Post.destroy_all` in the sandbox.  It will truncate that table in the sandbox, then when you exit the sandbox and either enter the sandbox again or enter the normal console, you will find all of your `Posts` still exist.  So the functionality is there you just have to go about it a slightly different way using `destroy_all.

Let me know if you have any other questions!

**Comment by mlwyatt** [comment]
> When you are calling `Post.connection.truncate(Post.table_name)` you are reaching outside of the sandbox to the `connection`, so it is truncating the prod table.

That makes sense. Does that mean any `ActiveRecord::Base.connection.execute` queries/updates get sent straight to the connection thus avoiding the sandbox rolling back?

> `delete_all` or `destroy_all`

I'm using MySQL and maybe it's just a quirk of MySQL's `TRUNCATE`, intended or not, but truncating a table will also reset the `AUTO_INCREMENT` counter while `delete_all` will just `DELETE` all the rows

**Comment by paulreece** [comment]
> That makes sense. Does that mean any ActiveRecord::Base.connection.execute queries/updates get sent straight to the connection thus avoiding the sandbox rolling back?

I believe so, yes.


> I'm using MySQL and maybe it's just a quirk of MySQL's TRUNCATE, intended or not, but truncating a table will also reset the AUTO_INCREMENT counter while delete_all will just DELETE all the rows

I myself am not sure how to reset the `AUTO_INCREMENT` counter without using the connection.  It might not be possible from the sandbox. 

Just curious, what's your use case for needing the counter reset?

**Comment by mlwyatt** [comment]
> Just curious, what's your use case for needing the counter reset?

I don't have a production reason for it. I like to have the same `id`s production would have for a static table, like `states`. I just I noticed my truncate persisted while testing reseeding a particular model.

**Comment by lucthev** [comment]
This seems to be a MySQL quirk, albeit a [documented one](https://dev.mysql.com/doc/refman/8.0/en/truncate-table.html):

> Truncate operations cause an implicit commit, and so cannot be rolled back.

I'm not sure there's much Rails can do about it?

**Comment by mlwyatt** [comment]
Since this isn't really a rails bug, I'll close
