### ISSUE TITLE
SecureRandom `base58` and `base36` doesn't work with 3.3.0preview1

### ISSUE THREAD

**Issue by stephannv** [rails/rails#49260]
### Steps to reproduce

Using ruby 3.3.0preview1 and Rails 7.1.0.beta1
```ruby
# Your reproduction script goes here
p SecureRandom.base58
p SecureRandom.base36
```

### Expected behavior

Should output something like that:
```ruby
p SecureRandom.base58 # => "1BipXQik5Pdq583m"
p SecureRandom.base36 # => "4vz0qqyk6rf5mpxx"
```

### Actual behavior

```
random/formatter.rb:241:in `alphanumeric': wrong number of arguments (given 2, expected 0..1) (ArgumentError)
```

### System configuration
**Rails version**: 7.1.0.beta1

**Ruby version**: 3.3.0preview1

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/49261#issuecomment-1718230791
