### ISSUE TITLE
Respect prereqs for each database on rake db:migrate

### ISSUE THREAD

**Issue by sobrinho** [rails/rails#49273]
### Steps to reproduce

We have some hooks on secondary connections like:

```
Rake::Task["db:migrate:auditing"].prereqs << "something"
```

But when we call `rake db:migrate` the prereqs aren't respected because of that line:

https://github.com/rails/rails/blob/6d4abdca5de1f85e1188e030d6cd8399948b02c1/activerecord/lib/active_record/railties/databases.rake#L100

Since we already have the rake task for each database defined, we could be invoking then instead:

https://github.com/rails/rails/blob/6d4abdca5de1f85e1188e030d6cd8399948b02c1/activerecord/lib/active_record/railties/databases.rake#L137

That would remove some code duplication as well.

### Expected behavior
prereqs for each database are invoked.

### Actual behavior
They are not.

### System configuration
**Rails version**: 6.1

**Ruby version**: N/A

**Comment by sobrinho** [comment]
I will do a PR to validate the complexity.

**Comment by paulreece** [comment]
Hey there, would you mind creating a small [reproduction script](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report) so that we can confirm the bug and test locally?

**Comment by sobrinho** [comment]
Not stale

**Comment by sobrinho** [comment]
Still trying to prioritize this but I will in the next days.

**Comment by sobrinho** [comment]
Not stale
