### ISSUE TITLE
Loosen nodes test condition

### ISSUE THREAD

**Issue by BuonOmo** [rails/rails#49274]
Hi,

I am the current maintainer of [cockroachdb/activerecord-cockroachdb-adapter](https://github.com/cockroachdb/activerecord-cockroachdb-adapter). In [one of the latest PRs](https://github.com/cockroachdb/activerecord-cockroachdb-adapter/pull/284) I have decided to overload the `Arel::Nodes::JoinSource` class to contain a new attribute, hence I also needed to override `==`, `eql?` and `hash`. This lead me to failing this test condition:

https://github.com/rails/rails/blob/910eb470c5c2f1871117893fc33f5443bde8bf8d/activerecord/test/cases/arel/nodes_test.rb#L23

Looking at the [commit message](https://github.com/rails/rails/commit/6d225a9870aea1fa25ab71774206d08d5b216355) introducing this condition:

> * that the class defining all 3 is also a descendant of Node, to avoid the default ones that rely on identity only

It feels like the test condition could be changed to something like: `subnode.instance_method(:==).super_method != nil`.

I can definitely do that in the adapter codebase (and will). But I'm opening this PR for two reasons:

1. Being sure I'm not overlooking an important aspect of the owner being descendent of `Arel::Nodes::Node`
2. Upstreaming the change to benefit the community if I'm not misleading!

Thank you for the dedication,
Ulysse

P.S: there are plenty of options to loosen this condition, I've chosen one arbitrarily here, but I can look deeper for sure!

**Comment by rafaelfranca** [comment]
Yes. It is fine to change that conditional. The owner doesn't need to be a descendent of `Arel::Nodes::Node`. Can you please open a PR?
