### ISSUE TITLE
ActionDispatch defaults to last file in POST request without bracket notation ( [] )

### ISSUE THREAD

**Issue by TravisGM92** [rails/rails#49286]
### Steps to reproduce

1. In the controller, permit all parameters (or just one)
2. Make a POST request, sending more than one file, without using the bracket notation:

```
curl -F "file=@sample.pdf" -F "file=@sample2.pdf" -X POST http://localhost:3000/upload-file
```
3. Verify in the controller that only _one_ file is available in the parameters.

### Expected behavior

Either ActionDispatch should automatically convert two parameters with the same name into an array with the 2 keys, or it should provide 2 parameters with the same name, each with different values.

### Actual behavior

Only the last file indicated in the POST request is available in the parameters (in my example, sample2.pdf).

### System configuration
**Rails version**: 7.0.5.1

**Ruby version**: 3.2.2

**Comment by rafaelfranca** [comment]
Thank you for the issue. This is the intended behavior. Changing this would break a lot of applications.
