### ISSUE TITLE
Precision removed for datetime column for postgres adapter

### ISSUE THREAD

**Issue by pegasusflyhigh** [rails/rails#49282]
Hi!

We got a dependabot PR to upgrade rails version from 7.0.7.2 to 7.0.8. But [this](https://github.com/rails/rails/commit/8db97a70460a42b12b61a3fe4cd57f26d3f95a3d) commit has changed our structure.sql removing precision 6 from a specific datetime column. 
We use postgres for database and that commit is for sqlite adapter. We want to understand the cause of this change in postgres adapter?

This is how we added the column :

```ruby
  change_table :tests, bulk: true do |t|
    t.column :activate_at, :datetime, null: true
  end

```

Please note that the precision was not removed where we added the column using `create_table` or `create_column`.

### System configuration
**Rails version**:  7.0.7.2

**Ruby version**:  ruby 3.2.2

**Comment by skipkayhil** [comment]
Hey @pegasusflyhigh, thank you for opening an issue. Can you modify [this script](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_migrations_gem.rb) to reproduce the issue for me? That will make it very easy to debug and see what the problem is
