### ISSUE TITLE
Upsert requires explicit column order for unique_by index

### ISSUE THREAD

**Issue by OskarEichler** [rails/rails#49308]
### Steps to reproduce
I have the following model SourceTrack with 3 columns:
type
external_id
title

On the table is a unique index on `[:type, :external_id]`

If I now try to perform an upsert operation but switch the order of the index like so:
`SourceTrack.upsert({type: 'AmazonSourceTrack', external_id: 1, title: "bro"}, unique_by: [:external_id, :type])`

it returns the error:
`ArgumentError: No unique index found for [:external_id, :type]`

Only when the order is exactly the same it performs the upsert:
`SourceTrack.upsert({type: 'AmazonSourceTrack', external_id: 1, title: "bro"}, unique_by: [:type, :external_id])`

### Expected behavior
It would be great if the order of the columns wouldn't matter.

### Actual behavior
The order needs to be exactly the same as how the index is created.

### System configuration
**Rails version**: 7.0.8
**Ruby version**: 3.2.1

**Comment by fatkodima** [comment]
Oh, hey there ✋ 
That is already implemented in https://github.com/rails/rails/pull/48018 and will be in rails 7.1.
