### ISSUE TITLE
Zeitwerk, omniauth and multiple DBs (connects_to)

### ISSUE THREAD

**Issue by fxn** [rails/rails#49310]
I move here https://github.com/fxn/zeitwerk/issues/275, because it is a Rails issue.

The description is big and there's already some conversation with some advances. I won't copy it all here. Please refer to the issue linked above for background.

**Comment by eileencodes** [comment]
I think the connection is fixed by https://github.com/rails/rails/pull/45450, so we can probably close this.

**Comment by fxn** [comment]
Thanks @eileencodes!
