### ISSUE TITLE
Provide an option to specify the database.yml file to be used when starting rails server

### ISSUE THREAD

**Issue by deXterbed1** [rails/rails#49326]
### Expected behavior
When working on multiple features at the same time, it pays off to have a separate copy of the DB for each branch in order to avoid schema changes from other branches that don't make sense when submitting a PR. Most of the time you end up reverting multiple migrations just to get rid these changes in the commit. 

One way is to change the database.yml file each time you switch branches, another would be to have a separate yml file that can be selected when restarting the server after switching the branch.

Something like `bin/rails s -D database_<feature_x>.yml` could be used to specify the yml file, which is not possible in rails at the time.

I would be happy to hear if there are any better alternatives to this!

**Comment by fatkodima** [comment]
I also saw this - https://fractaledmind.github.io/2023/09/06/enhancing-rails-sqlite-branch-databases/.

Rails issues are reserved for issues, but this looks like a feature request. You should better to discuss it on https://discuss.rubyonrails.org or on the Discord.
