### ISSUE TITLE
Documentation Bug, lack of definition of 'Resourceful' 

### ISSUE THREAD

**Issue by YusukeSuzuki** [rails/rails#49327]
The documentation lacks a definition of what conditions are met for resourceful routing.

**Comment by paulreece** [comment]
Hey Yusuke!  

So I took a look at the Guides and it looks like `resourceful` is defined [here](https://guides.rubyonrails.org/routing.html#crud-verbs-and-actions).

>[2.2 CRUD, Verbs, and Actions](https://guides.rubyonrails.org/routing.html#crud-verbs-and-actions)
In Rails, a resourceful route provides a mapping between HTTP verbs and URLs to controller actions. By convention, each action also maps to a specific CRUD operation in a database.

**Comment by YusukeSuzuki** [comment]
The word Resourceful, however, appears abruptly before the clause.

> [2 Resource Routing: the Rails Default](https://guides.rubyonrails.org/routing.html#resource-routing-the-rails-default)
> Resource routing allows you to quickly declare all of the common routes for a given resourceful controller.

The description in 2.2 is a description of a resourceful route, not a definition. Resourceful route does ~~" is a description, and "Resourceful route is what does ~~" is a definition.

After all, is it correct to say that a resourceful route is one that routes the 8 specified requests for a resource, and a resourceful controller is one that is complete with the 8 specified actions?

I don't know what Resourceful refers to and I'm totally confused by this chapter.

**Comment by paulreece** [comment]
Yusuke, thank you for clarifying your confusion.  In the future when raising an issue if you could quote the specific area of the docs that are confusing you that would be more helpful. 

> The description in 2.2 is a description of a resourceful route, not a definition. Resourceful route does ~~" is a description, and "Resourceful route is what does ~~" is a definition.

I disagree with you here.  This is an unnecessary distinction in semantics.  The guide tells you that a `resourceful route` provides a mapping between HTTP verbs and URLS to controller actions.  This _defines_ what a `resourceful route` is.  The definition could be more detailed sure, but you still are told what the meaning of the phrase is. 

The guides then go on to give you a table mapping for the HTTP CRUD verbs to each route, further [defining](https://guides.rubyonrails.org/routing.html#crud-verbs-and-actions) it.

> After all, is it correct to say that a resourceful route is one that routes the 8 specified requests for a resource, and a resourceful controller is one that is complete with the 8 specified actions?

Almost, if you read the definition again that I quoted earlier it tells you that `a resourceful route provides a mapping between HTTP verbs and URLs to controller actions`.  Extrapolating this to your definition it would be more like "a resourceful route is one that routes an HTTP verb/URL to a Controller Action"(singular).  When you specify `resources: photos` in your `routes.rb` it is telling you that for each route in the table from the link above you are now getting a controller action made available to you as well as a URL for it.  Of course you would then have to specifically create the controller action yourself depending on how you are creating things in your rails app.

All this to say I think you are maybe confused by the phrase `resourceful controller`.  I think that could be defined further if you find it helpful.  Feel free to add more to define `resourceful routes` if you think that would be helpful as well.  I'd suggest opening a PR for the Docs and submitting your suggested changes.

**Comment by mateusdeap** [comment]
So, I may be just intruding, but since I was looking for issues to help on, I'd like to chime in with my own 2 cents.

Maybe just saying:

> Resource routing allows you to quickly declare all of the common routes for a given  controller.

Would be clearer, since then it doesn't seem like we're talking about some special controller type. A resourceful controller is just a plain controller. Or better yet, if you go back to what REST is supposed to be about, maybe saying `resource controller` is more accurate, since, as I understand it, the doc is just trying to single out controllers responsible for interfacing the client with a given resource (as opposed to controllers that might be more geared toward some form of state management or something, and saying that a controller is resourceful can be understood from context, but might be an improper term.

**Comment by paulreece** [comment]
Hey Mateus,

Thanks for sharing your thoughts.  I think that's a totally reasonable addition to the Docs and an excellent assessment of the situation.  Feel free to open a PR adding in your change.

**Comment by mateusdeap** [comment]
@paulreece Done
