### ISSUE TITLE
Rails db:migrate is not running, not giving any error as well

### ISSUE THREAD

**Issue by ayuPar** [rails/rails#49330]
### Steps to reproduce
I am able to perform all the rails command except for rails db:migrate , it is nor running neither giving any error, just there are some warnings. But when I am running it by using test environment it is working.
I rollback two migration and now when I am running rails db:migrate nothing happened and when I checked the status using rails db:migrate:status those migration is down.

### System configuration
**Rails version**:
ruby '2.6.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.6'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'

**Comment by fatkodima** [comment]
Rails 6 is not supported for bug fixes (https://guides.rubyonrails.org/maintenance_policy.html).
Can you provide a sample rails 7+ app that reproduces the issue?

**Comment by ayuPar** [comment]
In my project I am using Rails 6

**Comment by fatkodima** [comment]
Closing, if you will be able to provide a repro, I will reopen.
