### ISSUE TITLE
Locals on partials now are only accepted with special comments.

### ISSUE THREAD

**Issue by celsoMartins** [rails/rails#49333]
Hi all.

It's really unbelievable that this is happening: https://blog.kiprosh.com/allow-template-to-set-strict-locals/

I can only access the partial variables with a weird special comment.

Do you know what the result in the code will be, right?

1. Developers will stop using partials
2. If they do, they will use the controller's instance variables.

Do you have any plans to rollback it? To make it optional or magical in the Rails way?

I'll have to change every partial in all of my projects.

I attached the error I'm getting that led me to the post above.

Thanks.

![Screenshot 2023-09-20 at 12 25 58](https://github.com/rails/rails/assets/214322/8523cc10-218f-46db-a7f1-870b51850e3b)

**Comment by celsoMartins** [comment]
I don't know how it could be a good idea. Or am I missing anything?

**_slots_table.html.erb**

```
<%# locals: (experience_price:, slots:) -%>

<% if slots.present? %>
  <table class="table table-sm table-striped">
    <thead>
      <tr>
        <th><%= Slot.human_attribute_name :slot_time %></th>
        <th><%= Slot.human_attribute_name :slot_price %></th>
        <th><%= Slot.human_attribute_name :spots %></th>
        <th><%= I18n.t('general.actions.title') %></th>
      </tr>
    </thead>

    <tbody id="slots-list">
      <%= render 'slots/slots_list', experience_site: experience_site, slots: slots %>
    </tbody>
  </table>
<% else %>
  <h2 class="text-center fst-italic"><%= I18n.t('slots.index.empty') %></h2>
<% end %>
```

**_slots_list.html.erb**

```
<%# locals: (experience_price:, slots:) -%>

<% slots.each do |slot| %>
  <tr>
    <td><%= I18n.l(slot.slot_time, format: :short) %></td>
    <td><%= number_to_currency(slot.slot_price) %></td>
    <td><%= slot.spots.count %></td>
    <td>
      <% if current_admin.manager? || current_admin.attendant? %>
        <%= button_to experience_site_slot_path(experience_site, slot), method: :delete, class: "btn btn-sm text-danger" do %>
          <i class="bi bi-trash"></i>
        <% end %>
      <% end %>
    </td>
  </tr>
<% end %>
```

I have tried with the full syntax `render partial: 'foo', locals: { bar: 1, xpto: 2 }` but I was able to solve the problem using the "magic comment" only. Without it, I can't access the values as I always did in the past.

Thanks.

**Comment by skipkayhil** [comment]
Hey @celsoMartins, can you provide a sample repo that demonstrates the problem you are facing? It's not to me from the information you have provided

**Comment by celsoMartins** [comment]
Hi @skipkayhil 

I'm working now on a private repository. And I can't open it fully.

The problem is that I was able to access partial local variables without the need for local_assigns or the magic comment specifying the variables.

Before the magic comment, I could only access variables through `local_assigns`. I added the comment at the top of the partial and it accepted the direct use of the variable. As it has been working until now.

Could you be more specific on what additional information you need?

Thanks for the prompt response.

**Comment by skipkayhil** [comment]
> I'm working now on a private repository. And I can't open it fully.

Right, can you generate a new Rails application that demonstrates the issue? For example, I performed the following steps:

```
$ rails -v
Rails 7.1.0.beta1
$ rails new --minimal min
...
$ rails g scaffold Post title:string
# Verified that 'render "form", post: @post' does the correct thing
# Updated app/views/posts/edit.html.erb as per your description: 'render partial: "form", locals: { post: @post }'
# Verified that also performs as expected
```

And I'm not seeing the behavior you describe

---

The magic comment is _only_ if you want to prevent unexpected locals from being passed to a partial, it is not a requirement, and code should be behaving the same as before if you don't include it

**Comment by celsoMartins** [comment]
Great. So the problem might be in my app setup? Where is this setup? I can add my setup files and the issue may be there.

I can provide some more context: It is a rails + react application with graphql. The admin part is only rails with erb templates. They're both the same app providing admin features and a GraphQL API to respond Apollo requests. It's a very common setup that we use here and this application is the only one that we detected this behavior so far. I didn't look into the other apps after I found out the issue in one of them.

I might be missing anything. I couldn't find the documentation on that feature in the rails doc. How can I enable and disable it?

Thanks.

**development.rb**
```
require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.cache_classes = false

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing
  config.server_timing = true

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true

    config.cache_store = :memory_store
    config.public_file_server.headers = {
      "Cache-Control" => "public, max-age=#{2.days.to_i}"
    }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  config.action_mailer.raise_delivery_errors = false
  config.action_mailer.perform_caching = false
  host = 'localhost'
  config.action_mailer.default_url_options = { host: host, port: 3000 }

  config.force_ssl = true

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  external_host = /[a-z0-9-.]+\.ngrok-free\.app/

  config.hosts << external_host
  Rails.application.routes.default_url_options[:host] = external_host

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  config.cache_classes = false
  config.assets.compile = true
  config.assets.debug = true
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  # config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true
end
```

**application.rb**

```
require_relative "boot"

require "rails"
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_mailbox/engine"
require "action_text/engine"
require "action_view/railtie"
require "action_cable/engine"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module NaturalExtremo
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 7.0

    config.i18n.available_locales = %w[pt-BR en]
    config.i18n.default_locale = 'pt-BR'

    config.time_zone = 'Brasilia'
    config.beginning_of_week = :sunday

    # Don't generate system test files.
    config.generators.system_tests = nil

    config.assets.enabled = true

    config.action_controller.default_protect_from_forgery = false
    config.session_store :_natural_extremo, secure: true

    config.active_job.queue_adapter = :sidekiq

    # This also configures session_options for use below
    # config.middleware.use ActionDispatch::Cookies
    # config.middleware.use ActionDispatch::Session::CookieStore, key: '_natural_admin_session'

  end
end
```

**Comment by skipkayhil** [comment]
> I might be missing anything. I couldn't find the documentation on that feature in the rails doc. How can I enable and disable it?

https://edgeguides.rubyonrails.org/action_view_overview.html#strict-locals

The documentation is here. The magic comment is the way to opt-in or out

> So the problem might be in my app setup? Where is this setup? I can add my setup files and the issue may be found there.

At this point we're debugging your application instead of fixing a bug, which is not the purpose of the issue tracker. There could be any number of gems in your application doing something unexpected. I recommend trying to start from a new Rails app and applying gems and configuration to it until you're able to find the problem. Until then, I'm going to close this issue as we do not provide application support on the issue tracker.

If you are able to reproduce the problem in a public app, then I'll be happy to re-open.

**Comment by celsoMartins** [comment]
The blog post I added in the very first post has more information than the documentation you linked here. It doesn't have any information on how to disable it.

Ok, I'm on my own. I'll try to find out why is RAILS demanding the strict locals now. Based on your last message, it seems that it is not a real concern for you and the framework. It was a classic "works on my machine".

**Comment by celsoMartins** [comment]
It's working now without the strict locals. For future searches, I didn't update my gems, and I didn't change any configs as well. I didn't even restart the server. I simply had the magic comments removed, tested again and it worked.

And I'm not the first one facing this intermittent issue. And I didn't clear any caches.

I would be curious about that.

https://stackoverflow.com/questions/18022525/partial-variables-availiable-only-through-local-assigns#comment26392675_18022525
