### ISSUE TITLE
`db:rollback:{database}` dumps all databases schemas

### ISSUE THREAD

**Issue by kv109** [rails/rails#49351]
### Steps to reproduce

Create a new Rails app
```
rails new --minimal rails-rollback-bug
cd rails-rollback-bug
```

Replace the `development` section in the `database.yml` with:
```yaml
development:
  primary:
    <<: *default
    database: db/primary.sqlite3
  secondary:
    <<: *default
    database: db/secondary.sqlite3
```

Run the rollback task:
```
rails db:rollback:primary
```

Verify that schemas for both databases were dumped, even though the task was supposed to be performed only for the `primary` database:
```
ls db | grep schema
schema.rb
secondary_schema.rb # this should not be here!
```

### Expected behavior
Only schema for the primary database should be dumped, i.e. only the `schema.rb` file should be created.

### Actual behavior
Schemas for both databases are dumped, i.e. two files (`schema.rb` and `secondary_schema.rb`) are created.

### Fix
I have a [fix](https://github.com/rails/rails/compare/main...kv109:rails:dont-dump-all-schemas-after-rollback?expand=1), but I didn't open a pull request, because I'm not sure how/if to test it. It looks like this aspect of databases tasks is [not tested at all](https://github.com/rails/rails/blob/main/activerecord/test/cases/tasks/database_tasks_test.rb), at least I couldn't find such tests. I'd be happy to write them, but I need some guidance.

### Is this really a problem?
If
1. Your secondary database schema isn't maintained by your Rails app and
2. you don't want to set `database_tasks` option to `false`, because you still want to be able to use `db:create`, `db:drop`, etc. (for easier development),

then each `db:rollback` will result in `ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column schema_migrations.version does not exist`, which can be pretty annoying.

### System configuration
Rails version: 7.0.8
Ruby version: 3.2.2

**Comment by hahmed** [comment]
The tests for the db tasks look like they are [in railties](https://github.com/rails/rails/blob/7c03e4f1b7553084f34318a9efc2793137de36f4/railties/test/application/rake/migrations_test.rb#L7)

Let's say you have an app with a schema (primary) already, and if you run `bin/rails db:migrate:primary` whilst having a secondary database setup in database.yml it does not create the `secondary_schema.rb`, taking that into account I think this makes sense 🤔
