### ISSUE TITLE
Activestorage direct uploads exhibits weird behaviour with data:{turbo:true}

### ISSUE THREAD

**Issue by nkokkos** [rails/rails#49354]
### Steps to reproduce

Create a simple rails application with esbuild and use the example as posted here https://edgeguides.rubyonrails.org/active_storage_overview.html#example. 

Enable turbo with data:{turbo:true} on the link leading to the upload page.

### Expected behavior

This should really happen:
https://edgeguides.rubyonrails.org/active_storage_overview.html#example.

### Actual behavior

During the upload process, the progress bars are shown more than once. For example, if I upload one file, two upload bars are shown and only one is active (both bars have the name of the file being uploaded). Now, if I try to upload again another file, 3 progress bars are shown and only one is active. 

### System configuration
**Rails version**: 7.0.8

**Ruby version**:  3.2.2

**Comment by hahmed** [comment]
Hey @nkokkos any chance you could link to a repo that reproduces this issue? That will really help, thank you.

**Comment by nkokkos** [comment]
Hi, 

@hahmed 
Unfortunately, I can not reproduce it on a new rails app. I tried to extract most of the part of the application where I was having the trouble to a new one here: https://github.com/nkokkos/test_upload but it seems everything works fine. I guess I have more digging to do in my own app. Thank you

**Comment by zzak** [comment]
Please open an issue when you have a reproduction, I realize writing a script for this with the JS is hard so a repo is fine as long as it can demonstrate the bug. Closing this until there is new information.
