### ISSUE TITLE
`bin/rails test` command is compiling assets too

### ISSUE THREAD

**Issue by luizkowalski** [rails/rails#49363]
Hey 👋🏻 

I'm seeing this strange behavior when running my app on the `main` Rails branch: executing the tests with `bin/rails test` will first compile the assets prior to executing the test suite.

I checked the edge upgrade guide and changelog and I see no mention of this behavior

<details><summary>when on branch main</summary>
<p>

```ruby
sumiu on  rails-main +1 -113974 [$✘!?] via  orbstack via  v20.7.0 via 💎 v3.2.2 via 📟 5GiB/8GiB
❯ rt
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.06s.
yarn run v1.22.19
$ postcss ./app/assets/stylesheets/application.postcss.css -o ./app/assets/builds/style.css

🌼 daisyUI 3.7.7 https://daisyui.com
╰╮
 ╰─ ✔︎ [ 3 ] themes are enabled. You can add more themes or make your own theme:
      https://daisyui.com/docs/themes

    ❤︎ Support daisyUI: https://opencollective.com/daisyui

✨  Done in 0.70s.
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.07s.
yarn run v1.22.19
$ esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds --public-path=assets --minify

  app/assets/builds/application.js      988.0kb
  app/assets/builds/application.js.map  586.5kb

✨  Done in 0.15s.
Running 7 tests in a single process (parallelization threshold is 50)
Run options: --seed 64798

# Running:

.......

Finished in 0.280526s, 24.9531 runs/s, 53.4710 assertions/s.
7 runs, 15 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Minitest to /Users/luiz/Projects/sumiu/coverage. 96 / 105 LOC (91.43%) covered.
```

</p>
</details> 

<details><summary>when on 7.0.x</summary>
<p>

```ruby
❯ rt
Running 7 tests in a single process (parallelization threshold is 50)
Run options: --seed 61047

# Running:

.......

Finished in 0.266972s, 26.2200 runs/s, 52.4400 assertions/s.
7 runs, 14 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for Minitest to /Users/luiz/Projects/sumiu/coverage. 99 / 100 LOC (99.0%) covered.
```

</p>
</details> 

I checked the changelog and the upgrade

### Steps to reproduce

```
rails _7.1.0.beta1_ new app_name
cd app_name
bin/rails g model user email:string
bin/rails test
```

### Expected behavior
Assets not to be compiled during test

### Actual behavior
Assets being compiled

### System configuration
**Rails version**:
7.1.0.beta1

**Ruby version**:
3.2.2

**Comment by skipkayhil** [comment]
I saw this happening to me as well, thanks for creating an issue

**Comment by ghiculescu** [comment]
Here’s some background: https://github.com/rails/rails/pull/46664

**Comment by luizkowalski** [comment]
To me, just a surprise as there is nothing about this behavior mentioned anywhere.

I assume this is meant mainly for system tests right? if this is so, doesn't make sense to only compile assets when system tests are triggered (or if `ENV["CI"]` is truthy)?

**Comment by ghiculescu** [comment]
No, it's for any tests. The original driver was for CI but it's helpful to have a single command that can run all Rails tests without any other setup required.

I've opened https://github.com/rails/rails/pull/49370 to add it to the upgrade guide.
