### ISSUE TITLE
Can Rails run without tzdata / tzinfo-data

### ISSUE THREAD

**Issue by voxik** [rails/rails#49375]
The tzdata package is by default not installed in Fedora anymore. Due to this, quite some package depending on Rails are failing for us with errors such as:

~~~
/usr/share/gems/gems/tzinfo-2.0.6/lib/tzinfo/data_sources/zoneinfo_data_source.rb:252:in `initialize': None of the paths included in TZInfo::DataSources::ZoneinfoDataSource.search_path are valid zoneinfo directories. (TZInfo::DataSources::ZoneinfoDirectoryNotFound)
    from /usr/share/gems/gems/tzinfo-2.0.6/lib/tzinfo/data_source.rb:157:in `new'
    from /usr/share/gems/gems/tzinfo-2.0.6/lib/tzinfo/data_source.rb:157:in `create_default_data_source'
    from /usr/share/gems/gems/tzinfo-2.0.6/lib/tzinfo/data_source.rb:55:in `block in get'
    from /usr/share/gems/gems/tzinfo-2.0.6/lib/tzinfo/data_source.rb:54:in `synchronize'
    from /usr/share/gems/gems/tzinfo-2.0.6/lib/tzinfo/data_source.rb:54:in `get'
    from /usr/share/gems/gems/activesupport-7.0.8/lib/active_support/railtie.rb:88:in `block in <class:Railtie>'
    from /usr/share/gems/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `instance_exec'
    from /usr/share/gems/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `run'
    from /usr/share/gems/gems/railties-7.0.8/lib/rails/initializable.rb:61:in `block in run_initializers'
    from /usr/share/ruby/tsort.rb:231:in `block in tsort_each'
    from /usr/share/ruby/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
    from /usr/share/ruby/tsort.rb:434:in `each_strongly_connected_component_from'
    from /usr/share/ruby/tsort.rb:352:in `block in each_strongly_connected_component'
    from /usr/share/ruby/tsort.rb:350:in `each'
    from /usr/share/ruby/tsort.rb:350:in `call'
    from /usr/share/ruby/tsort.rb:350:in `each_strongly_connected_component'
    from /usr/share/ruby/tsort.rb:229:in `tsort_each'
    from /usr/share/ruby/tsort.rb:208:in `tsort_each'
    from /usr/share/gems/gems/railties-7.0.8/lib/rails/initializable.rb:60:in `run_initializers'
    from /usr/share/gems/gems/railties-7.0.8/lib/rails/application.rb:372:in `initialize!' 
~~~

The thing is that while we can force installation of tzdata via package dependencies, some projects might opt for installing tzinfo-data gem instead.

Now I have two questions:

1) Are the tzdata really always required? Could they be e.g. lazy loaded?

2) I believe that the error is not properly handled. In the following code:

https://github.com/rails/rails/blob/e35e78020f27836a53f5e54ada1c3e63aed2cd4f/activesupport/lib/active_support/railtie.rb#L89-L93

Not only the `TZInfo::DataSourceNotFound` should be handled, but also the `TZInfo::DataSources::ZoneinfoDirectoryNotFound` we are facing.

**Comment by voxik** [comment]
> Not only the `TZInfo::DataSourceNotFound` should be handled, but also the `TZInfo::DataSources::ZoneinfoDirectoryNotFound` we are facing.

Although the error message is informative enough. Not sure what would be different if there was extra handling of this.

**Comment by voxik** [comment]
> The tzdata package is by default not installed in Fedora anymore. 

BTW here is more details why this change was done:

https://fedoraproject.org/wiki/Changes/AllowRemovalOfTzdata

**Comment by rafaelfranca** [comment]
I don't think this can be lazy loaded, but if people want to use fedora to run their Rails app, they can see the exception and add `tzinfo-data` to the gemfile like they already have to do in Windows. I'll make sure that exception also shows the same message.

**Comment by voxik** [comment]
> I don't think this can be lazy loaded,

I was afraid of that 

> but if people want to use fedora to run their Rails app, they can see the exception and add `tzinfo-data` to the gemfile like they already have to do in Windows. I'll make sure that exception also shows the same message.

Or installing tzdata package would also resolve the issue. But that would make the message less comprehensive probably.

Do you think that asking tzinfo maintainers for adding some default timezone, such as UTC would also work?

**Comment by rafaelfranca** [comment]
> Do you think that asking tzinfo maintainers for adding some default timezone, such as UTC would also work?

I think that would be good. It can't be lazy because rails needs to setup to use the configured timezone, which by default is UTC. If UTC doesn't need to load the data we can change the code to only load the data when something different from the default is configured.

**Comment by philr** [comment]
> Not only the TZInfo::DataSourceNotFound should be handled, but also the TZInfo::DataSources::ZoneinfoDirectoryNotFound we are facing.

> I'll make sure that exception also shows the same message.

@rafaelfranca It isn't necessary to handle `TZInfo::DataSources::ZoneinfoDirectoryNotFound`. `TZInfo::DataSource.get` throws `TZInfo::DataSourceNotFound` with `TZInfo::DataSources::ZoneinfoDirectoryNotFound` as the inner exception when there's no data available:

```ruby
> TZInfo::DataSources::ZoneinfoDataSource.search_path = ['/tmp/nothing']
=> ["/tmp/nothing"]
> TZInfo::DataSource.get
/home/philr/tzinfo/tzinfo/lib/tzinfo/data_source.rb:159:in `rescue in create_default_data_source': No source of timezone data could be found. (TZInfo::DataSourceNotFound)
Please refer to https://tzinfo.github.io/datasourcenotfound for help resolving this error.
        from /home/philr/tzinfo/tzinfo/lib/tzinfo/data_source.rb:156:in `create_default_data_source'
        from /home/philr/tzinfo/tzinfo/lib/tzinfo/data_source.rb:55:in `block in get'
        from /home/philr/tzinfo/tzinfo/lib/tzinfo/data_source.rb:54:in `synchronize'
        from /home/philr/tzinfo/tzinfo/lib/tzinfo/data_source.rb:54:in `get'
/home/philr/tzinfo/tzinfo/lib/tzinfo/data_sources/zoneinfo_data_source.rb:252:in `initialize': None of the paths included in TZInfo::DataSources::ZoneinfoDataSource.search_path are valid zoneinfo directories. (TZInfo::DataSources::ZoneinfoDirectoryNotFound)
        from /home/philr/tzinfo/tzinfo/lib/tzinfo/data_source.rb:157:in `new'
        from /home/philr/tzinfo/tzinfo/lib/tzinfo/data_source.rb:157:in `create_default_data_source'
        from /home/philr/tzinfo/tzinfo/lib/tzinfo/data_source.rb:55:in `block in get'
        from /home/philr/tzinfo/tzinfo/lib/tzinfo/data_source.rb:54:in `synchronize'
        from /home/philr/tzinfo/tzinfo/lib/tzinfo/data_source.rb:54:in `get'
```

Commit 54f30488e190eea5e923fe51914051df0e8c33f6 also handles `TZInfo::ZoneinfoDirectoryNotFound`, which doesn't exist in tzinfo >= 2.0.0.
