### ISSUE TITLE
Rails.logger is unpredictable

### ISSUE THREAD

**Issue by mperham** [rails/rails#49389]
```
rails-15ccf5be962b/railties (main *) % git grep "logger =" lib
lib/rails/application/bootstrap.rb:          logger = if config.log_file_size
lib/rails/application/bootstrap.rb:          logger = ActiveSupport::TaggedLogging.new(logger)
lib/rails/application/bootstrap.rb:          logger = ActiveSupport::TaggedLogging.new(ActiveSupport::Logger.new(STDERR))
lib/rails/application/bootstrap.rb:          Rails.error.logger = Rails.logger
lib/rails/autoloaders.rb:      each { |loader| loader.logger = logger }
lib/rails/commands/server/server_command.rb:          Rails.logger = ActiveSupport::BroadcastLogger.new(Rails.logger, console)
lib/rails/generators/rails/app/templates/config/environments/production.rb.tt:  config.logger = ActiveSupport::Logger.new(STDOUT)
```

There are at least three different possible types for `Rails.logger`: AS::Logger, AS::BroadcastLogger and AS::TaggedLogging. I'd like to see Rails.logger be of a predictable type so I can safely and consistently manipulate it in my initializer.

**Comment by rafaelfranca** [comment]
Thank you for the issue, but you should depend in the interface, not in the specific implementation. All implementation respond to the same methods. If they don't please open an issue that we will fix.

**Comment by mperham** [comment]
AS::Logger doesn't respond to `broadcast_to`.

```
undefined method `broadcast_to' for #<ActiveSupport::Logger:0x000000010a8e0390 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x0000000109e60870 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x0000000109e604b0 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x000000010a8e03e0 @shift_period_suffix="%Y%m%d", @shift_size=1048576, @shift_age=0, @filename="/Users/mperham/src/sidekiq/test/dummy/log/development.log", @dev=#<File:/Users/mperham/src/sidekiq/test/dummy/log/development.log>, @binmode=false, @mon_data=#<Monitor:0x0000000109e607a8>, @mon_data_owner_object_id=3520>> (NoMethodError)

            ::Rails.logger.broadcast_to(config.logger)
                          ^^^^^^^^^^^^^
```

**Comment by rafaelfranca** [comment]
Nothing does anymore. That method was removed. But `AS::Logger` doesn't respond to `tag`, so indeed this is an issue. We will probably need to always use a tagged log.

**Comment by rafaelfranca** [comment]
I see the issue you found is related to `broadcast_to`. That method was private API and it was removed. The new way to broad cast a logger, which is now public is creating an instance of `ActiveSupport::BroadcastLogger`

In your case:

```
ActiveSupport::BroadcastLogger.new(Rails.logger, config.logger)
```

That doesn't solve the problem to Rails < 7.1, but it will allow sidekiq to be sure it will not break in the future without warning since that new class is public

**Comment by mperham** [comment]
```ruby
Rails.logger = ActiveSupport::BroadcastLogger.new(Rails.logger, config.logger)
```

Sidekiq doesn't "own" this global attribute and it feels wrong that I should completely replace it. Overwriting it will undo any other changes or monkeypatches in the app initializers. This is your recommended usage?

**Comment by rafaelfranca** [comment]
It depends on how late you do that change. `Rails.logger` is owned by the application, and it is fine to libraries to configure it, but depending on the order you do it, it is true that you can get overridden, or override application configuration.

I think if you do in a `after_initialize` block, it should be fine. At this point the application already configured everything to the logger.

I don't think it will be worse to do `Rails.logger = ActiveSupport::BroadcastLogger.new(Rails.logger, config.logger)` than it is to do `::Rails.logger.extend(::ActiveSupport::Logger.broadcast(config.logger))`.

In both cases, the application could completely override `Rails.logger` after you that code is executed in Sidekiq.

**Comment by mperham** [comment]
😎👍🏼
