### ISSUE TITLE
Did the local and remote option of form helpers became obsolete?

### ISSUE THREAD

**Issue by gregmolnar** [rails/rails#49384]
I have a few questions about `form_for` and `form_with`.
`form_for` has a `remote` option to generate the form tag with a 'data-remote="true"' attribute. That attribute is used by Rails UJS to submit the form remotely if set. Since Rails UJS is not included in the latest Rails anymore, should this option be deprecated? 
The same question applies to the local option of `form_with`.
And since Turbo seems to be the new recommended way to handle remote forms, wouldn't it be better to control the data attribute to enable/disable Turbo on the form tag?

And if anything is done to these options, maybe the naming could be aligned, I find it a little confusing to have "remote" for one and "local" for the other.

**Comment by rafaelfranca** [comment]
The issue tracker isn't place for questions.
You can use the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for questions about implementation of the framework.
