### ISSUE TITLE
nested_attributes create with pre-filled id

### ISSUE THREAD

**Issue by armellarcier** [rails/rails#49385]
### Steps to reproduce

```ruby
order = Order.new
order.order_lines_attributes = [{ id: 'uuid1', name: 'first line', _create: true }]
order.save
```

### Expected behavior

creates an Order with an OrderLine, giving the OrderLine 'uuid1' as an id

### Actual behavior

`raise_nested_attributes_record_not_found!`

### Suggestion

Add an option so that nested_attributes looks like

```
          if attributes["id"].blank? || attributes["_create"]
            unless reject_new_record?(association_name, attributes)
              association.reader.build(attributes.except(*UNASSIGNABLE_KEYS))
            end
...
```

### System configuration
**Rails version**: Rails 7.0.3.1

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-musl]

**Comment by nvasilevski** [comment]
I just wanted to add that since technically Rails doesn't expect the `_create` option in the attributes it's not a bug but rather a feature request which may be more suitable for https://discuss.rubyonrails.org/ as the issue tracker reserved for bugs. But I'll let someone else to evaluate
