### ISSUE TITLE
Ruby on rails back end not taking my request for log in with google from my React front end

### ISSUE THREAD

**Issue by Chris-Kamau** [rails/rails#49399]
Started POST "/user/google" for ::1 at 2023-09-27 08:23:16 +0300
Processing by UsersController#google as HTML
  Parameters: {"token"=>"[FILTERED]", "user"=>{}}
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT ?  [["LIMIT", 1]]
  ↳ app/controllers/users_controller.rb:74:in `current_user'
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.12ms)
Completed 422 Unprocessable Entity in 7ms (Views: 6.3ms | ActiveRecord: 0.4ms | Allocations: 995)

class UsersController < ApplicationController

  before_action :authenticate_user, only: [:show]

  def create
    user = User.create(user_params)
    if user.valid?
      session[:user_id] = user.id
      render json: { id: user.id, username: user.username, address: user.address, phone: user.phone, user_type: user.user_type }, status: :created
    else
      render json: { error: user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def show
    user = User.find_by(id: session[:user_id])
    if user
      render json: user
    else
      render json: { error: "Not authorized" }, status: :unauthorized
    end
  end

  def reset
    @username = User.find_by(username: params[:username].to_s)
    if @username.update(password: params[:password].to_s)
      render json: @username, status: :ok
    else
      render json: { error: 'Failed to update username.' }, status: :unprocessable_entity
    end
  end

  def google
    begin
      data = Google::Auth::IDTokens.verify_oidc(access_token, aud: "333805260504-3tnauvgaja1p1ha5itmc7b5u7a318eih.apps.googleusercontent.com")
      
      # Find the user based on data or create a new user if not exists
      user = User.find_or_create_by(email: data['email']) do |u|
        u.username = data['email'] # You can set a suitable username here
        u.password = SecureRandom.hex(12) # Generate a random password
      end
      
      # Set the user's ID in the session
      session[:user_id] = user.id
      
      # Sign in the user using your authentication method
      
      render json: { id: user.id, username: user.username, address: user.address, phone: user.phone, user_type: user.user_type }, status: :ok
    rescue StandardError => e
      render json: { error: 'Google authentication failed' }, status: :unprocessable_entity
    end
  end
  

  private

  def user_params
    params.permit(:user_type, :username, :password, :address, :phone, :email, :password_confirmation)
  end

  def authenticate_user
    unless logged_in?
      render json: { errors: "Unauthorized" }, status: :unauthorized
    end
  end

  def logged_in?
    session[:user_id].present?
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end
Here is my user controller

**Comment by fatkodima** [comment]
Hey @Chris-Kamau we reserve the Rails Issues tracker for bugs in the framework as we don't have the bandwidth to offer application support. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help with your application. Thanks for understanding.
