### ISSUE TITLE
Documentation: execution order of ActiveJob retry_on / discard_on is unspecified

### ISSUE THREAD

**Issue by dssjoblom** [rails/rails#49406]
As far as I can tell, the documentation does not explicitly define the order of execution of multiple `retry_on` / `discard_on` blocks. This makes application code unnecessarily dependent on internal implementation details.

For example, consider the following case:

```ruby
class BaseError < StandardError; end

class SpecializedError < BaseError; end

class MyJob < ApplicationJob 
  discard_on BaseError
  retry_on SpecializedError
end
```

The idea here would be to retry only specific errors and discard the rest. The example works as intended, but it is unclear why, as it fails if the order of the `discard_on` and `retry_on` lines are inverted.

**Comment by paulreece** [comment]
Thanks for bringing this to our attention!

Can you provide a repro script and compare and contrast how it differs from the current example in the docs?(https://guides.rubyonrails.org/active_job_basics.html#retrying-or-discarding-failed-jobs). 

```Ruby
class RemoteServiceJob < ApplicationJob
  retry_on CustomAppException # defaults to 3s wait, 5 attempts

  discard_on ActiveJob::DeserializationError

  def perform(*args)
    # Might raise CustomAppException or ActiveJob::DeserializationError
  end
end
```

**Comment by paulreece** [comment]
Thanks Earlopain. 
> I'm not sure what a repro script would be useful for, this is purely about documentation.
 
A repro script would have allowed me to invert the order and confirm the order was needed.  It's helpful to confirm the behavior before adding an item to the Documentation.  However with your explanation of why this is happening I agree that it's not needed now. 😎

> In cases of errors with overlapping inheritance like in the example provided example by OP the execution order matters for the expected behaviour. Currently they're executed last to first but the behaviour is undocumented, https://api.rubyonrails.org/classes/ActiveJob/Exceptions/ClassMethods.htmlm doesn't address it.

With this in mind I think a brief aside added to the Docs about the order of `retry_on` and `discard_on` in regards to using  Exceptions with overlapping inheritance.

**Comment by ghiculescu** [comment]
I think first to last would make more sense, as it would match how callbacks in Active Model (etc) work.

**Comment by simi** [comment]
I went thru this recently and both `retry_on` and `discard_on` are based on `rescue_from` and currently following this comment.

https://github.com/rails/rails/blob/7c03e4f1b7553084f34318a9efc2793137de36f4/activesupport/lib/active_support/rescuable.rb#L71-L72

Indeed documentation backed by automated tests ensuring the order is consistent (if not present yet) would be handy.

**Comment by ghiculescu** [comment]
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_job"
require "minitest/autorun"

GenericException = Class.new(StandardError)
RetryException = Class.new(GenericException)

module JobBuffer
  class << self
    def add(value)
      values << value
    end

    def values
      @values ||= []
    end
  end
end

class BuggyJob < ActiveJob::Base
  retry_on RetryException
  discard_on GenericException

  def perform
    if executions == 2
      JobBuffer.add("done")
    else
      raise RetryException
    end
  end
end

class BuggyJobTest < ActiveJob::TestCase
  def test_stuff
    perform_enqueued_jobs do
      BuggyJob.perform_later
    end

    assert_equal 1, JobBuffer.values.length
    assert_equal "done", JobBuffer.values.last
  end
end
```

Output:

```
[ActiveJob] [BuggyJob] [5ae9ed1a-32f2-40c4-ae66-87581a601f67] Performing BuggyJob (Job ID: 5ae9ed1a-32f2-40c4-ae66-87581a601f67) from Test(default) enqueued at 2023-09-27T23:43:54.844848000Z
[ActiveJob] [BuggyJob] [5ae9ed1a-32f2-40c4-ae66-87581a601f67] Discarded BuggyJob (Job ID: 5ae9ed1a-32f2-40c4-ae66-87581a601f67) due to a RetryException (RetryException).
[ActiveJob] [BuggyJob] [5ae9ed1a-32f2-40c4-ae66-87581a601f67] Performed BuggyJob (Job ID: 5ae9ed1a-32f2-40c4-ae66-87581a601f67) from Test(default) in 2.46ms
[ActiveJob] Enqueued BuggyJob (Job ID: 5ae9ed1a-32f2-40c4-ae66-87581a601f67) to Test(default)
F

Failure:
BuggyJobTest#test_stuff
Expected: 1
  Actual: 0
```

We should either:

- Fix behaviour such that handlers act in specified order
- Mention in docs that they are handled in reverse order

**Comment by ghiculescu** [comment]
https://github.com/rails/rails/blob/7c03e4f1b7553084f34318a9efc2793137de36f4/activesupport/lib/active_support/rescuable.rb#L126-L128 suggests this order is intentional.

**Comment by ghiculescu** [comment]
Per @rafaelfranca this behaviour is expected, and should be documented. I opened https://github.com/rails/rails/pull/49413 to update the docs, and I'll close this as behaving correctly.

**Comment by dssjoblom** [comment]
Thanks a lot, everyone 🙏
