### ISSUE TITLE
[DOCS] has_one association options in guides does reflect all options in api

### ISSUE THREAD

**Issue by silva96** [rails/rails#49419]
### Steps to reproduce

```ruby
# Your reproduction script goes here
```

### Expected behavior

Go to https://edgeguides.rubyonrails.org/association_basics.html#options-for-has-one

You should see :required option, and other options that are present [in the api](https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_one-label-Options)

I suspect has_many and maybe other relations don't reflect all options, like `: ensuring_owner_was`

### Actual behavior

Go to https://edgeguides.rubyonrails.org/association_basics.html#options-for-has-one

You don't see :required option, and other options that are present [in the api](https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_one-label-Options)

### System configuration
**Rails version**: Any version

**Ruby version**: It doesn't matter

**Comment by paulreece** [comment]
Hey Silva thanks for reporting this!

I think this makes total sense to add `:required, :disable_joins, :strict_loading, and :ensuring_owner_was` to this list.

Would you like to Open a PR to address this?

**Comment by silva96** [comment]
> Hey Silva thanks for reporting this!
> 
> I think this makes total sense to add `:required, :disable_joins, :strict_loading, and :ensuring_owner_was` to this list.
> 
> Would you like to Open a PR to address this?

Go ahead if you can, I'm a little busy, sorry :(
