### ISSUE TITLE
Weird `["` being added to cookie names on Rails 7.1.0 RC1

### ISSUE THREAD

**Issue by brunnopleffken** [rails/rails#49422]
### Steps to reproduce

I'm using Phusion Passenger + Nginx. I upgraded my app from Rails 7.0.8 to Rails 7.1 RC1, using the unaltered code below for getting email and password, authenticating and creating cookies as I always did:

```ruby
# authenticate and get user
# ...
token = WebToken.encode({ user_id: user.id })
cookies.permanent[:user_id] = token
```

Now, Rails 7.1.0 is storing cookies with `["`, like this:

<img width="633" alt="Screenshot 2023-09-28 at 18 59 38" src="https://github.com/rails/rails/assets/3427344/96f86b61-c7bf-4e1c-b616-bfba3ab664c2">

This is getting me a LOT of trouble because...

```ruby
if cookies[:user_id].blank?
  # ...I'm ALWAYS getting here because the cookie name is invalid
end
```

Renaming manually it to just `user_id` (which means removing `["`), everything works perfectly like before.

### Expected behavior

The name of the cookie should be `user_id`.

### Actual behavior

The name is `["user_id`, so it's impossible to authenticate a user with the actual name.

### System configuration
**Rails version**: 7.1.0 RC1

**Ruby version**: 3.3.0-preview2

**Comment by brunnopleffken** [comment]
Just a note. It's exactly the same project, but I rolled back to **Rails 7.0.8** with the old Gemfile from my Git history... the cookies are named properly and my authentication works:

<img width="318" alt="Screenshot 2023-09-28 at 19 43 47" src="https://github.com/rails/rails/assets/3427344/f91d3d8a-00b9-4c4f-9937-e43a5b5f644a">

No errors.

**Comment by skipkayhil** [comment]
Can you share your Rack version in both cases? Additionally, if you're able to provide a reproduction using one a [bug report template](https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller_gem.rb) (or a new Rails app) that would be very helpful

**Comment by skipkayhil** [comment]
I tried adding this to an empty controller action but my cookie is being set correctly with both Rack 2 and Rack 3. I think we'll definitely need more information to reproduce.

```
def index
  cookies.permanent[:user_id] = SecureRandom.uuid
end

**Comment by brunnopleffken** [comment]
Perhaps something in the production environment. I'm unable to reproduce it locally (Rails 7.1 with just `rails s` using Puma on my Mac M1 Pro). But in production (AWS EC2 + Ubuntu x64 + Nginx + Phusion Passenger + Ruby 3.3.0), as soon as I updated the project to Rails 7.1 I got this strange cookie error.

So, it's something with that combination in production — which is not that unusual.

As I noted, I rolled back the Rails version to 7.0.8 and Ruby to 3.2.2 in production to avoid further damage to our project. But I'll create a blank EC2 instance with that same config (Rails 7.1 + Ruby 3.3.0 + Nginx/Passenger) to see if I can reproduce this issue with a test project.

I'll get you in touch in this same issue.

**Comment by skipkayhil** [comment]
> Can you share your Rack version in both cases?

This is the important bit for you to check. Does Passenger support Rack 3?

**Comment by rafaelfranca** [comment]
@brunnopleffken were you able to confirm this issue also happens withou Passenger and if Passenger indeed supports Rack 3?

**Comment by zzak** [comment]
I just looked through the issues and PRs, as well as the commit history and my assumption is that no, they haven't really changed anything regarding rack in a very long time. Perhaps @ioquatix knows? (re: passenger rack 3 support)

**Comment by brunnopleffken** [comment]
Before the update (and now, after the downgrade), I was using Rack 2.2.8.
After upgrading to Rails 7.1 RC1, my Rack version was also upgraded to 3.0.8.

I'm creating a clean EC2 instance with Nginx + Passenger + Rails 7.1 to test this simulating a prod env.

Currently, I'm using the latest Passenger version.

<img width="413" alt="Screenshot 2023-10-02 at 11 16 09" src="https://github.com/rails/rails/assets/3427344/c1aaab4a-fce7-4773-bc24-046694c5e5b1">

I'm not sure about Rack 3.x support for Passenger. A quick search in their repository and their support page returned no results. As @zzak said, perhaps this issue should be theirs.

**Comment by ioquatix** [comment]
I don’t believe passenger supports rack 3.

cc @FooBarWidget

**Comment by brunnopleffken** [comment]
I just want to confirm my tests from yesterday. The same old project from before, Ruby on Rails 7.1 RC2 on Nginx + Passenger + Rails 3.3.0, but `gem 'rack', '~> 2.2'` is defined in Gemfile. Works perfectly!

<img width="323" alt="Screenshot 2023-10-03 at 12 09 29" src="https://github.com/rails/rails/assets/3427344/7186520f-f609-4912-8f8f-19fa44d66f20">

No more `["`.

The latest version of Phusion Passenger is incompatible with Rack 3. I think this should be mentioned in their documentation, since Rack 3 is the default for Rails 7.1 and could break some applications.
