### ISSUE TITLE
NoMethodError (undefined method `intern' for nil:NilClass)

### ISSUE THREAD

**Issue by ademir10** [rails/rails#49420]
### Steps to reproduce

```ruby
# Your reproduction script goes here
```

### Expected behavior

Call Mailer and send attachment after to use net http connection + certificates
### Actual behavior

When we try to use this code to generate a Bank Key for payment (PIX in Brazil) using the following code below we receive  this message:
**NoMethodError (undefined method `intern' for nil:NilClass)**

**Our Code:**
uri = URI.parse("https://cdpj.partners.bancointer.com.br/pix/v2/cob/#{idTransacao}")
                http = Net::HTTP.new(uri.host, uri.port)
                OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ssl_version]=nil
                http.use_ssl = true
                http.cert = OpenSSL::X509::Certificate.new(File.read("#{Rails.public_path}/certificates/Inter_API_Certificado.crt"))
                http.key = OpenSSL::PKey::RSA.new(File.read("#{Rails.public_path}/certificates/Inter_API_Chave.key"))
                http.ssl_version = :TLSv1_2
                http.verify_mode = OpenSSL::SSL::VERIFY_NONE

                request = Net::HTTP::Put.new(uri.request_uri, 'Content-Type' => 'application/json')
                request["Authorization"] = "Bearer #{bearer_token}"
                #Add Headers, if needed
                request.add_field 'X_REMOTE_USER', 'USER_NAME'
                request.add_field 'Accept', '*'
                request.body = json_params.to_json

                response = http.request(request)
**Here we can see the right response before to call the mailer.
After to generate the PDF attachment we receive the error**

dados_enviados = {
        "envio_fatura_manual" => params[:envio_manual].to_s,
        "mes_fechamento" => params[:mes].to_i,
        "cliente" => @cliente,
        "pix_payload" => pix_payload,
        "pix_qrcode" => pix_qrcode,
        "total_fatura" => $_total_fatura,
        "emprestimos" => @emprestimos,
        "qnt_emprestimos" => @qnt_emprestimos
      }

        EnviaFaturaMailer.enviar_pdf(dados_enviados).deliver_now

**Mailer Action:**
arquivo_pdf = WickedPdf.new.pdf_from_string(render_to_string pdf: "esign", template: "configs/pdf_licenca_uso.html.erb")
        attachments['Fatura mensal - Get empréstimos mês ' + dados_enviados['mes_fechamento'].to_s + '.pdf'] = arquivo_pdf

      mail( to: 'financeiro@ddti.com.br' + ';' + dados_enviados['cliente']['email'],
      subject: 'Fatura mensal - Get empréstimos - ' + dados_enviados['cliente']['razao'] )

**PS*****
If we remove the net http connection everything back to work.

any suggestion?
thank you Guys! 

### System configuration
**Rails version**:
Rails 6.0.6.1
**Ruby version**:
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Comment by skipkayhil** [comment]
Hey @ademir10, we use the issue tracker for bugs in Rails and don't provide application support. You could potentially try the [forums](discuss.rubyonrails.org) or stackoverflow instead.
