### ISSUE TITLE
Support for storing ActiveStorage::Blob metadata in a jsonb column type for PostgreSQL

### ISSUE THREAD

**Issue by vpereira** [rails/rails#49432]
I've been exploring the use of ActiveStorage with PostgreSQL and noticed that the metadata column for ActiveStorage::Blob is stored as text. Given the benefits of the jsonb data type in PostgreSQL (like indexing capabilities, and advanced querying), I'm wondering  if would worth to migrate this column to use jsonb.

So based on that I would like to:

* Understand if there are any specific reasons or considerations why the default type for metadata is text (I can imagine because of other database technologies, but just to be sure).

* Explore the possibility of Rails supporting or recommending jsonb for this purpose, especially since PostgreSQL is a popular choice among Rails developers.

* Suggest that if there are benefits to using jsonb for metadata, perhaps an option could be added to the ActiveStorage generators to allow developers to choose the column type when setting up ActiveStorage.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we reserve the issues tracker for issues only.. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.

**Comment by vpereira** [comment]
Hi @rafaelfranca,

Thank you for your response. I'm eager to submit a PR addressing this. When adjusting the ActiveStorage migration to use jsonb, should it automatically detect the PostgreSQL driver, or would you prefer this to be controlled via a configuration or rake task flag?

**Comment by rafaelfranca** [comment]
I think it should be automatic.
