### ISSUE TITLE
rails db:drop needs to drop -shm and -wal files with SQLite adapter

### ISSUE THREAD

**Issue by dhh** [rails/rails#49435]
Right now `rails db:drop` doesn't remove the -shm and -wal files with the SQLite adapter. Only the `.sqlite` files. Thus you get an error if you later recreate the database and those lingering files are still there.

**Comment by rafaelfranca** [comment]
@fractaledmind could you take a look at this? I think it is related to the performance changes you did in #49349

**Comment by fractaledmind** [comment]
I'll put a fix in tomorrow.

**Comment by fractaledmind** [comment]
Wow, love to wake up to a fix. Thanks @codergeek121!
