### ISSUE TITLE
Feature Request: :includes_counter for :has_many

### ISSUE THREAD

**Issue by chmich** [rails/rails#49450]
### Actual Behaviour

Invoice.includes(:customer) works well if `:customer` is a :belongs_to, for example

But Invoice.includes(`:positions`) doesnt work if `:positions` is a `:has_many` relation, for example.

Is reasonable.

### Expected behavior

Often in lists it would be helpful to see a counter of subrecords. Nothing else. And this would only be possible with a `:includes', for performance reasons.

### Feature request Idea

Would it be an idea to have a new function, say a `:includes_counter`, that only calculates the number of sub-records and loads it into the active-record relation?

Would it be possible to make this work for all associations and scopes where `:includes` is not currently capable?

Many thanks!

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.2.2

**Comment by rafaelfranca** [comment]
It seems you want the `:counter_cache` option? https://guides.rubyonrails.org/association_basics.html#options-for-has-many-counter-cache

Also, we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.
