### ISSUE TITLE
Change in ActiveRecord::Relation#merge behavior on v7.0.8

### ISSUE THREAD

**Issue by ajvondrak** [rails/rails#49463]
### Steps to reproduce

**Context:**
- 515aa1ea4ed6fc744636d5c3495e44b88057dcf6 changed how `ActiveRecord::Relation#merge` behaves circa v7.0.0rc1
- #48095 added the `Arel::Nodes::And#fetch_attribute` method circa v7.0.8 (previously, `And` used the default `Arel::Nodes::Node` implementation that just returns `nil`)
- However, the above patch has changed the output of `#merge` in a weird corner case, and I'm not sure whether it's considered correct (in light of the new Rails 7 behavior) or incorrect (because the output has changed—perhaps unexpectedly?—between patch versions)

```ruby
require "bundler/inline"

gemfile do
  gem "rails", ENV["RAILS_VERSION"]
  gem "sqlite3"
end

require "active_record"

# db adapter shouldn't actually impact this repro
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Schema.define { create_table :models, force: true }

class Model < ActiveRecord::Base
end

$nesting = 0

trace = TracePoint.new(:call, :return) do |tp|
  case tp.self
  when ActiveRecord::Relation::WhereClause, Arel::Nodes::Node
    case tp.event
    when :call
      puts "#{'  ' * $nesting}#{tp.self} #{tp.method_id}"
      $nesting += 1
    when :return
      $nesting -= 1
      puts "#{'  ' * $nesting}--> #{tp.return_value.inspect}"
    end
  end
end

# I'm afraid this is as simplified as I can get the repro! Our actual query had the same basic shape.
x = Model.where.not(a: 1)
y = Model.where.not(a: 2).where.not(b: ['', nil])
z = Model.where(c: true)
y_or_z = y.or(z)

trace.enable if ENV["TRACE"]
merged = x.merge(y_or_z)
trace.disable

puts "\n=== SQL generated on Rails #{Rails.version} ==="
puts merged.to_sql
```

Prior to v7.0.8, the `WHERE` clause includes the first `"models"."a" != 1` condition:

```console
$ RAILS_VERSION=7.0.7.2 ruby repro.rb
-- create_table(:models, {:force=>true})
   -> 0.0125s

=== SQL generated on Rails 7.0.7.2 ===
SELECT "models".* FROM "models" WHERE "models"."a" != 1 AND ("models"."a" != 2 AND NOT (("models"."b" = '' OR "models"."b" IS NULL)) OR "models"."c" = 1)
```

However, with the patch in v7.0.8, the `"models"."a" != 1` condition disappears:

```console
$ RAILS_VERSION=7.0.8 ruby repro.rb
-- create_table(:models, {:force=>true})
   -> 0.0056s

=== SQL generated on Rails 7.0.8 ===
SELECT "models".* FROM "models" WHERE ("models"."a" != 2 AND NOT (("models"."b" = '' OR "models"."b" IS NULL)) OR "models"."c" = 1)
```

### Expected behavior

I'm not sure what the desired behavior is here, in light of the changes to `#merge` circa Rails v7.0.0rc1.

It could be that this is now considered the "right" behavior: you could say that the `y_or_z` predicates include a condition on the `"models"."a"` column, so the predicates in `x` should be clobbered, even though the query results now change between patch versions of Rails.

OTOH, it seems like this behavior change may have been unintentional (as it relates to the `unscope` issue), so I wanted to call attention to it, in case there are more tests that can/should be added.

### Actual behavior

If you run the repro script with `TRACE=1`, you can see that `Arel::Nodes::And#fetch_attribute` winds up recursing down into its children in 7.0.8 (versus returning `nil` immediately in older versions), which appears to have a ripple effect on the logic of `ActiveRecord::Relation::WhereClause#referenced_columns`, which influences how the `#merge` goes (output truncated here for brevity):

```console
$ RAILS_VERSION=7.0.7.2 TRACE=1 ruby repro.rb | head -11
-- create_table(:models, {:force=>true})
   -> 0.0113s
#<ActiveRecord::Relation::WhereClause:0x000000010c498448> merge
  #<ActiveRecord::Relation::WhereClause:0x000000010c498448> predicates_unreferenced_by
    #<ActiveRecord::Relation::WhereClause:0x000000010c492fe8> referenced_columns
      #<ActiveRecord::Relation::WhereClause:0x000000010c492fe8> each_attributes
        #<ActiveRecord::Relation::WhereClause:0x000000010c492fe8> extract_attribute
          #<Arel::Nodes::Grouping:0x000000010c492598> fetch_attribute
            #<Arel::Nodes::Or:0x000000010c4926d8> fetch_attribute
              #<Arel::Nodes::And:0x000000010c492c00> fetch_attribute
              --> nil
```

```console
$ RAILS_VERSION=7.0.8 TRACE=1 ruby repro.rb | head -15
-- create_table(:models, {:force=>true})
   -> 0.0098s
#<ActiveRecord::Relation::WhereClause:0x000000010e09a538> merge
  #<ActiveRecord::Relation::WhereClause:0x000000010e09a538> predicates_unreferenced_by
    #<ActiveRecord::Relation::WhereClause:0x000000010e098850> referenced_columns
      #<ActiveRecord::Relation::WhereClause:0x000000010e098850> each_attributes
        #<ActiveRecord::Relation::WhereClause:0x000000010e098850> extract_attribute
          #<Arel::Nodes::Grouping:0x000000010e098508> fetch_attribute
            #<Arel::Nodes::Or:0x000000010e098558> fetch_attribute
              #<Arel::Nodes::And:0x000000010e0986c0> fetch_attribute
                #<Arel::Nodes::NotEqual:0x000000010e099ef8> fetch_attribute
                --> #<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x000000010c6c1fa8 @name="models", @klass=Model(id: integer), @type_caster=#<ActiveRecord::TypeCaster::Map:0x000000010e09cf68 @klass=Model(id: integer)>, @table_alias=nil>, name="a">
                #<Arel::Nodes::Not:0x000000010e0994a8> fetch_attribute
                --> nil
              --> false
```

### System configuration

**Rails version**: this potential regression applies to Rails 7.0.8

**Ruby version**: `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]`

**Comment by rafaelfranca** [comment]
Thank you for the issue. The 7.0.8 behavior is the desired behavior. Although the commit that fixed it wasn't actually planning to fix this behavior, the behavior is now correct.

**Comment by ajvondrak** [comment]
@rafaelfranca Great, thanks for confirming!

Curious: that being the case, do you think that this warrants a closer look at the Arel `#fetch_attribute` definitions at all? I.e., are there other nodes that are currently returning `nil` when they should be using custom logic, and thus could be affecting `#merge`?

A quick look at 7.0.8 shows that most nodes use the default `Arel::Nodes::Node#fetch_attribute` implementation:

```ruby
Arel::Nodes::Node.descendants.map { |node| node.instance_method(:fetch_attribute).owner }.tally
#=>
{
  Arel::Nodes::Node=>93,
  Arel::Nodes::HomogeneousIn=>1,
  Arel::Nodes::And=>1,
  Arel::Nodes::FetchAttribute=>11,
  Arel::Nodes::Or=>1,
  Arel::Nodes::Grouping=>1
}
```

But I also don't know a lot about the Arel node structure, so these could mostly just be leaves or otherwise not contain attributes (for all I know). Just raising the alarm, given the `And` oversight.

For instance, poking around on my local PostgreSQL database (adapter matters because SQLite doesn't support regexp nodes), it seems like this could be a problem:

```ruby
puts User.select(:name).where(name: 'clobber me').merge(User.where(User.arel_table[:name].matches_regexp('clobbered'))).to_sql
# SELECT "users"."name" FROM "users" WHERE "users"."name" = 'clobber me' AND "users"."name" ~ 'clobbered'

# This node doesn't define fetch_attribute, so let's teach it real quick
Arel::Nodes::Regexp.include(Arel::Nodes::FetchAttribute)

puts User.select(:name).where(name: 'clobber me').merge(User.where(User.arel_table[:name].matches_regexp('clobbered'))).to_sql
# SELECT "users"."name" FROM "users" WHERE "users"."name" ~ 'clobbered'
```

Happy to open a separate ticket, if desired.

**Comment by rafaelfranca** [comment]
I think it makes sense. If you want to check that would be awesome!
