### ISSUE TITLE
`validates_uniqueness_of` does not work with `mark_for_destruction`

### ISSUE THREAD

**Issue by ghiculescu** [rails/rails#49468]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.text :title
    t.integer :post_id

    t.index [:title, :post_id], unique: true
  end
end

class Post < ActiveRecord::Base
  has_many :comments, autosave: true
end

class Comment < ActiveRecord::Base
  belongs_to :post
  validates_uniqueness_of :title
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments.create!(title: "hi")

    # reload
    post = Post.find(post.id)

    post.comments[0].mark_for_destruction
    post.comments.build(title: "hi")

    # raises ActiveRecord::RecordInvalid: Validation failed: Comments title has already been take
    post.save!

    assert_equal 1, post.comments.count
  end
end
```

### Expected behavior
I expect the test to pass.

### Actual behavior
`post.save!` raises with a validation error.

If you remove the `validates_uniqueness_of` and just keep the unique database constraint, the test passes. I expect `validates_uniqueness_of` to do the same thing as an equivalent database index, so I expect it to not block the save here.

Before working on a PR I'd like to get confirmation on if this expectation is wrong.

### System configuration
**Rails version**: main

**Ruby version**: 3.2.2

**Comment by Jay0921** [comment]
@ghiculescu The uniqueness validation on Comment is run before any database operation. This is why you're encountering the error. You could add some logs within the callbacks to find out. 

```
class Comment < ActiveRecord::Base
  belongs_to :post
  validate :check_uniqueness_of_title

  after_save do
    puts "Created comment #{id}"
  end

  after_destroy do
    puts "Destroyed comment #{id}"
  end

  def check_uniqueness_of_title
    if Comment.where(title: title, post_id: post_id).exists?
      puts "#{title} has already been taken"
    end
  end
end
```

Results: 
```
Created comment 1
hi has already been taken
Destroyed comment 1
Created comment 2
```

**Comment by fatkodima** [comment]
The issue seems valid to me. 
So we should skip the uniqueness validation if the record is marked for destruction, I think?

**Comment by rafaelfranca** [comment]
Validations will run before the save action, and the fact that a record is marked for destruction is only know by the save action. I don't think there is a way to solve this without coupling autosave behavior with validation behavior, but if you find a solution let's go ahead and fix.

**Comment by ghiculescu** [comment]
> without coupling autosave behavior with validation behavior

Given that both behaviours are supported by Active Record, is coupling them a problem? Is it just that it's messy?

**Comment by rafaelfranca** [comment]
Not necessarily, but today is inexistent, so we can change autosave or uniqueness validation without having to consider each other behavior. So adding it might need to be well justified.
