### ISSUE TITLE
Incorrect Table Name Generated in create_join_table

### ISSUE THREAD

**Issue by jubilee2** [rails/rails#49479]
**Issue Report**

**Description:**

The `create_join_table :shiny_apps, :shiny_users` command is attempting to create a table named `shiny_apps_users`, but it should create a table named `shiny_apps_shiny_users`.

**Environment:**

- Ruby version: 3.2.2
- Rails version: 7.0.8

**Reproducibility:**

You can reproduce the issue by following these steps:

1. Create a new Rails application:
   ```
   rails new foobar
   cd foobar
   ```

2. Generate scaffolds for `shiny_app`, `user`, and `shiny_user`:
   ```
   rails g scaffold shiny_app name:string
   rails g scaffold user name:string
   rails g scaffold shiny_user name:string
   ```

3. Generate two migrations for join tables:
   ```
   rails g migration create_shiny_apps_users_join_table
   rails g migration create_shiny_apps_shiny_users_join_table
   ```

4. Run the migrations:
   ```
   rails db:migrate
   ```

5. In the last two migrations, use the following commands:
   ```ruby
   def change
     create_join_table :shiny_apps, :users
   end
   ```

   ```ruby
   def change
     create_join_table :shiny_apps, :shiny_users
   end
   ```

6. You will encounter the following error:
   ```
   SQLite3::SQLException: table "shiny_apps_users" already exists
   ```

**Expected Behavior:**

The `create_join_table` command should create a table named `shiny_apps_shiny_users` when used with `:shiny_apps` and `:shiny_users`.

**Actual Behavior:**

The command is attempting to create a table named `shiny_apps_users`, resulting in a table name conflict.

**Possible Fix:**

To resolve this issue, consider updating the `create_join_table` command in the migration file to explicitly specify the desired table name:
```ruby
def change
  create_join_table :shiny_apps, :shiny_users, table_name: :shiny_apps_shiny_users
end
```

This will ensure that the correct table name is used.

**Comment by rafaelfranca** [comment]
Thank you for the issue. That is the expected behavior. It matches the prefix and reuse it instead of repeating. If you want it to repeat the prefix, the `create_join_table :shiny_apps, :shiny_users, table_name: :shiny_apps_shiny_users` call is the correct way to do it.

**Comment by jubilee2** [comment]
Thank you
