### ISSUE TITLE
Unnecessary dependency on webpack in @rails/actiontext 7.1 

### ISSUE THREAD

**Issue by erikaxel** [rails/rails#49496]
Hi,

https://github.com/rails/rails/pull/47679 introduced webpack as a dependency for @rails/actiontext 7.1 in https://github.com/rails/rails/blob/v7.1.0/actiontext/package.json

We are not using webpack to bundle our javascript and this change draws in around 350 extra packages on our system.
Is it possible to remove this dependency? I don't see a specific reason why it would needed to be included, but I might be wrong. @smridge do you perhaps remember why it was added?

### System configuration
**Rails version**: 7.1

**Ruby version**: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin23]

**Comment by krsyoung** [comment]
For anybody else who is landing here because of `yarn audit` failing, once a new `@rails/actiontext` NPM package is pushed it will be fixed (the `webpack` dependency pulls in a vulnerable package `glob-parent`).

Also worth checking your `package.json` file and ensuring you're within minor versions (if you haven't already moved to 7.1). If that is the case, then moving back to `7.0.8` solves the issue.

The specific CVE is:

```
yarn audit v1.22.19
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ glob-parent before 5.1.2 vulnerable to Regular Expression    │
│               │ Denial of Service in enclosure regex                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ glob-parent                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=5.1.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @rails/actiontext                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @rails/actiontext > webpack > watchpack >                    │
│               │ watchpack-chokidar2 > chokidar > glob-parent                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1091181                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

❤️ here for the quick reporting and resolution!
