### ISSUE TITLE
Undocumented breaking change for @rails/ujs

### ISSUE THREAD

**Issue by Earlopain** [rails/rails#49499]
During the upgrade from 7.0 to 7.1 I had to change how @rails/ujs is getting initialized from

```js
import Rails from "@rails/ujs"
Rails.start()
```

to

```js
import "@rails/ujs";
```

The explicit import seems to now have side-effects as it complains about ujs already being initialized.
![image](https://github.com/rails/rails/assets/14981592/0cefbc8b-4314-405d-9100-c002f0b5b746)

https://github.com/rails/rails/tree/main/actionview/app/javascript suggests that the previous usage is still correct.

I'm using esbuild to bundle my js, specifically with this command:
`esbuild app/typescript/*.* --target=es2022 --bundle --sourcemap --outdir=./public/build`

Is this a bug with my setup or in ujs itself?

### System configuration
**Rails version**: 7.1

**Ruby version**: 3.2.2

**Comment by Earlopain** [comment]
It seems this check behaves differently in esm. https://github.com/rails/rails/blob/2d271a4b901e7a7dae8ba4e5e83edfebdee278e8/actionview/app/javascript/rails-ujs/index.js#L152C68-L152C68

**Comment by skipkayhil** [comment]
Yeah I agree with @Earlopain, I think `start()` is only expected to be called automatically if using Sprockets (or at least that was the intention of the if statement linked above

**Comment by mguan2020** [comment]
Hello @Earlopain @rafaelfranca @skipkayhil,

I am a beginner to open-source and would like to work on this issue. I have basic programming knowledge in Ruby. 

Could you please guide me on how to proceed with this? I have carefully read through the Contributing to Ruby on Rails guide posted in the Readme.

Thank you very much.

**Comment by Earlopain** [comment]
@mguan2020 I have no connection to the Rails project, I just opened this issue. As skipkayhil said, feel free to give this a shot yourself. Though with the mention of wanting to work on it themselves there is a risk of being beaten to the punch, just keep that in mind

**Comment by mguan2020** [comment]
Thank you for the reply.
