### ISSUE TITLE
Indicate in the changelog/release notes for 7.1, that `Rails.logger` is now a `BroadcastLogger`

### ISSUE THREAD

**Issue by mensfeld** [rails/rails#49494]
Following on my discussion with @rafaelfranca:

My gem [karafka](https://github.com/karafka/karafka) integrates with the Rails logger via a Railtie using the "unofficial" broadcast  API as follows:

https://github.com/karafka/karafka/blob/b32be801a9a81853d81bbe249a76388acfd5876b/lib/karafka/railtie.rb#L49

Rails 7.1 has replaced the `#broadcast` module with a `BroadcastLogger` and because of that I wanted to upgrade my integration. After reading the docs what I did was that (in railtie:

```ruby
rails_logger = Rails.logger

stdout_logger = ActiveSupport::Logger.new($stdout)
stdout_logger.level = Rails.logger.level

Rails.logger = ActiveSupport::BroadcastLogger.new(
  rails_logger,
  stdout_logger
)
```
basically wrapping the native Rails logger and my logger with a broadcast and using this as a Rails logger.

While it worked for my case, it caused following issue for any ActiveJobs:

```
/gems/3.1.0/gems/activejob-7.1.0/lib/active_job/logging.rb:32:in `logger_tagged_by_active_job?': undefined method `current_tags' for nil:NilClass (NoMethodError)

        logger.formatter.current_tags.include?("ActiveJob")
```

that is because BroadcastLogger is proxying only the logger API (which makes sense).

My approach was based on the docs as they did not clearly state that `Rails.logger` is now a broadcast logger itself with the extra APIs needed and that instead of wrapping it with a BroadcastLogger the upgrade path is to use a `broadcast_to` delegator on the Rails logger itself effectively replacing the above code with:

```ruby
stdout_logger = ActiveSupport::Logger.new($stdout)

Rails.logger.broadcast_to(stdout_logger)
```

it is not stated in the [release notes](https://edgeguides.rubyonrails.org/7_1_release_notes.html) or at least it was not exactly clear to me how to upgrade my integration to achieve the pre 7.1 behaviour without any errors.

**Comment by Edouard-chin** [comment]
Ah yeah that's true, I realise this could have been clearer.

Feel free to assign me on the issue @rafaelfranca !

**Comment by mensfeld** [comment]
@Edouard-chin thank you :pray:
