### ISSUE TITLE
session cookies corrupted in production on Rails 7.1

### ISSUE THREAD

**Issue by sweetppro** [rails/rails#49508]
### Steps to reproduce
 in my `session_store.rb` I have
```
Rails.application.config.session_store :cookie_store, :key => '_myapp_session', :same_site => :strict
```

### Expected behavior
session cookie should be correctly set:
`_myapp_session`

### Actual behavior
session cookie is actually set with name:
`"[_myapp_session`

### System configuration
Rails 7.1
Ruby 3.2.2

**Comment by ghiculescu** [comment]
Seems to be the same issue as https://github.com/rails/rails/issues/49422. Any chance you're using passenger and rack 3?

**Comment by sweetppro** [comment]
Ah yes, this looks like the issue. It was late last night I posted this and didn’t search. I’ll keep an eye on the passenger repo for a potential fix
