### ISSUE TITLE
 `Could not find table` in CI even though `db:test:prepare` has been run

### ISSUE THREAD

**Issue by deanpcmad** [rails/rails#49500]
When creating a new Rails app with 7.1.0, which is setup to test in GitHub actions, it fails with a `Could not find table` error.

With 7.1.0.rc2, it works fine, so something has changed in the last few days.

An example app is here: https://github.com/deanpcmad/blogtest

Of which you can see the actions logs for [7.1.0](https://github.com/deanpcmad/blogtest/actions/runs/6420609711/job/17433065722) or for [7.1.0.rc2](https://github.com/deanpcmad/blogtest/actions/runs/6420698975/job/17433371320)

### System configuration
**Rails version**: 7.1.0

**Ruby version**: 3.2.2

**Comment by deanpcmad** [comment]
Having going back through the commits and testing against each ref, I've found that it's PR #49470 that has caused this

**Comment by rafaelfranca** [comment]
That is the correct behavior. The model doesn't have a table, so either you remove action text from the application, or you install its migration and run them.

**Comment by skipkayhil** [comment]
> This was a brand new Rails 7.1.0 app, which action text wasn't installed or activated though

https://github.com/deanpcmad/blogtest/blob/62f67c3c773f27886cef80843ecee078d6c71603/config/application.rb#L3

`rails/all` initializes all of the Rails frameworks

**Comment by deanpcmad** [comment]
After setting the following in `config/application.rb`, tests now pass:

```
require "active_record/railtie"
# require "active_storage/engine"
require "action_controller/railtie"
require "action_view/railtie"
require "action_mailer/railtie"
require "active_job/railtie"
require "action_cable/engine"
# require "action_mailbox/engine"
# require "action_text/engine"
require "rails/test_unit/railtie"
```

But you're right, it's not a good user experience. Especially for new users. I've wasted about 2 hours of work time trying to fix this as I thought it was an issue with CI :laughing:

**Comment by ghiculescu** [comment]
Reopening as I don't think this is a good first run experience, but if it's the approach we are taking it should be in the getting started guide.

**Comment by ghiculescu** [comment]
Thoughts on this? https://github.com/rails/rails/pull/49509

**Comment by rafaelfranca** [comment]
This is intended behavior. Again, if you don't want action text, remove it. If you want it, run the task. I'm ok with us running the task automatically, but I don't think we should avoid checking if those tables exists or not.

**Comment by rafaelfranca** [comment]
Fixed!

**Comment by deanpcmad** [comment]
Excellent, thanks for all you do, Rafael!

**Comment by ghiculescu** [comment]
Thanks for the fix.

**Comment by excid3** [comment]
Ran into this as well in the 7.1.0 release. Will there be a bugfix release out soon with this @rafaelfranca?

**Comment by rafaelfranca** [comment]
Yes! Today.
