### ISSUE TITLE
Brand new Rails 7.1 repo with no tests pass locally but not on GitHub Action.

### ISSUE THREAD

**Issue by jasnow** [rails/rails#49514]
### Steps to reproduce

 1. Run "rails new oct10"
     * URL: https://github.com/jasnow/oct10 
 2. Copied .rvmrc from another repo to use 3.3.0-preview2 and Rails 7.1.
 3. Copied .github/workflows/rubyonrails.yml from another repo.
 4. Created "oct10" on GitHub and ran these commands:
    * git remote add origin git@github.com:jasnow/oct10.git
    * git branch -M main
    * git push -u origin main
 5. Ran "rake db:create:all db:migrate"
 6. Ran "rake" (no tests)
 7. Push code to GitHub and "test" action failed with this msg:
    * /home/runner/work/oct10/oct10/vendor/bundle/ruby/3.3.0+0/gems/activerecord-7.1.0/lib/active_record/connection_adapters/
       sqlite3_adapter.rb:458:in `table_structure': **Could not find  table 'action_text_rich_texts'** (ActiveRecord::StatementInvalid)

Will be glad to provide additional information as needed.

### Expected behavior

I expect the local and GitHub Action behavior to be the same.

**Not that Rails 7.1.0.rc2 did not have this problem.**

### Actual behavior

Local "rake" ran with no errors but GitHub Action "rake" failed.

### System configuration

Rails 7.1.0

Ruby 3.3.0-preview2

OS: Ubuntu

**Comment by fatkodima** [comment]
Was able to reproduce locally, investigating.

**Comment by jasnow** [comment]
This is a duplicate of #49500.

**Comment by fatkodima** [comment]
Fixed by https://github.com/rails/rails/commit/a731dbdfb8940b657946b8febcf7f56d7227beb0, which is already backported to `7-1-stable` branch. You need to use `branch: "7-1-stable"` in your Gemfile.

To reproduce locally, just run `CI=1 rake`.

**Comment by jasnow** [comment]
> Fixed by [a731dbd](https://github.com/rails/rails/commit/a731dbdfb8940b657946b8febcf7f56d7227beb0), which is already backported to `7-1-stable` branch. You need to use `branch: "7-1-stable"` in your Gemfile.
> 
> To reproduce locally, just run `CI=1 rake`.

Verfied the medigation worked.
