### ISSUE TITLE
Default cache format version still on 6.2

### ISSUE THREAD

**Issue by djfpaagman** [rails/rails#49543]
### Steps to reproduce

I'm working with a single file, simplified Rails app to test some stuff in the Rails codebase, and noticed that it gives a deprecation warning:

> DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.

```ruby
# frozen_string_literal: true
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '~> 7.1'
end

require 'rails/all'

Rails.logger = Logger.new(STDOUT)

class App < Rails::Application
  config.root = __dir__
  config.consider_all_requests_local = true
  config.secret_key_base = 'i_am_a_secret'
  config.active_storage.service_configurations = { 'local' => { 'service' => 'Disk', 'root' => './storage' } }
  config.eager_load = false

  routes.append do
    root to: 'welcome#index'
  end
end

class WelcomeController < ActionController::Base
  def index
    render inline: 'Hi!'
  end
end

App.initialize!

run App
```

Boot the app, the deprecation warning is printed on boot:

```sh
rackup app.ru
```

> DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.
>
> Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more information on how to upgrade.
 (called from load at /Users/dennis/.asdf/installs/ruby/3.2.1/bin/rackup:25)
[2023-10-08 20:10:50] INFO  WEBrick 1.8.1
[2023-10-08 20:10:50] INFO  ruby 3.2.1 (2023-02-08) [arm64-darwin22]
[2023-10-08 20:10:50] INFO  WEBrick::HTTPServer#start: pid=45700 port=9292

### Expected behavior
No deprecation warnings.

### Actual behavior
Deprecation warnings.

### System configuration
- **Rails version**: 7.1
- **Ruby version**: 3.2.1

---

I think this is because these variables still need to be bumped:

https://github.com/rails/rails/blob/f20643d4b903e3b57b905fdb19479cccb42a220f/activesupport/lib/active_support/cache.rb#L55
https://github.com/rails/rails/blob/f20643d4b903e3b57b905fdb19479cccb42a220f/activerecord/lib/active_record/marshalling.rb#L5

Not sure what the correct way to bump these is, can they just be bumped to `7.1` or will that break things? Happy to create a PR to do whatever makes most sense.

**Comment by ghiculescu** [comment]
Typically they'd get set via `load_defaults` ([here](https://github.com/rails/rails/blob/2533044859d4f689386f6af3b353946ee557bb1a/railties/lib/rails/application/configuration.rb#L242) or [here](https://github.com/rails/rails/blob/2533044859d4f689386f6af3b353946ee557bb1a/railties/lib/rails/application/configuration.rb#L313)), or [you would set them explicitly](https://github.com/rails/rails/blob/f705603d234478321353068e9ab3f9e8a5187ec6/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults_7_1.rb.tt#L181-L190).

If you set this config in your single file app, does the warning go away?

When the deprecated code gets removed, the initial values in the codebase will get updated too.

**Comment by zzak** [comment]
We cannot change this value and the caches are intended to be backwards compatible, see #42025.

**Comment by rafaelfranca** [comment]
It is because the config in `config.active_support.cache_format_version` is applied after you called `ActiveSupport::Cache::RedisCacheStore.new`. It is only applied when this initializer is run https://github.com/rails/rails/blob/2d49514fe20b8084ba75f1077364cbb0951c9b48/railties/lib/rails/application/bootstrap.rb#L71

And the `config/environments` files are executed before that config is applied, so you `config.cache_store = ActiveSupport::Cache::RedisCacheStore.new` is actually executed before.

if you need to call `new` in the cache storage you also need to set `ActiveSupport::Cache.format_version` explicitly.

**Comment by Frexuz** [comment]
I'm seeing the same, with `config.cache_store = :memory_store` (development) and `config.load_defaults 7.1`
