### ISSUE TITLE
Cannot create records with composite primary key containing `id` column in Rails 7.1

### ISSUE THREAD

**Issue by janko** [rails/rails#49541]
### Steps to reproduce

This example table comes from Rodauth:

```rb
require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.connection.create_table :recovery_codes, primary_key: [:id, :code] do |t|
  t.integer :id
  t.string :code
end

class RecoveryCode < ActiveRecord::Base
end

RecoveryCode.create(id: 1, code: "foo")
```

### Expected behavior

I expected the record to be successfully created, since the `id` column is just like any other column.

### Actual behavior

I get an error:

```
/Users/janko/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/attribute_methods/primary_key.rb:36:in `id=': Expected value matching ["id", "code"], got 1. (TypeError)

          raise TypeError, "Expected value matching #{self.class.primary_key.inspect}, got #{value.inspect}." unless value.is_a?(Enumerable)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /Users/janko/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activemodel-7.1.0/lib/active_model/attribute_assignment.rb:49:in `public_send'
        from /Users/janko/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activemodel-7.1.0/lib/active_model/attribute_assignment.rb:49:in `_assign_attribute'
        from /Users/janko/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/attribute_assignment.rb:19:in `block in _assign_attributes'
        from /Users/janko/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/attribute_assignment.rb:11:in `each'
        from /Users/janko/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/attribute_assignment.rb:11:in `_assign_attributes'
        from /Users/janko/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activemodel-7.1.0/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
        from /Users/janko/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/core.rb:431:in `initialize'
        from /Users/janko/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/inheritance.rb:76:in `new'
        from /Users/janko/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/inheritance.rb:76:in `new'
        from /Users/janko/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/persistence.rb:37:in `create'
```

If I rename the `id` column to something else (e.g. `account_id`), then it works. IMO Active Record should not be treating the `id` column in any special way, it's just a column like any other, it should only be concerned what column is the primary key. But I see the `#id=` method being overridden with special behavior in Active Record.

### System configuration
**Rails version**: 7.1.0

**Ruby version**: 3.2.2

**Comment by nvasilevski** [comment]
>IMO Active Record should not be treating the id column in any special way

Perhaps, but that's what we have in Rails and composite primary keys must be following the concept of `ID` serving as an identifier and not the `id` column value (except for methods that do accept raw column names like `find_by` or `where()`)

The problem is not specific to composite primary keys but most likely models with composite PKs will be inconvenienced the most. Consider a regular single-column PK example:

```ruby
ActiveRecord::Schema.define do
  create_table :topics, force: true, id: false do |t|
    t.string :title, primary_key: true
    t.integer :id
  end
end

class Topic < ActiveRecord::Base
end

Topic.create(id: "I will be the title and not the ID")
#<Topic title: "I will be the title and not the ID", id: nil>
```

Here it's also impossible to properly access/write the `id` column. So as long as Rails treats `id` term as "an identifier" the composite primary keys logic must follow. 

Rails used to say that non-PK `id` columns are not supported
https://github.com/rails/rails/blob/0bddf3513b387939e09eb597248f797f0e88d0d5/guides/source/active_record_basics.md#L215

With the introduction of the composite primary keys the guidance changes to avoid using `id` as anything other than a single column PK
https://github.com/rails/rails/blob/a4d5f1d7399a1eb4823a91a6493f0f02f60994ae/guides/source/active_record_basics.md#L215-L219

And use `id_value` accessor in case if we end up working with such db schema where `id` column is not a single-column PK

**Comment by janko** [comment]
Thank you for the tip about `id_value` attribute, I didn't know about it, it works when I use it 👍🏻 

```rb
RecoveryCode.create(id_value: 1, code: "foo")
```

**Comment by nvasilevski** [comment]
>Has this attribute been identified as something that would be good to eventually remove

Not yet but I definitely heard opinions that perhaps having smart behavior (pk value) for `id` term wasn't the most suitable choice. However considering how long this behavior existed I can imagine it's going to be painful to deprecate and remove it even in a major release. I can imagine many existing libraries, applications and Rails itself rely on the existing behavior and find it convenient compared to a more verbose option like `record.primary_key_value` or `record.identifier` 

Personally I'd be comfortable with either as long as it serves the most of the real world applications in the community

**Comment by Martin-Alexander** [comment]
One use case for composite primary keys containing `id` (or just non-primary `id` columns) is temporal tables where you'll have a matching history table wherein multiple rows can represent different versions of a single business entity at different points in time.

Consider something like this that represents an employee being created with a salary of 100 on Sep 5th, updated to 200 on Sep 7th, and deleted on Sep 8th. The primary key would be a composite including `id` and `lower(sys_period)` or there could be an auto-incrementing `history_id` column in the history table.

id | salary | sys_period
-- | -- | --
1 | 100 | [Sep 5th, Sep 7th)
1 | 200 | [Sep 7th, Sep 8th)

You could rename `id` in the temporal table (i.e., the current table). But if you're converting an existing table to a temporal table this could be a pain. Or you could have your history table use `_id` instead, but again, could be a pain.

**Comment by Martin-Alexander** [comment]
Considering that non-primary `id` columns were explicitly not supported for such a long time and are even now discouraged, would it be acceptable to make `#id` return the primary key value _only if_ there isn't a non-primary `id` column? That way everyone following Active Record's recommendations would be unaffected.

```ruby
ActiveRecord::Schema.define do
  create_table :foo

  create_table :bar, id: false do |t|
    t.string :title
  end

  create_table :baz, primary_key: biz_id

  create_table :boo, primary_key: biz_id do |t|
    t.integer :id
  end
end

# Behaviour unchanged
foo = Foo.create # => #<Foo id: 1> 
foo.id # => 1

# Behaviour unchanged
bar = Bar.create(title: "bar") # => #<Bar title: "bar"> 
bar.id # => nil

# Behaviour unchanged
baz = Baz.create # => #<Baz biz_id: 1> 
baz.id # => 1

# Behaviour changed
boo = Boo.create(id: 100) # => #<Boo biz_id: 1, id: 100> 
boo.id # => 100
boo.primary_key_value # => 1
```
