### ISSUE TITLE
Rails 7.1 is breaking mongoid dependency...

### ISSUE THREAD

**Issue by fedorzajac** [rails/rails#49550]
### Steps to reproduce

updating rails from 7.0.8 to 7.1

```ruby
# Your reproduction script goes here
bundle update
bundle update
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using rack 3.0.8 (was 2.2.8)
Using activesupport 7.1.0 (was 7.0.8)
Using activemodel 7.1.0 (was 7.0.8)
Using mongoid 1.0.6 (was 8.1.2) # <----------------
Using activejob 7.1.0 (was 7.0.8)
Using activerecord 7.1.0 (was 7.0.8)
Using actionview 7.1.0 (was 7.0.8)
Using actionpack 7.1.0 (was 7.0.8)
Using actioncable 7.1.0 (was 7.0.8)
Using actionmailer 7.1.0 (was 7.0.8)
Using activestorage 7.1.0 (was 7.0.8)
Using railties 7.1.0 (was 7.0.8)
Using actionmailbox 7.1.0 (was 7.0.8)
Using actiontext 7.1.0 (was 7.0.8)
Using rails 7.1.0 (was 7.0.8) # <-------------
Bundle updated!
```

### Expected behavior

do not downgrade mongoid

### Actual behavior

mongoid was downgraded and my models break.

### System configuration
**Rails version**:
7.0.8

**Ruby version**:
ruby -v      
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [arm64-darwin22]

**Comment by zzak** [comment]
Hello!

That is the behavior of bundler if you don't pin a dependency and run `bundle update`, there is nothing Rails can do about this.

I think this is kind of covered here:
https://guides.rubygems.org/patterns/#pessimistic-version-constraint

Going to close this as there is not anything actionable for us, please feel free to re-open if there is additional information.
Thanks!

**Comment by fedorzajac** [comment]
@zzak thank you for explanation, however i reached dependency error when specifying mongoid version...
```Gemfile
...
ruby '>= 3.0.0'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
# gem 'psych', '~> 4.0'
gem 'rails', '~> 7.1'
# gem 'rubocop'

gem 'mongoid', '~> 8'
...
```

```bash
undle update
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Could not find compatible versions

Because mongoid >= 7.3.4 depends on activemodel >= 5.1, < 7.1, != 7.0.0
  and rails >= 7.1.0 depends on activemodel = 7.1.0,
  mongoid >= 7.3.4 is incompatible with rails >= 7.1.0.
So, because Gemfile depends on rails ~> 7.1
  and Gemfile depends on mongoid ~> 8,
  version solving has failed.
```

**Comment by adrienpoly** [comment]
@fedorzajac nothing Rails can do here this is a Mongo issue 

will be fixed once this is merged and a new version released

https://github.com/mongodb/mongoid/pull/5728

**Comment by fedorzajac** [comment]
@adrienpoly ok, thank you very much!
