### ISSUE TITLE
The Postgres adapter's "table name too long" error message is confusing

### ISSUE THREAD

**Issue by adampal** [rails/rails#49557]
The PR #45136 enforces a maximum table name length when creating tables.

The error message is:
`Table name '#{table_name}' is too long; the limit is #{table_name_length} characters`

The issue is `table_name_length` for Postgres returns 58 characters. All the Postgres docs show a max table length of 63 characters. The reason it's different is that we're reducing it by 5 characters to allow for `_pkey` suffix Postgres adds.

I encountered the error when upgrading an app to Rails 7.1 and it wasn't immediately obvious to me why my table name that was 60 characters long should be an issue.  I had to check the Rails source code to find out why it wasn't working.

My suggestion is to add something to the error message to save people having to dig through the Rails code to figure out why the max allowed by Rails is less than the max allowed by Postgres.

I'm happy to submit a PR if it's something the core team are happy to add.

**Comment by ghiculescu** [comment]
A PR to make an error message more useful is always 👍

**Comment by adampal** [comment]
Thanks @ghiculescu I'll open a PR
