### ISSUE TITLE
Rails Guides search functionality

### ISSUE THREAD

**Issue by akirataguchi115** [rails/rails#49561]
Ruby on Rails Guides (https://guides.rubyonrails.org/) could use a search functionality just like Ruby on Rails API has (https://api.rubyonrails.org/).

**Comment by vipulnsward** [comment]
Thanks for reporting, there have been several attempts at it, but no good solution yet- https://github.com/rails/rails/pull/39299

Is should be available when there is consensus on a good solution.

**Comment by akirataguchi115** [comment]
Thanks for finding the duplicate!
