### ISSUE TITLE
_uses_legacy_table_name ignored for DB Table name on Schema Load

### ISSUE THREAD

**Issue by ElliottAYoung** [rails/rails#49567]
### Steps to reproduce
A Migration with a legacy database table name that is too long, for example (tested specifically on Postgres):

```ruby
class SomeMigration < ActiveRecord[7.0]
    create_table :some_table_name_that_is_too_long_for_the_database_to_handle do |t|
      ...
    end
end
```

Will run successfully and the database table will be created. At any point forward if I run `bundle exec rake db:schema:load` I get the following error message:

```
ArgumentError: Table name 'some_table_name_that_is_too_long_for_the_database_to_handle' is too long; the limit is 58 characters
```

### Expected behavior
If a database table is generated and flagged as a legacy override for the length validation this should persist to future schema loads instead of raising an error.

### Actual behavior
Despite being disabled for the `create_table` method in the migration, any tables with names that are too long are unable to be created when loading the DB schema with `bundle exec rake db:schema:load`

### System configuration
**Rails version**:
7.1.0

**Ruby version**:
3.1.2

**Comment by fatkodima** [comment]
You should not use `_uses_legacy_table_name` manually, it is used by rails internally. It was added in https://github.com/rails/rails/pull/45136.

You should preserve the old migration version, like `< ActiveRecord::Migration[7.0]`. Can you try if that works?

**Comment by fatkodima** [comment]
You need to change to `ActiveRecord::Schema[7.0].define` in `schema.rb` or to rename the table to shorter name. Do not know of a better solution.

**Comment by paulreece** [comment]
@ElliottAYoung as @fatkodima said you need to change your schema definition to not get this error to flag for the time being.

To give more context if you have your test code set like this:
```Ruby
class SomeMigration < ActiveRecord::Migration[4.2]
    create_table :some_table_name_that_is_too_long_for_the_database_to_handle do |t|
      ...
    end
end
``` 
It will allow you to create the legacy table but will still raise an `ArgumentError`.
But if you change your `schema.rb` as noted above it will no longer raise this.

And for those curious, if you're trying to create a table name that's too long with a 7.1 migration it will give you an argument error when you try to migrate and create the table in the first place.

```Ruby
 rails db:migrate
...
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Caused by:
ArgumentError: Table name 'some_table_name_that_is_too_long_for_the_database_to_handles' is too long; the limit is 58 characters
```
I think a maintainer will need to jump in about how to handle this `ArgumentError` with legacy tables.  I have a feeling they'll suggest renaming the table to something shorter.

**Comment by rafaelfranca** [comment]
I don't think Rails should force people to rename tables if they work just fine for the database.

I'm ok with we raising an error for new tables, but the schema.rb should continue to work with tables names that are big.

People can't keep `ActiveRecord::Schema[7.0].define` being used since the next schema dump will bump the version (it was never intended to the schema to not be in the current version of Rails), so it seems the schema version of `create_table` should not enforce table name size.

**Comment by fatkodima** [comment]
> I think rename table for postgreSQL should just get the name of the index from the database and rename it?

I think we can try this. So then we should also remove all the added length checking code?

**Comment by rafaelfranca** [comment]
Don't think so. Having it truncated by postgresql is also strange, but at least we can increase the limit to 63, instead of 58.

**Comment by fatkodima** [comment]
Ok, thanks, will look into this.
