### ISSUE TITLE
GitHub Projects are empty

### ISSUE THREAD

**Issue by akirataguchi115** [rails/rails#49578]
![image](https://github.com/rails/rails/assets/31825085/23991c8c-5196-4912-98b1-00faf0da9a5f)
Projects look like this right now. Should we close them?

**Comment by eileencodes** [comment]
We were going to use them but never got around to setting up proper automation. In the future please make suggestions like this on the forum and not the issues tracker. We reserve the issues tracker for bugs in the framework only.
