### ISSUE TITLE
Active Record join class is unable to infer value for `belongs_to ..., inverse_of:`

### ISSUE THREAD

**Issue by seanpdoyle** [rails/rails#49574]
### Steps to reproduce

An Active Record join model accessed through a `has_many ..., through:` association is unable to infer its `inverse_of:` association by pluralizing a predictably pluralizable class name.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table "listings", force: :cascade do |t|
    t.bigint "list_id", null: false
    t.bigint "pin_id", null: false
  end

  create_table "lists", force: :cascade do |t|
  end

  create_table "pins", force: :cascade do |t|
  end
end

class Pin < ActiveRecord::Base
  has_many :listings
end

class List < ActiveRecord::Base
  has_many :listings
  has_many :pins, through: :listings
end

class Listing < ActiveRecord::Base
  belongs_to :list
  belongs_to :pin
end

class BugTest < Minitest::Test
  def test_association_stuff
    list = List.create!
    pin = list.pins.new

    pin.save!

    assert_equal [pin], list.reload.pins
    assert_equal 1, list.reload.pins.count
  end
end
```

### Expected behavior

The call to `list.reload.pins` should include `pin`, and the `Listing.belongs_to :pin` association should be able to infer its inverse by pluralizing its class name to `:listings`.

### Actual behavior

```
Failure:
BugTest#test_association_stuff [bug.rb:64]:
--- expected
+++ actual
@@ -1 +1 @@
-[#<Pin id: 1, created_at: "2023-10-10 22:12:52.792230000 +0000", updated_at: "2023-10-10 22:12:52.792230000 +0000">]
+#<ActiveRecord::Associations::CollectionProxy []>

Failure:
BugTest#test_association_stuff [bug.rb:64]:
Expected: 1
  Actual: 0
```

When declared as `Listing.belongs_to :pin, inverse_of :listings`, the tests pass.

```diff
diff --git a/activerecord/bug.rb b/activerecord/bug.rb
index ffd9d384e0..16974dc6df 100644
--- a/activerecord/bug.rb
+++ b/activerecord/bug.rb
@@ -51,7 +51,7 @@ class List < ActiveRecord::Base
 
 class Listing < ActiveRecord::Base
   belongs_to :list
-  belongs_to :pin
+  belongs_to :pin, inverse_of: :listings
 end
 
 class BugTest < Minitest::Test
```

### System configuration

**Rails version**:

`activerecord` at `main@c8149e6`

**Ruby version**:

```
❯ ruby -v
ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22]
```

**Comment by akhilgkrishnan** [comment]
Seems like there is record added to `listings` table when creating an associated record for `pins` in `lists` table.

**Comment by composerinteralia** [comment]
If I recall correctly, Rails doesn't have automatic inversing for `belongs_to` associations because most of the time it's not needed. This is the rare case where it is needed, and there is a bit of documentation saying you need an explicit `inverse_of`: https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#module-ActiveRecord::Associations::ClassMethods-label-Setting+Inverses. I agree with you that this is not ideal, but since it's documented weirdness it's probably not officially a bug.

**Comment by seanpdoyle** [comment]
@composerinteralia thank you for pointing me to that documentation!

I hoped that the relationship inference would still work, since the relationship names are conventional:

> If you do not set the `:inverse_of` record, the association will do its best to match itself up with the correct inverse.

I'm happy to explore improvements to the inference in this situation. Are you familiar enough with the parts of Active Record that handle the inflections and inference? Could you point me in the right direction?

**Comment by composerinteralia** [comment]
Automatic inversing starts around here: https://github.com/rails/rails/blob/bd17a7efb3852427b62c47179c995a4135796bf5/activerecord/lib/active_record/reflection.rb#L708 I have looked at this code before, and I'd be happy to pair on whatever. I don't remember if anybody has tried automatic inverses from a `belongs_to` to the `has_many`. There have been various attempts at inferring inverses for more cases (e.g. when there is a custom foreign key that matches the inverse), but everything I can remember was in the opposite direction, from the `has_many` to the `belongs_to`.
