### ISSUE TITLE
Rails 7.1 breaks assets compilation (Terser::Error: "extend" is redeclared)

### ISSUE THREAD

**Issue by ArturT** [rails/rails#49599]
### Steps to reproduce

Rails 7.1 breaks assets compilation (Terser::Error: "extend" is redeclared)

I updated Rails 7.0.8 to Rails 7.1.1.

I use the terser 1.1.18 gem.

```ruby
# config/environments/production.rb
config.assets.js_compressor = :terser
```

When I deploy the Rails app to Heroku I'm getting the following error for the assets compilation step.

https://eslint.org/docs/latest/rules/no-redeclare

```
...
remote:        rake aborted!
remote:        Terser::Error: "extend" is redeclared
remote:        --
remote:         44142   }
remote:         44143
remote:         44144 };
remote:         44145
remote:         44146 const ZERO_WIDTH_SPACE = "\uFEFF";
remote:         44147 const NON_BREAKING_SPACE = "\u00A0";
remote:         44148 const OBJECT_REPLACEMENT_CHARACTER = "\uFFFC";
remote:         44149
remote:            => const extend = function (properties) {
remote:         44151   for (const key in properties) {
remote:         44152     const value = properties[key];
remote:         44153     this[key] = value;
remote:         44154   }
remote:         44155
remote:         44156   return this;
remote:         44157 };
remote:         44158
remote:        ==
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/terser-1.1.18/lib/terser.rb:284:in `parse_result'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/terser-1.1.18/lib/terser.rb:228:in `run_terserjs'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/terser-1.1.18/lib/terser.rb:180:in `compile_with_map'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/terser-1.1.18/lib/terser/compressor.rb:36:in `call'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/terser-1.1.18/lib/terser/compressor.rb:23:in `call'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:84:in `call_processor'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `reverse_each'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `call_processors'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:184:in `load_from_unloaded'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:59:in `block in load'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:43:in `load'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `block in load'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `load'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/base.rb:81:in `find_asset'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/base.rb:88:in `find_all_linked_assets'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/manifest.rb:125:in `each'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/manifest.rb:125:in `to_a'
remote:        /tmp/build_6cc64a5b/vendor/bundle/ruby/3.2.0/gems/sprockets-4.2.1/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
...
```

I suspect the issue is related to actioncable but I could not find the exact line of code that is failing.
There are a few similar lines, for example `rails/actioncable/app/assets/javascripts/actioncable.js`:
https://github.com/search?q=repo%3Arails%2Frails++const+extend+%3D+function+%28properties%29+%7B&type=code

When I run `bundle exec rake assets:precompile` in development then there is no error.

I'd appreciate your help. I'm not sure if this is the issue with Rails or maybe it's our Heroku environment issue. Thank you.

### Expected behavior

Assets compilation should be successful.

### Actual behavior

Assets compilation is failing during Heroku deployment.

### System configuration

**Rails version**: 7.1.1 (also the same issue on Rails 7.1.0)

**Ruby version**: 3.2.2

**terser version**: 1.1.18

**Comment by rafaelfranca** [comment]
Thank you for the issue. Can you see if this PR fix the problem? https://github.com/rails/rails/pull/49615

**Comment by ArturT** [comment]
@rafaelfranca Thank you for looking into it.

I use the following code in Gemfile:

```
gem 'rails', github: 'rails/rails', ref: 'eb1e91ebb7bec7c634424b7597226a970ab4e498'
```

During Heroku deployment I'm still getting the error:

```
...
remote:        rake aborted!
remote:        Terser::Error: "extend" is redeclared
remote:        --
remote:         44142   }
remote:         44143
remote:         44144 };
remote:         44145
remote:         44146 const ZERO_WIDTH_SPACE = "\uFEFF";
remote:         44147 const NON_BREAKING_SPACE = "\u00A0";
remote:         44148 const OBJECT_REPLACEMENT_CHARACTER = "\uFFFC";
remote:         44149
remote:            => const extend = function (properties) {
remote:         44151   for (const key in properties) {
remote:         44152     const value = properties[key];
remote:         44153     this[key] = value;
remote:         44154   }
remote:         44155
remote:         44156   return this;
remote:         44157 };
remote:         44158
remote:        ==
remote:        /tmp/build_dbfeebda/vendor/bundle/ruby/3.2.0/gems/terser-1.1.18/lib/terser.rb:284:in `parse_result'
remote:        /tmp/build_dbfeebda/vendor/bundle/ruby/3.2.0/gems/terser-1.1.18/lib/terser.rb:228:in `run_terserjs'
remote:        /tmp/build_dbfeebda/vendor/bundle/ruby/3.2.0/gems/terser-1.1.18/lib/terser.rb:180:in `compile_with_map'
...
```

**Comment by rafaelfranca** [comment]
It could be another library not from Rails. I just want to make sure the problem is on Trix

**Comment by ArturT** [comment]
I added

```
# config/environments/development.rb
config.assets.js_compressor = :terser
```

and executed locally `bundle exec rake assets:precompile` to get the error. But I'm not sure how to narrow down the file that is causing the issue because the error message does not include the path to the problematic file.

I tried to remove all required files from `app/assets/javascripts/application.js` but I'm still getting the error.

**Comment by rafaelfranca** [comment]
If you don't add `config.assets.js_compressor = :terser` you can generate an unminified, but concatenated file which would need to have two or more `const extend` definitions, and we could use the code around them to know where they are defined.

**Comment by ArturT** [comment]
I pry into the source code of terser and it looks like the error is coming from the `rails_admin` gem.

```
From: /Users/artur/.rvm/gems/ruby-3.2.2/gems/terser-1.1.18/lib/terser.rb:285 Terser#parse_result:

    283: def parse_result(result, generate_map, options, source_map_options = {})
    284:   require 'pry'; binding.pry
 => 285:   raise Error, error_message(result, options) if result.has_key?('error')
    286:
    287:   if generate_map
    288:     [result['code'] + source_map_comments(source_map_options), result['map']]
    289:   else
    290:     result['code'] + source_map_comments(source_map_options)
    291:   end
    292: end

[1] pry(#<Terser>)> result
=> {"error"=>
  {"message"=>"\"extend\" is redeclared",
   "filename"=>"/Users/artur/.rvm/gems/ruby-3.2.2/gems/rails_admin-3.1.2/app/assets/javascripts/rails_admin/application.js.erb",
   "line"=>44150,
   "col"=>6,
   "pos"=>1295653}}
```

**Comment by ArturT** [comment]
> If you don't add `config.assets.js_compressor = :terser` you can generate an unminified, but concatenated file which would need to have two or more `const extend` definitions, and we could use the code around them to know where they are defined.

I found the problematic lines:

```
➜   ag 'const extend = function \(properties\) {' public

public/assets/trix-9d726c63bf503ba68adf3d1bea343c030494f01061abf524a4e743f686629201.js
275:const extend = function (properties) {

public/assets/rails_admin/application-07b4e001f7c1929ae33ff81fff381a581b8c141c720aa062059421219bfe3d89.js
44150:const extend = function (properties) {
```

**Comment by ArturT** [comment]
Trix has this line:

```
export const extend = function(properties) {
```

https://github.com/basecamp/trix/blob/5ebe789bdb8d5aca97847c7a324b8b841ee68c08/src/trix/core/helpers/extend.js#L1

Maybe rails_admin gem needs to update the trix version?
https://github.com/railsadminteam/rails_admin/blob/0e12e5b465997c14d5b7a4d500a0d4cebed21aa9/app/assets/javascripts/rails_admin/application.js.erb#L28
But it looks like they use CDN to load trix https://github.com/railsadminteam/rails_admin/blob/0e12e5b465997c14d5b7a4d500a0d4cebed21aa9/lib/rails_admin/config/fields/types/action_text.rb#L14

I'm not sure if this is a problem with the version of trix that is used by rails_admin or something else.
https://github.com/search?q=repo%3Arailsadminteam%2Frails_admin%20trix&type=code

Or maybe I'm doing something wrong to try your patch. Maybe the following code is not enough to test the fix?

```ruby
gem 'rails', github: 'rails/rails', ref: 'eb1e91ebb7bec7c634424b7597226a970ab4e498'
```

**Comment by rafaelfranca** [comment]
Amazing! Thanks. I think we need to fix trix. I'll take a look on doing that.

Yes. I think you are doing the right thing to point to the commit, but the problem is that both trix included in Rails and the one included in rails_admin are defining the same constant. Trix should not be exposing a global constant. It works fine when se use `imports`, but not in the assets pipeline.

**Comment by skipkayhil** [comment]
I opened a PR above to fix Trix, @ArturT could you see if that commit fixes the issue for you?

**Comment by MrSerth** [comment]
I have the same issue as @ArturT and can confirm that PR #49778 fixes the issue for me.

**Comment by ArturT** [comment]
I tried #49778 

```ruby
gem 'rails', github: 'skipkayhil/rails', ref: 'c93a989635d01fa46947b2618a7dde2505c77410'
```

Assets compilation works now. I was able to deploy the Rails app to Heroku.

But there is a new error in the rails_admin gem related to Active Storage and Turbo.

![e1](https://github.com/rails/rails/assets/662545/b1da3946-1846-4d9d-b790-4818edf19cc8)

This is from Active Storage: 
https://github.com/rails/rails/blob/4c5c904a212a850c43adb7a3c3a719ca3d2b9159/activestorage/app/javascript/activestorage/ujs.js#L8
![e2](https://github.com/rails/rails/assets/662545/a3f4e759-b91e-4784-973a-f658dd74442d)

This one is from Turbo
https://github.com/rails/rails/blob/4c5c904a212a850c43adb7a3c3a719ca3d2b9159/guides/assets/javascripts/%40hotwired--turbo.js#L3913
![e3](https://github.com/rails/rails/assets/662545/a1ebd5e6-181d-46a4-a38a-8c5bb58d4d7d)

The above error prevents us to load custom js scripts for the rails_admin gem from `app/assets/javascripts/rails_admin/custom/ui.js`. Even when I remove our custom js scripts for the rails_admin gem then the error is still present.

**Comment by skipkayhil** [comment]
@ArturT could you share what your `application.js` file looks like? (at a minimum whichever combinatin of `//= require`s are causing the issue?)

Additionally:
- what library/version are you getting turbo.js from? (turbo-rails?)

It would surprise me if _just_ upgrading Rails from 7 to 7.1 would cause a new conflict between Active Storage and Turbo since the Active Storage code hasn't changed much from Rails 7, but if you upgrade `turbo-rails` as well then I could see the problem being there

**Comment by ArturT** [comment]
The rails_admin gem depends on `turbo-rails (~> 1.0)`:

```
    rails_admin (3.1.2)
      activemodel-serializers-xml (>= 1.0)
      kaminari (>= 0.14, < 2.0)
      nested_form (~> 0.3)
      rails (>= 6.0, < 8)
      turbo-rails (~> 1.0)
```

We use `turbo-rails (1.5.0)`:

```
    turbo-rails (1.5.0)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
```

Our `app/javascript/application.js` looks like:

```
// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails

// dependencies

import "jquery"
import "jquery_ujs"
import "bootstrap-sprockets"
import "chartkick"
import "Chart.bundle"

// https://github.com/hotwired/turbo-rails
import "@hotwired/turbo-rails"
// enable/disable Turbo Drive
window.Turbo.session.drive = false

// our scripts

import "general"
import "pages"
import "channels"
import "controllers"
```

I removed the content of both files `app/javascript/application.js` and `app/assets/javascripts/rails_admin/custom/ui.js` and I restarted the Rails app. I'm still seeing the issue in Chrome console (even in incognito).

I downgraded turbo-rails gem version to older versions 1.4.0 and 1.3.2 that we were using over the last year without issue and in both cases we still see the issue: `Uncaught ReferenceError: Cannot access 'started' before initialization`. So I suspect that Rails is somehow triggering the issue.

**Comment by skipkayhil** [comment]
Sorry, one more question, what javascript library are you using? (`webpacker`, `js-bundling` + `webpack`/`esbuild` etc.) I assumed you weren't using one since you were using terser but based on your `application.js` it seems like you are

**Comment by ArturT** [comment]
We use `importmap-rails` gem. I added it a few days ago. I will try without it. Previously we were using just assets pipeline with `terser` gem. We never used webpacker because our Rails app is old. We migrated it a few times from Rails 4 to 5, 6, 7 and recently to Rails 7.0.8. We were using Rails 7.0.8 with assets pipeline (without importmaps) for some times without an issue. 

Just recently I wanted to update it to Rails 7.1 but I could not due to this issue. In the mean time I added importmaps (just 2 days ago).

**Comment by ArturT** [comment]
I reverted the importmap changes and I'm still seeing the exception: `Uncaught ReferenceError: Cannot access 'started' before initialization`.

**Comment by ArturT** [comment]
* Rails 7.0.8, turbo-rails 1.5.0

Correct. And the latest rails_admin gem:

```
    rails_admin (3.1.2)
      activemodel-serializers-xml (>= 1.0)
      kaminari (>= 0.14, < 2.0)
      nested_form (~> 0.3)
      rails (>= 6.0, < 8)
      turbo-rails (~> 1.0)
```

* no javascript bundling or importmaps (just sprockets and terser)

```
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)

    sprockets (4.2.1)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)

    terser (1.1.19)
      execjs (>= 0.3.0, < 3)
```

I confirm for simplicity I will not use importmaps (just our old code) to narrow down the issue.

* What does application.js look like?

```
// app/assets/javascripts/application.js

// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
// or any plugin's vendor/assets/javascripts directory can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file.
//
// Read Sprockets README (https://github.com/rails/sprockets#sprockets-directives) for details
// about supported directives.
//
//= require jquery
//= require jquery_ujs
//= require bootstrap-sprockets
//= require chartkick
//= require Chart.bundle
//= require general/helpers
//= require general/bootstrap
//= require general/colors
//= require general/form_utils
//= require general/consent_required
//= require general/copy_to_clipboard
//= require general/nav-tabs
//= require pages/homepage
//= require pages/billing
//= require pages/builds
//= require pages/onboarding_project_form
//= require pages/faq
//= require pages/test_files_history
```

When I remove content of the `app/assets/javascripts/application.js` file then I still see the issue `Uncaught ReferenceError: Cannot access 'started' before initialization` while visiting `/admin` (rails admin panel).

I'll try to create a new Rails 7.1.1 app with your fix #49778 and the rails_admin gem to see if I can reproduce the problem.

**Comment by ArturT** [comment]
I managed to reproduce the issue on a new Rails 7 app. I installed the rails_admin gem with sprockets.
You can see step by step in git commit messages what I did.

https://github.com/ArturT/rails7-issue-49599/commits/master

**Comment by ArturT** [comment]
Do you think the error that I'm seeing in the rails_admin panel after using your fix for Rails is not related to Rails? If so then I can report that issue to the rails_admin repository.

```Ruby
# Gemfile
# merged https://github.com/rails/rails/pull/49778
gem 'rails', github: 'rails/rails', ref: 'e21ed11d569a31389ff9dad4d3692e736dbecd86'
```

**Comment by skipkayhil** [comment]
> Do you think the error that I'm seeing in the rails_admin panel after using your fix for Rails is not related to Rails?

Sorry, no, I just haven't had time to look into it yet. The linked PR fixed the original issue here, so let me open a new issue for the second problem

**Comment by ArturT** [comment]
Thanks.
