### ISSUE TITLE
Yarn used instead of Bun if Bun is not installed

### ISSUE THREAD

**Issue by TheAssailant** [rails/rails#49608]
### Steps to reproduce

Without bun installed on the system:

```bash
$ rails new test-app --javascript bun --css bootstrap
```

### Expected behavior
I feel the script should halt and let the user know that bun is not installed on their system, much like how it halts if it cannot install the pg gem.

### Actual behavior
Install script switches to using yarn instead of bun.

```
       apply  /Users/paul/.rvm/gems/ruby-3.2.2/gems/cssbundling-rails-1.3.3/lib/install/bootstrap/install.rb
  Install Bootstrap with Bootstrap Icons, Popperjs/core and Autoprefixer
      create    app/assets/stylesheets/application.bootstrap.scss
         run    yarn add sass bootstrap bootstrap-icons @popperjs/core postcss postcss-cli autoprefixer nodemon from "."
yarn add v1.22.18
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.22.19", while you're on "1.22.18".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
success Saved 94 new dependencies.
```

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

**Comment by paulreece** [comment]
Please see my comments at the bottom of #49522

@terracatta Any idea of how we should adress this?

**Comment by paulreece** [comment]
Reposting this here for ease of understanding:


I tested this a few times locally and it tries to use yarn every time:
```Python
 Add build:css script
  Add build:css script
         run    npm pkg set scripts.build:css="tailwindcss -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --minify" from "."
         run    yarn build:css from "."
Usage Error: The nearest package directory (/Users/ruby_test/test_seven) doesn't seem to be part of the project declared in /Users/.
```

I think it is possibly because the conditional here is explicitly checking for the [`bun.lockb`](https://github.com/rails/cssbundling-rails/blob/66635235a96909f688627789b40cc81795917f7f/lib/install/helpers.rb#L11) file but it doesn't seem to be getting created in the when creating the new app so it returns `false` every time and defaults to `yarn`:

```Ruby
  def using_bun?
    File.exist?('bun.lockb') || (tool_exists?('bun') && !File.exist?('yarn.lock'))
  end

```

```Ruby
❯ rails c
irb(main):001> File.exist?('bun.lockb')
=> false
```
```Ruby
❯ ls
Dockerfile		README.md		bun.config.js		lib			storage			vendor
Gemfile			Rakefile		config			log			tailwind.config.js
Gemfile.lock		app			config.ru		package.json		test
Procfile.dev		bin			db			public			tmp
```

**Comment by terracatta** [comment]
@paulreece what is the exact command you are running that produces the output you included? Also, do you have `bun` in your local path?

**Comment by paulreece** [comment]
> Also, do you have `bun` in your local path?

This was the issue!  I was accidentally in the wrong directory last night when testing.  Thanks for your help.

**Comment by paulreece** [comment]
For anyone seeing this just check if bun's in your path first using `bun --version` if it isn't you either need to reinstall or restart your terminal.
