### ISSUE TITLE
InvalidAuthenticityToken Exception raised for "null" origin headers regardless of the protection strategy

### ISSUE THREAD

**Issue by jwright** [rails/rails#49611]
### Steps to reproduce

1. Specify the `null_session` strategy on a controller.
2. Send a POST request to an action in the controller with a "null" `origin` header
3. Notice that an exception is raised even though the strategy is set to `:null_session`

```ruby
# app/controllers/orders_controller.rb

class OrdersController < ActionController::Base
  protect_from_forgery with: :null_session

  def create
    # ...
  end
end
```

```ruby
# test/controllers/orders_controller_test.rb

class OrdersControllerTest < ActionDispatch::IntegrationTest
  describe "POST /orders" do
    describe "without an origin header" do
      let(:params) { {} }

      it "should still create the order" do
        OrdersController.stub_any_instance(:protect_against_forgery?, true) do
          post orders_path, params: params, headers: {HTTP_ORIGIN: "null"}

          assert_response :success
        end
      end
    end
  end
end
```

### Expected behavior

I believe that the exception for a null `origin` should result in the same protection strategy specified for that controller instance. If it is set to `with: :null_session` then it should not raise an exception and should null out the session just as other issues with the authenticity token.

For endpoints where we get these exceptions raised, they are valid requests from a webhook and for some reason some have a "null" origin. We want to process these requests so we are forced to add something like this as a workaround:

```ruby
class OrdersController < ActionController::Base
  protect_from_forgery with: :null_session
  rescue_from ActionController::InvalidAuthenticityToken, with: :ignore

  def create
    # ...
  end

  private

  def ignore(_exception)
    # we do not care about this exception, hence the `null_session` strategy
  end
end
```

If this is in fact by design and it is in the best interest for security to have this raise an exception, then I would ask that a special error class (e.g. `UnidentifiableOrigin`) be used.

### Actual behavior

An `InvalidAuthenticityToken` exception is raised, ignoring the protection strategy. 

Source: https://github.com/rails/rails/blob/d39db5d1891f7509cde2efc425c9d69bbb77e670/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L614

### System configuration
**Rails version**: 7.0.6
**Ruby version**: 2.7.5

**Comment by akhilgkrishnan** [comment]
@jwright  Could you please create a reproduction test script using the below template https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller_main.rb ?
