### ISSUE TITLE
Rails 7.1 : `with_options` now aggregates options from validations

### ISSUE THREAD

**Issue by sgara** [rails/rails#49620]
### Steps to reproduce
Using `with_options` to group multiple validations like this :
```ruby
class MyObject < ApplicationRecord
  with_options unless: -> { skip_validations? } do |object|
    object.validate :on_update_custom_validation, on: :update
    object.validate :another_custom_validation
  end
end
```

### Expected behavior
`another_custom_validation` should always run, this should be equivalent to :
```ruby
class MyObject < ApplicationRecord
  validate :on_update_custom_validation, on: :update, unless: -> { skip_validations? }
  validate :another_custom_validation, unless: -> { skip_validations? }
end
```

### Actual behavior
`another_custom_validation` runs on update, eg, it's now equivalent to :
```ruby
class MyObject < ApplicationRecord
  validate :on_update_custom_validation, on: :update, unless: -> { skip_validations? }
  validate :another_custom_validation, on: :update, unless: -> { skip_validations? }
end
```

### System configuration
**Rails version**: Rails 7.1

**Ruby version**: Ruby 3.2.2

**Comment by fatkodima** [comment]
Can you create a reproduction test script using this template - https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb?

**Comment by fatkodima** [comment]
This is actually equivalent to
```ruby
class MyObject < ApplicationRecord
  validate :on_update_custom_validation, on: :update, unless: -> { skip_validations? }
  validate :another_custom_validation, unless: -> { skip_validations? }
end
```

and `another_custom_validation` runs on `update` because by default (no `:on` specified) validations always run, independently of `create` or `destroy` etc. See https://api.rubyonrails.org/classes/ActiveModel/Validations/ClassMethods.html#method-i-validate.

**Comment by sgara** [comment]
I'm trying to create a reproduction script. In fact, I had a more explicit case with a complete application. Simplified example :
```
class MyObject < ApplicationRecord
  with_options unless: -> { skip_validations? } do |object|
    object.validates :title, presence: true
    object.validate :another_custom_validation
  end
end
```
which raised the following error :
```
ArgumentError: Unknown key: :presence. Valid keys are: :on, :if, :unless, :prepend. Perhaps you meant to call `validates` instead of `validate`?
```

On the other hand, I can't reproduce it with the simple script so I guess this may be a more complicated issue involving another dependency.

**Comment by fatkodima** [comment]
Looks similar to this issue https://github.com/rails/rails/issues/49457

**Comment by sgara** [comment]
Ok you're absolutely right, adding `config` to the script's gemfile triggered the issue. Closing this, thanks
