### ISSUE TITLE
ActiveRecord errors on Rails 7.1 running test suite

### ISSUE THREAD

**Issue by avonderluft** [rails/rails#49641]
### Steps to reproduce

Run test suite on [Occams CMS rails71 branch](https://github.com/avonderluft/occams/tree/rails71)  

```ruby
# rails test
```

### Expected behavior
Test suite should pass consistently, as it does for Rails 6.1, 7.0
See github actions example [here](https://github.com/avonderluft/occams/actions/runs/6514606850)

### Actual behavior
Test suite sometimes passes, but fails about 1 out 4 times with errors.  Tried running test suite in postgresql and mysql, but with much the same results
```
Cannot expire connection, it is owned by a different thread
cannot start a transaction within a transaction
SQLite3::BusyException: database is locked
```

### System configuration
**Rails version 7.1.1**:

**Ruby version 2.7, 3.0, 3.1, 3.2**:

**Comment by fatkodima** [comment]
We do not provide support on the issue tracker. If you will be able to provide a reproduction test script, will be happy to reopen and investigate.
