### ISSUE TITLE
How can I prepend all image paths with a custom directory outside of the app

### ISSUE THREAD

**Issue by mices** [rails/rails#49659]
How can I prepend all image paths with a custom directory outside of the app regardless of whether I'm using active_storage or not? My app has a lot of images from before I started using activestorage so there's a mix I'm trying to run two websites from the same database and having trouble with images in general

**Comment by fatkodima** [comment]
Hey @mices, we reserve the Rails Issues tracker for bugs in the framework as we don't have the bandwidth to offer application support. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help. Thanks for understanding.
