### ISSUE TITLE
`TypeError: wrong argument type Integer` when using `prefetch_primary_key?`

### ISSUE THREAD

**Issue by nicoco007** [rails/rails#49657]
We're using `prefetch_primary_key?` and `next_sequence_value` in a potentially unorthodox way in our project. It worked fine previously, but as of 7.1.0 we get the following error when creating a record:

```
TypeError: wrong argument type Integer (must respond to :each)
    bundler/gems/rails-2872d55a3be1/activerecord/lib/active_record/persistence.rb:1256:in `zip'
```

It seems be caused by #48241 which [returns the prefetched ID as-is](https://github.com/Shopify/rails/blob/c92933265efce7faa77767bf7f6ac0532312fd4e/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L192) even if a list of `returning` columns is specified. It looks like `_create_record` in `persistence.rb` expects a list of values corresponding to the columns to be returned, so when `_insert_record` returns just the integer it blows up.

### Steps to reproduce

Note the return values of `prefetch_primary_key?` and `next_sequence_value` here are just placeholders for actual logic.
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  class << self
    def prefetch_primary_key?
      true
    end

    def next_sequence_value
      Random.rand(1000000)
    end
  end
end

class BugTest < Minitest::Test
  def test_prefetch_primary_key
    Post.create!
  end
end
```

### Expected behavior
Model is created with the ID returned by `next_sequence_value`.

### Actual behavior
`TypeError` deep inside Rails.

### System configuration
**Rails version**: 7.1.1 & latest `main` as of writing (2872d55)

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
Would you like to work on a PR? That seems like an easy change (wrapping into `Array()`) and a test case.

Also curious since do not remember if had seen the use of prefetching primary keys before. What is the usecase?

**Comment by nicoco007** [comment]
Sure! I don't think it's necessarily the intended use case, but on our end we're basically using it to "sandbox" external API clients to a specific range of IDs.

**Comment by mguan2020** [comment]
Hello @nicoco007, @fatkodima,

Thank you very much for bringing this issue up. I found the discussion for this issue very helpful and constructive.

I have submitted a PR that I believe will have the solution that you are looking for.

Please let me know if there is anything you want me to fix.

**Comment by nicoco007** [comment]
Oh awesome, thanks for tackling this!

**Comment by nvasilevski** [comment]
Hey @nicoco007, sorry for the bother, would you mind elaborating a bit on the actual database schema being used in our application in production?

The reason I ask is that in your reproduction script the table is defined like
```ruby
create_table :posts, force: true do |t|
end
```
which by convention defines an auto-incremented `id` column as a primary key.

However It doesn't seem to represent a realistic setup. I assume models that utilize `prefetch_primary_key` capability won't have an auto-increment property on the column and the schema will most likely look like:

```ruby
create_table :posts, force: true, id: false do |t|
  t.integer :id, null: false
end
```

Which still reveals the same bug but may require a different approach to fix the problem. Thank you!

**Comment by nicoco007** [comment]
We do actually use this on tables with auto-incrementing IDs, although I can see why that's weird. Basically we use `prefetch_primary_key?` & `next_sequence_value` for our staging environment so external clients have an assigned range of IDs in specific tables so they can't accidentally fill the database with an excessive amount of dummy data. These same tables are also used internally and we don't want these restrictions when we're interacting with the models/database ourselves, so the auto-increment stayed. It's definitely a bit of a weird setup and we might be abusing the system here (or at least not doing what it was originally intended to do).
