### ISSUE TITLE
action_mailer.asset_host is missing protocol/scheme (http/https)

### ISSUE THREAD

**Issue by mikevoets** [rails/rails#49656]
## Overview

According to the [Action Mailer documentation](https://guides.rubyonrails.org/v5.1/action_mailer_basics.html), `action_mailer.asset_host` needs to have a value with the protocol or "scheme", e.g. `https://`. I have also experienced that if we omit the protocol, images sourced from our CDN aren't included in emails.

However, in the [Rails documentation](https://guides.rubyonrails.org/asset_pipeline.html), it's advised that `asset_host` is without the protocol. 

Rails also claims that setting `config.asset_host` is a shorthand for setting `config.action_controller.asset_host` and `config.action_mailer.asset_host`, but the latter won't work if you omit the protocol.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  ruby '3.0.5'
  source 'https://rubygems.org'
  gem 'rails', '7.0.8'
end

require 'rails/all'

module MyApplication
  class Application < Rails::Application
    config.load_defaults 7.0
    config.asset_host = 'example.com'
  end
end

Rails.application.initialize!

puts Rails.configuration.action_mailer.asset_host
```

### Expected behavior

I expect `Rails.configuration.action_mailer.asset_host` to return `https://example.com`

### Actual behavior

`Rails.configuration.action_mailer.asset_host` returns `example.com`

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.0.5

**Comment by MatheusRich** [comment]
I was able to reproduce it in Rails 7.1 with Ruby 3.2.2.

Not sure if it's a bug or desired behavior at this point, but the action_controller and action_mailer code do look the same:

https://github.com/rails/rails/blob/9f6b721b1d482ab16d7bdce758fea448bd7ffdbb/actionpack/lib/action_controller/railtie.rb#L68

https://github.com/rails/rails/blob/9f6b721b1d482ab16d7bdce758fea448bd7ffdbb/actionmailer/lib/action_mailer/railtie.rb#L34

**Comment by rafaelfranca** [comment]
This is intended behavior, but the doc is clearly wrong. We can't omit the protocol in the Action Mailer config because we can't infer from the request. We can in the controller. So either we tell people to config each host separately, or we tell them to always include the protocol, or we add a new config to action mailer just to configure the asset protocol.

**Comment by MatheusRich** [comment]
I believe the smaller lift here would be just updating the docs for Action Mailer. I'll open a PR.

**Comment by AxelTheGerman** [comment]
I'm glad I found this issue as this started showing up for me all of a sudden, I believe after the 7.1.1 upgrade.

The error I was getting was `ActionView::Template::Error: undefined method `protocol' for nil:NilClass`.

Wondering if there should be some kind of warning being logged when not having a protocol set - or maybe or more descriptive error being raised?

Alternatively maybe development and test could have a default protocol HTTP vs other environments HTTPS?
