### ISSUE TITLE
Unsafe implementation of `==(other)` method of AttributeSet

### ISSUE THREAD

**Issue by DmitryPogrebnoy** [rails/rails#49670]
### Steps to reproduce

There is a problem with the implementation of method `==(other)` of AttributeSet.
See https://github.com/rails/rails/blob/e4e242685efc74e4bacccd5c5878bc671fd63fb7/activemodel/lib/active_model/attribute_set.rb#L106-L108

So if you try to use it like this: `attribute_set == null`, then you get an NoMethodException.

The steps for reproduction are clear:
1. Get an instance of `AttributeSet` or `LazyAttributeSet`.
2. Suppose you have and instance AttributeSet in the variable `my_attribute_set`. Invoke the code below
```ruby
my_attribute_set == nil
```

### Expected behavior
It should return false. And be safe for any other instances

### Actual behavior
NoMethodException is thrown

### System configuration
**Rails version**: Rails 7

**Ruby version**: 2.7.8

**Comment by fatkodima** [comment]
Can you create a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb template?

**Comment by DmitryPogrebnoy** [comment]
Here it is:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

class BugTest < Minitest::Test
  def test_attribute_set
    my_attribute_set = ActiveModel::AttributeSet.new({})

    assert_equal false, my_attribute_set == nil
  end
end
```

**Comment by fatkodima** [comment]
Would you like to open a PR? An additional check for `self.class == other.class` and a test case would be enough.

**Comment by DmitryPogrebnoy** [comment]
Yep, I will do it.

**Comment by fatkodima** [comment]
Update to the suggestion: instead of `self.class == other.class` it is correct to use `other.is_a?(self.class)`, because there is also a `LazyAttributeSet` class.

**Comment by fatkodima** [comment]
Good point! @DmitryPogrebnoy How did you got that error? Can you share a real-world example?

**Comment by DmitryPogrebnoy** [comment]
I have a debugger gem that does object introspection. And there is a nil check in there like this:
`my_attribute_set == nil`. So it's quite unnatural to me that it will throw an exception in any case. This is an issue for the context: https://youtrack.jetbrains.com/issue/RUBY-31972.

Also, the current implementation of the `==(other)` method violates the symmetry contract, because `nil == my_attribute_set` returns false without any exception.

From my point of view this is definitely a bug. I don't know why we need to keep it just because this is not a part of public api.
