### ISSUE TITLE
[7.1.1] ActiveSupport::Cache::Entry regression resulting in TypeError: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by Judahmeek** [rails/rails#49685]
### Steps to reproduce
Cache a hash and then fetch it.

https://github.com/Judahmeek/active-support-cache-bug

### Expected behavior
ActiveSupport::Cache::Entry's value method should return a hash, like `{key: "value"}`

### Actual behavior
ActiveSupport::Cache::Entry's value method returns a string, like `"\x04\b{\x06:\x13keyI\"\x19value\x06:\x06ET"`, which results in `TypeError: no implicit conversion of Symbol into Integer` when my logic tries to reference a hash key on the returned string.

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

I've confirmed the cache_spec.rb example passes with Rails 7.0.8

**Comment by fatkodima** [comment]
Why are you going into the internals of the cache implementation in your test? https://github.com/Judahmeek/active-support-cache-bug/blob/6afd9d5d9f783142d65cfe13d2ef5b155f05564d/spec/system/cache_spec.rb#L32-L33

**Comment by Judahmeek** [comment]
> Why are you going into the internals of the cache implementation in your test? https://github.com/Judahmeek/active-support-cache-bug/blob/6afd9d5d9f783142d65cfe13d2ef5b155f05564d/spec/system/cache_spec.rb#L32-L33

Thanks for pointing that out. I don't think we actually have a good reason to be doing that.
