### ISSUE TITLE
Rails.cache.delete_matched throws invalid %-encoding for long url keys

### ISSUE THREAD

**Issue by m-bucher** [rails/rails#49690]
Because the FileStore Rails-Cache splits URI-encoded strings within an escape sequence (e.g. `%/2F`) , the path cannot be URI-decoded again: `invalid %-encoding`.
IMHO `ActiveSupport::Cache::FileStore::normalize_key‎` should make sure that the sub-directory names do not split escape-sequences.
There might be an issue with finding such large URL-keys  with `delete_matched` again in order to delete them, but I have not tested that.

### Steps to reproduce
```
Rails.cache.write "http://test.example.de#{'/a'*100}", 'brute-force'
Rails.cache.delete_matched(/hello/)
```
This will only fail, if the `cache_path` is set to a path without a trailing `/`, e.g. `Rails.root.join('tmp', 'cache')`.

```
Rails.cache.write "http://test.example.de#{'/a'*200}", 'brute-force'
Rails.cache.delete_matched(/hello/)
```
This also breaks if a trailing slash is in the cache_path (like it is in the default-path`)

### Expected behavior
`Rails.cache.delete_matched()` should not throw an exception.

### Actual behavior
```
/.../rubies/ruby-3.0.0/lib/ruby/3.0.0/uri/common.rb:324:in `decode_www_form_component': invalid %-encoding (Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa/%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2/Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa%2Fa) (ArgumentError)
```

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.0.0

**Comment by fatkodima** [comment]
Thanks for the report! I identified what the problem is and going to open a PR.
