### ISSUE TITLE
url_helpers generate invalid urls if a records second composite primary key is empty

### ISSUE THREAD

**Issue by mateigl** [rails/rails#49695]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, primary_key: ["firstname", "lastname"], force: true do |t|
    t.string "firstname", default: "", null: false
    t.string "lastname", default: "", null: false
  end
end

class User < ActiveRecord::Base
end

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger = config.logger

  routes.draw do
    resources :users, only: [:show]
  end
end

require "action_controller/railtie"

class UsersController < ActionController::Base
  include Rails.application.routes.url_helpers

  def show
    @user = User.find(params.extract_value(:id))
    render json: @user
  end
end

class BugTest < Minitest::Test
  include Rack::Test::Methods
  include Rails.application.routes.url_helpers

  def test_with_both_keys
    user = User.create!(firstname: "John", lastname: "Doe")
    get user_path(user)
    assert last_response.ok?
  end

  def test_with_only_first_key
    user = User.create!(firstname: "Jack")
    get user_path(user)
    assert last_response.ok?
  end

  def test_with_only_second_key
    user = User.create!(lastname: "Black")
    get user_path(user)
    assert last_response.ok?
  end

  private

  def app
    Rails.application
  end
end
```

### Expected behavior

Generated urls should be handled correctly even if the composite primary key is partially empty. It might be design choice to not support empty keys but the url helpers should at least warn about invalid urls.

### Actual behavior

Generated urls which contain merged composite primary keys always respond with a 404 error if the respective record has a empty second primary key.

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

**Comment by HolyWalley** [comment]
Thanks for the steps to reproduce, it was really helpful.
I think issue is not in url_helper, but in [extract_value](https://github.com/rails/rails/blob/main/actionpack/lib/action_controller/metal/strong_parameters.rb#L970) method which simply splits parameter by delimeter (`_` by default), so `"_Black"` results into `["", "Black"]`, but `"Jack_"` results into `["Jack"]` which then causes an error, when you are trying to use it as a result to find.

**Comment by fatkodima** [comment]
While I think that having blank (I mean empty strings really, because `NULL`s are not allowed or should not be allowed) columns as parts of a composite primary key is not a good idea, this is still a valid use case.

We can solve this by something like
```diff
diff --git a/actionpack/lib/action_controller/metal/strong_parameters.rb b/actionpack/lib/action_controller/metal/strong_parameters.rb
index de9ce87a6f..e375213de4 100644
--- a/actionpack/lib/action_controller/metal/strong_parameters.rb
+++ b/actionpack/lib/action_controller/metal/strong_parameters.rb
@@ -968,7 +968,11 @@ def deep_dup
     #   params.extract_value(:tags, delimiter: ",") # => ["ruby", "rails"]
     #   params.extract_value(:non_existent_key) # => nil
     def extract_value(key, delimiter: "_")
-      @parameters[key]&.split(delimiter)
+      if (value = @parameters[key])
+        values = value.split(delimiter)
+        values << "" if value.end_with?(delimiter)
+        values
+      end
     end

     protected
``` 

@nvasilevski Do you think this is a good idea?

**Comment by nvasilevski** [comment]
>@nvasilevski Do you think this is a good idea?

I agree that despite of the use-case being a bit unusual it's hard to to call it "wrong" so perhaps it would be a good thing to support it. So assuming that the generated URLs are fine and `params[:id]` value also matches our expectation I think your suggested solution will work. But should we then try to accommodate composite primary keys with the size larger than 2. Where we could end up with an identifier like `"Nikita__"` 
In these situations it's really hard to avoid introducing complexity just to support some non-realistic scenario which is valid on paper 😕

**Comment by HolyWalley** [comment]
I also think that use case is rare, but, if you are considering changing extract_value, maybe something like this might be a solution?

```ruby
def split(str, delimeter)
  str.each_char.with_object([""]) do |ch, obj|
    unless ch == delimeter
      obj.last << ch
    else
      obj << ""
    end
  end
end
```

btw, I can open a PR

**Comment by mateigl** [comment]
This might be a simpler solution:

```ruby
def extract_value(key, delimiter: "_")
  @parameters[key]&.split(delimiter, -1)
end
```

**Comment by fatkodima** [comment]
Nice, missed that `-1` thing! Opened https://github.com/rails/rails/pull/49749, added you both as co-authors. 
@mateigl Wasn't able to find your email to include into the `Co-author` thing, only some `no-reply` one.

**Comment by mateigl** [comment]
Thanks for taking care of this!
