### ISSUE TITLE
`alias_attribute` raises a deprecation warning. Rails 7.1 

### ISSUE THREAD

**Issue by rockwellll** [rails/rails#49699]
I'm in the process of upgrading an app from Rails 7.0.6 to Rails 7.1. 

Everything is running smoothly but I am seeing these logs,

```
DEPRECATION WARNING: Contact::Property model aliases `contact`, but `contact` is not an attribute. Starting in Rails 7.2, alias_attribute with non-attribute targets will raise. Use `alias_method :profile, :contact` or define the method manually. (called from block (3 levels) in <top (required)> at /Users/ahmed/hellotext/hellotext/spec/models/api/profile/params_spec.rb:181)
```

I searched in the Rails' upgrade docs but there was no mention of deprecating `alias_attribute`. 

Can anyone confirm this behavior or link a related page? Thank you in advance.

**Comment by skipkayhil** [comment]
I agree, this should be included in https://guides.rubyonrails.org/7_1_release_notes.html

Would you be interested in opening a PR?

**Comment by akhilgkrishnan** [comment]
Seems like we already shown some warnings for `alias_attribute` with non-attribute targets, ref: https://github.com/rails/rails/pull/48972.
