### ISSUE TITLE
Rails 7.1 changes `joins` behavior when using `unscope` in the scope

### ISSUE THREAD

**Issue by jwoodrow** [rails/rails#49708]
### Steps to reproduce

```ruby
create_table(:humans), id: :uuid do |t|
  t.string :human_id
  t.timestamp
end

create_table(:things), id: :uuid do |t|
  t.timestamp
end

class Thing
  belongs_to :human, lamda {
    unscope(:where).where('CAST(humans.id AS character varying) = things.human_id')
  }
end

class Human
  has_many :things, lambda {
    unscope(:where).where('things.human_id = CAST(humans.id AS character varying)')
  }
end

puts Human.joins(:things).to_sql
```

### Expected behavior

```sql
SELECT "humans".*
FROM "humans"
INNER JOIN "things" ON things.human_id = CAST(humans.id AS character varying)
```

### Actual behavior

```sql
SELECT "humans".*
FROM "humans"
INNER JOIN "things" ON things.human_id = CAST(humans.id AS character varying)
AND "things"."human_id" = "humans"."id"
```

### Why the `unscope` behavior required

We use Heroku Connect to keep Salesforce data up to date without the need for API calls. This works by having a second schema `salesforce` next to the `public` one. The extra complexity being we get 0 possibility of controlling the types on the fields in the `salesforce` schema. And it just so happens that they don't have any UUID types for their columns so any attempt to do a `INNER JOIN "things" ON "things"."human_id" = "humans"."id"` will lead inevitably to a `PG::UndefinedFunction: ERROR:  operator does not exist: character varying = uuid` error.

I believe this is linked to [this PR change](https://github.com/rails/rails/pull/47246) and more specifically [this change](https://github.com/rails/rails/blob/9f6b721b1d482ab16d7bdce758fea448bd7ffdbb/activerecord/lib/active_record/reflection.rb#L209)

```ruby
primary_foreign_key_pairs.each do |primary_key_column_name, foreign_key_column_name|
  klass_scope.where!(table[primary_key_column_name].eq(foreign_table[foreign_key_column_name]))
end
```

Now it systematically enforces the `foreign_key`/`primary_key` pairing after the scope is calculated meaning `unscope` no longer has any effect. 

Not being able to do joins/eager_loading is blocking situation for Rails 7.1 for us and I wish rails would just allow users to build their own join queries ready to use like it used to be possible back in the day with `finder_sql`

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

**Comment by rafaelfranca** [comment]
I'm not sure that is the change that caused this because it didn't change the order of operations, but I don't think this was intentional.

**Comment by akhilgkrishnan** [comment]
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 7.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :humans, id: :uuid do |t|
  end

  create_table :things, id: :uuid do |t|
    t.string :human_id
  end
end

class Thing < ActiveRecord::Base
  belongs_to :humans, lambda {
    unscope(:where).where("CAST(humans.id AS character varying) = things.human_id")
  }
end

class Human < ActiveRecord::Base
  self.table_name = "humans"
  has_many :things, lambda {
    unscope(:where).where("things.human_id = CAST(humans.id AS character varying)")
  }
end

class BugTest < Minitest::Test
  def test_sql
    sql = Human.joins(:things).to_sql
    puts sql
    assert false, sql.include?('"things"."human_id" = "humans"."id"')
  end
end

```

FYI: Also tried to reproduce on 7.0.8, seems like same sql query is generating there as well. could you please confirm that?

**Comment by jwoodrow** [comment]
> I'm not sure that is the change that caused this because it didn't change the order of operations, but I don't think this was intentional.

@rafaelfranca 
It was the best guess I had because we also use `where_exists` and in that use case the query builds as expected so the change seems to be Rails related and since this only happened when using `joins` style query builders I felt like this inclusion in what looks like the `join` logic of this primary key matching seemed significative 🤔 

> FYI: Also tried to reproduce on 7.0.8, seems like same sql query is generating there as well. could you please confirm that?

@akhilgkrishnan
On our end we were using Rails 7.0.8 just before (we try to stay up to date with Rails to prevent issues from existing between multiple versions) and were not encountering any issues on `join` queries. Maybe the fact we're using `pg` and not `sqlite3` (granted this should not have that much of an impact AFAIK)

**Comment by skipkayhil** [comment]
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 7.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# docker run --rm -e POSTGRES_PASSWORD=postgres -p 9999:5432 postgres
ActiveRecord::Base.establish_connection("postgres://postgres:postgres@localhost:9999/postgres")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :humans, id: :uuid, force: true do |t|
  end

  create_table :things, id: :uuid, force: true do |t|
    t.string :human_id
  end
end

class Thing < ActiveRecord::Base
  belongs_to :humans, lambda {
    unscope(:where).where("CAST(humans.id AS character varying) = things.human_id")
  }
end

class Human < ActiveRecord::Base
  self.table_name = "humans"
  has_many :things, lambda {
    unscope(:where).where("things.human_id = CAST(humans.id AS character varying)")
  }
end

class BugTest < Minitest::Test
  def test_sql
    sql = Human.joins(:things).to_sql
    puts sql
    refute_includes sql, '"things"."human_id" = "humans"."id"'
  end
end
```

I modified the script to use Postgres (in a docker container)

@jwoodrow Can you modify this script so that it passes on 7.0.8 and fails on 7.1? Like Akhil posted above, I tested the above script on main, 7-1-stable, 7-0-stable, and 7.0.8 and all of them produce the same query

**Comment by jwoodrow** [comment]
Hi, sorry about the delay. I've moved on with a monkey patch that seems to work but might probably break at one point but here it is if someone is looking for it. The gist is that I'm doing the primary_key clause BEFORE the scope clause and that allows me to use `unscope` as expected


```ruby
# lib/extensions/active_record/reflection.rb
module ActiveRecord
  module Reflection
    class AbstractReflection
      def join_scope(table, foreign_table, foreign_klass)
        predicate_builder = predicate_builder(table)
        scope_chain_items = join_scopes(table, predicate_builder)
        klass_scope       = klass_join_scope(table, predicate_builder)

        if type
          klass_scope.where!(type => foreign_klass.polymorphic_name)
        end

        primary_key_column_names = Array(join_primary_key)
        foreign_key_column_names = Array(join_foreign_key)

        primary_foreign_key_pairs = primary_key_column_names.zip(foreign_key_column_names)

        primary_foreign_key_pairs.each do |primary_key_column_name, foreign_key_column_name|
          klass_scope.where!(table[primary_key_column_name].eq(foreign_table[foreign_key_column_name]))
        end

        scope_chain_items.inject(klass_scope, &:merge!)

        if klass.finder_needs_type_condition?
          klass_scope.where!(klass.send(:type_condition, table))
        end

        klass_scope
      end
    end
  end
end
```

**Comment by rafaelfranca** [comment]
@jwoodrow can you help us to reproduce? We can't reproduce the issue, so we can't fix it. I understand that you already wrote a fix in form of a monkey patch, but that doesn't help the framework to determine if the issue is on the framework on your application.

**Comment by doits** [comment]
@jwoodrow Give it a try with `query_constraints: []`.

```ruby
class Human
  has_many :things, lambda {
    unscope(:where).where('things.human_id = CAST(humans.id AS character varying)')
  }, query_constraints: []
end
```

I think that fixes it, but I'm not sure if this is really the correct way to build such stuff. I'd want to build custom finder queries for my associations, too.

---

If we are at it: How do you retrieve the association when the model is already loaded without a join? E.g. `Human.last.things` – that doesn't work because it builds the query with `humans.id` instead of the specific `id` of the record. Do you overwrite `#things` to make it work maybe?

**Comment by erik-ekberg-hs** [comment]
I run into a similar sounding problem with `unscope` and `joins`. My particular use case is with `in_order_of`. For example,
```rb
# Adds "... IN ..." statement
User.in_order_of(:role, [:admin, :customer])
=> "SELECT users.* FROM users WHERE users.role IN ('admin', 'customer') ORDER BY CASE WHEN users.role = 'admin' THEN 1 WHEN users.role = 'customer' THEN 2 END ASC"

# unscope(...) removes "... IN ..." statement
User.in_order_of(:role, [:admin, :customer]).unscope(where: :role)
=> "SELECT users.* FROM users ORDER BY CASE WHEN users.role = 'admin' THEN 1 WHEN users.role = 'customer' THEN 2 END ASC"

# unscope(...) does not remove "... IN ..." statement for joins
User.joins(:tags).in_order_of(:name, [:some_name, :another_name]).unscope(where: :name)
=> "SELECT users.* FROM users INNER JOIN tags ON tags.owner_record_type = 'User' AND tags.owner_record_id = users.id WHERE name IN ('some_name', 'another_name') ORDER BY CASE WHEN name = 'some_name' THEN 1 WHEN name = 'another_name' THEN 2 END ASC"
```

**Comment by doits** [comment]
I'm not sure if this is the same problem @erik-ekberg-hs, since this issue is about unscoping, but here it doesn't work because the scope is applied at a later stage (so it makes no sense to call `unscope` and to expect it to remove a scope that gets added later). In your case it should be applied already (because of the call chain), so the issue feels different. (But maybe it is the same because maybe when chaining something on the `join` it changes the order of when scopes are applied? 🤷 .)

---

I guess the original issue comes down to the question: Should a `unscope(:where)` inside an assoication unscope the join condition?

```rb
has_many :things, lambda {
  # should this `unscope` remove the join condition?
  unscope(:where)
}
```

Or another way to ask the question: Should the join conditions already be applied when executing the lambda?

And the question why this is desired comes down to this question: How can an association be defined the Rails' way with 100 % custom sql, no automatic join conditions? Is this even desired?

---

I just tested it again, and it looks like it seems to be possible by using `foreign_key: []` (not `query_constraints: []` like I wrote before, looks like something changed internally):

```rb
  has_many :things, lambda {
    unscope(:where).where('things.human_id = CAST(humans.id AS character varying)')
  }, foreign_key: []
```

Here's a test case that verifies it:

<details><summary>Test case</summary>

```rb
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails'

  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :humen, id: :uuid, force: true do |t|
  end

  create_table :things, id: :uuid, force: true do |t|
  end
end

class Human < ActiveRecord::Base
  has_many :things, lambda {
    unscope(:where).where('1 = 1')
  }, foreign_key: []
end

class Thing < ActiveRecord::Base
  has_many :humans, lambda {
    unscope(:where).where('1 = 1')
  }, foreign_key: []
end

class BugTest < Minitest::Test
  def test_human_joins_thing_sql
    sql = Human.joins(:things).to_sql
    assert_equal sql, 'SELECT "humen".* FROM "humen" INNER JOIN "things" ON (1 = 1)'
  end
end
```

</details>

Again the question is: **Is this what Rails actually wants allow us to do**? Or is this a sideeffect of something different?

And it only works with `has_many`, not `belongs_to`. I case of `belongs_to`, setting `foreign_key: []` has no effect. I guess it makes no sense to have a `has_many` and `belongs_to` with custom sql anyway (can be `has_many` on both sides then), though I didn't think further about it. I didn't test further what happens if you try to assign something nor if you specify other options (like `inverse_of` etc.) either.

---

Again, I think the real question is: How can an association be specified with completely custom sql?
