### ISSUE TITLE
`ActiveRecord::Core#inspect` should have an option to not show the attributes in production

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails#49707]
By mistake, we had a hash containing multiple `ActiveRecord::Base` instance being inspected in production, through `Hash#to_s` call.

This was causing the parameter filter to execute for each attribute, which with the large set of objects we had, end up spending 9s to run.

While this was clearly a mistake, Rails could just help here avoiding the catastrophic results by not listing the attribute by default in production.

If for some reason people want to include their attributes in log message they can use another method that would print the record with attributes (maybe a formatted_inspect). Or they can disable the config per class (or globally)

**Comment by andrewn617** [comment]
I am working on implementing a solution for this.

**Comment by igrigorik** [comment]
>While this was clearly a mistake, Rails could just help the mistake to not catrastofic results by not listing the attribute by default in production.

Yes. Please!

**Comment by mguan2020** [comment]
Hi @rafaelfranca,

Thank you very much for opening this issue. I have linked a PR that I believe will have the solution that you are looking for.

**Comment by p8** [comment]
ActiveRecord uses `ActiveSupport::ParameterFilter` to mask attributes defined in `Rails.application.config.filter_parameters` using a deny list.
I'd like to see Rails support masking based on an allow lists instead.

I've created a PR to support parameter filtering based on allow lists: https://github.com/rails/rails/pull/45545
An alternative could be making the filtering pluggable, so everyone can write their own filtering class.

**Comment by p8** [comment]
Including `ActiveSupport::Inspect` that doesn't render any attributes could work here as well.
https://github.com/rails/rails/pull/45122

**Comment by andrewn617** [comment]
@mguan2020 I believe want to change the behaviour of `inspect` by default, not introduce a new method.

@p8 I think your solution will not solve the performance issue we are experiencing, since it still requires us to hit the parameter filter for every attribute.

I opened a PR with a solution that allows the attributes used by the `inspect` method to be configured: https://github.com/rails/rails/pull/49765
