### ISSUE TITLE
EDITOR in rails credentials:edit is being ignored 

### ISSUE THREAD

**Issue by ChaosInfinited** [rails/rails#49736]
### Steps to reproduce
1. Create new Rails  >=7.1.0.beta1 <=7.1.1 application (on Arch Linux, don't know about other OSes)
2. Type in terminal `EDITOR=nano rails credentials:edit`

### Expected behavior
Rails' credentials should be opened using nano, or any other specified editor

### Actual behavior
Rails' credentials are opening in system's default text editor (Kate), which doesn't work right, as it opens an empty tmp file and the terminal doesn't wait for Kate to end before saving: `File encrypted and saved.`
I tried uninstalling kate to see how rails will react to it, but it just opened nothing with `File encrypted and saved.` 

It fails as such on >=7.1.0.beta1 <=7.1.1 rails versions, works fine on <=7.0.8

### System configuration
**Rails version**: 7.1.0.beta1 - 7.1.1

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
Works on OS X on my machine. https://github.com/rails/rails/blob/ad1e443e535a6709cc314b614e757eb843d8c208/railties/lib/rails/command/helpers/editor.rb#L11-L13

**Comment by ChaosInfinited** [comment]
Ah, I see, my VISUAL is indeed set :facepalm: thanks!

**Comment by thewatts** [comment]
I just ran into this as well.

Here's the PR for reference: https://github.com/rails/rails/pull/48374
