### ISSUE TITLE
Rails 7.1.1 form_with and include_blank cannot be false for a required field

### ISSUE THREAD

**Issue by francesco-loreti** [rails/rails#49747]
```ruby
= form_with model: product do |f|
  = f.select :user_id, collection, { include_hidden: false, include_blank: false, required: true }
```

### Actual behavior
`ArgumentError - include_blank cannot be false for a required field.:`

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

**Comment by akhilgkrishnan** [comment]
@francesco-loreti This is an expected behaviour that was added in https://github.com/rails/rails/pull/20124.

**Comment by zzak** [comment]
I wonder if we included the name of the field it would help connect the dots.

**Comment by akhilgkrishnan** [comment]
> I wonder if we included the name of the field it would help connect the dots.

Yes, we also want to include the field name. I've raised a PR for that #49845
