### ISSUE TITLE
Rendering action mailer preview raises deprication warning

### ISSUE THREAD

**Issue by dannyy83** [rails/rails#49754]
When rending an action mailer preview path, a deprication warning is raised even though I am not using `config.action_mailer.preview_path` anywhere in my rails configuration.

### Steps to reproduce
Visit a URL that renders an action mailer preview.
Or, in the rails console, execute: `ActionMailer::Base.show_previews`

### Expected behavior
The action mailer preview renders

### Actual behavior
The deprication warning is thrown:

`DEPRECATION WARNING: Using preview_path= option is deprecated and will be removed in Rails 7.2. Please use preview_paths= instead.`

I am not using the preview_path option anywhere in my rails config.

I believe this is raised within one of the before_actions of `Rails::MailersController#preview` 

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

**Comment by skipkayhil** [comment]
Could you provide an app that can reproduce the issue, or at a minimum a full backtrace of where the warning is coming from?

**Comment by danielyazbek** [comment]
Hi @skipkayhil, thanks for your prompt response.
I've done some more investigation and found that the `rspec-rails` gem is the culprit (which I currently have in groups `test` and `development`. If I remove this gem from my gemfile and restart, then the warnings disappear and everything works as expected.

**Comment by danielyazbek** [comment]
It is easy to reproduce, I have created a clean rails 7.1.1 project and added the `rspec-rails` gem.
See https://github.com/danielyazbek/debug_action_mailer_deprication

You can see the deprication warning by visiting the `/rails/mailers/` url.

**Comment by danielyazbek** [comment]
See https://github.com/rspec/rspec-rails/issues/2703
