### ISSUE TITLE
postgres enum array + db:prepare regression in rails 7.1.1

### ISSUE THREAD

**Issue by modosc** [rails/rails#49767]
### Steps to reproduce
repo is here: https://github.com/modosc/rails-7-bug-repro

the `schema.rb` is a snippet from a rails 7.0 app we have. when upgrading to 7.1 various db tasks broken. i isolated the issue down to what's committed in `db/schema.rb`. 

### Expected behavior
`rails db:prepare`  should work and not remove the `accounts` table from `db/schema.rb`

### Actual behavior
```bash
$ rails db:drop db:prepare
Dropped database 'rails_bug_development'
Dropped database 'rails_bug_test'
Created database 'rails_bug_development'
unknown OID 824692: failed to recognize type of 'account_types'. It will be treated as String.
Created database 'rails_bug_test'
$ git diff
diff --git a/db/schema.rb b/db/schema.rb
index c7a182a..45937af 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -18,7 +18,4 @@ ActiveRecord::Schema[7.1].define(version: 2023_10_24_155210) do
   # Note that some types may not work with other database engines. Be careful if changing database.
   create_enum "account_type", ["customer", "vendor"]

-  create_table "accounts", force: :cascade do |t|
-    t.enum "account_types", array: true, enum_type: "account_type"
-  end
 end
```

there seems to be an intermediate change to `db/schema.rb` which includes these contents:
```
# Could not dump table "accounts" because of following StandardError
#   Unknown type 'account_type' for column 'account_types'
```
but that gets overwritten almost immediately.

note that `db:schema:load` does work as expected:
```bash
$ rails db:drop db:create db:schema:load
Dropped database 'rails_bug_development'
Dropped database 'rails_bug_test'
Created database 'rails_bug_development'
Created database 'rails_bug_test'
```

also note that in both cases the underlying db table is created. however, any subsequent db migration will cause the `accounts` table to be removed from `db/schema.rb`

finally, note that if i remove `array: true` from both the initial migration and `db/schema.rb` everything works as expected.

### System configuration
**Rails version**:
```bash
$ rails -v
Rails 7.1.1
```

**Ruby version**:
```bash
$  ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
```

**Postgres version**:
```
psql (16.0, server 15.4 (Homebrew))
```

**Comment by modosc** [comment]
i bisected from the last 7.0.x release and came up with 660fee087d4c92f0c7c31f11bc29b5f40e399caa :
```
660fee087d4c92f0c7c31f11bc29b5f40e399caa is the first bad commit
commit 660fee087d4c92f0c7c31f11bc29b5f40e399caa
Author: Ben Sheldon [he/him] <bensheldon@gmail.com>
Date:   Sun Jun 26 08:23:00 2022 -0700

    Allow db:prepare to load schema if database already exists but is empty; also dumps schema after migrations

 activerecord/CHANGELOG.md                          |  4 +++
 .../lib/active_record/tasks/database_tasks.rb      | 16 ++++++------
 railties/test/application/rake/dbs_test.rb         | 29 ++++++++++++++++++----
 3 files changed, 35 insertions(+), 14 deletions(-)
```

**Comment by modosc** [comment]
i verified that this works if the changes to `ActiveRecord::Tasks::DatabaseTasks.prepare_all` are reverted:

https://github.com/modosc/rails-7-bug-repro/tree/with-monkeypatch

with this fix in our non-public repo i still see these lines in the `db:prepare` output:
```
Created database 'foo_development'
unknown OID 857906: failed to recognize type of 'account_types'. It will be treated as String.
Created database 'foo_test'
unknown OID 859362: failed to recognize type of 'account_types'. It will be treated as String.
```
but `db/schema.rb` is no longer overwritten and migrations can be run.

**Comment by fatkodima** [comment]
Identified what the problem is. Going to open a PR.

**Comment by fatkodima** [comment]
@modosc Can you verify that https://github.com/rails/rails/pull/49772 fixes your issue?

**Comment by modosc** [comment]
@fatkodima tested locally and it works, thanks for the quick response!
