### ISSUE TITLE
Strict locals cause an error when implicitly rendering a collection

### ISSUE THREAD

**Issue by ayushn21** [rails/rails#49761]
Rendering a collection where the partial name is implicit, and the partial contains strict locals, an error is thrown.

### Steps to reproduce

Create a new app and scaffold a `Post`.

```shell
$ rails new strict-locals-error
$ bin/rails generate scaffold post title:string body:text
$ bin/rails db:migrate
```

Create a few posts using the UI. Amend the `index` view to render the collection implicitly:

```erb
<%# app/views/posts/index.html.erb %>

<div id="posts">
  <%= render @posts %>
</div>
```

Set a strict local in the `_post` partial:

```erb
<%# app/views/posts/_post.html.erb %>

<%# locals: (post:) %>

<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>
```

### Expected behavior

The index view should render successfully.

### Actual behavior

An error is thrown and the view doesn't render.

```
app/views/posts/index.html.erb:6
Started GET "/cable" for 127.0.0.1 at 2023-10-24 13:25:15 +0100
Started GET "/cable" [WebSocket] for 127.0.0.1 at 2023-10-24 13:25:15 +0100
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
Started GET "/posts/" for 127.0.0.1 at 2023-10-24 13:26:13 +0100
Processing by PostsController#index as HTML
  Rendering layout layouts/application.html.erb
  Rendering posts/index.html.erb within layouts/application
  Post Load (0.2ms)  SELECT "posts".* FROM "posts"
  ↳ app/views/posts/index.html.erb:6
  Rendered collection of posts/_post.html.erb [2 times] (Duration: 1.0ms | Allocations: 1778)
  Rendered posts/index.html.erb within layouts/application (Duration: 3.6ms | Allocations: 2630)
  Rendered layout layouts/application.html.erb (Duration: 3.8ms | Allocations: 2722)
Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.1ms | Allocations: 2972)



ActionView::Template::Error (unknown keywords: :post_counter, :post_iteration):

app/views/posts/index.html.erb:6
```

This issue is not present when implicitly rendering a single partial. For eg:

```erb
<%= render @post %>
```

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

**Comment by HolyWalley** [comment]
I can reproduce it

I'll try to figure out what's wrong

**Comment by HolyWalley** [comment]
So, from what I understand so far, when you are rendering partial from a collection like that

```erb
<%= render @posts %>
```

rails also generates 2 additional variables (in your case :post_counter and :post_iteration)

it happens here https://github.com/rails/rails/blob/main/actionview/lib/action_view/renderer/collection_renderer.rb#L148

It's intender behaviour and it's documented [here](https://guides.rubyonrails.org/layouts_and_rendering.html#counter-variables)

I don't know if the behaviour you described was also intentional.

From what I see in the PR description is that this PR should also allow us in the future to precompile views, so, fix for this issue must also consider this fact, I suppose

I will continue my investigation and hopefully will come to the appropriate solution

**Comment by ayushn21** [comment]
Thanks for looking into this @HolyWalley. I see what's happening .... if I change the magic comment to:

```erb
<%# locals: (post:, post_counter:, post_iteration:) %>
```🤔

the error goes away.

I wonder if this issue should be a documentation fix rather than a code fix? 🤔 .... or perhaps some additional logic around the magic comment that allows those variables automatically when the name of the strict local variable matches the name of the partial?

I'm just spitballing ideas here ... I don't understand the inner workings of this stuff so please feel free to ignore me :D.

**Comment by HolyWalley** [comment]
> if I change the magic comment to 
> ```erb
> <%# locals: (post:, post_counter:, post_iteration:) %>
> ```
> the error goes away.

Exactly

btw, now if you try to render single partial it should (from my understanding) fail, cause post_counter and post_interaction will be empty, so, it makes sense to do something like this, probably:

```erb
<%# locals: (post:, post_counter: nil, post_iteration: nil) %>
```

I'm also not sure if this behaviour should be documented or fixed, my gut filing says that it's not Rails way to write this boilerplate, so, I'm trying to come up with some elegant solution, however, I'm also not the best expert here, so, it takes time and it would be nice to hear any feedback on that topic, maybe from someone related to the original PR

**Comment by ayushn21** [comment]
> btw, now if you try to render single partial it should (from my understanding) fail, cause post_counter and post_interaction will be empty

Ah yes good point, we'll need those `nil` default values.

> my gut filing says that it's not Rails way to write this boilerplate

I agree, it's very unintuitive. My ideal solution here would be the ability to write:

```erb
<%# locals: (post:) %>
```

And Rails under the hood also allows the `post_counter` and `post_iteration` variables. Whether this is viable I have no idea, so yeah would be great to hear the opinion of someone involved in the original PR 👍.

**Comment by HolyWalley** [comment]
From what I see now, both `render @post` and `render @posts` and the end uses the same `ActionView::Template` (same object_id). This object will compile and cache a rendering method for partial.

So, I guess that now, the only quick way to do so, is to modify `ActionView::Template#strict_locals!` method to something like this:


```ruby
    def strict_locals!
      if @strict_locals == NONE
        self.source.sub!(STRICT_LOCALS_REGEX, "")
        @strict_locals = $1

        return if @strict_locals.nil? # Magic comment not found

        if @strict_locals.blank?
          @strict_locals = "**nil"
        else
          model_attr, *other_attributes = @strict_locals.split(",")

          [model_attr, *other_attributes, model_attr.sub(/:\z/, "_counter: nil"), model_attr.sub(/:\z/, "_iteration: nil")].join(",")
        end
      end

      @strict_locals
    end
```

(haven't yet tested spelling, but the idea is understandable I think)

However, this will add 2 extra arguments (_counter and _iteration) to all partials, even those which do not render from model. Which is quite dirty.

For now, I think it makes sense to wait for someone's related to the original feature opinion. Maybe I oversee some better options to do that. Anyway, I would like to implement this or any better solution if there will be decision to do so.

**Comment by HolyWalley** [comment]
Well, I started to think from another end. What if we can skip passing _counter and _iteration to partial if they were not specified in the partial manually? It sound a bit more intuitive, I'll check if that's possible to implement without hacks

**Comment by HolyWalley** [comment]
Well, yeah, that's possible and looks much better

we can modify [ActionView::Base#_run](https://github.com/rails/rails/blob/main/actionview/lib/action_view/base.rb#L245) method to something like this:

```ruby
    def _run(method, template, locals, buffer, add_to_stack: true, has_strict_locals: false, &block)
      _old_output_buffer, _old_virtual_path, _old_template = @output_buffer, @virtual_path, @current_template
      @current_template = template if add_to_stack
      @output_buffer = buffer

      if has_strict_locals
        begin
          allowed_locals = method(method).parameters.select { |type, name| type.in?(%i[keyreq key]) }.map(&:last)

          public_send(method, buffer, **locals.slice(*allowed_locals), &block)
        rescue ArgumentError => argument_error
          raise(
            ArgumentError,
            argument_error.
              message.
                gsub("unknown keyword:", "unknown local:").
                gsub("missing keyword:", "missing local:").
                gsub("no keywords accepted", "no locals accepted")
          )
        end
      else
        public_send(method, locals, buffer, &block)
      end
    ensure
      @output_buffer, @virtual_path, @current_template = _old_output_buffer, _old_virtual_path, _old_template
    end
```

however, in this implementation, it won't raise an error if extra local was passed, which kinda breaks the restricted locals feature. 

I think we can probably pass an argument to render method to allow this behaviour for collections only...

btw, if using method(method).parameters is hacky, we can parse has_strict_locals (it's a string of format 'post:'), it's just requires a bit more code

**Comment by HolyWalley** [comment]
yep, it's quite easy to pass additional option and only remove those locals from call that might be removed

```diff
diff --git a/actionview/lib/action_view/base.rb b/actionview/lib/action_view/base.rb
index cb1e485fed..979e9de2de 100644
--- a/actionview/lib/action_view/base.rb
+++ b/actionview/lib/action_view/base.rb
@@ -242,14 +242,17 @@ def initialize(lookup_context, assigns, controller) # :nodoc:
       assign(assigns)
     end

-    def _run(method, template, locals, buffer, add_to_stack: true, has_strict_locals: false, &block)
+    def _run(method, template, locals, buffer, add_to_stack: true, has_strict_locals: false, optional_locals: [], &block)
       _old_output_buffer, _old_virtual_path, _old_template = @output_buffer, @virtual_path, @current_template
       @current_template = template if add_to_stack
       @output_buffer = buffer

       if has_strict_locals
         begin
-          public_send(method, buffer, **locals, &block)
+          allowed_locals = method(method).parameters.select { |type, name| type.in?(%i[keyreq key]) }.map(&:last)
+          excepted_locals = optional_locals - allowed_locals
+
+          public_send(method, buffer, **locals.except(*excepted_locals), &block)
         rescue ArgumentError => argument_error
           raise(
             ArgumentError,
diff --git a/actionview/lib/action_view/renderer/collection_renderer.rb b/actionview/lib/action_view/renderer/collection_renderer.rb
index 7eba19edb9..87599b9015 100644
--- a/actionview/lib/action_view/renderer/collection_renderer.rb
+++ b/actionview/lib/action_view/renderer/collection_renderer.rb
@@ -194,7 +194,7 @@ def collection_with_template(view, template, layout, collection)

           _template = (cache[path] ||= (template || find_template(path, @locals.keys + [as, counter, iteration])))

-          content = _template.render(view, locals)
+          content = _template.render(view, locals, optional_locals: [counter, iteration])
           content = layout.render(view, locals) { content } if layout
           partial_iteration.iterate!
           build_rendered_template(content, _template)
diff --git a/actionview/lib/action_view/template.rb b/actionview/lib/action_view/template.rb
index 189e73c239..45365dbead 100644
--- a/actionview/lib/action_view/template.rb
+++ b/actionview/lib/action_view/template.rb
@@ -244,14 +244,14 @@ def supports_streaming?
     # This method is instrumented as "!render_template.action_view". Notice that
     # we use a bang in this instrumentation because you don't want to
     # consume this in production. This is only slow if it's being listened to.
-    def render(view, locals, buffer = nil, add_to_stack: true, &block)
+    def render(view, locals, buffer = nil, add_to_stack: true, optional_locals: [], &block)
       instrument_render_template do
         compile!(view)
         if buffer
-          view._run(method_name, self, locals, buffer, add_to_stack: add_to_stack, has_strict_locals: strict_locals?, &block)
+          view._run(method_name, self, locals, buffer, add_to_stack: add_to_stack, has_strict_locals: strict_locals?, optional_locals:, &block)
           nil
         else
-          view._run(method_name, self, locals, OutputBuffer.new, add_to_stack: add_to_stack, has_strict_locals: strict_locals?, &block)&.to_s
+          view._run(method_name, self, locals, OutputBuffer.new, add_to_stack: add_to_stack, has_strict_locals: strict_locals?, optional_locals:, &block)&.to_s
         end
       end
     rescue => e
```

if this seems good I can prepare a PR

**Comment by HolyWalley** [comment]
As I can see, the author of the [original feature](https://github.com/rails/rails/pull/45602) is on paternity leave now, so, as one of the most involved into review process @byroot, could you please take a look at the discussion above?

**Comment by byroot** [comment]
After a quick skim, I think that `render @posts` should detect that the view uses strict locals and forgo passing `*_counter` and  `*_iteration` arguments if they aren't accepted.

However it shouldn't forgo passing any other argument.

If someone wish to PR that, otherwise I'll try to find some time for it later.
