### ISSUE TITLE
Nested form params are malformed in Rails 7.1

### ISSUE THREAD

**Issue by dan003400** [rails/rails#49783]
```
<%= form_with(model: [:dashboard, @integration]) do |form| %>
  <%= form.text_field "configurations_fields[measurement_id]", value: @integration.configurations_fields[:measurement_id] %>
<% end %>
```

browser payload:
```
integration[configurations_fields[measurement_id]]: G-123231231
integration[kind]: ga4
```

params on server:
```
{"integration"=>#<ActionController::Parameters {"configurations_fields[measurement_id"=>{"]"=>"G-123231231"}, "kind"=>"ga4"} permitted: false>, "commit"=>"Connect Google Analytics", "layout"=>"dashboard", "controller"=>"dashboard/integrations", "action"=>"create"}
```

### Expected behavior
Before upgrading to 7.1 (previously 7.0) there was no issues by having fields like so, but now as you can see there is added characters being added. Our guess is this is being added during some middleware process that processes the controller params.

```{"configurations_fields[measurement_id"=>{"]"=>"G-123231231"}, "kind"=>"ga4"}```

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.1.2

**Comment by fatkodima** [comment]
Duplicate of https://github.com/rails/rails/issues/49601?

**Comment by dan003400** [comment]
@fatkodima this does appear to be the same issue, I am not sure what the solution is after reading through this, we have tried both:

```
<%= form.text_field "integration[configurations_fields][measurement_id]", value: @integration.configurations_fields[:measurement_id] %>
```

```
<%= form.text_field "configurations_fields[measurement_id]", value: @integration.configurations_fields[:measurement_id] %>
```

```
<%= form.text_field "configurations_fields[[measurement_id]]", value: @integration.configurations_fields[:measurement_id] %>
```

All with the exact same errors, is there a solution to all this?

**Comment by dan003400** [comment]
We have since got this working by using `fields_for` as so:

```
<%= form.fields_for :configurations_fields do |configurations_fields| %>
   <%= configurations_fields.text_field :measurement_id, value: @integration.configurations_fields[:measurement_id] %>
<% end %>
```

It seems the string representation without the fields_for should work properly?

**Comment by fatkodima** [comment]
Had you tried `fields_for`(https://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-fields_for) for `configurations_fields`?

**Comment by dan003400** [comment]
Talk about that timing!

**Comment by fatkodima** [comment]
So the problem solved? Can we close this?

**Comment by dan003400** [comment]
Yes, unless the string representation should work for nested fields in the `text_field` helper.

**Comment by fatkodima** [comment]
> Yes, unless the string representation should work for nested fields in the text_field helper.

Do you mean 
```ruby
<%= configurations_fields.text_field "measurement_id", value: ...
```
 or what?

**Comment by dan003400** [comment]
Should this work:

```
<%= form.text_field "configurations_fields[measurement_id]", value: @integration.configurations_fields[:measurement_id] %>
```

This has always worked in the past in previous version of rails. A shorthand without using `fields_for`

**Comment by fatkodima** [comment]
@jeremyevans Can you suggest, was this worked before accidentally too?

**Comment by jeremyevans** [comment]
Correct.  `a[b[c]]` was never officially supported by Rack.  The officially supported way is `a[b][c]`.  If Rails wants to be backwards compatible and support `b[c]` for text_field, then it would need to parse the `b[c]` and not just do `"a[#{arg}]"`.

**Comment by stillhart** [comment]
Just run into the same issue. As written, this does not feel very railsy
