### ISSUE TITLE
MemoryStore#fetch with 7.1 defaults can't set `expires_at` via block opts

### ISSUE THREAD

**Issue by mroach** [rails/rails#49796]
### Steps to reproduce

In a Rails app, use the following config:

```ruby
config.cache = :memory_store
config.load_defaults(7.1)
```

Now, use `Rails.cache.fetch` passing a block and try to set `options.expires_at`. An `ArgumentError` is raised:

```
ArgumentError: Either :expires_in or :expires_at can be supplied, but not both
```

Additionally, the cache store's options are mutated with the `expries_at` option set in the block

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class TestApp < Rails::Application
  config.root = "/tmp"
  config.eager_load = false
  config.cache = :memory_store
  config.load_defaults(7.1)

  Rails.application.initialize!
end

class BugTest < Minitest::Test
  def test_memory_store_fetch_opts
    Rails.cache.fetch(SecureRandom.alphanumeric) do |_key, opts|
      opts.expires_at = 1.minute.from_now
      Time.now.to_s
    end
  ensure
    puts "Cache options are now #{Rails.cache.options}"
  end
end
```

### Expected behavior

Cache is written with the given `expires_at` value.

### Actual behavior

An `ArgumentError` is raised saying that we're trying to set two options. `Rails.cache` options are mutated with the options from the block.

```
# Running:

Cache options are now {:compress=>true, :compress_threshold=>1024, :expires_at=>Thu, 26 Oct 2023 12:58:56.191690312 UTC +00:00}
E

Error:
BugTest#test_memory_store_fetch_opts:
ArgumentError: Either :expires_in or :expires_at can be supplied, but not both
```

### System configuration
**Rails version**: *main*

**Ruby version**: 3.2.2

**Comment by HolyWalley** [comment]
If no one minds, I'll check it out

**Comment by HolyWalley** [comment]
Well, turns out the actual problem is a bit more serious (but easy to fix)

method `merge_options` in case if no call_options were specified returns Store@options as a result of merge, this way when we change our options in block, what we actually do - we change global rails cache options. I'll make a PR with a fix soon
