### ISSUE TITLE
simple_format adds br tags between li tags in rails 6

### ISSUE THREAD

**Issue by arusa** [rails/rails#49816]
### Steps to reproduce

When you use [simple_format](https://github.com/rails/rails/blob/23938052acd773fa24068debe56cd892cbf8d868/actionview/lib/action_view/helpers/text_helper.rb#L322C40-L322C40) on a text that contains an html list, like the following line, it adds <br /> tags between list items, which is invalid HTML syntax:

```ruby
ApplicationController.helpers.simple_format("<ol><li>item1</li><li>item2</li></ol>")
```

I have tried it with Rails 6.1.7.6 and Rails 7.1.1 and the result is identical.

### Expected behavior
```
ApplicationController.helpers.simple_format("<ol><li>item1</li><li>item2</li></ol>")
=> "<p><ol><li>item1</li><li>item2</li></ol></p>"
```

### Actual behavior

```
ApplicationController.helpers.simple_format("<ol><li>item1</li><li>item2</li></ol>")
=> "<p><ol>\n<br /><li>item1</li>\n<br /><li>item2</li>\n<br /></ol></p>"
```

### System configuration

**Rails version**: 7.1.1 and 6.1.7.6

**Ruby version**: 3.1.4 and 3.0.6

**Comment by paulreece** [comment]
Hey there, thanks or opening the issue. 

So I believe `simple_format` is intended to be used with text, not HTML.  At least that's what the examples are showing for it's use in the Doc Strings here:
https://github.com/rails/rails/blob/23938052acd773fa24068debe56cd892cbf8d868/actionview/lib/action_view/helpers/text_helper.rb#L282-L321

**Comment by arusa** [comment]
Thanks for the quick reply!

One of the examples also shows it being used with html code and even the possibility to tell the sanitizer about allowed attributes:

https://github.com/rails/rails/blob/23938052acd773fa24068debe56cd892cbf8d868/actionview/lib/action_view/helpers/text_helper.rb#L320

**Comment by paulreece** [comment]
Good Catch! I do see that these examples are mainly for single HTML elements though, not lists. 

However I do see your point, if it is intended to be able to deal with multiple HTML elements then having the `< br />`s in there aren't needed.

**Comment by fatkodima** [comment]
Line 320 shows an example of html. 

This `sanitize` call https://github.com/rails/rails/blob/403447d06165b0e9a13f0942f11b97e2f9d426b8/actionview/lib/action_view/helpers/text_helper.rb#L325 ands newlines (don't know why) making it look like `"<ol>\n<li>item1</li>\n<li>item2</li>\n</ol>"`, and that is further appended `<br>`s because of newlines.

**Comment by paulreece** [comment]
Since this is happening within `[rails-html-sanitizer](https://github.com/rails/rails-html-sanitizer)` I wonder if this would be better served as an issue opened on that repo?

**Comment by akhilgkrishnan** [comment]
@arusa, I'm actually getting the expected on 7.1.1 and main

```ruby
3.1.3 :010 > ApplicationController.helpers.simple_format("<ol><li>item1</li><li>item2</li></ol>")
 => "<p><ol><li>item1</li><li>item2</li></ol></p>"
 ```

**Comment by paulreece** [comment]
As am I on both 7.1.1 and main:
```Ruby
irb(main):001> ApplicationController.helpers.simple_format("<ol><li>item1</li><li>item2</li></ol>")
=> "<p><ol><li>item1</li><li>item2</li></ol></p>"
```

**Comment by arusa** [comment]
That's really strange. I have the latest version of `rails-html-sanitizer` (1.6.0) and rails 7.1.1 and get a different result on at least 2 different apps on my MacBook and also on the Linux servers.

```
$ grep rails-html-sanitizer Gemfile.lock
...
    rails-html-sanitizer (1.6.0)
$ bin/rails c
Loading production environment (Rails 7.1.1)
irb(main):001> ApplicationController.helpers.simple_format("<ol><li>item1</li><li>item2</li></ol>")
=> "<p><ol>\n<br /><li>item1</li>\n<br /><li>item2</li>\n<br /></ol></p>"
```

On a completely new created app it works as expected (tested with ruby 3.1.4 and 3.2.1):

```
$ rails new rails7test
$ cd rails7test
$ bin/rails c
Loading development environment (Rails 7.1.1)
irb(main):001> ApplicationController.helpers.simple_format("<ol><li>item1</li><li>item2</li></ol>")
=> "<p><ol><li>item1</li><li>item2</li></ol></p>"
```

Seems like I need to dig a little bit deeper on what's the difference between the older updated apps and the fresh created one.

Btw. I also tested it with a new created rails 7.0.8 app and it didn't work. So it seems this behaviour only changed very recently.

**Comment by akhilgkrishnan** [comment]
I'm able to reproduce this by running an inline script

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  # gem "rails", "~> 7.1.0"
  gem "rails", "7.1.1"
  # gem "rails", github: "rails/rails", branch: "main"
end

require "action_view"
require "minitest/autorun"
require "logger"
require "action_controller/railtie"


class ApplicationController < ActionController::Base
end

class SimpleFormatHelperTest < Minitest::Test
  def test_content
    assert_equal "<p><ol><li>item1</li><li>item2</li></ol></p>", ApplicationController.helpers.simple_format("<ol><li>item1</li><li>item2</li></ol>")
  end
end
```

**Comment by akhilgkrishnan** [comment]
I found the actual problem of this issue, In https://github.com/rails/rails/pull/48293 this PR, we added support of `Rails::HTML5::Sanitizer` and by default the rails 7.1 uses the `Rails::HTML5::Sanitizer`. Before this configuration it was using `Rails::HTML4::Sanitizer`.

If you want to replicate this behaviour,
```ruby
# config.action_view.sanitizer_vendor = Rails::HTML5::Sanitizer

3.2.2 :001 > ActionController::Base.helpers.simple_format("<ol><li>item1</li><li>item2</li></ol>")
 => "<p><ol><li>item1</li><li>item2</li></ol></p>"
```

```ruby
# config.action_view.sanitizer_vendor = Rails::HTML4::Sanitizer

3.2.2 :002 > ActionController::Base.helpers.simple_format("<ol><li>item1</li><li>item2</li></ol>")
 => "<p><ol>\n<br /><li>item1</li>\n<br /><li>item2</li>\n<br /></ol></p>"
```

**Comment by akhilgkrishnan** [comment]
@arusa, I'm marking this PR as closed, as the observed behaviour aligns with our expectations. If you believe there are further issues to address, please don't hesitate to reopen it.

**Comment by akhilgkrishnan** [comment]
@arusa, I'm marking this PR as closed, as the observed behaviour aligns with our expectations. If you believe there are further issues to address, please don't hesitate to reopen it.
