### ISSUE TITLE
Existing class named Content clashes with ActionView::TestCase::Behavior::Content:Class when running test inheriting from ActionView::TestCase

### ISSUE THREAD

**Issue by ccasabona** [rails/rails#49818]
We have several projects with a class named Content.  Starting in rails 7.1, referencing this class name in a helper test which inherits from ActionView::TestCase causes an exception NoMethodError from ActionView::TestCase::Behavior::Content:Class when, as in this example, calling certain Active Record methods with the object Content as the receiver.

This exception occurs only in tests which inherit from ActionView::TestCase.  The class name works correctly in other tests and in the app itself.

This seems to have come from #49194 (but don't hold me to that). It occurs in 7.1.0, 7.1.1, and in the main branch.

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  # gem "rails", "~> 7.1.0"
  gem "rails", "~> 7.1.1"
  # gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "action_view"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :contents, force: true do |t|
    t.string "title"
  end
end

class Content < ActiveRecord::Base
end

class ContentsHelperTest < ActionView::TestCase
  def test_content
    # new method works
    Content.new(title: 'New Content')

    # either of these cause an exception
    # Content.create!(title: 'First')
    Content.first
  end
end

```

### Expected behavior
Existing classes named Content should be usable in tests inheriting from ActionView::TestCase

### Actual behavior
Using an object named Content as the receiver in certain Active Record method calls mistakenly goes to ActionView::TestCase::Behavior::Content:Class.  

```
# Running:

E

Error:
ContentsHelperTest#test_content:
NoMethodError: undefined method `first' for ActionView::TestCase::Behavior::Content:Class
    content-bug.rb:49:in `test_content'

```

### System configuration
Rails 7.0, 7.1, Main

**Ruby version**:
ruby 3.2.2 (2023-03-30 revision e51014f9c0) +YJIT [x86_64-darwin19]

**Comment by akhilgkrishnan** [comment]
https://github.com/rails/rails/pull/49194#discussion_r1337940387 Looks like we added the Content class for the troubleshooting purpose.

**Comment by seanpdoyle** [comment]
One quick and dirty workaround for this particular name conflict would involve referencing mentions of `Content` as its fully qualified name: `::Content`. It's tedious and unexpected, but should resolve the issue.

I'm surprised that the conflict occurs at all, since the internal class is defined inside the `Behavior::` module, but I guess mixing that module in affects the namespace resolution hierarchy.

I'm curious what @rafaelfranca thinks about reverting the internal class to be anonymous.

**Comment by p8** [comment]
Maybe rename `ActionView::TestCase::Behavior::Content` to something like `RenderedContent` or `RenderedViewContent`, similar to `RenderViewCollection`?

**Comment by seanpdoyle** [comment]
@p8 I like that! I've opened https://github.com/rails/rails/pull/49856 to explore that further.

**Comment by rafaelfranca** [comment]
Does this really happen on Rails 7.0? There is no `ActionView::TestCase::Behavior::Content` class on that release

**Comment by ccasabona** [comment]
Thanks for fixing this.

The problem does not happen on 7.0.

Charlie
