### ISSUE TITLE
Setting marshalling_format_version in new_framework_defaults_7_1 does not work

### ISSUE THREAD

**Issue by tomhughes** [rails/rails#49827]
### Steps to reproduce
Setting `Rails.application.config.active_record.marshalling_format_version` to `7.1` in `config/initializers/new_framework_defaults_7_1.rb` does not successfully activate the new format.

To reproduce create a rails 7.0 app and upgrade it to 7.1 then uncomment the line and evaluate `ActiveRecord::Marshalling.format_version` in the console and it will still be `6.1`.

Only when you change `config/application.rb` to load the 7.1 default will `ActiveRecord::Marshalling.format_version` change.

### Expected behavior
Setting the value in `new_framework_defaults_7_1.rb` should work.

### Actual behavior
Setting the value in `new_framework_defaults_7_1.rb` does not work.

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
Can not reproduce. Can you create a sample app that reproduces and share?

**Comment by tomhughes** [comment]
Well I would have done but there's no template test case for something like that needs the whole rails stack... Let me see what I can do.

**Comment by fatkodima** [comment]
You can generate a new app with `rails _7.0.8_ new testapp`, make necessary modifications and push it to github.

**Comment by tomhughes** [comment]
It seems this is an interaction with the `delayed_job_active_record` gem and it doesn't happen if I remove that from our Gemfile...

**Comment by fatkodima** [comment]
I am sure you got this https://github.com/collectiveidea/delayed_job_active_record/pull/212

**Comment by tomhughes** [comment]
No because that was closed without being merged...

**Comment by fatkodima** [comment]
Read that PR description.
