### ISSUE TITLE
skip_before_action where an array is used for the :only option doesn't work after upgrading 7.0 -> 7.1

### ISSUE THREAD

**Issue by Cashaca** [rails/rails#49830]
### Steps to reproduce
```
class AdminController < ApplicationController
  before_action :authenticate_user!
end

class NewsletterPreferencesController < AdminController
skip_before_action :authenticate_user! , only: [:new, :create]
 def new
 end

 def create
 end

end

```
### Expected behavior
before_action authenticate_user! is skipped for the NewsletterPreferencesController new and create actions

### Actual behavior
before_action is not skipped

Using a separate line for each action without using only: [array] does work

This works
skip_before_action :authenticate_user! , only: :new
skip_before_action :authenticate_user! , only: :edit

So the root cause is that the :only option is no longer accepting an array of controller methods
...

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.1

**Comment by fatkodima** [comment]
Can you create a reproduction test script using this template - https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller_gem.rb ?

**Comment by Cashaca** [comment]
I will close this issue... I further narrowed it down in our own application where the bug only happens if one of the methods listed in the :only array is a non existing method. But I can not recreate it in the bug report template.

Thanks BTW for forcing me to spend 10min understanding how this template works! One extra skill under my belt ;-)

**Comment by fatkodima** [comment]
> Thanks BTW for forcing me to spend 10min understanding how this template works! One extra skill under my belt ;-)

You are welcome 😄
