### ISSUE TITLE
Inquiry About Reserved Keywords When Passing Variables to Translations

### ISSUE THREAD

**Issue by reckyy** [rails/rails#49879]
Hello, I would like to confirm two things regarding the reserved keywords as mentioned in the title.

1. The [document](https://railsguides.jp/i18n.html#%E8%A8%B3%E6%96%87%E3%81%AB%E5%A4%89%E6%95%B0%E3%82%92%E6%B8%A1%E3%81%99) states that the keywords `default` and `scope` are reserved. Are these the only ones? Recently, I used `object` as a variable name and was unable to pass the variable. Upon reviewing the code, I found the following line excluding reserved keywords.
https://github.com/ruby-i18n/i18n/blob/v1.14.1/lib/i18n/backend/base.rb#L57

`values = Utils.except(options, *RESERVED_KEYS) unless options.empty?`

https://github.com/ruby-i18n/i18n/blob/v1.14.1/lib/i18n.rb#L19-L34
```ruby
RESERVED_KEYS = %i[
    cascade
    deep_interpolation
    default
    exception_handler
    fallback
    fallback_in_progress
    fallback_original_locale
    format
    object
    raise
    resolve
    scope
    separator
    throw
  ]
```

2. The [document](https://railsguides.jp/i18n.html#%E8%A8%B3%E6%96%87%E3%81%AB%E5%A4%89%E6%95%B0%E3%82%92%E6%B8%A1%E3%81%99) mentions that:

> The `default` and `scope` keywords are reserved, and cannot be used as variables. Using them will result in an `I18n::ReservedInterpolationKey` exception.

However, in my case, using a reserved keyword did not trigger the `I18n::ReservedInterpolationKey` exception.

I have created a sample app for testing purposes.
https://github.com/reckyy/sample_for_i18n

I look forward to your confirmation on the above matters.

**Comment by fatkodima** [comment]
You need to pass extra keys additionally to reserved for this behavior to trigger, like: 
```ruby
I18n.t("key", scope: "something", foo: "bar")
``` 
Because otherwise the value returned as is.
See https://github.com/ruby-i18n/i18n/blob/7cf09474b77fd41e65d979134b0525f67cf371b0/lib/i18n/backend/base.rb#L57-L65

@radar Is this expected behavior? Because looks like a bug for me, but I am not sure. Can help with a PR, if this is a bug.

**Comment by radar** [comment]
@fatkodima I think not showing an error here is probably a mistake. If people are using reserved keys, i18n should alert them about this. Could you please submit a PR for this?

**Comment by fatkodima** [comment]
Sure, will try to do that tomorrow.
