### ISSUE TITLE
Usage of `normalizes` interacting with caching/dumping

### ISSUE THREAD

**Issue by mjankowski** [rails/rails#49871]
There's a [long history of issues](https://github.com/search?q=repo%3Arails%2Frails+no+_dump_data+for+class+proc&type=issues) that boil down to "ruby can't marshall procs". I don't know if this issue is in that category and is an expected shortcoming of `normalizes`, or if this should work and doesn't. Discovered the issue running inside a caching block, but attempted to distill down minimally in case below.

### Steps to reproduce

Attempt to cache or just `Marshal.dump` an AR object using `normalizes`. Example:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
  end
end

class User < ActiveRecord::Base
  normalizes :name, with: -> { _1.strip.downcase }
end

class BugTest < Minitest::Test
  def test_caching_normalized_record
    user = User.create(name: "First Name    ")

    assert_equal "first name", user.name
    assert_equal user.inspect, Marshal.load(Marshal.dump(user)).inspect
  end
end
```

### Expected behavior

Using `normalizes` should manipulate values when set, and not impact caching/dumping the object.

### Actual behavior

When `normalizes` is in use, an error is thrown:

> TypeError: no _dump_data is defined for class Proc

### System configuration
**Rails version**: 7.1 and/or `main` branch

**Ruby version**: 3.2.2

**Comment by jonathanhefner** [comment]
Adding `ActiveRecord.marshalling_format_version = 7.1` to the reproduction script fixes the error.

I'm inclined to say that is an acceptable limitation.  It is already advisable to migrate to `marshalling_format_version = 7.1`, so I'm not really in favor of complicating the implementation of `NormalizedValueType` just to support the old `Marshal` format.

**Comment by mjankowski** [comment]
> Adding `ActiveRecord.marshalling_format_version = 7.1` to the reproduction script fixes the error.

Confirmed this locally, thanks for quick response both of you!

> I'm inclined to say that is an acceptable limitation. It is already advisable to migrate to `marshalling_format_version = 7.1`, so I'm not really in favor of complicating the implementation of `NormalizedValueType` just to support the old `Marshal` format.

I agree with this -- I didn't realize these two issues were linked; and I was doing the "start using normalizes in some places" portion of a rails upgrade before completing all the config update elements, including the marshalling format change.

Do you think any of:

- Add docs around this requirement to API docs?
- Add a note in upgrading docs?
- Add code which detects attempting to use normalizes without updating the marshall format version?

...would be useful to future people encountering this? Or is this issue conversation probably enough?

**Comment by jonathanhefner** [comment]
> Do you think any of:
>
>     * Add docs around this requirement to API docs?
>
>     * Add a note in upgrading docs?
>
>     * Add code which detects attempting to use normalizes without updating the marshall format version (and warns)?
>
>
> ...would be useful to future people encountering this? Or is this issue conversation probably enough?

I'm not sure that code emitting warning would be feasible because an app may not actually be marshalling models (e.g. not using caching, or using the `:message_pack` serializer instead).  We could try to catch the `TypeError`, determine if it's due to `normalizes`, and then raise a better error; but that seems complicated for very little gain.

There doesn't seem to be a good spot in the upgrading docs for such a note, so I will add one to the `normalizes` API docs: #49876.  It's not ideal, but we want to eventually remove the old Marshal format (and that caveat with it).
