### ISSUE TITLE
Trying to convert a 7.0 serialized column to 7.1 and I'm lost!

### ISSUE THREAD

**Issue by salex** [rails/rails#49875]
### Steps to reproduce
I upgraded to rails 7.11 from 7.0.5  and can't figure out how to get  an active record field column to serialize

Understand that serialization has change but can't find any clues in the issues or guides on what I need the change

I had 
```ruby
class Group < ApplicationRecord
 ...
      serialize :settings, ActiveSupport::HashWithIndifferentAccess
...
```
Which give error (in console)

```ruby
.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/psych-5.1.1.1/lib/psych/class_loader.rb:99:in `find': Tried to load unspecified class: ActiveSupport::HashWithIndifferentAccess (Psych::DisallowedClass)
```

I assume they added a `coder` field and ActiveSupport::HashWithIndifferentAccess is not a coder.

I tried to parse the YAML in the six or so records I have and it errors and just get Psych nodes

What am I missing?  Any suggestion?

I've been meaning to convert the fields to JSON but have not got around to it. Thankfully I upgraded in  a new branch. Guess I could put a hashes in ruby conversion file and replace the fields. There are about 25 elements in the settings field.

### System configuration
**Rails version**:7.1.1

**Ruby version**: 3.0.1

**Comment by fatkodima** [comment]
This https://stackoverflow.com/questions/74312283/tried-to-load-unspecified-class-activesupporttimewithzone-psychdisallowed ?

**Comment by salex** [comment]
Thank you.

I vaguely remember this with the last major release. Guess I'll try to remember the next time I do an upgrade to not replace any major files to say N and look what has been changed/added before I say Y!

Worked fine. A quick run thru the rest looks ok,

Thank you.

**Comment by salex** [comment]
When you're a wisker away for 80, you tend to forget stuff!
