### ISSUE TITLE
Update dev dependencies install docs wrt nodesource script deprecation

### ISSUE THREAD

**Issue by zzak** [rails/rails#49900]
In the `development_dependencies_install.md` guide here:
https://github.com/rails/rails/blob/a6099ed2b7a544d8fe67688e8a0f9237847404ee/guides/source/development_dependencies_install.md?plain=1#L126

As well as docked:
https://github.com/rails/docked/blob/0cb4cb2c72d0079885b50ec0eb6f94651e5a64f9/Dockerfile#L8-L13

Since the nodesource install script is deprecated, it can generate some pretty huge warning until it's eventually deactivated.

New instructions require installing a debian repository on Ubuntu:
https://github.com/nodesource/distributions#installation-instructions

**Comment by Rushi0508** [comment]
I can do this. Please assign me the issue @zzak

**Comment by zzak** [comment]
@Rushi0508 Sorry, I think there is already a PR to address this, closing since the rails/rails PR was merged.
