### ISSUE TITLE
Failing to upgrade from 7.1.rc2 to 7.1: stack level too deep

### ISSUE THREAD

**Issue by devaniljr** [rails/rails#49929]
Everytime I try to upgrade from Rails 7.1.rc2 to 7.1.0 or 7.1.1 I get an error `stack level too deep`

The looping starts here:

`activesupport (7.1.1) lib/active_support/core_ext/object/json.rb`

```rb

class Object
  def as_json(options = nil) # :nodoc:
    if respond_to?(:to_hash)
      to_hash.as_json(options)
    else
      instance_values.as_json(options)
    end
  end
end
```
```rb
    else
      self
    end
    result = {}
    subset.each do |k, v|
      result[k.to_s] = options ? v.as_json(options.dup) : v.as_json
    end
    result
  end
end
```

`block in as_json`

Using the gem better errors, I tried to see if there is any more obvious origin. It seems to start in something related to database. 

![image](https://github.com/rails/rails/assets/7834279/f0ed57d6-c391-4e5e-9638-be90d4704a40)

**Comment by fatkodima** [comment]
Can you create a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/generic_gem.rb template?

**Comment by devaniljr** [comment]
I was able to identify the root cause of the issue, and it turned out not to be related to Rails. The problem stemmed from the 'meta_request' gem. I'm closing this issue now.
