### ISSUE TITLE
intermittent test failure in connection_pool_test

### ISSUE THREAD

**Issue by fredwillmore** [rails/rails#49927]
### Steps to reproduce
in `activerecord` directory, run bin/test test/cases/connection_pool_test.rb:218
About half the time the test on line 244 fails.
I was able to get the test to pass consistently by changing the `@idle_since` value from 0.2 to 0.02000000001 seconds ago. I think the comparison between the configured idle_timeout and the actual idle time was suffering from a floating-point precision error.

### Expected behavior
The test should reliably pass.

### Actual behavior
The test fails intermittently

### System configuration 
MacOS 13.6
Apple M2 Pro

**Rails version**: 7.2.0.alpha

**Ruby version**: 3.2.2

**Comment by paulreece** [comment]
I just ran this 5 times in a row and it passed every time. 

Can you make a reproduction script?

**Comment by fredwillmore** [comment]
This issue seems to have gone away on its own - I'm hammering the test that had the issue before:
bin/test test/cases/connection_pool_test.rb:218
but it passes every time. I'm a new contributor, just setting up my environment, so maybe there was some process that just wasn't complete. The only thing I did between originally seeing and reporting the issue was to create a copy of the bug report template in guides/bug_report_templates/active_record_main.rb and run it locally.
