### ISSUE TITLE
Rails 5.2 to 6 creates new migrations

### ISSUE THREAD

**Issue by MSCAU** [rails/rails#49922]
### Steps to reproduce
Upgrade Rails from 5.2 to 6.0 using `rails app:update`, then `bundle update`, then start the server and realise that it won't run. because there are pending migrations with today's date. The two migrations are:

`<timestamp>_add_service_name_to_active_storage_blobs.active_storage.rb`
and
`<timestamp>_create_active_storage_variant_records.active_storage.rb`

### Expected behavior
I'd expect some mention of this in the relevant upgrade guide: https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-2-to-rails-6-0

### Actual behavior
There is no mention of this, so the inability to access my app without running them comes as an unpleasant surprise. The same is true of other upgrades. The current guide cites the word 'migration' 9 times but none seem to pertain to the actions I am flagging.

**Comment by MSCAU** [comment]
FWIW, there is a StackOverflow page which mentions someone else being caught off guard by this: https://stackoverflow.com/questions/59857774/pgundefinedtable-error-relation-active-storage-blobs-does-not-exist

**Comment by fatkodima** [comment]
Rails < 7.1 is not supported, see https://guides.rubyonrails.org/maintenance_policy.html. Just run `bin/rails db:migrate`.
