### ISSUE TITLE
Rails.cache.redis is returning ConnectionPool instead of Redis object

### ISSUE THREAD

**Issue by drgcms** [rails/rails#49935]
### Steps to reproduce
Update from Rails 7.0.x to 7.1.1

```ruby
Rails.cache.redis.del(key) 
```

### Expected behavior
success

### Actual behavior
`cache_clear': undefined method `del' for #<ConnectionPool:0x00007fec5c7b1150 @size=5, @timeout=5, @auto_reload_after_fork=true, @available=#<ConnectionPool::TimedStack:0x00007fec5c7b1100 @create_block=#<Proc:0x00007fec5c914650 /home/rails/drg_cms_test/vendor/ruby/3.2.0/gems/activesupport-7.1.1/lib/active_support/cache/redis_cache_store.rb:150>, @created=0, @que=[], @max=5, @mutex=#<Thread::Mutex:0x00007fec5c9145d8>, @resource=#<Thread::ConditionVariable:0x00007fec5c914588>, @shutdown_block=nil>, @key=:"pool-4820", @key_count=:"pool-4820-count"> (NoMethodError)

### System configuration
Rails 7.1.1
Ruby 3.2.2

I inspected the code and it looks that this code is picking some default settings, which were not used in 7.0.x tree.

```ruby
        # around line 150 in ../active_support/cache/redis_cache_store.rb
        if pool_options = self.class.send(:retrieve_pool_options, redis_options)
          @redis = ::ConnectionPool.new(pool_options) { self.class.build_redis(**redis_options) }
        else
          @redis = self.class.build_redis(**redis_options)
        end
```

My redis configuration:
```ruby
 config.cache_store = :redis_cache_store, { url: "redis://localhost:6379/15", expires_in: 1.day }
```

Reverting to 7.0.8 and it works as expected.

by
TheR

**Comment by fatkodima** [comment]
This is expected. You need to pass `pool: false` to the configuration. See https://github.com/rails/rails/pull/45235
