### ISSUE TITLE
Cannot create test database using db:create task.

### ISSUE THREAD

**Issue by marlinpierce** [rails/rails#49938]
### Steps to reproduce

From the command line:

    RAILS_ENV=test bundle exec rails db:create

also for

    RAILS_ENV=test bundle exec rake db:create

### Expected behavior

Should create the test database after it has been dropped.

### Actual behavior

Error message:

> ActiveRecord::NoDatabaseError: Unknown database 'ac_test'

### System configuration

    Rails 6.1.7.6

    ruby 2.7.6p219

**Comment by fatkodima** [comment]
Only rails 7.1 is supported for bug fixes (see https://guides.rubyonrails.org/maintenance_policy.html). If you would verify that there is a problem in rails 7.1+ and provide us a reproduction test script or app, I will be happy to reopen.
