### ISSUE TITLE
superclass mismatch for class ProfileReporter (TypeError)

### ISSUE THREAD

**Issue by lowercase** [rails/rails#49949]
### Steps to reproduce
install rails-7.1.1 railties-7.1.1

after `rails test` get error:
```
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.1/lib/minitest/rails_plugin.rb:28:in `<module:Minitest>': superclass mismatch for class ProfileReporter (TypeError)
        from /app/vendor/bundle/ruby/3.2.0/gems/railties-7.1.1/lib/minitest/rails_plugin.rb:7:in `<main>'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
        from /app/vendor/bundle/ruby/3.2.0/gems/minitest-5.20.0/lib/minitest.rb:121:in `block in load_plugins'
        from /app/vendor/bundle/ruby/3.2.0/gems/minitest-5.20.0/lib/minitest.rb:115:in `each'
        from /app/vendor/bundle/ruby/3.2.0/gems/minitest-5.20.0/lib/minitest.rb:115:in `load_plugins'
        from /app/vendor/bundle/ruby/3.2.0/gems/minitest-5.20.0/lib/minitest.rb:144:in `run'
        from /app/vendor/bundle/ruby/3.2.0/gems/minitest-5.20.0/lib/minitest.rb:86:in `block in autorun'
```

### Expected behavior
no error

### Actual behavior
raises error

### System configuration
**Rails version**:
7.1.1
**Ruby version**:
3.2.2

**Comment by fatkodima** [comment]
Can you provide the exact steps I need to do to reproduce the issue? Because with the steps provided I saw no issues.

**Comment by lowercase** [comment]
Yes, you are right. To get this error you need to add the minitest-profile gem.
docker run --rm --network host -it ruby:3.2.2-alpine3.18 sh
# inside container:
gem update --system 3.4.21
apk add git make gcc musl-dev
gem install rails -v 7.1.1
rails new tmp
cd tmp
sed -i 's/gem "tzinfo-data".*$/gem "tzinfo-data"/' Gemfile
sed -i '/group :test do/a   gem "minitest-profile"' Gemfile
bundle install
rails test

**Comment by fatkodima** [comment]
You should use the built-in rails profiling (https://github.com/rails/rails/pull/49082). It does not work with that gem

**Comment by lowercase** [comment]
thanks
