### ISSUE TITLE
Routing `defaults:` values aren't overridden by request's values

### ISSUE THREAD

**Issue by seanpdoyle** [rails/rails#49942]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index", defaults: { value: "original" }
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: params[:value]
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/?value=override"

    assert_not_equal "original", last_response.body
    assert_equal "override", last_response.body
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior

The `"override"` value passed as the request's `?value=override` query parameter would override the `defaults: { value: "original" }` option declared as part of the route when accessed by the `params[:value]` helper in the controller.

That String would then be rendered as the response's body.

### Actual behavior

The `"original"` String that's assigned as part of the route-based `defaults: { value: "original" }` option isn't being overridden by a request-based value from the `?value=override` query parameter.

### System configuration
**Rails version**: `main@8d778e0708`

**Ruby version**: `3.2.0`

**Comment by adrianna-chang-shopify** [comment]
This is intentional, from [the docs](https://guides.rubyonrails.org/routing.html#defining-defaults):
> You cannot override defaults via query parameters - this is for security reasons. The only defaults that can be overridden are dynamic segments via substitution in the URL path.
