### ISSUE TITLE
Using empty string for ActionView `template_path`

### ISSUE THREAD

**Issue by mwilde345** [rails/rails#49940]
I just upgraded to Rails 7 and I had to make a change to my template paths that leaves me a bit confused.

I had to change `'./'` custom template path to `''` empty string in order for ActionView to find the correct template.

### Steps to reproduce

Project structure:
```
app
- members
- - member_mailer.rb
- - invite_member_email.erb
```

`member_mailer.rb`:
```
module Members
  class MemberMailer < ActionMailer::Base
    append_view_path Rails.root.join('app', 'members')

    default template_path: './'
    default template_name: 'invite_member_email'

    def invite_email
      mail(to: params[:to], subject: params[:subject])
    end
  end
end
```

### Expected behavior
ActionView finds the `invite_member_email` template in `app/members`

### Actual behavior
```
ActionView::MissingTemplate:
    Missing template .//invite_member_email with "mailer".

    Searched in:
      * "./"
```

So I now have to use an empty string as template_path so it will search in `app/members` for `/invite_member_email`. This makes for a bit of code that is confusing to read initially. Is this a bug?

If i leave out `template_path` completely, then:

```
  ActionView::MissingTemplate:
    Missing template members/member_mailer/invite_member_email with "mailer".

    Searched in:
      * "members/member_mailer"
```

It looks in the default path ActionView would expect. My custom path `app/members` is ignored now. Same result with `prepend_view_path` and `append_view_path`. Is `template_path` required when `template_name` is specified? Don't see that called out here: https://guides.rubyonrails.org/action_mailer_basics.html#mailer-views

### System configuration
**Rails version**: 7.0

**Ruby version**: 2.7.5

**Comment by fatkodima** [comment]
Curious, why are you not using `views/mailers/` for templates? Can you verify the error persists on rails 7.1 or `main`? If so, it would be helpful if you can create a sample app that reproduces an issue and share with us.

**Comment by mwilde345** [comment]
directory structure is an artifact of old codebase that I came in to upgrade. No reason not to use `views/mailers` aside from just trying to get things working as they already were in the legacy directory structure. Let me get that other info for you.

**Comment by mwilde345** [comment]
"issue" remains in Rails 7.1.2 and Ruby 3.1.4

I don't have the time to prioritize a small mockup or pursue a solution right now so leaving it there as empty string for now.
