### ISSUE TITLE
Duplicate database.yml

### ISSUE THREAD

**Issue by amy-hs** [rails/rails#49959]
### Question
Hello! We have an internal gem for replicas, but are working to migrate off of that to native Rails. Is it possible to have 2 different `database.yml` files (i.e. `database.yml` and `database_old.yml`) and conditionally load one based on some kind of environment toggle? Thanks!

### System configuration
**Rails version**: 6.0.6.1

**Ruby version**: 3.0.6

**Comment by fatkodima** [comment]
Hey @amy-hs we reserve the Rails Issues tracker for bugs in the framework as we don't have the bandwidth to offer application support. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help with your application. Thanks for understanding.
