### ISSUE TITLE
net.get("/") hangs in Rails::Engine::CommandsTest test_server_command_broadcast_logs

### ISSUE THREAD

**Issue by fredwillmore** [rails/rails#49961]
### Steps to reproduce
cd railties
bin/test test/engine/commands_test.rb:62

### Expected behavior
test should execute

### Actual behavior
test hangs on line 68
net.get("/")
I can see that the process with pid is running, but it doesn't seem to be reachable. I think I must have a system configuration issue but I don't know how to resolve it..

### System configuration
Apple M2 Pro
MacOs 13.6

**Rails version**:7.2.0.alpha

**Ruby version**: 3.2.2

**Comment by yahonda** [comment]
This test passes at both Rails CI and my environment so it needs some more information.

```ruby
$ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
$ bin/test test/engine/commands_test.rb:62
Run options: --seed 39469

# Running:

.

Finished in 3.369073s, 0.2968 runs/s, 1.7809 assertions/s.
1 runs, 6 assertions, 0 failures, 0 errors, 0 skips
$
```
