### ISSUE TITLE
Using redis_cache_store, Rails.cache.write_multi does not set TTL correctly

### ISSUE THREAD

**Issue by fcbr** [rails/rails#49973]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "redis"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_redis_ttl

    redis = Redis.new
    cs = ActiveSupport::Cache.lookup_store(:redis_cache_store)
    cs.write('foo1', 'bar', expires_in: 10)
    cs.write_multi({ 'foo2' => 'bar' }, expires_in: 11)

    assert redis.ttl('foo1') != -1
    assert redis.ttl('foo2') != -1
  end
end
```

### Expected behavior

When using `Rails.cache.write_multi` with `expires_in`, the TTL of the keys should be set, just like `Rails.cache.write`.

### Actual behavior

No TTL is set (`redis.ttl key` returns -1).

### System configuration
**Rails version**: `main`, `7-0-stable`, `7-1-stable`

**Ruby version**: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin21]

**redis**: 6.2.8

**Comment by fatkodima** [comment]
Confirmed and identified the root-cause. Going to open a PR.
