### ISSUE TITLE
rails 7.1 active_record column serialization documentation

### ISSUE THREAD

**Issue by salex** [rails/rails#49978]
### Steps to reproduce
I've  upgraded an 7.0.8 to 7.1.1 but I'm stuck trying to understand what has changed in Active Record Column serialization and how if move from 7.0 implementations (or earlier ) to the current.

I  probably have updated code going back to rails 5 or earlier with stuff like:

```ruby
 serialize :column, type: Hash
 # or older
serialize :column, Hash
serialize :column, Array
serialize :column, type: Array
serialize :settings, type: ActiveSupport::HashWithIndifferentAccess 
serialize :preferences, coder: JSON
```
The writing is on the wall to move everything to JSON YAML is dead. That would require a conversion script getting all to stuff to JSON, changing all the fields to coder JSON and replacing/importing. Maybe a couple thousand records and some time.

### Expected behavior

Is there any document that gives a little more documentation on column serialization? What :coder are available, what :type works (or worked)

I can keep 7.0 defaults for now, but the upgrade was a waste of time with not knowing what I was trying to do - upgrade!

### System configuration
**Rails version**:
7.0.8 to 7.1.1

**Ruby version**:
3.0.1

**Comment by fatkodima** [comment]
Hey @salex, we reserve the Rails Issues tracker for bugs in the framework as we don't have the bandwidth to offer application support. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help with your application. Thanks for understanding.

As for your question, try to also look at https://api.rubyonrails.org and read the sources.
