### ISSUE TITLE
has_one ... dependent: :destroy results in destruction of existing record's association on call to 'new'

### ISSUE THREAD

**Issue by nemesit** [rails/rails#49980]
### Steps to reproduce

1. have a Model with a has_one: ..., dependent: :destroy relation
2. Save record with associated record to database
3. call new on the Model with an id of a persisted record and attributes for the has_one association
4. rails will destroy the association record for the persisted record instead of just creating an instance from the parameters

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  
  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :items, force: true  do |t|
  end
  
  create_table :categories, force: true  do |t|
    t.integer :item_id
    t.integer :some_attribute
  end
  
end

class Item < ActiveRecord::Base
  has_one :category, dependent: :destroy
  accepts_nested_attributes_for :category, allow_destroy: true
end

class Category < ActiveRecord::Base
  belongs_to :item
  validates :item, presence: true
end

class BugTest < Minitest::Test
  def test_new_destroying_records
    item = Item.create!
    category = item.create_category!
    
    assert_equal 1, Item.count
    assert_equal 1, Category.count
    
    # .new should in no case result in the destruction of records
    Item.new({id: item.id, category_attributes: { some_attribute: 1 }})
    
    assert_equal 1, Item.count     # success
    assert_equal 1, Category.count # fail
  end
end
```

### Expected behavior
A new instance should be created, no database access at all on Item.new

### Actual behavior
The existing category on the existing item gets destroyed.

### System configuration
**Rails version**: Rails 7.0.8

**Ruby version**: ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin21]

**Comment by fatkodima** [comment]
This is a documented behaviour of a `has_one`, see https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_one

> **association=(associate)**
> Assigns the associate object, extracts the primary key, sets it as the foreign key, and saves the associate object. To avoid database inconsistencies, permanently deletes an existing associated object when assigning a new one, even if the new one isn’t saved to database.

**Comment by nemesit** [comment]
oh god, why would anyone prefer to cause database inconsistencies deliberately in order to prevent database inconsistencies?

**Comment by zzak** [comment]
That is just how things work, if you need referential integrity you can apply a constraint to your database.
