### ISSUE TITLE
Expect `ActiveRecord::Relation#order` to take `Arel::Attributes::Attribute` and properly `reference` joined table

### ISSUE THREAD

**Issue by mylesboone** [rails/rails#49999]
### Steps to reproduce

```ruby
Topic.includes(:posts).order(Post.arel_table[:created_at])
```

### Expected behavior

```ruby
Topic.includes(:posts).order(Post.arel_table[:created_at])
# SELECT "topics"."id" AS t0_r0..."posts"."id" AS t1_r0...FROM "topics" LEFT OUTER JOIN "posts" ON "posts"."topic_id" = "topics"."id" ORDER BY "posts"."created_at"
```

### Actual behavior

```ruby
Topic.includes(:posts).order(Post.arel_table[:created_at])
# SELECT "topics".* FROM "topics" ORDER BY "posts"."created_at"
# ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "posts"
```

### System configuration
**Rails version**: 7.1.1

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
`Topic.includes` does not do `JOIN` in your case, but 2 separate queries and `order` is relevant to the parent query (the one that gets topics). Did you mean `.eager_load`? But in this case it works for me.

Can you create a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb template?

**Comment by paulreece** [comment]
So you can use a string within `order` to get your desired result:
```ruby
 Post.includes(:authors).order('authors.created_at DESC')
```

You can see that it is intended behavior to use strings with this method here:

https://github.com/rails/rails/blob/c37efa154e39aba9aba9132d983cd7f908c44e50/activerecord/lib/active_record/relation/query_methods.rb#L565-L582

**Comment by fatkodima** [comment]
Can you guys provide a reproducible test script, cause works on my machine.

**Comment by mylesboone** [comment]
@fatkodima thanks for your quick response --

The root of this issue is that it would make sense for `ActiveRecord::Relation#order` to properly do the join if `order` is passed a `Arel::Attributes::Attribute` for a relation's table (where the relation is `include`'d already)

Like you said, explicitly `eager_load`'ing the relation will work, but shouldn't (in my mind) be necessary, and instead `ActiveRecord::Relation` could be written to automatically do the `LEFT OUTER JOIN` when necessary.  

FWIW - I plan to implement this once #50000  goes in (since #50000 touches the methods this would need to change).

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_should_not_raise_sql_error
    post = Post.create!
    post.comments << Comment.create!

    assert_equal 1, Post.includes(:comments).order(Comment.arel_table[:id]).to_a.size
    # This currently will give ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR
  end
end
```
