### ISSUE TITLE
BuildKite -> GitHub Actions?

### ISSUE THREAD

**Issue by northeastprince** [rails/rails#50021]
We're already using GHA for some CI steps, but I'm wondering if there's a specific reason why we haven't moved the rest over or if someone just hasn't gotten around to that, in which case I'd be happy to work on a PR.

**Comment by akhilgkrishnan** [comment]
Hey @northeastprince , we reserve the Rails Issues tracker for bugs in the framework. Please use the [Rails Discussion forum](https://discuss.rubyonrails.org/) for asking questions or doubts.

**Comment by skipkayhil** [comment]
> We're already using GHA for some CI steps, but I'm wondering if there's a specific reason why we haven't moved the rest over or if someone just hasn't gotten around to that

To actually answer the question, from what I understand the plan is to eventually move more things into buildkite rather than out of it.

**Comment by northeastprince** [comment]
Ah, I couldn't find anything on that. What's the reason for that? I'd figure a more integrated system would be better.

**Comment by skipkayhil** [comment]
I think there has been discussion about it on discord, but I haven't been able to quickly find it

**Comment by simi** [comment]
> I think there has been discussion about it on discord, but I haven't been able to quickly find it

@skipkayhil maybe this one https://discord.com/channels/849034466856665118/974004968015155230/1066047917183467540

> If we can break the railties suite in many workers without needing to do crazy things, and the github actions can handle our size, I'd say go for it.

:information_source: The outcome of the discussion with Rafael França was it is worth to try to port `railities` as starting point.

**Comment by skipkayhil** [comment]
Right, and I think the additional constraint was we don't want PRs' Action list to have ~100 items because it makes it really hard to grok.

**Comment by hahmed** [comment]
Here is my attempt to move everything to GitHub Actions - https://github.com/rails/rails/compare/main...hahmed:rails:ha/github-ci you can see in this list https://github.com/hahmed/rails/actions/runs/6461932101 there are quite a few jobs without splitting up the railties stuff (going to revisit the railties tests soon).
