### ISSUE TITLE
Incorrect casting for mysql boolean bound value for JSON queries

### ISSUE THREAD

**Issue by the-spectator** [rails/rails#50024]
Incorrect casting for MySQL boolean bound value for JSON queries. Mysql doesn't treat '0' or '1' as a boolean in the context of the JSON field. Reference: https://bugs.mysql.com/bug.php?id=90469

Previously, rails used to cast boolean values as 'TRUE' or 'FALSE' but after change introduced in 1dc69cab761fbfd46142f70d8ea58a41c6a12c12, this behavior has changed, and boolean casted values are converted into '1' or '0'.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  ruby "3.2.2"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # working version
  # gem "rails", "~> 6.1"
  # not working, broken in 1dc69cab761fbfd46142f70d8ea58a41c6a12c12
  gem "rails", git: "https://github.com/rails/rails", branch: "main"
  gem "trilogy"
  gem "mysql2"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
# ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.establish_connection(
  adapter: "mysql2",
  database: "rails_dev",
  username: "root",
  password: "root"
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :rails_bugs, force: true do |t|
    t.json :metadata
  end
end

class RailsBug < ActiveRecord::Base
  store_accessor :metadata, :is_bug

  scope :by_bug_value, ->(value) { where("JSON_EXTRACT(metadata, '$.is_bug') = ?", value) }
end

class BugTest < Minitest::Test
  def test_casting_boolean
    RailsBug.create(is_bug: true)
    RailsBug.create(is_bug: false)
    RailsBug.create(is_bug: true)
    RailsBug.create(is_bug: true)

    assert_equal 3, RailsBug.by_bug_value(true).count
  end
end

```

### Expected behavior

Generated SQL
```sql
SELECT COUNT(*) FROM `rails_bugs` WHERE (JSON_EXTRACT(metadata, '$.is_bug') = '1')
```

### Actual behavior

```
F

Failure:
BugTest#test_casting_boolean [mysql_json_bool_bug.rb:52]:
Expected: 3
  Actual: 0
```

Generated SQL
```sql
SELECT COUNT(*) FROM `rails_bugs` WHERE (JSON_EXTRACT(metadata, '$.is_bug') = TRUE)
```

### System configuration
**Rails version**:
main

**Ruby version**:
3.2.2

**Comment by byroot** [comment]
So this is a duplicate of https://github.com/rails/rails/issues/44312

We can't blindly pass the value as a boolean as it would open the door to a security vulnerability, because MySQL in the presence of conflicting types resort to casting both sides to numerics.

```
mysql> select "foo" = FALSE;
+---------------+
| "foo" = FALSE |
+---------------+
|             1 |
+---------------+
1 row in set, 1 warning (0.00 sec)
```

e.g. `"foo" = FALSE` translate to `0 = 0`. So in the case of something like `WHERE secret_token = ?`, if an attacker can sneak a `false` they can extract lots of information they shouldn't have access to.

In your specific case I recommend to rewrite your scope like this:

```ruby
scope :by_bug_value, ->(is_bug) {
  if is_bug
    where("JSON_EXTRACT(metadata, '$.is_bug') = TRUE")
  else
    where("JSON_EXTRACT(metadata, '$.is_bug') = FALSE")
  end
}
```

It's unfortunate, but MySQL casting rules don't leave us much choice.

**Comment by the-spectator** [comment]
Thanks for the explanation @byroot. It's unfortunate but security takes precedence over convenience.
