### ISSUE TITLE
edgeapi.rubyonrails.org not on latest commit

### ISSUE THREAD

**Issue by northeastprince** [rails/rails#50027]
#49989 fixes a typo in a comment, and was merged 3 days ago, but the [Edge API Docs](https://edgeapi.rubyonrails.org) don't show the fix. It seems to be hosted on a DigitalOcean server, and I assume it gets manually updated given the problem. Maybe [a script that continuously pulls this repo](https://github.com/basecamp/kamal-skiff/blob/main/lib/skiff/templates/serve) or some other solution to keep it up-to-date would be beneficial?

**Comment by skipkayhil** [comment]
https://github.com/rails/rails-docs-server
The repo is here, it usually does get updated automatically but sometimes it breaks. I'll see if I can get some eyes on the problem

**Comment by Rushi0508** [comment]
Assign me the issue. I can do it.

**Comment by skipkayhil** [comment]
So I just looked into this and #49989 is properly showing up here: https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-fields_for

There happens to be the exact same paragraph here: https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-fields_for which I've submitted a PR to update here: #50134

Closing this as I don't see anything wrong with the docs auto updating
