### ISSUE TITLE
Not possible to issue a deprecation warning from a template?

### ISSUE THREAD

**Issue by jagthedrummer** [rails/rails#50047]
### Steps to reproduce

I'm working on a gem that provides some partials that apps can use and I'm trying to figure out how to warn users about deprecations in the options they should pass to a partial.

For instance an app might have a template at `app/views/home/index.html.erb` that does this:

```erb
<%= render 'my_gem/a_partial', some_option: true %>
```

Then in the gem partial I'm trying to do this:

```erb
<%
if defined?(some_option)
  ActiveSupport::Deprecation.warn(
    "`some_option` is deprecated." +
    "Please use `new_option` instead."
  )
  new_option = some_option
end
%>
```

Detecting the deprecated option and reassigning it to the new option works as expected but the deprecation message points to the wrong place.

Here's an app that illustrates the issue: https://github.com/jagthedrummer/rails_deprecation_test

### Expected behavior

I would expect the deprecation warning to point to the template that called the partial that's raising the deprecation.

```
DEPRECATION WARNING: `deprecated_option` is deprecated. Please use `new_option` instead.
  (called from app/views/home/index.html.erb:1)
```

### Actual behavior

Instead it points deep into rail internals:

```
DEPRECATION WARNING: `deprecated_option` is deprecated. Please use `new_option` instead.
  (called from public_send at .../actionview-7.0.8/lib/action_view/base.rb:244)
```

If I inspect `caller` inside the gem partial I can see that the calling template is in the callstack and is one frame ahead of the line in `action_view/base.rb` that ends up being reported.

```
# snip
./app/views/home/index.html.erb:4:in `_app_views_home_index_html_erb___914303725008310334_29160'
.../actionview-7.0.8/lib/action_view/base.rb:244:in `public_send'
# snip
```

It just seems like the template is somehow filtered from the "deprecation stack". I've tried calling `Rails.backtrace_cleaner.remove_silencers!` immediately before calling the partial but that doesn't seem to have any effect. It's like the deprecation system just doesn't see `.erb` files.

### System configuration

**Rails version**: 7.0.8

**Ruby version**: 3.2.1

**Comment by fatkodima** [comment]
I was able to locally fix this problem with the following change:
```diff
diff --git a/activesupport/lib/active_support/deprecation/reporting.rb b/activesupport/lib/active_support/deprecation/reporting.rb
index 220404464f..cd719c964e 100644
--- a/activesupport/lib/active_support/deprecation/reporting.rb
+++ b/activesupport/lib/active_support/deprecation/reporting.rb
@@ -142,7 +142,8 @@ def extract_callstack(callstack)
           return _extract_callstack(callstack) if callstack.first.is_a? String

           offending_line = callstack.find { |frame|
-            frame.absolute_path && !ignored_callstack(frame.absolute_path)
+            path = frame.absolute_path || frame.path
+            path && !ignored_callstack(path)
           } || callstack.first

           [offending_line.path, offending_line.lineno, offending_line.label]
@@ -164,7 +165,7 @@ def _extract_callstack(callstack)
         RAILS_GEM_ROOT = File.expand_path("../../../..", __dir__) + "/"

         def ignored_callstack(path)
-          path.start_with?(RAILS_GEM_ROOT) || path.start_with?(RbConfig::CONFIG["rubylibdir"])
+          path.start_with?(RAILS_GEM_ROOT) || path.start_with?(RbConfig::CONFIG["libdir"])
         end
     end
   end
```

In my local env, 
`rubylibdir` is `"/Users/fatkodima/.asdf/installs/ruby/3.2.2/lib/ruby/3.2.0"` and
`libdir` is `"/Users/fatkodima/.asdf/installs/ruby/3.2.2/lib"` and gems are installed in `/Users/fatkodima/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/`, so `libdir` seems more appropriate.

What I did not get is why for callframe like `/Users/fatkodima/Desktop/rails_deprecation_test/app/views/home/index.html.erb:4:in `_app_views_home_index_html_erb__1197503666944623778_20940'` I got `nil` for `absolute_path` while a correct value for `path` ? 🤔 

@byroot Can you help with this?

**Comment by byroot** [comment]
👀

**Comment by byroot** [comment]
Right, so code generated with `eval` can't have an absolute path, so I think your fix is almost correct, as we'd need to check `loc.absolute_path || loc.path`.

**Comment by gazayas** [comment]
Writing just to mention that I I'm also getting `actionview-7.0.8/lib/action_view/base.rb:244` in the logs by reproducing the steps, and that @fatkodima's fix worked for me as well.

I noticed this issue was happening in the controller as well.

I took @jagthedrummer's example a little further in this app: https://github.com/gazayas/deprecation_test

I found that wrapping the warning message in a helper returns the correct paths.


```ruby
module ApplicationHelper
  def deprecation_warning(message)
    ActiveSupport::Deprecation.warn(message)
  end
end
```

```ruby
class HomeController < ApplicationController
  def index
    ActiveSupport::Deprecation.warn("Does not return proper file path")
    helpers.deprecation_warning("Returns proper file path")
  end
end
```

And in `app/views/home/index.html.erb:`
```ruby
<%
  ActiveSupport::Deprecation.warn("Does not return proper file path")
  deprecation_warning("Returns proper file path")
%>
```

This gives me the following logs.
```
Processing by HomeController#index as HTML
DEPRECATION WARNING: Does not return proper file path (called from send_action at /home/gazayas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionpack-7.0.8/lib/action_controller/metal/basic_implicit_render.rb:6)
DEPRECATION WARNING: Returns proper file path (called from index at /home/gazayas/ror/deprecation_test/app/controllers/home_controller.rb:4)
  Rendering layout layouts/application.html.erb
  Rendering home/index.html.erb within layouts/application
DEPRECATION WARNING: Does not return proper file path (called from public_send at /home/gazayas/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.8/lib/action_view/base.rb:244)
DEPRECATION WARNING: Returns proper file path (called from _app_views_home_index_html_erb__3368049221796106999_21120 at /home/gazayas/ror/deprecation_test/app/views/home/index.html.erb:3)
  Rendered home/index.html.erb within layouts/application (Duration: 1.4ms | Allocations: 580)
  Rendered layout layouts/application.html.erb (Duration: 71.0ms | Allocations: 33375)
Completed 200 OK in 81ms (Views: 72.7ms | ActiveRecord: 0.0ms | Allocations: 37551)
```

**Comment by jagthedrummer** [comment]
Thanks for the quick fix!
