### ISSUE TITLE
Lack of specifics regarding fixture error: RuntimeError: Foreign key violations found in your fixture data. Ensure you aren't referring to labels that don't exist on associations

### ISSUE THREAD

**Issue by Juksefantomet** [rails/rails#50056]
### Steps to reproduce

```
bundle exec rails g scaffold company
bundle exec rails g scaffold company_relation
```

edit migrations
```
create_table :companies do |t|
      t.string :name

      t.timestamps
end

create_table :company_relations do |t|
  t.boolean :parent
  t.boolean :child
  t.integer :parent_company_id

  t.references :company, null: true, foreign_key: true
  t.timestamps
end
```

company.rb
```
has_many :company_relations
```
company_relation.rb
```
belongs_to :company
```

create fixtures:

## omit the id specification in companies.yml fixture on purpose
companies.yml
```
company:
  name: 'Lumi Services AS'
```

company_relations.yml
```
company_relation:
  id: 1
  company_id: 1
```

```ruby
bundle exec rails rake:test
```

regardless of any other fixture working as intended ALL tests fail miserably due to the omitted id with:

```
E

Error:
ModelInQuestionControllerTest#test_name:
RuntimeError: Foreign key violations found in your fixture data. Ensure you aren't referring to labels that don't exist on associations.

```

### Expected behavior
A more specific detail regarding what fixture and/or relation is causing the issue.

### Actual behavior
ALL tests fail and has the same general error stating there is something wrong with your fixtures, resulting in a ton of troubleshooting if a third party was setting up new relations and forgot to update unit tests in accordance with new relations.

In this case i had to comment out and load each fixture individually to troubleshoot what was causing it, and everything was seemingly ok but the `id` was missing.

ref: [the-low-down-on-fixtures](https://guides.rubyonrails.org/testing.html#the-low-down-on-fixtures)

in the examples for fixtures, id is not covered, if those fixture tests was executed with relations in place they would never produce a success result.

### System configuration
**Rails version**: (~> 7.0.3, >= 7.0.3.1)

**Ruby version**: 3.2.2

**Comment by Juksefantomet** [comment]
I see now it has a bit more information in 7.1.x, apologies for not testing this prior to my report.

But i still cannot see any pointers nor references to `id` being required during fixture setup, as non relation entries resolves id without it having to be specified in the fixture.

But for any relation related fixture id has to be present, and that is not covered in the article referenced in the original post.

**Comment by yahonda** [comment]
Hi, Would you refer to the following Ruby on Rails API document.

https://api.rubyonrails.org/v7.1/classes/ActiveRecord/FixtureSet.html

> Label references for associations (belongs_to, has_one, has_many)
> Specifying foreign keys in fixtures can be very fragile, not to mention difficult to read. Since Active Record can figure out the ID of any fixture from its label, you can specify FK’s by label instead of ID.

This issue tracker is for the Rails framework itself, if you have further questions about how to use fixtures, please visit https://discuss.rubyonrails.org for help.
