### ISSUE TITLE
`ActionView::Helpers::TextHelper#word_wrap` Now Returns `nil` on Empty String 

### ISSUE THREAD

**Issue by sshaw** [rails/rails#50067]
### Steps to reproduce
After #45948(?) `word_wrap` returns `nil` for an empty string. Prior to 7.1 it returned an empty string

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "action_view/helpers/text_helper"
require "minitest/autorun"

class BugTest < Minitest::Test
  include ActionView::Helpers::TextHelper

  def test_stuff
    assert_equal word_wrap(""), ""
  end
end
```

### Expected behavior
`word_wrap` should return an empty string 

### Actual behavior
It returns `nil`

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.1

**Comment by jonathanhefner** [comment]
Sorry about that, and thank you for the bug report!  I've fixed this in #50069 and backported to `7-1-stable` in 71e0c050b81498adb1fec2a18056038ca14990ca.
