### ISSUE TITLE
No error messages in development after update from 7.0 to 7.1

### ISSUE THREAD

**Issue by joshfester** [rails/rails#50087]
### Steps to reproduce
I was on rails 7.0.8 and updated to 7.1.2. After the update, I no longer see errors in the console. It will just say "Completed 500 Internal Server Error" and render the error page you'd normally see in production. 

### Expected behavior
See errors with a stack trace in the console and on the rendered page

### Actual behavior
No errors, looks like it's in production

### System configuration
**Rails version**: 7.1.2

**Ruby version**:

Puma version: 6.4.0
web-console version: 4.2.1

When I start up the dev server, it says "Rails 7.1.2 application starting in development", and running Rails.env outputs "development". Puma and web-console are both the latest version, same as before the update to 7.1.

I ran `rails app:update` and even tried letting it overwrite my application.rb and development.rb. With the fresh development.rb, I get an error telling me to add my domain to config.hosts. The error shows in the console and I see the development error page. After I add `config.hosts << "my-domain.com:3000"`, then I stop seeing console errors and start seeing the production error page.

When I revert back to 7.0.8 the issue is gone. I tried a fresh project with `rails new` and added the config.hosts line, and that works as it should on rails 7.1.2. So this must be an issue specific to my codebase.

I can confirm `config.consider_all_requests_local = true`. When I run `request.local?` it always returns false. But it returned false even before this issue started. 

Maybe the wrong place to ask, but what else could cause this? Where else could I look?

Update: I tried curl'ing from localhost. `request.local?` returns true, but the issue persists. I tried removing the config.hosts line and curl'ing, same issue. Also tried: 
- changing the config to `config.hosts.clear`
- explicitly setting `config.log_level = :debug` 
- running `rails db:reset`
- changing to `config.load_defaults 7.0`

**Comment by joshfester** [comment]
Finally figured this out. Updated the Honeybadger gem from 4 to 5 and now the issue is fixed 😮‍💨

**Comment by woller** [comment]
> Finally figured this out. Updated the Honeybadger gem from 4 to 5 and now the issue is fixed 😮‍💨

This just saved me a ton of time. Thanks a lot 🎉
