### ISSUE TITLE
Passing DATABASE_URL env var breaks loading

### ISSUE THREAD

**Issue by andrewyoo** [rails/rails#50085]
Current rails main doesn't like when DATABASE_URL env is passed in.

### Steps to reproduce
```
rails new test_rails_edge --edge --database=postgresql
rails db:create
# update Gemfile to point to 'main' with `gem 'rails', github: 'rails/rails', branch: 'main'`
bundle
DATABASE_URL=postgres://localhost/test_rails_edge_development bin/rails c
```

results in:
```
.../activerecord/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `time_zone_aware_types' for ActiveRecord::Base:Class (NoMethodError)
```

### Expected behavior
Should load rails console using DATABASE_URL env for database

### Actual behavior
receives error `undefined method 'time_zone_aware_types' for ActiveRecord::Base:Class (NoMethodError)`

### System configuration
**Rails version**:
rails main b7d9654f981120b3f525533c3e35f544d3d3171e

**Ruby version**:
3.2.2

**Comment by fatkodima** [comment]
Confirmed and identified the cause. Going to open a PR.

**Comment by andrewyoo** [comment]
thanks @fatkodima !
