### ISSUE TITLE
`find_by` and `where` should cache association

### ISSUE THREAD

**Issue by yoshiyoshiharu** [rails/rails#50083]
I think fetched model using `find_by` or `where` by associated model should cache their associations.
If there are reasons why they does not cache, please let me know.

### Steps to reproduce

```ruby
class User < ApplicationRecord
  has_one :user_profile
end

class UserProfile < ApplicationRecord
  belongs_to :user
end
```

```ruby
user = User.first # Run SQL
user_profile = UserProfile.find_by(user: user) # Run SQL
user_profile.user # Run SQL, but I think this SQL should not run.
```

### Expected behavior

`user_profile = UserProfile.find_by(user: user)` should cache `user` association.
`user.user_profile` should not run SQL.
### Actual behavior

`user_profile = UserProfile.find_by(user: user)` does not cache `user` association.
`user.user_profile` run SQL.

### System configuration
**Rails version**: 3.2.2

**Ruby version**: 7.1.1

**Comment by paulreece** [comment]
Hey there, thanks for opening the issue.

So this is more of an enhancement suggestion.  Discussions like these are happening all the time at https://discuss.rubyonrails.org/ .  Feel free to post ideas like this there in the future.

In answer to your question, you can have the behavior you desire by adding `includes` to your `UserProfile` query.
```ruby
user = User.first # Run SQL
user_profile = UserProfile.includes(:user).find_by(user: user) # Run SQL
```
Here's an example from my local test app demonstrating this:
```ruby
irb(main):009:0> comment = Comment.includes(:post).find_by(post: post)
  SQL (0.9ms)  SELECT "comments"."id" AS t0_r0, "comments"."text" AS t0_r1, "comments"."author_id" AS t0_r2, "comments"."post_id" AS t0_r3, "comments"."created_at" AS t0_r4, "comments"."updated_at" AS t0_r5, "comments"."developer_id" AS t0_r6, "developers"."id" AS t1_r0, "developers"."name" AS t1_r1, "developers"."first_name" AS t1_r2, "developers"."salary" AS t1_r3, "developers"."firm_id" AS t1_r4, "developers"."mentor_id" AS t1_r5, "developers"."created_at" AS t1_r6, "developers"."updated_at" AS t1_r7, "posts"."id" AS t2_r0, "posts"."title" AS t2_r1, "posts"."created_at" AS t2_r2, "posts"."updated_at" AS t2_r3 FROM "comments" LEFT OUTER JOIN "developers" ON "developers"."id" = "comments"."developer_id" LEFT OUTER JOIN "posts" ON "posts"."id" = "comments"."post_id" WHERE "comments"."post_id" = $1 ORDER BY developers.name LIMIT $2  [["post_id", 1], ["LIMIT", 1]]
=>
#<Comment:0x000000011181f288
...
irb(main):010:0> comment.post
=>
#<Post:0x000000011181f148
 id: 1,
 title: "test",
 created_at: Thu, 26 Oct 2023 15:27:20.282111000 UTC +00:00,
 updated_at: Thu, 26 Oct 2023 15:27:20.282111000 UTC +00:00>
irb(main):011:0>
```

**Comment by nvasilevski** [comment]
>you can have the behavior you desire by adding includes to your UserProfile query.

That's a fair suggestion but I think it still adds this join which makes the query unnecessarily "heavier" than it could have been even though unlikely will be noticeable unless executed in an extremely hot path

Also I agree that most likely being able to pass whole objects to `where()` was only supposed to behave as a syntax sugar for building SQL so I'm leaning towards this being a feature request rather than a bug

**Comment by yoshiyoshiharu** [comment]
Thank you, everyone.
I misunderstand that I should post enhancement on an issue too.
I'll repost this feature request at https://discuss.rubyonrails.org/ .

**Comment by paulreece** [comment]
Sounds good. I'll go ahead and close this issue out then. If you ever have any questions on anything feel free to join us on the rails discord!
