### ISSUE TITLE
Proposal - Output the migration code, after the generate has run.

### ISSUE THREAD

**Issue by alterisian** [rails/rails#50095]
### Motivation
So that we help developers even more, when writing migrations, output the migration code after it has been run.
Since the migration code is typically small, we could output it straight after the migration has run, and save you going to open that file, if it has successfully added the field (in this instance). 

### Steps to reproduce

```ruby
rails g migration AddCodeToCountries code:string
```

### Expected behavior
      invoke  active_record
      create    db/migrate/20231118142828_add_code_to_countries.rb
      code     
class AddCodeToCountries < ActiveRecord::Migration[7.0]
  def change
    add_column :countries, :code, :string
  end
end

### Actual behavior
      invoke  active_record
      create    db/migrate/20231118142828_add_code_to_countries.rb

more db/migrate/20231118142828_add_code_to_countries.rb

class AddCodeToCountries < ActiveRecord::Migration[7.0]
  def change
    add_column :countries, :code, :string
  end
end

### System configuration
**Rails version**: 7

**Ruby version**: 3.1

**Comment by fatkodima** [comment]
We reserve github issue tracker for issues only and this is a feature request. Please use [Rails forum](https://discuss.rubyonrails.org/) for the discussion first.

**Comment by alterisian** [comment]
Ok thanks, @fatkodima

**Comment by alterisian** [comment]
Now moved to:
https://discuss.rubyonrails.org/t/proposal-output-the-migration-code-after-the-generate-has-run-was-issue-50095/84238
