### ISSUE TITLE
ActiveStorage only checks public schema to load files instead of tenant schema

### ISSUE THREAD

**Issue by hrithvik123** [rails/rails#50092]
I am trying to setup multi-tenancy in my Spree commerce app (ruby 3.2.0, rails 7) using Apartment (ros-apartment fork to be specific). 

When I upload files, they get added to the correct tenant schema and I can see it in ActiveStorage::Blob . But when I try to access the images, it only looks at ActiveStorage::Blob in public schema instead of tenant schema and ends up throwing 404 error ->

`ActiveRecord::RecordNotFound in ActiveStorage::Representations::ProxyController#show
Couldn't find ActiveStorage::Blob with 'id'=1`

Do I need to setup something else for it to work correctly ?

I have added the `config.middleware.use Apartment::Elevators::Subdomain` to my application.rb .

Any help is appreciated, thanks.

**Comment by fatkodima** [comment]
Hey @hrithvik123 we reserve the Rails Issues tracker for bugs in the framework as we don't have the bandwidth to offer application support. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help with your application. Thanks for understanding.
