### ISSUE TITLE
ActiveRecord is not cleaning duplicated values on `where(foo: my_array)`

### ISSUE THREAD

**Issue by mrcasals** [rails/rails#50111]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem 'activerecord', '~> 7.1.0'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post2 = Post.create!
    collection = Post.where(id: ([post.id, post2.id] * 10))

    sql = collection.to_sql
    sql_ids = sql.split(' IN ').last

    assert_equal 2, collection.count
    assert_equal 2, actual_sql_ids
  end
end
```

### Expected behavior
When calling `Post.where(id: my_ids)`, it's not cleaning up repeated values. Asking for the same value multiple times has not effect to the DB, but we can avoid sending extra bytes and parsing that extra information.

### Actual behavior
ActiveRecord is sending the values as they are, without cleaning duplicated values.

### System configuration
**Rails version**: Can confirm this happens at least since Rails 7.0.6

**Ruby version**: Ruby 3.2.2

**Comment by fatkodima** [comment]
Is it a common enough situation to have duplicates in `where`? And what about many duplicates?

**Comment by mrcasals** [comment]
@fatkodima I found a few places where this is happening in my codebase. Specially on public APIs. Of course I could try to make sure I call `uniq` on every call, but it's easier if ActiveRecord does the cleanup directly 😊

**Comment by byroot** [comment]
> I think, the most common case is having 1-2 duplicates at most. So this won't pay much in terms of data transfer.

I'd think the same.

> Do you think this is worth it?

I fear `uniq!` performance may not be that great for very large list of values. Generally speaking I don't mind Active Record doing a tiny bit of extra work to optimize queries etc, but here I'm really not sure the tradeoff is worth it.

**Comment by fatkodima** [comment]
I ran quite a few benchmarks and hadn't see any benefit from deduplication, only the opposite. So I am closing this, if you don't mind.

@mrcasals If you will be able to provide a real world like benchmark that proves its effectiveness, we will reconsider this.

**Comment by mrcasals** [comment]
@fatkodima got it, thanks for the quick response everyone! ❤️
