### ISSUE TITLE
Rails 7.0.5 and later: form_with no longer accepts single hash argument

### ISSUE THREAD

**Issue by ekortright-ewtn** [rails/rails#50117]
My application calls `form_with` by passing to it the hash returned by a method that figures out which parameters need to be set depending on the context.  This used to work until Rails 7.0.4 inclusive.  Starting with Rails 7.0.5, `form_with` accepts key-value pairs passed directly, but throws an error if a hash with the desired parameters is passed to it.

I don't see any mention of form_with changes in the 7.0.5 release notes, so I suspect this may be a bug.

### Steps to reproduce

In Rails console:

```ruby
include ActionView::Helpers::FormHelper
form_with({ url: 'foo' })
```

### Expected behavior
Should return a buffer with a `<form>` tag.  This is what happens if you use key-value pairs directly:
`form_with(url: 'foo')`

### Actual behavior
Throws an exception: `'form_with': wrong number of arguments (given 1, expected 0) (ArgumentError)`

### System configuration
**Rails version**: 7.0.5 and later (have not tested 7.1)

**Ruby version**: 3.2.1

**Comment by fatkodima** [comment]
I wasn't able to reproduce - it does not work for me neither for rails <= 7.0.4, nor for >= 7.0.5. And I don't see that `form_with` method's signature changed.

Can you create a sample app where this works with an old version, but fails with newer ones?

**Comment by ekortright-ewtn** [comment]
I will give it a try.  I am now getting all kinds of conflicting results, so that I was beginning to think it was because I was using Alpine Linux for some apps and Centos for others.  But that does not seem to matter, nor does the Rails version.

So far, all I know for sure is that using Ruby 2.7.3 and Rails 7.0.4, `form_with` can be called with a single hash argument.

**Comment by fatkodima** [comment]
Yeah, for ruby 2.7 it works for all versions. But for ruby 3.2 it does not work for all versions. Thats because of how ruby now handles keyword arguments. You need to pass either `for_with(url: 'foo')` or `form_with(**{url: 'foo'})`.

**Comment by ekortright-ewtn** [comment]
I see.  But you can still do things like `MyModel.new({ field1: 'value1', field2: 'value2' })` on Ruby 3.2.

**Comment by fatkodima** [comment]
Yes, because there are no keyword arguments. https://github.com/rails/rails/blob/5d0ab554e3286fe02ae795914ccc23e92f2c73b1/activerecord/lib/active_record/inheritance.rb#L56
https://github.com/rails/rails/blob/5d0ab554e3286fe02ae795914ccc23e92f2c73b1/activerecord/lib/active_record/core.rb#L428

**Comment by perfetti** [comment]
If you store the hash you can deconstruct it into `form_for`, otherwise it is keyword arguments, since it is generally used in a view file.
```
<% args = {url: 'foo'} %>
<%= form_for(**args) do |f| %>
```
is a complicated way to do this `<%= form_for(url: 'foo') do |f| %>`

**Comment by ekortright-ewtn** [comment]
I see; as long as there are no keyword arguments in the signature nothing changes.

Thanks for your help in understanding this.

**Comment by ekortright-ewtn** [comment]
@perfetti Thanks.  My specific situation benefits from calling a method that returns a hash.  But I should be able to do the deconstruct on the method call.
