### ISSUE TITLE
Error Message Degradation for Connection-Related Error Especially for Production Environment

### ISSUE THREAD

**Issue by aeroastro** [rails/rails#50125]
#### Gemfile

```ruby
source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "rails", github: "rails/rails", branch: "main"
gem "mysql2"
```

#### Test Code

```ruby
require "active_record"
require "action_controller/railtie"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "mysql2", host: "127.0.0.1", port: "3306")

class Post < ActiveRecord::Base
  has_many :comments
end

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    @post = Post.all.to_a
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    get "/"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior

There should be informative, accurate, and concise error message.

```
ActiveRecord::ConnectionNotEstablished (Can't connect to MySQL server on '127.0.0.1:3306' (61)):
```

### Actual behavior

The error message has been degraded.

```
ActiveRecord::DatabaseConnectionError (There is an issue connecting with your hostname: 127.0.0.1.

Please check your database configuration and ensure there is a valid connection to your database.
):
```

* `ActiveRecord::ConnectionNotEstablished` is more understandable than `ActiveRecord::DatabaseConnectionError` because the former implies when the connection issue happens.
* For a running production environment, almost all the causes of connection error are not the invalid database configuration, but due to the network error, disorder of a specific database instance (hardware or software), and other temporal failures. The error message of `Please check your database configuration` interferes with troubleshooting incidents on production environment.
* The message has lost port information, which makes it impossible to investigate which database is causing error when hosting multiple databases on different ports.
* The error code `61` has been lost.

### System configuration

**Rails version**: 7.2.0.alpha

**Ruby version**: 3.2.2

**Comment by paulreece** [comment]
Thanks for opening the issue.  Just for clarification, on previous Rails versions did you receive the `ActiveRecord::ConnectionNotEstablished` error in this circumstance?

**Comment by aeroastro** [comment]
Yes. I received correct the `ActiveRecord::ConnectionNotEstablished` errors from apps made with Rails 4, Rails 5, and Rails 6.

At least, the above reproduction code returns `ActiveRecord::ConnectionNotEstablished` with Rails `6.1.7.6`.

**Comment by skipkayhil** [comment]
For future readers, the PR that changed the errors is #39723 (first released in 7.0.0)

---

> * `ActiveRecord::ConnectionNotEstablished` is more understandable than `ActiveRecord::DatabaseConnectionError` because the former implies when the connection issue happens.

I think the ship may have sailed on this one, changing error classes is usually hard because of needing to deprecate. (The new class is a subclass of the old one which is why there was no deprecation needed before, but without that ability to subclass it's much harder)

> * For a running production environment, almost all the causes of connection error are not the invalid database configuration, but due to the network error, disorder of a specific database instance (hardware or software), and other temporal failures. The error message of `Please check your database configuration` interferes with troubleshooting incidents on production environment.

I kind of agree with this as well, but I'm not entirely sure where to draw the line. Maybe the current text only makes sense in development but not production?

> * The message has lost port information, which makes it impossible to investigate which database is causing error when hosting multiple databases on different ports.

This one should be really simple to fix, so I've opened a PR: #50135 

> * The error code `61` has been lost.

Agreed, it seems unfortunate that we've lost the underlying error message, but I can again see arguments for hiding it in development (or for beginners). In production I think showing the underlying error is more important (but the change is more involved so I haven't made a PR yet).

My overall thought is that while we want to make the error message nice for beginners, I agree with you that we should not be making it worse for experienced users.

**Comment by fatkodima** [comment]
Wdyt about this approach - https://github.com/rails/rails/pull/50145?

**Comment by aeroastro** [comment]
@skipkayhil 

> I kind of agree with this as well, but I'm not entirely sure where to draw the line. Maybe the current text only makes sense in development but not production?

The current text `Please check your database configuration and ensure there is a valid connection to your database.` does indeed seem to be more applicable to development scenarios, focusing primarily on database configuration issues. However, it may not adequately address other potential problems such as database or network issues in development environment. In a production environment, this message could rather potentially be misleading.

> My overall thought is that while we want to make the error message nice for beginners, I agree with you that we should not be making it worse for experienced users.

I agree with your sentiment that while we aim to make error messages beginner-friendly, it’s equally important not to compromise the experience for seasoned users. After reviewing the discussion on this pull request, I have a few suggestions that might benefit both novice and experienced users:

* Revert the exceptions and messages to their pre-Rails 7 state.
* If needed, display the current message in conjunction with the original message, but only on the Debug Error UI in the browser.

The message `Please check your database configuration and ensure there is a valid connection to your database.`, in my opinion, might be somewhat challenging for beginners to decipher and troubleshoot based solely on its content. Additionally, it doesn’t cover issues unrelated to database configuration.

In addition to that, the current message only translates a subset of potential exceptions, which can lead to inconsistencies between the exception class and messages. For instance, when connecting to MySQL via a socket instead of port, the error message is `ActiveRecord::ConnectionNotEstablished`, not `ActiveRecord::DatabaseConnectionError` as one might expect. This discrepancy could rather confuse beginners.

##### Rails7 style

```
# When connecting via socket
ActiveRecord::ConnectionNotEstablished (Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)):

# When connecting via port
ActiveRecord::DatabaseConnectionError (There is an issue connecting with your hostname: 127.0.0.1.

Please check your database configuration and ensure there is a valid connection to your database.
):
```

##### pre-Rails7 style

```
# When connecting via socket
ActiveRecord::ConnectionNotEstablished (Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)):

# When connecting via port
ActiveRecord::ConnectionNotEstablished (Can't connect to MySQL server on '127.0.0.1:3306' (61)):
```

If we stick to the original exceptions and messages prior to Rails 7, beginners can learn about database errors and how to solve them more efficiently.

I hope these suggestions are helpful and I look forward to further discussions on improving the user experience for both beginners and experienced users.

**Comment by aeroastro** [comment]
@fatkodima @byroot 
Thank you for the Pull Request, and sorry for the late reply.

I think the https://github.com/rails/rails/pull/50145 does not solve the issue.
Because the ambiguous and misleading message `Please check your database configuration and ensure there is a valid connection to your database.` still exist on production environment.
