### ISSUE TITLE
Rails 7.1 breaks loading plain text with yaml serializer

### ISSUE THREAD

**Issue by robbevp** [rails/rails#50146]
While upgrading to rails 7.1+ I bumped into an issue with a column that was supposed to contained serialized yaml, but didn't. This only happens if the column's content starts with a special character like `%`.

I think this issue is caused by [these changes](https://github.com/rails/rails/commit/185f2d718d4f971ef4d45c252ec2db3db6fb0f89#diff-935494b14b54c907fc1d206871d2a4797c490b80f2c86d61a7264131dd492e42L49-L57) as this removed some early returns if the yaml doesn't appear to be serialized yaml.

### Steps to reproduce

**Rails 7.0 - this works**
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text :content
  end
end

class Post < ActiveRecord::Base
  serialize :content
end

class BugTest < Minitest::Test
  def test_read_unserialized_value
    # Use raw sql to skip rails' serialization when inserting
    ActiveRecord::Base.connection.execute('INSERT INTO "posts" ("content") VALUES ("%{count}")')

    assert_equal '%{count}', Post.first.content_before_type_cast
    assert_equal '%{count}', Post.first.content
  end
end
```

**Rails 7.1 - This doesn't work**
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.text :content
  end
end

class Post < ActiveRecord::Base
  serialize :content, coder: YAML
end

class BugTest < Minitest::Test
  def test_read_unserialized_value
   # Use raw sql to skip rails' serialization when inserting
   ActiveRecord::Base.connection.execute('INSERT INTO "posts" ("content") VALUES ("%{count}")')

   assert_equal '%{count}', Post.first.content_before_type_cast
   
   # This will throw `Psych::SyntaxError: (<unknown>): could not find expected directive name while scanning a directive at line 1 column 1`
   assert_equal '%{count}', Post.first.content
  end
end
```

### Expected behavior
There should be no breaking behaviour here, since there was no deprecation notice. The upgrade guide to rails 7.1 also doesn't mention anything about changes around `serialize`: https://edgeguides.rubyonrails.org/7_1_release_notes.html

### Actual behavior
Trying to read the attribute will throw an error:
```
psych-5.1.1.1/lib/psych/parser.rb:62:in `_native_parse': (<unknown>): could not find expected directive name while scanning a directive at line 1 column 1 (Psych::SyntaxError)
```

### System configuration
**Rails version**: 7.0 -> 7.1

**Ruby version**: 3.2.2

**Comment by byroot** [comment]
As far as I know this wasn't a documented feature, as such it's not considered a breaking change even by sem-ver definition.

I recommend running a migration script to cleanup your database. Alternatively you can implement a custom coder for that column that restore the old behavior.

**Comment by robbevp** [comment]
Since this was part of the public API, I thought it would be considered a breaking change, but I can see your point about it never being documented.

I used a migration script to do this cleanup, so we could upgrade to rails 7.1+.

**Comment by byroot** [comment]
Yeah, [Hyrum's Law](https://www.hyrumslaw.com/) strikes again :)

Glad to hear you were able to cleanup your database state, it's probably for the better.
