### ISSUE TITLE
After touch removes saved_changes

### ISSUE THREAD

**Issue by matiassalles99** [rails/rails#50142]
### Steps to reproduce

- When calling `record.touch` on any ActiveRecord model, you can access the saved_changes in a after_touch callback
- When calling `saved_changes` in an after_touch callback that runs after an association touches the related record saved_changes is an empty hash, I suspect that might be related to the `clear_attribute_change` in the TouchLater module

<img width="793" alt="Screenshot 2023-11-22 at 15 33 48" src="https://github.com/rails/rails/assets/57004457/771a4c3a-d1c4-48e8-8367-2c823a5753a1">

- To replicate create two ActiveRecord classes

```ruby
class A < ApplicationRecord
  belongs_to :b, touch: true
end

class B < ApplicationRecord
  after_touch :do_sth

  def do_sth
    puts saved_changes
  end
end
```

### Expected behavior
- We should see the updated_at attribute inside the saved_changes hash, which allows calling updated_at_before_last_save to expire cache keys based on the updated_at

### Actual behavior
- saved_changes returns an empty hash, which means there is no way to access the previous updated_at value

### System configuration
**Rails version**: 7.1.0

**Ruby version**: 3.2.2

**Comment by adrianna-chang-shopify** [comment]
👋 Hi @matiassalles99 , can you help me clarify the expected vs actual behaviour? I wrote up a repro script, and I _am_ seeing the `updated_at` attribute inside the `saved_changes` hash. However, it doesn't seem to be an "updated" value if we touch the associated record. Here's the repro I was using:

```ruby
require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :bs, force: true do |t|
    t.timestamps
  end

  create_table :as, force: true do |t|
    t.references :b
    t.timestamps
  end
end

class A < ActiveRecord::Base
  belongs_to :b, touch: true
end

class B < ActiveRecord::Base
  after_touch :do_sth

  def do_sth
    puts "----- SAVED CHANGES for #{self}"
    puts saved_changes
  end
end

class TouchTest < Minitest::Test
  def test_touch_a
    b = B.create!
    a = A.create!(b: b)

    a.touch
  end
end
```

```
# Running:

D, [2023-11-29T17:46:33.288017 #74125] DEBUG -- :   B Create (0.1ms)  INSERT INTO "bs" ("created_at", "updated_at") VALUES (?, ?) RETURNING "id"  [["created_at", "2023-11-29 22:46:33.287616"], ["updated_at", "2023-11-29 22:46:33.287616"]]
D, [2023-11-29T17:46:33.293484 #74125] DEBUG -- :   A Create (0.1ms)  INSERT INTO "as" ("b_id", "created_at", "updated_at") VALUES (?, ?, ?) RETURNING "id"  [["b_id", 1], ["created_at", "2023-11-29 22:46:33.293128"], ["updated_at", "2023-11-29 22:46:33.293128"]]
D, [2023-11-29T17:46:33.302368 #74125] DEBUG -- :   B Update (0.0ms)  UPDATE "bs" SET "updated_at" = ? WHERE "bs"."id" = ?  [["updated_at", "2023-11-29 22:46:33.293581"], ["id", 1]]
----- SAVED CHANGES for #<B:0x0000000105dd6188>
{"id"=>[nil, 1], "created_at"=>[nil, 2023-11-29 22:46:33.287616 UTC], "updated_at"=>[nil, 2023-11-29 22:46:33.287616 UTC]}
D, [2023-11-29T17:46:33.302718 #74125] DEBUG -- :   A Update (0.1ms)  UPDATE "as" SET "updated_at" = ? WHERE "as"."id" = ?  [["updated_at", "2023-11-29 22:46:33.302578"], ["id", 1]]
D, [2023-11-29T17:46:33.302881 #74125] DEBUG -- :   B Update (0.0ms)  UPDATE "bs" SET "updated_at" = ? WHERE "bs"."id" = ?  [["updated_at", "2023-11-29 22:46:33.302767"], ["id", 1]]
----- SAVED CHANGES for #<B:0x0000000105dd6188>
{"id"=>[nil, 1], "created_at"=>[nil, 2023-11-29 22:46:33.287616 UTC], "updated_at"=>[nil, 2023-11-29 22:46:33.287616 UTC]} # The timestamp values here are from when we first created b

Finished in 0.018795s, 53.2056 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

Versus if we touch `b` directly, we see the new `updated_at` reflected properly in `saved_changes`

```ruby
class TouchTest < Minitest::Test
  def test_touch_b
    b = B.create!
    a = A.create!(b: b)

    b.touch
  end
end
```

```
# Running:

D, [2023-11-29T17:50:40.544742 #76157] DEBUG -- :   B Create (0.1ms)  INSERT INTO "bs" ("created_at", "updated_at") VALUES (?, ?) RETURNING "id"  [["created_at", "2023-11-29 22:50:40.544351"], ["updated_at", "2023-11-29 22:50:40.544351"]]
D, [2023-11-29T17:50:40.550451 #76157] DEBUG -- :   A Create (0.1ms)  INSERT INTO "as" ("b_id", "created_at", "updated_at") VALUES (?, ?, ?) RETURNING "id"  [["b_id", 1], ["created_at", "2023-11-29 22:50:40.550183"], ["updated_at", "2023-11-29 22:50:40.550183"]]
D, [2023-11-29T17:50:40.561569 #76157] DEBUG -- :   B Update (0.0ms)  UPDATE "bs" SET "updated_at" = ? WHERE "bs"."id" = ?  [["updated_at", "2023-11-29 22:50:40.550538"], ["id", 1]]
----- SAVED CHANGES for #<B:0x00000001077cfa08>
{"id"=>[nil, 1], "created_at"=>[nil, 2023-11-29 22:50:40.544351 UTC], "updated_at"=>[nil, 2023-11-29 22:50:40.544351 UTC]}
D, [2023-11-29T17:50:40.561879 #76157] DEBUG -- :   B Update (0.0ms)  UPDATE "bs" SET "updated_at" = ? WHERE "bs"."id" = ?  [["updated_at", "2023-11-29 22:50:40.561759"], ["id", 1]]
----- SAVED CHANGES for #<B:0x00000001077cfa08>
{"updated_at"=>[2023-11-29 22:50:40.550538 UTC, 2023-11-29 22:50:40.561759 UTC]} # These updated_at values match the previous and new `updated_at` values for b

Finished in 0.021722s, 46.0363 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

Is this in line with what you were seeing?

**Comment by matiassalles99** [comment]
@adrianna-chang-shopify Exactly, so the expected behavior is that when touching an associated record (in your example when you touch A, B should have the updated_at attribute in the saved_changes in the `after_touch` callback). Instead, you only see the updated_at attribute in the saved_changes when touching a specific record directly, not its associations.

From what I could understand in the source code, the following method in the module `TouchLater` is what clears the saved_changes hash after touching an associated record.
<img width="769" alt="Screenshot 2023-11-30 at 01 17 54" src="https://github.com/rails/rails/assets/57004457/686fb2f7-92b5-41b1-b66f-4a4c603c2611">

Maybe it's the desired behavior and there's a reason for it, but we encountered this issue when needing the previous updated_at value, and I'd be more than happy to help figure it out/fix the code if the change makes sense to y'all

**Comment by adrianna-chang-shopify** [comment]
Looking through the existing docs and test cases, I can't see anything that indicates this is intentional. I'd expect `touch: true` and touching the associated record to behave in the same way as if we were touching `b` directly.

The setup in `TouchLater` indeed seems to be the culprit -- others might have opinions, but this seems like a bug to me. Are you up for working on a fix? 😄

**Comment by matiassalles99** [comment]
yeah, haven't started working on it yet but will try to do so this weekend 💪

**Comment by matiassalles99** [comment]
@adrianna-chang-shopify I have been looking at this and seems like even though there are no tests that try to make it a desired behavior there are various lines of code that try not to track the changes such as 
```ruby
      def touch_deferred_attributes
        @_skip_dirty_tracking = true
        touch(time: @_touch_time)
      end
```
so I'm wondering if the best approach here is to make the PR anyways and see their feedback of you have any other recommendations

**Comment by matiassalles99** [comment]
@adrianna-chang-shopify makes sense - I'll close this issue since it's not a bug and will keep looking into it in my spare time to see if there's sth that can be changed, but looks like this is the desired behavior
