### ISSUE TITLE
ActiveRecord::DangerousAttributeError:        object_id is defined by Active Record

### ISSUE THREAD

**Issue by misdoro** [rails/rails#50160]
With ActiveRecord Before https://github.com/rails/rails/pull/45883/files
it was possible to have a polymorphic relation `object`, 
implicitly defining `object_type` and `object_id` columns.

### Expected behavior
Able to use `object` as a name for a polymorphic relationship

### Actual behavior
An exception 
```
ActiveRecord::DangerousAttributeError:
       object_id is defined by Active Record. Check to make sure that you don't have an attribute or method with the same name.
```
is raised 

### System configuration
**Rails version**:
updating from 7.0 to 7.1

Can the `object_id` column be removed from the dangerous attributes list?

Having the column with that name was not breaking anything for us for many years, and now we are blocked from upgrading to rails 7.1.

**Comment by fatkodima** [comment]
I think the action here is to rename the column in the app to something else.

**Comment by misdoro** [comment]
https://github.com/rails/rails/pull/38990 it was explicitly allowed here

**Comment by fatkodima** [comment]
Ah, ok. 

I see `object_id` is used in a few (3-5) places in Active Record. So if we change these to use `__id__` instead, then we can reconsider https://github.com/rails/rails/pull/45883/files (by @byroot) by removing `object_id` from the list? 

Still not sure this is a good idea, but `object_id` seems like a popular attribute name.

**Comment by byroot** [comment]
I don't mind allowing it again, but we should find some way to test that active record itself doesn't rely on it :)

**Comment by fatkodima** [comment]
Custom rubocop cop probably. Or redefining `object_id` in active record's test suite to raise 💥

**Comment by byroot** [comment]
I think defining an `object_id` column on several of the most used fixtures models should work.
