### ISSUE TITLE
Failing tests in shared_generator_tests

### ISSUE THREAD

**Issue by fredwillmore** [rails/rails#50168]
### Steps to reproduce
I get a number of test failures when I run
`bin/test test/generators/plugin_generator_test.rb`
The failures were all occurring here:
https://github.com/rails/rails/blob/main/railties/test/generators/shared_generator_tests.rb#L416-L417
With the aid of a debugger I went in and found that the test is asserting a match on `@bundle_commands[2]` but there is an actual match on `@bundle_commands[3]`. I made the change locally and now all the tests run clean.
Here is an example of the contents of `@bundle_commands` on line 416:
```
install
lock --add-platform=x86_64-linux
lock --add-platform=aarch64-linux
exec rails plugin new /Users/fredwillmore/OtherDocuments/ruby_projects/rails/railties/test/fixtures/tmp/bukkits/myproject --main
```
It looks like a second `lock` command with `--add-platform=aarch64-linux` is at issue here. This command is added here:
https://github.com/rails/rails/blob/main/railties/lib/rails/generators/app_base.rb#L690-L691
So this is a special case for arm64 macs. (I am using an M2 Pro, running macOS 13.6) The solution I used locally would not be suitable for use on any other platform.

### to reproduce
`bin/test test/generators/plugin_generator_test.rb`

### Expected behavior
tests pass

### Actual behavior
tests on matching bundle commands fail

### System configuration
rails 7.2.0.alpha
ruby 3.2.2

**Comment by hahmed** [comment]
Maybe we could use something like this? `matching_command = RUBY_PLATFORM.start_with?("arm64") ? @bundle_commands[3] : @bundle_commands[2]`  and use that on the next line for the assertion?

**Comment by jonathanhefner** [comment]
See also the discussion in https://github.com/rails/rails/pull/49679#discussion_r1363610234.  I am going to submit a PR shortly.
