### ISSUE TITLE
String contains null byte

### ISSUE THREAD

**Issue by collimarco** [rails/rails#50166]
### Steps to reproduce

```
@post = @project.posts.build post_params
@post.save
```

If some users pass a null byte through the REST API (post_params), Rails produces a 500 Internal Server Error on save. This is what I see from logs:

```
ArgumentError (string contains null byte)
```

### More details

In the JSON standard (as defined by RFC 8259), null bytes (i.e., the byte with value 0x00) are not allowed within the JSON text.

When a JSON request is decoded into params, the strings should not contain null bytes. If a string contains null bytes, that is an invalid JSON and an appropriate 4xx error should be returned to the client.

### Expected behavior
Rails returns a 4xx error when a JSON request is decoded if it contains null bytes.

### Actual behavior
Rails ignores the null bytes in the JSON string (and then raises a weird exception during `.save`).

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
Can you create a reproduction test script?

**Comment by collimarco** [comment]
```ruby
RSpec.describe 'Posts API', type: :request do

  let(:post_attributes) { { post: { title: "Text with \x00 null bytes", content: "Some content" } } }

  describe 'POST /posts' do
    context 'when the request includes a field with null bytes' do
      before { post '/posts', params: post_attributes.to_json, headers: { 'Content-Type': 'application/json' } }

      # this test fails, because Rails raises an exception that generates a 500 error
      it 'returns a 400 error to the client' do
        expect(response).to have_http_status(400)
      end
    end

  end
end
```

**Comment by fatkodima** [comment]
Can you create a **full** reproduction script using one of the following templates - https://github.com/rails/rails/tree/main/guides/bug_report_templates?

**Comment by codergeek121** [comment]
Trying to save null bytes in Postgres string or text columns will raise an `ArgumentError`. Imo there's no clear path for Rails to fix this, but I used the https://github.com/whitequark/rack-utf8_sanitizer gem to strip null bytes successfully.

**Comment by fatkodima** [comment]
Reproduction script
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", github: "rails/rails", branch: "main"
  gem "pg"
end

require "active_record"
require "action_controller/railtie"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "test_db")
ActiveRecord::Base.logger = Logger.new(STDOUT)

class User < ActiveRecord::Base
end

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
  end
end

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts.clear
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    post "/" => "test#create"
  end
end

class TestController < ActionController::Base
  def create
    User.create!(params.require(:user).permit(:name))
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < ActionDispatch::IntegrationTest
  def test_returns_success
    post "/", params: {user: {"name"=> "Dim\0a"}}, as: :json
    assert_response :success
  end

  private
    def app
      Rails.application
    end
end
```

**Comment by eugeneius** [comment]
> In the JSON standard (as defined by RFC 8259), null bytes (i.e., the byte with value 0x00) are not allowed within the JSON text.

Can you quote the part of RFC 8259 that specifies this? I just skimmed it and it seems to say the opposite: all characters are allowed, even if some—like 0x00—must be escaped.

**Comment by collimarco** [comment]
@eugeneius to be honest I didn't do much research about that: I read on some discussions that it was not allowed and then I asked ChatGPT: "Is it allowed by the standard to add null bytes to JSON?"  and that sentence is the reply that I got. It may be wrong, I don't know.

In any case I am pretty sure about this issue: it's not correct that a POST request from a user generates a 500 error for null bytes. Null bytes should be handled properly or, alternatively, a 400 should be returned.

**Comment by collimarco** [comment]
@codergeek121 That gem seems really promising! I'll try it. I wonder if Rails should implement something like that directly.

**Comment by eileencodes** [comment]
> to be honest I didn't do much research about that: I read on some discussions that it was not allowed and then I asked ChatGPT: "Is it allowed by the standard to add null bytes to JSON?" and that sentence is the reply that I got. It may be wrong, I don't know.

ChatGPT isn't always right and the Core team is not going to be able to do the research on this for you. Please investigate and if you find there is indeed a bug we can reopen. But for now I'm going to close.

**Comment by collimarco** [comment]
@eileencodes If are going to close an issue based on a single sentence, please read it until the end... I also said:

> **In any case** I am pretty sure about this issue: it's not correct that a POST request from a user generates a 500 error for null bytes. Null bytes should be handled properly or, alternatively, a 400 should be returned.

So the bug is there, and I don't understand why you are aggressively closing this without some discussion.

**Comment by nvasilevski** [comment]
>In any case I am pretty sure about this issue
>It's not correct that a POST request from a user generates a 500 error for null bytes.
>Null bytes should be handled properly

Allow me to disagree. From some point of view this issue can be seen as returning `HTTP 500` when user provides an integer value larger than can be stored in the database and the model doesn't have a validation. So it's not particularly clear what do you mean by "should be handled properly" because if my application uses sqlite (fox example) the **proper** handling would be the one that exists right now and no fix is required.

JSON standard is a crucial piece here because it will determine which layer the fix must be implemented if this indeed will be considered to be a bug. 

If JSON standard didn't allow null bytes then the issue should be handled even before the value reaches controller. But it looks like it's allowed to have null bytes in the value so it means that it's totally valid for `post_attributes` to contain values with null bytes. Which may look like the fix should live at the `Model` layer and Rails should strip null bytes before record creation (or attribute assignment) but even this won't be correct because the problem seem to only be specific to postgresql  adapter as the problem is not reproducible when using sqlite. 

Does it mean the fix should live in postgresql adapter? Perhaps, but it needs more investigation. The point I want to make that JSON standard is essential for determining whether something needs to be fixed and where it needs to be fixed and blindly relying on AI opinion in this case was a little irresponsible

**Comment by collimarco** [comment]
Even if I made a mistake with that sentence (maybe), that doesn't mean that I didn't spend time on this. Closing this issue without a certain conclusion doesn't bring any benefit and wastes the time that I spent and the time spent by other collaborators that created the reproduction script or provided useful feedback.

Not only ChatGPT gave me that answer, but I had also read some discussions like this:
https://stackoverflow.com/questions/43969649/null-character-within-json

**How do you interpret that?**

I was also suggesting that, regardless of what the JSON standard says, it may useful to **filter invalid UTF-8 characters and null bytes** in Rails (for example with a middleware). In this way we can avoid a large class of errors that otherwise happen in random locations inside the application code.

**Comment by zzak** [comment]
> it may useful to **filter invalid UTF-8 characters and null bytes** in Rails (for example with a middleware). In this way we can avoid a large class of errors that otherwise happen in random locations inside the application code.

That is a perfectly reasonable conclusion to this discussion for me.

However, we do not accept [feature requests](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark) in the form of GitHub issues.

I suggest that you open a PR if you feel strongly about this, or if you'd like [feedback](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#get-some-feedback) on your idea please use [discuss](https://discuss.rubyonrails.org/c/rubyonrails-core) or [discord](https://discord.gg/d8N68BCw49). :bow:
