### ISSUE TITLE
Exists? consider raw query as id

### ISSUE THREAD

**Issue by Kingtamil2001** [rails/rails#50180]
### Steps to reproduce
User.exists?("email = 'user_name@domain.com'")

### Expected behavior
User Exists (342.9ms)  SELECT  1 AS one FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."email" = $1 LIMIT $2  [["email", "user_name@domain.com"], ["LIMIT", 1]]

### Actual behavior
it triggers the query like this

`User Exists (5.6ms)  SELECT  1 AS one FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."id" = $1 LIMIT $2  [["id", 0], ["LIMIT", 1]]
`

### System configuration

Rails version: 5.0.3
Ruby version: 2.4.10
ActiveRecord version:: 5.0.3

**Comment by eileencodes** [comment]
Hi @Kingtamil2001 - as noted in the [documentation](https://edgeapi.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-exists-3F), `exists?` cannot take a string as a SQL query.

> Note: You can’t pass in a condition as a string (like name = 'Jamie'), since it would be sanitized and then queried against the primary key column, like id = 'name = \'Jamie\''.
