### ISSUE TITLE
Inconsistency in Documentation: Mismatch Between `revert` Code Example and Subsequent Steps

### ISSUE THREAD

**Issue by Leo-U** [rails/rails#50189]
There is an apparent error in [this documentation section](https://guides.rubyonrails.org/active_record_migrations.html#reverting-previous-migrations).

The point of confusion is the last part of the section where it says `the same migration could also have been written without using revert but this would have involved a few more steps` and proceeds to list some steps.

To my understanding, the phrase `the same migration` refers to the code example immediately above that text -- that code example demonstrates the use of `revert` to selectively rollback part of a previous migration. The way it works is that you copy and paste part of the code from a previous migration and wrap it in that `revert` block. Then, rails automatically does the opposite of what is included there. So, that part I think I understand.

So now, back to the text at the end. The steps listed are:
```
    1. Reverse the order of create_table and reversible.
    2. Replace create_table with drop_table.
    3. Finally, replace up with down and vice-versa.
```
Here's what I don't get: that second code example in the docs section that demonstrates the use of revert to selectively revert part of a migration does not involve dropping any table. It would make sense to me if that copy-pasted code included a create_table statement, but it doesn't. So, to my understanding, the steps listed with that last statement don't make sense.

For more context, the `ExampleMigration` referred to in that second code example appears to refer to a migration mentioned further up in the docs in another section, [here](https://guides.rubyonrails.org/active_record_migrations.html#using-reversible).

**It has been pointed out to me that the code example did originally have a `create_table` call, as you can see [here](https://github.com/rails/rails/blob/c4c3a44685b4cfb1ffd4c27309ccfbf1bb53d4e5/guides/source/active_record_migrations.md?plain=1#L606C6-L606C6)**. Therefore, it looks to me like the cause of the confusion is that when the section was updated to remove the `create_table` call, it caused the last bit of the wording in that section to become nonsensical.

I am not any kind of Rails expert, so I wouldn't want to try and edit the documentation myself, so I have decided to open this issue here. Thank you!

**Comment by apoorv1316** [comment]
@zzak Can I work on this?

**Comment by adrianna-chang-shopify** [comment]
@apoorv1316 feel free to open a PR :)

**Comment by cedriccarrard** [comment]
Hi @Leo-U i opened a PR, if you have any feedback

**Comment by Leo-U** [comment]
> Hi @Leo-U, i opened a PR, if you have any feedback

Oh, i thought @apoorv1316 claimed it. btw this is actually my first rails issue report, so I don't feel qualified to approve any edits

**Comment by zzak** [comment]
Just a _very_ quick look at the context around this:

* Seems it was added in a81845f26864d076970e706863c766aead432672
* a5b3f372ab30e043d25b25b05e603e6ed33c0ee9 changed the table names and removed the `create_table`

Maybe worth looking at those further, but also just looking at the other examples around them seem to support that each section should define the schema consistently. 🤔 It's not like there is a "setup" section before all of these examples where we define the schema up-front -- it's all pretty ad-lib, but I think there is certainly room for improvement.

**Comment by Leo-U** [comment]
@zzak Np, glad to!

Looks like @cedriccarrard has added their commit as you can see [here](https://github.com/rails/rails/pull/50228). Will their commit be successful, and should I therefore close this issue?

**Comment by zzak** [comment]
> Will their commit be successful, and should I therefore close this issue?

The issue should close automatically once the PR that "fixes #NNNN" is merged.

**Comment by cedriccarrard** [comment]
@Leo-U @zzak I've updated the pull request
