### ISSUE TITLE
[Proposal] Deprecate and replace `ActiveSupport::OrderedOptions` and `ActiveSupport::InheritableOptions`

### ISSUE THREAD

**Issue by kmcphillips** [rails/rails#50203]
## Problem

The [`ActiveSupport::OrderedOptions` and `ActiveSupport::InheritableOptions`](https://github.com/rails/rails/blob/ed2bc92b82ddc111150cdf48bb646fd97b3baacb/activesupport/lib/active_support/ordered_options.rb) classes are used throughout rails to provide the `*.config.*` options through the framework railties, as well as some more specific nested configuration options. It is the basis for [`ActiveSupport::Configurable`](https://github.com/rails/rails/blob/ed2bc92b82ddc111150cdf48bb646fd97b3baacb/activesupport/lib/active_support/configurable.rb#L14). They are part of the public API in Active Support.

They are a specialization of `Hash`, and their purpose is ostensibly to provide convenience read/writers as methods, and a few other small features. These classes were [introduced](https://github.com/thedarkone/rails/commit/9f146ea0ac904252b16be1c4017604aed0c383f7) ~15-18 years ago and are now **incorrectly named** and contain bugs as well as **unpredictable and unspecified behaviour** that makes them, in my opinion, dangerous to use reliably. 

I have made some improvements in #50151, but there are many many remaining problems. Such as:

### Incorrectly named and unnecessary hierarchy

The reason it is called `OrderedOptions` is that prior to Ruby 1.9 hash insertion did not promise a stable ordering, which this class provided.

The `InheritableOptions` subclass allows a parent hash to provide defaults, but there is no good reason for this to be a specialized class and can just be initialization options.

### They do not behave hash-like in many cases

Despite being a subclass of `Hash`, the implementation does not behave hash-like in many cases. The reason is that it uses hash default block initialization syntax to carry around the parent hash in the closure, rather than calling `update(parent)` or `merge(parent)` on initialize:
```ruby
  class InheritableOptions < OrderedOptions
    def initialize(parent = nil)
      super() { |h, k| parent[k] }
    end
```

So that parent is passed around by reference. Lookups first check `self` then fall back to `parent`. Any key that is updated is only changed `self` and overshadows the parent. So most hash operations only check _overrides_, but retrievals will fall through to the parent. It also means that changes to the parent hash are reflected in lookups, but any overrides remain local. It's very confusing, and again **unspecified and unpredictable behaviour**. (A detailed example of behaviour listed at the bottom).

This means as Rails calls [`inheritable_copy`](https://github.com/rails/rails/blob/ed2bc92b82ddc111150cdf48bb646fd97b3baacb/activesupport/lib/active_support/ordered_options.rb#L105-L107) on several different levels:
https://github.com/rails/rails/blob/ed2bc92b82ddc111150cdf48bb646fd97b3baacb/actionview/lib/action_view/helpers/controller_helper.rb#L23
https://github.com/rails/rails/blob/ed2bc92b82ddc111150cdf48bb646fd97b3baacb/activesupport/lib/active_support/configurable.rb#L32
https://github.com/rails/rails/blob/ed2bc92b82ddc111150cdf48bb646fd97b3baacb/activesupport/lib/active_support/configurable.rb#L156

The actual value of what is in each copy of the config object depends on what level it was modified, at what time, and if there were any overrides or not.

### Rails depends on this broken entangled behaviour

As linked above, the configs are declared in the root module as `ActiveSupport::Configurable`, but then are copied down. For example `ActionController::Base` is configurable, but that config is copied down to the controller instance, then to the view context. Rails has tests that depend on the pass by reference linking of those copies:
https://github.com/rails/rails/blob/ed2bc92b82ddc111150cdf48bb646fd97b3baacb/actionpack/test/controller/helper_test.rb#L261-L265

But nowhere is this behaviour tested in the unit tests for `InheritableOptions`, nor is it documented. And crucially **this behaviour stops working if it is overridden at any level**. Meaning that if you modify a key in some initialization step before the values are copied down, they stop being linked.

In a few places they are called "proxy" which is probably what is desired behaviour here.

## Proposed solution

Fixing all this behaviour in place would mean hard to diagnose internal behaviour breakage. There is no good reason to have `Ordered` in the name as all hashes are ordered. There is no reason to have `InheritableOptions` be a subclass, when it can just be an initializer options.

So I propose:
* Building a new `ActiveSupport::Options` class which fixes the above behaviour and reimplements as a hash, and documents all behaviour.
* Deprecate public use of `ActiveSupport::OrderedOptions` and `ActiveSupport::InheritableOptions` internally and publicly.
* Refactor rails internally to only use `ActiveSupport::Options`. The changes to `ActiveSupport::Configurable` may mean building a proxy wrapper around the config, and that's ok.

Building the new class is trivial, and I have it in a commit https://github.com/kmcphillips/rails/commit/fec85f7141fb6055b9406b2bdb5a7282b48e698a including tests. The new class is just over a hundred lines, including documentation and a `SafeOptions` specialization discussed [here](https://github.com/rails/rails/pull/50140#issuecomment-1823698711) which I think is a great feature to add.

Anyone using these classes outside of Rails just as a feature of Active Support would in most cases just need to update a class name and maybe a `new()` signature.

Internal use should be manageable, because we define the behaviour we want, and would do it over a release cycle.

## Appendix

Here is an example of how unpredictable the behaviour is. This mirrors how Rails copies the config down three levels in the base controller/controller class/view context example:

```
# Given a hash of default values
> defaults = { a: "a from defaults", b: "b from defaults" }
=> {:a=>"a from defaults", :b=>"b from defaults"}

# Inheritable options pulls the options from that default
> action_controller_base = ActiveSupport::InheritableOptions.new(defaults)
=> {}

# Assign an override value and a new key value
> action_controller_base.b = "b from action_controller_base"
> action_controller_base.c = "c from action_controller_base"

# This works pretty much as expected
> action_controller_base.a
=> "a from defaults"
> action_controller_base.b = "b from action_controller_base"
=> "b from action_controller_base"
> action_controller_base.c = "c from action_controller_base"
=> "c from action_controller_base"

# The defaults hash is unchanged
> defaults
=> {:a=>"a from defaults", :b=>"b from defaults"}

# But if you update the values in the defaults hash
> defaults[:a] = "a with updated default"
=> "a with updated default"
> defaults[:b] = "b with updated default"
=> "b with updated default"

# Original values are entangled with the copy, updated values are not
irb(main):061> action_controller_base.a
=> "a with updated default"
irb(main):062> action_controller_base.b
=> "b from action_controller_base"

# Then we can further make a copy
> controller_instance = action_controller_base.inheritable_copy
> controller_instance.c = "c from controller_instance"
> controller_instance.d = "d from controller_instance"

# The values are entangled differently with the two parents
> controller_instance.a
=> "a with updated default"
> controller_instance.b
=> "b from action_controller_base"
> controller_instance.c
=> "c from controller_instance"
> controller_instance.d
=> "d from controller_instance"

# We make one copy further
> view_context = controller_instance.inheritable_copy
> view_context.d = "d from view_context"
> view_context.e = "e from view_context"

# The values are entangled with the three parents
> view_context.a
=> "a with updated default"
> view_context.b
=> "b from action_controller_base"
> view_context.c
=> "c from controller_instance"
> view_context.d
=> "d from view_context"
> view_context.e
=> "e from view_context"

# Sometimes changing a parent is reflected all the way down in this copy, sometimes it is not, depending on at what level it was previously modified and at what time
> action_controller_base.a = "a override action_controller_base"
=> "a override action_controller_base"
> action_controller_base.b = "b override action_controller_base"
=> "b override action_controller_base"
> action_controller_base.c = "c override action_controller_base"
=> "c override action_controller_base"
> view_context.a
=> "a override action_controller_base"
> view_context.b
=> "b override action_controller_base"
> view_context.c
=> "c from controller_instance"
> view_context.d
=> "d from view_context"
```

**Comment by zzak** [comment]
Thank you for the extremely thorough writeup, but I would be inconsistent if I didn't remind you that we don't accept [feature requests](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark) in the form of GitHub issues. :bow:

Sorry!

**Comment by kmcphillips** [comment]
Oh sorry I should have been explicit about that at the top.

I'll do the work! But I won't do the work there is no appetite for it being done. So I'm looking for feedback and :+1: on the idea and approach.

Most of the work is actually managing a deprecation cycle I think. And that's a collective release time type effort, on top of the code change.

**Comment by zzak** [comment]
Historically we've reserved Issues for bug reports, this is not a bug (I think), and it would be unfair to all of the other contributors we've applied this restriction to if we made an exception here.

Please move this discussion to the [forum](https://discuss.rubyonrails.org/c/rubyonrails-core/5) or feel free to create a thread in [discord](https://discord.com/invite/d8N68BCw49).

Thanks for understanding!

**Comment by kmcphillips** [comment]
Ok great. Thanks!
