### ISSUE TITLE
Transaction commits before query execution within transaction block.

### ISSUE THREAD

**Issue by apmiller108** [rails/rails#50201]
### Steps to reproduce

Maybe this is totally expected, but this behavior was found to be surprising.

#### Senario 1
The transaction defined with the following code will commit after the `SET` statement, and before the `Message.all` query.
```ruby
ActiveRecord::Base.transaction do
  ActiveRecord::Base.connection.execute('SET LOCAL statement_timeout = \'5s\';')
  Message.all
end
```

```
TRANSACTION (0.7ms)  BEGIN
(3.4ms)  SET LOCAL statement_timeout = '5s';
TRANSACTION (0.5ms)  COMMIT
Message Load (0.4ms)  SELECT "messages".* FROM "messages" /* loading for pp */ LIMIT $1  [["LIMIT", 11]]
```

#### Senario 2
However, everything appears to run within the transaction when using `execute` for both queries.
```ruby
ActiveRecord::Base.transaction do
  ActiveRecord::Base.connection.execute('SET LOCAL statement_timeout = \'5s\';')
  ActiveRecord::Base.connection.execute(Message.all.to_sql)
end
```

```
TRANSACTION (0.4ms)  BEGIN
(2.4ms)  SET LOCAL statement_timeout = '5s';
(1.2ms)  SELECT "messages".* FROM "messages"
TRANSACTION (0.9ms)  COMMIT
```

### Expected behavior
I expected that in both of the above scenarios, everything in the transaction block would be run within the DB transaction statement, like this:

```
TRANSACTION (0.4ms)  BEGIN
(2.4ms)  SET LOCAL statement_timeout = '5s';
(1.2ms)  SELECT "messages".* FROM "messages"
TRANSACTION (0.9ms)  COMMIT
```

### Actual behavior

But instead, in scenario 1, only the first `execute` statement appears to run within the DB transaction. Maybe that is actually expected (albeit surprising to me). In any event it would be interesting to know why that happens.

```
TRANSACTION (0.7ms)  BEGIN
(3.4ms)  SET LOCAL statement_timeout = '5s';
TRANSACTION (0.5ms)  COMMIT
Message Load (0.4ms)  SELECT "messages".* FROM "messages" /* loading for pp */ LIMIT $1  [["LIMIT", 11]]
```

### System configuration
**Rails version**: 7.1

**Ruby version**: 3.2

**Comment by fatkodima** [comment]
Can you create a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb template?

**Comment by orhantoy** [comment]
I think it's because `Message.all` is lazy and doesn't actually execute the SQL query until you iterate the relation.
Try doing `Message.all.load`.

**Comment by fatkodima** [comment]
I am 99% sure this is the case, because of lazy loaded relation, and `transaction` block's return value is the last expression, which is then evaluated in the console for `#inspect`. But let's wait a bit for the OP's response.

**Comment by apmiller108** [comment]
@fatkodima Here's a test script the illustrates the issue using `statement_timeout` and `pg_sleep`. It's weird, but I it demonstrates what we've seen. @orhantoy is correct in that explicitly chaining `.load` makes in behave in the expected way.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "7.1.0"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "test", host: ENV['POSTGRES_HOST'],
                                        username: ENV['POSTGRES_USER'], password: ENV['POSTGRES_PASSWORD'],
                                        encoding: 'unicode', variables: { statement_timeout: '500ms'})
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_local_timeout_is_respected_for_select_query_within_transaction_block
    Post.create!
    assert_raises(ActiveRecord::QueryCanceled) { ActiveRecord::Base.connection.execute('SELECT pg_sleep(0.75);') }

    result = ActiveRecord::Base.transaction do
      ActiveRecord::Base.connection.execute("SET LOCAL statement_timeout = '1000ms'")
      Post.select('id, pg_sleep(0.75)')
    end

    refute_nil result.load
  end
end

```

This will fail with the following output:

```
# Running:

D, [2023-11-28T21:03:11.098585 #2345] DEBUG -- :   TRANSACTION (0.3ms)  BEGIN
D, [2023-11-28T21:03:11.099555 #2345] DEBUG -- :   Post Create (1.3ms)  INSERT INTO "posts" DEFAULT VALUES RETURNING "id"
D, [2023-11-28T21:03:11.100837 #2345] DEBUG -- :   TRANSACTION (1.0ms)  COMMIT
D, [2023-11-28T21:03:11.602731 #2345] DEBUG -- :    (501.6ms)  SELECT pg_sleep(0.75);
D, [2023-11-28T21:03:11.603617 #2345] DEBUG -- :   TRANSACTION (0.4ms)  BEGIN
D, [2023-11-28T21:03:11.604335 #2345] DEBUG -- :    (1.2ms)  SET LOCAL statement_timeout = '1000ms'
D, [2023-11-28T21:03:11.609486 #2345] DEBUG -- :   TRANSACTION (0.4ms)  COMMIT
D, [2023-11-28T21:03:12.110782 #2345] DEBUG -- :   Post Load (500.9ms)  SELECT id, pg_sleep(0.75) FROM "posts"
E

Finished in 1.023967s, 0.9766 runs/s, 0.9766 assertions/s.

  1) Error:
BugTest#test_local_timeout_is_respected_for_select_query_within_transaction_block:
ActiveRecord::QueryCanceled: PG::QueryCanceled: ERROR:  canceling statement due to statement timeout
```

The `Post.load` occurs outside the transaction block and therefore raises the timeout error due to the connection `statement_timeout` having been set to `'500ms'`. As mentioned above by @orhantoy, explicitly chaining `.load` on `Post.select` will make it run within the transaction where the local timeout is set and not raise the timeout error.

**Comment by zzak** [comment]
This is just my guess, but I think that is the behavior of PG, since you are already inside a transaction you cannot reset the previous timeout and the new timeout will only affect following commands. I would suggest investigating that :pray:
