### ISSUE TITLE
FormData Handling Nested Arrays Incorrectly in Rails 7.1.2

### ISSUE THREAD

**Issue by makoto-atarashi** [rails/rails#50227]
### Issue Overview
After upgrading Rails from version 7.0.6 to 7.1.2, FormData that is including nested array sent from frontend is being received differently on backend, causing processing troubles.

### Steps to Reproduce

1. Use the following frontend JavaScript code, which was working correctly with Rails 7.0.6, to send data to backend.

```javascript
let formData = new FormData();

formData.append("items[][foo]", "FOO");
formData.append("items[][bar]", "BAR");
formData.append("items[][baz]", "BAZ");
formData.append("items[][list][][a]", "A");
formData.append("items[][list][][b]", "B");

fetch("/api_url", {
  method: "POST",
  body: formData
})
  .then(response => response.json())
  .then(data => {
    console.log(data);
  })
  .catch(error => {
    console.error(error);
  });
```
2. Upgrade to Rails 7.1.2 and use the same frontend code to send data to the backend again.

### Expected Behavior
Expecting the data to be received on Rails 7.1.2 as it was on Rails 7.0.6.

### Actual Behavior
Data received on Rails 7.0.6 was in the following format:

```txt
Parameters: {"items"=>[{"foo"=>"FOO", "bar"=>"BAR", "baz"=>"BAZ", "list"=>[{"a"=>"A", "b"=>"B"}]}], "host"=>"example.com"}
```

However, on Rails 7.1.2, it has changed as follows, and params[:items][:list] is not received as an array as expected:

```txt
Parameters: {"items"=>[{"foo"=>"FOO", "bar"=>"BAR", "baz"=>"BAZ", "list[]a"=>"A", "list[]b"=>"B"}], "host"=>"example.com"}
```

### Environment

Rails Version: 7.0.6 -> 7.1.2
Ruby version: ruby 3.2.2-p53
Front End: JavaScript, Fetch API

### Specific Issue Points

On Rails 7.0.6, params[:items][:list] was correctly received as an array, but on Rails 7.1.2, params[:items][:list] is not received as an array as expected.

**Comment by fatkodima** [comment]
Same as (similar to) https://github.com/rails/rails/issues/49783 ?

**Comment by orhantoy** [comment]
I don't see a difference between 7.0.6 and 7.1.2 when using that exact JS frontend code with new vanilla Rails apps.
Do you have special middleware or callbacks in your controllers that could be doing something to the params?

**Comment by makoto-atarashi** [comment]
Thank you for your comment. After conducting further investigation, it seems that the root cause of this issue lies in the upgrade of the Rack middleware rather than in Rails itself. Considering this, I am inclined to withdraw this issue here, as it appears to be more relevant to the Rack middleware.
* https://github.com/rack/rack/issues/2128

Would you agree with closing this issue given the context provided? 
Your thoughts or any additional insights on this matter would be appreciated.
