### ISSUE TITLE
Cookie name ["session_id from 7.0.8 to 7.1.0

### ISSUE THREAD

**Issue by leoplct** [rails/rails#50229]
### Steps to reproduce
I have just upgraded from Rails 7.0.8 to 7.1.0 and the cookie name is named _["session_id_ instead of _session_id_.
If I rollback to 7.0.8 it return as _session_id_. 
After that I cannot sign up / log in with Devise due to Invalid authenticity token.

### Expected behavior
The cookie name should be session_id 

### Actual behavior
["session_id

### System configuration
**Rails version**: **7.2.0.alpha** and **7.1.0**
**Ruby version**: 3.1.2

![Screenshot 2023-12-01 at 16 17 33](https://github.com/rails/rails/assets/1176145/47d82254-6474-45b8-8aab-bb5f95da4e41)

I don't know where to look to debug.

**Comment by fatkodima** [comment]
Same as https://github.com/rails/rails/issues/49422 ?

**Comment by leoplct** [comment]
Thank you very much. I confirm that solved the issue. 

I had to:

1. Add to Gemfile

gem 'rack', '~> 2.2'

2.  Upgrade to ruby 3.2.2.
