### ISSUE TITLE
Serializers Not Working with coder: keyword argument

### ISSUE THREAD

**Issue by ddoherty03** [rails/rails#50221]
### Steps to reproduce
Here are three test cases in a gist:

https://gist.github.com/ddoherty03/5da3353436aea3704303976965ca8bd4

### Expected behavior
As I read the docs, using a positional argument with just the name of the class to serve as the serializer is deprecated and I am supposed instead to use the coder: keyword argument with the class name.  In the example, I save a Charge as a string and want to have it cast into a Charge object when read from the DB.  I have used the `serialize :charge, coder: Charge` line to do so.

### Actual behavior
When I do this however, the attribute remains a String and is not de-serialized into the expected class.  The other examples show (1) that it works using a positional class argument `serialize :charge, Charge` and does not work even adding the type keyword, `serialize :charge, coder: Charge, type: Charge`.

### System configuration
**Rails version**:
7.0.8 (and later?)

**Ruby version**:
3.2.2

**Comment by fatkodima** [comment]
You have your `dump` method defined incorrectly - you should not call `chg.to_s`, because `chg` is a `Charge` object. Try to insert debugger there and see what you get.

**Comment by ddoherty03** [comment]
Ok, but chg is a String, so the #to_s should be a no-op.  I changed it, however, to `chg.charge` but still get the same result.

**Comment by fatkodima** [comment]
>  I assume the dump method should convert it to some kind of String from which it can be restored with #load, right?

Yes. See the docs for an example https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize

`.dump` receives a `Charge` object in you case, but you convert it to string via `to_s` and get something like `<#Charge...>` and save it to the database. But you should do something like `"#{chg.charge}:#{chg.serial}"` (or something like this).

**Comment by fatkodima** [comment]
Change to
```ruby
  def self.dump(charge)
    case charge
    when Charge
      charge.charge
    when String
      charge
    end
  end
```

**Comment by ddoherty03** [comment]
Still fails.

**Comment by fatkodima** [comment]
Ah, I tested for the rails `main` branch. This works for me:

```ruby
# frozen_string_literal: true

require "bundler/inline"
require 'debug'

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :entries, force: true do |t|
    t.string :charge
  end
end

class Charge
  attr_reader :charge, :reason, :serial

  def initialize(chg_string)
    chg_string = chg_string.to_s
    /\A\s*(?<charge>.*?)(?:#(?<serial>[0-9]+))?\s*\z/ =~ chg_string
    @charge = charge
    @serial = serial
    @reason = ''
  end

  def self.load(str)
    new(str)
  end

  # Writing to the db as a string
  def self.dump(charge)
    case charge
    when Charge
      charge.charge
    when String
      charge
    end
  end
end

class Entry < ActiveRecord::Base
  serialize :charge, coder: Charge
end

class BugTest < Minitest::Test
  def test_association_stuff
    ent = Entry.create!
    ent.charge = "x:insur"
    ent.save
    id = ent.id

    ent2 = Entry.find(id)
    assert_equal Charge, ent2.charge.class
  end
end
``` 

For rails `7.0.8` you need to change `serialize` definition to use positional argument instead of keyword.
