### ISSUE TITLE
Question on ActiveRecord connection pool and schema cache dump

### ISSUE THREAD

**Issue by aravindhbw** [rails/rails#50224]
We are running a Rails unicorn web application which forks 3 processes during startup time which will then be used to process requests. We noticed a small increase in latency during startup time because Rails lazily runs the `SHOW FULL FIELDS` command for each table as and when it is queried to collect metadata. To avoid this we turned on schema cache dump using the `rake db:schema:cache:dump` command so that the metadata is collected eagerly. However since unicorn recommends re-establishing connections after forking, the cache dump is lost.

Rails version `5.2.8.18`

```
after_fork do |server, worker|
  # connection re-established so cache dump which was copied from the main process is lost
  ActiveRecord::Base.establish_connection if defined?(ActiveRecord::Base)
end
```

1. Why do we need to re-establish connections after forking?
2. If that is required, how can we reload the schema cache dump after the connection is re-established?

One alternative we tried was to take a copy of the parent schema cache before forking and set it to the child process after forking

```
parent_schema_cache = nil
before_fork do |server, worker|
  ActiveRecord::Base.connection_handler.clear_all_connections! if defined?(ActiveRecord::Base)
  parent_schema_cache = ActiveRecord::Base.connection.schema_cache if defined?(ActiveRecord::Base)
end

after_fork do |server, worker|
  ActiveRecord::Base.establish_connection if defined?(ActiveRecord::Base)
  ActiveRecord::Base.connection_pool.schema_cache = parent_schema_cache.dup
end
```

3. This doesn't look clean. Is there a better way to load the schema dump after forking?
4. How does integrating makara affect this setup where we run a primary db and few replica dbs? Does active record maintain separate connection pools for each db? If so, how does the schema cache get set for each connection pool?

Thanks in advance!

**Comment by fatkodima** [comment]
Hey @aravindhbw, we reserve the Rails Issues tracker for bugs in the framework as we don't have the bandwidth to offer application support. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help with your application. Thanks for understanding.
