### ISSUE TITLE
ActiveJob::Serializers::TimeWithZoneSerializer does not preserve the timezone

### ISSUE THREAD

**Issue by jakubkosinski** [rails/rails#50230]
### Steps to reproduce

```ruby
require 'active_job'
require 'active_job/arguments'
require 'active_support/all'

Time.zone = 'Europe/London' #=> "Europe/London"
time = Time.zone.parse('2023-12-01T14:30:00Z') #=> Fri, 01 Dec 2023 14:30:00.000000000 GMT +00:00
serialized_time = ActiveJob::Serializers::TimeWithZoneSerializer.serialize(time) #=> {"_aj_serialized"=>"ActiveJob::Serializers::TimeWithZoneSerializer", "value"=>"2023-12-01T14:30:00.000000000+00:00"}
gmt_deserialized_time = ActiveJob::Serializers::TimeWithZoneSerializer.deserialize(serialized_time) #=> Fri, 01 Dec 2023 14:30:00.000000000 GMT +00:00
Time.zone = 'America/Los_Angeles' #=> "America/Los_Angeles"
pst_deserialized_time = ActiveJob::Serializers::TimeWithZoneSerializer.deserialize(serialized_time) #=> Fri, 01 Dec 2023 06:30:00.000000000 PST -08:00
Time.zone = nil #=> nil
utc_deserialized_time = ActiveJob::Serializers::TimeWithZoneSerializer.deserialize(serialized_time) #=> 2023-12-01 14:30:00 +0000
```

### Expected behavior

Since `ActiveSupport::TimeWithZone` stores information about the time zone I expect that this information should be preserved when serializing time. Changing the `Time.zone` should not affect objects serialized with a different time zone.

### Actual behavior

Deserialization of a serialized `TimeWithZone` uses always the current `Time.zone` and not the one that was used to create a `TimeWithZone` object instance.

### System configuration
**Rails version**:
6.1.7.1 but the behaviour is the same in 7.x

**Ruby version**:
3.1.3p185

**Comment by joshuay03** [comment]
I don't know what the expected outcome here is and hopefully someone from one of the core team(s) can confirm, but I got a PR up anyway cause your expected outcome makes sense to me and it was pretty straightforward to implement: https://github.com/rails/rails/pull/50240
