### ISSUE TITLE
Should we allow update associations from nested_attributes not only by id?

### ISSUE THREAD

**Issue by ngoral** [rails/rails#50253]
It is not an issue, but a question with a suggestion.
At the moment, if I use `accepts_nested_attributes_for`, the associations will update only if I pass `id`. But sometimes it's just not a case. Sometimes we can find a unique record for update without id. By the id of the parent record and some other field of the association.

The following may be not the best example in real world, but I hope everyone would understand the concept.
Let's say we have a user and his notes. And we want notes of a user to have unique names.
```ruby
class User < ApplicationRecord
  has_many :notes
  accepts_nested_attributes_for :notes
end

class Note < ApplicationRecord
  belongs_to :user
  validates :title, uniqueness: { scope: :user_id }
end
```

And, let's say we have the API, and user does not know the ids of the notes, because.. why should they? =)
In that case I would receive a request with following parameters: `{ user: { foo: bar, notes_attributes: [{ title: 'I do not know the id', content: 'boo' }] } }`. Having these parameters I would have to either not use nested attributes and do everything by myself, or could process attributes, finding the id of every record and adding it to the attributes.

But if only we could find records by some other field...
Something like this: `accepts_nested_attributes_for :notes, key: :title`. And it will find the records for update by this key, not by id.
I took a glance on the NestedAttributes sources and it seems doable. And I could try to do it, but just wanted to know if there are some arguments against such behavior and functions.

What do you think?

**Comment by fatkodima** [comment]
This seems like a feature request, but we reserve GitHub issues for issues in the Rails framework.
Please use the [Rails forum](https://discuss.rubyonrails.org/) for the discussion first.
