### ISSUE TITLE
ActiveRecord: where.associated and where.missing produce an extra join vs using where / where.not with a check for nil

### ISSUE THREAD

**Issue by nickjj** [rails/rails#50283]
### Steps to reproduce

Here's an example where I have (2) models: `Receipt` and `Affiliate`

- An affiliate `has_many :receipts`
- A receipt `belongs_to :affiliate, optional: true`

#### associated vs where.not

Both of them produce a list of `receipts` that have an `affiliate_id` set:

```rb
Receipt.where.associated(:affiliate)
SELECT "receipts".* FROM "receipts" INNER JOIN "affiliates" ON "affiliates"."id" = "receipts"."affiliate_id" WHERE "affiliates"."id" IS NOT NULL /* loading for pp */ LIMIT $1  [["LIMIT", 11]]

Receipt.where.not(affiliate: nil)
SELECT "receipts".* FROM "receipts" WHERE "receipts"."affiliate_id" IS NOT NULL /* loading for pp */ LIMIT $1  [["LIMIT", 11]]
```

#### missing vs where

Both of them produce a list of `receipts` that don't have an `affiliate_id` set:

```rb
Receipt.where.missing(:affiliate)
SELECT "receipts".* FROM "receipts" LEFT OUTER JOIN "affiliates" ON "affiliates"."id" = "receipts"."affiliate_id" WHERE "affiliates"."id" IS NULL /* loading for pp */ LIMIT $1  [["LIMIT", 11]]

Receipt.where(affiliate: nil)
SELECT "receipts".* FROM "receipts" WHERE "receipts"."affiliate_id" IS NULL /* loading for pp */ LIMIT $1  [["LIMIT", 11]]
```

### Expected behavior

- `Receipt.where.associated(:affiliate)` produces the same query as `Receipt.where.not(affiliate: nil)`
- `Receipt.where.missing(:affiliate)` produces the same query as `Receipt.where(affiliate: nil)`

### Actual behavior

- `Receipt.where.associated(:affiliate)` creates an extra join
- `Receipt.where.missing(:affiliate)` creates an extra join

### System configuration

**Rails version**: 7.1.1

**Ruby version**: 3.2.2

**Database adapter / version**: Postgres 15.4

**Comment by fatkodima** [comment]
Can you create a reproduction script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_gem.rb template?

**Comment by nickjj** [comment]
I'll give it a shot, I didn't test this locally so I'm not sure if it runs but the asserts do check to see if both sets return the same query.

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :affiliates, force: true do |t|
  end

  create_table :receipts, force: true do |t|
    t.integer :affiliate_id
  end
end

class Affiliate < ActiveRecord::Base
  has_many :receipts
end

class Receipt< ActiveRecord::Base
  belongs_to :affiliate, optional: true
end

class BugTest < Minitest::Test
  def test_query_equality
    assert Receipt.where.associated(:affiliate).to_sql == Receipt.where.not(affiliate: nil).to_sql
    assert Receipt.where.missing(:affiliate).to_sql == Receipt.where(affiliate: nil).to_sql
  end
end
```

**Comment by fatkodima** [comment]
These methods were meant to be worked with all the association types, not only `belongs_to`. But yeah, for `belongs_to` we can remove the extra `join` (unless I am missing something). But giving that this is not a bug, but just the implementation details, I am not sure if this is worth changing (maybe for shorter and faster? queries). 

Let's wait for core people opinions.

**Comment by nickjj** [comment]
From a DSL / readability POV I think using `.associated` and `.missing` is more natural. In my opinion if they act differently than their where nil counterparts it makes for a less intuitive API and also makes it easier to write less efficient queries.

Given a large class of performance issues are related to waiting for the database, if it's possible to remove the extra join it feels worth it?

**Comment by aidanharan** [comment]
I don't think this is a bug and works as expected. The purpose of `associated` is to communicate the presence of the association. See https://github.com/rails/rails/pull/40696

So `Receipt.where.not(affiliate: nil)` only checks whether:
- The affiliate ID is not NULL.

Whereas `Receipt.where.associated(:affiliate)` is checking whether:
- The affiliate ID is not NULL, and
- The affiliate exists.

The check for whether the affiliate exists requires the query to include the join. 

The [API documentation](https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods/WhereChain.html#method-i-associated) for `associated` is explicit that the join is on purpose:

> associated(*associations)
>    Returns a new relation with joins and where clause to identify associated relations.

The method `missing` mirrors `associated` and it uses the join clause for similar reasons (see https://github.com/rails/rails/pull/34727).

**Comment by fatkodima** [comment]
Yes, you are absolutely right. The "The affiliate exists." point is very important.

**Comment by nickjj** [comment]
Thanks, yeah my previous reply about them returning different results sort of confirmed the join is necessary to obtain that information. Thanks for the clarification, it seems like both query types have their own intended use cases.
