### ISSUE TITLE
Support for Cookies Having Independent Partitioned State (CHIPS)

### ISSUE THREAD

**Issue by JonLatane** [rails/rails#50288]
### Steps to reproduce
Chrome and other browsers are phasing out third-party cookies. Many embedding applications that rely on them will need CHIPS support, as documented here: https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies. The tl;dr is that we need to be able to add `Partitioned;` into our `Set-Cookie` headers. We already have `same_site` and `secure` cookie options that work like this (`secure` is, in fact, identical).

The nearest I've found documentation on this is here: https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/middleware/cookies.rb#L184 But I'm not quite sure where the cookies are actually converted into a header string, so not clear on how to add CHIPS support.

### Expected behavior
Adding `partitioned: true` to an ActionDispatch cookie header hash, as described above, should add `Partitioned;` to the resulting `Set-Cookie` header string.

### Actual behavior
Adding `partitioned: true` to an ActionDispatch cookie header hash does nothing.

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.3

**Comment by lohithmv019** [comment]
we are also facing the same issue. Need a patch similar to the one we had during the "same_site" cookie implementation.

**Comment by zzak** [comment]
Related: rack/rack#2131

We reserve GitHub Issues for bug reports, and this is a [feature request](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark), please start a discussion on the [forum](https://discuss.rubyonrails.org/c/rubyonrails-core). :bow:
