### ISSUE TITLE
calling `ActiveSupport::Cache.lookup_store` in application.rb (or environments/*.rb) causes deprecation warning

### ISSUE THREAD

**Issue by nov** [rails/rails#50293]
### Steps to reproduce

call `ActiveSupport::Cache.lookup_store` w/ default `config.active_support.cache_format_version` under `config.load_defaults 7.0`

at that timing, `ActiveSupport::Cache.format_version` is still [the default `6.1`](https://github.com/rails/rails/blob/c1489a8ca4a9b91e21725f6a139e82e803c9eaa6/activesupport/lib/active_support/cache.rb#L55), thus causes [this warning](https://github.com/rails/rails/blob/c1489a8ca4a9b91e21725f6a139e82e803c9eaa6/activesupport/lib/active_support/cache.rb#L773-L778)

sample app is here. you can see the warning just by running it.
https://github.com/nov/rails7_1_sample

### Expected behavior

no warning.

### Actual behavior

```
% rails server
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.

Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more information on how to upgrade.
```

### System configuration
**Rails version**:

**Ruby version**:

**Comment by fatkodima** [comment]
Duplicate of https://github.com/rails/rails/issues/49892 and https://github.com/rails/rails/issues/49543

**Comment by nov** [comment]
OK, so the only workaround is https://github.com/rails/rails/issues/49543#issuecomment-1760134318

thus like this
```ruby
ActiveSupport::Cache.lookup_store = config.active_support.cache_format_version # call this first
config.cache_store = ActiveSupport::Cache.lookup_store :redis_cache_store # then lookup store 
```

**Comment by skipkayhil** [comment]
There's no need for any workaround. The default value of `6.1` is deprecated, and if you try to use that version you will receive a deprecation warning.

The fix is to use `7.0` for the `cache_format_version`

**Comment by nov** [comment]
no, as you can see, I'm getting this warning even I'm setting `cache_format_version` to `7.1`.

https://github.com/nov/rails7_1_sample/blob/c140d6ed7b8a4350416f267f6af41d126b25b30c/config/application.rb#L12-L27

**Comment by skipkayhil** [comment]
Ah, sorry about that. In the original issue you had said `load_defaults 7.0` so I assumed your reproduction used that as well. I'll reopen because I agree your reproduction looks like a bug.

**Comment by skipkayhil** [comment]
So the issue is that `load_defaults 7.1` sets `config.active_support.cache_format_version`, but that setting doesn't get copied to `ActiveSupport.cache_format_version` until initializers run (particularly `"active_suport.set_configs"`).

I'm not sure if there's anything easy we can do to make this possible. Is there a reason you can't set `cache_store` to a symbol so that it can be looked up during an initializer?

**Comment by nov** [comment]
We might can rewrite the `lookup_store` part for `cache_store`, but now we're sharing the same cache loader class for `cache_store` (setup in `application.rb`) and `session_store` (setup in `initializsers/session_store.rb`) sharing various redis options w/ different namespace.
If we can keep that, it would be better.

**Comment by rubyrider** [comment]
@fatkodima @nov I have proposed a pull request that fix this issue:
https://github.com/rails/rails/pull/50434

Please let me know if this is okey or further changes are required :)
