### ISSUE TITLE
Comments inside helper files affecting views

### ISSUE THREAD

**Issue by stxss** [rails/rails#50307]
Hey! I found some weird behavior while developing my most recent project, and was able to reproduce it with a brand new app, but I'm not sure the scope of this issue is limited to js/css bundling, as file contents were read/accessed when they were not supposed to.

### Steps to reproduce

Create a brand new rails app

```bash
rails new myapp -d postgresql --css=tailwind --javascript=esbuild
bundle add inline_svg # using this gem to render svg's
rails db:create
rails g scaffold posts
rails db:migrate
bin/dev
```
```ruby
# config/routes.rb
root "posts#index"
```

Create a new `app/assets/images/svg/` folder, where you save any svg you want. I placed the solid `sun` and `moon` icons from [heroicons](https://heroicons.com/)

```ruby
# app/helpers/icons_helper.rb

module IconsHelper
  def sun_icon
    inline_svg_tag("svg/sun.svg", class: "sun fill-black stroke-black ")
  end

  def moon_icon
    inline_svg_tag("svg/moon.svg", class: "moon fill-black stroke-black")
  end
end
```
```erb
# app/views/posts/index.html.erb

<%= sun_icon %>
<%= moon_icon %>
```

### Expected behavior

The page should just present a simple svg, not bound by any height styles, and adding TailwindCSS classes as comments should not affect the style of the elements.

### Actual behavior

You'll see 2 big svg's that occupy the whole page. 

Now, in this small app example, if you add `# h-6` anywhere in the `app/helpers/icons_helper.rb` or `<%# h-6 %>` in the `app/views/posts/index.html.erb` file and reload the page, the icons will indeed have a h-6 (1.5rem) applied, which, from my understanding, **should not** happen. 

In my personal project, removing this css class, closing the server and running `bin/dev` again, messed with all the svg files and every element that had a `h-6` applied to it. 

The weird thing with this as well, at least in my case, is that it only happens when that specific string 'h-6' is removed or added to the files and the server is restarted. So if you start the server, go to the page, add the string to the helper/view file in any way and restart the page, changes will be made and if that string is removed nothing will happen until you restart the server.

I'll attach a video to showcase what exactly is happening if my explanation isn't clear.

https://github.com/rails/rails/assets/93729036/5c91651c-115c-4287-b2de-39dcb44d2663

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**Comment by stxss** [comment]
Wow, thank you so much for the fast response!

Thanks for clarifying that, because I couldn't find anything that could explain such behavior, so now it makes sense to me. 

And yeah, what also had bugged me, was that h-6 was already applied to the svg's, and in my personal project, messing with that class on another, not related element, messed with all of the elements containing that class.

But even so, it personally still feels wrong for the file to include classes that are clearly commented out or not specified in the code, because in my case, all my svg files for some reason got reduced and the h-6 wasn't properly applied (unless i had that string of text in any view file, even if commented out) to a different height and it was because i took out one element that wasn't even related to the svg's and completely outside of the div that contained those images. It took me quite some time to figure out why my icons were essentially broken, and since there was no error whatsoever, there was no stack trace to go off of, figuring out the culprit was pretty annoying. 

Do you think it is worth to open this issue with Tailwind, or just leave this specific behavior be?

**Comment by skipkayhil** [comment]
> Do you think it is worth to open this issue with Tailwind, or just leave this specific behavior be?

I think it's working as intended: https://tailwindcss.com/docs/content-configuration#class-detection-in-depth Tailwind doesn't know anything about comments, its literally just scanning the whole file for the class strings.

You _should_ add the folder where you are putting your svgs to the `tailwind.config.js` file so that they are included when scanning for classes to ensure `w-6` and `h-6` are always included btw

**Comment by stxss** [comment]
oooh i see, my bad for not checking the documentation more thoroughly.

> By the way, you should add the folder where you are putting your svgs to the tailwind.config.js file. That'll ensure w-6 and h-6 are included when scanning for classes.

This really solved the issue, wonderful.

Thank you so much for your help and explanation, it really made this make sense for me!
