### ISSUE TITLE
Rails 7.1: query_constraints: preloading already loaded association cause a query without conditions.

### ISSUE THREAD

**Issue by yosiat** [rails/rails#50310]
When I am trying to use `query_constraints` I found a bug where doing `preload` on already loaded association, we get a `SELECT * FROM table` query without `WHERE` conditions.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.0"
  gem "pg"
end

require "active_record"
require "logger"

ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  database: "test",
  encoding: "unicode",
  host: "localhost",
  port: "5432",
  password: "12345",
  username: "test")

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
    t.integer :tenant_id
    t.integer :post_id
    t.integer :author_id
    t.string :body
    t.integer :position
  end

  create_table :posts, force: true do |t|
    t.integer :tenant_id
  end

  create_table :author, force: true do |t|
    t.integer :tenant_id
  end
end

class Post < ActiveRecord::Base
  query_constraints :tenant_id, :id

  has_many :comments
end

class Author < ActiveRecord::Base
  query_constraints :tenant_id, :id
end

class Comment < ActiveRecord::Base
  query_constraints :tenant_id, :id

  belongs_to :post
  belongs_to :author
end

post = Post.create!(tenant_id: 1)
post.comments << Comment.create(body: "hello", tenant_id: 1, author: Author.new(tenant_id: 1))
post.save!


# Preloading here for already loaded association (author)
# Causes `SELECT * FROM author` query
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Associations::Preloader.new(records: post.comments, associations: [:author]).call
```

Output:
```
-- create_table(:comments, {:force=>true})
   -> 0.0343s
-- create_table(:posts, {:force=>true})
   -> 0.0069s
-- create_table(:author, {:force=>true})
   -> 0.0086s
D, [2023-12-09T16:01:05.744467 #68584] DEBUG -- :   Comment Load (0.2ms)  SELECT "comments".* FROM "comments" WHERE "comments"."tenant_id" = $1 AND "comments"."post_id" = $2  [["tenant_id", 1], ["post_id", 1]]
D, [2023-12-09T16:01:05.746333 #68584] DEBUG -- :   Author Load (0.2ms)  SELECT "authors".* FROM "authors"
```

### Expected behavior

1. No additional queries should be done - since associations are already loaded
2. In my opinion: A query without conditions should be avoided at all cost, and if we got to invalid-state we should throw an error.

### Troubleshooting

From my simple investigation: looks like `keys_to_load` (here - https://github.com/rails/rails/blame/main/activerecord/lib/active_record/associations/preloader/association.rb#L89) is empty set and `already_loaded_records_by_key` contains the already loaded data.

I am not sure if adding guard of `return if keys_to_load.empty?` is correct, because this code don't look specific to `query_constraints` so I assume something else is going on here.

### System configuration
**Rails version**: `7.1`
**Ruby version**: `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]`

**Comment by nvasilevski** [comment]
hey, thanks for the report! I just wanted to add that `ActiveRecord::Associations::Preloader` is private and not supposed to be used directly by applications. So in many cases this will not be considered as a bug as long as internal classes/methods work as intended when utilized through the public APIs. 

However understanding that despite of being private `Preloader` is still being used often and considering the simplicity of the fix I think it was worth addressing.

**Comment by yosiat** [comment]
@fatkodima  thanks for fixing the issue! 

@nvasilevski I understand that this is private API and we limit the usages of it in our code-bases so only specific case.. it just happen that you have array of models like `Post.all.to_a` and you want to preload relations (to save some n+1), and currently from what I know there is no good API/solution for this.
