### ISSUE TITLE
`Where(relation: )` broken for polymorphic records when using composite primary keys

### ISSUE THREAD

**Issue by jackozi** [rails/rails#50318]
### Steps to reproduce

When creating a polymorphic association with composite primary keys where(relation: model) is broken. 

- Create a model with composite primary key (e.g. Post as commentable) 
- Point another model towards it with a polymorphic relation (e.g Comment)
- Comment.where(commentable: post) will raise: `ArgumentError: Expected corresponding value for ["commentable_title", "commentable_author"] to be an Array`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, primary_key: [:title, :author], force: true do |t|
    t.string :title
    t.string :author
  end

  create_table :comments, force: true do |t|
    t.string :commentable_title
    t.string :commentable_author
    t.string :commentable_type
  end
end

class Post < ActiveRecord::Base
  has_many :comments, query_constraints: %i[commentable_title commentable_author], as: :commentable
end

class Comment < ActiveRecord::Base
  belongs_to :commentable, query_constraints: %i[commentable_title commentable_author], polymorphic: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(title: "post", author: "author")
    post.comments << Comment.create!

    assert Comment.where(commentable: post).exists?
  end
end
```

### Expected behavior
Correct collection should be returned. 

### Actual behavior
Error is raised instead 

### System configuration
**Rails version**: edge 

**Ruby version**: 3.2.2

**Comment by jackozi** [comment]
Fixed it [here](https://github.com/jackozi/rails) by enabling `_read_attribute` to handle arrays since the primary key is coming in array form. This solved the testcase in the bug report.

**Comment by fatkodima** [comment]
I do not think that that fix is correct, because the method's name and signature indicates that `attr_name` should be a single value.

I was able to come up with another solution. Going to open a PR.
