### ISSUE TITLE
Inaccurate documentation for config.active_support.executor_around_test_case

### ISSUE THREAD

**Issue by semaperepelitsa** [rails/rails#50344]
The guide says:

> [3.14.17 config.active_support.executor_around_test_case](https://guides.rubyonrails.org/configuring.html#config-active-support-executor-around-test-case)
> Configure the test suite to call `Rails.application.executor.wrap` around test cases.

But the actual implementation calls `executor.perform`

https://github.com/rails/rails/blob/531643244474446efc061b559504ed67acc8cae1/activesupport/lib/active_support/executor/test_helper.rb#L3-L7

I don't know myself what is the actual difference with `wrap` - the method is marked as "nodoc".

**Comment by skipkayhil** [comment]
From reading #43550, it looks like the difference is that `#wrap` can not be nested, but `#perform` can. As you mention, `#perform` is not actually documented so I'm not sure if it's worth explaining the difference.

cc @byroot in case I'm misunderstanding

**Comment by byroot** [comment]
Yes, it's a private API and don't need to be reflected.

**Comment by semaperepelitsa** [comment]
I see. It still looks wrong to me to say that `Rails.application.executor.wrap` is called when the actual method is different (even slightly). For the record, I think the changelog entry explains it much better:

> `Rails.application.executor` hooks are now called around every tests.

In any case, I just wanted to make sure it is not a mistake.

**Comment by semaperepelitsa** [comment]
The documentation was added in https://github.com/rails/rails/commit/fbd11abe46c200729365f53571de67aead38edab 

cc @rafaelfranca

**Comment by skipkayhil** [comment]
> For the record, I think the changelog entry explains it much better:
> 
> > `Rails.application.executor` hooks are now called around every tests.
> 
> In any case, I just wanted to make sure it is not a mistake.

That seems fine to me if you want to open a PR
