### ISSUE TITLE
[feature request] Add support for returning Symbols for ActiveRecord enums

### ISSUE THREAD

**Issue by postmodern** [rails/rails#50350]
ActiveRecord enums allow defining an enum attribute for a finite set of Symbol names, or even a mapping of Symbols to underlying String values.

```ruby
class Order < ActiveRecord::Base

  enum status: [:active, :completed, :rejected]
  
end
```

Currently (ActiveRecord 7.1) the Symbol names actually are converted into Strings.

```ruby
order = Order.new(status: :active)
order.status
# => "active"
```

This seems a little counter-intuitive, since the user is explicitly specifing a set of Symbols. It would be useful if there was some kind of keyword argument option, or even another method, that would allow returning Symbols instead of Strings.

```ruby
class Order < ActiveRecord::Base

  enum status: [...], _symbolize: true
  
end
```

**Comment by eileencodes** [comment]
Hey @postmodern thanks for opening an issue. This is a duplicate [issue](https://github.com/rails/rails/issues/49981) with an [open PR](https://github.com/rails/rails/pull/49982) already. So I'm going to close this.

For future reference, we don't take feature requests on the issues tracker and encourage folks to use [the forum](https://discuss.rubyonrails.org/) for that.
