### ISSUE TITLE
Don't make Trilogy the default for MySQL until they solve it working with current default MySQL configuration

### ISSUE THREAD

**Issue by andyjeffries** [rails/rails#50355]
I saw it will be the default in the next major release (https://rubyonrails.org/2023/10/5/Rails-7-1-0-has-been-released) but it doesn't support the default MySQL authentication mechanism.

https://github.com/trilogy-libraries/trilogy/issues/26#issuecomment-1737467740

Please don't make it the default until this issue has been solved.

**Comment by eileencodes** [comment]
We're aware of the issues with `caching_sha2_password` and it's something I'm personally working on, but it's not going to happen before the new year. Also both GH and Shopify are running on Trilogy so we're not going to forget to wait for this change to make Trilogy the default in 7.2.
