### ISSUE TITLE
Loading an async null / @none=true relation causes a method not implemented error

### ISSUE THREAD

**Issue by walski** [rails/rails#50351]
### Steps to reproduce

Unfortunately I wasn't able to create an executable test case but if you change [this AR test case](https://github.com/rails/rails/blob/ee65e97829e1d09a00047958273656d3b6488924/activerecord/test/cases/relation/load_async_test.rb#L32-L42) to become:

```ruby
    def test_scheduled?
      deferred_posts = Post.where(author_id: 1).load_async
      if in_memory_db?
        assert_not_predicate deferred_posts, :scheduled?
      else
        assert_predicate deferred_posts, :scheduled?
      end
      assert_predicate deferred_posts, :loaded?
      deferred_posts.to_a
      assert_not_predicate deferred_posts, :scheduled?

      ## ADDED THESE TWO LINES ##
      none_posts = Post.none.load_async.to_a
      assert_not_predicate deferred_posts, :scheduled?
    end
```

And then run `bundle exec ruby -Itest test/cases/relation/load_async_test.rb  -n 'test_scheduled?'`

It hopefully gets close to a standalone test. If somebody can help me get a standalone test that can inherit from `ActiveRecord::TestCase`, I could also put up a real executable test case.

### Expected behavior

No exception is raised.

### Actual behavior

NoMethodError: undefined method `!' for #<ActiveRecord::Promise status=complete>
    /Users/walski/Desktop/rails_bug/rails-main/activerecord/lib/active_record/relation.rb:716:in `scheduled?'

### System configuration
**Rails version**: `main` but also `7.1.2`

**Ruby version**: 3.2.2

### Possible cause

I think for null / `@none = true` relations, [this code](https://github.com/rails/rails/blob/ee65e97829e1d09a00047958273656d3b6488924/activerecord/lib/active_record/relation.rb#L963) causes `@future_result` to be an `ActiveRecord::Promise` which does explicitly not implement `!`. While for normal (`@none = false`) relations `@future_result` is a `ActiveRecord::FutureResult` which DOES implement `!`.

**Comment by fatkodima** [comment]
Was able to come up with the following
```diff
diff --git a/activerecord/lib/active_record/promise.rb b/activerecord/lib/active_record/promise.rb
index 4e9b2ff06e..1d1f95d91b 100644
--- a/activerecord/lib/active_record/promise.rb
+++ b/activerecord/lib/active_record/promise.rb
@@ -62,6 +62,7 @@ def status

       class Complete < self # :nodoc:
         attr_reader :value
+        alias_method :result, :value

         def initialize(value)
           @value = value
diff --git a/activerecord/lib/active_record/relation.rb b/activerecord/lib/active_record/relation.rb
index 1cd2d054a6..f154655527 100644
--- a/activerecord/lib/active_record/relation.rb
+++ b/activerecord/lib/active_record/relation.rb
@@ -713,7 +713,11 @@ def load_async
     # Returns <tt>true</tt> if the relation was scheduled on the background
     # thread pool.
     def scheduled?
-      !!@future_result
+      if @future_result.respond_to?(:nil?)
+        !@future_result.nil?
+      else
+        true
+      end
     end

     # Causes the records to be loaded from the database if they have not
```

But curious, why we need to undefine `!` here https://github.com/rails/rails/pull/44446/files#diff-aa5588044046f5f03c6b00de7a2d18d997632b763a4c53b97ec9870782e99056R5?

cc @byroot

**Comment by lucasmazza** [comment]
I have a working patch at https://github.com/rails/rails/pull/50353 that I tested with our app. Running `MyModel.none.load_async` on a console was enough to get the `NoMethodError` exception

**Comment by byroot** [comment]
> Why we need to undefine `!` here

The reasoning is that a common mistake with promises is to use the promise object directly instead of it's value. So I wanted to make this mistake raise an error rather that silently return the wrong boolean.
