### ISSUE TITLE
respond_to not working

### ISSUE THREAD

**Issue by raoehtesham03** [rails/rails#50363]
### Steps to reproduce

```ruby
def index
      respond_to do |format|
        format.html {
          binding.pry
          @client_count = policy_scope(Client.group("clients.id")).count
          @client_count = @client_count.is_a?(Hash) ? @client_count.keys.size : @client_count
          if @client_count == 1
            client = policy_scope(Client).order("clients.name").first
            redirect_to client_landing_url(host: client.domain)
          end
        }
        format.json do
          binding.pry
          @clients = policy_scope(ClientService.get_list(params, current_user.system_admin?))
          serialize_clients = ClientService.serialize_clients(@clients)

          render json: serialize_clients
        end
      end
   end
```

### Actual behavior
    
   while hitting this url http://admin.localtest.me/admin/clients , it is not going into the format.json loop.
   Please help me to figure out this.
### System configuration
**Rails version**: 6.1.7.6

**Ruby version**: 2.7.8

**Comment by fatkodima** [comment]
Hey @aoehtesham03 we reserve the Rails Issues tracker for bugs in the framework as we don't have the bandwidth to offer application support. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help with your application. Thanks for understanding.
