### ISSUE TITLE
async_count returns a Integer instead of a Promise

### ISSUE THREAD

**Issue by guillaumebriday** [rails/rails#50399]
### Steps to reproduce

When being cached, sometime the `#async_count` method returns an Integer instead of a Promise

```ruby
projects = policy_scope(Project)
projects.async_count
#  CACHE Project Count (0.1ms)  SELECT COUNT(*) FROM "projects" WHERE "projects"."team_id" = $1

#=> 792 
```

I found a workaround adding useless a `where`
```ruby
projects = policy_scope(Project.where('1=1')
projects.async_count
#=> #<ActiveRecord::Promise status=pending>
```

### Expected behavior
In my views, I call it with `.value` and it raises an error because it's an Integer and not a `#<ActiveRecord::Promise status=pending>`

### System configuration
**Rails version**: Latest

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
Can you provide a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb template?

**Comment by guillaumebriday-pa** [comment]
Let me do that, i'll need some time 👍

**Comment by guillaumebriday-pa** [comment]
@fatkodima There you go 👉  https://github.com/guillaumebriday-pa/async_count_bug/blob/main/app/controllers/posts_controller.rb#L5 

(It's a brand new rails app here)

I wasn't able to reproduce it in the AR bug report template, and the bug only happens when the query is cache, here with Pagy

**Comment by rubyrider** [comment]
I tried reproducing with active record bug report template. Doesn't look like an query cache issue! perhaps more context needed?

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  gem 'psych', '5.1.2'
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    1000.times { |i| Post.create! }

    @posts = Post.all

    @post_count = @posts.async_count

    @post_count = @posts.async_count
    
    assert_respond_to @post_count, :value
  end
end

```

**Comment by guillaumebriday-pa** [comment]
@rubyrider Thank you for you answer 👍 

I tried to do exactly what you did in the template but here the queries are not cached for some reasons, and that is why it works as expected. But as soon as the cache mechanism occurs, like in my example with Pagy, it does not work anymore.

![Screenshot 2023-12-20 at 16 07 39](https://github.com/rails/rails/assets/89008587/c7d3bb45-4ffb-4f7f-a1e4-6a85759a03bd)


Can you pull this example and try on your side? https://github.com/guillaumebriday-pa/async_count_bug

**Comment by fatkodima** [comment]
I was able to find the problem and a solution. Going to open a PR.

**Comment by rubyrider** [comment]
@fatkodima what is your findings can you share?

**Comment by fatkodima** [comment]
Incorrect working with query caching while using async queries.

**Comment by guillaumebriday** [comment]
Thank you so much @fatkodima for your reactivity! 🙏
