### ISSUE TITLE
With SQLite3 Database incorrect command output for 'bin/rails db:drop'.

### ISSUE THREAD

**Issue by maniSHarma7575** [rails/rails#50391]
### Steps to reproduce

1. Create a new Rails app.
```ruby
rails new sqlite-db-drop
```

2. Run the `db:drop` command.
```ruby
bin/rails db:drop
```

3. Output of the above command.
```shell
Dropped database 'storage/development.sqlite3'
Database 'storage/test.sqlite3' does not exist
```

Upon closer inspection, it is observed that for the non-existing database `storage/development.sqlite3` on the disk, the command output displays `Dropped database 'storage/development.sqlite3'`. Instead, it should state `Database 'storage/development.sqlite3' does not exist`.

### Research:

Upon investigating the code, I discovered the following:

In the ActiveRecord SQLite3 adapter code at 

https://github.com/rails/rails/blob/462e8e8b1c74d46a78e7077c5b07bfbc6fab08b0/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb#L31-L39

It appears that every time a new connection to SQLite3 is established, an attempt is made to create a database due to the default configuration settings.

This behavior is defined in the SQLite3 Ruby gem code, specifically at 

https://github.com/sparklemotion/sqlite3-ruby/blob/302e9c0328bff2bb04e1d4a54614140ca06f3648/lib/sqlite3/database.rb#L91-L101

You can also refer to the relevant documentation [here](https://rubydoc.info/gems/sqlite3/SQLite3%2FDatabase:initialize), which outlines supported permission options.

Each time a new connection to the database is established (used for dropping the database or executing other commands), the connection first attempts to create a database and then proceeds to drop it.

An issue arises when an exception is raised in the code snippet below, as it doesn't work as intended. The SQLite3 database is created with the default mode of `READWRITE | CREATE`. Consequently, a new database is created every time, even if it already exists. 

```ruby
rescue Errno::ENOENT => error 
   if error.message.include?("No such file or directory") 
     raise ActiveRecord::NoDatabaseError 
   else 
     raise 
   end 
 end 
```

You can read about. Why Sqlite3 Gem has not forced Safe Check on the database initialization only if database exist?
[https://github.com/sparklemotion/sqlite3-ruby/pull/174](https://github.com/sparklemotion/sqlite3-ruby/pull/174)

Have created a PR to fix: [https://github.com/rails/rails/pull/50392](https://github.com/rails/rails/pull/50392)

### Expected behavior

```shell
bin/rails db:drop
Database 'storage/development.sqlite3' does not exist
Database 'storage/test.sqlite3' does not exist
```

### Actual behavior

```shell
bin/rails db:drop
Dropped database 'storage/development.sqlite3'
Database 'storage/test.sqlite3' does not exist
```

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.2.2

**Comment by maniSHarma7575** [comment]
PR: https://github.com/rails/rails/pull/50392

**Comment by maniSHarma7575** [comment]
@fatkodima @yahonda , could you please check it? I am facing an issue with fixing the test case. Does the PR come with breaking changes? Can you please help me with that?"

**Comment by maniSHarma7575** [comment]
@byroot Could you please take a moment to review changes? I'm seeking your valuable input to ensure that I've taken the correct approach in addressing the issue. The pull request is #50392

**Comment by zzak** [comment]
@maniSHarma7575 Please don't ping maintainers without their acknowledgement, many people are also away during the holidays so you will have to be patient, and try asking for feedback in [discord](https://rubyonrails.org/2022/6/13/rails-discord-server-is-now-open-to-the-public) after sometime has passed.
