### ISSUE TITLE
Fragment caching raises "undefined method `capture' for "<!DOCTYPE html>....."

### ISSUE THREAD

**Issue by lfekson** [rails/rails#50401]
### Steps to reproduce

config.load_defaults 7.1
With haml using:
- cache any_object do
  =# any_output, e.g.
  = render 'something'

I was able to receive an output without raising error only when manually replaced in actionview-7.1.2/lib/action_view/helpers/cache_helper.rb, line 285:
fragment = output_buffer.capture(&block)
onto:
fragment = @output_buffer.capture(&block)

As debugging showed, output_buffer's class is "String" that doesn't have the "capture" method.

```ruby
# Your reproduction script goes here
```

### Expected behavior

Rendering 'something'

### Actual behavior

Raised an error: undefined method `capture' for "<!DOCTYPE html>....full html text of the page where the fragment should be rendered..."
### System configuration
**Rails version**:
7.1.2
**Ruby version**:
3.2.2

**Comment by fatkodima** [comment]
Can you create a sample app that reproduces the issue?

**Comment by skipkayhil** [comment]
I think this was fixed in #49612, can you try `7-1-stable` branch?

**Comment by lfekson** [comment]
@skipkayhil, I tried to get actionview from the 7-1-stable branch, resulting error is the same.

**Comment by lfekson** [comment]
Looks like it was haml-rails that affected the fragment cache helper: with haml-rails 2.1.0 no issues, at least the "undefined method capture" error is not raised. Previously used version was 2.0.1.

**Comment by panaak** [comment]
> Looks like it was haml-rails that affected the fragment cache helper: with haml-rails 2.1.0 no issues, at least the "undefined method capture" error is not raised. Previously used version was 2.0.1.

With rails 7.1.3.4 the haml-rails update to 2.1.0 didn't work for me. undefined method `capture' raised on any attempt of fragment caching.
Only downgrade to rails 7.0.8.4 fixes it.

**Comment by panaak** [comment]
Full bundle update followed by upgrade back to rails 7.1.3.4 seems to have fixed the issue.

**Comment by kzink** [comment]
Ran into this issue also - upgrading both `haml-rails` and `haml` gems to the latest resolved it with rails `7.1.4`. Make sure you `Rails.cache.clear` to verify!

**Comment by franee** [comment]
Using `rails 7.1`. This is fixed by upgrading to `haml-rails 3.0.0` &  `haml 7.2.0`.
