### ISSUE TITLE
Example Docker file fails (7.1.2)

### ISSUE THREAD

**Issue by brodjustice** [rails/rails#50402]
### Steps to reproduce
```
$ rails new empty_rails_app -d postgresql
...
$ cd empty_rails_app/
$ docker build --progress=plain -t empty_rails_app .
...
$ docker run -p 3000:3000 empty_app_2
bin/rails aborted!
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit`
/rails/config/environment.rb:5:in `<main>'
Tasks: TOP => db:prepare => db:load_config => environment
(See full trace by running task with --trace)
```
This can be worked around by removing the `config/master.key` from `.dockerignore` and setting `config/master.key` file to readable. Maybe I'm missing an essential concept, but while this it might be called bad practice to share credentials in this manner, I don't see how the Docker image could ever function without master.key access to those credentials.

I've also considered and tried passing the credentials via `.env` and `docker-compose.yml` but this also fails because of the same issue: the `master.key` needs to be in the Docker image.

Or am I missing something obvious?

### System configuration
Rails 7.1.2
Ruby 3.0.0p0

**Comment by maniSHarma7575** [comment]
@brodjustice You can solve this issue by passing an environment variable `RAILS_MASTER_KEY`

```
docker run -p 3000:3000 -e RAILS_MASTER_KEY="Paste key here from config/master.key" empty_rails_app
```

**Comment by bparanj** [comment]
If @maniSHarma7575 suggestion works. It should be added to the documentation.

**Comment by brodjustice** [comment]
@bparanj  I quickly tried the suugestion, but the suggestion doesn't work for me either, though for possibly different reasons. Output is below. I'll try to dig into this a bit more later this week.

```
$ docker run -p 3000:3000 -e RAILS_MASTER_KEY=83ad0d41fa85ca30372114ad16e9d655 empty_rails_app
bin/rails aborted!
ActiveSupport::MessageEncryptor::InvalidMessage: 
/rails/config/environment.rb:5:in `<main>'
Tasks: TOP => db:prepare => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by bparanj** [comment]
@brodjustice It seems like line 5 in the environment.rb is causing the issue. Things to check:

- Is the RAILS_MASTER_KEY correct?
- Ensure that the `master.key` or `credentials.key` file exists and is correct. This file is used to decrypt encrypted files like `credentials.yml.enc`.
- Delete any old Docker images for empty_rails_app. Create a new Docker image and try again.
- If the master key is corrupt, you may have to re-encrypt credentials

**Comment by softwaregravy** [comment]
I have independently confirmed that the commandline including the correct rails master key is working. 

```bash
$ cat config/master.key
56c2424517b428203a33f2b7b019daaa
$  docker run -p 3000:3000 -e RAILS_MASTER_KEY="56c2424517b428203a33f2b7b019daaa" -e DATABASE_URL=postgresql://xxx:@host.docker.internal/rails_50402_development rails-50402
```

Inserting a typo into that master key gives me the error reported.

**Comment by bparanj** [comment]
I have created a PR for the documentation change: https://github.com/rails/rails/pull/50509

**Comment by dhh** [comment]
Yeah, you need a RAILS_MASTER_KEY to boot. It's expected that you pass this in as you start your Docker container.

**Comment by krtschmr** [comment]
```
 => ERROR [build 6/6] RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile                                                                                                             4.4s
------                                                                                                                                                                                           
 > [build 6/6] RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile:
4.289 bin/rails aborted!
4.289 SassC::SyntaxError: Error: Custom property values may not be empty. (SassC::SyntaxError)
4.289         on line 12:33648 of stdin
4.289 >>  2))}.form-select{--bs-form-select-bg-img:url("data:image/svg+xml,%3csvg x
4.289    ------------------------------------------^
4.290 
4.290 Tasks: TOP => assets:precompile
4.290 (See full trace by running task with --trace)
------
Dockerfile:47
--------------------
  45 |     
  46 |     # Precompiling assets for production without requiring secret RAILS_MASTER_KEY
  47 | >>> RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile
  48 |     
  49 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile" did not complete successfully: exit code: 1

```

the `build` still fails. maybe we need a better explanation. or the question is , shall `rails new` + `docker build` pass?

**Comment by dhh** [comment]
Don't you have your answer of what's wrong right here:

```
SassC::SyntaxError: Error: Custom property values may not be empty. (SassC::SyntaxError)
4.289         on line 12:33648 of stdin
4.289 >>  2))}.form-select{--bs-form-select-bg-img:url("data:image/svg+xml,%3csvg x
```

**Comment by krtschmr** [comment]
true. my bad. was in wrong project space. `rails new` and `docker build` works! 🚀
