### ISSUE TITLE
Generates wrong sql query for infinite date ranges

### ISSUE THREAD

**Issue by owen2345** [rails/rails#50409]
### Steps to reproduce

```ruby
Patient.where(created_at: Date.today..).to_sql
=> "SELECT \"patients\".* FROM \"patients\" WHERE \"patients\".\"created_at\" >= '2023-12-20'"
Patient.where(created_at: Date.today...).to_sql
=> "SELECT \"patients\".* FROM \"patients\" WHERE \"patients\".\"created_at\" >= '2023-12-20'"
Patient.where(created_at: ..Date.today).to_sql
=> "SELECT \"patients\".* FROM \"patients\" WHERE \"patients\".\"created_at\" <= '2023-12-20'"
Patient.where(created_at: ...Date.today).to_sql
=> "SELECT \"patients\".* FROM \"patients\" WHERE \"patients\".\"created_at\" < '2023-12-20'"
```

### Expected behavior
The expected behavior for the second example is `created_at > '2023-12-20'` without equal (excluding the first day) similar to the fourth one.

### Actual behavior
The resulting query is not excluding the first date.

### System configuration
**Rails version**:
- Rails 7.1
- Also tried in Rails 6.1

**Ruby version**:
- ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]
- Also tried in 2.6

**Comment by fatkodima** [comment]
`Date.today..` and `Date.today...` are the same thing. `...` applies only to the right hand side of the range, so this is not a bug.
