### ISSUE TITLE
`find_by` is broken when passing an instance that uses composite primary keys

### ISSUE THREAD

**Issue by claracodes** [rails/rails#50411]
Big thanks for adding support for composite primary keys. We’ve implemented them and seen big performance gains - we’re using them on partitioned tables! 
However, `find_by` seems to be broken when trying to pass in an instance that uses composite primary keys.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "7.1.2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, primary_key: [:id, :company_id], force: true do |t|
    t.integer :id
    t.integer :company_id
  end

  create_table :profiles, primary_key: :id, force: true do |t|
    t.integer :user_id
    t.integer :company_id
  end
end

class User < ActiveRecord::Base
  has_one :profile
end

class Profile < ActiveRecord::Base
  belongs_to :user, query_constraints: [:user_id, :company_id]
end

class BugTest < Minitest::Test
  def test_find_by
    user = User.create!(id: [1, 1])
    profile = Profile.create(id: 1, user_id: 1, company_id: 1)

    assert_equal profile, Profile.find_by(user: user)
  end
end
```

**Comment by fatkodima** [comment]
Was able to reproduce, going to open a PR.

**Comment by bparanj** [comment]
See: https://edgeguides.rubyonrails.org/active_record_composite_primary_keys.html. It says:

Take caution when using find_by(id:) on models where :id is not the primary key, such as composite primary key models. See the [Active Record Querying](https://edgeguides.rubyonrails.org/active_record_querying.html#using-id-as-a-condition) guide to learn more.

This does not seem to be a valid bug.

**Comment by fatkodima** [comment]
We do not use `find_by(id:)` in the test case.
