### ISSUE TITLE
Wrong Ruby Version in Gemfile

### ISSUE THREAD

**Issue by VSPPedro** [rails/rails#50413]
### Steps to reproduce

1. Install ruby 3.0.3-rc1.
2. Create a new rails project using  7.0.8: `rails _7.0.8_ new project`
3. Result:

```
     ...
      create  tmp/storage
      create  tmp/storage/.keep
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_7_0.rb
      run  bundle install
      Your Ruby version is 3.3.0.rc1, but your Gemfile specified 3.3.0
```

### Expected behavior
The ruby version in the Gemfile should be 3.3.0-rc1.

### Actual behavior
The ruby version in the Gemfile is 3.3.0. Because of that it raises an error:

`Your Ruby version is 3.3.0.rc1, but your Gemfile specified 3.3.0`

### System configuration
**Rails version**: 7.0.8
**Ruby version**: 3.3.0-rc-1

### Context
I'm working on updating tests for a Ruby library, and the CI is trying to run Rails using different Ruby versions. I'm thinking about whether I should skip this scenario.

Thank you for everything. You guys are the best!

**Comment by yahonda** [comment]
This feature is added at Rails 7.1 via https://github.com/rails/rails/pull/47584 , not feasible to back port to older versions of Rails because this is a new feature.

**Comment by VSPPedro** [comment]
Thank you for the details. I understand.
