### ISSUE TITLE
Using `:destroy_async` with `has_many` causes `delete_all` to default to nullify, leading to foreign key errors

### ISSUE THREAD

**Issue by ZempTime** [rails/rails#50421]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "active_job/railtie"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.references :post, foreign_key: true, null: false
  end
end

class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy_async
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!
    
    # The following assertion will fail with:
    # ActiveRecord::NotNullViolation: SQLite3::ConstraintException: NOT NULL constraint failed: comments.post_id
    post.comments.delete_all

    assert_equal 0, post.comments.count
    assert_equal 0, Comment.count
  end
end
```

### Expected behavior
I'd expect `delete_all` to delete the table records without invoking any callbacks, and not default to the nullification strategy.

If this is the expected behavior, we'll want to add `:destroy_async` as one of the conditions here:
https://github.com/rails/rails/blob/18b8f37192430c1f468551d1006b90430dd8d61a/activerecord/lib/active_record/associations/collection_association.rb#L155

### Actual behavior
`delete_all` will nullify the foreign key, causing a foreign key error which aborts the transaction.

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.2.2

### Other relevant facts

One of the main reasons to use `dependent: :destroy_async` is to manage situations where a record has many other related records and destroying those in the background can prevent request timeouts or out of memory errors (ex: 7.1 adds [batching](https://github.com/rails/rails/pull/44617) support).

I ran into this behavior in our tests. The resolution was explicitly specifying `delete_all(:delete_all)`. I didn't expect `delete_all` to raise this error because I'm explicitly calling it and want to sidestep all the callbacks/running background jobs for test state setup. I'm guessing this is how and where most people might run into this behavior.

In the documentation [here](https://edgeguides.rubyonrails.org/association_basics.html), there is a note:

> :destroy_async: when the object is destroyed, an ActiveRecord::DestroyAssociationAsyncJob job is enqueued which will call destroy on its associated objects. Active Job must be set up for this to work. Do not use this option if the association is backed by foreign key constraints in your database. The foreign key constraint actions will occur inside the same transaction that deletes its owner.

However since `delete_all` skips callbacks, I don't think this applies.

I understand that the current behavior might be intentional, but if it's determined to be an oversight and there's interest in updating it, I would be more than happy to get a pr together for this. Please let me know what would be helpful.

**Comment by fatkodima** [comment]
Yes, because you should not use `:destroy_async` with a foreign key and should call `.destroy` on a parent record, not `delete_all` on the association.
