### ISSUE TITLE
Add BACKTRACE env variable to turn off backtrace for normal running, not just tests

### ISSUE THREAD

**Issue by dhh** [rails/rails#50440]
You can turn off the backtrace cleaner by setting the BACKTRACE env variable during testing. But you should be able to do the same during normal operations too. If you want to run a command or even IRB without the backtrace cleaner active, this should be possible with the same BACKTRACE env variable flag.

**Comment by bparanj** [comment]
Will the following change work:

```ruby
# frozen_string_literal: true

require "active_support/backtrace_cleaner"
require "active_support/core_ext/string/access"

module Rails
  class BacktraceCleaner < ActiveSupport::BacktraceCleaner # :nodoc:
    APP_DIRS_PATTERN = /\A(?:\.\/)?(?:app|config|lib|test|\(\w*\))/
    RENDER_TEMPLATE_PATTERN = /:in `.*_\w+_{2,3}\d+_\d+'/

    def initialize
      super
      
      unless ENV['BACKTRACE']
        @root = "#{Rails.root}/"
        add_filter do |line|
          line.start_with?(@root) ? line.from(@root.size) : line
        end
        add_filter do |line|
          if RENDER_TEMPLATE_PATTERN.match?(line)
            line.sub(RENDER_TEMPLATE_PATTERN, "")
          else
            line
          end
        end
        add_silencer { |line| !APP_DIRS_PATTERN.match?(line) }
      end
    end
  end
end
```

**Comment by dhh** [comment]
That's a bit too deep. We should apply this where the Backtrace Cleaner is getting setup. Not inside the class itself.

**Comment by nimir** [comment]
For turning off the Backtrace Cleaner in rails console, I am thinking of surrounding the IRB prepend statement at: [(https://github.com/rails/rails/blob/main/railties/lib/rails/commands/console/console_command.rb#L38)](https://github.com/rails/rails/blob/main/railties/lib/rails/commands/console/console_command.rb#L38) with a check in, something like:

```ruby
...
@console = app.config.console || begin
  require "irb"
  require "irb/completion"

  unless options[:full_backtrace] || ENV["BACKTRACE"]
    IRB::WorkSpace.prepend(BacktraceCleaner)
  end

  if !Rails.env.local?
    ENV["IRB_USE_AUTOCOMPLETE"] ||= "false"
  end

  IRB
end
...

```

I am also thinking of adding a test in `ConsoleTest` ... However, I am not yet sure what a minimal test should be. My first idea is to start a mocked_console with an app that has some code raising an exception and we assert that a full backtrace is shown when the flag is on. Makes sense?

Regarding all commands, is it a good idea to make the change on the `backtrace_cleaner` method at [https://github.com/rails/rails/blob/main/railties/lib/rails.rb#L55](https://github.com/rails/rails/blob/main/railties/lib/rails.rb#L55) ? it also felt too deep!

**Comment by bparanj** [comment]
Write a failing test for the new behavior. Implement your current approach and make it pass. The test should be for both on and off scenarios.

**Comment by nimir** [comment]
For the console, here are the two tests I added to `console_test.rb`:

```ruby
def test_console_disables_backtrace_cleaner_when_BACKTRACE_env_is_set
    switch_env "BACKTRACE", "true" do
      app = build_app(nil)
      console = Rails::Console.new(app).console

      assert_not_includes console::WorkSpace.included_modules, Rails::Console::BacktraceCleaner
    end
  end

  def test_console_enables_backtrace_cleaner_when_BACKTRACE_env_is_not_set
    switch_env "BACKTRACE", "false" do
      app = build_app(nil)
      console = Rails::Console.new(app).console

      assert_includes console::WorkSpace.included_modules, Rails::Console::BacktraceCleaner
    end
  end
```

and to make the first one pass, I've made the following change to `console_command.rb`:

```diff
-IRB::WorkSpace.prepend(BacktraceCleaner)
+IRB::WorkSpace.prepend(BacktraceCleaner) unless ENV["BACKTRACE"]
```

I appreciate if someone can let me know if this is ok? Also I need pointing in the right direction for what other cases we need to disable the `BacktraceCleaner` other than console?

This is my first attempt to contribute to rails, I learned that DRAFT PRs are not encouraged so instead i am sharing my progress here!

**Comment by bparanj** [comment]
1. `$ export BACKTRACE=1`
2. Go inside the rails console and `raise "my exception"` as a quick test.
3. You should be able to see the full backtrace in the console.

Turn it off and test the negative case also. I think you can use the dummy rails app embedded inside the Rails codebase for this purpose.

**Comment by nimir** [comment]
@bparanj thanks for the feedback, the proposed fix in my last comment already addresses the feature of turning on/off for backtrace in rails console. I've tested it with a dummy app and through the newly added tests.

But from @dhh issue description I understood this has other cases beyond console, and I needed some directions on that so I can complete the feature.

Thanks

**Comment by bparanj** [comment]
Other cases are:

```
rails server
```

```ruby
rails runner
```

I created tester.rb in the root of the project:

```ruby
puts 'This is a test runner'

raise 'Test exception for backtrace'
```

Any command we run should use that env variable. Here is my test:

```
gitpod /workspace/rails-docs (main) $ rails runner tester.rb
This is a test runner
/workspace/rails-docs/tester.rb:3:in `<main>': Test exception for backtrace (RuntimeError)
        from /workspace/.rvm/ruby-3.2.2/gems/railties-7.1.2/lib/rails/commands/runner/runner_command.rb:41:in `load'
        from /workspace/.rvm/ruby-3.2.2/gems/railties-7.1.2/lib/rails/commands/runner/runner_command.rb:41:in `block in perform'
        from /workspace/.rvm/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/execution_wrapper.rb:92:in `wrap'
        from /workspace/.rvm/ruby-3.2.2/gems/railties-7.1.2/lib/rails/commands/runner/runner_command.rb:40:in `perform'
        from /workspace/.rvm/ruby-3.2.2/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
        from /workspace/.rvm/ruby-3.2.2/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /workspace/.rvm/ruby-3.2.2/gems/railties-7.1.2/lib/rails/command/base.rb:178:in `invoke_command'
        from /workspace/.rvm/ruby-3.2.2/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
        from /workspace/.rvm/ruby-3.2.2/gems/railties-7.1.2/lib/rails/command/base.rb:73:in `perform'
        from /workspace/.rvm/ruby-3.2.2/gems/railties-7.1.2/lib/rails/command.rb:71:in `block in invoke'
        from /workspace/.rvm/ruby-3.2.2/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
        from /workspace/.rvm/ruby-3.2.2/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
        from /workspace/.rvm/ruby-3.2.2/gems/railties-7.1.2/lib/rails/commands.rb:18:in `<main>'
        from <internal:/home/gitpod/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/home/gitpod/.rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /workspace/.rvm/ruby-3.2.2/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by ghiculescu** [comment]
@dhh Before https://github.com/rails/rails/pull/43237 new apps got an initializer that helped with this. It looked like this:

https://github.com/rails/rails/blob/e21c38ed7f9161e07e73afe2899f26ab7a260231/railties/lib/rails/generators/rails/app/templates/config/initializers/backtrace_silencers.rb.tt

We could bring it back?

**Comment by nimir** [comment]
In learning more about the source code, I tracked down when the old `backtrace_silencers.rb.tt` was removed to see why? i guess it was mainly to avoid having too many initializers 

Incase it can be useful, Here is the PR https://github.com/rails/rails/pull/43237

So as @ghiculescu suggested, we could have it back or apply it in the `railties/lib/rails/BacktraceCleaner.rb`

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/commit/f4c9d0b014e3c1c27c3d5db73dbf42c48733a1b6 it seems we remove this feature

**Comment by rafaelfranca** [comment]
We don't need to bring back the initializer, we can just make this a default initializer inside `railties/lib/rails/application.rb`.
