### ISSUE TITLE
Solid Queue should be the default Active Job backend for Rails 8

### ISSUE THREAD

**Issue by dhh** [rails/rails#50442]
[Solid Queue](https://github.com/basecamp/solid_queue) should be the default Active Job backend for Rails 8 since it supports all our major databases and enables someone to run jobs in production without either additional dependencies (like Redis), using database-specific backends (like Good Job), or using commercially-restrained backends (like Sidekiq).

The necessary tables should be setup by default as part of rails new. The user should not have to do any configuration whatsoever to be able to deploy their application in production with Solid Queue as the job runner. We also need to figure out a standardized setup for running the worker jobs, especially as part of the default Dockerfile setup.

You should be able to avoid this using `--skip-solid-queue` or just `--skip-solid`.

cc @rosa

**Comment by rosa** [comment]
👍 👍  Feel free to assign it to me.

**Comment by mtparet** [comment]
Do not forget to add required database specificity.. like running full vacuum in postgresql to avoid full bloated table (simple vacuum is not enough for intensity table queue usage ) and MySQL optimize for MySQL database.

**Comment by dhh** [comment]
@mtparet That's a good thing to perhaps have general ergonomics for, but it's out of scope for this.

**Comment by nickjj** [comment]
> We also need to figure out a standardized setup for running the worker jobs

I don't know if this is the spot for this but what about using Docker Compose? It was made for running 1 or more containers associated with a specific project. Here's a working example https://github.com/nickjj/docker-rails-example that runs Postgres, Redis, Puma, Action Cable, Sidekiq, esbuild and Tailwind. Everything is spun up with a single `docker compose up` command. Nothing needs to be installed on the host except for Docker / Docker Compose.

It could easily be modified to run whatever Solid Queue processes are needed instead of Sidekiq.

**Comment by ghiculescu** [comment]
Would you include https://github.com/rails/rails/issues/26045 in the Rails 8 milestone?

**Comment by AhmedKamal20** [comment]
Do you know if this will be accompanied by Mission Control or not necessary?
and if not would Mission Control be released seperetly by then?

Thanks

**Comment by dhh** [comment]
#26045 looks different now that we can offer transactional guarantees by default. Need to consider the upgrade path closely, though. But don't want to cut people off from the significant benefit of transactional guarantees if their setup allows it (like a default Solid Queue installation does).

**Comment by dhh** [comment]
I'd like to see Mission Control by default as well, yes. But let's see if we can get it good enough in time for Rails 8. First we gotta release it 😄

**Comment by sergiotapia** [comment]
Don't know if this is helpful but in Elixir, we can use Oban for queues/jobs. All jobs are persisted in Postgres. https://github.com/sorentwo/oban

Maybe some good ideas could be plucked from Oban!

**Comment by ds-jcaro** [comment]
Hi! I'm a Rails newbie. I just added Solid Queue to my 7.1 rails project, the experience was greatly simple.
The downside is that in the development environment, all the queries are logged, and now my console is full of Solid queue polling queries.
It would be great if you document how we could filter those queries, or even better if it is done by default.

**Comment by kidandcat** [comment]
Hi! I'm a Rails newbie. I just added Solid Queue to my 7.1 rails project, the experience was greatly simple.
The downside is that in the development environment, all the queries are logged, and now my console is full of Solid queue polling queries.
It would be great if you document how we could filter those queries, or even better if it is done by default.

**Comment by rosa** [comment]
@kidandcat you can silence these with [the `silence_polling` setting](https://github.com/basecamp/solid_queue?tab=readme-ov-file#other-configuration-settings). I think having this set to `true` by default makes sense, I'll look into it!

**Comment by brenogazzola** [comment]
Since we now have a default backend for jobs, maybe we should add a rails command for it? We have one for server and console, but not one for the workers. Having a `rails w` seems more friendly than `bundle exec rake solid_queue:start` when you are already using to running `rails s` and `rails c`

```
aliases = {
  "g"  => "generate",
  "d"  => "destroy",
  "c"  => "console",
  "s"  => "server",
  "db" => "dbconsole",
  "r"  => "runner",
  "t"  => "test"
}
```

**Comment by dhh** [comment]
Great point @brenogazzola. Yes, we should definitely have that. And allow any of the job backends to hook into it.

**Comment by brenogazzola** [comment]
I've never taken a look at this part of Rails, but I found the `server_command.rb` file and I can take a stab at doing something similar for the worker.

**Comment by AnushatRently** [comment]
Hello, I am having the queuing backend system as delayed_job for now. I am planning to migrate to either solid_queue or sidekiq. To decide the queuing backend system, what I need to consider?

**Comment by brenogazzola** [comment]
@AnushatRently You will have better chance of getting an answer to this question by asking in the official forum, since it's more visible:

https://discuss.rubyonrails.org/

**Comment by devsaimsohail** [comment]
Hey. I have been searching a lot that you can we handle the CRON jobs using the Solid Queue but Unfortunately did not get any viewpoint from any Resource from any where. As I am shifting my application from Sidekiq to Solid Queue and I have many background jobs that automatically trigger themselves using the CRON.
For Example:
update_all_calls_data:
    every: '1h'
    class: Schedules::UpdateAllCallsDataJob
 As I am shifting from solid Queue so I also want to control all my jobs using the Solid Queue at that moment.
 
 And also a second thing that you have mentioned that **cron-like tasks are coming very soon.** I just want to know that when cron-like tasks will be available?

**Comment by rosa** [comment]
Hey @devsaimsohail, no ETA on when they'll be ready, but you can follow https://github.com/basecamp/solid_queue/issues/104 to be notified when that happens!

**Comment by devsaimsohail** [comment]
> Hey @devsaimsohail, no ETA on when they'll be ready, but you can follow [basecamp/solid_queue#104](https://github.com/basecamp/solid_queue/issues/104) to be notified when that happens!

I am just Curious to know Does whenever Gem works with Solid Queue?

**Comment by robzolkos** [comment]
> Does whenever Gem works with Solid Queue

Whenever has access to your Rails application via rake or the rails runner, so you can queue up jobs using that (its not specific to solid_queue).

**Comment by fractaledmind** [comment]
@rosa: When the PR to land this opens, I am going to open a corresponding PR to update the `/railties/lib/rails/generators/rails/app/templates/config/databases/sqlite3.yml.tt` template to use a separate `queue` database when Solid Queue is enabled as the ActiveJob backend and SQLite is the database.

**Comment by dhh** [comment]
This is done 👍
