### ISSUE TITLE
Add a default LSP for better editor/IDE support in Rails 8

### ISSUE THREAD

**Issue by dhh** [rails/rails#50453]
@tenderlove made [a very compelling argument](https://www.youtube.com/watch?v=GnqRMQ0iQTg&t=33m40s) for including an official Rails LSP in the framework at Rails World. Let's make it so.

Shopify is doing work in https://github.com/Shopify/ruby-lsp-rails.

**Comment by halimsamy** [comment]
Maybe [Solargraph](https://solargraph.org/)?

**Comment by thedumbtechguy** [comment]
> Maybe [Solargraph](https://solargraph.org/)?
This is more of a rails framework server than a language server.

It just piggybacks on the lsp standard to interface with editors.

**Comment by gobijan** [comment]
The ruby-lsp-rails gem works fine in its current state. I use it for development everyday. From installation point of view it is enough to just include it in the gemfile under development. Is this the scope of this issue? Change the generator template?

**Comment by andyw8** [comment]
Hi @gobijan,

We (the ruby-lsp-rails maintainers) are working with some Rails Core members on a change to how the LSP is run. Once that is complete we can hopefully make it available by default for new Rails applications.

cc @vinistock

**Comment by gobijan** [comment]
Thx for clarification @vinistock 
I really like the work you’re doing and am super hyped for all the improvements this will bring to our editing workflow.

**Comment by ismailarilik** [comment]
For VS Code, one line of code is enough, that is:

```json
// .vscode/extensions.json
{
  "recommendations": [
    ...
    "Shopify.ruby-extensions-pack"
    ...
  ]
}
```

**Comment by h4sohail** [comment]
It would be great if we could get LSP features in erb files as well. I find it cumbersome to manually search for methods I come across in erb files by searching for `def method_name`. I should be able to just right-click a method in a erb file with VSCode or some editor and go to the definition.

**Comment by johannesschobel** [comment]
I guess, it would be better to add it to the `devcontainer.json` file, instead of the `.vscode/extensions.json` file, as the `.devcontainer/devcontainer.json` file is used from now on to have a "unified development environment".

```jsonc
// .devcontainer/devcontainer.json
{
  // ... normal configuration here

  "customizations": {
    "vscode": {
      "extensions": [
        "Shopify.ruby-lsp"
      ]
    }
  }
}
```

This will add the `ruby-lsp` extension to the devcontainer when installing / building the latter. So there is no need to install it manually. It can then be updated via the "extensions" panel from VSCode...

All the best,
Johannes

**Comment by rafaelfranca** [comment]
Just FYI, the generated devcontainer configuration already comes with the LSP installed. This issue is more for folks that aren't going to use devcontainers, or will not use vscode.

**Comment by dhh** [comment]
With a default vscode setup for this, I think we're better off leaving integration with other editors as a documentation issue at this point.

**Comment by ascarter** [comment]
The Zed editor (spiritual successor to Atom) just added support for ruby-lsp as the language server. Maybe a doc that other editors could drop in a link for how to use ruby-lsp and use VS Code as the default example?

https://github.com/zed-industries/zed/pull/11768

**Comment by brunoprietog** [comment]
At least now, by default Rails does not create the .vscode folder with the extensions.json file. In that file the Ruby LSP extension is supposed to be recommended. So, the default setting for VS Code only works if you are going to use devcontainers and VS Code, but it won't recommend by default the extension if you don't plan to use them, which I understand is the initial idea of this, right? Is that something you would like to see? The json should look something like this:

```json
{
	// See https://go.microsoft.com/fwlink/?LinkId=827846 to learn about workspace recommendations.
	// Extension identifier format: ${publisher}.${name}. Example: vscode.csharp

	// List of extensions which should be recommended for users of this workspace.
	"recommendations": [
		"redhat.vscode-yaml",
		"shopify.ruby-lsp"
	],
	// List of extensions recommended by VS Code that should not be recommended for users of this workspace.
	"unwantedRecommendations": [
		
	]
}
```

Happy to contribute if you want
