### ISSUE TITLE
Default PWA files

### ISSUE THREAD

**Issue by dhh** [rails/rails#50455]
While [Action Notifier](https://github.com/rails/rails/issues/50454) brings the most interesting part of the PWA puzzle to the table, we should also ensure that the basic configuration files are just there to be filled in. That means serving a webmanifest, a default logo, and a service-worker.js file from root. This isn't hard right now, but it's a little clumsy, due to the fact that the service worker, for example, has to live in the root. So let's just smooth that all out.

**Comment by kwhandy** [comment]
Adding standard for PWA integration can help us to acquire google's TWA which allow us to deploy rails webapp as android app then publish it to google play so users can find + install our product from there(even you have to do $25 one-time payment to google play)

but still I don't know if apple app store also allow us to publish TWA app or not, but if they can, that gonna be rock

**Comment by joemasilotti** [comment]
I'm very excited for this one! Especially because it could help unlock some doors around offline caching for Turbo Native apps.

**Comment by jcmaciel** [comment]
@dhh Congratulations on directing this version of our Rails to PWA. I've been betting on it since 2019, where I've been applying it to all my B2B software.

Very excited, thank you!

**Comment by khoerodin** [comment]
Finally after a long wait

**Comment by dhh** [comment]
First stab here: https://github.com/rails/rails/pull/50528/

**Comment by dhh** [comment]
The defaults in https://github.com/rails/rails/pull/50528 are good enough for now. Will extend the default service-worker in more detail as part of Action Notifier.
