### ISSUE TITLE
In rails 7.1  it is not possible to test path helpers in controllers tests when an application uses config.relative_url_root different to "/"

### ISSUE THREAD

**Issue by vtamara** [rails/rails#50461]
### Steps to reproduce

Let's say I want to run an application on the mount point `/a/` and I want all my resources on that mount point (e.g `/a/users/`).

Using as I traditionally would:

1. `config.relative_url_root="/a/"` and
2. `scope "/a"` in `routes.draw` to recognize routes within the mount point "/a"

At least with rails 6.x, 7.0 and 7.1 the resulting path helpers are different to the working routes as the following test case shows:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"
  config.relative_url_root = "/a/"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    scope "/a" do
      get "/" => "test#index", as: :root
    end
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def index
    render plain: "Home"
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods
  include Rails.application.routes.url_helpers

  def test_workingroute_root_is_a_in_6_7_and_7_1
    get "/a"  # This one works
    assert last_response.ok?
  end

  def test_root_path_different_to_workingroute_root_in_6_7_and_7_1
    puts root_path  # Will present "/a/a"
    get root_path # No route matches [GET] "/a/a"
    assert last_response.ok?
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior

 `root_path` should be `/a`

### Actual behavior

The helper `root_path` is returning `/a/a` and that route in reality doesn't work, the route that works is `/a`.

With rails 7.1 and previous if I remove the `scope "/a"` from `routes.draw`, `root_path` becomes `/` that is not what is needed.

### Remarks

Thinking in how to implement this in rails, I see two options:
1. not prefixing path helpers with `relative_url_root` since a `scope "/a"` should be already present in `routes.draw` (maybe just presenting a warning when declared routes in `routes.draw`  are outside of `/a` ?).
2. not requiring `scope "/a"` in `routes.draw` but rails should automatically parse routes starting with the prefix  `config.relative_url_root`

I guess that the first solution is simpler to implement and that was the behaviour for routes of mounted engines up to rails 7.0 (behaviour changed/broken in rails 7.1 as described at https://github.com/rails/rails/issues/49688  with this short PR by @bensheldon https://github.com/rails/rails/pull/45719 as described in the same issue ).

### System configuration

**Rails version**: 7.1  although this problema happened in 7.0 and 6.x also.

**Ruby version**: 3.2.2

**Comment by bensheldon** [comment]
hey @vtamara 👋🏻 I remember responding to you over in #49688. In [my PR](https://github.com/rails/rails/pull/45719), I think this note under "Other Information" is very relevant:

> The existing tests imply that the proper way to mount Rails with a relative url root is to customize `config.ru` with a `map` directive, which produces the `SCRIPT_NAME` which Rails handles implicitly and correctly for the main Application and Mounted Engines. 
> 
> The `config.relative_url_root` seems to be intended _only_ for generating paths outside of a request/controller/view (e.g. when using `*.routes.url_helpers.some_path`).

In reference to my first paragraph, I think that the application is set up confusingly, if not incorrectly (example: `root` is not the same as `as: :root`, which you have nested below the root of the Rails Rack App); at minimum, it omits the set up of Rack and/or any path-rewriting webservers (nginx, apache, etc). The latter is why your tests are failing: you have not changed the test harness's Rack mount point for the Rails Rack App to account for the `config.relative_url_root`. 

In reference to my second paragraph, I think you are violating the purpose of `config.relative_url_root` by using `include Rails.application.routes.url_help` in your Controllers; the Controllers' existing URL helpers should be correct.

Also, I did say I would do a pass at the documentation. I have not yet done that 😊

**Comment by vtamara** [comment]
Hi @bensheldon , thanks for the answer.

I started this new bug report because in our discussion at https://github.com/rails/rails/issues/49688, at the end I described the problem that I present here without any answer from you.

In the test case I presented here, I understand the confussion of `as :root`,  it is possible to change it by `as :index`, also `root_path` should be replaced by  `index_path`, but the result is the same.

Also it is possible to remove `include Rails.application.routes.url_helpers` from the controller but the result is the same.

In the simple example application https://gitlab.com:vtamara/app49688 I changed `config/routes.ru` to be:
```
require_relative "config/environment"                                                                                                                           
map "/a" do                                                                                                                                                     
  run Rails.application                                                                                                                                         
  Rails.application.load_server                                                                                                                                 
end
```
and removed `scope "a/"` from `config/routes.rb` and it works.


After I tried the same change in the example application of this engine https://gitlab.com/pasosdeJesus/msip   whose default mount point is `/msip`

To make work the assets in develpoment mode I had to create a link from `public/msip/assets`  to `public/assets` and it worked partially.

I say partially because in some situations the route helpers of the engine generate wrong paths, for example the main menu (test/dummy/app/views/layout/application.html.erb)  has `msip.orgsociales_path`  and in the home page it becomes `/msip/orgsociales` but from the index view of `Msip::OrgsocialesController`  it becomes `/orgsociales`.

**Comment by bensheldon** [comment]
Sorry to have missed a follow-up on #9688 😞 

> Could you please tell me how to change in the test case the "test harness's Rack mount point for the Rails Rack App to account for the config.relative_url_root"

I don't know for sure 😓 The metho used for simulating it in the tests was setting a `SCRIPT_NAME=` parameter with the relative root:

https://github.com/rails/rails/blob/4c0eceae06fefe41c7e6bbf5c37e61c24eb6bf74/railties/test/railties/engine_test.rb#L1680

Or in other words:

```ruby
get("/posts/1", {}, { "SCRIPT_NAME" => "/foo" })

# is equivalent to the absolute path /foo/posts/1 
# when using this rack configuration:

map "/foo" do                                                                                                                                                     
  run Rails.application 
end
```

(though that should work regardless of `config.relative_url_root`)

---

I think I'm still a little unclear specifically on why you're using `config.relative_url_root`. That's only necessary if you're hosting the Rails application at a different path than the `/`. In your examples, it seems like you're still hosting the Rails application at `/` and then adding additional routes. 

> I say partially because in some situations the route helpers of the engine generate wrong paths, for example the main menu (test/dummy/app/views/layout/application.html.erb) has msip.orgsociales_path and in the home page it becomes /msip/orgsociales but from the index view of Msip::OrgsocialesController it becomes /orgsociales.

Can you show me the example of that? I didn't see an `index.html` template for that.

**Comment by vtamara** [comment]
Thank you @bensheldon

> Or in other words:
> 
> ```ruby
> get("/posts/1", {}, { "SCRIPT_NAME" => "/foo" })
> 

When I try this, I get the error:
```
ArgumentError: wrong number of arguments (given 3, expected 1)
```
If I try with:
```ruby
get("/posts/1", params: {}, headers: { "SCRIPT_NAME" => "/foo" })
```
It doesn´t present error but it doesn´t work.

Any hint?

> Can you show me the example of that? I didn't see an `index.html` template for that.

I could solve (instead of assigning `config.relative_url_root` in a file at `config/initializers/`  it should be assigned in `config/application.rb`).

Thank you.

**Comment by vtamara** [comment]
This was not fixed

**Comment by zzak** [comment]
I'm not sure which issue we should keep open, sorry :sleepy:

**Comment by zzak** [comment]
@vtamara So I've tried both your repro script here, and cloned your app in #49688, and both cases are failing with Rails < 7.1

```
# 49688
# Rails 7.0.8

$ bin/test rails test/controllers/routes_test.rb

E

Error:
RoutesTest#test_users_path:
ActionController::RoutingError: No route matches [GET] "/a/a/users"
    test/controllers/routes_test.rb:5:in `block in <class:RoutesTest>'


rails test test/controllers/routes_test.rb:3

F

Failure:
RoutesTest#test_articles_path [/home/zzak/code/bugs/49688/app49688/test/controllers/routes_test.rb:10]:
Expected: "/a/a/articles"
  Actual: "/a/articles"

rails test test/controllers/routes_test.rb:9
```

```
# 50461
# Rails 6.1.7

/a/a
I, [2024-05-30T08:00:34.303164 #123641]  INFO -- : Started GET "/a/a" for 127.0.0.1 at 2024-05-30 08:00:34 +0900
F, [2024-05-30T08:00:34.303479 #123641] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/a/a"):

F

Failure:
BugTest#test_root_path_different_to_workingroute_root_in_6_7_and_7_1 [bug.rb:54]:
Expected false to be truthy.

rails test bug.rb:51

I, [2024-05-30T08:00:34.304866 #123641]  INFO -- : Started GET "/a" for 127.0.0.1 at 2024-05-30 08:00:34 +0900
.
```

This test fails on 7.0, 7.1, and main.

If you could provide a reproducible test case which demonstrates a pass/fail between versions, it would be greatly appreciated.

I was trying to validate my patch in #51933 against your bug, but was inconclusive. Could try my branch in your app to verify?

**Comment by vtamara** [comment]
@zzak  It seems the problem was solved.

Now with rails 7.1.2 in tests I can use routes helpers and they will start with what is configured in `Rails.configuration.relative_url_root`

Thank you
