### ISSUE TITLE
.create method on record is creating the attribute that is defined as enum in my model

### ISSUE THREAD

**Issue by raoehtesham03** [rails/rails#50469]
### Expected behavior
In Rails 6.0:
   Upon executing `Model.new(params)`, it initializes an object with all the columns.

### Actual behavior
In Rails 6.1:
   When I do `Model.new(params).create`, it initializes the object with only the column attributes of this table and also the attribute defined as an enum.

```ruby
class MyModel < ActiveRecord::Base
  enum object_types: { floor: 0, room: 1 }
end

MyModel.new.save 
```
The created object will also have object_types.

Why it is happening ?

### System configuration
**Rails version**: 6.1.7.6

**Ruby version**: 2.7.8

**Comment by fatkodima** [comment]
Hey @raoehtesham03 we reserve the Rails Issues tracker for bugs in the framework as we don't have the bandwidth to offer application support. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help with your application. Also note, that rails < 7 is not supported for bug fixes.
