### ISSUE TITLE
Rails 7.1.0 has the inconsistency behavior for ActiveSupport::JSON.encode when encoding the Hash with symbols and strings of the same word as keys.

### ISSUE THREAD

**Issue by takkanm** [rails/rails#50481]
### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", ENV['RAILS_VERSION']
end

require "active_support"

pp ActiveSupport::JSON.encode({ 'a' => 1, :a => 2 })
```

### Expected behavior

The result is `"{\"a\":2}"` when running the sample code with `RAILS_VERSION=7.0.8`.

### Actual behavior

The result is `"{\"a\":1,\"a\":2}"` when running the sample code with `RAILS_VERSION=7.1.0`.
This behavior is also the same with the current HEAD.

### Remarks

This inconsistency is introduced by ab01f9f3da837395550c0b20d3349aad9d314e38 contained in #48614, and this change is not recorded in the CHANGELOG.
However, the current behavior is consistent with the results of `JSON.dump` in Ruby itself.

```ruby
require 'json'
pp JSON.dump({ 'a' => 1, :a => 2 }) # => "{\"a\":1,\"a\":2}"
```

Therefore, I would like to know if this behavior should be corrected as an inconsistency or remain as a specification. If this is the current specification, I would be happy to see it described in the test.

### System configuration
**Rails version**: 7.1.0 

**Ruby version**: 3.3.0

**Comment by maniSHarma7575** [comment]
@takkanm for nested hash. It appears that the behavior is the same as `RAILS_VERSION=7.0.8`. However, for the same key at the parent level, both keys are present in the output. This inconsistency should be addressed.

```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "rails", ENV['RAILS_VERSION']
end

require "active_support"

pp ActiveSupport::JSON.encode({ 'a' => 1, :a => 2, c: { 'b': 3, :b => 4 } })
```

Output: `"{\"a\":1,\"a\":2,\"c\":{\"b\":4}}"`
