### ISSUE TITLE
Warning on serialize from ActiveStorage

### ISSUE THREAD

**Issue by dorianmarie** [rails/rails#50483]
```
DEPRECATION WARNING: Passing the class as positional argument is deprecated and will be removed in Rails 7.2.

Please pass the class as a keyword argument:

  serialize :metadata, type: Object
```

Comes from:

```
has_one_attached :csv_file
```

ruby 3.2.2 (2023-03-30 revision e51014f9c0) +YJIT [arm64-darwin22]

Rails 7.1.2

------

It seems like the issue is coming from rails, this happened after the upgrade to rails 7.1

**Comment by fatkodima** [comment]
Can't reproduce. Can you create a reproduction script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_storage.rb ?

**Comment by bparanj** [comment]
Here is the test case:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f

  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_one_attached :profile
  serialize :metadata, type: Object
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_upload_and_download
    user = User.create!(
      profile: {
        content_type: "text/plain",
        filename: "dummy.txt",
        io: ::StringIO.new("dummy"),
      }
    )

    assert_equal "dummy", user.profile.download
  end
end
```

Cannot reproduce this error. It fails for a different reason:

```
/Users/bparanj/.rvm/gems/ruby-3.2.2@contrib/gems/activerecord-7.1.2/lib/active_record/attribute_methods/serialization.rb:208:in `serialize': missing keyword: :coder If no default coder is configured, a coder must be provided to `serialize`. (ArgumentError)

            raise ArgumentError, <<~MSG.squish
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from 50483.rb:56:in `<class:User>'
	from 50483.rb:54:in `<main>'
$ rails -v
Rails 7.1.2
```

**Comment by dorianmarie** [comment]
Maybe it's because I have a text field for metadata on the `active_storage_blobs` table:

```
  create_table "active_storage_blobs", force: :cascade do |t|
    t.string "key", null: false
    t.string "filename", null: false
    t.string "content_type"
    t.text "metadata"
    t.bigint "byte_size", null: false
    t.string "checksum"
    t.datetime "created_at", precision: nil, null: false
    t.string "service_name", null: false
    t.index ["key"], name: "index_active_storage_blobs_on_key", unique: true
  end
```

**Comment by fatkodima** [comment]
Please, provide us a reproduction script or app.

**Comment by bparanj** [comment]
The test case I provided is already using that field: https://github.com/rails/rails/blob/main/activestorage/db/migrate/20170806125915_create_active_storage_tables.rb

You can see it. For reporting issues, please follow these guidelines: https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#reporting-an-issue

If you need help with debugging your application you can post it here: https://discuss.rubyonrails.org/

**Comment by 1v** [comment]
Same warning from has_one_attached after upgrade. Rails 7.1.1 (was 7.0.3)

**Comment by zzak** [comment]
@bparanj Thanks for your investigation!

After looking at the script [above](https://github.com/rails/rails/issues/50483#issuecomment-1872553844), I think that the code is failing due to the changes in #47463

```
serialize :metadata, type: Object
```

The default coder is nil, and you have not specified one, therefore raising this exception:
https://github.com/rails/rails/blob/e0a55b038f7f2f50d1467876558be183be6cedaa/activerecord/lib/active_record/attribute_methods/serialization.rb#L206-L213

This is expected behavior.

If anyone is able to reproduce this, please provide more information :bow:

**Comment by 1v** [comment]
There is no `serialize :metadata, type: Object` in my code, warning comes just from `has_one_attached`. 

Also I have `serialize` in other models like `serialize :options` and it outputs warning:
```
DEPRECATION WARNING: Passing the coder as positional argument is deprecated and will be removed in Rails 7.2.

Please pass the coder as a keyword argument:

  serialize :options, coder: JSON
 (called from <class:Foo> at app/models/foo.rb:22)
```
But no matter what combination of arguments I pass into serialize - warning won't disappear.

**Comment by zzak** [comment]
I've just tried with a fresh 7.0 app, adding a scaffold and active storage, then upgrade to 7.1 and could not reproduce. I thought maybe it was an initializer or some configuration, maybe.

Could you check your config and check any uses of `serialize` or `store`?

If you are able to reproduce it, could you try to get a full stack trace?

Setting `config.active_support.deprecation = :raise` in your config may also help getting a stacktrace. [[ref](https://edgeapi.rubyonrails.org/classes/ActiveSupport/Deprecation/Behavior.html#method-i-behavior-3D)]

**Comment by 1v** [comment]
I have ` config.active_record.default_column_serializer = JSON` without it I get:
```
     ArgumentError:
       missing keyword: :coder If no default coder is configured, a coder must be provided to `serialize`.
```
on every serialize. Disabling it and adding coder manually I get same warning.

I tried to create new rails app and I don't get any warning with it. Then I tried to add my gems and turns out it comes from gem `globalize` and there is pull request to fix it https://github.com/globalize/globalize/pull/811

**Comment by zzak** [comment]
Thanks for following up!

@dorianmarie Can you confirm you're also using globalize? Or if not can you get us a full backtrace of the warning?

**Comment by dorianmarie** [comment]
@zzak Yes I'm using globalize as well

**Comment by dorianmarie** [comment]
So I guess we can close this and wait for a new globalize release

**Comment by kimesf** [comment]
FYI, Globalize is being updated to support Rails 7.2 and above.

https://github.com/globalize/globalize/blob/39ec169ea03e160f80c2bcc8dfd2b9d0ea752b25/test/data/models/serialized_attr.rb#L18
