### ISSUE TITLE
Ruby Versions are in multiple locations, making it difficult to upgrade

### ISSUE THREAD

**Issue by bparanj** [rails/rails#50504]
### Steps to reproduce

Rails is amazing. It is now cloud native and I am able to work with it on gitpod, codespaces and EC2. Currently there are 3 places where I need to update Ruby version to upgrade Ruby. 

Dockerfile:

```
ARG RUBY_VERSION=3.3.0
```

Gemfile:

```ruby
ruby "3.3.0"
```

and .ruby-version file:

```
ruby-3.3.0
```

### Expected behavior

There should be only one location where we need specify the Ruby version. 

### Actual behavior

I have to change Ruby versions in all those three files to update Ruby to latest version.

### System configuration

**Rails version**: 7.1.2

**Ruby version**: 3.3.0

This will provide a great experience for beginners.

**Comment by zzak** [comment]
This is a limitation of the tools available, I'm not sure this is a bug in other words.

Please open a PR if you have any suggestions to improve this experience. :bow:

**Comment by skipkayhil** [comment]
I do plan to wrap up #49360, it's almost ready to go on my local
