### ISSUE TITLE
Add Brakeman by default to new apps

### ISSUE THREAD

**Issue by dhh** [rails/rails#50501]
[Brakeman](https://brakemanscanner.org) is a great way to prevent common security vulnerabilities in Rails from going into production. We should be encouraging that for new applications. Especially for newcomers to the framework who might otherwise make rookie mistakes. So let's add it in the same way we just added Rubocop. `--skip-brakeman` if you don't want it, otherwise we add to default gemfile and create a default binstub in bin/brakeman.

**Comment by claudiug** [comment]
@dhh unrelated, had you also think to add a gem similar to: https://github.com/robbyrussell/indexter. a tool too warm of missing indexes that might be missing?

**Comment by vipulnsward** [comment]
Opened https://github.com/rails/rails/pull/50507 for feedback
