### ISSUE TITLE
Add basic JS Linter by default

### ISSUE THREAD

**Issue by faqndo97** [rails/rails#50529]
Now that the project is moving towards more default configurations, including a basic Rubocop setup by default, I believe it's also beneficial to add a default JavaScript linter. There are many options in this area, such as [ESLint](https://eslint.org/), [Quick Lint](https://quick-lint-js.com/), and others. Regarding the configuration, I don't have a specific one in mind, but I think it's worthwhile to have something in place. One well-known option is [Standard](https://standardjs.com/). Although we decided against the standard style in Ruby, it could be a viable option for JavaScript. I'm open to assisting with the implementation, but I'd like to discuss it first and decide on the configuration and linter. @dhh I know you have been pushing about these default, I don't know if 37signals it's already using something that can be the based for this work.

**Comment by dhh** [comment]
Rails doesn't ship with a dependency on npm by default, so this is work that would have to be explored in jsbundling-rails. Not necessarily against it, but don't want to make things hugely complicated for it.
