### ISSUE TITLE
Action View `test:ujs` failures in CI

### ISSUE THREAD

**Issue by skipkayhil** [rails/rails#50524]
Tracking issue to fix `test:ujs` in Buildkite

First failure was on Ruby 3.2
https://buildkite.com/rails/rails/builds/103069

Once Ruby 3.3 was added to Buildkite, it has been failing on 3.3:
https://buildkite.com/rails/rails/builds/103106

I haven't yet been able to reproduce locally

**Comment by skipkayhil** [comment]
https://buildkite.com/rails/rails/builds/103183#018cc6f0-e6a9-4e04-a7e6-dc67019298fe

Got an actual error message:

```
rake aborted!
Errno::ENOENT: No such file or directory - npm (Errno::ENOENT)
/rails/actionview/Rakefile:36:in `system'
/rails/actionview/Rakefile:36:in `block (2 levels) in <top (required)>'
Tasks: TOP => test:ujs
(See full trace by running task with --trace)
```

So the issue is the `npm` command is not found for some reason 🤔

**Comment by zzak** [comment]
This has happened before: #48525

**Comment by skipkayhil** [comment]
I built the image locally and it appears the issue is the same as the previously mentioned one:

```
root@19c01f3415ae:/rails/actionview# apt list -a nodejs
Listing... Done
nodejs/stable-security,now 18.19.0+dfsg-6~deb12u1 amd64 [installed]
nodejs/unknown 18.17.1-deb-1nodesource1 amd64
nodejs/stable 18.13.0+dfsg1-1 amd64
```

You can see that the highest version (18.19.0) is coming from debian instead of nodesource

**Comment by zzak** [comment]
Seems explained in nodesource/distributions#1601
