### ISSUE TITLE
Request to add back DB2 support in rails framework.

### ISSUE THREAD

**Issue by praveen-db2** [rails/rails#50537]
Hi,

I am from ibm_db adapter development team. I see from this commit https://github.com/rails/rails/commit/f960948d233a4713922997d80ca7c6ddec9c8a49 on-wards  db2 support is been removed from rails framework. Not sure why this is been done.

This is creating lot of problems for our customers who use DB2.

Can this commit be reverted back and add DB2 support back in framework ?
I really appreciate your help.

Thanks
Praveen

**Comment by eileencodes** [comment]
Hi @praveen-db2 the PR that removed the adapter explained that it was unmaintained at the time. However, there's nothing about that change that doesn't allow the ibm_db adapter to be used. There are many database adapters not baked directly into Rails. Without knowing what problems you're facing, we can't advise how to fix the issue, but it is likely the ibm_db adapter is missing something important or your customers are using Rails versions that your adapter doesn't support.

**Comment by praveen-db2** [comment]
Hi @eileencodes thanks for your immediate reply.
Please look at this ticket https://github.com/ibmdb/ruby-ibmdb/issues/164, it will help you understand problem.

**Comment by dhh** [comment]
You can just do "rails new my-app" then manually switch to your DB2 adapter afterwards. Or you can use a Rails template to do this. But out of the box, Rails is committed to only maintaining three default options: sqlite, PostgreSQL, mysql. Every other database can continue to integrate using the adapter setup as always 👍

**Comment by praveen-db2** [comment]
@dhh you said "Or you can use a Rails template to do this." Can I know how it can be done.

**Comment by dhh** [comment]
https://guides.rubyonrails.org/rails_application_templates.html

**Comment by scotdb** [comment]
The comment that only two databases are supported isn't strictly true.   The main problem that we as Db2 users face is the lack of support for Db2 in the following two places in the railties gem -

railties-7.1.2/lib/rails/generators/rails/app/templates/config/databases
railties-7.1.2/lib/rails/generators/database.rb

If you look at those you'll find the list is much longer than the three mentioned -

     JDBC_DATABASES = %w( jdbcmysql jdbcsqlite3 jdbcpostgresql jdbc )
      DATABASES = %w( mysql trilogy postgresql sqlite3 oracle sqlserver ) + JDBC_DATABASES

Similar list from the set of template YAML files.

It is all very well to say "you can just add those manually", as I had to do in the past. 

But to remove the ibm_db driver as "unsupported", leaving behind a bunch of other proprietary drivers, is hardly equitable.  The Rails driver from IBM is being supported actively by IBM (Praveeen above being one of the developers).

So what I, as a Db2 user, would like to see is the Db2 links put back into these two locations as they once were.

Phil Nelson

**Comment by skipkayhil** [comment]
> But to remove the ibm_db driver as "unsupported", leaving behind a bunch of other proprietary drivers, is hardly equitable. The Rails driver from IBM is being supported actively by IBM

It looks like there has been a lot of development in the past year, but at the time the PR was merged (2020) the most recent release of `ibm_db` was `4.0.0` and it did not support Rails 5.2 which was released in 2018.

**Comment by dhh** [comment]
Yeah, I do actually think we should eject the rest of the proprietary DBs on that list as well. Along with the JDBC versions. Rails will maintain for the 3 open source DBs we support, and then everything else can bring its own adapter by hand or rails application template.

**Comment by zzak** [comment]
For reference, there is an adapter for [oracle](https://github.com/rsim/oracle-enhanced) which is pretty well maintained.
