### ISSUE TITLE
find_by returns record for nil input

### ISSUE THREAD

**Issue by bparanj** [rails/rails#50559]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails', github: 'rails/rails'
  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new($stdout)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_find_by_nil
    post = Post.create!(title: 'Test Post')
    result = Post.find_by(nil)

    assert_equal post.title, result.title
    assert result.class == Post
    assert_nil result
  end
end

```

### Expected behavior

It should return nil as documented in the API documentation.

### Actual behavior

It generates the wrong SQL for `find_by(nil)` query:

```
TRANSACTION (0.0ms)  begin transaction
Post Create (0.5ms)  INSERT INTO "posts" ("title") VALUES (?) RETURNING "id"  [["title", "Test Post"]]
TRANSACTION (0.0ms)  commit transaction
Post Load (0.1ms)  SELECT "posts".* FROM "posts" LIMIT ?  [["LIMIT", 1]]
```

### System configuration
**Rails version**: Rails 7.1.2

**Ruby version**: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]

**Comment by rafaelfranca** [comment]
This is expected behavior. Documentation say "If no record is found, returns nil" but records are found when you don't pass any conditions. This is the same as `where(nil)`

**Comment by fatkodima** [comment]
> It should return nil as documented in the API documentation.

The behaviour looks weird, but accordingly to the documentation
> Finds the first record matching the specified conditions

Returns just "first" record, with no conditions applied. 

Let's see what other people think about it.
