### ISSUE TITLE
Incorrect notification order in ActiveRecord transactions

### ISSUE THREAD

**Issue by zvkemp** [rails/rails#50562]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'rails'
  # If you want to test against edge Rails replace the previous line with this:
  #
  # first bad commit:
  # gem 'rails', github: 'rails/rails', ref: '542f0951dddac49bf06f7da35d990db4f3829307'

  # The parent commit of the above ref will pass this test:
  # gem 'rails', github: 'rails/rails', ref: 'bb68040de45754b27f5064c5635f6d0944cfc727'

  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

class Subscriber
  attr_reader :events

  def initialize
    @events = []
  end

  def start(_name, _id, payload)
    return if payload[:name] == 'SCHEMA'

    # substitution here to strip out the new default return on the main branch
    events << [:start, payload[:sql].sub(/ RETURNING "id"/, '')]
  end

  def finish(_name, _id, payload)
    return if payload[:name] == 'SCHEMA'

    events << [:finish, payload[:sql].sub(/ RETURNING "id"/, '')]
  end

  def publish(*); end

  def publish_event(*); end
end

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    subscriber = Subscriber.new
    ActiveSupport::Notifications.subscribe('sql.active_record', subscriber)

    post = Post.create!

    post.destroy

    create_events = subscriber.events.slice!(0, 6)
    destroy_events = subscriber.events

    expected_create_order = [
      [:start, 'begin transaction'],
      [:finish, 'begin transaction'],
      [:start, 'INSERT INTO "posts" DEFAULT VALUES'],
      [:finish, 'INSERT INTO "posts" DEFAULT VALUES'],
      [:start, 'commit transaction'],
      [:finish, 'commit transaction']
    ]

    expected_destroy_order = [
      [:start, 'begin transaction'],
      [:finish, 'begin transaction'],
      [:start, 'DELETE FROM "posts" WHERE "posts"."id" = ?'],
      [:finish, 'DELETE FROM "posts" WHERE "posts"."id" = ?'],
      [:start, 'commit transaction'],
      [:finish, 'commit transaction']
    ]

    assert_equal(create_events, expected_create_order)
    assert_equal(destroy_events, expected_destroy_order)
  end
end

```

### Expected behavior
The evented notifications should appear in the order of the database executions, i.e.:

- begin transaction
- execute statement
- commit transaction

### Actual behavior

The statement execution is wrapped around `begin`, with `commit` trailing after both:

- execute statement
  - begin transaction
- commit transaction

Or, to put it in terms of start/finish:

- start execute statement
- start begin
- finish begin
- finish execute statement
- start commit
- finish commit

This behavior changed in https://github.com/rails/rails/pull/44576. For loggers or other subscribers that receive a single notification per event, this probably did not change anything, as the 'finishes' are still in the correct order. However, for subscribers that process `start` and `finish` events individually (e.g., tracers), this ordering implies that "execute statement" is a parent event of "begin" — which is not correct in terms of how this was previously understood.

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.3.0

**Comment by bparanj** [comment]
I have tested this test case.

 This fails:

```ruby
gem 'rails', '7.1.0.beta1'
```

This works:

```
gem 'rails', '7.0.8'
```

So this bug was introduced in version `7.1.0.beta1`.

**Comment by zvkemp** [comment]
Yes, more specifically in this commit: https://github.com/rails/rails/pull/44576/commits/542f0951dddac49bf06f7da35d990db4f3829307

**Comment by zvkemp** [comment]
This has to do with the new ordering of `materialize_transactions`, which is now called within the `with_raw_connection` method. I have a potential fix in mind, but I'd like @matthewd to weigh in before I spend too much time on the implementation.

The gist is that the log messages for `transaction begin` are triggered by `materialize_transactions`, which is in turn triggered by `with_raw_connection`, which is now called _inside_ the log block for `internal_exec_query` (at least in the case of the sqlite3 adapter). Inverting the nesting of these blocks will trigger the messages in the expected order:

```ruby
        def internal_exec_query(sql, name = nil, binds = [], prepare: false, async: false) # :nodoc:
          # ...
          with_raw_connection do |conn|
            log(sql, name, binds, type_casted_binds, async: async) do
              # ...
```

However, the `log { with_raw_connection {` pattern occurs frequently, but I'm not sure this ordering is ever intentional or important. The previous design materialized transactions before `log` was called, and called `ActiveSupport::Dependencies.interlock.permit_concurrent_loads` inside the log block (same position as `with_raw_connection` is now. So the question is whether `with_raw_connection` should be instrumented itself (maybe with a new notification?), or if its ok for just the internal yield to be instrumented.

**Comment by zvkemp** [comment]
The issue persists. I will re-submit as a PR.
