### ISSUE TITLE
Generate devcontainer files by default

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails#50566]
Make easier for users to setup their development environments for Rails applications.

https://containers.dev/

Note: This ticket serves as a placeholder for the intention to do this work. Not as an open invitation to feature requests. Before we engage in broad discussion of what should or shouldn't be in such a generator, the core team will propose a solution first, so there's something tangible to discuss.

**Comment by excid3** [comment]
Can't wait for this @rafaelfranca!

**Comment by ksylvest** [comment]
Does this require a separate `Dockerfile` (e.g. `Dockerfile.local`) / can it be paired with compose.yml to provide DB / Redis for local also?

**Comment by seanpk** [comment]
I have been experimenting with using devcontainers for about 3 months and quite like them. I have a docker compose file that also starts a container with the DB (which is the default setup from doing it through VS Code). When I needed Redis, I just shortcutted and added it to may main container using `apt`.

Having a good setup by default will be much better - what I've done works, but I'm sure some of my other "make it work for this project" work is suboptimal.

**Comment by rafaelfranca** [comment]
Still defining it. It will go further than a generator but I didn't decide how much yet. I'm working on the feature, when it is ready I'm sure it will have plenty of opportunities to contribute.

**Comment by Gary-H9** [comment]
Awesome looking forward to contributing! 😄

**Comment by viktorianer** [comment]
I've been [closely following the discussion](https://discuss.rubyonrails.org/t/add-devcontainer-flag-to-rails-new-command/84507/6?u=viktorianer) on adding a `devcontainer` flag to `rails new` command. The idea is promising, but there are complexities in the setup, as illustrated by examples like [Ruby on Whales](https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development). My own setup, which includes a `makefile`, aims to streamline container management and environment configurations.

### Challenges with Current Devcontainer

The existing [devcontainer in the Rails repository](https://github.com/rails/rails/tree/main/.devcontainer) presents several issues. For instance, executing `devcontainer exec --workspace-folder . bash` leads to git permission errors and lacks the comfort of advanced host machine features like autocomplete, history sub search, and custom aliases.

Moreover, using `makefile` for container startup with correct host user ID (via `.env.local`) helps avoid some of these issues. This approach could be a part of the solution.

### Docker Compose Complications

Docker Compose adds another layer of complexity. For example, a Docker upgrade disrupted my previously working setup using `tmpfs` to enhance Rails performance inside Docker. This required an adjustment to the `tmpfs` settings in the `docker-compose.yml` to maintain non-root user operations.

Given these challenges, I believe there's room for improvement in the default devcontainer setup for Rails. I'm eager to contribute and collaborate on finding the best minimal/default setup, especially with insights from experienced Rails developers like @rafaelfranca.

**Comment by rafaelfranca** [comment]
> The existing [devcontainer in the Rails repository](https://github.com/rails/rails/tree/main/.devcontainer) presents several issues. For instance, executing `devcontainer exec --workspace-folder . bash` leads to [git permission errors](https://github.com/actions/runner/issues/2033#issuecomment-1238771855) and lacks the comfort of [advanced host machine features](https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins) like [autocomplete](https://github.com/marlonrichert/zsh-autocomplete), [history sub search](https://github.com/zsh-users/zsh-history-substring-search), and custom aliases.

I'm being using this container for 4 years and I never had any of those problem. About comfort of advanced host machine features, the devcontainer solution for this is making your dotfiles repository and [using it to setup the devcontainer](https://github.com/devcontainers/cli/pull/362). I have all my custom aliases inside the dev container.

It does require people changing some mindsets, indeed, but I don't think I'll complicate the implementation to adopt it to different workflows. We will only include a blessed path, if you want to deviate from it, you will need to deal with the problems yourself.

The docker compose issue is interesting. I also never had any problem with this, but i also don't mess with tmpfs on the docker compose config.  I guess most users will not have.

That said, I'm fine with us trying to avoid common mistakes, but I have no goal to make this work for every single workflow.

The devcontainer will be highly optimized for VSCode as well, so while people can have a similar experience with the CLI, who uses VSCode will have a better experience.

**Comment by brunoprietog** [comment]
Could we also generate the `.vscode` folder with the recommended extensions file? Including ruby-lsp, and commands to start the Rails server. Although this would not be specifically for containers as such.

**Comment by viktorianer** [comment]
> Could we also generate the `.vscode` folder with the recommended extensions file? Including ruby-lsp, and commands to start the Rails server. Although this would not be specifically for containers as such.

That's also one of the problems. Devcontainer started in VSCode dose not use installed staff. So, adding `.code` will not help. Instead, devcontainers including own list of extensions to install.

Personally, I do not like both ways. That's why I am using devcontainers CLI. This way, I can install extensions as I wont and run in the containers only stuff needed for development gems, like LSP server.

Would prefer this way in default ✌🏼

@rafaelfranca 
I could add a draft PR tomorrow, of it is ok for you?
I figured today out, how this devcontainers works and have already a base setup. 

With this draft, we can discuss how much we should add to the minimum setup?

**Comment by rafaelfranca** [comment]
No. I don't want any implementation right now. I'm implementing it. Thank you for offering.

**Comment by rafaelfranca** [comment]
> Could we also generate the .vscode folder with the recommended extensions file? Including ruby-lsp, and commands to start the Rails server. Although this would not be specifically for containers as such.

Yes. That is one of the plans. Global extensions that are user specific you can install using `dev.containers.defaultExtensions`. But for Rails specific extensions that the core team thinks are useful, they will be included in the devcontainer config, along with commands.

> That's also one of the problems. Devcontainer started in VSCode dose not use installed staff.

To solve this VSCode has a config. `dev.containers.defaultExtensions`. My config is this for example:

```
"dev.containers.defaultExtensions": [
  "github.copilot",
  "eamodio.gitlens",
  "github.vscode-pull-request-github",
  "streetsidesoftware.code-spell-checker",
  "ms-vsliveshare.vsliveshare-pack"
]
```

**Comment by Gary-H9** [comment]
### Dotfiles

With respect to including `dotfiles` functionality, I think it's a very valuable feature and in my experience reduces friction when trying to get users to adopt using a dev container. I have noted how I include them in dev containers in my [dotfiles](https://github.com/Gary-H9/dotfiles) repository.

### Spinning up a Database using the Dev Container

I think the possibility of using [Docker in Docker](https://github.com/devcontainers/features/tree/main/src/docker-in-docker) to spin up a database inside the dev container is something that should be considered. 

This would have all of the benefits of using a dev container but for the database as well - Consistency, Isolation, Ease of Setup and Flexibility.

> We will only include a blessed path, if you want to deviate from it, you will need to deal with the problems yourself.

However, I do agree with @rafaelfranca on this and I'm not sure if Docker in Docker to spin up a database is overcomplicating things. 🙇 

That being said, if we do think dev container database's are a good idea, perhaps there could be options for the `--devcontainer` flag*? e.g. `--devcontainer=mysql`, `--devcontainer=postgresql`. With the default flag just creating configurations not including any database functionality.

(*presuming it's that flag.)

**Comment by viktorianer** [comment]
One more annoying thing, which I solved in my docker environment, is the installation of Ruby, Bundler and Node/Yarn version correct. 

Here is an output, where you can see the problem with Ruby and Bundler:

```bash
...
=> ERROR [web dev_container_auto_added_stage_label 7/8] RUN cd /tmp/rails     && bundle install     && yarn install     && yarn cache clean     && rm -rf /tmp/rails 
------
 > [web dev_container_auto_added_stage_label 7/8] RUN cd /tmp/rails     && bundle install     && yarn install     && yarn cache clean     && rm -rf /tmp/rails:
0.231 Bundler 2.4.10 is running, but your lockfile was generated with 2.4.21. Installing Bundler 2.4.21 and restarting using that version.
3.848 Fetching gem metadata from https://rubygems.org/.
3.895 Fetching bundler 2.4.21
4.101 Installing bundler 2.4.21
4.257 Your Ruby version is 3.2.2, but your Gemfile specified 3.3.0
```

There is no `3.3` variant of image right now https://github.com/devcontainers/images/blob/main/src/ruby/.devcontainer/Dockerfile, see https://github.com/devcontainers/images/pull/905.

Bundler can handle (to some degree?), the version and fallback with `restarting using that version`. I am not sure, but this was not always this way?

In case of Node, using just `ARG NODE_VERSION="lts/*"` will not work for most Rails apps. 

```bash
47.39 yarn install v1.22.19
47.42 [1/5] Validating package.json...
47.42 error community_app@1.1.0: The engine "node" is incompatible with this module. Expected version "~18.x". Got "20.11.0"
47.42 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
47.42 error Found incompatible module.
```

**Comment by j-manu** [comment]
> I think the possibility of using [Docker in Docker](https://github.com/devcontainers/features/tree/main/src/docker-in-docker) to spin up a database inside the dev container is something that should be considered.

Dev containers support docker compose. You don't need docker in docker.

**Comment by Gary-H9** [comment]
@j-manu - That's true, Dev containers also [support](https://github.com/microsoft/vscode-dev-containers/blob/main/containers/docker-in-docker/README.md) Docker in Docker. It was the first thing that came to mind as I had done it recently and found it quite elegant - I liked that if I killed the devcontainer it also killed the database and so on. 

I think the key difference would probably be around persistent volumes. I'll think about it more if it's deemed to be something that's desired. 

I'm agnostic as to which approach is taken, my larger point is really that I think it's worth considering spinning up a database as well (or providing the option to).

**Comment by viktorianer** [comment]
> I'm agnostic as to which approach is taken, my larger point is really that I think it's worth considering spinning up a database as well (or providing the option to).

For sure, database should be included, see the issue description, it says:

> development environments for Rails applications

But, Docker in Docker is not needed for this. Also, you can stop and take down the devcontainer environments easy, along with all databases and what else you include in it. After https://github.com/devcontainers/cli/issues/386 is done for CLI, it will be as easy as docker compose itself. In VS Code, it is [already build in](https://code.visualstudio.com/docs/devcontainers/containers#_managing-containers).

To summarize, using `dockerComposeFile` is the [way to go here](https://containers.dev/implementors/json_reference/#compose-specific).

I continue to explore the drawbacks of the devcontainers for Rails apps :P. Not sure, if I like the idea to use ASDF and `.tool-versions` as default in Rails new apps?! It makes installation of correct version of Ruby, Node and Yarn (if required) so much easier in devcontainers. See https://github.com/devcontainers-contrib/features/tree/main/src/asdf-package.

Because, if we do not use ASDF, we need to define the versions in several places, repeating it several times. From the maintains and usage point of view, not so good.

@rafaelfranca 
What do you think about adding `.tool-versions` by default to new Rails 8 apps?

**Comment by robzolkos** [comment]
The Dockerfile that the devcontainer uses should specify the versions of node and ruby that are built in the environment.  imo adding `asdf` and other tools like this misses the point of having the devcontainer config being the single source of truth for versioning.  The dockerfile provides the versioning for the dependencies used to run the app itself, whilst docker-compose.yml ties together all the ancillary services the app requires to work in development (databases etc).

**Comment by viktorianer** [comment]
My point is, now you have to define Ruby in `Gemfile` (let's say `ruby "3.2.2"`) and in `.devcontainer` (let's say ARG VARIANT=3-bullseye). So, at least, you have here 2 places, I do not see single source of truth here. And I am not talking about dotfiles, which are also present in a new Rails project, see https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/app_generator.rb#L54.

So, on a new Rails app, you would have at least **3 sources** for Ruby version! For me, even 2 definitions, like before Rails 8 in `Gemfile` and `.ruby-version`, is at least not clear where source of truth is.

**Comment by viktorianer** [comment]
Curious about temporary removed Ruby version in Gemfile, see https://github.com/rails/rails/commit/75d5308f81ad5e45cd05ccf1132cc780481b9c04. 🥸

**Comment by rafaelfranca** [comment]
Read the commit message you will find the reason.

**Comment by viktorianer** [comment]
> Read the commit message you will find the reason.

I did, and understand it, because I was talking about it some comments above 🙂.

But I am curious about the coming solution for this. ✌🏼

**Comment by rafaelfranca** [comment]
We are considering actually never adding `ruby` to the Gemfile. Most tolling already support reading from `.ruby-version` and there is no much advantage of also having it on the Gemfile.

**Comment by akhilgkrishnan** [comment]
Closing this issue, as this feature is already added in https://github.com/rails/rails/issues/50566

**Comment by viktorianer** [comment]
@akhilgkrishnan 
You probably wanted to link https://github.com/rails/rails/pull/50914?

**Comment by akhilgkrishnan** [comment]
> @akhilgkrishnan You probably wanted to link #50914?

Oh yes, Thanks @viktorianer
