### ISSUE TITLE
/rails/active_storage/direct_uploads is open by default and potentially dangerous 

### ISSUE THREAD

**Issue by StanlyShauro** [rails/rails#50601]
When you generate new APP with Active Storage `/rails/active_storage/direct_uploads ` is available by default for all. Anybody may create blobs as many as they want.

In my opinion it is unexpected risk for new RoR programmers. 
Furthermore, there is no appropriate way to protect this route with authentication (at least I don't know one) 

### System configuration
**Rails version**:
7.1.2
**Ruby version**:
3.2.2

**Comment by rafaelfranca** [comment]
Yes. It is true that by default it is open to everyone, but you can protect this route with authentication.

See https://guides.rubyonrails.org/active_storage_overview.html#integrating-with-libraries-or-frameworks and https://discuss.rubyonrails.org/t/activestorage-direct-uploads-safe-by-default-how-to-make-it-safe/74863/7
