### ISSUE TITLE
Resolve `mutex_m` Dependency Warning in Minitest

### ISSUE THREAD

**Issue by bparanj** [rails/rails#50618]
### Issue
When using `minitest` with Ruby 3.3.0, the following warning is generated:

```
usr/local/lib/ruby/gems/3.3.0/gems/minitest-5.20.0/lib/minitest.rb:3: warning: mutex_m was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add mutex_m to your Gemfile or gemspec. Also contact author of minitest-5.20.0 to add mutex_m into its gemspec.
```

### Motivation

The changes ensure compatibility with Ruby 3.4.0 and beyond.

### Steps to reproduce
The following script using Ruby 3.3.0 DOES not reproduce the `mutex_m` warning:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  gem "minitest", "5.20.0"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff
    assert "zomg".present?
    refute "".present?
  end
end
```

This test passes. This warning only occurs on the [CI server](https://github.com/rails/rails/pull/50615).

**minitest version** (5.20.0)
**Ruby version**: 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]
**Rails version**:  Rails 7.1.2

- Do we need to explicitly add `mutex_m` to the Gemfile as a temporary fix?
- How to contact the author of minitest-5.20.0 to add mutex_m into its gemspec ?

**Comment by Earlopain** [comment]
There has been a commit to fix this on the minitest side a bit ago but no new relase since then yet. https://github.com/minitest/minitest/commit/5f5c2111f36658fd2636b108b8327ce4b2f3cf8d

**Comment by bparanj** [comment]
What is the temporary fix we can apply on the Rails side for now?

**Comment by Earlopain** [comment]
You should be able to add mutex_m to the Gemfile on the rails side for the time being. minitest is lacking a gemspec so you can't point it to the current master branch.

**Comment by byroot** [comment]
Nothing for Rails to fix here I'm afraid, just wait for a minitest release and in the meatime you can add `mutex_m` in your Gemfile as others mentioned.
