### ISSUE TITLE
uninitialized constant autoloading error explicitly path required why

### ISSUE THREAD

**Issue by AbdulWahab552** [rails/rails#50691]
i am using ruby 3.2.2 and rails version 7.0.1 in my code at one file i have to add explicitly the path of model class otherwise it didnt work i think on rails 7 my zeitwerk will handle the autoloading but it didnt working for me

**Comment by byroot** [comment]
Sorry but this report is way too obscure to be actionable.

Please try to include some code samples or something like that.
