### ISSUE TITLE
avoid broadcasts to channels with no subscribers

### ISSUE THREAD

**Issue by wdiechmann** [rails/rails#50694]
## Preambel

This issue is more like an idea / performance optimization

### Steps to reproduce

```
module RedisConcern
  extend ActiveSupport::Concern

  included do
    def channels_subscribed_to_include? channel
      Rails.env.development? ? 
        Redis.new.pubsub("channels").include? channel : 
        Redis.new.pubsub("channels").include? "%s:%s" % [ ENV["REDIS_NAMESPACE"], channel]
    end
  end 
end

class SomeResource < ApplicationRecord
  include RedisConcern
  after_create_commit :broadcast_create
  after_update_commit :broadcast_update

  def broadcast_create
    broadcast_prepend_later_to stream1, target: t1, partial: p1, locals: {} if channels_subscribed_to_include? stream1
    broadcast_prepend_later_to stream2, target: t2, partial: p2, locals: {} if channels_subscribed_to_include? stream2
    broadcast_prepend_later_to stream3, target: t3, partial: p3, locals: {} if channels_subscribed_to_include? stream3
    broadcast_prepend_later_to stream4, target: t4, partial: p4, locals: {} if channels_subscribed_to_include? stream4
  end

  def broadcast_update
    broadcast_replace_later_to stream1, target: t1, partial: p1, locals: {}
    broadcast_replace_later_to stream2, target: t2, partial: p2, locals: {}
    broadcast_replace_later_to stream3, target: t3, partial: p3, locals: {}
    broadcast_replace_later_to stream4, target: t4, partial: p4, locals: {}
  end
end
```

Do `some_resource.create`

Do `some_resource.update updated_at: DateTime.current`

### Expected behavior
The optimal situation would be not to see any queued broadcasts unless there are subscribers present.
Second best situation would be not to see any queued broadcasts unless there are subscribers.

### Actual behavior
All 4 streams are being queued - no matter what number of subscribers are present or even subscribed - but only in the update scenario.

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**Comment by byroot** [comment]
It is debatable whether it is an improvement as it incurs an extra roundtrip to the backend.

So depending on how costly it is to generate, it may be a win or a loss.

In general we don't take feature requests, so if you are interested in this I suggest attempting to implement it, and we can then debate its merits on the PR with actual code.

**Comment by wdiechmann** [comment]
‘extra roundtrip’ ?

the only ‘cost’ is an extra Redis - lookup - and only if there are subscribers, otherwise the ‘cost’ is offset by the lack of an insert of another background job into Redis

But no problem — I shaved 35 background jobs, each doing 1-4 SQL SELECTs eventually, off per each new punch (some time/attendance SaaS I’m building) and with projected 100’s of punches 6-8 times a day, this is serious compute I’m avoiding

I hear you - no feature requests! 

No problem

**Comment by wdiechmann** [comment]
“Roundtrip to the backend” in my vocabulary	implies going from the client to the server (and back) which obviously is not the case, hence my “repeating what you said"

What I guess you wanted to say: it’s debatable whether an extra Redis lookup is cheaper than inserting/performing a background job.

That is correct - provided that the background job will not do any work at all - in that case it’s in fact an extra Redis operation. If the background job is going to do any kind of work, then this ‘feature’ will save compute.

Your note on PR’s is noted

**Comment by byroot** [comment]
> What I guess you wanted to say: it’s debatable whether an extra Redis lookup is cheaper than inserting/performing a background job.

Yes, except Redis isn't the only possible Action Cable *backend*.

**Comment by wdiechmann** [comment]
I am aware of that — but CPU is CPU I guess 
🙂

I’m not able to provide a PR - my rails-fu is not remotely big enough to muster such a feat, hence the misplaced issue for which I apologize! It was by no means my intention to amass the much commotion -

Have a nice weekend
