### ISSUE TITLE
Upgrading 7.1.1 to 7.1.2 stores new (similarly named) session cookie and breaks CSRF (among other things)

### ISSUE THREAD

**Issue by namolnad** [rails/rails#50702]
Hi there, I imagine if this were happening for everyone it would have been quickly addressed, so I'm not sure how reproducible it will be, but these are the steps I took:
### Steps to reproduce
- Upgrade to 7.1.2 from 7.1.1
- Heard report of issue from user (turned out to be CSRF issue)
- Inspected my own cookies (my app uses the default cookie store for sessions)
- Noticed a new session cookie alongside my expected one (`_my_app_name_session` was expected and now I also had `["_my_app_name_session`
- Realized my app was unable to read the new session data, which was causing the issues being reported.
- Reverted upgrade

### Expected behavior
The session cookie would continue to be written and read as normal

### Actual behavior
For some reason a slightly garbled version of the session cookie seems to be getting written

### System configuration
**Rails version**:
7.1.2
**Ruby version**:
3.3.0

Thanks!

**Comment by skipkayhil** [comment]
Hey @namolnad, thanks for opening an issue! What web server are you using and does it support Rack 3? This issue usually appears because applications are using a web server that does not support Rack 3 but their Rack version was upgraded to 3 along with a Rails upgrade.

**Comment by namolnad** [comment]
> Hey @namolnad, thanks for opening an issue! What web server are you using and does it support Rack 3? This issue usually appears because applications are using a web server that does not support Rack 3 but their Rack version was upgraded to 3 along with a Rails upgrade.
> 
> For example, there's some discussion for a similar issue here: #49422

Thanks @skipkayhil, you were spot on. I was using puma, but was using an older version. After upgrading to latest, things are back to working perfectly. Appreciate the guidance! I'll close this one out.
