### ISSUE TITLE
Tests fail to load Prism properly in Ruby 3.3.0

### ISSUE THREAD

**Issue by gazayas** [rails/rails#50709]
Ruby 3.3.0 supports Prism out of the box, so Rails applications with dependencies that require Prism don't need to explicitly define the `prism` gem in their Gemfile/gemspec anymore. However, when updating to Ruby 3.3.0, `require "prism"` invoked this way won't work when running tests.

### Steps to reproduce
```
$ rails new prism_issue
$ cd prism_issue

# Generate a model to test against.
$ rails g model Foo bar:string
      invoke  active_record
      create    db/migrate/20240111132518_create_foos.rb
      create    app/models/foo.rb
      invoke    test_unit
      create      test/models/foo_test.rb
      create      test/fixtures/foos.yml
$ rails db:migrate
== 20240111132518 CreateFoos: migrating =======================================
-- create_table(:foos)
   -> 0.0018s
== 20240111132518 CreateFoos: migrated (0.0019s) ==============================
```

Add `require "prism"` in `config/application` to emulate requiring from a dependency.
```ruby
require_relative "boot"

require "rails/all"

require "prism"
puts "Constant is defined: #{Prism}"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)
```

Run tests.
```
$ bundle exec rails test
```

### Expected behavior
Tests should run without any issues.

### Actual behavior
There is a `LoadError` for `prism/prism`, and Rails acts as if the migration that was run earlier hasn't been run yet. (Note that `Constant is defined: Prism` is output once, and then the `require` line fails).

```
> bundle exec rails test
Constant is defined: Prism
bin/rails aborted!
LoadError: cannot load such file -- prism/prism (LoadError)
/home/gazayas/ror/prism_issue/config/application.rb:9:in `<main>'
/home/gazayas/ror/prism_issue/Rakefile:4:in `require_relative'
/home/gazayas/ror/prism_issue/Rakefile:4:in `<main>'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
Migrations are pending. To resolve this issue, run:

        bin/rails db:migrate

You have 1 pending migration:

db/migrate/20240111132518_create_foos.rb
```

### System configuration
**Rails version**:
7.1.2

**Ruby version**:
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-darwin21]

**Comment by bparanj** [comment]
By default the migration is only run for development. You need to set the environment to test:
 RAILS_ENV=test bin/rails db:migrate
bin/rails aborted!
LoadError: cannot load such file -- prism/prism (LoadError)
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
/home/ubuntu/work/pris/config/application.rb:8:in `<main>'
/home/ubuntu/work/pris/Rakefile:4:in `require_relative'
/home/ubuntu/work/pris/Rakefile:4:in `<main>'
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/railties-7.1.2/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/railties-7.1.2/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/railties-7.1.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/railties-7.1.2/lib/rails/command.rb:156:in `invoke_rake'
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/railties-7.1.2/lib/rails/command.rb:73:in `block in invoke'
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/railties-7.1.2/lib/rails/commands.rb:18:in `<main>'
/home/ubuntu/.rvm/gems/ruby-3.3.0@r71/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)

**Comment by Edouard-chin** [comment]
Looks to be a bootsnap issue only when not running in development mode

```ruby
# name this file bug_report.rb

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "bootsnap"
end

ENV["BOOTSNAP_CACHE_DIR"] = "bootsnap_cache"
require "bootsnap/setup"

require "prism"

```

```sh
ruby bug_report.rb #> OK
RAILS_ENV=test ruby bug_report.rb #> Issue reproduced
RAILS_ENV=production ruby bug_report.rb #> Issue reproduced
```

**Comment by bparanj** [comment]
Here is the [issue](https://github.com/Shopify/bootsnap/issues/463)

**Comment by gazayas** [comment]
Thank you, @bparanj and @Edouard-chin.
