### ISSUE TITLE
Introduce Consolidated Methods for Common Check Operations

### ISSUE THREAD

**Issue by rehan-akmal** [rails/rails#50704]
### Problem
In our current Rails codebase, we frequently encounter situations where we need to check the presence, absence, or other conditions of multiple variables, which often results in long and repetitive code like this:
```
if a.present? && b.present? && c.present? && d.present? && e.present?
  # Do something
end
```
Reading and maintaining such code can become cumbersome and error-prone, especially as the number of variables increases.
### Proposal
To address this issue and enhance the readability and maintainability of our code, I think we can introduce consolidated methods for common check operations. These methods will simplify conditional checks on multiple variables and promote more elegant and DRY (Don't Repeat Yourself) coding practices.

### Expected behavior
New Methods
`all_present?` `any_present?`
`all_nil?` `any_nil?`
 `all_balnk?` `any_blank?`
 `all_true?` `any_true?`
 `all_false?` `any_false?`

We can introduce these new methods, which will accept multiple variables as arguments and return true if all or any of the variables are present, respectively. This would allow us to rewrite the previous example as follows:
```
if all_present?(a, b, c, d, e)
  Do something
end

if any_present?(a, b, c, d, e)
  Do something
end

if all_nil?(a, b, c, d, e)
  Do something
end

if any_nil?(a, b, c, d, e)
  Do something
end

-- all_true?, all_blank? etc.
```
### Generalized Methods:

Alternatively, we can create more generalized methods that accept both the operation (e.g., :present, :nil, :blank, :true, :false) and the variables to check. For instance, a method signature might look like  `check_all(operation, *variables)`
```
if check_all(:present, a, b, c, d, e)
  Do something
end

if check_all(:nil, a, b, c, d, e)
  Do something
end
```

This approach would provide flexibility for various types of checks beyond just presence.

**Comment by fatkodima** [comment]
This is a feature request, but we reserve GitHub issues for issues in the Rails framework.
Please use the [Rails forum](https://discuss.rubyonrails.org/) for the discussion first.

Personally, I do not think `all_present?(a, b, c)` is in any way better than `[a, b, c].all?(&:present?)`. Even the opposite.
