### ISSUE TITLE
`rails new --skip-test` breaks `rails --tasks`

### ISSUE THREAD

**Issue by thedanbob** [rails/rails#50700]
### Steps to reproduce
1. Generate a new rails app with the flag `--skip-test`, or comment out `require "rails/test_unit/railtie"` in an existing app's `application.rb` to disable the test framework.
2. Run `bin/rails --tasks` ~(or `bin/rake --tasks`)~

### Expected behavior
Rails outputs a list of available tasks.

### Actual behavior
Rails outputs `Unrecognized command "default" (Rails::Command::UnrecognizedCommandError)`

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.2

### Details
Here's the sequence that leads to the bug as I understand it:
1. Rake is invoked without a valid task name so its `top_level_tasks` [only contains the default task](https://github.com/ruby/rake/blob/a7ad109522d38b39024d6dd6b0def75e0eaedf46/lib/rake/application.rb#L791).
2. In Rails, the [default task is set](https://github.com/rails/rails/blob/c66b655bf8948622722c24e6455b9b41febbe3a6/railties/lib/rails/test_unit/testing.rake#L6) in a file loaded by `rails/test_unit/railtie`, which doesn't get loaded if tests are skipped.
3. Rails [raises an UnrecognizedCommandError](https://github.com/rails/rails/blob/c66b655bf8948622722c24e6455b9b41febbe3a6/railties/lib/rails/commands/rake/rake_command.rb#L23) before rake has a chance to [print the list of tasks](https://github.com/ruby/rake/blob/a7ad109522d38b39024d6dd6b0def75e0eaedf46/lib/rake/application.rb#L134).

### Workaround
Add the line `task :default` to a .rake file to set an empty default task.

**Comment by jonathanhefner** [comment]
Thank you for the bug report! :smiley:

> 2\. Run `bin/rails --tasks` (or `bin/rake --tasks`)

`bin/rake --tasks` should be unaffected.  It does not go through `Rails::Command::RakeCommand`.

  ```console
  $ bin/rake --tasks
  ...
  rake zeitwerk:check                     # Check project structure for Zeitwerk compatibility
  ```

I see that we have [one mention of `bin/rails -T`](https://github.com/rails/rails/blob/c66b655bf8948622722c24e6455b9b41febbe3a6/guides/source/active_record_multiple_databases.md?plain=1#L165) in the documentation.  In my opinion, `bin/rails -T` / `bin/rails --tasks` should not be officially supported.  They only list commands that are implemented as Rake tasks, whereas `bin/rails --help` lists all Rails commands.  Furthermore, it's possible that they will stop working entirely in the future as we migrate Rails commands from Rake to Thor.

I'm not necessarily opposed to fixing the issue, but are there other use cases where it is a problem?

**Comment by thedanbob** [comment]
> `bin/rake --tasks` should be unaffected. It does not go through `Rails::Command::RakeCommand`.

You're right, I thought I had tested it as being broken as well but I must have been mistaken. I've edited my report.

> I'm not necessarily opposed to fixing the issue, but are there other use cases where it is a problem?

We use it on our servers to detect and run specially named tasks as cron jobs. If it's deprecated our ops guy would just have to replace it with `rake --tasks`.

**Comment by mattr** [comment]
We've encountered the same issue when using RSpec -- it is not possible to generate the list of tasks prior to installation, since the `testing.rake` file is not loaded.

It would be possible to resolve this (partially) by moving the `task default: :test` line out of `testing.rake` and into the generated `Rakefile` (or a separate `lib/tasks/default.rake` generated file):
```shell
> rails -T
# ...
bin/rails zeitwerk:check

> rake -T
# ...
rake zeitwerk:check

> rake
rake aborted!
Don't know how to build task 'test' (See the list of available tasks with `rake --tasks`)
```
This has, to my mind, the added benefit of making the option to override the default rake task more obvious in the app (which could include additional comments).
