### ISSUE TITLE
Rails eager loads by default, disabled when one column is set to nullable in database schema

### ISSUE THREAD

**Issue by St4niuu** [rails/rails#50718]
### Steps to reproduce

I've got a model called Occurences:
Schema: 

```ruby
class CreateOccurences < ActiveRecord::Migration[7.0]
  def change
    create_table :occurences do |t|
      t.integer :state, null: false
      t.string :injector, null: false
      t.string :description, null: true
      t.string :start_employee, null: false
      t.string :finish_employee, null: true
      t.timestamp :start, null: false
      t.timestamp :finish, null: true
    end

    add_foreign_key :occurences, :injectors, column: :injector
    add_foreign_key :occurences, :employees, column: :start_employee
    add_foreign_key :occurences, :employees, column: :finish_employee

  end
end
```
Model:
```ruby
class Occurence < ApplicationRecord
  belongs_to :injector, foreign_key: :injector
  belongs_to :start_employee, foreign_key: :start_employee, class_name: "Employee"
  belongs_to :end_employee, foreign_key: :finish_employee, class_name: "Employee", optional: true
end
```

And a Employee model:
Schema:
```ruby
class CreateEmployees < ActiveRecord::Migration[7.0]
  def change
    create_table :employees, id: false do |t|
      t.string :id, null: false, index: { unique: true }, primary_key: true
      t.string :name, null: false
    end
  end
end
```

Model:
```ruby
class Employee < ApplicationRecord
  has_many :start_employee, foreign_key: :start_employee
  has_many :finish_employee, foreign_key: :finish_employee
end
```

On object creation, finish_employee is undefined, on update finish_employee is being set.

### Expected behavior
The key problem here is that, rails loses ability to eager load a column when it can be null, whatever it goes as value.

### Actual behavior
When I update the occurence object to provide  finish_employee and finish attributes, as of my definition in code - finish_employee expects instance of Employee, so under @occurence[:finish_employee] goes query with find function, to find the actual employee. To my suprise, when I tried to save "updated" occurence, rails tried to save ruby object's id "#<Employee:0x0000026f69911560" as a string, not its actual id as it was in start_employee. Despite of writing Employee object itself under @occurence[:start_employee], it's been saved as employee's id. The same happens when I fetch this, start_employee is being returned as eagerly loaded object, not only employee's id, finish_employee is loade with loaded only with pure id. Hope you get my problem.

Here is example of one fetched occurence, after the initial creation and update with finish values:
In this example I was forced to pass only the id of fetched Employee to the finish_employee attribute, cause it otherwise tried to save ruby object's id, problem is I don't have any employee with such an ID.

{
    "data": {
        "id": 1,
        "state": 4,
        "injector": {
            "id": "ST 52",
            "location": {
                "id": "Location name"
            },
            "duration": 120,
            "ip": "0.0.0.0"
        },
        "description": "",
        "start_employee": {
            "id": "3779332794",
            "name": "Surname Name"
        },
        "finish_employee": "3779332794",
        "start": "2024-01-11T20:43:53.000Z",
        "finish": "2024-01-11T20:44:14.000Z"
    }
}

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.2.2

**Comment by rafaelfranca** [comment]
Could you create a reproduction script with this template https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb?

**Comment by St4niuu** [comment]
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 7.0.8"

  # Use the Puma web server [https://github.com/puma/puma]
  gem "puma", "~> 5.0"

  # Build JSON APIs with ease [https://github.com/rails/jbuilder]
  # gem "jbuilder"

  # Use Redis adapter to run Action Cable in production
  # gem "redis", "~> 4.0"

  # Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
  # gem "kredis"

  # Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
  # gem "bcrypt", "~> 3.1.7"

  # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
  gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

  # Reduces boot times through caching; required in config/boot.rb
  gem "bootsnap", require: false

  # Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
  # gem "image_processing", "~> 1.2"

  # Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
  gem "rack-cors"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do

  create_table "employees", id: :string, force: :cascade do |t|
    t.string "name", null: false
    t.index ["id"], name: "index_employees_on_id", unique: true
  end

  create_table "injectors", id: :string, force: :cascade do |t|
    t.string "location", null: false
    t.integer "duration", null: false
    t.string "ip", null: false
    t.string "form"
    t.boolean "assigned", default: false
    t.index ["form"], name: "index_injectors_on_form"
    t.index ["id"], name: "index_injectors_on_id", unique: true
    t.index ["location"], name: "index_injectors_on_location"
  end

  create_table "locations", id: :string, force: :cascade do |t|
    t.index ["id"], name: "index_locations_on_id", unique: true
  end

  create_table "occurences", force: :cascade do |t|
    t.integer "state", null: false
    t.string "injector", null: false
    t.string "description"
    t.string "start_employee", null: false
    t.string "finish_employee"
    t.datetime "start", precision: nil, null: false
    t.datetime "finish", precision: nil
  end

  add_foreign_key "injectors", "locations", column: "location"
  add_foreign_key "occurences", "employees", column: "finish_employee"
  add_foreign_key "occurences", "employees", column: "start_employee"
  add_foreign_key "occurences", "injectors", column: "injector"
end


class Injector < ApplicationRecord
  belongs_to :location, foreign_key: :location
  has_many :cycles, foreign_key: :injector
  has_many :occurences, foreign_key: :injector
end

class Employee < ApplicationRecord
  has_many :start_employee, foreign_key: :start_employee
  has_many :finish_employee, foreign_key: :finish_employee
end


class Occurence < ApplicationRecord
  belongs_to :injector, foreign_key: :injector
  belongs_to :start_employee, foreign_key: :start_employee, class_name: "Employee"
  belongs_to :end_employee, foreign_key: :finish_employee, class_name: "Employee", optional: true
end

class Location < ApplicationRecord
  has_many :injectors, foreign_key: :location
end


class BugTest < Minitest::Test
  def test_association_stuff
    @location = Location.new(id: "US").save
    @location = Location.find(1)
    @injector = Injector.new(id: "ST 52", location: @location, duration: 120, ip: "0.0.0.0").save
    @injector = Injector.find(1)
    @employee = Employee.new(id: "123456789", name: "Jane Doe").save
    @employee = Employee.find(1)
    @occurence = Ocurrence.new(state: 5, injector: @injector, description: "", start_employee: @employee, start: "2024-01-11 21:00:00").save
    @occurence = Occurence.find(1)
    @occurence[:finish_employee] = @employee
    @occurence[:finish] = "2024-01-01 21:00:00"
    @occurence.save
  end
end
```

**Comment by St4niuu** [comment]
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 7.0.8"

  # Use the Puma web server [https://github.com/puma/puma]
  gem "puma", "~> 5.0"

  # Build JSON APIs with ease [https://github.com/rails/jbuilder]
  # gem "jbuilder"

  # Use Redis adapter to run Action Cable in production
  # gem "redis", "~> 4.0"

  # Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
  # gem "kredis"

  # Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
  # gem "bcrypt", "~> 3.1.7"

  # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
  gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

  # Reduces boot times through caching; required in config/boot.rb
  gem "bootsnap", require: false

  # Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
  # gem "image_processing", "~> 1.2"

  # Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
  gem "rack-cors"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do

  create_table "employees", id: :string, force: :cascade do |t|
    t.string "name", null: false
    t.index ["id"], name: "index_employees_on_id", unique: true
  end

  create_table "injectors", id: :string, force: :cascade do |t|
    t.string "location", null: false
    t.integer "duration", null: false
    t.string "ip", null: false
    t.string "form"
    t.boolean "assigned", default: false
    t.index ["form"], name: "index_injectors_on_form"
    t.index ["id"], name: "index_injectors_on_id", unique: true
    t.index ["location"], name: "index_injectors_on_location"
  end

  create_table "locations", id: :string, force: :cascade do |t|
    t.index ["id"], name: "index_locations_on_id", unique: true
  end

  create_table "occurences", force: :cascade do |t|
    t.integer "state", null: false
    t.string "injector", null: false
    t.string "description"
    t.string "start_employee", null: false
    t.string "finish_employee"
    t.datetime "start", precision: nil, null: false
    t.datetime "finish", precision: nil
  end

  add_foreign_key "injectors", "locations", column: "location"
  add_foreign_key "occurences", "employees", column: "finish_employee"
  add_foreign_key "occurences", "employees", column: "start_employee"
  add_foreign_key "occurences", "injectors", column: "injector"
end


class Injector < ApplicationRecord
  belongs_to :location, foreign_key: :location
  has_many :cycles, foreign_key: :injector
  has_many :occurences, foreign_key: :injector
end

class Employee < ApplicationRecord
  has_many :start_employee, foreign_key: :start_employee
  has_many :finish_employee, foreign_key: :finish_employee
end


class Occurence < ApplicationRecord
  belongs_to :injector, foreign_key: :injector
  belongs_to :start_employee, foreign_key: :start_employee, class_name: "Employee"
  belongs_to :end_employee, foreign_key: :finish_employee, class_name: "Employee", optional: true
end

class Location < ApplicationRecord
  has_many :injectors, foreign_key: :location
end


class BugTest < Minitest::Test
  def test_association_stuff
    @location = Location.new(id: "US").save
    @location = Location.find(1)
    @injector = Injector.new(id: "ST 52", location: @location, duration: 120, ip: "0.0.0.0").save
    @injector = Injector.find(1)
    @employee = Employee.new(id: "123456789", name: "Jane Doe").save
    @employee = Employee.find(1)
    @occurence = Ocurrence.new(state: 5, injector: @injector, description: "", start_employee: @employee, start: "2024-01-11 21:00:00").save
    @occurence = Occurence.find(1)
    @occurence[:finish_employee] = @employee
    @occurence[:finish] = "2024-01-01 21:00:00"
    @occurence.save
  end
end
```
This test case on my computer doesn't work, haven't really tested in ruby/rails anything yet, but I am going to and got no clue how to set it up.
