### ISSUE TITLE
(parallelization threshold is 50)

### ISSUE THREAD

**Issue by pedrodiogop** [rails/rails#50712]
Yesterday I was running the App without a problem but today I can't run. This should be simple but since I m new I don't know how to correct this issue. 

### Expected behavior
The App should just start.

### Actual behavior
I receive this:
rails -s 
Running 0 tests in a single process (parallelization threshold is 50)
Run options: --seed 52290

# Running:

Finished in 0.000377s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips

### System configuration
**Rails version**: 7.1.2

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin23]

**Comment by rafaelfranca** [comment]
I think you meant to run `rails s` instead of `rails -s`. Try that. Just to be use `rails server` or `rails s` is how you start the app.

**Comment by pedrodiogop** [comment]
oh, can't believe it. Yeah that was the problem.
Thank you.
