### ISSUE TITLE
rails/rails is dependent on yard, rails and sdoc

### ISSUE THREAD

**Issue by dorianmarie** [rails/rails#50739]
### Steps to reproduce

```
~/src> git clone git@github.com:rails/rails.git
Cloning into 'rails'...
remote: Enumerating objects: 859917, done.
remote: Counting objects: 100% (586/586), done.
remote: Compressing objects: 100% (334/334), done.
remote: Total 859917 (delta 332), reused 468 (delta 252), pack-reused 859331
Receiving objects: 100% (859917/859917), 262.58 MiB | 6.53 MiB/s, done.
Resolving deltas: 100% (642022/642022), done.
~/src> cd rails/
~/s/rails> bundle clean --force
Removing actioncable (7.1.2)
Removing actionmailbox (7.1.2)
Removing actionmailer (7.1.2)
Removing actionpack (7.1.2)
Removing actiontext (7.1.2)
Removing actionview (7.1.2)
Removing activejob (7.1.2)
Removing activemodel (7.1.2)
Removing activerecord (7.1.2)
Removing activestorage (7.1.2)
Removing activesupport (7.1.2)
Removing rails (7.1.2)
Removing railties (7.1.2)
Removing sdoc (2.6.1)
Removing yard (0.9.34)
~/s/rails> bundle
Bundle complete! 84 Gemfile dependencies, 221 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
~/s/rails> rake
rake aborted!
LoadError: cannot load such file -- rails/api/generator (LoadError)
<internal:/Users/dorianmariefr/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/Users/dorianmariefr/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/dorianmariefr/src/rails/railties/lib/rails/api/task.rb:4:in `<top (required)>'
<internal:/Users/dorianmariefr/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/Users/dorianmariefr/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/dorianmariefr/src/rails/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)
```

### Expected behavior

It runs the tests

### Actual behavior

It is dependent on yard, rails and sdoc being installed

### System configuration
**Rails version**: commit 4fb230d2140054f8d0114c2c8dcc659af10a7972 (HEAD -> main, origin/main, origin/HEAD)

Author: Xavier Noria <fxn@hashref.com>

Date:   Fri Jan 12 23:58:55 2024 +0100

**Ruby version**: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) +YJIT [arm64-darwin23]

**Comment by dorianmarie** [comment]
A good first step would be:

```
diff --git a/railties/lib/rails/api/task.rb b/railties/lib/rails/api/task.rb
index ddd7952381..da13beea4b 100644
--- a/railties/lib/rails/api/task.rb
+++ b/railties/lib/rails/api/task.rb
@@ -1,7 +1,7 @@
 # frozen_string_literal: true
 
 require "rdoc/task"
-require "rails/api/generator"
+require_relative "generator"
 
 module Rails
   module API
```

**Comment by skipkayhil** [comment]
Is there a reason to not use `bundle exec rake`?

**Comment by byroot** [comment]
Or just `bin/rake`. But I agree it's nice not to have to think about it.

**Comment by dorianmarie** [comment]
I feel like running `rake` is the standard way of running tests in a ruby project

**Comment by rafaelfranca** [comment]
No. Using Rake you are running outside of the bundle environment. Either you need `bundle exec` or some bundler binstub.

**Comment by rafaelfranca** [comment]
If you look on every single Ruby project, you don't see `Rakefiles` setting up the bundler environment, neither bundler does that when you generate a new gem. Rails apps setup the bundle environment, so I'm not opossed to do this in Rails, but definitely this isn't the standard way of running tests in Ruby projects.

Project might document `rake` as the way to run tests, but in reality they mean `bundle exec rake`. They just don't document that.

**Comment by rafaelfranca** [comment]
Example https://github.com/thoughtbot/factory_bot/blob/main/CONTRIBUTING.md#running-the-test-suite

**Comment by dorianmarie** [comment]
Ok I'm just gonna `alias rake "bundle exec rake"'. For thoughtbot projects I just run `rspec` but I have `alias rspec "bundle exec rspec"` because there could be multiple versions of rspec.
