### ISSUE TITLE
Assets Precompile Issue on CircleICi

### ISSUE THREAD

**Issue by raoehtesham03** [rails/rails#50765]
### Steps to reproduce
I have upgraded my rails application from 6.1 to 7.0. So, while running the test cases on CircleCi it is not able to execute below line :-
                   stylesheet_link_tag "mailer
However, everything is working fine on local.

### Actual behavior
 Failure/Error: = stylesheet_link_tag "mailer"
     
     ActionView::Template::Error:
       Error: StringMap expected string key

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.0.6

Is this related to assets precompile on CircleCi ?
Please help me to figure out this.

I am getting this error on 

        rake assets:precompile
                      
                      
        rake aborted! ExecJS::ProgramError: Error: StringMap expected string key stringmap.set

**Comment by Edouard-chin** [comment]
Closing. See comment on your previous issue https://github.com/rails/rails/issues/50725#issuecomment-1889780403 if you want us to help.
