### ISSUE TITLE
Request: rename Rails console as irr or something other than irb

### ISSUE THREAD

**Issue by MtnBiker** [rails/rails#50770]
Maybe not the right place to post this.

But it's confusing that the prompt for irb and rails console is the same.

**Comment by Edouard-chin** [comment]
You can create a `~/.irbrc` file and customize irb as you wish here. You can use something like this:

```ruby
if ENV["RAILS_ENV"]
  IRB.conf[:PROMPT][:RAILS] = IRB.conf[:PROMPT][:DEFAULT].clone
  IRB.conf[:PROMPT][:RAILS][:PROMPT_I] = "%N(rails):%03n> "

  IRB.conf[:PROMPT_MODE] = :RAILS
end
```

**Comment by MtnBiker** [comment]
Thanks. Works like a charm.

**Comment by rafaelfranca** [comment]
Maybe we should do that automatically. @dhh what do you think?

**Comment by dhh** [comment]
What's the problem we're trying to solve?

**Comment by dhh** [comment]
Why is it an issue that the prompt is the same between vanilla irb and irb loaded with the Rails app? That's the first time I've heard of that causing someone problems.

**Comment by rafaelfranca** [comment]
I believe because of the methods available in Rails console are drastically different from just calling `irb` so if you have two terminals one with the console another one with the irb, you don't know where you are at. I have seeing people also changing the prompt to show if the console is a production console.

In general, I think it would be good developer experience to Rails to show a more informative prompt.

**Comment by dhh** [comment]
Yeah, I could be on for making it more informative. Like including the env. But also don't want to make the line too long. Don't think adding (rails) to it is meaningful.

**Comment by MtnBiker** [comment]
Length: `irb(rails):002>` vs `irb(main):001>` using @Edouard-chin Edouard-chin. They are the same in the two places I use it. 

Maybe `irc(main)` for rails console and `irb(main)` as it has been.

They are different environments and shouldn't look the same.

**Comment by dhh** [comment]
Actually, if anything, we should shave off the needless prefixing. "irb(main):001>" is just noise for us. But I'd take "dev:001>" and "prod:001>". Problem is we don't have any structured abbreviated names for envs. You don't want "development:001>" and "production:001>". Too long.

**Comment by MtnBiker** [comment]
An example of where confusion can arise. In [Active Record Query Interface](https://guides.rubyonrails.org/active_record_querying.html), Section 2.1.1, the following example `irb> customer = Customer.find(10)` appears. The word console appears no where on that page. I think some will think irb means irb, not rails console.

**Comment by Edouard-chin** [comment]
Oops, looks like I closed this too early and there is more to it, sorry!
I don't have much opinion on the topic.

> You don't want "development:001>" and "production:001>". Too long.

For reference, the prompt name on a postgres repl is the name of the database, which never bothered me and felt it was too long. 🤷 
```
❯ bin/rails dbconsole

my_app_development=#
```

**Comment by st0012** [comment]
Just to add some ideas and notes:

- You can use `IRB.conf[:IRB_NAME]` to replace `irb` from the prompt more easily.
    - For example, `IRB.conf[:IRB_NAME] = Rails.root.basename.to_s` will give you 
        `my-app(main):001>`
- IRB has colorisation module that can also be used here.
    - `IRB.conf[:IRB_NAME] = IRB::Color.colorize(Rails.root.basename.to_s, [:BLUE, :BOLD])` will show `my-app` in blue and the rest in the default colour.
    - Displaying different environments in different colours may be helpful as I've seen a few apps showing `production` in red.
- The way Rails currently invokes IRB doesn't allow it to use `IRB.conf` for configuration. So if we decided to customise the prompt, some additional adjustments need to be made there too. I'll be happy to help on this :-)

**Comment by rafaelfranca** [comment]
@st0012 can we move forward with `"dev:001>" and "prod:001>"`?

**Comment by st0012** [comment]
@rafaelfranca sure no problem. I'll prepare a PR for it.

**Comment by byroot** [comment]
> `"dev:001>" and "prod:001>"`?

Is the `001` even worth it? I don't quite see the value of it. My `irbrc` just strips it.

**Comment by dhh** [comment]
Agree, I'd rather do without.

**Comment by st0012** [comment]
Maybe the saved space display the app/folder name, like `dev:my-app>` or `my-app(dev)>`?

**Comment by byroot** [comment]
I think the application name would be valuable yes, especially for people who often juggle between multiple applications.

My preference goes to `my-app(dev)>` but no strong opinion here.

**Comment by dhh** [comment]
Dig that a lot 👌

**Comment by st0012** [comment]
PR for the prompt change: https://github.com/rails/rails/pull/50825

**Comment by dorianmariefr** [comment]
Wouldn't development and production be more consistent with the rest of the usage in rails?

**Comment by ghiculescu** [comment]
> I think the application name would be valuable yes, especially for people who often juggle between multiple applications.
> 
> My preference goes to `my-app(dev)>` but no strong opinion here.

Would you consider adding the Rails version to the prompt?

Eg. `my-app @ 7.1.1(dev)>`

We've found it handy when doing upgrades, or switching between apps on different versions.

**Comment by dhh** [comment]
Too much for me. But great to point someone at how they can customize this further.

Context > Consistency on prod/dev. I don't want a long prefacing line. It's just ugly.

**Comment by chaadow** [comment]
> > `"dev:001>" and "prod:001>"`?
> 
> Is the `001` even worth it? I don't quite see the value of it. My `irbrc` just strips it.

Actually this helps me when i put `binding.irb` and debugging inside of rails console.
Ehen the counter resets to 001, it means i'm inside a new irb, which then i can safely leave with `control + D` without exiting my rails console session.

Now i'm a bit lost, but it's not that big of a deal, I can add it back to my irbrc. 

It was just to share my "experience".
