### ISSUE TITLE
Tests can't run without yarn

### ISSUE THREAD

**Issue by arusa** [rails/rails#50772]
### Steps to reproduce

1. Create a new rails app that uses yarn
2. `docker build -t testimage:1 .`
3. `docker run -it testimage:1 /bin/bash`
4. `bin/rails test`

### Expected behavior

As the image already contains all precompiled assets I would expect the tests to be able to run successfully even without precompiling first.

### Actual behavior

`bin/rails test` now always runs `test:prepare`, which tries to compile the assets and therefore crashes, because the default Dockerfile doesn't keep yarn in the image.

I want an option to skip running `test:prepare` when running tests.

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.1.4

**Comment by rafaelfranca** [comment]
I don't think we should skip `test:prepare` since it can run more things, but I can see us not trying to compile assets if they are present like we used to do with sprockets.

**Comment by rafaelfranca** [comment]
BTW, I know the current dockerfile is supposed to be used to run tests, but I'm planning to change that. The Dockerfile used for CI will be the same one that will be used in development, and that will for sure include yarn. That is another way to solve this issue.

**Comment by waymondo** [comment]
i ran into this today too after a Rails update where we have a docker setup where an image already has the precompiled assets (an no yarn executable). i learned though that `cssbundling-rails` allows you to bypass the build step with an ENV var:

https://github.com/rails/cssbundling-rails/blob/main/lib/tasks/cssbundling/build.rake#L63
