### ISSUE TITLE
rails routes --unused error for nil controllers

### ISSUE THREAD

**Issue by jacquesn** [rails/rails#50784]
I don't know how to reproduce this one, but I'll describe it. Running `rails routes --unused` raises:

> rails/commands/unused_routes/unused_routes_command.rb:42:in `action_missing?': undefined method `to_sym' for nil (NoMethodError)

I seem to somehow have three instances of `ActionDispatch::Journey::Route` where their `RouteInfo` `@controller_name` and `@action_name` are `nil`. 

If I add a line in `RouteInfo#unused?`, I can get the command to work for me (super helpful command by the way!):

```
def unused?
  return false if @controller_name.nil? # This line

  controller_class_missing? || (action_missing? && template_missing?)
end
```

If I comment out all my application routes, I still get this problem, so I'm guessing the problem routes are coming from gems or something in my particular Rails configuration. One of the bad routes, for instance, gives an instance of `Sprockets::Environment` on `.app.app`. 

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.3.0

**Comment by hahmed** [comment]
@jacquesn if you can upload a repo that reproduces this issue that would be great, otherwise there is not much to go on.

**Comment by jacquesn** [comment]
I've determined the problem. I had a namespace collision with `Controller` through a service in my app. I should just change that service name 😅
