### ISSUE TITLE
Undocumented - validations enabled by autosave

### ISSUE THREAD

**Issue by semaperepelitsa** [rails/rails#50807]
Validations are enabled by default when autosave is true:

    belongs_to :foo, autosave: true
    has_one :foo, autosave: true

https://github.com/rails/rails/blob/9c3ffab47c3bf59320ba08e9dafdb0275cf91a5a/activerecord/lib/active_record/reflection.rb#L653-L658

However, this is not documented in `has_one` or `belongs_to`:

https://github.com/rails/rails/blob/9c3ffab47c3bf59320ba08e9dafdb0275cf91a5a/activerecord/lib/active_record/associations.rb#L1660-L1669

https://github.com/rails/rails/blob/9c3ffab47c3bf59320ba08e9dafdb0275cf91a5a/activerecord/lib/active_record/associations.rb#L1830-L1840

**Comment by semaperepelitsa** [comment]
Still relevant.

**Comment by rafaelfranca** [comment]
Fixed by #50856
