### ISSUE TITLE
Segmentation Fault on Docker and ruby 3.3.0

### ISSUE THREAD

**Issue by dorianmarie** [rails/rails#50839]
### Steps to reproduce

See this repository for a minimal reproduction

https://github.com/dorianmarie/rails-segmentation-fault-minimal

Running `docker build -t tmp .` triggers the crash

### Expected behavior

Doesn't crash

### Actual behavior

Crashes

### System configuration
**Rails version**: Rails 7.1.3

**Ruby version**: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) +YJIT [arm64-darwin23]

**Comment by dorianmarie** [comment]
I'm going to report to ruby as well

**Comment by dorianmarie** [comment]
Ok so this is it I think https://bugs.ruby-lang.org/issues/20085?tab=history https://github.com/ruby/ruby/pull/9371

It's not been backported to 3.3 (e.g. future 3.3.1) yet.

**Comment by rafaelfranca** [comment]
Not a Rails issue
