### ISSUE TITLE
ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError)

### ISSUE THREAD

**Issue by raoehtesham03** [rails/rails#50835]
### Steps to reproduce
I have upgraded my rails application from 6.0 to 6.1 . Since then when I am  executing below queries

```ruby
 d = Document.find(768365)
 d.page_image.variant(resize_to_limit: Document::PAGE_IMAGE_STYLES[:small]).processed

```
I am getting this error
### Actual behavior
  ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError)

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.0.6

**Comment by Edouard-chin** [comment]
👋 Please use the bug report template https://github.com/rails/rails/blob/ee88f4133f732ccc57904047972d66082d9c34d2/guides/bug_report_templates/active_storage.rb to reproduce the problem. We can't investigate much with the two lines of code your provided otherwise.
