### ISSUE TITLE
Rails logs error messages with huge stack trace that I can't silence

### ISSUE THREAD

**Issue by bcowell** [rails/rails#50831]
Every time I have a runtime error running either the rails server or tests my error logs include a massive stack trace that I haven't been able to silence.

[Gist of example development.log](https://gist.github.com/bcowell/b48ab2e820f474e3130e8bd2f3f6c140)

### Steps to reproduce
1. Run `rails s`
2. Edit any line in a method to have invalid ruby
3. Save the file and execute so it runs the method/test
> My console fills with the massive stack trace

### Expected behavior
I expect an error message to include a reasonable stack trace with a few lines.

### Actual behavior
Stack trace on every error is roughly 10k lines...

### System configuration
MacBook Pro 2019 Intel 
macOS 13.3.1

**Rails version**:
6.1.7.6
**Ruby version**:
5.0.2

**Comment by fatkodima** [comment]
Are you from the future 
> Ruby version:
> 5.0.2

or from the past? 😄 

> Rails version:
> 6.1.7.6

Rails 6.1 is not supported for bugfixed and the problem seems from the `listen` gem which is not used in modern rails. Try to upgrade rails.

**Comment by bcowell** [comment]
> Are you from the future
> 
> > Ruby version:
> > 5.0.2
> 
> or from the past
> 
> > Rails version:
> > 6.1.7.6
> 
> ? 😄
> 
> Rails 6.1 is not supported for bugfixed and the problem seems from the `listen` gem which is not used in modern rails. Try to upgrade rails.

Ahh ya sorry that should say v3.0.2.
Thanks I’ll give that a try
