### ISSUE TITLE
belongs_to association doesn't work with composite `primary_key` option

### ISSUE THREAD

**Issue by bguban** [rails/rails#50850]
### Steps to reproduce
I have an aggregator model that represents the same entity from different providers. This model has a single primary but some of the providers have a composite key. So I must use 2 columns to be able to build the reflection

```
class Ticker < ApplicationRecord
  # this model has gvkey and iid but they are not the primary key. just fields to build the relation
  has_many :co_actions, primary_key: [:gvkey, :iid], query_constraints: [:gvkey, :iid]
end

class CoAction
  # this model has gvkey and iid as a foreign key
  belongs_to :ticker, primary_key: [:gvkey, :iid], query_constraints: [:gvkey, :iid]
end
```

When I run
```
CoAction.take.ticker
```
it returns
```
/activerecord-7.1.3/lib/active_record/reflection.rb:576:in `check_validity!': Association CoAction#ticker primary key [:gvkey, :iid] doesn't match with foreign key ["gvkey", "iid"]. Please specify query_constraints, or primary_key and foreign_key values. (ActiveRecord::CompositePrimaryKeyMismatchError)
```
but I would expect to receive the ticker model instead. The composite_primary_key gem does what expected but rails 7.1.3 relation builder converts the primary key into a string instead. So what you see in the message is a string `"[:gvkey, :iid]"`. (ActiveRecord::Reflection::BelongsToReflection#association_primary_key)

### System configuration
**Rails version**: 7.1.3

**Ruby version**: 3.2.1

**Comment by bguban** [comment]
Hey @nvasilevski. Thanks for the quick response. I think the problem is conceptual. With the singular primary/foreign keys I was able to specify both (primary and foreign) in the relation and override the primary_key defined in the class but now, with the composite primary key, I'm only able to specify the foreign_key in the relation but the primary key is always taken from the class. 

Going back to the schema. The ticker model has its own singular primary key and it connects to other models (except co_action) using its own key. Here is the schema:
```
ActiveRecord::Schema.define do
  create_table :tickers, id: true, force: true do |t|
    t.integer :gvkey
    t.integer :iid
  end

  create_table :co_actions, id: true, force: true do |t|
    t.integer :gvkey
    t.integer :iid
  end
end

class Ticker < ActiveRecord::Base
  has_many :co_actions, primary_key: [:gvkey, :iid], foreign_key: [:gvkey, :iid]
end

class CoAction < ActiveRecord::Base
  belongs_to :ticker, query_constraints: [:gvkey, :iid], primary_key: [:gvkey, :iid]
end

class BugTest < Minitest::Test
  def test_association_stuff
    ticker = Ticker.create!(gvkey: 123, iid: 321)
    CoAction.create!(gvkey: 123, iid: 321)
    assert_equal ticker, CoAction.take.ticker
  end
end
```
I understand that the schema looks weird but the `co_actions` table is given by a 3rd party provider so I can't add a `ticker_id` column to it.

**Comment by Jay0921** [comment]
@bguban I'm not sure if this will resolve the problem.
```
class Ticker < ActiveRecord::Base
  self.primary_key = [:gvkey, :iid]

  has_many :co_actions, query_constraints: [:gvkey, :iid]
end

class CoAction < ActiveRecord::Base
  self.primary_key = [:gvkey, :iid]

  belongs_to :ticker, query_constraints: [:gvkey, :iid]
end
```

**Comment by nvasilevski** [comment]
@Jay0921 While this should work as well, overriding `primary_key` is less preferable just because I find it semantically incorrect. I treat `primary_key` as a term coming from the db-level and I would prefer it to reflect the actual state of the database schema. This is why `query_constraints` is a little better option since it will behave as a "virtual primary key" while not making `primary_key` value misleading. 

But ultimately I agree that there is a legit issue (limitation) in current Rails capabilities and it needs to be addressed
