### ISSUE TITLE
Running "bundle exec rake rdoc" more than once does not work

### ISSUE THREAD

**Issue by sato11** [rails/rails#50871]
### Steps to reproduce
1. Run "bundle exec rake rdoc" to fully generate "doc/rdoc" contents
1. Touch any file that should contain API documentation
1. Run again "bundle exec rake rdoc"

### Expected behavior

"Only generate documentation for files that have been changed since the API was generated," according to [the comment](https://github.com/rails/rails/blob/v7.1.3/railties/lib/rails/api/task.rb#L163-L164).

### Actual behavior
Aborts with messages like;

```
Parsing sources...
100% [ 1/ 1]  railties/lib/rails/api/task.rb

Generating API format into /workspaces/rails/doc/rdoc...
rake aborted!
Could not find main page "/workspaces/rails/railties/RDOC_MAIN.md" among rendered files
```

### Notes
The commit https://github.com/rails/rails/commit/9e99649e7e525b6ee1d4901c89711c0b0693fe4f introduced the mtime-based enhancement for those who work on the API documentation locally. However, its logic even filters out the main page, namely `railties/RDOC_MAIN.md`, which I seldom touch but is necessary for rdoc to build.

Not being able to execute the task more than once seems to be a bug on one hand, but on the other hand the fact no one has ever fixed it since the change took place 7-8 years ago makes be biased to believe this is not a bug.

I've followed [the rdoc section in the guides](https://edgeguides.rubyonrails.org/api_documentation_guidelines.html#rdoc) and got stuck. That's why I believe something can be fixed, but I'm afraid I'm not able to tell if this is a program issue or a documentation issue.

So I'd like to seek advice. Has anybody come across the same issue?

**Comment by rafaelfranca** [comment]
This is a bug in the code. Do you mind trying to fix?

**Comment by sato11** [comment]
Thanks! I'll do it 🙂
