### ISSUE TITLE
Allow comments on `railsrc`.

### ISSUE THREAD

**Issue by ruyrocha** [rails/rails#50899]
### Steps to reproduce

Allow comments on `railsrc` file, as right now they're treated as arguments:
```ruby
ruy@devastator ~/D/Rails> rails new --api chaotic-api
Using --database=trilogy --css=tailwind --skip-jbuilder #--template=~/Development/Rails/template.rb from /home/ruy/.railsrc
Based on the specified options, the following options will also be activated:

  --skip-javascript [due to --api]
  --skip-hotwire [due to --skip-javascript]
  --skip-asset-pipeline [due to --api]
```

### Expected behavior
Commented out lines are not treated as arguments.

### Actual behavior
Comments behave like command line arguments.

### System configuration
**Rails version**: 7.1.3

**Ruby version**: 3.2.3

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.

**Comment by ruyrocha** [comment]
Thank you so much for pointing me to the right direction, @rafaelfranca :pray:
