### ISSUE TITLE
Rails 7.1 undefined method purge & same for variant using ruby 3.3.0-dev

### ISSUE THREAD

**Issue by kashifcodility** [rails/rails#50932]
irb(main):047> image
=> 
#<ActiveStorage::Attachment:0x00007ff81133c0a0
 id: 4,
 name: "images",
 record_type: "News",
 record_id: 2,
 blob_id: 4,
 created_at: Wed, 31 Jan 2024 12:00:01.463996000 UTC +00:00>
irb(main):048> 
irb(main):049> 
irb(main):050> image.class
=> ActiveStorage::Attachment(id: integer, name: string, record_type: string, record_id: integer, blob_id: integer, created_at: datetime)
irb(main):051> 
irb(main):052> 
irb(main):053> 
irb(main):054> image.purge
/home/lap-053/.rbenv/versions/3.3.0-dev/lib/ruby/gems/3.4.0+0/gems/activemodel-7.1.3/lib/active_model/attribute_methods.rb:489:in `method_missing': undefined method `purge' for an instance of ActiveStorage::Attachment (NoMethodError)

**Comment by fatkodima** [comment]
Can you create a reproduction script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_storage.rb template?
