### ISSUE TITLE
Should there be a RAILS_MASTER_KEY_DUMMY like SECRET_KEY_BASE_DUMMY?

### ISSUE THREAD

**Issue by dorianmariecom** [rails/rails#50939]
### Steps to reproduce

Have a rails app with `config.require_master_key = true`

```
RAILS_ENV=production SECRET_KEY_BASE_DUMMY=1 bin/rails assets:precompile
```

### Expected behavior

It ignores the master key requirement?

### Actual behavior

Error:

```
Missing encryption key to decrypt file with. Ask your team for your master key and write it to /rails/config/master.key or put it in the ENV['RAILS_MASTER_KEY'].
```

### System configuration
**Rails version**: Rails 7.1.3
**Ruby version**: ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [arm64-darwin23]

----

What about a RAILS_MASTER_KEY_DUMMY=1?

**Comment by morgoth** [comment]
I believe this could be solved by having
`config.require_master_key = ENV["SECRET_KEY_BASE_DUMMY"].nil?`

**Comment by skipkayhil** [comment]
Since this is a feature request (and the idea was rejected previously), I'm going to go ahead and close. Feel free to continue discussion on https://discuss.rubyonrails.org
