### ISSUE TITLE
ActiveStorage::IntegrityError (ActiveStorage::IntegrityError)

### ISSUE THREAD

**Issue by raoehtesham03** [rails/rails#50947]
### Steps to reproduce
I have upgraded my rails application from 5.2 to 6.0 and then 6.0 to 7.0 . So, I am getting ActiveStorage::IntegrityError (ActiveStorage::IntegrityError) while I am trying to get -
```ruby
 attachment.variant(resize_to_limit: resize).processed.url
```

### Expected behavior
It should not give this error.

### Actual behavior
Getting this  ActiveStorage::IntegrityError (ActiveStorage::IntegrityError) Error.

### System configuration
**Rails version**: 3.0.6

**Ruby version**:  7.0.8

Please provide me the solution to resolve this problem I am stuck on it since a week.

**Comment by skipkayhil** [comment]
Unfortunately we don't have the bandwidth to debug application issues, only bugs in the Rails framework. If you are able to provide a reproduction of this issue that indicates there is a bug in Rails then I can re-open this issue, but until then I'm going to have to close
