### ISSUE TITLE
[Bug][7.1+] Development of "Add validation option for enum" is incomplete

### ISSUE THREAD

**Issue by james-em** [rails/rails#50959]
### Steps to reproduce
According to the changelog https://github.com/rails/rails/releases/tag/v7.1.0 (Find: Add validation option for enum) there is a new feature introduced in Rails 7.1 where is is possible to add `validate: true` to an enum to avoid raising an exception as soon as an invalid value is assigned to an enum.

It seems the work was properly done but only to one of the 2 possible syntax.

```ruby
# Fine:
enum :something, %i[test1 test2], validate: true

# Not fine:
enum something_else: { test1: "test1", test2: "test2"}, _validate: true
```

### Expected behavior
Both should behave the same

### Actual behavior
The second line will prevent Rails to even boot as it will consider `_validate: true` to be an enum value and will raise 
```
raise ArgumentError, "Enum values #{values} must be either a non-empty hash or an array."
```

### System configuration
**Rails version**: 7.1.3

**Ruby version**: 3.2.2

**How to fix Rails**
activerecord-7.1.3/lib/active_record/enum.rb

```ruby
    def enum(name = nil, values = nil, **options)
      if name
        values, options = options, {} unless values
        return _enum(name, values, **options)
      end

      # HERE: Simply add: :_validate to definitions because the signature of _enum is def _enum(name, values, prefix: nil, suffix: nil, scopes: true, instance_methods: true, validate: false, **options)
      definitions = options.slice!(:_prefix, :_suffix, :_scopes, :_default, :_instance_methods, :_validate)
      options.transform_keys! { |key| :"#{key[1..-1]}" }

      definitions.each { |name, values| _enum(name, values, **options) }
    end
```

**Comment by fatkodima** [comment]
`validate: ...` is an implemented syntax, not a `_validate: ...`. Why do you expect it to work?

**Comment by james-em** [comment]
> `validate: ...` is an implemented syntax, not a `_validate: ...`. Why do you expect it to work?

Hi,

This is just how enums are built.

You can do the following:

```
enum :my_enum, [:value, :value2], prefix: true, suffix: false, instance_methods: false, validate: true

enum another_enum2: { value: "something" }, _prefix: true, _suffix: false, _instance_methods: false
```

But in the second instance you can't do the following: `_validate: true`

It simply appears to have been forgotten, don't you agree?

**Comment by fatkodima** [comment]
Ok, I see that is already implemented in https://github.com/rails/rails/pull/50333
