### ISSUE TITLE
rails new fails if bootsnap is missing from the Gemfile used to run the 'rails new' command (updated)

### ISSUE THREAD

**Issue by koenhandekyn** [rails/rails#50966]
### Steps to reproduce

i'm launching this from a root dir with a gemfile pointing to rails/rails latest greatest as of today (some 720alpha version in other words) 

```bash
be rails new rails-blank-7.2.0.alpha --css=tailwind -a=propshaft
```

note that moving into the dir and then manually doing the ```rails importmap:install``` actually works! 

### Expected behavior

a rails app ready to get rolling 

### Actual behavior

```
         run  bundle install --quiet
         run  bundle lock --add-platform=x86_64-linux
Writing lockfile to /Users/koenhandekyn/Work/rails-blank-7.2.0.alpha/Gemfile.lock
         run  bundle lock --add-platform=aarch64-linux
Writing lockfile to /Users/koenhandekyn/Work/rails-blank-7.2.0.alpha/Gemfile.lock
         run  bundle binstubs bundler
       rails  importmap:install
<internal:/Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- bootsnap/setup (LoadError)
	from <internal:/Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/koenhandekyn/Work/rails-blank-7.2.0.alpha/config/boot.rb:4:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
       rails  turbo:install stimulus:install
<internal:/Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- bootsnap/setup (LoadError)
	from <internal:/Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/koenhandekyn/Work/rails-blank-7.2.0.alpha/config/boot.rb:4:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
       rails  tailwindcss:install
<internal:/Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- bootsnap/setup (LoadError)
	from <internal:/Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/koenhandekyn/Work/rails-blank-7.2.0.alpha/config/boot.rb:4:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
```

### System configuration

**Rails version**: 7.2.0.alpha

**Ruby version**: 3.2.3

**Comment by skipkayhil** [comment]
I tried running the same command but wasn't able to reproduce. Any chance you have the full log of the command? My guess is bootsnap failed to compile during the first `bundle install` and that failure cascaded.

**Comment by koenhandekyn** [comment]
ok sorry

some refinements: seems this is not a specific 7.2.0.alpha issue. i just tried on 7.1.3 and it also fails, indeed pointing to bootsnap.

```
       rails  importmap:install
<internal:/Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- bootsnap/setup (LoadError)
	from <internal:/Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/koenhandekyn/Work/rails-blank-test/config/boot.rb:4:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
       rails  turbo:install stimulus:install
<internal:/Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- bootsnap/setup (LoadError)
	from <internal:/Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/koenhandekyn/Work/rails-blank-test/config/boot.rb:4:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
       rails  tailwindcss:install
<internal:/Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- bootsnap/setup (LoadError)
	from <internal:/Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/koenhandekyn/Work/rails-blank-test/config/boot.rb:4:in `<top (required)>'
	from bin/rails:3:in `require_relative'
	from bin/rails:3:in `<main>'
```

however, on both versions, if i then 'cd' into the project and run 'rails  importmap:install', the command actually runs fine

```ll
❯ rails  importmap:install
       apply  /Users/koenhandekyn/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/importmap-rails-2.0.1/lib/install/install.rb
  Add Importmap include tags in application layout
      insert    app/views/layouts/application.html.erb
  Create application.js module as entrypoint
      create    app/javascript/application.js
  Use vendor/javascript for downloaded pins
      create    vendor/javascript
      create    vendor/javascript/.keep
  Configure importmap paths in config/importmap.rb
      create    config/importmap.rb
  Copying binstub
      create    bin/importmap
         run  bundle install
```

further, i just tested it with mri 3.2.3 and 3.2.2 and both seem to have the same issues. next to this initialisation i don't seem to have any bootsnap issues.

because i'm not in a 'project' directory when i launch this command, i don't seem to have a bootsnap tmp folder that i can delete?

i'm doing a gem uninstall bootsnap / all versions / gem install bootsnap > compiling > done without errors : but i'm still getting the same errors. 

i'm running bundle exec to pin my rails version but i don't haver bootsnap in my Gemfile. adding bootsnap.

```bundle add bootsnap```

and surprise > it now works.

CONCLUSION

i was using a Gemfile to 'pin' a specific rails version as i have multiple rails versions on my system, as many have. also it allows me to pin to a rails version from a branch or a git tag.

however, for it to work it seems we also need to add bootsnap, so the smallest Gemfile to install a new rails project for a specific version seems to be the below.

```
source "https://rubygems.org"
gem "rails", "7.1.3"
gem "bootsnap", "~> 1.18"
```

my issue seems 'solved' somehow, but i think the rails core team should reflect why bootsnap is required for installing a new rails project. it shouldn't is my feeling.

**Comment by rafaelfranca** [comment]
The problem is that you are constraining the bundle environment to that `Gemfile` you are using to run the `rails new` command. Any gem that isn't there, but is in the application's Gemfile would fail to load because they aren't in the bundler environment.

> i think the rails core team should reflect why bootsnap is required for installing a new rails project. it shouldn't is my feeling.

It isn't. You are generating a Rails application in a constrained environment that isn't how the `rails new` command is supposed to run. If you have multiple versions of Rails in your machine and you want to use a specific version to generate the app the right command to do is:

```
rails _7.1.3_ new something
```

Your reproduction is failing with bootsnap but it would fail with any gem that isn't a dependency of the `rails` gem.
