### ISSUE TITLE
Improve ActiveStorage Proxy Documentation

### ISSUE THREAD

**Issue by jmarsh24** [rails/rails#50963]
The current guide https://edgeguides.rubyonrails.org/active_storage_overview.html#authenticated-controllers for building an authenticated controller in rails proxy mode isn't complete. If you follow the included example you will end up with the following error.

```
ArgumentError:
       Cannot generate URL for xxxxxxxx.jpg using Disk service, please set ActiveStorage::Current.url_options.
```

```ruby
# app/controllers/logos_controller.rb
class LogosController < ApplicationController
  # Through ApplicationController:
  # include Authenticate, SetCurrentAccount

  def show
    redirect_to Current.account.logo.url
  end
end
```

The proposed fix for this is to set the current host options by prepending `include ActiveStorage::SetCurrent` at the top of the controller.

```ruby
# app/controllers/logos_controller.rb
class LogosController < ApplicationController
  include ActiveStorage::SetCurrent
  # Through ApplicationController:
  # include Authenticate, SetCurrentAccount

  def show
    redirect_to Current.account.logo.url
  end
end
```

**Comment by AmandaPerino** [comment]
Hi @jmarsh24 thanks for bringing this to our attention. I have linked this issue in the task for updating the Active Storage guide, and will have a team look at it as soon as they can.
