### ISSUE TITLE
ActiveSupport::TimeZone.new raises ArgumentError

### ISSUE THREAD

**Issue by dan-jensen** [rails/rails#50976]
### Steps to reproduce

Instantiate an `ActiveSupport::TimeZone` object using the ["initialize" syntax](https://github.com/rails/rails/blob/f14401aa17c02cfad2213b5bb92a650f43ee4b86/activesupport/lib/active_support/values/time_zone.rb#L299):

```ruby
ActiveSupport::TimeZone.new('America/Toronto', -28800)
```

### Expected behavior

An object should be returned of `ActiveSupport::TimeZone` class.

### Actual behavior

An exception is raised: "ArgumentError: wrong number of arguments (given 2, expected 1)".

This occurs because the [`new` method](https://github.com/rails/rails/blob/f14401aa17c02cfad2213b5bb92a650f43ee4b86/activesupport/lib/active_support/values/time_zone.rb#L299) over-writes the [`initialize` method](https://github.com/rails/rails/blob/f14401aa17c02cfad2213b5bb92a650f43ee4b86/activesupport/lib/active_support/values/time_zone.rb#L303), and it only expects one argument.

### System configuration
**Rails version**: 7.1.2

**Ruby version**: 3.1.3

**Comment by p8** [comment]
`create` does work:
```ruby
ActiveSupport::TimeZone.create('America/Toronto', -28800)
=> #<ActiveSupport::TimeZone:0x000000012ac4ef20 @name="America/Toronto", @utc_offset=-28800, @tzinfo=#<TZInfo::DataTimezone: America/Toronto>>
```

**Comment by dan-jensen** [comment]
@p8 Nice, that does work! It works because [alias_method :create, :new](https://github.com/rails/rails/blob/f14401aa17c02cfad2213b5bb92a650f43ee4b86/activesupport/lib/active_support/values/time_zone.rb#L211) aliases `initialize` before the `new` method over-writes it. This is fascinating, because it means the [documentation for `create`](https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html#method-c-create) is also incorrect (it shows the method signature of the `new` method when it should be the `initialize` method).

**Comment by p8** [comment]
Hmm, that doc is confusing. I'll see if I can change it.

**Comment by dan-jensen** [comment]
Yeah, seems like correcting the documentation will be the easiest solution here. It would be nice to clean up the code, on the premise that it's confusing and we should generally avoid overriding `initialize` with `new`, but that doesn't seem to be easy. I tried renaming `def initialize` as `def self.create` and removing  the alias, but many tests fail.

For clarity, I believe the [documentation](https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html) needs these 2 corrections:

![documentation-revisions](https://github.com/rails/rails/assets/3031162/8124a786-b2d3-4c39-bbbc-dc0f0482e74f)

**Comment by dan-jensen** [comment]
@p8 thanks for the incredibly quick action on this, you rock!

**Comment by p8** [comment]
Thanks @dan-jensen 🙏
