### ISSUE TITLE
Add the ability to configure minimum number of active connections for connection pool

### ISSUE THREAD

**Issue by catlee** [rails/rails#50989]
Currently ActiveRecord connection pools support configuring a maximum size via the [`pool`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html#:~:text=database%20connection%20configuration%3A-,pool,-%3A%20maximum%20number%20of) configuration setting.

Establishing new connections to the DB can be a relatively expensive operation, and so we want to try and make sure that the application always has a minimum number of established connections to the DB. We can do that in our application's initialization path, but connections which have been idle for too long will get cleaned up by the reaper.

I'd like to add support for specifying a minimum pool size to the connection pools so that we can ensure we always have a certain number of active connections to the DB established.

As a starting point, I propose the following changes:

* [ ] Rename `size` to `max_size` in [`ConnectionPool`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/ConnectionPool.html)
* [ ] Alias `size` to `max_size` for backwards compatibility
* [ ] Add `min_size` as a supported option to [`ActiveRecord::DatabaseConfigurations::HashConfig`](https://api.rubyonrails.org/classes/ActiveRecord/DatabaseConfigurations/HashConfig.html)
* [ ] Optionally rename `pool` to `max_size` for clarity, and add an alias for `pool` for backwards compat
* [ ] Modify `ConnectionPool` and `ConnectionPool::Reaper` to respect the minimum pool size

I will add a PR that implements these ideas.

**Comment by zzak** [comment]
Since there is a PR already and this is a new feature, I think we can close the issue
