### ISSUE TITLE
jemalloc Dockerfile configuration may be problematic across architectures

### ISSUE THREAD

**Issue by modosc** [rails/rails#50991]
i just noted https://github.com/rails/rails/pull/50943 merged (which is awesome!). however, i think there may be some issues when running on different architectures. 

see [this comment](https://github.com/docker-library/ruby/issues/182) for a solution. i'm not 100% sure how to apply this to the `Dockerfile` generation in rails (otherwise i'd create a pr) but i know locally we had to do this to ensure our `Dockerfile` ran our rails app + `jemalloc` across the following architectures:
 * aarch64-linux
 * arm64-darwin-*
 * x86_64-darwin-*
 * x86_64-linux

also i haven't tested the [other simpler solution](https://github.com/docker-library/ruby/issues/182#issuecomment-1570307359) proposed in this issue either but maybe it's the way to go?

**Comment by byroot** [comment]
> see https://github.com/docker-library/ruby/issues/182 for a solution.

You linked to the whole issue so I'm not 100% certain what you are talking about, but the PR I merged work on multi-platform.

So closing. If I misunderstood and there is really a problem I can re-open, but please describe the problem better.
