### ISSUE TITLE
Trilogy:EOFError cannot be recovered on ActiveRecord 7.1

### ISSUE THREAD

**Issue by zhangyangyu** [rails/rails#50993]
### Steps to reproduce

```ruby
require 'json'
require 'rack'
require 'base64'
require "bundler"

Bundler.require(:default)

#$app ||= Rack::Builder.parse_file("#{__dir__}/config.ru").first
#RELATIVE_URL_ROOT = ENV['RAILS_RELATIVE_URL_ROOT']

ActiveRecord::Base.establish_connection(
  adapter:            'trilogy',
  database:           'test',
  host:               'xxxx',
  username:           'xxxxx',
  password:           'xxxxx',
  port:               4000,
  ssl_mode:           'VERIFY_IDENTITY',
  encoding:           'utf8mb4',
  collation:          'utf8mb4_general_ci',
  pool:               2500,
  checkout_timeout:   5,
  connect_timeout:    5,
  read_timeout:       5,
  idle_timeout:       0,
  reaping_frequency:  0,
)

Dir["./app/models/*.rb"].each do |file|
  require file
end

def handler(event:, context:)
  httpMethod = event.fetch('httpMethod')
  STDOUT.write Process.pid
  STDOUT.write "\n"
  STDOUT.write httpMethod
  STDOUT.write "\n"

  if httpMethod == "POST"
    discard = Message.take().as_json()
    STDOUT.write discard
    STDOUT.write "\n"
    discard = 'returned'
    return {
      'statusCode' => 200,
      'body' => discard,
    }
  else
    return {
      'statusCode' => 200,
      'body' => "pong"
    }
  end
end
```

We are using ActiveRecord 7.1.3 on AWS Lambda Function to connect to database using Trilogy driver(2.7). We found occasionally there are `EOFError`. We tried to reproduce it and find when a connection is checked out from the pool, [after some time](https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-troubleshooting.html#nat-gateway-troubleshooting-timeout) when the underlying TCP connection is broken, following query on the connection could trigger the error. On AWS Lambda Function we could steadily reproduce it with all 7.1.x versions. 7.0.8 works well. Can't reproduce it locally. And pool configuration like `idle_timeout`/`reaping_frequency` doesn't change anything.
![img_v3_027q_971706a5-dfe9-4e5b-ac37-114d993fc1dg](https://github.com/rails/rails/assets/3690895/90e09bbf-828b-449d-8e10-8c6c3fcf496b)

### Expected behavior
The broken connection could be recovered and doesn't affect application.

### Actual behavior
Error is raised.
### System configuration
**Rails version**:
7.1
**Ruby version**:
3.2.2

**Comment by jhawthorn** [comment]
Hello! Could you make sure you are wrapping each unit of work (the body of your handler function) with `Rails.executor.wrap` https://guides.rubyonrails.org/threading_and_code_execution.html#wrapping-application-code.

Using executor.wrap (which a standard Rails application will wrap the request in) will checkout and checkin the connection from the pool around the work being done. The checkout will also have a ping to verify the connection and will automatically reconnect if it fails. Without the executor wrap, Active Record doesn't know your expectations of it and so can't safely reconnect (though there is some exploration being done of).

I'm not sure why a difference would be seen between 7.0 and 7.1
