### ISSUE TITLE
Passing an array to the `model` parameter of `form_with` does not work with singular, unpersisted resources

### ISSUE THREAD

**Issue by johnpitchko** [rails/rails#51008]
### Steps to reproduce

Passing an array to the `model` parameter of `form_with` when the terminal resource in the array is singular _AND_ unpersisted generates an incorrect path. In the example below, ActionDispatch generates a named path of `posts_comments_path`, which does not exist because the routes defines a singular `comment` resource, so the valid path should be `posts_comments_path`.

In my testing, this issue only appears of the resource is unpersisted; so works fine if the form is updating a saved resource but not when creating a new resource. My own _highly_ inexperienced analysis discovered that the `PolymorphicRoutes` class will [return a singular resource path _if_ the resource is persisted](https://github.com/rails/rails/blob/36c1591bcb5e0ee3084759c7f42a706fe5bb7ca7/actionpack/lib/action_dispatch/routing/polymorphic_routes.rb#L317). If the resource is new, then the code runs [this line to generate a plural path](https://github.com/rails/rails/blob/36c1591bcb5e0ee3084759c7f42a706fe5bb7ca7/actionpack/lib/action_dispatch/routing/polymorphic_routes.rb#L321).

I understand that this _might_ be an intentional design or may be justified for some reason beyond my understanding. Also, I appreciate that it may not be possible for ActionDispatch to be aware if the resource is singular or plural.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
  gem 'sqlite3'
  gem 'debug'
end

# require "action_controller/railtie"
require "active_record"
require "action_view"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_one :comment
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"

    resources :posts do
      resource :comment
    end
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < ActionView::TestCase
  include ActionView::Helpers::FormHelper
  include Rails.application.routes.url_helpers

  def test_something
    post = Post.create

    result = form_with model: [post, Comment.new] 
    assert result.match %r{"\/posts\/1\/comment"}
  end

  private

  def app
    Rails.application
  end
end

```

### Expected behavior
ActionDispatch should return the correct path using a singular child resource `/posts/1/comment`

### Actual behavior
ActionDispatch returns the incorrect path using a plural child resource `/posts/1/comments`

### System configuration
**Rails version**: 7.1.3

**Ruby version**: 3.0.2

**Comment by johnpitchko** [comment]
Did some digging and it appears this is a known limitation of the `polymorphic_url` code. I was able to get what I needed to work by specifying the `url` attribute in the `form_with` method call.

**Comment by zzak** [comment]
I think this is a duplicate of #49604
