### ISSUE TITLE
Pure ruby view templates, pages and components

### ISSUE THREAD

**Issue by sebyx07** [rails/rails#51018]
Came across this project called [Matestack UI Core](https://github.com/matestack/matestack-ui-core) and couldn't help but think it's pretty cool. What's your opinion on making ruby the language to write the templates instead of html, and also write abstractions to reduce the need of js:

Here's a quick look at how it works:

For controllers, pretty standard stuff:

```ruby
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    item = Item.find(params[:id])
    render Items::ShowPage.new(item:)
  end
end
```

And then, instead of juggling between HTML and Ruby, you keep it all Ruby:

`views/index.rb`

```ruby
h1 "Items"

@items.each do |item|
  div do
    link_to item.title, item_path(item)
  end
end
```

span "Items count: #{@items.count}"

`pages/items/show_page`

```ruby
module Items
  class ShowPage
    include ActivePage
    attr_reader :item

    def initialize(item:)
      @item = item
    end

    def template
      page_title
      div class: 'card' do
         div do
            h3 item.title
        
            link_to "Items" items_path
        
            render Items::ItemDetailsComponent.new(item:)
         end
      end
    end
    
    def page_title
      h1 "Show Item", class: 'title'
    end
    
    def style
       {
         h1: {
            color: 'red'
         }
       }
    end
  end
end
```

And you can define components like so:

`components/items/item_details_component`

```ruby
module Items
  class ItemDetailsComponent
    include ActiveComponent
    
    attr_reader :item

    def initialize(item:)
      @item = item
    end

    def template
      table do
        # Details go here
      end
    end
  end
end
```
I'm thinking this could really simplify how we handle views and frontend logic in Rails apps. Plus, it's Ruby through and through, which is always a plus

Also there is [matestack-ui-vuejs](https://github.com/matestack/matestack-ui-vuejs) which has some really interesting ways to hide the use of js.

This could pave the path to leveraging powerful component libraries similar to those available in React, such as Ant Design or Material-UI. While Hotwire offers a solid approach, the elegance of pure Ruby, coupled with its dynamic nature, allows us to utilize JSX-like templating effectively.

@dhh

**Comment by dhh** [comment]
Not my cup of tea. But whatever floats your boat!

We don't use this issue tracker for inbound feature requests, though. So probably best place for you to explore this is as a gem. All the best ✌️
