### ISSUE TITLE
GlobalID::Locator.locate_signed cannot find SGIDs created in a Rails 6.1 app

### ISSUE THREAD

**Issue by goulvench** [rails/rails#51051]
### Steps to reproduce
1. Attach `ActiveRecord` items in an `ActionText` in a Rails 6.1 app
2. Update the app to Rails 7.1
3. Display the action_text, but all attachables are missing.

I found that `Rails.application.key_generator.generate_key('signed_global_ids')` generates different keys in Rails 6 and 7, so I guess it's a config change in the `key_generator` itself.

This looks like a duplicate of #40266, but in my case the secret_key_base has not been changed, as shown in the bug report below.
People have reported the same problem in the [forum](https://discuss.rubyonrails.org/t/rails-6-1-7-gives-404-for-actiontext-attachments/80803), but the solution isn't applicable in my situation.

[Gist](https://gist.github.com/goulvench/c035bc90ed04c33be2212da43fa35146), or script below
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  #gem "rails", "6.1"
  gem "rails", github: "rails/rails", branch: :main

  gem "sqlite3"
end

require "active_record/railtie"
require "active_storage/engine"
require "action_text/engine"
require "tmpdir"

class TestApp < Rails::Application
  config.load_defaults 6.1

  config.root = __dir__
  config.hosts << "example.org"
  config.eager_load = false
  config.session_store :cookie_store, key: "cookie_store_key"
  config.secret_key_base = "secret_key_base"

  config.active_storage.service = :local
  config.active_storage.service_configurations = {
    local: {
      root: Dir.tmpdir,
      service: "Disk"
    }
  }
  # Disable logging for a cleaner output
  config.logger = Logger.new(nil)
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

Rails.application.initialize!

require ActiveStorage::Engine.root.join("db/migrate/20170806125915_create_active_storage_tables.rb").to_s

# Disable migration logging for a cleaner output
ActiveRecord::Migration.verbose = false
ActiveRecord::Schema.define do
  CreateActiveStorageTables.new.change

  create_table :users, force: true
end

class User < ActiveRecord::Base
  has_one_attached :profile
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_blob_sgid_after_rails_upgrade
    user = User.create!(
      profile: {
        content_type: "text/plain",
        filename: "dummy.txt",
        io: ::StringIO.new("dummy"),
      }
    )
    puts "Rails version: #{Rails::VERSION::STRING}"
    rails_6_sgid = "eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJalJuYVdRNkx5OTBaWE4wTFdGd2NDOUJZM1JwZG1WVGRHOXlZV2RsT2pwQ2JHOWlMekUvWlhod2FYSmxjMTlwYmdZNkJrVlUiLCJleHAiOm51bGwsInB1ciI6ImF0dGFjaGFibGUifX0=--aa099340e7af7ec6ce1af3866ade911ea22c7834"

    assert_equal rails_6_sgid, user.profile.blob.attachable_sgid
  end
end
```

### Expected behavior

```ruby
GlobalID::Locator.locate_signed(rails_6_sgid) # => Original attachable
```

### Actual behavior

```ruby
GlobalID::Locator.locate_signed(rails_6_sgid) # => nil
```

### System configuration
- **Rails version**: 7.1.3 and edge
- **Ruby version**: 3.1.4

**Comment by goulvench** [comment]
Finally found a way to load previous SGIDs.

```ruby
# config/application.rb
# Keep using Rails 6.1 hash digest settings
config.active_support.key_generator_hash_digest_class = OpenSSL::Digest::SHA1
# Rails 7 doesn't automatically use the secret_key_base defined in credentials
config.secret_key_base = credentials.secret_key_base
```

The heart of the problem is that Rails 7 no longer automatically picks up a `secret_key_base` defined in credentials in a dev environment, which may be caused by #48470.

**Comment by maxvlc** [comment]
Hi @goulvench,

I've encountered the same issue and found that applying that configuration resolves it. 
Although you mentioned the development environment, implementing this in the application also impacts production and other environments without any issues, right?

Thks!

**Comment by goulvench** [comment]
Hi @maxvlc, I haven't yet deployed to staging to confirm (I still have issues preventing deploy), but I think this issue is restricted to local (aka test/dev) environments. 

If you look at [rails/railties/lib/rails/application.rb#L478](https://github.com/rails/rails/blob/a42ca9cf1436ac7c6051dc6530d27eb4b04ab5f9/railties/lib/rails/application.rb#L478), you'll see that the code paths are different in local vs prod environments.

```ruby
def secret_key_base
  if Rails.env.local? || ENV["SECRET_KEY_BASE_DUMMY"]
    config.secret_key_base ||= generate_local_secret
  else
    validate_secret_key_base(
      ENV["SECRET_KEY_BASE"] || credentials.secret_key_base || begin
        secret_skb = secrets_secret_key_base

        if secret_skb.equal?(config.secret_key_base)
          config.secret_key_base
        else
          Rails.deprecator.warn(<<~MSG.squish)
            Your `secret_key_base` is configured in `Rails.application.secrets`,
            which is deprecated in favor of `Rails.application.credentials` and
            will be removed in Rails 7.2.
          MSG

          secret_skb
        end
      end
    )
  end
end
```

**Comment by rafaelfranca** [comment]
You are probably jumping too many versions at once. Are you also applying the 7.1 new framework default?

**Comment by maxvlc** [comment]
Not at all, I'm currently on Rails 7.0.8 and in the process of upgrading to 7.1.3. From what I've observed, there are differences between them, but not necessarily in the versions.

@rafaelfranca, are you referring to these defaults?
`config.load_defaults 7.1` inside `application.rb`? Yes, I've also implemented that.

What I've noticed is that in environments other than production/staging (at least as I have them configured via environment variables), it successfully retrieves the secrets without any issue. The problem only occurred in the development environment.

Thanks to both of you!

**Comment by goulvench** [comment]
This issue is actually a duplicate of issue #50925, which accurately traced the problem to #48470.

After this change, during development Rails looks for the `secret_key_base` in config, and in credentials in other settings. The line 
```ruby
config.secret_key_base = credentials.secret_key_base
```
can therefore be changed to:
```ruby
config.secret_key_base = credentials.secret_key_base if Rails.env.local?
```

I'm not sure I understand the reason for this divergence. Maybe the Rails code could be changed to `config.secret_key_base ||= credentials.secret_key_base | generate_local_secret` to improve dev/prod parity.
