### ISSUE TITLE
New find_or_create_by behavior in Rails 7.1 can introduce subtransactions in PostgreSQL

### ISSUE THREAD

**Issue by stanhu** [rails/rails#51052]
In https://github.com/rails/rails/pull/45720, `find_or_create_by` was modified to call `create_or_find_by`, but that [method](https://github.com/rails/rails/blob/023a3eb3c046091a5d52027393a6d29d0576da01/activerecord/lib/active_record/relation.rb#L214-L218) can introduce subtransactions in PostgreSQL via the `transaction(requires_new: true)` call:

```ruby
def create_or_find_by(attributes, &block)
  transaction(requires_new: true) { create(attributes, &block) }
rescue ActiveRecord::RecordNotUnique
  find_by!(attributes)
end
```

As I mentioned in https://about.gitlab.com/blog/2021/09/29/why-we-spent-the-last-month-eliminating-postgresql-subtransactions/, we spent a lot of effort to get rid of subtransactions because they suffer from significant performance issues at scale. We saw all our database replicas stall out at times as a result:

> In a busy database, it's possible for the size of the subtransaction log to grow so large that the working set no longer fits into memory. This results in a lot of cache misses, which in turn causes a high amount of disk I/O and CPU as PostgreSQL furiously tries to load data from disk to keep up with all the lookups.

Has this been solved in PostgreSQL yet? No. The commits highlighted in https://postgres.ai/blog/20210831-postgresql-subtransactions-considered-harmful#ideas-for-postgresql-development haven't made it into PostgreSQL upstream yet. I see there is recent activity in this thread: https://www.postgresql.org/message-id/flat/CAFiTN-vzDvNz=ExGXz6gdyjtzGixKSqs0mKHMmaQ8sOSEFZ33A@mail.gmail.com

For now, we're going to patch ActiveRecord to revert the change, but I'd suggest reverting this or making it some option for those who really need to deal with the racy conditions outlined.

**Comment by rafaelfranca** [comment]
Thank you for the issue. Did you try to apply pressure to the PostgreSQL project so they can apply that patch, or find a different solution for the problem? They might not know the problem exists in real deployments, and it seems a big users of the database, you can have some influence there.

As for what we should do in Rails, I don't think we should do anything about a database implementation miss behaving. Implementing a different version of `find_or_create_by` in applications that have this problem should be easy enough. Now, if we can show MySQL or SQLite3 has the same problem, we should reconsider that change.

cc @matthewd @byroot

**Comment by matthewd** [comment]
Yeah I'm not keen on even implicitly committing us to avoid introducing more subtransactions in general, to be honest (see #44518, which has languished, but I do still really want to pursue).

The most plausible, sufficiently isolated, solution I could see us considering would be to have an adapter-level config option that just globally disables savepoints (so we never create one, and any rollback always goes all the way up to the full txn). @stanhu would that work / be helpful for you, or is that an overly blunt sledgehammer?

**Comment by stanhu** [comment]
@matthewd That would be helpful, especially in development or test. However, in test, savepoints happen all the time due to database cleanup between tests, so it's difficult to block those entirely.

In production, we generally don't prevent subtransactions from happening since it's not always obvious when they occur since it depends on being called within an existing transaction. However, we alert whenever any code path introduces a subtransaction. To do this, we [patched ActiveRecord to record the depth of transactions](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/67918/diffs), and alert any time the depth is > 1.

**Comment by ghiculescu** [comment]
As an alternative fix, we could investigate the `ON CONFLICT DO NOTHING` idea from: https://github.com/rails/rails/pull/31989#discussion_r169772156. That might enable us to remove the subtransaction entirely.

**Comment by byroot** [comment]
> As an alternative fix, we could investigate the `ON CONFLICT DO NOTHING` idea

Yeah, sounds nice, can be an extra `supports_....` in the adapters.

**Comment by hms** [comment]
@stanhu 

If you revert the change as you described above, you will find that in the rescue case, any open transitions that are inflight prior to the create_or_find statement, by your code or by Rails, will be in an invalid state won't commit. In fact, that database connection will be in an invalid state until a rollback is issued on it.  

Whenever Postgres bumps into a database constraint that fails (such as the above immediate unique index enforced at the database level), it sets the transaction to an invalid state and it's effectively dead / useless until a rollback.  The value of the requires_new: true is that the rollback is constrained to just the attempted insert statement.

The suggested fix by @byroot (thanks, didn't know about that option) looks like an interesting and potentially better / faster solution for Postgres.  Unfortunately, between the 'big 3' supported databases, the syntax for implementing a non-savepoint solution for create_or_find is different: 

- Postgres: insert ... on conflict do nothing
- mysql: insert ignore ...
- sqlite: insert or ignore ...

And with all three, there is the open question of what is returned on the 'do nothing' / 'ignore' case so the control of flow can be implemented.
