### ISSUE TITLE
has_many through alias_method

### ISSUE THREAD

**Issue by OskarEichler** [rails/rails#51062]
We are trying to do something like this:

```
  has_many :source_tracks
  alias_method :source_objects, :source_tracks
  has_many :source_object_genres, through: :source_objects
```

However it seems like ActiveRecord does not recognize the alias_method for source_objects:

```
ActiveRecord::HasManyThroughAssociationNotFoundError: Could not find the association :source_objects
```

 Is that something that could get added?

### System configuration
**Rails version**: 7.1.3
**Ruby version**: 3.2.1

**Comment by OskarEichler** [comment]
Similarly this isn't working either on the alias_method:

```
UTrack.where(id: u_object_ids).includes(:source_objects)
```
or
````
ActiveRecord::Associations::Preloader.new(records: u_objects, associations: [:source_objects]).call
```

**Comment by OskarEichler** [comment]
I guess it would need something like an alias_association

**Comment by nvasilevski** [comment]
Hey, thanks for the report!

>I guess it would need something like an alias_association

This is something that is being considered but hasn't gain much traction due to use-cases not being very clear https://github.com/rails/rails/pull/49801

It is expected that `alias_method` won't be sufficient to provide capability of aliasing an existing association, but perhaps you could achieve this by defining one more association with a different name, like:

```ruby
  has_many :source_tracks
  has_many :source_objects, class_name: "SourceTrack"
  has_many :source_object_genres, through: :source_objects
```

**Comment by OskarEichler** [comment]
Thanks @nvasilevski we are using this solution, however this is causing other issues when loading relations. So for example when doing this:

```
UTrack.includes(:source_tracks).each{ |ut| ut.source_objects }
```

The preloading here doesn't work as now the relations source_objects and source_tracks are different even though they yield the same results.
