### ISSUE TITLE
`DuplicableTest#test_duplicable` failure with ruby 3.4.0dev 

### ISSUE THREAD

**Issue by yahonda** [rails/rails#51075]
Managed to reproduce CI failure at https://buildkite.com/rails/rails-nightly/builds/165#018da4eb-5216-4c18-b84b-32e067fdb17a/1250-1260

### Steps to reproduce
- Install ruby 3.4.0dev that includes https://github.com/ruby/ruby/commit/de1a586ecc2ee7f465f0c0a69291054136a3a819
```ruby
git clone https://github.com/rails/rails
cd rails
rm Gemfile.lock
bundle install
cd activesupport
bin/test test/core_ext/object/duplicable_test.rb -n test_duplicable
```

### Expected behavior
It should pass.

### Actual behavior
It fails as follows.

```ruby
F

Failure:
DuplicableTest#test_duplicable [test/core_ext/object/duplicable_test.rb:15]:
Method.
TypeError expected but nothing was raised.


bin/test test/core_ext/object/duplicable_test.rb:12



Finished in 0.000362s, 2762.5911 runs/s, 5525.1823 assertions/s.
1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.4.0dev (2024-02-12T17:31:48Z master de1a586ecc) [x86_64-linux]

**Comment by yahonda** [comment]
According to git bisect, this behavior changes since https://github.com/ruby/ruby/commit/de1a586ecc2ee7f465f0c0a69291054136a3a819 via https://github.com/ruby/ruby/pull/9926

cc @byroot as one of the author of this commit.

**Comment by byroot** [comment]
Thanks for letting me know. I'll fix the test tomorrow.
