### ISSUE TITLE
Add .test to default allowed host in development mode

### ISSUE THREAD

**Issue by dhh** [rails/rails#51086]
By default, puma-dev uses the .test TLD to route development requests, and we should ensure that this works out of the box. Right now you'll get this error message:

![CleanShot 2024-02-14 at 08 04 48@2x](https://github.com/rails/rails/assets/2741/1a7758ae-dfac-4af0-9f6b-e5beed025f6d)

That's pretty unfriendly for a golden path like puma-dev. So let's add \.test$ as a default allowed TLD.

**Comment by la-ruby** [comment]
wondering whether its a bug with Rails 7.1.3.2 - i get this line duplicated:

    config.hosts << "793c-2600-1012-b059-1095-a889-73bb-b74e-4c73.ngrok-free.app"

<img width="803" alt="image" src="https://github.com/rails/rails/assets/55279023/27f33f8f-039c-4dcf-a3c6-27eeed114f9c">
