### ISSUE TITLE
DatabaseTasks run in both development and test environments when RAILS_ENV=development

### ISSUE THREAD

**Issue by deissimon** [rails/rails#51105]
### Steps to reproduce
```ruby
# Commands executed with the expectation of affecting only the development environment:
RAILS_ENV=development rake db:create
RAILS_ENV=development rake db:schema:load
RAILS_ENV=development rake db:drop
# Additional operations like purge, prepare also included.
```

The commands above impact both the development and test environments, despite my expectation for them to affect only the development environment. Is this expected?

### Expected behavior
The database creation, schema loading, and dropping should be confined to the development environment.

### Actual behavior
The database is created, and the schema is loaded, among other actions, in both the development and test environments.

### System configuration
Rails Version: 7.1.3 (issue persists in earlier versions as well)

**Ruby version**:
Ruby Version: 3.2.2

**Comment by deissimon** [comment]
This can lead to some unexpected behavior when I depend on some custom schemas which are created beforehand the rails schema is load because the schema was not created for test database yet. Is this intended?

**Comment by rafaelfranca** [comment]
Yes. It is expected behavior. You can use `SKIP_TEST_DATABASE` if you want to disable that behavior.

**Comment by rafaelfranca** [comment]
You can read https://github.com/rails/rails/issues/27299 if you are wondering why.

Duplicate of #27299
