### ISSUE TITLE
url_for helper incorrectly combines query parameters on routes with a default parameter

### ISSUE THREAD

**Issue by DanielHeath** [rails/rails#51147]
### Steps to reproduce

Define a route with a query parameter in the route.
Call url_for to generate that route, providing additional query parameters.

```ruby# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "rails"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/foo?bar=baz" => "test#index", as: :foo
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_returns_success
    assert_equal url_helpers.foo_path(query: :param), "/foo?bar=baz&query=param"
  end

  private
    def url_helpers
      Rails.application.routes.url_helpers
    end
end
```

### Expected behavior
The additional URL parameters should be added using an `&`

### Actual behavior
The additional URL parameters are added using an `?`

### System configuration
**Rails version**: 7.1.3

**Ruby version**: 3.2.2

**Comment by rafaelfranca** [comment]
This isn't supported. You should not define routes with query params. Rails doesn't match routes with them

**Comment by DanielHeath** [comment]
Defining routes this way hasn't caused any errors in current or past versions of rails. 

Given it's doesn't work and isn't going to, would a PR be accepted to raise a deprecation/error if you try to?

**Comment by rafaelfranca** [comment]
> would a PR be accepted to raise a deprecation/error if you try to?

Yes! That would be better.
