### ISSUE TITLE
ActiveRecord queries against an unmigrated database breaks Zeitwerk

### ISSUE THREAD

**Issue by shamas-** [rails/rails#51158]
### Steps to reproduce
1. Define a `has_and_belongs_to_many` relationship on a model, for example
```ruby
class Apple < ApplicationRecord
  has_and_belongs_to_many :oranges
end
```
2. Setup the relationship using `create_join_table` in a migration file
3. Write code to use the relationship such as
```ruby
# file.rb
Apple.joins(:oranges).first #line 1
```
4. Use `schema_format = :sql`
5. Run the migration from step 2 to update db/structure.sql
6. Roll the database back
7. Run `bin/rails zeitwerk:check`

### Expected behavior
7. "All is good!" output

### Actual behavior
6. This is output:
```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "oranges_apples" does not exist
LINE 1: ...* FROM "apples" INNER JOIN "oranges...

/Users/person/file.rb:1
```

### Commentary
The obvious solution is to run the migration. However, it's not always possible to run the migration before running some other code that Zeitwerk will eager load on. For example in a production scenario I need to build the deployment and then run the migration later through the built deployment code. During asset precompilation in the build phase I am seeing the above style of error in connection with this kind of error:

```
       ERROR in ./app/javascript/other/afile1.js.erb
       Module build failed (from ./node_modules/rails-erb-loader/index.js):
       Error: rails-erb-loader failed with code: 1
           at ChildProcess.<anonymous> (/tmp/build_6e8198a8/node_modules/rails-erb-loader/index.js:128:16)
           at ChildProcess.emit (node:events:514:28)
           at maybeClose (node:internal/child_process:1105:16)
           at ChildProcess._handle.onexit (node:internal/child_process:305:5)
        @ ./app/javascript/application.js 5:187-232
       
       webpack 5.76.3 compiled with 1 error in 10796 ms
```

@fxn 

### System configuration
**Rails version**: 7.0.8

**Ruby version**: 3.1.4

**Comment by rafaelfranca** [comment]
I don't think there is a solution for this problem. If you loaded `file.rb` and that code is trying to execute code that depends on the database schema, there is no other workaround than upgrading the database schema.

**Comment by rafaelfranca** [comment]
A common solution to this problem is first to ship the database schema, then, when the database is ready and migrate, deploy the code that uses that schema

**Comment by fxn** [comment]
Let me add for extra clarification that Zeitwerk is not really related to this (which @rafaelfranca is already saying).

The problem is that the file is being evaluated, and it cannot be evaluated. The application is the one doing that by means of having eager loading enabled. How is eager loading implemented is not really relevant to this situation.

You are asking the framework to eager load, and the code cannot be eager loaded.
