### ISSUE TITLE
Docs: ActiveRecord validations - Skipping Validations fails to mention callbacks/timestamps in some cases

### ISSUE THREAD

**Issue by Earlopain** [rails/rails#51169]
### Steps to reproduce

https://guides.rubyonrails.org/active_record_validations.html#skipping-validations lists a bunch of methods that skip validations. One of these is `update_columns`, which in addition to skipping validations also skips callbacks and doesn't update timestamps. This is explained in the method doc at https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-update_columns but should also be mentioned there.

Other listed methods likely do something similar.

### Expected behavior
Docs should mention what other consequences there are to using these methods apart from just skipping validations. Might be fine to just put this as a general note, urging the user to look up the docs for the method they are intersted in using.
 Maybe method docs can be linked to directly from the list instead of just using method name code blocks?

**Comment by Edouard-chin** [comment]
> https://guides.rubyonrails.org/active_record_validations.html#skipping-validations lists a bunch of methods [...] which in addition to skipping validations also skips callbacks [...] but should also be mentioned there.

Isn't that page only related to documenting validation though?

The information related to skipping callback on `update_columns` is mentioned in the [callback documentation](https://guides.rubyonrails.org/active_record_callbacks.html#skipping-callbacks) which similarly doesn't mention that it skips validations.

**Comment by Earlopain** [comment]
That's a good point, however I would say the same applies there as well.

They mention being careful about skipping them, each for a different reason. You only have the full picture if you know about it, read the method docs, or read both guides.
