### ISSUE TITLE
Updating delegated types using delegate type attributes produces orphaned children

### ISSUE THREAD

**Issue by SteveKhuu** [rails/rails#51170]
### Steps to reproduce
```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails', '~> 7'
  gem 'sqlite3', platform: :mri
end

require 'active_record'
require 'minitest/autorun'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :products do |t|
    t.references :purchasable, polymorphic: true
    t.text :name

    t.timestamps
  end

  create_table :digital_goods do |t|
    t.boolean :drm_free

    t.timestamps
  end

  create_table :physical_goods do |t|
    t.decimal :weight

    t.timestamps
  end
end

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Product < ApplicationRecord
  delegated_type :purchasable, types: %w[DigitalGood PhysicalGood]

  accepts_nested_attributes_for :purchasable
end

class DigitalGood < ApplicationRecord
  has_one :product, as: :purchasable, touch: true
end

class PhysicalGood < ApplicationRecord
  has_one :product, as: :purchasable, touch: true
end

class BugTest < Minitest::Test
  def setup
    Product.destroy_all
    PhysicalGood.destroy_all
    DigitalGood.destroy_all
  end

  def test_delegated_type_update
    Product.create({ name: 'CD', purchasable_type: 'PhysicalGood', purchasable_attributes: { weight: 0.1 } })
    Product.create({ name: 'Video', purchasable_type: 'DigitalGood', purchasable_attributes: { drm_free: true } })

    Product.last.purchasable.update({ drm_free: false })

    assert_equal 2, Product.count
    assert_equal 1, PhysicalGood.count
    assert_equal 1, DigitalGood.count
  end

  def test_delegated_type_update_with_purchasable_attributes
    Product.create({ name: 'CD', purchasable_type: 'PhysicalGood', purchasable_attributes: { weight: 0.1 } })
    Product.create({ name: 'Video', purchasable_type: 'DigitalGood', purchasable_attributes: { drm_free: true } })

    Product.last.update({ purchasable_attributes: { drm_free: false } })

    assert_equal 2, Product.count
    assert_equal 1, PhysicalGood.count
    assert_equal 1, DigitalGood.count #a child gets orphaned here.
  end
end

```

### Expected behavior
In the same way we created records using the parent class, we expected to be able to update the associated child delegate type record as well. 
i.e. both of our test examples should be passing.

### Actual behavior
When the delegate_type attributes (e.g. `purchasable_attributes`) are used in the update call, a new child delegate type record will be created and the parent will update its foreign key reference to the new child. This leaves an orphaned record in the child table.
i.e. as a result, our `test_delegated_type_update_with_purchasable_attributes` test fails because the number of child records (namely `DigitalGood`) has changed.

### System configuration
**Rails version**: Rails 7.1.3.2

**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin22]

**Comment by Jay0921** [comment]
@SteveKhuu I got this error when I ran the test. 
```
Failure:
BugTest#test_delegated_type_update_with_purchasable_attributes [51170.rb:81]:
Expected: 1
  Actual: 2
```
`Product.last.update({ purchasable_attributes: { drm_free: false } })` essentially creates a new record instead of updating the existing one.

**Comment by rubyrider** [comment]
What about passing an id of existing purchasable object?

**Comment by SteveKhuu** [comment]
> @SteveKhuu I got this error when I ran the test.
> 
> ```
> Failure:
> BugTest#test_delegated_type_update_with_purchasable_attributes [51170.rb:81]:
> Expected: 1
>   Actual: 2
> ```
> 
> `Product.last.update({ purchasable_attributes: { drm_free: false } })` essentially creates a new record instead of updating the existing one.

Yes, that's exactly the bug here. It's an update call and should be updating records. 
Instead, the update call is creating a new record in addition to updating `Product`

**Comment by joshuay03** [comment]
I don't think this is a delegated types issue but is the default behaviour of `accepts_nested_attributes_for` with a one-to-one. Have a look at the `:update_only` option [in the docs](https://edgeapi.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html).

Setting `accepts_nested_attributes_for :purchasable` in your script passes both tests.

**Comment by SteveKhuu** [comment]
> I don't think this is a delegated types issue but is the default behaviour of `accepts_nested_attributes_for` with a one-to-one. Have a look at the `:update_only` option [in the docs](https://edgeapi.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html).
> 
> Setting `accepts_nested_attributes_for :purchasable, update_only: true` in your script passes both tests.

Ahhh missed that. `update_only: true` is the solution here. Thank you @joshuay03 !
