### ISSUE TITLE
bundle install fails on Edge: mysql2 gem incompatible with MySQL@8.3

### ISSUE THREAD

**Issue by JordanForeman** [rails/rails#51199]
### Steps to reproduce

1. Clone a fresh copy of Rails

```sh
git clone git@github.com:rails/rails.git
```

2. Install MySQL >=8.3

```sh
brew install mysql # at this time, installs 8.3.0
```

3. (Attempt to) Install dependencies

```sh
cd rails
bundle install
```

4. Note the errors, specifically:

```sh
client.c:1438:3: error: call to undeclared function 'mysql_ssl_set'; ISO C99 and later do not support implicit function declarations
[-Wimplicit-function-declaration]
  mysql_ssl_set(wrapper->client,
  ^
```

### Expected behavior

`bundle install` succeeds unceremoniously

### Actual behavior

Bundler fails to install `mysql2` with the following error:

```sh
client.c:1438:3: error: call to undeclared function 'mysql_ssl_set'; ISO C99 and later do not support implicit function declarations
[-Wimplicit-function-declaration]
  mysql_ssl_set(wrapper->client,
  ^
```

### Additional Information

I don't think this is specific to my system (although specs are listed below). My understanding of the issue (after poking around the interwebs the last couple evenings) stems from the fact that MySQL@8.3 removes a few APIs that the `mysql2` gem relied upon. This is fixed in the next patch release of `brianmario/mysql2` ([v0.5.6](https://github.com/brianmario/mysql2/releases/tag/0.5.6)). Simply upgrading this gem locally allows `bundle install` to pass as expected, although I'm not familiar enough with the Rails project to properly triage any potential side-effects.

### System configuration

**Rails version**: Edge

**Ruby version**: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-darwin22]

#### System specs (if it helps):

Mac OSX 12.6.3 (22G436)
**CPU:** 2.8 GHz Quad-Core Intel Core i7
**GPU:** Intel HD Graphics 630 1536MB
**RAM:** 16 GB 2133 MHz LPDDR3

**Comment by rubylevelup** [comment]
this seems to be related to mysql2 but not to rails?

**Comment by eileencodes** [comment]
This was fixed in https://github.com/brianmario/mysql2/pull/1352 and https://github.com/brianmario/mysql2/pull/1353. You need to upgrade your mysql2 version to 0.5.6. We likely don't want force Rails to use that version by default (at least yet) because you may not be using mysql 8.0. In the future, please report C level bugs for mysql2 to https://github.com/brianmario/mysql2

**Comment by JordanForeman** [comment]
Thanks @eileencodes! I was able to find those fixes applied in the `mysql2` gem. My problem seems to be with my mental model for dependencies and how they're managed in the Ruby ecosystem (apologies for that, I'm still learning the language basics). Per @yahonda's comment on #51200, installing the correct version of the `mysql2` gem at the _system_-level solves this problem without forcing anything on Rails. Apologies for the noise!
