### ISSUE TITLE
trilogy: will trilogy support prepared statement

### ISSUE THREAD

**Issue by xuan-cao-swi** [rails/rails#51216]
For [pg](https://github.com/rails/rails/blob/v7.1.3.2/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L911) and [mysql2](https://github.com/rails/rails/blob/v7.1.3.2/activerecord/lib/active_record/connection_adapters/mysql2/database_statements.rb#L123) adapter, both of them support prepare and execute, so I am wondering if trilogy will support prepare statement in the future (or PR welcomed?)

**Comment by skipkayhil** [comment]
There's an open issue on the trilogy repo: https://github.com/trilogy-libraries/trilogy/issues/105
