### ISSUE TITLE
where.first_or_create! fails with encrypted attribute fails

### ISSUE THREAD

**Issue by liaden** [rails/rails#51224]
### Steps to reproduce

1. On Rails 7, I am taking an existing application with a plaintext column and encrypting it.
2. We added the line: `encrypts :name, deterministic: true`.
3. Test code runs `Thing.where(name: 'test').first_or_create(attr1: 'foo', attr2: 'bar')`
4. See error `Validation failed: Name can't be blank`

```ruby
class Thing
  validates :name, presence: true, uniqueness: true
  encrypts :name, deterministic: true
end
```

```ruby
    # config/application.rb
    config.active_record.encryption.store_key_references = true
    config.active_record.encryption.extend_queries = true
    config.active_record.encryption.support_unencrypted_data = true
```

### Expected behavior
The `thing` is created successfully.

### Actual behavior
Validation error

### System configuration
**Rails version**: 7.0.8.1

**Ruby version**: 3.1.3

**Comment by samsamkim** [comment]
Hi @liaden , I could not replicate the bug - could I ask what the exact validation error was, please? Thanks!

**Comment by zzak** [comment]
Please provide a reproducible test if possible:
https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case
