### ISSUE TITLE
Postgres JSONB column default and virtual column expressions are not typecasted on save

### ISSUE THREAD

**Issue by agrobbin** [rails/rails#51233]
### Steps to reproduce

When leveraging the JSONB column type in PG, sometimes you want to have an expression as the default value of a column, and other times want to have a virtual / generated column value itself be JSONB that is computed from another column.

It's expected that the initial values on new record creation are `nil`, however, it appears that Active Record is not properly typecasting those values _after_ saving a record. Here is a minimal test case (somewhat contrived, but hopefully it clearly explains the issue):

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "jsonb_default_values_bug_test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.jsonb :event
    t.jsonb :default_metadata, null: false, default: -> { "jsonb_build_object('now', now())" }
    t.virtual :foo, type: :jsonb, as: "event -> 'foo'", stored: true
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_default_value_typecasting
    post = Post.new

    assert_nil post.default_metadata

    post.save!

    assert_instance_of Hash, post.default_metadata
    assert_equal %w[now], post.default_metadata.keys
  end

  def test_virtual_column_value_typecasting
    post = Post.new(event: { foo: { bar: 'baz' } })

    assert_nil post.foo

    post.save!

    assert_instance_of Hash, post.foo
    assert_equal %w[bar], post.foo.keys
  end
end
```

### Expected behavior

It is expected that both of these tests would pass, with both `post.default_metadata` and `post.foo` returning a Ruby Hash of the JSON post-`save!`.

### Actual behavior

Both `post.default_metadata` and `post.foo` return strings of serialized JSON rather than a Ruby Hash. Adding a `post.reload` after `post.save!` fixes the issue, but that shouldn't be required to receive the typecasted values.

I'd be happy to help fix this if someone could provide a little guidance on where to look!

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.3.0

**Comment by wesharper** [comment]
This seems to be the same as: https://github.com/rails/rails/issues/48423

**Comment by agrobbin** [comment]
@wesharper yeah, it definitely looks closely related! I'll leave it to the core team to decide what to do.

**Comment by abaldwin88** [comment]
This is related to but not a duplicate of #48423. It's a separate issue. This deserialization issue will happen on either create or update when a JSONB column is included in a RETURNING statement.

I have a couple potential fixes for consideration. I'll turn this into a PR soon.  https://github.com/rails/rails/compare/main...abaldwin88:rails:fix_returning_jsonb_deserialize
