### ISSUE TITLE
Unintended Fallback to `Rails::HTML4::Sanitizer` for `ActionView::Helpers::SanitizeHelper.sanitizer_vendor` without `sprockets-rails`

### ISSUE THREAD

**Issue by yuemori** [rails/rails#51246]
### Steps to reproduce

Starting from Rails 7.1, the Action View HTML sanitizer can be customized through the `config.action_view.sanitizer_vendor` setting, with supported values being `Rails::HTML4::Sanitizer` or `Rails::HTML5::Sanitizer`, and the default being `Rails::HTML5::Sanitizer`. The current implementation checks for the `Rails::HTML::Sanitizer` constant defined:

https://github.com/rails/rails/blob/db30dd6fe71341ac132bb1e850bd4df2596a2803/railties/lib/rails/application/configuration.rb#L313-L321

However, the `Rails::HTML` constant is not defined unless rails-html-sanitizer is explicitly required, which is not the case by default in Rails. This setup does not usually cause issues because sprockets-rails requires rails-html-sanitizer.

passed test (depends `sprockets-rails` ):

```ruby
require "bundler/inline"

gemfile(true, quiet: true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 7.1"
  gem "sprockets-rails"
end

require "action_controller/railtie"
require "action_view/railtie"
require "minitest/autorun"

class TestApp < Rails::Application
  config.load_defaults 7.1
  config.eager_load = true
end

# avoid Sprockets::Railtie::ManifestNeededError
FileUtils.mkdir_p "#{__dir__}/app/assets/config"
FileUtils.touch "#{__dir__}/app/assets/config/manifest.js"

TestApp.initialize!

class BugTest < Minitest::Test
  def test_sanitizer_vendor
    assert_equal ActionView::Helpers::SanitizeHelper.sanitizer_vendor, Rails::HTML5::Sanitizer
  end
end
```

failure test:

```ruby
require "bundler/inline"

gemfile(true, quiet: true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 7.1"
end

require "action_controller/railtie"
require "action_view/railtie"
require "minitest/autorun"

class TestApp < Rails::Application
  config.load_defaults 7.1
  config.eager_load = true
end

TestApp.initialize!

class BugTest < Minitest::Test
  def test_sanitizer_vendor
    assert_equal ActionView::Helpers::SanitizeHelper.sanitizer_vendor, Rails::HTML5::Sanitizer
  end
end
```

Result:

```
# Running:

F

Failure:
BugTest#test_sanitizer_vendor [test1.rb:29]:
Expected: Rails::HTML4::Sanitizer
  Actual: Rails::HTML5::Sanitizer
```

### Expected behavior

Regardless of whether sprockets-rails is being used, the default value of `ActionView::Helpers::SanitizeHelper.sanitizer_vendor` should be `Rails::HTML5::Sanitizer` . Additionally, it should not result in an error in `new_framework_defaults_7_1.rb` .

### Actual behavior

1. Upgrading from Rails 7.0 to 7.1: If `sprockets-rails` is removed and replaced with `propshaft`, the code in `new_framework_defaults_7_1.rb` raises `uninitialized constant Rails::HTML` exception since `rails-html-sanitizer` is not required by default:

https://github.com/rails/rails/blob/v7.1.3.2/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults_7_1.rb.tt#L254

2. Rails 7.1 without sprockets-rails: Opting for `propshaft` over `sprockets-rails` sets the `sanitizer_vendor` to `Rails::HTML4::Sanitizer`, contrary to the behavior documented in the Rails Upgrade guide.

### System configuration

**Rails version**: 7.1.3

**Ruby version**: 3.0.3

**Comment by yuemori** [comment]
To check which sanitizer your application is using, you can run `rails runner "puts ActionView::Helpers::SanitizeHelper.sanitizer_vendor"` . If `Rails::HTML5::Sanitizer` is returned, then a fallback has not occurred.

As a workaround for this issue, you can add code to `require "rails-html-sanitizer"` in `config/application.rb` or a similar file. However, it's unconfirmed whether this has any other impacts or not.

```ruby
# config/application.rb
require_relative "boot"

require "rails/all"
require "rails-html-sanitizer" # Add this line to require rails-html-sanitizer
```

**Comment by flavorjones** [comment]
Thank you for reporting this. I'll take a look.

**Comment by flavorjones** [comment]
PR proposed at #51267

**Comment by yuemori** [comment]
Thank you for quick response and proposal!
