### ISSUE TITLE
QueryAttributes treated as strings in exec_query

### ISSUE THREAD

**Issue by LukeClancy** [rails/rails#51250]
### Steps to reproduce

I have a library [dynamic_records](https://github.com/LukeClancy/dynamic-records-meritfront) that uses exec_query alongside QueryAttributes to write sql. Recently I updated rails, pg and psql to a recent version and found that exec_query no longer works as expected.

exec_query seems to be converting all parameters into strings. I do not believe this is expected functionality.

```ruby
value = 1
type = ActiveRecord::Type::Integer.new
qa = ActiveRecord::Relation::QueryAttribute.new('int_input', value, type)
x = ActiveRecord::Base.connection.exec_query("select $1", 'query name', [qa])
out_v = x.rows.first.first

puts "value: #{out_v.inspect}, class: #{out_v.class.to_s}"
```

### Expected behavior
"value: 1, class: Integer"

### Actual behavior
"value \"1\", class: String"

### System configuration
ruby 3.2.2p53
rails (7.1.3.2)
activemodel (= 7.1.3.2)
activerecord (= 7.1.3.2)
pg (1.5.6)

psql (PostgreSQL) 16.2 (Ubuntu 16.2-1.pgdg22.04+1)

**Comment by nvasilevski** [comment]
The tricky part here is that `QueryAttribute` seems to be `# :nodoc:` which most likely it was supposed to be private. So it may be hard to justify any changes as long as all of the public APIs that use `QueryAttribute` work as expected

Any chance that we could come up with a reproduction using public APIs to reveal the issue? That would help tremendously to argue that this is indeed a bug

**Comment by LukeClancy** [comment]
I have reproduced the issue using find_by_sql. To my knowledge find_by_sql used to pass types to the database, but now seems to leave it for the database to "deduce" them from context.

```
#convert an integer to a string
irb(main):006> User.find_by_sql("select $1 as x", [1])
  User Load (0.8ms)  select $1 as x  [[nil, 1]]
=> [#<User x: "1", id: nil>]

#pass the id as a string in a where statement (gets deduced as integer)
irb(main):008> User.find_by_sql("select id from users where users.id = $1", ["1"])
  User Load (2.2ms)  select id from users where users.id = $1  [[nil, "1"]]
=> [#<User id: 1>]

#confuse the database by having it deduce string and integer from input. Raises  PG::AmbiguousParameter
irb(main):009> User.find_by_sql("select id, $1 as r from users where users.id = $1", ["1"])
  User Load (0.8ms)  select id, $1 as r from users where users.id = $1  [[nil, "1"]]
/home/luke/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params': PG::AmbiguousParameter: ERROR:  inconsistent types deduced for parameter $1 (ActiveRecord::StatementInvalid)
LINE 1: select id, $1 as r from users where users.id = $1
                   ^
DETAIL:  bigint versus text
```

This could lead to many hard to find / track down bugs.

**Comment by LukeClancy** [comment]
This example makes it clear that data types are not making it to the database at all

**Comment by rafaelfranca** [comment]
I don't think it even did. Can you provide a reproduction script with this template https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb that pass in any version of Rails without using private API?

**Comment by LukeClancy** [comment]
[I created a gist for it](https://gist.github.com/LukeClancy/682fef41659f16790979a95e37555879). I tried on sqlite3, but it seemed to have different issues. For example Post.find_by_sql('select * from posts where id = ?', ["3 bla bla bla"]) did not throw an error (despite the id column being integers). I do not know enough about sqlite to call this an error... but, seems iffy?
