### ISSUE TITLE
Configuration of config.i18n.fallbacks is not working

### ISSUE THREAD

**Issue by nflorentin** [rails/rails#51253]
Hi,

I noticed that configuring `i18n.fallbacks` as [explained in rails guides](https://guides.rubyonrails.org/configuring.html#config-i18n-fallbacks) lead to a silent not working configuration. 

Tested on `rails 7.1` with last version (1.14.1) of `i18n` gem.

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "~> 7.1"
  gem "i18n", "1.14.1"
end

require "active_support/railtie"
require "minitest/autorun"

class TestApp < Rails::Application
  config.load_defaults 7.1

  config.eager_load = false

  config.i18n.default_locale = :en
  config.i18n.available_locales = [:'en-GB', :'en-UK', :'en-US', :en]

  config.i18n.fallbacks = { :'en-GB' => [:en], :'en-UK' => [:en], :'en-US' => [:en] }

  # not working either
  # config.i18n.fallbacks = [:'en-US', :en]
  # config.i18n.fallbacks.map = { :'en-GB' => [:en], :'en-UK' => [:en], :'en-US' => [:en] }

  # makes the test pass
  # I18n.fallbacks = { :'en-GB' => [:en], :'en-UK' => [:en], :'en-US' => [:en], :en => [:en] }
end

Rails.application.initialize!

class I18nFallbacksTest < ActiveSupport::TestCase
  test "fallbacks" do
    assert_not_empty I18n.fallbacks
  end
end
```

### Expected behavior
- The configuration should be reflected in `I18n.fallbacks`
- The fallbacks should work as expected.
- If syntax is not valid anymore, an error should be raised

### Actual behavior
- I18n.fallbacks is empty, so fallbacks are not working
- There is no error raised

### Comments

I'm not sure if the problem is from rails or i18n side but [a similar issue](https://github.com/ruby-i18n/i18n/issues/645) on i18n repo was open one year ago and was set as completed but the bug is apparently stills present.

### System configuration
**Rails version**: 7.1.3
**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
It works as expected, the problem is that output from `i18n` is a bit confusing - https://github.com/ruby-i18n/i18n/pull/683.

**Comment by nflorentin** [comment]
Thank a lot @fatkodima !

It's now crystal clear 👍
