### ISSUE TITLE
add a better interface to the issues tab on this repo

### ISSUE THREAD

**Issue by quantummarc** [rails/rails#51278]
![Screenshot 2024-03-07 at 16 56 02](https://github.com/rails/rails/assets/78028419/184a2221-2f7c-4de5-87d1-b82bf189406a)
a page like this with url "/issues/new/choose"

so new features/ideas can be suggested etc

**Comment by fatkodima** [comment]
New features should be suggested via a rails forum (https://discuss.rubyonrails.org) or a discord server. "Issues" tab is reserved for issues/bugs in the framework only.
