### ISSUE TITLE
Using preload with composite keys can cause too many records to be read

### ISSUE THREAD

**Issue by tomhughes** [rails/rails#51290]
### Steps to reproduce

Using `preload` with composite keys can cause more records to be read than are required - consider this test case:

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "activerecord", "7.1.3.2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :nodes, primary_key: [:node_id, :node_version] do |t|
    t.integer :node_id
    t.integer :node_version
  end

  create_table :node_tags, primary_key: [:node_id, :node_version, :k], force: true do |t|
    t.integer :node_id
    t.integer :node_version
    t.text :k
  end
end

class Node < ActiveRecord::Base
  has_many :tags, class_name: "NodeTag", query_constraints: [:node_id, :node_version], :inverse_of => :node
end

class NodeTag < ActiveRecord::Base
  belongs_to :node, query_constraints: [:node_id, :node_version], :inverse_of => :tags
end

class BugTest < Minitest::Test
  def test_preload
    node = Node.create(id: [1, 1])
    node.tags.create(k: "a")
    node.tags.create(k: "b")
    node = Node.create(id: [1, 2])
    node.tags.create(k: "c")
    node.tags.create(k: "d")
    node = Node.create(id: [2, 1])
    node.tags.create(k: "e")
    node.tags.create(k: "f")

    nodes = Node.preload(:tags)
              .where(node_id: 1, node_version: 2)
              .or(Node.where(node_id: 2, node_version: 1))
              .order(:node_id, :node_version)

    assert_equal 2, nodes.size

    nodes.each do |node|
      assert_equal 2, node.tags.size
    end
  end
end
```

The assertions pass, but if you look at the logged SQL for the preload you see this:

```sql
SELECT "node_tags".*
FROM "node_tags"
WHERE "node_tags"."node_id" IN (?, ?) AND "node_tags"."node_version" IN (?, ?)
```

where the bound ID values are 1 and 2 as are the bound version values.

So not only will that read the tags for `[1, 2]` and `[2, 1]` as expected but it will also read the tags for `[1, 1]` which are not needed.

Those records don't appear to get attached to any node so are presumably being discarded when the preload is matched to the original records.

### Expected behavior

The required records are preloaded.

### Actual behavior

Extra records are preloaded.

### System configuration

**Rails version**: 7.1.3.2
**Ruby version**: 3.2.2

**Comment by nvasilevski** [comment]
A bit of context: https://github.com/rails/rails/pull/48947#issuecomment-1681439294

This worst case was anticipated but a decision was made to go with `IN` statement since it doesn't break the public API of  and most likely will benefit most commonly used schema designs. 

>presumably being discarded when the preload is matched to the original records.

yep

The solution would either be to get back to `OR` statements or build a row constructor statements `(node_id, node_version) IN ((1,2), (2, 1))` but maybe a solution that would satisfy everyone would be for Rails to allow the behavior to be configured so applications can choose what works best for them depending on db schemas and databases they use

**Comment by AntonKhorev** [comment]
https://github.com/rails/rails/pull/48947#issuecomment-1681439294

> Having said that, I still think that we will be making a reasonable tradeoff by choosing the IN statements version of the query over the OR statements since the reproduction script I'm using may not necessarily represent a schema design from a real-world application while a setup where composite primary key or query_constraints has a shape of <tenant_key>, <unique_identifier> represents a real-world applications which will not be impacted by the issue described in my comment and will only benefit from the proposed improvement.

If your composite key has a unique_identifier as its part, why do you need a composite key?

**Comment by nvasilevski** [comment]
>why do you need a composite key?

to change the way mysql stores data on the disk 
https://shopify.engineering/how-to-introduce-composite-primary-keys-in-rails

**Comment by AntonKhorev** [comment]
Rails 8.0.2.1, still the same `WHERE "node_tags"."node_id" IN (?, ?) AND "node_tags"."node_version" IN (?, ?)`.
