### ISSUE TITLE
Add .default method to ActiveSupport::ParameterFilter (syntax sugar)

### ISSUE THREAD

**Issue by wowinter13** [rails/rails#51300]
Hello there, Rails team👋

I had a thought about adding a new `.default` method to `ActiveSupport::ParameterFilter`.
The idea is to make it **_slightly_** easier to create a `ParameterFilter` instance using the app's default filter params.
 
In a lot of bigger Rails projects, I saw devs often use custom loggers -> need to filter sensitive params before logging. Right now, we usually end up writing something like this:

```ruby

def filtered_params
  @filter ||= ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
  @filter.filter(params.to_h)
end
```

What if we added a `.default` method to `ParameterFilter`? Something like:

```ruby
module ActiveSupport
  class ParameterFilter
    def self.default
      @default ||= new(Rails.application.config.filter_parameters)
    end
  end
end
```

Because in 99 out of 100 cases, we end up using the default `Rails.application.config.filter_parameters` anyway.

Anyway, just an idea! But if you think it could be useful, feel free to assign this one to me

**Comment by akhilgkrishnan** [comment]
Hi @wowinter13 ,
Thanks for sharing this idea. Github issue is mainly used for tracking bugs. So you can move this to [Rails Discussion](https://discuss.rubyonrails.org/c/rubyonrails-core/5).

Ref: https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark

**Comment by wowinter13** [comment]
@akhilgkrishnan sure, thanks! Sorry, for some reason I totally forgot about [Rails Discussion](https://discuss.rubyonrails.org/c/rubyonrails-core/5)
