### ISSUE TITLE
RedisCacheStore not fault tolerant (as I expected)

### ISSUE THREAD

**Issue by JerrodCarpenter** [rails/rails#51302]
### Steps to reproduce
I've been around long enough to know I'm probably doing something wrong here with my configuration and I know I'm likely in the wrong place, but I'm not sure where to pose these types of questions. Based on the [RedisCacheStore documentation](https://api.rubyonrails.org/classes/ActiveSupport/Cache/RedisCacheStore.html), I understand that the connection is:

> Fault tolerant. If the Redis server is unavailable, no exceptions are raised. [Cache](https://api.rubyonrails.org/classes/ActiveSupport/Cache.html) fetches are all misses and writes are dropped.

This is great, this is exactly what I want, and you can see this is the case when working locally by turning off your local development redis.:

```ruby
✗ brew services stop redis 
Stopping `redis`... (might take a while)
==> Successfully stopped `redis` (label: homebrew.mxcl.redis)
✗ ./bin/rails c
Loading development environment (Rails 7.1.3.1)
[1] pry(main)> Rails.cache.fetch "test"
=> nil
```

Our rails cache configuration for production:
```ruby
  config.cache_store = :redis_cache_store, {
    url: ENV.fetch("REDIS_CACHE_URL"),
    read_timeout: 1,
    pool: { timeout: 5, size: 10 },
    custom: { datadog: { service_name: "api-redis-cache-primary" } },
  }
```

I'm not quite sure how to cause this error to happen.

### Expected behavior
I'm expecting this to be true for all errors.

### Actual behavior
I'm seeing `Redis::CannotConnectError` (see example below).

<img width="1266" alt="Screenshot 2024-03-11 at 9 49 13 PM" src="https://github.com/rails/rails/assets/4128301/12e3c917-85f6-437d-a512-7e3e177dd444">

### System configuration
**Rails version**: 7.1.3.1

**Ruby version**: 3.3.0

**Comment by JerrodCarpenter** [comment]
[Here](https://github.com/rails/rails/blob/4d3e2910c680baad7c14d2797a53a6b72405149b/activesupport/lib/active_support/cache/redis_cache_store.rb#L483) I see `failsafe`s method definition for the `RedisCacheStore`. To be fair I haven't done the work to see if this error that it's rescuing is inclusive of what I'm experiencing.

**Comment by skipkayhil** [comment]
Are you only seeing that error in Datadog? That makes me think its coming from the `error_reporter.call` inside the `rescue` block of the failsafe which I think is expected.

**Comment by JerrodCarpenter** [comment]
> Are you only seeing that error in Datadog? That makes me think its coming from the `error_reporter.call` inside the `rescue` block of the failsafe which I think is expected.

Yep, that is indeed the case.

**Comment by JerrodCarpenter** [comment]
One thing that's confusing me is I see this when opening a rails console session:

```ruby
> def test
*   res = Rails.cache.fetch("key", expires_in: 1.minute, skip_nil: true) do  
*     raise ::Redis::CannotConnectError    
*   end    
*   puts "yep"  
*   res  
* rescue Redis::BaseError  
*   puts "nope"  
*   res  
* end  
=> :test
> test
nope
=> nil
```

Shouldn't "yep" print here because the error is rescued in the rails cache fetch block?

**Comment by skipkayhil** [comment]
The `fetch` block itself isn't rescued, only reading/writing values to the cache.
