### ISSUE TITLE
Doc have typo?

### ISSUE THREAD

**Issue by 1c7** [rails/rails#51305]
https://guides.rubyonrails.org/layouts_and_rendering.html#the-formats-option

<img width="891" alt="image" src="https://github.com/rails/rails/assets/1804755/40d5c68d-097d-41b2-8f63-dd331b21802f">

**Comment by skipkayhil** [comment]
The expected path of the asset would be `app/assets/javascripts/main.js`, `lib/assets/javascripts/main.js`, or `vendor/assets/javascripts/main.js`. I agree that not indicating the name of the file in that section is a bit confusing.

Would you be interested in opening a PR to improve this?

**Comment by 1c7** [comment]
I can't open PR right now, my shoulder hurts, I have to visit doctor tomorrow,
maybe 3-4 days later I could come back and open PR.

**Comment by debashiscodes** [comment]
@skipkayhil I will raise a PR for this, and I am working on it.
