### ISSUE TITLE
`ActiveRecord::Migration::check_all_pending!` resets connection pool when in use in other threads

### ISSUE THREAD

**Issue by joshuay03** [rails/rails#51319]
This might not be a bug per se, but is unexpected behaviour that was exposed in our specific use case.

### Steps to reproduce

In production, we have a bunch of custom internal health-checks exposed via a controller endpoint that are pinged every 20s or so, one of which is a check for pending migrations. Up until recently we were using `ActiveRecord::Migration::check_pending!` which took an optional connection argument and would use it to access the migration context (presumably releasing the connection back into the pool immediately after) to check for pending migrations.

This method [has been deprecated in favour of `check_all_pending!`](https://github.com/rails/rails/commit/03379d1f599653d100dff9fbf3ce4434a930b915) and [was recently removed on `main`](https://github.com/rails/rails/commit/02f66fe3e25cef2b0dec8bca26e777fe788af35c). To comply with this (since we run against Rails edge) we ended up replacing `check_pending!` with `check_all_pending!` (which doesn't take any arguments) in the respective health-check. After deploying this change we started seeing this error intermittently:

```
ActiveRecord::ConnectionNotEstablished:  No connection pool for 'ActiveRecord::Base' found.
```

After some debugging we found that it was due to `check_all_pending!` [using a temporary pool under the hood](https://github.com/rails/rails/blob/0dc84e2e7d942dcaac3bd75414ae55bfad9bb18a/activerecord/lib/active_record/tasks/database_tasks.rb#L542-L549), meaning it would establish a new connection for its checks, then establish another one once done, resetting the connection pool object each time. This meant that other threads (we're currently running `puma` with `3` threads) that attempted to retrieve the current (cached) pool during this time (to then retrieve a connection) would fail to find it and raise here:
https://github.com/rails/rails/blob/0dc84e2e7d942dcaac3bd75414ae55bfad9bb18a/activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb#L224

We've considered that maybe this specific health-check setup is a bit unconventional, but given that I can find [some public repos utilising this method the same way](https://github.com/search?q=ActiveRecord%3A%3AMigration.check_all_pending%21+language%3ARuby&type=code&l=Ruby), I thought I'd open this up for discussion to see if there's any chance of changing / extending the implementation or even just warning against its use outside of something like a rake task so others don't run into a similar issue.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# Ensure `ActiveRecord::Base.configurations.configs_for` returns a config for which a temporary pool is yielded.
ActiveRecord::Base.configurations = { development: { adapter: "sqlite3", database: ":memory:" } }
# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

class BugTest < Minitest::Test
  def test_connection_pool_does_not_reset
    pool_before = ActiveRecord::Base.connection_pool

    ActiveRecord::Migration.check_all_pending!

    assert_equal pool_before.object_id, ActiveRecord::Base.connection_pool.object_id
  end
end
```

### Expected behavior

Connection pool is not reset when checking for pending migrations with `check_all_pending!`.

### Actual behavior

Connection pool is reset when checking for pending migrations with `check_all_pending!`.

### System configuration
**Rails version**: Edge

**Ruby version**: 3.2.2

**Comment by eileencodes** [comment]
I'm not sure what to do here, we need to establish connections to be able to use this for multiple databases. I introduced the temporary connection because there's a future world where we don't clobber `Base` connections, although we're not there yet. Even if we got rid of the temporary pool, the problem would still exist in order to use this for multiple databases. I guess we could reintroduce check pending on just the default Base connection, but that feels confusing.

I'm curious though, why is check pending migrations part of health checks in production? This feels like the wrong mechanism for making sure migrations were run on all the database servers.

**Comment by joshuay03** [comment]
Closing since there hasn't been any activity for a while.

It seems like there's no way around this behaviour. Also, https://github.com/rails/rails/commit/02f66fe3e25cef2b0dec8bca26e777fe788af35c has already been included in the 7.2 beta.

**Comment by szechyjs** [comment]
This is breaking our health checks, would be nice to get it fixed.

**Comment by ghiculescu** [comment]
Yeah, we ended up removing the pending migrations healthcheck. Turns out we didn't really need it.

**Comment by camallen** [comment]
> Is this still a problem in 7.2. I'm on 7.1.4 and it's a problem..
> We have this check run as part of the middleware, so each call to the app is creating temp connections.
> Oddly only crashes on dev (right now)

Yeah this is still a problem on rails edge, it should only impact multi threaded servers though. 

Also with a multi database setup the temporary pool can clobber the `ActiveRecord::Base` connection to be a different database which may not have the same schema. For us this was erroring with concurrent requests hitting the jobs db via the `ActiveRecord::Base` model connection pool that `ApplicationRecord` also uses.

You can look at the [active_record.migration_error](https://guides.rubyonrails.org/configuring.html) configuration which adds a middleware. 

Our current solution is to move these to the rails task / rails runner script pre boot.
