### ISSUE TITLE
migrate `migrate` folder to `migrations`

### ISSUE THREAD

**Issue by pynixwang** [rails/rails#51320]
### Steps to reproduce
`gem install rails && rails new -d postgresql --api demo`

### Expected behavior
db/migrations

### Actual behavior
db/migrate
migrate is a verb.

### System configuration
**Rails version**:
rails 1.0 - rails 7.0
**Ruby version**:
latest

this will fix the long lived bug from rails 1.0

**Comment by eileencodes** [comment]
Hi @pynixwang, this isn't a bug, the naming is intentional. We're not going to change it at this point, it would result in unnecessary churn in Rails applications for something that ultimately isn't user facing or a real problem.

**Comment by pynixwang** [comment]
@etiennebarrie yes, I know I can configure it, but maybe I want to make it default.
