### ISSUE TITLE
Using a secret_key_base from `secrets.yml` should raise a deprecation warning in development

### ISSUE THREAD

**Issue by niklas-hasselmeyer** [rails/rails#51322]
### Steps to reproduce
- In a new rails project, delete `credentials.yml.enc` and `tmp/local_secret.txt`
- Set `config.active_support.deprecation = :raise` in `config/environments/development.rb`
- Create a `config/secrets.yml` with the following content:
  ```
  development:
    secret_key_base: abcdef123456
  ```
- In the console:
  ```
  > Rails.application.secret_key_base
  => "abcdef123456"
  ```

### Expected behavior
This should raise a deprecation warning, because the `secrets.yml` file will be removed in 7.2

### Actual behavior
No deprecation warning is raised.

### Additional info
This does raise a warning in production (`railties/lib/rails/application.rb:489`), but for local environments, there isn't a warning.

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.2.2

**Comment by fatkodima** [comment]
Confirmed. We just encountered the same issue. Will try to provide a fix.
