### ISSUE TITLE
Javascript not setup with new rails app

### ISSUE THREAD

**Issue by andrianarivo** [rails/rails#51344]
### Steps to reproduce

- Create a new rails app
- Bundle failed because of postgres dependency with `libpq` (has to be installed manually)
- Bundle succeeds but javascript not setup with the app

```ruby
# Your reproduction script goes here
mkdir project-name
rails new -c tailwind -d postgresql .
```

### Expected behavior

Creates a new app and it works out of the box with importmaps

### Actual behavior

Need to setup Javascript:
```sh
rails importmap:install
rails stimulus:install
rails turbo:install
```

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.2.3 (2024-01-18 revision 52bb2ac0a6) [arm64-darwin23]

**Comment by rafaelfranca** [comment]
Thank you for the issue. When one of the steps failed, Rails can't continue doing what it needs to do, so it is expected JavaScript wasn't setup when `bundler install` failed. You should try to generate the application again if you want it to finish successfully.

**Comment by andrianarivo** [comment]
@rafaelfranca , thank you for the clarifications. For those who encounter the same issue, if using Tailwind + importmaps you'll need to configure it as well. [Docs](https://tailwindcss.com/docs/guides/ruby-on-rails)
