### ISSUE TITLE
Object#with_options not work correctly together with ActiveRecord::Enum#enum

### ISSUE THREAD

**Issue by mktktmr** [rails/rails#51367]
### Steps to reproduce

`Code to reproduce`
```ruby
class User < ApplicationRecord
  # Case 1: working correctly 
  enum :category, { cate1: 1, cate2: 2 }, prefix: true, validate: true
  # Case 2: working incorrectly
  with_options prefix: true, validate: true do
    enum :role, { role1: 1, role2: 2 }
  end
end
```

`Result`
```ruby
# Case 1
From: /bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/enum.rb @ line 217 :

    212:       private
    213:         attr_reader :name, :mapping
    214:     end
    215:
    216:     def enum(name = nil, values = nil, **options)
 => 217:       binding.irb
    218:       if name
    219:         values, options = options, {} unless values
    220:         return _enum(name, values, **options)
    221:       end
    222:

irb(Notice):001> name
=> :category
irb(Notice):002> values
=> {:cate1=>1, :cate2=>2}
irb(Notice):003> options
=> {:prefix=>true, :validate=>true}

# Case 2
From: /bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/enum.rb @ line 217 :

    212:       private
    213:         attr_reader :name, :mapping
    214:     end
    215:
    216:     def enum(name = nil, values = nil, **options)
 => 217:       binding.irb
    218:       if name
    219:         values, options = options, {} unless values
    220:         return _enum(name, values, **options)
    221:       end
    222:

irb:rdbg(Notice):004> name
:role
irb:rdbg(Notice):005> values
nil
irb:rdbg(Notice):006> options
{:prefix=>true, :validate=>true, :role1=>1, :role2=>2} # ❗ values are treated as options
```

### Expected behavior
#enum` treats second argument as `values`.

### Actual behavior
`#enum` treats second argument as `options`.

### System configuration
**Rails version**: `7.1.3.2`

**Ruby version**: `3.2.0`

**Comment by fatkodima** [comment]
Yes, this is how it works - it merges two hashes together https://github.com/rails/rails/blob/30e37387249632cce382d7b7b7adc619855dc7d9/activesupport/lib/active_support/core_ext/object/with_options.rb#L55-L63

**Comment by 3v0k4** [comment]
The issue comes from [`ActiveSupport::OptionMerger#method_missing`](https://github.com/rails/rails/blob/30e37387249632cce382d7b7b7adc619855dc7d9/activesupport/lib/active_support/option_merger.rb#L21):

```ruby
      def method_missing(method, *arguments, &block)
        options = nil
        if arguments.size == 1 && arguments.first.is_a?(Proc)
          proc = arguments.shift
          arguments << lambda { |*args| @options.deep_merge(proc.call(*args)) }
        elsif arguments.last.respond_to?(:to_hash) # 👈
          options = @options.deep_merge(arguments.pop)
        else
          options = @options
        end

        if options
          @context.__send__(method, *arguments, **options, &block)
        else
          @context.__send__(method, *arguments, &block)
        end
      end
```

When the last argument is a hash, in this case `{ role1: 1, role2: 2 }`, it merges it with the options passed to `with_options` instead of leaving it to `enum`.

I guess you could add an empty hash at the end? It's not pretty, though:

```ruby
  with_options prefix: true, validate: true do
    enum :role, { role1: 1, role2: 2 }, {}
  end
```

**Comment by mktktmr** [comment]
> Yes, this is how it works - it merges two hashes together
> 
> https://github.com/rails/rails/blob/30e37387249632cce382d7b7b7adc619855dc7d9/activesupport/lib/active_support/core_ext/object/with_options.rb#L55-L63

@fatkodima 
Thank you for your reply. 
Do you mean this is not bug but the specification of `ActiveRecord::Enum#enum`, right?

**Comment by mktktmr** [comment]
@3v0k4 Thank you for your reply and sample code.
Your suggestion is work well 😄 
I will follow your suggestion, If this is not a bug.

**Comment by fatkodima** [comment]
> Do you mean this is not bug but the specification of `ActiveRecord::Enum#enum`, right?

That is not a bug, this is how `with_options` works and its unfortunate, that `enum` takes a hash as an argument.
