### ISSUE TITLE
unexpected routes add by the turbo rails gem

### ISSUE THREAD

**Issue by kristoph** [rails/rails#51360]
I am using rails 7.1.2

Anytime I include the turbo rails gem I see these routes which I do not want to have added:

turbo_recede_historical_location GET      /recede_historical_location(.:format)  turbo/native/navigation#recede
turbo_resume_historical_location GET      /resume_historical_location(.:format)  turbo/native/navigation#resume
turbo_refresh_historical_location GET      /refresh_historical_location(.:format) turbo/native/navigation#refresh

How can I remove these routes? Should these really be added as part of the turbo rails gem/

**Comment by nvasilevski** [comment]
Rails reserves github issues for bugs only. Please post questions on any other public forum

Technically Rails is not what adds these routes to your app so you should direct your question to someone who is knowledgable of the `turbo-rails` library

https://github.com/hotwired/turbo-rails/blob/102a491754d46f7dd924201fcfaf879a0f04b11c/config/routes.rb#L2

Perhaps you could set `Turbo.draw_routes` to `false` but I have very little knowledge in this area and not aware of any implications
