### ISSUE TITLE
(New to Rails) Can't start the server

### ISSUE THREAD

**Issue by kmafeni04** [rails/rails#51391]
### Steps to reproduce
ran rails new my_app

### Expected behavior
The app to be created

### Actual behavior
received these errors: ```
Writing lockfile to /home/kome/my_app/Gemfile.lock
         run  bundle binstubs bundler
       rails  importmap:install
<internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- json (LoadError)
        from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/json.rb:49:in `init!'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/json.rb:42:in `install!'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache.rb:34:in `setup'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap.rb:68:in `setup'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap.rb:112:in `default_setup'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/setup.rb:5:in `<top (required)>'
        from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /home/kome/my_app/config/boot.rb:4:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>'
       rails  turbo:install stimulus:install
<internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- json (LoadError)
        from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/json.rb:49:in `init!'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/json.rb:42:in `install!'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache.rb:34:in `setup'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap.rb:68:in `setup'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap.rb:112:in `default_setup'
        from /home/kome/.gem/ruby/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/setup.rb:5:in `<top (required)>'
        from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /home/kome/my_app/config/boot.rb:4:in `<top (required)>'
        from bin/rails:3:in `require_relative'
        from bin/rails:3:in `<main>' ```
### System configuration
**Rails version**:
Rails 7.1.3.2
**Ruby version**:
ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]  "Arch linux"

**Comment by JoeDupuis** [comment]
I don't think this is a Rails issue. It looks like Arch's Ruby 3.0.6 is excluding the json gem. 
Try installing the [`ruby-json` package ](https://archlinux.org/packages/extra/x86_64/ruby-json/).

**Comment by JoeDupuis** [comment]
Looking at the ruby package dependency (`ruby > ruby-stdlibs > ruby-json`), it looks like ruby-json should already be installed. Something might have gone wrong while installing the packages. I would reinstall all 3 (ruby, ruby-stdlibs, ruby-json) to make sure or follow the ["multiple version" section of the arch wiki](https://wiki.archlinux.org/title/ruby#Multiple_versions) to install ruby outside of your package manager.

**Comment by kmafeni04** [comment]
> would reinstall all 3 (ruby, ruby-stdlibs, ruby-json) to make sure

Have already tried this

**Comment by rafaelfranca** [comment]
Thank you for the issue. It sucks that you can't start the server, but this is an issue in the Ruby distribution in your linux. Does `ruby -r json -e "puts 1"` work?

**Comment by JoeDupuis** [comment]
I was able to reproduce using this dockerfile: 

```
FROM archlinux:latest
ENV PATH="${PATH}:/root/.local/share/gem/ruby/3.0.0/bin"

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm ruby git make gcc
RUN gem install rails
```
For convenience:

```
docker build . -t repro_51391
docker run -it --rm repro_51391 bash
```

There might be something wrong after all. 
Requiring `json` works fine  (`ruby -r json -e "puts 1"` returns ` with exit code 0)
but somehow it breaks when required during rails initialization, *unless* the gem is installed through bundler.

I've bypassed the failure through the minimal flag: `rails new --minimal repro_test`, but I get the same error trying to start the console with `bin/rails c`.

Installing the json gem through bundler let me open the console. 

I'll dig a bit more later tonight.

**Comment by JoeDupuis** [comment]
Not Rails related. Looks like it happens when inside a bundler environment:
```
bundle init && bundle exec ruby -e "require 'json'; puts 'done'" # Fails
ruby -e "require 'json'; puts 'done'" # Works
```

**Comment by kmafeni04** [comment]
> ruby -r json -e "puts 1"
It returns 1

**Comment by kmafeni04** [comment]
> Not Rails related. Looks like it happens when inside a bundler environment:

So is it bundle that's the issue or the ruby binary distributed by arch?

**Comment by JoeDupuis** [comment]
I am not sure yet, I was still digging.  

Some of the standard gems are installed in `/usr/lib/ruby/gems/3.0.0/gems`. Those are still found by Rubygems, even when running through bundler, but somehow they get filtered out later when enumerating the gemspecs. 
When using bundler, Rubygems uses an alternate enumerator for the specification stubs that filter them out. 

So it looks like it could be either a bug in rubygems/bundler or Arch. 
Assuming it's a bug in bundler, I was planing to open a PR to fix it.

I would not wait on that if I were you. You should bypass the issue and install ruby through rbenv or a similar tool instead. 
This issue should probably be closed.

**Comment by skipkayhil** [comment]
Looks the same as https://github.com/rails/rails/issues/42373 (but this time its `json` instead of `irb`)

`json` is also not in the [list](https://bugs.ruby-lang.org/issues/20309) of "default gems" to be promoted to a "bundled gem" for 3.5, so I'm not sure gem authors will want to add it to their dependencies any time soon.

Anyways, you can work around this by adding `gem "json"` to your Gemfile, but I agree this is an incompatibility between Bundler and how Arch packages Ruby.

**Comment by kmafeni04** [comment]
> Anyways, you can work around this by adding gem \"json\" to your Gemfile

Thank you, this works
