### ISSUE TITLE
ActionMailer::Base.smtp_settings extra options?

### ISSUE THREAD

**Issue by msxavi** [rails/rails#51403]
### Steps to reproduce
Hello,

I could not find any references to these changes on `smtp_settings` below. I also doubt that there is a dependency injecting `open_timeout` and `read_timeout`.

```ruby
irb(main):005:0> ActionMailer::Base.smtp_settings
=> {:address=>"localhost", :port=>25, :domain=>"localhost.localdomain", :user_name=>nil, :password=>nil, :authentication=>nil, :enable_starttls_auto=>true}
irb(main):006:0> Rails.version
=> "7.0.8"

irb(main):001> ActionMailer::Base.smtp_settings
=>
{:address=>"localhost",
 :port=>25,
 :domain=>"localhost.localdomain",
 :user_name=>nil,
 :password=>nil,
 :authentication=>nil,
 :enable_starttls_auto=>true,
 :open_timeout=>5,
 :read_timeout=>5}
irb(main):002> Rails.version
=> "7.1.3.2"
```

Was the change above intentional?

TIA.

### Expected behavior
Was it intentional?

### Actual behavior
`open_timeout` and `read_timeout` return with `ActionMailer::Base.smtp_settings` and both default to 5.

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.1.4

**Comment by fatkodima** [comment]
Yes https://github.com/rails/rails/commit/52db7f2ef3c4a902227cac163657c89282986e25

**Comment by msxavi** [comment]
@fatkodima thanks. How is [this](https://github.com/rails/rails/blob/v7.1.3.2/actionmailer/test/delivery_methods_test.rb#L25-L34) passing then?

**Comment by fatkodima** [comment]
In that test, these lines https://github.com/rails/rails/commit/52db7f2ef3c4a902227cac163657c89282986e25#diff-b2555388d34f4657f98f10cd106ccac94433e322044fb9455724b09247984850R48-R56 are not executed and so the values are not set.
