### ISSUE TITLE
Schema file naming when there is no "primary" database

### ISSUE THREAD

**Issue by fsuchan** [rails/rails#51406]
The [guide](https://guides.rubyonrails.org/active_record_multiple_databases.html) on multiple databases states:

_If a primary configuration is provided, it will be used as the "default" configuration. If there is no configuration named "primary", Rails will use the first configuration as default for each environment. The default configurations will use the default Rails filenames. For example, primary configurations will use schema.rb for the schema file, whereas all the other entries will use [CONFIGURATION_NAMESPACE]\_schema.rb for the filename._

The part _If there is no configuration named primary..._ gives me a headache because it leads to this:

**database.yml**
```
domain_a: &domain_a
  migrations_paths: db/migrate/domain_a
  ...

domain_b: &domain_b
  migrations_paths: db/migrate/domain_b
```

**-> schema.rb**
-> domain_b_schema.rb

The database configuration for domain_a was first in the list and **implicitly** resulted in schema.rb. Is there a way to achieve **explicit** naming like domain_a_schema.rb and domain_b_schema.rb?

We could add a "primary" database to database.yml which is just empty but that seems wasteful.

### System configuration
**Rails version**: 7.1

**Ruby version**: 3.3

**Comment by fatkodima** [comment]
Hat you tried `schema_dump: domain_a_schema.rb` (see https://edgeguides.rubyonrails.org/active_record_multiple_databases.html)?

**Comment by fsuchan** [comment]
@fatkodima thanks, that was exactly what I was looking for 🙏
