### ISSUE TITLE
Is where way to disable ActiveRecord::UnknownAttributeReference check?

### ISSUE THREAD

**Issue by nleo** [rails/rails#51430]
I have single user, local machine hosted pet project
I prefer to write `Post.order("length(title)")`, not `Post.order(Arel.sql("length(title)"))`

**Comment by fatkodima** [comment]
Hey @nleo we reserve the Rails Issues tracker for bugs in the framework as we don't have the bandwidth to offer application support. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help with your application. Thanks for understanding.
