### ISSUE TITLE
Date#change crashes on leap years

### ISSUE THREAD

**Issue by weshatheleopard** [rails/rails#51443]
### Steps to reproduce
```ruby
> my_date = Date.new(2024,2,29)
> my_date.change(year:2025)
Date::Error: invalid date
```

### Expected behavior
If source date is Feb 29 but target year is a non-leap year, the new date should be Feb 28th of the target year.

### Actual behavior
Crash

### System configuration
**Rails version**: 6.1.7.7

**Ruby version**: 3.1.4p223

**Comment by skipkayhil** [comment]
> If source date is Feb 29 but target year is a non-leap year, the new date should be Feb 28th of the target year.

I'm not sure I agree with your expected behavior. Why should `change` coerce certain dates into other dates? And why should it coerce to February 28th and not March 1st?

**Comment by 3v0k4** [comment]
> Why should `change` coerce certain dates into other dates?

Yeah, I don't think `change` is supposed to perform `DateTime` calculations.

> And why should it coerce to February 28th and not March 1st?

In my experience, libraries try to target the given month when performing calculations.

[moment](http://momentjs.com/docs/#/get-set/month/):

```js
moment('2024-02-29').year('2025')
// 2025-02-28
```

[date-fns](https://date-fns.org/):

```js
date = new Date(2024, 1, 29)
_.add(date, { years: 1 })
// 2025-02-28
```

[java.time](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html):

```java
LocalDate date = LocalDate.of(2024, 02, 29).plusYears(1);
System.out.println(date);
// 2025-02-28
```

Also, Ruby does the same with `Date`:

```ruby
date = Date.new(2024, 02, 29)
date.next_year
# 2025-02-28
```

**Comment by vipulnsward** [comment]
You can use [`Date#advance`](https://edgeapi.rubyonrails.org/classes/Date.html#method-i-advance) which returns the expected result, which is meant for performing calculations 
 

```ruby
> my_date = Date.new(2024,2,29)
 => Thu, 29 Feb 2024
> my_date.advance(years: 1)
 => Fri, 28 Feb 2025
```

[`#change`](https://edgeapi.rubyonrails.org/classes/Date.html#method-i-change)  is a simple wrapper meant only to change the value of the date parts and attempt to create a new date, without any calculations.
