### ISSUE TITLE
Rails error reporter not reporting exceptions inheriting directly from the Exception class

### ISSUE THREAD

**Issue by everton** [rails/rails#51459]
### Steps to reproduce
Subscribing any error reporter and raising exceptions inheriting directly from the Exception class vs other exception classes (exceptions inheriting from StandardError, for example, are reported properly, while from Exception not).

(I realized this behavior while testing some cases for the https://github.com/fractaledmind/solid_errors gem; cc @fractaledmind)

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", "7.1.3.2"

  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class SonOfException     < Exception;     end
class SonOfStandardError < StandardError; end

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  # config.logger = Logger.new('/dev/null')
  Rails.logger  = config.logger

  routes.draw do
    get "/break_with_exception"      => "test#break_with_exception"
    get "/break_with_standard_error" => "test#break_with_standard_error"
  end
end

class ErrorSubscriber
  REPORTED_ERRORS = Hash.new { 0 }

  def report(error, handled:, severity:, context:, source: nil)
    REPORTED_ERRORS[error.class.name] += 1
  end
end

Rails.error.subscribe(ErrorSubscriber.new)

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  def break_with_exception
    raise SonOfException
  end

  def break_with_standard_error
    raise SonOfStandardError
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_exception
    get "/break_with_exception"

    assert_equal 1, ErrorSubscriber::REPORTED_ERRORS['SonOfException']
  end

  def test_standard_error
    get "/break_with_standard_error"

    assert_equal 1, ErrorSubscriber::REPORTED_ERRORS['SonOfStandardError']
  end

  private
    def app
      Rails.application
    end
end
```

### Expected behavior
I don't know if there is any reason to not report all Exceptions, but I imagined all of them should be reported.

### Actual behavior
Exceptions inheriting directly from the Exception class are not reported, while others (such as RuntimeError or StandardError) are reported normally.

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.3.0

**Comment by kuei0221** [comment]
The default handled error class is `StandardError`, so the subclass of 'Exception` is ignored. 
Modifying that constant should let your test pass.
https://github.com/rails/rails/blob/0033d46236932aad5477b966fad155a83caeab97/activesupport/lib/active_support/error_reporter.rb#L29C23-L29C36

**Comment by rafaelfranca** [comment]
This is expected behavior. You can pass which exceptions you want to handle and report passing it explicitly.

**Comment by fractaledmind** [comment]
@rafaelfranca How could we configure the reporter in the test script to receive the Exception error?

**Comment by rafaelfranca** [comment]
You don't. You just pass it as an argument to `handle` or `report`. What I mean that Rails will not handle or report `Exception` subclasses because they aren't supposed to be handled. They are really exceptional and programs should fail on them. If your program should handle that exemption, it should not be direct subclass of `Exception`.

Rails is matching the behavior of `rescue`. If you need to rescue a direct subclass of `Exception` you need to explicitly write code to do that. Same with the error report.

```
Rails.error.handle(MyExceptionSubclass) do
end
```

**Comment by everton** [comment]
> (...) They are really exceptional and programs should fail on them.

I totally understand that they are not supposed to be swallowed, this is why Ruby has the StandardError as a separate subclass, but the whole purpose of the error reports API was to allow gems like sentry and solid-errors to notify about errors in production, and I think I don't want any kind of error, but especially something so low level to not be notified to me and silently makes the app die.

**Comment by everton** [comment]
P.S.: maybe, instead of changing Rails default behavior it could be something defined in the reporter class or object, so the libraries/gems could decide what to subscribe for in a similar way than #handle and #report allows (I mean, the method which delegates the error could check if the class has something like a BASE_EXCEPTION constant or something like that)

**Comment by rafaelfranca** [comment]
Did you try this script against 7-1-stable and main? No test fails. Very likely because the problem doesn't exist there.

**Comment by everton** [comment]
You are right, @rafaelfranca 
I focused on the latest version and didn't test it against the main branch, but it is working as expected in the main branch.

I don't know what you mean by "7-1-stable" (I thought the latest version was stable), but I just tested it with:

   - 7.1.0
   - 7.1.1
   - 7.1.2
   - 7.1.3
   - 7.1.3.1
   - 7.1.3.2
   
   None of these are working; only the main branch is passing

**Comment by rafaelfranca** [comment]
I mean https://github.com/rails/rails/tree/7-1-stable that will be 7.1.4

**Comment by everton** [comment]
It is working, thanks @rafaelfranca
