### ISSUE TITLE
`validates_associated` does not work with `accepts_nested_attributes_for` for `has_many` associations

### ISSUE THREAD

**Issue by Tao-Galasse** [rails/rails#51477]
### Steps to reproduce

I have a model like this:
```ruby
class OrderLine < ApplicationRecord
  has_many :order_line_resources
  accepts_nested_attributes_for :order_line_resources
  validates_associated :order_line_resources
end
```
Which is associated to this model:
```ruby
class OrderLineResource < ApplicationRecord
  belongs_to :order_line
  validates :order_line_id, uniqueness: { scope: :resource_id }
end
```

However, if I write something like this:
```ruby
order_line.update!(order_line_resources_attributes: [{ resource_id: 1 }, { resource_id: 1 }])
```
I receive an error triggered by my unique index on database level: `ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "idx_order_line_resources_order_line_id_resource_id"` but not the validation error I was expecting.

### Expected behavior

I would like to get a validation error from ActiveRecord directly (`ActiveRecord::RecordInvalid`) and not by my pg database.

### Actual behavior

The error is triggered on database level, so my app raises `ActiveRecord::RecordNotUnique: PG::UniqueViolation`

### System configuration
**Rails version**:
7.1.3.2

**Ruby version**:
3.3.0

I hope everything is clear! 🙂 
Thanks a lot for your help and keep up the good work, Rails team, you're doing an amazing job! ✨

**Comment by fatkodima** [comment]
Can you create a reproduction test script using this template https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb ?

**Comment by fatkodima** [comment]
This is the same problem as described in https://github.com/rails/rails/issues/4568 and more linked issues/PRs. Uniqueness validation works only on the persisted records. When you assign `order_line_resources_attributes`, both records are valid, because there are no duplicates in the database for each of them. But when you try to save, then the problem arises.

**Comment by Tao-Galasse** [comment]
> This is the same problem as described in #4568 and more linked issues/PRs. Uniqueness validation works only on the persisted records. When you assign `order_line_resources_attributes`, both records are valid, because there are no duplicates in the database for each of them. But when you try to save, then the problem arises.

Yes, that's what I saw. 
I was expecting a way to make it works properly without having to re-write a custom validation on the `OrderLine` model, but I guess I have no other choice?

I'm probably too used to rails magic 😅 Thanks for your help!

**Comment by jeduardo824** [comment]
Currently, there's no other option to address this at the application level using validations.

One way to 'fix' this is by adding a unique index between order_line_id and resource_id.

Even if the validation worked, doing it at the DB level would also prevent invalid records from being saved due to race conditions, as explained [here](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/validations/uniqueness.rb#L227)

**Comment by Tao-Galasse** [comment]
> Currently, there's no other option to address this at the application level using validations.
> 
> One way to 'fix' this is by adding a unique index between order_line_id and resource_id.
> 
> Even if the validation worked, doing it at the DB level would also prevent invalid records from being saved due to race conditions, as explained [here](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/validations/uniqueness.rb#L227)

As you can see in the example I gave, this is what I did. That's also the reason why I have an `ActiveRecord::RecordNotUnique` error related to PG instead of the records being created successfully.

But I wanted to have an `ActiveRecord::RecordInvalid` in order to fall in the "standard" error handling process, and gracefully manage localisation of the error & stuff like that, which is not very smooth with db-level errors.

I'll go with a custom validation on the parent model. Probably something like this:
```ruby
  validate :unique_order_line_resources

  def unique_order_line_resources
    return if order_line_resources.length == order_line_resources.map(&:container_resource_id).uniq.length

    errors.add(:order_line_resources, :record_not_unique)
  end
```

Thanks for your help!

**Comment by jeduardo824** [comment]
> > Currently, there's no other option to address this at the application level using validations.
> > One way to 'fix' this is by adding a unique index between order_line_id and resource_id.
> > Even if the validation worked, doing it at the DB level would also prevent invalid records from being saved due to race conditions, as explained [here](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/validations/uniqueness.rb#L227)
> 
> As you can see in the example I gave, this is what I did. That's also the reason why I have an `ActiveRecord::RecordNotUnique` error related to PG instead of the records being created successfully.
> 
> But I wanted to have an `ActiveRecord::RecordInvalid` in order to fall in the "standard" error handling process, and gracefully manage localisation of the error & stuff like that, which is not very smooth with db-level errors.
> 
> I'll go with a custom validation on the parent model. Probably something like this:
> 
> ```ruby
>   validate :unique_order_line_resources
> 
>   def unique_order_line_resources
>     return if order_line_resources.length == order_line_resources.map(&:container_resource_id).uniq.length
> 
>     errors.add(:order_line_resources, :record_not_unique)
>   end
> ```
> 
> Thanks for your help!

Ops, sorry! I should've read the example more carefully. 

Other solution would be to catch the "ActiveRecord::RecordNotUnique" exception and add the error to the record, but I know this can be messy and hard to maintain depending on the complexity of the codebase.

```rb
order_line = OrderLine.create!

begin
    order_line.update!(order_line_resources_attributes: [{ resource_id: 1 }, { resource_id: 1 }])
rescue ActiveRecord::RecordNotUnique
    order_line.errors.add(...)
end
```
