### ISSUE TITLE
Rails.cach.fetch always returns Nil 

### ISSUE THREAD

**Issue by Vigneshwar2411** [rails/rails#51473]
### Steps to reproduce
We have setup a basic rails app and trying to write and fetch values using Rails.cache. It seems like its always returning us nil.

We write our value into Rails.cache on def new and try to retrieve the value on def view. We always get the value as nil in def view. But, we are able to successfully retrieve the cache value in def new.

Are we missing something ? Can someone help us out.
Please find the Gemfile version, cache_store config and sample code below

```ruby
  def new
    Rails.cache.write("test_cache", "test", expires_in: 10.minutes)

    p 'Fetch cache in new'
    p Rails.cache.fetch("test_cache")
    # Prints test correctly
  end

  def view
    p 'Fetch cache set from def new'
    p Rails.cache.fetch("test_cache")
    # Prints nil
  end
```

### Expected behavior
Should print value test in def view

### Actual behavior
Prints the value as NIL in def view

### System configuration
**Rails version**: 6.1.3

**Ruby version**: ruby 3.0.6p216 (2023-03-30 revision 23a532679b)

Application Config
class Application < Rails::Application
    config.time_zone = 'UTC'
    I18n.default_locale = :en
    ENV['REDIS_SSL'] ||= 'true'

    redis_config = {
        host: Apollo::Core::EnvWrapper.fetch('REDIS_HOSTNAME'),
        port: Apollo::Core::EnvWrapper.fetch('REDIS_PORT'),
        db: Apollo::Core::EnvWrapper.fetch('REDIS_DB_PARTITION'),
        namespace: 'cache',
        ssl: ENV['REDIS_SSL'] == 'true'
    }
    password = Apollo::Core::EnvWrapper.fetch('REDIS_PASSWORD')
    redis_config = redis_config.merge(password: password) if password.present?
    config.cache_store = :redis_cache_store, redis_config
  end

Gemfile:
gem 'redis', '4.1.2'
gem 'redis-store', '1.6.0'
gem 'redis-actionpack', '5.1.0'
gem 'redis-activesupport', '5.2.0'
gem 'activesupport'
gem 'active_model_serializers', '0.9.8'
gem 'redis-rack', '2.0.5'
gem 'redis-rails', '~> 5.0', '>= 5.0.2'

**Comment by fatkodima** [comment]
Rails 6.1 is not supported with bugfixes (see https://guides.rubyonrails.org/maintenance_policy.html). Can you create a sample app with the latest rails version which reproduces the issue?

Closing for now, as I am sure this is not a rails issue, but maybe some configuration in the app. Will be happy to reopen if reproduction is provided.

**Comment by Vigneshwar2411** [comment]
Sure @fatkodima . Although 6.1 is not being supported. Do you have any idea what configuration would be causing this ?

We have set the application cache_store to point to redis_store. But still facing this issue.

**Comment by fatkodima** [comment]
Don't know. Try to put a debugger and step into the `Rails.cache.write` and `Rails.cache.fetch` methods to see if something is wrong.
