### ISSUE TITLE
Trix toolbar doesn't render correctly with Propshaft

### ISSUE THREAD

**Issue by turgs** [rails/rails#51482]
### Steps to reproduce

```bash
# In bash, get a new rails app setup using propshaft
bin/rails new . -a propshaft
bin/rails generate scaffold post title:string body:text

# Install Action Text:
bin/rails action_text:install
bundle install
bin/rails db:migrate

#  post body is rich text
cat << EOF > app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :body
end
EOF

# ensure it's a rich_text_area in the form
sed -i 's/<%= form.text_area :body %>/<%= form.rich_text_area :body %>/' app/views/posts/_form.html.erb

```

### Expected behavior
http://localhost:3000/posts/new should render the text area with Trix toolbar.

Here is what renders if I follow all the same steps above, but instead of `bin/rails new . -a propshaft`, just using `bin/rails new .`:

![image](https://github.com/rails/rails/assets/1312348/e53bc1e9-a793-410d-a7cd-a779e10faa31)

### Actual behavior
The toolbar is just HTML buttons.

![image](https://github.com/rails/rails/assets/1312348/521a03ca-e8fe-4cd2-9bfa-adbc24f716e1)

I cannot figure out how to get it working in Propshaft.

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.3.0

**Comment by JoeDupuis** [comment]
You need to import trix.css and actiontext.css.
In `app/views/layouts/application.html.erb`, change:
```ruby
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
```
to:
```ruby
<%= stylesheet_link_tag "trix", "actiontext", "application", "data-turbo-track": "reload" %>
```

This is not necessarily the correct fix here, but should get you unblocked.

Sprocket does a lot and it's quite old. 
The idea of behind Propshaft is to get out of the way and let you use whichever tools is better suited for your use case. 

With sprocket (current default), `actiontext.css` gets imported automatically by a sprocket directive ` *= require_tree .`. 

Propshaft doesn't handle importing or merging files. It expects you or an external tool to do it.


I am not sure how to fix this, :thinking: 

Having the Action Text installer add stylesheets in the layout is not necessarily desirable as some users will use Rails with a CSS bundler, importing Actiontext.css and trix.css should be done there.

Perhaps we should do it anyway. Fixing it for the default case make sense. Plus the Rails "trend" is to push for not bundling and relying on HTTP2 instead.

**Comment by turgs** [comment]
Thank you. I think I understand now. I didn't realise  `*= require_tree .` was sprockets specific.

So the comments in _app/spreadsheets/application.css_ seem to be sprockets specific. 

```css
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS (and SCSS, if configured) file within this directory, lib/assets/stylesheets, or any plugin's
 * vendor/assets/stylesheets directory can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the bottom of the
 * compiled file so the styles you add here take precedence over styles defined in any other CSS
 * files in this directory. Styles in this file should be added after the last require_* statement.
 * It is generally better to create a new file per style scope.
 *
 *= require_tree .
 *= require_self
 *= require tailwind_apply
 */
```

I've added underneath that comment
```css
@import "actiontext.css";
```

Then similarly in actiontext.css, that has sprockets stuff too:

```css
/*
 * Provides a drop-in pointer for the default Trix stylesheet that will format the toolbar and
 * the trix-editor content (whether displayed or under editing). Feel free to incorporate this
 * inclusion directly in any other asset bundle and remove this file.
 *
 *= require trix
*/
```

I've added underneath that comment:

```css
@import "trix.css";
```

That way I can leave my `app/views/layouts/application.html.erb` unchanged.

**Comment by JoeDupuis** [comment]
I might take a look at the generator to add those import automatically if I can find the time. :eyes:

**Comment by turgs** [comment]
It turns out, the way I did it didn't work. I've gone back to your suggestion of just modifying the layout `app/views/layouts/application.html.erb`

**Comment by jeduardo824** [comment]
The @mattlemx suggestions work for me. 

@JoeDupuis I'm happy to work in a PR to add this to the generator.

**Comment by rafaelfranca** [comment]
Closing since this more a feature request than an issue. Propshaft isn't as integrated to Rails as Sprockets just yet, but we will need to fix this for Rails 8. Feel free to open a PR.

**Comment by zzak** [comment]
cc #51799
