### ISSUE TITLE
`bin/rails db:prepare` breaks virtual/generated columns in `db/schema.rb`

### ISSUE THREAD

**Issue by cmoel** [rails/rails#51522]
### Steps to reproduce

I put together a minimal reproduction at https://github.com/cmoel/rails_sqlite_generated_column_schema_bug_main. The last commit in that repo is the result of running `bin/rails db:prepare`, which demonstrates the bug.

I tried building a minimal reproduction using [the executable test case templates](https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case) but wasn't fully successful. This is what I've come up with so far: https://gist.github.com/cmoel/6fe5c180a24f941ebf4db70d7e9bde5c. Note: If someone is able to guide me in making the executable test case, I'm happy to finish it.

### Expected behavior

`bin/rails db:prepare` doesn't change anything in `db/schema.rb`.

### Actual behavior

`bin/rails db:prepare` to changes the virtual column to a boolean column in `db/schema.rb`.

### System configuration
**Rails version**:

Main as of https://github.com/rails/rails/commit/bad7ff1664fb05cc227d0386ee3cbe4c292efe05.

**Ruby version**:

v3.3.0

---

### More details

I think I found a bug with virtual/generated columns. The summary is `bin/rails db:migrate` correctly adds virtual columns to `db/schema.rb` but `bin/rails db:prepare` changes the column type to the concrete `type` in `db/schema.rb`. I put together the steps to reproduce with a minimal Rails app at https://github.com/cmoel/rails_sqlite_generated_column_schema_bug_main. Also, I originally reported this bug on https://github.com/fractaledmind/activerecord-enhancedsqlite3-adapter/issues/10. @fractaledmind requested that I open the issue here.

### How to reproduce the bug in a Rails app

Generate 2 migrations, one to create the table and one to add the generated column. This is the `create_table` entry in `db/schema.rb` after running `bin/rails db:migrate`:

```ruby
  create_table "syncs", force: :cascade do |t|
    t.integer "person_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.datetime "unblocked_at"
    t.virtual "blocked", type: :boolean, as: "case when unblocked_at is null then '1' else null end", stored: false
    t.index ["person_id", "blocked"], name: "index_syncs_on_person_id_and_blocked", unique: true
  end
```

I then ran `bin/rails db:prepare` and the `create_table` entry was changed. This is the diff:

```diff
diff --git a/db/schema.rb b/db/schema.rb
index 5594677..9bc0e13 100644
--- a/db/schema.rb
+++ b/db/schema.rb
@@ -21,7 +21,7 @@
     t.datetime "created_at", null: false
     t.datetime "updated_at", null: false
     t.datetime "unblocked_at"
-    t.virtual "blocked", type: :boolean, as: "case when unblocked_at is null then '1' else null end", stored: false
+    t.boolean "blocked"
     t.index ["person_id", "blocked"], name: "index_syncs_on_person_id_and_blocked", unique: true
   end
```

I wouldn't have expected `bin/rails db:prepare` to change `db/schema.rb`, and particularly wouldn't have expected it to change a column type.

**Comment by fatkodima** [comment]
I was able to identify the cause - going to open a PR.
