### ISSUE TITLE
Use Rails application with Ractor

### ISSUE THREAD

**Issue by ukolovda** [rails/rails#51543]
I want run multiple Ractor instance in single process (for execute dispatcher and multiple rake task). 

As I understand, simplest way is - to create Ractor, make private Rails application instance for it and use it.

But I got the error "can not access non-shareable objects".

I try use single application, but got the same error.

### Steps to reproduce

Run this file:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_stuff

    r = Ractor.new do
        app = Rails::Application.new
    end

  end
end
```

### Expected behavior

I should create separate application instance inside the Ractor. Or use single application.

### Actual behavior

I got the error:
```
test.rb:20: warning: Ractor is experimental, and the behavior may change in future versions of Ruby! Also there are many implementation issues.
#<Thread:0x00007fdd063a5a58 run> terminated with exception (report_on_exception is true):
/home/ukolovda/.rvm/gems/ruby-3.3.0/gems/railties-7.1.3.2/lib/rails/railtie.rb:173:in `abstract_railtie?': can not access non-shareable objects in constant Rails::Railtie::ABSTRACT_RAILTIES by non-main ractor. (Ractor::IsolationError)
        from /home/ukolovda/.rvm/gems/ruby-3.3.0/gems/railties-7.1.3.2/lib/rails/railtie.rb:247:in `initialize'
        from /home/ukolovda/.rvm/gems/ruby-3.3.0/gems/railties-7.1.3.2/lib/rails/engine.rb:448:in `initialize'
        from /home/ukolovda/.rvm/gems/ruby-3.3.0/gems/railties-7.1.3.2/lib/rails/application.rb:110:in `initialize'
        from test.rb:21:in `new'
        from test.rb:21:in `block in test_stuff'
```

### System configuration
**Rails version**:
7.1.3.2

**Ruby version**:
3.3.0

### Context:
I have a Rails model (ActiveRecord). When user append a row, I need run some processing loop for this row. When user delete a row, processing loop will terminate.
It worked if I use Thread, but cannot utilize more than 1 processor core. Ractor can, but not works in Rails.

It there exists more simple way - I will glad to see it.

**Comment by rafaelfranca** [comment]
Rails really can't work with Ractors and we have no plans to make it work. Rails applications are shared global state and changing this will very likely require changing the entire framework.
