### ISSUE TITLE
getting started with rails guide is not working for me

### ISSUE THREAD

**Issue by AnthonyGriffithG** [rails/rails#51542]
### Steps to reproduce
https://guides.rubyonrails.org/getting_started.html

Followed  the steps to 7.5 (deleting an article)

### Expected behavior
I should be able to destroy an article by clicking the link and accepting the confirmation.

### Actual behavior
Nothing happens, seems like the page just reloads.

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.2.3

**Comment by JoeDupuis** [comment]
I just went through the guide and could not reproduce.
Any error in the browser console or the rails server output?
