### ISSUE TITLE
Normalizes causes inconsistencies in Active Record queries

### ISSUE THREAD

**Issue by damienlethiec** [rails/rails#51552]
If you confirm that it is a bug, I would be happy to try to fix it. I could need some help as it would be my first PR for Rails.

Thanks !

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.string :description
  end
end

class Post < ActiveRecord::Base
  normalizes :title, with: -> (title) { title.upcase }
  normalizes :description, with: -> (description) { description.strip.presence }
end

ActiveRecord::Base.connection.execute("INSERT INTO Posts (title, description) VALUES ('downcase title', '')") # skips normalization

class BugTest < Minitest::Test
  def test_query_upcase
    post = Post.first
    assert_equal post.title, 'downcase title' # true
    assert_equal Post.where(title: 'downcase title').count, 1 # false
    # "SELECT \"posts\".* FROM \"posts\" WHERE \"posts\".\"title\" = 'DOWNCASE TITLE'"
  end

  def test_query_strip_presence_main
    post = Post.first
    assert_equal post.description, ''
    assert_equal Post.where.not(description: '').count, 0 # true
    # "SELECT \"posts\".* FROM \"posts\" WHERE \"posts\".\"description\" != NULL"
    assert_equal Post.where(description: '').count, 1 # false
    # "SELECT \"posts\".* FROM \"posts\" WHERE \"posts\".\"description\" = NULL"
  end

  def test_query_strip_presence_sum
    assert_equal Post.all.count, Post.where(description: '').count + Post.where.not(description: '').count # false
  end
end
```

### Expected behavior
- ActiveRecord Queries (where and find_by especially) can still find old model instances that have not been normalized since the introduction of a normalization for the moment
- Normalization to nil does not break ActiveRecord Queries

### Actual behavior
- ActiveRecord queries work find when looking for the normalized value (I am aware that it is a feature, which is actually already a bit disturbing in my opinion : https://github.com/rails/rails/pull/49105), but not when looking for the current value of model instances that have not been normalized yet
- Normalization to nil breaks the consistency of Query Result (ex: `where.not.count + where.count != all`)

### System configuration
**Rails version**: Main

**Ruby version**: 3.3.0

**Comment by rafaelfranca** [comment]
Normalize can't change the case sentiveness of the database. It is only to make sure the value is consistent on the Ruby land, as soon it goes to the database, there isn't nothing the framework can do.

**Comment by damienlethiec** [comment]
Could it be useful nonetheless to document the behavior @rafaelfranca ?
