### ISSUE TITLE
[ActiveStorage] blob.url doesn't return permanent link

### ISSUE THREAD

**Issue by giorgimeladze** [rails/rails#51556]
This is not a bug, more of an issue I'm facing while I want to generate a permanent link through ActiveStorage Blob models. By default it is 5 minutes and no longer than 1 week for **attachment.url**

`class Listing
      has_many_attached :images

def images_urls
    images.map do |image|
      image.url(expires_in: 10.years)
    end
  end

end`

I'm not sure if **polymorphic_url** will help and is permanent, that's why I'm raising an issue

### Expected behavior
image.url(expires_in: 10.years) makes a url for 10 years(basically a permanent one)

### Actual behavior
image.url(expires_in: 10.years) returns error saying it exceeds one-week limit

### System configuration
**Rails version**:
'rails', '~> 7.0.4', '>= 7.0.4.2'
**Ruby version**:
ruby '>= 3.1.3'

**Comment by justinko** [comment]
The max expiration is dependent on the configured ActiveStorage service. For example, it is one week for AWS S3. 

Please close this issue.

**Comment by giorgimeladze** [comment]
> The max expiration is dependent on the configured ActiveStorage service. For example, it is one week for AWS S3.

Is there a way to manually change it to for example 100 years or make it permanent?

**Comment by justinko** [comment]
AWS determines that. Not Rails.On Apr 17, 2024, at 10:03 AM, giorgimeladze ***@***.***> wrote:﻿

The max expiration is dependent on the configured ActiveStorage service. For example, it is one week for AWS S3.

Is there a way to manually change it to for example 100 years or make it permanent?

**Comment by giorgimeladze** [comment]
okay then, thank you
