### ISSUE TITLE
security-issue? view without controller action works!

### ISSUE THREAD

**Issue by chmich** [rails/rails#51555]
**Hi**

Rails-7, discussion on [stackoverflow](https://stackoverflow.com/questions/1352420/rails-view-without-a-controller/78315593#78315593)

Is it a bug or a feature?

i`d see it as a bug because the controller is the main point where you mange the security of the app.

**Routes**

```
resources :invoices
```

**invoices_controller.rb**
```
  before_action :authorize_action

  # def index
  #
  # end

  private 

  def authorize_action
     ....
  end
```

**invoices/index.haml**

=> works!

**BUT** the `authorize_action` method fires if `index` is commented out or not.

From my view it should not work. Because if i see no controller action i would expect that the app is giving no access.

**Thanks, Chris**

**Comment by juanmanuelramallo** [comment]
It's a feature not a bug. This is by design. See https://guides.rubyonrails.org/layouts_and_rendering.html#rendering-by-default-convention-over-configuration-in-action

> You've heard that Rails promotes "convention over configuration". Default rendering is an excellent example of this. By default, controllers in Rails automatically render views with names that correspond to valid routes. For example, if you have this code in your BooksController class:
> ```ruby
> class BooksController < ApplicationController
> end
> ```
> ...

**Comment by chmich** [comment]
thanks, @juanmanuelramallo
