### ISSUE TITLE
`alias_attribute` does not work when building `has_many` records via relation.

### ISSUE THREAD

**Issue by dewyze** [rails/rails#51576]
### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "7.1.3.2"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: :cascade do |t|
  end

  create_table :posts, force: :cascade do |t|
    t.integer :person_id
  end
end

class User < ActiveRecord::Base
  has_many :posts,
    inverse_of: :user
end

class Post < ActiveRecord::Base
  alias_attribute :user_id, :person_id

  belongs_to :user
end

class BugTest < Minitest::Test
  def test_association
    user = User.create!

    assert Post.create(user: user)        # Success
    assert Post.create(user_id: user.id)  # Success
    assert user.posts.create!             # Failure
  end
end
```

### Expected behavior

`Post.create(user: user)` works fine. But when creating the associated record via `user.posts.create!` it breaks because the foreign key is not getting set properly.

```
ActiveModel::MissingAttributeError: can't write unknown attribute `user_id`
          raise ActiveModel::MissingAttributeError, "can't write unknown attribute `#{name}`"
```

Additionally, we cannot specify `belongs_to :user, foreign_key: :user_id` or `has_many :posts, inverse_of: :user, foreign_key: :user_id`. One of those has to at least set `foreign_key: :person_id` for this to work.

### Actual behavior

The `has_many` association calls `set_owner_attributes`: https://github.com/rails/rails/blob/6f0d1ad14b92b9f5906e44740fce8b4f1c7075dc/activerecord/lib/active_record/associations/has_many_association.rb#L62

Set owner attributes is called and gets the foreign key: https://github.com/rails/rails/blob/6f0d1ad14b92b9f5906e44740fce8b4f1c7075dc/activerecord/lib/active_record/associations/foreign_association.rb#L25

If it's not specified, the name is derived, in this case `user_id` when the has many checks the inverse `belongs_to`: https://github.com/rails/rails/blob/6f0d1ad14b92b9f5906e44740fce8b4f1c7075dc/activerecord/lib/active_record/reflection.rb#L773-L783

Then we call `_write_attribute`: https://github.com/rails/rails/blob/6f0d1ad14b92b9f5906e44740fce8b4f1c7075dc/activerecord/lib/active_record/associations/foreign_association.rb#L32

This raises the error since `_write_attribute` does not reference aliases.

`write_attribute` would work: https://github.com/rails/rails/blob/6f0d1ad14b92b9f5906e44740fce8b4f1c7075dc/activerecord/lib/active_record/attribute_methods/write.rb#L33

But @byroot [mentions here](https://github.com/rails/rails/pull/45633#issuecomment-1198552406) a possible high cost to doing that.

I'm happy to help implement a solution, but not sure exactly where it should live. I don't know if doing it in the foreign key lookup would be cheaper at all, but it still requires a call to `<record_class>.attribute_aliases`.

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.1.0

**Comment by byroot** [comment]
Not sure if we really want to change this.

In your case I believe you can easily fix this with:

```ruby
has_many :posts, inverse_of: :user, foreign_key: :person_id
```

**Comment by dewyze** [comment]
Yeah, we can make that work. But in the case of trying to rename a class, column, etc. The presence of those can still be confusing.

If we don't want to introduce this that's fine, but I wanted to check first if this was the intended behavior.
