### ISSUE TITLE
Is there already a built-in method from the Rails API for finding all NESTED belongs_to associations?

### ISSUE THREAD

**Issue by Austin-X** [rails/rails#51586]
### Steps to reproduce

In the title of this issue, I used the words "**NESTED belongs_to associations**", and I will explain what I mean by that with an example.

Let's say I have a model A which belongs to model B, and model B belongs to models C and D. The image below shows a visual image of these belongs_to associations.

![image](https://github.com/rails/rails/assets/32133198/de675771-273d-4cb4-be75-ff2f34f62cbc)

The code for these models could look like the code snippet below
```ruby
class A < ApplicationRecord
  belongs_to :b
end

class B < ApplicationRecord
  belongs_to :c
  belongs_to :d
end

class C < ApplicationRecord
end

class D < ApplicationRecord
end
```

See the "Expected behavior" and "Actual behaviour" sections for what the expected and actual result should be when I want to calculate the **nested** belongs_to associations for model A.

### Expected behavior

Return models B, C, and D

### Actual behavior

If I do something like `A.reflect_on_all_associations(:belongs_to)`, it's just going to return model B because the `reflect_on_all_associations(:belongs_to)` method is only one level deep.

My workaround involves recursively calling the `reflect_on_all_associations(:belongs_to)` method, but as you all know, recursive code is always dangerous to use when writing production code, so I was just wondering if we already had a built-in method that calculates these **nested** belongs_to associations.

### System configuration
**Rails version**: 6.0.6.1

**Ruby version**: 2.7.8

**Comment by fatkodima** [comment]
Hey, we reserve the Rails Issues tracker for bugs in the framework. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help or discussion. 

Recursive is the way to go.
