### ISSUE TITLE
Rails Query Issue with Null Value Comparison

### ISSUE THREAD

**Issue by sajjadmurtaza** [rails/rails#51595]
### Steps to reproduce
`XYZ.orders.where('orders.created_at < ? AND state = ?', 1.days.ago, nil)
=> []
`

<img width="1169" alt="Screenshot 2024-04-18 at 08 33 49" src="https://github.com/rails/rails/assets/8552702/8f67a890-3a03-48d9-a175-3b8ff2d41f24">

it work only when I pass NULL

`XYZ.orders.where('orders.created_at < ? AND state IS NULL', 1.days.ago)
`

### Expected behavior
should return result same as when I pass NULL

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 3.1.4

**Comment by fatkodima** [comment]
This is expected, use
```ruby
XYZ.orders.where('orders.created_at < ?', 1.day.ago).where(state: nil)
```
