### ISSUE TITLE
Rubocop binstubs issue causes failures on Windows

### ISSUE THREAD

**Issue by mohits** [rails/rails#51618]
### Steps to reproduce

After setting up a new application with Rails main, create a controller in the empty application.

```
$ ruby bin\rails g controller home welcome
```

### Expected behavior

The generate command should complete successfully without any errors from Rubocop.

```
$ ruby bin\rails g controller home welcome --force
   identical  app/controllers/home_controller.rb
       route  get "home/welcome"
      invoke  erb
       exist    app/views/home
   identical    app/views/home/welcome.html.erb
      invoke  helper
   identical    app/helpers/home_helper.rb
Inspecting 2 files
..
```

### Actual behavior

The command completes but ends with an error from Rubocop.

```
$ ruby bin\rails g controller home welcome
      create  app/controllers/home_controller.rb
       route  get "home/welcome"
      invoke  erb
      create    app/views/home
      create    app/views/home/welcome.html.erb
      invoke  helper
      create    app/helpers/home_helper.rb
D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/configuration.rb:138:in `system': Exec format error - bin/rubocop -A --fail-level=E app/controllers/home_controller.rb app/helpers/home_helper.rb (Errno::ENOEXEC)
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/configuration.rb:138:in `block in apply_rubocop_autocorrect_after_generate!'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/generators.rb:317:in `block in run_after_generate_callback'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/generators.rb:316:in `each'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/generators.rb:316:in `run_after_generate_callback'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/generators.rb:263:in `invoke'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/command/base.rb:178:in `invoke_command'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/command/base.rb:73:in `perform'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/command.rb:71:in `block in invoke'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/command.rb:149:in `with_argv'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/command.rb:69:in `invoke'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/bundler/gems/rails-284baa18c2c6/railties/lib/rails/commands.rb:18:in `<main>'
        from D:/Ruby33-x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from D:/Ruby33-x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from D:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
```

### System configuration
**Rails version**: 7.2.0-alpha

```
  remote: https://github.com/rails/rails.git
  revision: 284baa18c2c62abec170b61e285aefbd9604f675
  branch: main
```

**Ruby version**: ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x64-mingw-ucrt]

### Fix

The issue is fixed by installing binstubs for rubocop (unfortunately, right now, I do not know where the fix would be applied in the Rails codebase).

```
$ bundle binstubs rubocop --force
```

If you point me to where it should go, I am happy to open a PR. Else, I'm happy for someone to do this at the correct place. Thanks!

### Other Information

Detailed links:
* The setup is basic Rails main for a new application on Windows. However, detailed steps are available here: https://notepad.onghu.com/2024/how-to-use-rails-main-for-development/
* The problem and fix are also detailed here: https://notepad.onghu.com/2024/fix-rails-main-on-windows-rubocop-error/

**Comment by andyw8** [comment]
https://github.com/rails/rails/blob/cf64895067e285a8eefe43a40ad9324138a19a40/railties/lib/rails/configuration.rb#L138

**Comment by zzak** [comment]
I believe this was fixed by #51779, @mohits can you verify?

If someone can reproduce, please feel free to re-open.

**Comment by mohits** [comment]
Hi @zzak, I think this looks like it is completed but I'm not sure.

[1] I created a new app on main and then ran the usual generate controller home welcome and I got this:

```
$ ruby bin\rails g controller home welcome
      create  app/controllers/home_controller.rb
       route  get "home/welcome"
      invoke  erb
      create    app/views/home
      create    app/views/home/welcome.html.erb
      invoke  helper
      create    app/helpers/home_helper.rb
```

No error! That's great.

[2] However, I think the earlier versions would run `rubocop` and show that no offenses were found. So, I'm not sure it's fully fixed. This is what I had on my post from before (after fixing binstubs):

```
$ ruby bin\rails g controller home welcome --force
   identical  app/controllers/home_controller.rb
       route  get "home/welcome"
      invoke  erb
       exist    app/views/home
   identical    app/views/home/welcome.html.erb
      invoke  helper
   identical    app/helpers/home_helper.rb
Inspecting 2 files
..

2 files inspected, no offenses detected
```

Could it be that `rubocop` doesn't run on Windows any more?

**Comment by andyw8** [comment]
@mohits try making a change in `.rubocop.yml`, e.g. set the styling to use single quotes, and run the generator again.

I'm not sure if the behaviour has changed, but when testing on Mac I see RuboCop output only if there are corrections made, otherwise it's silent.

**Comment by andyw8** [comment]
Ah, it was change here: https://github.com/rails/rails/pull/51808

**Comment by mohits** [comment]
I just switched off, but will try this. This what I tired was on a pristine main branch app and used to work fine (after the bundle fix) without changing rubocop.xml earlier.

**Comment by andyw8** [comment]
Also note that option is now off by default: https://github.com/rails/rails/pull/51782

**Comment by mohits** [comment]
Thanks, I had missed that though I try to skim through the changes in the Rails repo.

After your note:
* I created a new app from main again
* Edited `/config/environments/development.rb` to uncomment the line about `rubocop_autocorrect`
* Generated a new controller and did not see any `rubocop` output

Did that again and saw this in Task Manager:

![image](https://github.com/rails/rails/assets/56816/577b91c8-66e7-4338-ab32-956692cb14af)

I think the silence is related to: #51808. So, it's all good!

Thanks everyone. I will update my post to reflect these items later this week.
