### ISSUE TITLE
Action Cable as Stand Alone server leads to Devise::MissingWarden: error

### ISSUE THREAD

**Issue by ashikajith** [rails/rails#51612]
### Steps to reproduce
We recently upgraded the rails app to 7.1, and now that we support the Action Cable to run as a standalone server, I was following this guide and did as follow 
```ruby
# config/initializer/health_check.rb
Rails.application.config.after_initialize do
  ActionCable.server.config.health_check_path = "/up"
end
```
```ruby
# action_cable.ru 
require_relative "config/environment"
Rails.application.eager_load!
run ActionCable.server
```
```ruby
# config/application.rb
config.action_cable.mount_path = nil
config.action_cable.url = "ws://#{ENV['API_URL'].remove('http://')}/cable"
config.action_cable.allowed_request_origins = [%r{https?://.*}]
```

Now, when I start the app `bundle exec puma -p 3030 action_cable.ru`, along with the rails server. The action cable server starts running, but when I make a `curl` request to `/up`, I get the 500 error. On inspecting, I came to know that it conflicts with the Devise gem
```bash
Devise::MissingWarden: Devise could not find the `Warden::Proxy` instance on your request environment.
Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
```
I am curious if anyone has faced any similar issue before and why Rails::HealthController is using warden callbacks as it is just a health check endpoint

### Expected behavior
`curl localhost:3030/up` should return 200 responses, from [Rails#HealthController/show](https://github.com/rails/rails/blob/main/railties/lib/rails/health_controller.rb#L35)

### Actual behavior
`curl localhost:3030/up` is returning a 500 error response, with the error
```bash
Devise::MissingWarden: Devise could not find the `Warden::Proxy` instance on your request environment.
Make sure that your application is loading Devise and Warden as expected and that the `Warden::Manager` middleware is present in your middleware stack.
If you are seeing this on one of your tests, ensure that your tests are either executing the Rails middleware stack or that your tests are using the `Devise::Test::ControllerHelpers` module to inject the `request.env['warden']` object for you
```

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.3.0

**Comment by ashikajith** [comment]
I added warden::Manager to the rack App and resolved the error. However, I am confident that there are more efficient ways to tackle this issue.
```
# action_cable.ru 
require_relative "config/environment"
use Warden::Manager  # Adding this line fixed the issue
Rails.application.eager_load!
run ActionCable.server
```

**Comment by rafaelfranca** [comment]
Thank you for the issue but this is an issue with your setup of Devise.
