### ISSUE TITLE
[ActiveRecord] Enum defined methods does not follow naming convention

### ISSUE THREAD

**Issue by maniSHarma7575** [rails/rails#51621]
### Describe the problem

When we defined the enum in Rails, methods for the enums were generated on the fly. However, these enums do not adhere to the naming convention of the methods.

When listing the methods for a particular instance in the script below, Rails defines two methods for the same key: one with the naming convention and the other with the same name as the key.

For example:

```ruby
[1] pry(#<BugTest>)> john.methods.select { |method| method.to_s.include? "US"}
=> [:"US West (Oregon)!", :US_West_Oregon_?, :US_West_Oregon_!, :"US West (Oregon)?"]
```

The method `:"US West (Oregon)!"` contains spaces and round brackets in the name.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"
require "pry"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Base.has_many_inversing = true

ActiveRecord::Schema.define do
  create_table "users", force: :cascade do |t|
    t.string "name"
    t.integer "data_region"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
end

class User < ActiveRecord::Base
  enum data_region: {
    'US West (Oregon)':   'us-west-2',
    'Canada (Central)':   'ca-central-1',
    'Europe (Frankfurt)': 'eu-central-1',
  }
end

class BugTest < Minitest::Test
  def test_enum_method_naming_convention
    john = User.create!(name: "John")
    refute_respond_to john, :"US West (Oregon)?"
    refute_respond_to john, :"US West (Oregon)!"
    refute_respond_to john, :"Canada (Central)?"
    refute_respond_to john, :"Canada (Central)!"
    refute_respond_to john, :"Europe (Frankfurt)?"
    refute_respond_to john, :"Europe (Frankfurt)!"
  end
end
```

### Expected behavior

Enum methods should be generated following the naming convention.

### Actual behavior

Enum methods defined by Rails doesn't follow the naming convention

### System configuration
**Rails version**: 7.2.0.alpha

**Ruby version**: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

**Comment by fatkodima** [comment]
I did not get what the problem is?

Rails generates both methods ("pretty" and "not pretty") on purpose - https://github.com/rails/rails/blob/284baa18c2c62abec170b61e285aefbd9604f675/activerecord/lib/active_record/enum.rb#L279-L294

**Comment by maniSHarma7575** [comment]
> I did not get what the problem is?
> 
> Rails generates both methods ("pretty" and "not pretty") on purpose -
> 
> https://github.com/rails/rails/blob/284baa18c2c62abec170b61e285aefbd9604f675/activerecord/lib/active_record/enum.rb#L279-L294

@fatkodima Upon reviewing the command output below, it's evident that the method name `US West (Oregon)!` contains spaces and brackets, which deviates from standard programming naming conventions. I've noticed this discrepancy, and it seems there might be an issue with adhering to the naming convention for methods.

Additionally, we recently integrated an enum into our application with the following values. However, we discovered that calling the method for the corresponding keys is not possible without utilizing 'send', primarily due to the naming convention.

Could you kindly clarify if Rails intentionally maintains this naming convention?  and Why?

```ruby
[1] pry(#<BugTest>)> john.methods.select { |method| method.to_s.include? "US"}
=> [:"US West (Oregon)!", :US_West_Oregon_?, :US_West_Oregon_!, :"US West (Oregon)?"]
```

**Comment by fatkodima** [comment]
As you can see from the removed tests in the PR you opened, this is intentional. It keeps original enum key names to be able to use exact key names (via `send`, for example). And a mangled name to be able to little easier use it in the code, like for:
`User.enum foo: {"foo bar" => 1}` you can call `User.foo_bar`.

For enums with keys like in the description for this issue, it is a pain to use either of the approaches. But this is how it is done and removing this behavior is at least breaking, without saying that it is not needed.

**Comment by manishElitmus** [comment]
> As you can see from the removed tests in the PR you opened, this is intentional. It keeps original enum key names to be able to use exact key names (via `send`, for example). And a mangled name to be able to little easier use it in the code, like for: `User.enum foo: {"foo bar" => 1}` you can call `User.foo_bar`.
> 
> For enums with keys like in the description for this issue, it is a pain to use either of the approaches. But this is how it is done and removing this behavior is at least breaking, without saying that it is not needed.

@fatkodima, I suggest that instead of using either approach, we consider restricting the definition of enum keys to follow a convention friendly to programming methods.
