### ISSUE TITLE
`ActiveSupport::Inflector` isolation/conflicts: recommended approach

### ISSUE THREAD

**Issue by krystof-k** [rails/rails#51630]
I'm trying to utilize `ActiveSupport::Inflector`:

```ruby
# config/initializers/inflections.rb

ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym "API"
  inflect.acronym "ID"
  inflect.acronym "JSON"
  inflect.acronym "PDF"
  inflect.acronym "URL"
end
```

and it breaks all the time.

One thing is autoloading, which can be sort of handled via custom `Zeitwerk::Inflector`. I created one:

<details>
<summary><em>Custom Zeitwerk inflector to override conflicts</em></summary>

```ruby
# config/initializers/zeitwerk.rb

# List of file glob patterns and their corresponding camelized class names
OVERRIDES = {
  "**/gems/actionmailbox-*/app/models/action_mailbox/inbound_email/message_id.rb" => "MessageId",
  "**/gems/avo-*/app/components/avo/fields/id_field" => "IdField",
  "**/gems/avo-*/app/helpers/avo/url_helpers.rb" => "UrlHelpers"
}.freeze

# Override the default Zeitwerk inflector to use the overrides
Rails.autoloaders.each do |autoloader|
  autoloader.inflector = Class.new(Zeitwerk::Inflector) do
    define_method(:camelize) do |basename, abspath|
      # Check if the file path matches any of the overrides
      OVERRIDES.each do |glob_pattern, camelized|
        if File.fnmatch?(glob_pattern, abspath)
          # Return the hard-coded camelized class name
          return camelized
        end
      end
      # For all other files, use the default ActiveSupport::Inflector.camelize
      basename.camelize
    end
  end.new
end
```

</details>

 and while it still breaks all the time, it can be fixed.

But then there are cases, when the conflict is within the code of a 3rd party gem or engine, using the inflector methods like `.classify`, `.underscore`, `.camelize` etc.

For example, I recently bumped into the `JSON` acronym issue in the [active_model_serializers](https://github.com/rails-api/active_model_serializers) gem: 

> It converts `json_api` using `"json_api".classify` to `JsonApi`.
>
> Some controller:
> ```ruby
> render json: data, adapter: :json_api, status: 200
> ```
>
> [rails-api/active_model_serializers `/lib/active_model_serializers/adapter.rb`](https://github.com/rails-api/active_model_serializers/blob/bda195020e77f9fd4850d4beeb3d3e51bfa086e6/lib/active_model_serializers/adapter.rb#L84):
> ```ruby
> adapter_name = adapter_name.to_s.classify.tr('API', 'Api')
> ```
>
> 9 years ago (!), they even [added this hack](https://github.com/rails-api/active_model_serializers/issues/993) to sort out the issue if you have API in acronyms. But not JSON, so it breaks anyway.

Or [Avo stops showing IDs](https://github.com/avo-hq/avo/issues/2716) when I have ID in acronyms. And the list can go on and on.

I tried to look up any similar issues – to my surprise, there are not that many as I would expect – for example #28624 or #40068, and I understood there is no solution to this nor any effort in the direction of solving this.

Therefore I want to ask if I'm not missing anything, and if I'm not, I would like to propose **updating the docs** in the meaning of _don't try to use custom inflections, it breaks stuff_, if this is the recommended approach. If it was there, it would save me many hours trying to use the inflector properly, break stuff and then trying to fix it with such hacks as described above.

I'm sorry in advance if this issue in this repo is not a right place for this, but I couldn't come up with anything better, as if there was a solution to this I'm pretty confident I'd have found it.

### System configuration
**Rails version**:
7.0.8.1
**Ruby version**:
3.2.3

**Comment by adrianthedev** [comment]
We (at Avo) do have an `Avo::IdField` and a few other `%Id%` classes. Would that inflection rule interfere with a partial class name? We don't have any `Id` class on it's own.

**Comment by rafaelfranca** [comment]
Feel free to send a PR. but yeah, we don't recommend changing the inflector because it has global effect on the Ruby process.

**Comment by krystof-k** [comment]
OK, will do. However, is changing the inflector in the way it acts only locally, not affecting 3rd party gems/engines possible? Or allowing gems/engines to use their own inflector (I guess it works the other way to – inflections used in gems/engines affects the parent app).

**Comment by rafaelfranca** [comment]
Unfortunately it isn't possible. This would break a lot of existing applications that rely on the global aspect of inflectors.
