### ISSUE TITLE
ActiveRecord/Postgresql composite primary keys breaks count query on includes+references

### ISSUE THREAD

**Issue by urmorae** [rails/rails#51634]
### Steps to reproduce
ActiveRecord 7.1.3.2, Ruby 3.3.0, PostgreSQL adapter

Assuming you have tables

```
class ItemType < ApplicationRecord
  self.primary_key = 'item_type_cd'
end

class Item < ApplicationRecord
  self.primary_key = %i[item_type_cd some_other_column]
  belongs_to :item_type, foreign_key: 'item_type_cd'
end
```

Running a query

`
Item.where(item_type_col1: 'x').includes(:item_type).references(:item_type).count
`

Crashes because it generates 

`
SELECT COUNT(DISTINCT ["item_type_cd", "some_other_column"]) FROM "items" LEFT OUTER JOIN "item_types" ON "item_types"."item_type_cd" = "item"."item_type_cd" WHERE "item_types"."item_type_col1" = $1
`

### Expected behavior

It should generate count(*) 

### Actual behavior

Invalid SQL generated

**Comment by fatkodima** [comment]
Can you create a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb template?

**Comment by urmorae** [comment]
Sure thing, it breaks with sqlite as well. Seems like I cannot attach .rb files here so sry, test is in markdown:

```
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "~> 7.1.0"
  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :item_types, force: true do |t|
    t.string :item_type_nm, null: false
  end

  create_table :items, primary_key: [:item_type_id, :other_field] do |t|
    t.string :other_field, null: false
    t.references :item_type
  end
end

class ItemType < ActiveRecord::Base
  has_many :items
end

class Item < ActiveRecord::Base
  self.primary_key = [:item_type_id, :other_field]
  belongs_to :item_type
end

class BugTest < Minitest::Test
  def test_count_with_references
    assert_raises ActiveRecord::StatementInvalid do
      Item.where(item_type_nm: 'a').includes(:item_type).references(:item_type).count
    end
  end
end
```

**Comment by urmorae** [comment]
PS: .where condition is not actually relevant when reproducing the bug

**Comment by fatkodima** [comment]
I was able to identify the problem and seems like found the solution. Will open a PR a bit later today. 
But you are welcome to open a PR, if you want to try to fix it by yourself.
