### ISSUE TITLE
It is not possible to pass raw JSON string to ActiveRecord JSON type attribute

### ISSUE THREAD

**Issue by aliismayilov** [rails/rails#51647]
### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"
require "json"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.json :data
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_json_values
    data = '{"foo":"bar"}'
    post_with_parsed_data = Post.create!(data: JSON.parse(data))
    post_with_raw_data = Post.create!(data:)

    assert_equal({"foo" => "bar"}, post_with_parsed_data.reload.data)
    assert_equal({"foo" => "bar"}, post_with_raw_data.reload.data)
  end
end
```

### Expected behavior
When passing a JSON string into a JSON backed column, no serialization happens and the data should be stored as is. When loaded, it should be parsed into Hash object.

### Actual behavior
The raw string is [encoded into JSON string](https://github.com/rails/rails/blob/ec4558ae9f5cc60355f3fd15d4f2f7adccf1c158/activerecord/lib/active_record/type/json.rb#L17-L19) – a valid JSON string gets wrapped with double quotes and becomes a JSON text by losing its structure.
```
Failure:
BugTest#test_json_values [test.rb:37]:
Expected: {"foo"=>"bar"}
  Actual: "{\"foo\":\"bar\"}"
```

The same behavior happens with JSONB columns, since it uses the same serializer logic. This behavior allows any kind of string to pass through. Please feel free to close this issue if it's an expected behavior (feature, not a bug:), because any single string is a valid JSON by latest JSON specification. 

### System configuration
**Rails version**: edge/main version

**Ruby version**: 3.3.0

**Comment by rafaelfranca** [comment]
This is expected behavior for the reasons you already said. Any string is valid JSON and we can't know which string is a result of JSON.dump or it is a string that need to be made to be translated to json. Thank you for the issue
