### ISSUE TITLE
Individually uncommenting `ActiveRecord` related framework defaults, not enabling respective behaviour

### ISSUE THREAD

**Issue by Gooner91** [rails/rails#51642]
### Steps to reproduce

Wasn't 100% sure about a reproduction script, I hope the information helps. 

Currently application is loading 6.1 defaults.

Following behaviour observed when enabling (individual) new 7.0 defaults (specifically for `ActiveRecord::Base`). As far as I understand, uncommenting these defaults individually should be enough to enable their new behaviour. However, when for example uncommenting the flag:

```
Rails.application.config.active_record.partial_inserts = false
```

**in IRB:**

```
ActiveRecord::Base.partial_inserts # still returns true
```
![Screenshot 2024-04-23 at 13 49 06](https://github.com/rails/rails/assets/8371074/3fe87d04-d8b4-47e5-b28f-0d7f5420ce7b)

After loading `7.0` defaults in `application.rb`, I can observe the expected behaviour of disabled `partial_inserts`. 

Also observed similar behaviour for `Rails.application.config.active_record.automatic_scope_inversing = true`, `ActiveRecord::Base.automatic_scope_inversing` returns `false`.
![Screenshot 2024-04-23 at 13 59 56](https://github.com/rails/rails/assets/8371074/07de116e-666c-4f74-8484-22f05051d9ed)

### Expected behavior
Uncommenting individual defaults should enable the expected behaviour (without the need to update `load_defaults`)

### Actual behavior
Unless `load_defaults` is updated to load 7.0, `ActiveRecord::Base`'s accessor still returns the old configs.

### System configuration
**Rails version**: 7.0.8.1

**Ruby version**: 3.3.0

**Comment by rafaelfranca** [comment]
This usually happens because `ActiveRecord::Base` was loaded before it should be. It could be a gem doing that, or your own code. Do you have any kind of `ActiveRecord::Base.include` in any initializer?

**Comment by Gooner91** [comment]
Hi, thanks for the response, I didn't find any occurrence of `ActiveRecord::Base.include`, will further check if its a gem as you mentioned.

**Comment by Gooner91** [comment]
I will close this issue for now, uncomment these defaults at the end. On the way if I come across any finding worth sharing here, will do if it helps someone else.
