### ISSUE TITLE
ActionMailer deliver_later doesn't work in development (delivery_method = :file)

### ISSUE THREAD

**Issue by collimarco** [rails/rails#51691]
### Steps to reproduce

I have this configuration:

```ruby
# config/environment/development.rb

config.action_mailer.delivery_method = :file
```

Then I have this code:

```ruby
SubscriberMailer.with(email_id: email_id, subscriber_id: subscriber_id).newsletter.deliver_now
```

It works fine in development, and I can see the sent emails in `tmp/emails`.

**If I replace `deliver_now` with `deliver_later`, the email are no longer written to file...**

Note: I am aware that `deliver_later` uses background jobs for processing and indeed I am running the solid queue process (the other jobs are being processed properly, only the emails disappear).

### Expected behavior

I should see emails in `tmp/emails`.

### Actual behavior

When using deliver_later emails are lost and never written to `tmp/emails`.

### System configuration

**Rails version**: 7.1.3.2
**Ruby version**: 3.3.1

**Comment by fatkodima** [comment]
Can you provide a sample app that reproduces the issue?

**Comment by collimarco** [comment]
Oops...

The problem was that development was using (by mistake) the default in-memory queue for Active Job instead of Solid Queue. Thus the jobs were processed successfully if they were scheduled from code running in the main Rails process (e.g. `bin/dev`), but they were scheduled and lost when they were created from another short-lived process (e.g. rake task, cron job, etc.).
