### ISSUE TITLE
Scaffolding with namespace generates broken partial view links with tailwind

### ISSUE THREAD

**Issue by brunto** [rails/rails#51701]
### Steps to reproduce

1. Generate a new tailwind rails app `rails new myapp -c tailwind`
2. Generate a namespaced scaffold: `bin/rails g scaffold Admin::Books name:string`
3. Run the migration: `bin/rails db:migrate`
4. Change the root_path to: `root "admin/books#index"`
5. Start the server: `bin/dev` (don't forget to install foreman)
6. Open the index page
7. Add a new book
8. Go back to the index page
9. BoOoooOommm ```undefined method `edit_book_path' for an instance of #<Class:0x000000012316db80>```

### Expected behavior
We should have the edit links working for the book.

### Actual behavior
```undefined method `edit_book_path' for an instance of #<Class:0x000000012316db80>```

### Fix
Inside the file `app/views/admin/books/_book.html.erb`, we should change the following:

```
<%= link_to "Edit this book", edit_book_path(book), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
```

to

```
<%= link_to "Edit this book", edit_admin_book_path(book), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
```

or maybe it's related to the module definition in: `app/models/admin.rb`

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: ruby 3.3.1 (2024-04-23 revision c56cd86388) +YJIT [arm64-darwin23]

**Comment by flavorjones** [comment]
@brunto Can you please re-open this issue on https://github.com/rails/tailwindcss-rails? Thank you!

Worth noting, some work is already being done to clean up the templates: rails/tailwindcss-rails#357

**Comment by flavorjones** [comment]
See also https://github.com/rails/tailwindcss-rails/pull/359 which I think fixes this issue.
