### ISSUE TITLE
`ActiveSupport::LogSubscriber` example and code reloads

### ISSUE THREAD

**Issue by josegomezr** [rails/rails#51714]
I can't call this a bug or a feature, but rather a surprise. I hope you can shine light whether the behavior is expected or not.

### Steps to reproduce

Following the API docs on [`ActiveSupport::LogSubscriber`][as-ls] I placed in my
app a class like:

```ruby
# lib/my_module/log_subscriber.rb
module MyModule
  class LogSubscriber < ActiveSupport::LogSubscriber
    attach_to :my_module # important, you'll see why

    def something(event)
      info "  Here 'something' happened! duration=#{event.duration.round(2)}ms payload=#{event.payload.inspect}"
    end
  end
end
```

Note: `lib/my_module` is autoloadable.

Then I emit the events with `ActiveSupport::Notifications`.

```ruby
ActiveSupport::Notifications.instrument('something.my_module', {data: :here})
```

And until this point, everything works as expected, there's a log line:

```
[2024-05-02T14:20:50.191+02:00] INFO:   Here 'something' happened! duration=0.02ms payload={:data=>:here}
```

Then I change the log message a bit... and reload code with `reload!`.

```
[2024-05-02T14:21:43.589+02:00] INFO:   Here 'something' happened! duration=0.03ms payload={:data=>:here}
```

I still see the old code handler, if I inspect the constant: `MyModule::LogSubscriber.inspect` and recall `#instrument` again...

### Expected behavior

I should see:

```
[2024-05-02T14:25:43.321+02:00] INFO:   NEW Here 'something' happened! duration=0.03ms payload={:data=>:here}
```

### Actual behavior

I actually see:

```
[2024-05-02T14:25:43.150+02:00] INFO:   Here 'something' happened! duration=0.04ms payload={:data=>:here}
[2024-05-02T14:25:43.321+02:00] INFO:   NEW Here 'something' happened! duration=0.03ms payload={:data=>:here}
```

### System configuration
**Rails version**: 7.1.3.2

**Ruby version**: 3.2.2

---

I spent some time digging over the [`ActiveSupport::LogSubscriber`][as-ls] objects, which lead me to [`ActiveSupport::Subscriber`][as-s].

I was expecting that when the code reloads, the subscribers are "cleaned up" and I see the new code running.

I tried calling: `.detach_from` just before `.attach_to` and doesn't work either. I placed a breakpoint on `ActiveSupport::Subscriber.detach_from` & `ActiveSupport::Subscriber.attach_to` for investigating and noticed that after the `reload!` + `#inspect`:

```ruby
delegates = ActiveSupport::Notifications.notifier.all_listeners_for('something.my_module').map(&:delegate)
# This returns two items
delegates.select { _1.class.name =~ /MyModule/}
# this returns one item, the same logic in ActiveSupport::Subscriber.find_attached_subscriber
delegates.select { _1.instance_of?(MyModule::LogSubscribers)}

# for reference, this is the method body
def find_attached_subscriber
  subscribers.find { |attached_subscriber| attached_subscriber.instance_of?(self) }
end
```

That `#instance_of?` check fails to find the subscriber, even though they're the same class.

I suspect that `reload!` redefines `MyModule::LogSubscribers` to be a different thing so that `#instance_of?` doesn't match anymore [even though the class name is the same] and the moment I evaluate the const again, it calls `.attach_to` again and attaches a new instance of a class with the same name but not the same "class" as the one previous to the reload (?) [because it's techincally not an instance of the new const?].

To verify my hypothesis I defined:

```ruby
def reaload_capable_attach_to(namespace, new_subscriber = new, notifier = ActiveSupport::Notifications, inherit_all: false)
  # Match the subscriber by class name instead of #instance_of?
  if subscriber = subscribers.find { _1.class.name == new_subscriber.class.name }
    subscribers.delete(subscriber)
    # Remove event subscribers of all existing methods on the class.
    fetch_public_methods(subscriber, true).each do |event|
      pattern = "#{event}.#{namespace}"
      notifier.unsubscribe(subscriber.patterns[pattern])
      subscriber.patterns.delete(pattern)
    end
  end

  attach_to(namespace, new_subscriber, notifier, inherit_all: false)
end
```

and used it like:

```diff
- attach_to :my_module
+ reaload_capable_attach_to :my_module
```

And with that it after reloads and I see only one message. That brings me to the questions:

- Is it expected behavior?
  + If so, the example can't tolerate code reloads, should it be stated somewhere?
- Should `LogSubscriber`/`Subscriber`'s be able to handle code reloads?
- Am I misusing these facilities?

p.s.: Sorry for the wall of text, it's been a bit tough to put all the content together in a somewhat coherent shape 😅

[as-ls]: https://api.rubyonrails.org/v7.1.3.2/classes/ActiveSupport/LogSubscriber.html
[as-s]: https://api.rubyonrails.org/v7.1.3.2/classes/ActiveSupport/Subscriber.html

**Comment by fxn** [comment]
Stuff that is cached cannot be reloadable. Middleware is an example, [this section](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#use-case-2-during-boot-load-code-that-remains-cached) of the autoloading guide explains this (but I see there is an obsolete mention to `lib`).

If you still want `lib` to be reloadable, one way to organize this would be to create `lib/log_subscribers` and ignore that subdirectory in the `autoload_lib` call.

**Comment by josegomezr** [comment]
I had something like this:

```ruby
module Namespace
  extend ActiveSupport::Autoload

  autoload :MyService
end
```

and in the soruce of `namespace/my_service.rb`.

```
require_relative ./log_subscriber.rb
```

Then I saw the repeating messages and blamed the `#attach_to`, and with the
results of this research I ended up with:

```ruby
module Namespace
  extend ActiveSupport::Autoload

  autoload :MyService # this is the class emitting `xxx.namespace` events.

  eager_autoload do
    autoload :LogSubscriber
  end

  # LogSubscriber.attach_to :namespace
  LogSubscriber.reaload_capable_attach_to :namespace
end
```

**Comment by fxn** [comment]
And `namespace/my_service.rb`, where was it stored? How was `Namespace` loaded?

Subscribers are typically defined while the application boots, because you want them to be when is yours effectively defined?

**Comment by josegomezr** [comment]
> Are any of those files in the autoload paths?

I believe that's the case. Files are in `rails-root/lib/`, and  `application.rb` has:

```ruby
config.autoload_lib(ignore: %w[tasks])
```

**Comment by fxn** [comment]
But, who loads these files, and when? Is loading them triggered from config/initializers?

**Comment by josegomezr** [comment]
I triggered the behavior from the console by:

```ruby
Namespace::MyService.new().call()
```

That should be Zeitwerk loading them (?). I didn't do any `require` call other than what `application.rb` already had.

The way I was intending to use the service [and in turn the subscriber] was in a rake task like:

```
namespace :ns do
  task import_all: :environment do
    Namespace::MyService.new().call()
  end
end
```

and just `bin/rake ns:import_all`

p.s: This is a bit far away from my ruby understanding, I apologize if I can't answer clearly :sweat_smile:

**Comment by fxn** [comment]
No prob at all :D, I believe I have an idea of your setup now.

About to fly to RailsConf right now, I'll followup if there's anything else worth sharing. Thank you!
