### ISSUE TITLE
[Edge Guides]: Text in some code snippets not readable (low contrast)

### ISSUE THREAD

**Issue by alexandergitter** [rails/rails#51723]
The color scheme used on some code snippets makes parts of the snippets unreadable due to a very low contrast.

Examples:

- **Unreadable config content**
https://edgeguides.rubyonrails.org/active_storage_overview.html#example-azure-storage-cors-configuration
![image](https://github.com/rails/rails/assets/816758/65afd595-fe1c-40bc-8578-5d157fbcb58e)

- **Invisible colons in yaml config**
https://edgeguides.rubyonrails.org/active_storage_overview.html#configuring-services
![image](https://github.com/rails/rails/assets/816758/8c04299c-7e96-4eeb-8147-b5841d5dc6d7)

**Comment by akhilgkrishnan** [comment]
@alexandergitter Thanks for raising this issue.  I've raised a [PR](https://github.com/rails/rails/pull/51724) for fixing this.
