### ISSUE TITLE
New `permanent_connection_checkout` does not seem to work as expected.

### ISSUE THREAD

**Issue by ioquatix** [rails/rails#51722]
I'm trying out the new AR `lease_connection` and `with_connection` methods in `Falcon`.

Here is the example code I'm working with:

https://github.com/socketry/falcon-rails-example/pull/7

I could not seem to isolate the connection from leaving the `with_connection` block without also specifying `(prevent_permanent_checkout: true)` which seems to defeat the purpose of using `with_connection`.

Even with:

```ruby
config.active_record.permanent_connection_checkout = :disallowed
```

set, I could check out permanent connections, e.g. a top level `highscore_id = Highscore.last.id`.

Not sure exactly how this is supposed to fit together, but it does, on the surface, look like it's not fully working as intended.

Reproductions: https://gist.github.com/ioquatix/2bbcc5a4dd2fdf171e585b69f9c5f914

**Comment by casperisfine** [comment]
First repro:

```ruby
  def test_bare_connection
    assert_raises(ActiveRecord::ActiveRecordError) do
      post = Post.create!
      post.comments << Comment.create!
    end
  end
```

This assumption isn't correct. `.create!` will checkout and then check back in a connection.

**Comment by casperisfine** [comment]
Here's how it should be:

```ruby
class BugTest < Minitest::Test
  def test_bare_connection
    refute_predicate Post.connection_pool, :active_connection?
    assert_raises(ActiveRecord::ActiveRecordError) do
      Post.connection
    end
  end
end
```

**Comment by ioquatix** [comment]
It doesn't seem to check out back in:

```
  def test_bare_connection
    # assert_raises(ActiveRecord::ActiveRecordError) do
      post = Post.create!
      post.comments << Comment.create!
    # end

    assert_equal 0, Post.connection_pool.stat[:busy] # fails here
  end
```

**Comment by ioquatix** [comment]
Thanks!
