### ISSUE TITLE
`config.assets.debug` has misleading documentation

### ISSUE THREAD

**Issue by Uaitt** [rails/rails#51747]
### Steps to reproduce

The [config.assets.debug](https://guides.rubyonrails.org/configuring.html#config-assets-debug) documentation on the *Configuring Rails Applications* guide is misleading. 

Citing directly from the text:
**config.assets.debug**
*Disables the concatenation and compression of assets. Set to true by default in development.rb.*

Today I have noticed that a freshly generated app does not have the `config.assets.debug` option set to true in the `config/environments/development.rb` file. It was removed in [this commit](https://github.com/rails/rails/commit/adec7e7ba87e3d268149d0020d54dc211eb02ada) and probably the documentation remained outdated.

Since I have no idea what the documentation for this option should say, I have decided to open an issue instead.

### System configuration
**Rails version**:
7.1.3.2

**Comment by Aqirlone1** [comment]
Will look into it and update if needed
