### ISSUE TITLE
ActiveSupport::KeyGenerator hash digest class differs during and after application initialization

### ISSUE THREAD

**Issue by victordesjardins** [rails/rails#51750]
Since rails 7.0, [default hash digest class](https://guides.rubyonrails.org/configuring.html#config-active-support-key-generator-hash-digest-class) for `ActiveSupport::KeyGenerator` is SHA256. 
This SHA256 hash digest class is set through configuration in an `after_initialize` [as found in ActiveSupport railtie](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/railtie.rb).

The problem is that the source code for `ActiveSupport::KeyGenerator` defines a default SHA1 hash digest class if the configuration hash digest class have not been set up. 
It means that using this `KeyGenerator` during application initialization (with SHA1) differs from using it after initialization (with SHA256).

### Steps to reproduce
In any initializer file, print the hash digest class for `ActiveSupport::KeyGenerator`, let's say in `app/config/initializers/digest_class.rb`

```ruby
p ActiveSupport::KeyGenerator.hash_digest_class
```

Then open a rails console in your local environment with `config.eager_load = true`
=> The initializer will print **SHA1**. 
But if you print the same code in the console, it will print **SHA256**.

### Expected behavior
I would expect the `KeyGenerator` to have the same behaviour during and after initialization. 
Because for instance, if we generate a key in an initializer using `ActiveSupport::KeyGenerator#generate_key`, it will be a key generated with SHA1 hash digest class whereas **we expect it to be generated with a SHA256** hash digest class.

Is there a reason why the hash digest class is set in an `after_initialize` ?

### System configuration
**Rails version**:
7.0.7

**Ruby version**:
3.0.6

**Comment by zzak** [comment]
This is just how config and initialization works, I don't think we can change it.

> The default value depends on the config.load_defaults target version

**Comment by victordesjardins** [comment]
@zzak I understand how initialization works. I just wonder why it necessarily needs to be done in an `after_initialize` ? As long as we want to have SHA256 as default `hash_digest_class`, why don't we set that property before initialization so that we can use it during initialization without change of behaviour ?

**Comment by zzak** [comment]
Maybe it's related to #31651, but most of the initializers in the Active Support railtie are using `after_initialize`.

**Comment by 6temes** [comment]
I've opened a PR to address this: #56746

The fix raises a `RuntimeError` when `key_generator` is accessed before the `key_generator_hash_digest_class` configuration has been applied. This turns the silent misconfiguration into an immediate, actionable error.

Apps that don't configure `key_generator_hash_digest_class` (pre-7.0 defaults) are unaffected.
