### ISSUE TITLE
Inconsistent model state when dumped and loaded with Marshal version 7.1

### ISSUE THREAD

**Issue by benk-gc** [rails/rails#51807]
### Steps to reproduce

We believe we've run across a bug with Marshaling of associations on ActiveRecord models introduced in rails/rails#47747. Since Marshaling is used when caching this affected us via Rails.cache, but I've reproduced the minimal case below using Marshal directly:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def setup
    ActiveRecord::Marshalling.format_version = 7.1

    post = Post.create!
    post.comments << Comment.create!
  end

  def test_association_marshalling
    post = Post.first

    assert_equal false, post.association_cached?(:comments)

    # Stimulate the association_cached? flag set to true.
    post.comments

    # Before being Marshaled `association_cached?` is true which makes `_marshal_dump_7_1`
    # dump the association.
    assert_equal true, post.association_cached?(:comments)
    assert_equal false, post.association(:comments).loaded?

    marshalled_post = Marshal.dump(post)
    loaded_post = Marshal.load(marshalled_post)

    # We expect this to be `false` to be consistent with previous state but it is now `true`.
    assert_equal false, loaded_post.association(:comments).loaded?

    # Because `loaded?` is `true` this does not retrieve a result and returns an empty target.
    assert_instance_of Comment, loaded_post.comments.first
  end
end
```

It appears that because `_marshal_dump_7_1` determines whether to store the association based on `association_cached?` it stores associations which aren't actually loaded. Then, when loading the dumped model, it changes the value of `loaded?` by setting the target, resulting in an incorrect state and an inability to load the association unless forced.

Naively this can be fixed by changing the implementation of `_marshal_dump_7_1` to:

```ruby
def _marshal_dump_7_1
  payload = [attributes_for_database, new_record?]

  loaded_associations = self.class.reflect_on_all_associations.select do |reflection|
    association(reflection.name).loaded?
  end

  unless loaded_associations.empty?
    payload << loaded_associations.map do |reflection|
      [reflection.name, association(reflection.name).target]
    end
  end

  payload
end
```

But I'm unsure of the implications of this. Any suggestions gratefully received!

### Expected behaviour

It is expected that, after loading the Marshaled post, we can retrieve the association correctly per its previous state.

### Actual behavior

Because the loaded model believes the association is already loaded, it returns `nil` unless we force it to return the association with `reload` or by executing another query (e.g. with `.count`)

### System configuration

**Rails version**: 7.1

**Ruby version**: 3.2

**Comment by rafaelfranca** [comment]
@byroot

**Comment by byroot** [comment]
> But I'm unsure of the implications of this.

I think you are correct. I checked the original implementation of this in Paquito, seems like we had this problem all the way down to there.

I think the best fix would be `association_cached?(reflection.name) && association(reflection.name).loaded?`, so that we don't build association objects needlessly. But other than that your suggestion looks good to me.

**Comment by byroot** [comment]
Backported to 7.2 and 7.1.

**Comment by benk-gc** [comment]
Nice, thanks for the quick fix!
