### ISSUE TITLE
Inaccurate docs/comments about ActiveStorage video previewer defaults could be improved

### ISSUE THREAD

**Issue by searls** [rails/rails#51802]
I spent way too long being confused why my app's video previews were _not_ the first frame (despite documentation [here](https://github.com/rails/rails/blob/77909f38be4a4061438000f502da28e546921fbc/activestorage/app/models/active_storage/blob/representable.rb#L51), [here](https://github.com/rails/rails/blob/77909f38be4a4061438000f502da28e546921fbc/activestorage/app/models/active_storage/preview.rb#L6), and [here](https://github.com/rails/rails/blob/77909f38be4a4061438000f502da28e546921fbc/guides/source/active_storage_overview.md?plain=1#L1014)). This was how the video previewer behaved by default prior to 7.0, but was changed in https://github.com/rails/rails/pull/39096 to instead use ffmpeg scene detection to detect a more meaningful frame.

(This change actually results in _worse_ video previews in my case, where the uploaded files are all vertical social media videos created with [CapCut](https://www.capcut.com), whose cover image feature allows users to set the first frame of the video to a static image. As a result, scene detection will typically choose the _subsequent_ frame as the cover image.)

Anyway, it'd be great if we could update the remaining references to "first frame" in all the code comments and guides for ActiveStorage, because it really threw me off the trail—especially since the Active Storage gem itself hard-codes the old default (`-y -vframes 1 -f image2`) in several spots, so I only discovered the new default by debugging the previewer.

I'm opening this as an issue instead of as a PR, because I don't know how to best succinctly summarize the new behavior in each of these spots. Should it link to the PR explaining the change?

**Comment by zzak** [comment]
Is the same true if you aren't using `ffmpeg` with at least the supported version?

Meaning we probably should document both? :shrug:

**Comment by searls** [comment]
@zzak if I read correctly, I think the change effectively raised (or specified) the minimum required ffmpeg version with 7.0 and was why it wasn't backported to 6.1

**Comment by zzak** [comment]
Ahh ok, #42471 helped me make sense of this. I missed that load_defaults hook.

Yeah we should update the doc in those places.

The reason why the old default is [hard-coded](https://github.com/rails/rails/blob/692f25a9254c58c64b138770e6b604e73de38620/activestorage/lib/active_storage.rb#L366) is to avoid a breaking change and to rely on load_defaults instead.

**Comment by zzak** [comment]
> ...uses scene change detection to generate preview images of videos.

Or something to that extent seems reasonable to me.
