### ISSUE TITLE
Default Active Support Logger in Addition to Custom Logger in Rails 7.1 x BroadcastLogger Class in Development environment

### ISSUE THREAD

**Issue by buck4chuka** [rails/rails#51812]
### Steps to reproduce

```ruby
  # Custom logger
     class CustomLogger < ActiveSupport::Logger
    include MessageSerializer

    def info(*msg, &block)
      value = as_hash(msg[0], msg[1], &block)
      super(value, &nil)
    end
    
    config.logger =  ActiveSupport::BroadcastLogger.new(CustomLogger.new)
# Your reproduction script goes here
```

### Expected behavior

Rails.logger.info("message",foo: "foo", bar: "bar")

Should be able to take variable arguments without throwing an error.
Works as expected in production

### Actual behavior

`Rails.logger.info("message",foo: "foo", bar: "bar")`

In local it fails with 
```wrong number of arguments (given 2, expected 0..1)```

I tracked this down to the fact that in local development,
The Broadcast Logger is instantiated with two sinks even when I want only one sink.

```ruby
Rails.logger.broadcasts =>

[#<CustomLogger:0x0000000119402468>
#<ActiveSupport::Logger:0x000000011fdf8b10>]
```

`bundle exec rails s --no-log-to-stdout` does remove the ActiveSupport::Logger but this behaviour is unexpected in my opinion.
If I add a customer logger I expect the Broadcast logger to contain only the sinks that I explicitly included

### System configuration
**Rails version**:
7.1.3
**Ruby version**:
3.2.2

**Comment by rafaelfranca** [comment]
Thank you for the issue.

This is the default behavior of the framework and we have no intention to change it.

`rails s` in development without `--no-log-to-stdout` will add a new logger to the broadcast unless the broadcast is already configured to log to stdout.

If you want, you can make you CustomLogger to report it is logging to STDOUT. See https://github.com/rails/rails/blob/66aeb8a0984e3e32be9d91b14104c93f4998cd15/activesupport/lib/active_support/logger.rb#L20-L31
