### ISSUE TITLE
Storage folder sometimes doesn't need Kamal configuration in Rails 8.0.0.alpha

### ISSUE THREAD

**Issue by jeromedalbert** [rails/rails#51836]
### Steps to reproduce

```
rails new myapp --main --skip-active-storage -d postgresql
cat config/deploy.yml
```

### Expected behavior
`config/deploy.yml` should not configure a persistent storage volume.

### Actual behavior

`config/deploy.yml` is configuring a persistent storage volume in this section:

```
# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "myapp_storage:/rails/storage"
```

### System configuration
**Rails version**: 8.0.0.alpha

**Ruby version**: 3.3.1

### Comments

According to the comment mentioned above in `config/deploy.yml`, a persistent storage volume seems to be needed only for sqlite and local Active Storage. If using a different database and the `--skip-active-storage` option, it doesn't seem needed.

Related: https://github.com/rails/rails/issues/51835
Potential fix: https://github.com/rails/rails/pull/51838

**Comment by yahonda** [comment]
Would you add a test to make sure this option works as expected? I think some tests at https://github.com/rails/rails/blob/main/railties/test/generators/app_generator_test.rb are helpful as a reference.
