### ISSUE TITLE
Release 7.0.8.2 contains broken trix.css

### ISSUE THREAD

**Issue by floriank** [rails/rails#51849]
### Steps to reproduce

1. Go to https://github.com/rails/rails/releases/tag/v7.0.8.2
2. Download a source tarball for the release
3. Unpack locally
4. Open up `./actiontext/app/assets/stylesheets/trix.css`

### Expected behavior
Find the CSS for the trix editor.

### Actual behavior
Well, I found its JS.

### System configuration
**Rails version**: 7.0.8.2

**Ruby version**: v3.1+

---

More seriously, this broke our pipeline* today - I think the release should probably be yanked/amended

Thanks for the hard work! <3

<sub>*and by "broke" I mean it broke asset precompilation as ExecJS/node did not like to be fed with CSS :wink: </sub>

**Comment by rafaelfranca** [comment]
7.0.8.3 is released now

**Comment by floriank** [comment]
Thank you ❤️
