### ISSUE TITLE
Generate Migration - Rename Table

### ISSUE THREAD

**Issue by GitToTheHub** [rails/rails#51865]
Hi,

does a migration generator exists for renaming a table? I didn't find anything in the documentation of `rails generate migration --help` or in the rails guides: https://guides.rubyonrails.org/active_record_migrations.html

Regards,

Manuel

**Comment by fatkodima** [comment]
Hey @GitToTheHub we reserve the Rails Issues tracker for bugs in the framework as we don't have the bandwidth to offer application support. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help with your application. Thanks for understanding.

**Comment by GitToTheHub** [comment]
Hey @fatkodima, thanks for the explanation, I understand this. When there is no functionality for generating a migration for renaming a table, where can i report this. In the Rails forum?

**Comment by fatkodima** [comment]
You can ask on the forum if the feature is something people want to see in the framework. Personally, I don't think it is needed, but maybe someone else think the opposite.

We have some "meta-syntax" for other migration-related generators https://github.com/rails/rails/blob/965b8c372ac0e19021f92cf798095af6046ab140/activerecord/lib/rails/generators/active_record/migration/migration_generator.rb#L28-L42, maybe we can extend it.

**Comment by GitToTheHub** [comment]
Cool, thanks for the code where i can find it. I know that it is not absolutely necessary. It would just be for the sake of completeness.

**Comment by simi** [comment]
> Cool, thanks for the code where i can find it. I know that it is not absolutely necessary. It would just be for the sake of completeness.

AFAIK there is nothing like `completeness` goal in here. There are 2 basic cases guessed from migration name to cover the most used and simple commands.

Renaming table is relatively tricky operation in common production runtime and instead of renaming, you can rename model and point to original table name.

**Comment by GitToTheHub** [comment]
> Renaming table is relatively tricky operation in common production runtime and instead of renaming, you can rename model and point to original table name.

ok, I don’t have much experience here. Why it is a tricky operation?
