### ISSUE TITLE
/Users/amol/.rvm/gems/ruby-2.5.1/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:68: [BUG] Segmentation fault at 0x94000f78d65f0300 ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin23]

### ISSUE THREAD

**Issue by flsdeveloper** [rails/rails#51872]
### Steps to reproduce
-  here is carash report

Process:               ruby [41188]
Path:                  /Users/USER/*/ruby
Identifier:            ruby
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        zsh [1090]
Responsible:           Terminal [582]
User ID:               501

Date/Time:             2024-05-21 11:27:46.5600 +0530
OS Version:            macOS 14.4.1 (23E224)
Report Version:        12
Anonymous UUID:        7CB5F3F7-E375-30CA-61DD-C549910C1D2A

Sleep/Wake UUID:       167CAA0A-ED6C-41F3-A22F-0560F10D6865

Time Awake Since Boot: 50000 seconds
Time Since Wake:       8229 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x7FF89080EA78)

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x94000f78d65f0300 -> 0x00000f78d65f0300 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x94000f78d65f0300

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   ruby [41188]

VM Region Info: 0xf78d65f0300 is not in any region.  Bytes after previous region: 16530630705921  Bytes before following region: 88541449223424
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  reserved VM address space (unallocated)
--->  GAP OF 0x5f9000000000 BYTES
      MALLOC_NANO              600000000000-600020000000 [512.0M] rw-/rwx SM=PRV  

Application Specific Information:
abort() called

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x7FF89080EA78)

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff89080ea78 ???
1   libsystem_kernel.dylib        	    0x7ff80057f14a __pthread_kill + 10
2   libsystem_pthread.dylib       	    0x7ff8005b7ebd pthread_kill + 262
3   libsystem_c.dylib             	    0x7ff8004dda39 abort + 126
4   libruby.2.5.1.dylib           	       0x10d9c8879 die + 9 (error.c:552)
5   libruby.2.5.1.dylib           	       0x10d9c8ab5 rb_bug_context + 565 (error.c:582)
6   libruby.2.5.1.dylib           	       0x10daaeeb1 sigsegv + 81 (signal.c:928)
7   libsystem_platform.dylib      	    0x7ff8005e6fdd _sigtramp + 29
8   ???                           	               0x0 ???
9   libruby.2.5.1.dylib           	       0x10dab67a7 do_hash + 8 (st.c:322) [inlined]
10  libruby.2.5.1.dylib           	       0x10dab67a7 st_lookup + 39 (st.c:1080)
11  libruby.2.5.1.dylib           	       0x10d9b63e8 rb_enc_registered + 42 (encoding.c:640) [inlined]
12  libruby.2.5.1.dylib           	       0x10d9b63e8 rb_enc_find_index + 56 (encoding.c:706)
13  mysql2.bundle                 	       0x10d918d23 mysql2_set_field_string_encoding + 51 (result.c:228)
14  mysql2.bundle                 	       0x10d9181bb rb_mysql_result_fetch_row + 523
15  mysql2.bundle                 	       0x10d918b1d rb_mysql_result_each_ + 429 (r
Air mmo % rails db:migrate
/Users/amol/.rvm/gems/ruby-2.5.1/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:68: [BUG] Segmentation fault at 0x94000f78d65f0300
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin23]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information --------------------------
```

### Expected behavior
<!-- Tell us what should happen -->

### Actual behavior
<!-- Tell us what happens instead -->

### System configuration
**Rails version**: 5.0.2

**Ruby version**: 2.5.1

mysql gem gem 'mysql2', '~> 0.4.10'

**Comment by fatkodima** [comment]
Ruby 2.5 and rails 5 are too old and not supported. Try to update and if the error still happens to open an issue in the mysql2 gem repository.
