### ISSUE TITLE
ActionPack 7.1.3.3  Selenium DriverFinder.path(options, service_class) deprecation is NOT fixed

### ISSUE THREAD

**Issue by vrodic** [rails/rails#51922]
According to https://github.com/rails/rails/commit/8473fe27533d3eded0a2c33e5e28897e06961706, a fix for Selenium webdriver deprecation should have made it in 7.1.3.3. (2024-05-06)  However, release tarballs or gem files do not contain this fix (2024-05-16). 

Fix was commited to 7-1 stable before 7.1.3.3 was released, and after 7.1.3.2 was released. I'm not sure why it did not make it into https://github.com/rails/rails/tree/v7.1.3.3/actionpack. 

This is the message that occurs when running Selenium system tests since selenium-webdriver 4.20

```
WARN Selenium [DEPRECATION] DriverFinder.path(options, service_class) is deprecated. Use DriverFinder.new(options, service).driver_path instead.
```

### System configuration
**Rails version**:
7.1.3.3
**Ruby version**:
3.3.1

**Comment by zzak** [comment]
That's because 7.1.3.3 was a security release, it will make it into 7.1.4 whenever that lands.

For now you can point your app at `7-1-stable`.

**Comment by runephilosof-abtion** [comment]
Contribute to https://github.com/rails/rails/milestones/7.1.4, to get the next minor out faster :)
