### ISSUE TITLE
Command `rails devcontainer` failed - missing templates

### ISSUE THREAD

**Issue by gleonet** [rails/rails#51972]
### Steps to reproduce

1. Installing `gem --version 7.2.0.beta1 rails `
2. `rails new my_app --devcontainer` 
3. Error message: `Could not find ".devcontainer/devcontainer.json" in any of your source paths`

Same error when running the command `./bin/rails devcontainer`

The folder `templates` seems to be missing in `~/.rbenv/versions/3.3.2/lib/ruby/gems/3.3.0/gems/railties-7.2.0.beta1/lib/rails/generators/rails/devcontainer/`

### Expected behavior
Creation of a new app succeed and the configuration for devcontainer is installed

### Actual behavior
Installation of devcontainer or creation of a new app failed

### System configuration
**Rails version**: 7.2.0.beta1

**Ruby version**: 3.3.2

**Comment by rafaelfranca** [comment]
Yeh, that folder doesn't exist, and should not. It seems thor isn't using the right source paths for some reason. I'm looking

**Comment by rafaelfranca** [comment]
Closed by https://github.com/rails/rails/commit/5fea59c0763c83390300a5a26fdd2197673e2689
