### ISSUE TITLE
rails restart doesn't work with puma

### ISSUE THREAD

**Issue by 20ae** [rails/rails#51998]
### Steps to reproduce

```ruby
# Your reproduction script goes here
```

### Actual behavior

```
pkill -f puma
bundle exec puma puma.rb
```

**I executed the commands to restart puma using the puma.rb configuration file, but now the server itself is not working... 😢**
**The logs were recorded before restarting the server, but no logs are being recorded after the restart.**

**<서버 재시작 이전의 로그>**
F, [2024-05-31T00:13:55.698403 #11796] FATAL -- : [65571e93-1da8-479a-9158-65fdbe05af2b] ActionController::RoutingError (No route matches [GET] "/"):
F, [2024-05-31T00:59:46.161702 #11796] FATAL -- : [d675c636-8c35-46bc-8ba5-42f7de5f228c] ActionController::RoutingError (No route matches [GET] "/"):
F, [2024-05-31T01:10:35.833419 #11796] FATAL -- : [232f5305-ec88-4be3-89a3-6e72568409ad] ActionController::RoutingError (No route matches [GET] "/cdn-cgi/trace"):
F, [2024-05-31T01:20:38.073533 #11796] FATAL -- : [4ca4950f-04d6-4f32-b732-f474a613d163] ActionController::RoutingError (No route matches [GET] "/"):
F, [2024-05-31T01:40:34.038187 #11796] FATAL -- : [23291458-741c-45f7-9fc1-9538bb711fb3] ActionController::RoutingError (No route matches [GET] "/owa/auth/logon.aspx"):
F, [2024-05-31T01:45:02.027802 #11796] FATAL -- : [993bc70e-803a-453d-bd72-7db11640a303] ActionController::RoutingError (No route matches [GET] "/actuator/gateway/routes"):
F, [2024-05-31T01:45:21.631071 #11796] FATAL -- : [c66721f0-8195-49e9-8368-9839d7e2cf4b] ActionController::RoutingError (No route matches [GET] "/owa/auth/logon.aspx"):
F, [2024-05-31T02:48:08.693956 #11796] FATAL -- : [9a2f5ca6-8dcd-478a-8717-854905adc4b6] ActionController::RoutingError (No route matches [GET] "/"):
F, [2024-05-31T03:01:52.402733 #11796] FATAL -- : [1294ffb2-1971-4437-ac57-675a7d8d64af] ActionController::RoutingError (No route matches [GET] "/"):
F, [2024-05-31T03:02:04.216789 #11796] FATAL -- : [aaab09e5-be44-485f-a201-63b14fde42c3] ActionController::RoutingError (No route matches [GET] "/"):
F, [2024-05-31T03:20:42.691349 #11796] FATAL -- : [26985619-538c-46c1-8558-abb841841399] ActionController::RoutingError (No route matches [GET] "/"):
F, [2024-05-31T03:37:08.563627 #11796] FATAL -- : [1a46f940-3157-4bf4-aa70-01904d0d4a2e] ActionController::RoutingError (No route matches [GET] "/ab2g"):
F, [2024-05-31T03:37:09.321112 #11796] FATAL -- : [0d490d4f-f4d0-4ce0-af17-fc553d72cebc] ActionController::RoutingError (No route matches [GET] "/ab2h"):
F, [2024-05-31T03:37:10.154971 #11796] FATAL -- : [d1bb5def-ede4-45b3-89c6-a664f3d7a8e9] ActionController::RoutingError (No route matches [GET] "/alive.php"):
### System configuration
**Rails version**:
**Ruby version**:
Using rails-dom-testing 2.0.3
Using rails-html-sanitizer 1.0.4
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.0
Using ruby_dep 1.5.0
Using rails 5.2.2
Using rpush 3.3.1

**Comment by yahonda** [comment]
Hi, Rails 5.2.2 is not supported anymore. Would you upgrade your Rails application to see if it reproduces?

**Comment by Leeyeongae** [comment]
Hi! What is the minimum supported version of Rails? Can I just upgrade Rails? I don't know how to upgrade it.

**Comment by zzak** [comment]
@Leeyeongae The issue tracker here is reserved for bugs with the framework, not help or support with Rails.

You can try asking on [discuss](https://discuss.rubyonrails.org/), and I suggest reading the [upgrade guide](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html).
