### ISSUE TITLE
[ActiveRecord::Encryption] ignores key_provider in with_encryption_context

### ISSUE THREAD

**Issue by dari-us** [rails/rails#52003]
### Steps to reproduce
When using an `ActiveRecord::Encryption.with_encryption_context` block, `ActiveRecord` still uses the global default `key_provider` for encryption/decryption operations (i.e. saving a record or reading a DB record) inside the block.

Use case for this is, inside an `around_action` I want to use a `ActiveRecord::Encryption.with_encryption_context` block with a user-provided key to encrypt their sensitive data (multiple models) and ensure it can only be read by that one user.

In case this is not the intended use of `ActiveRecord::Encryption.with_encryption_context`, is there a way to achieve what I am trying? The key used for encryption/decryption must be user-supplied (i.e. can only be retrieved inside of a Controller; using an option along with `encrypts` inside of the models is not an option).

The below script demonstrates this:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "7.1.3.3"
  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Encryption.config.primary_key = "someprimarykey"
ActiveRecord::Encryption.config.key_derivation_salt = "somesalt"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :messages, force: true do |t|
    t.string :content
  end
end

class Message < ActiveRecord::Base
  encrypts :content
end

class BugTest < Minitest::Test
  def setup
    @key_provider = ActiveRecord::Encryption::DerivedSecretKeyProvider.new("topsecret")
    @content = "some content"
  end

  def setup_database_records
    Message.create!(content: @content)
    ActiveRecord::Encryption.with_encryption_context(key_provider: @key_provider) do
      Message.create!(content: @content)
    end
  end

  def test_encrypted_with_context_raises_without_context
    setup_database_records()
    assert_raises ActiveRecord::Encryption::Errors::Decryption do
      Message.find(2).content
    end
  end

  def test_encrypted_without_context_raises_with_context
    setup_database_records()
    ActiveRecord::Encryption.with_encryption_context(key_provider: @key_provider) do
      assert_raises ActiveRecord::Encryption::Errors::Decryption do
        Message.find(1).content
      end
    end
  end

  def test_manual_encryption_raises_with_different_key_provider
    ciphertext = ActiveRecord::Encryption.context.encryptor.encrypt(@content, key_provider: @key_provider)
    assert_raises ActiveRecord::Encryption::Errors::Decryption do
      ActiveRecord::Encryption.context.encryptor.decrypt(ciphertext)
    end
  end

  def test_manual_encryption_does_not_raise_with_same_key_provider
    ciphertext = ActiveRecord::Encryption.context.encryptor.encrypt(@content, key_provider: @key_provider)
    assert_equal ActiveRecord::Encryption.context.encryptor.decrypt(ciphertext, key_provider: @key_provider), @content
  end
end
```

### Expected behavior
I expect `ActiveRecord` to use the provided `key_provider` for all encryption/decryption operations inside of the `ActiveRecord::Encryption.with_encryption_context` block.

### Actual behavior
`ActiveRecord` still uses the global default `key_provider` for encryption/decryption operations inside of the `ActiveRecord::Encryption.with_encryption_context` block.

### System configuration
**Rails version**:
7.1.3.3

**Ruby version**:
3.3.1

**Comment by rosa** [comment]
@dari-us, I believe this was fixed in https://github.com/rails/rails/pull/51019 (follow-up https://github.com/rails/rails/pull/51324).

**Comment by dari-us** [comment]
@rosa Thanks for the hint, using `gem "rails", github: "rails/rails", branch: "7-1-stable"`, the tests succeed, however, the newest official release `7.1.3.4` still has this problem.
Does anyone know whether there will be a release soon to fix this or will I have to keep using "7-1-stable" or wait until `7.2`? I prefer using an official release over a GitHub branch.

**Comment by zzak** [comment]
@dari-us That was a security fix so it won't include the bug fixes in `7-1-stable` yet, those will come in 7.1.4.

**Comment by dari-us** [comment]
@zzak I see, thanks for clarification, I will wait for 7.1.4 then

**Comment by fletchto99** [comment]
I'm curious if there was ever a regression for this issue? I looks like in rails `7.1.5` (and rails 8) this issue still occurs. I'm trying to simulate a scenario where a key gets lost in the environment via unit tests. Borrowing from the sample code above I created the following which I believe should fail but no error is actually raised (and the message content does get decrypted):

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "7.1.5"
  gem "sqlite3"
  gem "debug"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Encryption.config.key_derivation_salt = "somesalt"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :messages, force: true do |t|
    t.string :content
  end
end

class Message < ActiveRecord::Base
  # Use our custom key provider for encryption
  encrypts :content, key_provider: ActiveRecord::Encryption::DerivedSecretKeyProvider.new("topsecret")
end

class BugTest < Minitest::Test
  def test_encrypted_raises_with_key_provider_context
    message = Message.create!(content: "foo")
    assert_equal true, message.encrypted_attribute?(:content)

    # Create a key provider with a different key than the one used to encrypt the message
    kp = ActiveRecord::Encryption::DerivedSecretKeyProvider.new("lostkey")

    # Pass our new key provider to the encryption context
    ActiveRecord::Encryption.with_encryption_context(key_provider: kp) do

      # We shouldn't be able to decrypt the message because the key provider is different
      assert_raises ActiveRecord::Encryption::Errors::Decryption do
        message.content
      end
    end
  end
end
```
