### ISSUE TITLE
Inconsistent charset case in redirect content type

### ISSUE THREAD

**Issue by joao-esteves** [rails/rails#52025]
When using `redirect` in a route in `config/routes.rb`, the `charset` in the `content-type` header is `UTF-8`. This is inconsistent with most (all?) other content types output by Rails, where it is lowercase (`utf-8`). Rails headers in general seem to be lowercase.

Noticed this while making unit tests, as I had to match an uppercase UTF-8 in a particular test. There might not be any practical effects beyond this. Still, I believe it's better to be consistent, and I can take this small issue myself as a beginner contribution if you think it should be done.

I could not make an executable test case as suggested, there the encoding comes back in lowercase. But when making normal Rails tests (via Minitest or Rspec) it comes as uppercase. This is because the Rails applications needs to initialize for this to happen: it's an initializer that sets the uppercase encoding (`Encoding::UTF_8`).

### Steps to reproduce

1. Make a new Rails app
2. Add `/old` redirect route in `config/routes.rb` such as below
3. Make a request to `/old` and inspect response headers

```ruby
# config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  get "old" => redirect("up")
end
```

### Expected behavior

By `curl --verbose`, both `/old` and `/up` should have `content-type: text/html; charset=utf-8`.

### Actual behavior

By `curl --verbose`, `/up` has `content-type: text/html; charset=utf-8` while `/old` has `content-type: text/html; charset=UTF-8`.

### System configuration

**Rails version**: 8.0.0.alpha (Edge) / 7.1.3.4

**Ruby version**: 3.3.1

**Comment by zzak** [comment]
This is because the default charset is set to the default encoding:
https://edgeguides.rubyonrails.org/configuring.html#config-encoding

https://github.com/rails/rails/blob/c628f7711245ee36ddae9c85b23555b1a342782b/actionpack/lib/action_dispatch/railtie.rb#L60

Which is defined as:
https://github.com/rails/rails/blob/c628f7711245ee36ddae9c85b23555b1a342782b/railties/lib/rails/application/configuration.rb#L32

```
Encoding::UTF_8.to_s #=> "UTF-8"
```

Changing this especially for the sake of consistency is probably not a good reason, if you are writing your tests in Ruby maybe you can try:

```
assert_equal response.charset, Encoding::UTF_8.to_s
```

**Comment by joao-esteves** [comment]
> Changing this especially for the sake of consistency is probably not a good reason

@zzak True. I simply saw an odd behavior and thought I'd get opinions just in case. I found that header keys are recommended to be lowercase by the HTTP spec (and required by Rack 3 afaik), though there seem to be no problems with values. At worst I'd get a bit more experience in this repository.

Since writing this issue I've found that unmatched routes also get the uppercase UTF-8 encoding in their 404 response, which makes changing this even more problematic. I'm fine with the issue being closed if it's not worth it.

**Comment by zzak** [comment]
Yes, rack 3 is strict about the keys being lower-case but not values. Since there is nothing for us to do here, I will close this.

Maybe you can check for [Response#media_type](https://edgeapi.rubyonrails.org/classes/ActionDispatch/Response.html#method-i-media_type)?
