### ISSUE TITLE
Would be nice to be able to specify a table to use for `references` columns when generating a migration

### ISSUE THREAD

**Issue by jagthedrummer** [rails/rails#52022]
### Steps to reproduce

When generating database migrations and models it would be nice to be able to specify the name of the table that should be used for the relationship.

For instance, imagine that a `User` model and table already exists, and you want to scaffold a `Task` model that can be assigned to a user. If you want the name of the attribute to just be `user` you can do this and everything works fine.

```
rails g scaffold Task name:string user:references
```

If you want the name of the attribute to be `assigned_to_user` then you might try this:

```
rails g scaffold Task name:string assigned_to_user:references
```

But the generators assume that you have a model named `AssignedToUser` and a table named `assigned_to_users`.

It would be nice to be able to do something like this (using whatever syntax would be appropriate):

```
rails g scaffold Task name:string assigned_to_user:references{table_name=users}
```

### Expected behavior

If there were a way to indicate the table to be referenced then I'd expect the migration to include a line that looks like this:

```ruby
t.references :assigned_to_user, index: true, foreign_key: {to_table: :users}
```

And for the model to include a line that looks like this:

```ruby
belongs_to :assigned_to_user, class_name: 'User'
```

### Actual behavior

Since there's not currently a way to indicate the table/model to be used for the relationship you end up with a line in the migration that looks like this:

```ruby
t.references :assigned_to_user, index: true, foreign_key: true
```

And a line in the model that looks like this:

```ruby
belongs_to :assigned_to_user
```

When you try to run the migration it fails because there's no table named `assigned_to_users`. And the model contains a `belongs_to` that points to a class that doesn't exist.

### System configuration

**Rails version**: 7.1.3.3

**Ruby version**: 3.3.1

**Comment by rafaelfranca** [comment]
Thank you for the issue. We don't want to complicate the generators and migration helpers to support all possible cases. They are target for the most common cases. For everything else, you can do, but you need to do a little of the work yourself.

**Comment by zzak** [comment]
This came up recently in #46900 and I remembered core saying pretty much exactly this, but I couldn't find the reference to link to it.

Although I think that one is the most full-featured version I have seen, but it does make sense. How often are you generating code for a Rails app that you need a feature complete CLI? Maybe it could lead to drift and become a source of bugs.

**Comment by jagthedrummer** [comment]
Kinda looks like rails core just didn't say anything at all about #46900 which is pretty disappointing.
