### ISSUE TITLE
Database references and ActiveRecord references not match

### ISSUE THREAD

**Issue by JMente** [rails/rails#52021]
### Steps to reproduce

- Create a new project using rails 7.1.3
- Create two tables related example Animals and Toys

Animals migration

```
class CreateAnimals < ActiveRecord::Migration[7.1]
  def change
    create_table :animals do |t|
      t.string :name
      t.timestamps
    end
  end
end
```

Toys migration

```
class CreateToys < ActiveRecord::Migration[7.1]
  def change
    create_table :toys do |t|
      t.string :name
      t.timestamps
    end

    add_reference :toys, :animals, foreign_key: true
  end
end
```

- Add model reference from toys to animals

Toy Model

```
class Toy < ApplicationRecord
  belongs_to :animal
end
```

- Run migrations
- Execute rails console using `rails c`
- Create a new animal `Animal.create(name: "Cat")`
- Create a new toy `Toy.create!(name: "mouse", animal: Animal.first)`
- See error on console

```
can't write unknown attribute `animal_id` (ActiveModel::MissingAttributeError)

          raise ActiveModel::MissingAttributeError, "can't write unknown attribute `#{name}`"
```

- rename model raltion from animal to animals
- see error again:

```
 Missing model class Animals for the Toy#animals association. You can specify a different model class with the :class_name option. (NameError)

            raise NameError.new(message, name)
```

```ruby
# Your reproduction script goes here
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails'
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem 'sqlite3', '~> 1.4'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :animals, force: true do |t|
    t.string :name
  end

  create_table :toys, force: true do |t|
    t.string :name
  end

  add_reference :toys, :animals, foreign_key: true
end

class Animal < ActiveRecord::Base
  has_many :toys
end

class Toy < ActiveRecord::Base
  belongs_to :animal
end

class BugTest < Minitest::Test
  def test_association_stuff
    animal = Post.create!(name: 'Cat')
    animal.toys << Toy.create!(name: 'mouse', animal: animal)

    assert_equal 1, animal.toys.count
    assert_equal 1, Toy.count
    assert_equal animal.id, Toy.first.animal.id
  end
end
```

### Expected behavior

No issues because the migration is correct and the relation is also correct, but according the docs belongs_to will do the magic and foreign_key parameters is optional

### Actual behavior

belongs_to take the name and add the prefix "_id" it complete break the rails way and i know can add the foreign_key param but the idea is this issue is confusing and hard to locate and fix for new rails developers, please do something about it

### System configuration
**Rails version**: 7.1.3

**Ruby version**: 3.1

**Comment by fatkodima** [comment]
Can you create reproduction test scripts using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb template?

**Comment by JMente** [comment]
> Can you create reproduction test scripts using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb template?

Added thanks for the quick reply 🚀

**Comment by fatkodima** [comment]
Because it is a `belongs_to`, you need to use `add_reference :toys, :animal, foreign_key: true`.
