### ISSUE TITLE
ActiveModel::Attributes API with a dynamic default appears to re-use values across instances

### ISSUE THREAD

**Issue by mkdynamic** [rails/rails#52030]
### Steps to reproduce

Define an attribute via the ActiveModel::Attributes API with a dynamic default:

```ruby
class Foo < ApplicationRecord
  attribute :bar, :string, default: -> { SecureRandom.uuid }
end

class Gyp < ApplicationRecord
  has_many :foos
end
```

Instantiate a bunch of new of `Foo` records via the association, specifically I am using `my_gyp.foos.find_or_initialize_by(...)`.

### Expected behavior

The default value lambda is called for every new record, so that every `foo#bar` would be unique.

### Actual behavior

Some of the `my_gyp.foos` records share the same value for `bar`.

### System configuration

**Rails version**: 7.1.3
**Ruby version**: 3.3.0

**Comment by mkdynamic** [comment]
Related: https://github.com/rails/rails/issues/50568

**Comment by mkdynamic** [comment]
I may have a misunderstanding of this API, but is this potentially because the default value is being memoized?

https://github.com/rails/rails/blob/5dabff4b7bf4cc5e2e552efb78c6a3f3e44bed37/activemodel/lib/active_model/attribute/user_provided_default.rb#L17-L23

**Comment by justinko** [comment]
Cannot reproduce. Please try creating an [executable test case](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case).
