### ISSUE TITLE
Chaining where clauses in scopes, behaving differently in rails 7.1 -- Is using merge required now?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [rails/rails#52032]
### Steps to reproduce

1. create a rails project with rails 7.1
2. create a simple scope that chains together multiple where() and append a scope that checks for a boolean value of true

below does not work
```
scope :faster_search, -> (first_name:, last_name:, age:) do
         search_results = where.not(status: [:deceased]).where(first_name: first_name).where(last_name: last_name).active.order(updated_at: :desc)
```

below works
```
scope :faster_search, -> (first_name:, last_name:, age:) do
         search_results = active.where.not(status: [:deceased]).where(first_name: first_name).where(last_name: last_name).active.order(updated_at: :desc)
```

### Expected behavior
the scope would include the entire query, instead of partial results.
### Actual behavior

scope is returning only the first half of the query
### System configuration
**Rails version**:
rails 7.1.2-7.1.3.3
**Ruby version**:
ruby 3.2.4

**Comment by fatkodima** [comment]
Can you create a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb template?

**Comment by RailsCod3rFuture** [comment]
anomaly
