### ISSUE TITLE
ConnectionPool leak connections

### ISSUE THREAD

**Issue by tevvi** [rails/rails#52046]
### Steps to reproduce
Pre-Requirements: you must use mysql2 database adapter
Open `rails c` in stage or dev environment. Then run following snippet:
```ruby
# Fast solution to not clear cache after call fetch_count_mysql_connections because it obtains connection
pid = Process.fork do
  module MockSlowDatabase
    # Let's simulate database connection timeout error, override following method:
    # https://github.com/brianmario/mysql2/blob/0.5.5/ext/mysql2/client.c#L1076
    # https://dev.mysql.com/doc/c-api/8.0/en/mysql-get-server-info.html
    def server_info(...)
      raise 'database connection timeout error'
    end
  end
  
  Object.const_get('Mysql2::Client').class_eval do
    prepend MockSlowDatabase
  end
  
  50.times do
    ActiveRecord::Base.connection
  rescue StandardError
    nil
  end

  puts 'pool stat:'
  puts ActiveRecord::Base.connection_pool.stat
end

def fetch_count_mysql_connections
  ActiveRecord::Base.connection.execute("SELECT COUNT(*) FROM INFORMATION_SCHEMA.PROCESSLIST;").to_a.dig(0, 0)
end

$connections = []
$connections << fetch_count_mysql_connections

$finished = false

Thread.new do
  loop do
    $connections << fetch_count_mysql_connections
    break if $finished
    sleep 1
  end
end

Process.wait pid
$finished = true
sleep 1

puts $connections
```

### Expected behavior
Connection obtained by  `ActiveRecord::Base.connection` saved to connection pool

### Actual behavior
Every call of `ActiveRecord::Base.connection` creates connection in database, but not saves it to pool, so database receives 50 new connections

### Reason why it is a bug
Imagine that you have unstable database or network between rails app and database server
When your application try to obtain new connection in mysql server, rails gem do next:
1. Opens new database connection
https://github.com/rails/rails/blob/v7.1.3.4/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L676
This will cause usual tcp handshake. Connection to database will be obtained even if you have issue with database(slow database)
2. Sends request to receive database version
https://github.com/rails/rails/blob/v7.1.3.4/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L678 \
https://github.com/brianmario/mysql2/blob/0.5.5/ext/mysql2/client.c#L1076 \
https://dev.mysql.com/doc/c-api/8.0/en/mysql-get-server-info.html \
This will cause tcp package to database server. Database server must accept this package, perform command and return back data. So if we have issue with database(database slows down and perform any query more than 1+ minute), then ruby thread will be blocked for a long time.
Imagine that you have timeout(for example rack-timeout gem) 30s, then you will faced with timeout and exception will be raised \
When exeption raised inside `checkout_new_connection`, `conn` variable is unset so `adopt_connection` in `ensure` block works only for case when `checkout_new_connection` returns value
### System configuration
**Rails version**:  6.1.7, but version independent

**Ruby version**: 3.2.2, but version independent

**Mysql version**: 5.7, but problem will be reached for any versions

### Monkeypatch for rails 7.1.3.2
This could also be a solution
```ruby
# This is a changed copy of
# https://github.com/rails/rails/blob/v7.1.3.2/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L689

raise "outdated connection_pool leak monkeypatch" if Rails.version != '7.1.3.2'

# If you faced with this error, that mean rails version is changed in project
# To solve this error open file for current rails version of this project
# https://github.com/rails/rails/blob/v7.1.3.2/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L689
# And investigate connection pool leak is fixed or not
# How to investigate leak fixed or not:
# Open issue
# https://github.com/rails/rails/issues/52046
# And run provided code snipped
# If fixed: delete this file
# if not: investigate changes of methods try_to_checkout_new_connection and new_connection
# Reimplement monkeypatch
# And change rails version in condition above

module ActiveRecord
  module ConnectionAdapters
    class ConnectionPool
      def try_to_checkout_new_connection
        # first in synchronized section check if establishing new conns is allowed
        # and increment @now_connecting, to prevent overstepping this pool's @size
        # constraint
        do_checkout = synchronize do
          if @threads_blocking_new_connections.zero? && (@connections.size + @now_connecting) < @size
            @now_connecting += 1
          end
        end
        if do_checkout
          begin
            # if successfully incremented @now_connecting establish new connection
            # outside of synchronized section
            conn = checkout_new_connection
            conn.pool = self
            conn.check_version
            conn
          rescue ConnectionNotEstablished => ex
            raise ex.set_pool(self)
          ensure
            synchronize do
              if conn
                @thread_cached_conns[connection_cache_key(current_thread)] ||= conn
                adopt_connection(conn)
                # returned conn needs to be already leased
                conn.lease
              end
              @now_connecting -= 1
            end
          end
        end
      end

      def new_connection
        Base.public_send(db_config.adapter_method, db_config.configuration_hash)
      end
    end
  end
end
```

### Monkeypatch for rails 6.1.7
```ruby
# This is a changed copy of
# https://github.com/rails/rails/blob/v6.1.7/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L892

raise "outdated connection_pool leak monkeypatch" if Rails.version != '6.1.7'

# If you faced with this error, that mean rails version is changed in project
# To solve this error open file for current rails version of this project
# https://github.com/rails/rails/blob/v6.1.7/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L892
# And investigate connection pool leak is fixed or not
# How to investigate leak fixed or not:
# Open issue
# https://github.com/rails/rails/issues/52046
# And run provided code snipped
# If fixed: delete this file
# if not: investigate changes of methods try_to_checkout_new_connection and new_connection
# Reimplement monkeypatch
# And change rails version in condition above

module ActiveRecord
  module ConnectionAdapters
    class ConnectionPool
      def try_to_checkout_new_connection
        # first in synchronized section check if establishing new conns is allowed
        # and increment @now_connecting, to prevent overstepping this pool's @size
        # constraint
        do_checkout = synchronize do
          if @threads_blocking_new_connections.zero? && (@connections.size + @now_connecting) < @size
            @now_connecting += 1
          end
        end
        if do_checkout
          begin
            # if successfully incremented @now_connecting establish new connection
            # outside of synchronized section
            conn = checkout_new_connection
            conn.check_version
            conn
          ensure
            synchronize do
              if conn
                @thread_cached_conns[connection_cache_key(current_thread)] ||= conn
                adopt_connection(conn)
                # returned conn needs to be already leased
                conn.lease
              end
              @now_connecting -= 1
            end
          end
        end
      end

      def new_connection
        Base.public_send(db_config.adapter_method, db_config.configuration_hash)
      end
    end
  end
end
```

### Rails 7.1.0.beta1 and higher versions behaviour
This commit changes behaviour of obtaining connection on tcp layer and "defer to first use"
https://github.com/rails/rails/commit/8551e64e2411811f26d210601abdba6e13d8798c

But first use happens on the next line after rails initialize new connection for mysql2 adapter as you can see here:
https://github.com/rails/rails/blob/v7.1.0.beta1/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L673-L675

Bug is still present but also connection obtaining becomes more implicit(but still obtained when you call ActiveRecord::Base.connection without any usage)

### Other database adapters
I tested only mysql adapter, but i think this bug will be present for other adapters too. Just lets check code for postgresql:
https://github.com/rails/rails/blob/v6.1.7/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L426C21-L426C35
Looks like tcp package will be sent too for check version

**Comment by byroot** [comment]
So I'm pretty sure this is no longer a problem on 7.2/main, or at least I couldn't make your script reproduce the issue there.

However I do indeed repro on 7.1, and yes, `ConnectionPool#new_connection` doesn't account for `check_version` potentially failing, and when it happens it leaves the connection not belonging to any pool, so the connection is leaked until GC triggers and close it, which is bad.

We could add the connection to the pool earlier, or we could explicitly and eagerly close it we fail the version check. Given that 7.2+ isn't impacted, this is a backport fix, so I think the eager closing is better as it changes the behavior less.

**Comment by byroot** [comment]
Fixed for 7.1 in https://github.com/rails/rails/pull/52055, and backported to 7.0.

**Comment by byroot** [comment]
What you suggest is pretty much what happens on 7.2, hence why it's not affected.

7.1 is stable, so I don't want to make significant changes to how its connection pooling works, hence why I made a more targeted fix.

**Comment by matthewd** [comment]
> But, when error raised, dont delete connection from pool because tcp connection already obtained.

Sorry, I don't think it's reasonable to expect Rails to operate well in a situation where it's normal for every database query to potentially timeout.

Needing to keep track of exactly which of the initialization queries we've managed to run on a given connection, in the hope that the next request might help us edge closer to having a fully-available connection before it too times out, is a lot of complexity with no real justification.

Put your database server closer to your application, or increase your network/application timeouts to reflect the performance characteristics you expect.

**Comment by tevvi** [comment]
I checked bug in rails v7.2.0.beta2, not reproduced

**Comment by tevvi** [comment]
@sunil-sharma No, you may faced with this issue also with other database servers

**Comment by sunil-sharma** [comment]
Thanks @tevvi 
FYI - your monkey patch reduced errors but still getting a few Connection Pool issues.
