### ISSUE TITLE
Proposal of `Rails.application.message_encryptors` as centralized registry of MessageEncryptor and improved encryption/decryption UX

### ISSUE THREAD

**Issue by feliperaul** [rails/rails#52063]
#44179 implemented a very nice API for `MessageVerifiers` (which is now returned when `Rails.application.message_verifiers`), acting as a registry of `MessageVerifier` instances and easing the key rotation process.

That pull request also introduced the `MessageEncryptors` (note the plural) class for parity; however, it's not being used anywhere in the framework yet. 

So I propose we go all the way with this parity: `Rails.application.message_encryptors` should also exist, and return an instance of ` ActiveSupport::MessageEncryptors` implemented in that pull request. 

This would make encrypting / decrypting data as convenient as signing/verifying messages.

What I mean by that is that we already have this:

```rb
# Already existing API for MessageVerifier
data = Rails.application.message_verifiers("arbitrary_verifier_use_case_name").generate(data)
Rails.application.message_verifiers("arbitrary_verifier_use_case_name").verify(data)
```

So, since we also already have `ActiveSupport::MessageEncryptor` and, since #44179, `MessageEncryptors` as a registry, we should also have something along the lines:

```rb
# New proposed API for MessageEncryptor
data = Rails.application.message_encryptors("arbitrary_encryptor_use_case_name").encrypt_and_sign(data)
Rails.application.message_encryptors("arbitrary_encryptor_use_case_name").decrypt_and_verify(data)
```

The rationale is not only parity;

1. The [current documentation for MessageEncryptor](https://api.rubyonrails.org/v5.2.3/classes/ActiveSupport/MessageEncryptor.html) shows an example that needs the user to handle the concepts of key generator, salt generator and key length on their own; `Rails.application.message_encryptors` would simplify all these concepts just like `Rails.application.message_verifiers` did, using reasonable defaults and deriving keys with secret_key_base as secret and the verifier name as salt.
2. Using `MessageEncryptor` (singular) directly without the use of `MessageEncryptors` (plural) is a recipe for pain when any parameters need to be rotated in the future; however, despite it's existence, `MessageEncryptors` is not yet integrated into the framework in a convenient way, and even googling it's existence is hard. 

Is this a reasonable proposal? If so I can give it a shot. 

Pinging original author @jonathanhefner - please let me know your thoughts; also, if you would like to work on this instead of me, feel free to say so, since it's your prior art.

**Comment by rafaelfranca** [comment]
Yes. Please open a PR. That was the plan but it was never finished. Closing this issue since we don't take proposals in the issue tracker.
