### ISSUE TITLE
[Question] Why doesn't set_pk_sequence! support the parameter for is_called?

### ISSUE THREAD

**Issue by mktktmr** [rails/rails#52082]
Thanks RoR developers!

I have a question for [ActiveRecord::ConnectionAdapters::PostgreSQL::SchemaStatements#set_pk_sequence!](https://github.com/rails/rails/blob/19eebf6d33dd15a0172e3ed2481bec57a89a2404/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L262)

I think `set_pk_sequence!` should support a parameter for `is_called`. 
I mention about third parameter of postgresql `setval` function.

https://www.postgresql.org/docs/current/functions-sequence.html
> SELECT setval('myseq', 42, false);    Next nextval will return 42

I think it is better that like below.

```ruby
def set_pk_sequence!(table, value, is_called = true)
  # ...
  query_value("SELECT setval(#{quote(quoted_sequence)}, #{value}, #{is_called})", "SCHEMA")
```

Why doesn't `set_pk_sequence!` support the parameter for is_called?

**Comment by mktktmr** [comment]
Sorry, I will post this question to https://discuss.rubyonrails.org/.

**Comment by zzak** [comment]
Since `set_pk_sequence!` is not intended to be used by application developers, there is no point to add it.

**Comment by luxiar-MakotoShirakawa** [comment]
@zzak Thank you for replying.
I understood a point that you mention.
If some codes have `:nodoc:`, it means private API, right?

**Comment by mktktmr** [comment]
@zzak Thank you for replying.
I understood a point that you mention.
If some codes have `:nodoc:`, it means private API, right?

**Comment by zzak** [comment]
> If some codes have :nodoc:, it means private API, right?

Correct. It should be explained under [method visibility](https://edgeguides.rubyonrails.org/api_documentation_guidelines.html#method-visibility).

**Comment by mktktmr** [comment]
I've watched the document and understood it.
Thanks for your kindness!
