### ISSUE TITLE
new_framework_defaults initializer for Rails 7.1 not setting ActiveRecord.run_after_transaction_callbacks_in_order_defined

### ISSUE THREAD

**Issue by jdlubrano** [rails/rails#52098]
### Steps to reproduce

I was upgrading a Rails application from Rails 7 to 7.1 and ran into unexpected behavior involving the `ActiveRecord.run_after_transaction_callbacks_in_order_defined` config option.  In `config/initializers/new_framework_defaults_7_1.rb`, I had uncommented the setting such that:

```ruby
Rails.application.config.active_record.run_after_transaction_callbacks_in_order_defined = true
```

I was not, however, seeing `after_commit` callbacks run in the order in which they were defined.  I saw them continuing to run in the reverse order in which they were defined.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "debug"
  gem "rails", ">= 7.1"
  gem "sqlite3", "~> 1.4"
end

require "rails/all"
require "minitest/autorun"

debugger
puts "Rails version: #{Rails::VERSION}"

database = ":memory:"
ENV['DATABASE_URL'] = "sqlite3:#{database}"
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: database)

class App < Rails::Application
  config.eager_load = false
  config.load_defaults 7.0
end

# config/initializers/new_framework_defaults_7_1.rb
Rails.application.initializer "demo.new_framework_defaults" do
  Rails.application.config.active_record.run_after_transaction_callbacks_in_order_defined = true
end

App.initialize!

class BugTest < Minitest::Test
  def test_callbacks_in_order_defined
    assert ActiveRecord.run_after_transaction_callbacks_in_order_defined
  end
end
```

### Expected behavior

`ActiveRecord.run_after_transaction_callbacks_in_order_defined` should be set to `true` and callbacks should run in the order in which they are defined.

### Actual behavior

`ActiveRecord.run_after_transaction_callbacks_in_order_defined` is not set to `true` and after transactional callbacks continue to run in the reverse order of how they are defined.

### System configuration
**Rails version**: 7.1.3.4

**Ruby version**: 3.3.0

### Investigation Notes

I did a little digging into the Rails source.  I noticed that in [`activerecord/lib/active_record/railtie.rb`](https://github.com/rails/rails/blob/2ebb508cd8ee16c0bb280f91b93c01d939fcbf12/activerecord/lib/active_record/railtie.rb#L230-L276), the local variable `configs` is being shadowed and set to a new `Hash` [here](https://github.com/rails/rails/blob/2ebb508cd8ee16c0bb280f91b93c01d939fcbf12/activerecord/lib/active_record/railtie.rb#L245-L260).  That new Hash is then referenced and reused again in the [`after_initialize` hook here](https://github.com/rails/rails/blob/2ebb508cd8ee16c0bb280f91b93c01d939fcbf12/activerecord/lib/active_record/railtie.rb#L233-L241).  I found that a little surprising and wondered if that local variable being "reset" to a Hash was intentional 🤷‍♂️ .  I was surprised that the two hooks within the "active_record.set_configs" would depend on one another _and_ that the first block (as written) would depend on the second block running first to set `configs` to a specific value.

**Comment by TomNaessens** [comment]
Nice find! We encountered the same when upgrading from 6.x defaults to 7.0 defaults. Googling for them + "load order" didn't turn up anything, so I'll list them here hoping they can lead others the way.

For 6.x to 7.0 defaults, this happens specifically for:
- `Rails.application.config.active_record.automatic_scope_inversing`
- `Rails.application.config.active_record.verify_foreign_keys_for_fixtures`
- `Rails.application.config.active_record.partial_inserts`

We've fixed this by defining those in `application.rb` since they get executed before the `set_configs` ActiveRecord railtie is loaded.
