### ISSUE TITLE
[Feature Request][CSP] Support for multiple Content Security Policies

### ISSUE THREAD

**Issue by KirtashW17** [rails/rails#52105]
CSP allows multiple policies: https://developer.mozilla.org/es/docs/Web/HTTP/Headers/Content-Security-Policy#multiple_content_security_policies

It would be nice to be able to define multiple CSPs using the Rails DSL. I think this would be useful when we already have a CSP that is working without the report-only mode, and we want to make changes without breaking nothing. In this case, you could create an additional experimental CSP in report-only mode.

**Comment by p8** [comment]
Hi @KirtashW17,
Sorry, we don't take [feature request](https://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#what-about-feature-requests-questionmark) in the Github issues.

If you'd like feedback on an idea for a feature before doing the work to make a patch, please start a discussion on the [rails-core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core).

**Comment by KirtashW17** [comment]
I see that there is already a discussion on the board:
https://discuss.rubyonrails.org/t/why-cant-i-set-both-content-security-policy-content-security-policy-report-only-headers/83438
