### ISSUE TITLE
ActionCable: Invalid channel causes repeated subscription attempts

### ISSUE THREAD

**Issue by adamdebono** [rails/rails#52110]
When subscribing to an ActionCable channel, if the channel name doesn't exist, Rails doesn't send anything back to the client, which enters an infinite loop where it continually tries to subscribe.

### Steps to reproduce

- Connect to an ActionCable consumer
- Subscribe to a channel that doesn't exist

### Expected behavior

The connection should reject the subscription, so the JS client can stop trying to connect, and run any relevant callbacks.

### Actual behavior

The connection outputs `Subscription class not found: "InvalidChannelName"` to the logs, and nothing is transmitted back to the client.

In the web inspector, we can see the constant stream of connection attempts:

![Screenshot 2024-06-13 at 09 00 21](https://github.com/rails/rails/assets/1049190/21fec748-8b95-4231-aa9a-4a03ecae342b)

From my basic understanding of the internals, this could be fixed transmitting a rejection here: https://github.com/rails/rails/blob/827f4ef15cfde1c42d75ed9521023a5c5cfe91d6/actioncable/lib/action_cable/connection/subscriptions.rb#L46

I'd be happy to submit a PR if this would be acceptable.

### System configuration
**Rails version**: 7.1.3

**Ruby version**: 3.3.1

**Comment by kervin5** [comment]
Wondering if this expected behavior or a bug

**Comment by zzak** [comment]
It's a duplicate of #44652
