### ISSUE TITLE
Some Rails integration tests break with rack 3.1

### ISSUE THREAD

**Issue by Fjan** [rails/rails#52125]
### Steps to reproduce
Any reference to `request.raw_post` will trigger an exception during integration tests. The code works fine, as do system and controller tests.

Apparently this is due to the header 'rack.input' which has now become optional, and will be nil if there is no input: https://github.com/rack/rack/pull/1997

Rails should probably check for existence of that header (or lock to an older rack version)

### Expected behavior
No test failures

### Actual behavior
```
`NoMethodError: undefined method `read' for nil
           /ruby-3.3.1/gems/actionpack-7.1.3.4/lib/action_dispatch/http/request.rb:472:in `read_body_stream'
```

### System configuration
**Rails version**: 7.1.3.4

**Ruby version**: 3.3.1

**Comment by skipkayhil** [comment]
Can you provide a way to reproduce the error you are seeing? My app is running Rack 3.1 on Rails `7-1-stable` and I haven't seen any issues in any `ActionDispatch::IntegrationTest`s

**Comment by Fjan** [comment]
@skipkayhil  Did you use `request.raw_post` in your code? That's all that's needed to reproduce it.

**Comment by willnet** [comment]
Here is the reproducible code.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "www.example.com"
  config.secret_key_base = "secret_key_base"
  config.action_dispatch.show_exceptions = :rescuable
  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
  end
end

class TestController < ActionController::Base
  def index
    request.raw_post
    render plain: "Home"
  end
end

require "minitest/autorun"

class TestControllerTest < ActionDispatch::IntegrationTest

  def test_returns_success
    get "/"
    assert_response :success
  end

  private
    def app
      Rails.application
    end
end
```

**Comment by skipkayhil** [comment]
Thank you both for the reproduction! I think it makes sense that `raw_post` should continue to work (and return `nil`) when `rack.input` is `nil`, so I opened a PR to fix the issue.
