### ISSUE TITLE
Demo video on home page doesn't work as demo'd

### ISSUE THREAD

**Issue by JESii** [rails/rails#52139]
### Steps to reproduce

```ruby
# Your reproduction script goes here
```
No script... just watch the video and try to duplicate the results.

### Expected behavior

Should be able to follow the video, repeat the steps, and have the thing work.
### Actual behavior

Two issues
1. MINOR: The presenter doesn't clear the screen between commands... so you have to fiddle with the video controls, forward and backward, to see the command to be able to duplicate it. Just clear the screen between commands.
2. MAJOR: the demo steps do not work. There's nothing there about installing and configuring the database (PostgreSQL as the default), and finding the correct steps is a complete rabbit hole (2+ hours so far and still not there). Extremely poor form to present a video that purports to show you how to use Rails and then learn that it's fatally flawed. Good thing I've used Rails before; if I weren't committed to figuring out what to do, I'd say: "What a piece of junk this thing is. I'm going elsewhere".

It would have been so easy to make a video with the information required to actually follow the video and get something running.
It could have been as simple as a list of prerequisites.

### System configuration
**Rails version**:
7.1.3.4

**Ruby version**:
4.2.4

**Comment by zzak** [comment]
Thanks for the feedback, but the issue tracker is reserved for bugs in the framework.

If you want to provide additional feedback or request changes, please use [discuss](https://discuss.rubyonrails.org/).
