### ISSUE TITLE
Infinite loop passing form_builder in partial as local after update to 7.1.3.4 (was 7.0.8.4)

### ISSUE THREAD

**Issue by zameo94** [rails/rails#52142]
### Steps to reproduce
When I try to pass the form_builder to a partial as local, I've got an infinite loop with this error:
```
Completed 500  in 1701ms (ActiveRecord: 1314.9ms | Allocations: 163362)



SystemStackError (stack level too deep):

app/views/admin/authors/_form.html.erb:357
```
The code is:

```
<%= form_for [:admin, @author], html: { class: 'form form-horizontal', multipart: true, style: 'margin-bottom: 0' } do |f| %>
  <%= render partial: 'my_partial', locals: { f: f } %>
<% end %>
```
I noticed this problem after updating to Rails 7.1.3.4 (was 7.0.8.4)

### System configuration
**Rails version**: 7.1.3.4

**Ruby version**: 3.3.2

**Comment by gettinDrikkieWithIt** [comment]
Exactly the same issue for me, rendering any partial gives a `stack level to deep`

**Comment by zameo94** [comment]
@gettinDrikkieWithIt only partials with form_builder as locals? the others work for me

**Comment by ccasabona** [comment]
Try using form_with as form_for and form_tag are soft-deprecated.

**Comment by zameo94** [comment]
@ccasabona I tried with form_with, same problem

**Comment by gettinDrikkieWithIt** [comment]
@zameo94 my partial has basic text inside it, not even a form. And still getting this error

**Comment by zameo94** [comment]
@gettinDrikkieWithIt how do you render your partial? can you share the line?

**Comment by nicho1991** [comment]
i get the same, it can be boiled down to almost nothing to replicate

```
= simple_form_for @plane do |form|
  = render 'form_general', locals: { f: form }
```

and just leave whatever partial empty, in this case _form_general

**Comment by zameo94** [comment]
@nicho1991 in my case, when I delete all the references to the form in the partial, it's working

**Comment by zzak** [comment]
Thanks for investigating.

I tried to create a repro script, but the test passes. If you are able to alter the script to fail (only using rails) please feel free. It will help us bisect the offending commit, and determine how to fix.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "minitest/autorun"
require "action_view"

class BugTest < ActionView::TestCase
  def setup
    @controller.append_view_path "."
  end

  def test_stuff
    partial = <<~ERB
      <%= puts f %>
    ERB

    File.write("_partial.html.erb", partial)

    render inline: <<~ERB
      <%= form_with model: false, url: false do |f| %>
        <%= render(partial: 'partial', locals: { f: f }) %>
      <% end %>
    ERB
  end
end
```

**Comment by zameo94** [comment]
@nicho1991 thanks for your message. Actually, after removing the gem `meta_request`, the error disappear 🥳
