### ISSUE TITLE
Add a dummy encryption key for ActiveRecord::Encryption

### ISSUE THREAD

**Issue by matthewford** [rails/rails#52148]
### Steps to reproduce
Running in Docker, we have SECRET_KEY_BASE_DUMMY=1, which skips the check for the master key; ideally, we have something similar for ActiveRecord::Encryption keys, so we do not have to define dummy values for the primary_key etc. Or we could reuse that same dummy key to skip ActiveRecord::Encryption key checks.

If you load your config.active_record.encryption from environment variables, these are typically not available at build time; they are only available on runtime, which throws an error when compiling assets.

### Expected behavior
Assets should compile

### Actual behavior

```
KeyError: key not found: "ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY" (KeyError)
```
### System configuration

**Rails version**:
7.1.3

**Ruby version**:
3.3.1

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.
