### ISSUE TITLE
[ActiveRecord] alias_attribute does not work on methods defined in the superclass

### ISSUE THREAD

**Issue by chaadow** [rails/rails#52144]
Related to https://github.com/rails/rails/pull/52118
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # At the commit that introduced this issue
  gem "rails", github: "rails/rails", ref: 'a2fb85152662751b4055001b6f0b7c1f5c0cb3b3'
  # Or 
  # gem "rails", github: "rails/rails", branch: 'main'

  # Before the commit that introduced this issue ( -1 )
  # gem "rails", github: "rails/rails", ref: '3ec2f1941759cc6eb0935e5f9a9bc176dbb0be0a'

  gem 'sqlite3'
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name
  end
end

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def some_method
    'hello'
  end
end

 # Inherits from a class that defined `#some_method`
class User < ApplicationRecord
  alias_attribute :some_method, :name
end

class BugTest < Minitest::Test
  def test_that_some_method_can_still_be_used_as_alias
    user = User.create!(name: 'chaadow')

    assert_equal 'chaadow', user.some_method
  end
end
```

### Expected behavior
Before https://github.com/rails/rails/pull/52118, alias_attribute would work on methods defined in `ApplicationRecord` ( or any parent class I believe)

calling the aliased method would use the value of the column

### Actual behavior

Right now, it uses the value from ApplicationRecord ( the parent)
```sh
  1) Failure:
BugTest#test_that_some_method_can_still_be_used_as_alias [ruby.rb:50]:
Expected: "chaadow"
  Actual: "hello"
```

### System configuration
**Rails version**: `main` or this `gem "rails", github: "rails/rails", ref: 'a2fb85152662751b4055001b6f0b7c1f5c0cb3b3'`

**Ruby version**: `3.3.3`

**Comment by byroot** [comment]
Can you give a more real world example? Because while I see what's going on, I don't quite understand in which situation you'd write such code.

**Comment by chaadow** [comment]
the real world example is this is a bit of legacy application. and so the idea is
```ruby
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def universal_name = to_s
end
```

then in most models we redefine by using for example `def universal_name = name`

and in particular 3 models, there are `alias_attribute :universal_name, :name` ( instead of redefining the method as usual) 

But I checked, because usually when we use `alias_attribute` it's because we want to use the alias in a `where` query. but they were not used so the fix was easy to do ( although as you've suspected from the `to_s`, <MyModel:x2848923> started to appear in one feature of the app everywhere on the front side 💀 )

The fix was easy ( I just redefined the method instead of using `alias_attribute`) , I also realized we were using the `to_s` feature that Rails provides in reverse. perks of maintaining a 6/7 year old app.

@byroot Honestly, this was just to inform you because it took us by surprise and also thought it might help you, but as far as I'm concerned, if you feel fixing this would make you lose the performance benefit you've added, then by all means, please do close the issue.

**Comment by byroot** [comment]
I'll see if I can preserve the behavior.
