### ISSUE TITLE
Safari 17.5-18 IOs TypeError undefined is not a constructor (evaluating 'new o.WebSocket(this.consumer.url,e)')

### ISSUE THREAD

**Issue by aleksandrlat** [rails/rails#52171]
I see in production this error `TypeError undefined is not a constructor (evaluating 'new o.WebSocket(this.consumer.url,e)')` in Safari 17.5-18 IOs 

The stacktrace:

```
at Connection.open(webpack://swoop/./node_modules/@rails/actioncable/app/assets/javascripts/actioncable.esm.js:165:37)
this.webSocket = new adapters.WebSocket(this.consumer.url, socketProtocols);
at Subscriptions.add(webpack://swoop/./node_modules/@rails/actioncable/app/assets/javascripts/actioncable.esm.js:395:19)
this.consumer.ensureActiveConnection();
at createActionCableHandler(webpack://swoop/./app/assets/javascripts/graphql/createActionCableHandler.js:72:58)
const channel = getActionCableClient().subscriptions.create({
```

From [here](https://github.com/rails/rails/blob/242216803ee73f528b0a74c6bdb367e5b98d8f83/actioncable/app/assets/javascripts/actioncable.esm.js#L3) I see adapters.Websocket can be undefined. But `undefined` case is not handled any how.

**Comment by zzak** [comment]
Are you able to reproduce this locally?

**Comment by aleksandrlat** [comment]
@zzak unfortunately not

**Comment by bheiskell** [comment]
Hey folks,

My team encountered this issue too. With Sentry Replays and manual testing, I _think_ I narrowed this down to people opening our application from SMS links on their Apple Watch. I hacked together a reproducer that confirmed `typeof WebSocket === 'undefined'` with that environment. The watch reports itself as the same user agent as the iPhone, but you can detect its usage via the view port resolution.

I'm sharing this to save folks troubleshooting time in the future. I don't have a strong opinion as to whether rails should do anything special here.
