### ISSUE TITLE
ActionText does not aware of rails_storage_proxy

### ISSUE THREAD

**Issue by artemas** [rails/rails#52190]
https://github.com/rails/rails/blob/5bec50bc70380bb1e70e8fb0a1654130042b1f16/actiontext/app/helpers/action_text/tag_helper.rb#L39

**blob_url_template** should be `rails_service_blob_proxy_url` if Rails.application.config.active_storage.resolve_model_to_route == :rails_storage_proxy

**Comment by zzak** [comment]
Since this is a feature request I'm closing the ticket, let's discuss on the PR.
