### ISSUE TITLE
Is loading secret_key_base from environment no longer possible?

### ISSUE THREAD

**Issue by humphreyja** [rails/rails#52212]
Is there a solution out there for people who store their `secret_key_base` as an environment variable? Hosted key managers (like with Heroku, GitHub, AWS) allows for a minimal amount of people to manage keys and I find it really hard to justify to compliance about keeping secrets stored and committed into a code base. 

We set our `secret_key_base` in **secrets.yaml**. But seeing as that is going away in the next version, there isn't really a solution for us. 

```yaml
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
```

There is a golden rule with encryption....anything that can be decrypted, will be decrypted, given enough time and CPU power. So we aren't comfortable with storing credentials in our committed codebase. For most things, we can just refer to the ENV variable, but from what I can tell, `secret_key_base` looks directly in the credentials file. 

Is there a solution out there for still loading this value from ENV?

### Expected behavior

Be able to set `secret_key_base` from platform env and not stored in committed codebase.

### Actual behavior

Required to store `secret_key_base` in a file that is committed to the codebase.

**Comment by skipkayhil** [comment]
Have you tried reading through the [docs](https://api.rubyonrails.org/)? I think they should answer your question.

If that doesn't work, feel free to ping me and I'll re-open.

**Comment by humphreyja** [comment]
Had to dig for it a bit, wasn't aware of the application checking ENV first, then credentials, then secrets. For anyone else looking for this, here's the link to the docs.  You can just specify the key via `SECRET_KEY_BASE` and skip the credentials file entirely. Moving from `Rails.application.secrets.secret_key_base` to `Rails.application.secret_key_base` is also required.

https://api.rubyonrails.org/classes/Rails/Application.html#method-i-secret_key_base
