### ISSUE TITLE
Rails 7.1 csrf_token_storage breaking changes

### ISSUE THREAD

**Issue by mpvosseller** [rails/rails#52244]
I ran into two issues with the [new `csrf_token_storage` behavior in Rails 7.1+](https://github.com/rails/rails/pull/44283). I'm not sure if these would be considered bugs, "breaking changes", or just "implementation details that shouldn't be depended on" so I wanted to raise them.

1) The CSRF token is silently _not_ stored when using Devise and authentication fails (`authenticate_user!`).

Devise sets the current controller to an instance of [`Devise::FailureApp`]( https://github.com/heartcombo/devise/blob/a259ff3c28912a27329727f4a3c2623d3f5cb6f2/lib/devise/failure_app.rb#L10) which extends `ActionController::Metal` (and not `ActionController::Base`) so it does not respond to `commit_csrf_token` from `ActionController::RequestForgeryProtection` as required on this [line](https://github.com/rails/rails/blob/6045f257fbbff039edb2542c9859488cec0dcaa9/actionpack/lib/action_dispatch/http/request.rb#L452). 

Is this something Devise should fix or if it should be addressed in Rails somehow? I filed a [ticket](https://github.com/heartcombo/devise/issues/5698) with Devise to make them aware of the issue. As described in that ticket my workaround was to `include ActionController::RequestForgeryProtection` in `Devise::FailureApp`. 

2) The CSRF token is written to session much later in the request / response cycle than it was before. In my tests it is now written _after_ the controller action method returns. This means the session (and its session.id) may not be available until after the controller action method returns. This broke a controller method that depended on having a `session.id` present inside the controller action method. We could work around this by writing something to the session ourselves but it was a change in behavior I wanted to raise.

cc: @simbasdad @byroot @rafaelfranca

Thank you!

**Comment by dmatamoroscr** [comment]
I seem to also be running into this issue in prod, but I can't seem to replicate it locally.

**Comment by dmatamoroscr** [comment]
I'm running into sporadic CSRF issues, that seem to go away when the user deletes their cache + cookies. Additionally, if I try to use the cookie CSRF setup, all my integrations tests fail due to CSRF, but everything works fine with the session store
