### ISSUE TITLE
Overriding class methods in concerns do not run on scoped queries such as "where"

### ISSUE THREAD

**Issue by WillTaylor22** [rails/rails#52262]
### Steps to reproduce

```ruby
module MyConcern
  extend ActiveSupport::Concern

  class_methods do

    # Does not work with Model.where(...).update_all
    # This seems to be a bug in rails
    # N.b. this has to be an override for an existing method for the bug to occur, namely tested on update_all
    def self.update_all(updates)
      puts "custom method has run"
    end
  end
end

```

### Expected behavior

Model.update_all(...)
-> "custom method has run"

Model.where(...).update_all(...)
-> "custom method has run"

### Actual behavior

Model.update_all(...)
-> "custom method has run" (correct)

Model.where(...).update_all(...)
->  (only original update_all is called)

### System configuration
**Rails version**:
7.0.3

**Ruby version**:
3.2.2

**Comment by Jay0921** [comment]
@WillTaylor22 The behavior is actually correct. Your `MyConcern` only adds the class method to the `Model` class. However, the result of `Model.where(...)` is an instance of `ActiveRecord::Relation`, not the `Model` class. Therefore, the `update_all` method in the concern won't get called. To override the `update_all` method, the easiest way I can think of is to monkey patch it.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: "rails/rails", branch: "main"
  gem "sqlite3", "~> 1.4"
end

require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

module CustomUpdateAll
  def update_all(updates)
    puts "custom method has run"
    super
  end
end

ActiveRecord::Relation.prepend(CustomUpdateAll)

class Post < ActiveRecord::Base
end

puts "Post.where(id: nil).class: #{Post.where(id: nil).class}"
# => Post::ActiveRecord_Relation
Post.update_all(title: "hello")
Post.where(id: nil).update_all(title: "hello")
```

**Comment by kabirpathak** [comment]
@WillTaylor22 ideally the following code should fail with  `NoMethodError` because of the usage of `self`. Can you please confirm if that is the case? 

```ruby
class_methods do
  def self.update_all(updates)
     puts "custom method has run"
  end
  
  > Post.update_all(attr: 'val')
```

**Comment by fatkodima** [comment]
@Jay0921 is correct.
