### ISSUE TITLE
No number_to_rounded method present

### ISSUE THREAD

**Issue by morgoth** [rails/rails#52270]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # If you want to test against edge Rails replace the previous line with this:
  gem "rails", github: "rails/rails", branch: "main"
end

require "minitest/autorun"
require "action_view"

class BugTest < ActionView::TestCase
  def test_no_number_to_rounded
    render inline: <<~ERB
      <p><%= number_to_rounded(10) %></p>
    ERB

    element = rendered.html.at("p")

    assert_equal element.text, "10"
  end
end

```

### Expected behavior
Works as documented https://edgeapi.rubyonrails.org/classes/ActiveSupport/NumberHelper.html#method-i-number_to_rounded

### Actual behavior
ActionView::Template::Error: undefined method `number_to_rounded' for <#<Class:0x00007adea9409ce8>:0x00007adea9e54f18>

### System configuration
**Rails version**: main

**Ruby version**: 3.3.2

**Comment by Jay0921** [comment]
@morgoth The `number_to_rounded` method is part of `ActiveSupport::NumberHelper`, so you can't directly use it in the view. Alternatively, you can use the [number_with_precision](https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_with_precision) method from `ActionView::Helpers::NumberHelper`. Under the hood, the `number_with_precision` method delegates the call to `number_to_rounded`.

https://github.com/rails/rails/blob/4fa56814f18fd3da49c83931fa773caa727d8096/actionview/lib/action_view/helpers/number_helper.rb#L79-L89

**Comment by p8** [comment]
I guess these should list the same numbers?
https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html
https://edgeapi.rubyonrails.org/classes/ActiveSupport/NumberHelper.html

**Comment by p8** [comment]
Updating documentation could be a "good first issue".

**Comment by kabirpathak** [comment]
@p8 @akhilgkrishnan  Can you please assign this to me? I'd like to take this up.

**Comment by akhilgkrishnan** [comment]
> @p8 @akhilgkrishnan Can you please assign this to me? I'd like to take this up.

We don't normally assign the tickets, you can directly work on the issues.
