### ISSUE TITLE
NumericalityValidator - only_integer option should allow to use values like 4.0

### ISSUE THREAD

**Issue by MisterBolt** [rails/rails#52286]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "active_model"
require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"

class BugTest < Minitest::Test
  class TestModel
    include ::ActiveModel::Validations

    attr_accessor :position

    validates :position, numericality: { only_integer: true }

    def initialize(position)
      @position = position
    end
  end

  def test_stuff
    refute TestModel.new(4.0).valid?
    assert TestModel.new(4).valid?
    assert_equal 4, 4.0
  end
end
```

### Expected behavior
I think that NumericalityValidator - only_integer option shouldn't raise error for 4.0 value if `4 == 4.0` is true.
```
INTEGER_REGEX = /\A[+-]?\d+[.]?0*\z/
```

**Comment by Jay0921** [comment]
@MisterBolt The current behavior is correct. The reason why `4 == 4.0` returns true is because it performs type conversions under the hood. You should use `eql?` instead of `==` to ensure that numbers have the same type and equal values.

**Comment by fidalgo** [comment]
@MisterBolt The definition comes from the maths where 4 is an integer and 4.0 is a real number: https://mathmonks.com/integer/real-numbers-vs-integers
@Jay0921 provided an option to achieve your desired result.
