### ISSUE TITLE
ActionController::Parameters#values returns an array of ActionController::Parameters objects for nested hashes

### ISSUE THREAD

**Issue by chimpanstache** [rails/rails#52294]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"
require "minitest/autorun"

class BugTest < Minitest::Test
  def test_strong_parameters
    hash = {
      "foo" => { "ruby"=>2, "rails"=>2 }
    }

    unexpected_result = [ActionController::Parameters.new({ "ruby"=>2, "rails"=>2 })]
    expected_result =  [{ "ruby"=>2, "rails"=>2 }]

    # passes
    assert ActionController::Parameters.new(hash).values.eql?(unexpected_result)

    # fails
    assert ActionController::Parameters.new(hash).values.eql?(expected_result)
  end
end
```

### Expected behavior
`ActionController::Parameters.new(hash).values` should return ` [{ "ruby"=>2, "rails"=>2 }]`

### Actual behavior

It actually returns `[ActionController::Parameters.new({ "ruby"=>2, "rails"=>2 })]`
### System configuration
**Rails version**:
This seem to be happening since 7.1.0. It is working as expected on 7.0.8.3
**Ruby version**:
3.2.3

**Comment by fatkodima** [comment]
Since https://github.com/rails/rails/commit/c7adce2d8e649c2e95ae7efe0c249dd7d48fa876

The definition of `eql?` changed and `ActionController::Parameters.new(hash).values[0].class` is/was `ActionController::Parameters` (not `Hash`), so this is now a correct behaviour. 
cc @jhawthorn to confirm

**Comment by chimpanstache** [comment]
Not sure that I understand, but `ActionController::Parameters.new(hash).values[0].class` was `ActiveSupport::HashWithIndifferentAccess` in rails 7.0.8.3 right ?

**Comment by fatkodima** [comment]
Yes.
