### ISSUE TITLE
Relax the sqlite3 dependency for Rails 7.1

### ISSUE THREAD

**Issue by voxik** [rails/rails#52309]
### Steps to reproduce

Sqlite3 dependency in `main` branch was relaxed in #51592. Would it be possible to relax this dependency also for Rails 7.1+ or are there some incompatibilities?

### Expected behavior

Sqlite3 can be use as a dependency of Rails 7.1 app

### Actual behavior

Only `sqlite3 ~> 1.4` can be use as a dependency of Rails 7.1 app

**Comment by voxik** [comment]
BTW I am asking, because there is system sqlite-3.46.0 currently in Fedora Rawhide, which is not compatible with older sqlite3 gems in [minor ways](https://github.com/sparklemotion/sqlite3-ruby/pull/504).

**Comment by voxik** [comment]
Actually, I would not mind even Rails 7.0 support 😇

**Comment by yahonda** [comment]
https://github.com/rails/rails/commit/3271c4f6d221a73af801d7d57905f0cece374e05 has been merged to 7-1-stable then it will be included once the newer version of Rails 7.1.z is released.

**Comment by ghiculescu** [comment]
> [3271c4f](https://github.com/rails/rails/commit/3271c4f6d221a73af801d7d57905f0cece374e05) has been merged to 7-1-stable then it will be included once the newer version of Rails 7.1.z is released.

Closing as resolved.
