### ISSUE TITLE
enable_extension in schema dump doesn't contain schema name

### ISSUE THREAD

**Issue by afn** [rails/rails#52312]
Although [enable_extension](https://apidock.com/rails/v7.1.3.2/ActiveRecord/ConnectionAdapters/PostgreSQLAdapter/enable_extension) allows a schema name to be specified for the extension, the schema dumper doesn't include the schema name in the generated `enable_extension` call.

### Steps to reproduce

Run the below migration, and then run `rails db:migrate`.

```ruby
class EnablePostgisExtension < ActiveRecord::Migration[7.1]
  def change
    create_schema 'myschema'
    enable_extension 'myschema.postgis'
  end
end
```

### Expected behavior

Expect `db/schema.rb` to contain:

```ruby
  enable_extension "myschema.postgis"
```

### Actual behavior

`db/schema.rb` contains:

```ruby
  enable_extension "postgis"
```

### System configuration
**Rails version**: current `main` (36b2dbfc1d722128c05eb6d6506c7d435ba5b55d)

**Ruby version**: 3.3.2

**Comment by afn** [comment]
I think this can be addressed by the above PR — let me know if this looks reasonable, and I can add corresponding tests.

I've also noticed a few things while setting up this test case:

1. The `disable_extension` method doesn't appear to handle schema names, so rolling back a migration with `enable_extension` with a named schema doesn't actually drop the extension. I can add a fix for this in the same PR or in a separate one if this is considered a separate issue.
2. Perhaps this is unintentional, but `create_schema` is not handled by the command recorder, but rather executed as-is. Are schemas not meant to be created in migrations?

**Comment by yahonda** [comment]
Thanks for the review.

> The disable_extension method doesn't appear to handle schema names, so rolling back a migration with enable_extension with a named schema doesn't actually drop the extension. I can add a fix for this in the same PR or in a separate one if this is considered a separate issue.

The `disable_extension` method is also schema name aware, but the generated SQL statements handle schema names differently.
While `enable_extension` uses "create extension if not exists ... schema ...", `drop_extension` just calls the extension name like "schema_name.extension_name".
Would you open another pull request to make `disable_extension` handle schema name the same way as `enable_extension` does?

```ruby
class EnableHStoreExtension2 < ActiveRecord::Migration[8.0]
  def up
    create_schema 'testschema'
    enable_extension 'testschema.hstore'
  end
  def down
    disable_extension 'testschema.hstore'
    drop_schema 'testschema'
  end
end
```

- bin/rails db:migrate that calls up method
```sql
CREATE SCHEMA "testschema"
CREATE EXTENSION IF NOT EXISTS "hstore" SCHEMA testschema
```

- bin/rails db:rollback that calls down method
```sql
DROP EXTENSION IF EXISTS "testschema.hstore"
DROP SCHEMA "testschema" CASCADE
```

**Comment by afn** [comment]
> The `disable_extension` method is also schema name aware, but the generated SQL statements handle schema names differently. While `enable_extension` uses "create extension if not exists ... schema ...", `drop_extension` just calls the extension name like "schema_name.extension_name".

That's actually incorrect --- weirdly, `DROP EXTENSION` [doesn't accept a schema name](https://www.postgresql.org/docs/current/sql-dropextension.html).

> Would you open another pull request to make `disable_extension` handle schema name the same way as `enable_extension` does?

I'll follow up shortly with a PR that makes `enable_extension` reversible and allows `drop_extension` to take a schema name (which will get chopped off in the generated SQL).

**Comment by afn** [comment]
Sorry, I mean makes `create_schema` reversible.

**Comment by afn** [comment]
See PRs #52451 and #52452
