### ISSUE TITLE
ActiveRecord::AttributeMethods::Serialization::ClassMethods.serialize is not backwards compatible 7.0 -> 7.1

### ISSUE THREAD

**Issue by jprosevear** [rails/rails#52336]
### Steps to reproduce

Call serialize with Hash as the second positional argument:

https://github.com/simukappu/activity_notification/blob/dd8d68188647abf6cfc2b54ce51c6ab985548859/lib/activity_notification/orm/active_record/subscription.rb#L17

### Expected behavior
Use YAML encoder as per Rails 7.0
https://github.com/rails/rails/blob/7-0-stable/activerecord/lib/active_record/attribute_methods/serialization.rb#L112C13-L112C67

### Actual behavior

Throws error:

```
/Users/jpr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/attribute_methods/serialization.rb:208:in `serialize': missing keyword: :coder If no default coder is configured, a coder must be provided to `serialize`. (ArgumentError)

            raise ArgumentError, <<~MSG.squish
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /Users/jpr/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/activity_notification-2.3.0/lib/activity_notification/orm/active_record/notification.rb:48:in `<class:Notification>'
```

### System configuration
**Rails version**:
7.1.3.4

**Ruby version**:
3.3.4

**Comment by jprosevear** [comment]
I suspect appending after https://github.com/rails/rails/blob/77dfa65392e672ac83ced68cda37d5770c16ea6c/activerecord/lib/active_record/attribute_methods/serialization.rb#L202 something like:

```
coder = Coders::YAMLColumn.new(attr_name, class_name_or_coder)
```

is the right move

**Comment by fatkodima** [comment]
Provide us a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb template.

**Comment by ruyrocha** [comment]
This is the test script:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: "rails/rails", branch: "7-1-stable"
  # gem "rails", github: "rails/rails", branch: "main"
  # gem "rails", path: "~/GitHub/rails"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :subscriptions, force: true do |t|
    t.text :optional_targets
  end
end

class Subscription < ActiveRecord::Base
  serialize :optional_targets, Hash
end

class BugTest < Minitest::Test
  def test_serialize_exception_on_serializer
    subscription = Subscription.create!(optional_targets: { color: "red" })

    assert_equal Subscription.first, subscription
  end
end
```

I'm afraid it only displays the deprecation warning message:

```
DEPRECATION WARNING: Passing the class as positional argument is deprecated and will be removed in Rails 7.2.

Please pass the class as a keyword argument:

  serialize :optional_targets, type: Hash
 (called from <class:Subscription> at run-52336.rb:28)
Run options: --seed 43065
```

**Comment by skipkayhil** [comment]
This is behaving as expected with [`load_defaults 7.1`](https://edgeguides.rubyonrails.org/configuring.html#config-active-record-default-column-serializer). If you use `load_defaults 7.0` (or configure `config.active_record.default_column_serializer` manually) then you get the deprecation warning above.

**Comment by jprosevear** [comment]
The warning is expected, the crash is not.   I have been trying to write a minimal test script, but the issue seems complex - an AR loading another AR through an engine and have not been able to minimize the test case yet.

**Comment by jprosevear** [comment]
Fixed up stream
