### ISSUE TITLE
PostgreSQL array not decrypting 

### ISSUE THREAD

**Issue by JDrizzy** [rails/rails#52331]
### Steps to reproduce

1. Create new rails app with postgresql as db
2. Add a string array field to model via migration
3. Encrypt array field
4. Creating or updating the array field raises exception `ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  malformed array literal`

#### Executable Test Case

Test script
```Ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem 'activerecord', '7.1.3.4'
  gem 'pg'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'postgresql', database: 'array-test')
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Encryption.configure \
  primary_key: 'nYlllafgBdhQ7Vn37dlWAoqfDbTPl4Fl',
  deterministic_key: 'CK7x2oUEeu06bKehhKGiKYAHoytPaOPg',
  key_derivation_salt: 'Fol1dR03ZXnL8k4hEUYj7IMr0UlgOMHC'

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :tags, array: true, default: []
  end
end

class Post < ActiveRecord::Base
  encrypts :tags
end

class BugTest < Minitest::Test
  def test_creating_record_with_array
    post = Post.create!(tags: ["tag1", "tag2"])
    assert_equal ["tag1", "tag2"], post.tags
  end
end
```

### Expected behavior

The array value should be stored encrypted and then retrieved decrypted.

### Actual behavior

Exception is thrown: `ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  malformed array literal`

### System configuration
**Rails version**: 7.1.3.4

**Ruby version**: 3.1.0

**Comment by ghiculescu** [comment]
Hmm, I'm not sure if this is expected to work. Nothing in https://guides.rubyonrails.org/active_record_encryption.html suggests arrays are supported. https://guides.rubyonrails.org/active_record_encryption.html#supported-types says **they must be serializable as strings**. And https://guides.rubyonrails.org/active_record_encryption.html#important-about-storage-and-column-size talks about string/text columns only.

**Comment by ghiculescu** [comment]
You may be better off putting a proposal for a new feature in https://discuss.rubyonrails.org/.
