### ISSUE TITLE
Behaviour of `autosave` associations has changed on edge

### ISSUE THREAD

**Issue by ghiculescu** [rails/rails#52332]
### Steps to reproduce

This script has different output between `7-2-stable` and `main`:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # gem "rails"
  # gem "rails", github: "rails/rails", branch: "7-2-stable"
  gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.integer :address_id
    t.timestamps
  end

  create_table :addresses, force: true do |t|
    t.text :country
    t.timestamps
  end
end

class User < ActiveRecord::Base
  belongs_to :address, autosave: true
end

class Address < ActiveRecord::Base
  has_one :user
end

class BugTest < Minitest::Test
  def test_bad
    user = User.create!(address: Address.new(country: "USA"))

    user.create_address(country: "Australia")

    assert_equal "Australia", User.find(user.id).address.country
  end

  def test_fine
    user = User.create!(address: Address.new(country: "USA"))

    user.address.update!(country: "Australia")

    assert_equal "Australia", User.find(user.id).address.country
  end
end

```

### Expected behavior

Both tests should pass.

### Actual behavior

`test_bad` fails on `main` but not `7-2-stable`.

Admittedly, it's not a good way of writing the code, because the "USA" `Address` record is orphaned as a result. But I think this is still a regression.

### System configuration
**Rails version**: `main`

**Ruby version**: 3.2

**Comment by ghiculescu** [comment]
Tagging you in here @joshuay03 

Similar to https://github.com/rails/rails/pull/49847#issuecomment-2222043763, this passes on https://github.com/rails/rails/commit/cacf96ecd053f0a3d64c7bf478dac63f98e6aa6d but fails with 16f1222753cac0a554a2acd8f4ffa3f23d51d945.

**Comment by joshuay03** [comment]
> Tagging you in here @joshuay03
> 
> Similar to [#49847 (comment)](https://github.com/rails/rails/pull/49847#issuecomment-2222043763), this passes on [cacf96e](https://github.com/rails/rails/commit/cacf96ecd053f0a3d64c7bf478dac63f98e6aa6d) but fails with [16f1222](https://github.com/rails/rails/commit/16f1222753cac0a554a2acd8f4ffa3f23d51d945).

Thanks! I've got a fix in https://github.com/rails/rails/pull/52333, however I'm now a bit concerned that there are more untested cases out there that my original changes don't account for...

**Comment by composerinteralia** [comment]
> However, I'm now a bit concerned that there are more untested cases out there that my original changes don't account for...

You might be right. We're seeing a bunch of test failures around this at GitHub. @ronricardo put together a reproduction for one of our failures:

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Passes with either autosave: true or autosave: nil
  # gem "rails", github: "rails/rails", ref: "78ce2994b23b4b68db07a910df252284f1d18954"

  # Fails with autosave: true or autosave: nil
  # gem "rails", github: "rails/rails", ref: "16f1222753cac0a554a2acd8f4ffa3f23d51d945" # https://github.com/rails/rails/pull/49847

  # Half fixed: Passes with autosave: nil, but still fails with autosave: true
  gem "rails", github: "rails/rails", ref: "56fbc632a378acc40d99f5b4be321f80a5d8b8c4" # https://github.com/rails/rails/pull/52333

  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :pull_requests, force: true do |t|
  end

  create_table :issues, force: true do |t|
    t.integer :pull_request_id
  end
end

class PullRequest < ActiveRecord::Base
  has_one :issue#, autosave: true
end

class Issue < ActiveRecord::Base
  belongs_to :pull_request
end

class BugTest < Minitest::Test
  def test_issue_is_autosaved_when_pull_request_is_set_on_issue
    pull_request = PullRequest.new
    issue = Issue.new

    issue.pull_request = pull_request
    pull_request.save!

    assert_predicate pull_request.issue, :persisted?
  end
end
```

**Comment by joshuay03** [comment]
Thanks for the report @composerinteralia

I came up with an alternative fix in https://github.com/rails/rails/pull/52412 which your script and all the regression tests I've added so far pass against. I think it's a much better implementation than the current one now that I understand the root cause behind these regressions. Could you please let me know if you still have any issues against that ref?
