### ISSUE TITLE
ActiveRecord: Issue with NULL insertion for serialized empty arrays causing database constraint violations

### ISSUE THREAD

**Issue by iberianpig** [rails/rails#52340]
After upgrading Rails from 7.0 to 7.1, an issue arises when using a customized Coder to serialize and save empty arrays in ActiveRecord. The saved value is inserted as NULL, violating the database's `NOT NULL` constraint. This behavior does not occur in Rails 7.0.

### Steps to reproduce
The following code snippets demonstrate the issue.

This example uses a customized `Coder` class to serialize and deserialize the `col_array` column.

Run the following test code:

```ruby
begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "rails", path: "."
  gem "sqlite3", "~> 1.4.0"
  gem "debug"
end

require "rails/all"

class TestApp < Rails::Application
  config.load_defaults 7.0
  config.colorize_logging = false
end

ENV["DATABASE_URL"] = "sqlite3::memory:"

puts ENV["DATABASE_URL"]

Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :col_array,            default: "", limit: 255, null: false
  end
end

class Post < ActiveRecord::Base
  class Coder
    def self.dump(value)
      value&.join(',')
    end

    def self.load(string)
      string&.split(',')&.map(&:to_i)
    end
  end

  serialize :col_array, coder: Coder, type: Array # NG
  # serialize :col_array, coder: Coder # OK
end

require "minitest/autorun"

class BugTest < Minitest::Test
  def test_save_with_blank_array
    query_logs = []
    capture_query_logs = -> (&block) do
      ActiveRecord::Base.logger.stub(:debug, ->(msg) { query_logs << msg }) { block.call }
    end

    capture_query_logs.call do
      begin
        post = Post.new
        assert_equal post.col_array, []
        post.save!
        assert_equal post.reload.col_array, []
      rescue ActiveRecord::NotNullViolation => e
        # for example with MySQL:  "Mysql2::Error: Column 'col_array' cannot be null"

        puts e.message
      end
    end

    insert_query = query_logs.find { |log| log.include?("INSERT INTO") }

    assert_includes insert_query, %q{INSERT INTO "posts" ("col_array") VALUES (?)}
    assert_includes insert_query, %q{[["col_array", ""]]} # <- fail in Rails 7.1

    # Actual SQL
    #  INSERT INTO "posts" ("col_array") VALUES (?) [["col_array", ""]] # OK in Rails 7.0
    #  INSERT INTO "posts" ("col_array") VALUES (?) RETURNING "id"  [["col_array", nil]] # NG in Rails 7.1
    #                                                                              ^^^ want it to be ""
  end

  def test_save
    post = Post.new(col_array: [1, 2, 3])
    assert_equal [1, 2, 3], post.col_array
    post.save!
    assert_equal [1, 2, 3], post.reload.col_array
  end
end
```

### Expected behavior

When saving an empty array, it should be stored as an empty string, not NULL.

### Actual behavior

The empty array is being stored as NULL, leading to errors due to the `NOT NULL` constraint violation.

### System configuration

- Rails: 7.1.0
- Ruby: 3.3.1
- Database: MySQL, SQLite

### Additional Information
Using `git bisect`, the problematic commit was identified as follows: [c4c0b799e464942e26b928817a8cef5f8578c688](https://github.com/rails/rails/commit/c4c0b799e464942e26b928817a8cef5f8578c688). This commit was introduced in the following PR: [rails/rails#47482](https://github.com/rails/rails/pull/47482).

```
Finished in 0.014410s, 138.7930 runs/s, 485.7755 assertions/s.
2 runs, 7 assertions, 1 failures, 0 errors, 0 skips
c4c0b799e464942e26b928817a8cef5f8578c688 is the first bad commit
commit c4c0b799e464942e26b928817a8cef5f8578c688
Author: Jean Boussier <jean.boussier@gmail.com>
Date:   Thu Feb 23 16:57:22 2023 +0100

    Serialized attribute should be able to be defined in abstract classes

    Ref: https://github.com/rails/rails/pull/47191

    This feature recently regressed when https://github.com/rails/rails/pull/47191
    was merged to handle defaults.

    The `attribute` definition callback is set on the parent class and
    is triggered when the child class schema is loaded.

    I don't know if this is fixable.

 .../attribute_methods/serialization.rb             |  2 +-
 activerecord/lib/active_record/type/serialized.rb  |  5 +--
 .../test/cases/serialized_attribute_test.rb        | 51 ++++------------------
 3 files changed, 12 insertions(+), 46 deletions(-)
```

**Comment by reedstonefood** [comment]
As far as I can tell, there are several places in `Coder` / `Serialized` sections of the codebase where there is an assumption that a value of `nil` will be stored as `nil` in the database. This is incorrect in your case, and also in my case (hashes stored as serialized YAML) which I will be posting up later this week.

I've put together a fix for my case; unfortunately it doesn't fix yours as well.

**Comment by oday-k** [comment]
> As far as I can tell, there are several places in `Coder` / `Serialized` sections of the codebase where there is an assumption that a value of `nil` will be stored as `nil` in the database. This is incorrect in your case, and also in my case (hashes stored as serialized YAML) which I will be posting up later this week.
> 
> I've put together a fix for my case; unfortunately it doesn't fix yours as well.

@reedstonefood 
I'm facing a similar issue to what you faced, can you share your fix to see if I can get it working?
