### ISSUE TITLE
Leveraging button form attribute to simplify front-end integration

### ISSUE THREAD

**Issue by francis-schiavo** [rails/rails#52360]
Hello,

currently when using `button_to` the generated html looks like this:

```html
<form class="button_to" method="post" action="/event_types/5">
  <input type="hidden" name="_method" value="delete" autocomplete="off">
  <button class="btn btn-danger btn-sm" type="submit">Delete</button>
  <input type="hidden" name="authenticity_token" value="CSRF-TOKEN" autocomplete="off">
</form>
```

This requires some workaround when working with Bootstrap (or any other CSS framework) since it wraps the button with a form element.
HTML5 allows us to tie a button to a form by passing the form `id` to the button's `form` attribute. Something similar to this:

```html
<button class="btn btn-danger btn-sm" type="submit" form="MyForm">Delete</button>

<form class="button_to" method="post" action="/event_types/5" id="MyForm">
  <input type="hidden" name="_method" value="delete" autocomplete="off">
  <input type="hidden" name="authenticity_token" value="CSRF_TOKEN" autocomplete="off">
</form>
```

I figure we could probably generate a random id to connect the tags and even add some inline css or a default class to the form an make it easier to completely hide the form.

My question is: is there any particular reason for the current design ? Could we change the current behavior or add a way to customize the html generation ?

I would be glad to work on this if it is an acceptable feature.

**Comment by felipedmesquita** [comment]
The current design outputs simpler code and does not need to generate an id for the form tag.
If your layout requires, you can also style the form element using the `:form_class` [option](https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-button_to).
