### ISSUE TITLE
Callbacks / Validations not running for `accepts_nested_attributes_for` relation on certain values, but will run on other values, or when another value is saved together with the problematic value, or when updating the record directly

### ISSUE THREAD

**Issue by josesei** [rails/rails#52372]
### Steps to reproduce
```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org/"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 6.1.7.8"
  gem "sqlite3", "~> 1.4"
end

require 'active_record'
require "minitest/autorun"

module ActiveRecord
  module AttributeMethods
    module Dirty
      def has_changes_to_save?
        mutations_from_database.any_changes?
      end
    end
  end

  module AutosaveAssociation
    def changed_for_autosave?
      # pp "has_changes_to_save? #{has_changes_to_save?}"
      # has_changes_to_save? is true for nested attributes passing tests, but false for the failing test
      new_record? || has_changes_to_save? || marked_for_destruction? || nested_records_changed_for_autosave?
    end

    def associated_records_to_validate_or_save(association, new_record, autosave)
      if new_record || custom_validation_context?
        association && association.target
      elsif autosave # always enters here for nested attributes
        association.target.find_all(&:changed_for_autosave?)
      else
        association.target.find_all(&:new_record?)
      end
    end

    # another potential fix could be to split the associated_records_to_validate_or_save method into two methods? not sure how feasible that is

    def validate_collection_association(reflection)
      # pp "enters validate_collection_association"
      if association = association_instance_get(reflection.name)
        # pp records = associated_records_to_validate_or_save(association, new_record?, reflection.options[:autosave]), empty for failing test, not empty for nested attributes passing tests
        if records = associated_records_to_validate_or_save(association, new_record?, reflection.options[:autosave])
          records.each_with_index { |record, index| association_valid?(reflection, record, index) }
        end
      end
    end

    def association_valid?(reflection, record, index = nil)
      # pp "enters association_valid?"
      return true if record.destroyed? || (reflection.options[:autosave] && record.marked_for_destruction?)

      context = validation_context if custom_validation_context?

      unless valid = record.valid?(context)
        if reflection.options[:autosave]
          indexed_attribute = !index.nil? && (reflection.options[:index_errors] || ActiveRecord::Base.index_nested_attribute_errors)

          record.errors.group_by_attribute.each { |attribute, errors|
            attribute = normalize_reflection_attribute(indexed_attribute, reflection, index, attribute)

            errors.each { |error|
              self.errors.import(
                error,
                attribute: attribute
              )
            }
          }
        else
          errors.add(reflection.name)
        end
      end
      valid
    end
  end
end

module ActiveModel
  module Type
    class Value
      def changed?(old_value, new_value, _new_value_before_type_cast)
        # pp "Value::Changed changed? oldvalue #{old_value}"
        # pp "Value::Changed changed? newvalue #{new_value}"
        old_value != new_value
      end
    end

    module Helpers
      module Numeric
        def changed?(old_value, _new_value, new_value_before_type_cast) # :nodoc:
          # number_to_non_number? is false for the failing test, true for other tests
          # this makes it weird, since it makes it so that it runs validations for some not number values that contain
          # numbers, but not for others, like the ones starting with 0 followed by not a number
          # pp "Helpers::Numeric changed? #{super}"
          (super || number_to_non_number?(old_value, new_value_before_type_cast)) &&
            !equal_nan?(old_value, new_value_before_type_cast)
        end

        private
        def equal_nan?(old_value, new_value)
          eqnan = (old_value.is_a?(::Float) || old_value.is_a?(BigDecimal)) &&
            old_value.nan? &&
            old_value.instance_of?(new_value.class) &&
            new_value.nan?
          # pp "equal_nan? #{eqnan}"
          eqnan
        end

        def number_to_non_number?(old_value, new_value_before_type_cast)
          old_value != nil && !new_value_before_type_cast.is_a?(::Numeric) &&
            non_numeric_string?(new_value_before_type_cast.to_s)
        end

        # NUMERIC_REGEX=/\A\s*-?\d+(\.\d+)?\s*\Z/ # <======== THIS WOULD BE THE 'FIX'

        def not_just_numeric_string(value)
          # pp "non_numeric_string? #{!NUMERIC_REGEX.match?(value)}"
          # 'wibble'.to_i will give zero, we want to make sure
          # that we aren't marking int zero to string zero as
          # changed.
          !NUMERIC_REGEX.match?(value)
        end
      end
    end
  end

  class Attribute
    private

    class FromUser < Attribute # :nodoc:
      def type_cast(value)
        type.cast(value)
      end

      def changed?
        changed_from_assignment? || changed_in_place?
      end

      def changed_from_assignment?
        # if name == "length"
        #   pp "assigned? #{assigned?.present?}"
        #   pp "type.changed?(original_value, value, value_before_type_cast) #{type.changed?(original_value, value, value_before_type_cast)}"
        #   pp "type #{type}"
        # end
        assigned? && type.changed?(original_value, value, value_before_type_cast)
      end

      private
      def _value_for_database
        Type::SerializeCastValue.serialize(type, value)
      end
    end
  end

  class AttributeMutationTracker
    def any_changes?
      attr_names.any? { |attr| changed?(attr) }
    end

    def changed?(attr_name, from: OPTION_NOT_GIVEN, to: OPTION_NOT_GIVEN)
      # attribute_changed? is false for the failing test
      # pp "attribute_changed?  #{attribute_changed?(attr_name)}" if attr_name == "length"
      attribute_changed?(attr_name) &&
        (OPTION_NOT_GIVEN == from || original_value(attr_name) == type_cast(attr_name, from)) &&
        (OPTION_NOT_GIVEN == to || fetch_value(attr_name) == type_cast(attr_name, to))
    end

    private

    def type_cast(attr_name, value)
      attributes[attr_name].type_cast(value)
    end

    def attribute_changed?(attr_name)
      # for all tests forced_changes.include?(attr_name) is false
      # for the failing tests attributes[attr_name].changed? is false but for the working tests it is true
      # pp attributes["length"].changed? if attr_name == "length"
      # pp attributes["length"] if attr_name == "length"
      # forced_changes.include?(attr_name) || !!attributes[attr_name].changed? # original line
      # pp "attributes[attr_name].changed?: #{attributes[attr_name].changed?}" if attr_name == "length"
      forced_changes.include?(attr_name) || !!attributes[attr_name].changed?
    end
  end
end


ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :my_quotes, force: true do |t|
  end

  create_table :my_quote_line_items, force: true do |t|
    t.references :my_quote, foreign_key: true
    t.decimal :length
    t.decimal :width
  end
end

class BugTest < ActiveSupport::TestCase
  class MyQuote < ActiveRecord::Base
    has_many :my_quote_line_items
    accepts_nested_attributes_for :my_quote_line_items, allow_destroy: true
  end

  # spec/support/post.rb
  class MyQuoteLineItem < ActiveRecord::Base
    belongs_to :my_quote

    before_validation :convert_length

    def convert_length
      pp "enters convert_length" # does not enter for the failing test
      self.length = 1.0  # just for demonstration purposes
    end

    # start workaround
    # include ActiveModel::Dirty
    # def length=(val)
    #  length_will_change!
    #  super(val)
    # end
    # end workaround
  end

  test "it works if value does not start with 0" do
    quote = MyQuote.create
    quote_line_item = quote.my_quote_line_items.create

    quote_line_item.update_columns(length: 0.0)

    # it fails if it was 0.0 and string input starts with 0 not followed by a number
    pp "before update"
    pp "THIS I WANT TO COMPARE - value does not start with 0 through quote"
    quote.update(my_quote_line_items_attributes: { "0" => { id: quote_line_item.id, length: "1' 6\"" } })
    pp "after update"
    assert_equal 1.0, quote.my_quote_line_items.first.length

    #  Working test attribute before calling changed?
    #  #<ActiveModel::Attribute::FromUser:0x00007f071ff02440
    #   @name="length",
    #   @original_attribute=
    #    #<ActiveModel::Attribute::FromDatabase:0x00007f071ff03f70
    #     @name="length",
    #     @original_attribute=nil,
    #     @type=#<ActiveModel::Type::Decimal:0x00007f071c4066e8 @limit=nil, @precision=nil, @scale=nil>,
    #     @value_before_type_cast=0.0>,
    #   @type=#<ActiveModel::Type::Decimal:0x00007f071c4066e8 @limit=nil, @precision=nil, @scale=nil>,
    #   @value=0.1e1, # value here is 1, but it just gets the first number until a non number character, when this value is different from 0 it works
    #   @value_before_type_cast="1' 6\"">
  end

  test "it works when updating a quote line item directly" do
    quote = MyQuote.create
    quote_line_item = quote.my_quote_line_items.create

    quote_line_item.update_columns(length: 0.0)

    pp "before update"
    pp "THIS I WANT TO COMPARE - value starts with 0 but from quote line item"
    quote_line_item.update(length: "0' 6\"")
    pp "after update"
    assert_equal 1.0, quote.my_quote_line_items.first.length
  end

  test "it doesn't work" do
    quote = MyQuote.create
    quote_line_item = quote.my_quote_line_items.create
    quote_line_item.update_columns(length: 0.0) # to make this fail it need to be 0.0

    # it fails if it was 0.0 and string input starts with 0 not followed by a number
    pp "NEXT ONE DOESN'T WORK"
    pp "before update"
    quote.update(my_quote_line_items_attributes: { "0" => { id: quote_line_item.id, length: "0' 6\"" } })
    pp "after update"
    assert_equal 1.0, quote.my_quote_line_items.first.length

    # Failing test attribute before calling changed?
    #   #<ActiveModel::Attribute::FromUser:0x00007f071f331788
    #   @name="length",
    #   @original_attribute=
    #    #<ActiveModel::Attribute::FromDatabase:0x00007f071f333308
    #     @name="length",
    #     @original_attribute=nil,
    #     @type=#<ActiveModel::Type::Decimal:0x00007f071c4066e8 @limit=nil, @precision=nil, @scale=nil>,
    #     @value_before_type_cast=0.0>,
    #   @type=#<ActiveModel::Type::Decimal:0x00007f071c4066e8 @limit=nil, @precision=nil, @scale=nil>,
    #   @value=0.0, # value here is 0, but it just gets the first number until a non number character, when this value is different from 0 it works, because it compares both from database and from user
    #   @value_before_type_cast="0' 6\"">
  end

  test "it works just like it was before, but with a 'valid' additional attribute" do
    quote = MyQuote.create
    quote_line_item = quote.my_quote_line_items.create
    quote_line_item.update_columns(length: 0.0) # to make this fail it need to be 0.0

    # it fails if it was 0.0 and string input starts with 0 not followed by a number
    pp "before update"
    quote.update(my_quote_line_items_attributes: { "0" => { id: quote_line_item.id, length: "0' 6\"", width: 2 } })
    pp "after update"
    assert_equal 1.0, quote.my_quote_line_items.first.length
  end

  test "it works if starting value is not 0.0" do
    quote = MyQuote.create
    quote_line_item = quote.my_quote_line_items.create

    quote_line_item.update_columns(length: 3.0)

    # it fails if it was 0.0 and string input starts with 0 not followed by a number
    pp "before update"
    quote.update(my_quote_line_items_attributes: { "0" => { id: quote_line_item.id, length: "0' 6\"", width: 2 } })
    pp "after update"
    assert_equal 1.0, quote.my_quote_line_items.first.length
  end
end

```

Long story short, after upgrading from Rails 5 -> Rails 6.1.7.8 I'm seeing unexpected behavior for `accepts_nested_attributes_for`. Some nested records are not saving because callbacks are not being run like before in certain scenarios. I know we are on 7.1 for bugfixes now, but it should definitely be addressed, at least for the latest version. I didn't reproduce it there because I spent way too much time on it, but I'm pretty sure the same happens on 7.1.

Sorry for the length of the tests, it is more like a playground to explore different alternatives and flows.

From the title: Callbacks / Validations are not running for `accepts_nested_attributes_for` relation on certain values, but will run on other values, or when another value is saved together with the problematic value, or when updating the record directly

### Expected behavior
Associations with accepts_nested_attributes_for have validations run on updated records, even when a single attribute of a record of the association is updated with a type other from the declarated. In this case String trying to be converted to Decimal.

### Actual behavior
Some records are updated and some are not, seemingly because ActiveRecord is trying to coerse String values into numeric values for the case of a Decimal attribute that lives inside one record of the association, then it compares it with the old value just by coercing it to a number, and for some cases it doesn't detect a change when there actually is (because of type casting). The records do update and callbacks are run correctly when the value of that attribute is different to the old value from the perspective of ActiveRecord or when other attributes are updated.

=======

I think it can be fixed by updating the NUMERIC_REGEX from my debugging, but I'm probably naive about it. I took a deep dive but it's just been two days looking at ActiveRecord code and I'm not super familiar with it. The method that uses it might benefit from renaming to not_only_numeric_string.

Edit: maybe we also need to check for empty string or some other cases I'm not contemplating, it's just a prototype.

There's a workaround of forcing attribute_will_change! through ActiveModel::Dirty, but not ideal since you need to be aware of this and it is a regression from an old version.

### System configuration
**Rails version**:
6.1.7.8
**Ruby version**:
3.3.0

**Comment by fatkodima** [comment]
Rails 6.1 is not supported for bug fixes. Can you verify if it still not works in rails 7.1+?

**Comment by josesei** [comment]
I can confirm it still not works for rails 7.1+, here's how to reproduce:

ruby```
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org/"
  # Activate the gem you are reporting the issue against.
  gem "activerecord", "~> 7.1.3.4" # I'm guessing it has to do with ActiveModel but I'm not sure since the problem is not monifested when you update the line item directly, so it might be a problem with the nested attributes
  gem "sqlite3", "~> 1.4"
end

require 'active_record'
require "minitest/autorun"

module ActiveModel
    module Helpers
      module Numeric
        def changed?(old_value, _new_value, new_value_before_type_cast) # :nodoc:
          # number_to_non_number? is false for the failing test, true for other tests
          # this makes it weird, since it makes it so that it runs validations for some not number values that contain
          # numbers, but not for others, like the ones starting with 0 followed by not a number
          # pp "Helpers::Numeric changed? #{super}"
          (super || number_to_non_number?(old_value, new_value_before_type_cast)) &&
            !equal_nan?(old_value, new_value_before_type_cast)
        end

        private
        def equal_nan?(old_value, new_value)
          eqnan = (old_value.is_a?(::Float) || old_value.is_a?(BigDecimal)) &&
            old_value.nan? &&
            old_value.instance_of?(new_value.class) &&
            new_value.nan?
          # pp "equal_nan? #{eqnan}"
          eqnan
        end

        def number_to_non_number?(old_value, new_value_before_type_cast)
          old_value != nil && !new_value_before_type_cast.is_a?(::Numeric) &&
            non_numeric_string?(new_value_before_type_cast.to_s)
        end

        NUMERIC_REGEX=/\A\s*-?\d+(\.\d+)?\s*\Z/ # <======== THIS WOULD BE THE 'FIX'

        def not_just_numeric_string(value)
          # pp "non_numeric_string? #{!NUMERIC_REGEX.match?(value)}"
          # 'wibble'.to_i will give zero, we want to make sure
          # that we aren't marking int zero to string zero as
          # changed.
          !NUMERIC_REGEX.match?(value)
        end
      end
    end
  end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :my_quotes, force: true do |t|
  end

  create_table :my_quote_line_items, force: true do |t|
    t.references :my_quote, foreign_key: true
    t.decimal :length
    t.decimal :width
  end
end

class BugTest < ActiveSupport::TestCase
  class MyQuote < ActiveRecord::Base
    has_many :my_quote_line_items
    accepts_nested_attributes_for :my_quote_line_items, allow_destroy: true
  end

  # spec/support/post.rb
  class MyQuoteLineItem < ActiveRecord::Base
    belongs_to :my_quote

    before_validation :convert_length

    def convert_length
      pp "enters convert_length" # does not enter for the failing test
      self.length = 1.0  # just for demonstration purposes
    end

    # start workaround
    # include ActiveModel::Dirty
    # def length=(val)
    #  length_will_change!
    #  super(val)
    # end
    # end workaround
  end

  test "it works if value does not start with 0" do
    quote = MyQuote.create
    quote_line_item = quote.my_quote_line_items.create

    quote_line_item.update_columns(length: 0.0)

    # it fails if it was 0.0 and string input starts with 0 not followed by a number
    pp "before update"
    pp "THIS I WANT TO COMPARE - value does not start with 0 through quote"
    quote.update(my_quote_line_items_attributes: { "0" => { id: quote_line_item.id, length: "1' 6\"" } })
    pp "after update"
    assert_equal 1.0, quote.my_quote_line_items.first.length

    #  Working test attribute before calling changed?
    #  #<ActiveModel::Attribute::FromUser:0x00007f071ff02440
    #   @name="length",
    #   @original_attribute=
    #    #<ActiveModel::Attribute::FromDatabase:0x00007f071ff03f70
    #     @name="length",
    #     @original_attribute=nil,
    #     @type=#<ActiveModel::Type::Decimal:0x00007f071c4066e8 @limit=nil, @precision=nil, @scale=nil>,
    #     @value_before_type_cast=0.0>,
    #   @type=#<ActiveModel::Type::Decimal:0x00007f071c4066e8 @limit=nil, @precision=nil, @scale=nil>,
    #   @value=0.1e1, # value here is 1, but it just gets the first number until a non number character, when this value is different from 0 it works
    #   @value_before_type_cast="1' 6\"">
  end

  test "it works when updating a quote line item directly" do
    quote = MyQuote.create
    quote_line_item = quote.my_quote_line_items.create

    quote_line_item.update_columns(length: 0.0)

    pp "before update"
    pp "THIS I WANT TO COMPARE - value starts with 0 but from quote line item"
    quote_line_item.update(length: "0' 6\"")
    pp "after update"
    assert_equal 1.0, quote.my_quote_line_items.first.length
  end

  test "it doesn't work" do
    quote = MyQuote.create
    quote_line_item = quote.my_quote_line_items.create
    quote_line_item.update_columns(length: 0.0) # to make this fail it need to be 0.0

    # it fails if it was 0.0 and string input starts with 0 not followed by a number
    pp "NEXT ONE DOESN'T WORK"
    pp "before update"
    quote.update(my_quote_line_items_attributes: { "0" => { id: quote_line_item.id, length: "0' 6\"" } })
    pp "after update"
    assert_equal 1.0, quote.my_quote_line_items.first.length

    # Failing test attribute before calling changed?
    #   #<ActiveModel::Attribute::FromUser:0x00007f071f331788
    #   @name="length",
    #   @original_attribute=
    #    #<ActiveModel::Attribute::FromDatabase:0x00007f071f333308
    #     @name="length",
    #     @original_attribute=nil,
    #     @type=#<ActiveModel::Type::Decimal:0x00007f071c4066e8 @limit=nil, @precision=nil, @scale=nil>,
    #     @value_before_type_cast=0.0>,
    #   @type=#<ActiveModel::Type::Decimal:0x00007f071c4066e8 @limit=nil, @precision=nil, @scale=nil>,
    #   @value=0.0, # value here is 0, but it just gets the first number until a non number character, when this value is different from 0 it works, because it compares both from database and from user
    #   @value_before_type_cast="0' 6\"">
  end

  test "it works just like it was before, but with a 'valid' additional attribute" do
    quote = MyQuote.create
    quote_line_item = quote.my_quote_line_items.create
    quote_line_item.update_columns(length: 0.0) # to make this fail it need to be 0.0

    # it fails if it was 0.0 and string input starts with 0 not followed by a number
    pp "before update"
    quote.update(my_quote_line_items_attributes: { "0" => { id: quote_line_item.id, length: "0' 6\"", width: 2 } })
    pp "after update"
    assert_equal 1.0, quote.my_quote_line_items.first.length
  end

  test "it works if starting value is not 0.0" do
    quote = MyQuote.create
    quote_line_item = quote.my_quote_line_items.create

    quote_line_item.update_columns(length: 3.0)

    # it fails if it was 0.0 and string input starts with 0 not followed by a number
    pp "before update"
    quote.update(my_quote_line_items_attributes: { "0" => { id: quote_line_item.id, length: "0' 6\"", width: 2 } })
    pp "after update"
    assert_equal 1.0, quote.my_quote_line_items.first.length
  end
end
```

**Comment by josesei** [comment]
was anyone able to reproduce?

**Comment by Jay0921** [comment]
@josesei  It looks like the issue is coming from the input string. When the database column type is `decimal` and the input is a `string`, Rails uses the `.to_d` method to convert the string to a decimal value. This conversion is handled here: 
https://github.com/rails/rails/blob/a5ffec5291442b38188e987e32844a6a8d260e4c/activemodel/lib/active_model/type/decimal.rb#L65-L71

So, this will be the actual results: 

```ruby
"1' 6\"".to_d # => 1.0
"0' 6\"".to_d # => 0.0
```

This explains why it works when the initial value is not `0.0` or when there is an additional attribute (e.g., `width: 2`). When the initial value is `0.0`, Rails converts `"0' 6\""` to `0.0`. Since the values are the same, the `changed?` method returns false, therefore no save or validation is triggered.

**Comment by josesei** [comment]
@Jay0921 I agree it definitely comes from the input string.

This is unexpected behavior to me, since it is working fine for saving the model itself, just not the nested relations.

Also, it seems to be a regression, since the same code was working properly in Rails 5.

**Comment by Jay0921** [comment]
> This is unexpected behavior to me, since it is working fine for saving the model itself, just not the nested relations.

Depending on how you define `working fine`, if you mean the callback got triggered, then yes, it does. I only looked at the code at a high level. It seems like all the callbacks are triggered when you update the record directly, even if there are no changes. However, for nested attributes, it only calls the update method if the value has changed.

This code will trigger the callback even no value has changed. 
```ruby
quote_line_item.update({})
```

However, the value in the database is not the intended value:
```ruby
quote_line_item.update_columns(length: "1' 6\"") # => 1.0
quote_line_item.update(length: "1' 6\"") # => 1.0
```
