### ISSUE TITLE
Upgrading from rails 7.0 to 7.1: Rails.logger is nil

### ISSUE THREAD

**Issue by bubiche** [rails/rails#52391]
### Steps to reproduce

Sample repo: https://github.com/bubiche/rails_7_1_logger_issue_sample

I use a class to load secrets into `config/database.yml`
```yml
production:
  password: <%= SecretLoader.get("db_password") %>
```

The class:
```ruby
# lib/secret_loader.rb
# loaded under config/application.rb with `require "secret_loader"`
class SecretLoader
  def self.get(key)
    Rails.logger.info("Some log")
    # code to load and return secrets
  end
end
```

The logging part works fine in rails 7 but after upgrading to rails 7.1, `Rails.logger` is not available when I run commands like `rails assets:clobber` or `rails db:migrate`

### Expected behavior

Able to see `Some log` from the logger.

### Actual behavior

I got the error "NoMethodError: undefined method `info' for nil:NilClass (NoMethodError)" for `Rails.logger.info`

### System configuration
**Rails version**: 7.1.3.4

**Ruby version**: 3.2.4

**Comment by fatkodima** [comment]
Can you create a sample app that works using the previous rails version and fails with the new version and share with us?

**Comment by bubiche** [comment]
@fatkodima I have created a sample app here: https://github.com/bubiche/rails_7_1_logger_issue_sample I hope it helps with debugging.

**Comment by RobertChang0722** [comment]
@bubiche Just provide you a workaround.

```ruby
# config/application.rb

module Rails71Logger
  class Application < Rails::Application
    config.load_defaults 7.1

    config.before_configuration do
      Rails.logger ||= Logger.new(STDOUT)
      require 'secret_loader'
    end
  end
end
```

**Comment by fatkodima** [comment]
Relevant https://github.com/rails/rails/issues/51578
It started to fail after https://github.com/rails/rails/pull/46134

**Comment by bubiche** [comment]
thanks guys, problem solved.
