### ISSUE TITLE
20 Years of Rails – Republish v0.5

### ISSUE THREAD

**Issue by schmijos** [rails/rails#52414]
The [first version of Rails](https://x.com/dhh/status/1384170390402965509) became 20 years of age by yesterday. Happy Birthday! 🎉 

We celebrated this at the Zurich Rails meetup and I held a [presentation about Rails 0.5](https://docs.google.com/presentation/d/e/2PACX-1vTTRiG_mEW_o8t6tKAZ-A_z4MjByU3cxzM88GhMFnae7WeY5nUHUXP7t-4H1XHXCp0V6PKETsDfJmjN/pub?start=false&loop=false&delayms=3000). Since I was missing historical context it was a bit difficult to find the original sources. I then found them on the RubyForge web archives: [rails-0.5.0.tgz](https://web.archive.org/web/20040823011510/http://rubyforge.org/frs/download.php/1031/rails-0.5.0.tgz).

The audience suggested that it would be nice to republish Rails 0.5 on GitHub.
Therefore I made an [orphan branch with tag `v0.5.0`](https://github.com/schmijos/rails/tree/v0.5.0) in my fork but I cannot create a PR here.
Would some maintainer with upstream push permissions mind to merge this orphan?

PS: As a bonus if some want's to run it. I've got a sample project over here with a [Dockerfile](https://github.com/renuo/rails-0.5-example/blob/main/Dockerfile)

**Comment by rafaelfranca** [comment]
Thank you for the suggestion. Since this isn't an issue I'm going to close, but I did create a series of branches [with all the missing releases](https://github.com/rafaelfranca/omg-rails/commits/0-8-stable/), since the initial commit in this repository is with code after 0.8.5. I'll discuss with the Rails core to see if we want to publish those

**Comment by rafaelfranca** [comment]
Done. https://github.com/rails/rails/tree/feba2817693536f24cd3848f3cbdc28735806261

**Comment by schmijos** [comment]
Thank you for adding this to the collection here! 🙏 

I noticed that you published only what was in the `vendor` folder in the _Rubyforge_ release.
This means the following is missing for v0.5:

- [rakefile](https://github.com/schmijos/rails/blob/v0.5.0/rakefile)
- [router](https://github.com/schmijos/rails/blob/v0.5.0/config/apache.conf)
- [database config](https://github.com/schmijos/rails/blob/v0.5.0/config/database.yml)
- [docs](https://github.com/schmijos/rails/tree/v0.5.0/doc/api)
- empty template folder structure and the symlinks

Is this on purpose?

**Comment by schmijos** [comment]
Ok. This works 👍 

I guess that `railties/fresh_rakefile` is not copied to the newly generated `rails` folder can be considered a bug.
