### ISSUE TITLE
Can we have a checkbox alias?

### ISSUE THREAD

**Issue by andrewhavens** [rails/rails#52430]
It is certainly acceptable to refer to checkboxes as two words: "Check Box". But more often, they are referred to as "Checkbox" (one word):
* HTML: [input `type="checkbox"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox)
* Wikipedia: [Checkbox](https://en.wikipedia.org/wiki/Checkbox)
* Nielson Norman Group: [Checkboxes](https://www.nngroup.com/articles/checkboxes-design-guidelines/)

For backwards compatibility, it makes sense to continue supporting `check_box` Form Helper, but I propose adding an alias (or making `check_box` the alias), so that our forms can refer to them as simply "checkbox", without the underscore.

The classes/methods that I think should be aliased are:
* [ActionView::Helpers::FormHelper#check_box](https://github.com/rails/rails/blob/19eebf6d33dd15a0172e3ed2481bec57a89a2404/actionview/lib/action_view/helpers/form_helper.rb#L1343)
* [ActionView::Helpers::FormBuilder#check_box](https://github.com/rails/rails/blob/19eebf6d33dd15a0172e3ed2481bec57a89a2404/actionview/lib/action_view/helpers/form_helper.rb#L2468)
* [ActionView::Helpers::FormBuilder#collection_check_boxes](https://github.com/rails/rails/blob/19eebf6d33dd15a0172e3ed2481bec57a89a2404/actionview/lib/action_view/helpers/form_options_helper.rb#L908)
* [ActionView::Helpers::FormOptionsHelper#collection_check_boxes](https://github.com/rails/rails/blob/19eebf6d33dd15a0172e3ed2481bec57a89a2404/actionview/lib/action_view/helpers/form_options_helper.rb#L782)
* [ActionView::Helpers::FormTagHelper#check_box_tag](https://github.com/rails/rails/blob/19eebf6d33dd15a0172e3ed2481bec57a89a2404/actionview/lib/action_view/helpers/form_tag_helper.rb#L455)
* [ActionView::Helpers::Tags::CheckBox](https://github.com/rails/rails/blob/def0397e595c503099e3c10bd811d5d9e3613b38/actionview/lib/action_view/helpers/tags/check_box.rb)
* [ActionView::Helpers::Tags::CollectionCheckBoxes and CheckBoxBuilder#check_box](https://github.com/rails/rails/blob/def0397e595c503099e3c10bd811d5d9e3613b38/actionview/lib/action_view/helpers/tags/collection_check_boxes.rb)

If this proposal is acceptable, I can draft a PR to make this change. Let me know what you think.

**Comment by rafaelfranca** [comment]
I think an alias is good, but @dhh might have a strong opinion about this.

**Comment by dhh** [comment]
Yes, I'm fine with an alias. But let's indeed make checkbox_tag the new primary and check_box_tag an eternal alias to the new name.
