### ISSUE TITLE
Engine generator generates non-inclusive language

### ISSUE THREAD

**Issue by ConnorSheremeta** [rails/rails#52456]
https://source.android.com/docs/setup/contribute/respectful-code
Suggests that the term 'dummy' is a non-inclusive term and should be replaced if possible. Suggestions for a replacement term from the documentation above include: unused, placeholder, no-op, base, fake/mock/stub.

### Steps to reproduce
Running `rails plugin new blorgh --mountable` (from the Rails guide https://guides.rubyonrails.org/engines.html#generating-an-engine) creates the directory  '`test/dummy`' along with other references to the term 'dummy' which is considered a non-inclusive term.

### Expected behavior
The generator does not reference the term 'dummy' which is considered non-inclusive.

### Actual behavior
The directory `'test/dummy'` is created from the generator along with other references to the term 'dummy'.

### System configuration
**Rails version**: 7.1.3.4

### Related to
https://github.com/rails/rails/issues/43601

**Comment by rafaelfranca** [comment]
Thank you for the issue but we don't have any plans to change the generator.
