### ISSUE TITLE
StrongParameters default approach prone to 500: Recommended approach?

### ISSUE THREAD

**Issue by dari-us** [rails/rails#52463]
In the [Rails documentation](https://guides.rubyonrails.org/action_controller_overview.html#strong-parameters), there is a recurring pattern of `params.require(:something).permit(:some, :other, :stuff)` to "fetch" a nested `ActionController::Parameters` with `require`, then `permit`ting its content.
To me, this suggests, that `require` ensures it returns a `ActionController::Parameters`, which it doesn't, as it can return arbitrary non-blank or `false` values.
With a little bit of parameter manipulation, it is possible to produce a 500 by making Rails call `permit` on, say, an instance of String.
It baffles me that [the docs](https://guides.rubyonrails.org/action_controller_overview.html#outside-the-scope-of-strong-parameters) state, while not being a silver bullet, StrongParameters is supposed to cover the most common use cases, and yet, it fails at making arguably the most common use case safe against 500.

To guard against this, one can `params.permit(user: [:name, :age]).require(:user)`, however, once in a nested context, where you have more parameters, f.e. `:id` of a parent record, you always have to explicitly permit them as well, like so `params.permit(:id, user: [:name, :age]).require(:user)` or else a log message / exception will occurr, depending on configuration of `action_on_unpermitted_parameters`.
The `permit`, then `require` approach is clumsy, smelly and un-rails-y to me, so I use the following Initializer to address this problem:

```
# config/initializers/action_controller_parameters.rb
module ActionController
  class BadParameterNesting < KeyError
    attr_reader :key

    def initialize(key)
      @key = key
      super("param must contain nested params, but doesn't: #{key}")
    end
  end

  class Parameters
    # like fetch but raises if value is no ActionController::Parameters
    def nested(key, *args, &block)
      value = fetch(key, *args, &block)
      raise BadParameterNesting.new(key) unless value.is_a?(self.class)

      return value
    end
  end
end

ActionDispatch::ExceptionWrapper.rescue_responses.merge!(
  "ActionController::BadParameterNesting" => :bad_request
)

```

Is there something I am missing or is a monkey-patch like this the only way to make the most common use case of StrongParameters bulletproof against 500?
This is a problem for `params.require(...).permit(...)` and `params.fetch(:x, {}).permit(...)`, which are both solved by `params.nested(...).permit(...)`.

**Comment by jeromedalbert** [comment]
> With a little bit of parameter manipulation, it is possible to produce a 500 by making Rails call permit on, say, an instance of String.

Can you provide an example of such a request that would produce a 500?

**Comment by rafaelfranca** [comment]
`"something" => "else"` would cause that to raise an error since `something` isn't a hash.

I was pretty sure we had an issue for this already, but could not find it.

**Comment by dari-us** [comment]
@rafaelfranca I think I found the issue you mean: https://github.com/rails/rails/issues/42953

It was marked stale, but apparently there are some PRs and suggestions how people think it should be fixed.

I believe adding a new method that is used instead of `require` when nested params are expected (and consistently using that in the docs for these situations) is the most simple, safe and compatible way to go. I based my `nested` on `fetch`, because it allows for a fallback.

**Comment by dari-us** [comment]
The approach mentioned in #51674 works for replacing `require(...).permit(...)`, however, in my apps I also often use `fetch(:x, {}).permit(...)`, (f.e. for filter forms on an index pages) so I guess `mandate` would solve only one of my use cases, as it does not provide a fallback option, so I'd be stuck with `fetch`, then checking its type, then `permit`.
Maybe it's a good idea to account for a use case with fallback as well.
