### ISSUE TITLE
Certain ActiveRecord queries are not using parameterized queries

### ISSUE THREAD

**Issue by sliiser** [rails/rails#52476]
Most of the time when activerecord makes queries to the database, parameterized queries are used.
```ruby
Comment.where(post_id: 1)
# Comment Load (0.2ms)  SELECT "comments".* FROM "comments" WHERE "comments"."post_id" = ?  [["post_id", 1]]
```
However, in some cases, the full SQL without any parameter placeholders is used
```ruby
Comment.insert({post_id: 1}) 
# Comment Insert (0.3ms)  INSERT INTO "comments" ("post_id") VALUES (1) ON CONFLICT  DO NOTHING RETURNING "id"
Comment.where("post_id = ?", 1) 
# Comment Load (0.5ms)  SELECT "comments".* FROM "comments" WHERE (post_id = 1)
```
This is inconsistent and in our case lead to PII being available in database logs (without parameters) that was assumed to be PII free.

This can be worked around by using the underlying database connection directly rather than active record

```ruby
sql = 'INSERT INTO "comments" ("post_id") VALUES (?) ON CONFLICT  DO NOTHING RETURNING "id"'
Comment.connection.exec_query(sql, 'SQL', [1])
# INSERT INTO "comments" ("post_id") VALUES (?) ON CONFLICT  DO NOTHING RETURNING "id"  [[nil, 1]]
```
but this kind of defeats the purpose of active record. Also, having to know all the places where parameterized queries are and are not being utilized is difficult.

Should consistency be an objective here or is this something that is considered out of scope for Rails/ActiveRecord? If it is, I can look into how to make this happen.

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")

ActiveRecord::Schema.define do
  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Comment < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    logger = StringIO.new
    ActiveRecord::Base.logger = Logger.new(logger)
    
    Comment.insert({post_id: 1})
    assert_nil logger.string['("post_id") VALUES (1)']

    Comment.where("post_id = ?", 1) 
    assert_nil logger.string['(post_id = 1)']
  end
end
```

### Expected behavior
Parameterized queries are used wherever possible.

### Actual behavior
Parameters end up in the SQL string.

### System configuration
**Rails version**: 7.1.3.4

**Ruby version**: 3.3.0

**Comment by Procrustes5** [comment]
I strongly agree with this issue. The inconsistent use of parameterized queries in ActiveRecord is concerning, especially regarding security and PII exposure.
I'm interested in contributing to fix this problem. Is there an ongoing discussion addressing this? If not, I'd be willing to work on a solution.

**Comment by byroot** [comment]
> is this something that is considered out of scope for Rails/ActiveRecord?

Kind of. 

Parameterized queries have been implemented mostly to allow preparing statements, not for trimming server logs, hence why it's not used for things like INSERT.

So I wouldn't classify this as a bug, but if someone opened a PR to make these queries use parameterized, I think it would be welcome.
