### ISSUE TITLE
Assigning HashWithIndifferentAccess to default_url_options makes url helper go foobar

### ISSUE THREAD

**Issue by bogdan** [rails/rails#52482]
In my case `default_url_options` is dynamic so I need to be able to assign it from wherever source they come.

### Steps to reproduce

```ruby
Rails.application.routes.default_url_options = {host: 'example.com'}.with_indifferent_access
Rails.application.routes.url_helpers.rails_health_check_path 
```

### Expected behavior

```
"/up
```

### Actual behavior

```
"/up?action=show&controller=rails%2Fhealth"
```

### System configuration
**Rails version**: 3.2.2

**Ruby version**: 7.1.3.4

**Comment by jeromedalbert** [comment]
Not addressing the underlying issue, but symbol-based hashes work better, so `Rails.application.routes.default_url_options = {host: 'example.com'}.with_indifferent_access.symbolize_keys` is a workaround.

**Comment by nikhilbhatt** [comment]
@bogdan what is the usecase for `with_indifferent_access` here? why we can't directly use it like this? (symbol keys)

```
Rails.application.routes.default_url_options = { host: 'example.com' }
```

The below method expects string symbol keys. & `deafult_url_options` should be symbol keys as well.
https://github.com/rails/rails/blob/a5ffec5291442b38188e987e32844a6a8d260e4c/actionpack/lib/action_dispatch/routing/route_set.rb#L844-L891

**Comment by bogdan** [comment]
There is no use case as you can always call `to_h.symbolize_keys` anyway. It is just that it is expected for `HashWithIndifferentAccess` to behave like `Hash`. Also, the behavior is quite strange. I would even say it looks like a security issue because it reveals internal structure of the app. 

I think if it is 1-3 lines to fix it, we should do it.

**Comment by nikhilbhatt** [comment]
Yes, its just a 1 line fix + test cases (I tried this in my local and it was working fine). I can create a PR for this if it is needed. 

```
options = default_url_options.symbolize_keys.merge options 
```

**Comment by nikhilbhatt** [comment]
it's a 1 liner fix. I am not sure if we can make default_url_options to not assign indifferent access hash but we can do this to make it work. I can make a PR if it this works.

```
options = default_url_options.symbolize_keys.merge options 
```

**Comment by bogdan** [comment]
Such a solution can be slow because we generate one more hash object for every `url_for` call. It is better to avoid that.
