### ISSUE TITLE
Segmentation fault when some gems are present in a specific order in the Gemfile

### ISSUE THREAD

**Issue by rameerez** [rails/rails#52493]
### Steps to reproduce

1. Create a new project:
```
rails new projectname --database=postgresql
```
2. Verify `rails c` works as expected
3. Add either of these gems to the Gemfile immediately below the `gem "rails"` line (the order in which the gem is added is important to trigger the segfault, oddly enough; I wasn't able to reproduce it if the gem was added to the bottom of the Gemfile):
```ruby
gem "twitter"
# or
gem "noticed", "~> 1.6"
```
4. Run `bundle install`
5. Verify `rails c` now segfaults (if not at first run, after a few runs, like 4-5 runs. For some reason I can't trigger the segfault consistently, it only happens one every few times)

For reference, this is the [Gemfile.lock](https://github.com/user-attachments/files/16473864/Gemfile.lock.txt) under which the segfault gets triggered.

### Expected behavior

I first discovered this when upgrading a project from Rails 7.0 to Rails 7.1 – the lastest version that doesn't segfault is 7.0.8.4

By debugging this I realized the `twitter` gem is deprecated and the `noticed` gem latest version is 2.4 and not 1.6 (it doesn't segfault with noticed ~> 2.4) – but I feel in any case the expected behavior should be throwing an error instead of segfaulting.

### Actual behavior

Upon running `rails s`, `rails c` or pretty much any Rails command, it segfaults.

The way in which it segfaults doesn't seem to be consistent. The stack trace sometimes mentions `actionview`, sometimes `bootsnap`, sometimes `msgpack`, sometimes `zeitwerk` – often at different files and different lines within the same file.

[Sample segfault error log](https://github.com/user-attachments/files/16473721/segfault.log)

### System configuration
 - Ruby 3.3.4
 - Rails 7.1.3
 - Macbook Pro M1 Max (MacBookPro18,2)
 - macOS Ventura 13.5.1
 
@lmansur noted this may be related to `libffi` because both `twitter` and `noticed ~> 1.6` depend on it (indirectly via the `http` gem), and `noticed` dropped http on >= 2, which is not segfaulting. So in case my ffi version is of any help to replicate and debug:
 ```
 ❯ ruby -r ffi -e "puts FFI::VERSION"
1.17.0
```

**Comment by flavorjones** [comment]
Hi, thanks for reporting your experience here. However, it doesn't seem like this is an issue with Rails, especially since your repro involves running other gems that are not part of the Rails project.

You may want to report this upstream to Ruby at https://bugs.ruby-lang.org/issues/ where there maybe someone who's willing to help narrow the problem down a bit more.

For the record: I cannot reproduce what you're describing on:

- x86_64-linux
- Ruby 3.3.4
- Rails 7.1.3
- using your exact Gemfile.lock

Maybe someone with a Mac can try to repro.
