### ISSUE TITLE
Hash#to_json behavior change on Rails > 7.1 when using yajl/json_gem

### ISSUE THREAD

**Issue by chrishulton** [rails/rails#52519]
### Steps to reproduce

We have a number of applications using the [yajl-ruby](https://github.com/brianmario/yajl-ruby) gem and specifically the [JSON gem API](https://github.com/brianmario/yajl-ruby?tab=readme-ov-file#json-gem-compatibility-api) with`require 'yajl/json_gem'`.

Prior to Rails 7.2, hashes would use the `#to_json` method defined in `ActiveSupport::ToJsonWithActiveSupportEncoder` and supported options such as `except`.  In Rails 7.2 and up, it looks like the patch does not apply in the same way, and instead the hash is now using the native definition added by the `yajl-ruby` gem.

This appears related to this PR: https://github.com/rails/rails/pull/51640 which switches from `prepend` to `include` when applying the patch.

The below script will pass with `gem "rails"` and fail with `gem "rails", github: "rails/rails", branch: "main"`.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Passes with this version
  # gem "rails"

  # Fails with this version
  gem "rails", github: "rails/rails", branch: "main"

  gem "yajl-ruby"
end

require "active_support"
require "active_support/core_ext/object/blank"
require "minitest/autorun"
require "yajl/json_gem"

class BugTest < Minitest::Test
  def test_stuff
    puts "Rails version: #{Rails.version}"
    puts "Hash#to_json definition: #{{}.method(:to_json)}"

    assert_equal(
      "{}",
      { "foo" => "bar" }.to_json(except: ["foo"])
    )
  end
end
```

#### Rails 7.1.3.4 (pass)

```
# Running:

Rails version: 7.1.3.4
Hash#to_json definition: #<Method: Hash(ActiveSupport::ToJsonWithActiveSupportEncoder)#to_json(options=...) /usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/core_ext/object/json.rb:36>
.

Finished in 0.001267s, 789.2660 runs/s, 789.2660 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

#### Rails 8.0.0.alpha (fail)

```
# Running:

Rails version: 8.0.0.alpha
Hash#to_json definition: #<Method: Hash#to_json(*)>
F

Finished in 0.001134s, 881.7370 runs/s, 881.7370 assertions/s.

  1) Failure:
BugTest#test_stuff [yajl_to_json_issue.rb:27]:
Expected: "{}"
  Actual: "{\"foo\":\"bar\"}"

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

### Expected behavior

The test should pass (?)

I am not sure if this change is intended behavior, something to fix, or something that may be worth calling out in the release notes as it is a behavior change and not obvious at first.

### Actual behavior

The `ActiveSupport::ToJsonWithActiveSupportEncoder#to_json` definition is not used, and the test fails.

### System configuration

**Rails version**: 7.1.3.4 (passing), 8.0.0.alpha (failing)

**Ruby version**: 3.3.1

**Comment by rafaelfranca** [comment]
This is more likely yajl-ruby "monkey patching Rails" and expecting the order of the includes to match what they expect. Rails never claimed that using yali-ruby or any other json implementation would yield the same result. Did you try to report to yail-ruby and fix it there? If it is all because `prepend` changed to `include` this can be easily fixed there.

The fix would to make sure yail-ruby is required before active_support. Rails is guaranteed to work because we do require `json` like you can see in this comment https://github.com/rails/rails/pull/51640/files#r1575329346
