### ISSUE TITLE
Testing Rails 7.2.0rc1 — Error with default "allow_browser versions: :modern"

### ISSUE THREAD

**Issue by krschacht** [rails/rails#52534]
### Steps to reproduce

(I'm not certain this is a bug, but the behavior definitely seems wrong and since it's related to really new functionality, the `allow_browser` tag, I thought I'd report it in case this is helpful to the team.)

The issue is that when using Chrome Inspector to view a website at a mobile size, the new rails `allow_browser` is not recognizing the browser. In order to develop an app that works well even on the smaller viewports, I have to comment this line out in order to preview.

1. I created a brand new rails app, viewed in the latest Mac Chrome (Version 126.0.6478.183 (Official Build) (arm64)
2. I viewed any page generated by rails scaffolding
3. Press F12 to open inspector and turn on the device toolbar (Cmd + Shift + M or the icon near the top-left of chrome inspector menu bar)
4. Change the drop-down device type to anything other than Responsive. For example, change it to "iPhone 14 Pro Max"
5. The page will immediately transform to a mobile size and it won't immediately issue a new server request, but reload the page with this iPhone viewport enabled and you get this error:
<img width="648" alt="image" src="https://github.com/user-attachments/assets/08e79303-0616-448c-9d48-56bff767e742">

Note: Because this is a newly generated app my browser support is set to the default `allow_browser versions: :modern`

### Expected behavior

I would expect that the default `allow_browser versions: :modern` should allow me to view my app using the Chrome inspector mobile viewports. I did some investigation and when loading with a normal "Responsive" chrome browser the `request.user_agent` is `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`

When loading with "iPhone 14 Pro Max" the user agent changes to `Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1`. I am pretty sure that this supports webp images, web push, badges, import maps, CSS nesting, and CSS :has.

### Actual behavior

It blocks it showing the screenshot included above

### System configuration
**Rails version**: 7.2.0.rc1

**Ruby version**: 3.3.4

**Comment by rafaelfranca** [comment]
Thank you for reporting this. This is because `modern` only support Safari 17.2 and the chrome inspector is reporting safari 16.6

```
>> user = UserAgent.parse("Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1")
>> user.browser
=> "Safari"
>> 
>> user.version
=> #<UserAgent::Version 16.6>
```

This was somewhat reported already in https://github.com/rails/rails/pull/50505#issuecomment-1894487201. You can change the requirements yourself for your application.

**Comment by krschacht** [comment]
@rafaelfranca Thanks for your quick response. However, it's notable that the PR you linked to discussed this very same confusion when someone else couldn't figure out why their browser was unsupported.

I think we can fix it with a couple small tweaks to copy. I tee'd up a PR which makes these changes in case you are willing to consider this: https://github.com/rails/rails/pull/52538 I predict that a lot of developers are going to run into this and be confused, however

**Comment by indigotechtutorials** [comment]
This is still happening now and its pretty annoying since Rails should be the best web framework out there having a bug like this is really annoying and frustrating for new developers

<img width="1710" alt="Image" src="https://github.com/user-attachments/assets/5712ad0b-6560-4ab4-94b9-1f7d352b2695" />

**Comment by maxkaplan** [comment]
@indigotechtutorials thank you for reporting this frustrating experience.
I also noticed browser device emulation does not pass `allow_browser versions: :modern`
Is this a bug or a feature? 
Seems like a bad dev experience to me. 
I had to turn it off so I could keep moving.

**Comment by indigotechtutorials** [comment]
Im still not even sure of the intentions of adding the allow browser versions line and making it the default since as someone just trying to build a website I don't care about blocking old browsers 😂 this seems like a random edge use case that somehow got merged into main as a default

Please remove this

**Comment by frenkel** [comment]
Seems like a bug in the browser where they should have updated that version number.
