### ISSUE TITLE
Rails 7.2.0 is creating a pid file when the env var PIDFILE is unset

### ISSUE THREAD

**Issue by nickjj** [rails/rails#52558]
### Steps to reproduce

- Start your project with `rails s`
- Confirm `config/puma.rb` has `pidfile ENV["PIDFILE"] if ENV["PIDFILE"]`
- Hardcode `pidfile "/dev/null"` and the expected / actual behavior below still occurs

### Expected behavior

- `tmp/pids/server.pid` does not exist

### Actual behavior

- `tmp/pids/server.pid` does exist

### System configuration

**Rails version**: 7.2.0

**Ruby version**: 3.3.4

### Thoughts

I haven't dug into it but if you run `rails s --pid /dev/null` then no pid file gets created. Does this indicate that `rails s` is not adhering to the `pidfile` that Puma has configured?

**Comment by Earlopain** [comment]
I don't believe this is specific to 7.2, I distinctly remember having to do the same thing as yourself beforehand. By default `rails s` creates a pidfile in development, even if no `pidfile` directive is used.

Bit of extra info in #50669,  #50644 and #52073 (which looks relevant for point 3)

**Comment by nickjj** [comment]
Thank you for including the extra detail about `rails s` including a pidfile in development, I did not know that.

I was able to confirm that when I set the app to run in production the pidfile does not get created, but you can make a case that having the pidfile not get created in development is also beneficial. I've certainly had containers die in such a way where a lingering pid file existed and I had to manually delete it before I could up my app again.

In production the pid file almost doesn't matter in a containerized environment in production because you typically don't volume mount all of your directories and when the container dies in any way (graceful or non-graceful) its non-volume mounted file system will get reset back to the original image's version without the pid file.

**Comment by rafaelfranca** [comment]
Pid files in development are useful for the LSP to know if the server is running and where. I don't think we will change that.

This is by design, isn't an issue. If you don't want a pid file, you can explicitly pass the option to `rails s`

**Comment by c960657** [comment]
The wording in the generated `puma.rb`, [“Only use a pidfile when requested”](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/templates/config/puma.rb.tt#L36-L37), suggests that PID files are used only when explicitly requested using `ENV["PIDFILE"]`. It took me a while to figure out that in `development` it is [always enabled](https://github.com/rails/rails/blob/main/railties/lib/rails/commands/server/server_command.rb#L247), and it cannot be disabled using e.g. `pidfile nil`.

I suggest this logic is made more explicit/obvious by moving the it into puma.rb.tt.

**Comment by rafaelfranca** [comment]
Rails works with more servers than puma. We can't move the logic there. I'll just remove that comment from the puma config.
