### ISSUE TITLE
assert_selector not counted as assertion in IntegrationTest

### ISSUE THREAD

**Issue by Fjan** [rails/rails#52565]
### Steps to reproduce
The `assert_selector` assertion does not increase the assertion count in an IntegrationTest. Inside a SystemTest it works as expected. This can have the side effect of producing a warning in a test in rails 7.2.0

```ruby
class BodyTest < ActionDispatch::IntegrationTest
  test 'has body' do
    visit "/"
    assert_selector 'body'
  end
end
```

### Expected behavior

Test should complete without a warning.

### Actual behavior
It shows a warning:
`Test is missing assertions: "test_has_body"`

### System configuration
**Rails version**: 7.2.0

**Ruby version**: 3.3.4

**Comment by fatkodima** [comment]
This is a `capybara`'s bug (see https://github.com/teamcapybara/capybara/blob/0480f90168a40780d1398c75031a255c1819dce8/lib/capybara/node/matchers.rb#L109-L115), `self.assertions += 1` should be added somewhere in that method. Please, open a bug report there.

**Comment by Fjan** [comment]
The `self.assertions += 1` is here https://github.com/teamcapybara/capybara/blob/0480f90168a40780d1398c75031a255c1819dce8/lib/capybara/minitest.rb#L152 that's why it works fine in a system test.

**Comment by fatkodima** [comment]
I can't reproduce. Can you provide a sample app with the reproduction?

**Comment by Fjan** [comment]
You can reproduce by dropping this in a file in `test/integration` in a newly generated rails app,  and run the test:

```ruby
require "test_helper"
require 'capybara/rails'

class BodyTest < ActionDispatch::IntegrationTest
  include Capybara::DSL # Make the Capybara DSL available in integration tests
  test 'has body' do
    visit "/"
    assert_selector 'body'
  end
end
```

The same test will work fine as a system test. Is this a problem with how Capybara hooks into rails?

**Comment by fatkodima** [comment]
Reproduced. This works:
```ruby
require "test_helper"
require 'capybara/rails'
require 'capybara/minitest'

class BodyTest < ActionDispatch::IntegrationTest
  include Capybara::DSL # Make the Capybara DSL available in integration tests
  include Capybara::Minitest::Assertions

  test 'has body' do
    visit "/"
    assert_selector 'body'
  end
end
```

From the docs https://github.com/teamcapybara/capybara?tab=readme-ov-file#using-capybara-with-minitest

**Comment by Fjan** [comment]
Thank you! Apologies for not figuring that out that myself.

**Comment by fatkodima** [comment]
No problems 😉
