### ISSUE TITLE
Colour contrast on document action site makes code examples unreadable

### ISSUE THREAD

**Issue by barnaclebarnes** [rails/rails#52575]
### Steps to reproduce

Colour scheme on new documentation site is not accessible.

Go to a page such as https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#the-update-task and look for code samples/command. For example this one:

![CleanShot 2024-08-12 at 19 51 25@2x](https://github.com/user-attachments/assets/48fc8010-c165-47d6-9a6e-fd0104cb01e4)

### Expected behavior

It should use accessible colours.

### Actual behavior

You can't read it. Not sure if it is OK for some people but I have a red/green colourblindness and I find this impossible to read.

### System configuration

Rails 7.2
Latest Safari (17.5)

**Comment by rafaelfranca** [comment]
This isn't what I'm seeing both with dark or light theme. Can you make sure the css isn't cached in your browser? That might me it. If it is, I can see how force the cache to invalidate.

<img width="840" alt="Screenshot 2024-08-12 at 12 40 14 PM" src="https://github.com/user-attachments/assets/dade6d17-06e6-4771-91b9-9cafc9f7f7d3">

**Comment by rafaelfranca** [comment]
Yeah, cache is a problem. We will fix it.
