### ISSUE TITLE
Fresh `db/schema.rb` of a Rails app with PostgreSQL contains a Rubocop offense

### ISSUE THREAD

**Issue by Uaitt** [rails/rails#52579]
### Steps to reproduce
```bash
# assuming Rails 7.2.0 and an existing PostgreSQL connection locally
rails new example_app --database=postgresql
bin/rails db:create
bin/rails db:migrate
```

Then, running
```bash
cat db/schema.rb
```

you'll get
```rb
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[7.2].define(version: 0) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

end
````

and if you try to do `bin/rubocop db/schema.rb` you get:
```
Inspecting 1 file
C

Offenses:

db/schema.rb:16:1: C: [Correctable] Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body end.

1 file inspected, 1 offense detected, 1 offense autocorrectable
````

### Expected behavior

I expect that the freshly generated schema does not contain Rubocop offenses.

### Actual behavior

The fresh `db/schema.rb` contains a Rubocop offense.

### System configuration
**Rails version**: 7.2.0

**Ruby version**: 3.3.4

**Comment by fatkodima** [comment]
I wonder if we should fix it or add `schema.rb` file to the ignore list for rubocop?

**Comment by rafaelfranca** [comment]
Yes. I think so. `schema.rb` is a generated file and we don't want to have to conform to rubocop rules.

**Comment by Earlopain** [comment]
`schema.rb` is excluded when using `rubocop-rails`: https://github.com/rubocop/rubocop-rails/blob/d4a4ea7555ce186ebbdadd68f760d477ebf52932/config/default.yml#L13

**Comment by rafaelfranca** [comment]
Strange, why doesn't it work? https://github.com/rails/rubocop-rails-omakase/blob/main/rubocop.yml That gem uses rubocop-rails

**Comment by Earlopain** [comment]
See my edited comment above, I was a bit too late for you to see it.
