### ISSUE TITLE
`bin/brakeman` added when running `rails app:update` even without brakeman in Gemfile

### ISSUE THREAD

**Issue by etiennebarrie** [rails/rails#52576]
### Steps to reproduce

Upgrading a Rails 7.1 application to Rails 7.2 adds a `bin/brakeman` when running `bin/rails app:update` after upgrading the gem.

### Expected behavior

Either of these solutions would be acceptable:

* `bin/brakeman` is not added unless it's already in the Gemfile.
* `brakeman` is added to the Gemfile.

But the first one seems favorable.

### Actual behavior

`bin/brakeman` is added but doesn't work:

```console
$ bin/brakeman 
/Users/etienne/.gem/ruby/3.3.4/gems/bundler-2.5.17/lib/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable brakeman for gem brakeman. brakeman is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/etienne/.gem/ruby/3.3.4/gems/bundler-2.5.17/lib/bundler/rubygems_integration.rb:304:in `block in replace_bin_path'
	from bin/brakeman:7:in `<main>'
```

### System configuration
**Rails version**:
7.1.3.4 then 7.2.0
**Ruby version**:
3.3.4

**Comment by etiennebarrie** [comment]
Options for the app generator when running app:update are here:
https://github.com/rails/rails/blob/d7f93473682d9b64ab268a6736d5af2853e97ce2/railties/lib/rails/commands/app/update_command.rb#L62-L76

However similar options are guessed based on whether the gems have been loaded already and have defined a constant, which we cannot do here because the gem isn't loaded by default: https://github.com/rails/rails/blob/d7f93473682d9b64ab268a6736d5af2853e97ce2/railties/lib/rails/generators/rails/app/templates/Gemfile.tt#L49-L50

`brakeman` seems well behaved when being required, so maybe we could just try requiring it and use this to detect whether `skip_brakeman` should be used.

**Comment by Earlopain** [comment]
The same is probably true for rubocop as well

**Comment by etiennebarrie** [comment]
Good catch, `bin/thrust` as well.
