### ISSUE TITLE
Unable to pass `auto_increment` option to create_table in Rails 7.1

### ISSUE THREAD

**Issue by kenichi-sonoda** [rails/rails#52587]
We are using sharding in our application, and to ensure that IDs are unique across all shards, we have stopped using auto-increment. Instead, we assign IDs via a cache server and then insert them into the database. For this, we previously used the following create_table command:

``` Ruby
class CreateTests < ActiveRecord::Migration[7.0]
  def change
    create_table :tests, auto_increment: false do |t|
      t.string :name

      t.timestamps
    end
  end
end
```

However, in Rails 7.1, the id: :bigint, default: nil part is no longer present in the create_table command in the schema.rb.
Upon checking the actual database, we found that the ID column is set to AUTO INCREMENT,
which was not the case in Rails 7.0:

``` Ruby
  create_table "tests", id: :bigint, default: nil, charset: "utf8mb4", collation: "utf8mb4_bin", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
```

Additionally, when using ActiveRecord::Migration[7.1], an error occurs:

``` Ruby
class CreateTests < ActiveRecord::Migration[7.1]
  def change
    create_table :tests, auto_increment: false do |t|
      t.string :name

      t.timestamps
    end
  end
end
```

```
-- create_table(:tests, {:auto_increment=>false})
bin/rails aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

Unknown key: :auto_increment. Valid keys are: :temporary, :if_not_exists, :options, :as, :comment, :charset, :collation, :limit, :default, :precision, :unsigned
/srv/db/migrate/20240812133600_create_tests.rb:4:in `change'
```

The cause of this issue appears to be related to the following pull request, where the auto_increment option is not included among the expected options:
https://github.com/rails/rails/pull/46178/files#diff-5a1c923abf3a794dbc133959167f794b2479ea8bcd0b1deda7766c22f05e8dfeL328

I would like to know whether the exclusion of the auto_increment option was an oversight or if it was intentionally decided that this option would no longer be supported.

**Comment by byroot** [comment]
I suspect it's an oversight, PR welcome.
