### ISSUE TITLE
ActiveSupport 7.2.0 `NameError` from `active_support/delegation.rb:47`

### ISSUE THREAD

**Issue by aramprice** [rails/rails#52582]
### Steps to reproduce
Create `foo.rb` with the following contents:

```ruby
require "active_support/core_ext/module/delegation"

class Foo
  class Bar
    def baz
      puts "baz from #{self.class}"
    end
  end

  delegate :baz, to: Bar
end

puts Foo::Bar.new.baz
```

### Expected behavior
With the latest ActiveSupport (7.2.0) should behave like `activesupport-7.1.3.4`:

```shell
; ruby foo.rb
baz from Foo::Bar
``

### Actual behavior
With `activesupport-7.2.0` the code above produces the following error"

```shell
; ruby foo.rb
~/.gem/ruby/3.2.5/gems/activesupport-7.2.0/lib/active_support/delegation.rb:47:in `generate': uninitialized constant #<Class:ActiveSupport::Delegation>::Inflector (NameError)

          unless Inflector.safe_constantize(to.name).equal?(to)
                 ^^^^^^^^^
	from ~/.gem/ruby/3.2.5/gems/activesupport-7.2.0/lib/active_support/core_ext/module/delegation.rb:161:in `delegate'
	from foo.rb:12:in `<class:Foo>'
	from foo.rb:5:in `<main>'
```

### System configuration
**Rails version**:
n/a 
- `activesupport-7.2.0`

**Ruby version**:
- `ruby-3.2.5`

**Comment by rafaelfranca** [comment]
Thank you for the issue. Not an issue. You can use active support without requiring the top level file first.

This is documented at https://guides.rubyonrails.org/active_support_core_extensions.html#cherry-picking-a-definition.

Change your script to:

```
require "active_support"
require "active_support/core_ext/module/delegation"

class Foo
  class Bar
    def baz
      puts "baz from #{self.class}"
    end
  end

  delegate :baz, to: Bar
end

puts Foo::Bar.new.baz
```

**Comment by aramprice** [comment]
@rafaelfranca - thanks for the clarification. I'm seeing this issue with [factory_bot](https://github.com/thoughtbot/factory_bot/blob/main/lib/factory_bot.rb#L2) and will open an issue there.
