### ISSUE TITLE
Underscore-prefixed options to `enum` are silently ignored

### ISSUE THREAD

**Issue by mattbrictson** [rails/rails#52586]
### Steps to reproduce

I had an enum defined in the deprecated style:

```ruby
enum status: { open: "open", closed: "closed" }, _prefix: true
```

Upon upgrading to Rails 7.2, I saw this warning:

> Defining enums with keyword arguments is deprecated and will be removed
> in Rails 8.0. Positional arguments should be used instead
>
> `enum :status, {:open=>"open", :closed=>"closed"}`

Following the instructions in the deprecation message, I changed my code to:

```ruby
enum :status, { open: "open", closed: "closed" }, _prefix: true
```

To my surprise, the `:_prefix` option is now no longer honored, changing the behavior of the enum and breaking my tests. This was not mentioned in the deprecation message or in the Rails 7.2 upgrade notes.

### Expected behavior

I expect an error to be raised (e.g. "`:_prefix is not a valid enum option`) or a warning to be emitted.

It would also be nice if the original deprecation warning had included non-underscored options in its code recommendation, i.e.:

> Defining enums with keyword arguments is deprecated and will be removed
> in Rails 8.0. Positional arguments should be used instead
>
> `enum :status, {:open=>"open", :closed=>"closed"}, prefix: true`

### Actual behavior

The `:_prefix` option is silently ignored and has no apparent effect on the enum.

### System configuration

**Rails version**:Rails 7.2.0

**Ruby version**: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-darwin23]

**Comment by rafaelfranca** [comment]
> This was not mentioned in the deprecation message or in the Rails 7.2 upgrade notes.

That was always the API for enums even before 7.2. See https://api.rubyonrails.org/v7.1/classes/ActiveRecord/Enum.html the `_prefix` isn't even documented there. But, sure, we can be more loudly when people are using old API. Although, we don't validate all the `options` to allow libraries to extend enums, so `_prefix` will likely raise an error on 7.2, but will not going forward.

**Comment by mattbrictson** [comment]
> Although, we don't validate all the options to allow libraries to extend enums, so _prefix will likely raise an error on 7.2, but will not going forward.

Make sense 👍
