### ISSUE TITLE
`IF NOT EXISTS` for `add_index` can lead to accidental invalid indexes in PostgreSQL on lock timeouts

### ISSUE THREAD

**Issue by shayonj** [rails/rails#52583]
### Steps to reproduce

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", "~> 7.0.0"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "test_db")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :articles, force: true do |t|
    t.string :title
    t.text :content
  end
end

class Article < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_index_creation_with_if_not_exists
    # Simulate a long-running query that will cause a lock timeout
    ActiveRecord::Base.connection.execute("CREATE OR REPLACE FUNCTION simulate_long_query() RETURNS void AS $$ BEGIN PERFORM pg_sleep(30); END; $$ LANGUAGE plpgsql;")
    ActiveRecord::Base.connection.execute("SET lock_timeout = '5s';")

    # In one session, start a long-running query
    Thread.new do
      ActiveRecord::Base.connection.execute("BEGIN; SELECT simulate_long_query();")
    end

    # Wait a moment for the other thread to start
    sleep(1)

    # Try to create an index concurrently
    assert_raises(ActiveRecord::LockWaitTimeout) do
      ActiveRecord::Base.connection.add_index :articles, :title, algorithm: :concurrently
    end

    # Now try again with IF NOT EXISTS
    ActiveRecord::Base.connection.execute("CREATE INDEX CONCURRENTLY IF NOT EXISTS index_articles_on_title ON articles (title);")

    # Check if the index is valid
    result = ActiveRecord::Base.connection.execute("SELECT indisvalid FROM pg_index WHERE indexrelid = 'index_articles_on_title'::regclass;")
    
    assert_equal false, result.first['indisvalid'], "Index should be invalid but is marked as valid"
  end
end
```

- `createdb test_db` (to setup the DB)
- `ruby bug_test.rb` (notice the spec passes and it validates that the index is invalid)

### Expected behavior

When creating an index concurrently fails due to a lock timeout, and a subsequent attempt is made using `IF NOT EXISTS`, the operation should either fail or create a valid index.

### Actual behavior

When the initial `CREATE INDEX CONCURRENTLY` fails due to a lock timeout, it leaves an invalid index entry in the system catalogs. A subsequent `CREATE INDEX CONCURRENTLY IF NOT EXISTS` silently completes without actually creating a valid index. This leaves an invalid index in place, which can lead to unexpected query performance issues.

### System configuration

**Rails version**: 7.0.0
**Ruby version**: 3.0.0

### Additional context

The current behavior of `IF NOT EXISTS` with concurrent index creation can lead to subtle and hard-to-debug issues in production environments. When a concurrent index creation fails (e.g., due to a lock timeout), it leaves behind an invalid index entry. Subsequent attempts to create the index with `IF NOT EXISTS` will silently do nothing, leaving the invalid index in place.

This is particularly problematic in the context of Rails migrations, where the migration might be marked as completed even though the index wasn't actually created successfully. This can lead to performance issues that are only discovered much later when investigating slow queries.

### Proposed solution

We could try few different routes and I am more than happy to propose a PR based on what makes sense

- If index exists when `if_not_exists` is present and if the index is invalid, raise an exception. This will at least alert the user so they can manually intervene.
- Build an internal catch/retry mechanism where if lock timeout is raised and `if_not_exists` is present then rails tries to drop the index and then create it again, something like below
- Instead of using `IF NOT EXISTS`, rails queries the PG catalog to check if a valid index exists, if so, then it continues, otherwise it drops the invalid index and retries. 
- Something else?

```ruby
def safe_add_index_with_retry(table, columns, options = {})
    index_name = options[:name] || index_name(table, columns)
    add_index(table, columns, **options)
  rescue ActiveRecord::LockWaitTimeout
    begin
      execute("DROP INDEX CONCURRENTLY IF EXISTS #{index_name}")
    rescue ActiveRecord::StatementInvalid => e
      Rails.logger.error("Failed to remove index: #{e.message}")
      raise
    end

    retries = 0
    begin
      add_index(table, columns, **options)
    rescue ActiveRecord::LockWaitTimeout => e
      raise e unless retries < 5
      retries += 1
      sleep(2**retries)
      retry
    end
  end
```

**Comment by rafaelfranca** [comment]
Thank you for the issue but this isn't an rails issue. Rails is sending commands to postgresql like they are instructed by you. If postgresq created a invalid index when a lock timeout happend it is an issue on postgresql

**Comment by byroot** [comment]
We do all sort of stuff to workaround various database idiosyncrasies though.

I agree with you I wouldn't consider this a Rails bug, hence should be closed. But better handling this footgun would be a nice feature hence a PR is welcome.

**Comment by shayonj** [comment]
Yeah, I agree. This is not a rails bug, but the if_not_exists is so easy to use and run into this footgun. I'll look into a PR. Thanks!
