### ISSUE TITLE
`@rails/ujs` npm package has not been released with a 7.2.0 version

### ISSUE THREAD

**Issue by klaustopher** [rails/rails#52594]
### Steps to reproduce
In the [upgrade guide](https://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#moving-between-versions) it states that all entries in `Gemfile` and `package.json` should be updated to the desired version of rails:

> Change the versions for Rails JavaScript packages in package.json and run bin/rails javascript:install if running jsbundling-rails

Changed the entry for `@rails/ujs` to version 7.2.0, and tried `npm install`.

### Expected behavior
NPM install succeeds and everything is installed

### Actual behavior
Install fails:

```
$ npm install
npm error code ETARGET
npm error notarget No matching version found for @rails/ujs@^7.2.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
```

I know from the changelog that there are no changes in the UJS files, but I think that a matching version should be available on [npm](https://www.npmjs.com/package/@rails/ujs)

### System configuration
**Rails version**: 7.2.0

**Ruby version**: 3.3.4

**Comment by rafaelfranca** [comment]
@rails/ujs was deprecated in 7.1 and while still exists we aren't planning to do any new release

**Comment by rafaelfranca** [comment]
See https://github.com/rails/rails/pull/50535

**Comment by klaustopher** [comment]
@rafaelfranca Thanks for the hint, did not know that it was deprecated. 

I looked through the release notes for 7.2.0 again and also the doc changes associated with #50535 and it mentions two fixes for `@rails/ujs` but not that it has been removed.
Maybe it‘s
Possible to add that somewhere and point to the docs about how to replace it with turbo?

**Comment by rafaelfranca** [comment]
Yes. That was an oversight from my part. We should definitely have documented that change. Do you want to open a PR? I think we should add to the release notes, and upgrading guide. Although you necessarily don't need to change to turbo right now. You can continue to use the version 7.1.0.
