### ISSUE TITLE
False positive for enum without DB column in rails 7.2 in parallelized tests

### ISSUE THREAD

**Issue by robbevp** [rails/rails#52607]
While updating an app to 7.2, my CI started throwing a lot of errors around enums:
```
RuntimeError: Undeclared attribute type for enum 'post_type' in Post. Enums must be backed by a database column or declared with an explicit type via `attribute`.
```
These are false positives as (1) the DB column exists (2) the tests worked locally/work when not executed in parallel.

I _think_ the actual issue might not be related to enums, but just be some underlying problem in how attributes are initialized. However, I'm not knowledgeable enough about these rails internals to be really sure of what is going on 

### Steps to reproduce
* Add an enum backed by a Postgres enum to a model
* Add a test that calls the model in some way that loads the attribute info
* Run tests in parallel
* Run tests using `config.eager_load = true` ~~(This is needed in my actual app but not in the reproduction below)~~

I had to add a bunch of stuff to the basic script to reproduce the error and had to create a separate schema file. There might be a better way to reproduce this
```ruby
# frozen_string_literal: true

ENV['RAILS_ENV'] ||= 'test'

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "~> 7.2.0"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "pg", "~> 1.5.7"

  gem "minitest", "5.24.1" # https://github.com/minitest/minitest/issues/1007
end

require "active_record"
require "action_controller/railtie"
require "logger"

ActiveRecord::Base.configurations = { 
  "test" => {
    "adapter"=>"postgresql",
    "database"=>"test",
    "host"=>"localhost",
    "username"=>"rails",
    "password"=>"rails"
  }
}

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter:  "postgresql",
  host:     "localhost",
  username: "rails",
  password: "rails",
  database: "test")
ActiveRecord::Base.logger = Logger.new(STDOUT)


class Application < Rails::Application
  # Setting eager load to `true` matters in my test setup
  # but this does not make a difference in the reproduction
  config.eager_load = false
end

Rails.application.initialize!

class Post < ActiveRecord::Base
  enum :post_type, { one: 'one', two: 'two', three: 'three' }
end


class ActiveSupport::TestCase
  parallelize(
    workers: 0, # The amount of workers doesn't matter, as long as `parallelize` is used
    threshold: 1 # The threshold does matter, if you set this to 2 the tests will work
  )
end

require "rails/test_help"

class BugTest < ActiveSupport::TestCase
  def test_one
    Post.new

    assert true
  end

  def test_two
    Post.new

    assert true
  end
end
```

In a separate `db/schema.rb` file
```ruby
ActiveRecord::Schema.define do
  create_enum "my_enum", ["one", "two", "three"]

  create_table :posts, force: true do |t|
    t.enum :post_type, enum_type: :my_enum
  end
end
```

### Expected behavior
The DB column should be detected, since this worked in rails 7.1.X (and many versions before that)

### Actual behavior
An error is throw saying that the enum does not have a matching DB column
```
RuntimeError: Undeclared attribute type for enum 'post_type' in Post. Enums must be backed by a database column or declared with an explicit type via `attribute`.
    vendor/ruby/gems/activerecord-7.2.0/lib/active_record/enum.rb:259:in `block in _enum'
    vendor/ruby/gems/activemodel-7.2.0/lib/active_model/attribute_registration.rb:71:in `block in apply_to'
    vendor/ruby/gems/activemodel-7.2.0/lib/active_model/attribute_registration.rb:69:in `each'
    vendor/ruby/gems/activemodel-7.2.0/lib/active_model/attribute_registration.rb:69:in `apply_to'
    vendor/ruby/gems/activemodel-7.2.0/lib/active_model/attribute_registration.rb:87:in `block in apply_pending_attribute_modifications'
    vendor/ruby/gems/activemodel-7.2.0/lib/active_model/attribute_registration.rb:86:in `each'
    vendor/ruby/gems/activemodel-7.2.0/lib/active_model/attribute_registration.rb:86:in `apply_pending_attribute_modifications'
    vendor/ruby/gems/activerecord-7.2.0/lib/active_record/attributes.rb:249:in `_default_attributes'
    vendor/ruby/gems/activemodel-7.2.0/lib/active_model/attribute_registration.rb:38:in `attribute_types'
    vendor/ruby/gems/activerecord-7.2.0/lib/active_record/attribute_methods.rb:260:in `_has_attribute?'
    vendor/ruby/gems/activerecord-7.2.0/lib/active_record/inheritance.rb:61:in `new'
    script.rb:67:in `test_one'
```

### System configuration
**Rails version**: 7.2

**Ruby version**: 3.2.4

**Comment by rafaelfranca** [comment]
Probably caused by 6d00605f955a992fb52d4a1006f7c50b99a2e858

**Comment by rafaelfranca** [comment]
I tried to reproduce with the script and I can but it is because the script doesn't create the table so doesn't have the column.

This script pass without any problem:

```ruby
# frozen_string_literal: true

ENV['RAILS_ENV'] ||= 'test'

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", path: "../rails"

  gem "pg", "~> 1.5.7"

  gem "minitest", "5.24.1" # https://github.com/minitest/minitest/issues/1007
end

require "active_record"
require "action_controller/railtie"
require "logger"

ActiveRecord::Base.configurations = {
  "test" => {
    "adapter"=>"postgresql",
    "database"=>"test",
    "host"=>"postgres",
    "username"=>"postgres",
    "password"=>"postgres"
  }
}

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter:  "postgresql",
  host:     "postgres",
  username: "postgres",
  password: "postgres",
  database: "test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_enum "my_enum", ["one", "two", "three"]

  create_table :posts, force: true do |t|
    t.enum :post_type, enum_type: :my_enum
  end
end


class Application < Rails::Application
  # Setting eager load to `true` matters in my test setup
  # but this does not make a difference in the reproduction
  config.eager_load = false
end

Rails.application.initialize!

class Post < ActiveRecord::Base
  enum :post_type, { one: 'one', two: 'two', three: 'three' }
end


class ActiveSupport::TestCase
  parallelize(
    workers: 0, # The amount of workers doesn't matter, as long as `parallelize` is used
    threshold: 1 # The threshold does matter, if you set this to 2 the tests will work
  )
end

require "rails/test_help"

class BugTest < ActiveSupport::TestCase
  def test_one
    Post.new

    assert true
  end

  def test_two
    Post.new

    assert true
  end
end
```

Can you modify the script so it fails?

**Comment by robbevp** [comment]
Hi @rafaelfranca
I modified your version to make it fail again. Seems I made some wrong assumptions while debugging. The number of workers should be >= 2 and `config.eager_load = true`

The script below does fail for me with the error
```
./db/schema.rb doesn't exist yet. Run \`bin/rails db:migrate\` to create it, then try again.
```
 Is there a way too keep the schema inline and have parallelization?

After creating a separate schema file, I get the error described above on 7.2.0, but not on 7.1.3.4. I added a print of `Post.columns` to verify that the column itself exists

```ruby
# frozen_string_literal: true

ENV['RAILS_ENV'] ||= 'test'

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "7.2.0"

  gem "pg", "~> 1.5.7"

  gem "minitest", "5.24.1" # https://github.com/minitest/minitest/issues/1007
end

require "active_record"
require "action_controller/railtie"
require "logger"

ActiveRecord::Base.configurations = {
  "test" => {
    "adapter"=>"postgresql",
    "database"=>"test",
    "host"=>"localhost",
    "username"=>"rails",
    "password"=>"rails"
  }
}

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  adapter:  "postgresql",
  host:     "localhost",
  username: "rails",
  password: "rails",
  database: "test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_enum "my_enum", ["one", "two", "three"]

  create_table :posts, force: true do |t|
    t.enum :post_type, enum_type: :my_enum
  end
end


class Application < Rails::Application
  config.eager_load = true
end

Rails.application.initialize!

class Post < ActiveRecord::Base
  enum :post_type, { one: 'one', two: 'two', three: 'three' }
end


class ActiveSupport::TestCase
  parallelize(
    workers: 2,
    threshold: 1
  )
end

require "rails/test_help"

class BugTest < ActiveSupport::TestCase
  def test_one
    pp Post.columns
    Post.new

    assert true
  end

  def test_two
    Post.new

    assert true
  end
end
```

**Comment by robbevp** [comment]
Bisecting leads to https://github.com/rails/rails/commit/6d00605f955a992fb52d4a1006f7c50b99a2e858 as the first bad commit.

When running the script above the subtype at [activerecord/lib/active_record/enum.rb#L258-L259](https://github.com/rails/rails/blob/7-2-stable/activerecord/lib/active_record/enum.rb#L258-L259) is  `#<ActiveModel::Type::Value:0x000000010dec7fd0 @limit=nil, @precision=nil, @scale=nil>`
If eager load is false, or if the tests aren't parallelized, the subtype is `#<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x000000012b056000 @limit=nil, @precision=nil, @scale=nil>`

While trying to work backwards to see where this difference comes from, I found that [ActiveRecord::ConnectionAdapter::PostgreSQL::Question#lookup_cast_type_from_column](https://github.com/rails/rails/blob/7-2-stable/activerecord/lib/active_record/connection_adapters/postgresql/quoting.rb#L189-L192) has the same input type, but returns the different subtypes
```
#<ActiveRecord::ConnectionAdapters::PostgreSQL::Column:0x0000000115ab9300
 @collation=nil,
 @comment=nil,
 @default=nil,
 @default_function=nil,
 @generated="",
 @identity=nil,
 @name="post_type",
 @null=true,
 @serial=nil,
 @sql_type_metadata=
  #<ActiveRecord::ConnectionAdapters::SqlTypeMetadata:0x000000014550b810
   @limit=nil,
   @precision=nil,
   @scale=nil,
   @sql_type="my_enum",
   @type=:enum>>
```

**Comment by rafaelfranca** [comment]
@jonathanhefner

**Comment by duduribeiro** [comment]
I'm also seeing this after upgrading to Rails 7.2 

As workaround we disabled parallel tests until this is fixed. Like pointed by @robbevp, the weird thing is that this works locally and only fail on CI with parallel tests enabled.

**Comment by duduribeiro** [comment]
@jonathanhefner I'm trying to debug this but I still didn't have success and will try to check if I can help somehow with this tomorrow. 

The only odd thing that I noticed is that:
when calling `connection.lookup_cast_type_from_column(column)` each version (one with eager_load = true and another with eager_load = false) uses a different OID to look for the column.

I added some logs on `activerecord/lib/active_record/type/hash_lookup_type_map.rb # register_type` and on `activerecord/lib/active_record/model_schema.rb # type_for_column`:

```
# eager_load: false
registered enum type: 24578 #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff639f4c38> 
registered enum type: 24578 #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff63acc930> 
registered enum type: 24632 #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff95a41b28> 
registered enum type: 24631 #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff95a42b18> 
registered enum type: 24631 #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff959fb808> 
registered enum type: 24632 #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff959fb358> 
type_for_column post_type oid: 24632 - #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff959fb358> 
type_for_column post_type oid: 24631 - #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff959fb808> 

########

# eager_load: true
registered enum type: 24578 #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff716f0c68> 
registered enum type: 24578 #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff70c5cb80> 
registered enum type: 24632 #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff70eb4bd0> 
registered enum type: 24631 #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff70eb5418> 
registered enum type: 24632 #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff70f50df0> 
registered enum type: 24631 #<ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum:0x0000ffff70f51688> 
type_for_column post_type oid: 24578 - #<ActiveModel::Type::Value:0x0000ffff70faa198> 
type_for_column post_type oid: 24578 - #<ActiveModel::Type::Value:0x0000ffff70fc6208> 
```

on my machine the version with eager_load tries to find a type for the OID 24578 while the version without eager_load tries to find the type for the OID `24632` and `24631`.  And even on version with eager_load have registered the OID 24578 with `ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum` type, it returns `ActiveModel::Type::Value` when calling `lookup_cast_type_from_column`. Tomorrow I will try to find if there is any issue with `type_map.lookup` method to see why it is not returning `ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Enum` when doing the lookup. 
🍻

**Comment by gstokkink** [comment]
Running into the same issue here, can confirm it only occurs when running tests in parallel with multiple workers _and_ eager loading enabled.

**Comment by gstokkink** [comment]
For what it's worth, this issue does _not_ occur if I comment out this bit of code:

https://github.com/rails/rails/blob/v7.2.0/railties/lib/rails/testing/maintain_test_schema.rb#L11-L15

Might explain why the issue only occurs when eager loading is enabled.

**Comment by rafaelfranca** [comment]
That makes the issue disappear but isn't the place where we should fix. We should understand why the `connection.lookup_cast_type_from_column(column)` is returning different values.

**Comment by gstokkink** [comment]
Oh no, I agree, just saying that that's probably why eager loading is a prerequisite for this issue to appear. The forced schema loading seems to trigger it.

**Comment by rafaelfranca** [comment]
I think I'll just revert #49769. It is uncommon to define enums not backed by a column. Having enums not working on postgresql on CI is worse than not having non-database backed enums work. That PR wasn't released on 7-1-stable, even though the fix was merged and nobody asked for a release.

**Comment by rafaelfranca** [comment]
Can you confirm that https://github.com/rails/rails/pull/new/rm-test-fix-52607 fix this issue?

**Comment by arcreative** [comment]
@rafaelfranca Just curious if this was a fluke or if I should be more restrictive with my version specifications in the future? It seems that this being a breaking change was unintentional for a minor release, but if not, I'll make things more stringent moving forward. Thanks!

**Comment by rafaelfranca** [comment]
This is a bug as any other, bugs happens, no matter the version. This wasn't intended if that is what you asking.

**Comment by duduribeiro** [comment]
@rafaelfranca just tested and everything worked just fine.



![Image](https://github.com/user-attachments/assets/fecc8e3c-e1ff-4c83-9bab-c4fe604bb85d)

**Comment by robbevp** [comment]
> Can you confirm that https://github.com/rails/rails/pull/new/rm-test-fix-52607 fix this issue?

This fix also works fine here, but for my reproduction and actual app

**Comment by gstokkink** [comment]
Fixed here as well.

**Comment by duduribeiro** [comment]
Thanks so much @rafaelfranca. 
I will try to investigate if I can help with https://github.com/rails/rails/issues/49717 somehow.

**Comment by therealrodk** [comment]
I got this error locally after adding an enum column to a brand new Rails 8.1.2 app. The error was resolved after restarting my server.
