### ISSUE TITLE
ActiveRecord model attributes info does not show up in the Rails console after invoking `lease_connection`

### ISSUE THREAD

**Issue by rodrigoargumedo** [rails/rails#52601]
### Steps to reproduce

- Create a new app with PostgreSQL adapter
- Open the newly created app in a dev container.
- Generate models described in the template (or closely similar) and migrate the database
- Pop open a rails console
- Type in the model name and hit enter
- Type `Post.lease_connection`

Rails Template Code:
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "postgresql", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.comments << Comment.create!

    assert_equal 1, post.comments.count
    assert_equal 1, Comment.count
    assert_equal post.id, Comment.first.post.id
  end
end
```

Rails Console:
```ruby
rails-app(dev)> Post
=> Post (call 'Post.lease_connection' to establish a connection)
rails-app(dev)> Post.lease_connection
=> #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x0000000000c7d8 env_name="development" role=:writing>
rails-app(dev)> Post
=> Post (call 'Post.lease_connection' to establish a connection)
```

### Expected behavior
The leased connection should return the model attributes as such:

`Post(id: integer, created_at: datetime, updated_at: datetime)`

And:

`Comment(id: integer, post_id: integer, created_at: datetime, updated_at: datetime)`

### Actual behavior
It instead returns the following message: `Post (call 'Post.lease_connection' to establish a connection)` and `Comment (call 'Comment.lease_connection' to establish a connection)`

### System configuration
**Rails version**: 7.2.0

**Ruby version**: 3.3.1

**Comment by byroot** [comment]
Indeed. `lease_connection` doesn't actually force the connection to be established, this is happening since we made connection establishment fully lazy.

As a short term workaround you can do: `Post.lease_connection.verify!`. I think the proper fix here would be to just update the message to say to use `.load_schema`.

**Comment by byroot** [comment]
https://github.com/rails/rails/pull/52613
