### ISSUE TITLE
Memory leak and performance degradation with IsolatedExecutionState == `:fiber`

### ISSUE THREAD

**Issue by rsamoilov** [rails/rails#52617]
### Steps to reproduce

I am seeing performance degradation and increased memory usage with ActiveRecord 7.2 in fiber-based environments. It looks like accessing connection pool methods, like `release_connection` or `enable_query_cache!` introduces memory leaks.

**ActiveRecord 7.1 Gemfile**

```ruby
source "https://rubygems.org"

gem "pg"
gem "activerecord", "7.1.3.4", require: "active_record"
gem "puma", "~> 6"
gem "rack", "~> 2"
```

**ActiveRecord 7.2 Gemfile**

```ruby
source "https://rubygems.org"

gem "pg"
gem "activerecord", "7.2.0", require: "active_record"
gem "puma", "~> 6"
gem "rack", "~> 2"
```

**Script**

```ruby
# frozen_string_literal: true

require "bundler/setup"
Bundler.require(:default)

ActiveSupport::IsolatedExecutionState.isolation_level = :fiber
ActiveRecord::Base.establish_connection("postgresql://localhost")

app = ->(_) do
  Fiber.new {
    ActiveRecord::Base.connection_handler.clear_active_connections!
    [200, {}, ["Hello world"]]
  }.resume
end

run app
```

Running the script with `bundle exec puma config.ru` and testing with `wrk http://localhost:9292 -d 30s`.

**ActiveRecord 7.1.3.4 + Ruby 3.3.3 results:**

RPS: 27 163;
Memory usage: 45MB;

**ActiveRecord 7.2.0 + Ruby 3.3.3 results:**

RPS: 17 431;
Memory usage: 1778MB;

**ActiveRecord 7.2.0 + Ruby 3.2.2 results:**

RPS: 974;
Memory usage: 153MB;

### Expected behavior

There are no differences in memory usage and performance between ActiveRecord 7.1 and ActiveRecord 7.2.

### Actual behavior

Setting `ActiveSupport::IsolatedExecutionState.isolation_level` to `:fiber` and accessing Active Record connection pool methods leads to increased memory usage and performance degradation.

### System configuration

**OS**: macOS 14.6.1
**Rails version**: 7.2.0
**Ruby version**: 3.3.3

**Comment by byroot** [comment]
I have a tentative fix here: https://github.com/rails/rails/pull/52618, but I'll likely refine it tomorrow.

In short, these aren't fully leaked because there is the connection reaper to clear these references on a regular basis. This code was mostly written for threads so it's not expected that you'd commonly spawn ephemeral threads that would query Active Record.

I suppose it's more common to do that with Fibers, so only relaying on the reaper for that isn't sufficient and we should instead either eagerly prune or use a weak reference.

**Comment by byroot** [comment]
Backported to 7-2-stable.

**Comment by rsamoilov** [comment]
Hey @byroot , thank you for the quick fix! I can see things work as expected with Ruby 3.3 now, but the issue still exists with Ruby 3.2.

**Ruby 3.2.4:**
RPS: 1383;
Memory usage: 125MB;

Do you want me to create a new issue?

**Comment by byroot** [comment]
I'm using the following script to reproduce:

```ruby
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", path: "/Users/byroot/src/github.com/byroot/rails"#"7.2"
  gem "sqlite3"
end
require "sqlite3"
require "active_record"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: "/tmp/leak.sqlite3")

ActiveRecord::Schema.define do
  create_table :posts, id: { type: :string }, force: true do |t|
  end

  create_table :comments, force: true do |t|
    # The `default: ""` option here is the key to reproducing the bug 
    t.string :post_id, default: ""
  end
end


ActiveSupport::IsolatedExecutionState.isolation_level = :fiber

20.times do
  1_000.times do
    Fiber.new {
      ActiveRecord::Base.connection_handler.clear_active_connections!
      [200, {}, ["Hello world"]]
    }.resume
  end
  GC.start
  puts `ps -o rss= -p #{$$}`
end
```

The memory usage is indeed higher for me on 3.2.2, but that's likely because we can't use `WeakKeyMap` on 3.2, and in both cases it's stable.

~200M on 3.3 on my machine and ~300M on 3.2.

Are you seeing something different?

**Comment by byroot** [comment]
Nevermind, I see you're talking about latency, not memory usage, it does indeed seem quite lower on 7.2 compare to 7.1. I'll have a look.

**Comment by byroot** [comment]
Alright, the Ruby 3.2- fallback for WeakKeyMap does indeed have really bad performance :s 

I'll try to figure something.

**Comment by byroot** [comment]
Alright, https://github.com/rails/rails/pull/52632 solves the performance issue and doesn't re-introduce the memory one.
