### ISSUE TITLE
belongs_to_required_validates_foreign_key behaves inconsistently on false-y foreign keys of newly created objects

### ISSUE THREAD

**Issue by gregorbg** [rails/rails#52614]
### Steps to reproduce

When configuring the Rails 7.1 upgrade, one of the new configuration flags is called `active_record.belongs_to_required_validates_foreign_key` (see https://guides.rubyonrails.org/configuring.html#config-active-record-belongs-to-required-validates-foreign-key)

When set to `false` (which is the new 7.1 default) the validations of my AR model behave differently depending on whether the foreign key is `''` (the empty string) or `nil`, even though both are false-y and clearly don't (shouldn't) exist in the database.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "7.1.3.4"
  gem "sqlite3", "~> 1.4"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, id: { type: :string }, force: true do |t|
  end

  create_table :comments, force: true do |t|
    # The `default: ""` option here is the key to reproducing the bug 
    t.string :post_id, default: ""
  end
end

# The config value in question that is part of `config.load_defaults 7.1`
ActiveRecord.belongs_to_required_validates_foreign_key = false

class Post < ActiveRecord::Base
end

class Comment < ActiveRecord::Base
  # The `required: true` part is crucial and is only written here because
  # in the dummy script, `config.load_defaults 5.0` never runs...
  belongs_to :post, required: true
end

class BugTest < Minitest::Test
  def test_association_stuff
    comment_nil_fk = Comment.new(post_id: nil)
    comment_empty_fk = Comment.new(post_id: '')

    assert_equal false, comment_nil_fk.valid?
    assert_equal false, comment_empty_fk.valid?

    assert_equal ["must exist"], comment_nil_fk.errors[:post]
    assert_equal ["must exist"], comment_empty_fk.errors[:post]
  end
end
```

### Expected behavior
Both `Comment` records should be invalid, as they point to an entity that does not exist.

### Actual behavior
One is reported as valid and the other one isn't

### Context
I have managed to isolate the root cause of the issue: In my schema definition, the foreign key is defined as follows
```ruby
create_table :comments, force: true do |t|
  # The `default: ""` option here is the key to reproducing the bug
  t.string :post_id, default: ""
end
```

Looking at the [ActiveRecord source code](https://github.com/rails/rails/blob/v7.1.3.4/activerecord/lib/active_record/associations/builder/belongs_to.rb#L125-L140), the new option in 7.1 is implemented in the following snippet
```ruby
if required
  if ActiveRecord.belongs_to_required_validates_foreign_key
    model.validates_presence_of reflection.name, message: :required
  else
    condition = lambda { |record|
      foreign_key = reflection.foreign_key
      foreign_type = reflection.foreign_type

      record.read_attribute(foreign_key).nil? ||
        record.attribute_changed?(foreign_key) ||
        (reflection.polymorphic? && (record.read_attribute(foreign_type).nil? || record.attribute_changed?(foreign_type)))
    }

    model.validates_presence_of reflection.name, message: :required, if: condition
  end
end
```

Specifically, the return value of the lambda always catches the first of my test cases when the FK is nil. However, the second OR-part reads `record.attribute_changed?(foreign_key)` and that returns `false` if the value I'm initializing to is the same as the DB default value.

Now we cannot easily change the ID of our parent table to int. Too many historical debt for that. And the child table wants to prevent `nil` on the FK column, so `""` (the empty string) seems like the only reasonable default value.

When creating a new entry from a frontend form, and the user forgets to enter something in the "What are you commenting on" field, the `simple_form` submits the `<input>` content as empty string, and the newly created `Comment` thereby gets initialized with an empty string. This behavior finally leads to this bug report, because then I would expect the model validations to complain.

### System configuration
**Rails version**: 7.1.3.4

**Ruby version**: 3.3.0

**Comment by byroot** [comment]
> even though both are false-y and clearly don't (shouldn't) exist in the database.

They aren't though. `""` isn't falsey in Ruby nor SQL. So from Active Record point of view (and SQL) there is a value for that column.

I think there two things you could do, either change this column to not have a default, so it is initialized to `nil`, or add a normalizer:

```ruby
class Comment < ActiveRecord::Base
  belongs_to :post, required: true
  normalizes :post_id, with: :presence.to_proc
end
```

But I don't think this is a Rails bug.

**Comment by gregorbg** [comment]
Thanks for the quick response! I take the blame for not being precise in my description, so let me clarify: `"".presence` does return `nil`, that's what I meant by "falsey".

In the ActiveRecord snippet that I shared, wouldn't it make sense to replace the `nil?` check (that very strictly only checks for the `nil` value itself) with something more "forgiving" that also triggers for values where `.present?` returns `false`?

**Comment by byroot** [comment]
> wouldn't it make sense to replace the `nil?` check (that very strictly only checks for the `nil` value itself) with something more "forgiving" that also triggers for values where `.present?` returns `false`?

No, that would be inconsistent with how Active Record behaves. But I showed you how you can make it behave that way with `normalizes`.

**Comment by gregorbg** [comment]
Cool, gotcha! I don't have any deep insight into the principles that drive AR internally, so it was meant as a genuine question.

Thanks a lot for your advice!
