### ISSUE TITLE
editing new credentials for non-standard environment results in no key file being created

### ISSUE THREAD

**Issue by patrick99e99** [rails/rails#52620]
### Steps to reproduce
```
%> ./bin/rails credentials:edit --environment development
Adding config/credentials/development.key to store the encryption key: <<KEY>>

Save this in a password manager your team can access.

If you lose the key, no one, including you, can access anything encrypted with it.

      create  config/credentials/development.key

Ignoring config/credentials/development.key so it won't end up in Git history:

      append  .gitignore
%> ./bin/rails credentials:edit --environment integration
%> ls config/credentials/
development.key     development.yml.enc integration.yml.enc
```

### Expected behavior
integration.key should have been created

### Actual behavior
integration.key was not created

### System configuration
Rails 7.0.8.4

Ruby 3.3.0

**Comment by willianveiga** [comment]
I can't reproduce it on rails main (4bb2227640531c877e30cc96f10df0c298dc3331). The `integration.key` was created.

**Comment by willianveiga** [comment]
I can't reproduce it either on Rails 7.0.8.4 with Ruby 3.3.4.

**Comment by patrick99e99** [comment]
I have since updated to 7.2.1, and just tried this again and it did create an integration.key file this time.. so..... nevermind I guess!
