### ISSUE TITLE
Brakeman warnings for edge applications

### ISSUE THREAD

**Issue by peterberkenbosch** [rails/rails#52624]
### Steps to reproduce

```sh
rails new demo --main
cd demo
bin/brakeman --no-pager
```
### Expected behavior
No warnings 

### Actual behavior

== Warnings ==

Confidence: High
Category: Attribute Restriction
Check: ModelAttributes
Message: Mass assignment is not restricted using `attr_accessible`
File: app/models/application_record.rb
Line: 1

Confidence: High
Category: Cross-Site Request Forgery
Check: ForgerySetting
Message: `protect_from_forgery` should be called in `ApplicationController`
File: app/controllers/application_controller.rb
Line: 1

### System configuration
**Rails version**: 8.0.0.alpha , sha: 156b9ac638155a00c7cf9d165f1eae258fa77f37

**Ruby version**: `ruby 3.3.4 `

**Comment by peterberkenbosch** [comment]
Following Brakeman output does fix it, should this be patched on the generator? 

```diff
diff --git a/app/controllers/application_controller.rb b/app/controllers/application_controller.rb
index 0d95db2..0eec1f7 100644
--- a/app/controllers/application_controller.rb
+++ b/app/controllers/application_controller.rb
@@ -1,4 +1,5 @@
 class ApplicationController < ActionController::Base
+  protect_from_forgery with: :exception
   # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
   allow_browser versions: :modern
 end
diff --git a/app/models/application_record.rb b/app/models/application_record.rb
index b63caeb..ea94dfa 100644
--- a/app/models/application_record.rb
+++ b/app/models/application_record.rb
@@ -1,3 +1,4 @@
 class ApplicationRecord < ActiveRecord::Base
   primary_abstract_class
+  attr_accessible
 end
```

**Comment by rafaelfranca** [comment]
This is a bug in brakeman. `attr_accessible` doesn't even exist anymore.

`protect_from_forgery with: :exception` is the default already.

https://github.com/rails/rails/blob/190764a3c166c71fe23cbb3a795ab929df73ef81/actionpack/lib/action_controller/railtie.rb#L108-L114

Please open an issue on brakeman.
