### ISSUE TITLE
ActiveJob::TestHelper#perform_enqueued_jobs no longer works in Rails 7.2 with default :async test adapter

### ISSUE THREAD

**Issue by jrochkind** [rails/rails#52651]
I haven't been able to reproduce this in a single-file script, I'm not sure why. 

But I can link to two fresh `rails g newapp` apps with just enough to reproduce -- one in Rails 7.1 with a passing test, and one in Rails 7.2 with equivalent failing test. 

```ruby
class TestprintJob < ApplicationJob
  queue_as :default

  def perform(*args)
    $performed = true
    Rails.logger.warn "WE-PRINTED-IT"
  end
end

class ArticleTest < ActiveSupport::TestCase
  include ActiveJob::TestHelper

  test "the truth" do
    $performed = false

    perform_enqueued_jobs do
      TestprintJob.perform_later
    end

    assert $performed
  end
end
```

I expect the `perform_enqueued_jobs` to mean the job enqueued with `perform_later` in there gets run before the `perform_enqueued_jobs` block returns, so the global $performed is set to true.  

In Rails 7.1 -- this is what happens, and the test succeeds. 
* https://github.com/jrochkind/rails_7.1_perform_enqueued_jobs_demo , just run `rails test`

In Rails 7.2 -- the test fails, and it seems that the enqueued job was not actually performed before the `perform_enqueued_jobs` block returns. 
* https://github.com/jrochkind/rails_7.2_perform_enqueued_jobs_demo , just run `rails test`. 

https://api.rubyonrails.org/classes/ActiveJob/TestHelper.html#method-i-perform_enqueued_jobs

this has, of course, been extracted from a test failure I had in an actual app after updating to Rails 7.2.

**Comment by skipkayhil** [comment]
I believe this is expected after #48585.

While you set the adapter to `:async`, what happened on 7.1 is the adapter would be silently changed to `:test` for a test class that includes `ActiveJob::TestHelper`. In 7.2, if you want to use `:async` adapter by default in test environment then you have to set the `:test` adapter explicitly for job classes where you want to use `ActiveJob::TestHelper` (`perform_enqueued_*`, etc.).

**Comment by jrochkind** [comment]
Aha, ok, thanks! Thanks for linking to relevant PR!

I guess it wasn't doing quite what I expected before either! 

I feel like making `perform_enqueued_jobs` a no-op when you are using the "wrong" test adapter is a trap!  I would have thought it should raise instead, if it's only usable with a certain adapater. (I didn't actually realize it was switching to test adapter before, so that wasn't necessarily optimal either... but simply doing nothing when i expected it to do something doens't seem right?)
