### ISSUE TITLE
Deprecate `config.active_job.enqueue_after_transaction_commit` config

### ISSUE THREAD

**Issue by rafaelfranca** [rails/rails#52675]
This config now accepts the following values:

* `:never` - Never defer the enqueue.
* `:always` - Always defer the enqueue.
* `:default` - Let the queue adapter define the behaviour.

We believe that his behavior should not be defined by the adapter, and changing its value globally to all jobs can be too much of a sharp knife.

We should still allow specific jobs to change `enqueue_after_transaction_commit` between `true` and `false`, but document explicitly what are the issues that messing with this value could cause.

See discussion in https://github.com/rails/rails/pull/52659#issuecomment-2302422632

**Comment by dhh** [comment]
Is there anything left here?

**Comment by rafaelfranca** [comment]
Yes. No work was done to fix this yet

**Comment by aashishpsaini** [comment]
Hii, @rafaelfranca Please help with what needs to be done here. Can someone else take it up?

**Comment by januszm** [comment]
If possible, it'd be easier if this could be hadled in ActiveJob rather than in all potential queue adapter, here's the error I recently encountered using AWS SQS Shoryuken adapter:

```ruby
NoMethodError: undefined method `enqueue_after_transaction_commit?' for #<ActiveJob::QueueAdapters::ShoryukenAdapter:0x00007f31ebda9b60> (NoMethodError)
          queue_adapter.enqueue_after_transaction_commit?
```

**Comment by xuanxu** [comment]
@rafaelfranca I've open an initial PR here: #53336
