### ISSUE TITLE
`attributes_to_define_after_schema_loads` deprecation and recovery

### ISSUE THREAD

**Issue by amkisko** [rails/rails#52685]
Hey!

In version 7.2.0 breaking change introduced by `attributes_to_define_after_schema_loads` removal, there were no deprecation warnings and it is not easy to find traces and where the change was introduced.

Here's the commit with the change: https://github.com/rails/rails/commit/e0a55b038f7f2f50d1467876558be183be6cedaa

There are some gems and custom classes that rely on this method, are there any suggestions how to replace it? At the moment it is not clear how to access all registered attributes, it seems that ActiveModel started ignoring attributes that are not baked from database. The use case for this one when we have custom SQL query as a source of data for the model.

E.g. this code:
```ruby
  def self.load_schema!
    @columns_hash ||= {}

    attributes_to_define_after_schema_loads.each do |name, (cast_type, default)|
      cast_type = cast_type[type_for_attribute(name)] if Proc === cast_type
      cast_type = connection.lookup_cast_type_from_column(type) if Symbol ===
        cast_type
      define_attribute(name, cast_type, default: default)
      @columns_hash[name.to_s] = ActiveRecord::ConnectionAdapters::Column.new(
        name.to_s,
        default
      )
    end
  end
```

**Comment by amkisko** [comment]
```
      defined_enums.each_key do |name|
        unless columns_hash.key?(resolve_attribute_name(name))
```
This partially helps, but not sure how to get default value.

**Comment by rafaelfranca** [comment]
`attributes_to_define_after_schema_loads` was always internal of the framework. No gem or application should use that method. That is why there wan't any deprecation. Rails is free to remove any of its internal methods at any time.

At the moment, there is no public API to do what you want. But we would definitely accept a pull request to expose a method that returns all registered attributes in the public API.
