### ISSUE TITLE
encrypts method must be called before using it on normalizes or attributes API

### ISSUE THREAD

**Issue by duduribeiro** [rails/rails#52681]
Hey folks 👋 

We are already running rails on alpha at the current eaa74ee ref. I'm trying to upgrade my Rails to the latest main branch ref and my CI started to raise `ActiveRecord::Encryption::Errors::Decryption: ActiveRecord::Encryption::Errors::Decryption` exceptions in a lot of places we try to save a record with encrypted data in tests. 

I tracked down the problem to the https://github.com/rails/rails/commit/9c8390032c85df23d973432b67d025df05c838f7 commit. When I use the commit before this one (984b10b) everything works just fine. 

cc @djmb 

After some investigation I found that after 9c8390032c85df23d973432b67d025df05c838f7, the `encrypts` method is order dependent. It must be called before using other stuffs that touches the encrypted attribute (like normalizes or attributes API). My issues with ActiveRecord::Encryption::Errors::Decryption is because my model was calling `normalizes` at a encrypted attribute before the encrypts being defined on model. 

I think encrypts must not be order dependent to behave like all previous rails versions but if we decide that it should be order dependent, I can update Rails docs to provide this information

I found the same problem with Attributes API:

The following script reproduces the problem:

```ruby

# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: "rails/rails", ref: "9c83900"
  gem "sqlite3"
  gem "debug"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Encryption.configure(
  primary_key: SecureRandom.alphanumeric(32),
  deterministic_key: SecureRandom.alphanumeric(32),
  key_derivation_salt: SecureRandom.alphanumeric(32),
)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.string :author
    t.string :publish_date
  end
end

class Post < ActiveRecord::Base
  attribute :publish_date, :date # When attribute is before encrypts, it does not work

  encrypts :title, :publish_date
  encrypts :author, deterministic: true

  # attribute :publish_date, :date # When attribute is after encrypts, it works
end

class BugTest < Minitest::Test
  def test_should_encrypts_and_returns_a_date
    post = Post.create!(publish_date: Date.current)

    refute_nil post.publish_date
    assert post.publish_date.is_a?(Date)
  end
end
```

when running it, it fails:

```
  1) Failure:
BugTest#test_should_encrypts_and_returns_a_date [test_case_52681.rb:49]:
Expected nil to not be nil.
```

but when moving the attribute call to be below the encrypts call, it works:
```ruby
class Post < ActiveRecord::Base
  # attribute :publish_date, :date # When attribute is before encrypts, it does not work

  encrypts :title, :publish_date
  encrypts :author, deterministic: true

  attribute :publish_date, :date # When attribute is after encrypts, it works
end
```

```
.

Finished in 0.005337s, 187.3712 runs/s, 374.7424 assertions/s.

1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by duduribeiro** [comment]
I created a blank rails repo with a basic setup and looks like it is not happening. I even configured the test environment like my app. I'm suspecting some dependency may be interfering on this. I will investigate it further

**Comment by duduribeiro** [comment]
I found the problem. It was something on my app 😄 

if I do: 

```ruby
class Company < ApplicationRecord
...

  normalizes :cnpj, with: ->(cnpj) { CNPJ.new(cnpj).stripped }
  encrypts :cnpj, deterministic: true
...
```

it fails. 

I updated to move the normalizes call below the `encrypts` 

```ruby
class Company < ApplicationRecord
...
  encrypts :cnpj, deterministic: true
  normalizes :cnpj, with: ->(cnpj) { CNPJ.new(cnpj).stripped }
...
```

and it worked. still don't know why. I think it can be maybe something in my app as in a blank app it works just fine with the normalizes in any position.

**Comment by djmb** [comment]
Hi @duduribeiro,

Hmm yes this makes sense - we’ll need to ensure that the encrypted type is wrapped inside the normalized type as well. 

I’m not sure why your new app didn’t have the same problem. 

We can take a similar approach here to what we’ve done with serialized types and ensure the nesting is correct whichever order things are declared in.

**Comment by duduribeiro** [comment]
@djmb should we reopen this so?

**Comment by duduribeiro** [comment]
@djmb just found another issue with my app tests after moving to https://github.com/rails/rails/commit/9c8390032c85df23d973432b67d025df05c838f7 

I have a fixture:

```yaml
ada:
  name: Ada Lovelace
  birth_date: 1815-12-10
```

birth_date is an encrypted attribute (so I store as string on DB) and I use [attributes api](https://guides.rubyonrails.org/5_0_release_notes.html#active-record-attributes-api) to convert it into a Date

```ruby
class Person < ApplicationRecord
  attribute :birth_date, :date

  encrypts :birth_date
end
```

when using commit 984b10b it stores the birth_date just fine
```ruby
people(:ada).birth_date
Sun, 10 Dec 1815
```
 
but when using commit https://github.com/rails/rails/commit/9c8390032c85df23d973432b67d025df05c838f7 it does not store the birth date:

```ruby
people(:ada).birth_date
nil
```

**Comment by djmb** [comment]
Thanks for that, @duduribeiro. I think this is essentially the same issue as with normalize. 

We need to find a way to insert the encrypted attribute type in the right place for all kinds of attribute decorations. 

@dhh - I think we should revert https://github.com/rails/rails/pull/52650 for now. I’ll look into how we can resolve these.

**Comment by dhh** [comment]
@djmb Can you add a PR for the revert? The old PR won't clean revert, so probably some conflicts that need sorting.

**Comment by djmb** [comment]
@dhh - raised here - https://github.com/rails/rails/pull/52693

**Comment by duduribeiro** [comment]
@djmb 


```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: "rails/rails", ref: "6f79f25"
  gem "sqlite3"
  gem "debug"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Encryption.configure(
  primary_key: SecureRandom.alphanumeric(32),
  deterministic_key: SecureRandom.alphanumeric(32),
  key_derivation_salt: SecureRandom.alphanumeric(32),
)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
    t.string :author
    t.string :publish_date
  end
end

class Post < ActiveRecord::Base
  attribute :publish_date, :date

  encrypts :title, :publish_date
  encrypts :author, deterministic: true
end

class BugTest < Minitest::Test
  def test_should_encrypts_and_returns_a_date
    post = Post.create!(publish_date: Date.current)

    refute_nil post.publish_date
    assert post.publish_date.is_a?(Date)
  end
end
```

```
.

Finished in 0.046496s, 21.5072 runs/s, 43.0145 assertions/s.

1 runs, 2 assertions, 0 failures, 0 errors, 0 skips
```

looking good 🥇 
thanks for that

**Comment by duduribeiro** [comment]
Closed by https://github.com/rails/rails/pull/52693
