### ISSUE TITLE
Warnings for "Test is missing assertions"

### ISSUE THREAD

**Issue by Mark-ICS** [rails/rails#52690]
Since upgrading from rails 7.1.0 to 7.2.0, I now get a number of warnings stating:

 > Test is missing assertions

These reference my tests which work by using Mock.verify to check that a certain method has been called as expected after an action.

For example, when creating a new user, I expect `ProcessNewUserJob.perform_later` to be called. 

These tests work by using `mock.verify` to check the method was called, so there is no need to use an `assert_x` method on in my test.

Is this approach to testing not valid/recommended now? 

### Steps to reproduce

Add a new test in Minitest, e.g.:

```ruby

test 'queue job for new user' do
  mock_perform_later = Minitest::Mock.new
  user = User.new(name: 'Mark')
  mock_perform_later.expect(:call, nil, [user])

  ProcessNewUserJob.stub :perform_later, mock_perform_later do
    user.save!
  end
  mock_perform_later.verify
end
```

Then run tests: `bundle exec rails test`

### Expected behavior
I expect the test to run with no warnings if I am calling `.verify` on a mock during the test.

### Actual behavior
I get the warning
> Test is missing assertions

### System configuration
**Rails version**: 7.2.0
**Ruby version**: 3.3.4

**Comment by fatkodima** [comment]
This is an unnecessary complicated test. You can just assert that the job was enqueued without any mocks. https://api.rubyonrails.org/classes/ActiveJob/TestHelper.html#method-i-assert_enqueued_jobs

**Comment by Mark-ICS** [comment]
@fatkodima ok that's fair, and is a bad example, however what if I wanted to test something non-job related? 

Is there never a case where it might be appropriate to have a test that purely checks mocked calls? 

For example, if I'm building a SlackClient, I might want to test that calling `client.send_message` will make the appropriate HTTP request to a slack web-hook?

**Comment by fatkodima** [comment]
> Is there never a case where it might be appropriate

Never say never, it depends. I think, the cases where only mocks are checked are pretty rare and adding some asserts like `assert_nothing_raises` or `pass` is ok.

**Comment by Mark-ICS** [comment]
Would it be reasonable to expect that the warning doesn't show if using `verify` alone? Or is it better to just suppress it?

**Comment by fatkodima** [comment]
It is reasonable, but we can't do anything from the rails side. This warning thing works in rails by checking if after the test ran we have `assertions` variable incremented, but mocks do not increment any assertions. So just suppressing I think is the way to go.

**Comment by Mark-ICS** [comment]
Makes sense, thanks @fatkodima.
