### ISSUE TITLE
The Rails application utilizes a background process application callback to initiate a specific event

### ISSUE THREAD

**Issue by jquerys7** [rails/rails#52730]
I have a unique app that leverages the SuckerPunch gem and Carrierwave Backgrounder to efficiently upload and process images in the background of a cutting-edge rails application. As a user creates an instance of the Asset model, the image processing begins, triggering the setting of the attachment_processing? attribute in the Asset model to true. To alert the user during this processing phase, I utilize this sleek view template:

```
-if instance.send(base_name)
  .form-row
    - if instance.send(base_name).attachment_processing?
      .image_processing
        %span Processing Asset #{proccessing_asset_name(instance.send(base_name))}
        = image_tag("ajax-loader.gif")
    - else    
       = nice_asset(instance.send(base_name),options[:thumb])
```
Upon completion of the processing, the attribute switches to false and the image is displayed post-page refresh, as observed in the server logs which show this automatic update.

```
Started GET "/assets/ajax-loader.gif" for 127.0.0.1 at 2014-11-21 16:10:38 +0000
   (0.2ms)  BEGIN
  SQL (0.4ms)  UPDATE `assets` SET `attachment_processing` = 0, `updated_at` = '2014-11-21 16:11:14' WHERE `assets`.`id` = 6362
   (1.9ms)  COMMIT
```
Seeking a more streamlined approach for displaying the finished image, I wonder if there's a way - be it through ajax or other means - to automate this process instead of prompting the user to manually refresh the page?

Your insights and suggestions are greatly appreciated.

Original source https://jquerys.space/questions/the-rails-application-utilizes-a-background-process-application-callback-to-initiate-a-specific-event

**Comment by rafaelfranca** [comment]
Please use https://discuss.rubyonrails.org/ for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
