### ISSUE TITLE
Unable to initialize active_record.encryption.hash_digest_class in 7.1.4

### ISSUE THREAD

**Issue by jpalermo** [rails/rails#52740]
### Steps to reproduce
Follow the [new_framework_defaults_7_1.rb](https://github.com/rails/rails/blob/v7.1.4/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults_7_1.rb.tt#L54) guide and configure
`Rails.application.config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA256`

See that the key_generator is instead using `OpenSSL::Digest::SHA1`

We think this might have been caused by the changes to order of initialization in #50606, but we're not confident in that.

Currently it seems that it's impossible to change the `hash_digest_class` without some terrible `instance_variable_set` on the `default_context` of the `Encryption` class since the Encryption is initialized before any initializers.

### System configuration
**Rails version**: 7.1.4

**Comment by maximerety** [comment]
Hi @jpalermo,

I'm the implementer of the fix in https://github.com/rails/rails/pull/50606 (and another one in https://github.com/rails/rails/pull/52669 - to be released with Rails 7.1.5 / 7.2.2).

I'd like to help, but I'm not sure how to reproduce your issue.

A few things that could help:

1. > See that the key_generator is instead using OpenSSL::Digest::SHA1

    Are you checking this by calling `ActiveRecord::Encryption.config.hash_digest_class`?

    I'd assume:

    ```shell
    bin/rails console
    irb(main):001> ActiveRecord::Encryption.config.hash_digest_class
    ```

2. > Follow the [new_framework_defaults_7_1.rb](https://github.com/rails/rails/blob/v7.1.4/railties/lib/rails/generators/rails/app/templates/config/initializers/new_framework_defaults_7_1.rb.tt#L54) guide and configure
`Rails.application.config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA256`

    Is this happening in `config/application.rb`, a `config/environments/*.rb` file, an initializer file in `config/initializers`, or somewhere else?

3. In `config/application.rb`, what defaults are you loading? E.g.

    ```ruby
    class Application < Rails::Application
      config.load_defaults 7.1 # <- Is this present? Are you using something else?

      # [...] other configs... 
    end
    ```

4. What's the value of `config.eager_load` when encountering the issue?

Thanks for sharing any other useful information.

**Comment by jpalermo** [comment]
Yeah, we were unable to reproduce the problem with a new test project. So we started debugging through the rails initialization code and found what the difference is.

1. We are just checking `ActiveRecord::Encryption.config.hash_digest_class`
2. We are trying to configure the `Rails.apoplication.config` properties within an initializer
3. We did in fact have our `config.load_defaults` set to `7.0` rather than `7.1`. So we switched that, which gave us the correct SHA256 class, but we were still unable to configure it back to SHA1, so something is still wrong with our loading.
4. `config.eager_load` doesn't seem to change the behavior

So we found that if we include 
```
gem 'delayed_job'
gem 'delayed_job_active_record'
```
in our Gemfile.

This causes DelayedJobActiveRecord to require ActiveRecord during the `Bundler.require(*Rails.groups)` within `application.rb`.

This makes it so when the `active_record.set_configs` initializer in railties runs, it has a block with `ActiveSupport.on_load(:active_record) do` and that runs immediately, which causes all the configs to be loaded into the config objects before any of the initializers have been run. 

Without DelayedJobActiveRecord, `:active_record` is NOT loaded during the `active_record.set_configs` initializer and the config loading is delayed until after the initializers have been run.

**Comment by maximerety** [comment]
Thanks for sharing your discovery.

I've encountered the same problem countless times with various gems (most of which are fixed now) which would trigger the early loading of Rails components (and their configs), before you get a chance to add configs in an initializer.

An example found recently: https://github.com/girishso/pluck_to_hash/blob/master/lib/pluck_to_hash.rb#L61.

If possible, the offending gem(s) should be fixed by wrapping offending code within an `ActiveSupport.on_load(:active_record) do; end` block so that they don't trigger an undesired early loading of `ActiveRecord::Base`.

Examples of such fixes I've seen recently: https://github.com/cloudinary/cloudinary_gem/pull/532, https://github.com/shadabahmed/logstasher/pull/173, and even in Rails itself: https://github.com/rails/rails/pull/50715.

I don't know if this is a promising avenue in your particular case.

If not possible to fix at the source, you might need to move your configs in a "safer" place, such as `config/application.rb` which is loaded much earlier in the process, before the `active_record.set_configs` initializer in railties runs.

I don't see any generic fix in Rails itself that could prevent this kind of issue, and not break other features (such as eager loading, as shown by https://github.com/rails/rails/pull/50606).

And to protect yourself from having similar problems again without noticing, you could add as first initializer in your application something like this:

```ruby
# config/initializers/00000_lazy_loading.rb
Rails.application.configure do
  frameworks = [ActionMailer, ActiveJob, ActionView, ActionController, ActiveRecord] # ...

  # Catch violations from gems
  frameworks.each do |mod|
    already_loaded = mod.autoload?(:Base).nil?
    raise "#{mod}::Base loaded before application initializers are run" if already_loaded
  end

  # Catch violations from your initializers in dev/test
  if !config.eager_load && !Rails.env.production?
    config.after_initialize do
      frameworks.each do |mod|
        already_loaded = mod.autoload?(:Base).nil?
        raise "#{mod}::Base loaded during application boot when it should be lazy" if already_loaded
      end
    end
  end
end
```

**Comment by jpalermo** [comment]
Yeah, looks like [delayed_job_active_record Job class](https://github.com/collectiveidea/delayed_job_active_record/blob/master/lib/delayed/backend/active_record.rb#L33) is inheriting from `ActiveRecord::Base`.

Wrapping that whole class definition, or the require of it in a `.on_load(:active_record)` would probably be possible, but the fact that those are getting sprinkled around various codebases feel like a very non-ideal solution. And one that is going to continue to show up forever.

Fixing this within Rails itself also seems non-trivial as you mentioned.

For now we just added a `require: false` to the `delayed_job_active_record` gem in the Gemfile and require it explicitly in a wonderfully named `zzz_load_delayed_job_active_record` initializer.

**Comment by rafaelfranca** [comment]
The correct fix in on `delayed_job_active_record`. It should not be loading Active Record before the Rails framework.

**Comment by jpalermo** [comment]
@rafaelfranca, is the loading process of gems that use Rails components documented somewhere?

**Comment by rafaelfranca** [comment]
https://guides.rubyonrails.org/configuring.html#avoid-loading-rails-frameworks

**Comment by pjurewicz** [comment]
I can agree that this kind of bugs should be addressed on the gems provider site.
On the other hand, Rails could warn If their components were loaded prematurely. That should be easy to detect.
There are multiple gems that have or used to have this problem, including very popular ones:
- [rails_event_store](https://github.com/RailsEventStore/rails_event_store/pull/1906)
- [friendly_id](https://github.com/norman/friendly_id/issues/823)
- [globalize](https://github.com/globalize/globalize/issues/786)
- [pg_hero](https://github.com/ankane/pghero/issues/232)
- [delayed_job_active_record](https://github.com/collectiveidea/delayed_job_active_record/issues/128)

Putting to much trust in uncommenting things in `new_framework_defaults` can be really dangerous in some scenarios.
I've written more in this [article](https://blog.arkency.com/i-do-not-blindly-trust-setting-things-in-new-framework-defaults-initializers-anymore/).

**Comment by willnet** [comment]
@pjurewicz I had the same opinion as you and made a tool to detect gems that don't lazy-load components like `ActiveRecord::Base`.
[Here it is](https://github.com/willnet/a-nti_manner_kick_course), just for your reference.
