### ISSUE TITLE
Running `bin/setup` in an application template errors out when `bin/dev` uses Foreman

### ISSUE THREAD

**Issue by jeromedalbert** [rails/rails#52755]
The issue started appearing on Rails main after this commit was merged: https://github.com/rails/rails/commit/7ed09d3a387a780278700ac6edac3e97aa41aa3a.

### Steps to reproduce

Run the following shell commands:

```shell
echo 'after_bundle { run "bin/setup" }' > template.rb

rails new myapp --main --css tailwind -m $(pwd)/template.rb
```

### Expected behavior

The template should not error out.

### Actual behavior

The template errors out:

```
== Starting development server ==
...
Installing foreman...
...
Successfully installed foreman-0.88.1
1 gem installed
/Users/jerome/.asdf/installs/ruby/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable foreman for gem foreman. foreman is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
        from /Users/jerome/.asdf/installs/ruby/3.3.2/lib/ruby/site_ruby/3.3.0/bundler/rubygems_integration.rb:293:in `block in replace_bin_path'
        from /Users/jerome/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/bin/foreman:25:in `<main>'
```

Note: if I `cd myapp` and run `bin/setup` again, it works with no errors.

### System configuration
**Rails version**: main (8.0.0.alpha)

**Ruby version**: 3.3.2

**Comment by dhh** [comment]
We could add "--skip-dev-server" flag to the default bin/setup. But you'll only be able to depend on that for a vanilla bin/setup file, before folks have messed with it. But do investigate that!

**Comment by jeromedalbert** [comment]
I think I found a nicer fix! Changing my `template.rb` to the following works: 

```ruby
after_bundle do
  Bundler.with_original_env do
    run "bin/setup"
  end
end
```

🎉 

The issue is that in application templates, any code inside `after_bundle { ... }` is basically executed in a Bundler context. So when `bin/setup` calls `bin/dev` which does `foreman start -f Procfile.dev`, it is virtually the same as doing `bundle exec foreman start -f Procfile.dev`, which errors out. I get the exact same error when running foreman with `bundle exec`. `Bundler.with_original_env` clears up the Bundler context.
