### ISSUE TITLE
Rails multi Tenant with Multi DB not working - No connection pool for 'Activerecord::Base' found.

### ISSUE THREAD

**Issue by sunil-sharma** [rails/rails#52757]
### Steps to reproduce
We have implemented Multi-tenancy with Multiple Databases with Rails 7.0

We are strong DB configurations into MetaDB and loading dynamically like this:

      

 
      db_config = MetadbDsDetail.all.each_with_object({}) do |db_detail, db_hash|
      next if db_detail.blank?
      puts "************* Available ECL db details #{db_detail} *******************"
      lxp_db = {
        adapter: 'mysql2',
        database: db_detail.db_name,
        username: db_detail.username,
        password: db_detail.decrypt_password(db_detail.password),
        host: db_detail.db_url,
        port: db_detail.try(:port) || 3306,
        pool: db_detail.db_pool || 100,
        reaping_frequency: db_detail.reaping_frequency || 5
      }

      lxp_replica_db = {
        adapter: 'mysql2',
        database: db_detail.replica_db,
        username: db_detail.replica_username,
        password: db_detail.decrypt_password(db_detail.replica_password),
        host: db_detail.replica_db_url,
        port: db_detail.try(:replica_port) || 3306,
        pool: db_detail.replica_db_pool || 100,
        reaping_frequency: db_detail.reaping_frequency || 5
      }

      ecl_master_db = {
        adapter: db_detail.ecl_adapter,
        database: db_detail.ecl_master_db_name,
        username: db_detail.ecl_master_username,
        password: db_detail.decrypt_password(db_detail.ecl_master_password),
        host: db_detail.ecl_master_db_url,
        port: db_detail.try(:ecl_master_port) || 3306,
        pool: db_detail.ecl_master_db_pool || 100,
        reaping_frequency: db_detail.ecl_master_reaping_frequency || 5
      }

      db_hash[db_detail.db_name.to_sym] = lxp_db
      db_hash[db_detail.replica_db.to_sym] = lxp_replica_db
      db_hash[db_detail.ecl_master_db_name.to_sym] = ecl_master_db
    end
    new_config = Rails.application.config.database_configuration.merge!(db_config)
    ActiveRecord::Base.configurations = new_config

Sideki Middleware code to Switch connection

     `# lib/sidekiq/middleware/server_middleware.rb
      class ServerSideMiddleware
        def call(worker, job, queue)
          # before_action logic here
          if MULTI_DB_ENABLED
            lxp_tenant = job['lxp_tenant'] if job['lxp_tenant'].present?
            ecl_tenant = job['ecl_tenant'] if job['ecl_tenant'].present?
      
            if(lxp_tenant || ecl_tenant)
              switch_tenant_connection(lxp_tenant, BaseLxp, :lxp_tenant_sidekiq_server) if lxp_tenant
              switch_tenant_connection(ecl_tenant, ApplicationRecord, :ecl_tenant_sidekiq_server) if ecl_tenant
              yield # Execute the job
            # elsif Sidekiq::Cron::Job.all.map(&:klass).uniq.include?(job['class']) # MULTIDB: cron jobs needs to run for all databases
            #   exec_cron_on_multi_db
            else
              yield
              puts "Job #{job.class} with Job Id #{job} in queue #{queue} does not have tenant argument"
            end
          end
          puts "After executing #{worker.class} with job #{job}" # after_action logic here
        end
      
        def exec_cron_on_multi_db
          yield && return if Rails.env.test?
          ecl_details = MetadbDsDetail.all
          ecl_details.each do |ecl_db|
            ActiveRecord::Base.connection.schema_cache.clear!
            ApplicationRecord.establish_connection(ecl_db.ecl_master_db_name.to_sym)
            # ActiveRecord::Base.descendants.each(&:reset_column_information)
            yield if block_given?
          end
        end
      
        def switch_tenant_connection(tenant, base_class, store_key)
          if tenant.present?
            base_class.establish_connection(tenant.to_sym)
            RequestStore.store[store_key] = tenant
          end
        end
      end
```
 In Above code we are getting proper value for ecl_tanent and lxp_tanent but we are facing multiple issues for multiple Jobs like
 `No connection pool for 'Activerecord::Base' found.`
 `ActiveRecord::ConnectionNotEstablished`
 
 How to solve this?

### Expected behavior
Ideally, it should switch connection to the correct DB and execute code.

### Actual behavior
Giving Connecton Pool and ConnectionNotEstablished Error

### System configuration
**Rails version**: '~> 7.0', '>= 7.0.8

**Ruby version**: '3.0.6'

**Comment by fatkodima** [comment]
Hey @sunil-sharma we reserve the Rails Issues tracker for bugs in the framework as we don't have the bandwidth to offer application support. Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help with your application. Thanks for understanding.
