### ISSUE TITLE
params.deep_transform_keys! doesn't work with camelCased json payloads (ActionController)

### ISSUE THREAD

**Issue by fandan** [rails/rails#52754]
### Steps to reproduce
ApplicationController:
```
before_action :underscore_params!

def underscore_params!
    params.deep_transform_keys!(&:underscore)
end

```

TestCaseController:
```
def create
    @test_case = TestCase.new(permitted_params)
    
    if @test_case.save
      render status: :created
    else
      render status: :unprocessable_entity
    end
  end

def permitted_params
    params.require(:test_case).permit(:field_one, :field_two)
end
```

Create a POST request with following json payload:
```
{ testCase: { fieldOne: "test", fieldTwo: "case" }
```

### Expected behavior
deep_transform_keys! underscores the keys of delivered params to...

```
{ test_case: field_one: "test", field_two: "test" }
```

### Actual behavior
Output of params before deep_transform_keys!:
```
<ActionController::Parameters {"testCase"=>{"fieldOne"=>"test, "fieldTwo"=>"case"}, "controller"=>"api/test_cases", "action"=>"create", "test_case"=>{}} permitted: false>
```
Output of params after deep_transform_keys!:
```
<ActionController::Parameters {"test_case"=>{}, "controller"=>"api/test_cases", "action"=>"create"} permitted: false>
```
As you can see there exists already a empty hash named **test_case** before deep_transform_keys was called.
My impression is that a empty hash with downcased model name (:test_case) is created if no such named hash was delivered.
Now deep_transform_keys! can`t rename **TestCase** to **test_case** because this name already exists.

In a scenario without camelCased names (e.g. "CaseController" and { case: { field: "test" }} as json payload) , there are no problems.

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.3.0

**Comment by fatkodima** [comment]
I cannot reproduce. Can you provide a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/action_controller.rb template?
