### ISSUE TITLE
Fix dev container smoke test

### ISSUE THREAD

**Issue by andrewn617** [rails/rails#52768]
### Steps to reproduce

Dev Container smoke test is broken by [this commit](https://github.com/rails/rails/commit/7ed09d3a387a780278700ac6edac3e97aa41aa3a), which introduced running `bin/dev` to consistently start the server as part of `bin/setup`.

### Expected behavior
After creating the dev container we run `bin/setup`, which runs the server. The workflow then hangs forever and times out.

For example: https://github.com/rails/rails/actions/runs/10637687852

### Actual behavior
After creating the dev container we bundle gems and setup the db but do not run the server, so we can run tests.

### System configuration
**Rails version**:

**Ruby version**:

**Comment by yahonda** [comment]
It looks like Rails CI is getting timed out https://buildkite.com/rails/rails/builds/110765#0191a49c-e62d-433e-b97c-6ab909e6445b/1323
