### ISSUE TITLE
Composite keys given as array of strings break nested_attributes update

### ISSUE THREAD

**Issue by chbach** [rails/rails#52785]
### Steps to Reproduce

Refer to the example in the guidelines: [Composite Primary Key Migrations](https://edgeguides.rubyonrails.org/active_record_composite_primary_keys.html#composite-primary-key-migrations).

Suppose we have a form that updates a store with a list of products and nested fields for the products (since `sku` and `description` depend on the store). We would need to render a hidden input for each product's `id`, containing an array with the `store_id` (integer) and `sku` (string). When processing these values in a controller after permitting `products_attributes` params, we receive an array of strings since all parameter values are passed as strings.

If we examine the code executed during `Store.update(store_params)`, we see a simple string comparison used to identify objects within the nested attributes hash or array.

See the code here: [Rails Nested Attributes](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/nested_attributes.rb#L527)

### Actual Behavior

In this example, the comparison fails because it tries to match `'[3, "XYZ12345"]'` with `'["3", "XYZ12345"]'`. This causes existing objects not to be correctly identified, leading to record not found exceptions although the record is fetched correctly from the database. 

### Expected Behavior

Although the application code should ideally convert IDs to the correct types before update or create operations, this behavior is inconsistent with other Active Record find operations involving IDs, including composite keys. For example, `Product.find(["3", "XYZ12345"])` would work correctly. It would be more robust if Active Record checked each part of composite keys separately and converted each element to a string (`to_s`) before comparison.

## Side note

The `fields_for` view helper renders a single hidden input for the ID, containing a space-separated list of elements for the composite key. Instead, it should render a separate input for each element of the ID using array `[]` brackets. This would pass the composite key as an array, which is necessary for `nested_attributes` with composite keys, rather than as a string.

### System configuration
**Rails version**:
EDGE (8.0.0)

**Ruby version**:
3.3.4

**Comment by fatkodima** [comment]
Please, provide a bug report using this template - https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb

**Comment by chbach** [comment]
Hi @fatkodima, sorry for not providing code using the bug template. Please check out the code below. 

```ruby 
# frozen_string_literal: true

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rails'
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem 'sqlite3'
end

require 'active_record'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :stores do |t|
  end

  create_table :products, primary_key: %i[store_id sku] do |t|
    t.belongs_to :store
    t.string :sku
    t.text :description
  end
end

class Store < ActiveRecord::Base
  has_many :products

  accepts_nested_attributes_for :products
end

class Product < ActiveRecord::Base
  belongs_to :store
end

class BugTest < Minitest::Test
  def test_nested_attributes
    store = Store.create(products: [
                           Product.new(sku: 'ABCDEFG', description: 'Product 1'),
                           Product.new(sku: 'HIJKLMN', description: 'Product 2')
                         ])

    assert store.reload.persisted?
    assert_equal 2, store.products.count

    # works with string parameters
    assert Product.find([store.id.to_s, 'ABCDEFG']).present?

    # fails in nested_attributes.rb#537, because `detect` only checks string representation of whole string
    assert store.update!(products_attributes: [
                           { id: [store.id.to_s, 'ABCDEFG'], description: 'Product 1 updated' }
                         ])

    assert_equal 2, store.reload.products.count
    assert_equal 'Product 1 updated', store.products.first.description
  end
end

```
