### ISSUE TITLE
Unnecessary double signature in authentication generator

### ISSUE THREAD

**Issue by alexandreruban** [rails/rails#52799]
In the `Authentication` concern of the authentication generator ([link to code](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/authentication/templates/controllers/concerns/authentication.rb)), we store the signed id of the session in the signed cookies: 

```rb
def set_current_session(session)
  Current.session = session
  cookies.signed.permanent[:session_token] = { value: session.signed_id, httponly: true, same_site: :lax }
end
```

As the cookie is already signed, there is no need to store the `session.signed_id`. We could simply store the `session.id`.

**Comment by bigscorpions** [comment]
> In the `Authentication` concern of the authentication generator ([link to code](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/authentication/templates/controllers/concerns/authentication.rb)), we store the signed id of the session in the signed cookies:
> 
> def set_current_session(session)
>   Current.session = session
>   cookies.signed.permanent[:session_token] = { value: session.signed_id, httponly: true, same_site: :lax }
> end
> As the cookie is already signed, there is no need to store the `session.signed_id`. We could simply store the `session.id`.

But is the `session.id` random string or just auto increment int id? If it is a random string, then it would be fine. If it is auto increment id, then signed cookie will not help, cause the id still exposes and can be guessed. I think the id should be random string, or token, just like the old cookie session(browser session) generated random string.
