### ISSUE TITLE
Issue with new rails app -> .env.erb file

### ISSUE THREAD

**Issue by johannesschobel** [rails/rails#52818]
### Steps to reproduce

run `rails new testapplication --main --devcontainer -j esbuild -c tailwind`

This generates a `.env.erb` file with the following content in the root directory

```rb
<%# This env template should lookup values from a password store or from ENV -%>
# Generated by kamal envify from .env.erb
KAMAL_REGISTRY_PASSWORD=<%= ENV["KAMAL_REGISTRY_PASSWORD"] %>
RAILS_MASTER_KEY=<%= File.read("config/master.key") %>
# GITHUB_TOKEN=<%#= `gh config get -h github.com oauth_token`.strip %>
```

### Expected behavior

It should generate an `.erb` file instead - and not the template

### Actual behavior
It actually generates the template file (see above)

### System configuration
**Rails version**: 8.0.0.alpha

**Ruby version**: 3.2.1

**Comment by skipkayhil** [comment]
Can you be more specific about what you expect to happen and why? I'm not sure I understand how "an `.erb` file` is not the actual behavior already

**Comment by johannesschobel** [comment]
it should not generate an `.env.erb` file, but rather an `.env` file with the respective content..

like
```
RAILS_MASTER_KEY="asdf1234"
``` 
which is the actual content of the file `./config/master.key`.
Currently, this is the template file (i.e., a stub) that should be executed first in order to produce respective values.

**Comment by skipkayhil** [comment]
I think the current behavior is expected because it allows you to check in `.env.erb` to git and use [kamal envify](https://kamal-deploy.org/docs/commands/envify/). You could probably switch to using a bare `.env` if you wanted to, but `.env.erb` was likely chosen as a better default?

**Comment by jeromedalbert** [comment]
skipkayhil is correct.

By the way, a few months ago `.env` was in the codebase, but was [removed](https://github.com/rails/rails/commit/33592402f9) to fix an issue, so you either need to rely on `.env.erb` (by running `kamal envify` which will evaluate it and create an `.env`), or manually create the `.env` file yourself.

In the meantime the current behavior is as expected, so I believe this bug can be closed for now. Note: the current env file structure is subject to [change](https://github.com/rails/rails/issues/51829#issuecomment-2260085351).

**Comment by dhh** [comment]
Also, this .env.erb will go away with Kamal 2 that has a new approach to secrets. But what we have now is working as intended.
