### ISSUE TITLE
Second-db schema is overwritten erroneously when running db:migrate

### ISSUE THREAD

**Issue by dhh** [rails/rails#52829]
When you install Solid Queue, we add a new dedicated schema in db/queue_schema.rb. We also add an empty directory for future migrations in db/queue_migrate. If you run db:prepare, everything works as it should, after we fixed https://github.com/rails/rails/issues/52776. But if you run db:migrate, you get a different version of the same issue. The db/queue_schema.rb is erroneously overwritten with an empty schema. 

Maybe because the queue schema wasn't loaded yet when db:migrate tried to set up the secondary db upon running db:migrate, it may just be creating the empty db, then dumping the schema for that empty db (which is empty). This is not how it works on the primary DB nor of course is how it should work.

If on a new app, you have a db/schema.rb and you have an empty db/migrate, you won't get your schema zeroed out when running db:migrate as the first db task.

See https://github.com/rails/solid_queue/issues/329

cc @rafaelfranca

**Comment by andrewn617** [comment]
I think this is an issue in general, not with multi databases. On a fresh app just working with the primary database I can repro this issue by doing the following:

```
bin/rails g model Post
bin/rails db:migrate
rm -rf db/migrate
bin/rails db:drop
bin/rails db:migrate
```

After doing this, the schema file will be empty and there will be no posts table.

When we run `db:migrate` on a database that is not set up, we do not create the database and load it's schema first. We do that in the prepare task [here](https://github.com/rails/rails/blob/1f64e4dee65fc18cbd246b9882f6296e83f12b41/activerecord/lib/active_record/tasks/database_tasks.rb#L182-L197), however there is no equivalent code in migrate task as far as I can tell. So should we add that?

**Comment by dhh** [comment]
Interesting. I tried replicating it in an app that only had a schema.rb, no migrations. If I run db:migrate there for the first time, it'll create the db, load the schema, and all is well. This was using sqlite. Are you using mysql or pgsql? Wonder if there's a difference.

Either way, this should not happen! If there's a schema available, it should never be overwritten by an empty db. Think that's basically just the guard we need to intercept this loop.

**Comment by andrewn617** [comment]
Hmm that's interesting. I am just repro-ing this on `rails new test-app --main`, so yes using sqlite. I wonder what is different 🤔 . But I was able to write a failing test, and yes fixing the issue seems to be simple, so I will open a PR.

**Comment by mkasztelnik** [comment]
@andrewn617 thanks for working on this issue. Unfortunately, this solution only works with a single database configuration when `db:drop db:create db:migrate` is executed. In a multi-database setup, migrations are triggered only for databases with pending migrations. I’ve created #53320 to ensure schemas are loaded for all new databases, even those without pending migrations.

**Comment by jherdman** [comment]
I came here via the noted solid queue issue above. This bug is still in play on Rails 8.0.0@fa35b70a5f6863104856f25641026fc4d449b449.

**Comment by Kagayakashi** [comment]
Command `db:migrate:reset` overwrites solid_queue schema too.

**Comment by thisismydesign** [comment]
This is still present in 8.0.2

**Comment by chrishough** [comment]
This is still failing in 8.0.2
