### ISSUE TITLE
Rails 7.1 changing behaviour of rename_table in existing migrations

### ISSUE THREAD

**Issue by Mbuckley0** [rails/rails#52839]
### Steps to reproduce

* Create a new rails 7.0 app
* Create a new table with the ID being a uuid
* Rename the table
* Upgrade to rails 7.1
* Run `bundle exec rails db:migrate:reset`
* See that the structure.sql file has renamed the table constraint name whereas it previously didn't

https://github.com/Mbuckley0/test_migration_constraint_upgrade

If you run `bundle exec rails db:migrate:reset` before the Upgrade to rails 7.1 commit it will work but if you run it after it will error as `rename_table` is automatically updating the constraint name.

### Expected behavior
`rename_table` should have the same behaviour as it did in rails 7.0 for migrations created in <= rails 7.0

### Actual behavior

Rails 7.1 has changed the behaviour of `rename_table` in existing migrations to also rename the table constraints name

### System configuration
**Rails version**:
7.0.8.4 Upgrading to 7.1.4

**Ruby version**:
3.3.0

**Comment by casperisfine** [comment]
Seems similar to https://github.com/rails/rails/pull/50837, @fatkodima does that ring a bell?

**Comment by fatkodima** [comment]
Yes, looks similar. I will take a look later or someone else is welcome.

**Comment by fatkodima** [comment]
Can you update that test app to use rails 7.0 and working migrations? So I will then upgrade myself to 7.1 and see the problem? Also, can you try to upgrade to 7.2 and see if the problem still persists?

**Comment by Mbuckley0** [comment]
I have downgraded that test app to use rails 7.0 now. I have also tested it against rails 7.2 and it has the same issue.

**Comment by fatkodima** [comment]
This was changed in https://github.com/rails/rails/commit/3e8f1e0aeb81bacddf5a4d29ee3019ad8cc4681a (https://github.com/rails/rails/pull/49998). 
Since this was a bug fix for tables with uuids, because it worked correctly for tables with other primary keys, I wonder if we should preserve the old buggy behaviour? cc @byroot

**Comment by Mbuckley0** [comment]
I have no issues with that. I was just unable to find anything mentioning the change so I did not know if it was intentional or not.

**Comment by byroot** [comment]
> I wonder if we should preserve the old buggy behaviour?

Ideally we should have, but now that's it's been out for a while it risk making things worse, no?

**Comment by fatkodima** [comment]
yes, so I am 👍 for closing this issue.
