### ISSUE TITLE
bug: Guides highlight illegible text on highlight

### ISSUE THREAD

**Issue by hichemfantar** [rails/rails#52836]
### Steps to reproduce
select any text in the guides part of the docs.

![image](https://github.com/user-attachments/assets/046bbf48-c3ba-4187-a98b-2e2057b31d85)

### Expected behavior
selected text should be visible on dark and light mode

### Actual behavior
text color blends in with the selection background color

**Comment by zzak** [comment]
This is a known issue and since there is already a substantial PR to address this and other a11y issues, going to close this one.
