### ISSUE TITLE
`ActiveRecord::ConnectionAdapters::SchemaStatements#add_index` does not document new option `nulls_not_distinct`

### ISSUE THREAD

**Issue by emilyst** [rails/rails#52852]
In Rails 7.1, [a pull request](https://github.com/rails/rails/pull/48608/files) added the option `nulls_not_distinct` to the possible options for use with `ActiveRecord::ConnectionAdapters::SchemaStatements#add_index`. Unfortunately, the pull request did not add documentation for this option, meaning that its existence and behavior are currently undocumented.

I don't have the time and energy to submit a patch to address this, but I thought I'd raise the issue so that the Rails project would be aware of this gap. This is probably an easy issue to address, for someone wanting to get started contributing to the Rails project.

**Comment by holmes2** [comment]
Hi @emilyst ,
Is this the location https://github.com/rails/rails/blob/main/guides/source/active_record_postgresql.md where the documentation would get added ?

**Comment by emilyst** [comment]
> Hi @emilyst , Is this the location https://github.com/rails/rails/blob/main/guides/source/active_record_postgresql.md where the documentation would get added ?

Good question. No, that's probably not the best place.

There are two major places where Rails is documented: in the guides and in the API reference. The guides are not really meant to be a comprehensive reference in the way that the API reference provides. What I had in mind was in [the API reference for this method, which is defined alongside the source code here](https://github.com/rails/rails/blob/281a00a46e0d629fea3bce3ca2bd89fa4e860171/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L768-L902).

**Comment by holmes2** [comment]
I would like to contribute to the doc if no one is assigned to the issue
