### ISSUE TITLE
Calling connection.active? after establish_connection returns false since AR 7.2.0

### ISSUE THREAD

**Issue by lvonk** [rails/rails#52858]
There is a difference in result in calling `ActiveRecord::Base.connection.active?` since 7.2 release after calling `ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "dev_db")`. 
Prior to 7.2 `active?` would return `true` for a postgresql database, but since 7.2 it returns `false`. In both scenarios the connection can be used right after. 
I read through the changelogs but couldn't find a change that caused this, but perhaps I missed something. Did the meaning of `active?` change or is connection setup more lazy then before? I any case the doc of the method doesn't seem to reflect reality anymore imho.

### Steps to reproduce
```ruby
# AR 7.1
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "= 7.1.4"
  gem "pg"
end

require "active_record"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "dev_db")
puts ActiveRecord::Base.connection.active?
# true
```

```ruby
# AR 7.2
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "activerecord", "= 7.2.0"
  gem "pg"
end

require "active_record"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "dev_db")
puts ActiveRecord::Base.connection.active?
# false
```
### Expected behavior
That `active?` returns `true` in AR 7.2 as the connection is ready to use.

### Actual behavior
`active?` returns `false` even though the connection can be used right after.

### System configuration
**Rails version**: NA

**Ruby version**: 3.2.2

**Postgres version**: 16.4

**Comment by fatkodima** [comment]
This was changed in https://github.com/rails/rails/pull/49378 (cc @byroot)

**Comment by lvonk** [comment]
Thanks for clarifying @fatkodima

**Comment by byroot** [comment]
Yes, the connection is now fully lazy. Of course that makes the `establish_connection` name weird, but it has always been a bit of a lie. It doesn't establish a connection, just configure it. It being active was always just a side effect.

> I any case the doc of the method doesn't seem to reflect reality anymore imho.

You mean `#active?` ?

**Comment by lvonk** [comment]
> You mean `#active?` ?

Yeah I meant `#active?`. But as you explained it, the docs do probably makes sense.

**Comment by byroot** [comment]
Sounds good. If you want force the connection for some reason, you can use `#verify!`.
