### ISSUE TITLE
reject_if callback evaluation point changed in rails 7.2

### ISSUE THREAD

**Issue by Roguelazer** [rails/rails#52855]
### Steps to reproduce

The following passes if you pin `rails ~> 7.1.0` and fails if you pin `rails ~> 7.2.0`:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
    t.string :content
  end
end

class Post < ActiveRecord::Base
  has_many :comments

  attr_accessor :allow_comments

  accepts_nested_attributes_for :comments, allow_destroy: true, reject_if: :disallow_comments

  private

  def disallow_comments
    !allow_comments
  end
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_accepts_nested_attribute_for
    post = Post.create!(comments_attributes: {1 => {content: "foo"}}, allow_comments: true)
    assert_equal post.comments.size, 1
    post = Post.create!(comments_attributes: {1 => {content: "foo"}}, allow_comments: false)
    assert_equal post.comments.size, 0
  end
end

```

### Expected behavior
Prior to Rails 7.2, *all* constructor arguments were evaluated before the `reject_if` method was evaluated; this allows your `reject_if` to read other attributes of the object (which our application relies on in a few places, to disable nested attributes on a 1:many relationship built with cocoon via a single checkbox in a form).

### Actual behavior
In Rails 7.2, the arguments to `.new` (including those handled via nested attributes) are evaluated in order, which means that it's effectively unpredictable (since hash orders aren't particularly specified).

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.3.5

**Comment by skipkayhil** [comment]
Can you test this on `7-2-stable`? I think this was fixed in https://github.com/rails/rails/pull/52792

**Comment by Roguelazer** [comment]
Yep, it's fixed in `7-2-stable`. d'oh.
