### ISSUE TITLE
[ActiveRecord::Encryption] Allow deterministic encryption keys to be rotated

### ISSUE THREAD

**Issue by rymai** [rails/rails#52872]
### Proposal

In https://github.com/rails/rails/pull/41659/commits/f78a480818c421f0120181cfdfac633b8cc39a8a, changes were made to "encourage deterministic encryption to remain unchanged", and as a result, rotation us prohibited for deterministic encryption.

I understand the main motivation and default use-case of wanting to define unique indexes, but in my understanding, the "deterministicality" should be for a given key, so if you change the key, obviously the same payload will be encrypted to another value, but it should be possible to encrypt the value with the existing and previous keys and search for these (basically https://github.com/rails/rails/blob/main/activerecord/lib/active_record/encryption/extended_deterministic_queries.rb#L62).

Our use-case is that we want to use deterministic encryption so that we can query for a specific value, but we also want to be able to rotate the key so that new values are encrypted with the **latest key**.

Should we just remove `DeterministicKeyProvider` in favor `DerivedSecretKeyProvider`?

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.
