### ISSUE TITLE
[ActiveRecord::Encryption] Is it possible to store the data in a JSONB column?

### ISSUE THREAD

**Issue by rymai** [rails/rails#52873]
### Proposal

We'd like to store the encrypted data (i.e. this hash: https://github.com/rails/rails/blob/main/activerecord/lib/active_record/encryption/message_serializer.rb#L65-L68) in a JSONB column instead of a string/text one.

Our use-case is to query for all rows where the encrypted value was encrypted with a specific key, so that we know how many records we would need to force-rotate. Using JSONB would also allow to set up indexes for better performance.

I don't think it's supported, and if we'd want to add support, how hard would it be?

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.

**Comment by rymai** [comment]
Thanks! Actually, I just tried locally and JSONB seems to be supported! 🎉
