### ISSUE TITLE
Changed behaviour if CurrentAttributes caused by new default functionality

### ISSUE THREAD

**Issue by schovi** [rails/rails#52901]
### Steps to reproduce

Now in Ruby.7.2 when I create a new CurrentAttributes it automatically sets the every attribute to nil, due to a new default feature
https://github.com/rails/rails/blob/3d2510359c37b2d84a8b33b0b3964ae60f6653f0/activesupport/lib/active_support/current_attributes.rb#L112 

It is quite a breaking change in a larger codebase like our where we have many calls of `Current.attribute.key?(:something)` or passing the whole `Current.attributes` somewhere. 

Unfortunately this (from my perspective breaking) change was not enough documented in release notes nor in the doc https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html

### Expected behavior

```
# Rails 7.1.4

class Test < ActiveSupport::CurrentAttributes
  attribute :a, :b
end
# => [:a, :b]

Test.attributes
# => {}
```

### Actual behavior

```
```ruby
# Rails 7.2

class Test < ActiveSupport::CurrentAttributes
  attribute :a, :b
end

Test.attributes
# => { a: nil, b: nil}
```

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.3.5

**Comment by rafaelfranca** [comment]
I don't believe this behavior was defined, that is why it wasn't considered in the changelogs. I can fix this easily, but I want to understand the use case before sticking to this behavior. Can you explain why you need to check if a key exists?

**Comment by schovi** [comment]
@rafaelfranca The `key?` or `[:something].nil?` is detail which just making the migration harder. But what could cause issue is passing the `.attributes` somewhere else. For example Sidekiq has a middleware that accepts the Current object, calls attributes and serialise it to JSON and attach to job payload. For example we have an Current object holding event, tracing etc metadata. We are speaking about 20+ keys. Most of them is not set usually. With this change the job payload size can grow less or more and consume more Redis memory which can in certain spikes ends with OOM. 

The middleware: https://github.com/sidekiq/sidekiq/blob/2451d70080db95cb5f69effcbd74381cf3b3f727/lib/sidekiq/middleware/current_attributes.rb#L30-L40

**Comment by rafaelfranca** [comment]
Thanks! It makes sense. It should be fixed now.
