### ISSUE TITLE
`ActionController::Live` and `ActiveRecord::Base.connected_to` stale db state

### ISSUE THREAD

**Issue by jscheid** [rails/rails#52906]
### Steps to reproduce

Repro repo: https://github.com/jscheid/prevent-writes-test

Possibly related to #36830.

I've been hunting down an issue in our multi-db, passenger-based, postgres-based app where we see spurious errors "`Write query attempted while in readonly mode`" raised in code paths where we'd definitely expect the app to be connected to the primary (writable) db role.

I've managed to reliably reproduce in our app by limiting to one passenger worker (so that one process is being reused for all requests) and:
1. Hitting an `ActionController::Live` endpoint which uses `ActiveRecord::Base.connected_to(..., prevent_writes: true)`.
2. Provoking an `ActionController::Live::ClientDisconnected` to be raised during processing of said endpoint (just by disconnecting the client early.)
3. In the next request (served by the same worker), `preventing_writes?` will return true unexpectedly.

I can't share our whole app here and so instead I've built the repro test case linked above. Unfortunately I didn't yet manage to reproduce the exact same behavior, however it reliably demonstrates very similar behavior, except that the error thrown in step (3) is instead `No connection pool for 'ActiveRecord::Base' found for the role.` It's not the same error but it seems to indicate that some db state isn't being cleaned up properly in this scenario?

Things I've tried:
- Using a single-threaded, single-worker Puma server instead of a single-worker Passenger server - and I can see the same behavior, so it doesn't seem to depend on the web server being used.
- Using both latest Rails (7.2.1) and the version we're currently running in production (7.1.3.1), the behavior is the same in both cases.
- Using `Rails.application.executor.wrap` and/or `ActiveRecord::Base.connection_pool.with_connection` inside the `ActionController::Live` thread in hopes that it will isolate the environment stood up by `ActiveRecord::Base.connected_to`, but to no avail.
- Raising a `RuntimeError` from inside the Live thread (instead of `ActionController::Live::ClientDisconnected`) to see what happens, but interestingly this **doesn't** seem to trigger the same behavior.

Things I haven't tried yet:
- Using a database (connection handler) other than Postgres; but from reading the Rails code I think all the role/`prevent_writes` stuff is happening at the level of the abstract connection so I don't think it would help shed much light.

I can't rule out some kind of misconfiguration or misuse of `ActionController::Live` or `ActiveRecord::Base.connected_to` on our part - if so my apologies and I hope someone can point me into the right direction.

### Expected behavior

When using `ActiveRecord::Base.connected_to` inside `ActionController::Live.stream`, and when the client disconnects early, it should clean up after itself so that subsequent requests served by the same worker process have a clean database environment.

### Actual behavior

When using `ActiveRecord::Base.connected_to` inside `ActionController::Live.stream`, and when the client disconnects early, the database environment used for the next requests seems to be corrupted in some way that I don't fully understand yet.

### System configuration
**Rails version**: `7.2.1`, but also tested with `7.1.3.1` with identical results.
**Ruby version**: 3.3.5

**Comment by jscheid** [comment]
I've analyzed this further and the long and short of it is that `ActiveRecord::ConnectionHandling`, which provides the multi-db mechanics, is not thread-safe. This is something that I feel should be called out more prominently in the documentation, especially since Rails db connection handling is very much thread-safe otherwise.

Here is my understanding of what's happening:
1. The Live endpoint is hit, passenger starts processing the request and queues any other incoming requests.
2. As soon as the client disconnects, passenger treats the request as complete and starts processing the next request (I have not verified this but it seems like a safe assumption.)
3. Meanwhile, the thread started in step (1) is still executing, assuming it still has work to do. It will only check the connection state on the next call to `stream.write`.
4. If the thread is still inside a `connected_to` block, there will still be an entry on `connected_to_stack` until the thread exits; due to the lack of thread-safety, this entry will be picked up by any code processing the next request if that code executes before the thread exits, which can be an arbitrary amount of time (depending on when `response.stream.write` is called next.)

In our specific case it so happens that we only need to run a piece of SQL with `connection.execute` so our workaround is likely going to be removing `connected_to` altogether and instead doing something like:

```ruby
connection =
  ActiveRecord::Base.connection_handler.retrieve_connection(
    ActiveRecord::Base.connection_specification_name,
    role: :reading,
    shard: ActiveRecord::Base.current_shard,
  )

connection.execute(...)
```

That's using private(ish) methods and we're losing `prevent_writes`. I'm not particularly happy about it, but it'll do for now. We'd be SOL though if we wanted to use ActiveRecord here.

Can anyone suggest a better workaround, poke holes into my analysis, or think of a feasible fix on the Rails side?

**Comment by 97jaz** [comment]
@jscheid We just ran into the same problem. I read through your description, but I'm unclear on the issue of thread safety. The `connected_to_stack` is [fiber local](https://github.com/rails/rails/blob/v8.0.1/activerecord/lib/active_record/core.rb#L205-L213), so I don't understand how it's leaking into another thread.

**Comment by tavianator** [comment]
> [@jscheid](https://github.com/jscheid) We just ran into the same problem. I read through your description, but I'm unclear on the issue of thread safety. The `connected_to_stack` is [fiber local](https://github.com/rails/rails/blob/v8.0.1/activerecord/lib/active_record/core.rb#L205-L213), so I don't understand how it's leaking into another thread.

Maybe because `ActionController::Live` copies the thread-locals to the other thread: https://github.com/rails/rails/blob/v8.0.1/actionpack/lib/action_controller/metal/live.rb#L276

**Comment by eileencodes** [comment]
It does seem to be related to how thread-locals are copied with `ActionController::Live`. I've come up with a solution for setting specific keys as excluded so applications can opt-out of sharing the database context. See https://github.com/rails/rails/pull/56393

**Comment by chaadow** [comment]
@jscheid Thank you for sharing this. I had the same issue which I could solve with `config.action_controller.live_streaming_excluded_keys = [:active_record_connected_to_stack]` What a scare. Some agent triggered a CSV export ( which uses the read replica ) which triggered a `ActionController::Live::ClientDisconnected`

thanks to your instructions, I managed to replicate it locally. I wish this `config.action_controller.live_streaming_excluded_keys = [:active_record_connected_to_stack]` was the default.

**Comment by eileencodes** [comment]
> I wish this config.action_controller.live_streaming_excluded_keys = [:active_record_connected_to_stack] was the default

If I made it the default and backported it, it's potentially a breaking change. I could make it the default in a future version with a deprecation warning. I'm just not sure if anyone is depending on the old behavior for some reason.
