### ISSUE TITLE
Time.find_zone has inconsistent behavior between mac and linux environments for "America/Indianapolis"

### ISSUE THREAD

**Issue by iyaz-shaikh** [rails/rails#52949]
### Steps to reproduce

Hey folks,

I've encountered some strange behavior in a rails console between a linux environment and a darwin (m1 macbook) environment. When trying to do a 

```ruby
Time.find_zone("America/Indianapolis")
```

I get different behavior between the two environments. On the macbook environment, the method returns a timezone object with the expected timezone. On the linux environment, the method returns as `nil`. See below:

Linux:
<img width="714" alt="Screenshot 2024-09-16 at 1 35 35 PM" src="https://github.com/user-attachments/assets/3c3b2be2-462e-4544-8b30-0964453f602a">

<img width="409" alt="Screenshot 2024-09-16 at 1 35 43 PM" src="https://github.com/user-attachments/assets/1e91e964-07ba-4629-b385-219cc85b46e9">

Darwin:
<img width="707" alt="Screenshot 2024-09-16 at 1 35 10 PM" src="https://github.com/user-attachments/assets/7c2720b3-b18b-4b16-930f-19b09132720a">

<img width="1062" alt="Screenshot 2024-09-16 at 1 35 26 PM" src="https://github.com/user-attachments/assets/3d50ee48-7924-4caa-9261-12de494bd1c4">

The gem version of ActiveSupport is 7.2.1 on both machines as well. This seems like a bug but I wanted to open an issue here to see what folks thought.

Reproduction script in a rails console:
```ruby
Time.find_zone("America/Indianapolis")
```

### Expected behavior
Both environments should either return `nil` or a proper timezone object

### Actual behavior
The darwin environment returns a proper timezone object while the linux environment returns `nil`.

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.3.1

**ActiveSupport version**: 7.2.1

**Comment by jeromedalbert** [comment]
The `America/Indianapolis` timezone is obsolete [^1] [^2]. You should be using `America/Indiana/Indianapolis` instead, or its Rails friendly name `Indiana (East)`[^3].

So I am not surprised that you are getting inconsistent behavior between Darwin and the version of Linux you are using. You can run `find -L /usr/share/zoneinfo/ -type f` to find the list of supported timezones on your OS.

I believe this issue can be closed as it does not seem to be a Rails problem.

[^1]: https://www.timezoneconverter.com/cgi-bin/zoneinfo.tzc?s=default&tz=America/Indianapolis
[^2]: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#Time_zone_abbreviations
[^3]: https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html

**Comment by matthewd** [comment]
Yeah, Rails is dependent on the system timezone database (or, if present, the `tzinfo-data` gem)

**Comment by iyaz-shaikh** [comment]
Sounds good, thanks for the quick feedback all 🙏
