### ISSUE TITLE
Can't use ActiveRecord::Base.connection to check the existence of the DB  in Rails 7.2.1

### ISSUE THREAD

**Issue by zameo94** [rails/rails#52946]
Hi all!
I have a problem when checking the DB existence after upgrading to Rails 7.2.1.
With Rails 7.1.3.4, I had this method to check if the DB exists:

```
def self.database_exists?
    ActiveRecord::Base.connection
  rescue ActiveRecord::NoDatabaseError
    false
  else
    true
end
```

After the update, whether the DB exists or not, with `ActiveRecord::Base.connection` I got this output:

`#<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x00000000021e80 env_name="test" role=:writing>`

At the moment, I run that check with a raw query, which I would like to avoid:

```
def self.database_exists?
    ActiveRecord::Base.connection.execute("SHOW DATABASES").any?
  rescue ActiveRecord::NoDatabaseError
    false
end  
```

What method should I use to emulate my old behavior in Rails 7.2.1?

Thanks!

### System configuration
**Rails version**: 3.3.4

**Ruby version**: 7.2.1

**Comment by rafaelfranca** [comment]
`ActiveRecord::Base.connection.database_exists?`

**Comment by zameo94** [comment]
@rafaelfranca Thanks a lot!
