### ISSUE TITLE
[Bug][Railties] Generating scaffold don't apply tailwindcss template if rails new command with '--css=tailwind --javascript=esbuild'

### ISSUE THREAD

**Issue by takaokouji** [rails/rails#52942]
### Steps to reproduce

I created new rails application with `--css=tailwind --javascript=esbuild` command line options. Then I run `bin/rails generate scaffold Diary written_on:date:uniq content:string`. After that, it created *.html without tailwindcss's classes.

app/views/diaries/index.html.erb:
```html
<p style="color: green"><%= notice %></p>

<% content_for :title, "Diaries" %>

<h1>Diaries</h1>

<div id="diaries">
  <% @diaries.each do |diary| %>
    <%= render diary %>
    <p>
      <%= link_to "Show this diary", diary %>
    </p>
  <% end %>
</div>

<%= link_to "New diary", new_diary_path %>
```

Because generated Gemfile miss `tailwindcss-rails` gem.

Related codes are here:
https://github.com/rails/rails/blob/ac4dfd23d6f046ff522eca655a02557de3fa5b18/railties/lib/rails/generators/app_base.rb#L613-L619

This is my fix.

```ruby
      def css_gemfile_entry
        return if options[:api]
        return unless options[:css]

        if !using_js_runtime? && options[:css] == "sass"
          return GemfileEntry.floats "dartsass-rails", "Use Dart SASS [https://github.com/rails/dartsass-rails]"
        else

        gemfile_entries = []
        if using_js_runtime? || options[:css] != "tailwind"
          gemfile_entries <<  GemfileEntry.floats "cssbundling-rails", "Bundle and process CSS [https://github.com/rails/cssbundling-rails]"
        end
        if options[:css] == "tailwind"
          gemfile_entries << GemfileEntry.floats "tailwindcss-rails", "Use Tailwind CSS [https://github.com/rails/tailwindcss-rails]"
        end
        gemfile_entries
      end
```

### Expected behavior

- new rails application with `--css=tailwind --javascript=esbuild` command line options
- run `bin/rails generate scaffold Diary written_on:date:uniq content:string`
- generated *.html **with** tailwindcss's classes

### Actual behavior

- new rails application with `--css=tailwind --javascript=esbuild` command line options
- run `bin/rails generate scaffold Diary written_on:date:uniq content:string`
- generated *.html **without** tailwindcss's classes

workaround:

After rails new, run below command.

```bash
bin/bundle add tailwindcss-rails
```

### System configuration
**Rails version**:
7.2.1

**Ruby version**:
3.3.5

**Comment by hahmed** [comment]
Could you print out the output of `rails new tailwinder --css=tailwind --javascript=esbuild` please? Also do you have node installed?

**Comment by flavorjones** [comment]
Please see existing https://github.com/rails/tailwindcss-rails/discussions/237
