### ISSUE TITLE
ActionText adding a spurious `content: ''` to rich text attachments causing them to not preview in the editor

### ISSUE THREAD

**Issue by Jeremy-Walton** [rails/rails#52947]
### Steps to reproduce

1. Create a simple app
2. Install Action Text and Trix
3. Add a new record with attached rich content and a form to add it.
4. Create a new record with an attached image, save it, and then edit the record.

### Expected behavior
The Trix editor should render images in the rich content editor.

### Actual behavior

![Screenshot 2024-09-16 at 10 58 57 AM](https://github.com/user-attachments/assets/3b2189db-acaa-4f4e-9037-9db32daad4a5)

![Screenshot 2024-09-16 at 10 59 04 AM](https://github.com/user-attachments/assets/874a65ce-6fa4-41c1-a70e-4f4b7f0ea7f3)

![Screenshot 2024-09-16 at 11 02 31 AM](https://github.com/user-attachments/assets/0e660651-d900-4511-bfd4-6d4e14339ad8)

![Screenshot 2024-09-16 at 11 02 52 AM](https://github.com/user-attachments/assets/703fb91e-71bb-4867-9cbe-10eeac43149c)

It only shows the caption and delete X.

This seems to have been introduced by https://github.com/rails/rails/commit/1ac6d40d36a07b48a67bc7f8627fd1f92bffcb14
in `actiontext/lib/action_text/content.rb#97`.

If the `sanitize_content_attachment(node["content"])` returns a nil, it still adds `content: ''` to the node.

In Trix, https://github.com/basecamp/trix/blob/457a834808abe07058e4e8fda1b2cb0452868e2c/src/trix/models/attachment.js#L75
`this.hasContent()` is called to determine if the image is previewable.

https://github.com/basecamp/trix/blob/457a834808abe07058e4e8fda1b2cb0452868e2c/src/trix/models/attachment.js#L120
`return this.attributes.has("content")` returns true even though the content is an empty string. This results in Trix not returning 'preview' from `getType()`.

### System configuration
**Rails version**: 7.1.3.4

**Ruby version**: 3.3.1

**Trix js version**: 2.1.5

**@rails/actiontext js version**: 7.2.100

**Comment by p8** [comment]
This is fixed on 7-1-stable: https://github.com/rails/rails/pull/52281
