### ISSUE TITLE
UniquenessValidator raises error when used on singleton class

### ISSUE THREAD

**Issue by emilyst** [rails/rails#52959]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org/"

  gem "ostruct"
  gem "rails"
  gem "sqlite3"
end

require "active_record"
require "logger"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new($stdout)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
end

class SingletonClassUniquenessValidatorBugTest < Minitest::Test
  def test_uniqueness_of_singleton_class
    Post.create!(title: "First post!")

    second_post = Post.create!(title: "First post!")
    second_post.singleton_class.validates(:title, { uniqueness: true })
    refute second_post.valid?
  end
end
```

### Expected behavior

The validation should run without error and (in the example above) result in a value of `false`.

### Actual behavior

The validation on a model object whose singleton class has a uniqueness check raises `NoMethodError`.

```
% ruby singleton_class_uniqueness_validator_bug.rb
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
-- create_table(:posts, {:force=>true})
D, [2024-09-17T10:34:01.176316 #41590] DEBUG -- :    (3.7ms)  DROP TABLE IF EXISTS "posts"
D, [2024-09-17T10:34:01.176625 #41590] DEBUG -- :    (0.2ms)  CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar)
   -> 0.0065s
D, [2024-09-17T10:34:01.177367 #41590] DEBUG -- :    (0.0ms)  CREATE TABLE "schema_migrations" ("version" varchar NOT NULL PRIMARY KEY)
D, [2024-09-17T10:34:01.178278 #41590] DEBUG -- :    (0.0ms)  CREATE TABLE "ar_internal_metadata" ("key" varchar NOT NULL PRIMARY KEY, "value" varchar, "created_at" datetime(6) NOT NULL, "updated_at" datetime(6) NOT NULL)
D, [2024-09-17T10:34:01.191854 #41590] DEBUG -- :   ActiveRecord::InternalMetadata Load (1.4ms)  SELECT * FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = ? ORDER BY "ar_internal_metadata"."key" ASC LIMIT 1  [[nil, "environment"]]
D, [2024-09-17T10:34:01.192018 #41590] DEBUG -- :   ActiveRecord::InternalMetadata Create (0.0ms)  INSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES ('environment', 'development', '2024-09-17 17:34:01.191886', '2024-09-17 17:34:01.191888') RETURNING "key"
Run options: --seed 20979

# Running:

D, [2024-09-17T10:34:01.250838 #41590] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2024-09-17T10:34:01.250939 #41590] DEBUG -- :   Post Create (0.1ms)  INSERT INTO "posts" ("title") VALUES (?) RETURNING "id"  [["title", "First post!"]]
D, [2024-09-17T10:34:01.251007 #41590] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
D, [2024-09-17T10:34:01.251157 #41590] DEBUG -- :   TRANSACTION (0.0ms)  begin transaction
D, [2024-09-17T10:34:01.251204 #41590] DEBUG -- :   Post Create (0.1ms)  INSERT INTO "posts" ("title") VALUES (?) RETURNING "id"  [["title", "First post!"]]
D, [2024-09-17T10:34:01.251241 #41590] DEBUG -- :   TRANSACTION (0.0ms)  commit transaction
E

Finished in 0.003977s, 251.4458 runs/s, 0.0000 assertions/s.

  1) Error:
SingletonClassUniquenessValidatorBugTest#test_uniqueness_of_singleton_class:
NoMethodError: undefined method `superclass' for nil
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.2.1/lib/active_record/validations/uniqueness.rb:63:in `find_finder_class_for'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.2.1/lib/active_record/validations/uniqueness.rb:20:in `validate_each'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/validator.rb:155:in `block in validate'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/validator.rb:151:in `each'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/validator.rb:151:in `validate'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:385:in `block in make_lambda'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:179:in `block in call'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:668:in `block (2 levels) in default_terminator'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:667:in `catch'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:667:in `block in default_terminator'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:180:in `call'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:559:in `block in invoke_before'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:559:in `each'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:559:in `invoke_before'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:109:in `run_callbacks'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:913:in `_run_validate_callbacks'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/validations.rb:441:in `run_validations!'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/validations/callbacks.rb:115:in `block in run_validations!'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:110:in `run_callbacks'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:913:in `_run_validation_callbacks'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/validations/callbacks.rb:115:in `run_validations!'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activemodel-7.2.1/lib/active_model/validations.rb:366:in `valid?'
    /Users/emily.strickland/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activerecord-7.2.1/lib/active_record/validations.rb:71:in `valid?'
    singleton_class_uniqueness_validator_bug.rb:35:in `test_uniqueness_of_singleton_class'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration

**Rails version**: 7.2

**Ruby version**: 3.3.5

### Analysis

Note that all the other validators seem to work in this case. `UniquenessValidator` is, uh, unique. That's why I believe this is a bug and not just an unsupported use case.

The code raising the error in `ActiveRecord::Validations::UniquenessValidator#find_finder_class_for` seems to be pretty old (from 2009) and likely predates Ruby's `Object#singleton_class` method, as well as the methods `#subclasses` and `#descendants` added in Rails 3. (I'm going off memory, so I might not be right in remembering versions.)

For what it's worth, there's a pretty easy workaround. The script below demonstrates. It might not be the best overall solution for this problem, but it's the least invasive thing I can think to use. (I can't use a refinement because (I think) it wouldn't be in scope at the point where this class is instantiated and used.)

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org/"

  gem "ostruct"
  gem "rails"
  gem "sqlite3"
end

require "active_record"
require "logger"
require "minitest/autorun"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new($stdout)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
end

module SingletonClassUniquenessValidator
  def find_finder_class_for(record)
    @klass = @klass.superclass if @klass.singleton_class?
    super
  end

  ActiveRecord::Validations::UniquenessValidator.prepend(self)
end

class SingletonClassUniquenessValidatorBugTest < Minitest::Test
  def test_uniqueness_of_singleton_class
    Post.create!(title: "First post!")

    second_post = Post.create!(title: "First post!")
    second_post.singleton_class.validates(:title, { uniqueness: true })
    refute second_post.valid?
  end
end
```

**Comment by rafaelfranca** [comment]
It seems you already found a solution. Care to send a PR?

**Comment by fatkodima** [comment]
Curious, can you describe a usecase for using a validator on singleton classes?

**Comment by emilyst** [comment]
> Curious, can you describe a usecase for using a validator on singleton classes?

Very good question. It allows you to create a validation against an _instance_ of a model rather than the model _class_. Using the singleton class means you avoid polluting the validators associated with the model.

I have a situation where I want to validate some objects differently than others.

**Comment by fatkodima** [comment]
> I have a situation where I want to validate some objects differently than others.

Yes, so please give some details about a real world use case. Maybe there is a better way to implement it, since no one reported this issue for too long. Before fixing, we need to understand the use case.

**Comment by emilyst** [comment]
I'm not sure how much detail you want, but here's a simplified version of my use case:

I have `Question` objects which define questions that go on a survey. Each `Question` can be multiple choice, free-form text, a number, etc. Some questions will be required, while others will not. Some accept only formatted answers like phone numbers, but others are more flexible. The `Question` model can't know what all objects will exist, so it can't know ahead of time what validations it will need. That means we can't simply define them on the model without doing something very complicated (like defining every possible validation on `Question` and then using a predicate method to determine if it should run).

Instead, we're creating validations for each `Question` object on the fly. (In our case, we're using database records, but it could be done using a configuration file, or manually from the console, or whatever.)

This works out great, except in the case of `UniquenessValidator`. I have already worked around the issue locally, using the workaround I described earlier. I thought that the Rails project might like to be aware of the fact that `UniquenessValidator` is exceptional in this way. I don't feel strongly about this either way, and I'm perfectly happy to close this issue if you think there's no value in changing this behavior.

**Comment by fatkodima** [comment]
From the description, can't this be implemented via some database column to differentiate the question types (say `question_type` column) and some custom validation that does different checks depending on which value that column have? 

Something like:
```ruby
class Question < ApplicationRecord
  validate :validate_something

  def validate_something
    if question_type = "type1"
      # do some uniqueness validation
    else
      # do some other uniqueness validation
    end
  end
end
```

**Comment by emilyst** [comment]
That's basically the alternative I described earlier ("defining every possible validation on Question and then using a predicate method to determine if it should run"). It means you can't add new types of questions without a code change.

There are other drawbacks I can imagine, such as needing unwieldy logic to avoid repetition. What if two types of questions need the same validation? Now you've got to factor that validation into some reusable component. Rails already has these reusable components, in the form of `ActiveModel::Validator`.

All that said, it genuinely seems as if you do not regard this issue as a bug, and I'm content to close this issue if so.

**Comment by fatkodima** [comment]
> What if two types of questions need the same validation? 

`if question_type == "type1" || question_type == "type2"` ?

You probably still use some conditional logic to decide which objects get which validation? I don't understand how this is simpler than the custom validation.

I don't know, I will let @rafaelfranca decide if this is the bug we want to fix.

**Comment by rafaelfranca** [comment]
Did https://github.com/rails/rails/pull/52972 solve the problem?

**Comment by bogdan** [comment]
> Did https://github.com/rails/rails/pull/52972 solve the problem?

No, it was just the performance.

**Comment by emilyst** [comment]
Correct. #52972 will still rely on `@klass` being in the hierarchy of `record.class`, which is not the case for singleton classes.
