### ISSUE TITLE
.true? and false?

### ISSUE THREAD

**Issue by sebyx07** [rails/rails#53018]
patch with active support TrueClass and FalseClass
similar to 0.zero?

```ruby
class TrueClass
  def true?
     true
  end
  
  def false?
    false
   end
end

class FalseClass
  def true?
     false
  end
  
  def false?
    true
   end
end
```

imo I would find it useful in context such as:

```ruby
def check_if_button_is_disabled?
  driver.css('button').has_attribute('disabled').false?
end
```

instead of 
```
driver.css('button').has_attribute('disabled').blank?
driver.css('button').has_attribute('disabled') == false
!driver.css('button').has_attribute('disabled')
```

**Comment by sebyx07** [comment]
I can work on a pr, if this gets approved

**Comment by simi** [comment]
Not sure if the example is related to system tests, but for you usecase you should use `assert` or `refute` in tests.

**Comment by skipkayhil** [comment]
Thank you for opening an issue but I'm going to have to close this because we reserve issues for bugs in Rails.

Feature requests are best discussed on a PR implementing them, or you can start a thread on the [forums](https://discuss.rubyonrails.org/c/rubyonrails-core/5)
