### ISSUE TITLE
ActiveSupport::HashWithIndifferentAccess and the splat operator

### ISSUE THREAD

**Issue by bruno-b-martins** [rails/rails#53015]
### Steps to reproduce

```ruby
def foo(bar: nil)
  bar
end
hash = ActiveSupport::HashWithIndifferentAccess.new(bar: "xyz")
foo(**hash)
```

### Expected behavior

I was expecting the above script to work because "IndifferentAccess" makes `hash` accept `:bar` and `"bar"`.
However, I'm not sure if this is the intended behavior or not. Can you please clarify me? :bow: 

### Actual behavior

`foo(**hash)` raises an `ArgumentError` since the splat operator is passing `"bar"` instead of `:bar` to `foo`.

Other things I tried:
`Hash` works fine (`hash = { bar: "xyz" }`).
Using `.deep_symbolize_keys` makes `HashWithIndifferentAccess` work but `.deep_transform_keys { |key| key.to_sym }` does not.

### System configuration
**Rails version**:
7.1.4
**Ruby version**:
3.3.5

**Comment by rafaelfranca** [comment]
HashWithIndifferentAccess stores the keys always as strings, not symbol. They have indifferent access, not indifferent storage
