### ISSUE TITLE
ActionDispatch::RequestId#make_request_id strips needed characters from X-Request-ID

### ISSUE THREAD

**Issue by wgrrrr** [rails/rails#53043]
`ActionDispatch::RequestId#make_request_id` currently strips all characters from the `X-Request-ID` that do not conform to the pattern `/[^\w\-@]/`. We are trying to use the CloudFront request ID available to us through the header `X-Amz-Cf-Id` (which we have passed to our app via proxy as `X-Request-ID`),  but the values are padded with equal signs which are being stripped by this method. This means we are unable to trace requests from CloudFront through to our Rails app.

An example value of `X-Amz-Cf-Id` is this `sjgxAo-1K9Z_3leC_noAbpH5tb2f86FFyrGaAzp---jD7Wm2dXaJPg==`

### Steps to reproduce
Send a request to the Rails app where the HTTP header `X-Request-ID` has the value `sjgxAo-1K9Z_3leC_noAbpH5tb2f86FFyrGaAzp---jD7Wm2dXaJPg==`.

### Expected behavior
`X-Request-ID` in the Rails app (as available through `request.uuid` method call) should be `sjgxAo-1K9Z_3leC_noAbpH5tb2f86FFyrGaAzp---jD7Wm2dXaJPg==`.

### Actual behavior
The `X-Request-ID` header value is shown as `sjgxAo-1K9Z_3leC_noAbpH5tb2f86FFyrGaAzp---jD7Wm2dXaJPg`

### System configuration
**Rails version**: 7.0.8.4

**Ruby version**: 3.1.6

**Comment by zzak** [comment]
It's a good find, I think the default is probably too restrictive but I'm weary to change it (the last time was in #31815). Perhaps it should be configurable. Are you interested in working on a PR?

**Comment by khaile** [comment]
Hi @zzak! Could you assign this issue to me?

**Comment by dhh** [comment]
I think you're better off adding your own method/header extractor ala #amz_id rather than try to override an existing Rails method that's designed to work only with the Rails native request id. I don't think making this configurable is worth the complexity increase.
