### ISSUE TITLE
ActiveRecord not using join alias under certain conditions

### ISSUE THREAD

**Issue by alanoliveira** [rails/rails#53063]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_one :comment
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.create_comment!

    # -- OK --
    # INNER JOIN "comments" "comment" ON "comment"."post_id" = "posts"."id"
    assert_equal [1], Post.joins(:comment).where(comment: {id: 1}).pluck(comment: [:id])

    # -- NG --
    # INNER JOIN "comments" ON "comments"."post_id" = "posts"."id"
    assert_equal [1], Post.joins(:comment).pluck(comment: [:id])
  end
end
```

### Expected behavior
Rails use the join alias `"comments" "comment" ` in both queries.

### Actual behavior
The alias is not used when `where` clause is absent.

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.3.4

**Comment by kabirpathak** [comment]
Took some time, but I think i've found the reason. 

From `activerecord/lib/active_record/associations.rb` 
https://github.com/rails/rails/blob/15ddce90583bdf169ae69449b42db10be9f714c9/activerecord/lib/active_record/associations.rb#L818-L830

And i think `.pluck(comment` isn't counted as a reference because it only works on the result set, and does not affect the actual query. But i'm not sure.

`Post.joins(:comment).pluck(comments: [:id])` this works. 

I would love to open a PR. Waiting for confirmation.

**Comment by kamipo** [comment]
Sorry, I already worked before I saw this new comment.

**Comment by kabirpathak** [comment]
No worries. This is too difficult for me anyways!

**Comment by alanoliveira** [comment]
Hello @kamipo san,
Thank you very much for your quick fix.

Sorry, I'm not sure if I should open a new issue, but I found another case where the alias is not used (tested with ba468db0bdc880c694df091b5800d114e963eff0 and 7.2.1).


```
Post.joins(:comment).merge(Comment.where(id: 1)).pluck(comment: [ :id ])
```

**Comment by kabirpathak** [comment]
@kamipo can you please assign this followup ticket to me?

**Comment by kamipo** [comment]
I added an extra test for `pluck` with hash values 3780c138694091140c52601f6214f12bc7221eac.

https://github.com/rails/rails/blob/3780c138694091140c52601f6214f12bc7221eac/activerecord/test/cases/calculations_test.rb#L1151-L1154

> Sorry, I'm not sure if I should open a new issue, but I found another case where the alias is not used (tested with https://github.com/rails/rails/commit/ba468db0bdc880c694df091b5800d114e963eff0 and 7.2.1).
> ```
> Post.joins(:comment).merge(Comment.where(id: 1)).pluck(comment: [ :id ])
> ```

What you are saying “the alias is not used” is `pluck` or `merge`?

**Comment by alanoliveira** [comment]
> What you are saying “the alias is not used” is pluck or merge?

`merge` is not using the alias.

```sql
SELECT "comment"."id" -- pluck is ok
FROM "posts" INNER JOIN "comments" "comment" ON "comment"."post_id" = "posts"."id" 
WHERE "comments"."id" = ? -- merge is not ok
```

**Comment by kamipo** [comment]
`merge` just get the generated where clauses. Use `where` with alias for the purpose.

```ruby
Post.joins(:comment).merge(Comment.where(comment: { id: 1 })).pluck(comment: [ :id ])
# or
Post.joins(:comment).where(comment: { id: 1 }).pluck(comment: [ :id ])
```

**Comment by alanoliveira** [comment]
Actually the where was just the simplest example I could think. 
The real problem is when `merge` is used with a scope.


Let me share a better example:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: "rails/rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_one :comment
end

class Comment < ActiveRecord::Base
  belongs_to :post

  scope :ordered, -> { order(:id) }
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!
    post.create_comment!

    # ok
    Post.joins(:comment).where(comment: { id: 1 }).to_a

    # ng
    Post.joins(:comment).where(comment: { id: 1 }).merge(Comment.ordered).to_a
  end
end
```
