### ISSUE TITLE
minitest spec style and ruby -n does not work with full test name

### ISSUE THREAD

**Issue by grosser** [rails/rails#53074]
### Steps to reproduce

```
describe :foo do
  it "bar" do
    puts "baz"
  end
end
```

- does not work with `test "bar" do` either
- works with `class Foo < Minitest::Test` and `def test_bar`

run any test and copy the test name it produces:

```ruby
ruby test/models/model_test.rb -v
Run options: -v --seed 21156

# Running:

Model::#name#test_0001_is permalink = 0.15 s = .
```

then run that:
```
ruby test/models/model_test.rb -n 'Model::#name#test_0001_is permalink' -v
```
... and nothing happens

### Expected behavior
run the single test

... worked on 7.0
broken on 7.1.3.4
broken on 7.1.0

### Actual behavior
runs nothing

### System configuration
**Rails version**: 7.2.1
**Minitest version**: 5.24.1
**Ruby version**: 3.2.2

**Comment by Earlopain** [comment]
Can you provide a reproducable app? Trying this out myself I don't get a difference in test name with the example you gave, I just get `foo#test_0001_bar` in both cases which seems correct.

**Comment by grosser** [comment]
the test name is the same, the problem is that it cannot run the test

```
Nothing ran for filter: bar#test_0001_baz

Did you mean?  test_0001_baz
```

... started commenting out stuff until I found
```
Minitest::Spec::DSL::TYPES[-1] = [//, ActiveSupport::TestCase]
```
was causing it 🤦

**Comment by grosser** [comment]
found it https://github.com/minitest/minitest-rails/issues/256

**Comment by Earlopain** [comment]
Ah, right. I thought you were saying that the test name output changed between versions, my bad
