### ISSUE TITLE
`test_select_with_not_exists_field` fails against sqlite3_mem since ba468db

### ISSUE THREAD

**Issue by yahonda** [rails/rails#53097]
Managed to reproduce CI failure https://buildkite.com/rails/rails-nightly/builds/1083#01923a70-2a43-43bb-8f67-a0a2e9441f6a/1249-1258

### Steps to reproduce

```ruby
git clone https://github.com/rails/rails
cd rails/activerecord
bundle install
ARCONN=sqlite3_mem bin/test test/cases/relation/select_test.rb:31
```

### Expected behavior
It should pass.

### Actual behavior
```ruby
$ ARCONN=sqlite3_mem bin/test test/cases/relation/select_test.rb:31
Using sqlite3_mem
Run options: --seed 20687

# Running:

F

Failure:
ActiveRecord::SelectTest#test_select_with_not_exists_field [test/cases/relation/select_test.rb:31]:
ActiveRecord::StatementInvalid expected but nothing was raised.


bin/test test/cases/relation/select_test.rb:30



Finished in 0.063685s, 15.7022 runs/s, 15.7022 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
$
```

### System configuration
**Rails version**: main branch

**Ruby version**: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]

**Comment by fatkodima** [comment]
https://github.com/rails/rails/pull/53095

**Comment by yahonda** [comment]
Thanks for the info. Closing this as #53095 already exists.

**Comment by yahonda** [comment]
Well, no needed to close it.
