### ISSUE TITLE
Certain prepared statements with `TIMESTAMP` raise `PG::SyntaxErrors`

### ISSUE THREAD

**Issue by andrewjanssen** [rails/rails#53094]
# Steps to reproduce

1. Make a query like `Post.where("created_at < TIMESTAMP ? - INTERVAL '1 day'", Time.now)`.
2. Cause it to be executed with `pluck(:id)`, `first`, etc.
3. An exception is raised.
4. 😿

Here's a repro script.

```
# frozen_string_literal: true

require "bundler/inline"

# Some tests in this file begin to fail when using this commit.
failing_ref = "684131a4f0b34ec758b17868981a526ec9f8805f"

# All tests in this file pass when using its parent.
previous_ref = "baad391196b7ea6f6072447ee503bae8f25af76b"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", github: "rails/rails", ref: failing_ref
  gem "pg"
end

require "active_record/railtie"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "postgresql", host: "localhost", database: "postgres")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.timestamps
  end
end

class Post < ActiveRecord::Base
end

class Bug < Minitest::Test
  def test_certain_queries_begin_to_fail_with_684131a
    # These begin to fail with 684131a, raising a PG::SyntaxError.
    Post.where("created_at < TIMESTAMP ? - INTERVAL '1 day'", Time.now).pluck(:id)
    Post.where("created_at + INTERVAL '1 day' < TIMESTAMP ?", Time.now).pluck(:id)

    # This query continues to succeed even with 684131a.
    Post.where("created_at + INTERVAL '1 day' < ?", Time.now).pluck(:id)
  end

  def test_these_queries_still_work_if_in_unprepared_statements
    # Even with 684131a, no PG::SyntaxErrors are raised.
    Post.connection.unprepared_statement do
      Post.where("created_at < TIMESTAMP ? - INTERVAL '1 day'", Time.now).pluck(:id)
      Post.where("created_at + INTERVAL '1 day' < TIMESTAMP ?", Time.now).pluck(:id)
      Post.where("created_at + INTERVAL '1 day' < ?", Time.now).pluck(:id)
    end
  end

  def test_to_sql_still_works
    # Even with 684131a, no PG::SyntaxErrors are raised.
    assert Post.where("created_at < TIMESTAMP ? - INTERVAL '1 day'", Time.now).to_sql.match?(
      /SELECT "posts"\.\* FROM "posts" WHERE \(created_at < TIMESTAMP '.*' - INTERVAL '1 day'\)/
    )
    assert Post.where("created_at + INTERVAL '1 day' < TIMESTAMP ?", Time.now).to_sql.match?(
      /SELECT "posts"\.\* FROM "posts" WHERE \(created_at \+ INTERVAL '1 day' < TIMESTAMP '.*'\)/
    )
    assert Post.where("created_at + INTERVAL '1 day' < ?", Time.now).to_sql.match?(
      /SELECT "posts"\.\* FROM "posts" WHERE \(created_at \+ INTERVAL '1 day' < '.*'\)/
    )
  end
end
```

# Expected behavior

I expected to continue to be able to make queries like `Post.where("created_at < TIMESTAMP ? - INTERVAL '1 day'", Time.now).pluck(:id)`. This worked through Rails 7.1, but began to fail with 684131a in 7.2.

# Actual behavior

`ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "$1"
LINE 1: ..."posts" WHERE (created_at < TIMESTAMP $1 - INTERVAL '1 day')`

# System configuration
Rails version: master

# Ruby version
3.3.5

# See also
* https://github.com/rails/rails/pull/51139
* https://github.com/rails/rails/issues/52052
* https://github.com/rails/rails/issues/51617
* https://github.com/rgeo/activerecord-postgis-adapter/issues/402

**Comment by byroot** [comment]
So, I don't know postgres well, and I'm quite annoyed to see how limited their prepared statement are, but in this specific case isn't the solution to use a less ambiguous casting syntax?

```ruby
Post.where("created_at < ?::TIMESTAMP - INTERVAL '1 day'", Time.now).pluck(:id)
```

**Comment by andrewjanssen** [comment]
> [...] in this specific case isn't the solution to use a less ambiguous casting syntax? `Post.where("created_at < ?::TIMESTAMP - INTERVAL '1 day'", Time.now)`

Thank you @byroot, your query there works and I hadn't thought of it. Instead, I had changed my query to (something similar to) `Post.where("created_at + INTERVAL '1 day' < ?", Time.now)`.

I confirmed that the exception is only raised when when the `postgresql` adapter is used:
  * `mysql2` and `trilogy` — My original query works before and after 684131a: `Post.where("created_at < TIMESTAMP ? - INTERVAL 1 day", Time.now)` (`1 day` is unquoted for MySQL).
* `sqlite3` — `INTERVAL` and `TIMESTAMP` do not exist in SQLite.

**Comment by byroot** [comment]
Alrigth, I'll close then. I understand this change will cause some churn for some users, but there's unfortunately nothing I can think of that we could realistically do to continue supporting this without losing all the prepared statement improvements.

**Comment by andrewjanssen** [comment]
Okay. Thanks for discussing! And for your work on Ruby/Rails in general.
