### ISSUE TITLE
Authentication generator does not reset sessions on login/logout in accordance with the rails security guide

### ISSUE THREAD

**Issue by erikbelusic** [rails/rails#53129]
The Rails security guides say

> The most effective countermeasure is to issue a new session identifier and declare the old one invalid after a successful login. That way, an attacker cannot use the fixed session identifier. This is a good countermeasure against session hijacking, as well. Here is how to create a new session in Rails: `reset_session`

in the [session-fixation-countermeasures](https://guides.rubyonrails.org/security.html#session-fixation-countermeasures) section

### Steps to reproduce
1. Generate a new application
2. Run the authentication generator
3. Manually create a user in the database
4. add `logger.info "SESSION_ID=#{session[:session_id]}"` to some controller action you hit
5. Visit site and check logs for session id
6. Login and check logs for session id
7. Logout  check logs for session id

### Expected behavior
Sessions are reset after login and logout to mirror best practices in Rails docs.

### Actual behavior
Session ID is the same before login, after login, and after sign out. (unless there is a reason this security measure is not needed with the generated code)

### System configuration
**Rails version**: 8.0.0.beta1

**Ruby version**: 3.3.5

**Comment by codergeek121** [comment]
The relevant session identifier is saved in a `cookies.signed.permanent[:session_id]` cookie. This cookie's value is the `session.id`. The login (`SessionsController#create`) creates a new session on every login (`user.sessions.create!`). The session is destroyed on every logout as well. Iiuc The login cookie is therefore immune to session-fixation.

I'd argue the correct fix here would be to update the security guide.

**Comment by erikbelusic** [comment]
Just to confirm my understanding, this is a non-issue with the generator code because it does not rely on the `session_id` of the request session object and instead relies on the id of the DB backed session active record?

**Comment by rafaelfranca** [comment]
That is right. Session fixation is mitigated in this case by not using the cookie session store.
