### ISSUE TITLE
Default to SolidQueue in production.rb

### ISSUE THREAD

**Issue by HamptonMakes** [rails/rails#53141]
When you upgrade to Rails 8, the template for the updated `config/environment/production.rb` has the following:

```
  # Replace the default in-process and non-durable queuing backend for Active Job.
  # config.active_job.queue_adapter = :resque
```

I'm thinking it should suggest :solid_queue instead, but since this is only the upgrade path- it should show the new-style configuration commented out.

```
  # Replace the default in-process and non-durable queuing backend for Active Job.
  # config.active_job.queue_adapter = :solid_queue
  # config.solid_queue.connects_to = { database: { writing: :queue } }
```

Thoughts?

**Comment by HamptonMakes** [comment]
I believe this addresses something that was supposed to be changed in #52804

**Comment by JoeDupuis** [comment]
I just tested with Rails 8 and I am getting: 

```ruby
  # Replace the default in-process and non-durable queuing backend for Active Job.
  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = { database: { writing: :queue } }
```

not

```ruby
# Replace the default in-process and non-durable queuing backend for Active Job.
# config.active_job.queue_adapter = :resque
```

`production.tt` contains the latter, but solid_queue install step replace it: https://github.com/rails/solid_queue/blob/main/lib/generators/solid_queue/install/install_generator.rb#L14-L19

Try regenerating a new app. I suspect that the wrong version of Rails was used.

**Comment by HamptonMakes** [comment]
@JoeDupuis Ah, I need to rephrase then maybe- that just confused me.

This happened to me first when I was upgrading my application to Rails 8- it nuked my :solid_queue settings and I saw it recommending `:resque`

Perhaps the right approach here is to have it commented out until the install step? That way, existing applications can have a nice suggestion on the recommended Rails 8 way to do it, but not attempt to enable Solid Queue in the upgrade path, since they also won't have some of the new configurations set (like changes in `database.yml` for multi-database and the schema changes.

**Comment by JoeDupuis** [comment]
Oh I see! It was an existing Rails 7 app with solid queue installed and you ran the `bin/rails app:update` on Rails 8, I'll respond on the PR. #53143

**Comment by HamptonMakes** [comment]
Just updating here... fixing this would likely require a change in the SolidQueue code, which I have prepared but also there is a lack of tests around the generators, and as a new-ish contributor I'm sure I'll need to get those in order.

I'm going to take this to the RailsCore discussion list to get feedback on the best way to solve.

**Comment by rafaelfranca** [comment]
@dhh not sure what to do here. Should upgrading an existing app configure solid queue? I don't think it should. Like any other custom configuration you add, the update task will override everything you need to use git to know what you want to keep

**Comment by dhh** [comment]
No, I don't think existing apps should be updated. Switching your queuing backend is a big change. You should do that manually. So I say update shouldn't do anything.

**Comment by JoeDupuis** [comment]
@dhh The issue is that from now on, every update will try to revert your job queue back to the default for Rails 7.

I would expect `app:update` to produce no diff if called right after `rails new`, but currently, it produces this diff:

```
--- a/config/environments/production.rb
+++ b/config/environments/production.rb
@@ -47,12 +47,10 @@ Rails.application.configure do
   config.active_support.report_deprecations = false

   # Replace the default in-process memory cache store with a durable alternative.
-  config.cache_store = :solid_cache_store
+  # config.cache_store = :mem_cache_store

   # Replace the default in-process and non-durable queuing backend for Active Job.
-  config.active_job.queue_adapter = :solid_queue
-  config.solid_queue.connects_to = { database: { writing: :queue } }
-
+  # config.active_job.queue_adapter = :resque

   # Ignore bad email addresses and do not raise email delivery errors.
   # Set this to true and configure the email server for immediate delivery to raise delivery errors.
```
`rails new` followed by `rails app:update` makes no sense, but it illustrates what people will hit when upgrading from Rails 8 to 8.1.

In the draft PR (#53143), I suggest using the Active Storage update pattern: only re-run the install script if the Solid gems are detected.

This would fix the subsequent `rails new` > `rails app:update` diff without installing Solid Queue on apps that use a different queue.

I'm unsure if it's worth the added complexity in the framework, since updates should ideally be done with git's help, but this is already an existing pattern (Active Storage).

**Comment by rafaelfranca** [comment]
That is the wrong expectation. `rails new` followed by `rails app:upgrade` can and will generate different results.

I think I'm ok with keeping `:resque` as the recommended queue when upgrading an existing Rails application at least for one more release.
