### ISSUE TITLE
Opt out of `touch` bumping lock_version ?

### ISSUE THREAD

**Issue by jdelStrother** [rails/rails#53178]
Anyone else find it surprising that` touch` bumps OptimisticLocking's lock_version ?
It was [added as a feature](https://github.com/rails/rails/commit/8bc464c8090f2929917ecd2d9476c914aa6da787) back in 2011, but I'm not sure I see why that would be useful.

---

One example where this is causing problems is in forms that accept ActiveStorage uploads.
Say I have a Post editing form which accepts some text fields for the post title & body, and an ActiveStorage image upload.  Post has a lock_version column to try and avoid any stale reads.
If I submit the form with an image, then tweak the text fields and submit again, there's a good chance of hitting StaleObjectError because AnalyzeJob has asynchronously run on the image and touched the Post, bumping its lock_version.

---

There's some mention of this being surprising behaviour in https://github.com/rails/rails/pull/45579#issuecomment-2169844052 , but I don't think it got anywhere. (cc @natematykiewicz  )

Perhaps we could tweak `locking_enabled?`'s method signature? eg if we passed `attempted_action`  to the locking_enabled method here - https://github.com/rails/rails/blob/23729cec4eb591995f6ac6e88e49fd444e011f3c/activerecord/lib/active_record/locking/optimistic.rb#L87-L93  - then I could opt out of the lock_version bumps from touch methods:

```ruby
class ApplicationRecord
  def self.locking_enabled?(attempted_action: nil)
     attempted_action != "touch" && super
  end
end
```

### Steps to reproduce

Create a model with a lock_version column, call `touch` on it

### Expected behavior

updated_at is changed, lock_version is not

### Actual behavior

Both updated_at and lock_version are changed

**Rails version**: 7.2

**Comment by natematykiewicz** [comment]
I've caught a fair share of tags in the 2 years since I made #45579. Bumping the `lock_version` on `touch`, and PaperTrail inserting new rows on `touch` both seem like common issues. (The latter not being Rails' problem, obviously.)

I still agree with my comment you linked to. I don't think a `touch` should change the `lock_version`.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.

**Comment by jdelStrother** [comment]
OK, done: https://discuss.rubyonrails.org/t/opt-out-of-touch-bumping-lock-version/87582
