### ISSUE TITLE
Rate limiting does not reset between tests 

### ISSUE THREAD

**Issue by gstokkink** [rails/rails#53172]
Recently we decided to implement the new rate limiting introduced in Rails 7.2 into several of our controllers. However, we quickly noticed that controller tests started failing with the `429 Too Many Requests`. Turns out that the cache store, which stores the rate limiting keys, is not being reset in-between tests. This is not a problem if the default 'null store' is used for tests, but is an issue when using, for instance, the 'memory store'.

I'm not sure if this is something that Rails should fix by default, or is simply something that the developers should implement themselves (e.g., using an after-test callback). In the latter case the documentation might need updating to prevent surprises.

### Steps to reproduce

Note that in the below script I have to explicitly specify the store the rate limiter uses. The problem also occurs when simply setting `config.cache_store = :memory_store` for the test environment in a regular Rails application, however.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  routes.draw do
    get "/" => "test#index"
    get "/new" => "test#new"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  rate_limit to: 1, within: 1.minute, store: ActiveSupport::Cache::MemoryStore.new

  def index
    render plain: "Index"
  end

  def new
    render plain: 'New'
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def test_index
    get "/"
    puts last_response.status
    assert last_response.ok?
  end

  def test_new
    get "/new"
    puts last_response.status
    assert last_response.ok?
  end

  private

  def app
    Rails.application
  end
end
```

### Expected behavior

All tests should succeed.

### Actual behavior

```
# Running:

I, [2024-10-04T10:28:17.062079 #91741]  INFO -- : Started GET "/" for 127.0.0.1 at 2024-10-04 10:28:17 +0200
200
.I, [2024-10-04T10:28:17.104620 #91741]  INFO -- : Started GET "/new" for 127.0.0.1 at 2024-10-04 10:28:17 +0200
429
F

Finished in 0.051631s, 38.7364 runs/s, 38.7364 assertions/s.

  1) Failure:
BugTest#test_new [reproduction.rb:58]:
Expected false to be truthy.

2 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.3.5

**Comment by zzak** [comment]
Yeah, I'm not sure what to do because underneath `rate_limit` is just a before_action. So it seems like it would be quite a lift to support something like clearing the cache between tests.

One option is to change `config.action_controller.cache_store` to a null store in your test environment. It's probably OK since you don't really want to test the cache store implementation, unless you're using a custom store (then that is a separate issue).

The other option is, like you said, to use a teardown between tests. I've updated your script to demonstrate that and fix the failing test:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << "example.org"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger  = config.logger

  Rails.cache = ActiveSupport::Cache::MemoryStore.new

  routes.draw do
    get "/" => "test#index"
    get "/new" => "test#new"
  end
end

class TestController < ActionController::Base
  include Rails.application.routes.url_helpers

  rate_limit to: 1, within: 1.minute, store: Rails.cache

  def index
    render plain: "Index"
  end

  def new
    render plain: 'New'
  end
end

require "minitest/autorun"
require "rack/test"

class BugTest < Minitest::Test
  include Rack::Test::Methods

  def teardown
    cache_key = ["rate-limit", "test", "127.0.0.1"].join(":")
    Rails.cache.delete(cache_key)
  end

  def test_index
    get "/"
    puts last_response.status
    assert last_response.ok?
  end

  def test_new
    get "/new"
    puts last_response.status
    assert last_response.ok?
  end

  private

  def app
    Rails.application
  end
end
```

This is using the same name for the cache key, but that detail is internal and could change, perhaps an opportunity to explore making that discoverable or configurable in some way.

**Comment by Earlopain** [comment]
I make much use of `Rails.cache.clear` in my tests, which does remove _everything_ but at least for my use-case it doesn't matter. It will probably make trouble when using parallel tests with a cache store other than memory so definitly not a general solution (unless they are partitioned somehow, never looked into how that works)
