### ISSUE TITLE
Executor/Reloader does not work under 'rails runner'

### ISSUE THREAD

**Issue by seandilda** [rails/rails#53223]
### Steps to reproduce

Create a long that occasionally calls rails code through the [Executor](https://edgeguides.rubyonrails.org/threading_and_code_execution.html#executor) or Reloader and run it through `rails runner`.

```ruby
#!/usr/bin/env ruby

require_relative 'config/environment'

3.times do
  Rails.application.reloader.wrap do
    puts "Cache size: #{ActiveRecord::Base.connection.query_cache.size}"

    # Do any active record query here
    User.count
  end
end

```

### Expected behavior
I expect the query cache to always be empty at the beginning of the `wrap` block.  That behavior can be seen if the file is called directly:

```
$ ruby test.rb 
Cache size: 0
Cache size: 0
Cache size: 0
```

### Actual behavior
The cache is only empty the first time through the loop.  All future times through the loop, the query cache from the first loop is still present, preventing all future sql queries in the loop.

```
$ rails runner test.rb
Cache size: 0
Cache size: 1
Cache size: 1
```

### System configuration
**Rails version**: 7.2.1

**Ruby version**: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]

**Comment by seandilda** [comment]
After some digging around, I found #50223 and confirmed that the `--skip-executor` option does fix my issue.

```
$ rails runner --skip-executor test.rb
Cache size: 0
Cache size: 0
Cache size: 0
```

I believe this is now a documentation issue and the option should be added to https://guides.rubyonrails.org/command_line.html#bin-rails-runner and/or https://guides.rubyonrails.org/threading_and_code_execution.html#executor

**Comment by kabirpathak** [comment]
Preview: https://4c0e003e.rails-docs-preview.pages.dev/guides/command_line#bin-rails-runner
<img width="888" alt="image" src="https://github.com/user-attachments/assets/b25e0658-88b6-4540-ac4f-2afa6a6a28d7">

**Comment by seandilda** [comment]
@kabirpathak Thanks!  That looks great to me.
