### ISSUE TITLE
Another infinite loop in the DependencyTracker

### ISSUE THREAD

**Issue by brenogazzola** [rails/rails#53221]
Bug introduced in https://github.com/rails/rails/pull/50944.
A case of infinite loop was fixed here: https://github.com/rails/rails/pull/52978

This is a new one, caused probably by a bug in how Rails identifies the dependencies.

### Steps to reproduce
Add this to a view and try to load the page.

```erb
<% cache presenter.record do
  <%= render "orders/#{presenter.partial_name || "default"}" %>
<% end
```

### Expected behavior
Page renders

### Actual behavior
Page gets stuck in an infinite loop

### System configuration
**Rails version**: 773d640cf1d650356519acc9cb0bbc2c5c8de670
**Ruby version**: 3.3.5 

### Cause
The dependency tracker does not properly identify the dependency, getting this:
```
"orders/#{presenter.partial_name || "
```

Instead of the complete string:
```
"orders/#{presenter.partial_name || "default"}"
```

Because of this, the `while` loop below in the `ERBTracker` never exits, as it cannot find the ending `}`. 
```
while unmatched_brackets > 0 && !scanner.eos?
```

/cc @skipkayhil @jhawthorn I'm currently fixing this by moving the `||` to another place. I might take a stab at a PR at a later date, but I thought it was best to have this issue open in case someone else is having problems with the PR

**Comment by brenogazzola** [comment]
Fixed the code. I had added a } by mistake

**Comment by brenogazzola** [comment]
Seems like there is something else still causing problems. We've removed all `||` but we are still crashing after deploy. I'll try to find out what is is happening.

**Comment by jhawthorn** [comment]
Thanks for the report. I'll try to take a look later today. If there isn't a quick fix to fail forward with I'll revert the change add a test and we can try again later.

**Comment by brenogazzola** [comment]
Instead of trying to fix our partials, I decided to patch the ErbTracker to see if there was some other problem I was not seeing. What I did was replace this:
```ruby
if quote_type == '"' && dependency.include?('#{')
```

With this:
```ruby
if quote_type == '"' && dependency.include?('#{') && dependency.include?('}')
```

It worked. CPU usage remained where it was and nothing crashed. Though it feels to me like this might be fixing the symptom (the missing `}`) instead of the cause (the dependency string ending before the `}`).

That said, this is the first time I've read this part of Rails code and have no idea what is the correct way to fix this.

For reference, this is the initializer I used to test:
```ruby
require_dependency 'action_view/dependency_tracker'

module MonkeyPatches
  class ErbTracker < ActionView::DependencyTracker::ERBTracker
    def add_static_dependency(dependencies, dependency, quote_type)
      if quote_type == '"' && dependency.include?('#{') && dependency.include?('}')
        scanner = StringScanner.new(dependency)

        wildcard_dependency = +""

        while !scanner.eos?
          if scanner.scan_until(/\#{/)
            unmatched_brackets = 1
            wildcard_dependency << scanner.pre_match

            while unmatched_brackets > 0 && !scanner.eos?
              scanner.scan_until(/[{}]/)

              case scanner.matched
              when "{"
                unmatched_brackets += 1
              when "}"
                unmatched_brackets -= 1
              end
            end

            wildcard_dependency << "*"
          else
            wildcard_dependency << scanner.rest
            scanner.terminate
          end
        end

        dependencies << wildcard_dependency
      elsif dependency
        if dependency.include?("/")
          dependencies << dependency
        else
          dependencies << "#{directory}/#{dependency}"
        end
      end
    end
  end
end

Rails.application.config.to_prepare do
  ActionView::DependencyTracker.remove_tracker ActionView::DependencyTracker::ERBTracker
  ActionView::DependencyTracker.register_tracker :erb, MonkeyPatches::ErbTracker
end
```

**Comment by jhawthorn** [comment]
Thanks! Yes it seems the problem was the parser finding a mismatched number of `{`/`}`, so we needed to add an early exit in that case.
