### ISSUE TITLE
AR::Locking::Optimistic broken link to Pessimistic

### ISSUE THREAD

**Issue by zzak** [rails/rails#53248]
On the [AR::Locking::Optimistic](https://edgeapi.rubyonrails.org/classes/ActiveRecord/Locking/Optimistic.html) does, there is a paragraph:

> Check out `ActiveRecord::Locking::Pessimistic` for an alternative.

Due to the fixed-width markup, RDoc is unable to autolink it to the proper place:
https://github.com/rails/rails/blob/fae425b8fbbd0f78b151e5e2161b4daa5d5dd49a/activerecord/lib/active_record/locking/optimistic.rb#L12

You can either remove the fixed-width and get the auto-link, or create the link by hand, up to you.

See: https://ruby.github.io/rdoc/RDoc/MarkupReference.html#class-RDoc::MarkupReference-label-Links

**Comment by zalom** [comment]
@zzak I would like to take this one if that is fine. It looks like a low-hanging fruit, and I am just starting with the contributions.
