### ISSUE TITLE
Should Solid Cache be configured as the default in development?

### ISSUE THREAD

**Issue by faqndo97** [rails/rails#53272]
I recently started two new projects using the latest Rails 8 beta, and while testing various cache scenarios in development, I noticed that the default store is set to memory instead of solid cache. In my previous experience with most projects, if Redis or Memcached were used, they were also set as the default cache store in development. The advantage of this approach is having a more replicable environment, where the tools we use in development closely mirror those in production. My question is: Should solid cache, when installed, be set as the default cache store across all environments? Thanks!

**Comment by rafaelfranca** [comment]
Don't think so. The Development environment has no intention to mirror the behavior of the production environment.
