### ISSUE TITLE
[ActiveSupport::Cache::RedisCacheStore] Race condition when instantiating connection pools on JRuby

### ISSUE THREAD

**Issue by gillesbergerp** [rails/rails#53279]
### Steps to reproduce

Instantiate an ``ActiveSupport::Cache::RedisCacheStore`` and start reading/writing data from multiple threads simultaneously. 

The snippet below creates a single store and accesses its ``redis`` pool from 1000 promises (using https://github.com/ruby-concurrency/concurrent-ruby) and then proceeds to count the number of unique objects returned.

```ruby
store = ActiveSupport::Cache::RedisCacheStore.new(
  url: 'redis://redis-local:6379/0',
  pool_size: 32,
  pool_timeout: 10,
)

Concurrent::Promises
  .zip(*1000.times.map { Concurrent::Promises.delay { store.redis } })
  .value!
  .group_by(&:object_id)
  .count
```

### Expected behavior

Only one pool being instantiated.

### Actual behavior

Multiple pools/clients are instantiated.

### System configuration
**Rails version**: ``6.1.7.7``

**Ruby version**: ``jruby 9.4.8.0 (3.1.4)``

**Comment by gillesbergerp** [comment]
I just noticed that this should be fixed by https://github.com/rails/rails/commit/c07812cee2be727b334ed2c89ef1ceaa6b467447

**Comment by fatkodima** [comment]
You need to upgrade, https://guides.rubyonrails.org/maintenance_policy.html
