### ISSUE TITLE
Missing documentation on intended use of Devcontainers and Kamal along side

### ISSUE THREAD

**Issue by NielsKSchjoedt** [rails/rails#53294]
Using Rails 8 with Kamal and Devcontainers:

Since both Kamal and Devcontainers are becoming a default, I guess it's obvious to also cover how to best work with them together. I have started a discussion [here](https://discuss.rubyonrails.org/t/is-it-intended-to-use-kamal-2-from-within-the-devcontainer/87657) outlining the problem. The documentation for [devcontainers](https://edgeguides.rubyonrails.org/getting_started_with_devcontainer.html) or for Kamal in rails should probably hold some mention of intended use/best practice? If it is "decided" that kamal should be run from within the devcontainer, then the config should probably also see a change to support it. Thoughts?

**Comment by rafaelfranca** [comment]
This is a nice to have so I'll not block 8.0.0 because of it.

But, you only need to add https://github.com/devcontainers/features/tree/main/src/docker-outside-of-docker to the list of features of your devcontainer. Rails can generate it by default if Kamal is present. PRs welcome.

**Comment by JoeDupuis** [comment]
I just opened #53327 to add the required feature and environment  for this to work.
