### ISSUE TITLE
Add authentication constraints alongside Rails 8 authentication

### ISSUE THREAD

**Issue by simmerz** [rails/rails#53296]
Devise provides `authenticated(scope, block)` ([here](https://github.com/heartcombo/devise/blob/72884642f5700439cc96ac560ee19a44af5a2d45/lib/devise/rails/routes.rb#L314)) - I've found it really useful when I have different kinds of users but I want everyone to start at `/` with their own namespaced controller for their role.

I think something similar in the Rails authentication framework would be really useful.

**Comment by justinko** [comment]
`authenticated` depends on Warden: https://github.com/heartcombo/devise/blob/72884642f5700439cc96ac560ee19a44af5a2d45/lib/devise/rails/routes.rb#L479

I haven't looked at the Rails 8 auth generator code, but I'm almost certain it doesn't utilize Rack.

**Comment by JoeDupuis** [comment]
> I'm almost certain it doesn't utilize Rack.

It doesn't. I just finished porting a custom Warden setup to the new auth generator on a toy app. Everything lives in controllers/models.

**Comment by simmerz** [comment]
@JoeDupuis I'd be interested if you've done this kind of thing in your port and what a sensible approach might be? I'm guessing you'd be using the new sessions table and joining that to the user?

**Comment by rafaelfranca** [comment]
Thank you for the suggestion but that generator has no intention to support all existing cases.

**Comment by JoeDupuis** [comment]
@simmerz I don't have restrictions in my route file, only in my controllers.

**Comment by evdevdev** [comment]
I see that the issue is closed, but for anyone who happens to stumble upon it. 

@excid3 Has [a fantastic episode](https://gorails.com/episodes/routing-constraints-with-rails-authentication-generator) of GoRails that covers exactly this.
