### ISSUE TITLE
`Hash#to_json` is incompatible with `::JSON.{generate, dump}` with duplicate keys of different type

### ISSUE THREAD

**Issue by victorpolko** [rails/rails#53305]
According to [these comments](https://github.com/rails/rails/blob/v8.0.0.beta1/activesupport/lib/active_support/core_ext/object/json.rb#L31-L32), `::JSON.{generate,dump}` must be compatible with `Hash#to_json`.
There is a case when this is not true – when encoding a hash with duplicate keys of different type.

### Steps to reproduce

```ruby
# irb for a cleaner example
irb(main):001:0> require 'json'
true

irb(main):002:0> source_hash = { some: true, "some" => false } # duplicate key names, different key type
{:some=>true, "some"=>false}

irb(main):003:0> source_hash.to_json
"{\"some\":true,\"some\":false}" # expected
irb(main):004:0> JSON(source_hash)
"{\"some\":true,\"some\":false}" # expected
irb(main):005:0> JSON.generate(source_hash)
"{\"some\":true,\"some\":false}" # expected
irb(main):006:0> JSON.dump(source_hash)
"{\"some\":true,\"some\":false}" # expected

irb(main):007:0> require 'active_support'
true
irb(main):008:0> require 'active_support/core_ext'
true
irb(main):009:0> source_hash.to_json
"{\"some\":false}" # NOT expected
```

I believe that this behavior started with [this change](https://github.com/rails/rails/commit/0bed5bdb213ea68e2f167ac4f61f698f37cf2d69#diff-9ede9439761f1445d14184027370b603fdcf6eb1f50304d3c85f6756674afb60R42) some 15 years ago by @NZKoz, but I'd be glad to be wrong.

### System configuration
**Rails version**: checked with `6.1.7.7`

**Ruby version**: checked with `2.4.6`, `2.7.8`, `3.0.7`

**Comment by victorpolko** [comment]
Marking this issue as resolved as a side-effect from #48614 by @jhawthorn, which was considered an inconsistency in #50481 and json's [#564](https://github.com/ruby/json/pull/564).

**Comment by jhawthorn** [comment]
There's a little bit of awkwardness here. I'd like to say that it's invalid input and Rails doesn't guarantee any behaviour if you provide duplicate hash keys. `{"some":true,"some":false}"` is invalid JSON, but silently removing a key is also bad so there is no good choice here.

In an ideal world maybe we would detect duplicate hash keys and raise an error, but it's a bit too expensive to do and we don't generally provide such guardrails.

**Comment by byroot** [comment]
Newer versions of the `json` gem will handle this: https://github.com/ruby/json/pull/841
