### ISSUE TITLE
ActiveRecord::Store I can't search in the db

### ISSUE THREAD

**Issue by leoluchini** [rails/rails#53332]
### Steps to reproduce

```ruby
class CreateExclusions < ActiveRecord::Migration[7.2]
  def change
    create_table :exclusions do |t|
      t.jsonb :device
      
      t.timestamps
    end
  end
end


```

Using `store` from `ActiveRecod::Store`

```ruby
class Exclusion < ApplicationRecord
  store :device, accessors: %i(brand brand_model), coder: JSON
end

Exclusion.create(brand: 'AAA')

Exclusion.where("device ->> 'brand' = 'AAA'")
=> []
```
When I checked the database I found the data is stored in this way

```
 id |         device         |         created_at         |         updated_at         
----+------------------------+----------+------------------+---------------------------
 12 | "{\"brand\":\"AAAS\"}" | 2024-10-16 09:42:41.739296 | 2024-10-16 09:42:41.739296
```
When I remove all the logic from `ActiveRecod::Store`

```ruby
class Exclusion < ApplicationRecord
end

Exclusion.create(device: {brand: 'BBB'})

> Exclusion.where("device ->> 'brand' = 'BBB'")
=> [#<Exclusion:0x0000000151f5f558 id: 13, device: {"brand"=>"BBB"}>]

```
The current status in the database is

```
 id |         device         |         created_at         |         updated_at         
----+------------------------+----------+------------------+----------------------------
 12 | "{\"brand\":\"AAAS\"}" | 2024-10-16 09:42:41.739296 | 2024-10-16 09:42:41.739296
 13 | {"brand": "BBB"}       | 2024-10-16 10:54:01.420978 | 2024-10-16 10:54:01.420978
(2 rows)
```

### Expected behavior
be able to perform searches with the information stored through `ActiveRecord::Store`

### Actual behavior
does not return results

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.3.5

**Comment by cubasepp** [comment]
https://api.rubyonrails.org/v7.2/classes/ActiveRecord/Store.html

> NOTE: If you are using structured database data types (e.g. PostgreSQL hstore/json, or MySQL 5.7+ json) there is no need for the serialization provided by [.store](https://api.rubyonrails.org/v7.2/classes/ActiveRecord/Store/ClassMethods.html#method-i-store). Simply use [.store_accessor](https://api.rubyonrails.org/v7.2/classes/ActiveRecord/Store/ClassMethods.html#method-i-store_accessor) instead to generate the accessor methods. Be aware that these columns use a string keyed hash and do not allow access using a symbol.

**Comment by leoluchini** [comment]
Thank you for your comment and your time, It was my fault for not understanding this part correctly.
