### ISSUE TITLE
Rails 8: db:prepare re-run seeds when SolidCache is added

### ISSUE THREAD

**Issue by MaxLap** [rails/rails#53348]
When running `rails db:prepare`, if a DB is created, then the seeds will be run.

This is a problem when the DB being created is for something such as SolidCache (and likely SolidQueue, but I don't use that). A production environment that is functionnal can end up having its seed run again, which can cause all kind of issues, just because SolidCache was added.

If things are configured right, then re-running the whole thing will then work, because then no DB will be created so the seed will not be run... If things are not configured right, then the now existing DB might not contain a schema_migrations table, which means the seed will be run again.

This later case happens to me right now because of this issue: https://github.com/rails/solid_cache/issues/228. But if I change my schema config temporarily, I confirmed that it worked the 2nd time I ran `rails db:prepare`.

I believe the problem comes from https://github.com/rails/rails/blame/main/activerecord/lib/active_record/tasks/database_tasks.rb#L183, since any database being initialized means running the seed, which is likely not desired.

**Rails version**: 8.0.0.beta1
**Ruby version**: 3.3.5
**SolidCache version**: 1.0.6

The same problem would likely happen with SolidQueue and SolidCable too.

**Comment by morgoth** [comment]
Yes, I had the same issue. When added a new database configuration and running `bin/rails db:prepare` the database was created and the seeds were run.
I made my seed file idempotent to make it work as desired.

Since it's a bit surprising maybe it is worth to change the behavior to run seeds only when all databases are initialized.

**Comment by MaxLap** [comment]
I would say that the primary database is all that matters. If it already exists, then don't run the seeds.

If someone decides to have a real second database for some custom table, I doubt even this person would expect the seed to run again. And if someone want's code to run at that first partial deploy, they probably expect to have to run it themselves via a rake task or a migration.

**Comment by MaxLap** [comment]
I just realized, this problem would also happen anytime you move one of the SolidCache, SolidQueue, SolidCable to a new database / server (unless to restore a backup, which I doubt you would for these).

**Comment by flavorjones** [comment]
I can imagine adding a method to `AR::DatabaseConfigurations::DatabaseConfig` and subclases (like `HashConfig`) that's something like:

```ruby
def seeded?
  configuration_hash.fetch(:seeded, true)
end
```

and then the "system" tables for solid {cache,queue,cable} could have a database config like:

```yaml
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
    seeded: false
```

I'm curious if anyone from the core team has thought about differentiating like this between app database and framework databases already.

**Comment by flavorjones** [comment]
See proposal at https://github.com/rails/rails/pull/53354

**Comment by flavorjones** [comment]
@zzak pointed out that https://github.com/rails/rails/issues/53059 has a similar root cause, which I'll try framing as "Rails thinks this database is managed by the app, but it's not."

I'm going to retry a variation on #53354 that addresses both issues.

**Comment by flavorjones** [comment]
Actually, I think #53509 is similar but not the same, and has to do with management of the schema as opposed to management of data content. In this issue, Solid Cache still uses Rails to manage the schema (just doesn't use/need seeds). In #53509 management of both is external to Rails.
