### ISSUE TITLE
How to override/modify rails built-in migration generator?

### ISSUE THREAD

**Issue by Grubba27** [rails/rails#53356]
### background
In our Rails app, we have a folder called `plugins` where we can have Rails-like apps related to our main Rails app. 

Those include migration, jobs, models, etc.

One of the pieces that are not very well glued together is the migration generation story–Currently, we need to generate via `rails g migration_name` a migration file and then move it to the `plugins/<plugin-name>/db/migrate` folder.

I've read the [rails generator guide](https://guides.rubyonrails.org/generators.html#generator-command-line-options) and ended up creating this `.rb` generator:

<details>

<summary>
   
`/lib/generators/rails/plugin_migration_generator.rb`

</summary>

```rb
# frozen_string_literal: true

require "rails/generators/active_record/migration/migration_generator"

class Rails::PluginMigrationGenerator < ActiveRecord::Generators::MigrationGenerator
  class_option :plugin_name,
               type: :string,
               banner: "plugin_name",
               desc: "The plugin name to generate the migration into.",
               required: true

  source_root "#{Gem.loaded_specs["activerecord"].full_gem_path}/lib/rails/generators/active_record/migration/templates"

  private

  def db_migrate_path
    "plugins/#{options["plugin_name"]}/db/migrate"
  end
end

```

</details>

And it works fine for the most part.

<details>
<summary>
Working pictures
</summary>

`--help` command:

<img width="899" alt="Screenshot 2024-10-17 at 17 43 35" src="https://github.com/user-attachments/assets/bd8a2bc1-5eb2-4100-a6c0-2c8a93dca9d3">

running `rails g plugin_migration some_migration2 --plugin-name discourse-chat-integration`:

<img width="1209" alt="Screenshot 2024-10-17 at 17 45 23" src="https://github.com/user-attachments/assets/36c19a57-c14e-4242-b6fb-83f1b3cf4f39">

</details>

Then I read the [overriding rails generators part](https://guides.rubyonrails.org/generators.html#overriding-rails-generators). The docs mention that you can override/configure the built-in rails generators. 

This leads to my question: **How to override/modify rails built-in migration generator?**

> A similar question was asked before in the [forum](https://discuss.rubyonrails.org/t/how-to-override-rails-generate-migration-template/79230). What I'm looking for is more to extend the options of the generator rather than override completely

### Steps to reproduce
> in Linux/MacOs
```sh
rails new app 
cd app
mkdir -p lib/generators/rails  
touch lib/generators/rails/migration_generator.rb && curl https://gist.githubusercontent.com/Grubba27/1f764790df4ed7a039c47061890ab063/raw/1dbfff909cd4a621d48d04b4e77b1ddf8c352e4f/migration_generator.rb >> lib/generators/rails/migration_generator.rb
touch lib/generators/rails/plugin_migration_generator.rb && curl https://gist.githubusercontent.com/Grubba27/1f764790df4ed7a039c47061890ab063/raw/1dbfff909cd4a621d48d04b4e77b1ddf8c352e4f/plugin_migration_generator.rb >> lib/generators/rails/plugin_migration_generator.rb
```
These are the two files from the gists:

<details>

<summary>

[plugin_migration_generator.rb](https://gist.githubusercontent.com/Grubba27/1f764790df4ed7a039c47061890ab063/raw/1dbfff909cd4a621d48d04b4e77b1ddf8c352e4f/plugin_migration_generator.rb)

</summary>

```rb
# frozen_string_literal: true

require "rails/generators/active_record/migration/migration_generator"

class Rails::PluginMigrationGenerator < ActiveRecord::Generators::MigrationGenerator
  class_option :plugin_name,
               type: :string,
               banner: "plugin_name",
               desc: "The plugin name to generate the migration into.",
               required: true

  source_root "#{Gem.loaded_specs["activerecord"].full_gem_path}/lib/rails/generators/active_record/migration/templates"

  private

  def db_migrate_path
    if options["plugin_name"]
      "plugins/#{options["plugin_name"]}/db/migrate"
    else
      "db/migrate"
    end
  end
end
```

</details>

<details>

<summary>

[migration_generator.rb](https://gist.githubusercontent.com/Grubba27/1f764790df4ed7a039c47061890ab063/raw/1dbfff909cd4a621d48d04b4e77b1ddf8c352e4f/migration_generator.rb)

</summary>

```rb
# frozen_string_literal: true

require "rails/generators/active_record/migration/migration_generator"

class Rails::MigrationGenerator < ActiveRecord::Generators::MigrationGenerator
  class_option :plugin_name,
               type: :string,
               banner: "plugin_name",
               desc: "The plugin name to generate the migration into."

  source_root "#{Gem.loaded_specs["activerecord"].full_gem_path}/lib/rails/generators/active_record/migration/templates"

  private

  def db_migrate_path
    if options["plugin_name"]
      "plugins/#{options["plugin_name"]}/db/migrate"
    else
      "db/migrate"
    end
  end
end
```

</details>

### Expected behavior
running the following command
```sh
rails g migration foo2 --plugin-name testing
# creates plugins/testing/db/migrate/20241017210353_foo.rb
```

### Actual behavior

```sh
rails g migration foo --plugin-name testing
# creates db/migrate/20241017210413_foo.rb
```

### System configuration
**Rails version**:

```sh
Rails 7.1.4.1
```

**Ruby version**:

```sh
ruby 3.2.2 
```

**Comment by flavorjones** [comment]
Hi @Grubba27,

Thanks for asking this question. However, we reserve the Rails Issues tracker for bugs in the framework because we don't have the bandwidth to offer application support.

Please use stackoverflow or the [Rails forum](https://discuss.rubyonrails.org/) for help. Thanks for understanding! ♥
