### ISSUE TITLE
Dockerfile.tt: Why  copy single files before copying all files?

### ISSUE THREAD

**Issue by fidalgo** [rails/rails#53378]
In the Dockerfile.tt (railties/lib/rails/generators/rails/app/templates/Dockerfile.tt) file we have several instructions where we copy some files:

```

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git<% if depend_on_bootsnap? -%> && \
    bundle exec bootsnap precompile --gemfile<% end %>

<% if using_node? -%>
# Install node modules
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

<% end -%>
<% if using_bun? -%>
# Install node modules
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

<% end -%>
# Copy application code
COPY . .
```

So we are copying single files, and then we issue another command to copy all the files. Why don't first copy all the files with `COPY . .` and then run `bundle`, `yarn` or `bun`?

At the moment,  this is failing in my setup, as I do use `.tool-versions` for setting the ruby and nodejs versions. As this file is not copied while the `Gemfile` and `Gemfile.lock` are copied, this will make the step to fail.

Let me know if there's any reason to keep it like this, or we could simplify it, and I'll be glad to open a PR.

**Comment by Earlopain** [comment]
These files are copied individually with the assumption that they will change less frequently that application code. This allows docker to cache bundler and yarn package installs.

See https://github.com/rails/rails/pull/53369 were copying `.ruby-version` was rejected. You should instead modify your template if you need something like that to work.

**Comment by fidalgo** [comment]
Thanks for pointing out @Earlopain I understand the argument, but that was not the thing I was optimizing for, when going through a newly generated file, but I understand the reasoning.
Will close this issue, as this has been explained by the core team.
