### ISSUE TITLE
Rails hangs when showing highlighted source of an exception from an erb file in development mode

### ISSUE THREAD

**Issue by Masa331** [rails/rails#53388]
### Steps to reproduce

I created a sample app for reproduction of this problem [here](https://github.com/Masa331/repro). To reproduce it clone the repo, run the application in development mode and try to visit the app in a browser. Or create your own fresh Rails app with `rails new test_app` and apply the same changes as in the reproduction commit [here](https://github.com/Masa331/repro/commit/fe811345b1c13fbd0d4547a746a4b4c0c4482151).

The problematic part is the ERB template:
```erb
<div id='<%= non_existing_method %>'>
```

### Expected behavior
Rails should show the classical error page reporting "undefined local variable or method `non_existing_method'"

### Actual behavior
The application hangs indefinitely without showing the error page. I traced the problem to [here](https://github.com/rails/rails/blob/eb7cd90230ff960940459811c2acacfe75a6daed/actionview/lib/action_view/template/handlers/erb.rb#L118) where it gets stuck in a never ending loop trying to match a string `<div id='` against a string `@virtual_path = "application/index";;@output_buffer.safe_append='<!-- BEGIN app/views/application/index.html.erb -->'; @output_buffer.safe_append='<div id=\''.freeze; @output_buffer.append=( foobar ); @output_buffer.safe_append='\'>`. In the second string there is a slash before the single quote and so no match is ever made.

This problem doesn't occur when the quotes in the ERB template are changed from single quotes to double quotes.

### System configuration
**Rails version**: 7.2.1.1

**Ruby version**: 3.2.4

**Comment by byroot** [comment]
Seems similar to https://github.com/rails/rails/pull/53243 / https://github.com/rails/rails/issues/53221 / https://github.com/rails/rails/pull/52978 but for Rails 7.2.

cc @jhawthorn
