### ISSUE TITLE
`field_with_errors` default behavior causes styling issues and lacks easy customization

### ISSUE THREAD

**Issue by adnjoo** [rails/rails#53390]
### Steps to reproduce

1. Generate a new Rails app.
2. Create a form with `form_with` for a model (e.g., Note).
3. Add validations to the model, such as `validates :title`, `presence: true`.
4. Submit the form with an invalid (blank) title field.

```ruby
# Run this script to reproduce the issue
rails new form_with_error_test
cd form_with_error_test
rails g model Note title:string content:text
rails db:migrate

# In app/models/note.rb
class Note < ApplicationRecord
  validates :title, presence: true
end

# In app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to @note
    else
      render :new
    end
  end

  private

  def note_params
    params.require(:note).permit(:title, :content)
  end
end

# In app/views/notes/new.html.erb
<%= form_with model: @note, local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.submit %>
<% end %>

# Start the Rails server and visit /notes/new, submit a form without a title, and observe the behavior.

```

### Expected behavior

When a form field has validation errors, Rails should render the field with error styles or messages, or in a way that can be customized (e.g., using `field_with_errors` wrapper or a custom method).

### Actual behavior

The form field with errors is wrapped with a `div.field_with_errors`, which can cause styling issues. The default behavior doesn't allow easy customization of how the error messages are displayed, and disabling this behavior with `field_error_proc` still requires additional steps to handle errors correctly in forms.

#### Screenshots

overwrites existing html

before:
<img width="300" alt="Screenshot 2024-10-20 at 8 24 11 AM" src="https://github.com/user-attachments/assets/b2628ffe-f792-4160-9162-f9be5380f16f">
after:
<img width="300" alt="Screenshot 2024-10-20 at 8 24 21 AM" src="https://github.com/user-attachments/assets/bc8c0fc8-1783-41b6-8f86-ea6158381f4a">

#### References

I did manage to fix the behavior by adding an e.g. [field_with_errors initializer](https://railsdesigner.com/disable-field-with-errors/).

### System configuration
**Rails version**:
Rails version: 7.2.1.1

**Ruby version**:
Ruby version: 3.3.4

**Comment by adnjoo** [comment]
> ### Steps to reproduce
> 1. Generate a new Rails app.
> 2. Create a form with `form_with` for a model (e.g., Note).
> 3. Add validations to the model, such as `validates :title`, `presence: true`.
> 4. Submit the form with an invalid (blank) title field.
> 
> ```ruby
> # Run this script to reproduce the issue
> rails new form_with_error_test
> cd form_with_error_test
> rails g model Note title:string content:text
> rails db:migrate
> 
> # In app/models/note.rb
> class Note < ApplicationRecord
>   validates :title, presence: true
> end
> 
> # In app/controllers/notes_controller.rb
> class NotesController < ApplicationController
>   def new
>     @note = Note.new
>   end
> 
>   def create
>     @note = Note.new(note_params)
>     if @note.save
>       redirect_to @note
>     else
>       render :new
>     end
>   end
> 
>   private
> 
>   def note_params
>     params.require(:note).permit(:title, :content)
>   end
> end
> 
> # In app/views/notes/new.html.erb
> <%= form_with model: @note, local: true do |form| %>
>   <%= form.label :title %>
>   <%= form.text_field :title %>
>   <%= form.submit %>
> <% end %>
> 
> # Start the Rails server and visit /notes/new, submit a form without a title, and observe the behavior.
> ```
> 
> ### Expected behavior
> When a form field has validation errors, Rails should render the field with error styles or messages, or in a way that can be customized (e.g., using field_with_errors wrapper or a custom method).
> 
> ### Actual behavior
> The form field with errors is wrapped with a `div.field_with_errors`, which can cause styling issues. The default behavior doesn't allow easy customization of how the error messages are displayed, and disabling this behavior with `field_error_proc` still requires additional steps to handle errors correctly in forms.
> 
> #### Screenshots
> Overwrites existing html
> 
> before: <img alt="Screenshot 2024-10-20 at 8 24 11 AM" width="300" src="https://private-user-images.githubusercontent.com/22807629/378196489-b2628ffe-f792-4160-9162-f9be5380f16f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzQ3OTUsIm5iZiI6MTcyOTQzNDQ5NSwicGF0aCI6Ii8yMjgwNzYyOS8zNzgxOTY0ODktYjI2MjhmZmUtZjc5Mi00MTYwLTkxNjItZjliZTUzODBmMTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE0MjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0Y2ZjNTE3MTlkOTcyYTE1NjhhZTFjYzllZGIzMTllMjVhMzAzMDg1ZDljOWM1MTJiZTZjNTI3YjdjNjNlYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8s2CwEW0gXeQohu8oveshAAjvpWTNqt9WZDe0eUjVNM"> after: <img alt="Screenshot 2024-10-20 at 8 24 21 AM" width="300" src="https://private-user-images.githubusercontent.com/22807629/378196493-bc8c0fc8-1783-41b6-8f86-ea6158381f4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzQ3OTUsIm5iZiI6MTcyOTQzNDQ5NSwicGF0aCI6Ii8yMjgwNzYyOS8zNzgxOTY0OTMtYmM4YzBmYzgtMTc4My00MWI2LThmODYtZWE2MTU4MzgxZjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE0MjgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYzJjMGMyNGFlMWI0NjdmYmRkYzcyYTdjYmNkMGQ3NWQ0NWNhYTRkMjgzNGY5ODY5MDRjZjMwNjM3ODRiMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.25u2yljS_cJd8Z4PPDnnTRaisss_UqEjf4vJS1J-3AM">
> 
> #### References
> I did manage to fix the behavior by adding an e.g. [field_with_errors initializer](https://railsdesigner.com/disable-field-with-errors/).
> 
> ### System configuration
> **Rails version**: Rails version: 7.2.1.1
> 
> **Ruby version**: Ruby version: 3.3.4

**Comment by skipkayhil** [comment]
Thank you for opening an issue, but this is more of a feature request than a bug. Feature discussions should be done on [the forums](https://discuss.rubyonrails.org/) because we reserve issues for bugs in the framework
