### ISSUE TITLE
add_index for a composite index with array and expression raises an exception

### ISSUE THREAD

**Issue by filipegiusti** [rails/rails#53406]
### Steps to reproduce

`add_index :profiles, [:organization_id, 'lower(email)']` fails with `ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "lower(email)" does not exist`.

I'm not sure this is supported but it's at least unexpected given `add_index :profiles, 'lower(email)'` works.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  gem "pg"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "postgresql", database: "test")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :profiles, force: true do |t|
    t.integer :organization_id, null: false
    t.text :email, null: false
  end
end

class Profile < ActiveRecord::Base
end

class AddIndex < ActiveRecord::Migration::Current
  def change
    add_index :profiles, [:organization_id, 'lower(email)']
  end
end

class BugTest < ActiveSupport::TestCase
  def test_migration_up
    assert_nothing_raised do
      AddIndex.migrate(:up)
    end
  end
end                            
```

### Expected behavior

It creates a composite index using a column and an expression.

### Actual behavior

An exception is raised.

### System configuration
**Rails version**: 7.2.1.1
**Ruby version**: 3.3.1

**Comment by JoshAntBrown** [comment]
It would seem it doesn't check for expressions when you pass an array? In the meantime you can create a composite index by making the entire line an expression. The following would work in the original example:

```ruby
class AddIndex < ActiveRecord::Migration::Current
  def change
    add_index :profiles, '"organization_id", lower(email)'
  end
end```

**Comment by filipegiusti** [comment]
Yes @JoshAntBrown, that seems to be the case. Thank you for the alternative way, that works perfectly.

**Comment by fatkodima** [comment]
Closing as this is expected - for expression indexes the suggested approach should be used.
