### ISSUE TITLE
with rails8 / master rails new --master|main  app fails trying to write to incorrect path

### ISSUE THREAD

**Issue by danmack** [rails/rails#53405]
### Steps to reproduce

On fresh unix system, I am on Alpine Linux.   Normal user, try to create a new rails app using --master or --main.
````
rails1% rails new --main app
      create
      create  Gemfile
         run  bundle install --quiet
There was an error while trying to write to `/home/username/.local/share/gem/ruby/3.3.0`. It is likely that you need to grant write
permissions for that path.
         run  bundle exec rails new /home/urails/app --main
The git source https://github.com/rails/rails.git is not yet checked out. Please run `bundle install` before trying to start your application
rails1:~$ echo $HOME
/home/urails
````

The rails command/bundle appear to actually be using the path /home/username/... because if I create a symlink in /home of "username" pointing to my home directory, the command succeeds correctly, e.g.:

````
rails1:/home# ls -altr
total 12
drwxr-xr-x 22 root   root   4096 Aug 15 11:28 ..
drwxr-xr-x  3 root   root   4096 Oct 21 15:43 .
drwxr-sr-x 10 urails urails 4096 Oct 21 15:44 urails
rails1:/home# ln -s urails username
rails1:/home# ls -l
total 4
drwxr-sr-x 10 urails urails 4096 Oct 21 15:44 urails
lrwxrwxrwx  1 root   root      6 Oct 21 15:50 username -> urails
````

Now the rails new command works.

Thank you,

### Expected behavior

Command completion without errors

### Actual behavior

````
      create
      create  Gemfile
         run  bundle install --quiet
There was an error while trying to write to `/home/username/.local/share/gem/ruby/3.3.0`. It is likely that you need to grant write
permissions for that path.
         run  bundle exec rails new /home/urails/sw/gr8 --master
The git source https://github.com/rails/rails.git is not yet checked out. Please run `bundle install` before trying to start your application
````

### System configuration
**Rails version**:

main/master branch

**Ruby version**:

3.3.3

**Comment by inkyvoxel** [comment]
I don't think this is related to Rails. It seems related to your Ruby install and user permissions.

The `rails new` command is also running `bundle install`, and it is `bundle install` that is giving the permission error.

`bundle install` is trying to install the gems specified in Rails' default Gemfile. These gems are not installed inside your new app's folder (e.g. `/home/urails/app`), but rather in the `GEM_HOME` location (e.g. `/home/username/.local/share/gem/ruby/3.3.0`). It looks like your current user doesn't have permission to write to that folder.
