### ISSUE TITLE
TailwindCSS Not Properly Setup on New Rails App

### ISSUE THREAD

**Issue by scottwater** [rails/rails#53419]
Using Rails 8 RC1 - `rails new r8rc1 --js esbuild --css tailwind` 

This creates a tailwind.config.js file in the root directory with just the modules.export content object (no themes or plugins enabled in the config file). This also creates the tailwind.application.css file with the three @tailwind directives. 

The tailwindcss file is not included in the layout/application file.

I expected to have the same generate behavior as using `bin/bundle add tailwindcss-rails`

This includes the theme (really just font) and the default tailwind plugins in the tailwind.config.js file in the /config directory. I also expected it to update the layout/application file to include stylesheet_link_tag. 

### System configuration
**Rails version** 8 RC1

**Ruby version**: 3.5.5

**Comment by vinibispo** [comment]
@scottwater I was able to reproduce the issue

**Comment by flavorjones** [comment]
Please see existing https://github.com/rails/tailwindcss-rails/discussions/237
