### ISSUE TITLE
Rails.error methods doing nothing in test/dev is dangerous

### ISSUE THREAD

**Issue by nhorton** [rails/rails#53421]
### Steps to reproduce
Currently, if I have code like the following in my codebase in a default Rails deployment, I won't see any issues until I go to production:
```ruby
Rails.error.handle do
  MyModel.find(bad_id)
end
```
This is because there are no report subscribers by default.

### Expected behavior
The above code should fail in a test unless the test wraps it in `assert_error_reported`.

### Actual behavior
Tests pass without issue.

### Proposal
I have 2 core proposals
1. Add a error subscriber that logs the error by default in all environments. Do it with an explicit subscribe call in each env file (so folks who do not want it can easily remove it). Simple example of what I use:
```ruby
class ErrorLoggingSubscriber
  def report(error, handled:, severity:, context:, source: nil)
    message = "#{error.class}: #{error.message}"
    backtrace = backtrace_string(error.backtrace)

    severity = :warn if severity == :warning
    severity = Logger::Severity.coerce(severity)
    Rails.logger.add(severity, message, **context, handled:, backtrace:)
  end

  private

  def backtrace_string(backtrace)
    return 'No Backtrace' unless backtrace

    Rails.backtrace_cleaner.clean(backtrace).join("\n")
  end
end

# Subscribe the custom error reporter
Rails.error.subscribe(ErrorLoggingSubscriber.new)
```

2. Add another subscriber that registers itself in `test.rb` that raises the errors passed to it. That subscriber could skip raising based on a thread variable or such that `assert_error_reported` sets.

**Comment by nhorton** [comment]
Note that I would be up for putting in the PR for this, but I want to make sure this is consistent with something Rails Core wants before doing so.

**Comment by byroot** [comment]
> 1. Add a error subscriber that logs the error by default in all environments.

Sounds fair. Not sure about the exact implementation though, there's an effort to try to keep `environment/*.rb` and `config/initializers` tight. So perhaps it should just be an internal initializer with a `config.something = false` to not do it.

> 2. Add another subscriber that registers itself in test.rb that raises the errors passed to it. That subscriber could skip raising based on a thread variable or such that assert_error_reported sets.

Here I disagree. Your test is supposed to test that the behavior you expected happened, whether it had to handle exceptions for that or not is orthogonal. I think it's easy enough to implement that behavior yourself if that's what you want.

**Comment by byroot** [comment]
> If `unexpected` was more-ergonomic, I could get most of the code switched to that and all needs would be solved.

Sounds interesting, best if you open a PR so we can discuss it.

If that's OK with you I'll close this issue and wait for your PR, since we don't normally take feature requests on the issue tracker.
