### ISSUE TITLE
Increased CPU usage with Rails 8.0.0.beta1

### ISSUE THREAD

**Issue by pglombardo** [rails/rails#53420]
### Steps to reproduce

Deploy Rails 8.0.0.beta1 to production with a proper Solid Queue/Cache/Cable setup and seeing increased CPU utilization.

### Expected behavior

Ideal would be to not add to CPU utilization.

### Actual behavior

There are no no framework errors.  The site is running normally but I see an increased CPU utilization after deploy:

<img width="989" alt="Screenshot 2024-10-17 at 00 05 40" src="https://github.com/user-attachments/assets/fca62c5f-0bbd-40f3-a566-7b4f12103005">

I haven't had a chance to investigate or profile the cpu utilization.  I'll be updating to rc1 soon.

### System configuration
**Rails version**:
Rails 8.0.0.beta1

**Ruby version**:
Ruby 3.3.5

**Comment by skipkayhil** [comment]
Can you be really specific about what changed at the point you show in the graph?

For example, what Rails/Ruby versions were running before? Did you change any configuration? You mention Solid* gems, were they running the same before? Is the increase in server processes or active job processes?

**Comment by pglombardo** [comment]
That deploy was an upgrade from Rails 7.2.2 to Rails 8.0.0.beta1.  

The 3 CPU spikes was me deploying with the new Solid_Cache/Cable/Queue and working out DB connectivity (`db:prepare` doesn't run if DB already exists so no schema was loaded).

Solid_Cache/Cable are running with dedicated databases.  Solid_queue is running in the primary database.

I'm up to Rails 8.0.0 now and there is still increased CPU usage but it's not a critical issue for me hence the lack of investigation and details (apologies).

Also, this CPU utilization seems to be baseline regardless of traffic as it's also happening on my staging server.

<img width="1322" alt="Screenshot 2024-11-10 at 12 01 39" src="https://github.com/user-attachments/assets/4fc53cb9-a242-4ab5-9949-3ed3e2856068">

If needed, feel free to close this issue because of a lack of details but once I get a chance to properly investigate with profiler I'll post back here for the community.

**Comment by zzak** [comment]
Please do investigate and let us know.
