### ISSUE TITLE
Rails 6.1 guides and api docs redirect to edge

### ISSUE THREAD

**Issue by vadviktor** [rails/rails#53434]
### Steps to reproduce

Visiting the v6.1 api doc URL https://api.rubyonrails.org/v6.1/ redirects to https://edgeapi.rubyonrails.org/.

The same redirection happens when visiting the v6.1 guides from any source: https://guides.rubyonrails.org/v6.1/ redirects to https://edgeguides.rubyonrails.org/.

### Expected behavior

Each URL responds with the correct version of the documentation behind them.

### Actual behavior

They are redirected to the latest, edge version of the documentations.

### Note

It does not happen to v6.0.

**Comment by rafaelfranca** [comment]
Should be fixed now. Thanks
