### ISSUE TITLE
Rails IRB Console Is Not Working (Cannot Type Anything in the Console)

### ISSUE THREAD

**Issue by SanthoshRam-98** [rails/rails#53455]
**Title**: Cannot Type in Rails IRB Console on Windows 11 (Rails 7.1.4.2)

**Environment**:
- Ruby version: 3.1.3
- Rails version: 7.1.4.2
- Operating system: Windows 11

**Description**:
When I run `rails console`, I cannot type anything in the console. The prompt appears, but it does not accept any input. This issue persists in both PowerShell and Command Prompt.

**Steps to Reproduce**:
1. Open PowerShell/Command Prompt.
2. Navigate to my Rails application directory.
3. Run `rails console`.

![image](https://github.com/user-attachments/assets/1ca50da3-2fe5-44db-b7e4-548319bbaefc)

**What I Have Tried**:
- Uninstalled and reinstalled Rails,Bootsnap.
- Updated the Gemfile and ran bundle install.
- Tried launching the console in different shells (PowerShell, CMD).
- Attempted a regular IRB session outside of Rails.
- Removed Gemfile.lock file and reinstalled.
- Deleted libvips for image processing to address console warnings.

**Expected Behavior**:
I expect to see a prompt where I can type Ruby commands.

**Actual Behavior**:
I am unable to type anything in the console.

**Comment by inkyvoxel** [comment]
Hi @SanthoshRam-98, were you able to type into a regular `irb` session?

**Comment by SanthoshRam-98** [comment]
Hi @inkyvoxel, thanks for the reply! The issue was that I had added config/initializers/firebaseConfig.rb for Firebase configuration in my Rails application, but since it wasn't used anywhere, it caused an error. I deleted the file, and now the issue is resolved—I can type in the Rails console again.

**Comment by inkyvoxel** [comment]
Great! Nice work figuring it out. Consider closing the issue if the problem was unrelated to Rails.
