### ISSUE TITLE
`./bin/thrust` eats `$PORT`

### ISSUE THREAD

**Issue by dentarg** [rails/rails#53462]
### Steps to reproduce

Expected the value of `$PORT` to be used when starting Puma

```shell
$ PORT=31337 ./bin/thrust ./bin/rails server
{"time":"2024-10-27T19:00:48.653131+01:00","level":"INFO","msg":"Server started","http":":80"}
=> Booting Puma
=> Rails 8.0.0.rc1 application starting in development
=> Run `bin/rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 6.4.3 (ruby 3.3.5-p100) ("The Eagle of Durango")
*  Min threads: 3
*  Max threads: 3
*  Environment: development
*          PID: 93282
* Listening on http://127.0.0.1:3000
* Listening on http://[::1]:3000
Use Ctrl-C to stop
```

`./bin/thrust ./bin/rails server` is how the default Dockerfile is started:

https://github.com/rails/rails/blob/e6429269fd5a8a7d728557f4e7d7f82c0ad1478c/railties/lib/rails/generators/rails/app/templates/Dockerfile.tt#L118

### Expected behavior

Puma is listening on port 31337

### Actual behavior

Puma is listening on port 3000 (the default port)

### System configuration
**Rails version**: 8.0.0.rc1

**Ruby version**: 3.3.5

**Comment by dentarg** [comment]
So thruster understands `TARGET_PORT` and will set `PORT` to that value. Should the Dockerfile use that somehow? 🤔

**Comment by byroot** [comment]
Could you open this at https://github.com/basecamp/thruster please?

Thruster is just a gem that's in the default Gemfile from Rails point of view
