### ISSUE TITLE
.count returns empty hash when called on empty ActiveRecord::AssociationRelation and chained with .group

### ISSUE THREAD

**Issue by marelons1337** [rails/rails#53489]
### Steps to reproduce
Call `.count` on empty `ActiveRecord::AssociationRelation` when combined with `group` returns empty hash. However if the same `ActiveRecord::AssociationRelation` is queried with for example `where` it correctly returns 0.

https://api.rubyonrails.org/v7.2.1.2/classes/ActiveRecord/QueryMethods.html#method-i-group
I found this mention in guides that it _Returns an array with distinct records based on the group attribute_
However this doesn't seem to be the case as it returns `ActiveRecord::AssociationRelation`, not an `Array`
If above was true then I would assume we would receive an empty array which in fact would return 0 when combined with `count`.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "7.2.1"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :comments, force: true do |t|
    t.integer :post_id
  end
end

class Post < ActiveRecord::Base
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end

class BugTest < ActiveSupport::TestCase
  def test_relation_count
    post = Post.create!
    assert_equal 0, post.comments.count
    assert_equal "ActiveRecord::Associations::CollectionProxy", post.comments.class.name

    assert_equal({}, post.comments.group(:id).count)
    assert_equal "ActiveRecord::AssociationRelation", post.comments.group(:id).class.name

    assert_equal 0, post.comments.where(post_id: post.id).count
    assert_equal "ActiveRecord::AssociationRelation", post.comments.where(post_id: 1).class.name
  end
end
```

### Expected behavior
Either 
1. `group` should correctly return an Array 
2. or `...group(:id).count` should return 0 instead of empty hash when called on an empty `ActiveRecord::AssociationRelation`

### Actual behavior
Calling `.count` on empty `ActiveRecord::AssociationRelation` when combined with `group` returns empty hash.

### System configuration
**Rails version**: 7.2.1

**Ruby version**: 3.2.2

Am I missing something here, is it my misunderstanding of how `group` works or is it really an issue? I'm happy to work on that if the latter is the case.

**Comment by JoeDupuis** [comment]
This is expected. Count on group returns a hash of where the key is the group fields and the value is the count:

```ruby
Post.create type: :blog
Post.create type: :blog
Post.create type: :article

Post.group(:type).count #=> {blog: 2, article: 1} 
```

**Comment by fatkodima** [comment]
See https://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-count

> If [count](https://api.rubyonrails.org/Calculations.html#method-i-count) is used with [Relation#group](https://api.rubyonrails.org/QueryMethods.html#method-i-group), it returns a [Hash](https://api.rubyonrails.org/Hash.html) whose keys represent the aggregated column, and the values are the respective amounts:

Since the relation is empty, so is the returned hash.
