### ISSUE TITLE
Upgrading rc1 to rc2 removes foreman (thus css dev build task) on app:upgrade for tailwind app

### ISSUE THREAD

**Issue by robshep** [rails/rails#53496]
### Steps to reproduce
* Generate an 8.0.0.rc1 app with `--css=tailwind`
* update to 8.0.0.rc2 and `rails app:update`

The incoming change to `bin/dev` removes foreman build suport and reverts to just `rails server` 

### Steps to reproduce
```bash

rails _8.0.0.rc1_ new rc1 --css=tailwind
sed -i .bak -e 's|8.0.0.rc1|8.0.0.rc2|' Gemfile
bundle update
rails app:update
```

### Expected behavior

foreman css build support retained for apps generated with css build requirements

### Actual behavior

Foreman build support removed.

I appreciate here that this is an overriding file coming from an update process that should be reviewed. 
But for newcomers who don't appreciate whats happening this is destructive and I would of thought a developer experience bug. 

### System configuration
**Rails version**: 8.0.0.rc1 to 8.0.0.rc2

**Ruby version**: 3.3

**Comment by nicalpi** [comment]
I was finding the same thing right now, there's also a chance on the `/bin/setup` that removes the `yarn install` process 

```
-  # Install JavaScript dependencies
-  system("yarn install --check-files")
```

**Comment by rafaelfranca** [comment]
Yes. That is expected behavior. `rails app:update` has no knowledge about tailwind. The update task isn't supposed to know about the entire state of your application. You should always looks that the diff generated and make the decisions that makes sense for your application.
