### ISSUE TITLE
Opening edge guides with an anchor on mobile makes it impossible to scroll

### ISSUE THREAD

**Issue by Earlopain** [rails/rails#53500]
For example on https://edgeguides.rubyonrails.org/configuring.html#config-action-view-field-error-proc it insists on scrolling the chapter guide into view:

https://github.com/user-attachments/assets/230a6fd7-7e32-43e8-8fc1-fb54ee836e26

When the guide is opened without an anchor, there is no problem.

Similarly, clicking on chapter sections results in the same behavior.

**Comment by SleeplessByte** [comment]
@Earlopain yeah this was caused by a late addition in #51499. The issue is indeed with anchor links.

I'll try to fix it right now.

**Comment by SleeplessByte** [comment]
Once the PR preview passes, you can check the fix there.

**Comment by Earlopain** [comment]
This looks good to me, thanks! Works like I would expect it to.
