### ISSUE TITLE
`app:update` prints deprecation warnings during `active_storage:update`

### ISSUE THREAD

**Issue by Earlopain** [rails/rails#53558]
### Steps to reproduce
Have a app on 7.2 with ActiveStore set up, upgrade to 8.0, and run `app:update`

### Expected behavior
No deprecation warnings

### Actual behavior

```
$ bin/rails app:update
...
       rails  active_storage:update
DEPRECATION WARNING: `to_time` will always preserve the full timezone rather than offset of the receiver in Rails 8.1. To opt in to the new behavior, set `config.active_support.to_time_preserves_timezone = :zone`. (called from <top (required)> at /home/user/code/reverser/config/environment.rb:5)
DEPRECATION WARNING: `to_time` will always preserve the full timezone rather than offset of the receiver in Rails 8.1. To opt in to the new behavior, set `config.active_support.to_time_preserves_timezone = :zone`. (called from <top (required)> at /home/user/code/reverser/config/environment.rb:5)
````

`active_storage:update` seems to load the environment, which causes some initializers to run, include the one for assigning `to_time_preserves_timezone`. There is code to silence warnings:
https://github.com/rails/rails/blob/ff770ee5d84eb9a7afa6c36f6d1c306211f32311/railties/lib/rails/generators/actions.rb#L396-L398
so I would say that deprecations are unexpected. However I did not easily find a way to silence deprecations in that block. The deprecators are only available _after/sometime during_ the command. `Rails.logger` is also not yet set up.

**Comment by rodrigoargumedo** [comment]
The only workaround I got around the warning is placing the `config.active_support.to_time_preserves_timezone = :zone` in `application.rb` in the config directory.
