### ISSUE TITLE
[Getting Started] Tutorial suggest modifying migration file and rerun db:migrate but it does not have any effect.

### ISSUE THREAD

**Issue by ml4nC3** [rails/rails#53568]
### Steps to reproduce

Following the Getting started tutorial, on [Using Concerns chapter](https://guides.rubyonrails.org/getting_started.html#using-concerns), the tutorial says :
> To choose the status for the existing articles and comments you can add a default value to the generated migration files by adding the default: "public" option and launch the migrations again.

Well... It does not look correct because migrations have already been run and modifying the files does not take any effect.

I tried modifying the file like so :
```ruby
class AddStatusToArticles < ActiveRecord::Migration[7.2]
  def change
    add_column :articles, :status, :string, default: "public"
  end
end
```
Then run `rails db:migrate`.

The process does not give any feedback. After that the `schema.rb` file is not modified :
```ruby
ActiveRecord::Schema[7.2].define(version: 2024_11_09_093933) do
  create_table "articles", force: :cascade do |t|
    t.string "title"
    t.text "body"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "status"
  end

  create_table "comments", force: :cascade do |t|
    t.string "commenter"
    t.text "body"
    t.integer "article_id", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "status"
    t.index ["article_id"], name: "index_comments_on_article_id"
  end

  add_foreign_key "comments", "articles"
end
```

### Expected behavior

I expected the schema to be modified with the default value "public" as suggested in the tutorial.

### Actual behavior

Creating a new record in the website and checking the data in `rails console` shows `status: nil` in the new record.

Which seems expected because the migration has already been taken care of so Rails does not rerun it (I guess). But then why the tutorial is suggesting to modify migration files ?

Shouldn't it suggest creating a new migration to modify column default value ?

### System configuration
**Rails version**:
```bash
rails --version
Rails 7.2.1.2
```

**Ruby version**:
```bash
ruby --version
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
```

**Comment by hahmed** [comment]
I think that makes sense, feel free to open a PR.

**Comment by zzak** [comment]
Wait, "launch the migrations again"? I would assume that to mean this works if you `db:migrate:redo`, but could probably be clearer. Alternatively, yeah, suggesting a path which does not result in modifying already run migrations would probably lead to less confusion. :thinking:

**Comment by hahmed** [comment]
@zzak yeah, that's what I was thinking if someone was not familiar with rails might not have the context on `db:migrate:redo` but +1 to your suggestion about re-wording/ordering

**Comment by ml4nC3** [comment]
> Wait, "launch the migrations again"? I would assume that to mean this works if you `db:migrate:redo`, but could probably be clearer. Alternatively, yeah, suggesting a path which does not result in modifying already run migrations would probably lead to less confusion. 🤔

Well or we can consider that this is the good excuse to show that we can redo migration with the command `db:migrate:redo`.

But as I was not aware of this option it got me confused indeed.

**Comment by jaredholdcroft** [comment]
I had a go at changing this - https://github.com/rails/rails/pull/53599
