### ISSUE TITLE
update database.yml template

### ISSUE THREAD

**Issue by alec-c4** [rails/rails#53574]
Hi.
I'd like to propose to update https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/templates/config/databases/postgresql.yml.tt and other templates in this directory with following configuration for development section (similar to production section)

```
<%- if options.skip_solid? -%>
development:
  <<: *default
  database: <%= app_name %>_development
<%- else -%>
development:
  primary: &primary_development
    <<: *default
    database: <%= app_name %>_development
    username: <%= app_name %>
    password: <%%= ENV["<%= app_name.upcase %>_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_development
    database: <%= app_name %>_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: <%= app_name %>_development_queue
    migrations_paths: db/queue_migrate
  <%- unless options.skip_action_cable? -%>
  cable:
    <<: *primary_development
    database: <%= app_name %>_development_cable
    migrations_paths: db/cable_migrate
  <%- end -%>
<%- end -%>
```

Firstly, in the `config/queue.yml` settings, the development and production environments have identical configurations, but there’s no configured database for development. Additionally, I believe developers should be able to modify the settings in `config/cable.yml` and `config/cache.yml` to point to existing databases.

What are your thoughts? If you approve, I’ll create a pull request.

UPD: I think I'm not clear enough in description above. My idea is to add ability to check code in prod-like environment, but locally and without any hassle.

**Comment by rubyrider** [comment]
may be worth proposing a pr? wdyt?

**Comment by alec-c4** [comment]
> may be worth proposing a pr? wdyt?

done https://github.com/rails/rails/pull/53584

**Comment by skipkayhil** [comment]
Closing in favor of the PR to centralize discussion (and this isn't really a bug anyways)
