### ISSUE TITLE
`Rails.root.join '/'` returns `#<Pathname:/>`

### ISSUE THREAD

**Issue by corsonknowles** [rails/rails#53578]
### Steps to reproduce

In a Rails console, or anywhere you evaluate code, pass any string argument beginning with '/' to Rails.root.join and it will omit the Rails path

```shell
(dev)> Rails.root.join '/'
=> #<Pathname:/>
(dev)> Rails.root.join '//'
=> #<Pathname://>
(dev)> Rails.root.join '/abc'
=> #<Pathname:/abc>
(dev)> Rails.root.join '/abc/'
=> #<Pathname:/abc/>
```

```ruby
# Your reproduction script goes here
```

### Expected behavior

Rails.root.join '/' should return the rails path with an ending `/`

### Actual behavior
it returns `/`

### System configuration
**Rails version**:
(Rails 7.1.5)
**Ruby version**:
ruby 3.3.5

**Comment by Earlopain** [comment]
`Rails.root` is a `Pathname` and this is just what happens when you use an absolute path with those. You should omit the leading slash to get the behavior that you want. It doesn't matter if the `Pathname` was created with or without a trailing slash, `join` will always consider the argument to be a new entry.

Here is the documentation for this:
https://docs.ruby-lang.org/en/3.3/Pathname.html#method-i-join
From the `#+` method documentation:
> Appends a pathname fragment to `self` to produce a new Pathname object. Since `other` is considered as a path relative to `self`, if `other` is an absolute path, the new Pathname object is created from just `other`.

**Comment by corsonknowles** [comment]
Yes, maybe I'm in the wrong place with this one, but I still kind of think the issue is best solved at the Rails layer. 

[Rails/FilePath](https://www.rubydoc.info/gems/rubocop-rails/2.5.2/RuboCop/Cop/Rails/FilePath) is going to flag on things like `"#{Rails.root} + /"` which is something needed relatively often. We could patch it up there, but maybe Rails should break from the `pathname API` for the purposes of `Rails.root` and always deliver a root path.

**Comment by Earlopain** [comment]
There is an issue for RuboCop at https://github.com/rubocop/rubocop-rails/issues/1177. I don't think Rails should do something about it.

**Comment by zzak** [comment]
It is [documented](https://edgeapi.rubyonrails.org/classes/Rails.html#method-c-root) that `Rails.root` is a Pathname object. So take from that whatever behaviors Pathname provides.
