### ISSUE TITLE
Timeout Issue When Publishing Messages to RabbitMQ Queue in Ruby on Rails Using Bunny Gem

### ISSUE THREAD

**Issue by GuilhermeTrivilin** [rails/rails#53588]
I'm facing a timeout issue when attempting to publish messages to a RabbitMQ queue in my Ruby on Rails application. I'm using the Bunny gem for connection and message publishing. The connection to RabbitMQ is successfully established, but when I try to publish a message, it times out. Interestingly, running the same publishing code directly through Rails Console works perfectly.

Here’s the setup for my connection initializer:

```
# config/initializers/rabbitmq.rb
require 'bunny'

unless Rails.env.test?
  RABBITMQ_CONN = Bunny.new(
    host: ENV['RABBITMQ_HOST'] || 'localhost',
    port: ENV['RABBITMQ_PORT'] || 5672,
    username: ENV['RABBITMQ_USER'] || 'guest',
    password: ENV['RABBITMQ_PASSWORD'] || 'guest'
  )

  RABBITMQ_CONN.start
end
```

And here is the service responsible for publishing messages:

```
# app/service/rabbitmq/point_calculations_publisher.rb
class Rabbitmq::PointCalculationsPublisher
  def self.publish(message)
    channel = RABBITMQ_CONN.create_channel
    queue = channel.queue('point_calculations', durable: true)
    queue.publish(message.to_json, persistent: true)
  ensure
    channel&.close
  end
end
```

Environment Details: Ruby version: 2.5.6 Rails version: 5.2 Bunny gem version: 2.19 Troubleshooting Steps Taken: Verified that the connection works, as I can successfully connect. Tested publishing through Rails Console, which works as expected without timeouts. Additional Context: The timeout occurs only when publishing within the Rails application itself. I suspect it might be related to how the Bunny connection is being handled in production vs. Rails Console.

Any insights or solutions from those who have encountered similar issues would be highly appreciated!

**Comment by zzak** [comment]
We reserve the issue tracker for bugs with the framework, not troubleshooting.

Please use the [forums](https://discuss.rubyonrails.org/) where you're more likely to receive feedback from the community about your issue.

Thanks! :bow:
