### ISSUE TITLE
`class_attribute` setter redefinition discards prepended overrides in subclasses

### ISSUE THREAD

**Issue by zvkemp** [rails/rails#53606]
### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "8.0.0"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"
end

require "active_support"
require "minitest/autorun"

module SetterOverride
  def some_attribute=(value)
    previous_values << some_attribute
    super
  end

  def previous_values
    @previous_values ||= []
  end
end

class TestBase
  class_attribute :some_attribute

  class << self
    prepend(SetterOverride)
  end
end

class TestClass2 < TestBase
end

class BugTest < ActiveSupport::TestCase
  def test_base_and_subclass_assignment
    TestBase.some_attribute = :base_0
    TestBase.some_attribute = :base_1
    TestBase.some_attribute = :base_2

    assert_equal([nil, :base_0, :base_1], TestBase.previous_values)

    assert_equal([], TestClass2.previous_values)
    assert_equal(:base_2, TestClass2.some_attribute)

    TestClass2.some_attribute = :subclass_1
    TestClass2.some_attribute = :subclass_2
    TestClass2.some_attribute = :subclass_3

    assert_equal([:base_2, :subclass_1, :subclass_2], TestClass2.previous_values)
  end
end
```

### Expected behavior

In the above example, `TestClass2` should collect `[:base_2, :subclass_1, :subclass_2]` as `previous_values`

### Actual behavior

It only collects `[:base2]`, then the setter redefines itself without the prepended override. This seems to be caused by `TestClass2` not being equal to `owner`; i.e. this only happens in a subclass of a parent with class_attributes.

I believe this was introduced in https://github.com/rails/rails/commit/1962e8d7350aef9af3e3f42ce81f3958cc634734 (but I haven't done a bisect yet). The issue is not present in v7.2.2.

Edit: bisect does point to 1b94c8199d26dc6ad34e83ec4bd081283fe671e7

### System configuration
**Rails version**: 8.0.0

**Ruby version**: 3.3.5

**Comment by zvkemp** [comment]
Introduced https://github.com/rails/rails/pull/52717.

This is a potential solution:

```ruby
     ...
      name = name.to_sym
      namespaced_name = "__class_attribute_#{name}".to_sym
      ::ActiveSupport::ClassAttribute.redefine(self, namespaced_name, default)

      class_methods << "silence_redefinition_of_method def #{name}; #{namespaced_name}; end"
      class_methods << "silence_redefinition_of_method def #{name}=(value); #{namespaced_name}=(value); end"
     ...
```

...however I think it's probably preferable to just revert that commit. While it's laudable to increase the performance of the writer, that was the _only_ meaningful increase of any of the benchmarks outlined in the original PR. Those class-level writers are very unlikely to be a hot path, so I don't think the trade-off in non-standard behavior is worth the speed increase.

@byroot @casperisfine your thoughts?

**Comment by byroot** [comment]
> Those class-level writers are very unlikely to be a hot path

That's what I thought, but if I went to optimize it is because I noticed they ended up in a hot path in a real app in production.

**Comment by zvkemp** [comment]
> they ended up in a hot path in a real app in production

Without seeing the app in question, this really seems like an anti-pattern. Or rather, something to optimize in that app, rather than break standard expectations about inheritance. The effect of this in our app is that the setter overrides apply to the first call but not any subsequent calls — a very astonishing result, and one that surfaces in unexpected ways (see https://github.com/graphiti-api/graphiti/issues/486).

**Comment by byroot** [comment]
> this really seems like an anti-pattern.

It's a question of point of view. You can see it as an anti-pattern, or as a major footgun that a simingly normal attribute accessor has abysmal performance.

But I'm looking at ways to support your use case without losing too much performance.

**Comment by byroot** [comment]
Also note that your prepend works for `attr=`, but would already not have worked on 7.2 and older with a reader because the method was similarly redefined.

So in a way, this ship had already sailed, `class_attribute` was always tricky to decorate.

**Comment by byroot** [comment]
Also a very easy workaround for both, is to do:

```ruby
class Foo
  class_attribute :_some_attribute

  class << self
    def some_attribute
      _some_attribute
    end

    def some_attribute=(value)
      self._some_attribute = value
    end
  end

end
```

**Comment by zvkemp** [comment]
That's essentially the workaround I would propose be incorporated into ActiveSupport (https://github.com/rails/rails/issues/53606#issuecomment-2476592786). It would only re-define the internal implementation, leaving user-defined behavior alone.

**Comment by byroot** [comment]
Otherwise I have this kind of mixed bag solution: https://github.com/rails/rails/commit/c07b03d746881768d12cc0dd260058d1382b9b7f
