### ISSUE TITLE
Error in ‘Getting Started’ guide - Incorrect use of textarea in Step 7.3.3.

### ISSUE THREAD

**Issue by LamaInPijamas** [rails/rails#53609]
URL to the issue: https://guides.rubyonrails.org/getting_started.html 
STEP: 7.3.3

The documentation currently includes the following line in app/views/articles/new.html.erb:
<%= form.textarea :body %>

When following along, this results in an error:
ActionView::Template::Error (undefined method `textarea' for an instance of ActionView::Helpers::FormBuilder)

This is happening because of small typo ,- there is a missing underscore.
The correct method name is text_area : 
<%= form.text_area :body %>

**Comment by fatkodima** [comment]
Please, provide a PR with a fix.

**Comment by LamaInPijamas** [comment]
I’ve submitted a PR #53610. Let me know if any further adjustments are needed.

**Comment by skipkayhil** [comment]
https://github.com/rails/rails/pull/53610#issuecomment-2472213200
