### ISSUE TITLE
find_each with model repressing a view raise error since rails 8.0

### ISSUE THREAD

**Issue by aandrieu** [rails/rails#53638]
Hello 👋 

Bumping from rails 7.2 to rails 8.0 was really smooth except for this issue.

We use a model to represent a view and it seems that we can no longer use `find_each` on this class.
Based on some investigation it seems related to #52384 that introduced a cursor approach for batched operations. Indeed, this PR use `primary_key` function as default cursor but since our model is a view this method returns `nil` resulting in an error in find_each 😬 .

### Steps to reproduce

First need to create a SQL view (for instance using this snipets):
```
CREATE VIEW users AS
SELECT *
FROM (
    VALUES
        ('1', 'Alexis', 28),
        ('2', 'John', 30),
        ('3', 'Jane', 25)
) AS t(id, name, age);
```

Then you can reproduce the error with the following code
```ruby
class User < ApplicationRecord
end

User.where("age < 30").find_each do |user|
   puts user
end
# Expected corresponding value for [] to be an Array
```

### Expected behavior
Before this version it was working, so it should continue to work.

BTW, I don't know if it is a good idea or a hack to use a model to represent a view. So if it is not a valid case feel free to close this issue 😄 

### Actual behavior
Error is raised.

### System configuration
**Rails version**: 8.0
**Ruby version**: 3.3.6

Many thanks

**Comment by fatkodima** [comment]
Will
```ruby
class User < ApplicationRecord
  self.primary_key = :id
end
```
work?

**Comment by aandrieu** [comment]
Yes for view with primary key it will (so in the exemple it will). But in our case unfortunately we don't have one.

The view look like more something like that:
```
CREATE VIEW users AS
SELECT *
FROM (
    VALUES
        ('Alexis', 28),
        ('John', 30),
        ('Jane', 25)
) AS t(name, age);
```

**Comment by fatkodima** [comment]
I wonder how it worked for views without the `id` column. Had it worked?

**Comment by aandrieu** [comment]
Yes used to work. But since we were always bellow the limit of 1000 maybe there were some hidden issues

**Comment by fatkodima** [comment]
Yes, so that looks like was the case, because it had < 1000 records and used just `select *` and returned early because there were no more records. So it was still broken generally. I think, you need to either convert that view to a regular table or include the `id` column in it or batch over some other existing column in the view. I think, there is nothing rails can help in this case - batch iteration is not possible without some unique column.

**Comment by aandrieu** [comment]
Ok thank you for the clarifications 👍 

I think we can close this issue if it is expected  😄
