### ISSUE TITLE
Active model serializer is not working on Rails 8

### ISSUE THREAD

**Issue by anthonylee1994** [rails/rails#53648]
### Steps to reproduce
1. install `active_model_serializers`
2. `rails g serializer User`

### Expected behavior
It will return json { id: 1 }

### Actual behavior
<img width="1139" alt="Screenshot 2024-11-15 at 14 14 28" src="https://github.com/user-attachments/assets/de303ba3-4fa2-405d-9325-58b3a0dfadb9">

### System configuration
**Rails version**: 8

**Ruby version**: 3.36

**Comment by Earlopain** [comment]
Why do you think this is a bug in rails? Can you create a test case with https://edgeguides.rubyonrails.org/contributing_to_ruby_on_rails.html#create-an-executable-test-case

**Comment by Earlopain** [comment]
Ah, right. Looks like there is already a PR for it https://github.com/rails-api/active_model_serializers/pull/2483 (and also https://github.com/rails-api/active_model_serializers/pull/2482 from about two months ago)

**Comment by byroot** [comment]
Ah good catch. I'll close this as a 3rd party issue.

And cc @bf4 who's been very helpful in merging and releasing patches for AMS in the past.
