### ISSUE TITLE
Activerecord's `method_missing` method is not thread-safe

### ISSUE THREAD

**Issue by eyad-alabadleh** [rails/rails#53667]
This issue is related to a [change](https://github.com/rails/rails/pull/50594) introduced in rails 7.1.4 and it is affecting all versions after it. If, at the same time, many threads have called an attribute method that has not been defined yet, then these threads will go to the `method_missing` method and they will not be able to call the attribute method successfully. This is the current definition of `method_missing`:
```ruby
def method_missing(name, ...)
  unless self.class.attribute_methods_generated?
    if self.class.method_defined?(name)
      # The method is explicitly defined in the model, but calls a generated
      # method with super. So we must resume the call chain at the right step.
      last_method = method(name)
      last_method = last_method.super_method while last_method.super_method
      self.class.define_attribute_methods
      if last_method.super_method
        return last_method.super_method.call(...)
      end
    elsif self.class.define_attribute_methods
      # Some attribute methods weren't generated yet, we retry the call
      return public_send(name, ...)
    end
  end

  super
end
```
Only one thread will be able to successfully define the attributes methods and call `return public_send(name, ...)` (in the elsif block). All other threads will call `super` and will raise an exception like to this:
```
.rvm/gems/ruby-3.3.2@active_record_bug/gems/activemodel-7.2.2/lib/active_model/attribute_methods.rb:509:in `method_missing': undefined method `name' for an instance of User (NoMethodError)
```
This is because once the attribute methods are defined, most of the paths in the method above will lead to calling `super`. The threads will go on one of these paths:
- If the thread is at `unless self.class.attribute_methods_generated?`, then it will get `true` and will not enter the unless block, and will call `super`.
- if the thread is at `if self.class.method_defined?(name)`, then it will get `true` and enter the block, will not find a `super_method` and will call `super`.
- if the thread is at `elsif self.class.define_attribute_methods`, then it will get `false` since the methods are already defined and will call `super`

### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "7.2.2"
  gem "sqlite3"
end

require "active_record/railtie"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :name, null: false
    t.string :username, null: false
  end
end

class User < ActiveRecord::Base
  def method_missing(name, ...)
    # add sleep to simulate a race condition
    sleep 1
    super
  end

  def username
    "override: #{super}"
  end
end

class BugTest < ActiveSupport::TestCase
  def test_call_undefined_method
    # create test user
    user = User.create!(name: "name", username: "username")

    # undefine attribute methods to simulate the case where methods have not been defined yet
    User.undefine_attribute_methods

    # call name method on the user from many thread at the same time
    threads = []
    10.times do
      threads << Thread.new do
        assert_equal "name", user.name
      end
    end
    threads.each(&:join)
  end

  def test_call_defined_method_that_calls_super
    # create test user
    user = User.create!(name: "name", username: "username")

    # undefine attribute methods to simulate the case where methods have not been defined yet
    User.undefine_attribute_methods

    # call name method on the user from many thread at the same time
    threads = []
    10.times do
      threads << Thread.new do
        assert_equal "override: username", user.username
      end
    end
    threads.each(&:join)
  end
end

```

### Expected behavior
All threads should be able to retrieve the attribute value.

### Actual behavior
One thread is able to retrieve the attribute value, other threads raise a `NoMethodError` exception.

### System configuration
**Rails version**:
7.1.4 to 8.0.0

**Ruby version**:
3.3.2

**Comment by Laykou** [comment]
We observe the same behavior and it's a super blocker for Rails upgrades for us.

**Comment by eyad-alabadleh** [comment]
Hey, an update for anyone who is facing this issue. This issue is only happening with the old Rails 6.1 Marshal format, moving to 7.1 format will resolve this issue. If you have to use the old Rails 6.1 Marshal format, the above issue still exists and needs to be resolved.

To change the marshal format, you just need to set this config `config.active_record.marshalling_format_version` to `7.1`. The default value for this (if not set) is `6.1`, or you need to make sure you are loading the `7.1` default configurations in `application.rb` by calling `config.load_defaults 7.1`.

**Comment by Laykou** [comment]
@eyad-alabadleh Are you sure? We were using `config.load_defaults 7.1`  together with Rails 7.1.4 and we were still facing these issues, so it was not affected by incorrect `marshalling_format_version`.

We could still observe random "undefined method `name` for Status object" (which was a standard column in database and should be automatically available by ActiveRecord).

Why would the `marshalling_format_version` be related to this? Thank you

**Comment by eyad-alabadleh** [comment]
Hey @Laykou I am sure because I can reproduce the issue with Marshal format 6.1 but not with 7.1. Also I have upgraded to 7.2 successfully and I do not see these kind of exceptions in the logs as before. You need to make sure you are using marshal format 7.1, please try reading it from the marshaling module directly to make sure `ActiveRecord::Marshalling.format_version`

**Comment by rafaelfranca** [comment]
@byroot should we synchronize that code? I know we are dropping 6.1 Marshal support soon, but for version that are still using it, it would be great to fix the problem.

**Comment by byroot** [comment]
`define_attribute_methods` is already synchronized though. I'll have a look at that reproducer tomorrow.

**Comment by byroot** [comment]
Ok, so the first test case is easy to fix, the second one however, I'm not sure it's even possible. I'll keep digging a bit more but I'm not very hopeful.

Also, I'd like some context on this. This is happening to you in production? How come you're not defining attribute methods eagerly on boot? Or am I missing something?

**Comment by byroot** [comment]
Alright, I found a fix that work for both test cases: https://github.com/rails/rails/pull/53890

I'll merge and backport on green. Thanks a lot for the good reproduction script.

**Comment by eyad-alabadleh** [comment]
Thank you @byroot
