### ISSUE TITLE
Rails 7.2+ Multi Database Read-Write Proxy for Custom SQL (Makara Alternative)

### ISSUE THREAD

**Issue by OskarEichler** [rails/rails#53699]
Since the introduction of Rails 7.2 the gem [Makara](https://github.com/instacart/makara) is no longer working. Until this point it definitely was the best Read-Write Proxy for Connections.

There currently does not seem to be a good alternative. Rails introduced a [build-in read/write split](https://guides.rubyonrails.org/active_record_multiple_databases.html) with version 6, however the setup assumes a CRUD style application rather than a rich API. It’s hooked into routes rather than looking at the actual query content itself.

So while the build-in way does work well for ActiveRecord, any custom SQL is not being handled properly at this point in time. 

The guys over at OLIOEX started working on their own implementation, which is only available for MySQL: https://github.com/OLIOEX/janus-ar

They created a great post outlining the issue: https://tech.olioex.com/ruby/2024/04/16/introducing-janus.html

Makara is currently looking for someone to take over development, as InstaCart seems to have switched over to an in-house solution and will no longer maintain Makara. 

This is a dealbreaker for us to upgrade to Rails 7.2, Rails 8 and beyond.

Ideally the built in Rails way would start to support custom SQL by checking for write prefixes like INSERT, UPDATE, DELETE, LOCK, CREATE, GRANT, DROP, ALTER, TRUNCATE, BEGIN, SAVEPOINT & FLUSH.

It would be great if someone from the core team can chime in here whether this is planned to be supported in the future directly. It certainly is a crucial feature for scaling Rails applications.

### System configuration
**Rails version**: 7.2+

@fatkodima

**Comment by zzak** [comment]
Sorry, we do not accept feature requests / questions / feedback on the issue tracker, and prefer to use [discuss](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for such discussions.

Thank you for understanding.
