### ISSUE TITLE
Implement Default Encryption for Active Job Parameters

### ISSUE THREAD

**Issue by Jhonnyr97** [rails/rails#53712]
**Description**:

Currently, parameters passed to jobs in Active Job are serialized and stored in plain text, potentially exposing sensitive data. This proposal suggests introducing automatic encryption of job parameters by default, thereby enhancing the security of Rails applications.

**Benefits**:
- Enhanced Security: Protects sensitive data without requiring manual implementations by developers.

**Considerations**:
- Compatibility: Ensure that parameter encryption is compatible with the various queue adapters supported by Active Job.
- Performance: Assess the impact on performance and optimize the encryption/decryption process.
- Backward Compatibility: Provide options to disable automatic encryption for existing applications that may not be ready for this change.

Implementing this feature would enhance the security of Rails applications by automatically protecting sensitive data passed to background jobs.

**Comment by fatkodima** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.
