### ISSUE TITLE
delegate :connection in AR models seems buggy > 7.1.4

### ISSUE THREAD

**Issue by jasonperrone** [rails/rails#53720]
### Steps to reproduce
database.yml: (database_A is the default database based on Rails env.)

```
database_A:
  blah blah

database_B:
  blah blah
```

Create an AR class:

```
class Hello < ApplicationRecord
    establish_connection :database_B
end
```

Create another class

```
class Goodbye < ApplicationRecord  
  class << self
    delegate :connection, to: Hello
  end
end
```

### Expected behavior
Running an AR query on Hello returns data from database B in Rails <= 7.1.4
Running an AR query on Goodbye returns data from database B in Rails <= 7.1.4

### Actual behavior
Running an AR query on Hello returns data from database B in Rails > 7.1.4
Running an AR query on Goodbye returns data from database A in Rails > 7.1.4 <= **problem**

It is very interesting to note that whether in 7.1.4 or 7.2.2:

```
Goodbye.connection.current_database => "database_B"
```

But in 7.2.2, the data is coming from database A. That's why I'm reporting this as a bug. If the connection's current database was database A then sure I would expect data from database A. But telling me the current connection is database B but then pulling data from database A is not right.

BTW, the reason we're using delegate in this fashion is we have a dozen of these classes that use a different database from the other hundred classes and one of our guys thought that putting establish_connection in each of these dozen classes would eat connections from the connection pool, but I'm not even sure if that's true. If it's not, I'm fine with just putting establish_connection in each of the dozen classes.

### System configuration
**Rails version**:
7.2.2

**Ruby version**:
3.3.6

**Comment by nvasilevski** [comment]
What about `Goodbye.connection_pool`? Perhaps you could try overriding `connection_pool` as well. And perhaps `Goodbye.lease_connection`

But overall I don't think Rails makes any promises that overriding `connection` is the way to configure connection to the database. `#connection` returns **a** connection which is not guaranteed to be the same connection used everywhere by Rails

**Comment by jasonperrone** [comment]
delegate :connection_pool in addition to delegate :connection appears to be working. Give me a few minutes to confirm.

**Comment by nvasilevski** [comment]
> putting establish_connection in each of these dozen classes would eat connections from the connection pool

I don't think that's true but I also dont think this is the way to configure multi-db setup.

You should consider defining abstract parent classes per-database like
```ruby

class DatabaseARecord < ApplicationRecord
  self.abstract_class = true
  
  connects_to database: {
    writing: :database_a,
    reading: :database_a_replica # if you have read replicas
  }
end

class DatabaseBRecord < ApplicationRecord
  self.abstract_class = true
  
  connects_to database: {
    writing: :database_b,
    reading: :database_b_replica # if you have read replicas
  }
end
```

And define `Hello` and `Goodbye` as `class Hello < DatabaseBRecord` and `class Goodbye < DatabaseBRecord`

**Comment by jasonperrone** [comment]
I wanted to do that. Unfortunately, in the real world, each of these classes is already inheriting from a parent and I can't make them inherit from an abstract class as well. I would have to evaluate copying and pasting everything in from the parents so I could inherit from a new abstract class.

But my integration tests confirm it.. delegate :connection_pool worked.

**Comment by jasonperrone** [comment]
I wonder why the requirement that the class be abstract in order to use connects_to...

**Comment by nvasilevski** [comment]
>I wonder why the requirement that the class be abstract in order to use connects_to...

It's not related to `connects_to`, it's for classes that are not supposed to represent any particular table in the database
>If you are using inheritance with Active Record and don’t want a class to be considered as part of the STI hierarchy, you must set this to true.

https://api.rubyonrails.org/classes/ActiveRecord/Inheritance/ClassMethods.html#method-i-abstract_class-3F

>already inheriting from a parent

Can parents inherit from abstract db-specific classes? Or instead of inheritance you could use composition and share code using modules

**Comment by jasonperrone** [comment]
I don't understand what you mean by "it's not related to connects_to?" What I am saying is I would love to put connects_to in any AR model I want, and I don't understand why I can only put it in abstract classes. I wish I could just put it in Goodbye, for example.

So, the parents are actually AR models that connect to database A. Like, look at this:

```
class Alert < ApplicationRecord
  # lots and lot of methods, callbacks, associations, validations, you name it
end
```

Obviously uses databaseA, the default

Then I have
```
LibAlert < Alert
  # inherits all those wonderful juicy things
  class << self
    delegate :connection_pool, to: LibMetric # LibMetric has the actual establish_connection in it
  end
end
```

So I can't make LibAlert inherit from any abstract class, since it's already inheriting from an AR Model which itself can't be abstract and certainly wouldn't be able to inherit from any abstract class connecting to database B.

**Comment by jasonperrone** [comment]
The last thing you said is interesting. I can put connects_to in a Module and include it? I'd go for that.

**Comment by jasonperrone** [comment]
What I could probably do is move all the methods, callbacks etc in the parent to a concern, and then have the parent and the child include that concern.

**Comment by nvasilevski** [comment]
>I can put connects_to in a Module and include it? 

It is an option, but 
>What I could probably do is move all the methods, callbacks etc in the parent to a concern

This sounds better. Having an abstract parent class per-database is what the guide recommends https://guides.rubyonrails.org/active_record_multiple_databases.html#setting-up-your-application
See `AnimalsRecord`

**Comment by jasonperrone** [comment]
Yeah I think that's the answer, no doubt.

Thanks for all your help, buddy.

**Comment by nvasilevski** [comment]
I hope context from this issue helps. Feel free to open an issue if you find any bugs with multi-db setup

**Comment by jasonperrone** [comment]
I will. I converted a couple of my classes already and so far so good.
