### ISSUE TITLE
`check_constraint` with `validate: false` doesn't generate `NOT VALID` check constraint on `create_table`

### ISSUE THREAD

**Issue by mtsmfm** [rails/rails#53732]
### Steps to reproduce

The following test fails with `T=1` env var.

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "rails", path: "."
  gem "pg"
end

require "active_record/railtie"
require "minitest/autorun"

ENV["DATABASE_URL"] = "postgres://postgres:mysecretpassword@localhost:5432"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
end
Rails.application.initialize!
ActiveRecord::Migration.verbose = false

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    if ENV["T"]
      t.check_constraint "id > 0", name: "foo", validate: false
    end
  end

  unless ENV["T"]
    add_check_constraint :posts, "id > 0", name: "foo", validate: false
  end
end

class BugTest < ActiveSupport::TestCase
  def test_validate_false
    schema = ActiveRecord::SchemaDumper.dump(ActiveRecord::Base.connection_pool, StringIO.new).tap(&:rewind).read

    assert_equal "t.check_constraint \"id > 0\", name: \"foo\", validate: false", schema.scan(/.*check_constraint.*/)[0].strip
  end
end

__END__
$ ruby foo.rb
Run options: --seed 35390

# Running:

.

Finished in 0.033561s, 29.7967 runs/s, 29.7967 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

$ T=1 ruby foo.rb
Run options: --seed 60934

# Running:

F

Finished in 0.068562s, 14.5853 runs/s, 14.5853 assertions/s.

  1) Failure:
BugTest#test_validate_false [foo.rb:40]:
--- expected
+++ actual
@@ -1 +1 @@
-"t.check_constraint \"id > 0\", name: \"foo\", validate: false"
+"t.check_constraint \"id > 0\", name: \"foo\""


1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

It seems Postgres ignores `NOT VALID` option on `CREATE TABLE`:

```sql
DROP TABLE IF EXISTS "posts";
CREATE TABLE "posts" ("id" bigserial primary key);
ALTER TABLE "posts" ADD CONSTRAINT foo CHECK (id > 0) NOT VALID;
SELECT conname, convalidated FROM pg_constraint WHERE contype = 'c' AND conname = 'foo';
/*
 conname | convalidated
---------+--------------
 foo     | f
(1 row)
*/

DROP TABLE IF EXISTS "posts";
CREATE TABLE "posts" ("id" bigserial primary key, CONSTRAINT foo CHECK (id > 0) NOT VALID);
SELECT conname, convalidated FROM pg_constraint WHERE contype = 'c' AND conname = 'foo';

/*
 conname | convalidated
---------+--------------
 foo     | t
(1 row)
*/
```

It causes unintended diff on `db/schema.rb` with `db:schema:load`.
For example:

1. Developer A creates a migration with `add_check_constraint` and pushes a commit with updated `db/schema.rb`
2. Developer B pulls the change and executes `db:schema:load`
3. Developer B executes `db:schema:dump`
4. Developer B gets a diff on `db/schema.rb` because the constraint created without `NOT VALID` option.

### Expected behavior

The test passes with T=1 env var (`T=1 ruby foo.rb`)

### Actual behavior

The test failed.

### System configuration
**Rails version**: Edge (783108d31)

**Ruby version**: 3.3.6

**Comment by kamipo** [comment]
> Executing `ALTER TABLE` query with `NOT VALID` after `CREATE TABLE` query (something like `supports_comments_in_create?`) would be possible choice, in my humble opinion.

As the document says, the purpose of the `NOT VALID` option is to prevent scanning existing rows of a large table, so it is not practically useful to work the `NOT VALID` option with `CREATE TABLE`.

https://www.postgresql.org/docs/current/sql-altertable.html#SQL-ALTERTABLE-DESC-ADD-TABLE-CONSTRAINT

> Scanning a large table to verify a new foreign key or check constraint can take a long time, and other updates to the table are locked out until the `ALTER TABLE ADD CONSTRAINT` command is committed. The main purpose of the `NOT VALID` constraint option is to reduce the impact of adding a constraint on concurrent updates. With `NOT VALID`, the `ADD CONSTRAINT` command does not scan the table and can be committed immediately.

> The PR solves the diff issue but `t.check_constraint` still doesn't create a constraint with `NOT VALID` and it doesn't throw any warn/error. Is this a desired behavior?

PostgreSQL itself also ignores the `NOT VALID` option in `CREATE TABLE`, but this does not cause any problems in practice.

If we frequently make mistakes with `CONSTRAINT` options, it might be useful to validate the options like #46178.

**Comment by mtsmfm** [comment]
I see.

> If we frequently make mistakes

I don't think this option is used that often since no one has been aware of this issue.

**Comment by alvherre** [comment]
I think rails should do what pg_dump does in this case: the constraint is emitted in a separate ALTER TABLE statement, like so:
```
CREATE TABLE public.invalid_test (
    a integer
);
ALTER TABLE public.invalid_test
    ADD CONSTRAINT invalid_test_a_check CHECK ((a > 0)) NOT VALID;
```
Then the NOT VALID flag is correctly understood.

I'm not sure that it's a good idea to have Postgres throw an ERROR when the NOT VALID flag is given at CREATE TABLE time; doing that would break scripts that work today.  Maybe raising a WARNING is sufficient to make users aware of the fact that NOT VALID is being ignored.

**Comment by yahonda** [comment]
Opened https://github.com/rails/rails/pull/54286 to deprecate the `validate: false` option for `check_constraint`.
