### ISSUE TITLE
Proposed:  Versioned inflections

### ISSUE THREAD

**Issue by jprosevear** [rails/rails#53749]
Correctly, https://github.com/rails/rails/blob/main/activesupport/lib/active_support/inflections.rb has been frozen for a long time to not break backwards compat.

However there are many known exceptions (like "canvas") that could be added to make for a better user experience out of the box 

```
rails g model ArtCanvas name:string
[WARNING] The model name 'ArtCanvas' was recognized as a plural, using the singular 'ArtCanva' instead. Override with --force-plural or setup custom inflection rules for this noun before running the generator.
      invoke  active_record
      create    db/migrate/20241126143705_create_art_canvas.rb
      create    app/models/art_canva.rb
      invoke    test_unit
      create      test/models/art_canva_test.rb
      invoke      factory_bot
      create        test/factories/art_canvas.rb
```

Is it reasonable to version inflections and then move them forward with `config.load_defaults` in application.rb but allow something like `config.active_support.inflection_version = 7.2` to allow for backwards compat. 

Non-english could potentially be added in through gems.

**Comment by skipkayhil** [comment]
Thank you so much for the issue but we don't take feature requests on the issue tracker. We recommend you to try to implement the feature and send us a pull request, or if you want to know if the feature will be accepted ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.

**Comment by jprosevear** [comment]
@skipkayhil unfortunately i've been waiting 2 weeks now to be approved on the discussion board
