### ISSUE TITLE
Link on documentation not working

### ISSUE THREAD

**Issue by Naventilaten-Source** [rails/rails#53761]
### Steps to reproduce

Link: https://guides.rubyonrails.org/association_basics.html#polymorphic-associations
Section 4.2

Error Link:
[Associations section of the Composite Primary Keys guide](https://guides.rubyonrails.org/active_record_composite_primary_keys#associations-between-models-with-composite-primary-keys).

```ruby
# Your reproduction script goes here
```

### Expected behavior

Open an active webpage

### Actual behavior

webpage not found

### System configuration
**Rails version**:

**Ruby version**:

**Comment by fatkodima** [comment]
Do you want to send a fix PR? The `.html` suffix is missing in the url.
