### ISSUE TITLE
ActiveRecord::Relation#pick/#pluck problem when there is a "contradiction" in a where clause

### ISSUE THREAD

**Issue by zverok** [rails/rails#53772]
First of all, I know it is, like, 5 years late (just now transitioning an old codebase from Rails 6.0 up). But still, I would like to at least have Rails team opinions about one problematic consequence of an optimization made for “definitely empty” relation in https://github.com/rails/rails/pull/37266

### Steps to reproduce

Our code has a lot of statements like this:

```ruby
count, source_count, from, to = UserEvents.where(user_id: some_user_ids)
  .pick(Arel.sql('count(*), count(distinct source_id), min(triggered_at), max(triggered_at)'))
```

### Expected behavior

Before the optimization, we would have the result of this statement when `some_user_ids` are empty, as follows:
* count=0
* source_count=0
* from=nil
* to=nil

This seemed convenient and corresponded to the reality (as `some_user_ids` is a dynamic param, then when it is empty, we have our counts consistent with other situations).

### Actual behavior

After the optimization, this `pick` would return `nil`, making all counts `nil`, too.

There are also subtler problems, like having (in the same situation):
```ruby
row = some_relation.pluck(Arel.sql('some, columns'))
```
...when it is expected for all values to be `nil`, but the count of them in row is important (think “empty table” rendering in HTML).

So... I understand it is probably too late to question the approach (and there are several comments in the original PR—after it was merged—pointing at the problem, none of them answered), but, as a mental exercise, I see three possible answers:
1. An ability to just turn off the optimization via some settings (globally, or per relation, some chained method like `.enforced` or something)
2. A smarter analysis at least in `pluck`, to see if the list of columns include any `count`, and either skipping the optimization, or just “faking” the answer properly (by providing an array with values with `nil` for non-`count` columns, and `0` for `count` columns)
3. Or, maybe, there is a more idiomatic way to make this query without resorting to a literal SQL (with some Arel query builder), which will give the desired outcome?

Thanks.

**Comment by fatkodima** [comment]
I think simply skipping the optimization when the query has a custom `select` can solve the problem.
