### ISSUE TITLE
locking_enabled? Returns a Column Object Instead of Boolean in ActiveRecord

### ISSUE THREAD

**Issue by Grigore-George-Mihai** [rails/rails#53771]
### Steps to reproduce
The `locking_enabled?` method in ActiveRecord, which determines whether optimistic locking is enabled for a model, does not return a strict boolean value (`true` or `false`). Instead, it returns an instance of `ActiveRecord::ConnectionAdapters::Column` when the `lock_version` column is present.

```ruby
require "active_record"
require "sqlite3"

ActiveRecord::Base.establish_connection(
  adapter: "sqlite3",
  database: ":memory:"
)

class Article < ActiveRecord::Base
end

ActiveRecord::Schema.define do
  create_table :articles, force: true do |t|
    t.string :title
    t.integer :lock_version, default: 0, null: false
  end
end

puts "Locking enabled?: #{Article.locking_enabled?.class}" # Expected: TrueClass
```

### Expected behavior

The `locking_enabled?` method should return a strict boolean value (`true` or `false`), regardless of whether optimistic locking is enabled.

### Actual behavior

The `locking_enabled?` method returns the second operand of the && operation, which is an `ActiveRecord::ConnectionAdapters::Column` object when optimistic locking is enabled.

### System configuration
**Rails version**: 7.2.2 / 8.0.0

**Ruby version**: 3.3.4

Suggested Fix
```ruby
def locking_enabled?
  !!(lock_optimistically && columns_hash[locking_column])
end
```

**Comment by fatkodima** [comment]
Why do you need a strict boolean for this method?

**Comment by Grigore-George-Mihai** [comment]
> Why do you need a strict boolean for this method?

Most Rails predicate methods return strict boolean values, and the documentation suggests it should be boolean. I wasn’t sure if it’s necessary here.

**Comment by Grigore-George-Mihai** [comment]
> There are also many rails predicate methods which return just truthy/falsey values (not necessary `true`/`false`). They are expected to be used in conditionals without explicit checking by `== true` or `== false`. So, I think there is no need to fix this. But other people may have other opinions.

That makes sense, thanks for the clarification. I think we can close this.
