### ISSUE TITLE
`rails test --profile` exits with non-zero status when tests pass

### ISSUE THREAD

**Issue by mattbrictson** [rails/rails#53806]
When tests are run using the `--profile` option, the exit status is `1`, even when all tests pass.

### Steps to reproduce

```ruby
require "bundler/inline"
gemfile(true) do
  source "https://rubygems.org"
  gem "railties"
end

# When this test file is run with `--profile` option, it exits with non-zero status,
# even though the test passes.
#
# E.g.
#
#   $ RAILS_MINITEST_PLUGIN=1 ruby assert_true.rb --profile
#   $ echo $?
#   1

require "active_support"
require "minitest/autorun"

class GoodTest < ActiveSupport::TestCase
  def test_stuff
    assert true
  end
end
```

### Expected behavior

`bin/rails test --profile` should exit with status `0` if all tests pass.

### Actual behavior

The exit status is non-zero.

### System configuration

**Rails version**: 8.0.0

**Ruby version**: ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [arm64-darwin24]

**Comment by fatkodima** [comment]
For reference, `--profile` was added in https://github.com/rails/rails/pull/49082.

Identified what the problem is - going to open a PR.
