### ISSUE TITLE
Railties 7.1 is not compatible with Ruby 3.0 due to zeitwerk dependency

### ISSUE THREAD

**Issue by jkastner864** [rails/rails#53810]
### Steps to reproduce
When upgrading Rails 6.1.7.7 to 7.1.5 with Ruby 3.0.7, I get this error:
```
Bundler found conflicting requirements for the Ruby version:
  In Gemfile:
    Ruby (~> 3.0.7.0)

    rails (= 7.1.5) was resolved to 7.1.5, which depends on
      railties (= 7.1.5) was resolved to 7.1.5, which depends on
        zeitwerk (~> 2.6) was resolved to 2.7.1, which depends on
          Ruby (>= 3.2.0)
```
Zeitwerk jumps to 2.7 which requires Ruby >= 3.2.0.  Railties is documented to be compatible with Ruby >= 2.7.0.

### Expected behavior
Bundler builds without error on Ruby 3.0.

### Actual behavior
Bundler cannot build due to requirement conflicts.

### System configuration
**Rails version**: 7.1.5

**Ruby version**: 3.0.7

**Comment by skipkayhil** [comment]
The Zeitwerk requirement is `~> 2.6`, only `2.7+` requires Ruby 3.2.

If Bundler isn't picking a `2.6.x` you may want to upgrade Bundler or manually specify `< 2.7` in your Gemfile.
