### ISSUE TITLE
Rails 7.2+ `db:truncate_all` fails with Postgres db

### ISSUE THREAD

**Issue by chiperific** [rails/rails#53834]
### Steps to reproduce

1. Have a Postgres db setup with some data (not sure about the other adapters)
2. Attempt to run `rails db:truncate_all` or `rails db:seed:replant`
3. See the error:

```sh
$ rails db:truncate_all
bin/rails aborted!
ActiveRecord::StatementInvalid: PG::FeatureNotSupported: ERROR:  cannot truncate a table referenced in a foreign key constraint (ActiveRecord::StatementInvalid)
DETAIL:  Table "users" references "tenants".
HINT:  Truncate table "users" at the same time, or use TRUNCATE ... CASCADE.


Caused by:
PG::FeatureNotSupported: ERROR:  cannot truncate a table referenced in a foreign key constraint (PG::FeatureNotSupported)
DETAIL:  Table "users" references "platform_tenants".
HINT:  Truncate table "users" at the same time, or use TRUNCATE ... CASCADE.

Tasks: TOP => db:truncate_all
```

### Expected behavior

Expect commands like `rails db:truncate_all` and `rails db:seed:replant` to truncate all database tables without foreign key violation errors.

### Actual behavior

Commands fail with given message.

### System configuration
**Rails version**: Rails 7.2.2

**Ruby version**: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [aarch64-linux]

**Others**:
* psql (PostgreSQL) 15.10 (Debian 15.10-0+deb12u1)
* PostgreSQL: postgres:15.2 docker image

**Comment by fatkodima** [comment]
Can you test with rails 8.0 or rails `main` ?

**Comment by chiperific** [comment]
I created a new rails 7.2.2 / pg 1.5.9 app with simple dummy data and was unable to replicate the issue.

**Comment by zernie** [comment]
@chiperific I'm having the same issue. I had to write a custom rake task that truncates tables using `RESTART IDENTITY CASCADE`.
