### ISSUE TITLE
The `column-side` element is not auto-scrolling properly when you are using a desktop browser

### ISSUE THREAD

**Issue by raphox** [rails/rails#53852]
When I check, in the following code, the value of the variable `isMobile` using a desktop browser, its value is `smooth`:

https://github.com/rails/rails/blob/d3e3eefeef20bfbec69a8358a7c39d3a7f20574c/guides/assets/javascripts/guides.js#L59-L72

When the variable `isMobile` is `true` in the following code, the auto-scroll code is ignored:

https://github.com/rails/rails/blob/d3e3eefeef20bfbec69a8358a7c39d3a7f20574c/guides/assets/javascripts/guides.js#L367-L369

**Comment by raphox** [comment]
The screen will always have the `matchMedia` (mobile or not). Maybe it is a good idea to change the code:

```diff
- if ('matchMedia' in window) { 
+  if (isMobile && 'matchMedia' in window) { 
```

Do you agree @SleeplessByte?

**Comment by SleeplessByte** [comment]
I don't agree. The value `isMobile` should be a boolean. The correct code is:

```diff
   var mediaQueryList = window.matchMedia(`(max-width: ${MOBILE_WIDTH_FROM_STYLE_CSS_BREAKPOINT}px)`); 
-  isMobile = mediaQueryList.matches ? 'auto' : 'smooth'; 
+  isMobile = mediaQueryList.matches; 

   mediaQueryList.addEventListener('change', function (ev) { 
-    isMobile = ev.matches ? 'auto' : 'smooth';
+    isMobile = ev.matches;
   }); 
```

They probably will accept a PR!
