### ISSUE TITLE
`Action Cable` and `transactional_fixtures` with Postgres adapter is causing flaky system specs

### ISSUE THREAD

**Issue by Nicolasvb23** [rails/rails#53883]
### Introduction
After upgrading to `Rails 7.2`, we started noticing some flakiness and weird errors around our system specs – sometimes the execution would succeed but sometimes it would hang and in some cases weird errors would come up (some even related to C and memory allocations). We've tried with a greater version of Rails (8.0) and even pointing to the last commit on main to see if this was already fixed, but the results were the same.

After digging a little more around the issue, we find out that the problem was related to `transactional_fixtures` and `ActionCable` not working well together when using the `Postgres adapter`. Either switching from `transactional_fixtures` to [`DatabaseCleaner`](https://github.com/DatabaseCleaner/database_cleaner) or changing `ActionCable` to use the `test` adapter in the `cable.yml` fixed the issue.

We managed to do git bisect in the Rails repo and it seems that the issue is directly related to the changes introduced in [this PR](https://github.com/rails/rails/pull/50999).

### Steps to reproduce
To assist in replicating the issue, we've created two sample applications that demonstrate the problem:
* [deadlock_rails_7.2](https://github.com/cedarcode/deadlock_rails_7.2)
* [deadlock_rails_8](https://github.com/cedarcode/deadlock_rails_8)

The steps are:

1. Clone the repo
2. Run the system tests several times, to see the flakiness

### System configuration
**Rails version**: `Rails 7.2`, `Rails 8.0`

**Ruby version**: `Ruby 3.3.5`, `Ruby 3.3.6`

### Stack trace
The gem [`sigdump`](https://github.com/fluent/sigdump) was used to generate the dump with the status of all the threads and variables regarding the process that executed the system spec:
[sigdump_stack_trace.txt](https://github.com/user-attachments/files/18042044/sigdump_stack_trace.txt)

**Comment by Nicolasvb23** [comment]
Here goes few screenshots with some of the different outputs resultant from running the specs:
![image](https://github.com/user-attachments/assets/961452a7-bf68-469e-baac-1a9465d03a17)
![image](https://github.com/user-attachments/assets/56d36c83-e583-48f8-9f0e-5c4bbb4e6a4b)
And
![image](https://github.com/user-attachments/assets/d53bae7e-87f5-469a-9664-98a572ce8f21)
![image](https://github.com/user-attachments/assets/27ec2d34-b33e-4b3d-bc65-2a2cd2db1adc)

**Comment by Nicolasvb23** [comment]
Thank you so much for the quick resolution @byroot 👏

We've tried our applications with the changes you've introduced and everything seems to be alright

**Comment by byroot** [comment]
Welcome. Probably wouldn't have been so easy without the provided reproduction.
