### ISSUE TITLE
Update to 7.2.2 changed type of cookie value

### ISSUE THREAD

**Issue by Aqualon** [rails/rails#53889]
We had a test failure in an app while updating from 7.2.1.2 to 7.2.2 and broke it down to change in 066c4134806d6a05972f085139c2326704fc427c 

### Steps to reproduce
Define CookieController setting a number on a cookie
```
class CookieController < ApplicationController
  def update
    cookies[:key] = 123
  end
end
```
and this test case:
```
class CookieControllerTest < ActionController::TestCase
  tests CookieController
  test "update" do
    put :update

    assert_equal 123, cookies[:key]
  end
end
```
In Rails 7.2.1.2 this test is green, in 7.2.2 it's failing
```
Failure:
CookieControllerTest#test_update [test/controllers/cookie_controller_test.rb:8]:
Expected: 123
  Actual: "123"
```
For the Gemfile to check
```
# broken
gem "rails", git: "https://github.com/rails/rails.git", branch: "7-2-stable", ref: "066c4134806d6a05972f085139c2326704fc427c"
# working
gem "rails", git: "https://github.com/rails/rails.git", branch: "7-2-stable", ref: "add6b17792d5a4a75008483b4852cd19221a2b90"
```

### Expected behavior
Not sure if it's a bug or just something that worked by coincidence before?

### Actual behavior
Instead of the set number it's a string in test

### System configuration
**Rails version**: 7.2.x
**Ruby version**: 3.3.6

**Comment by fatkodima** [comment]
Cookie values are always strings. That was a coincidence and the test code needs to be fixed.
