### ISSUE TITLE
Rails `8.0.0.1` node packages released as `8.0.1` (instead of `8.0.001`?)

### ISSUE THREAD

**Issue by tagliala** [rails/rails#53903]
### Steps to reproduce
Hello,

apologies if this is a duplicate. I've searched and at the best of my knowledge this is not a duplicate

I've noticed the following:

```
$ pnpm outdated
┌───────────────────────────┬─────────┬────────┐
│ Package                   │ Current │ Latest │
├───────────────────────────┼─────────┼────────┤
│ @rails/actioncable        │ 7.2.200 │ 8.0.1  │
├───────────────────────────┼─────────┼────────┤
│ @rails/actiontext         │ 7.2.200 │ 8.0.1  │
├───────────────────────────┼─────────┼────────┤
│ @rails/activestorage      │ 7.2.200 │ 8.0.1  │
└───────────────────────────┴─────────┴────────┘
```

Ref: https://www.npmjs.com/package/@rails/actioncable/v/8.0.1

### Expected behavior

Package released as `8.0.001`

### Actual behavior

Package released as `8.0.1`, that ~will collide with the actual `8.0.1`~ is a little bit misleading, but will not collide with `8.0.1` that will be released as `8.0.100`

### System configuration
**Rails version**: 7.2.2 (should not matter)

**Ruby version**: 3.3.6 (should not matter)

### Other infos

I suspect that the trailing zeroes are being stripped out

**Comment by byroot** [comment]
cc @jhawthorn

**Comment by tagliala** [comment]
Sorry, maybe `8.0.1` will be released as `8.0.100` and that will be more than fine

**Comment by tagliala** [comment]
Thanks, I've later realized that 8.0.1 will be 8.0.100 and this should not be an issue at all (just a little bit confusing, since it is the first time it happens given 8.0.0 is the first major release using the new versioning)

I'm closing here

**Comment by tagliala** [comment]
> (except of course - that was used before but has its own downside).

I think that the current implementation is much better, thanks. The small confusion only affects major version bumps, and can maybe addressed with a small alert in the documentation related to javascript packages by stating that this is how node deals with leading zeros
