### ISSUE TITLE
Add an option to ensure uniqueness of newly generated session IDs in `Session::CacheStore`

### ISSUE THREAD

**Issue by riseshia** [rails/rails#53900]
## Background

`Session::CacheStore`, which uses `ActiveSupport::Cache::Store` as session storage, relies on `SecureRandom.hex(16)` to ensure session ID uniqueness. ([ref](https://github.com/rails/rails/blob/6d638f9f30c976d3e8899714459e776b3acb0cf2/actionpack/lib/action_dispatch/middleware/session/abstract_store.rb#L28-L32)) While this provides 2^128 possible values and is practically sufficient in most cases (Ref: [Birthday attack - Wikipedia](https://en.wikipedia.org/wiki/Birthday_attack)), there are certain systems where additional measures are preferred to guarantee uniqueness, even at the cost of some extra overhead (e.g., a single `set` command for `RedisCacheStore`).

## Proposal

I propose adding an option to `Session::CacheStore` to guarantee session ID uniqueness by checking whether the generated session ID is already in use. This option could be named something like `ensure_sid_uniqueness` or something better.

## Reference implementations

- `Session::MemCacheStore` with dalli includes logic to regenerate session IDs if the generated ID already exists.
    - Ref: https://github.com/petergoldstein/dalli/blob/67942b8db6ba8ae9c39e30d9c0c63fb1525586b3/lib/rack/session/dalli.rb#L126-L133
- The session store implementation in `redis-store` uses a similar approach.
    - Ref: https://github.com/redis-store/redis-rack/blob/d2cb7cb512687d81e817a44f8498b1e39f727261/lib/rack/session/redis.rb#L22-L31

## Implementation

Similar to `redis-store`, we could use a "set" command (via `CacheStore#write` with `unless_exist`) to check that sid is in use or not when the option given. I have willing to submit PR for this if core team don't mind.

**Comment by fatkodima** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org) for feedback.

**Comment by riseshia** [comment]
oops ok. Thanks for pointing out.
