### ISSUE TITLE
Use SERVER_PROTOCOL instead of HTTP_VERSION

### ISSUE THREAD

**Issue by MSP-Greg** [rails/rails#53925]
Current master has the following:

https://github.com/rails/rails/blob/527483b8a84980c8ee90ce569a0e805e302427fb/actionpack/lib/action_controller/metal/live.rb#L56-L61

Current versions of common 'support software' are now using `SERVER_PROTOCOL` instead of `HTTP_VERSION`.  The main reason is the conflict that arises when a client request supplies a `version` header.

Hence, could the current line
```ruby
if request.get_header("HTTP_VERSION") == "HTTP/1.0"
```
be changed to the following:
```ruby
if (request.get_header("SERVER_PROTOCOL") || request.get_header("HTTP_VERSION")) == "HTTP/1.0"
```

This was from a quick GitHub search of the the repo.

I'm not sure which versions are currently maintained, and sometime in the future `HTTP_VERSION` should be removed, so a comment might be helpful.  Hence, I haven't submitted a PR.

**Comment by byroot** [comment]
Thanks for the heads up. I patched it and backported up to 7.1.
