### ISSUE TITLE
Error subscriber reports different Action View errors in development and production

### ISSUE THREAD

**Issue by tombruijn** [rails/rails#53938]
When errors are reported to an [error reporter subscriber](https://api.rubyonrails.org/v7.2.2/classes/ActiveSupport/ErrorReporter.html#method-i-subscribe), the reported error is different in development and production environments when the error originates from an Action View view template.

### Steps to reproduce

Given this error subscriber:

```ruby
# config/application.rb

# ...

class MyErrorSubscriber
  def self.report(error, handled:, severity:, context: {}, source: nil)
    puts "MyErrorSubscriber: #{error.class}: #{error}"
  end
end
Rails.error.subscribe(MyErrorSubscriber)
```

Given this view:

```erb
<%# app/views/examples/index.html.erb %>
<% nil.foo %>
```

I'm including a test scenario based on the app template from the contribution guide. It shows different behavior though: reporting both the `ActionView::Template::Error` and `NoMethodError` errors in the production environment.
https://github.com/tombruijn/rails-minimal-duplicate-error-script

This `rails new` test app shows the same behavior I describe in this issue.
https://github.com/tombruijn/rails-minimal-duplicate-error-app

### Expected behavior

I expect the same error type to be reported in development and production to the error subscriber. Either `ActionView::Template::Error` or `NoMethodError`.

### Actual behavior

In development, `ActionView::Template::Error` is reported.

```
MyErrorSubscriber: ActionView::Template::Error: undefined method `foo' for nil:NilClass

    nil.foo
       ^^^^
```

In production, `NoMethodError` is reported.

```
MyErrorSubscriber: NoMethodError: undefined method `foo' for nil:NilClass

    nil.foo
       ^^^^
```

### System configuration

**Rails version**:

- 7.2.2
- 8.0.0.1

**Ruby version**s:

- ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [aarch64-linux]
- ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin24]

### More information

The `ActionView::Template::Error` error is an error wrapper that wraps the actual `NoMethodError` that happened in the view and contains the `NoMethodError` that occurs in the view template as an [error cause](https://ruby-doc.org/3.2.0/Exception.html#method-i-cause).

The behavior difference is related to how the two environments handle errors. In development, it shows the debugging information (error message, backtrace, etc). In production, it shows the `public/500.html` page.

In development, the error is reported by the [`actiondispatch/middleware/executor.rb`'s `rescue` block](https://github.com/rails/rails/blob/v8.0.0.1/actionpack/lib/action_dispatch/middleware/executor.rb#L24-L25).

In production, the error is read from the [`action_dispatch.report_exception` request environment](https://github.com/rails/rails/blob/v8.0.0.1/actionpack/lib/action_dispatch/middleware/executor.rb#L18-L21). This request environment is set by the [`ShowException` middleware](https://github.com/rails/rails/blob/v8.0.0.1/actionpack/lib/action_dispatch/middleware/show_exceptions.rb#L36-L38), where on line 37 it explicitly unwraps the error with `unwrapped_exception`. [It only does that](https://github.com/rails/rails/blob/v8.0.0.1/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L39-L40) for `ActionView::Template::Error` errors.

Whether it does one or the other (raise error and show debug page / show 500 error page) comes from the [DebugExceptions middleware's `render_exception` method](https://github.com/rails/rails/blob/v8.0.0.1/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb#L61-L75). The handling of that influences what error is reported to the error subscriber.

The development error debug page is configurable with [`config.consider_all_requests_local`](https://guides.rubyonrails.org/configuring.html#config-consider-all-requests-local). However, setting this option to `true` in the production environment, makes it so that it reports _no errors_ to the error subscriber. I see the same behavior for `def show_detailed_exceptions? = true` when added to the controller; it reports no errors to the error subscriber in production.

We noticed this behavior in the [AppSignal Ruby gem](https://github.com/appsignal/appsignal-ruby). Our Ruby gem reports all errors reported by the Rails error reporter and errors that bubble up the middleware stack. We deduplicate errors, but do not deduplicate errors that are already reported as error causes of another error. Which results in both the `ActionView::Template::Error` and `NoMethodError` errors being reported.

**Comment by byroot** [comment]
> We deduplicate errors, but do not deduplicate errors that are already reported as error causes of another error.

Yeah, Rails does this too: https://github.com/rails/rails/blob/544c90c3ac7bb6a6914a365fabae66d75cfdf5bf/activesupport/lib/active_support/error_reporter.rb#L235-L237, but I think we probably should mark the cause as reported too.

That's the only way I see not to single out `Template::Error`.

**Comment by tombruijn** [comment]
The error deduplication in the error reporter you linked would work if the both the ActionView::Template::Error and the error cause would both be reported to the error reporter, right?
(I am only seeing both the error wrapper and error cause reported separately in [this test script](https://github.com/tombruijn/rails-minimal-duplicate-error-script) but not in a real Rails app.)

The issue we're running into for our error deduplication, is that Rails reports a different error to error reporter subscribers (the error cause) than is raised up through the middleware (the ActionView::Template::Error error wrapper). 
It only does this in production, breaking the deduplication in our Ruby gem.
In the development env, the middleware and error reporter subscribers receive the same error type.

In a Rails app in production, we first receive the ActionView::Template::Error error wrapper through our middleware error reporter, and then the error cause (NoMethodError) through the error reporter subscriber.
We can fix the duplicate error reporting on our end in a similar way you suggested, by also marking error causes as being reported when we receive an error.

I'm curious to know if the behavior we're seeing is correct, that Rails reports different errors in production and development to error reporter subscribers for errors originating from Action View templates (ActionView::Template::Error vs the error cause, e.g. NoMethodError).

**Comment by byroot** [comment]
> The error deduplication in the error reporter you linked would work if the both the ActionView::Template::Error and the error cause would both be reported to the error reporter, right?

Yes, but my suggestion is to change that by not only tagging the reported error but also its `#cause`.

**Comment by byroot** [comment]
https://github.com/rails/rails/pull/53975 fixes your repro.

**Comment by tombruijn** [comment]
Thanks! I was wondering if it was supposed to report both errors while creating the repro.
It was actually another behavior difference I found, which prevented me from actually reproducing it in the script, but it was not the behavior difference I created this issue for.

With your fix I've managed to reproduce the original behavior I noticed in a `rails new` app. See the update [repro repo](https://github.com/tombruijn/rails-minimal-duplicate-error-script), the changes are in the [latest commit](https://github.com/tombruijn/rails-minimal-duplicate-error-script/commit/87a011d07745d858c3ee8413a2fcb2a8eae839c0)

Now it There it will still report different errors in production and development.
Is it supposed to do that?

**Comment by byroot** [comment]
> where they report `NoMethodErorr` in production and the `ActionView::Template::Error` in development.

I'll try to find some time to dig into that one, but I suspect it's simply because of which level the exception is report differ in prod and dev. To me that's not a bug, just a subtle implementation detail.

But I'll see if I can fix it.

**Comment by byroot** [comment]
So in production mode the error is reported from the executor middleware:

```
NoMethodError
/Users/byroot/src/github.com/byroot/rails/activesupport/lib/active_support/error_reporter.rb:213:in 'ActiveSupport::ErrorReporter#report'
/Users/byroot/src/github.com/byroot/rails/actionpack/lib/action_dispatch/middleware/executor.rb:20:in 'ActionDispatch::Executor#call'
/Users/byroot/src/github.com/byroot/rails/actionpack/lib/action_dispatch/middleware/static.rb:27:in 'ActionDispatch::Static#call'
/Users/byroot/.gem/rubies/3.4.0-preview2/gems/rack-3.1.8/lib/rack/sendfile.rb:114:in 'Rack::Sendfile#call'
/Users/byroot/src/github.com/byroot/rails/actionpack/lib/action_dispatch/middleware/host_authorization.rb:143:in 'ActionDispatch::HostAuthorization#call'
/Users/byroot/src/github.com/byroot/rails/railties/lib/rails/engine.rb:535:in 'Rails::Engine#call'
/Users/byroot/.gem/rubies/3.4.0-preview2/gems/rack-test-2.1.0/lib/rack/test.rb:360:in 'Rack::Test::Session#process_request'
/Users/byroot/.gem/rubies/3.4.0-preview2/gems/rack-test-2.1.0/lib/rack/test.rb:163:in 'Rack::Test::Session#custom_request'
/Users/byroot/.gem/rubies/3.4.0-preview2/gems/rack-test-2.1.0/lib/rack/test.rb:112:in 'Rack::Test::Session#get'
/opt/rubies/3.4.0-preview2/lib/ruby/3.4.0+0/forwardable.rb:240:in 'Rack::Test::Methods#get'
app.rb:59:in 'BugTest#test_returns_success'
```

In other envs it's also reported first from `ShowEceptions / DebugExceptions`:

```
----------------------------------------
ActionView::Template::Error
/Users/byroot/src/github.com/byroot/rails/activesupport/lib/active_support/error_reporter.rb:213:in 'ActiveSupport::ErrorReporter#report'
/Users/byroot/src/github.com/byroot/rails/actionpack/lib/action_dispatch/middleware/executor.rb:25:in 'ActionDispatch::Executor#call'
/Users/byroot/src/github.com/byroot/rails/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:31:in 'ActionDispatch::DebugExceptions#call'
/Users/byroot/src/github.com/byroot/rails/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:32:in 'ActionDispatch::ShowExceptions#call'
/Users/byroot/src/github.com/byroot/rails/railties/lib/rails/rack/logger.rb:41:in 'Rails::Rack::Logger#call_app'
/Users/byroot/src/github.com/byroot/rails/railties/lib/rails/rack/logger.rb:29:in 'Rails::Rack::Logger#call'
/Users/byroot/src/github.com/byroot/rails/actionpack/lib/action_dispatch/middleware/remote_ip.rb:96:in 'ActionDispatch::RemoteIp#call'
/Users/byroot/src/github.com/byroot/rails/actionpack/lib/action_dispatch/middleware/request_id.rb:34:in 'ActionDispatch::RequestId#call'
/Users/byroot/.gem/rubies/3.4.0-preview2/gems/rack-3.1.8/lib/rack/method_override.rb:28:in 'Rack::MethodOverride#call'
/Users/byroot/.gem/rubies/3.4.0-preview2/gems/rack-3.1.8/lib/rack/runtime.rb:24:in 'Rack::Runtime#call'
/Users/byroot/src/github.com/byroot/rails/actionpack/lib/action_dispatch/middleware/executor.rb:16:in 'ActionDispatch::Executor#call'
----------------------------------------
MyErrorSubscriber: ActionView::Template::Error: undefined method 'foo' for nil
----------------------------------------
NoMethodError
/Users/byroot/src/github.com/byroot/rails/activesupport/lib/active_support/error_reporter.rb:213:in 'ActiveSupport::ErrorReporter#report'
/Users/byroot/src/github.com/byroot/rails/actionpack/lib/action_dispatch/middleware/executor.rb:20:in 'ActionDispatch::Executor#call'
/Users/byroot/src/github.com/byroot/rails/actionpack/lib/action_dispatch/middleware/static.rb:27:in 'ActionDispatch::Static#call'
/Users/byroot/.gem/rubies/3.4.0-preview2/gems/rack-3.1.8/lib/rack/sendfile.rb:114:in 'Rack::Sendfile#call'
/Users/byroot/src/github.com/byroot/rails/actionpack/lib/action_dispatch/middleware/host_authorization.rb:143:in 'ActionDispatch::HostAuthorization#call'
/Users/byroot/src/github.com/byroot/rails/railties/lib/rails/engine.rb:535:in 'Rails::Engine#call'
/Users/byroot/.gem/rubies/3.4.0-preview2/gems/rack-test-2.1.0/lib/rack/test.rb:360:in 'Rack::Test::Session#process_request'
/Users/byroot/.gem/rubies/3.4.0-preview2/gems/rack-test-2.1.0/lib/rack/test.rb:163:in 'Rack::Test::Session#custom_request'
/Users/byroot/.gem/rubies/3.4.0-preview2/gems/rack-test-2.1.0/lib/rack/test.rb:112:in 'Rack::Test::Session#get'
/opt/rubies/3.4.0-preview2/lib/ruby/3.4.0+0/forwardable.rb:240:in 'Rack::Test::Methods#get'
app.rb:59:in 'BugTest#test_returns_success'
----------------------------------------
```

I think the reason is because it goes into the `exception_app` which also has an executor middleware.

**Comment by tombruijn** [comment]
Awesome! Thanks for the fix @byroot!
