### ISSUE TITLE
Allow for lazy initialization of secure token

### ISSUE THREAD

**Issue by acoffman** [rails/rails#53942]
If you specify that a model `has_secure_token`, you can currently configure the token to be automatically created on either `:create` or `:initialize` via `config.active_record.generate_secure_token_on`.

Looking at the implementation [here](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/secure_token.rb#L54) it appears that there is no configuration option you can pass that will cause the token to _not_ be automatically created. In our use case, we only want to generate tokens for users who specifically request one. This is obviously not hard to implement ourselves, but I was wondering if a PR would be of interest that allows this behavior to be configured. I would be happy to submit one if so.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in the [Rails Core discussion board](https://discuss.rubyonrails.org/c/rubyonrails-core/5) for feedback.
