### ISSUE TITLE
Returning the correct namespace for dynamically generated controllers using module_parent 

### ISSUE THREAD

**Issue by budu** [rails/rails#53968]
I've been working on a project to generate controllers from paths and I came across an interesting problem with Rails `module_parent` core extension method.

### Steps to reproduce & Actual behavior

```ruby
module Some; module Namespace; end; end

# Create a controller dynamically
Some::Namespace.const_set 'SomeController', Class.new(ActionController::Base)

# Check the module parent
Some::Namespace::SomeController.module_parent #=> Object
```

### Expected behavior

```ruby
Some::Namespace::SomeController.module_parent #=> Some::Namespace
```

### Additional information

I've traced back the issue to the `module_parent_name` method:

```ruby
def module_parent_name
  if defined?(@parent_name)
    @parent_name
  else
    parent_name = name =~ /::[^:]+\z/ ? -$` : nil
    @parent_name = parent_name unless frozen?
    parent_name
  end
end
```

Here, `@parent_name` is a cache introduced way back in 269c6c6bcf by @jeremy. 

I was wondering why the cache is set before the class is added to the namespace. I've found that the issue is specific to controllers because sub-classing a controller trigger the `ActionController::Railties::Helpers#inherited` method to injects the Rails helpers using the `module_parents` method. The cache is set to nil at this point.

Looking at the `module_parent_name` code, I'm wondering if it would be a good idea to change the condition from `defined?(@parent_name)` to simply `@parent_name`. This would allow meta-programming to happen before the cache gets set. The downside would be that true anonymous classes and top-level modules would never be cached.

### System configuration

```bash
$ ruby --version
ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x86_64-linux]
$ rails --version
Rails 8.0.1
```

**Comment by byroot** [comment]
I suspect the fix is more to not cache is the module is still anonymous. I'll try that tomorrow.
