### ISSUE TITLE
Inconsistent Behavior of Predicate Methods with Different Enum (for Non-column-backed) Attribute Types

### ISSUE THREAD

**Issue by shrkw** [rails/rails#53985]
There seems to be a difference in the behavior of predicate methods (`#{enum_value}?`) depending on the type of the attribute used for an enum with non-column-backed attributes. It is unclear whether this behavior is intentional or a bug.

### Steps to reproduce

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record/railtie"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
  config.secret_key_base = "secret_key_base"
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end
end

class Post < ActiveRecord::Base
  attribute :fruit, :integer
  enum :fruit, %i[apple banana cherry]

  attribute :topic, :string
  enum :topic, %i[sports politics entertainment]
end

class BugTest < ActiveSupport::TestCase
  def test_association_stuff
    post = Post.create!
    post.assign_attributes(fruit: :apple, topic: :sports)

    assert_equal true, post.apple?
    assert_equal true, post.sports?
  end
end

```

### Expected behavior

Both `post.apple?` and `post.sports?` should return `true` when the corresponding values are assigned via `assign_attributes`.

### Actual behavior

- `post.apple?` correctly returns `true` for the integer-based `fruit` enum.
- `post.sports?` unexpectedly does not work for the string-based `topic` enum.

### Question

Is this discrepancy between integer-based and string-based enum attribute types an intentional behavior, or is it a bug?

### System configuration
**Rails version**: 8.0.1

**Ruby version**: 3.3.6

**Comment by fatkodima** [comment]
When values are not provided in enum definitions, indexes are used. This works for integer-based attributes, but does not work for string attributes, because predicate methods (like `.sports?`) compares `0` and `"0"`. You need to explicitly define the enum values. Something like
```ruby
  enum :topic, %i[sports politics entertainment].index_with(&:to_s)
```
is working.

**Comment by shrkw** [comment]
Ah, I see! Since enums use indices, the attribute type should be specified as integer. I understand now. Thank you!
