### ISSUE TITLE
Rails 8.0 Getting Started missing inheritance in code block

### ISSUE THREAD

**Issue by tevulytis** [rails/rails#53995]
### Steps to reproduce
1. Run Rail 8.0 Getting Started Guide from beginning to Chapter 13: https://guides.rubyonrails.org/v8.0/getting_started.html#rich-text-fields-with-action-text.
2. Copy paste from code block below text "First, add the following to the Product model:" into your code.
3. Refresh the browser pointing to Puma server on localhost:3000 serving your code.

### Expected behavior
Website loads and displays products.

### Actual behavior
Error: undefined method `has_rich_text' for class Product

Wrong code:
```ruby
class Product
  has_rich_text :description
  validates :name, presence: true
end
```

Correct code (error does not happen with this)
```ruby
class Product < ApplicationRecord
    has_rich_text :description
    validates :name, presence: true
end
```

As a reference in chapter 7 (validations) class Product is also defined with inheritance in the code block: https://guides.rubyonrails.org/v8.0/getting_started.html#validations.

Same on edge guide: https://edgeguides.rubyonrails.org/getting_started.html#rich-text-fields-with-action-text

I will do the change and PR myself at some point. But if anyone is quicker, feel free! ;)

### System configuration
**Rails version**: 8.0.1

**Ruby version**: ruby 3.3.6

**Comment by mohsen-alizadeh** [comment]
apparently, it's been fixed in https://github.com/rails/rails/pull/53986

**Comment by tevulytis** [comment]
Great, thanks! Now only the push to prod would be great! I believe this issue can be closed then.

**Comment by skipkayhil** [comment]
Ah, I thought I checked that commit but indeed doc generation appears to be stuck

Thank you both for investigating
