### ISSUE TITLE
Problem invoking tasks from eg: db/seeds.rb - rails/tasks/statistics.rake:4: warning: already initialized constant STATS_DIRECTORIES

### ISSUE THREAD

**Issue by e12e** [rails/rails#54002]
### Steps to reproduce
I'm a little uncertain if this can be easily reduced to a single file, so this is what I did:

```console
rails new rails_task_test --api --skip-docker --skip-keeps --skip-action-mailer --skip-action-mailbox --skip-action-text --skip-active-job --skip-active-storage --skip-action-cable --skip-action-cable --skip-asset-pipeline --skip-javascript
cd rails_task_test/
rails db:migrate
git add .
git commit -m "initial commit"
```
Then verify that we can eg run (empty) seed script: `rails db:seed` (no output as expected).

Then add tasks, and invoke from `seeds.rb`:
```ruby
# db/seeds.rb

Rails::Command.invoke 'task:task1'
```

```ruby
# lib/tasks/tasks.rake

namespace :task do
  desc 'Task 1'
  task task1: :environment do
    puts "Task 1"
  end
end
```

Then we run seed:

```console
rails db:seed
/Users/e12e/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/tasks/statistics.rake:4: warning: already initialized constant STATS_DIRECTORIES
/Users/e12e/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/railties-8.0.1/lib/rails/tasks/statistics.rake:4: warning: previous definition of STATS_DIRECTORIES was here
Task 1
```

### Expected behavior
Should be able to invoke tasks without warning.

### Actual behavior
See above

### System configuration
**Rails version**: 8.0.1

**Ruby version**: 3.3.6

### Other notes

Hit this when upgrading from rails 7.2 to 8. We found it because we load seeds in our tests,
and our seeds.rb calls various seed tasks.

It seems to stem from:

Issue: #20510 fix: https://github.com/rails/rails/pull/21022/files#diff-a842f1d305b90875696271f71637d86d703e4cb4ee2464a5bfab86a5331ab12fR15

In particular:
```ruby
# railties/lib/rails/tasks.rb
require 'rake'

# Load Rails Rakefile extensions
%w(
  annotations
  framework
  initializers
  log
  middleware
  misc
  restart
  routes
  tmp
).tap { |arr|
  # This apparently is true, meaning that statistics is loaded twice?
  arr << 'statistics' if Rake.application.current_scope.empty?
}.each do |task|
  load "rails/tasks/#{task}.rake"
end
```

I'm not sure what would be a reasonable fix, because I don't quite understand what/how stats work.

**Comment by mohsen-alizadeh** [comment]
You are running a rails command `rails db:seed` which is trying to run another rails command `Rails::Command.invoke 'task:task1'`.

It is clear that it would load the tasks twice.

The right way triggering it this way:

```ruby
Rake::Task['task:task1'].invoke
```

**Comment by ngobin** [comment]
Thank you for the pointer on this! We also encountered this warning after upgrading from 7.2 -> 8.0, and based on this thread traced it to a call to `Rails.application.load_tasks` in a test setup for a Minitest test suite that invoked some tasks. Changing the line in setup to `Rails.application.load_tasks unless defined?(Rake::Task)` prevented the warning. Like you, I'm curious why we didn't get it in 7.2!

**Comment by espen** [comment]
`Rails.application.load_tasks unless defined?(Rake::Task)` doesn't work for me. It results in error `Don't know how to build task` when invoking rake tasks.

Running the test suits requires Rakefile which does `load_tasks` yet I still have to explicitly set it in `test_helper.rb`. Which then results in this error of `already initialized constant STATS_DIRECTORIES`
