### ISSUE TITLE
DirectUploads breaking on rails 8

### ISSUE THREAD

**Issue by juanxcerv** [rails/rails#54001]
### Steps to reproduce
We're using DirectUpload for file attachments. 
We've identified a specific [commit](https://github.com/rails/rails/commit/42d75ed3a8b96ee4610601ecde7c40e9d65e003f) that is causing an issue inside of `node_modules/.pnpm/activestorage@5.2.8/node_modules/activestorage/app/assets/javascripts/activestorage.js`

Specifically the response we get inside of `requestDidLoad` no longer responds to `response.direct_upload`
It seems like this is happening due to `direct_upload` becoming `directUpload` in the new response data. 

### Expected behavior
Response should look like this
![image](https://github.com/user-attachments/assets/c81e15fa-32b4-48aa-9663-9346924b873f)
like it does on Rails 7.2.2.1

### Actual behavior
Instead it looks like this

![image](https://github.com/user-attachments/assets/13222d08-f4bf-46ab-a29c-c6a81c59b8f0)
and no longer responds to `response.direct_upload`
![image](https://github.com/user-attachments/assets/7a1e31e0-96b9-4c14-9a15-e38cf0130b21)
, which it is still attempting to do on line 584: `var direct_upload = response.direct_upload;` of 
`node_modules/.pnpm/activestorage@5.2.8/node_modules/activestorage/app/assets/javascripts/activestorage.js`

### System configuration
**Rails version**: 8.0.0.1

**Ruby version**: 3.3.6

**Comment by skipkayhil** [comment]
You should match the version of `@rails/activestorage` with your Rails version. Does this issue still occur with `@rails/activestorage` `8.0.0.1?

**Comment by maddieholtzer** [comment]
Thank you @skipkayhil! this appears to have been the issue. We had the most recent version of `@rails/activestorage` but we realized that we had actually never migrated onto it and were still using the quite old `activestorage`. This issue can be closed out.
