### ISSUE TITLE
Incorrect enum reported as error

### ISSUE THREAD

**Issue by bchellingworth** [rails/rails#54038]
### Steps to reproduce

Create a model and add 2 enum definitions:

In this example, the second definition fails because 'none?' is already defined as an instance method, however when I try to load this model in the console, it tells me that the error is the first enum definition 'monthly?' that is already defined.

```
class Organization < ApplicationRecord

	enum :billing_cycle, { monthly: 0, quarterly: 1, yearly: 3 }
	enum :credit_type, { none: 0, fixed: 1, percentage: 3 }
	
end
```

### Expected behavior

The error should tell me that the :credit_type enum is the problem with the value 'none'

### Actual behavior

<class:Organization>': You tried to define an enum named "billing_cycle" on the model "Organization", but this will generate a instance method "monthly?", which is already defined by another enum. (ArgumentError)

The error reports that the billing_cycle enum is the problem with the value 'monthly'

### System configuration
**Rails version**: 8.0.0

**Ruby version**: 3.2.5

**Comment by fatkodima** [comment]
Can you provide a reproduction test script using https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb template?

**Comment by kiku1705** [comment]
I tried the below script and it is failing with the correct error 

```
.rvm/gems/ruby-3.2.5/gems/activerecord-8.0.0/lib/active_record/enum.rb:389:in `raise_conflict_error': You tried to define an enum named "credit_type" on the model "Oraganization", but this will generate a class method "none", which is already defined by Active Record. (ArgumentError)
```

```require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", '8.0.0'
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record/railtie"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
  config.secret_key_base = "secret_key_base"
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :oraganizations, force: true do |t|
    t.integer :billing_cycle
    t.integer :credit_type
  end
end

class Oraganization < ActiveRecord::Base
  enum :billing_cycle, { monthly: 0, quarterly: 1, yearly: 3 }
	enum :credit_type, { none: 0, fixed: 1, percentage: 3 }
end

class BugTest < ActiveSupport::TestCase
  def test_association_stuff
    Oraganization.create(billing_cycle: 0, credit_type: 0)
  end
end
```
@bchellingworth do i need to add something else.

**Comment by bchellingworth** [comment]
Hi, I ran the test script and it worked ok, i got the correct error, but when I run it using rails console I get the wrong error (see attachment). No idea what the difference is i'm afraid.
![Your paragraph text](https://github.com/user-attachments/assets/b6e84eaf-f83b-4252-83a3-ab658621426a)

**Comment by nvasilevski** [comment]
😕 
It's really hard to even come up with a guess without being able to reproduce the error. But perhaps let's guess `monthly?` error is somehow correct, could you check `Organization.instance_method(:monthly?)` Perhaps some other gem defines it even though you have basically no modules included 😕 

But eventually you may need to jump into the rails source and set a debugger or some `puts` statements around here 
https://github.com/rails/rails/blob/6dda150b5e4cd25c6af76b99fe9a5c5986691e05/activerecord/lib/active_record/enum.rb#L399

**Comment by bchellingworth** [comment]
Thanks for responding @nvasilevski 

I tried to debug further but I wasn't able to come up with anything useful.

I have created a fresh rails project, everything default (I chose API mode to lighten the load). All I have done is create the model and added the enums

[https://github.com/bchellingworth/rails_enum_reporting_error](url)

If you just run the rails console and do something like `org = Organization.new` you should see the problem.

Let me know if I can help in anyway or if I can provide any more info.

Thanks

**Comment by bchellingworth** [comment]
Interestingly, if you declare the erroneous enum first, then it reports it correctly, I wonder if this is simply a race condition with it printing to the console? perhaps I/O needs flushing?

**Comment by fatkodima** [comment]
I installed the repro app and get the correct error
```
enum(dev)> org = Organization.new
app/models/organization.rb:3:in `<class:Organization>': You tried to define an enum named "credit_type" on the model "Organization", but this will generate a class method "none", which is already defined by Active Record. (ArgumentError)
```

for bad `"none"` value.

**Comment by nvasilevski** [comment]
>I wonder if this is simply a race condition with it printing to the console? 

You may want to remove the console out of the question by for example setting `eager_load=true` and just booting the server
https://github.com/bchellingworth/rails_enum_reporting_error/blob/93827a67da0d3f03103e32932473c1e22eae479a/config/environments/development.rb#L10

or running something like `bundle exec rails runner 'Organization.new'`

**Comment by bchellingworth** [comment]
Ok, I guess this is just an issue I'm experiencing and not a wider problem. Thanks for the help everyone.
