### ISSUE TITLE
Small typo in "Getting Started" Rails Guide

### ISSUE THREAD

**Issue by aavina** [rails/rails#54044]
### Steps to reproduce
Typo found on this line - https://github.com/rails/rails/blob/main/guides/source/getting_started.md?plain=1#L615

`let'` should be `let's`

# Your reproduction script goes here
N/A

### Expected behavior
```
need to manually refresh it. So let's do this now by running 'reload!'.
```

### Actual behavior
```
need to manually refresh it. So let' do this now by running 'reload!'.
```

### System configuration
N/A

**Comment by nvasilevski** [comment]
Would you like to open a PR? This is a good opportunity for a contribution

**Comment by kiku1705** [comment]
created a PR https://github.com/rails/rails/pull/54048 to fix this, @aavina if you would like to open a PR, please go ahead. Thank you.
