### ISSUE TITLE
set_callback raise ArgumentError if used SymbolProc

### ISSUE THREAD

**Issue by Roriz** [rails/rails#54056]
### Steps to reproduce
```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "sqlite3"
end

require "active_record/railtie"
require "minitest/autorun"

# This connection will do for database-independent bug reports.
ENV["DATABASE_URL"] = "sqlite3::memory:"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)
  config.secret_key_base = "secret_key_base"
end
Rails.application.initialize!

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :title
  end
end

class Post < ActiveRecord::Base
  def do_something
    puts "do_something"
  end

  def run_callback?
    true
  end
end

Post.set_callback(:update, :before, :do_something, if: proc(&:run_callback?)) # raise ArgumentError
# Post.set_callback(:update, :before, :do_something, if: lambda(&:run_callback?)) # raise ArgumentError
# Post.set_callback(:update, :before, :do_something, if: ->(p) { p.run_callback? }) # all fine
# Post.set_callback(:update, :before, :do_something, if: :run_callback?) # all fine

class BugTest < ActiveSupport::TestCase
  def test_association_stuff
    post = Post.create!(title: "Example")

    assert_nothing_raised do
      post.update!(title: "Updated Title")
    end
  end
end
```
### Expected behavior
After setting a callback with lambda or proc, it should not run with any syntax provided by Ruby.

### Actual behavior
If we use the short syntax with proc(:method_name) or lambda(:method_name), it raises an error "no receiver given".
Since RuboCop has a rule to encourage use of SymbolProc when possible, the error can occur more frequently: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/SymbolProc

### System configuration
Rails version: 8.0.1
Ruby version: 3.3.0

**Comment by fatkodima** [comment]
This is some weird syntax. You need to really simply use
```ruby
Post.set_callback(:update, :before, :do_something, if: :run_callback?)
```

**Comment by Roriz** [comment]
> This is some weird syntax. You need to really simply use
> 
> ```ruby
> Post.set_callback(:update, :before, :do_something, if: :run_callback?)
> ```

There are some workarounds to resolve this issue, and one of them is what you described.

However, using a lambda is not wrong; it is even the recommendation in the RDoc for the method: https://github.com/rails/rails/blob/main/activesupport/lib/active_support/callbacks.rb#L696.

I believe Rails should support both cases, whether it’s a fully described lambda or a symbolProc, which we frequently use in Rails.

**Comment by nvasilevski** [comment]
I agree that uses of `proc(&:run_callback?)` or `lambda(&:run_callback?)` are not very convincing alongside much cleaner `if: :run_callback?` syntax. So perhaps what rails could do is to provide a better error message asking to use the symbol-based syntax. At the same time it could be a linter's job to recommend switching to a cleaner alternative while Rails should support lambdas/procs of any arity 😕 

It's not a strong opinion but I somehow want to claim that adding support for this syntax isn't obviously justified while comes at a small maintenance cost with no benefit to the end user

**Comment by Roriz** [comment]
I completely agree with improving the error message. If implemented, it could have saved countless hours debugging last month. I’m happy to make this change if we agree it’s the best approach.

However, I still believe the use of proc(&:run_callback?) should be supported, as it is a native Ruby syntax. It doesn’t make much sense to have only parts of Rails work with this syntax, like ActiveRecord, while others raise an error or ignore it. If we need to discuss the maintenance, we should talk about the new syntax with just method name: `:run_callback?`. While that approach is simpler, it isn’t native to Ruby.

I’ve already created a PR to support the arity, and it look like was not that much changes: https://github.com/rails/rails/pull/54064.
