### ISSUE TITLE
Fix Broken API Documentation Link in Rails v2.3 Action Controller Guide

### ISSUE THREAD

**Issue by sumit-jr** [rails/rails#54079]
### Steps to Reproduce
1. Visit the Rails guide page: [Action Controller Overview](https://guides.rubyonrails.org/v2.3/action_controller_overview.html#session).
2. Navigate to the section **6.2 Other Ways to Use Filters**.
3. Click on the link provided for more information on using filters: [Rails API Documentation](https://edgeapi.rubyonrails.org/classes/ActionController/Filters/ClassMethods.html).

### Expected Behavior
The link should redirect to the relevant Rails API documentation page that provides detailed information on using filters in Action Controller.

### Actual Behavior
The link is broken and does not redirect to a valid page. Instead, it results in a **404 error** or a "page not found" message.

### System Configuration
- **Rails version**: 2.3 (as per the guide)
- **Ruby version**: N/A (not relevant to this issue)

---

### Additional Information
The broken link appears to be due to the outdated version of the Rails guide (v2.3). The `edgeapi.rubyonrails.org` domain is likely no longer in use or has been replaced by a newer documentation system. It would be helpful to update the guide to point to the correct and current API documentation.

---

### Suggested Fix
Update the link in the Rails guide to point to the current API documentation. For example, the correct link for Rails 7.0 might be:  
[https://api.rubyonrails.org/v7.0/classes/ActionController/Filters/ClassMethods.html](https://api.rubyonrails.org/v7.0/classes/ActionController/Filters/ClassMethods.html)

**Comment by sumit-jr** [comment]
### Issue Description
The provided link references the Rails API documentation for version 2.3, which is outdated. Over time, the structure and availability of the Rails documentation have evolved, and older versions may no longer be accessible or may have been relocated.

---

### Steps to Resolve the Issue

1. **Access the Latest Documentation**  
   - Visit the [official Ruby on Rails API documentation](https://api.rubyonrails.org/).  
   - Navigate to the **Action Controller** section to find updated information on **Filters**.  

2. **Consider Upgrading to a Newer Rails Version**  
   - If feasible, update your project to a more recent version of Rails. Newer versions offer improved documentation, enhanced features, and better support.  

---

### Updated Link for Rails 2.3 Documentation
The updated link for the Rails 2.3 documentation is:  
[ActionController::Filters::ClassMethods (Rails 2.3)](https://api.rubyonrails.org/v2.3/classes/ActionController/Filters/ClassMethods.html#:~:text=Module%3A%20ActionController%3A%3AFilters%3A%3AClassMethods&text=Filters%20enable%20controllers%20to%20run,the%20intended%20action%20is%20performed.)

---

### Example Links to Latest Documentation
- [Action Controller Overview](https://guides.rubyonrails.org/action_controller_overview.html)  
- [Rails API Documentation](https://api.rubyonrails.org/)  

---

### Summary
The broken link is likely a result of the documentation for Rails 2.3 being outdated. To resolve this, you can access the latest documentation for up-to-date information. If you are working with Rails 2.3, upgrading to a more recent version is recommended for better support and access to updated resources.

**Comment by akhilgkrishnan** [comment]
@sumit-jr Here you're mentioning too older rails documentation, currently we are not maintaining older documentations ref: https://guides.rubyonrails.org/maintenance_policy.html
