### ISSUE TITLE
String#mb_chars causes warning with Ruby 3.4's frozen string warnings enabled

### ISSUE THREAD

**Issue by JasonBarnabe** [rails/rails#54076]
### Steps to reproduce

```ruby
> Warning[:deprecated]
=> false
> 'hi'.frozen?
=> false
> 'hi'.mb_chars
=> #<ActiveSupport::Multibyte::Chars:0x0000758c2a0c1558 @wrapped_string="hi">
> Warning[:deprecated] = true
=> true
> 'hi'.mb_chars
/home/jason/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/activesupport-8.0.1/lib/active_support/multibyte/chars.rb:58: warning: literal string will be frozen in the future (run with --debug-frozen-string-literal for more information)
=> #<ActiveSupport::Multibyte::Chars:0x0000758c23e50bf8 @wrapped_string="hi">
```

`String#mb_chars` initializes a `ActiveSupport::Multibyte::Chars`, which does `@wrapped_string.force_encoding(Encoding::UTF_8) unless @wrapped_string.frozen?`.

### Expected behavior
No warning.

### Actual behavior
Warning.

### System configuration
**Rails version**: 8.0.1

**Ruby version**: 3.4.1

**Comment by byroot** [comment]
Fixed and backported.

I'm curious though, is there a legitimate reason to use `.mb_chars` today? I was thinking of deprecating and removing it given it's mostly a relic from Ruby 1.8.x when strings had no encoding support.

**Comment by JasonBarnabe** [comment]
> I'm curious though, is there a legitimate reason to use `.mb_chars` today? 

I'm using it to limit a multi-byte string to a certain byte length without breaking characters.

```ruby
> "こにちわ".mb_chars.limit(3).to_s
=> "こ"
> "こにちわ".mb_chars.limit(4).to_s
=> "こ"
> "こにちわ".mb_chars.limit(5).to_s
=> "こ"
> "こにちわ".mb_chars.limit(6).to_s
=> "こに"
```
Though it looks like `String#truncate_bytes(3, omission: nil)` would do the same job.
