### ISSUE TITLE
Activerecord truncate method

### ISSUE THREAD

**Issue by fl00r** [rails/rails#5510]
Why there is no `truncate` method in ActiveRecord?

Could it be something like this?

    https://github.com/fl00r/rails/commit/8b9eacc0ed4b413fa518c3121b2a3807b07756b5

**Comment by simi** [comment]
@tenderlove I think this can be useful (for example in migration) and implemented (blank) in `ActiveRecord::ConnectionAdapters::SchemaStatements` (with with shortcut on `ActiveRecord::Base` (`self.connection.truncate!(table_name) ` for example).

I think I'm able to implement simple truncation for all standard adapters (including SQLite3 - see [The Truncate Optimization](http://sqlite.org/lang_delete.html)).

I can start this as a gem if there's not a final decision for this feature.

**Comment by matthewd** [comment]
9a4e183fe9f81365f7815c391512b3d46622d8c8

**Comment by simi** [comment]
thanks @matthewd, time to close

**Comment by matthewd** [comment]
Ah, yeah, I didn't look closely enough at the SQLite documentation you linked. I think we're probably better leaving it as it is now, instead of implementing `truncate` via `DELETE`, and risking unexpected behaviour on a table that has triggers.
