### ISSUE TITLE
ActiveRecord models based on a view create new instances with id = 0 rather than nil

### ISSUE THREAD

**Issue by stevenchanin** [rails/rails#5982]
Given a model like:

```
class Manufacturer < ActiveRecord::Base
  attr_accessible :name

  self.table_name = 'v_manufacturers'
  self.primary_key = 'id'
end
```

when you create a new instance

```
m = Manufacturer.new(name: 'Nissan')
# => #<Manufacturer id: 0, name: "Nissan">
```

but the id should be nil.

For a test case with tests (1.9.3 @ rails 3.2), see

```
https://github.com/stevenchanin/view_test
```

**Comment by eddiej** [comment]
The reproduction above that closed the issue uses the sqlite3 adapter. The original test case, using the mysql2 adapter, is still failing. @stevenchanin did you manage to resolve this in another way?

**Comment by senny** [comment]
@eddiej just ran my test-case using `mysql2` against `master` and it passes:

```ruby
ActiveRecord::Base.establish_connection(adapter: 'mysql2', database: 'test123')
```

Can you reproduce the error modifying my gist?

**Comment by stevenchanin** [comment]
@eddiej I'm sorry, but I don't recall. This problem came up with a project to replace a PHP site with Rails. Ultimately, we got all the PHP code retired, switched to real tables (not views) that followed Rails naming conventions and then it was no longer an issue.

**Comment by kevinkaske** [comment]
I have reproduced the error with the mysql2 adapter: https://gist.github.com/kevinkaske/60dae38ffc386beb5099

I changed the field in the view from manufacturer_id to id and then run a test to make sure the id is > 0

**Comment by eddiej** [comment]
@senny if you create the Manufacturers table with an id primary key, and create the view to select this id (instead of using manufacturer_id), the test cases fail using the mysql2 adaptor. I'll post a gist shortly.

**Comment by stevenchanin** [comment]
@eddiej Nice job creating such a clean & simple test.

**Comment by senny** [comment]
@eddiej I'll have a look.

**Comment by senny** [comment]
@eddiej I was able to reproduce the issue. It's due to the fact that the model based on the view has a `Column` object with `default=0`. However digging deeper I found that this is what MySQL reports about the view. See the following snippet from the MySQL-CLI:

```
mysql> SHOW FULL FIELDS FROM Manufacturers;
+-------------------+--------------+-----------------+------+-----+---------+----------------+---------------------------------+---------+
| Field             | Type         | Collation       | Null | Key | Default | Extra          | Privileges                      | Comment |
+-------------------+--------------+-----------------+------+-----+---------+----------------+---------------------------------+---------+
| id                | int(11)      | NULL            | NO   | PRI | NULL    | auto_increment | select,insert,update,references |         |
| manufacturer_name | varchar(255) | utf8_unicode_ci | YES  |     | NULL    |                | select,insert,update,references |         |
+-------------------+--------------+-----------------+------+-----+---------+----------------+---------------------------------+---------+
2 rows in set (0.00 sec)

mysql> SHOW FULL FIELDS FROM v_manufacturers;
+-------+--------------+-----------------+------+-----+---------+-------+---------------------------------+---------+
| Field | Type         | Collation       | Null | Key | Default | Extra | Privileges                      | Comment |
+-------+--------------+-----------------+------+-----+---------+-------+---------------------------------+---------+
| id    | int(11)      | NULL            | NO   |     | 0       |       | select,insert,update,references |         |
| name  | varchar(255) | utf8_unicode_ci | YES  |     | NULL    |       | select,insert,update,references |         |
+-------+--------------+-----------------+------+-----+---------+-------+---------------------------------+---------+
2 rows in set (0.01 sec)
```

I don't think this is something that Active Record should thinker around. It's behaving as the database tells it to.

**Comment by GerryG** [comment]
This isn't fixed for 3.2.x, is it?

**Comment by senny** [comment]
@GerryG it's not. Also note that `3.2.x` is no longer supported by the Rails team.

**Comment by GerryG** [comment]
I understand these versions are not under active support, but I was at least hoping there was a user patch or something.  Seems like that would be hard and not worth it, so we may have to forgo using the view altogether.

Just to clarify, there is a way to handle it in some rails 4 version? That may be something we could do, but not immediately. It seems like the fact that mysql reports the column as default: 0 on the view would need to be fixed in mysql specific code. Is that so?

**Comment by GerryG** [comment]
It isn't clear to me from the comments if this is fixed in any version of rails.

**Comment by jonatanklosko** [comment]
Hi, we've experienced this in our project recently and hopefully I've found an easy fix. We use MySQL and [senny's comment](https://github.com/rails/rails/issues/5982#issuecomment-138231374) was the start point for solving this, thanks =). For details see the comment [here](https://github.com/jonatanklosko/worldcubeassociation.org/blob/efb7e27875650c6e909e4254f56eefec1cb69b7e/WcaOnRails/app/models/person.rb#L58-L63).

**Comment by guilleiguaran** [comment]
This still happening as Active Record 5 + MySQL when trying to work with models backed by views.

I'm using this as a workaround:

```ruby
before_create -> { self.id = nil }
```
