### ISSUE TITLE
Rails 3.2.5 Regression: incorrect _changed? for datetimes

### ISSUE THREAD

**Issue by earnold** [rails/rails#6591]
I just upgraded from 3.2.2 to 3.2.5, and now I have failing specs. I've identified the problem as this. 

When you have this model: 
```rails
  create_table "posts", :force => true do |t|
    t.string   "title"
    t.datetime "published_at"
  end
```

previously you could do: 

    1.9.3p125 :013 >p = Post.last
    1.9.3p125 :014 > p.published_at = p.published_at
    1.9.3p125 :015 > p.changed?
    => false 

but now: 

    1.9.3p125 :013 >p = Post.last
    1.9.3p125 :014 > p.published_at = p.published_at
    1.9.3p125 :015 > p.changed?
    => true 
    1.9.3p125 :006 > p.changes
     => {"published_at"=>[Thu, 12 Apr 2012 19:32:33 UTC +00:00, Thu, 12 Apr 2012 19:32:33 UTC +00:00]} 

I'm going to see if I can put together a failing test around this.

**Comment by luxflux** [comment]
Me too, Rails 4.1.11.

**Comment by mintuhouse** [comment]
I am able to reproduce it on 4.1.13
using postgres and passing the time from browser as string in format "2015-12-30 4:58 PM"

**Comment by benbartling** [comment]
I'm also having this issue. Rails 4.2.3

**Comment by maclover7** [comment]
Is this an issue on master?

**Comment by rafaelfranca** [comment]
Until we have reproduction steps and confirmation that the issue is really present in recent versions we should keep it closed.
