### ISSUE TITLE
ActiveRecord::SchemaDumper removes prefixes and suffixes when ignoring tables.

### ISSUE THREAD

**Issue by marcelokanzaki** [rails/rails#9015]
When I have the following in my database:

- some_table
- my_prefix_some_table

and configure `ActiveRecord::SchemaDumper.ignore_tables = ["some_table"]`

The SchemaDumper ends up ignoring **both tables**, because it removes prefixes and suffixes before comparing tables names with the elements in the supplied array.

The result is that I never get the chance to ignore just one or the other table.

**Comment by nerdinand** [comment]
I tried to reproduce this on `master`. It does not seem to be a problem anymore. See this test case:
https://gist.github.com/nerdinand/d67739425cd56c5427b4

**Comment by timbreitkreutz** [comment]
I noticed this old ticket and did a bit of investigation.

1. Like @nerdinand I verified that the bug no long seems to exist in master.
2. I converted his test case gist to a unit test in `schema_dumper_test.rb` and packaged it into PR #22271.

If folks agree I suggest we merge in the test case and close this ticket...

**Comment by timbreitkreutz** [comment]
This was fixed in https://github.com/rails/rails/commit/e23ec4c79c7f402f3d306771616c1d597132e2fa
