### ISSUE TITLE
Rake db:fixtures:load - can't set fixture_class_name.

### ISSUE THREAD

**Issue by jacobstr** [rails/rails#9516]
I have a many to many relation using a through table:

```ruby
class User < ActiveRecord::Base
  has_many :badges, :through => :users_badges 
end

class UsersBadges < ActiveRecord::Base
  belongs_to :user
  belongs_to :badge
  belongs_to :badgesource, :polymorphic => true
end

class Badge < ActiveRecord::Base
  attr_accessible :points, :description
  has_many :users, :through => :users_badges
end
```

And a fixtures file named `users_badges.yaml` inside of test/fixtures.

The first issue was really that it was recognizing the class name for my UsersBadges model as UsersBadge ( which I'm not sure is correct - I couldn't find documentation on this).

So - the workaround was to add `set_fixture_class` before the fixtures are loaded inside of test_helper.rb

Unfortunately, this only works in the test context. It's nice to interact with the fixtures in the console but running rake:db:fixtures:load does the same naming conversion translation. 

When it gets the class name wrong, it doesn't correctly grok the fixture file. My fixtures are related using labels. The SQL insert statement isn't adjusted to use ids and I get:

table `users_badges` has no column named user: 

```sql
INSERT INTO "users_badges" ("user", "badge", "badgesource") VALUES ('user1', 'mood_badge', 'rocking_out (Generic)').
```

The relevant code is around `lib/active_record/fixtures.rb:492`

**Comment by repinel** [comment]
Why trying to duplicate the issue using `master`, I didn't have any SQL problem. However, the fixture were not properly loaded into the database.

My [sample app](https://github.com/repinel/my_app/tree/set-fixture) has the following models:

```ruby
class Post < ActiveRecord::Base
  self.table_name = 'records'
  has_many :comments
end

class Comment < ActiveRecord::Base
  belongs_to :post
end
```

And `schema.rb`:
```ruby
  create_table "comments", force: :cascade do |t|
    t.string   "content"
    t.integer  "post_id"
  end

  create_table "records", force: :cascade do |t|
    t.string "title"
  end
```

`records.yml`:
```yaml
one:
  title: foo
```

`comments.yml`
```yaml
great:
  content: 'great'
  post: one
```

You may check by the app tests that the fixtures load fine for the tests having `set_fixture_class records: Post` in the `test_helper.rb`.

@senny What's your opinion on having something like a `mapping.rb` file on `fixtures` directory that would holder the `set_fixture_class` statements make it easier to share that with the `db:fixtures:load`? One other option could be having the class name defined in the fixture itself with something like `CLASS_NAME` and being ignored just like is done for `DEFAULTS`.

**Comment by senny** [comment]
Backtracking in the git history it looks like ada11d6313bd1f74c6a229caca36ca063b38da4e was the origin of `set_fixture_class`. I still feel like this configuration is directly related to the fixture and not the TestCase (the way it's currently implemented).

If that's the case (maybe @jeremy can elaborate more about the origin) I think we could make the configuration accessible directly in the fixture file itself. Something along the lines of:

```yaml
<% set_fixture_class "Book" %>

one:
  title: "Odyssey"

two:
  title: "Ulysses"
```

**Comment by trak3r** [comment]
I'm getting bit by this now as well.

I agree with @senny sentiment, "feel like this configuration is directly related to the fixture and not the TestCase" and also his suggestion for the declaration in the fixture file.

**Comment by senny** [comment]
with #20574 merged Rails 5 will allow you to configure the fixture class directly in the YAML file:

*test/fixtures/accounts.yml*
```yaml
_fixture:
  model_class: User
david:
  name: David
```
