### ISSUE TITLE
Multiple accept headers' specificity is misinterpreted

### ISSUE THREAD

**Issue by ekampp** [rails/rails#9940]
The HTTP standard clearly states that higher specificity mime-types should take precedence, when multiple mimetypes is supplied. This is not the case with the current version of rails (cloned of master branch).

    curl http://localhost:3000/entries --header "Accept:application/json, text/plain"

should return json, and in fact does so. While

    curl http://localhost:3000/entries --header "Accept:application/json, text/plain, */*"

should still return json, since the `*/*` is less specific, but this returns html.

Here is [a test application](https://github.com/ekampp/accept-header-specificity-test) where this can be tested.

**Comment by demsullivan** [comment]
I'm not seeing this issue happen in Rails 4.2.1 - even with `Accept: application/json, text/javascript, */*` Rails will respond with JSON.

However, when using CORS, it breaks.

Starting from a plain Rails project, I have the following in my `ApplicationController`:
```
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  def cors_preflight_check
    if request.method == 'OPTIONS'
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version, Token'
      headers['Access-Control-Max-Age'] = '1728000'

      render :text => '', :content_type => 'text/plain'
    end
  end
```

And in my `ProductsController`:

```
class ProductsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { render json: {msg: "it worked"} }
    end
  end
end
```

Issuing `$.ajax('/products')` from `http://localhost:3000/` sends `Accept: */*` and Rails responds with HTML.

Issuing `$.ajax({url: 'products', dataType: 'json'})` from `http://localhost:3000/` sends `Accept: application/json, text/javascript, */*` and Rails responds with JSON.

That's fine.

Now from any other domain:

Issuing `$.ajax('http://localhost:3000/products')` from any other domain sends `Accept: */*` and Rails responds with HTML.

Issuing `$.ajax({url: 'http://localhost:3000/products', dataType: 'json'})` from any other domain sends `Accept: application/json, text/javascript, */*` and Rails responds with **HTML** when it should respond with **JSON**.

**Comment by LTe** [comment]
Hi @demsullivan! I think issue only appear when you make **non-ajax** HTTP request (like API does) with application/json accept header.

**Comment by djpate** [comment]
I have the same issue as @demsullivan (on 3.2.8). 
@LTe not sure what you mean by non-ajax request. 
Are CORS Ajax not considered ajax?

**Comment by ekampp** [comment]
@demsullivan I believe you're right. But this is also quite an old issue. And they removed the implicit mime-type response out of Rails, and into the `responders` gem. So in your example you're explicitly responding with json.

**Comment by ekampp** [comment]
I have updated the initial example to rails 4.2.3, which supports the results found by @demsullivan

**Comment by jcoyne** [comment]
This is still an issue. If `*/*` is present in the Accept header, it will skip content negotiation, even if more suitable mime-types precede the `*/*`

**Comment by josevalim** [comment]
We unfortunately still have browsers to thank for this behaviour. In IE10 (iirc), any software installed on your system can still prepend something to the accepts query. In other words, we cannot trust accept headers if they have */* in them because chances would be that you would serve the wrong page for anyone running on IE.

**Comment by jcoyne** [comment]
IE10 is EOL as of January and has less that 3.4% according to netmarketshare.com.  Shouldn't Rails be concerned about the API use case? It's important to me that I give my clients the best matching content, rather than something that is merely adequate for them: `*/*`

**Comment by josevalim** [comment]
It is IE10 and older, which means we are looking at least at 15% market share. I haven't checked if they finally fixed the issue on IE11.

**Comment by kreynolds** [comment]
What exactly is the accept header causing bad behavior that we're concerned about? When I went through the various browsers previously, everything seemed to Do The Right Thing™. Is our problem here when :format is unspecified, the browser prefers XML over HTML, and the endpoint implements both XML and HTML?

**Comment by bradgessler** [comment]
We ran into this problem and wrote a middleware that rewrites the headers to deal with Internet Explorer mime type issues. I just pulled this chunk of code out of our rails repo, MIT licensed it, and am sharing it with you at https://gist.github.com/bradgessler/0958e3f8a17c358263c5. Feel free to use that in your own project (or better yet turn it into a gem to share with the rest of the community and post al link on here).

Overall I believe this should belong in a middleware and should not be a rails core team concern.

**Comment by jcoyne** [comment]
@bradgessler Nice work. I too prefer that approach.

**Comment by kreynolds** [comment]
@bradgessler I agree, rails core should behave correctly and any goofiness belongs elsewhere.

**Comment by david50407** [comment]
Still can re-produced on Rails 5.0.0.1.

Requests with header `Accept: x-any-type/x-any-subtype, */*` has been rewrited as `text/html` here (`ActionDispatch::Http::MimeNegotiation`):

https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L77
https://github.com/rails/rails/blob/v5.0.0.1/actionpack/lib/action_dispatch/http/mime_negotiation.rb#L159

It's very annoying while using api-mode with requesting `Accept: application/json, */*` and return 406 (not acceptable).

**Comment by kreynolds** [comment]
As a reminder, I have this and several other issues fixed in #14540. I'd be happy to spend the time updating it to merge it cleanly into the main branch if I knew that rails core would accept it. There is no need for a separate gem or middleware or any nonsense like that, the parsing just needs to be correct.

**Comment by mb21** [comment]
Cannot believe this is still not fixed in Rails 5.0.6. The following doesn't return JSON:

    curl 'http://localhost:3000/article/1' -H 'Accept: application/json, */*'

with this in the controller:

    respond_to do |format|
      format.html { render }
      format.json { render json: @article }
    end

**Comment by david50407** [comment]
I monkey-patched `ActionDispatch::Http::MimeNegotiation`, to skip browser-like accepts check:

```ruby
# This monkey patch applies to:
#     Rails acts '*/*' in multi-accept types as 'text/html' directly.
# Related to: https://github.com/rails/rails/issues/9940
ActionDispatch::Http::MimeNegotiation.send :remove_const, :BROWSER_LIKE_ACCEPTS
ActionDispatch::Http::MimeNegotiation.const_set :BROWSER_LIKE_ACCEPTS, /NEVER_MATCHED_MIME_TYPE_LOL/
```

**Comment by ekampp** [comment]
@mb21 there's no need to reopen this issue. The bug is confirmed -- also by core team members. There is already a branch that fixes this problem, which is open: #14540

**Comment by mb21** [comment]
@ekampp  I assumed issues would be closed only when they are fixed in master, i.e. when the branch that fixes the bug is merged? Would love to see #14540 merged, but it's been there since 2014 :S

**Comment by ekampp** [comment]
Yep, and this issue has been here since 2013. Don't get your hopes up 😉

**Comment by celesteking** [comment]
Stumbled across the same issue. Why all the talk? Why not just provide a knob that would allow switching it off the hacks? You can keep it on by default for compatibility.

**Comment by kreynolds** [comment]
If I got a commitment from the core team they would actually merge this in, I'd be happy to rebase it for master, maybe voting on #14540 would get their attention?

**Comment by bradgessler** [comment]
If somebody has time and doesn’t want to wait for core team to respond, use my code above from https://github.com/rails/rails/issues/9940#issuecomment-182630629 to make a gem (additional config options would be nice), and release.

**Comment by phoet** [comment]
this is only partially related, but it was the best search result i got, so...

we see some requests with broken accept-headers to our application that raise mime errors

```
Mime::Type.parse("text/html,application/xhtml+xml,application/xml;q=0.9,\\*\\/\\*;q=0.8")
# => Mime::Type::InvalidMimeType ("\\*\\/\\*" is not a valid MIME type)
```

is there a way to tell rails to ignore this instead of exploding into the users face?

**Comment by ekampp** [comment]
@phoet, perhaps this is of some use to you: https://stackoverflow.com/a/12993197/1146473
